### ISSUE TITLE
I'm trying to Install the beta version of flutter to enable web development.

### ISSUE THREAD

**Issue by vamsi452** [flutter/flutter#61734]
Tried flutter channel beta

Error message: git: fatal: 'origin/beta' is not a commit and a branch 'beta' cannot be created from it
Switching channels failed with error code 128.

Please help! Thank you

![Screen Shot 2020-07-17 at 11 00 43 AM](https://user-images.githubusercontent.com/14830149/87806876-247d0000-c81d-11ea-8f0b-8f720d48515f.png)

**Comment by VrajGohil** [comment]
https://dev.to/adityasingh20/small-issue-solution-in-flutter-5073

Check if this helps.

**Comment by vamsi452** [comment]
@VrajGohil 
Thank you for your response. I tried that 

"git remote add origin https://github.com/flutter/flutter"
Result is :
fatal: remote origin already exists.

**Comment by VrajGohil** [comment]
> @VrajGohil
> Thank you for your response. I tried that
> 
> "git remote add origin https://github.com/flutter/flutter"
> Result is :
> fatal: remote origin already exists.

Related issue #53231

**Comment by VladyslavBondarenko** [comment]
Hi @vamsi452 
have you downloaded flutter from https://flutter.dev/docs/development/tools/sdk/releases?
or what way have you cloned the repository?
is https://github.com/flutter/flutter/issues/15134#issuecomment-636563676 your case?
could you provide your `flutter doctor -v`?

**Comment by vamsi452** [comment]
<img width="586" alt="Screen Shot 2020-07-22 at 1 31 19 PM" src="https://user-images.githubusercontent.com/14830149/88214341-a3a87480-cc1f-11ea-8e6d-d3b0c3cf52cb.png">
@VladyslavBondarenko  Please find the attached flutter doctor. Thank you!

**Comment by VladyslavBondarenko** [comment]
@vamsi452 does the error persist? could you answer other questions from above?

**Comment by issyrael** [comment]
Same issue as above for me as well. What was the walk around?

**Comment by issyrael** [comment]
Here is a work around that worked for me in installing the Master channel.

1. I created a new folder away from my previous flutter folder
2. Cloned master: git clone -b master https://github.com/flutter/flutter.git      (Make a note of the path to this location)
3. run this command (Downloads Dart SDK): ./flutter/bin/flutter --version
4. Make the newly cloned channel the primary: 
export PATH="$PATH:[Type in here the path to the newly downloaded version]/flutter/bin"
5. run: source $HOME/.zshrc or source $HOME/.bashrc
6. run to confirm success: echo $PATH
7. run: flutter doctor -v  

DONE!

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
