### ISSUE TITLE
[linux] After upgrade to beta channel,   commands get stuck at "Waiting for another command to release the startup lock"

### ISSUE THREAD

**Issue by huybanh** [flutter/flutter#61739]
## Steps to Reproduce

1. Extract flutter with tar
2. Run "flutter channel beta"

After this, can't run "flutter upgrade", "flutter doctor" or any other flutter commands

## Logs

flutter channel beta
Switching to flutter channel 'beta'...
git: Switched to a new branch 'beta'
git: Branch beta set up to track remote branch beta from origin.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

flutter doctor
Waiting for another flutter command to release the startup lock...

Tried deleted the lockfile at flutter/bin/cache/lockfile, or the whole cache folder, killed processes or shutdonw/start pc again (linux), didn't help

**Comment by TahaTesser** [comment]
Hi @huybanh 
Can you please try `flutter doctor -v`, and give the complete output. Also please more details about what Linux you using?. From which  exact version of Flutter you've switched to `beta` channel
Thank you

**Comment by huybanh** [comment]
Linux info: (custom distro)

uname --kernel-name --kernel-release --machine
Linux 3.10.0-957.el7.raiseusblimit.x86_64 x86_64

cat /etc/os-release
NAME="Userful Linux"
VERSION="7.5.1804.20180510 (UEL)"
ID="userful centos rhel fedora"
ID_LIKE="rhel fedora"
VERSION_ID="7.5.1804.20180510"
PRETTY_NAME="Userful Linux El 7.5.1804.20180510 (UEL)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:userful:enterprise_linux:7.5.1804.20180510:GA"

**Comment by RatakondalaArun** [comment]
Hey @huybanh  can you try `flutter.bat doctor`
because I had the same issue using flutter command on *git bash on windows*
and also this issue seems similar to #58993 but on windows platform

**Comment by huybanh** [comment]
Hi @RatakondalaArun , I can't. Don't have Windows environment here.

**Comment by christopherfujino** [comment]
I'm sorry we didn't resolve this issue sooner. @huybanh are you still in this state? I believe we have refactored this logic since you filed this issue.

**Comment by huybanh** [comment]
We postponed this evaluation, not working on it now.

Thanks for your update.

**Comment by TahaTesser** [comment]
Hi @huybanh 
Given your last message I feel safe to close this issue, if you disagree/experience this issue again please write in the comments and I will reopen it. 
Thank you
