### ISSUE TITLE
flutter_gallery_v2_web_compile_test new_gallery_dart2js_size benchmark gradually increasing...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#61735]
I think this is probably expected. Rebaseline?

![Screen Shot 2020-07-17 at 9 05 53 AM](https://user-images.githubusercontent.com/1435716/87807126-bdefe600-c80c-11ea-87a9-6e48d23561e8.png)

**Comment by yjbanov** [comment]
Gradual increase in size is expected as Flutter accumulates new functionality. I did not rebaseline the dashboard as I'm unable to load the page. I'm also told that we have moved to Skia Gold where we do not need to rebaseline manually.
