### ISSUE TITLE
The UserAccelerometerEvent  are not received

### ISSUE THREAD

**Issue by eliaweiss** [flutter/flutter#61742]
Testing on Android release 9 (SDK 28), LENOVO Lenovo TB-X505F

The UserAccelerometerEvent  are not received, I checked with the debuger:

this is my code

  streamSubscription = userAccelerometerEvents.listen((UserAccelerometerEvent event) {
     print('imhere');

in 
  Stream<dynamic> receiveBroadcastStream([ dynamic arguments ]) {
    final MethodChannel methodChannel = MethodChannel(name, codec);
    StreamController<dynamic> controller;
    controller = StreamController<dynamic>.broadcast(onListen: () async {
      binaryMessenger.setMessageHandler(name, (ByteData reply) async {
        if (reply == null) {
          controller.close();
        } else {
          try {
            controller.add(codec.decodeEnvelope(reply));

The line `controller.add(codec.decodeEnvelope(reply));` is reachable but the line `_listToUserAccelerometerEvent(event.cast<double>())` in 

/// Events from the device accelerometer with gravity removed.
Stream<UserAccelerometerEvent> get userAccelerometerEvents {
  if (_userAccelerometerEvents == null) {
    _userAccelerometerEvents = _userAccelerometerEventChannel
        .receiveBroadcastStream()
        .map((dynamic event) =>
            _listToUserAccelerometerEvent(event.cast<double>()));
  }
  return _userAccelerometerEvents;
}

and also the 'imhere' message never get printed.

It seems that from some reason, the stream is not working on old devices.

I have a complicated scenario, where i capture images from the camera process them, and use the Accelerometer in the same time.

Initially I thought that Accelerometer is not available, so I run the code on startup and set a flag, but strangely the code works on startup.
 It breaks only when I use the camera in parallel.

I assume it is a memory issue.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@eliaweiss you seem to have open similar issue [61741](https://github.com/flutter/flutter/issues/61741).
Closing this as duplicate.
