### ISSUE TITLE
Keyboard automatically disappears from TextField in ListView.Builder

### ISSUE THREAD

**Issue by MdeBruin93** [flutter/flutter#61740]
I've followed https://bloclibrary.dev/#/flutterinfinitelisttutorial tutorial, but instead of a Text widget I'm using both a Text widget and a TextField widget. However as soon as I tap on one of the TextFields the keyboard appears and immediatly disappears again. I've tried to remove the key, however then all of the TextFields are updated whenever the keyboard appears.

The code can be found here: https://stackoverflow.com/questions/62952469/keyboard-automatically-disappears-from-textfield-in-listview-builder.

## Steps to Reproduce

Follow this tutorial https://bloclibrary.dev/#/flutterinfinitelisttutorial and instead of using Texts use both Texts and TextFields.

**Expected results:** 

A list of TextFields that can be updated individual.

**Actual results:** 

A list of TextFields whereas when I tap on one the keyboard appears and immediatly dissappears again.

**Comment by darrenaustin** [comment]
cc @justinmc

**Comment by justinmc** [comment]
@MdeBruin93 Nothing jumps out at me after a brief look.  Could you combine all of the code in your StackOverflow question into a single block that I can copy paste into a main.dart and run?

**Comment by MdeBruin93** [comment]
@justinmc 
I've attached a file that contains that code + some extras to make it compile (or atleast it should compile).
Just click on a TextField which should open up a keyboard, for me the keyboard immediately disappears again.

I'm using the latest Flutter stable release (v1.17.5).
[flutter issue.zip](https://github.com/flutter/flutter/files/4951757/flutter.issue.zip)

**Comment by markusaksli-nc** [comment]
Hi @MdeBruin93 
As far as I can tell the attached code should have these imports:
<details>
 <summary>Missing imports</summary>

 ```
import 'dart:convert';
import 'dart:io';

import 'package:equatable/equatable.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:http/http.dart';
import 'package:uuid/uuid.dart';
```
</details>

The code also contains an extra copy of the `CategoriesService` class and is missing a `GameCategoryItemWidget` and `LoadingIndicator` class, and `void main()`. There is also an unrecognized usage of `events.debounceTime`. What we need is a **minimally reproducible code sample** that demonstrates the issue.

Thank you

**Comment by MdeBruin93** [comment]
Hi @markusaksli-nc ,
I've rewritten the code from scratch with only a ListView.Builder on a stateless screen and it seems to be working perfectly now. Will strip the code from my app too to see what the real problem is.
I've added a short recording of the problem I'm facing.
[flutter issue.zip](https://github.com/flutter/flutter/files/4952734/flutter.issue.zip)

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
