### ISSUE TITLE
Cherry pick an update to the null safe flutter deps into the stable release.

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#61749]
The null safe versions pinned in the current pubspecs do not allow the stable 2.9.x Dart sdk, so we need to update to the latest versions in all pubspecs:

characters: 1.1.0-nullsafety.1
collection: 1.15.0-nullsafety.1
meta: 1.3.0-nullsafety.1
typed_data: 1.3.0-nullsafety.1
vector_math: 2.1.0-nullsafety.1

This needs to be cherry picked into the stable branch.

**Comment by pcsosinski** [comment]
@jakemac53 remind me if this has dependencies on the Dart version included in Flutter?  I am going to spin another beta build today, any reason not to pick it?

**Comment by leafpetersen** [comment]
@pcsosinski Any updates on this?

**Comment by jakemac53** [comment]
The expectation is that you should be able to cherry pick these at any time. You should not be blocked on anything upstream in the Dart sdk (its stated version or otherwise).

**Comment by pcsosinski** [comment]
@jakemac53 this isn't a commit to CP as much as a change directly on the branch right?  are you able to make that change and send it to me for review?  the branch is flutter-1.20-candidate.7

**Comment by jakemac53** [comment]
If it is easier we could do a normal cherry pick - flutter master channel can safely pin these deps as well right now. They allow both dev and stable versions of the 2.9 Dart sdk.

**Comment by pcsosinski** [comment]
whatever makes the most sense works for me.

**Comment by jakemac53** [comment]
Ok, I will work on a flutter PR,  you can choose to wait for that to land and cherry pick or just create an identical commit on top of the stable branch.

**Comment by jakemac53** [comment]
@a14n can you actually work on this? I can't figure out the flutter update packages script.

We want to make a PR that only updates the `-nullsafety`  versions so it can be cherry picked into stable (not update any other packages). I couldn't figure out any way to do that.

**Comment by a14n** [comment]
Checking out `flutter-1.20-candidate.7` I don't see `-nullsafety` dependencies. Is it the right branch to make the change?

**Comment by a14n** [comment]
>We want to make a PR that only updates the -nullsafety versions so it can be cherry picked into stable (not update any other packages). I couldn't figure out any way to do that.

I don't know how to update only some packages. In #61978 I updated https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L35-L39 and https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L12-L16 before running `flutter update-packages --force-upgrade`.

**Comment by jakemac53** [comment]
`flutter-1.21-candidate.4` does pin the existing null safe packages and I think is probably where we need to cherry pick in? But I don't know the processes here.

**Comment by jakemac53** [comment]
Sorry @a14n I was confused by the multiple candidate branches - it sounds like flutter-1.20-candidate.7 is what will be paired with the Dart 2.9 stable release - that does not currently pin any null safe versions and thus does not need a cherry pick.

Closing this issue as there is actually no action item at all at this time
