### ISSUE TITLE
why is the registrar.messenger() always be null, everyone can help me?

### ISSUE THREAD

**Issue by tryroach** [flutter/flutter#61746]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

Analyzing doctor...                                                     

   info • Unused import: 'package:doctor/constants/serviceList.dart' • lib/modules/login/pages/loginIndexPage.dart:1:8 • unused_import
   info • Unused import: 'package:doctor/modules/login/widgets/loginThirdLoginWidget.dart' • lib/modules/login/pages/loginIndexPage.dart:6:8 • unused_import
   info • The declaration '_jumpToWebView' isn't referenced • lib/modules/login/pages/loginIndexPage.dart:235:3 • unused_element
   info • 'pickImage' is deprecated and shouldn't be used. Use imagePicker.getImage() method instead. • lib/modules/login/widgets/pickImageShow.dart:47:48 • deprecated_member_use
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: PdfViewerPage._pdfUrl •
          lib/modules/mine/pages/PdfViewerPage.dart:15:7 • must_be_immutable
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. •
          lib/modules/mine/pages/mineBindBankCardPage.dart:363:13 • deprecated_member_use
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. •
          lib/modules/mine/pages/mineWithDrawPage.dart:198:25 • deprecated_member_use
   info • Avoid using braces in interpolation when not needed • lib/modules/settings/settingsPage.dart:112:32 • unnecessary_brace_in_string_interps
warning • The parameter 'token' is required • lib/modules/staging/pages/testMockPage.dart:25:21 • missing_required_param
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Badge.value, Badge.textStyle,
          Badge.isRounded, Badge.positionTop, Badge.positionRight, Badge.positionLeft, Badge.positionBottom, Badge._inside, Badge._before, Badge.spacing, Badge.paddingBottom,
          Badge.paddingLeft, Badge.paddingRight, Badge.paddingTop • lib/widgets/badge.dart:11:7 • must_be_immutable
warning • The parameter 'token' is required • plugins/ticPlugin/example/lib/main.dart:80:29 • missing_required_param
  error • Target of URI doesn't exist: 'package:flutter/foundation.dart' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:7:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/gestures.dart' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:8:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/widgets.dart' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:9:8 • uri_does_not_exist
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:106:5 • undefined_annotation
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:107:5 • undefined_annotation
  error • The method 'hashValues' isn't defined for the type 'WebSetting' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:366:23 • undefined_method
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:385:5 • undefined_annotation
  error • Undefined class 'Widget' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:504:3 • undefined_class
  error • Undefined class 'BuildContext' • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:505:5 • undefined_class
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:510:5 • undefined_annotation
  error • The name 'Factory' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:512:9 • non_type_as_type_argument
  error • The name 'OneSequenceGestureRecognizer' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/platform_interface.dart:512:17 •
         non_type_as_type_argument
  error • Target of URI doesn't exist: 'package:flutter/foundation.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:7:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/gestures.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:8:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/services.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:9:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/widgets.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:10:8 • uri_does_not_exist
  error • Undefined class 'Widget' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:22:3 • undefined_class
  error • Undefined class 'BuildContext' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:23:5 • undefined_class
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:25:5 • undefined_annotation
  error • The name 'Factory' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:27:9 • non_type_as_type_argument
  error • The name 'OneSequenceGestureRecognizer' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:27:17 •
         non_type_as_type_argument
  error • The method 'GestureDetector' isn't defined for the type 'AndroidWebView' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:30:12 • undefined_method
  error • The method 'AndroidView' isn't defined for the type 'AndroidWebView' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:40:14 • undefined_method
  error • Undefined name 'TextDirection' • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:53:26 • undefined_identifier
  error • The name 'StandardMessageCodec' isn't a class • plugins/webview_flutter-0.3.13/lib/src/webview_android.dart:56:36 • const_with_non_type
  error • Target of URI doesn't exist: 'package:flutter/foundation.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:7:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/gestures.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:8:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/services.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:9:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/widgets.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:10:8 • uri_does_not_exist
  error • Undefined class 'Widget' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:22:3 • undefined_class
  error • Undefined class 'BuildContext' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:23:5 • undefined_class
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:25:5 • undefined_annotation
  error • The name 'Factory' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:27:9 • non_type_as_type_argument
  error • The name 'OneSequenceGestureRecognizer' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:27:17 •
         non_type_as_type_argument
  error • The method 'UiKitView' isn't defined for the type 'CupertinoWebView' • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:29:12 • undefined_method
  error • The name 'StandardMessageCodec' isn't a class • plugins/webview_flutter-0.3.13/lib/src/webview_cupertino.dart:41:34 • const_with_non_type
  error • Target of URI doesn't exist: 'package:flutter/services.dart' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:7:8 • uri_does_not_exist
  error • The method 'MethodChannel' isn't defined for the type 'MethodChannelWebViewPlatform' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:17:20 •
         undefined_method
  error • Undefined class 'MethodChannel' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:23:9 • undefined_class
  error • Undefined class 'MethodChannel' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:25:16 • undefined_class
  error • Const variables must be initialized with a constant value • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:26:7 •
         const_initialized_with_non_constant_value
  error • The method 'MethodChannel' isn't defined for the type 'MethodChannelWebViewPlatform' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:26:7 •
         undefined_method
  error • Undefined class 'MethodCall' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:28:30 • undefined_class
  error • The method 'MissingPluginException' isn't defined for the type 'MethodChannelWebViewPlatform' • plugins/webview_flutter-0.3.13/lib/src/webview_method_channel.dart:66:11 •
         undefined_method
  error • Target of URI doesn't exist: 'package:flutter/foundation.dart' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:7:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/gestures.dart' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:8:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter/widgets.dart' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:9:8 • uri_does_not_exist
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:112:5 • undefined_annotation
  error • Undefined name 'required' used as an annotation • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:113:5 • undefined_annotation
  error • Classes can only extend other classes • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:136:23 • extends_non_class
  error • Undefined class 'Key' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:144:5 • undefined_class
  error • The named parameter 'key' isn't defined • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:161:15 • undefined_named_parameter
  error • Undefined name 'defaultTargetPlatform' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:181:15 • undefined_identifier
  error • Case expressions must be constant • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:182:14 • non_constant_case_expression
  error • Undefined name 'TargetPlatform' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:182:14 • undefined_identifier
  error • Case expressions must be constant • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:185:14 • non_constant_case_expression
  error • Undefined name 'TargetPlatform' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:185:14 • undefined_identifier
  error • Undefined name 'defaultTargetPlatform' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:190:70 • undefined_identifier
  error • The name 'Factory' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:208:13 • non_type_as_type_argument
  error • The name 'OneSequenceGestureRecognizer' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:208:21 •
         non_type_as_type_argument
  error • Undefined class 'State' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:333:3 • undefined_class
  error • The name 'StatefulWidget' isn't a type so it can't be used as a type argument • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:333:9 • non_type_as_type_argument
   info • The method doesn't override an inherited method • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:333:25 • override_on_non_overriding_member
  error • Classes can only extend other classes • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:336:29 • extends_non_class
  error • Undefined class 'Widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:343:3 • undefined_class
   info • The method doesn't override an inherited method • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:343:10 • override_on_non_overriding_member
  error • Undefined class 'BuildContext' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:343:16 • undefined_class
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:348:27 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:349:49 • undefined_identifier
   info • The method doesn't override an inherited method • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:354:8 • override_on_non_overriding_member
  error • The method 'initState' isn't defined in a superclass of '_WebViewState' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:355:11 • undefined_super_method
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:357:59 • undefined_identifier
   info • The method doesn't override an inherited method • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:361:8 • override_on_non_overriding_member
  error • The method 'didUpdateWidget' isn't defined in a superclass of '_WebViewState' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:362:11 • undefined_super_method
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:365:43 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:366:32 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:372:25 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:374:9 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:375:7 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:380:9 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:381:9 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:384:33 • undefined_identifier
  error • Undefined name 'widget' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:385:9 • undefined_identifier
  error • The method 'FlutterError' isn't defined for the type 'WebViewController' • plugins/webview_flutter-0.3.13/lib/webview_flutter.dart:662:35 • undefined_method
95 issues found. (ran in 9.0s)
```
```

```[✓] Flutter (Channel master, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.0-3.0.pre at /Users/caowen/Library/Flutter/flutter
    • Framework revision 06d0cd514e (3 weeks ago), 2020-06-26 15:34:41 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/caowen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/caowen/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/caowen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • CDY AN90 • QKX4C20428006046 • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>
there's my problem and with my code

@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      com.jiguang.jpush.JPushPlugin.registerWith(shimPluginRegistry.registrarFor("com.jiguang.jpush.JPushPlugin"));
      com.alveliu.flutterfullpdfviewer.FlutterFullPdfViewerPlugin.registerWith(shimPluginRegistry.registrarFor("com.alveliu.flutterfullpdfviewer.FlutterFullPdfViewerPlugin"));
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      com.hjc.flutter_walle_plugin.FlutterWallePlugin.registerWith(shimPluginRegistry.registrarFor("com.hjc.flutter_walle_plugin.FlutterWallePlugin"));
      com.example.imagegallerysaver.ImageGallerySaverPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.imagegallerysaver.ImageGallerySaverPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    flutterEngine.getPlugins().add(new com.casuaCloud.doctor.tic.ticplugins.TicPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());
  }
}

 /** Plugin registration. */
    public static void registerWith(Registrar registrar) {
 /**The problem is this line,  registrar.messenger() was alway be null */
        final MethodChannel channel = new MethodChannel(registrar.messenger(), "jpush");
        channel.setMethodCallHandler(new JPushPlugin(registrar, channel));

        registrar.addViewDestroyListener(new PluginRegistry.ViewDestroyListener() {
            @Override
            public boolean onViewDestroy(FlutterNativeView flutterNativeView) {
                instance.dartIsReady = false;
                return false;
            }
        });
    }

2020-07-18 00:58:28.986 10321-10321/com.bonjourjames.doctor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bonjourjames.doctor, PID: 10321
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bonjourjames.doctor/com.causahealth.doctor.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3865)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4044)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8293)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
        at com.jiguang.jpush.JPushPlugin.registerWith(JPushPlugin.java:37)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
        at com.causahealth.doctor.activity.MainActivity.configureFlutterEngine(MainActivity.java:63)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
        at com.causahealth.doctor.activity.MainActivity.onCreate(MainActivity.java:48)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3838)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4044) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8293) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by snailzzj** [comment]
Hi, @tryroach . I have same problem. Did you found solution?

**Comment by tryroach** [comment]
@snailzzj Check the configureFlutterEngine  in your app MainActivity , is there hava super call?
