### ISSUE TITLE
Update BoxFit documentation about clip

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#61755]
As FittedBox defaults its clipBehavior to Clip.none, we should update its API doc by stating that `BoxFit.cover`, `BoxFit.none`, `BoxFit.fitHeight`, `BoxFit.fitWidth` would also require `Clip.hardEdge` to clip the content.

Related issue: https://github.com/flutter/flutter/issues/21830
Related PR: https://github.com/flutter/flutter/pull/59364

**Comment by cv692001** [comment]
Hey I am very new to Contributing and this is going to be my first contribution can you please help me

**Comment by liyuqian** [comment]
I'm happy to help! Reading and following steps in https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md might be a good first step.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by TheBiirb** [comment]
@liyuqian I believe `FittedBox` defaults its `clipBehavior` to `Clip.hardEdge`, no?

**Comment by markusaksli-nc** [comment]
@liyuqian This isn't the case in either your original PR or the latest master:
https://github.com/flutter/flutter/blob/8e8acaac7a19c1bc9a5bc27ea74cfda7caf3b0a5/packages/flutter/lib/src/widgets/basic.dart#L1427
Do we just close this issue? Your PR description reads as this was supposed to be `Clip.none`. There is nothing to be changed in the docs as it stands though.

**Comment by liyuqian** [comment]
@TheBiirb @markusaksli-nc : we will eventually have `FittedBox` default to `Clip.hardEdge`. Currently we are still waiting for another internal patch to fix some Google internal tests. I'll make sure to update this issue once it's done.
