### ISSUE TITLE
Use better solution for waiting for Scenic in SessionConnection tests

### ISSUE THREAD

**Issue by farchond** [flutter/flutter#61768]
Currently, the solution we are using to wait for Scenic to startup is something akin to: while (!condition) { sleep(100); }

While this works, and is better than sleeping for a large, predetermined about of time, it is not as clean as it could be.

**Comment by zanderso** [comment]
Comments from a thread on the PR above:

> Yes, notice that TestWithEnvironment depends on gtest:
>
> class TestWithEnvironment : public gtest::RealLoopFixture
>
> The Flutter tree might have a different version of gtest than the Fuchsia tree, which means we cannot include code in the Fuchsia SDK that depends on gtest. Even more problematically, gtest itself depends on the Fuchsia SDK, which means introducing a dependency from the Fuchsia SDK to gtest would create a circular dependency.
>
> Instead, I'd recommend creating your own version of this code in the Flutter tree that uses the Flutter instance of gtest."

and:

> Do keep in mind that forked libraries will require some ongoing maintenance. Today there's no discrepancy between these two versions, because the forking is fresh. What happens in a year, after features/bugfixes have been added to the Fuchsia version, or when a Components v2-specific "TestWithEnvrionment" gets authored?"
