### ISSUE TITLE
Migrate build.sh checks from Cirrus to LUCI

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#61767]
[Build.sh ](https://github.com/flutter/engine/blob/master/ci/build.sh )is one for the steps remaining in the cirrus file: https://github.com/flutter/engine/blob/master/.cirrus.yml#L120

The script makes directory changes and path assignments, it's better we write another version of it to use from LUCI recipe.

**Comment by nturgut** [comment]
@dnfield I think before using it from LUCI recipe, we need to rewrite the build.sh. What do you think?

Related to our conversation on the PR: https://github.com/flutter/engine/pull/19854#issuecomment-660357686

**Comment by godofredoc** [comment]
obsolete.
