### ISSUE TITLE
[camera] iOS not recording audio

### ISSUE THREAD

**Issue by adamdupuis** [flutter/flutter#61771]
Audio is not being recorded when recording video with the Camera plugin (0.5.8+2) on iOS (13.5.1).

It is not working in the example Camera plugin app and the microphone permission is never requested.

(`enableAudio` is set to `true`)

**Edit:** This could be an issue with the iPhone I am using. Recording video with the native Camera app also seems to not record audio.

**Comment by Mouradif** [comment]
@adamdupuis what was your solution? I'm having the same problem
