### ISSUE TITLE
Audit our binary size

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6177]
Things to consider removing from release builds:
- [ ] skia image encoders (PNG encoder is used for screenshot feature in debug mode)
- [ ] skia has a table of square roots that seems unnecessary
- [ ] We should make sure DartVM doesn't have a parser for Dart source code

**Comment by tvolkert** [comment]
Other things to consider:
- [ ] Tree-shaking the material icons font to include only the icons the app uses
- [ ] Investigating to see if there's anything included in the app snapshot that could be removed from release builds

**Comment by dnfield** [comment]
I'm going to close this bug.

We can't remove image encoders - in particular, PNG is needed for freetype.

AFAICT, Skia has removed the table of roots, and the Dart VM doesn't contain a parser for VM code.

We've impelemnted tree shaking of material icons.

The Dart team is tracking AOT size with these bugs: https://github.com/dart-lang/sdk/issues?q=is%3Aopen+is%3Aissue+label%3Avm-aot-code-size

We're tracking size with these bugs: https://github.com/flutter/flutter/labels/a%3A%20size

There's at least one other bug currently that could also reduce size: https://github.com/dart-lang/sdk/issues/39104
