### ISSUE TITLE
The method '>=' was called on null. Receiver: null Tried calling: >=(25)

### ISSUE THREAD

**Issue by RickyC2020** [flutter/flutter#61782]
Hi Guys,

I am new to Flutter and a beginner at programming. I am getting the above error message from the simple calculator code below, which should calculate BMI. When I take out the 'greater-than' sign and put "==" instead, as an experiment, it works. But when I use the 'greater-than' sign or even the 'less-than' sign. it throws the above error. Can't find the problem and My Android Studio is up to date.  Your help would be well appreciated.

import 'package:flutter/cupertino.dart';
import 'dart:math';

class CalculatorBrain{

  CalculatorBrain({@required this.weight,@required this.height});

  final int height;
  final int weight;
  double _bmi;
  
  String calculateBMI(){
    _bmi = weight/pow(height/100, 2);
    return _bmi.toStringAsFixed(1);
  }

  String getResult(){

    if(_bmi >= 25){
      return 'OVERWEIGHT';
    }else if(_bmi > 18.5){
      return 'NORMAL';
    }else{
      return 'UNDERWEIGHT';
    }
  }

  String getInterpretation(){
    if(_bmi >= 25){
      return 'Eat Less';
    }else if(_bmi > 18.5){
      return 'You are ok';
    }else{
      return 'Eat more';
    }
  }
}

**Comment by rezvan-net** [comment]
you must omit 'double' before your equation. 

` _bmi = weight / pow(2, height/100);`
