### ISSUE TITLE
Allow embedded  `flutter run -d web`

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#61788]
## Use case

I am trying to create an embedded simulator inside vscode. Vscode uses webview for embedded views so I am using flutter web, but the HttpServer, used in` flutter run -d web`, is served with the default header 'x-frame-options: SAMEORIGIN' that doesn't allow to access it from vscode or any iframe. 

I would like to propose to create this flag 
`flutter run -d web --web-allow-embedded`
that in the following line [devfs_web.dart#L189](https://github.com/flutter/flutter/blob/6e0bc30e84de96294f0141c3813872b3e9156ed6/packages/flutter_tools/lib/src/build_runner/devfs_web.dart#L189), would execute
`httpServer.defaultResponseHeaders.remove('x-frame-options', 'SAMEORIGIN');`

The approach is the same as how DartTools is embedded right now in vscode  https://github.com/flutter/devtools/blob/177ac62a0d37d610cb837d4ea53c26a2170069d1/packages/devtools_server/lib/src/server.dart#L239

![image](https://user-images.githubusercontent.com/19904063/87851120-ffa88b80-c8f5-11ea-9e6e-4d29e024fd2d.png)

**Comment by jonahwilliams** [comment]
Seems like a reasonable addition. I don't think there would be an issue with removing the x-frame-options header for the local web server in all cases, though I admit I haven't thought about it much.

@jamesblasco if you're willing to put together a PR I'd more than happy to review it
