### ISSUE TITLE
Image picker not found in Pub.dartLang.org 

### ISSUE THREAD

**Issue by JustinWeru12** [flutter/flutter#61787]
I am receiving the following error while installing image picker in a pubspec.yaml. 

`Because lancy depends on image picker any which doesn't exist (could not find package image picker at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...`

Flutter Doctor
`[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.752], locale ---)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.47.2)
[√] Connected device (1 available)`

**Comment by Yodart** [comment]
@JustinWeru12 could you please provide full logs for this? `flutter run --verbose`

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by JustinWeru12** [comment]
I found out the issue was in syntax
