### ISSUE TITLE
Add a functionality to tap on screen and then go to code of the place you tapped

### ISSUE THREAD

**Issue by 007sya** [flutter/flutter#61793]
Have an option like in browse console (Source code Inspection) to click in a widget on the screen and automatically select the widget in the code
![Capture](https://user-images.githubusercontent.com/53478143/87852718-caf00080-c904-11ea-851a-0c8110800717.PNG)

This functionality would be very convinient, because sometimes you get lost in the code and can't find the widget you are looking for.

**Comment by Yodart** [comment]
Great news, our dear flutter already supports this with the power of the Flutter Inspector. Here's the relevant documentation for that https://flutter.dev/docs/development/tools/devtools/inspector. And also, here's an incredible talk from DartConf 2018 around the same feature https://www.youtube.com/watch?v=JIcmJNT9DNI.

**Comment by 007sya** [comment]
Saved me! Thank you very much
