### ISSUE TITLE
Flutter within android layout overlays when keyboard is open on Android.

### ISSUE THREAD

**Issue by vekexasia** [flutter/flutter#61794]
## Steps to Reproduce

1. override `setContentView` to actually use a custom android layout within your Activity and host the original flutter view within a framelayout.

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:orientation="vertical"
              android:id="@+id/ll"
              android:background="@android:color/transparent"
              android:layout_height="match_parent">
    <FrameLayout android:layout_width="match_parent" android:layout_height="0dp"
              android:layout_weight="1"
              android:id="@+id/flutterFragment"/>

    <com.adincube.sdk.BannerView android:id="@+id/bannerView" android:layout_width="match_parent"
                                 android:layout_height="50dp"/>
</LinearLayout>

```
2. App opens properrly but when screen is resized due to keyboard being opened, the 50dp vertical space becomes blank (seems flutter is over the layout).

**Expected results:** 

I would expect my 50dp view in the bottom to be visible.

**Actual results:** 

Here is what i see when keyboard is open (notice the "white" space):
![image](https://user-images.githubusercontent.com/200523/87854068-4f478100-c90f-11ea-8f3e-29e2e633c61b.png)

When keyboard is closed (notice the darkblue stuff space before the soft-touch back btn):
![image](https://user-images.githubusercontent.com/200523/87854065-4656af80-c90f-11ea-8bbb-d1ca7b828319.png)

--- flutter doctor -v
```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.3.pre at /home/andrea/git/flutter
    • Framework revision 8fe7655ed2 (2 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/andrea/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/andrea/android-sdk
    • Java binary at: /home/andrea/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/andrea/Desktop/android-studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Pixel 3a   • 9B9AY1HXDU • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by iapicca** [comment]
Hi @vekexasia 
Can you please provide a **complete** minimal reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
