### ISSUE TITLE
Multiple webviews disappear at random

### ISSUE THREAD

**Issue by owenkealey** [flutter/flutter#61795]
Unfortunately this is not easily reproducible(I myself cannot reproduce, but 30% of my users report it), but I have an IndexedStack where each child is a webview. The user, via controls on the app, is able to flip through webviews so that one is displayed at a time and the other ones(being children of an IndexedStack) are hidden. 

Problem is that sometimes when users flip to a webview in the IndexedStack, they aren't there -- the webview is totally blank as if it wasn't there(I have done extensive debugging to verify that it is indeed there on the widget tree side). Sometimes refreshing it brings it back, sometimes not. Its as if they fall asleep when in the background. 

Any thoughts?

**Comment by owenkealey** [comment]
I think this may be caused by https://github.com/flutter/flutter/issues/61781 webviews DO use lots of memory.

**Comment by owenkealey** [comment]
Restarting the device temporarily fixes the issue, which if caused by #61781 makes sense as restarting clears memory.

**Comment by VladyslavBondarenko** [comment]
@owenkealey 
would be good if you could provide reproducing steps with a minimal complete code sample/project together with your `flutter doctor -v`

**Comment by dnfield** [comment]
@owenkealey - please see if you can provide a minimal example. It would also help to know what platform(s) this happens on. The linked bug is specific to iOS.

**Comment by owenkealey** [comment]
Sorry about that! Heres an example: 
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Buggy Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _tab = 0;

  void _changeTab() {
    setState(() {
      _tab == 9 ? _tab = 0 : _tab ++;
      print("_tab");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: IndexedStack(
          index: _tab,
          /// These are the "tabs"
          children: <Widget>[
            ...List<int>.generate(10, (i) => i + 1).map((e){
              return Container(
                height: 500,
                child: WebView(
                  javascriptMode: JavascriptMode.unrestricted,
                  initialUrl: "https://footlocker.com",
                )
              );
            }).toList()
          ],
        )
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _changeTab,
        tooltip: 'Switch Webview',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

@dnfield As far as I know this only happens on iOS thats why I mentioned that issue(but I also haven't tested on Android).

flutter doctor -v:
```
➜  webview_bug flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.17.5 at /Users/owen/Downloads/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro • 8AD57C00-669E-47D9-AC42-E72F5EC1DD39 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

! Doctor found issues in 2 categories.```

Also note that this is really only reproducible on a real iPhone. My internal users have not been able to reproduce on iPad however, or simulator which leads me to believe this is a out of memory issue(as iPads and desktops have much more memory for the webviews).

I think this is a bug because I can make a similar app with Swift, WKWebview and sub/super views and it wont do this.

**Comment by VladyslavBondarenko** [comment]
@owenkealey thanks,
I tried with stable `1.17.5`, webview_flutter: ^0.3.22+1 on iPhone 7 iOS 13.6 this code sample (the only change - set initialUrl to `https://flutter.dev`, because after many visits access to the website from code sample was restricted). I tried with higher number of tabs (40). The first blank webview appeared on 27th tab and then the more tabs I change - the more often webviews were not rendered.
I tried also with current master `1.21.0-2.0.pre.94` - reproduces too, webviews start to load after some pause, but the first blank appeared on 54th tab. 
It may be not iOS specific. I tried with Redmi Note 7 Android 9 (API 28).  It's working properly with 5 tabs. 
But when I set 10  - app crashes when I change tab before all of them are loaded, but once they are loaded I can interact with them. When I use 40 or 20 - app is loading for long time and crashes in the end without even rendering webview.
No stack trace, only `Lost connection to device.`.

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/34647

**Comment by owenkealey** [comment]
@VladyslavBondarenko Makes sense, I also suspect this is NOT a problem with the plugin because I have tried with other webview plugins(flutter_inappwebview) and the same thing happens.

**Comment by owenkealey** [comment]
If it helps, refreshing the webview often brings it back(sometimes not though) but obviously this is sub optimal.

**Comment by owenkealey** [comment]
One of my users it happens with just 6 tabs:
[video0.mp4.zip](https://github.com/flutter/flutter/files/4973563/video0.mp4.zip)

**Comment by uncleballs** [comment]
> Unfortunately this is not easily reproducible(I myself cannot reproduce, but 30% of my users report it), but I have an IndexedStack where each child is a webview. The user, via controls on the app, is able to flip through webviews so that one is displayed at a time and the other ones(being children of an IndexedStack) are hidden.
> 
> Problem is that sometimes when users flip to a webview in the IndexedStack, they aren't there -- the webview is totally blank as if it wasn't there(I have done extensive debugging to verify that it is indeed there on the widget tree side). Sometimes refreshing it brings it back, sometimes not. Its as if they fall asleep when in the background.
> 
> Any thoughts?

GOOGLE LOOK AT THIS NOW

**Comment by miyoyo** [comment]
Maybe the views are always attached to some rendered, even when in the background, which means that, when native, the system can easily cull them out, saving memory, however, it cannot cull them out with flutter because they're always constantly rendering?

**Comment by owenkealey** [comment]
I'm not exactly sure what you mean, I thought the whole point of an IndexedStack was so that each child remains in the widget tree even when not being painted. 

Unless in this case the RenderObject is being delegated to the system and the system is just doing whatever it wants with it?

**Comment by miyoyo** [comment]
The system has to draw to a texture in order to pass it to flutter, it might constantly keep the webview drawing which draws more of the system resources than something native which could automatically stop drawing and taking ram.
I would expect similar RAM usage from a native view that has to draw 5 or 6 webviews *at once*.

**Comment by owenkealey** [comment]
Although to be honest I am not really sure how flutter and native views interact so my assessment could be wrong.

**Comment by owenkealey** [comment]
Yea I guess that's a possibility, in any event we will probably have to wait for the Flutter engine team to comment.

**Comment by dnfield** [comment]
@owenkealey - I just tried this on master on an iPhone 11, and I'm not able to see any issue. Memory usage looks reasonable to me and doesn't increase as I cycle through. I'm able to continuously cycle through and not have any webviews disappear.

**Comment by dnfield** [comment]
Can you try on master and see if you still have this issue?

**Comment by owenkealey** [comment]
Sure, trying now.

**Comment by dnfield** [comment]
I'm also using webview_flutter 0.3.22+1

**Comment by dnfield** [comment]
Ahh, with a sufficiently large number of webviews I do run into problems - e.g. if I bump it up to 100 webviews instead of 10.

**Comment by owenkealey** [comment]
Running in debug mode with just ten webviews one disappears and then two more. Refreshing brings them back and Interestingly, I am using flutter_inappwebview for the webviews because it has callback support for iosOnWebContentProcessDidTerminate but that doesnt fire when they disappear so it must be something else.

I have also tried with webview_flutter and can confirm they disappear there as well. 

Them disappearing with 100 isnt that concerning honestly because I don't expect users to have 100 browser tabs open, but some users can reproduce with like 2 or 3.

**Comment by owenkealey** [comment]
Also if it is of any help, I with my internal users have found that if you DON'T switch through webviews, they dont disappear(until you start flipping through them). For example, if you make some webviews, leave them for 20 minutes on the first one, they will start disappearing 1-2 minutes into you flipping through them.

**Comment by blasten** [comment]
@owenkealey This seems to occur if you load the website in the example. It doesn't occur if it's changed to google.com or wikipedia.org.  If you found evidence that this repros with other websites, feel free to reopen the issue.

**Comment by owenkealey** [comment]
> @owenkealey thanks,
> I tried with stable `1.17.5`, webview_flutter: ^0.3.22+1 on iPhone 7 iOS 13.6 this code sample (the only change - set initialUrl to `https://flutter.dev`, because after many visits access to the website from code sample was restricted). I tried with higher number of tabs (40). The first blank webview appeared on 27th tab and then the more tabs I change - the more often webviews were not rendered.

@VladyslavBondarenko found it happens on flutter.dev.  I too can reproduce on flutter.dev.

I suspect it happens more frequently on footlocker.com because footlocker.com is image and resource heavy. I tested on another image heavy site, polygon.com and it reproduces there as well.

Even if it only happens on a few sites...certainly it must be something to do with Flutter because I a) can use WKWebview with Swift and nothing like this happens(lag happens, but thats to be expected with so many browsers) and b) I seriously doubt that there is something special about footlocker.com and flutter.dev that causes their host browsers to crash and go blank.

**Comment by owenkealey** [comment]
@blasten ^^ Not sure if you get notifs for closed issues so sorry If I have @ you twice

**Comment by miyoyo** [comment]
@blasten I'm sorry but this is not a valid reason to close the issue.

If it happens on this website, what stops it from happening to another website? Are all webview usecases really nothing but google and wikipedia?

There is a problem here, and it's wrong to silence it because it's "just a strange edge case".

**Comment by blasten** [comment]
Sorry. I didn’t mean to close it because it’s an edge case. If you have the example in a vanilla iOS app, please send it to us as it could help us figure out where the issue may be.

**Comment by owenkealey** [comment]
By vanilla iOS app do you mean an app made with Swift/WKWebview?

**Comment by owenkealey** [comment]
Because if you scroll up I commented an example of it in Flutter.

**Comment by chinmaygarde** [comment]
@blasten My suspicion is that we are creating a FlutterView with its one device backing store for each platform view even though there is no interleaving of Flutter contents. Does that make sense? There is a test case for this so we should use that to verify.

**Comment by owenkealey** [comment]
Might also want to take a look at this thread, https://github.com/pichillilorenzo/flutter_inappwebview/issues/459 That was the original issue I reported because I thought it was a plugin issue(before I discovered I could reproduce with the official plugin).

Someone reported problems as well with putting a webview inside a page view not sure if related.

**Comment by owenkealey** [comment]
@blasten somewhat unrelated but how could I get in contact with the flutter team to get a customer: label. My company uses Flutter and would like one.

**Comment by dnfield** [comment]
@csells

**Comment by virskor** [comment]
Any plan to fix this issue? Thanks

**Comment by Calx-Takeno** [comment]
P2 to P3, maybe speed it up to fix it. Is it good news?

**Comment by blasten** [comment]
@chinmaygarde There's only one `FlutterView` and one `WKWebView` at the time. (no overlay surfaces)

I debugged this further. This seems to happen only if you use the `IndexedStack` widget. If you change it for `Column` and display the 10 webviews at the same time, then they are all rendered.

I tried to come up with an equivalent SwiftUI code, and saw that website isn't rendered passed the 5th webview. 
If you can come up with an equivalent demo in a vanilla iOS app that works, I can give it try.

**Comment by owenkealey** [comment]
Any idea why it happens when only using IndexedStack? That widget is kind of essential to making tabs for my browser app.

**Comment by blasten** [comment]
`IndexedStack` causes the webviews to be appended and removed from the view hierarchy multiple times, while strong references are held in memory.

**Comment by cyanglaz** [comment]
@blasten Was the appending and removing happening because of the clipping logic (https://github.com/flutter/flutter/issues/46167)? Or it is something else.

**Comment by blasten** [comment]
> Was the appending and removing happening because of the clipping logic

This seems to be the behavior of `IndexedStack`: https://github.com/flutter/flutter/blob/c44e5a32b5d88e605c9b86ba7029e8e86f42b85f/packages/flutter/lib/src/rendering/stack.dart#L707

**Comment by owenkealey** [comment]
@blasten That's odd. If it was a memory issue then multiple web views on the screen at once should produce the blank screen problem, correct?

**Comment by owenkealey** [comment]
Oh also I tried using Visibility and Offstage widgets to achieve the same effect and same issue.

**Comment by owenkealey** [comment]
Maybe iOS isn't detecting that the WKWebView has left the screen because it's status in the widget tree is managed by Flutter, so it never activates the memory and energy saving features that it normally would(such as pausing JavaScript execution).

**Comment by virskor** [comment]
Still wait for a good workround🤒

**Comment by manojdvs123** [comment]
Hey is there any way to delete the webhistory. Please let me know if there is any.

**Comment by Calx-Takeno** [comment]
One month has passed. Is there any update on this issue?
Anyone suffers from this problem. Please raise your hand! Let the flutter team hear us

**Comment by blasten** [comment]
@cyanglaz feel free to assign a new milestone

**Comment by Calx-Takeno** [comment]
any updates on this issue or plan?

**Comment by cyanglaz** [comment]
After digging into the problem, it seems that loading too many requests on too many web views caused the problem. I couldn't find anything [here](https://developer.apple.com/documentation/webkit/wkwebview/1414954-loadrequest?language=objc) indicates a limit of web views can load request at the same time.

It could also be that loading request while the web view is not in the view hierarchy caused the issue. 

For reference, here is a sample iOS app that reproduced the same problem, this is resembling how flutter engine and the web view plugin works behind the scene.

```objc
#import "ViewController.h"
#import <WebKit/WebKit.h>

@interface ViewController ()

@property (nonatomic, strong) NSMutableArray *webviews;
@property (weak, nonatomic) WKWebView *current;
@property (assign) NSInteger index;

@end

@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];
  self.webviews = [[NSMutableArray alloc] init];
  for (int i = 0; i < 100; i ++) {
    WKWebViewConfiguration* configuration = [[WKWebViewConfiguration alloc] init];
    WKWebView *webView = [[WKWebView alloc] initWithFrame:CGRectMake(0, 0, 300, 400) configuration:configuration];
    [self.webviews addObject:webView];
    NSURLRequest* request = [[NSURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://footlocker.com"]];
    [webview loadRequest:request];
  }
  UIButton *button = [[UIButton alloc] initWithFrame:CGRectMake(0, 400, 100, 100)];
  button.backgroundColor = [UIColor redColor];
  [button addTarget:self action:@selector(nextWebView) forControlEvents:UIControlEventTouchUpInside];
  [self.view addSubview:button];

  // Do any additional setup after loading the view.
}

- (void)nextWebView {
  if (self.index == self.webviews.count) {
    self.index = 0;
  }
  if (self.current) {
    [self.current removeFromSuperview];
  }
  WKWebView *webview = self.webviews[self.index];
  self.current = webview;
  [self.view addSubview:webview];
  self.index ++;
}

@end```

For fixing this, I think it makes sense for a WebView to only load request when it is added to the view hierarchy.

**Comment by cyanglaz** [comment]
Based on my comment above, there isn't really a proper fix from flutter side, because this behavior is limited on iOS.

One workaround is to reload the webView on [webViewWebContentProcessDidTerminate](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455639-webviewwebcontentprocessdidtermi?language=objc) I will create a PR to expose this callback to dart, so one can reload the webview in this callback.

However, I would highly recommend against using `IndexedStack` with many WKWebView (more than 10 is probably too many in old devices) as `IndexedStack` caches all its children, especially for web pages uses a lot of memory. And also on iOS, WKWebView runs out of process so the app can't reliably catch the memory pressure warning.

**Comment by cyanglaz** [comment]
After flutter/plugins#3212 lands, this could be workarounded by reloading the webview when `WebResourceErrorType.webContentProcessTerminated` is present. (You might need to do more handling based on your specific cases.
A simple example would be:
```dart
IndexedStack(
        index: _tab,
        /// These are the "tabs"
        children: <Widget>[
          ...List<int>.generate(40, (i) => i).map((e) {
            WebView webView = WebView(
              javascriptMode: JavascriptMode.unrestricted,
              initialUrl: 'https://footlocker.com',
              onWebViewCreated: (controller) {
                _controllers[e] = controller;
              },
              onWebResourceError: (error) {
                if (error.errorType == WebResourceErrorType.webContentProcessTerminated) {
                  _controllers[e].reload();
                }
              },
            );
            return webView;
          }).toList()
        ],
      )),
```

**Comment by owenkealey** [comment]
I think this issue falls is because of a more general issue with the design of the framework itself. When the state of a widget changes, flutter doesn't change the widget, but discards it and makes a new one. This is fine for lightweight text widgets and such, but for webviews it means creating and destroying a webview every time the page is scrolled potentially. 

https://stackoverflow.com/a/56995828

There is a NOTICEABLE performance difference between a webview inside flutter and one inside a Swift app, like HUGE, even with just one.

**Comment by cyanglaz** [comment]
flutter/plugins#3212 has been landed, we should be able to workaround this issue by detecting when the webview stopped loading due to memory pressure.

**Comment by lisuizhe** [comment]
> @chinmaygarde There's only one `FlutterView` and one `WKWebView` at the time. (no overlay surfaces)
> 
> I debugged this further. This seems to happen only if you use the `IndexedStack` widget. If you change it for `Column` and display the 10 webviews at the same time, then they are all rendered.
> 
> I tried to come up with an equivalent SwiftUI code, and saw that website isn't rendered passed the 5th webview.
> If you can come up with an equivalent demo in a vanilla iOS app that works, I can give it try.

@blasten I am using flutter_echarts in a **ListView** and get the issue Echarts widget is blank(white, though it should be another issue that webview_flutter should be initially transparent instead of white background) randomly.
The flutter_echarts is using webview_flutter internally to render Apache Echarts.js.
Please check this issue for reference: https://github.com/entronad/flutter_echarts/issues/129
As per my observation, the "blank webview" issue happens more frequently on IOS(in practice, for my app not happen on Android), after digging a lot, I think it may be related to this issue.
