### ISSUE TITLE
flutter install command fails, when xcode installs fine

### ISSUE THREAD

**Issue by safield** [flutter/flutter#61799]
I am building a flutter app, and trying to install on ios simulator.

When I run the app using xcode, the app builds and installs without issue.

But when I try to install on simulator using the command _flutter install -v_ I get the following error output...

> [ +159 ms] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
>                     Failed to install the requested application
>                     An application bundle was not found at the provided path.
>                     Provide a valid path to the desired application bundle.
> [  +18 ms] "flutter install" took 11,261ms.
> Install failed
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
> #1      InstallCommand._installApp (package:flutter_tools/src/commands/install.dart:73:7)
> <asynchronous suspension>
> #2      InstallCommand.runCommand (package:flutter_tools/src/commands/install.dart:53:13)
> <asynchronous suspension>
> #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
> #4      _rootRunUnary (dart:async/zone.dart:1192:38)
> #5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> #6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> #8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> #9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
> #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
> #11     _rootRun (dart:async/zone.dart:1184:13)
> #12     _CustomZone.run (dart:async/zone.dart:1077:19)
> #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
> #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
> #15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
> #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
> #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
> #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5) 

My flutter doctor...

> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-CA)
>     • Flutter version 1.17.5 at /Users/me/.flutter_sdk
>     • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
>     • Engine revision ee76268252
>     • Dart version 2.8.4
> 
>  
> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/me/.android_sdk
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/me/.android_sdk
>     • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.9.3
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
>       instructions).
> 
> [✓] Connected device (1 available)
>     • iPhone SE (2nd generation) • C4BEF46C-3B8A-41D2-B5E9-11C3105F1784 • ios •
>       com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by jonahwilliams** [comment]
You should generally use `flutter run` to build and install or `flutter build ios --simulator` and then `flutter install`. The error message is expected, since it seems you have't built the exact bundle before

**Comment by safield** [comment]
What do you mean? Everytime I run flutter install, it fails with this error. How is this expected?
