### ISSUE TITLE
Can't enter a space before a newline after a newline

### ISSUE THREAD

**Issue by MisakoGunjima** [flutter/flutter#61797]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add the following widget to your widget trees 
```
TextField(
        expands: true,
        maxLines: null,
      )
```

3. Can't enter a space before a newline after a newline

![ezgif-2-d8d1ee7d1b73](https://user-images.githubusercontent.com/6672138/87857304-b2153880-c960-11ea-95b3-20219d0f083e.gif)

on LogCat Error
``` E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

```

</details>

**Comment by darshankawar** [comment]
Hi @MisakoGunjima,
If I understand the issue correctly, when your app launches, you are are pressing `enter` from keyboard and then trying to add spaces in `newline` and here you are unable to add spaces, am I correct ?

If so, I tried to replicate this on latest Flutter dev channel with the code snippet you provided and I am able to add space in same line and also after I press `enter` to go to new line and then able to add spaces there as well. So I am unable to replicate the issue, unless I am missing something.

Below is the code sample I tried and a video for your reference:

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(title: Text('Demo')),
        body: SafeArea(
          child:
          Container(
              color: Colors.yellow,
              child: Center(child: TextField(
                expands: true,
                maxLines: null,
              ))
          ),
        ),
        floatingActionButton: RaisedButton(
          onPressed: () {},
          child: Text('Button'),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

I tested on Android 8.1.0 device.

[61797.mp4.zip](https://github.com/flutter/flutter/files/4946935/61797.mp4.zip)

**Comment by MisakoGunjima** [comment]
That's not quite what I'm trying to convey.

step1. input new line

step2. Select the previous line( line 1)

step3.input space

The problem is that you can't enter a space when the next line exists.

**Comment by darshankawar** [comment]
Hi @MisakoGunjima,
I followed the steps you mentioned and was able to enter space when the new line exists. See the attached video.
I tested on Android 10 and on latest Flutter dev channel. Which device are you facing this issue on ?

[61797.mp4.zip](https://github.com/flutter/flutter/files/4947633/61797.mp4.zip)

**Comment by MisakoGunjima** [comment]
Thanks!!!!!

When I changed from the stable channel to the dev channel, I was able to enter a space.

Apparently it was already a problem fixed in the dev channel.
