### ISSUE TITLE
Starting stocks app on /settings route breaks stocks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#618]
I'm pretty sure that if you start the stocks app at any route other than '/', it'll crash when you hit the "<-" icon at the top left.

**Comment by Hixie** [comment]
We should probably break down the route and build the history from each part up to the final part. Like, if it was "/settings/wifi" we'd open the "/" page, then push the "/settings" page, then push the "/settings/wifi" page. Or some such.

**Comment by sethladd** [comment]
This issue hasn't received an update in a while. Do we plan to address this in the framework?

**Comment by Hixie** [comment]
Yeah, this is something we'll probably have to figure out sooner rather than later.

**Comment by eseidelGoogle** [comment]
Likely relates to https://github.com/flutter/flutter/issues/95 or https://github.com/flutter/flutter/issues/5330.

**Comment by Hixie** [comment]
We suspect this will shortly become a customer blocker.

**Comment by eseidelGoogle** [comment]
FYI @lukef you may run into this as part of deep linking.

**Comment by Hixie** [comment]
This should be fixed now, but please don't hesitate to file new bugs if there are aspects of this that aren't satisfactory.
