### ISSUE TITLE
err_name_not_resolved flutter

### ISSUE THREAD

**Issue by Vitttu** [flutter/flutter#61804]
The problem appears when you open a web page with WebView
ERRO: err_name_not_resolved

Flutter is updated
The Code is revised
Dependencies are applied

WebView Works only on the emulator, but does not run on the physical device

**Comment by darshankawar** [comment]
Hi @Vitttu,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Also mention the device on which you are trying and not working.

**Comment by dataamericadevelopment** [comment]
> Hi @Vitttu,
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Also mention the device on which you are trying and not working.

Hello, @darshankawar ! We are facing the same problem with WebView.
In store reviews (Google Play and Apple App Store) the error of err_name_not_resolved was reported, but in debug, the app runs smoothly.
Then I put the Flutter Doctor command as requested.

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [versÃ£o 10.0.19041.450], locale pt-BR)
    • Flutter version 1.17.5 at C:\Dev\FlutterSDK
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Dev\AndroidSDK
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Dev\AndroidSDK
    • ANDROID_SDK_ROOT = C:\Dev\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at D:\Usuários\mathi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM G935F • 192.168.0.101:5555 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```
