### ISSUE TITLE
Desktop App 

### ISSUE THREAD

**Issue by VadimGushin** [flutter/flutter#61817]
Hello
I wanted to ask you about the desktop part of the technology.
If the documentation is about how ordinary developers can inject native code into a desktop application (WPF, Mac, Linux) like buinding or as a custom plugin or something similar
Best regards, Vadim

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by VadimGushin** [comment]
Ok, I got it, thanks for the answer
