### ISSUE TITLE
IconButton ripple effect

### ISSUE THREAD

**Issue by savke30** [flutter/flutter#61811]
Bug with IconButton ripple effect.

When i set background color of Container and inside that Container as a child I put IconButton widget.
Then suddenly ripple effect goes behind that backgroun color.

I know for fix when I swap Container widget with Material but in this situation I really need my Container widget.

Is there any solution to have a ripple effect on IconButton widget and the parent of that widget stays to be a Container?

**Comment by yvesjordan06** [comment]
Take a look at [this issue](https://github.com/flutter/flutter/issues/3782) it has a workaround

@Hixie said 



>What's going on is that the Material spec says that the splashes are actually ink on the Material. So when we splash, what we do is we literally have the Material widget do the splash. If you have something on top of the Material, we splash under it, and you can't see it.

Try wrapping your IconButton in a Material Widget

``` dart
Container(
    child:Material(
        color: Colors.transparent //To let the Container background be displayed
        child: IconButton(
            icon: Icon(Icons.heart),
            onPressed: (){}
        ),
    ),
)
```

Hope it helps you out

**Comment by VladyslavBondarenko** [comment]
Thanks @yvesjordan06 ,
@savke30 does it help or your use case is different?

**Comment by savke30** [comment]
@yvesjordan06 that was helpful.

I think this issues is solved.

**Comment by BananaMasterz** [comment]
I tried this and it gives a rectangular ripple which is not pretty.

**Comment by gtu-myowin** [comment]
> I tried this and it gives a rectangular ripple which is not pretty.

Then, you can use ClipOval. Like this

```dart
ClipOval(
  child: Material(
    color: Colors
        .transparent, //To let the Container background be displayed
    child: IconButton(
        icon: Icon(
          Icons.play_arrow,
          color: Colors.white,
        ),
        onPressed: () {}),
  ),
),
```
