### ISSUE TITLE
Change all localizations to NOT being uppercase

### ISSUE THREAD

**Issue by LasseRosenow** [flutter/flutter#61820]
Related: https://github.com/flutter/flutter/issues/104270

---

## Use case
Some localizations like `cancelButtonLabel `, `closeButtonLabel `, `continueButtonLabel `, `okButtonLabel `, `viewLicensesButtonLabel ` are uppercase [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/material_localizations.dart) and also in all translations [here](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations/lib/src/l10n)
In my app I have my Dialog actions and buttons in general using normal case, but Widgets like the DatePicker use those internal localizations .. so they are UPPERCASE while the rest of my app is not.

## Proposal
Modern material design goes more into using normal case so that should be reason enough to change that.
But also more importantly the letter case should be controlled by TextButtonTheme and so on depending on where you use those strings. So by default everything should be stored in normal case and if you want something like UPPERCASE, you should do that programmatically. This way the letter cases in applications can be way more consistent.

**Comment by MitchellGoodwin** [comment]
Fixed mostly by #115187. Notably abbreviations like 'OK' and 'PM' are still uppercase, but I think that's somewhat normal. Closing this issue as fixed, we can reopen if those strings still being uppercase is a problem.
