### ISSUE TITLE
Flutter upgrade caused error with localization

### ISSUE THREAD

**Issue by shikha1992** [flutter/flutter#61825]
I recently upgraded my flutter version to 1.17.5 
after this I prepared release apk file and its not opening while it works fin when debug build is installed in device. Error logs are as below : 
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 
    #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221)
    <asynchronous suspension>
    #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67)
    <asynchronous suspension>
    #2      DemoLocalizations.load (package:greenplayapp/utils/language/demo_localization.dart:23)
    <asynchronous suspension>
    #3      _loadAll.<anonymous closure> (package:flutter/src/widgets/localizations.dart)
    <asynchronous suspension>
```

**Comment by shameemreza** [comment]
Looks like the issue is releated to assets. Please See the documentation of DefaultAssetBundle: https://api.flutter.dev/flutter/widgets/DefaultAssetBundle-class.html

**Comment by shikha1992** [comment]
> Looks like the issue is releated to assets. Please See the documentation of DefaultAssetBundle: https://api.flutter.dev/flutter/widgets/DefaultAssetBundle-class.html

Everything works fine in debug mode apk. Only issue is with release apk.

**Comment by shameemreza** [comment]
> > Looks like the issue is releated to assets. Please See the documentation of DefaultAssetBundle: https://api.flutter.dev/flutter/widgets/DefaultAssetBundle-class.html
> 
> Everything works fine in debug mode apk. Only issue is with release apk.

Did you try by cleaning cache?

**Comment by VladyslavBondarenko** [comment]
Hi @shikha1992 
does it persist when running after `flutter clean`, `flutter pub get`? could you provide a minimal reproducible project and your `flutter doctor -v`?

**Comment by shikha1992** [comment]
It was cache issue. It works okay. Works now
