### ISSUE TITLE
Unnecessary images are not cached.

### ISSUE THREAD

**Issue by violet-dev** [flutter/flutter#61838]
![asfasfasf1d11d](https://user-images.githubusercontent.com/66541802/87901398-e2102900-ca91-11ea-83c8-2d49e36c1efd.png)

This is my code where the above bug occurs.
https://github.com/project-violet/violet/blob/dev/lib/pages/viewer/vertical_viewer_widget.dart
Whatever method I use, all images are live.
So the imageCache.clear(); function doesn't work.
I've erased the problematic functions and tested image.network, networkimage, and cachednetworkimage.
Using `PaintingBinding.instance.imageCache.clearLiveImages();` works fine, but this doesn't seem to be the preferred solution.

I think https://github.com/flutter/flutter/issues/47378 is not my problem.
The only thing is that the images are not cached when the widget is disposed.

**Comment by iapicca** [comment]
Hi @violet-dev 
[cached_network_image](https://pub.dev/packages/cached_network_image) is a 3rd party plugin, 
if the problem is specific for said plugin please open an issue in the dedicated [github](https://github.com/Baseflow/flutter_cached_network_image/issues);

if you believe the issue is with flutter itself please provide 
your `flutter doctor -v`,
 your `flutter run --verbose`
and a minimal complete reproducible code sample that does not use 3rd party plugins
Thank you

**Comment by violet-dev** [comment]
This problem occurs intermittently for all image widget using imageprovider, such as image.network, networkimage, and cachednetworkimage.
First, I could solve this problem by calling `ImageChache::evict` directly.
This doesn't seem to be a fundamental solution. I will make a sample code later and post it.

```
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18362.900], locale ko-KR)
    • Flutter version 1.19.0-4.3.pre at C:\Dev\flutter
    • Framework revision 8fe7655ed2 (3 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at F:\android-sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = F:\android-sdk
    • Java binary at: F:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at F:\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\rollrat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (4 available)
    • SM N960N            • 28bc93d820057ece • android-arm64  • Android 9 (API 28)
    • AOSP on IA Emulator • emulator-5554    • android-x86    • Android 9 (API 28) (emulator)
    • Web Server          • web-server       • web-javascript • Flutter Tools
    • Chrome              • chrome           • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @violet-dev 
Can you please provide your `flutter run --verbose` and a minimal reproducible code sample that does not use 3rd party plugins
Thank you
