### ISSUE TITLE
AnimatedBuilder is throwing an exception

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#6183]
## Steps to Reproduce

Attempted to run `main.dart` with following code and received an error message instructing to report ticker assertion. 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/animation.dart';

void main() {
  runApp(new LogoApp());
}

class LogoApp extends StatefulWidget {
  LogoAppState createState() => new LogoAppState();
}

class LogoAppState extends State<LogoApp> with SingleTickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(
      duration: const Duration(milliseconds: 2000),
      vsync: this,
    )..forward();
  }

  @override
  Widget build(BuildContext context) {
    Animation<double> animation =
        new Tween(begin: 0.0, end: 200.0).animate(_controller);
    return new Container(
      padding: const EdgeInsets.symmetric(vertical: 10.0),
      child: new AnimatedBuilder(
        animation: animation,
        builder: (BuildContext context) {
          return new Image.asset(
            name: 'assets/flutter_logo.png',
            width: animation.value,
            height: animation.value,
            fit: ImageFit.contain
          );
        }
      )
    );
  }
}
```

## Flutter Doctor

quddusc@quddusc:~/Dev/flutter-projects/animation_examples$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/quddusc/flutter/flutter
    • Framework revision b329894b4d (2 hours ago), 2016-10-03 12:52:06
    • Engine revision 71f2871f00
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /usr/local/google/home/quddusc/Android/Sdk
    • Platform android-24, build-tools 24.0.0
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 6P • 84B7N15818000592 • android-arm

## Logs and Crash Reports

quddusc@quddusc:~/Dev/flutter-projects/animation_examples$ flutter run
Launching loader on Nexus 6P...
--------- beginning of main
Observatory listening on http://127.0.0.1:8108
Diagnostic server listening on http://127.0.0.1:45648
Syncing files to device...                           2.3s
Synced 8.7MB.
Connected to _flutterView/0xea66f540.
Running lib/main.dart on Nexus 6P...
I/flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown building LogoApp(dirty; state: LogoAppState(478457275; ticker
I/flutter : active)):
I/flutter : type '(BuildContext) => dynamic' is not a subtype of type 'TransitionBuilder' of 'builder'
I/flutter : 
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : 
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      AnimatedBuilder.AnimatedBuilder (package:flutter/src/widgets/transitions.dart:404:20)
I/flutter : #1      LogoAppState.build (/data/user/0/com.yourcompany.animationExamples/cache/animation_examplesjxtpau/lib/main.dart:30:18)
I/flutter : #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2666:23)
I/flutter : #3      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
I/flutter : #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652:5)
I/flutter : #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768:22)
I/flutter : #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647:5)
I/flutter : #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139:14)
I/flutter : #8      Element.updateChild (package:flutter/src/widgets/framework.dart:1970:12)
I/flutter : #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:520:16)
I/flutter : #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:491:5)
I/flutter : #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:437:17)
I/flutter : #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1649:19)
I/flutter : #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:436:13)
I/flutter : #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:337:7)
I/flutter : #15     runApp (package:flutter/src/widgets/binding.dart:369:7)
I/flutter : #16     main (/data/user/0/com.yourcompany.animationExamples/cache/animation_examplesjxtpau/lib/main.dart:5:3)
I/flutter : #17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
I/flutter : #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
Application running.
Type "h" or F1 for this help message; type "q", F10, or ctrl-c to quit.
Type "r" or F5 to perform a hot reload of the app, and "R" to restart the app.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
Syncing files to device...                           1.1s

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
The exception is accurate.  The function you've provided doesn't match the type required by the widget:

https://docs.flutter.io/flutter/material/TransitionBuilder.html

**Comment by abarth** [comment]
`        builder: (BuildContext context) {`

should be 

`        builder: (BuildContext context, Widget child) {`

**Comment by Hixie** [comment]
The analyzer should catch cases like this. Try `flutter analyze`.

**Comment by sethladd** [comment]
It would be even better if the analyzer said this:

"'builder' named parameter received a type of '(BuildContext) => dynamic', which does not match the expected type of 'TransitionBuilder' ('(BuildContext, Widget) => Widget')"

The current error: `type '(BuildContext) => dynamic' is not a subtype of type 'TransitionBuilder' of 'builder'` is a bit hard to grok. What is a TransitionBuilder? What does it mean "of builder" ?

cc @bwilkerson @scheglov How easy it is to print out the details for a TypeDef ?

**Comment by Hixie** [comment]
This was supposed to be fixed by https://github.com/dart-lang/sdk/issues/25988

**Comment by sethladd** [comment]
Oh! interesting... maybe we need to reopen the Dart issue?

**Comment by sethladd** [comment]
Done!
