### ISSUE TITLE
Fail to build flutter engine.

### ISSUE THREAD

**Issue by wqyfavor** [flutter/flutter#61847]
I am building Flutter engine on Mac.

Procedure to reproduce.

Follow this document to build up and do gclient sync in my directory. https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment

Switch src/flutter to v1.17.5.

Do gclient sync again.

Use './flutter/tools/gn --unoptimized' to create a target.

Use 'ninja -C out/host_debug_unopt' to build.

The following is the build issue.
Actually on my colleague's computer everything works fine. But from the output of Dart compiler I cannot figure out what on earth is wrong.

➜  src git:(a0fb98a) ninja -C out/host_debug_unopt
ninja: Entering directory `out/host_debug_unopt'
[1/1] Regenerating ninja files
[1158/1260] ACTION //flutter/flutter_frontend_server:frontend_server_dill(//build/toolchain/mac:clang_x64)
FAILED: gen/flutter/flutter_frontend_server/frontend_server.dart.dill 
python ../../third_party/dart/build/gn_run_binary.py compiled_action /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/gen/flutter/flutter_frontend_server/frontend_server.dart.dill.d --depfile_output_filename=gen/flutter/flutter_frontend_server/frontend_server.dart.dill --dfe=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/flutter/flutter_frontend_server/.packages --platform=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/gen/flutter/flutter_frontend_server/frontend_server.dart.dill /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/flutter/flutter_frontend_server/bin/starter.dart
Command failed: /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/gen/flutter/flutter_frontend_server/frontend_server.dart.dill.d --depfile_output_filename=gen/flutter/flutter_frontend_server/frontend_server.dart.dill --dfe=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/flutter/flutter_frontend_server/.packages --platform=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/out/host_debug_unopt/gen/flutter/flutter_frontend_server/frontend_server.dart.dill /Users/wqyfavor/Desktop/Dev/Global/aliflutter/engine_normal/src/flutter/flutter_frontend_server/bin/starter.dart
output: ../../third_party/dart/pkg/meta/lib/meta.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/collection.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/algorithms.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/canonicalized_map.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/combined_wrappers/combined_iterable.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/combined_wrappers/combined_list.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/combined_wrappers/combined_map.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/comparators.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/empty_unmodifiable_set.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/equality.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/equality_map.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/equality_set.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/functions.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/iterable_zip.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/priority_queue.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/queue_list.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/union_set.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/union_set_controller.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/unmodifiable_wrappers.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/utils.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/collection/lib/src/wrappers.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/typed_data/lib/typed_buffers.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../third_party/dart/third_party/pkg/typed_data/lib/typed_data.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.8.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^

[1164/1260] ACTION //third_party/dart/utils/analysis_server:analysis_server_dill(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.

**Comment by jason-simmons** [comment]
Try running `git clean -fdx` in the `src/flutter` directory in the engine source tree.

The initial run of `gclient sync` using the engine master branch created a `flutter_frontend_server/.dart_tool/package_config.json` file.  If you switch to the 1.17.5 version of the engine sources, the `package_config.json` file is not automatically removed.

During the build the Dart SDK (from the 1.17.5 engine) then sees the version metadata in that `package_config.json` (from the master engine) and thinks that there is a mismatch.

**Comment by wqyfavor** [comment]
> Try running `git clean -fdx` in the `src/flutter` directory in the engine source tree.
> 
> The initial run of `gclient sync` using the engine master branch created a `flutter_frontend_server/.dart_tool/package_config.json` file. If you switch to the 1.17.5 version of the engine sources, the `package_config.json` file is not automatically removed.
> 
> During the build the Dart SDK (from the 1.17.5 engine) then sees the version metadata in that `package_config.json` (from the master engine) and thinks that there is a mismatch.

Thanks.

**Comment by kelidon** [comment]
> Try running `git clean -fdx` in the `src/flutter` directory in the engine source tree.
> 
> The initial run of `gclient sync` using the engine master branch created a `flutter_frontend_server/.dart_tool/package_config.json` file. If you switch to the 1.17.5 version of the engine sources, the `package_config.json` file is not automatically removed.
> 
> During the build the Dart SDK (from the 1.17.5 engine) then sees the version metadata in that `package_config.json` (from the master engine) and thinks that there is a mismatch.

Could you provide an information on  ```src/flutter```  directory location, I think I'm missing it.
