### ISSUE TITLE
 Failed assertion: line 4973 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by fathah** [flutter/flutter#61848]
I am stuck in this error. When I pop from a screen to a searchDelegate, I am getting this error. Whats the problem??
```
════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2625 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4973 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
    MaterialApp 
```

**Comment by iapicca** [comment]
Hi @fathah 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
