### ISSUE TITLE
TextField Paste not work

### ISSUE THREAD

**Issue by liujiakuoyx** [flutter/flutter#61852]
please click the link to see the picture:
![image](https://github.com/liujiakuoyx/liujiakuoyx.github.io/blob/master/images/1595238684310493.gif?raw=true)
only inputFormatters is not empty, cut all text in the textfield,paste will not work.

I found the problematic code：
//Use the last formatted value when an identical repeat pass is detected.
![image](https://user-images.githubusercontent.com/22370823/87925707-41326580-cab3-11ea-9947-d09ffa1f144e.png)

**Comment by iapicca** [comment]
Hi @liujiakuoyx 
Can you please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by liujiakuoyx** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/liujiakuo/development/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/liujiakuo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/liujiakuo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SEA AL10 • 6HJ4C19703046088 • android-arm64 • Android 10 (API 29)

**Comment by liujiakuoyx** [comment]
On my phone, this is a problem that will definitely arise.
```
            TextField(
                    maxLines: 5,
                    minLines: 1,
                    inputFormatters: [
                      LengthLimitingTextInputFormatter(100),
                    ],
                    cursorColor: Color.fromRGBO(40, 194, 144, 0.7),
                    scrollPadding: EdgeInsets.symmetric(vertical: 10),
                    style: TextStyle(
                      color: Colors.black54,
                      fontSize:16.0,
                      fontWeight: FontWeight.w400,
                    ),
                    enableInteractiveSelection: true,
                    decoration: InputDecoration(
                      isDense: true,
                      hintText: '请输入消息',
                      hintStyle: TextStyle(
                        color: Colors.black54,
                        fontSize: 16.0,
                        fontWeight: FontWeight.w400,
                      ),
                      filled: true,
                      fillColor: Colors.transparent,
                      border: OutlineInputBorder(),
                    ),
                  )
```

**Comment by iapicca** [comment]
Hi @liujiakuoyx 
testing the code below with the latest master

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);
  static const Widget _home = MyHomePage(key: Key('home'));
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: TextField(
            maxLines: 5,
            minLines: 1,
            inputFormatters: [
              LengthLimitingTextInputFormatter(100),
            ],
            cursorColor: const Color.fromRGBO(40, 194, 144, 0.7),
            scrollPadding: const EdgeInsets.symmetric(vertical: 10),
            style: const TextStyle(
              color: Colors.black54,
              fontSize: 16.0,
              fontWeight: FontWeight.w400,
            ),
            enableInteractiveSelection: true,
            decoration: const InputDecoration(
              isDense: true,
              hintText: '请输入消息',
              hintStyle: const TextStyle(
                color: Colors.black54,
                fontSize: 16.0,
                fontWeight: FontWeight.w400,
              ),
              filled: true,
              fillColor: Colors.transparent,
              border: const OutlineInputBorder(),
            ),
          ),
        ),
      );
}

```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/nevercode/development/flutter_master
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

It seems to behave as intended ([video](https://photos.app.goo.gl/A7fj4vN7vMSo2p6X7))
Does the code above represent the issue you are describing?
Thank you

**Comment by liujiakuoyx** [comment]
Please do not enter any text after cutting. I found that English is no problem. Chinese or some continuous numbers, such as "123", will cause the above problems.
Thank you

**Comment by liujiakuoyx** [comment]
This may be related to the input method software. The first gif is Sogou input method, and this video picture is Baidu input method. The back button of Baidu input method is invalid after pasting, and the focus must be switched. And some other problems appeared in the video.
https://github.com/liujiakuoyx/liujiakuoyx.github.io/blob/master/images/1595250226248791.mp4

**Comment by darrenaustin** [comment]
cc @justinmc

**Comment by justinmc** [comment]
I'm not able to reproduce this using @iapicca's code on an Android simulator at API level 30.  Is there anything I'm doing wrong?

![unpasteable](https://user-images.githubusercontent.com/389558/87998731-9a979600-caad-11ea-886c-5db1e27bf25d.gif)

**Comment by liujiakuoyx** [comment]
This is me running on an Android simulator at API level 30.
https://github.com/liujiakuoyx/liujiakuoyx.github.io/blob/master/images/textField.gif

And this is my code：
https://github.com/liujiakuoyx/testTextField

> I'm not able to reproduce this using @iapicca's code on an Android simulator at API level 30. Is there anything I'm doing wrong?
> 
> ![unpasteable](https://user-images.githubusercontent.com/389558/87998731-9a979600-caad-11ea-886c-5db1e27bf25d.gif)

This is me running on an Android simulator at API level 30.
https://github.com/liujiakuoyx/liujiakuoyx.github.io/blob/master/images/textField.gif

And this is my code：
https://github.com/liujiakuoyx/testTextField

**Comment by justinmc** [comment]
@liujiakuoyx Can you try on the master channel?  Maybe the behavior has changed recently.  I tried using your code and still couldn't reproduce it.

**Comment by VladyslavBondarenko** [comment]
I can reproduce it with current stable `1.17.5` running on Redmi Note 7 Android 9 (API 28) - paste doesn't work when value is copied by 'cut' and copied words start with a number (paste works if you paste it after 'copy' instead of 'cut'). 
But not with current beta `1.20.0-7.2.pre` and master `1.21.0-2.0.pre.114`. Seems to be fixed, so there is no need to track the issue.
@liujiakuoyx please comment if your results are different and I'll reopen

**Comment by liujiakuoyx** [comment]
It helped me a lot, thank you. I wish you a happy life and work. @VladyslavBondarenko
