### ISSUE TITLE
iOS 14 app miss SF font

### ISSUE THREAD

**Issue by alexmay23** [flutter/flutter#61858]
Not sure where is a problem, but the same build on iOS 13 uses SF font, but when I run on IOS 14 it doesn't use SF, and font looks totally different.

**Comment by VladyslavBondarenko** [comment]
Hi @alexmay23 
please follow up on https://github.com/flutter/flutter/issues/60034, https://github.com/flutter/flutter/issues/60034
closing as duplicate. If you disagree please comment and I'll reopen
