### ISSUE TITLE
Task :app:compileFlutterBuildRelease FAILED

### ISSUE THREAD

**Issue by attare026** [flutter/flutter#61855]
when I build a release app or bundle its face like this error
and when run on my device debug its runs perfectly!
please help!!!

## Android Studio

```bash
Dart snapshot generator failed with exit code -1073741819

Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -1073741819
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter SDK\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'G:\flutter SDK\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 11s
Running Gradle task 'assembleRelease'...                          493.9s (!)
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
* Where:
Script 'G:\flutter SDK\packages\flutter_tools\gradle\flutter.gradle' line: 780

[ +133 ms] > Task :app:compileFlutterBuildRelease FAILED
[ +400 ms] FAILURE: Build failed with an exception.
[   +7 ms] * Where:
[   +2 ms] Script 'G:\flutter SDK\packages\flutter_tools\gradle\flutter.gradle' line: 780
[   +2 ms] * What went wrong:
[   +2 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[   +1 ms] > Process 'command 'G:\flutter SDK\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[   +1 ms] 1 actionable task: 1 executed
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 5m 5s
[+1275 ms] Running Gradle task 'assembleRelease'... (completed in 307.6s, longer than expected)
[  +14 ms] "flutter apk" took 310,145ms.
Gradle task assembleRelease failed with exit code 1

```

```console
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-GB)
    • Flutter version 1.17.5 at G:\flutter SDK
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at E:\AndroidSDK
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • M2004J19C • 2c4e9be70405 • android-arm64 • Android 10 (API 29)

• No issues found!

```

when I build a release app or bundle its face like this error
and when run on my device debug its runs perfectly!
please help!!!

**Comment by iapicca** [comment]
Hi @attare026 
does this possible [solution](https://github.com/flutter/flutter/issues/60868#issuecomment-654091949) work for you?
Thank you

**Comment by attare026** [comment]
> Hi @attare026
> does this possible [solution](https://github.com/flutter/flutter/issues/60868#issuecomment-654091949) work for you?
> Thank you

Hi @iapicca show like error
Switching to flutter channel 'beta'...
git: error: Your local changes to the following files would be overwritten by checkout:
git:    packages/flutter_tools/BUILD.gn
git:    packages/flutter_tools/README.md
git:    packages/flutter_tools/bin/fuchsia_attach.dart
git:    packages/flutter_tools/bin/fuchsia_tester.dart
git:    packages/flutter_tools/bin/macos_assemble.sh
git:    packages/flutter_tools/bin/tool_backend.dart
git:    packages/flutter_tools/bin/xcode_backend.sh
git:    packages/flutter_tools/gradle/aar_init_script.gradle
git:    packages/flutter_tools/gradle/flutter.gradle
git:    packages/flutter_tools/gradle/resolve_dependencies.gradle
git:    packages/flutter_tools/lib/executable.dart
git:    packages/flutter_tools/lib/runner.dart
git:    packages/flutter_tools/lib/src/android/android_builder.dart
git:    packages/flutter_tools/lib/src/android/android_console.dart
git:    packages/flutter_tools/lib/src/android/android_device.dart
git:    packages/flutter_tools/lib/src/android/android_emulator.dart
git:    packages/flutter_tools/lib/src/android/android_sdk.dart
git:    packages/flutter_tools/lib/src/android/android_workflow.dart
git:    packages/flutter_tools/lib/src/android/gradle.dart
git:    packages/flutter_tools/lib/src/android/gradle_errors.dart
git:    packages/flutter_tools/lib/src/android/gradle_utils.dart
git:    packages/flutter_tools/lib/src/aot.dart
git:    packages/flutter_tools/lib/src/application_package.dart
git:    packages/flutter_tools/lib/src/artifacts.dart
git:    packages/flutter_tools/lib/src/asset.dart
git:    packages/flutter_tools/lib/src/base/build.dart
git:    packages/flutter_tools/lib/src/base/config.dart
git:    packages/flutter_tools/lib/src/base/file_system.dart
git:    packages/flutter_tools/lib/src/base/fingerprint.dart
git:    packages/flutter_tools/lib/src/base/io.dart
git:    packages/flutter_tools/lib/src/base/net.dart
git:    packages/flutter_tools/lib/src/base/os.dart
git:    packages/flutter_tools/lib/src/base/signals.dart
git:    packages/flutter_tools/lib/src/base/terminal.dart
git:    packages/flutter_tools/lib/src/base/time.dart
git:    packages/flutter_tools/lib/src/base/user_messages.dart
git:    packages/flutter_tools/lib/src/base/utils.dart
git:    packages/flutter_tools/lib/src/base/version.dart
git:    packages/flutter_tools/lib/src/build_info.dart
git:    packages/flutter_tools/lib/src/build_runner/build_runner.dart
git:    packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart
git:    packages/flutter_tools/lib/src/build_runner/web_compilation_delegate.dart
git:    packages/flutter_tools/lib/src/build_system/build_system.dart
git:    packages/flutter_tools/lib/src/build_system/depfile.dart
git:    packages/flutter_tools/lib/src/build_system/file_hash_store.dart
git:    packages/flutter_tools/lib/src/build_system/source.dart
git:    packages/flutter_tools/lib/src/build_system/targets/android.dart
git:    packages/flutter_tools/lib/src/build_system/targets/assets.dart
git:    packages/flutter_tools/lib/src/build_system/targets/dart.dart
git:    packages/flutter_tools/lib/src/build_system/targets/ios.dart
git:    packages/flutter_tools/lib/src/build_system/targets/linux.dart
git:    packages/flutter_tools/lib/src/build_system/targets/macos.dart
git:    packages/flutter_tools/lib/src/build_system/targets/web.dart
git:    packages/flutter_tools/lib/src/build_system/targets/windows.dart
git:    packages/flutter_tools/lib/src/bundle.dart
git:    packages/flutter_tools/lib/src/cache.dart
git:    packages/flutter_tools/lib/src/codegen.dart
git:    packages/flutter_tools/lib/src/commands/analyze.dart
git:    packages/flutter_tools/lib/src/commands/analyze_base.dart
git:    packages/flutter_tools/lib/src/commands/analyze_continuously.dart
git:    packages/flutter_tools/lib/src/commands/analyze_once.dart
git:    packages/flutter_tools/lib/src/commands/assemble.dart
git:    packages/flutter_tools/lib/src/commands/build.dart
git:    packages/flutter_tools/lib/src/commands/build_aar.dart
git:    packages/flutter_tools/lib/src/commands/build_apk.dart
git:    packages/flutter_tools/lib/src/commands/build_appbundle.dart
git:    packages/flutter_tools/lib/src/commands/build_bundle.dart
git:    packages/flutter_tools/lib/src/commands/build_fuchsia.dart
git:    packages/flutter_tools/lib/src/commands/build_ios.dart
git:    packages/flutter_tools/lib/src/commands/build_ios_framework.dart
git:    packages/flutter_tools/lib/src/commands/build_linux.dart
git:    packages/flutter_tools/lib/src/commands/build_macos.dart
git:    packages/flutter_tools/lib/src/commands/build_web.dart
git:    packages/flutter_tools/lib/s
git: error: The following untracked working tree files would be overwritten by checkout:
git:    packages/flutter_tools/lib/src/base/platform.dart
git: Please move or remove them before you switch branches.
git: Aborting
Switching channels failed with error code 1.

**Comment by attare026** [comment]
Hello please anyone help me! :(

**Comment by TahaTesser** [comment]
Hi @attare026 
Looks like you cannot upgrade due to local changes, please reset setup using git, execute `git reset --hard` flutter setup folder then execute `flutter channel beta` or reinstall beta setup from official website 

After upgrading to `beta` channel, try the possible [solution](https://github.com/flutter/flutter/issues/60868#issuecomment-654091949)

Thank you

**Comment by attare026** [comment]
> Hi @attare026
> Looks like you cannot upgrade due to local changes, please reset setup using git, execute `git reset --hard` flutter setup folder then execute `flutter channel beta` or reinstall beta setup from official website
> 
> After upgrading to `beta` channel, try the possible [solution](https://github.com/flutter/flutter/issues/60868#issuecomment-654091949)
> 
> Thank you
@TahaTesser Thanks your support but
this not work for me I have already try and now again try to reinstall goto this guideline but face the same error!

**Comment by attare026** [comment]
Any one face this problem?

**Comment by iapicca** [comment]
Hi @attare026 
as @TahaTesser pointed out the issue seems to be specific to your installation,
please try these [steps](https://github.com/flutter/flutter/issues/44165#issuecomment-612614373) (or alternatively [these other](https://github.com/flutter/flutter/issues/44165#issuecomment-566814253)),
then run `flutter channel beta -v` and finally `flutter upgrade -f -v`
Thank you

**Comment by vaaniiaa** [comment]
@attare026 
hi buddy
I'm facing same problem , could you resolve this issue finally?
Kindly let me know if there is any solution
