### ISSUE TITLE
Assistance Required: setState issue;

### ISSUE THREAD

**Issue by ritvij-saxena** [flutter/flutter#61865]
Hello, 
I was trying to implement a scaffold, where the body is dynamically assigned according to the ListTile clicked in the drawer. Earlier the widget Option1Content widget used to get the value after the setState however this has stopped since I updated my flutter. Any assistance would be greatly appreciated. Thank you.

**CODE** 
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatefulWidget{
  MyWidgetState createState()=> MyWidgetState();
}
class MyWidgetState extends State<MyWidget> {
  bool status;
  Widget myBody;
  GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  
   void closeDrawer() {
    if (_scaffoldKey.currentState.isDrawerOpen) {
      _scaffoldKey.currentState.openEndDrawer();
    }
  }
  
  @override
  void initState(){
    super.initState();
    status = false;
    myBody = Option1Content(status:status);
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key:_scaffoldKey,
    appBar:AppBar(
      iconTheme: IconThemeData(color: Colors.black),
      elevation:0,
      backgroundColor:Colors.transparent,
    actions:[
      Switch(
        inactiveThumbColor: Colors.black,
        activeColor: Colors.green,
        value:status,
        onChanged:(value){
          setState((){
            status=value;
          });
        })
    ]
    ),
      drawer: Drawer(
        child:Center(child:ListView(children:[
          DrawerHeader(
                      child: Column(
                        children: <Widget>[
                          CircleAvatar(
                            radius: 50,
                            backgroundColor: Colors.grey,
                          ),
                          Padding(
                            padding: const EdgeInsets.only(
                                left: 8.0, right: 8.0, top: 12.0),
                            child: Text(
                              'Account',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                              ),
                              textScaleFactor: 1.3,
                            ),
                          ),
                        ],
                      ),
                    ),
          ListTile(title:Center(child:Text('Option 1')),onTap:(){
            closeDrawer();
            setState((){
              myBody = Option1Content(status:status);
            });
          }),
          ListTile(title:Center(child:Text('Option 2')),onTap:(){
            closeDrawer();
            setState((){
              myBody = Center(child:Text('Option 2 Content'));
            });
          }),
          ListTile(title:Center(child:Text('Option 3')),onTap:(){
            closeDrawer();
            setState((){
              myBody = Center(child:Text('Option 3 Content'));
            });
          }),
        ]))
      ),
      body: myBody
    );
  }
}

class Option1Content extends StatefulWidget {
  final bool status;
  Option1Content({@required this.status});

  @override
  _Option1ContentState createState() => _Option1ContentState();
}

class _Option1ContentState extends State<Option1Content> {

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('${widget.status}'),
    );
  }
}

My Question on StackOverflow: https://stackoverflow.com/questions/62997547/obtain-variable-value-from-a-different-widget

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
