### ISSUE TITLE
How to run code in Backend to build and destroy widget in Flutter app

### ISSUE THREAD

**Issue by akashtechnology** [flutter/flutter#61861]
I wanna build an android app that I can control in Backend, such as I can run the code on the server, and rebuild the widgets in the flutter app while running on android. 

I am a new programmer, and right not I don't have much understanding, So please anyone can tell me how I could achieve this.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
