### ISSUE TITLE
Re-enable lint script 

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#61875]
[lint.sh](https://github.com/flutter/engine/blob/master/ci/lint.sh) script fails for engine files. Example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8874483205899836240/+/steps/lint_test/0/stdout 

We disabled the script for now. 

(1) We should either change the script or fix the code. 
(2) We should re-enable the script on LUCI engine and web_engine recipes.

**Comment by gaaclarke** [comment]
cc @gaaclarke turned off in https://flutter-review.googlesource.com/c/recipes/+/4460

**Comment by jason-simmons** [comment]
@gaaclarke

**Comment by gaaclarke** [comment]
https://flutter-review.googlesource.com/c/recipes/+/4561  CL reenabling.

**Comment by pedromassangocode** [comment]
@gaaclarke can you confirm whether https://github.com/flutter/engine/pull/19895 fixed this issue or not?

**Comment by gaaclarke** [comment]
The linter was turned back on after changes were made, yes.
