### ISSUE TITLE
hi i want to get private video from vimeo but vimeo require domain to add to the list to get permission play this video in my application what domain or url will i give?

### ISSUE THREAD

**Issue by shahadsameir** [flutter/flutter#61874]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by praveengodz** [comment]
> ## Steps to Reproduce
> 1. Run `flutter create bug`.
> 2. Update the files as follows: ...
> 3. ...
> 
> **Expected results:**
> 
> **Actual results:**
> 
> Logs

@shahadsameir did you get any solution for this ?
