### ISSUE TITLE
Installation fails in Ubuntu 18 running on top of Android 8.1.0.

### ISSUE THREAD

**Issue by l3laze** [flutter/flutter#61883]
Hi,

I'm using my mobile for development and have been trying to get this working and it doesn't even make it through the initial installation process...lol. I installed all dependencies including `libglu1-mesa`, downloaded the latest stable Linux installation from the website, copied it into the chroot environment and extracted the archive.  When I try to run `flutter --help`, `flutter doctor`, or `flutter doctor -v` it fails immediately complaining that `...dart-sdk/bin/dart` isn't a file or directory. I tried explicitly adding `...dart-sdk/bin` to the path and it still fails.

When I tried to `rm -rf flutter` it whined about a  `.pack` in a deep-nested internal `.git` folder not being empty. Had a similar issue with another project that I tried to use recently and the only fix was nuking the environment and starting over. So, I nuked this.

I am using Ubuntu 18.04 through UserLAnd running on Android 8.1.0 with an arm-v8a processor. It is not rooted and I used a fresh environment (container?) where I ran `apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y`. The only unnecessary packages installed were `bash-completion` and `nano`.

There are no special characters in the path and `.../dart-sdk/bin` exists, and all directories and executables inside the flutter directory are rwx for the user all the way down to `dart-sdk/bin`.

**Comment by jonahwilliams** [comment]
Please see https://github.com/flutter/flutter/issues/56992

We do not currently support arm as a host platform for development - you probably downloaded the x64 binaries.

**Comment by l3laze** [comment]
Wow; I'm sorry... I should've known I forgot something. Thank you.
