### ISSUE TITLE
'embedder_unittests' fails to compile on fuchsia

### ISSUE THREAD

**Issue by arbreng** [flutter/flutter#61898]
The errors all seem OpenGL-related, it's likely we need to rewrite the Fake embedder to use software / not-OpenGL.

See: fxb/48600

**Comment by zanderso** [comment]
Copied from the upstream issue:

> These unittests run the engine inside of a Fake embedder, and do pixel-comparisons on the output images.  They work very similar to our in-tree pixel tests for Scenic.  They are also the most important unittests in the entire suite -- they test the embedder API contract that we are moving towards.
>
> Unfortunately, the Fake embedder is written using OpenGL so it won't even compile on Fuchsia :(  So this task involves writing a software-rendering version of the fake embedder.  That will let it compile on Fuchsia and also increase the hermeticity of the test on all embedder platforms (desktop Linux, Mac, Windows) -- so there is even some non-Fuchsia impact here as well.
>
> The Fake embedder does a test version of what Scenic or a Wayland compositor do -- combining a bunch of rectangular layers into one and applying some simple effects like opacity.  That means this would be a really fun rendering task, and perfect for someone who wants to learn a little bit more about what a compositor does or wanting something very visual.

**Comment by gw280** [comment]
cc @chinmaygarde. I'm going to take a quick look at this, see what it needs

**Comment by chinmaygarde** [comment]
@gw280 Are you still working on this? If not, please feel free to clear your assignment. Thanks.

**Comment by gw280** [comment]
Thanks for this. Sorry, forgot to close out the issue.
