### ISSUE TITLE
Blur filter samples colors from outside its area

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#61891]
The blur filter is sampling pixels from outside the area that it is clipped to. Is there any way to limit a blur strictly to the contents of an image, as if applying a gaussian blur in an image editor? See images below.

I also posted [a question](https://stackoverflow.com/questions/62988341/how-can-the-blur-filter-be-stopped-from-sampling-colors-surrounding-a-blurred-im) on StackOverflow.

## Steps to Reproduce

Take a look at the example below:

```dart
class BlurDemo extends StatelessWidget {
  BlurDemo({Key key}) : super(key: key);

  final String imageUrl =
      'https://dogtime.com/assets/uploads/2018/10/puppies-cover-1280x720.jpg';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Blur Demo'),
      ),
      backgroundColor: Colors.black,
      body: Center(
        child: SizedBox(
          width: 250,
          height: 250,
          child: FittedBox(
            fit: BoxFit.cover,
            child: Stack(children: [
              Image.network(imageUrl),
              Positioned.fill(
                child: ClipRRect(
                    child: BackdropFilter(
                        filter: ImageFilter.blur(sigmaX: 20.0, sigmaY: 20.0),
                        child: Container(color: Colors.black.withAlpha(0))),
    ))])))));}}
```

**Expected results:**
Expecting the blur to only sample from pixels directly behind the filter (in this case, the image).

[Mockup](https://i.stack.imgur.com/hi4D7.png)

**Actual results:**
The blur filter is sampling from pixels outside the area that the blur is clipped to (in this case, the black background). The result is a subtle black edge bleeding into the blurred image.

[Image example](https://i.stack.imgur.com/3jBFI.png)

The effect is very subtle, but it does have a significant visual impact in my use case.

**Comment by ethanblake4** [comment]
Try using [ImageFiltered](https://api.flutter.dev/flutter/widgets/ImageFiltered-class.html) instead of BackdropFilter.

**Comment by doppio** [comment]
That's exactly what I needed. Thank you!
