### ISSUE TITLE
sir when i run this app in emulator,it runs correctly .when i see a emulator the app size is 97 mb,the app size is large .i have doubt if i use flutter for my project app size would bigger ,what is the solution for it

### ISSUE THREAD

**Issue by deepakzero** [flutter/flutter#61890]
sir when i run this app in emulator,it runs correctly .when i see a emulator the app size is 97 mb,the app size is large .i have doubt if i use flutter for my project the  app size would bigger ,what is the solution for it

the size of app in flutter is high how to develop the big projects using flutter

**Comment by jonahwilliams** [comment]
You already filled https://github.com/flutter/flutter/issues/61893
