### ISSUE TITLE
whether the flutter is suited for big projects with with low app size

### ISSUE THREAD

**Issue by deepakzero** [flutter/flutter#61893]
sir when i flutter counter app run this app in emulator,it runs correctly .when i see a emulator the app size is 97 mb,the app size is large .
i have doubt if i use flutter for my project app size would bigger ,what is the solution for it
pls help me to clear this

**Comment by jonahwilliams** [comment]
@deepakzero  please read https://flutter.dev/docs/perf/app-size , you cannot use emulator/debug size as a proxy for the resulting artifact size

**Comment by deepakzero** [comment]
> @jonahwilliams when i run the of to see app size 
C:\Users\welcome\AndroidStudioProjects\flutter_app>flutter build apk --split-per-abi
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      79.6s
√ Built build\app\outputs\apk\release\app-armeabi-v7a-release.apk (5.1MB).
√ Built build\app\outputs\apk\release\app-arm64-v8a-release.apk (5.4MB).
√ Built build\app\outputs\apk\release\app-x86_64-release.apk (5.6MB).

is this app take 5 to 6 mb for the complete installition from playstore

**Comment by deepakzero** [comment]
@jonahwilliams  iam beginner in flutter pls explain briefly about you cannot use emulator/debug size as a proxy for the resulting artifact size with simple example
