### ISSUE TITLE
[FATAL:Paint.cpp(64)] Check failed: Dart_IsList(data).

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#619]
When I launch the material gallery and go to the Selection Controls page, I crash in the engine on the following assert:

```
Paint DartConverter<Paint>::FromDart(Dart_Handle dart_paint) {
  // ...
  DCHECK(Dart_IsList(data));
```

- [ ] We should handle bogus data more gracefully (by throwing an exception on the Dart side), and
- [x] we shouldn't be sending over bogus data in the first place.

**Comment by jason-simmons** [comment]
_RenderSwitch was creating a Paint with a null color

https://github.com/flutter/flutter/pull/661

**Comment by abarth** [comment]
I fixed the engine not to crash when there's a null color.
