### ISSUE TITLE
"xcdevice" process never exits on macOS

### ISSUE THREAD

**Issue by zhouyifan0904** [flutter/flutter#61905]
Every time I launch my project directory with VS Code on macOS, a xcdevice process is started but it never exits when I'm done.

Over time, I have multiple processes running when I ps:
<img width="1117" alt="Screen Shot 2020-07-20 at 3 27 16 PM" src="https://user-images.githubusercontent.com/13145408/87992623-864b9d00-ca9d-11ea-8a69-ff955eef5383.png">
 
Is this something that need to be fixed? Should I just manually kill these processes?

**Comment by TahaTesser** [comment]
Hi @zhouyifan0904 
Can you please provide your `flutter doctor -v`? i can see that process but it's normal to see it running in the running for couple of hours, looks similar to android daemon process
Thank you

**Comment by zhouyifan0904** [comment]
> Hi @zhouyifan0904
> Can you please provide your `flutter doctor -v`? i can see that process but it's normal to see it running in the running for couple of hours, looks similar to android daemon process
> Thank you

![carbon](https://user-images.githubusercontent.com/13145408/88096901-3ed01a00-cb4c-11ea-97a8-cc6df5c489c2.png)

**Comment by TahaTesser** [comment]
Hi @zhouyifan0904 
Looking. around, it doesn't look it's related to Flutter itself,  its part of Xcode , you can notice it without even using Flutter and xcdevice processes itself don't take much CPU and memory usage  when running in the background. If you uninstall Xcode and restart your Mac, it should go away 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
