### ISSUE TITLE
google sign in not working in release apk

### ISSUE THREAD

**Issue by kittugithubpandey** [flutter/flutter#61935]
google signin not working in release apk

**Comment by TahaTesser** [comment]
Hi @kittugithubpandey 
Make sure you've added `internet` permission for release https://stackoverflow.com/a/2378619
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by GaspardMerten** [comment]
Not only that but you should make sure that you uploaded the correct release key of your app to Google platform! The debug key and the release key are not the same. And if you are using the playstore to release your app, then make sure that if you enabled the auto-signing, you are using the key provided in the Play Console.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by kittugithubpandey** [comment]
google signin not working in release apk

cupertino_icons: ^1.0.0
  http: ^0.12.2
  shared_preferences: ^0.5.10
  connectivity: ^0.4.9+2
  flutter_facebook_login: 3.0.0
  google_sign_in: 4.5.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  fluttertoast: 7.1.1

**Comment by kittugithubpandey** [comment]
please provide support asap.

**Comment by kittugithubpandey** [comment]
Future<void> _handleGetContact() async {
    setState(() {

    });
    final http.Response response = await http.get('https://people.googleapis.com/v1/people/me/connections''?requestMask.includeField=person.names',
      headers: await _currentUser.authHeaders,
    );
    if(_currentUser.displayName != null || _currentUser.displayName != ""){
      String name = _currentUser.displayName.toString();
      var array = name.split(" ");
      first_name = array[0];
      last_name = array[1];
      email = _currentUser.email;
      print(first_name+"\t"+last_name+"\t"+email);
      Fluttertoast.showToast(
          msg: first_name+"\t"+last_name+"\t"+email,
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
          timeInSecForIosWeb: 1,
          backgroundColor: Colors.red,
          textColor: Colors.white,
          fontSize: 16.0
      );
    }
    if (response.statusCode != 200) {
      setState(() {
      });
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {

      }
      else {

      }
    });
  }

  String _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic> connections = data['connections'];
    final Map<String, dynamic> contact = connections?.firstWhere(
          (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic> name = contact['names'].firstWhere(
            (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> googleSignin() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: <String>[
      'email',
      'https://www.googleapis.com/auth/contacts.readonly',
    ],
  );

**Comment by TahaTesser** [comment]
Hi @kittugithubpandey 
Your code sample is incomplete, make sure you've filled out the  google auth screen from https://pub.dev/packages/google_sign_in#android-integration to make it work in production 

`google_sign_in` works in release mode, try this code sample 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() => runApp(MyApp3());

class MyApp3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
          print("");
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn().then((value) {
        value.authentication.then((valueq) {
          print(valueq.idToken);
        });
      });
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(iSignedIn ? userName : 'empty user name'),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a27c242b0e (7 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by ankit-apk** [comment]
> google signin not working in release apk

To make google auth work in release mode you will have to sign your app first in release mode and then find the SHA1 and SHA256 keys for release build by running 
keytool -list -v -keystore <your keystore path> -alias <your alias>

Add the SHAs in Firebase and update your google sevices.json file.
