### ISSUE TITLE
master could not compile Flokk app

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#61936]
I am trying to compile the gskinner Flokk app for windows, and I get the following error:
```
CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/flokk/flokk_src/windows/flutter/ephemeral/.plugin_symlinks/path_provider_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```
I am on the master branch:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-2.0.pre.83, on Microsoft Windows [Version 10.0.18363.959], locale en-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
[√] Android Studio (version 4.0)
[√] Connected device (3 available)
```

**Comment by TahaTesser** [comment]
Hi @MohiuddinM 
For issues related to `gskinnerTeam/flokk, please open issue on their dedicated github [repository](https://github.com/gskinnerTeam/flokk/issues)

If you believe this is an issue with Flutter
Can you please provide  your `flutter run --verbose -d <Windows device>` and a complete reproducible minimal code sample [without using third party packages](url)
Thank you

**Comment by stuartmorgan** [comment]
This is not a Flutter bug. As the Windows instructions say, "Breaking changes are still common on Windows".

The Flokk README specifically says:

> * Flokk was built on the bleeding edge of Flutter, so make sure to use the master branch in their git repo and checkout commit 9c3f0faa6d.
>    * We're aiming to upgrade to an official Flutter version soon to make this easier.

They've checkin in things like plugin versions that are specific to that version, and there has been a major breaking change since then. You can't use the latest master until they've upgraded.
