### ISSUE TITLE
url_launcher:unknown error when launching url 

### ISSUE THREAD

**Issue by ShengjieGeng** [flutter/flutter#61943]
![image](https://user-images.githubusercontent.com/18364968/88042511-9be4c380-cb7e-11ea-86f2-94cbeb3315ec.png)
here is the url:http://search.m.dangdang.com/search.php?keyword=爱心树

**Comment by GaspardMerten** [comment]
You are using non-standard characters that won't fit correctly in an URL, try using the string returned by Uri.encodeFull(yourUrl) as the request URL!

**Comment by VladyslavBondarenko** [comment]
Thanks @GaspardMerten 
@ShengjieGeng closing as solved
