### ISSUE TITLE
webview_flutter version 0.3.21 - Reg clearCache() method in webview_flutter.dart

### ISSUE THREAD

**Issue by rampal** [flutter/flutter#61953]
Any specific reason reload() method inside clearCache() method
webview_flutter version 0.3.21 
class: webview_flutter.dart
/// Note: Calling this method also triggers a reload.
  Future<void> clearCache() async {
    await _webViewPlatformController.clearCache();
    return reload();
  }

IS IT POSSIBLE TO REMOVE  return reload(); from clearCache() method?
While calling clearCache() method because of reload() see unexpected behaviour.

Thanks,
Rampal

**Comment by VladyslavBondarenko** [comment]
Hi @rampal 
could you describe your case why you need to avoid reload and what do you mean by unexpected behaviour?

**Comment by rampal** [comment]
In Android I am getting data cache issue so in onWebViewCreated: (WebViewController webViewController) async method
I have added webViewController.clearCache();

I load html page in _controllerCompleter.future
          .then((WebViewController webViewController)

_webViewController.loadUrl(initialUrl, headers: headers);

I am injecting data in 
onPageFinished: (String paramVal) async {
          if (javascriptWithData.isNotEmpty) {
            await _webViewController.evaluateJavascript(javascriptWithData);
          }

So what happens when webViewController.clearCache() method being called it tries to reload the page.
IN this case the required information is not being set and because of reload it try to access some javascript function and throws undefined.

I was thinking clearCache() method purpose should be just clear cache and not to have reload() method inside that. If anyone wants to have reload it can be called explicitly.


thanks,
Rampal

**Comment by rampal** [comment]
@VladyslavBondarenko VladyslavBondarenko

ANY update on this?

**Comment by rampal** [comment]
@VladyslavBondarenko VladyslavBondarenko
ANY update on this?

**Comment by craigjwallace** [comment]
Please could this be addressed?

I am finding that reloading the page when clearcache is requested also triggers onPageFinished:

This cuases early terminatrion of my spinkit loading screen.

It isn't logical to have a 'clearcache' function that also forces a reload. : (

**Comment by tavyDesign** [comment]
+1 please fix this!

**Comment by stuartmorgan** [comment]
Closing as resolved; clearing the cache doesn't call reload in version 4.
