### ISSUE TITLE
Samsung One UI keyboard feature is incorrectly treated by flutter app

### ISSUE THREAD

**Issue by philipdolenko** [flutter/flutter#61952]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: lib/main.dart -> Chnage lines 100 - 106 to just TextField()
3. Type some text then use "cursor control" feature (Samsung One UI) to move cursor

**Expected results:** cursor is moving as in native apps

**Actual results:** cursor only moves in one direction (from right to left)

Here how it looks like https://photos.app.goo.gl/rX8MRHNhtM2Zc6JM6

Tested on master and betta (most recent versions)

I understand that this issue is in low priority because its only on Samsung devices but still, it would be nice if the flutter team will look at it.

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-2.0.pre.88, on Mac OS X 10.15.6
    19G73, locale en-UA)
 
[!] Android toolchain - develop for Android devices (Android SDK 
    version 29.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK
      licenses.
      See
      https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
 
[✓] Connected device (3 available)            
    ! Error: Tymofii Dolenko’s iPhone is not connected. Xcode will
      continue when Tymofii Dolenko’s iPhone is connected. (code -13)

! Doctor found issues in 3 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment]
Tried with master `1.21.0-2.0.pre.88` on Samsung SM G950F Android 9 (API 28) and Samsung SM M305F Android 10 (API 29). They have "cursor control" feature too, but cursor moves correctly there. May be a device specific

**Comment by philipdolenko** [comment]
Hi, @VladyslavBondarenko thanks for a quick reply. I have tested on SM G969F (Android 10) and the cursor moves only in one direction. Are you on the latest beta too?

**Comment by VladyslavBondarenko** [comment]
@philipdolenko 
yes, with beta `1.19.0-4.3.pre` as well

**Comment by darshankawar** [comment]
Revisiting this issue and running sample code on S10+ device (Android 12) with One UI version, I was able to swipe the cursor in the textfield properly in both directions:


https://github.com/user-attachments/assets/bac9f1ba-6f41-4dfc-8801-15ea68a690ee


Closing this as not replicable and also considering the age of the issue and lack of activity. If anyone still face this issue with latest stable version, please use new issue template, fill out requested details.
