### ISSUE TITLE
Flutter desktop FFI dlopen fails with file system sandbox blocked open()

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#61950]
I am trying to access a native function, which was written in Golang, on Flutter but unfortunately it throws the error:

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library
(dlopen(/path/to/libhello_ffi.dylib, 1):
no suitable image found.  Did find:
	file system sandbox blocked open() of
'/path/to/libhello_ffi.dylib')
```

## Steps to Reproduce

It works fine if I just directly execute the dart file instead of flutter run.

Am I missing something here?

Usage: Flutter for Desktop (macOS)
OS: macOS catalina 10.15.6

code:
```dart
import 'dart:ffi' as ffi;

typedef PrintHello_func = ffi.Void Function();
typedef PrintHello = void Function();

void ffi_test() {
  var path =
      '/path/to/libhello_ffi.dylib';

  final ffi.DynamicLibrary dylib = ffi.DynamicLibrary.open(path);

  final PrintHello hello = dylib
      .lookup<ffi.NativeFunction<PrintHello_func>>('PrintHello')
      .asFunction();

  hello();
}

```

**Expected results:** Print "Hello World"

**Actual results:** 

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library
(dlopen(/path/to/libhello_ffi.dylib, 1):
no suitable image found.  Did find:
	file system sandbox blocked open() of
'/path/to/libhello_ffi.dylib')

When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      ffi_test (package:squash_archiver/features/home/ui/widgets/ffi_test.dart:17:55)
#3      _HomeScreenState._buildTestFfi.<anonymous closure> (package:squash_archiver/features/home/ui/pages/home_screen.dart:73:13)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#24     _invoke1 (dart:ui/hooks.dart:267:10)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

```

flutter analyze
```
 

```

flutter doctor -v
```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.83, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.21.0-2.0.pre.83 at /Users/username/Library/Application Support/fvm/versions/master
    • Framework revision 9e658bc3d5 (10 hours ago), 2020-07-21 03:56:07 +0200
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.6 19G73

• No issues found!


```

Related Stackoverflow URL: https://stackoverflow.com/q/63014101/1317099

**Comment by dcharkes** [comment]
Thanks for reporting.

> It works fine if I just directly execute the dart file instead of flutter run.

This is something Flutter-desktop specific then. I can have a look, but maybe one of the Flutter-desktop devs can chime in.

**Comment by ganeshrvel** [comment]
I made a stackoverflow post as well, it has better insight into the Flutter desktop - golang integration problem

**https://stackoverflow.com/q/63014101/1317099**

**Comment by dcharkes** [comment]
For completeness sake, do you have the same issues when using C instead of Go? That way we can rule out that it is something Go-specific.

**Comment by ganeshrvel** [comment]
@dcharkes 
Yes it breaks even while calling a c program, I just confirmed.

I cloned the FFI sample repo from https://github.com/dart-lang/samples/tree/master/ffi/hello_world and even it threw an 

```dart
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library
(dlopen(/path/to/hello_world/hello_library/libhello.dylib,
1): no suitable image found.  Did find:
	file system sandbox blocked open() of
'/path/to/hello_world/hello_library/libhello.dylib')

When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      hello_world_ffi (package:squash_archiver/features/home/ui/widgets/ffi/hello_world/hello.dart:8:36)
#3      ffi_test (package:squash_archiver/features/home/ui/widgets/ffi_test.dart:9:3)
#4      _HomeScreenState._buildTestFfi.<anonymous closure> (package:squash_archiver/features/home/ui/pages/home_screen.dart:73:13)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#25     _invoke1 (dart:ui/hooks.dart:267:10)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

```

**Comment by ganeshrvel** [comment]
Oh there is another issue:

using relative path to access the binary file will throw:

```dart
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen(../libhello.dylib, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      main (package:bug/main.dart:11:36)
#3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
#4      _rootRun (dart:async/zone.dart:1190:13)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _runZoned (dart:async/zone.dart:1630:10)
#7      runZonedGuarded (dart:async/zone.dart:1618:12)
#8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by dcharkes** [comment]
> using relative path to access the binary file will throw

Yes, that's a known security feature of MacOS.

@VladyslavBondarenko note that you have a different error message, that does not mention the sandbox. That might simply be that the file does not exist at that path, or the be the same MacOS security feature.

Lets dedicate this issue to the sandbox.

> Yes it breaks even while calling a c program, I just confirmed.

Thanks for confirming.

**Comment by ganeshrvel** [comment]
@dcharkes 


```
> using relative path to access the binary file will throw

Yes, that's a known security feature of MacOS.
```

In that case:
  1. What is the right way to access a binary file for FFI in Flutter (for desktop) if not relative path? 
  2. How do we bundle the native binaries in the release mode?

**Comment by dcharkes** [comment]
> What is the right way to access a binary file for FFI in Flutter (for desktop) if not relative path?

Use an absolute path, and make sure it's in the same or a subfolder of the dart standalone executable or the flutter executable.

> How do we bundle the native binaries in the release mode?

That is an open question. We have a working solution for Flutter iOS and Flutter Android, and workarounds for Dart standalone/pub. But we haven't explored Flutter Desktop yet. For more background see: https://github.com/dart-lang/sdk/issues/36712#issue-436172213

**Comment by stuartmorgan** [comment]
> using a relative path to access the binary file will throw

Relative to what? There are no guarantees about what your working directory will be when running an application, so I'm not sure why you would expect a relative path to work.

> ```
>  var path =
>      '/path/to/libhello_ffi.dylib';
> ```

Is this path a path in your application's bundle, or not? If it's not, failing is expected behavior unless you turned off sandboxing for your application.

**Comment by ganeshrvel** [comment]
Makes sense. Maybe if there was a way to refer to the app's '/Contents/Resources/' directory it had been easier to locate the binary. 

> That is an open question. We have a working solution for Flutter iOS and Flutter Android, and workarounds for Dart standalone/pub. But we haven't explored Flutter Desktop yet. For more background see: 

Anyhow like @dcharkes mentioned, waiting for an official way to bundle binaries along with the desktop apps.

**Comment by stuartmorgan** [comment]
> Is this path a path in your application's bundle, or not?

Can you answer this question please? This is critical information in understanding whether this is actually a bug.

**Comment by ganeshrvel** [comment]
This issue is not related to the path of the native binary.  That was something I attempted and I was told that it wouldn't work due to macOS security policy.

Anyways, I used absolute path to the native binary and the app threw:

```dart
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library
(dlopen(/path/to/hello_world/hello_library/libhello.dylib,
1): no suitable image found.  Did find:
	file system sandbox blocked open() of
'/path/to/hello_world/hello_library/libhello.dylib')

When the exception was thrown, this was the stack:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      hello_world_ffi (package:squash_archiver/features/home/ui/widgets/ffi/hello_world/hello.dart:8:36)
#3      ffi_test (package:squash_archiver/features/home/ui/widgets/ffi_test.dart:9:3)
#4      _HomeScreenState._buildTestFfi.<anonymous closure> (package:squash_archiver/features/home/ui/pages/home_screen.dart:73:13)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#25     _invoke1 (dart:ui/hooks.dart:267:10)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)
```

**Comment by stuartmorgan** [comment]
> This issue is not related to the path of the native binary.

It's not at all clear to me that that's actually been established, thus my question (which your last comment still doesn't answer).

> That was something I attempted and I was told that it wouldn't work due to macOS security policy.

If it's outside your bundle, then yes. If it's inside your bundle, I would expect it to work, and if it doesn't then it's important that we have that information.

> Anyways, I used absolute path to the native binary and the app threw [...] `/path/to/hello_world/hello_library/libhello.dylib`

Again, this is obviously not a real path. Is the actual path in question here inside your application bundle, or not? Please provide the *actual* path, not a made-up path, obfuscating only the minimum needed for privacy (your username if it's in the path, your application name if it's sensitive).

**Comment by stuartmorgan** [comment]
> Maybe if there was a way to refer to the app's '/Contents/Resources/' directory

(I've filed #61962 for this piece.)

**Comment by ganeshrvel** [comment]
@stuartmorgan 

> If it's outside your bundle, then yes. If it's inside your bundle, I would expect it to work, and if it doesn't then it's important that we have that information. 

- The app is still under development and I didn't attempt to make a release build yet. So I wouldn't be know about the bundled path yet.
- The native binary resides inside the lib folder.
- The project path: /Users/username/my_app
- The binary paths that I attempted:
    - /Users/username/test_go_ffi/lib/common/binaries/libhello_ffi.dylib

The dart file:
```dart
import 'dart:ffi' as ffi;

typedef PrintHello_func = ffi.Void Function();
typedef PrintHello = void Function();

void main() {
  var path = '/Users/username/test_go_ffi/lib/common/binaries/libhello_ffi.dylib';

  final ffi.DynamicLibrary dylib = ffi.DynamicLibrary.open(path);

  final PrintHello hello = dylib
      .lookup<ffi.NativeFunction<PrintHello_func>>('PrintHello')
      .asFunction();

  hello();
}

```

Hope this helps

**Comment by stuartmorgan** [comment]
> I didn't attempt to make a release build yet. So I wouldn't be know about the bundled path yet.

This is unrelated to build mode. macOS applications are always bundles, whether debug or release.

> /Users/username/test_go_ffi/lib/common/binaries/libhello_ffi.dylib

This is not inside your application, so as noted above it is entirely expected that you would get a sandbox violation unless you've turned the sandbox off. Given that, closing, as this isn't a bug.

I've commented on your SO post with a high-level description of the right way to handle this.

**Comment by ganeshrvel** [comment]
@stuartmorgan 
Is there any write up on how to copy the native files into debug or release bundles? How do I develop an app if I can't run the native file? Is turning off the sandbox the right way to get this done during development?

**Comment by stuartmorgan** [comment]
> Is there any write up on how to copy the native files into debug or release bundles?

Flutter's instructions for this are at https://flutter.dev/docs/development/platform-integration/c-interop#ios-and-macos

If you want to do something different manually, I would imagine there are many tutorials on bundling resources with Xcode; there's nothing Flutter-specific about the process.

> How do I develop an app if I can't run the native file?

I don't understand the question. You develop the app by configuring it correctly such that it can run.

> Is turning off the sandbox the right way to get this done during development?

I don't know what you mean by "right". If your only goal is to make your app work when you build it locally, turning off the sandbox will accomplish your goal. On the other hand, if you intend to distribute your app, then loading a library from a hard-coded path on your machine won't work regardless of sandboxing and you'll need to bundle it, at which point the sandbox shouldn't be a problem in the first place.

**Comment by ganeshrvel** [comment]
Thanks! You were helpful. @stuartmorgan
