### ISSUE TITLE
Add "Dry run" support to Flutter's merge bot

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#61955]
Flutter’s merge bot (added in https://github.com/flutter/cocoon/pull/507) looks at PRs with the “waiting for tree to go green” label and lands them when all checks are green. It works great and the different rollers (skia->engine, engine->flutter, etc) rely on this functionality.

However, the rollers also have support for dry-runs. Since there is no corresponding “waiting for tree to go green” label for dry runs, the rollers have to do the checking for checks themselves. This is not ideal because the rollers run into issues with the Github API returning less than the number of checks in the beginning (things that the merge bot has figured out how to handle).

Could we create a new label that the merge bot checks for, does everything the same as “waiting for tree to go green” but does not submit at the end.
Another approach is if there is a label “dry run” in addition to “waiting for tree to go green” then the merge bot does not submit at the end but instead just removes the “waiting for tree to go green” label.

WDYT?

**Comment by rmistry** [comment]
FYI: @godofredoc 
(I'm not sure who owns the merge bot right now)

**Comment by godofredoc** [comment]
\cc @dnfield @christopherfujino @pcsosinski

**Comment by dnfield** [comment]
Is the idea that the roller on a dry run needs to know when it should eventually close the PR?

I'm a little curious about what would happen if the roller opened the PR as a draft in that state.

**Comment by rmistry** [comment]
When a roller is in dry run mode it needs to know when all checks are green or if there is a failure. i.e. it needs to know when a roll is "good" without actually landing it. Eg: Skia likes to put rollers in dry run mode when it's waiting for a branch. Dart->Engine recently used the dry run feature as well.

Right now the roller tries to look at the checks, but does not do it as well as the merge bot and that occasionally results in false positives and false negatives. Since the merge bot is Flutter's "commit queue" equivalent of Chromium, I figure it would make sense for it to support "dry runs" just like Chromium's CQ does. Our Chromium rollers directly use their commit queue for both normal runs and dry runs.

**Comment by pcsosinski** [comment]
may be slightly off topic, but when I put the Dart->Engine into dry run mode it gave us infra problems by trying dry runs with every Dart revision (/cc @godofredoc)

**Comment by rmistry** [comment]
> may be slightly off topic, but when I put the Dart->Engine into dry run mode it gave us infra problems by trying dry runs with every Dart revision (/cc @godofredoc)

That is on topic. Those are the kind of problems that happen when the roller tries to look at checks.
In that case there was a bug where right after upload the roller asked Github how many checks exist and it said 0 so the roller thought great everything is green and immediately marked it as successful. This was fixed by making the roller expect > 0 checks. But it's still not a perfect solution.

**Comment by dnfield** [comment]
I think we'd want to know what the mechanism would be to notify the roller that checks were successful. A comment?

**Comment by rmistry** [comment]
Comments are not great because we have to rely on the exact text matching. Android Gerrit instance likes to communicate with a "Verified" label.
If we trigger the dry run with a label like “dry run - start”, then the merge bot could at the end remove that label and add a new one called "dry run - successful" or "dry run - failed"
(these names were completely arbitrary, I'm sure you could come up with much better names)
That's one idea, there might be other better ones.

Another thought is that for a dry run we don't really care if the tree is open or closed, so it could bypass the tree check completely (that's what the Chromium CQ's dry run does).

**Comment by dnfield** [comment]
Could you elaborate on what bypassing the check means?

**Comment by dnfield** [comment]
Ahh ok, sure. So basically we want to teach it to label a PR once all checks have passed?

**Comment by rmistry** [comment]
Yes, exactly. And to make it ignore the tree-check and then not merge the PR if it is in dry-run mode.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
