### ISSUE TITLE
Garbled characters in comment cause "error • Target of URI doesn't exist:" when run "flutter analyze".

### ISSUE THREAD

**Issue by zhengger** [flutter/flutter#61951]
## Steps to Reproduce

1. If there is garbled characters in the comment line which is at the line 8 in the picture below. There will be **error • Target of URI doesn't exist:** occurs when run "flutter analyze"command .

![image](https://user-images.githubusercontent.com/2143234/88052202-79f23d80-cb8c-11ea-814a-b26ec04176b8.png)

2. If the line 8 with garbled characters is deleted, everything is ok when run "flutter analyze":
![image](https://user-images.githubusercontent.com/2143234/88052606-10befa00-cb8d-11ea-82cc-752a9390a872.png)

3. In either situation, the whole project can be compiled successfully despite the error notification.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @zhengger 
I cannot see that `Target of URI doesn't exist` error is about 8 line with garbled characters.
`flutter analyze` doesn't consider them in comment as error, closing. If you disagree please provide your `flutter doctor -v` and a minimal complete reproducible code sample
