### ISSUE TITLE
LazyBlock not scrolling

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#6196]
Hello,

I am using a LazyBlock to display list of items with differents sizes. In the children declaratio, I add in this order: one container, a List of item (using map and addAll) and to finish another container.

At startup, I intialize the List of item using a HttpRequest call. This call is triggered in the initState method of my component. The LazyBlock is correctly drawn but I can't scroll. 

I have put traces in the Scrollable class to check if one or more conditions were not verified but even the touchdown event is not triggered.

If I navigate in my application with a push and come back with a pop, the scroll begins to work.

I have tried to add data to my List using an action, if I do it, the scroll begin to work but if I clear the List before adding data, it doesn't.

Can you help me?

Thanks,

Vincent

**Comment by eseidelGoogle** [comment]
@Hixie or @HansMuller are your best bet.

**Comment by HansMuller** [comment]
It's a little hard to tell what you're up to here, a bit of the code would help.

How are you defining the LazyBlock's delegate? Are you using The LazyBlockChildren class?

When the HttpRequest's future resolves do you rebuild the lazy block with setState()?

**Comment by lequem** [comment]
Here some piece of code: the LazyBlock Code:

`
Widget body = new RefreshIndicatorPadding(
      padding: padding,
      child : new ScrollConfiguration(
        child : new LazyBlock(
          padding: padding,
          onScrollEnd: _scrollListener,
          delegate: new LazyBlockChildren(
            children: <Widget>[
              new Container(
                padding: const EdgeInsets.only(left: 3.0, right: 3.0, bottom: 8.0),
                child: new Container(

                  child: new RaisedButton(
                    child: new Row(
                      children: [
                        new Icon(Icons.location_on),
                        new Text(_currentPlace.toString(), style: textStyle(16.0, FontWeight.normal))
                      ],
                    ),
                    onPressed: _changeLocationShowDialog
                  )
                )
              )
            ]..addAll(kevents.map(
                (PlayEvent event) => new PlayCard(
                  playEvent: event,
                  onTap: () { _showPlayEvent(context, event); }
                )
              )
            )..add(_reloadingData ?
              new Container(child: new Center( child: new CircularProgressIndicator(value: null)), padding: const EdgeInsets.all(5.0)):
              new SizedBox(height: 0.0)
            )..add(new SizedBox(
              height: 16.0 + _kAppBarHeight + statusBarHeight
            ))
          ),
          scrollableKey: _scrollableKey,
        )
      ),
      displacement: 100.0,
      scrollableKey: _scrollableKey,
      key: _refreshIndicatorKey,
      refresh: _refresh,
      location: RefreshIndicatorLocationPadding.top
    );
`
RefreshIndicatorPadding extends RefreshIndicator and add a padding property

And the code to load data:

`void _updatePlayEventList() {
    setState((){
      kevents.clear();
    });
    PlayAPI.getEvents(val).then((http.Response resp) {
      List<PlayEvent> tmpevs = new List<PlayEvent>();
      [...] fill the tmpevs list with parsed data
      setState((){
        kevents.addAll(tmpevs);
     });
   });

`

I hope the code will help you. Do not hesitate if you have any question

**Comment by HansMuller** [comment]
Thanks for providing the code, that helps.

About two weeks ago I fixed a bug like this, https://github.com/flutter/flutter/pull/5934. I assume that you have an up to date copy of Flutter?

If you're up to date then please verify that `_updatePlayEventList()` actually causes the entire app to be rebuilt, i.e. it causes the lazy block to be rebuilt. Just to check:

If you wrap the LazyBlock in a Builder that prints a message, 
```
  new Builder(builder: (BuildContext context) {
    print("Building  kevents ${tmpevs.length}");
    return new LazyBlock(...);
  }
```
and also print one here:
```
      setState((){
        print("Updating kevents ${tmpevs.length}");
        kevents.addAll(tmpevs);
     });
```
Is the LazyBlock actually being rebuilt after the HTTP request resolves?

**Comment by lequem** [comment]
Ahhh sorry, my install was not up to date, I didn't pay attention that some traces I added in sources were blocking the git pull.
Now it works perfectly.
Sorry to have made your time lost and thank you again for your help.
Vincent
