### ISSUE TITLE
Function `await picker.getImage(...)` from `image_picker` shows no dialog to select an image and never returns

### ISSUE THREAD

**Issue by mzimbres** [flutter/flutter#61965]
Hi, I am trying to use the `image_picker` plugin in flutter web and have the following problem. When the user clicks a button to load an image I call the function

```dart
Future<void> foo() async
{
   PickedFile img = await picker.getImage(source: ImageSource.gallery);
   ...
}
```

The call to `getImage` however shows no dialog to select an image and never returns. If I call it again (by clicking the button in the UI) I get the error

```text
Overflow on channel: plugins.flutter.io/image_picker.  Messages on this channel are being discarded in FIFO
fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
```

What could be a cause of this problem? I am running the web version with `flutter run web`.

**Comment by Abhishek01039** [comment]
you can try https://pub.dev/packages/image_picker_web plugin for web version

**Comment by iapicca** [comment]
Hi @mzimbres 
[image_picker](https://pub.dev/packages/image_picker) doesn't support web,
but there's a first party web implementation [image_picker_for_web](https://pub.dev/packages/image_picker_for_web)

If the issue persists, 
please provide your `flutter doctor -v`, 
your `flutter run -d chrome --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by mzimbres** [comment]
@iapicca image_picker_for_web works like a charm, thanks for suggesting it, I did not know it existed.

**Comment by cedvdb** [comment]
@iapicca THE DOOC OF IMAGE-picker_for_web says to just add it to the dependencies and that it should work after. Is there anything else that has to be done ? Like importing said package somewhere ? It still hits me with the MissingPluginException
