### ISSUE TITLE
[linux] Font is escaping it's bounds and text is rendering invisible margin  with powerline glyphs

### ISSUE THREAD

**Issue by andrzejressel** [flutter/flutter#61989]
## Steps to Reproduce

1. Clone https://github.com/jereksel/flutter_powerline
2. Run application using `flutter run`

## Description:

When using Powerline glyphs from Nerd Fonts there seems to be strange bugs:

1. Font seems to be escaping it's bounds
![image](https://user-images.githubusercontent.com/1307829/88114197-9eaddb80-cbb3-11ea-937b-ee7c188f7cac.png)

Except when widget is scaled down - then is seems to be fine:
![image](https://user-images.githubusercontent.com/1307829/88114249-bdac6d80-cbb3-11ea-8c52-1c12f0063d68.png)

2. Text widget seems to be having invisible margin on the right:
![image](https://user-images.githubusercontent.com/1307829/88114309-e2084a00-cbb3-11ea-9763-c8b893af8b40.png)

Between powerline arrow and `123` there is white space and I think it shouldn't be there.

<details>
  <summary>Logs</summary>

```

```

```
Analyzing powerline_font...                                     
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale pl_PL.UTF-8)
    • Flutter version 1.21.0-1.0.pre at /home/andrzej/fvm/versions/dev
    • Framework revision f25bd9c55c (7 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/andrzej/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/andrzej/Android/Sdk
    • Java binary at: /home/andrzej/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/andrzej/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
i can reproduce the issues using your repository 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.94, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.94 at /home/taha/Code/flutter
    • Framework revision adc9dde3ba (12 hours ago), 2020-07-21 16:17:23 -0700
    • Engine revision 5a73d4dc25
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.

```

</details>

**Comment by jereksel** [comment]
Hi, I've decided to check this bug on other platforms:
1. Web (on Windows)
Is not present
![image](https://user-images.githubusercontent.com/1307829/88432032-c0010880-cdfb-11ea-9d34-f71c7b4061b7.png)
![image](https://user-images.githubusercontent.com/1307829/88432044-c68f8000-cdfb-11ea-90fc-5f3e11a4f574.png)

2. Android
Is present
![image](https://user-images.githubusercontent.com/1307829/88432557-b7f59880-cdfc-11ea-95b2-74bf80e9bc41.png)
![image](https://user-images.githubusercontent.com/1307829/88432515-a14f4180-cdfc-11ea-9409-aa29a95670ba.png)

3. Windows
Is present
![image](https://user-images.githubusercontent.com/1307829/88435827-57b62500-ce03-11ea-810a-ebbb1e56ce13.png)
![image](https://user-images.githubusercontent.com/1307829/88435848-60a6f680-ce03-11ea-94ed-881f3867af1d.png)
![image](https://user-images.githubusercontent.com/1307829/88435866-68669b00-ce03-11ea-9dae-196b77c66389.png)


Unfortunatelly I don't own neither iOS nor MacOS device, so I can't check it there

**Comment by jereksel** [comment]
So I've checked this glyph in fontforge and indeed it's escaping bounds (it start before `0`):

<section>

![image](https://user-images.githubusercontent.com/1307829/88465473-8d224780-cec3-11ea-942a-cc6c93cb2385.png)

</section>

**Comment by jereksel** [comment]
I'm sorry, I was wrong about web. The bug is reversed. It breaks when text is bounded:

![image](https://user-images.githubusercontent.com/1307829/88466856-f066a680-ced0-11ea-8d66-fb00c335b929.png)
![image](https://user-images.githubusercontent.com/1307829/88466859-f65c8780-ced0-11ea-8ccd-c85bb6b299ad.png)
