### ISSUE TITLE
flutter run --watch

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#6199]
`flutter listen` is [being removed](https://github.com/flutter/flutter/pull/6198). Should we implement `flutter run --watch` that automatically reloads the application if any file in the application changes?

**Comment by sethladd** [comment]
I don't think we need it at this time.

**Comment by Hixie** [comment]
I think it'd be a fine feature, but is not a high priority. We have bugs to deal with before we add features.

**Comment by mit-mit** [comment]
Closing.

**Comment by bugeats** [comment]
Some of us newcomers to Flutter out here are not using VSCode and IDEs. A `flutter run --watch` would be very useful.

**Comment by bramus** [comment]
Coming over from React Native and the likes I today installed Flutter for doing my first experiments with it and truth be told this was the first thing I was looking for …

As I'm unfamiliar with Flutter at this time, is there any technical reason to not include this low-effort huge-impact #DX improvement?
