### ISSUE TITLE
Material gallery crashes when you press the drop-down button

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#620]

**Comment by Hixie** [comment]
(A red screen of death crash, not an engine crash.)

**Comment by abarth** [comment]
Yeah, I broke this with RepaintBoundary.  The problem is that dropdown list uses `Positioned` to position itself instead of using the OverlayPosition.

**Comment by HansMuller** [comment]
Do you mean that _DropDownRoute<T> should provide an override of:
```
  ModalPosition get position => null; // from ModalRoute<T>
```

**Comment by abarth** [comment]
Yes, exactly.

**Comment by abarth** [comment]
Closing as duplicate of #630
