### ISSUE TITLE
unable to sign in through Google Sign In , for Flutter web app

### ISSUE THREAD

**Issue by vivek-chiluveru** [flutter/flutter#62009]
The following is the message I get when I enter my email Id for Google sign in, for the Flutter Web app-"This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."
(Google Sign in works fine for android app.)

**Comment by Abhishek01039** [comment]
have a look into it https://support.google.com/accounts/thread/22873505?hl=en @vivek-chiluveru

**Comment by vivek-chiluveru** [comment]
> have a look into it https://support.google.com/accounts/thread/22873505?hl=en @vivek-chiluveru

Thank you @Abhishek01039

**Comment by darshankawar** [comment]
Hi @vivek-chiluveru,
Does the link provided above solve your issue ?

**Comment by vivek-chiluveru** [comment]
No, the issue isn't  solved.

**Comment by darshankawar** [comment]
Hi @vivek-chiluveru,
Can you try [this](https://github.com/flutter/flutter/issues/60259#issuecomment-649540654) solution and see if it works for you ?
If problem persists, there's a similar open issue describing your case, [61155](https://github.com/flutter/flutter/issues/61155).
I'd suggest to follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
