### ISSUE TITLE
android tv remote back key stopped functioning on master channel

### ISSUE THREAD

**Issue by andraskende** [flutter/flutter#62010]
Hello,

I just noticed that on master branch the android tv remote back key stopped functioning today after a flutter upgrade.
I think this flutter change to master was recent, on dev & beta channels same flutter app works fine.

here is my app:
    https://github.com/andraskende/apptv1/

simple app - works on dev, can't exit the program with remote back button on android tv (nvidia shield tv)

    import 'package:flutter/material.dart';
    import 'package:flutter/services.dart';

    void main() {
      runApp(MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return Shortcuts(
          shortcuts: {
            // MASTER BRANCH
            LogicalKeySet(LogicalKeyboardKey.select): const ActivateIntent(),
            // STABLE BRANCH
            // LogicalKeySet(LogicalKeyboardKey.select):
            //     const Intent(ActivateAction.key),
          },
          child: MaterialApp(
            title: 'Flutter Demo',
            theme: ThemeData(
              primarySwatch: Colors.blue,
              visualDensity: VisualDensity.adaptivePlatformDensity,
            ),
            home: MyHomePage(title: 'Flutter Demo Home Page'),
          ),
        );
      }
    }

    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);

      final String title;

      @override
      _MyHomePageState createState() => _MyHomePageState();
    }

    class _MyHomePageState extends State<MyHomePage> {
      int _counter = 0;

      void _incrementCounter() {
        setState(() {
          _counter++;
        });
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: _incrementCounter,
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        );
      }
    }

**Comment by TahaTesser** [comment]
Hi @andraskende 
Can you please provide your `flutter doctor -v` on `master` which reproduces the issue ? Also please provide details about which nvidia shield tv it is and Android version 
Thank you

**Comment by andraskende** [comment]
andras@andras ~ % 
andras@andras ~ % flutter channel master         
Switching to flutter channel 'master'...
git: Already on 'master'
git: Your branch is up to date with 'origin/master'.
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
andras@andras ~ % 
andras@andras ~ % flutter upgrade                
Flutter is already up to date on channel master
Flutter 1.21.0-2.0.pre.94 • channel master • https://github.com/flutter/flutter.git
Framework • revision adc9dde3ba (11 hours ago) • 2020-07-21 16:17:23 -0700
Engine • revision 5a73d4dc25
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)
andras@andras ~ % 
andras@andras ~ % flutter create apptv3          
Creating project apptv3...
  apptv3/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  apptv3/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  apptv3/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  apptv3/ios/Runner/Info.plist (created)
  apptv3/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  apptv3/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  apptv3/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  apptv3/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  apptv3/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  apptv3/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  apptv3/ios/Runner/Base.lproj/Main.storyboard (created)
  apptv3/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  apptv3/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  apptv3/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  apptv3/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  apptv3/ios/Flutter/Debug.xcconfig (created)
  apptv3/ios/Flutter/Release.xcconfig (created)
  apptv3/ios/Flutter/AppFrameworkInfo.plist (created)
  apptv3/ios/.gitignore (created)
  apptv3/test/widget_test.dart (created)
  apptv3/apptv3.iml (created)
  apptv3/.gitignore (created)
  apptv3/.metadata (created)
  apptv3/android/app/src/profile/AndroidManifest.xml (created)
  apptv3/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  apptv3/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  apptv3/android/app/src/main/res/drawable/launch_background.xml (created)
  apptv3/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  apptv3/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  apptv3/android/app/src/main/res/values/styles.xml (created)
  apptv3/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  apptv3/android/app/src/main/AndroidManifest.xml (created)
  apptv3/android/app/src/debug/AndroidManifest.xml (created)
  apptv3/android/gradle/wrapper/gradle-wrapper.properties (created)
  apptv3/android/gradle.properties (created)
  apptv3/android/.gitignore (created)
  apptv3/android/settings.gradle (created)
  apptv3/android/app/build.gradle (created)
  apptv3/android/app/src/main/kotlin/com/example/apptv3/MainActivity.kt (created)
  apptv3/android/build.gradle (created)
  apptv3/android/apptv3_android.iml (created)
  apptv3/pubspec.yaml (created)
  apptv3/README.md (created)
  apptv3/ios/Runner/Runner-Bridging-Header.h (created)
  apptv3/ios/Runner/AppDelegate.swift (created)
  apptv3/ios/Runner.xcodeproj/project.pbxproj (created)
  apptv3/lib/main.dart (created)
  apptv3/.idea/runConfigurations/main_dart.xml (created)
  apptv3/.idea/libraries/Dart_SDK.xml (created)
  apptv3/.idea/libraries/KotlinJavaRuntime.xml (created)
  apptv3/.idea/modules.xml (created)
  apptv3/.idea/workspace.xml (created)
Running "flutter pub get" in apptv3...                              1.1s
Wrote 71 files.

All done!
[✓] Flutter: is fully installed. (Channel master, 1.21.0-2.0.pre.94, on Mac OS X 10.15.6 19G73, locale en-US)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.6)
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.47.2)
[✓] Connected device: is fully installed. (1 available)

In order to run your application, type:

  $ cd apptv3
  $ flutter run

Your application code is in apptv3/lib/main.dart.

andras@andras apptv3 % 
andras@andras ~ % cd apptv3
andras@andras apptv3 % 
andras@andras apptv3 % flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-2.0.pre.94, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.21.0-2.0.pre.94 at /Users/andras/development/flutter
    • Framework revision adc9dde3ba (12 hours ago), 2020-07-21 16:17:23 -0700
    • Engine revision 5a73d4dc25
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andras/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/andras/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SHIELD Android TV (mobile) • 192.168.50.187:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
andras@andras apptv3 % 
andras@andras apptv3 % code .
andras@andras apptv3 % 
andras@andras apptv3 % flutter run
Launching lib/main.dart on SHIELD Android TV in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        35.5s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 6.6s
Waiting for SHIELD Android TV to report its views...                 9ms
Syncing files to device SHIELD Android TV...                       273ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on SHIELD Android TV is available at: http://127.0.0.1:51154/QkkDGOojjuI=/
Lost connection to device.
andras@andras apptv3 %

**Comment by andraskende** [comment]
NVIDIA SHIELD Android TV Pro 2019 Android 9 (API 28) - Up to with latest updates...

Thanks !!

**Comment by jason-simmons** [comment]
The back button was affected by https://github.com/flutter/engine/pull/19024.

This has been reverted (https://github.com/flutter/engine/pull/19956)

**Comment by andraskende** [comment]
Just tested again with upgraded master, its working fine again.
Thank you !
