### ISSUE TITLE
[video_player] audio output from EarPiece not speaker

### ISSUE THREAD

**Issue by tonypottera24** [flutter/flutter#62015]
## Steps to Reproduce

flutter 1.17.5
video_player: ^0.10.11+2
Android 9
Samsung S8

1. Play a video file
```
final videoPlayerController = VideoPlayerController.file(await recording.videoFile);
videoPlayerController.addListener(_videoPlayerControllerListener);
await videoPlayerController.initialize();
await videoPlayerController.play();
```

**Expected results:** 
The voice came out from speaker
**Actual results:** 
The voice came out from earpiece

**Comment by TahaTesser** [comment]
Hi @tonypottera24 
Can you please provide your `flutter doctor -v` your `flutter run --verbose`  logs while playing video and a complete reproducible minimal code sample with local or network example 
Thank you

**Comment by tonypottera24** [comment]
This situation might be caused by flutter_sound 5.1.1
I start the video_player after `closeAudioSession()`.
After I changed to flutter_sound 4.0.6, this bug disappeared.
