### ISSUE TITLE
Unable to build plugin frameworks: ** BUILD FAILED **

### ISSUE THREAD

**Issue by LuckyRoc** [flutter/flutter#62013]
flutter build  ios-framework --cocoapods --output=pods -v

![image](https://user-images.githubusercontent.com/10631829/88146772-dc9c1580-cc2e-11ea-8334-503e526037ac.png)

**Comment by TahaTesser** [comment]
Hi @LuckyRoc 
Can you please provide your `flutter doctor -v` your complete `flutter build ios-framework --cocoapods --output=pods -v` and a complete reproducible minimal code sample from module and ios app, you can  add them in a zip and attachment in the comment
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
