### ISSUE TITLE
FutureBuilder: add a way to refresh it.

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#62019]
There's stated in the docs:

> The future must have been obtained earlier, e.g. during State.initState, State.didUpdateConfig, or State.didChangeDependencies. It must not be created during the State.build or StatelessWidget.build method call when constructing the FutureBuilder. If the future is created at the same time as the FutureBuilder, then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.

## The problem

You have a FutureBuilder.  You have a database or a remote server with some list of items.
In initState you retrieve this data with FutureBuilder and build a ListView.
Go to the other screen and add a new item. Pop to the previous screen.
**Result**: list is not rebuilt and the new item has not appeared.
It's because we make a future call once in initState and never re-fetch data anymore
We cannot use setState() to change this Future while being in the other screen.
FutureBuilder currently is a "one-off" solution which has no API to refresh.

See also these discussions:
https://stackoverflow.com/questions/62539885/flutter-provider-what-is-the-best-way-to-dispatch-the-action-properly?noredirect=1#comment111407495_62539885
https://stackoverflow.com/questions/60143638/flutter-prevent-futurebuilder-always-refresh-every-change-screen
https://www.youtube.com/watch?v=_60WdOoezmc (he uses an ugly workaround with static browse() method and setState)
People encounter the same problems.

## Proposal

You probably need to add a refreshOnNotify parameter (to work with ChangeNotifier and react to notifyListeners()).
Also add a forceRefresh() method to access this FutureBuilder from GlobalKey or from context, to update it manually.

**Comment by fiorcode** [comment]
any solution for this situation?

**Comment by subzero911** [comment]
> any solution for this situation?

I started using MobX, it has ObserverableFuture which holds a future state. This package https://pub.dev/packages/mobx_widget contains ObserverFuture which is a FutureBuilder analogue, working with an ObservableFuture type. I await the future in a Store and watch its state on UI side.

**Comment by AnyKay00** [comment]
Any Solutions to this problem? Having the same problem, even updating the page with setState is not working for me.

**Comment by fiorcode** [comment]
Like @subzero911 you can use [https://pub.dev/packages/mobx_widget](url).
In my case i solved it by using the .then function of Navigator.

`Future _getThings;

Future _getThings() async =>
      Provider.of<ItemProvider>(context, listen: false).fetchThings();

Future onReturn() async => setState(() => _getThings = _getThings());

  @override
  void initState() {
    _getThings= _getThings();
    super.initState();
  }

Navigator.of(context).pushNamed(DashboardScreen.routeName).then((_) => onReturn())
`

Navigator sets the function onReturn to be executed when the user cames back to the page, but i assume that this only works if the page is not replaced.

Just in case this is a video that helped me to understand FutureBuilder [https://www.youtube.com/watch?v=LYN46233cws](url)

**Comment by TornaxO7** [comment]
Shouldn't this issue still be opened? Because `mobx_widget` is just a workaround, right?

**Comment by TornaxO7** [comment]
@subzero911 if you added a thumb up to my message, than could you please reopen your issue again?

**Comment by TornaxO7** [comment]
Thank you! :)

**Comment by subzero911** [comment]
You can also check out https://pub.dev/packages/get, I requested something like ObservableFuture and they added StateMixin recently, so Controller now can have a state (Empty/Error/Loading/Success) which you can read in widgets.
I can agree, FutureBuilder out of the box is worthless.

**Comment by TornaxO7** [comment]
Ok so in my case I found this package: https://pub.dev/packages/async_builder
It's almost doing the same as `FutureBuilder` but there's one problem: Everytime if I call `setState(() {})` the widget is gonna be completely rebuild which creates a flicker - "effect" which you might try to avoid..... So I'm trying to find a solution.

**Comment by lutang123** [comment]
I have the same issue with FutureBuilder, then I used a lots of setState with some variables to help handle different state, it's kind of working, and below is simplified code. I don't think this is the best way, is there a better way except using some of the package as mentioned above? any opinions are appreciated

`//inside stateful State class:

_hasError = false;
_isLoading = false;

String _myText = '';

Future<void> _getMyText() async {

      setState(() {
        _isLoading = true;
        });
      
      try {
        myText = await myFutureFunction();
        
        setState(() {
        _isLoading = false;
        });
        
      } catch (e) {
      
        setState(() {
        _isLoading = false;
        _hasError = true;
        });
      }

}

  @override
  void initState() {
    super.initState();
    _myText = _getMyText(); //this is a future to fetch data from API
  }
  
  //then inside build method:
  
  _isLoading 
  ? LoadingWidget() 
  : (!_hasError
     ? Text(_myText) //here is the data we want to display.
     : Text('error here');
     
  // and if you have any button to navigate to another page and want refresh when back, do this:
  
  onTap: () => Navigator.of(context).pushNamed(OtherScreen)
                .then((_) async {
              await _getMyText();
            });
  
  `
  
  That's the basic logic, I know it's not good to use too much setState, but I don't know a better way yet.

**Comment by asm495** [comment]
I tried many different techniques and I couldn't find a way to refresh the FutureBuilder. Instead what I did was when I wanted to refresh the page was to call popAndPushNamed.

https://api.flutter.dev/flutter/widgets/Navigator/popAndPushNamed.html

This popped back to the previous screen but then pushed straight back to the screen that was currently viewed. This caused the FutureBuilder to rebuild and display correctly. I appreciate it may not help everyone but for me it was a very quick and easy solution.

**Comment by Amr1440** [comment]
Same problem here Im using Futurebuilder and can't change UI using setState !

**Comment by subzero911** [comment]
I must admit FutureBuilder is still quite useful in some cases for late state variables initializing.
Say, you have some `late UserProfile _userProfile`, and you want to show its data on page loaded.
You start loading it from db or network in postFrameCallback.
Before null-safety, _userProfile was null until it's not fully loaded, and you could check if it's null and show the spinner.
But now, it can't have null value, and you will get `LateInitializationError` for first several frames.
To solve it I wrapped _userProfile into future `late Future<UserProfile> _userProfile`, call `fetchProfile()` (not awaiting it!) and use FutureBuilder to watch its state and show spinner until it's fully loaded and show snapshot.data afterwards.

**Comment by cbreezier** [comment]
The solution here is to use a `StreamBuilder` instead of a `FutureBuilder`. This solves the "rerun" problem and the "flickering" problem, as well as being more semantically correct.

Instead of switching out the future that the `FutureBuilder` depends on (which is kind of like ripping the carpet out from under someone's feet and replacing it with a new one - not very pleasant), use a `StreamBuilder` and simply emit new data into your stream.

Here's a simple, non-compiling example for demonstration purposes:

Before:
```
Future<String> future;

Widget build(BuildContext context) {
    return Column(
        children: [
            TextButton(
                child: Text('Refresh'),
                onPressed: () {
                    setState(() {
                        this.future = Future.delayed(Duration(seconds: 5), () => 'Result');
                    });
                },
            ),
            FutureBuilder(
                future: future,
                builder: ...
           ),
       ],
    );
}
```

After:
```
StreamController<String> streamController;

Widget build(BuildContext context) {
    return Column(
        children: [
            TextButton(
                child: Text('Refresh'),
                onPressed: () async {
                    this.streamController.add(await Future.delayed(Duration(seconds: 5), () => 'Result'));
                },
            ),
            StreamBuilder(
                stream: streamController.stream,
                builder: ...
           ),
       ],
    );
}
```

Apologies for syntax errors - I wrote that up without reference.

This does mean you need a StatefulWidget. Don't forget to dispose of your `streamController`!

**Comment by Chetan-Goyal** [comment]
To overcome such type of problem, I will separate FutureBuilder from my build method and save the data returned by future builder in a separate object (or state). I will have to write some boiler plate code to manage the state but It will help me to refresh data whenever I need by calling that Future. 
This approach will also avoid the "flicker" effect since old data will be displayed until new data is being loaded. 

Having refresh option in FutureBuilder would be a better approach than using these workarounds.

**Comment by aalindsingh** [comment]
Hello,
I faced this issue too. 
The problem I faced was that the AutoComplete widget that I was using for input on a screen wasn't showing the refreshed data for suggestions even after putting the code in a separate util file and using setState or StreamBuilder.
I think our approach of trying to refresh the screen and expecting the widget to show the updated data is wrong. What I did was that I had a separate service for the API call and I passed it as a reference to the future attribute of the FutureBuilder.
Then every time the user selected another button on top (campaign type in my case); all I did was call the API service again and the widget reloads showing the updated data.
I hope it helps, worked for me :)

--Below is a rough code for the implementation that I have written--

-service.dart
-----------------
Future<Model> getData(BuildContext context) async {
final response = http.get('url');

if(response.statusCode == 200)
  return Data.fromJson(jsonDecode(response.body));
}  
 
-screen.dart
------------------

IconButton(
onPressed: () {
  getData(context);
  setState(() {});
 },
icon: Icon(), 
),

FutureBuilder(
future: getData(context),
body: _body(),
);

**Comment by adi-16-7** [comment]
> Hello, I faced this issue too. The problem I faced was that the AutoComplete widget that I was using for input on a screen wasn't showing the refreshed data for suggestions even after putting the code in a separate util file and using setState or StreamBuilder. I think our approach of trying to refresh the screen and expecting the widget to show the updated data is wrong. What I did was that I had a separate service for the API call and I passed it as a reference to the future attribute of the FutureBuilder. Then every time the user selected another button on top (campaign type in my case); all I did was call the API service again and the widget reloads showing the updated data. I hope it helps, worked for me :)
> 
> --Below is a rough code for the implementation that I have written--
> 
> ## -service.dart
> Future getData(BuildContext context) async { final response = http.get('url');
> 
> if(response.statusCode == 200) return Data.fromJson(jsonDecode(response.body)); }
> 
> ## -screen.dart
> IconButton( onPressed: () { getData(context); setState(() {}); }, icon: Icon(), ),
> 
> FutureBuilder( future: getData(context), body: _body(), );

Hey @aalindsingh thanks for the solution, it worked perfectly fine for me in my use case too!!

**Comment by mk48** [comment]
👀

**Comment by subzero911** [comment]
I didn't understand this widget right.
It doesn't refresh anything. It just watches the existing `Future` object (but you still have to manually rebuild the widget somehow).

You can use `ChangeNotifierProvider` to refresh `FutureBuilder`.

- Expose a future in a controller.
- Watch this future in the FutureBuilder.

In `fetch()` method:
- assign your network request to this future.
- call notifyListeners() to show a loader.
- `await` the future
- call notifyListeners() again to show the result.

I hope this will help.

**Comment by subzero911** [comment]
This behavior still seems incorrect 🤔
FutureBuilder is expected to handle its `snapshot.connectionState` automatically and show loading / error / data.
But it doesn't until I rebuild it with setState / notifyListeners / in some other way.

**Comment by subzero911** [comment]
Minimal reproducible sample:

<summary></summary>
<details>

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Provider(
      create: (context) => Controller(),
      builder: (context, child) => MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: const MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final ctrl = context.watch<Controller>();

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FutureBuilder(
              future: ctrl.futureData,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.none) {
                  return Container();
                }
                if (snapshot.connectionState == ConnectionState.done) {
                  if (snapshot.hasError) {
                    return const Text('Error');
                  }
                  return Text(snapshot.data!.body);
                } else {
                  return const Center(
                    child: CircularProgressIndicator(),
                  );
                }
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: ctrl.download,
        tooltip: 'Download',
        child: const Icon(Icons.download),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class Controller {
  Future<Response>? futureData;

  Future<void> download() async {
    futureData = get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1'));
    await futureData;
  }
}

```
</details>

**Expected behaviour:**
FutureBuilder automatically changes its state accordingly to future's ConnectionState.

**Actual behaviour:**
Nothing happens until I rebuild it manually with `notifyListeners()`
```dart
Future<void> download() async {
    futureData = get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1'));
    notifyListeners();
    await futureData;
    notifyListeners();
  }
```
