### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by vansul** [flutter/flutter#62017]
## Steps to Reproduce

When I run `flutter doctor -v` I get an error saying that I have Android license status unknown.

I found solution on internet to resolve the issue by running the command `flutter doctor --android-licenses` but then I got error `Android sdkmanager tool not found`. Then I got solution on internet which is to go to android studio and install Android SDK Command-line Tools. And then again when ran the command `flutter doctor --android-licenses` I got the same error, I figured out that Android SDK Command-line Tools are installed in `<SDK PATH>\cmdline-tools\latest\bin\` instead of `<SDK PATH>\tools\bin\` which is required by flutter. So, copied and pasted it there but it doesn't work, instead I got the sdkmanager usage manual.

## Logs

Output of `flutter doctor -v`

```
C:\Users\Vaibhav>flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale en-IN)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Vaibhav\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.47.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment]
Hi @vansul,
I see a similar [issue](https://github.com/flutter/flutter/issues/51670) that describes your case which has several solutions that you can try.
Can you try [this](https://github.com/flutter/flutter/issues/51670#issuecomment-592943797) solution from it and see if it works for you ?

**Comment by vansul** [comment]
Thanks, it worked successfully.
