### ISSUE TITLE
ClipRRect: The argument type 'BorderRadiusDirectional' can't be assigned to the parameter type 'BorderRadius'. 

### ISSUE THREAD

**Issue by kightsonsanom** [flutter/flutter#62011]
ClipRRect `borderRadius` parameter does not allow BorderRadiusDirectional object to be passed.

**Comment by darshankawar** [comment]
Hi @kightsonsanom,
Yes currently it doesn't seem to support `BorderRadiusDirectional`, unlike other widgets such as `Card` or `Container` using their `shape` property.
So what is your question here ? Are you looking / proposing to have this feature for `ClipRRect` ?

**Comment by kightsonsanom** [comment]
Hello @darshankawar, thank you for your quick response. Yes, I am proposing to include this feature for `ClipRRect`, currently, when we want to include an image at the start of an eg list item with rounded corners we have to explicitly provide circular corners depending on the direction of the text.

Example:

![image](https://user-images.githubusercontent.com/24854180/88278986-994fae80-cce3-11ea-9131-dec79cc75dda.png)

**Comment by mohamadtn888** [comment]
On the `BorderRadiusDirectional` use `reslove()` method to be converted to a `BorderRadius` object.

**Comment by gnprice** [comment]
It looks like this was fixed in #101200, after being duplicated as #91997.
