### ISSUE TITLE
Flutter for windows cannot open when copy release folder to another path

### ISSUE THREAD

**Issue by amasahara** [flutter/flutter#62020]
I try make todo app on windows, after i release success i run on E:\Flutter\flutter_app_todo\build\windows\x64\Release\Runner everything woking well but when i copy to anthor path example D:\todo my app cannot run, it just blank application
![Untitled](https://user-images.githubusercontent.com/5392719/88157868-8088bf80-cc35-11ea-9e2e-bcf53e2b0838.png)

**Comment by TahaTesser** [comment]
Hi @amasahara 
Did you execute `fluter build windows` to generate this build?
Can you please provide your `flutter doctor -v`, your `flutter build windows` and a complete reproducible minimal code sample
Thank you

**Comment by amasahara** [comment]
Hi @TahaTesser, thanks for your care.
Here is my Flutter doc tor

> PS E:\Flutter\flutter_app_todo> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel master, 1.20.0-1.0.pre, on Microsoft Windows [Version 6.1.7601], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
> [!] Android Studio (version 3.3)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] VS Code (version 1.47.2)
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.

and flutter build windows

> PS E:\Flutter\flutter_app_todo> flutter build windows
> Building Windows application...

it still create release folder at E:\Flutter\flutter_app_todo\build\windows\x64\Release\Runner and same error too. I not sure but seem it cannot create table of sqlite database when i copy it to another folder. Here is my database code

```
class TodoDatabase {
  static const DB_NAME = 'todo.db';
  static const DB_VERSION = 1;
  static Database _database;

  static const initScripts = [TodoTable.CREATE_TABLE_QUERY];
  static const migrationScripts = [TodoTable.CREATE_TABLE_QUERY];

  TodoDatabase._privateConstructor();
  static final TodoDatabase instance = TodoDatabase._privateConstructor();

  Future<Database> get database async {
    if (_database == null) {
      _database = await init();
    }
    return _database;
  }

  Future<Database> init() async {
    if (Platform.isWindows) {
      //path to db file, at application folder
      final script = File(Platform.script.toFilePath());
      final file = File(p.join(script.parent.path, DB_NAME));
      if (!await file.exists()) {
        // create db file
        new File(file.path).create(recursive: true);
      }

      // Init ffi loader if needed.
      sqfliteFfiInit();
      var databaseFactory = databaseFactoryFfi;
      var db = await databaseFactory.openDatabase(file.path,
          options: OpenDatabaseOptions(version: DB_VERSION));

      await db.execute(TodoTable.CREATE_TABLE_QUERY);
      return db;
    } else {
      var databasesPath = await getDatabasesPath();
      String path = p.join(databasesPath, DB_NAME);
      var db = await openDatabase(path, onCreate: (db, version) {
        initScripts.forEach((script) async => await db.execute(script));
      }, onUpgrade: (db, oldVersion, newVersion) {
        migrationScripts.forEach((script) async => await db.execute(script));
      }, version: DB_VERSION);
      return db;
    }
  }
}
```

**Comment by TahaTesser** [comment]
cc: @stuartmorgan 

I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by amasahara** [comment]
did you need my full source code

**Comment by stuartmorgan** [comment]
The most likely reason for a white screen is an exception in your code. Please provide the output from running your binary in a console from the location where it's not working.

In general, moving the entire folder works, so this is specific to your application.

> //path to db file, at application folder

This is a very strange place to keep user data, FYI.

**Comment by amasahara** [comment]
that means where application start, it will check in same folder of location, if not database file, it will create new database file, maybe 2 image will make you understand this.
This image that when i copy release folder to another location it cannot create database file and application also cannot run too
![nôtk](https://user-images.githubusercontent.com/5392719/88243045-58db3b00-ccb9-11ea-86dc-614f6f1e5f7c.png)

But if i still run application on release folder where flutter build app, it will automatic create database and woking fine
![runok](https://user-images.githubusercontent.com/5392719/88243050-5b3d9500-ccb9-11ea-9cb8-5f358cf3d50b.png)

**Comment by stuartmorgan** [comment]
> that means where application start, it will check in same folder of location, if not database file, it will create new database file, maybe 2 image will make you understand this.

I didn't say I didn't understand it, I said it's strange to keep user data, like a database file, in the application directory. That's what document and/or application support directories are for. However, I don't think that's related to the issue.

Again:
> Please provide the output from running your binary in a console from the location where it's not working.

Screenshots of an empty window aren't console output. We need to know what is logged when it fails to run.

**Comment by stuartmorgan** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): join(null, "src", "windows", "sqlite3.dll"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1101:5)
#1      Context.join (package:path/src/context.dart:240:5)
#2      join (package:path/path.dart:262:13)
#3      windowsInit (package:sqflite_common_ffi/src/windows/setup.dart:12:24)
#4      sqfliteFfiInit (package:sqflite_common_ffi/src/sqflite_ffi_io.dart:19:5)
#5      TodoDatabase.init (package:flutter_app_todo/db/todo_database.dart:38:7)
<asynchronous suspension>
#6      main (package:flutter_app_todo/main.dart:9:31)
```

You'll need to file an issue against sqflite_common_ffi. From a cursory look at the code in this stack, it appears that windows/setup.dart is only designed to work when you `flutter run` from within your project. That's an issue with the package, not with Flutter.
