### ISSUE TITLE
[ Solved ] Running Gradle task 'assembleDebug'

### ISSUE THREAD

**Issue by xjy37** [flutter/flutter#62021]
# 解决以上问题

参考了几个方案没有解决后来看到一个方案很好，适合国内用(Ali Maven repository)

**At**: `{path/to/FlutterSDK}/packages/flutter_tools/gradle/flutter.gradle`**
### A:
To Modify:
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
         //修改这里
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
Modified:
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        //已修改
        google()
        jcenter()
        //maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
### B:
To Modify:
```
private static final String DEFAULT_MAVEN_HOST = "https://storage.googleapis.com/";
```
Modified:
```
//private static final String DEFAULT_MAVEN_HOST = "https://storage.googleapis.com/";
private static final String DEFAULT_MAVEN_HOST = "https://storage.flutter-io.cn/download.flutter.io";
```
---
**At**: `{path/to/project}/android/build/gradle`
> Modity Just like A

Then when running `flutter build apk`, you could see execute time reduced to about `52s` in Line `Running Gradle task 'assembleDebug'`, while no additional modifications `142s`.

**Comment by TahaTesser** [comment]
Hi @xjy37 
Thanks for this solution, this is specific to [Using Flutter in China](https://flutter.dev/community/china. 
You seem to be proposing mirror links  without third party

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
