### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by RaySummer** [flutter/flutter#62029]
Hey,The following error occurred in my code.

'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

I use the bottom sheet in scaffold in the project. In the bottom sheet, I use the row layout, and a textfield is nested inside. When I click textfield to get the focus, the keyboard pop-up will automatically disappear, and then there will be an exception

code:
  Scaffold(
          backgroundColor: Colors.white,
          appBar: AppBar(
            iconTheme: IconThemeData(
              color: Colors.black54,
            ),
            title: Text(
              '${widget.targetUser.name}',
              style: TextStyle(
                color: Colors.black54,
              ),
            ),
            backgroundColor: Colors.white,
            automaticallyImplyLeading: true,
            elevation: 0.5,
          ),
          body: Container(
            padding: EdgeInsets.only(bottom: 65),
            color: Colors.white,
            child: ListView(
              padding: EdgeInsets.all(0),
              physics: const AlwaysScrollableScrollPhysics(),
              reverse: true,
              controller: scrollController,
              children: <Widget>[
                StreamBuilder<ChatRecordResponseBody>(
                  stream: bloc.stream,
                  // initialData: null,
                  builder: (BuildContext context,
                      AsyncSnapshot<ChatRecordResponseBody> snapshot) {
                    if (snapshot.data == null) {
                      bloc.getHistoryChatList(user.uid, widget.targetUid);
                      return ProgressIndicatorFactory
                          .buildPaddedProgressIndicator();
                    }
                    if (snapshot.data.data.length <= 0) {
                      return Container();
                    }
                    if (snapshot.hasData) {
                      return Column(
                        children: snapshot.data.data.map((model) {
                          return _buildItem(model);
                        }).toList(),
                      );
                    } else if (snapshot.hasError) {
                      return Text('${snapshot.error}');
                    }
                  },
                ),
                StreamBuilder<bool>(
                  stream: bloc.bottomStream,
                  initialData: false,
                  builder:
                      (BuildContext context, AsyncSnapshot<bool> snapshot) {
                    return ScrolledToEndTips(
                      hasContent: snapshot.data,
                      scrollController: scrollController,
                    );
                  },
                ),
                StreamBuilder<bool>(
                  stream: bloc.loadingStream,
                  initialData: false,
                  builder:
                      (BuildContext context, AsyncSnapshot<bool> snapshot) {
                    return ScrolledToLoadingTips(
                      hasContent: snapshot.data,
                      scrollController: scrollController,
                    );
                  },
                ),
              ],
            ),
          ),
          bottomSheet: _buildBottomSheet(context),
        )

Widget _buildBottomSheet(BuildContext context) {
    return Container(
      height: 65,
      child: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            Divider(
              height: 0.1,
              color: Colors.black54,
            ),
            Container(
              padding: EdgeInsets.symmetric(vertical: 5, horizontal: 10),
              height: 60,
              width: MediaQuery.of(context).size.width,
              child: Row(
                children: <Widget>[
                  Container(
                    margin: EdgeInsets.symmetric(horizontal: 5),
                    padding: EdgeInsets.symmetric(horizontal: 5, vertical: 5),
                    child: Icon(
                      Feather.volume_2,
                      size: 22,
                      color: Colors.black54,
                    ),
                    decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(100),
                        border: Border.all(color: Colors.black54, width: 0.2)),
                  ),
                  Expanded(
                    child: GestureDetector(
                      child: Container(
                        padding:
                            EdgeInsets.symmetric(horizontal: 15, vertical: 5),
                        margin: EdgeInsets.only(right: 20),
                        height: 60,
                        child: TextField(
                          minLines: 1,
                          maxLines: 3,
                          focusNode: fn,
                          controller: commentController,
                          keyboardType: TextInputType.text,
                          decoration: InputDecoration(
                            border: InputBorder.none,
                            focusedBorder: InputBorder.none,
                          ),
                          style: TextStyle(
                            fontSize: 15,
                            color: Colors.black54,
                          ),
                        ),
                        decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius: BorderRadius.circular(20),
                            border:
                                Border.all(color: Colors.black54, width: 0.2)),
                      ),
                    ),
                  ),
                  Container(
                    margin: EdgeInsets.symmetric(horizontal: 5),
                    padding: EdgeInsets.symmetric(horizontal: 5, vertical: 5),
                    child: Icon(
                      AntDesign.smileo,
                      size: 22,
                      color: Colors.black54,
                    ),
                    decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(100),
                        border: Border.all(color: Colors.black54, width: 0.2)),
                  ),
                  fn.hasFocus
                      ? GestureDetector(
                          onTap: () {
                            sendMessage();
                          },
                          child: Container(
                            padding:
                                EdgeInsets.symmetric(horizontal: 10, vertical: 7),
                            child: Text(
                              'send',
                              style:
                                  TextStyle(fontSize: 16, color: Colors.black54),
                            ),
                            decoration: BoxDecoration(
                                color: Colors.white70,
                                border: Border.all(
                                    color: Color(0xffcceabb), width: 1),
                                borderRadius: BorderRadius.circular(10)),
                          ))
                      : GestureDetector(
                          child: Container(
                            margin: EdgeInsets.symmetric(horizontal: 5),
                            padding:
                                EdgeInsets.symmetric(horizontal: 5, vertical: 5),
                            child: Icon(
                              Ionicons.ios_add,
                              size: 22,
                              color: Colors.black54,
                            ),
                            decoration: BoxDecoration(
                                color: Colors.white,
                                borderRadius: BorderRadius.circular(100),
                                border: Border.all(
                                    color: Colors.black54, width: 0.2)),
                          ),
                        ),
                ],
              ),
              decoration: BoxDecoration(
                color: Colors.white,
              ),
            )
          ],
        ),
      ),
    );
  }

**Comment by darshankawar** [comment]
Hi @RaySummer,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing. The code you provided has lot of custom elements and widgets and we won't be able to use this code `as-is` to replicate the issue.  Please provide a de-coupled code sample that we can copy - paste and run to see the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by wangfeng211** [comment]
I take the same error...

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
