### ISSUE TITLE
Consider renaming the `packages` directory in the  Flutter repo.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#6202]
The current convention of storing package sources in a `packages` directory of the flutter repo is at odds with the Dart convention that treats these directories as special in package URI resolution.

For reference, see the [pkgspec DEP](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Accepted/0005%20-%20Package%20Specification/DEP-pkgspec.md).  The salient bit from the **Resolving package: URIs** section is:

> If a tool does not find a .packages file in the previous step, it should look for a packages directory next to the entry point. If the entry point is a file: URI this means checking if a packages directory exists, in all other cases, the directory is assumed to exist. The tool then resolves package URIs as if the packages directory had been specified using --package-root.
> 
> If the entry point was file: URI and a packages directory was not found in the previous step, then the tool checks for the presence of a .packages file in the parent directory of the entry point, and recursively check each parent directory up to the root directory until a .packages file is found. That .packages file is used to resolve package URIs.
> 

A consequence of the current flutter repo layout is that IDEs need to do extra heroics to play nice (https://github.com/flutter/flutter-intellij/issues/38).

The world would be a much better place for tools if the packages directory got a new name.  Maybe we could follow the Dart SDK convention and opt for `pkg`?

Any thoughts greatly appreciated.

cc @Hixie @abarth @danrubel

**Comment by sethladd** [comment]
Sort of an API stability question, since it's asking about renaming our directory structure.

**Comment by eseidelGoogle** [comment]
The pub `sdk: flutter` feature may need to be updated if this layout changes.  I'm not sure how it goes about finding packages in the flutter sdk.

**Comment by Hixie** [comment]
`packages/` directories are going away, right? That's actually why we picked this name. We considered the conflict, but it was only going to be temporary so we figured we'd take the short-term hit in favour of the right long-term name.

(Not clear what else we'd call it.)

**Comment by Hixie** [comment]
(pkg is an abbreviation and we try hard to avoid those in Flutter land)

**Comment by sethladd** [comment]
Bikesheading!

* `_packages`
* `bundled_packages`
* `vendored_packages`

**Comment by Hixie** [comment]
`packages` is better than all of those :-P

**Comment by pq** [comment]
> packages/ directories are going away, right? 

Yes!

Which implies (and this is really the point) that the [pkgspec DEP](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Accepted/0005%20-%20Package%20Specification/DEP-pkgspec.md) may get a rewrite to not treat `packages` directories as special.  Not sure how far down the road that is though.

paging @kevmoo and @lrhn for insight into a possible timeline...

**Comment by Hixie** [comment]
If `packages/` directories are still eventually going away then I recommend leaving this as-is since that means there's no new information since we originally decided on the name. :-)

**Comment by devoncarew** [comment]
@Hixie, I think pub using truckloads of symlinks in `packages/` directories is going away (`pub get --no-packages-dir` should soon be the default). But I think the pkgspec DEP will keep `packages/` as an alternative way to resolve package: references - alternative to the .packages file.

> The pub sdk: flutter feature may need to be updated if this layout changes. I'm not sure how it goes about finding packages in the flutter sdk.

Does it locate things based on being in the `<repo-root>/packages/` dir? I see these references in flutter app pubspecs:

```
dependencies:
  flutter:
    sdk: flutter
```

and know we need to pass in the `FLUTTER_ROOT` env var when running pub, but not sure how the resolution happens.

**Comment by abarth** [comment]
@devoncarew `pub` is hard-coded to look in `FLUTTER_ROOT/packages/<foo>` for package `foo` in `sdk: flutter`.

**Comment by mit-mit** [comment]
@Hixie we will ship Dart SDK 1.20 to stable later this week / early next week, and with that release the default behavoir of pub changes to produce a `.packages` file, not a `packages` dir. However, we still support, and will likely have to support for many quarters, the ability to produce a `packages` dir for compatibility reasons, so pub has a flag you can use to get such a dir.

**Comment by Hixie** [comment]
I'm sure it'll be many more quarters before we're done with Flutter. :-)

**Comment by pq** [comment]
I think we should table this.  The motivation, ultimately, was to explore a quick and _easy_ route to have the repo structure play nice in the IDE but thats not what we're looking at. 😃  Luckily, there are other angles on that and I'll pick 'em up over on flutter/flutter-intellij#38.  Thanks everyone for the input!
