### ISSUE TITLE
analyzer_benchmark mega_gallery_batch_maximum & mega_gallery_watch_maximum regressions (small)

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62045]
They're small, and I believe likely a candidate for rebaselining. Can you confirm?

![Screen Shot 2020-07-22 at 9 42 11 AM](https://user-images.githubusercontent.com/1435716/88204071-a5624000-cbff-11ea-8801-f7cdd4bc5b81.png)

**Comment by liyuqian** [comment]
These two also got rebaselined recently so I wonder if we shall close this one?
<img width="710" alt="Screen Shot 2020-07-27 at 4 08 31 PM" src="https://user-images.githubusercontent.com/22987568/88600632-932f3a00-d023-11ea-9121-5bbbd5956b1c.png">

**Comment by zanderso** [comment]
It looks like we can close this.
