### ISSUE TITLE
Update nnbd versions to .2 for update to 2.10 Dart SDK

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#62044]
This will require a manual engine roll. The versions are:

```
characters: 1.1.0-nullsafety.2
collection: 1.15.0-nullsafety.2
meta: 1.3.0-nullsafety.2
typed_data: 1.3.0-nullsafety.2
vector_math: 2.1.0-nullsafety.2
```

**Comment by jonahwilliams** [comment]
This cannot be done until the engine roll, otherwise we cannot version solve for the 2.10 SDK constraint

**Comment by zanderso** [comment]
Looks like this might be in https://github.com/flutter/flutter/pull/62255.
