### ISSUE TITLE
web_benchmarks_html draw_rect_variable_paint & draw_rect_variable_paint need baselines...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62046]
They look pretty stable since their introduction; maybe we can take as-is?
![Screen Shot 2020-07-22 at 9 49 32 AM](https://user-images.githubusercontent.com/1435716/88204787-a8a9fb80-cc00-11ea-9b5d-a9b680d2e868.png)

**Comment by mdebbar** [comment]
I set the baseline/goal to the recommended numbers. It should be fine now.
