### ISSUE TITLE
flutter desktop windows cMake error

### ISSUE THREAD

**Issue by 926** [flutter/flutter#62059]
Hi,
deleted windows file
$ flutter clean
$ flutter create .
$ flutter run -d windows

But I still get the error below :

CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory):
  The source directory

    C:/.../windows/flutter/ephemeral/.plugin_symlinks/path_provider_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

**Comment by stuartmorgan** [comment]
This is not a bug. If you are building with the latest master, Windows plugins must have CMake files.

**Comment by 926** [comment]
I understand,
Could you please point me to the documentation on how to make these CMake files ?

**Comment by 926** [comment]
Is there any shorter way than through the whole doc ?
https://cmake.org/cmake/help/latest/guide/tutorial/index.html

Sorry to insist, but flutter downgrade yields : 

    There is no previously recorded version for channel "master"

And client needs a new release...

**Comment by 926** [comment]
Build succeeded !
If there are other wandering souls facing the cmake issue :

Just make sure to get the latest **ref** from the plugins at https://github.com/google/flutter-desktop-embedding/tree/master/plugins
e.g. for path_provider_fde ref: be63fd1
for file_chooser ref : 282bb7b

Other takeaways :

Before 
    $ flutter run -d windows -v
Start with 
    $ flutter build windows -v

There might be breaking errors from other dependencies,
Until then they behaved well but the latest master turned them bunkers,
    $ flutter pub upgrade
Cooled down most of them, others I removed
