### ISSUE TITLE
CupertinoSlidingSegmentedControl: Calculated width doesn't account for highlighted style

### ISSUE THREAD

**Issue by afitz0** [flutter/flutter#62063]
`CupertinoSlidingSegmentedControl` currently determines its width based on the width of the widest child widget. This calculation doesn't account for the (slight) increase of the child's width when it's selected:

![Screen Recording 2020-07-22 at 12 29 33 PM mov](https://user-images.githubusercontent.com/400613/88219872-119c6e00-cc17-11ea-9d57-c90d17c1d804.gif)

This small change in width happens regardless of which child is the widest:

![Screen Recording 2020-07-22 at 1 10 14 PM mov](https://user-images.githubusercontent.com/400613/88223873-09473180-cc1d-11ea-943c-a4ea35a42588.gif)

---

Additionally, I think the overall width semantics don't match the iOS spec. `CupertinoSlidingSegmentedControl` currently sizes itself to be as small as it needs to be in order to fit all of the children (set to be the same width as the biggest child).

It seems like the correct semantics would be that its width is the maximum allowed by its parent. From the docs for [`UISegmentedControl`](https://developer.apple.com/documentation/uikit/uisegmentedcontrol):

```
The UISegmentedControl object automatically resizes segments to fit proportionally within their 
superview unless they have a specific width set.
```

**Comment by ManuLpz4** [comment]
Hi!
You are right, let me do a little research to PR as soon as possible 😁

**Comment by afitz0** [comment]
Thanks @ManuLpz4 for the quick work!

It looks like the bottom one in the gif is still resizing the width on the "All of them!" selection. Is that just an artifact of the GIF?

**Comment by ManuLpz4** [comment]
@afitz0 Nope, it's the current `CupertinoSlidingSegmentedControl ` and the one above is the one I'm preparing (to compare) :P

**Comment by afitz0** [comment]
Aha! Got it. :) In that case, it's looking great! Looking forward to seeing the PR. 😃

**Comment by VladyslavBondarenko** [comment]
Reproduces with current master `1.21.0-2.0.pre.114`

<details>
 <summary>code sample</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Body()));

class Body extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return BodyState();
  }
}

class BodyState extends State<Body> {
  Map<int, Widget> map;
  int selectedIndex = 0;

  @override
  void initState() {
    map = new Map();
    for (int i = 0; i < 3; i++) {
      map.putIfAbsent(
        i,
        () => Text("Tab" * (i + 1)),
      );
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: CupertinoSlidingSegmentedControl(
            onValueChanged: (value) {
              setState(() {
                selectedIndex = value;
              });
            },
            groupValue: selectedIndex,
            children: map,
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.114, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.114 at /Users/nevercode/dev/flutter
    • Framework revision ddb8e6e3bf (7 hours ago), 2020-07-22 20:00:07 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 55C8466B-5367-492B-8EFE-EC45D980571F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment]
It seems we want to do a measurement run in the layout process, but I'm not sure if that's entirely safe. 

> Additionally, I think the overall width semantics don't match the iOS spec. CupertinoSlidingSegmentedControl currently sizes itself to be as small as it needs to be in order to fit all of the children (set to be the same width as the biggest child). It seems like the correct semantics would be that its width is the maximum allowed by its parent.

I think that contradicts the behavior I see on the native component. `UISegmentedControl` does have an intrinsic size and by default it only occupies as much space as it needs on iOS. 
You can always force `CupertinoSlidingSegmentedControl` to expand by giving it a set of tight width constraints, e.g.:

```dart
SizedBox(
  width: double.infinity,
  child: CupertinoSlidingSegmentedControl(...),
)
```
I guess this also works as a workaround if the varying widget size bothers you.
