### ISSUE TITLE
VoiceOver traversal within a ListView not working correctly

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#62067]
b/ 161103275

Observe that VoiceOver will lose focus when attempting to read a SingleChildScrollView out of the viewport in a ListView.

Steps to Reproduce
- Turn on VoiceOver.
- Swipe to right the move to the next container.
- VoiceOver works fine when navigating to text 1 to 3.
- However, it will navigate to elsewhere when attempting to navigate to text 4. Meanwhile, it could not focus on text 0 to 3 any more.

Video (internal): http://rcll/cuKRuXHHSIm5lhnG6mjwDr/b1rKJ2mnEijiFIO4SIRJcV

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: _buildListViewBody(),
      ),
    );
  }

  Widget _buildListViewBody() {
    return ListView(
      children: List.generate(
        100,
        (index) => _buildContainer('Text $index'),
      ),
    );
  }

  Widget _buildContainer(String text) {
    return MergeSemantics(
      child: SingleChildScrollView(
        child: Container(
          height: 200,
          decoration: BoxDecoration(border: Border.all(color: Colors.blue)),
          child: Center(child: Text(text)),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.95, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.95 at /Users/tahatesser/Code/flutter_master
    • Framework revision 50b87dc6c3 (19 hours ago), 2020-07-22 11:09:59 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by chunhtai** [comment]
@mehmetf I wasn't able to reproduce it, the voice over traversal works correctly for me.
<details>
<summary>flutter doctor -v</summary> 
[✓] Flutter (Channel master, 1.21.0-6.0.pre.18, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.21.0-6.0.pre.18 at /Users/chtai/git/flutter
    • Framework revision 5e0ba2290f (2 hours ago), 2020-07-24 13:37:08 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chtai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (4 available)
    • yellow XR (mobile) • 00008020-000A208E26D1002E • ios            • iOS 13.5.1
    • macOS (desktop)    • macos                     • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)   • web-server                • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 84.0.4147.89
</details>

**Comment by mehmetf** [comment]
Since accessibility problems can be iOS version specific, I will ask the customer to let us know what iOS version they were testing with.

**Comment by mehmetf** [comment]
Seems you have already done that. Thanks!

**Comment by chunhtai** [comment]
Close as not reproducible
