### ISSUE TITLE
can we fade system status bar

### ISSUE THREAD

**Issue by leetomlee123** [flutter/flutter#62088]

**Comment by SaumitraVerma** [comment]
Yes,
Refer to this url

https://medium.com/nonstopio/hide-or-show-app-bar-and-bottom-navigation-bar-while-scrolling-in-flutter-3994f78e52c0

**Comment by leetomlee123** [comment]
> Yes,
> Refer to this url
> 
> https://medium.com/nonstopio/hide-or-show-app-bar-and-bottom-navigation-bar-while-scrolling-in-flutter-3994f78e52c0

sorry u misunderstand me .i means android system bar ,not app bar

**Comment by SaumitraVerma** [comment]
OK,

https://pub.dev/packages/flutter_statusbar_manager

there is a status-bar sethidden attribute

**Comment by leetomlee123** [comment]
Tks
hope it is works

**Comment by leetomlee123** [comment]
> OK,
> 
> https://pub.dev/packages/flutter_statusbar_manager
> 
> there is a status-bar sethidden attribute

tks for your help
