### ISSUE TITLE
flutter daemon does not stop app in release mode

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#6208]
When an app is started by the daemon in release mode it generates an error. The app is running on the device but cannot be stopped normally by the daemon. This particular app was generated by flutter create.

Here's a console transcript with the stack trace elided. I sync'd flutter sources (except engine) before making this. Since I'm not compiling the engine I shouldn't need to worry about that, right?

> flutter daemon
> Starting device daemon...
> [{"method":"app.start","params":{"deviceId":"00ef792d109d24ac","projectDirectory":".../flutter/myapp","startPaused":false,"mode":"release","target":"lib/main.dart","hot":true},"id":25}]
> [{"id":25,"result":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","deviceId":"00ef792d109d24ac","directory":".../flutter/myapp","supportsRestart":true}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","log":"Building APK in release mode (android-arm-release)...","progress":true,"id":"0"}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","log":"Warning: signing the APK using the debug keystore."}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","progress":true,"id":"0","finished":true}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","log":"Built build/app.apk (8.1MB)."}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","log":"Launching loader on Nexus 5X..."}}]
> [{"event":"app.log","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061","log":"Exception from flutter run: Error the service protocol is not enabled.","stackTrace" ...
> ...
> <huge stack trace>
> ...
> [{"method":"app.stop","params":{"appId":"c91c921c-f68f-414e-bea9-7e92ab310061"},"id":27}]
> [{"id":27,"result":true}]
> [{"event":"daemon.logMessage","params":{"level":"status","message":"Application finished."}}]

**Comment by devoncarew** [comment]
I suspect that the daemon code expects a service protocol port to be available for an app launch; it won't be for release mode launches. We also won't be able to stop the app via the daemon.

I don't know how we should implement the `run` button; launch in release mode, or launch in debug mode, but w/o connecting a debugger from IntelliJ?

**Comment by stevemessick** [comment]
Hmm, yeah I was just playing with `flutter run --release`. I think we need to communicate what release mode does to our users. We can't stop the app via the Stop button so we should probably disable that. @mit-mit for consideration in docs.

**Comment by mit-mit** [comment]
I would expect the Run button in IntelliJ to call `flutter run --release`. Why is it that this is not supported on emulators? How else do you test animations and other perf sensitive UI features that don't work well in slow mode?

**Comment by devoncarew** [comment]
To update: the resolution here is to change the run button to use flutter run --debug.
