### ISSUE TITLE
[AddToApp] x86_64 libflutter.so not exist when build apk

### ISSUE THREAD

**Issue by ybin0823** [flutter/flutter#62095]
## Use case
Flutter version: 1.17.5
Target platform: Android

For example, our project structure like below, 
https://flutter.dev/docs/development/add-to-app/android/project-setup
```
Master Project
   |_ Android project
   |_ iOS project
   |_ add_to_app_flutter
```

If we build apk in android, 

### android build apk
![스크린샷 2020-07-23 오후 1 07 13](https://user-images.githubusercontent.com/7553607/88251320-7920ef00-cce5-11ea-8eaf-34ff0383c84c.png)
![스크린샷 2020-07-23 오후 1 07 08](https://user-images.githubusercontent.com/7553607/88251324-7b834900-cce5-11ea-8743-b0520802687b.png)
![스크린샷 2020-07-23 오후 1 07 02](https://user-images.githubusercontent.com/7553607/88251325-7c1bdf80-cce5-11ea-99bd-15c6232ac08d.png)

There are no libflutter.so and libapp.so in x86_64.

But in flutter said, https://flutter.dev/docs/deployment/android#build-an-app-bundle
`By default, the app bundle contains your Dart code and the Flutter runtime compiled for armeabi-v7a (ARM 32-bit), arm64-v8a (ARM 64-bit), and x86-64 (x86 64-bit).`

### flutter build apk
If we run `flutter build apk` under add_to_app_flutter directory.
MasterProject/add_to_app_flutter/build/host/outputs/apk/release/app-release.apk
![스크린샷 2020-07-23 오후 1 11 35](https://user-images.githubusercontent.com/7553607/88251541-1419c900-cce6-11ea-8d92-981308da582b.png)
There are lisflutter.so and libapp.so in x86_64.

🤔 

## Proposal
We thought maybe there was an issue with `gradle`.  
So I found the `flutter.gradle` file to analyze how it works.

We added `PLATFORM_X86_64` into the `DEFAULT_PLATFORMS`
https://github.com/flutter/flutter/blob/ddb8e6e3bfef90c8674ac0ab5508e581a3873dae/packages/flutter_tools/gradle/flutter.gradle#L77-L79

And it works!!
![image](https://user-images.githubusercontent.com/7553607/88250778-95bc2780-cce3-11ea-806c-d65a39b77a0d.png)

Could you add PLATFROM_X86_64 into the `DEFAULT_PLATFORMS` at next flutter version for add-to-app ?

**Comment by jonahwilliams** [comment]
Seems like a reasonable fix.

DEFAULT_PLATFORMS are only used if your gradle script does not specify one or more target platforms though. You should be able to pass in `--Ptarget-platform=android-arm,android-arm64,android-x64`
