### ISSUE TITLE
Could not read script 'C:\Users\universal\Desktop\CT\android\app\Users\walidaits\flutter\packages\flutter_tools\gradle\flutter.gradle' as it does not exist.

### ISSUE THREAD

**Issue by gajesss** [flutter/flutter#62090]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @gajesss,
Can you try [this](https://github.com/flutter/flutter/issues/55619#issuecomment-624945046) solution and see if it works for you ?

**Comment by darshankawar** [comment]
Related to [55619](https://github.com/flutter/flutter/issues/55619)

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
