### ISSUE TITLE
No type or protocol named 'FlutterPlugin'

### ISSUE THREAD

**Issue by casualcoder404** [flutter/flutter#62102]
**When I try to flutter build ios or just run on iOS simulator, it fails with following error:**

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:5:
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.h:7:51: error: no type or protocol named 'FlutterPlugin'
    @interface FLTSharedPreferencesPlugin : NSObject <FlutterPlugin>
                                                      ^
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:11:41: error: no type or protocol named 'FlutterPluginRegistrar'
    + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
                                            ^
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:12:3: error: use of undeclared identifier 'FlutterMethodChannel'
      FlutterMethodChannel *channel = [FlutterMethodChannel methodChannelWithName:CHANNEL_NAME
      ^
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:12:25: error: use of undeclared identifier 'channel'
      FlutterMethodChannel *channel = [FlutterMethodChannel methodChannelWithName:CHANNEL_NAME
                            ^
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:12:36: error: use of undeclared identifier 'FlutterMethodChannel'
      FlutterMethodChannel *channel = [FlutterMethodChannel methodChannelWithName:CHANNEL_NAME
                                       ^
    /Users/hh/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+3/ios/Classes/FLTShare
    dPreferencesPlugin.m:14:4: error: use of undeclared identifier 'channel'
      [channel setMethodCallHandler:^(FlutterMethodCall *call, FlutterResult result) {
       ^
    6 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

And this is how it looks in xcode

<img width="1436" alt="Screenshot 2020-07-23 at 11 56 58 AM" src="https://user-images.githubusercontent.com/47086172/88257598-b84a4280-ccdb-11ea-9716-2b0780aa5917.png">

```
```

```
```

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.5 at /Users/hh/Developer/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (4th generation) • 7983738B-844D-4B69-98BF-D93F5F3550AB • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
</details>

**Please help.**

**Comment by darshankawar** [comment]
Hi @casualcoder404,
Can you try [this](https://github.com/flutter/flutter/issues/57222#issuecomment-629597999) solution and see if it works for you ?
Thanks.

**Comment by darshankawar** [comment]
Related to [58594](https://github.com/flutter/flutter/issues/58594)

**Comment by casualcoder404** [comment]
> Hi @casualcoder404,
> Can you try [this](https://github.com/flutter/flutter/issues/57222#issuecomment-629597999) solution and see if it works for you ?
> Thanks.

Hey @darshankawar thanks for the reply.

I checked that solution but I'm afraid of implementing it as there are many other configurations made to existing project for say implementing firebase and NotificationServiceExtensions etc.

**Comment by darshankawar** [comment]
Hi @casualcoder404,
Can you try by upgrading `shared_preferences` plugin to latest version, run `pub get`, then do a `flutter clean` and then `flutter run` ?

**Comment by casualcoder404** [comment]
> Hi @casualcoder404,
> Can you try by upgrading `shared_preferences` plugin to latest version, run `pub get`, then do a `flutter clean` and then `flutter run` ?

Yes sir, I tried this but didn't help.

(I tried v 0.5.7+3 and not v 0.5.8 as it is giving some errors, but I don't think that matters)

**Comment by casualcoder404** [comment]
<img width="340" alt="Screenshot 2020-07-23 at 6 09 16 PM" src="https://user-images.githubusercontent.com/47086172/88287327-c44ff780-cd0f-11ea-85d7-e35da78791c3.png">


<img width="340" alt="Screenshot 2020-07-23 at 6 10 00 PM" src="https://user-images.githubusercontent.com/47086172/88287391-d92c8b00-cd0f-11ea-8a4b-986d388c1d9d.png">

Here's a screenshot from xcode. I don't think the issue is with any particular package, as the Semantic issue and Generic issue randomly shows up on any one of the packages.

**Comment by casualcoder404** [comment]
Appdelegate.m

<img width="1019" alt="Screenshot 2020-07-23 at 6 25 22 PM" src="https://user-images.githubusercontent.com/47086172/88288776-e0ed2f00-cd11-11ea-899f-d62aab51ecbd.png">

**Comment by jmagman** [comment]
Those errors mean it can't find the Flutter.framework symbols.
What's the output of:
```
$ file ios/Flutter/Flutter.framework/Flutter
```

**Comment by casualcoder404** [comment]
> Those errors mean it can't find the Flutter.framework symbols.
> What's the output of:
> 
> ```
> $ file ios/Flutter/Flutter.framework/Flutter
> ```

$ file ios/Flutter/Flutter.framework/Flutter
ios/Flutter/Flutter.framework/Flutter: Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm_v7] [arm64]
ios/Flutter/Flutter.framework/Flutter (for architecture x86_64):        Mach-O 64-bit dynamically linked shared library x86_64
ios/Flutter/Flutter.framework/Flutter (for architecture armv7): Mach-O dynamically linked shared library arm_v7
ios/Flutter/Flutter.framework/Flutter (for architecture arm64):

**Comment by casualcoder404** [comment]
The workaround mentioned by @darshankawar worked. The only problem for me was changing the name to create new project, as it'll change other configurations such as app store id and firebase integration etc. But I was able to create a new project in different folder, with the same name. And copied lib, pubscec and android folder to it with some small changes to xcode and it worked.

Thanks everyone.

**Comment by casualcoder404** [comment]
The workaround mentioned by @darshankawar worked. The only problem for me was changing the name to create new project, as it'll change other configurations such as app store id and firebase integration etc. But I was able to create a new project in different folder, with the same name. And copied lib, pubscec and android folder to it with some small changes to xcode and it worked.

Thanks everyone.
