### ISSUE TITLE
"Failed assertion: line 784 pos 12: 'elapsedInSeconds >= 0.0': is not true" sometimes appears on iOS

### ISSUE THREAD

**Issue by rivetingpeppermint** [flutter/flutter#62103]
## Steps to Reproduce

1. Update Flutter to `1.17.5` (this error did not appear in the previous version, I used `1.12.13+hotfix.5`)
2. Run this snippet below:
``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Issue example',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Failed assertion: line 784 pos 12: 'elapsedInSeconds >= 0.0': is not true."),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              child: Text('Show dialog'),
              onPressed: (){
                return showDialog<void>(
                  barrierDismissible: false,
                  context: context,
                  builder: (BuildContext context) {
                    return WillPopScope(
                        onWillPop: () async => false,
                        child: AlertDialog(
                      title: Text('Example dialog'),
                      content: const Text('Hello there'),
                      actions: <Widget>[
                        FlatButton(
                          child: Text('Dismiss'),
                          onPressed: () {
                            Navigator.of(context).pop();
                          },
                        ),
                      ],
                    ));
                  },
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** Dialog will get dismissed without fail, every single time. This is the case with Android.

**Actual results:** On iOS, the error "Failed assertion: line 784 pos 12: 'elapsedInSeconds >= 0.0': is not true" will sometimes pop up. I haven't figured out the pattern yet. When this error appears, the dialog will be stuck on the screen and nothing will be clickable. There's also a tiny bit of blue on the "Dismiss" button, as if the button press action was stuck.

**Flutter doctor output:**
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G95, locale en-ID)
    • Flutter version 1.17.5 at /Users/macbook2/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbook2/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM P205 • RR2M900KXKX • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @rivetingpeppermint,
I verified this on latest `dev` and `beta` channels and I saw no issues while running your code. I used `iphone 11 simulator (OS 13.5)` for this. The dialog opens and closes properly without any issues.

[62103.mov.zip](https://github.com/flutter/flutter/files/4964532/62103.mov.zip)

**Comment by rivetingpeppermint** [comment]
I used an iPad Pro (9.7-inch, running iOS 13.5.1) and this happened about 1/8 of the time I dismissed dialogs.

**Comment by darshankawar** [comment]
Hi @rivetingpeppermint,
I looked at your code again and wanted to know the reason behind using `WillPopScope` inside `alertDialog`.
A `WillPopScope` is usually used to override or disable the back button for a modal route. But here as I see, you are using it inside `alertdialog`. To dismiss the dialog, you can simply using `Navigator.of(context).pop()` as a best practice because we simply need to close the dialog upon tapping `Dismiss` button. So I'd suggest you to use the latter `Navigator` line of code to close the dialog.

**Comment by rivetingpeppermint** [comment]
I use WillPopScope to prevent the dialog accidentally getting closed by the back button on Android phones because it happened quite frequently with users. 

Unrelated to dialogs but to contexts, I have  
```
final GlobalKey<NavigatorState> globalNavKey = GlobalKey(debugLabel: "globalNavKey");
```
inside a separate file for global variables, and then 
```
globalNavKey.currentState.pushNamed("/pageName");
```
in some other places, specifically to open a page after clicking push notifications. Could that be affecting something and causing the failed assertion?

**Comment by darshankawar** [comment]
@rivetingpeppermint,
Is this only happening on iPad or on other devices such as iphone, simulator or on Android devices ?

**Comment by rivetingpeppermint** [comment]
I've tried on an iPhone 7 and it happened as well. Doesn't happen on Android devices.

**Comment by darshankawar** [comment]
Hi @rivetingpeppermint,
Not sure if I missed it before, but I don't see `Cancel` button in the code you provided earlier. How do you get to Cancel button ?

**Comment by rivetingpeppermint** [comment]
The code I provided earlier was a minimal reproduction of the dialogs in my actual app. They're essentially the same except for text styles, colors etc.

**Comment by darshankawar** [comment]
Since I don't have iPad or iphone 7 to replicate this issue and unable to replicate this on simulator (iPhone 11, 13.5), I am leaving this issue open for further analysis.

**Comment by rivetingpeppermint** [comment]
I'll be able to do it in a few days, please wait for my response and don't close the issue yet.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.Thanks for your contribution.
Thank you
