### ISSUE TITLE
Flutter driver report

### ISSUE THREAD

**Issue by amreniouinnovent** [flutter/flutter#62104]
I want to make a useful report of Flutter driver test but I can see logs on console only.
How could I listen to flutter logs in Flutter driver?

I tried StackOverflow and flutter issues but nothing there.
https://stackoverflow.com/questions/63039677/flutter-driver-logs-to-a-file

I tried https://pub.dev/packages/logging but still not working
```
Logger.root.onRecord.listen((record) {
  print('${record.level.name}: ${record.time}: ${record.message}');
});
```

So is there any way I can listen to Flutter logs in Flutter driver test?

**Comment by TahaTesser** [comment]
Hi @amreniouinnovent 
I think you're referring to test coverage, it's not supported by Flutter driver 
Closing as duplicate https://github.com/flutter/flutter/issues/61236
