### ISSUE TITLE
[desktop] Add Support for Firebase for desktop 🖥

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#62114]
I had this idea since the launch of macOS in alpha and Linux too. How will we be able to use firebase with them. Windows soon.

So what I am proposing is a collaboration between firebase team and flutter team to make it fully supported. So that even the documentation has a for Flutter part.

The community can help but can’t do it alone.

**Comment by TahaTesser** [comment]
Hi @YazeedAlKhalaf 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself.  
Clsing as duplicate https://github.com/FirebaseExtended/flutterfire/issues/2028
Thanky ou
