### ISSUE TITLE
local_auth android 'no_fragment_activity' error

### ISSUE THREAD

**Issue by fbss101** [flutter/flutter#62117]
When running local auth with the new API realesed on flutter, so any project created or rebuilt in the last few weeks, error for 'no_fragment_activity' appears.

I have narrowed it to a problem with the Main activity, looking at what flutter generates with a new project:

public class MainActivity extends FlutterActivity {
   // You can keep this empty class or remove it. Plugins on the new embedding
   // now automatically registers plugins.
 }

Therefore changing FlutterActivity to FlutterFragmentActivity is useless. Any ideas on how to solve it?

**Comment by VladyslavBondarenko** [comment]
Hi @fbss101 
please follow up on https://github.com/flutter/flutter/issues/41119, closing current issue as duplicate
