### ISSUE TITLE
Unclear what "signing id" is, when fixing XCode upgrade

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6211]
Just upgraded to XCode 8. Tried to build my Gallery, and got this message:

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter run --release
Running lib/main.dart on ...
** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)

Build settings from command line:
    ARCHS = arm64
    ONLY_ACTIVE_ARCH = YES
    SDKROOT = iphoneos10.0

=== CLEAN TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===

Check dependencies
[BEROR]Signing for "Runner" requires a development team. Select a development team in the project editor.
[BEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.0'
[BEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.0'
[BEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.0'

Clean.Remove clean /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app
    builtin-rm -rf /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app

Clean.Remove clean /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app.dSYM
    builtin-rm -rf /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app.dSYM

Clean.Remove clean /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Runner.build/Release-iphoneos/Runner.build
    builtin-rm -rf /Users/sethladd/Code/flutter/examples/flutter_gallery/build/ios/Runner.build/Release-iphoneos/Runner.build

** CLEAN SUCCEEDED **

=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===

Check dependencies
Signing for "Runner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'


Could not build the precompiled application for the device.

It appears that your application still contains the default signing identifier.
Try replacing 'com.yourcompany' with your signing id
in /Users/sethladd/Code/flutter/examples/flutter_gallery/ios/Runner/Info.plist

Error running application on .

```

Love that we're trying to suggest the fix! However, when I open "/Users/sethladd/Code/flutter/examples/flutter_gallery/ios/Runner/Info.plist" I don't see something labeled "signing id".

What exactly am I supposed to change? Do we mean "Bundle identifier" ?

![screen shot 2016-10-04 at 4 06 57 pm](https://cloud.githubusercontent.com/assets/5479/19095757/9965d242-8a4c-11e6-9b0e-3ee40ba30a20.png)

**Comment by sethladd** [comment]
cc @danrubel @cbracken

**Comment by sethladd** [comment]
After I futzed around, and deleted an expired cert from my keychain, and then installed the provisioning profile again (I think I did it twice, in fact), THEN I saw this and it worked:

![screen shot 2016-10-04 at 4 32 37 pm](https://cloud.githubusercontent.com/assets/5479/19096319/4ed56a4a-8a50-11e6-8e50-9f7fb71d41b9.png)


(Note: not sure if our tools can detect the expired key, but that seems to have tripped me up)

**Comment by cbracken** [comment]
As of Xcode 8, developers now need to set both **Development Team** and one of **Provisioning Profile** or **Provisioning Profile (Deprecated)**. I'll see if we can detect this and emit a nice error message.

**Comment by sethladd** [comment]
Thanks! I think we need to update our internal "Flutter for Google Devs" doc, too. Will send a link.

**Comment by eseidelGoogle** [comment]
@xster also recently improved our messaging from `flutter run` for some kinds of signing errors.  Not sure if that affected this bug or not?

**Comment by xster** [comment]
Duping into #7839.
Already slightly tweaked the onboarding doc to mention physical deploy. 
`flutter run` should print a slightly better message now with #7879.
Will clarify the public website a bit with #7839.
It's also a little confusing that the xcode error dump is mixed in with our own flutter output messages. #7867 should make it slightly better.

**Comment by lukepighetti** [comment]
I ran into this today and I'm still not sure what it's asking me to do. Any insight?

**Comment by earyzhe** [comment]
I still have this problem also :/. amy news?

**Comment by kangwang1988** [comment]
This issue seems to be resolved by: https://github.com/flutter/website/pull/596
