### ISSUE TITLE
Cannot install Flutter on MacOS mojave 10.14.6

### ISSUE THREAD

**Issue by cpk6212000** [flutter/flutter#62111]
I am trying to install Flutter on my macOS, I followed through the guide. When I run the command
`flutter doctor -v`
It just stuck at 'building flutter tool'
I tried many times and ensured I have Admin access on my account. 
I tried to set my permanent path to Flutter too, but still doesnt work.
Could you help me? Thanks!
<img width="578" alt="Screen Shot 2020-07-23 at 4 59 10 PM" src="https://user-images.githubusercontent.com/20808253/88269006-e04e9b80-cd05-11ea-89cb-e891e5aaa5a6.png">

**Comment by TahaTesser** [comment]
Hi @cpk6212000 
Can you please provide your `flutter doctor -v` your `flutter --version --verbose` 
Thank you

**Comment by cpk6212000** [comment]
I attached the result on my first trial on running `flutter doctor -v`
When I ran the `flutter --version --verbose`, the result is also the same.
<img width="597" alt="Screen Shot 2020-07-23 at 8 28 19 PM" src="https://user-images.githubusercontent.com/20808253/88286309-20704700-cd23-11ea-9bb2-dc8211b49f64.png">
It just stuck at running and no verbose printed out.

Since I got stuck at the first run, I just deleted the whole 'flutter' folder and then download the folder, set the path again. And the results are just same. Will it caused this problem too?

**Comment by cpk6212000** [comment]
The terminal show that it is running a dart process, but without any verbose

**Comment by TahaTesser** [comment]
Hi @cpk6212000 
Is this first tiem you installng Flutter on this mac? Are you located in China?  You could try [Configuring Flutter to use a mirror site](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) 
if not, can you try a different internet connection? disable any vpn 
Thank you

**Comment by cpk6212000** [comment]
Thanks, It works with a different internet connection!

**Comment by Dayojaiye74** [comment]
Internet connection could be the issue..  Glad it's solved now
