### ISSUE TITLE
Google TOS requires explicit consent

### ISSUE THREAD

**Issue by geira** [flutter/flutter#62129]
Having just installed Flutter on Ubuntu using Snap, my first command was to configure Flutter to disable analytics. I was pretty horrified to see that this downloads more software directly from Google and then claims I have consented to the Google Terms of Service after the fact without even visiting any Google site. Clearly this is not a legally binding contract since I was neither informed in advance nor given any opportunity to the reverse the procedure. At the very least you need to implement a "Do you agree (yes/no)?" prompt in order to claim any form of informed consent here. 

Trying to revoke my consent, I failed to find any contact information on the flutter.dev website, and their "privacy" link just points to the general Google Privacy (or lack thereof) Policy which I obviously find totally unacceptable, and also has no point of contact or GDPR deletion request procedure if you don't have a Google account. What exactly is the procedure If one doesn't agree with the TOS? Deleting the source code tree makes little sense if executables have been installed elsewhere.

Anyway, as I'm sure you know, anyone can fork the Flutter codebase, remove the TOS requirement and distribute the fork as allowed by the BSD license. Situations like these are exactly the reason why FOSS was invented in the first place. Why anyone would have to accept a service TOS to compile and run a piece of open source software on their own computer is beyond me. If Google is commited to the open source movement in anything but lip service they should not demand users sell their privacy in order to use their software (something which they often have little choice in due to employer or client contracts).

```
$ sudo snap install flutter --classic
flutter 0+git.aca15f8 from Flutter Team✓ installed
$ flutter config --no-analytics
Initializing Flutter
Downloading https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.17.5-stable.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  458M  100  458M    0     0  7110k      0  0:01:05  0:01:05 --:--:-- 6954k
Flutter initialized
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (3 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Analytics reporting disabled.
```

**Comment by christopherfujino** [comment]
Flutter does have its own [Terms of Service](https://flutter.dev/tos), which this notice should absolutely link to.

**Comment by geira** [comment]
> Flutter does have its own [Terms of Service](https://flutter.dev/tos), which this notice should absolutely link to.

Actually that clearly states it is the terms of service for the Flutter *website*, not the Flutter *software*:

> The Flutter website (the “Website”) is hosted by Google. By using and / or visiting the Website, you consent to be bound by Google’s general Terms of Service and Privacy Policy.

Furthermore, claiming that just visiting a website immediately implies acceptance is not legally valid in the EU and many other juristictions. For this you need an explicit action, plus a means to withdraw consent.

What you people seem to fail to understand is the difference between a policy and an agreement. The **Privacy Policy** should be a *document* describing what you actually do in detail (presumably within the bounds of the law); it is for information only. So are most Terms of Service, which only allows for termination of the right of use if broken. The unified [Terms of Service](https://policies.google.com/terms) (which one e.g. has to agree to by opening a Google account) however is a *contract*, which includes giving Google additional permissions to collect data which would be illegal without the user's documented agreement:

> By law, you have certain rights that can’t be limited by a contract like these terms of service. 

Now, according to EU law, any terms which the user has "no real opportunity of becoming acquainted" with are not legally valid. This includes the case noted here, where the terms are only linked to after the download action has taken place.

Then there is the issue of conflicts between the Google TOS and the FOSS license, of which the latter can take precedent:

> Some of our services include software that’s offered under open source license terms that we make available to you. Sometimes there are provisions in the open source license that explicitly override parts of these terms, so please be sure to read those licenses.

The Google TOS includes many additional provisions which is not compatible with the "zero freedom" principle of Free software, i.e.  [the freedom to use the software for any purpose whatsoever](https://fsfe.org/activities/gplv3/barcelona-rms-transcript#q11-banning-bad-use).

I think the Flutter development team should take a moment to discuss within themselves whether they really want to develop Free Software, or just offer another useful tool to bolster surveillance capitalism. As we currently are considering standardizing on GoLang this is an issue we are keeping a close watch on, and so far it seems the GoLang group have managed to avoid these issues. It seems the Go software itself is remarkably free of any terms outside the BSD License, only the GoLang website is covered by the Google TOS.

**Comment by christopherfujino** [comment]
> > Flutter does have its own [Terms of Service](https://flutter.dev/tos), which this notice should absolutely link to.
> 
> Actually that clearly states it is the terms of service for the Flutter _website_, not the Flutter _software_:

You're right.

**Comment by Hixie** [comment]
The TOS are now explicitly mentioned in the README at https://github.com/flutter/flutter and on the web site on pages such as https://flutter.dev/docs/get-started/install/linux.
