### ISSUE TITLE
Wrong scroll behaviour after open/close keyboard

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#62123]
As you can see, I can't scroll before the keyboard opening, but after - I can. Looks like a mistake.

![Screen Recording 2020-07-23 at 14 37 54](https://user-images.githubusercontent.com/42138594/88292104-dcb91580-cd01-11ea-8c38-b02831b4ffb9.gif)

flutter:
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-RU)

code:
```dart
void main(){
runApp(MaterialApp(
home: Scaffold(
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: Center(
          child: SingleChildScrollView(
            physics: const BouncingScrollPhysics(),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Container(
                  color: Colors.amber,
                  height: 450,
                  width: 300,
                ),
                TextField(),
              ],
            ),
          ),
        ),
      ),
    )
));
}
```

**Comment by ykmnkmi** [comment]
flutter web beta latest: only when focusing on small window and resize to bigger size

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/60589, closing current issue as duplicate,
Comment if you disagree and I'll reopen
