### ISSUE TITLE
(Flutter Desktop FFI) Accessing a native method from Flutter Desktop for macOS crashes the app.

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#62122]
## Steps to Reproduce
While trying to access the native methods inside a dylib file from a Flutter macOS app, it crashes the app.

Note: this is not a release build, I am trying to setup the FFI setup in the debug mode.

1. I compiled the C code from https://github.com/dart-lang/samples/tree/master/ffi/hello_world 
2. I added the resulting dylib file into the Xcode from "Frameworks, Libraries and Embedded content"
3. **Embed option** was set **Embed & Sign**
4. **Target Membership** was set **Optional**
3. `flutter run --verbose`
4. The app starts just fine, when I invoke the FFI code to access the native method the app crashes without any error.

Crash log:
```shell
[ +220 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///var/folders/gd/tfxtn2j90055v3tzk05185680000gn/T/io.org.myapp/myappViRgeR/myapp/)
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 23,272ms.
[ +228 ms] ensureAnalyticsSent: 224ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 0

```

Code:
```
import 'dart:ffi' as ffi;

typedef hello_world_func = ffi.Void Function();

typedef HelloWorld = void Function();

void test_ffi() {
  final dylib = ffi.DynamicLibrary.open('heyhello.dylib');

  final hello = dylib
      .lookup<ffi.NativeFunction<hello_world_func>>('hello_world')
      .asFunction();

  hello();
}

```

<img width="832" alt="Screenshot 2020-07-23 at 6 53 01 PM" src="https://user-images.githubusercontent.com/182092/88291413-d16fe500-cd15-11ea-980f-b92bccd8ea93.png">

**Expected results:** The app prints: "Hello world"

**Actual results:** The app crashes

flutter analyze
```
No issues found! (ran in 16.0s)
```

flutter doctor -v 
```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.83, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.21.0-2.0.pre.83 at /Users/username/Library/Application Support/fvm/versions/master
    • Framework revision 9e658bc3d5 (2 days ago), 2020-07-21 03:56:07 +0200
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.6 19G73

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
Please provide a backtrace for the crash from running under a debugger.

**Comment by ganeshrvel** [comment]
@stuartmorgan 
Somehow this issue got fixed after upgrading to the latest master version which arrived this morning. But there is another issue with the FFI, for which I have raised a ticket here: https://github.com/flutter/flutter/issues/62185

Flutter 1.21.0-6.0.pre.17 • channel master • https://github.com/flutter/flutter.git
Framework • revision e64fe11542 (4 hours ago) • 2020-07-23 18:11:17 -0700
Engine • revision 626244a72c
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
