### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by HLGB26** [flutter/flutter#62126]
I am getting this error "Looking up a deactivated widget's ancestor is unsafe."

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

Now how do i save a  reference to the ancestor, i have no idea i am new to flutter and documention is not so helping me in this because there is no sample code

**Comment by VladyslavBondarenko** [comment]
Hi @HLGB26 
check [existing issues](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+Looking+up+a+deactivated+widget%27s+ancestor+is+unsafe+), is your case different?
provide your `flutter doctor -v` and a minimal complete reproducible code sample.
take a look at https://github.com/flutter/flutter/issues/47128#issuecomment-627551073

**Comment by HLGB26** [comment]
****This is how my feed page looks**** 


class QuestionFeed extends StatefulWidget {
  final  FirebaseUser loggedInUser;
  QuestionFeed({this.loggedInUser});

  @override
  _QuestionFeedState createState() => _QuestionFeedState();
}

class _QuestionFeedState extends State<QuestionFeed> {
  List<Widget> questions;
  List<String> followingsList=[];
  bool x;
  final _scaffoldKey=GlobalKey<ScaffoldState>();

  retrieveTimeLine()async{
    QuerySnapshot querySnapshot =await questionsFeedReference.orderBy("timeStamp",descending: true).getDocuments();
    setState(() {
      List<Widget> allQuestions=querySnapshot.documents.where((element) {
        if(element["type"]=="question" ){
          x=true;
          return true;
        }
        else if(element["type"]=="answer"){
          x=false;
          return true;
        }
        else{
          return false;
        }
      }).map((document)=>x?Question.fromDocument(document):Answer.fromDocument(document)).toList();
      this.questions=allQuestions;
    });
  }

//  retrieveFollowings()async{
//    QuerySnapshot querySnapshot =await followingReference.document(widget.loggedInUser.uid).collection("userFollowing").getDocuments();
//    setState(() {
//      followingsList=querySnapshot.documents.map((document) => document.documentID).toList();
//
//    });
//
//  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    retrieveTimeLine();

  }

  createUserTimeLine(){
    retrieveTimeLine();
    if(questions==null){
      return circularProgress();
    }
    else{
      return ListView(children: questions,);
    }
  }

  @override
  Widget build(context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: header(
        context,
        isAppTitle: true,
      ),
      body: RefreshIndicator(child: createUserTimeLine(),onRefresh: ()=>retrieveTimeLine(),),
    );
  }
}

**Comment by HLGB26** [comment]
**This is how my answer page looks , I am Using Zefyr Editor and then showing it in zefyr.view mode in list view**

NotusDocument _document;
ZefyrController _zefyrController;
FocusNode _focusNode;

class Answer extends StatefulWidget {
  final String questionId;
  final String userProfileImg;
  final String userId;
  final dynamic timeStamp;
  final String answer;
  final String answerId;
  final dynamic likes;
  final String userName;
  final String question;

  Answer({
    this.questionId,
    this.userId,
    this.timeStamp,
    this.likes,
    this.userName,
    this.question,
    this.answerId,
    this.answer,
    this.userProfileImg,
  });
  factory Answer.fromDocument(DocumentSnapshot documentSnapshot) {
    return Answer(
      questionId: documentSnapshot["questionId"],
      userName: documentSnapshot["userName"],
      userId: documentSnapshot["userId"],
      question: documentSnapshot["question"],
      likes: documentSnapshot["likes"],
      timeStamp: documentSnapshot["timeStamp"],
      answer: documentSnapshot["answer"],
      answerId: documentSnapshot["answerId"],
      userProfileImg: documentSnapshot["userProfileImg"],
    );
  }

  int getTotalNumberOfLikes(likes) {
     _document =NotusDocument.fromJson( jsonDecode(answer));
     _zefyrController = ZefyrController(_document);
     _focusNode=FocusNode();
    if (likes == null) {
      return 0;
    }
    int counter = 0;
    likes.values.forEach((eachValue) {
      if (eachValue == true) {
        counter = counter + 1;
      }
    });
    return counter;
  }

  @override
  _AnswerState createState() => _AnswerState(
    questionId: this.questionId,
    userName: this.userName,
    userId: this.userId,
    question: this.question,
    likes: this.likes,
    timeStamp: this.timeStamp,
    likeCount: getTotalNumberOfLikes(this.likes),
    answer:this.answer,
    answerId:this.answerId,
    userProfileImg:this.userProfileImg,
  );
}

class _AnswerState extends State<Answer> {
  final String questionId;
  final String userId;
  Timestamp timeStamp;
  Map likes;
  final String question;
  final String userName;
  final String answer;
  final String answerId;
  final String userProfileImg;
  int likeCount;
  bool isLiked;
  bool showHeart = false;


  final String currentOnlineUserId = current_user.userId;
  _AnswerState({
    this.questionId,
    this.userName,
    this.userId,
    this.question,
    this.likes,
    this.likeCount,
    this.timeStamp,
    this.userProfileImg,
    this.answer,
    this.answerId,
  });

  final _scaffoldKey=GlobalKey<ScaffoldState>();




  @override
  Widget build(BuildContext context) {
    isLiked = (likes[currentOnlineUserId] == true);
    return  Container(
      height: 600,
      child: ZefyrScaffold(
        key: _scaffoldKey,
        child: ZefyrEditor(
          padding: EdgeInsets.all(16),
          controller: _zefyrController,
          mode: ZefyrMode.view,
          focusNode: _focusNode,
          imageDelegate: MyAppZefyrImageDelegate(),
          physics: NeverScrollableScrollPhysics(),
        ),
      ),
    );

**Comment by HLGB26** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

E:\flutter\quantumApp\functions>flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
    • Flutter version 1.17.4 at C:\programs\flutter\flutter
    • Framework revision 1ad9baa8b9 (5 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\programs\android_sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\programs\android_sdk
    • Java binary at: C:\programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\programs\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by HLGB26** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 4.0)
> [√] Connected device (1 available)
> 
> • No issues found!
> 
> E:\flutter\quantumApp\functions>flutter doctor -v
> [√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
> • Flutter version 1.17.4 at C:\programs\flutter\flutter
> • Framework revision [1ad9baa](https://github.com/flutter/flutter/commit/1ad9baa8b99a2897c20f9e6e54d3b9b359ade314) (5 weeks ago), 2020-06-17 14:41:16 -0700
> • Engine revision ee76268252
> • Dart version 2.8.4
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\programs\android_sdk
> • Platform android-30, build-tools 29.0.3
> • ANDROID_HOME = C:\programs\android_sdk
> • Java binary at: C:\programs\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
> • Android Studio at C:\programs\Android Studio
> • Flutter plugin version 47.1.2
> • Dart plugin version 193.7361
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] Connected device (1 available)
> • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
> 
> • No issues found!



> ****This is how my feed page looks****
> 
> class QuestionFeed extends StatefulWidget {
> final FirebaseUser loggedInUser;
> QuestionFeed({this.loggedInUser});
> 
> @override
> _QuestionFeedState createState() => _QuestionFeedState();
> }
> 
> class _QuestionFeedState extends State {
> List questions;
> List followingsList=[];
> bool x;
> final _scaffoldKey=GlobalKey();
> 
> retrieveTimeLine()async{
> QuerySnapshot querySnapshot =await questionsFeedReference.orderBy("timeStamp",descending: true).getDocuments();
> setState(() {
> List allQuestions=querySnapshot.documents.where((element) {
> if(element["type"]=="question" ){
> x=true;
> return true;
> }
> else if(element["type"]=="answer"){
> x=false;
> return true;
> }
> else{
> return false;
> }
> }).map((document)=>x?Question.fromDocument(document):Answer.fromDocument(document)).toList();
> this.questions=allQuestions;
> });
> }
> 
> // retrieveFollowings()async{
> // QuerySnapshot querySnapshot =await followingReference.document(widget.loggedInUser.uid).collection("userFollowing").getDocuments();
> // setState(() {
> // followingsList=querySnapshot.documents.map((document) => document.documentID).toList();
> //
> // });
> //
> // }
> 
> @override
> void initState() {
> // TODO: implement initState
> super.initState();
> retrieveTimeLine();
> 
> }
> 
> createUserTimeLine(){
> retrieveTimeLine();
> if(questions==null){
> return circularProgress();
> }
> else{
> return ListView(children: questions,);
> }
> }
> 
> @override
> Widget build(context) {
> return Scaffold(
> key: _scaffoldKey,
> appBar: header(
> context,
> isAppTitle: true,
> ),
> body: RefreshIndicator(child: createUserTimeLine(),onRefresh: ()=>retrieveTimeLine(),),
> );
> }
> }

Also i am getting the error on Answer Page and not on feed page

**Comment by HLGB26** [comment]
![1](https://user-images.githubusercontent.com/65150064/88304803-582cbe00-cd26-11ea-8c9b-dedca031d373.jpg)
![2](https://user-images.githubusercontent.com/65150064/88304838-67137080-cd26-11ea-8234-2c6333f87523.jpg)
![5](https://user-images.githubusercontent.com/65150064/88304976-8e6a3d80-cd26-11ea-917b-7cabc6b7376d.jpg)

**Comment by VladyslavBondarenko** [comment]
@HLGB26 
would be helpful if you make your code sample [minimal and complete](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by HLGB26** [comment]
Here is the code:

class QuestionFeed extends StatefulWidget {
  final  FirebaseUser loggedInUser;
  QuestionFeed({this.loggedInUser});

  @override
  _QuestionFeedState createState() => _QuestionFeedState();
}

class _QuestionFeedState extends State<QuestionFeed> {
  List<Widget> questions;
  List<String> followingsList=[];
  bool x;
  final _scaffoldKey=GlobalKey<ScaffoldState>();

  retrieveTimeLine()async{
    QuerySnapshot querySnapshot =await questionsFeedReference.orderBy("timeStamp",descending: true).getDocuments();
    setState(() {
      List<Widget> allQuestions=querySnapshot.documents.where((element) {
        if(element["type"]=="question" ){
          x=true;
          return true;
        }
        else if(element["type"]=="answer"){
          x=false;
          return true;
        }
        else{
          return false;
        }
      }).map((document)=>x?Question.fromDocument(document):Test()).toList();
      this.questions=allQuestions;
    });
  }

//  retrieveFollowings()async{
//    QuerySnapshot querySnapshot =await followingReference.document(widget.loggedInUser.uid).collection("userFollowing").getDocuments();
//    setState(() {
//      followingsList=querySnapshot.documents.map((document) => document.documentID).toList();
//
//    });
//
//  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    retrieveTimeLine();

  }

  createUserTimeLine(){
    retrieveTimeLine();
    if(questions==null){
      return circularProgress();
    }
    else{
      return ListView(children: questions,);
    }
  }

  @override
  Widget build(context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: header(
        context,
        isAppTitle: true,
      ),
      body: RefreshIndicator(child: createUserTimeLine(),onRefresh: ()=>retrieveTimeLine(),),
    );
  }
}
class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
//  final _scaffoldKey=GlobalKey<ScaffoldState>();
  @override
  Widget build(BuildContext context) {
    return Column(
        children: <Widget>[
          MessagesStream(),
        ],
      );

  }
}

class MessagesStream extends StatefulWidget {

//  File importFile() async{
//    File file = await FilePicker.getFile();
//    return file;
//  }

  @override
  _MessagesStreamState createState() => _MessagesStreamState();
}

class _MessagesStreamState extends State<MessagesStream> {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
      stream: answersReference.document("038281b3-3842-4ea9-b4d8-3155a571826e").snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return Center(
            child: CircularProgressIndicator(
              backgroundColor: Colors.lightBlueAccent,
            ),
          );
        }
        final messages = snapshot.data;
        List<MessageBubble> messageBubbles = [];

        final messageText = messages.data['answer'];
//          final messageSender = message.data['sender'];
//          final currentUser = _loggedInUser.displayName;
        _document =NotusDocument.fromJson( jsonDecode(messageText));
        _zefyrController = ZefyrController(_document);
        _focusNode=FocusNode();

        final messageBubble = MessageBubble(

          text: _zefyrController ,

        );
        messageBubbles.add(messageBubble);

        return  Container(
          height: 600,
          child: ZefyrScaffold(
//        key: _scaffoldKey,
            child: ZefyrEditor(
              padding: EdgeInsets.all(16),
              controller: _zefyrController,
              mode: ZefyrMode.view,
              focusNode: _focusNode,
              imageDelegate: MyAppZefyrImageDelegate(),
              physics: NeverScrollableScrollPhysics(),
            ),
          ),
        );

      },
    );
  }
}

**Comment by VladyslavBondarenko** [comment]
@HLGB26 
glad that you found [a workaround](https://github.com/memspace/zefyr/issues/341#issuecomment-663965567),
closing as issue with the 3rd party plugin and not with flutter itself

**Comment by hamiouitarek00** [comment]
`import 'dart:ui';
import 'package:fingerprint/dashboard.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:convert';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:url_launcher/url_launcher.dart' as UrlLauncher;
import 'factoryMap.dart';
import 'main.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

import 'profileDialog.dart';

final Color backgroundColor = HexColor("#192B4A");
List userData;
var currentIndex;
var session2;

List filtered;
 GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

AnimationController _AnimationController;

class ProfileLandingPage extends StatefulWidget {
  var session;
  @override
  ProfileLandingPage({Key key, @required this.session}) : super(key: key);
  _ProfileLandingPage createState() => _ProfileLandingPage(session: session);
  _ProfileLandingPage t = new _ProfileLandingPage();
  Future<dynamic> searchFilter(var data, var session) {
    var m = t._searchFilter(data, session);
    return m;
  }
}

class _ProfileLandingPage extends State<ProfileLandingPage>
    with SingleTickerProviderStateMixin {
  var session;

  double _progress = 0;
  bool ready = false;

  _ProfileLandingPage({@required this.session});
  SearchBarResearch v = new SearchBarResearch();
  Map data;


  void startTimer(){
    new Timer.periodic(Duration(seconds: 1), (Timer timer) {
      setState(() {
        if(_progress == 1) {

          timer.cancel();
          print('Timer terminato, dati ricevuti');
          ready = true;
        }
        else _progress += 0.25;
      });
    });
  }

  Future getData() async {
    final http.Response response = await http.post(
        'https://service.isipc.it/eco/wrpc/com/isi/eco/module/crm/outlook/OutlookLogic.search.json',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'cookie': session,
        },
        body: json.encode({
          'search': 'customer',
          'sort': [
            {'property': 'RagSoc', 'direction': 'ASC'}
          ]
        }));
    final http.Response responseTel =
    await http.post('https://service.isipc.it/eco/wrpc/Customer.list.json',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'cookie': session,
        },
        body: json.encode({
          'sort': [
            {'property': 'CUST_DESC', 'direction': 'ASC'}
          ]
        }));
    data = json.decode(response.body);

    setState(() {
      userData = data['customer'];
      print("userData $userData");
      /* userData.sort();*/
      session2 = session;
    });
  }
  Future<dynamic> _searchFilter(var field, var session) async {
    final http.Response result = await http.post(
        'https://service.isipc.it/eco/wrpc/com/isi/eco/module/crm/outlook/OutlookLogic.search.json',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'cookie': session,
        },
        body: json.encode({
          'search': 'customer',
          'RagSoc': '*' + field + '*',
          //'CUST_PROV': '*' + field + '*'
        }));

    /* var test;
    for (int i=0; i<)*/


    final fData = json.decode(result.body);
    filtered = fData['customer'];
  }

  @override
  void initState() {
    super.initState();
    getData();
    startTimer();
    _AnimationController =
        new AnimationController(vsync: this, duration: Duration(seconds: 3000));
  }

  Icon cusIcon = Icon(Icons.search);
  Widget cusSearchBar = Text("Clienti");
  @override
  Widget build(BuildContext context) {
    return ready == true ? Scaffold(
        backgroundColor: Colors.white,
        resizeToAvoidBottomInset: false,
        extendBodyBehindAppBar: true,
        appBar: AppBar(
          title: cusSearchBar,
          backgroundColor: backgroundColor,
          elevation: 0.0,
          brightness: Brightness.dark,
          actions: <Widget>[
            IconButton(
              onPressed: () {
                setState(() {
                  showSearch(context: context, delegate: SearchBarResearch());
                });
              },
              icon: Icon(Icons.search),
            ),
          ],
        ),
        body: Container(
          child: v.buildSuggestions(context),
        )): Scaffold(
        backgroundColor: backgroundColor,
        resizeToAvoidBottomInset: false,
        extendBodyBehindAppBar: true,
        appBar: AppBar(
          title: cusSearchBar,
          backgroundColor: backgroundColor,
          elevation: 0.0,
          brightness: Brightness.dark,
          actions: <Widget>[
            IconButton(
              onPressed: () {
                setState(() {
                  showSearch(context: context, delegate: SearchBarResearch());
                });
              },
              icon: Icon(Icons.search),
            ),
          ],
        ),
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(15.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                CircularProgressIndicator(
                  strokeWidth: 5,
                  backgroundColor: backgroundColor,
                  valueColor: new AlwaysStoppedAnimation<Color>(Colors.white),
                  value: _progress,
                ),
              ],
            ),
          ),
        ),
    );
  }
}

class SearchBarResearch extends SearchDelegate<String> {
  @override
  List<Widget> buildActions(BuildContext context) {
    return null;
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
        icon: Icon(Icons.arrow_back),
        onPressed: () {
          print(filtered.length.toString());
          close(context, null);
          buildSuggestions(context);
        });
  }

  @override
  Widget buildResults(BuildContext context) {
    // return null;
    ProfileLandingPage t = new ProfileLandingPage(session: session2);

    if (query.length > 2) {
      return FutureBuilder(
          future: t.searchFilter(query, session2),
          builder: (context, projectSnap) {
            return ListView.builder(
              itemCount: filtered == null ? 0 : filtered.length,
              itemBuilder: (context, index) {
                var code = filtered[index]['CodCf'];
                return Slidable(
                  actionPane: SlidableDrawerActionPane(),
                  actionExtentRatio: 0.25,
                  child: Container(
                    color: Colors.white,
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: ListTile(
                          onTap: () {
                            print('il codice è $code');
                            currentIndex = index;
                            Navigator.of(context).push(
                                new MaterialPageRoute<Null>(
                                    builder: (BuildContext context) {
                              print('index di partenza $index');
                              var x = code;
                              print('codice di partenza ' + session2);
                              return myDialog(
                                session: session2,
                                index: index,
                                code: x,
                              );
                            }));
                          },
                          leading: CircleAvatar(
                            backgroundColor: HexColor('#FFB400'),
                            child: Icon(
                              Icons.supervisor_account_rounded,
                              color: Colors.white,
                            ),
                            foregroundColor: Colors.white,
                          ),
                          title: Text(filtered[index]['RagSoc'].toString()),
                          subtitle: Text(filtered[index]['Comune'] +
                              ', ' +
                              filtered[index]['Provincia'].toString() + '\n' + filtered[index]['Indi'], )
                      ),
                    ),
                  ),
                  actions: <Widget>[
                    IconSlideAction(
                        caption: 'Chiama',
                        color: Colors.white,
                        icon: Icons.call,
                        foregroundColor: HexColor('#192B4A'),
                        onTap: () {
                          if (filtered[index]['CUST_PHONE'] == "") {
                            AlertDialog(
                                content: Text('Numero non disponibile'));
                          } else
                            UrlLauncher.launch('tel://3451174506' /*+
                                filtered[index]['CUST_PHONE'].toString()*/);
                        }),
                  ],
                  secondaryActions: <Widget>[
                    IconSlideAction(
                      caption: 'Raggiungi',
                      color: Colors.white,
                      icon: Icons.add_location,
                      foregroundColor: HexColor('#192B4A'),
                      onTap: () {
                        Navigator.of(context).push(new MaterialPageRoute<Null>(
                            builder: (BuildContext context) {
                              return MapsState(
                                session: session2,
                                index: index,
                                desc: filtered[index]['RagSoc'],
                                addr: filtered[index]['Indi'],
                                prov: filtered[index]['Provincia'],
                                zip: filtered[index]['Cap'],
                              );
                            },
                            fullscreenDialog: true));
                      },
                    ),
                  ],
                );
              },
            );
          });
    } else {
      filtered = userData;
      return buildList(context);
    }
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    ProfileLandingPage t = new ProfileLandingPage(session: session2);
    if (query.length > 2)
      return FutureBuilder(
          future: t.searchFilter(query, session2),
          builder: (context, projectSnap) {
            return ListView.builder(
              itemCount: filtered == null ? 0 : filtered.length,
              itemBuilder: (context, index) {
                var code = filtered[index]['CodCf'];
                return Slidable(
                  actionPane: SlidableDrawerActionPane(),
                  actionExtentRatio: 0.25,
                  child: Container(
                    color: Colors.white,
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: ListTile(
                          onTap: () {
                            print('il codice è $code');
                            currentIndex = index;
                            Navigator.of(context).push(
                                new MaterialPageRoute<Null>(
                                    builder: (BuildContext context) {
                              print('index di partenza $index');
                              var x = code;
                              print('codice di partenza ' + session2);
                              return myDialog(
                                session: session2,
                                index: index,
                                code: x,
                              );
                            }));
                          },
                          leading: CircleAvatar(
                            backgroundColor: HexColor('#FFB400'),
                            child: Icon(
                              Icons.supervisor_account_rounded,
                              color: Colors.white,
                            ),
                            foregroundColor: Colors.white,
                          ),
                          title: Text(filtered[index]['RagSoc'].toString()),
                          subtitle: Text(filtered[index]['Comune'] +
                              ', ' +
                              filtered[index]['Provincia'].toString() + '\n' + filtered[index]['Indi'])),
                    ),
                  ),
                  actions: <Widget>[
                    IconSlideAction(
                        caption: 'Chiama',
                        color: Colors.white,
                        icon: Icons.call,
                        foregroundColor: HexColor('#192B4A'),
                        onTap: () {
                          if (filtered[index]['CUST_PHONE'] == "") {
                            AlertDialog(
                                content: Text('Numero non disponibile'));
                          } else
                            UrlLauncher.launch('tel:// '+
                                filtered[index]['CUST_PHONE'].toString());
                        }),
                  ],
                  secondaryActions: <Widget>[
                    IconSlideAction(
                        caption: 'Raggiungi',
                        color: Colors.white,
                        icon: Icons.add_location,
                        foregroundColor: HexColor('#192B4A'),
                        onTap: () {
                          Navigator.of(context)
                              .push(new MaterialPageRoute<Null>(
                                  builder: (BuildContext context) {
                                    return MapsState(
                                      session: session2,
                                      index: index,
                                      desc: filtered[index]['RagSoc'],
                                      addr: filtered[index]['Indi'],
                                      prov: filtered[index]['Provincia'],
                                      zip: filtered[index]['Cap'],
                                    );
                                  },
                                  fullscreenDialog: true));
                        }),
                  ],
                );
              },
            );
          });
    else {
      filtered = userData;
      return buildList(context);
    }
  }
}

buildList(BuildContext context) {
  return ListView.builder(
    itemCount: filtered == null ? 0 : filtered.length,
    itemBuilder: (context, index) {
      return Slidable(
        actionPane: SlidableDrawerActionPane(),
        actionExtentRatio: 0.25,
        child: Container(
          color: Colors.white,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: ListTile(
              onTap: () {
                currentIndex = index;
                Navigator.of(context).push(
                    new MaterialPageRoute<Null>(builder: (BuildContext context) {
                  var x = filtered[currentIndex]['CodCf'];
                  return new myDialog(
                    session: session2,
                    index: index,
                    code: x,
                  );
                }));
              },
              leading: CircleAvatar(
                backgroundColor: HexColor('#FFB400'),
                child: Icon(
                  Icons.supervisor_account_rounded,
                  color: Colors.white,
                ),
                foregroundColor: Colors.white,
              ),
              title: Text(filtered[index]['RagSoc'].toString()),
              subtitle: Text(filtered[index]['Comune'] +
                  ', ' +
                  filtered[index]['Provincia'].toString() +  '\n' + filtered[index]['Indi']),
            ),
          ),
        ),
        actions: <Widget>[
          IconSlideAction(
              caption: 'Chiama',
              color: Colors.white,
              icon: Icons.call,
              foregroundColor: HexColor('#192B4A'),
              onTap: () {
                if (filtered[index]['CUST_PHONE'] == "") {
                  AlertDialog(content: Text('Numero non disponibile'));
                } else
                  UrlLauncher.launch('tel://3451174506' /*+
                                filtered[index]['CUST_PHONE'].toString()*/);
              }),
        ],
        secondaryActions: <Widget>[
          IconSlideAction(
            caption: 'Raggiungi',
            color: Colors.white,
            icon: Icons.add_location,
            foregroundColor: HexColor('#192B4A'),
            onTap: () {
              Navigator.of(context).push(new MaterialPageRoute<Null>(
                  builder: (BuildContext context) {
                    return MapsState(
                      session: session2,
                      index: index,
                      desc: filtered[index]['RagSoc'],
                      addr: filtered[index]['Indi'],
                      prov: filtered[index]['Provincia'],
                      zip: filtered[index]['Cap'],
                    );
                  },
                  fullscreenDialog: true));
            },
          ),
        ],
      );
    },
  );
}

Future<void> _showError(context) {
  return showDialog<void>(
    context: context,
    barrierDismissible: false, // user must tap button!
    builder: (BuildContext context) {
      return AlertDialog(
        title: Text('Attenzione'),
        content: SingleChildScrollView(
          child: ListBody(
            children: <Widget>[
              Text('Numero non disponibile'),
            ],
          ),
        ),
        actions: <Widget>[
          TextButton(
            child: Text('Chiudi'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
        ],
      );
    },
  );
}

`


i'm facing the same issue, can anyone help??
