### ISSUE TITLE
Import Flutter generated SDK into React Native Application

### ISSUE THREAD

**Issue by mindbirth** [flutter/flutter#62124]
Hi!

Not sure where to ask this issue, so please bear with me.

We're in the process of finalizing a Flutter based SDK for Android and iOS. The outputs are the standard .aar for Android and .framework for iOS. 
The Flutter based SDK will have UI components and non-UI components related to internal and background logic. 

When using native Android and iOS applications we know this is fine. We don't have issues (well, at least not issues we cannot overcome) when doing things "the old fashioned way".

However, we also have the purpose to use these SDKs on a React Native Application, meaning the React Native Application will have to import the .aar and .framework according to the platform. 
Well, this sort of thing is something React Native already supports. However, the question now is if there will be an issue because the SDK is based on Flutter and if that will break and collide with the React Native components somehow.

Yes, we will begin testing shortly to evaluate it. BUT, in the meanwhile, did someone else already tried it before? What problems appeared? What configurations are required? Any tips or suggestions to take into account when developing/generating sdk/importing sdk?

Any tips and suggestions are most welcomed.

If this is relevant to anyone, I can also give updates about the results we uncover during the investigation. That might be helpful to someone else.

Thanks and kind regards to everyone!

**Comment by jmagman** [comment]
This is probably a better question for the Flutter community than GitHub since you haven't actually hit an issues yet (maybe try the Discord help channel?) https://flutter.dev/community
You can also look into https://flutter.dev/docs/development/add-to-app for embedding the aar and framework into an existing application.

**Comment by jmagman** [comment]
Please file any Flutter issues you find during your investigation!
