### ISSUE TITLE
android_view_scroll_perf__timeline_summary benchmarks regressed

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62137]
90th_percentile_frame_rasterizer_time_millis, 99th_percentile_frame_rasterizer_time_millis, average_frame_rasterizer_time_millis, and worst_frame_rasterizer_time_millis, worst_frame_rasterizer_time_millis. Clear signal at https://github.com/flutter/flutter/pull/60238, so maybe this is a test issue?

![Screen Shot 2020-07-23 at 9 10 23 AM](https://user-images.githubusercontent.com/1435716/88310316-5df1b780-ccc4-11ea-9eb5-e8bd4b2f1e57.png)

cc @cyanglaz

**Comment by blasten** [comment]
I rebaselined the goal as the previous goal wasn't accounting for the entire cost of the feature.
