### ISSUE TITLE
I want to make a feed page just like quora.

### ISSUE THREAD

**Issue by HLGB26** [flutter/flutter#62134]
I  want to take documents from firestore and show them in feed page , but i am confused between using stream builder or query snapshot to get document data.Which one should i use?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
