### ISSUE TITLE
Blank screen when running a flutter web project

### ISSUE THREAD

**Issue by DiegoMoSi** [flutter/flutter#62149]
I created a flutter web app according to the steps in https://flutter.dev/docs/get-started/web, I tried running the default application that you get when you create a new flutter project, I haven't changed a single line of code, and I get a blank screen.
I don't get an error, just a blank screen.
The flutter version that I am currently running: Flutter 1.20.0-7.2.pre • channel beta
Below are pictures of the blank screen, the blank screen with the google chrome console open, and a picture of my terminal when I run the app:
![blank_screen](https://user-images.githubusercontent.com/65504911/88317632-2a705680-ccdf-11ea-888d-03a18c29b70e.PNG)
![blank_flutter_console](https://user-images.githubusercontent.com/65504911/88317642-2f350a80-ccdf-11ea-911f-bb28acf51174.PNG)
![flutter_console](https://user-images.githubusercontent.com/65504911/88318347-34df2000-cce0-11ea-8063-dc0f81577366.PNG)

Here is the public github repo of the project in case you are interested:
https://github.com/DiegoMoSi/web_app_trial.git

**Expected results:** See the counter app that all flutter projects start with.

**Actual results:** Blank screen.

<details>
  <summary>
</summary>

```
```
[ +117 ms] executing: [C:\src\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +81 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] a2bde82fbd52e09057a4146f46889f4e10342d32
[   +1 ms] executing: [C:\src\flutter\flutter/] git tag --contains HEAD
[  +76 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0-7.2.pre
[   +9 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url origin
[  +52 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +73 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: C:\Users\pinol\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +57 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +11 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +185 ms] Generating
C:\Users\pinol\OneDrive\Escritorio\flutter_web\web_app_trial\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +99 ms] Launching lib\main.dart on Chrome in debug mode...
[  +65 ms] Updating assets
[  +87 ms] Syncing files to device Chrome...
[  +41 ms] Generating
C:\Users\pinol\OneDrive\Escritorio\flutter_web\web_app_trial\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +36 ms] <- reset
[   +8 ms] C:\src\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\pinol\AppData\Local\Temp\flutter_tools.670455a8\flutter_tool.44bdb39d\app.dill   
--libraries-spec file:///C:/src/flutter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root C:\Users\pinol\AppData\Local\Temp\flutter_tools.670455a8\flutter_tools.ac5465ff      
--filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform
file:///C:/src/flutter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +22 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13857 ms] Syncing files to device Chrome... (completed in 13,957ms, longer than expected)
[   +1 ms] Synced 23.5MB.
[   +1 ms] <- accept
[   +6 ms] Caching compiled dill
[ +221 ms] [CHROME]:
[   +8 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56552/devtools/browser/92945ae4-05de-4426-8225-3b2177a5cd45

Analyzing web_app_trial...
No issues found! (ran in 13.0s)

```
```
[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.0-7.2.pre at C:\src\flutter\flutter
    • Framework revision a2bde82fbd (5 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pinol\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\pinol\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.89
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 84.0.522.40

• No issues found!

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @DiegoMoSi 
the page is loaded correctly for me running your project with the same flutter version, but on mac.
Please follow up on https://github.com/flutter/flutter/issues/61464,
closing current issue as duplicate,
if you disagree please write in the comments and I will reopen it
