### ISSUE TITLE
Firebase based app crashes on Android emulator when launched

### ISSUE THREAD

**Issue by zaidman** [flutter/flutter#62153]
Some insights:
1. Runs great on iOS emulator and devices
2. Uses the same config files as another Firebase project, which runs just fine (a year old project, with different plugins versions)
3. No exception in thrown
4. When I change my main.dart file to the famous counter example (https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b) - it still crashes, which makes me think that it's a config issue
5. I've ran it with the **--verbose** command, but the output is huge. I'd appreciate if someone could tell me what part of it I should copy here

**Comment by jonahwilliams** [comment]
You could upload the logs to a github gist or pastebin. Ultimately we cannot help at all without a way to reproduce the issue, and the logs are one part of that.

**Comment by zaidman** [comment]
Well - found out the cause for the crash (my bad):
I had **firebase_crashlytics** plugin installed, and used in my code, but not yet configured (in Firebase's console).

To whomever find it useful :)
