### ISSUE TITLE
[webview_flutter] WebView fails to open pdf links

### ISSUE THREAD

**Issue by willvlad** [flutter/flutter#62155]
To reproduce, just go to any webpage and click on a pdf file
```
 WebView(
                initialUrl: _url,
                javascriptMode: JavascriptMode.unrestricted,
                         )
```
Put any url for example, https://google.com, search for any pdf file, try to open it by tapping the link

**Comment by darshankawar** [comment]
Hi @willvlad,
I see there's a similar open issue describing your case, [](https://github.com/flutter/flutter/issues/48245).
I'd suggest you to follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by willvlad** [comment]
Which one?

**Comment by darshankawar** [comment]
@willvlad my bad, added the link.
