### ISSUE TITLE
Define Navigator default route in MaterialApp constructor param?

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#6215]
Looking with @yjbanov at providing a default route name to our app other than '/', we went on a very long walk to [here](https://github.com/flutter/engine/blob/79363675af57152559296cfd8c9026b4165f7961/shell/platform/android/org/domokit/sky/shell/SkyActivity.java#L147).  This doesn't provide a clear resolution -- it appears that this configuration is built to allow a Flutter app to receive a route from an intent to go to a new landing page.

For the leafy app, we'd like to be able to use a route such as '/trunk' as the default landing page for our app.  Is it feasible to allow this configuration?

**Comment by abarth** [comment]
The Navigator lets you specify the initial route:

https://docs.flutter.io/flutter/widgets/Navigator/initialRoute.html

The MaterialApp hard codes that to `ui.window.defaultRouteName`, but we can make that overridable as a parameter to MaterialApp.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/6216 has a fix.
