### ISSUE TITLE
The current Dart SDK version is 2.8.4. The current Flutter SDK version is 0.0.0-unknown.

### ISSUE THREAD

**Issue by Dayojaiye74** [flutter/flutter#62156]
## Steps to Reproduce

Here is my Dependencies:

''' version: 1.0.0+1

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.16.1 '''

NOW

 I get this error when I try to run my futter app since I upgraded Android Studio. Your Help will be Appreciated 

```
``` 'fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Running "flutter pub get" in flutter_note_app...                

The current Dart SDK version is 2.8.4.
The current Flutter SDK version is 0.0.0-unknown.

Because path_provider >=0.4.0 requires Flutter SDK version >=0.1.4 <2.0.0 and path_provider <0.4.0 requires SDK version <2.0.0, path_provider is forbidden.
So, because flutternoteapp depends on path_provider any, version solving failed.
pub get failed (1; So, because flutternoteapp depends on path_provider any, version solving failed.) ''''

**Comment by VladyslavBondarenko** [comment]
Hi @Dayojaiye74 
your flutter repository may be in detached HEAD state, try to switch to any channel (for example `flutter channel stable`, `flutter doctor`) and try after this, because now you have `Flutter SDK version is 0.0.0-unknown`. Did it help?

**Comment by Dayojaiye74** [comment]
I fixed it by deleting the Flutter SDK and reinstalled it..  now everything works perfectly fine ♥ @VladyslavBondarenko

**Comment by VladyslavBondarenko** [comment]
@Dayojaiye74 then I'm closing the issue
