### ISSUE TITLE
Consider using dlsym/dlopen on Android embedding to dynamically use NDK API.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#62166]
Certain NDK APIs are available at higher versions than we currently support, for example one can access the [AChoreographer](https://developer.android.com/ndk/reference/group/choreographer) on API 24+ (whereas we support API 16+), and proposed image decoding APIs would enable expanded support for image formats without a JNI hop.

It should be possible to use dlopen/dlsym to dynamically use these methods if they are available. 

I suspect that we could improve performance by avoiding a JNI hop on each vsync by accessing the choreographer dynamically from C++ when API >= 24. That would be an interesting case to prove out.

**Comment by chinmaygarde** [comment]
Is there a measurable difference in per frame performance? This is a fair amount of code to maintain.

**Comment by dnfield** [comment]
I have not tried to mesaure this.
