### ISSUE TITLE
Consider using xml parser instead of json for parsing plist

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#62160]
Flutter tools rely on `plutil` to parse plist into json. I assume we do this because dart:core comes with json decoding support.  Unfortunately, certain internal apps are picking up plist configuration that contains `<data>` tags which are not supported for json conversion.

I tried to extract certain key values but plutil isn't happy with these tags even if their specific conversion is not requested.

Sample plist:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleDisplayName</key>
        <string>Test (Dev)</string>
        <key>CFBundleLocalizations</key>
        <array>
                <data>
                828fnna
                </data>
                <string>ar</string>
                <string>bg</string>
        </array>
</dict>
</plist>
```

```
[14:34] ~$ /usr/bin/plutil -convert json -o - ~/test.plist 
/Users/mehmetf/test.plist: invalid object in plist for destination format
```

`package:xml` is not a heavy dependency so if we were willing to include it, we could sidestep this problem.

**Comment by mehmetf** [comment]
@jonahwilliams in case he has seen this in the wild. I am not sure how unusual it is for plists to not be parseable to json.

**Comment by jonahwilliams** [comment]
We already depend on package:xml for parsing android manifests, so the additional dependency isn't really a concern

**Comment by jonahwilliams** [comment]
@jmagman for thoughts on using xml parsing.

**Comment by jmagman** [comment]
The suggestion is to use `plutil -convert xml` and parse that, right?  That makes sense to me.

**Comment by jmagman** [comment]
JSON also doesn't have an equivalent for `<date>`.

**Comment by mehmetf** [comment]
I *think* plist is usually XML itself but relying on `-convert xml` is probably more robust.

**Comment by jmagman** [comment]
> I _think_ plist is usually XML itself but relying on `-convert xml` is probably more robust.

It's usually a binary on macOS, though the app developer can configure it.  Most first party apps on macOS are binary, for example.

**Comment by jmagman** [comment]
> > I _think_ plist is usually XML itself but relying on `-convert xml` is probably more robust.
> 
> It's usually a binary on macOS, though the app developer can configure it. Most first party apps on macOS are binary, for example.

"usually" and "most" were exaggerations, I see Xcode, Developer, and some utility apps are binary, most of the rest are XML.

**Comment by jmagman** [comment]
I had it backwards, `PLIST_FILE_OUTPUT_FORMAT` defaults to binary on iOS, and on macOS is "same as input" which usually means XML.

**Comment by jmagman** [comment]
The Flutter built iOS app uses the OS default and is binary.
```
$ file build/ios/Release-iphoneos/Runner.app/Info.plist 
build/ios/Release-iphoneos/Runner.app/Info.plist: Apple binary property list
```
