### ISSUE TITLE
[recipes] engine.py should `git fetch --tags` rather than `git fetch`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#62174]
We should also use the LUCI git module, rather than shelling out to `git`, so that it is more consistent between platforms.

https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#1496
https://stackoverflow.com/questions/1204190/does-git-fetch-tags-include-git-fetch

**Comment by christopherfujino** [comment]
This could possibly explain why mac build of dart sdk had a different version than linux and windows in https://github.com/flutter/flutter/issues/62146

**Comment by digiter** [comment]
Triage: this is fixed.

**Comment by christopherfujino** [comment]
Fixed by https://flutter-review.googlesource.com/c/recipes/+/4680 and https://flutter-review.googlesource.com/c/recipes/+/4662
