### ISSUE TITLE
Support driver.getWidgetDiagnostics on the web

### ISSUE THREAD

**Issue by themightychris** [flutter/flutter#62178]
It appears that when running `flutter drive` against Chrome in a web build, `driver.getWidgetDiagnostics()` hangs rather than providing any result. Is this directly due to `--release` or `--profile` needing to be used?

Is this expected to be a temporary limitation? Dart DevTools appears to work fine with the web platform (when launched for debugging from vscode at least) and seems able to access the same information that `getWidgetDiagnostics` exposes, so it seems that the underlying data _is_ available for web builds currently.

## Why?

Flutter Driver tests can be run very quickly and cheaply in Linux CI environments with ChromeDriver, while Android and iOS driving have requirements that currently exclude GitHub Actions' Linux runners. You have to use macOS runners instead which are very expensive and have their own pile of problems. Doing Flutter integration testing with ChromeDriver under Linux runners works great up until you need to tap widget diagnostics to verify the visual state of elements on the screen

**Comment by angjieli** [comment]
Is this still happening? I just tried this function with Chrome and the test finishes without any issue.

**Comment by TahaTesser** [comment]
Hi @themightychris 
Can you please provide more details asked above https://github.com/flutter/flutter/issues/62178#issuecomment-695036243
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by zachary-russell** [comment]
@TahaTesser the core of the issue was that we couldn't run Flutter for Web in debug mode w/ the test driver and getWidgetDiagnistics only gives us useful information under debug builds (profile and release give basically no information for diagnostics).

**Comment by angjieli** [comment]
IIRC, we are now able to run Flutter For Web in debug mode with Flutter Driver.
