### ISSUE TITLE
TextField Slow

### ISSUE THREAD

**Issue by andrefedev** [flutter/flutter#62173]
A simple screen with a text field on my Samsung device affects the fps in up to 76ms.

Even when I move the cursor from one side to the other and then I leave it still to eliminate some character, the application crashes for a couple of seconds.

I tried to reproduce the same error in an emulator but I did not have the problem.

    Physical device: Samsung SM-A307G / DS, Android
    One UI: 2.0
    Android: 10 

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale es-419)
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    [✓] Android Studio (version 4.0)
    [✓] VS Code (version 1.47.2)
    [✓] Connected device (4 available)

    • No issues found!

    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Fruver Admin',
          debugShowCheckedModeBanner: false,
          home: Scaffold(
            appBar: AppBar(
              title: Text('test'),
            ),
            body: Container(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.end,
                children: <Widget>[
                  Text('hello world2'),
                  Container(
                    width: double.infinity,
                    margin: EdgeInsets.only(bottom: 8.0),
                    child: TextField(
                      decoration: const InputDecoration(
                        border: UnderlineInputBorder(),
                        hintText: 'Número de teléfono',
                      ),
                    ),
                  ),
                ],
              ),

            ),
          ),
        );
      }
    }

![Screenshot_20200723-205155](https://user-images.githubusercontent.com/14114839/88354653-3aac2400-cd27-11ea-8dda-ea8940f8a064.jpg)

Edition.

The Ebay Motors application from the search engine enter some characters and start to move the cursor from one side to the other, suddenly delete some character it is impossible the app crashes, exit the application but the keyboard was still open.

**Comment by TahaTesser** [comment]
Hi @andrefedev 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/51933
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
