### ISSUE TITLE
Issue from website page 起步:安装Flutter

### ISSUE THREAD

**Issue by tanwanlanyue1** [flutter/flutter#62183]
![d15076467a0f0d8d8a231b222998e46](https://user-images.githubusercontent.com/50123920/88363553-054d1800-cdb3-11ea-83ac-2b2222300558.jpg)

**Comment by VladyslavBondarenko** [comment]
Hi @tanwanlanyue1 
is the problem with positioning text in the tooltip? if no, could you describe it?
provide please a complete minimal reproducible code sample and your `flutter doctor -v`

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
