### ISSUE TITLE
gradlew.bat file is getting deleted automatically

### ISSUE THREAD

**Issue by vatsal-27** [flutter/flutter#62189]

**Comment by TahaTesser** [comment]
Hi @vatsal-27 
This is an issue with Flutter itself, please check your antivirus 
Closing as duplicate of https://github.com/flutter/flutter/issues/56628  https://github.com/flutter/flutter/issues/61997
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by vatsal-27** [comment]
but i dont have antivirus on my system

**Comment by TahaTesser** [comment]
Hi @vatsal-27 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
