### ISSUE TITLE
local textSelectionColor and page specfic themes

### ISSUE THREAD

**Issue by millionhz** [flutter/flutter#62182]
## Use case

I want a specific text field to have a specific text selection color. I have tried searching for ways on the internet and the docs but wasn't able to find any. Also i wasn't able to find a way to get page specific theme.

This feature is not related to any problem.

### local textSelectionColor

Flutter should have a way to specify the text selection color and selection handle color on every TextFeild widget. Right now if  want to change the textSelectionColor I have to specify it ion the app level theme through themeData but this applies to all the textFeilds but I want to edit a specific field.

### page specific themes

Flutter should have a way to specify themes to specific pages. 

Just like in how we can specify namedRoutes we should also be able to specify the themes of those namedRoutes.

**Comment by Piinks** [comment]
cc @Renzo-Olivares

**Comment by Renzo-Olivares** [comment]
As of https://github.com/flutter/flutter/pull/142476, you should be able to wrap a subtree with a local `Theme` widget with a custom `TextSelectionTheme.selectionHandleColor`. For `selectionColor` you can wrap your subtree with a `DefaultSelectionStyle` widget and set the `selectionColor` to the desired value. For page specific themes, is it possible to wrap your route with a `Theme` widget?
