### ISSUE TITLE
(Flutter Desktop FFI for macOS) The output from the FFI call isn't retrieved until the next function call

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#62185]
The output from the FFI call isn't printed until the next time the function is invoked. It's printing values from the previous time the same function was called.

Target App: Flutter Desktop for macOS

## Steps to Reproduce
1. I compiled the C code from https://github.com/dart-lang/samples/tree/master/ffi/hello_world 
2. I added the resulting dylib file into the Xcode from "Frameworks, Libraries and Embedded content"
3. **Embed option** was set **Embed & Sign**
4. **Target Membership** was set **Optional**
5. `flutter run --verbose`

test_ffi dart file:
```dart
import 'dart:ffi' as ffi;

typedef hello_world_func = ffi.Void Function();

typedef HelloWorld = void Function();

void test_ffi() {
  final dylib = ffi.DynamicLibrary.open('heyhello.dylib');

  final hello = dylib
      .lookup<ffi.NativeFunction<hello_world_func>>('hello_world')
      .asFunction<HelloWorld>();


  print('This should output hello world: ');

  hello();
}
```

**Expected results:**
```shell
This should output hello world: 
Hello World
This should output hello world: 
Hello World
```

**Actual results:** 
```shell
Hello World
This should output hello world: 

Hello World
This should output hello world: 
```

```shell
[+16237 ms] Hello World
[        ] flutter: This should output hello world: 
[+1028 ms] Hello World
[        ] flutter: This should output hello world: 
[ +684 ms] Hello World
[        ] flutter: This should output hello world: 
````

flutter analyze
```shell
No issues found! (ran in 6.3s)
```

flutter doctor -v
```shell
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/username/Library/Application Support/fvm/versions/master
    • Framework revision e64fe11542 (5 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.6 19G73

• No issues found!

```

**Comment by ganeshrvel** [comment]
@TahaTesser this issue is related to desktop, not ios. Could you change the label?

**Comment by stuartmorgan** [comment]
None of this code is Flutter code; if you have an issue with things that are generic to Dart, you should file them in the Dart repository.

I'm also not at all clear what the issue you are trying to report even is; the issue title and the code and output don't match at all. Nothing is being "retrieved" in the code you've shown, nor is it clear what you mean by "until the next function" since you have no calls after the FFI call. And your output seems to show that the FFI output is actually flushed before the print output, but since you've cropped your output, and also not included all the code, it's really hard to tell what's actually going on here. My guess is that it's just a misunderstanding of output buffering, but it's impossible to tell from what's here.

If you file this as a Dart bug, I recommend explaining more clearly, including a complete sample and complete output, nor just part of each.

**Comment by ganeshrvel** [comment]
@stuartmorgan I am not sure how exactly to explain it. I have created a screen recording of whats happening.

Screen recording link: https://drive.google.com/file/d/1oFwxTUPKfL0Ev7BRV0K0TpdzQjMtdJ3Q/view?usp=sharing


As you can see the output of the native function, which is "Hello World", doesn't get flushed into the console if there is no statement after it.

```dart
  print('This should output hello world: ');

  hello();
```

From the code: `hello();` should log "Hello World" in the console but for some reason it wasn't happening (as seen in the video). The output of hello(); was kept as a backlog to be printed in the console until the next time I invoke the test_ffi method.

How did I fix it:
I added another statement after the `hello();`.
```dart
  print('This should output hello world: ');

  hello();

  print('EOD ');
```


Strange, I don't know if it's a bug or whether it is supposed to work this way.

**Comment by stuartmorgan** [comment]
> @stuartmorgan I am not sure how exactly to explain this. I have created a screen recording of the issue.

Not pruning off the first `flutter: This should output hello world: ` from your "Actual results" section, thus making it look like you were seeing out-of-order print statement interleaving when that's not actually what's happening, would have been a significant improvement.

> As you can see that the output of the native function, which is "Hello World", doesn't get flushed into the console if there is no statement after it.

As I said above then: "My guess is that it's just a misunderstanding of output buffering". You're using a non-flushing call in the C code, so I'm not sure why you expect it to be printed immediately.
