### ISSUE TITLE
Expose a way to determine whether a widget is part of the project

### ISSUE THREAD

**Issue by Norbert515** [flutter/flutter#62187]
## Use case

Some debugging tools might benefit from the information whether a widget/ element is inside the project or not.
Such tools might want to identify the widget which is being pressed on the screen. 
Right now, it is not possible to determine whether such widget is inside the project or not because anything related to `_HasCreationLocation` and `_Location` is private inside the `widget_inspector.dart` file.

## Proposal

I propose a very small API that takes a widget/element and determines whether it is inside the project or not. Optionally such a method could also return lines numbers etc.
It wouldn't be necessary to expose the `_Location` itself and thus keeping the API surface very small.

```dart
bool _isLocalCreationLocation(Object object) {
  final _Location location = _getCreationLocation(object);
  if (location == null)
    return false;
  return WidgetInspectorService.instance._isLocalCreationLocation(location);
}
```

This is a top-level function, which could be made public.

Right now, the only way I see to use this information is forking Flutter and making some methods public. If there is any way to access this information right now, I'd be happy to know!

**Comment by jacob314** [comment]
I'm happy to approve a CL to make it public. The only reason it is private is due to an abundance of caution about exposing a larger public api.
Maybe call the method debugIsLocalCreationLocation and guard it so it can only be used in debug mode?

**Comment by Norbert515** [comment]
That sounds great!
For my use-case, knowing whether a widget/ element is part of the project is enough. But I could imagine use-cases where the actual location would be of interest too.

Do you think exposing: 

```dart
_Location _getCreationLocation(Object object) {
  final Object candidate =  object is Element ? object.widget : object;
  return candidate is _HasCreationLocation ? candidate._location : null;
}
```

or similar would make sense too?

Regarding the guard for debug mode, would a:

```dart
if(kReleaseMode) return null
```

suffice?

**Comment by jacob314** [comment]
I would expose in debug mode only so not profile mode. You will see a bunch of blocks like
```dart
bool isLocal = false;
assert(() {
  isLocal = ...;
}());
return isLocal;
```
in the framework. 
If you want to expose _Location you will need to make it public while continuing to expose the private _Location class as that name is depended on by the kernel transform. It might be useful to refactor the _Location API a bit before exposing. If it is refactored, you would need to either update the kernel transformer in the dart sdk that uses it or refactor it in a way that doesn't expose the _Location class but exposes perhaps a smaller public interface.

**Comment by Norbert515** [comment]
Ok thanks, I'll start with a PR which exposes that one method. If necessary I'll make another one with an exposed _Location!
