### ISSUE TITLE
video_player protect video from download 

### ISSUE THREAD

**Issue by GauravPatni** [flutter/flutter#62192]
I need to integrate a video player in my flutter web project where we are providing proprietary videos to only subscribed/paid users.
But in current implementation user can easily download videos with right-click & save video as.... option. Also with show control option there an option to download videos. 
Is there any way to prevent this?

Thanks ,
Gaurav

**Comment by GauravPatni** [comment]
Any update? 
Shall I consider my web project having video content with flutter or not? plz, give recommendations ...

**Comment by shashwatadi** [comment]
Is there a workaround for this?

**Comment by mhbdev** [comment]
Dudes, No idea? no progress?

**Comment by lychnobite007** [comment]
Found any solution buddy??
