### ISSUE TITLE
There should be "The first page" and "The last page" button for PaginatedDataTable.

### ISSUE THREAD

**Issue by nxr836** [flutter/flutter#62191]
If there are thousands of table items to show, and they are sorted by Id, date of update. How could app user view the last item of current table? Click "next page" button for tens of times? That is super inconvenient.

And, the API "Goto the first page" or "Goto the last page" should be implemented and exposed to developer. For example. If the number of the items in current table could be updated dymanically, and the current page is not the first page, after the number of items is updated (like keyword searching), app user has to click "the last page" button for sometimes to go to the first page to view items.

**Comment by pedromassangocode** [comment]
This is now fixed, see https://master-api.flutter.dev/flutter/material/PaginatedDataTable/showFirstLastButtons.html.

**Comment by nxr836** [comment]
Excellent! Thanks to the Flutter team!
