### ISSUE TITLE
Add flexibility to make icon leading or trailing in `Button.icon` constructors

### ISSUE THREAD

**Issue by vin-fandemand** [flutter/flutter#62202]
## Use case

Add flexibility to make icon leading or trailing in `Button.icon` constructors

## Proposal

At the moment `Button.icon` constructors only allow leading icons. It would be nice to specify whether it would be leading or trailing to give more flexibility.

**Comment by HansMuller** [comment]
You can just swap the icon/label parameters to make the "icon" the trailing widget.

**Comment by vin-fandemand** [comment]
> You can just swap the icon/label parameters to make the "icon" the trailing widget.

Haha smart. thanks.
