### ISSUE TITLE
The plugins repository version checking logic is too restrictive

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#62212]
In particular, it requires bumping the version of a plugin even if a doc typo is fixed or a test is added, or a dev_dependency is changed. These should not ordinarily require a version bump.

This is painful especially when a change has to get reverted - see, for example, flutter/plugins#2896 which attempted to revert a commit that was never published and had to bump the version number(s) to get CI to run.

/cc @csells @amirh @cyanglaz @ditman

**Comment by ditman** [comment]
I kinda understand that anything that ends up being visible in pub.dev (like a change in the README) requires a version change (even if it's a patch), but I agree that the revert case is extra annoying. Should the check be able to detect that you're doing a revert and ease the restriction then?

**Comment by stuartmorgan** [comment]
This is resolved:
- The version check ensures that bumps are valid, but doesn't require that every change bump the version
- Reverts work (although currently it's up to the person doing the revert to ensure that the change hasn't been published; we'll need to disable this once autopublish is set up, and/or add logic to actually check against the pub.dev version)

**Comment by ditman** [comment]
There's also the `NEXT` version for the Changelog entries that can be "published later". [Like this](https://github.com/flutter/plugins/commit/2d70191bc2d69744fe7c8b22bb44846242d24df8#diff-8aa882b3af4c75822f13f8e65ad4f30002d3cabdaa180f7e13ee72ed7046c083R1-R4).
