### ISSUE TITLE
Lint failure on vulkan_swapchain_stub.cc, <vulkan.h> file not found

### ISSUE THREAD

**Issue by Adlai-Holler** [flutter/flutter#62222]
In https://github.com/flutter/engine/pull/19962 this lint failure was discovered and a `NOLINT` was added to the file at issue.

We should debug this and remove the NOLINT.

**Comment by gaaclarke** [comment]
I haven't looked into this but this probably has to do with a mixmatch of GN arguments between compiling with vulkan and running the linter.

**Comment by jonahwilliams** [comment]
Closing as obsolete
