### ISSUE TITLE
Change the organization name in already created  project

### ISSUE THREAD

**Issue by jeydi243** [flutter/flutter#62230]
## Use case

When we run `create `command the default template fill the organization name by default : **com.example**
But  when you want to publish your app on google play you must change the default organization name with your own (e.g: mysociety.com.myapp). But it difficult to change it manually in all files... The only way to indicate this is only at the beginning with the command `create`

## Proposal
If it is possible flutter should give a simpler way to change the name of the organization even after a project has been created.

**Comment by YazeedAlKhalaf** [comment]
In android, you just need to change it in the `build.gradle`

**Comment by TahaTesser** [comment]
Hi @jeydi243 
You can easily change this just like any Android app, please follow https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
