### ISSUE TITLE
Passing callback functions multiple levels down the widget tree can be inconvenient

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#6223]
This is not necessarily a bug, but something we were facing.

When some data object is held in a widget state (e.g. email conversation view), and some user action is defined multiple levels down in the widget tree (e.g. a popup menu item for that conversation), the callback function has to be passed all the way down to the descendant widget that defines the user action, which can be tedious.

Is there any better way to structure our code for this scenario?
Would `flutter_flux` be a reasonable alternative?

cc @dvdwasibi

**Comment by sethladd** [comment]
Thanks for the feedback! I wonder if this is better for the mailing list. It's an important discussion, to be sure. Would you be willing to send this to flutter-dev@googlegroups.com or our internal list?

**Comment by dvdwasibi** [comment]
This is a CL where this starts to emerge:
https://fuchsia-review.googlesource.com/#/c/11589/

I guess the problem really arises in Widget Testing.

**Comment by yyoon** [comment]
@sethladd 

Sure, I can do that. Just wanted to create an issue before our sync meeting.

**Comment by sethladd** [comment]
Thanks. For those following along, here's the thread in the mailing list: https://groups.google.com/forum/#!topic/flutter-dev/Gf7iANlKtck

Will close this for now. If you're curious or have any thoughts, please join us on the mailing list.
