### ISSUE TITLE
webview_flutter 0.3.22+1, when scroll html page sometimes all screen freeze in iOS13.5.1

### ISSUE THREAD

**Issue by Neojoke** [flutter/flutter#62245]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
When WebView load a url(https://didi.github.io/mand-mobile/#/en-US/docs/components/gesture/scroll-view), scroll the page with fingers, screen will freeze and all touches can not work.
**Actual results:** 
The html content can not response any gestures but other flutter widget work fine for example appbar, when application switch to background and back to foreground, and everything become normal. 
These scrollable html components use css3 properties and other page like this also lead this problem, anyone can help me ? thanks dude.
![8841595651941_ pic](https://user-images.githubusercontent.com/8511328/88448800-e4003080-ce73-11ea-9cf7-d53fcbd20732.jpg)
<details>
  <summary>Logs</summary>

```
```

```



```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/wupeng/development/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices
    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual,
      while gradle downloads the missing components. This functionality will
      only work if the licenses in the licenses folder in ANDROID_HOME are
      valid.
      If the Android SDK has been installed to another location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will
      not work without the currently missing SDK components.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • 柴 • 00008020-000C1D001E88003A • ios • iOS 13.5.1

! Doctor found issues in 3 categories.
```

</details>

https://pub.dev/packages/webview_flutter

**Comment by darshankawar** [comment]
Hi @Neojoke,
I see a similar open issue related to scrolling on iOS, [53490](https://github.com/flutter/flutter/issues/53490).
I'd suggest you follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by Neojoke** [comment]
@darshankawar thank you for reminding.
It’s ok on iOS 13.6 or other iOS versions.
There are a large number of users using iOS 13.5.1, so we should fix it.

**Comment by ztigunes** [comment]
i have same issue. Also, i have problem on ios 13.6 simulator. Are there any solution?

**Comment by ztigunes** [comment]
Are there any solution except ios 13.6 upgrade ?

**Comment by ztigunes** [comment]
Other webview packages  also not working on ios. We had to delay the ios deployment because of this.  
webview_flutter not updated since May 21.  Do you have a road map for this bug? Thanks. Best regards.
