### ISSUE TITLE
Lightweight mobile app emulator using flutter desktop?

### ISSUE THREAD

**Issue by manyopensource** [flutter/flutter#62246]
By default using flutter desktop won't emulate the android/ios apps, but maybe you could create something that will allow that?

**Comment by manyopensource** [comment]
But maybe that is all wrong and I can close the issue (feature request)!

**Comment by TahaTesser** [comment]
Hi @manyopensource
You can use https://pub.dev/packages/preview  if you're VSC user or you can use chrome web, set device sizes 
Besides  these approaches, i am not sure it could be done from Flutter side 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by manyopensource** [comment]
This was a feature request, not an issue! And also I need the interactivity (not just static widgets), because the solution above I think will not be interactive!
