### ISSUE TITLE
Is there any way to disable minify on flutter-web release build or pass arguments to dart2js

### ISSUE THREAD

**Issue by atiqsamtia** [flutter/flutter#62259]
How can I disable minification for a Web release build? It is messing up my JSON conversion because of class names mismatch.

There is an option for dart2js compiler which can specify the level of minifying but I can't find any documentation on how to pass that option from flutter build. 

Here you can see the option. https://dart.dev/tools/dart2js#basic-options

**Comment by jonahwilliams** [comment]
flutter build web --profile does not minify. Optimizations may still result in type names not being unique or appearing.

> It is messing up my JSON conversion because of class names mismatch

Relying on class names through toString (or some other means) sounds like a huge hack, unless you are implementing the mapping yourself. I would recommend reaching out on a flutter.dev/community site to find guidance on a better approach.
