### ISSUE TITLE
[web-infra] Linux LUCI give errors for accessing flutter_logs bucket

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#62267]
Linux LUCI give errors for accessing flutter_logs bucket, therefore has an error in the upload goldens step, example: https://chromium-swarm.appspot.com/task?id=4d9fb0db428c9710

This week it uploaded successfully many times ex: https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Engine/7270

Therefore this might also be a transient issue

**Comment by nturgut** [comment]
This was due to `buildbucket` id being `0` for led runs. automated runs should keep passing. I'm dropping the priority. As an alternative we can fix our led commands to not run this step if `buildbucket id == 0`

/cc @christopherfujino @godofredoc

**Comment by christopherfujino** [comment]
> This was due to `buildbucket` id being `0` for led runs. automated runs should keep passing. I'm dropping the priority. As an alternative we can fix our led commands to not run this step if `buildbucket id == 0`
> 
> /cc @christopherfujino @godofredoc

shouldn't we skip uploading if `api.runtime.is_experimental` (which LED sets to True)?

**Comment by godofredoc** [comment]
That functionality landed in https://flutter-review.googlesource.com/c/recipes/+/4721

**Comment by nturgut** [comment]
Closing the issue since fix has landed.
