### ISSUE TITLE
add flutter info in useragent in webview_flutter;

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#62261]
add flutter info in useragent in webview_flutter so that js in webview know it is loaded by flutter plugin

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
