### ISSUE TITLE
Flutter StreamBuilder what is the scope to your children

### ISSUE THREAD

**Issue by andrefedev** [flutter/flutter#62279]
As I understand the logic it would be that if I have a StreamBuilder that has a "FirebaseUser" stream, it will be executed every time the user logs in or logs out. But when this happens, any screens other than (LoginScreen() and HomeScreen()) are not redirected to the proper screen.

I have a button to log out, this I will use intentionally for the example. On HomeScreen() and AnotherScreen(). When I press the Logout button on HomeScreen() my app redirects to LoginScreen(). **The problem is that when I try to log out of AnotherScreen(), it actually logs out but doesn't redirect to LoginScreen().**

   #### main.dart

    return StreamBuilder<FirebaseUser>(
      stream: FirebaseAuth.instance.onAuthStateChanged,
      builder: (context, AsyncSnapshot<FirebaseUser> snapshot) {
        // execute others..
        final user = snapshot.data;
        if (user != null) {
          return HomeScreen();
        } else {
          return LoginScreen();
        }
      }
    )

   #### HomeScreen.dart

    return Scaffold(
      body: Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              onPressed: () => FirebaseAuth.instance.signOut(),
              child: Text('Signout'),
            ),
            RaisedButton(
              child: Text("Go to AnotherScreen()")
              onPress: () {
                Navigator.push(context, MaterialPageRoute(builder: (_) => AnotherScreen()));
              }
            ),
          ],
        ),
      ),
    );

#### AnotherScreen.dart

    return Scaffold(
      body: Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Another Screen')
            RaisedButton(
              onPressed: () => FirebaseAuth.instance.signOut(),
              child: Text('Signout'),
            ),
          ],
        ),
      ),
    );

It has taken me a lot to understand what is happening, maybe I do not understand how flutter works. So does each new screen behave independently and do i need to push the page manually?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by andrefedev** [comment]
Hi @jonahwilliams,
I think this is more related to missing documentation since nowhere is the scope of StreamBuilder discussed, anyway closing this issue leaves doubt open to the community.
