### ISSUE TITLE
url_launcher list.join with new line seperator does not work

### ISSUE THREAD

**Issue by altziokas** [flutter/flutter#62276]
Dear Flutter team,

It appears that when using the join method within a url_launcher function, the separator is ignored.

Please see my attached example. 
[main.txt](https://github.com/flutter/flutter/files/4976913/main.txt)

It is a simple app that demonstrates this issue. (could not upload main.dart so i changed to .txt :-) )

while the Text(myList.join("\n")) does show the list split by new line, the below sending of email ignores the separator:

 launchURL('example@example.com', 'Example Subject', 'myList has these numbers:\n ${myList.join("\n")}');

Please see the attached file for more info such as declarations etc.

Thanks and regards,
Alex

**Comment by altziokas** [comment]
also the multi-line String does not work in url_launcher.

e.g
```
launchURL('example@example.com', 'Example Subject',
'''Example of
multiline
Text''');
```
also generates "Example of multiline text"

**Comment by stuartmorgan** [comment]
Your examples aren't valid URLs; see https://pub.dev/packages/url_launcher#encoding-urls
