### ISSUE TITLE
how can I check current status that is web or app. 

### ISSUE THREAD

**Issue by choikyubeom** [flutter/flutter#62289]
hello.

I want to know a flag code that current device is web or app.
so, if device is web, I want to show additional pages and functions.

thank you.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by choikyubeom** [comment]
^^
