### ISSUE TITLE
Extension finders for FlutterDriverExtension

### ISSUE THREAD

**Issue by marcin-jelenski** [flutter/flutter#62299]
## Use case

Flutter driver exposes only a subset of finders available in flutter "widget tests". To mention some `SerializableFinder`s: `ByText`, `ByText`, `ByType` etc.

There're cases where we need a "first element" or wait for an element which can't be described using existing finders. Also, there're some open GitHub issues which seems related:

#62106
#18445

There's an option to add a custom data handler and write interaction manually:

```dart
enableFlutterDriverExtension(
    handler: (request) async {
       // custom handler with flutter_test
    }
  );
```

Using data handler seems not as a most elegant solution though. Also, this method doesn't reuse `waitFor` nor `waitForAbsent` methods.

## Proposal

Let's make `FlutterDriverExtension::_finders` field public (or add a method), so anyone can add a custom `SerializableFinder`, read it's parameters and connect with flutter tests finder:

https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension/extension.dart#L164

**Comment by dnfield** [comment]
The direction for this is to use package:e2e instead, which supports all finders.

**Comment by marcin-jelenski** [comment]
@dnfield we've picked flutter driver for remote test execution with appium. Instrumentation and test specification is stored outside of target devices and can't be processed on Android or iOS. To be precise, instrumentation uses dart packages which aren't available on flutter - `dart:mirrors`, `dart:io`. 

Also, flutter driver is available for web and iOS while e2e package is not (and probably won't be available for a while).

Are there any circumstances why custom serializers for flutter driver shouldn't be implemented? Is it going to be deprecated? If it's not the case, we can make a code contribution.

CC @pedromassangocode

**Comment by dnfield** [comment]
E2e does support web and iOS - we're actively using it on those platforms.

It is still possible to use the flutter drive command with e2e tests to have some host driven logic.  I'd be very interested if you have an example test that isn't possible to do with e2e

**Comment by marcin-jelenski** [comment]
@dnfield  OK, my fault. I was mislead with a package description which states latest e2e it is not available for iOS yet. When it comes to host driven logic, I haven't found any examples which does similar. Where they can be found?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/9917689/88945019-c07f2080-d28d-11ea-8b14-504b98fe4b95.png">

**Comment by dnfield** [comment]
It would help to have an example of the test you're trying to write. In general the web e2e examples use at least some host driven logic. There may be gaps there.

**Comment by marcin-jelenski** [comment]
@dnfield thank you for the response. 

We're using a variety of BDD packages (https://pub.dev/packages/gherkin, https://pub.dev/packages/ogurets) and Appium, Selenium tool for multi-platform testing. Each of these loads test scenarios on a host machine and executes test cases using remote driver. Appium, Selenium and BDD packages can't be compiled and embedded into a device. 

To be precise, one of the issues is inability to read assets directory as a file (which contains text test cases):
https://github.com/flutter/flutter/issues/28162

Secondly, Appium and Selenium are heavy desktop tools which aren't expected to be ran on mobile devices. Also, we need to switch between Android and Flutter driver sometimes (Flutter embedded into existing App).

----------------

Flutter driver is a way to achieve shared test mechanism on different platforms. Remote drivers are widely used in the market:

For a web testing (it's not Flutter Web) we use Chrome WebDriver. Also there's an official Webdriver package which we've tested:
https://pub.dev/packages/webdriver

For native Android testing we're using UIAutomator as a driver:
https://developer.android.com/training/testing

For iOS we use idb:
https://github.com/facebook/idb/

----------------

Looking at the e2e source code, tests and examples, there's just command / result binding. This is similar to Flutter driver data handler.
https://github.com/flutter/plugins/blob/master/packages/e2e/test/binding_test.dart

Flutter Driver serialises it's finders and commands to json and back. It contains pretty much `SerializableFinders`. The way would be to make them public and reusable. I don't see any mechanism inside e2e package to achieve the same but writing from the scratch.

We've tried to adopt Flutter Driver as a test bridge. Undoubtedly great, it has limitations - lacking of finders, commands. We'd like to provide extensions to fill the gaps. A full-specified webdriver might be implemented some day then:
https://www.w3.org/TR/webdriver/

**Comment by dnfield** [comment]
I'm still not quite clear on what serializing a finder gets you that you couldn't get by running the test built into your app using e2e.  We are building some web driver type support into e2e, specifically for browser testing - but it's not clear to me that that model would be desireable or helpful for device based testing.

**Comment by marcin-jelenski** [comment]
@dnfield it's about remote control. Flutter driver exposes a JSON bridge to control the app with a set of commands and waits. Tests can be controlled externally, from any language or software. E2e package requires building test functions with dart and to be precompiled into a device. And that's a totally different use case.

On a host machine (PC), we have a controller software (Appium) which decides which action is performed next. 

The simplest scenario is clicking a button. PC reads a text use case and sends a command:

```dart
await driver.tap(find.text("Click me"));
```

Flutter driver waits for "Click me" text and performs a tap.

I don't see any way of doing similar with e2e package without rebuilding an app. Our need is extending a set of possible commands and finders for remote execution, not precompiling tests for device execution. Is there anything I missed? Would you mind providing any example of a web driver test you've mentioned? I haven't found any.

**Comment by dnfield** [comment]
Ahhh I see now. You want to be able to write the test/host code in languages other than. Dart?

**Comment by marcin-jelenski** [comment]
We might use dart but yes, other languages would be also possible with driver's json bridge. We'd like to add custom commands and waits extending existing implementation of flutter driver  (so raw data handler isn't an option).

**Comment by marcin-jelenski** [comment]
@dnfield any chances to move forward? We might find resources to submit a PR if a Flutter Team agrees on direction.

**Comment by dnfield** [comment]
We don't really plan to enhance flutter driver, but if you have some need and would like to submit a pr we can review it.

**Comment by marcin-jelenski** [comment]
Extended with #67916
