### ISSUE TITLE
Strech animation for CupertinoSliverNavigationBar

### ISSUE THREAD

**Issue by tidann** [flutter/flutter#62298]
## Use case
On iOS 13, the Sliver Navigation Bar "stretchs" when overscrolling. This is also a feature in Material Design, with the `stretch` property of `SliverNavigationBar` associated with `FlexibleSpaceBar` 's `stretchModes`. However this feature is not included in the `CupertinoSliverNavigationBar` class in Flutter.

## Proposal
Add this type of stretch animation to `CupertinoSliverNavigationBar`.
Illustrations : 

### Current behaviour
![current_behaviour](https://user-images.githubusercontent.com/50319695/88484734-1a6fa580-cf71-11ea-9d9e-dbf15df2ecde.gif)

### Expected behaviour
![expected_behaviour](https://user-images.githubusercontent.com/50319695/88484829-fb254800-cf71-11ea-9e82-c940feea503f.gif)

### Material equivalent
![material_equivalent](https://user-images.githubusercontent.com/50319695/88484751-34a98380-cf71-11ea-8de9-90344a6f4fe3.gif)

**Comment by hacnguyen1412** [comment]
yeah, I have the same issue :)))

**Comment by DanielEdrisian** [comment]
Ok, fixing this:

- [x] Stretch nav bar upon over scroll (Open PR: https://github.com/flutter/flutter/pull/71707)
- [] Expand title horizontally upon stretch

Just to clarify something: I believe the standard iOS nav items do not track the large title when stretched. See file app on iOS as an example. So in the case of trailing nav bar buttons, those buttons won't follow the nav title like the example you've shown. I think in your example, we're seeing a custom title view? (correct me if I'm wrong)

 cc @xster

**Comment by xster** [comment]
>  I believe the standard iOS nav items do not track the large title when stretched. 

If you meant the top row icon buttons, I believe so too.

**Comment by tidanneels** [comment]
> I believe the standard iOS nav items do not track the large title when stretched. 

You're right, my example was from the Messages app on iphone SE (1st gen) on iOS 13, but I think it has been changed on iOS 14

**Comment by Hixie** [comment]
If anyone is interested in helping with this issue, @DanielEdrisian wrote a PR in  https://github.com/flutter/flutter/pull/72100 which was reviewed and only needs tests added before it can land.
