### ISSUE TITLE
Please bump test package version

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#623]
The test package now works with 1.14-dev. In order to help developers test 1.14-dev with Flutter, can we bump our version range for the test package?

See also https://github.com/dart-lang/test/issues/360

Once we bump our test version range, I believe we can close https://github.com/flutter/flutter/issues/548

**Comment by sethladd** [comment]
Hm, we might not be able to do move. @Hixie writes:

> the internal API changed again

/me will check into this.

**Comment by abarth** [comment]
We just need to update our code to use the newer version of the test package.

**Comment by sethladd** [comment]
I think we're good here. The test package is now on 0.12.5+2 which allows for 1.14-dev

```
environment:
  sdk: '>=1.11.0 <1.16.0'
```
