### ISSUE TITLE
How to solve this problem Failed assertion: line 298 pos 10: 'data != null', A non-null String must be provided to a Text widget.

### ISSUE THREAD

**Issue by AmitabhBaidehi** [flutter/flutter#62305]
I've a issue, this is my code for a quiz app everything is going good but whenever i answer 5-6 question this error occurs " Failed assertion: line 298 pos 10: 'data != null', A non-null String must be provided to a Text widget."
Please help

    import 'dart:async';
    import 'dart:convert';
    import 'dart:math';
    import 'package:flutter/material.dart';
    import 'package:flutter/services.dart';
    import 'package:quiz_app/resultpage.dart';
    
    class getjson extends StatelessWidget {
      
    
      String langname;
      getjson(this.langname);
      String assettoload;
    
      
      setasset() {
        if (langname == "Python") {
          assettoload = "assets/python.json";
        } else if (langname == "Java") {
          assettoload = "assets/java.json";
        } else if (langname == "Javascript") {
          assettoload = "assets/js.json";
        } else if (langname == "C++") {
          assettoload = "assets/cpp.json";
        } else {
          assettoload = "assets/linux.json";
        }
      }
    
      @override
      Widget build(BuildContext context) {
       
        setasset();
        
        return FutureBuilder(
          future:
          DefaultAssetBundle.of(context).loadString(assettoload, cache: false),
          builder: (context, snapshot) {
            List mydata = json.decode(snapshot.data.toString());
            if (mydata == null) {
              return Scaffold(
                body: Center(
                  child: Text(
                    "Loading",
                  ),
                ),
              );
            } else {
              return quizpage(mydata: mydata);
            }
          },
        );
      }
    }
    
    class quizpage extends StatefulWidget {
      final List mydata;
    
      quizpage({Key key, @required this.mydata}) : super(key: key);
      @override
      _quizpageState createState() => _quizpageState(mydata);
    }
    
    class _quizpageState extends State<quizpage> {
      final List mydata;
      _quizpageState(this.mydata);
    
      Color colortoshow = Colors.indigoAccent;
      Color right = Colors.green;
      Color wrong = Colors.red;
      int marks = 0;
      int i = 1;
      bool disableAnswer = false;
      // extra varibale to iterate
      int j = 1;
      int timer = 30;
      String showtimer = "30";
      var random_array;
    
      Map<String, Color> btncolor = {
        "a": Colors.indigoAccent,
        "b": Colors.indigoAccent,
        "c": Colors.indigoAccent,
        "d": Colors.indigoAccent,
      };
    
      bool canceltimer = false;
    
      genrandomarray(){
        var distinctIds = [];
        var rand = new Random();
        for (int i = 0; ;) {
          distinctIds.add(rand.nextInt(10));
          random_array = distinctIds.toSet().toList();
          if(random_array.length < 10){
            continue;
          }else{
            break;
          }
        }
        print(random_array);
      }
    
      @override
      void initState() {
        starttimer();
        genrandomarray();
        super.initState();
      }
    
      // overriding the setstate function to be called only if mounted
      @override
      void setState(fn) {
        if (mounted) {
          super.setState(fn);
        }
      }
    
      void starttimer() async {
        const onesec = Duration(seconds: 1);
        Timer.periodic(onesec, (Timer t) {
          setState(() {
            if (timer < 1) {
              t.cancel();
              nextquestion();
            } else if (canceltimer == true) {
              t.cancel();
            } else {
              timer = timer - 1;
            }
            showtimer = timer.toString();
          });
        });
      }
    
      void nextquestion() {
        canceltimer = false;
        timer = 30;
        setState(() {
          if (j < 10) {
            i = random_array[j];
            j++;
          } else {
            Navigator.of(context).pushReplacement(MaterialPageRoute(
              builder: (context) => resultpage(marks: marks),
            ));
          }
          btncolor["a"] = Colors.indigoAccent;
          btncolor["b"] = Colors.indigoAccent;
          btncolor["c"] = Colors.indigoAccent;
          btncolor["d"] = Colors.indigoAccent;
          disableAnswer = false;
        });
        starttimer();
      }
    
      void checkanswer(String k) {
    
       
        if (mydata[2][i.toString()] == mydata[1][i.toString()][k]) {
          
          marks = marks + 5;
         
          colortoshow = right;
        } else {
          
          colortoshow = wrong;
        }
        setState(() {
         
          btncolor[k] = colortoshow;
          canceltimer = true;
          disableAnswer = true;
        });
        
        Timer(Duration(seconds: 2), nextquestion);
      }
    
      Widget choicebutton(String k) {
        return Padding(
          padding: EdgeInsets.symmetric(
            vertical: 10.0,
            horizontal: 20.0,
          ),
          child: MaterialButton(
            onPressed: () => checkanswer(k),
            child: Text(
              mydata[1][i.toString()][k],
              style: TextStyle(
                color: Colors.white,
                fontFamily: "Alike",
                fontSize: 16.0,
              ),
              maxLines: 1,
            ),
            color: btncolor[k],
            splashColor: Colors.indigo[700],
            highlightColor: Colors.indigo[700],
            minWidth: 200.0,
            height: 45.0,
            shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.0)),
          ),
        );
      }
    
      @override
      Widget build(BuildContext context) {
        SystemChrome.setPreferredOrientations(
            [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
        return WillPopScope(
          onWillPop: () {
            return showDialog(
                context: context,
                builder: (context) => AlertDialog(
                  title: Text(
                    "Quizstar",
                  ),
                  content: Text("You Can't Go Back At This Stage."),
                  actions: <Widget>[
                    FlatButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: Text(
                        'Ok',
                      ),
                    )
                  ],
                ));
          },
          child: Scaffold(
            body: Column(
              children: <Widget>[
                Expanded(
                  flex: 3,
                  child: Container(
                    padding: EdgeInsets.all(15.0),
                    alignment: Alignment.bottomLeft,
                    child: Text(
                      mydata[0][i.toString()],
                      style: TextStyle(
                        fontSize: 16.0,
                        fontFamily: "Quando",
                      ),
                    ),
                  ),
                ),
                Expanded(
                  flex: 6,
                  child: AbsorbPointer(
                    absorbing: disableAnswer,
                    child: Container(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: <Widget>[
                          choicebutton('a'),
                          choicebutton('b'),
                          choicebutton('c'),
                          choicebutton('d'),
                        ],
                      ),
                    ),
                  ),
                ),
                Expanded(
                  flex: 1,
                  child: Container(
                    alignment: Alignment.topCenter,
                    child: Center(
                      child: Text(
                        showtimer,
                        style: TextStyle(
                          fontSize: 35.0,
                          fontWeight: FontWeight.w700,
                          fontFamily: 'Times New Roman',
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      }
    }

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
