### ISSUE TITLE
Run python code with Flutter

### ISSUE THREAD

**Issue by VayHuit** [flutter/flutter#62300]
Hello,

I would like to know if it's actually possible to run python code inside a flutter app, locally. I need to blur faces an license plates (for anonymation reasons). I found this project [https://github.com/understand-ai/anonymizer](url), which seems to be adapted to my need but I dont know if it's possible to run it inside my app. Or maybe you know other ways to do the same then I'm oppened to all the possibilities, but it must be free / open source.

Thanks in advance.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
