### ISSUE TITLE
where: error: unrecognized arguments: git Error: Unable to find git in your PATH.

### ISSUE THREAD

**Issue by Blakeboy02** [flutter/flutter#62308]
When I run flutter in a windows 10 64bit machine I am getting the error listed in the title (where: error: unrecognized arguments: git Error: Unable to find git in your PATH.)

## Logs

`where: error: unrecognized arguments: git Error: Unable to find git in your PATH.`

N/A

(For clarification here is what is in my path: ``` C:\Program Files\Git\bin;C:\Users\User\AppData\Local\Programs\Python\Python38-32;C:\Users\User\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Users\User\Documents\flutter\bin;C:\Windows\System32;```

**Comment by Blakeboy02** [comment]
oh i have ran as administrator it is now working but now it crashes error:
``` Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter 

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:828:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:391:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:191:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:212:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#11     androidSdk (package:flutter_tools/src/globals.dart:75:38)
#12     new DeviceManager (package:flutter_tools/src/device.dart:75:27)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:128:28)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#19     deviceManager (package:flutter_tools/src/device.dart:32:44)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:321:9)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     _rootRun (dart:async/zone.dart:1184:13)
#24     _CustomZone.run (dart:async/zone.dart:1077:19)
#25     _runZoned (dart:async/zone.dart:1619:10)
#26     runZoned (dart:async/zone.dart:1539:10)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#34     _rootRun (dart:async/zone.dart:1184:13)
#35     _CustomZone.run (dart:async/zone.dart:1077:19)
#36     _runZoned (dart:async/zone.dart:1619:10)
#37     runZonedGuarded (dart:async/zone.dart:1608:12)
#38     runZoned (dart:async/zone.dart:1536:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     run.<anonymous closure> (package:flutter_tools/runner.dart)
#41     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#42     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#43     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#44     _rootRun (dart:async/zone.dart:1184:13)
#45     _CustomZone.run (dart:async/zone.dart:1077:19)
#46     _runZoned (dart:async/zone.dart:1619:10)
#47     runZoned (dart:async/zone.dart:1539:10)
#48     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#49     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#50     run (package:flutter_tools/runner.dart:48:10)
#51     main (package:flutter_tools/executable.dart:69:9)
#52     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
encountered exception: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified.
, errno = 3)

#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:828:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:391:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:191:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:212:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#11     androidSdk (package:flutter_tools/src/globals.dart:75:38)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:77:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#18     androidValidator (package:flutter_tools/src/android/android_workflow.dart:32:50)
#19     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:83:44)
#20     Doctor.validators (package:flutter_tools/src/doctor.dart:159:46)
#21     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:165:45)
#22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:271:47)
#23     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:247:26)
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#25     _rootRun (dart:async/zone.dart:1184:13)
#26     _CustomZone.run (dart:async/zone.dart:1077:19)
#27     _runZoned (dart:async/zone.dart:1619:10)
#28     runZoned (dart:async/zone.dart:1539:10)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#30     _doctorText (package:flutter_tools/runner.dart:246:19)
#31     _informUserOfCrash (package:flutter_tools/runner.dart:155:35)
#32     _handleToolError (package:flutter_tools/runner.dart:136:13)
#33     _rootRunUnary (dart:async/zone.dart:1192:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#39     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#40     _rootRun (dart:async/zone.dart:1184:13)
#41     _CustomZone.run (dart:async/zone.dart:1077:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```

**Comment by darshankawar** [comment]
Hi @Blakeboy02,
I see there's a similar open issue describing your case, [59770](https://github.com/flutter/flutter/issues/59770).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
