### ISSUE TITLE
Ability to load subtitle from URL for videoplayer

### ISSUE THREAD

**Issue by gowthamkrishnabj** [flutter/flutter#62318]
Loading of subtitles from the network, sync with video playback.

**Comment by pedromassangocode** [comment]
Hi @gowthamkrishnabj 
Can you please elaborate more what do you want? Your statement is not clear if this is a feature request or an issue with Flutter.

Thank you

**Comment by gowthamkrishnabj** [comment]
Hi @pedromassango,

Flutter has a video playback plugin, that allows you to add local subtitle file. I just wanted to know, how to pass the below subtitle_uri to the video player.
 {
        "name": "SSA/ASS position & alignment",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-avc-baseline-480.mp4",
        "subtitle_uri": "https://storage.googleapis.com/exoplayer-test-media-1/ssa/test-subs-position.ass",
        "subtitle_mime_type": "text/x-ssa",
        "subtitle_language": "en"
      }


below code from pub.dev
Future<ClosedCaptionFile> _loadCaptions() async {
    final String fileContents = await DefaultAssetBundle.of(context)
        .loadString('assets/bumble_bee_captions.srt');
    return SubRipCaptionFile(fileContents);
  }
I understood we can give an asset path, but I wanted to pass the subtitle URL instead of local assets. 
This may not be an issue, just wanted to know to implement using flutter. 


Thanks,
Gowtham

**Comment by vanlooverenkoen** [comment]
It is possible to use a subtitle. You just have to download the file yourself. 
```
  Future<ClosedCaptionFile> _getCloseCaptionFile() async {
    final url = '$baseUrl/api/v1/movies/${widget.id}/subtitle';
    try {
      final data = await http..get(url);
      final srtContent = data.data.toString();
      return SubRipCaptionFile(srtContent);
    } catch (e) {
      print('Failed to get subtitles for ${widget.id}');
      return null;
    }
  }
```

**Comment by skulljuice** [comment]
> It is possible to use a subtitle from an url. You just have to download the file yourself.
> 
> ```
>   Future<ClosedCaptionFile> _getCloseCaptionFile() async {
>     final url = '$baseUrl/api/v1/movies/${widget.id}/subtitle';
>     try {
>       final data = await http.get(url);
>       final srtContent = data.data.toString();
>       return SubRipCaptionFile(srtContent);
>     } catch (e) {
>       print('Failed to get subtitles for ${widget.id}');
>       return null;
>     }
>   }
> ```

A small change;

 final response = await http.get(url);
 final srtContent = response.body.toString();

thanks @vanlooverenkoen . 🙏

**Comment by vanlooverenkoen** [comment]
Ah yes indeed. I am using dio. so for me it is data instead of body my bad

**Comment by skulljuice** [comment]
Cheers 🥂. Yes, this ticket can close now.

**Comment by vanlooverenkoen** [comment]
@pedromassangocode can you close this ticket?

**Comment by pedromassangocode** [comment]
Hi @vanlooverenkoen 
Thanks for your comments.

For future readers, please see https://github.com/flutter/flutter/issues/62318#issuecomment-706374823 for how to download the subtitle using Dio and https://github.com/flutter/flutter/issues/62318#issuecomment-729128708 using http package.
