### ISSUE TITLE
Native Event penetration to Flutter（it is very urgent！！！）

### ISSUE THREAD

**Issue by llywuchen** [flutter/flutter#62310]
Native Event penetration to Flutter！！！
   When I present a IOS Native ViewController on Futter Page use Plugin。In the Native ViewController,I click But the back Fluuter Page in response。 here is the  example code : https://github.com/llywuchen/NativeEventPenetration.git ，please help me!!!!

   In addition. I use `v1.7.8` version,it has no this problem!!!

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.10-pre.1, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)
```

**Comment by pedromassangocode** [comment]
Hi @llywuchen 
Can you please elaborate more what this issue is about?
Thank you

**Comment by llywuchen** [comment]
Hi @pedromassangocode ,can you see and run my demo in https://github.com/llywuchen/NativeEventPenetration.git ,first I added a Native Page on a flutter page,then clicked the NativePage,but the click evnet was captured by the Flutter page。


in flutter demo example :

 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: GestureDetector(behavior: HitTestBehavior.opaque,child: Center(
          child: Text('Running on: $_platformVersion\n'),
        ),onTap: (){
          print("flutter on taped!!!!");///click the native page but this callback responded
          if(!isPresented){
            isPresented = true;
            Demo.presentIOS;     ///add a IOS native page on flutter page
          }
        },),
      ),
    );
  }

in ios plugn :
 public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    if call.method == "presentIOS" {//add native page on flutter
        let vc = UIViewController()
        vc.view.backgroundColor = .red
        UIApplication.shared.keyWindow?.rootViewController?.present(vc, animated: true, completion: nil)
        return
    }
    result("iOS " + UIDevice.current.systemVersion)
  }

steps: run and click flutter page ,then present ios native page,and click the native page,you can see the console print : flutter on taped!!!!

**Comment by pedromassangocode** [comment]
Hi @llywuchen 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose`.
Thank you

**Comment by llywuchen** [comment]
@pedromassangocode Hi,I just wanted to fix this bug on v1.12.13,because all my apps use flutter in this version,and it't in  online deployment。Can you run my demo in v1.12.13,and help me how to fix this problem,is't very urgent.Thank you!

**Comment by VladyslavBondarenko** [comment]
Hi @llywuchen 
does https://github.com/flutter/flutter/issues/35784#issuecomment-516274701 help?

**Comment by llywuchen** [comment]
@VladyslavBondarenko Thank you very much

**Comment by VladyslavBondarenko** [comment]
@llywuchen 
I just found an open duplicate, please follow up on https://github.com/flutter/flutter/issues/14720,
closing current issue
