### ISSUE TITLE
Glide equivalent in flutter

### ISSUE THREAD

**Issue by febinkr** [flutter/flutter#62315]
In my SDK sample app in native android, an image is loaded using Glide library as follows.

```
   private void updateProfilePhoto(BadgeUIEntity badgeUIEntity) {
        String profilePhotoChecksum = badgeUIEntity.profilePhotoChecksum();
        String profilePhotoUrl = badgeUIEntity.profilePhotoUrl();
        if (profilePhotoChecksum != null && !TextUtils.isEmpty(profilePhotoUrl)) {
            try {
                RequestOptions requestOptions = RequestOptions.signatureOf(new ObjectKey(profilePhotoChecksum));
                Glide.with(this)
                        .applyDefaultRequestOptions(requestOptions)
                        .load(profilePhotoUrl).into(ivProfilePhoto);
            } catch (Exception e) {
                Timber.v(e);
            }
        }
    }
```

How can I render the same image in flutter? I have no idea what to do with this checksum in Flutter.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
