### ISSUE TITLE
App building in flutter taking too long

### ISSUE THREAD

**Issue by kevinwawerumwangi** [flutter/flutter#62321]
![Screenshot (456)](https://user-images.githubusercontent.com/57669326/88523938-6702c180-d001-11ea-9564-7b82f08b8410.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi kevinwawerumwangi
It seems that Flutter is downloading the required dependencies for the device you're about to run your Flutter app on. Next time it will be fast.

Closing as invalid issue.

**Comment by kevinwawerumwangi** [comment]
Thank you for the reply
