### ISSUE TITLE
[iOS] platform views inside ListView cannot be clicked

### ISSUE THREAD

**Issue by duanhuangjun** [flutter/flutter#62320]
The Item widget of the ListView in the flutter wraps the nativeView of the player, and the item cannot be clicked

**Comment by duanhuangjun** [comment]
In ios, as long as nativeView is included, there are often unclickable bugs

**Comment by duanhuangjun** [comment]
Can someone help me

**Comment by duanhuangjun** [comment]
I can't put platform views inside ListView. Only on iOS. On Android, it works fine.

**Comment by pedromassangocode** [comment]
Hi @duanhuangjun  
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a [complete reproducible minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example).

Thank you

**Comment by pedromassangocode** [comment]
Maybe related to https://github.com/flutter/flutter/issues/52002

**Comment by duanhuangjun** [comment]
[✓] Flutter (Channel v1.12.13-hotfixes, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/duanhuangjun/Documents/flutter
    • Framework revision f139b11009 (4 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/duanhuangjun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • VOG AL00 • MQS0219726035110 • android-arm64 • Android 10 (API 29)

**Comment by duanhuangjun** [comment]
Stack(
        children: <Widget>[
          Hero(
            tag: Utils.getShortVideoHeroTagFromListToDetail(widget.tagId, widget.shortVideoBean.shortVideoAppDTO.id),
            child: widget.shortVideoBean.isSelectedPlay
                ? Container(
              height: ScreenUtil.screenWidth *
                  ((widget.shortVideoBean.shortVideoAppDTO.mediaHeight /
                      widget.shortVideoBean.shortVideoAppDTO.mediaWidth).clamp(9/16, 1)),
              width: ScreenUtil.screenWidth,
              child: ShortPlayer(
                playList: widget.shortVideoBean.shortPlayList,
                morph: ShortViewMorph.small,
                playCtrShowChanged: (s) => null,
              ),
            )
                : Image.network(
              widget.shortVideoBean.shortVideoAppDTO.cover,
              height: ScreenUtil.screenWidth *
                  ((widget.shortVideoBean.shortVideoAppDTO.mediaHeight /
                      widget.shortVideoBean.shortVideoAppDTO.mediaWidth).clamp(9/16, 1)),
              width: ScreenUtil.screenWidth,
              fit: BoxFit.cover,
            ),
          ),
          Positioned(
              right: dip(10),
              bottom: dip(10),
              width: dip(25),
              height: dip(25),
              child: Visibility(
                visible: widget.shortVideoBean.isSelectedPlay,
                child: InkWell(
                  child: Container(
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(dip(25)),
                        color: Styles.black6),
                    child: Align(
                      alignment: Alignment.center,
                      child: GlobalState.isMuteShortVideoList ? Icon(
                        HPIcons.mute,
                        size: dip(16),
                        color: Colors.white,
                      ): Icon(
                        HPIcons.voice,
                        size: dip(16),
                        color: Colors.white,
                      ),
                    ),
                  ),
                  onTap: (){
                    setState(() {
                      if (GlobalState.isMuteShortVideoList) {
                        GlobalState.isMuteShortVideoList = false;
                        print("VideoItem VideoItem  mute=false");
                        HPPlayer.getInstance().setMute(false);
                      } else {
                        GlobalState.isMuteShortVideoList = true;
                        HPPlayer.getInstance().setMute(true);
                      }

                      UserTrackManger.customClick('Button_Mute', properties: {
                        //点击按钮前的状态
                        'MuteStatus': GlobalState.isMuteShortVideoList ? 'ON':'OFF',
                        'mediaId': widget.shortVideoBean.shortVideoAppDTO.mediaId,
                        'title': widget.shortVideoBean.shortVideoAppDTO.title
                      });

                    });
                  },
                ),
              )
          ),
        ],
      );

**Comment by pedromassangocode** [comment]
Hi @duanhuangjun  
Can you please provide a [complete reproducible minimal code](https://stackoverflow.com/help/minimal-reproducible-example) sample.

Thank you

**Comment by duanhuangjun** [comment]
ScrollViewListener(
          child: CustomScrollView(
            controller: _controller,
            slivers: getListWidget(),
          ),
        ),


Widget getListWidget() {
  return SliverList(
    delegate: SliverChildBuilderDelegate(
      (BuildContext context, int index) {
        return SliverMultiBoxScrollEndListener(
          bottomOverlapCompensation: (ScreenUtil.screenWidth *
              ((shortVideoList[index].shortVideoAppDTO.mediaHeight /
                  shortVideoList[index].shortVideoAppDTO.mediaWidth).clamp(9/16, 1))),
          child: ShortVideoItemWidget(
            shortVideoBean: shortVideoList[index],
            tagId: widget.tagId,
          ),
        );
      },
      childCount: shortVideoList.length,
    ),
  );
}

class ShortVideoItemWidget extends StatefulWidget {

  @override
  Widget build(BuildContext context) {
    return  ShortPlayer(
		…   nativeView
	)

}

**Comment by duanhuangjun** [comment]
The above is my brief code. The Item in my ListView is an nativeView. If I quickly slide on the ios or switch the page and then return to the list page, the phenomenon that the ListView cannot be clicked will appear

**Comment by pedromassangocode** [comment]
Hi @duanhuangjun 
I need a minimal reproducible code that help me copy/paste and run it, I can't do it with the code you provided above. You can create a sample project  that reproduce the issue and provide it as a .zip file or upload it on GitHub.
Thank you.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
