### ISSUE TITLE
Support for fitbit

### ISSUE THREAD

**Issue by edwin-alvarez** [flutter/flutter#62334]
It will be great if flutter can integrate with Fitbit, both flutter and Fitbit are own by Google.

**Comment by TahaTesser** [comment]
Hi @edwin-alvarez 
Since Fitbit doesn't run Android Wear OS but it's own OS, it's not actually suitable for Flutter apps. Do you think otherwise? Could you give some use cases to have flutter support on fitbit?
Thank you

**Comment by prik-k** [comment]
Use cases like for a third party, coach (say) to moniter performance of  an athelete (say). Day-in day-out track records or analysis od effort vs result, calories burnt etc. People might want to have these data in form of an app.

**Comment by TahaTesser** [comment]
@prik-k  @edwin-alvarez 
Fitbit has it own OS and  Flutter probably won't support new OS for wearable 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by elogic2square** [comment]
I am planning to integrate fitbit sdk into flutter application...Do we have any firbit sdk plugin for flutter android application?

**Comment by gcappon** [comment]
Hi all! I developed this package for the purpose:

https://pub.dev/packages/fitbitter

It is still a pre-release but it works pretty well! (of course I'm planning to expand its functionalities).

The code is available here https://github.com/gcappon/fitbitter

You can also check a brief tutorial I made to demonstrate the use of fitbitter to fetch step data from Fitbit:

https://github.com/gcappon/fitbitter/tree/master/example

Enjoy!
