### ISSUE TITLE
Black Screen when using .LayoutParams.FLAG_SECURE with webview_flutter on Android 10 

### ISSUE THREAD

**Issue by Rinkubirwal** [flutter/flutter#62333]
Hi team,

I m facing a problem in webview_flutter when i integrate it on My App. I have to Secure my App from Screen Shot and Recording.
when i added code for this 

<code>
getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);
</code>

After adding this code in MainActivity. The Webview is showing Black Screen. when i remove this code its working fine.

Please help me.

**Comment by TahaTesser** [comment]
Hi @Rinkubirwal 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Rinkubirwal** [comment]
**1. Command flutter doctor -v**
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.19.0-4.3.pre at D:\Flutter SDK
    • Framework revision 8fe7655ed2 (4 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Rinku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • ONEPLUS A5000 • emulator-5554 • android-x86    • Android 7.1.1 (API 25)
    • Web Server    • web-server    • web-javascript • Flutter Tools
    • Chrome        • chrome        • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

**2. Main.dart File**

<code>
import 'package:flutter/material.dart';
import 'package:webview_flutter_plus/webview_flutter_plus.dart';

void main() {
  runApp(WebViewPlusExample());
}

class WebViewPlusExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebViewPlusExampleMainPage(),
    );
  }
}

class WebViewPlusExampleMainPage extends StatefulWidget {
  @override
  _WebViewPlusExampleMainPageState createState() =>
      _WebViewPlusExampleMainPageState();
}

class _WebViewPlusExampleMainPageState
    extends State<WebViewPlusExampleMainPage> {
  WebViewPlusController _controller;
  double _height = 1000;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('webview_flutter_plus Example'),
      ),
      body: ListView(
        children: [
          SizedBox(
            height: 500,
            child: WebViewPlus(
              initialUrl: 'assets/index.html',
              onWebViewCreated: (controller) {
                this._controller = controller;
              },
              onPageFinished: (url) {
                _controller.getHeight().then((double height) {
                  print("Height: " + height.toString());
                  setState(() {
                    _height = height;
                  });
                });
              },
              javascriptMode: JavascriptMode.unrestricted,
            ),
          )
        ],
      ),
    );
  }
}
</code>

**3. MainActivity.kt**

<code>

package com.careervisiongopalganj.yt_video_player

import io.flutter.embedding.android.FlutterActivity
                   
import android.os.Build
import android.view.ViewTreeObserver
import android.view.WindowManager
import android.view.WindowManager.LayoutParams
import android.os.Bundle

class MainActivity: FlutterActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);
        super.onCreate(savedInstanceState)


    }
}


</code>


**5. App Output without**
<code> getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);</code>

![WhatsApp Image 2020-07-28 at 6 07 21 PM](https://user-images.githubusercontent.com/7892304/88666397-a4e51000-d0fd-11ea-8d3f-616534454243.jpeg)




6. App Output with 

<code> getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);</code>

![WhatsApp Image 2020-07-28 at 6 07 21 PM (1)](https://user-images.githubusercontent.com/7892304/88666415-ab738780-d0fd-11ea-884b-2abe2a36cac8.jpeg)



Hi Team when i added FLAG_SECURE in App is Display black screen as above mentioned. please help. waiting for your response

**Comment by TahaTesser** [comment]
Hi @Rinkubirwal 
Not able to reproduce this issue on Galaxy M30 and Oneplus 8 on latest `beta`

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0-7.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision a2bde82fbd (10 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • IN2011 (mobile)  • c9d8ee0c   • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details> 


Can you upgrade to latest beta and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by Rinkubirwal** [comment]
Hi @TahaTesser  

Issue not resolved after doing this. I have to prevent my App from Screenshot and screent recording. help me if any other solution instead of 
<code>
 getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);
</code>

flutter doctor -v


[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.20.0-7.2.pre at D:\Flutter SDK
    • Framework revision a2bde82fbd (10 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Rinku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • CPH1823 (mobile) • 192.168.1.6:5555 • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

**Comment by TahaTesser** [comment]
Hi @Rinkubirwal 
Could you try this using `webview_flutter: ^0.3.22+1` and remove `webview_flutter_plus`, it might be using `webview_flutter` but i just want to confirm the issue on `webview_flutter: ^0.3.22+1` version 

Also please try `getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);` without  using any package. Try different device too please, i cannot reproduce the issue,  this bug could be device specific 
Thank you

**Comment by duythien0912** [comment]
I have similar issue when trying on real device Android 10

**Comment by Joseph-Nathan** [comment]
I have a similar issue when trying on real device running Android 10

**Comment by duythien0912** [comment]
@TahaTesser Please help 🙏

**Comment by Rinkubirwal** [comment]
Hi @TahaTesser  its not working. please help me.

**Comment by TahaTesser** [comment]
Hi @Rinkubirwal   
As mentioned, https://github.com/flutter/flutter/issues/62333#issuecomment-665472331, this issue doesn't reproduce on latest on `webview_flutter: ^0.3.22+1`, jus tried again on Android 10 device  using official [example](https://pub.dev/packages/webview_flutter/example). 

![IMG_0039](https://user-images.githubusercontent.com/48603081/90366934-a2832f80-e085-11ea-8bd4-79ce64d6b08d.jpg)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 7c6f9dd239 (8 days ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!
```

</details> 


If the issue is only reproduce using `webview_flutter_plus`, please create issue on their [GitHub](https://github.com/shah-xad/webview_flutter_plus/issues)

**Comment by TahaTesser** [comment]
@Rinkubirwal 
Already did, https://github.com/flutter/flutter/issues/62333#issuecomment-674701167, there is an example link to the official example and `getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,WindowManager.LayoutParams.FLAG_SECURE);` to MainActiviy

**Comment by prashantspandey** [comment]
This happens on only specific devices such as oppo , vivo etc. , The whole web view turns black when Flag secure is on ?
Any solutions anyone?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
