### ISSUE TITLE
flutter_test_performance interface_change_elapsed_time_ms slight regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62339]
Looks like around revert https://github.com/flutter/flutter/pull/61841.

![Screen Shot 2020-07-27 at 8 29 34 AM](https://user-images.githubusercontent.com/1435716/88560699-52173580-cfe3-11ea-8096-0740ce01b06d.png)

May be a candidate for rebaselining if this revert caused it and the new change that was supposed to land didn't address it.

**Comment by chinmaygarde** [comment]
The linked issue makes sense as being the cause of the change. This is a candidate for re-baselining.

**Comment by kf6gpe** [comment]
Rebaselined; closing.
