### ISSUE TITLE
i couldn't run my flutter project because of this error.

### ISSUE THREAD

**Issue by Natnael3344** [flutter/flutter#62344]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Failed to transform aapt2-3.5.0-5435860-windows.jar (com.android.tools.build:aapt2:3.5.0-5435860) to match attributes {artifactType=_internal-android-aapt2-binary, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for Aapt2Extractor: C:\Users\hp\.gradle\caches\modules-2\files-2.1\com.android.tools.build\aapt2\3.5.0-5435860\e8565f11a238b905299000292dded060de0317ea\aapt2-3.5.0-5435860-windows.jar.
         > java.io.IOException: Unable to delete directory 'C:\Users\hp\.gradle\caches\transforms-2\files-2.1\c0252cf5dde88a33f635b67b7685ae6e'
             Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
             - C:\Users\hp\.gradle\caches\transforms-2\files-2.1\c0252cf5dde88a33f635b67b7685ae6e\aapt2-3.5.0-5435860-windows

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sarthak290** [comment]
run command flutter clean ...
(Please check if you are connected to internet)

and i advice you to change your channel to master using this code flutter channel master ..

and then upgrade your flutter using this code flutter upgrade ...

and try again & let me know :)

**Comment by darshankawar** [comment]
Hi @Natnael3344,
It seems from the error log that the path `C:\Users\hp.gradle` may not be accessible to the resources. Can you try [this](https://stackoverflow.com/a/59658427) possible solution and see if it works for you ?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
