### ISSUE TITLE
Ensure autoroller does not try to roll the engine until all assets built

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#62353]
I believe there is a hard-coded list (in the skia auto-roller source tree) of assets to test on cloud storage before attempting to roll an engine commit -> framework. I don't believe anyone is keeping this list up to date. We should come up with a more robust solution to ensure that an engine commit is fully built before rolling to the framework. For example, on LUCI, we could have a job that waits for/is triggered by all other shards finishing, then writes a text file to cloud storage. This could also be used in the engine recipe to ensure we don't double upload.

**Comment by godofredoc** [comment]
I haven't seen any issues related to this, should we close?

**Comment by christopherfujino** [comment]
it would make sense to add this to tech debt, however I think we will still want some programmatic way to determine all engine builds are finished and uploaded. This would be a hard requirement of scheduling the codesigning build (unless instead codesigning is done per builder, rather than per commit)

**Comment by godofredoc** [comment]
That's the way it will work in the future. The signing process will happen per artifact using metadata embedded on every artifact.

@XilaiZhang this is related to your work to embed signing metadata to the different artifacts.

**Comment by christopherfujino** [comment]
> That's the way it will work in the future. The signing process will happen per artifact using metadata embedded on every artifact.
> 
> @XilaiZhang this is related to your work to embed signing metadata to the different artifacts.

What will be the trigger?

**Comment by godofredoc** [comment]
> > That's the way it will work in the future. The signing process will happen per artifact using metadata embedded on every artifact.
> > @XilaiZhang this is related to your work to embed signing metadata to the different artifacts.
> 
> What will be the trigger?

The last step on the orchestrator recipe when the build is from a release candidate branch. We need to add a new component build -> archive -> test -> sign

**Comment by christopherfujino** [comment]
> > > That's the way it will work in the future. The signing process will happen per artifact using metadata embedded on every artifact.
> > > @XilaiZhang this is related to your work to embed signing metadata to the different artifacts.
> > 
> > 
> > What will be the trigger?
> 
> The last step on the orchestrator recipe when the build is from a release candidate branch. We need to add a new component build -> archive -> test -> sign

cool

**Comment by XilaiZhang** [comment]
> This would be a hard requirement of scheduling the codesigning build (unless instead codesigning is done per builder, rather than per commit)
Yes christopher is right, the signing is done per builder

**Comment by keyonghan** [comment]
Closing as complete.
