### ISSUE TITLE
[windows] Terminate batch job (Y/N)? - Pressing 'N' (for no) is not working

### ISSUE THREAD

**Issue by mrmayurgithub** [flutter/flutter#62357]
## When I use flutter on Vs Code, and try to exit app by pressing Ctrl + C in command line, the option asks us to confirm, but actually it terminates the app whether we give 'n' or 'y' as an input. The app should not be terminated if we give 'n' or 'N' as an input.

**Comment by TahaTesser** [comment]
Same on mac and linux temrinals

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (13 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (4 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!
```

</details>

**Comment by mrmayurgithub** [comment]
> 
> 
> Same on mac and linux terminals
> flutter doctor -v

Do you know how can we solve this issue ?

**Comment by jmagman** [comment]
`Terminate batch job` message is from Windows, @TahaTesser how are you reproducing this on a mac?

**Comment by TahaTesser** [comment]
@jmagman 
i didn't know it was windows specific, pressing `n` doesn't anything on mac and linux,  control + c directly  terminates  the app.

**Comment by stuartmorgan** [comment]
>  The app should not be terminated if we give 'n' or 'N' as an input.

This is a misunderstanding of what this message is. The `flutter` command has a thin `.bat` wrapper on Windows to make it a runnable command; Ctrl-C terminates the Flutter tool's Dart script, as it is supposed to. Then, because it's how the console on Windows works, you get a prompt asking if you want to terminate the enclosing .bat script.

What you answer to the `Terminate batch job` prompt is basically irrelevant, because the `.bat` is just there to run the command that you've already terminated.
