### ISSUE TITLE
Firebase Auth (signInWithEmailAndPassword) Crashes the application

### ISSUE THREAD

**Issue by ritvij-saxena** [flutter/flutter#62360]
In my main.dart I am using a provider widget [StreamProvider.value from Provider package] which streams through auth state and then renders either the login page or the home page depending upon the state.
When I use the email id and password to sign-in

I receive these messages

> >W/DynamiteModule(11337): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(11337): [FirebaseAuth:] Preparing to create service connection to gms implementation
> I/BiChannelGoogleApi(11337): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@cca6679
> W/DynamiteModule(11337): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(11337): [FirebaseAuth:] Preparing to create service connection to gms implementation
> W/GmsClient(11337): IGmsServiceBroker.getService failed
> W/GmsClient(11337): android.os.DeadObjectException
> W/GmsClient(11337): 	at android.os.BinderProxy.transactNative(Native Method)
> W/GmsClient(11337): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/GmsClient(11337): 	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:13)
> W/GmsClient(11337): 	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:244)
> W/GmsClient(11337): 	at com.google.android.gms.common.api.internal.zabo.run(com.google.android.gms:play-services-base@@17.1.0:11)
> W/GmsClient(11337): 	at android.os.Handler.handleCallback(Handler.java:873)
> W/GmsClient(11337): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> W/GmsClient(11337): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
> W/GmsClient(11337): 	at android.os.Looper.loop(Looper.java:193)
> W/GmsClient(11337): 	at android.os.HandlerThread.run(HandlerThread.java:65)
> Lost connection to device.

 or

> W/InputMethodManager(23649): IME died: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
> W/InputMethodManager(23649): android.os.DeadObjectException
> W/InputMethodManager(23649): 	at android.os.BinderProxy.transactNative(Native Method)
> W/InputMethodManager(23649): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/InputMethodManager(23649): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.updateSelection(IInputMethodSession.java:224)
> W/InputMethodManager(23649): 	at android.view.inputmethod.InputMethodManager.updateSelection(InputMethodManager.java:1653)
> W/InputMethodManager(23649): 	at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:150)
> W/InputMethodManager(23649): 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:193)
> W/InputMethodManager(23649): 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:442)
> W/InputMethodManager(23649): 	at io.flutter.plugin.editing.InputConnectionAdaptor.finishComposingText(InputConnectionAdaptor.java:241)
> W/InputMethodManager(23649): 	at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:161)
> W/InputMethodManager(23649): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
> W/InputMethodManager(23649): 	at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:225)
> W/InputMethodManager(23649): 	at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:211)
> W/InputMethodManager(23649): 	at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:588)
> W/InputMethodManager(23649): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1315)
> W/InputMethodManager(23649): 	at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:526)
> W/InputMethodManager(23649): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> W/InputMethodManager(23649): 	at android.os.Looper.loop(Looper.java:193)
> W/InputMethodManager(23649): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> W/InputMethodManager(23649): 	at java.lang.reflect.Method.invoke(Native Method)
> W/InputMethodManager(23649): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> W/InputMethodManager(23649): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> W/GmsClient(23649): IGmsServiceBroker.getService failed
> W/GmsClient(23649): android.os.DeadObjectException
> W/GmsClient(23649): 	at android.os.BinderProxy.transactNative(Native Method)
> W/GmsClient(23649): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/GmsClient(23649): 	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:13)
> W/GmsClient(23649): 	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:244)
> W/GmsClient(23649): 	at com.google.android.gms.common.api.internal.zabo.run(com.google.android.gms:play-services-base@@17.1.0:11)
> W/GmsClient(23649): 	at android.os.Handler.handleCallback(Handler.java:873)
> W/GmsClient(23649): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> W/GmsClient(23649): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
> W/GmsClient(23649): 	at android.os.Looper.loop(Looper.java:193)
> W/GmsClient(23649): 	at android.os.HandlerThread.run(HandlerThread.java:65)
> W/DynamiteModule(23649): Local module descriptor class for com.google.firebase.auth not found.
> I/FirebaseAuth(23649): [FirebaseAuth:] Preparing to create service connection to gms implementation
> W/GmsClient(23649): IGmsServiceBroker.getService failed
> W/GmsClient(23649): android.os.DeadObjectException
> W/GmsClient(23649): 	at android.os.BinderProxy.transactNative(Native Method)
> W/GmsClient(23649): 	at android.os.BinderProxy.transact(Binder.java:1127)
> W/GmsClient(23649): 	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:13)
> W/GmsClient(23649): 	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:244)
> W/GmsClient(23649): 	at com.google.android.gms.common.api.internal.zabo.run(com.google.android.gms:play-services-base@@17.1.0:11)
> W/GmsClient(23649): 	at android.os.Handler.handleCallback(Handler.java:873)
> W/GmsClient(23649): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> W/GmsClient(23649): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
> W/GmsClient(23649): 	at android.os.Looper.loop(Looper.java:193)
> W/GmsClient(23649): 	at android.os.HandlerThread.run(HandlerThread.java:65)
> 

the app has androidx [migration]

**android/build.gradle**

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**android/app/build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "<package-name>" //removed
//        minSdkVersion 16
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
```

**Comment by darshankawar** [comment]
Hi @ritvij-saxena,
This seem to be an issue with `Firebase Auth` plugin which has a separate github repo for tracking these issues.
https://github.com/FirebaseExtended/flutterfire/issues.
Please consider opening this issue there.
Closing, as this isn't an issue with Flutter.
