### ISSUE TITLE
Latest master release seems to ignore --enable-experiment="non-nullable"

### ISSUE THREAD

**Issue by flukejones** [flutter/flutter#62376]
- `1.21.0-1.0.pre` does not have the issue but is missing a couple of fixes I require in dart
- `1.21.0-5.0.pre` has an issue covered in another issue here:

```
Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2 which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
The current Dart SDK version is 2.10.0-0.0.dev.flutter-9dca49e71e.
```
- versions above `1.21.0-5.0.pre` seem to ignore the `--enable-experiment="non-nullable"` so I get many failures in builds.

On my Mac I have `1.21.0-5.0.pre` but with dart `2.9.0`, while all issues above seem to happen with dart `2.10.0`. It's behaving like the args are not being passed to dart vm.

Not using `non-nullable` is not an option for me as I have a 12000 line codebase relying on it, so please don't suggest this as a fix.

**Comment by flukejones** [comment]
Precise details of what works for me on my Mac are:

```
Flutter 1.21.0-5.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision 54c9441723 (10 days ago) • 2020-07-17 18:56:12 -0400
Engine • revision d327828632
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)
```

**Comment by pedromassangocode** [comment]
Hi @creativecreatorormaybenot 
With the current `master` you need the latest SDK version because it was updated. Update `pubspec.yaml` as follow:

```yaml
environment:
  sdk: ">=2.10.0-0.0.dev.flutter-24c7666def <3.0.0"
```


Let me know if this help you.

**Comment by creativecreatorormaybenot** [comment]
@pedromassango I have this same issue, but I think you tagged the wrong user 😄

**Comment by pedromassangocode** [comment]
Thanks, I've updated my comment

**Comment by flukejones** [comment]
@pedromassangocode thank you, this solved the issue here.

I should note that without that change, if I do a regular `flutter channel master` + `flutter upgrade` I get the issue every time.

**Comment by flukejones** [comment]
I will leave it up to your discretion to close the issue.

**Comment by pedromassangocode** [comment]
Hi @flukejones 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by flukejones** [comment]
The issue is now recurring on the update I did today:

```
Flutter is already up to date on channel master
Flutter 1.21.0-6.0.pre.141 • channel master • https://github.com/flutter/flutter.git
Framework • revision c748f1a7aa (2 days ago) • 2020-07-31 17:45:18 -0700
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)
```

as previously, it seems to ignore --enable-experiment="non-nullable"

**Comment by flukejones** [comment]
I'm not able to reopen the issue.

**Comment by pedromassangocode** [comment]
Did you updated your environment version?

**Comment by flukejones** [comment]
I don't recall needing to do this for previous masters. Only since the first time. But yes updating the environment did work - I assumed it would update regardless.

**Comment by pedromassangocode** [comment]
This is an experimental feature and the environment version you want is not stable so since it is not recommended to use, Flutter does not update it for you.

Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it.
Thank you
