### ISSUE TITLE
Videoplayercontrol nested in native Android applications does not work

### ISSUE THREAD

**Issue by hpp1106geek** [flutter/flutter#62371]
I'm trying to integrate video_ Player to native Android through models mode, but the video can not be played, the error is：
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)

**Comment by darshankawar** [comment]
Hi @hpp1106geek,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
