### ISSUE TITLE
Documentation Unclear google_maps_flutter

### ISSUE THREAD

**Issue by mintymac** [flutter/flutter#62370]
https://pub.dev/packages/google_maps_flutter

This: Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.

Should read: Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist, in XCode, file with the key io.flutter.embedded_views_preview and the value YES.    

Or

Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist
<key>io.flutter.embedded_views_preview</key>
<true/>

**Comment by darshankawar** [comment]
Hi @mintymac,
The complete sentence in the document is:

`To use this plugin on iOS` you need to opt-in for the embedded views preview by adding a boolean property to the app's `Info.plist` file, with the key `io.flutter.embedded_views_preview` and the value `YES`.

The prefix `To use this plugin on iOS` seem to be self-explanatory and indicates that you need to add the flag in `info.plist` and pass the value as yes. It doesn't have to be done through Xcode.

**Comment by mintymac** [comment]
Hi @darshankawar .  The value is not YES.  The value is true in info.plist.  Does that make sense to you?

**Comment by darshankawar** [comment]
@mintymac I see, got it now.

The plugin [example](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/example/ios/Runner/Info.plist) shows the flag value as `true`, but the doc shows `YES`.

**Comment by darshankawar** [comment]
@mintymac,
There's already a similar ticket I found, [32097](https://github.com/flutter/flutter/issues/32097) and an open [PR](https://github.com/flutter/plugins/pull/2726) to fix it.
Please follow-up there for updates.
Closing this as duplicate.
