### ISSUE TITLE
[cocoon] ensure the commit exist in the replica before triggering a new prod build

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62375]
The gob replica fetches github data every 15 mins. It could happen that the commit has not been replicated yet when we are retrying a task.

We need to validate the commit exists before triggering a new prod task.

**Comment by godofredoc** [comment]
@CaseyHillers is this still relevant?

**Comment by CaseyHillers** [comment]
Yes. When https://github.com/flutter/flutter/issues/81795 we can close this. Right now, users can retry non-mirrored commits which cause an infra failure.

When Cocoon supports post-submit scheduling of .ci.yaml, I'll add in GoB mirroring updating to decrease the mirror time to under a minute which should fix this.

**Comment by nehalvpatel** [comment]
Just confirming, but looks like this and #100911 can be merged?
