### ISSUE TITLE
better to add flutter version  in pubspects.yaml

### ISSUE THREAD

**Issue by TomerconDevelopers** [flutter/flutter#62382]
Switching flutter version causes many issues in projects, Like external plugins crash, compile error etc..
Steps to reproduce the issue:

Developer 1 created a flutter project using flutter version x.x.x . and left company.
Developer 2 joined the company, and he run the project using flutter version y.y.y. ( Because, He installed this latest version y.y.y.)
and he have no idea about flutter version used by Developer 1.

Now I temporarily solved the issue by using following comment in main.dart file
`// Build with Flutter version 1.19.0-4.1.pre`
But not every developer may not follow same.

So its better , If flutter automatically add flutter version in pubspecs.yaml

**Comment by darshankawar** [comment]
Hi @TomerconDevelopers,
According to the official documentation, you can specify the `flutter version` in `pubspec.yaml` inside `environment` section:

For ex: 

```
environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2
```
This will help all the developers to know what flutter version the project is on. Let me know if this answers your question / request.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
