### ISSUE TITLE
Failed running on iOS simulator!

### ISSUE THREAD

**Issue by Seven163** [flutter/flutter#62390]
Failed to build iOS app
Error output from Xcode build:
↳
    2020-07-28 15:01:58.046 xcodebuild[8899:121867] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2020-07-28 15:01:58.046 xcodebuild[8899:121867] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **
Xcode's output:
↳
    ../../.pub-cache/hosted/pub.flutter-io.cn/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
      void add(String name, value) {
           ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:699:8: Context: This is the overridden method ('add').
      void add(String name, Object value,
           ^
    ../../.pub-cache/hosted/pub.flutter-io.cn/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
      void set(String name, Object value) {
           ^
    org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:708:8: Context: This is the overridden method ('set').
      void set(String name, Object value,
           ^
    ../../.pub-cache/hosted/pub.flutter-io.cn/photo_view-0.2.5/lib/photo_view.dart:279:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
     - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter/packages/flutter/lib/src/painting/image_stream.dart').
     - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter/packages/flutter/lib/src/painting/image_stream.dart').
        stream.addListener(listener);
                           ^
    ../../.pub-cache/hosted/pub.flutter-io.cn/photo_view-0.2.5/lib/photo_view.dart:281:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
     - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter/packages/flutter/lib/src/painting/image_stream.dart').
     - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('../flutter/packages/flutter/lib/src/painting/image_stream.dart').
          stream.removeListener(listener);
                                ^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

![image](https://user-images.githubusercontent.com/14191749/88637025-39df0d80-d0ec-11ea-8126-fe04240e6cb8.png)

Please help check.

**Comment by TahaTesser** [comment]
Hi @Seven163 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Seven163** [comment]
**flutter doctor -v:**
[✓] Flutter (Channel master, 1.21.0-6.0.pre.41, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)
• No issues found!

**flutter run --verbose:**
seems the issue is:
[ +174 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone 11.
[  +10 ms] "flutter run" took 45,393ms.
[  +17 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:596:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:872:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
![image](https://user-images.githubusercontent.com/14191749/88649567-8e898500-d0fa-11ea-82fc-861af355d188.png)

**Comment by TahaTesser** [comment]
Hi @Seven163 
Can you please provide your complete `flutter run --verbose` in txt file and attach it here  and a complete reproducible minimal code sample 
Thank you
