### ISSUE TITLE
FlutterAPP On iPhone 7/7P  crash  When TextField  was editing , maxLength  of TextField was setted

### ISSUE THREAD

**Issue by MasterChanMonkey** [flutter/flutter#62399]
<img width="1134" alt="Screen Shot 2020-07-27 at 3 55 35 PM" src="https://user-images.githubusercontent.com/41544585/88657324-55eea900-d104-11ea-96e6-d9ecf08760d2.png">

**Comment by TahaTesser** [comment]
Hi @MasterChanMonkey 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by bulldriver** [comment]
We met a similar  problem, the difference is that it will appear when we use the Chinese input method.
` flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/Ari/development/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/Ari/Library/Android/sdk
  1 [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
  2     • Flutter version 1.17.5 at /Users/Ari/development/flutter
  3     • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
  4     • Engine revision ee76268252
  5     • Dart version 2.8.4
  6
  7 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
  8     • Android SDK at /Users/Ari/Library/Android/sdk
  9     • Platform android-29, build-tools 29.0.3
 10     • ANDROID_HOME = /Users/Ari/Library/Android/sdk
 11     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
 12     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 13     • All Android licenses accepted.
 14
 15 [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
 16     • Xcode at /Applications/Xcode.app/Contents/Developer
 17     • Xcode 11.6, Build version 11E708
 18     • CocoaPods version 1.9.1
 19
 20 [✓] Android Studio (version 4.0)
 21     • Android Studio at /Applications/Android Studio.app/Contents
 22     • Flutter plugin version 47.1.2
 23     • Dart plugin version 193.7361
 24     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 25
 26 [✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
 27     • IntelliJ at /Applications/IntelliJ IDEA.app
 28     • Flutter plugin version 45.0.2
 29     • Dart plugin version 193.6494.35
 30
 31 [✓] VS Code (version 1.47.2)
 32     • VS Code at /Applications/Visual Studio Code.app/Contents
 33     • Flutter extension version 3.12.2
 34
 35 [!] Connected device
 36     ! No devices available
`

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
