### ISSUE TITLE
Issue with showDatePicker and locale

### ISSUE THREAD

**Issue by MarcusSchilling** [flutter/flutter#62396]
## Steps to Reproduce

```
var birthdayFuture = showDatePicker(context: context,
                initialDate: lastDate,
                firstDate: DateTime(1900),
                lastDate: today,
                initialEntryMode: DatePickerEntryMode.calendar,
                locale: Locale("de", "DE")
            );
```
-> I use the showDatePicker method to show a DatePicker.
I have enabled the Internationalization 
```
    return MaterialApp(
      localizationsDelegates: [
        // ... app-specific localization delegate[s] here
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('de', 'DE'), // English, no country code
        // ... other locales the app supports
      ],
      theme: ThemeData.light(),
      home: Scaffold(
        body: Registration(),
      ),
    );

```
Run the App.

**Expected results:** 
I want to see a DateTimePicker with the german layout. And after I type a point than there should still be the german layout in the TextField Widget.
**Actual results:** 
When the DatePicker opens and the textfield is showed than a keyboard opens with the german layout. 
![flutter_02](https://user-images.githubusercontent.com/6787636/88650778-5289fc00-d0c9-11ea-915f-838aa2808676.png)

When you type "." it doesn't sets a '.' in the textfield but a '/' and formats the date back to english  

![Screenshot_20200728-114626](https://user-images.githubusercontent.com/6787636/88650808-5b7acd80-d0c9-11ea-8a1a-0e46f21a60c6.jpg)

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel master, 1.21.0-5.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-5.0.pre at ...
    • Framework revision d9252f95f9 (7 days ago), 2020-07-21 10:46:04 -0400
    • Engine revision 5a73d4dc25
[    • Dart version 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)]([url]([url](url)))

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/schilling/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Users/schilling/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

...

! Doctor found issues in 1 category.

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @MarcusSchilling 
Just reopened this issue https://github.com/flutter/flutter/issues/55535, it would have been fixed but i can reproduce 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
