### ISSUE TITLE
running pub upgrade error

### ISSUE THREAD

**Issue by orket** [flutter/flutter#62393]

**Comment by orket** [comment]
![image](https://user-images.githubusercontent.com/45196030/88642221-e3aca300-d0c8-11ea-91f3-8d9091b6ec4d.png)

**Comment by pedromassangocode** [comment]
Hi @orket 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
