### ISSUE TITLE
 Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://135.181.35.63:3000/play/pippo/002506727034_01_//STATIC/main.m3u8, null)

### ISSUE THREAD

**Issue by Sukhvsin2** [flutter/flutter#62394]
I am calling stream from an API and passing it to the video player. It was running very smooth yesterday today I got this error.
What should I do?

**Comment by pedromassangocode** [comment]
Hi @Sukhvsin2 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
