### ISSUE TITLE
Implement _embedder.yaml analysis rules

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#624]
Dart 1.14-dev supports _embedder.yaml, which can contain package-local analysis rules.

Flutter has a wrapper around dartanalyzer and modifies the default behavior of analyzer. We'd like the IDE (Atom) experience to have the same analysis rules during editing.

**Comment by sethladd** [comment]
cc @pq

**Comment by pq** [comment]
For reference, the bits we want to replace are [here]( https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart) (formerly `skyanalyzer`).

**Comment by sethladd** [comment]
Some of those lines, yes. :) The script also does work to find the appropriate files to analyze.

We want to ensure that if `flutter analyze` has certain rules turned on/off, that the development experience in Atom has the same rules turned on/off. That way, analysis works the same both on the command line and in the editor.

Thanks!

**Comment by pq** [comment]
Quick update.  Adding `strong-mode` introduces a bunch of errors that `flutter analyze` post processes away.  For example:

```Type check failed: {'/' : (RouteArguments args) => new FlutterDemo()} (Map<dynamic, dynamic>) is not of type Map<String, (RouteArguments) → Widget> because {'/' : (RouteArguments args) => new FlutterDemo()} cannot be typed as Map<String, (RouteArguments) → Widget>lib/main.dart, line 8```

We *should* be able to suppress these by error code but I'm in a conversation with the DDC folks to suss it out.

**Comment by pq** [comment]
Digging a bit deeper, this warning should be suppressible like so:
```
analyzer:
  strong-mode: true
  errors:
    dev_compiler.StaticTypeError: false
```
but something's not right in analyzer-land.

I opened a new bug to track: https://github.com/dart-lang/sdk/issues/25102.

**Comment by pq** [comment]
Turns out https://github.com/dart-lang/sdk/issues/25102 was a red herring.  Error codes are being properly set, it's just that DDC error codes follow a convention that trips up the suppression logic.  Tracking here: https://github.com/dart-lang/sdk/issues/25104.

**Comment by Hixie** [comment]
This bug is about adding to our _embedder.yaml file the relevant flags (as described in https://github.com/dart-lang/sdk/issues/25011) to hide the specific warnings that we're already filtering in the `flutter analyze` command, yes?

Note that `flutter analyze` is pretty specific about some of the warnings it skips. For example, it only skips the "Name non-constant identifiers using lowerCamelCase" warning if the identifier in question (as determined by opening the file mentioned in the error message and examining the exact line and column given) matches the regexp `/_?([A-Z]|_+)\b/`. It also allows per-line silencing of warnings. So we might not be able to entirely solve this just with _embedder.yaml files.

**Comment by sethladd** [comment]
> It also allows per-line silencing of warnings

We want to enable that, too. cc @floitschG is working to help make this happen.

**Comment by pq** [comment]
Me too.  Very much.  There have been a number of threads and issues (I can only find one at the moment, https://github.com/dart-lang/linter/issues/44, but I know there are a few others).

> cc @floitschG is working to help make this happen.

:+1:  What's the plan?

@sethladd or @floitschG? 

cc @bwilkerson FYI.

**Comment by sethladd** [comment]
> What's the plan?

The formal plan is to document all feedback messages, and use those to be able to ignore a certain feedback (e.g., a specific warning by name) in the code.

Is there a Dart SDK bug open for how to ignore a certain feedback at a source location? I'd like to link it here.

**Comment by pq** [comment]
> Is there a Dart SDK bug open for how to ignore a certain feedback at a source location? I'd like to link it here.

https://github.com/dart-lang/sdk/issues/12490

**Comment by eseidelGoogle** [comment]
We'd love to have this, but not in scope for the hackathon.

**Comment by abarth** [comment]
Stealing from @pq because he's gotten all the groundwork in.  I just need to turn the crank here.

**Comment by abarth** [comment]
We now use _embedder.yaml to control the analyzer.

**Comment by floitschG** [comment]
Following up on the "suppres per line" discussion:
The plan is to add error-ids to every possible (static) error/warning in
our Dart tools. Once we have those, we can then add new syntax (most likely
as a comment) to disable warnings.

Work has already started to add these ids, but it's a big task: lots of
warning/errors and our tools have to agree on them.
