### ISSUE TITLE
Cannot use null safety < Dart 2.10.0

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#62405]
With the latest `master`, using any null safety syntax does not work with:

```
analyzer:
  enable-experiment:
    - non-nullable
```

The analyzer says that the SDK constraint needs to be `>=2.10.0` and then `pub get` needs to be run, however, the latest available Dart version is `2.10.0-0.0.dev`.

**Comment by pedromassangocode** [comment]
Hi @creativecreatorormaybenot 
With the current `master` you need the latest SDK version in your `pubspec.yaml`:

```yaml
environment:
  sdk: ">=2.10.0-0.0.dev.flutter-24c7666def <3.0.0"
```

Let me know if this help you.

**Comment by creativecreatorormaybenot** [comment]
@pedromassango I did do that, but id does not help unfortunately 😕

**Comment by creativecreatorormaybenot** [comment]
@pedromassangocode Did work after invalidating caches 👍🏽

**Comment by ollydixon** [comment]
Does this compile to release?

**Comment by ollydixon** [comment]
@creativecreatorormaybenot ```flutter clean``` or something else for invalidating cache?

**Comment by creativecreatorormaybenot** [comment]
@ollydixon It was an IDE problem. Invalidate caches & restart worked for me in AS. There is no real issue here. If you set the SDK constraint correctly, you will not have a problem.

**Comment by ollydixon** [comment]
@creativecreatorormaybenot ah I'm using VSC getting the same issue but there's no cache cause it's extremely lightweight hehe.

**Comment by ollydixon** [comment]
@creativecreatorormaybenot do guys know how close Dart is to releasing this? (Where can I find out hehe)
