### ISSUE TITLE
Flutter fails at Building flutter tool... on ubuntu 20.04

### ISSUE THREAD

**Issue by FirzenYogesh** [flutter/flutter#62411]
## Steps to Reproduce

I used the git repo to install flutter, instead of using the premade files provided in the documentation page.
This seems to be happening on Ubuntu 20.04, however i am using a DigitalOcean Droplet (a new one). It is hosted in India.
I tried on two different new droplets as well with no luck!

I cloned using this
```
git clone https://github.com/flutter/flutter.git -b stable --depth 1
```

I tried it on my macbook, it seems to be working. Could it be on linux only?

## Logs

Logs:

```
/home/code/.development-tools/sdk/flutter/bin/internal/shared.sh: line 153:  8783 Killed                  "$DART" --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.packages" --no-enable-mirrors "$SCRIPT_PATH"
```

`flutter doctor -v` output:

```
Building flutter tool...
```

Note: Tried the same on `beta`, `dev` and `master` as well. 

`stable` and `beta` same results
`dev ` and `master ` seems to be stuck indefinitely

Any help on this is much appreciated.
Thanks!

**Comment by TahaTesser** [comment]
Hi @FirzenYogesh 
Having you tried on local machine with Ubuntu 20.04? this could be virtualisation issue, not sure if Flutter linux is supported on linux virtualisation

**Comment by FirzenYogesh** [comment]
Hi @TahaTesser 
I only have a macbook, so couldn't check.

Also I want it on a remote machine because I take my iPad when I am on the move and I code in that. That's why I am trying to install on a remote machine, also if I install using the premade packs from the documentation site, it works only for that build. When I switch to different channel and run `flutter upgrade` I get the same error.

**Comment by FirzenYogesh** [comment]
It seems, I had insufficient RAM during the building process on my server, I put up a swapfile to solve it.

I am closing this.

**Comment by true-eye** [comment]
> It seems, I had insufficient RAM during the building process on my server, I put up a swapfile to solve it.
> 
> I am closing this.

Could you explain how you put up a swapfile to solve this in details?
