### ISSUE TITLE
dart-sdk issue 

### ISSUE THREAD

**Issue by hamidkhaksari** [flutter/flutter#62410]
## Steps to Reproduce

1. after opening android studio i see a message " Dart SDK is not configured"
2. so i download manually dart-sdk zip file and unzip it to flutter/bin/cache/dart-sdk
3. after that when i open android studio all files from this folder remove it automatic and i don't know why

## Logs

```
```

flutter doctor -v
Downloading Dart SDK from Flutter engine ab5cce503795905db03375bea8759238e4b42a53...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    310      0 --:--:-- --:--:-- --:--:--   310
[/home/hamid/extra/wd/flutter/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/hamid/extra/wd/flutter/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/hamid/extra/wd/flutter/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/hamid/extra/wd/flutter/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by TahaTesser** [comment]
Hi @hamidkhaksari 
If you've flutter setup properly installed then you don't need to download dart sdk separatetely for Android Studio.

You need to add Flutter location then Android Studio will detect both Flutter and Dart SDK from flutter setup 
### Solution
When you see "Dart SDK is not configured", Inside Android Studio -> go to `preferences` -> `languages & framework` on left menu -> Click `flutter` and first option, locate your flutter sdk and then click apply, it will also detect dart sdk at the same time if Flutter sdk is done 

<img width="759" alt="Screenshot 2020-07-28 at 8 32 47 PM" src="https://user-images.githubusercontent.com/48603081/88683655-ac161900-d111-11ea-9e01-071a8b458bac.png">
<img width="744" alt="Screenshot 2020-07-28 at 8 33 31 PM" src="https://user-images.githubusercontent.com/48603081/88683662-ad474600-d111-11ea-8d64-6ea7cd0dcfc6.png">

Hope this helps

**Comment by hamidkhaksari** [comment]
Hi TahaTesser , thanks for the solution but it's not working for me, however my problem solved by a trick.

this is my solution :
1. first i founded flutter looking for this file "dart-sdk-linux-x64.zip" for install dart sdk. so i downloaded this file directly from google.
2. the file name downloaded is "dartsdk-linux-x64-release.zip" so i rename it to "dart-sdk-linux-x64.zip" 
3. then in the terminal typing "flutter run" and dart sdk installed fine.

before do that when i typing flutter run i got many error. 

thank you

**Comment by TahaTesser** [comment]
Hi @hamidkhaksari 
This could because corrupted download file, otherwise, you can solve "Dart SDK is not configured" message Android Studio following my steps given earlier. 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
