### ISSUE TITLE
Changing orientation can result in very delayed drawing of view

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6241]
On a Moto G4, in release mode, we've gotten ourselves into a state when we turn landscape to portrait, we see a mostly blank screen:

Note: nothing looks like an error in our adb logcat output.

![screenshot_20161006-160522](https://cloud.githubusercontent.com/assets/5479/19173806/ea574454-8bde-11e6-8930-533b8ca8866f.png)

Once you tap the screen, the contents are drawn.

(Note: also, when we're in this state, many (most?) taps are not registered.)

**Comment by Hixie** [comment]
I've not seen this recently. I'm going to close this but don't hesitate to reopen if it still happens.
