### ISSUE TITLE
Cocoon agent still has default timeout of 15 minutes

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#62419]
https://github.com/flutter/flutter/pull/36571 removed default timeouts from devicelab tests as part of a larger effort to remove all timeouts from our tests.

Unfortunately, the default timeout [remained in the Cocoon agent](https://github.com/flutter/cocoon/blob/25a5899e829a0e96b0a9c974965a73715366d81d/agent/lib/src/runner.dart#L17-L20):

```dart
/// The default task timeout, if a custom value is not provided.
///
/// This should be the same as `_kDefaultTaskTimeout` defined in https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/framework.dart
const Duration _kDefaultTaskTimeout = const Duration(minutes: 15);
```

We should remove that timeout and have one global (probably 1 hour) test runner timeout

**Comment by tvolkert** [comment]
FYI @Hixie 

@godofredoc after we fix this, we should update all agents ASAP.

**Comment by godofredoc** [comment]
ack, we'll crowdsource the update and update here when it is complete. \cc @digiter

**Comment by Hixie** [comment]
We should still make sure (by policy, not by technical enforcement) that tests generally take less than 5 minutes, and certainly not more than 15 minutes.

**Comment by godofredoc** [comment]
\cc @keyonghan one more metric to track, devicelab tests running for longer than 5 mins.

**Comment by keyonghan** [comment]
Will add to our SLO.

**Comment by tvolkert** [comment]
This has been fixed.  And anecdotally, device lab tests seem more stable already.
