### ISSUE TITLE
Improve tool behavior when a FS operation receives ERROR_ACCESS_DENIED on windows.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#62425]
This error can happen transiently in the presence of antivirus scanning of newly downloaded files. See: https://github.com/flutter/flutter/issues/61997.

Better behavior here can likely be added to the `ErrorHandlingFilesystem` wrapper here:

https://github.com/flutter/flutter/blob/c1e7176d243aa7dd8eadddf32a16a9f68902ec7d/packages/flutter_tools/lib/src/base/error_handling_file_system.dart#L383

Rather than prompt the user in a manner similar to [this](https://en.wikipedia.org/wiki/Abort,_Retry,_Fail%3F), the tool should `throwToolExit` with advice to try again, and if the problem persists, to manually inspect file and directory ownership/permissions.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/ee12d7c3fcc861ec74edf4101ab1b9270f2634a8
