### ISSUE TITLE
The Wiki for flutter/flutter repository is not open for edits by public. 

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [flutter/flutter#62423]

**Comment by jonahwilliams** [comment]
Of course not, if anyone on the internet could edit we would quickly need to contend with trolls and other spam. Unfortunately there is no good way to submit patches directly to the wiki, but edits could be proposed within new issues.

**Comment by Ankur-Khandelwal** [comment]
How to send a Pull Request then to edit the Wiki?

**Comment by rashedmyt** [comment]
@Ankur-Khandelwal Open a issue describing the problem with wiki and someone with access will change it
