### ISSUE TITLE
showTimePicker has unlocalized strings

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#62422]
`flutter_localizations` is present. I set the locale to `Locale('pl')`.

Buttons are localized correctly (_ANULUJ_ and _OK_), but _SELECT TIME_, _ENTER TIME_, _Hour_ and _Minute_ isn't. Icon buttons' tooltips aren't localized too.

![image](https://user-images.githubusercontent.com/4085280/88699054-23927b00-d107-11ea-9f9a-64108995b3fb.png)

```
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.388],
    locale pl-PL)
    • Flutter version 1.21.0-1.0.pre at D:\flutter
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

Code for this bug is available in a small repo I created for this and another bug here: https://github.com/Albert221/flutter_time_picker_issues

**Comment by darshankawar** [comment]
Hi @Albert221,
I tried to replicate the code from your repo on latest Flutter dev channel and on Android 8.1.0 device, but was unable to see the `select time,` enter time`,  `hours`, `mins` on my device. Are there any other settings we need to do to see these texts?

![62422](https://user-images.githubusercontent.com/67046386/88764295-533a9500-d192-11ea-83c4-9ff1acafd1cb.png)

**Comment by Albert221** [comment]
You probably are running an old Flutter dev version, from before the Time Picker redesign. Try upgrading.

**Comment by darshankawar** [comment]
@Albert221, thanks for the tip. I now see the updated `showTimePicker`.
Replicable on latest `dev` and `master` channels. 

<details>
<summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Related [PR](https://github.com/flutter/flutter/pull/60096).
