### ISSUE TITLE
new_gallery__transition_perf worst_frame_rasterizer_time_millis regressed on 07/14 from 300ms to 350ms

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#62447]
See https://flutter-flutter-perf.skia.org/e/?begin=1594278000&end=1595282810&queries=sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery__transition_perf&requestType=0

**Comment by liyuqian** [comment]
CC @kf6gpe

**Comment by chinmaygarde** [comment]
The linked commit is an engine roll. @liyuqian is there any clue on what in the engine roll caused this or is a bisect required?

**Comment by chinmaygarde** [comment]
@liyuqian Marking this as a P0 till we can figure out if this was as a result of a tradeoff or is just a regression. @flar, @zanderso says you have a tool to aid with this analysis.

**Comment by liyuqian** [comment]
This might be caused by a Skia roll that changes what shaders need to be compiled. Our next step should be to bisect those engine commits and see which commit is causing it. I'll try my bisect tool with it. But my tool is still buggy so hopefully we'll also have someone manually bisect it to make sure that we can solve this P0 fast. @jason-simmons : can you please help bisect this manually while I try my tool simultaneously?

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/google/skia/commit/7a96c2a6bb374b36ddf633b529c303e731e7467b

**Comment by liyuqian** [comment]
Thank you @jason-simmons !

@bsalomon @lhkbob @brianosman : is google/skia@7a96c2a expected to have this regression?

**Comment by brianosman** [comment]
Thank you for the heads up. We were aware there might be an impact, but didn't see anything this large in our testing (or from other clients). Regardless, I'm going to revert that CL for now: https://skia-review.googlesource.com/c/skia/+/307782

**Comment by brianosman** [comment]
We'd also like to confirm that the revert is going to fix the problem here. How long will we have to wait to see if there's an improvement?

**Comment by flar** [comment]
@jason-simmons bisected the regression to that specific change, so how much room for doubt is there here?

**Comment by brianosman** [comment]
Sorry: I don't doubt that the CL in question caused the original regression. At the time it landed, we had already added some automatic inlining to the SkSL compiler, which we thought was going to mitigate any real perf impact. Since then, we've made some small changes to the inlining logic, but also to other parts of how shaders are assembled. I just want to be sure that nothing that landed in the meantime prevents us from getting back all the perf we originally lost.

**Comment by flar** [comment]
Perhaps we should trace through whether those additional changes have landed in the framework repo where these benchmarks are run.

The last engine roll into the framework had the skia roll up through a52442ab76f8

**Comment by liyuqian** [comment]
@brianosman : in a nice day the Skia commit should roll all the way to framework within one day and we can see the improvement within several hours. Today isn't very good as we are having multiple issues that are blocking the rollers at multiple levels. I'll do my best to unblock them as the engine sheriff this week, and let you know when your commit finally lands in the framework repo so we can have a look at the number.

**Comment by liyuqian** [comment]
Confirmed the fix by https://github.com/flutter/flutter/pull/62925 as shown below
![image](https://user-images.githubusercontent.com/22987568/89371357-fc542480-d697-11ea-9e4d-a3053280199c.png)
