### ISSUE TITLE
Document the operation of canvas.drawAtlas() and canvas.drawRawAtlas()

### ISSUE THREAD

**Issue by flar** [flutter/flutter#62450]
These methods have minimal documentation that basically only describes the types of the parameters and the scenario in which the method would be useful, but no information on how the parameters are used to render the atlas.

A description of how the lists of `Rect` and `RSTransform` objects are applied to render (parts of) the atlas to the destination would be helpful, as well as an example.

**Comment by zanderso** [comment]
@flar Assigning you because it sounds like you have become the expert on this call.

**Comment by flar** [comment]
fixed in https://github.com/flutter/engine/pull/20176
