### ISSUE TITLE
Overlay's OverlayEntry's contexts are not children of Overlay's context.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6245]
This prevents the OverlayEntry from reaching up into the parent of the Overlay to get inherited widgets.

**Comment by Hixie** [comment]
Do you mean the context passed to an OverlayEntry's build function?

**Comment by abarth** [comment]
From reading the code it looks like they are....

**Comment by abarth** [comment]
I'll add a test that shows it.

**Comment by Hixie** [comment]
@apwilson Please reopen this if you can explain in more detail what you meant.
