### ISSUE TITLE
Accessing gallery using flutter_webview

### ISSUE THREAD

**Issue by Deena1999** [flutter/flutter#62466]
Can uploading from gallery can be done using flutter webview.Have implemented webview and converted a website to an app,but where not able to acccess the gallery upon pressing the upload button available in the website.Have added the read/write external storage permissions in manifest.xml

**Comment by pedromassangocode** [comment]
Hi @Deena1999 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal [complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by Deena1999** [comment]
Hi,@pedromassangocode
**Response for flutter doctor -v:**
      Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E266, locale
    en-IN)
    • Flutter version 1.18.0-11.1.pre at
      /Users/saravavenkatasalam/Desktop/flutter
    • Framework revision 2738a1148b (3 months ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/saravavenkatasalam/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @Deena1999 
Can you please provide a minimal [complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample so that I can reproduce the issue.
Thank you

**Comment by Deena1999** [comment]
Hi,@pedromassangocode

**This is the main.dart file**

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:permission_handler/permission_handler.dart';
void main() async{
  WidgetsFlutterBinding.ensureInitialized();
    await Permission.camera.request();
    await Permission.storage.request();
    runApp(MyApp());}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Udhyog'),
        ),
        body: WebView(
          initialUrl: "https://udhyog.xyz",
          javascriptMode: JavascriptMode.unrestricted,
        )
      ),
    );
  }
}

Have also added the permission_handler and webview_flutter plugins in pubspec.yaml

**Comment by pedromassangocode** [comment]
Hi @Deena1999 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/27924).

Consider this comment to workaround this issue https://github.com/flutter/flutter/issues/27924#issuecomment-532268306

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
