### ISSUE TITLE
Material date picker is not fully focusable with a keyboard

### ISSUE THREAD

**Issue by gmoraja** [flutter/flutter#62460]
@goderbauer
@gspencergoog

Following up on issue https://github.com/flutter/flutter/issues/49809

When using a keyboard, the focus doesn't move out of the "minutes" field. Using the Tab key creates extra space inside the field, instead of moving the focus to the next element. If needed, I can upload a video to show the behavior.

**Comment by darrenaustin** [comment]
This sounds like it will be fixed with #47156. I will close this as a duplicate. Please reopen if this is not solved when a fix for #47156 lands.
