### ISSUE TITLE
iOS Text field textSelectionHandleColor is not correct

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#62479]
iOS Text field textSelectionHandleColor is not correct

My theme config contains this:

```
    cursorColor: ThemeColors.accent,
    textSelectionHandleColor: ThemeColors.accent,
    textSelectionColor: ThemeColors.accent.withOpacity(0.4),
```
But still my iOS text field textSelectionHandleColor is blue.

![image](https://user-images.githubusercontent.com/21172855/88777640-ba068100-d187-11ea-9414-96ac0a313e3f.png)

Latest Flutter verions: 1.17.5
No Warnings

**Comment by TahaTesser** [comment]
Hi @vanlooverenkoen 
I can reproduce the issue 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/43887
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
