### ISSUE TITLE
[Flutter-Driver]: driver.getText is not supporting RichText widget properly

### ISSUE THREAD

**Issue by GarimaVats** [flutter/flutter#62489]
## 
I am trying to fetch text from RichText widget with driver.getText function on . I am using get text as below :
    expect(await world.driver.getText(find.byValueKey(widgetkey)), searchtext);

We are writing RichText code like below example:
   _text = RichText(
   key: WidgetKeys.XYZScreenText,
   text: TextSpan(
    children: [
   TextSpan(
  text: translate(context, StringKeys.xyzInfoText1),
  style: appTextTheme(context)
 .bodyText2
 .apply(color: AMBColors.bodyText)),
 TextSpan(
 text: translate(context, StringKeys.xyzInfoText2),
 style:
 TextStyles.body2Bold.apply(color: AMBColors.bodyText)),
 ],
 ),
 );

I tried it on master as well as stable flutter channel. But still I am facing exception 
   Exception: DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported    operation: Type RichText is currently not supported by getText

<img width="1184" alt="Screenshot 2020-07-29 at 1 03 05 PM" src="https://user-images.githubusercontent.com/33538185/88793683-d53eb400-d1ba-11ea-8035-da20709b9f79.png">

**Comment by aditi-malik** [comment]
Is there any update on this issue? @GarimaVats, did you find any workaround?

**Comment by GarimaVats** [comment]
Not yet @aditi-malik

**Comment by darshankawar** [comment]
Per [this](https://github.com/flutter/flutter/pull/48809#issuecomment-665586713) comment, the OP's implementation is not yet supported.
