### ISSUE TITLE
gemfile json dependency needs to be updated...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62497]
Github has noted that there's a potential vulnerability with json 2.3.0, and we should update to 2.3.1.

See the proposed PR, and approve if it's reasonable.

https://github.com/flutter/flutter/pull/62378.

cc @godofredoc @pcsosinski

**Comment by pcsosinski** [comment]
ping - what's the status on this?

**Comment by christopherfujino** [comment]
> ping - what's the status on this?



> ping - what's the status on this?

update is i've been spending all day trying to get https://github.com/flutter/flutter/pull/62987 to pass cirrus...
