### ISSUE TITLE
Infra failures on LUCI don't seem to create red checks on GitHub

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#62503]
Even though the tip of the engine tree was purple (infrastructure failure), this PR https://github.com/flutter/engine/pull/20110 was landed by the auto-roller.

**Comment by godofredoc** [comment]
I checked all the LUCI builders and they are all green. We need to verify the wait-for-tree-to-go-green and the build tree status.

The assumption is that tree status bot is not taking the luci check status as input.

**Comment by godofredoc** [comment]
The handlers are creating the status with no errors but they engine-status check does not show up in the github ui. Here is an example:

![image](https://user-images.githubusercontent.com/54371434/88864405-f6eb6b80-d1b9-11ea-9818-76ea832d1214.png)

**Comment by godofredoc** [comment]
The problem may be related to the flutter-dashboard using app-authentication instead of token authentication and the app-auth not having permissions to the status api.

**Comment by godofredoc** [comment]
luci-engine status was not being added because flutter-dashboard didn't have permissions to write to the status API. Permissions were updated and the luci-engine is being added again.

![image](https://user-images.githubusercontent.com/54371434/88988390-a5141580-d28d-11ea-8d00-b4d670eef9f3.png)
