### ISSUE TITLE
we should push people off the alpha branch

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6250]
either by having a bot proactively check any green build to alpha, or by having the tool autoupdate you to master if you're on alpha when it does its first run.

**Comment by abarth** [comment]
We already do this in `flutter upgrade` but we should do it in `run` and other commands, possibly with a permission prompt.

**Comment by Hixie** [comment]
What we could do is treat this as a special case of the "you're out of date" warning.

Any time the current branch is not a preferred branch, or any time the current branch is more than 3 weeks old and there has been a more recent checkin on that branch, on startup, display the message "This flutter installation is 4 weeks out of date. To update, run flutter update. To silence this warning, run flutter config --no-out-of-date-warning."

**Comment by eseidelGoogle** [comment]
I believe we did this?  I don't see any alpha-specific commits on that branch, so maybe we didn't yet?

**Comment by eseidelGoogle** [comment]
We had 19 sessions today alone from the alpha branch. :/  I guess we do need this!?

**Comment by eseidelGoogle** [comment]
Our alpha branch is alive an well.  Closing. :)
