### ISSUE TITLE
Flutter maps doesn't load on release mode

### ISSUE THREAD

**Issue by dhs9004** [flutter/flutter#62506]
Hi,

Flutter maps isn't loading on android when it is released for google play, on debug it works perfectly.

I'm using VSCode with flute version 1.20.0-7.2.pre
google_maps_flutter: ^0.5.28+1

flutter build appbundle --release
- Running Gradle task 'bundleRelease'...
- Note: Some input files use unchecked or unsafe operations.
- Note: Recompile with -Xlint:unchecked for details.
- Removed unused resources: Binary resource data reduced from 383KB to 193KB: Removed 49%
- Running Gradle task 'bundleRelease'...
- Running Gradle task 'bundleRelease'... Done                       195.7s (!)
- √ Built build\app\outputs\bundle\release\app-release.aab (22.7MB).

Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-CA)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (2 available)

• No issues found!

Note: If I build the appbundle on VSCode and then rebuild it on Android studio the release works.
Any comment on this will more than appreciate,

Thanks,

**Comment by darshankawar** [comment]
Hi @dhs9004,
Do you have the SHA-1 created for the api key for release version of the plugin ?
See [this](https://github.com/flutter/flutter/issues/28133#issuecomment-465233684) comment from the ticket and check if it works for you.
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ViniciusDS** [comment]
O have the same problem.

Logs flutter doctor:

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.14.6 18G103 x86_64, locale en-BR)
    • Flutter version 1.23.0-18.1.pre at /Users/viniciusds/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/viniciusds/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Z2 Plus (mobile)           • 3a7bb8cb                             • android-arm64 • Android 10 (API 29)
    • LM G810 (mobile)           • LMG810EAW                    • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 7F7C176D-573D-438A-846B-64D5EA902218 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
