### ISSUE TITLE
Need a tool to bisect noisy tests/benchmarks against both framework and engine commits

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#62504]
The tool should
- provide clear signals even if the benchmark is very noisy. The noise may make the bisect process longer, but should never make the final signal less confident.
- be able to handle the engine build and the `--local-engine` flag to bisect engine commits in addition to framework commits.
- be able to run on the device lab in case a regression is only reproducible there.
- be able to retry flaky and failed test runs, or count the flaky/failed rate to bisect when it becomes flaky.
- not require any human intervention during the bisection as it may take hours to finish a bisection for very noisy and lengthy benchmarks.

I'm currently working on it in spare time. This should help
- https://github.com/flutter/flutter/issues/60210
- https://github.com/flutter/flutter/issues/58248
- https://github.com/flutter/flutter/issues/50570
- https://github.com/flutter/flutter/issues/60559

**Comment by yusuf-goog** [comment]
closing as obsolete.
