### ISSUE TITLE
When retrying flaky tests we should require multiple passes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#62517]
One of our biggest velocity-harming problems is that we have some failing tests that sometimes pass, and when people see such a test fail, rather than fix it, they retry the test.

The result is that if a test fails to fail, we treat it as an eventually passing test.

To avoid this problem, I propose that when a test fails, we ping a central server to mark the test as having failed, and the next time the test runs, if it has been marked as failing recently, we require that it passes N times in a row to count as a pass, rather than only once. As part of this we can also remove the current retry logic in cocoon: the goal now is not to run the test until it passes, but to run the test until it fails, so we don't need to run a test twice it fails the first time.

I'm not sure how to compute N. I think a simple solution would be to set N to 1 if the test has never failed in the last week, and 10 if it's failed at all in the last week.

cc @tvolkert @godofredoc

**Comment by godofredoc** [comment]
Can we just remove the retries? or limiting to 2 or 3?

**Comment by Hixie** [comment]
Well the idea here is the reverse, the idea is to retry when a test has passed, _if_ it has ever failed in the past few weeks.

**Comment by Hixie** [comment]
Maybe this doesn't work because at the regression point the test won't have failed recently (so we don't retry it), and also a regression is likely to be something like GC timing being different causing a race condition to fail differently, but not in a way that is actually related to the actual commit that causes the failure.
