### ISSUE TITLE
tool should warn when users are out of date

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6251]
If the flutter checkout that people are using is more than a week old, if there is a newer checkin on the selected branch, we should display a message whenever the tool starts up saying so. Maybe only do this once per day or something.

```
Your flutter installation is 3 weeks old. To update to the latest version, run flutter update.
```

**Comment by eseidelGoogle** [comment]
@danrubel

**Comment by sethladd** [comment]
This feels very in-scope for M2.

**Comment by johnmccutchan** [comment]
We need to hit the network and fetch from the remote repository. I'm worried about doing that without having the user prompt us- unexpected network access can be expensive and unappreciated.

What about a doctor check?

**Comment by eseidelGoogle** [comment]
I suspect paid-network users are not one of the user cases we're targeting yet.  We have a ton of other bad bugs for such already (e.g. https://github.com/flutter/flutter/issues/7300).  I suspect once we have the code to check we can place it wherever you or others think makes sense. :D  Thanks for looking!

**Comment by Hixie** [comment]
I think it would be fine to implement this as follows:

* If the branch is more than one month old:
  * If it's been more than a month since we did a `git fetch`:
    * Do a `git fetch`.
  * Then, if there is a never commit on this branch:
    * Briefly inform the user that this branch may be old, and to consider `flutter upgrade`.

**Comment by Hixie** [comment]
Oh and `flutter doctor` should just always do a `git fetch` and check if it's the latest checkin on its branch.
