### ISSUE TITLE
Show error message in app when ptrace is not permitted on iOS 14 instead of crashing

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#62518]
On iOS 14 execution of JIT fails when the debugger is not attached, and debug Flutter apps (including host add-to-app applications) [crash on launch](https://github.com/flutter/flutter/issues/60657) when manually launched from the home screen on a physical device.

Instead of crashing, give the user a message with a link to documentation.

Suggestion from @chinmaygarde in JIT crash discussion doc: 
> We could toss up a UI built with UIKit that shows why the app failed to launch as well as the workaround and a link to other documentation.

Suggestion from @mraleph:
> I think instead of just showing a warning into the log we should be showing message box explaining that Flutter application built in debug mode can only be launched through `flutter run`.

https://github.com/flutter/flutter/issues/60657#issuecomment-664623229

**Comment by jmagman** [comment]
Detection of issue is at:
https://github.com/flutter/engine/blob/b955e15ee9c5a8b15664aabb576e01c1233293ad/runtime/ptrace_ios.cc#L65-L69

**Comment by Hixie** [comment]
Why can't we run debug applications from the launch screen anymore on iOS 14? That seems like a serious regression for many workflows. (I've seen countless people work on their apps, then unplug and head to dinner and then demo their app at dinner without having planned for doing so, relying on whatever debug build was there.)

**Comment by jmagman** [comment]
@Hixie see https://github.com/flutter/flutter/issues/60657#issuecomment-664620215, there's a lot more details in that issue.
