### ISSUE TITLE
find error at 'AssetBundleImageProvider' when compile app

### ISSUE THREAD

**Issue by kamaludin21** [flutter/flutter#62530]
Hi guys, i found this error when compile my app, can help me?

```
Compiler message:
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:672:7: Error: The getter 'erethrow' isn't defined for the class 'AssetBundleImageProvider'.
 - 'AssetBundleImageProvider' is from 'package:flutter/src/painting/image_provider.dart' ('/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'erethrow'.
      erethrow;
      ^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

**Comment by darshankawar** [comment]
Hi @kamaludin21,
`erethrow` sounds like a typo. Can you try [this](https://stackoverflow.com/questions/62744055/when-i-run-the-emulator-shows-compiler-error) solution and see if it works for you ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
