### ISSUE TITLE
[WebView doesn't support on MacOS App]Unsupported operation: Trying to use the default webview implementation for TargetPlatform.macOS but there isn't a default one

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#62546]
I saw some issues regarding WebView, some guys mentioned that WebView is not currently supportive on MacOS app and Web app. Is it right?

If yes, I wonder when WebView will be supported by MacOS and Web app. 

Do you have an alternative solution to this, such as recommendation of other packages. Thanks.

![image](https://user-images.githubusercontent.com/1920873/88880940-9e22de00-d260-11ea-8ca0-99270f4e510c.png)

**Comment by darshankawar** [comment]
Hi @jims57,
There's a similar open issue describing your case, [41725](https://github.com/flutter/flutter/issues/41725).
Please follow-up there for updates.
Closing this as duplicate.
