### ISSUE TITLE
 LUCI bots Building flutter tools is failing Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2 which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#62541]
The current Dart SDK version is 2.10.0-0.0.dev.flutter-a3815b6590.

Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2 which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Resolving dependencies...
The current Dart SDK version is 2.10.0-0.0.dev.flutter-a3815b6590.

https://cirrus-ci.com/task/5090607431417856?command=setup#L444

**Comment by xu-baolin** [comment]
I think there are some problems with our CI stability, we often need to rerun to pass, especially the flutter-build tree, which is often closed.

**Comment by xu-baolin** [comment]
After synchronizing the forked branch and the upstream master, the problem is solved

**Comment by Vickycp** [comment]
A quick git pull and then any flutter command such as flutter -h does downloads a valid dart SDK (2.9.0-edge.a3815b659047cfc6b63d41d180aa1ca1b781ee68).

**Comment by benedicte69** [comment]
> A quick git pull and then any flutter command such as flutter -h does downloads a valid dart SDK (2.9.0-edge.a3815b659047cfc6b63d41d180aa1ca1b781ee68).

Thank you @Vickycp
