### ISSUE TITLE
[share] add timeout to opening share dialog, tapping multiples times opens multi share dialogs 

### ISSUE THREAD

**Issue by nguyenthehoang** [flutter/flutter#62548]
About this plugin: https://pub.dev/packages/share
I put action share in a RaisedButton like this
```
RaisedButton(
  onPressed: () async {
    await Share.share('shareMessage');
  },
  child: Text('Share'),
),
```
But button can tap multi-times and it will open so many share box. Can I handle to open one box ?
Has anyone faced this problem, please help me. Thank you so much
![Screenshot_20200730-115338](https://user-images.githubusercontent.com/34738382/88882136-7b41fb00-d25b-11ea-88b8-8dfaa2f7519c.png)

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () async {
            await Share.share('shareMessage');
          },
          child: Text('Share'),
        ),
      ),
    );
  }
}

``` 

</details>

**Comment by Zazo032** [comment]
I don't think this is a problem with Flutter, this also happens on native apps, so it's probably a problem with Android itself.

**Comment by TahaTesser** [comment]
@Zazo032 
I was thinking maybe timeout could  help here or do you think it's better to match native behaviour?

**Comment by Zazo032** [comment]
Maybe a timeout would help fixing this, but I think matching native behaviour is not the best solution here, as native is not working as it should.

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
