### ISSUE TITLE
Is there any way to write file to SD card from flutter app?

### ISSUE THREAD

**Issue by ZhFahim** [flutter/flutter#62555]
Would you please tell me is there any way to write file to SD card from flutter app? I am currently writing an app that should have a feature about modify files of SD card (removable storage). But I couldn't figure out any way to implement this feature.

**Comment by darshankawar** [comment]
Hi @ZhFahim,
There's a similar open issue describing your case and I see that you've commented there, [40504](https://github.com/flutter/flutter/issues/40504).
Please follow-up there for updates.
Closing this as duplicate.
