### ISSUE TITLE
[Slider] Thumb's center doesn't align with division's center

### ISSUE THREAD

**Issue by hariom08** [flutter/flutter#62567]
I'm trying to create a custom slider like the one below :

![photo6109691975172205113](https://user-images.githubusercontent.com/28510722/88901733-cb768880-d26e-11ea-9ff5-b6717142f176.jpg)

For that, I created 2 custom classes from SliderComponentShape and SliderTickMarkShape for the Slider's Thumb and the Slider divisions. In both the class, I was just fiddling around the paint object and radius to create the custom shape for my division and my thumb, and there is nothing fancy. 
But the problem is, except the center position in the slider, the thumb doesn't get aligned to any other division's center.
I've posted this problem in the StackOverflow [here](https://stackoverflow.com/questions/63051155/custom-discreet-slider-problem-in-aligning-the-thumb-to-the-divisions-center) and explained this very clearly with all the needed codes.

The question is: Shouldn't the thumb's center get naturally aligned to the division's center in all its positions? Or am I missing something?

**Comment by HansMuller** [comment]
CC @clocksmith @JoseAlba

**Comment by TahaTesser** [comment]
This is reproducible in a new duplicae of https://github.com/flutter/flutter/issues/108007

**Comment by TahaTesser** [comment]
This is blocking https://github.com/flutter/flutter/pull/147783

I'm fixing this bug to unblock the PR.

### Before

https://github.com/flutter/flutter/assets/48603081/84bf229e-c270-435a-b52b-8f2b55559dcc

### After

https://github.com/flutter/flutter/assets/48603081/d6ae6082-6e30-41a1-8a6f-8af5fe63376c
