### ISSUE TITLE
The named parameter 'vsync' isn't defined.

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#62574]
I am on the master channel.

Since animations got migrated to nnbd I get this error: `The named parameter 'vsync' isn't defined.`

The application itself compiles and everything is working, but I get this error in my IDE. I think it has something to do with `@required` which now is only `required`. 

How do I get rid of this error?

**Comment by lazylazyllama** [comment]
Restarting the IDE fixed the issue.

**Comment by ryanhz** [comment]
@lazylazyllama  What has changed for required named parameters?
from annotation `@required` to keyword `required` ?

**Comment by efraespada** [comment]
@ryanhz is right.
I just changed in `animation_controller.dart`
```dart
    required TickerProvider vsync,
```
to
```dart
    @required TickerProvider vsync,
```
and solved.

It seems an error.

@lazylazyllama restarting the IDE doesn't fix it. Please reopen the issue.

**Comment by efraespada** [comment]
> @ryanhz is right.
> I just changed in `animation_controller.dart`
> 
> ```dart
>     required TickerProvider vsync,
> ```
> 
> to
> 
> ```dart
>     @required TickerProvider vsync,
> ```
> 
> and solved.
> 
> It seems an error.
> 
> @lazylazyllama restarting the IDE doesn't fix it. Please reopen the issue.

Adding `@` only removes the Dart error. It doesn't work at compilation time.

**Comment by lazylazyllama** [comment]
```yaml
environment:
  sdk: ">=2.10.0-1.0.dev <3.0.0"
```

fixed it for me

**Comment by svonidze** [comment]
I moved Flutter SDK to another location, even I updated patches in the code I got a bunch of problems, one of them was exactly what described here for AnimationController.

The reason became hidden in the Android Studio config, somehow the FlutterSDK path became blank, so I have to reconfigure the FlutterSDK path in Android Studio: Go to Setting -> Language & Frameworks -> Flutter and set the path to Flutter SDK

**Comment by thisisgit** [comment]
Just FYI, I asked for the difference between `required` & `@required` and the answer is that they're the same thing. 
Refer to this comment: https://github.com/flutter/flutter/pull/62485#issuecomment-671555967

cc @ryanhz

**Comment by ryanhz** [comment]
@thisisgit Thanks for letting me know

**Comment by eseidel** [comment]
I also just hit this.  Restarting VSC seemed to fix it (I also changed the pubspec to be >2.9.0). Presumably the Analyzer got confused?

**Comment by huytower** [comment]
After I updated code as

in the file `pubspec.yaml`
`environment:
  sdk: ">=2.9.0 <3.0.0"`

then `pub get`

then restart IDE

This error has gone.

**Comment by garshom** [comment]
run `flutter clean` and restart IDE

**Comment by cletusajibade** [comment]
> run `flutter clean` and restart IDE

This worked for me.

**Comment by dpkswn4** [comment]
> run `flutter clean` and restart IDE

Worked for me as well.

**Comment by HassanDarwish** [comment]
it does work for me i have did
environment:
  sdk: ">=2.9.0<3.0.0"
and
 this.animationBehavior = AnimationBehavior.normal,
    @required TickerProvider vsync,

pub get
flutter clean
restart  android studio 
nothing work
please open it for me

**Comment by flutterq** [comment]
All Possible Solution Added Here[ [Solved] AnimationController The named parameter ‘vsync’ isn’t defined](https://fluttercorner.com/solved-animationcontroller-the-named-parameter-vsync-isnt-defined/)
