### ISSUE TITLE
Strange behavior of the toStringAsFixed method

### ISSUE THREAD

**Issue by RusKryzhanovskiy** [flutter/flutter#62576]
I noticed that the double.toStringAsFixed(2) method incorrectly rounds up numbers. 

The number with the fractional part `.975` after rounding is rounded to a large value `.98` if the integer part is between 1 and 3 or 16 and 63 inclusive. In other cases, the rounding goes to a lower value `.97`.

You can reproduse it by writing and executing the following code: 

```dart
for (var i = 0; i < 80; i++) {
      var value = i + 0.975;
      print('$value => ${value.toStringAsFixed(2)}');
}
```

<details>
  <summary>output</summary>

    flutter: 0.975 => 0.97
    flutter: 1.975 => 1.98
    flutter: 2.975 => 2.98
    flutter: 3.975 => 3.98
    flutter: 4.975 => 4.97
    flutter: 5.975 => 5.97
    flutter: 6.975 => 6.97
    flutter: 7.975 => 7.97
    flutter: 8.975 => 8.97
    flutter: 9.975 => 9.97
    flutter: 10.975 => 10.97
    flutter: 11.975 => 11.97
    flutter: 12.975 => 12.97
    flutter: 13.975 => 13.97
    flutter: 14.975 => 14.97
    flutter: 15.975 => 15.97
    flutter: 16.975 => 16.98
    flutter: 17.975 => 17.98
    flutter: 18.975 => 18.98
    flutter: 19.975 => 19.98
    flutter: 20.975 => 20.98
    flutter: 21.975 => 21.98
    flutter: 22.975 => 22.98
    flutter: 23.975 => 23.98
    flutter: 24.975 => 24.98
    flutter: 25.975 => 25.98
    flutter: 26.975 => 26.98
    flutter: 27.975 => 27.98
    flutter: 28.975 => 28.98
    flutter: 29.975 => 29.98
    flutter: 30.975 => 30.98
    flutter: 31.975 => 31.98
    flutter: 32.975 => 32.98
    flutter: 33.975 => 33.98
    flutter: 34.975 => 34.98
    flutter: 35.975 => 35.98
    flutter: 36.975 => 36.98
    flutter: 37.975 => 37.98
    flutter: 38.975 => 38.98
    flutter: 39.975 => 39.98
    flutter: 40.975 => 40.98
    flutter: 41.975 => 41.98
    flutter: 42.975 => 42.98
    flutter: 43.975 => 43.98
    flutter: 44.975 => 44.98
    flutter: 45.975 => 45.98
    flutter: 46.975 => 46.98
    flutter: 47.975 => 47.98
    flutter: 48.975 => 48.98
    flutter: 49.975 => 49.98
    flutter: 50.975 => 50.98
    flutter: 51.975 => 51.98
    flutter: 52.975 => 52.98
    flutter: 53.975 => 53.98
    flutter: 54.975 => 54.98
    flutter: 55.975 => 55.98
    flutter: 56.975 => 56.98
    flutter: 57.975 => 57.98
    flutter: 58.975 => 58.98
    flutter: 59.975 => 59.98
    flutter: 60.975 => 60.98
    flutter: 61.975 => 61.98
    flutter: 62.975 => 62.98
    flutter: 63.975 => 63.98
    flutter: 64.975 => 64.97
    flutter: 65.975 => 65.97
    flutter: 66.975 => 66.97
    flutter: 67.975 => 67.97
    flutter: 68.975 => 68.97
    flutter: 69.975 => 69.97
    flutter: 70.975 => 70.97
    flutter: 71.975 => 71.97
    flutter: 72.975 => 72.97
    flutter: 73.975 => 73.97
    flutter: 74.975 => 74.97
    flutter: 75.975 => 75.97
    flutter: 76.975 => 76.97
    flutter: 77.975 => 77.97
    flutter: 78.975 => 78.97
    flutter: 79.975 => 79.97
</details>

<details>
  <summary>flutter doctor</summary>

    [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB) 
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    [✓] Android Studio (version 4.0)
    [✓] Connected device (1 available)

    • No issues found!
</details>

**Comment by stuartmorgan** [comment]
In the future, please file Dart bugs in the Dart repository, rather than the Flutter repository.

However, this is not a bug. Most of those numbers aren't exactly representable as doubles, which is why the rounding varies. Try a large value, like `toStringAsFixed(15)`, to see why.
