### ISSUE TITLE
Error -32601 received from application: Method not found

### ISSUE THREAD

**Issue by saagarch** [flutter/flutter#62584]
I updated flutter today to 1.17.5 and now I'm seeing this "Error -32601 received from application: Method not found" while debugging. I don't know what's the problem, everything is normal except the debug console and no changes appearing in mobile device after this error appears. Any help?

**Comment by darshankawar** [comment]
Hi @saagarch,
Can you try running `flutter pub cache repair` and then `flutter run` to see if it works for you ?
If problem persists, provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
