### ISSUE TITLE
adb.exe: error: cannot bind listener: cannot listen on socket: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)

### ISSUE THREAD

**Issue by harshmahalka** [flutter/flutter#62589]
I am getting this error on running my first app itself
![error fl](https://user-images.githubusercontent.com/63551943/88953134-15369180-d2b6-11ea-89c3-e67382446068.png)

My device is connected properly. I am using Windows 7 SP1 with Redmi Note 7 pro as device.
This error comes up as soon as the app runs on my device after intallation.
I have already tried reinstalling sdk platform tools.
Also Everything is updated upto date
Also my app works fine on installation but this error comes up.
kindly help me out..

**Comment by darshankawar** [comment]
Hi @harshmahalka,

Can you try  `adb kill-server` and then `adb root` and see if it works for you?
Thanks.
