### ISSUE TITLE
is there any limitation for open new tab of flutter app in flutter web?

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [flutter/flutter#62598]
I tried to open my web app in 6 tabs and more tab in browser but I couldn't.
Until 5 pages it is ok but after that, it stays on loading
is there any limitation or bug?

**Comment by TahaTesser** [comment]
Hi @MohammadEhsanMirzaaee 
Not sure if it has any limitation
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by MohammadEhsanMirzaaee** [comment]
in production and release, it's ok and I able to create unlimited new tabs but in debug mode when it's connected to my code the problem appears

open new tab code:
```
js.context.callMethod("open", [testUrl]);
````

```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.0-7.2.pre at /Users/mohammadehsan/Library/Flutter/flutter
    • Framework revision a2bde82fbd (13 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mohammadehsan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 80.0.3987.122

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @MohammadEhsanMirzaaee 
Can you upgrade to master and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Also do you see any errors in chrome console, if yes, please provide 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
