### ISSUE TITLE
Input should have some default padding

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#626]
I think `input` should have some default padding (and/or a padding attribute). Currently placeholder and actual text are too close to the edges.

Workaround of developer adding the padding using a container is not great since that padding area won't respond to tap events for focus.

**Comment by abarth** [comment]
The padding is speced here:

https://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

There's supposed to be 16px above and below the text.  Currently we only have 8px.
