### ISSUE TITLE
Navigator Stack Preview

### ISSUE THREAD

**Issue by millionhz** [flutter/flutter#62609]
## Use case & Proposal

Often times I find it difficult to remember the state of the navigator stack, so there should be a way to see the current navigator stack like the just run a function to show a list of the stack. This will be very helpful for debugging.

**Comment by pedromassangocode** [comment]
Hi @millionhz 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/29317).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
