### ISSUE TITLE
Official support for Google Translate on Pub Dev

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#62604]
Hi I searched for the official Google Translate pub dev pkg, but didn't find one. Are there any plans by Google to support it? I will need it for chat. Thanks.

**Comment by darshankawar** [comment]
Hi @andesappal,
Although there's no Flutter's official plugin for Google translate, there's a 3rd party [plugin](https://pub.dev/packages/translator) that you may try.
Please note that this is not an endorsement for this plugin but just to let you know that there exists a plugin. See if it works per your need.
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
