### ISSUE TITLE
unable to run on a real device with usb 

### ISSUE THREAD

**Issue by Swarajsm** [flutter/flutter#62606]
Hi, I have been trying to install my application on my Real Android device(Android 10) which totally works fine on my Emulator.
But I see an error while trying to run on my device.

**Comment by Swarajsm** [comment]
`Launching lib\main.dart on RMX1971 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > dl.google.com
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > jcenter.bintray.com
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7/arm64_v8a_debug-1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7.pom'.
               > storage.googleapis.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by erickzanardo** [comment]
Seems related to this: https://github.com/flutter/flutter/issues/41553 and this: https://github.com/flutter/flutter/issues/41281

By reading those issues, maybe upgrading flutter or cleaning the gradle cache could be possible solutions

Or maybe just intermittent network issues? I wasn't able to access those links

**Comment by Swarajsm** [comment]
> Seems related to this: #41553 and this: #41281
> 
> By reading those issues, maybe upgrading flutter or cleaning the Gradle cache could be possible solutions
> 
> Or maybe just intermittent network issues? I wasn't able to access those links

I don't know ho do I do that?

**Comment by lechnerio** [comment]
Hi, I had the same issue. 

Try to run `$ flutter upgrade` (which version are you currently running?)  
to clear the gradle cache: https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache

also make sure you are running the latest usb driver for android development.

**Comment by Swarajsm** [comment]
@lechnerio here is my doctor result
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)

**Comment by Swarajsm** [comment]
Could it be because I don't have the Google USB drivers?

**Comment by Swarajsm** [comment]
I will be closing this issue in 120 minutes, The problem was solved after installing the latest versions of Google USB 
 Drivers [https://developer.android.com/studio/run/win-usb](url)

**Comment by lechnerio** [comment]
> Could it be because I don't have the Google USB drivers?

pretty sure it's because of that. the developer studio docs is a pretty nicely documented resource. you should get it to run in no time

**Comment by Swarajsm** [comment]
Thanks alot man
