### ISSUE TITLE
layer_tree pointer being null not checked in engine/shell/common/animator.cc

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#62600]
https://github.com/flutter/engine/blob/f2b02d8fd53b7190461f2dde5eb2e27a16dbf086/shell/common/animator.cc#L181
This `if` statement looks like checking the pointer `layer_tree` not being NULL, but before this if, `layer_tree->frame_size()` is already called. 

It seems that either we don't need the `if` or we should put what before it inside `if`.

**Comment by CareF** [comment]
cc @liyuqian @jason-simmons @chinmaygarde @iskakaushik

**Comment by flar** [comment]
The only caller I can find (in engine.cc) protects against null before it calls this method, but I could be missing an indirect call to it.

Also, the code following this if block that attempts a completion on the LayerTree becomes suspect as well.

**Comment by iskakaushik** [comment]
If there is a code-path that results in this case happening or if we believe this to have a potential risk, i'd like to see a test as a part of this PR.

**Comment by CareF** [comment]
Double checked and I also didn't find anywhere else this method is called other than 
https://github.com/flutter/engine/blob/11964ec300e25649b0e8a64fc47988f15ef1f52f/shell/common/engine.cc#L470
which is already `null` protected. So I removed the if statement. And thus I can't think of anything to test. @iskakaushik

**Comment by iskakaushik** [comment]
Feel free to close the issue if there's nothing else to do here.

**Comment by CareF** [comment]
@iskakaushik I think the issue should be closed by flutter/engine#20178
