### ISSUE TITLE
InputDecorator sometimes reports incorrect intrinsic height

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#62620]
The following Dart Pad shows an overflow error where one should not occur. It happens when the given `TextFormField` displays its error text.

https://dartpad.dev/5d4da142bb0aec403f608a0fffa9c7d3

After adding `visualDensity: VisualDensity.adaptivePlatformDensity` to the `Theme`, the issue disappears.

https://dartpad.dev/0c5beea2e2149faef98110edc9fb7bff

@slightfoot found the likely culprit of this issue here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L1259

**Comment by mdebbar** [comment]
My understanding is this is working as intended. The docs for [adaptivePlatformDensity](https://api.flutter.dev/flutter/material/VisualDensity/adaptivePlatformDensity.html) say that by default it makes thing compact on desktop environments. When I open the flutter web app in a mobile browser I see that `adaptivePlatformDensity` doesn't make a difference.

**Comment by matthew-carroll** [comment]
Hm, I don't think I would describe any behavior like this to be "working as intended". For example, consider the following questions and answers:

Is the developer doing anything unusual from a layout perspective?
 - Not really. We're working with a column that has children of definite size. We stack a handful of items, we grab their intrinsic height, and then we either scroll or don't. The layout concepts here are quite simple and obvious. An overflow doesn't really make sense.

Is it obvious that this layout should produce an overflow?
 - No, not at all. I legitimately thought this was a bug up to this moment (and still do).

Is it obvious what the cause of the overflow is?
 - No, not at all. Only by digging through the source code with @slightfoot did we locate the issue. I would not have even noticed the offending line if it weren't for Simon pointing it out.

Is it clear what a developer should do to rectify this overflow?
 - No, not at all. Because the root cause is completely opaque, the change to fix this issue is almost unknowable.

Were any error logs produced that would help developers locate the root cause and fix it?
 - No, not at all.

Even if this particular layout should not work in the absence of the `visualDensity` property (which is debatable), running into broken layouts without any reasonable method or approach to debug it should not be considered "working as intended". At a minimum, I would like to see appropriate error logs that would lead a developer to understanding the root cause and then taking the appropriate action to correct it.

**Comment by mdebbar** [comment]
I didn't see the overflow issue when I tried it. I only saw the differences in spacing/padding. That's why I said that's expected when using `adaptivePlatformDensity`. I was later able to reproduce the overflow issue by changing the dimension of the window.

The issue of incorrect intrinsic height is filed [here](https://github.com/flutter/flutter/issues/48679) (and it looks like the same root cause for your [other issue](https://github.com/flutter/flutter/issues/62619)).

**Comment by matthew-carroll** [comment]
If the root cause is the same as #62619 then wouldn't we expect the `adaptivePlatformDensity` to have no effect? Because #62619 was found to be platform independent, right?

**Comment by mdebbar** [comment]
@Piinks @gspencergoog any idea why the density affects intrinsic height measurement?

**Comment by gspencergoog** [comment]
@matthew-carroll I can't reproduce the problem with the Dartpad links in the description. Has the problem gone away?

I also don't think that setting the density is the "real" fix, I think it happens to fix the problem because it adjusts the internal padding from the default, but I suspect another cause.

**Comment by matthew-carroll** [comment]
Hi @gspencergoog, here's a screenshot of the issue that I just took right now. Perhaps it requires a certain size or aspect ratio?

![Screen Shot 2020-08-13 at 1 47 04 PM](https://user-images.githubusercontent.com/7259036/90185412-8cb2f900-dd6b-11ea-9359-f9cd5fabcd44.png)

**Comment by gspencergoog** [comment]
Ahh, yes, it has to be a certain height.  I had tried changing width, but not height. I see it now.

**Comment by gspencergoog** [comment]
But adding `adaptivePlatformDensity` doesn't fix the problem for me.

**Comment by matthew-carroll** [comment]
Hm, it solves it for me. I can't seem to find a size that reproduces the issue when the `visualDensity` property is provided.

**Comment by gspencergoog** [comment]
I can't find one where it doesn't:
![image](https://user-images.githubusercontent.com/8867023/90186098-85401f80-dd6c-11ea-811a-553892c6869e.png)

**Comment by gspencergoog** [comment]
Well, except for really big sizes.

**Comment by matthew-carroll** [comment]
Interesting. I guess it might be a different root cause then.

**Comment by gspencergoog** [comment]
I can reproduce what you're seeing on Linux, though. The density adjustment changes the margin around the text, internal to the `InputDecorator` (as you saw in the code).  You can also "fix" the problem by setting `isDense` to true (which is unrelated to visual density), or by setting `expands` to true on the  `TextFormField`.

I suspect the root problem is related to the one that Michael pointed out in the other bug: https://github.com/flutter/flutter/issues/48679

**Comment by darshankawar** [comment]
I am able to replicate the overflow issue upon running the dartpad link and tapping on `do something`.

![Screen Shot 2020-08-27 at 4 19 55 PM](https://user-images.githubusercontent.com/67046386/91433625-3375ba00-e881-11ea-9175-b4f92fd0e085.png)

**Comment by darshankawar** [comment]
@matthew-carroll Hi,
I verified this issue using latest master version and running on web but didn't get the error as reported above and earlier:

<img width="924" alt="Screenshot 2023-04-21 at 4 30 05 PM" src="https://user-images.githubusercontent.com/67046386/233620689-7f64a0f4-e13f-4a56-ac60-8a818959c6f6.png">

I updated the dartpad code to run on latest version as below. Can you take a look and see if you still get the reported error at your end ?

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  void _validateForm() {
    _formKey.currentState?.validate();
  }

  // This tree reproduces an overflow problem that I don't understand.
  // Upon initial run everything is fine. Then, press the button that
  // causes the error message to appear. Notice that suddenly there is
  // an overflow error on the Column.
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: double.infinity,
      color: Colors.yellow,
      child: _buildExpandOrScroll(
        child: Center(
          child: _buildCard(
            child: _buildContent(),
          ),
        ),
      ),
    );
  }

  // Builds a series of widgets that accomplish the concept of scrolling
  // if the content exceeds the available space, or, if there is sufficient
  // space to display the content then the content is given all available
  // space to occupy. My use-case is the desire to vertically center my
  // content when it does not overflow the available space.
  Widget _buildExpandOrScroll({Widget? child}) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          child: ConstrainedBox(
            constraints: BoxConstraints(
              minHeight: constraints.maxHeight,
            ),
            child: IntrinsicHeight(
              child: child,
            ),
          ),
        );
      },
    );
  }

  // Builds a white card with rounded corners. Padding is applied outside
  // the card, and inside the card. The content of the card is the provided
  // "child"
  Widget _buildCard({Widget? child}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 72),
      child: ConstrainedBox(
        constraints: BoxConstraints.loose(Size(400, double.infinity)),
        child: Material(
          color: Colors.white,
          borderRadius: BorderRadius.circular(32),
          elevation: 24,
          child: Padding(
            padding: const EdgeInsets.symmetric(
                horizontal: 40, vertical: 20),
            child: child,
          ),
        ),
      ),
    );
  }

  // Builds the content of the card. Includes a title, a bunch of vertical
  // space, an error message that may or may not be displayed, and a button
  // that causes the error message to display.
  Widget _buildContent() {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'Some Title',
            style: TextStyle(
              fontSize: 30,
              fontWeight: FontWeight.bold,
            ),
          ),
          TextFormField(
            decoration: InputDecoration(
              hintText: 'some input...',
            ),
            validator: (String? value) {
              return 'This is a form error';
            },
          ),
          SizedBox(height: 400),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              //  color: Colors.grey.shade900,
              //  padding: const EdgeInsets.all(24),
              //  shape: RoundedRectangleBorder(
              //    borderRadius: BorderRadius.circular(16),
              child: Text(
                'Do Something',
                style: TextStyle(
                  color: Colors.white,
                ),
              ),
              onPressed: () {
                _validateForm();
              },
            ),
          ),
          SizedBox(height: 16),
        ],
      ),
    );
  }
}

```

</details>
