### ISSUE TITLE
Missing packages Google or Facebook login

### ISSUE THREAD

**Issue by devisdee** [flutter/flutter#62639]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
```
import 'package:esport/backend/firebase_services.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_sign_in/google_sign_in.dart';

class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final FirebaseRepository _services = FirebaseRepository();
  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final FirebaseAuth _auth = FirebaseAuth.instance;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          Positioned(
            top: -40,
            left: -10,
            child: CircleAvatar(
              radius: 50,
              backgroundImage: AssetImage(
                'assets/images/ll2.jpg',
              ),
            ),
          ),
          Positioned(
            top: 90,
            left: 90,
            child: CircleAvatar(
              radius: 25,
              backgroundImage: AssetImage(
                'assets/images/ll6.jpg',
              ),
            ),
          ),
          Positioned(
            top: 140,
            left: -15,
            child: CircleAvatar(
              radius: 35,
              backgroundImage: AssetImage(
                'assets/images/ll1.jpg',
              ),
            ),
          ),
          Positioned(
            top: -50,
            right: 80,
            child: CircleAvatar(
              radius: 40,
              backgroundImage: AssetImage(
                'assets/images/ll4.jpg',
              ),
            ),
          ),
          Positioned(
            top: 20,
            right: -55,
            child: CircleAvatar(
              radius: 50,
              backgroundImage: AssetImage(
                'assets/images/ll7.jpg',
              ),
            ),
          ),
          Positioned(
            top: 100,
            right: 75,
            child: CircleAvatar(
              radius: 60,
              backgroundImage: AssetImage(
                'assets/images/ll8.jpg',
              ),
            ),
          ),
          Positioned(
            top: MediaQuery.of(context).size.height / 2.5,
            child: Container(
              width: MediaQuery.of(context).size.width,
              child: Center(
                child: RichText(
                  text: TextSpan(
                    children: [
                      TextSpan(
                        text: 'e',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.greenAccent,
                          fontSize: 38,
                        ),
                      ),
                      TextSpan(
                        text: 'Sports',
                        style: TextStyle(
                            color: Colors.white,
                            fontSize: 40,
                            fontFamily: 'Pacifico'),
                      )
                    ],
                  ),
                ),
              ),
            ),
          ),
          Positioned(
            top: MediaQuery.of(context).size.height / 1.50,
            left: 0,
            right: 0,
            child: GestureDetector(
              onTap: () {
                _services.signInFacebook();
              },
              child: Container(
                margin: EdgeInsets.only(left: 50, right: 50),
                padding: EdgeInsets.all(10),
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(20),
                    color: Colors.blue,
                    boxShadow: [
                      BoxShadow(
                        blurRadius: 5,
                        color: Color(0xff92e1e2),
                      )
                    ]),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Icon(FontAwesomeIcons.facebookF, color: Colors.white),
                    SizedBox(
                      width: 20,
                    ),
                    Text(
                      'Connect to Facebook',
                      style: TextStyle(
                          fontSize: 20,
                          fontFamily: 'Kalam',
                          color: Colors.white),
                    )
                  ],
                ),
              ),
            ),
          ),
          Positioned(
            top: MediaQuery.of(context).size.height / 1.30,
            left: 0,
            right: 0,
            child: GestureDetector(
              onTap: () async {
                try {
                  final GoogleSignInAccount _googleUser =
                      await _googleSignIn.signIn();
                  final GoogleSignInAuthentication _googleAuth =
                      await _googleUser.authentication;

                  final AuthCredential credential =
                      GoogleAuthProvider.getCredential(
                    accessToken: _googleAuth.accessToken,
                    idToken: _googleAuth.idToken,
                  );

                  final FirebaseUser user =
                      (await _auth.signInWithCredential(credential)).user;
                  print("signed in " + user.displayName);

                 
                } catch (e) {
                  print(e);
                }
                //_services.signInGoogle();
              },
              child: Container(
                margin: EdgeInsets.only(left: 50, right: 50),
                padding: EdgeInsets.all(10),
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(20),
                    color: Colors.red,
                    boxShadow: [
                      BoxShadow(color: Color(0xffe65758), blurRadius: 5)
                    ]),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Icon(
                      FontAwesomeIcons.google,
                      color: Colors.white,
                    ),
                    SizedBox(
                      width: 20,
                    ),
                    Text(
                      'Connect to Google',
                      style: TextStyle(
                        fontSize: 20,
                        fontFamily: 'Kalam',
                        color: Colors.white,
                      ),
                    )
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Expected results:** 

**Actual results:** 
notify runnable to start.
```
D/ZrHung.AppEyeUiProbe(17445): restart watching
D/ZrHung.AppEyeUiProbe(17445): restart watching
I/OpenGLRenderer(17445): Initialized EGL, version 1.4, mEglDisplay 0x1
D/OpenGLRenderer(17445): Swap behavior 2
D/mali_winsys(17445): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns
 0x3000
D/mali_winsys(17445): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns
 0x3000
W/libEGL  (17445): EGLNativeWindowType 0x7ab0387010 disconnect failed
D/mali_winsys(17445): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns
 0x3000
I/ViewRootImpl(17445): jank_removeInvalidNode jank list is null
W/InputMethodManager(17445): startInputReason = 1
W/InputMethodManager(17445): startInputReason = 5
I/flutter (17445): MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

```

<details>
  <summary>Logs</summary>

```
```

google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
```
```

```√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\corei\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\corei\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • LLD AL10  android-arm64 • Android 9 (API 28)


```

</details>

**Comment by darshankawar** [comment]
Hi @devisdee,
I tried to replicate the issue without `FirebaseRepository` package you mentioned and I was able to run the app and tap on `Sign in to Google` properly without any issues.
Can you try with official google_sign_in [example](https://pub.dev/packages/google_sign_in/example) and see if you get the same exception ?
If you don't get the exception using official example, then probably issue could be in `Firebase Repository` or the backend package you are using.  Also when do you get the error ? During build compile or after tapping on the Google Sign in button ?

**Comment by devisdee** [comment]
not solve the problem ? same message is display 

Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
W/FlutterActivity(25721): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@666716c) but could not find and invoke the GeneratedPluginRegistrant.
Debug service listening on ws://127.0.0.1:56232/L3REOtE36gs=/ws
Syncing files to device LLD AL10...
E/        (25721): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
D/AwareBitmapCacher(25721): handleInit switch not opened pid=25721
D/ZrHung.AppEyeUiProbe(25721): notify runnable to start.
D/ZrHung.AppEyeUiProbe(25721): restart watching
I/OpenGLRenderer(25721): Initialized EGL, version 1.4, mEglDisplay 0x1
D/OpenGLRenderer(25721): Swap behavior 2
D/mali_winsys(25721): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(25721): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/app.nibs.espor(25721): Starting profile saver IsSaveProfileNow end.
W/InputMethodManager(25721): startInputReason = 1
W/InputMethodManager(25721): startInputReason = 5
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
I/flutter (25721): Google Error No implementation found for method init on channel plugins.flutter.io/google_sign_in
W/InputMethodManager(25721): startInputReason = 8
W/IInputConnectionWrapper(25721): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(25721): getTextBeforeCursor on inactive InputConnection
D/ZrHung.AppEyeUiProbe(25721): stop checker.
W/libEGL  (25721): EGLNativeWindowType 0x7a93a2d010 disconnect failed
D/ViewRootImpl[MainActivity](25721): surface should not be released
W/libEGL  (25721): EGLNativeWindowType 0x7a9398a010 disconnect failed
V/ActivityThread(25721): Handle window ActivityRecord{e2604b3 token=android.os.BinderProxy@cee3ec5 {app.nibs.esport/app.nibs.esport.MainActivity}} visibility: false
D/ZrHung.AppEyeUiProbe(25721): Current Activity:false
D/ZrHung.AppEyeUiProbe(25721): not watching, wait.

**Comment by darshankawar** [comment]
@devisdee,
Can you try [this](https://stackoverflow.com/a/63027620) solution and see if it works for you ?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by Septimus** [comment]
Seems like a similar issue to #61166.
