### ISSUE TITLE
inferred type is MainActivity but FlutterEngine was expected #47095

### ISSUE THREAD

**Issue by iamkunalpitale** [flutter/flutter#62644]
e: C:\Users\HP\StudioProjects\fluxstore_woocommerce\android\app\src\main\kotlin\com\inspireui\fluxstore\MainActivity.kt: (9, 5): 'configureFlutterEngine' overrides nothing
e: C:\Users\HP\StudioProjects\fluxstore_woocommerce\android\app\src\main\kotlin\com\inspireui\fluxstore\MainActivity.kt: (9, 42): Unresolved reference: NonNull
e: C:\Users\HP\StudioProjects\fluxstore_woocommerce\android\app\src\main\kotlin\com\inspireui\fluxstore\MainActivity.kt: (9, 65): Unresolved reference: FlutterEngine

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
Hi @iamkunalpitale  
Can you please provide your `flutter doctor -v`, 
your `flutter build apk --verbose` 
your `pubspec.yaml`
and a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
