### ISSUE TITLE
flutterview time consuming

### ISSUE THREAD

**Issue by liruibao** [flutter/flutter#62651]
Flutterview takes 700ms from creation to the first frame display. Is there any good optimization strategy?

**Comment by pedromassangocode** [comment]
Hi @liruibao 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by liruibao** [comment]
• Framework revision dbf9f1c617 (10 days ago), 2020-07-21 11:29:25 +0800
    • Engine revision e683684044
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3

    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

**Comment by pedromassangocode** [comment]
Hi @liruibao 
Can you please provide a complete `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample? I need these information to help you with this issue.

Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
