### ISSUE TITLE
maxLength in TextFormField accepts extra symbol with TextInputType.number

### ISSUE THREAD

**Issue by onadoroz** [flutter/flutter#62653]
## Steps to Reproduce

1. set maxLength: 1 and keyboardType: TextInputType.number, in TextFormField Widget
2. enter value 111 in the field
3. display the value of the filed in console

**Expected results:** 
I/flutter (23736): Value: 1
I/flutter (23736): Value: 1
I/flutter (23736): Value: 1

**Actual results:** 
I/flutter (23736): Value: 1
I/flutter (23736): Value: 1
I/flutter (23736): Value: 11

<details>
 
TextFormField(
                keyboardType: TextInputType.number,
                maxLength: 1,
                onChanged: (a) {
                  print("Value: $a");
                })),

I/flutter (  506): Value: 1
I/flutter (  506): Value: 1
I/flutter (  506): Value: 11

</details>

**Comment by pedromassangocode** [comment]
Hi @onadoroz 
Can you please provide your `flutter doctor -v`. 
Thank you

**Comment by onadoroz** [comment]
> flutter doctor -v

PS C:\DiskD\lab\blp_biz\blpbiz> flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.17763.1282], locale en-US)
    • Flutter version 1.17.5 at C:\DiskD\CoDE\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\onadoroz\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Pixel 2 • FA79L1A10329 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by pedromassangocode** [comment]
I was able to reproduce on Android but not on iOS devices.

<details>
<summary>  Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            keyboardType: TextInputType.number,
            maxLength: 1,
            onChanged: (a) {
              print("Value: $a");
            },
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>  Logs (Android)</summary>

```
I/flutter ( 4298): Value: 1
I/flutter ( 4298): Value: 1
I/flutter ( 4298): Value: 11
```
</details>

<details>
<summary>  Logs (iOS)</summary>

```
I/flutter ( 4298): Value: 1
I/flutter ( 4298): Value: 1
I/flutter ( 4298): Value: 1
```
</details>

<details>
<summary>  flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.17.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 1119074E-0493-4533-9212-6758A33EB40C • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 3 categories.

```
</details>

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by onadoroz** [comment]
@TahaTesser ,

I'd not agree that we should ignore this issue as data displayed in the text filed is not the same as what system processes in this case. despite the probability of this case is low, but it can make a solid impact on data processing.
I'm attaching a screenshot form example app.
![Screenshot_20200825-170445](https://user-images.githubusercontent.com/43214237/91192902-c9310e00-e6f6-11ea-936b-dc9212701296.png)
Please highlight what additional information is needed.

**Comment by pedromassangocode** [comment]
Hi @onadoroz 
I as I commented on https://github.com/flutter/flutter/issues/62653#issuecomment-667059733 the issue was not reproducible on `dev` and now it is not reproducible on latest `stable` channel.

Please upgrade `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If you still facing this issue then please provide the output of `flutter doctor -v`.

**Comment by onadoroz** [comment]
Hi @pedromassangocode 
I just upgraded and can confirm that issue is not reproducible on:

flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.17763.1339], locale en-US)
    • Flutter version 1.20.2 at C:\DiskD\CoDE\flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

Thank you for your attention!
