### ISSUE TITLE
The TextField could not set the selection state?

### ISSUE THREAD

**Issue by 1169886116** [flutter/flutter#62654]
//PDA扫描得到的值,取出来处理一下,在赋值给输入框,在设置选中状态无效
onChanged: (str) {
//将输入框的值处理
String newStr = str.split("#").first;
//赋值输入框新值
_controller.text = newStr;
//设置新值的选中状态
_controller.selection = TextSelection(
             baseOffset: 0,
             extentOffset: numberStr.length,                  
  );
} 

The TextField could not set the selection state?

**Comment by pedromassangocode** [comment]
Hi @1169886116 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by reazon7** [comment]
same issue...
change selection not working:
`textController.selection = TextSelection.collapsed(offset: data.length);`


` Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)`

**Comment by pedromassangocode** [comment]
Hi @reazon7 
If you are facing this same issue please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample to help us reproduce the issue.
Thank you.

**Comment by reazon7** [comment]
> Hi @reazon7
> If you are facing this same issue please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample to help us reproduce the issue.
> Thank you.

in my case,, it's not TextField but TextFormField that has the problem.

here's minimal code
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final TextEditingController _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Testing'),
        ),
        body: TextFormField(
          controller: _controller,
          onChanged: (value) {
            String newData = 'asdqwe123';
            _controller.value = TextEditingValue(
              text: newData,
              selection: TextSelection.collapsed(offset: newData.length),
            );
          },
        ),
      ),
    );
  }
}
`
this happended after I upgraded flutter version to stable 1.20.1 (in stable 1.17.5 it's fine)...
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.17134.1246], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)`

**Comment by Omrankabalan** [comment]
Same happening to me after upgrading to stable 1.20.1 

It was working perfectly in stable 1.17.5

**Comment by katlehotech** [comment]
Same problem.

Flutter upgrade broke: 

TextSelection.collapsed(offset: 5);

the offset is always 0(zero), it ignores the 5

**Comment by pedromassangocode** [comment]
Hi @katlehotech 
For me to help you solve this issue I need you to provide a code that I can just copy/paste and run it. Please provide such code.
Thank you

**Comment by Omrankabalan** [comment]
@pedromassangocode  There is complete reproducible code added by @reazon7 9 days ago!

**Comment by 1169886116** [comment]
import 'package:flutter/material.dart';

class TextFieldPage extends StatefulWidget {
  @override
  _TextFieldPageState createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {
  TextEditingController tfController = TextEditingController();
  FocusNode tfNode = FocusNode();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text("选中状态"),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            TextField(
              controller: tfController,
              focusNode: tfNode,
              decoration: InputDecoration(
                labelText: "用户名",
                hintText: "用户名",
                prefixIcon: Icon(Icons.person),
              ),
              onChanged: (result) {
                print("输入: $result");
              },
              onSubmitted: (result) {
                print("提交: $result");
                //赋值
//                tfController.text = result;
                //设置选中状态
                tfController.selection = TextSelection(
                  baseOffset: 0, //开始位置
                  extentOffset: result.length, //长度
                );
              },
            )
          ],
        ),
      ),
    );
  }
}

**Comment by 1169886116** [comment]
Clicking submit cannot set the content to selected mode

**Comment by 1169886116** [comment]
flutter SDK : [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.6 19G2021,
    locale zh-Hans-CN)

**Comment by pedromassangocode** [comment]
> @pedromassangocode There is complete reproducible code added by @reazon7 9 days ago!

The code he shared does not reproduce the actual issue!

**Comment by pedromassangocode** [comment]
Hi @1169886116  
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v` and a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by katlehotech** [comment]
I was on a Beta Channel so it might have been an issue in my case

```
C:\Users\vivat\AndroidStudioProjects\ecash_pay>flutter upgrade --force
Flutter is already up to date on channel beta
Flutter 1.20.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (6 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

**Comment by katlehotech** [comment]
Just do a 
`> flutter downgrade`
everything will work fine

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
