### ISSUE TITLE
RawKeyboard._synchronizeModifiers crash

### ISSUE THREAD

**Issue by nikitadol** [flutter/flutter#62663]
I got some crashes from analytics

Devices:
- HUAWEI P30 (Android 10.0)
- HUAWEI P30 Pro (Android 10.0)

```
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
       at RawKeyboard._synchronizeModifiers(raw_keyboard.dart:599)
       at RawKeyboard._handleKeyEvent(raw_keyboard.dart:525)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:74)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:73)
       at _DefaultBinaryMessenger.handlePlatformMessage(binding.dart:199)
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-BY)
    • Flutter version 1.17.5 at /Users/nikitadold/development/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/nikitadold/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/nikitadold/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3
```

</details>

**Comment by darshankawar** [comment]
Hi @nikitadol,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by nikitadol** [comment]
> Please provide flutter doctor -v 

It was a little higher

> a minimal complete reproducible code sample that shows the issue you are facing.

Judging by the analytics logs, this happens after the user interacted with the TextField and then left the screen with it, since the crash occurs on the screen, where there are no text fields.

I would gladly provide a minimal code, but I don't have such a device.

**Comment by darshankawar** [comment]
Hi @nikitadol,
Without a code sample, we won't be able to help out much since we don't know the exact cause of the issue yet.

**Comment by nikitadol** [comment]
- I do not know in what case the code in this method is executed
- I don't know why 'assert' is there
https://github.com/flutter/flutter/blob/7884420a0a32467fa268761b99cf19c58480a499/packages/flutter/lib/src/services/raw_keyboard.dart#L659-L661
- I don't have a Huawei P30 to try to find the problem, but maybe someone has such a device and can help us

**Comment by kw2019ltd** [comment]
same issue

![image](https://user-images.githubusercontent.com/47334522/89155608-d5033780-d571-11ea-96f2-aa03e1f0098e.png)

**Comment by darshankawar** [comment]
@kw2019ltd, If you are able to replicate the exception, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Since I don't have Huawei device, and without proper steps to replicate, it's difficult to analyze the root cause of the issue.

**Comment by kw2019ltd** [comment]
hi no iam not, it was one of the user using my app in production, saw it in firebase.

**Comment by mehmetf** [comment]
Customer:money is also seeing this. Not sure on what phone yet but it is frequent enough to bubble up to p2. 

https://github.com/flutter/flutter/commit/c68758fab137f751d56faa1ced119b7a3561e37e# might be the culprit? Hence @gspencergoog . The crash location indicates that it is occurring somewhere here: https://github.com/flutter/flutter/commit/c68758fab137f751d56faa1ced119b7a3561e37e#diff-736f0dce2e45442b57ab5128ac1f5f1bR661-R670
