### ISSUE TITLE
Build input file cannot be found: '/Users/mac/forkcommerceBefours/build/ios/Debug-iphonesimulator/Runner.app/Runner' (in target 'Runner' from project 'Runner')

### ISSUE THREAD

**Issue by mbilawisdom** [flutter/flutter#62662]
Xcode's output:
↳
    error: Build input file cannot be found: '/Users/mac/forkcommerceBefours/build/ios/Debug-iphonesimulator/Runner.app/Runner' (in target 'Runner' from project 'Runner')
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by darshankawar** [comment]
@mbilawisdom,
You seem to have opened similar issue earlier today, [62634](https://github.com/flutter/flutter/issues/62634).
Please follow-up there for updates and kindly don't open multiple tickets for same issue.
Closing this as duplicate.
