### ISSUE TITLE
Switch from `amberctl get_up` to `pkgctl resolve`

### ISSUE THREAD

**Issue by nekorevend** [flutter/flutter#62684]
While the transition from `amberctl` to `pkgctl` is still in progress, there is a relatively simple change that can be made:
`amberctl get_up -n <package name>`
becomes
`pkgctl resolve fuchsia-pkg://fuchsia.com/<package name>`

This transition will allow Fuchsia to more quickly drop deprecated commands from the API surface area.

**Comment by iskakaushik** [comment]
this needs to be done in https://github.com/flutter/packages/tree/master/packages/fuchsia_ctl

**Comment by zanderso** [comment]
See also: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/fuchsia/amber_ctl.dart

**Comment by digiter** [comment]
Triage: what's needed from infra team?

**Comment by chaselatta** [comment]
Tracking via fxbug.dev/61329
