### ISSUE TITLE
Skia gold github bot doesn't update the PR status post triage

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#62682]
https://github.com/flutter/flutter/pull/62647#issuecomment-666926042 says there is 1 item awaiting triage.

The dashboard says

```
Displaying: 0 of 0 images starting at 0
UniqueTests Visible: 0
UniqueTests Total: 0
```

**Comment by Piinks** [comment]
Checking the logs on the cocoon dashboard, something may be broken there.

**Comment by Piinks** [comment]
It looks like multiple Luci builds are not reflected as completed, which is blocking the bot from clearing its pending status.

![Screen Shot 2020-07-31 at 10 52 59 AM](https://user-images.githubusercontent.com/16964204/89063603-4e561c80-d31d-11ea-93c7-d3ccd9956d52.png)

![Screen Shot 2020-07-31 at 10 57 18 AM](https://user-images.githubusercontent.com/16964204/89063610-50b87680-d31d-11ea-9539-f9436ea35c7b.png)

Reference PR: https://github.com/flutter/flutter/pull/62513

This appears to be affecting all PRs, the merge bot will be blocked by this as well.

cc/ @godofredoc

**Comment by Piinks** [comment]
Changes can land in the interim once all other checks have completed. If there are actual image changes, the Skia bot will comment on the PR to notify.

**Comment by Piinks** [comment]
A change in cocoon has been deployed that removes Luci statuses (they use checks now), which should unblock the bot for new PRs. Any PR that has a duped Luci status and check probably won't resolve the flutter-gold bot until I can switch it over to update for checks, working on that now. :)
