### ISSUE TITLE
Add loading indicator while the app is being loaded (esp. for web)

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#62680]
# Description
Web apps (especially those build by Skia-canvasKit) take a while to load the first time. E.g. look at this simple example: https://youtu.be/9kC7S_ILaho It's a very basic app that does NOT do anything. It's 5.8MB big and has 253 files (little .svg files). If you want more detail about the code, you have it all here: https://github.com/flutter/flutter/issues/62670 

## Samsung A40: 6 seconds (loading time)
Anyhow, as you can see this app was being loaded for **6 seconds** while the user is staring at a blank screen and has no idea what's going on. 

The only thing that can cross his mind at this point is that the website is not working and therefore is forced to close the page. I even myself thought that the website was NOT working. Had it not been for the video, I would have closed it out thinking something was broken. Can you please enable a loading indicator so users know what's going on?

## iPad 2 mini: 31 seconds (loading time)
I just tried the same site https://experiment25.web.app/ on iPad 2 mini (iOS12) and loading took more than **half a minute**!!! https://youtu.be/AWg2k4vN4Fc

## iPhone 6: 18 seconds (loading time)
Same site https://experiment25.web.app/ on iPhone 6 (iOS12) and loading took more than **18 seconds**!

A loading indicator is a MUST!

**Comment by TahaTesser** [comment]
Hi @tomasbaran 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/48468
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
