### ISSUE TITLE
Cannot use SingleTickerProviderStateMixin with Null Safety

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#62685]
##  Steps to Reproduce

1. `class _FooState extends State<Foo> with SingleTickerProviderStateMixin<Foo>`
2. Build app with `--enable-experiment=non-nullable --no-sound-null-safety`.
3. Compile time error: `Error: 'State<Foo>' doesn't implement 'State<Foo>' so it can't be used with 'SingleTickerProviderStateMixin<Foo>'.`

That makes absolutely no sense to me 😂

```
Flutter 1.21.0-6.0.pre.138 • channel master • https://github.com/flutter/flutter.git
Framework • revision f06ee8dd8d (17 minutes ago) • 2020-07-31 13:34:35 -0400
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)
```

**Comment by creativecreatorormaybenot** [comment]
I found a fix for this:

## Fix

You can make the state parameter nullable, which will resolve the issue.

```dart
  State<Foo?> createState() => _FooState();
}

class _FooState extends State<Foo?> with SingleTickerProviderStateMixin<Foo?> {
```

**Comment by darshankawar** [comment]
Hi @creativecreatorormaybenot,
Per your last comment, do you feel the issue can be closed ?
Thanks.

**Comment by creativecreatorormaybenot** [comment]
@darshankawar I am not sure if this is intended, however, for the moment this might be fine to close because the migration is not yet finished.
