### ISSUE TITLE
 snackbar Not Working with cupertinopagesnackbar 

### ISSUE THREAD

**Issue by ifahimkhan** [flutter/flutter#62693]
i tried passing Scaffold as a child to CupertinoPageScaffold not working

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>
ant error-causing widget was: 
  MaterialApp file:///C:/Users/user/AndroidStudioProjects/flutter_app_sqflite/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1965:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3414:29)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3437:32)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3220:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
...

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @ifahimkhan,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
