### ISSUE TITLE
The plugin camera could not be built error when building for release

### ISSUE THREAD

**Issue by gtchax** [flutter/flutter#62716]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'camera'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 10s
           
[  +12 ms] "flutter apk" took 248,834ms.
The plugin camera could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:773:7)
#2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#3      _rootRunBinary (dart:async/zone.dart:1204:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#8      Future._completeError (dart:async/future_impl.dart:534:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#19     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#20     _rootRunUnary (dart:async/zone.dart:1192:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#26     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#34     _rootRun (dart:async/zone.dart:1184:13)
#35     _CustomZone.run (dart:async/zone.dart:1077:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

```
```

``[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-ZW)
    • Flutter version 1.17.5 at /Users/gwinyai/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gwinyai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • SM J710GN • 5203dc4aee0d6391 • android-arm • Android 6.0.1 (API 23)

• No issues found!`
```

</details>

**Comment by darshankawar** [comment]
Hi @gtchax,
As the log states,  `SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`
Can you try solutions mentioned [here](https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil) and see if they work for you ?

**Comment by gtchax** [comment]
Thank you for the response. The problem was caused by another package and a faulty flutter sdk setup on my macbook.

**Comment by PenF00k** [comment]
> Thank you for the response. The problem was caused by another package and a faulty flutter sdk setup on my macbook.

Could you please specify which package caused the issue and how did you solve the 'faulty flutter sdk setup' issue?
I've got the same problem with an old project after updating all dependencies and flutter to 1.20.0.
