### ISSUE TITLE
Support for setting max height on multiline text inputs

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#6271]
Multiline text inputs will expand infinitely as more text is entered. The client should be able to specify a max number of rows (and possible a minimum?), and text should scroll vertically.

**Comment by QoLTech** [comment]
Setting maxLines allows as many lines up to that number, but it also initially starts with that many rows. So, setting maxLines to 5 starts with 5 lines, instead of 1. Is this intended and how can I work around this?
