### ISSUE TITLE
Dart JAVA Interoperability

### ISSUE THREAD

**Issue by ranajit1996** [flutter/flutter#62713]
Platform channel is OK. But Flutter should provide more direct way to use native libs in our project. As we know that there are tons of existing JAVA libs. It'll really help us to switch from native dev to flutter completely.

**Comment by TahaTesser** [comment]
Hi @ranajit1996 
Can you explain the proposal in detail, to me platform channel makes sense of this and also give use some use cases for this feature
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
