### ISSUE TITLE
TextFormField keyboardType is not returning the proper keyboardTypes. Unable to access any special characters.

### ISSUE THREAD

**Issue by samariotorres** [flutter/flutter#62714]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel master, 1.21.0-6.0.pre.141, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.21.0-6.0.pre.141 at /Users/samariotorres/development/flutter
    • Framework revision c748f1a7aa (5 hours ago), 2020-07-31 17:45:18 -0700
    • Engine revision 280bbfc763
    • Dart version 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/samariotorres/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.0
</details>

**Comment by isomdurm** [comment]
same exact issue. is there a workaround? need to fix asap

**Comment by darshankawar** [comment]
Hi @samariotorres,
There's similar ticket describing the case, [62659](https://github.com/flutter/flutter/issues/62659) and a [fix](https://github.com/flutter/engine/pull/20181) was merged. See if this resolves your issue.
