### ISSUE TITLE
[Web] Feature request: Don't include query strings in routes when loading a flutter app from a route URL

### ISSUE THREAD

**Issue by jonaird** [flutter/flutter#62722]
## Use case

To make Flutter web behave more naturally in the context of the browser, it would be desirable for the user to be able to copy and paste url's and for a Flutter app to load in a particular route. We can do this with predefined routes but only if the routes are completely static and don't include any dynamic data. For example, let's say that in a social media app, you have a route '/user' that displays a particular user's profile. In order for these urls to work you would have to predefine routes for every single user for your app i.e. 'user/{userId}'. 

## Proposal

Instead a possible solution would to be able to set query strings at the end of the route. Thus the url for a user could be '/user?id={userId}'. As of Flutter 1.20, if you try to load a URL with query strings, it will treat the whole thing as a route instead of going to the '/user' route.

Perhaps there would be a better solution to this that is being considered...

**Comment by TahaTesser** [comment]
Hi @jonaird 
If i am not mistaken your suggesting support for parameter for routes  
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/48950
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
