### ISSUE TITLE
Support Microsoft Edge for Web Dev

### ISSUE THREAD

**Issue by adeolaex** [flutter/flutter#62721]
## Making Microsoft Edge another option for flutter Web Development.

     Google Chrome is the default web browser for flutter web apps, but it's a known fact that it is RAM hungry and not the best 
     performance wise.

## Proposal

     Since Microsoft Edge uses Chromium (Google Chrome also uses it) from Google, would it be possible to make it available
     for flutter web development. 

     Microsoft Edge also used 5% less resources on some of my performance based test.

**Comment by timsneath** [comment]
It's supported: https://github.com/flutter/flutter/pull/56173

**Comment by adeolaex** [comment]
It's not recognised by flutter doctor on Mac os. Even when passing the flag `flutter run -d edge` , it gives an error. I'm on the latest beta channel and still can't get it to work.

**Comment by timsneath** [comment]
Yeah, we don't support Edge on macOS, only on Windows. I haven't yet seen any data to suggest that's a sizable user population.

**Comment by ShixiangWang** [comment]
> Yeah, we don't support Edge on macOS, only on Windows. I haven't yet seen any data to suggest that's a sizable user population.

It is so sad.

**Comment by cpboyd** [comment]
@timsneath As Edge is still using Chromium underneath, it seems arbitrary that it can't be supported on platforms other than Windows.

There are security and privacy concerns raised by Chrome itself:
https://www.sciencealert.com/a-tech-expert-says-we-should-stop-using-google-chrome
https://www.independent.co.uk/life-style/gadgets-and-tech/google-spying-duckduckgo-privacy-b1817908.html
https://www.forbes.com/sites/zakdoffman/2021/03/20/stop-using-google-chrome-on-apple-iphone-12-pro-max-ipad-and-macbook-pro/

The reason I specifically refuse to install Chrome on my Mac is that the software updater will periodically phone home to Google Analytics, without my explicit consent:
https://superuser.com/questions/730736/how-to-remove-google-software-update-from-mac-osx

**Comment by cpboyd** [comment]
@adeolaex You can do this instead:
```zsh
export CHROME_EXECUTABLE=/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge
flutter run -d chrome
```
