### ISSUE TITLE
Master branch keyboard doesn't display symbols on iOS

### ISSUE THREAD

**Issue by Pebsie** [flutter/flutter#62733]
## Steps to Reproduce

Switch to master, run `flutter upgrade`. Add a `TextFormField` and launch the app in release on iOS.

**Expected results:** A full set of symbols is available when tapping on the 123/symbols button

**Actual results:** A numpad is displayed mimicking the behaviour of `keyboardType: TextInputType.numberWithOptions()` (where before it would display the full set of symbols)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.141, on macOS 11.0 20A5323l, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
 
[✓] Connected device (4 available)            

• No issues found!
```

![WhatsApp Image 2020-08-01 at 18 02 50](https://user-images.githubusercontent.com/5247617/89111226-24027d00-d44b-11ea-9cd9-e7822536ac92.jpeg)
![WhatsApp Image 2020-08-01 at 18 03 19](https://user-images.githubusercontent.com/5247617/89111229-26fd6d80-d44b-11ea-9894-3a2eed6c502e.jpeg)

The widget:
```
  Padding(
                  padding: EdgeInsets.all(10),
                  child: TextFormField(
                    controller: _emailController,
                    decoration: InputDecoration(
                      labelText: "Email Address",
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
```

**Comment by isomdurm** [comment]
this is still a very large issue and one causing a lot of issues from clients. is there a fix for this? Have tried many things, but still ios on iphone does not show punctuation, but it does on ipad and android.

**Comment by isomdurm** [comment]
this came after updating flutter to master branch, same logs as you, same exact issue as yours.

**Comment by darshankawar** [comment]
Hi @Pebsie,
There's similar ticket describing your case, [62659](https://github.com/flutter/flutter/issues/62659) and the [fix](https://github.com/flutter/engine/pull/20181) has been merged. See if this resolves your issue.
