### ISSUE TITLE
Add a sample code in documentation to demonstrate how to use Offstage widget to measure the dimensions. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#62737]
[Docs](https://api.flutter.dev/flutter/widgets/Offstage-class.html) says:

>Offstage can be used to measure the dimensions of a widget without bringing it on screen (yet)

It would be a good idea to show some code snippet on how to do that, here is a question asked on [Stackoverflow](https://stackoverflow.com/q/62355448/12483095)

**Comment by cv692001** [comment]
Hey , I am new to the cotribution can you please help me out with this that how to proceed ?
