### ISSUE TITLE
Tried to automatically register plugins with FlutterEngine but could not find and invoke the GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by simranaswani** [flutter/flutter#62743]
I am trying to run my android app in release mode, but my app shows the error

`Tried to automatically register plugins with FlutterEngine but could not find and invoke the GeneratedPluginRegistrant
`

This is my MainActivity.java -

```
package com.example;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
}
```
My app works properly in debug mode and I am running on Flutter v1.17.5

Flutter doctor -v:

```
(base) Simrans-MacBook-Pro:MoneyLotto-simfinal simranaswani$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.2 19C57, locale en-IN)
    • Flutter version 1.17.4 at /Users/simranaswani/Developer/flutter
    • Framework revision 1ad9baa8b9 (6 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/simranaswani/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Redmi 4 • b4e5b9aa7d04 • android-arm64 • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```

**Comment by setokynet** [comment]
`public class MainActivity extends FlutterActivity {
    @override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        // GeneratedPluginRegistrant.registerWith(flutterEngine);
        super(flutterEngine);

}`

Try this code.

I'm having trouble calling the methods in MethodChannel from Flutter.

**Comment by simranaswani** [comment]
@setokynet  I tried the above method but my app is crashing. 
Could you suggest something else?

**Comment by darshankawar** [comment]
Hi @simranaswani,
Can you try this solution and see if it works for you ? Add below in manifest file.

```
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
```
For more context and info, check [this](https://github.com/flutter/flutter/issues/58113#issuecomment-636833955) link and see if any of the solutions work for you.

**Comment by simranaswani** [comment]
@darshankawar The above lines are already present in my Android Manifest. However the app still crashes

**Comment by darshankawar** [comment]
@simranaswani 
Can you check in `app/build.gradle` if you have `minifyEnabled : true` and if so, try to remove it and see if it works ?

**Comment by simranaswani** [comment]
So I tried removing `minifyEnabled : true`  and the app compiled. However now my apk is 40 mb and will need to add `minifyEnabled back` .  So is there anything I can do?

**Comment by darshankawar** [comment]
@simranaswani,
Can you try to debug `FlutterActivity.java` by adding breakpoints and see where is it trying to register plugins ? Also are you by any chance using any other sdks ? 
Also provide `pubspec.yaml`.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by SunLongbri** [comment]
我也遇到这个问题，按照上面的提示，依然有错误：

我的代码：

 else if ("startWebViewEngine".equals(call.method)) {
            // Instantiate a FlutterEngine.
            FlutterLoader flutterLoader = FlutterInjector.instance().flutterLoader();
            flutterEngine = new FlutterEngine(activity.getApplicationContext());
            flutterChannel = new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), "samples.flutter.dev/webengine");

            DartExecutor.DartEntrypoint dartEntrypoint = new DartExecutor.DartEntrypoint(flutterLoader.findAppBundlePath(), "webViewMain");
            flutterEngine.getDartExecutor().executeDartEntrypoint(
                    dartEntrypoint
            );

            FlutterEngineCache
                    .getInstance()
                    .put("web_engine", flutterEngine);
        } else if ("callNativeWeb".equals(call.method)) {
            String url = call.argument("url");
            String menuID = call.argument("menuID");
            HashMap hashMap = new HashMap();
            hashMap.put("url", url);
            hashMap.put("menuID", menuID);
            activity.startActivity(
                    FlutterActivity
                            .withCachedEngine("web_engine")
                            .build(activity)
            );

            flutterChannel.invokeMethod("urlFromNatie", hashMap);
        }

我打过断点，错误点在于无法找到用到的插件，打开一个Container倒是可以。
