### ISSUE TITLE
DataTable uses the sort arrow opposing the material spec

### ISSUE THREAD

**Issue by Wikiwix** [flutter/flutter#62745]
The [DataTable Widget](https://api.flutter.dev/flutter/material/DataTable-class.html) uses a downward arrow to show that a column is sorted ascending and an upward arrow for descendingly sorted columns. This is opposing the [Material Specification](https://material.io/components/data-tables#anatomy:~:text=Sorting%20by%20the%20schedule%20column%20in%20ascending%20order%20is%20indicated%20with%20an%20upward%20arrow.)

Somewhat relates to #56204.

**Comment by markusaksli-nc** [comment]
Closing this since https://github.com/flutter/flutter/pull/62795 was merged. @Wikiwix For future reference you can write `Fixes #62745` in the "Related issues" section of your PR and GitHub will automatically close the issue you are fixing when it gets merged.
