### ISSUE TITLE
While [flutter build web] for basic project rised to Unsupported operation:    Cannot extract a file path from a URI with a fragment component Error: No 'main' method found.

### ISSUE THREAD

**Issue by sanjaysanju618** [flutter/flutter#62740]
Target dart2js failed: Exception: Error: Error when reading
'file:///F:/PROJECT/#Flutter/Aqua%20App/aqua_app/.dart_tool/flutter_build/1aabd1e7ce6cf2c637259bec2a824503/main.dart': Unsupported operation:   
Cannot extract a file path from a URI with a fragment component
Error: No 'main' method found.
Error: Compilation failed.

Compiling lib\main.dart for the Web...                             0.6s 
Exception: Failed to compile application for the Web.

**Comment by TahaTesser** [comment]
Hi @sanjaysanju618 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by sanjaysanju618** [comment]
Thanking you Mr. @TahaTesser for your involvement in this issue. I have found the issue and it is on my side, that is my file name for the flutter is start with **#** its leads to **_Cannot extract a file path from a URI issue _** 

'file:///F:/PROJECT/ **#** Flutter/Aqua%20App/aqua_app/.dart_tool/flutter_build/1aabd1e7ce6cf2c637259bec2a824503/main.dart'

**Comment by jamilxt** [comment]
**TROUBLESHOOT**
If you are facing this issue, 
make sure - you got no '#' character inside of your project's FILE PATH.
