### ISSUE TITLE
Text Field is not allowing me to access special characters

### ISSUE THREAD

**Issue by antmyers** [flutter/flutter#62756]
## Steps to Reproduce

1. Create a simple app with a text field like so:

Padding(
              padding: const EdgeInsets.all(25.0),
              child: TextField(
                keyboardType: TextInputType.emailAddress,
                autocorrect: false,
                controller: _emailController,
                decoration: InputDecoration(
                    labelText: 'Email',
                    labelStyle: TextStyle(
                        color: Colors.black : Colors.grey)),
              ),
            ),

**Expected results:**
When I click on the text field, I need my users to access the special characters, particularly to enter in an email address.

**Actual results:** When I hit the "123" button in the bottom left of the keyboard, it takes me to just numbers. Going back to "ABC." No matter what keyboard I use it looks exactly the same. See attached screen recording.

Please help because without this users are not able to create new accounts on my app

![Hnet-image](https://user-images.githubusercontent.com/44888349/89129968-843b0280-d4cf-11ea-980b-74ba8c6f0eb0.gif)

**Comment by isomdurm** [comment]
Please is there a workaround for this? Need to fix asap and ive tried setting keyboard types to no avail on iphones. help

**Comment by darshankawar** [comment]
Hi @antmyers,
There was similar ticket describing your case, [62659](https://github.com/flutter/flutter/issues/62659) and a [fix](https://github.com/flutter/engine/pull/20181) was merged too.  See if the fix resolves your issue.
Thanks.

**Comment by antmyers** [comment]
This fixed it! Thank you for the quick response :]
