### ISSUE TITLE
Aspects of an InheritedModel are not reset before a dependant widget rebuilds

### ISSUE THREAD

**Issue by Quijx** [flutter/flutter#62753]
When a widget depends on an `InheritedModel`, an `aspect` is passed to `InheritedModel.inheritFrom` to define on which part of the `InheritedModel` the dependant depends. These aspects are saved in the `Map<Element, Object> _dependents` in the `InheritedElement`. In the case of the sublass `InheritedModelElement<T>`, the `Object` value is a `HashSet<T>()` that contains the aspects of type `T`.

Before the dependant widget rebuilds for any reason, the aspects of that dependant should be cleared, because otherwise the widget will be rebuilt if an aspect of the `InheritedModel` changes that the dependant widget no longer depends on. However this does not seem to be the case.

Also if there are potentially many aspect objects or the aspect object does not override `==` and `hashCode` and are instantiated in the `build` method, these aspect objects accumulate, which could lead to memory issues or performance problems if the widget gets rebuild often and the app runs for a long time.

The following gif shows this problem in action:
Notice the following:
- At first the colored bottom widget only rebuilds (indicated by color change) if the value of "A" changes, but not when "B" changes.
- After switching to display "B", it rebuilds if either "A" or "B" are change, because the dependency on the "A" variable is not removed correctly.
- The number of saved aspects (on the console to the left) rises each time the widget rebuilds.

The demo from the gif can also be testet here: https://dartpad.dev/eebb7b848ddc60102b62b203e6bdb698
![output](https://user-images.githubusercontent.com/48153628/89126585-f2d78a80-d4e6-11ea-9eb0-dccfcf60cb4c.gif)

## Steps to Reproduce

1. Run `flutter create bug`. (Or directly check demo at https://dartpad.dev/eebb7b848ddc60102b62b203e6bdb698 and continue at step 3.)
2. Replace the code in `lib/main.dart` with the content of the following gist: https://gist.github.com/Quijx/eebb7b848ddc60102b62b203e6bdb698
3. Run the app
4. Tap the "Increase A" button.
    - The value of "A" changes on the very top.
    - The colored `Dependant` widget rebuilds (indicated by color change) and the displayed value of "A" us updated.
5. Tap the "Increase B" button.
    - The value of "B" changes on the very top.
    - The `Dependant` does *not* rebuild (no color change) because it does not depend on "B". So far correct.
6. Tap the "Display B" button.
    - The colored `Dependant` now rebuilds and displays "B".
7. Tap the "Increase B" button.
    - The value of "B" changes on the very top.
    - As expected the `Dependant` now rebuilds and displays the new value of "B".
8. Tap the "Increase A" button.
    - The value of "A" changes on the very top.
    - The `Dependant` widget rebuilds (color changes) even though it does not depend on "A".
    - The last console output is `Number of saved aspects: 4` because `Dependant` was rebuilt 4 times.
9. Tap the "Rebuild" button 10 times.
    - The `Dependant` widget rebuilds 10 times.
    - No new console output appear because the print method to display the number of saved aspects is only called when the `InheritedModel` changes.
10. Tap the "Increase B" button.
    - The last console output is `Number of saved aspects: 15`. (4 from before + 10 rebuilds + 1 rebuild because "B" increased). 

**Expected results:** 
In step 8 the `Dependant` widget should not rebuild because it no longer depends on "A".
All console outputs should be `Number of saved aspects: 1` because the `Dependant` widget only ever depends on one aspect of the `InheritedModel` at a time.

**Actual results:** 
In step 8 the `Dependant` widget rebuild even though it no longer depends on "A".
Any time the `Dependant` widget rebuilds, the number of aspects increases, which could lead to memory or performance problems depending on the exact circumstances.

<details>
  <summary>Logs</summary>

**Output from the "Steps to Reproduce"**
```
[+7273 ms] I/flutter (26012): Number of saved aspects: 1
[+1712 ms] I/flutter (26012): Number of saved aspects: 2
[+3327 ms] I/flutter (26012): Number of saved aspects: 3
[+1328 ms] I/flutter (26012): Number of saved aspects: 4
[+35539 ms] I/flutter (26012): Number of saved aspects: 15
```

**Output of `flutter analyze`**
```
Analyzing inherited_model_bug...                                        
No issues found! (ran in 1.2s)
```

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.141, on Linux, locale en_DE.UTF-8)
    • Flutter version 1.21.0-6.0.pre.141 at /home/quijx/Documents/System/libs/flutter
    • Framework revision c748f1a7aa (2 days ago), 2020-07-31 17:45:18 -0700
    • Engine revision 280bbfc763
    • Dart version 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/quijx/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /opt/JetBrains/apps/AndroidStudio/ch-0/191.5791312/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0
    • cmake version 3.18.0
    • ninja version 1.10.0
    • pkg-config version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/JetBrains/apps/AndroidStudio/ch-0/191.5791312
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/JetBrains/apps/AndroidStudio/ch-0/183.5692245
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/JetBrains/apps/IDEA-C/ch-0/192.6817.14
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[✓] Connected device (4 available)
    • Moto G 5 Plus (mobile) • ZY22459Q48 • android-arm    • Android 8.1.0 (API 27)
    • Linux (desktop)        • linux      • linux-x64      • Linux
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    ),
  );
}

/// A widget that contains two values (`_a` and `_b`) in its state.
/// It has a button for each variable to increase it.
/// Both values are provided to a [Dependant] widget via an [ABModel] that
/// extends [InheritedModel].
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _a = 0;
  int _b = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('InheritedModel Bug'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'A: $_a, B: $_b',
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            RaisedButton(
              onPressed: () => setState(() => _a++),
              child: const Text('Increase A'),
            ),
            RaisedButton(
              onPressed: () => setState(() => _b++),
              child: const Text('Increase B'),
            ),
            ABModel(
              a: _a,
              b: _b,
              // The `const` is important, because the [Dependant] should not
              // automatically rebuild if this widget rebuilds.
              child: const Dependant(),
            ),
          ],
        ),
      ),
    );
  }
}

/// A function type that extracts an [int] value from an [ABModel].
typedef GetInt = int Function(ABModel abModel);

/// An [InheritedModel] that keeps two ints calls [a] and [b]. The aspects are
/// of type [GetInt].
class ABModel extends InheritedModel<GetInt> {
  const ABModel({this.a, this.b, Widget child}) : super(child: child);

  final int a;
  final int b;

  static int of(BuildContext context, GetInt aspect) {
    final abModel =
        InheritedModel.inheritFrom<ABModel>(context, aspect: aspect);
    return aspect(abModel);
  }

  @override
  bool updateShouldNotify(ABModel oldWidget) {
    return a != oldWidget.a || b != oldWidget.b;
  }

  @override
  bool updateShouldNotifyDependent(
    ABModel oldWidget,
    Set<GetInt> dependencies,
  ) {
    debugPrint('Number of saved aspects: ${dependencies.length}');
    for (final d in dependencies) {
      if (d(this) != d(oldWidget)) {
        return true;
      }
    }
    return false;
  }
}

/// A widget that depends on the [ABModel]. It either displays A or B depending
/// on the state.
class Dependant extends StatefulWidget {
  const Dependant();

  @override
  _DependantState createState() => _DependantState();
}

class _DependantState extends State<Dependant> {
  /// If `true`, A is displayed. If `false`, B is displayed.
  bool _showA = true;

  final _rand = Random();

  @override
  Widget build(BuildContext context) {
    int val;
    // Depend on the [ABModel] with either a function that extracts [a] or a
    // function that extracts [b] from the [ABModel] depending on [_showA].
    if (_showA) {
      val = ABModel.of(context, (abModel) => abModel.a);
    } else {
      val = ABModel.of(context, (abModel) => abModel.b);
    }
    return Container(
      // Use a new random color on each rebuild to see when a rebuild is
      // happening.
      color: HSVColor.fromAHSV(1, _rand.nextDouble() * 306, 0.5, 1).toColor(),
      padding: const EdgeInsets.all(8),
      child: Column(
        children: [
          Text(
            '${_showA ? 'A' : 'B'}: $val',
            style: const TextStyle(fontWeight: FontWeight.bold),
          ),
          RaisedButton(
            onPressed: () => setState(() => _showA = !_showA),
            child: Text('Display ${_showA ? 'B' : 'A'}'),
          ),
          RaisedButton(
            onPressed: () => setState(() {}),
            child: const Text('Rebuild'),
          ),
        ],
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.142, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-6.0.pre.142 at /home/taha/Code/flutter_master
    • Framework revision d261f1ef58 (8 hours ago), 2020-08-03 00:59:36 -0400
    • Engine revision 083282e33b
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 365525432a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!

```

</details>

**Comment by Quijx** [comment]
I just did a bit more testing and found out that this bug is also present for `InheritedWidget`s.

Now i see that for `InherritedModel`s, this bug is not a big problem for most people because not many use `InherritedModel` in the first place and even fewer change what aspect they depend on.

However `InheritedWidget` is used everywhere and it is not uncommon to see cases where either one subtree or another is build depending on some state. And if one subtree depends on some `InheritedWidget`, the widget will always rebuild if the `InheritedWidget` changes, even if that subtree is no longer shown. This probably leads to fequent unnecessary rebuilds in many applications.

I have made another demo here: https://dartpad.dev/6aa4206628af8542fb6e0173fe38c0ed

@TahaTesser should I file a new issue for the `InheritedWidget` case, or adapt this one?

**Comment by TahaTesser** [comment]
@Quijx 
Sure, go ahead

**Comment by Quijx** [comment]
Is there any timeline for when this could be fixed?
I've been woking with a locally modified flutter since creating this issue where I just inserted 
```dart
for (final InheritedElement dep in _dependencies ?? Iterable.empty()) {
    dep._dependents.remove(this);
}
_dependencies?.clear();
```
before
https://github.com/flutter/flutter/blob/81142c1f9a18df456b3b147a45cd5971e58014ec/packages/flutter/lib/src/widgets/framework.dart#L4311
. Seems to work so far, but I'm not sure if this is the correct fix or if it has undesirable side effects.

This bug (or more specifically #62753) is relevant to me, because I'm writing a redux-like State management, where I want to do something like the following to depend on parts of an immutable state:
```dart
class UsernameText extends StatelessWidget {
  const UsernameText({Key? key, required this.id}) : super(key: key);

  final int id;

  @override
  Widget build(BuildContext context) {
    final String username = StoreProvider.watch<MyState, String>(
      context,
      (state) => state.users[id].name,
    );
    return Text(username);
  }
}
```

The `watch` function uses `InheritedModel.inheritFrom` internally with the function passed in the second argument as the aspect.

Since the lambda is a different object on every rebuild and the dependencies are never cleared, the aspects accumulate for every build. (Also it breaks an optimization that could otheriwse be made where some evaluations of the function can be cached, but I won't get into that now.)

**Comment by goderbauer** [comment]
There is some more context on why the behavior is this way in https://github.com/flutter/flutter/issues/12992#issuecomment-344358873. That issue also covers updating the docs to make this clearer. I am going to close this issue in favor of the other one.
