### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/user/Desktop/Flutter/bubulearn-flutter/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by Dersh** [flutter/flutter#62754]
## Command
```
flutter build apk
```

## Steps to Reproduce
just running the build using the terminal.

## Logs
ProcessException: Operation not permitted Command: /Users/user/Desktop/Flutter/bubulearn-flutter/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel master, 1.20.0-7.0.pre, on Mac OS X 10.15.5 19F101, locale ru-RU)
    • Flutter version 1.20.0-7.0.pre at /Users/user/dev/sdk/flutter
    • Framework revision 462b0ea76e (4 weeks ago), 2020-07-02 16:13:02 -0400
    • Engine revision 51ca1432b3
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • A64ED275-18FE-44E8-865C-67B2648A24EE • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.5+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
agora_rtc_engine-1.0.13
agora_rtm-0.9.12
backendless_sdk-1.1.8
firebase_crashlytics-0.1.4+1
firebase_messaging-6.0.16
firebase_remote_config-0.3.1+1
flutter_plugin_android_lifecycle-1.0.8
image_picker-0.6.7+4
package_info-0.4.1
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
permission_handler-5.0.1+1
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2
wakelock-0.1.4+2

**Comment by Dersh** [comment]
Solved by [android] folder removal and restoring it back from repository (git)

**Comment by anaman9** [comment]
create a new project..
just replace gradlew file from new project to old project..

and just boom.
