### ISSUE TITLE
Android system back button not working

### ISSUE THREAD

**Issue by CaLouro** [flutter/flutter#62766]
Today I realized that my app wasn't responding to Android's system back button. This was seen on both debug and release builds, and in 2 real devices and an emulator. I searched the internet and couldn't find an answer.

And I did some testing too. Using the WillPopScope widget I confirmed that it was registering the actions from the appbar's back button (in app) normally, but no sign of the system wide back button. Keeping in mind that I haven't been fidgeting with these kind of functionalities recently I kept wondering if the problem was with my code, so I created an brand new and fresh project and the problem persisted, both on emulator and physical device.

This problem, after all, did never thrown any error or anything suspicious on the debug console. Another thing to add is that the other buttons (the 'home' and the 'recent apps') kept working fine.

## Steps to Reproduce

1. Create a new Flutter project (I used Android Studio's interface all standard options)
2. No files were updated or changed.
3. Ran on debug on emulator (SDK: "Target: google_apis_playstore [Google Play] (API level 30)") and real device (Galaxy S9+ Android 10).

**Expected results:** 
The back button to work as intended by every other app.

**Actual results:** 
It didn't work. 
;-;

**Comment by mnazim** [comment]
@CaLouro Are you on `master` channel? System back is not working on  `master 1.21.0-6.0.pre.141` currently.

```

```

**Comment by vegidio** [comment]
This started to happen to me since yesterday after I upgraded to latest version in the master branch. The back button was working before the upgrade so I assume it's a bug in the latest version.

**Comment by DJafari** [comment]
run `flutter upgrade` on channel `master`, in the `1.21.0-6.0.pre.142` version this bug solved

**Comment by pedromassangocode** [comment]
I @CaLouro 
I can't reproduce this on latest `master` channel.
Can you upgrade and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> Complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.teal,
        canvasColor: Colors.transparent,
      ),
      home: Scaffold(),
    );
  }
}

```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.142, on Mac OS X 10.15.6 19G73,
    locale en)
    • Flutter version 1.21.0-6.0.pre.142 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision d261f1ef58 (5 hours ago), 2020-08-03 00:59:36 -0400
    • Engine revision 083282e33b
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 365525432a)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by vegidio** [comment]
It's working again after the upgrade, with Flutter 1.21.0-6.0.pre.142 • channel master

**Comment by CaLouro** [comment]
I was on `master 1.21.0-6.0.pre.141`. Just ran an upgrade and things are back to normal. Thanks everyone.

**Comment by NiranjanShah** [comment]
it is not working with below environment 

[✓] Flutter (Channel master, 1.22.0-2.0.pre.162, on Mac OS X 10.15.6 19G2021, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
[✓] VS Code (version 1.43.0)

**Comment by z85510** [comment]
I've same problem after upgrading to 1.22.0-10.0.pre.65
Sometimes it works but I don't know why and most of time it doesn't work

Should I downgrade or a new version will release soon?

**Comment by CaLouro** [comment]
@z85510 Hey, check if your Flutter is not on the master branch. I recommend not using it since it's prone to this types of bugs. If you use the stable branch, it shouldn't have this bug.
