### ISSUE TITLE
TimePicker is not correct in RTL languages 

### ISSUE THREAD

**Issue by omidh28** [flutter/flutter#62775]
![timerpicker_bug](https://user-images.githubusercontent.com/11672360/89156295-ad1ad080-d57f-11ea-9691-35a64791f495.png)

To reproduce, Set app locale to a right-to-left language (`fa` for example) then open timepicker.

Besides that "Select Time" which not translated, Why is that the time of day format is in `mm:hh` format instead of `hh:mm`? 

RTL doesn't mean everything should be written right to left, Those languages still use `hh:mm` for time format. 
Also it wasn't an issue in previous TimePicker widget.

**Flutter Doctor**
[√] Flutter (Channel beta, 1.20.0-7.3.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (4 available)

**Comment by darshankawar** [comment]
Issue replicable on latest dev channel.

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: [Locale('fa')],
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: FlatButton(
              color: Colors.red.shade200,
              child: Text('Show time picker'),
              onPressed: () {
                showTimePicker(
                  context: context,
                  initialTime: TimeOfDay.fromDateTime(
                    DateTime(2020, 7, 28, 19, 3),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by HansMuller** [comment]
CC @rami-a @darrenaustin

**Comment by rami-a** [comment]
Looks like you are correct, I have created a fix for this in https://github.com/flutter/flutter/pull/62803
