### ISSUE TITLE
[in_app_purchase] `PurchaseParam#sandboxTesting` is not used to switch iOS sandbox environment

### ISSUE THREAD

**Issue by oboenikui** [flutter/flutter#62779]
## Steps to Reproduce

I'm using in_app_purchase plugin version 0.3.4+3, and I notice that `PurchaseParam` has a confusing param.

sample code:

```dart
final PurchaseParam purchaseParam = PurchaseParam(
  productDetails: productDetails,
  sandboxTesting: true,
);
await InAppPurchaseConnection.instance
    .buyNonConsumable(purchaseParam: purchaseParam);
```

`PurchaseParam` has `sandboxTesting` param. [This document](https://github.com/flutter/plugins/blob/939b9a6f00367238131ad8dcc8b704f4e3e5ba26/packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart#L97) says:

> The 'sandboxTesting' is only available on iOS, set it to `true` for testing in AppStore's sandbox environment. The default value is `false`.

But this explanation seems to be wrong. In fact, it is only used to test [Ask to Buy](https://support.apple.com/en-us/HT201089) feature.

```dart
    await _skPaymentQueueWrapper.addPayment(SKPaymentWrapper(
        productIdentifier: purchaseParam.productDetails.id,
        quantity: 1,
        applicationUsername: purchaseParam.applicationUserName,
        simulatesAskToBuyInSandbox: purchaseParam.sandboxTesting,
        requestData: null));
```
https://github.com/flutter/plugins/blob/939b9a6f00367238131ad8dcc8b704f4e3e5ba26/packages/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart#L52

Furthermore, `simulatesAskToBuyInSandbox` isn't actually used because of typo.

```dart
    payment.simulatesAskToBuyInSandbox =
        [[paymentMap objectForKey:@"simulatesAskToBuyInSandBox"] boolValue];
```
https://github.com/flutter/plugins/blob/f903d4cf0342b894e44143b02d993bf298b8abe4/packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m#L182-L183

Correct key is `simulatesAskToBuyInSandbox`, but actual is `simulatesAskToBuyInSandBox`.

**Expected results:** 

`sandboxTesting` is used to switch sandbox environment.

**Actual results:**

`sandboxTesting` is used to switch "Ask to Buy" feature, and furthermore, it is not working.

To switch sandbox environment, switch provisioning profile. This seems to be an iOS specification, so there seems to be no way to change it.

**Comment by alexlovar** [comment]
Hi @oboenikui, i trying to implementing this plugin in my app, one month ago this work but now is asking for parents permissions.
 could you please help me to fix my code to works again?
i'm adding the lines:

**Comment by oboenikui** [comment]
@alexlovar You mean that you don't want to test "Ask to Buy" feature, right?
If you set `true` to `sandboxTesting` parameter, the transaction simulates "Ask to Buy" feature.
So set `false` like:

```
final PurchaseParam purchaseParam = PurchaseParam(
  productDetails: productDetails,
  sandboxTesting: false, // or delete this line
);
await InAppPurchaseConnection.instance
    .buyNonConsumable(purchaseParam: purchaseParam);
```

Regardless of the value of `sandboxTesting`, you will actually be connected to Sandbox environment unless your app is released to the App Store.

**Comment by alexlovar** [comment]
thanks @oboenikui .
i'm using the sample files buyapp.dart from this repository. i can't find the way to set the params in the sample
i'm using the sample files buyapp.dart from this repository.
i'm adding the lines in the void _listenToPurchaseUpdated(List purchaseDetailsList) line 415 from buyapp.dart sample file.

**Comment by oboenikui** [comment]
You need to use `PurchaseParam` with `buyNonConsumable` method.
For more details, see `main.dart` of in_app_purchase example.

https://github.com/flutter/plugins/blob/d82940f02fc306707cce66e4e7111c0bc6ca6fc6/packages/in_app_purchase/example/lib/main.dart#L256
