### ISSUE TITLE
Flutter WebView within ListView or CustomScrollView - Crashes on Android for large heights

### ISSUE THREAD

**Issue by DFelten** [flutter/flutter#62784]
Currently we've got a problem with the Flutter WebView within a ScrollView. We would like to display a WebView with article content written in HTML below an Image and other content like the title or buttons. It shouldn't be possible to just scroll the WebView. Instead, the entire content should be scrolled together.

The problem is, that the WebView should scroll together with the header. Therefore the WebView needs a fixed height as far as I know. Via Javascript it's possible to get the scroll height of the WebView. This is great working on iOS, but on Android the App is crashing when the height of the WebView is too large. The reason for this seems to be that under Android the height of the WebView may only be as large as the screen. Otherwise there is a warning message:

> Creating a virtual display of size: [1080, 11303] may result in
> problems(https://github.com/flutter/flutter/issues/2897).It is larger
> than the device screen size: [1080, 1794].

Is there a better possibility to use a WebView inside a ListView? We also tried [flutter_html][1], but on some articles we also need JavaScript and this is not supported. On large pages it's also a bit laggy.

## Steps to Reproduce

1. Checkout flutter project from [GitHub](https://github.com/DFelten/flutter_webview_in_scrollview) or use the example code below.
2. `flutter run` with Android device or simulator
3. When there is no crash, set the height for example to a value like 13000. This is a realistic value since it's possbile that the articles are long.

**Expected results:** 

WebView is working like on iOS within the ListView. Scoll the WebView together with the Flutter widgets should be possible.

**Actual results:** 

App is crashing on Android and even sometimes soft reboot the device.

<details>
  <summary>Logs</summary>

Full log is attached in the log.txt:

[log.txt](https://github.com/flutter/flutter/files/5016015/log.txt)

flutter run log:
```
Launching lib/main.dart on SM A520F in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1,7s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device SM A520F...                                331ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on SM A520F is available at: http://127.0.0.1:58676/0qox6geqRgo=/
W/PlatformViewsController(20730): Creating a virtual display of size: [1080, 39000] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 1920].
V/Surface (20730): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/WebViewFactory(20730): Loading com.android.chrome version 84.0.4147.111 (code 414711173)
I/zygote64(20730): no shared libraies, dex_files: 1
I/cr_LibraryLoader(20730): Loaded native library version number "84.0.4147.111"
I/cr_CachingUmaRecorder(20730): Flushed 5 samples from 5 histograms.
W/ResourceType(20730): Failure getting entry for 0x7f130582 (t=18 e=1410) (error -2147483647)
D/ConnectivityManager(20730): requestNetwork; CallingUid : 10202, CallingPid : 20730
W/cr_media(20730): Requires BLUETOOTH permission
D/ViewRootImpl@39d1500[MainActivity](20730): setView = DecorView@4482139[] TM=true MM=false
V/InputMethodManager(20730): Not IME target window, ignoring
D/NetworkSecurityConfig(20730): No Network Security Config specified, using platform default
D/ViewRootImpl@39d1500[MainActivity](20730): dispatchAttachedToWindow
Lost connection to device.
```

```
```

```
```

</details>

## Example code

This is an example App of the current problem. It works for small pages, but not for large ones. The height when it crashes depends on the device. You could for example set the height manually to a value like 13000:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: CrashingWebViewExample()));

class CrashingWebViewExample extends StatefulWidget {
  @override
  _CrashingWebViewExampleState createState() => _CrashingWebViewExampleState();
}

class _CrashingWebViewExampleState extends State<CrashingWebViewExample> {
  WebViewController _webViewController;
  double _webViewHeight = 1;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(height: 100, color: Colors.green),
          Container(
            height: _webViewHeight,
            child: WebView(
              initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
              javascriptMode: JavascriptMode.unrestricted,
              onPageFinished: (String url) => _onPageFinished(context, url),
              onWebViewCreated: (controller) async {
                _webViewController = controller;
              },
            ),
          ),
          Container(height: 100, color: Colors.yellow),
        ],
      ),
    );
  }

  Future<void> _onPageFinished(BuildContext context, String url) async {
    double newHeight = double.parse(
      await _webViewController.evaluateJavascript("document.documentElement.scrollHeight;"),
    );
    setState(() {
      _webViewHeight = newHeight;
    });
  }
}
```

The code is also available [on GitHub][2].

  [1]: https://pub.dev/packages/flutter_html
  [2]: https://github.com/DFelten/flutter_webview_in_scrollview

**Comment by TahaTesser** [comment]
Hi @DFelten
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/45243
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
