### ISSUE TITLE
Unable to run flutter app

### ISSUE THREAD

**Issue by mrfoxie** [flutter/flutter#62782]
![image](https://user-images.githubusercontent.com/25217451/89175538-925b5280-d5a5-11ea-87d0-075d5d4424db.png)
when i tried to run flutter app it showed me this error and not aslo even that i cant run my old apps too

**Comment by pedromassangocode** [comment]
Looks like you don't have Java JDK installed. Please follow the steps at https://flutter.dev/docs/get-started/install/windows and make sure you have java [JDK](https://www.oracle.com/java/technologies/javase-jdk14-downloads.html) installed.

Closing as this has nothing to do with Flutter. If you disagree please comment bellow.
Thank you

**Comment by mrfoxie** [comment]
thank you very much
