### ISSUE TITLE
Cocoon failing to add commits with long commit msgs

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#62789]
While trying to insert the datastore record for https://github.com/flutter/flutter/commit/d261f1ef584dc9b233e4e46102e2f83dbe21ad78:

```
Failed to add commit d261f1ef584dc9b233e4e46102e2f83dbe21ad78: ApplicationError: The value of property "Commit.Message" is longer than 1500 bytes.
```

**Comment by tvolkert** [comment]
@godofredoc assigned to you to triage / delegate

**Comment by tvolkert** [comment]
What's curious is that the commit message of d261f1e is shorter than that of f06ee8d, yet the latter succeeded...

**Comment by tvolkert** [comment]
It looks like the row got added to the datastore.  Did something get unblocked, or was it manually inserted?

**Comment by godofredoc** [comment]
I landed a new version with my fix, sending the PR

**Comment by tvolkert** [comment]
It turns out this affected flutter/flutter@f06ee8d as well - the commit was skipped in the dashboard due to this bug.
