### ISSUE TITLE
updating the dart SDK to 2.10+ version

### ISSUE THREAD

**Issue by Faiizii** [flutter/flutter#62790]
## Steps to Reproduce

1. Run the command choco upgrade dart-sdk --pre ( and in result it is showed me 2.10+ version installed)
2. But running flutter --version not showing me the updated version (yes directory has been created)

## Logs

C:\Users\user_name>choco -v
0.10.15

C:\Users\user_name>choco upgrade dart-sdk --pre
Chocolatey v0.10.15
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.

 Do you want to continue?([Y]es/[N]o): y

Upgrading the following packages:
dart-sdk
By upgrading you accept licenses for the packages.
dart-sdk v2.10.0.2-c-000-dev is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\Users\user_name>flutter --version
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (3 weeks ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```
```

C:\Users\user_name>flutter doctor -v
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.21.0-1.0.pre at C:\flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user_name\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.47.3)
    • VS Code at C:\Users\user_name\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```

**Comment by jonahwilliams** [comment]
Flutter is built with a particular Dart SDK, and can only be used with a given version of that SDK.

**Comment by Faiizii** [comment]
ok, but  in documentation, i did not find this sentence **can only be used with a given version of that SDK** (May be I missed it). In documentation of [Get the Dart SDK](https://dart.dev/get-dart), Dev channel: pre-releases uses currently 2.10.0-2.0.dev version. As you can see, I have the latest dev channel pre-releases flutter SDK version ** Flutter version 1.21.0-1.0.pre**, but it has Dart SDK v2.9.0. 
So according to you ** can only be used with a given version of that SDK**, how can I switch to 2.10 version of Dart?

**Comment by mustufaalighiya** [comment]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...


===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF748943B22
version=2.13.0-77.0.dev (dev) (Thu Feb 25 00:41:11 2021 -0800) on "windows_x64"
pid=4452, thread=6444, isolate_group=main(000001E249FCA410), isolate=main(000001E249FCF090)
isolate_instructions=1e248c00000, vm_instructions=7ff74886fa30
Stack dump aborted because InitialRegisterCheck failed.
the Dart compiler exited unexpectedly.
