### ISSUE TITLE
flutter tool not recognizing iPhone device name

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6279]
Maybe because my iPhone is running iOS 10 ?

![screen shot 2016-10-11 at 4 54 45 pm](https://cloud.githubusercontent.com/assets/5479/19292790/99c26282-8fd3-11e6-8185-fea573af7aaf.png)

Notice the blank name before the dot for the iOS device.

**Comment by eseidelGoogle** [comment]
Correct.  And your imobiledevice version is too old.  @cbracken knows more.  I thought we made `flutter doctor` detect this?  @danrubel

**Comment by sethladd** [comment]
My flutter is 5 days old, I think. I can try upgrading and rerunning `flutter devices`.

**Comment by raju-bitter** [comment]
I see the same on my machine:

`
> flutter run
More than one device connected; please specify a device with the '-d <deviceId>' flag.

SM N920S • 05157df5d93b793d                         • android-arm
         • ba9c0b7bb6175f61268fb99ed496f5bdf5417566 • ios
`
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/raju/dev/flutter
    • Framework revision 6777766d2d (12 hours ago), 2016-10-11 15:51:35
    • Engine revision e8d046e9e2
    • Tools Dart version 1.20.0-dev.10.2

**Comment by danrubel** [comment]
I'm seeing this with my iOS 9.x iPod Touch. Running `flutter doctor` shows 
```
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x libimobiledevice is incompatible with the installed XCode version. To update, run:
      brew uninstall libimobiledevice
      brew install --HEAD libimobiledevice
```
after following the `flutter doctor` instructions above, running it again, I shows
```
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
```
Now, `flutter devices` correctly shows the name of the connected iOS 9.x device.

**Comment by danrubel** [comment]
Same problem, warning, and fix with my iOS 9.x iPod Touch and XCode 8.x.

**Comment by cbracken** [comment]
Correct, yep I landed the doctor fix in #6111.

**Comment by danrubel** [comment]
@cbracken Thank you!
@sethladd Is this working for you? Issue fixed?

**Comment by sethladd** [comment]
Hm, doesn't look fixed?

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter devices
2 connected devices:

Moto G 4 • ZY223GJDRL                               • android-arm
         • ff369dfd5f4a80545a431441c1e3066f8cb8d759 • ios
~/Code/flutter/examples/flutter_gallery[master*] $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 2805e5f8b8 (26 minutes ago) • 2016-10-12 09:41:35
Engine • revision e8d046e9e2
Tools • Dart 1.20.0-dev.10.2
```

**Comment by raju-bitter** [comment]
Solved the problem for me. Two iOS devices connected, shows name of both of them.
```
flutter run
More than one device connected; please specify a device with the '-d <deviceId>' flag.

Paddington • 7ede958c9d7faa47c7965b41405ff7df107735eb • ios
Shiva      • ba9c0b7bb6175f61268fb99ed496f5bdf5417566 • ios
```

**Comment by sethladd** [comment]
Sorry, I only ran `flutter upgrade`, which I was expecting to fully upgrade my system.

After I manually ran the homebrew commands (which, flutter doctor nicely tells me :) I see this output:

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter devices
2 connected devices:

Moto G 4 • ZY223GJDRL                               • android-arm
iPhone   • ff369dfd5f4a80545a431441c1e3066f8cb8d759 • ios
```

Woot!

Thanks for the help :)

**Comment by rbucker** [comment]
I know this issue is closed but it never provided a reliable explanation or fix.... Currently I have the same problem...  Macbook Air 2019 with 2 USB-C ports. While my USB-C will not identify my Moto G6 when plugged in the USB-C but if I use a USB-A/C dongle it connects... and no matter what I connect with the iPhone will not connect to flutter. HOWEVER on my 2012 MBA the iPhone worked ONLY if I launched iTunes first.

**Comment by eseidelGoogle** [comment]
This issue was closed 3 years ago. :)  It's very possible that the issue you're encountering is new/different.  Would you be willing to file a new bug @rbucker?

**Comment by rbucker** [comment]
https://github.com/flutter/flutter/issues/41022
