### ISSUE TITLE
Square in text input field after tapping +

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#628]
![img_20151130_122536](https://cloud.githubusercontent.com/assets/5479/11483535/b43731fc-975d-11e5-8a34-6e478ff1ba80.jpg)

After I tap the + FAB, I see a text input pop up. Inside, I see a square on top of the text "Company Name".

Also, fwiw, typing in this input does not seem to do anything or return results.

**Comment by sethladd** [comment]
cc @jason-simmons @eseidel

**Comment by abarth** [comment]
The character is a zero-width space U+200B.  Maybe there's no glyph for that in the font we're using on iOS?  I wonder if we should be using Roboto on iOS...

**Comment by chinmaygarde** [comment]
We no longer seem to be using that non printing character. Can mark this ticket as fixed. But we still need better fallback.
