### ISSUE TITLE
luci sdk tasks are running twice

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62808]
For every commit we are running the same task twice, this has impacted our capacity usage since the sdk repo was enabled on luci.

The reason for this is that we enabled the app but we didn't disable the webhook meaning that every time there is a new commit the webhook api gets called twice: one for the web_hook configuration and one for the github app.

\cc. @keyonghan

**Comment by kf6gpe** [comment]
After talking with @godofredoc, I've disabled the webhook. @godofredoc is monitoring behavior to see if this fixes the problem.

**Comment by godofredoc** [comment]
Moving to P2 as we believe the problem is now fixed

**Comment by godofredoc** [comment]
This is now running as expected.

**Comment by keyonghan** [comment]
Issue reproduced in: https://github.com/flutter/flutter/pull/62445
<img width="915" alt="Screen Shot 2020-08-05 at 5 40 54 PM" src="https://user-images.githubusercontent.com/54558023/89477741-e51e4100-d742-11ea-9cf8-935eba45422c.png">

**Comment by godofredoc** [comment]
I think this is a different issue. Are we using the new config files? is the builder duplicated in the new files?

**Comment by godofredoc** [comment]
I looked for the configs but could not find them

**Comment by keyonghan** [comment]
Cocoon is using https://github.com/flutter/cocoon/blob/master/app_dart/dev/luci_try_builders.json at this moment.

**Comment by godofredoc** [comment]
We are actually triggering the build twice:


![image](https://user-images.githubusercontent.com/54371434/89698787-e8970100-d8d7-11ea-90df-136022e25be7.png)

**Comment by godofredoc** [comment]
The webhook seems to be called twice:

![image](https://user-images.githubusercontent.com/54371434/89699163-04030b80-d8da-11ea-893f-c84a7a1a521a.png)

**Comment by keyonghan** [comment]
This debug info was triggered when labeling via `_checkForLabelsAndTests`. Two labels were added, causing two debug records in the log.

**Comment by godofredoc** [comment]
Does adding a label causes a synchronize?

**Comment by keyonghan** [comment]
It shouldn't. Otherwise, we will see three runs (first commit, then two labels). I am still debugging.

**Comment by keyonghan** [comment]
This happens only on flutter/flutter repo. flutter/engine tasks are not triggered multiple times.

**Comment by keyonghan** [comment]
Debug on pr: https://github.com/flutter/flutter/pull/63401

Webhood was trigger once at 10:27:29
<img width="1365" alt="Screen Shot 2020-08-10 at 11 23 55 AM" src="https://user-images.githubusercontent.com/54558023/89816878-25434200-dafc-11ea-854f-8b7e04078a7b.png">

The builders were scheduled twice at 10:27:19 and 10:27:30
<img width="1675" alt="Screen Shot 2020-08-10 at 11 24 05 AM" src="https://user-images.githubusercontent.com/54558023/89816985-4a37b500-dafc-11ea-9554-3a19bb238932.png">

Is it possible from recipe/config side, we somehow are triggering the builders twice for flutter repo? @godofredoc

**Comment by keyonghan** [comment]
Or the luci status was not disabled appropriately that it still has tests running againt it?

**Comment by keyonghan** [comment]
With webhook disabled, it is verified that no replicated tasks are scheduled. Closing.
One recent PR:
<img width="1671" alt="Screen Shot 2020-08-10 at 2 36 43 PM" src="https://user-images.githubusercontent.com/54558023/89834050-f1294a80-db16-11ea-82b3-c6a3eb07aa09.png">
