### ISSUE TITLE
Can't use keyboard shortcuts on a programmatically-focused textfield

### ISSUE THREAD

**Issue by mpfaff** [flutter/flutter#62800]
## Steps to Reproduce

1. Create a new Flutter project.
2. Update the files as follows:
main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            focusNode: _focusNode,
            onSubmitted: (_) => _focusNode.requestFocus(),
          ),
        ),
      ),
    );
  }
}
```
3. Run on macOS (haven't tested other platforms)
4. Type some text in the field
5. Press enter to submit (the field will be focused immediately using `_focusNode.requestFocus`)
6. Try to select text in the field using shift+arrow keys

**Expected results:** 

I can use keyboard shortcuts like copy and paste and can select text with shift+arrow keys.

**Actual results:** 

Same issue as reported in #36034.

Keyboard shortcuts do not work on a `TextField` that has been focused using `focusNode.requestFocus`.

**Comment by TahaTesser** [comment]
Hi @mpfaff 
This is specific to desktop https://github.com/flutter/flutter/issues/58473
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
