### ISSUE TITLE
Connectivity package fails - Execution failed for task ':app:mergeDebugNativeLibs'.

### ISSUE THREAD

**Issue by cristianfb1989** [flutter/flutter#62806]
Hi, everyone, I have this trouble:

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@24e15651' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'com.android.builder.files.ZipCentralDirectory@51a6811e' was deleted, but previous version not found in cache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
`

`connectivity: ^0.4.4+1`

Can anyone help me? Thank you

**Comment by darshankawar** [comment]
Hi @cristianfb1989,
Can you try `flutter pub cache repair` or `flutter clean` and then `flutter run` to see if it resolves your issue ?
If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing ?
Also curious, any reason you are using `^0.4.4+1` and not the [latest](https://pub.dev/packages/connectivity/versions/0.4.9) version of it ?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by preetb123** [comment]
Open the project in Android Studio android and clean the project
`Build -> Clean Project`
