### ISSUE TITLE
Allow having a background color in CustomScrollView,NestedScrollView (GridView/SliverGrid)

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#62818]
## Use case
It's just an option we need. I need it for my project and from looking around on GitHub and Stackoverflow, I'm not the only one. Wrapping it in a container doesn't cut it because it creates a whole lot of other issues, especially in SliverGrid. 

Not only that, by not having this option, Grids are prone to more errors, such as https://github.com/flutter/flutter/issues/62817

**Comment by TahaTesser** [comment]
This looks like reasonable proposal 
Related https://github.com/flutter/flutter/issues/19709  https://github.com/flutter/flutter/issues/28083, this could be address well this proposal

**Comment by tomasbaran** [comment]
For the meantime, I found a very simple workaround. Just add this to each tile Container in the GridView/SliverGrid:

```
decoration: BoxDecoration(
              color: Colors.black,
              borderRadius:
                  BorderRadius.only(topRight: Radius.circular(1)),
            ),
```

## Result
<img width="942" alt="Captura de pantalla 2020-08-04 a las 14 53 03" src="https://user-images.githubusercontent.com/25743901/89302261-841f3c00-d662-11ea-8d95-82441b24c7f0.png">

**Comment by tomasbaran** [comment]
Never mind my previous workaround since it doesn't work 100%. 

@dhawalmehta22 found a fix (see original post: https://github.com/flutter/flutter/issues/25009) that works at all times. Just wrap the problematic container with another container and add this to the parenting container:

 ```
decoration: BoxDecoration(
              color: Colors.black, //the color of the main container
              border: Border.all(
                //apply border to only that side where the line is appearing i.e. top | bottom | right | left.
                width: 2.0, //depends on the width of the unintended line
                color: Colors.black,
              ),
            ),
```

**Comment by tomasbaran** [comment]
Even better would be having a background in CustomScrollView, which essentially also acts as a container. Wrapping it in a container is NOT the same in many cases.

**Comment by goderbauer** [comment]
@Piinks

**Comment by Piinks** [comment]
> Wrapping it in a container doesn't cut it because it creates a whole lot of other issues

> Wrapping it in a container is NOT the same in many cases.

@tomasbaran can you elaborate on why this does not work, or creates other issues?

**Comment by Piinks** [comment]
Can you follow up in https://github.com/flutter/flutter/issues/29702? We de-dupe issues to focus conversation and solutions in one place. Thanks!
