### ISSUE TITLE
Error executing fluent upgrade.   Because flutter_tools depends on source_maps 0.10.10-nullsafety which doesn't

### ISSUE THREAD

**Issue by SongHuaixu** [flutter/flutter#62829]
## Steps to Reproduce
<details>

<summary> 1. flutter upgrade </summary>

```

Upgrading Flutter from
/Users/{User}/flutter...
Downloading Dart SDK from Flutter engine fa16c3d0bacd7d9928bc4c61659989d07cbf2645...
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  258M  100  258M    0     0  4114k      0  0:01:04  0:01:04 --:--:-- 3767k
Building flutter tool...
Because flutter_tools depends on source_maps 0.10.10-nullsafety which doesn't match any versions, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

</details>

<details>

<summary> 2. pub upgrade</summary>

```

Resolving dependencies... (44.1s)
Because hi_classroom depends on flutter_test any from sdk which doesn't exist
  (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.

```
</details>

<details>

<summary> 3. flutter pub get </summary>

```

Building flutter tool...
Because flutter_tools depends on source_maps 0.10.10-nullsafety which doesn't
  match any versions, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

</details>

**Comment by uucp** [comment]
me too

**Comment by chqianpront** [comment]
same issue

**Comment by k644606347** [comment]
same issue

**Comment by rpoverflow** [comment]
same here

**Comment by addappcn** [comment]
me  too

**Comment by mdyoyo** [comment]
same issue

**Comment by oydp** [comment]
same issue

**Comment by cszwdy** [comment]
same issue

**Comment by oydp** [comment]
I tried change the repo branch in flutter root directory. It looks like working..
Hope this will help. Here are the details.
```
$ which flutter
/Users/mawanli/flutter/bin/flutter
$ cd /Users/mawanli/flutter/
$ git checkout stable
$ flutter upgrade
Downloading Dart SDK from Flutter engine ee76268252c22f5c11e82a7b87423ca3982e51a7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0   557k      0  0:06:30  0:06:30 --:--:--  517k
Building flutter tool...
Flutter is already up to date on channel stable
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (5 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

**Comment by uucp** [comment]
branch stable is working ..

**Comment by weiminghuaa** [comment]
use official pub, not mirror

**Comment by oydp** [comment]
> use official pub, not mirror

Thanks..

**Comment by 97thjingba** [comment]
same here

**Comment by pedromassangocode** [comment]
Can confirm that this happened to me earlier in the morning. Looks like it does upgraded the master channel even with those warnings/errors because I just tried upgrade it again and it says that the master channel is already updated.

<img width="575" alt="Screen Shot 2020-08-04 at 11 43 52" src="https://user-images.githubusercontent.com/67424416/89285189-db63e300-d647-11ea-9e67-92564d4de3c1.png">

**Comment by fanchou** [comment]
git checkout beta
flutter upgrade

**Comment by fanchou** [comment]
git checkout beta

**Comment by fanchou** [comment]
git checkout beta

**Comment by fanchou** [comment]
git checkout beta   -> flutter upgrade      git checkout master   ->  flutter upgrade

**Comment by SongHuaixu** [comment]
> Can confirm that this happened to me earlier in the morning. Looks like it does upgraded the master channel even with those warnings/errors because I just tried upgrade it again and it says that the master channel is already updated.
> 
> <img alt="Screen Shot 2020-08-04 at 11 43 52" width="575" src="https://user-images.githubusercontent.com/67424416/89285189-db63e300-d647-11ea-9e67-92564d4de3c1.png">

It's ok now
