### ISSUE TITLE
textField Cursor misplaced in TextAlign.center or TextAlign.right

### ISSUE THREAD

**Issue by kdm7173icomer** [flutter/flutter#62831]
## In textField, Cursor is misplaced when text align is TextAlign.center or TextAlign.right (TextAlign.end).

Please, see attach gif.

good.gif
<img src="https://i.stack.imgur.com/6Qppd.gif" width="300">

misplace.gif
<img src="https://i.stack.imgur.com/6kMlW.gif" width="300">

## This has some conditions and results.

**Conditions:**
1. textAlign is TextAlign.center or TextAlign.right (TextAlign.end).
2. Cursor Must comes at the last of each line. (last of column)
3. Cursor Must NOT comes at the last of lines. (!last of row)
**(TextAlign.center || TextAlign.right || TextAlign.end) && Cursor at the last of column && !Cursor at the last of row**

**Results:**
Cursor places at exactly same as textAlign.start or textAlign.left. (It seems like texts are applied align option. But cursor is not.)
**Only Cursor is misplaced. Texts are placed well.**

## TEST CODE
Nothing special
only 

TextField( maxLines: null, textAlign: TextAlign.end );
or
TextField( maxLines: null, textAlign: TextAlign.center );

can test this situation.

**Comment by TahaTesser** [comment]
Hi @kdm7173icomer 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by kdm7173icomer** [comment]
I made new issue with simple code and doctor -v. please see #62934.
