### ISSUE TITLE
'flutter screenshot --type=skia' *,skp file can not be open by https://debugger.skia.org/

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#62845]
PS C:\Users\Administrator> flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:51477/UVKsyH_MGdo=/
No supported devices connected.
Screenshot written to flutter_16.skp (0kB).
PS C:\Users\Administrator>

C:\Users\Administrator>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at F:\flutter_dev\src_new\flutter
    • Framework revision 0b8abb4724 (6 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • PDCM00 • 9LL7VO8XUOIN75ZH • android-arm64 • Android 10 (API 29)

• No issues found!

C:\Users\Administrator>

![image](https://user-images.githubusercontent.com/61075224/89271042-c3ec2080-d66e-11ea-83b7-07be87bb8038.png)
This function was still good a few weeks ago. The left side of the picture above is working properly.

this is the skp file in HEX:
00 20 e0 06 28 37 3b 07 09 00 43 00 74 00 72 00 6c 00 2b 00 53 00 68 00 69 00 66 00 74 00 2b 00 50 00 61 00 67 00 65 00 20 00 64 00 6f 00 77 00 6e 00 00 00 49 12 28 07 64 ef 88 00 f0 5f 89 00 08 00 00 00 98 c3 e1 06 a4 ed 88 00 f0 5f 89 00 09 00 00 00 00 00 00 00 98 c3 e1 06 00 00 00 00 00 00 00 00 00 00 00 00 80 00 00 00 08 ee 88 00 bc ed 88 00 5f 49 d3 74 64 ee 88 00 30 06 2b 01 03 00 00 00 f8 ed 88 00 36 43 d3 74 30 06 2b 01 03 00 00 00 f0 5f 89 00 f0 55 00 00 f0 5f 89 00 c8 ed 88 00 00 00 00 00 60 18 2b 01 f0 5f 89 00 f0 5f 89 00 00 00 00 00 f0 5f 89 00 00 00 00 00 09 00 00 00 44 ee 88 00 5b 4a d3 74 60 18 2b 01 77 4a d3 74 f0 f7 96 0c f0 5f 89 00 f0 55 00 00 f0 5f 89 00 00 00 00 00 f0 5f 89 00 00 00 00 00 00 00 00 00 00 00 00 00 43 ac 00 00 00 00 00 00 4d 00 6f 00 76 00 65 00 20 00 54 00 61 00 62 00 20 00 42 00 61 00 63 00 6b 00 77 00 61 00 72 00 64 00 09 00 43 00 74 00 72 00 6c 00 2b 00 53 00 68 00 69 00 66 00 74 00 2b 00 50 00 61 00 67 00 65 00 20 00 75 00 70 00 00 00 00 00 49 12 28 07 64 ef 88 00 f0 5f 89 00 08 00 00 00 98 c3 e1 06 a4 ed 88 00 f0 5f 89 00 09 00 00 00 00 00 00 00 98 c3 e1 06 00 00 00 00 00 00 00 00 00 00 00 00 80 00 00 00 08 ee 88 00 bc ed 88 00 5f 49 d3 74 64 ee 88 00 30 06 2b 01 03 00 00 00 f8 ed 88 00 36 43 d3 74 30 06 2b 01 03 00 00 00 f0 5f 89 00 f0 55 00 00 f0 5f 89 00 c8 ed 88 00 00 00 00 00 60 18 2b 01 f0 5f 89 00 f0 5f 89 00 00 00 00 00 f0 5f 89 00 00 00 00 00 09 00 00 00 44 ee 88 00 5b 4a d3 74 60 18 2b 01 77 4a d3 74 f0 f7 96 0c f0 5f 89 00 f0 55 00 00 f0 5f 89 00 00 00 00 00 f0 5f 89 00 00 00 00 00 00 00 00 00 00

**Comment by TahaTesser** [comment]
Hi @xu-baolin 
Can you upgrade to latest  stable and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by jason-simmons** [comment]
The `flutter screenshot --type=skia` Skia picture snapshots are not working in the current Flutter engine master.

The behavior changed with the new definition of `SK_DISABLE_EFFECT_DESERIALIZATION` in https://github.com/google/skia/commit/5c9d1817.  A debug_unopt engine will trigger an assert in `SkBinaryWriteBuffer::writeFlattenable` during SKP serialization.

If I remove `SK_DISABLE_EFFECT_DESERIALIZATION` in https://github.com/google/skia/blob/master/gn/flutter_defines.gni, then the resulting SKPs can load in the debugger.  However, removing `SK_DISABLE_EFFECT_DESERIALIZATION` increases binary size (an Android release build of libflutter.so increases by 154KB).

The SKPs exported by the current engine also are not serializing fonts.  It looks like this started with https://github.com/flutter/engine/commit/15d19a494914d1c2143ce889090b96c6354c871d.  That commit added `SerializeTypefaceWithoutData` and `SerializeTypefaceWithData` callbacks, but their behaviors are reversed.

**Comment by xu-baolin** [comment]
Thank you guys, @TahaTesser @jason-simmons 
I will close this issue because bug fixed.
