### ISSUE TITLE
Teach 'pub' to tell you what to do if it sees `sdk: flutter`

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#6284]
## Steps to Reproduce

With a clean, updated copy of Flutter, I'm having issues running pub commands. It looks like whenever my pubspec.yaml contains   

```
flutter:
    sdk: flutter
```

instead of

```
flutter:
    path: ../../flutter/packages/flutter
```

If I run 'pub get' or 'pub upgrade', I get the message "The Flutter SDK is not available." and pub get fails. However, if I run 'flutter run' and pub get hasn't been run, it appears to successfully run pub get and then run the app. This behavior is consistent across the example apps and my own app. 

It is coming up because I need to use flutter_test as a dependency, and flutter_test depends on flutter from source sdk rather than path, so I have to switch to the sdk syntax.
## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/emshack/flutter
    • Framework revision 2805e5f8b8 (62 minutes ago), 2016-10-12 09:41:35
    • Engine revision e8d046e9e2
    • Tools Dart version 1.20.0-dev.10.2
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39
[✓] Connected devices
    • iPhone 6s • C1E3EB06-AD47-46DC-AD56-9DB6A02312EB • ios (simulator)
```

**Comment by eseidelGoogle** [comment]
Correct `flutter packages get` is the new command.  Perhaps we need to teach pub to explain that better.

https://groups.google.com/forum/#!topic/flutter-dev/djiZKDpcyjE

**Comment by abarth** [comment]
Yeah, @eseidelGoogle would you be willing to file a bug on pub to improve the error message to say "run flutter packages get" ?

**Comment by emshack** [comment]
Ah, thanks!

**Comment by eseidelGoogle** [comment]
https://github.com/dart-lang/pub/ is the location of the pub code.  I'm not sure what ask them to change.  Not clear that hard-coding `flutter packages get` into pub makes sense.  Maybe pub should link to instructions on flutter.io?

```
%pub get
Resolving dependencies... 
The Flutter SDK is not available.
Depended on by:
- flutter_gallery 
```

**Comment by abarth** [comment]
Yes, maybe we should have a `https://flutter.io/pub/` landing page with instructions.

**Comment by eseidelGoogle** [comment]
This is really a bug for pub.  And could link to flutter.io for setup instructions.  Easy fix.

**Comment by xster** [comment]
Another angle for this is for editor developers. Instead of generically handle Dart and pubspecs, they'd have to create a custom Flutter handler for the sdk: flutter clause.

**Comment by Hixie** [comment]
Pub now says "Flutter users should run `flutter packages get` instead of `pub get`.".
