### ISSUE TITLE
Use local auth tokens in communication with GCP

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62842]
LUCI_CTX is a protocol to generate short lived tokens for tasks running on LUCI.  The protocol is defined here:

https://github.com/luci/luci-py/blob/master/client/LUCI_CONTEXT.md

This will allow the device lab tasks running on LUCI to upload logs and results using the LUCI context instead of API tokens.

**Comment by digiter** [comment]
So there's a LUCI_CONTEXT env variable that points to a json file, which should contain a `local_auth` key-value that specifies [how to obtain OAuth2 tokens](https://github.com/luci/luci-py/blob/master/client/LUCI_CONTEXT.md#local_auth). We need to implement a local auth client.

@godofredoc Where should the local auth client live? In a dart package?

**Comment by godofredoc** [comment]
It will be used in the cocoon agent, in the flutter repository after devicelab is migrated to luci and potentially in the metrics collection in the engine. A package that can be accessed from those places will be great.

**Comment by digiter** [comment]
Example LUCI_CONTEXT json file:
```
{"local_auth":{"accounts":[{"email":"bots-fuchsia@chromium-swarm.iam.gserviceaccount.com","id":"system"},{"email":"flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com","id":"task"}],"default_account_id":"task","rpc_port":41417,"secret":"somesecret"},"luciexe":{"cache_dir":"/b/s/w/ir/cache"},"realm":{}}
```

Looks like the `ServiceAccount` module already has a function for getting access token: [link](https://source.corp.google.com/fuchsia-infra/chromium/recipes-py/recipe_modules/service_account/api.py;rcl=aac04034f188f96e39d77509ac5b1d967874c918;l=37). @godofredoc
