### ISSUE TITLE
Flutter creating instance of class with image. I do not know what reason is.

### ISSUE THREAD

**Issue by nurbek-b** [flutter/flutter#62843]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building CartItem(dirty):
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CartItem file:///Users/macbookpro/AndroidStudioProjects/codecanyon-22764499-ecommerce-ui-kit-using-flutter/treva_shop_flutter/lib/UI/CartUIComponent/CartLayout.dart:42:40
When the exception was thrown, this was the stack: 
#2      new AssetImage (package:flutter/src/painting/image_resolution.dart:134:15)
#3      new Image.asset (package:flutter/src/widgets/image.dart:618:12)
#4      CartItem.build (package:treva_shop_flutter/widgets/cartitem.dart:89:44)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
═════════════════════

**Comment by darshankawar** [comment]
Hi @nurbek-b,
Verify if the asset names in `pubspec.yaml` are correctly called in your code.
If problem persists, please provide `flutter doctor -v`, `pubspec.yaml` and minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
