### ISSUE TITLE
no have shadow in bottom navigation bar

### ISSUE THREAD

**Issue by tranlo** [flutter/flutter#62850]
I can't find the shadow in Bottom navigation bar. only have elevation

**Comment by darshankawar** [comment]
Hi @tranlo,
Yes, Bottom Navigation Bar has `elevation` property. If you want to give a shadow effect to it, you may wrap the widget with `Container` and use `BoxDecoration` method to apply shadow effect, like below:

```
bottomNavigationBar: Container(
        decoration: BoxDecoration(
          boxShadow: <BoxShadow>[
            BoxShadow(
                color: Colors.black54,
                blurRadius: 15.0,
                offset: Offset(0.0, 0.75)
            )
          ],
        ),
        child: BottomNavigationBar(
          items: [
            new BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Text('Home'),
            ),
            new BottomNavigationBarItem(
              icon: Icon(Icons.mail),
              title: Text('Messages'),
            ),
            new BottomNavigationBarItem(
                icon: Icon(Icons.person),
                title: Text('Profile')
            )
          ],
        ),
      )
```

![Screen Shot 2020-08-05 at 11 39 37 AM](https://user-images.githubusercontent.com/67046386/89377904-5f819d80-d710-11ea-9b0b-f82fa843d86d.png)

**Comment by tranlo** [comment]
> Hi @tranlo,
> Yes, Bottom Navigation Bar has `elevation` property. If you want to give a shadow effect to it, you may wrap the widget with `Container` and use `BoxDecoration` method to apply shadow effect, like below:
> 
> ```
> bottomNavigationBar: Container(
>         decoration: BoxDecoration(
>           boxShadow: <BoxShadow>[
>             BoxShadow(
>                 color: Colors.black54,
>                 blurRadius: 15.0,
>                 offset: Offset(0.0, 0.75)
>             )
>           ],
>         ),
>         child: BottomNavigationBar(
>           items: [
>             new BottomNavigationBarItem(
>               icon: Icon(Icons.home),
>               title: Text('Home'),
>             ),
>             new BottomNavigationBarItem(
>               icon: Icon(Icons.mail),
>               title: Text('Messages'),
>             ),
>             new BottomNavigationBarItem(
>                 icon: Icon(Icons.person),
>                 title: Text('Profile')
>             )
>           ],
>         ),
>       )
> ```
> 
> ![Screen Shot 2020-08-05 at 11 39 37 AM](https://user-images.githubusercontent.com/67046386/89377904-5f819d80-d710-11ea-9b0b-f82fa843d86d.png)

Thanks @darshankawar . I got it
