### ISSUE TITLE
Flutter Web : google_sign_in, idpiframe_initialization_failed, Cookies are not enabled in current environment

### ISSUE THREAD

**Issue by vin-fandemand** [flutter/flutter#62858]
I was building a web app with Flutter and implementing Google Sign In using the google_sign_in plugin. I was testing it on various browsers and got the error `google_sign_in, idpiframe_initialization_failed, Cookies are not enabled in the current environment` while testing on `Chrome 84.0.4147.111`. From  [this answer](https://stackoverflow.com/questions/42668299/google-auth-api-javascript-idpiframe-initialization-error-on-chrome) I learned that the third party cookies need to be enabled. Once I enabled the google sign in worked as expected.

Now I feel that we cannot expect every user to have their cookies enabled. So there should be some sort of warning on the page to tell the user that they should enable cookies to allow functioning?

**Comment by darshankawar** [comment]
Hi @vin-fandemand,
There's similar open issue describing your case, [59145](https://github.com/flutter/flutter/issues/59145).
Please follow-up there for updates and any questions you may have.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
