### ISSUE TITLE
Flutter upgrade doesn't tell me what else I need to do to complete upgrade

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6286]
My expectation was that by running `flutter upgrade`, I'm putting my setup/config/local install into an upgraded state for Flutter. However, turns out I needed to run additional commands to upgrade.

Could we inform the user of additional upgrade steps (or, perform the steps for them) at the end of `flutter upgrade` ? Something like, "To complete this upgrade, please run these commands..."

Specifically, my libimobiledevice was out of date. `flutter upgrade` didn't inform me of that. It probably should, since it falls under the user intent to upgrade.

Thanks!

**Comment by sethladd** [comment]
cc @cbracken

**Comment by cbracken** [comment]
Fixed by #6330
