### ISSUE TITLE
app restart when resuming after sent in background on the oneplus6 android phone

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#62862]
## Steps to Reproduce

start the app
send it in background
come back to app
app restart from splash screen

**Expected results:** 

app resume gracefully without restarting

**Actual results:** 

app restart

I can't reproduce it, I don't own a oneplus6 phone
I get this feedback from ours users on oneplus6

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-FR)
    • Flutter version 1.17.5 at /Users/renanyoy/code/sdk/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
```

**Comment by renanyoy** [comment]
device description
```
08-04 16:30:10.237  8212  8679 I flutter : app..........: leads2keys
08-04 16:30:10.237  8212  8679 I flutter : version......: 1.0.125 (25)
08-04 16:30:10.237  8212  8679 I flutter : system.......: android
08-04 16:30:10.237  8212  8679 I flutter : device.......: OnePlus6
08-04 16:30:10.237  8212  8679 I flutter : manufacturer.: OnePlus
08-04 16:30:10.237  8212  8679 I flutter : brand........: OnePlus
08-04 16:30:10.237  8212  8679 I flutter : model........: ONEPLUS A6000
08-04 16:30:10.237  8212  8679 I flutter : android......: 10
```

**Comment by TahaTesser** [comment]
Hi @renanyoy 
Can you please provide your `pubspec.yaml` and `flutter run --release --verbose` 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by renanyoy** [comment]
I don't own a oneplus6 phone, it just feedbacks from users

**Comment by TahaTesser** [comment]
Hi @renanyoy 
To better address the address we would  need more information about the ap and logs
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
