### ISSUE TITLE
Widgets do not remove their dependency on an InheritedWidget when rebuilt without calling .of(context) again

### ISSUE THREAD

**Issue by Quijx** [flutter/flutter#62861]
When a widget has a dependency on an `InheritedWidget` by calling `.of(context)` on it, it gets rebuilt whenever the `InheritedWidget` changes. However if the dependant gets rebuilt without calling `.of(context)` on that `InheritedWidget` class again, the widget still gets rebuilt whenever the `InheritedWidget` changes. This should not be the case because nothing can depend in the content of the `InheritedWidget` if `.of(context)` is not called.

This issue is likely the cause of #62753.

Here a gif demonstrating this bug. Note the following:
- At first the bottom colored widget does not rebuild (its color does not change) when the counter updates because it does not (yet) depend on the `InheritedWidget` that contains the counter value.
- After clicking "Show counter" the widget rebuilds (indicated by color change) every time the counter updates.
- After clicking "Show nothing" the widget still rebuilds every time the counter updates, even though it no longer depends in the `InheritedWidget`.
- The demo is also available at https://dartpad.dev/6aa4206628af8542fb6e0173fe38c0ed

![inherited_widget_bug](https://user-images.githubusercontent.com/48153628/89307114-fb5bcc80-d670-11ea-87fd-7ded747c06d3.gif)

## Steps to Reproduce

1. Run `flutter create bug`. (Or directly check demo at https://dartpad.dev/6aa4206628af8542fb6e0173fe38c0ed and continue at step 3.)
2. Replace the code in `lib/main.dart` with the content of the following gist: https://gist.github.com/Quijx/6aa4206628af8542fb6e0173fe38c0ed
3. Run the app
4. Tap the "Increase Counter" button.
    - The value of the counter changes on the very top.
    - The colored `Dependant` widget does not rebuild (no color change) because it does not show the counter and therefore does not depend in the `InheritedCounter`.
5. Tap the "Show counter" button.
    - The colored `Dependant` widget now rebuilds (indicated by color change) and displays the counter value.
6. Tap the "Increase Counter" button.
    - The value of the counter changes on the very top.
    - As expected the `Dependant` now rebuilds and displays the new counter value.
7. Tap the "Show nothing" button.
    - The `Dependant` widget rebuilds an no longer shows the counter.
8. Tap the "Increase Counter" button.
    - The value of the counter changes on the very top.
    - The `Dependant` now rebuilds (color changes) even though it no longer depends on the `InheritedCounter` (`InheritedCounter.of(context)` was not called).

**Expected results:** 
In step 8 the `Dependant` widget should not rebuild because it no longer depends on the `InheritedCounter`.

**Actual results:** 
In step 8 the `Dependant` widget rebuilds even though it no longer depends on the counter and `InheritedCounter.of(context)` was not called during the last build.
<details>
  <summary>Logs</summary>

```
Analyzing inherited_widget_bug...                                        
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.141, on Linux, locale en_DE.UTF-8)
    • Flutter version 1.21.0-6.0.pre.141 at /home/quijx/Documents/System/libs/flutter
    • Framework revision c748f1a7aa (4 days ago), 2020-07-31 17:45:18 -0700
    • Engine revision 280bbfc763
    • Dart version 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/quijx/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /opt/JetBrains/apps/AndroidStudio/ch-0/191.5791312/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0
    • cmake version 3.18.0
    • ninja version 1.10.0
    • pkg-config version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/JetBrains/apps/AndroidStudio/ch-0/191.5791312
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/JetBrains/apps/AndroidStudio/ch-0/183.5692245
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/JetBrains/apps/IDEA-C/ch-0/192.6817.14
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel master, 1.21.0-6.0.pre.160, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-6.0.pre.160 at C:\Code\flutter
    • Framework revision 31ee51a302 (35 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by Quijx** [comment]
@goderbauer 
As a test I added
```dart
if (_dependencies != null) {
    for (final InheritedElement dep in _dependencies) {
        dep._dependents.remove(this);
    }
    _dependencies.clear();
}
```
just before the `performRebuild();` call in `Element.rebuild()`.
That seems to resolve the issue. Not sure how "right" this solution is though.
Just in case that helps for the fix...

**Comment by Quijx** [comment]
Is there any timeline for when this could be fixed?
I've been woking with a locally modified flutter since creating this issue where I just inserted 
```dart
for (final InheritedElement dep in _dependencies ?? Iterable.empty()) {
    dep._dependents.remove(this);
}
_dependencies?.clear();
```
before
https://github.com/flutter/flutter/blob/81142c1f9a18df456b3b147a45cd5971e58014ec/packages/flutter/lib/src/widgets/framework.dart#L4311
. Seems to work so far, but I'm not sure if this is the correct fix or if it has undesirable side effects.

This bug (or more specifically #62753) is relevant to me, because I'm writing a redux-like State management, where I want to do something like the following to depend on parts of an immutable state:
```dart
class UsernameText extends StatelessWidget {
  const UsernameText({Key? key, required this.id}) : super(key: key);

  final int id;

  @override
  Widget build(BuildContext context) {
    final String username = StoreProvider.watch<MyState, String>(
      context,
      (state) => state.users[id].name,
    );
    return Text(username);
  }
}
```

The `watch` function uses `InheritedModel.inheritFrom` internally with the function passed in the second argument as the aspect.

Since the lambda is a different object on every rebuild and the dependencies are never cleared, the aspects accumulate for every build. (Also it breaks an optimization that could otheriwse be made where some evaluations of the function can be cached, but I won't get into that now.)

**Comment by Quijx** [comment]
Closing i favor of #12992.
For the reason see comment https://github.com/flutter/flutter/issues/62753#issuecomment-1485981533.
