### ISSUE TITLE
Documentation re: iOS 9 minimum version

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62879]
Recent versions of Xcode now throw warnings when projects default to iOS 8. We should:

  * Make the default template iOS 9.
  * Provide documentation as to how to target iOS 8 for those still wanting to do so.
  * Provide documentation as to how to migrate old projects.

cc @jmagman @xster @csells

**Comment by jmagman** [comment]
The template change is tracked in https://github.com/flutter/flutter/issues/60035 and automatically migrate existing projects in #62880.
@kf6gpe should we use this issue to track the documentation changes?

**Comment by kf6gpe** [comment]
Sounds good. Didn't realize you'd already started issues for the work! That's great.

This is for tracking documentation then.

**Comment by jmagman** [comment]
> Provide documentation as to how to target iOS 8 for those still wanting to do so.

I don't think we document how to target iOS 8 anymore--we shouldn't advertise or imply that it will work.

1. Default template updated in https://github.com/flutter/flutter/pull/62902
2. Tool automatically migrates in https://github.com/flutter/flutter/pull/85174
3. Website updated: https://github.com/flutter/website/pull/6057

Closing as done!
