### ISSUE TITLE
Gradual increases to web_size__compile_test flutter_gallery_dart2js_size

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#62870]
I've been assuming this is normal growth to the addition of code, and I've rebaselined a few times, but I want to make sure before rebaselining again that this assumption holds.

See:
![Screen Shot 2020-08-04 at 9 23 14 AM](https://user-images.githubusercontent.com/1435716/89318848-34298080-d634-11ea-8e94-f4b2c04d4e64.png)

I don't think this is urgent, hence the reasonable priority.

cc @yjbanov

**Comment by yjbanov** [comment]
Yeah, this is expected. Rebaselined.
