### ISSUE TITLE
[pigeon] run analyzer on the package

### ISSUE THREAD

**Issue by xster** [flutter/flutter#62878]
<img width="885" alt="Screen Shot 2020-08-04 at 10 01 52 AM" src="https://user-images.githubusercontent.com/156888/89322728-8620d500-d639-11ea-9cac-d9d9f69f88e9.png">

**Comment by stuartmorgan** [comment]
We do run static analysis; our options don't fully align with pub.dev's, but it's pretty close now (and the remaining issue pub is flagging for Pigeon will be fixed once Dart 3 rolls out).
