### ISSUE TITLE
Support synchronized IME on Android

### ISSUE THREAD

**Issue by xster** [flutter/flutter#62876]
Android hasn't had a way to control the IME animation transition until Android 11 via `getWindowInsetsController().controlWindowInsetsAnimation()`. Add support. 

iOS FR: https://github.com/flutter/flutter/issues/57609

**Comment by xster** [comment]
The upstream symptom to fix is https://github.com/flutter/flutter/issues/19279

**Comment by GaryQian** [comment]
This work can be broken into two halves:

- Updating the flutter view insets as the IME animates
- Sending user scroll position to the embedder, and animating the IME to follow

The first is what is necessary to resolve #19279, b/144470661, so I will implement that first via `WindowInsetsAnimation.Callback`

**Comment by xster** [comment]
Agreed. Your breakdown (IME output vs IME input) sounds exactly right and are independent. Plan SGTM.

**Comment by xster** [comment]
So i.e. you're saying you want to start with the part that's not the part you have a draft PR for? :)

**Comment by GaryQian** [comment]
Turns out it took writing that draft to figure out the problem space to properly tackle the problem. *Shrug*

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/20843 Implements embedder->framework sync

**Comment by GaryQian** [comment]
Reopening, as framework->embedder syncing of scrollable widgets is not yet complete.

**Comment by pcsosinski** [comment]
@xster I believe there is no work for 1.22 related to this - if so can we move it to an appropriate milestone?  thanks

**Comment by zanderso** [comment]
[Triage] @GaryQian Are you still working on this?

**Comment by GaryQian** [comment]
I am not actively working on the remaining work right now. Though this bug could be closed in favor of a new more specific bug that tracks remaining framework->embedder syncing work.

**Comment by gmackall** [comment]
> Though this bug could be closed in favor of a new more specific bug that tracks remaining framework->embedder syncing work.

Closing as recommended.
