### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/abdelrahman/Downloads/Glif data/elnaamy_group/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by AbdelrahmanAhmedShawky** [flutter/flutter#62875]
## Command
```
flutter build apk --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/abdelrahman/Downloads/Glif data/elnaamy_group/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.169, on Mac OS X 10.15.2 19C57,
    locale en)
    • Flutter version 1.21.0-6.0.pre.169 at /Users/abdelrahman/Downloads/flutter
      doc/flutter
    • Framework revision 0e558042d7 (65 minutes ago), 2020-08-04 11:36:04 -0400
    • Engine revision 033dd45607
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/abdelrahman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 5ACE8F49-6490-42DA-A5DE-9C52CB809AD7
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    ! Error: Abdelrahman iPhone is not connected. Xcode will continue when
      Abdelrahman iPhone is connected. (code -13)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
flutter_plugin_android_lifecycle-1.0.8
google_maps_flutter-0.5.28+1
image_picker-0.6.6+4
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+9
shared_preferences_web-0.1.2+7

**Comment by darshankawar** [comment]
@BodyiOS 
Since this an old issue, I suggest you to upgrade to latest master version and try the command again to see if you still see same error or not.

`flutter channel master`
`flutter upgrade`

Also try [this](https://github.com/flutter/flutter/issues/65149#issuecomment-686255862) solution and see if it works for you.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
