### ISSUE TITLE
☂️ Migrate framework tests to null safety

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#62886]
Prerequisites (cc @jonahwilliams):

- [x] migrate the framework _[in progress by @a14n]_
- [x] publish platform/file/process in SDK allowlist, publish on pub, _[in progress by @jonahwilliams]_
- [x] migrate flutter_goldens/flutter_goldens_client, https://github.com/flutter/flutter/issues/53908 _[@jonahwilliams signed up for this]_
- [x] migrate flutter_test, https://github.com/flutter/flutter/issues/53908, _[in progress by @goderbauer: #66663]_

It doesn't make sense to start migrating the tests before all the bullets above are done.

The long pole that will block flutter_test migration is the migration of the framework.

**Comment by jakemac53** [comment]
[this is the commit](https://github.com/dart-lang/sdk/commit/ed3584b71be99c89287e6c5ac8ecadb9ea650d5d) adding those deps to the allow list, you will see dev release tags show up there once it appears in one.

**Comment by goderbauer** [comment]
Also as pointed out by @jonahwilliams we need to remove this part of trick:

https://github.com/flutter/flutter/blob/504963b4d1aa8c06e291a88f6036e2145168c9dc/packages/flutter/lib/src/material/animated_icons/animated_icons.dart#L7-L12

**Comment by jakemac53** [comment]
You can keep the trick if you rewrite the test to opt in to null safety, FWIW. But it really should be removed anyways.

**Comment by jakemac53** [comment]
@jonahwilliams it looks like https://github.com/dart-lang/sdk/commit/ed3584b71be99c89287e6c5ac8ecadb9ea650d5d made it into `2.10.0-4.0.dev`, so you can set that as the min sdk constraint and start publishing packages. Ping me if you have any questions/concerns about the release checklist.

**Comment by jonahwilliams** [comment]
I'm on it!

**Comment by goderbauer** [comment]
There's also https://github.com/flutter/flutter/issues/59879, but if that becomes a blocker we can opt out of sound nullsafety for the time being.

**Comment by jonahwilliams** [comment]
Additional blockers: https://github.com/flutter/flutter/issues/63441

**Comment by jonahwilliams** [comment]
#63441 is resolved but waiting on publishing by @cyanglaz

**Comment by cyanglaz** [comment]
path_provider_platform_interface and local_auth are published.

**Comment by jonahwilliams** [comment]
Thanks! now blocked on https://github.com/flutter/gallery/pull/265

**Comment by jonahwilliams** [comment]
now blocked on https://github.com/flutter/flutter/pull/64067

**Comment by goderbauer** [comment]
Migration of the flutter_test package is here: https://github.com/flutter/flutter/pull/66663

**Comment by goderbauer** [comment]
Submitting #66663 is blocked on migrating `Tooltip` and `Card` from the material lib to NNBD, which are unfortunately imported by `flutter_test`.

**Comment by goderbauer** [comment]
This is all done!
