### ISSUE TITLE
Delete iOS debug app when quitting resident runner

### ISSUE THREAD

**Issue by xster** [flutter/flutter#62883]
Branching off from https://github.com/flutter/flutter/issues/62518. Since a JIT remnant on a non-simulator iOS 14 device will be unusable after disconnecting the debugger and can only trigger an error, delete it when the resident runner is being quit.

**Comment by jonahwilliams** [comment]
This would preclude us from ever figuring out how to re-use the existing application on a repeat flutter run. I'm also not sure how it would interact with --no-resident/flutter attach. I think provided the app does not exit, a user could still reconnect right? @jmagman

**Comment by jonahwilliams** [comment]
I guess we could worry about that later though

**Comment by xster** [comment]
> This would preclude us from ever figuring out how to re-use the existing application on a repeat flutter run

Us fixing the VM would be bundled with a Flutter commit that can fix the tooling I'm thinking right?

> I'm also not sure how it would interact with --no-resident

It wouldn't

> flutter attach. I think provided the app does not exit, a user could still reconnect right

Ya, I'm proposing that we only do this on quit (q). Not detach (d) from either flutter run or flutter attach. Once you quit, it's final and that app will never work again without a host.

**Comment by jonahwilliams** [comment]
Makes sense to me

**Comment by jonahwilliams** [comment]
Thanks!

**Comment by jonahwilliams** [comment]
The way I would do this: make stopApp in the iOS device (not the simulator device) try and do an uninstall. Mark the iOS device as not supporting flutter exit so stopApp is always called instead of the service extension.

**Comment by 2ZeroSix** [comment]
I think it could lead to additional problems.

To launch an application signed with a free personal account certificate, you must set the developer as trusted in
`general settings->device management`.
But this value is reset as soon as the last application from this developer is removed from the device.

The proposed behavior will lead to the fact that developers using free accounts will have to build the application for ios twice each time they start the debug, unless they have their other applications installed.

**Comment by jmagman** [comment]
@2ZeroSix That's a very good point.  The profile being removed every time would drive me nuts.

**Comment by xster** [comment]
@jmagman can we test to see if this is universally true? If so, let's not implement this.

**Comment by xster** [comment]
Let's close this based on @2ZeroSix's good point.
