### ISSUE TITLE
No available listeners for Texture widget

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#62908]
I cant find any listeners related to texture widget. Like when frame is drawn to texture widget, I want to attach a listener and fetch that frame. For example OnFrameAvailableListener. Can someone help regarding this issue please ?

**Comment by darshankawar** [comment]
Hi @premingiet,
Are you still having this issue ?
If so, please provide `flutter doctor -v` and a code sample related to the texture widget and the limitation.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
