### ISSUE TITLE
No example for BottomSheet search

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6290]
From our material design catalog page, I tried to find examples of "BottomSheet" and came up empty: https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=path%3Aexamples+%22new+BottomSheet%22&type=Code

1) Do we have example of BottomSheet, and is GitHub's search not finding it?

2) Can we add examples of BottomSheets? :)

Thanks!

**Comment by sethladd** [comment]
cc @HansMuller @InMatrix

**Comment by abarth** [comment]
`BottomSheet` isn't a thing you use on its own.  There are persistent bottom sheets (see https://docs.flutter.io/flutter/material/ScaffoldState/showBottomSheet.html) and modal bottom sheets (see https://docs.flutter.io/flutter/material/showModalBottomSheet.html) that are how you typically use this.

The docs on https://docs.flutter.io/flutter/material/BottomSheet-class.html try to explain this situation.

**Comment by HansMuller** [comment]
The gallery has persistent and modal bottom sheet demos. They're

examples/flutter_gallery/lib/demo/persistent_bottom_sheet_demo.dart
examples/flutter_gallery/lib/demo/modal_bottom_sheet_demo.dart

**Comment by InMatrix** [comment]
Thanks for the pointers, @HansMuller. I'll update the page to correct the query.

**Comment by sethladd** [comment]
Thanks all!
