### ISSUE TITLE
☂️ State Restoration Remaining Work

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#62916]
Split from https://github.com/flutter/flutter/issues/6827.

## Migrating Widgets and Example Apps

Will start with the following widgets (in order of priority):

- [x] Scrollables (e.g. ListView, PageView, etc), PR: https://github.com/flutter/flutter/pull/63131
  - ListWheelScrollView
  - NestedScrollView
  - PageView
  - ScrollView
  - CustomScrollView
  - BoxScrollView
  - ListView
  - GridView
  - Scrollable
  - SingleChildScrollView
- [x] Textfields, PR: https://github.com/flutter/flutter/pull/63401
  - CupertinoTextField
  - TextField
  - EditableText (uses a Scrollable)
- [x] Navigator, PR: https://github.com/flutter/flutter/pull/65658
- [x] Root-level app widgets, PR: https://github.com/flutter/flutter/pull/65658
  - WidgetsApp
  - CupertinoApp
  - MaterialApp
- [x] Migrate Veggie Seasons App (required for https://github.com/flutter/samples/pull/433)
  - [x] CupertinoTabView, PR: https://github.com/flutter/flutter/pull/67169
  - [x] CupertinoTabScaffold, PR: https://github.com/flutter/flutter/pull/67770
- [x] Widgets for the Flutter Gallery app to make the app restorable
  - [x] [Reply] State restorable pages, PR: https://github.com/flutter/gallery/pull/368, OpenContainer not supported
  - [x] Gallery Demo Pages, PR: https://github.com/flutter/gallery/pull/378, https://github.com/flutter/gallery/pull/379, https://github.com/flutter/gallery/pull/382, https://github.com/flutter/gallery/pull/409, https://github.com/flutter/gallery/pull/408
    - [x] RestorableBoolN for Checkbox: PR - https://github.com/flutter/flutter/pull/71653, https://github.com/flutter/gallery/pull/388
    - [x] TextFormField/Form: https://github.com/flutter/gallery/pull/476
    - [x] Dialog/Pickers: https://github.com/flutter/flutter/issues/70918, https://github.com/flutter/gallery/pull/476
    - [x] DataTable (selected row count data): https://github.com/flutter/flutter/issues/70916 
    - [x] Drawer/endDrawer: https://github.com/flutter/flutter/issues/70925
  - [x] Other mini apps: 
    - [x] Shrine: https://github.com/flutter/gallery/pull/389
    - [x] Fortnightly: https://github.com/flutter/gallery/pull/390
    - [x] Rally: https://github.com/flutter/gallery/pull/394, `OpenContainer` not supported
    - [x] Crane: https://github.com/flutter/gallery/pull/392, ~StaggeredGridView not state restorable yet~
      - [x] StaggeredGridView: https://github.com/letsar/flutter_staggered_grid_view/pull/148, https://github.com/flutter/gallery/pull/396
    - [x] Starter: https://github.com/flutter/gallery/pull/391, Drawer is not state restorable yet

Could be simpler:
- FloatingActionButton contains constants for different configurations, but it's not an enum so it's not easily accessible for state restoration unless a List/Map of some sort from String/int index-to-location is created.

## Documentation

- [x] Hot reload/restart doesn't work with state restoration

## Integration with other platforms

- [x] enable state restoration for iOS (https://github.com/flutter/flutter/issues/62915)

**Punted:**

- integrate state restoration with Nav 2.0 for the web (see also https://github.com/flutter/flutter/issues/65776)
     - may require https://github.com/flutter/flutter/issues/33615
- PageStorage (used by some `Scrollable`s to retain page state): https://github.com/flutter/flutter/issues/70520
- Support state restoration for `OpenContainer` in animations package: https://github.com/flutter/flutter/issues/69924
- BottomSheet: https://github.com/flutter/flutter/issues/70915
- Time Picker: https://github.com/flutter/flutter/issues/80564

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
After getting one of the gallery apps partially state restorable through https://github.com/flutter/gallery/pull/368, I found a few nice-to-have features that I would like to include in this issue thread:
1. **Hot reload/restart functionality when working on state restoration**: While defining the `toPrimitives` and `fromPrimitives` methods for `RestorableListenable`, I found out through trial and error that hot reload/restart did not reflect my updated code. I had to rerun the app from scratch to observe any changes I made to those methods.
2. **Improved documentation on the StandardMessageCodec**: Since only objects that are serializable through the `StandardMessageCodec` can have its state restored, it was tedious to figure out how to store enums and had to look up how to read `Maps` and `Lists`, since they had to be cast from `dynamic`. It would be nice to have improved documentation on how to handle the common cases.

**Comment by pedromassango** [comment]
@goderbauer any plans to support state restoration for SnackBars?

**Comment by shihaohong** [comment]
@pedromassango I don't think SnackBars would be supported (or, at least, it wouldn't be a high priority) since its a temporary widgets that fades from the user's view rather quickly. Persistent pages, modals, or page state (like scroll offset) are examples of features/widgets that would benefit from state restoration.

**Comment by pedromassango** [comment]
[suggestion][question]

Shouldn't we get a warning if we use a `RestorationScope` in any part of the application without having a `RootRestorationScope` as the parent widget (anywhere up in the tree) since he is the one who makes the `rootBucket` available in the widget tree?

For example, I almost got confuse why the code bellow was not restoring its state:

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        title: 'Flutter Demo',
        home: RestorationScope(restorationId: 'home', child: HomePage()),
      ),
    );

class HomePage extends StatefulWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with RestorationMixin {
  RestorableInt _counter = RestorableInt(0);

  @override
  String get restorationId => '_home_Page';

  @override
  void restoreState(RestorationBucket oldBucket, bool initialRestore) {
    registerForRestoration(_counter, '_counter');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
            child: Text('Contador: ${_counter.value}'),
          onTap: () => setState(() => _counter.value -= 1),
        ),
      ),
    );
  }
}

```

Until I realised that it was missing the `RootRestorationScope`.

Is this worth to file a new issue?

**Comment by goderbauer** [comment]
Unfortunately, we cannot produce a warning in that case. You may be using a widget from a third-party library that supports state restoration and hence uses a RestorationScope, but your own app my not use state restoration and hence there's no RootRestorationScope.

**Comment by Hixie** [comment]
(triage meeting update: @shihaohong says "michael and i are working through the remaining mini apps on the gallery, as well as any material widgets that need to be updated to support state restoration.")

**Comment by Hixie** [comment]
(This is on pause until after Feb 17th.)

**Comment by shihaohong** [comment]
I'm back from vacation and can resume work on this issue!

**Comment by shihaohong** [comment]
I've been busy preparing for a Flutter Engage presentation. I should hopefully have the time to come back to this tomorrow onward. `TextFormField`, `Form` and the date pickers are the next on my to-do list. Bottom sheet is less of a priority because it's a UI component that isn't persistent

**Comment by shihaohong** [comment]
Update: Just landed Material Date Picker state restoration -- next steps would be to look at the Material DateRangePicker, as well as the Cupertino date picker

**Comment by shihaohong** [comment]
Another update: Landed DateRangePicker, as well as code sample templates for state restoration samples. Currently working through state restoration for `TextFormField` and `FormField`.

**Comment by esDotDev** [comment]
Before I start a new issue on this, I was wondering if there are plans to enable us to use the Restoration API in a general purpose sense (not strictly tied to app restart).

What I would really like to do, is re-use this same mechanism to maintain basic state on my various top-level StatefulWidgets, so I can just throw up HomePage or SettingsPage, and it will restore all it's previous scroll positions, animators and textFields. 

Currently it's cumbersome to do this by hand, or requires use of an IndexedStack where all views are kept alive in memory and in the tree.

**Comment by goderbauer** [comment]
@esDotDev We've discussed using the State Restoration Mechanism for that before, but have not implemented that yet. Can you file a new issue for that use case?

**Comment by esDotDev** [comment]
Done :) https://github.com/flutter/flutter/issues/62916#issuecomment-818012330

**Comment by shihaohong** [comment]
Closing this issue out as the core work is finally done 🥳.

That being said, any outstanding state restoration issues will be continuously worked on, and do not hesitate to file new issues if there are concerns or features that has not been addressed :)
