### ISSUE TITLE
No example of Stepper in search

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6291]
From our material design catalog, I tried to find examples of Steppers: https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=path%3Aexamples+%22new+Stepper%22&type=Code

No results were displayed.

1) Do we have an example, and is search just not finding it?

2) Should we build an example?  (if not, should we change the link on the catalog?)

**Comment by sethladd** [comment]
cc @HansMuller @InMatrix

**Comment by Hixie** [comment]
I think maybe we never added this to the gallery? We should add an example to the gallery.

**Comment by HansMuller** [comment]
Steppers were added in mid September, https://github.com/flutter/flutter/pull/5765

I'll add a gallery demo.

**Comment by eseidelGoogle** [comment]
Confirmed.  I don't see an example as of ecdf99c326417e07495e37fd60b8a707aef83aba.

**Comment by sethladd** [comment]
Closing this, as we now have a Stepper, and it appears in our Widget Gallery: https://flutter.io/widgets/material/
