### ISSUE TITLE
Show a SnackBar across Scaffolds

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#62921]
[Design Doc](https://docs.google.com/document/d/1TCH0T-X42z96lAcSkFttHAQMJ0MsvMojDKa6F4IQI3Y/edit?usp=sharing) outlining the proposal
Related to https://github.com/flutter/flutter/issues/57218
WIP PR https://github.com/flutter/flutter/pull/62226

The feature will make it possible to distribute SnackBar notifications across multiple Scaffold instances.

**Comment by goderbauer** [comment]
SEO: ScaffoldMessenger

**Comment by Piinks** [comment]
Closed #62226 to preserve original proposal and refactor based on feedback in the design doc. Will link new PR when ready.

**Comment by Piinks** [comment]
Weekly update :)
Now working on removing *all* or as much of the existing `SnackBar` API out of the `Scaffold` and into `ScaffoldMessenger`. There will be a new, updated design doc, as I wanted to preserve the original proposal. Will link all once ready.

**Comment by Piinks** [comment]
Also: this will be a breaking change in the updated implementation, so I'm also working on migration guide etc. :)

**Comment by Piinks** [comment]
Re-opening as the change was reverted.

**Comment by Piinks** [comment]
This is going to require a more thoughtful migration plan. The new and old API will need to peacefully coexist while customers are migrated, with the old API eventually being deprecated.

**Comment by markbeij** [comment]
I'm really looking forward to the ScaffoldMessenger. When will 1.23 be released?
