### ISSUE TITLE
Flutter project not creating android directory

### ISSUE THREAD

**Issue by imabhishekkumar** [flutter/flutter#62928]
## Steps to Reproduce

I'm using Android Studio V4.0
1. Start a new Flutter project
2. Flutter Plugin

## Logs

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (3 available)

• No issues found!

**Comment by darshankawar** [comment]
Hi @imabhishekkumar,
Please follow-up in [this](https://github.com/flutter/flutter/issues/61405) ticket regarding the issue you are facing. There's a [solution](https://github.com/flutter/flutter/issues/61405#issuecomment-658412180) mentioned on how to create a Flutter plugin project that generated `android` folder.

See if it works for you and resolves the issue.

**Comment by imabhishekkumar** [comment]
The command `flutter create --org com.example --template=plugin --platforms=android,ios -a kotlin hello` solves the issue.

**Comment by darshankawar** [comment]
Closing this as fixed.
