### ISSUE TITLE
How to add physics property to webview_flutter widget?

### ISSUE THREAD

**Issue by AshaLiu** [flutter/flutter#62940]
It seems that this component does not expose the api to let me set physics property.

I want to disable this effect.

can anyone  help me, thanks

**Comment by darshankawar** [comment]
Hi @AshaLiu,
Can you please elaborate on the issue, like what exactly are you trying to achieve and how `physics` property would help in that ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
