### ISSUE TITLE
Strange interaction between FittedBox and LazyBlock

### ISSUE THREAD

**Issue by alanlgardner** [flutter/flutter#6294]
There is some strange interaction where LazyBlock is dynamically adjusting widgets during scrolling, which messes with FittedBox calculations.

## Steps to Reproduce

```dart
import 'dart:async';

import 'package:flutter/widgets.dart';

int acolor(int index, int offset) =>
    0xFF000000 + (0xFFFFFF ~/ (index + offset + 1));

Widget lazy() => colorized(
    0xFFFF1111,
    new LazyBlock(
        delegate:
            new LazyBlockChildren(children: [new Text('BAD MODULE!!!')])));

Widget colorized(int color, [Widget child = null]) => new Container(
    decoration: new BoxDecoration(backgroundColor: new Color(color)),
    child: child);

Widget fittedBox(i) => new Container(
    margin: new EdgeInsets.symmetric(vertical: 10.0),
    child: new ClipRect(
        child: new SizedBox(
      width: 300.0,
      height: 400.0,
      child:
          new Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
        new SizedBox(height: 50.0, child: colorized(acolor(i, 0))),
        new Flex(children: [
          colorized(
              acolor(i, 1),
              new SizedBox(
                  width: 300.0,
                  height: 350.0,
                  child: new FittedBox(
                      fit: ImageFit.cover,
                      alignment: FractionalOffset.topCenter,
                      child: new SizedBox(
                          width: 500.0, height: 800.0, child: lazy()))))
        ])
      ]),
    )));
Future main() async {
  runApp(new Stack(children: [
    new Positioned(
        top: 100.0,
        bottom: 150.0,
        left: 300.0,
        width: 300.0,
        child: new Block(children: new List.generate(10, fittedBox)))
  ]));
}
```

## Logs
None

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/alangardner/src/fuchsia/sysui/third_party/flutter
    • Framework revision d65cda2379 (6 days ago), 2016-10-06 11:29:41
    • Engine revision f97caf271c
    • Tools Dart version 1.20.0-dev.10.1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/alangardner/tools/android-sdk-linux
    • Platform android-24, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 9 • HT4A1JT03343 • android-arm

**Comment by abarth** [comment]
Note, if you wrap code in ````dart` blocks, they look prettier.

**Comment by abarth** [comment]
We should check whether https://github.com/flutter/flutter/pull/6302 fixes this issue as well.

**Comment by abarth** [comment]
I ran this example after https://github.com/flutter/flutter/pull/6302, and it's not obvious to me that anything is still wrong.  I'm going to close this issue.  Please re-open it if https://github.com/flutter/flutter/pull/6302 doesn't solve the problem for you.
