### ISSUE TITLE
“flutter doctor“ output shows unreadable codes 

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#62958]
on Windows7:
![图片](https://user-images.githubusercontent.com/48232744/89393667-b5206f00-d73d-11ea-995b-df0154bd7ac2.png)
![图片](https://user-images.githubusercontent.com/48232744/89393738-c9646c00-d73d-11ea-978c-c90d7049bdb5.png)

on secureCRT terminal connecting to macOS:
![图片](https://user-images.githubusercontent.com/48232744/89394141-498ad180-d73e-11ea-931f-99f28d877fa2.png)

however, everything is OK in macOS GUI terminal:
![图片](https://user-images.githubusercontent.com/48232744/89393972-10eaf800-d73e-11ea-9988-23b96b49cee5.png)

I'm using windows 7 chinese edition:
![图片](https://user-images.githubusercontent.com/48232744/89394354-8f479a00-d73e-11ea-917b-f3ddbcad798e.png)

macOS version:
![图片](https://user-images.githubusercontent.com/48232744/89394427-a6868780-d73e-11ea-918c-a90ebf591c3f.png)

**Comment by heroqin** [comment]
I've found the reason：
![图片](https://user-images.githubusercontent.com/48232744/91028996-cd92f380-e630-11ea-9e4c-109a1bdc1540.png)

if I select truetype font, the output is normal, but if I select bitmap font, then the output has unreadable codes.

**Comment by darshankawar** [comment]
@heroqin 
Can you confirm if this is still an issue using latest stable version of the framework. The framework has added considerable support for windows platform since this issue was filed.
