### ISSUE TITLE
Stepper widget, not able to change elevation in horizontal mode.

### ISSUE THREAD

**Issue by Gorter-dev** [flutter/flutter#62957]
## Steps to Reproduce

Create a flutter app.
Implement the stepper widget.
Set type to StepperType.horizontal

Result:
No option to to change elevation.

I made a PR where I made it possible to do this.

[#62856](https://github.com/flutter/flutter/pull/62856)

**Comment by Gorter-dev** [comment]
Could this PR be reviewed?

**Comment by urmamb** [comment]
Try this
`Theme(
            data: ThemeData(
              canvasColor: Colors.transparent,
              shadowColor: Colors.transparent
            ),
            child: Stepper()`

**Comment by Gorter-dev** [comment]
@urmamb Thanks a lot! This works, but I think some users may want to have a shadowColor set and change the elevation. Therefore I think my PR is still valid.
