### ISSUE TITLE
Add a --bugs flag to "flutter doctor"

### ISSUE THREAD

**Issue by alanlgardner** [flutter/flutter#6296]
## Steps to Reproduce

When running "flutter doctor" the output includes potentially sensitive path name information which provides no value for bugs. The instructions should tell you to run a command that excludes information irrelevant to bugs. For instance:

flutter doctor --bugs

[✓] Flutter (on Linux, channel master)
    • Flutter at {-- PATH  REDACTED --}
    • Framework revision d65cda2379 (6 days ago), 2016-10-06 11:29:41
    • Engine revision f97caf271c
    • Tools Dart version 1.20.0-dev.10.1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at {--- PATH  REDACTED --}
    • Platform android-24, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 9 • {--ID REDACTED--} • android-arm

**Comment by abarth** [comment]
Good idea.  /cc @danrubel

**Comment by Hixie** [comment]
The path actually is often helpful (e.g. we've found bugs because the path has spaces, or non-ASCII characters, and without the actual path we'd not have been able to figure it out). I'm going to close this for now.
