### ISSUE TITLE
[web]: showModalBottomSheet not working | Exception caught by Gesture : No MediaQuery By Gesture

### ISSUE THREAD

**Issue by Shripardhi01** [flutter/flutter#62975]
Function contain showModalBottomSheet
```
void _startAddNewTransaction(BuildContext ctx) {
    showModalBottomSheet(
      context: ctx,
      builder: (_) {
        return GestureDetector(
          onTap: () {},
          child: NewTransaction(_addNewTransaction),
          behavior: HitTestBehavior.opaque,
        );
      },
    );
  }
```
Code in Scaffold
```
appBar: AppBar(
          title: const Text(MyApp._title),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () => _startAddNewTransaction(context),

              // onPressed: () => _test(),
            )
          ],
        ),
```

NewTransaction class
contains

```
import 'package:flutter/material.dart';

class NewTransaction extends StatelessWidget {
  final titleController = TextEditingController();
  final amountController = TextEditingController();

  NewTransaction(this.addTx);
  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 5,
      child: Container(
        padding: EdgeInsets.all(10),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            TextField(
              decoration: InputDecoration(labelText: 'Title'),
              controller: titleController,
            ),
            TextField(
              decoration: InputDecoration(labelText: 'Amount'),
              controller: amountController,
              keyboardType: TextInputType.number,
            ),
            FlatButton(
              child: Text('Add Transaction'),
              textColor: Colors.purple,
              onPressed: submitData,
            ),
          ],
        ),
      ),
    );
  }
}

```

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No MediaQuery widget found.
MyApp widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was:
  MyApp
The ownership chain for the affected widget is: "MyApp ← [root]"
Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of
your application widget tree.
When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
packages/flutter/src/widgets/debug.dart 217:7                                                                              <fn>
packages/flutter/src/widgets/debug.dart 228:5                                                                              debugCheckHasMediaQuery
packages/flutter/src/material/bottom_sheet.dart 658:10                                                                     showModalBottomSheet
packages/Expencer/main.dart 49:5                                                                                           [_startAddNewTransaction]
packages/Expencer/main.dart 71:32                                                                                          <fn>
packages/flutter/src/material/ink_well.dart 992:19                                                                         [_handleTap]
packages/flutter/src/material/ink_well.dart 1098:38                                                                        <fn>
packages/flutter/src/gestures/recognizer.dart 184:24                                                                       invokeCallback
packages/flutter/src/gestures/tap.dart 524:11                                                                              handleTapUp
packages/flutter/src/gestures/tap.dart 284:5                                                                               [_checkUp]
packages/flutter/src/gestures/tap.dart 219:7                                                                               handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 477:9                                                                        handleEvent
packages/flutter/src/gestures/pointer_router.dart 78:12                                                                    [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 124:9                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/gestures/pointer_router.dart 122:17                                                                   [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 108:7                                                                    route
packages/flutter/src/gestures/binding.dart 220:19                                                                          handleEvent
packages/flutter/src/gestures/binding.dart 200:14                                                                          dispatchEvent
packages/flutter/src/gestures/binding.dart 158:7                                                                           [_handlePointerEvent]
packages/flutter/src/gestures/binding.dart 104:7                                                                           [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 88:7                                                                            [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/window.dart 758:13                         _invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/window.dart 372:5                          invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 129:14                [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 479:16                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 440:21                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 210:16                <fn>
Handler: "onTap"
Recognizer:
  TapGestureRecognizer#6059c
════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while handling a gesture:[39;49m
No MediaQuery widget found.

[38;5;244mMyApp widgets require a MediaQuery widget ancestor.[39;49m
[38;5;244mThe specific widget that could not find a MediaQuery ancestor was: MyApp[39;49m
    [38;5;244mstate: _MyAppState#33ae3[39;49m
[38;5;244mThe ownership chain for the affected widget is: "MyApp ← [root]"[39;49m

[38;5;248mTypically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree.[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244mC:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_[39;49m
[38;5;244mpackages/flutter/src/widgets/debug.dart 217:7                                                                              <fn>[39;49m
[38;5;244mpackages/flutter/src/widgets/debug.dart 228:5                                                                              debugCheckHasMediaQuery[39;49m
[38;5;244mpackages/flutter/src/material/bottom_sheet.dart 658:10                                                                     showModalBottomSheet[39;49m
[38;5;244mpackages/Expencer/main.dart 49:5                                                                                           [_startAddNewTransaction][39;49m
[38;5;244m...[39;49m
[38;5;244mHandler: "onTap"[39;49m
[38;5;244mRecognizer: TapGestureRecognizer#6059c[39;49m
    [38;5;244mdebugOwner: GestureDetector[39;49m
    [38;5;244mstate: possible[39;49m
    [38;5;244mwon arena[39;49m
    [38;5;244mfinalPosition: Offset(464.0, 23.0)[39;49m
    [38;5;244mfinalLocalPosition: Offset(12.0, 23.0)[39;49m
    [38;5;244mbutton: 1[39;49m
    [38;5;244msent tap down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

**Comment by pedromassangocode** [comment]
Hi @Shripardhi01 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by Shripardhi01** [comment]
Below is output of `flutter doctor -v`
```
PS F:\FlutterApp\expencer> flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.17134.228], locale
    en-US)
    • Flutter version 1.17.5 at F:\flutter_windows\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Shri\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Shri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Redmi 5A • 58bb9e107d74 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

github repo: https://github.com/Shripardhi01/flutterApp/tree/master/Expencer

**Comment by Shripardhi01** [comment]
The issue is solved.
