### ISSUE TITLE
Accidentally Edited GeneratedPluginRegistrant.h file, xcode and flutter is not working 

### ISSUE THREAD

**Issue by ArnavS59** [flutter/flutter#62988]
I accidentally edited the GeneratedPluginRegistrant.h file, I tried undoing my mistake but I couldnt find a way to do so. My flutter app won't build. Even after creating a new project , it still shows the same errors. 

Can anyone please help me! Any help appreaciated.
<img width="1215" alt="Screenshot 2020-08-05 at 18 05 47" src="https://user-images.githubusercontent.com/59086777/89436291-51e70a80-d746-11ea-9951-2c04b03db278.png">

**Comment by GeraldoBastos** [comment]
Hey, @ArnavS59 maybe you can try to execute the `flutter build ios` to resolve your problem.

**Comment by TahaTesser** [comment]
Hi @ArnavS59 
Does this solution https://github.com/flutter/flutter/issues/62988#issuecomment-669313954 solves your issue? 
You can reset your changes by `git reset --hard` in your flutter sdk folder and then `flutter doctor -v`

**Comment by ArnavS59** [comment]
@TahaTesser @GeraldoBastos 
I used 'flutter clean' and it works perfectly but for the new projects I create but for the old projects that I already have I am getting this new error for the podfile.
<img width="1242" alt="Screenshot 2020-08-06 at 11 56 31" src="https://user-images.githubusercontent.com/59086777/89518909-e0f23200-d7db-11ea-9fac-0f88cf5264d9.png">

<img width="1383" alt="Screenshot 2020-08-06 at 12 01 29" src="https://user-images.githubusercontent.com/59086777/89519391-96bd8080-d7dc-11ea-911a-4e62429de565.png">

Could this be due to the fact that I flutter upgrade it.

**Comment by TahaTesser** [comment]
Hi @ArnavS59 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/63018
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
