### ISSUE TITLE
Support `--analyze-size` for iOS

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#62998]
right now we support `flutter build apk --analyze-size`. This prints a summary to the CLI and outputs a file `apk-analysis.json` that DevTools can parse in the Code Size tool. 

![Screen Shot 2020-08-05 at 11 03 30 AM](https://user-images.githubusercontent.com/43759233/89447728-56420200-d70b-11ea-951e-2eee13004410.png)

We should support this same functionality for IPAs.

**Comment by xster** [comment]
@jonahwilliams fixed everything :)

https://github.com/flutter/flutter/pull/63610
