### ISSUE TITLE
build_runner is failing after flutter upgrade

### ISSUE THREAD

**Issue by wolframm** [flutter/flutter#62996]
Latest flutter upgrade breaks build_runner. It finds some "Bad state: Unexpected diagnostics" and then it is waiting on a dart file from which it should generate some code, but does nothing:

json_serializable:json_serializable on lib/models/business.dart

If I remove the build-filter option, build_runner simply waits on ALL my dart files.

I ran "flutter clean". Nothing helps.

FLUTTER DOCTOR -V OUTPUT:

[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-US)
• Flutter version 1.20.0 at /Users/arne/flutter
• Framework revision 840c9205b3 (14 hours ago), 2020-08-04 20:55:12 -0700
• Engine revision c8e3b94853
• Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at /Users/arne/Library/Android/sdk
• Platform android-29, build-tools 29.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.6, Build version 11E708
• CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 47.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

COMMAND LINE OUTPUT:

arne@MacBook-Pro-Arne consumer % flutter pub run build_runner build --build-filter '/Users/arne/rebait/consumer/lib/models/*'
[INFO] Generating build script...
[INFO] Generating build script completed, took 343ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 51ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 450ms

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] json_serializable:json_serializable on lib/models/theme.dart:

Bad state: Unexpected diagnostics:
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:88:62 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:153:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:186:51 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:133:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:154:25 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:18:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:64:4 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:168:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:47:14 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:159:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:132:37 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:118:48 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:19:11 - This requires the 'non-nullable' language feature to be enabled.
[SEVERE] json_serializable:json_serializable on lib/models/theme.dart:

Bad state: Unexpected diagnostics:
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:152:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:88:62 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:153:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:186:51 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:133:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:154:25 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:18:17 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:64:4 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:168:32 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:47:14 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:159:38 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:132:37 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:118:48 - This requires the 'non-nullable' language feature to be enabled.
/Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:19:11 - This requires the 'non-nullable' language feature to be enabled.
[INFO] 2.1s elapsed, 1/2 actions completed.
[INFO] 3.2s elapsed, 1/2 actions completed.
[INFO] 4.3s elapsed, 1/2 actions completed.
[INFO] 5.4s elapsed, 1/2 actions completed.
[INFO] 6.5s elapsed, 1/2 actions completed.
[INFO] 7.6s elapsed, 1/2 actions completed.
[INFO] 8.7s elapsed, 1/2 actions completed.
[INFO] 9.8s elapsed, 1/2 actions completed.
[INFO] 10.9s elapsed, 1/2 actions completed.
[INFO] 11.9s elapsed, 1/2 actions completed.
[INFO] 13.0s elapsed, 1/2 actions completed.
[INFO] 14.1s elapsed, 1/2 actions completed.
[INFO] 15.2s elapsed, 1/2 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:

json_serializable:json_serializable on lib/models/business.dart
[INFO] 17.2s elapsed, 1/2 actions completed.
[INFO] 18.2s elapsed, 1/2 actions completed.

**Comment by Sartori-RIA** [comment]
same here :(

**Comment by ichitaka** [comment]
Similar here. My outputs look different tho. Here an extract:
```
../../tools/flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../tools/flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not found: 'package:characters/characters.dart'
export 'package:characters/characters.dart';
^
../../tools/flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
../../tools/flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^

```

I actually thought that the upgrade failed, as it took quite long but also I found out that I had some network issues, while I was upgrading. Similar flutter doctor output.

**Comment by aseef17** [comment]
> Similar here. My outputs look different tho. Here an extract:
> 
> ```
> ../../tools/flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
> import 'package:characters/characters.dart';
>        ^
> ../../tools/flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not found: 'package:characters/characters.dart'
> export 'package:characters/characters.dart';
> ^
> ../../tools/flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
> import 'package:characters/characters.dart';
>        ^
> ../../tools/flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
> import 'package:characters/characters.dart';
>        ^
> ```
> 
> I actually thought that the upgrade failed, as it took quite long but also I found out that I had some network issues, while I was upgrading. Similar flutter doctor output.
> 
> EDIT: Also tried flutter clean. No success.

Can confirm that I receive the same error. Seems like the Flutter team broke something that has to do with autofill of TextFormField in the latest stable release

**Comment by proninyaroslav** [comment]
> /Users/arne/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.

Because of this error I had to downgrade.

**Comment by JacobT14** [comment]
Adding a dependency override will fix the infinite builder:
`dependency_overrides:
  analyzer: '0.39.14'`
see https://github.com/flutter/flutter/issues/62240

**Comment by hardmen** [comment]
Same issue here

**Comment by wolframm** [comment]
> Adding a dependency override in your pubspec.yaml will fix the infinite builder:
> `dependency_overrides: analyzer: '0.39.14'`
> see #62240

Thanks, JacobT14! Going back to dart analyzer version 0.39.14 fixed it for me. So, something is broken in 0.39.16.

**Comment by cubuspl42** [comment]
The issue to track is:
https://github.com/flutter/flutter/issues/62240
