### ISSUE TITLE
Scheduler docs are missing

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#6299]
The [Scheduler docs](https://docs.flutter.io/flutter/scheduler/Scheduler-class.html) yield a Firebase 404 page.  That link comes from the [Animation docs](https://flutter.io/animations/#scheduler)

**Comment by abarth** [comment]
Thanks.  https://docs.flutter.io/flutter/scheduler/SchedulerBinding-class.html is the proper link.  Will fix.
