### ISSUE TITLE
Convert dev/update_packages.py to a flutter subcommand

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#63]

**Comment by abarth** [comment]
Do we still want this to be a flutter subcommand now that its written in dart?

**Comment by Hixie** [comment]
It's certainly not as high a priority. Dunno how much we care about whether we have just one entry-point or not. This is only needed for people working on the flutter framework itself, right?

**Comment by abarth** [comment]
Correct.

**Comment by Hixie** [comment]
I say let's not worry about it then.

**Comment by Hixie** [comment]
In fact, we might want to just drop this entire script and just have the flutter script automatically call pub get when necessary. "flutter test" does that, and I'm finding myself writing that code again for "flutter analyze".
