### ISSUE TITLE
Difficulty creating flutter application

### ISSUE THREAD

**Issue by OkekeS** [flutter/flutter#63002]
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\User
1\Desktop\flutter\sampleproject\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path=
'C:\src\flutter\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".
 
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JJ6iu

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue 
template. Thank you!                                                                       
https://git.io/JJ6iz

PS C:\Users\User 1\Desktop\flutter> flutter create sampleproject
Recreating project sampleproject...
  sampleproject\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\User
1\Desktop\flutter\sampleproject\android\app\src\main\res\mipmap-mdpi\ic_launcher.png',    
path =
'C:\src\flutter\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-mdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Users\User 1\Desktop\flutter\flutter_02.log.

**Comment by Abhishek01039** [comment]
can you please provide ` flutter doctor -v `?
Thank you

**Comment by darshankawar** [comment]
@OkekeS,
It seems you opened another issue with similar error. Check my comment in [63003](https://github.com/flutter/flutter/issues/63003)
