### ISSUE TITLE
The --isolate-filter flag is broken

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#63016]
`named_isolate_test` assumes that isolates will be printed by the tool in a particular order in response to the 'l' command to the tool. Sometimes they are and sometimes they aren't, resulting in a flaky test.

The test seems to assume that the flag `--isolate-filter` should be avoiding that issue, but it doesn't appear to behave as the test expects, and since the failure mode is flaky it isn't clear when it stopped behaving that way.

See: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/named_isolates_test.dart#L54

Successful run:
```
2020-08-04T16:14:49.119330: run:stdout: Connected views:
2020-08-04T16:14:49.119584: run:stdout:   second isolate name (isolates/755844902764335)
2020-08-04T16:14:49.119878: run:stdout:   first isolate name (isolates/1586374175207423)
2020-08-04T16:14:49.120217: run:stdout: 
2020-08-04T16:14:49.518845: run:stdout: Application finished.
2020-08-04T16:14:49.582162: "/home/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-04T16:14:49.582729: 
```

Failed run:
```
2020-08-04T16:24:33.800322: run:stdout: Connected views:
2020-08-04T16:24:33.800954: run:stdout:   first isolate name (isolates/2768993873320415)
2020-08-04T16:24:33.801343: run:stdout:   second isolate name (isolates/2845128484978191)
2020-08-04T16:24:33.811197: Task failed: --isolate-filter failed to attach to a specific isolate

Stack trace:2020-08-04T16:24:33.811339: 
2020-08-04T16:24:33.845814: bin/tasks/named_isolates_test.dart 64:7                    main.<fn>
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 169:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 101:41  _TaskRunner.run

2020-08-04T16:24:33.846076:
```

@jonahwilliams for insight into the behavior of the isolate filter and vmservice listing isolates.

/cc @mklim in case some insight can be shared despite having moved on =)

**Comment by mklim** [comment]
I think the failure is because "first isolate name" line is appearing at all. https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/named_isolates_test.dart#L63-L64 It looks like the behavior as intended is that if you pass `--isolate-filter="second isolate name"`, you would only ever see "second isolate name" in the `l` output no matter how long you waited. The success looks like it's from the first section of the test, without the filter.

**Comment by zanderso** [comment]
The `--isolate-filter` flag gets routed to the `viewFilter` field of `FlutterDevice` here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L191

But then the field is never read. It appears the application of the filter in the `views` getter of `FlutterDevice` was removed (along with the `views` getter itself entirely for good measure), and the integration test continued to pass due to luck. There was no unit test.

**Comment by mklim** [comment]
Sorry, in my first comment I missed that there was also an ordering issue causing the flake in addition to the underlying failure. The test is assuming that as soon as it sees the "second isolate name" line without seeing the first isolate it has passed, so when the second isolate happens to be printed first it's passing.

**Comment by zanderso** [comment]
@xster It looks like the `--isolate-filter` flag is probably useful for add-to-app. Have you seen any issues reported of this flag not working?

If no one has noticed that this is broken, and we don't have any other uses of this flag in our own codebase, my inclination would be to "fix" this issue by removing the flag and deleting the test.

**Comment by zanderso** [comment]
Dropping to P3 since the tree is open again.

**Comment by zanderso** [comment]
@mklim Thanks for replying, btw =)

**Comment by Hixie** [comment]
BTW see also https://github.com/flutter/flutter/issues/62613 which is about removing or documenting the secret "l" key command.

**Comment by xster** [comment]
I second. I haven't heard about this flag before nor did I receive feedback in the past regarding this filter from our customers.
