### ISSUE TITLE
[web]: Hot Reload doesn't work

### ISSUE THREAD

**Issue by enzodanjour** [flutter/flutter#63020]
When the application is running on vsCode using the terminal, the comand R, witch refeers to Hot Reload, the comand h, wich refeers to Help, doesn't works.
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Linux, locale pt_BR.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by PixelToast** [comment]
Hot reload is not currently supported on web, see #53041
