### ISSUE TITLE
Running flutter driver parallel in emulator, simulator, physical device

### ISSUE THREAD

**Issue by 3lVv0w** [flutter/flutter#63037]
## Use case

- running device test farm using flutter driver 

-  increase productivity

- use single command

## Proposal

-

**Comment by sebastianbuechler** [comment]
You can specify the debugger `launch.json` file and add compounds there.

For example:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Current Device",
			"request": "launch",
			"type": "dart"
		},
		{
			"name": "Android",
			"request": "launch",
			"type": "dart",
			"deviceId": "android"
		},
		{
			"name": "iPhone",
			"request": "launch",
			"type": "dart",
			"deviceId": "iphone"
		},
	],
	"compounds": [
		{
			"name": "All Devices",
			"configurations": ["Android", "iPhone"],
		}
	]
}
```

**Comment by darshankawar** [comment]
Hi @3lVv0w,
See [this](https://github.com/flutter/flutter/issues/33129) ticket which sounds similar to your request. Also see [this](https://github.com/flutter/flutter/issues/33129#issuecomment-515286808) comment which describes how to run flutter driver tests simultaneously on multiple devices.
Does this help to resolve your use case ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
