### ISSUE TITLE
On Nougat, apps start full screen

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6303]
Get a Nexus 6 with Nougat on it. Run `flutter create x; cd x; flutter run`.

App is full-screen (on-screen system UI fades away).

**Comment by eseidelGoogle** [comment]
Relevant code would probably be:
https://github.com/flutter/engine/blob/master/shell/platform/android/org/domokit/sky/shell/SkyActivity.java#L59
or
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/android/AndroidManifest.xml.tmpl

**Comment by abarth** [comment]
I suspect I broke this with the new platform plugin.
