### ISSUE TITLE
when flutter release background services like android has ? I am super excited for this enhancement in flutter

### ISSUE THREAD

**Issue by adnankhan74444** [flutter/flutter#63044]

**Comment by darshankawar** [comment]
Hi @adnankhan74444,
Please provide a detailed use case mentioning your requirement and how a background service as an enhancement would help to achieve it.

**Comment by adnankhan74444** [comment]
@darshankawar For Example i have to upload a video on server or firebase storage and i don't want to block a UI and uploaded a video on background service and show the uploaded progress in  notification tray. Did you get my point ?
Another Example if my internet is not connected i have to upload a form or any thing else.When internet connect will connect that form which i have shaved in sqlite i will upload on server through background service. Did you get my point ? if not please ask me i will elaborate my question further.

**Comment by darshankawar** [comment]
@adnankhan74444,
There's similar open issue describing your case, [32164](https://github.com/flutter/flutter/issues/32164).
Does that sound similar to your request ?

**Comment by adnankhan74444** [comment]
@darshankawar Yeah i was looking for this.

**Comment by adnankhan74444** [comment]
@darshankawar  Is Flutter gives any plugin to achieve that kind of services ?

**Comment by darshankawar** [comment]
@adnankhan74444, currently there's no official Flutter's plugin to provide this feature.
I'd suggest you follow-up in [32164](https://github.com/flutter/flutter/issues/32164) for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
