### ISSUE TITLE
Problem with Chinese typesetting

### ISSUE THREAD

**Issue by leetomlee123** [flutter/flutter#63045]
just like this picture

![Screenshot_20200806-144750](https://user-images.githubusercontent.com/19498940/89501088-4c270e80-d7b2-11ea-9531-9f2b330b8756.jpg)

**Comment by leetomlee123** [comment]
every line has different lineHeight

**Comment by TahaTesser** [comment]
Hi @leetomlee123 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by leetomlee123** [comment]
Flutter is already up to date on channel stable
Flutter 1.20.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 840c9205b3 (32 hours ago) • 2020-08-04 20:55:12 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

C:\Users\lxv1>flutter doctor -v
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale zh-CN)
    • Flutter version 1.20.0 at D:\flutter\flutter
    • Framework revision 840c9205b3 (32 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\asdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\asdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\lxv1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by leetomlee123** [comment]
https://oss-asq-download.11222.cn/font/package/FZXKTK.TTF

that my font url  ,use chinese chactre show it

**Comment by leetomlee123** [comment]
i use textpaint.layout to calc long text to pages
i change font.recalc page characters but it is overflow page.
i think maybe textpainter.layout cache character.but not consider font change

**Comment by TahaTesser** [comment]
Hi @leetomlee123 
Can you please provide a complete reproducible minimal code sample
Thank you
