### ISSUE TITLE
handleStatusBarTouches missing in FlutterViewController

### ISSUE THREAD

**Issue by mlf2020** [flutter/flutter#63051]
recently i update flutter to 1.17.5，when i build my project i found that function ‘handleStatusBarTouches’  is missing，has this function been removed？

**Comment by TahaTesser** [comment]
Hi @mlf2020 
You're right seems to be removed https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm 

Updated to documentation is needed https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen

**Comment by mlf2020** [comment]
But the document it not updated @TahaTesser
> https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen
![Snip20200806_1](https://user-images.githubusercontent.com/12659293/89532939-2edf5800-d825-11ea-8492-3bca2b1ba94b.png)

**Comment by krmao** [comment]
any way about this ?

**Comment by cyanglaz** [comment]
Looks like the API was removed and we introduced a fix for it so we don't need this API anymore? @gaaclarke We need to update this document tho.

**Comment by hellohuanlin** [comment]
I wrote up a Swift version here: https://github.com/hellohuanlin/put-flutter-to-work/commit/7515c37309cc839d24d969bf2f677bb897c49311, when we update the website.
