### ISSUE TITLE
Facing Error During running & building error

### ISSUE THREAD

**Issue by Anus80** [flutter/flutter#63058]
Launching lib\main.dart on LND L29 in debug mode...
AndroidManifest.xml could not be found.
Please check E:\LoginUI-master\android\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.
Exited (sigterm)

Facing THis Error Any one have solution for this??

**Comment by darshankawar** [comment]
Hi @Anus80,
The solution is in the error itself.  `Consider running "flutter create ." to create one.`
Did you try to run this command and see if it resolves the issue ?

**Comment by Anus80** [comment]
@darshankawar 
![Screenshot (10)](https://user-images.githubusercontent.com/69299607/89538201-b4f2a300-d813-11ea-98aa-32259c7265c7.png)

**Comment by Anus80** [comment]
@darshankawar Error!
![Screenshot (11)](https://user-images.githubusercontent.com/69299607/89538571-2c283700-d814-11ea-99f8-df271021d320.png)

**Comment by toannhanb7** [comment]
@Anus80 : you are missing "dot" in the command. you command should be
```flutter create .```

**Comment by darshankawar** [comment]
@Anus80, type in `flutter create .` and see if it resolves your issue.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
