### ISSUE TITLE
 use --coverage --machine together fail

### ISSUE THREAD

**Issue by NanYeYe** [flutter/flutter#63050]
when I use `flutter test --coverage --machine test/demo_test.dar` to test,
it can not create coverage file.
when I use `flutter test --coverage test/demo_test.dar` to test,
it can create coverage file.

[ my machine version ]
~ imac$ flutter --version
Flutter 1.17.0 • channel unknown • unknown source
Framework • revision e6b34c2b5c (3 months ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
-------------------------------------------------------
@NanYeYe This PR was merged in v1.15.12 and is available in the current stable.  If you are seeing problems running coverage and machine together, please file a new issue and we'll take a look.

_Originally posted by @jmagman in https://github.com/flutter/flutter/pull/51988#issuecomment-668107525_

**Comment by darshankawar** [comment]
Hi @NanYeYe,
Since your flutter version shows `unknown`, that may not mean you are on `stable` channel.
Can you try following:

1. `flutter channel stable`
2. `flutter upgrade`
3. `flutter doctor -v`. Here you should see Flutter 1.20.0 : channel stable

Once you see you are on `channel stable`, then you may verify again to see that `flutter test --coverage --machine test/demo_test.dart` is available or not.

**Comment by jmagman** [comment]
That's not necessary, e6b34c2 is 1.17.0, and https://github.com/flutter/flutter/pull/51988 merged in v1.15.12, so the combination should work.
\cc @jonahwilliams

**Comment by NanYeYe** [comment]
> That's not necessary, [e6b34c2](https://github.com/flutter/flutter/commit/e6b34c2b5c96bb95325269a29a84e83ed8909b5f) is 1.17.0, and #51988 merged in v1.15.12, so the combination should work.
> \cc @jonahwilliams

@jmagman but it really fail to create coverage file when i use --coverage and --machine together.

**Comment by jmagman** [comment]
@NanYeYe Apologies, I meant that we thought https://github.com/flutter/flutter/pull/51988 should work, but doesn't, so this issue will track your reported problem.  

We'll investigate, thanks!

**Comment by jonahwilliams** [comment]
This was fixed after 1.17.0, but definitely still works and there are integration tests that cover it
