### ISSUE TITLE
Unable to have customised theme for title in FlexibleSpaceBar

### ISSUE THREAD

**Issue by ashank96** [flutter/flutter#63055]
## Use case

I am using **FlexibleSpaceBar** for **flexibleSpace** of **SliverAppBar**, and when I am passing a TextWidget to the tile with a different style, the style does not reflect on the flexibleSpace UI being rendered. 
This is because the title inside FlexibleSpaceBar is using `TextStyle titleStyle = theme.primaryTextTheme.headline6` as `DefaultTextStyle`  which is overriding the custom style of the tile passed every time.

## Proposal
In the build method of  `_FlexibleSpaceBarState` we can just remove the `DefaultTextStyle` widget that encloses the title as its child, from the file [flexible_space_bar.dart](https://github.com/flutter/flutter/blob/beta/packages/flutter/lib/src/material/flexible_space_bar.dart) and it works like a charm for me as of now. :) 

Now I can have any title style in my **FlexibleSpaceBar**

It will be great to add this small change in the widget globally, so that people with similar requirements need not do a workaround for the same locally. 
Thanks in advance.

**Comment by darshankawar** [comment]
Hi @ashank96,
If I understand your use case correctly, you want to use a different `text style` for `FlexibleSpaceBar's` title text. I think you can customize it using `ThemeData` widget inside `MaterialApp` at root level and use it's `textTheme` property to override the default `headline6`, as below:

```
return MaterialApp(
      theme: ThemeData(
        textTheme: TextTheme(
        headline6: TextStyle(fontSize: 12, fontWeight: FontWeight.w300, color: Colors.red)
        )
      ),
```

And then use it inside `FlexibleSpaceBar's` title property as:

```
flexibleSpace: FlexibleSpaceBar(
                  centerTitle: true,
                  title: Text("Collapsing Toolbar",
                      style: Theme.of(context).textTheme.headline6),
```
Does this resolve your question ?

**Comment by ashank96** [comment]
@darshankawar Thanks for the quick response. 
Yeah that works fine only when I am using a Text widget as title. 
But in my use case I want to use other widgets as title too.

**Comment by darshankawar** [comment]
@ashank96,
Proposing to remove `DefaultTextStyle` or any other widget for that matter may not be feasible practically, since it must have been added with a purpose for other widgets to leverage.

**Comment by ashank96** [comment]
yeah then there should be another issue, to support other widgets too.
Thanks @darshankawar we can close this

**Comment by darshankawar** [comment]
Closing this based on @ashank96's suggestion.
