### ISSUE TITLE
[web] Multiple clicks required to select widget (chrome)

### ISSUE THREAD

**Issue by radvansky-tomas** [flutter/flutter#63062]
I am having issues selecting form widgets in chrome running in Run/Debug mode.

To demonstrate this, I opened sample, while running my own app in chrome
https://flutter.github.io/samples/web/form_app/#/form_widgets

Video:
https://youtu.be/NORHxnW-Sd0

If I run those samples in proper Chrome/Safari instances clicks work fine.
So I suspect this has something to do with connection between Android Studio / Flutter -> Chrome instance

**Comment by TahaTesser** [comment]
Hi @radvansky-tomas 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
