### ISSUE TITLE
Unable to run Flutter Doctor

### ISSUE THREAD

**Issue by sebastianbuechler** [flutter/flutter#63064]
I wanted to upgrade to Flutter 1.20, but it did not work. So I ran Flutter Doctor and I got an error.
## Steps to Reproduce

1. run flutter doctor in cmd

## Logs

```
```

C:\src\flutter>flutter doctor
 Checking Dart SDK version...                                                                                            
Downloading Dart SDK from Flutter engine <<<<<<< HEAD ee76268252c22f5c11e82a7b87423ca3982e51a7 ======= c8e3b9485386425213e2973126d6f57e7ed83c54 >>>>>>> 840c9205b344a59e48a5926ee2d791cc5640924c...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: flutter_infra/flutter/&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
ee76268252c22f5c11e82a7b87423ca3982e51a7 ======= c8e3b9485386425213e2973126d6f57e7ed83c54 &gt;&gt;&gt;&gt;&gt;&gt;&gt; 840c9205b344a59e48a5926ee2d791cc5640924c/dart-sdk-windows-x64.zip</Details></Error>
In C:\src\flutter\bin\internal\update_dart_sdk.ps1:68 Zeichen:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Error: Unable to update Dart SDK. Retrying...

```
```

**Comment by sebastianbuechler** [comment]
It seems there has been some problems with the local flutter git repo since i could not pull the new origin repo because of unmerged changes. 

I found this helpful: 
Go to the flutter base directory and reset the git repo:
git reset --hard origin/stable
From:
https://stackoverflow.com/questions/52397496/flutter-upgrade-fail

Afterwards flutter doctor runs smoothly and upgraded Dart and Flutter to the newest stable version.

**Comment by darshankawar** [comment]
Hi @sebastianbuechler,
Given your last message, do you feel this issue can be closed ?
Thanks.
