### ISSUE TITLE
InteractiveViewer should use Pinch to Zoom on MacBooks

### ISSUE THREAD

**Issue by kobutri** [flutter/flutter#63060]
## Use case

When you are using a MacBook you are used to zoom with with the pinch gesture we are already familiar with on mobile.

## Proposal

Use pinching on MacBooks to zoom. 
Moreover this should be the default for devices with touchpads whose drivers support pinching.

**Comment by justinmc** [comment]
Thanks for pointing this out.  I use a MacBook daily and I didn't even know that pinch to zoom was possible on the trackpad, but you're right, it works on things like Google Maps.  Hopefully Flutter already has the ability to listen to this gesture.  If so, it should be an easy fix.

In the meantime you can use two finger scroll to zoom on a MacBook.

**Comment by justinmc** [comment]
This will depend on a resolution to https://github.com/flutter/flutter/issues/23604 ([design doc](https://flutter.dev/go/trackpad-gestures
)), which will bring the ability to detect pinch gestures on a trackpad.

**Comment by justinmc** [comment]
This will be fixed with https://github.com/flutter/engine/pull/31593.

**Comment by Piinks** [comment]
The engine change landed, is this resolved now?

**Comment by Piinks** [comment]
Confirmed with customer that this now works as expected.

**Comment by justinmc** [comment]
Thanks, indeed this works now.
