### ISSUE TITLE
Workmanager status Observer

### ISSUE THREAD

**Issue by halimpuckjava** [flutter/flutter#63077]
with workmaneger plugin add observer to tack status of workmanager (start, failed, progress, complete, result)

**Comment by darshankawar** [comment]
Hi @halimpuckjava,
By workmanager, are you referring to this [plugin](https://pub.dev/packages/workmanager) ?

**Comment by halimpuckjava** [comment]
hi @darshankawar 

yes, i mean flutter workmanager, so why not add observer to track status (start, progress, failed, complete, result)

**Comment by darshankawar** [comment]
@halimpuckjava,
the plugin you are using `workmanager` is a 3rd party plugin. Please consider opening this issue in their repo (https://github.com/fluttercommunity/flutter_workmanager/issues).
Closing this, as it's not related to Flutter. If you disagree, write in comments and I'll reopen.
Thanks.
