### ISSUE TITLE
Unable to build flutter tools

### ISSUE THREAD

**Issue by Devdre1909** [flutter/flutter#63080]
Presently on the master channel, I switched to the beta channel then I run flutter upgrade to find out I can't use Linux as a device, so I switched back to the master branch, I run flutter upgrade. Then I started getting these errors: 

```
Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2
  which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```
![2020-08-06-135009_1366x768_scrot](https://user-images.githubusercontent.com/49331266/89533824-ea839600-d7eb-11ea-85d6-810355a3acec.png)

The current Dart SDK version is 2.10.0-0.0.dev.flutter-a3815b6590.

_Flutter Info before switching to the master channel_

Flutter 1.18.0-11.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2738a1148b (3 months ago) • 2020-05-13 15:24:36 -0700
Engine • revision ef9215ceb2
Tools • Dart 2.9.0 (build 2.9.0-8.2.beta)

I can't presently get any info on the master channel (which I am presently on) cause every time I run any flutter command, it tries to run pub upgrade with keeps giving error.

I am assuming the issue is that Dart SDK
 upgraded, if I can roll back to a version compatible with the dependency it should work, or the dependency should be reviewed.

**Comment by pedromassangocode** [comment]
Hi @Devdre1909 
I can't reproduce this issue on latest `master` channel.
Can you please try again:
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by Devdre1909** [comment]
Thank you. 

Tried running `flutter upgrade --force`, I got these

```
Building flutter tool...
The current Dart SDK version is 2.10.0-0.0.dev.flutter-a3815b6590.

Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2
  which requires SDK version >=2.9.0-18.0 <=2.9.10, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

I can't seem to run any flutter command again, they all try to build flutter tool.

**Comment by Devdre1909** [comment]
Fixed. 

I used git to switched branch to stable, then I run `flutter upgrade`, it worked fine, but I need to run a Linux app on flutter, so I used git to switch branch to **dev**, then run flutter upgrade again.
