### ISSUE TITLE
Flutter Web - Browser Refresh Notifier

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#63085]
## Use case

This feature can be very useful to detect browser refreshes especially for forms or text inputs. The users can be notified that their data will be lost. Also (in my case) when use packages like [flutter_screenutil](https://pub.dev/packages/flutter_screenutil), the draft data is lost upon browser refresh and errors are logged. Even navigator may be used to push a new screen every time browser refreshes, but a notifier or a callback would be way more useful and handy

## Proposal

I think this feature can be added to the dart:js or directly in the framework itself. A flutter notifier would be great and make things very much easier but using dart for this feature wouldn't hurt too. The notifier (in flutter) would work just like flutter's NotificationListener and notify its children. 
Else, a dart callback would also do. In flutter, setState can be called in the callback, to update changes.
Or in my case, I can call navigator.push in the callback to go back to the home screen from where I will navigate back to the screen.

**Comment by yjbanov** [comment]
This looks like a good idea for a plugin or a package. It can also be implemented directly using `package:js` by calling the browser API directly. The framework is probably not the right place for this functionality because it is very platform-specific.
