### ISSUE TITLE
[pigeon] Nested classes in @FlutterApi methods crash with java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [flutter/flutter#63086]
# Steps to Reproduce

Assuming the following pigeon:
```.dart
import 'package:pigeon/pigeon.dart';

class Nested {
  String data;
}

class Reply {
  Nested nested;
}

@FlutterApi()
abstract class BugApi{
  void onReply(Reply reply);
}
```

When running the application and calling `onReply` from Kotlin/Java as:
```.kt
Pigeon.BugApi api;
val nested = Pigeon.Nested()
nested.setData("hello world")
val reply = Pigeon.Reply()
reply.setNested(nested )
api.onReply(reply) { run {}}
```

The following exception is throw:
```
 java.lang.IllegalArgumentException: Unsupported value: com.example.bug.Pigeon$Nested@852d0a4
```

Looking at the code, the issue can be easily identified. In the generated code of `onReply`, the `toMap` method of the reply is correctly called. However, inside `toMap`, the `toMap` of `Nested` is **not** called. The same issue is also present in `fromMap`
```.java
// class Pigeon.BugApi
public void onReply(Reply argInput, Reply<Void> callback) {
  BasicMessageChannel<Object> channel =
      new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.BugApi.onReply", new StandardMessageCodec());
  HashMap inputMap = argInput.toMap();
  channel.send(inputMap, channelReply -> {
    callback.reply(null);
  });
}

// class Pigeon.Reply 
HashMap toMap() {
  HashMap<String, Object> toMapResult = new HashMap<>();
  toMapResult.put("nested", nested);  // should be nested.toMap()
  return toMapResult;
}

static Reply fromMap(HashMap map) {
  Reply fromMapResult = new Reply ();
  Object nested= map.get("nested");
  fromMapResult.nested= (Nested)nested; // should be Nested.fromMap((HashMap )nested)
  return fromMapResult;
}
```

**EDIT:** Uploaded files:
[flutter-doctor.txt](https://github.com/flutter/flutter/files/5035554/flutter-doctor.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/5035576/pubspec.yaml.txt)

**Comment by TahaTesser** [comment]
Hi @felix-barz-brickmakers 
Can you please provide your `flutter doctor -v` your `pubspec.yaml`
Thank you

**Comment by felix-barz-brickmakers** [comment]
@TahaTesser I have uploaded the requested files

**Comment by gaaclarke** [comment]
Should be fixed in https://github.com/flutter/packages/pull/204
