### ISSUE TITLE
AnimationController class: not able to construct

### ISSUE THREAD

**Issue by stefanodecillis** [flutter/flutter#63087]
I hope it's just me but I got this error after upgrading to Flutter version 1.20.

If you try to initialize an AnimationController variable, you will notice soon you won't be able to set **vsync**. The new attribute name it's its type **TickerProvider**. Even if you try to set it with the new name, you will get this error:

`Context: Found this candidate, but the arguments don't match.`

I think the commit d6a25ae <-> a7e868d aimed to improve null safety but probably there is something wrong.

**Comment by TahaTesser** [comment]
Hi @stefanodecillis 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/63088
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
