### ISSUE TITLE
[add2app]  FlutterViewController won't be destroyed 

### ISSUE THREAD

**Issue by yaminet1024** [flutter/flutter#63092]
# flutter doctor
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

# problem
my flutter project use add to exist app 

I just want to dispose the widget when the activity destroy so that release some provider widget.

the sample in my statefulWidget like this

```
  final GlobalKey<OverlayState> _overlayKey = GlobalKey<OverlayState>();
  OverlayEntry current;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.detached) {
      pop();
    }
  }

 @override
  Widget build(BuildContext context) {
    return Overlay(
      key: _overlayKey,
      initialEntries: const <OverlayEntry>[],
    );
  }

  void pop() {
    //remove the entry the widget will not call dispose
    current.remove();
    setState(() {});
  }

  void push(OverlayEntry app) {
    assert(app != null);
    
    setState(() {
      current = app;
      overlayKey.currentState.insert(app);
    });
  }
```

it seems that the StatefulWidget that contains BlocProvider in OverlayEntry not call the dispose method after remove from entry when the detached lifecycle event coming.

it just useful when the activity is onResume,anybody help me?

**update: this is the most mini sample** 

```
void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

// for the cacheEngine,when i call SystemNavigator.pop(),the page will not
// call despose cause bloc will not call, so i  use setState to dispose last widget,but it not work util next MaterialApp show

class MyAppState extends State<MyApp> with WidgetsBindingObserver {
  bool isFirst = false;

  @override
  void initState() {
    isFirst = true;
    super.initState();
    print("MyAppState initState");
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    super.dispose();
    //this will not call util the second app show
    print("MyAppState dispose");
  }

  @override
  Widget build(BuildContext context) {
    return isFirst
        ? MaterialApp(
            home: BlocProvider(
              create: (context) {
                return CounterBloc()..add(TestEvent());
              },
              child: BlocBuilder<CounterBloc, CounterState>(
                builder: (context, state) {
                  return MaterialApp(
                    home: MyHomePage(
                      title: "dispose test",
                    ),
                  );
                },
              ),
            ),
          )
        : MaterialApp(
            home: Scaffold(
              appBar: AppBar(
                title: Text("wrong"),
              ),
              body: Center(
                child: Text(
                    "the last materialApp only dispose when this app show"),
              ),
            ),
          );
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.detached) {
      // setState seems not used
      setState(() {
        isFirst = false;
      });
    }
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void dispose() {
    super.dispose();
    print("dispose");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(

        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            CupertinoButton(
                child: Text("pop"),
                onPressed: () {
                  SystemNavigator.pop();
                })
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class CounterBloc extends Bloc<CounterEvent, CounterState> {
  CounterBloc() : super(CounterInitial());

  @override
  Stream<CounterState> mapEventToState(
    CounterEvent event,
  ) async* {
    // TODO: implement mapEventToState
  }

  @override
  Future<void> close() {
    //this will not call when the second app show
    print("close");
    return super.close();
  }
}

```

**Comment by TahaTesser** [comment]
Hi @yaminet1024 
Can you please provide a complete reproducible minimal code sample from module and native code 
Thank you

**Comment by yaminet1024** [comment]
> Hi @yaminet1024
> Can you please provide your `pubspec.yaml` from module, a complete reproducible minimal code sample from module and native code
> Thank you

Hi,this  is the minimal code sample:
https://github.com/yaminet1024/flutter_lifecycle_test
 the `pubspec.yaml` is

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.1
```

the first stateful widget will not dispose after I use cacheEngine, so that the blocProvider will not call the dispose method.
for this exception, I set a var to change and setState the new widget after the lifecycle destroy, but it seems that the last widget dispose only you start the flutterActivity.

you can get the example exception for this
startFlutterActivity-> pop Activity (SysemNavigator.pop() the widget will not dispose )-> startFlutterActivity(the last page widget dispose util the second widget show)

thanks

**Comment by TahaTesser** [comment]
hI @yaminet1024 
Thanks foe code sample 
<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_stable
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by yaminet1024** [comment]
this will also not dispose in iOS yet

**Comment by shi1234ww** [comment]
@TahaTesser  Hi , So Is there any solution for this problem?

**Comment by lorant-csonka** [comment]
I experience the same issue. I tried to create a workaround [like this](https://github.com/flutter/flutter/issues/14720#issuecomment-365857592), but it doesn't solve the problem.

**Comment by AlanJN** [comment]
Is this problem solved? I also encountered the same problem as #65829

**Comment by BurykinNikolay** [comment]
Same problem.
I'm trying to use flutter modules in a native application. There is no way to destroy engines.

**Comment by ruiq** [comment]
Same problem.
I'm trying to use flutter modules in a native application with FlutterEngineGroup. There is no way to destroy engines.

**Comment by Limvunhoy** [comment]
Is this problem solved?

**Comment by ljmatan** [comment]
Camera stays active, deactivate nor dispose are getting called, this is really bad

**Comment by ljmatan** [comment]
What finally appears to destroy the controller is opening the ViewController object again. I'm afraid the best workaround would be to just do Navigator.pop(context) through a channel which would ensure at least dispose is getting called and would hopefully release some app resources.

**Comment by felipecastrosales** [comment]
updates in this, @TahaTesser?

**Comment by dodatw** [comment]
Is there any good solution.
I can't reset the stats when using FlutterEngine, every time it opens it for the second time it shows the previous state.
I need to use other workarounds to force maintenance of UI state.

**Comment by felipecastrosales** [comment]
@dodatw can you explain this better (or in more details)?

**Comment by darshankawar** [comment]
@yaminet1024 Hello,

I tried to verify this issue using latest stable version of the framework (3.7.12) to know if the issue you reported still persists or not, but while running the repo you shared, I am getting below message:

```
dhs@Dhss-MacBook-Pro flutter_lifecycle_test % flutter run
Resolving dependencies... 
The lower bound of "sdk: '>=2.1.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.1.0-86.0.dev) only supports null safety.

For details, see https://dart.dev/null-safety
dhs@Dhss-MacBook-Pro flutter_lifecycle_test % 

```
Since this is quite an old issue and there have been numerous updates made to the framework since this issue was logged including null safety, the repo will need to be updated to be able to run on latest version. So if by any chance you can confirm at your end on latest version to see if the issue still persists, please provide us an updated code sample or repo that we can use to verify this behavior properly.

Everyone other than OP too in this threa, who can provide a latest / updated code sample or a repo that we can clone, would be helpful to analyze and properly address this issue further.

Thanks.
