### ISSUE TITLE
[plugins/google_sign_in] After upgrading to 1.20 got build errors on beta channel

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#63093]
After upgrading to 1.20 got build errors on beta channel:
```
* What went wrong:
Running Gradle task 'assembleDebug'...                                                                              
A problem was found with the configuration of task ':google_sign_in:compileDebugJavaWithJavac'.
Running Gradle task 'assembleDebug'...                                                                              
> File '/Users/jimmyff/Development/onescene/app/build/google_sign_in/intermediates/annotation_processor_list/debug/annotationProcessors.json' specified for property 'processorListFile' does not exist.

```

Switching to stable channel resolved my issue.

**Comment by darshankawar** [comment]
Hi @jimmyff,
Glad to know it's working for you. In`beta` if you are still experiencing the issue, can you try [this](https://github.com/flutter/flutter/issues/59443#issuecomment-644609716) solution and see if it works for you ? 
Also if switching to stable solves the issue, do you feel this issue can be closed ?
Thanks.

**Comment by jimmyff** [comment]
Yep happy to close. Just wanted to flag it incase you guys weren't  aware of it.

**Comment by deepikadt** [comment]
I am on the stable channel and still experiencing this issue. 


* What went wrong:
A problem was found with the configuration of task ':video_player:compileDebugJavaWithJavac'.
> File '/Users/apple/Desktop/healthcare/build/video_player/intermediates/annotation_processor_list/debug/annotationProcessors.json' specified for property 'processorListFile' does not exist.

My app was working fine. I released a build for ios and after then when I run the app in debug mode in android then I got this error.
