### ISSUE TITLE
Flutter web doesn't hot restart

### ISSUE THREAD

**Issue by arjendevos** [flutter/flutter#63095]
When i run the website it does load but when i edit the files and do a hot restart it keeps loading and never stops.

## Steps to Reproduce

1. Run `flutter run`.
2. Choose `chrome.`
3. Website load.
4. Edit something in your files
5. Press "r" in terminal.

**Expected results:** `Performing hot restart... 6.43ms (!)`

**Actual results:** `Performing hot restart...  (This is taking an unexpectedly long time.)`
and then it never stops loading

<details>
  <summary>Logs</summary>

[  +95 ms] executing: [C:\Program Files\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 916c3ac648aa0498a70f32b5fc4f6c51447628e3
[   +1 ms] executing: [C:\Program Files\Flutter\flutter/] git tag --contains HEAD
[ +204 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.20.0
           1.20.0-7.4.pre
[   +7 ms] executing: [C:\Program Files\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Program Files\Flutter\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +74 ms] executing: [C:\Program Files\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] executing: C:\Users\arvoc\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +42 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] Multiple devices found:
[  +29 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +1 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
[   +1 ms] Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52
[   +1 ms] [0]: Web Server (web-server)
[        ] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[  +21 ms] Please choose one:
[   +1 ms]  [0|1|2]
[   +2 ms] : 
[+21919 ms] flutter analyze
[   +1 ms] Please choose one:
[   +1 ms]  [0|1|2]
[        ] : 
[+4965 ms] 1
[  +67 ms] Found plugin flutter_web_image_picker at C:\Program Files\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_image_picker-0.0.2\
[  +57 ms] Found plugin flutter_web_image_picker at C:\Program Files\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_image_picker-0.0.2\
[  +46 ms] Generating C:\Program Files\Flutter\dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +63 ms] Launching lib\main.dart on Chrome in debug mode...
[  +54 ms] Updating assets
[  +75 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +4 ms] Syncing files to device Chrome...
[   +8 ms] Found plugin flutter_web_image_picker at C:\Program Files\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_image_picker-0.0.2\
[  +20 ms] Found plugin flutter_web_image_picker at C:\Program Files\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_image_picker-0.0.2\
[  +12 ms] Generating C:\Program Files\Flutter\dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +45 ms] <- reset
[   +5 ms] C:\Program Files\Flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Program Files\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\Program Files\Flutter\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\arvoc\AppData\Local\Temp\flutter_tools.6d8a0064\flutter_tool.15ed3375\app.dill --libraries-spec file:///C:/Program%20Files/Flutter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages   
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root C:\Users\arvoc\AppData\Local\Temp\flutter_tools.6d8a0064\flutter_tools.45ce2ed --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform       
file:///C:/Program%20Files/Flutter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +18 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+6893 ms] Syncing files to device Chrome... (completed in 6.997ms, longer than expected)
[   +1 ms] Synced 24.1MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[ +188 ms] [CHROME]:
[   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:62244/devtools/browser/27a58271-128e-4a6b-8ff9-a5734759893e
[+5183 ms] Debug service listening on ws://127.0.0.1:62267/yrmQSqQ47TQ=

[ +177 ms] Debug service listening on ws://127.0.0.1:62267/yrmQSqQ47TQ=
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] �🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".

```
```

```
```

[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale nl-NL)
    • Flutter version 1.20.0 at C:\Program Files\Flutter\flutter
    • Framework revision 916c3ac648 (5 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\arvoc\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\arvoc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\arvoc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!

```
```

</details>

**Comment by MaxAuer** [comment]
@arjendevos could you resolve this? I have the issue very often but can not reproduce it consistently and I have no idea what is causing it. Sometimes hot restart works, sometimes not.
