### ISSUE TITLE
Flutter is showing "FAILURE: Build failed with an exception."

### ISSUE THREAD

**Issue by iamaboyeji** [flutter/flutter#63107]
flutter is showing **> FAILURE: Build failed with an exception.** 

**This is the full message**

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

**Below is this execution code after the instance at above**

> Exception: Gradle task assembleDebug failed with exit code 1

This is the image below for more clarity.

![main dart - hello_flutter - Visual Studio Code 8_6_2020 6_52_29 PM](https://user-images.githubusercontent.com/65618547/89565226-2d5a6380-d816-11ea-923e-796a80c04c56.png)

**and i am  also not seeing the launch.json folder**

Thanks

#63107 
@pedromassangocode @sethladd @FlutterIssues

**Comment by pedromassangocode** [comment]
Hi @iamaboyeji 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by iamaboyeji** [comment]
@pedromassango  thank you sir, i will

**Comment by iamaboyeji** [comment]
**flutter run --verbose**

`PS C:\Users\USER\Documents\Practice\Mobile\Flutter\hello_flutter> flutter run --verbose
[ +108 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +553 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[   +6 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +769 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[  +21 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +182 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +2 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[ +145 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +317 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +257 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] stable
[ +177 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +70 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +30 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +163 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +156 ms] List of devices attached
[   +8 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +80 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +138 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +68 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +42 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +81 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +40 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +39 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +190 ms] No supported devices connected.
[  +39 ms] "flutter run" took 1,814ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:703:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

**pubspec.yaml**

`name: hello_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

This is the requested code sir. @pedromassango  @pedromassangocode

**Comment by iamaboyeji** [comment]
Thanks @pedromassango @pedromassangocode

**Comment by pedromassangocode** [comment]
Hi @iamaboyeji 
Can you please provide your `flutter doctor -v`.
Thank you

**Comment by iamaboyeji** [comment]
hello everyone, i am closing this issue, i have successfully resolved it, thanks @pedromassangocode @pedromassango 

to prevent any further re-occurrence on this issue,  i am providing the solutions i used. 

**after creating the project, inside the graddle folder, check wrapper, then check graddle properties, in this folder check for graddle version. after doing this check

**Comment by iamaboyeji** [comment]
hello everyone, i am closing this issue, i have successfully resolved it, thanks @pedromassangocode @pedromassango 

to prevent any further re-occurrence on this issue,  i am providing the solutions i used. 

**after creating the project, inside the graddle folder, check wrapper, then check graddle wrapper properties, in this folder check for graddle version. after doing this check this path in your system say;**
> C:\Users\USER\.gradle\wrapper\dists
_**note: this is for my system check, your respective gradle\wrapper\dists folder in your system**_
>
**then check if the gradle version found in your project **gradle-wrapper-properties**, if it is not the same maybe you should download the version found in the gradle-wrapper-properties folder in your project, then after downloading it relocate it without unzipping to the respective **C:\Users\USER\.gradle\wrapper\dists folder** in your system, then restart your system. after restarting, then run `flutter run` in your ide terminal 
> mine is VS code 
>
_note this may also  be caused by a new update in android studio, if this is the case as it was for a friend of mine, just consider upgrading android studio, it will update the gradle wrapper, then relaunch flutter in your ide, it should work properly_

**pls note i am no pro or long term user, i also asked this question and i was debugging for three days, so while trying everything i could, i finally resolved the issue with solutions stated above, so if it does not work for you, pls contact other pro flutter unblockers like @pedromassango  and the likes**

**_If you have any questions i am available if i can answer_**
**Thank you**

**Comment by FARIDJADDA** [comment]
### Good issue 

`Flutter upgrade`

or

`flutter upgrade --force
`  

&

`flutter run
`  

👍👍👍
