### ISSUE TITLE
Unexpected failures in Mac Android AOT Engine & Mac Web Engine

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#63100]
I got multiple LUCI failures for one of my PRs. One of them seems like an error with a git command. The other one couldn't find vpython for some reason.

PR: https://github.com/flutter/engine/pull/20278

LUCI failures:
- https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20AOT%20Engine/6610
- https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/7490

**Comment by digiter** [comment]
Triage: assigned to current oncall.

**Comment by godofredoc** [comment]
Hi haven't seen this issue after landing: https://flutter-review.googlesource.com/c/recipes/+/6080
