### ISSUE TITLE
We should retry Firebase Test Lab tests that fail with "Infrastructure failure"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#63103]
We should retry Firebase Test Lab tests that fail with "Infrastructure failure". For example, https://cirrus-ci.com/task/5070753072676864?command=main#L64 (matrix-1gtenoqcbayvd) failed with:

```
More details are available at [https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/8055742164365635109].
WARNING: Need help for test execution [blueline-28-en-portrait]? Please join the #test-lab Slack channel at https://firebase.community/ and include execution ID [8055742164365635109] with your question.
+--------------+-------------------------+------------------------+
|   OUTCOME    |     TEST_AXIS_VALUE     |      TEST_DETAILS      |
+--------------+-------------------------+------------------------+
| Passed       | blueline-29-en-portrait | --                     |
| Passed       | griffin-24-en-portrait  | --                     |
| Inconclusive | blueline-28-en-portrait | Infrastructure failure |
+--------------+-------------------------+------------------------+
```

I asked about this on Slack as the error message suggests and was told:

> As best as I can tell, this was a spurious network error when we were processing the test results; nothing wrong with your app.
In general, retrying on infra errors might fix the issue (as it likely would have here), but there's no guarantee. We often automatically retry tests that fail like this, but we (mis-)characterized it as non-retryable in this case. Any kind of backoff would not be necessary.

cc @godofredoc

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/issues/63419#issuecomment-699761371 claims that the tests are now passing consistently.

**Comment by goderbauer** [comment]
Since https://github.com/flutter/flutter/issues/63419#issuecomment-699761371 is claiming that this is fixed and since there have been no new reports, I am closing this issue.
