### ISSUE TITLE
Flutter Web icons look pixelated on PixelBook screen (but not external monitor)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#63122]
Viewing Rive 2, I see that when I load it on my external monitor (attached to pixel book) it looks fine, but on the built in screen icons look pixelated.  @ferhatb asked me to file.

On main screen normal (100%) browser zoom:
![Screenshot 2020-08-06 at 11 19 47 AM](https://user-images.githubusercontent.com/11857803/89575905-4f86be00-d7e3-11ea-8247-d4e9921f9e99.png)

On external monitor, normal (100%) browser zoom:
![Screenshot 2020-08-06 at 11 21 02 AM](https://user-images.githubusercontent.com/11857803/89575926-56153580-d7e3-11ea-9643-8e6fa275242b.png)

Main screen at 200% browser zoom:
![Screenshot 2020-08-06 at 12 52 06 PM](https://user-images.githubusercontent.com/11857803/89576139-b60bdc00-d7e3-11ea-92b3-7f965586218a.png)

External Monitor 200% browser zoom:
![Screenshot 2020-08-06 at 12 52 22 PM](https://user-images.githubusercontent.com/11857803/89576150-ba37f980-d7e3-11ea-8639-36c440f75621.png)

I believe Rive2 uses the CanvasKit backend?

**Comment by eseidelGoogle** [comment]
I believe this is the external monitor: https://www.asus.com/us/Monitors/VG248QE/

**Comment by yjbanov** [comment]
The pixelation looks similar to one reported in https://github.com/flutter/flutter/issues/62652 for iOS/Safari 14. Wondering if it's the same issue.

@eseidelGoogle Do you see this issue when your laptop is disconnected from the external monitor? (hypothesizing device-pixel ratio confusion when a second monitor is present).

/cc @kjlubick I suspect the fix might be on the Skia side.

**Comment by eseidelGoogle** [comment]
Here is a screen shot from my pixelbook with no external monitor and the latest build of the app.  I've not restarted my pixel book.

![image](https://user-images.githubusercontent.com/11857803/89917104-44e67300-dbad-11ea-830e-b499a5be4f15.png)

**Comment by goderbauer** [comment]
It is not super-clear to me based on what we should pick the correct asset variant if not based on the reported pixel ratio.

**Comment by yjbanov** [comment]
@goderbauer I agree that we should pick the correct variable based on the device pixel ratio. However, I think the logic we use doesn't work for low DPR screens. I think the following would work better:

```dart
  String? _findNearest(SplayTreeMap<double, String> candidates, double value) {
    if (candidates.containsKey(value))
      return candidates[value]!;
    final double? lower = candidates.lastKeyBefore(value);
    final double? upper = candidates.firstKeyAfter(value);
    if (lower == null)
      return candidates[upper];
    if (upper == null)
      return candidates[lower];
    // On low DPR screens, prefer the higher resolution image because using
    // a lower resolution image results in visible scaling artifacts.
    if (value < 2)
      return candidates[upper];
    if (value > (lower + upper) / 2)
      return candidates[upper];
    else
      return candidates[lower];
  }
```

**Comment by jonahwilliams** [comment]
Re-posting some comments I made on the discord chat:

> What are we actually trying to measure here? For example, if I am trying to draw an image into a square that is 100 physical pixels x 100 physical pixels, then I should choose an image that is sized closest to that, right? if I go under, I'm going to stretch and it will look pixelated and if I go over I'm wasting memory and processor time. but instead of specifying the physical pixels of the image, our asset system specifies the device pixel ratio?

> so we are using dpr as a short cut for guessing the image physical pixels without decoding it? but if we knew the exact physical dimensions then we could always pick the best size.

**Comment by dnfield** [comment]
Also some thoughts from chat from me:

I don't think DPR is a good proxy for this on desktop (including Desktop web).

On mobile, DPR is widely used to constrain logical screen size. On Desktop, it is rarely used that way - desktop idioms assume more logical space is fine, small controls are fine, crowded views are fine, because worst case you have a mouse and keyboard for input and don't need to rely on touch input that will have a hard time picking specific pixels or small controls.

@yjbanov - does this affect mobile web _and_ desktop web?

I do not think we should be rounding up on mobile - the current algorithm seems correct on Android and iOS, and rounding up could result in additional memory consumption for using larger than necessary assets.

**Comment by jonahwilliams** [comment]
This definitely affects desktop web, the flutter gallery application also looks pixelated on my monitor when served in chrome

**Comment by dnfield** [comment]
Another thing that affects this: we don't snap to physical pixels.
