### ISSUE TITLE
[Flutter 1.20][iOS] TextFiel and TextFormField are auto selecting text

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#63130]
## Steps to Reproduce

1. Run the code bellow on a iOS device
2. Type "ss" in the text field.

Note: you can reproduce this by typing any text in the field.

**Expected results:** 
The typed text to no be selected

**Actual results:**
The typed text was auto-selected

<img src="https://user-images.githubusercontent.com/33294549/89581940-b4680580-d82f-11ea-865e-d7af3720dd79.gif" alt="Girl in a jacket" width="240" height="400">

<details>
  <summary>Sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: TextFormField(
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 1.20.0, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.20.0 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 840c9205b3 (2 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by goderbauer** [comment]
@pedromassango Is this iOS only, or do you also see this on Android?

**Comment by pedromassango** [comment]
> @pedromassango Is this iOS only, or do you also see this on Android?

Android works fine. I don't tested on Web and Desktop though.

**Comment by goderbauer** [comment]
I can reproduce it, looks like this only happens when you enter multiple letters quickly? If you pause in between typing letters, everything seems fine.

**Comment by pedromassango** [comment]
> I can reproduce it, looks like this only happens when you enter multiple letters quickly? If you pause in between typing letters, everything seems fine.

Most of the time yes. But even if you enter multiple letters is a space of one second or so it also happens. I think you can notice this in the GIF attached.

**Comment by goderbauer** [comment]
This PR seems related: https://github.com/flutter/flutter/pull/45354

Makes it sound like that's even intentional? /cc @LongCatIsLooong

**Comment by goderbauer** [comment]
Ah! Native does this, too. A word is highlighted if upon pressing the space bar, iOS will replace it with the autocorrect suggestion from the bar above the keyboard. I think this is fully intentional. It's not a selection, it's just a highlight to tell you that iOS will autocorrect the word.

**Comment by goderbauer** [comment]
If you turn off Auto-Correction (Settings > General > Keyboard > Auto-Correction) this goes away.

AFIKT, this should probably be closed as working as intended. :)

**Comment by slightfoot** [comment]
Is this new behaviour, I've not seen it before. Should it be highlighted in this way?

**Comment by goderbauer** [comment]
> Is this new behaviour, I've not seen it before. Should it be highlighted in this way?

Not sure when iOS started doing this, but I am seeing the same behavior in the native Mail app:

![image](https://user-images.githubusercontent.com/1227763/89586416-831e1400-d7f4-11ea-8cd7-75bbc11595f8.png)

**Comment by slightfoot** [comment]
@goderbauer Perhaps the highlight should be less opaque, its more of a color thing? looks like highlighting the text after the auto-correct is darker.

**Comment by goderbauer** [comment]
iOS seems to be using the same color for the autocorrect highlight and the selection highlight.

It does appear that FLutter's highlight for both is a little darker than the default iOS color. That'd be a different issue, though.

**Comment by pedromassango** [comment]
The autocorrect suggestions in the Flutter app  looks different with the native one if you tyme in the same word.

<img width="331" alt="Screen Shot 2020-08-06 at 23 02 01" src="https://user-images.githubusercontent.com/33294549/89587318-550ef300-d839-11ea-92e9-2e742268d97c.png">  
<img width="358" alt="Screen Shot 2020-08-06 at 23 03 50" src="https://user-images.githubusercontent.com/33294549/89587330-58a27a00-d839-11ea-89bb-1624014e1bf3.png">


This will require a new issue since this one is not valid anymore.

**Comment by pedromassango** [comment]
@goderbauer Are you ok if I close this issue and open another one for the mentioned problems?

**Comment by goderbauer** [comment]
@pedromassango sounds good.

**Comment by LongCatIsLooong** [comment]
@pedromassango this is part of https://github.com/flutter/flutter/issues/12920. The background highlight is intended (although the color is slightly off). I think it would be much less confusing when we fix the color & implement the tooltip (will be working on that shortly).

I don't think we have much control over what predictive text the ios software keyboard shows. From my experience, you can get different autocorrect suggestions even in the same application if you make the same typo a second time.

**Comment by pedromassango** [comment]
> @pedromassango this is part of #12920. The background highlight is intended (although the color is off). I think it would be much less confusing when we fix the color & implement the tooltip (I'll start working on that shortly).
> 
> I don't think we have much control over what predictive text the ios software keyboard shows. From my experience, you can get different autocorrect suggestions even in the same application if you make the same typo a second time.

Great then. Just closed https://github.com/flutter/flutter/issues/63141 as a duplicate of the one mentioned in the comment above.

**Comment by pcsosinski** [comment]
@Hixie @goderbauer @LongCatIsLooong is there a cherrypick fix we need for 1.20?  looks like this issue is a dupe so nothing to consider for CP?

**Comment by goderbauer** [comment]
@pcsosinski This was closed as "working as intended" - there's nothing to cherry pick.

**Comment by goderbauer** [comment]
I'll remove the label.
