### ISSUE TITLE
NoSuchMethodError: The method 'toFilePath' was called on null.

### ISSUE THREAD

**Issue by dhust** [flutter/flutter#63139]
## Steps to Reproduce

1. flutter run -d chrome
2. ...
3. ...

## Logs

[  +96 ms] executing: [c:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f25bd9c55c48c139524139b477d04b13e9f36b2c
[        ] executing: [c:\flutter/] git tag --contains HEAD
[ +174 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.21.0-1.0.pre
           1.21.0-5.0.pre
[   +8 ms] executing: [c:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [c:\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +65 ms] executing: [c:\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: C:\Users\Dave\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +39 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +157 ms] Generating D:\Websites\Fam\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +74 ms] Launching lib\main.dart on Chrome in debug mode...
[  +54 ms] Updating assets
[  +68 ms] Syncing files to device Chrome...
[  +33 ms] Generating D:\Websites\Fam\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +36 ms] <- reset
[   +5 ms] c:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev c:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
c:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true   
--output-dill C:\Users\Dave\AppData\Local\Temp\flutter_tools.71bd7ae\flutter_tool.cda46035\app.dill --libraries-spec
file:///c:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root C:\Users\Dave\AppData\Local\Temp\flutter_tools.71bd7ae\flutter_tools.316c864e --filesystem-scheme org-dartlang-app
--initialize-from-dill build\cache.dill.track.dill --platform file:///c:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +29 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+7043 ms] Syncing files to device Chrome... (completed in 7,142ms, longer than expected)
[   +1 ms] Synced 23.3MB.       
[        ] <- accept
[        ] Caching compiled dill
[ +176 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:50637/devtools/browser/846237f3-481e-4c1d-a2a8-eed11e6c7de2
ERROR - 2020-08-06 17:16:01.948414
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                      Object.noSuchMethod
package:dwds/src/handlers/injector.dart 51:41  DwdsInjector.middleware.<fn>.<fn>

[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.21.0-1.0.pre at c:\flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dave\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Dave\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @dhust 
This happens if you've deleted caches files 
Please checkout this [solution](https://stackoverflow.com/a/61847858)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
