### ISSUE TITLE
Request for multiple uploader

### ISSUE THREAD

**Issue by konewltd** [flutter/flutter#63155]
## Proposal

I am currently using the external packages to implement a multi-image picker. However, the package is not stable and sometimes causes platform exceptions when I am using it with other packages. Hence, I hope flutter can officially provide a way to implement multi-image picker or multiple files uploader in the future stable version.

**Comment by darshankawar** [comment]
Hi @konewltd,
This proposal sounds similar to [16054](https://github.com/flutter/flutter/issues/16054).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
