### ISSUE TITLE
flutter keep print 2 empty lines on 'Device'

### ISSUE THREAD

**Issue by BoshiLee** [flutter/flutter#63169]
flutter doctor -v 

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-TW)
    • Flutter version 1.20.1 at /Users/boshi/flutter
    • Framework revision 2ae34518b8 (27 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/boshi/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • HTC Desire 19 (mobile) • NE97S1P01318                             • android-arm64 •
      Android 9 (API 28)
    • ios 的 iPhone (mobile)  • c78f66a8a68f05fed5bc18909f239c8df502fb43 • ios           •
      iOS 13.5.1
    • iPhone 11 Pro (mobile) • 182963EC-9B7C-4FFE-BC33-8F6157C2E0AF     • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.

I faced this issue today again today. I post the old issue on [this post](https://github.com/flutter/flutter/issues/54931)
But this time I can point out this issue is only occurred on device. 

minimal complete code sample to reproduce: 
`void main() {
  print('123');
  debugPrint('12');
}`

My device is iPhone 8, seems only on iOS Devices. Android prints normally.

**Comment by pedromassangocode** [comment]
Hi @BoshiLee 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/63082).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
