### ISSUE TITLE
I have errors and unable to run my app after upgrading flutter to the latest release of 1.20.1

### ISSUE THREAD

**Issue by austinevick** [flutter/flutter#63164]
![issue 1](https://user-images.githubusercontent.com/51150248/89609171-fc5a4d00-d86e-11ea-9a9b-4338e7a1273e.PNG)
![issue 2](https://user-images.githubusercontent.com/51150248/89609173-fe241080-d86e-11ea-81ba-fcc26f676155.PNG)
![issue 3](https://user-images.githubusercontent.com/51150248/89609175-febca700-d86e-11ea-8447-d26a5d75f323.PNG)
![issue 4](https://user-images.githubusercontent.com/51150248/89609177-ff553d80-d86e-11ea-8434-d9b3494737ee.PNG)
![issue 5](https://user-images.githubusercontent.com/51150248/89609178-ffedd400-d86e-11ea-9877-7c3691c834e1.PNG)

**Comment by toannhanb7** [comment]
@austinevick : Did you try to run `flutter pub get` first?

**Comment by darshankawar** [comment]
Hi @austinevick,
Please try `flutter pub cache repair` or `flutter clean` and then `flutter run` to see if it works for you.
Thanks.

**Comment by Kiplangatdan** [comment]
> Hi @austinevick,
> Please try `flutter pub cache repair` or `flutter clean` and then `flutter run` to see if it works for you.
> Thanks.

@darshankawar Thanks, had the same issue, above suggestions resolve my problem.

**Comment by austinevick** [comment]
> @austinevick : Did you try to run `flutter pub get` first?

I did but only one app is working but I'll keep trying.

**Comment by anisioisidoro** [comment]
try reinstalling the Flutter and Dart extension

And then run the command **flutter clean**, it worked for me

**Comment by darshankawar** [comment]
@austinevick,
Please try above solution and see if it works for you.
Thanks.

**Comment by austinevick** [comment]
Thanks everyone this issue has been resolved. I will be closing it now but feel free to reopen if you encounter similar error.
