### ISSUE TITLE
Failed to find snapshot: /Users/xuemingliu/Library/Developer/CoreSimulator/Devices/CCF4F3D4-D7F8-4996-B272-42761DFED1D5/data/Containers/Bundle/Application/830B4E93-403D-4248-8555-F6B314DB46A9/swift_flutter.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin

### ISSUE THREAD

**Issue by DiaoMan00** [flutter/flutter#63160]
`flutter doctor -v`

[✓] Flutter (Channel master, 1.21.0-6.0.pre.245, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.21.0-6.0.pre.245 at /Users/xuemingliu/flutter/flutter
    • Framework revision 77b4505c80 (2 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/xuemingliu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • CCF4F3D4-D7F8-4996-B272-42761DFED1D5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!

so i do not understand why there's something wrong with 'CoreSimulator'.

**Comment by pedromassangocode** [comment]
Hi @DiaoMan00 
Can you explain what actions did you take for this to happen?
Thank you.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
