### ISSUE TITLE
Why My code not working in VS CODE in C

### ISSUE THREAD

**Issue by cjgohil** [flutter/flutter#63171]
I try to change color but my code is not working
my code is
`#include <stdio.h>

int main(){
    printf("\033[36;1;4m;Hello master]");
}`

**Comment by amanv8060** [comment]
Mark as irrelevent and close this

**Comment by cjgohil** [comment]
but why?

**Comment by amanv8060** [comment]
> but why?

Because this is not a place to ask this , it is a flutter repo and you are asking help for c code .
