### ISSUE TITLE
EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK

### ISSUE THREAD

**Issue by ajeethhacki** [flutter/flutter#63178]
Expected: exactly one matching node in the widget tree Which: means none were found but one was expected When the exception was thrown, this was the stack: #4 main..

#6 testWidgets.. (package:flutter_test/src/widget_tester.dart:140:29)

```
     IconButton(
              key: Key("profileIconKey"),
              onPressed: () {
                //this is to reset the event chiose chip selection
                Constants.eventsCurrentSelectedChoiseChip = 0;

                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) {
                      //return Profile(Strings.ProfileInitialState);
                      return ProfileNew(Strings.ProfileInitialState);
                    },
                  ),
                );
              },
              icon: Icon(CustomIcons.female_avatar_and_circle22,
                  size: 25, color: Colors.grey),
            ),
```

```
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:slc/view/dashboard/dashboard.dart';

void main() {
  Widget makeTestableWidget({Widget child}) {
    return EasyLocalization(
      child: child,
      path: 'resources/langs',
      supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')],
      fallbackLocale: Locale('en', 'US'),
    );
  }

  group("full smoke test", () {
    final notificationIcon = find.byKey(Key("notificationIconKey"));
    testWidgets(
      'dashboard 0 smoke test',
      (WidgetTester tester) async {
        await tester.pumpWidget(makeTestableWidget(
            child: Dashboard(
          selectedIndex: 0,
        )));
        expect(notificationIcon, findsOneWidget);
      },
    );
  });
}

```

**Comment by TahaTesser** [comment]
Hi @ajeethhacki 
Can you please provide your `flutter doctor -v` your `flutter test test widget_test.dart --verbose` and a complete reproducible runnable minimal code sample without using third party packages
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
