### ISSUE TITLE
[DevTools] The scrollbar of debugger page code window can not drag.

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#63177]
Or there are other ways to quickly position to a specified row(the dart file may have thousands of lines).
window10 + chrome

**Comment by pedromassangocode** [comment]
Hi @xu-baolin, 
to report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
