### ISSUE TITLE
upgrade to 1.20.1 app can not load the flutter module and creates  a new folder 

### ISSUE THREAD

**Issue by beydeng** [flutter/flutter#63176]
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (29 hours ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

My iOS podfile 
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

    # Pods for iOSFlutterHybrid

    install_all_flutter_pods(flutter_application_path)
    
end

as i run pod install,it will create a new folder on my app root;
like this :

 flutter_module
Dany/flutter_module/.ios/Flutter/podhelper.rb (the new floder)
myiOS

it seems like my app can not find podhelper.rb in the flutter_module floder,but to the new floder;

how can i solve this problem

**Comment by TahaTesser** [comment]
Hi @beydeng 
Do you have any custom pods in your podfile i am unable to reproduce the issue, app runs fine
<img width="544" alt="Screenshot 2020-08-07 at 5 22 29 PM" src="https://user-images.githubusercontent.com/48603081/89643060-97d0d980-d8d2-11ea-8f81-f1a5969fbfa8.png">

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Users/taha/Code/flutter_stable
    • Framework revision 2ae34518b8 (33 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS 14.0
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!


```

</details> 

Can you please provide your `podfile`, your `pubspec.yaml` a complete reproducible minimal code sample with steps by steps to reproduce 
Thank you

**Comment by beydeng** [comment]
@TahaTesser 
![image](https://user-images.githubusercontent.com/7223164/89745986-c4127300-dae9-11ea-945a-5f74682ac325.png)

my iOS podfile is 
# Uncomment this line to define a global platform for your project
flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, 
target "XiaobanParent" do
    # Uncomment thisline if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    # Pods for khb
    pod 'SDWebImage', '5.0.0'

    pod 'WechatOpenSDK', '1.8.7'
    pod 'AFNetworking',  '3.2.0'
    pod 'Masonry', '1.1.0'

    #pod 'PLMediaStreamingKit' 
    pod 'PLPlayerKit' 
    pod 'AMap3DMap', '6.6.0'
    pod 'AMapSearch', '6.9.0'
    pod 'AMapLocation'
    
    pod 'RongCloudIM/IMLib', '2.8.32' 
    pod 'RongCloudIM/IMKit', '2.8.32'
    
    pod 'GTSDK', '2.2.0.0'
    
    pod 'SDAutoLayout'
    pod 'ReactiveObjC'
    pod 'JJException', '0.2.8'
    pod 'BAPickView', '1.1.9'
    pod 'TZImagePickerController'
    
    pod 'CYLTabBarController', '~> 1.29.0'
    
    pod 'SDCycleScrollView','>= 1.80'
    
    # Pods for iOSFlutterHybrid

    install_all_flutter_pods(flutter_application_path)
    
end

**Comment by beydeng** [comment]
I can't find any problem in my app...

**Comment by beydeng** [comment]
![image](https://user-images.githubusercontent.com/7223164/89747283-b01e3f80-daf0-11ea-8502-0890baab5940.png)

**Comment by beydeng** [comment]
it seems like the iOS load the flutter engine module to the new floder(User),but i can't find the problem why "pod install" create the new floder(User)
![image](https://user-images.githubusercontent.com/7223164/89747353-055a5100-daf1-11ea-80c2-9c5db6ec63e7.png)

**Comment by beydeng** [comment]
As i switch V17.5,it's runs fine.

**Comment by TahaTesser** [comment]
i can reproduce this issue

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Users/taha/Code/flutter_stable
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8179i
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

**Comment by chinmaygarde** [comment]
cc @jmagman

**Comment by jmagman** [comment]
I fixed up the App.framework path problem (which https://github.com/flutter/flutter/pull/63568 also does) and it still doesn't embed the App.framework into the resulting host app, though it does make the phantom `/User/` directory go away.  The Flutter script doesn't run any `flutter` code, it just bails at `flutter_export_environment.sh: line 8: inherited: command not found`.  When I escape the `export "OTHER_LDFLAGS=$(inherited) -framework Flutter"` parenthesis, it embeds as expected.

**Comment by szotp** [comment]
Interesting, for me it would still make App.framework after printing that error:

<my directory>/app/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
Project<my directory>/app built and packaged successfully.

And the app ran fine, but I'm still using Xcode 11.

**Comment by jmagman** [comment]
@szotp you're right.  I updated https://github.com/flutter/flutter/pull/63412/ to just fix the path issue and make the test more complete.  The tests pass, and in my own local test I see the embedded App.framework.

Would you mind reviewing and validating that PR works?  I appreciate that you already did #63568, I fixed it in a slightly different way.

**Comment by jmagman** [comment]
The workaround is to use `beta`.  It's only a few commits behind `stable`.  The regression was introduced in #62372.

<img width="703" alt="Screen Shot 2020-08-12 at 9 59 03 AM" src="https://user-images.githubusercontent.com/682784/90044555-a7f60980-dc82-11ea-84d9-ed1d97960562.png">

**Comment by szotp** [comment]
Another workaround: make App.framework manually before running pod install:

```
app_framework="my_flutter/.ios/Flutter/App.framework"
mkdir $app_framework
echo "static const int Moo = 88;" | xcrun clang -x c -dynamiclib -o "${app_framework}/App" -
cd MyApp
pod install
```
