### ISSUE TITLE
Got this error when i upgraded to 1.20.1

### ISSUE THREAD

**Issue by jithinjoycy** [flutter/flutter#63188]
Unhandled exception:                                                    
Unsupported operation: serialization of generic DartType: UnknownType(?) (UnknownType)
#0      BinaryPrinter.defaultDartType (package:kernel/binary/ast_to_binary.dart:2231:5)
#1      UnknownType.accept (package:front_end/src/fasta/type_inference/type_schema.dart:82:14)
#2      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#3      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#4      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2069:7)
#5      InterfaceType.accept (package:kernel/ast.dart:7504:42)          
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#7      BinaryPrinter.visitFutureOrType (package:kernel/binary/ast_to_binary.dart:2090:5)
#8      FutureOrType.accept (package:kernel/ast.dart:7903:42)           
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#10     BinaryPrinter.visitAsExpression (package:kernel/binary/ast_to_binary.dart:1616:5)
#11     AsExpression.accept (package:kernel/ast.dart:4913:44)           
#12     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#13     BinaryPrinter.visitVariableSet (package:kernel/binary/ast_to_binary.dart:1368:7)
#14     VariableSet.accept (package:kernel/ast.dart:3144:44)            
#15     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#16     BinaryPrinter.visitExpressionStatement                          
(package:kernel/binary/ast_to_binary.dart:1795:5)
#17     ExpressionStatement.accept (package:kernel/ast.dart:5784:43)    
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#19     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#20     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1803:5)
#21     Block.accept (package:kernel/ast.dart:5823:43)                  
#22     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#23     BinaryPrinter.visitLabeledStatement (package:kernel/binary/ast_to_binary.dart:1837:5)
#24     LabeledStatement.accept (package:kernel/ast.dart:5984:43)       
#25     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#26     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#27     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1803:5)
#28     Block.accept (package:kernel/ast.dart:5823:43)                  
#29     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#30     BinaryPrinter.visitTryCatch (package:kernel/binary/ast_to_binary.dart:1954:5)
#31     TryCatch.accept (package:kernel/ast.dart:6532:43)               
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#33     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:475:7)
#34     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1327:5)
#35     FunctionNode.accept (package:kernel/ast.dart:2909:38)           
#36     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:389:10)
#37     BinaryPrinter.visitFunctionDeclaration                          
(package:kernel/binary/ast_to_binary.dart:2030:5)
#38     FunctionDeclaration.accept (package:kernel/ast.dart:6988:43)    
#39     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#40     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#41     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1803:5)
#42     Block.accept (package:kernel/ast.dart:5823:43)                  
#43     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#44     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:475:7)
#45     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1327:5)
#46     FunctionNode.accept (package:kernel/ast.dart:2909:38)           
#47     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:389:10)
#48     BinaryPrinter.visitFunctionExpression                           
(package:kernel/binary/ast_to_binary.dart:1742:5)
#49     FunctionExpression.accept (package:kernel/ast.dart:5535:44)     
#50     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#51     BinaryPrinter.visitNamedExpression (package:kernel/binary/ast_to_binary.dart:1503:5)
#52     NamedExpression.accept (package:kernel/ast.dart:3813:38)        
#53     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#54     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#55     BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1497:5)
#56     Arguments.accept (package:kernel/ast.dart:3753:38)              
#57     BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:396:10)
#58     BinaryPrinter.visitConstructorInvocation                        
(package:kernel/binary/ast_to_binary.dart:1489:5)
#59     ConstructorInvocation.accept (package:kernel/ast.dart:4154:44)  
#60     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#61     BinaryPrinter.visitNamedExpression (package:kernel/binary/ast_to_binary.dart:1503:5)
#62     NamedExpression.accept (package:kernel/ast.dart:3813:38)        
#63     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#64     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#65     BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1497:5)
#66     Arguments.accept (package:kernel/ast.dart:3753:38)              
#67     BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:396:10)
#68     BinaryPrinter.visitConstructorInvocation                        
(package:kernel/binary/ast_to_binary.dart:1489:5)
#69     ConstructorInvocation.accept (package:kernel/ast.dart:4154:44)  
#70     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#71     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:475:7)
#72     BinaryPrinter.visitReturnStatement (package:kernel/binary/ast_to_binary.dart:1944:5)
#73     ReturnStatement.accept (package:kernel/ast.dart:6491:43)        
#74     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#75     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:292:7)
#76     BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1803:5)
#77     Block.accept (package:kernel/ast.dart:5823:43)                  
#78     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:382:10)
#79     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:475:7)
#80     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1327:5)
#81     FunctionNode.accept (package:kernel/ast.dart:2909:38)           
#82     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:389:10)
#83     BinaryPrinter.writeOptionalFunctionNode                         
(package:kernel/binary/ast_to_binary.dart:484:7)
#84     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1203:5)
#85     Procedure.accept (package:kernel/ast.dart:2400:40)              
#86     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:410:10)
#87     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:301:7)
#88     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1131:5)
#89     Class.accept (package:kernel/ast.dart:1379:38)                  
#90     BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:424:10)
#91     BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:319:7)
#92     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:961:5)
#93     Library.accept (package:kernel/ast.dart:607:38)                 
#94     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:403:10)
#95     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:710:9)
#96     BinaryPrinter.writeComponentFile.<anonymous closure>            
(package:kernel/binary/ast_to_binary.dart:553:7)
#97     Timeline.timeSync (dart:developer/timeline.dart:163:22)         
#98     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:536:14)
#99     IncrementalSerializer.serialize                                 
(package:front_end/src/fasta/incremental_serializer.dart:308:13)
#100    IncrementalSerializer.writePackagesToSinkAndTrimComponent       
(package:front_end/src/fasta/incremental_serializer.dart:159:24)
#101    FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:747:31)
#102    FrontendCompiler.compile (package:frontend_server/frontend_server.dart:564:13)
<asynchronous suspension>                                               
#103    _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#104    listenAndCompile.<anonymous closure>                            
(package:frontend_server/frontend_server.dart:1201:26)
#105    _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#106    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#107    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#108    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#109    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#110    _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#111    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#112    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#113    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#114    _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:121:24)
#115    _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#116    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#117    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#118    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#119    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#120    _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#121    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#122    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#123    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#124    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#125    _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:121:24)
#126    _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#127    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#128    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#129    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#130    _StreamController._add (dart:async/stream_controller.dart:682:7)
#131    _StreamController.add (dart:async/stream_controller.dart:624:5) 
#132    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)       
#133    _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)        
#134    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#135    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#136    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#137    _StreamController._add (dart:async/stream_controller.dart:682:7)
#138    _StreamController.add (dart:async/stream_controller.dart:624:5) 
#139    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#140    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#141    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)       
#142    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)   
#143    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#144    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.                                  
the Dart compiler exited unexpectedly.

**Comment by pedromassangocode** [comment]
Hi @jithinjoycy 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/63038).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
