### ISSUE TITLE
Application build/run keeps hanging after 1.20.1 upgrade

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#63191]
`flutter doctor -v` output - [doctor.txt](https://github.com/flutter/flutter/files/5041598/doctor.txt)
`flutter run -v` output -  [run_log.txt](https://github.com/flutter/flutter/files/5041612/run_log.txt)

See the `run_log.txt` above. Once the run script reaches the last line it gets stuck. There are four dart.exe instances running: 
![image](https://user-images.githubusercontent.com/7585117/89650775-d5296d00-d8ba-11ea-8615-6c4c61e3420e.png)

Here is the `pubspec.yaml` which imports another 10 libraries. [pubspec_yaml.txt](https://github.com/flutter/flutter/files/5041672/pubspec_yaml.txt)

These are the packages that are used by the app and the libraries [libraries.txt](https://github.com/flutter/flutter/files/5041975/libraries.txt)

Is there any command line option that I could run the build with so I can get logs from the `...\dart.exe` execution?

.. and BTW I have run the clean/get several times but that does not make any difference.

**Comment by anisioisidoro** [comment]
try reinstalling the Flutter and Dart extension

And run the command  **flutter clean**, it worked for me

**Comment by anisioisidoro** [comment]
try reinstalling the Flutter and Dart extension

And then run the command **flutter clean**, it worked for me

**Comment by kostaa** [comment]
Hi 

**Is there a command line option that I could run the build with so I can get logs from the ...\dart.exe execution?**

So I can try to narrow it down to the point that is causing this problem.

**Comment by zanderso** [comment]
Last log line:
```
C:\DevTools\flutter\flutter_stable\bin\cache\dart-sdk\bin\dart.exe \
--disable-dart-dev C:\DevTools\flutter\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot \
--sdk-root C:\DevTools\flutter\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ \
--target=flutter \
-Ddart.developer.causal_async_stacks=true \
-Ddart.vm.profile=false \
-Ddart.vm.product=false \
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions \
--enable-asserts \
--track-widget-creation \
--no-link-platform \
--packages D:\[...]\.packages \
--output-dill D:\[...]\.dart_tool\flutter_build\3b825b823ed761d0a91a8ed1696fc3f8\app.dill \
--depfile D:\[...]\.dart_tool\flutter_build\3b825b823ed761d0a91a8ed1696fc3f8\kernel_snapshot.d \
package:[...]/main.dart
```

It looks like the frontend_server might be hanging?

@kostaa Do you have a small reproduction that you can share?

**Comment by kostaa** [comment]
@zanderso - this is rather a large app so to narrow it down to the bit that causing the issue while the code still compiles is a bit tricky. Just out of interest what is the purpose of of the `frontend_server`? Is there a way to add additional log traces?

**Comment by jifalops** [comment]
This happened to me on Ubuntu 20.04.

**Comment by zanderso** [comment]
@kostaa the frontend_server compiles the Dart source code to an intermediate representation that the Dart VM can read and run.

If you can't share a small repro, you might try running that command manually, verifying that it hangs, and adding the `--verbose` flag to see if we can learn anything more.

**Comment by kostaa** [comment]
@zanderso - here is the output when running the command. It does not hang and returns immediately. See below the `.dart_tool\flutter_build\3b825b823ed761d0a91a8ed1696fc3f8\`  directory content. If the `\kernel_snapshot.d package:yomneyApp/main.dart` is an input file for the process then it is not there.

```
C:\DevTools\flutter\flutter_stable\bin\cache\dart-sdk\bin\dart.exe 
--verbose 
--disable-dart-dev C:\DevTools\flutter\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot 
--sdk-root C:\DevTools\flutter\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ 
--target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false 
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions 
--enable-asserts 
--track-widget-creation 
--no-link-platform 
--packages D:\repo__at\_yomney\app_yomney\.packages 
--output-dill D:\repo__at\_yomney\app_yomney\.dart_tool\flutter_build\3b825b823ed761d0a91a8ed1696fc3f8\app.dill 
--depfile D:\repo__at\_yomney\app_yomney\.dart_tool\flutter_build\3b825b823ed761d0a91a8ed1696fc3f8\kernel_snapshot.d package:yomneyApp/main.dart

result a6d91799-e053-498b-9ab2-8e434fcd5282
Error: Error when reading '.developer.causal_async_stacks=true': The system cannot find the file specified.

.developer.causal_async_stacks=true: Error: No 'main' method found.
Try adding a method named 'main' to your program.
a6d91799-e053-498b-9ab2-8e434fcd5282

```


![image](https://user-images.githubusercontent.com/7585117/90109723-21a1fc00-dd44-11ea-8b7d-00367de4ac7f.png)

**Comment by zanderso** [comment]
It looks like you may need to add quotes around some of the command line arguments to help the shell parse them correctly.

**Comment by kostaa** [comment]
I see ... was not paying much attention to the content of the command. Anyway once I quote the arguments I get 
"result 4a9266ad-712a-4f4f-b305-a60e0b6f6a64" and the command keeps running.

**Comment by kostaa** [comment]
Never managed to get to the bottom of this but just upgraded to the latest stable release and the problem is gone.

![image](https://user-images.githubusercontent.com/7585117/112652796-b4ac2400-8e45-11eb-89b4-c63057087411.png)
