### ISSUE TITLE
dart/flutter rollers should not update dart/sdk repo

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#63198]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=57723. 

From the issue: 
We have removed all of the usages of the dart sources in //third_party/dart/ from fuchsia and would like to remove this dependency from the integration repo. Before we remove this from the integration repo we need to make sure that the rollers do not update the entry when a roll occurs. 

The rollers that need to be updated are
- https://luci-scheduler.appspot.com/jobs/turquoise/dart-flutter-roller-b48ad232
- https://luci-scheduler.appspot.com/jobs/turquoise/flutter-with-deps-roller

cc @chaselatta and @godofredoc who are chatting on the upstream bug. OK to keep conversation there.

**Comment by godofredoc** [comment]
This is already fixed in the fuchsia repos.
