### ISSUE TITLE
connectivity_macos not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by danielmessi13** [flutter/flutter#63190]
flutter run --verbose:
https://pastebin.com/mibuJkfJ

pubspec.yaml:
https://pastebin.com/3x7wtXA1

flutter analyze
https://pastebin.com/X1mPmMmr

flutter doctor -v
https://pastebin.com/riX1pswq

**Comment by pedromassangocode** [comment]
Hi @danielmessi13
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/62413).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
