### ISSUE TITLE
Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1 Error, Not sure what do to to resolve it 

### ISSUE THREAD

**Issue by CaptainCoda** [flutter/flutter#63207]
Hello! 

I am new to flutter and recently received code to work on for an application that runs on flutter. I tried to run and debug the code initially to ensure that everything works from my predecessor but upon doing so I got this error msg: 

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.3/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentAutofillScope
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:790:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
  AutofillScope get currentAutofillScope;
                    ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 46s
Exception: Gradle task assembleDebug failed with exit code 1

I am not sure what do to resolve this issue and have scoured the forums for help with no avail. 

Running Flutter Doctor nets me: 

[flutter] flutter doctor -v
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.0 at C:\src\flutter
    • Framework revision 916c3ac648 (6 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\varun\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\varun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!
exit code 0

I am not sure what the issue is, any help is appreciated!

**Comment by wangcheng2005** [comment]
me too

**Comment by darshankawar** [comment]
Hi @CaptainCoda,
This seems to be an issue with `flutter_chips_input` plugin which is a 3rd party plugin. Please consider opening this issue in their repo https://github.com/danvick/flutter_chips_input/issues.
Closing, as this isn't an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by CaptainCoda** [comment]
The issue was rather simple to resolve, you had to update the plugins in the ymal file. One of the plugins is a part of the flutter_chips_input plugins. I feel foolish realizing the solution was so simple.

**Comment by samiraz009** [comment]
how you fi it pleae tell me

**Comment by samiraz009** [comment]
i have same problem i dont know how to updtae plugins in ymal

**Comment by KanybekMomukeyev** [comment]
Same here

**Comment by JamesWR1215** [comment]
> 
> 
> The issue was rather simple to resolve, you had to update the plugins in the ymal file. One of the plugins is a part of the flutter_chips_input plugins. I feel foolish realizing the solution was so simple.

How did you fix it? Please share

**Comment by diko66** [comment]
me too
