### ISSUE TITLE
Pigeon: Often the generated code message's version doesn't match the actual version

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#63208]
Updating it by hand isn't working it.  We should parse the pubspec to make sure that it is correct.
```
// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
```

**Comment by pedromassangocode** [comment]
Does this issue should remain opened? The linked PR description seems to fix this issue.

**Comment by gaaclarke** [comment]
Thanks, we have a test that should fix this.
