### ISSUE TITLE
LUCI infra failure in post_goma step

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#63212]
LUCI build: https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine/12677

This happened in PR: https://github.com/flutter/engine/pull/20276

I looked around the logs but I couldn't find the cause of the failure. I'm not sure where to look.

**Comment by Hixie** [comment]
Assigned to @godofredoc for now per our conversation.

**Comment by godofredoc** [comment]
This seems to be a problem with how swarming manages the caches, please look at comments in the CL:

https://chromium-review.googlesource.com/c/infra/luci/luci-py/+/2230747

**Comment by godofredoc** [comment]
Moving out of the ticket queue and keeping it assigned to me to follow up

**Comment by godofredoc** [comment]
I haven't seen this issue after landing https://flutter-review.googlesource.com/c/recipes/+/6080

**Comment by mdebbar** [comment]
Thanks @godofredoc !
