### ISSUE TITLE
Wrong Xcode version in path

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#63211]
I got an infra failure in PR: https://github.com/flutter/engine/pull/20276

LUCI build: https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20Debug%20Engine/6612

**Comment by digiter** [comment]
Triage: the real failure is at "build android_release_vulkan". Probably related to the test code.

**Comment by digiter** [comment]
Error message [link](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8872606129734923376/+/steps/build_android_release_vulkan/0/stdout):
```
[3766/3771] STAMP obj/flutter/sky/sky.stamp
[3767/3771] LINK clang_x64/gen_snapshot
FAILED: clang_x64/gen_snapshot 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /b/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.11.0 -flto -rdynamic -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-dead_strip -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o clang_x64/gen_snapshot -Wl,-filelist,clang_x64/gen_snapshot.rsp  -ldl -lpthread -framework CoreFoundation -framework CoreServices
ld: can't open output file for writing: clang_x64/gen_snapshot, errno=2 for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by digiter** [comment]
Looks like a flaky with Xcode, and it seems stabilized for now. 

<img width="841" alt="Screen Shot 2020-08-14 at 10 51 10" src="https://user-images.githubusercontent.com/6259181/90278301-13bfaa00-de1c-11ea-89fb-86983736b437.png">
