### ISSUE TITLE
Error conecting to firebase Google Android emulator

### ISSUE THREAD

**Issue by sandroarnaldo** [flutter/flutter#63224]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Debug service listening on ws://127.0.0.1:58654/fBkIsGYoVfw=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 7105): eglMakeCurrent: 0xa2484f00: ver 3 0 (tinfo 0xa2483580)
W/GooglePlayServicesUtil( 7105): Google Play services out of date for br.com.colorsdj.colorsdj.  Requires 12451000 but found 11743470
D/EGL_emulation( 7105): eglMakeCurrent: 0xa2484f00: ver 3 0 (tinfo 0xa2483580)
E/FirebaseInstanceId( 7105): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
E/FirebaseInstanceId( 7105): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
D/EGL_emulation( 7105): eglMakeCurrent: 0x9faf0b20: ver 3 0 (tinfo 0x8c819990)
W/GooglePlayServicesUtil( 7105): Google Play services out of date for br.com.colorsdj.colorsdj.  Requires 12451000 but found 11743470
W/GoogleApiManager( 7105): The service for com.google.android.gms.auth.api.signin.internal.zzh is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
W/GooglePlayServicesUtil( 7105): Google Play services out of date for br.com.colorsdj.colorsdj.  Requires 12451000 but found 11743470
W/GooglePlayServicesUtil( 7105): Google Play services out of date for br.com.colorsdj.colorsdj.  Requires 12451000 but found 11743470
W/GoogleApiManager( 7105): The service for com.google.android.gms.auth.api.signin.internal.zzh is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
W/GoogleApiAvailability( 7105): GMS core API Availability. ConnectionResult=2, tag=null
W/GoogleApiAvailability( 7105): java.lang.IllegalArgumentException
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.2.1:141)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.2.1:46)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager.zac(com.google.android.gms:play-services-base@@17.2.1:213)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:101)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:75)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect(com.google.android.gms:play-services-base@@17.2.1:255)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:125)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.2.1:145)
W/GoogleApiAvailability( 7105): 	at android.os.Handler.dispatchMessage(Handler.java:101)
W/GoogleApiAvailability( 7105): 	at com.google.android.gms.internal.base.zap.dispatchMessage(com.google.android.gms:play-services-base@@17.2.1:8)
W/GoogleApiAvailability( 7105): 	at android.os.Looper.loop(Looper.java:164)
W/GoogleApiAvailability( 7105): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/zygote  ( 7105): Do partial code cache collection, code=60KB, data=42KB
I/zygote  ( 7105): After code cache collection, code=57KB, data=41KB
I/zygote  ( 7105): Increasing code cache capacity to 256KB
D/NetworkSecurityConfig( 7105): No Network Security Config specified, using platform default
D/EGL_emulation( 7105): eglMakeCurrent: 0xa2484f00: ver 3 0 (tinfo 0xa2483580)
D/EGL_emulation( 7105): eglMakeCurrent: 0xa2484f00: ver 3 0 (tinfo 0xa2483580)
E/FirebaseInstanceId( 7105): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
W/GooglePlayServicesUtil( 7105): Google Play services out of date for br.com.colorsdj.colorsdj.  Requires 12451000 but found 11743470
E/FirebaseInstanceId( 7105): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
D/EGL_emulation( 7105): eglCreateContext: 0x9faf0b20: maj 3 min 0 rcv 3
D/EGL_emulation( 7105): eglMakeCurrent: 0x9faf0b20: ver 3 0 (tinfo 0x8c819990)
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x000087fe
E/eglCodecCommon( 7105): glUtilsParamSize: unknow param 0x000087fe
D/EGL_emulation( 7105): eglMakeCurrent: 0xa2484f00: ver 3 0 (tinfo 0xa2483580)
D/EGL_emulation( 7105): eglMakeCurrent: 0x9faf0b20: ver 3 0 (tinfo 0x8c819990)
Lost connection to device.

**Comment by darshankawar** [comment]
Hi @sandroarnaldo,
This seems to be an issue with Firebase which has separate repo for tracking issue : https://github.com/FirebaseExtended/flutterfire/issues. Please consider opening this issue there.
Closing, as this doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.
