### ISSUE TITLE
Document how to disable icon fonts tree shaking in error messages

### ISSUE THREAD

**Issue by roman-mityukov** [flutter/flutter#63248]
I got the following error while building (flutter 1.20.1)

> This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations

**Comment by jonahwilliams** [comment]
Pass `--no-tree-shake-icons` as a build argument. We should document that in the error message if it isn't already.

**Comment by 360views** [comment]
> --no-tree-shake-icons

I have the same issue - How do I disable icon tree shaking in the code itself and not in the terminal (I get this error when I'm building APK in Android Studio (Build --> Flutter --> Build APK)

**Comment by tazik561** [comment]
> > --no-tree-shake-icons
> 
> I have the same issue - How do I disable icon tree shaking in the code itself and not in the terminal (I get this error when I'm building APK in Android Studio (Build --> Flutter --> Build APK)

you can run `flutter build apk --no-tree-shake-icons`

**Comment by qcsltd** [comment]
How do we set this in Xcode when building an Archive for release to TestFlight? Thanks.

**Comment by CiriousJoker** [comment]
@qcsltd Maybe you can run `flutter build bundle` to cache the the compiled files so XCode's build command reuses them? Haven't tested this

**Comment by gaojuanjuan** [comment]
> Hi, can someone please tell me how i can specify the --no-tree-shake-icons in Xcode so I can build an iOS archive release for TestFlight.
> 
> I need to generate icons based on dynamic hexcodes, so returning a const is not an option for me, hence my Xcode build process is now failing (since upgrading to flutter v1.20).
> 
> Many thanks

I also encountered this problem, have you solved it?

**Comment by gaojuanjuan** [comment]
> Hi, can someone please tell me how i can specify the --no-tree-shake-icons in Xcode so I can build an iOS archive release for TestFlight.
> 
> I need to generate icons based on dynamic hexcodes, so returning a const is not an option for me, hence my Xcode build process is now failing (since upgrading to flutter v1.20).
> 
> Many thanks

I also encountered this problem, have you solved it?

**Comment by qcsltd** [comment]
No, not yet. Asked on 3 developer forums and no response.

**Comment by tippuvenky** [comment]
Hi, can someone please tell me how i can specify the --no-tree-shake-icons in Xcode so I can build an iOS archive release for TestFlight.

I need to generate icons based on dynamic hexcodes, so returning a const is not an option for me, hence my Xcode build process is now failing (since upgrading to flutter v1.20).

Many thanks

> Hi, can someone please tell me how i can specify the --no-tree-shake-icons in Xcode so I can build an iOS archive release for TestFlight.
> 
> I need to generate icons based on dynamic hexcodes, so returning a const is not an option for me, hence my Xcode build process is now failing (since upgrading to flutter v1.20).
> 
> Many thanks

I'm also facing the same issue

**Comment by Etiene** [comment]
This worked for me: 

On terminal
`flutter build ios --no-tree-shake-icons`

On xcode
Project > Build settings > User defined > TREE_SHAKE_ICONS = false
Product > Archive

**Comment by naveenfunk** [comment]
The build generated fine but material icons are not visible now in the app.
