### ISSUE TITLE
Cannot easily hot restart a framework test

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#63243]
When `flutter run`ning a test you should be able to restart the test by doing a hot restart. However, when doing so, I always get this error:

```

Performing hot restart...                                              ⣾E/flutter (25430): [ERROR:flutter/shell/common/engine.cc(205)] Could not prepare to run the isolate.
E/flutter (25430): [ERROR:flutter/shell/common/engine.cc(144)] Engine not prepare and launch isolate.
        
Restarted application in 731ms.
Application finished.
hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.
```

**Comment by jason-simmons** [comment]
How are you starting the test?

I tried making a default app with `flutter create` and running `flutter run test/widget_test.dart` using an Android device.  Hot restart worked in this scenario.

**Comment by goderbauer** [comment]
It also works for me on a fresh up created with `flutter create`.

I can't seem to make it work for tests in the flutter framework, though. Here's how I am running them (in the context of another flutter project to make `flutter run` happy):

```
$ flutter create foo
$ cd foo
$ flutter run ../flutter/packages/flutter/test/material/textfield_restoration_test.dart
```

**Comment by jason-simmons** [comment]
This works if you copy the test source into the directory where the empty app was created.

It looks like the `_launchFromDevFS` function in the tool expects the main script to be under the project root path (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L448)

The relative path URI computed by `_launchFromDevFS` eventually becomes the `mainScript` argument passed to the `runInView` service protocol method in the engine.  The engine can't find the kernel at that path and the hot restart fails.
