### ISSUE TITLE
Make `flutter doctor` detect Atom's dart version

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#6324]
In https://github.com/flutter/flutter/pull/6297 I hit the issue of viewing Flutter sample dart code with Atom that showed a sea of red. The underlying issue turned out to be Atom was configured to use an old brew installed Dart - version 1.17 in fact.

It would be good to have `flutter doctor` detect and warn on this condition.

**Comment by eseidelGoogle** [comment]
Thanks for the bug!  Unfortunately Atom is no longer our recommended editor, so closing this. :/  Unclear if this issue affects Intellij as well.
