### ISSUE TITLE
Add clipBehavior to Overlay, Flow, AnimatedSize, and AndroidView

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#63246]
Thanks for https://github.com/flutter/flutter/pull/63147#issuecomment-670435675 to point this out.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by TheBiirb** [comment]
@liyuqian What about flow and platform_view? They have pushClipRect too

**Comment by TheBiirb** [comment]
@liyuqian Flow widget as well?

**Comment by liyuqian** [comment]
Yes, thanks. Added to the title.
