### ISSUE TITLE
my app doesn't run on profile mode

### ISSUE THREAD

**Issue by shiratsu** [flutter/flutter#63244]
i tried to run an app on profile mode.
but it didn't run.

i tried 2 ways.
At first i tried to run on VSCode with this launch option
```
{
      "name": "Flutter-profile",
      "request": "launch",
      "type": "dart",
      "flutterMode": "profile",
    }
```

vscode said
```
Could not run build/ios/iphoneos/Runner.app on XXXXXXX-XXXXXXX.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                        22.4s
Error running application on XXXXXXXX.
```

then

i tried to run on xcode with profile mode
but xcode said
```
error: failed to launch '/private/var/containers/Bundle/Application/8AD4849D-565F-XXXXXXXXXXX-A4F7-34BF6398D714/Runner.app' -- XXXX-XXXXX has denied the launch request.
Internal launch error: process launch failed: failed to get the task for process 5046
```

by the way it run properly on debug mode even if device is real device(iPhone XR)

**Comment by TahaTesser** [comment]
Hi @shiratsu 
I can run the app with no issues
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "program": "lib/main.dart",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        }
    ]
}
```

Try a new project with this configuration 

If the problem persist,  Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
