### ISSUE TITLE
constant "Waiting for another flutter command to release the startup lock..." error message

### ISSUE THREAD

**Issue by Ashok-Varma** [flutter/flutter#63259]
## Steps to Reproduce

1. I tried upgrading flutter and since process is taking long i cancelled it (^c)
2. Flutter state never recovered from then, every flutter command gives error `Waiting for another flutter command to release the startup lock...`

## Tried solutions (But these didn't work)
1. Removed lockfile
2. cleaned repo `git clean -fdx`
3. cloned repo to new folder and changed ENV to reflect new folder
4. removed all flutter related caches that i can see
```
rm -rf ~/.pub-cache
rm -rf ~/.dart
rm -rf ~/.dartServer
rm -rf ~/.flutter
rm -rf ~/.flutter_tool_state
```
Still same error. Does flutter store state in any other place. Is there a way to clean flutter completely without using `flutter`, can't use the command

**Comment by darshankawar** [comment]
Hi @Ashok-Varma,
Try to run this command `killall -9 dart`. Then close the IDE / terminal windows you are using and start over fresh to see if it resolves your issue.
Thanks.

**Comment by TahaTesser** [comment]
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/63264
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Ashok-Varma** [comment]
@darshankawar i tried `killall -9 dart`, didn't find any dart process. same for flutter. But still i get this error

**Comment by swkang73** [comment]
Same issue here as @Ashok-Varma

**Comment by zrayburn** [comment]
I know this issue is closed but in my environment, CentOS core, I use NFS storage for just about everything and something about flock freaks out when in such an environment. I fixed this by going into <FLUTTER HOME>/bin/internal/shared.sh and commenting out lines 45-49 and line 51 which effectively forces flutter to use the basic mkdir lock method.
In summary, flutter assumes that just because flock exists it is the proper method for establishing an update/run lock. Sometimes in weird NFS environments this is not the case.
@TahaTesser I'm not sure if there is any way to solve this at a broad level but if you would like more information from me, let me know.

**Comment by errorsolve** [comment]
[already [Solved] Waiting for another flutter command to release the startup lock
](https://fluttercorner.com/waiting-for-another-flutter-command-to-release-the-startup-lock/)

**Comment by RandalSchwartz** [comment]
> I know this issue is closed but in my environment, CentOS core, I use NFS storage for just about everything and something about flock freaks out when in such an environment. I fixed this by going into /bin/internal/shared.sh and commenting out lines 45-49 and line 51 which effectively forces flutter to use the basic mkdir lock method.
> In summary, flutter assumes that just because flock exists it is the proper method for establishing an update/run lock. Sometimes in weird NFS environments this is not the case.
> @TahaTesser I'm not sure if there is any way to solve this at a broad level but if you would like more information from me, let me know.

THANK YOU THANK YOU.  Yes, the install dir was on NFS on Centos for me!  Broken!  Made your edit, now fixed.
