### ISSUE TITLE
This App Bundle contains native code, and you've not uploaded debug symbols. We recommend that you upload a symbol file to make your crashes and ANRs easier to analyse and debug

### ISSUE THREAD

**Issue by nishanthrk** [flutter/flutter#63268]
Hi When I upload my bundle in new playstore beta console it shows me this warning

"This App Bundle contains native code, and you've not uploaded debug symbols. We recommend that you upload a symbol file to make your crashes and ANRs easier to analyse and debug"

flutter version 1.20

**Comment by darshankawar** [comment]
Hi @nishanthrk,
There's similar open issue describing your case, [60240](https://github.com/flutter/flutter/issues/60240).
Please follow-up there for updates.
Closing this as duplicate.

**Comment by flutterq** [comment]
[[solved] Playstore error: App Bundle contains native code, and you’ve not uploaded debug symbols
](https://fluttercorner.com/solved-playstore-error-app-bundle-contains-native-code-and-youve-not-uploaded-debug-symbols/)
