### ISSUE TITLE
Sentry stacktraces do not show code

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#63276]
Stacktraces from python - beautiful inline code
![image](https://user-images.githubusercontent.com/19492893/89707978-c90fdf00-d990-11ea-8498-390bd48bd4c2.png)

---

Stacktraces from dart - no inline code snippets :(

![image](https://user-images.githubusercontent.com/19492893/89707993-ef357f00-d990-11ea-8b3e-02225d1e8e7e.png)

---

I understand that python is a super dynamic language and can pick up the code using magic like the `inspect` module, but is there a way to "give" sentry my dart code too?

---

<details>

<summary>fluter doctor -v</summary>

<p>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G4032, locale en)
    • Flutter version 1.17.5 at /Users/dev/Tools/flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6392135/Android
      Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • POCO F1 • e19ec1f6 • android-arm64 • Android 10 (API 29)

• No issues found!
```

</p>
</details>

**Comment by darshankawar** [comment]
Hi @devxpy,
Does [this](https://github.com/flutter/flutter/issues/37875) sound similar to your question / request ?
Thanks.

**Comment by devxpy** [comment]
Umm, I'm not quite sure whether I understand if https://github.com/flutter/flutter/issues/37875 is about sentry at all.

As far as source maps go, flutter doesn't need those, because there's no transpiling step that I'm aware of.

And the part about "Sometimes sentry doesn't give you something useful because the the stacktrace is only flutter internal libraries" seems only related to exceptions from flutter engine, which dont bubble up to user code. 

This issue is strictly about showing source code snippets with stacktraces.

**Comment by devxpy** [comment]
Thanks for fixing my typo :)

**Comment by bruno-garcia** [comment]
We'll investigate if it's possible at all and how we could do this.
One approach is to allow users to run `sentry-cli` to upload a "source bundle" and on the server we lookup the relevant lines of code on that bundle as the events come in.

**Comment by devxpy** [comment]
@bruno-garcia I've tried uploading dart source files - 

```
sentry-cli releases files "$VERSION" upload ./lib
```

But the source code still doesn't show in-line with the stack trace on sentry.io

**Comment by bruno-garcia** [comment]
There is not support yet. This will require some work on tooling (get the source code available on the server) and on the backend. We haven't started this work yet.

I've raised an issue in the Sentry Dart/Flutter SDK repository (moved away from Flutter's org):

The issue will be tracked here: https://github.com/getsentry/sentry-dart/issues/132 and for that reason I'll close the issue here.
