### ISSUE TITLE
GTK 3.0 development libraries issue (Fedora 32)

### ISSUE THREAD

**Issue by Meta-Cortex** [flutter/flutter#63271]
[xxxxx@localhost ~]$ flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-8.0.pre.110, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-8.0.pre.110 at /home/xxxxx/snap/flutter/common/flutter
    • Framework revision 4aed976812 (61 minutes ago), 2020-08-07 23:30:56 -0700
    • Engine revision 1e50d87dc8
    • Dart version 2.10.0 (build 2.10.0-4.0.dev b9c5118c73)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✗] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
    **✗ GTK 3.0 development libraries are required for Linux development.**
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.

[xxxxx@localhost ~]$ sudo dnf install gtk3-devel
Last metadata expiration check: 1:00:24 ago on Sat 08 Aug 2020 09:31:57 AM EEST.
**Package gtk3-devel-3.24.21-1.fc32.x86_64 is already installed.**
Dependencies resolved.
Nothing to do.
Complete!

Why do I get this error?

**Comment by stuartmorgan** [comment]
Sounds like the `doctor` check for libraries will need a bit of restructuring rather than assuming everything on the list will be a dependency of the GTK libraries.

What does `pkg-config` report for each of [these libraries](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L56) (so that we know which one(s) to break out separately)?

**Comment by Meta-Cortex** [comment]
Which command exactly I need to use to get that report?
I tried these for now:
```
[xxxxx@localhost ~]$ pkg-config --modversion gtk+-3.0
3.24.21
[xxxxx@localhost ~]$ pkg-config --modversion glib-2.0
2.64.4
[xxxxx@localhost ~]$ pkg-config --modversion gio-2.0
2.64.4
[xxxxx@localhost ~]$ pkg-config --modversion blkid
2.35.2
```

**Comment by stuartmorgan** [comment]
Oh, you're using the snap, I missed that before.

@MarcusTomlinson @kenvandine Do people need to do some explicit update step to get the snap that has blkid installed?

**Comment by MarcusTomlinson** [comment]
> Oh, you're using the snap, I missed that before.
> 
> @MarcusTomlinson @kenvandine Do people need to do some explicit update step to get the snap that has blkid installed?

No, nothing special needs to be done. The snap will update automatically once it’s published to stable. That should happen sometime tomorrow.

**Comment by MarcusTomlinson** [comment]
In the meantime, you can verify that the newer flutter snap works by running:

`snap refresh flutter --edge`

_(Note, you may also need to remove your project's `linux` directory and `flutter create ./` again)_

To restore your flutter snap to the stable channel again, run:

`snap refresh flutter --stable`

**Comment by MarcusTomlinson** [comment]
Ok sooner than that ;) @kenvandine has just published the fixed flutter snap to stable. It should update automatically on your system, but if you want to force it, you can run:

`snap refresh`
