### ISSUE TITLE
How to Embedded Android Fragment / iOS ViewController to Flutter Widget with their own life cycle 

### ISSUE THREAD

**Issue by thanhhuan1990** [flutter/flutter#63283]
I'm trying to add Flutter to my existing application: Android and iOS, 

### But I'm facing 1 big problem: 
Android Native app is using a RecyclerView to show dynamic list of more than 100 Fragments type. 
I want to create flutter widget to replace current **Parent RecyclerView**, and than update current fragment to widget, one-by-one.
But while implementing, I need to re-use current fragment in Flutter's ListView.Builder to make sure application working until replace finish.

### Issue: Do know how to use Android Fragment in Flutter.

Anyone have knowledge about this, please help.

Thank you very much

**Comment by TahaTesser** [comment]
Hi  @thanhhuan1990 
You show your `RecyclerView` in your Flutter App using [AndroidView](https://api.flutter.dev/flutter/widgets/AndroidView-class.html) Widget in Flutter  
Please check out [article ](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6)
Does this answer question?

**Comment by thanhhuan1990** [comment]
Thank for your response @TahaTesser ,
I know about AndroidView or PlatformView, but it cannot resolve my issue.
My existing component (Fragment / ViewController) has their own life cycle, perform API call and handle logic by themself, not only UI. And I need reused all of this in Flutter.

**Comment by TahaTesser** [comment]
I’m not sure if this possible to embed native with their  own life cycle in into flutter widget. So flutter lifecycle is different
Recyclerview works completely different than listview in flutter if you embed in a stateful widget.
The issue needs further investigation.

**Comment by Hixie** [comment]
This doesn't seem like a bug so much as a request for help, for which I would recommend StackOverflow or reddit.

In general though, I would recommend starting by replacing the fragments rather than the recycler view. Going inside out tends to work better.
