### ISSUE TITLE
Can't run flutter_driver sample app

### ISSUE THREAD

**Issue by srockytfl** [flutter/flutter#63289]
I just follow this tutorial:
https://flutter.dev/docs/cookbook/testing/integration/introduction

Flutter doctor:
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

After run this command, I got this timeout error:

flutter drive --target=test_driver/app.dart
<img width="1014" alt="Screen Shot 2020-08-08 at 11 27 55" src="https://user-images.githubusercontent.com/69392984/89712902-3f4d1b00-d96a-11ea-81e6-c620ccedb049.png">

Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 7.1s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter (26310): Observatory listening on http://127.0.0.1:42686/ZZ5CTwfT-YM=/
00:00 +0: Counter App (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50924/ZZ5CTwfT-YM=/
VMServiceFlutterDriver: Isolate found with number: 1198731682576823
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
00:02 +0: Counter App starts at 0

VMServiceFlutterDriver: get_text message is taking a long time to complete...
00:32 +0 -1: Counter App starts at 0 [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 322:28               Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 320:10               Invoker._handleError
  package:test_api/src/backend/invoker.dart 276:9                Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 275:38               Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1021:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 18:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1114:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1020:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1263:21                                   _rootCreateTimer
  dart:async/zone.dart 1154:19                                   _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 274:34               Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

00:32 +0 -1: Counter App increments the counter

VMServiceFlutterDriver: tap message is taking a long time to complete...
01:02 +0 -2: Counter App increments the counter [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 322:28               Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 320:10               Invoker._handleError
  package:test_api/src/backend/invoker.dart 276:9                Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 275:38               Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1021:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 18:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1114:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1020:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1263:21                                   _rootCreateTimer
  dart:async/zone.dart 1154:19                                   _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 274:34               Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

01:02 +0 -2: Counter App (tearDownAll)

01:02 +0 -2: Counter App starts at 0 [E]

  DriverError: Failed to fulfill GetText due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #3      _rootRun (dart:async/zone.dart:1182:47)
  #4      _CustomZone.run (dart:async/zone.dart:1093:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
  #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #13     _rootRun (dart:async/zone.dart:1190:13)
  #14     _CustomZone.run (dart:async/zone.dart:1093:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
  #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
  #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

  package:flutter_driver/src/driver/vmservice_driver.dart 336:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 232:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

01:02 +0 -2: Counter App increments the counter [E]

  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #3      _rootRun (dart:async/zone.dart:1182:47)
  #4      _CustomZone.run (dart:async/zone.dart:1093:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
  #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #13     _rootRun (dart:async/zone.dart:1190:13)
  #14     _CustomZone.run (dart:async/zone.dart:1093:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
  #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
  #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

  package:flutter_driver/src/driver/vmservice_driver.dart 336:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 232:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

01:02 +0 -2: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
Stopping application instance.
Driver tests failed: 255

source code:
https://github.com/srockytfl/flutter_app

**Comment by darshankawar** [comment]
Hi @srockytfl,
You are missing the `key` declaration inside `Text` and `FAB` buttons respectively in your repo code.

```
Text(
              '$_counter',
              key: Key('counter'),
```

```
floatingActionButton: FloatingActionButton(
        key: Key('increment'),


```
Once you add above lines and run driver test, it should work.

**Comment by srockytfl** [comment]
All tests passed! Thank you.
One thing I think it could be better in the docs, is how to test more complex scenarios, like async functions or widget navigation .. The docs always shows the simple counter example. Of course I can do a google search, and find some articles or posts on stackoverflow, but it's always boring or uncomplete and it's not official.
For example: I have a simple login page I would like to test. The page has this structure LoginPage > LoginViewModel > LoginRepository > LoginApi. I my widget test, I was able to successfully type the login and password tests and hit the login button, but I don't know how to test if the navigation to the HomePage was successful. There isn't official samples about this. If someone can take a look I can provide a simple example with this scenario too, thank you.

**Comment by darshankawar** [comment]
@srockytfl thanks for confirming. For your question on better documentation and examples on flutter driver, I'd suggest you open a new issue and provide all required details.
I am closing this as fixed.
