### ISSUE TITLE
ArgumentError: Invalid argument(s): Cannot find executable for reg.

### ISSUE THREAD

**Issue by avalosa** [flutter/flutter#63291]
## Steps to Reproduce

C:\Apps>flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    f3b7788f7..836edde74  flutter-1.21-candidate.8 -> origin/flutter-1.21-candidate.8
git:    77b4505c8..4aed97681  master     -> origin/master
git: Your branch is up to date with 'origin/beta'.
git: Already on 'beta'
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

C:\Apps>flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (7 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

C:\Apps>flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.

C:\Apps>flutter devices

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for reg.".

A crash report has been written to C:\Apps\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Invalid+argument%28s%29%3A+Cannot+find+executable+for+reg.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJ1IE

## Logs

```
```

```
[flutter_01.log](https://github.com/flutter/flutter/files/5045410/flutter_01.log)

```

**Comment by markusaksli-nc** [comment]
Hi @avalosa 
There seems to have been a bug where the latest beta is stuck on `1.20.0` even when upgrading. This is actually the last version of stable and since web isn't supported on stable yet, this might have caused the issue.

In any case you can simply manually download the latest version of the beta channel from [flutter.dev ](https://flutter.dev/docs/development/tools/sdk/releases) instead of trying to upgrade from the tool. Let me know if this fixes your issue.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
