### ISSUE TITLE
I/flutter ( 7417): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════

### ISSUE THREAD

**Issue by Brakachan** [flutter/flutter#63295]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Brakachan** [comment]
I/flutter ( 7417): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7417): The following assertion was thrown during performLayout():
I/flutter ( 7417): Leading widget consumes entire tile width. Please use a sized widget.
I/flutter ( 7417): 'package:flutter/src/material/list_tile.dart':
I/flutter ( 7417): Failed assertion: line 1353 pos 7: 'tileWidth != leadingSize.width'

**Comment by Brakachan** [comment]
I got this error in Flutter ... system was working perfectly but start to show this error without a change in the code.

**Comment by darshankawar** [comment]
Hi @Brakachan,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
