### ISSUE TITLE
MergeSemantics does not take sortKey into account

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#63303]
b/163110107

Min repro case:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MergeSemantics(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Semantics(sortKey: OrdinalSortKey(3), child: Text('line A')),
                Semantics(sortKey: OrdinalSortKey(2), child: Text('line B')),
                Semantics(sortKey: OrdinalSortKey(1), child: Text('line C')),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

Expected:

Merged semantics should read "line C / line B / line A"
Observed:

Merged semantics reads "line A / line B / line C"

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by chunhtai** [comment]
I also replied to the internal bug

This is WAI

The sortkey is meant for focus traversal order. https://api.flutter.dev/flutter/semantics/SemanticsProperties/sortKey.html

The concatenate order is determined by visitChildrenForSemantics. The document specifically says `Called when collecting the semantics of this node.`
https://api.flutter.dev/flutter/rendering/RenderObject/visitChildrenForSemantics.html

**Comment by mehmetf** [comment]
I find it surprising that MergeSemantics changes the focus traversal order when it is explicitly defined in the subtree. Perhaps the intention needs to be fixed here?

**Comment by chunhtai** [comment]
MergeSemantics does not change the focus traversal order. There are two things:
1. focus traversal order
2.semantics collection order.

The concatenation is depends on `semantics collection order` which by default is the paint order and is the same order where the children are passed into the column.

If the behavior is that the merge semantics must concatenate in a different order than the children in the column, this is a new feature request.

**Comment by mehmetf** [comment]
I agree that this is an FR.

I was asking whether it is a valid FR. *Should* MergeSemantics consider focus traversal order? One caveat is that I *think* focus traversal order isn't entirely determined in Dart. Even if we fix this, there will still be cases where labels will change when `MergeSemantics` is introduced to the widget tree.

**Comment by chunhtai** [comment]
I think we should not overload the sort key with the mergeSemantics. I am a bit worry that we may later on run into a request that want to separate out the sort key with mergeSemantics.

If we want to do this, we should come up with a new api. I wonder what is the use case where the customer wants the merge semantics to concatenate the string in reverse of the display order. That does not feel like a pleasant UI experience.

**Comment by mehmetf** [comment]
Agreed that we should learn more about the use case. Could you please post that question to internal issue? Thanks @chunhtai.

**Comment by chunhtai** [comment]
closed as WAI, see internal bug for more details
