### ISSUE TITLE
Image picker for web

### ISSUE THREAD

**Issue by bhavikvashi1804** [flutter/flutter#63314]
image_picker_for_web-0.1.0+1/lib/image_picker_for_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' as html;

I created app in which I have used Image picker for web it works well for me in web version but as soon as I run it to android it gives me above error.

Is there any way to solve this, means same code runs on both platform Android + Web: pick image?

**Comment by zhaolinlins** [comment]
Yes, Android and iOS  temporary use https://pub.dev/packages/image_picker

**Comment by TahaTesser** [comment]
Hi @bhavikvashi1804 

Create a new project and add following
```
  image_picker: ^0.6.7+4
  image_picker_for_web: ^0.1.0+1
```

<details> 
<summary>Code Sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);

    setState(() {
      _image = File(pickedFile.path);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}

``` 

</details> 

This works on mobile and web

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by bhavikvashi1804** [comment]
> Hi @bhavikvashi1804
> 
> Create a new project and add following
> 
> ```
>   image_picker: ^0.6.7+4
>   image_picker_for_web: ^0.1.0+1
> ```
> 
> Code Sample
> ```dart
> import 'dart:io';
> 
> import 'package:flutter/material.dart';
> import 'package:image_picker/image_picker.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Material App',
>       theme: ThemeData.dark(),
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   File _image;
>   final picker = ImagePicker();
> 
>   Future getImage() async {
>     final pickedFile = await picker.getImage(source: ImageSource.gallery);
> 
>     setState(() {
>       _image = File(pickedFile.path);
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Image Picker Example'),
>       ),
>       body: Center(
>         child: _image == null ? Text('No image selected.') : Image.file(_image),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: getImage,
>         tooltip: 'Pick Image',
>         child: Icon(Icons.add_a_photo),
>       ),
>     );
>   }
> }
> ```
> 
> This works on mobile and web
> 
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

This will allow to pick the image file in both web and mobile but there is one issue still, after picking image in web it does not support to open image via following code.
Container(
                  child: Center(
                    child: _pickedImage == null
                        ? Text('No image selected.')
                        : Image.file(_pickedImage),
                  ),
                ),


here _pickedImage is file type varible.

**Comment by bhavikvashi1804** [comment]
Error Log
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 205:5               get _namespacePointer
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 220:48                                         _namespacePointer
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 223:15                                         _dispatchWithNamespace       
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 354:60                                         open
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 527:19                                         readAsBytes
packages/flutter/src/painting/image_provider.dart 878:40                                                                   _loadAsync

**Comment by bhavikvashi1804** [comment]
CircleAvatar(
            radius: 40,
            backgroundImage: kIsWeb
                ? _imagePath.length == 0 ? null : NetworkImage(_imagePath)
                : _image == null ? null : FileImage(_image),
          ),

**Comment by bhavikvashi1804** [comment]
> CircleAvatar(
> radius: 40,
> backgroundImage: kIsWeb
> ? _imagePath.length == 0 ? null : NetworkImage(_imagePath)
> : _image == null ? null : FileImage(_image),
> ),

this works for me to display image on web and android

**Comment by TahaTesser** [comment]
Hi @bhavikvashi1804 
This is not related to this issue as mentioned earlier https://github.com/flutter/flutter/issues/63314#issue-675634445
```
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49 throw
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 205:5 get _namespacePointer
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 220:48 _namespacePointer
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 223:15 _dispatchWithNamespace
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 354:60 open
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 527:19 readAsBytes
packages/flutter/src/painting/image_provider.dart 878:40 _loadAsync
```

if you think is a bug, please a file new and provide all the details with complete sample
