### ISSUE TITLE
TextOverflow not working as expected in Text widget

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#63311]
## Steps to reproduce

Run the following app (also visible at http://dartpad.dev/0c6794bd5daf972aff91724efee85dd9):

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Align(
        alignment: Alignment.center,
        child: SizedBox(
          width: 150,
          child: ColoredBox(
            color: const Color(0xff666666),
            child: Text('onelongword anotherreallylongword', maxLines: 1, overflow: TextOverflow.visible),
          ),
        ),
      ),
    );
  }
}
```

## Expected behavior

You expect something like the following result:

![bug_desired png](https://user-images.githubusercontent.com/15253456/89723239-74785e00-d9a8-11ea-8d15-fd4f056b2bac.png)

## Actual behavior

This is what's rendered -- the second word doesn't show up at all, despite the overflow being set to `visible`:

![bug_actual](https://user-images.githubusercontent.com/15253456/89723250-94a81d00-d9a8-11ea-83be-24bdd5b3c23a.png)

## Related

If you change the overflow to `TextOverflow.clip`, then you expect the following output:

![bug_desired_clip](https://user-images.githubusercontent.com/15253456/89723292-1d26bd80-d9a9-11ea-8400-63016f182d2f.png)

But again, the second word is completely omitted:

![bug_actual_clip](https://user-images.githubusercontent.com/15253456/89723311-47787b00-d9a9-11ea-8a92-431b4bc73d49.png)

## Other info

In the latter case, if clipping at word breaks is actually working as intended, then I think we should add a new `TextOverflow` enum value that allows the caller to clip in the middle of a word.  The first case above seems unlikely that it's working as intended.

**Comment by tvolkert** [comment]
Setting `softWrap: false` achieved the desired behavior.

This should be documented better.  Currently, the `Text.overflow` property only says "How visual overflow should be handled."  If the overflow behavior is affected by the `softWrap` property, the interplay should be documented (in the properties and also the `Text` constructor arguments), and there should be breadcrumbs from one to the other.

**Comment by broccolism** [comment]
Does anyone start to deal with this? I wanna do it.

**Comment by broccolism** [comment]
@tvolkert 
I set the attribute `sofWrap: false` of `Text` class as you said and it worked with `TextOverflow.visible`.
But it shows no any text with 'TextOverflow.clip` property.
Is this expected work?

**Comment by tvolkert** [comment]
@broccolism here's what I used:

```dart
Text(
  'insert text here',
  maxLines: 1,  // Don't wrap at all
  softWrap: false,  // Don't wrap at soft breaks
  overflow: TextOverflow.clip,  // Clip the overflow
);
```

This can be seen at http://dartpad.dev/4afce9459e04be1bfc5524fad8eb35df
