### ISSUE TITLE
When flutter is installed via Snap, there is no flutter/bin in Platform.environment['PATH']]

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#63325]
I installed flutter from snap by `snap install flutter --classic` 
If I'm not wrong flutter bin path is something like `~/snap/flutter/common/flutter/bin`

But by running `Platform.environment['PATH'].split(':')` in my case output is:

`[/snap/flutter/21/usr/bin, /snap/flutter/21/bin, /home/aliyazdi75/.config/composer/vendor/bin, /home/aliyazdi75/.local/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /snap/bin]`

and there is no such a `flutter/bin` in this array.

**Comment by TahaTesser** [comment]
Hi @aliyazdi75 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by aliyazdi75** [comment]
Hello my friend @TahaTesser 
<details>
<summary>
flutter doctor -v
</summary>
<pre>
[✓] Flutter (Channel master, 1.21.0-8.0.pre.45, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-8.0.pre.45 at /home/aliyazdi75/snap/flutter/common/flutter
    • Framework revision f6c5d6647f (5 days ago), 2020-08-05 03:16:04 -0400
    • Engine revision a4e0104ae8
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 363c72111d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/aliyazdi75/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /home/aliyazdi75/Application/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/aliyazdi75/Application/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
</pre>
</details>
<details>
<summary>
flutter run --verbose
</summary>
<pre>
[ +119 ms] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f6c5d6647f8078ef375e81ae04bcc85c20af94ed
[        ] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git tag --contains HEAD
[ +189 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git describe --match
*.*.*-*.*.pre --first-parent --long --tags
[  +18 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-7.0.pre-45-gf6c5d6647
[  +12 ms] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +42 ms] executing: [/home/aliyazdi75/snap/flutter/common/flutter/] git rev-parse --abbrev-ref
HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: /home/aliyazdi75/Android/Sdk/platform-tools/adb devices -l
[  +42 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +76 ms] Multiple devices found:
[  +48 ms] Linux (desktop)  • linux      • linux-x64      • Linux
[   +1 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[        ] Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
[   +1 ms] [0]: Linux (linux)
[        ] [1]: Web Server (web-server)
[        ] [2]: Chrome (chrome)
[   +1 ms] Please choose one:
[        ]  [0|1|2]
[        ] : 
[+49329 ms] 1
[ +153 ms] Found plugin path_provider at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11
/
[   +7 ms] Found plugin path_provider_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-
0.0.1+2/
[   +3 ms] Found plugin path_provider_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-
0.0.4+3/
[  +17 ms] Found plugin shared_preferences at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0
.5.8/
[   +2 ms] Found plugin shared_preferences_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_l
inux-0.0.2+1/
[   +2 ms] Found plugin shared_preferences_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_m
acos-0.0.1+10/
[   +4 ms] Found plugin shared_preferences_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_w
eb-0.1.2+7/
[  +12 ms] Found plugin url_launcher at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[   +2 ms] Found plugin url_launcher_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0
.0.1+1/
[   +1 ms] Found plugin url_launcher_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0
.0.1+7/
[   +3 ms] Found plugin url_launcher_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1
.2/
[ +105 ms] Found plugin path_provider at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11
/
[   +1 ms] Found plugin path_provider_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-
0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-
0.0.4+3/
[   +6 ms] Found plugin shared_preferences at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0
.5.8/
[   +1 ms] Found plugin shared_preferences_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_l
inux-0.0.2+1/
[   +1 ms] Found plugin shared_preferences_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_m
acos-0.0.1+10/
[   +2 ms] Found plugin shared_preferences_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_w
eb-0.1.2+7/
[   +5 ms] Found plugin url_launcher at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[   +1 ms] Found plugin url_launcher_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0
.0.1+1/
[   +1 ms] Found plugin url_launcher_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0
.0.1+7/
[   +1 ms] Found plugin url_launcher_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1
.2/
[  +68 ms] Generating
/home/aliyazdi75/Documents/AndroidStudioProjects/my_site/android/app/src/main/java/io/flutter/plugin
s/GeneratedPluginRegistrant.java
[  +86 ms] Launching lib/main.dart on Web Server in debug mode...
[  +56 ms] Updating assets
[ +681 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force
rerun. for more information see #56466.
[   +6 ms] Syncing files to device Web Server...
[  +22 ms] Found plugin path_provider at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11
/
[   +1 ms] Found plugin path_provider_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-
0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-
0.0.4+3/
[   +4 ms] Found plugin shared_preferences at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0
.5.8/
[   +1 ms] Found plugin shared_preferences_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_l
inux-0.0.2+1/
[   +1 ms] Found plugin shared_preferences_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_m
acos-0.0.1+10/
[   +1 ms] Found plugin shared_preferences_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_w
eb-0.1.2+7/
[   +4 ms] Found plugin url_launcher at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[   +1 ms] Found plugin url_launcher_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0
.0.1+1/
[   +1 ms] Found plugin url_launcher_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0
.0.1+7/
[   +1 ms] Found plugin url_launcher_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1
.2/
[  +27 ms] Found plugin path_provider at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11
/
[   +1 ms] Found plugin path_provider_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-
0.0.1+2/
[        ] Found plugin path_provider_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-
0.0.4+3/
[   +2 ms] Found plugin shared_preferences at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0
.5.8/
[        ] Found plugin shared_preferences_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_l
inux-0.0.2+1/
[        ] Found plugin shared_preferences_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_m
acos-0.0.1+10/
[        ] Found plugin shared_preferences_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_w
eb-0.1.2+7/
[   +2 ms] Found plugin url_launcher at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[        ] Found plugin url_launcher_linux at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0
.0.1+1/
[        ] Found plugin url_launcher_macos at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0
.0.1+7/
[        ] Found plugin url_launcher_web at
/home/aliyazdi75/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1
.2/
[   +7 ms] Generating
/home/aliyazdi75/Documents/AndroidStudioProjects/my_site/android/app/src/main/java/io/flutter/plugin
s/GeneratedPluginRegistrant.java
[ +351 ms] <- reset
[   +5 ms] /home/aliyazdi75/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/aliyazdi75/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.da
rt.snapshot --sdk-root /home/aliyazdi75/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.KTEOSG/flutter_tool.YMLZDZ/app.dill --libraries-spec
file:///home/aliyazdi75/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-u
nreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.KTEOSG/flutter_tools.QQAAUY --filesystem-scheme
org-dartlang-app --initialize-from-dill build/cache.dill.track.dill --platform
file:///home/aliyazdi75/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk
.dill
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+22628 ms] Syncing files to device Web Server... (completed in 23,075ms, longer than expected)
[        ] Synced 35.8MB.
[        ] <- accept
[        ] Caching compiled dill
[  +21 ms] lib/main.dart is being served at http://localhost:43203
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider
using the
           Chrome or Edge devices for an improved development workflow.
[   +6 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
</pre>
</details>
Minimal code sample:

```
  final separator = (Platform.isWindows) ? ';' : ':';
  final flutterBinPath =
      Platform.environment['PATH'].split(separator).lastWhere((setting) {
    return path.canonicalize(setting).endsWith(path.join('flutter', 'bin'));
  });
```

Output:

```
Bad state: No element
#0      ListMixin.lastWhere (dart:collection/list.dart:180:5)
#1      _flutterRootPath (file:///home/aliyazdi75/Documents/AndroidStudioProjects/my_site/tool/grind.dart:85:53)
#2      generateLocalizations (file:///home/aliyazdi75/Documents/AndroidStudioProjects/my_site/tool/grind.dart:25:5)
#3      _LibraryMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:1089:36)
#4      _ObjectMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:242:25)
#5      TaskDiscovery.discoverDeclaration.<anon> (package:grinder/src/discover_tasks.dart:77:38)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     ZonedValue.withValue (package:grinder/src/utils.dart:113:12)
#11     GrinderTask.execute (package:grinder/src/grinder_task.dart:63:27)
#12     Grinder._invokeTask (package:grinder/src/grinder.dart:193:27)
#13     Grinder.start.<anon> (package:grinder/src/grinder.dart:168:16)
#14     Future.forEach.<anon> (dart:async/future.dart:512:26)
#15     Future.doWhile.<anon> (dart:async/future.dart:554:26)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#17     _RootZone.bindUnaryCallbackGuarded.<anon> (dart:async/zone.dart:1423:26)
#18     Future.doWhile (dart:async/future.dart:570:18)
#19     Future.forEach (dart:async/future.dart:510:12)
#20     Grinder.start (package:grinder/src/grinder.dart:167:21)
#21     runTasks (package:grinder/src/cli.dart:67:38)
#22     grind (package:grinder/grinder.dart:46:12)
#23     main (file:///home/aliyazdi75/Documents/AndroidStudioProjects/my_site/tool/grind.dart:7:33)
```

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```dart
import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:flutter/material.dart';

void main() {
  final separator = (Platform.isWindows) ? ';' : ':';
  final flutterBinPath = Platform.environment['PATH'].split(separator);
  // final flutterBinPath = Platform.environment['PATH'];
  print(flutterBinPath);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details> 

<details> 
<summary>logs</summary> 

```
r (12426): [/sbin, /system/sbin, /product/bin, /apex/com.android.runtime/bin, /system/bin, /system/xbin, /odm/bin, /vendor/bin, /vendor/xbin]
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.1 at /home/taha/snap/flutter/common/flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by jmagman** [comment]
@csells How should we triage snap installer issues like this?

**Comment by csells** [comment]
They should be redirected here: https://github.com/kenvandine/flutter-snap/issues

**Comment by jmagman** [comment]
@aliyazdi75 You should file with [flutter-snap](https://github.com/kenvandine/flutter-snap/issues) then.  Sounds like maybe their docs are unclear for how to add it to your path?  Or maybe it should be doing it automatically?  They would know more.

**Comment by aliyazdi75** [comment]
@jmagman @TahaTesser no one answers me on their repository.

**Comment by jmagman** [comment]
@aliyazdi75 It's only been 5 days, and 2 of those days were weekend.  I don't know what their triage process is like.

**Comment by aliyazdi75** [comment]
@jmagman ok, thanks.
