### ISSUE TITLE
Fine-tuned System Info access of Android + iOS device within flutter app

### ISSUE THREAD

**Issue by somdipdey** [flutter/flutter#63324]
I am trying to access the following information about the device in which my flutter app is executing:

- CPU utilization (%) for multi-core systems (ARM's big.LITTLE architecture for Android/iOS platforms)
- Peak temperature of the CPU cores/GPU/Battery (if the sensors are available)
- GPU utilization (%)
- RAM utilization (MB)
- Power consumption in Watts / Battery voltage + current discharge
- Size of an asset within the flutter app

I am aware of this package system_info (https://pub.dev/packages/system_info), however, I am not able to access the aforementioned specific values programmatically within my flutter app. Can someone let me know if accessing these values are possible or not?
And if yes, then how can I achieve it?

**Comment by TahaTesser** [comment]
Adding `would be a good package` if the can be separate package to get these low level system  information

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
