### ISSUE TITLE
CupertinoSlidingSegmentedControl crash : AnimationController.animateTo() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by palicka** [flutter/flutter#63338]
App is crashing when using CupertinoSlidingSegmentedControl  (on Iphone 6s). I'm doing some heavy work (loading maps with many polygons) while using this slider, and when I swipe it back really soon, it crashes (not every time)

stack trace:
```
The following assertion was thrown while handling a gesture:
AnimationController.animateTo() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 512 pos 7: '_ticker != null'

When the exception was thrown, this was the stack: 
#2      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:512:7)
#3      _SegmentedControlState.pressed= (package:flutter/src/cupertino/sliding_segmented_control.dart:384:36)
#4      _RenderSegmentedControl.pressedIndex= (package:flutter/src/cupertino/sliding_segmented_control.dart:662:11)
#5      _RenderSegmentedControl._onCancel (package:flutter/src/cupertino/sliding_segmented_control.dart:746:5)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onCancel"
Recognizer: HorizontalDragGestureRecognizer#c3c53
  start behavior: start
```

flutter doctor:
> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.3 19D76, locale en-GB)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
> [✓] Android Studio (version 3.6)

**Comment by pedromassangocode** [comment]
Hi @palicka 
Are you still having this issue? Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
