### ISSUE TITLE
Cupertino dat picker in rtl language

### ISSUE THREAD

**Issue by mo-ah-dawood** [flutter/flutter#63337]
Cupertino date picker has wrong positions in rtl direction
![Screenshot_٢٠٢٠٠٨٠٩-١٨٠٨٥٤](https://user-images.githubusercontent.com/31937782/89736739-d0f08180-da6b-11ea-89b7-e29bed07755a.jpg)

It has to be 
(am or pm)  hours  minutes date
Not
 (am or pm)  minutes hours date
Or we need an order property for positions

**Comment by HansMuller** [comment]
CC @rami-a @darrenaustin
