### ISSUE TITLE
Flutter Datatable - Working example with multiple columns enabled for sorting

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#63346]
Could we please have an example with multiple columns enabled for sorting?
https://api.flutter.dev/flutter/material/DataTable-class.html

**Comment by clocksmith** [comment]
Can you clarify is this means that multiple columns can be sorted, or that the row order can be sorted depending on the values multiple columns at once?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
