### ISSUE TITLE
Some build failures for flutter_app targets are opaque

### ISSUE THREAD

**Issue by pylaligand** [flutter/flutter#6335]
Context: trying to build a flutter_app whose dependencies are not properly set.

Error message of `<engine>/build/package.py`:
```
Failed to run the Flutter compiler. Exit code: 1
Error building /foo/bar/fuchsia/out/debug-x86-64/user_shell.flx: 1
```

Seems to be failing at the snapshotting phase, which when run manually produces:
```
[ERROR:../../lib/tonic/file_loader/file_loader.cc(155)] error: Unable to read Dart source 'package:flutter/services.dart'.
```

And indeed the flutter_app was missing a dependency. That second error message should however appear in the build logs to be helpful. It looks like [runCommandAndStreamOutput](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/process.dart#L58) is not catching the log produced by [tonic's file_loader](https://fuchsia.googlesource.com/tonic/+/master/file_loader/file_loader.cc#155).

**Comment by abarth** [comment]
How can I repro?  Just add a random bad import to something that builds with `flutter_app`?

**Comment by pylaligand** [comment]
Yes that's how I was able to repro. However this seems to be working now for some reason.
