### ISSUE TITLE
third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.

### ISSUE THREAD

**Issue by sumanthkumarps** [flutter/flutter#63356]
flutter run
```
Downloading Web SDK...                                              2.8s
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "windows_x64"
pid=37052, thread=18264, isolate_group=main(000001F171E0BBF0), isolate=main(000001F171E1C140)
isolate_instructions=1f170800000, vm_instructions=7ff7ad189820
  pc 0x00007ff7ad310ebc fp 0x00000008e8bfd4d0 Unknown symbol
-- End of DumpStackTrace
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android}
Attempting to read last messages from the daemon log...
Daemon pid: 33952
  log file: C:\Users\sumanthkumarps\.gradle\daemon\5.6.2\daemon-33952.out.log
----- Last  20 lines from daemon log file - daemon-33952.out.log -----
10:06:35.202 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 17: received class org.gradle.launcher.daemon.protocol.Build
10:06:35.202 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 17: Received non-IO message from client: Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android}
10:06:35.202 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android}.
10:06:35.203 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android} with connection: socket connection from /127.0.0.1:61836 to /127.0.0.1:61837.
10:06:35.204 [ERROR] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android}, connection = DefaultDaemonConnection: socket connection from /127.0.0.1:61836 to /127.0.0.1:61837] after 0.0 minutes of idle
10:06:35.204 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Marking the daemon as busy, address: [acd30f02-a207-481d-bcab-aeed35f5c947 port:61836, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]]
10:06:35.205 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [acd30f02-a207-481d-bcab-aeed35f5c947 port:61836, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]]
10:06:35.206 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
10:06:35.207 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
10:06:35.209 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
10:06:35.210 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
10:06:35.210 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
10:06:35.211 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=8979e2db-ac25-4427-ba50-cc36b1352e62, currentDir=D:\teplay\AndroidClient\Flutter\teplay\android}. Dispatching build started information...
10:06:35.211 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 19: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
10:06:35.213 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\sumanthkumarps\AppData\Local\Android\Sdk\platform-tools\;C:\Program Files\Java\jdk1.8.0_231\bin\;D:\flutter_windows_1.17.5-stable\flutter\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\sumanthkumarps\AppData\Local\Android\Sdk\platform-tools\;C:\Program Files\Java\jdk1.8.0_231\bin\;C:\Users\sumanthkumarps\AppData\Local\Microsoft\WindowsApps;;C:\Users\sumanthkumarps\AppData\Local\Programs\Microsoft VS Code\bin;C:\flutter_windows_1.17.2-stable\flutter\bin, USERDOMAIN_ROAMINGPROFILE=TELXSI, PROCESSOR_LEVEL=6, SYSTEMDRIVE=C:, SESSIONNAME=RDP-Tcp#76, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, DRIVERDATA=C:\Windows\System32\Drivers\DriverData, DEFLOGDIR=C:\ProgramData\McAfee\Endpoint Security\Logs, PROGRAMFILES=C:\Program Files, PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules, PROGRAMDATA=C:\ProgramData, DIRNAME=D:\teplay\AndroidClient\Flutter\teplay\android\, USERNAME=sumanthkumarps, USERDNSDOMAIN=TELXSI.COM, CMD_LINE_ARGS=-q -Ptarget-platform=android-x86 -Ptarget=D:\teplay\AndroidClient\Flutter\teplay\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug, ONEDRIVE=C:\Users\sumanthkumarps\OneDrive, APP_HOME=D:\teplay\AndroidClient\Flutter\teplay\android\, MINGIT_PATH=D:\flutter_windows_1.17.5-stable\flutter\bin\mingit\cmd, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, ONEDRIVECONSUMER=C:\Users\sumanthkumarps\OneDrive, SNAPSHOT_PATH=D:\flutter_windows_1.17.5-stable\flutter\bin\cache\flutter_tools.snapshot, SHARED_BIN=D:\flutter_windows_1.17.5-stable\flutter/bin/internal/shared.bat, WINDIR=C:\Windows, HOMEPATH=\Users\sumanthkumarps, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel, PUBLIC=C:\Users\Public, CACHE_DIR=D:\flutter_windows_1.17.5-stable\flutter\bin\cache, _SKIP=2, LOCALAPPDATA=C:\Users\sumanthkumarps\AppData\Local, COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files, USERDOMAIN=TELXSI, DART_SDK_PATH=D:\flutter_windows_1.17.5-stable\flutter\bin\cache\dart-sdk, LOGONSERVER=\\GANDHARA, FLUTTER_TOOLS_DIR=D:\flutter_windows_1.17.5-stable\flutter\packages\flutter_tools, PROMPT=$P$G, JAVA_HOME=C:\Users\sumanthkumarps\Downloads\android-studio-ide-191.6010548-windows\android-studio\jre, PROGRAMFILES(X86)=C:\Program Files (x86), FLUTTER_ROOT=D:\flutter_windows_1.17.5-stable\flutter, APPDATA=C:\Users\sumanthkumarps\AppData\Roaming, PROGRAMW6432=C:\Program Files, SYSTEMROOT=C:\Windows, JAVA_EXE=C:\Users\sumanthkumarps\Downloads\android-studio-ide-191.6010548-windows\android-studio\jre/bin/java.exe, DART=D:\flutter_windows_1.17.5-stable\flutter\bin\cache\dart-sdk\bin\dart.exe, FLUTTER_SUPPRESS_ANALYTICS=true, OS=Windows_NT, COMMONPROGRAMW6432=C:\Program Files\Common Files, COMPUTERNAME=SUMANTHKUMAR_PS, COMMONPROGRAMFILES=C:\Program Files\Common Files, COMSPEC=C:\Windows\system32\cmd.exe, PROCESSOR_REVISION=9e0a, CLASSPATH=D:\teplay\AndroidClient\Flutter\teplay\android\\gradle\wrapper\gradle-wrapper.jar, APP_BASE_NAME=gradlew, =D:=D:\teplay\AndroidClient\Flutter\teplay\android, TEMP=C:\Users\SUMANT~1\AppData\Local\Temp, FLUTTER_ALREADY_LOCKED=true, HOMEDRIVE=C:, USERPROFILE=C:\Users\sumanthkumarps, TMP=C:\Users\SUMANT~1\AppData\Local\Temp, NUMBER_OF_PROCESSORS=6, CLIENTNAME=LAPTOP-5QDQAKLH}
10:06:35.216 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
10:06:35.216 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 33952). The daemon log file: C:\Users\sumanthkumarps\.gradle\daemon\5.6.2\daemon-33952.out.log
10:06:35.217 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 1.4 GB]
10:06:35.221 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
10:06:35.221 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=49650a92-022d-4ac3-a84d-9dea6b43c02a,javaHome=C:\Users\sumanthkumarps\Downloads\android-studio-ide-191.6010548-windows\android-studio\jre,daemonRegistryDir=C:\Users\sumanthkumarps\.gradle\daemon,pid=33952,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx1536M,-Dfile.encoding=windows-1252,-Duser.country=IN,-Duser.language=en,-Duser.variant]
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         5.1s
the Dart compiler exited unexpectedly.
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by sumanthkumarps** [comment]
flutter doctor -v
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale en-IN)
    • Flutter version 1.20.0 at D:\flutter_windows_1.17.5-stable\flutter
    • Framework revision 916c3ac648 (9 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\sumanthkumarps\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Users\sumanthkumarps\Downloads\android-studio-ide-191.6010548-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\sumanthkumarps\Downloads\android-studio-ide-191.6010548-windows\android-studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\sumanthkumarps\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @sumanthkumarps 
Can you please provide your complete `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Ravi-Sharma792** [comment]
I'm also facing the same issue just after the flutter 1.20 update

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Sandwich2080** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Running Gradle task 'assembleRelease'...                               \../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "windows_x64"
pid=17696, thread=18072, isolate_group=main(00000101795C4F60), isolate=main(00000101795C6910)
isolate_instructions=7ff75ab89810, vm_instructions=7ff75ab89820
  pc 0x00007ff75ad10ebc fp 0x0000000100afabc0 Unknown symbol
-- End of DumpStackTrace
[exit     : sp(0) fp(0x100afd8a8) pc(0)]
[stub     : sp(0x100afd8b8) fp(0x100afd8d8) pc(0x10178e80e84)]
[dart     : sp(0x100afd8e8) fp(0x100afd930) pc(0x1010171bab2) dart:core__RegExp@0150898_hasMatch ]
[dart     : sp(0x100afd940) fp(0x100afd9a0) pc(0x101078b83c6) package:flutter_tools/src/android/gradle.dart_::_buildGradleApp__async_op_consumeLog ]
[dart     : sp(0x100afd9b0) fp(0x100afd9f8) pc(0x101022e0864) package:flutter_tools/src/base/process.dart__DefaultProcessUtils@74014270_stream__async_op_<anonymous closure> ]
[dart     : sp(0x100afda08) fp(0x100afda78) pc(0x10101712976) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x100afda88) fp(0x100afdaf0) pc(0x101017127bd) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x100afdb00) fp(0x100afdb98) pc(0x10101711f16) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x100afdba8) fp(0x100afdc28) pc(0x1010274ac63) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x100afdc38) fp(0x100afdc78) pc(0x101078d42c5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x100afdc88) fp(0x100afdcb8) pc(0x1010274a484) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afdcc8) fp(0x100afdcf8) pc(0x101022e056f) dart:async__ForwardingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afdd08) fp(0x100afdd68) pc(0x101022dfdbb) dart:async__WhereStream@4048458__handleData@4048458 ]
[dart     : sp(0x100afdd78) fp(0x100afddb0) pc(0x101022df9a1) dart:async__ForwardingStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x100afddc0) fp(0x100afde00) pc(0x101022df737) dart:async__ForwardingStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x100afde10) fp(0x100afde80) pc(0x10101712976) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x100afde90) fp(0x100afdef8) pc(0x101017127bd) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x100afdf08) fp(0x100afdfa0) pc(0x10101711f16) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x100afdfb0) fp(0x100afe030) pc(0x1010274ac63) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x100afe040) fp(0x100afe080) pc(0x101078d42c5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x100afe090) fp(0x100afe0c0) pc(0x1010274a484) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afe0d0) fp(0x100afe100) pc(0x101022de60e) dart:async__SinkTransformerStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afe110) fp(0x100afe140) pc(0x101022de26e) dart:async__EventSinkWrapper@4048458_add ]
[dart     : sp(0x100afe150) fp(0x100afe180) pc(0x101022ddf54) dart:convert__StringAdapterSink@10003594_add ]
[dart     : sp(0x100afe190) fp(0x100afe1e0) pc(0x101022df32d) dart:convert__LineSplitterSink@10003594__addLines@10003594 ]
[dart     : sp(0x100afe1f0) fp(0x100afe238) pc(0x101022dedf7) dart:convert__LineSplitterSink@10003594_addSlice ]
[dart     : sp(0x100afe248) fp(0x100afe290) pc(0x101022de990) dart:convert_StringConversionSinkMixin_add ]
[dart     : sp(0x100afe2a0) fp(0x100afe2f8) pc(0x101022db047) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x100afe308) fp(0x100afe348) pc(0x101022dada7) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x100afe358) fp(0x100afe3c8) pc(0x10101712976) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x100afe3d8) fp(0x100afe440) pc(0x101017127bd) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x100afe450) fp(0x100afe4e8) pc(0x10101711f16) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x100afe4f8) fp(0x100afe578) pc(0x1010274ac63) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x100afe588) fp(0x100afe5c8) pc(0x101078d42c5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x100afe5d8) fp(0x100afe608) pc(0x1010274a484) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afe618) fp(0x100afe648) pc(0x101022de60e) dart:async__SinkTransformerStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afe658) fp(0x100afe688) pc(0x101022de26e) dart:async__EventSinkWrapper@4048458_add ]
[dart     : sp(0x100afe698) fp(0x100afe6c8) pc(0x101022ddf54) dart:convert__StringAdapterSink@10003594_add ]
[dart     : sp(0x100afe6d8) fp(0x100afe710) pc(0x101022ddc61) dart:convert__StringAdapterSink@10003594_addSlice ]
[dart     : sp(0x100afe720) fp(0x100afe770) pc(0x101022db959) dart:convert__Utf8ConversionSink@10003594_addSlice ]
[dart     : sp(0x100afe780) fp(0x100afe7c8) pc(0x101022db724) dart:convert__Utf8ConversionSink@10003594_add ]
[dart     : sp(0x100afe7d8) fp(0x100afe808) pc(0x101022db43e) dart:convert__ConverterStreamEventSink@10003594_add ]
[dart     : sp(0x100afe818) fp(0x100afe870) pc(0x101022db047) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x100afe880) fp(0x100afe8c0) pc(0x101022dada7) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x100afe8d0) fp(0x100afe940) pc(0x10101712976) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x100afe950) fp(0x100afe9b8) pc(0x101017127bd) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x100afe9c8) fp(0x100afea60) pc(0x10101711f16) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x100afea70) fp(0x100afeaf0) pc(0x1010274ac63) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x100afeb00) fp(0x100afeb40) pc(0x101078d42c5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x100afeb50) fp(0x100afeb80) pc(0x1010274a484) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afeb90) fp(0x100afebc0) pc(0x10102749e8e) dart:async__SyncStreamController@4048458__sendData@4048458 ]
[dart     : sp(0x100afebd0) fp(0x100afec00) pc(0x10102749b25) dart:async__StreamController@4048458__add@4048458 ]
[dart     : sp(0x100afec10) fp(0x100afec40) pc(0x1010274975f) dart:async__StreamController@4048458_add ]
[dart     : sp(0x100afec50) fp(0x100afec90) pc(0x101022d5d02) dart:io__Socket@15069316__onData@15069316 ]
[dart     : sp(0x100afeca0) fp(0x100afece0) pc(0x101022d5b07) dart:io__Socket@15069316__onData@15069316__onData@15069316 ]
[dart     : sp(0x100afecf0) fp(0x100afed60) pc(0x10101712a9f) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x100afed70) fp(0x100afedd8) pc(0x101017127bd) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x100afede8) fp(0x100afee80) pc(0x10101711f16) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x100afee90) fp(0x100afef10) pc(0x1010274ac63) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x100afef20) fp(0x100afef60) pc(0x101078d42c5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x100afef70) fp(0x100afefa0) pc(0x1010274a484) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x100afefb0) fp(0x100afefe0) pc(0x10102749e8e) dart:async__SyncStreamController@4048458__sendData@4048458 ]
[dart     : sp(0x100afeff0) fp(0x100aff020) pc(0x10102749b25) dart:async__StreamController@4048458__add@4048458 ]
[dart     : sp(0x100aff030) fp(0x100aff060) pc(0x1010274975f) dart:async__StreamController@4048458_add ]
[dart     : sp(0x100aff070) fp(0x100aff0b0) pc(0x101022d58ec) dart:io__RawSocket@15069316__RawSocket@15069316._<anonymous closure> ]
[dart     : sp(0x100aff0c0) fp(0x100aff0e8) pc(0x10101764f17) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x100aff0f8) fp(0x100aff140) pc(0x101022b2a7a) dart:io__NativeSocket@15069316_issueReadEvent_issue ]
[dart     : sp(0x100aff150) fp(0x100aff188) pc(0x1010170ef63) dart:async_::__microtaskLoop@4048458 ]
[dart     : sp(0x100aff198) fp(0x100aff1c8) pc(0x1010170ebc4) dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x100aff1d8) fp(0x100aff208) pc(0x1010170ead7) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x100aff218) fp(0x100aff248) pc(0x1010170e8e3) dart:isolate_::__runPendingImmediateCallback@1026248 ]
[dart     : sp(0x100aff258) fp(0x100aff270) pc(0x1017c133f2d) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x100aff280) fp(0x100aff398) pc(0x10178e81388)]

This is the stacktrace message, hope this can help solve the issue.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pratiksonwane** [comment]
Launching lib\main.dart on AC2001 in debug mode...
lib\main.dart:1
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\Abhay\AppData\Local\Android\Sdk\licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
Installing Android SDK Build-Tools 28.0.3 in C:\Users\Abhay\AppData\Local\Android\Sdk\build-tools\28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
Checking the license for package Android SDK Platform 29 in C:\Users\Abhay\AppData\Local\Android\Sdk\licenses
License for package Android SDK Platform 29 accepted.
Preparing "Install Android SDK Platform 29 (revision: 5)".
"Install Android SDK Platform 29 (revision: 5)" ready.
Installing Android SDK Platform 29 in C:\Users\Abhay\AppData\Local\Android\Sdk\platforms\android-29
"Install Android SDK Platform 29 (revision: 5)" complete.
"Install Android SDK Platform 29 (revision: 5)" finished.
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=4280, thread=1400, isolate_group=main(00000232ACD71CF0), isolate=main(00000232ACD8BDB0)
isolate_instructions=232abe00000, vm_instructions=7ff6e35ef240

  pc 0x00007ff6e37800ec fp 0x000000aa33bfdc70 Unknow
n symbol
-- End of DumpStackTrace
3

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 59s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)




Please help me with this.

**Comment by andreweop** [comment]
Hello is there new update about this issue? i have tried to restart Vscode, i have tried restarting Android Studio, i have tried increasing the VM heap to 600mb in android studio and nothing seems to work. this is the error i keep receiving
`Launching lib\main.dart on AOSP on IA Emulator in debug mode...
lib\main.dart:1
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64"
pid=9544, thread=25092, isolate_group=main(000002D806B72C50), isolate=main(000002D806B4F360)
isolate_instructions=7ff61fc3f950, vm_instructions=7ff61fc3f960
  pc 0x00007ff61fdc0fb2 fp 0x000000fd5e4fc7e0 Unknown symbol
-- End of DumpStackTrace
[exit     : sp(0) fp(0xfd5e4fda50) pc(0)]
[stub     : sp(0xfd5e4fda60) fp(0xfd5e4fda80) pc(0x2d806c81ea4)]
[dart     : sp(0xfd5e4fda90) fp(0xfd5e4fdad8) pc(0x2d810316b6c) dart:core__RegExp@0150898_hasMatch ]
`
thanks in advance

**Comment by andreweop** [comment]
> Hello is there new update about this issue? i have tried to restart Vscode, i have tried restarting Android Studio, i have tried increasing the VM heap to 600mb in android studio and nothing seems to work. this is the error i keep receiving
> `Launching lib\main.dart on AOSP on IA Emulator in debug mode... lib\main.dart:1 ../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory. version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64" pid=9544, thread=25092, isolate_group=main(000002D806B72C50), isolate=main(000002D806B4F360) isolate_instructions=7ff61fc3f950, vm_instructions=7ff61fc3f960 pc 0x00007ff61fdc0fb2 fp 0x000000fd5e4fc7e0 Unknown symbol -- End of DumpStackTrace [exit : sp(0) fp(0xfd5e4fda50) pc(0)] [stub : sp(0xfd5e4fda60) fp(0xfd5e4fda80) pc(0x2d806c81ea4)] [dart : sp(0xfd5e4fda90) fp(0xfd5e4fdad8) pc(0x2d810316b6c) dart:core__RegExp@0150898_hasMatch ] `
> thanks in advance

This problem have been solved after doing all the following solutions and restarting my computer.

**Comment by bukunmialuko** [comment]
I dont know if this is a standard solution but, the java installed on my windows machine was java 11, i uninstalled it and installed the latest java 8. I restarted the pc, then built the project an i didnt get the error again. I have restarted my pc before this porcess but this solved the issue for me.
