### ISSUE TITLE
Execute flutter run on the last/default device selection after timeout

### ISSUE THREAD

**Issue by rohan20** [flutter/flutter#63365]
## Use case

![image](https://user-images.githubusercontent.com/8232573/89763198-57e83d00-daf2-11ea-8574-3f276757b900.png)

The ability to type in a digit to select which device to run on is a great addition to the tooling. Thanks for that. 

However, after typing in the `flutter run` command, I mostly move away from the IDE/Terminal until the app builds, assuming that I'd see the app show up on my device anyway and I'll know that my app built correctly. 

But there's a minor problem when I have multiple devices connected. Since I moved away after `flutter run`, I never provide an input to the device selection prompt that shows up after a few seconds after `flutter run`.

## Proposal

**Solution 1:** Automatically run on the last selected device after a timeout. 
**Solution 2:** Automatically run on Device #0 from the list after a timeout. 

Timeout suggestion: 20 seconds. Seems enough to look through a list of up to ~5 devices and make a selection.

**Comment by jmagman** [comment]
If you know which device to run on, you can pass in `-d <device-id>` to `flutter run`.  The device selection is a convenience over that.  I think it would be unexpected for a prompt like that to time out and disappear and run on a random device.

After the device selection, it would be nice to print something like:
```
To run on this device next time, try "flutter <exactly the command they ran> -d <selected device ID>"
```
like:
```
To always run on this device next time, try "flutter run --release -d 23049829583405983"
```

**Comment by rohan20** [comment]
I'm aware of `-d <device-id>` and that's what I used prior to this useful change in the tooling. Even without this change to the tooling, the idea of automatically running a default device after a timeout seems nice for the developer's experience.

**Comment by jmagman** [comment]
@zanderso @jonahwilliams for opinions.

**Comment by jmagman** [comment]
> Also, does the prompt have to disappear? Why can't it enter 0 on its own and continue in the same manner like it would've with a manual input?

Sure, or that.  Also unexpected, but spookier.

**Comment by jonahwilliams** [comment]
I can't think of any examples of a CLI prompt that resolves itself after a timeout - I think it would be pretty un-intuitive behavior.

**Comment by zanderso** [comment]
@rohan20 Thanks for the proposal, but I think I agree with @jonahwilliams that this is probably in the category of being a bit too smart for a command line tool. To mitigate any inconvenience, it seems like @jmagman's suggesting in https://github.com/flutter/flutter/issues/63541 will help---just copy and paste for subsequent runs.
