### ISSUE TITLE
Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.

### ISSUE THREAD

**Issue by praveengupta0895** [flutter/flutter#63360]
### This is the Issue:

After Upgrading the flutter to the latest version. I'm facing this issue, I've the same code for another application having earlier version of flutter and it is working fine.

What it does with my list view is that:

With the new ListView add two or more children.
Scroll down the list to the point where the first child is entirely off the screen.
Make any changes to the contents, so that the first child reduces its height.
Scroll all the way back up to the initial position. The ListView shows nothing on screen (just white empty space).

### Console Log:

`════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)
The relevant error-causing widget was: 
  ListView file:///G:/abc/abc/lib/HomeScreen/HomeScreenDemo.dart:787:34
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///G:/abc/abc/lib/HomeScreen/HomeScreenDemo.dart:787:34
When the exception was thrown, this was the stack: 
#2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
#3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
#6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#80e2a relayoutBoundary=up33 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 395.4, crossAxisExtent: 300.0, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 395.4, remainingCacheExtent: 645.4, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 2025.0, paintExtent: 395.4, maxPaintExtent: 2025.0, hasVisualOverflow: true, cacheExtent: 895.4)
...    scrollExtent: 2025.0
...    paintExtent: 395.4
...    maxPaintExtent: 2025.0
...    hasVisualOverflow: true
...    cacheExtent: 895.4
...  currently live children: 72 to 80
RenderObject: RenderSliverList#80e2a relayoutBoundary=up33 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 395.4, crossAxisExtent: 300.0, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 395.4, remainingCacheExtent: 645.4, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 2025.0, paintExtent: 395.4, maxPaintExtent: 2025.0, hasVisualOverflow: true, cacheExtent: 895.4)
    scrollExtent: 2025.0
    paintExtent: 395.4
    maxPaintExtent: 2025.0
    hasVisualOverflow: true
    cacheExtent: 895.4
  currently live children: 72 to 80
...  child with index 72: RenderIndexedSemantics#4719b relayoutBoundary=up34 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: index=72; layoutOffset=None (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(0.0, 300.0)
...    index: 72
...    child: RenderRepaintBoundary#7395c relayoutBoundary=up35 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      size: Size(0.0, 300.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderLimitedBox#2949c relayoutBoundary=up36 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(0.0, 300.0)
...        maxWidth: 0.0
...        maxHeight: 0.0
...        child: RenderConstrainedBox#797d3 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=0.0, h=300.0)
...          size: Size(0.0, 300.0)
...          additionalConstraints: BoxConstraints(biggest)
...  child with index 73: RenderIndexedSemantics#b19d0 relayoutBoundary=up34 NEEDS-PAINT
...    needs compositing
...    parentData: index=73; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(216.0, 300.0)
...    index: 73
...    child: RenderRepaintBoundary#222ae relayoutBoundary=up35 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      size: Size(216.0, 300.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderStack#0c631 relayoutBoundary=up36 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(216.0, 300.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderPadding#f63e0 relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 2: RenderPadding#40eb7 relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 3: RenderPadding#3001c relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 300.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 4: RenderPadding#46a5e relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(30.0, 30.0)
...          padding: EdgeInsets(10.0, 10.0, 0.0, 0.0)
...          textDirection: ltr
...        child 5: RenderPadding#a98d0 relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(195.0, 300.0)
...          padding: EdgeInsets(0.0, 130.0, 0.0, 0.0)
...          textDirection: ltr
...        child 6: RenderPadding#8842c relayoutBoundary=up37 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(200.0, 165.0)
...          padding: EdgeInsets(100.0, 0.0, 0.0, 0.0)
...          textDirection: ltr
...  child with index 74: RenderIndexedSemantics#ac52a relayoutBoundary=up34 NEEDS-PAINT
...    needs compositing
...    parentData: index=74; layoutOffset=216.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(0.0, 300.0)
...    index: 74
...    child: RenderRepaintBoundary#7fb20 relayoutBoundary=up35 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      size: Size(0.0, 300.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderLimitedBox#2f07c relayoutBoundary=up36 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(0.0, 300.0)
...        maxWidth: 0.0
...        maxHeight: 0.0
...        child: RenderConstrainedBox#a803d NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=0.0, h=300.0)
...          size: Size(0.0, 300.0)
...          additionalConstraints: BoxConstraints(biggest)
...  child with index 75: RenderIndexedSemantics#aaab8 relayoutBoundary=up34
...    needs compositing
...    parentData: index=75; layoutOffset=216.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(216.0, 300.0)
...    index: 75
...    child: RenderRepaintBoundary#4429a relayoutBoundary=up35
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#e1570 DETACHED
...        engine layer: OffsetEngineLayer#a4408
...        offset: Offset(-70.2, 0.0)
...      size: Size(216.0, 300.0)
...      metrics: 50.0% useful (1 bad vs 1 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderStack#78a8d relayoutBoundary=up36
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(216.0, 300.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderPadding#5f7e0 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 2: RenderPadding#349c5 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 3: RenderPadding#25434 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 300.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 4: RenderPadding#b544d relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(30.0, 30.0)
...          padding: EdgeInsets(10.0, 10.0, 0.0, 0.0)
...          textDirection: ltr
...        child 5: RenderPadding#eba0e relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(195.0, 300.0)
...          padding: EdgeInsets(0.0, 130.0, 0.0, 0.0)
...          textDirection: ltr
...        child 6: RenderPadding#77bfb relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(200.0, 165.0)
...          padding: EdgeInsets(100.0, 0.0, 0.0, 0.0)
...          textDirection: ltr
...  child with index 76: RenderIndexedSemantics#8d1d6 relayoutBoundary=up34
...    needs compositing
...    parentData: index=76; layoutOffset=432.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(0.0, 300.0)
...    index: 76
...    child: RenderRepaintBoundary#b39ee relayoutBoundary=up35
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#b0b4d DETACHED
...        engine layer: OffsetEngineLayer#0526f
...        offset: Offset(145.8, 0.0)
...      size: Size(0.0, 300.0)
...      metrics: 50.0% useful (1 bad vs 1 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderLimitedBox#9536e relayoutBoundary=up36
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(0.0, 300.0)
...        maxWidth: 0.0
...        maxHeight: 0.0
...        child: RenderConstrainedBox#e7a50
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=0.0, h=300.0)
...          size: Size(0.0, 300.0)
...          additionalConstraints: BoxConstraints(biggest)
...  child with index 77: RenderIndexedSemantics#2cb8b relayoutBoundary=up34
...    needs compositing
...    parentData: index=77; layoutOffset=432.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(216.0, 300.0)
...    index: 77
...    child: RenderRepaintBoundary#eaa36 relayoutBoundary=up35
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#08870 DETACHED
...        engine layer: OffsetEngineLayer#7c207
...        offset: Offset(145.8, 0.0)
...      size: Size(216.0, 300.0)
...      metrics: 88.9% useful (1 bad vs 8 good)
...      diagnosis: this is a useful repaint boundary and should be kept
...      child: RenderStack#ab8f6 relayoutBoundary=up36
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(216.0, 300.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderPadding#d4967 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 2: RenderPadding#aa908 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 3: RenderPadding#f138f relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 300.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 4: RenderPadding#807fb relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(30.0, 30.0)
...          padding: EdgeInsets(10.0, 10.0, 0.0, 0.0)
...          textDirection: ltr
...        child 5: RenderPadding#2bb3c relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(195.0, 300.0)
...          padding: EdgeInsets(0.0, 130.0, 0.0, 0.0)
...          textDirection: ltr
...        child 6: RenderPadding#30066 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(200.0, 165.0)
...          padding: EdgeInsets(100.0, 0.0, 0.0, 0.0)
...          textDirection: ltr
...  child with index 78: RenderIndexedSemantics#b136a relayoutBoundary=up34
...    needs compositing
...    parentData: index=78; layoutOffset=648.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(0.0, 300.0)
...    index: 78
...    child: RenderRepaintBoundary#11957 relayoutBoundary=up35
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#b3183 DETACHED
...        engine layer: OffsetEngineLayer#e3d7d
...        offset: Offset(361.8, 0.0)
...      size: Size(0.0, 300.0)
...      metrics: 83.3% useful (1 bad vs 5 good)
...      diagnosis: this is a useful repaint boundary and should be kept
...      child: RenderLimitedBox#76ccf relayoutBoundary=up36
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(0.0, 300.0)
...        maxWidth: 0.0
...        maxHeight: 0.0
...        child: RenderConstrainedBox#2203a
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=0.0, h=300.0)
...          size: Size(0.0, 300.0)
...          additionalConstraints: BoxConstraints(biggest)
...  child with index 79: RenderIndexedSemantics#8bf38 relayoutBoundary=up34 NEEDS-LAYOUT
...    needs compositing
...    parentData: index=79; layoutOffset=648.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(216.0, 300.0)
...    index: 79
...    child: RenderRepaintBoundary#fc6d2 relayoutBoundary=up35 NEEDS-LAYOUT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#41aec DETACHED
...        engine layer: OffsetEngineLayer#01b84
...        offset: Offset(361.8, 0.0)
...      size: Size(216.0, 300.0)
...      metrics: 87.5% useful (1 bad vs 7 good)
...      diagnosis: this is a useful repaint boundary and should be kept
...      child: RenderStack#966b6 relayoutBoundary=up36 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(216.0, 300.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderPadding#a0b58 relayoutBoundary=up37 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 2: RenderPadding#0a891 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 3: RenderPadding#d9929 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 300.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 4: RenderPadding#10592 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(30.0, 30.0)
...          padding: EdgeInsets(10.0, 10.0, 0.0, 0.0)
...          textDirection: ltr
...        child 5: RenderPadding#85406 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(195.0, 300.0)
...          padding: EdgeInsets(0.0, 130.0, 0.0, 0.0)
...          textDirection: ltr
...        child 6: RenderPadding#8a578 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(200.0, 165.0)
...          padding: EdgeInsets(100.0, 0.0, 0.0, 0.0)
...          textDirection: ltr
...  child with index 80: RenderIndexedSemantics#e2814 relayoutBoundary=up34 NEEDS-LAYOUT
...    needs compositing
...    parentData: index=80; layoutOffset=864.0 (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...    semantic boundary
...    size: Size(216.0, 300.0)
...    index: 80
...    child: RenderRepaintBoundary#7aa58 relayoutBoundary=up35 NEEDS-LAYOUT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...      layer: OffsetLayer#f5fa7 DETACHED
...        engine layer: OffsetEngineLayer#d2f36
...        offset: Offset(212.6, 0.0)
...      size: Size(216.0, 300.0)
...      metrics: 75.0% useful (1 bad vs 3 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderStack#36b4e relayoutBoundary=up36 NEEDS-LAYOUT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=300.0)
...        size: Size(216.0, 300.0)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        child 1: RenderPadding#bb486 relayoutBoundary=up37 NEEDS-LAYOUT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 2: RenderPadding#cfbae relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 136.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 3: RenderPadding#399ac relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(216.0, 300.0)
...          padding: EdgeInsets.all(8.0)
...          textDirection: ltr
...        child 4: RenderPadding#3f089 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(30.0, 30.0)
...          padding: EdgeInsets(10.0, 10.0, 0.0, 0.0)
...          textDirection: ltr
...        child 5: RenderPadding#42e35 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(195.0, 300.0)
...          padding: EdgeInsets(0.0, 130.0, 0.0, 0.0)
...          textDirection: ltr
...        child 6: RenderPadding#f3222 relayoutBoundary=up37
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=300.0)
...          size: Size(200.0, 165.0)
...          padding: EdgeInsets(100.0, 0.0, 0.0, 0.0)
...          textDirection: ltr
`
### After running Flutter Doctor:

G:\abc\abc>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

**Comment by KrunalRGandhi** [comment]
@praveengupta0895 hi, did you find a solution for this issue? I am facing similar issue.

**Comment by praveengupta0895** [comment]
Hi @KrunalRGandhi ,
No, still looking for help. Please refer to this case I'd #63380 for further assistance and raise the question as well and you can also provide your minimal reproducible code there.

**Comment by praveengupta0895** [comment]
@KrunalRGandhi , Now I'm able to resolve it. Go and see the newer post.
