### ISSUE TITLE
childMainAxisExtent != null && childMainAxisExtent >= 0'

### ISSUE THREAD

**Issue by orihgc** [flutter/flutter#63381]
return SliverGrid(
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return lessonWidgets[index];
        },
        childCount: lessonWidgets.length,
      ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 12,
        crossAxisSpacing: 12,
      ),
    );

**Comment by pedromassangocode** [comment]
Hi @orihgc 
For the issue to be workable, it needs to be reproducible with a [minimal complete code](https://stackoverflow.com/help/minimal-reproducible-example) sample that doesn’t include 3rd party plugins or complex production code. Please provide such sample.

You also need to provide the actual vs expected result description.
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
