### ISSUE TITLE
Load local files with webview_flutter

### ISSUE THREAD

**Issue by pvegh** [flutter/flutter#63392]
I need to download a html file to the local storage in ios/android apps and load it in webview. Let's say somewhere in the library folder (iOS). I haven't seen a solution for this, is it possible?

It cannot be in assets and cannot list them manually, since they are dynamic and there might be countless of them.

**Comment by darshankawar** [comment]
Hi @pvegh,
Check out [this](https://www.rrtutors.com/tutorials/Webview-in-flutter-Open-Local-HTML-file-in-to-webview) and [this](https://inducesmile.com/google-flutter/how-load-a-local-html-file-in-flutter-webview/) link and see if they answer your question / requirement.

**Comment by pvegh** [comment]
They don't, both are loading html from asset folder. We want to load unbundled html files that are located in e.g. flutterAppRoot/Library or Documents folders (example for iOS)

**Comment by pvegh** [comment]
I think I can attach a demo project today to showcase what we're trying to do. We found a workaround which looks ugly, and only works on Android, not iOS. Maybe it helps to more quickly find a solution.

**Comment by pvegh** [comment]
So here's the mentioned solution: https://github.com/pvegh/flutter_webview_local
It works on Android, doesn't work on iOS, see error below.
It would be nice if this would work on both platforms. I'm open for ideas of course.

[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/.../Library/Developer/CoreSimulator/Devices/C4520E1E-A283-4C3B-8FB4-8199D585E311/data/Containers/Data/Application/C722AFD0-83A9-4724-80CB-32A0740D43BF/Library/data:texthtml;charset=utf-8,%3Chtml%3E%0A%3Ca%20href=%22bar.html%22%3Ebar%3Ca%3E%0A%3Chtml%3E' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)

**Comment by lydongcanh** [comment]
Use ` Uri.directory` method seems to do the trick for me.
It also render all linked css & javascript files, while load data as string doesn't.

```
final uri = Uri.directory("$your_local_file_path");
final uriString = uri.toString().substring(0, uri.toString().length - 1); /// Remove final slash symbol
_webViewController.loadUrl(uriString);
```

**Comment by mikezander** [comment]
@pvegh Did you end up finding  a solution? May have to resort to native code.

**Comment by pvegh** [comment]
Looks like I posted a workaround above.
I switched to another project, so I don't have current information on this, sorry.

**Comment by stuartmorgan** [comment]
This was fixed by the PRs above, we just forgot to close it.
