### ISSUE TITLE
CupertinoSwitch - Provide the ability to add a border

### ISSUE THREAD

**Issue by mzegar** [flutter/flutter#63407]
## Use case

The `CupertinoSwitch` has no way to add a border to it. Attempting to use a `Container` with a `BoxDecoration` and `borderRadius` creates a thick border around the `CupertinoSwitch`. 

```
return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
        color: value
            ? activeBorderColor
            : inactiveBorderColor,
      ),
      child: CupertinoSwitch(
        value: value,
        activeColor: activeColor,
        onChanged: onChanged,
      ),
    );
```

The above creates a thick border around the `CupertinoSwitch`.

## Proposal

Add the ability to change the `borderColor` and `borderWidth` of a `CupertinoSwitch`. This will also allow the creation of thin borders around the `CupertinoSwitch`.

## PR implementation

https://github.com/flutter/flutter/pull/63423

**Comment by mzegar** [comment]
@HansMuller Hi, apologizes for bothering you, can I get this looked at by the appropriate parties? PR has been up for a while.
Thank you!

**Comment by xster** [comment]
We'd like to generally limit the scope of the Cupertino package to what's feasible in Xcode natively. Is there a customizable border with UISwitch?

**Comment by mzegar** [comment]
@xster 

This is how the CupertinoSwitch currently looks like on Flutter
![](https://i.imgur.com/ZKby8FZ.png)

Here is an example straight from the iOS settings I believe. You can see that the switches in the OFF state have a light grey colour with a darker outline.
![](https://cdn.osxdaily.com/wp-content/uploads/2014/04/on-off-labels-enabled-ios.jpg)

Another iOS image, check out the OFF state switch
![](https://developer.apple.com/design/human-interface-guidelines/ios/images/switches-default_2x.png)

There are also other images I found with some outline. Some being apart of iOS and others packages for other libraries.

**Comment by DanielEdrisian** [comment]
This has changed in iOS 14. There are no borders, as seen here:

<img src="https://user-images.githubusercontent.com/11810973/96312825-42dfcc80-0fc1-11eb-9945-ea658bd1b545.png" width=300>

Closing until there's further need in the future.
