### ISSUE TITLE
[e2e] Use vsyncStart from FrameTiming.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#63415]
## Use case

FrameTiming now provides a `vsyncStart` value. Update code and tests to account for it. See:

https://github.com/flutter/plugins/pull/2914#pullrequestreview-464486966

**Comment by CareF** [comment]
So this will be a very future todo, if we have to keep e2e compatible with the stable version.

**Comment by ditman** [comment]
Yep, I don't think you want to be assigned to this @CareF until it actually can be done.
