### ISSUE TITLE
Enable/disable luci tests in a single file per repository

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#63437]
As we are migrating tests to luci for all repos, a single file to control tests is needed, similar to the yaml file for cirrus tests (flutter): https://github.com/flutter/flutter/blob/master/.cirrus.yml

On builder level, we will use `try_builders.json` in different repos by adding an `enabled` flag.
- [x] add flag to engine
- [x] add flag to framework
- [x] add flag to cocoon
- [x] add flag to packages
- [x] updating cocoon backend to include enable/disable logic

**Comment by keyonghan** [comment]
@godofredoc Please correct me if anything is incorrect.

I guess what needs here is to enable/disable luci tasks in sub-shard level similar to [cirrus yaml file](https://github.com/flutter/flutter/blob/master/.cirrus.yml).

(on shard level, https://github.com/flutter/flutter/blob/master/dev/try_builders.json would be the source control to enable/disable a builder)

Sub-shards are configured in flutter/infra, but we want to control on repo level. With those manifest files ready in corresponding repos, cocoon will read those manifest before triggering pre-submit tasks. The `subshards ` value derived from the manifest file will be added to https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/service/luci_build_service.dart#L193 to replace server side configuration.

**Comment by godofredoc** [comment]
I was thinking on expanding the json file with an enabled flag. Something similar to the flaky flag but we will also need a way to disable tests from shards.

**Comment by keyonghan** [comment]
> I was thinking on expanding the json file with an enabled flag. Something similar to the flaky flag but we will also need a way to disable tests from shards.

Thanks. A flag is good to keep the historical builders all the time.
I will start from the builder level. Then move on to the shard level.
