### ISSUE TITLE
Please support Connect via network

### ISSUE THREAD

**Issue by tvtoankgi** [flutter/flutter#63435]
## Use case

XCode can detect device that Connect via network, no need cable.
## Proposal

Please support. Thank you

**Comment by darshankawar** [comment]
Hi @tvtoankgi,
Is this request for connecting iphone devices using network in Xcode or in Android Studio ?
Thanks.

**Comment by tvtoankgi** [comment]
Hi @darshankawar.
Thank you your support. XCode can detect my network connected iphone but Flutter doctor does not recognize. Please help Android Studio able to connect to iphone via network. 
Thank you very much.

**Comment by darshankawar** [comment]
Hi @tvtoankgi,
There seems to be an open issue similar to your case, [15072](https://github.com/flutter/flutter/issues/15072).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
