### ISSUE TITLE
ImagePicker.pickVideo(source: ImageSource.Gallery) returns jpg files and not the actual video selected.

### ISSUE THREAD

**Issue by jeromekai** [flutter/flutter#63444]
ImagePicker.pickVideo(source: ImageSource.Gallery) returns jpg files and not the actual video selected.

**Comment by shaohui93** [comment]
我也碰到了，你解决了么？
I met too. Have you solved it?

**Comment by darshankawar** [comment]
Hi @jeromekai,
There's similar open issue describing your case, [52419](https://github.com/flutter/flutter/issues/52419).
Please follow-up there for updates.
Closing this as duplicate.
