### ISSUE TITLE
[null-safety] migration of tests to null-safety is blocked by gallery dependency

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#63441]
We need to do breaking change releases for package:process/platform/file in order to migrate flutter_goldens and flutter_goldens_client. However, we have a dependency on the gallery in the macro-benchmarks. This transitively depends on a lower version of platform.

https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/pubspec.yaml#L21

```
Because every version of gallery from git depends on google_fonts ^1.0.0 which depends on path_provider ^1.4.0, every version of gallery from git requires path_provider ^1.4.0.
And because path_provider >=1.2.2 <1.6.4 depends on platform ^2.0.0, every version of gallery from git requires platform ^2.0.0 or path_provider ^1.6.4.
And because path_provider >=1.6.4 depends on path_provider_platform_interface ^1.0.1 which depends on platform ^2.0.0, every version of gallery from git requires platform ^2.0.0.
So, because flutter_update_packages depends on both platform 3.0.0-nullsafety.1 and gallery from git, version solving failed.
Running "flutter pub upgrade" in flutter_update_packages.mTtFaI...             
pub upgrade failed (1; So, because flutter_update_packages depends on both platform 3.0.0-nullsafety.1 and gallery from git, version solving failed.)
```

We should not re-publish platform as a non-breaking version constraint, since the update to null-safety required a breaking change in the FakePlatform class.

**Comment by goderbauer** [comment]
The dependency was added in https://github.com/flutter/flutter/pull/57576, so cc @pennzht, @clocksmith @yjbanov 

Can the gallery just be updated to depend on the new version of platform? Or would that require migrating all of the gallery to nullsaftey?

**Comment by goderbauer** [comment]
> Can the gallery just be updated to depend on the new version of platform? Or would that require migrating all of the gallery to nullsaftey?

To answer my own question: The gallery doesn't directly depend on platform, it depends on platform via other dependencies.

**Comment by jonahwilliams** [comment]
We would only need to release a new path_provider version which supports 2 - 4, then a new fonts, then a new gallery
