### ISSUE TITLE
[google_sign_in] serverClientId returns invalid token signature 

### ISSUE THREAD

**Issue by PJosue100** [flutter/flutter#63440]
How to implement the serverClientId in the GoogleSignIn object?

I want to be able to authenticate with a backend server, the process in android with Java is:

GoogleSignInOptions gso = new GoogleSignInOptions.Builder (GoogleSignInOptions.DEFAULT_SIGN_IN)
         .requestIdToken (getString (R.string.server_client_id))
         .requestEmail ()
         .build ();

This process is denoted by the following link: https://developers.google.com/identity/sign-in/android/backend-auth

**Comment by TahaTesser** [comment]
Hi @PJosue100 
You can define it like this
```
GoogleSignIn _googleSignIn = GoogleSignIn(scopes: <String>[
  'email',
  'https://www.googleapis.com/auth/contacts.readonly',
], clientId: "your client id ");

```

Please try code sample

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(scopes: <String>[
  'email',
  'https://www.googleapis.com/auth/contacts.readonly',
], clientId: "your client id ");

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn().then((value) {
        value.authentication.then((value) {});
      });
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(iSignedIn ? userName : 'empty user name'),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }
}

``` 

</details> 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by PJosue100** [comment]
Hi  @TahaTesser 

I tried the code you sent but got a problem with the returned token. Since when verifying the token the signature appears invalid. Test the same data in an application made in java with the same package name and sha1 version debug (use the same google-services.json file) and the returned token if it has the verified signature.

Both tokens show the same data; except for the signature.

The problem comes when I try to verify the token using Google API Client Library for java
[https://developers.google.com/identity/sign-in/android/backend-auth] (url), since using the token from the application made in java a successful result is obtained. While the result from flutter does not pass the verification in the verify (idTokenString) method; of the GoogleIdTokenVerifier class.

**Comment by PJosue100** [comment]
Update in case someone has the same problem, the return of the token is correct, the problem was that when printing the token in the console, it has a very large length and is not completely displayed in the console.
