### ISSUE TITLE
await picker.getVideo(source: ImageSource.gallery);

### ISSUE THREAD

**Issue by shaohui93** [flutter/flutter#63450]
var result = await picker.getVideo(source: ImageSource.gallery);
    print("${result.path}");
I use the above code to select videos  But why is the last address JPG  like this  ‘’cache/image_picker1718163224.jpg‘’

but  source: ImageSource.gallery  change to   source: ImageSource.camera     Everything's OK

**Comment by darshankawar** [comment]
Hi @shaohui93,
There's similar open issue describing your case, [52419](https://github.com/flutter/flutter/issues/52419).
Please follow-up there for updates.
Closing this as duplicate.
