### ISSUE TITLE
Tab Bar view behavior is not working when use the onHorizontalDragUpdate as a child

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [flutter/flutter#63459]
## Steps to Reproduce

1. Run the below code snippet
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ChartApp(),
    );
  }
}

class ChartApp extends StatefulWidget{

  _ChartAPP createState() => _ChartAPP();
}

class _ChartAPP extends State<ChartApp>{

bool disableTabBehavior;

Widget build(BuildContext context){
  return DefaultTabController(length: 2, child: Scaffold(
   appBar: AppBar(
     title: const Text('Sample'),
     bottom: const TabBar(tabs: <Widget>[
       Tab(child: Text('Tab1'),),
       Tab(child: Text('Tab2'),),
     ]),
   ),
   body: TabBarView(children: <Widget>[
      Container(color: Colors.red,
      child: Stack(children: <Widget>[
        Listener(
          child: GestureDetector(
            onHorizontalDragUpdate: (DragUpdateDetails details){
              _dragUpdate(details);
            },
          ),
        ),
      ],),),
      Container(color: Colors.green),
   ]),
  ));
}
}
void _dragUpdate(DragUpdateDetails details){}
```
2. Here is the output 
![issue](https://user-images.githubusercontent.com/61863686/89864198-29896100-dbc9-11ea-8f3b-11628677db64.gif)
 
3. Reproduce step,
 
- Run an application then swipe from right to left in the first tab it is not moved to the next tab.
- Move to Tab 2 by click then swipe right to left then it goes to Tab 1.
- I can't able to move from Tab 1 to Tab 2 by swipe because I have included an `onHorizontalDragUpdate` gesture as a child in `TabBarView`.
- I want to disable the `onHorizontalDragUpdate` when the `disableTabBehavior` is false.

**Expected results:** 

- Want to move from Tab 1 to Tab 2, even using the `onHorizontalDragUpdate` as a child.

**Actual results:** 

- It is not moving from Tab 1 to Tab 2 while swipe from left to right.

<details>
  <summary>Logs</summary>

```
```

```
```

```
PS D:\Dart\tab_bar_view> flutter doctor -v
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.20.0 at C:\src\flutter
    • Framework revision 916c3ac648 (10 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Admin-user\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Redmi Note 6 Pro (mobile) • 53a1093e   • android-arm64  • Android 9 (API 28)
    • Web Server (web)          • web-server • web-javascript • Flutter Tools
    • Chrome (web)              • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by vaibhavjain30699** [comment]
In you code, the GestureDetector in the container is overriding the drag behaviour of the TabBar.
You can use a TabController to achieve the effect you want.

**Comment by darshankawar** [comment]
Hi @Yuvaraj-Gajaraj,
When we need to move to tab 1 to tab 2 or vice-versa, we are using swipe gesture by default. In your code, since you wrapped `onHorizontalDragUpdate` with GestureDetector, it's going to override the swipe gesture.
Can you try @vaibhavjain30699's solution and see if it works for you?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by jja08111** [comment]
I think [this](https://stackoverflow.com/questions/43869027/gesturedetector-within-tabbarview-nested-scrolling) solution will solve the issue.
