### ISSUE TITLE
Questions about  "ScrollController.jumpTo"

### ISSUE THREAD

**Issue by bridfish** [flutter/flutter#63451]
Through listview, I write a component of the ”marquee“ effect. By calling the jumpTo () method of scrollcontroller regularly, the position is changed dynamically to realize the effect of ”marquee“. However, in the test, it is found that the effect will become more and more stuck after a period of time. The frame value decreases slowly from 60. Can't jumpTo () method of scrollcontroller  be called frequently?

code：

  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      startTimer();
    });
  }

  void startTimer() {
    _smarqueeTimer = Timer.periodic(Duration(microseconds: 16), (timer) {
      final distance = _scrollController.offset ?? 0;
      _scrollController.jumpTo(
          distance + (1 / SmarqueeSpeed.NORMAL_SPEED) * widget.speedRate);
    });
  }

**Comment by darshankawar** [comment]
Related to [31637](https://github.com/flutter/flutter/issues/31637)

**Comment by darshankawar** [comment]
Hi @bridfish,
There's similar open issue describing slowness around ScrollController.jumpTo() using listview, [52207](https://github.com/flutter/flutter/issues/52207).
I'd suggest you follow-up there and in [31637](https://github.com/flutter/flutter/issues/31637) for updates on this issue.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
