### ISSUE TITLE
Why line break,just chinese character

### ISSUE THREAD

**Issue by leetomlee123** [flutter/flutter#63464]
![Screenshot_20200811-161212](https://user-images.githubusercontent.com/19498940/89874059-da343800-dbaa-11ea-8e7c-7e2da134cedc.jpg)

**Comment by TahaTesser** [comment]
Hi @leetomlee123 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

**Comment by leetomlee123** [comment]
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.19041.388], locale zh-CN)
    • Flutter version 1.20.0 at D:\flutter\flutter
    • Framework revision 840c9205b3 (6 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\asdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\asdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\lxv1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

**Comment by TahaTesser** [comment]
Hi @leetomlee123 
To better address the issue, can you please provide and a complete reproducible minimal code sample with included Chinese text 
Thank you
