### ISSUE TITLE
Flutter Web with selectable text everywhere

### ISSUE THREAD

**Issue by stefanodecillis** [flutter/flutter#63478]
Hello,

my suggestion is very simple: make text selectable for the web version, at least let the developers choose.

At the moment Flutter web seems very good (even if it's not stable) and I would like to start its use in a small web environment (production). 
I didn't find any feature requests here (sorry if this results as a duplicated) and there are few questions on stackoverflow where the work-around is the **SelectableText** Widget. The last one it's no so feasible since it works with contexts. 

Thank you in advance for reading the suggestion and hope this can be done. Probably it's a good feature to have before Flutter Web will be stable and sure can help many people developing with it.

**Comment by TahaTesser** [comment]
Hi @stefanodecillis 
Are you proposing any widget which contains to have selectable text on web?

**Comment by stefanodecillis** [comment]
I would like to not have a widget to choose. I mean, in web development, any widget should have selectable text whenever it's displayed on page. 
It would be great to have an attribute or a widget (such as materialApp widget) where this is possible

**Comment by yjbanov** [comment]
You can disable text selection on the Web: https://stackoverflow.com/questions/3779534/how-do-i-disable-text-selection-with-css-or-javascript.

The difference is that Flutter makes text not selectable by default. For consistency with Flutter on all other platforms we'd like to keep the current default.

**Comment by rknell** [comment]
@yjbanov I agree it should be the default, however I agree with @stefanodecillis that it would be great to have an option to make it selectable everywhere - or at least be able to chuck an inherited widget somewhere in the tree to make all sub widgets text selectable. 

I have a table that users are consistently trying to copy and am being tasked with fixing that right now
