### ISSUE TITLE
bug - circle image outside of bounds in web

### ISSUE THREAD

**Issue by bar4488** [flutter/flutter#63473]
## Steps to Reproduce
1. Run `flutter create bug`.
2. Change the build method as follows:
```dart
 @override
  Widget build(BuildContext context) {
    var url =
        "https://images.unsplash.com/photo-1502759683299-cdcd6974244f?auto=format&fit=crop&w=440&h=220&q=60";
    return Center(
      child: SizedBox(
        width: 80,
        height: 80,
        child: FittedBox(
          child: SizedBox(
            width: 40,
            height: 40,
            child: ClipOval(
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: Colors.red,
                  image: DecorationImage(
                    image: NetworkImage(url),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
```
3. Run the application in any web environment.

**Expected results:** 
The decoration image should be rendered inside the circle, as shown when running on a mobile phone:
![image](https://user-images.githubusercontent.com/36762719/89890741-85111a00-dbdc-11ea-8332-a199436b557d.png)

**Actual results:** 
The image is rendered outside of the bounding circle:
![image](https://user-images.githubusercontent.com/36762719/89890385-ef758a80-dbdb-11ea-9b75-1bd0038270b1.png)

I was able to reproduce the bug in several different computers.

If there is any research to do or any help required, I would be more than glad to contribute my time for this issue.

**Comment by darshankawar** [comment]
The rendering seem to be off in web, while it's proper in mobile.  Tested in beta `1.20.0`.

![63473](https://user-images.githubusercontent.com/67046386/89893464-0a54f880-dbf6-11ea-9f2a-be0e24470cff.png)

![Screen Shot 2020-08-11 at 5 10 56 PM](https://user-images.githubusercontent.com/67046386/89893481-0fb24300-dbf6-11ea-8d07-7df2041cbd5c.png)

**Comment by yjbanov** [comment]
This should be fixed by https://github.com/flutter/engine/pull/20310. I just checked on a local build and I'm not seeing this issue.
