### ISSUE TITLE
Flutter beta channel version number stuck at 1.20.0

### ISSUE THREAD

**Issue by markusaksli-nc** [flutter/flutter#63485]
Looks like the update to the latest stable has somehow caused any beta channel or any switch to the beta channel to get the version number stuck at `1.20.0` (which is not even beta, it's the previous stable).

### Steps

1. Download any latest channel except beta
2. `flutter channel beta`
3. `flutter upgrade`

### Logs
<details>
 <summary>Expected</summary>

```
C:\Users\marku>flutter --version
Flutter 1.20.0-7.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

C:\Users\marku>flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0-7.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```
</details>
<details>
 <summary>Actual</summary>

```
C:\Users\marku>flutter --version
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

C:\Users\marku>flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```
</details>
<details>
 <summary>Changing from a fresh download of current stable to beta</summary>

```
C:\Users\marku>flutter --version
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (5 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

C:\Users\marku>flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:  * [new branch]          1/20           -> origin/1/20
git:    f25bd9c55..5a6dfa35c  dev            -> origin/dev
git:  * [new branch]          flutter-1.21-candidate.7 -> origin/flutter-1.21-candidate.7
git:  * [new branch]          flutter-1.21-candidate.8 -> origin/flutter-1.21-candidate.8
git:  * [new branch]          flutter-1.21-candidate.9 -> origin/flutter-1.21-candidate.9
git:    848cb83b8..2c1b95b9e  master         -> origin/master
git:  * [new tag]             1.21.0-7.0.pre -> 1.21.0-7.0.pre
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
git: Switched to a new branch 'beta'
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

C:\Users\marku>flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine d6ee1499c27a156a797d9f1539ffb7892855c1d0...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Flutter is already up to date on channel beta
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

C:\Users\marku>flutter --version
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)

C:\Users\marku>flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (10 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```
</details>

It's important to note that the commit ref `916c3ac648` is correct (the ref for latest beta `1.20.0-7.4.pre` is `916c3ac`), all that's wrong here is the displayed version number. This means functionality should not be affected. 

This will still cause a lot of confusion since users aren't going to know that the ref is correct without checking on [flutter.dev](https://flutter.dev/docs/development/tools/sdk/releases). I had this affect all of my machines and already saw this in a couple of `flutter doctor` logs when triaging issues.

A workaround is to just download the latest beta from [flutter.dev](https://flutter.dev/docs/development/tools/sdk/releases). Also this probably has something to do with current beta  `1.20.0-7.4.pre` being behind current stable `1.20.1`.

**Comment by TahaTesser** [comment]
I was stuck at the same `1.20.0` version, `flutter upgrade --force` didn't help, it said it was up-to update
I have deleted existing setup -> `git clone -b  beta https://github.com/flutter/flutter.git` , results in `beta 1.20.0-7.4.pre`  when ran `flutter doctor -v` on MacOS

**Comment by kf6gpe** [comment]
cc @christopherfujino

**Comment by christopherfujino** [comment]
Thanks for reporting this. I had just noticed this last week, when I filed https://github.com/flutter/flutter/issues/63159, so I am closing this as a duplicate. Please follow there for discussion and updates.

**Comment by christopherfujino** [comment]
In case you're wondering, downloading the pre-built archive from the website "fixes" this because it's version of the git repo doesn't have the newer tags. If you do a `git fetch`, it will then "update" the reported version.
