### ISSUE TITLE
FileSystemException: Cannot open file, path = 'C:\Users\hp\AppData\Local\Temp\flutter_tool.7c451adf-dbda-11ea-884e-c4651690b32e\app.dill' (OS Error: Access is denied.  , errno = 5)

### ISSUE THREAD

**Issue by chaitanya642000** [flutter/flutter#63484]
I was runnig my flutter app on my device from cmd , but suddenly these error poped up. I didn't face these issue initially. I search it on internet and I found that it might be due permission issues, so I took full ownership over my fluuter installation folder. I also restarted my PC but it was of no use. Here is the screen shot of error and flutter doctor command.
![flutter_doctor](https://user-images.githubusercontent.com/48641297/89907599-7fcac400-dc0a-11ea-9104-ccdb5eee54be.png)

![flutter_issue](https://user-images.githubusercontent.com/48641297/89907290-1d71c380-dc0a-11ea-90e7-2441138af3f5.png)

**Comment by TahaTesser** [comment]
Hi @chaitanya642000 
Can you upgrade to latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persist,  Can you please provide your `flutter doctor -v` your `flutter run --verbose`
Thank you

**Comment by chaitanya642000** [comment]
> Hi @chaitanya642000
> Can you upgrade to latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persist, Can you please provide your `flutter doctor -v` your `flutter run --verbose`
> Please refrain from posting screenshots if not needed, text is better
> Thank you

**Comment by chaitanya642000** [comment]
I got these error "git: fatal: Unable to create 'D:/development/flutter/.git/index.lock': Permission denied
Switching channels failed with error code 128."

**Comment by TahaTesser** [comment]
Hi @chaitanya642000 
Please request logs from https://github.com/flutter/flutter/issues/63484#issuecomment-672017300 and if you're issues with `index.lock`, delete and try upgrade again

**Comment by chaitanya642000** [comment]
> Hi @chaitanya642000
> Can you upgrade to latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persist, Can you please provide your `flutter doctor -v` your `flutter run --verbose`
> Please refrain from posting screenshots if not needed, text is better
> Thank you

**Comment by chaitanya642000** [comment]
I got these error

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > java.io.IOException: Access is denied

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         2.0s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by chaitanya642000** [comment]
Where is index.lock file?

**Comment by TahaTesser** [comment]
Hi @TahaTesser 
It's in your path " 'D:/development/flutter/.git/index.lock':`
Please try deleting it and run the commands again

Can you upgrade to latest `stable` and try again
`flutter channel `stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by Arnab28122000** [comment]
This issue keeps poping, but sometimes it doesn't mainly during the assemble debug this issue pops up. After restarting the PC sometimes the issue resolves and sometimes it doesn't. This issue is an everyday problem for me. I am using the flutter stable version on vs code with windows 10 OS. It would be great if anyone can help me permanently solve this issue, I have deleted and reinstalled everything still the issue remains the same.
