### ISSUE TITLE
Flutter gradle task running forever

### ISSUE THREAD

**Issue by Songeziwe** [flutter/flutter#63499]
Hello everyone I just installed flutter on my new laptop. I'm having a very big problem which i can't solve. Gradle task is running too long when trying to debug the flutter app on my physical device. I gave it an opportunity to run as long as it can. 
But the following output is what I got at the end:

Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.5.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.5.0/builder-3.5.0.jar'.
         > Premature end of Content-Length delimited message body (expected: 8174407; received: 6553552

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 21s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Songeziwe** [comment]
I pointed Android studio to the android sdk and flutter

**Comment by Songeziwe** [comment]
Please help guys if you have any solution to this problem.

**Comment by markusaksli-nc** [comment]
Hi @Songeziwe 
Can you please provide your `flutter doctor -v`, and your `flutter run --verbose` logs. Does this happen if you create a default project using `flutter create bug` and attempt to run it?
Thank you

**Comment by Abhishek01039** [comment]
First of all, try to invalide caches and restart AS (Android Studio).
If it won't work head on to build.gradle(Project: yourappname) and change gradle line in dependencies to the newest version:
```dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
       }
```

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
