### ISSUE TITLE
For some reason, the variable 'questionBank' isn't being recognized by dart. It is being recognized when I enclose it in a function and call it. 

### ISSUE THREAD

**Issue by kt-aakash** [flutter/flutter#63496]
![Screenshot from 2020-08-11 20-36-16](https://user-images.githubusercontent.com/19407796/89915392-ebfdf580-dc13-11ea-829f-67cd9833d7bb.png)

## Steps to Reproduce
It probably can't be reproduced because I observed that its working fine on my friend's machine.

<details>

  <summary>
Logs(**Dart analysis**)
error: The class '_QuizPageState' doesn't have a default constructor. (new_with_undefined_constructor_default at [quizzler] lib/main.dart:25)

error: Named parameters must be enclosed in curly braces ('{' and '}'). (named_parameter_outside_group at [quizzler] lib/main.dart:36)

error: Default values aren't allowed in function typed parameters. (default_value_in_function_typed_parameter at [quizzler] lib/main.dart:36)

error: The name of a constructor must match the name of the enclosing class. (invalid_constructor_name at [quizzler] lib/main.dart:36)

error: Default values aren't allowed in function typed parameters. (default_value_in_function_typed_parameter at [quizzler] lib/main.dart:36)

error: Named parameters must be enclosed in curly braces ('{' and '}'). (named_parameter_outside_group at [quizzler] lib/main.dart:36)

info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [quizzler] lib/main.dart:36)
</summary>

```
```

```
```

```
```

</details>

**Comment by vaibhavjain30699** [comment]
You can't modify the **questionBank** variable because it is immutable. To modify it, you need to do it in either **init** method, build function or any of your custom functions.

**Comment by kt-aakash** [comment]
Oh, thanks for correcting me. I ran it (with out widgets) on dartpad and assumed it would work on Flutter too. Big Mistake on my part. Thanks again!
