### ISSUE TITLE
<elided use case> causes OOM

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#63516]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=57501.

@iskakaushik is assigned to the upstream bug; so assigning here.

**Comment by kf6gpe** [comment]
Presently being investigated by a member of the Fuchsia team no action needed from Flutter at present.

**Comment by zanderso** [comment]
There's not yet enough information on the upstream issue(s) for @iskakaushik to take a look at this one, so I will remove his assignment.

**Comment by chinmaygarde** [comment]
Triage: This needs more investigation on the application side. The update on the internal bug two days ago suggests this is unlikely to be a Flutter issue.

**Comment by kf6gpe** [comment]
Critical issue triage update: upstream team looking at logs for additional information about the issue. Still nothing actionable for the Flutter team.

**Comment by kf6gpe** [comment]
Upstream issue closed as "working as intended". Closing this issue.
