### ISSUE TITLE
TableRow.toString() logic is inverted for non-null populated lists

### ISSUE THREAD

**Issue by InspiredIdealist** [flutter/flutter#6351]
Simple inverted logic with a list null check.

[Offending Code in the master branch](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/table.dart#L55)

## Steps to Reproduce

1. Create a TableRow instance
2. set the children on the TableRow with a list which contains at least one object
3. call TableRow.toString()
4. String will output "child list is null" because the logic is the opposite of what it should be.

**Comment by eseidelGoogle** [comment]
@Hixie

**Comment by abarth** [comment]
Thanks for the report!

**Comment by abarth** [comment]
Looks like a trivial fix.  :P
