### ISSUE TITLE
Proposal for cleaning up button APIs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#63510]
We currently have the following button classes: ButtonStyleButton, ContainedButton, ElevatedButton, FlatButton, MaterialButton, OutlineButton, OutlinedButton, RaisedButton, RawMaterialButton, and TextButton.

My understanding is that the best practice is to use OutlinedButton, ElevatedButton, and TextButton, and use ButtonStyleButton for custom buttons.

I propose that we deprecate OutlineButton, RaisedButton, ContainedButton, FlatButton, MaterialButton, and RawMaterialButton, each with a pointer to the relevant class, and that we update the documentation for OutlinedButton, ElevatedButton, TextButton, and ButtonStyleButton to all include sample code, and that we remove the detailed documentation from the deprecated classes to clearly indicate which are the preferred classes.

**Comment by Piinks** [comment]
I think this is a mid-migration issue. IIRC @hansmuller is in the process of introducing the new buttons, and eventually deprecating the old. Currently, the customer tests we run for the framework will fail if they are using a deprecated API, so the old API can't be deprecated until everyone is migrated. It creates this kinda confusing situation with new and old API co-existing during a migration phase.
That's at least how I understand it, I've run into this while trying to deprecate some API for new features too.

**Comment by Janaka-Steph** [comment]
At least some information and pointers in the doc would be nice imo.

**Comment by HansMuller** [comment]
@Janaka-Steph The API doc for the existing button classes were updated a few days ago: https://github.com/flutter/flutter/pull/64472.  They refer to a new migration guide  [flutter.dev/go/material-button-migration-guide]( https://flutter.dev/go/material-button-migration-guide).

**Comment by Janaka-Steph** [comment]
Oh that's great, thank you! I hope the official doc https://flutter.dev/docs/development/ui/widgets/material will also get updated soon. I just learned the "hard way", reading Github issues and figuring out which widgets to use, how to do theming the right way, etc.

**Comment by duzenko** [comment]
Sorry, is there somewhere a rationale as for why we needed all these types of buttons before and why we don't need them now any more?

**Comment by HansMuller** [comment]
The "Buttons" section of [flutter.dev/go/material-theme-system-updates](flutter.dev/go/material-theme-system-updates) provides the rationale for the "new button universe", [flutter.dev/go/material-button-migration-guide](flutter.dev/go/material-button-migration-guide) was the proposal for the API changes, and [flutter.dev/docs/release/breaking-changes/buttons](https://flutter.dev/docs/release/breaking-changes/buttons) is the final version of the migration guide.
