### ISSUE TITLE
DropdownButton doesn't change value and can't be used twice

### ISSUE THREAD

**Issue by InspiredIdealist** [flutter/flutter#6352]
**After running the app...**
1. Tap on the dropdown button, the menu should appear
2. Select an item from the dropdown (that isn't the selected element)
3. *(Issue 1)* The menu disappears without the selection changing
4. *(Issue 2)* Tap on the dropdown button again...
5. [The error shown below occurs](#error)

*Use the sample code below*

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'DropdownButton Bug',
      theme: new ThemeData(
        primarySwatch: Colors.red,
      ),
      home: new DropdownButtonBug(),
    ),
  );
}

class DropdownButtonBug extends StatefulWidget {
  DropdownButtonBug({Key key}) : super(key: key);

  @override
  _DropdownButtonBugState createState() => new _DropdownButtonBugState();
}

class _DropdownButtonBugState extends State<DropdownButtonBug> {

  final List<String> _items = ['One', 'Two', 'Three', 'Four'].toList();

  String _selection;

  @override
  Widget build(BuildContext context) {
    _selection = _items.first;

    final dropdownMenuOptions = _items
      .map((String item) =>
        new DropdownMenuItem<String>(value: item, child: new Text(item))
      )
      .toList();

    return new Scaffold(
      body: new DropdownButton<String>(
        value: _selection,
        items: dropdownMenuOptions,
        onChanged: (s) {
          setState(() {
            if(s != null)
              _selection = s;
          });
        }
      )
    );
  }
}

```

#### Error
>
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown while routing a pointer event:
I/flutter : 'package:flutter/src/material/drop_down.dart': Failed assertion: line 499 pos 12: '_currentRoute ==
I/flutter : null' is not true.
I/flutter : 
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      _DropdownButtonState._handleTap (package:flutter/src/material/drop_down.dart:499:12)
I/flutter : #3      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:14)
I/flutter : #4      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter : #5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:198:9)
I/flutter : #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter : #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter : #8      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:122:19)
I/flutter : #9      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
I/flutter : #10     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
I/flutter : #11     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
I/flutter : #12     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
I/flutter : #13     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:59)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : 
I/flutter : Event:
I/flutter :   PointerUpEvent(Point(76.6, 345.2))
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
>

## Logs

Output of `flutter analyze`: 
> Analyzing lib/main.dart...
> No analyzer warnings! (ran in 5.9s)

## Flutter Doctor

> [✓] Flutter (on Linux, channel master)
>      • Flutter at /usr/local/flutter
>      • Framework revision 9cab64a72c (2 days ago), 2016-10-14 21:57:28
>      • Engine revision d999f6c123
>      • Tools Dart version 1.20.0-dev.10.2
>  
>  [✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
>      • Android SDK at /usr/local/android/Sdk
>      • Platform android-24, build-tools 24.0.2
>      • OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
>  
>  [✓] Atom - a lightweight development environment for Flutter
>      • flutter plugin version 0.2.6
>      • dartlang plugin version 0.6.40
>  
>  [✓] Connected devices
>      • Android SDK built for x86 • emulator-5554 • android-x86 (emulator)

## Testing System Information
* CPU: i5-2400
* RAM: 24G
* OS: Ubuntu 16.04
* IDE: Atom w/ Flutter plugin

## Android Emulator Info:
* Device: Nexus 6 (1440 x 2560, 560dpi)
* Target: Android 7 (API 24)
* CPU: Intel Atom (x86)
* Memory Options: (RAM: 3072, VM Heap: 32)
* Internal Storage: 200MB
* Emulation Options: Use Host GPU

**Comment by abarth** [comment]
Interesting.  Thanks for the report.  I'll take a look.

**Comment by abarth** [comment]
The reason the selection doesn't change is that you assign `_selection` on every build.  Instead, you probably want to move the `_selection = _items.first;` line to an override of `initState`

**Comment by abarth** [comment]
There's still a bug in there.  Investigating.

**Comment by abarth** [comment]
I have a fix.  Writing test.

**Comment by abarth** [comment]
After https://github.com/flutter/flutter/pull/6353 lands, this example should work if you move the `_selection` assignment to `initState`.  Also, there's no need to test for null in `onChanged`.  The button will never call that callback with null.

```dart
class _DropdownButtonBugState extends State<DropdownButtonBug> {

  final List<String> _items = ['One', 'Two', 'Three', 'Four'].toList();

  String _selection;

  @override
  void initState() {
    _selection = _items.first;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final dropdownMenuOptions = _items
      .map((String item) =>
        new DropdownMenuItem<String>(value: item, child: new Text(item))
      )
      .toList();

    return new Scaffold(
      body: new DropdownButton<String>(
        value: _selection,
        items: dropdownMenuOptions,
        onChanged: (s) {
          setState(() {
            _selection = s;
          });
        }
      )
    );
  }
}
```

**Comment by InspiredIdealist** [comment]
Thank you for the quick turn around, and tips @abarth!

**Comment by abarth** [comment]
My pleasure!

**Comment by aslamzee** [comment]
Is there a way to validate the dropdown button

**Comment by thenexus00** [comment]
onChanged you can just build in an if condition or run a function before or along side the state change.

**Comment by Allan-Nava** [comment]
I use the same code but doesn't change the UI value of dropdown when I tap another value

**Comment by zoechi** [comment]
@Allan-Nava I'd suggest you ask on StackOverflow with a minimal reproduction.

**Comment by Ankit0080** [comment]
> After #6353 lands, this example should work if you move the `_selection` assignment to `initState`. Also, there's no need to test for null in `onChanged`. The button will never call that callback with null.
> 
> ```dart
> class _DropdownButtonBugState extends State<DropdownButtonBug> {
> 
>   final List<String> _items = ['One', 'Two', 'Three', 'Four'].toList();
> 
>   String _selection;
> 
>   @override
>   void initState() {
>     _selection = _items.first;
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     final dropdownMenuOptions = _items
>       .map((String item) =>
>         new DropdownMenuItem<String>(value: item, child: new Text(item))
>       )
>       .toList();
> 
>     return new Scaffold(
>       body: new DropdownButton<String>(
>         value: _selection,
>         items: dropdownMenuOptions,
>         onChanged: (s) {
>           setState(() {
>             _selection = s;
>           });
>         }
>       )
>     );
>   }
> }
> ```

Applying the same code but it is not working

child: DropdownButton<String>(
                                        style: const TextStyle(
                                            color: Colors.black),
                                        hint: Container(
                                          margin:
                                              EdgeInsets.fromLTRB(10, 0, 0, 0),
                                          //and here
                                          child: Text(
                                            "Select State",
                                            style: TextStyle(
                                                color: AppColors.greyColor,
                                                fontFamily: 'NotoSansRegular',
                                                fontSize:
                                                    AppFontSize.font_small),
                                            textAlign: TextAlign.start,
                                          ),
                                        ),
                                        icon: Padding(
                                          padding: const EdgeInsets.fromLTRB(
                                              0, 0, 10, 0),
                                          child: Icon(Icons.arrow_drop_down),
                                        ),
                                        iconSize: 20,
                                        isExpanded: true,
                                        underline: SizedBox(),
                                        items: statusList
                                            .map<DropdownMenuItem<String>>(
                                                (String status) {
                                          return DropdownMenuItem<String>(
                                            value: status,
                                            child: Container(
                                              margin: EdgeInsets.fromLTRB(
                                                  10, 0, 0, 0),
                                              child: Text(status,
                                                  style: TextStyle(
                                                      color: Colors.black,
                                                      fontFamily:
                                                          'NotoSansRegular',
                                                      fontSize: AppFontSize
                                                          .font_small)),
                                            ),
                                          );
                                        }).toList(),
                                        value: selectedPropertyStatus,
                                        onChanged: (String newValue) {
                                          Helper.showToast(newValue);
                                          setState(() {
                                            selectedPropertyStatus = newValue;
                                          });
                                        },
                                      ),
