### ISSUE TITLE
i build chat app using firebase and its run without any error , but i was try to run my project on another laptop and i have this error now :Failed assertion: boolean expression must not be null . whats the problem plz? 

### ISSUE THREAD

**Issue by wesamodeh** [flutter/flutter#63529]
[

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
