### ISSUE TITLE
TextEditingController face with bug in the beta branch

### ISSUE THREAD

**Issue by sobhan15** [flutter/flutter#63521]
hi
i have problem,when i defind TextEditingController inside the provider ,then i call controller from provider ,
the cursor of text field is reversed,please help me ,Thanks

**Comment by darshankawar** [comment]
Hi @sobhan15,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Also, when you say `provider`, are you referring to this [plugin](https://pub.dev/packages/provider) ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
