### ISSUE TITLE
[e2e] Move `watchPerformance` to e2e after `FrameTimingSummarizer` goes into stable release

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#63537]
This issue is to monitor the duplicate of `watchPerformance` in various host-independent performance tests, which will be moved to `e2e` in flutter/plugins after `FrameTimingSummarizer` goes into stable version. 

We can't do it now because `e2e` is tested against Flutter stable SDK.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will wait until `FrameTimingSummarizer` goes into stable version and assign myself again.

**Comment by CareF** [comment]
`FrameTimingSummarizer` is in flutter 1.22 now. However I can't find what versions of the framework and the engine `e2e` is tested against.

**Comment by liyuqian** [comment]
I think the `integration_test` is going to use whatever Flutter version that's currently installed (`flutter --version`)? CC @dnfield for confirmation.

**Comment by dnfield** [comment]
Correct.

**Comment by CareF** [comment]
The issue is not about in the user side what version of flutter it's using, but for the CI system what versions of flutter is test against. See flutter/plugins#2914 for previously why we moved `watchPerformance` out of `e2e`.

**Comment by liyuqian** [comment]
I think our CI should always use the tip-of-tree master Flutter version. That's why we had a broken test described in  flutter/plugins#2914: the master Flutter introduces  a breaking API that breaks the e2e tests in the CI. I remembered that we moved `watchPerformance` out of e2e originally because we don't want to break e2e users who were still using stable branch Flutter?

**Comment by CareF** [comment]
I'm pretty sure back then one of the CI test is testing against the stable version of the engine, and we revert this together with moving `FrameTimingSummarizer` out of the engine for the reason.

**Comment by dnfield** [comment]
Plugins ci tests against stable and master
