### ISSUE TITLE
Flutter use image.asset  flicker

### ISSUE THREAD

**Issue by mlf2020** [flutter/flutter#63547]
When I click on a container to switch pictures(Image widget), the first time I switch pictures, I have a flicker problem. Is this flutter's bug ? I use Stack and Offstage widget solved my problem

**Comment by Abhishek01039** [comment]
can you provide `flutter doctor -v` and `flutter run -v` and simple reproduction code?

**Comment by mlf2020** [comment]
Container(
              constraints: BoxConstraints(maxWidth: 52),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[

                  //  the code below may lead to a flicker problem when call setState func
                  currentIndex == index ? Image.asset('images/base_info_nor.png',
              package: StringUtils.packageName) :Image.asset('images/base_info_sel.png',
              package: StringUtils.packageName),
                //  the code above may lead to a flicker problem when call setState func

                  Padding(padding: EdgeInsets.only(top: 4)),
                  Text(
                    item.text,
                    overflow: TextOverflow.ellipsis,
                    maxLines: 2,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        color: currentIndex == index
                            ? hui.colorNeutral2
                            : hui.colorNeutral4,
                        fontSize: hui.infoSizeSupport),
                  )
                ],
              ),
            ),

**Comment by markusaksli-nc** [comment]
Hi @mlf2020 
What we need is a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates this issue. You should be able to simply paste into a new project `main.dart` and (after adding a few random image assets) run it. Please also provide your `flutter doctor -v` logs.
Thank you

**Comment by itssidhere** [comment]
Related #63218

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
