### ISSUE TITLE
Regression: Switching between bottom navigation tab bars shows grey square

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#63558]
https://github.com/flutter/flutter/pull/62951 (`e8c942104bb4b414b67e303a54b00e8fc45c67a6`) caused a regression on our app. Now, when changing tabs in our home screen, a giant grey square appears for <1s, causing a really weird behaviour. In Crashlytics, these 2 logs are appearing related to that error:

## Code sample

```dart
import 'package:cuberto_bottom_bar/cuberto_bottom_bar.dart';
import 'package:flutter/material.dart';

void main() => runApp(HomeScreen());

class HomeScreen extends StatefulWidget {
  @override
  HomeScreenState createState() => HomeScreenState();
}

class HomeScreenState extends State<HomeScreen> {
  int index;

  @override
  void initState() {
    super.initState();
    index = 0;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: const Placeholder(),
        bottomNavigationBar: CubertoBottomBar(
          selectedTab: index,
          onTabChangedListener: (int _index, _, __) => setState(() => index = _index),
          tabs: <TabData>[
            TabData(
              iconData: Icons.bug_report,
              title: 'Test',
            ),
            TabData(
              iconData: Icons.bug_report_outlined,
              title: 'Test 2',
            ),
          ],
        ),
      ),
    );
  }
}
```

You'll need to add this line to `pubspec.yaml`:

```yaml
  cuberto_bottom_bar: ^1.1.1+2
```

## Logs
![image](https://user-images.githubusercontent.com/2807712/90001420-b566c000-dc91-11ea-8c65-9fb890d814d2.png)

![image](https://user-images.githubusercontent.com/2807712/90001582-e3e49b00-dc91-11ea-98dd-e89ba9fda3b1.png)

If possible, revert or provide a workaround until it gets fixed.

cc/ @a14n

**Comment by darshankawar** [comment]
Hi @Zazo032,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Zazo032** [comment]
```
[✓] Flutter (Channel unknown, 1.21.0-8.0.pre.146, on Microsoft Windows [VersiÃ³n 10.0.19041.423], locale es-ES)
    • Flutter version 1.21.0-8.0.pre.146 at C:\src\flutter
    • Framework revision e8c942104b (20 hours ago), 2020-08-11 16:16:03 +0200
    • Engine revision 235e389d29
    • Dart version 2.10.0 (build 2.10.0-9.0.dev)
```

Can't provide a code sample right now as it's private.

**Comment by Zazo032** [comment]
Note that this only hapens on Profile and Release mode, everything works fine on Debug mode.

**Comment by darshankawar** [comment]
Hi @Zazo032,
I tried demo tab bar code [sample](https://flutter.dev/docs/cookbook/design/tabs) on latest Master `1.21.0-8.0.pre.176` in profile mode, but didn't see the grey square as you mentioned.

[62951_176.mp4.zip](https://github.com/flutter/flutter/files/5062114/62951_176.mp4.zip)

Not sure if I missed anything, but is there any other way to replicate it ?

**Comment by Zazo032** [comment]
Minimal code sample:

```dart
import 'package:cuberto_bottom_bar/cuberto_bottom_bar.dart';
import 'package:flutter/material.dart';

void main() => runApp(HomeScreen());

class HomeScreen extends StatefulWidget {
  @override
  HomeScreenState createState() => HomeScreenState();
}

class HomeScreenState extends State<HomeScreen> {
  int index;

  @override
  void initState() {
    super.initState();
    index = 0;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: const Placeholder(),
        bottomNavigationBar: CubertoBottomBar(
          selectedTab: index,
          onTabChangedListener: (int _index, _, __) => setState(() => index = _index),
          tabs: <TabData>[
            TabData(
              iconData: Icons.bug_report,
              title: 'Test',
            ),
            TabData(
              iconData: Icons.bug_report_outlined,
              title: 'Test 2',
            ),
          ],
        ),
      ),
    );
  }
}
```

You'll need to add this line to `pubspec.yaml`:

```yaml
  cuberto_bottom_bar: ^1.1.1+2
```

**Comment by darshankawar** [comment]
Thanks @Zazo032 for the code sample.
Since `cuberto_bottom_bar` is a 3rd party plugin, could this be an issue at their end ?
I tried with material widget `BottomNavigationBar` and don't see such behavior.

[62951.mp4.zip](https://github.com/flutter/flutter/files/5062220/62951.mp4.zip)

**Comment by Zazo032** [comment]
I don't think so, since this was a breaking change for that plugin introduced in the framework side. As per the logs, it seems that there's an issue on transforming `BoxBorder`s, may be reproducible in some other way by lerping 2 `BoxBorder`s (without depending on a plugin).

**Comment by a14n** [comment]
Basically the problem is cause by the `is` check and mixed migrated file to nullsafety:

```dart
//------------- a.dart
// @dart = 2.8
import 'b.dart';
void main() => print(f(null));  // true or false ???

//------------- b.dart
bool f(dynamic o) => o is String?;
```

I expected `true` as result but it is currently `false`. 

I'm waiting for a response from the language team to know if this is a VM bug or not.

Until a fix land you should pin your flutter version to the commit before e8c942104bb4b414b67e303a54b00e8fc45c67a6

**Comment by a14n** [comment]
@Zazo032 could you test on the head of master branch?

**Comment by goderbauer** [comment]
@a14n I assigned this to you since you seemed to be looking at it.

Regarding your last comment: Did anything land on master that may have fixed this?

**Comment by Zazo032** [comment]
This is still happening on latest master:
```
Flutter 1.21.0-10.0.pre.70 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0629030a05 (3 hours ago) • 2020-08-13 00:01:03 -0400
Engine • revision 7571e7c380
Tools • Dart 2.10.0 (build 2.10.0-11.0.dev)
```

**Comment by leafpetersen** [comment]
I have not been able to reproduce the small example from @a14n of unexpected `is` check behavior, and specifically it does not reproduce on `2.10.0-11.0.dev` .

**Comment by a14n** [comment]
According to the error screenshot in this issue's description it's thrown by https://github.com/flutter/flutter/blob/c67eafa87d2de441a195a8aa46c92eac37ce4616/packages/flutter/lib/src/painting/box_border.dart#L156-L165

and the message mentions `null` and `null` as `a` and `b`. With those values the code should have been handled by https://github.com/flutter/flutter/blob/c67eafa87d2de441a195a8aa46c92eac37ce4616/packages/flutter/lib/src/painting/box_border.dart#L108-L109

So I quite confused (and I don't have time for now to investigate futher)

**Comment by goderbauer** [comment]
I am unable to reproduce the problem on the latest master with the code given in https://github.com/flutter/flutter/issues/63558#issuecomment-672798514.

```
[✓] Flutter (Channel unknown, 1.21.0-10.0.pre.97, on Mac OS X 10.14.6 18G6020, locale en-US)
    • Flutter version 1.21.0-10.0.pre.97 at /Users/goderbauer/dev/flutter
    • Framework revision 4f775a26d1 (17 minutes ago), 2020-08-14 10:11:29 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
```

There are no exceptions in the console and the transition looks as expected.

Do you have a screenshot that shows the visual glitch caused by this?

**Comment by Zazo032** [comment]
This is still happening on latest master:
```
Flutter 1.21.0-10.0.pre.101 • channel master • https://github.com/flutter/flutter.git
Framework • revision f512e86c2a (70 minutes ago) • 2020-08-14 12:03:18 -0700
Engine • revision 7571e7c380
Tools • Dart 2.10.0 (build 2.10.0-11.0.dev)
```
You have to run with `--profile` or `--release`, debug builds seem to work.

<details>

### Video
[Tab bug.zip](https://github.com/flutter/flutter/files/5077004/Tab.bug.zip)

### Logs
```
I/flutter (11415): ══╡  ╞══════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11415): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (11415): Another exception was thrown: Instance of 'ErrorSummary'
```

</details>

**Comment by goderbauer** [comment]
I can reproduce this in release mode, but not in debug mode. In release mode the first `if` condition in this code here doesn't trigger and we go straight to the throw at the end:

https://github.com/flutter/flutter/blob/8d4aef0d51c7691bf7bf191338260c08621498bb/packages/flutter/lib/src/painting/box_border.dart#L106-L166

I have no idea why the first if doesn't trigger, what makes it even more strange is that when I delete the other if conditions in the method, suddenly the first if does trigger...

**Comment by goderbauer** [comment]
I've filled https://github.com/flutter/flutter/issues/63819 with my findings so far.

**Comment by Zazo032** [comment]
Fixed by https://github.com/flutter/flutter/pull/64024
