### ISSUE TITLE
Persistent roadmap for supporting 3D 

### ISSUE THREAD

**Issue by softmarshmallow** [flutter/flutter#63562]
as written in under documentation, flutter team is has plans for 3D support.
https://flutter.dev/docs/resources/faq

> Today we don’t support for 3D via OpenGL ES or similar. We have long-term plans to expose an optimized 3D API, but right now we’re focused on 2D.

I'm going to make production level 3D drawing widget for creating next generation applications, such like [this](https://dribbble.com/shots/13952652-Weather-App-Visual-Concept) example.

If flutter team provides which api you guys will be using it will be helpful to design architecture, so after flutter team supports 3d officially, my work can still be valid and not be trashed.

Thanks!

**Comment by darshankawar** [comment]
Hi @softmarshmallow ,
There's similar open issue describing your case, [58145](https://github.com/flutter/flutter/issues/58145).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
