### ISSUE TITLE
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext != null': is not true.

### ISSUE THREAD

**Issue by rifthyahmed** [flutter/flutter#63563]
<details>
  <summary>Logs</summary>
[+31601 ms] I/flutter (32582): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════[   +6 ms] I/flutter (32582): The following assertion was thrown during a platform message callback:
[  +80 ms] I/flutter (32582): 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext !=
[  +62 ms] I/flutter (32582): null': is not true.
[   +1 ms] I/flutter (32582): 
[   +1 ms] I/flutter (32582): Either the assertion indicates an error in the framework itself, or we should provide substantially  
[   +2 ms] I/flutter (32582): more information in this error message to help you determine and fix the underlying cause.
[  +27 ms] I/flutter (32582): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (32582):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +1 ms] I/flutter (32582): 
[   +1 ms] I/flutter (32582): When the exception was thrown, this was the stack:
[  +30 ms] I/flutter (32582): #2      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:329:15)
[   +1 ms] I/flutter (32582): #3      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
[   +1 ms] I/flutter (32582): #4      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1623:43)     
[  +47 ms] I/flutter (32582): #5      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:598:68)
[   +1 ms] I/flutter (32582): #6      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:76:49)
[  +27 ms] I/flutter (32582): #7      _DefaultBinaryMessenger.handlePlatformMessage
(package:flutter/src/services/binding.dart:267:33)
[   +1 ms] I/flutter (32582): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
[   +1 ms] I/flutter (32582): #12     _invoke3 (dart:ui/hooks.dart:281:10)
[   +1 ms] I/flutter (32582): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
[   +1 ms] I/flutter (32582): (elided 5 frames from class _AssertionError and dart:async)
[   +1 ms] I/flutter (32582): ════════════════════════════════════════════════════════════════════════════════════════════════════ 
[  +25 ms] I/flutter (32582): Another exception was thrown: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line   
329 pos 15: 'primaryContext != null': is not true.
[ +123 ms] I/chatty  (32582): uid=10156(agency.hypesocial.endako_mobile) 1.ui identical 7 lines
[   +1 ms] I/flutter (32582): Another exception was thrown: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line   
329 pos 15: 'primaryContext != null': is not true.
```


</details>

**Comment by darshankawar** [comment]
Hi @rifthyahmed,
When opening an issue, please provide some or all informatlon such as `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by rifthyahmed** [comment]
I had a issue with `curved_navigation_bar: ^0.3.3`. I downgraded its version.
