### ISSUE TITLE
flutter.dev web page  loading problem overlaping text

### ISSUE THREAD

**Issue by Zeeshan-progs** [flutter/flutter#63561]
![Screenshot (582)](https://user-images.githubusercontent.com/67018643/90007256-0b4e5e80-dcb8-11ea-8fe9-547fe38b47bb.png)

**Comment by darshankawar** [comment]
Hi @Zeeshan-progs,
I tried same web page and able to see without any issues.

![Screen Shot 2020-08-12 at 4 55 00 PM](https://user-images.githubusercontent.com/67046386/90009917-93cefe00-dcbc-11ea-8327-0491494a2bbb.png)

Please try to close the browser / refresh the page and see if it works for you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
