### ISSUE TITLE
Support dynamic thread merging on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#63585]
The raster queue should execute on the platform thread only when a platform view is rendered on the screen. This is required to be able to call synchronous/non-thread safe APIs from the rasterizer.

Related: https://github.com/flutter/flutter/issues/59930

**Comment by chinmaygarde** [comment]
Per the linked issues, the August milestone seems appropriate.

**Comment by blasten** [comment]
https://github.com/flutter/engine/pull/20864 will reland the PR.
