### ISSUE TITLE
Add Platform view documentation for iOS

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#63588]
The [wiki](https://github.com/flutter/flutter/wiki/Hybrid-Composition#ios) should have an iOS section with code snippets targeted to plugin authors and app developers that don't write plugins.

cc @cyanglaz

**Comment by cyanglaz** [comment]
Related https://github.com/flutter/flutter/issues/56736

**Comment by blasten** [comment]
Taking this item since it's needed for the website.
