### ISSUE TITLE
Async methods don't get called after one throws an exception

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#6358]
## Steps to Reproduce

Run the following app (I am using an iOS simulator, have not tested elsewhere):

```
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new FlutterDemo(),
    ),
  );
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  _FlutterDemoState createState() => new _FlutterDemoState();
}

class _FlutterDemoState extends State<FlutterDemo> {
  Future printAppDir() async {
    print("click");
    Directory appDir = await PathProvider.getApplicationDocumentsDirectory();
    print(appDir?.path ?? "null appDir");
  }

  Future breakAsyncMethods() async {
    throw new Exception("async methods will now be broken");
  }

  Future debugAsyncMethods() async {
    print("debug async - start");
    await new Future(() {
      print("debug async - computation");
    });
    print("debug async - past future");
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter Demo'),
        ),
        body: new Column(children: [
          new RaisedButton(
              child: new Text("debug async methods"),
              onPressed: debugAsyncMethods),
          new RaisedButton(
              child: new Text("simple print"),
              onPressed: () {print("simple print");}),
          new RaisedButton(
              child: new Text("print app dir"), onPressed: printAppDir),
          new RaisedButton(
              child: new Text("break async"), onPressed: breakAsyncMethods)
        ]));
  }
}

```

1. Press the top 3 buttons and observe their output in the logs.
2. Press the "break async" button
3. Press the top 3 buttons again. Observe that only the "simple print" button whose onPressed is not async has it's print statement executed.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 3203757958 (52 minutes ago), 2016-10-17 10:30:13
    • Engine revision d999f6c123
    • Tools Dart version 1.20.1

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.5
    • dartlang plugin version 0.6.39

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • iPhone 5s • 16BCCC3C-2F9C-401F-B2BF-97F1E3D2929A • ios (simulator)

```

**Comment by eseidelGoogle** [comment]
@Hixie would know.

**Comment by drewwarren** [comment]
@abarth was looking at this last week. I thought it was resolved but I can still reproduce.

**Comment by abarth** [comment]
@drewwarren I "resolve" the issue you were hitting by getting rid the exception.  It's still on my plate to figure out why exceptions prevent further futures from resolving.

/cc @a-siva

**Comment by jason-simmons** [comment]
This is related to Tonic's implementation of DartMicrotaskQueue::RunMicrotasks.

After the uncaught exception DartStickyError::MaybeSet sets the sticky error.  The next time RunMicrotasks is called, it noticed the sticky error and does not invoke the _startMicrotaskLoop task queued by schedule_microtask.dart.

As a result, nobody is draining the queue of async callbacks managed by schedule_microtask.dart.  Any future calls to _scheduleAsyncCallback just append callbacks to the queue.

@johnmccutchan how should Tonic/Flutter manage the sticky error?

Is it safe to keep running microtasks after an error is set?  Or is the embedder supposed to clear the error at some point?

**Comment by johnmccutchan** [comment]
When the standalone embedder has an isolate with an unhandled exception it sets the sticky error for the isolate and terminates the isolate.

The flutter embedder does not terminate the isolate but does stop processing new messages (see `dart_message_handler.cc`) and stops processing the asynchronous microtask queue.

**Comment by abarth** [comment]
> The flutter embedder does not terminate the isolate but does stop processing new messages (see dart_message_handler.cc) and stops processing the asynchronous microtask queue.

Our general approach in Flutter is to continue after unhandled exceptions.  Would anything break terribly if we switched this to continuing to process messages?

**Comment by johnmccutchan** [comment]
@abarth As discussed offline. We should be able to remove this restriction after I figure out what is causing reassemble to hang.

**Comment by jason-simmons** [comment]
This has been fixed in Tonic
