### ISSUE TITLE
for the web client the `onTap:` `GestureDetector()` ignores mouse clicks between lines of text in a compound widget

### ISSUE THREAD

**Issue by jro-cw** [flutter/flutter#63586]
Android and iOS are fine, but on the webclient, `onLongPress:` and `onTap:` do not fire when the mouse click is between two text containers

`onLongPress:` and `onTap:` do fire when he mouse click is directly over the displayed text of one of the text containers of a compound Widget.

![image](https://user-images.githubusercontent.com/53796271/90048266-800da280-dc90-11ea-9926-337b3f078189.png)

_(?? too long ??) here is the `GestureDetector()`_

    return GestureDetector(
      key: util.makey(this, "gd", uniq),
      child: Container(
        key: util.makey(this, "slide", uniq),
        child: Container(
          key: util.makey(this, "cont", uniq),
          color: data.id == this._selectedCID ? Colors.grey[200] : null,
          padding: EdgeInsets.fromLTRB(5.0, 10.0, 15.0, 10.0),
          margin: EdgeInsets.only(left: 5.0, right: 5.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              icon,
              Flexible(
                key: util.makey(this, "flexible", uniq),
                child: Container(
                  child: Column(
                    children: <Widget>[
                      Row(children: <Widget>[
                        Expanded(
                          child: _conversationName(context, data, read),
                        ),
                        Column(
                          children: <Widget>[
                            Text(
                              Chat.formatDate(context, data.lastMessage?.updated ?? data.created),
                              style: DefaultTextStyle.of(context).style.apply(
                                    color: Colors.grey[700],
                                    fontSizeFactor: .5,
                                    fontWeightDelta: read ? 1 : 3,
                                  ),
                            ),
                            Text(data.messageCount == null ? "<>" : data.messageCount.toString(),
                                style: DefaultTextStyle.of(context).style.apply(fontSizeFactor: .5))
                          ],
                        ),
                      ]),
                      Container(
                        child: SmartText(
                          selectable: false,
                          useCache: false,
                          text: data?.lastMessage?.text ?? util.xl(context, "no.messages"),
                          style: DefaultTextStyle.of(context)
                              .style
                              .apply(
                                color: Colors.grey[700],
                                fontSizeFactor: .8,
                                fontWeightDelta: read ? 1 : 4,
                              )
                              .copyWith(fontStyle: read ? FontStyle.normal : FontStyle.italic),
                          overflow: TextOverflow.ellipsis,
                          maxLines: 2,
                        ),
                        alignment: Alignment.centerLeft,
                        margin: EdgeInsets.only(top: 3.0, bottom: 0.0),
                      ),
                    ],
                  ),
                  margin: EdgeInsets.only(left: 15.0),
                ),
              ),
            ],
          ),

          //shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10.0)),
        ),
      ),
      onTap: () => _doSelect(context, data),
      onLongPress: () => _doPopup(context, data),
      onTapDown: _storePosition,
    );

**Comment by markusaksli-nc** [comment]
Hi @jro-cw
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by jro-cw** [comment]
\dev\flutter\bin\flutter doctor -v
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.20.0 at C:\dev\flutter
    • Framework revision 916c3ac648 (12 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jrobertson.CALLWARE\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

**Comment by jro-cw** [comment]
... still refining sample code / still to be posted ...

**Comment by jro-cw** [comment]
Well, this has started working in our latest builds of our complex flutter app, ... which would explain the inability for me to implement a minimal test.  I am assuming that there has been a recent fix in the 'beta' channel.
