### ISSUE TITLE
NetworkImage is not working on Mac desktop app

### ISSUE THREAD

**Issue by AGUIR-I** [flutter/flutter#63601]
Hello everyone, NetworkImage is working perfectly on mobile app (android/iOS) but it is not working on ****Mac** desktop app**. Is there any solution to this problem ? thanks in advance.

                  Container(
                      width: 100,
                      height: 100,
                      child: Image.network(
                        "https://codabee.com/wp-content/uploads/2019/05/flutter.png",
                      ),
                    )

**flutter doctor -v**

[✓] Flutter (Channel dev, 1.20.0, on Mac OS X 10.15.4 19E287, locale fr-FR)
    • Flutter version 1.20.0 at /Users/---/flutter
    • Framework revision 7736f3bc90 (5 weeks ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/----/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E287
    
• No issues found!

**Comment by stuartmorgan** [comment]
See https://flutter.dev/desktop#entitlements-and-the-app-sandbox for discussion of the entitlement necessary to access remote resources.

If you believe you have already followed those instructions, please provide a link to a full testcase that reproduces the issue.

**Comment by AGUIR-I** [comment]
It's working !  the problem is solved by adding **com.apple.security.network.client** in entitlements file. Thank you very much !
