### ISSUE TITLE
Listener is being marked as deprecated, but there is no sufficient replacement

### ISSUE THREAD

**Issue by kwiesmueller** [flutter/flutter#63607]
Hey there,
i'm trying to implement some sort of hovering behavior on mobile.
So there are squares and when the finger slides over the screen and enters a square, it will change color.
On exit it will revert.

I searched a while and found the Listener widget, but when i use it, it's being marked as deprecated and i should use MouseRegion. MouseRegion sounds like it is mouse cursor focused and not touch.
This seems like a deprecation without a matching replacement and i can not find any explanation for it.

https://api.flutter.dev/flutter/widgets/Listener-class.html

**Comment by timsneath** [comment]
Check out https://flutter.dev/gestures, which covers `GestureDetector`. This should support your needs.

**Comment by kwiesmueller** [comment]
Not really as it does not support any onHover or enter events like the Listener does.
Or is that explicitly not intended to support?
