### ISSUE TITLE
Engine doesn't build in Xcode 12

### ISSUE THREAD

**Issue by xster** [flutter/flutter#63613]
Didn't look too deep yet. We'll have to change this line

https://github.com/flutter/buildroot/blob/97f6f007f88e572f148b9800e4d7deeccfd6766b/build/mac/find_sdk.py#L60

Probably have to update more search paths for issues like 

`In file included from ../../third_party/boringssl/src/crypto/x509/t_x509.c:57:
../../third_party/libcxx/include/ctype.h:38:15: fatal error: 'ctype.h' file not found
#include_next <ctype.h>`

**Comment by xster** [comment]
oops, the second issue was just local. The Python stdout affects the functionality.

**Comment by jmagman** [comment]
Are builders Xcode versions being updated?  It doesn't matter for macOS, but for iOS the builder needs to stay on the lowest version of Xcode (really clang) supported by the tool for bitcode.  If we bump it, we need to coordinate messaging so people have time to upgrade their systems.  https://github.com/flutter/flutter/issues/49787#issuecomment-583705509
Fortunately I think the builders are different per branch now?  Would need to remember to bump each branch's clang version as the code is promoted to each branch.

**Comment by xster** [comment]
No, I'm not moving anything here. I'm just making it possible for Xcode 12 to build an engine locally along with Xcode 11.
