### ISSUE TITLE
CanvasKit: some text disappears in Flutter Gallery

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#63616]
This is reproducible in:

* flutter/flutter: 441d7f3fb8cac85c51927aeca030a6ff53c83ed1
* flutter/engine: 4fb3ea81a943b51d8b93a4a537d30ef8c9e37e92
* flutter/gallery: 9cf3b20f797af39eeda9cf59f7f549fadad9ba56
* Chrome 84 on Linux or Mac.

The "Settings" menu loses some of its text when it's fully expanded (you can briefly see the text in the middle of the transition though):

![missing-text](https://user-images.githubusercontent.com/211513/90076448-8ada2e80-dcb4-11ea-84a1-48bb3ca1578f.png)

It should look like this:

![text-present](https://user-images.githubusercontent.com/211513/90076473-a2b1b280-dcb4-11ea-9244-f589af230849.png)

**Comment by yjbanov** [comment]
From offline conversation, @hterkelsen has a fix in the works.

**Comment by aseef17** [comment]
> From offline conversation, @hterkelsen has a fix in the works.

Might be related to #55686
