### ISSUE TITLE
Build scheduling delays impacting ability to release

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#63618]
pre submits are currently backed up over 2.5 hours.  for a hotfix that includes an engine update, this is pushing the time to generate a release to O(days), purely based on the ability to execute builds.  

cc @christopherfujino @tvolkert @keyonghan @godofredoc

**Comment by christopherfujino** [comment]
so Godofredo already raised the priority of release builds (https://github.com/flutter/infra/pull/164/files). If we fixed this https://github.com/flutter/flutter/issues/53371 then the pre-submit builds would also run on the release builders and thus have higher priority.

**Comment by pcsosinski** [comment]
https://github.com/flutter/flutter/issues/63618

**Comment by godofredoc** [comment]
We don't prioritize traffic based on branch. The queue time is being affected by the ongoing migration of the SDK to LUCI.

https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=58053

**Comment by christopherfujino** [comment]
> We don't prioritize traffic based on branch.

On prod builds we do, right? https://github.com/flutter/infra/blob/master/config/engine_config.star#L171

**Comment by godofredoc** [comment]
> > We don't prioritize traffic based on branch.
> 
> On prod builds we do, right? https://github.com/flutter/infra/blob/master/config/engine_config.star#L171

yes that is correct for prod we prioritize those tasks.

**Comment by godofredoc** [comment]
Moving to P1 as the new capacity is ready and build/tests will start to catch up.

**Comment by pcsosinski** [comment]
thanks for adding the capacity.   it wasn't clear from the PSA that this capacity strain was coming.  was it expected?

**Comment by godofredoc** [comment]
It was not expected actually the problem was that we set priority of sdk builders to 30 as all the other builders but we didn't modify it in the engine drones. That caused engine builds to take priority over the sdk ones.

I just reverted that change:

https://flutter-review.googlesource.com/c/recipes/+/5582

**Comment by digiter** [comment]
Triage: this is fixed.
