### ISSUE TITLE
Oops; flutter has exited unexpectedly: "FileSystemException

### ISSUE THREAD

**Issue by Celestine4cpp** [flutter/flutter#63628]
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to 'C:\Users\Ledesba\Desktop\first_flutter_app\first_flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Users\Ledesba\Desktop\first_flutter_app\first_flutter_app\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+copy+file+to+%27C%3A%5CUsers%5CLedesba%5CDesktop%5Cfirst_flutter_app%5Cfirst_flutter_app%5Candroid%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27%2C+path+%3D+%27C%3A%5Cflutter%5Cpackages%5Cflutter_tools%5Ctemplates%5Capp%5Candroid.tmpl%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJ9Ss

exit code 1

**Comment by Abhishek01039** [comment]
https://github.com/flutter/flutter/issues/15711

**Comment by darshankawar** [comment]
Hi @Celestine4cpp,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates and questions.
Closing this as duplicate.
