### ISSUE TITLE
[web]: TextSpans interact with wrong TapGestureRecognizers 

### ISSUE THREAD

**Issue by monkeyswarm** [flutter/flutter#63638]
Flutter: Channel master, 1.20.0-3.0.pre.11, on Mac OS X 10.15.6. running on Chrome 84.0.4147.125

When multiple TextSpans, are in a parent TextSpan, shown within a constrained container, TapGestureRecognizers do not respond correctly.

See code below. This displays three spans of text in a fixed-width container.

Repro: tap on each of the three spans
Expected: see log 'span 0 tapped', 'span 1 tapped', 'span 2 tapped'.
Actual: see log 'span 0 tapped' for all spans.

If the TapGestureRecognizer is not set for the first span, then _none_ of the other TapGestureRecognizers fire.

If the container width constraint is removed, then it works ok, until the browser window is made small enough to enforce multiple lines, in which case the bug reappears.

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'TextSpan',
        home: Center(
            child: Container(
                width: 300,
                color: Color(0xFFDDDDDD),
                child: RichText(
                    text: TextSpan(children: [
                  TextSpan(
                      text: '[Lorem ipsum dolor sit amet, ]',
                      recognizer: TapGestureRecognizer()
                        ..onTap = () => print('span 0 tapped')
                  ),
                  TextSpan(
                      text: '[consectetur adipiscing elit, ]',
                      recognizer: TapGestureRecognizer()
                        ..onTap = () => print('span 1 tapped')),
                  TextSpan(
                      text: '[sed do eiusmod tempor incididunt]',
                      recognizer: TapGestureRecognizer()
                        ..onTap = () => print('span 2 tapped')),
                ])))));
  }
}

```

**Comment by Liuzhiyang94** [comment]
Meat the same problem.   The text show below the container in the simple case.
```
Container(
            color: Colors.red,
            child: Text(
              "test content"
    )
```
![image](https://user-images.githubusercontent.com/18064048/90111581-6dbf6180-dd81-11ea-8ba5-537006dc6bdb.png)


Here is my doctor -v
```

Flutter (Channel master, 1.21.0-10.0.pre.70, on Mac OS X 10.15.6 19G73,
    locale zh-Hans-CN)
    • Flutter version 1.21.0-10.0.pre.70 
    • Framework revision 0629030a05 (4 hours ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

```

**Comment by darshankawar** [comment]
Issue is replicable on latest beta version as well. Tapping on different spans only registers first tap.

<details>
<summary>log</summary>

```
span 0 tapped
span 0 tapped
span 0 tapped
span 0 tapped
span 0 tapped
span 0 tapped
span 0 tapped

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0 at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 916c3ac648 (12 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (3 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 1 category.

```

</details>

**Comment by mdebbar** [comment]
This is because we don't do granular measurements inside rich text correctly yet.

**Comment by aliyazdi75** [comment]
Another wrong behavior menthioned in this https://github.com/flutter/flutter/issues/63977.

**Comment by mariamhas** [comment]
adjusting priority based on next blocking issue

**Comment by YeungKC** [comment]
I can't reproduce this behavior on master, I don't know if I'm doing it the wrong way or if it's been fixed, could you please re-test?

cc @monkeyswarm 



[✓] Flutter (Channel Fix_Mouse_Scroll_miscontrol_of_ScrollPosition, 1.22.0-10.0.pre.122, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans)
    • Flutter version 1.22.0-10.0.pre.122 at /Users/YeungKC/FlutterProjects/flutter
    • Framework revision e5d524ad8f (52 分钟前), 2020-10-30 05:26:37 +0800
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/YeungKC/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/YeungKC/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode 12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/YeungKC/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android Studio.app/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Users/YeungKC/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.7846.90

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (6 available)
    • macOS (desktop)           • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)          • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 86.0.4240.111

**Comment by monkeyswarm** [comment]
The problem as shown in my demo code is indeed solved.
I still seem to have a related problem in my actual codebase, but I will open a separate issue once I can isolate that into an example, so feel free to close this issue. Thanks.

**Comment by YeungKC** [comment]
I see, caused by the line change, which is probably why @mdebbar said it was.
