### ISSUE TITLE
Use `old_gen_heap_size` to encourage the Dart VM to more aggressively collect garbage on mobile platforms

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#63631]
Since https://dart-review.googlesource.com/c/sdk/+/151635, this flag helps limit how much memory the VM will allocate in old space, and should help trigger collections more aggressively as we approach device limits.

On Android, this could be defaulted to `dalvik.vm.heapsize`, which is the size of a "largeHeap" app on Android. My only concern with this is that this value is likely _much_ lower than what we currently allow - i.e. I haven't seen it larger than 512mb, whereas I've definitely run apps without OOMing that use multiple gigabytes of RAM. 

On iOS, we should probably be safe with `[NSProcessInfo processInfo].physicalMemory / 2`.  Some devices seem to let you use more (e.g. use up to 75% of memory before killing you), but some are as low as half.

- [x] Android
- [x] iOS
- [ ] Fuchsia (TBD)

/cc @iskakaushik @gw280 for input on Fuchsia

/cc @rmacnak-google FYI

/cc @zanderso @liyuqian

**Comment by dnfield** [comment]
So I don't forget - we do already support this argument in the shell, here: https://github.com/flutter/engine/blob/95b2ebfaf4e7de3a06c04d5af7107d4c0b0dcef1/common/settings.h#L217 - added by @gaaclarke a ways back now.

We should still respect any user supplied value if the application decides to override this to avoid breaking anyone using it.

/cc @chinmaygarde as well who probably has good thoughts on this.

**Comment by dnfield** [comment]
This will help with https://github.com/flutter/flutter/issues/56482

**Comment by zanderso** [comment]
w.r.t. Fuchsia, it looks like you need a special handle to grab `ZX_INFO_KMEM_STATS` [(docs)](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/docs/reference/syscalls/object_get_info.md#zx_info_kmem_stats), which has a field reporting total system physical memory, but maybe there's a system service to query over FIDL.

Maybe @arbreng can point in the right direction.

**Comment by zanderso** [comment]
Regarding testing, you might add a debug-only flag that hardcodes this to a known appropriately small value, then add an integration test in the framework repo that tries to allocate more than that.

**Comment by chinmaygarde** [comment]
Is the size limitation enforced per isolate or across all isolates in the VM? I know there has been some confusion about this in the past. We'd want the latter.

To test this, I'd prepare a runtime test that allocates more than a very small amount specified in the specific shell instance created with a super small limit. As @zanderso suggests, an integration test will be good too but the runtime test will be closer to the engine and prevent engine releases that regress this. One small gotcha with the runtime test, please make sure the VM is no running before the test is run. All runtime tests shut down the VM in fixture teardown but it'd be good to assert this explicitly in the test.

**Comment by dnfield** [comment]
My understanding is that allocating more will be allowed, but will trigger more GCs.  @rmacnak-google - is that accurate?

Also, I believe this is per isolate.  @rmacnak-google or @mkustermann can confirm.

**Comment by arbreng** [comment]
@dnfield  @zanderso 
re: fuchsia
ZX_INFO_KMEM_STATS requires the root resource, so that would create a big ole' security hole if flutter made use of that hande.  The root resource gives you near total-control over a fuchsia system, so we can't use that path.  :(

Some code in experiences.git is using https://source.corp.google.com/fuchsia/fuchsia-mirror/sdk/fidl/fuchsia.memory/monitor.fidl?q=monitor.fidl, and that looks like exactly what you want.

It looks like https://source.corp.google.com/fuchsia/fuchsia-mirror/sdk/core.api?q=core.api&sq=package:fuchsia is not marking it for inclusion into the SDK package though, so you might have to do that first.

**Comment by mkustermann** [comment]
> Is the size limitation enforced per isolate or across all isolates in the VM?
> I know there has been some confusion about this in the past. We'd want the latter.
> ...
> Also, I believe this is per isolate. @rmacnak-google or @mkustermann can confirm.

The limits are per isolate group. Right now each `Isolate.spawn()` creates a new isolate group. So the limits currently apply per isolate.

We're working on making isolates more lightweight (see https://github.com/dart-lang/sdk/issues/36097). Once isolate groups are on by-default the limit will apply to the main isolate and all isolates spawned from there (though not the entire VM, e.g. the embedder might run multiple apps).

**Comment by dnfield** [comment]
iOS is done, Android is under review, Fuchsia still TBD.

Rolling out milestone for Android/Fuchsia.

**Comment by kf6gpe** [comment]
Since this has a milestone for this month, I'm giving this a P3. Downgrade as appropriate.

**Comment by dnfield** [comment]
For Android: I have a WIP patch I will finish up before EOM so that applications can adjust as needed. We have a less clear case about how much of a limit (if any) to put on Android vs iOS.

For Fuchsia: I think this is going to be a matter of just discussing this with @arbreng - I suspect he will have a better idea about what value to give this parameter.

For embedder API: it's already possible to pass this in, and some of our embedder based clients are using it.

**Comment by dnfield** [comment]
Android and iOS are done, assigning to @dreveman and @arbreng for Fuchsia side.

**Comment by minikin** [comment]
@dnfield Just wondering if you have a plan to implement this feature for Linux (Flutter Embedder API)?

**Comment by dnfield** [comment]
I got an email about a omment that appears to not be showing up here RE: linux/embedder.

Embedder API users can set this option themselves per application more easily.

**Comment by minikin** [comment]
@dnfield Thank you, Dan! It was a comment from me, but I found your comment above `For embedder API: it's already possible to pass this in, and some of our embedder-based clients are using it.`

I have a memory budget of about 180Mb. At a start, an app takes about 80 - 100 Mb, during operation, it's about 150 Mb,
just wondering if I can have any recommendations as to which value to set `old_gen_heap_size`?
```sh
...
 "--dart-define",
 "DART_VM_OPTIONS=--old_gen_heap_size=170"
```

**Comment by dnfield** [comment]
I'm going to close this as completed - I'm not sure if Fuchsia ever implemented it or not but a separate issue can be opened for that if needed.

**Comment by vikas-flutter** [comment]
@dnfield Please reply to @minikin's comment or provide an example on how to change the value of this option for different use cases. Also in which scenarios we should start using this option. Thanks.
