### ISSUE TITLE
‘Flutter build windows’ product cannot run on some computers

### ISSUE THREAD

**Issue by wb1992321** [flutter/flutter#63646]
The product generated by ‘flutter build windows’ is not an installation program, but an execution program and depends on the current directory environment. If you need to send it to others, you need to send the entire folder of Runner, and it will...

![image](https://user-images.githubusercontent.com/10239402/90117872-11ad0b00-dd8a-11ea-90df-bc181f98d738.png)

The directory structure is as follows (I sent out the Runner folder):

![image](https://user-images.githubusercontent.com/10239402/90118445-cfd09480-dd8a-11ea-8314-2331aa6d64c4.png)

![image](https://user-images.githubusercontent.com/10239402/90118374-ba5b6a80-dd8a-11ea-89fa-cfd99fc68d80.png)

Is it possible to generate installable program files?

**Comment by markusaksli-nc** [comment]
Hi @wb1992321 
Did I understand correctly that you cannot open the application when copying the `Release` folder to a different windows machine opening the flutter executable? Could you translate what this error says or copy the text here?
Thank you

**Comment by wb1992321** [comment]
> Hi @wb1992321
> Did I understand correctly that you cannot open the application when copying the `Release` folder to a different windows machine opening the flutter executable? Could you translate what this error says or copy the text here?
> Thank you

The product compiled by "flutter build windows" cannot be directly sent to the computer of other ordinary users, because his computer may lack components, so if possible, I hope to be able to compile a package that needs to be installed, and install the required program environment to On the computer. MacOS also encountered the same problem. The only app file cannot be generated for dmg files. Fortunately, the macOS environment is relatively uniform, and the lack of related components rarely occurs.

Note: From Google Translate

**Comment by markusaksli-nc** [comment]
I'm going to label this as a new feature request for a flutter windows installer build option. Not sure what this installer would do other than unpacking the contents of `Release`. Does a flutter windows app depend on anything that the installer could bundle? I was able to run the exe on all of my machines.

**Comment by stuartmorgan** [comment]
There are different kinds of installers, with different targets; one option isn't going to satisfy all use cases. I've filed https://github.com/flutter/flutter/issues/63672 to consider MSIX, however, which is an option that is worth considering as a built-in.

The error in the screenshot is due to not reading https://github.com/flutter/flutter/wiki/Desktop-shells#distributing. Since this is already documented (and to the extent that there's a feature request here, the issue above tracks it), closing.

> MacOS also encountered the same problem.

Everything you have described in this issue is entirely Windows-specific, and there is no comparable structure on macOS (which has application bundles as a core OS concept), so I have no idea what this is referring to. If you have issues with macOS, you'll need to file a specific bug with details.

**Comment by wb1992321** [comment]
> Everything you have described in this issue is entirely Windows-specific, and there is no comparable structure on macOS (which has application bundles as a core OS concept), so I have no idea what this is referring to. If you have issues with macOS, you'll need to file a specific bug with details



Of course, there will be no running problems on macOS. I just want to be able to output the installation package file in the'dmg' format instead of the executable file in the'app' format. Of course, this is not a problem, I just want to make it as perfect as possible . I have tried to replace the file on macOS with Dart but it failed. It should be a permission problem, but there is no pop-up permission request and any solution, so I did not continue to try.

**Comment by stuartmorgan** [comment]
> I just want to be able to output the installation package file in the'dmg' format instead of the executable file in the'app' format.

There are plenty of existing utilities/scripts that already exist for packing a macOS application in a disk image for those who want to distribute their app on a disk image. Any of them will work just as well with an app build with Flutter as with any other app. We have no plans to reinvent that wheel, or to pick one specific implementation (especially given that they have different features, aesthetic choices, etc.)

> I have tried to replace the file on macOS with Dart but it failed.

I have no idea what this means, but if it's about packaging in a disk image, it's out of scope.
