### ISSUE TITLE
flutter: webview runs fine when app installed via usb, but not when installed over google play

### ISSUE THREAD

**Issue by eshiett1995** [flutter/flutter#63640]
I am using flutters webview which is `webview_flutter: ^0.3.21` to display a webpage,  It works perfectly when I run the app locally, but when the app is published and downloaded from the Playstore the webview seems to not work as expected:

1. The buttons are not clickable
2. pages are not scrollable
3. UI on the screen is generally not intractable.

**Comment by markusaksli-nc** [comment]
Hi @eshiett1995 
Can you please provide your `flutter doctor -v` logs and `pubspec.yaml` and mention which device this happens with. Does the issue not reproduce locally with `flutter run --release`? Could you test if the issue reproduces with a basic `flutter create bug` project with `webview_flutter` dependency and this code in `main.dart`:

<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: WebView(
          initialUrl: "https://pub.dev/packages/webview_flutter/install",
        ),
      ),
    );
  }
}
```
</details>

Thank you

**Comment by eshiett1995** [comment]
@markusaksli-nc apologies for my late reply, it seems the webview still works, but one has to click it with two fingers. but when I try this on debug mood it works well with one finger.  I was unable to produce the issue with `flutter run --release` as it worked perfectly.

This is a snippet of my code 

`class _WebState extends State<Web> {
  WebViewController _controller;
  bool isLoading = true;
  OkraHandler okraHandler;

  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      WebView(
          initialUrl: "https://mobile.okra.ng",
          onPageFinished: (response) {
            setState(() {isLoading = false;});
            String jsonOptions = jsonEncode(widget.okraOptions.toJson());
            _controller.evaluateJavascript("openOkraWidget('$jsonOptions')");
          },
          javascriptMode: JavascriptMode.unrestricted,
          javascriptChannels: Set.from([
            JavascriptChannel(
                name: 'FlutterOnSuccess',
                onMessageReceived: (JavascriptMessage message) {
                  okraHandler =
                      new OkraHandler(true, true, false, message.message);
                }),
            JavascriptChannel(
                name: 'FlutterOnError',
                onMessageReceived: (JavascriptMessage message) {
                  okraHandler =
                      new OkraHandler(true, false, true, message.message);
                }),
            JavascriptChannel(
                name: 'FlutterOnClose',
                onMessageReceived: (JavascriptMessage message) {
                  Navigator.pop(context, okraHandler);
                })
          ]),
          onWebViewCreated: (webViewController) {
            _controller = webViewController;
          }),
      isLoading ? Center( child: CircularProgressIndicator(),)
          : Container(width: 0, height: 0,  color: Colors.transparent),
    ]);
  }
}`

**Comment by markusaksli-nc** [comment]
Could you specify which version of flutter you used to build the release build for Google Play Store and provide your `flutter doctor -v` if you still haven't upgraded?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
