### ISSUE TITLE
url launcher in second page

### ISSUE THREAD

**Issue by mojanimator** [flutter/flutter#63658]
when i navigate to second page in my app and run a playstore  link with urllauncher.  play store app opens but when i exit from  
 play store and return to my second page and press back to move to first page . it not work and prints dequeue failed and remain in same second page. but seems first page is running behind this page!
i tried pop with different calling navigator (global key and of(context)) but not work.

**Comment by darshankawar** [comment]
Hi @mojanimator,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by mojanimator** [comment]
nothing special in my app .
in first page:
Navigator.of(context).push(MaterialPageRoute(builder: (context) => AboutUs()));
 
 in second page just run 
 await launch('https://play.google.com/store/apps/developer?id=Varta+Studio');
and go to play store app and back to your app (in second page ).  then tap back button in your device to go to first page. that not work.

**Comment by mojanimator** [comment]
this happened on last update of flutter

**Comment by darshankawar** [comment]
Hi @mojanimator,
I tried to replicate the issue on latest Stable (1.20.2) but couldn't replicate it. I was able to navigate back properly.

[63658.mp4.zip](https://github.com/flutter/flutter/files/5072978/63658.mp4.zip)

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MaterialApp(
    home: PageStorageTest(),
  ));
}

class PageStorageTest extends StatefulWidget {
  @override
  _PageStorageTestState createState() => _PageStorageTestState();
}

class _PageStorageTestState extends State<PageStorageTest> {
  PageStorageKey key0 = PageStorageKey<String>('key0');
  PageStorageKey key1 = PageStorageKey<String>('key1');
  PageStorageKey key2 = PageStorageKey<String>('key2');
  bool flag = true;

  void _onPress() {
    setState(() {
      flag = !flag;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: _onPress,
            child: Text("+"),
          ),
          appBar: AppBar(
            title: Text('PageStorageKey bug app'),
          ),
          body: Center(
            child: RaisedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => AboutUs()),
                );
              },
              child: Text('Tap')
            )
          ),
        );
  }
}

class AboutUs extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const String toLaunch = 'https://play.google.com/store/apps/developer?id=Varta+Studio';
    return Scaffold(
      appBar: AppBar(

      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
           _launchURL(toLaunch);
          },
          child: Text('launch')
        )
      )
    );
  }

  Future<void> _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(
        'https://play.google.com/store/apps/developer?id=Varta+Studio',
        forceSafariVC: false,
        forceWebView: false,
      );
    } else {
      throw 'Could not launch $url';
    }
  }

}
```

</details>

Can you upgrade to latest stable and try above code to see it it works for you ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
