### ISSUE TITLE
Scrolling Problem in Flutter

### ISSUE THREAD

**Issue by asbn223** [flutter/flutter#63655]
Hello, 

While scrolling in the desktop app created by flutter, it showed 
'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 392 pos 12: '!_debugDuringDeviceUpdate': is not true.

I don't know what that meant.. Scrolling is working fine but it shows after i scroll.

**Comment by darshankawar** [comment]
Hi @asbn223,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by asbn223** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/45443718/90137839-e6301d80-dd95-11ea-8717-ffa7c601f22c.png)
![Screenshot_20](https://user-images.githubusercontent.com/45443718/90137847-e7614a80-dd95-11ea-8676-f909190aa65c.png)
Here is the status for flutter doctor -v

C:\Users\ASBN\StudioProjects\recipe_app>flutter doctor -v
[√] Flutter (Channel master, 1.21.0-9.0.pre, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-9.0.pre at C:\src\flutter
    • Framework revision 4aed976812 (5 days ago), 2020-08-07 23:30:56 -0700
    • Engine revision 1e50d87dc8
    • Dart version 2.10.0 (build 2.10.0-4.0.dev b9c5118c73)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\ASBN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 84.0.522.58

• No issues found!

**Comment by darshankawar** [comment]
Hi @asbn223,
Please post the code sample directly in the comment in proper code format, as opposed to the screenshot, because we won't be able to copy paste the code that you shared in screenshots.
Thanks.

**Comment by asbn223** [comment]
Hello @darshankawar, 
I have solved it by removing single child scroll view in first screenshot. Thank you for the help.

**Comment by ThinkDigitalSoftware** [comment]
> Hello @darshankawar,
> I have solved it by removing single child scroll view in first screenshot. Thank you for the help.

But this doesn't tell us where the issue was and why. I'm getting this too and I'm not using a scrollable

**Comment by asbn223** [comment]
The problem was i was using SingleChildScrollView and LayoutBuilders at same place. By removing the SingleChildScrollView, it was solved.
