### ISSUE TITLE
How to Add Print Feature button via bluetooth in my apps to my thermal printer?

### ISSUE THREAD

**Issue by ihsandroid1** [flutter/flutter#63650]
I'm just starting to learn darts and flutter and I love it :) but I was wondering **How to add Bluetooth print in my cashier app transactions (webview).**

_I use an epson printer for POS and cashier.

The paper width is about 58mm for thermal paper material._

Thank you very much :)

**Comment by Abhishek01039** [comment]
Hi @ihsandroid1 ,
This platform is not meant for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this.
for webView you can check https://pub.dev/packages/flutter_webview_plugin or https://pub.dev/packages/webview_flutter
Thanks

**Comment by ihsandroid1** [comment]
**okay thank you i wish i found what i really want :)**
