### ISSUE TITLE
Flutter Driver - how to test permissions dialog?

### ISSUE THREAD

**Issue by srockytfl** [flutter/flutter#63662]
Hi, I'm testing my app using flutter driver and it's working in most cases, but know I have a page that asks for GPS permission. To continue the workflow of my app, I need to accept the permission, how can I do that?
thank you
![Screenshot_1597323443](https://user-images.githubusercontent.com/69392984/90138718-cbd25180-dd4d-11ea-858f-d3f944147c78.png)

**Comment by darshankawar** [comment]
Hi @srockytfl,
Currently flutter driver can't interact with native elements. See [this](https://github.com/flutter/flutter/issues/34345) issue for more details.
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by srockytfl** [comment]
Thank you, this is really bad :-( 
Is there a way to run the test disabling this alerts? Like if the permission was already granted?
