### ISSUE TITLE
Create 1.20 forks for new sdk recipes

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#63670]
Release branches are failing with infra failures because the builders can not find the forked versions of the recipes for release branches.

\cc @christopherfujino @pcsosinski

**Comment by christopherfujino** [comment]
I'm guessing this was fixed by https://flutter-review.googlesource.com/c/recipes/+/5620.

Somewhat related, this new recipe is so simple, it seems like a perfect candidate to get moved into the actual repo. Then we wouldn't need to fork the recipe, it could just be a single step recipe to call the script.

**Comment by godofredoc** [comment]
I think we are already there, the recipe only prepares the environment and delegates the execution to the test runner from sdk repo. We may need more work on adhoc tests.

The property configs are already being moved to the repos.

**Comment by christopherfujino** [comment]
> I think we are already there, the recipe only prepares the environment and delegates the execution to the test runner from sdk repo. We may need more work on adhoc tests.
> 
> The property configs are already being moved to the repos.

Is there a way we can prevent engineers from adding additional test logic into the recipe?

**Comment by godofredoc** [comment]
We need documentation, guidelines and enforce the guidelines in code reviews.

**Comment by christopherfujino** [comment]
> We need documentation, guidelines and enforce the guidelines in code reviews.

SGTM

**Comment by christopherfujino** [comment]
Maybe also a comment in the recipe, "don't add test logic here!"

**Comment by godofredoc** [comment]
Also would it be possible to update the adhoc tests to use the runner? I think we can now safely assume the environment will be prepared for the script to run.

**Comment by christopherfujino** [comment]
> Also would it be possible to update the adhoc tests to use the runner? I think we can now safely assume the environment will be prepared for the script to run.

What are the ad hoc tests?

**Comment by godofredoc** [comment]
the ones in the .cirrus.yaml file e.g: https://github.com/flutter/flutter/blob/master/.cirrus.yml#L292 during the transition those will be implemented as bash scripts in the recipes repo but may be a good idea to add them to the test_runner.

**Comment by christopherfujino** [comment]
I didn't even know about that. Yeah, we should add them to `dev/bots/test.dart`

**Comment by godofredoc** [comment]
This is complete.
