### ISSUE TITLE
No recipe named 'femu_test_1_20_0' in repo 'flutter'

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#63682]
Here is the test: https://ci.chromium.org/p/flutter/builders/prod/Linux%20beta%20Fuchsia%20FEMU/2
```
Infra Failure
recipe infra failure: Uncaught exception: UnknownRecipe("No recipe named 'femu_test_1_20_0' in repo 'flutter'.",)
```

**Comment by godofredoc** [comment]
Created the forked version:

https://flutter-review.googlesource.com/c/recipes/+/5621
