### ISSUE TITLE
Update the Cupertino picker visuals

### ISSUE THREAD

**Issue by xster** [flutter/flutter#63694]
The picker UI has been updated in iOS 14
https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/

![pickers-hero_2x](https://user-images.githubusercontent.com/156888/90176987-b580c180-dd5e-11ea-941e-29a9b3101cc0.png)

**Comment by YeungKC** [comment]
In fact, date picker also has different effects in iOS14. If you change the style of picker, it will actually affect date picker, resulting in strange effects.
I think the title should be changed to Update the Cupertino picker and date picker visuals.

**Comment by xster** [comment]
I created a separate issue for the date picker https://github.com/flutter/flutter/issues/63693

If you meant the visual effect of the highlight for multi-column pickers like

![IMG_0005](https://user-images.githubusercontent.com/156888/90179509-65a3f980-dd62-11ea-8a7f-c651fbe953d4.PNG)

We can generally create a new constructor argument for https://github.com/flutter/flutter/blob/c67eafa87d2de441a195a8aa46c92eac37ce4616/packages/flutter/lib/src/cupertino/picker.dart#L257 to make it selectable. 

Then the highlight can be added in the date picker itself somewhere in https://github.com/flutter/flutter/blob/c67eafa87d2de441a195a8aa46c92eac37ce4616/packages/flutter/lib/src/cupertino/date_picker.dart#L1920

cc @LongCatIsLooong might have opinions

**Comment by LongCatIsLooong** [comment]
Now if someone wants to build a multi-column picker by combining `CupertinoPicker`s, they would have to add the grey `RRect` highlight themselves because the highlight has rounded corners? That shouldn't be too hard but they need to know what the color and the corner radius are.

**Comment by YeungKC** [comment]
@xster
I like the new constructor.
Because of your reply in #21049, I thought you would not recommend doing this.

**Comment by xster** [comment]
My general guidelines is to create various modular components to be able to compose a UI that matches the native UI in high fidelity in its various configurable forms. But for things outside the native spec, I wouldn't go too far to enable them since that's an infinitely scoped problem.

**Comment by omidraha** [comment]
> My general guidelines is to create various modular components to be able to compose a UI that matches the native UI in high fidelity in its various configurable forms. But for things outside the native spec, I wouldn't go too far to enable them since that's an infinitely scoped problem.

Configurable forms prevent developers from resort to unusual ways ([one](https://stackoverflow.com/a/59934967) , [two](https://github.com/figengungor/country_pickers/blob/3cb288d2208c4f0d51442935132065fb0f395152/lib/country_picker_cupertino.dart#L16) , ..) for customization.
