### ISSUE TITLE
We should have grab handles and support for mouse click-drag on widgets that only support longpress

### ISSUE THREAD

**Issue by csells** [flutter/flutter#63708]
Several widgets in Flutter support longpress to initiate a drag 'n' drop action, e.g. ReorderableListView. That's a natural gesture on mobile form-factors but not on desktop web or native desktop. The [material guidelines call for grab handles](https://material.io/components/lists#behavior) to indicate drag 'n' drop. Flutter should add grab handles into the widgets that support drag 'n' drop and not require longpress for mouse-initiated drag 'n' drop.

[Here's a DartPad sample](https://dartpad.dev/0fbfd605659c9d57bcf02843b6bc366c) that shows one work-around for adding short-click and drag by creating a clone of ReorderableListView and changing a single line of code (LongPressDraggable => Draggable).

![flutter-long-press-vs-short-press](https://user-images.githubusercontent.com/2568253/90189399-fafaba00-dd71-11ea-8c00-a48c8761f98a.gif)

**Comment by darrenaustin** [comment]
Hey folks, we are ramping up a design to try to address this and other issues with `ReorderableListView`. We are tracking it with #66080 and in a [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0). Feedback welcome.

**Comment by darrenaustin** [comment]
With the recent refactoring of the `ReorderableListView` (PRs: #74299 and #74697), we have added automatic drag handles when running on the desktop (with a `buildDefaultDragHandles` property to turn it off). If this isn't what you want, you can add your own drag handle as a widget to each of your items with something like:

```dart
ReorderableDragStartListener(
  index: index,
  child: const Icon(Icons.drag_handle),
),
```
 
somewhere in the child's subtree.
