### ISSUE TITLE
Removing WIP labels from PR seems to cancel/re-run certain LUCI tasks

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#63701]
This is almost certainly wasted effort, since there would be no code changes that necessitate re-running anything.

**Comment by nehalvpatel** [comment]
Yes, I will check this today

**Comment by nehalvpatel** [comment]
Looks like it was indeed addressed by @christopherfujino with this PR: https://github.com/flutter/cocoon/pull/1895

See also: https://github.com/flutter/flutter/issues/100717

**Comment by godofredoc** [comment]
Awesome let's close this bug. Thanks for checking!
