### ISSUE TITLE
MediaQuery.of(context).orientation returning incorrect value

### ISSUE THREAD

**Issue by kmcdonald-purchys** [flutter/flutter#63717]
I have an application where most pages are restricted to portrait view, but two pages support all orientations.  The main application is not restricted - I am restricting the orientations on each page.  The portrait pages are displaying correctly, but pages with landscape support are doing the following:

1) Begin in portrait
2) Rotate the phone to landscape (either direction)
3) The app flips to landscape (either direction), but immediately flips back to portrait
4) Rotate the phone back to portrait
5) Rotate the phone to landscape (either direction) and it doesn't even flip initially - it simply stays in portrait

I have the MediaQuery orientation printing on build for troubleshooting and here's what happens:

Step 1) Prints Orientation.portrait
Step 2) Prints the following:

Orientation.portrait
Orientation.landscape
Orientation.landscape
Orientation.portrait

All further rotations) Nothing is printed in the console

Note: This same code was working properly in past testing.  I am not certain at which point in time it ceased working properly.

## Code Sample

import 'package:flutter/services.dart';
import 'package:purchys_client/models/property.dart';
import 'package:purchys_client/widgets/header.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:photo_view/photo_view.dart';
import 'package:photo_view/photo_view_gallery.dart';

class PropertyGallery extends StatefulWidget {
  final Property property;
  final int index;

  const PropertyGallery({Key key, this.property, this.index}) : super(key: key);

  @override
  _PropertyGalleryState createState() => _PropertyGalleryState(property: this.property, index: this.index);
}

class _PropertyGalleryState extends State<PropertyGallery> {
  final Property property;
  int index;

  _PropertyGalleryState({this.property, this.index});

  @override
  void initState() {
    super.initState();

    if (index == null) {
      index = 0;
    }

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.portraitDown,
      DeviceOrientation.portraitUp,
    ]);
  }

  @override
  dispose(){
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    PageController _pageController = PageController(initialPage: index);

    print(MediaQuery.of(context).orientation.toString());

    return new Scaffold(
      appBar: 
        header(context, page: property.address, removeBackButton: false),
      body: Container(
        color: Theme.of(context).canvasColor,
        child: PhotoViewGallery.builder(
          pageController: _pageController,
          enableRotation: true,
          transitionOnUserGestures: true,
          backgroundDecoration: BoxDecoration(
            color: Theme.of(context).canvasColor,
          ),
          scrollPhysics: const BouncingScrollPhysics(),
          builder: (BuildContext context, int index) {
            return PhotoViewGalleryPageOptions(
              imageProvider: NetworkImage(property.images[index].mediaUrl),
              initialScale: PhotoViewComputedScale.contained,
              minScale: PhotoViewComputedScale.contained,
              maxScale: PhotoViewComputedScale.covered * 1.1,
            );
          },
          itemCount: property.images.length,
        )
      )
    );
  }
}

**Comment by darshankawar** [comment]
@kmcdonald-purchys 
Is this still a valid issue using latest Flutter stable version ? 
If so, can you provide updated `flutter doctor -v` and complete minimal reproducible code sample ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
