### ISSUE TITLE
image_picker not respecting locale

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#63719]
Im using image_picker and have correctly configured portuguese locale on MaterialApp like so:

```
  localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: [
          const Locale('pt', 'BR'),
        ],
```

But on iOS when i use ImageSource.camera it is in English ("use photo", etc). Seems like a bug to me.
Is there a way to make this correct (portuguese)?

Flutter doctor:

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale pt-BR)
    • Flutter version 1.20.1 at /Users/danvilela/flutter
    • Framework revision 2ae34518b8 (8 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 5A353A88-24B3-469C-9C9B-D2542FCAE084 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Hi @dmvvilela,
Can you add below in `info.plist` and see if it resolves your issue ?

```
<key>CFBundleDevelopmentRegion</key>
<string>es</string>
```

**Comment by dmvvilela** [comment]
There is already a Key there with the string: $(DEVELOPMENT_LANGUAGE)

Where can this be changed so i don't hardcode this?

(Also, es is for spanish.. brazilian portuguese is pt-BR)

**Comment by darshankawar** [comment]
@dmvvilela checkout [this](https://developer.apple.com/forums/thread/26130) link and see if it works for you.
Thanks.

**Comment by dmvvilela** [comment]
The thing is, for a multi language app this is not good enough.. Cause it can't be only english or only portuguese..

**Comment by darshankawar** [comment]
@dmvvilela I see what you are saying.
I tested on latest Stable (1.20.2) and indeed the text shows up in English, but not sure if providing only the `localizationDelegates` is enough for `image_picker` plugin to show up in specified language.

![IMG-0182](https://user-images.githubusercontent.com/67046386/90480967-a62eb900-e14e-11ea-927c-68117774cadf.PNG)

**Comment by dmvvilela** [comment]
Yep, that is the problem.

For now my app is only portuguese, but i'm pretty sure i'll have to internationalize it soon.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by mediproductions** [comment]
Hi,

my application is a multi language one so I really need another way to set the locale for this module.
Thank you

**Comment by jpr0ger** [comment]
Hi. Faced the same problem.

And after many hours of searching, it unexpectedly helped in my case. Perhaps it will be useful for someone else.

Edit the file Info.plist manually by Android Studio or VS Code or other text editor. 

Replace 

<key>CFBundleDevelopmentRegion</key>
<string>$(DEVELOPMENT_LANGUAGE)</string>

By

<key>CFBundleDevelopmentRegion</key>
  <array>
     <string>ru-RU</string>
     <string>en-US</string>
  </array>
<key>CFBundleLocalizations</key>
  <array>
     <string>ru-RU</string>
     <string>en-US</string>
  </array>

Of course, specifying your localization in the format xx-XX and specifying the parameters MaterialApp supportedLocales and localizationsDelegates.

![IMG_0160](https://user-images.githubusercontent.com/16898445/104076072-eab61080-5225-11eb-8606-515443465bcb.PNG)

**Comment by TahaTesser** [comment]
Hi everyone|
Flutter localization won't be modified for system text so modifying native locale is required, solution https://github.com/flutter/flutter/issues/63719#issuecomment-757053169 works perfectly, just tried with Chinese.

`image_picker: ^0.7.0-nullsafety`
<img src="https://user-images.githubusercontent.com/48603081/108365077-cd109980-721c-11eb-84e1-b89d8e2bdd66.jpeg" height="450" />

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.49, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.49 at /Users/tahatesser/Code/flutter_master
    • Framework revision 23e41734e5 (5 hours ago), 2021-02-18 00:46:02 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>

Maybe there could be some solution in the package to use flutter localization and modify native locale
Thank you

**Comment by stuartmorgan** [comment]
Native UI element language is controlled by the languages set in the application's plist. The need to reflect supported languages in the application is documented [here](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle)

Closing, as this is not an issue with the plugin; all native UI on iOS relies on the proper localization process having been followed.
