### ISSUE TITLE
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12:

### ISSUE THREAD

**Issue by yuqiaochuang** [flutter/flutter#63734]
I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
    The following assertion was thrown during performLayout():
    'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12:
    '_pendingDimensions': is not true.
    Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new?template=BUG.md
    The relevant error-causing widget was:
      SliverRefresh
      file:///Users/fionaliu/Downloads/flutter_pulltorefresh-master/lib/src/internals/indicator_wrap.dart:315:12
    When the exception was thrown, this was the stack:
    #2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:559:12)
    #3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
    #4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:189:39)
I/flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
    #6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:147:13)
    #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
    #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1466:12)
    #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1375:20)
    #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1638:7)
    #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
    #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
    #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
    #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
    #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
    #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
    #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
    #21     _invoke (dart:ui/hooks.dart:253:10)
    #22     _drawFrame (dart:ui/hooks.dart:211:3)
    (elided 5 frames from class _AssertionError and dart:async)
    The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#14a06 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT:
      needs compositing
      creator: SliverRefresh ← MaterialClassicHeader ← Viewport ← IgnorePointer-[GlobalKey#4074f] ←
        Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
        RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#728b0] ← _PointerListener ← Listener
        ← _ScrollableScope ← ⋯
      parentData: paintOffset=Offset(0.0, 512.0) (can use size)
      constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.reverse,
        scrollOffset: 457.1, remainingPaintExtent: 512.0, crossAxisExtent: 360.0, crossAxisDirection:
        AxisDirection.right, viewportMainAxisExtent: 512.0, remainingCacheExtent: 1012.0, cacheOrigin:
I/flutter:     -250.0)
      geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    This RenderObject had the following descendants (showing up to depth 5):
        child: RenderRotatedBox#3e73f relayoutBoundary=up2 NEEDS-PAINT
          child: RenderFractionalTranslation#8b1a8 relayoutBoundary=up3 NEEDS-PAINT
            child: RenderTransform#d68c7 relayoutBoundary=up4 NEEDS-PAINT
              child: RenderPositionedBox#33491 relayoutBoundary=up5 NEEDS-PAINT
                child: RenderSemanticsAnnotations#7121d relayoutBoundary=up6 NEEDS-PAINT
    ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/chatty: uid=10920(u0_a920) 1.ui identical 40 lines
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/chatty: uid=10920(u0_a920) 1.ui identical 7 lines
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/chatty: uid=10920(u0_a920) 1.ui identical 4 lines
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/zygote64: Do full code cache collection, code=123KB, data=79KB
I/zygote64: After code cache collection, code=99KB, data=62KB
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.
I/flutter: Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 559 pos 12: '_pendingDimensions': is not true.

**Comment by huanghui1998hhh** [comment]
How do you solve it....

**Comment by zenkog** [comment]
Any solution to this? I got the same problem. And the problem was caused by `ClassicHeader()` in my case.

**Comment by sunny-nahian** [comment]
have any Solution i also need it

**Comment by triztian** [comment]
I'm experiencing this same issue with the library, anyone know how to fix or prevent the issue in the `scroll_position` widget?
