### ISSUE TITLE
Landscape is busted on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6374]
This is using stocks since Gallery has landscape mode disabled.

![screen shot 2016-10-18 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/11857803/19492758/d9af6e7c-952c-11e6-84a6-bea780e6aeab.png)

@chinmaygarde might have a theory?

**Comment by eseidelGoogle** [comment]
@headcr4sh, your bug from twitter.  Just a recent regression.

**Comment by eseidelGoogle** [comment]
@chinmaygarde a couple folks ran into this today at the Dart summit.

**Comment by chinmaygarde** [comment]
The Info.plist looks correct in that it does not allow non-portrait orientation. Not sure why the simulator is allowing rotation.

**Comment by eseidelGoogle** [comment]
Customers who don't edit their Info.plist would still of course hit this.  We just have to fix the underlying engine bug. :)

**Comment by chinmaygarde** [comment]
Tracked to regression to the Android fix. https://github.com/flutter/engine/commit/d9d23336863bca886479c417d2a37f2c223251ec. Fixing.
