### ISSUE TITLE
Add ability to import SVG to Flutter project

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#63752]
Suggestion related to this: https://github.com/flutter/flutter/issues/1831

Everybody agree, that direct SVG support does not make any sense. Flutter should be able to import asset from source svg file and generate Dart code to render vector image properly. 3 ways possible:
- External command line tool to process source svg and convert it to Flutter drawable
- Android Studio/InteliJ Flutter plugin: add option to import svg and convert it to Flutter drawable format
- Define svg asset in publspec.yaml, svg will be processed at build time automatically and converted as required. 

I think it's good idea, because svg is widely used vector format, we need easy way to use it. Similar as native Android way - you can import svg and it will be converted to Android vector drawable format, which you can use.

Please vote/comment what do you think.

**Comment by darshankawar** [comment]
Hi @giaur500,
See [this](https://github.com/flutter/flutter/issues/55229#issuecomment-618066571) comment.
If you have any specific feature request or issues related to svg support, you may file it here: https://github.com/dnfield/flutter_svg.
Closing as, per the comment, there's currently no plan to have inbuilt support for svg. If you disagree, write in comments and I'll reopen.
Thanks.
