### ISSUE TITLE
Version suffix is removed when using --build-number for iOS

### ISSUE THREAD

**Issue by dominikheeb** [flutter/flutter#63768]
When using --build-number parameter for flutter build we want to use some version suffix for ios to mark prerelease versions during testing.

flutter seems to remove the suffix even though apple allows to use them when versioning a prerelease iOS app.

Source:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364

## Steps to Reproduce

`flutter build ios --release --no-codesign --build-number 1.2.4d241 ./lib/main.dart`

**Expected results:** 
Generated.xconfig file should contain "FLUTTER_BUILD_NUMBER=1.2.4d241"

**Actual results:** 
Generated.xconfig file contains FLUTTER_BUILD_NUMBER=1.2.4241

When i manually edit Generated.xconfig xcode build will use the version with suffix but flutter itself does not enter the value with suffix into the xconfig file.

<details>
  <summary>Logs</summary>

```
Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-CH)
    • Flutter version 1.17.5 at /Users/***/development/flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3
```

</details>

**Comment by dominikheeb** [comment]
upgrade flutter to 1.20.2 did not solve the issue

**Comment by TahaTesser** [comment]
i can reproduce same results on `master` too 


[Generated.xcconfig.zip](https://github.com/flutter/flutter/files/5075327/Generated.xcconfig.zip)

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (24 hours ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (2 available)            
    • SM M305F (mobile)  • 32003c30dc19668f                     • android-arm64 • Android 10 (API 29)
    • iPhone 11 (mobile) • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.94, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-10.0.pre.94 at /Users/tahatesser/Code/flutter_master
    • Framework revision 58feba8edd (11 hours ago), 2020-08-13 21:16:04 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • SM M305F (mobile)  • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11 (mobile) • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!
```

</details>

**Comment by dominikheeb** [comment]
Is there any update to this issue?
We still cannot produce pre release packages due to this issue.

**Comment by nickwph** [comment]
Hello! Just wanted to follow on this issue. Our team is still waiting for an official support for arbitrary version name and number setting in flutter.

**Comment by DYLERN** [comment]
Looks like the suffix is being intentionally removed:
https://github.com/flutter/flutter/blob/89edac404184db1dc9a04b4bad615e28d946037b/packages/flutter_tools/lib/src/build_info.dart#L456-L491
I feel like the developer should be able to disable this, maybe we could add a `--[no-]validate-build-name` flag to the `flutter build ios` and `flutter build ipa` commands?

**Comment by jmagman** [comment]
@vashworth has a good summary for why we don't want to do this:

> So Flutter has two different flags `--build-name` and `--build-number`. `--build-name` is used to set `CFBundleShortVersionString` and `--build-number` is used to set `CFBundleVersion`.
> 
> So for `--build-name`/`CFBundleShortVersionString`, both the [archived documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364:~:text=is%20not%20recognized.-,CFBundleShortVersionString,-CFBundleShortVersionString%20(String)) and [current documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) are clear that it should only be "three period-separated integers". So I don't think it makes sense to allow just any value to be set as this PR does.
> 
> Also, this PR doesn't seem to actually address issue #63768.
> 
> In issue #63768, they reported that `--build-number`/`CFBundleVersion` should allow a suffix that allows either d, a, b, or fc followed by a number of 1-255. And according to this [archived documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364:~:text=the%20LSApplicationQueriesSchemes%20key.-,CFBundleVersion,-CFBundleVersion%20(String)) for `CFBundleVersion`, it seems true. However, if we look at [current documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion), it does not mention allowing a suffix and explicitly states only "numeric characters (0-9) and periods" are allowed. It's not clear to me if the App Store/Xcode will reject, ignore, or accept the suffix.
> 
> If we wanted to allow the suffix as the archived documentation says, I think we should probably update the below function to only allow just a suffix of d, a, b, or fc (followed by a number of 1-255) rather than just any string.
> 
> https://github.com/flutter/flutter/blob/9a72e1c699f2b277b85110c89cbbb851f4de6935/packages/flutter_tools/lib/src/build_info.dart#L409-L454

https://github.com/flutter/flutter/pull/139227#issuecomment-1852733522

If you want to set a particular special version that would potentially be rejected by the App Store I suggest digging into your `ios/Runner.xcworkspace` and setting the `CURRENT_PROJECT_VERSION` build setting there yourself, and `CFBundleVersion` and `CFBundleShortVersionString` in the project, which _should_ override Flutter's attempts to parse the version from the pubspec.  There's nothing stopping you from doing whatever you want to your Xcode project, the Flutter `create` template is just trying to be helpful by letting you reuse your pubspec version.
