### ISSUE TITLE
Should the default `ThemeData.visualDensity` be `adaptivePlatformDensity` or `standard`?

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#63788]
Currently, the default value for `visualDensity` in a `ThemeData` is `VisualDensity.standard`, which is defined as `VisualDensity(horizontal: 0.0, vertical: 0.0)`. This matches the visual density of mobile devices before visual density was implemented.

Our `flutter create` template, however, currently defaults to using `VisualDensity.adaptivePlatformDensity`, which, as the name suggests, adapts the density to the platform it is running on, so for mobile platforms, it returns `standard`, and for desktop platforms it returns `compact`.

This is inconsistent, but the default was chosen using feedback from the Material Design team: they wanted the default to be the same as mobile platforms, with the reasoning that desktop platforms can have touch displays too, and so the controls should be accessible on a touch screen.

This is reasonable logic. It is also at odds with the normal state of desktop applications, and applications with a density the same as a mobile application looks very sparse and "magnified" on a desktop display when contrasted with other desktop apps. Using a desktop app with mobile density feels like an inefficient use of space when using a more accurate pointing device than a finger, and leaves fewer pixels for the more complex UIs that desktop apps typically have.

So, we should commit to a default, but which should it be? If we decide to keep the current default, and remove the adaptive form from the create template, how should we advertise the adaptive alternative so that desktop developers don't get the mistaken impression that Flutter can only do sparse UIs?

/cc @Hixie @HansMuller @willlarche @csells

**Comment by Hixie** [comment]
We seem to be saying the default should be adaptive, since that's what we're literally defaulting to in our templates. I'd like to make the template shorter by removing this part of it (there are lots of other features that I think we should be highlighting before this one if we're highlighting features beyond what we have without this one).

**Comment by csells** [comment]
agreed. the default should be what works best for the platform the app runs on; hardcoding the default to mobile and then overriding it in the generated template output is confused and unnecessary.

**Comment by clocksmith** [comment]
Given how this currently works, defaulting to adaptive and removing the template override makes sense to me. However, there may be more research needed to determine if this value should be set solely on target platform, or if it should also use screen size.

**Comment by gspencergoog** [comment]
When you say "screen size", I think what you are referring to is the physical dimensions of the screen, not the pixel size, and the problem is that on Desktop platforms we rarely know the physical size of the screen (and the ways we do have of getting it are unreliable).

Having a device pixel ratio helps, but even with that, the changes in density are odd: the density goes down as the logical screen size decreases, meaning that controls get larger on smaller screens, and making hard boundaries to the sizes causes popping in layout. Not having hard boundaries means that everyone gets a different layout depending on screen size, which is also not desirable.

Because of all that, I would suggest not basing it on screen size until we know for sure that it is important to do that.

I think the more relevant test is "are we running on mobile or desktop?", and I think we can usually answer that in better ways than screen size.

**Comment by gspencergoog** [comment]
We also do know if the user last interacted using touch or mouse pointer, but we don't use that as a signal because it would cause popping in the layout. We do use that to decide whether or not to show focus highlights, however.

**Comment by HansMuller** [comment]
Do we have an algorithm (heuristic) for distinguishing desktop and mobile platforms?

**Comment by gspencergoog** [comment]
We have some ways of guessing the difference, but we don't have a defined algorithm as such.  The information is a hodgepodge:

- If it runs iOS or Android, it's pretty likely to be a mobile device (ChromeOS running Android apps are exceptions), although that doesn't mean they don't also have a mouse.
- If it runs on Linux, Windows or macOS, it's pretty likely to be a desktop device (some Linux embedded systems aside), although that doesn't mean it doesn't also have a touch screen.
- On the web, we know the platform we're running on, and have some CSS media queries we can use to decide about the availability of touch interfaces, but those are also based on similar heuristics arrived at by the browser.
- Size is a common way to determine this on the web, because it is easy to do, but this also has issues on low-DPI desktop screens, and causes layout popping when you resize your browser. Also, when multi-window is a thing, different windows will have different sizes, they probably shouldn't have different densities because of this.
- If we see interactions with a touch pointer, we know there is at least a touch interface, although that's not guaranteed to be the only pointer interface. Same for mouse interactions. The problem is we can't currently get that information a priori, only after they interact.
- Hardware keyboard use and touch interfaces are negatively correlated, but they can still coexist.

So, we could develop an algorithm, but it is unlikely to be definitive or known at application launch. Even if we could know definitively between mobile and desktop, we don't know the user's preference.

Desktops can have touch interfaces, and low resolution screens, but that doesn't mean the user isn't using a mouse and keyboard to access them. Users can also switch between modes during the run of the app. As far as I know there's no way to determine the primary input mode, since it often is just at the whim of the user, and just because there isn't a mouse/keyboard now, does mean they won't attach one, or that they won't change their screen resolution/touch capability when dragging the window to another display.

I feel like this is something where we make a basic, deterministic, assumption (e.g. just based on platform), and let developers override if they have a different use case or intent, or want to ask the user their preference.
