### ISSUE TITLE
[flutter_tools] `flutter version` deprecation notice should link to website downloads

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#63787]
The preferred method of getting a Flutter release should be downloading the pre-built archive.

https://flutter.dev/docs/development/tools/sdk/releases

**Comment by albertviilik** [comment]
The deprecation notice for ```flutter version``` is generated by the following method in the class ```FlutterCommand```:

```dart
void _printDeprecationWarning() {
  if (deprecated) {
    globals.printStatus('$warningMark The "$name" command is deprecated and '
        'will be removed in a future version of Flutter.');
    globals.printStatus('');
  }
}
```

I believe that the issue can be solved by changing the printed status message to the following:

```dart
void _printDeprecationWarning() {
  if (deprecated) {
    globals.printStatus('$warningMark The "$name" command is deprecated and '
        'will be removed in a future version of Flutter. Refer to https://flutter.dev/docs/development/tools/sdk/releases');
    globals.printStatus('');
  }
}
```

The output before the change is:
```zsh
[!] The "version" command is deprecated and will be removed in a future version of Flutter.

1.20.2
1.21.0-9.0.pre
1.20.1
...
0.0.6
v0.0.6
v0.0.20-alpha
```

And after:
```zsh
/Users/albertviilik/git/GitHub/flutter/bin/cache/dart-sdk/bin/dart --enable-vm-service:63432 /Users/albertviilik/git/GitHub/flutter/packages/flutter_tools/bin/flutter_tools.dart version
Observatory listening on http://127.0.0.1:63432/YfOdhH0MCrk=/

[!] The "version" command is deprecated and will be removed in a future version of Flutter. Refer to https://flutter.dev/docs/development/tools/sdk/releases

1.20.2
1.21.0-9.0.pre
1.20.1
...
0.0.6
v0.0.6
v0.0.20-alpha
```

Please let me know what you think. Apologies for any mistakes. This is my first attempt of contribution to open source.

**Comment by christopherfujino** [comment]
> The deprecation notice for `flutter version` is generated by the following method in the class `FlutterCommand`:
> 
> ```dart
> void _printDeprecationWarning() {
>   if (deprecated) {
>     globals.printStatus('$warningMark The "$name" command is deprecated and '
>         'will be removed in a future version of Flutter.');
>     globals.printStatus('');
>   }
> }
> ```
> 
> I believe that the issue can be solved by changing the printed status message to the following:
> 
> ```dart
> void _printDeprecationWarning() {
>   if (deprecated) {
>     globals.printStatus('$warningMark The "$name" command is deprecated and '
>         'will be removed in a future version of Flutter. '
>         'Refer to https://flutter.dev/docs/development/tools/sdk/releases');
>     globals.printStatus('');
>   }
> }
> ```
> 
> The output before the change is:
> 
> ```shell
> [!] The "version" command is deprecated and will be removed in a future version of Flutter.
> 
> 1.20.2
> 1.21.0-9.0.pre
> 1.20.1
> ...
> 0.0.6
> v0.0.6
> v0.0.20-alpha
> ```
> 
> And after:
> 
> ```shell
> [!] The "version" command is deprecated and will be removed in a future version of Flutter. Refer to https://flutter.dev/docs/development/tools/sdk/releases
> 
> 1.20.2
> 1.21.0-9.0.pre
> 1.20.1
> ...
> 0.0.6
> v0.0.6
> v0.0.20-alpha
> ```
> 
> Please let me know what you think. Apologies for any mistakes. This is my first attempt of contribution to open source.

@albertviilik that looks right to me! If you open a PR with a test, I'd be happy to review it!
