### ISSUE TITLE
Set QOS and thread priorities for all threads managed by the Flutter engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#63812]
Part of this was attempted in https://github.com/flutter/engine/pull/15673 and must be carried to completion.

**Comment by wangying3426** [comment]
Any update please?

**Comment by JsouLiang** [comment]
@chinmaygarde Hello, I had PR about this issue, Please give me some suggestion, Thank you.
https://github.com/flutter/engine/pull/30605

**Comment by JsouLiang** [comment]
https://github.com/flutter/engine/pull/30605

**Comment by chinmaygarde** [comment]
Closing as completed in https://github.com/flutter/engine/pull/30605
