### ISSUE TITLE
Release and debug mode different for NNBD-migrated code 

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#63819]
The following code prints an exception in release/profile mode, but works as expected in debug mode:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'hello',
      home: Scaffold(
        floatingActionButton: FloatingActionButton(
          child: Text('123'),
          onPressed: () {
            try {
              print(BoxBorder.lerp(null, null, 0));
            } catch (e) {
              print(e);
            }
          },
        ),
      ),
    );
  }
}
```

The behavior stays the same when the implementation of `BoxBorder.lerp` is reduced to the following (have to update call-sides to new signatures):

```dart
  static BoxBorder? lerp(BoxBorder? a) {
    if (a is Border?) {
      print('a is Border?');
      return null;
    }
    if (a is Border) {
      print('a is Border');
      return const BorderDirectional();
    }
    print('throw');
    throw 'Help!';
  }
```

The code will print `throw` in release mode, and `a is Border?` in debug mode. The latter is the expected behavior. Modifying the function in the following ways makes the exception go away, but I cannot explain why that is, because it shouldn't matter:

* replacing `return const BorderDirectional()` with `return null`
* removing the second `if`
* duplicating the same function in the same class under a new name `lerp2` and calling this function also makes the exception go away (why?? it's the same code in the same scope).
* copying the function as is into another class and calling it on that other class makes the exception go away
* turning the function into a toplevel function and calling that function makes the problem go away.

It is completely unclear to my why the function changes it behavior when the modification described above are performed. I also don't know how to debug this further since extracting the function makes the problem go away....

For the record, the behavior in release mode should be the same as it is in debug mode.

Prior to migrating the file that contains `BoxBorder.lerp` to NNBD in https://github.com/flutter/flutter/commit/e8c942104bb4b414b67e303a54b00e8fc45c67a6 everything worked as expected.

**Comment by goderbauer** [comment]
@leafpetersen Any idea what is going on here or how to debug this further? It's a mystery to me right now...

**Comment by alexmarkov** [comment]
This is a bug in Dart AOT compiler (in implementation of `is` tests).
Small repro:

```dart
abstract class A {}
class B extends A {}
class C extends A {}

void foo(A? x) {
  if (x is C?) {
    print('$x is C?');
    return;
  }
  print('$x is not C?');
}

void main() {
  B();
  C();
  foo(B());
  foo(null);
}
```

Correct behavior in JIT:
```
$ out/ReleaseX64/dart --enable-experiment=non-nullable foo.dart 
Instance of 'B' is not C?
null is C?
```

Incorrect behavior in AOT:
```
$ pkg/vm/tool/precompiler2 --enable-experiment=non-nullable foo.dart foo.snapshot
$ pkg/vm/tool/dart_precompiled_runtime2 foo.snapshot
Instance of 'B' is not C?
null is not C?
```

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/158800

**Comment by goderbauer** [comment]
@alexmarkov Thanks for looking into and fixing it!

**Comment by alexmarkov** [comment]
The fix landed in Dart SDK repo. Do we need to cherry-pick it to the next release?
@a-siva @pcsosinski

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter in a51dc3d913344f3073da12f4aae654c3299dec6c.

**Comment by pcsosinski** [comment]
@goderbauer is this something we need to fix on beta/stable in your opinion?

**Comment by goderbauer** [comment]
@pcsosinski The bug in Dart was exposed in Flutter by PR https://github.com/flutter/flutter/pull/62951, so if that PR made it into any bata or stable releases we should definitely cherry-pick this fix. Even if that PR didn't make it into any releases, I'd be in favor of cherry-picking this fix since it can easily cause other nasty bugs, which are going to be hard to discover since they only manifest in release (production!) mode. I'd say we should cherry-pick.

**Comment by alexmarkov** [comment]
This bug can appear in AOT mode when doing `is` test with nullable type (`x is Foo?`) in migrated code. While user code is unlikely to trigger this bug, we have a bunch of migrated code in Dart SDK, Flutter and various packages.

**Comment by pcsosinski** [comment]
thanks

@goderbauer e8c942104bb4b414b67e303a54b00e8fc45c67a6 went in 8/11, 2 days after our 1.21 branch point and well after 1.20, so we'r good there

@alexmarkov I don't think we're expecting folks to run migrated code on the beta release yet, are we?

**Comment by alexmarkov** [comment]
@pcsosinski Only the code we migrated so far (Dart SDK/core libraries, a few packages, part of Flutter). Don't know if we have `is` tests with nullable types in that code (we certainly do after e8c942104bb4b414b67e303a54b00e8fc45c67a6).

**Comment by goderbauer** [comment]
I just did a quick search: the only `is` check with nullable types we have in the flutter/flutter code base was introduced in https://github.com/flutter/flutter/commit/e8c942104bb4b414b67e303a54b00e8fc45c67a6.
