### ISSUE TITLE
LUCI failure during the `buildbucket.collect` step

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#63820]
Unrelated failure in the PR: https://github.com/flutter/flutter/pull/63786

The failure happens at the `buildbucket.collect` step:
```
Failure
Step('display builds.build(s) failed') (retcode: 1)
```
https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/280

(I retried it https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/311 in the same PR and it succeeded).

**Comment by digiter** [comment]
Closing as the PR has landed.
