### ISSUE TITLE
[video_player] Keep audio playing in background

### ISSUE THREAD

**Issue by zxl777** [flutter/flutter#63836]
[video_player] Keep audio playing in background

**Comment by SriniVest** [comment]
what is  the significance of audio playing in the background @zxl777

**Comment by darshankawar** [comment]
Hi @zxl777,
Can you elaborate on the issue ? It's not clear if this is an issue or a request. Also provide a use-case wherein you need the audio to keep playing in background. Usually it's a good practice to stop audio when user moves out of the screen or minimizes the app.

**Comment by zxl777** [comment]
After subscribing to YouTube App membership, YouTube App has a background playback function. At this time, the phone screen can be black and news or music is still playing in the background.

**Comment by YazeedAlKhalaf** [comment]
Any updates?

**Comment by robert-j-webb** [comment]
Hey any update on this? Would love to have this as a feature?
