### ISSUE TITLE
"flutter build apk" is slow

### ISSUE THREAD

**Issue by safield** [flutter/flutter#63830]
I am using the command "flutter  build apk --debug --target-platform=android-arm" to build my app.

My app is not very large. Its take about 23 seconds to build after I change only one line. This is really slow!

**Comment by Abhishek01039** [comment]
it is completely fine for building a new apk.
still, update Gradle.properties to 
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
```
and upgrade the Gradle version to 6.5.1 as well
it will improve a little bit

**Comment by jonahwilliams** [comment]
@safield  there is a reason our issue templates include things like log ouput and `flutter doctor`. How could anyone possibly help you if you won't even include info on what is slow or what version of flutter you are on?
