### ISSUE TITLE
[web] support felt test for firefox on windows

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#63832]
`felt test --browser=firefox` command runs both unit tests and integration tests.

It works on Linux and Mac now, it's better to increase the support to Windows. 

We can also add one test to Windows LUCI bots to run, so that we can make sure that tooling won't break other changes. Running more tests on Windows bots (since Linux is already running them), won't add more value, and use resources.

**Comment by yjbanov** [comment]
Our story for Windows engine hacking is to use WSL, where Firefox should work already.
