### ISSUE TITLE
"Host Tests for ios_debug_sim" failing on bots but passing locally

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#63843]
Example [PR's](https://github.com/flutter/engine/pull/20537) failed run: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/7106?

These unit tests were fixed in https://github.com/flutter/engine/commit/0cda2931e502809dcc8dcb335816b4259fbe04ba and the tree eventually turned green after that PR landed.  But that bot started turning red again for the some reason, see  https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6386.

It's almost like the tests are running with an old version of `ios_test_flutter` but `run_tests.py` is [ensuring that that is getting built before the tests are run](https://github.com/flutter/engine/blob/1590fb23caf49f5cc19884673381cfdfc8c186e9/testing/run_tests.py#L296).

https://github.com/flutter/flutter/issues/63802 is probably related.

cc @dnfield @godofredoc

**Comment by dnfield** [comment]
Do we need to clobber the builder caches?

**Comment by gaaclarke** [comment]
If you look at the failure before the fixing PR: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871971729595584672/+/steps/Host_Tests_for_ios_debug_sim/0/stdout

```
/b/s/w/ir/cache/builder/src/out/ios_debug_sim/../../third_party/ocmock/Source/OCMock/OCMockObject.m:419: error: -[AccessibilityBridgeTest testAnnouncesLayoutChangeWithLastFocused] : failed: caught "NSInvalidArgumentException", "-[OCMockObject(FlutterView) view]: unrecognized selector sent to instance 0x600001dff340"
```

and after the fixing pr: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871969852673199920/+/steps/Host_Tests_for_ios_debug_sim/0/stdout

```
2020-08-14 11:04:17.082120-0700 IosUnitTests[27591:420192] ERROR: UIAccessibilityElement initialized with nil container: 
```

The errors are different.  This seem to not be an infra problem, but some flake that isn't showing up locally.  This may have been flakey for a while but the tests were passing on red.

**Comment by godofredoc** [comment]
we are clobbering by default in all the engine builds

**Comment by gaaclarke** [comment]
The root problem got fixed in https://github.com/flutter/engine/commit/f60e8369681e7c75e7cb93b7ae03bac0e92dce5e.  It appears to be a problem with running the tests on different platforms since how the UIAccessibilityElement class behaves triggered the error or not.  That's why they worked locally and not remotely.  I don't think there is much we can do there.
