### ISSUE TITLE
CheckboxListTile tristate: true not working

### ISSUE THREAD

**Issue by hpoul** [flutter/flutter#63846]
#58154 added `tristate` for `CheckboxListTile` but did not update the logic for what actually happens when the user taps on the list tile to call `onChanged`.

the documentation reads:

>  /// When a tri-state checkbox ([tristate] is true) is tapped, its [onChanged]
>  /// callback will be applied to true if the current value is false, to null if
>  /// value is true, and to false if value is null (i.e. it cycles through false
>  /// => true => null => false when tapped).

But the implementation does not support this:

https://github.com/flutter/flutter/blob/d1583fc39b8044d8e92fed63a01e0b523ce248b7/packages/flutter/lib/src/material/checkbox_list_tile.dart#L419

hence when trying to use it with tristate and `value: null` when tapping on the list tile produces:

```
flutter: 2020-08-15 12:14:41.735337 SHOUT main - Unhandled Flutter framework (gesture) error.
### Failed assertion: boolean expression must not be null
#0      CheckboxListTile.build.<anonymous closure> (package:flutter/src/material/checkbox_list_tile.dart:419:54)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:19)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
```

tapping on the Checkbox within the ListTile works as intended.

## Steps to Reproduce

create a `CheckboxListTile` with `tricheck: true`: Here an example: https://dartpad.dartlang.org/a50f547017bba61fc6c73f68aa100081

**Expected results:** 

true => null => false

**Actual results:** 

null error when `value` is null, otherwise:

true => false => tue => false

here the difference between tapping on the list tile vs tapping on the checkbox:

![checkboxilsttile-tristate](https://user-images.githubusercontent.com/313066/90310478-e2b1a900-def1-11ea-9289-224b404c7f50.gif)

**Comment by xu-baolin** [comment]
I am currently investigating this issue.

**Comment by darshankawar** [comment]
Issue replicable on latest Stable (1.20.2) and throws exception when checbox is tapped and it's state is `null`.

![63846](https://user-images.githubusercontent.com/67046386/90388160-0537f380-e0a5-11ea-8a22-aa045a712dce.png)

<details>
<summary>log</summary>

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Failed assertion: boolean expression must not be null


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      CheckboxListTile.build.<anonymous closure> (package:flutter/src/material/checkbox_list_tile.dart:417:54)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#809de
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(61.3, 348.0)
  finalLocalPosition: Offset(61.3, 40.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
W/libEGL  (26980): EGLNativeWindowType 0xd42cc008 disconnect failed
D/mali_winsys(26980): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(26980): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/BpSurfaceComposerClient(26980): Failed to transact (-1)
E/BpSurfaceComposerClient(26980): Failed to transact (-1)
```

</details>

**Comment by HansMuller** [comment]
CC @shihaohong
