### ISSUE TITLE
get null safety to work

### ISSUE THREAD

**Issue by srinivas-codezyng** [flutter/flutter#63841]
Hi, I am trying to get null safety working in my Flutter project. Just not able to get it working.
I have tried with Dev/beta channel. It does not work. I always keep getting following error: 

This requires the 'non-nullable' language feature to be enabled.

I tried adding analysis.options.yaml file as well in the root folder of the project. It does not work.
Appreciate any help for how to get null safety working in Flutter.

Thanks,
Srinivas

**Comment by jonahwilliams** [comment]
null-safety is not released yet
