### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by pawani15** [flutter/flutter#63844]
The following assertion was thrown building DashboardPage(dirty, state: _DashboardPageState#dbb6a):
type 'String' is not a subtype of type 'int' of 'index'

The relevant error-causing widget was: 
  DashboardPage file:///E:/Edecofy_5_8_20/lib/OnBoardingScreens/OnBoardingScreens.dart:83:59
When the exception was thrown, this was the stack: 
#0      Constants.drawer (package:Edecofy/const.dart:485:55)
#1      _DashboardPageState.build (package:Edecofy/dashboard.dart:391:27)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...

**Comment by Abhishek01039** [comment]
hii @pawani15 
This platform is not meant for your personal code assistance 
please as this type of question in https://flutter.dev/community
Thanks

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
