### ISSUE TITLE
Google Maps map with Circle with a center of (NaN, NaN) crashes the app with no error message

### ISSUE THREAD

**Issue by thib92** [flutter/flutter#63845]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Install the Google Maps package
3. Create Circles with a center of (NaN, NaN) and a radius of 0.0
4. See the app crash with no error message

**Expected results:**

Obviously this is a bug on the user's end, but the app crashes without an error message, so it is quite hard to debug. It would be nice to throw an error that can be caught by the IDE's debugger

**Actual results:**

The app crashes with no error message and the debug session ends.

**Comment by darshankawar** [comment]
Hi @thib92,
Can you provide `flutter doctor -v` and a minimal code sample that shows the issue ?
I tried with a demo code, but was able to see the map open properly without any issues. Maybe I am missing something in the demo code.

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import "package:flutter/cupertino.dart";
import 'package:google_maps_flutter/google_maps_flutter.dart';

num lt = 0/0;
num ln = 0/0;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: TrialMaps(),
    );
  }
}

class TrialMaps extends StatefulWidget {

  @override
  _TrialMapsState createState() => _TrialMapsState();
}

class _TrialMapsState extends State<TrialMaps> {

  LatLng firstLocation = LatLng(lt, ln);

  GoogleMapController _mapController;

  @override
  Widget build(BuildContext context) {
    print(lt.isNaN);
    print(ln.isNaN);

    Set<Circle> circles = Set.from([Circle(
      circleId: CircleId("my id"),
      center: LatLng(lt, ln),
      radius: 0,
    )]);
    return GoogleMap(
      mapType: MapType.normal,
      myLocationEnabled: true,
      circles: circles,
      onCameraMove: null,
      initialCameraPosition: CameraPosition(
        target: firstLocation,
        zoom: 10,
      ),
      onMapCreated: (GoogleMapController controller) {
        setState(() {
          _mapController = controller;
        }
        );
      },
    );
  }
}
```

</details>

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
