### ISSUE TITLE
Alert dialog doesn't dismiss immediately

### ISSUE THREAD

**Issue by amirmujtaba** [flutter/flutter#63848]
## Steps to Reproduce

```dart
bool flag= await showDialog(
              context: context,
              builder: (BuildContext context)
            {
              return AlertDialog(
                title: Text('Are you sure?'),
                content: Text("Are you sure to post new request?"),
                backgroundColor: Theme.of(context).primaryColor,
                actions: <Widget>[
                  RaisedButton(shape: StadiumBorder(),child: Text("Yes, Post request"),
                      onPressed: () =>
                      {
                        Navigator.of(context).pop(true)
                      }),
                  RaisedButton(shape: StadiumBorder(),color: Theme.of(context).errorColor,child:Text("No", style: TextStyle(color: Colors.white)),
                    onPressed: () => Navigator.of(context).pop(false),
                  )
                ],
              );
            });
            print(flag);
            if(flag)
              {
                for (int i = 0; i < 1000; i++) {
                RequestsService.addRequest(request).then((value) => {});
                }
                print("123");
              }
```
**Expected results:** 
It should immediately dismiss the dialog when yes button is pressed

**Actual results:** 
It doesn't immediately dismiss the dialog when yes button is pressed, rather dismiss after completing the loop 1000 time

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
hii @amirmujtaba 
can you please provide `flutter doctor -v ` and `flutter run -v`
Thanks

**Comment by amirmujtaba** [comment]
you can check this link for sample https://dartpad.dev/d9dbf51fbf8e87d37503d16fc04eaf24?fbclid=IwAR1hqgz9CdtbTaIi38ZhYJoAHD_-3DkqV12rMg4tsV-m1YxcKeLMLxb9rUs

**Comment by Abhishek01039** [comment]
working fine @amirmujtaba 
it is popping the window immediately.

**Comment by amirmujtaba** [comment]
No, it's not working, I have tried calling API in Future.delayed,  now that is working better, but there is still problem it block UI thread, i.e. I'm giving duration 1 sec, and dialog is dismissed immediately but circular progress bar stuck

**Comment by pedromassangocode** [comment]
Hi @amirmujtaba 
Based on the issue description the code your provided (https://dartpad.dev/d9dbf51fbf8e87d37503d16fc04eaf24?fbclid=IwAR1hqgz9CdtbTaIi38ZhYJoAHD_-3DkqV12rMg4tsV-m1YxcKeLMLxb9rUs) is working as expected the AlertDialog is popping immediately.

Please provide a clear example that reproduces the issue you're facing.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
