### ISSUE TITLE
Why am I getting an error in the build function when changing the theme of the application?

### ISSUE THREAD

**Issue by StatTark** [flutter/flutter#63853]
My main file down below;

```
import 'package:flutter/material.dart';
import 'package:ajanda/screens/mainmenu.dart';
Future<void> main() async{
  runApp(MaterialApp(
      debugShowCheckedModeBanner: false, title: "Takvim", home: MainMenu()));
}
```

Mainmenu file down below;

```
import 'package:ajanda/blocs/theme.dart';
import 'package:provider/provider.dart';

//const String testDevice = 'Mobile_id';

class MainMenu extends StatelessWidget {
  MainMenu({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<ThemeChanger>(
      builder: (_) => ThemeChanger(ThemeData.dark()),
      child: new MaterialAppWithTheme(),
    );
  }
}

class MaterialAppWithTheme extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MainMenuBody(),
    );
  }
}

class MainMenuBody extends StatefulWidget {
  @override
  _MainMenuBodyState createState() => _MainMenuBodyState();
}

class _MainMenuBodyState extends State<MainMenuBody> {

....

}
```

**I'm trying to make a dark theme, but I got 2 errors and I can't solve the reason why I would be glad if you could help. I'm getting an error like this in my build function. The argument type 'Widget Function (BuildContext)' can't be assigned to the parameter type 'Widget Function (BuildContext, Widget)'. The other issue like this error: The return type 'ThemeChanger' isn't a 'Widget', as required by the closure's context.**

Theme.dart file down below

```
import 'package:flutter/material.dart';

class ThemeChanger with ChangeNotifier{

  ThemeData _themeData;

  ThemeChanger(this._themeData);

  getTheme() => _themeData;

  setTheme(ThemeData theme){
    _themeData= theme;

    notifyListeners();
  }

}
```

**Comment by abhikhedekar4241** [comment]
Hey, can you provide screenshot of the error

**Comment by StatTark** [comment]
@abhikhedekar4241 
![image](https://user-images.githubusercontent.com/33375656/90316265-ba45a100-df29-11ea-919d-7d4a194600b7.png)

**Comment by bierbaumtim** [comment]
You should use create to provide the ChangeNotifier. The builder is a WidgetBuilder.

**Comment by abhikhedekar4241** [comment]
Yes. You should use create instead of builder

**Comment by StatTark** [comment]
@abhikhedekar4241 Can you give me a code sample that I can implement?

**Comment by bierbaumtim** [comment]
```
return ChangeNotifierProvider<ThemeChanger>(
      create: (_) => ThemeChanger(ThemeData.dark()),
      child: new MaterialAppWithTheme(),
);
```

**Comment by abhikhedekar4241** [comment]
@bierbaumtim Perfect 👍🏻

**Comment by bierbaumtim** [comment]
Also i'm not sure if it is possible or a good idea to have more than one MaterialApp. You can use the ChangeNotifierProvider inside runApp;
Like:
```
Future<void> main() async{
  runApp(ChangeNotifierProvider<ThemeChanger>(
         create: (_) => ThemeChanger(ThemeData.dark()),
         child: new MaterialAppWithTheme(),
      ));
}
```

**Comment by StatTark** [comment]
@bierbaumtim I am getting one more error. 
![image](https://user-images.githubusercontent.com/33375656/90316488-368cb400-df2b-11ea-8f4f-3c55c83e1b57.png)

source : https://developer.school/flutter-dynamic-theming-with-provider/

**Comment by bierbaumtim** [comment]
move the line into the build function as in the provided source and it should work.

In an StatelessWidget it is only possible to access the BuildContext from the build method.
In an StatefulWidget you can use the BuildContext in all methods except initState to get InheritedWidgets.
