### ISSUE TITLE
local_auth:0.6.2+3 - AAPT: error: expected reference but got (raw string) #FFFFFFFF. 

### ISSUE THREAD

**Issue by mhabashy** [flutter/flutter#63855]
Error while tyring to build android for the first time after moving to a new MAC. Was able to build two other flutter apps fine, one had local_auth and the other didn't. However, I would like to note that it was on  flutter 1.20.1, before I updated to flutter 1.20.2

### Gradle Version
gradle-6.1.1

------
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/<~>/Desktop/<~>/build/local_auth/intermediates/packaged_res/debug/values/values.xml:11:5-16:11: AAPT: error: expected reference but got (raw string) #FFFFFFFF.
      

--------------
# FLUTTER DOCTOR
--------------
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)
------------

**Comment by Abhishek01039** [comment]
hii @mhabashy 
can you send your values.xml file?

**Comment by mhabashy** [comment]
@Abhishek01039 Thanks for responding. Sure thing 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="black_text">#212121</color>
    <color name="grey_text">#757575</color>
    <color name="hint_color">#BDBDBD</color>
    <color name="success_color">#43A047</color>
    <color name="warning_color">#E53935</color>
    <dimen name="body_text_size">14sp</dimen>
    <dimen name="huge_text_size">20sp</dimen>
    <dimen name="medium_text_size">16sp</dimen>
    <style name="AlertDialogCustom" parent="@android:style/Theme.Material.Dialog.Alert">
    <item name="background">#FFFFFFFF</item>
    <item name="android:textStyle">bold</item>
    <item name="android:textSize">14sp</item>
    <item name="colorAccent">#FF009688</item>
  </style>
</resources>
```

**Comment by Abhishek01039** [comment]
hi @mhabashy 
Thanks for sharing your code.
I think you need  `android:background` key in `<item name="background">#FFFFFFFF</item>`.
Thanks

**Comment by Abhishek01039** [comment]
By the way, this thing 
 ```
  <item name="background">#FFFFFFFF</item>
    <item name="android:textStyle">bold</item>
    <item name="android:textSize">14sp</item>
    <item name="colorAccent">#FF009688</item>
``` you can provide the `AlertDialog` widget.

**Comment by mhabashy** [comment]
@Abhishek01039 added
```
<resources>
  <!-- Fingerprint dialog theme. -->
  <style name="AlertDialogCustom" parent="@android:style/Theme.Material.Dialog.Alert">
    <item name="android:background">#FFFFFFFF</item> //<!--- added android:background key
    <item name="android:textStyle">bold</item>
    <item name="android:textSize">14sp</item>
    <item name="colorAccent">#FF009688</item>
  </style>
</resources>
```

This worked right away. thank you.
