### ISSUE TITLE
flutter logs doesn't show logs for physical devices

### ISSUE THREAD

**Issue by haiqn** [flutter/flutter#6385]
## Steps to Reproduce

1. Connect an iPhone with laptop.
2. flutter run from the flutter app directory.
3. Open another terminal tab and do flutter logs.

## Logs

Run your application with `flutter run` and attach all the log output.

flutter run --no-hot -d f8169b6874207f9ae293f3f6a0a6297d35043fb1
Running lib/main.dart on ...
Exception from flutter run: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 56618
dart:io                                                           WebSocket.connect
package:flutter_tools/src/vmservice.dart 28                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          VMService.connect
package:flutter_tools/src/resident_runner.dart 106                ResidentRunner.connectToServiceProtocol.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/resident_runner.dart                    ResidentRunner.connectToServiceProtocol
package:flutter_tools/src/run.dart 192                            RunAndStayResident._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/ios/devices.dart 294                    IOSDevice.startApp.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/ios/devices.dart 310                    IOSDevice._acquireAndForwardPort.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/run.dart                                RunAndStayResident._run
package:flutter_tools/src/run.dart 52                             RunAndStayResident.run.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/run.dart 50                             RunAndStayResident.run
package:flutter_tools/src/commands/run.dart 219                   RunCommand.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 62                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 147                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 199         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 50                          DeviceManager.getDevicesById.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 183                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 136                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 72                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 105                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>

Run `flutter analyze` and attach any output of that command also.

flutter analyze
Analyzing lib/main.dart...
No analyzer warnings! (ran in 6.7s)

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/hqn/flutter
    • Framework revision 57044c2a63 (53 minutes ago), 2016-10-18 13:38:13
    • Engine revision 269fd75d56
    • Tools Dart version 1.21.0-dev.0.0

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x libimobiledevice is incompatible with the installed XCode version. To update, run:
      brew uninstall libimobiledevice
      brew install --HEAD libimobiledevice

[-] Atom - a lightweight development environment for Flutter
    • flutter plugin not installed; this adds Flutter specific functionality to Atom.
      Install the plugin from Atom or run 'apm install flutter'.
    • dartlang plugin version 0.6.39

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin installed
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    •          • f8169b6874207f9ae293f3f6a0a6297d35043fb1 • ios
    • iPhone 6 • 5008B5FC-46A9-41CF-989A-B0ECA3F6A519     • ios (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
This is due to:
```
x libimobiledevice is incompatible with the installed XCode version. To update, run:
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
```
libimobiledevice is how we get logs, etc from the device.

@danrubel Should `flutter logs` have had a different failure mode here?

**Comment by Hixie** [comment]
Well we definitely shouldn't show that stack trace.

**Comment by Vanethos** [comment]
Sorry to pick up such an old issue, but this is happening again for me

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.2 18C54, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

`flutter logs` works correctly on Android, but on iOS I see logs from the device, not flutter logs 

E.g.

```
Requesting to start advertising for clients 16  with (
        {
        kCBAdvDataAppleMfgData = <0aff4c00 1005071c 8e58b4>;
        kCBAdvDataIsConnectable = 1;
        kCBAdvOptionAdvertisingInterval = 432;
        kCBMsgArgIsPrivilegedDaemon = 1;
    }
)
Received XPC message "CBMsgIdStopAdvertising" from session "com.apple.wirelessproxd-peripheral-53-2"
Sending XPC message "CBMsgIdAdvertisingStopped" to session "com.apple.wirelessproxd-peripheral-53-2"
Received XPC message "CBMsgIdStartAdvertising" from session "com.apple.wirelessproxd-peripheral-53-1"
```

**Comment by zoechi** [comment]
@Vanethos please create a new issue instead. This one is long closed.
Adding a link to this issue in the new one is a good idea though.
