### ISSUE TITLE
Plugin project :connectivity_macos not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by azad47808** [flutter/flutter#63878]
I have a project that made with older Flutter,  I created a new flutter app and copy and paste the lib folder, pubspec.yaml, test folder, fonts, and images folder from the old project to my new project. When I run the project in VSCODE I get this error.
`Launching lib\main.dart on SM J710F in debug mode...
Plugin project :connectivity_macos not found. Please update settings.gradle.`
And after that forever I get  Running Gradle task 'assembleDebug'... in VSCODE.

**Flutter docter.**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Dart --version**
`Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"`

**pubspec.yaml**
name: moneyexchangeunion
description: Money Exchange Union App

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bmnav:
  http:
  flutter_datetime_picker:
  flutter_localizations:
    sdk: flutter
  dropdownfield:
  flutter_tagging:
  url_launcher: ^5.5.0
  connectivity:
  flutter_html:
  flutter_swiper:
  youtube_player_flutter:
  flutter_email_sender:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/ico.jpg
    - images/image-placeholder.jpg
    - images/sarf.jpg
    - images/banner.jpg
    - images/totia.jpg
    - images/afg.png
    - images/australia.png
    - images/canada.png
    - images/crone.png
    - images/tot.png
    - images/face.png
    - images/web.png
    - images/call.png
    - images/tel.png
    - images/usa.png
    - images/caldar.png
    - images/darham.png
    - images/pound.png
    - images/riyal.png
    - images/rupees.png
    - images/toman.png
    - images/euro.png
    - images/frank.png

  fonts:
    - family: IranSans
      fonts:
        - asset: fonts/IRANSansMobile.ttf
          weight: 400
        - asset: fonts/IRANSansWeb_Light.ttf
          weight: 300
        - asset: fonts/IRANSansWeb_Medium.ttf
          weight: 500```

**settings.gradle**
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle

**Comment by azad47808** [comment]
I solved this problem by deleting connectivity_macos-0.1.0+3 folder form flutter_sdkpath\.pub-cache\hosted\pub.dartlang.org

**Comment by darshankawar** [comment]
@azad47808,
Given your last message, I feel safe to close the issue. If you disagree, write in comments and I'll reopen.
Thanks.
