### ISSUE TITLE
ToggleButtons Widget optionally extend down vertically

### ISSUE THREAD

**Issue by LockedThread** [flutter/flutter#63871]
Hey, Flutter development community. I want to make a suggestion about the ToggleButtons widget. The ToggleButtons widget is quite intuitive but lacks feasibility in some use-cases. My proposal is to add the option for the ToggleButtons widget not only to work horizontally but also vertically so it would stack down after there's no room left horizontally.

Here is my use case:
![image](https://user-images.githubusercontent.com/42919066/90324234-0d275480-df3a-11ea-9075-d79f989450d0.png)

So ToggleButtons would work to an extent with this if it was only one row, not two.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by xu-baolin** [comment]
I continue this work now, the previous PR #63880 has been closed without merge.
