### ISSUE TITLE
Flutter is laggy 😢

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#63891]
Flutter is so laggy and I want the issue to be addressed. The app runs smoothly after the first run. But each time you enter the app it lags a lot. Doesn’t stay at 60FPS. I have tried it first on my iPhone 6. But then when I tried it on an iPhone 11 Pro Max the app still lags a bit at every startup. It is frustrating. Flutter promises 60FPS but I don’t see it. I need help. Btw the problem is worse on iOS than on Android.

I can’t share source code but I can give you app links to download and try it.

**Comment by AliAnilKocak** [comment]
Have you tested the suggestions here? [Flutter Best Practices](https://flutter.dev/docs/perf/rendering/best-practices )

There are many factors that affect performance. For example: large images, too many items, etc.

You can send the application link so that we can make a review.

**Comment by YazeedAlKhalaf** [comment]
iOS: https://apps.apple.com/sa/app/split-it-split-your-stories/id1525916578
Android: https://play.google.com/store/apps/details?id=dev.alkhalaf.split_it

**Comment by iapicca** [comment]
I think @AliAnilKocak is making a [good point](https://github.com/flutter/flutter/issues/63891#issuecomment-674503049),
performance are very much dependent from your implementation and optimization,
you may want to make sure that
-  the installed flutter version is the `latest stable` or above

and provide 
-  `flutter doctor -v`
-  `flutter run -v` (or flutter run -d chrome -v for web etc)
-  `pubspec.yaml`
-  MOST IMPORTANTLY a minimal reproducible code sample (not a snippet or production code!)

**Comment by pedromassangocode** [comment]
Hi @YazeedAlKhalaf 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that reproduces this issue?
Thank you

**Comment by YazeedAlKhalaf** [comment]
I think the cause is using the FFmpeg library.

I am closing this for now,
