### ISSUE TITLE
Web Skia rendering not working in debug mode

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#63898]
## Steps to Reproduce

1. Create a Flutter app.
2. `flutter config --enable-web` on the `beta` channel.
3. `flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome`

**Expected results:** I would expect Flutter to use Skia for rendering.

**Actual results:** The app with Rive does not run. See https://github.com/rive-app/rive-flutter/issues/2#issuecomment-673964042.

### Versions

```
Flutter 1.20.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

## Release mode

Executing the command from above (**3.**) and appending `--release` will make Skia rendering work.

I want to use Skia rendering in debug mode, however, I cannot succeed in doing so.

## Related issues

This is a critical issue because of related issues like https://github.com/rive-app/rive-flutter/issues/2.

The consequence of the aforementioned issue is that any app using a package like that cannot be debugged because they will not even run in debug mode.

**Comment by sidrao2006** [comment]
Sorry, but this is not the case with me... Skia improves the support of SVGs and so I tried using it.
It did work on debug mode. The only problem is it doesn't render images

**Comment by sidrao2006** [comment]
Can you please post the output of `flutter doctor` and `flutter run -v`

**Comment by iapicca** [comment]
possible dupe of https://github.com/flutter/flutter/issues/63370

**Comment by markusaksli-nc** [comment]
I also cannot reproduce this. Please provide your `flutter doctor -v` and `flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome --verbose` logs.

**Comment by creativecreatorormaybenot** [comment]
@markusaksli-nc See https://github.com/rive-app/rive-flutter/issues/2#issuecomment-673964042.

**Comment by markusaksli-nc** [comment]
What are you using to check which rendering backend flutter is using?

**Comment by creativecreatorormaybenot** [comment]
@markusaksli-nc I am using https://github.com/rive-app/rive-flutter/issues/2#issuecomment-673964042 as a reference. I cannot see anything rendered at all - only this error in the JS console.

**Comment by creativecreatorormaybenot** [comment]
@iapicca @markusaksli-nc I moved this issue to #64011 to better describe the issue 👍
