### ISSUE TITLE
Unnecessary JAVA process running in background

### ISSUE THREAD

**Issue by Revantark** [flutter/flutter#63905]
After executing " flutter run" command in terminal ( After building apk) , there seems to be a java process running in 
the background consuming 500MB to 1GB . I killed the process as i thought it was useless since app has been built. And checked ,whether everything is 
working or not. Yes. Everything is fine and i get 1GB RAM free. 
I do it every time to free up my RAM , so that my chrome and other apps wont stuck/lag.

Auto killing the process, after building apk would be great. 

**flutter doctor -v**

```
[✓] Flutter (Channel stable, 1.20.0, on Linux, locale en_IN)
    • Flutter version 1.20.0 at /usr/flutter
    • Framework revision 840c9205b3 (12 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/revanth_ark/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
[flutter run -v.txt](https://github.com/flutter/flutter/files/5082421/flutter.run.-v.txt)

**Comment by jonahwilliams** [comment]
@Revantark please don't add irrelevant labels to your bug report

**Comment by sidrao2006** [comment]
It may be because you are using `flutter run` . Please check if you are facing the same problem with `flutter build` . 
Also please provide `flutter doctor -v` and `flutter run -v`

**Comment by Revantark** [comment]
> It may be because you are using `flutter run` . Please check if you are facing the same problem with `flutter build` .
> Also please provide `flutter doctor -v` and `flutter run -v`

Hmm. Added those commands. problem exist even with flutter build.

**Comment by sidrao2006** [comment]
Can you please provide the outputs of `flutter doctor -v`, `flutter run -v` and also if possible, maximum information on the 'JAVA process'(name, exact memory consumption, etc.)

**Comment by Revantark** [comment]
> Can you please provide the outputs of `flutter doctor -v`, `flutter run -v` and also if possible, maximum information on the 'JAVA process'(name, exact memory consumption, etc.)

I have already added. please check the post.

**Comment by sidrao2006** [comment]
Oops! Sorry

**Comment by sidrao2006** [comment]
Ok and if possible, please name the process as well

**Comment by sidrao2006** [comment]
Hey @Revantark ,  are you running your app on a real device and the RAM issue is with your real device right?

**Comment by Revantark** [comment]
> Hey @Revantark , are you running your app on a real device and the RAM issue is with your real device right?

The problem is with my PC/linux , not my phone.
The process name is JAVA.
And i think , its problem with my installed JDK . But couldnt fix it.

**Comment by sidrao2006** [comment]
Sorry, but its not an unnecessary process. Flutter uses java to compile the app. If its not shutting down by itself, try reinstalling jdk

**Comment by sidrao2006** [comment]
And if you are using an emulator, then it will definitely take up RAM

**Comment by TahaTesser** [comment]
Hi @Revantark 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/58298 
Read this https://github.com/flutter/flutter/issues/58298#issuecomment-637424358 
You can read about this [here](https://stackoverflow.com/a/32300657)
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Revantark** [comment]
> Hi @Revantark
> I see there's an open issue addressing the case you described. #58298
> Read this [#58298 (comment)](https://github.com/flutter/flutter/issues/58298#issuecomment-637424358)
> You can read about this [here](https://stackoverflow.com/a/32300657)
> If you disagree, please write in the comments and I will reopen it.
> Thank you

I dont think , this is a normal behaviour as you mentioned there.
The java process after building apk , is waste of RAM. It needs to be killed.
Please reopen the issue..

**Comment by TahaTesser** [comment]
@Revantark 
Pleas check this https://stackoverflow.com/a/32300657
