### ISSUE TITLE
Upgraded to latest version of flutter and now my existing project giving errors

### ISSUE THREAD

**Issue by abhikhedekar4241** [flutter/flutter#63903]
8 warnings generated.
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/fade_scale_transition.dart:148:29: Error: 'decelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
      ).chain(CurveTween(curve: decelerateEasing));
                                ^^^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:315:12: Error: 'decelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
        curve: decelerateEasing,
               ^^^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:321:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
      ).chain(CurveTween(curve: standardEasing));
                                ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:326:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
      ).chain(CurveTween(curve: standardEasing));
                                ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:335:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
            ).chain(CurveTween(curve: standardEasing));
                                      ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:355:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
            ).chain(CurveTween(curve: standardEasing));
                                      ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:402:12: Error: 'accelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
        curve: accelerateEasing,
               ^^^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:408:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
      ).chain(CurveTween(curve: standardEasing));
                                ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:413:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
      ).chain(CurveTween(curve: standardEasing));
                                ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:422:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
            ).chain(CurveTween(curve: standardEasing));
                                      ^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:445:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
            ).chain(CurveTween(curve: standardEasing));

```
```

```
```

```
```
<details>

</details>

**Comment by sidrao2006** [comment]
Please refer to [flutter breaking changes](https://flutter.dev/docs/release/breaking-changes)

**Comment by Abhishek01039** [comment]
hey @sidrao2006 
[ flutter's breaking changes](https://flutter.dev/docs/release/breaking-changes) for 1.17 
hey @abhikhedekar4241  
can you please provide minimal reproduction code and `flutter run -v `?
Thanks

**Comment by iapicca** [comment]
before following @Abhishek01039 good suggestion
could you please run from terminal
```console
cd <your project folder>
flutter create .
```
(don't forget the dot)

**Comment by darshankawar** [comment]
Hi @abhikhedekar4241,
Whenever you upgrade, it's always good to run `flutter pub cache repair` and then `flutter run` to get all latest updates and dependencies. Try that and see if it works for you.
If problem persists, provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by darshankawar** [comment]
> before following @Abhishek01039 good suggestion
> could you please run from terminal
> 
> ```
> cd <your project folder>
> flutter create .
> ```
> 
> (don't forget the dot)

Hey @iapicca :-)

**Comment by abhikhedekar4241** [comment]
Upgrading version of "animations" package (it is provided in flutter itself) worked for me.
I added []((https://pub.dev/packages/animations) dependency in pubspec.yaml
