### ISSUE TITLE
navigating with method callback is not working

### ISSUE THREAD

**Issue by EngAddow** [flutter/flutter#63909]
here is code I want to go sortedResult page when click go button but that doesnt work for me:
```import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: IconButton(
            icon: Icon(Icons.sort),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => SearchResult(),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class SearchResult extends StatefulWidget {
  @override
  _SearchResultState createState() => _SearchResultState();
}

class _SearchResultState extends State<SearchResult> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: IconButton(
          icon: Icon(Icons.sort),
          onPressed: () {
            _showSortOptions(onSort: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => SortedResults()));
              //   BlocProvider<ProductsBloc>(
              //     create: (context) => ProductsBloc()
              //       ..add(SortProducts(
              //           _sortKey, page, _orderKey, widget.query)),
              //     child: SortedResults(),
              //   );
            });
            print('sort');
          },
        ),
      ),
    );
  }

  void _showSortOptions({Function onSort}) {
    showCupertinoModalPopup(
        context: context,
        builder: (context) {
          return Material(
            child: StatefulBuilder(
                builder: (BuildContext context, StateSetter setState) {
              return Container(
                height: 400,
                decoration: BoxDecoration(
                  color: Color(0xffffffff).withOpacity(0.9985939860343932),
                  boxShadow: [
                    BoxShadow(
                        color: Color(0x5d000000),
                        offset: Offset(0, 0),
                        blurRadius: 25,
                        spreadRadius: 0)
                  ],
                ),
                child: GestureDetector(
                  onTap: () {
                    print('sort results');

                    // Navigator.push(
                    //     context,
                    //     MaterialPageRoute(
                    //         builder: (context) => SortedResults()));
                    onSort();
                    Navigator.of(context).pop();
                  },
                  child: Container(
                    margin: EdgeInsets.symmetric(horizontal: 32),
                    alignment: Alignment.center,
                    width: 500,
                    height: 50,
                    decoration: BoxDecoration(
                      color: Color(0xff000000),
                      boxShadow: [
                        BoxShadow(
                            color: Color(0x407c5f3b),
                            offset: Offset(0, 5),
                            blurRadius: 10,
                            spreadRadius: 0)
                      ],
                    ),
                    child: Text("go",
                        style: TextStyle(
                          color: Color(0xffffffff),
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                          fontStyle: FontStyle.normal,
                        )),
                  ),
                ),
              );
            }),
          );
        });
  }
}

class SortedResults extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('jjjjj'),
    );
  }
}
```

flutter doctor -v:
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/addow/Developer/flutter
    • Framework revision bbfbf1770c (3 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/addow/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile)        • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone SE (2nd generation) (mobile) • E50AFF28-BB84-48BE-931E-329079A30EBA • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

**Comment by Abhishek01039** [comment]
hi @EngAddow 
Seems like not a full code!
This is not meant for your personal code assistance 
please ask this question to https://flutter.dev/community
Thanks

**Comment by pedromassangocode** [comment]
Hi @EngAddow 
For the issue to be workable, it needs to be reproducible with a minimal complete code sample that doesn’t include 3rd party plugins or complex production code. Please provide such sample.
Thank you

**Comment by EngAddow** [comment]
Thank you @pedromassangocode & @Abhishek01039  I went yesterday with that problem exist and came back today and run it again without modifying and it worked it's weird behavior really, the same code is working which I tested a lot of times yesterday

**Comment by pedromassangocode** [comment]
Hi @EngAddow 
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
