### ISSUE TITLE
The icon is not a Flutter icon

### ISSUE THREAD

**Issue by qcks** [flutter/flutter#63923]
<img width="633" alt="截屏2020-08-17 上午10 49 03" src="https://user-images.githubusercontent.com/21257035/90353529-081cef00-e079-11ea-958f-91bebc6846e0.png">

Create from the command line,The icon is not a Flutter icon
flutter create --org com.example --template=plugin --platforms=android,ios -a java hello
<img width="344" alt="截屏2020-08-17 上午11 07 40" src="https://user-images.githubusercontent.com/21257035/90353876-1b7c8a00-e07a-11ea-8872-7f897023e999.png">

![image](https://user-images.githubusercontent.com/21257035/90354657-816a1100-e07c-11ea-823f-68df0a1077cd.png)

**Comment by sidrao2006** [comment]
Hey @qcks, Android Studio takes some time to detect and load the project types and sometimes it fails. 
Also if you are creating the project from the terminal, then Android Studio won't have any metadata during the creation that implies that the project is a flutter project

**Comment by qcks** [comment]
Android studio 道阻且长
This problem occurred after I upgraded from flutter SDK 1.12 to 1.20.1.
