### ISSUE TITLE
camera bug  Android6.0 controller.stopVideoRecording() cause  DequeueBuffer: dequeueBuffer failed

### ISSUE THREAD

**Issue by yingqiang006** [flutter/flutter#63928]
camera  
Android6.0
controller.stopVideoRecording()  cause

DequeueBuffer: dequeueBuffer failed
E/CameraDeviceGLThread-0( 1373): Received exception on GL render thread: 
E/CameraDeviceGLThread-0( 1373): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-0( 1373): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-0( 1373): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-0( 1373): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:727)
E/CameraDeviceGLThread-0( 1373): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-0( 1373): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-0( 1373): 	at android.os.Looper.loop(Looper.java:179)
E/CameraDeviceGLThread-0( 1373): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/CameraDeviceState( 1373): Legacy camera service transitioning to state ERROR
I/MediaRecorder( 1373): reset()
E/CameraCaptureSession( 1373): Session 1: Exception while stopping repeating: 
E/CameraCaptureSession( 1373): android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
E/CameraCaptureSession( 1373): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2000)
E/CameraCaptureSession( 1373): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:913)
E/CameraCaptureSession( 1373): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:480)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:290)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:283)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:373)
E/CameraCaptureSession( 1373): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
E/CameraCaptureSession( 1373): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/CameraCaptureSession( 1373): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/CameraCaptureSession( 1373): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/CameraCaptureSession( 1373): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraCaptureSession( 1373): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/CameraCaptureSession( 1373): 	at android.os.Looper.loop(Looper.java:163)
E/CameraCaptureSession( 1373): 	at android.app.ActivityThread.main(ActivityThread.java:5769)
E/CameraCaptureSession( 1373): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 1373): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/CameraCaptureSession( 1373): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
E/RequestThread-0( 1373): Timed out while waiting for request to complete.
W/CaptureCollector( 1373): Preview buffers dropped for request: 1
E/CameraDeviceState( 1373): Cannot receive result while in state: 0
E/CameraDeviceState( 1373): Cannot receive result while in state: 0
E/CameraDeviceState( 1373): Cannot receive result while in state: 0
W/MessageQueue( 1373): Handler (android.graphics.SurfaceTexture$1) {2a61261} sending message to a Handler on a dead thread
W/MessageQueue( 1373): java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {2a61261} sending message to a Handler on a dead thread
W/MessageQueue( 1373): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
W/MessageQueue( 1373): 	at android.os.Handler.enqueueMessage(Handler.java:631)
W/MessageQueue( 1373): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
W/MessageQueue( 1373): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
W/MessageQueue( 1373): 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
W/MessageQueue( 1373): 	at android.os.Handler.sendEmptyMessage(Handler.java:519)
W/MessageQueue( 1373): 	at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:376)
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 1373): [SurfaceTexture-1-1373-4] cancelBuffer: BufferQueue has been abandoned

**Comment by darshankawar** [comment]
Hi @yingqiang006,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by yingqiang006** [comment]
https://github.com/flutter/plugins/pull/1789/commits/a671d8b286a763ab02fe03bd57b6e6f943d4e73c

This solution solved my problem

**Comment by darshankawar** [comment]
@yingqiang006 Good to know.
Closing this issue as solved.

**Comment by JmyW** [comment]
Issue is still there. And the solution "flutter/plugins@a671d8b" is not helping in my case with latest version "_camera 0.7.0+2_". Can anyone help? 

**[Reproduced Steps]**
1. Execute the example code
2. Tap video record icon
3. Tap "stop" icon
4. Program hang for 5 sec then logged message "Unhandled Exception: CameraException(videoRecordingFailed, Operation timed out in camera service)"

**[Source Code]** Just use the example code in GitHub 
https://github.com/flutter/plugins/tree/master/packages/camera/camera/example

[Device] Samsung Galaxy J7 Prime

**[Error Code]**
E/CameraCaptureSession( 5434): Session 2: Failed to create capture session; configuration failed
E/flutter ( 5434): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: CameraException(videoRecordingFailed, Operation timed out in camera service)
E/flutter ( 5434): #0      CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:479:7)
E/flutter ( 5434): <asynchronous suspension>
E/flutter ( 5434): #1      _CameraExampleHomeState.onStopButtonPressed.<anonymous closure> (package:camera_example/main.dart)
E/flutter ( 5434): <asynchronous suspension>

**[Flutter doctor -v]**
[√] Flutter (Channel dev, 1.26.0-17.2.pre, on Microsoft Windows [Version 10.0.18363.1316], locale zh-TW)
    • Flutter version 1.26.0-17.2.pre at C:\flutter
    • Framework revision 79b49b9e10 (2 days ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Jemmy_Wu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM G610Y (mobile) • 5210ff844cbc83f1 • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.
