### ISSUE TITLE
"icon font tree shaking" does not work with IconData subclasses

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#63920]
## Steps to Reproduce

Hi thanks for the wonderful Flutter! In 1.20.0 release there is a new feature "icon font tree shaking". However, I cannot do it in the custom font_awesome_flutter fonts...

1. Run `flutter create bug`.
2. Add [font_awesome_flutter](https://github.com/fluttercommunity/font_awesome_flutter) package as dependency.
3. Observe that it does not do any icon font tree shaking.

Related issue: https://github.com/fluttercommunity/font_awesome_flutter/issues/112 and @michaelspiss

**Expected results:** 
Do tree shaking.

**Actual results:** 
Not do tree shaking.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by awhitford** [comment]
I believe that _tree shaking_ is only done for _release_ builds.  Did you try that?  How are you observing that there was no tree shaking?

**Comment by michaelspiss** [comment]
The test setup was the following:
Based on the example app, the floating action button was removed and the app body replaced by a `Column` with one icon per style in `font_awesome_flutter`. Then `flutter build apk` and `flutter build apk --no-tree-shake-icons` in fluttter stable 1.20.2 were used to create comparable outputs - both produce release builds, but I did recheck with the `--release` flag and the results are the same. Verification was done by looking at the file sizes and opening up the `.apk` file to inspect individual `.ttf`s.

Expected result:
- Material icons are removed completely as they are not used.
- Font awesome `.ttf`s get tree shaken to a couple of bytes, each file only holding the one icon used.

Actual result:
- The material icons `.ttf` is only a couple of bytes in size in the normal, full size in the `--no-tree-shake-icons` build.
- Font awesome `.ttfs` are untouched, all at their original file size, which should not be the case.

**Comment by TahaTesser** [comment]
I can reproduce the issue 
<img width="1077" alt="Screenshot 2020-08-18 at 3 29 04 PM" src="https://user-images.githubusercontent.com/48603081/90499758-9079bd80-e167-11ea-9280-e614ab1793c2.png">


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.21.0-10.0.pre.138 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 3562b3c0de (4 hours ago), 2020-08-18 01:46:02 -0400
    • Engine revision 02de4eb7ce
    • Dart version 2.10.0 (build 2.10.0-37.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (4 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!


```

</details>

**Comment by HansMuller** [comment]
CC @dnfield

**Comment by dnfield** [comment]
There are two unfortunate things happening here:

1. If you specify _no_ icons, we just copy the assets over as-is. We assume that if you didn't want to use it, you wouldn't have included it in the pubspec. This might not be desireable behavior.
1. The FontAwesomeFlutter package _subclasses_ IconData, which we aren't handling very well.

I'm not sure about whether we should fix the first point, or the best way to do so. I believe there are other issues open for that.

For the second point, we definitely should make that work, and I think this issue has the right context to do it.

**Comment by dnfield** [comment]
See e.g. https://github.com/fluttercommunity/font_awesome_flutter/blob/087c07b76c6b7a8a83fb6d7522331a9f2a33a1ec/lib/src/icon_data.dart#L8

**Comment by dnfield** [comment]
Filed https://github.com/flutter/flutter/issues/64106 to track removing assets your app does not refer to - but I suspect we will not be able to fix that anytime soon.

**Comment by dnfield** [comment]
To clarify: the linked change (flutter/engine#20614) will fix this issue _if and only if you reference at least one icon from the font in the Font Awesome package_ - but only for the fonts that actually have referenced icons.

For now, if you need to shake out one of the fonts without referring to it, you need to manually remove it from the package (e.g. create a new package that has only the font you reference).
