### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by darab-singh93** [flutter/flutter#63930]
I am facing this issue with 

path_provider: ^1.6.11
Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale en-IN)

**Comment by P-B1101** [comment]
did you stop app and run it again after add dependency?

**Comment by hamdikahloun** [comment]
@darab-singh93  Please provide more information :
flutter doctor
FYI : Path provider 1.6.11 support Android/iOS/Mac, so Windows not supported

**Comment by darshankawar** [comment]
Hi @darab-singh93,
There's similar open issue describing your case, [46679](https://github.com/flutter/flutter/issues/46679.
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
