### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by salim-lachdhaf** [flutter/flutter#63934]
i'm facing this issue after migrating to support embedding, any solution ?

it works only when i added `SharedPreferences.setMockInitialValues({});` , this is weird !

**Comment by hamdikahloun** [comment]
@salim-lachdhaf Please provide more information : 
flutter doctor
FYI : shared Preferences 0.5.8 support Android/iOS/WEB/Mac/Linux, so Windows not supported

**Comment by salim-lachdhaf** [comment]
```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [version 6.1.7601], locale fr-FR)
    • Flutter version 1.20.2 at E:\SDK\FlutterSDK
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\SDK\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\SDK\Android\Sdk
    • ANDROID_SDK_ROOT = E:\SDK\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM T813 (mobile)             • 64fd402f04e9bba0 • android-arm64 • Android 7.0 (API 24)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by hamdikahloun** [comment]
@salim-lachdhaf you build for Android or iOS ?

**Comment by salim-lachdhaf** [comment]
for android

**Comment by darshankawar** [comment]
Hi @salim-lachdhaf,
Can you please elaborate when you say `migrated to support embedding` ? Also provide a minimal complete reproducible code sample along with `pubspec.yaml` that shows the issue.
Thanks.

**Comment by salim-lachdhaf** [comment]
i solved the issue by adding     `SharedPreferencesPlugin.registerWith(registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))`
 in the `MainActivity` in the same way as the example

**Comment by darshankawar** [comment]
@salim-lachdhaf Glad to know it's fixed.
Given your last message, I feel safe to close this issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by aMarFlo** [comment]
i have the same issue, and i tried to add SharedPreferencesPlugin.registerWith(registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")) but the method registrarFor didn't found it
