### ISSUE TITLE
flutter create template is not hot-reload compatible

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6394]
```
void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new FlutterDemo(),
    ),
  );
}
```

If you try changing the primarySwatch from blue to red and hot reloading it will ignore the change.  I suspect this is expected, and it's possible that we want to keep the `flutter create` template this way, just noticed it while playing with a new project.

@Hixie @johnmccutchan

**Comment by sethladd** [comment]
I'd love to better understand why hot reload wouldn't pick this up. When we trigger a rebuild, where does that start from? runApp() ?

**Comment by abarth** [comment]
Hot reload doesn't re-execute main.  The simple fix is to move the "new MaterialApp" code into a widget.

**Comment by sethladd** [comment]
Good point.

**Comment by Hixie** [comment]
Yeah when I was playing with this yesterday I just did this:

```dart
void main() {
  runApp(new App());
}

class App extends StatelessWidget {
  App({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: new FlutterDemo(),
    );
  }
}
```

**Comment by johnmccutchan** [comment]
The new template is much nicer. I believe this is fixed.

**Comment by lordgreg** [comment]
I've spent last hour figuring why this isn't updating. :) 

This should definitely be added to the docs.

**Comment by zoechi** [comment]
@lordgreg https://flutter.io/hot-reload/#limitations

**Comment by Akiat** [comment]
Just in case someone have the same "issue" as mine:

If your theme is defined in a static class, it will not be reloaded.

E.g:

theme.dart
```dart
class Themes {
  static ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    visualDensity: VisualDensity.adaptivePlatformDensity,
    fontFamily: "Raleway",
    primaryColor: MAIN_COLOR,
    accentColor: Colors.white,
  );
}
```

main.dart
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Routes initializations
  final router = FluroRouter();
  Routes.configureRoutes(router);
  Application.router = router;

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: Application.router.generator,
      initialRoute: Routes.splashscreen,
      debugShowCheckedModeBanner: false,
      title: APP_NAME,
      theme: Themes.darkTheme, // <- If you change something in this theme, the changes will not be taken into account.
    );
  }
}
```

This is not a bug, but I just want to add this here if anyone asks the question.

The solution is as simple as doing your tests with a non-static theme.
