### ISSUE TITLE
[Feature Request] Adding Official Support for Flutter Apps in Firebase console

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#63947]
I am suggesting to work with the Firebase team to make Flutter officially supported in Firebase. Don't get me wrong, Flutter is now supported as a secondary thing. Not as Unity is supported for example.

What I mean is having Flutter a new way of adding Firebase, like a new way just for Flutter. 

<img src="https://i.imgur.com/NBv0eYm.png" />

In the photo above you can see a choice for Unity, Why not have a choice for Flutter?

Plus the documentation for Flutter is so weak, not up to date, and not in all services.

**Comment by pedromassangocode** [comment]
Hi @YazeedAlKhalaf 
From what I can see, the issue/feature request is not related to Flutter itself. I suggest you to fill the following form to send a feature request to the Firebase team: https://firebase.google.com/support/troubleshooter/report/features.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
