### ISSUE TITLE
[Feature Request] SurfaceTexture Widget for flutter

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#63949]
## Use case

As you know with SurfaceTexture widget we will be able to get the real time frames that are being drawn to surface texture. Like in case of video_player, currently it uses Texture widget and we are unable to grab real time frames that are being drawn. 

With real time video frames acccess, we can use it to process frame data with deep learning stuff such as object detection.
Also this will solve the major issue of video_player that is on some android devices, the texture widget goes out of parent widget based on video aspect ratio because repaint is being taken care at backend and flutter has no access to painting of texture widget. This can be solved if video_player would use a Surface widget instead of Texture widget.

## Proposal

> i wish flutter implements a new *__SurfaceTexture__* widget, where we can have access to *__SurfaceTexture.OnFrameAvailableListener__* just like on android java. There we can grab real time video frames from player as raw image data and can manipulate the pixels and apply Machine learning on those frames. Currently i cant find any other solution to grab real time video frames from a *__local storage video__* that *__video_player__* is playing.

**Comment by nehaaaa6** [comment]
mport 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:video_player/video_player.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final cameras = await availableCameras();
  final camera = cameras.first;
  runApp(MyApp(camera: camera));
}

class MyApp extends StatefulWidget {
  final CameraDescription camera;

  MyApp({Key? key, required this.camera}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late VideoPlayerController _controller;
  late CameraController _cameraController;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/sample_video.mp4')
      ..initialize().then((_) {
        _controller.play();
        setState(() {});
      });
    _cameraController = CameraController(widget.camera, ResolutionPreset.high);
    _cameraController.initialize().then((_) {
      _cameraController.startImageStream((CameraImage image) {
        // Process image data here
      });
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    _cameraController.stopImageStream();
    _cameraController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            SizedBox.expand(
              child: FittedBox(
                fit: BoxFit.cover,
                child: SizedBox(
                  width: _controller.value.size.width,
                  height: _controller.value.size.height,
                  child: VideoPlayer(_controller),
                ),
              ),
            ),
            Positioned.fill(
              child: AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                child: CameraPreview(_cameraController),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by jonahwilliams** [comment]
This is already available via the Texture widget and the native TextureRegistry.
