### ISSUE TITLE
Jetbrains OpenJDK.exe didn't closed after exiting Android Studio or Visual Studio Code

### ISSUE THREAD

**Issue by tomazx** [flutter/flutter#63945]
After building or debugging an app, OpenJDK is opened to build to Android APK's
So, after exiting/closing Android Studio or Visual Studio Code the OpenJDK.exe still remains in RAM
Hope this OpenJDK closed too after exiting IDE
Thanks

**Comment by Revantark** [comment]
> After building or debugging an app, OpenJDK is opened to build to Android APK's
> So, after exiting/closing Android Studio or Visual Studio Code the OpenJDK.exe still remains in RAM
> Hope this OpenJDK closed too after exiting IDE
> Thanks

Same issue here.
A java process runs in background ,even when it is unnecesary .
 Post your "flutter run -v" here.

**Comment by TahaTesser** [comment]
Hi @tomazx 
I see there are issues addressing the case you described.  https://github.com/flutter/flutter/issues/58298   https://github.com/flutter/flutter/issues/63905
You can read about this [on stackoverflow](https://stackoverflow.com/a/32300657)  and also java process ins't related to flutter itself 
If you disagree, please write in the comments and I will reopen it.
Thank you
