### ISSUE TITLE
[google_sign_in]No option to request Refresh token

### ISSUE THREAD

**Issue by fayaz07** [flutter/flutter#63954]
```https://pub.dev/packages/google_sign_in```
I would like to have refresh-token by adding `access_type:offline` header while I sign in to the google account, so that I can manage the refreshing of token and all other stuff.

**Comment by darshankawar** [comment]
Hi @fayaz07,
There's similar open issue describing your case, [15796](https://github.com/flutter/flutter/issues/15796).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by fayaz07** [comment]
Hi @darshankawar , thanks for the update
