### ISSUE TITLE
Error upgrade flutter

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#6395]
This is the log when i try to upgrade.
Switching to from alpha to master...
Upgrading Flutter from /Users/arcas/Desktop/flutter...
fatal: Not possible to fast-forward, aborting.
Building unlinked bundles for flutter...             2.1s
Building unlinked bundles for flutter_driver...      0.1s
Building unlinked bundles for flutter_markdown...    0.0s
Building unlinked bundles for flutter_sprites...     0.1s
Building unlinked bundles for flutter_test...        0.1s
Building unlinked bundles for flutter_tools...       0.3s
Building unlinked bundles for playfair...            0.0s
Building unlinked bundles for sky_engine...          0.0s
Building unlinked bundles for sky_services...        0.2s

**Comment by eseidelGoogle** [comment]
The Flutter SDK uses `git`, it's likely that you have modifications to your sdk at `/Users/arcas/Desktop/flutter`.

You can try:
```
cd /Users/arcas/Desktop/flutter
git status
```
to see what modifications you have.

Probably `flutter upgrade` should give you a better error message here and/or help you understand what to do.

**Comment by arcas0803** [comment]
I have use flutter upgrade and thats the output of the console.
I also use git and these is the output:
```
On branch alpha
Your branch and 'origin/alpha' have diverged,
and have 1 and 200 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   examples/hello_services/android/app/build.gradle
	modified:   examples/stocks/lib/stock_list.dart
	modified:   examples/stocks/lib/stock_row.dart

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	packages/flutter/unlinked.ds
	packages/flutter/unlinked_spec.ds
	packages/flutter_driver/unlinked.ds
	packages/flutter_driver/unlinked_spec.ds
	packages/flutter_markdown/unlinked.ds
	packages/flutter_markdown/unlinked_spec.ds
	packages/flutter_sprites/unlinked.ds
	packages/flutter_sprites/unlinked_spec.ds
	packages/flutter_test/unlinked.ds
	packages/flutter_test/unlinked_spec.ds
	packages/flutter_tools/unlinked.ds
	packages/flutter_tools/unlinked_spec.ds
	packages/playfair/unlinked.ds
	packages/playfair/unlinked_spec.ds

no changes added to commit (use "git add" and/or "git commit -a")
```
My question is if i'm going to have to upgrade via git or if is a possible solution to do with flutter commands.

**Comment by eseidelGoogle** [comment]
The flutter commands wouldn't know how to help you here, since you've made modifications to the flutter repository itself.  It's not clear that we should be using `git` as our sdk vending solution, but that's what we have for now. ;)

To move forward, I would do `git diff` and decide if you care about these changes.

If you do:
```
git add examples
git commit -m "my local changes"
```
Will turn them into a commit so that `flutter upgrade` can successfully rebase for you, although honestly I'd run `git pull --rebase` manually as you could have conflicts you might want to resolve yourself.

If you don't want the changes, you can do `git reset --hard` to delete them all, or `git checkout HEAD path/to/changed/file` to reset one file at a time.

Hope that helps?

**Comment by eseidelGoogle** [comment]
I should note that your checkout is also on the older `alpha` branch, I believe `flutter upgrade` should know how to move you to `master` which is much more current.

**Comment by arcas0803** [comment]
`git rebase -a` 
Solve the problem.
Thanks so much. Flutter is awesome.
