### ISSUE TITLE
My problem is the login

### ISSUE THREAD

**Issue by Elian28** [flutter/flutter#63958]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
Hi @Elian28 
can you please provide `flutter run -v`, `flutter doctor -v` and, minimal reproduction code?
Thanks
