### ISSUE TITLE
[package_info] Installer information

### ISSUE THREAD

**Issue by mamm26** [flutter/flutter#63961]
Hi,

The installer information is necessary in this plugin.

Android: https://developer.android.com/reference/android/content/pm/PackageManager#getInstallerPackageName(java.lang.String)
iOS: ?

Thanks.

**Comment by TahaTesser** [comment]
Hi @mamm26 
Can you please provide more details? i don't see installer information. Are you suggesting it should be implemented for both platforms? 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by caiopo** [comment]
Hey, I had a similar requirement recently and couldn't find any package that made this, so I made my own.

Here it is: https://pub.dev/packages/installer_info

If you decide to use it and face any issues, please let me know. Thanks!
