### ISSUE TITLE
[recipes] the recipes repo should have a CQ check that enforces YAPF

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#63967]
The flutter.googlesource.com/recipes repo should have a CQ check that validates all python files adhere to YAPF.

**Comment by godofredoc** [comment]
Recipes changes was added here:
  https://flutter-review.googlesource.com/c/recipes/+/5804

**Comment by godofredoc** [comment]
Changes to run as experimental have been applied. We'll wait for the experimental results before moving the recipe to prod and close this bug.
