### ISSUE TITLE
pacakge:flutterapp/a.dart (flutter beginner)

### ISSUE THREAD

**Issue by msorange19** [flutter/flutter#63962]
import 'package:flutter/material.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart';
import 'package:flutterapp/a.dart';

void main() => runApp(MaterialApp(home: BottomNavBar()));

class BottomNavBar extends StatefulWidget {
  @override
  _BottomNavBarState createState() => _BottomNavBarState();
}

class _BottomNavBarState extends State<BottomNavBar> {
  int _page = 0;
  GlobalKey _bottomNavigationKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        bottomNavigationBar: CurvedNavigationBar(
          key: _bottomNavigationKey,
          index: 0,
          height: 50.0,
          items: <Widget>[
            Icon(Icons.add, size: 30),
            Icon(Icons.list, size: 30),
            Icon(Icons.compare_arrows, size: 30),
            Icon(Icons.call_split, size: 30),
            Icon(Icons.perm_identity, size: 30),
          ],
          color: Colors.white,
          buttonBackgroundColor: Colors.white,
          backgroundColor: Colors.blueAccent,
          animationCurve: Curves.easeInOut,
          animationDuration: Duration(milliseconds: 600),
          onTap: (index) {
            setState(() {
              _page = index;
            });
          },
        ),
        body: Container(
          color: Colors.blueAccent,
          child: Center(
            child: Column(
              children: <Widget>[
                Text(_page.toString(), textScaleFactor: 10.0),
                RaisedButton(
                  child: Text('Go To Page of index 1'),
                  onPressed: () {
                    final CurvedNavigationBarState navBarState =
                        _bottomNavigationKey.currentState;
                    navBarState.setPage(1);
                  },
                )
              ],
            ),
          ),
        ));
  }
}

**Comment by msorange19** [comment]
![image](https://user-images.githubusercontent.com/47300623/90415469-ef412780-e0d2-11ea-82ca-5bd5499d6d5f.png)

**Comment by Abhishek01039** [comment]
hi @msorange19 
what is `import 'package:flutterapp/a.dart';` ?
this is your file I mean `a.dart` file?

**Comment by msorange19** [comment]
> hi @msorange19
> what is `import 'package:flutterapp/a.dart';` ?
> this is your file I mean `a.dart` file?

yes. i have created another file in lib. i like to add that page with this page.
![image](https://user-images.githubusercontent.com/47300623/90416258-10564800-e0d4-11ea-94b4-23bfd86c16af.png)

**Comment by msorange19** [comment]
@Abhishek01039 bro, i have seen in one tutorial that he has added import 'package:flutterapp/newpage.dart'. But it is showing error for me
![image](https://user-images.githubusercontent.com/47300623/90416947-ed786380-e0d4-11ea-863b-38ff028228dc.png)

**Comment by Abhishek01039** [comment]
what is your project name `flutterapp` ?

**Comment by msorange19** [comment]
navbar

**Comment by Abhishek01039** [comment]
so import like `package:navbar/a.dart`.

**Comment by msorange19** [comment]
thank you so much. i got it.

**Comment by Abhishek01039** [comment]
so now you can close it 
Thanks

**Comment by Abhishek01039** [comment]
Hi @TahaTesser
This issue is solved so can you please close the issue?
Thanks.
