### ISSUE TITLE
Add ability to provide selectableDayPredicate for showDateRangePicker

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter/flutter#63973]
## Use case

It will be good to have the ability to specify the max selectable range. But it's a less flexible solution since it won't allow to manage available date for selection during `startDate` selection. `selectableDayPredicate` allows to manage selectable range in a more efficient way

## Proposal

Add ability to specify `selectableDayPredicate`

`selectableDayPredicate`, compared to the regular date picker, can also receive selected start date value as an optional argument. Also during the selection of the date range, it can validate the selected period against `selectableDayPredicate` to ensure that range doesn't contain disabled items.

**Comment by HansMuller** [comment]
CC @rami-a @darrenaustin

**Comment by darrenaustin** [comment]
We did think about adding this feature, but is does complicate the UI to support this. We could allow the user to only select start and end dates that pass the predicate the same way we handle this in the single date picker case. However, what if there are unselectable dates between a valid start and end date? How do we show the user that they are trying to select an invalid date range?

**Comment by TatsuUkraine** [comment]
@darrenaustin yeah, was thinking about this issue as well. The primary issue that I faced for instance - the ability to limit the max range.

> However, what if there are unselectable dates between a valid start and end date? How do we show the user that they are trying to select an invalid date range?

I didn't dive into the code. So hard to say if it's possible but I see 2 probable solutions:
- don't allow to select End date, if at least one date between Start date and End date is disabled
- if the start date is selected, user click on potential End date, and if at least one date between Start date and clicked End date is disabled - the selection of End date become a selection of Start date

**Comment by TatsuUkraine** [comment]
both solutions will allow not just disable dates in the date picker, but also manage max range, for instance after start date is selected predicate will be invoked with 2 params: predicate date and selectedStartDate. So it will allow dev to disable everything after some date, based on his requirements (aka max range)

**Comment by TatsuUkraine** [comment]
just to make it clear - I was thinking that `selectedStartDate` for predicate could be nullable (optional), which will be null if no start date is selected

**Comment by TatsuUkraine** [comment]
> I didn't dive into the code. So hard to say if it's possible but I see 2 probable solutions:
>
> - don't allow to select End date, if at least one date between Start date and End date is disabled
> - if the start date is selected, user click on potential End date, and if at least one date between Start date and clicked End date is disabled - the selection of End date become a selection of Start date

There might be 3 option - disable all dates greater than the disabled date by the predicate AND greater than selected start date

**Comment by darrenaustin** [comment]
> I didn't dive into the code. So hard to say if it's possible but I see 2 probable solutions:
> 
> * don't allow to select End date, if at least one date between Start date and End date is disabled

That was my first thought as well, but might have performance issues. It means for every date that is displayed we need to check every date between itself and the selected start date to see if we need to disable it as an end date.

> * if the start date is selected, user click on potential End date, and if at least one date between Start date and clicked End date is disabled - the selection of End date become a selection of Start date

To me this would be a confusing user experience. If I am trying to select a range and don't realize there is an disabled date between the selected start date and the one I am tapping on, then I would have no idea why the start date suddenly moved to the tapped date.

**Comment by TatsuUkraine** [comment]
> To me this would be a confusing user experience. If I am trying to select a range and don't realize there is an disabled date between the selected start date and the one I am tapping on, then I would have no idea why the start date suddenly moved to the tapped date.

Agreed, then - probably best solution could be 3 option from my last comment))

> disable all dates greater than the disabled date by the predicate AND greater than selected start date

**Comment by TatsuUkraine** [comment]
like an option, it may work in the following way:
- `selectableDayPredicate` will have same signature is in regular date picker, and will be invoked only when no date selected yet
- `maxRangeDuration` getter, that will be invoked when the start date is selected, and all dates outside of this duration (basically all dates greater than startDate + duration) will be disabled

**Comment by darrenaustin** [comment]
I'm thinking a simpler solution would be adding a new `selectableDateRangePredicate` that would allow the app to control which ranges are valid. Something like:

```dart
typedef SelectableDateRangePredicate = bool Function(DateTimeRange range);
```

This can be used by the picker to check each displayed date for select-ability by the app. If a start date is selected, then for each displayed date it would check against the predicate with a range of `start date`-`date`. If no start date has been selected then the range would just be `date`-`date`.

This would allow the app to just check against specific dates, or enforce a max number of days in the range, or any other criteria they choose.

There might be some issues with performance if the app does some heavy calculations in this predicate, but that would be no different than the single date picker's predicate.

**Comment by GusRodrigues86** [comment]
@darrenaustin this solution, from what I can see (and what I had implemented) would help to provide some "fixed range date pickers", like, week date range picker.

**Comment by Sam3077** [comment]
I began working on this a bit before finding this issue. My solution still uses the `SelectableDayPredicate` to identify which days should be selectable and it highlights those dates if they're included in a date range selection. Although this method doesn't serve the use case of limiting the number of selected days, it does offer a fairly intuitive UI that makes it easier to see what days can and can't be selected. Here's a video of my work so far:

https://user-images.githubusercontent.com/25106528/104074862-713f0380-51ce-11eb-8b75-5111f41c10d7.mov

I'd love to hear your thoughts and feedback!

**Comment by joymyr** [comment]
Has there been any progress on this? In many use cases the showDateRangePicker won't be usable without a selectableDayPredicate. The solution from @Sam3077 looks great, and is the most userfriendly one.

**Comment by Chuckame** [comment]
Regarding what as been said

> disable all dates greater than the disabled date by the predicate AND greater than selected start date

Why not just disabling all the dates after the next non selectable date? That way, there isn't any magic unwanted range switching, and it would respect the main sense of non selectable date: not able of including a non selectable date into a selected range. I'll try to provide an example soon.

I'm thinking about a missing key feature: what about inclusive end dates? Like Airbnb, if you cannot select the 15th day of the month as a start date, you can select it as the last date of the range.

**Comment by Chuckame** [comment]
Here an example, disabling all the days beginning from the next non-selectable day:
 
https://github.com/flutter/flutter/assets/16419143/86748f78-acae-4126-89aa-35c93d94a9ec

**Comment by Chuckame** [comment]
Here the example for including the next non selectable day:


https://github.com/flutter/flutter/assets/16419143/2a2be325-1e2f-470c-8b17-b4ed5b2ad43e

**Comment by tvolkert** [comment]
Is this the same as https://github.com/flutter/flutter/issues/637?

**Comment by TatsuUkraine** [comment]
@tvolkert Sort of, current ticket for date range picker
