### ISSUE TITLE
Document our plugin message system

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6397]
Including in particular conventions around channel (message) names.

**Comment by eseidelGoogle** [comment]
We have some minimal docs at flutter.io/platform-services.  @mit-mit likely plans some updates as part of our current plugin work.

**Comment by mit-mit** [comment]
@Hixie can you elaborate on what you mean by channel name conventions?

**Comment by Hixie** [comment]
For example, the `flutter/platform` channel has a `Clipboard.setData` method. Do we document that anywhere? Or even up one level, do we document that channel names should be of the form `foo/bar` or methods of the form `Foo.bar`?

**Comment by mit-mit** [comment]
Note to self: Include this in the doc update for next week.

Concrete sample:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/clipboard.dart
```
const String _kChannelName = 'flutter/platform';

  static Future<Null> setData(ClipboardData data) async {
    await PlatformMessages.invokeMethod(
       _kChannelName,
      'Clipboard.setData',
      ...
```

**Comment by sethladd** [comment]
Our recent event showed that developers want to know more about the plugin system, how it works, how to try it, etc.

**Comment by Hixie** [comment]
cc @abarth who was asking about whether these conventions are documented.
