### ISSUE TITLE
NestedScrollView is NOT scrolling the header first and then body at all times [web]

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#63978]
## Steps to Reproduce

1. Run `min repro code`.
2. It's a little hard to reproduce—you have to play with the thumb to get the sense of when the issue is being reproduced. I used the same `min repro code` for both, the expected and the actual results.

**Expected results:** 
![ezgif-6-540037f13176](https://user-images.githubusercontent.com/25743901/90429263-46d49880-e0bd-11ea-8066-a438afda0ea5.gif)

**Actual results:** 
![ezgif-6-2a8bcb01d929](https://user-images.githubusercontent.com/25743901/90429334-6d92cf00-e0bd-11ea-97a2-351560f06ad9.gif)

<details>
<summary>min repro code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  TabController _tabController;
  ScrollController _scrollViewController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: 2);
    _scrollViewController = ScrollController(initialScrollOffset: 0.0);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _scrollViewController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        controller: _scrollViewController,
        headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 500,
              title: Text('Tab Controller Example'),
              pinned: true,
              floating: true,
              forceElevated: boxIsScrolled,
              bottom: TabBar(
                tabs: <Widget>[
                  Tab(
                    text: "Home",
                    icon: Icon(Icons.home),
                  ),
                  Tab(
                    text: "Example page",
                    icon: Icon(Icons.help),
                  )
                ],
                controller: _tabController,
              ),
            )
          ];
        },
        body: TabBarView(
          children: <Widget>[
            PageOne(),
            PageTwo(),
          ],
          controller: _tabController,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.control_point),
        onPressed: () {
          _tabController.animateTo(1,
              curve: Curves.bounceInOut, duration: Duration(milliseconds: 10));
          _scrollViewController
              .jumpTo(_scrollViewController.position.maxScrollExtent);
        },
      ),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemExtent: 250.0,
      itemBuilder: (context, index) => Container(
        padding: EdgeInsets.all(10.0),
        child: Material(
          elevation: 4.0,
          borderRadius: BorderRadius.circular(5.0),
          color: index % 2 == 0 ? Colors.cyan : Colors.deepOrange,
          child: Center(
            child: Text(index.toString()),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on Mac OS X 10.15.3 19D76, locale es-ES)
    • Flutter version 1.21.0-10.0.pre.114 at /Users/tomasbaran/dev/flutter
    • Framework revision b2c0970aa7 (32 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 3 categories.
```

</details>

**Comment by markusaksli-nc** [comment]
Hi @tomasbaran 
Can you please provide a sample that doesn't include references to assets and produces the same behavior as in your gifs? I can't reproduce with this one.
Thank you

**Comment by tomasbaran** [comment]
@markusaksli-nc not necessary. I know that I didn't include the assets but don't worry about it, that does NOT matter. Just open up the second tab (Example page), that's where the issue happens on. Adding assets would NOT change a thing, just a waste of time on my end since the issue does NOT happen on the first tab, but on the second one. 

I hope, it makes sense.

As I said in my original post, you really have to play with your thumb. It happens maybe 5% of the time, depending on how you slide. You have to sort of accelerate your thumb slide and then release your finger from the screen. I just recorded a video so you know how: https://youtu.be/5E-E0R_pvPE

**Comment by markusaksli-nc** [comment]
I meant the overscroll you have in the gif. It seems like that is missing from the repro code. I tried with the current sample but couldn't reproduce at all.

**Comment by tomasbaran** [comment]
@markusaksli-nc I have no idea what you mean. Assets are present only in the first tab view (home page).

You must be able to reproduce at least the `actual example` @pedromassango (https://github.com/flutter/flutter/issues/63948) was able to do it, I was able to do it, I have no idea what's wrong on your side. If you are unable to reproduce it, maybe pass it to @pedromassango, he was able to run the build without any problems.

**Comment by markusaksli-nc** [comment]
I am talking about the overscroll indicator you seem to have that significantly increases the distance the header can scroll.
<img src="https://user-images.githubusercontent.com/25743901/90429263-46d49880-e0bd-11ea-8066-a438afda0ea5.gif" height="400" /> Versus what we see <img src="https://user-images.githubusercontent.com/68219924/90522271-2d425800-e174-11ea-81c5-80cf91549c2f.gif" height="400" />

This seems like it would make reproducing the issue much simpler. I already removed the references to the assets from your code. I'm also able to reproduce the desktop scrolling issue. I can't reproduce this mobile inertia issue you are talking about here.

**Comment by pedromassangocode** [comment]
Hi @tomasbaran 
On what iOS version are you having this issue?

**Comment by tomasbaran** [comment]
@markusaksli-nc I see, now I know what you mean. Sorry, my bad. I forgot to add to the `min repro code` this line:

`expandedHeight: 500,` in the `SliverAppBar`. I just fixed it in my original post, please check it out again and accept my apologies.

@pedromassango good point. First off, this is a [web] specific issue probably. Or maybe not only, but that's the platform I was testing.

Second, I didn't think it could have to do with the OS but it looks like it does. I was NOT able to reproduce the issue on web on Android. I was able to reproduce the issue on iOS 12,14 both on Safari and on Chrome browsers.

**Comment by tomasbaran** [comment]
Btw, this may look like a minor bug BUT in certain cases like in mine right now, it can totally break user experience:

https://youtu.be/jP0ys9nbDYs 

I'm not publishing all the code since it's a little complex but I'm using `NestedScrollView` and that's what happens when it is NOT scrolling properly.

**Comment by markusaksli-nc** [comment]
@tomasbaran no worries, happens to the best of us. Are those iOS devices physical or emulator? I wasn't able to repro this and I'll be OOO for a while. @pedromassangocode can you try the new repro code out?

**Comment by pedromassangocode** [comment]
@markusaksli-nc I tried the new repro code on Android, iOS 13.6 and Chrome and was unable to reproduce this issue. Worth noting that this is a totally different of https://github.com/flutter/flutter/issues/63948.

**Comment by tomasbaran** [comment]
@markusaksli-nc Thanks for your kind words. I reproduced this issue on the real device.

@pedromassango I'm not sure what you mean on Chrome. The issue is reproducible only when build for web and ran on Safari/Chrome browser on a real iOS device.

Trying to reproduce this issue on Android is a waste of time since I was NOT able to reproduce it on Android myself either and I know how to reproduce it on iOS. Please, give it a try it's a BIG issue in my opinion as it gives you flickering. You just really have to play with your finger since it happens about 5% of the time but enough to be seen broken or buggy. You kinda have to accelerate your finger fast. Try to mimic what I did in the video.

**Comment by pedromassangocode** [comment]
Hi @tomasbaran 
Ok, after spending some twenty minutes, I was able to reproduce this issue on latest `master` channel.

This is very difficult to reproduce since it doesn’t happens all the time, so I wasn’t able to record a video about it, But as you can see in the image, the `header` is not fully collapsed but the `body` already started scrolling.

**Actual:** `body` started scrolling before the `header` is not fully collapsed

<img width="713" alt="Screen Shot 2020-08-21 at 08 37 31" src="https://user-images.githubusercontent.com/67424416/90865282-0f4e4080-e38a-11ea-897a-dfbed80f0090.png">

**Expected:** body doesn’t start scrolling before `header` is fully collapsed

<img width="713" alt="Screen Shot 2020-08-21 at 08 41 25" src="https://user-images.githubusercontent.com/67424416/90865588-7966e580-e38a-11ea-8b8c-aed1f648f3cc.png">


<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.212, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.212 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision eef4220a87 (7 hours ago), 2020-08-20 17:46:07 -0700
    • Engine revision 4dc866283d
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by goderbauer** [comment]
Could be an issue with the NestedScrollVIew (cc @Piinks). Was anybody able to reproduce this in a native iOS app (not web)?

I just tried to reproduce this on the web and failed. In order to investigate it we probably need a more reliable way of reproducing it.

**Comment by tomasbaran** [comment]
@goderbauer I'm not sure about iOS - haven't tried it yet. I may have more time to do that next week.

As for reproducing the issue, if you read carefully the comments above, you'll be able to reproduce it, although I do admit will take some time to learn how to achieve it. To put it very simply, you just have to scroll really fast and release your finger/thumb from the screen asap (before the header reaches top of the screen)

**Comment by Piinks** [comment]
This really really tricky to reproduce, but I have a video of it here on an iOS simulator:

![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/16964204/91599933-edb9ff80-e91b-11ea-9804-9e45fc5838d6.gif)

It took a bunch of tries to get it. It happens when you apply a really fast and short flinging gesture. I am guessing the issue here might be with the ballistic activity that is happening in this case when the gesture is released. I'm going to see if I can trim down the code sample further to eliminate other widgets.

**Comment by Piinks** [comment]
I was able to narrow it down and reproduce with this code below. I definitely think this is a ballistic activity error in the NestedScrollView.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyHomePage());

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                expandedHeight: 500,
                title: Text('Demo'),
              )
            ];
          },
          body: PageTwo(),
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemExtent: 200.0,
      itemBuilder: (context, index) => Container(
        padding: EdgeInsets.all(10.0),
        child: Material(
          color: index % 2 == 0 ? Colors.cyan : Colors.deepOrange,
          child: Center(
            child: Text(index.toString()),
          ),
        ),
      ),
    );
  }
}
```

**Comment by tomasbaran** [comment]
Thank you @Piinks You are awesome!!! :)
