### ISSUE TITLE
APK crashes on startup after signing it with Google Play

### ISSUE THREAD

**Issue by yousifAlneamy** [flutter/flutter#63989]
Hi, I've built an update of my app and the generated release APKs are working fine when installing them on my device. However, after uploading to Google Play Consol and then use the APK signed by Google Play, the app crashes immediately on startup and I have tested it on different phones and the same problem appears.

The APKs which are signed with my private key are working fine.

Google Play: If I don't remove the older version of my app and then update, the app works fine. If I clean the app data & cache (From "App Info") and then uninstall and use the google play version. The app won't work and crashes.

The most confusing thing, If I make a new install (not update) of the app from Google Play and then wait and try to open it later, it may work and never face this problem with this app. Also, if the app keeps crashing after trying to open it for a while, just restart the device and then open the app, it will work as nothing had happened.

**Not weird enough?** install the app that is signed by Google Play without even bothering to open it and then restart the device without having to be connected (online). The app works fine.

The problem happens with APKs and bundle

**UPDATE: this problem only happens with specific ISP provider.** 

Do you want to check the app yourself? Give an email address and will send it to you.

I'm on the `Stable Channel` (**1.20.2**). I can't provide my `flutter doctor -v` because I'm switching to `Beta Channel` and my connection speed is 60KB right now.

`flutter doctor -v` from my previous posts

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IQ)
    • Flutter version 1.17.1 at /Users/yousif/development/flutter
    • Framework revision f7a6a7906b (10 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yousif/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2
```

**Comment by yousifAlneamy** [comment]
Update: this prob

**Comment by TahaTesser** [comment]
Hi @yousifAlneamy 
As you mentioned with only happens with " specific ISP provider" so how it work when you run the app with signed APK?
Can you please provide your `flutter doctor -v` **updated**, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
