### ISSUE TITLE
Prioritize scheduling devicelab tests that have recently failed to reopen the tree faster

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#64007]
## Use case

If a commit merges and fails one devicelab test (even legitimately, because of a regression and not a flake) the tree will close. When the commit is reverted, as soon as that one test passes, the tree will reopen.

## Proposal
Prioritize running tests that recently failed to reopen the tree faster.

**Comment by keyonghan** [comment]
This has been implemented.
