### ISSUE TITLE
Flutter daemon prints incorrect timing for hot reload

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#6400]
This is difficult to reproduce because you need to type (or paste) the correct json into the Flutter daemon. It is actually quite difficult to reproduce. I never saw the hot reload time printed to the console while manually controlling the daemon. I tried many times. Finally, I went back to IntelliJ and tried again. Everything worked perfectly, and the time was printed as expected. So, this is an intermittent issue. But, once it starts happening it seems to be repeatable, in my limited experience.
1. Start an app.
2. Make it do hot reload.
3. Make note of the log messages.
4. Make it do a restart.
5. Make another note of the log messages.

In the first set of log messages you'll see that it reports the number of libraries that got reloaded.

At the end of the second set of log messages you'll see the amount of time required to do the hot reload. If you wait 10s or so between issuing the reload and the restart then the reload time will be reported with 10s+ too much time.

**This would look bad in a demo.** IMO, of course.

Here're some sample commands. You'll need to use your own device ID and app ID, and project directory.

``` json
[{"method":"app.start","params":{"deviceId":"00ef792d109d24ac","projectDirectory":".../flutter/myapp","startPaused":true,"mode":"debug","target":"lib/main.dart","hot":true},"id":1}]
[{"method":"app.restart","params":{"appId":"dcfa8cd3-cd56-460f-b09a-20fd329606e2","fullRestart":false},"id":3}]
[{"method":"app.restart","params":{"appId":"dcfa8cd3-cd56-460f-b09a-20fd329606e2","fullRestart":true},"id":4}]
```

**Comment by stevemessick** [comment]
It may be that the first Hot Reload works as expected but subsequent ones have the timing message delayed.

**Comment by stevemessick** [comment]
More data. Here's the json output printed by the daemon when IntelliJ told it to do a hot reload followed by a restart. Note that the response from the hot reload does not appear until after the response from the restart.
```json
[{"method":"app.restart","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","fullRestart":false},"id":23}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Syncing files to device...","progress":true,"id":"2"}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","progress":true,"id":"2","finished":true}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Performing hot reload...","progress":true,"id":"3"}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","progress":true,"id":"3","finished":true}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Reloaded 197 of 407 libraries."}}]
[{"method":"app.restart","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","fullRestart":true},"id":24}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Syncing files to device...","progress":true,"id":"4"}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","progress":true,"id":"4","finished":true}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Waiting for application to start...","progress":true,"id":"5"}}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","progress":true,"id":"5","finished":true}}]
[{"id":24,"result":true}]
[{"event":"app.log","params":{"appId":"c7fc8029-2ff0-4d2b-9e47-3ea23b25291c","log":"Hot reload performed in 7053 ms."}}]
[{"id":23,"result":true}]
```

**Comment by Hixie** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@stevemessick A restart should not be requested until the reload has completed. The CLI UI enforces this.

**Comment by stevemessick** [comment]
@johnmccutchan So if I wait 10 seconds for a reload, that is working as expected? I saw one reload timing reported in the 170+ second range. That can't be right.

I'm **trying** to make the IDE enforce the same constraints, which is why I need the output to be printed in a timely manner.

**Comment by johnmccutchan** [comment]
@stevemessick No, clearly something is wrong with the timing being reported. Reloads should take milliseconds. We are waiting for the 'FirstFrame' event from the flutter framework after a reload. For some reason that is taking along time to arrive.

Can you reproduce with more verbose logging from within flutter_tools?

**Comment by eseidelGoogle** [comment]
I'm not sure this is the cause, but it's at least related: Flutter won't
produce a frame unless it's needed (we get a vsync callback from the OS).
For example if the device is off or the application is in the background it
could be an indefinite period of time before we produce a frame. :)

**Comment by stevemessick** [comment]
@johnmccutchan I'm not able to run the app using `flutter daemon` anymore. The app starts but never displays its UI. It just paints the display black with the standard Android trim (back, home, app stack buttons plus status bar icons).

FWIW everything is working fine when I use the iOS simulator from IntelliJ. Reload prints both status messages and (with the `flutter create` app) the reload times are 80-120ms. The app itself works fine with my Nexus 5X from IntelliJ, but the reload timing is not printed until after a refresh, as I described earlier. Just to be clear, as @eseidel implies, the app is in the foreground.

**Comment by johnmccutchan** [comment]
I'm confused about this issue. Can someone please summarize what the current status is?

**Comment by mit-mit** [comment]
Eric suggested that blocking on the first frame being rendered might be
unreliable. Did you confirm or reject that?

**Comment by eseidelGoogle** [comment]
Specifically we only post frames when the device requests them.  If the screen is off or the app is in the background, we won't post a frame until the app is foreground/on again.

I also remember that Jason recently fixed our logging to not buffer lines.  I wonder if that could have been related here?

**Comment by stevemessick** [comment]
Today the behavior is slightly different from what I initially reported. As Eric mentions, it is important to have the screen on with the app in the foreground. Here's the output from the IntelliJ console after doing two hot reloads.

```json
Reloaded 0 of 388 libraries.
Hot reload performed in 231 ms.
Reloaded 0 of 388 libraries.
Hot reload performed in 6485 ms.
```
The first hot reload was done while watching the app update. The second was done with the screen off. It wasn't until clicking the Restart button in IntelliJ (about 5 seconds later) that the timing for the hot reload was printed.

The change to logging may have helped but it hasn't fixed everything.

**Comment by johnmccutchan** [comment]
Tracking of reload / restart times depends on the device rendering a frame to be accurate. 

We say that it's done after the reassemble is completed. This would avoid the need for an actual frame to be produced by the device. For the record about 50% of the reload time is spent inside the VM and the other 50% is spent doing the reassemble. Waiting for the frame adds a negligible delay.

Thoughts?

**Comment by Hixie** [comment]
Sure. The frame time is really the app's problem, anyway, not the hot reload's problem. Go for it.
