### ISSUE TITLE
How  to catch`Unhandled Exception` happened  in `ui_dart_state.cc`

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#64014]
I just wonder how  to catch`Unhandled Exception` happened  in `ui_dart_state.cc`

I have got this error, I ask this question because I'm not sure which part of code cause this

> E/flutter ( 7299): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: UGC (of class scala.Enumeration$Val)

**Comment by pedromassangocode** [comment]
Hi @jerryzhoujw 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that causes this exception?
Thank you

**Comment by jerryzhoujw** [comment]
Hi @pedromassango,  

It's fixed later on yesterday, and the casing code is related to an exception when make a graphQL request.

Do you prefer me to create a minimal complete reproducible code then ?

**Comment by pedromassangocode** [comment]
> Do you still prefer creating a minimal complete reproducible code then ?

Yes, please.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
