### ISSUE TITLE
Hot reload failure error message is ugly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#64027]
Currently if you remove a field from a const class and try to hot reload you get:

```
Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancelling, class: {type: @Class, fixedId: true, id:
classes/3988, name: ItemGeometry}, message: Const class cannot remove fields: Library:'package:plexiglass/rendering/items/common.dart' Class: ItemGeometry}]}
```

This is not a pretty message. We should pretty print it.

**Comment by jonahwilliams** [comment]
Looks like we process the reload response, but then don't do anything special with the info:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L602

It would be a bit easier to handle this if `package:vm_service` had a structured type for the ReloadReport details,. fyi @bkonyi @devoncarew
