### ISSUE TITLE
Problems with new projects（AS 4.0.1 + Flutter 1.20.2）

### ISSUE THREAD

**Issue by zhumj** [flutter/flutter#64033]
1. When I create a new project, there is no Podfile generated in the ios folder.
2. When I create Plugin, there is no /andoid or /ios under the Plugin folder.
The above two questions were not available when I was using the older version (before 1.17) Flutter. Is there any change with the new SDK?

Here is the directory of my new version projects: 
![20200818183707](https://user-images.githubusercontent.com/8665756/90503340-d774ac80-e181-11ea-9afa-528086435522.png)

Here is the directory of my old version projects: 
![20200818183331](https://user-images.githubusercontent.com/8665756/90503041-62a17280-e181-11ea-846e-5143c4d581a3.png)

**Comment by TahaTesser** [comment]
Hi @zhumj 
1. `podfile` isn't generated until you add a package in `pubspec.yaml` that requires it. For example, add `image_picker` and `pub get` will generate `podfile` automatically 

2. Now when you create plugin, you need to define platforms. 
Please check official documentation [Step 1: Create the package](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-1-create-the-package-1)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by zhumj** [comment]
I added provider and pub get, but the podfile is still not generated.

**Comment by TahaTesser** [comment]
Just tried again, no issues
<img width="523" alt="Screenshot 2020-08-27 at 4 14 05 PM" src="https://user-images.githubusercontent.com/48603081/91433153-73886d00-e880-11ea-8647-376e27783835.png">
<img width="796" alt="Screenshot 2020-08-27 at 4 14 38 PM" src="https://user-images.githubusercontent.com/48603081/91433156-74210380-e880-11ea-9383-b120ea6a2fa1.png">

**Comment by zhumj** [comment]
Only use image_picker to generate provider? Because I added the provider and did not generate a podfile, which is too inconvenient to use, I still recommend generating a podfile directly when creating a project. Also, thank you for your answer, sir.

**Comment by TahaTesser** [comment]
@zhumj 
provider doesn't require native ios podfile, add any package that requires pod
