### ISSUE TITLE
Flutter web TextField highlight area not correct when selecting chinese text

### ISSUE THREAD

**Issue by ArchangelXu** [flutter/flutter#64031]
steps to reproduce:
create a textfield like:
```
TextField(
            maxLines: null,
            expands: true,
            decoration: null,

          )
```
with text:

> 　　Flutter web中文光标位置有问题是怎么回事呢？Flutter web相信大家都很熟悉，但是Flutter web中文光标位置有问题是怎么回事呢，下面就让小编带大家一起了解吧。
> 　　Flutter web中文光标位置有问题，其实就是中文行高不对，大家可能会很惊讶Flutter web怎么会中文光标位置有问题呢？但事实就是这样，小编也感到非常惊讶。
> 　　这就是关于Flutter web中文光标位置有问题的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！

and try to select all text.

<img width="562" alt="WX20200818-125015@2x" src="https://user-images.githubusercontent.com/8541162/90496194-1bfb4a80-e178-11ea-93ff-a3611dfc8686.png">

Meanwhile, when the content is English, everything seems fine.
<img width="567" alt="WX20200818-125125@2x" src="https://user-images.githubusercontent.com/8541162/90496199-1d2c7780-e178-11ea-8a73-ee57f88e06e5.png">

**Comment by ArchangelXu** [comment]
update:
The issue is gone when i set style to 
`style: TextStyle(height: 1.0)`
So maybe it is related to the calculation of font height?

**Comment by ArchangelXu** [comment]
flutter doctor:
Flutter 1.21.0-9.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 7c6f9dd239 (9 days ago) • 2020-08-09 10:31:03 -0400
Engine • revision 6d86e67f04
Tools • Dart 2.10.0 (build 2.10.0-4.0.dev 0341576448)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
Hi @ArchangelXu,
I tried to replicate the issue with your code on latest beta, but was able to select all chinese text properly without any issues.

![Screen Shot 2020-08-19 at 12 45 45 PM](https://user-images.githubusercontent.com/67046386/90604212-1fdfa900-e21a-11ea-9b2c-648a50423b03.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0 at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 916c3ac648 (3 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (3 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.125

! Doctor found issues in 1 category.
Deeptis-MacBook-Air:~ deeptibelsare$ flutter config --enable-web
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
Deeptis-MacBook-Air:~ deeptibelsare$ flutter devices
3 connected devices:

SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
Web Server (web)  • web-server       • web-javascript • Flutter Tools
Chrome (web)      • chrome           • web-javascript • Google Chrome
84.0.4147.125

```

</details>


<details>
<summary>code sample</summary>

```
body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(
          maxLines: null,
          expands: true,
          decoration: null
        )
      ),
```

</details>

Can you switcth to latest beta and see if you still experience the same issue ?
Thanks.

**Comment by mizuirot** [comment]
Hi @darshankawar , @ArchangelXu 

This bug happened to me in a Japanese environment.

■environment
Windows 10
Google chrome 85.0.4183.83
flutter latest beta

-----

image
![Flutter Demo - Google Chrome 2020_09_07 1_12_02](https://user-images.githubusercontent.com/69755373/92330086-2e95df00-f0a7-11ea-9075-da44ed43603f.png)

code
```
      body: Center(
        child: TextField(
          maxLines: null,
          controller: TextEditingController(
              text: 'あ\nああ\nあ\nああ\nあ\nああ\nあ\nああ\nあ\nああ\nあ\nああ\n'),
          style: Theme.of(context).textTheme.subtitle1,
        );,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print('text style: ${Theme.of(context).textTheme.subtitle1}');
        },
      ),
```

Log
```
text style: TextStyle(debugLabel: (englishLike subhead 2014).merge(blackRedmond subtitle1), inherit: false, color: Color(0xdd000000), family: Segoe UI, size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none)
```

DOM
```
<flt-offset flt-layer-state="updated" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 535.667px);">
<flt-picture flt-layer-state="updated" style="position: absolute; transform: translate(0px, 0px);">
<flt-dom-canvas style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px;">
<draw-rect flt-rect="Rect.fromLTRB(0.0, 0.0, 16.0, 21.3)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 0px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 21.3, 32.0, 42.7)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 21.3333px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 42.7, 16.0, 64.0)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 42.6667px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 64.0, 32.0, 85.3)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 64px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 85.3, 16.0, 106.7)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 85.3333px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 106.7, 32.0, 128.0)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 106.667px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 128.0, 16.0, 149.3)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 128px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 149.3, 32.0, 170.7)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 149.333px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 170.7, 16.0, 192.0)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 170.667px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 192.0, 32.0, 213.3)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 192px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 213.3, 16.0, 234.7)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 213.333px); width: 16px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<draw-rect flt-rect="Rect.fromLTRB(0.0, 234.7, 32.0, 256.0)" flt-paint="SurfacePaintData(color = #90caf9; isAntiAlias = true)" style="position: absolute; transform-origin: 0px 0px 0px; transform: translate(0px, 234.667px); width: 32px; height: 21.3333px; background-color: rgb(144, 202, 249);">
</draw-rect>
<p style="font-size: 16px; font-weight: normal; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; color: rgba(0, 0, 0, 0.867); position: absolute; white-space: pre-wrap; overflow-wrap: break-word; overflow: hidden; height: 277.333px; width: 665px; transform-origin: 0px 0px 0px; transform: none;">
あ
ああ
あ
ああ
あ
ああ
あ
ああ
あ
ああ
あ
ああ
</p>
</flt-dom-canvas>
</flt-picture>
<flt-transform flt-layer-state="updated" style="position: absolute; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 0, 21.3333);">
</flt-transform>
<flt-transform flt-layer-state="updated" style="position: absolute; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 32, 256);">
</flt-transform>
</flt-offset>
```

> `<p style="font-size: 16px; font-weight: normal; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; color: rgba(0, 0, 0, 0.867); position: absolute; white-space: pre-wrap; overflow-wrap: break-word; overflow: hidden; height: 277.333px; width: 665px; transform-origin: 0px 0px 0px; transform: none;">`

in my environment, this string height needs about 300px. 

thanks.

**Comment by TahaTesser** [comment]
Hi @ArchangelXu 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mizuirot** [comment]
Hi @TahaTesser 

I'm not good at English, so I'm sorry if there is something difficult to understand.

Sorry to ask such silly questions,

A) Issue is still replicable in my environment. (with japanese text). 

What should I do next?

1. create new issue
2. send additional information here

B) If I find a problem that looks the same as this time, what should I do next?

1. create new issue
2. send additional information to related issue

thanks,

---

just in case, I write  additional information of my environment.

<details>
<summary>flutter run --verbose</summary>
[  +96 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e682ec711a8c05fe78157595240b392de339fa32
[        ] executing: [C:\tools\flutter/] git tag --points-at HEAD
[  +29 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\tools\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-9.0.pre-109-ge682ec711
[   +7 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +22 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +30 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] Multiple devices found:
[  +15 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +1 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83
[   +1 ms] [0]: Web Server (web-server)
[        ] [1]: Chrome (chrome)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+10132 ms] 1
[ +117 ms] Generating C:\Users\user\Projects\test\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +60 ms] Launching lib\main.dart on Chrome in debug mode...
[  +51 ms] Updating assets
[  +61 ms] Syncing files to device Chrome...
[  +28 ms] Generating C:\Users\user\Projects\test\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +52 ms] <- reset
[   +4 ms] C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\tools\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\user\AppData\Local\Temp\flutter_tools.63f0841b\flutter_tool.a951cf75\app.dill --libraries-spec file:///C:/tools/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\user\AppData\Local\Temp\flutter_tools.63f0841b\flutter_tools.d63cc27 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform file:///C:/tools/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+11733 ms] Syncing files to device Chrome... (completed in 11,820ms, longer than expected)
[   +1 ms] Synced 27.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +130 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59950/devtools/browser/b1e88bc6-3a6d-4366-a4aa-735f2a41eda0
[+4752 ms] Debug service listening on ws://127.0.0.1:59979/-EV1OE7HU3A=

[ +202 ms] Debug service listening on ws://127.0.0.1:59979/-EV1OE7HU3A=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
</details>

<details>
<summary>flutter doctor -v</summary>
[√] Flutter (Channel master, 1.22.0-10.0.pre.109, on Microsoft Windows [Version 10.0.19041.450], locale ja-JP)
    • Flutter version 1.22.0-10.0.pre.109 at C:\tools\flutter
    • Framework revision e682ec711a (7 hours ago), 2020-09-09 10:52:27 +0200
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 2 categories.
</details>

**Comment by TahaTesser** [comment]
@mizuirot
Please file a new issue and provide all details
