### ISSUE TITLE
Focus issue after upgrading from 1.17.5 to 1.20.0 (and above)

### ISSUE THREAD

**Issue by P-Jay357** [flutter/flutter#64030]
It doesn't crash and no errors are thrown, but after updating my app's flutter version from 1.17.5 to 1.20.0 (and above, the last 2 updates haven't fixed this issue) there is an issue when on a page with multiple form widgets. When 1 widget is focused it works as expected, but when another widget is then focused the hint text for the new widget doesn't animate, and so the user's input is displayed on top of the hint text, which makes it hard to read. The hint text only moves up after the user has pressed the enter key.

I'm just wondering if anyone else has had this issue since updating, and any help towards making a fix would be greatly appreciated.

**Comment by TahaTesser** [comment]
Hi @P-Jay357 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
