### ISSUE TITLE
Failed assertion: line 329 pos 15: 'primaryContext != null': is not true.

### ISSUE THREAD

**Issue by Priptide** [flutter/flutter#64034]
Reloaded 9 of 628 libraries in 942ms.
Reloaded 9 of 628 libraries in 700ms.
I/tudentsTech.US(20403): WaitForGcToComplete blocked HeapTrim on None for 49.609ms
Reloaded 9 of 628 libraries in 1,099ms.
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext !=
null': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
[38;5;244m#2      ShortcutManager.handleKeypress[39;49m
[38;5;244m#3      _ShortcutsState._handleOnKey[39;49m
[38;5;244m#4      FocusManager._handleRawKeyEvent[39;49m
[38;5;244m#5      RawKeyboard._handleKeyEvent[39;49m
[38;5;244m#6      BasicMessageChannel.setMessageHandler.<anonymous closure>[39;49m
[38;5;244m#7      _DefaultBinaryMessenger.handlePlatformMessage[39;49m
[38;5;244m#8      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:282:15)[39;49m
[38;5;244m#12     _invoke3  (dart:ui/hooks.dart:281:10)[39;49m
[38;5;244m#13     _dispatchPlatformMessage  (dart:ui/hooks.dart:156:5)[39;49m
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during a platform message callback:[39;49m
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext != null': is not true.

[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      ShortcutManager.handleKeypress[39;49m
[38;5;244m#3      _ShortcutsState._handleOnKey[39;49m
[38;5;244m#4      FocusManager._handleRawKeyEvent[39;49m
[38;5;244m#5      RawKeyboard._handleKeyEvent[39;49m
[38;5;244m#6      BasicMessageChannel.setMessageHandler.<anonymous closure>[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext != null': is not true.

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext != null': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

**Comment by pedromassangocode** [comment]
Hi @Priptide 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by Priptide** [comment]
Flutter Doctor:
`PS D:\Flutter\Code\UST> flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-GB)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Charlie\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\Charlie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!`

The verbose

`[+38033 ms] I/flutter (20907): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (20907): The following assertion was thrown during a platform message callback:
[   +1 ms] I/flutter (20907): 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 329 pos 15: 'primaryContext !=
[  +12 ms] I/flutter (20907): null': is not true.
[   +1 ms] I/flutter (20907): 
[        ] I/flutter (20907): Either the assertion indicates an error in the framework itself, or we should provide substantially
[  +10 ms] I/flutter (20907): more information in this error message to help you determine and fix the underlying cause.
[   +2 ms] I/flutter (20907): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (20907):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +1 ms] I/flutter (20907): 
[   +9 ms] I/flutter (20907): When the exception was thrown, this was the stack:
[   +2 ms] I/flutter (20907): #2      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:329:15)
[   +1 ms] I/flutter (20907): #3      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
[   +1 ms] I/flutter (20907): #4      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1623:43)
[   +1 ms] I/flutter (20907): #5      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:598:68)
[   +1 ms] I/flutter (20907): #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
[   +7 ms] I/flutter (20907): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
[   +2 ms] I/flutter (20907): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
[   +1 ms] I/flutter (20907): #12     _invoke3 (dart:ui/hooks.dart:281:10)
[   +2 ms] I/flutter (20907): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
[  +11 ms] I/flutter (20907): (elided 5 frames from class _AssertionError and dart:async)
[   +1 ms] I/flutter (20907): ════════════════════════════════════════════════════════════════════════════════════════════════════`


The error is caused when using a side drawer but there is lots on it not sure which part causes this error so it may take a while to get this minimal reproducible code

**Comment by pedromassangocode** [comment]
So, once you get the minimal reproducible code you can share it here.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
