### ISSUE TITLE
Android command line tools sdk folder structure is inconsistent with the expected search path for the sdkmanager

### ISSUE THREAD

**Issue by bjconlan** [flutter/flutter#64035]
I recently extracted the most recent android sdk tools (non java8 dependent commandlinetools-linux-6609375_latest.zip) which contains the root directory 'tools' (naturally I renamed the extracted directory to 'cmdline-tools' lending to a 'cmdline-tools/tools' structure) while the code which looks to reference the appropriate binaries looks into a folder called 'latest' (as such falls back to the $ANDROID_SDK_ROOT/tools/sdkmanager (java8 dependent version which looks to be installed by one of the (non java8) sdkmanager packages) 

In short, I think the 'latest' should be renamed 'tools' (but this mis-configuration on my behalf could be a side effect of the poor documentation surrounding android command line tools (ie the renaming of the extracted 'tools' folder to be contained in a directory called 'cmdline-tools'). 

https://github.com/flutter/flutter/blob/a51dc3d913344f3073da12f4aae654c3299dec6c/packages/flutter_tools/lib/src/android/android_sdk.dart#L382

Also the avdmanager path needs some assistance with respect to using the 'newer' sdk tool path over the legacy path
https://github.com/flutter/flutter/blob/a51dc3d913344f3073da12f4aae654c3299dec6c/packages/flutter_tools/lib/src/android/android_sdk.dart#L302

**Comment by GurjinderPartola** [comment]
Actually `cmdline-tools/latest` is the right location:
![immagine](https://user-images.githubusercontent.com/17544193/111080088-13e06f00-84fd-11eb-82d2-a9b1272114e9.png)
Pinned versions are not yet supported (see #76527).
