### ISSUE TITLE
Not possible to update selected date from another source then the CalendarDatePicker

### ISSUE THREAD

**Issue by GauteHaugen** [flutter/flutter#64040]
Hi, I'm trying to use a CalendarDatePicker in combination with buttons that have a predefined date on them. The date that is selected is stored in the state of the widget that has the CalendarDatePicker as its child. When the CalendarDatePicker updates its date by the user tapping a date, the variable outside gets updated. But if the user taps one of the buttons with a predefined date on it, the CalendarDatePicker does not get the updated value. I created this previous issue #60981, where the currentDate field was added. This allows you to update the current date and not the selected date which I need to be able to update using input outside of the CalendarDatePicker

## Steps to Reproduce

1. Start a new clean flutter project
2. Replace main.dart with code from below.
3. Run the app and use buttons to change the date.

**Expected results:**
I would expect the selected date in the CalendarDatePicker to update when tapping one of the buttons under it.

**Actual results:**
The CalendarDatePicker only updates its selected date when the user taps a date in the CalendarDatePicker widget.

<details>
<summary><b>flutter doctor -v</b></summary>
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\gaute.haugen\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\gaute.haugen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM G975F (mobile) • R58M16BWQWR • android-arm64 • Android 10 (API 29)

• No issues found!
</details>

<details>
<summary><b>Code</b></summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var date = DateTime.now().toUtc();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          CalendarDatePicker(
            initialDate: date ?? DateTime.now(),
            firstDate: DateTime(1970, 1, 1),
            lastDate: DateTime(2099, 31, 12),
            onDateChanged: (DateTime value) {  },
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.arrow_back),
                onPressed: () {
                  setState(() {
                    date = date.add(Duration(days: -1));
                  });
                },
              ),
              IconButton(
                icon: Icon(Icons.arrow_forward),
                onPressed: () {
                  setState(() {
                    date = date.add(Duration(days: 1));
                  });
                },
              )
            ],
          ),
          Text('Current date: ${date.toString()}'),
        ],
      )
    );
  }
}
```
</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.139, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-10.0.pre.139 at /Users/tahatesser/Code/flutter_master
    • Framework revision a51dc3d913 (6 hours ago), 2020-08-18 02:51:02 -0400
    • Engine revision 0b330467da
    • Dart version 2.10.0 (build 2.10.0-38.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

```

</details>

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
I am able to reproduce the problem with the sample code. Thanks for the report, it looks like a state update issue. Not sure what is causing it yet.
