### ISSUE TITLE
Unable to tap the drawn text in Flutter driver test.

### ISSUE THREAD

**Issue by Indumathi1195R** [flutter/flutter#64048]
Hi Team,
	
       1. I have drawn some text on the canvas and trying to tap on the text in flutter text but it doesn't work
       2. I have implemented accessibility using semanticsBuilder of custom painter
       3. And I have tried to find the element by using find.text('string') and find.bySemanticsLabel('Label') and the element is not null, but the tapping doesn't occur.

The error we got is following by:
VMServiceFlutterDriver: tap message is taking a long time to complete...

We have prepared the sample for the same. Please find the sample from the following link.

Sample link:
[flutter_app_testbed.zip](https://github.com/flutter/flutter/files/5091303/flutter_app_testbed.zip)

Regards,
Indumathi R

**Comment by darshankawar** [comment]
It doesn't tap on drawn widgets that are implemented using Paint. Not sure if Flutter driver supports it though.

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by ajaygautam** [comment]
FlutterDriver team, can I please get an update on this?
This will help raise quality of our software. 

Thanks

Ajay

**Comment by Indumathi1195R** [comment]
Hi Team,

Any update on this?

Regards,
Indumathi R

**Comment by goderbauer** [comment]
Stuff that you draw on a canvas is basically opaque to the testing framework. You can, however, find the CustomPainter and use `tapAt` to tap at the desired offset within that painter.


https://master-api.flutter.dev/flutter/flutter_test/WidgetController/tapAt.html
