### ISSUE TITLE
Long rasterizer frames scrolling Gallery on iPhone 6s

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6405]
Probably most important is that if we fix this is that we find a way to test it since @chinmaygarde indicated this may be the same as an issue he fixed prior. :)

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision edbe0348474f6c88cc2935deb9fa52e323e7dc91 (16 minutes ago), 2016-10-19 16:17:55
    • Engine revision 525c947ece
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • Eric's iPhone • 245efaebda74df40169418839fff2a8368bcaae5 • ios
```

See video.
https://youtu.be/G0Da0Pxmf9g

**Comment by eseidelGoogle** [comment]
I believe this is some sort of regression.  I don't recall our iPhone scrolling performance coming in-and-out like this before.

**Comment by eseidelGoogle** [comment]
Do we know when this regression might have started?  This regression just (negatively) affected a potential pitch by @sethladd to an internal customer. :(  FYI @abarth

**Comment by eseidelGoogle** [comment]
I'm seeing this opening drawers and navigating between routes on my iPhone 6, having built on 7acc996547e2ffe0d08e5797c835bf2a2702e8c4.  I'm not sure if that's the same bug, but on that assumption I think this is a pretty-high-priority regression and may block our customers shipping on iOS.

**Comment by chinmaygarde** [comment]
I investigated this some more. My initial suspicion was a regression in the pipelining flow but that does not seem to be the case. In the slow frames, the offending call is in one of the `GrVertexBatch::onDraw` calls. Most of the time spent in this call is wall time. The actual CPU time is minimal. Still trying to figure out what is going on. Just an update.

**Comment by sethladd** [comment]
Do we still see this effect?

**Comment by chinmaygarde** [comment]
I haven't seen this issue since the latest Skia roll. But, since I don't know the cause of the issue in the first place, I cannot say this is fixed. I will keep an eye out for this but we should leave this ticket open.

**Comment by eseidelGoogle** [comment]
There are definitely still long frames here and there, but I don't think this bug is particularly useful for now.  We'd have to attack specific instances.  The general random long frames I recall seeing are gone.
