### ISSUE TITLE
build_material_checkbox.canvaskit.drawFrameDuration.average regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#64058]
web_benchmarks_canvaskit build_material_checkbox.canvaskit.drawFrameDuration.average jumped from ~13ms to ~19ms.

See https://flutter-flutter-perf.skia.org/e/?begin=1597682768&end=1597696717&keys=Xf6596c634a675eea7960c0bf5ca0c829&xbaroffset=21088

https://github.com/flutter/flutter/commit/579cab8a868540b107e4e0c9f7afec3fbae11b60 is the culprit.

**Comment by liyuqian** [comment]
@LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
@liyuqian revert?

**Comment by LongCatIsLooong** [comment]
Going to land the revert if I still need more time to investigate by the time the tree turns green.

**Comment by liyuqian** [comment]
Sounds good. Thanks for the quick resopnse!

**Comment by LongCatIsLooong** [comment]
Ran the benchmark (as instructed in the README file, `flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true --profile -d web-server lib/web_benchmarks.dart`) 6 times in incognito mode for each of the scenarios below. Taking the median:

| with Revert (#64062) | with the Revert but use a global key instead | without Revert (#64062) run 1 | without Revert (#64062) run 2 | 
| --- | --- | --- | --- |
| 14474 μs  | 14768 μs | 15890 μs | 15438 μs |

On my PC it seems the patch introduced a ~6% - 10% time increase. @liyuqian does the approach sound reasonable?

**Comment by LongCatIsLooong** [comment]
"with the Revert but use a global key instead" means to add a global key to the mouse region to ensure the `FocusableActionDetector`'s child doesn't have to be inflated again when we have to add/remove an `Action` or `Shortcuts` widget from the tree, i.e.:

```dart
  final GlobalKey mouseRegionKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    Widget child = MouseRegion(
      key: mouseRegionKey,
      onEnter: _handleMouseEnter,
      onExit: _handleMouseExit,
      cursor: widget.mouseCursor,
      child: Focus(
        focusNode: widget.focusNode,
        autofocus: widget.autofocus,
        canRequestFocus: _canRequestFocus,
        onFocusChange: _handleFocusChange,
        child: widget.child,
      ),
    );
    if (widget.enabled && widget.actions != null && widget.actions.isNotEmpty) {
      child = Actions(actions: widget.actions, child: child);
    }
    if (widget.enabled && widget.shortcuts != null && widget.shortcuts.isNotEmpty) {
      child = Shortcuts(shortcuts: widget.shortcuts, child: child);
    }
    return child;
  }
```
It seems this outperforms the original PR in the benchmark (defined in https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/lib/src/web/bench_build_material_checkbox.dart, toggling a grid of `CheckBox`es on and off), as it is the simplest use case and the tree never changes height (as is the most common I think). But I'd expect it to become worse when the tree height does change.

I'm not entirely sure using global keys is the way to go, as there might be use cases that require constantly changing the height of `FocusableActionDetector`'s subtree. @gspencergoog can I get your opinions on this?

**Comment by liyuqian** [comment]
> On my PC it seems the patch introduced a ~6% - 10% time increase. @liyuqian does the approach sound reasonable?

Yes, this sounds reasonable. The devicelab has a bigger difference probably because it has a weaker linux box.

**Comment by gspencergoog** [comment]
@LongCatIsLooong I think this may be why I implemented it the way I did originally, so using the `GlobalKey` is probably a good compromise.

**Comment by LongCatIsLooong** [comment]
@liyuqian the benchmark seems to be back to normal after the revert and didn't regress after the reland: https://flutter-flutter-perf.skia.org/e/?begin=1598045636&end=1598063764&keys=Xf6596c634a675eea7960c0bf5ca0c829&numCommits=90&xbaroffset=21088. Close?

**Comment by liyuqian** [comment]
Yes, closing now. Thanks for the fix!
