### ISSUE TITLE
docs-linux failing on release branches

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#64068]
https://github.com/flutter/flutter/runs/999350932

ex failure:  Docs deployment cannot be run on the flutter-1.21-candidate.9 branch.

cc @tvolkert @christopherfujino

**Comment by tvolkert** [comment]
The fact that they're not deployed is working as intended inasmuch as this isn't the master or stable branch.  The issue is that the shard shouldn't even be calling `deploy_docs`
