### ISSUE TITLE
Overflow glow has bad interaction with drawer shadow

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6407]
Not sure what the right interaction is, but this seems wrong.

See video.
https://youtu.be/Xt0yNeBe9tc

**Comment by Hixie** [comment]
The bug is that we're not clipping the glow to the container width. The reason it looks like a bad interaction is just https://github.com/flutter/flutter/issues/5231.

**Comment by Hixie** [comment]
Fixed.
