### ISSUE TITLE
Provide clearer renderer options on the web

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#64092]
The web provides two renderer options: HTML (default) and CanvasKit. To enable CanvasKit one must pass the cryptic and elusive `--dart-define=FLUTTER_WEB_USE_SKIA=true` option. Now that the CanvasKit renderer is maturing, let's discuss how to better surface it.

Another issue with this option is that it's all-or-nothing. You are either always in HTML mode or always in CanvasKit mode. One common situation that's not addressed is that apps that are built simultaneously for mobile and desktop form factors have different constraints. Desktop devices (laptops, computers, TVs) tend to have good internet connections but are compute intensive due to larger denser screens. Mobile devices tend to have worse internet connection speeds and are light on widget count/screen ratio. For this use-case we should provide an option that picks the HTML renderer for mobile devices, and CanvasKit for desktop.

Details are in this doc: https://docs.google.com/document/d/1aY0iU16wf_sdT7nwfpjgT-IatHNfF3slTiYHKmxcIog

**Comment by yjbanov** [comment]
Bumping to september. I was a little too optimistic about being able to do actual work in August.

**Comment by yjbanov** [comment]
@angjieli implemented this.

**Comment by esDotDev** [comment]
fwiw, this assumption is a bit overly simplistic. Tablets sit in a middle ground where they share more in common with Desktop than Phones, yet they will still be pushed to HTML with this approach. Just food for thought.
