### ISSUE TITLE
Fail to build engine for ARMM64/Aarch64 on Ubuntu Server

### ISSUE THREAD

**Issue by YuvarajVelumani82** [flutter/flutter#64098]
Hi, 

I've followed the steps described on the [loliot](https://wiki.loliot.net/docs/lang/flutter/engine/flutter-engine-for-linux-arm64) to cross compile it to my target device ( Qualcomm Snapdragon SA8155P ADP AIR).

My Hardware setup doesn't have SD card boot option (or I don't know how to do it). When I ran the below command,

> cd $HOME/flutter-engine/engine/src \
&& [ -d out/linux_debug_arm64 ] && sudo rm -r out/linux_debug_arm64 ;\
./flutter/tools/gn \
    --clang \
    --target-sysroot $HOME/flutter-engine/sdk/sysroot \
    --target-toolchain $HOME/flutter-engine/sdk/toolchain \
    --target-triple aarch64-linux-gnu \
    --linux-cpu arm64 \
    --runtime-mode debug \
    --embedder-for-target \
    --no-lto \
    --target-os linux \
    --arm-float-abi hard

I got the following error message:
> Generating GN files in: out/linux_debug_arm64
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/mio.ten.fujitsu.com/yvelumani/flutter-engine/engine/src/out/linux_debug_arm64/
Command: python /home/mio.ten.fujitsu.com/yvelumani/flutter-engine/engine/src/build/config/linux/pkg-config.py -s /Volumes/Data/flutter-work/sdk/sysroot -a arm64 --system_libdir lib gtk+-3.0
Returned 1.
stderr:
>
>Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xau', not found
Could not run pkg-config.
>
>See //flutter/shell/platform/linux/config/BUILD.gn:14:1: whence it was called.
pkg_config("gtk") {
^------------------
See //flutter/shell/platform/linux/BUILD.gn:74:16: which caused the file to be included.
  configs += [ "//flutter/shell/platform/linux/config:gtk" ]
               ^------------------------------------------

My intentions is to run Flutter apps on the Qualcomm SA8155P ADP AIR hardware which has Automotive Grade Linux (Yocto 2.6) on one board and Linux on the other board.

**If the procedure which I'm following is WRONG, please do help me How to build the Engine for Qualcomm Snapdragon processors**

Note: Should I need to install Android Studio on my Ubuntu Server.. Since I'm connected remotely using putty, I do not have GUI. I hope Flutter app can be developed/build from command line. (Please correct me if I'm wrong)

-Thanks in advance and I highly appreciate your help.

**Comment by stuartmorgan** [comment]
According to your log, you are trying to build the GTK embedding in a sysroot where `pkg-config` fails for the GTK development headers. That's not going to work. Since you seem to be using a custom sysroot, I'm not sure what help you're looking for; we have no way of knowing how your sysroot is set up.

If you want to build this configuration before it's officially supported, you'll need to build a sysroot that has everything the build requires.

**Comment by YuvarajVelumani82** [comment]
My sysroot points to 
sysroot -> /usr/arm-linux-gnueabi/lib
