### ISSUE TITLE
Remove the `--with-flutter-driver` option from `flutter create`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#64095]
The recommended way of creating integration tests moving forward is to use `package:integration_test` (formerly known as package:e2e).

I do not believe we should offer an option to easily create such a test, since the package is vended from outside the SDK and creates yet another API surface for us to maintain/hotfix. It is not terribly hard to create an integration test there.

We should just drop the option and the related template(s).

/cc @jonahwilliams  @zanderso

**Comment by jonahwilliams** [comment]
I'm always up for deleting code
