### ISSUE TITLE
Building Beautiful UIs with Flutter - Step 8 - AnimationController() params in _handleSubmitted()

### ISSUE THREAD

**Issue by rebecca-fundy** [flutter/flutter#64104]
Thanks for the tutorial!
The 'Duration' key should be 'duration' (lower case).  This crashed my program.

    animationController: AnimationController(
      Duration: const Duration(milliseconds: 700),  //should be duration: const Duration(milliseconds: 700),
      vsync: this,
    ),
  );

**Comment by darshankawar** [comment]
Hi @rebecca-fundy,
Thanks for finding this.

Link: https://codelabs.developers.google.com/codelabs/flutter/#7

**Comment by emem365** [comment]
Should I fix this? I am new to contributing and this seems easy enough :)

**Comment by emem365** [comment]
Also, could you point me to where this codelabs repo might be.
I found the dart code at [flutter/friendlychat-steps](https://github.com/flutter/friendlychat-steps), but that is just the code, and I checked, its actually correct. I cant seem to find the codelabs doc for this to correct

**Comment by JuYeong0413** [comment]
@emem365 The source for the codelabs on codelabs.google.developer.com are not accessible to non-Googlers.

**Comment by emem365** [comment]
@JuYeong0413 Yes, I kinda figured this after trying to search through all the GitHub repos for flutter and not finding anything, haha. Anyways, I guess I'll find something else to try and help with :)

**Comment by pedromassangocode** [comment]
Cc @sfshaza2

**Comment by domesticmouse** [comment]
The codelab text has been updated. Thanks for the bug report!
