### ISSUE TITLE
[dashboard] /api/public/build-status returned 500

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#64114]
The dashboard is currently broken: 
```
An error occured fetching tree status from Cocoon: /api/public/build-status returned 500
An error occured fetching build statuses from Cocoon: Invalid argument(s): Illegal to set field isFlaky (8) of Task to value (null): not type bool
```

**Comment by digiter** [comment]
The win_tool_tests Task entities have Flaky=null in the datastore, and that is causing this error. /cc @godofredoc @keyonghan

**Comment by digiter** [comment]
I have manually set Flaky=false for those entities in datastore.

**Comment by digiter** [comment]
The dashboard is recovered.

**Comment by godofredoc** [comment]
We are still missing proper fixes:

* This config problem should have been discovered on presubmit.
* The code creating the the model should be adding false by default if the field is mandatory.

**Comment by digiter** [comment]
@keyonghan As you added the config file and the presubmit for it, do you have some ideas on addressing the above comment?

**Comment by keyonghan** [comment]
> This config problem should have been discovered on presubmit.
`presubmit` does not support `isFlaky` flag. May not be suitable to catch the issue.
> The code creating the the model should be adding false by default if the field is mandatory.
https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_github_commits.dart#L206

**Comment by digiter** [comment]
Moved out of ticket queue as the immediate issue is fixed, and the last comment needs a few days to address.
