### ISSUE TITLE
scrollController.jumpTo() at top causes a surge in memory

### ISSUE THREAD

**Issue by Bedroome** [flutter/flutter#64124]
```dart
class A extends StatelessWidget {
  ScrollController _scrollController = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _scrollController.jumpTo(0.0);
        },
      ),
      body: CustomScrollView(
        controller: _scrollController,
        slivers: [
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Image.network(
                  'https://picsum.photos/seed/${Random().nextInt(99999)}/500/500',
                  height: 200,
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
```
When my list slides to the back, such as 400 to 500, clicking the button to top will cause the memory to rise suddenly
<img width="845" alt="截屏2020-08-19 上午11 27 12" src="https://user-images.githubusercontent.com/35730858/90588891-549a3300-e20f-11ea-9a51-df1a57750d9d.png">
When I click on the above, a peak appears
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
Hi @Bedroome,
There's similar open issue describing your case, [20857](https://github.com/flutter/flutter/issues/20857).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by Bedroome** [comment]
The problem I encountered seems to be different from there. When I call jumpTo, the memory will suddenly go up, and then stop going down. It seems that the memory is relatively stable when I slide.

**Comment by darshankawar** [comment]
Thanks @Bedroome, reopened.
I enabled `showPerformanceOverlay` and verified the behavior and noticed a spike when tap on FAB after scrolling for lot of images.

![64124_1](https://user-images.githubusercontent.com/67046386/90633922-8b3e7080-e244-11ea-87a0-fb990599e7b3.png)
![64124](https://user-images.githubusercontent.com/67046386/90633939-90032480-e244-11ea-9850-6270760161a2.png)

Tested on latest Stable (1.20.2) and on Android device 8.1.0

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by dnfield** [comment]
Hm. I wonder if the `jumpTo` implementation isn't setting the velocity the way we'd expect for the fix I did for this.

**Comment by dnfield** [comment]
Yup. `jumpTo` forces the pixels to jump without any information sent on to the physics.

We should be able to fix this by letting a `Scrollable` return true from `recommendDeferredLoading` when processing a `jumpTo` or perhaps a `forcePixels`.

**Comment by Bedroome** [comment]
> Yup. `jumpTo` forces the pixels to jump without any information sent on to the physics.
> 
> We should be able to fix this by letting a `Scrollable` return true from `recommendDeferredLoading` when processing a `jumpTo` or perhaps a `forcePixels`.
I noticed that jumpTo will judge recommendDeferredLoading, after it has been set to the top, it is still executing recommendDeferredLoading. It seems that there is no value to determine when to stop return true.

**Comment by dnfield** [comment]
An experiment that is almost there but not quite:

- in `forcePixels`, calculate an `impliedVelocity` based on the change in pixels.
- add the implied velocity to the activity's velocity when asking the physics about whether to defer

The missing piece right now is where to reset the implied velocity. Ideally, it would decrease as listeners reacted, but we don't know about that in the position and using `recommendDeferredScrolling` won't quite cut it because not all listeners willc all that (even if in this example they all do), and we don't really know how much of the implied velocity to consume there.

**Comment by dnfield** [comment]
Resetting it at the end of the frame seems to work fine.  Opened patch to fix this.

**Comment by Bedroome** [comment]
Maybe setPixels also needs this operation

**Comment by dnfield** [comment]
@bedroome can you share an example where it would cause problems as it is today?

**Comment by Bedroome** [comment]
I’m not sure about the jump value, but I don’t want to overscroll
, so I used setPixels instead of jumpTo

**Comment by Bedroome** [comment]
If there are other questions, should I use forcePixels instead of setPixels

**Comment by dnfield** [comment]
You shouldn't be calling either unless you're a ScrollPosition subclass or a ScrollActivity.

**Comment by Bedroome** [comment]
Thanks.

**Comment by DardanBala** [comment]
I am having the same issue, did you guys find a solution for this?
