### ISSUE TITLE
Json Error is not enough

### ISSUE THREAD

**Issue by SpeedRn** [flutter/flutter#64126]
![image](https://user-images.githubusercontent.com/10684520/90589414-9d062080-e210-11ea-8dbf-689ba673df61.png)

I want to get the 'cause' param, when I encounter a problem during json encoding

**Comment by stuartmorgan** [comment]
> I want to get the 'cause' param

It's a public property of the object; nothing is preventing you from accessing it.

**Comment by SpeedRn** [comment]
> > I want to get the 'cause' param
> 
> It's a public property of the object; nothing is preventing you from accessing it.

But it is not printed by the framework. I have to catch it every time and print it by myself. 
Is that a normal behavior?
