### ISSUE TITLE
docs.flutter.io missing open search description (doesn't tab-search in chrome)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6412]
https://www.chromium.org/tab-to-search

Maybe this is a dartdoc bug?  Donno.  @sethladd

**Comment by eseidelGoogle** [comment]
This is likely an easy fix?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1823](https://github.com/flutter/website/issues/1823) via [**ZenHub**](https://www.zenhub.com/)
