### ISSUE TITLE
When Java isn't available, the error message from `flutter precache` is misleading.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#64123]
I was running `flutter precache --force --windows` on my Windows machine, and got the following error:

```
Failed to download the Android dependencies
```

When I run the same command with `--verbose`, it tells me that the *real* problem is that I don't have Java on my machine.

```
[   +6 ms] executing: C:\Users\gspencer\code\flutter\bin\cache\flutter_gradle_wrapper.58475391\gradlew.bat -b C:\\Users\\gspencer\\code\\flutter\packages\flutter_tools\gradle\resolve_dependencies.gradle --project-cache-dir C:\Users\gspencer\code\flutter\bin\cache\flutter_gradle_wrapper.58475391 resolveDependencies
[  +37 ms]
           ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

           Please set the JAVA_HOME variable in your environment to match the
           location of your Java installation.
[        ] Failed to download the Android dependencies
```

 A better error message in this case would have been to add "because Java could not be found." or some such to the end of the non-verbose message.

/cc @christopherfujino

**Comment by Aman9026** [comment]
@gspencergoog  Should I add a module for sending different exit codes to 'processResult' and then print the error message accordingly or simply add a suggestion in the error message to do a verbose?

**Comment by gspencergoog** [comment]
Ideally, it should process the error codes and know what to print for them.  Presumably there are other possible error conditions as well (download failed, missing Android SDK, etc.).

Hopefully that's possible, but if that turns out to be too complicated/time consuming for some reason, then adding a suggestion about rerunning with `--verbose` would help, but also change the short error message to not be so definitive (and wrong) about what the problem is.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/bf4a5484aacb60d53a64b92a99bc74ba0d7899f1
