### ISSUE TITLE
Scaffold API docs - Should there be a single Scaffold in my entire Flutter app?

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#64136]
Hello,

The documentation at https://api.flutter.dev/flutter/material/Scaffold-class.html says

"The Scaffold was designed to be the single top level container for a MaterialApp and it's typically not necessary to nest scaffolds. For example in a tabbed UI, where the bottomNavigationBar is a TabBar and the body is a TabBarView, you might be tempted to make each tab bar view a scaffold with a differently titled AppBar. It would be better to add a listener to the TabController that updates the AppBar."

Does this mean I should not have a scaffold on any routes in my app?

Here, users say we can have a scaffold per page like here https://stackoverflow.com/questions/60561552/multiple-scaffolds-for-each-page-inside-a-flutter-app

So which one should it be? Please clarify in the docs...

**Comment by rohan20** [comment]
Use one `Scaffold` per page. The StackOverflow answer also mentions something similar that is in line with the docs:

>Here, we are nesting two Scaffolds, and, as you can see, the second app bar is being drawn below the first app bar. That would not be the best approach for tabbed or nested navigations. If you want to navigate inside the body of a Scaffold, and change the app bar depending on the content, using TabControllers, such as DefaultTabController, is preferred.

When you navigate to a new page using a `Route`, a new screen is created with the widget you pass to the route. So you **can** have another `Scaffold` on that screen. Even though that route is called from within a `Scaffold` of the first screen, the route replaces the first screen or adds itself on top of the first screen.

**Comment by pedromassangocode** [comment]
> Does this mean I should not have a scaffold on any routes in my app?

No. You can have one Scaffold for each route if you need to (and it is recommended if you are using Material Design widgets). 

I'm leaving this open to improve the Scaffold API docs, looks like we need to make it clear that it is ok to have one Scaffold widget for each Route if necessary.

**Comment by HansMuller** [comment]
@pedromassango - that's correct, we really need to improve the API doc for Scaffold.

**Comment by emem365** [comment]
@HansMuller @pedromassango 
I would like to contribute to the docs for this. I am super new to contributing, should I just go in and try to make some changes and see if you like it? :)
Also, is there anything else you want me to change in the docs?

**Comment by emem365** [comment]
I have created a PR, @HansMuller. Would be glad if you could review it :)

**Comment by pedromassangocode** [comment]
This still valid on latest `master` channel. The API docs of the Scaffold widget were not updated with the required information.

 https://api.flutter.dev/flutter/material/Scaffold-class.html

**Comment by emem365** [comment]
Created a PR #66972 to fix the documentation on this.
