### ISSUE TITLE
[url_launcher] return value from web view

### ISSUE THREAD

**Issue by komape** [flutter/flutter#64139]
> Already [questioned this on StackOverflow](https://stackoverflow.com/questions/63453775/how-to-get-return-value-from-javascript-in-webview-of-android-with-flutter) but did not receive any answers or feedback.

## Use case

I want to process payments in my Flutter app with PayPal. Therefore I want to use Androids WebView. So if the user clicks on my 'Pay' button, the WebView should open with the specified PayPal Site (setting price, item and so on in URL). Because the user can cancel the payment in the WebView I need to know if the payment was successful. PayPal is able to forward the user to a site depending on the success of the payment. I could set up to little sites which just tell the user to close to WebView (or do it automatically) and return some data with this action. Probably with some JavaScript.

As far as I understand these [two](https://stackoverflow.com/questions/6205627/returning-value-from-javascript-reliably-to-webview) [questions](https://stackoverflow.com/questions/3298597/how-to-get-return-value-from-javascript-in-webview-of-android) on StackOverflow, this is possible with Java. But I need it for Flutter. 

## Proposal

The [url_launcher package](https://pub.dev/packages/url_launcher) is already able to open a web view but I don't understand how to return a value or if it is even possible with url_launcher. So far it only returns a boolean that indicates if the launcher was able to launch the web view.

Is it possible to return data from the web view?

If so, how to?

If not, I request this as a feature.

**Comment by darshankawar** [comment]
Hi @komape,
Just wondering if you have looked at [webview_flutter](https://pub.dev/packages/webview_flutter) plugin to see if that answers your question ?
Thanks.

**Comment by komape** [comment]
Hi,

I just found the webview-flutter package and it looks promising. Thanks!

**Comment by darshankawar** [comment]
@komape,
Good to know that. Do you feel this issue can be closed ? If you get specific questions related to `webview_flutter` plugin, you may open a separate issue with required details.
Thanks.
