### ISSUE TITLE
Failed assertion: line 4016 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by RonadoLong** [flutter/flutter#64135]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by RonadoLong** [comment]
slove

**Comment by tsaievan** [comment]
> slove

idiot
