### ISSUE TITLE
video_player: Error: Type 'VideoPlayerOptions' not found.

### ISSUE THREAD

**Issue by ydotmalik** [flutter/flutter#64159]
I am using flutter_html 1.0.0, which has video_player as a dependency. When I compile my project, I get these errors:
```
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.12/lib/video_player.dart:216:9: Error: Type 'VideoPlayerOptions' not found.
  final VideoPlayerOptions videoPlayerOptions;
        ^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.12/lib/video_player.dart:216:9: Error: 'VideoPlayerOptions' isn't a type.
  final VideoPlayerOptions videoPlayerOptions;
        ^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.12/lib/video_player.dart:272:12: Error: The method 'setMixWithOthers' isn't defined for the class 'VideoPlayerPlatform'.
 - 'VideoPlayerPlatform' is from 'package:video_player_platform_interface/video_player_platform_interface.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_platform_interface-2.0.2/lib/video_player_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMixWithOthers'.
          .setMixWithOthers(videoPlayerOptions.mixWithOthers);
           ^^^^^^^^^^^^^^^^
```

I have another computer which also uses flutter_html 1.0.0, but I see video_player 0.10.11+1 and 0.10.2+5 and in .pub_cache (not sure which one is actually used). I don't have this error. Neither have a reference to VideoPlayerOptions or setMixWithOthers.

**Comment by rvgroup** [comment]
I removed the link to this package and then added it again - the error disappeared.

**Comment by ydotmalik** [comment]
Sorry, could you clarify what you did? You removed flutter_html from pubspec.yaml and added it back?

**Comment by ydotmalik** [comment]
Hmm, that worked.

**Comment by fabriciorodrigues13** [comment]
Good night, I have the same error, could you detail me how you managed to solve the error?


> Hmm, funcionou.

Good night, I have the same error, could you detail me how you managed to solve the error?

**Comment by Edwin-tw** [comment]
I had the same issue.
I fixed it by adding this to the pubspec's dependencies:
`video_player_platform_interface: ^2.1.0`

https://pub.dev/packages/video_player_platform_interface

**Comment by ydotmalik** [comment]
> Good night, I have the same error, could you detail me how you managed to solve the error?

I removed flutter_html from pubspec.yaml, ran pub get, added flutter_html back, and ran pub get again. Next time I compiled, the error went away.

**Comment by fabriciorodrigues13** [comment]
> > Good night, I have the same error, could you detail me how you managed to solve the error?
> 
> I removed flutter_html from pubspec.yaml, ran pub get, added flutter_html back, and ran pub get again. Next time I compiled, the error went away.


Thanks, it worked.

**Comment by mamonraab** [comment]
> I had the same issue.
> I fixed it by adding this to the pubspec's dependencies:
> `video_player_platform_interface: ^2.1.0`
> 
> https://pub.dev/packages/video_player_platform_interface

this work for me

**Comment by adamkoch** [comment]
Seems like `video_player` [depends on](https://github.com/flutter/plugins/blob/db329d71fca07eb1c24d576f8d1dc2bdc0792a55/packages/video_player/video_player/pubspec.yaml#L23) an older version of `video_player_platform_interface` that doesn't have the new `VideoPlayerOptions` class. I think it should be updated to `^2.1.0` to fix these issues properly (without the need to add `video_player_platform_interface` directly as a dependency to your own app).
