### ISSUE TITLE
image asset is not loading on web

### ISSUE THREAD

**Issue by msorange19** [flutter/flutter#64154]
![image](https://user-images.githubusercontent.com/47300623/90652310-c0a48780-e25f-11ea-94be-678cccb5babd.png)

![image](https://user-images.githubusercontent.com/47300623/90651822-4d9b1100-e25f-11ea-95bd-23138978fb09.png)

![image](https://user-images.githubusercontent.com/47300623/90651899-64416800-e25f-11ea-8709-7722ae8e554c.png)

**Comment by TahaTesser** [comment]
Hi @msorange19 
Your `pubspec.yaml` indent is incorrect, it should be like this but i wonder there is no error from pubspec.yaml when run you the app. 


![image (1)](https://user-images.githubusercontent.com/48603081/90656554-04978c80-e260-11ea-8d26-2015418ec637.png)

Can you please provide your `flutter doctor -v` your `flutter run --verbose`, complete `pubspec.yaml ` and a complete reproducible minimal code sample
Thank you

**Comment by msorange19** [comment]
i have fixed indent still showing nothing
![image](https://user-images.githubusercontent.com/47300623/90660465-c43c0c80-e267-11ea-844d-59c6854b4438.png)

**Comment by msorange19** [comment]
@TahaTesser 
here is my yaml file
name: food
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
