### ISSUE TITLE
E/UIFirst (24661): failed to open /proc/24661/stuck_info

### ISSUE THREAD

**Issue by saicharansigiri** [flutter/flutter#64152]
i am facing this issue since i updated my phone to android 10 ,it continuously show's this exception

**Comment by saicharansigiri** [comment]
i am facing this issue since i updated to android 10

**Comment by TahaTesser** [comment]
hI @saicharansigiri 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by saicharansigiri** [comment]
doctor --verbose
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.20.2 at C:\src\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\saicharan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.44.2)
    • VS Code at C:\Users\saicharan\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • RMX1807 (mobile) • 92fe572d • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by saicharansigiri** [comment]
Launching lib\main.dart on RMX1807 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for RMX1807 to report its views...
Debug service listening on ws://127.0.0.1:55790/8hLvX4-FKIM=/ws
Syncing files to device RMX1807...
E/UIFirst (31874): failed to open /proc/31874/stuck_info
I/chatty  (31874): uid=10050(sigiri.co.sq_1) identical 36 lines
E/UIFirst (31874): failed to open /proc/31874/stuck_info
E/UIFirst (31874): failed to open /proc/31874/stuck_info
I/chatty  (31874): uid=10050(sigiri.co.sq_1) identical 10 lines
E/UIFirst (31874): failed to open /proc/31874/stuck_info
E/UIFirst (31874): failed to open /proc/31874/stuck_info
I/chatty  (31874): uid=10050(sigiri.co.sq_1) identical 1 line
E/UIFirst (31874): failed to open /proc/31874/stuck_info
E/UIFirst (31874): failed to open /proc/31874/stuck_info
I/chatty  (31874): uid=10050(sigiri.co.sq_1) identical 5 lines
E/UIFirst (31874): failed to open /proc/31874/stuck_info
E/UIFirst (31874): failed to open /proc/31874/stuck_info
I/chatty  (31874): uid=10050(sigiri.co.sq_1) identical 6 lines
E/UIFirst (31874): failed to open /proc/31874/stuck_info

**Comment by saicharansigiri** [comment]
@TahaTesser  i am really  unable to complete my project because of this issue
 plz look in to it quickly

**Comment by TahaTesser** [comment]
Hi @saicharansigiri 
Can you upgrade to dev and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the problem after upgrade,  Can you please provide your `flutter doctor -v` **with upgrade** , your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by saicharansigiri** [comment]
E/UIFirst ( 4726): failed to open /proc/4726/stuck_info, No such file or directory
E/UIFirst ( 4726): failed to open /proc/4726/stuck_info, No such file or directory
E/UIFirst ( 4726): failed to open /proc/4726/stuck_info, No such file or directory
E/UIFirst ( 4726): failed to open /proc/4726/stuck_info, No such file or directory

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
