### ISSUE TITLE
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════ The following FirebaseException was thrown building Builder: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by San-Zay** [flutter/flutter#64151]
![Screenshot (326)](https://user-images.githubusercontent.com/48524931/90647462-0eb58d00-e258-11ea-88e0-5fb397bfadc6.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
![Screenshot (326)](https://user-images.githubusercontent.com/48524931/90647526-21c85d00-e258-11ea-9e65-d5f435618e35.png)

**Comment by TahaTesser** [comment]
Hi @San-Zay 
This is not an issue with Flutter itself. Please check this https://github.com/FirebaseExtended/flutterfire/issues/3235
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by San-Zay** [comment]
@TahaTesser  sir, Thank you
