### ISSUE TITLE
getting error on release apk, debug apk works fine

### ISSUE THREAD

**Issue by jithinjoycy** [flutter/flutter#64169]
Flutter: Unhandled exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

**Comment by darshankawar** [comment]
Hi @jithinjoycy,
Please provide `flutter doctor -v`, a minimal complete reproducible code sample that shows the issue along with `pubspec.yaml`.
Thanks.

**Comment by darshankawar** [comment]
@jithinjoycy,
Please provide the earlier and downgraded gradle versions that you used.
Thanks.

**Comment by bhanuka96** [comment]
same issue on release apk 😭

**Comment by bhanuka96** [comment]
> same issue on release apk 😭

@darshankawar do you have any solution?

**Comment by bhanuka96** [comment]
I used  package_info: '>=0.4.3 <2.0.0'

**Comment by bhanuka96** [comment]
full error

```
2020-09-15 16:53:41.813 1467-1491/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2020-09-15 16:53:41.813 1467-1491/? E/ANDR-PERF-JNI: gIOPHAl initialized
2020-09-15 16:53:41.814 4097-4170/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:361)
    <asynchronous suspension>
    #2      PackageInfo.fromPlatform (package:package_info/package_info.dart:43)
    <asynchronous suspension>
    #3      SplashLogic.versionCheck (package:orel_go_driver/screens/Splash/logic/splashLogic.dart:15)
    <asynchronous suspension>
    #4      _SplashState.initState.<anonymous closure>.<anonymous closure> (package:orel_go_driver/screens/Splash/splash.dart:21)
    <asynchronous suspension>
```

**Comment by darshankawar** [comment]
@bhanuka96 since this is a closed issue, please consider opening a new one by providing all required details.
Thanks.

**Comment by bhanuka96** [comment]
@darshankawar okay I will do it. 

it's working when I am installing like this
`flutter build apk --no-shrink`

Is it okay to build apk/appbundle for production level(publish to play store)?
