### ISSUE TITLE
Move flutter/infra to googlesource.com so we don't have to wait for changes to mirror

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#64168]
I believe the current mirroring schedule is more than 15 minutes.

Preferably, merge the infra config with flutter.googlesource.com/recipes, so that we can land changes that affect both in a single, atomic CL.

**Comment by digiter** [comment]
@godofredoc Do we want to merge https://github.com/flutter/infra with flutter.googlesource.com/recipes?

**Comment by godofredoc** [comment]
I don't think we are prepared for that yet. We'd need at least one pager with the pros/cons and strategy for the migration.

Couple of things we have been discussing is:

* Why all the teams using LUCI keep configurations from recipes separated.
* What flexibility functionality are we losing by doing that, etc

**Comment by digiter** [comment]
Unassigned myself as this would take longer than I thought.

**Comment by digiter** [comment]
Triage: Next step is merging infra/config with recipes.

**Comment by digiter** [comment]
@godofredoc Could you help with creating a "infra" repository under https://flutter-review.googlesource.com/admin/repos?

**Comment by godofredoc** [comment]
The new repository was created:

https://flutter.googlesource.com/infra

**Comment by CaseyHillers** [comment]
This was finished as part of the ci.yaml work
