### ISSUE TITLE
Update all tool string containing 'pub get' to 'flutter packages get'

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#6417]
We recently changed flutter so that you need to run `flutter packages get`, not `pub get`.

However, some (many?) status messages still say that we are running `pub get` thus potentially causing confusion. For example, when running flutter for the first time:

```
$ flutter doctor
Downloading Material fonts...                        2.2s
Downloading package sky_engine...                    1.4s
Running 'pub get' in sky_engine...                   0.4s
Downloading package sky_services...                  0.4s
Running 'pub get' in sky_services...                 3.1s
Downloading package flutter_services...              0.3s
Running 'pub get' in flutter_services...             1.7s
```

**Comment by sethladd** [comment]
Good catch!

**Comment by warent** [comment]
Turns out there's an option for `flutter create` which is --[no-]pub
If we're going to be replacing references from `pub get` to `flutter packages get`, maybe that option should be renamed as well... any suggestions?

**Comment by abarth** [comment]
Yeah.  Probably should be `--[no]-get-packages`.  (We should probably keep the `--[no]-pub` as a hidden alias during a transition period.
