### ISSUE TITLE
Unable to run `flutter update-packages` on master branch.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#64172]
When I synced to master this morning, I was unable to run `flutter update-packages`.  It said:

```
% flutter update-packages
The current Flutter SDK version is 0.0.0-unknown.                       
                                                                        
Because macrobenchmarks depends on e2e 0.7.0 which requires Flutter SDK version >=1.12.13+hotfix.5 <2.0.0, version solving failed.
Running "flutter pub get" in macrobenchmarks...                         
pub get failed (1; Because macrobenchmarks depends on e2e 0.7.0 which requires Flutter SDK version >=1.12.13+hotfix.5 <2.0.0, version solving failed.)

% flutter --version
Flutter 0.0.0-unknown • channel master • git@github.com:gspencergoog/flutter.git
Framework • revision 606abc915f (25 minutes ago) • 2020-08-20 01:01:06 +0900
Engine • revision 0b330467da
Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)
```

When I run it with `--verbose`, I get:
```
[  +84 ms] executing: [/home/gspencer/code/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 606abc915fb85e6896c85e19c1cf3fa4f526745a
[        ] executing: [/home/gspencer/code/flutter/] git tag --points-at HEAD
[  +18 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/home/gspencer/code/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] v1.20.1-8-g606abc915f
[   +5 ms] Could not interpret results of "git describe": v1.20.1-8-g606abc915f
[   +6 ms] executing: [/home/gspencer/code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/gspencer/code/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:gspencergoog/flutter.git
[  +45 ms] executing: [/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +28 ms] executing: [/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/home/gspencer/code/flutter/] git fetch https://github.com/flutter/flutter.git --tags -f
[ +723 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags -f
[   +4 ms] From https://github.com/flutter/flutter
            * branch                  HEAD       -> FETCH_HEAD
[        ] executing: [/home/gspencer/code/flutter/] git tag --points-at HEAD
[  +23 ms] Exit code 0 from: git tag --points-at HEAD
[        ] executing: [/home/gspencer/code/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] v1.20.1-8-g606abc915f
[        ] Could not interpret results of "git describe": v1.20.1-8-g606abc915f
[   +1 ms] executing: [/home/gspencer/code/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 68 minutes ago
[  +14 ms] Flutter 0.0.0-unknown • channel master • git@github.com:gspencergoog/flutter.git
           Framework • revision 606abc915f (68 minutes ago) • 2020-08-20 01:01:06 +0900
           Engine • revision 0b330467da
           Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)
[ +201 ms] ensureAnalyticsSent: 197ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

Which indicates that the tool is unable to parse `v1.20.1-8-g606abc915f` because it contains a leading `v`, which we stopped using a while ago.

When I look at my tags, I get this:
```
% git tag  | grep '1\.20\.'
1.20.0
1.20.0-0.0.pre
1.20.0-1.0.pre
1.20.0-2.0.pre
1.20.0-3.0.pre
1.20.0-7.0.pre
1.20.0-7.1.pre
1.20.0-7.2.pre
1.20.0-7.3.pre
1.20.0-7.4.pre
1.20.1
1.20.2
v1.20.1
```

The two tags for 1.20.1 point to different revs:
```
% git rev-parse v1.20.1
1b4775952889830e8181fb2997cd5c28418dd8c8
% git rev-parse 1.20.1
2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
```

Which shows a renegade old-style version tag.

Running `git fetch upstream --tags` doesn't fix it.

The only fix appears to be blowing away the `v1.20.1` tag manually.

**Comment by zanderso** [comment]
Dropping the priority to P3 since this doesn't seem too widespread and there's no customer tag. Please feel free to bump it back up if I'm mistaken.

**Comment by gspencergoog** [comment]
No worries, @zanderso. I just set it to P1 because That's what @christopherfujino requested.

**Comment by gspencergoog** [comment]
Objectively, it probably is more like P3, unless we find out that everyone synced that errant tag.

**Comment by jmagman** [comment]
Where did that tag come from?  We should lock down permissions for upstream tagging, if possible.

**Comment by pcsosinski** [comment]
looks like the tag is deleted now?  weird that it was pointing to a relatively new hash (~17 hours)

**Comment by pcsosinski** [comment]
@christopherfujino can we add better handling so a similar tag won't break us?

**Comment by christopherfujino** [comment]
> @christopherfujino can we add better handling so a similar tag won't break us?

Not sure. Unfortunately we're using `git describe --match`, which takes a shell glob, not a regex ¯\_(ツ)_/¯

**Comment by gspencergoog** [comment]
Well, but couldn't we filter the output so that it only contains tags that match a regex, and then only accept a leading 'v' up to version v1.16.3 (which is the last version that used a leading v)?

**Comment by gspencergoog** [comment]
And maybe we should have a test that runs as part of the publish step that checks the main repo tags for errant tags to make sure that nothing unexpected gets created?

And +1 to @jmagman's suggestion to lock down permissions.

**Comment by pcsosinski** [comment]
I'm not sure we can restrict who can create tags (https://github.community/t/feature-request-protected-tags/1742)

**Comment by christopherfujino** [comment]
> Well, but couldn't we filter the output so that it only contains tags that match a regex, and then only accept a leading 'v' up to version v1.16.3 (which is the last version that used a leading v)?

`git describe` doesn't return all matching tags, it determines the nearest ancestor tag (matching the glob), and then reports the current version as the count of commits past that tag.

If we wanted to do more precise filtering of tags, we would need to implement git describe ourselves.

**Comment by christopherfujino** [comment]
Closing this as it appears to have been an isolated instance and has not been seen again.
