### ISSUE TITLE
'context != null': is not true.

### ISSUE THREAD

**Issue by SumanKumar5** [flutter/flutter#64179]
### **> here is the log**

E/flutter ( 1209): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/material/scaffold.dart': Failed assertion: line 1452 pos 12: 'context != null': is not true.
E/flutter ( 1209): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 1209): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 1209): #2      Scaffold.of (package:flutter/src/material/scaffold.dart:1452:12)
E/flutter ( 1209): #3      _RegistrationScreenState.build.<anonymous closure> (package:flash_chat/screens/registration_screen.dart:128:34)
E/flutter ( 1209): <asynchronous suspension>
E/flutter ( 1209): #4      _RegistrationScreenState.build.<anonymous closure> (package:flash_chat/screens/registration_screen.dart)
E/flutter ( 1209): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 1209): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 1209): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 1209): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 1209): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 1209): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 1209): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 1209): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 1209): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 1209): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 1209): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 1209): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 1209): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 1209): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 1209): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 1209): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 1209): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 1209): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 1209): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 1209): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 1209): #25     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 1209): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter ( 1209): 

### **> here is chat.dart file**

import 'package:flutter/material.dart';
import 'package:flash_chat/components/rounded_button.dart';
import 'package:flash_chat/constants.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'chat_screen.dart';
import 'package:modal_progress_hud/modal_progress_hud.dart';

class RegistrationScreen extends StatefulWidget {
  static const String id = 'registration_screen';
  @override
  _RegistrationScreenState createState() => _RegistrationScreenState();
}

class _RegistrationScreenState extends State<RegistrationScreen> {
  final _auth = FirebaseAuth.instance;
  bool showSpinner = false;
  String email;
  String password;
  String username;
  BuildContext ctx;

  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: ModalProgressHUD(
        inAsyncCall: showSpinner,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 24.0),
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Flexible(
                  child: Hero(
                    tag: 'logo',
                    child: Container(
                      height: 200.0,
                      child: Image.asset('images/logo.png'),
                    ),
                  ),
                ),
                SizedBox(
                  height: 48.0,
                ),
                TextFormField(
                  validator: (value) {
                    if (value.isEmpty || !value.contains('@')) {
                      return 'Please enter a valid Email address.';
                    }
                    return null;
                  },
                  keyboardType: TextInputType.emailAddress,
                  textAlign: TextAlign.center,
                  onSaved: (value) {
                    email = value;
                  },
                  decoration:
                      kTextFieldDecoration.copyWith(hintText: 'Email Address'),
                ),
                SizedBox(
                  height: 8.0,
                ),
                TextFormField(
                  validator: (value) {
                    if (value.isEmpty || value.length < 4) {
                      return 'Please enter at least 4 characters.';
                    }
                    return null;
                  },
                  textAlign: TextAlign.center,
                  onSaved: (value) {
                    username = value;
                  },
                  decoration:
                      kTextFieldDecoration.copyWith(hintText: 'Username'),
                ),
                SizedBox(
                  height: 8.0,
                ),
                TextFormField(
                  validator: (value) {
                    if (value.isEmpty || value.length < 7) {
                      return 'Password must be at east 7 characters long.';
                    }
                    return null;
                  },
                  obscureText: true,
                  textAlign: TextAlign.center,
                  onSaved: (value) {
                    password = value;
                  },
                  decoration:
                      kTextFieldDecoration.copyWith(hintText: 'Password'),
                ),
                SizedBox(
                  height: 24.0,
                ),
                RoundedButton(
                  title: 'Register',
                  colour: Colors.blueAccent,
                  onPressed: () async {
                    final isValid = _formKey.currentState.validate();
                    FocusScope.of(context).unfocus();
                    if (isValid) {
                      _formKey.currentState.save();

                      try {
                        final newUser =
                            await _auth.createUserWithEmailAndPassword(
                                email: email, password: password);
                        if (newUser != null) {
                          Navigator.pushNamed(context, ChatScreen.id);
                        }
                      } on PlatformException catch (e) {
                        var message =
                            'An error occurred, Please check your credentials!';

                        if (e.message != null) {
                          message = e.message;
                        }

                        Scaffold.of(ctx).showSnackBar(
                          SnackBar(
                            content: Text(message),
                            backgroundColor: Theme.of(ctx).errorColor,
                          ),
                        );
                      } catch (e) {
                        print(e);
                      }
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by PixelToast** [comment]
The context you pass to `Scaffold.of` is `ctx`, which is null because you never assign it, I suggest removing it entirely and just using the `context` variable available to you already.

**Comment by SumanKumar5** [comment]
I didl

> The context you pass to `Scaffold.of` is `ctx`, which is null because you never assign it, I suggest removing it entirely and just using the `context` variable available to you already.

I did this in the first place and same error occurred l. So I tried with buildcontext

**Comment by SumanKumar5** [comment]
solution:-- [https://stackoverflow.com/questions/63501468/flutter-error-context-null-is-not-true](url)
