### ISSUE TITLE
Update 'auto formatting' wiki with atom/intellij changes

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#6418]
https://github.com/flutter/flutter/wiki/Early-Access%3A-Auto-Formatting

**Comment by devoncarew** [comment]
Also, is it still early access?

**Comment by mit-mit** [comment]
Not sure. @sethladd

**Comment by sethladd** [comment]
We should move this page over to the website, it's no longer in early access. And yeah, we should update this to IntelliJ. :)

On this (new) page we can also mention the difference between "format with intellij" or "format with dartfmt", which I believe are two different actions in IntelliJ?
