### ISSUE TITLE
Pigeon: Add support for enums

### ISSUE THREAD

**Issue by Tywholland** [flutter/flutter#64192]
## Use case

We'd like to be able to use enums in our pigeon dart file, and use those enums in native code.

## Proposal

We're currently working around this by using Strings instead of enums, but if the code gen could do something like convert dart enums to strings, and then convert strings to enums in java/objc, we could gain a bit of pseudo type safety.

**Comment by GaryQian** [comment]
https://github.com/flutter/packages/pull/331
