### ISSUE TITLE
Monitor prod capacity to increase max_concurrent value for engine configs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64198]
The engine repo needs to run builders on every commit which can potentially increase the capacity needs by 3. To avoid the potential problem of the engine using all the available capacity and affecting sdk builds we are decreasing the total number of concurrent builds to 3 but we would like this number to get back to 6.

In order to increase the max concurrent builds to 6 we will be collecting data for a couple of weeks and start negotiating a capacity increase.

**Comment by godofredoc** [comment]
@keyonghan can you please own the monitoring part? I'll start separate bugs for the capacity requests

**Comment by godofredoc** [comment]
Thanks for the info, can we calculate the requirements per platform?

**Comment by keyonghan** [comment]
Based on LUCI executions between 08/01-08/15 (prod pool). We need to have 5 more Linux bots, 3 more Windows bots, and 3 more Mac bots to compensate the effect of the max_concurrent value change.

Linux bots number: 40; Linux Engine builds number: 1776; All Linux builds number: 4061
 => 1776/4061*40*30%=5.25
Mac bots number: 11; Mac Engine builds number: 1554; All Mac builds number: 1716
 => 1554/1716*11*30%=2.98
Windows bots number: 22; Windows Engine builds number: 666; All Windows builds number: 1475
 => 666/1475*22*30%=2.98

**Comment by godofredoc** [comment]
Capacity was increased and schedules were enabled. Prod capacity goes to 50% after working hours and weekends and Try capacity goes to 33% after working hours and weekends.

New capacity:

22 -> 40 win pro
40 -> 60 debian prod
40 -> 60 win try
80 -> 100 debian try
