### ISSUE TITLE
Longpressing on an unselected word in a text field should select it (iOS)

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#64190]
## Steps to Reproduce

  1. Run an app with a text field on an iOS device (e.g. the code below).
  1. Enter some text in the field.
  1. Long press on a word that is not currently selected.
  1. The cursor is moved to that position in Flutter, but on native iOS, the word is selected.

On native, longpressing on the collapsed cursor allows it to be dragged around.  We should make sure that behavior is preserved when this is fixed.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Comment by justinmc** [comment]
There is some code deduplication that can probably happen when this is fixed. See https://github.com/flutter/flutter/pull/63994/files#r473348460.

**Comment by darshankawar** [comment]
Issue replicable on latest stable (1.20.2). Tested on iphone 6s and observed that tapping longpress on an entered text shows `paste, select all` toolbar, but doesn't select the word.

![IMG-0198](https://user-images.githubusercontent.com/67046386/91426262-e510ed00-e879-11ea-9b02-af9af970cb37.PNG)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by Renzo-Olivares** [comment]
cc @justinmc can this be closed? The behavior on iOS 16 is long pressing moves the cursor to the pressed position, which matches the current flutter behavior.

**Comment by justinmc** [comment]
@Renzo-Olivares Is your edit referring to native iOS 16 behavior?  How did you reproduce that behavior?  I tried in Messages and it still just placed the cursor even when the field wasn't focused, but I realized I was using iOS 15.  Trying to upgrade now.

Otherwise if that's not something that we need to implement in Flutter then I agree this should be closed.

**Comment by Renzo-Olivares** [comment]
@justinmc I tried this on iOS 16 on the notes app. I am however not seeing the same behavior in the Messages app, it only places the cursor at the long press position. Maybe that behavior is custom to the notes app then?

**Comment by justinmc** [comment]
The Files app also seems to place the cursor.  I say let's close this!
