### ISSUE TITLE
PageableList loses position after rotation

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#642]
Repro:

Run widgets/pageable_list.dart on your phone
- Scroll to Card 4.
- Rotate the phone 90 degrees and back

The list ends up showing the wrong card that's half scrolled.

**Comment by abarth** [comment]
The problem is that we remember what page to show based on the scroll offset instead of the page number.  When you rotate, the offset for the same page is different.

/cc @HansMuller

**Comment by Hixie** [comment]
@HansMuller You fixed this, right?

**Comment by HansMuller** [comment]
Yes - https://github.com/flutter/flutter/issues/652
