### ISSUE TITLE
Simple animation CPU usage regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#64205]
For a simple animation with a single `LinearProgressIndicator`, Flutter used to only use ~15% CPU on iPhone 6s back in Dec 2019 (e.g., 7874bca248dafc109f5745f8766ece37d203fd51) after the optimization mentioned in [#14104][1] (LinearProgressApp is the simple animation app).

Now, that simple animation on iPhone 6s has ~25% CPU usage with OpenGL and ~20% CPU usage with Metal for Flutter 77b4505 in my local test on iPhone 6s. (To switch between Metal and OpenGL, see [this comment][2].)

Considering that the measurement tool might have changed between Dec 2019 and Aug 2020, I also did a local test using the same version of Xcode/instruments, and only differ the Flutter version (7874bca2 vs. 77b4505). I can still see 77b4505 to have about 7% more CPU usage than 7874bca2 (both are measured using OpenGL). 

So some regressions seem to have slipped through while we're having problem with https://github.com/flutter/flutter/issues/45435.

We need to either
(1) bisect the commit and use the Xcode/instruments to figure out which commit caused the regression
or
(2) debug the current code to see if we're introducing `BackdropFilterLayer` unnecessarily for a simple animation, or if we're introducing an offscreen layer unnecessarily without a `BackdropFilterLayer`.

[1]: https://github.com/flutter/engine/pull/14104#issuecomment-561931914
[2]: https://github.com/flutter/flutter/issues/61045#issuecomment-655658088

**Comment by liyuqian** [comment]
CC @kf6gpe for performance regressions, and CC @iskakaushik who seems to be working on some high CPU usage issue on Mac that might be related to this.

**Comment by flar** [comment]
I'm starting a bisect.

**Comment by chinmaygarde** [comment]
Triage: @jason-simmons mentions that the additional GC's [due to this patch](https://github.com/flutter/engine/pull/20673) was causing extra CPU usage. Not sure if this is relevant.

**Comment by liyuqian** [comment]
@chinmaygarde @jason-simmons : maybe you're referring to a newer regression in https://github.com/flutter/flutter/issues/64515 ? This issue was created for a potential older and milder regression.

**Comment by kf6gpe** [comment]
@liyuqian Did you want to try re-running these given Jim's tests? Or look into a build backing out the patch @chinmaygarde noted in the comment above?

**Comment by liyuqian** [comment]
I just reran the test on latest master Flutter using 3 different ways:
1. Default profile build with Metal and Jim's readback optimization
2. Local profile engine build with Metal but without Jim's readback optimization
3. Local profile engine build with OpenGL but without Jim's readback optimization

Both 1 and 2 have ~25% CPU usages and 3 has ~30% CPU usage. The 5% CPU difference here is similar to the 5% CPU difference in the original PR [#14104][1]. So Jim's optimization seems to be working properly.

I then tried to run the test using an old Flutter. But I wasn't able to run the app in profile mode both from Xcode or command line. As Xcode and iOS versions are moving targets that may become incompatible with old Flutter tools, I think reproducing this would be more difficult as time goes by.

I'm going to close this issue as
- We just verified that Jim's optimization is still working.
- Even with ~25% CPU usage, the energy usage reported by Xcode is still low and green. This is very different from the high energy use when we originally started the energy work with 20% CPU usage.
- It's difficult for us to further investigate this as old tools become incompatible with new Xcode and iOS versions.

[1]: https://github.com/flutter/engine/pull/14104#issuecomment-561931914

**Comment by flar** [comment]
FWIW, when I mentioned I was going to bisect in a comment above, I pretty quickly ran into the same Xcode version issues that liyuqian mentioned and I never got back to figuring them out and so it went nowhere.

**Comment by flar** [comment]
> I just reran the test on latest master Flutter using 3 different ways:
> 
> 1. Default profile build with Metal and Jim's readback optimization
> 2. Local profile engine build with Metal but without Jim's readback optimization
> 3. Local profile engine build with OpenGL but without Jim's readback optimization
> 
> Both 1 and 2 have ~25% CPU usages and 3 has ~30% CPU usage. The 5% CPU difference here is similar to the 5% CPU difference in the original PR [#14104](https://github.com/flutter/engine/pull/14104#issuecomment-561931914). So Jim's optimization seems to be working properly.

I don't understand this experiment.

First, the only apples-to-apples comparison of with and without my fix is #1 vs #2 and both of them had the same CPU %. This would make sense because I don't think that Metal triggers my fix in the first place. But, this also doesn't test my fix because my fix isn't involved in either 1 or 2.

My fix does do something with OpenGL (case #3), but you only tested that without my optimization. So, how does this verify my fix?

**Comment by liyuqian** [comment]
Ah, yes, I forgot to add a case 4. Now it's added and it's ~25% CPU usage as expected.
