### ISSUE TITLE
[flutter_tools] There should be an integration test that verifies all cached binaries exist

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#64209]
Add a test that would have caught [this](https://github.com/flutter/flutter/issues/64041).

Something like:

```
flutter config --enable-web --enable-linux-desktop --enable-macos-desktop --enable-windows-desktop
flutter precache --all-platforms
```

**Comment by jmagman** [comment]
This would be a good place to do https://github.com/flutter/flutter/issues/50387 as well.

**Comment by christopherfujino** [comment]
This is now covered by this test: https://github.com/flutter/flutter/blob/master/dev/tools/test/codesign_integration_test.dart
