### ISSUE TITLE
Document differences between BackdropFilter and ImageFiltered

### ISSUE THREAD

**Issue by flar** [flutter/flutter#64204]
## Use case

Developers occasionally need to apply an ImageFilter to part of their Widget tree. We created a BackdropFilter widget to satisfy a common use of that technique, but there were other uses for which it was not as suited, such as blurring a widget in isolation. It is possible to use BackdropFilter to achieve those other results, but the construction is not obvious and there are a number of pitfalls that a developer can fall into.

More recently a new ImageFiltered widget was added which more directly serves the other needs to filter a part of an app with a more straightforward construction and an easier to manage behavior. But, developers continue to use BackdropFilter as it has been around longer and has more awareness built for it.

## Proposal

Document the existence of the two widgets in each other's doc comments and provide examples and guidance on when to use each.

**Comment by liyuqian** [comment]
CC @redbrogdon @filiph as some example code (bad performance vs good performance) in DartPad might be useful here in API docs. Other general feedback or help from DevRel to improve this [API doc][1] would also be appreciated.

[1]: https://master-api.flutter.dev/flutter/widgets/ImageFiltered-class.html

**Comment by filiph** [comment]
This calls for a widget of the week. 

Can I get more information on how `ImageFiltered` is different from `BackdropFilter`? Is it "just" simpler (as in, wrap one child and apply the filter to it, instead of constructing a Stack)? Or are there other significant differences? Is there a design doc for ImageFiltered, for instance?

**Comment by filiph** [comment]
I've scripted a widget of the week. It will go out in about a month from now. I've also assigned this issue to me and will address the API docs issue. Cheers!

**Comment by flar** [comment]
BackdropFilter is designed to blur an entire background behind its child (potentially with clipping to control its area of effect). That is something that apps sometimes need to do.

ImageFiltered is designed to blur a single child. Apps sometimes also need to do that.

BackdropFilter was not designed to blur a single widget. Because we created BackdropFilter first and didn't create ImageFiltered alongside it, developers found a clever way to use BackdropFilter in a Stack to blur another widget. That doesn't mean that ImageFiltered is simply an optimization for the other technique. The two are different and the use of one to accomplish the other was a clever workaround.

**Comment by flar** [comment]
Thanks for taking this on!

**Comment by flar** [comment]
I see the PR for the change to the doc comments.

Will there be additional work on this via the widget of the week? Is that tracked somewhere?

**Comment by filiph** [comment]
Yes, the widget of the week is in the works but tracked separately (in buganizer). Once that's out, I'll update the `ImageFiltered` API docs once again to include the video.

I also noticed that the old Widget of the Week video for `BackdropFilter` starts with "ImageFilter", which is confusing. I asked the video team to release a fixed version. Also tracked separately (as all our video work).
