### ISSUE TITLE
LUCI details page is difficult to navigate

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#64208]
Today I tried to land https://github.com/flutter/flutter/pull/62635

There were test failures:

![Screen Shot 2020-08-19 at 5 26 33 PM](https://user-images.githubusercontent.com/1377460/90702872-33ead100-e241-11ea-993d-97bfc68cfcb0.png)

The "details" link leads to this page. It's not clear what "Step('display builds.build(s) failed') (retcode: 1)" means, however one can try re-running the test from here. 

![Screen Shot 2020-08-19 at 5 28 02 PM](https://user-images.githubusercontent.com/1377460/90703124-c9866080-e241-11ea-855d-7f0d53606927.png)

Re-running the test didn't magically improve the situation, so I tried following the "View more details on flutter-dashboard" link. That link leads to a page packed full of a remarkable amount of information, most of which doesn't appear to be relevant to discovering what's gone wrong with the failed test. There are many links in likely red areas, but only the one indicated by the arrow, leads closer to information about the source of the test failure.

![Screen Shot 2020-08-19 at 5 46 51 PM](https://user-images.githubusercontent.com/1377460/90703959-03586680-e244-11ea-8bad-fd037ae1056b.png)

The destination page looks similar, and it includes another link in a likely red box (albeit under a rather opaque heading) which leads to the transcript from the failing test.

![Screen Shot 2020-08-19 at 5 50 29 PM](https://user-images.githubusercontent.com/1377460/90704196-b4f79780-e244-11ea-9760-833ba201529c.png)

Having got this far, the failure is still hard to reason about:
```dart
02:45 +4675 ~13 -2: /b/s/w/ir/k/flutter/packages/flutter/test/rendering/viewport_test.dart: Nested viewports (same orientation) showOnScreen not in view of neither inner nor outer                    
02:45 +4675 ~13 -2: /b/s/w/ir/k/flutter/packages/flutter/test/rendering/reattach_test.dart: objects can be detached and re-attached: layout [E]                                                        
  'package:flutter/src/semantics/semantics.dart': Failed assertion: line 0: 'value != null': is not true.
```

It turns out that the people who have been working on this problem can tell you that it's been recently fixed and that it will likely go away if the PR is sync'd up and resubmitted.

So. The reason for going through all of this is to observe that it's difficult to discover what's gone wrong because it's difficult to navigate the reports we're providing. I'm coming at this from within Google and I have to assume that it's even more difficult to navigate for an external developer.

I hope we can find a way to make navigating these reports easier.

**Comment by godofredoc** [comment]
Thanks for the report: I can see a few easy improvement to the UI:

1. Do not show the buildbucket.collect step.
2. In display builds print the name of the shard being run.
3. Present the inner failures in the github UI instead of the the wrapping step failure.

To see details we'll still need 3 clicks - one in the github ui to get to the orchestrator task - one more to go to the shard task - and the final one to get to the logs.

**Comment by godofredoc** [comment]
Moving this bug to the sdk migration project.

**Comment by christopherfujino** [comment]
Also, [this build](https://ci.chromium.org/p/flutter/builders/try/testonly_devicelab_tests/512?) timed out after 3 hours but the only visible messaging was "infra failure". We should explicitly call out in the milo UI when a timeout has occurred.

**Comment by goderbauer** [comment]
In https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/2323? I had to check all 8 links in the red "get" box to get to the actual exception. It would be nice if there was an easier way to see why something failed.

**Comment by christopherfujino** [comment]
> In https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/2323? I had to check all 8 links in the red "get" box to get to the actual exception. It would be nice if there was an easier way to see why something failed.

we chatted in discord, I pointed out that below the "get" box the results of each individual drone build is listed with its actual status color. Still, this is admittedly a confusing UI.

**Comment by pedromassango** [comment]
By clicking on `stdout` link we are able to actually find the useful information about the failing tests.

![Screen Shot 2020-10-14 at 22 46 52](https://user-images.githubusercontent.com/33294549/96049371-d3a69300-0e6f-11eb-8392-467a4ca60cfa.png)

**Comment by Hixie** [comment]
Ideally we'd just show the entire error log on GitHub and never have to click through to Luci. That's how it worked under Cirrus (though admittedly Cirrus never showed the whole log so you did sometimes have to click one extra link to see the whole thing)

**Comment by godofredoc** [comment]
@Hixie what would it be a good # of lines to add to the github UI? 100 last lines?

**Comment by Hixie** [comment]
What's the maximum we can show?

**Comment by godofredoc** [comment]
> What's the maximum we can show?

The api does not specify limits but based on the space available in github UI I'd recommend < 100 lines.

**Comment by Hixie** [comment]
Isn't it a web page? Like, it can scroll?

**Comment by fkorotkov** [comment]
It can be maximum of 65535 characters (see https://github.com/github/docs/issues/3765)

**Comment by pedromassango** [comment]
I would be good to show the failed test logs only as it is what we will be looking for

**Comment by godofredoc** [comment]
Here is a second CL to propagate the data to github:

https://flutter-review.googlesource.com/c/recipes/+/12022

**Comment by godofredoc** [comment]
Update on the size of the summary markdown: LUCI supports a max of 4332 chars in the summary markdown.

**Comment by godofredoc** [comment]
This is how the summary looks in LUCI UI: https://ci.chromium.org/p/flutter/builders/prod/Windows%20gradle_plugin_light_apk_test/2134

This is how the summary looks in github UI: https://github.com/flutter/flutter/pull/80015/checks?check_run_id=2293770244

**Comment by keyonghan** [comment]
Till this moment, changes have been implemented to address/mitigate this issue:
- Deprecated builders with shards, which means no consolidated subshard builds in a single parent build
- Both luci build page and github UI are showing last lines of the stdout log
- Reduced the inappropriate url time of `View more details on flutter-dashboard` link on GitHub UI check runs page
- Separated infra failures (purple) from test failures (red)

More improvements to follow:
- [ ] Add clear message about what a developer is expected to do when an infra failure happens (whether a retry is needed? where to file an infra bug? where to look for help?)
- [ ] Add clear message about what a developer is expected to do when a test failure happens (linking to the failed test file? where the failure has happened in earlier PRs?)
- [ ] Improve flutter build dashboard: for example the button `DOWNLOAD ALL LOGS` is confusing in the task box.

**Comment by keyonghan** [comment]
> * [ ]  Improve flutter build dashboard: for example the button `DOWNLOAD ALL LOGS` is confusing in the task box.

Now it is updated to `VIEW LOGS`
<img width="326" alt="Screen Shot 2021-06-01 at 4 39 39 PM" src="https://user-images.githubusercontent.com/54558023/120402941-1bdbce00-c2f8-11eb-9ad3-4ac137ad3ce8.png">

**Comment by keyonghan** [comment]
The wiki link is now available in the check run page.
<img width="1137" alt="Screen Shot 2021-06-09 at 10 57 48 AM" src="https://user-images.githubusercontent.com/54558023/121405413-e2b3e700-c911-11eb-8acc-3c40b2443037.png">

**Comment by HansMuller** [comment]
@keyonghan - (per https://github.com/flutter/flutter/issues/64208#issuecomment-857920172): will most outside-of-Google developers understand what "LUCI" refers to? Maybe use "understanding" instead of "triaging"; rely on a simpler language.

**Comment by keyonghan** [comment]
> @keyonghan - (per [#64208 (comment)](https://github.com/flutter/flutter/issues/64208#issuecomment-857920172)): will most outside-of-Google developers understand what "LUCI" refers to? Maybe use "understanding" instead of "triaging"; rely on a simpler language.

Makes sense. PTAL: https://github.com/flutter/cocoon/pull/1244

**Comment by keyonghan** [comment]
New update is ready:
<img width="943" alt="Screen Shot 2021-06-10 at 10 05 08 AM" src="https://user-images.githubusercontent.com/54558023/121567479-75688a80-c9d3-11eb-8de0-0979e38d170f.png">

**Comment by keyonghan** [comment]
Proposed improvements in https://github.com/flutter/flutter/issues/64208#issuecomment-841470687 are now ready. 

Closing this issue. Please reopen a new one for further issues/requests.
