### ISSUE TITLE
InteractiveViewer should support mouse scrolling

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#64210]
## Use case

We use @justinmc's [`InteractiveViewer`](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html) widget for vertical lists that can have an arbitrary width (the items can have arbitrary widths).  
→ you can obviously apply the same to the reverse dimensions :)

This is very nice for allowing this use case. However, what is a bummer that the mouse scrolling characteristic is lost due to this widget.  
Users find this to be really unintuitive on web.

## Proposal

The `InteractiveViewer` should have something like a `scrollingDirection` attribute, which determines the [`Axis`](https://api.flutter.dev/flutter/painting/Axis-class.html) along which a mouse scroll will scroll the `InteractiveViewer`.

In my example, this would allow to use the mouse scroll wheel (or trackpad scrolling) to scroll vertically while scrolling horizontally still needs a drag.

**Comment by justinmc** [comment]
That sounds reasonable, thanks for opening this issue.  Maybe if scaling is disabled via `scaleEnabled` we could make scroll events cause panning by default?  Or maybe that's too simplistic and we do need a parameter, because people might not want the behavior to change if they temporarily disable scale, for example.

We should also think about mice that have directional scrolling, like Apple's mice.

**Comment by creativecreatorormaybenot** [comment]
@justinmc That sounds very good! 👍🏽

Actually, just yesterday we also discovered the case of directional scrolling. Any trackpad usually allows scrolling in all directions and that would be a great fit :)  
An example for this would be **Lucidchart** (in case you know it). It allows to pan using trackpads by default.

Regarding your point of automatic panning on scroll: I think that this is very reasonable because it seems like it would be the natural choice. If we create an interactive viewer, we probably expect it to be interactive.  
In all of the use cases that I had, I **only** used it for panning actually and disabled scaling because of that.

**Comment by justinmc** [comment]
Ah thanks for the Lucidchart example.  It looks like they do panning with bidirectional scrolling by default, and holding down the option key + scrolling does zoom. Come to think of it, I think this is how photo editors like Gimp and Photoshop work on desktop too.

I think we can do a `panByScrolling` boolean to enable this behavior, or even a `controlScheme` enum with these two options.

**Comment by Schwusch** [comment]
I just copied the `InteractiveViewer` class and replaced the `_receivedPointerSignal(PointerSignalEvent)` function with this
```dart
void _receivedPointerSignal(PointerSignalEvent event) {
    if (event is PointerScrollEvent) {
      if (_gestureIsSupported(_GestureType.scale)) {
        final childRenderBox =
        _childKey.currentContext.findRenderObject() as RenderBox;
        final childSize = childRenderBox.size;
        final scaleChange = 1.0 - event.scrollDelta.dy / childSize.height;
        if (scaleChange == 0.0) {
          return;
        }
        final focalPointScene = _transformationController.toScene(
          event.localPosition,
        );
        _transformationController.value = _matrixScale(
          _transformationController.value,
          scaleChange,
        );

        // After scaling, translate such that the event's position is at the
        // same scene point before and after the scale.
        final focalPointSceneScaled = _transformationController.toScene(
          event.localPosition,
        );
        _transformationController.value = _matrixTranslate(
          _transformationController.value,
          focalPointSceneScaled - focalPointScene,
        );
      } else if (_gestureIsSupported(_GestureType.pan)) {
        final childRenderBox =
        _childKey.currentContext.findRenderObject() as RenderBox;
        final childSize = childRenderBox.size;
        final yScroll = -event.scrollDelta.dy;
        final xScroll = -event.scrollDelta.dx;
        _transformationController.value = _matrixTranslate(
          _transformationController.value,
          Offset(xScroll, yScroll),
        );
      }
    }
  }
```
Scaleing takes precedence, but if that's disabled the widget works like a charm with mousepads or scrollwheels.
Now I am just missing scrollbars, in both directions.

**Comment by hacker1024** [comment]
It looks like a rotation feature is in the works (#57698); it'd be great if a rotation touch gesture on macOS and iPadOS could trigger that as well.

**Comment by zhou67832033** [comment]
@justinmc  InteractiveViewer should support scrollbars, in both directions. Thanks!

**Comment by justinmc** [comment]
@zhou67832033 Thanks, that's a great example of 2d mouse scrolling with scroll bars!

**Comment by zhou67832033** [comment]
> @zhou67832033 Thanks, that's a great example of 2d mouse scrolling with scroll bars!

Are there currently plans to support Scrollbar feature?

**Comment by zhou67832033** [comment]
> scrollbars



> I just copied the `InteractiveViewer` class and replaced the `_receivedPointerSignal(PointerSignalEvent)` function with this
> 
> ```dart
> void _receivedPointerSignal(PointerSignalEvent event) {
>     if (event is PointerScrollEvent) {
>       if (_gestureIsSupported(_GestureType.scale)) {
>         final childRenderBox =
>         _childKey.currentContext.findRenderObject() as RenderBox;
>         final childSize = childRenderBox.size;
>         final scaleChange = 1.0 - event.scrollDelta.dy / childSize.height;
>         if (scaleChange == 0.0) {
>           return;
>         }
>         final focalPointScene = _transformationController.toScene(
>           event.localPosition,
>         );
>         _transformationController.value = _matrixScale(
>           _transformationController.value,
>           scaleChange,
>         );
> 
>         // After scaling, translate such that the event's position is at the
>         // same scene point before and after the scale.
>         final focalPointSceneScaled = _transformationController.toScene(
>           event.localPosition,
>         );
>         _transformationController.value = _matrixTranslate(
>           _transformationController.value,
>           focalPointSceneScaled - focalPointScene,
>         );
>       } else if (_gestureIsSupported(_GestureType.pan)) {
>         final childRenderBox =
>         _childKey.currentContext.findRenderObject() as RenderBox;
>         final childSize = childRenderBox.size;
>         final yScroll = -event.scrollDelta.dy;
>         final xScroll = -event.scrollDelta.dx;
>         _transformationController.value = _matrixTranslate(
>           _transformationController.value,
>           Offset(xScroll, yScroll),
>         );
>       }
>     }
>   }
> ```
> 
> Scaleing takes precedence, but if that's disabled the widget works like a charm with mousepads or scrollwheels.
> Now I am just missing scrollbars, in both directions.

Have you implemented scrollbars, can you share it?

**Comment by justinmc** [comment]
No one is currently working on scrollbars for InteractiveViewer that I'm aware of, but it seems like a good idea.

**Comment by Schwusch** [comment]
> Have you implemented scrollbars, can you share it?

@zhou67832033 I have not, sorry

**Comment by marcosagni98** [comment]
vertical scroll should work using the scrollWheel and then the zoom using control + scroll

**Comment by creativecreatorormaybenot** [comment]
Yes precisely, this is rather straight-forward to implement. You can see an example I built in [this demo](https://twitter.com/creativemaybeno/status/1384099462897831937?s=20).

**Comment by nguyenxndaidev** [comment]
It would be nice if scrollbar is supported by InteractiveViewer. Currently, I have a some troubles when using nested scrollbars for the same purpose.
See: https://stackoverflow.com/q/67461431/8228301

**Comment by justinmc** [comment]
This works for panning by scrolling: https://github.com/flutter/flutter/compare/master...justinmc:iv-scroll-pan

However, what are all of the use cases that we want to support here?  Some people have mentioned that scrolling should only pan in the vertical direction and shift+scroll should pan horizontally, others seem to want slightly different behavior.  Can we support everyone's use cases using an enum like in that branch?  Or do we need something more powerful?

**Comment by justinmc** [comment]
Related: Another issue calls for pinch-to-zoom with the trackpad https://github.com/flutter/flutter/issues/63084

**Comment by creativecreatorormaybenot** [comment]
@justinmc having written support for this in Flutter myself, looking at other Flutter web apps like Rive (+ looking at their sources), and working with many apps supporting this (Miro, Lucidchart, etc.), this is the default behavior I have observed:

* Free panning using trackpad should be supported if the trackpad allows for it (example is MacBook).
* Locked panning if you only have mouse wheel (or some other kind of scroll lock): regular scrolls vertically, with <kbd>shift</kbd> it scrolls horizontally.
* Shift should also lock to horizontal panning on trackpad, so no need to do any special handling (it just works perfectly implicitly).
* Pinching on trackpad should zoom.
* Holding <kbd>ctrl</kbd> (command on macOS) & scrolling should zoom instead of pan.
* Using control / command and the plus & minus buttons should zoom in & out.


@justinmc tbh, you can probably just go to `editor.rive.app` and copy their behavior because it is written in Flutter Web and does exactly what all other major apps do.

The behavior is not too complicated to implement perfectly. I can share my code if that helps, but there is one blocker: Rive and I both had to override some default DOM behaviors (see my answers on SO, i.e. [this one](https://stackoverflow.com/a/67039291/6509751) and [this one](https://stackoverflow.com/a/67039463/6509751)). Also, you might want to add some "polyfill"-esque code to make sure the behavior is consistent across all browsers. You can check the Rive source for that.

Overall, I think this is the expected behavior everywhere looking at all major apps and it is fairly trivial to get perfectly working with a bit of HTML event handling.

**Comment by xvrh** [comment]
@justinmc Thank you for the `InteractiveViewerScrollControls.scrollPans` code. I really like the idea.
I was able to easily build the "press CMD/CTRL to zoom" interaction:
```dart
class __FlowGraphState extends State<_FlowGraph> {
  bool _isZoomKeyPressed = false;

  @override
  void initState() {
    super.initState();
    RawKeyboard.instance.addListener(_onKeyPressed);
  }

  void _onKeyPressed(RawKeyEvent event) {
    var zoomKeyPressed = event.isControlPressed || event.isMetaPressed;
    if (_isZoomKeyPressed != zoomKeyPressed) {
      setState(() {
        _isZoomKeyPressed = zoomKeyPressed;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return InteractiveViewer(
      scrollControls: _isZoomKeyPressed
          ? InteractiveViewerScrollControls.scrollScales
          : InteractiveViewerScrollControls.scrollPans,
      maxScale: 1.5,
      minScale: 0.1,
      constrained: false,
      boundaryMargin: EdgeInsets.all(5000),
      child: child,
    );
  }

  @override
  void dispose() {
    RawKeyboard.instance.removeListener(_onKeyPressed);
    super.dispose();
  }
}
```

The only thing I would change in the `scrollPans` code is to adapt the panning to feel the same whatever the scale is.
So divide the translation by the currentScale:
```dart
var currentScale = _transformationController!.value.getMaxScaleOnAxis();
final Offset translation = Offset(-event.scrollDelta.dx, -event.scrollDelta.dy) / currentScale;
```

**Comment by rodydavis** [comment]
Currently the PointerScrollEvent does not send the implicit "ctrlKey' == true when the gesture is zooming vs panning. You can keep track of the control key separately with the keyboard listener.

```dart
 if (event is PointerScrollEvent) {
    // TODO: Scale and Pan at the same time
    if (_controlPressed) {
      double zoomDelta = (-event.scrollDelta.dy / 300);
      final scale = zoomDelta;
      final origin = controller.mousePosition;
      print("scale: ${scale} at origin: ${origin}");
    } else {
      final panDelta = -event.scrollDelta;
      print("pan: ${panDelta}");
    }
  }
```

You can capture this information correctly with dart:html and the control key is implicitly true when its a zoom gesture on the trackpad:

```dart
html.document.body!.addEventListener('wheel', (e) {
      e.preventDefault();
      final event = e as html.WheelEvent;
      final origin = event.offset;
      if (e.ctrlKey == true) {
        double scale = 1;
        if (event.deltaY < 0) {
          scale = 0.1;
        } else {
          scale = -0.1;
        }
        print("scale: ${scale} at origin: ${origin}");
      } else {
        final panDelta = Offset(-event.deltaX.toDouble(), -event.deltaY.toDouble());
        print("pan: ${panDelta}");
      }
    }, false);
```

Wheel Event:

https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event

You can pan and zoom with the same event with this demo:

https://rodydavis.github.io/html-canvas-utilities/

**Comment by Piinks** [comment]
I recently looked into InteractiveViewer and making it a 2D scrollable under the hood, and unfortunately, that is not something we are likely to do. Retro-fitting this for scrolling would likely require a bunch of breaking changes to this widget. 
This is because InteractiveViewer is not actually a scrolling widget.
Instead I have been working on a separate 2D scrollable that will be very similar to this. In contrast, it will work with all of the existing scrolling constructs, like scroll notifications, scrollbars, etc.

Regarding this issue though, there are a lot of comments with varying feature requests. I'd like to resolve these. Since there are several, we will likely need to split them out individual issues so we can get them assigned and addressed. 

From what I gather above:

1. support for panning the interactive viewer with pointer scrolling instead of scaling
2. trackpad pinch to scale
  -  this looks like it may have been resolved by https://github.com/flutter/flutter/pull/89944
  - or https://github.com/flutter/engine/pull/31593, see https://github.com/flutter/flutter/issues/63060
  - also https://github.com/flutter/flutter/issues/63084
3. keyboard modifiers on pointer scrolling
4. platform specific behaviors
5. device specific behaviors (trackpad v mouse, etc)

Can anyone confirm some of this for us? With a clear picture of what is needed, we can set about having it done. :) Thanks!

**Comment by Piinks** [comment]
Great! Thank for the feedback. I have updated the list above.

**Comment by creativecreatorormaybenot** [comment]
> I recently looked into InteractiveViewer and making it a 2D scrollable under the hood, and unfortunately, that is not something we are likely to do. Retro-fitting this for scrolling would likely require a bunch of breaking changes to this widget.

I would like to point out that adding mouse scrolling to `InteractiveViewer` does not _require_ "Retro-fitting this for scrolling", which also means that it would not _require_ "a bunch of breaking changes to this widget". I do understand that making it a scrollable would require that, but do we need to make it a scrollable?

@Piinks Is the new widget you are planning to build meant to replace `InteractiveViewer`? Otherwise, I think it might be worth to challenge the requirement of making it integrate with scroll notifications et al.

**Comment by Hixie** [comment]
@creativecreatorormaybenot Mouse scrolling on some platforms (macOS notably) requires scrolling physics, and implementing that requires either the whole scrolling infrastructure or duplicating that whole logic, neither of which is reasonable to retrofit into a widget that wasn't built for it. Our goal is to have widgets be coherent and implement the same APIs so that they are easier to fit together. How exactly this will turn out for InteractiveViewer is yet to be determined. I recommend letting @Piinks work through the design and see what they come up with. In the meantime if you would be satisfied with a variant of InteractiveViewer that implements just part of the problem (e.g. non-physics-aware mouse scrolling) then you are welcome to fork the widget and upload a package to pub.

**Comment by davsl** [comment]
I did the impossible... I found a way to both support mouse scrolling and showing scrollbars with using InteractiveViewer class. I made this package: [flutterx_table](https://pub.dev/packages/flutterx_table)
This package was originally created as a more customizable alternative to DataTable but I also introduced a very useful component:
`
ScrollableViewScrollbar.both(
                      controllerX: _controllerX,
                      controllerY: _controllerY,
                      child: ScrollableView(
                              controllerX: _controllerX,
                              controllerY: _controllerY,
                              child: <whatever>));
`
It works perfectly with Apple Trackpad and allows to scroll smoothly in every direction
<img width="1080" alt="Schermata 2022-07-20 alle 20 11 43" src="https://user-images.githubusercontent.com/17468246/180052945-58914be6-064a-45e5-b81f-19707eb69ae6.png">

**Comment by Piinks** [comment]
I am removing my assignment because I am focused on a separate 2D scrolling widget (See https://github.com/orgs/flutter/projects/32), and @moffatman has been working on this specifically in the linked PRs above. :)

**Comment by krishnagandrath** [comment]
It should also have an option to disable mouse wheel events. In my case I need interactive viewer for mobile devices but don't want to update scale for mouse wheel events. Is there any way to disable it or do we need to write custom code ourselves?

**Comment by justinmc** [comment]
Now that https://github.com/flutter/flutter/pull/112171 and related PRs are merged, scrolling on a mouse or trackpad causes a pan, and pinching on a trackpad causes a scale.  There are several other suggestions in this issue (like the [previous comment](https://github.com/flutter/flutter/issues/64210#issuecomment-1373207786)), but I'm going to consider this issue complete.

For any other related features/bugs, please create a new issue and tag me.

For the option to allow scrolling to scale as before, see https://github.com/flutter/flutter/pull/114280.
