### ISSUE TITLE
Get docs-linux working on LUCI

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#64212]
The `docs-linux` test shard was disabled on Cirrus on post-submit in https://github.com/flutter/flutter/pull/63995. However, the `docs.sh` bash script has CIRRUS env variables hard-coded. Also, I'm not sure if the firebase auth is working. In any case, the master channel docs site hasn't updated since that PR landed https://master-api.flutter.dev/.

The `docs.sh` script should be refactored to support LUCI. Then the post-submit cirrus test should be disabled.

**Comment by godofredoc** [comment]
This is complete. Docs are being uploaded from LUCI.
