### ISSUE TITLE
[web] - Material Icons not render in debug mode, works in profile only

### ISSUE THREAD

**Issue by menezes85** [flutter/flutter#64211]
using current master: 
Flutter 1.21.0-10.0.pre.184 • channel master • https://github.com/flutter/flutter.git
Framework • revision 04f7c9d52e (2 hours ago) • 2020-08-19 16:59:52 -0700
Engine • revision 74d32ecdbd
Tools • Dart 2.10.0 (build 2.10.0-45.0.dev)

Flutter doctor:

E:\apps\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, 1.21.0-10.0.pre.184, on Microsoft Windows [versÃ£o 10.0.17134.829], locale pt-BR)
    • Flutter version 1.21.0-10.0.pre.184 at E:\apps\flutter
    • Framework revision 04f7c9d52e (2 hours ago), 2020-08-19 16:59:52 -0700
    • Engine revision 74d32ecdbd
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\William\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\pc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\William\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @menezes85 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by puertojose** [comment]
Having the same issue for a while already 😅
