### ISSUE TITLE
[webView_flutter][iOS] WebView is frozen in release mode with flutter 1.20.2 stable version

### ISSUE THREAD

**Issue by crazyleaf9999** [flutter/flutter#64228]
In my project, I found WebView in my App will be frozen on iOS with flutter stable version 1.20.2.
This issue is not happened in flutter 1.18.0-11.1.pre. I made a sample webview App which only shows a google page after launching.
The sample webview App will be frozen after launching.

**pubspec.yaml**
```
  webview_flutter: ^0.3.22
  flutter_inappwebview: ^4.0.0
```
The following two webviews are frozen after launching in release mode.
(flutter stable version 1.20.2 happens and doesn't happen with flutter 1.18.0-11.1.pre.)

```dart
WebView(initialUrl: 'https://www.google.com'),
```
or
```dart
InAppWebView(initialUrl: 'https://www.google.com'),
```

## Steps to Reproduce

1. Run the provided sample project https://github.com/crazyleaf9999/flutter_webview_test
(You have to fill your own team and bundle identifier in Xcode settings)
<img width="1003" alt="set_team_and_bundle_identifier" src="https://user-images.githubusercontent.com/7054602/90716293-30a62280-e2df-11ea-8551-be51a33c0adc.png">

2. Build the webview App in release mode.
(This issue only happens in release mode.)
3. Install the webview App on real iOS device.
4. Open the App and the webview will be frozen after launching.
5. If nothing happens, please kill the App.
6. Repeat step 4 and 5 and it happens with high probability.
<img src="https://user-images.githubusercontent.com/7054602/90716764-45cf8100-e2e0-11ea-8eab-46a31bb654f1.PNG" width=320/>

**Expected results:** 
The webview is scrollable in release mode App.

**Actual results:** 
The webview is frozen in release mode App.

<details>
  <summary>Logs</summary>

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

I got an error:
```
body is too long (maximum is 65536 characters).
```
Please read the output of `flutter run --verbose` in:
https://github.com/crazyleaf9999/flutter_webview_test/blob/master/flutter_run_log

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.
```
Analyzing flutter_1_2_0_with_webview...

   info • The value of the field '_counter' isn't used • lib/main.dart:54:7 • unused_field
   info • The declaration '_incrementCounter' isn't referenced • lib/main.dart:56:8 • unused_element
```

Finally, paste the output of running `flutter doctor -v` here. 
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale zh-Hant-TW)
    • Flutter version 1.20.2 at /Users/brianlin/Dev/flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brianlin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode_11_6.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Taiwan 的 iPhone (mobile)            • b4bcaf1e0923c7b38acf316dac9c6bef2dd3a1e7 • ios • iOS 13.3
    • iPhone SE (2nd generation) (mobile) • 0A3062A9-31F8-4EA5-975F-6FA6642F1D17     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)
```

</details>

**Comment by crazyleaf9999** [comment]
Thanks for your investigation.
You can tell me if you need me to do something.
Thanks a lot!

**Comment by cyanglaz** [comment]
@crazyleaf9999 Thanks for the offering. https://github.com/flutter/engine/pull/20708 should fix the issue. We are currently working on landing it.

**Comment by cyanglaz** [comment]
reopen as the fix has not been cherry-picked to stable

**Comment by pcsosinski** [comment]
we can close it now if it's fixed in master.   we CP for closed issues :)

**Comment by MahiMahionly** [comment]
get the Release APK from this command in terminal: ** flutter run --release **.
This Will Definitely Solve Your All Those Problems..
Also It have less MB output than Getting Release Apk from Build ->Flutter->Build Apk ...etc .
:)Mahi

**Comment by Shubhankt1** [comment]
Hi
I'm having same kind of problem but, its not constant and not happening on all iOS devices.
It happens randomly and then the web view stops working (in release/production mode).

the device which it occurred on is iPhone 11 Pro Max.
iOS version: `14.5`
Flutter `1.22.5`, channel `stable`
package: **webview_flutter** (version `^1.0.7`)

Unfortunately I don't have logs because its one of the client device.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Shubhankt1** [comment]
@TahaTesser I've filed a new issue for it. Here is the [LINK](https://github.com/flutter/flutter/issues/81535#issue-872237758) for issue #81535
