### ISSUE TITLE
Flutter select specific version

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#64238]
At this time there is no way to select a specific flutter version

`flutter version 1.17.5` is deprecated

`flutter downgrade 1.17.5` will downgrade to the previous installed flutter version. In my case it will downgrade to 1.17.4 (#63635)

I would like to see a command that selects a specific version for a specific channel

For example `flutter select stable 1.17.5`

Why?
We are using 1 jenkins slave for our pull requests & automated builds. 

Some projects are still using 1.17.5 and they should still be able to build with that soecific version. Right now we don't have a command to select a flutter version

**Comment by christopherfujino** [comment]
for CI, you can do `flutter checkout 1.17.5 && flutter precache` (the second command is optional, but will ensure the correct Dart SDK and binaries necessary to build ios and android are present).

**Comment by vanlooverenkoen** [comment]
Flutter checkout does not exist
```
~/Documents/work(:|✔) % flutter checkout 1.20.2
Could not find a command named "checkout".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by erickzanardo** [comment]
@vanelizarov there is the package that is very helpful for handling multiple versions of Flutter, check this out I think it will solve your issue http://pub.dev/packages/fvm

**Comment by vanlooverenkoen** [comment]
@erickzanardo thanks I will try that one for now

**Comment by erickzanardo** [comment]
Awesome! If the package solves your problem maybe consider closing this issue @vanlooverenkoen

**Comment by pedromassangocode** [comment]
Hi @vanlooverenkoen 
Did the package solved your problem?

**Comment by vanlooverenkoen** [comment]
Yes we are using it right now. But I do believe this is something that should be included in flutter itself.

**Comment by pedromassangocode** [comment]
Hi @vanlooverenkoen 

The `flutter version XXX` was deprecated for some reason and since the community have some amazing alternatives like http://pub.dev/packages/fvm, there is no need to have this in Flutter again.

Given your last message I feel safe to close this issue.
Thank you
