### ISSUE TITLE
how to link native framework of plugin ios with flutter  version  1.20.2

### ISSUE THREAD

**Issue by fusen-github** [flutter/flutter#64243]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
i want to link a framework to ios plugin, but link error  

Undefined symbols for architecture arm64:
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServers(GCDWebServerFunctions.o)
  "_inflateEnd", referenced from:
      -[GCDWebServerGZipDecoder open:] in GCDWebServers(GCDWebServerRequest.o)
      -[GCDWebServerGZipDecoder close:] in GCDWebServers(GCDWebServerRequest.o)
  "_deflate", referenced from:
      -[GCDWebServerGZipEncoder readData:] in GCDWebServers(GCDWebServerResponse.o)
  "_kUTTagClassFilenameExtension", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServers(GCDWebServerFunctions.o)
  "_xmlFreeDoc", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebServers(GCDWebDAVServer.o)
      -[GCDWebDAVServer(Methods) performLOCK:] in GCDWebServers(GCDWebDAVServer.o)
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServers(GCDWebServerFunctions.o)
  "_xmlReadMemory", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebServers(GCDWebDAVServer.o)
      -[GCDWebDAVServer(Methods) performLOCK:] in GCDWebServers(GCDWebDAVServer.o)
  "_xmlStrcmp", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebServers(GCDWebDAVServer.o)
      __XMLChildWithName in GCDWebServers(GCDWebDAVServer.o)
  "_inflate", referenced from:
      -[GCDWebServerGZipDecoder writeData:error:] in GCDWebServers(GCDWebServerRequest.o)
  "_deflateInit2_", referenced from:
      -[GCDWebServerGZipEncoder open:] in GCDWebServers(GCDWebServerResponse.o)
  "_deflateEnd", referenced from:
      -[GCDWebServerGZipEncoder open:] in GCDWebServers(GCDWebServerResponse.o)
      -[GCDWebServerGZipEncoder close] in GCDWebServers(GCDWebServerResponse.o)
  "_inflateInit2_", referenced from:
      -[GCDWebServerGZipDecoder open:] in GCDWebServers(GCDWebServerRequest.o)
  "_kUTTagClassMIMEType", referenced from:
      _GCDWebServerGetMimeTypeForExtension in GCDWebServers(GCDWebServerFunctions.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I confirm GCDWebServers.framework has  architecture arm64

my plugin podspec:

Pod::Spec.new do |s|
  s.name             = 'app_plugin'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'
  
  s.vendored_frameworks = 'ThirdLibs/libs/GCDWebServers.framework' 

  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => '' }
end

**Comment by fusen-github** [comment]
I've solved it, thank you.

**Comment by TahaTesser** [comment]
Hi @fusen-github 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by DeepashreeB** [comment]
> I've solved it, thank you. @TahaTesser

Hi @TahaTesser  how you solved can you share.

**Comment by DeepashreeB** [comment]
@fusen-github How You Solved this? Can please explain here
