### ISSUE TITLE
Listview.builder listitem placeholder 

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#64244]
# Use Case

Since listview.builder builds the list lazily, if the value of the listitem is dependent on network requests or a complex function, then till the value arrives, a placeholder or loader can be used.

# Perks

- This will really improve the performance of lists and reduce janks.
- It will improve the UI design and provide a richer user experience 
- It'll make the best use of building lists lazily

**Comment by sidrao2006** [comment]
Can anyone please look into it

**Comment by goderbauer** [comment]
You can just return a widget from the builder that shows a placeholder and then - whenever the load is done - replaces the placeholder with the actual content.
