### ISSUE TITLE
Need to run flutter sometimes twice to run with latest dart files

### ISSUE THREAD

**Issue by johannesvuorinen** [flutter/flutter#64263]
On Mac OS we have had the issue where we sometimes have to run flutter twice to run with our latest dart files. Running flutter sometimes uses our dart files that are not the latest saved ones but the ones on the previous flutter run. Is there some cache in place which does not always invalidate? Cleaning of course helps but it makes iterating especially init dart code very slow process where hot reload is not possible.

This issue is similar to this already closed issue:
https://github.com/flutter/flutter/issues/16604

**Comment by jonahwilliams** [comment]
sounds like a bug in our cache invalidation, can you reliably reproduce this through flutter run? If so it would really be helpful to have full verbose logs `flutter run -v`.

In addition we require `flutter doctor -v` for issue reports

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
