### ISSUE TITLE
The Scrollable snapOffsetCallback() could supply fling velocity, current scroll offset

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#6426]
If an app is using a Scrollable's snapOffsetCallback to scroll between pages, the velocity would inform how many pages the fling should span and the current scroll offset would anchor the scroll offset delta.

Currently its possible to find the current scrollOffset by creating the Scrollable with a global key. Then `scrollableKey.currentState.scrollOffset` is the current offset. The fling velocity is implied by the difference between the current offset and the snapOffsetCallback parameter.

Adding callback parameters that made the current scroll offset and the fling velocity explicit would be convenient.

**Comment by HansMuller** [comment]
@Hixie

**Comment by eseidelGoogle** [comment]
Unclear if this is related to https://github.com/flutter/flutter/issues/6427 https://github.com/flutter/flutter/issues/6431 or https://github.com/flutter/flutter/issues/6432 or fixed by @Hixie's big scrolling rewrite?

**Comment by abarth** [comment]
I think we're going to remove snapOffsetCallback for now.  We'll probably need to add the feature back with a different API in the future.
