### ISSUE TITLE
Slow bot_update step blocking tree re-opening

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64278]
The bot_update step usually takes a couple of minutes, but it's taking more than an hour here: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/6431

End of the logs:
```
[1:11:30] Still working on:
[1:11:30]   src/third_party/dart/third_party/pkg/html
[1:11:30]   src/third_party/dart/third_party/pkg/linter
```

**Comment by godofredoc** [comment]
Not sure, the bot update is a black box but it shouldn't take more than 5 mins. I can take a look by I recommend to kill the process and retry from github ui to unblock.

**Comment by digiter** [comment]
Retried the builder.

**Comment by godofredoc** [comment]
Did you use? https://g3doc.corp.google.com/company/teams/flutter/luci/playbook.md#trigger-prod-builder-retries

**Comment by zanderso** [comment]
The tree is showing a blue square there, now. Will this eventually re-run and turn green?

**Comment by zanderso** [comment]
Same issue on Windows Host Engine: https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/6348, sorry I didn't include that in the initial report.

**Comment by godofredoc** [comment]
Seems like there is a problem checking out  src/third_party/swiftshader, do you know where are we getting it from?

**Comment by digiter** [comment]
> Did you use? https://g3doc.corp.google.com/company/teams/flutter/luci/playbook.md#trigger-prod-builder-retries

I clicked the retry button, the retry build succeeded: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/6432

**Comment by digiter** [comment]
Looks like the issue is caused by network hiccup and that is recovered.
