### ISSUE TITLE
Retries of LUCI tasks from the flutter-dashboard do not paint the square as yellow

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64282]
For some reason the retries of LUCI tasks are not updating the dashboard as flaky.

Flutter dashboard:
![image](https://user-images.githubusercontent.com/54371434/90829534-c4ceb480-e2f4-11ea-8e39-1eb744333c4b.png)

LUCI milo:
![image](https://user-images.githubusercontent.com/54371434/90829587-e29c1980-e2f4-11ea-95c3-e27d1a3b09fe.png)

Commit:
https://github.com/flutter/flutter/commit/a2e5e074ab4318aa07758c875811f4170f0c60d4

Failed build:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20framework_tests/141

Passed build:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20framework_tests/142

**Comment by keyonghan** [comment]
`Attempts` is default set to 0 when first created in datastore. Though re-run is conducted, the `Attempts` will be updated to 1, so flakiness will not be reflected on dashboard.

The fix is to set `Attempts` to 1 in the beginning.
