### ISSUE TITLE
The PR checks failed by accident, and the contributors can not retry.

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#64291]
The PR checks failed by accident, and the contributors can not retry. https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/728?
![image](https://user-images.githubusercontent.com/61075224/90840384-710faa00-e38c-11ea-96ff-7b7635258d37.png)

**Comment by godofredoc** [comment]
This is working as intended, the correct way to retry the builds is from the github ui:


![image](https://user-images.githubusercontent.com/54371434/90843611-e0e34d80-e316-11ea-9fea-01f67a4ecbfa.png)

**Comment by xu-baolin** [comment]
Why there is nothing here?
![image](https://user-images.githubusercontent.com/61075224/90843925-4aa23c80-e395-11ea-88da-be06fc652af2.png)

**Comment by digiter** [comment]
Triage: @Hixie Would you mind taking a look at the permissions?

**Comment by Hixie** [comment]
Which permissions specifically? I'm not aware of anything that controls who can retry; I assume it's always that only contributors (as in, people in the flutter-hackers group) can retry. (See https://github.com/flutter/flutter/wiki/Contributor-access for the process for getting contributor access.)

**Comment by Hixie** [comment]
(in the meantime you can always force it by just pushing to the branch again)

**Comment by godofredoc** [comment]
Closing as obsolete. Please reopen if this is still an issue.
