### ISSUE TITLE
Failed assertion: line 1564: 'child == _child' is not true.

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#643]
If the _DropDownMenu<T> build() function concludes by returning a Focus et al widget, then an inexplicable (to me anyway) assertion is triggered.

```
    return new Focus(
      key: new GlobalObjectKey(route),
      child: new FadeTransition(
        performance: route.performance,
        opacity: menuOpacity,
        child: new BuilderTransition(
          performance: route.performance,
          variables: <AnimatedValue<double>>[menuTop, menuBottom],
          builder: (BuildContext context) {
            return new CustomPaint(
              painter: new _DropDownMenuPainter(
                color: Theme.of(context).canvasColor,
                elevation: route.elevation,
                menuTop: menuTop.value,
                menuBottom: menuBottom.value,
                renderBox: context.findRenderObject()
              ),
              child: new Column(children, justifyContent: FlexJustifyContent.collapse)
            );
          }
        )
      )
    );
```

The assertion failure starts like this:

```
android: I/flutter : Exception caught while building _DropDownMenu
android: I/flutter : 'packages/flutter/src/widgets/framework.dart': Failed assertion: line 1564: 'child == _child' is not true.
```

Removing the outermost Focus widget, i.e. returning the FadeTransition widget instead eliminates the assert.

**Comment by abarth** [comment]
That assert really shouldn't fire.  We probably need to make a reduced test case to figure out what's going on here.

**Comment by Hixie** [comment]
Wow, that's not an assert that should ever fire at all. Do you have a stack, or a branch I can pull to reproduce this?

**Comment by HansMuller** [comment]
The bug can still be reproduced by wrapping the value created by _DropdownMenu.build() in material/dropdown.dart with a Focus Widget:

```
class _DropDownMenu<T> extends StatusTransitionComponent {
  ...
  Widget build(BuildContext context) {
    ...
    return new Focus(
      key: new GlobalObjectKey(route),
      child: new FadeTransition(
      ...
```

**Comment by Hixie** [comment]
It's possible what's going on is that two widgets in the ancestor chain have the same global key. We don't catch that case and if you do do that this is the assert that ends up firing.

See also https://github.com/flutter/flutter/issues/2911

**Comment by Hixie** [comment]
The widgets involved in the repro case here don't exist any more, and we haven't heard any recent complaints, and the cause I suggested might be the cause above is now something we'll catch, so I'm going to close this optimistically.
