### ISSUE TITLE
Video Player refuses to play videos after playing a series of videos

### ISSUE THREAD

**Issue by pnwanno** [flutter/flutter#64302]
The video_player refuses to play videos after playing a set of videos.
I need to be able to play videos on ListView scrolls which means a number of videos should be ready to play as soon as they are scrolled onto.
I cannot dispose the player in the middle of the page - except I am done with it.

I am running in debug mode on Tecno Camon cd7 android 10 mode. This issue have repeated itself on several other devices.
How can I launch an App when the behavior of the video player is inconsistent.

I have raised this issue before but it seemed that I had been doing something wrong, I have gone back to check over and over again and I think, this is an issue with the video player. Please I need to get over with this, My App is in it's final stages and I can't switch to a different tool right now

**Comment by darshankawar** [comment]
Hi @pnwanno,
We'll need a minimal complete reproducible code sample that we can copy paste and run in IDE. The code you provided seems to have custom code which isn't needed for us to replicate.
Thanks.

**Comment by pnwanno** [comment]
@darshankawar  Thank you for your response and the flutter team.
I figured out the cause for the video player refusing to play, as I raised in my issue above - in a bid to send a reproducible sample code to you.
I use streams for my state management and videos in the ListView.builder widget a lazy-loaded from a server. The videoplayer get widget get destroyed and rebuilt many times on the list and I didn't think to dispose it alongside. I only disposed them on the route's dispose method. I saw this when I reproduced the player list on a fresh dart file.
Thank you - The VideoPlayer is fine so far. 
Kindly close this issue. Thanks!

**Comment by darshankawar** [comment]
@pnwanno glad to know you found the root-cause.
Closing this as non-issue.

**Comment by Kishan-Somaiya** [comment]
I'm also facing the same issue, can you explain your solution ? @pnwanno that would be great.

**Comment by pnwanno** [comment]
> I'm also facing the same issue, can you explain your solution ? @pnwanno that would be great.

I think it is an exoplayer issue - not the video player by flutter, as the video player is just a mask on top the exoplayer.
The reason for that (the issue you described) is that you might not disposing the controller unknowingly.
Depending on your code I can help you figure the solution. You might think you are disposing it but you might be missing something.

**Comment by Kishan-Somaiya** [comment]
@pnwanno have a look at this https://github.com/flutter/flutter/issues/64693

**Comment by pnwanno** [comment]
An intuitive way to deal with it (though solutions may vary depending on your code and state management), is
List<VideoPlayerController>_vplayer=List<VideoPlayerController>();
resetVideoPlayer(){
_vplayer.forEach((element) {
      element.dispose();
    });
    _vplayer=List<VideoPlayerController>();
   //call your state management method to reset state to ensure it is not attached to any widget then create a new controller afterwards
}
//always call the resetVideoPlayer function whenever you are changing the player source
//create a new controller
_vplayer.add(
 VideoPlayerController.File(File("/path/to/file"));
// VideoPlayerController.Network("url");
);
VideoPlayerController _newPLayer= _vplayer.last;
//modify the code above to solve your needs
//Kindly send feedback here if it works or not - to help someone else who may be in the same state

**Comment by Kishan-Somaiya** [comment]
@pnwanno thanks for your reply, can i send you my code and will you help me with it ? i won't be able to send the code here.

**Comment by pnwanno** [comment]
> @pnwanno thanks for your reply, can i send you my code and will you help me with it ? i won't be able to send the code here.

Alright, but, I can't put my email here either. Choose a way to send it to me, I'll walk with you on the method chosen

**Comment by Kishan-Somaiya** [comment]
@pnwanno i'll share you a gist link in few minutes

**Comment by Kishan-Somaiya** [comment]
@pnwanno here's the gist link :  https://gist.github.com/Kishan-Somaiya/eab3bb3c5208e7a1ef5437e60b252944

**Comment by darshankawar** [comment]
@pnwanno, @Kishan-Somaiya please take up your discussion privately. Thanks.

**Comment by Dhua-v** [comment]
It would be very grateful of you @Kishan-Somaiya to put here the solution

1. Non-working code
2. Fixed code.
It will help the community a lot.
