### ISSUE TITLE
unreadable code output when debugging

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#64301]
![图片](https://user-images.githubusercontent.com/48232744/90853747-9365ef80-e3ad-11ea-82e2-3ce1c8acb648.png)

my OS:
![图片](https://user-images.githubusercontent.com/48232744/90853811-c7d9ab80-e3ad-11ea-97dd-82b490d86072.png)

**Comment by heroqin** [comment]
Hi @pedromassangocode，
![图片](https://user-images.githubusercontent.com/48232744/90997919-6ad03680-e5f5-11ea-9346-93d9ed3d38b6.png)
and fragment of flutter run --verbose:
![图片](https://user-images.githubusercontent.com/48232744/90998059-c26ea200-e5f5-11ea-999e-693f61faf095.png)
[flutter_blue-0.7.2.zip](https://github.com/flutter/flutter/files/5115505/flutter_blue-0.7.2.zip)
above is the reproducible code sample, to reproduce it, do a flutter clean first, then F5

**Comment by pedromassangocode** [comment]
Hi @heroqin 
I was not able to reproduce this issue using the [China Flutter server](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) and I think it has something to do with the font used in your computer.

**Comment by pedromassangocode** [comment]
May be related to https://github.com/flutter/flutter/issues/62958

**Comment by heroqin** [comment]
Hi @pedromassangocode 
I wonder this issue is because I'm using Windows7 Chinese version.
by the way, #62958 doesn't appear anymore  when I  upgrade flutter to version 1.20 stable.

**Comment by heroqin** [comment]
Hi @pedromassangocode 
I use the default font comming from windows7 Chinese version and never do anything to the font.

**Comment by darshankawar** [comment]
@heroqin 
Are you still experiencing this issue using latest stable version of framework ?
