### ISSUE TITLE
One tap for toolbarOptions and draggable cursor in TextField widget on iOS

### ISSUE THREAD

**Issue by tsusubk** [flutter/flutter#64319]
Use case:
TextField on iOS behaves in a confusing way to native users in which they can think it was a bug.

Current behavior:
- double tap on cursor to show toolbarOptions
- long press before cursor can be draggable

Expected behavior:
- one tap on cursor to show toolbarOptions
- the cursor is already draggable, no long press needed before

Step to reproduce:
Run an app with a TextField widget on an iOS simulator/device, e.g.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @tsusubk 
I can reproduce the issue 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/62252 but it is missing custom drag point so I am gonna comment there 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
