### ISSUE TITLE
flutter update-packages   stuck

### ISSUE THREAD

**Issue by AttSee** [flutter/flutter#64310]
I try more than once, no benefit
I waited more than twenty minutes

flutter update-packages
Waiting for another flutter command to release the startup lock...Running "flutter pub get" in tracing_tests...                       0.6s
Running "flutter pub get" in bots...                                1.3s
Running "flutter pub get" in customer_testing...                    0.5s
Running "flutter pub get" in snippets...                            0.9s
Running "flutter pub get" in platform_interaction...                1.1s
Running "flutter pub get" in flutter_gallery...                     1.5s
Running "flutter pub get" in non_nullable...                        0.6s
Running "flutter pub get" in gradle_deprecated_settings...          0.5s
Running "flutter pub get" in release_smoke_test...                  0.9s
Running "flutter pub get" in channels...                            1.0s
Running "flutter pub get" in android_semantics_testing...           1.0s
Running "flutter pub get" in ios_platform_view_tests...             1.1s
Running "flutter pub get" in flutterapp...                          0.6s
Running "flutter pub get" in flavors...                             1.1s
Running "flutter pub get" in flutter_driver_screenshot_test...         1.0s
Running "flutter pub get" in flutterapp...                          0.6s
Running "flutter pub get" in ui...                                  1.1s
Running "flutter pub get" in external_ui...                         1.1s
Running "flutter pub get" in web_compile_tests...                   0.5s
Running "flutter pub get" in ios_app_with_extensions...             0.6s
Running "flutter pub get" in hybrid_android_views...               88.3s
Running "flutter pub get" in android_views...                       0.9s
Running "flutter pub get" in web...                                 0.4s
Running "flutter pub get" in android_embedding_v2_smoke_test...         0.5s
Running "flutter pub get" in abstract_method_smoke_test...          0.5s
Running "flutter pub get" in splash_screen_kitchen_sink...          1.1s
Running "flutter pub get" in splash_screen_trans_rotate...          1.1s
Running "flutter pub get" in splash_screen_load_rotate...           0.6s
Running "flutter pub get" in image_loading...                       0.9s
Running "flutter pub get" in named_isolates...                      0.5s
Running "flutter pub get" in devicelab...                           1.1s
Running "flutter pub get" in manual_tests...                        0.7s
Running "flutter pub get" in platform_views_layout...               1.0s
Running "flutter pub get" in platform_views_layout_hybrid_composition...        1.1s 
Running "flutter pub get" in macrobenchmarks...                   (     It got stuck here    )
(This is taking an unexpectedly long time.)       ⣟                 

---------------------------------------------------------------------------------------------
attia@HP-Pavilion:~$ flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/attia/Porgram/flutter
    • Framework revision be9bc8cb39 (3 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/attia/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/attia/Porgram/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/attia/Porgram/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.135

• No issues found!

**Comment by Basher7** [comment]
@AttSee why you closed this issue?
I also facing same problem.
are you get any solution?

**Comment by AttSee** [comment]
@Basher7 In case you deleted the flutter files, you need more time
Wait a little longer and the download will finish

**Comment by liwei511** [comment]
one hour later ...
I also facing saave problem

**Comment by liwei511** [comment]
$ flutter update-packages
Running "flutter pub get" in automated_tests...                     4.7s
Running "flutter pub get" in complex_layout...                      6.5s
Running "flutter pub get" in macrobenchmarks...
Git error. Command: `git clone --mirror https://github.com/flutter/gallery.git C:\src\flutter\.pub-cache\git\cache\gallery-e81411447eb674bf0aa7b6d3b66e18a667cfbf46`
stdout: 
stderr: Cloning into bare repository 'C:\src\flutter\.pub-cache\git\cache\gallery-e81411447eb674bf0aa7b6d3b66e18a667cfbf46'...
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
exit code: 128
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Running "flutter pub get" in macrobenchmarks...                 (This is taking an unexpectedly long time.)       \
