### ISSUE TITLE
MissingPluginException Android

### ISSUE THREAD

**Issue by vogttho** [flutter/flutter#64320]
Unable to run the App on Android. Works fine on iOS

I use 
   <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

in my manifest

## Steps to Reproduce

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependency_overrides:
  flutter_svg: 0.18.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.8

  google_maps_flutter: ^0.5.30
  http: ^0.12.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  fluster: ^1.1.2
  flutter_cache_manager: ^1.4.1
  flutter_linkify: ^3.1.3

  cached_network_image: ^2.2.0+1
  twitter_api: ^0.1.2
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics:  ^0.1.4+1
  firebase_storage:  ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.2

Gradle Version = 5.6.2

ERROR:

MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_pr

FLUTTER DOCTOR:
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale de-CH)
    • Flutter version 1.21.0-9.1.pre at /Users/me/work/dev/tools/flutter
    • Framework revision be9bc8cb39 (vor 3 Tagen), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM G955F (mobile) • ce031713435368f40c • android-arm64 • Android 9 (API 28)

**Comment by TahaTesser** [comment]
Hi @vogttho 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/46679
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
