### ISSUE TITLE
webview_flutter plugin is lagging and keyboard problems

### ISSUE THREAD

**Issue by varunkumarmedam** [flutter/flutter#64336]
When I compared webview_flutter plugin with https://pub.dev/packages/flutter_webview_plugin this plugin, I found an enormous and drastic performance issue which reflected a lot on our production.

But https://pub.dev/packages/flutter_webview_plugin this plugin don't manage cookies why is really very sad.

**Comment by darshankawar** [comment]
Hi @varunkumarmedam,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample w.r.t `webview_flutter` plugin, that shows the issue you are facing, along with the devices on which you tried.

**Comment by varunkumarmedam** [comment]
Hello @darshankawar, thanks for immediate response

import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter WebView Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: WebviewScaffold(
          url: "http://bloodline.ga/app/",
          withZoom: true,
          appCacheEnabled: true,
          withJavascript: true,
        ));
  }
}
The above code works very smoothly.

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter WebView Demo', home: MySite());
  }
}

class MySite extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox(
        height: MediaQuery.of(context).size.height,
        child: WebView(
          initialUrl: 'https://bloodline.ga/app/',
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ),
    );
  }
}
This is lagging which can be observed while scrolling

**Comment by varunkumarmedam** [comment]
And [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) can manage cookies also (cross-domain too), and I tried to integrate [webview_cookie_manager](https://pub.dev/packages/webview_cookie_manager) with this webview_flutter plugin but this can able to get cookies in cross-domain. But later found [webview_cookie_manager](https://pub.dev/packages/webview_cookie_manager) cant get cookies from cross-domain.

**Comment by varunkumarmedam** [comment]
We are trying to get [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) performance with [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) cookie management

**Comment by darshankawar** [comment]
@varunkumarmedam,
There's another open issue describing your case, [61280](https://github.com/flutter/flutter/issues/61280).
Does that sound similar to your issue ?

**Comment by varunkumarmedam** [comment]
@darshankawar yaa that issue is somewhat similar but we are facing problems with cross-origin cookies too. I cant able to find the correct solution in the closes issues too.

**Comment by varunkumarmedam** [comment]
[ flutter_inappwebview ](https://pub.dev/packages/flutter_inappwebview) this plugin works as expected for cookies management but we can't use because of low performance like this plugin

**Comment by darshankawar** [comment]
Hi @varunkumarmedam,
`flutter_inappwebview` is a 3rd party plugin, so if you have any issues related to it, I'd suggest to raise those here : https://github.com/pichillilorenzo/flutter_inappwebview/issues.

I don't really know exactly about `cross-origin cookies` issues you are talking about, but if you have any specifics with it, I'd suggest you to open a new issue w.r.t `webview_flutter` plugin and for current issues related to lagging and keyboard, please follow-up in 61280. Makes sense ?
Thanks.
