### ISSUE TITLE
[web]: Text Editor is unusable on Flutter web because caret positioning is incorrect

### ISSUE THREAD

**Issue by mypocketsoft** [flutter/flutter#64330]
Text Editor is unusable on Flutter web because the caret doesn't go where the user clicks, and the editing point for text is somewhere else again. 

This is for a rewrite of my TaskAngel To-do List App (www.taskangel.com), which I am updating/converting from Windows and iOS to Flutter Web.

This issue is a show-stopper for my project because what good is a to-do list app where you can't change the text? Is anyone working on this? I am happy to help if I can.

On Mac, with Safai and Chrome the text can still be edited but the caret position has to be fine-tuned with the arrow keys.
On Android tablet with Chrome [version 84.0.4147.111], the caret goes inside the same the word that has been tapped, but to a different letter. But then if I start typing, the letter is inserted somewhere different.
On iPhone [iPhone 11 Pro max version 13.6] with Chrome [version 84.0.4147.122], if the text field has been scrolled horizontally, the cursor position when tapped is completely wrong. This also happens with Safari, and with a home page web link, on iPhone and iPad

In my text editing widget I have:
````dart
void initState() {
...
if (_task?.title == null) {
      _titleTextController = TextEditingController();
    } else {
      _titleTextController =
          TextEditingController.fromValue(TextEditingValue(text: _task.title));
    }
}
````
and then the page build function has:
````dart
new TextFormField(
                      style: textTheme.subtitle1,
                      controller: _titleTextController,
                       decoration: new InputDecoration(
                        hintText: 'What are you going to do?',
                        labelText: 'Task',
                        border: InputBorder.none,
                      ),
                      showCursor: true,
                      maxLines: 1,
                      keyboardType: TextInputType.text,
                      autofocus: true,
                      
                      ),

````

I am building my app with this parameter set, as advised in this issue: https://github.com/flutter/flutter/issues/33523:
````
flutter build web --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true

````

On Mac with Safari, text editing is just about managable when you click on the text then use the arrow keys to get to where you want to change text.

On iPad, the caret goes to completely the wrong place if the text has been scrolled.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.2, on Mac OS X 10.15.5 19F72f, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.0)
[✓] Connected device (3 available)

Thanks for any help or advice you can give me.
Thanks,
Andrew
http://www.taskangel.com

**Comment by markusaksli-nc** [comment]
Hi @mypocketsoft 
Can you please provide your `flutter doctor -v`, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by mypocketsoft** [comment]
Here's the flutter doctor -v. I'm working on the code sample.
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.5 19F72f, locale en)
    • Flutter version 1.21.0-9.1.pre at /Users/andrewboswell/Development/flutter
    • Framework revision be9bc8cb39 (7 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andrewboswell/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile)  • emulator-5554                        • android-x86    • Android 8.1.0 (API 27) (emulator)
    • iPhone SE (2nd generation) (mobile) • 2BEA330B-659A-476E-951D-9F208EC0FAFD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)
    • Web Server (web)                    • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 84.0.4147.135
    ! Error: Andrew's iPad Mini is not connected. Xcode will continue when Andrew's iPad Mini is connected. (code -13)
    ! Error: Lizzie's iPad is not connected. Xcode will continue when Lizzie's iPad is connected. (code -13)
    ! Error: Andrew’s iPhone is not connected. Xcode will continue when Andrew’s iPhone is connected. (code -13)

• No issues found!

**Comment by markusaksli-nc** [comment]
Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and clarify the expected vs actual behavior (with a video for example)?

**Comment by mypocketsoft** [comment]
Here is the minimum reproducible code sample. The fault is most evident when running the web app on a mobile device, eg iPhone Chrome or Android Tablet Chrome. The fault is less evident when running on my MacBook with chrome.

Expected behaviour:
Scroll up towards the end of the text. Then when tapping a word in the text editor, the caret should move to the character in the text that was tapped, so that the text there can be edited. 

Actual behaviour:
When tapping a word in the text editor, the text scrolls towards the start of the text and the caret moves to a random point on the top line. This is the wrong position for the text to be edited.


````dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Text Editor',
      theme: ThemeData(      
        primarySwatch: Colors.blue,     
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Text Editor'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  String _text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac vulputate nibh. Vivamus at lacus vel metus viverra semper. Ut maximus orci sed odio congue, id gravida arcu facilisis. Maecenas egestas, magna sed aliquam hendrerit, est leo volutpat sapien, varius convallis elit ante quis eros. Fusce non quam at dui aliquet fringilla vel a leo. Donec placerat mauris nec congue lobortis. Nullam sit amet orci ipsum. Nullam quis dolor vitae urna lobortis dignissim eget ut libero. In in pulvinar lorem. Phasellus ac tortor id risus feugiat feugiat vitae vel risus. Morbi porta arcu eget tellus hendrerit congue. Maecenas suscipit et risus ac commodo. Nullam mattis vel leo sed fermentum. Mauris volutpat sit amet neque nec ornare. Suspendisse ex sapien, pretium sit amet ante nec, dictum sagittis augue.\n\n""";
  var _textEditingController = TextEditingController();
  
  @override
  void initState() {
    _text = _text + _text + _text + _text + _text;
    _textEditingController.text = _text;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: 50.0 ),
        child: TextField(
          decoration: new InputDecoration.collapsed(
          hintText: 'Your text'
        ),
          controller: _textEditingController,
          maxLines: null,
        )
      ));
      }
}

````

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-2.0.pre.78`.
<img src="https://user-images.githubusercontent.com/68219924/91279742-90447800-e78e-11ea-9a5a-7a36dfa0e140.gif" height="500" /><img src="https://user-images.githubusercontent.com/68219924/91280099-fe893a80-e78e-11ea-856e-c95c70f52699.gif" height="500" />
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final controller = TextEditingController(
      text:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n"
             * 10);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Container(
          child: Center(
            child: SingleChildScrollView(
              child: TextField(
                controller: controller,
                maxLines: null,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.78, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.78 at C:\Development\flutter_master
    • Framework revision d0596582fe (2 hours ago), 2020-08-25 23:26:06 -0700
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

Was able to repro this on iOS and Android browsers but couldn't on desktop.

**Comment by mdebbar** [comment]
The root cause of this issue is https://github.com/flutter/flutter/issues/41630. Please react with a thumbs up to that issue to show that you are affected by it.
