### ISSUE TITLE
web_benchmarks_html build_material_checkbox.html.drawFrameDuration.average & build_material_checkbox.html.drawFrameDuration.average regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#64332]
May be https://github.com/flutter/flutter/pull/61398? /cc @LongCatIsLooong, who made the commit, and @yjbanov.

![image](https://user-images.githubusercontent.com/1435716/90910344-02cae780-e38c-11ea-84ce-bae431f9ae7d.png)

Probably not P0-worthy, but worth investigating quickly. Marking P1.

**Comment by LongCatIsLooong** [comment]
Looks like both benchmarks are back to green after the revert, and didn't seem to regress after the reland. Closing.
