### ISSUE TITLE
Dart observatory stopped working on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#64333]
**Steps to repro**

1. `flutter run`

2. Open the URL, you will see this in the console:

```
main.dart.js:3881 WebSocket connection to 'ws://127.0.0.1:40395/4D4hNFR8LdA=/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Sn @ main.dart.js:3881
```

cc @zanderso  @liyuqian

**Comment by bkonyi** [comment]
The fix should have rolled into the framework over the weekend.

**Comment by zanderso** [comment]
I am still seeing the behavior from https://github.com/flutter/flutter/issues/64333#issuecomment-678379960 at top of tree flutter/flutter.

**Comment by bkonyi** [comment]
@zanderso looks like the engine roll was delayed but just landed 10 minutes ago. Can you try again?
