### ISSUE TITLE
Extracting Frames from a video

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#64340]
## Use case
A plugin can be developed to extract every frame from a video either from a device memory or a live camera 

## Proposal
Frames then can be used in Tensorflow Lite models

**Comment by darshankawar** [comment]
Hi @SAMYAK99,
Have you looked at [this](https://pub.dev/packages/flutter_ffmpeg) and [this](https://pub.dev/packages/video_manipulation) plugin to see if they are helpful in your use-case ?
Thanks.

**Comment by SAMYAK99** [comment]
I have tried both these plugins but I am not able to  extract every frame from a video either from a device memory or a live camera and save it .

**Comment by stuartmorgan** [comment]
This is not a common enough use case that we would build a first-party plugin for it. It's certainly an interesting opportunity for a third-party plugin.
