### ISSUE TITLE
the command line menu to select a device for `flutter run` interrupts user flow

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#64356]
The flutter command line tool recently changed to showing a command line menu for `flutter run` when there is more than one device available and no device was specified on the command line:

<img width="549" alt="Screen Shot 2020-08-21 at 12 34 23 PM" src="https://user-images.githubusercontent.com/1269969/90927983-e12d2880-e3aa-11ea-878f-f1513547e751.png">

I believe the intent here was to be helpful, but on the whole I think this interrupts user flow. With desktop and web devices, there's now always more than one device available. I think we should switch back to failing when there's more than one device, and listing the available devices, and that the user should re-run with `flutter run -d ...`.

**Comment by jmagman** [comment]
I filed https://github.com/flutter/flutter/issues/63541 to tell the user about `-d` so they can avoid the prompt on the next run.

**Comment by eliasyishak** [comment]
@devoncarew closing this as stale but if this is something you still think we should do, feel free to reopen.  Seems like the current workflow for selecting a device after running `flutter run` is pretty set
