### ISSUE TITLE
Error: The getter 'toolbarIsVisible' was called on null. 

### ISSUE THREAD

**Issue by sudha-anecure** [flutter/flutter#64368]
Hi - all details are in #34571 - I am opening this new issue to reopen that one.

**Comment by pedromassangocode** [comment]
Hi @sudha-anecure 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by sudha-anecure** [comment]
Looks like #64471 is tracking this - and the developer wants to see if it
is reported in newer versions. I had put all my info in the original case
#34571

Please look at the comments across those two cases.
With best regards,
Sudha

*Sudha Varadarajan*
Founder, CEO, CTO
https://www.linkedin.com/in/sudhakv/
*Swell* | San Francisco
Join us at swell.life
<https://instagram.com/swell_stories>
<https://twitter.com/intent/follow?source=followbutton&variant=1.0&screen_name=swell_stories>
  <https://facebook.com/swellstory>
<https://linkedin.com/company/swellstories>
<https://reddit.com/u/swell_stories>  <https://medium.com/@swellstories>

**Comment by pedromassangocode** [comment]
Hi @sudha-anecure 
Do you have any idea on what device this issue happened?

**Comment by pedromassangocode** [comment]
Closing this in favour of https://github.com/flutter/flutter/issues/64471 since https://github.com/flutter/flutter/issues/64471 provides more information related to the issue. Please follow up on that issue.
