### ISSUE TITLE
flutter project startup stuck at Installing and launching... with android studio

### ISSUE THREAD

**Issue by fusen-github** [flutter/flutter#64378]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by markusaksli-nc** [comment]
Added wait label for what @sidrao2006 asked.

CC myself

**Comment by fusen-github** [comment]
I run "flutter run -v" command in terminal 3 times and successed 2 times, failed 1 time

fail is crashed when lanuching.
this is failed log:
[failed_log.txt](https://github.com/flutter/flutter/files/5117793/failed_log.txt)


this is success log:
[success_log.txt](https://github.com/flutter/flutter/files/5117796/success_log.txt)

Thrank You  @sidrao2006  @markusaksli-nc

**Comment by markusaksli-nc** [comment]
When it failed, did it get stuck on a blank white screen on your iOS device?

**Comment by fusen-github** [comment]
no, it crashed.   and the terminal get stuck  @markusaksli-nc 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/11560800/91047431-a21e0200-e64c-11ea-8ccf-5872ef2a8df1.png">

**Comment by markusaksli-nc** [comment]
In that case, please refer to https://github.com/flutter/flutter/issues/46705 for possible solutions and if none of them work, follow the advice in the issue and comment there with your case. I'm closing this one as a duplicate for now.
