### ISSUE TITLE
FLutter Crashed When creatin a new project

### ISSUE THREAD

**Issue by mikdhadc** [flutter/flutter#64383]
[flutter_01.log](https://github.com/flutter/flutter/files/5112206/flutter_01.log)
[flutter_01.log](https://github.com/flutter/flutter/files/5112207/flutter_01.log)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by darshankawar** [comment]
Hi @mikdhadc,
Per [this](https://github.com/flutter/flutter/issues/60358#issuecomment-650285966) comment, the issue has been fixed in Master. Please switch to latest master and see if it works for you.
Thanks.

**Comment by mikdhadc** [comment]
Thanks for your answers.However the issue is solved by downloading and setting up the sdk again.
