### ISSUE TITLE
Switch / SwitchListTitle widget not work in Samsung S20

### ISSUE THREAD

**Issue by facestamp** [flutter/flutter#64387]
Hi
I reach a strange behavior on the Switch widget or SwitchListTitle widget.

I tested the same app in 3 mobiles. And only S20 can't render the switch widget or SwitchListTile widget. The rest of the App is good in all mobiles. Please see the screenshots for details.

I try to repeat the problem using the below code posted in flutter. Same behavior.
https://api.flutter.dev/flutter/material/SwitchListTile-class.html
![20200822_093418](https://user-images.githubusercontent.com/70059363/90954949-c4c4e500-e4ab-11ea-9b96-e50a8510d7be.jpg)
![20200822_093146](https://user-images.githubusercontent.com/70059363/90954951-cc848980-e4ab-11ea-8326-b21a3bcffe72.jpg)
![20200822_093016](https://user-images.githubusercontent.com/70059363/90954953-d60df180-e4ab-11ea-9253-c1ba90cbb639.jpg)

**Comment by markusaksli-nc** [comment]
Hi @facestamp 
Can you reproduce this behavior with a `flutter create bug` default project with the following code
<details>
 <summary>Minimal code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  bool _lights = false;

  @override
  Widget build(BuildContext context) {
    return SwitchListTile(
      title: const Text('Lights'),
      value: _lights,
      onChanged: (bool value) {
        setState(() {
          _lights = value;
        });
      },
      secondary: const Icon(Icons.lightbulb_outline),
    );
  }
}
```
</details>

Are you using any third-party plugins? Could you provide your `flutter doctor -v` with the S20 connected? Please refrain from using images for any logs.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
