### ISSUE TITLE
W/FlutterActivity(26771): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@27cf01e) but could not find and invoke the GeneratedPluginRegistrant.

### ISSUE THREAD

**Issue by SuleCodes** [flutter/flutter#64382]
I have been chasing a solution to this bug but no actual fix. Cases are being closed without a resolve and its been preventing me from meeting a deadline. I would really appreciate any help on this. 
## Steps to Reproduce

1. Run upgrade to latest flutter version
2. Notice android/app/src/main/java/ does not have a MainActivity.js
3. Attempt flutter channel stable as recommended 
3. With the latest upgrade a lot of developers have run into the issue which also prevents use of firestore and services like google authentication. 

**Expected results:** 
Expecting to run android application and use:

var result = await _authenticator.login(); 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

 info • Redundant use of the annotation @required on the required positional parameter 'context' • lib/components/alert_dialog.dart:4:32 •
          invalid_required_positional_param
   info • Redundant use of the annotation @required on the required positional parameter 'message' • lib/components/alert_dialog.dart:5:7 •
          invalid_required_positional_param
   info • Redundant use of the annotation @required on the required positional parameter 'title' • lib/components/alert_dialog.dart:5:33 •
          invalid_required_positional_param
   info • Unused import: 'package:bubble_app/components/alert_dialog.dart' • lib/screens/searchBook_screen.dart:2:8 • unused_import
   info • Unused import: 'package:bubble_app/classes/objects.dart' • lib/screens/signIn_screen.dart:3:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/screens/signIn_screen.dart:12:8 • unused_import
   info • The value of the field '_auth' isn't used • lib/screens/signIn_screen.dart:22:9 • unused_field
   info • Unused import: 'package:bubble_app/classes/enums.dart' • lib/screens/signUp_screen.dart:2:8 • unused_import
   info • Unused import: 'package:bubble_app/screens/searchBook_screen.dart' • lib/screens/signUp_screen.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_signin_button/flutter_signin_button.dart' • lib/screens/signUp_screen.dart:8:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/screens/signUp_screen.dart:10:8 • unused_import
   info • The value of the field '_authenticator' isn't used • lib/screens/signUp_screen.dart:28:17 • unused_field
   info • Redundant use of the annotation @required on the required positional parameter 'buildContext' • lib/services/authentication.dart:13:34 •
          invalid_required_positional_param
   info • Don't type annotate initializing formals • lib/services/authentication.dart:13:44 • type_init_formals
   info • Redundant use of the annotation @required on the required positional parameter 'buildContext' • lib/services/authentication.dart:14:24 •
          invalid_required_positional_param
   info • Don't type annotate initializing formals • lib/services/authentication.dart:14:34 • type_init_formals

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

DEBUG OUTPUT

W/FlutterActivity(27545): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@706dbb8) but could not find and invoke the GeneratedPluginRegistrant.
D/EGL_emulation(27545): eglMakeCurrent: 0xebb78a80: ver 3 0 (tinfo 0xdfbd56b0)
D/eglCodecCommon(27545): setVertexArrayObject: set vao to 0 (0) 1 0
I/OpenGLRenderer(27545): Davey! duration=2880ms; Flags=1, IntendedVsync=29946678770321, Vsync=29946678770321, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=29946685604143, AnimationStart=29946685647143, PerformTraversalsStart=29946685741143, DrawStart=29949463124143, SyncQueued=29949474403143, SyncStart=29949476330143, IssueDrawCommandsStart=29949476839143, SwapBuffers=29949538614143, FrameCompleted=29949561494143, DequeueBufferDuration=6696000, QueueBufferDuration=2405000,
I/Choreographer(27545): Skipped 173 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(27545): eglMakeCurrent: 0xebb7a220: ver 3 0 (tinfo 0xdfbd5870)
D/eglCodecCommon(27545): setVertexArrayObject: set vao to 0 (0) 1 0
**I/flutter (27545): MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)**

</details>

**Comment by TahaTesser** [comment]
Hi @SuleCodes 
You can do it like this `MainActivity.kt`

```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        GeneratedPluginRegistrant.registerWith(flutterEngine)

    }
}

```

and you can leave it empty just like this, Firetore works with no issies
```
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

Hope this solves your issue

**Comment by SuleCodes** [comment]
The issue was resolved by me moving my branch to stable but also completing the facebook authentication alongside google when using the SignInButtons package.
