### ISSUE TITLE
[a11y][web][infra] Adding Chrome OS bots to LUCI

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#64394]
After long investigations we agreed on an approach to test accessibility for Flutter for Web. Currently the approach only works in Google. We are planning to extend the testing to Flutter Engine and Flutter in the next quarters. Since a11y on web can break both on engine changes and on Framework changes it would be better if we can run these tests on both repos.

I want to discuss the possibility of adding ChromeOS bots to LUCI engine infra in the future quarters.

**Comment by godofredoc** [comment]
Chrome OS will be tricky as the OS hides most of the functionality and it requires users to be signed in. Can you please share the current test workflow? e.g. chrome os machines with a user signed in, x app installed, test loading a url and driving it with chrome driver.

**Comment by nturgut** [comment]
We had discussion with @godofredoc on this topic. Looks like we might be able to use Chrome OS GCE's.

**Comment by derek-j-pitman** [comment]
Alternatively, the approach I've been going with has been using the linux-chromeos image:

https://chromium.googlesource.com/chromium/src/+/master/docs/chromeos_build_instructions.md

Runs the browser, as it would on Chrome OS, but with all the OS hooks stubbed out. No need to sign in with an account. It just works out of the box with ChromeDriver too, from my experience. You can also pass command-line flags to enable a11y features like high-contrast, screen magnification and ChromeVox (the screen reader).

All the same, Chrome would need builders in LUCI for this branch, just sharing what I know.

**Comment by godofredoc** [comment]
Obsolete
