### ISSUE TITLE
Update Android SDK from 28 to latest stable version in existing flutter packages

### ISSUE THREAD

**Issue by boskokg** [flutter/flutter#64396]
Update Android SDK from 28 to latest stable version in existing flutter packages.

example: https://github.com/flutter/plugins/blob/master/packages/connectivity/connectivity/android/build.gradle

There is still written "compileSdkVersion 28"

Expected: packages should use the latest stable version.

This issue relates to #54382

**Comment by xster** [comment]
@cyanglaz tentatively assigning this one to you to move all SDK versions to 29 (since it's now a requirement to deploy to the play store)

**Comment by cyanglaz** [comment]
I hit some CI problem and was dragged to other higher priority issues. Will revisit this issue as soon as possible
