### ISSUE TITLE
The function MyApp is not defined

### ISSUE THREAD

**Issue by rohan1234** [flutter/flutter#64399]
Hey everyone as I am polish my skills on UI but when I code it's completely fine even working but in console it's showing a message in file widget_test.dart error message like => The MyApp function is not defined   

Thanks in advance 🙂

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @rohan1234,
You might have changed the root method of your app in `main.dart` which usually is something like:

```
void main() {
  runApp(MyApp());
}
```
And the `test/widget_test.dart` file looks for `MyApp()` method in its test upon compiling. If you have removed / renamed the `MyApp()` method in `main.dart` file and if you are not running any widget tests, you can simply comment out the entire `widget_test.dart` which should resolve your issue.
Thanks.

**Comment by rohan1234** [comment]
@darshankawar @maheshmnj it`s resolved thnx for cooperating
