### ISSUE TITLE
Textfield is hidden by keyboard

### ISSUE THREAD

**Issue by Blacktoviche** [flutter/flutter#64392]
I have read and tried every single solution exists in flutter repository issues and outside but no luck.
As Taha referred in this comment [36266#issuecomment-639566006](https://github.com/flutter/flutter/issues/36266#issuecomment-639566006) here is flutter doctor -v output

`[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.1 at /home/mike/flutter
    • Framework revision 2ae34518b8 (2 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/mike/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

[when keyboard comes up..](https://github.com/flutter/flutter/issues/10826)
[Keyboard overlap all widget...](https://github.com/flutter/flutter/issues/20289)
And tens of stackoverflow solution but no luck.

Here is my latest code snap 

> Scaffold(
        backgroundColor: Constants.PRIMARY_COLOR,
        body:  ListView(
              children: <Widget>[
                    SizedBox(
                      height: 20,
                    ),
                    LogoWidget(),
                    Text(
                      "Text",
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Constants.ACCENT_COLOR),
                    ),
                    SizedBox(
                      height: MediaQuery.of(context).size.height / 4,
                    ),
                    _buildForm(),
                    _buildLoginButton()
                  ],
                ),
      );

**Comment by Blacktoviche** [comment]
@Mashood97 Thank you so much Muhammad but I tried something similar I used [flutter_keyboard_visibility](https://github.com/MisterJimson/flutter_keyboard_visibility) . But if the keyboard visible or not 
`MediaQuery.of(context).size.height}` is printing the same screen size just like there is nothing happened

**Comment by Mashood97** [comment]
You need to change the height first check on init state that if the keyboard is visible then change the height of the screen for eg: like this:
bool _isKeyboardVisible = false;

initState=> _isKeyboardVisible = true;

Container(
height: _isKeyboardVisible ? MediaQuery.of(context).size.height * 0.17 : MediaQuery.of(context).size.height * 0.7;
);
 

It's a rough example but I think this may clear you about this scenario.

**Comment by Blacktoviche** [comment]
@Mashood97 Thankx for this but it didn't work. I also tried @hazzo trick here  [10826#issuecomment-678814021](https://github.com/flutter/flutter/issues/10826#issuecomment-678814021) but  the same result it didn't work.
So I decided to investigate the external packages I use in the app by creating another project and use the packages one by one.
I found the cause of the problem finally,
I'm using [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) this package add many things to android folder files. the one which caused the problem is:
`<item name="android:windowFullscreen">true</item>`
in `[flutter_project_folder]/android/app/src/main/res/values`

When I remove this line the everything is working normal without any trick or any need for external keyboard packages.

**Comment by harishreddy-m** [comment]
Thank you. I spent three days struggling with different layouts, resizeToAvoidBottomInset.

This solved the problem.

**Comment by subzero911** [comment]
> @Mashood97 Thank you so much Muhammad but I tried something similar I used [flutter_keyboard_visibility]

flutter_keyboard_visibility is not a quite good solution. If you look at the source, you will notice that it doesn't actually checks a native keyboard. It just checks if less than 85% of viewport is available (considered that 15% of the screen is occupied by soft keyboard). So I wouldn't recomment to ever use this "plugin"

**Comment by Blacktoviche** [comment]
@subzero911  Thankx. I never thought of using such a package but disparately I used it that time and I removed it after I found that the issue related to a package not design things
