### ISSUE TITLE
Flutter: Offering WebView Preload

### ISSUE THREAD

**Issue by EitanSchwartz** [flutter/flutter#64402]
Hello all, first I'll introduce myself.
My name is Eitan and I'm working on Taboola's Flutter library.

**Problem Background:**
Our library offers content that's displayed in a WebView. To load it I'd like to call something like webview.loadUrl() where the url points to our content. Hopefully, this should work regardless of the WebView's Widget build() event and regardless of whether the WebView's attached to the view hierarchy or not.

In recent days, we've been working, together with MailOnline, to try and improve the speed of loading our content. I've been trying to build a method to preload our WebView's content before displaying it (ideally, in our WebView extending class constructor).

**The issue:**
To the best of my understanding:
- You can only call loadUrl() from the WebViewController of the WebView.
- You only get the relevant WebViewController from the WebView's onWebViewCreated(controller) callback.
- I found that onWebViewCreated(controller) is only called after Flutter calls the Widget's build() method.

This means you cannot preload a WebView's content, unless I'm missing something.

**P.s.,**
On our Android SDK we have no issue preloading, since we can call loadUrl() directly on the WebView, regardless of whether it's displayed or not.
There's an open ticket on this issue (with different use cases but still): https://github.com/flutter/flutter/issues/51875

**Our regular Android/iOS example projects for reference + documentation links:**
https://sdk.taboola.com/taboolasdk/docs/taboola-android-sdk-feed-via-native
https://sdk.taboola.com/taboolasdk/docs/taboola-ios-sdk-feed-via-native
https://github.com/taboola/android-sdk-examples
https://github.com/taboola/ios-sdk-examples

Any help would be appreciated,
Thx in advance, Eitan.

**Comment by TahaTesser** [comment]
Hi @EitanSchwartz 
You can comment your use case on the existing issue https://github.com/flutter/flutter/issues/51875
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
