### ISSUE TITLE
Inline google navigation in flutter app

### ISSUE THREAD

**Issue by gadishimwe** [flutter/flutter#64404]
Hello. I'm developing my first flutter application which will heavily rely on Google Maps services. The problem I'm having is specifically about using Google Navigation inline flutter app and I've been searching all over the internet, there is no package or a way of implementing such thing.

There is a package for this feature but doesn’t use google maps. It uses Mapbox instead which I don’t want to use.
https://pub.dev/packages/flutter_mapbox_navigation

I would like to have this capability in flutter and I think it will be useful to anyone who will want to develop apps that uses Google Navigation. 

![thread-2258909-10264555833951136684](https://user-images.githubusercontent.com/52411901/90973990-5e7da800-e527-11ea-8a3a-baa37dd79a96.jpg)

I want something similar to the above image.

**Comment by TahaTesser** [comment]
Hi @gadishimwe 
Navigation isn't support yet
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/29277
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
