### ISSUE TITLE
Allow to use custom SpringDescription and Tolerance with AnimationController.fling()

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#64400]
## Use case

Creating other variants of a fling animation.

## Proposal

These parameters are now not modifiable, they should be.
It wouldn't be such a problem if the `animateWith` could be used to create a custom fling, though, it's impossible, because it's bugged #60419
That's an easy fix.

**Comment by hs2361** [comment]
If you could provide me with some guidance, I would like to work on this issue.

**Comment by nt4f04uNd** [comment]
Closed with #65057
