### ISSUE TITLE
Hang during a reload

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#6440]
Meta bug to keep track of any new hangs during reload after [removing sticky errors](https://fuchsia-review.googlesource.com/#/c/12879) lands. See related https://github.com/flutter/flutter/issues/5513

**Comment by johnmccutchan** [comment]
@jason-simmons

**Comment by johnmccutchan** [comment]
@jason-simmons Has there been any issues since you landed your change?

**Comment by jason-simmons** [comment]
I haven't noticed any problems
