### ISSUE TITLE
Android Studio (not installed)

### ISSUE THREAD

**Issue by mrfoxie** [flutter/flutter#64416]
`C:\Users\SIDDH\Desktop>flutter doctor
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.21.0-7.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.48.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.`
![image](https://user-images.githubusercontent.com/25217451/90980158-53526880-e577-11ea-991b-94cf6ea95a99.png)

**Comment by mrfoxie** [comment]
> Hi @mrfoxie
> this is completely fine that no download the Android studio.
> you can either use vscode or intellij IDEA for developing flutter apps.
> you can run flutter apps without Android studio.
> Thanks

okay but I have android studio installed and configured it but as you told that it's fine then please close this

**Comment by darshankawar** [comment]
Closing this as non-issue.
