### ISSUE TITLE
web support for package_info, or means to stamp web build with version from pubspec.yaml

### ISSUE THREAD

**Issue by Leffe108** [flutter/flutter#64415]
## Use case
In some apps we want to display the version number of the app or include it in requests to a backend service (so we can have an idea about if people are using an old version due to bad cache settings on the web server, slow store updates etc)

For mobile it seems the flutter way is to put your version number in pubspec.yaml and use the package_info to access it at runtime.

However package_info doesn't support web platform, so it cannot be used there.

## Proposal
If possible:
* Provide web support in package_info plugin 

Otherwise:
* Provide a documented way to stamp the version into the web build. Either as in stamp it into a dart => js file or a side resource json file that the app can load to receive version number.

Other fields that package_info provide such as app name could be supported as well, but as they don't change as often it is less of a problem to hard code that into multiple source files.

**Comment by darshankawar** [comment]
Hi @Leffe108,
There's similar open issue describing your case, [46609](https://github.com/flutter/flutter/issues/46609).
Please follow-up there for updates and any questions.
Closing this as duplicate.
