### ISSUE TITLE
flutter webview could not play video media

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#64434]
1. chrome is ok
2. android native webview is ok.
3. flutter webview has problems.

test link:
[https://mp.weixin.qq.com/s/l4qGixv2vNONJH-ermU9Yg](https://mp.weixin.qq.com/s/l4qGixv2vNONJH-ermU9Yg)

**Comment by darshankawar** [comment]
Hi @hamberluo,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by hamberluo** [comment]
@darshankawar 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-CN)
    • Flutter version 1.20.2 at /Users/hamberluo/Documents/Dev/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hamberluo/Documents/Dev/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/hamberluo/Documents/Dev/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.


[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • IN2020 (mobile) • 192.168.0.116:5555 • android-arm64 • Android 10 (API 29)
```

complete reproducible code
url should be replaced by the link above
```
 body: Builder(
          builder: (BuildContext context) => WebView(
            initialUrl: url,
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {
              _controller.complete(webViewController);
            },
            onPageStarted: (String url) {
              print('Page started loading: $url');
            },
            onPageFinished: (String url) {
              print('Page finished loading: $url');
              _updateTitle();
            },
            javascriptChannels: <JavascriptChannel>{
              _toasterJavascriptChannel(context),
            },
            navigationDelegate: (NavigationRequest request) async {
              print('navigation to $request');
              final url = request.url;
              return NavigationDecision.navigate;
            },
            gestureNavigationEnabled: false,
          ),
        ),
```

**Comment by darshankawar** [comment]
Hi @hamberluo,
The test link you shared isn't loading for me when I directly click on it in browser. Getting `connection has timed out`.

Can you try with [this](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) link and see if it works for you ?

**Comment by hamberluo** [comment]
Hi @darshankawar,
[this](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) link works for me.

Can you try [this](https://mp.weixin.qq.com/s/l4qGixv2vNONJH-ermU9Yg) with Chrome?

**Comment by darshankawar** [comment]
@hamberluo,
Same issue with the new link you sent. Probably you can check [this](https://flutter.dev/community/china) link and see if it works for you .

**Comment by hamberluo** [comment]
> @hamberluo,
> Same issue with the new link you sent. Probably you can check [this](https://flutter.dev/community/china) link and see if it works for you .

it works for me.

**Comment by darshankawar** [comment]
@hamberluo I am unable to access the link you sent still. Please provide a working copy of the link that I can use to test your issue. You may also try to run the official `webview_flutter` [example](https://pub.dev/packages/webview_flutter/example) with the link you have and see if you still get the issue or not.
Thanks.

**Comment by hamberluo** [comment]
@darshankawar my code is just a copy of example.
I upload two screenshot for you to explain it.

before video play
![before video play](https://tva1.sinaimg.cn/large/007S8ZIlgy1gj1ubj61zyj30u01u0di3.jpg)

video play failed
![video play failed](https://tva1.sinaimg.cn/large/007S8ZIlgy1gj1ucsbzhxj30u01u00v4.jpg)

**Comment by darshankawar** [comment]
@hamberluo I am guessing you are in China, which has a separate Flutter [link](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) for Flutter apps to work. I'd suggest you go through this link one more time. That may also be the reason why the links you shared with me aren't opening at my end. Because, the regular local links I tried works properly within the plugin at my end.
Please try the local china links and see if it works, because like this, there's not going to be any solution and we'll just keep exchanging information.
Thanks.

**Comment by hamberluo** [comment]
@darshankawar yes I am in China. The (link)[https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site] you shared works for me.

I am guessing you cannot access the (video link)[https://mp.weixin.qq.com/s/l4qGixv2vNONJH-ermU9Yg] I shared.
That blocks our solution.

Maybe it is a html video tag compatibility issue.

**Comment by darshankawar** [comment]
@hamberluo It could be due to a firewall issue at your end. Please check if you can switch network and try again to see if it works.
Thanks.

**Comment by hamberluo** [comment]
Hi, @darshankawar 
I found Flutter 1.22.1 has fixed this issue.
So it should be closed.
Thank you!
