### ISSUE TITLE
After a flutter upgrade, do not download a platform SDK if the app is started for a different platform

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#64446]
Consider a situation where the user changed of channel or anything similar, then run:

```dart
flutter run -d macos
```

then in the logs, we can see lines such as:

```
Downloading Web SDK...                                             29.5s
```

This is inefficient, as the Web SDK shouldn't be needed to start the app on macos. 

The idea is that `flutter run` (and `flutter build`?) should understand that we want the SDK only of a very specific platform, and download only what is needed.

**Comment by jonahwilliams** [comment]
I added some more context to https://github.com/flutter/flutter/issues/6491#issuecomment-684102010 . Since this is a specific case of an already filled bug, I'm going to de-dupe this into it.
