### ISSUE TITLE
flutter run command is stuck so i cannot hot reload my app 

### ISSUE THREAD

**Issue by tufail-bin-nazir** [flutter/flutter#64445]
Although my app gets installed and opens in my physical device, but the command never ends so i don't get the option for the hot reload. i also ran 'flutter doctor -v' command , below is the result.
<details>
 <summary>flutter doctor -v</summary>

```
PS C:\Users\Tufail\Documents\myflutterprojects\myapp> flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.17134.1667], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (11 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Tufail\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.1)
    • VS Code at C:\Users\Tufail\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • POCO F1 (mobile) • 7f287a21 • android-arm64 • Android 10 (API 29)

• No issues found!
```
</details>

tried with the virtual device also , same issue

it is my first app, i started learning flutter from yesterday, 
The log for the 'flutter run -v' is in comments.

Thanks

**Comment by tufail-bin-nazir** [comment]
PS C:\Users\Tufail\Documents\myflutterprojects\myapp> flutter run --verbose
[ +133 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +230 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[   +9 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +76 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +33 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +52 ms] List of devices attached
           7f287a21               device product:beryllium model:POCO_F1 device:beryllium transport_id:4
[   +7 ms] C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell getprop
[  +91 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +241 ms] Generating
C:\Users\Tufail\Documents\myflutterprojects\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +82 ms] ro.hardware = qcom
[  +67 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +5 ms] Launching lib\main.dart on POCO F1 in debug mode...
[   +6 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Tufail\AppData\Local\Temp\flutter_tools.4a98e874\flutter_tool.50b9f6fc\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +24 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
C:\Users\Tufail\Documents\myflutterprojects\myapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: C:\Users\Tufail\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
C:\Users\Tufail\Documents\myflutterprojects\myapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.myapp" (Raw: "com.example.myapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="myapp" (Raw: "myapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.myapp.MainActivity" (Raw: "com.example.myapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +15 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell -x logcat -v time -t 1
[ +191 ms] Exit code 0 from: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell -x logcat -v time-t 1
[   +3 ms] --------- beginning of main
           08-24 17:11:26.011 D/ContactsDatabaseHelper(13881): onOpen: WAL enabled for profile.db: false
[   +6 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell -x logcat -v time -t 1
[ +209 ms] Exit code 0 from: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell -x logcat -v time-t 1
[   +2 ms] --------- beginning of main
           08-24 17:11:26.224 W/LabeledIntent( 2603): Custom titleChooser return null, fallback to the default titleChooser
[  +24 ms] <- compile package:myapp/main.dart
[  +18 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +136 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.4-6686687
                    Installed as C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +41 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +19 ms] Using gradle from C:\Users\Tufail\Documents\myflutterprojects\myapp\android\gradlew.bat.
[   +4 ms] C:\Users\Tufail\Documents\myflutterprojects\myapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +18 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +184 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +6 ms] executing: [C:\Users\Tufail\Documents\myflutterprojects\myapp\android/]
C:\Users\Tufail\Documents\myflutterprojects\myapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\Tufail\Documents\myflutterprojects\myapp\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2105 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +8 ms] > Task :app:preBuild UP-TO-DATE
[  +11 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +5 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +12 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +15 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +394 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +106 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +6 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +76 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +2 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[  +89 ms] > Task :app:packageDebug UP-TO-DATE
[ +200 ms] > Task :app:assembleDebug
[   +1 ms] BUILD SUCCESSFUL in 2s
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[ +479 ms] Running Gradle task 'assembleDebug'... (completed in 3.8s)
[  +48 ms] calculateSha: LocalDirectory:
'C:\Users\Tufail\Documents\myflutterprojects\myapp\build\app\outputs\flutter-apk'/app.apk
[  +70 ms] calculateSha: reading file took 68us
[ +650 ms] calculateSha: computing sha took 649us
[   +7 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +4 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
C:\Users\Tufail\Documents\myflutterprojects\myapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +27 ms] Exit code 0 from: C:\Users\Tufail\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree
C:\Users\Tufail\Documents\myflutterprojects\myapp\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.myapp" (Raw: "com.example.myapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="myapp" (Raw: "myapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.myapp.MainActivity" (Raw: "com.example.myapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +3 ms] Stopping app 'app.apk' on POCO F1.
[   +1 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell am force-stop
com.example.myapp
[ +198 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell pm list packages
com.example.myapp
[ +153 ms] package:com.example.myapp
[   +3 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell cat
/data/local/tmp/sky.com.example.myapp.sha1
[  +90 ms] 55f27d248d32fb985f5545cd908452c6458697f1
[   +3 ms] Latest build already installed.
[        ] POCO F1 startApp
[   +4 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.example.myapp/com.example.myapp.MainActivity
[ +168 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.myapp/.MainActivity (has extras) }
[   +2 ms] Waiting for observatory port to be available...
[ +934 ms] Observatory URL on device: http://127.0.0.1:42917/HvlUM1FUC48=/
[   +6 ms] executing: C:\Users\Tufail\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7f287a21 forward tcp:0 tcp:42917
[  +50 ms] 56442
[        ] Forwarded host port 56442 to device port 42917 for Observatory
[   +6 ms] Caching compiled dill
[  +31 ms] Connecting to service protocol: http://127.0.0.1:56442/HvlUM1FUC48=/

**Comment by markusaksli-nc** [comment]
Hi @tufail-bin-nazir 
Does the command not get past `Connecting to service protocol: http://127.0...` even after waiting for 30 seconds here? Do I understand correctly that this happens even with the default `flutter create` project?
Thank you

**Comment by tufail-bin-nazir** [comment]
Hi @markusaksli-nc 
yes , it doesn't pass the **connecting to service protocol** , its just stuck there forever.
yeah , i created a new project using the command line and  then run the command flutter run -v

**Comment by markusaksli-nc** [comment]
This could be caused by a network connection issue. Is it possible for you to try with a different network?

**Comment by tufail-bin-nazir** [comment]
ok i will try and let know the result

**Comment by tufail-bin-nazir** [comment]
@markusaksli-nc , i tried but no luck , stuck at same line again

**Comment by markusaksli-nc** [comment]
Not sure what more to do here, passing this on

**Comment by GaryQian** [comment]
@tufail-bin-nazir Are you still experiencing this with newer versions of flutter?
