### ISSUE TITLE
Image Picker Plugin Issue

### ISSUE THREAD

**Issue by shahryar-cmyk** [flutter/flutter#64447]
Hey,
Can you kindly update the
 https://pub.dev/packages/image_picker 
package read me. Package is updated but read me tab not.By using the previous read me file i crashed by flutter project it give me this error [https://github.com/flutter/flutter/issues/49343]. It took me 3 hr to figure it out and resolved it with making the new project and dumping the existing file with updated ImagePicker package usage.
Thanks

**Comment by darshankawar** [comment]
Hi @shahryar-cmyk,
Can you please elaborate on what exactly need to be updated in the `readme` tab ? What info in `readme` led to the crash ? and what fix you made that need to be updated in `readme` ?
Thanks.

**Comment by shahryar-cmyk** [comment]
Hi @darshankawar.
Currently i am trying uploading the image at the fire_storage package from image_picker. I don't know if the crash occured from the image_picker plugin or i am doing something wrong in my file. I added the file to the stackOverflow and added a response as i fixed the error.

**Comment by shahryar-cmyk** [comment]
Hi @darshankawar 
The issue is in my end not the plugin end. The issue i got because i am returning the ImagePicker() function of the file then gettting the image from camera then passing the file to the Fire Storage bucket.
In Code 
I written this ``    final pickedFile = await ImagePicker().getImage(source: ImageSource.camera);``
Instead of i have to write this `` final pickedFile = await picker.getImage(source: ImageSource.camera);``

**Comment by darshankawar** [comment]
@shahryar-cmyk glad to know you found the root-cause.
Given your last message, closing this as non-issue.
