### ISSUE TITLE
hasEnrolledFingerprints

### ISSUE THREAD

**Issue by cgdzin** [flutter/flutter#64451]
it would be nice if local_auth package add hasEnrolledFingerprints or FaceId function

**Comment by pedromassangocode** [comment]
Hi @cgdzin 
Can you elaborate more what is your proposal? Like, what this `hasEnrolledFingerprints` should actually do and/or return? This will help anyone that may want to contribute to this package.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
