### ISSUE TITLE
Move test utilities to separate folder from actual tests

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6445]
The following files in `packages/flutter` are test utilities, not tests, yet they live alongside the tests themselves.  We should clean this up just for hygiene's sake.

```
test/animation/animation_tester.dart
test/gestures/gesture_tester.dart
test/rendering/rendering_tester.dart
test/services/mocks_for_image_cache.dart
test/gestures/velocity_tracker_data.dart
test/widget/mock_text_input.dart
test/widget/test_widgets.dart
test/widget/semantics_tester.dart
```

**Comment by Hixie** [comment]
What is there to clean up? I don't really understand where you'd want these instead.

**Comment by tvolkert** [comment]
Closing - the use case that drove this request no longer exists.
