### ISSUE TITLE
microbenchmarks MatrixUtils_persp_transformPoint_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#64469]
Looks like it's on this roll.

It's small, but persists after this roll.

https://flutter-flutter-perf.skia.org/e/?begin=1598031665&end=1598051058&keys=X8d786420a42b5955be2c6b8178e87364&xbaroffset=21187

cc @gaaclarke this week's engine sheriff.

**Comment by zanderso** [comment]
Correction: @chinmaygarde is the current sheriff.

**Comment by flar** [comment]
This benchmark is entirely computational dart code with no dependence on the framework of the engine. Any regressions would be likely due to a change in Dart itself.

This was the only Dart roll I saw in that Engine roll: https://github.com/flutter/engine/pull/20680

**Comment by zanderso** [comment]
Here's the list of Dart commits: https://github.com/dart-lang/sdk/compare/2.10.0-45.0.dev...2.10.0-47.0.dev

@a-siva @alexmarkov @mkustermann

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/d11e89f5168a4c919d73181c15c2d96bd0867407

Not sure why this change (involving the VM service) would affect this particular benchmark.

@bkonyi

**Comment by bkonyi** [comment]
That change shouldn't have any meaningful impact on performance unless the test is spawning a Dart process with the VM service and dartdev enabled (this is the default) and you're measuring performance by including startup time. The change basically just delays the printing of the Observatory message until DDS connects to avoid races between VM service clients.

You might want to consider running any non-Flutter Dart tests with the `--disable-dart-dev` flag to avoid this extra overhead.

**Comment by flar** [comment]
This benchmark is the 3rd of 4 microbenchmark loops run in the same VM so a startup delay would more likely have affected one of the earlier benchmarks.

The same run performs the following benchmark tasks in the following order:

MatrixUtils_persp_transformRect_iteration   (improved from ~515 to ~510 on 8c3cff8)
MatrixUtils_affine_transformRect_iteration   (improved from ~387 to ~384 on 83c3ff8)
MatrixUtils_persp_transformPoint_iteration  (regressed from ~322 to ~327 on 83c3ff8)
MatrixUtils_affine_transformPoint_iteration.  (holds steady around ~301)

So it looks like the regression coincided with the two rect benchmarks (run earlier in the same run) improving a bit.

Each run causes the creation of 10,000,000 Rect or Point objects. Could the change have affected when GC runs happen during the benchmark?

**Comment by bkonyi** [comment]
> This benchmark is the 3rd of 4 microbenchmark loops run in the same VM so a startup delay would more likely have affected one of the earlier benchmarks.

If that's the case, https://github.com/dart-lang/sdk/commit/d11e89f5168a4c919d73181c15c2d96bd0867407 is definitely not going to cause a problem as it should only impact performance _before_ the main isolate of the process is started.

**Comment by zanderso** [comment]
@jason-simmons Do you still have the data from bisecting down to https://github.com/dart-lang/sdk/commit/d11e89f5168a4c919d73181c15c2d96bd0867407?

There are some changes to the Dart VM compiler that look like they could impact Dart performance:
https://github.com/dart-lang/sdk/commit/e5cf5d95023746c796c122d4b94f61963eb514b5
https://github.com/dart-lang/sdk/commit/816fd08b9281544e2c6ffb24e271307561b647cb
https://github.com/dart-lang/sdk/commit/fdd01da670e10b48c39516716103c309e711ed76

**Comment by jason-simmons** [comment]
I reran the benchmark.  This was on a Mac host and Android (Moto G4) target.
Framework commit https://github.com/flutter/flutter/commit/93395b4890241248b981de466b9b4189dd225864
Engine commit https://github.com/flutter/engine/commit/ea971c5859d08cb18ed75281a0c209948babb037

With Dart SDK commit https://github.com/dart-lang/sdk/commit/d11e89f5168a4c919d73181c15c2d96bd0867407:
```
    "MatrixUtils_persp_transformRect_iteration": 510.12010000000004,
    "MatrixUtils_affine_transformRect_iteration": 384.1256,
    "MatrixUtils_persp_transformPoint_iteration": 327.8765,
    "MatrixUtils_affine_transformPoint_iteration": 301.5176
```

With the previous Dart SDK commit https://github.com/dart-lang/sdk/commit/ae462475f978d1395c7147d2c7055f53114d8294:
```
    "MatrixUtils_persp_transformRect_iteration": 504.7586,
    "MatrixUtils_affine_transformRect_iteration": 382.8752,
    "MatrixUtils_persp_transformPoint_iteration": 322.998,
    "MatrixUtils_affine_transformPoint_iteration": 302.23
```

The difference is consistently reproducible.

**Comment by jason-simmons** [comment]
I can reproduce the difference in the MatrixUtils_persp benchmarks by starting with https://github.com/dart-lang/sdk/commit/ae462475f978d1395c7147d2c7055f53114d8294 and just adding these lines from https://github.com/dart-lang/sdk/commit/d11e89f5168a4c919d73181c15c2d96bd0867407#diff-49401d85ab1ec16dde493cf6e59c4790R40:

In `sdk/lib/_internal/vm/bin/vmservice_io.dart`:
```
@pragma("vm:entry-point")
bool _waitForDdsToAdvertiseService = false;
```

I don't know why a microbenchmark would be affected by this declaration.

**Comment by alexmarkov** [comment]
We might be getting a slightly different order of data and code in the application snapshot. Such reordering might affect tight loop micro-benchmarks by a few percent (for example due to changes in memory cache behavior).

**Comment by flar** [comment]
This benchmark was originally written a year ago to test a performance improvement that brought it down from ~450 range to ~345, so we've gotten even better than that without any changes to the code. I think a couple of ns regression is fine with regard to the purpose of the benchmark.

<img width="999" alt="Screen Shot 2020-08-28 at 4 40 16 PM" src="https://user-images.githubusercontent.com/50503328/91622718-5077bf00-e94d-11ea-88c4-e7aad1a9113e.png">

**Comment by zanderso** [comment]
Not sure if Skia perf requires us to manually rebaseline, but it sounds like that would be the right idea here. Dropping the priority, and assigning back to @kf6gpe to rebaseline/close.

**Comment by kf6gpe** [comment]
Sounds good! I've marked this as passing, so I think we're set.

R.
