### ISSUE TITLE
We need screenshots on the framework tour page

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6446]

**Comment by sethladd** [comment]
What problem are we addressing?  (just want to ensure we put the correct screenshots on there :)

**Comment by sethladd** [comment]
@Hixie do you remember what this was intended to help improve? Not sure how to help deliver sufficiency, given the title. Thanks for any background!

**Comment by Hixie** [comment]
I think this was just about having ANY screenshots on this page:
   https://flutter.io/widgets-intro/
...to orient the reader and show them various widgets.

**Comment by sethladd** [comment]
Ah, that we can do! :)

**Comment by sethladd** [comment]
Unlikely to do in time for M2, sorry. If someone wants to grab this, great!

**Comment by Sfshaza** [comment]
I'd like to use @gspencergoog's s/w to do this, if we can.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1882](https://github.com/flutter/website/issues/1882) via [**ZenHub**](https://www.zenhub.com/)
