### ISSUE TITLE
hostonly_devicelab_tests failing consistently on luci

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64466]
DeviceLab hostonly tests are failing consistently and currently blocking the migration of Cirrus to LUCI:

This is the link to the logs:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20hostonly_devicelab_tests

module_test failure:

```
 Task result:
 {
   "success": false,
   "reason": "Failed to copy read-only asset file"
 }
 Finished task "module_test"
```

module_custom_host_app_name_test:

```
Task result:
 {
   "success": false,
   "reason": "Failed to copy read-only asset file"
 }
```

gradle_jetifier_test:
```
Task result:
 {
   "success": false,
   "reason": "Task failed: Exception: APK doesn't contain class `io.flutter.plugins.firebaseauth.FirebaseAuthPlugin`."
 }
 Finished task "gradle_jetifier_test"

```

gradle_plugin_light_apk_test:
```
Task result:
 {
   "success": false,
   "reason": "Gradle did not exit with error as expected"
 }
 Finished task "gradle_plugin_light_apk_test"
```

**Comment by godofredoc** [comment]
\cc @zanderso @xster @blasten

**Comment by yjbanov** [comment]
Is it possible that due to the following `flutter doctor` warning some Android SDK tools are not available, causing gradle to crash?

```
! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
```

@godofredoc you mentioned offline that you suspect we could be leaking processes. What makes you believe that might be the case? (I don't see an indication in the logs)

**Comment by godofredoc** [comment]
We found in another windows tests that the builder was getting blocked because run_tests process was still running after the tests completed, and we added a kill command to make it pass https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/os_utils/api.py;l=40;bpv=1;bpt=0 but that is executed only after  the test run step has completed.

Our assumption of leaking processes comes for the error failing to delete files:

```
[gradle_plugin_bundle_test] [STDOUT] "C:\b\s\w\ir\cache\java\bin\java" exit code: 0
[gradle_plugin_bundle_test] [STDOUT] Failed to delete C:\b\s\w\ir\tmp\t\flutter_devicelab_gradle_plugin_test.c209959e: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\tmp\t\flutter_devicelab_gradle_plugin_test.c209959e' (OS Error: The process cannot access the file because it is being used by another process.
[gradle_plugin_bundle_test] [STDOUT] 
[gradle_plugin_bundle_test] [STDOUT] , errno = 32)
[gradle_plugin_bundle_test] [STDOUT] 
[gradle_plugin_bundle_test] [STDOUT] 
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870338257383019424/+/steps/run_test.dart_for_hostonly_devicelab_tests_shard_and_subshard_3_last/0/stdout

**Comment by pcsosinski** [comment]
@blasten is this on you radar?

**Comment by blasten** [comment]
@godofredoc we could just disable this test. It added some value last year, but not anymore.

**Comment by godofredoc** [comment]
After splitting the tests only windows continue failing. The same tests are passing on linux and mac:

* Windows build_aar_module_test  https://ci.chromium.org/p/flutter/builders/prod/Windows%20build_aar_module_test/5
* Windows gradle_jetifier_test https://ci.chromium.org/p/flutter/builders/prod/Windows%20gradle_jetifier_test/5
* Windows gradle_plugin_light_apk_test https://ci.chromium.org/p/flutter/builders/prod/Windows%20gradle_plugin_light_apk_test/4
* Windows module_custom_host_app_name_testhttps://ci.chromium.org/p/flutter/builders/prod/Windows%20module_custom_host_app_name_test/6
* Windows module_test https://ci.chromium.org/p/flutter/builders/prod/Windows%20module_test/5
* Windows plugin_dependencies_test https://ci.chromium.org/p/flutter/builders/prod/Windows%20plugin_dependencies_test/6

**Comment by godofredoc** [comment]
@blasten can you please take a look? seems like they are all affected by the same issue whenever there is a module involved the tests are failing in windows.

**Comment by blasten** [comment]
@godofredoc These tests are passing on Cirrus https://cirrus-ci.com/build/5366726126731264  (see `*-windows` jobs).  I'm not sure what is the difference in the environment.  If these tests are blocking progress in some front, I think they can be temporarily disabled provided they are passing in some other environment. 

This may need more debugging to better understand what is the difference between the Cirrus and the LUCI windows bots.

**Comment by blasten** [comment]
Let me know what is the best way to move forward. I can disable the tests, but please let me know where the metadata is for LUCI.

**Comment by godofredoc** [comment]
Fixed most of the problems in these tests. They were failing because in windows the line separator uses \r\n instead of just \n and the instructions to insert modules and dependencies were not working.

**Comment by blasten** [comment]
Great catch! Thanks @godofredoc
