### ISSUE TITLE
Builder testonly_devicelab_tests fails with "Infra Failure"

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#64465]
https://ci.chromium.org/p/flutter/builders/try/testonly_devicelab_tests/253?

What's the remedy?  The "Retry" button says "Note: this doesn't trigger anything else (e.g. CQ)." Not sure what CQ is (Commit Queue?). Appears to be room enough in the dialog for a more detailed explanation :-).

![Screen Shot 2020-08-24 at 8 38 00 AM](https://user-images.githubusercontent.com/1377460/91065286-23da4500-e5e5-11ea-8021-f706b896c4a9.png)

**Comment by godofredoc** [comment]
Hi Hans,

Thanks for the report, the recommended way to re-trigger tasks is from the github ui. But I can see that it was cancelled and the re-run button does not appear.

The workaround is to trigger all the tests manually: https://g3doc.corp.google.com/company/teams/flutter/luci/playbook.md#manually-trigger-build-for-a-pr-and-commit

Medium term solution: is to mark the timeouts as failures so the re-run button appears on the github UI. For now I re-ran all the tests for you.

**Comment by HansMuller** [comment]
Thanks for the help!

**Comment by godofredoc** [comment]
\cc @digiter as these are the devicelab tests on presubmit.
