### ISSUE TITLE
`ImageDecoderFixtureTest.ValidImageResultsInSuccess` is flaky and causes tree-closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#64475]
Sample [failure at here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871107728863735792/+/steps/Host_Tests_for_host_profile/0/stdout). This seems to have failed only once in the past 200 runs.

**Comment by chinmaygarde** [comment]
I am going to land [a low risk patch](https://github.com/flutter/engine/pull/20706/files) to get the tree going and then investigate de-flaking this.

**Comment by cbracken** [comment]
I'm seeing something similar here, except the segfault is in `ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode`:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870622653939142288/+/steps/Host_Tests_for_host_debug_unopt/0/stdout

**Comment by cbracken** [comment]
Just saw this again on Linux Host Engine release run of ui_unittests. Looks like Chinmay's above was profile.

Build: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/6839
Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8869029216637469536/+/steps/Host_Tests_for_host_release/0/stdout

**Comment by zanderso** [comment]
Let's track this one at the newer issue here: https://github.com/flutter/flutter/issues/80582
