### ISSUE TITLE
Flutter IOS compile fails after first compilation (need to clean the build every time IOS is tested)

### ISSUE THREAD

**Issue by yuvals38** [flutter/flutter#64473]
Hi,
I am a long time software engineer but newish at building flutter apps. My flutter/xcode/android studio are all up to date on their latest versions.

After the recent flutter update (1.20.2) I am having trouble compiling my new projects on xcode after the first compile (done on vscode for IOS). Android compilations are running fine.
Older flutter apps are still compiling successfully BUT a recent app I build (nothing complex at all) only passes compilation the first time. After that I get errors of paths that could not be mapped on xcode.

Also every time I compile for IOS it seems that the ios folder is copied again within itself in recursion. 

The log:

fatal error: lipo: can't map input file: /Users/yuvalsamuel/Library/Developer/Xcode/DerivedData/Runner-agmapakhycdyudbecdmtiebwqevs/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
fatal error: lipo: can't map input file: /Users/yuvalsamuel/Library/Developer/Xcode/DerivedData/Runner-agmapakhycdyudbecdmtiebwqevs/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
Failed to extract x86_64 for /Users/yuvalsamuel/Library/Developer/Xcode/DerivedData/Runner-agmapakhycdyudbecdmtiebwqevs/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/. Running lipo -info:
fatal error: lipo: can't map input file: /Users/yuvalsamuel/Library/Developer/Xcode/DerivedData/Runner-agmapakhycdyudbecdmtiebwqevs/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/flutter_assets/ios/Flutter/App.framework/ (Invalid argument)
Command PhaseScriptExecution failed with a nonzero exit code

Kind regards
Yuv

**Comment by mkiisoft** [comment]
This kind of question/issue will have better impact at StackOverFlow. Make sure you always post your "flutter doctor" so we have a better idea of the possible issues.

**Comment by jonahwilliams** [comment]
@yuvals38 can you include the full logs for a failed build? i.e. `flutter build/run -v` as well as the `flutter doctor -v` output?

**Comment by yuvals38** [comment]
> @yuvals38 can you include the full logs for a failed build? i.e. `flutter build/run -v` as well as the `flutter doctor -v` output?
I am using assets in this project (images only). The Assets folder sits in the main project folder ,could this be the problem?

build log for ios :

Changing current working directory to: /Users/yuvalsamuel/Developer/hummus
Running "flutter pub get" in hummus...                              0.4s
Building hummus for device (ios-release)...
Automatically signing iOS for device deployment using specified development team
in Xcode project: 5TBH3TRLZF
Running pod install...                                              1.3s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         0.9s
Xcode build done.                                           33.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/yuvalsamuel/Developer/hummus/ios/Runner/GeneratedPluginRegistrant.m:1
    0:9: fatal error: module 'path_provider' not found
    @import path_provider;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    /Users/yuvalsamuel/Developer/hummus/ios/Runner/GeneratedPluginRegistrant.m:1
    0:9: fatal error: module 'path_provider' not found
    @import path_provider;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

And the flutter doctor log:

✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-IL)
    • Flutter version 1.20.2 at /Users/yuvalsamuel/Developer/flutter
    • Framework revision bbfbf1770c (12 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yuvalsamuel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @yuvals38  
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/64259

This seems to be fixed in https://github.com/flutter/flutter/issues/57210, which is not landed into `stable` yet https://github.com/flutter/flutter/issues/64259#issuecomment-679846698

Can you upgrade to latest `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
