### ISSUE TITLE
GLContextSwitch not working with unobstructed platform views.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#64480]
**Background**

`GLContextSwitch` is a way to automatically clear flutter's gl context when rasterizer is done with it. It makes sure the `external_view_embedder` doesn't have access to the flutter's gl context, thus preventing 3rd party libraries from mistakenly get the flutter's gl context (for example, lower version of google map).

The `surface_frame->SubmitFrame()` used to be the end of the flutter's gl context life cycle, and `external_view_embedder` starts after.

See: https://github.com/flutter/flutter/issues/41620

**Issue**

With unobstructed platform views, which requires `surface_frame->SubmitFrame()` happen after `external_view_embedder->SubmitFrame()`, the flutter's gl context is not cleared during `external_view_embedder->SubmitFrame()` anymore.

This issue affects android with hybrid composition platform views, and lower version of iOS that uses open gl. This issue is rare because it only happens when a 3rd party library explicitly creates their own open gl context and did not handle the gl context properly.

**Solution**

One way to fix it this to clear the "current" gl context before `external_view_embedder->SubmitFrame()`, and re-set flutter's gl context to current again in `surface_frame->SubmitFrame()`.

**Comment by jonahwilliams** [comment]
Out of date as we no longer support GL on iOS
