### ISSUE TITLE
Odd wrapping in Gallery Grid example on iPhone 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6448]
![img_0002](https://cloud.githubusercontent.com/assets/11857803/19584877/b0af723e-96fc-11e6-9173-58e31efca481.PNG)

**Comment by abarth** [comment]
It's interesting that some of these have text overflow effects.  I wonder if there's a bug in the ellipsizing code.  /cc @jason-simmons

**Comment by eseidelGoogle** [comment]
I'm no longer seeing this.

**Comment by xster** [comment]
Looks fine on an SE as well. Font size dynamically adjusts.
