### ISSUE TITLE
image list duration tests use hard coded certificate, which has expired.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#64489]
This test needs to be rewritten to not require renewing the certificate, perhaps by using HttpOverrides to simulate network loading.

Disabled in https://github.com/flutter/flutter/pull/64486

**Comment by Hixie** [comment]
@aam Looks like these tests are yours.

**Comment by aam** [comment]
Addressed via https://github.com/flutter/flutter/pull/64519
