### ISSUE TITLE
Pinch zoom in Gallery grid example isn't under my fingers

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6449]
I would expect it to zoom under my fingers, instead it seems to just scale from 0,0.

See video.
https://youtu.be/Tkehd48owLM

**Comment by eseidelGoogle** [comment]
https://youtu.be/Tkehd48owLM

**Comment by HansMuller** [comment]
I have a fix for this. Will try and land it tomorrow.
