### ISSUE TITLE
Router widget web engine integration

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#64494]
The router widget reports its route information back to the engine through the SystemChannel.navigation `routeInformationUpdated` method. However, the engine side functionality has not been implemented yet. This is one of the blocker that needs to be resolved before we can release the router widget.

According to the [Router design doc](https://docs.google.com/document/d/1QodTFmwVr1yk8dyQvoqkeILxvm92oikB1bVhHTtp6R4/edit#heading=h.xzma0mek5jk2) , the web engine should create browser history entries for those route information in order to support browser backward and forward buttons. We also need to have some mechanisms to switch between new and old behaviors for backward compatibility.

**Comment by GitHubMurt** [comment]
Looks like this is not working
flutter --version
Flutter 1.22.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (6 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1

**Comment by chunhtai** [comment]
@GitHubMurt it is only can you try with master channel? I don't think this is in beta yet

**Comment by GitHubMurt** [comment]
@chunhtai  Yes it works on master thanks!
