### ISSUE TITLE
Single-character wrapping in title bar for swipe-to-dismiss demo on iPhone 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6450]
I would expect either the whole word to wrap, or probably better to have it change phone size or ellipsize.  We probably want some standardized titlebar behavior here.

![img_0003](https://cloud.githubusercontent.com/assets/11857803/19585022/e1e33632-96fd-11e6-9dad-417ca15f908f.PNG)

**Comment by abarth** [comment]
We need to add a text overflow effect to app bar

**Comment by HansMuller** [comment]
I'll do that now. Should be a quick fix.

**Comment by jason-simmons** [comment]
This should be fixed now
