### ISSUE TITLE
average_cpu_usage simple_animation_perf_ios regression..

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#64515]
https://flutter-flutter-perf.skia.org/e/?begin=1597878666&end=1597946236&keys=Xdc817274e9c4343e64e486c6ed262323&xbaroffset=21155
Looks like it started on this engine roll. https://github.com/flutter/flutter/pull/64213

cc @chinmaygarde (this week's sheriff) and @liyuqian

**Comment by zanderso** [comment]
Maybe https://github.com/flutter/engine/pull/19842 (Dart_HintFreed) or https://github.com/flutter/engine/pull/20631 (Skia roll)? @dnfield

**Comment by dnfield** [comment]
Revert has landed upstream. Will keep this open until it rolls into framework.

**Comment by dnfield** [comment]
Fixed in https://github.com/flutter/flutter/pull/64593
