### ISSUE TITLE
Font distortion on iOS14

### ISSUE THREAD

**Issue by Sunzhen0402** [flutter/flutter#64528]
## Steps to Reproduce

<img width="512" alt="Font distortion" src="https://user-images.githubusercontent.com/44433901/91115742-771fc680-e6bd-11ea-8ccd-f4fa875714a9.png">
## The font is obviously distorted on iOS14

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Sunzhen0402 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by pedromassangocode** [comment]
@xster I was investigating related issues and found out that you merged a PR that closed https://github.com/flutter/flutter/issues/60013 Just want you to confirm if this issue should still remain opened.

**Comment by Sunzhen0402** [comment]
hi @pedromassangocode 
# my  `flutter doctor -v`
Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2005, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/xxx
    • Framework revision 8af6b2f038 (8 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by pedromassangocode** [comment]
Hi @Sunzhen0402 
Since a [related issue](https://github.com/flutter/flutter/issues/60013) was fixed and the PR landed recently on `master` channel on https://github.com/flutter/engine/pull/20557 can you upgrade to `master` and try again:
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by xster** [comment]
I'm gonna close this issue. 1.17 is unfortunately pretty old and it's fixed on master now. 

![Screen Shot 2020-08-25 at 9 22 45 AM](https://user-images.githubusercontent.com/156888/91200956-b3025e00-e6b4-11ea-9008-a8f274dff8a7.png)

Chinese and Latin all look ok on iOS 14 now.
