### ISSUE TITLE
AM/PM clipped in Time Picker on iPhone 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6452]
![img_0004](https://cloud.githubusercontent.com/assets/11857803/19585169/08a918b2-96ff-11e6-9bc4-81908efbc057.PNG)

**Comment by abarth** [comment]
This is a dup of a customer fast issue

**Comment by eseidelGoogle** [comment]
That's https://github.com/flutter/flutter/issues/6314
