### ISSUE TITLE
Compile darwin Flutter frameworks with minimum deployment version flags

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#64520]
iOS 8.0 was broken in https://github.com/flutter/flutter/issues/64017 even though it's the documented minimum version supported by the engine.

https://flutter.dev/docs/deployment/ios#review-xcode-project-settings
> Flutter supports iOS 8.0 and later.

This may have been detected if the respective iOS/macOS/simulators were compiled with:
`-miphoneos-version-min=8.0`
`-miphoneos-version-min=8.0`
`-mmacosx-version-min=10.11`

https://chromium.googlesource.com/chromium/src/build/config/+/refs/heads/master/ios/BUILD.gn#118

Use these flags so this accidental deprecation doesn't happen again.

**Comment by jmagman** [comment]
`gn` has something like this in their example app:
https://gn.googlesource.com/gn/+/refs/heads/master/examples/ios/build/config/ios/deployment_target.gni

**Comment by jmagman** [comment]
I can't figure out where it's being set up, but the flag already seems to be set?
```
[1/97] ../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/flutter/shell/gpu/gpu_surface_metal.gpu_surface_metal.o.d ... -miphoneos-version-min=8.0  ...  -c ../../flutter/shell/gpu/gpu_surface_metal.mm -o obj/flutter/shell/gpu/gpu_surface_metal.gpu_surface_metal.o
```
Same with `-mmacosx-version-min` for the host.

And that flag wouldn't have prevented #64017, it just seems to do availability-type checks.

@chinmaygarde @dnfield @jason-simmons do you guys know where it's being set to 8.0?

**Comment by dnfield** [comment]
https://github.com/flutter/buildroot/blob/a5d7e3e9b3bb79e92ab89ebacd3779d3ef346753/build/config/ios/ios_sdk.gni#L17

**Comment by jmagman** [comment]
Thanks, @dnfield.  Closing.
