### ISSUE TITLE
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)

### ISSUE THREAD

**Issue by Vandanaclover** [flutter/flutter#64532]
when login with google. This is show exception.

PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/33393 
and please refer this as well https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google/54696963
Thanks.

**Comment by pedromassangocode** [comment]
Hi @Vandanaclover 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/33393).

You can try the solution described on https://github.com/flutter/flutter/issues/33393#issuecomment-510395178 and see if that works for you.

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
