### ISSUE TITLE
Update defualt Android targetSdkVersion

### ISSUE THREAD

**Issue by fareezMaple** [flutter/flutter#64538]
## Use case

As stated by Google:
> This is a reminder that starting November 2, 2020, updates to apps and games on Google Play will be required to target Android 10 (API level 29) or higher. After this date, the Play Console will prevent you from submitting new app bundles and APKs with a targetSdkVersion less than 29. Please note that Wear OS apps are not subject to the API level 29 requirement. This will not impact your existing listing on the Play Store.
## Proposal

`targetSdkVersion` in `android\app\build.gradle` need to be defaulted to `29`

**Comment by Abhishek01039** [comment]
HI @fareezMaple 
Google team are working on it 
you can check it here
https://github.com/flutter/flutter/pull/63008
https://github.com/flutter/flutter/issues/54382
https://github.com/flutter/flutter/issues/62295

**Comment by markusaksli-nc** [comment]
Closing this as a duplicate
