### ISSUE TITLE
App stays on native Splash-Screen with looping "iokit-get-properties" Errors for minutes before launching

### ISSUE THREAD

**Issue by maxp89** [flutter/flutter#64544]
## Problem in short

Launching my Flutter App from within Android Studio causes the app to loop errors on a physical iPhone 8 for about 2-5 minutes (check device logs in details section). 
After this it loads the first Flutter view and the app works fine.

## Steps to Reproduce

This behavior occurs with a developed app on a physical iPhone 8 with latest iOS 13.6.1, with XCode 11.6 on my Mac (more versions in details section)

Due to an NDA I cannot share details about that app here, but I tried to reproduce the errors I saw on the "console.app" of the iPhone.

I cannot reproduce it every time, but it occurs every day by just doing:
- Launch Android Studio
- Launch the Flutter App

**Expected results:** 
App shows Splash Screen and after some seconds the first Flutter-view is drawn on the screen.

**Actual results:** 
App shows Splash Screen for about 4 minutes and then loads the first Flutter-view

**My current Workaround:** 
After creating a new Flutter Project with Android Studio Wizard, launching it and then launch the first app which hung, sometimes the plain Flutter Demo app hangs, sometimes everything loads smoothly (which happens more often).

Also, if I try to get some verbose output or use the command-line to run the app, it works fine. Thus, it seems to be occur only with Androids Run Button. However, the launch configuration is as normal as it can be.

The only real things I was able to capture are the iPhone device logs...
I googled the log-output and found https://github.com/flutter/flutter/issues/60406.

<details>

Device Logs

"fehler" means error.

Those log statements loop for minutes, until the first Flutter-view is loaded.

> fehler	10:41:16.539129+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifier
> fehler	10:41:16.539299+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOMatchCategory
> fehler	10:41:16.539378+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProviderClass
> fehler	10:41:16.539448+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatch
> fehler	10:41:16.539516+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOSourceVersion
> fehler	10:41:16.539608+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifierKernel
> fehler	10:41:16.539803+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatched
> fehler	10:41:16.539940+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProbeScore
> fehler	10:41:16.540318+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegend
> fehler	10:41:16.540525+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegendPublic
> fehler	10:41:16.540637+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOPowerManagement
> fehler	10:41:16.540834+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMVersionNumber
> fehler	10:41:16.540941+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMBuildTime
> fehler	10:41:16.541033+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties AGXTraceCodeVersion
> fehler	10:41:16.541141+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterBundleName
> fehler	10:41:16.541228+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterPluginClassName
> standard	10:41:16.559607+0200	wifid	Too frequent(4.999997 secs) CCA event from driver
> fehler	10:41:16.754395+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifier
> fehler	10:41:16.754609+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOMatchCategory
> fehler	10:41:16.754899+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProviderClass
> fehler	10:41:16.755142+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatch
> fehler	10:41:16.755284+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOSourceVersion
> fehler	10:41:16.755482+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifierKernel
> fehler	10:41:16.755655+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatched
> fehler	10:41:16.755745+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProbeScore
> fehler	10:41:16.755944+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegend
> fehler	10:41:16.756108+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegendPublic
> fehler	10:41:16.756230+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOPowerManagement
> fehler	10:41:16.756397+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMVersionNumber
> fehler	10:41:16.756493+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMBuildTime
> fehler	10:41:16.756580+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties AGXTraceCodeVersion
> fehler	10:41:16.756688+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterBundleName
> fehler	10:41:16.756803+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterPluginClassName
> fehler	10:41:16.970418+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifier
> fehler	10:41:16.970628+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOMatchCategory
> fehler	10:41:16.970877+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProviderClass
> fehler	10:41:16.971028+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatch
> fehler	10:41:16.971157+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOSourceVersion
> fehler	10:41:16.971266+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifierKernel
> fehler	10:41:16.971406+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatched
> fehler	10:41:16.971514+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProbeScore
> fehler	10:41:16.971981+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegend
> fehler	10:41:16.972217+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegendPublic
> fehler	10:41:16.972445+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOPowerManagement
> fehler	10:41:16.972543+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMVersionNumber
> fehler	10:41:16.972615+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMBuildTime
> fehler	10:41:16.972687+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties AGXTraceCodeVersion
> fehler	10:41:16.972862+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterBundleName
> fehler	10:41:16.972954+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterPluginClassName
> standard	10:41:17.122112+0200	locationd	os_transaction created: (<private>) <private>
> standard	10:41:17.122272+0200	locationd	os_transaction released: (<private>) <private>
> fehler	10:41:17.186387+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifier
> fehler	10:41:17.186542+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOMatchCategory
> fehler	10:41:17.186640+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProviderClass
> fehler	10:41:17.186775+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatch
> fehler	10:41:17.186913+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOSourceVersion
> fehler	10:41:17.187047+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifierKernel
> fehler	10:41:17.187145+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatched
> fehler	10:41:17.187220+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProbeScore
> fehler	10:41:17.187921+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegend
> fehler	10:41:17.188088+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegendPublic
> fehler	10:41:17.188234+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOPowerManagement
> fehler	10:41:17.188344+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMVersionNumber
> fehler	10:41:17.188435+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMBuildTime
> fehler	10:41:17.188504+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties AGXTraceCodeVersion
> fehler	10:41:17.188585+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterBundleName
> fehler	10:41:17.188652+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterPluginClassName
> fehler	10:41:17.401786+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifier
> fehler	10:41:17.401942+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOMatchCategory
> fehler	10:41:17.402017+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProviderClass
> fehler	10:41:17.402133+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatch
> fehler	10:41:17.402359+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOSourceVersion
> fehler	10:41:17.402482+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties CFBundleIdentifierKernel
> fehler	10:41:17.402607+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IONameMatched
> fehler	10:41:17.402729+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOProbeScore
> fehler	10:41:17.402959+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegend
> fehler	10:41:17.403053+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOReportLegendPublic
> fehler	10:41:17.403177+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties IOPowerManagement
> fehler	10:41:17.403275+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMVersionNumber
> fehler	10:41:17.403404+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties SCMBuildTime
> fehler	10:41:17.403613+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties AGXTraceCodeVersion
> fehler	10:41:17.403815+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterBundleName
> fehler	10:41:17.403903+0200	kernel	Sandbox: Runner(634) deny(1) iokit-get-properties GPURawCounterPluginClassName

Flutter analyze
```
No issues found! (ran in 7.5s)
```

Flutter doctor
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale de-DE)
    • Flutter version 1.20.2 at
      /Users/X@X.com/workspaces/flutter
    • Framework revision bbfbf1770c (12 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/X@X.com/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone von X (mobile) • ... • ios • iOS 13.6.1

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @maxp89 
Not sure what do you mean by "splash screen", Did you add splash your screen or are you getting a white screen?
Can you please different drive or simulator? Does this reproduce on devices or just iPhone 8?

If the problem persists,  Can you upgrade to latest `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by maxp89** [comment]
Hi @TahaTesser we added a custom native splash screen to our app, showcasing a logo on a colored background. This was done with XCode/Storyboard, I think. 

The Flutter Demo app gets stuck sometimes as well. This results in a white screen for minutes before it shows the counter-app.

**Comment by TahaTesser** [comment]
@maxp89 
Thanks for providing info 

If the problem persists on the latest `master`, Can you please provide your `flutter doctor -v` **with the latest master** and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by fnicastri** [comment]
Could it be related to #63025 ?

**Comment by maxp89** [comment]
@fnicastri thank you for your idea. 
I just looked at that ticket, it doesn't seem to be the same warning/error.

The #63025 did not mention any "stopping" or "hanging" of the flutter app.

The log output in this ticket comes from the Apple Console application and the physical device. 
Android Studio is not that verbose and doesn't output anything useful to trace that bug :( 

I have a feeling that it could be something with my Mac... other colleagues developing the same app do not seem to have the same problem, however they have other minor issues.

It might take a few days for me to reproduce the problem... and follow @TahaTesser suggestions.

**Comment by fnicastri** [comment]
@maxp89 
It's not just you, I have the same issue.
And I have #63025 too.
It was just an idea...

**Comment by acoutts** [comment]
I'm experiencing this too. Very flaky to get a physical iOS device to run lately.

**Comment by maxp89** [comment]
First of all thank you for your efforts. 

This bug did not happen again to me with the latest flutter versions. 
Thus, can stay closed.
