### ISSUE TITLE
STS_GLApi : DTS, ODTC are not allowed for Package

### ISSUE THREAD

**Issue by arfeenmushtaq** [flutter/flutter#64548]
Hi Guys,
   Im experiencing following issue when I try to run my application on a device SM G610F. The application runs fine on the emulator. I have also tried giving internet permission. it still does not work.
   The application launched but is unable to make any network calls 

Launching lib\main.dart on SM G610F in debug mode...
Running Gradle task 'assembleDebug'...
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device SM G610F...
D/libGLESv2( 8189): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.trevatell_template
V/InputMethodManager( 8189): Starting input: tba=android.view.inputmethod.EditorInfo@d5e9765 nm : com.example.trevatell_template ic=null
D/InputMethodManager( 8189): startInputInner - Id : 0
I/InputMethodManager( 8189): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 8189): Input channel constructed: fd=107
D/InputTransport( 8189): Input channel destroyed: fd=87
D/SurfaceView( 8189): windowStopped(true) false 17f2756 of ViewRootImpl@326ff18[MainActivity]
D/SurfaceView( 8189): BG show() Surface(name=Background for - SurfaceView - com.example.trevatell_template/com.example.trevatell_template.MainActivity@17f2756@0) io.flutter.embedding.android.FlutterSurfaceView{17f2756 V.E...... ........ 0,0-1080,1920}
D/SurfaceView( 8189): surfaceDestroyed 1 #1 io.flutter.embedding.android.FlutterSurfaceView{17f2756 V.E...... ........ 0,0-1080,1920}
D/SurfaceView( 8189): onWindowVisibilityChanged(8) false 17f2756 of ViewRootImpl@326ff18[MainActivity]
D/SurfaceView( 8189): BG show() Surface(name=Background for - SurfaceView - com.example.trevatell_template/com.example.trevatell_template.MainActivity@17f2756@0) io.flutter.embedding.android.FlutterSurfaceView{17f2756 V.E...... ........ 0,0-1080,1920}
D/OpenGLRenderer( 8189): eglDestroySurface = 0xcd3ddbb0, 0xcd397000
D/ViewRootImpl@326ff18[MainActivity]( 8189): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@326ff18[MainActivity]( 8189): MSG_WINDOW_FOCUS_CHANGED 0

**Comment by arfeenmushtaq** [comment]
D:\Projects\ACTProjects\qsmart_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.0)
[√] VS Code (version 1.48.1)
[√] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @arfeenmushtaq 
Are you using google sign in or firebase? 

Can you upgrade to latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
