### ISSUE TITLE
Can not set --target-platform for locally-built engine 

### ISSUE THREAD

**Issue by littleGnAl** [flutter/flutter#64554]
## Steps to Reproduce

* Compile the engine by following the wiki [https://github.com/flutter/flutter/wiki/Compiling-the-engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine)

* Run the following command:
```
flutter build aar \
    --target-platform android-arm,android-arm64,android-x64 
    --local-engine-src-path <my local engine path>/engine/src \ 
    --local-engine=android_debug_unopt \
    --no-profile --no-release -v
```

No matter what I set for the `--target-platform`, the target platform will always `android-arm` for my command above.

After I read the source code of `flutter_tools`, I found that it only get the target platform according the local engine path.

https://github.com/flutter/flutter/blob/707f995de35bdf887169fcd39448b877cbcc8992/packages/flutter_tools/lib/src/android/gradle.dart#L622-L623

**Comment by jonahwilliams** [comment]
You can only use the target-platform provided by the locally built engine - if you need a different target-platform you need to build a different engine variant.

**Comment by littleGnAl** [comment]
```
drwx------   35 littlegnal  staff      1120 Aug 25 15:32 android_debug_unopt
drwx------   35 littlegnal  staff      1120 Aug 25 15:32 android_debug_unopt_arm64
drwx------   35 littlegnal  staff      1120 Aug 25 15:32 android_debug_unopt_x64
drwx------    6 littlegnal  staff       192 Aug 17 00:52 android_debug_unopt_x86
drwx------   35 littlegnal  staff      1120 Aug 25 15:32 android_profile
drwx------   34 littlegnal  staff      1088 Aug 25 15:32 android_profile_arm64
drwx------   34 littlegnal  staff      1088 Aug 25 15:32 android_profile_x64
drwx------   35 littlegnal  staff      1120 Aug 25 15:32 android_release
drwx------   33 littlegnal  staff      1056 Aug 25 15:32 android_release_arm64
drwx------   33 littlegnal  staff      1056 Aug 25 15:32 android_release_x64
-rw-r--r--    1 littlegnal  staff  15571309 Aug 25 17:36 compile_commands.json
drwx------   80 littlegnal  staff      2560 Aug 25 15:32 host_debug_unopt
drwx------   73 littlegnal  staff      2336 Aug 25 17:50 host_debug_unopt_arm64
drwx------   73 littlegnal  staff      2336 Aug 25 18:05 host_debug_unopt_x64
drwx------  477 littlegnal  staff     15264 Aug 25 15:32 host_profile
drwx------   80 littlegnal  staff      2560 Aug 25 15:32 host_release
```
I have built different engine variants, it possible to set multiple target-platform to one build command?

If not, one AAR can only use in a single target-platform.

**Comment by jonahwilliams** [comment]
No, its not supported

**Comment by TahaTesser** [comment]
@jonahwilliams 
Can this issue be closed? 
Thank you

**Comment by jonahwilliams** [comment]
@littleGnAl my recommendation would be to create different outputs AARs per target platform and then merge them with something like https://stackoverflow.com/questions/54949399/how-to-merge-combine-two-aar-files

**Comment by littleGnAl** [comment]
@jonahwilliams Thank you.

**Comment by TahaTesser** [comment]
@littleGnAl 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by littleGnAl** [comment]
@TahaTesser Yes, it's okay to close, thank you(I don't know why the bot reopens it...). 

@jonahwilliams Btw, I found that it can package all local engines together as a single `out/xx/Flutter.framework` and replace `$FRAMEWORK_PATH/bin/cache/artifacts/engine/ios-xx/` folder on iOS(https://github.com/flutter/flutter/issues/61045#issuecomment-668278475), is there a similar way in Android like that(maybe this has out of the topic of this issue)?
