### ISSUE TITLE
Same package name and dependency

### ISSUE THREAD

**Issue by viralvaghela** [flutter/flutter#64553]
## Use case

When the name of the package and dependency name same we are getting an error and lots of beginners are facing this.

## Proposal

can we do something so that we don't have to change the package name?

**Comment by Abhishek01039** [comment]
HI @viralvaghela 
can you please clarify the code?
if possible then please provide the minimal reproduction code in which you are facing this issue.
Thanks

**Comment by TahaTesser** [comment]
Hi @viralvaghela 
You can import `as`, https://stackoverflow.com/a/57952240
Can you please provide more details
Thank you

**Comment by viralvaghela** [comment]
Okay Thank you @TahaTesser

**Comment by TahaTesser** [comment]
Hi @viralvaghela 
Glad you got your answer, given your last message I feel safe to close this issue if you disagree please write in the comments and I will reopen it. 
Thank you
