### ISSUE TITLE
Support double-tap-drag gesture to select a block of text

### ISSUE THREAD

**Issue by dave** [flutter/flutter#64550]
## Use case

In native iOS text fields, double-tapping on text followed by a drag selects a block of text. In flutter apps this doesn't happen. 

## Proposal

We should support this gesture.

**Comment by dave** [comment]
This is related to: https://github.com/flutter/flutter/issues/63576

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Thanks for the issue, I agree.  Long-press-and-drag currently does work (except in SelectableText https://github.com/flutter/flutter/pull/63994), and double-tap-and-drag should do the same thing I think.

**Comment by Renzo-Olivares** [comment]
Closed by #117502
