### ISSUE TITLE
Crash in ShellTest.OnPlatformViewDestroyWhenThreadsAreMerging in shell_unittests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64562]
From the logs [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871039744422876160/+/steps/Host_Tests_for_host_debug_unopt/0/stdout?format=raw).
```
...
[ RUN      ] ShellTest.OnPlatformViewDestroyWhenThreadsAreMerging
...
Traceback (most recent call last):
...
Exception: Command "/b/s/w/ir/cache/builder/src/out/host_debug_unopt/shell_unittests --gtest_shuffle --gtest_repeat=2" exited with code -11
```

P0 because the tree is closed on this failure. The test added in https://github.com/flutter/engine/commit/e7136c3f5960f34b27579e893454886db105e88b, so assigning @cyanglaz

**Comment by cyanglaz** [comment]
Going to move it to P1 as it is not blocking the tree ATM. Still need to resolve this ASAP.
