### ISSUE TITLE
Image picker plugin returns image instead of video

### ISSUE THREAD

**Issue by weissmanuel** [flutter/flutter#64567]
Hi,

I am using the image_picker plugin on version 0.6.7+7.

Now I'm facing the issue if I want to pick a video from the video gallery on android devices. Instead of returning a video the plugin returns an image as picked_file.

<img width="719" alt="Bildschirmfoto 2020-08-25 um 18 31 21" src="https://user-images.githubusercontent.com/28729535/91202267-d7d0f280-e701-11ea-8e48-d1c0f386280e.png">

Here my code snipped to get videos:

```
pickedFile = await _picker.getVideo(
          source: widget.imageSource,
          preferredCameraDevice: CameraDevice.front,
          maxDuration: widget.maxVideoDuration,
        );
```

Does anyone know how to fix this?

**Comment by Abhishek01039** [comment]
Hi @weissmanuel 
can you please provide your `flutter doctor -v` and `flutter run -v`?
Thanks

**Comment by weissmanuel** [comment]
Hi @Abhishek01039 

Thanks for your help! 

`flutter doctor -v`

Manus-MacBook:fs_you_flutter manuel$ flutter doctor -v

[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.4 19E287, locale de-CH)
    • Flutter version 1.21.0-9.1.pre at /usr/local/flutter
    • Framework revision be9bc8cb39 (7 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/manuel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/manuel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

 
[✓] Connected device (1 available)            
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!


`flutter run -v`

[flutter_run_v.TXT](https://github.com/flutter/flutter/files/5125754/flutter_run_v.TXT)

**Comment by darshankawar** [comment]
Hi @weissmanuel,
There's similar open issue describing your case, [52419](https://github.com/flutter/flutter/issues/52419).
Please follow-up there for updates and any questions.
Closing this as duplicate.
