### ISSUE TITLE
Google Map Unresponsive - White/Blank screen in Place Tracker App

### ISSUE THREAD

**Issue by bajajsahil** [flutter/flutter#64568]
I am seeing the white/blank screen issue when

1. I switch between apps
3. I navigate outside of the app e.g. open the phone dialer using url_launcher.
3. I open the camera on top of google map and comes back. (see steps - https://github.com/flutter/flutter/issues/39797#issuecomment-664171459)

This issue is also coming in the official place tracker app and in my own app which uses google map plugin.

This issue I have already opened in flutter/sample repository - https://github.com/flutter/samples/issues/532

### Place Tracker APP

![Screenshot_20200818-233446](https://user-images.githubusercontent.com/19187821/90974128-e1156000-e545-11ea-91ed-093ae13794bb.jpg)

### My APP

![Screenshot_20200818-233420](https://user-images.githubusercontent.com/19187821/90974156-2043b100-e546-11ea-9429-e556834efb52.jpg)

_**google_maps_flutter**_ - 0.5.30

**_flutter doctor -v_**

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.17134.165], locale en-IN)
    • Flutter version 1.20.1 at \mine\fultter\flutter
    • Framework revision 2ae34518b8 (2 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at \mine\install\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = \mine\install\AndroidSDK
    • Java binary at: \mine\install\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at \mine\install\Android Studio
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G960F (mobile) • 231173e32f027ece • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by darshankawar** [comment]
Hi @bajajsahil,
Please provide a minimal complete reproducible code sample that shows the issue, along with `pubspec.yaml`.
Thanks.

**Comment by bajajsahil** [comment]
Hi @darshankawar 

Well, I have mentioned that it is also happening in the flutter sample [place_tracker](https://github.com/flutter/samples/tree/master/place_tracker) app so I didn't add the code. Please find the below minimal code extracted from the place tracker app only. The issue is reproducible when we just switch between apps on the real mobile. 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(PlaceMap(center: const LatLng(45.521563, -122.677433)));
}

class PlaceMap extends StatefulWidget {
  final LatLng center;

  const PlaceMap({
    Key key,
    this.center,
  }) : super(key: key);

  @override
  PlaceMapState createState() => PlaceMapState();
}

class PlaceMapState extends State<PlaceMap> {
  Completer<GoogleMapController> mapController = Completer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: GoogleMap(
            onMapCreated: (controller) => mapController.complete(controller),
            initialCameraPosition: CameraPosition(
              target: widget.center,
              zoom: 11.0,
            ),
            markers: {
              Marker(
                markerId: MarkerId('center'),
                position: widget.center,
                infoWindow: InfoWindow(
                  title: 'My Place',
                ),
              )
            },
          ),
        ),
      ),
    );
  }
}
```

```
name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.30
  provider: ^4.0.0
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  assets:
    - assets/

  uses-material-design: true
```

Thanks

**Comment by darshankawar** [comment]
Hi @bajajsahil, thanks for the code sample.
I tried the same on latest stable (1.20.2) using Android 8.1.0 device but didn't see the white / blank screen while switching between apps, unless I missed any step.

[64568.mp4.zip](https://github.com/flutter/flutter/files/5134316/64568.mp4.zip)

Are there any specific steps to replicate ? A video / gif would be helpful.
Thanks.

**Comment by bajajsahil** [comment]
hi @darshankawar 

PFB videos with minimal code and place tracker app.

[videos.zip](https://github.com/flutter/flutter/files/5135747/videos.zip)

If you notice in place tracker app video, when I am tapping on the zoom in or zoom out icon then only map reappears.

**Comment by darshankawar** [comment]
@bajajsahil thanks for the videos.
Strange that when I tried the same steps on Samsung S10+, I don't see the issue at all.

[64568.mp4 2.zip](https://github.com/flutter/flutter/files/5136062/64568.mp4.2.zip)

It seems to be only happening on specific device you have. Can you by any chance try on another device than S9 and see if you still experience the same issue ? Just trying to see if it's a certain device specific issue. As I tried on Samsung Galaxy A2Core, I didn't see the issue there. 
Thanks.

**Comment by bajajsahil** [comment]
Hi @darshankawar, Did you check with the place tracker app also?

Thanks.

**Comment by bajajsahil** [comment]
Hey @darshankawar, Also, try opening the camera while switching app.

**Comment by nqnhat14** [comment]
I also have the same issue, tried on Google Pixel 3 XL, Android 10. Please try to switch between apps multiple times then you can see the white screen with Google logo on the bottom left corner.

**Comment by bajajsahil** [comment]
@nqnhat14 Just in case if you need a workaround, I have provided it here - https://github.com/flutter/samples/issues/532#issuecomment-679985582

**Comment by darshankawar** [comment]
@bajajsahil,
Yes I tried the official `place_tracker` from samples on Samsung S10+, but don't see the issue. Also tried opening camera while switching app, but same.

[64568.mp4.zip](https://github.com/flutter/flutter/files/5140594/64568.mp4.zip)

Were you able to test it on different device at your end ?
Thanks.

**Comment by bajajsahil** [comment]
Hi @darshankawar, In the video you attached, you are opening the gallery app not the camera app. Can you please try by opening the camera app? 

Just try minimizing the app, open camera, switch to place tracker app like this back and forth

No, I didn't get the chance to test on other devices. But we have one more user @nqnhat14 facing a similar issue with Google Pixel3 XL.

**Comment by darshankawar** [comment]
@bajajsahil Just now tried by switching between place tracker and camera app and saw no issues.

[64568.mp4 2.zip](https://github.com/flutter/flutter/files/5142205/64568.mp4.2.zip)

**Comment by bajajsahil** [comment]
Hi @darshankawar Check this out.

[64568_Reproducible.zip](https://github.com/flutter/flutter/files/5143531/64568_Reproducible.zip)

With camera app it is always reproducible and with other apps it is intermittent. Before opening the camera app and after closing the camera app, it worked fine but when switching with the camera opened it broke.

**Comment by darshankawar** [comment]
I am unable to replicate this issue on the devices I have (Samsung S10+ and Galaxy A2Core), but per OP, he's consistently able to replicate the issue on Samsung S9, hence, I am keeping this issue open for further analysis.

**Comment by nkulic** [comment]
Same happening on Samsung Galaxy S10. Switching to another app and returning to flutter app where google maps was previously displayed shows blank map until map is manually rotated. Manual rotation of map while google maps is bank seems to cause frame refresh which then displays map correctly.

**Comment by GaneshvrBhat** [comment]
I have run into similar problem with google maps flutter, here are details,
App loads google maps and all related functionality perfectly when built on mocbook intel chip, however if its built I=on **MacBook m1 chip / arm_64** then map doesn't load only google logo is displayed.

**Comment by Sam-MNDL** [comment]
Same problem for me, someone find a solution?

**Comment by neiljaywarner** [comment]
we have similar issue

**Comment by c0c4i** [comment]
This is not device specific, I have this issue on the majority of my android devices, I can't let people have this issue so frequenly

**Comment by neiljaywarner** [comment]
Android surface view helped us

....sent from my phone

**Comment by darshankawar** [comment]
@bajajsahil Revisiting this issue to verify if it still persists on latest stable version and plugin version, I tried original code sample you shared and also another demo code and ran on Samsung S10 running Android 12 and Pixel XL emulator running Android 13 and by switching between the app and another app (ex: camera) from recent apps, but was unable to replicate the behavior that is described in this issue.


https://github.com/flutter/flutter/assets/67046386/e191b0c8-b992-499a-a079-5d98aa8492b9

If you by chance can replicate this still using latest version, please provide us an update so we can update the issue status. Also, anyone in this thread facing this issue, please check if you are still able to replicate this behavior or not on latest versions.
