### ISSUE TITLE
[device_info] More clearly define scope

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#64569]
There has been interest in adding desktop support to `device_info` (see https://github.com/flutter/flutter/issues/39674, https://github.com/flutter/plugins/pull/2942#issuecomment-680119751); it's not really clear to me how we would evaluate whether to accept or reject any given information being added there; there are obvious easy things (e.g., exact OS version), and all kinds of things that obviously wouldn't belong, but a huge grey area that could arguably be "device" information, but would potentially be too niche. I think we should more clearly articulate the intended scope of `device_info` somewhere in the README or docs.

It would also be nice to take a step back as we extend it to new platforms and consider extracting a base class for the info structure. There are many reasonable things that could be included that would be common across at least all of desktop, and maybe all devices, and having a few common abstractions for those things would be good.

**Comment by ditman** [comment]
// Subscribing, this is very relevant for any web implementation later.

**Comment by yash1200** [comment]
I think we should use [neofetch](https://github.com/dylanaraps/neofetch) data model for defining base class for the info structure. Atleast it would work on all linux distros and macos.

**Comment by stuartmorgan** [comment]
The screenshots of the default information display are a clear illustration of the problem, IMO. Taking a few examples:

- `OS` Clearly yes
- `Resolution` It's a property of the device, but it's not included on iOS or Android currently. (I assume that's because it's available other ways, as it will be on desktop via screen APIs in the framework, but that's a guess on my part; we should have an articulation of why it's not there.)
- `Memory` Similar to resolution, except that I have no idea why it's not there.
- `Uptime` Not really a property of the device, and utility seems niche; I would personally say no
- `Terminal Font` Clearly no

**Comment by yash1200** [comment]
I think, we just need to specify the base class for all desktop platforms (linux, macos and windows) all together and not include Android and iOS in it.

**Comment by stuartmorgan** [comment]
I think you misunderstood my references to iOS and Android in my last comment. I'm not saying it's technically difficult to include things like resolution and memory because they aren't there for iOS and Android, I'm saying that we need clearly articulated scope criteria for what should be included in this plugin, in general (and that whatever those criteria are, they should almost certainly give the same answer for whether or not to include very general concepts like memory and screen resolution for any platform).

**Comment by yash1200** [comment]
I am sorry for that misunderstanding. I've made a Google docs for it. Here's the [link](https://docs.google.com/document/d/1wWrBNuviQGe5izdRuG67uiq9PL796ryD53p5-e5npkY/edit?usp=sharing). This will help in maintaining the information. I have added some things for linux and windows. Please review it. (You can edit if you want to make some changes in it.)

**Comment by stuartmorgan** [comment]
@yash1200 Articulating the desired scope of the plugin at a higher level is a precondition of reviewing specific proposals for what fields it should have on desktop platforms; thus this issue.

**Comment by stuartmorgan** [comment]
@matthew-carroll you're listed as the code owner for this plugin; thoughts on the above?

**Comment by stuartmorgan** [comment]
Please read [my comment above](https://github.com/flutter/flutter/issues/64569#issuecomment-680194017); this issue is not about discussing technical difficulty, it's about clearly defining and articulating the **intended scope** of the plugin.

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
