### ISSUE TITLE
Add an option to skip SDK git hash check for development

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#64574]
## Use case

I want the ability to build and deploy a custom Flutter engine with my local changes to Dart SDK for Fuchsia OS.  Without this
change, it is impossible to test such an engine on Fuchsia, since git hashes will *always* be mismatched (I am always grafting new changes on top of HEAD).

## Proposal

Add a build flag that unsets `dart_version_git_info` at build time.

**Comment by filmil** [comment]
I'm working on this, please assign me to it. Thanks!

**Comment by pedromassangocode** [comment]
Hi @filmil 
Can you confirm that https://github.com/flutter/engine/pull/20748 fixed this issue?

**Comment by filmil** [comment]
Confirmed.

I was able to build a flutter engine that I could deploy using this approach.

**Comment by pedromassangocode** [comment]
Thanks
