### ISSUE TITLE
Debug-only Crash when running flutter run on default app

### ISSUE THREAD

**Issue by mswift42** [flutter/flutter#6457]
## Steps to Reproduce

When creating a new flutter app and running it, I get this error message:

> > flutter run
> > Launching loader on P4502...
> > --------- beginning of /dev/log/system
> > E/ActivityManager: WMS runs the animation too long
> > W/ActivityManager: Launch timeout has expired, giving up wake lock!
> > W/ActivityManager: Force removing ActivityRecord{424fd858 u0 com.yourcompany.fln/org.domokit.sky.shell.SkyActivity t107}: app died, no saved state
> > Exception from flutter run: FormatException: Bad UTF-8 encoding 0xff
> > dart:isolate  _RawReceivePortImpl._handleMessage
> 
> Exception from flutter run: FormatException: Bad UTF-8 encoding 0xb7
> dart:isolate  _RawReceivePortImpl._handleMessage
> 
> Exception from flutter run: FormatException: Bad UTF-8 encoding 0x80
> dart:isolate  _RawReceivePortImpl._handleMessage
> 
> W/ActivityManager: No content provider found for permission revoke: file:///data/local/tmp/app.apk
> W/ActivityManager: No content provider found for permission revoke: file:///data/local/tmp/app.apk
> W/ActivityManager: Force removing ActivityRecord{41cbbf08 u0 com.yourcompany.fln/org.domokit.sky.shell.SkyActivity t108}: app died, no saved state
> W/System.err: java.lang.NullPointerException
> W/System.err:     at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
> W/System.err:     at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
> W/System.err:     at android.os.Binder.execTransact(Binder.java:404)
> W/System.err:     at dalvik.system.NativeStart.run(Native Method)
> Timed out while waiting for a debug connection.
> Error launching DevFS loader on P4502.
## Flutter Doctor

> flutter doctor
> [✓] Flutter (on Linux, channel master)
>     • Flutter at /home/martin/github/flutter
>     • Framework revision e837e16378 (5 hours ago), 2016-10-20 21:30:27
>     • Engine revision 0aea498f61
>     • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/martin/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[-] IntelliJ IDEA Community Edition (version 15)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[-] IntelliJ WebStorm (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[-] IntelliJ IDEA Community Edition (version 2016.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[-] IntelliJ WebStorm (version 2016.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • P4502 • Medion • android-arm

Output of getprop is [here](https://gist.github.com/mswift42/7c22266c5b46c503df6fe5c1540244f8)

**Comment by eseidelGoogle** [comment]
It's possible https://github.com/flutter/flutter/issues/5738 or https://github.com/flutter/flutter/issues/6280 are related.  They both have the bad encoding message in the output.

I don't see anything indicative in the `flutter run` output unfortunately.

**Comment by eseidelGoogle** [comment]
So re-reading the log, I suspect the bad encodings are a red herring.  It looks like the app is crashing on your Android device.

I believe this is the device:
http://www.pcadvisor.co.uk/review/budget-smartphones/aldis-medion-life-p4502-budget-smartphone-review-3591554/

And it's got a Mali 400 GPU, which should be well supported (it's very common).  Not why the crash.

Its also possible this was just a bad revision of flutter and a `flutter upgrade` will solve things.

**Comment by mswift42** [comment]
Well, It works flawlessly with my Moto G4, but the P4502 now only shows me this:

```
Building APK in debug mode (android-arm)...         5923ms
Installing build/app.apk...                         4159ms
Exception from flutter run: FormatException: Overlong encoding of 0x0
dart:isolate  _RawReceivePortImpl._handleMessage

Timed out while waiting for a debug connection.
Error launching DevFS loader on P4502.

```

**Comment by eseidelGoogle** [comment]
I might try `flutter run --release` vs `flutter run` (--debug is default) and see if one works and the other doesn't.  I believe the Flutter binary is crashing on your device, but I don't see any explanation of such in the logs.

One might also try `adb logcat -c` (to clear the device logs) and then try running flutter and then `adb logcat` to see the logs.  `flutter run` and `flutter logs` just wrap adb (including logcat), but it's not clear why we aren't seeing reports of the app crashing on the device (which it seems to be doing).

**Comment by mswift42** [comment]
It "works" with --release. See attached screenshot

**Comment by eseidelGoogle** [comment]
The screenshot didn't seem to come through.

**Comment by mswift42** [comment]
I updated my previous comment to include the screenshot.

Here is the output of the command flutter run --release:

...
$ flutter run --release
Building APK in release mode (android-arm-release)...      
Warning! Signing the APK using the debug keystore.
You will need a real keystore to distribute your application.
Installing build/app.apk...                         5589ms
Running lib/main.dart on P4502...

To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
Exception from flutter run: FormatException: Overlong encoding of 0x0
dart:isolate  _RawReceivePortImpl._handleMessage

I/flutter (15345): [INFO:SkFontMgr_android_parser.cpp(608)] [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
I/flutter (15345): 
I/flutter (15345): [INFO:SkFontMgr_android_parser.cpp(608)] [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
I/flutter (15345): 
I/flutter (15345): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15345): The following ArgumentError was thrown during performLayout():
I/flutter (15345): Invalid argument(s): 0.0
I/flutter (15345): When the exception was thrown, this was the stack:
I/flutter (15345): #0      _Double.clamp (dart:core-patch/double.dart)
I/flutter (15345): #1      TextPainter.layout (package:flutter/src/painting/text_painter.dart)
I/flutter (15345): #2      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart)
I/flutter (15345): #3      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #4      _ToolbarLayout.performLayout (package:flutter/src/material/app_bar.dart)
I/flutter (15345): #5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter (15345): #6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter (15345): #7      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #8      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter (15345): #9      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #11     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #12     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter (15345): #13     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #14     RenderConstrainedOverflowBox.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter (15345): #15     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #16     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #17     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #18     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter (15345): #19     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #20     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #21     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #23     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #25     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #26     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart)
I/flutter (15345): #27     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #28     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #29     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #30     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart)
I/flutter (15345): #31     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter (15345): #32     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter (15345): #33     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #35     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #37     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #39     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #41     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #43     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #45     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #46     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #47     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #49     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #50     RenderStack.performLayout (package:flutter/src/rendering/stack.dart)
I/flutter (15345): #51     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #52     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #53     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #54     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #55     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #56     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #57     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #58     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter (15345): #59     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #60     RenderView.performLayout (package:flutter/src/rendering/view.dart)
I/flutter (15345): #61     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart)
I/flutter (15345): #62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart)
I/flutter (15345): #63     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart)
I/flutter (15345): #64     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart)
I/flutter (15345): #65     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart)
I/flutter (15345): #66     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart)
I/flutter (15345): #67     main (file:///home/martin/github/flp4502/lib/main.dart)
I/flutter (15345): #68     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart)
I/flutter (15345): #69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)
I/flutter (15345): The following RenderObject was being processed when the exception was fired:
I/flutter (15345):   RenderParagraph relayoutBoundary=up1 NEEDS-LAYOUT
I/flutter (15345): This RenderObject has no descendants.
I/flutter (15345): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15345): Another exception was thrown: NoSuchMethodError: The getter 'height' was called on null.
Exception from flutter run: FormatException: Bad UTF-8 encoding 0xb9
dart:isolate  _RawReceivePortImpl._handleMessage

Exception from flutter run: FormatException: Bad UTF-8 encoding 0xa1
dart:isolate  _RawReceivePortImpl._handleMessage

Exception from flutter run: FormatException: Bad UTF-8 encoding 0xa1
dart:isolate  _RawReceivePortImpl._handleMessage

Exception from flutter run: FormatException: Overlong encoding of 0x0
dart:isolate  _RawReceivePortImpl._handleMessage
...

**Comment by eseidelGoogle** [comment]
This may be improved by https://github.com/flutter/flutter/commit/d3dc5d7ca9a190e58593311705724c1e751868be which was a fix made for a similar crash on Pixel phones.  There is a bit more information we need to gather about the CPU type of this phone, I can look up instructions for that later.  FYI @rmacnak-google

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this.  We definitely have seen various strange crashes which show up as encoding errors (which is likely a red herring).  The tool, framework and engine have changed a ton since november.

Speculatively closing.  *Please* feel encouraged to re-open or file a new bug if you're still having any trouble?

**Comment by nanowang** [comment]
Issue re-occurred on Pixel

## command

flutter run

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xff (at offset 10947)

```
dart:isolate  _RawReceivePortImpl._handleMessage
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/nano/workspace/vendor/sdk/flutter
    • Framework revision e8a6df4df9 (32 hours ago), 2017-03-14 20:20:54
    • Engine revision b97103b441
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/nano/workspace/vendor/sdk/android-sdk-macosx
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ Python installation missing module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
      brew update
      brew install --HEAD libimobiledevice
      brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
      brew update
      brew install ios-deploy
    • CocoaPods version 1.1.1

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • Pixel • FA6B40303026 • android-arm • Android 7.1.1 (API 25)
```

**Comment by nirwannursabda** [comment]
_flutter clean_ fix this issue. for future reference
