### ISSUE TITLE
How to Get Verified Blue tick in flutter

### ISSUE THREAD

**Issue by manu223** [flutter/flutter#64571]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
Hi @manu223 
can you please provide your `flutter run -v`, `flutter doctor -v`, and complete minimal reproduction code?
Thanks.

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
