### ISSUE TITLE
Fuchsia SDK autoroller is paused

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64606]
I reverted the most recent roll and paused the auto roller for a failing time zone unit test:

https://github.com/flutter/engine/pull/20770

```
[ RUN      ] FuchsiaShellTest.LocaltimesVaryOnTimezoneChanges
../../flutter/shell/common/shell_fuchsia_unittests.cc:188: Failure
Expected equality of these values:
  initial_dart_isolate_time_str
    Which is: "2020-08-26 02"
  final_dart_isolate_time_str
    Which is: "2020-08-25 20"
Local time in Europe/Amsterdam rounded down to nearest hour read twiceshould be the same but this test says they are not; time zone handling in the dart VM is likely broken.
[  FAILED  ] FuchsiaShellTest.LocaltimesVaryOnTimezoneChanges (352 **ms)**
```

Possibly related:

https://github.com/dart-lang/sdk/commit/0e1d32f10c

@kf6gpe @iskakaushik @arbreng

**Comment by zanderso** [comment]
Even though the test didn't start failing until the Fuchsia SDK roll, the test continues to fail even after reverting the roll.

**Comment by zanderso** [comment]
https://github.com/dart-lang/sdk/commit/0e1d32f10c was reverted, and rolled into the engine, but the test is still failing as above. Leaving P0 because the engine tree is closed on this.

**Comment by filmil** [comment]
Well, on the upside, the test did what it was designed to do -- which is to fail if setting time fails...

**Comment by iskakaushik** [comment]
This behavior is very likely broken prior to the test being added, I filed: https://github.com/dart-lang/sdk/issues/43199 to fix the underlying problem. I will revert the test to enable the autorollers.
