### ISSUE TITLE
InteractiveViewer should support aligning sized content when 'constrained' is false

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#64604]
## Use case

I have a large image that the user can drag around within a smaller box using the new InteractiveViewer widget. I have set `constrained` to false. I'm not seeing any way to set the initial alignment of the contents -- currently the image is always forced to the top-left. A requirement of this use case is that the image starts center-aligned. Using a Transform widget is insufficient because it won't place nicely with the boundary margin of the InteractiveViewer.

## Proposal

I'm not sure what the API should look like, but we need some way to control how the contents of the InteractiveViewer are initially positioned when the child is larger than the parent.

This might be as simple as passing an `Alignment` into the InteractiveViewer which can be used on the inner OverflowBox.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
This may be a duplicate of https://github.com/flutter/flutter/issues/58997, take a look at the discussion there.  I'm thinking we should add a BoxFit parameter to handle things like this.

Another thing to look at in the meantime is my [flutter-go](https://github.com/justinmc/flutter-go) example.  It's not exactly what you want, but it might give you some ideas.

Last thing to try, it should definitely be possible to center the child by actually setting the translation of the matrix with TransformationController.  You'll have to know the size of the parent and child and do the math yourself.

**Comment by doppio** [comment]
You're right, this appears to be a duplicate. Thanks for the ideas in the meantime!

**Comment by justinmc** [comment]
No problem, I'll try to follow up on https://github.com/flutter/flutter/issues/58997 soon.
