### ISSUE TITLE
Fluent engine cannot compile

### ISSUE THREAD

**Issue by yohyow** [flutter/flutter#64612]
When I execute the following command:

~/engine/src#:./flutter/tools/gn --target-os linux --linux-cpu arm64 --runtime-mode debug

Failed, as shown below:

Generating GN files in: out/linux_debug_arm64
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /root/engine/src/out/linux_debug_arm64/
Command: python /root/engine/src/build/config/linux/pkg-config.py freetype2
Returned 1.
stderr:

Could not run pkg-config.

See //build/config/linux/BUILD.gn:30:1: whence it was called.
pkg_config("freetype2") {
^------------------------
See //build/config/BUILDCONFIG.gn:352:33: which caused the file to be included.
  _native_compiler_configs += [ "//build/config/linux:sdk" ]
                                ^-------------------------

Please help! Ths.

**Comment by stuartmorgan** [comment]
> --target-os linux --linux-cpu arm64

That build configuration isn't fully supported yet. Notably, there isn't a sysroot for it, so you either need to provide one yourself, or install all of the necessary packages (such as, in this instance, freetype2 development libraries and headers).
