### ISSUE TITLE
Missing newline in flutter run help

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6461]
"Specify a file to write the process id to.You can send SIGUSR1 to trigger a hot reload and SIGUSR2 to trigger a full restart."

**Comment by Hixie** [comment]
The output now has excessive indentation:
```
    --[no-]hot                  Run with support for hot reloading.
                                (defaults to on)

    --pid-file                                                Specify a file to write the process id to.
                                                              You can send SIGUSR1 to trigger a hot reload
                                                              and SIGUSR2 to trigger a full restart.

    --benchmark                 
```

**Comment by warent** [comment]
Good catch! I was pretty hasty in trying to fix that. Anyway, this should be default behavior for all help text rather than special casing. I'm trying to think of a good way to do this. Looks related to dart-lang/args#41

**Comment by warent** [comment]
Would it be worth implementing an ArgParser wrapper for something this trivial?

**Comment by Hixie** [comment]
I think we should fix the indentation in the flutter tool first (by switching from `'''` to `'`), but yes, eventually we should fix this generally, either by fixing https://github.com/dart-lang/args/issues/41 (that's the ideal solution) or by wrapping that package ourselves (if for some reason we can't get the args package fixed).
