### ISSUE TITLE
Consider making lerpDouble parameters non-null

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#64617]
In `dart:ui`, `lerpDouble` currently has the following signature: `double? lerpDouble(num? a, num? b, double t)`.

Post non-null by default, we should consider strengthening the parameter contract to require them to be non-null. While this would be a breaking change, it seems likely that the framework either meets this guarantee or can provide it without a framework breaking change.

**Comment by Hixie** [comment]
I would imagine there's lots of cases where we pass through nulls. Lerping in general is frequently done from a null to a non-null.

**Comment by jonahwilliams** [comment]
lerping from a null sort of makes sense, but it is annoying that it returns a nullable type now that it cannot be ignored

**Comment by cbracken** [comment]
I may do a quick survey to see where are all the cases where we (potentially) lerp from null to null to see how feasible it would be to eliminate that case and just always default nulls to 0.0.

**Comment by cbracken** [comment]
Closing this since the function is now specified a lot better than it was. It's still not ideal, but enough people rely on this behaviour that it would be too much of a breaking change, I think.

**Comment by spkersten** [comment]
Could it be defined with a type parameters, so it can be both nullable and non-nullable like this:
```
T lerpDouble<T extends double?>(T a, T b, double t) {
  if (a == null) return b;
  if (b == null) return a;
  return a + (b - a) * t as T;
}
```
