### ISSUE TITLE
What does the command `flutter build ios` do if  we can get the release-ipa with Xcode archive?

### ISSUE THREAD

**Issue by ShaowenSu** [flutter/flutter#64626]
According to the guide on flutter.dev about [create-a-build-archive](https://flutter.dev/docs/deployment/ios#create-a-build-archive), we need to run `flutter build ios` before we use Xcode to archive and get the IPA for AppStore/TestFlight.

But is it necessary to do such job? It seems that I use Xcode to archive without running the flutter build command, I also get the release-IPA correctly. So, what's the different if I run the command before archive?

For example, if I use `flutter build ios --bundle-sksl-path flutter_01.sksl.json` to build the app with **SkSL warm-up**, then use Xcode to archive afterward, is the IPA summiting to AppStore/TestFlight including the SkSL warm-up already? Or I should use the runner.app in folder `my_project\build\ios\iphoneos\` and compress it to IPA myself?

@liyuqian sorry to disturb you, since I knew you are following the SkSL issues. Thank you for your jobs.

Thank you for any suggestion.

**Comment by TahaTesser** [comment]
Adding documentation, since this could be better explained https://flutter.dev/docs/deployment/ios#create-a-build-archive

**Comment by liyuqian** [comment]
Loop in our mobile and tool experts @xster @jonahwilliams

**Comment by jonahwilliams** [comment]
When you archive in xcode it users the last build `flutter build ios` configuration.

I don't really understand why we don't support archiving from the CLI. The xcode UI is confusing and I don't like it, I can't be the only one.

**Comment by jonahwilliams** [comment]
FWIW here is a draft of `flutter build ipa`: https://github.com/flutter/flutter/pull/64683

There are some potential complexities with choosing how to codesign, as I haven't figured out how to generate fake/unsigned IPAs yet.

**Comment by ShaowenSu** [comment]
> When you archive in xcode it uses the last build `flutter build ios` configuration.
> 
> I don't really understand why we don't support archiving from the CLI. The xcode UI is confusing and I don't like it, I can't be the only one.

Yes, build and archive with different tools confuses me, and I knew that some people are also suffering from the same problem, similar question are asked on Stackoverflow but no one answer.

Any way, thank you for your explanation, may be we can add this explanation to https://flutter.dev/docs/deployment/ios#create-a-build-archive

**Comment by szotp** [comment]
> as I haven't figured out how to generate fake/unsigned IPAs yet.
What do you need unsigned ipas for?

For more advanced use cases it would be better to have a simpler command that just prepares the flutter variables/configuration, without touching xcode at all. That's because many companies already have standarized workflow for iOS apps: for example, mine uses fastlane, custom derivedDataPath and manual enterprise signing.

**Comment by jonahwilliams** [comment]
Thats a good idea @szotp , what would you call that command though? flutter build ios-config?

**Comment by szotp** [comment]
Yes, sounds good.

**Comment by jmagman** [comment]
Some more info in https://github.com/flutter/flutter/issues/45400#issuecomment-558306972.

**Comment by jmagman** [comment]
Created https://github.com/flutter/flutter/issues/66619.

**Comment by khandilist** [comment]
Also, does it really work for obfuscating during the build proses when we run this command:
flutter build ios --obfuscate --split-debug-info=/<project-name>/<directory>
Before archiving through Xcode?
Is there any way to confirm?
I tried to delete build/ios folder that created from "flutter build ios" and still can archive from Xcode without any errors.

**Comment by jmagman** [comment]
@khandilist Running `flutter build ios` will update Xcode build settings, some of which get passed into Flutter, like `SPLIT_DEBUG_INFO` and `DART_OBFUSCATION` in your example.  You can run 
```
$ cd ios
$ xcrun xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Flutter -configuration Release
```
if you're curious.

`flutter build ios --config-only --obfuscate --split-debug-info=//` would update the build settings (`--config-only` is available as of 1.22.0-12.0.pre, currently on the beta channel, leave it off if you're on stable).

You can also run `flutter build xcarchive --obfuscate --split-debug-info=//` to directly generate the archive, and skip `flutter build ios` altogether.  That command is only available on the beta channel.  Docs will be updated once it hits stable.

**Comment by sooxt98** [comment]
@jmagman Hi, i just tried `flutter build ios --config-only` it's abit slow for just updating the build number & version in xcode. It's better to bind this feature to `flutter pub get` when we save/update the pubspec

**Comment by jmagman** [comment]
@sooxt98 `flutter pub get` wouldn't be able to update build settings like `FLUTTER_TARGET`, `TREE_SHAKE_ICONS`, `DART_DEFINES`, etc derived from flags passed into `flutter build`/`run`/`xcarchive`.  The tool could be changed to just update `FLUTTER_BUILD_NAME` and `FLUTTER_BUILD_NUMBER` on a `pub get` but right now they are all updated at the same time.

**Comment by jmagman** [comment]
In light of `flutter build ios--config-only` and `flutter build xcarchive`/`ipa` the last thing left to do it document the way they work.  I'm going to close this issue in favor of https://github.com/flutter/website/issues/4852.

Please feel free to create follow-up issues if you have feature requests to make this flow more usable, or if you have additional documentation requests.
