### ISSUE TITLE
problem to get data from firestore. generate an error 

### ISSUE THREAD

**Issue by muneeb900** [flutter/flutter#64624]
QuestionModel  getQuestionModelFromDatasnapshot(
      DocumentSnapshot questionSnapshot) {
    QuestionModel questionModel = new QuestionModel();

    questionModel.question = questionSnapshot.data**['question'];**

    /// shuffling the options
    List<String> options = [
      questionSnapshot.data**['option1'],**
      questionSnapshot.data**['option2'],**
      questionSnapshot.data**['option3'],**
      questionSnapshot.data**['option4'],**
    ];
    options.shuffle();

    questionModel.option1 = options[0];
    questionModel.option2 = options[1];
    questionModel.option3 = options[2];
    questionModel.option4 = options[3];
    questionModel.correctOption = questionSnapshot.data**['correctoption'];**
    questionModel.answered = false;

    print(questionModel.correctOption.toLowerCase());

    return questionModel;
  }
Error Generate:
Closure call with mismatched arguments: function '[]'
Receiver: Closure: () => Map<String, dynamic> from Function 'data':.
Tried calling: []("quizImgUrl")
Found: []() => Map<String, dynamic>

**Comment by hamdikahloun** [comment]
Hi @muneeb900 

Can you provide more details and Logs:

- flutter doctor -v

- flutter run -v

- minimal complete reproducible code sample

**Comment by markusaksli-nc** [comment]
Added wait label for what @hamdikahloun asked

Cc myself

**Comment by muneeb900** [comment]
problem solved

**Comment by Sasha1189** [comment]
hi @muneeb900 

how?

**Comment by Testapp-101** [comment]
> Error Generate:
> Closure call with mismatched arguments: function '[]'
> Receiver: Closure: () => Map<String, dynamic> from Function 'data':.
> Tried calling:
> Found: => Map<String, dynamic>

Can you please tell me how you solved this?

**Comment by reema-pandya** [comment]
> problem solved

I'm getting the same error.
Can you please share your solution?

**Comment by Testapp-101** [comment]
Use get() isntrad of just get

**Comment by santosh2055** [comment]
Please share the solution in details. @Testapp

**Comment by Testapp-101** [comment]
If you are using get to get some value use get() instead of get to retrieve
that value
