### ISSUE TITLE
Unable to run gradlew unless gradle version changed from 5.6.2 to 6.3 

### ISSUE THREAD

**Issue by Germain-L** [flutter/flutter#64630]
I'm on flutter 1.22 (i remember having the issue a while ago on some other versions), i have to manually change the gradle version in `\android\gradle\wrapper\gradle-wrapper.properties` from 5.6.2 to 6.3 in order to be able to use gradlew and java sdk 14

## Steps to Reproduce

On windows

1. Install java sdk 14 and add <path to java>\bin and JAVA_HOME variables
2. Create a new flutter project
3. run android\gradlew signingReport

## Logs

```
C:\projects\test_project>android\gradlew signingReport
Starting a Gradle Daemon, 1 busy and 5 incompatible and 2 stopped Daemons could not be reused, use --status for details
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

[...]

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by hamdikahloun** [comment]
Hi @Germain-L 
 Java SDK 14 support min Gradle 6.4.
Change the gradle version in \android\gradle\wrapper\gradle-wrapper.properties from 5.6.2 to **_6.4.1_**

**Comment by TahaTesser** [comment]
Hi @Germain-L
`android\gradlew signingReport` isn't not related to flutter. Also, you should probably use Java 1.8 that comes with Android Setup to not have issues.  

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by joshpetit** [comment]
Is the Gradle wrapper version not set by flutter? If so which build tool needs to be updated to make it default to 6.3 or higher? Every time I create a new project I have to manually modify that so knowing what might be the issue would be helpful, thanks!

**Comment by hamdikahloun** [comment]
@joshpetit 
Check this file 
`flutter/packages/flutter_tools/templates/app/android.tmpl/gradle/wrapper/gradle-wrapper.properties`

**Comment by joshpetit** [comment]
@hamdikahloun Oh, I see. It was updated but just hasn't reached the [stable](https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/templates/app/android.tmpl/gradle/wrapper/gradle-wrapper.properties) branch yet. Thanks.
