### ISSUE TITLE
Guidance on keyboard shortcuts for Desktop/Web

### ISSUE THREAD

**Issue by Jonas-Sander** [flutter/flutter#64634]
I want to implement custom keyboard shortcuts for desktop and web in our flutter web.  

For example: 
We are building a school organization app. 
If a user is on the homework page they should be able to create a new homework via `CTRL + N` instead of clicking an extended FAB.

**The problem is that it's even hard to find out if keyboard shortcuts are supported yet**.
Much less how to implement them if they are supported.

Google searches for flutter keyboard shortcuts are often referring to keyboard shortcuts for flutter IDEs.  
There is no (at least I couldn't directly find one) article about keyboard shortcuts.

What I could find:
- https://github.com/flutter/flutter/issues/31946 "Keyboard shortcuts and actions should be supported." (Closed)
Not much context, it seems like this is only for standard keyboard shortcuts like TAB, ENTER, CTRL-Z and meant as something which helps the Flutter to natively support these. Nothing for me as a developer for my own app to use (from what I understand).
- A Stackoverflow question with no answers: ["How to handle keyboard shortcuts"](https://stackoverflow.com/questions/61960260/how-to-handle-keyboard-shortcuts)
- The [`Shortcuts`](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html)/[`ShortcutManager`](https://api.flutter.dev/flutter/widgets/ShortcutManager-class.html) Widgets with **sub-par documentation**.
There is no context on why these classes exist, what problems they solve and what problems they do not solve.
There are no examples.
I have no idea if these widgets help me or not with my problem.
- The [`keyboard_shortcuts`](https://pub.dev/packages/keyboard_shortcuts) package.
I haven't used it yet, it seems like something that could work. Nonetheless this is a package by a single person for a universal problem which in my opinion should be solved by Flutter.

So my points are that there should be Guidance if keyboard shortcuts are already supported by Flutter.  
If they aren't I would wish for a single ticket for keyboard shortcuts for web and desktop that is easily searchable and where the current state and the the next steps are documented.
If they are there should be documentation on how to implement them with examples.

**Comment by vitthal-inani** [comment]
I suggest you use this https://pub.dev/packages/keyboard_shortcuts or look into this for inspiration.

**Comment by vitthal-inani** [comment]
> * The [`keyboard_shortcuts`](https://pub.dev/packages/keyboard_shortcuts) package.
>   I haven't used it yet, it seems like something that could work. Nonetheless this is a package by a single person for a universal problem which in my opinion should be solved by Flutter.

This should give you a codebase for your own custom implementation I guess.

**Comment by gspencergoog** [comment]
@JSANL Thanks for filing this issue. Flutter definitely supports keyboard shortcuts.  Buttons and other controls support pressing space/enter to activate, and tab to move focus.

I agree with you though, there's not sufficient documentation. We'll improve the documentation and add some more samples.

In the meantime, The basic idea is that the `Shortcuts` widget maps key events to an `Intent`, and the `Actions` widget maps an `Intent` to an `Action`.  You implement the `Action` class, or you can use a `CallbackAction` to wrap an existing function.

You can use the [`FocusableActionDetector`](https://api.flutter.dev/flutter/widgets/FocusableActionDetector-class.html) class to combine all of these into one wrapper (it combines the Shortcuts, Actions, and mouse hover into one widget for convenience).  It also has an example and slightly better documentation.

For your specific case, you could do something like this this dartpad example (but I used Alt-N instead of Ctrl-N, because Ctrl-N is a browser shortcut):
https://dartpad.dartlang.org/a824f267aac76bbd063811f83bda9a13

**Comment by csells** [comment]
@gspencergoog @sfshaza2 is there more we should be rolling into our docs here?

**Comment by gspencergoog** [comment]
We can always add more documentation. I have added more examples to Actions and Shortcuts. Is it enough to close this issue? Probably not.  I probably need to spend some more time on the docs and add more prose there, in addition to the examples.

**Comment by PavelPZ** [comment]
I spent several hours researching how to use **default keyboard shortcuts** for ListView (PgUp, PgDn, ...). Unfortunately without success. 

See official explanation: 
- https://github.com/flutter/flutter/issues/76918#issuecomment-788342392
- https://github.com/flutter/flutter/issues/76918#issuecomment-789025283

This issue is part of **Windows Next** project, I would therefore like to link it to similar   https://github.com/flutter/flutter/issues/76918.

**Comment by esDotDev** [comment]
I think the main issue, documentation wise, is short of finding this in the source code, how is any desktop developer supposed to know this exists? 

Probably what's needed is some central location, geared at Desktop/Web developers, explaining all the built in helpers that exist in the framework at any point in time:
* FocusTraversalGroups
* Shortcuts / ShortcutManager
* MouseRegion
* PopUp / ContextMenu
* Scrollbar
* etc?

It seems more and more helpers are popping up in the framework, but it's certainly hard to keep track of them from the outside looking in.

**Comment by esDotDev** [comment]
Another issue, is a developer coming to this page gets a 91 line example, in a small window that only holds 25 lines, but all they actually are looking for, is these 4 lines:
```
Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.arrowUp): const IncrementIntent(),
        LogicalKeySet(LogicalKeyboardKey.arrowDown): const DecrementIntent(),
      },
```
I know this is a larger discussion on docs, but if I simply saw that snippet, at the top of the docs page, I would immediately understand what this does, it would be more clear than the description: "_This widget establishes a ShortcutManager to be used by its descendants when invoking an Action via a keyboard key combination that maps to an Intent_"

**Comment by asadamatic** [comment]
What is the purpose of `Focus` widget here?

**Comment by Jonas-Sander** [comment]
I've now looked at the docs of the [`Shortcuts`](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html) [(stable link)](https://github.com/flutter/flutter/blob/d79295af24/packages/flutter/lib/src/widgets/shortcuts.dart#L564) class.   
The documentation is way better from when I first opened this issue. Good job 👍

One thing that did confuse me when comming to the whole shortcuts documentation though is that creating/using shortcuts seems very complicated and verbose.  
It feels a bit like the Router in that it is powerful and flexible but complex and hard to understand.  

As a starter I did ask myself when first when looking at the shortcuts code why there is even a seperation between `Intent` and `Action`. 
At the very first look at it I was also just confused why something like `Action` and `Intent` is even necessary.    
I basically thought to myself: _I just wanted to make something happen when pressing a button! Why do I need to learn all this stuff now?!_

When I wanted to first use shortcuts I just though of something like the `keyboard_shortcuts` has done:
```dart
    KeyBoardShortcuts(
        keysToPress: {LogicalKeyboardKey.arrowUp},
        onKeysPressed: () => setState(() {
              count = count + 1;
            }),
      //....
   )
``` 

The current system still needs to have `Intent` and `Action`:
```dart
    Shortcuts(
      shortcuts: <ShortcutActivator, Intent>{
        LogicalKeySet(LogicalKeyboardKey.arrowUp): const IncrementIntent(),
      },
      child: Actions(
        actions: <Type, Action<Intent>>{
          IncrementIntent: CallbackAction<IncrementIntent>(
            onInvoke: (IncrementIntent intent) => setState(() {
              count = count + 1;
            }),
          ),
        },
```

The thing that I disliked the most was that there was not a simple explanation as to **why**.   
Basically separating `Action` and `Intent` means that the system is more flexible(?). What does that mean in practical terms mean though?  
    
Here are my **guesses**:     
*(I haven't actually used the shortcut system as I found it too confusing back then)*

* By separating `Action` and `Intent` you can (more easily) replace/change what buttons need to be pressed to invoke a `Intent` without needing to touch the code where the `Action` is run. Basically in this way you can make the decision of what buttons invoke what intent somewhere more suitable in the code than where the `Action` (the thing you want to do in the end) is defined/run.    
For example you could have a screen where you could change the shortcuts which basically means only needing to modify the `ShortcutActivator` in `Shortcuts`. All the code where you say what happens when receiving the `Intent` (the code that uses the `Actions` class for example) can stay the same.  

* Separating the `Action` and `Intent`  means that the `Action` may be in another context than the `Intent`. This allows passing the `Action` stuff via the constructor that may not be available in the place where the `Intent` is defined. (What would be a good example here?).  This is basically what is shown in the second example in the docs but without a "why/where you would actually use this".

* This may also allow to override the `Action` but leaving the intent the same (e.g. overriding the default actions provided by `MaterialApp` for skipping focus? (no idea if you can really do this))

I wish there was some explanation in this way somewhere.     
For me this also begs the question if there should be an easier system like `keyboard_shortcuts` available for simple cases and the above for the "harder" cases?  

For me it's also unclear what the best practices are with the shortcut system. As someone unexperienced I would probably just use the system like in the first example in the docs (having the `Shortcuts` and `Actions` widgets directly next to each other). As we saw above there may be positives to separating both from each other. From the docs I just can't tell why I should separate them and what problems I could encounter in the future (maybe internationalization, customization?) if I don't.

Of course I can't comment on what information would be more suited for the code docs and the flutter web docs.

**Comment by esDotDev** [comment]
Definitely seems like there is some room for wrapper that strips away some of the flexibility/decoupling, and just couples a simple method to a key binding as you tend to want more often than not. 

The need to define an actual class makes this a bit tricky to imagine tho... in practice we want something like:
```
SimpleShortcut(
  bindings: {
     KeyBinding([LogicalKeyboardKey.arrowUp]) :  () => count = count + 1,
  }
  child: ...
)
```

**Comment by Leffe108** [comment]
Regarding the guesses for the action/intent system, I find it makes sense once you have more than one trigger (intent) for the same action to have the actions in one place so they can be reused. One such example is if you have both a shortcut and a button to invoke the same action. 

But with this perspective, while it is quite simple to make a function that trigger an intent from a button, I miss a intent-property on buttons to make it agnostic that both buttons and shortcuts may emit intents directly instead of a callback.

But .. you could easily do this centralization in a action class yourself without the action/intent system in the framework if shortcuts had a simple callback making the framework easier and less complex.

**Comment by gspencergoog** [comment]
@esDotDev You can already use a `Focus` widget to act like a simple shortcuts widget. Here's an example implementation similar to what you are requesting (`SingleActivator` on the `dev` branch is already similar to your `KeyBinding` example, so I used that instead).

```dart
class SimpleShortcut extends StatelessWidget {
  const SimpleShortcut({
    Key? key,
    required this.bindings,
    required this.child,
  }) : super(key: key);

  final Map<ShortcutActivator, VoidCallback> bindings;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: (FocusNode node, RawKeyEvent event) {
        KeyEventResult result = KeyEventResult.ignored;
        // Activates all key bindings that match, returns handled if any handle it.
        for (final ShortcutActivator activator in bindings.keys) {
          if (activator.accepts(event, RawKeyboard.instance)) {
            bindings[activator]!.call();
            result = KeyEventResult.handled;
          }
        }
        return result;
      },
      child: child,
    );
  }
}
```

It doesn't separate concerns between the bindings and the actions, but it is simple to use:

```dart
  @override
  Widget build(BuildContext context) {
    return SimpleShortcut(
      bindings: {
		const SingleActivator(LogicalKeyboardKey.arrowUp, control: true): () => count++,
		const SingleActivator(LogicalKeyboardKey.arrowDown, control: true): () => count--,
	  },
      child: child,
    );
  }
```

For some apps, this may be all that is needed.

**Comment by esDotDev** [comment]
Oh nice, ty! I'll probably do a blog post on this. 

Indeed I think this would serve the majority of common use cases, especially since we can still get code re-use by declaring the actions as methods and passing them around that way.

**Comment by gspencergoog** [comment]
BTW, I am working on some extensive docs for the system that will be published on the website soon.

**Comment by whiplashoo** [comment]
Is there a way to use shortcuts (keyboard combinations) that conflict with the platform-level ones? 

For example, I want for the user of my MacOS app to be able to use shortcuts like `Command + Q` or `Command + Space` for app-specific Actions. These, however, are macOS declared shortcuts, so the below example doesn't work:

``` dart
shortcuts: <ShortcutActivator, Intent>{
  SingleActivator(LogicalKeyboardKey.keyQ, meta: true):  const RemoveDraftIntent(),
},
```

It instead quits the app. 

So, is there a way to override these platform-level shortcuts or to prevent the KeyEvent from propagating outside the Flutter app? 

Should I open a separate issue for this?

**Comment by gspencergoog** [comment]
@whiplashoo I'm not sure it's possible to override those on macOS.  But yes, please open a new issue for that if you would like us to take a look at it.

**Comment by gspencergoog** [comment]
Closing this issue because I've published this: https://flutter.dev/docs/development/ui/advanced/actions_and_shortcuts

Please open new issues if you find other deficiencies in the docs.
