### ISSUE TITLE
Issue: ImageFit, ImageFit.scaleDown not a good fit for FittedBox.fit

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#6463]
The value of FittedBox.fit can be ImageFit.scaleDown. The doc for ImageFit.scaleDown says:

`Center the image within the box and, if necessary, scale the image down to ensure that the image fits within the box.`

FittedBox provides an alignment parameter. It's not clear from the FittedBox doc how alignment jibes with ImageFit.scaleDown centering. FTR: FittedBox alignment works as expected.

On a related note, the ImageFit emum is, well, image specific. Maybe it should be called BoxFit.

**Comment by eseidelGoogle** [comment]
Unchanged: https://docs.flutter.io/flutter/painting/ImageFit-class.html
