### ISSUE TITLE
ScrollController is not attached

### ISSUE THREAD

**Issue by JakubPatrik** [flutter/flutter#64646]
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart:
Failed assertion: line 110 pos 12: _positions.isNotEmpty'

**Comment by TahaTesser** [comment]
Hi @JakubPatrik 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by JakubPatrik** [comment]
Seems to have been a build bug, now works fine
