### ISSUE TITLE
Port sample apps to win32/uwp 

### ISSUE THREAD

**Issue by steskalja** [flutter/flutter#64640]
I would be great if the flutter team updated the sample apps to work with win32/uwp. I know flutter supports win32, but it would be useful to see sample apps. This would allow new developers to get an idea of how to design and structure an app for win32/uwp.

**Comment by TahaTesser** [comment]
Hi @steskalja 
Can you please link the samples you're talking about? Don't they run on win32? 
Thank you

**Comment by stuartmorgan** [comment]
The Windows embedding APIs, tool support, and templates are not stable, so checking in Windows runners would be counterproductive at this stage. Desktop-compatible samples will have Windows added when it's stable, as happened with the other desktop platforms.

In the meantime you can [add a Windows runner](https://github.com/flutter/flutter/wiki/Desktop-shells#tooling) to a sample locally to try it out. I'm not sure what you mean by "how to design and structure"; the samples would be using the stock runner created by the template.
