### ISSUE TITLE
Crash when compiling file:///Users/lutang/Developer/flutter/packages/flutter_tools/lib/src/version.dart, at character offset 32933: type 'AmbiguousBuilder' is not a subtype of type 'Expression'

### ISSUE THREAD

**Issue by lutang123** [flutter/flutter#64662]
My Flutter totally crashed: 

It was all ok yesterday, but this morning I suddenly want to try Flutter web, so I did this following the step in https://flutter.dev/docs/get-started/web:
 
 flutter channel beta
 flutter upgrade
 flutter config --enable-web

And somehow I got all kinds of error. And now I couldn't run any App, not even starting a new app. I double check, my Flutter, Dart and Android Studio all updated.

1. It can not recognize any device, so I can not run the code on emulator or physical device, and I got error like this:

Can't load Kernel binary: Invalid kernel binary format version.

2. Then I googled, and seems people say  to delete bin/cache, and the run flutter doctor,   so I did, but then I got the following error, below are Logs and what I got after running flutter doctor: 

## Logs

What does this mean? why it crashed and how can I get it running? Well, I don't have to run web or change channel, at least help me get back and being able to run a normal mobile app like I was yesterday. I have been trying and searching for answer and have tries a few hours, nothing works.

And here is what I have after running flutter doctor, it's basically the same error message as above.

% flutter doctor -v
Building flutter tool...
Crash when compiling file:///Users/lutang/Developer/flutter/packages/flutter_tools/lib/src/version.dart,
at character offset 32933:
type 'AmbiguousBuilder' is not a subtype of type 'Expression'
#0      BodyBuilder.doBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:1767:46)
#1      BodyBuilder.endBinaryExpression (package:front_end/src/fasta/kernel/body_builder.dart:1718:7)
#2      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4644:20)
#3      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4466:13)
#4      Parser.parseSingleLiteralString (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5522:17)
#5      Parser.parseLiteralString (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5467:13)
#6      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4892:14)
#7      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4793:12)
#8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4525:13)
#9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4466:13)
#10     Parser.parseReturnStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4373:13)
#11     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4240:14)
#12     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4217:20)
#13     Parser.parseBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6380:15)
#14     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4238:14)
#15     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4217:20)
#16     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6080:13)
#17     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4254:14)
#18     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4217:20)
#19     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4122:15)
#20     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:990:14)
#21     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)
#22     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)
#23     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3726:20)
#24     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3467:15)
#25     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3141:15)
#26     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1852:13)
#27     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1810:14)
#28     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:578:14)
#29     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:474:14)
#30     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#31     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:425:14)
<asynchronous suspension>
#32     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
<asynchronous suspension>
#33     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:358:20)
#34     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#35     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:356:12)
#36     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>
#37     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#38     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#39     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#40     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#41     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#42     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#44     new Future.sync (dart:async/future.dart:223:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#46     _rootRun (dart:async/zone.dart:1190:13)
#47     _CustomZone.run (dart:async/zone.dart:1093:19)
#48     _runZoned (dart:async/zone.dart:1630:10)
#49     runZoned (dart:async/zone.dart:1550:10)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#51     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#52     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#53     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#54     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#55     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#56     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#57     _rootRun (dart:async/zone.dart:1182:47)
#58     _CustomZone.run (dart:async/zone.dart:1093:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#60     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#61     _rootRun (dart:async/zone.dart:1190:13)
#62     _CustomZone.run (dart:async/zone.dart:1093:19)
#63     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#64     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#65     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#66     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:998:7)
#1      DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)
#2      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:665:5)
#3      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3726:20)
#4      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3467:15)
#5      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3141:15)
#6      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1852:13)
#7      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1810:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:578:14)
#9      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:474:14)
#10     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:354:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:425:14)
<asynchronous suspension>
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:242:15)
<asynchronous suspension>
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:358:20)
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#15     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:356:12)
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#18     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#19     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#21     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#22     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#23     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#24     new Future.sync (dart:async/future.dart:223:31)
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#26     _rootRun (dart:async/zone.dart:1190:13)
#27     _CustomZone.run (dart:async/zone.dart:1093:19)
#28     _runZoned (dart:async/zone.dart:1630:10)
#29     runZoned (dart:async/zone.dart:1550:10)
#30     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#31     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#32     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#33     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#34     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#35     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#36     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#37     _rootRun (dart:async/zone.dart:1182:47)
#38     _CustomZone.run (dart:async/zone.dart:1093:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#44     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```
```
update: 
I then put back this cache file in Flutter/bin/cache (as I said I deleted this cache file after searching on google for solution, but I got new error as I shown above, so then I put it back, but still I have the following error:

Flutter device daemon #1: process exited during startup. Exit code: 253, stderr: Can't load Kernel binary: Invalid kernel binary format version. 

I don't understand this, what happened? Is it because I run Flutter upgrade? so how do I go back or solve the problem, right now when I open any flutter app, I got this error and it can't detect the available device, so I can not run any app, nor can I start any new app.

I am relatively new to software development, just started using Flutter since April this year, so I don't have a lot of experience. Any help is highly appreciate. Thanks for everyone reading this.

**Comment by johnniwinther** [comment]
This might have been fixed recently in https://dart-review.googlesource.com/c/sdk/+/157941.

@lutang123 What version of flutter are you running?

**Comment by lutang123** [comment]
> This might have been fixed recently in https://dart-review.googlesource.com/c/sdk/+/157941.
> 
> @lutang123 What version of flutter are you running?

Hi, John, thank you for your quick response. 

I was running the latest version of Flutter, as I said: 

"I did this following the step in https://flutter.dev/docs/get-started/web:

flutter channel beta
flutter upgrade
flutter config --enable-web"

so I upgraded flutter, so the version I was running should be the latest, and I always upgrade whenever possible. But I don't know what's wrong and why it got crashed. I have read the link you forwarded to me before I posted the issue, but honestly I didn't understand and didn't see a clear message on how to fix it.

But anyway, last night I re-do everything from beginning, I installed a new flutter sdk and replaced the current one, updated Andriod Studio and downloaded new Xcode too, and eventually it started working normally, only some packages I included in "pubspes.yaml" can't be recognized, I don't know why, I indeed ran 'flutter pub get' several times and the packages are all latest version, so then I downloaded the package github repo, and added a separated dart file for those package (instead of in"pubspes.yaml"), then my App is working Ok, I am glad.

Even though it's ok now, I would still like to understand where it goes wrong and how can I prevent such things happen again. Should I not upgrade Flutter? Should I not change channel to beta? What should I do if i want to enable web for a current mobile project? 

Thank you very much for any comment and help.

**Comment by johnniwinther** [comment]
I don't know enough about the flutter development process to answer your questions. Maybe @jonahwilliams knows more?

**Comment by jonahwilliams** [comment]
@lutang123 this might happen if the tool cache breaks in an unexpected way. you could verify this by checking that the downloaded dart sdk version matches the commit in the flutter repo, so essentially:

```
bin/cache/dart-sdk/bin/dart --version
```

and then:

```
git status
git rev-parse HEAD
```

If you include that information it will help me narrow down what went wrong here.  On the otherhand if you want to unblock yourself, you could delete the entire `flutter/bin/cache` directory and try again.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
