### ISSUE TITLE
Material Design Catalog page not loading

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#6466]
This page ([https://flutter.io/material-design-catalog/](https://flutter.io/material-design-catalog/)) is not loading. Possibly related to recent commits from [#294](https://github.com/flutter/website/pull/294) and [#291](https://github.com/flutter/website/pull/291).

@Hixie Can you ptal and debug?

**Comment by sethladd** [comment]
Works for me from home. Can you try again?

**Comment by Hixie** [comment]
I have no idea what's going on here. The page is literally making Chrome hang for me.

**Comment by Hixie** [comment]
Works fine in Firefox.

**Comment by sethladd** [comment]
I'm now in Munich, and I see the delayed loading. The text in the page came up, but not the images. I see:

![screen shot 2016-10-24 at 4 28 25 am](https://cloud.githubusercontent.com/assets/5479/19644027/68523c8a-99a2-11e6-969b-b50404041583.png)

**Comment by Hixie** [comment]
Chrome really is frozen. It hangs the tab hard. I've no idea why. Firefox works fine.

**Comment by Hixie** [comment]
(I don't think my changes did anything that would affect this, but clearly they might have.)

**Comment by InMatrix** [comment]
I got this error message in the developer console when loading the catalog in Chrome: "Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError" 

I suspect loading images from material.google.com is causing the problem, but then I don't understand why it appears to only affect Chrome.

**Comment by InMatrix** [comment]
Fixed by adding a missing </p>
