### ISSUE TITLE
flutter tool doesn't run on WSL1 - unhandled exception in bot_detector.dart/AzureDetector 

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#64673]
## Steps to Reproduce

1. Set up a fresh install of a WSL1 Ubuntu distribution on Windows.
2. `git clone https://github.com/flutter/flutter.git -b stable`
3. Attempt to run any flutter command, e.g. `flutter doctor`
4. The tool quits with exit code 255.

## Logs

The tool exits:

```
$ flutter/bin/flutter doctor
Downloading Dart SDK from Flutter engine 9d5b21729ff53dbf8eadd8bc97e0e30d77abec95...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  246M  100  246M    0     0  36.3M      0  0:00:06  0:00:06 --:--:-- 36.7M
Building flutter tool...
Unhandled exception:
OS Error: Connection refused, errno = 111
```

Connecting to the Dart observatory reveals the unhandled exception is raised by the attempt to connect to Azure: https://github.com/flutter/flutter/blame/master/packages/flutter_tools/lib/src/base/bot_detector.dart#L105.

The bug was introduced here: https://github.com/flutter/flutter/pull/50641

## Workaround

The issue can be avoided by running flutter once with `BOT=false` in the environment:

```
$ BOT=false flutter doctor
```

This creates a JSON file `~/.flutter_tool_state` with key `"is-bot": false` so that future invocations skip the bot detector check and don't raise an unhandled exception.

## Flutter doctor output

```
 ~  flutter doctor                                                                                                                                                                                       ✔  10s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.1)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/usr/lib/android-sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

**Comment by jonahwilliams** [comment]
@matthewlloyd do you have the full stack trace from the failure?

Also FWIW, use flutter in WSL2 occasionally and it works pretty OK there.

**Comment by jonahwilliams** [comment]
Looks like we need to add `on OsError` (which is actually an exception).

**Comment by matthewlloyd** [comment]
The tool didn't produce a stack trace with the exception and I don't see a way to capture a stack trace from the observatory. However it seems obvious and I agree on what needs to be fixed there.

I actually started out using Flutter on WSL2, but as a heavy IntelliJ user my files are hosted in Windows and the /mnt/c filesystem performance was unusably slow (and the \\wsl mount doesn't play well with IntelliJ). I tried IntelliJ under X410 with WSL2-hosted project files, which works fine, but the Android emulator doesn't run under WSL2 and tools like adb and flutter daemon don't work so well with the Android emulator running on the Windows side. So back to WSL1 it was for me. Now I am using mostly MSYS2 with Flutter and Windows-hosted project files, which works quite smoothly, and occasionally I'm dipping into WSL1 for scripts and other things that need packages that pacman doesn't have but apt does. I'm glad it works so well because I'm making a conscious effort to reduce my time spent using Apple products.

**Comment by jonahwilliams** [comment]
Fair enough, the error should be fixable in this case anyway. That said, we definitely do not test flutter on WSL1, and due to the differences between that and a real linux installation there will be other cases we will likely miss in the future.
