### ISSUE TITLE
Back navigation doesn't trigger route observer didPop()

### ISSUE THREAD

**Issue by scaraux** [flutter/flutter#64677]
## Steps to Reproduce

1. Create a widget that implements the `RouteAware` Mixin
2. Push this widget through a `CupertinoPageRoute` / `MaterialPageRoute`
3. Pop this route using a NavigationBar, or `Navigator.of(context).pop()`

**Expected results:** 

The `didPop()` method should be called

**Actual results:** 

The `didPop()` method does not get called

```
final RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();

return CupertinoApp(
    ...
    navigatorObservers: [routeObserver],
}
```

Pushing like so:

```
Navigator.of(context).push(
  CupertinoPageRoute(builder: (context) => MyWidget()),
);

```
The Widget

```
class MyWidget extends StatefulWidget {
  MyWidget({Key key}) : super(key: key);

  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> with RouteAware {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context));
  }

  @override
  void dispose() {
    routeObserver.unsubscribe(this);
    super.dispose();
  }

  @override
  void didPop() {
    print('never called');
  }

  @override
  void didPopNext() {
    print('never called');
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: [
          CupertinoNavigationBar(
            middle: Text('42'),
          ),
        ],
      ),
    );
  }
}
```

The `didPop() `method is never called when popping a `CupertinoPageRoute` with the back button unless I push with `rootNavigator = true` which is not what I want.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/oscar/flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/oscar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Oscar’s iPhone (mobile) • xxx • ios • iOS 13.5.1

! Doctor found issues in 2 categories.
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @scaraux 
Can you please provide a minimal complete reproducible code sample? I need a code that I can just copy/paste to run it.
Thank you

**Comment by scaraux** [comment]
> Hi @scaraux
> Can you please provide a minimal complete reproducible code sample? I need a code that I can just copy/paste to run it.
> Thank you

When creating a simple project to provide you the minimal reproducible code, I noticed that the issue I am facing only happens when pushing routes from a screen that is embedded in `CupertinoTabScaffold`, which is the case in the app I am working on.

Here is the full code, shortest I was able to do:

<details>
  <summary>Minimal Reproducible Code</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

final RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyHomePage(),
      navigatorObservers: [routeObserver],
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final CupertinoTabController _controller = CupertinoTabController();

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      controller: _controller,
      tabBuilder: (BuildContext context, int index) {
        return CupertinoTabView(
          builder: (BuildContext context) => TabPage(),
        );
      },
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(icon: Icon(Icons.home)),
          BottomNavigationBarItem(icon: Icon(Icons.star)),
        ],
      ),
    );
  }
}

class MySecondPage extends StatefulWidget {
  MySecondPage({Key key}) : super(key: key);

  @override
  _MySecondPageState createState() => _MySecondPageState();
}

class _MySecondPageState extends State<MySecondPage> with RouteAware {
  @override
  void didChangeDependencies() {
    routeObserver.subscribe(this, ModalRoute.of(context));
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    routeObserver.unsubscribe(this);
    super.dispose();
  }

  @override
  void didPop() {
    print('didPop called');
  }

  @override
  void didPopNext() {
    print('didPopNext called');
  }

  @override
  void didPush() {
    print('didPush called');
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(),
      child: Container(
        color: CupertinoColors.white,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'Navigate back using the navigation bar.\n Observer won\'t trigger',
                textAlign: TextAlign.center,
              )
            ],
          ),
        ),
      ),
    );
  }
}

class TabPage extends StatefulWidget {
  TabPage({Key key}) : super(key: key);

  @override
  _TabPageState createState() => _TabPageState();
}

class _TabPageState extends State<TabPage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Container(
        color: CupertinoColors.white,
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CupertinoButton(
                color: CupertinoColors.activeBlue,
                child: Text(
                  'Push A Screen',
                  style: TextStyle(
                    color: CupertinoColors.black,
                  ),
                ),
                onPressed: () {
                  Navigator.of(context).push(
                    CupertinoPageRoute(builder: (context) => MySecondPage()),
                  );
                },
              )
            ],
          ),
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}
```
</details>

**Comment by scaraux** [comment]
After making some research, I believe this is not a bug but rather this is how Flutter navigators work.
Correct me if I'm wrong, but using a `CupertinoTabView`, a new Navigator is created.

Since I set my observer for the root navigator only, the didPop is therefore not triggered as it depends on a more nested navigator. I need to find a find to set multiple `navigatorObservers`, one for each `CupertinoTabView` and later on retrieve the observer.

**Comment by pedromassangocode** [comment]
> After making some research, I believe this is not a bug but rather this is how Flutter navigators work.
> Correct me if I'm wrong, but using a `CupertinoTabView`, a new Navigator is created.
> 
> Since I set my observer for the root navigator only, the didPop is therefore not triggered as it depends on a more nested navigator. I need to find a find to set multiple `navigatorObservers`, one for each `CupertinoTabView` and later on retrieve the observer.

Right. I would suggest you to attach the `RouteAware` into the `_MyHomePageState` class so that you will be able to listen to `didPop()` (witch is called when the actual route is popped) and `didPopNext()` that is called when the top route is popped.

Closing as this is not an issue with Flutter itself. If you disagree please feel free to write in the comments bellow and I will reopen it.
Thank you

**Comment by scaraux** [comment]
> > After making some research, I believe this is not a bug but rather this is how Flutter navigators work.
> > Correct me if I'm wrong, but using a `CupertinoTabView`, a new Navigator is created.
> > Since I set my observer for the root navigator only, the didPop is therefore not triggered as it depends on a more nested navigator. I need to find a find to set multiple `navigatorObservers`, one for each `CupertinoTabView` and later on retrieve the observer.
> 
> Right. I would suggest you to attach the `RouteAware` into the `_MyHomePageState` class so that you will be able to listen to `didPop()` (witch is called when the actual route is popped) and `didPopNext()` that is called when the top route is popped.
> 
> Closing as this is not an issue with Flutter itself. If you disagree please feel free to write in the comments bellow and I will reopen it.
> Thank you

Placing it in _MyHomePageState doesnt allow to listen for `didPop`s coming from inside the TabView. Also, I want to implement RouteAware at a screen level, for analytics purposes, as I need their respective name.

As of right now, I created an observer for each TabView page, and I switch the current observer upon tab change. Then the push screens can plug themselves on the observer they belong. Let me know if you have a better approach.
