### ISSUE TITLE
Table is maybe not always the best initial answer for layouts

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6467]
Suggestion for API docs. If a user is looking to layout, and they find Table in the API docs, we may want to redirect them to other docs re: layout.

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/6471.

**Comment by sethladd** [comment]
Great, thanks!
