### ISSUE TITLE
[image_picker] return thumbnail image for pick video functionality

### ISSUE THREAD

**Issue by 123cristen** [flutter/flutter#64686]
It would be great to have a plugin for generating a video thumbnail from video files as a preview.

**Comment by mehmetf** [comment]
image_picker can be extended to return a thumbnail image for "pick video" functionality. 

`PickedFile` can return path, bytes but also os filename and a thumbnail if the file is a video. 

You can use content resolver to do this on Android. See:

https://developer.android.com/reference/android/provider/MediaStore.Video.Thumbnails for API < 29 and https://developer.android.com/reference/android/content/ContentResolver#loadThumbnail(android.net.Uri,%20android.util.Size,%20android.os.CancellationSignal) for the most recent API.

**Comment by stuartmorgan** [comment]
Was the initial request related to image_picker, or was it about wanting to be able to generate a thumbnail for an arbitrary video file that an app already has a path to (with permissions)? Those are very different features.

**Comment by thecaptainXgod** [comment]
Any updates?

**Comment by stuartmorgan** [comment]
Absent clarity on what exactly is being requested here, closing.
