### ISSUE TITLE
LayoutBuilder should cache constraints and not rebuild if unchanged

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6469]
Run the following and then tap the screen - you'll see that the print occurs each tap.

I don't expect that print to output more than once.

``` dart
Future main() async {
  GlobalKey _simKey = new GlobalKey();

  runApp(
    new Column(
      children: [
        new Flexible(
          child: new LayoutBuilder(
            builder: (_, BoxConstraints constraints) {
              print('LayoutBuilder build $constraints');
              return new Foo(key: _simKey);
            },
          ),
        )
      ],
    ),
  );
}

class Foo extends StatefulWidget {
  Foo({Key key}) : super(key: key);
  @override
  FooState createState() => new FooState();
}

class FooState extends State<Foo> {
  Color _color = newColor;

  void swap() => setState(() {
        _color = newColor;
      });

  @override
  Widget build(_) => new LayoutBuilder(
        builder: (__, ___) => new GestureDetector(
              onTap: swap,
              child: new Container(
                decoration: new BoxDecoration(backgroundColor: _color),
              ),
            ),
      );

  static Color get newColor => new Color(new Random().nextInt(0xFFFFFFFF));
}
```

**Comment by abarth** [comment]
Ah, thanks for this example.  What's happening is the LayoutBuilder in FooState needs to rebuild, which means it provokes a layout on itself, which causes the LayoutBuilder with the print to also go through layout because there's no layout boundary between them.

**Comment by abarth** [comment]
It's interesting that in this case Foo will build twice.  Once because of its setState and once because its parent rebuilt during layout.  Normally it would only build once because its parent would rebuild before we got around to processing its setState rebuild.

/cc @Hixie

**Comment by abarth** [comment]
I think it would be reasonable for LayoutBuilder to cache its BoxConstraints and only call the builder again if the constraints change or it went through `update`.

This example does point to another issue with LayoutBuilder.  In your example, you're only changing paint-time information, but you're trigger a bunch of unnecessary layout work.  Maybe our walk-pruning in layout is enough to make that ok.  It's probably worth studying this example to see how many unnecessary objects we actually visit in layout.

**Comment by Hixie** [comment]
Yeah the double rebuild is expected behaviour. @HansMuller  and I looked at it a lot back when he was trying the "inheritance link parent" idea and when I was working on LayoutBuilder bugs. We concluded there was not much to be done about it.

I agree that we should cache the constraints and not rebuild if they didn't change.

We can't avoid the other problem with the way this example is written, because we've no way to know if the callback has changed. We could use a delegate instead of a callback, though. That would make LayoutBuilder more awkward to use but more efficient.

**Comment by apwilson** [comment]
Anything I can do to help fix this issue?  I actually tried to cache the constraints in my local version of flutter but I ran into the issue @Hixie described, the children in the builder callback wouldn't get rebuilt even if some state they depended on had changed.

**Comment by apwilson** [comment]
I've 'fixed' this issue in my app by applying tight constraints to my LayoutBuilder so reducing priority.

**Comment by radzish** [comment]
Hello,

I have one more example that seems to be related, but in this case more critical:

```

**Comment by marcglasberg** [comment]
> In general you should assume that build methods will be called excessively. If that's a problem, use a stateful widget and cache the widget you return from `build`, so that it gets short-circuited next time.

@Hixie Could you explain how exactly? I'm not sure I follow.

**Comment by Hixie** [comment]
```dart
class _FooState extends State<Foo> {
  Widget _child;
  Widget build(BuildContext context) {
    _child ??= Container();
    return _child;
  }
}
```

**Comment by neckaros** [comment]
I was wandering why my widgets were always rebuilding!

ended up creating a Cached version of the layout builder that takes external parameters to check for rebuild:

```dart
import 'package:flutter/widgets.dart';

class CachedLayoutBuilder extends StatefulWidget {
  final Widget Function(BuildContext context, BoxConstraints constraints)
      builder;
  final List<dynamic> parentParameters;

  const CachedLayoutBuilder({Key key, this.builder, this.parentParameters})
      : super(key: key);
  @override
  _CachedLayoutBuilderState createState() => _CachedLayoutBuilderState();
}

class _CachedLayoutBuilderState extends State<CachedLayoutBuilder> {
  Widget previousBuild;
  BoxConstraints previousContraints;
  List<dynamic> previousParameters;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (ctx, constraints) {
      var parametersIdentical = true;
      if (previousParameters == null ||
          widget.parentParameters == null ||
          previousParameters.length != widget.parentParameters.length) {
        parametersIdentical = false;
      } else {
        for (var i = 0; i < previousParameters.length; i++) {
          if (previousParameters[i] != widget.parentParameters[i]) {
            parametersIdentical = false;
            break;
          }
        }
      }
      previousParameters = widget.parentParameters;
      if (!parametersIdentical || previousContraints != constraints) {
        previousBuild = widget.builder(ctx, constraints);
        previousContraints = constraints;
      }
      return previousBuild;
    });
  }
}
```

not very clean but does the job

**Comment by yjbanov** [comment]
@neckaros I believe your solution breaks if the `builder` function inherits something from the `BuildContext`, such as `Theme.of(context)` (or anything else published by an `InheritedWidget`).
