### ISSUE TITLE
Docs for the example code of package:integration_test is outdated

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#64690]
https://github.com/flutter/plugins/blob/master/packages/integration_test/README.md#using-flutter-driver-to-run-tests should refer to the example code, and we should update the filenames accordingly so that it works.

**Comment by jiahaog** [comment]
Currently in the [example app](https://github.com/flutter/plugins/tree/master/packages/integration_test/example), we tell users to place their test code with the following structure (simplified)

```yml
test_driver/
  foo_integration_test.dart # Entrypoint driver script that runs on the host
  foo.dart # Actual integration test script performing assertions running on device
```

Users can the tests with the following command:

```sh
flutter drive --driver=test_driver/foo_integration_test.dart  --target=test_driver/foo.dart 
```

It would be more appropriate for `foo.dart` to be placed in the `test/` directory, but we cannot rename it to `foo_integration_test.dart` because this would be picked up by the `flutter test` command which performs globbing of all files that end with `_test.dart` in the `test/` directory.

Would it make sense to introduce a `integration_test/` directory as a convention?

```yml
integration_test/ 
   foo_test.dart # Actual integration test script performing assertions running on device
test/
   # widget tests
  baz_test.dart
test_driver/
  integration_test_driver.dart # Can be shared to drive all package:integration_test tests
```

In this way there is a clear distinction between integration tests that run on a device, and widget tests that run with the flutter tester.

(related b/167126561)

cc/ @dnfield

**Comment by dnfield** [comment]
This sounds fine to me.
