### ISSUE TITLE
Video Playing In Slow Motion On Release Build For Both Android & iOS

### ISSUE THREAD

**Issue by RalphMarvin** [flutter/flutter#64705]
When i run my app in debug mode using flutter run i=the video plays fine but once i do a release build it plays in slow motion

**Comment by darshankawar** [comment]
Hi @RalphMarvin,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
