### ISSUE TITLE
Image orientation changes after upload with image picker flutter

### ISSUE THREAD

**Issue by Abhijithsp** [flutter/flutter#64703]
I have this image upload with image_picker 0.6.7+7 but now there is problem occurs,after i capture image in portrait mode it shows to a container with corresponding orientation but after upload the image to server database the orientation changing to 90 degree clockwise but no problem with landscape photo,i could't figure out what is problems is,i am also using compression to compress image before upload.

## Steps to Reproduce

```
Future getImage() async {
    PickedFile image = await Imagepicker.getImage(source: ImageSource.camera,maxHeight: 800);

    setState(() {
      _image = File(image.path);
      imageadd_containervisible = false;
      image_show_containervisible = true;
      isimage_selected = true;
      isCompresscomplete = false;
      isDisablesubmitbutton = true;
    });
    final tempDir = await getTemporaryDirectory();

    CompressObject compressObject = CompressObject(
      imageFile: _image,
      //image
      path: tempDir.path,
      //compress to path
      quality: 90,
      //first compress quality
      step: 4,
      //compress quality step, The bigger the fast, Smaller is more accurate, default 6
      mode: CompressMode.LARGE2SMALL,
    );

    Luban.compressImage(compressObject).then((imageFile){
      setState(() {
        compressedFile = File(imageFile);
        isCompresscomplete = true;
        isimage_selected = true;
        isDisablesubmitbutton = false;
      });
    });
  }

```

**Comment by darshankawar** [comment]
Hi @Abhijithsp,
For compressing the image, are you using any plugin ?
Also, what database are you using to store the images ? Can you also provide pictures of before and after you upload in to database ?
Thanks.

**Comment by Abhijithsp** [comment]
I am using Luban compression package,i have this same code base working for another client without any problem,i was using old image picker in this project and i have updated to latest version but i have updated but still problem  occurs.Backend is Nodejs API with mogodb,
The problem arise only in portrait mode
App Screen after capturing photo then shows to container 

![WhatsApp Image 2020-08-27 at 7 19 03 PM](https://user-images.githubusercontent.com/22987790/91451856-82304d80-e89b-11ea-952e-1ab771b6e990.jpeg)

shows image after upload in web

![Untitled](https://user-images.githubusercontent.com/22987790/91451901-8fe5d300-e89b-11ea-9550-ae5f5bc31166.png)

Flutter doctors returns no problem

**Comment by darshankawar** [comment]
Thanks @Abhijithsp for the details.
Is it possible for you to try image capturing and then saving in the db without compressing the image to see how it behaves then ?

**Comment by Abhijithsp** [comment]
I tested turned out it's a problem with compression not image picker problem @darshankawar

**Comment by Abhijithsp** [comment]
After i removed the compression from the function it's working without any problem @darshankawar

**Comment by darshankawar** [comment]
Thanks @Abhijithsp for finding the root-cause. Since the compression plugin is a 3rd party, I'd suggest you to raise this issue in their repo : https://github.com/crazecoder/flutter_luban/issues
Closing, as this doesn't seem to be an issue with Flutter or it's plugins. If you disagree, write in comments and I'll reopen.
Thanks.
