### ISSUE TITLE
Draggable maxSimultaneousDrags should work with multiple draggables

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#64707]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Use the following widget.
3. Start dragging around with multiple fingers

```dart
class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (context, index) => Draggable(
        maxSimultaneousDrags: 1,
        child: Text(index.toString()),
        data: index,
        feedback: SizedBox.shrink(),
      ),
    );
  }
}
```

Add a draggable to every item in a list and set maxSimultaneousDrags to 1

**Expected results:** 
One can only drag one of them at the same time

**Actual results:** 
You can drag as many as you can grab with your fingers

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.36, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.22.0-2.0.pre.36 at /usr/local/flutter-master
    • Framework revision d30e36ba8c (5 days ago), 2020-08-21 22:36:03 -0400
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)
```

</details>

This can be reproduced on every version of flutter

**Comment by darshankawar** [comment]
Hi @Kavantix,
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Kavantix** [comment]
@darshankawar edited the main post

**Comment by darshankawar** [comment]
Issue replicable on latest Stable (1.20.2). Able to drag multiple list items.

[64707.mp4.zip](https://github.com/flutter/flutter/files/5140202/64707.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by exaby73** [comment]
I can no longer reproduce this issue on the latest `Master (3.6.0-3.0.pre.54)` as of writing this. Therefore, I am closing this issue. If you disagree, please comment with a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I can reopen it. Thank you.
