### ISSUE TITLE
CP Request: Dart 2.9.2

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#64708]
Original issue: #63560
Dart SDK issue: https://github.com/dart-lang/sdk/issues/43157

I don't know if this already tracked somewhere, but as all the issues are closed, I thought I'd open a new issue.

Dart 2.9.2 has been released with a fix for a bug that prevents some users from building in release mode.

I would appreciate a CP into the stable channel, as I am affected by this.

**Comment by darshankawar** [comment]
Hi @knaeckeKami,
Please see [this](https://github.com/flutter/flutter/issues/63560#issuecomment-678939637) comment. The CP request for stable branch was made and the fix has been [merged](https://github.com/dart-lang/sdk/issues/43157#issuecomment-680808585) in stable and beta. Will just need to wait till this fix rolls into Flutter.
Hope this helps.

**Comment by knaeckeKami** [comment]
Hi @darshankawar,

Yes, the CP for Dart was merged into the stable branch of Dart.

I am asking for a CP with Dart 2.9.2 into the stable branch of Flutter. The number of reactions on the CP issue in Dart indicates that quite a number of users currently cannot build in release mode in the current stable version, so I think a CP is at least worth discussing.
There is no label called "cp: 1.22" or similar, so I'm not sure if there is currently another cherry-pick release planned.

**Comment by mraleph** [comment]
@knaeckeKami Dart and Flutter cherry-pick processes are aligned so there is no need to explicitly request cherry-picks. The work on bringing 2.9.2 into 1.20 is in progress (https://github.com/flutter/engine/pull/20838).
