### ISSUE TITLE
SafeArea does not seem to work for Pixel 3 XL emulator

### ISSUE THREAD

**Issue by SvenSchoene** [flutter/flutter#64714]
## Steps to Reproduce

Here is the code I copy&pasted for this ticket from here: https://flutter.dev/docs/get-started/codelab

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
            title: Text('Welcome to Flutter. Let\'s make this a bit longer.'),
          ),
          body: Center(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}
```

In the code above I added a `SafeArea()`-widget around `Scaffold()`. This causes no change in any way.

The expected result is that the text in the app bar is not overlayed by the notch.

The actual result can be seen on the screenshot:

![safearea_pixel3xl](https://user-images.githubusercontent.com/7631673/91443242-58fbc700-e873-11ea-93d6-4a24d030c33a.JPG)

This is a considerably worse problem in our actual app, where it looks like this (we're using a `Column()` there to display two an additional subtitle):

![safearea_pixel3xl_2](https://user-images.githubusercontent.com/7631673/91443682-f22add80-e873-11ea-9e05-72544a9d9957.JPG)

For reference: The emulator the screenshots was taken with is this one:

![android_studio_pixel3xl](https://user-images.githubusercontent.com/7631673/91443751-1090d900-e874-11ea-8d47-835a094f8db2.JPG)

`flutter doctor -v` output is here:

```
C:\Users\Sven>flutter doctor -v
[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.18362.1016], locale de-DE)
    • Flutter version 1.21.0-9.1.pre at G:\flutter
    • Framework revision be9bc8cb39 (9 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\DEV\Android\SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\DEV\Android\SDK
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Sven\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 83.0.478.61

• No issues found!
```

* While I'm currently on beta 1.21.0, I want to add that we saw this issue already with 1.17.0.
* I do not know if that problem existed before that version, since we only started testing on a Pixel 3 XL emulator recently.
* This problem exists on no other phone we tested, neither Android, nor iOS. I don't even know if it exists on real Pixel 3 XL devices, since we don't have one to test with. All we know is that there might be a subset of users for our app (and possibly many other Flutter apps as well) that suffer from this problem.
* There seemed to be a related / similar / the same bug already: https://github.com/flutter/flutter/issues/35403 In the ticket it is declared as solved. So either the error has returned since the 26th February (date of the last comment), or I'm doing something wrong.

I'm willing to provide any further information required to make sense of this issue.

**Comment by darshankawar** [comment]
Hi @SvenSchoene,
I think the best bet is to verify the same on physical Pixel 3 XL device. But as you already mentioned you don't have one handy neither I. But does [this](https://github.com/flutter/flutter/issues/35403#issuecomment-591343391) comment probably help a bit ? 
Thanks.

**Comment by SvenSchoene** [comment]
Hey,

thanks for the attempt at finding something that may help! :) 

The ticket you're linking to is the same one I'm linking to in my last bullet point at the bottom of my post. So no, unfortunately it doesn't help the situation. I'm even wondering whether that bug was ever fixed (clearly in that comment in #35403 it looks fixed), or if it returned at some point.

**Comment by darshankawar** [comment]
The Pixel 3 XL emulator indeed cuts-off the appbar text. Since I don't have Pixel 3 XL device to confirm if this is an emulator specific issue or a genuine bug, I am keeping this issue open for further analysis.

![Screen Shot 2020-08-28 at 11 33 23 AM](https://user-images.githubusercontent.com/67046386/91527778-04fceb00-e924-11ea-855c-184ba21c714d.png)

**Comment by jagip360m** [comment]
Hey,
To make the cutout work better use these instructions. Not sure if that is the correct way to get it to work, but it seems to work.

https://medium.com/@hiteshdhamshaniya.wvmagic/notch-android-emulator-with-p-e9b3556d9d5e

**Comment by SvenSchoene** [comment]
Thank you @jagip360m for the suggestion!

Setting the "Display cutout"-setting to a reasonable setting other than "Device default" does work.

One thing that this little experiment shows is that this is not a Flutter issue at all, because the issue is occuring throughout all apps on Android on a Pixel 3 XL emulator (see my two attached screenshots). So the default settings of the emulator are the issue here.

Since there is nothing to do on the Flutter side I'll close this ticket. Thanks again for that pointer!

![pixel_3_xl_01](https://user-images.githubusercontent.com/7631673/92535092-ba8a4100-f236-11ea-9d75-2ad9aaa22c7c.JPG)

![pixel_3_xl_02](https://user-images.githubusercontent.com/7631673/92535099-bd853180-f236-11ea-945a-0dc989bf9fd5.JPG)
