### ISSUE TITLE
ERROR: Could not find method implementation() for arguments [project ':path_provider_linux'] on object of type

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#64712]
**Error**

    FAILURE: Build failed with an exception.
    
    * Where:
    Script '/home/xxx/flutter_linux_v1.5.4-hotfix.2-stable.tar (1)/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 362
    
    * What went wrong:
    A problem occurred configuring project ':shared_preferences_linux'.
    > Could not find method implementation() for arguments [project ':path_provider_linux'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 1s
    Gradle task assembleDebug failed with exit code 1
    Exited (sigterm)

I'm using flutter version `1.20.1`

**flutter.gradle**

       // Wait for the Android plugin to load and add the dependency to the plugin project.
                pluginProject.afterEvaluate {
                    pluginProject.dependencies {
                        implementation dependencyProject
                    }
                }
            }
        }

The error pointed to `implementation dependencyProject`.

**build.gradle**

    buildscript {
        ext.kotlin_version = '1.3.31'
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.3.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.google.gms:google-services:4.3.3'
    
        }
    }
    
    
    allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    subprojects {
        project.configurations.all {
    
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex')) {
                    details.useVersion "27.1.1"
                }
    
                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx')) {
                    details.useVersion "1.0.1"
                }
    
                resolutionStrategy {
                    force 'com.android.support:support-v4:27.1.0'
                }
    
            }
        }
    }
    
    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

**android/app/build.gradle**

  

      def localProperties = new Properties()
        def localPropertiesFile = rootProject.file('local.properties')
        if (localPropertiesFile.exists()) {
            localPropertiesFile.withReader('UTF-8') { reader ->
                localProperties.load(reader)
            }
        }
        
        def flutterRoot = localProperties.getProperty('flutter.sdk')
        if (flutterRoot == null) {
            throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
        }
        
        def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
        if (flutterVersionCode == null) {
            flutterVersionCode = '1'
        }
        
        def flutterVersionName = localProperties.getProperty('flutter.versionName')
        if (flutterVersionName == null) {
            flutterVersionName = '1.0'
        }
        
        apply plugin: 'com.android.application'
        apply plugin: 'kotlin-android'
        apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
        apply plugin:'com.google.gms.google-services'
        
        android {
            compileSdkVersion 28
        
            sourceSets {
                main.java.srcDirs += 'src/main/kotlin'
            }
        
            lintOptions {
                disable 'InvalidPackage'
            }
        
            defaultConfig {
                // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
                applicationId "com.xxx"
                minSdkVersion 24 
                targetSdkVersion 28
                versionCode 36
                versionName "1.0.47"
                testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            }
        
            buildTypes {
                release {
                    signingConfig signingConfigs.debug
                }
            }
        
            flutter {
                source '../..'
            }
        
            configurations.all {
                    resolutionStrategy {
                            force 'com.android.support:support-v4:27.1.0'
                }
            }
        }
        
        dependencies {
        
            implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
            testImplementation 'junit:junit:4.12'
            androidTestImplementation 'androidx.test.ext:junit:1.1.1'
            androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
            implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21")
            implementation("androidx.lifecycle:lifecycle-livedata-core:2.1.0")
            implementation("androidx.lifecycle:lifecycle-common:2.1.0")
            implementation("androidx.arch.core:core-runtime:2.1.0")
            implementation("androidx.arch.core:core-common:2.1.0")
            implementation("androidx.annotation:annotation:1.1.0")
            implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.50")
            implementation("org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50")
        
        }

**Comment by darshankawar** [comment]
Hi @tony123S,
Is this on Linux ? Can you provide the gradle version you are using ? When do you exactly get this error ?
Also provide `flutter doctor -v`, `flutter run --verbose`.
Thanks.

**Comment by tony123S** [comment]
Yes, is on Linux. It used to work before.
**flutter doctor -v**
```
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.1 at /home/seng/Desktop/flutter_linux_1.20.1-stable/flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/seng/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

```

**Comment by tony123S** [comment]
My app able to run using `flutter run --verbose`, but can't debug. Why?

**Comment by tony123S** [comment]
I don't understand why it will show this error 

`Script '/home/seng/flutter_linux_v1.5.4-hotfix.2-stable.tar (1)/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 362`

I'm using this command to set flutter path, but why it keeps pointing to another flutter sdk ?

`export PATH="$PATH:/home/xxx/Desktop/flutter_linux_1.20.1-stable/flutter/bin/"`

**Comment by tony123S** [comment]
What is wrong?! Been stuck for a whole day. How to get more error info ? 

I also restart and reboot my PC.

**Comment by darshankawar** [comment]
Hi @tony123S,
Can you provide a minimal complete reproducible code sample that shows the issue ?
Also can you try to switch to latest master and see if it works for you there or see similar issue ?
Thanks.

**Comment by tony123S** [comment]
Thanks @darshankawar . I know  what causes this problem to happen. I have pointed to `flutter_linux_v1.5.4-hotfix.2`, which is wrong. After pointed to stable version, the error gone.

**Comment by satinder1624** [comment]
Hi 
I receiving following error
* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [androidx.annotation:annotation:1.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

my code android/build
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

dependencies {
    implementation 'androidx.annotation:annotation:1.1.0'
}


code for app/build
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app_firebase"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

apply plugin: 'com.google.gms.google-services'

can anyone help me with that?

**Comment by Althaf-codes** [comment]
@satinder1624 I'm also facing with the same error. Did you solved it? If so could you please share it?
