### ISSUE TITLE
[Feature request] Add keyboard shortcut support to TextField and other similar widgets

### ISSUE THREAD

**Issue by nojusr** [flutter/flutter#64721]
When editing a textfield or any other similar text editing widget, it is not possible to use the keyboard navigation and editing keys that most desktop users are accustomed to. I presume that this also applies to mobile devices that have built-in keyboard support. 

Here are a couple of things that are missing:
- Pressing the 'delete' key does not remove text in front of the cursor
- Arrow key navigation doesn't work
- Common key combinations don't work (Ctrl+A to select all, Ctrl+C to copy, Ctrl+V to paste, etc)

flutter --version:
```
Flutter 1.21.0-1.0.pre • channel unknown • unknown source
Framework • revision f25bd9c55c (6 weeks ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

I am not sure if this feature is already in development, but I've checked all of the recently accepted pull requests and didn't find anything similar to this.

**Comment by darshankawar** [comment]
Hi @nojusr,
I found a similar open issue, [27880](https://github.com/flutter/flutter/issues/27880).
Does that sound similar to your request ?
Thanks.

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by nojusr** [comment]
@darshankawar 
yeah, it appears that the issue you mentioned does indeed have the same premise, but i wrote it with the intention of the issue hopefully being put to a higher priority due to the fact that as far as i can tell, the same problem also applies to desktops, which rely much more on keyboard shortcuts than phones or tablets.

**Comment by stuartmorgan** [comment]
This is obsolete; lots of work has happened on editing and shortcuts in the last 3.5 months. Support for shortcuts exist, arrow keys are handled on all desktop platforms, delete should work everywhere.

If you find specific issues in a current version (that aren't already filed), please file new issues for the specific cases. Please include the platform you are reporting against in those issues.
