### ISSUE TITLE
LinearGradient missing parameters

### ISSUE THREAD

**Issue by lauralarez** [flutter/flutter#64724]
I recently upgraded the framework and after that, the LinearGradient is showing an error with the parameters stops and colors

> The named parameter 'stops' isn't defined.
> The named parameter 'colors' isn't defined.

```
Container(
    decoration: BoxDecoration(
      gradient: new LinearGradient(
        begin: Alignment.topLeft,
        end: Alignment.topRight,
        stops: [0.15, 0.5],
        colors: [
          Colors.blue,
          Colors.black
       ],
      ),
    ),
  );
```

However, when I go to the gradient.dart file they are still defined in the class.

```
...
class LinearGradient extends Gradient {
  /// Creates a linear gradient.
  ///
  /// The [colors] argument must not be null. If [stops] is non-null, it must
  /// have the same length as [colors].
  const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);
...
}
```

Flutter version 1.22.0-2.0.pre.93 • channel master 
Dart 2.10.0 (build 2.10.0-62.0.dev)

**Comment by pedrocsa** [comment]
Same problem here @lauralarez waiting for solution.

**Comment by pedrocsa** [comment]
@lauralarez , found the solution.

Go to your "Dart Analysis" tab and restart Dart Analysis Server:

![image](https://user-images.githubusercontent.com/40666410/91516681-71311c00-e92f-11ea-872b-3b422266a686.png)

The error should go away.

**Comment by lauralarez** [comment]
> @lauralarez , found the solution.
> 
> Go to your "Dart Analysis" tab and restart Dart Analysis Server:
> 
> ![image](https://user-images.githubusercontent.com/40666410/91516681-71311c00-e92f-11ea-872b-3b422266a686.png)
> 
> The error should go away.

Thanks a lot, it did work after running flutter clean

**Comment by n13** [comment]
Restarted VS code.. .fixed it....

**Comment by dt170** [comment]
> 
> 
> @lauralarez , found the solution.
> 
> Go to your "Dart Analysis" tab and restart Dart Analysis Server:
> 
> ![image](https://user-images.githubusercontent.com/40666410/91516681-71311c00-e92f-11ea-872b-3b422266a686.png)
> 
> The error should go away.

Fix the issue for me thanks!

**Comment by jugbeep** [comment]
If you're in VSCode: Run `flutter clean` in your terminal. Then open your command palette under 'View > Command Palette'. Type `>Restart Analysis Server` and hit enter to run it. That should clear up any linting issues you were seeing.

**Comment by Jvaeyhcd** [comment]
> @lauralarez , found the solution.
> 
> Go to your "Dart Analysis" tab and restart Dart Analysis Server:
> 
> ![image](https://user-images.githubusercontent.com/40666410/91516681-71311c00-e92f-11ea-872b-3b422266a686.png)
> 
> The error should go away.

赞
