### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for C:\Users\Lenovo\AndroidStudioProjects\beg_new\android\gradlew.bat.". A crash report has been written to C:\Users\Lenovo\AndroidStudioProjects\beg_new\flutter_10.log.

### ISSUE THREAD

**Issue by jithin07** [flutter/flutter#64720]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jonahwilliams** [comment]
@jithin07 you need to include the crash report on your bug report

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
