### ISSUE TITLE
testonly_devicelab_tests tests timing out after 3 hours in presubmit

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64723]
These tests have been timing out several times in a row. We should make this tests non blocking and informational only, split them per test to show a better signal and make it easy to identify if some specific test_bed type is failing tests with no capacity.

**Comment by godofredoc** [comment]
Moving as a P0 as this is blocking PRs consistently.

The test bed is for mac ios is down:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-22

**Comment by godofredoc** [comment]
We also need docs on how to access those machines and how to recover them.

**Comment by digiter** [comment]
There's an error when connecting salt: `Attempt to authenticate with the salt master failed with timeout error`.

**Comment by godofredoc** [comment]
Rebooting the machine fixed the issue. Removing the P0 and moving this bug out of the ticket queue

**Comment by godofredoc** [comment]
Now tests are failing consistently:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-22

Is this a real issue?

**Comment by digiter** [comment]
New bot status: Quarantined: CPU too hot at 77.5°C (>70°C).

**Comment by digiter** [comment]
Changed to P3 as the immediate issue has been mitigated.

**Comment by digiter** [comment]
The remaining tasks are duplicated in https://github.com/flutter/flutter/issues/65046
