### ISSUE TITLE
99th_percentile_frame_build_time_millis stock_animation_open_first_frame_average stock_animation_subsequent_frame_average regressions

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#64731]
https://flutter-flutter-perf.skia.org/e/?begin=1598378301&end=1598446986&keys=Xd08a403681c564e5dc7e5bf637fc7a59&xbaroffset=21234

Perhaps this roll? https://github.com/flutter/flutter/pull/64593

**Comment by zanderso** [comment]
If it's the hint_freed revert, we'll have to take it, but maybe it's the Skia roll? https://github.com/flutter/engine/pull/20742

**Comment by zanderso** [comment]
Maybe @liyuqian or @jason-simmons could take a quick look.

**Comment by liyuqian** [comment]
I believe this is expected by "Revert hint_freed (flutter/engine#20746)" as [the benchmark improved when hin_freed first rolled into the framework](https://flutter-flutter-perf.skia.org/e/?begin=1598034362&end=1598551384&keys=Xd08a403681c564e5dc7e5bf637fc7a59&numCommits=130&xbaroffset=21234)

CC @dnfield as this means that hint_freed brought us some speedup 😄

**Comment by dnfield** [comment]
Hint freed is coming back but it'll happen less often. Be curious to see if it helps this benchmark again.
