### ISSUE TITLE
when I am trying to create new project, pub get is stuck

### ISSUE THREAD

**Issue by jajojon** [flutter/flutter#64744]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs
![Снимок экрана (1)](https://user-images.githubusercontent.com/23551202/91483402-19f46280-e8c1-11ea-9052-44dd58ca92a0.png)

```
```

```
```

**Comment by TahaTesser** [comment]
Hi @jajojon 
Please try a different network, this could be because of your ISP. 
If the problem, please Can you please provide your `flutter doctor -v` your `flutter create mybug --verbose`
Thank you

**Comment by jajojon** [comment]
> Hi @jajojon
> Please try a different network, this could be because of your ISP.
> If the problem, please Can you please provide your `flutter doctor -v` your `flutter create mybug --verbose`
> Thank you

Thank you for your response, If I could solve this problem. I had to just upgrade my java jdk version

**Comment by TahaTesser** [comment]
Hi @jajojon 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
