### ISSUE TITLE
Fixing glitchy resizing with macOS embedder

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#64755]
I was playing with macOS embedder in current master and the glitches during resizing immediately caught my attention. 

Current behavior:
<img src="https://i.imgur.com/FwI6jN1.gif" width=370></img>

I looked into this and managed to get the resize behave smoothly as expected:
<img src="https://i.imgur.com/y46EumT.gif" width=370></img>

To get smooth content resizing synchronized with window resizing, two changes are required:

### Rendering and rasterizing must be done synchronously while AppKit view size is being updated

This means holding the platform thread (on macOS it is same as rasterize) while shell obtains the layer tree and then rasterizing the layer tree *before* returning from NSView size update notification.

While waiting for layer tree, the shell should discard any layer tree with wrong size, i.e. possible leftover from previous frame.

### Ensuring that OpenGL context update is synchronized with CoreAnimation transaction

The step before solves half of the problem, but unfortunately it's not a complete solution. The main issue remaining is that `[NSOpenGLContext flushBuffer]` often updates the view too early, because it's not synchronized with core animation transactions.

For metal this should be fixable using `presentsWithTransaction`, sadly opengl has no similar property.

One way to fix this for OpenGL is to create `IOSurface` backed context and set the surface as view layer content. This is synchronized with current transaction. The drawback is, that this possibly relies to `[CALayer setContentsChanged]` call, which is not documented. As far as I can tell, both Safari and Chrome are using this. Alternative to this is using `CGIOSurfaceContextCreateImageReference`. At this point I'm not sure if either of these is mac Appstore safe.

The benefit of using `IOSurface` backed rendering is, that if at any point Flutter supports rendering of only changed part of layer tree, we can use multiple CALayers to simulate partial updates (there is no API for partial redraws on macOS for either OpenGL or Metal). This could make quite a large impact on energy saving when only small part of window is updating.

These changes are currently available in my [macos_resize_experiment](https://github.com/knopp/engine/tree/macos_resize_experiment) branch.

**Comment by markusaksli-nc** [comment]
Hi @knopp 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/44136. There is already a proposed fix for this (see http://flutter.dev/go/double-buffered-window-resize). You can comment there with these insights.
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you
