### ISSUE TITLE
Gold is returning too many expectations in local testing

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#64759]
When running local golden file tests, we retrieve the known expectations from Gold, endpoint: 
```dart
'https://flutter-gold.skia.org/json/expectations/commit/HEAD'
```

If a test fails local comparison, we use the /details endpoint to look up the platform information for the image so we can provide a local visual diff for the right platform. Endpoint: 
```dart
'https://flutter-gold.skia.org/json/details?test=$testName&digest=$expectation'
```

This seems to have broken recently, as when a test fails I get 4 different image results. Upon checking, the expectations endpoint is returning more results than expected.

#### Test: material.text_field_opacity_test.0
 According to the dashboard, there are 2 positive images at head for this test, 1 mac, 1 linux:
https://flutter-gold.skia.org/search?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=false&offset=0&pos=true&query=name%3Dmaterial.text_field_opacity_test.0%26source_type%3Dflutter&sort=desc&unt=false

However, when requesting from the expectations endpoint, there are 12 results.
8 of these are linux, 4 are mac. So when testing locally on my mac, I get 4 failure results all with slightly different diffs. I can't tell which ones are the actual result I care about, so the test is kind of pointless.

```dart
"material.text_field_opacity_test.0":{
  "1805da1bb0c5da23e905b4bfd5bc7214":"positive",
  "257347da1ffb665cab39a88f487ce0f4":"positive",
  "29f30491fcc9c5b4771acd73d5e7744a":"positive",
  "498e60a2c7ae3a8c4af0e5639ef1bfd7":"positive",
  "8242408c872c5ed2ad89712d95ddb20a":"positive",
  "9d4b18f7a9e0e47bd221412131aabb39":"positive",
  "a36c27f3725f583ce57507576fccee0d":"positive",
  "bfe4f22f82ee2b84896979fd938dc39f":"positive",
  "c92a4539703ea888854624b234ed6062":"positive",
  "d81ef31bd08e2cfa59ab703642f62b0d":"positive",
  "e0c781192f3140886d70e98c798dbc4d":"positive",
  "fb66deea579168a24d292001b8a96a14":"positive"
}
```

Here's the results from running this test as mentioned, all of the computed diffs are slightly different. 

```
29f30491fcc9c5b4771acd73d5e7744a,{
  CI: [cirrus, luci],
  Platform: [macos],
  ext: [png],
  name: [material.text_field_opacity_test.0],
  source_type: [flutter]
},
material.text_field_opacity_test.0,
positive
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞══════════════════════
The following TestFailure object was thrown running a test:
  Golden "material.text_field_opacity_test.0.png": Pixel test failed, 5.53% diff detected.
══════════════════════════════════════════════════════════════════════

From Gold:
a36c27f3725f583ce57507576fccee0d, {
  CI: [cirrus, luci],
  Platform: [macos],
  ext: [png],
  name: [material.text_field_opacity_test.0],
  source_type: [flutter]
},
material.text_field_opacity_test.0,
positive
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞══════════════════════
The following TestFailure object was thrown running a test (but after the test had completed):
  Golden "material.text_field_opacity_test.0.png": Pixel test failed, 5.81% diff detected.
══════════════════════════════════════════════════════════════════════

From Gold:
d81ef31bd08e2cfa59ab703642f62b0d, {
  CI: [cirrus, luci],
  Platform: [macos],
  ext: [png],
  name: [material.text_field_opacity_test.0],
  source_type: [flutter]
},
material.text_field_opacity_test.0,
positive
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞══════════════════════
The following TestFailure object was thrown running a test (but after the test had completed):
  Golden "material.text_field_opacity_test.0.png": Pixel test failed, 1.89% diff detected.
══════════════════════════════════════════════════════════════════════

From Gold: 
e0c781192f3140886d70e98c798dbc4d, {
  CI: [cirrus, luci], 
  Platform: [macos], 
  ext: [png], 
  name: [material.text_field_opacity_test.0], 
  source_type: [flutter]
},
material.text_field_opacity_test.0, 
positive
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═══════════════════════
The following TestFailure object was thrown running a test (but after the test had completed):
  Golden "material.text_field_opacity_test.0.png": Pixel test failed, 5.83% diff detected.
═══════════════════════════════════════════════════════════════════════
```

cc/ @darrenaustin @kjlubick

**Comment by kjlubick** [comment]
A better API to use for this is probably /json/latestpositivedigest. Goldctl uses this for some comparison commands; it always returns 0 or 1 digests and it will be a much closer match than grabbing one off of the expectations.

**Comment by Piinks** [comment]
For example: 
```
https://flutter-gold.skia.org/json/latestpositivedigest/,CI=cirrus,Platform=linux,name=cupertino.activityIndicator.inprogress.1.0,source_type=flutter,
```

This'll take a bit of refactoring, but will be a HUGE improvement on performance. Thanks @kjlubick! Will see about getting it out today. :)

**Comment by kjlubick** [comment]
Shoutout to @leandrolovisolo who oversaw and landed this API

**Comment by Piinks** [comment]
Currently blocked on https://github.com/flutter/flutter/issues/64969
Some of our luci recipes appear to have lost goldctl, so not every platform will have a result for the `latestpositivedigest` when we put together the trace id.

**Comment by Piinks** [comment]
Downgrading as this has a workaround in place while waiting on #64982 to land. :)
