### ISSUE TITLE
ValueChanged<T> callbacks don't document the T

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#6475]
The doc generated for a ValueChanged<T> valued callback doesn't reveal the type of its parameter.

For example see onChanged here: https://docs.flutter.io/flutter/material/Checkbox-class.html

**Comment by sethladd** [comment]
Open this over at https://github.com/dart-lang/dartdoc/issues/1263 (at least, I think this is a dartdoc issue)

**Comment by astashov** [comment]
Looking into it
