### ISSUE TITLE
Android emulator in Flutter Infra docs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64751]
@blasten implemented android emulator support for flutter infrastructure and has one test running on presubmit/postsubmit in flutter engine.

To help anyone wanting to reuse android emulator support we need to write some documentation.

**Comment by digiter** [comment]
Triage: what's the expected milestone? @blasten

**Comment by godofredoc** [comment]
@blasten is this something that can be prioritized on your side? having some docs will help when Ricardo starts checking emulator support

**Comment by blasten** [comment]
I'm working on re-enabling this test in the engine, since it got disabled a while back https://github.com/flutter/flutter/issues/90401. 

I will add docs along the way.

**Comment by godofredoc** [comment]
documentation was added to go/flutter-engprod
