### ISSUE TITLE
Test `testSetFlutterViewControllerAfterCreateCanStillDispatchTouchEvents` on engine iOS tests is flaky

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#64763]
The test is flaky. 
Log: 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870773991329664432/+/steps/Host_Tests_for_ios_debug_sim/0/stdout?format=raw

**Comment by cyanglaz** [comment]
@godofredoc I can't reproduce this flake locally (Had about 50k runs). To help debugging, is there a way to get the crash log from the LUCI machine? The above log shows where the file is located:
`/Users/chrome-bot/Library/Developer/Xcode/DerivedData/IosUnitTests-accqtxfeirzsdjbzktfvllceohpz/Logs/Test/Test-IosUnitTests-2020.08.27_16-10-50--0700.xcresult`

**Comment by godofredoc** [comment]
Can you please share the task link?

**Comment by cyanglaz** [comment]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6562

**Comment by godofredoc** [comment]
Seems like that bot only has these two files: 

* Test-IosUnitTests-2020.08.27_23-44-26--0700.xcresult
* Test-IosUnitTests-2020.08.27_20-19-45--0700.xcresult

Would one of those help?

**Comment by cyanglaz** [comment]
Thanks! Looks like it only keeps 2 history log files. I guess the original file when the crash happened was gone. I'll watch for the next failure (if happens) the next couple of weeks and let you know right away so we can get the file. 

Or there might be a way to save more history files?

**Comment by godofredoc** [comment]
If this helps debugging we can make a change to always add those files to the isolated output of the task.

**Comment by cyanglaz** [comment]
Yeah that will definitely help!

**Comment by cyanglaz** [comment]
looks like it's not flaky anymore, closing the issue.
