### ISSUE TITLE
iOS records fewer timeline events than Android does

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#6477]
Our transitions test seems to show that on iOS the timeline records fewer events than it does on Android.

According to the build logs we are running equal number of transition tests ([example](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9mM2NhMTEwNDJlODBjNTZhM2E0Y2E5YTUwZTQ1MTRhMGJhYjM0OWUzDAsSBFRhc2sYgICAgICAoAkM)). However, we are extracting less than half the number recorded timeline events:

Android:

<img width="457" alt="screen shot 2016-10-21 at 4 52 21 pm" src="https://cloud.githubusercontent.com/assets/211513/19615001/41b0cfbe-97af-11e6-8f00-9c055ded7d33.png">

iOS:

<img width="458" alt="screen shot 2016-10-21 at 4 52 29 pm" src="https://cloud.githubusercontent.com/assets/211513/19615003/42fc274c-97af-11e6-93ef-7900cdee5485.png">

I suspect that on iOS we are not respecting the `--trace-startup` flag, which is supposed to make the timeline buffer unlimited.

/cc @chinmaygarde @johnmccutchan @Hixie

**Comment by johnmccutchan** [comment]
@yjbanov `--trace-startup` makes the buffer stop recording new events after it hits a threshold (~8k)

**Comment by yjbanov** [comment]
That should not be the case due to https://github.com/flutter/engine/blob/f07c32d24716f91cbce3b3157b48b294979e9ea2/runtime/dart_init.cc#L619.

There was a relatively recent change: https://github.com/flutter/engine/commit/d35e0805e05bfe2bc555749b094a00dc93db0f12#diff-0dd7d4ac807a12f5a5c27296058b990a. But it looks as if it should preserve behavior.

**Comment by chinmaygarde** [comment]
I verified that that `--trace-startup` does switched on the endless trace recorder on iOS. 
![screen shot 2016-11-07 at 2 34 17 pm](https://cloud.githubusercontent.com/assets/44085/20078949/64044f46-a4f7-11e6-8a8f-ec3f75fbbec8.png)

**Comment by chinmaygarde** [comment]
@yjbanov and I investigated this some more and tried to reproduce it locally. We did see one failure initially but were subsequently unable to reproduce the same with more logging.

We have decided to dump the entire timeline to the logs and wait for another failure. That way we will have more data to further this investigation. So far, I am blocked.

**Comment by yjbanov** [comment]
@Hixie Could you please remove the "old: bug" label? This is still happening.

**Comment by yjbanov** [comment]
We are now getting the full timeline from iOS10/Xcode8 so it's not an issue for our own devicelab. It's still an issue in iOS9/Xcode7. Closing until someone asks for it.
