### ISSUE TITLE
Resize the app window will cause framework crash

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#64786]
![20200828_180149](https://user-images.githubusercontent.com/61075224/91548876-aef66a80-e958-11ea-8aa9-b371e27efd97.gif)
### Sample code
```
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
//        initialIndex: 1,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              TestWidget(0, Colors.red),
              TestWidget(1, Colors.yellow),
              TestWidget(2, Colors.blue),
            ],
          ),
        ),
      ),
    );
  }
}

class TestWidget extends StatelessWidget {
  final Color color;
  final int index;
  TestWidget(this.index, this.color);
  @override
  Widget build(BuildContext context) {
    print('call build $index');
    return ColoredBox(color: color);
  }
}
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 1.00 pixels on the bottom.

The relevant error-causing widget was: 
  AppBar file:///D:/My%20Documents/Desktop/flutter_app_demo/lib/main.dart:15:19
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#92928 relayoutBoundary=up9 OVERFLOWING
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=392.0, 0.0<=h<=47.0)
...  size: Size(392.0, 47.0)
...  direction: vertical
...  mainAxisAlignment: spaceBetween
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

```
Launching lib\main.dart on Windows in debug mode...
flutter: call build 0
Connecting to VM Service at ws://127.0.0.1:52698/h_SiziZ4hQ8=/ws

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during layout:[39;49m
A RenderFlex overflowed by 1.6 pixels on the bottom.

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mAppBar[39;49m
[38;5;244mThe overflowing RenderFlex has an orientation of Axis.vertical.[39;49m
[38;5;244mThe edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.[39;49m

[38;5;248mConsider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.[39;49m
[38;5;248mThis is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.[39;49m

[38;5;244mThe specific RenderFlex in question is: RenderFlex#6a7a8 relayoutBoundary=up9 OVERFLOWING[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.105, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.105 at C:\Code\flutter_master
    • Framework revision cad4d1333e (10 hours ago), 2020-08-27 17:48:05 -0700
    • Engine revision 77dd1c05b9
    • Dart version 2.10.0 (build 2.10.0-67.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
You've made the window smaller than the content without providing any kind of overflow semantics. As it says in the output:

> This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

This is an error in your application, not Flutter.

**Comment by xu-baolin** [comment]
This is a demo from Flutter official website, but it will crash on windows without any documentary. Maybe we can do more better, such as limited the window size rather than crash.

**Comment by stuartmorgan** [comment]
It isn't crashing, it's throwing an exception clearly indicating that there is too much content for the window size.

If you want to set a minimum window size when locally turning the sample into a runnable Windows application you are welcome to do so.

**Comment by xu-baolin** [comment]
Sorry for the inaccurate description ：）

**Comment by xu-baolin** [comment]
Does it mean that we can't use flex widgets on Windows platforms like other platforms?

**Comment by stuartmorgan** [comment]
This has nothing to do with Windows vs other platforms. You can get the same exception on mobile by having something with a minimum width larger than the device's screen and not adding any clipping or scrolling. Or by having a widget that is too large for its container.
