### ISSUE TITLE
`flutter create` should fail if called from inside the flutter repo

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6480]
We saw this happen in the usability study today (P2), and it has some subtle negative effects later, for example they ended up having the wrong set of analyzer warnings.

**Comment by sethladd** [comment]
Should we not allow someone to create a new project inside a non-empty directory? Seems like the safe thing to do.

**Comment by abarth** [comment]
> Should we not allow someone to create a new project inside a non-empty directory? Seems like the safe thing to do.

Some error messages recommend doing that to restore missing files.
