### ISSUE TITLE
too many postitianal arguement 

### ISSUE THREAD

**Issue by Fard433n** [flutter/flutter#64807]
error: Too many positional arguments: 1 expected, but 2 found. (extra_positional_arguments_could_be_named at [destini_challenge_starting] lib\main.dart:44)

**Comment by SirusCodes** [comment]
This error means you are passing an extra argument into the constructor.
Send your code.

**Comment by Fard433n** [comment]
Thank you for your response I found that error before thanks a lot for
responding

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
