### ISSUE TITLE
[Web] Use workbox-strategies for flutter web

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#64816]
# Use Case

[Worbox Strategies](https://developers.google.com/web/tools/workbox/modules/workbox-strategies) can be very useful while developing for the web, especially for PWAs. Flutter already implements the use of service workers, but it can be customized at a greater level and can improve the efficiency of flutter web apps with the various stragies provided by workbox.

# Implementation

Arguments can be passed to the flutter command line tool build web command defining the prebuilt strategy to be used.
OR
The workbox API can be directly integrated into flutter.

**Comment by sidrao2006** [comment]
cc @dnfield

**Comment by jonahwilliams** [comment]
@sidrao2006 if you want to write your own service worker you are in no way obligated to use the autogenerated one (which is really just an 80% solution).

We have discussed supporting an online-first mode too FWIW, but we're not going to provide "direct integration" of another JavaScript service worker library.

**Comment by jonahwilliams** [comment]
If you have _specific_ features you would like integrated into the service worker, then by all means file issues for those and we can consider them.

**Comment by sidrao2006** [comment]
@jonahwilliams thanks for replying.
Writing my own service worker is a tedious job. If flutter auto generates the service worker using workbox strategies, the work will be efficient as well as easy. Flutter can optimize the files as needed which is specified during the build

**Comment by jonahwilliams** [comment]
"workbox strategies" is not a specific feature request though, what sort of functionality are you looking for?

**Comment by sidrao2006** [comment]
Well, @jonahwilliams different projects have different needs. I just want to be able to power all the projects with the best optimised service worker easily.

**Comment by jonahwilliams** [comment]
We're not going to blanket implement different service worker caching strategies unless there is some demand for them. Just because something was implemented elsewhere does not provide evidence that it will be useful in Flutter

**Comment by sidrao2006** [comment]
Ok thanks a lot

**Comment by sidrao2006** [comment]
@jonahwilliams , there is now an implementation of `--pwa-strategy`. So, will workbox strategies be implemented as well?
