### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/file.mp4, null

### ISSUE THREAD

**Issue by Zeeshan-progs** [flutter/flutter#64815]
Video Player not loading video

**Comment by Zeeshan-progs** [comment]
![Screenshot (630)](https://user-images.githubusercontent.com/67018643/91605225-bedc7180-e98d-11ea-97eb-8e8b34fb5437.png)

**Comment by sidrao2006** [comment]
Hey @Zeeshan-progs , this looks like a source error. Can you please check your video file source.
If that doesn't solve your problem, can you please provide the output of `flutter doctor -v`
Thank you

**Comment by Zeeshan-progs** [comment]
> Hey @Zeeshan-progs , this looks like a source error. Can you please check your video file source.
> If that doesn't solve your problem, can you please provide the output of `flutter doctor -v`
> Thank you




flutter doctor and file din't  have any error

**Comment by sidrao2006** [comment]
Ok, as mentioned in your error logs it was a source error. Can you please look into that

**Comment by darshankawar** [comment]
Hi @Zeeshan-progs,
The exception says it can't find the file specified. I see there's space in the video file you are trying to play, `mirzapur 2.mp4`. Try to remove space from original file name and then in `pubspec.yaml` and finally use the updated file name in your code and try again.
Also this seems to be code implementation issue and not Flutter issue. Closing.
If you disagree, write in comments and I'll reopen.
Thanks.
