### ISSUE TITLE
Undocumented cloud storage bucket "flutter-catalog" with public access

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#64811]
We have to audit and justify any cloud buckets we own with public access, and it is unclear what `gs://flutter-catalog` is and if it's necessary.

My guess is that one of our CI tests in the framework are uploading screenshots of the `flutter-catalog` example app for each framework commit:

```
$ gsutil ls gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/animated_list.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/animated_list_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/app_bar_bottom.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/app_bar_bottom_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/basic_app_bar.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/basic_app_bar_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/custom_a11y_traversal.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/custom_a11y_traversal_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/custom_semantics.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/custom_semantics_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/expansion_tile_sample.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/expansion_tile_sample_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_animated_list.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_animated_list_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_app_bar_bottom.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_app_bar_bottom_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_basic_app_bar.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_basic_app_bar_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_custom_a11y_traversal.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_custom_a11y_traversal_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_custom_semantics.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_custom_semantics_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_expansion_tile_sample.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_expansion_tile_sample_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_tabbed_app_bar.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/ios_tabbed_app_bar_small.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/tabbed_app_bar.png
gs://flutter-catalog/2ae25cc2d725ff9875cfcfdc8ca3996eb39db13a/tabbed_app_bar_small.png
```

**Comment by christopherfujino** [comment]
cc @godofredoc

**Comment by dnfield** [comment]
It's an integration test that @HansMuller wrote a ways back. See dev/devicelab/tasks/sample_catalog_generator.dart

I have no idea if it's still necessary.

**Comment by christopherfujino** [comment]
Thanks @dnfield 

Found two PRs for reference:
https://github.com/flutter/flutter/pull/10462
https://github.com/flutter/flutter/pull/10303

@HansMuller can you give context around why we're uploading the screenshots to cloud storage, and if we ever use them?

**Comment by christopherfujino** [comment]
Per Hans in chat, "The original idea was that the sample catalog on our web site would include an up to date screenshot for each app. It looks like the sample catalog page has been replaced by a link to a different "curated" sample catalog https://flutter.dev/docs/catalog/samples"

So @godofredoc we're unblocked to delete this bucket :)

**Comment by godofredoc** [comment]
Thanks @christopherfujino  and @HansMuller for looking at this. Removed the bucket.

**Comment by godofredoc** [comment]
@christopherfujino @HansMuller seems like the test is still running and uploading to the bucket.

**Comment by christopherfujino** [comment]
> @christopherfujino @HansMuller seems like the test is still running and uploading to the bucket.

Oops, yeah, sorry, skipped a step :). Lemme make a PR to stop uploading.

**Comment by christopherfujino** [comment]
@HansMuller I'm deleting the uploading logic from this test. If we stop uploading the images, does this test still have value as a smoke test, or should we delete it altogether?

**Comment by dnfield** [comment]
If we can avoid running the test it would free up capacity in the devicelab...

**Comment by christopherfujino** [comment]
> If we can avoid running the test it would free up capacity in the devicelab...

agreed

**Comment by HansMuller** [comment]
@christopherfujino - there was a time when it seemed to have some value as a smoke test. We do run all of the gallery demos as part of the normal unit tests, so I think it's safe to drop this.

**Comment by digiter** [comment]
Triage: we have deleted the bucket.

**Comment by HansMuller** [comment]
NICE
