### ISSUE TITLE
ChangeNotifier takes too long when removing many listeners.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#64817]
I need to display thousands of widgets.

If each widget contains a Tooltip, which adds and removes a listener, removing all widgets simultaneously takes longer than it should. Each tooltips removeListener call has to iterate through all listeners to find the first listener. 

#64818 fixes that.

**Comment by Hixie** [comment]
Rendering thousands of widgets with tooltips is a lot more than the framework was designed for. Can you elaborate on what you are doing?

For context, when we did something similar for our dashboard (which is a TV-sized display with a grid of hundreds of cells showing test results for each recent commit), we designed it to avoid rendering separate widgets for each cell.

**Comment by modulovalue** [comment]
> Can you elaborate on what you are doing?

I'm drawing interactive class diagrams on a figma-like canvas where everything with a comment should come with a tooltip. 

> For context, when we did something similar for our dashboard (which is a TV-sized display with a grid of hundreds of cells showing test results for each recent commit), we designed it to avoid rendering separate widgets for each cell.

The issue is not about rendering. This is about widgets having the ability to add listeners, that will always have to be removed (In batches during their disposal!), and since removeListener is expensive that has the ability to be expensive too.

In this case, every tooltip is [adding a mouse listener](https://github.com/flutter/flutter/blob/d69ae36398157fe9a414e8e0158d70ffa2958a2d/packages/flutter/lib/src/material/tooltip.dart#L214) that is removed when [it is disposed](https://github.com/flutter/flutter/blob/d69ae36398157fe9a414e8e0158d70ffa2958a2d/packages/flutter/lib/src/material/tooltip.dart#L356). Closing a widget with a dozen classes, but where each class may also have dozens of commented properties, leads to a noticeable lag.

<img width="1501" alt="Bildschirmfoto 2020-09-03 um 03 47 44" src="https://user-images.githubusercontent.com/24444584/92062118-3cdab700-ed98-11ea-93b9-92c11fe1222d.png">

**Comment by Hixie** [comment]
In that picture I see two widgets, maybe 20. If that is being rendered using 1000s of widgets then that is an architectural problem which will lead to many issues beyond just addListener being expensive.

**Comment by modulovalue** [comment]
> In that picture I see two widgets, maybe 20. If that is being rendered using 1000s 

I wasn't too clear by what I meant saying "thousands of widgets". I meant to say potential nodes in the element tree. There are no problems here.


> which will lead to many issues beyond just addListener being expensive.

No, this issue is not about addListener, please read the issue statement again.
 - addListener is constant i.e. adding a thousand listeners will take 1000 units of time **that is optimal and good**
 - removeListener is linear i.e. removing a thousand listeners will take in the worst-case **500500** units of time **that is not good** and that's what this is about. The PR fixes that to also be constant and optimal.

**Comment by Hixie** [comment]
I understand, what I'm saying is that adding a thousand listeners is fundamentally a misuse of the API. There should never be 1000 distinct things on the screen at the same time that care about a particular data point. It shouldn't matter that removing 1000 listeners is expensive, because one should never need to remove 1000 listeners.

**Comment by modulovalue** [comment]
See #64818
