### ISSUE TITLE
Cancel button behavior for showdatepicker function

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6483]
It looks like the showdatepicker function returns picked ?? initialDate;
When using the function, is there anyway to tell whether the user select the initial date or hit cancel button?

**Comment by abarth** [comment]
We should probably return null and let the client decide to fall back to the initial date.

**Comment by warent** [comment]
@abarth Appears this also happens with showTimePicker. Should they both return null instead of coalescing the initial?

**Comment by abarth** [comment]
Yeah, they should be consistent.

**Comment by warent** [comment]
Seems like a subtly breaking change, but the PR is up now in case y'all decided to go for it :)

**Comment by abarth** [comment]
Yeah, we're still in the stage of the project where we're willing to make these sorts of breaking changes.  (Hence the API stability label.)  It's probably worth an email to flutter-dev once the patch lands that explains the API change.
