### ISSUE TITLE
Extract cirrus data

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#64844]
We need to extract cirrus data to detect flakiness per task for the last 3 months:

* Total flakiness per commit
* Total flakiness per task
* Queue time per task
* Execution time task

Ideally we should write this data to bigquery for data analysis

**Comment by digiter** [comment]
@keyonghan If I save the data to BigQuery, could you advise on how to store it? Do I reuse existing tables or create new datasets and tables?

**Comment by keyonghan** [comment]
> @keyonghan If I save the data to BigQuery, could you advise on how to store it? Do I reuse existing tables or create new datasets and tables?

Either `flutter-dashboard` or `flutter-infra` should work. I have been saving/querying data with `flutter-dashboard`. You can create a `cirrus` dataset inside.

**Comment by digiter** [comment]
From @godofredoc we want to implement it in the flutter/cocoon repository.

**Comment by godofredoc** [comment]
What I meant was to upload the go code you are using for extracting the data to a location inside flutter/cocoon so that we can reuse it later if needed.

**Comment by digiter** [comment]
I have downloaded the data from Cirrus to local disk, next step is to upload it to big query tables.

**Comment by digiter** [comment]
Cirrus data (range from 01/01/2020 to present) has been saved to `flutter-dashboard` in two tables: cirrus.Build, cirrus.Task.

**Comment by digiter** [comment]
The requested charts have been added to data studio.

<img width="1092" alt="Screen Shot 2020-09-30 at 17 02 28" src="https://user-images.githubusercontent.com/6259181/94751990-d026ee00-033e-11eb-9349-d94cb6126f95.png">

<img width="1199" alt="Screen Shot 2020-09-30 at 17 02 56" src="https://user-images.githubusercontent.com/6259181/94751992-d1f0b180-033e-11eb-9da6-ed7c7dc746a8.png">
