### ISSUE TITLE
[url_launcher] Error: No named parameter with the name 'webOnlyWindowName'

### ISSUE THREAD

**Issue by evolvingkid** [flutter/flutter#64863]
../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.1/lib/url_launcher.dart:100:5: Error: No named parameter with the name 'webOnlyWindowName'.
    webOnlyWindowName: webOnlyWindowName,  

This happen and app crashes when i include url launcher

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/plugins/pull/2979#issuecomment-683304067

**Comment by KholofeloMoyaba** [comment]
The following commands resolved it for me.
```
flutter clean
flutter pub upgrade
```

Well, I think the important one is `flutter pub upgrade` here. But cleaning does help especially when plugins are updated.

**Comment by evolvingkid** [comment]
Ya i did that command and also done pub cache repair command to. No change. But after sometime the app work without any issue on the command line but as soon as page are loaded where i import package app just stuck.

**Comment by sanekyy** [comment]
same issue

**Comment by ferraridamiano** [comment]
Upgrading url_launcher from 5.5.0 to 5.5.1 solved the issue for me

**Comment by TahaTesser** [comment]
Hi @evolvingkid 
This seems to be fixed in [url_launcher 5.5.1](https://pub.dev/packages/url_launcher/changelog#551)
Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by stuartmorgan** [comment]
This is not fixed. The `url_launcher_platform_interface` dependency is still wrong as described in the comment I linked to above

**Comment by TahaTesser** [comment]
@stuartmorgan  
My bad,  thanks for reopening the issue.

**Comment by ditman** [comment]
@stuartmorgan you're right, I'm bumping the dependencies of the url_launcher packages.

**Comment by balvinderz** [comment]
sorry for creating such a big issue . @ditman @cyanglaz

**Comment by ditman** [comment]
@balvinderz no problem! We all are learning about the plugin federation ;)

**Comment by ditman** [comment]
Here's the PR addressing the dependencies: https://github.com/flutter/plugins/pull/2984

**Comment by ditman** [comment]
`url_launcher: ^5.5.2` should mitigate this issue. I'm closing the issue, please reopen if you're still having issues!
