### ISSUE TITLE
Error screen on route change (pop or push) - observed whenever video player fails

### ISSUE THREAD

**Issue by pnwanno** [flutter/flutter#64868]
Whenever video player fails in page (though the failure is corrected on the page and the player continues), once I leave that
page, I get the "red screen" blank page error on the new page routed to.

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5154 pos 14: '() {

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _FocusMarker(dirty):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5154 pos 14: '() {
        // check that it really is our descendant
        Element ancestor = dependent._parent;
        while (ancestor != this && ancestor != null)
          ancestor = ancestor._parent;
        return ancestor == this;
      }()': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5017 pos 14: '_dependents.isEmpty': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5017 pos 14: '_dependents.isEmpty': is not true.

Another exception was thrown: Tried to build dirty widget in the wrong build scope.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Tried to build dirty widget in the wrong build scope.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5017 pos 14: '_dependents.isEmpty': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#351fe](state: OverlayState#fce76(entries: [OverlayEntry#965a9(opaque: true; maintainState: false), OverlayEntry#6fab8(opaque: false; maintainState: true), OverlayEntry#22712(opaque: true; maintainState: false), OverlayEntry#74f67(opaque: false; maintainState: true), OverlayEntry#80197(opaque: false; maintainState: false), OverlayEntry#9c207(opaque: false; maintainState: false), OverlayEntry#93f9b(opaque: true; maintainState: false), OverlayEntry#b6064(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5017 pos 14: '_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-GB)
    • Flutter version 1.20.2 at C:\flutter_src\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android_proj\android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android_proj\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.0)
    • VS Code at C:\Users\COMMUNICATION UNIT2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • TECNO CD7 (mobile) • 192.168.1.26:2020 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by darshankawar** [comment]
Hi @pnwanno,
Please provide a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
