### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by sachanayush47** [flutter/flutter#64884]
![IMG_20200830_110708_229](https://user-images.githubusercontent.com/30933398/91652058-37881e80-eab1-11ea-99e3-25576155e498.jpg)
![IMG_20200830_110711_495](https://user-images.githubusercontent.com/30933398/91652059-3951e200-eab1-11ea-963a-3e9c5a3f9542.jpg)

Java jdk 1.8 installed and added to java home but still issue persist.
Tried reinstalling all the things but didn't work.
Pls dont close this issue. It is not duplicate.

**Comment by iapicca** [comment]
dupe https://github.com/flutter/flutter/issues/31116

**Comment by darshankawar** [comment]
Hi @sachanayush47,
I see a similar [issue](https://github.com/flutter/flutter/issues/51670) that describes your case which has several solutions that you can try.
Can you try [this](https://github.com/flutter/flutter/issues/51670#issuecomment-592943797) solution from it and see if it works for you ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
