### ISSUE TITLE
Expose the ScrollController of a TabBar

### ISSUE THREAD

**Issue by anirudhb** [flutter/flutter#64880]
## Use case

Exposing the ScrollController of a TabBar would allow for custom scrolling behavior, as well as things like putting a specific tab into view, changing the scrolling physics etc.

## Proposal

Expose the ScrollController of a TabBar / allow the user to provide their own.

**Comment by ajain-bst** [comment]
I need this for doing a _fake scroll back_ on the tab bar when a page is shown, to indicate that the tab bar is scrollable. 
Basically, scrolling ahead just a little then scrolling back to the initial position when the page loads.

**Comment by Yivan000** [comment]
I also need this to do custom behavior when the `TabBar` (not `TabBarView` is scrolled in certain positions. Also, exposing the ScrollController makes it possible for a `Scrollbar` widget to show and customize its scrollbar without funkiness.
