### ISSUE TITLE
Support for OpenGL Bindings for iOS and Android

### ISSUE THREAD

**Issue by premingiet** [flutter/flutter#64882]
## Use case

currently i cant use any opengl drawing. Opengl binding for android and ios is very much needed.
I am trying to do some local video frame manipulation. But i dont see any video encoders or decoders available for flutter. Also i cant draw any video frames directly from flutter and extract it as surface texture for further manipulation. I have no way to do it in flutter.

## Proposal

Opengl binding for flutter would be great. Also some video encoders and decoders for flutter texture would be great, so we can draw something and encode it to a video.

**Comment by chinmaygarde** [comment]
You should be able to create your own FFI bindings to OpenGL and generate your own frames. For video encoding and decoding, you will have to drop back down to platform API. However, using these bindings to affect the way Flutter renders frames is probably something we will not be able to expose. Flutter does not use OpenGL on all platforms and is currently an implementation detail.
