### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by shameemreza** [flutter/flutter#64887]
Everythign seems working in my app. I build the android app successfully, but while I am trtying to build usinx XCODE, I am getting:

> Command PhaseScriptExecution failed with a nonzero exit code

I tried many ways, such as:

- Flutter Clean
- POD install
- Legacy Build

![Image of PhaseScriptExecution](https://i.postimg.cc/7PdNtwvN/Screen-Shot-2020-08-29-at-8-58-30-PM.png)

I also followed guide provided here: https://github.com/flutter/flutter/issues/56507

Thanks and will be great help if anyone can assist.

**Comment by TahaTesser** [comment]
Hi @shameemreza 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by devrajraut** [comment]
@shameemreza Could you pls tell us what the Migration issue was? Im having the same issue and I'm not able to run my App on the Simulator.

**Comment by shameemreza** [comment]
@devrajraut  It was IOS migration issue. I just follwoed this: https://flutter.dev/docs/development/ios-project-migration
