### ISSUE TITLE
PageView conflict with TabBarView during orientation change

### ISSUE THREAD

**Issue by Sid0518** [flutter/flutter#64899]
I ran into a particularly specific problem, but the relevant code is too big to provide here, so I'll describe my widget tree as best as I can, and attach appropriate screenshots.

I have a Scaffold with a PageView as the body, along with a BottomNavigationBar which is used to change the PageView's page. The Scaffold's AppBar also updates accordingly when the BottomNavigationBar is used to change pages.
One of my PageView pages is a TabBarView with 3 tabs, so my main Scaffold's AppBar is rebuilt with a TabBar when the user navigates to this TabBarView page. Other pages do not have this, so they have the basic AppBar.

![TabBarView](https://user-images.githubusercontent.com/30648642/91659832-f7945c00-eaef-11ea-8752-44cb652a9afa.png)
![Page next to TabBarView](https://user-images.githubusercontent.com/30648642/91659825-f5ca9880-eaef-11ea-8377-6d1340db199c.png)

Now here's the problem: 
When the user is on the TabBarView page in portrait mode, and the screen is rotated to landscape, the _PageView advances one page forward by itself_, so the wrong page gets aligned with the TabBar, so it gets drawn incorrectly. 

![TabBarView after screen rotation](https://user-images.githubusercontent.com/30648642/91659830-f6fbc580-eaef-11ea-96cc-305838b44920.png)

The 'ard' sticking out from the left is a portion of the 'TODO: Dashboard' text which is supposed to be drawn on the next page.

This _only ever happens during a screen rotation from portrait to landscape_, and that too _only while on the TabBarView page_. A landscape to portrait rotation _on the same TabBarView page_ does **not** glitch out like this, and every other page in the PageView goes through a correct portrait to landscape rotation.
No errors are raised by Flutter itself anywhere during this. I would've expected Flutter to raise an error if it was told to draw a TabBar which does not have a TabBarView below it.

I have managed to find a workaround by wrapping my PageView in an OrientationBuilder, which rebuilds the PageView on orientation change, and then I manually call jumpToPage on its PageController to set the correct page number (which I know because it's the same as the currentIndex of the BottomNavigationBar).

I don't require assistance to fix this bug (since I have fixed it myself for now), instead, I only wanted to point out this issue, so the Flutter team could look into it.

**Comment by pedromassangocode** [comment]
Hi @Sid0518 

Possible related to https://github.com/flutter/flutter/issues/63935.

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
