### ISSUE TITLE
Minor issues with tab animations

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#649]
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFZWZ6dndJX09Zak0/components_tabs_tabtouchtarget.webm
- [ ] The ink well effects should go all the way to the bottom of the tab bar, even under the indicator.
- [ ] The text color should fade out a little for non-selected tabs. This color animates as tabs are switched.
- [ ] The indicator grows a little while it's moving, then shrinks again as it arrives at its target. (Note that near the end of the video though it's small on its way back? I don't quite understand what's going on here.)
- [ ] On mobile, there should be no padding on the left and right edges between the tabs and the edge of the screen. (Presumably the toolbar padding should go only around the first and second rows, not the tab bar row.)

**Comment by zoechi** [comment]
> The indicator grows a little while it's moving

I'm not able to see this in the linked video.
I think the tabs in the gallery follow the other bullets.

**Comment by TahaTesser** [comment]
Looking at the flutter gallery app, it shows follow all bullet points mentioned. 
We have tabs example https://flutter.dev/docs/cookbook/design/tabs too
Closing, as resolved. If you disagree, please write in the comments and I will reopen it.
Thank you
