### ISSUE TITLE
Build input file cannot be found: ios/Flutter/AppFrameworkInfo.plist

### ISSUE THREAD

**Issue by shameemreza** [flutter/flutter#64905]
Anyone know how to resolve it.

Build input file cannot be found: '/Users/user176647/Desktop/discountdeal/ios/Flutter/AppFrameworkInfo.plist'

**Comment by TahaTesser** [comment]
Hi @shameemreza 
Please try this possible [solution](https://developer.apple.com/forums/thread/116142) 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by shameemreza** [comment]
I resolved the issue. There was others problem. Thanks
