### ISSUE TITLE
Unable to use constraint layout in splash screen & Also unable to set size of <item> in <layer-list> of xml 

### ISSUE THREAD

**Issue by basantsingh-os** [flutter/flutter#64909]
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/black" />

    
    <item
    android:layout_height="x dp"
    android:layout_width="y dp"
    android:gravity="center"
    android:drawable="@drawable/logo_0
    />

    <item
    android:layout_height="x dp"
    android:layout_width="y dp"
    android:gravity="bottom|left"
    android:drawable="@drawable/logo_1
    />

    <item
     android:layout_height="x dp"
    android:layout_width="y dp"
    android:gravity="bottom|right"
    android:drawable="@drawable/logo_2
    />

    
</layer-list>

having difficulty in designing splash screen.
note logo_0,logo_1,logo_2 are imported svgs.
Thus XML
So <bitmap> in <item> will not work

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
