### ISSUE TITLE
Allow PopupMenuItem's width to be set to  full width of the screen

### ISSUE THREAD

**Issue by misskter** [flutter/flutter#64918]
When I use the showMenu method, I set the width of child to MediaQuery.of (context). size.width But it doesn't work. I see that it is implemented in the source code like this
```dart
const double _kMenuMaxWidth = 5.0 * _kMenuWidthStep ; 
const double _kMenuMinWidth = 2.0 * _kMenuWidthStep ; 
const double _kMenuVerticalPadding = 8.0 ; 
const double _kMenuWidthStep = 56.0 ; 
... 
...
_PopupMenu < T > 类扩展StatelessWidget {
    最终Widget 子= ConstrainedBox （
约束：const BoxConstraints （minWidth ：_kMenuMinWidth ，maxWidth ：_kMenuMaxWidth ，），... ...      
}，
```
But I want it to be the maximum width of my screen

**Comment by TahaTesser** [comment]
Hi @misskter 
`_kMenuMinWidth` is a private source class variable, not sure why you using that in your code.
You can get width of device  using `minWidth: MediaQuery.of(context).size.width` 
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          color: Colors.blue,
          constraints:
              BoxConstraints(minWidth: MediaQuery.of(context).size.width),
          child: Text('Hello World',
              style: TextStyle(
                color: Colors.white,
              )),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

If you think this is a bug, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by misskter** [comment]
```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          child: Text('Material App Bar'),
          onTap: () {
            showMenu(
              context: context,
              position: RelativeRect.fromLTRB(0, 50, 0, 0),
              items: [
                PopupMenuItem(
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 30,
                    child: Text("one"),
                  ),
                ),
              ],
            );
          },
        ),
      ),
      body: Center(
        child: Container(
          color: Colors.blue,
          constraints: BoxConstraints(minWidth: MediaQuery.of(context).size.width),
          child: Text('Hello World',
              style: TextStyle(
                color: Colors.white,
              )),
        ),
      ),
    );
  }
}
````
My requirement is that the width of the pop-up menu is MediaQuery.of (context). size.width But the end result is not what I want

**Comment by TahaTesser** [comment]
This doesn't seem to be possible to change width of `PopupMenuItem` to the full width of the screen
However, this is not in Material Design guidelines https://material.io/components/menus#behavior

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: GestureDetector(
          child: Text('Material App Bar'),
          onTap: () {
            showMenu(
              context: context,
              position: RelativeRect.fromLTRB(0, 50, 0, 0),
              items: [
                PopupMenuItem(
                  child: Container(
                    width: double.maxFinite,
                    height: 30,
                    child: Text("one"),
                  ),
                ),
              ],
            );
          },
        ),
        actions: [],
      ),
      body: Center(
        child: Column(
          children: [
            Container(
              color: Colors.blue,
              constraints:
                  BoxConstraints(minWidth: MediaQuery.of(context).size.width),
              child: Text('Hello World',
                  style: TextStyle(
                    color: Colors.white,
                  )),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 216dee60c0 (2 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

</details>

**Comment by misskter** [comment]
Or you can add a parameter to showmenu to set the width, Thank you very much

**Comment by hyobbb** [comment]
I don't understand why this constraint exist. As the height of the widget can be set the width also should be able to set by user.

**Comment by SteveAlexander** [comment]
I just spent 20 mins looking into this, trying various workarounds and trying what seemed like obvious and straightforward things to change the width of the popup menu.

As it is, in my app, I have text items that are wrapping unnecessarily, and look pretty bad.

I guess I'll write my own pop up menu to work around this. This is pretty irritating though! Reiterating @hyobbb, I can't see a good reason for the width to be constrained with a constant value like this.

**Comment by andrden** [comment]
This limit is somewhat wrong for Desktop. 
https://material.io/components/menus#specs
At the very bottom Dropdown (Desktop)
It reads 320 at the drawing.
As my designer made a menu of width 300 for me I'll also have to write my own popup menu because of this bug

**Comment by inceptusp** [comment]
Adding on `This limit is somewhat wrong for Desktop.` stated by andrden: Some Google Docs menus are bigger than the fixed flutter width... As an example:
![image](https://user-images.githubusercontent.com/17789155/113523584-b335d680-957e-11eb-93e2-d6106d1ffef8.png)
This menu have a width of, at least, 480px which is 200px above the applied constraint...

**Comment by Bad-YX** [comment]
i think u sould make width: double.infinity,
> 
> 
> ```
> class Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: GestureDetector(
>           child: Text('Material App Bar'),
>           onTap: () {
>             showMenu(
>               context: context,
>               position: RelativeRect.fromLTRB(0, 50, 0, 0),
>               items: [
>                 PopupMenuItem(
>                   child: Container(
>                     width: MediaQuery.of(context).size.width,
>                     height: 30,
>                     child: Text("one"),
>                   ),
>                 ),
>               ],
>             );
>           },
>         ),
>       ),
>       body: Center(
>         child: Container(
>           color: Colors.blue,
>           constraints: BoxConstraints(minWidth: MediaQuery.of(context).size.width),
>           child: Text('Hello World',
>               style: TextStyle(
>                 color: Colors.white,
>               )),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> ```
> [√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.10240], locale zh-CN)
>     • Flutter version 1.20.2 at D:\environment\flutter
>     • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
>     • Engine revision 9d5b21729f
>     • Dart version 2.9.1
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at D:\environment\androidsdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = D:\environment\androidsdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 48.1.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] Connected device (2 available)
>     • Redmi 6 (mobile)                   • e677d8177d13  • android-arm • Android 8.1.0 (API 27)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
> 
> • No issues found!
> ```
> 
> My requirement is that the width of the pop-up menu is MediaQuery.of (context). size.width But the end result is not what I want, Unless I add maxwidth:_ If you comment out kmenumaxwidth, you can set the width of the menu to the width I want

**Comment by kirill-21** [comment]
Any workaround? How to set the width of showDialog more, than default? Just wrapping the widget inside of PopupMenuItem into a container with width does not help

**Comment by sgehrman** [comment]
Very surprised that menus are still unusable on desktop/web.  It's pretty simple to copy the source and change those values, but why do we have to do this?

**Comment by purutechno** [comment]
I'd created another issue for the same problem which is closed mentioning that the issue is already open.
That's hilarious : 

https://github.com/flutter/flutter/issues/97699

**Comment by purutechno** [comment]
No Update till now Supermans!   🚀

**Comment by purutechno** [comment]
> This limit is somewhat wrong for Desktop. https://material.io/components/menus#specs At the very bottom Dropdown (Desktop) It reads 320 at the drawing. As my designer made a menu of width 300 for me I'll also have to write my own popup menu because of this bug

Could you update us with your solution?

**Comment by purutechno** [comment]
I saw this guy's response so far :

https://github.com/flutter/flutter/issues/41032#issuecomment-534991065
