### ISSUE TITLE
Crash return from oauth2 using google maps

### ISSUE THREAD

**Issue by afedor** [flutter/flutter#64910]
I have a simple app that uses oauth2_client and google_maps_flutter
[oauth2_crash.patch.zip](https://github.com/flutter/flutter/files/5147465/oauth2_crash.patch.zip)

.  When I return from an oauth authentication from a browser, the application crashes.  Note that I am running flutter 1.20.2.  The crash only occurs on Android, not in iOS and it does NOT occur in flutter 1.17.5.

## Steps to Reproduce

- Create a new flutter project called oauth2_crash
- Apply the patch file attached to this project
- Add your own Google Maps API key (no crash unless Google Maps works)
- Compile and run on Androdi device/simulator
- Click the login button
- Wait for oauth to load a browser, then cancel the login using the "X"
- NOTE: App will crash here when activating again.

**Expected results:** 
App returns the "login" screen

**Actual results:** 
Crash

<details>
  <summary>Logs</summary>

```
Too long to include here see attached
[flutter_run_verbose.zip](https://github.com/flutter/flutter/files/5147488/flutter_run_verbose.zip)

```

```
afedor@t1v-techaf oauth2_crash % flutter analyze
Analyzing oauth2_crash...                                               
No issues found! (ran in 4.9s)
```

```
afedor@t1v-techaf oauth2_crash % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/afedor/Source/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/afedor/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Hi @afedor,
Since you are using `oauth2_client` plugin which is a 3rd party, do you think the plugin may not be compatible with latest Flutter version ?
Also, I see that you are using Api 30. Could you also retest this on api < 30 to see if the crash still occurs there ?
Thanks.

**Comment by afedor** [comment]
Hello,
oauth2_client has had 3 bug fix releases since 1.17.5, so it is at least being kept up-to-date, although I have no idea if this particular system gets tested (I only get the crash when using Google Maps, for instance).

Also, I'm not actually sure how to change the API.  compileSdkVersion and targetSdkVersion is set to 28 in my build.gradle file, and I also change the SDK in Project Settings in Android Studio to 28, but flutter doctor still claims SDK 30 is being used.

OT: If there's a way to symbolicate the backtrace from "flutter run" or use the debug build of libflutter.so, I could try to debug some of it myself.

**Comment by darshankawar** [comment]
Hi @afedor,
I tried your code sample on Android 8.1.0 device and followed the step to replicate as you mentioned, but didn't see the crash, unless I missed any step or settings apart from what you provided in the zip.

[64910.mp4.zip](https://github.com/flutter/flutter/files/5154258/64910.mp4.zip)

Also by changing the api, I meant, since you are using emulator with api 30 level, probably you can create another emulator and select api level < 30, as shown below, try again and see if you get crash on that setting.

![Screen Shot 2020-09-01 at 11 39 45 AM](https://user-images.githubusercontent.com/67046386/91801095-dfcfeb80-ec47-11ea-94c3-d5bf2f1c2b2a.png)

**Comment by afedor** [comment]
OK.  I tried API 28 and it still crashes.

Also, in your video, it's not clear to me what is happening after you click on the big "X" in the top-left corner.  You should return to the application "login" screen (if everything was working) or the app should crash (which is what happens to me).  But it looks like you are still in the browser and I can't tell if the app is still running or not.

**Comment by afedor** [comment]
[demo64910.mov.zip](https://github.com/flutter/flutter/files/5159246/demo64910.mov.zip)

**Comment by darshankawar** [comment]
@afedor after I tap on X, I remain on same screen but the app didn't crash and after tapping on back button from bottom bar few times, I get to the login screen.
Also, as a test, I tried using `url_launcher` plugin and opened `https://gmail.com` after tapping on `Login` button. Although, it doesn't have an X button on top-left, tapping on back button from bottom bar takes me to login screen properly.
I am not sure, but guess if this is the oauth2 plugin issue you are using.

**Comment by afedor** [comment]
Hi,
Thanks for looking at that.   I tried url_launcher and that crashes the app for me as well when I hit the back button (even after completely removing the oauth2 package). So it seems related only to Google Maps.  I don't know if there is a way to turn on more logging for maps, but I'll look into that to see if I can get more information

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by afedor** [comment]
FYI, I upgraded to flutter 1.22.1 recently and I was unable to reproduce the issue
