### ISSUE TITLE
onWebResourceError is called overzealously on Android

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#64925]
b/166114697

`onWebResourceError` API in webview_flutter plugin that was implemented within https://github.com/flutter/flutter/issues/53023.

The method does not document whether it is called for any page resource error (including images or scripts) or only for top-level navigation failures. From what I can see in practice on iOS it is only called for top-level navigation errors and on Android it depends on the version (see the two overloads for onReceivedError).

This is confusing and leads applications to stop loading pages and display fatal errors where they shouldn't (http://b/159587529).

Please:
1. Only report top-level navigation errors this way (isForMainFrame==true) for consistency between platforms.
2. Document the behavior of the method wrt top-level frame vs dependent resource.

**Comment by mehmetf** [comment]
@bparrishMines

**Comment by bparrishMines** [comment]
cc @cyanglaz @amirh @blasten

**Comment by blasten** [comment]
`WebViewClient#onReceivedError`:
> Note that unlike the deprecated version of the callback, the new version will be called for any resource (iframe, image, etc.), not just for the main page. Thus, it is recommended to perform minimum required work in this callback.


https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20android.webkit.WebResourceRequest,%20android.webkit.WebResourceError)


One possible workaround is to also pass `WebResourceRequest#isForMainFrame()` downstream.  Maybe, all the parameters from [WebResourceRequest]( https://developer.android.com/reference/android/webkit/WebResourceRequest
), so developers can be more precise about the behavior.
