### ISSUE TITLE
"select all" doesn't work.

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#64929]
## Steps to Reproduce

1. write few words at text field
2. double tap the word
3. tap "select all"

**Expected results:**
All words would be selected

**Actual results:**
no words is selected 
![File-from-iOS](https://user-images.githubusercontent.com/7422251/91686042-2dd8e680-eb97-11ea-99c7-90f1cd10d526.gif)

```
[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.18363.1016], locale ja-JP)
    • Flutter version 1.21.0-9.1.pre at C:\src\flutter
    • Framework revision be9bc8cb39 (13 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\hatadev\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\hatadev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.41

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @hatano0x06,
1. When we double tap the word, we see `cut, copy, paste` toolbar.
2. When we long press, then we see `paste, select all` and upon selecting `select all`, I am able to see the entire text selected properly.
3. When we double tap at end of the words, and select `select all`, then the entire text is selceted properly.

![Screen Shot 2020-08-31 at 3 44 27 PM](https://user-images.githubusercontent.com/67046386/91709883-08e97100-eba1-11ea-8df9-df48c22ed7e3.png)
![Screen Shot 2020-08-31 at 3 44 34 PM](https://user-images.githubusercontent.com/67046386/91709889-0a1a9e00-eba1-11ea-9474-6846ddeb0bf8.png)
![Screen Shot 2020-08-31 at 3 45 25 PM](https://user-images.githubusercontent.com/67046386/91709892-0b4bcb00-eba1-11ea-9b28-c4644238bce1.png)
![Screen Shot 2020-08-31 at 3 45 31 PM](https://user-images.githubusercontent.com/67046386/91709896-0be46180-eba1-11ea-9454-980dd12c6523.png)

I am on latest Stable (1.20.2) and tested on iOS simulator.

**Comment by hatano0x06** [comment]
I check at Stable (1.20.2) and it was ok for me too
thank you for your check

does it fixed at next beta version?

**Comment by darshankawar** [comment]
@hatano0x06 I am not sure about that. Mean time you may switch to Stable.
I am going ahead and closing this as non-issue.
Thanks.
