### ISSUE TITLE
[WEB] - Refresh Browser makes whole app restart

### ISSUE THREAD

**Issue by menezes85** [flutter/flutter#64923]
Hi guys, i am experiencing this behaviour on my flutter web app, recently i migrate my app to a web version, and i noticed that  if i refresh page via browser button, entire application restarts from splash.... how to fix this? 

Thanks in advance.

**Comment by pedromassangocode** [comment]
Hi @menezes85 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/53041).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by menezes85** [comment]
hello pedro, how are you? I read the question you mentioned, but here I refer to the normal behavior of any web page expected by the user while  updating a page, which is keep the user on the same page, and not redirect the user to the home page of the site. here i am not requesting new feature or  the ability to hot restart / hot reload the app in dev environment, they are different problems.

**Comment by pedromassangocode** [comment]
Hi @menezes85 
Please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
