### ISSUE TITLE
Flutter Version issue

### ISSUE THREAD

**Issue by ManishPanwar556** [flutter/flutter#64939]
## Steps to Reproduce

1.Run command flutter run -d chrome

**Expected results:** 
![image](https://user-images.githubusercontent.com/53398805/91700107-fa945880-eb92-11ea-9733-72388699094b.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/53398805/91699761-688c5000-eb92-11ea-92ea-b7c38a9cc613.png)
<details>
  <summary>Logs</summary>

```
```

```
```

The current Dart SDK version is 2.9.1.

Because flutter_app depends on flutter any from sdk which requires SDK version >=2.10.0-0.0.dev <3.0.0, version solving failed.
Running "flutter pub get" in flutter_app...
pub get failed (1; Because flutter_app depends on flutter any from sdk which requires SDK version >=2.10.0-0.0.dev <3.0.0, version solving failed.)

```
```

</details>

**Comment by hamdikahloun** [comment]
@ManishPanwar556 

Can you please provide :

- `flutter doctor -v`

- `flutter run --verbose`

- a minimal complete reproducible code sample

**Comment by ManishPanwar556** [comment]
No issue found while running flutter doctor

**Comment by ManishPanwar556** [comment]
[ +120 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                    #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:343:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
                    <asynchronous suspension>
                    #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
                    <asynchronous suspension>
                    #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
                    #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
                    #6      _rootRun (dart:async/zone.dart:1190:13)
                    #7      _CustomZone.run (dart:async/zone.dart:1093:19)
                    #8      _runZoned (dart:async/zone.dart:1630:10)
                    #9      runZoned (dart:async/zone.dart:1550:10)
                    #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
                    #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
                    #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
                    #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
                    #14     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
                    #23     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
                    #30     _rootRun (dart:async/zone.dart:1190:13)
                    #31     _CustomZone.run (dart:async/zone.dart:1093:19)
                    #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                    #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
                    #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                    #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
                    
                    
[ +280 ms] ensureAnalyticsSent: 256ms
[   +9 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

**Comment by hamdikahloun** [comment]
@ManishPanwar556 i dont see web folder in your project.

[https://flutter.dev/docs/get-started/web](https://flutter.dev/docs/get-started/web)

**Comment by ManishPanwar556** [comment]
I have enable it already

**Comment by hamdikahloun** [comment]
in your root project run : `flutter create .` and try again

**Comment by ManishPanwar556** [comment]
again getting the same error
![image](https://user-images.githubusercontent.com/53398805/91702082-d71edd00-eb95-11ea-8ec9-05030ee37ee2.png)

**Comment by neev123dev** [comment]
Hey you don't have a web folder that's why you are facing this issue.
Follow the steps to correctly install flutter for web:
* flutter channel beta
* flutter upgrade
* flutter config --enable-web
*   $ cd <inside local copy of the flutter/flutter repo>
*  $ git remote get-url origin
*  https://github.com/flutter/flutter.git
* flutter devices

**Comment by ManishPanwar556** [comment]
cd inside main.dart

**Comment by hamdikahloun** [comment]
PowerShell must be in your PATH :

- Add " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " to your Path variable
you might also need to add " C:\Windows\System32 " if it's not there in the path variable

**Comment by ManishPanwar556** [comment]
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\  this path?

**Comment by neev123dev** [comment]
hey @ManishPanwar556 are you sure that you have 64 bit??

**Comment by hamdikahloun** [comment]
PowerShell must be in your PATH so you must add it if doesn't exist.

![image](https://user-images.githubusercontent.com/32666446/91703402-06235780-eb72-11ea-9864-ddd9878518af.png)


Can please create new application :

- `flutter create mynewapp`

- `cd mynewapp`
 

- `flutter run -d chrome -v`

- `flutter doctor -v`

**Comment by ManishPanwar556** [comment]
Thanks @hamdikahloun @neev123dev actually the problem is in my powershell
