### ISSUE TITLE
Removing pages from Navigator.pages causes animation glitch

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#64941]
## Steps to Reproduce

The main goal was to remove pages from stack [HomePage, SecondLevelPage, ThirdLevelPage] to achieve [ThirdLevelPage] with usage of new Pages api from Navigator 2.0 #45938

1. Run following DartPad example https://dartpad.dartlang.org/3155332097b7c691e2b9cdaa1ac620a0
2. Press `Remove Second Level Page`
3. Observe animation glitch (compare screenshot in slow motion)
4. Press `Remove Home Page`
5. Observe animation glitch (compare screenshot in slow motion)

**Expected results:** 

I would expect the pages below current page to be removed without glitch/black screen

**Actual results:** 

Removal of pages below current page (`HomePage`, `SecondLevelPage`) causes animation glitch.

![CleanShot 2020-08-31 at 10 25 16](https://user-images.githubusercontent.com/16854239/91699319-67e4c100-eb74-11ea-9dc2-1943716ee05c.gif)

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale pl-PL)
    • Flutter version 1.22.0-1.0.pre at /Users/dominik/fvm/versions/dev
    • Framework revision ce40de69b7 (11 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • iPhone (Dominik) (mobile) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 13.6.1
    • macOS (desktop)           • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)          • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Issue replicable on latest stable (1.20.2) and happens on iOS. Tested on iOS simulator (iPhone SE) but doesn't occur on Android (tested on Samsung S10+).

[64941_ios.mov.zip](https://github.com/flutter/flutter/files/5150020/64941_ios.mov.zip)
[64941_s10.mp4.zip](https://github.com/flutter/flutter/files/5150021/64941_s10.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

**Comment by orestesgaolin** [comment]
I asked the question [on StackOverlfow](https://stackoverflow.com/a/63703735/6055532) and suggested answer i.e._adding `ValueKey(pages.length)` to Navigator_ resolves the issue. I wonder if that's intended behavior. If yes, then maybe it should be added to docs. What do you think?

**Comment by slightfoot** [comment]
> I asked the question [on StackOverlfow](https://stackoverflow.com/a/63703735/6055532) and suggested answer i.e._adding `ValueKey(pages.length)` to Navigator_ resolves the issue. I wonder if that's intended behavior. If yes, then maybe it should be added to docs. What do you think?

This is not a workaround or a even a good idea. You will loose your entire sub-tree state of all your routes.

**Comment by chunhtai** [comment]
There is a bug when we are rearranging the overlay, which cause the removed overlay entry to be placed on top for 1 frame. I will put up a PR to fix it
