### ISSUE TITLE
Please support --dart-define for flutter build macos

### ISSUE THREAD

**Issue by technolion** [flutter/flutter#64944]
## Use case

We would like to pass environment variables to a build process for macOS.
`flutter build` supports  passing environment variables to the build process when building for ios, android, windows and the web:

`flutter build web --dart-define=MY_HOSTNAME=api.example.com`

Unfortunately the option `--dart-define` is not available for macOS!

## Proposal

I noticed that for the web the minified main.dart.js contains the value passed with `--dart-define`.
It would be great, if the same would be done for macOS, leading to modified compiled native app including the passed value.

**Comment by technolion** [comment]
I just noticed that -dart-define **is** available for windows. It should definitely be supported for macOS as well, since Flutter for macOS is even further advanced.

**Comment by stuartmorgan** [comment]
It looks like all the plumbing is there and we're just not enabling the option.

@jonahwilliams There are a few subtle differences in the list of options on Linux vs. macOS (of which this is one). I'm assuming those are all accidents? If so, can we just pull out a utility method to set up that list for all of the desktop platforms? (I can do the PR, I just want to make sure there's not a reason not to do it that way.)

**Comment by jonahwilliams** [comment]
Yeah, now that the backend of the tool is updated they should support the same options for now (ignoring the non-assemble APIs). If you don't have time this week I can take a look too.

**Comment by technolion** [comment]
Awesome! Thanks a lot. That was ultra-quick!
