### ISSUE TITLE
Upgraded flutter and I can no longer update the version in the ios App store

### ISSUE THREAD

**Issue by pinkfish** [flutter/flutter#64954]
## Steps to Reproduce

Upgrade flutter from a previously created flutter version.  I don't have have a version of the ios specified in my runner that I can see.  I tried changing it around a bit, setting it to 9.3 in the options.  However it doesn't seem to help and not sure why it is broken now.

Try and upload compiled flutter app to the app store.

"Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."

**Expected results:** 

Should actually upload

**Actual results:** 

"Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."

<details>
  <summary>Logs</summary>

```
[16:57:41]: [Transporter Error Output]: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plist."
[16:57:41]: [Transporter Error Output]: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."
[16:57:42]: Transporter transfer failed.
[16:57:42]: 
[16:57:42]: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plist."
ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."
[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:41 PDT] <main> DBG-X:   parameter ShouldUseRESTAPIs = false

[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:41 PDT] <main> ERROR: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plist."

[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:41 PDT] <main> ERROR: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."

[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:41 PDT] <main> DBG-X: The error code is: 1102

[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:41 PDT] <main>  INFO: Done performing authentication.

[16:57:42]: [iTMSTransporter] 

[16:57:42]: [iTMSTransporter] 

[16:57:42]: [iTMSTransporter] 

[16:57:42]: [iTMSTransporter] Package Summary:

[16:57:42]: [iTMSTransporter]  

[16:57:42]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[16:57:42]: [iTMSTransporter] 	/var/folders/j3/cc_qhf156cz8qs2wgh554z3r0000gp/T/d20200828-23689-1fwg4ed/1500194738.itmsp - Error Messages:

[16:57:42]: [iTMSTransporter] 		ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plist."

[16:57:42]: [iTMSTransporter] 		ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."

[16:57:42]: [iTMSTransporter] [2020-08-28 16:57:42 PDT] <main> DBG-X: Returning 1

[16:57:42]: iTunes Transporter output above ^
[16:57:42]: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plist."
ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."
Return status of iTunes Transporter was 1: ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app does not support the minimum OS Version specified in the Info.plis\nERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

```

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-US)
    • Flutter version 1.21.0-9.1.pre at /Users/david/development/flutter
    • Framework revision be9bc8cb39 (13 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • iPhone (mobile)  • 088171530c05e7e91a261e7e3a4bab48290f59f3 • ios
      • iOS 12.4.8
    • Web Server (web) • web-server                               • web-javascript
      • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript
      • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @pinkfish 
Did you add any packages that require a higher minimum iOS version? if yes, you need to target a higher minimum for those pods.  Do you have any issues when running in release mode `flutter run --release -v`? 
Can you please provide your `flutter doctor -v`, your `flutter build ios -v`, your `pubspec.yaml`
Thank you

**Comment by KevinTheGray** [comment]
@TahaTesser  I hit this issue as well after upgrading to beta version 1.21.0-9.2.pre.  

The fix for me was to modify the file `ios/Flutter/AppFrameworkInfo.plist` and change `MinimumOSVersion` to `9.0`, which is the minimum version I support.  It was set `8.0`.  After doing this, I cleaned, rebuilt, archived and uploaded and it worked.

Some other information that may be useful
- The project is pretty old, `flutter created` it in August of 2018
- I also regenerated the Podfile after updating my Flutter version, because there was a warning about it being out of date.
Not sure if that's relevant, but I didn't really make any other major configuration changes.

**Comment by Bforsyth1234** [comment]
> @TahaTesser I hit this issue as well after upgrading to beta version 1.21.0-9.2.pre.
> 
> The fix for me was to modify the file `ios/Flutter/AppFrameworkInfo.plist` and change `MinimumOSVersion` to `9.0`, which is the minimum version I support. It was set `8.0`. After doing this, I cleaned, rebuilt, archived and uploaded and it worked.
> 
> Some other information that may be useful
> 
> * The project is pretty old, `flutter created` it in August of 2018
> * I also regenerated the Podfile after updating my Flutter version, because there was a warning about it being out of date.
> 
> Not sure if that's relevant, but I didn't really make any other major configuration changes.

This works but im trying to get it to work with codemagic ci/cd and flutter defaults to 8.0. Is there a way to set the MinimumOSVersion in flutter?

**Comment by aidandavis** [comment]
This is breaking my automated release pipeline.

After upgrading flutter I noticed an error in my automated deployment with Fastlane and Github Actions. The error I saw there was after the build and during the upload to testflight. The error in my pipeline was ```NoMethodError: [!] undefined method `strip' for nil:NilClass```.

I tried the build and upload manually through xcode and got the above error (```ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist."```).

**Comment by aidandavis** [comment]
https://github.com/flutter/flutter/issues/58200#issuecomment-675085313 This issue looks similar, could be solved by doing this?

**Comment by aidandavis** [comment]
I commented less than a day ago on this issue. It's still a problem for me.

**Comment by TahaTesser** [comment]
Hi @pinkfish 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
