### ISSUE TITLE
App Build Failed for iOS, Attached error of screenshot.

### ISSUE THREAD

**Issue by patelankur1986** [flutter/flutter#64956]
<img width="1351" alt="Screenshot 2020-08-31 at 10 09 14 PM" src="https://user-images.githubusercontent.com/11896328/91744154-a27f4580-ebd6-11ea-9a71-f1f6b8a8ed3b.png">

**Comment by patelankur1986** [comment]
flutter doctor -v

<img width="1380" alt="Screenshot 2020-08-31 at 10 13 09 PM" src="https://user-images.githubusercontent.com/11896328/91744476-33562100-ebd7-11ea-8355-3a5d6f3935a1.png">

**Comment by darshankawar** [comment]
Hi @patelankur1986,
Can you try `flutter pub cache repair` or `flutter clean` and then `flutter run` to see if it works for you ?
If problem persists, provide `flutter run --verbose` and the command you are trying to run which fails. Also, does it work on Android and failing only on iOS ?
Thanks.

**Comment by patelankur1986** [comment]
@darshankawar - I have been tried all the solutions but couldn't get anything and almost spent 2 days. Finally its works for me. Thanks buddy.👍
