### ISSUE TITLE
Isolates regression, crashes only in deployed apps

### ISSUE THREAD

**Issue by eukreign** [flutter/flutter#6496]
Isolates stopped working in deployed apps (it works in development mode). This regression is possibly caused by `FTL_CHECK` in [runtime/dart_init.cc#L268](https://github.com/flutter/engine/blob/f07c32d24716f91cbce3b3157b48b294979e9ea2/runtime/dart_init.cc#L268).

Related pull request and merge that caused the regression: https://github.com/flutter/engine/pull/3041

Related testing issue: #3443

Crash report in Google Play Developer Console:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/angler/angler:7.0/NRD90U/3155372:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 21120, tid: 21153, name: Thread-3  >>> com.app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:../../flutter/runtime/dart_init.cc(268)] Check failed: entry_uri.find(kFileUriPrefix) == 0u. 
'
    r0 00000000  r1 000052a1  r2 00000006  r3 00000008
    r4 ca8d0978  r5 00000006  r6 ca8d0920  r7 0000010c
    r8 e36dfd80  r9 cf403f80  sl d134ca94  fp e36a3608
    ip 00000000  sp ca8d0320  lr eb382537  pc eb384d94  cpsr 200f0010
```

**Comment by eseidelGoogle** [comment]
@johnmccutchan (also @a-siva who is helping us get better isolate testing).
