### ISSUE TITLE
Devicelab logs should be available for public

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#64964]
Currently, the logs in https://flutter-dashboard.appspot.com/#/build can only be downloaded after signing in with an `@google` account. This limits our general community to debug issues. See https://github.com/flutter/flutter/pull/61998#issuecomment-683300301 as an example.

As LUCI test logs can be accessed in public (e.g., https://ci.chromium.org/p/flutter/builders/try/Linux%20build_tests/1355? can be opened in the incognito mode), I don't see any reason to not make devicelab logs public.

**Comment by liyuqian** [comment]
CC @godofredoc

**Comment by godofredoc** [comment]
DeviceLab can not share logs without granting permission to the datastore. However this will be the default when the DeviceLab gets migrated to LUCI.

**Comment by godofredoc** [comment]
Obsolete: Now logs are available directly in the luci ui.
