### ISSUE TITLE
LUCI Recipes are missing goldctl

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#64969]
The luci build recipes download the goldctl tool for interacting with Flutter Gold.
While following up on https://github.com/flutter/flutter/issues/64759, I found that Gold is only receiving images from the macos build:

![Screen Shot 2020-08-31 at 12 31 49 PM](https://user-images.githubusercontent.com/16964204/91759855-345f6200-eb87-11ea-85cc-8c8aa4f72ed4.png)

Upon investigation is appears from the environment that the goldctl tool is not available anymore in the linux, windows, or web builds.

**Here is the recipe where goldctl is dowloaded: 
https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/flutter.py#71**

Looking at the latest build on master, goldctl is not in the environment

#### Windows build
 - https://ci.chromium.org/p/flutter/builders/prod/Windows%20framework_tests/194
- environment: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870425858761110144/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_widgets/0/logs/execution_details/0

#### Linux build
- https://ci.chromium.org/p/flutter/builders/prod/Linux%20framework_tests/241
- environment: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870425867976421936/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_widgets/0/logs/execution_details/0

#### Web Build
- https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_tests/227
- environment: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870424030672985552/+/steps/buildbucket.collect/0/steps/wait/0/logs/execution_details/0

#### Macos build 
- https://ci.chromium.org/p/flutter/builders/prod/Mac/13123
  - **Here you can see the Download goldctl step is run in Step 9**
- environment: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870432067182695040/+/steps/run_test.dart_for_framework_tests_shard/0/logs/execution_details/0

This blocks #64759

**Comment by keyonghan** [comment]
Prod recipes have been updated to use new recipes: https://github.com/flutter/infra/blob/master/config/framework_config.star#L50, where it calls https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/repo_util/api.py;l=105. But the new recipe misses `'GOLDCTL': EnsureGoldctl(api)`
@godofredoc Is this expected, or we should add it back?

**Comment by Piinks** [comment]
Definitely. Goldctl should be downloaded for all pre-submit and post-submit builds. It is necessary to execute golden file tests.

**Comment by Piinks** [comment]
I just checked a few pre-submit builds, they are also not downloading goldctl anymore. Golden file testing is broken across the board.

**Comment by godofredoc** [comment]
@Piinks Any reasons why this is not making the builders red?

**Comment by godofredoc** [comment]
@keyonghan we need to update the https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/flutter_deps/api.py to include the golden cli cipd package and ensure all the builders use it here: https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=56

**Comment by godofredoc** [comment]
@Piinks is it possible to raise an exception or exit with non zero status if gold client is not found?

**Comment by Piinks** [comment]
The environment informs the test, which is why it's quietly taking another path.
If goldctl is not present, it assumes we are in a different environment, like local testing.

We did it this way originally because we didn't want to download goldctl for test shards that aren't executing golden file tests, to be more efficient. If we can ensure it is downloaded for every build, I can add an assert so `if we are in a luci environment, goldctl must be present.` Would that affect the engine builds though? They can't interface with Gold because the engine is a separate repo.

https://github.com/flutter/flutter/blob/7aa8c2ab992f9a6e94736419db42ce80a7d22e8a/packages/flutter_goldens/lib/flutter_goldens.dart#L31

**Comment by keyonghan** [comment]
> @keyonghan we need to update the https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/flutter_deps/api.py to include the golden cli cipd package and ensure all the builders use it here: https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=56

Seems [`flutter_environment`](https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/repo_util/api.py;l=105) is more suitable? Since this is to update the envrionment.

Here is the CL: https://flutter-review.googlesource.com/c/recipes/+/6200
and a led run: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/0e7c5b634f4dd5be061d83390ba16c1ab2f631239dd0743f79431a1cc028f7e1/+/annotations (commented out the remaining steps)

**Comment by godofredoc** [comment]
Yes we can add the dependency for every build, it will be great if we can raise the error if we are in luci and goldctl is not available.

How can the engine be affected by raising an error? is this because of the web tests running from the engine?

**Comment by Piinks** [comment]
I'm not sure, I know the engine runs framework tests, and so I would need a way to detect `this is the engine` and not try to use Gold. Using `is goldctl here?` was  how we were doing it. 
So would the engine builders go red if I asserted that goldctl is present? They will go red if goldctl is there and the engine tries to use Gold.

**Comment by godofredoc** [comment]
Not yet, the web tests from the engine have not been migrated yet. In fact I have a pending CL to review a CL for that, let me add you.

I think is safe to land a change to raise and error after @keyonghan landed the recipe changes and we can address the engine portion in @nturgut CL.

**Comment by Piinks** [comment]
SGTM! Thanks!

Once the recipes are fixed, there will probably be a lot of images in need of triage, since images are checked in by the paramset and the missing platforms have already fallen off. I am not sure how this is going to present itself, it could be quiet, or stink up someone's PR. I'll keep an eye on it once the change lands.

**Comment by Piinks** [comment]
I mentioned on the CL, the `GOLD_TRYJOB` property should also be present in order to distinguish between pre and post submit testing.
Here in the original recipe: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/flutter.py#207

**Comment by Piinks** [comment]
The logic for the gold tryjob appears to be missing as well. 
It was added in https://github.com/flutter/infra/pull/91/files
https://github.com/flutter/infra/blob/master/config/framework_config.star

**Comment by godofredoc** [comment]
Just to validate was the logic "run gold jobs on any presubmit task"?

**Comment by Piinks** [comment]
> Just to validate was the logic "run gold jobs on any presubmit task"?

The tests are executed differently in pre and post submit.
pre-submit needs to run tryjobs for Gold.
post-submit uploads the images to Gold.

**Comment by Piinks** [comment]
Found the logic for the config, it's here: https://github.com/flutter/infra/blob/master/config/lib/common.star :)

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/6200 has been submitted.
Verified try jobs work: https://ci.chromium.org/p/flutter/builders/try/Linux%20SDK%20Drone/29051? (Step 13).

Please re-open if still any issues.

**Comment by Piinks** [comment]
Re-opening since this has regressed. Pre-submit and post-submit builders do not have goldctl again. Looks like it regressed a week age, for example you can see the drop off: https://flutter-gold.skia.org/search?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=true&offset=0&pos=true&query=name%3Dcupertino.activityIndicator.paused.light%26source_type%3Dflutter&sort=desc&unt=true

FYI @godofredoc @keyonghan

**Comment by godofredoc** [comment]
@Piinks  Do you have the name of a builder that is not uploading the golds?

**Comment by keyonghan** [comment]
Recipe is getting dependencies: https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=49. But from config side, `goldctl` dependency seems missing.

**Comment by Piinks** [comment]
> @Piinks Do you have the name of a builder that is not uploading the golds?

Looks like all of them. :(

**Comment by Piinks** [comment]
Gold has not seen anything from Luci in a week, and the last remaining mac Cirrus build was removed yesterday AFAICT. It looks like there is one cirrus linux build talking to Gold in pre-submit, but that is it.

**Comment by keyonghan** [comment]
From config side, dependency is configured separately for different builders. Based on [try_builders](https://github.com/flutter/flutter/blob/master/dev/try_builders.json) and [prod_builders](https://github.com/flutter/flutter/blob/master/dev/prod_builders.json), which are supposed to have the goldctl dependency? @Piinks

**Comment by godofredoc** [comment]
Found the issue, the dependency is not in the properties config. @Piinks only the tests using the flutter test runner need the dependency, am I right?

**Comment by godofredoc** [comment]
Did we land raising an error when the dependency is missing?

**Comment by Piinks** [comment]
> Did we land raising an error when the dependency is missing?

Still waiting on feedback: https://github.com/flutter/infra/pull/196
But I am not convinced it will work. I can not reliably assert that goldctl is present. OTher repos that checkout flutter/flutter and execute tests would be broken.
I can add more information to the environment (like cocoon#196 is proposing) to inform that we should assert, but this doesn't actually solve the problem. If the recipes change and the environment isn't set up right, then it will break again.

Goldctl should be present in try_builders and prod_builders. There should be an environment variable `GOLDCTL` with a path to the tool. There should also be `GOLD_TRYJOB` set up as well for the try_builders.

**Comment by Piinks** [comment]
This is the change that fixed this last time: https://flutter-review.googlesource.com/c/recipes/+/6200

**Comment by godofredoc** [comment]
I'm adding the comment to the PR and landed the fix. Please take a look and let us know if it is still failing.

**Comment by Piinks** [comment]
Verified on the Gold dashboard that luci builds [chrome, linux, windows, mac] are all present in tryjobs and prod.
