### ISSUE TITLE
[Web][SelectableText] copy SelectableText in flutter web doesn't work

### ISSUE THREAD

**Issue by enzodanjour** [flutter/flutter#64971]
The copy feature doesn't work during select a text and try copy with Ctrl + c.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale pt_BR.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

**Comment by kunit1** [comment]
This is already working correctly on latest master. It has not made its way to beta yet.

**Comment by darshankawar** [comment]
Hi @enzodanjour,
Please switch to Master and see if it works there, per above comment.
Thanks.

**Comment by enzodanjour** [comment]
Thanks, this works!

**Comment by darshankawar** [comment]
Thanks @enzodanjour for confirming.
Closing this as non-issue.
