### ISSUE TITLE
[infra] No way to skip builders per-branch on post-submit

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#64975]
We currently have no way of skipping builders on post-submit for particular branches (in this case, we would like to skip the Fuchsia builder on all branches except master). Try jobs are scheduled by cocoon based on JSON files in the source repos, however post-submit builders are defined in `flutter/infra`, and are the same across all branches.

**Comment by christopherfujino** [comment]
One solution to this would be to have the recipe read `prod_builders.json` and `try_builders.json` at the beginning, and if the current builder isn't defined, immediately exit with a green (or grey?)

**Comment by CaseyHillers** [comment]
This functionality is available in the engine, and will be added to the framework once https://github.com/flutter/flutter/issues/84998 is complete

**Comment by CaseyHillers** [comment]
Closing as framework now generates its luci configs from ci.yaml
