### ISSUE TITLE
We shouldn't check that layers aren't empty

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#650]
Layers are sometimes empty at the start and end of animations. For example, the opacity layer for the popup menu is now 0x0 at the very start. We throw an assert when building the layer for that now.

**Comment by abarth** [comment]
I'm sure I broke this.

**Comment by Hixie** [comment]
At a guess, it's just a combination of your menu changes creating a 0x0 OpacityLayer and my recent changes to the OpacityLayer to assert that the layer isn't empty (in addition to not being null, or whatever it was). We should just remove the "empty" part of the assert I added.

**Comment by abarth** [comment]
Ok, I've re-assigned this issue to you.  Feel free to bounce it back to me if you'd prefer me to look.
