### ISSUE TITLE
can't set CupertinoSlider's width

### ISSUE THREAD

**Issue by Sunyandong-CS** [flutter/flutter#65008]
| am going to use cupertinoSlider in my project, and it should be displayed with full screen, but I can't find ways to make it。
I have read the source code of cupertinoSlider and find :
`const double _kSliderWidth = 176.0; // Matches Material Design slider.`

so I wander why can't this widget expose a property 'width' to user?

**Comment by pedromassangocode** [comment]
Hi @Sunyandong-CS
You can use the `SizedBox` widget to define the size of your `CupertinoSlider`:

```dart
SizedBox(
    width: 400,
    child: CupertinoSlider(
      value: 0.5,
      onChanged: (value) {},
    ),
)
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by aloisdeniel** [comment]
I disagree with your solution @pedromassangocode.

How could we expand the slider to fill the screen?

For example, when doing that, the slider is limited to `176` in width for the reason described in the issue (which is not the case for material `Slider`s) : 

```dart
Row(
   children: [
     Expanded(
        child: CupertinoSlider( ...),
     )
  ],
)
```

**Comment by pedromassangocode** [comment]
Hi @aloisdeniel 

The code bellow has the following result.

| With Expanded | Without expanded |
|-|-|
|<img height="720" src="https://user-images.githubusercontent.com/67424416/115694864-28fcb900-a359-11eb-9665-167ee40b013b.png">|<img height="720" src="https://user-images.githubusercontent.com/67424416/115695018-53e70d00-a359-11eb-9556-6b07a90e3a3b.png">|


From my tests, you can customize the slider `width` with the `SizedBox` widget as well!

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Row(
            children: <Widget>[
              Expanded(
                child: CupertinoSlider(
                  value: .7,
                  onChanged: (v) {},
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>
