### ISSUE TITLE
[plugin] The plugin [flutter_plugin_android_lifecycle] could not be built due to the issue above

### ISSUE THREAD

**Issue by AdiKK17** [flutter/flutter#65012]
Launching lib\main.dart on ONEPLUS A6000 in release mode...
Running Gradle task 'assembleRelease'...
WARNING: [Processor] Library 'C:\Users\kumar\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_release\1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54\f970dd371259c1fef30727ae3d9d771d313c73f6\flutter_embedding_release-1.0.0-c8e3b9485386425213e2973126d6f57e7ed83c54.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/VisibleForTesting'
 Example of support library reference: 'android/support/annotation/NonNull'
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.5\android\src\main\java\io\flutter\plugins\share\MethodCallHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\sms_autofill-1.2.4\android\src\main\java\com\jaumard\smsautofill\AppSignatureHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clipboard_manager:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\Users\kumar\.gradle\caches\transforms-2\files-2.1\ce1635782ed616d72db5bb7f69df3596\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
         
     C:\Users\kumar\.gradle\caches\transforms-2\files-2.1\ce1635782ed616d72db5bb7f69df3596\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18m 8s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin clipboard_manager...
Running Gradle task 'assembleAarRelease'...
✓ Built build\app\outputs\repo.
Building plugin contacts_service...
Running Gradle task 'assembleAarRelease'...
✓ Built build\app\outputs\repo.
Building plugin flutter_plugin_android_lifecycle...
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
import androidx.lifecycle.Lifecycle;
                         ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22: error: cannot find symbol
  public static Lifecycle getActivityLifecycle(
                ^
  symbol:   class Lifecycle
  location: class FlutterLifecycleAdapter
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 15s

Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\programs\Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\programs\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\kumar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • ONEPLUS A6000 (mobile) • eb713420 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by pedromassangocode** [comment]
Hi @AdiKK17 
Can you please provide your `flutter build appbundle --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by AdiKK17** [comment]
Hello,

the problem is coming from flutter run --release not flutter build appbundle.

should i still provide flutter build appbundle --verbose or rather provide flutter run --release --verbose?

Thanks.

**Comment by pedromassangocode** [comment]
> Hello,
> 
> the problem is coming from flutter run --release not flutter build appbundle.
> 
> should i still provide flutter build appbundle --verbose or rather provide flutter run --release --verbose?
> 
> Thanks.

Please provide just `flutter run --release --verbose`

**Comment by AdiKK17** [comment]
Unable to input the logs here.

Any solution?

Thanks

**Comment by pedromassangocode** [comment]
You can just run the command and once it finishes copy and paste the output here.

**Comment by AdiKK17** [comment]
I have the logs but unable to paste the output here!

Too long a comment according to github guidelines.

**Comment by pedromassangocode** [comment]
You can share it as a `.txt` file.

**Comment by AdiKK17** [comment]
[problem_logs.txt](https://github.com/flutter/flutter/files/5160903/problem_logs.txt)

**Comment by pedromassangocode** [comment]
Based on the logs file, the builds failed multiple times, first due to the `clipboard_manager`:


> [+1699 ms] > Task :contacts_service:assembleRelease
> [+2600 ms] > Task :flutter_plugin_android_lifecycle:assembleRelease
> [+5902 ms] > Task :clipboard_manager:verifyReleaseResources FAILED
> [+5498 ms] FAILURE: Build failed with an exception.
> [   +3 ms] * What went wrong:
> [   +1 ms] Execution failed for task ':clipboard_manager:verifyReleaseResources'.
> [        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> [   +1 ms]    > 1 exception was raised by workers:
> [        ]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
> [        ]      C:\Users\kumar\.gradle\caches\transforms-2\files-2.1\ce1635782ed616d72db5bb7f69df3596\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not
> found.
> [   +1 ms]      C:\Users\kumar\.gradle\caches\transforms-2\files-2.1\ce1635782ed616d72db5bb7f69df3596\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
> [ +201 ms] * Try:
> [   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 15m 10s
> [        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> [        ] Use '--warning-mode all' to show the individual deprecation warnings.
> [        ] See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
> [ +184 ms] 302 actionable tasks: 280 executed, 22 up-to-date
> [+12329 ms] Running Gradle task 'assembleRelease'... (completed in 923.9s, longer than expected)
> [   +3 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> [ +473 ms] Building plugin clipboard_manager...
> [ +721 ms] Running Gradle task 'assembleAarRelease'...
> [   +7 ms] set `android.enableR8=true` in gradle.properties
> [+2180 ms] Using gradle from C:\\flutter\\.pub-cache\\hosted\\pub.dartlang.org\\clipboard_manager-0.0.4\\android\gradlew.bat.
> [   +1 ms] C:\\flutter\\.pub-cache\\hosted\\pub.dartlang.org\\clipboard_manager-0.0.4\\android\gradlew.bat mode: 33279 rwxrwxrwx.
> [        ] executing: [C:\\flutter\\.pub-cache\\hosted\\pub.dartlang.org\\clipboard_manager-0.0.4\\android/] C:\\flutter\\.pub-cache\\hosted\\pub.dartlang.org\\clipboard_manager-0.0.4\\android\gradlew.bat
> -I=C:\flutter\packages\flutter_tools\gradle\aar_init_script.gradle -Pflutter-root=C:\flutter -Poutput-dir=C:\Users\kumar\Music\getsupplys\build\app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true
> -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
> [+506575 ms] Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
>                       WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
>                       The current default is 'false'
>                       Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.
>                       :assembleAarRelease UP-TO-DATE
> 


### And them due to the `flutter_plugin_android_lifecycle` package:

>                       > Task :compileReleaseJavaWithJavac FAILED
>                       17 actionable tasks: 17 executed
> 
>                       C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8:
>                       error: package androidx.lifecycle does not exist
>                       import androidx.lifecycle.Lifecycle;
>                                                ^
>                       C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22:
>                       error: cannot find symbol
>                         public static Lifecycle getActivityLifecycle(
>                                       ^
>                         symbol:   class Lifecycle
>                         location: class FlutterLifecycleAdapter
>                       2 errors
> 
>                       FAILURE: Build failed with an exception.
> 
>                       * What went wrong:
>                       Execution failed for task ':compileReleaseJavaWithJavac'.
>                       > Compilation failed; see the compiler error output for details.
> 
>                       * Try:
>                       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
>                       * Get more help at https://help.gradle.org
> 
>                       BUILD FAILED in 1m 54s
> [ +629 ms] Exception: The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
> [ +196 ms] "flutter run" took 18,16,757ms.

Leaving this open because from the logs looks like the issues was caused by the `flutter_plugin_android_lifecycle` plugin.

@AdiKK17 Please try `flutter clean` before `flutter run --release` to see if it works for you.

**Comment by AdiKK17** [comment]
Flutter clean didn't work and neither did flutter pub cache repair.

**Comment by AdiKK17** [comment]
I was using a clipboard_manager 0.0.4 plugin.

Removing this plugin resolved the issue.

**Comment by yuensunn** [comment]
> I was using a clipboard_manager 0.0.4 plugin.
> 
> Removing this plugin resolved the issue.

Oh god you saved me hours of debugging. Thank you!

**Comment by zwz1192511822** [comment]
I also encountered this problem, how to solve it？

**Comment by AdiKK17** [comment]
@zwz1192511822 try removing the clipboard manager plugin
