### ISSUE TITLE
flutter create doesn't ask for a value fro the company id

### ISSUE THREAD

**Issue by frr149** [flutter/flutter#65022]
## Use case

The *company id* is a reverse dns id that identifies the app and publisher in the app store and google play. When running `flutter create` it doesn't ask for this value.

Instead, it inserts a generic `com.example.empty` in both the iOS and Android projects files. It has then to be manually changed by the developer. This is a waste of time and error prone.

## Proposal

Have an entry in `pubspec.yaml` for the company and project id, and have flutter keep that in sync with the iOS and Android project files.

**Comment by hamdikahloun** [comment]
Hi @frr149 
You can use : `flutter create --org com.my_org project_name`

**Comment by pedromassangocode** [comment]
Hi @frr149 
You can run: `flutter create --org com.org_name app_name` for more options please run: `flutter create --help`

Closing as this is not an issue with Flutter itself. If you disagree please write in the comments and I will reopen it.
Thank you
