### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark hotReloadMillisecondsToFrame & hotReloadMillisecondsToFrameAfterChange regressions 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#65029]
See https://flutter-flutter-perf.skia.org/e/?begin=1598835482&end=1598898484&keys=X49aa92e29117c746ab2e25d9ae6ff1d7&num_commits=50&request_type=1&xbaroffset=21301.

Looks likehttps://github.com/flutter/flutter/pull/63301 is the culprit commit. cc @clarkezone @liyuqian .

**Comment by zanderso** [comment]
Huh. It doesn't seem like that Windows template change should have been able to affect a Catalina hot reload benchmark.

**Comment by stuartmorgan** [comment]
Yep, zero chance that PR is related.

**Comment by jonahwilliams** [comment]
We need to recover the machine/device, could be a dialog.

**Comment by jonahwilliams** [comment]
I'm not sure which mac machine is the catalina one

**Comment by keyonghan** [comment]
Mac 12 is the catalina for ios. Checking.

**Comment by keyonghan** [comment]
There is no dialog showing up. Rebooted both bot and device.

**Comment by jonahwilliams** [comment]
Thanks @keyonghan !

**Comment by jonahwilliams** [comment]
I guess we can probably wait for one more PR to kick it

**Comment by jonahwilliams** [comment]
benchmark has returned to normal, closing
