### ISSUE TITLE
Attempting to create a package for an app however unable to test package at all

### ISSUE THREAD

**Issue by MockAirplane700** [flutter/flutter#65028]
## Steps to Reproduce

1. Create a package module in an android studio flutter project
2. The contents of my pub spec.ymal :
     name: synthexklutchrelease
description: Release version of klutch client ui

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  provider: ^4.0.5
  permission_handler: ^5.0.0+hotfix.5
  expandable: ^4.1.4
  barcode_scan: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.5.0
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0
  firebase_core: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

3. attempt to run initial test that comes in the template code 

I was expecting to see the results of the test in the terminal 

I got the following error : Dart 2.6.1 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @MockAirplane700,
Can you try [this](https://github.com/flutter/flutter/issues/38697#issuecomment-522138147) and [this](https://github.com/flutter/flutter/issues/38697#issuecomment-522141414) command and see if it works for you ?
Thanks.

**Comment by MockAirplane700** [comment]
Thank you
