### ISSUE TITLE
crash on list item tap

### ISSUE THREAD

**Issue by mrugendra** [flutter/flutter#6502]
## Steps to Reproduce

Create a list,
crash on tap of any list item (nothing happens on android, on tap not called)

##code snippet
```dart
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// @author: Mrugendra Thatte

import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/http.dart' as http;
import 'dart:convert';

void main() => runApp(new MaterialApp(
                            title: "TechCruch",
                            home: new NewsList()));


class NewsList extends StatefulWidget{

@override
_NewsListState createState() => new _NewsListState();

}

class _NewsListState extends State<NewsList> {
  String URL = "https://newsapi.org/v1/articles?source=techcrunch&apiKey=9b390aa215934b3381f53d07f4353b9f";
  List<NewsFeed> items = new List<NewsFeed>();

  @override
  void initState(){
      super.initState();
      loadData();
  }

  @override
  Widget build(BuildContext context){

    return new Scaffold(
          appBar: new AppBar(title: new Text('TechCrunch top news')),
          body: new Scrollbar(
              child: new MaterialList(
                  type: MaterialListType.threeLine,
                  padding: new EdgeInsets.symmetric(vertical: 4.0),
                  children: getListOfListItems(context, this.items),
              )
            )
        );
  }

  List<Widget> getListOfListItems(BuildContext context, List<NewsFeed> feeds){
    List<Widget> widgets = new List<Widget>();
    for(int i=0; i<feeds.length; i++){
      widgets.add(buildListItem(context, feeds[i]));
    }
    return widgets;
  }

  Widget buildListItem(BuildContext context, NewsFeed newsFeed) {
      return new ListItem(
        isThreeLine: true,
        dense: true,
        leading: null,
        title: new Text(newsFeed.title),
        subtitle: new Text(newsFeed.description),
        trailing: null,
        onTap: (){
            print("Tapped ");
        }
      );
    }

  void loadData() {
    // call the web server asynchronously
    http.get(URL).then((http.Response response){
      String jsonString = response.body;
      print(jsonString);
      parseJson(jsonString);
    });
  }

  void parseJson(String responseText){
    Map data = JSON.decode(responseText);
    List articles = data["articles"];
    setState((){
        items = new List<NewsFeed>();

        for(int i=0; i<articles.length; i++){
          String title = articles[i]["title"];
          String subtitle = articles[i]["description"];
          String link = articles[i]["link"];
          items.add(new NewsFeed(title, subtitle, link));
        }
    });
  }

}

class NewsFeed{

  NewsFeed(this.title, this.description, this.link);

  String title;
  String description;
  String link;
}

```

## Logs
CoreSimulatorBridge: Error in registering callback port Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedDescription=Unable to register pasteboard callback port., NSLocalizedFailureReason=Port is invalid.}

SpringBoard: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Application finished.
com.apple.CoreSimulator.SimDevice.215A9935-BD79-4FAE-8DDB-49BE6CCBDA19.launchd_sim[79148] (UIKitApplication:com.yourcompany.helloWorld[0x2015]: Service exited due to Broken pipe: 13
backboardd: [Common] Unable to get short BSD proc info for 82963: No such process
backboardd: [Common] Unable to get proc info for 82963: No such process
assertiond: notify_suspend_pid() failed with error 7

## Flutter Analyze
[lint] Annotate overridden members (lib/NavDrawer.dart, line 7, col 10)
[hint] Unused import (lib/NewsFeedItem.dart, line 4, col 8)
[lint] Specify type annotations. (lib/NewsList.dart, line 76, col 5)
[lint] Specify type annotations. (lib/NewsList.dart, line 75, col 5)
[lint] Name non-constant identifiers using lowerCamelCase. (lib/NewsList.dart, line 17, col 10)
[lint] Name non-constant identifiers using lowerCamelCase. (lib/Routes.dart, line 3, col 17)
[lint] Name non-constant identifiers using lowerCamelCase. (lib/Routes.dart, line 4, col 17)
[lint] Name non-constant identifiers using lowerCamelCase. (lib/Routes.dart, line 5, col 17)
[lint] Annotate overridden members (lib/UserProfile.dart, line 8, col 10)
[hint] Unused import (lib/UserProfile.dart, line 2, col 8)
[lint] 137 public members lack documentation (ran in 34.1s)

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mrugendrathattle/Research/Flutter/flutter
    • Framework revision edbe034847 (5 days ago), 2016-10-19 16:10:46
    • Engine revision 525c947ece
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/mrugendrathattle/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[-] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a
    x Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] Connected devices
    • iPhone SE • 215A9935-BD79-4FAE-8DDB-49BE6CCBDA19 • ios (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mrugendra** [comment]
if its any help, this is my code, 
3 files:
NewsFeed.dart: model 
NewsFeedItem: renders an news list item <= this is where it crashes in onTap and onLongPress
NewsList: fetches the data from internet and creates a list



[Archive.zip](https://github.com/flutter/flutter/files/549266/Archive.zip)

**Comment by eseidelGoogle** [comment]
`flutter upgrade` might fix.  iOS builds were busted last week for a couple days.  There isn't much that looks relevant from the logs.  It's possible that the Console.app shows a crash log for the Runner process?

**Comment by eukreign** [comment]
I can confirm that the attached code works fine on Android. Must be just iOS issue.

**Comment by mrugendra** [comment]
@eseidelGoogle that worked. thank you
