### ISSUE TITLE
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null':

### ISSUE THREAD

**Issue by ichitaka** [flutter/flutter#65020]
So this exception was triggered when I was trying to find a workaround for this issue: https://github.com/flutter/flutter/issues/63906

Minimal example to trigger the exception:
https://dartpad.dev/caee8917292fba910e759bb84130e637

The code is actually not working as intended with DartPad but the minimal example works as intended on Android.

Currently, I'm trying to use ScrollNotification as a means to deactivate the scrolling for a Widget through changes to the ScrollPhysics by switching between NeverScrollableScrollPhysics and AlwaysScrollableScrollPhysics. 

I'm receiving the following Exception:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null':
is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
```
This was the stack:
```
#2      ScrollableState._handleDragDown  package:flutter/…/widgets/scrollable.dart:527
#3      DragGestureRecognizer._checkDown.<anonymous closure>  package:flutter/…/gestures/monodrag.dart:375
#4      GestureRecognizer.invokeCallback  package:flutter/…/gestures/recognizer.dart:184
#5      DragGestureRecognizer._checkDown  package:flutter/…/gestures/monodrag.dart:375
#6      DragGestureRecognizer.addAllowedPointer  package:flutter/…/gestures/monodrag.dart:238
#7      GestureRecognizer.addPointer  package:flutter/…/
#8      RawGestureDetectorState._handlePointerDown  package:flutter/…/widgets/gesture_detector.dart:1137
#9      RenderPointerListener.handleEvent  package:flutter/…/rendering/proxy_box.dart:2654
#10     GestureBinding.dispatchEvent  package:flutter/…/gestures/binding.dart:200
#11     GestureBinding._handlePointerEvent package:flutter/…/gestures/binding.dart:158
#12     GestureBinding._flushPointerEventQueue  package:flutter/…/gestures/binding.dart:104
#13     GestureBinding._handlePointerDataPacket  package:flutter/…/gestures/binding.dart:88
#17     _invoke1  (dart:ui/hooks.dart:267:10)
#18     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onDown"
Recognizer:
  VerticalDragGestureRecognizer#84916
```

My flutter -doctor output:
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale de-DE)
    • Flutter version 1.20.1 at /Users/tumor/Documents/Projekte/tools/flutter
    • Framework revision 2ae34518b8 (4 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tumor/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[!] Connected device
    • Device emulator-5562 is offline.

! Doctor found issues in 2 categories.
```

My output for flutter run --verbose 

https://justpaste.it/73jzx
(posting it as a link to keep the post tidy) - Also does somebody know how to export the flutter logs directly to a file?

**Comment by pedromassangocode** [comment]
Hi @ichitaka 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by ichitaka** [comment]
I've added everything in my original post. Here the minimal code example again:
https://dartpad.dev/caee8917292fba910e759bb84130e637

Also, just to make things a little clearer the minimal example from the other issue (https://github.com/flutter/flutter/issues/63906), so you can see what I'm trying to accomplish:

https://dartpad.dev/bda4cc5fd2aea292310fe05daa440760

**Comment by pedromassangocode** [comment]
I was able to reproduce this with the latest `master` channel. You can easily reproduce by trying to scroll down once you are at the end of the list.

The issue does not happen if you don't pass the `somePhysics` into the `ListView`.

<details><summary>Logs</summary>

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:571:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:402:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:402:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:265:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#3368a
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 580 pos 12: '_drag == null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.87, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.87 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 4732a214a7 (2 days ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.

```
</details>

**Comment by nydlmaster** [comment]
status of this issue?

**Comment by Piinks** [comment]
Hi @ichitaka It looks like your sample code is nesting scrollables inside one another. 
Super simplified:

```dart
CustomScrollView( // outer scrollable
  slivers: [ 
    SliverAppBar(),
    SliverToBoxAdapter(),
    SliverFillRemaining(
      child: ListView() // inner scrollable
    ),
  ]
)
```

Have you tried composing your widgets with the NestedScrollView? This widget handles a lot of the complexities of nested scrolling for you.
Again super simplified:

```dart
NestedScrollView(
  headerSliverBuilder: (c, i) => SliverAppBar(), // outer
  body: ListView(), // inner
)
```

There is an example in the api docs that creates a similar UI to the one you provided above with the tab bar: https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html 

This also reminds me of https://github.com/flutter/flutter/issues/14452. When using ScrollNotifications to manipulate the scrollable itself, you can run into issues like this where a gesture has not finished being handled, and you end up in an invalid state. In these cases I have seen folks check what *kind* of notification they are getting before safely altering the scroll view.

**Comment by ichitaka** [comment]
> This also reminds me of #14452. When using ScrollNotifications to manipulate the scrollable itself, you can run into issues like this where a gesture has not finished being handled, and you end up in an invalid state. In these cases I have seen folks check what _kind_ of notification they are getting before safely altering the scroll view.

Thank you for your answer. This is also what I think the issue is. On your NestedScrollView suggestion: I currently use NestedScrollView, but I still can't produce the layout with it with a nice UX. I wanted to explore a solution with CustomScrollView but that caused this issue. The suggested NestedScrollView examples sadly are not producing that result either.

With NestedScrollView I'm facing the following issues:

1. As SliverOverlapAbsorber does not work with multiple persistent headers (SliverAppBar + TabBar), my ListView moves behind the second persistent header, causing unsatisfactory UX. (related to https://github.com/flutter/flutter/issues/52616)

Example: https://dartpad.dev/765e39092016076e94fdd10bf1efcfda

2. NestedScrollView does not provide the feature of FlexibleSpace (related to https://github.com/flutter/flutter/issues/54059)

**Comment by Piinks** [comment]
> Thank you for your answer. This is also what I think the issue is. On your NestedScrollView suggestion: I currently use NestedScrollView, but I still can't produce the layout with it with a nice UX. I wanted to explore a solution with CustomScrollView but that caused this issue. The suggested NestedScrollView examples sadly are not producing that result either.

Thanks for the update! I have recreated your dartpad sample with the NestedScrollView here: https://dartpad.dev/f832420f7aa0f191c2cfd53ac8734852
It can be tweaked further, but this basic refactor creates the same UI of your original sample! 🎉 

> With NestedScrollView I'm facing the following issues:
> 
> 1. As SliverOverlapAbsorber does not work with multiple persistent headers (SliverAppBar + TabBar), my ListView moves behind the second persistent header, causing unsatisfactory UX. (related to #22393)

In your reproduction, you don't need to use multiple slivers to create the tabbed heading your demo uses. In `NestedScrollView.headerSliverBuilder`, the `SliverAppBar` can hold everything, and as such it can be wrapped in a `SliverOverlapAbsorber`. The child of the `SliverToBoxAdapter` can instead go in `SliverAppBar.flexibleSpace`, and the `TabBar` can be placed inside `SliverAppBar.bottom` instead of its own independent `SliverPersistentHeader`.

> 1. NestedScrollView does not provide the feature of FlexibleSpace (related to #54059)

`NestedScrollView` does support `SliverAppBar.flexibleSpace`. You can see in the linked DartPad above. The issue you mentioned here is referring to `SliverAppBar.stretch`, which is scheduled for support this Fall. :)

Let me know how that DartPad works out for you, and perhaps this can also be posted as a question on StackOverflow? It appears to be a composition question, and there may be a lot of different ways to achieve the same effect.

**Comment by ichitaka** [comment]
Thank you for the effort! The question if this is a composition problem is difficult. Maybe I could build a custom NestedScrollView. Coming from other frameworks I think it is quite surprising, that this kind of multi-level-hierarchy is not possible with basic Widgets. I think I do not have a choice, but to wait for the Fall update.

I knew about the bottom parameter of the SliverAppBar, but I have issues with this approach:
1. I have to add an empty sized widget in the flexible space, so that the TabBar does not go over the Widgets in the flexiblespace.
2. I have to force some size to the widgets, to fill the extendedHeight parameter. This is impossible when using Widgets with undefined sizes, like Columns or Rows where the size is based on the content.
3. I might want to include an image in that flexiblespace (Common hero design pattern). The transition of the AppBar to the backgroundColor happens when the last element reaches the top. It becomes more difficult to design the AppBar contents, as the content of the flexiblespace now has information based content (mostly black on white or white on black). Sadly I can't customize the transition. I've added some pictures to make this clear.
![Screenshot_1601570321](https://user-images.githubusercontent.com/10514396/94838601-1f8c1d80-0416-11eb-89b0-ad4737ddbc7c.png)
