### ISSUE TITLE
Documentation for InputDecoration gives accent to wrong words

### ISSUE THREAD

**Issue by broccolism** [flutter/flutter#65034]
I found out this using Flutter as in my work.
Below is the documentation of `InputDecoration`'s `contentPadding` property.

![docs issue](https://user-images.githubusercontent.com/45515332/91888176-cfab2100-ecc6-11ea-9de0-38ea31afe99e.png)

As you may see, documentation's accent seems something wrong.
For example,  "`. If ` isOutline` property of [border] is false and if [filled] is false then `contentPadding` is `EdgeInsets.fromLTRB(0, 8, 0,......" in line 5 in the picture.

I think this should be fixed. Thanks!

**Comment by darshankawar** [comment]
Correct accent should be:
If `isOutline` property of [border] is false and if [filled] is false then `contentPadding` is `EdgeInsets.from LTRB(0,8,08)` when [isDense] is true and `EdgeInsets.fromLTRB(0,12,0,12)` when [isDense] is false.

**Comment by TomRvr** [comment]
Hi !  
I fixed the accent issue and submitted a PR https://github.com/flutter/flutter/pull/65094  

It's my first contribution, let me know if I did Something wrong.

**Comment by TomRvr** [comment]
Hi !  
I fixed the accent issue and submitted a PR https://github.com/flutter/flutter/pull/65094  

It's my first contribution, let me know if I did Something wrong.

**Comment by TomRvr** [comment]
Hi !  
I fixed the accent issue and submitted a PR https://github.com/flutter/flutter/pull/65094  

It's my first contribution, let me know if I did Something wrong.

**Comment by TomRvr** [comment]
Hi !  
I fixed the accent issue and submitted a PR https://github.com/flutter/flutter/pull/65094  

It's my first contribution, let me know if I did Something wrong.

**Comment by DeadlyMissile** [comment]
PR was merged. This can be closed

**Comment by darshankawar** [comment]
Closing this as fixed. Please check in latest master.
