### ISSUE TITLE
SliverList with Streambuilder always jumps to top (unable to save scroll state)

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#65035]
with  CustomScrollView  key there is no problem when switching between views.
```
return CustomScrollView(
      key: const PageStorageKey<String>('promo_list_csrv'),
```
but when there is  SliverList builded by **streambuilder** as a child to CustomScrollView it jumps to top when switching views.
did not found any solutions to force saving SliverList position state.

**Comment by darshankawar** [comment]
Hi @Xgamefactory,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
