### ISSUE TITLE
[cocoon] Dashboard opens popup and cannot scroll whole thing into view

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#65030]
![image](https://user-images.githubusercontent.com/8620741/91878046-a2616300-ec33-11ea-9192-b741e58c7e9f.png)

The right side of this screenshot is the edge of my browser window. When the popup is open, the grid is not scrollable. 

We should:

- Make sure the popup opens fully in the screen
- Make sure the grid is scrollable with thepopup open.

**Comment by dnfield** [comment]
This is particularly problematic if you try to view the popup for a column on the extreme right hand side of the grid, where even scrolling further doesn't help.

**Comment by digiter** [comment]
Triage: is there anything remaining?

**Comment by dnfield** [comment]
I think we can close this. I'm not sure actually scrolling the grid when the popup is open is important.
