### ISSUE TITLE
 fidl::internal::MessageReader::Bind crash in Flutter runner

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#65038]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=59293

We're presently waiting for the Fuchsia team to see if it's an issue with the Flutter runner or engine itself that requires our action.

This is a chaselist issue for Fuchsia.

cc @zanderso @iskakaushik @chinmaygarde as FYI, although presently no action required.

**Comment by kf6gpe** [comment]
Tuesday triage update: upstream issue notes that relevant code has landed, but waiting for rolls to determine whether the issue is fully fixed. No action needed from the Flutter team at present.

**Comment by chinmaygarde** [comment]
Looks fixed.
