### ISSUE TITLE
Flutter framework `customer_testing` tests cocoon with latest Flutter SDK, while cocoon CI uses stable SDK

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#65045]
In https://github.com/flutter/flutter/issues/65041, a change to `dartfmt` caused the `customer_testing` shard cocoon test to fail the formatter test. When trying to [update cocoon with the new formatting](https://github.com/flutter/cocoon/pull/931), Cocoon CI failed because it is based on Flutter stable SDK.

If cocoon's test suite is included in `customer_testing`, then Cocoon's CI should use the latest Flutter SDK, to minimize the time Cocoon's CI is broken. If Cocoon's CI needs to use stable Flutter SDK, then it should be removed from `customer_testing` (which usually runs latest SDK).

The version of the Flutter SDK used in Cocoon CI is defined in https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/cocoon.py#36.

**Comment by keyonghan** [comment]
Shall we update cocoon CI to use latest SDK, or the other way around?

**Comment by christopherfujino** [comment]
> Shall we update cocoon CI to use latest SDK, or the other way around?

I fleshed out the description.

**Comment by christopherfujino** [comment]
I'm not sure which version of Flutter we use for prod, but I'm guessing CI should use the same.

**Comment by CaseyHillers** [comment]
Would it be okay to remove the dartfmt checks from flutter/tests? The more important part is the tests.

**Comment by christopherfujino** [comment]
> Would it be okay to remove the dartfmt checks from flutter/tests? The more important part is the tests.

What do we do if a non-formatting breaking change happens that breaks Cocoon tests? I disabled the flutter/tests cocoon tests after hacking around the formatting issue an API change was still failing for Cocoon.

**Comment by CaseyHillers** [comment]
> What do we do if a non-formatting breaking change happens that breaks Cocoon tests? I disabled the flutter/tests cocoon tests after hacking around the formatting failure but updating Cocoon to latest in the registry picked up an API change that failed.

In this case, I think a breaking change to Cocoon's tests should then follow [Flutter's breaking change policy](https://flutter.dev/docs/resources/compatibility).

Since customer tests run in presubmit, developers have been able to update Cocoon to conform to updates without needing to go through the breaking change policy.

**Comment by christopherfujino** [comment]
> > What do we do if a non-formatting breaking change happens that breaks Cocoon tests? I disabled the flutter/tests cocoon tests after hacking around the formatting failure but updating Cocoon to latest in the registry picked up an API change that failed.
> 
> In this case, I think a breaking change to Cocoon's tests should then follow [Flutter's breaking change policy](https://flutter.dev/docs/resources/compatibility).
> 
> Since customer tests run in presubmit, developers have been able to update Cocoon to conform to updates without needing to go through the breaking change policy.

But then to land the change, they'd have to land on red (since tests run on stable). And cocoon ci would stay red until the Flutter breaking change is published to stable. Also, does Cocoon run master? If not, then applying a breaking change could break Cocoon.

Per @godofredoc , I think he said CI used to run on master, but it would frequently be broken.

**Comment by CaseyHillers** [comment]
In the case of https://github.com/flutter/tests/pull/34 (IIRC Cocoon was running on stable) Cocoon was able to be rolled forward. No need to land on red.

I think these cases where it causes deadlock require a soft transition. With test code that should be possible, right?

**Comment by christopherfujino** [comment]
In this case, methods were renamed https://github.com/flutter/flutter/commit/4d8934af485

**Comment by CaseyHillers** [comment]
There's some issues with Cocoon when running tests on Windows. These have crept in as Cocoon's CI is only a Linux bot. There's two paths forward:
1. Drop windows coverage of Cocoon in customer_tests.
2. Add windows builder to Cocoon and fix the outstanding issues. Maintain Cocoon Windows support.

@godofredoc what do you think? #2 is a few hours of work to get the builder running and Cocoon fixed.
