### ISSUE TITLE
app_flutter test in customer_testing is blocking the engine roll

### ISSUE THREAD

**Issue by flar** [flutter/flutter#65041]
See this log for details: https://api.cirrus-ci.com/v1/task/5569311278366720/logs/main.log

We have a PR that will adjust the file for the latest dartfmt rules, but there is a question as to whether there is a chicken-and-egg issue related to deploying this before the dart version rolls with the engine. See https://github.com/flutter/cocoon/pull/931

**Comment by flar** [comment]
Tagging @jason-simmons @christopherfujino who were involved in the discussion.

**Comment by flar** [comment]
There is now discussion about whether dartfmt should have rejected this file in the first place. The line was more than 80 characters, but dartfmt is run with a requested line length of 120, so it shouldn't have required reformatting.

This may be a bug in the dartfmt command in the latest Dart roll.

**Comment by flar** [comment]
As mentioned in the PR, the change to the way that `dartfmt` wants to format nested conditional expressions was intentional, so this is not a bug.

There is also a potential formatting that would make both versions of `dartfmt` happy so we can avoid the chicken and egg issue of which Dart version is running a given Cocoon instance.

**Comment by keyonghan** [comment]
Formatting issue have been fixed by https://github.com/flutter/cocoon/pull/931.

Now the roll is still blocked by `flutter analyze`.
```
info • This method overrides a method annotated as '@mustCallSuper' in 'RenderObjectElement', but doesn't invoke the overridden method • lib/widgets/lattice.dart:280:8 • must_call_super
   info • This method overrides a method annotated as '@mustCallSuper' in 'RenderObjectElement', but doesn't invoke the overridden method • lib/widgets/lattice.dart:285:8 • must_call_super
   info • This method overrides a method annotated as '@mustCallSuper' in 'RenderObjectElement', but doesn't invoke the overridden method • lib/widgets/lattice.dart:290:8 • must_call_super
```

Here is a potential fix: https://github.com/flutter/tests/pull/49

**Comment by keyonghan** [comment]
Fix has been submitted. Closing.
