### ISSUE TITLE
[devicelab] Presubmit on LUCI

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#65046]
Plan
- [ ] Cocoon backend reads the devicelab manifest.yaml in github_webhook.dart.
- [ ] Cocoon backend schedules a build from each of the tasks marked with `on_luci=true`, so that each devicelab task is a single build.
- [ ] Cocoon backend reports the build result to GitHub checks. If a task is marked `is_flaky` then the result will be neutral.
- [ ] Document how to recover the bots.

/cc @godofredoc @keyonghan

**Comment by godofredoc** [comment]
I'd also add how to present the builders in flutter-dashboard

**Comment by digiter** [comment]
> I'd also add how to present the builders in flutter-dashboard

Could you elaborate more on this? We already can view the builders on Milo: https://ci.chromium.org/p/flutter/g/framework-try/builders

**Comment by godofredoc** [comment]
Flutter SDK team does not use milo, we would like to get the results in flutter dashboard. E.g.:

![image](https://user-images.githubusercontent.com/54371434/91902405-84592a00-ec56-11ea-9770-35072f1b1eca.png)

**Comment by digiter** [comment]
The flutter dashboard shows builders from post-submit, this bug is about pre-submit.

**Comment by godofredoc** [comment]
Obsolete: two of the items in this plan were implemented. Reading and using the configurations from manifest.yaml was implemented slightly different.
