### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted  Command: /Users/sparkle-star/Documents/sparkle_seller_app/android/gradlew -q -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Psplit-per-abi=true -Pshrink=true assembleRelease

### ISSUE THREAD

**Issue by markjoseultra** [flutter/flutter#65063]
## Command
```
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
```

## Logs
ProcessException: ProcessException: Operation not permitted
  Command: /Users/sparkle-star/Documents/sparkle_seller_app/android/gradlew -q -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Psplit-per-abi=true -Pshrink=true assembleRelease
```

```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E2269, locale en-PH)
    • Flutter version 1.17.5 at /Users/sparkle-star/Developer/flutter
    • Framework revision 8af6b2f038 (9 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sparkle-star/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • SM G950F          • ce07171744102cd10c                   • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max • C24A0DF7-43B4-44AB-A47A-E94FDE98F9E7 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.0.1+13
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
flutter_plugin_android_lifecycle-1.0.8
flutter_secure_storage-3.3.3
image_cropper-1.3.0
image_picker-0.6.7+4
package_info-0.4.1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1

**Comment by darshankawar** [comment]
Hi @markjoseultra,
There was a recent [fix](https://github.com/flutter/flutter/pull/63540) made and merged in Master. Please switch to latest master and see if it works for you.
Thanks.

**Comment by devmgs** [comment]
I was able to resolve the issue by deleting android folder and recreating it.

https://github.com/flutter/flutter/issues/65149

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by anaman9** [comment]
create a new project..
just replace gradlew file from new project to old project..

and just boom.
