### ISSUE TITLE
☂️ On Windows minimizing the app window will modify the contents of the frame

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#65061]
This is an umbrella issue for capturing the problems that we see as a result of sending a zero size update window metrics event on window minimize on platform-windows.

The following issues are all a result of this, and we must verify that all these will be fixed before closing this issue:

- [x] #55262
- [x] #64718 
- [x] #64629 
- [x] #66636

Edit on 12 OCT 2020 (by @iskakaushik): updated the bug to mark this as an umbrella issue, and included more related issues.

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Icon(Icons.directions_car),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.39, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.39 at C:\Code\flutter_master
    • Framework revision a8281e31af (15 hours ago), 2020-09-01 10:57:59 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
@clarkezone Since we're now manually controlling the resize, we could potentially ignore the 0x0 size notification and leave the previous size buffer in place, right?

At some point we'll need a notion of "not visible" for all the desktop platforms for efficiency, but I think we'd want to do that through a mechanism other than setting a 0x0 drawing context.

**Comment by clarkezone** [comment]
We could consider that although I would want to confirm the guidance first.  In the UWP model there is an explicit suspend / resume semantic which makes it easier to know when to unload resources.  I believe that's coming to win32 as well as part of reunion: https://github.com/microsoft/ProjectReunion/issues/111

**Comment by xu-baolin** [comment]
Another relation issue #66636

**Comment by iskakaushik** [comment]
cc: @iskakaushik

**Comment by xu-baolin** [comment]
@dnfield FYI

**Comment by iskakaushik** [comment]
Some additional notes at: https://github.com/flutter/flutter/pull/65015#issuecomment-707231154

**Comment by dnfield** [comment]
Adding here: When we get the WM_SIZE message we should be checking whether the wparam is SIZE_MINIMIZED. https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size?redirectedfrom=MSDN

Specifically here: https://github.com/flutter/engine/blob/master/shell/platform/windows/win32_window.cc#L125

**Comment by stuartmorgan** [comment]
> we should be checking whether the wparam is SIZE_MINIMIZED

The question is what we do with that information; I don't think continuing to draw at the previous size indefinitely is the right solution (although it might be viable in the short term now, per my comments above). Ideally we should have a way to tell the engine to stop drawing until further notice.

**Comment by dnfield** [comment]
@stuartmorgan - correct, we should send an inactive message to the framework and pause the animator. We should then resume animation once we get a new WM_SIZE message that we've been restored.

**Comment by loic-sharma** [comment]
Hello, it seems all bugs linked to this umbrella issue have been fixed. The final piece is to implement lifecycle events, which is tracked by https://github.com/flutter/flutter/issues/103637. I'll close this umbrella issue, but feel free to create new issues if you find more bugs related to minimizing the app window!
