### ISSUE TITLE
^C on flutter run shows dialog on device

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6506]
If I do `flutter run` then hit Control-C, I get a dialog on the device saying the app has stopped, as if it had crashed.

**Comment by jason-simmons** [comment]
At shutdown time Flutter processes are segfaulting in Dart's Process_Exit when it tries to invoke the exit hook.  Process_Exit is casting Dart_CurrentIsolateData to a dart::bin::IsolateData*, which doesn't match the structure used by Flutter.

@rmacnak-google @a-siva

**Comment by jason-simmons** [comment]
This should be fixed in Dart now
