### ISSUE TITLE
Android Studio Not installed [Linux] pop os 20.04

### ISSUE THREAD

**Issue by steelx** [flutter/flutter#65068]
when I run `flutter doctor`
I get following message: as well I cannot run `flutter run` since it is not able to find running emulators. 
```
❯ flutter doctor -v
[✓] Flutter (Channel beta, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at
      /home/ajinkya/snap/flutter/common/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09
      -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /home/ajinkya/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-post-Ubuntu-0ubuntu120.04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).


Scanning for devices is taking a long time...⣽
```

But I have all installed already:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/cbKmq.png

**Comment by pedromassangocode** [comment]
Hi @steelx  based on you `flutter doctor -v` output I can see that your Android license status is Unknown, please follow the suggested link (https://flutter.dev/docs/get-started/install/linux#android-setup) to fix that. After that please provide your `flutter doctor -v` again.

>     ✗ Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit
>       https://flutter.dev/docs/get-started/install/linux#android-setup
>       for detailed instructions.

**Comment by steelx** [comment]
> Hi @steelx based on you `flutter doctor -v` output I can see that your Android license status is Unknown, please follow the suggested link (https://flutter.dev/docs/get-started/install/linux#android-setup) to fix that. After that please provide your `flutter doctor -v` again.
> 
> > ```
> > ✗ Android license status unknown.
> >   Try re-installing or updating your Android SDK Manager.
> >   See https://developer.android.com/studio/#downloads or visit
> >   https://flutter.dev/docs/get-started/install/linux#android-setup
> >   for detailed instructions.
> > ```

Im getting following error on visiting licenses.
```bash
❯ ./sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by steelx** [comment]
added JAVA_HOME

but now getting this error:
```
❯ ./sdkmanager --licenses

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-11-openjdk-amd64/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by steelx** [comment]
> Hi @steelx based on you `flutter doctor -v` output I can see that your Android license status is Unknown, please follow the suggested link (https://flutter.dev/docs/get-started/install/linux#android-setup) to fix that. After that please provide your `flutter doctor -v` again.
> 
> > ```
> > ✗ Android license status unknown.
> >   Try re-installing or updating your Android SDK Manager.
> >   See https://developer.android.com/studio/#downloads or visit
> >   https://flutter.dev/docs/get-started/install/linux#android-setup
> >   for detailed instructions.
> > ```



updated JAVA and PATH.


```bash
❯ javac -version
javac 1.8.0_265
❯ flutter doctor -v
[✓] Flutter (Channel beta, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at
      /home/ajinkya/snap/flutter/common/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09
      -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /home/ajinkya/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by steelx** [comment]
following PATH worked for me: `~/.zshrc`
```

#export JAVA_HOME=/usr/lib/jvm/default-java
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

export PATH=$JAVA_HOME/bin:$PATH
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH="/usr/lib/dart/bin:$PATH"
```

**Comment by pedromassangocode** [comment]
Hi @steelx 
Can you confirm that this issue can be closed?
Thanks

**Comment by steelx** [comment]
> Hi @steelx 
> Can you confirm that this issue can be closed?
> Thanks

Android studio not installed issue is there in cmd..but all works fine. (ʘᴗʘ✿)

You may close the issue

**Comment by pedromassangocode** [comment]
Hi @steelx 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
