### ISSUE TITLE
Build Time Error : "The batch file cannot be found"

### ISSUE THREAD

**Issue by arihantj13** [flutter/flutter#65077]
`
![Screenshot (8)](https://user-images.githubusercontent.com/56602519/91941594-13c61200-ed17-11ea-8f7c-0fc4eb8beda0.png)
Since last 30 days I'am facing this problem, after downloading flutter sdk, android studio. I setup environment variables and all, after that my first project is running normally but when i created another projects which is not running at all and showing the same error 
**Unable to locate gradlew script. Please check that D:\Projects\Intro2\android\gradlew.bat exists or that D:\Projects\Intro2\android can be read and then showing Exited (sigterm)**
I have installed flutter sdk so many time since last 30 days.
What is this problem?

**Comment by hamdikahloun** [comment]
Hi @arihantj13 

Can you provide please:

- `flutter doctor -v`

- `flutter run -v`

Thank you

**Comment by pedromassangocode** [comment]
Hi @arihantj13 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you

**Comment by arihantj13** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/56602519/91962211-d7e87800-ed29-11ea-9a29-251a090d07b7.png)
![Screenshot (16)](https://user-images.githubusercontent.com/56602519/91962215-da4ad200-ed29-11ea-9bc6-63f48bd036cb.png)
![Screenshot (17)](https://user-images.githubusercontent.com/56602519/91962217-dae36880-ed29-11ea-93c9-36b258d4b59c.png)
![Screenshot (18)](https://user-images.githubusercontent.com/56602519/91962219-db7bff00-ed29-11ea-9b75-af0d69cbfb93.png)
@hamdikahloun

**Comment by arihantj13** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/56602519/91962903-c9e72700-ed2a-11ea-889a-f0286091af5a.png)
![Screenshot (20)](https://user-images.githubusercontent.com/56602519/91962925-cf447180-ed2a-11ea-934e-e518bec9cf08.png)
![Screenshot (21)](https://user-images.githubusercontent.com/56602519/91962927-cfdd0800-ed2a-11ea-98f9-ed02b603ccf4.png)
@pedromassangocode

**Comment by hamdikahloun** [comment]
@arihantj13 

can you please run :

- `flutter doctor --android-licenses` and accept all the licenses

- connect your android phone with USB debugging enabled or start the android emulator, if you haven't any emulator check this [url](https://developer.android.com/studio/run/managing-avds) .

- `flutter create newapp`

- `cd newapp`

- `flutter run -v`

**Comment by arihantj13** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/56602519/91964874-54c92100-ed2d-11ea-912c-a32a26f3a0ef.png)
![Screenshot (23)](https://user-images.githubusercontent.com/56602519/91964879-572b7b00-ed2d-11ea-83f8-0d6ebac4df4f.png)
![Screenshot (24)](https://user-images.githubusercontent.com/56602519/91964884-58f53e80-ed2d-11ea-9116-ee3af4cc1298.png)
![Screenshot (25)](https://user-images.githubusercontent.com/56602519/91964890-5a266b80-ed2d-11ea-85ea-1f56bf2dd8e0.png)
![Screenshot (26)](https://user-images.githubusercontent.com/56602519/91964892-5abf0200-ed2d-11ea-8366-60dd9c8a4693.png)
@hamdikahloun

**Comment by hamdikahloun** [comment]
@arihantj13 

- don't forget to connect your android phone with USB debugging enabled or start the android emulator, if you haven't any emulator check this url : https://developer.android.com/studio/run/managing-avds .

- `flutter doctor --android-licenses` and accept all licenses

- `flutter devices`

**Comment by arihantj13** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/56602519/91973308-a9729900-ed39-11ea-9fad-66b356432ceb.png)
![Screenshot (28)](https://user-images.githubusercontent.com/56602519/91973313-ac6d8980-ed39-11ea-9d75-8745e165b392.png)
![Screenshot (29)](https://user-images.githubusercontent.com/56602519/91973319-ad062000-ed39-11ea-8ec0-96b5d85f7114.png)
@hamdikahloun

**Comment by hamdikahloun** [comment]
@arihantj13 

I suggest you to delete the installed Android studio, Download the new version from here :https://developer.android.com/studio and reinstall it. Don't forget to start android studio after the installation, finish all the steps and create new emulator. 
Delete everything in D:\flutter\bin\cache\downloads ,run `flutter doctor`  and try again .

**Comment by pedromassangocode** [comment]
Hi @arihantj13 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`? Please provide the outputs as copy/paste here a text, if GitHub complains you can share it as `.txt` file.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by fantania** [comment]
Hi, is this issue resolved? I’m getting the same issue when I create a new project

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
