### ISSUE TITLE
Find text containing some string in tests

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#65070]
## Use case

If you have a longer dynamic text and you want to test that it contains a specific word for example this is very useful.

## Proposal

```
expect(find.textContaining('test'), findsOneWidget);
```

should be good if there is some text like 'this is a test'.

Also finding editable texts based on a fragment would be useful as well.

**Comment by LongCatIsLooong** [comment]
Do you think it would be a good idea to make the existing text finder take a `Matcher`? This should yield a more composable API. The new `find.text` method will take a `dynamic`,  you would be able to do `find.text(contains('test'))` or `find.text((String s) => s.contains('text'))`, and it is still compatible with the current API `find.text('test')`. There's a utility function in the matcher package that allows you to convert a `dynamic` to a `Matcher`: https://api.flutter.dev/flutter/package-matcher_matcher/wrapMatcher.html. 

As for the downside, I find it a bit weird to use a `Matcher` in the left hand side of the `expect`, and using `dynamic` means we're sacrificing the type safety.

**Comment by TheBiirb** [comment]
PR was merged. Should we close this?

**Comment by christian-muertz** [comment]
@LongCatIsLooong the current implementation does enough for me for now.

I'll close this issue.
