### ISSUE TITLE
Flutter native bluetooth support

### ISSUE THREAD

**Issue by 7heViking** [flutter/flutter#65076]
**Feature request: Bluetooth**
I would like to see native Flutter support for bluetooth. I know there are third party plugins, but I would like to see this basic communication feature maintained an published by Flutter.

It will give you peace in mind, that the maintenance/development of the plugin does not suddenly stop but it backed by Flutter.

**Comment by darshankawar** [comment]
Hi @7heViking,
There's similar open issue describing your case, [53493](https://github.com/flutter/flutter/issues/53493).
Please follow-up there for updates and any questions.
Closing this as duplicate.
