### ISSUE TITLE
When run "flutter build web",the command line show "build web" is not currently supported?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#65073]
I will show what the problem happened, this is the steps:

At first when I use the command"flutter create .", the command line shows the problems following,and I can't find the "Web" file in the my project root files. What happened?

```
Recreating project ....
Wrote 3 files.

All done!
```

And then when I use the command"flutter build web", the command line shows the problems following:

```
"build web" is not currently supported.
```

Excuse me.Are there any tools that are not installed？

and then I input the conmand"flutter doctor -v", and this is my tool versions:

```
# 
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.20.2 at E:\develop\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\develop\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\develop\sdk
    • Java binary at: E:\develop\android-studio-ide-193.6107147-windows(4.0canary8)\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\develop\android-studio-ide-191.6010548-windows(3.5.3)
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at E:\develop\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

You can see , I had installed the following tools,just like:
 flutter SDK, JDK, Android SDK, environment variable, IDEA flutter plugins.

By the way, I had install `webdev` and `stagehand`, and I use `IntelliJ IDEA(2019.2)` to create flutter project and use the command to build flutter web.

You see I have ths problems above, so what's wrong?

**Comment by neev123dev** [comment]
hey do you have a web folder??

**Comment by piedcipher** [comment]
@AweiLoveAndroid You're using stable version of flutter SDK which doesn't have web support.

https://flutter.dev/docs/get-started/web

**Comment by darshankawar** [comment]
Hi @AweiLoveAndroid,
Please see [this](https://flutter.dev/docs/get-started/web) document for building web apps in Flutter. You need to be in beta to be able to create web app.
Closing this as non-issue.

**Comment by AweiLoveAndroid** [comment]
@darshankawar  Thanks a lot

**Comment by AweiLoveAndroid** [comment]
@piedcipher Thanks a lot
