### ISSUE TITLE
Application hangs after you minimize it and restore it back - Android v7  and Flutter v1.20.2 issue only

### ISSUE THREAD

**Issue by KengooMurzik** [flutter/flutter#65089]
Hi 

I'm dealing with problem, after the latest flutter update.
This happens on Android v7 only and with the latest version of flutter only. Rolling back to the v1.19 or earlier fies the prblem.

The application works ok, but it stops working after you minimize it and restore back.

here is the error from debug console:

```
E/Surface ( 5324): queueBuffer: error queuing buffer to SurfaceTexture, -19
E/EGL_emulation( 5324): tid 5483: swapBuffers(531): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation( 5324): egl_window_surface_t::swapBuffers called with NULL buffer
E/EGL_emulation( 5324): tid 5483: swapBuffers(498): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation( 5324): egl_window_surface_t::swapBuffers called with NULL buffer
E/EGL_emulation( 5324): tid 5483: swapBuffers(498): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation( 5324): egl_window_surface_t::swapBuffers called with NULL buffer
E/EGL_emulation( 5324): tid 5483: swapBuffers(498): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation( 5324): egl_window_surface_t::swapBuffers called with NULL buffer
```

**Comment by hamdikahloun** [comment]
Hi @KengooMurzik 

you can check this issue for more information : [https://github.com/flutter/flutter/issues/64414](https://github.com/flutter/flutter/issues/64414) .

**This issue was fixed in beta channel**

- `flutter channel beta`

- `flutter upgrade`

**Comment by darshankawar** [comment]
@KengooMurzik,
This seems to be a similar issue reported in 64414 and as stated in it, the fix was pushed in beta. Please switch to beta and then upgrade and see if it works for you, or you may have to wait till the fix reaches stable.
Thanks.

**Comment by KengooMurzik** [comment]
Thanks! The fix from beta works.
I'll for the next stable version.

Closing the issue
