### ISSUE TITLE
Hot reload "syncing files to device" takes a long time

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6508]
Can we maybe compress the files or find a quicker way to send them or send them with the initial package or something?

**Comment by johnmccutchan** [comment]
Re-compression: We are already using gzip compression over an HTTP put.

We might want to try bundling an initial version of the source into the APK/IPA.

Is this in reference to the initial copy of the files that happens before we start the application or the syncing of the remaining that happens while the app is launching? If it is the latter, I think we can make that faster by not doing it at all.

**Comment by Hixie** [comment]
This is in reference to the time you see the progress meter on the device.

But more broadly, my interest is in minimising the time from starting "flutter run" to having the device be responsive with your app loaded.

**Comment by johnmccutchan** [comment]
When the progress meter is on the device we do the following:

1. Use the snapshot binary to quickly determine the minimal set of Dart sources actually loaded by your program. We don't build a snapshot but rely on the VM's parser to determine the transitive import set. This is very fast.
2. Begin sending over the Dart sources via HTTP PUT compressed with gzip. This isn't that fast but I'm not sure what could be done to speed it up.
3. Send over all assets via HTTP PUT compressed with gzip. This isn't that fast but I'm not sure what could be done to speed it up.
4. Start the program

**Comment by Hixie** [comment]
How much data are we sending and what's the overall average data rate?
