### ISSUE TITLE
Chinese + number combination. The number cannot be displayed

### ISSUE THREAD

**Issue by zhangyingcheng** [flutter/flutter#65084]
### Code:
```dart
Container(
        alignment: Alignment.centerLeft,
        color: Colors.red,
        height: 40.0,
        child: Text(
          '这是一段中文字123456789123456789123456789123456789',
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
      )
```

show：
![image](https://user-images.githubusercontent.com/20310744/91962134-b47bf800-ed3e-11ea-925a-548d2b56b57f.png)

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

**Comment by hamdikahloun** [comment]
### Same result

**这是一段中文字123456789123456789123456789123456789** :

![image](https://user-images.githubusercontent.com/32666446/91972093-7a006400-ed1a-11ea-89ee-abe027faebfa.png)

**这是一段中文字qwertyazerty123456789** :

![image](https://user-images.githubusercontent.com/32666446/91972669-4e31ae00-ed1b-11ea-9044-2d16c13ec04e.png)

```
flutter doctor -v
[√] Flutter (Channel master, 1.22.0-10.0.pre.36, on Microsoft Windows [version 10.0.17763.973], locale fr-FR)
    • Flutter version 1.22.0-10.0.pre.36 at C:\Users\Lenovo\Documents\flutter
    • Framework revision 728fdc06ce (24 hours ago), 2020-09-01 11:40:50 +0100
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.0.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.0.28803.202
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • STK L21 (mobile)  • XMJ4C19B09007407 • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [version 10.0.17763.973]

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @zhangyingcheng,
Can you try by adding chinese escape char before every chinese character and then see if it works for you ?
Thanks.

**Comment by TahaTesser** [comment]
Hi @zhangyingcheng 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
