### ISSUE TITLE
climax app

### ISSUE THREAD

**Issue by Jonex171** [flutter/flutter#65091]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty):
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///home/jonex/AndroidStudioProjects/climax/lib/main.dart:10:12
When the exception was thrown, this was the stack: 
#0      _LoadingScreenState.getLocationData.<anonymous closure> (package:climax/Screen/loading_screen.dart:25:45)
#1      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:87:27)
#2      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:710:43)
#3      Builder.build (package:flutter/src/widgets/basic.dart:6757:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
...

**Comment by hamdikahloun** [comment]
Hi @Jonex171 

Can you provide please:

- `flutter doctor -v`

- `flutter run -v`

- minimal complete reproducible code sample

**Comment by darshankawar** [comment]
@Jonex171,
Please provide above details. Only providing the exception won't help to analyze the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
