### ISSUE TITLE
Flutter Connectivity iOS `null` values

### ISSUE THREAD

**Issue by johnwargo** [flutter/flutter#65093]
I have an application using the latest Connectivity plugin (^0.4.9+2) and the instructions on the page say:

To request location authorization, make sure to add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

* NSLocationAlwaysAndWhenInUseUsageDescription - describe why the app needs access to the user’s location information all the time (foreground and background). This is called Privacy - Location Always and When In Use Usage Description in the visual editor.
* NSLocationWhenInUseUsageDescription - describe why the app needs access to the user’s location information when the app is running in the foreground. This is called Privacy - Location When In Use Usage Description in the visual editor.

but when I ran the app with both of those descriptions set, the app complained (in the console) that I had incorrect settings and recommended only using `NSLocationWhenInUseUsageDescription` (I don't remember the exact error message, sorry and I can't reproduce right now).

With the setting set correctly, the app prompts me for location permission as expected, but when I run the following code, I get null values for Wi-Fi name and BSSID.  It feels like the instructions are missing something. Can someone please help me resolve this?

```dart
try {
   if (Platform.isIOS) {
      LocationAuthorizationStatus status =
          await _connectivity.getLocationServiceAuthorization();
      if (status == LocationAuthorizationStatus.notDetermined) {
          status =
              await _connectivity.requestLocationServiceAuthorization();
       }
       if (status == LocationAuthorizationStatus.authorizedAlways ||
          status == LocationAuthorizationStatus.authorizedWhenInUse) {
             wifiName = await _connectivity.getWifiName();
        } else {
             wifiName = await _connectivity.getWifiName();
         }
     } else {
         wifiName = await _connectivity.getWifiName();
     }
    on PlatformException catch (e) {
          print(e.toString());
          wifiName = "Failed to get Wi-Fi Name";
        }
        print('Wi-Fi Name: $wifiName');

        try {
          if (Platform.isIOS) {
            LocationAuthorizationStatus status =
                await _connectivity.getLocationServiceAuthorization();
            if (status == LocationAuthorizationStatus.notDetermined) {
              status =
                  await _connectivity.requestLocationServiceAuthorization();
            }
            if (status == LocationAuthorizationStatus.authorizedAlways ||
                status == LocationAuthorizationStatus.authorizedWhenInUse) {
              wifiBSSID = await _connectivity.getWifiBSSID();
            } else {
              wifiBSSID = await _connectivity.getWifiBSSID();
            }
          } else {
            wifiBSSID = await _connectivity.getWifiBSSID();
          }
        } on PlatformException catch (e) {
          print(e.toString());
          wifiBSSID = "Failed to get Wi-Fi BSSID";
        }
```

**Comment by hamdikahloun** [comment]
Hi @johnwargo 

Check please this url for more details about Connectivity Plugin : https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity

iOS 12
To use .getWifiBSSID() and .getWifiName() on iOS >= 12, the Access WiFi information capability in XCode must be enabled. Otherwise, both methods will return null.

iOS 13
The methods .getWifiBSSID() and .getWifiName() utilize the CNCopyCurrentNetworkInfo function on iOS.

As of iOS 13, Apple announced that these APIs will no longer return valid information. An app linked against iOS 12 or earlier receives pseudo-values such as:

SSID: "Wi-Fi" or "WLAN" ("WLAN" will be returned for the China SKU).

BSSID: "00:00:00:00:00:00"

An app linked against iOS 13 or later receives null.

The CNCopyCurrentNetworkInfo will work for Apps that:

The app uses Core Location, and has the user’s authorization to use location information.

The app uses the NEHotspotConfiguration API to configure the current Wi-Fi network.

The app has active VPN configurations installed.

**Comment by darshankawar** [comment]
HI @johnwargo,
I see a similar [open](https://github.com/flutter/flutter/issues/51529) issue happening on Android specifically and also see that you've commented on it too.
Since it seems to be an issue with the plugin itself, I guess it's affecting iOS too. 
Do you think your issue can be described there and we can add ios platform too indicating it's happening on both platforms ?
Thanks.

**Comment by johnwargo** [comment]
@hamdikahloun I referenced the instructions at that URL in my post. Why did you feel the need to point me to somewhere where I already demonstrated that I've been? Thank you, but that response doesn't do anything to answer my question.

**Comment by johnwargo** [comment]
@darshankawar yeah, I think the plugin's borked. The Android one has a solution and I published a complete example app for it. In that case it was related to a change in how Google handles permissions and there was a plugin available that helped resolve  it. 

I'd rather not add this issue to that one as this is iOS and the other Android (with completely different root causes). In this case, it looks like Apple changed (yet again) how things work and the plugin hasn't been updated to accommodate it. I'm not an iOS developer otherwise I'd jump in and look for a solution (and publish it, of course).

**Comment by darshankawar** [comment]
Hi @johnwargo fair point, thanks for your input.
I replicated the issue on latest stable (1.20.2) and do see `wifi name` and `BSSID` being returned `null`.

![IMG-0203](https://user-images.githubusercontent.com/67046386/92079835-3838f180-edde-11ea-836e-7771a47a1ddf.PNG)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.2 at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (1 available)            
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 13.6

```

</details>

**Comment by johnwargo** [comment]
oooh, I really wish someone would fix this. I would, but I don't have the skills.

**Comment by johnwargo** [comment]
OK, so I just updated everything on my mac (xcode, etc.) and ran it again and it does work. Worked like a champ.
