### ISSUE TITLE
[web] Text containing a "-" does not render correctly on webkit browsers

### ISSUE THREAD

**Issue by Nash0x7E2** [flutter/flutter#65099]
### The Problem 
Content to the right of `Text` containing a hyphen does not render on WebKit browsers. This behavior appears to only be isolated to WebKit since text renders fine on Chrome and Firefox browsers. 

Note, `CanvasKit` was not enabled for this test, this behavior occurs by default. 

![IMG_3624](https://user-images.githubusercontent.com/25674767/91991383-d0f93f80-ed00-11ea-9adb-b5a2b51f9f82.jpg)

### Sample Code 
```dart
import 'package:flutter/material.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Text(
            "E-Whatever",
            style: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ),
    );
  }
}
```

## Steps to Reproduce
1. Create a `Text` widget containing a hyphen. Example: "E-Whatever"
2. Build the project for the web using `flutter build web`
3. Open the website on a WebKit browser (Safari on Mac and iOS)

### Flutter Doctor 
```
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-2.0.pre.105, on Mac OS X 10.15.6 19G2021,
    locale en-TT)
    • Flutter version 1.22.0-2.0.pre.105 at
      /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision cad4d1333e (6 days ago), 2020-08-27 17:48:05 -0700
    • Engine revision 77dd1c05b9
    • Dart version 2.10.0 (build 2.10.0-67.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nash/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/nash/Library/Android/sdk
    • Java binary at: /Users/nash/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/nash/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

• No issues found!
```
*Update*: I tested this with CanvasKit and the text renders fine. Only happens with HTML rendering.

**Comment by pedromassangocode** [comment]
I was able to reproduce this on latest `master` channel with Safari on MacOS.

![Screen Shot 2020-09-02 at 15 40 37](https://user-images.githubusercontent.com/67424416/91998084-b770eb80-ed32-11ea-8bd3-9045fa745ddd.png)


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.39, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-10.0.pre.39 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision a8281e31af (20 hours ago), 2020-09-01 10:57:59 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 2 categories.
```
</details>

**Comment by TahaTesser** [comment]
Missing text on Android as well https://github.com/flutter/flutter/issues/65339

**Comment by mdebbar** [comment]
For some reason, when there's a "-" in the text, the DOM element likes to take an extra pixel in width which causes the text to wrap. I've only seen this in Safari, but other issues say it's happening in Android PWAs too.

**Comment by yuhao-nyc** [comment]
Hey guys! Experience same issue on Android browsers, Chrome specifically. Any updates here?

**Comment by Nash0x7E2** [comment]
Hi @yuhao-nyc! Still running into this issue on the latest master, in the meantime, try building your application with the flag `--dart-define=FLUTTER_WEB_USE_SKIA=true`.

**Comment by yuhao-nyc** [comment]
Thanks for reply. Yea I did tried `--dart-define=FLUTTER_WEB_USE_SKIA=true` BUT its causing lot more other problems

**Comment by Nash0x7E2** [comment]
Strange, what branch and version are you on? I am using `1.22.0-2.0.pre.105`. For the most part, it is relatively stable and I haven't encountered any major issues.

**Comment by yuhao-nyc** [comment]
It caused some CORS issues after I use `--dart-define=FLUTTER_WEB_USE_SKIA=true`. for example I have NetworkImage. image src coming from network. they are not rendering cause CORS issue @Nash0x7E2

**Comment by juzimmer** [comment]
I can confirm using SKIA flag on builds causes major issues on dev, 1.23.0-4.0.pre . I can't even get the text fields to gain focus from the cursor. Then eventually the UI stops responding, No errors ever produce. It's really wonky. I would have to record a video to show what it does.

**Comment by kaumudpa** [comment]
I can also conform that using SKIA flag on builds causes issues with iOS safari - tested on iphone. The app restarts 
abruptly again and again every few minutes.

**Comment by marcusljx** [comment]
I'm also getting this on Android PWA. Here's my output of `flutter --version`:
```
Flutter 1.22.0-12.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8b3760638a (12 days ago) • 2020-09-15 17:47:13 -0700
Engine • revision 4654fc6cf6
Tools • Dart 2.10.0 (build 2.10.0-110.3.beta)
```

**Comment by pedromassangocode** [comment]
Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself, use the [Subscribe] button to the top right instead.

**Comment by xhit** [comment]
Experience same issue on Android Chrome PWA but is random and with different text, not only with text containing a "-"

**Comment by cacianokroth** [comment]
Any update?

**Comment by jahngergely** [comment]
Any update or roadmap when will this be fixed?

**Comment by Franco7Scala** [comment]
Any Update? This bug is still present in 1.25.0-8.1.pre!

**Comment by hmbenhaim** [comment]
Any news about this issue? I upgraded to latest version (1.25.0-8.3.pre on mac) and is still present.

**Comment by mdebbar** [comment]
@hmbenhaim which channel of flutter are you using? If you use `master` and upgrade to latest, you should get the fix. The fix was rolled into the flutter repo over the weekend.

**Comment by hmbenhaim** [comment]
> @hmbenhaim which channel of flutter are you using? If you use `master` and upgrade to latest, you should get the fix. The fix was rolled into the flutter repo over the weekend.

    I tested on the beta channel. Now I switched to the master channel (1.26.0-2.0.pre.403) and I tested it on 2 pwa on Android and it looks like it's fixed. Thank you! I was struggling with that for a few weeks now. Can't wait for it to be on beta channel.

**Comment by nikssj** [comment]
Still no fixes for beta? Which beta is working ?
