### ISSUE TITLE
Flutter Testing Error

### ISSUE THREAD

**Issue by EdwinPz** [flutter/flutter#65103]
I had this code working perfectly fine on my laptop running linux, I switched to my new windows pc and the code gives me error when I try to run it. Flutter doctor says everything is okay. I attached an image of the error. 
![error](https://user-images.githubusercontent.com/14207470/92010486-db730380-ed17-11ea-89f6-f1768008245a.png)

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
