### ISSUE TITLE
zsh: operation not permitted: flutter

### ISSUE THREAD

**Issue by orest-kostiuk** [flutter/flutter#65101]
1.charged the terminal to zsh and made new zprofile through touch

2.then i used vim .zprofile, .zshrc and added this variable- export PATH="$PATH:/Users/username/flutter/bin"
Now when i run flutter i get this error "zsh: operation not permitted: flutter"

**Comment by TahaTesser** [comment]
Hi @orest-kostiuk 
You need to provide full disk access to the terminal app
This is MacOS Catalina permissions, not related to Flutter itself 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by orest-kostiuk** [comment]
i provided full disk access to the terminal app

**Comment by TahaTesser** [comment]
Hi @orest-kostiuk 
That's not full disk access, the option above it is the full disk access. 

<img width="681" alt="Screenshot 2020-09-03 at 2 42 33 PM" src="https://user-images.githubusercontent.com/48603081/92095876-dc796300-edf3-11ea-80be-c06092b50c16.png">

Adding following in your `.zprofile` 

```
export ANDROID_HOME={your path}/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH

export PATH="$PATH:{your path}/flutter/bin"
```

**Comment by orest-kostiuk** [comment]
<img width="991" alt="Знімок екрана 2020-09-03 о 12 21 21" src="https://user-images.githubusercontent.com/26009298/92096814-032d9e80-ede0-11ea-8fe3-169fac1c5c73.png">

**Comment by TahaTesser** [comment]
hI @orest-kostiuk 
I tried, it works with full disk access, this is not related to Flutter. You won't be able to run other scripts, this is related to MacOS and it's permissions

Please checkout this https://discussions.apple.com/thread/251255604
Thnk you

**Comment by orest-kostiuk** [comment]
> hI @orest-kostiuk
> I tried, it works with full disk access, this is not related to Flutter. You won't be able to run other scripts, this is related to macOS and it's permissions
> 
> Here what I did
> git clone -b stable https://github.com/flutter/flutter.git
> then add your path and execute `fluter doctor -v`
> if you don't download setup zip, delete it and clone using git clone to the folder directly where you want flutter setup to be
> 
> Please check out this https://discussions.apple.com/thread/251255604
> 
> Thank you

Thanks, it work's)
