### ISSUE TITLE
Support a local engine flag in the tool integration tests

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#65106]
I recently had to debug a regression in the flutter_tools integration tests using a local build of the engine binaries.

I was able to do this by patching `_setupProcess` in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/test_driver.dart to add a `--local-engine` flag to the command line that it generated.

It would be useful to have a flag in the test runner that can select a local engine.

@jonahwilliams

**Comment by jonahwilliams** [comment]
This will be easier to do once https://github.com/flutter/flutter/pull/64980 lands
