### ISSUE TITLE
Running Gradle task 'assembleDebug'... (This is taking an unexpectedly long time.)

### ISSUE THREAD

**Issue by aliahmadslm** [flutter/flutter#65115]
All done!
[√] Flutter: is fully installed. (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.2)
[√] Android Studio: is fully installed. (version 4.0)
[√] VS Code: is fully installed. (version 1.48.2)
[√] Connected device: is fully installed. (1 available)

In order to run your application, type:

  $ cd hello
  $ flutter run

Your application code is in hello\lib\main.dart.

C:\Users\Ali\Desktop>cd hello

C:\Users\Ali\Desktop\hello>flutter run
Launching lib\main.dart on Google Nexus 10 in debug mode...
Running Gradle task 'assembleDebug'...
(This is taking an unexpectedly long time.)       \

**Comment by aliahmadslm** [comment]
Please Help Me ... I can't find a way solve it

**Comment by hamdikahloun** [comment]
Hi @aliahmadslm 
Can you provide please flutter run -v.

**Comment by aliahmadslm** [comment]
Thanks @hamdikahloun ...

C:\Users\Ali\Desktop\hello>flutter run -v
[ +136 ms] executing: [C:\myflutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 216dee60c0cc9449f0b29bcf922974d612263e24
[   +1 ms] executing: [C:\myflutter\flutter/] git tag --contains HEAD
[ +222 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.3
[  +10 ms] executing: [C:\myflutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\myflutter\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] executing: [C:\myflutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +56 ms] List of devices attached
           192.168.20.102:5555    device product:vbox86p model:Google_Nexus_10 device:vbox86p transport_id:2
[   +7 ms] C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell getprop
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +227 ms] Generating C:\Users\Ali\Desktop\hello\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +59 ms] ro.hardware = vbox86
[   +9 ms] ro.build.characteristics = tablet nosdcard
[  +88 ms] Starting incremental build...
[   +5 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[  +29 ms] complete
[   +7 ms] Launching lib\main.dart on Google Nexus 10 in debug mode...
[   +6 ms] C:\myflutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\myflutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\myflutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Ali\AppData\Local\Temp\flutter_tools.413b6552\flutter_tool.75c9ad5b\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +58 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell -x logcat -v time -t 1
[  +60 ms] Exit code 0 from: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           09-02 17:02:23.378 I/logcat  ( 1746): type=1400 audit(0.0:628): avc: denied { read } for path="/dev/pts/1" dev="devpts" ino=4 scontext=u:r:logd:s0 tcontext=u:object_r:devpts:s0 tclass=chr_file
           permissive=1
[  +12 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell -x logcat -v time -t 1
[  +78 ms] Exit code 0 from: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           09-02 17:02:23.378 I/logcat  ( 1746): type=1400 audit(0.0:628): avc: denied { read } for path="/dev/pts/1" dev="devpts" ino=4 scontext=u:r:logd:s0 tcontext=u:object_r:devpts:s0 tclass=chr_file
           permissive=1
[  +39 ms] <- compile package:hello/main.dart
[  +19 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +68 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +33 ms] Building APK
[  +32 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from C:\Users\Ali\Desktop\hello\android\gradlew.bat.
[   +2 ms] C:\Users\Ali\Desktop\hello\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +48 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +108 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +6 ms] executing: [C:\Users\Ali\Desktop\hello\android/] C:\Users\Ali\Desktop\hello\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\Ali\Desktop\hello\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+54712 ms] File C:\Users\Ali\.android\repositories.cfg could not be loaded.
[+2651 ms] Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\Ali\AppData\Local\Android\sdk\licenses
[   +6 ms] License for package Android SDK Build-Tools 28.0.3 accepted.
[        ] Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
[+28690 ms] "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
[   +1 ms] Installing Android SDK Build-Tools 28.0.3 in C:\Users\Ali\AppData\Local\Android\sdk\build-tools\28.0.3
[ +108 ms] "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
[ +188 ms] "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
[+9701 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +129 ms] executing: [C:\myflutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 216dee60c0cc9449f0b29bcf922974d612263e24
[        ] [        ] executing: [C:\myflutter\flutter/] git tag --contains HEAD
[        ] [ +271 ms] Exit code 0 from: git tag --contains HEAD
[        ] [        ] 1.20.3
[        ] [  +15 ms] executing: [C:\myflutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\myflutter\flutter/] git ls-remote --get-url origin
[        ] [  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[  +16 ms] [  +92 ms] executing: [C:\myflutter\flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] [  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[   +1 ms] [  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +11 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +13 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] [  +16 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +12 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [ +168 ms] Initializing file store
[   +6 ms] [  +45 ms] Skipping target: gen_localizations
[   +1 ms] [  +15 ms] kernel_snapshot: Starting due to {}
[  +94 ms] [  +46 ms] C:\myflutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\myflutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\myflutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform
--packages C:\Users\Ali\Desktop\hello\.packages --output-dill C:\Users\Ali\Desktop\hello\.dart_tool\flutter_build\e5d8382652a8f08f736f9486830c1524\app.dill --depfile
C:\Users\Ali\Desktop\hello\.dart_tool\flutter_build\e5d8382652a8f08f736f9486830c1524\kernel_snapshot.d package:hello/main.dart
[+8192 ms] [+8163 ms] kernel_snapshot: Complete
[ +699 ms] [ +746 ms] debug_android_application: Starting due to {}
[ +500 ms] [ +458 ms] debug_android_application: Complete
[ +699 ms] [ +703 ms] Persisting file store
[   +1 ms] [  +18 ms] Done persisting file store
[        ] [  +44 ms] build succeeded.
[  +97 ms] [  +37 ms] "flutter assemble" took 10,486ms.
[        ] [   +4 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +303 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +86 ms] > Task :app:generateDebugBuildConfig
[   +1 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +98 ms] > Task :app:mergeDebugShaders
[        ] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[        ] > Task :app:mergeDebugAssets
[ +298 ms] > Task :app:copyFlutterAssetsDebug
[   +4 ms] > Task :app:mainApkListPersistenceDebug
[   +5 ms] > Task :app:generateDebugResValues
[   +3 ms] > Task :app:generateDebugResources
[+2718 ms] > Task :app:createDebugCompatibleScreenManifests
[ +364 ms] > Task :app:processDebugManifest
[ +109 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +893 ms] > Task :app:checkDebugDuplicateClasses
[ +199 ms] > Task :app:mergeDebugResources
[ +701 ms] > Task :app:processDebugResources
[+7969 ms] > Task :app:compileDebugKotlin
[ +209 ms] > Task :app:javaPreCompileDebug
[+7354 ms] > Task :app:compileDebugJavaWithJavac
[ +108 ms] > Task :app:compileDebugSources
[+3208 ms] > Task :app:mergeDebugJavaResource
[+3636 ms] > Task :app:desugarDebugFileDependencies
[+1592 ms] > Task :app:transformClassesWithDexBuilderForDebug
[+2491 ms] > Task :app:validateSigningDebug
[  +11 ms] > Task :app:signingConfigWriterDebug
[ +348 ms] > Task :app:mergeDebugJniLibFolders
[+2841 ms] > Task :app:mergeExtDexDebug
[ +533 ms] > Task :app:mergeDebugNativeLibs
[ +233 ms] Unable to strip library 'C:\Users\Ali\Desktop\hello\build\app\intermediates\merged_native_libs\debug\out\lib\x86_64\libflutter.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
[ +367 ms] > Task :app:stripDebugDebugSymbols
[   +4 ms] Compatible side by side NDK version was not found.
[        ] Unable to strip library 'C:\Users\Ali\Desktop\hello\build\app\intermediates\merged_native_libs\debug\out\lib\x86\libflutter.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
[  +86 ms] > Task :app:mergeDexDebug
[+3498 ms] > Task :app:packageDebug
[ +335 ms] > Task :app:assembleDebug
[  +73 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[  +11 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[  +25 ms] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[  +16 ms] BUILD SUCCESSFUL in 2m 27s
[   +2 ms] 31 actionable tasks: 30 executed, 1 up-to-date
[ +414 ms] Running Gradle task 'assembleDebug'... (completed in 147.9s, longer than expected)
[  +91 ms] calculateSha: LocalDirectory: 'C:\Users\Ali\Desktop\hello\build\app\outputs\flutter-apk'/app.apk
[  +77 ms] calculateSha: reading file took 72us
[ +573 ms] calculateSha: computing sha took 568us
[  +12 ms] ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +6 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Ali\Desktop\hello\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +37 ms] Exit code 0 from: C:\Users\Ali\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree C:\Users\Ali\Desktop\hello\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hello" (Raw: "com.example.hello")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello" (Raw: "hello")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello.MainActivity" (Raw: "com.example.hello.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] Stopping app 'app.apk' on Google Nexus 10.
[   +1 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell am force-stop com.example.hello
[ +573 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell pm list packages com.example.hello
[ +552 ms] Installing APK.
[   +3 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +23 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +27 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +1 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 install -t -r C:\Users\Ali\Desktop\hello\build\app\outputs\flutter-apk\app.apk
[+6057 ms] Performing Streamed Install
                    Success
[   +8 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 6.1s)
[  +31 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell echo -n e8646db10cab138e21b1a29428c7e9d86387c45f > /data/local/tmp/sky.com.example.hello.sha1
[ +108 ms] Google Nexus 10 startApp
[  +11 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.hello/com.example.hello.MainActivity
[ +714 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hello/.MainActivity (has extras) }
[  +11 ms] Waiting for observatory port to be available...
[+1424 ms] Observatory URL on device: http://127.0.0.1:44155/ba_8MwwEsXA=/
[   +9 ms] executing: C:\Users\Ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.20.102:5555 forward tcp:0 tcp:44155
[  +32 ms] 53352
[   +2 ms] Forwarded host port 53352 to device port 44155 for Observatory
[  +13 ms] Caching compiled dill
[  +32 ms] Connecting to service protocol: http://127.0.0.1:53352/ba_8MwwEsXA=/
[+2096 ms] Successfully connected to service protocol: http://127.0.0.1:53352/ba_8MwwEsXA=/
[   +9 ms] Waiting for Google Nexus 10 to report its views...
[  +11 ms] Waiting for Google Nexus 10 to report its views... (completed in 9ms)
[  +15 ms] DevFS: Creating new filesystem on the device (null)
[  +51 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.hello/code_cache/helloFMHNGE/hello/)
[   +4 ms] Updating assets
[ +215 ms] Syncing files to device Google Nexus 10...
[  +15 ms] Scanning asset files
[  +22 ms] <- reset
[  +11 ms] Compiling dart to kernel with 0 updated files
[   +8 ms] <- recompile package:hello/main.dart b23a2ea3-2b16-4ac3-8504-e5875f168795
[   +6 ms] <- b23a2ea3-2b16-4ac3-8504-e5875f168795
[ +163 ms] Updating files
[ +305 ms] DevFS: Sync finished
[   +3 ms] Syncing files to device Google Nexus 10... (completed in 527ms)
[   +7 ms] Synced 0.9MB.
[   +3 ms] <- accept
[  +12 ms] Connected to _flutterView/0xe6452010.
[   +6 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +8 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +6 ms] d Detach (terminate "flutter run" but leave application running).
[  +11 ms] c Clear the screen
[   +4 ms] q Quit (terminate the application on the device).
[  +10 ms] An Observatory debugger and profiler on Google Nexus 10 is available at: http://127.0.0.1:53352/ba_8MwwEsXA=/

**Comment by aliahmadslm** [comment]
> flutter run -v

After running this "flutter run -v" this command ... now its working thanks for the help @hamdikahloun  ... what this command basically do .. and what was the problem ??

**Comment by hamdikahloun** [comment]
@aliahmadslm you are welcome
It's the Android SDK take 28 second to finish downloading maybe due to the internet speed.

> Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
> [+28690 ms] "Install Android SDK Build-Tools

**Comment by aliahmadslm** [comment]
Thanks again @hamdikahloun

**Comment by nomicool** [comment]
I have fixed that issue with installing latest jdk and jre and added both path to environment variables. it fixes my all flutter issues now flutter is working on its speed.
