### ISSUE TITLE
[build-dashboard] Color scheme should match LUCI's milo

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#65119]
With the migration of tasks to run on Luci, more of the team will be interacting with Luci. Currently, the build dashboard uses an independent color scheme and animations to surface task statuses.

![Existing Flutter Build Dashboard Example](https://user-images.githubusercontent.com/2148558/92033000-cbf7b880-ed1f-11ea-9e67-0498674efe89.png)

However, navigating to LUCI the colors sometimes mean something else. Some of the differences:

- Flutter vs LUCI
- Blue = grey
- Animation = yellow
- Yellow = orange

We should update either the Flutter Dashboard or LUCI to be consistent. One issue with updating the LUCI dashboard is that other LUCI projects will still show the default color schemes (eg Fuchsia). For that reason I think it makes sense to update the Flutter build dashboard.

**Comment by CaseyHillers** [comment]
I'll create a draft PR to show a demo of what this would look like.

**Comment by CaseyHillers** [comment]
Adding passed secondary triaged as we discussed it in the Flutter infra meeting this week.

**Comment by CaseyHillers** [comment]
![Flutter Build Dashboard with LUCI color scheme](https://user-images.githubusercontent.com/2148558/92037972-7f17e000-ed27-11ea-90da-40024d8edb2f.png)

I threw together a quick prototype. There's a few tests that will need to be updated as I simplified some of the overhead of dashboard specific task logic. I surfaced any rerun with an icon, and moved the colors over.

[Demo link](https://testchillers-dot-flutter-dashboard.appspot.com/#/build)

**Comment by CaseyHillers** [comment]
Infra team gave LGTM today.

@Hixie @cbracken @zanderso

Do you have any thoughts on this build dashboard update? Here's a [demo link](https://testchillers-dot-flutter-dashboard.appspot.com/#/build).

This is a part of the Devicelab to LUCI migration to reduce the context switching needed between the Flutter Build Dashboard and MILO dashboards. The reason for the change in the build dashboard instead of MILO is that partner teams will continue to use the default MILO color scheme (such as Dart and Fuchsia).

The changes are matching the color scheme to MILO, and replacing the orange/yellow retried tasks with an icon.

**Comment by zanderso** [comment]
Overall I think it looks good. At first glance, the arrows in a circle gave me the impression that those are tasks that are running instead of finished tasks that had to be retried. Maybe some sort of warning sign like an exclamation point would be better there? Does MILO have an idiom for passed-on-retry?

**Comment by CaseyHillers** [comment]
Good point about the icon, switched to an exclamation point.

AFAIK MILO does not have a default setting for handling retried builds, but we could implement something for Flutter's dashboards. This wouldn't carryover to the other projects though.

**Comment by cbracken** [comment]
Agree with @zanderso on the icon -- exclamation sgtm. Agreed with updating the dashboard rather than Luci. Overall lgtm!
