### ISSUE TITLE
adb is a device?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6513]
```
~/tmp/testpixel $ flutter run
More than one device connected; please specify a device with the '-d <deviceId>' flag.

Error retrieving device properties for ro.build.characteristics.
adb                       • adb           • android-arm
Android SDK built for x86 • emulator-5554 • android-x86 (emulator)
```

Not sure why adb is being reported as a device?

```
~/tmp/testpixel $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 80d578d93e (31 hours ago) • 2016-10-23 17:20:38
Engine • revision db12c5e621
Tools • Dart 1.21.0-dev.0.0
```

```
~/tmp/testpixel $ adb --version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
```

```
~/tmp/testpixel $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision 80d578d93e (32 hours ago), 2016-10-23 17:20:38
    • Engine revision db12c5e621
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/sethladd/homebrew/opt/android-sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.34

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[-] IntelliJ WebStorm (version 11.0.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 (emulator)
```

Notice that doctor tells me Android SDK 23. When talking to Android 7.1.1, I think we want doctor to tell me I need a newer version of the SDK?

FWIW, `adb` is found via homebrew. Not sure if that's what the flutter tools want? Should flutter tools drive adb from PATH or from some other blessed source?

**Comment by sethladd** [comment]
cc @danrubel @jason-simmons

**Comment by sethladd** [comment]
The fix was to remove the version of adb that came from homebrew. I then updated android sdk up to version 25 via Android Studio. Then I manually set my ANDROID_HOME to point to the android sdk installed by Android Studio. Now, I no longer see "adb" as a device.

Maybe flutter doctor should help identify the version mismatches in this case?

**Comment by danrubel** [comment]
* **Part 1** - In trying to recreate the this problem, I found that `flutter devices` was trying to parse `adb devices` error output as a list of devices, which produces strange results such as what you mention above.

* **Part 2** - @devoncarew @Hixie Should `flutter doctor` check for a minimum `adb` or Android SDK version? Do we have a constant somewhere indicating the minimum version expected?

**Comment by Hixie** [comment]
@jason-simmons most recently worked on the Android SDK version issue, I think.

**Comment by Hixie** [comment]
As for whether it _should_, sure. Check for as much as possible.

**Comment by sethladd** [comment]
re: Part 2: we support Android back to Jelly Bean. But we also need to figure out how to ensure that you have an Android SDK that matches the device you are developing for. So, we can check for a minimum version, but also a matching version.

re: Part 1, glad you repro'ed it :)

**Comment by eseidelGoogle** [comment]
I don't think there is much more to do here?  @danrubel fixed the adb parsing issue before.
