### ISSUE TITLE
Flutter requires installation and setup of cocoapods in order to deploy apps on iOS devices

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#65131]
Flutter requires installation and setup of cocoapods in order to deploy apps on iOS devices.

The setup of cocoapods is crashing on the new macOS hardware, see https://feedbackassistant.apple.com/feedback/8612629

Would be nice if fluter switched to a different package management solution.

Comment blurb from @chinmaygarde 

> CocoaPods is used to manage native dependencies on the hosts. It seems like one of the dependencies of CocoaPods has a native dependency that is crashing on this host. We need to track a fix for this with CocoaPods or switch to a different package management solution.

**Comment by jonahwilliams** [comment]
I don't think we use cocoapods to handle host dependencies anymore (@christopherfujino ). We do use it to handle plugins for iOS/macOS, and that is probably unchangeable at this point.

**Comment by xster** [comment]
We don't require the installation and setup of cocoapods to deploy apps to the iOS devices. We require cocoapods to build apps **with plugins** on iOS. If you just `flutter create` a blank app, you can build and run without cocoapods.

**Comment by a-siva** [comment]
I am following the instructions documented here [https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices](https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices) and trying out the flutter gallery app, not creating a new app.

Maybe the documentation needs an update to be more precise about when installation and setup of cocoapods is needed. Somebody who gets this new mac hardware and follows the steps listed there is going to get the same crash.

**Comment by xster** [comment]
ummm ya, that doc is... simple but not entirely technically correct. Thanks for pointing out.

**Comment by pcsosinski** [comment]
adding this to the 1.22 milestone as we'll need it in that release when it is done.

**Comment by alexmarkley** [comment]
FWIW, looks like upstream is tracking this in the following issues:
- https://github.com/CocoaPods/CocoaPods/issues/9907
- https://github.com/libffi/libffi/issues/571

Furthermore, in my situation I was able to (temporarily) work around the issue by running the `sudo gem install cocoapods` step under Rosetta. Not sure what downstream problems that might create, but it got me moving forward.

**Comment by xster** [comment]
Right. The real fix is in https://github.com/CocoaPods/CocoaPods/issues/9907, but if you're blocked @a-siva you can run cocapods in a terminal under rosetta. Or just ignore the instructions and not use a project with plugins for now.

**Comment by jmagman** [comment]
PR for doc change at https://github.com/flutter/website/pull/4662.
Added https://github.com/CocoaPods/CocoaPods/issues/9907 to https://github.com/flutter/flutter/issues/60118 so it doesn't get lost.
