### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/mopcris/Desktop/myFlutterApps/edrishti/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by devmgs** [flutter/flutter#65149]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. Just run : flutter build apk
2. Build Works for new projects but fails on older projects

## Logs
ProcessException: Operation not permitted Command: /Users/mopcris/Desktop/myFlutterApps/edrishti/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-IN)
    • Flutter version 1.20.2 at /Users/mopcris/fluttersdk
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mopcris/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • D441D988-48A1-4C09-A86B-8D333FD33DD0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.6+30
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 20e59316b8b8474554b38493b8ca888794b0234a
### Plugins
flutter_keyboard_visibility-0.7.0
google_maps_flutter-0.5.21+17
path_provider-1.6.0
sqflite-1.2.0
webview_flutter-0.3.18+1

**Comment by devmgs** [comment]
Was able to correct it by deleting android folder and recreating it. as suggested in https://github.com/flutter/flutter/issues/62754

**Comment by anaman9** [comment]
create a new project..
just replace gradlew file from new project to old project..

and just boom.
