### ISSUE TITLE
[shared_preferences] Replace Shared Preferences with Jetpack Datastore

### ISSUE THREAD

**Issue by BraveEvidence** [flutter/flutter#65145]
Motivation

Shared Preferences on Android is slow and is bound to be buggy as it fail without warning. Jetpack Datastore solves this issue

Description

https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079

**Comment by stuartmorgan** [comment]
We would not maintain a second, Android-only plugin that does the same thing as `shared_preferences` but with a different backend. Updating `shared_preferences`'s Android implementation to DataStore seems reasonable though.

@darshankawar It's not clear to me why you retitled this issue in a way that completely changed the request.

**Comment by darshankawar** [comment]
@stuartmorgan 
My interpretation was a proposal to add new plugin instead of `shared_preferences` and hence also added `would be a good package`.  Sorry for any confusion caused due to it.
