### ISSUE TITLE
OTP autofill block interaction or black screen

### ISSUE THREAD

**Issue by darkang3lz92** [flutter/flutter#65144]
## Steps to Reproduce

```dart
AutofillGroup(
   child: TextFormField(
      autofocus: true,
      autofillHints: [AutofillHints.oneTimeCode],
   ),
),
```
1. Add TextField/TextFormField with AutofillHints.oneTimeCode
1. Tap Autofill code from Messages (without sending any SMS)
2. Tap TextField or go to Android home page

**Expected results:** 
Tapping TextField will shows keyboard and allow typing. Coming back from Android Home show app screen.

**Actual results:** 
Tapping TextField never show keyboard. Coming back from Android Home show black screen. Required to click back button to make it work normally.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.14.6 18G95, locale en-MY)
    • Flutter version 1.20.3 at /Users/xxxx/Downloads/flutter
    • Framework revision 216dee60c0 (31 hours ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/xxxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Pixel 4 XL (mobile) • 9B051FFBA0054P • android-arm64 • Android 10 (API 29)
```

</details>

**Comment by LongCatIsLooong** [comment]
Failed to reproduce on 216dee60c0 using 
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Material(
        child: AutofillGroup(
          child: TextFormField(
            autofocus: true,
            autofillHints: [AutofillHints.oneTimeCode],
          ),
        ),
      ),
    );
  }
}

```

The steps I took:
1. Send myself a message containing the keywords
2. Launch the app
3. The text field gets auto focused 

or 
1. Launch the app first
2. Switch to "Messages", copy the OTP
3. Go back to the app and tap on the text field

I had no problem trying to interact with the text field.

**Comment by pedromassangocode** [comment]
Hi @darkang3lz92 
I was not able to reproduce that on latest `stable` channel using a Xiaomi Redmi 5 Plus.
Are you able to reproduce this with a different device?

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 216dee60c0 (2 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30)
      (emulator)

! Doctor found issues in 2 categories.
```
</details>

**Comment by darkang3lz92** [comment]
@LongCatIsLooong To reproduce this, you will need to do it without any OTP sms, for the scenario when waiting for incoming sms. Please refer below.

@pedromassangocode I don't have other device now, but i can show you how it's look like below. 

All the buttons are functioning except keyboard, when we navigate push to other page during this "overlay" state, it will continue stay there until we click back button to close it, which affecting TextField in other page not working as well. Calling `Navigator.of(context).pop();` doesn't close the "overlay" as well, only Android back button work.

<img src="https://user-images.githubusercontent.com/33158127/92189699-e5207680-ee91-11ea-9694-374cfba7c3e3.png" width="250">
(ignore the white blocks during tapping on black screen, it caused by image conversion)

**Comment by LongCatIsLooong** [comment]
Thank you! Reproduced this on simulator. Didn't realize my test project was using v1 embedding.

**Comment by LongCatIsLooong** [comment]
Is this reproducible on device (sorry don't have an Android R device around atm)? Tried OTP autofill in a native android app running on Android R simulator, it has this issue too:

![untitled](https://user-images.githubusercontent.com/31859944/93406308-2d517880-f844-11ea-9822-fd170426ad67.gif)

**Comment by LongCatIsLooong** [comment]
Looks like it's currently being worked on. b/159487695 (internal).

**Comment by darkang3lz92** [comment]
Autofill service started to show `Waiting for message` snackbar instead of transparent layer. Issue can be closed now.
