### ISSUE TITLE
zsh: operation not permitted: flutter

### ISSUE THREAD

**Issue by orest-kostiuk** [flutter/flutter#65159]
1.charged the terminal to zsh and made new zprofile through touch

2.then i used vim .zprofile, .zshrc and added this variable- export PATH="$PATH:/Users/username/flutter/bin"
Now when i run flutter i get this error "zsh: operation not permitted: flutter"

3. added full disk access for my terminal

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/65101
