### ISSUE TITLE
flutter not finding my Android SDK (Request to display ANDROID_HOME in flutter doctor)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6516]
```
~/tmp/testpixel $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision 80d578d93e (32 hours ago), 2016-10-23 17:20:38
    • Engine revision db12c5e621
    • Tools Dart version 1.21.0-dev.0.0

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.34

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[-] IntelliJ WebStorm (version 11.0.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • None
```

Yet I seem to have an SDK:

![screen shot 2016-10-25 at 10 36 06 am](https://cloud.githubusercontent.com/assets/5479/19678665/f84073c8-9a9e-11e6-8d1e-a2fd96c9e0e8.png)

**Comment by sethladd** [comment]
cc @danrubel

**Comment by sethladd** [comment]
workaround: manually set `ANDROID_HOME`. But reading the docs, I get the sense that I shouldn't have had to do that?

**Comment by danrubel** [comment]
If you remove `ANDROID_HOME` and run `flutter doctor` from the top level flutter repo directory, then does `flutter doctor` find your Android SDK install location? If you run it from another directory does it not work? That's what I'm seeing on my end after I ran `brew install android-sdk`... and `brew uninstall android-sdk` does not fix it.

But then I closed the shell and reopend it and... viola! `flutter doctor` finds now finds the Android SDK regardless of the current directory. Does this work for you?

**Comment by sethladd** [comment]
> If you remove ANDROID_HOME and run flutter doctor from the top level flutter repo directory, then does flutter doctor find your Android SDK install location?

No. And I'm not sure how/why it would? Does `doctor` look in a variety of common locations on a Mac?

> If you run it from another directory does it not work?

I ran `flutter doctor` from `$HOME`, and it does not find my Android SDK:

```
[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
```

> Does this work for you?

Sorry, no. If ANDROID_HOME is not set, `doctor` cannot find the Android SDK.

Where does `doctor` look for the SDK on a Mac?

**Comment by danrubel** [comment]
> > If you remove ANDROID_HOME and run flutter doctor from the top level flutter repo directory, then does flutter doctor find your Android SDK install location?
> 
> No. And I'm not sure how/why it would? Does doctor look in a variety of common locations on a Mac?

I saw this because I was using two different shells... because I installed/uninstalled several times on one, it would work in one and broke in the other. Closing and reopening the one caused `flutter doctor` to work again. I was hoping that was the issue for you, but no luck.

> Where does doctor look for the SDK?

It looks for the SDK in the following locations
* `$ANDROID_HOME`
* `$ANDROID_HOME/sdk`
* `$homeDirPath/Library/Android/sdk` <-- Mac only
* `$homeDirPath/Library/Android/sdk/sdk` <-- Mac only
* `$homeDirPath/Android/Sdk` <-- Linux only
* `$homeDirPath/Android/Sdk/sdk` <-- Linux only

Is your SDK in one of these locations? Or are there an additional locations I should check?

**Comment by sethladd** [comment]
Interesting! Let's debug this in person :)

**Comment by sethladd** [comment]
DOH! `ANDROID_HOME` was set. To homebrew. Which I removed. :/

perhaps we can display ANDROID_HOME in `flutter doctor` so that users like me will see that ANDROID_HOME is incorrect set.

Thanks!

**Comment by UnaOmnia** [comment]
This is super hard. I read SO many of these vague comments...

QUESTION:

WHAT SHOULD ANDROID_HOME BE SET TO?

I am GUESSING C:\Program Files\Android

SAME QUESTION FOR ANDROID SDK FILES:

I am GUESSING C:\Program Files\Android\android-sdk <-- PS that is just the zip you link to you your site extracted with \tools\ inside right?

I am so freaking confused. 3rd open source app software I got stuck on recognizing the SDK tools with little to no coverage on instructions.

**Comment by UnaOmnia** [comment]
WAIT! I get it.. You have to download the SDK put it somewhere and then have Android Studio find and install it. That could be a bit more clear in the instructions....

**Comment by meine31** [comment]
Please someone help me with this issue; i did a ANDROID_HOME; but the flutter still not working; what kind of SDK we choose the android one or the  one installed with flutter!!! A picture exemple would be great!!! Thx.

**Comment by ashishpatill** [comment]
if i know my android sdk path, how do i update android_home to that path?

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/flutter-does-not-find-android-sdk-2

**Comment by milanpatel18** [comment]
Already solved at https://github.com/flutter/flutter/issues/15114#issuecomment-541346856

**Comment by KLTR** [comment]
> if i know my android sdk path, how do i update android_home to that path?

depends on your MACOS. 
for zsh you need to create a new file named .zshrc and set the path. export $ANDROID_HOME=[PATH-TO-Android-SDK]
if you use then you need to edit your .bashrc
