### ISSUE TITLE
webview_flutter resizes on keyboard open and keyboard dismiss automatically

### ISSUE THREAD

**Issue by uc-apa** [flutter/flutter#65168]
I have struggling with flutter webview, we are trying to open labs in webview. In react native webview it was working with no issue. Same thing is not working in webview in flutter app. Keyboard open up, webview is resized, keyboard automatically closes, I am clicking back and again but no success. Please help me regarding this issue.

Version being used: webview_flutter 0.3.22+1
[demo video](https://www.screencast.com/t/FCHWgluf667)
and screenshot
![image](https://user-images.githubusercontent.com/25792136/92106904-9f689d00-ee02-11ea-88e5-0dfe64aa143e.png)

[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.17.5 at F:\flutterSDK\flutter
    • Framework revision 8af6b2f038 (9 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at c:\Users\Akshay\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = c:\Users\Akshay\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.47.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by TahaTesser** [comment]
Hi @uc-apa 
Can you upgrade to  latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` **with upgrade** and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
