### ISSUE TITLE
Debug tests: Warning: You should set `SILENT_OBSERVATORY`

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#65163]
I want to debug my tests.
Tried both in VS Code and AS.
Set some breakpoints, run debug from IDE:
![image](https://user-images.githubusercontent.com/12999702/92102878-ded5c000-ede7-11ea-9898-a1ae99ff2a5e.png)
Run from terminal (i tried to set a variable here, and it stills throws the same warning):
![image](https://user-images.githubusercontent.com/12999702/92102907-e72dfb00-ede7-11ea-91fd-7e3aa379766d.png)

flutter doctor -v output:
![image](https://user-images.githubusercontent.com/12999702/92101985-9669d280-ede6-11ea-854b-81c8ea439d0a.png)

**Comment by TahaTesser** [comment]
Hi @subzero911 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/63075
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
