### ISSUE TITLE
[Sentry] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)

### ISSUE THREAD

**Issue by sbigtree** [flutter/flutter#65166]
```
E/flutter (30777): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)
E/flutter (30777): :///api/4d6ccf3384a14719a5dc404e52954c33/store/
E/flutter (30777): ^
E/flutter (30777): 
E/flutter (30777): #0      _Uri._fail (dart:core/uri.dart:1628:5)
E/flutter (30777): #1      new _Uri.notSimple (dart:core/uri.dart:1461:9)
E/flutter (30777): #2      Uri.parse (dart:core/uri.dart:1022:17)
E/flutter (30777): #3      _fromUriOrString (package:http/src/base_client.dart:108:50)
E/flutter (30777): #4      BaseClient._sendUnstreamed (package:http/src/base_client.dart:75:35)
E/flutter (30777): #5      BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter (30777): #6      SentryClient.capture (package:sentry/src/base.dart:182:48)
E/flutter (30777): #7      SentryClient.captureException (package:sentry/src/base.dart:210:12)
E/flutter (30777): #8      main (package:crashy/main.dart:99:18)
E/flutter (30777): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (30777): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (30777): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30777): #12     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (30777): #13     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (30777): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (30777): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (30777): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (30777): 
```

**Comment by TahaTesser** [comment]
Hi @sbigtree 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`
Thank you

**Comment by carlp95** [comment]
Hi @TahaTesser 
I'm having the same problem.

### Here is my **flutter doctor -v**:
`[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.17.5 at D:\Programs\flutter
    • Framework revision 8af6b2f038 (9 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at D:\Programs\JetBrains\IntelliJ IDEA 2018.2.3
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.7761

[√] Connected device (2 available)
    • MAR LX3A            • A4N4C19508001061 • android-arm64 • Android 10 (API 29)
    • AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
`
My isn't publish

### Here my pubspec.yaml:

`dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_dotenv:
  http:
  shared_preferences:
  device_info:
  provider: ^3.0.0
  intl: ^0.16.1
  intl_translation: ^0.17.9
  flutter_datetime_picker: ^1.3.8
  esc_pos_utils: ^0.3.6
  flutter_bluetooth_basic: ^0.1.5
  esc_pos_bluetooth: ^0.2.8
  multiselect_formfield: ^0.1.3
  path_provider: ^1.6.11
  screenshot: ^0.2.0
  social_share: ^2.0.5
  flag: ^3.0.4
  sentry: ">=3.0.0 <4.0.0"`

**Comment by sbigtree** [comment]
Hi@TahaTesser 
**Here is my crashy** 
git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/tree/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tree/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Here my pubspec.yaml**
name: crashy
description: A Flutter app that knows how to crash in various ways.

dependencies:
  sentry: ">=3.0.0 <4.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  test: 1.11.1

flutter:
  uses-material-design: true

[Ther demo is crashy](https://github.com/flutter/crashy)

**My issue**
I don't understand why it reported an error in the URI
I built a release installation, but I didn't receive an error report behind the Sentry, and using the test example also prompted a URL error
the exanple code
```
import 'package:sentry/sentry.dart';

final sentry = SentryClient(dsn: "2c781e11ced1472cb2ed6a7e2c43fe1d");
FlutterError.onError = (details, {bool forceReport = false}) {
  sentry.captureException(
    exception: details.exception,
    stackTrace: details.stack,
  );
};
void main() async {
   try {
     throw null;
   } catch (error, stackTrace) {
      await sentry.captureException(
      exception: error,
      stackTrace: stackTrace,
  );
}
  runZonedGuarded(
    () => runApp(MyApp()),
    (error, stackTrace) {
      await sentry.captureException(
        exception: error,
        stackTrace: stackTrace,
      );
    },
  );
}

```

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:sentry/sentry.dart';

final sentry = SentryClient(dsn: "2c781e11ced1472cb2ed6a7e2c43fe1d");

// FlutterError.onError = (details, {bool forceReport = false}) {
//   sentry.captureException(
//     exception: details.exception,
//     stackTrace: details.stack,
//   );
// };
void main() async {
  try {
    throw null;
  } catch (error, stackTrace) {
    await sentry.captureException(
      exception: error,
      stackTrace: stackTrace,
    );
  }
  runZonedGuarded(
    () => runApp(MyApp()),
    (error, stackTrace) async {
      await sentry.captureException(
        exception: error,
        stackTrace: stackTrace,
      );
    },
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           28.1s
Connecting to VM Service at ws://127.0.0.1:49910/9rXDbGRPifQ=/ws
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)
:///api/2c781e11ced1472cb2ed6a7e2c43fe1d/store/
^
[38;5;244m#0      _Uri._fail  (dart:core/uri.dart:1628:5)[39;49m
[38;5;244m#1      new _Uri.notSimple  (dart:core/uri.dart:1461:9)[39;49m
[38;5;244m#2      Uri.parse  (dart:core/uri.dart:1022:17)[39;49m
[38;5;248m#3      _fromUriOrString[39;49m
[38;5;248m#4      BaseClient._sendUnstreamed[39;49m
[38;5;248m#5      BaseClient.post[39;49m
[38;5;248m#6      SentryClient.capture[39;49m
[38;5;248m#7      SentryClient.captureException[39;49m
[38;5;248m#8      main[39;49m
[38;5;244m#9      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:233:25)[39;49m
[38;5;244m#10     _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#11     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#12     _runZoned  (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#13     runZonedGuarded  (dart:async/zone.dart:1618:12)[39;49m
#<…>

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 216dee60c0 (3 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

 
[✓] Connected device (1 available)            
    • iPhone 11 (mobile) • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

</details>

**Comment by a1tem** [comment]
The same issue here, 
I have got this : [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)
:///api/ac72a8a0458f455381ecfb9adb6fcb29/store/
^

**Comment by cadorca** [comment]
The project documentation indicates to put a dsn that looks like only the hash but you should put the complete DSN URL, search for **Client Keys (DSN)** in the project config, and replace the value in your flutter app, now everything should work properly. The correct DSN should looks like:
https://ac72a8a0458f455381ecfb9adb6fcb29@o111111.ingest.sentry.io/222222

<img src="https://user-images.githubusercontent.com/352267/92336657-8d883380-f068-11ea-9b1d-243b6e4cb1d8.png" width="100" height="200">

**Comment by sbigtree** [comment]
@cadorca I want to ask back this a '@o111111.ingest.sentry.io/222222' is what mean

**Comment by cadorca** [comment]
It's the full URL that sentry will generate for your project , you can find it in the project configuration. The docs only show the first part and it's wrong you need to provide the complete DSN to work properly. This is an example of a valid DSN:
https://d728a1240d7e425aa184e5b2a5d93299@o427942.ingest.sentry.io/5419428

**Comment by sbigtree** [comment]
@cadorca Think you very much!

I have found it

![image](https://user-images.githubusercontent.com/48344438/92357469-79047380-f11a-11ea-9fb5-399891e4cc77.png)

**Comment by a1tem** [comment]
Confirm, this issue is fixed now by using the full path. Thanks @cadorca!

**Comment by carloshwa** [comment]
It would be nice to update the documentation and sample app with this information.

**Comment by bruno-garcia** [comment]
The onboarding wizard was rendering an invalid DSN (just the key instead of the URL).
This problem was fixed on the Sentry side.

Worth noting the SDK has moved over to the Sentry org. Feel free to file issues and feature requests here now:

https://github.com/getsentry/sentry-dart/
