### ISSUE TITLE
Chromedriver tests failing on LUCI

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#65179]
The framework web smoke tests are unable to find the Chromedriver binary

Example: https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_smoke_test/121

The Chromedriver installation setup was recently changed in the LUCI recipe:
https://flutter.googlesource.com/recipes/+/a3100c854aaefa0b84ff344b4b859193f0604496

**Comment by godofredoc** [comment]
Taking this, yesterday we landed dynamic requirements for builders and that builder is not passing the chrome_and_driver dependency.
