### ISSUE TITLE
shared_preferences package: not suitable for tests

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#65176]
Please take a look at my test.
```dart
void main() async {
  TestWidgetsFlutterBinding.ensureInitialized(); 

  final store = AuthStore();
  GetIt.I.registerSingleton<ApiDio>(FakeApi());

  var sharedPrefs = SharedPrefs();
  await sharedPrefs.init();
  GetIt.I.registerSingleton<SharedPrefs>(sharedPrefs);
  SharedPreferences.setMockInitialValues({'token': '12345678'});

  test('token is not null after login', () async {
    when(GetIt.I<ApiDio>().dio.post(any, data: anyNamed('data')))
        .thenAnswer((_) async => Response(statusCode: 200, data: {
              'uuid': '16c29bd2-4f37-4c5e-906c-c0c41ea09922',
              'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
              'role': 'user',
            }));

    var result = await store.login('test@mail.com', 'qwerty');

    expect(result, true);
    verify(GetIt.I<ApiDio>().dio.post(any, data: anyNamed('data'))).called(1);
    expect(store.isAuth, true);
  });
}
```

Where SharedPrefs is a simple wrapper for SharedPreferences. `store.login()` uses it internally.
```dart
import 'package:shared_preferences/shared_preferences.dart';

class SharedPrefs {  
  SharedPreferences _sharedPreferences;  

  Future<void> init() async {
    _sharedPreferences = await SharedPreferences.getInstance();
  }

  String loadToken() {
    return _sharedPreferences.getString('token');
  }
  ...
}
```
Expected results - test is passed.
Actual results: `store.login()` throws the following error:
```
Failed to load "D:\Flutter\bioniq\test\auth_test.dart": MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

✖ loading D:\Flutter\bioniq\test\auth_test.dart
Exited (1)
```

**Comment by subzero911** [comment]
> Can you please try adding flutter prefix as mentioned here
No, it's not related. I can even remove the whole "setMockInitialValues" string, and the error remains.

pubspec.yaml: https://pastebin.com/aKNwBGnZ
flutter doctor:
![image](https://user-images.githubusercontent.com/12999702/92534709-2f14ae00-f23e-11ea-8803-38a4440be1f8.png)

**Comment by TahaTesser** [comment]
Hi @subzero911 
I just tried to test a simple example and I realized you're calling `setMockInitialValues` after `ensureInitialized`, it should be called before.  Test runs with no issues on `shared_preferences: ^0.5.10`  


### test.dart
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  SharedPreferences.setMockInitialValues({'token': '12345678'});

  TestWidgetsFlutterBinding.ensureInitialized();
  SharedPreferences sharedPreferences = await SharedPreferences.getInstance();

  test('test sharedPrefs', () async {
    var prefs = await SharedPreferences.getInstance();

    expect(prefs.getString('token'),
        '12345678'); //  change '12345678' to 'abc test will faill
  });
}

```

<img width="292" alt="Screenshot 2020-09-09 at 12 46 19 PM" src="https://user-images.githubusercontent.com/48603081/92566893-87799900-f29a-11ea-8186-8cab1e726e60.png">


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 216dee60c0 (8 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by subzero911** [comment]
I found that I **must** call `SharedPreferences.setMockInitialValues({})`, even with empty map. If I do not call it, i have a MissingPluginException.
I can do it after `ensureInitialized`, but it should be before `SharedPreferences.getInstance()`. if I do it before, i have the same MissingPluginException.

**Comment by TahaTesser** [comment]
@subzero911 
`setMockInitialValues` is called before instance in tests [reference](https://github.com/flutter/flutter/issues/48458#issuecomment-578942091)
Please try this test https://github.com/flutter/flutter/issues/65176#issuecomment-689359629

**Comment by subzero911** [comment]
I confirm that this test is working.
But `TestWidgetsFlutterBinding.ensureInitialized();` should be the first line, as stated in the docs, isn't it?

**Comment by TahaTesser** [comment]
Hi @subzero911 
Yes, it is but `shared_preferences` case, it seems to be that we need to add it before `ensureInitialized`. We could make it clear why in the doc issue https://github.com/flutter/flutter/issues/42780

Please add it before, your tests should work fine 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank yo
