### ISSUE TITLE
Animated Scale as implicit animation will be great to have!

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#65183]
I will be happy to have a widget out the box which can animate its scale by calling setState method.

**Comment by HansMuller** [comment]
Presumably [ScaleTransition](https://api.flutter.dev/flutter/widgets/ScaleTransition-class.html) isn't what you want? Can you explain why that is?

**Comment by Renesanse** [comment]
> Presumably [ScaleTransition](https://api.flutter.dev/flutter/widgets/ScaleTransition-class.html) isn't what you want? Can you explain why that is?

Well, following my issue title I can write again, that will be great to have out the box "implicit" animation implementation of Scaling. That means I don't wanna take care of animation controllers, tweens and other things. For me as a framework user will be more easier to call setState with different values of Scale property. Thanks!

**Comment by flar** [comment]
You use the word "implicit", but then you talk about driving the animation directly by supplying values. If you have to supply the intermediate scales by calling a method, that is not an implicit design, that is an explicit design.

An example of an implicit animation would be something like the AnimatedScale widget which triggers an animation any time your widget changes size. You just establish the new size and the animation happens automatically without any further input.
