### ISSUE TITLE
flutter doctor is reporting on "IntelliJ WebStorm", but we don't support WebStorm

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6518]
It's hard for me to determine if `flutter doctor` is finding the right IntelliJ. Not sure if we're reporting version numbers in the same way the user can introspect.

```
[-] IntelliJ WebStorm (version 11.0.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html
```

But I see:

![screen shot 2016-10-25 at 10 42 26 am](https://cloud.githubusercontent.com/assets/5479/19678886/ed1ac696-9a9f-11e6-9ac0-8ffea3d1dd4f.png)

**Comment by sethladd** [comment]
cc @pq

**Comment by sethladd** [comment]
Oh, I see what's going on. I do have WebStorm installed. Two things:

* Don't report on WebStorm via flutter doctor.

* If you were going to report on it, don't call it "IntelliJ WebStorm " :) But, you can ignore this point, because see point above.

**Comment by pq** [comment]
OK, I see how that would be confusing!

> Don't report on WebStorm via flutter doctor.

👍 

@danrubel : any objections to trimming down the IDEA products you're scanning for?  Currently only `Ultimate` and `Community Edition (CE)` are supported.

**Comment by danrubel** [comment]
Sgtm. Fix in flight.
