### ISSUE TITLE
flutter drive CI tests fail targeting iOS 14, stuck on local network permission popup

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#65207]
On iOS 14, launching a debug/profile Flutter app will prompt the user to allow local network access when the observatory publishes:

<img src="https://user-images.githubusercontent.com/682784/92180686-7d6c1c00-edfc-11ea-8574-c866085b019b.png" width="500">

### Steps to Reproduce
```
$ cd dev/devicelab
$ dart bin/run.dart -t ios_platform_view_tests
```
```
...
[ios_platform_view_tests] [STDOUT] stdout: [   +3 ms] 00:00 +0: FlutterDriver Merge thread to create and remove platform views should not crash
[ios_platform_view_tests] [STDOUT] stderr: [+5053 ms] VMServiceFlutterDriver: waitFor message is taking a long time to complete...
```
and the test will time out.

If you hit OK in the dialog, the tests run and pass.

**Comment by jmagman** [comment]
I'm really not sure how to fix this in a driver CI setup where there's no person to tap the button on the device.  The app itself doesn't have access to that popup (or that would defeat the purpose of forcing the user to allow the app to do things).  Even the [integration_test](https://github.com/flutter/plugins/tree/master/packages/integration_test) package is an `XCTest`, so it also doesn't have access to SpringBoard popups.  That package would need to convert to XCUITests to pull a trick like:
https://github.com/flutter/cocoon/blob/13876a4f9e4ba48be5fbbbec8940b9528482f77d/agent/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift#L12
```swift
let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
```

**Comment by jmagman** [comment]
\cc @dnfield based on CODEOWNERS.
I would work on this myself but I'm about to be on vacation for a week, so I want to leave a breadcrumb in case iOS 14 gets released in the meantime.

**Comment by jmagman** [comment]
@dnfield sorry for the errant comment, I meant to make it in https://github.com/flutter/flutter/issues/65217#issuecomment-686843993.

**Comment by xster** [comment]
One guess/untested solution for xctest is we could potentially force the uri via --*-vmservice-port and --vmservice-port-file and some combination of (these things have been changing recently) to connect to. Some plumbing may be needed for the driver mechanism.

**Comment by jmagman** [comment]
I think that suggested port always gets passed in now.  You're saying the engine should detect it's being `drive`n and not publish the port?  And we rely on other discovery mechanisms?

**Comment by xster** [comment]
Somewhat, we don't need the bonjour mechanism if we know the observatory uri. There's no permissions needed to just open a listen port for the observatory. There's probably various plumbing needed but we could attempt to not add the plist entry for driven tests, have the tool write out the uri to a file (I didn't know we had the --vmservice-port-file flag but it seems like that's what it's for) and let the tool watch for that file when trying to connect during the drive than waiting for mdns.

**Comment by jmagman** [comment]
The tool already passes in a suggested port, and that's the first one that gets tried.  https://github.com/flutter/flutter/pull/49735

**Comment by xster** [comment]
Ah cool, it even does `--disable-service-auth-codes`. I'm not sure it works since I always see an auth path in the observatory URI in the console. If it does, maybe we just need another flag to disable the new xcode_backend.sh function in flutter run. If the design of https://github.com/flutter/flutter/pull/49735 is sound, maybe there's just a bug? 

the --vmservice-out-file doesn't seem to make sense unfortunately. It seems like it's just writing it after finding the vmservice https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L285.

**Comment by jmagman** [comment]
> the --vmservice-out-file doesn't seem to make sense unfortunately. It seems like it's just writing it after finding the vmservice https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L285.

Not for `flutter drive`, but it makes sense if you `flutter run` then `flutter attach` or something like that.

**Comment by xster** [comment]
Right. That one's not very useful it seems.

**Comment by xster** [comment]
Does #66092 mean that we might decrease the need for the additional plist line and the dialog for the standard production use case if we can pull it out via the debugger and connect to the debug-uri/observatory uri directly?

**Comment by jmagman** [comment]
@xster Yes, at least for `run`/`drive`, that's the hope!

**Comment by xster** [comment]
Does #66092 unblock us on this now?

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/67452 and https://github.com/flutter/engine/pull/21632 are merged.  `flutter drive` no longer prompts the permission dialog.
