### ISSUE TITLE
DevTools identified as Rasomware by Bitdefender

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#65200]
I selected to open DevTools from IntelliJ IDEA on Windows 10, and I got a warning from Bitdefender that it was behaving as Rasomware, as it was modifying my files, so Bitdefender blocked it and restored my files.

I know this is just a false positive and I am safe, I am opening this issue to communicate this so others know it can happen.

FYI those are the files:

![image](https://user-images.githubusercontent.com/8120472/92166297-c200b300-ee0e-11ea-95ab-3fa7ae341e0d.png)

![image](https://user-images.githubusercontent.com/8120472/92166317-cfb63880-ee0e-11ea-8997-8d6287b70556.png)

![image](https://user-images.githubusercontent.com/8120472/92166578-33d8fc80-ee0f-11ea-8915-263e8bf0b32b.png)

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/61997

**Comment by jmagman** [comment]
I'll mention this case in https://github.com/flutter/flutter/issues/61997, thanks for the report!
