### ISSUE TITLE
Hardware back button not working

### ISSUE THREAD

**Issue by z85510** [flutter/flutter#65204]
Hey
I just upgrade to 1.22.0-10.0.pre.65 on Channel master and after that, I have a problem with hardware back button in android.
It doesn't work properly and most of time it doesn't work.

```
Flutter version 1.22.0-10.0.pre.65
Framework revision 2032a448ed
Dart version 2.10.0
```

**Comment by darshankawar** [comment]
Hi @z85510,
There's similar [issue](https://github.com/flutter/flutter/issues/64864) that was fixed. Also see [this](https://github.com/flutter/flutter/issues/64864#issuecomment-684989634) comment and I'd suggest you to keep an eye on the framework engine rollout to master to see the fix. Once it lands, you may upgrade master and see if that's resolved.
Closing this as duplicate.
