### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by reidlai** [flutter/flutter#65215]
I tried to use comand line to build the initial versioon genearted by Flutter in Android.  But immediately got Error "Could not find or load main class org.gradle.wrapper.GradleWrapperMain" but iOS has no error.

Then I run the same command in VSCode Terminal and deploy to Android Emulator.  it works without problem.  I have no clue what is the different.  I believe this should be related to environment variables but still have no clue after spending hours and hours.

Flutter version: 1.20.3
Android Studio: 4.0.1

## Steps to Reproduce
1. Run `flutter create test`
2. Run `cd test`
3. Run `flutter run -d <ios emulator devices>`
4. It works
5. Run `flutter run -d emulator-5554`
6. Got error "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain"
7. Run `flutter build apk --split-per-abi`
8. Got error "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain"
9. Run `cd android`
10. Run `./gradlew tasks --all`
11. It works
12. Run `./gradlew app:build`
13. It works
14. Open VisualStudio Code
15. Click "Terminal->New Terminal"
16. Run `flutter run -d emulator-5554`
17.  It works

**Comment by YowFung** [comment]
Hi, @reidlai 

Can you provide please:

- `flutter doctor -v`
- `echo %path%` or `env`

**Comment by darshankawar** [comment]
Hi @reidlai,
Are you getting any other error along with the one you posted ? Can you provide `flutter run --verbose` ?
Can you try [this](https://github.com/flutter/flutter/issues/17280#issue-320202856) possible solution and see if it works for you ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
