### ISSUE TITLE
Scaffolds are not removed in Release Mode

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#65212]
I think that I might have spotted a mistake in release mode @Piinks @HansMuller of https://github.com/flutter/flutter/pull/64101:

The [`_unregister` line](https://github.com/Piinks/flutter/blob/72469cd8d0f3552fc3cde54332fdc3d52296dc43/packages/flutter/lib/src/material/scaffold.dart#L239) will not remove the state from the hash set in release mode:

```dart
  void _unregister(ScaffoldState scaffold) {
    assert(_scaffolds.remove(scaffold));
  }
```

**Comment by creativecreatorormaybenot** [comment]
My proposal to fix this (if this is indeed a bug), is in #65214.

**Comment by pedromassangocode** [comment]
Hi @creativecreatorormaybenot 
Please share your `flutter doctor -v`.

**Comment by creativecreatorormaybenot** [comment]
@pedromassango This is just a code error (afaic) that was introduced in the linked PR #64101 yesterday (merged into master).

**Comment by pedromassangocode** [comment]
Please share it just for the records.

**Comment by creativecreatorormaybenot** [comment]
@pedromassango 

Flutter version [`48f1a0a8d5531a08de638f087678770dd26b01ba`](https://github.com/flutter/flutter/commit/48f1a0a8d5531a08de638f087678770dd26b01ba).

**Comment by HansMuller** [comment]
@creativecreatorormaybenot - good catch! That is indeed a bug.
