### ISSUE TITLE
Bad interaction between semantics trees and device_pixel_ratio on Fuchsia

### ISSUE THREAD

**Issue by teisenbe** [flutter/flutter#65218]
This is a tracking bug for a Fuchsia-internal bug: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=55485

**Comment by kf6gpe** [comment]
cc @chunhtai --- @dnfield said you may be able to help with this. Thanks!

**Comment by chunhtai** [comment]
@kf6gpe and @Hixie I have marked as P0 as per @teisenbe suggestion. This seems to be a high risk issue that we should fix ASAP.

**Comment by dnfield** [comment]
Quick update here as well - Fuchsia applies a transform right below the root to account for DPI, and is the only embedder that does so. A11y bridge has to account for that.

**Comment by chunhtai** [comment]
Current status: just set up a running device, still working on the fix. I currently target fixing this issue by the end of this week
