### ISSUE TITLE
webview_flutter-0.3.22+1 - unsafe operations.

### ISSUE THREAD

**Issue by marcusaureliusbrutus** [flutter/flutter#65229]
Hi,

I searched around and was not able to find any info how to address the below caveat.

webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.

I was hoping to use this plugin in my app for the purpose of accessing personal/private sites but the above warning is a major concern.  Is there an alternative to the above plugin which is known to be more secure?

Please advise.

Thanks.

**Comment by darshankawar** [comment]
Hi @marcusaureliusbrutus,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Also specify on which platform you are seeing this log.
Thanks

**Comment by iipavlov** [comment]
I see same message for the same webview version.

This is the flutter doctor output:
```
[✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.4 at ~/dev/flutter
    • Framework revision fba99f6cf9 (3 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at ~/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at:
  ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at
      ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6626763
    • Flutter plugin version 47.1.2
```

And this is the webview usage in the code:
 ```
Expanded(
            child: WebView(
              initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy
                  .require_user_action_for_all_media_types,
              initialUrl: NEWS_FEED_URL,
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController controller) {
                webView = controller;
              },

              gestureRecognizers: [
                Factory(() => PlatformViewVerticalGestureRecognizer()),
              ].toSet(),
              onPageStarted: (url) {
                print('Page started');
                setState(() {
                  isLoading = true;
                });
              },
              onPageFinished: (url) {
                print('Page Finished');
                setState(() {
                  isLoading = false;
                });
              },
            ),
          ),
```

**Comment by darshankawar** [comment]
@iipavlov @marcusaureliusbrutus If you are still seeing this issue, I'd recommend to upgrade to latest Stable version and latest `webview_flutter` plugin version and try again to see if issue persists. The plugin has undergone lot of changes and is out of developer preview, so you might want to use the latest version and check again. 
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
