### ISSUE TITLE
When the screen size changes, the current page should be refreshed. In my opinion.

### ISSUE THREAD

**Issue by qcks** [flutter/flutter#65239]
When the screen size changes, the current page should be refreshed. For example, the drawing area of the screen changes with split screen mode enabled or with virtual keys enabled.

**Comment by pedromassangocode** [comment]
To create a widget that's rebuilt when it's size constraints change you can use LayoutBuilder: https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html

Or you can use MediaQuery (https://api.flutter.dev/flutter/widgets/MediaQuery-class.html) that provide the actual size of the screen containing your Flutter app.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by qcks** [comment]
I don't agree with.
You don't understand.

**Comment by pedromassangocode** [comment]
Hi @qcks 
Can you fill a new issue with a detailed information about the issue/proposal?

This is closed for a few days now and would be better to have a new issue with detailed and precise information about you proposal.
