### ISSUE TITLE
Sometimes iproxy will stay in memory, causing iOS debug to be blocked.

### ISSUE THREAD

**Issue by zxl777** [flutter/flutter#65236]
Sometimes iproxy will stay in memory, causing iOS debug to be blocked.

It is recommended to automatically delete the remaining iproxy process in the memory before downloading the debug.
Automatically kill iproxy, so that iOS debug does not need to re-plug the USB data line.
```
killall iproxy 
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build

```

![image](https://user-images.githubusercontent.com/816448/92212831-241bef80-eec5-11ea-9d39-aec3834afb6b.png)

**Comment by darshankawar** [comment]
Hi @zxl777,
Can you provide `flutter doctor -v`. There was a similar [fix](https://github.com/flutter/flutter/pull/42026) made and merged in master. You may check that for reference and see if it helps.
Thanks.

**Comment by zxl777** [comment]
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/sky/development/flutter
    • Framework revision 216dee60c0 (3 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sky/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • X-Sky (mobile) • 9c56a3b9bab16635643815edc811b4997a2f6d9a • ios • iOS 13.6.1
```

**Comment by darshankawar** [comment]
@zxl777, did you try to switch to latest master per the fix and see if it is resolved there ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
