### ISSUE TITLE
Switching to beta channel downloads beta channel every time

### ISSUE THREAD

**Issue by tonydavidx** [flutter/flutter#65230]
when i switch to beta channel from stable. the beta channel sdk downloads to my computer if i go back to stable channel and switch to beta channel cli downloads the beta channel again. is there any way to avoid downloading the beta channel every time i switch to beta.

**Comment by pedromassangocode** [comment]
Hi @tonydavidx 
I see there's an open issue addressing the case you described (here https://github.com/flutter/flutter/issues/44212).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
