### ISSUE TITLE
Flutter app not working on device when debug cable disconnected and debug stopped - can't launch "from the icon", doesn't happen on iOS Simulator.

### ISSUE THREAD

**Issue by czaku** [flutter/flutter#65240]
## Description

Hi all,

I have a very weird problem, I can debug the app both on simulator and on device (iPhone). When I stop debugging I can launch the flutter app "from the icon" on Simulator and use it, but on iPhone it crashes. It works on iPhone only when I am debugging from Android Studio.
I have tried both on my iMac (Catalina) and Macbook (Big Sur latest beta).

I am running Xcode 12 beta 6 and iOS 12 beta 6.

I am running on flutter master channel, as I needed this fix to go in: https://github.com/flutter/flutter/issues/64045 (now finally I can debug on the device ;) )

It is a very basic flutter app so I am confident it is not about the app itself. 

**flutter doctor -v :** 

[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.82 at /Users/czaku/Dev/sdks/flutter
    • Framework revision 9248fda410 (10 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/czaku/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8189n
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 1C3F3A78-0394-46B1-9A03-854434E76864 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: czaku iPad Pro is not connected. Xcode will continue when czaku iPad Pro is connected. (code -13)
    ! Error: czaku iPhone is busy: Processing cache files from device. Xcode will continue when czaku iPhone is
      finished. (code -10)

**Comment by sidrao2006** [comment]
Hi @czaku can you please provide the output of `flutter run -v` and also when you run tye app from the command line, type `d` to detach your app from debug mode.

**Comment by pedromassangocode** [comment]
I'm unable to reproduce this issue due to lack of device so this will need additional triage.

**Comment by czaku** [comment]
> Hi @czaku can you please provide the output of `flutter run -v` and also when you run tye app from the command line, type `d` to detach your app from debug mode.

I have attached the end of flutter run -v - very interesting. it looks like it is stuck on `[  +44 ms] Updating files` and then nothing is happening, so I eventually killed the app and got that `[        ] Syncing files to device czaku iPhone... (completed in 237,042ms, longer than expected)` amongst other errors. please check below. Typing `d` to detach debugger didn't work but wasn;t sure how I was supposed to do that. 

`[ +179 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +10 ms] [ 60%] TakingInstallLock
[  +21 ms] [ 65%] PreflightingApplication
[  +29 ms] [ 65%] InstallingEmbeddedProfile
[   +4 ms] [ 70%] VerifyingApplication
[ +132 ms] [ 75%] CreatingContainer
[   +6 ms] [ 80%] InstallingApplication
[   +8 ms] [ 85%] PostflightingApplication
[  +19 ms] [ 90%] SandboxingApplication
[  +11 ms] [ 95%] GeneratingApplicationMap
[  +67 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +205 ms] ------ Debug phase ------
[        ] Starting debug of 00008030-001518512E30802E (D431AP, iPhone 11 Pro Max, iphoneos, arm64e) a.k.a. 'czaku iPhone' connected through USB...
[  +98 ms] [  0%] Looking up developer disk image
[  +12 ms] [ 95%] Developer disk image mounted successfully
[+1284 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +185 ms] (lldb) command source -s 0 '/tmp/BA9B2481-DC59-49DB-AB0C-BE12C1548F11/fruitstrap-lldb-prep-cmds-00008030_001518512E30802E'
[        ] Executing commands in '/tmp/BA9B2481-DC59-49DB-AB0C-BE12C1548F11/fruitstrap-lldb-prep-cmds-00008030_001518512E30802E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/czaku/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A5369b) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/czaku/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A5369b) arm64e/Symbols"
[        ] (lldb)     target create "/Users/czaku/Dev/virld/flutter-module/flutter_module/build/ios/iphoneos/Runner.app"
[+2785 ms] Current executable set to '/Users/czaku/Dev/virld/flutter-module/flutter_module/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/AC1520B4-41F0-4044-BC44-F28D95BB74EA/Runner.app"
[ +287 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:57952"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/czaku/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A5369b) arm64e/Symbols/usr" /System "/Users/czaku/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A5369b) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/AC1520B4-41F0-4044-BC44-F28D95BB74EA" "/Users/czaku/Dev/virld/flutter-module/flutter_module/build/ios/iphoneos" "/var/containers/Bundle/Application/AC1520B4-41F0-4044-BC44-F28D95BB74EA" "/Users/czaku/Dev/virld/flutter-module/flutter_module/build/ios/iphoneos" /Developer "/Users/czaku/Library/Developer/Xcode/iOS DeviceSupport/14.0 (18A5369b) arm64e/Symbols/Developer"
[  +15 ms] (lldb)     command script import "/tmp/BA9B2481-DC59-49DB-AB0C-BE12C1548F11/fruitstrap_00008030_001518512E30802E.py"
[   +3 ms] (lldb)     command script add -f fruitstrap_00008030_001518512E30802E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_001518512E30802E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_001518512E30802E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_001518512E30802E.safequit_command safequit
[        ] (lldb)     connect
[  +44 ms] (lldb)     run
[ +248 ms] success
[        ] (lldb)     safequit
[ +169 ms] Application launched on the device. Waiting for observatory port.
[   +9 ms] Attempting to forward device port 56011 to host port 57968
[        ] executing: /Users/czaku/Dev/sdks/flutter/bin/cache/artifacts/usbmuxd/iproxy 57968:56011 --udid 00008030-001518512E30802E
[+1005 ms] Forwarded port ForwardedPort HOST:57968 to DEVICE:56011
[ +104 ms] Installing and launching... (completed in 12.9s)
[        ] Caching compiled dill
[  +38 ms] Connecting to service protocol: http://localhost:57968
[        ] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[  +27 ms] Successfully connected to service protocol: http://localhost:57968
[   +1 ms] Waiting for czaku iPhone to report its views...
[   +3 ms] Waiting for czaku iPhone to report its views... (completed in 2ms)
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[  +15 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/B6C4528D-5280-4053-B494-529CFFF950E2/tmp/flutter_modulelcGymA/flutter_module/)
[   +1 ms] Updating assets
[  +74 ms] Syncing files to device czaku iPhone...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:app/main.dart 1bb6cd26-0de2-4197-bb7d-d2dce227a66c
[        ] <- 1bb6cd26-0de2-4197-bb7d-d2dce227a66c
[  +44 ms] Updating files
[+231906 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: HttpException: , uri = http://localhost:57968
[        ] trying again in a few - 9 more attempts left
[ +512 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58459
[        ] trying again in a few - 8 more attempts left
[ +510 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58462
[        ] trying again in a few - 7 more attempts left
[ +508 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58463
[        ] trying again in a few - 6 more attempts left
[ +505 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58465
[        ] trying again in a few - 5 more attempts left
[ +509 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58466
[        ] trying again in a few - 4 more attempts left
[ +508 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58468
[        ] trying again in a few - 3 more attempts left
[ +505 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58469
[        ] trying again in a few - 2 more attempts left
[ +508 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58471
[        ] trying again in a few - 1 more attempts left
[ +505 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58474
[        ] trying again in a few - 0 more attempts left
[ +506 ms] Error writing "build/flutter_assets/NOTICES" to DevFS: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58476
[        ] DevFS sync failed. Lost connection to device: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = localhost, port = 58476
[        ] Syncing files to device czaku iPhone... (completed in 237,042ms, longer than expected)
[   +1 ms] "flutter run" took 276,236ms.
[  +58 ms] ensureAnalyticsSent: 56ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 3`

**Comment by czaku** [comment]
Attaching log of running template flutter hello world project (with button incrementing count) - same thing happening. After running for a bit I am disconnecting cable, the app stays on foreground but when kill it from multitasking I am unable to relaunch it. Doesn't happen on the simulator. 
[run.txt](https://github.com/flutter/flutter/files/5190010/run.txt)

**Comment by czaku** [comment]
I just realised it is a known issue... https://flutter.dev/docs/development/ios-14

**Comment by czaku** [comment]
Closing as it is already reported here: https://github.com/flutter/flutter/issues/62531
