### ISSUE TITLE
different FlutterActivity use same flutter engine not work 

### ISSUE THREAD

**Issue by HXiaoMing** [flutter/flutter#65245]
I add a Flutter Activity with my native android app.  
in order to use less memory ，i make different FlutterActivity use same flutter engine .
i open four Activity one by one (ActivityA -> FlutterActivityA -> ActivityB -> FlutterActivityB).
(ActivityA and ActivityB is android native Activity，FlutterActivityA And FlutterActivityB is FlutterActivity.)
now the top Activity is FlutterActivityB，then i finish FlutterActivityB and ActivityB quickly.
after finish FlutterActivityB and ActivityB, the top Activity is FlutterActivityA.

if the FlutterActivityB onDestroy after the FlutterActivityA onResume，the FlutterActivityA can not renderer 
and can not interact with user. FlutterActivityA can not update and  renderer flutter ui any more.

i think is a CacheEngine bug(different FlutterActivity use same flutter engine), FlutterActivityB onDestroy after the FlutterActivityA onResume effect FlutterRenderer stopRenderingToSurface, thus, FlutterActivityA cannot Renderer again.

**Comment by hamdikahloun** [comment]
Hi @HXiaoMing 

Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?

did you use this method :

```
startActivity(
      FlutterActivity
        .withNewEngine()
        .build(currentActivity)
      );
```

**Comment by pedromassangocode** [comment]
Hi @HXiaoMing 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample? You can create a sample project that reproduces the issue and upload it on GitHub and then share the link here.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
