### ISSUE TITLE
[Semantics] When using a ListView nested inside a horizontal scroll view, I cannot select semantic nodes which are initially beyond the width of the screen

### ISSUE THREAD

**Issue by omar-f** [flutter/flutter#65253]
I have made a table which uses a ListView for my rows, nested inside a horizontal scroll view to allow scrolling between the columns.

My issue is that the cells which are initially beyond the width of the screen, cannot be selected with TalkBack or VoiceOver. i.e. if columns 0 to 3 are initially visible, VoiceOver/TalkBack does not select anything after column 3. The vertical direction is fine - I can select all the rows vertically, even those which I have to scroll to reach.

The issue only occurs when I place my row inside a list view. If I place a row directly inside the horizontal scroll view, I can select all columns. I've included a row (index -1) in the example code to show this. However, in production I need to use the ListView for performance.

The issue occurs on both iOS and Android. I tested on iOS 13.6 and Android 10.

Note that if I set `explicitChildNodes` to false on my row, the entire row contents are spoken - including all those which are beyond the screen. But it's still not possible to select the row from outside the initial width of the screen.

## Steps to Reproduce
1. Run `flutter create bug`.
2. Replace `main.dart` with this:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Material(
        child: SafeArea(
          child: ListWidget2D()
        )
      ),
    );
  }
}

class ListWidget2D extends StatelessWidget {

  final _colWidth = 120.0;
  final _cols = 20;
  final _rows = 50;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SizedBox(
        width: _rows * _colWidth,
        child: Column(
          children: [
            _buildRow(-1),
            Expanded(
              child: ListView.builder(
                  itemCount: _rows,
                  itemBuilder: (context, index) {
                    return _buildRow(index);
                  }
              )
            )
          ]
        ),
      ),
    );
  }

  Widget _buildRow(int rowIndex) {
    return Semantics(
      explicitChildNodes: true,
      child: Row(
          children: List.generate(_cols, (colIndex) {
            return SizedBox(
                width: _colWidth,
                height: 50,
                child: Text('Cell $rowIndex,$colIndex')
            );
          }).toList()
      )
    );
  }
}

```
2. Activate VoiceOver on iOS or TalkBack on Android
3. Move your finger over the visible cells, and observe the contents are spoken
4. Scroll the table to the right, revealing cells which were not already visible 
5. Move your finger over the new cells

**Expected results:** 
The contents of the new cells are spoken.

**Actual results:**
The contents are not spoken. The system sound effect indicates that there are no semantic elements there.

<details>
  <summary>Logs</summary>
No log output of `flutter run--verbose` after the app launched. If log output of the build would be useful, I can add that in.

`flutter analyze`
```
Analyzing bug...                                                        
No issues found! (ran in 2.4s)
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/omarf/Developer/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/omarf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Users/omarf/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

</details>

<details>
  <summary>Screenshots</summary>
In case my explanation didn't make sense, I've attached a few screenshots which hopefully explain the issue.

![1](https://user-images.githubusercontent.com/22119074/92263666-e7f08b00-eed4-11ea-9f14-4e55f01d0e06.png)

The above screenshot is the view before any scrolling. Column 3 is the last visible. Cell -1,3 is currently selected with TalkBack.

![2](https://user-images.githubusercontent.com/22119074/92263673-ec1ca880-eed4-11ea-88be-721308358cea.png)

After scrolling a bit, the cells in column 4 & above cannot be selected. Only the row -1 can be selected in TalkBack, since this is not inside the ListView.

I've repeated these two screenshots with `showSemanticsDebugger` set to true.

![3](https://user-images.githubusercontent.com/22119074/92263698-f343b680-eed4-11ea-999d-fc44ba92af22.png)
![4](https://user-images.githubusercontent.com/22119074/92263701-f50d7a00-eed4-11ea-889b-76a9019aa840.png)

</details>

**Comment by markusaksli-nc** [comment]
This does reproduce on stable but not on latest master `1.22.0-10.0.pre.87` and latest beta `1.21.0-9.2.pre`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\Development\flutter_beta
    • Framework revision 81a45ec2e5 (10 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```
</details>

Closing this as probably fixed.
