### ISSUE TITLE
Not Working in release mode 

### ISSUE THREAD

**Issue by lohitbura** [flutter/flutter#65259]
It's working fine with debug mode but. Not working in release mode . Storage not opened as expected . 
targetSdk : 30
Using latest version of flutter and image picker

**Comment by officer47p** [comment]
Maybe it's a problem with storage permission with lower sdks?
[Here's](https://pub.dev/packages/image_picker?target=#api--29) the instruction to add the permission needed.

Hit me up if it worked for you.

**Comment by lohitbura** [comment]
@officer47p I already tried that flag and set it to true . But it's not working after converting  to apk using flutter build apk

**Comment by lohitbura** [comment]
I believe you are referring this
android:requestLegacyExternalStorage="true

But I already tried it still not working when converting it into apk

**Comment by lohitbura** [comment]
Is there any other permission I needed to add in menifest

**Comment by hamdikahloun** [comment]
@lohitbura your android version please

**Comment by lohitbura** [comment]
@hamdikahloun 
It's 8.1 (Oreo)

**Comment by lohitbura** [comment]
I am targeting targetSdk :29 now but still getting error

**Comment by lohitbura** [comment]
I just created a new project and copy paste all the code but It worked. I don't know how . But I am closing this issue for now
