### ISSUE TITLE
Error (9009): Unable to 'pub upgrade' flutter tool. Retrying in five seconds..

### ISSUE THREAD

**Issue by leesh1202** [flutter/flutter#65286]
Continuously  getting this error .I have tried stable version as well as cloning.
When running flutter doctor 
Error (9009): Unable to 'pub upgrade' flutter tool. Retrying in five seconds..

**Comment by leesh1202** [comment]
flutter batch file isn't opening
flutter upgrade not working
cache deleted & again tried not working

**Comment by markusaksli-nc** [comment]
Hi @leesh1202 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/39130.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
