### ISSUE TITLE
requires SDK version >=2.10.0 <3.0.0, version solving failed

### ISSUE THREAD

**Issue by Ahemad7429** [flutter/flutter#65297]
I tried to switch branch from dev to master and master to dev. Also tried flutter upgrade, still I have been facing this for 2 days.

`pub get failed (1; Because demo_app requires SDK version >=2.10.0 <3.0.0, version solving failed.)
exit code 1`

**Details:
Flutter 1.22.0-10.0.pre.87 • channel master • https://github.com/flutter/flutter.git
Framework • revision 4732a214a7 (29 hours ago) • 2020-09-04 21:05:02 -0400
Engine • revision ac8b9c4c52
Tools • Dart 2.10.0 (build 2.10.0-86.0.dev)**

Any suggestions would be quite helpful.

Thank you.

**Comment by iapicca** [comment]
@Ahemad7429 
you seems to have switched to master succesfully
can you post your `flutter pub get -v`

**Comment by Ahemad7429** [comment]
[ +117 ms] executing: [/Users/AhemadAbbas/flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4732a214a7362a3781989977429f14202143b4f5
[        ] executing: [/Users/AhemadAbbas/flutter/] git tag --points-at HEAD
[  +18 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [/Users/AhemadAbbas/flutter/] git describe --match *.*.*
--first-parent --long --tags
[  +36 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-9.0.pre-87-g4732a214a
[  +10 ms] executing: [/Users/AhemadAbbas/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/AhemadAbbas/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/Users/AhemadAbbas/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.6
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19G2021
[  +44 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +121 ms] Running "flutter pub get" in flutter_ddd_architecture_firebase...
[   +5 ms] Using /Users/AhemadAbbas/flutter/.pub-cache for the pub cache.
[   +1 ms] executing:
[/Users/AhemadAbbas/Documents/FlutterDevelopement/flutter_ddd_architecture_firebase/]
/Users/AhemadAbbas/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +69 ms] FINE: Pub 2.10.0-86.0.dev
[  +57 ms] MSG : Resolving dependencies...
[  +60 ms] SLVR: fact: flutter_ddd_architecture_firebase is 1.0.0+1
[        ] SLVR: derived: flutter_ddd_architecture_firebase
[  +18 ms] SLVR: fact: flutter_ddd_architecture_firebase requires SDK version >=2.10.0
<3.0.0
[   +6 ms] SLVR: conflict: flutter_ddd_architecture_firebase requires SDK version >=2.10.0
<3.0.0
[   +5 ms] SLVR: Version solving took 0:00:00.041663 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (0.094s).
[  +10 ms] ERR : The current Dart SDK version is 2.10.0-86.0.dev.
[        ]     | 
[        ]     | Because flutter_ddd_architecture_firebase requires SDK version >=2.10.0
<3.0.0, version solving failed.
[        ] FINE: Exception type: SolveFailure
[  +20 ms] FINE: package:pub/src/solver/version_solver.dart 312:5
VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 133:27
VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 97:11
VersionSolver.solve.<fn>
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                         Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace                                Chain.capture
[        ]     | package:pub/src/utils.dart 126:11                  captureErrors
[        ]     | package:pub/src/command_runner.dart 182:13
PubCommandRunner.runCommand
[  +24 ms] Running "flutter pub get" in flutter_ddd_architecture_firebase... (completed in
0.3s)
[   +2 ms] "flutter get" took 450ms.
[   +4 ms] pub get failed (1;     | package:pub/src/command_runner.dart 182:13
           PubCommandRunner.runCommand)
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:335:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream
(package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._addListener.<anonymous closure>
(dart:async/future_impl.dart:393:9)
           #17     _rootRun (dart:async/zone.dart:1190:13)
           #18     _CustomZone.run (dart:async/zone.dart:1093:19)
           #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #20     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
           #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #23     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
           #24     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +264 ms] ensureAnalyticsSent: 256ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by pedromassangocode** [comment]
Hi @Ahemad7429 
Please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please comment and I will reopen it.
Thank you
