### ISSUE TITLE
Get current application memory usage / cpu usage

### ISSUE THREAD

**Issue by AtomicNicos** [flutter/flutter#65290]
## Use case

Multiple : 
- Delaying asynchronous memory intensive tasks
- Display the data in a scientific app
- Generally avoid OOM errors

## Proposal

Enable users to call some class, possibly `Runtime` (like in Android Java) or `ActivityManager.MemoryInfo` (in Android Kotlin) and retrieve the current memory usage of the application,  and the current CPU usage of the application.

## Disclaimer

If this feature exists, it is obfuscated by Googling that returns a lot of results for the VM inspector tools.

**Comment by pablo-threadable** [comment]
Any news on this?

**Comment by JigneshPatel23** [comment]
Any way to access these data on app's runtime?

**Comment by stuartmorgan** [comment]
This seems like a relatively niche feature, and writing such a plugin should be straightforward on any platform that provides APIs to get that information, so this seems like a very good candidate for a third-party plugin. It's not something we would build a first-party plugin for.

> * Generally avoid OOM errors

Mobile systems tend to manage memory quite actively, so making decisions based on the memory that happens to currently be free isn't generally a good way to avoid OOM errors; you have no way of knowing what resources the system may be able to easily free on demand.
