### ISSUE TITLE
Support for all unicode characters 

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#65296]
Since flutter doesn't depend on native resources (for UI elements), flutter can easily support all the unicode characters including emojis so that usage of emojis even those which are not available on user's device are visible.

**Comment by iapicca** [comment]
@sidrao2006 flutter supports emoji already
and without this being an endorsement it seems already possible to "import" non-native emoji 
as for this [package](https://pub.dev/packages/flutter_emoji)

**Comment by sidrao2006** [comment]
@iapicca thanks for the reply. If flutter supports all the emojis according to unicode's list of emojis(v13), then I'd be happy to close this issue

**Comment by berrylawchingman** [comment]
Pls ASAP do it

**Comment by iapicca** [comment]
@sidrao2006 you may want to look at this [approach](https://stackoverflow.com/questions/44936239/displaying-text-with-emojis-on-flutter) as well

**Comment by sidrao2006** [comment]
Thanks

**Comment by sidrao2006** [comment]
@iapicca , does flutter itself render emojis from its own font or does it depend on the system font and let the system render the emoji.
Mypoint is if I request an emoji that is not present in the system font, then can flutter render it or not?
