### ISSUE TITLE
imagefiltered_transform_animation_perf__timeline_summary failing with insufficient storage error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#65291]
```
stdout:             adb: failed to install /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/com.example.macrobenchmarks-1: Creating application package com.example.macrobenchmarks failed]
```

Marking P0 because the tree is closed on this, but it can wait until 9/8 after the long weekend!

**Comment by flar** [comment]
Mac-19 is failing from this now and completely blocking the build tree ATM. Is there a P-1?

**Comment by digiter** [comment]
Executed `adb reboot` on mac-19.

**Comment by digiter** [comment]
Tree is open now.

**Comment by flar** [comment]
Mac-19 is already up to its insufficient storage errors again. I think more than just a reboot of the phone is needed.

**Comment by digiter** [comment]
Stopped the mac-19 agent, will investigate further (https://github.com/flutter/flutter/issues/39925). Rerun the failed tests and they passed.
