### ISSUE TITLE
Flutter Doctor "Android SDK does not have the proper build-tools." is misleading

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6529]
The following output is misleading as the build-tools in my android sdk were up to date - I just hadn't installed the SDK platform part of the sdk.

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at <redacted>
    • Framework revision 2ac7d67e6a (85 minutes ago), 2016-10-25 10:40:54
    • Engine revision a8604ba9d2
    • Tools Dart version 1.21.0-dev.0.0

[-] Android toolchain - develop for Android devices
    • Android SDK at <redacted>
    x Android SDK does not have the proper build-tools.
    • Try re-installing or updating your Android SDK.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

Device <redacted> is not authorized.
You might need to check your device for an authorization dialog.
[✓] Connected devices
    • None
```

**Comment by mit-mit** [comment]
I suggest we change it to `Android SDK is missing command line tools; download from https://goo.gl/XxQghQ)`.

**Comment by mit-mit** [comment]
CC @danrubel

**Comment by stevenroose** [comment]
What exactly is missing when you get this message? I get it, I'm on Arch and I installed both [`android-tools`](https://www.archlinux.org/packages/community/x86_64/android-tools/) and [`android-platform`](https://aur.archlinux.org/packages/android-platform/).
