### ISSUE TITLE
ImageFit ignored on tablet, image always fills with distorted ratio

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#653]
I have a simple view that just returns an image, on my Nexus 9 tablet with Android 6.0 the image always fills the view with distorted ratio (in both landscape or portrait). On Nexus 5X with 6.0 and Nexus 5 with 6.0, image displays fine and I get proper ratio and black-space around the image when needed.

**Comment by abarth** [comment]
Can you post an example to this bug so that we can reproduce this issue?  It's odd that you'd get different behavior on table rather than phone.

**Comment by aghassemi** [comment]
Will do, let me update to latest Flutter and Mojo to ensure it is still an issue and then I will update the bug with more details.

**Comment by aghassemi** [comment]
No longer an issue with latest flutter and android mojo shell.
