### ISSUE TITLE
Automatically pull android tombstone files

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6530]
In https://github.com/flutter/flutter/issues/6503#issuecomment-256150692 @eseidelGoogle says that on Android there are tombstone files saved after crashes and that the logs mention them. We should have the tool automatically notice these messages and save the tombstone files locally for ease of uploading to bugs.

**Comment by dnfield** [comment]
I'm not sure this is really necessary after https://github.com/flutter/flutter/pull/12923 - that change gives you everything you need to symbolicate a crash, which is, AFAICT, all you'd want the tombstone for anyway.

Do we still need this bug?
