### ISSUE TITLE
Error: ADB exited with exit code 1 Performing Streamed Install  adb: failed to install C:\Users\ML\AndroidStudioProjects\i_am_rich\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user] Error launching application on Redmi 8.

### ISSUE THREAD

**Issue by AqeelTariq97** [flutter/flutter#65308]
### Error
Error: ADB exited with exit code 1 Performing Streamed Install  adb: failed to install C:\Users\ML\AndroidStudioProjects\i_am_rich\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user] Error launching application on Redmi 8.
![Screenshot (16)](https://user-images.githubusercontent.com/61206816/92324854-73177100-effa-11ea-87b3-69776dbc54e6.png)
### flutter doctor
C:\Users\ML>flutter doctor -v
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
• Flutter version 1.20.3 at C:\src\flutter
• Framework revision 216dee6 (4 days ago), 2020-09-01 12:24:47 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
• Android SDK at C:\Users\ML\AppData\Local\Android\sdk
• Platform android-30, build-tools 30.0.2
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[√] Android Studio (version 4.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 49.0.2
• Dart plugin version 193.7547
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
• Redmi 8 (mobile) • c255a8000007 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by hamdikahloun** [comment]
Hi @AqeelTariq97 

It's MIUI setting. It's not Flutter issue.

You can take a look here [Stackoverflow](https://stackoverflow.com/questions/47239251/install-failed-user-restricted-android-studio-using-redmi-4-device)

**Comment by AqeelTariq97** [comment]
Thank you soo much @hamdikahloun my problem is solved by your help.

**Comment by LeandroLeonCh** [comment]
Thanks @hamdikahloun  my prblem is solved too

**Comment by vamsimadhav** [comment]
Thanks @hamdikahloun

**Comment by JoyfulAlchemist** [comment]
update android studio and the flutter and dart plugins
