### ISSUE TITLE
FAB in SeachDelegate to Pop Context for Large and Unusual Screen Sizes.

### ISSUE THREAD

**Issue by Maverick099** [flutter/flutter#65309]
## Use case

Since the Screen size is not standard for all android devices. And most of the time navigating back is done by a FAB situated on the right side of the screen for user comfortability. And Search Delegate does not have an option to include a FAB to `Pop Context`  

## Proposal

Since the `SearchDeleagte` is made up of `Scaffold` it would be better to give developers to include an option to include a FAB to navigate to the previous screen.

**Comment by dnfield** [comment]
I'd be happy to hear from the material team on this (/cc @willlarche), but I suspect this is something we wouldn't want to support.

If there are ways to improve the search delegate for larger form factors that's great, but adding a FAB that closes the page doesn't seem quite right to me, for reasons I posted on the linked PR.

**Comment by willlarche** [comment]
Hi! 

Material has a pretty strong [point of view](https://material.io/components/buttons-floating-action-button#usage) for the use of a FAB. And I happen to know that the designers feel equally strongly that a FAB should not be used for navigation. We see it very seldomly IRL. 

So, I don't believe we should make this a prefered user journey.

However, we do recognize that sometimes it's the only way that makes sense. See our own [Gallery](gallery.flutter.dev). For those cases, we recommend rolling your own solution. You can use [our code](https://github.com/flutter/gallery/blob/00c8404ee13ab1383fca94daaeb70f156701d707/lib/pages/home.dart#L1105) as an example.

**Comment by Maverick099** [comment]
Thank you for the reply, It totally make sense after reading the docs that this would be irrelevant

**Comment by willlarche** [comment]
Great!
