### ISSUE TITLE
Failed assertion: line 4941 pos 16: 'child is! ParentDataElement<ParentData>': is not true.

### ISSUE THREAD

**Issue by Sufyan99** [flutter/flutter#65300]

**Comment by iapicca** [comment]
@Sufyan99 can you provide your doctor and a minimal code sample

**Comment by darshankawar** [comment]
@Sufyan99,
Please see my comment in [65299](https://github.com/flutter/flutter/issues/65299) on providing some or all information related to the issue you are facing.
