### ISSUE TITLE
NFC support 

### ISSUE THREAD

**Issue by spravesh1818** [flutter/flutter#65306]
Please add a nice library for nfc.Preferably by the flutter team itself.I had to go back to making native android application for making an app that required nfc.I used nfc_in_flutter which shows empty tag even if there is an ndef message in the tag.This makes it very difficult to make a hybrid application using flutter because all the features supported by native platform doesn't seem to be supported here.Thus I humbly request the flutter team if you could some how come up with a better library with better nfc support.

**Comment by iapicca** [comment]
There are plenty of 3rd party packages for this feature
[flutter_nfc_reader](https://pub.dev/packages/flutter_nfc_reader)
[nfc_in_flutter](https://pub.dev/packages/nfc_in_flutter)
[nfc_manager](https://pub.dev/packages/nfc_manager)
and of course it's always possible to create a custom solution with [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels)

Why should this be a first party plugin? What feature is missing?

**Comment by spravesh1818** [comment]
Yes, there are a lot of packages. But they don't work as intended. I used nfc_in_flutter. But the output it gave me was an empty tag even though I could detect the data in another application. The data was in the NDEF message format as well.But as you said I think I will try and create a custom solution. I just mean is like on android it has native support for NFC,it would be lovely if that is the same case on Flutter.

**Comment by TahaTesser** [comment]
Hi @spravesh1818 
If you've issues without party NFC packages, please create an issue on their dedicated GitHub 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/14209
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
