### ISSUE TITLE
W/System.err(18521)

### ISSUE THREAD

**Issue by ahmadali-2** [flutter/flutter#65314]
Getting Error while debugging app on my phone, SAMSUNG S6 having ANDROID 6.0.1
but working fine on emulator, Nexus 6, 5 etc.

Here is ERROR:
W/System.err(18521): 	at android.os.Parcel.readException(Parcel.java:1626)
W/System.err(18521): 	at android.os.Parcel.readException(Parcel.java:1573)
W/System.err(18521): 	at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:197)
W/System.err(18521): 	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:236)
W/System.err(18521): 	at io.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:274)
W/System.err(18521): 	at io.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:24)
W/System.err(18521): 	at io.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:81)
W/System.err(18521): 	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)
W/System.err(18521): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/System.err(18521): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(18521): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(18521): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(18521): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(18521): 	at android.os.Looper.loop(Looper.java:143)
W/System.err(18521): 	at android.app.ActivityThread.main(ActivityThread.java:7237)
W/System.err(18521): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18521): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
W/System.err(18521): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by darshankawar** [comment]
Hi @ahmadali-2,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows these logs.
Thanks. Also, can you try the same on some recent devices ( > 6) if you have and see if you still see these logs on them ?

**Comment by ahmadali-2** [comment]
@darshankawar 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)

**Comment by ahmadali-2** [comment]
@darshankawar 
C:\Users\Ahmad>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)
• No issues found!

**Comment by ahmadali-2** [comment]
ERROR is accuring in TextField, when i remove textfield error removes.

Here is the CODE:
                        Container(
                          child: TextField(
                            keyboardType: TextInputType.numberWithOptions(decimal: true),
                            style: TextStyle(color: Colors.indigo.shade900, fontSize: 16, fontWeight: FontWeight.w500),
                            decoration: InputDecoration(
                              prefix: Text("Bill Amount - ", style: TextStyle(color: Colors.indigo, fontSize: 18, fontWeight: FontWeight.w500),),
                              prefixIcon: Icon(Icons.attach_money),
                            ),
                            onChanged: (String value){
                              try {
                                _billAmount = double.parse(value);
                              }
                              catch(exception){
                                _billAmount = 0.0;
                              }
                            },
                          ),
                        ),

**Comment by darshankawar** [comment]
@ahmadali-2, are you still experiencing this issue ? Can you debug on the textfield why is it throwing the error ?
Can you also elaborate more on the issue ?

**Comment by ahmadali-2** [comment]
@darshankawar My issue still exists, i think it's Flutter's compatibility issue with the device, it seems like Flutter textField is not much flexible to adjust on all devices.

**Comment by darshankawar** [comment]
@ahmadali-2 
Tried on Android 8 and I am able to type in textfield without any issues.
Can you try with `TextFormField` to see if you get same logs ?

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
