### ISSUE TITLE
  url_launcher: ^5.5.2 

### ISSUE THREAD

**Issue by Topbrains** [flutter/flutter#65317]
Note: /Users/rafael/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.2/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.

**Comment by hamdikahloun** [comment]
Hi @Topbrains 
It's `shouldOverrideUrlLoading(WebView view, String url)` This method was deprecated in API level 24 but still needed for older version.

**Comment by Topbrains** [comment]
Hi @hamdikahloun
I am no using that call all I use is:
  Future<void> _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
Is there a way to silence that warning (like importing only canLaunch?)

**Comment by hamdikahloun** [comment]
@Topbrains `shouldOverrideUrlLoading(WebView view, String url)` it's in Android native code of this plugin.
You can try adding to android/app/build.gradle in the lintOptions block : 
```
lintOptions {
        disable 'InvalidPackage'
        checkAllWarnings false
        ignoreWarnings true       
    }
```
**_All warnings will be disabled_**

**Comment by Topbrains** [comment]
@hamdikahloun
Thanks for your quick reply. I will not turn off the linter. It's like closing your eyes. The issue is still there.
