### ISSUE TITLE
Flutter channel switching problem

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#65316]
I use 2 channels beta  and stable  . Everytime i switch from one to another there is download of approximately 200 mb, as far as i remember it is dart sdk which gets downloaded in case the flutter repo has  not been changed since last switch . what i feel is that this download should be skipped if the dart sdk for both the channel is same . or it might be a issue only in my computer ..

Specs
processor : Intel® Core™ i5-8250U CPU @ 1.60GHz × 8
Os:Ubuntu 20.04.1 LTS
OS type : 64 bit
gnome version:3.36.3
git version : 2.25.1

**Comment by hamdikahloun** [comment]
Hi @amanv8060 
this is the expected behavior here. Whenever you change your flutter version or channel the tool will always download the associated Dart SDK version . If this only happens once after changing your flutter version or channel then there is no issue.

From Flutter documentation:

> As of Flutter’s 1.19.0 dev release, the Flutter SDK contains the dart command alongside the flutter command so that you can more easily run Dart command-line programs. Downloading the Flutter SDK also downloads the compatible version of Dart.

**Comment by darshankawar** [comment]
Hi @amanv8060,
There's similar open issue describing your case, [44212](https://github.com/flutter/flutter/issues/44212).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
