### ISSUE TITLE
PageView Builde error resize

### ISSUE THREAD

**Issue by Zeeshan-progs** [flutter/flutter#65310]
Restarted application in 3,283ms.
I/flutter ( 6488): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6488): The following assertion was thrown during performResize():
I/flutter ( 6488): Horizontal viewport was given unbounded height.
I/flutter ( 6488): Viewports expand in the cross axis to fill their container and constrain their children to match
I/flutter ( 6488): their extent in the cross axis. In this case, a horizontal viewport was given an unlimited amount of
I/flutter ( 6488): vertical space in which to expand.
I/flutter ( 6488): The relevant error-causing widget was:
I/flutter ( 6488):   PageView
[38;5;248mI/flutter ( 6488):[39;49m
I/flutter ( 6488): When the exception was thrown, this was the stack:
[38;5;244mI/flutter ( 6488): #0      RenderViewport.performResize.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 6488): #1      RenderViewport.performResize[39;49m
[38;5;244mI/flutter ( 6488): #2      RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #3      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #4      RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #5      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #6      RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #7      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #8      RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #9      RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #10     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #11     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #12     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #13     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #14     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #15     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #16     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #17     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #18     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #19     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #20     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #21     RenderFlex.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #22     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #23     MultiChildLayoutDelegate.layoutChild[39;49m
[38;5;244mI/flutter ( 6488): #24     _ScaffoldLayout.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #25     MultiChildLayoutDelegate._callPerformLayout[39;49m
[38;5;244mI/flutter ( 6488): #26     RenderCustomMultiChildLayoutBox.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #27     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #28     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #29     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #30     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #31     _RenderCustomClip.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #32     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #33     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #34     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #35     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #36     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #37     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #38     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #39     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #40     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #41     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #42     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #43     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #44     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #45     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #46     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #47     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #48     RenderOffstage.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #49     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #50     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #51     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #52     _RenderTheatre.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #53     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #54     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #55     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #56     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #57     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #58     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #59     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #60     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #61     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #62     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #63     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #64     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #65     RenderObject.layout[39;49m
[38;5;244mI/flutter ( 6488): #66     RenderView.performLayout[39;49m
[38;5;244mI/flutter ( 6488): #67     RenderObject._layoutWithoutResize[39;49m
[38;5;244mI/flutter ( 6488): #68     PipelineOwner.flushLayout[39;49m
[38;5;244mI/flutter ( 6488): #69     RendererBinding.drawFrame[39;49m
[38;5;244mI/flutter ( 6488): #70     WidgetsBinding.drawFrame[39;49m
[38;5;244mI/flutter ( 6488): #71     RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mI/flutter ( 6488): #72     SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mI/flutter ( 6488): #73     SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mI/flutter ( 6488): #74     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>[39;49m
I/flutter ( 6488): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter ( 6488): The following RenderObject was being processed when the exception was fired: RenderViewport#a4cc2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 6488):   needs compositing
I/flutter ( 6488):   creator: Viewport ← IgnorePointer-[GlobalKey#8df6e] ← Semantics ← _PointerListener ← Listener ←
I/flutter ( 6488):     _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#4926a] ←
I/flutter ( 6488):     _PointerListener ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#a285e] ←
I/flutter ( 6488):     RepaintBoundary ← ⋯
I/flutter ( 6488):   parentData: <none> (can use size)
I/flutter ( 6488):   constraints: BoxConstraints(0.0<=w<=432.0, 0.0<=h<=Infinity)
I/flutter ( 6488):   size: MISSING
I/flutter ( 6488):   axisDirection: right
I/flutter ( 6488):   crossAxisDirection: down
I/flutter ( 6488):   offset: _PagePosition#670c3(offset: null, range: null..null, viewport: null, ScrollableState,
I/flutter ( 6488):     _ForceImplicitScrollPhysics -> PageScrollPhysics -> ClampingScrollPhysics ->
I/flutter ( 6488):     RangeMaintainingScrollPhysics, IdleScrollActivity#50c12, ScrollDirection.idle)
I/flutter ( 6488):   anchor: 0.0
I/flutter ( 6488): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 6488):     center child: _RenderSliverFractionalPadding#6235f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488):       child: RenderSliverFillViewport#e99c6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 6488): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderViewport#a4cc2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderViewport#a4cc2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#be221 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#4e0fb relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#9baf9 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#a2c77 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#f6c48 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#48568 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b2982 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#fe533 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#8a6a3 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: RenderBox was not laid out: RenderFlex#57c45 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter ( 6488): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.

**Comment by hamdikahloun** [comment]
Can you provide please:

`flutter doctor -v`

`flutter run -v`

minimal complete reproducible code sample with same widgets and design to check the behavior.

**Comment by Zeeshan-progs** [comment]
> Hi @Zeeshan-progs
> Issue fix in progress : #65015

**Comment by Zeeshan-progs** [comment]
Its still the same

**Comment by hamdikahloun** [comment]
It's still in progress. Will be available so soon.

**Comment by darshankawar** [comment]
@Zeeshan-progs 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Zeeshan-progs** [comment]
_________________________________________________________________________________________________________________________________________


RenderBox was not laid out: RenderFlex#6c468 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1702 pos 12: 'hasSize'

_________________________________________________________________________________________________________________________________________



PS C:\Users\DELL\AndroidStudioProjects\flutter100days> ### **flutter doctor -v**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.2 at C:\src\Flutter\flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)    

• No issues found!
 










PS C:\Users\DELL\AndroidStudioProjects\flutter100days> **### flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.40.1)
[√] Connected device (1 available)

• No issues found!

**Comment by Zeeshan-progs** [comment]
Resolved 



Thanks to all
