### ISSUE TITLE
share: '>=0.6.5 <2.0.0'

### ISSUE THREAD

**Issue by Topbrains** [flutter/flutter#65318]
Note: /Users/rafael/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.5/android/src/main/java/io/flutter/plugins/share/MethodCallHandler.java uses unchecked or unsafe operations.

**Comment by hamdikahloun** [comment]
Hi @Topbrains 
It's the Object Type Casting in `(List<String>) call.argument("paths")`. It's unsafe in Java because if call.argument("paths") it's not List<String> will be ClassCastException...

**Comment by Topbrains** [comment]
Hi @hamdikahloun:

Thanks a lot! This is very actionable. Perhaps add to the documentation of the plugin?

Thanks again
