### ISSUE TITLE
Support golang (e.g. gomobile) integration with Flutter

### ISSUE THREAD

**Issue by elansys-kc** [flutter/flutter#65315]
## Use case

As the following article concluded in 2018. It would be nice if flutter had better gomobile integration.

[Building a mobile frontend for a Go application using Flutter.](https://sites.google.com/a/athaydes.com/renato-athaydes/posts/buildingamobilefrontendforagoapplicationusingflutter)

This is a more recent shorter article that unfortunately misses out some details like filenames.
[Meet the coolest tech marriage: Flutter & Go!](https://medium.com/stack-me-up/meet-the-coolest-tech-marriage-flutter-go-369cf11367c9)

[Slides: Flutter + Gomobile](https://divan.dev/talks/2019/gdgbcn/FlutterGomobile.pdf)

## Proposal

Ideally better integration of the gomobile tool or alternatively a maintained article possibly based on the one above that is easily found alongside the [C interop](https://flutter.dev/docs/development/platform-integration/c-interop) on flutter.dev. This would help developers more easily build apps with a greater depth of packages that are memory safe, easier to write and have even better multicore capabilities than C provides. This should bolster the takeup of Flutter further.

Please thumbs up, if you do or would like to use golang in your flutter project(s)?

**Comment by stuartmorgan** [comment]
> better integration of the gomobile tool

Can you explain what advantage you see to gomobile now that FFI is available?

**Comment by elansys-kc** [comment]
gomobile produces an .aar with Kotlin bindings. I believe this approach uses only memory safe code. I am not an expert and primarily came to flutter for it's web support.

Ideally, I would like guidance as to the recommended approach, perhaps with reasoning. Rather than every developer having to work it out or even worse, grab c libs.

If Dart:FFI is the recommended approach then specific guidance as to how to do so for Go would be useful.

However, when I have looked at Dart:FFI and seen unsafe being in use, it has made me look to gomobile or binary execution.

I expect building android native go binaries and executing them as an asset might be the simplest approach with the best performance. However, I am not sure that Google really wants binaries being executed from within apps. Or how to ensure execution in a flutter app will occur from the right storage, to be compatible with APIs > 30.

p.s. Giving guidelines for C interop without guidelines for memory safe interop isn't ideal. Ideally it might be an idea for *custom* c code as opposed to android c libs to require a permission on Android, as a more important security measure than preventing execution sources, but I guess that is an SDK/NDK and not a flutter matter.

**Comment by pedromassangocode** [comment]
Not sure if this should be considered `new feature` or better document Flutter, so I will just label it `proposal` for now. Please feel free to add other labels.

**Comment by elansys-kc** [comment]
#https://github.com/go-flutter-desktop/go-flutter/issues/334

**Comment by elansys-kc** [comment]
#https://github.com/jerson/flutter-openpgp/issues/7

This issue mentions sticking with gomobile, but I don't understand the reason. I assume gomobile handles architecture matters under the hood with swift/kotlin etc.:

"looks like ffi dont work well for mobile because i need to get the architecture in dart and i think gomobile is enough for that but in the future when ffi had a better implementation easly could be used to replace gomobile"

**Comment by elansys-kc** [comment]
This package shows how one might use Dart: FFI for golang. I can't say that I understand the details but without guidance, I plan to utilise the gomobile option as I expect it has already solved some C cross-platform compilation issues and is more cross platform than e.g. xgo and Docker mentioned in the below link (Docker does not run on OpenBSD for example, for when Dart arrives on OpenBSD).

[dexecve](https://pub.dev/packages/dexecve)

Quote:
"You may want to cross compile the library for multiple platforms. Cross compilation of a static golang binary is relatively straight forward these days however it's not as easy to cross compile a library as cgo is required which normally is disabled for cross compilation.

I have found xgo very helpful for this."

**Comment by Hixie** [comment]
I don't expect this is something we will have time to get to soon, but it's worth tracking. We certainly would be happy to advise if this is something that someone would like to champion.

**Comment by elansys-kc** [comment]
Ok, Actually I prefer the smaller amount of boiler plate with the FFI approach. Maybe someone will come up with a better way of integrating gomobile at some time in the future or the android compiler may catch up to the desktop one in simplicity.

Seems less problematic to reduce the functionality of my mobile app for now compared to the electron (more platforms) and native desktop versions if/when released. Thanks

**Comment by elansys-kc** [comment]
Turns out that truly cross platform offline compatible security (Javascript for Open Source BSDs etc.) was problematic without Go, in any case without resorting to manual web crypto. So the mobile app will be delayed until we work out the best way forward, maintenance wise.

**Comment by jerson** [comment]
hi @elansys-kc may this could help, recently I released a new version of a flutter library using Go with FFI without gomobile

Flutter: https://github.com/jerson/flutter-openpgp/tree/v1.0.0-rc1

Go:  https://github.com/jerson/openpgp-mobile/tree/v0.9.1

**Comment by gargakshit** [comment]
Any updates on this?

**Comment by prologic** [comment]
@jerson Are you able to document how you went about creating this Flutter+Go library?

**Comment by jonahwilliams** [comment]
We're not planning to add any built in support for additional languages, but should be possible to use go via method/message channels
