### ISSUE TITLE
[linux web] Appbar title doesn't render properly on chrome 

### ISSUE THREAD

**Issue by mkhan-akhan** [flutter/flutter#65321]
![image](https://user-images.githubusercontent.com/1172020/92334837-a97dea80-f0e5-11ea-8cd0-245f8643f4c5.png)
Application type: Flutter web
Flutter version: 1.21.0-9.2.pre
Debug device: Chrome (web-javascript)
Editor: vscode
Operating system: Ubuntu 20.04
application: default starter counter app

Behaviour: Start in debug mode. Do not resize the window after the application launches. Move the cursor around, over the appbar or the + button at the bottom right. Result is as per the image provided. Resize the screen a wee bit and the title display becomes stable.

**Comment by markusaksli-nc** [comment]
Hi @mkhan-akhan 
Could you please provide your `flutter doctor -v` logs? Is this happening with the default app?
Thank you

**Comment by mkhan-akhan** [comment]
Logs:
aiyub@aiyub-B365M-H:~/projects/starter_counter_app$ flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_NZ.UTF-8)
    • Flutter version 1.21.0-9.2.pre at
/home/aiyub/snap/flutter/common/flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version
30.0.2)
    • Android SDK at /home/aiyub/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/aiyub/Android/Sdk
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter
doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
85.0.4183.83

! Doctor found issues in 1 category.
aiyub@aiyub-B365M-H:~/projects/starter_counter_app$

The issue is happening with every application I have executed so far. For
another example please check flutter/examples/animations

Thanks
Aiyub

**Comment by TahaTesser** [comment]
Hi @mkhan-akhan 
Tried to reproduce this several times 
I am using PopOS 20.04 based on Ubuntu 20.04 and the exact chrome version, still no issues

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.2.pre at /home/taha/Code/flutter_beta
    • Framework revision 81a45ec2e5 (12 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

• No issues found!
```

Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by mkhan-akhan** [comment]
Hi @TahaTesser 

I upgraded as suggested. I am now on Flutter 1.22.0-10.0.pre.93. However I am still getting the same behaviour.
![image](https://user-images.githubusercontent.com/1172020/92520259-6d769100-f26f-11ea-8be4-cf127b5125da.png)

aiyub@aiyub-B365M-H:~/projects/starter_counter_app$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.93, on Linux, locale en_NZ.UTF-8)
    • Flutter version 1.22.0-10.0.pre.93 at /home/aiyub/snap/flutter/common/flutter
    • Framework revision 418e424794 (29 minutes ago), 2020-09-09 03:10:05 +0800
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/aiyub/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/aiyub/Android/Sdk
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
aiyub@aiyub-B365M-H:~/projects/starter_counter_app$

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause after several tries using the same chrome version and steps but author seems to have the issue even on latest `master`. The issue needs further investigation.

**Comment by mkhan-akhan** [comment]
Hi @TahaTesser

It seems the issue I have is not specific to my flutter environment but more general. While I was moving my cursor around a pdf attachment in gmail that was opened in Chrome I noticed a similar render issue on the top left.
![20200911_070342](https://user-images.githubusercontent.com/1172020/92792766-f0c7ec00-f401-11ea-9965-87df888fe60a.jpg)

**Comment by yjbanov** [comment]
Do you see this in other Ubuntu machines? I have a similar issue but it's because of some Ubuntu Nvidia driver issues.

**Comment by mkhan-akhan** [comment]
@yjbanov 
Sorry, I have the one Ubuntu machine only. Hence unable to assess.

**Comment by Hixie** [comment]
I think if you are seeing this in GMail then it is unlikely to be a Flutter-specific issue. If you can confirm that this is specific to Flutter please file a new bug with steps showing how to reproduce the problem. Thanks!
