### ISSUE TITLE
[local_auth] TouchID is not working for multiple flutter apps on iOS Devices

### ISSUE THREAD

**Issue by Dharmik-Dalwadi** [flutter/flutter#65328]
**Steps to Reproduce**
Create two separate flutter applications with local_auth plugin.

1. Install 1st app and verify that fingerprint works as expected.
2. Install 2nd one app and verify that fingerprint works as expected.
3. Go back to the 1st app, This time fingerprint is stopped working in the 1st app. authentication pop-up won't appear in the 1st app.

#**Facing the same issue which was reported earlier: https://github.com/flutter/flutter/issues/41187**

**Plugin Version: local_auth: ^0.6.3+1** 

**Flutter Doctor -v:** 
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.14.4 18E224, locale en-GB)
    • Flutter version 1.20.3 at /Users/dharmik.dalwadi/Desktop/flutter
    • Framework revision 216dee60c0 (5 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dharmik.dalwadi/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/dharmik.dalwadi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Users/dharmik.dalwadi/Desktop/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[!] Connected device
    ! No devices available

**Here is my code:**
```import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  bool _canCheckBiometrics;
  List<BiometricType> _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  Future<void> _checkBiometrics() async {
    bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticateWithBiometrics(
          localizedReason: 'Scan your fingerprint to authenticate',
          useErrorDialogs: true,
          stickyAuth: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  void _cancelAuthentication() {
    auth.stopAuthentication();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                RaisedButton(
                  child: const Text('Check biometrics'),
                  onPressed: _checkBiometrics,
                ),
                Text('Available biometrics: $_availableBiometrics\n'),
                RaisedButton(
                  child: const Text('Get available biometrics'),
                  onPressed: _getAvailableBiometrics,
                ),
                Text('Current State: $_authorized\n'),
                RaisedButton(
                  child: Text(_isAuthenticating ? 'Cancel' : 'Authenticate'),
                  onPressed:
                      _isAuthenticating ? _cancelAuthentication : _authenticate,
                )
              ])),
    ));
  }
}

**Comment by sahebsingh416** [comment]
Hello,

I am also facing the same issue.

**Comment by darshankawar** [comment]
HI @Dharmik-Dalwadi,
I tried on latest dev channel and observed that although the `touch ID` dialog shows up, it automatically closes before touching cancel button on it.
I've 2 different app examples using the plugin and switched back and forth between them and observed that when I go back to first app, the touch ID dialog closes automatically.
[RPReplay-Final1599474793.MP4.zip](https://github.com/flutter/flutter/files/5182616/RPReplay-Final1599474793.MP4.zip)


Do you also get to see the touch ID dialog or it doesn't open at all ?
Can you share a video of the issue you are facing ?

The two app examples I tried are: 

1. the `local_auth` plugin official [example](https://github.com/flutter/plugins/tree/master/packages/local_auth/example).
2. An app demo from [Medium](https://medium.com/flutterdevs/local-authentication-in-flutter-1dc27647060c).

**Comment by Dharmik-Dalwadi** [comment]
Hi @darshankawar,
In my case, touch ID dialog doesn't open at all.

Here you can see in the video.
[RPReplay_Final1599476348.MP4.zip](https://github.com/flutter/flutter/files/5182721/RPReplay_Final1599476348.MP4.zip)

**Comment by darshankawar** [comment]
Although I definitely this as an issue, however, there are two different behaviors:

1. When I tried on latest dev channel, the first app closes the touch ID automatically instantly after it opens and doesn't wait for user to tap on cancel button.
2. In OP's case, the first app doesn't show up the touch ID.

**Comment by lzhuor** [comment]
Same here and not only for TouchId. It's the same for FaceId.

**Comment by sudeshkumara** [comment]
I'm also facing the same issue.

As explained by Dharmik-Dalvadi, if we install two applications that use the local_auth package, the first application will not work with fingerprint or face ID. Also, please note that both applications have two different package names.

If we reinstall the first application, the first application will work fine and the second application will not work.

@google-admin Could you please look into this?

**Comment by sudeshkumara** [comment]
I'm also facing the same issue.

As explained by @Dharmik-Dalwadi, if we install two applications that use the local_auth package, the first application will not work with fingerprint or face ID and the second app will work as excepted. Also, please note that both applications have two different package names.

If we reinstall the first application, the first application will work fine and the second application will not work.

@google-admin Could you please look into this?

**Comment by lchwe** [comment]
The same happens to me but it's really hard to reproduce consistently. The bug forces me to reinstall the app, which is not ideal for our users.

**Comment by RameshPMaersk** [comment]
I have the similar issue when I am running the app on iOS devices even with multiple flavors or multiple targets. This could be the bad experience to the users when they use multiple apps parallel.
If I enable it for one app, for the other app or target even not getting that pop up freshly as it is different target (appid).
@google-admin could you please help us with a fix as it is hight priority fix. Thank you!!

**Comment by parthkevadiya** [comment]
i have a facing issue regarding on IOS App, first of all i will run app the app is in resume state that time i will call authenticate method it show me local authenticate screen i will give credential then IOS app  is going to inactive state then again app is coming to resume state i will call authenticate method & give credential  this time IOS app will call to again inactive state  then again my authenticate method is call this process is working continuously. Plz Give me Solution ?

**Comment by danagbemava-nc** [comment]
I can't seem to reproduce this issue using `local_auth: ^2.2.0`  and the plugin example app. 

Given that we haven't had any activtity on this issue for a few years and it doesn't seem to reproduce with the latest plugin version, I'll be closing this as fixed. If anyone still faces this issue, please file a new issue and provide detailed steps to reproduce so that this can be properly investigated. 

Thank you


https://github.com/flutter/flutter/assets/88313112/641512f8-cc2a-4d2b-b544-ae96945e6462

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.19.5 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (2 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E                        • ios            • iOS 17.4.1 21E236
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E                        • ios            • iOS 17.4.1 21E236
    • macOS (desktop)      • macos                                            • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)         • chrome                                           • web-javascript • Google Chrome 123.0.6312.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>
