### ISSUE TITLE
Application destroys when Playing a video using SurfaceView in Flutter when a call attended

### ISSUE THREAD

**Issue by suhail-zartek** [flutter/flutter#65337]
The problem is Screen record Blocking used by surface view destroying the app in android 9.Flutter doesn't support secure flag for video record blocking. So, I used surface view instead of it. But, the problem is, if a call received at the time of playing a video on the player the app being restarted when going back to the player after the call disconnected. But, when I disabled the surface view it works well. But, this problem doesn’t happen on android 10 devices.Also, I've used exoplayer for video playback.

**Steps to Reproduce.**

- Play video
- Call to the device from any other device
- Attend the call and disconnect the call

This is a sample repo to reproduce the issue 
     
https://github.com/suhail-zartek/flutter_player_issue

**Logs**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @suhail-zartek 
Does this happen only Android 9 devices? Have you tried other devices with different Android versions such as Android 10? 
Can you please run the app in debug mode by executing `flutter run --verbose` while the cable is connected pickup call and provide complete logs with the crash
Thank you

**Comment by suhail-zartek** [comment]
@TahaTesser I've checked on android 8,9,10. This not happening in android 10. Also, it doesn't happen on every phone even in android 8 or 10. Few of them faced this issue. One of the devices which faced this issue was redmi 6 pro.

**Comment by TahaTesser** [comment]
Hi @suhail-zartek 
Thanks for confirming it's a device-specific issue, Can you please run the app in debug mode by executing `flutter run --verbose` while the cable is connected pickup call and provide complete logs with the crash to better address the issue 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
