### ISSUE TITLE
Run IOS: Your Xcode version may be too old for your iOS version.

### ISSUE THREAD

**Issue by xinoxapps** [flutter/flutter#65345]
IOS deployment is broken. Runs from Xcode just fine.

[✓] Flutter (Channel master, 1.22.0-10.0.pre.87, on Mac OS X 10.15.6 19G2021, locale nl-NL)
    • Flutter version 1.22.0-10.0.pre.87 at /Users/.../flutter
    • Framework revision 4732a214a7 (3 days ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[✓] Connected device (3 available)
    • iPhone (mobile)  • ab46f1da71da940f85f1b7706e495ca8f547f812 • ios            • iOS 13.6.1
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

**Comment by TahaTesser** [comment]
Hi @xinoxapps 
Can you please provide `flutter run --verbose -d <iphone device>` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by xinoxapps** [comment]
The following error occurs when starting from android studio on a real ios device, regardless of the project. Simulator works fine.

═══════════════════════════════════════════════════════════════════════════════════
Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
2020-09-07 18:36:51.450 ios-deploy[23393:123705] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, serviceName, NULL, &dbgServiceConnection)

**Comment by xinoxapps** [comment]
Seems to be solved after upgrading the phone iOS to 13.7

**Comment by TahaTesser** [comment]
hI @xinoxapps 
Whenever there is Xcode update, make sure to update the ios device first to avoid this. I've come across this before 
Running on 13.7 here too, no issues 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by xinlangzi** [comment]
@TahaTesser 

I upgraded my iPhone X to latest version 14.0 and upgraded the xCode to 12.0. Now I can't run into my real device iPhone X.
Do you have solution?

```
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        13.9s
Xcode build done.                                           26.4s
═══════════════════════════════════════════════════════════════════════════════════
Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
2020-09-22 15:55:49.655 ios-deploy[20636:211187] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not run build/ios/iphoneos/Runner.app on 87d8b3e09.......adc15571f5dbf2.
Try launching Xcode and selecting "Product > Run" to fix the problem:   
  open ios/Runner.xcworkspace                                           
                                                                        
Installing and launching...                                        11.7s
Error launching application on Xinlangzi’s iPhone.
```

**Comment by TahaTesser** [comment]
@xinlangzi 
Update your flutter, make sure it's the latest

**Comment by xinlangzi** [comment]
@TahaTesser 

Thank you. After upgrading to stable flutter 1.20.4, we are facing the below exception if we disconnect my phone (iOS 14.0)  from command line "flutter run" debug mode. I think some people are reporting this issue too. Do you have any idea?

```
Exception Type:  EXC_BAD_ACCESS (SIGKILL - CODESIGNING)
```

**Comment by ProFive** [comment]
The same problem 
`Running "flutter pub get" in app...
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: DQ762HHYAB
Running pod install...
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile
Xcode build done.                                           96.6s
Installing and launching...
═══════════════════════════════════════════════════════════════════════════════════
Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
2020-09-23 14:38:42.302 ios-deploy[68599:421979] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not run build/ios/iphoneos/Runner.app on 00008030-000A3189226B802E.
Exited (sigterm)
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.
`

**Comment by TahaTesser** [comment]
@xinoxapps 
That issue you're facing is this https://github.com/flutter/flutter/issues/60657#issuecomment-694319099 and, you can fix it by updating to `beta` for now
