### ISSUE TITLE
JSON Exception on flutter web

### ISSUE THREAD

**Issue by ochmist** [flutter/flutter#65343]
Hello guys, I am using flutter for a web app and I am running into the following problem when the app first starts, if I refresh the browse it then works perfectly. I am using a FutureBuilder in my in my App which initializes Firebase.

```'
Uncaught FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.c (https://app.mizizi.io/main.dart.js?version=1:2725:3)
    at Object.arr (https://app.mizizi.io/main.dart.js?version=1:5109:9)
    at Zs.fW (https://app.mizizi.io/main.dart.js?version=1:31115:26)
    at https://app.mizizi.io/main.dart.js?version=1:25546:15
    at aif.a (https://app.mizizi.io/main.dart.js?version=1:4181:71)
    at aif.$2 (https://app.mizizi.io/main.dart.js?version=1:28941:23)
    at ahy.$1 (https://app.mizizi.io/main.dart.js?version=1:28933:30)
    at Po.mV (https://app.mizizi.io/main.dart.js?version=1:29933:41)
    at acH.$0 (https://app.mizizi.io/main.dart.js?version=1:29346:11)
    at Object.tZ (https://app.mizizi.io/main.dart.js?version=1:4299:4
Manifest: Line: 1, column: 1, Syntax error.
```

I am using firebase hosting, not sure if that matters at all. I have experienced this issue with the firebase boilerplate index.html as well. 

Here is my flutter doctor output: 

```
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-9.0.pre at /Users/karou/work/flutter
    • Framework revision 7a43175198 (9 days ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/karou/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```

Any help will be greatly appreciated. Thank you in advance for your help.

**Comment by TahaTesser** [comment]
Hi @ochmist 
Can you please provide `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by ochmist** [comment]
Sorry for the late reply @TahaTesser. So I have narrowed this bug down to a very specific browser (Brave). The thing that bothers me is I cannot reproduce it in dev mode, only once it is deployed. 
Would you please describe a way I can get a similar deployment to my prod setup in dev?

**Comment by TahaTesser** [comment]
Hi @ochmist 
Please provide a minimal code sample, I would reproduce it by deploying on Brave 
Thank you

**Comment by ochmist** [comment]
Working on it.

**Comment by ochmist** [comment]
After deeper debugging, the issue is not in the framework but in a 3rd party library I was using. Closing. Thanks for the help.

**Comment by BasanthVerma** [comment]
@ochmist which library was it?

**Comment by IoanaAlexandru** [comment]
I'm also facing the same issue with my app, in Chrome, when running `flutter run --release -d chrome`. @ochmist could you please share your experience?

**Comment by ochmist** [comment]
Hey guys, i am so sorry. It has been a while and I do not remember exactly which library it was. Let me try to look through my changes and see if I will be able to locate it.

**Comment by KSingh1980** [comment]
I am facing the same issue. Did you recall what library you used?

**Comment by KSingh1980** [comment]
> I'm also facing the same issue with my app, in Chrome, when running `flutter run --release -d chrome`. @ochmist could you please share your experience?

Did you get any solution for this issue ?

**Comment by KSingh1980** [comment]
@IoanaAlexandru  Did you find any solution for this issue?

**Comment by IoanaAlexandru** [comment]
@KSingh1980  Not really, I think I worked around it by building the web release version and serving it over HTTP: https://stackoverflow.com/questions/62195515/access-flutter-localhost-from-real-mobile-browser
