### ISSUE TITLE
 flutter app keeps encoding code

### ISSUE THREAD

**Issue by MahmoudElbokl** [flutter/flutter#65346]
I left my code for a while (2 days) after that I found it as it looks in the attachment, and I don`t know how and why this happened,
kindly help me solve this issue.

![image](https://user-images.githubusercontent.com/55541781/92397108-7c9df780-f126-11ea-88aa-a57cc11be484.png)

**Comment by TahaTesser** [comment]
Hi @MahmoudElbokl 
Not sure what that screenshot is about, it looks like image file 
Please explain the issue in detail and provide steps to reproduce 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by MahmoudElbokl** [comment]
Hi @TahaTesser 

**This is my code** 


`import 'dart:io';
import 'dart:convert';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:otg_managment_app/servies/custom_exception.dart';
import 'package:requests/requests.dart';

class ApiProvider {
  final String _baseUrl = "http://pms.onetecgroup.com/api/";

  Future<dynamic> get(String endPoint) async {
    var responseJson;
    print(_baseUrl + endPoint);
    try {
      Response response = await Requests.post(_baseUrl + endPoint,
          bodyEncoding: RequestBodyEncoding.FormURLEncoded);
      debugPrint("$endPoint API ${response.content()}");
      response.raiseForStatus();
      responseJson = responseChecker(response);
      debugPrint("$endPoint API $response $responseJson");
    } on SocketException {
      throw FetchDataException('No Internet connection');
    }
    return responseJson;
  }

  Future<dynamic> post(String endPoint, Map<String, dynamic> body) async {
    var responseJson;
    print("object 2 $body");
    try {
      Response r = await Requests.post(_baseUrl + endPoint,
          body: body, bodyEncoding: RequestBodyEncoding.FormURLEncoded);
      debugPrint("$endPoint API $r");
      r.raiseForStatus();
      debugPrint("$endPoint API ${r.content()}");
      responseJson = responseChecker(r);
      debugPrint("$endPoint API $r $responseJson");
    } on SocketException {
      throw FetchDataException('No Internet connection');
    }
    return responseJson;
  }

  dynamic responseChecker(response) {
    print("RES ${response.statusCode}");
    switch (response.statusCode) {
      case 200:
        var responseJson = response.content();
        print(responseJson);
        return responseJson;
      case 202:
        print("1520 ${jsonDecode(response.body)["type"][0]}");
        print("1521 ${jsonDecode(response.body)["type"]}");
        String error;
        error = jsonDecode(response.body)["type"];
        print(error);
        return BadRequestException(error);
      case 400:
        print("1520 ${jsonDecode(response.body)["error"][0]}");
        print("1521 ${jsonDecode(response.body)["error"]}");
        String error;
        if (jsonDecode(response.body)["error"] is List) {
          error = jsonDecode(response.body)["error"][0];
        } else {
          error = jsonDecode(response.body)["error"];
        }
        throw BadRequestException(error);
      case 401:
        throw UnauthorisedException(jsonDecode(response.body)["error"]);
      case 403:
        throw UnauthorisedException(response.body.toString());
      case 426:
        throw UpgradeRequired(response.body.toString());
      case 500:

      default:
        throw FetchDataException(
            'Error occured while Communication with Server with StatusCode : ${response.statusCode}');
    }
  }
}`


**I left it for 2 days then when I open the project again I found that the code becomes** 

`import 'package:path/path.dart';
import 'package:pedantic/pedantic.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_example/utils.dart';
import 'package:test/test.dart';

void main() {
  group('sqflite', () {
    test('open null', () async {
      var exception;
      try {
        await openDatabase(null);
      } catch (e) {
        exception = e;
      }
      expect(exception, isNotNull);
    });
    test('exists', () async {
      expect(await databaseExists(inMemoryDatabasePath), isFalse);
      var path = 'test_exists.db';
      await deleteDatabase(path);
      expect(await databaseExists(path), isFalse);
      var db = await openDatabase(path);
      try {
        expect(await databaseExists(path), isTrue);
      } finally {
        await db?.close();
      }
    });
    test('close in transaction', () async {
      // await Sqflite.devSetDebugModeOn(true);
      var path = 'test_close_in_transaction.db';
      var factory = databaseFactory;
      await deleteDatabase(path);
      var db = await factory.openDatabase(path,
          options: OpenDatabaseOptions(version: 1));
      try {
        await db.execute('BEGIN TRANSACTION');
        await db.close();

        db = await factory.openDatabase(path,
            options: OpenDatabaseOptions(version: 1));
      } finally {
        await db.close();
      }
    });

    /// Check if a file is a valid database file
    ///
    /// An empty file is a valid empty sqlite file
    Future<bool> isDatabase(String path) async {
      Database db;
      var isDatabase = false;
      try {
        db = await openReadOnlyDatabase(path);
        var version = await db.getVersion();
        if (version != null) {
          isDatabase = true;
        }
      } catch (_) {} finally {
        await db?.close();
      }
      return isDatabase;
    }

    test('read_only missing database', () async {
      var path = 'test_missing_database.db';
      await deleteDatabase(path);
      try {
        var db = await openReadOnlyDatabase(path);
        fail('should fail ${db?.path}');
      } on DatabaseException catch (_) {}

      expect(await isDatabase(path), isFalse);
    });

    test('read_only empty file', () async {
      var path = 'empty_file_database.db';
      await deleteDatabase(path);
      var fullPath = join(await getDatabasesPath(), path);
      await Directory(dirname(fullPath)).create(recursive: true);
      await File(fullPath).writeAsString('');

      // Open is fine, that is the native behavior
      var db = await openReadOnlyDatabase(fullPath);
      expect(await File(fullPath).readAsString(), '');

      await db.getVersion();

      await db.close();
      expect(await File(fullPath).readAsString(), '');
      expect(await isDatabase(fullPath), isTrue);
    });

    test('read_only missing bad format', () async {
      var path = 'test_bad_format_database.db';`
    
**and some files become** 

`�PNG

   
IHDR   0   0   W��   tEXtSoftware Adobe ImageReadyq�e<  �IDATx��Y]H#W�����ht4��w)��fZ(,�i�e����>,�BAv�Bɾ�PZ�V[�e�}i�P*H��h������NH��f�ɝ�a/rg2s�9����ܱ���1ѭ����\.�j���eRӴ�h4����$�z<2`��q�/�?���z��[ZZ�� UUYWW�Kt�B9�-˫�����$U����~�<��[������T�Xy���!X�1@�5UWWW]�����@ ��N(I�����2 �����<7�����5Dx�
�6�����/E#?v�`߼n�{�J}�5���c�Q��ۙ��S�ᱽ��o�w3P<��O���C��)��Ӕ����G�z��f���L&Y,c;;;,�J鍣tttL���3^=�v 	����|���o666��D"�---izc~G�!�&+�a�]�xR�ݓ�����t����v�������N�����n�1 �x)��F�*��~}qq��Gx&ʋjCCC>�'�<��r��s�!<���*e� ��(J����y�Cy\���d V�ݭ��.&�+찻,.�U�7����̰y��4�5)�]}F��O��a� /�Ӂ2�~��`���2�Ӝ|���ތ��E�z K}��"�s�����qww�
�_P�[p���$�@ba��Dܥ*�$S��^S�!s@X-�`

**all the project files corrupted in this shape and I don't know why this happened.**


**this is the output of flutter doctor**

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Moaaz\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Moaaz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**this is the output of flutter run --verbose**

[ +112 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +185 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.2
[  +14 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] executing: C:\Users\Moaaz\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +35 ms] List of devices attached
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +47 ms] No supported devices connected.
[   +7 ms] "flutter run" took 181ms.
[  +16 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:343:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +258 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1


Thank you

**Comment by TahaTesser** [comment]
Hi @MahmoudElbokl 
This doesn't look like it's related to Flutter, it doesn't encode files, it's more of an Android Studio issue, Based on my Google search.
Please check this out https://stackoverflow.com/questions/39932158/file-was-loaded-in-the-wrong-encoding-utf-8-in-android-studio
Can you open those same files in the VS Code and check what they look like?

**Comment by MahmoudElbokl** [comment]
Hi @TahaTesser 

in VS Code it happened but only in one file after I see the mentioned link the problem is solved and it is related to IDE not flutter.

Thank you for your help.
