### ISSUE TITLE
Hot reload or even hot restart are not reflecting changes unless I stop and restart the application

### ISSUE THREAD

**Issue by Ninfa-Jeon** [flutter/flutter#65341]
I was trying to add a widget as a background to one of my screens. The screen was using Stack widget for layout so I pretty much knew where I was supposed to add the new code. The code before I made changes to it is as follows:
```
Stack(
        children: [
          BaseColorWidget(),
          Align(
            alignment: Alignment.center,
            child: SizedBox(
              height: 500.0,
              child: GridView.builder(
                itemCount: 6,
                shrinkWrap: true,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  crossAxisSpacing: 10.0,
                  mainAxisSpacing: 50.0,
                ),
                scrollDirection: Axis.horizontal,
                itemBuilder: (BuildContext context, int index) {
                  return CustomCard(
                    shape: BeveledRectangleBorder(
                      borderRadius: BorderRadius.all(
                        Radius.circular(20.0),
                      ),
                    ),
                    alignment: MainAxisAlignment.center,
                  );
                },
              ),
            ),
          ),
        ],
      ),

```
I added the code right above my gridview builder to make sure it was visible when i performed a hot reload.
The code that i added was:
```
Align(
            alignment: Alignment.bottomRight,
            child: Opacity(
              opacity: 0.6,
              child: Card(
                child: Container(
                  height: 600.0,
                  width: MediaQuery.of(context).size.width - 20.0,
                  // child: Form(),
                ),
                elevation: 0.0,
                shape: BeveledRectangleBorder(
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(30.0),
                  ),
                ),
              ),
            ),
          )
```
I added this and tried reloading but no changes were reflected. Then i tried hot restart but it was still the same. Eventually, i had to stop the running application and give it a fresh start to see the changes finally rendered.
Following are the results from Flutter doctor:

```
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.21.0-9.2.pre at C:\flutter\flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: G:\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at G:\android studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.45.1)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • CPH1809 (mobile) • 9a698cdc   • android-arm64  • Android 8.1.0 (API 27)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

! Doctor found issues in 1 category.
```
I hope i can find an answer to this as i tend to think that something is wrong with my code that its not rendering. Thanks

**Comment by Ninfa-Jeon** [comment]
Update: now even other changes are not showing up in hot reload/hot restart. It is starting to upset me. I tried changing opacity of a floating action button but it doesnt reflect until i give it a fresh restart.

**Comment by TahaTesser** [comment]
Hi @Ninfa-Jeon 
Can you please try hot reload from when running from `flutter run --verbose` to make sure it doesn't happen only on Android Studio
Can you please provide a complete reproducible minimal runnable code sample
Thank you

**Comment by Ninfa-Jeon** [comment]
Okay I just tried performing hot reload when running from `flutter run --verbose` and the issue is still the same...the changes are not reflecting on the emulator/device....there is one thing that I observed earlier though...the hot reload is showing this behaviour only for that screen...the changes i apply to other screens are rendered after a reload...
Also, I'm not sure how much of my code i should paste in here because its split into multiple screens and components...could you please let me know exactly what part of my code is relevant to be put here?

**Comment by Ninfa-Jeon** [comment]
I saw that someone filed a similar issue and among the comments I found this:

[https://github.com/flutter/flutter/issues/49744#issuecomment-581022384](url)

I have refactored my code today and I made changes that ended up giving me imports of the sort shown in the above link...i changed the format of those imports and voila! it works now...im closing the issue with this comment....thank you very much for your time and help.. <3

**Comment by asterisk37n** [comment]
same issue here.

**Comment by Ninfa-Jeon** [comment]
> same issue here.

I have pasted a solution above...kindly try that
