### ISSUE TITLE
Flutter app still shows leading password character on Android even after disabling feature in settings (Security Vulnerability)

### ISSUE THREAD

**Issue by jjmutumi** [flutter/flutter#65352]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
```dart
// lib/main.dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(obscureText: true),
        ),
      ),
    );
  }
}

```
3. On Android, go to settings.
4. Go to 'Security' or 'Security & Location'
5. Uncheck 'Show Passwords' (Display characters briefly as you type)
6. Open Flutter app `bug` and type in any text

**Expected results:** 
There should be **no** characters displayed for any time period as password 

**Actual results:** 
Characters are **displayed** briefly as you type

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.20.3 at C:\flutter
    • Framework revision 216dee60c0 (6 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Joseph\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\Joseph\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.0

[√] Connected device (1 available)
    • Infinix X610B (mobile) • 0425325972000854 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

</details>

**Comment by hamdikahloun** [comment]
Hi @jjmutumi I just tried with some application from play store (native and hybrid) and I don't see any changes. So I don't think it's Flutter issue

**Comment by jjmutumi** [comment]
@hamdikahloun try with password input in browser or any native Android application. The setting makes it so that when you are typing password no character is shown. Specifically Flutter apps will not conform to it.

**Comment by hamdikahloun** [comment]
Google chrome :
![Screenshot_20200907_211422](https://user-images.githubusercontent.com/32666446/92415076-2b562e00-f14f-11ea-98ff-88c559778ecc.jpg)

Setting:
![Screenshot_20200907_210830](https://user-images.githubusercontent.com/32666446/92415083-314c0f00-f14f-11ea-91f7-767a5a4a1315.jpg)

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-10.0.pre.88`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.88, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.88 at C:\Development\flutter_master
    • Framework revision e10bdbbd9d (11 hours ago), 2020-09-07 11:40:03 -0700
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>

The setting on my SM G950F
<img src="https://user-images.githubusercontent.com/68219924/92440794-b5d17880-f1b5-11ea-8d56-66aa06393097.jpg" width="600"/>

Expected vs actual
<img src="https://user-images.githubusercontent.com/68219924/92440839-ca157580-f1b5-11ea-91e0-8027237d8c24.gif" height="500" /><img src="https://user-images.githubusercontent.com/68219924/92440842-cb46a280-f1b5-11ea-954c-ee6b8474649f.gif" height="500" />

cc @AndroidNils 

This was already fixed for web and desktop in https://github.com/flutter/flutter/pull/56794. That was obviously just a platform issue but here it seems like the native setting isn't implemented yet.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
That's right, this setting has not been implemented in Flutter.  The final character is revealed only on iOS, Android, and Fuchsia apps (excluding browser) regardless of any setting:

https://github.com/flutter/flutter/blob/0bb1e573fce0a32c28d1bd3caf26e53405604f48/packages/flutter/lib/src/widgets/editable_text.dart#L2487-L2491

We'll have to pipe this setting through the engine and then use it in that if statement.  It seems that this setting [doesn't exist on iOS](https://apple.stackexchange.com/questions/337292/stop-password-characters-from-being-shown).

**Comment by honzakeller** [comment]
Any news? We have multiple reports from customers for bug in our applications. But it's hard to explain that the bug is in the Flutter framework :D.

**Comment by justinmc** [comment]
This is on my list of issues and I hope to get to it soon.  Meanwhile, if this issue is still unassigned, it's available if anyone else wants to submit a PR.

I think we have a pretty clear path forward by looking at my previous comment, as long as it's easy to read this setting in the Android engine.

**Comment by MobileSoftHK** [comment]
Still no update on this topic?

**Comment by Hixie** [comment]
status update from @LongCatIsLooong: _just merged the engine pull request and it's one small framework pull request away_

**Comment by Hixie** [comment]
This was reverted in https://github.com/flutter/flutter/pull/98089
