### ISSUE TITLE
Desktop screenshot

### ISSUE THREAD

**Issue by ashwin31** [flutter/flutter#65360]
## Use case
I need to take screenshots of whole desktop and send it to cloud. This is to track user activity at random intervals.

## Proposal
I came to flutter desktop development to build and release for windows, Linux, and Mac.

We need these features to build real desktop applications.

**Comment by markusaksli-nc** [comment]
There are third-party packages for this but no official functionality yet as far as I know. Labeling as a new feature request due to this.

**Comment by stuartmorgan** [comment]
This is not something that would be implemented within Flutter itself, or as a first-party plugin, as it's not a common need for desktop software. I recommend filing feature requests for desktop support in one or more of the existing plugins on pub.dev that take native screenshots.

**Comment by Shoothzj** [comment]
> There are third-party packages for this but no official functionality yet as far as I know. Labeling as a new feature request due to this.

Hello, could you tell me which package is for this? Thank you. I am new to desktop development, didn't get the search keyword.

**Comment by 1972chris** [comment]
Yes it’s from iPhone 6 , used a third party app called ibeesoft recovery
too retrieve deleted photos , Facebook messages , text messages. What your
seeing is iPhone backup memory files recovery by by ibeesoft.com
