### ISSUE TITLE
Platform key support for android is producing unsupported modifier combinations

### ISSUE THREAD

**Issue by postcodeing** [flutter/flutter#65367]
The following assertion was thrown during a platform message callback:
Platform key support for android is producing unsupported modifier combinations.
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 596 pos 14: 'et<PhysicalKeyboar'

**Comment by pedromassangocode** [comment]
Hi @postcodeing 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by robotion** [comment]
Platform key support for android is producing unsupported modifier combinations

'package:flutter/src/services/raw_keyboard.dart': Failed assertion: line 580 pos 14: 'et<LogicalKeyboard': Platform key support for android is producing unsupported modifier combinations. #0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39) #1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5) #2 RawKeyboard._synchronizeModifiers (package:flutter/src/services/raw_keyboard.dart:580:14)
