### ISSUE TITLE
Flutter Shared preferences problem while installed 2 applications

### ISSUE THREAD

**Issue by selvas1998** [flutter/flutter#65380]
I have a problem while using 2 apks with same code, one app's data using another app. I need to stop this. Two different storage to access the flutter **shared preferences**.

**Comment by pedromassangocode** [comment]
Hi @selvas1998 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample? 

Please also share the steps to reproduce the issue.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
