### ISSUE TITLE
"no connected devices" when we see an unauthorized device

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6538]
We shouldn't say "no connected devices" if we see an unauthorized device.

```
$ flutter run
Device 0012bae55d88a1be is not authorized.
You might need to check your device for an authorization dialog.
No connected devices.
```

**Comment by srsudar** [comment]
What do you think the simplest fix is for this? Based on where this call is printed in [`flutter_command.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart), other 0-device cases are handled like this:

```dart
    } else if (devices.isEmpty && deviceManager.hasSpecifiedAllDevices) {
      printStatus('No devices found');
      return null;
    }
```

However, I don't currently see anything like `deviceManager.devicePendingAuthorization` in [`DeviceManager`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/device.dart).

I could see either:

1. Adding a method like `devicePendingAuthorization` to `DeviceManager`.
2. Simply changing `No connected devices` to `No available devices`.

Number 2 seems less thorough but just as accurate. There's no need to add an additional 'authorized device' state if this error message is the only place that needs it, I would argue.

What do you think?

**Comment by Hixie** [comment]
I wouldn't necessarily aim for the simplest fix, but I agree with you that there's nothing really gained from doing anything more involved than just changing the message in this case.

**Comment by srsudar** [comment]
I meant simple in a good way, fwiw.

However, I can't repro the output you show above. Do you mean also for the output of `flutter devices`, as shown below?

```
$ flutter --version
Flutter 0.7.1-pre.30 • channel master • git@github.com:srsudar/flutter.git
Framework • revision 7f0f938de7 (12 hours ago) • 2018-08-27 11:11:14 +0200
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

$ flutter run
No connected devices.

$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to diagnose
potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.

• Device 01abfc49119c410e is not authorized.
  You might need to check your device for an authorization dialog.

```

**Comment by Hixie** [comment]
It's possible this has improved since the original bug was filed.

**Comment by zoechi** [comment]
Related #13047

**Comment by oycx** [comment]
we met the  same question,  Have you solved it?
