### ISSUE TITLE
LUCI seems to not use pub in the latest state

### ISSUE THREAD

**Issue by xster** [flutter/flutter#65397]
In https://github.com/flutter/flutter/pull/65234, I'm updating cupertino_icons package to 1.0.0 (which is stable on pub https://pub.dev/packages/cupertino_icons/versions/1.0.0) and in https://github.com/flutter/flutter/pull/65087 I'm updating gallery past https://github.com/flutter/gallery/pull/282 which started importing synthetic package locations. 

Both work locally on flutter pub get but both fail on LUCI. 

cupertino_icon ^1.0.0 doesn't exist in the first case https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870061933069596256/+/steps/run_test.dart_for_hostonly_devicelab_tests_shard_and_subshard_3_last/0/stdout 

and the synthetic package doesn't exist in the second case https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870127907410516896/+/steps/run_test.dart_for_hostonly_devicelab_tests_shard_and_subshard_3_last/0/stdout

Is there some pub caching going on that we need to clear in tests on LUCI?

**Comment by godofredoc** [comment]
@xster I think you mentioned you found the problem, did you ended up fixing the issue?

**Comment by digiter** [comment]
Triage: we heard this is fixed.
