### ISSUE TITLE
I have error Parse message failed after update flutter

### ISSUE THREAD

**Issue by sukitz** [flutter/flutter#65390]
![image](https://user-images.githubusercontent.com/26589818/92484989-961d6d00-f214-11ea-88ae-596d161d2a6c.png)

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Parse message failed: "number":721,"startTime":55258322478,"elapsed":19394,"build":14914,"raster":4086}}}}�~o{"jsonrpc":"2.0", "result":{"type":
Parse message failed: M","name":"vm","architectureBits":64,"hostCPU":"Unknown","operatingSystem":"ios","targ
Parse message failed: CPU":"arm64","version":"2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on \"ios_arm64\"","_profilerMode":"VM","_nat
Parse message failed: eZoneMemoryUsage":0,"pid":1770,"startTime":1599574456766,"_embedder":"Flutter","_maxRSS":277495808,"_currentRSS":26755
Parse message failed: 20,"isolates":[{"type":"@Isolate","id":"isolates\/25921
Parse message failed: 828734791","name":"main","number":"2592128828734791"}],"
Parse message failed: olateGroups":[{"type":"@IsolateGroup","id":"isolateGroups\/3314611313181365563","name":"main.dart","number":"331461
Parse message failed: 13181365563"}]},"id":"1068"}�~~{"jsonrpc":"2.0","m
Parse message failed: hod":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flu
Parse message failed: er.Frame","isolate":{"type":"@Isolate","id":"isolates\/2592128828734791","name":"main","number":"2592128828734791"},
Parse message failed: imestamp":1599575134379,"extensionData":{"number":722,"startTime":55259322549,"elapsed":19148,"build":15091,"raster"
Parse message failed: 732}}}}�~o{"jsonrpc":"2.0", "result":{"type":"VM",
Parse message failed: ame":"vm","architectureBits":64,"hostCPU":"Unknown","operatingSystem":"ios","targetCPU":"arm64","version":"2.9
Parse message failed:  (stable) (Wed Aug 26 12:44:28 2020 +0200) on \"io
Parse message failed: arm64\"","_profilerMode":"VM","_nativeZoneMemoryUsage":0,"pid":1770,"startTime":1599574456766,"
Parse message failed: mbedder":"Flutter","_maxRSS":277495808,"_currentRSS":267550720,"isolates":[{"type":"@Isolate","id":"i
```

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TH)
    • Flutter version 1.20.3 at /Users/sukitz/flutter
    • Framework revision 216dee60c0 (7 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sukitz/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • xxxxxx • ios • iOS 13.6.1

• No issues found!

```

</details>

**Comment by igoriuz** [comment]
Experiencing the same since updating plugins on android studio. It seems that my app starts crashing after a certain period.

```
❯ flutter doctor -v       
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale de-DE)
    • Flutter version 1.21.0-9.2.pre at /Users/ikazhdan/flutter
    • Framework revision 81a45ec2e5 (12 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ikazhdan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```

```
e message failed: e,"id":"libraries\/@920440318","name":"","uri":"package:file\/src\/forwarding\/forwarding_file.dart"},{"type":"@Libra
Parse message failed: ","fixedId":true,"id":"libraries\/@921127901","name":"","uri":"package:file\/src\/backends\/local\/local_link.dart"},{"ty
Parse message failed: ":"@Library","fixedId":true,"id":"libraries\/@922226071","name":"","uri":"package:file\/src\/interfac
Parse message failed: /file_system.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@923466249","name":""
Parse message failed: uri":"package:file\/src\/interface
Parse message failed: file_system_entity.dart"},{"type":"@Library","f
Parse message failed: edId":true,"id":"libraries\/@924242419","name":"","uri":"package:file\/src\/forwarding\/forwarding_file_system_entity.da
Parse message failed: "},{"type":"@Library","fixedId":true,"id":"libraries\/@925247555","name":"","uri":"package:file\/src\/interface\/lin
Parse message failed: dart"},{"type":"@Library","fixedId":true,"id":
Parse message failed: ibraries\/@926143497","name":"","uri":"package:file\/src\/forwarding\/forwarding_link.dart"},{"type":"@Libra
Parse message failed: ","fixedId":true,"id":"libraries\/@927411429","name":"","uri":"package:file\/src\/interface\/directory.dart"},{"type":"@L
Parse message failed: rary","fixedId":true,"id":"libraries\/@928323156","name":"","uri":"package:file\/src\/forwarding\/
Parse message failed: rwarding_file_system.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@929427498","name":"","uri":"pac
Parse message failed: ge:file\/src\/interface\/error_codes.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@9
Parse message failed: 437608","name":"","uri":"package:file\/src\/inte
Parse message failed: ace\/error_codes_dart_io.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@931003337","name":
Parse message failed: ,"uri":"package:fl_chart\/src\/cha
Parse message failed: \/bar_chart\/bar_chart.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@932479717","name":"","uri":"packag
Parse message failed: fl_chart\/src\/chart\/bar_chart\/bar_chart_data.dart"},{"t
Parse message failed: e":"@Library","fixedId":true,"id":"libraries\/@933450083","name":"","uri":"package:fl_chart\/src\/chart\/base\/a
Parse message failed: s_chart\/axis_chart_data.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@934180645","name":"",
Parse message failed: ri":"package:fl_chart\/src\/chart\/base\/base_chart\/base_chart_data.dart"},{"type":"@Library","fixedId":true,"id":"l
Parse message failed: raries\/@935092748","name":"","uri":"package:fl_chart\/src\/chart\/base\/base_chart\/touch_input.d
Parse message failed: t"},{"type":"@Library","fixedId":true,"id":"libraries\/@936336301","name":"","uri":"package:fl_chart\/src\/chart\/
```

**Comment by pedromassangocode** [comment]
Hi @sukitz @igoriuz
Can you please provide `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by sukitz** [comment]
@pedromassangocode
It doesn't show a problem. 
What should I do next?

**Comment by pedromassangocode** [comment]
Do you have an idea of what is causing this issue and the steps to reproduce it?

**Comment by igoriuz** [comment]
It says json-rpc error.

**Comment by pedromassangocode** [comment]
Hi @igoriuz 
Are you using this package https://pub.dev/packages/petitparser?

**Comment by igoriuz** [comment]
Hey @pedromassango unfortunately not. Nearly every flutter package was listed in these error messages. Even widgets.dart from the flutter framework was in this error output. 

I haven't received this error messages anymore since restarting android studio. I'll keep an eye on it.

**Comment by sukitz** [comment]
Hi @igoriuz 
I've restarted But still showing an error message

**Comment by pedromassangocode** [comment]
Hi @sukitz 
It seems like the message is showing up when you do a hot-reload. Can you please provide `flutter run --verbose` and then try to do a hot-reload?

**Comment by sukitz** [comment]
Hi @pedromassangocode 
I have no problem with this command. ```flutter run --verbose```

But i run the command from this button
![image](https://user-images.githubusercontent.com/26589818/92781413-4f737280-f3ce-11ea-91f7-b842e4359d65.png)

When I switch the screen out of Android Studio for a moment, a message pops up.

**Comment by pedromassangocode** [comment]
Could not find the cause of this issue and could not reproduce it with Android Studio so this will need additional triage.

**Comment by Hixie** [comment]
None of the comments here say how to reproduce this problem. We are eager to resolve it but we need to know exactly what you are doing to trigger what you are seeing...

Please file a new bug with clear steps to reproduce and we will look into it! Thanks!

**Comment by dingjianjaja** [comment]
> ![image](https://user-images.githubusercontent.com/26589818/92484989-961d6d00-f214-11ea-88ae-596d161d2a6c.png)
> 
> **Actual results:**
> 
> Logs
> ```
> Parse message failed: "number":721,"startTime":55258322478,"elapsed":19394,"build":14914,"raster":4086}}}}�~�o{"jsonrpc":"2.0", "result":{"type":
> Parse message failed: M","name":"vm","architectureBits":64,"hostCPU":"Unknown","operatingSystem":"ios","targ
> Parse message failed: CPU":"arm64","version":"2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on \"ios_arm64\"","_profilerMode":"VM","_nat
> Parse message failed: eZoneMemoryUsage":0,"pid":1770,"startTime":1599574456766,"_embedder":"Flutter","_maxRSS":277495808,"_currentRSS":26755
> Parse message failed: 20,"isolates":[{"type":"@Isolate","id":"isolates\/25921
> Parse message failed: 828734791","name":"main","number":"2592128828734791"}],"
> Parse message failed: olateGroups":[{"type":"@IsolateGroup","id":"isolateGroups\/3314611313181365563","name":"main.dart","number":"331461
> Parse message failed: 13181365563"}]},"id":"1068"}�~�~{"jsonrpc":"2.0","m
> Parse message failed: hod":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flu
> Parse message failed: er.Frame","isolate":{"type":"@Isolate","id":"isolates\/2592128828734791","name":"main","number":"2592128828734791"},
> Parse message failed: imestamp":1599575134379,"extensionData":{"number":722,"startTime":55259322549,"elapsed":19148,"build":15091,"raster"
> Parse message failed: 732}}}}�~�o{"jsonrpc":"2.0", "result":{"type":"VM",
> Parse message failed: ame":"vm","architectureBits":64,"hostCPU":"Unknown","operatingSystem":"ios","targetCPU":"arm64","version":"2.9
> Parse message failed:  (stable) (Wed Aug 26 12:44:28 2020 +0200) on \"io
> Parse message failed: arm64\"","_profilerMode":"VM","_nativeZoneMemoryUsage":0,"pid":1770,"startTime":1599574456766,"
> Parse message failed: mbedder":"Flutter","_maxRSS":277495808,"_currentRSS":267550720,"isolates":[{"type":"@Isolate","id":"i
> ```
> 
> ```
> [✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TH)
>     • Flutter version 1.20.3 at /Users/sukitz/flutter
>     • Framework revision 216dee60c0 (7 days ago), 2020-09-01 12:24:47 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/sukitz/Library/Android/sdk
>     • Platform android-29, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.7)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.7, Build version 11E801a
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 39.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.48.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.13.2
> 
> [✓] Connected device (1 available)
>     • xxxxxx • ios • iOS 13.6.1
> 
> • No issues found!
> ```

Has anyone solved this problem?
I also encountered this problem,when using iphone by android studio

**Comment by LiMeitong** [comment]
same problem.
