### ISSUE TITLE
Possibility of showing a snackbar in main function

### ISSUE THREAD

**Issue by ReaganRealones** [flutter/flutter#65406]
## Use case

   I have an application that requires internet to use and fetches some info on app launch. I am using a native splash screen and I understand that this runs until the flutter's first frame is rendered so I can do something like this in main.dart file 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
 

 //Make a network request to fetch some data before flutter renders any frame
  await Future.delayed(Duration(seconds: 5));

  runApp(MyApp());
}
```

So if the user does not have an active internet connection, I wanted to show them a snackbar right there before flutter itself renders its first frame.

## Proposal

How possible is it to show a snackbar right inside the main function .i.e without a `context `or `Scaffold` to work with. I decided to go with the native splash screens because the dart way of showing a "Splash screen" does not start immediately.

**Comment by LuizFilipeMedeira** [comment]
@ReaganRealones  Use a FutureBuilder.

 @override
  Widget build(BuildContext context) => FutureBuilder(
          future: Future.delayed(const Duration(seconds: 5)), -> your future here.
          builder: (context, snapshot) => MaterialApp(
              debugShowCheckedModeBanner: false,
              navigatorKey: _navigatorState,
              theme: themeData
),);

**Comment by ReaganRealones** [comment]
@LuizFilipeMedeira

> @ReaganRealones Use a FutureBuilder.
> 
> @override
> Widget build(BuildContext context) => FutureBuilder(
> future: Future.delayed(const Duration(seconds: 5)), -> your future here.
> builder: (context, snapshot) => MaterialApp(
> debugShowCheckedModeBanner: false,
> navigatorKey: _navigatorState,
> theme: themeData
> ),);

This can not work since the moment  `MyApp()` is executed, it will cause the splash screen to stop so it wont matter using the future builder,

**Comment by jonathanbonzali** [comment]
You can’t show the snackBar without a context ! You should possibly  implement  two splash screens , the first  goes with  native and the second   with flutter(They don’t need to be identical)and  then while showing the  flutter splash screen ,  you can check for internet connection and show the the snackbar using FutureBuilder ....

**Comment by ReaganRealones** [comment]
Yeah I guess, I would need to do so. Actually thought about that too because actually many apps do that too, just thought if there was another way. Okay thank you @jonathanbonzali. If you can, kindly give me any ideas for the issue I also submitted yesterday #65405. I will close this for now
