### ISSUE TITLE
External view embedder shouldn't submit frame if threads aren't merged on iOS

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#65404]
If the thread merger is disabled, the thread merger won't merge or unmerge threads. If this is the case, the external view embedder on iOS should ensure that the frame isn't submitted.

**Comment by pcsosinski** [comment]
@blasten this missed the cut for 1.22, I assume we need to CP it?

**Comment by blasten** [comment]
@pcsosinski That is correct. I just added the tag and will follow up with the form.
