### ISSUE TITLE
file_selector plugin

### ISSUE THREAD

**Issue by jasonpanelli** [flutter/flutter#65403]
## Use case

As Flutter applications grow in complexity, and become available to more open platforms (like web or desktop), they might need to access files other than images or videos both for loading, but also for saving. There is also a need for a better cross-platform file when different platforms store files differently. Users should be able to filter files and store files in a way appropriate to the platform they are working on with the right abstractions on the Flutter side.

## Proposal

The new plugin will include functions that will handle load and save file dialogs in platforms that support them and allow for reading and writing to a local file system. It will achieve this with classes that can abstract a file and file type across platforms, meaning allowing for a file to be a path reference or a byte container. File type filters for file dialogs must also support different file type identifiers such as MIME types and extensions; this can be achieved with a new class for file types.

**Comment by stuartmorgan** [comment]
Filed https://github.com/flutter/flutter/issues/70221 for desktop support.

**Comment by stuartmorgan** [comment]
Closing as the plugin exists; remaining work is tracked elsewhere.
