### ISSUE TITLE
Add TextTheme.of(context)

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#65410]
`Theme.of(context).textTheme` is quite a bit of boilerplate, having a `TextTheme.of(context)` would be a good addition.

**Comment by HansMuller** [comment]
Although `TextTheme.of(context)` is a little shorter than what we have now, it's not consistent with the way we've been using `FooTheme.of()` methods, which correspond to a theme, return FooThemeData, etc.

**Comment by feinstein** [comment]
So isn't `TextTheme` itself inconsistent with the theme model, as it doesn't have a `TextThemeData`?

**Comment by HansMuller** [comment]
Yes, absolutely, it's inconsistent with the conventions we've (finally) established.  Unfortunately that's one API we're not currently planning to back out of.

**Comment by feinstein** [comment]
Well, I understand your point, just want to add that for me it usually don't make much of a difference in practical terms, as I just create `ThemeData` once and later I just get the contents inline, like: `Theme.of(context).accentColor`. So if it's a `Theme`, `ThemeData`, `ThemeValue`, `ThemeContent` or any other name, it's just mostly transparent to me, maybe I am missing something here, does it make a practical difference in some scenarios?

I also wonder why you decided to make them 2 separate classes and not put everything directly inside `Theme`.

I understand if you are busy and can't answer these curiosities of mine now :)

**Comment by softmarshmallow** [comment]
Why not you easly just make a TextTheme.of -> and inside that return Theme.of.textTheme ?

**Comment by feinstein** [comment]
Because I want to share my shortcuts easily with the community. That's why I also made [this library](https://pub.dev/packages/text_theme_extensions) but I didn't add it to the repo, as I know it's not the Flutter style, and it wouldn't be accepted.

**Comment by HansMuller** [comment]
I'm going to close this because, nice idea though it is, we're not going to adopt this particular change. Thanks for the contribution though!
