### ISSUE TITLE
Flutter will not let me dive in

### ISSUE THREAD

**Issue by mato37** [flutter/flutter#65425]
```
`Launching lib\main.dart on ONEPLUS A5000 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
error: closed
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: connect error for write: closed
Error launching application on ONEPLUS A5000.`
```

Hello People, 
 i am trying to start programming ... but Android Studio / Flutter SDK is givig me this output.
Can you please help me?

Mato

**Comment by npearson72** [comment]
Have you tried `flutter doctor -v`?

**Comment by darshankawar** [comment]
Hi @mato37,
Did you follow all the [steps](https://flutter.dev/docs/get-started/install) on how to install Flutter ? It's not clear from the description which OS you are trying to run Flutter on. Please visit above link once again corresponding to OS you are on and see if you have all steps covered.

Also, there's similar open issue describing your case, [51690](https://github.com/flutter/flutter/issues/51690) which has various solutions you can try on. See if any of them works for you.
Thanks.

**Comment by mato37** [comment]
> flutter doctor -v

where do i type it in?

**Comment by darshankawar** [comment]
@mato37 run that command from root path of your flutter project. Also check the issue link I referred in my earlier comment and see if any of those solutions work for you.

**Comment by Sameerkash** [comment]
This might be an issue related to USB Debugging mode on the device,  as can be seen with, `adb: connect error for write: closed` 
this happens in Chinese manufacturer phones such as OnepLus, Xiaomi, Oppo they have a second option for `USB Debugging write` or similar,  apart from `allow USB Debugging`. @mato37  please check your developer options on your phone and ensure all settings related to USB Debugging are turned on.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
