### ISSUE TITLE
Manjaro Linux - Flutter doesn't detect my android emulators with `flutter devices`, so I can't launch flutter app with VS Code or CLI

### ISSUE THREAD

**Issue by E-jarod** [flutter/flutter#65424]
When I was on Manjaro KDE, flutter worked perfectly following this [tutorial](https://www.rockyourcode.com/how-to-get-flutter-and-android-working-on-arch-linux/).
Now I'm on Manjaro i3, and I have followed the same tutorial, but android devices are not launching the basic counter app of Flutter.

I have 2 android emulators : `android-10` and `test` : 
``` zsh
❯ avdmanager list avd
Available Android Virtual Devices:
    Name: android-10
    Path: /home/e-jarod/.android/avd/android-10.avd
  Target: Default Android System Image
          Based on: Android API 29 Tag/ABI: default/x86_64
---------
    Name: test
    Path: /home/e-jarod/.android/avd/test.avd
  Target: Default Android System Image
          Based on: Android API 29 Tag/ABI: default/x86_64
```

Flutter list only web devices (no problem here on web): 
```zsh
❯ flutter devices  
2 connected devices:

Web Server (web) • web-server • web-javascript • Flutter Tools
Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83
```

And I don't use Android Studio, but VS Code instead : 

```zsh
❯ flutter doctor -v           
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-9.0.pre at /opt/flutter
    • Framework revision 7a43175198 (11 days ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```

Is there a path problem with my android emulators ? Or maybe I have not installed correctly something ?

**Comment by TahaTesser** [comment]
Hi @E-jarod 
I have come across a similar issue while back on PopOS 20.04

Here what I did to solve the issue, you can do the same major and see if it solves the issue 

1. execute `sudo apt-get install android-tools-adb`
2. Go to SDK manager, install sdk tools 28 and 29, platform-tools 
3. open the Android folder of your flutter project into Android Studio, select Android SDK 28 or 29 in the project structure window and preferences -> flutter SDK - locate Flutter. Let Android Studio download all files and initialize, it will come sometime 

This is just a one-time thing, It solves the for me  in Android Studio and VS Code

**Comment by E-jarod** [comment]
Hi @TahaTesser,
In Arch/Manjaro linux, it's not `apt` but `pacman` packages manager. And for proprietary software we use `yay` (like for example skypeforlinux)

1. I have already installed the `android-sdk-platform-tools` as [the tutorial](https://www.rockyourcode.com/how-to-get-flutter-and-android-working-on-arch-linux/) says ([you can see](https://aur.archlinux.org/packages/android-sdk-platform-tools/) that `adb` is in it) : 

```zsh
❯yay -S android-sdk-platform-tools
```

2. Is this correct ?

```zsh
❯ sdkmanager --install "platform-tools" "platforms;android-28" "platforms;android-29"
Warning: File /home/e-jarod/.android/repositories.cfg could not be loaded.      
[=======================================] 100% Unzipping... android-10/framework
```

3. I have not installed android studio yet, I takes quite a long time to install :weary: . I will try and reply you.

**Comment by E-jarod** [comment]
I hava installed but I haven't anything on my project structure window : 
![2020-09-10-003333_468x620_scrot](https://user-images.githubusercontent.com/57091681/92661648-5bdbca80-f2fd-11ea-95af-66b275b2cbc1.png)

**Comment by TahaTesser** [comment]
Hi @E-jarod 
You need to locate your Android SDK and Flutter SDK to see those files in the window. 
Go to preferences and fix this
Thank you

**Comment by E-jarod** [comment]
I have uninstalled all my SDK and emulators, and reinstalled through Android Studio. Now it's working, thanks @TahaTesser.
But I don't know how to create correctly through CLI, because Android Studio is heavy.

**Comment by TahaTesser** [comment]
Hi @E-jarod 
Glad you resolved the issue, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
