### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#65427]
Please help me here! I can't really solve this problem and it's been a while which makes me worried!! Please Help me out
![Screenshot (150)](https://user-images.githubusercontent.com/63626719/92532249-8c642b80-f24d-11ea-88af-0da79c1e7965.png)

**Comment by TahaTesser** [comment]
Hi @ankitsharma-droid 
This seems to an issue with your Gradle download, either it's not properly downloaded or corrupted 
Please `caches` in your user directory -> `.gradle` folder  and execute `flutter run -v` with a stable internet connection 

If the problem persists Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by ankitsharma-droid** [comment]
> Hi @ankitsharma-droid 
> This seems to an issue with your Gradle download, either it's not properly downloaded or corrupted 
> Please `caches` in your user directory -> `.gradle` folder  and execute `flutter run -v` with a stable internet connection 
> 
> If the problem persists Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you 
> 
> 

Thank You Sir for your suggestion. I solved this error by renaming the parent folder that contained an extra whitespace.

**Comment by TahaTesser** [comment]
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
