### ISSUE TITLE
Incompatible protocol version: client=3.26 vm=4.0 Failed to connect to the VM observatory service at: ws://127.0.0.1:59555/wENc2Z63E2A=/ws java.io.IOException: Incompatible protocol version: client=3.26 vm=4.0

### ISSUE THREAD

**Issue by Ashbuhrz** [flutter/flutter#65453]
Cant Run application neither on the physical device nor in Emulator...the below error comes always

Incompatible protocol version: client=3.26 vm=4.0
Failed to connect to the VM observatory service at: ws://127.0.0.1:59555/wENc2Z63E2A=/ws
java.io.IOException: Incompatible protocol version: client=3.26 vm=4.0

**Comment by markusaksli-nc** [comment]
Hi @Ashbuhrz 
Could you please provide your `flutter doctor -v` logs? Are you facing this issue when running from Android Studio and can you run just fine from terminal?
Thank you

**Comment by Ashbuhrz** [comment]
i didn't try that...i was in hurry...so that i changed my flutter channel to stable from master...

stable works fine👍

**Comment by chengssir** [comment]
Incompatible protocol version: client=3.15 vm=4.0
Failed to connect to the VM observatory service at: ws://127.0.0.1:1024/e6DqD4GwtjE=/ws
java.io.IOException: Incompatible protocol version: client=3.15 vm=4.0

**Comment by chengssir** [comment]
I switched to the Stable version

**Comment by chengssir** [comment]
(base) ➜  flutter_demo_learning flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading android-arm-profile/darwin-x64 tools...                 3.1s
Downloading android-arm-release/darwin-x64 tools...                 1.9s
Downloading android-arm64-profile/darwin-x64 tools...               2.1s
Downloading android-arm64-release/darwin-x64 tools...               1.9s
Downloading android-x64-profile/darwin-x64 tools...                 2.7s
Downloading android-x64-release/darwin-x64 tools...                 1.8s
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/xxxxxx/Documents/flutter
    • Framework revision f139b11009 (5 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

**Comment by TahaTesser** [comment]
Hi @Ashbuhrz 
I see there is a newer open issue with more details,  its regression on the latest `master`
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by crtl** [comment]
Happened to me today after running `flutter upgrade`.
But it only happens in Android Studio (Windows 10).
When I run `flutter run` from CMD it works. When pressing "Run" button in AndroidStudio the app launches but it only shows a white screen and the error is displayed:

```
Incompatible protocol version: client=3.26 vm=4.0
Failed to connect to the VM observatory service at: ws://127.0.0.1:49939/Fsgksz_QDE0=/ws
java.io.IOException: Incompatible protocol version: client=3.26 vm=4.0
```

Flutter doctor:

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.121, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
    • Flutter version 1.22.0-10.0.pre.121 at D:\dev\flutter\sdk
    • Framework revision 6c1a29e54c (13 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.48.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Pixel 4 (mobile) • xxxxxxxxxx • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```
