### ISSUE TITLE
Incompatible protocol version: client=3.26 vm=4.0 Failed to connect to the VM observatory service at: ws://127.0.0.1:51327/FeKITnu5lwA=/ws java.io.IOException: Incompatible protocol version: client=3.26 vm=4.0

### ISSUE THREAD

**Issue by KhayyamA47** [flutter/flutter#65471]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by FabianGroeger96** [comment]
same issue as #65456

**Comment by TahaTesser** [comment]
Hi @KhayyamA47 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/65456
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
