### ISSUE TITLE
Incompatible protocol version: client=3.26 vm=4.0 Failed to connect to the VM observatory service at: ws://127.0.0.1:50441/Ln6FaCqUm_Q=/ws

### ISSUE THREAD

**Issue by PedroFerraresi** [flutter/flutter#65485]

**Comment by TahaTesser** [comment]
Hi @PedroFerraresi 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/65456
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
