### ISSUE TITLE
Next update, please add features for inkwell (ripple effect) on image/other widget. 

### ISSUE THREAD

**Issue by muhammadsaddamnur** [flutter/flutter#65487]
## Use case

very troublesome to create a widget that uses the effect as Inkwell (ripple effect)

## Proposal

Next update, please add features for inkwell (ripple effect) on image/other widget.

**Comment by CiriousJoker** [comment]
"Next update" sounds pretty demanding, especially considering this isn't urgent at all. You can just wrap whatever you want inside an inkwell and call it a day. Am I missing something here?
