### ISSUE TITLE
Can't run Flutter on NFS (flock reports "Bad file descriptor")

### ISSUE THREAD

**Issue by droundy** [flutter/flutter#6549]
## Steps to Reproduce

I expect you may have difficulty reproducing this, but I run into the following error when running flutter:

```
$ flutter
flock: 3: Bad file descriptor
```

The error happens at line 35 of the flutter shell script, which tries to take a lock using the flock utility.  This is on a debian stable computer, and I have no experience using flock with bash, and haven't been able to debug it.  I can make flutter work fine by changing the preceding line such that the if statement fails and a lock is not taken.

I presume file descriptor 3 is supposed to be created by line 50, which reads:

```
) 3< $PROG_NAME
```

but don't care to learn enough bash to figure out why it is not working, particularly as I have a workaround.  But it does seem worth fixing, to make flutter work for folks who aren't comfortable editing a bash script.
## Logs

Can't do this since flutter fails.  Unless I disable the lock, in which case it works fine.
## Flutter Doctor

Again, not relevant.

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
What version of bash?

**Comment by droundy** [comment]
$ bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by Hixie** [comment]
Can you add the indicated line below to your flutter shell script in the indicated position and tell me what it prints when you run `flutter`?
```dart
...
(
  if hash flock 2>/dev/null; then
    stat "$PROG_NAME"                   # ADD THIS LINE
    flock 3 # ensures that we don't simultaneously update Dart in multiple parallel instances
    # some platforms (e.g. Mac) don't have flock or any reliable alternative
  fi
...
```

**Comment by droundy** [comment]
$ bin/flutter
      File: ‘/home/droundy/src/flutter/bin/flutter’
      Size: 2236      	Blocks: 8          IO Block: 1048576 regular file
    Device: 27h/39d	Inode: 43385868    Links: 1
    Access: (0755/-rwxr-xr-x)  Uid: ( 1137/ droundy)   Gid: (  100/   users)
    Access: 2016-10-28 12:17:36.788721252 -0700
    Modify: 2016-10-28 12:18:09.808504939 -0700
    Change: 2016-10-28 12:18:09.808504939 -0700
     Birth: -
    flock: 3: Bad file descriptor

**Comment by droundy** [comment]
It just occurred to me that this is in an NFS-mounted directory, and I know NFS has some differences in locking.  Flutter works fine in /tmp, which is tmpfs.  So I guess maybe you can somehow identify that NFS is in use and avoid flock in that case?

**Comment by Hixie** [comment]
I agree that NFS and locking don't do well, but I wouldn't have expected "Bad file descriptor"...

**Comment by droundy** [comment]
Any chance that a fix for this could go in, so I could use flutter in my home directory over nfs? My current fix is to edit bin/flutter to change 'if hash flock...' to have a misspelling in flock, so that it doesn't use flock, which fails on nfs.  I'm not sure what a proper fix would be, not being an expert in the use of flock.

**Comment by Hixie** [comment]
The problem seems to be that NFS doesn't support exclusive locking on a file descriptor opened in read-only mode, because it wants to write in order to lock the file.

**Comment by Hixie** [comment]
We could just ignore errors from `flock`, I guess... if you replace the `flock 3` line with `flock 3 || true`, does it work for you?

**Comment by Hixie** [comment]
Possible workaround in https://github.com/flutter/flutter/pull/13955

**Comment by Hixie** [comment]
Please let me know if that didn't fix it.

**Comment by droundy** [comment]
After a long vacation, I've confirmed that using 'flock 3 || true' works on
NFS.  Thanks for figuring this out!

**Comment by Hixie** [comment]
Awesome, thanks! Good luck with Flutter!
