### ISSUE TITLE
Generate an AndroidManifest.xml when we create a new flutter app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#655]
Now that we can generate APKs (woohoo!) we can make it easier for developers if we generated a starter AndroidManifest.xml.

Presumably, we can generate this file when the user runs `flutter init`, and we can infer the name from the directory, just as we do when populating the name in pubspec.yaml.

We assume the developer will hand-edit this file later, but the generated xml file should work out of the box.

**Comment by sethladd** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/pull/659
