### ISSUE TITLE
Make flutter webview plugin work on the web using iframes

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#65516]
Flutter webview currently doesn't support web as it is not needed. However, by directly redirecting to the provided url, it makes the developer experience better instead of using platform constraints.
It will also improve the pub points!

**Comment by darshankawar** [comment]
@sidrao2006 Can you please elaborate on the request by giving an example and how it'll benefit devs ?
Thanks.

**Comment by sidrao2006** [comment]
@darshankawar , while using webview, if else condition has to be used for web. However this can be directly implemented in the package. For the web, an iframe can be used which allows fine controls. If an iframe is used, flutter can retain, webview's functionality in the web as well or if this is not possible then a simple redirection would also do.

Benefits

1. Improve pub points
2. Easy usage 
3. Better support as the package will now support all 3 platforms
4. Better code quality as well as functionality

**Comment by yjbanov** [comment]
@sidrao2006 I'm not sure I understand the feature request. You can run a Flutter Web app inside a webview today, including inside Flutter mobile native apps. Redirecting the webview to a provided URL is also supported. Would you be able to propose an API and an example using those API?

**Comment by sidrao2006** [comment]
@yjbanov , my feature request's aim is to make webview compatible with Flutter web

Currently webview runs on android and ios only but with some changes, it will work on web as well using iframes

**Comment by yjbanov** [comment]
Thanks for clarifying! I updated the title of the issue to reflect your suggestion.

/cc @ditman this is probably purely a plugin feature request. I can't think of anything we'd need to do in the framework and/or engine.

**Comment by ditman** [comment]
We have a master tracking issue for this plugin here:

https://github.com/flutter/flutter/issues/45295

(I'm going to close this as a duplicate)

Thanks for the issue @sidrao2006!
