### ISSUE TITLE
How do I remove the # sign from the URL?

### ISSUE THREAD

**Issue by ZhangLiuCheng** [flutter/flutter#65527]
such as https://zx.xbbvip.com/#/ , I need https://zx.xbbvip.com, Thank you!!!

**Comment by darshankawar** [comment]
Hi @ZhangLiuCheng,
It seems there's similar open issue describing your request, [33245](https://github.com/flutter/flutter/issues/33245).
Please follow-up there for updates and any questions.
Closing this as duplicate.
Thanks,
