### ISSUE TITLE
SelecetableRichText

### ISSUE THREAD

**Issue by osamagamal65** [flutter/flutter#65535]
**Selectable Rich Text is a nice feature that should be considered**

**Comment by SeasonLeee** [comment]
....

@osamagamal65 There's already a widget for that purpose:

https://api.flutter.dev/flutter/material/SelectableText/SelectableText.rich.html

https://api.flutter.dev/flutter/material/SelectableText-class.html

**Comment by darshankawar** [comment]
@osamagamal65 You can use `SelectableText.rich` constructor for your need. See above shared links for more reference.
Thanks.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
