### ISSUE TITLE
Xiaomi MIUI 12, app flickering issue.

### ISSUE THREAD

**Issue by kcam0035** [flutter/flutter#65536]
The application started to flicker since the phone updated to MIUI 12.
On the console the following line would come up with every flicker:
UPDATE null, mIsCastMode = false.

From what I can gather, the issue is most prominent when a google map is on screen.
currently using google_maps_flutter: ^0.5.32

Unfortunately, I cannot find any information online.

Things I have tried:
Disable developer options. (Still flickers on release mode)
Casting settings all off.
Wireless display casting off.

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 4.0)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = /path/to/android/studio
    X Android Studio not found at /path/to/android/studio
[√] VS Code (version 1.48.2)
[√] Connected device (1 available)

**Comment by darshankawar** [comment]
Hi @kcam0035,
Please provide a minimal complete reproducible code sample that shows the issue along with a video / gif if possible.
Thanks.

**Comment by kcam0035** [comment]
I shall create a sample application to reproduce the issue and post it here

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.

**Comment by alexaf2000** [comment]
I'm having the same issue.  The screen is flickering with black screen and receiveing the error: 
`D/SurfaceView(10496): UPDATE null, mIsCastMode = false`

Seems happening when Google Maps Widget is visible even when not moving it.

**Comment by alexaf2000** [comment]
> I'm having the same issue. The screen is flickering with black screen and receiveing the error:
> `D/SurfaceView(10496): UPDATE null, mIsCastMode = false`
> 
> Seems happening when Google Maps Widget is visible even when not moving it.
> 
>  app_video.mp4

Also here is visible: https://stackoverflow.com/questions/65225476/flutter-google-map-animation-flickering-problem
