### ISSUE TITLE
Draggable /  DragTarget   freezes in dragging

### ISSUE THREAD

**Issue by amarildolacerda** [flutter/flutter#65546]
master->android    OK
master->web         freezes
master->windows  freezes
beta->android      OK
beta->web           OK

**Comment by pedromassangocode** [comment]
Hi @amarildolacerda 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by amarildolacerda** [comment]
Today I find some way workaround this:

I Change:
     Draggable<...>(
      child: InkWell(.....)
    )

**Comment by pedromassangocode** [comment]
Hi @amarildolacerda 
I need you to provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
https://github.com/flutter/flutter/issues/65546
