### ISSUE TITLE
Figure out an Observatory solution for UWP

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#65559]
Based on recent discussions, the standard Dart observatory solution of having it communicate on a local network port isn't going to work for UWP targets. We'll need to figure out how we're going to do Observatory connections to enable debugging, hot reload, etc.

/cc @clarkezone @csells

**Comment by lmcdougald** [comment]
How hard would it be to use WinUI 3 with the Dart VM in a debug mode? Or is the point to debug the AOT build?

**Comment by MrBirb** [comment]
Last thing @clarkezone :D . Is there any more work to do here or should this be closed?
