### ISSUE TITLE
 Could not resolve all artifacts for configuration ':path_provider:classpath'.

### ISSUE THREAD

**Issue by rashedka** [flutter/flutter#65554]
i have error when add path_provider 

error :

> * What went wrong:
A problem occurred configuring project ':path_provider'.
> Could not resolve all artifacts for configuration ':path_provider:classpath'.
   > Could not find builder-3.3.0.jar (com.android.tools.build:builder:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar
   > Could not find bundletool-0.6.0.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
> Could not get unknown property 'android' for project ':path_provider' of type org.gradle.api.Project.
>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>* Get more help at https://help.gradle.org
BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1

flutter doctor 
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18362.592], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.48.2)
[√] Connected device (1 available)

• No issues found!`

i try search in many websites and search in google about this error

**Comment by hamdikahloun** [comment]
Hi @rashedka 
If you use Gradle 4 change it to 3.3.0 in /android/build.gradle
`classpath 'com.android.tools.build:gradle:3.3.0'`
Or 
In your application folder root run :
`cd android && gradlew cleanBuildCache`
Or
delete C:\Users\ (your User)\ .gradle\caches

**Comment by rashedka** [comment]
i get this error after change classpath :

Launching lib\main.dart on SM A305F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find builder-3.3.0.jar (com.android.tools.build:builder:3.3.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar
   > Could not find bundletool-0.6.0.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
Hi @rashedka,
Do you get this error after adding that plugin and while running `pub packages get` ? If you remove that plugin and run, do you get any error ?
Can you try [this](https://stackoverflow.com/a/61533189) solution and see if it works for you ?
Thanks.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
