### ISSUE TITLE
When should we release package:sentry 4.0.0?

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#65565]
@bruno-garcia When do you think we should release 4.0.0 of `package:sentry`? Do you think we have enough new features and bug fixes to make a pub release?

**Comment by bruno-garcia** [comment]
@yjbanov That makes sense.
We'll keep with additions that are non-breaking for a while next.
Thank you!

**Comment by bruno-garcia** [comment]
@yjbanov Would be nice to get a release out now given that for a 3 weeks likely nothing new will be added.

Q4 will bring a lot more, and we'll focus on non-breaking changes for a while until time comes for a new major.
What do you think?

**Comment by yjbanov** [comment]
SGTM. I'll publish 4.0.0 shortly.

**Comment by bruno-garcia** [comment]
The Sentry SDK was moved over to the Sentry organization. We'll take a bit more time before launching 4.0.0. Sorry for the delay.

The release will be done there. Please follow the repository to get notifications for new releases:

https://github.com/getsentry/sentry-dart/releases
