### ISSUE TITLE
Flutter doctor wrongly suggests we have a plugin for WebStorm

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#6557]
## Steps to Reproduce

Run `flutter doctor`. The output wrongly suggests that we have a plugin for WebStorm:

```
$ flutter doctor
...

[✓] IntelliJ IDEA Ultimate Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[-] IntelliJ WebStorm (version 2016.2.4)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html
...
```

## Expected behavoir

We only support IntelliJ IDEA (Ultimate & CE), so only that should be printed in flutter doctor.

**Comment by danrubel** [comment]
Fixed in https://github.com/flutter/flutter/commit/310b8053353f403b4a2cccd32bff56301a11ec65 ... or not?

**Comment by mit-mit** [comment]
Ah, yes, sorry my flutter was almost a week old :-)
