### ISSUE TITLE
Allow providing arbitrary startup arguments to Chrome "device"

### ISSUE THREAD

**Issue by phackwer** [flutter/flutter#65575]
## Use case

I think it's common sense: it's a pain to always have to restart the app and have to reaccept the exception for the local self signed certificate

## Proposal

Run Chrome with the flag to accept localhost self signed certificates

**Comment by jonahwilliams** [comment]
you could add a command line arg for additonal pass-through arguments, like `--browser-args=whatever,you,want`? This would let you plumb though what you want without the tool having an opinion.

**Comment by jonahwilliams** [comment]
(if you want to work on this I would be happy to review, but we're unlikely to add it ourselves anytime soon)

**Comment by phackwer** [comment]
Thanks, if there is opening for community PRs I will do it. :-)

It really takes a bunch of minutes of my day when I need to reload completely the app because a hot start does not reload assets like translation files. (this also has a ticket now: https://github.com/flutter/flutter/issues/65587)

**Comment by phackwer** [comment]
There is this option here on chrome:

chrome://flags/#allow-insecure-localhost

Now I need to see if it's callable from CLI

**Comment by phackwer** [comment]
There is also this manual option that does not work with Flutter (I just couldn't get it to work):

https://chromium.googlesource.com/chromium/src/+/refs/heads/master/components/security_interstitials/core/browser/resources/interstitial_large.js

It was explained here 
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate?rq=1:

Click anywhere on the page and type a BYPASS_SEQUENCE

"thisisunsafe" is a BYPASS_SEQUENCE for Chrome version 65

"badidea" Chrome version 62 - 64.

"danger" used to work in earlier versions of Chrome

You don't need to look for input field, just type it. It feels strange but it is working.

I tried it on Mac High Sierra.

To double check if they changed it again go to Latest chromium Source Code

To look for BYPASS_SEQUENCE, at the moment it looks like that:

var BYPASS_SEQUENCE = window.atob('dGhpc2lzdW5zYWZl');
Now they have it camouflaged, but to see the real BYPASS_SEQUENCE you can run following line in a browser console.

console.log(window.atob('dGhpc2lzdW5zYWZl'));

**Comment by phackwer** [comment]
Ok, found the argument (seems Mac needs an extra arg, but no Mac around here - I need to kill my browser, so I will edit this note later after testing on Linux):

On Windows
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --ignore-certificate-errors
On Mac OS
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors --ignore-urlfetcher-cert-requests &> /dev/null

**Comment by phackwer** [comment]
@jonahwilliams : 

dev/devicelab/lib/framework/browser.dart

lines 79 to 122 are the ones that detect the browser and add arguments.

But I couldn't get this to work, how exactly to I compile my own local flutter? Can you tell me the link for docs about contributing? Kind of new to Dart and Flutter on that level (so far just a senior engineer using this framework, not hacking it yet - till now, hehehe)

**Comment by phackwer** [comment]
Well this is the place to place it, but I would wrap this around an option like "noSslChecks". Since I can't find easy way to build it here to do a local test, and I'm out of time to follow all the items on "CONTRIBUTING.md", there you go. Could you see if this helps?

![image](https://user-images.githubusercontent.com/4871786/92818771-fd2b5500-f3bf-11ea-8ff0-03e4f1e5b056.png)

**Comment by jonahwilliams** [comment]
The code that you are looking for is located in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/chrome.dart#L179 . The instructions on contributing to the flutter tool are in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/README.md .

This change would need add the option to pass through addition, arbitrary arguments from the flutter run command. Adding flags that ignore certain errors is not something I think the tool should do by default.

> I'm out of time to follow all the items on "CONTRIBUTING.md", there you go. Could you see if this helps?

Like I said, I'd accept a PR which added this functionality but its not something I'm going to add in the near future.

**Comment by konsultaner** [comment]
@jonahwilliams I would love to write a PR. Any tips on where to start? I've never contributed to flutter.

**Comment by jonahwilliams** [comment]
@konsultaner I recommend starting with CONTRIBUTING.md, then looking at the flutter tool specific README.md in packages/flutter_tools.

Then look at https://github.com/flutter/flutter/issues/65575#issuecomment-692428551 for the code that needs to be chnaged
