### ISSUE TITLE
Gallery transformations_demo behaves unexpectedly on web

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#65570]
## Details
The Gallery's transformation demo is slow and hiding / showing hexagons unexpectedly.

![2d-2 2020-09-10 11_28_13](https://user-images.githubusercontent.com/1145719/92781191-c0784300-f358-11ea-8bf5-cc1d4573c5c4.gif)

Steps to reproduce:

1. go to https://gallery.flutter.dev/#/demo/2d-transformations
2. Make your browser window large
3. drag hexagons down and to the right
4. observe some hexagons don't show and that the frame rate seems to drop.

Other issues:

- Clicking "full screen" button twice causes the hexagons to disappear

**Target Platform:** Web
**Target OS version/browser:** Chrome 85
**Devices:** macOS Catalina

[Source code](https://github.com/flutter/gallery/blob/00c8404ee13ab1383fca94daaeb70f156701d707/lib/demos/reference/transformations_demo.dart)

**Comment by yjbanov** [comment]
@johnpryan Does this also happen in `--dart-define=FLUTTER_WEB_USE_SKIA=true`? I can't tell if it's an engine or a framework issue.

**Comment by markusaksli-nc** [comment]
@yjbanov I can't repro the disappearing behavior but the performance is terrible on HTML. Skia works perfectly well.

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.254, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.254 at C:\Development\flutter_master
    • Framework revision 0d8696f655 (2 hours ago), 2020-10-09 01:12:02 -0400
    • Engine revision 349889833c
    • Dart version 2.11.0 (build 2.11.0-203.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6821437\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6821437
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.70

• No issues found!
```
</details>

**Comment by guidezpl** [comment]
Can't repro, closing. If this is still occurring, please reopen an issue at https://github.com/flutter/gallery
