### ISSUE TITLE
Exception: Unable to launch com.example.xxx on DEVICE_ID: ProcessException: Process exited abnormally:

### ISSUE THREAD

**Issue by lutang123** [flutter/flutter#65581]
Here is what I got after running the App (This is the app I am working everyday, it worked well yesterday, and today when I started again, I got these error. This error might happened after I updating Xcode):

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           355.1s
Exception: Unable to launch com.example.iMomentum on 8F6345E4-6C60-41B4-A55F-2EEC6463CCD7:
ProcessException: Process exited abnormally:
com.example.iMomentum: -1

An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.example.iMomentum" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
	The operation couldn’t be completed. (null)
	(null)
  Command: /usr/bin/xcrun simctl launch 8F6345E4-6C60-41B4-A55F-2EEC6463CCD7 com.example.iMomentum --enable-dart-profiling --enable-checked-mode --verify-entry-points --start-paused --observatory-port=0
Error launching application on iPhone 11 Pro Max.
```

Here is the result running "flutter doctor -v":

<details><summary>flutter doctor -v</summary>

 ```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-CA)
    • Flutter version 1.20.3 at /Users/lutang/Developer/flutter
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lutang/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio
      2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (2 available)            
    • AOSP on IA Emulator (mobile) • emulator-5554                        •
      android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max (mobile)   • 8F6345E4-6C60-41B4-A55F-2EEC6463CCD7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```
</details>

I have searched on google trying to solve myself, but I can't find the right answer and sometimes I don't understand people's comments, I have tried "flutter --clean", "flutter upgrade", "sudo gem install cocoapods", " pod setup", and "flutter build ios", but nothing helps.

Please, is there anyone to help me? I don't understand why I got error, what is the problem and how to solve it. Thank you very much!

**Comment by pedromassangocode** [comment]
Hi @lutang123 
Can you please provide your `flutter run --verbose` and your `pubspec.yaml`. If the logs are too long you can provide it as a `.txt` file.
Thank you

**Comment by lutang123** [comment]
update: 

It took me half a day trying to figure out what's going wrong, and only realized that I can just re-start my Macbook and the error goes away and my app runs again! 

conclusion:

After updating Xcode, I should re-start computer to be able to use it.

**Comment by lutang123** [comment]
> Hi @lutang123
> Can you please provide your `flutter run --verbose` and your `pubspec.yaml`. If the logs are too long you can provide it as a `.txt` file.
> Thank you

Hi, thank you for your quick reply and changed to a better title. I later re-started my computer and it runs again, I didn't know it can be that easy...

**Comment by get6** [comment]
@lutang123 Thanks!

I'm using MacBook Air M1. I also occurred the same issue and I solved it using the same way.
