### ISSUE TITLE
FATAL EXCEPTION: lowpool while running a flutter app on android studio

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [flutter/flutter#65588]
Whenever I run a flutter app on Android Studio, I get the following error:

```
 E/AndroidRuntime(20162): FATAL EXCEPTION: lowpool[45]
 E/AndroidRuntime(20162): Process: com.google.android.gms.persistent, PID: 20162
 E/AndroidRuntime(20162): android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14 SQLITE_CANTOPEN): , while compiling: PRAGMA journal_mode
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:729)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:376)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:316)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
 E/AndroidRuntime(20162):     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
 E/AndroidRuntime(20162):     at apdw.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):3)
 E/AndroidRuntime(20162):     at rhn.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
 E/AndroidRuntime(20162):     at rhn.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):124)
 E/AndroidRuntime(20162):     at rhn.a(:com.google.android.gms@203019037@20.30.19 (120400-326531024):300)
 E/AndroidRuntime(20162):     at aahv.run(:com.google.android.gms@203019037@20.30.19 (120400-326531024):11)
 E/AndroidRuntime(20162):     at bocb.run(:com.google.android.gms@203019037@20.30.19 (120400-326531024):2)
 E/AndroidRuntime(20162):     at stf.b(:com.google.android.gms@203019037@20.30.19 (120400-326531024):12)
 E/AndroidRuntime(20162):     at stf.run(:com.google.android.gms@203019037@20.30.19 (120400-326531024):7)
 E/AndroidRuntime(20162):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 E/AndroidRuntime(20162):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 E/AndroidRuntime(20162):     at szg.run(:com.google.android.gms@203019037@20.30.19 (120400-326531024):0)
 E/AndroidRuntime(20162):     at java.lang.Thread.run(Thread.java:919)
 E/AndroidRuntime(20162):     Suppressed: bocn: 
 E/AndroidRuntime(20162):         at tk_trace.40-LogOperation(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.phenotype-ConfigurationChimeraProvider_query(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.phenotype-ConfigurationChimeraProvider_queryWithSignal(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.AsyncOpImpl(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.AsyncOpTask(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.40-LogOperation(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.phenotype-ConfigurationChimeraProvider_query(Unknown Source:0)
 E/AndroidRuntime(20162):         at tk_trace.phenotype-ConfigurationChimeraProvider_queryWithSignal(Unknown Source:0)

```

**Comment by darshankawar** [comment]
Hi @Ankur-Khandelwal,
It seems to be an IO access issue. Do you have proper permissions to access the db ?
Also which plugin are you using to interact with sql db ?
Thanks.

**Comment by Ankur-Khandelwal** [comment]
@darshankawar 

I am facing the problems for any app I try to make in the recent past. Even when I tried to run the default code (The basic floating button tapper) which appears whenever we create a new flutter project, I faced the same issue which has nothing to do with database.

I am facing this issue for a particular phone, when I tried running on another phone, I didn't get these errors.

**Comment by darshankawar** [comment]
@Ankur-Khandelwal not sure how you are seeing that error even for a new Flutter counter project. What phone is that which has this issue ?
Can you also provide how have you setup your Flutter sdk ? Did you follow all the steps as mentioned [here](https://flutter.dev/docs/get-started/install) ? Also provide `flutter doctor -v`.
Thanks.

**Comment by Ankur-Khandelwal** [comment]
Actually previously I was not getting this issue much. Sometimes it occurred, sometimes it didn't. But this time its persistent. 
Yes, I have setup the sdk properly because I have successfully created many apps with it. 
`C:\Users\khand\AndroidStudioProjects\flutter_app_test>flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)
    • Flutter version 1.20.2 at C:\Flutter\flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\khand\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052

[√] Connected device (1 available)
    • Redmi Note 7 Pro (mobile) • c3bdcc22 • android-arm64 • Android 10 (API 29)

• No issues found!

`

**Comment by Abhishek01039** [comment]
Hi @Ankur-Khandelwal 
can you please try `flutter clean` and `flutter pub cache repair`?
and make sure you have given the permission in AndroidManifest file like 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in that project in which you are using SQL database.
thanks

**Comment by Ankur-Khandelwal** [comment]
Hi @Abhishek01039 . I tried the steps mentioned by you. I am still getting the errors. 

And I am getting the errors not for a particular project, but in all the projects for this particular phone. Even for the basic flutter counter code which comes with every new flutter project, I am getting this error.

**Comment by darshankawar** [comment]
@Ankur-Khandelwal,
Can you try the same in VSCode and see if you get the same error ?

**Comment by Ankur-Khandelwal** [comment]
I don't have VS Code installed. And the setup would take some good amount of time. In Android Studio, its working fine on emulator, in other phones, just that its showing this error on Redmi Note 7 Pro, especially after upgrading it to Android 10.

**Comment by darshankawar** [comment]
@Ankur-Khandelwal not sure how is this related to Flutter. Can you try by creating a native Android project in AS and see if you get same error on same phone ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
