### ISSUE TITLE
Doc Request: How to style text

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6559]
Would love to learn how to:

- [x] change fonts - https://github.com/flutter/website/pull/307
- [ ] change styles for text
- [ ] use themes across text
- [ ] best practices for cascading these styles throughout the app

Tactical things:

- [x] how to make text bold?
- [x] how to make text italic?
- [x] how to control opacity of text?
- [x] how to control size of text?
- [x] how to control line height?

**Comment by sethladd** [comment]
Partially addressed by https://github.com/flutter/website/pull/307

**Comment by sethladd** [comment]
After conversation today, we should look to see if we can answer all of these by adding comments and snippets to https://docs.flutter.io/flutter/widgets/RichText-class.html

and probably update the link to RichText from https://docs.flutter.io/flutter/widgets/Text-class.html to explain why you should See Also RichText.

**Comment by Hixie** [comment]
Not sure what to do for bullets 2-4. I have a patch for the "tactical things".

**Comment by sethladd** [comment]
I think 2-4 could be an article that covers rich text in general. Perhaps by updating and broadening the focus of https://flutter.io/custom-fonts/

**Comment by Hixie** [comment]
Ok, I've removed the API label then since I've done the API docs part of it.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1995](https://github.com/flutter/website/issues/1995) via [**ZenHub**](https://www.zenhub.com/)
