### ISSUE TITLE
Hero transition seems to flash the screen before and after

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#656]
When triggering a hero transition, it appears that the screen flashes right before and right after. I see other elements, like the header bar, flash and reappear when the hero transition is complete.

This flash doesn't seem right. Is this a known issue?

Happy to show the demo at my desk.

**Comment by sethladd** [comment]
cc @Hixie @collinjackson

**Comment by Hixie** [comment]
- [ ] Heroes are animated at the overlay layer, which means if you animate a hero that ends up wanting to be behind the toolbar, it'll overlap the toolbar then get snapped behind it, which will seem like a flash. We should find a way to animate the hero below the target toolbar.
- [ ] For some reason it looks like PageRoutes have a black modal barrier behind, which, when combined with the move effect, makes the toolbar look like it's coming up over black.

**Comment by collinjackson** [comment]
I fixed the first thing in #741

**Comment by sethladd** [comment]
We seem to be doing much better here. I don't see a Flash. Need to test again, so assigning to me.

**Comment by eseidelGoogle** [comment]
This may also relate to https://github.com/flutter/flutter/issues/5231.

**Comment by Hixie** [comment]
We don't flash. There are other things we could improve but they're tracked in other bugs.

**Comment by cyberpwnn** [comment]
I've just overlooked heroes for so long because it's always done that. Basically dont put anything inside a hero... I.e. dont use them.
