### ISSUE TITLE
Mac LUCI builders are failing on checkout

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#65601]
About 1 in every 5 LUCI runs on the Mac Engine bots has been failing with an infra failure on the "Ensure checkout cache" step. This started on presubmits sometime around 6pm PST on 2020-09-10 (Thu) and has continued on post-submit runs.

This seems to affect all the Mac engine shards.

Examples:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/1659
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6754
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/4834
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/6758

**Comment by digiter** [comment]
Looks better on recent runs, will keep an eye on it. /cc @godofredoc @keyonghan 
<img width="1330" alt="Screen Shot 2020-09-11 at 09 11 03" src="https://user-images.githubusercontent.com/6259181/92948747-b9ac0780-f40e-11ea-9a44-2dc4ad256724.png">

**Comment by digiter** [comment]
From the dashboard https://ci.chromium.org/p/flutter/g/engine/console, the problem seems gone. I'm not sure about the reason, it could be network recovery, or newer underlying library code in "Ensure checkout cache" step.

**Comment by godofredoc** [comment]
Merging https://github.com/flutter/flutter/issues/65762 into this bug as they are the failing with the same problem.
