### ISSUE TITLE
flutter_test is over opinionated and won't allow network calls.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#65606]
The flutter_test package currently stubs out all http calls and returns a 400.

Apparently this has occurred because in the opinions of the package maintainers unit test should not do network calls.

May I politely suggest that this is overly opinionated.

Decisions as to how a developer constructs their unit tests should be left to the developer.

Can I please ask that you have an option to enable networking so developers can make their own decisions on what is appropriate for their tests cases.

In our case you are essentially doubling the amount of work required to set up mocks.

We have to build a mock server to test all of the api calls and now we will have to build a set of mock responses to test the widgets.  If we were able to do network calls then it would be simple to re-use the mock server for the widget/ui testing.

Whilst the maintainers may think this is not idea, in the real world budgets are constrained and having to unnecessarily build two mock systems is an excessive waste of resources.

**Comment by pedromassangocode** [comment]
Hi @bsutton 
This was previously addressed [here](https://github.com/flutter/flutter/issues/35318) and on the latest version of Flutter you can override this behavior by using `HttpOverrides.global = null;`.  Example:

```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart';

void main() {
  // Overrides the test client for every test, so network call will work.
  setUpAll(() => HttpOverrides.global = null);

  test("HTTP request", () async {
    final result = await get(Uri.http("flutter.dev", "/"));
    expect(result.statusCode, 200);
  });

  testWidgets("Empty widget test", (tester) async {
    // run your tests here
  });
}
```

You can see the solution on SO at https://stackoverflow.com/a/57998506.

Closing as this is not an issue with Flutter itself. If you disagree please feel free to write a comment bellow and I will reopen it.
Thank you
