### ISSUE TITLE
Gallery, Pesto: "Pesto Bruchetta" title is spelled wrongly; should be Bruschetta

### ISSUE THREAD

**Issue by simonegiacomelli** [flutter/flutter#6561]
See https://en.wikipedia.org/wiki/Bruschetta
![image](https://cloud.githubusercontent.com/assets/3785783/19779469/89f79efc-9c81-11e6-8db1-8ca322da32ab.png)

**Comment by eseidelGoogle** [comment]
Oops!  Thanks for the report!  @HansMuller @mpcomplete

**Comment by eseidelGoogle** [comment]
I believe I broke https://travis-ci.org/flutter/flutter/builds/171203992 :/

This is why I shouldn't code. :)

@mpcomplete or @HansMuller would you be willing to take this over?  I'm going to revert.

**Comment by mpcomplete** [comment]
Ha! We made sure to have a unit test that verifies that we misspelled Bruschetta :)

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by simonegiacomelli** [comment]
I've noticed that on the play store the preview image, bruschetta is still badly spelled...

**Comment by sethladd** [comment]
Thanks for the feedback! :) We're about the update our play store listing, the screenshot will be fixed.

Keep the feedback coming!
