### ISSUE TITLE
[url_launcher] canLaunch always return false on Android 11 using app with targetSdkVersion 30

### ISSUE THREAD

**Issue by PerLycke** [flutter/flutter#65613]
## Steps to Reproduce

1. Compile url_launcher example app using targetSdkVersion 30.
2. Run on device, or emulator, using Android 11.

**Expected results:** canLaunch works as expected.

**Actual results:** canLaunch always returns false due to new restrictions in Android 11.

Pointed out in https://github.com/flutter/flutter/issues/63727#issuecomment-690070820

**Comment by PerLycke** [comment]
Android 11 is released, and it's good practise to keep targetSdkVersion up to date, so this might become an issue if devs aren't aware of the issue. While there isn't a real solution, the best workaround should be to use try/catch instead of making use of the canLaunch function (IMO).

**Comment by TahaTesser** [comment]
This is the same issue, https://github.com/flutter/flutter/issues/63727, we won't need a new issue to explain the cause of the problem. I will edit duplicate to better address the issue 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async => _launchURL(),
      ),
    );
  }

  _launchURL() async {
    const url = 'https://flutter.dev';

    print("canLaunch ${await canLaunch(url)}");
    // if (await canLaunch(url)) {
    //   await launch(url);
    // } else {
    //   throw 'Could not launch $url';
    // }
  }
}


```

</details> 

```
I/flutter ( 7863): canLaunch false
I/flutter ( 7863): canLaunch false
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.137, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.137 at C:\Code\flutter_master
    • Framework revision 37e2013774 (3 hours ago), 2020-09-11 04:05:02 -0400
    • Engine revision bdaac368f8
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by singhteekam** [comment]
If you just simply try launch(url) rather than canLaunch(url) then it's working fine for me.
Try this:
void _launchURL() async {
   const url = 'https://pub.dev/packages/url_launcher';
  await launch(url);
 }

**Comment by Aaron-Tuil** [comment]
As written in the library doc [here](https://pub.dev/packages/url_launcher#installation), you have to set up your app for both iOS and Android. And specifically, for Android:

> Starting from API 30 Android requires package visibility configuration in your AndroidManifest.xml otherwise canLaunch will return false. A <queries> element must be added to your manifest as a child of the root element.

And the <queries> element that have to be added to your manifest:

`<queries>
  
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.DIAL" />
    <data android:scheme="tel" />
  </intent>
  
  <intent>
    <action android:name="android.intent.action.SEND" />
    <data android:mimeType="*/*" />
  </intent>
</queries>`

Pay attention: I've first tried to add only the first intent written above because it was the relevant one for me. But I still received false from the canLaunch function until I added all the lines.
