### ISSUE TITLE
Support for rounded path corners

### ISSUE THREAD

**Issue by joshliebe** [flutter/flutter#65627]
From what I can see, #4858 only addresses support for `DashPathEffect` (Using `dashPath()` in the [path_drawing](https://pub.dev/packages/path_drawing) package). What is the equivalent to `CornerPathEffect`?

If this does indeed not exist, would it be possible to add support for this?

**Comment by zanderso** [comment]
Closing for similar reasons as https://github.com/flutter/flutter/issues/4858. fyi @dnfield
