### ISSUE TITLE
Getting error while using Shared Preference 0.5.10 

### ISSUE THREAD

**Issue by Dibyendu1000** [flutter/flutter#65634]
I am using shared preferences in Flutter for storing user data, the code is as follows

```
void setUserValues() async{
    SharedPreferences sharedPrefs = await SharedPreferences.getInstance();
    currentUser.forEach((k,v)=>sharedPrefs.setString(k, v));
  }
```

**`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`**

I have added the shared_preferences 0.5.10 dependency in pubspec.yaml, have done pug get, have imported it, have tried wiping out my Emulator data, flutter clean and cold reboot of the emulator but it seems there is no end to it.

**Comment by pedromassangocode** [comment]
Hi @Dibyendu1000 
I see there's an open issue (https://github.com/flutter/flutter/issues/65334) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
