### ISSUE TITLE
Scaffold with elevation: 0 shows white line between appBar and body on Samsung devices

### ISSUE THREAD

**Issue by ghenry** [flutter/flutter#65631]
## Steps to Reproduce

1. Run this on any samsung device https://github.com/ghenry/scaffold_elevation_0_shows_white_line/

**Expected results:** 

Fluid `primaryColor` top to bottom

**Actual results:** 

<img width="220" height="400" src="https://user-images.githubusercontent.com/159608/92922646-110da000-f42e-11ea-89a3-5ccf89c5708f.jpg">

If I set `  extendBodyBehindAppBar: true` then I see a fluid blue on the above demo app, but in our own app we have:

```body: ColorfulSafeArea(
          bottom: true,
          color: Colors.white,
          child: SlidingUpPanel(
```

If I slide up the panel a tiny bit the white line goes away as the parallax comes in but adding `extendBodyBehindAppBar: true` doesn't get rid of it. See below:

<img width="220" height="500" src="https://user-images.githubusercontent.com/159608/92923203-f687f680-f42e-11ea-9a7e-65f3378f111f.jpg"> | <img width="220" height="500" src="https://user-images.githubusercontent.com/159608/92923208-f7b92380-f42e-11ea-9210-310e714d808d.jpg"> | <img width="220" height="500" src="https://user-images.githubusercontent.com/159608/92923209-f851ba00-f42e-11ea-8207-6da3240b3819.jpg">

Only happens on Samsung. Options? I've tried beta and master channels. The same. 

Thanks!

**Comment by ghenry** [comment]
```
[✓] Flutter (Channel stable, 1.20.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.20.3 at /home/ghenry/development/flutter
    • Framework revision 216dee60c0 (10 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ghenry/Android/Sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /home/ghenry/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/ghenry/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
```

**Comment by pedromassangocode** [comment]
Hi @ghenry 
I cannot reproduce this on latest stable channel (1.20.3) using a Samsung S10+

![65631](https://user-images.githubusercontent.com/67424416/92933324-0e1aab80-f43e-11ea-9003-f03682302e62.png)

Please provide the output of your `flutter run -v` and some information about the device you are facing this issue.
Thank you

**Comment by ghenry** [comment]
Thanks for testing. I've seen this on my S10e, S7 and Galazy A51. Attached.
[flutter_run_verbose_samsung_white_line.txt](https://github.com/flutter/flutter/files/5209476/flutter_run_verbose_samsung_white_line.txt)

**Comment by ghenry** [comment]
A51 attached.
[flutter_run_verbose_samsung_white_line_A51.txt](https://github.com/flutter/flutter/files/5209497/flutter_run_verbose_samsung_white_line_A51.txt)

**Comment by ghenry** [comment]
Actually, doesn't show on an S7. A
[flutter_run_verbose_samsung_no_white_line_S7.txt](https://github.com/flutter/flutter/files/5209504/flutter_run_verbose_samsung_no_white_line_S7.txt)
ttached.

**Comment by ghenry** [comment]
Hi all,

I don't know what I've done, but in our own app, after adding in ScreenUtil().setWidth() etc. so all our sizing, the white line has gone. I'll look at the example app I did to demostrate the issue.

Thanks.

**Comment by ghenry** [comment]
Ah, I know. I was changing my phone resolution to test screenutil on a device. Put it back to my usual, and it's still there. False alarm :-(

**Comment by Hixie** [comment]
This is almost certainly antialiasing. When two rectangles of the same color abut over a subpixel boundary and the color below them is different, the color below them will shine through the antialiasing.

If you change the color behind them, does it go away?

**Comment by ghenry** [comment]
They are both default blue though?

**Comment by pedromassangocode** [comment]
@ghenry I think Hixie means to set the Scaffold's `backgroundColor` to the same color as the appBar

**Comment by ghenry** [comment]
Should that not happen on all resolutions then or only really high ones?

**Comment by ghenry** [comment]
Yep, setting backgroundColor on the Scaffold resolves this. Should have thought of that.

Thanks.

Closing.
