### ISSUE TITLE
_formkey.currentState.reset() doesn't clear the form fileds .

### ISSUE THREAD

**Issue by ashusasamkar** [flutter/flutter#65637]

**Comment by TahaTesser** [comment]
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
