### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#65653]
```
[  +11 ms] Waiting for observatory port to be available...
[ +109 ms] Error waiting for a debug connection: The log reader stopped unexpectedly
[  +57 ms] Error launching application on ....
```

this error equal up to 70% of `flutter run` command globally , i hate this , very very bad .. it force me to run `flutter run` again .. and maybe happens again at this retry !

in general why i run `flutter run` multiple times ?

because the debug console stop logging the print() codes .. it just be silent without any outputs !! , so i close the app and run it again and this waste the day !!

**Comment by Abhishek01039** [comment]
Hi @imeDevelopers 
first of all sorry for this that are you facing again and again.
can you please send your `flutter doctor -v`?
Thanks.

**Comment by iapicca** [comment]
@imeDevelopers 
together with the doctor, as correctly suggested by @Abhishek01039,
please provide tour `flutter run -v` representative of the error.

Does this occure with physical or virtual device?


possibly related to 
https://github.com/flutter/flutter/issues/60353
https://github.com/flutter/flutter/issues/52764

**Comment by TahaTesser** [comment]
Hi @imeDevelopers 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` with the logs that represent the error.
Thank you

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
