### ISSUE TITLE
ChoiceChip() when selected looks disabled when using a dark theme

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#65663]
## Issue description

When using a dark theme, the ChoiceChip() widget looks disabled when it is selected and using default theme, both when created with Theme().dark or when using ColorScheme based themes, default or custom ones.

The situation can of course be corrected by defining a custom (none default) chipTheme for Theme, but it is a reasonable expectation that if you defined your overall theme colors for light and dark modes, that you also get a theme for selected ChoiceChips that are visually legible by default, also in dark mode.

Since the issue can easily be remedied with a custom theme, it is not a big issue, but the current situation does seem like an oversight or poor visual design.

## Steps to Reproduce

**This issue applies to all current Flutter versions and all channels.**

The source code for the issue demo can be found here:
https://gist.github.com/rydmike/b684b8fceaabb4ecabfdfa4b4e00004c

And the issue can easily be demonstrated and tried with this DartPad:
https://www.dartpad.dev/b684b8fceaabb4ecabfdfa4b4e00004c

### Actual results - OK Part - Light theme

The light Chip theme works OK with default light theme:
![image](https://user-images.githubusercontent.com/39990307/92974240-709b9800-f48e-11ea-9ab3-461e6a3e3b98.png)

Light theme also works well with default or custom ColorScheme based themes:
![image](https://user-images.githubusercontent.com/39990307/92974283-86a95880-f48e-11ea-85f5-02bce6186867.png)

### Actual results - FAIL Part - Dark theme

With default dark theme `Theme().dark` the selected ChoiceChip looks disabled or almost invisible:
![image](https://user-images.githubusercontent.com/39990307/92974438-da1ba680-f48e-11ea-9062-46488f2d36c0.png)

The same situation applies to ColorScheme based dark themes, default or custom ones, that even blend a bit of primary color into the canvas color. In this case, thanks the color blend, it is a bit more legible than the default theme, but still very poor.
![image](https://user-images.githubusercontent.com/39990307/92974523-13541680-f48f-11ea-9381-fdd61291520a.png)

## Expected results

It can be expected that when an overall dark theme has been defined, it would also produces legible colors for a ChoiceChip so that when it is selected it would also visually indicate that it is selected and not so that it looks disabled or almost invisible.

### Example fix

If we for the default dark theme add a custom chipTheme, eg like so

```dart
ThemeData.dark().copyWith(
  chipTheme: ChipThemeData.fromDefaults(
    secondaryColor: ThemeData.dark().colorScheme.primary,
    brightness: ThemeData.dark().brightness,
    labelStyle: ThemeData.dark().textTheme.bodyText1,
  ),
),

```
We get a dark selected ChoiceChip like this, where the other chips remain unchanged by the made theme addition:

![image](https://user-images.githubusercontent.com/39990307/92976116-857a2a80-f492-11ea-8727-49fdaa97d7b9.png)

We can use the equivalent solution for the custom ColorScheme based theme used in this example:
``` dart
darkTheme.copyWith(
  chipTheme: ChipThemeData.fromDefaults(
    secondaryColor: darkTheme.colorScheme.primary,
    brightness: darkTheme.brightness,
    labelStyle: darkTheme.textTheme.bodyText1,
  ),
),
```
And get a matching theme for it as well, were only the selected chip was modified, so the example custom fix works for this case too.
![image](https://user-images.githubusercontent.com/39990307/92976434-32ed3e00-f493-11ea-9f38-0a8394bf295d.png)

Likewise we show that if we add the equivalent chip theme's to the default light theme:
```dart
ThemeData.light().copyWith(
  chipTheme: ChipThemeData.fromDefaults(
    secondaryColor: ThemeData.light().colorScheme.primary,
    brightness: ThemeData.light().brightness,
    labelStyle: ThemeData.light().textTheme.bodyText1,
  ),
),
```

and to the ColorScheme based one:
```dart
lightTheme.copyWith(
  chipTheme: ChipThemeData.fromDefaults(
    secondaryColor: lightTheme.colorScheme.primary,
    brightness: lightTheme.brightness,
    labelStyle: lightTheme.textTheme.bodyText1,
  ),
 ),
```

We can see that the equivalent changes and additions to the light themes do not affect the current OK theming on them.

The above example fix, by adding the above additions to the chipTheme, is available as demo here:
https://gist.github.com/rydmike/607763139eab6f81159bcc3a61be1164

It can be tried with DartPade here:
https://www.dartpad.dev/607763139eab6f81159bcc3a61be1164

This was of course only way of theming the selected ChoiceChip. The default for Material standard might call for some other color scheme than this example. It is however doubtful that it calls for a result that is not very legible at all.

## Summary

ChoiceChip, when selected, was shown to have a none legible default sub theme in dark mode.

The issue is not critical and can easily be remedied with a custom chip theme as demonstrated above. It is however reasonable and expected, that if you create a default dark theme or even fully qualified ColorScheme based dark theme, that all the resulting sub themes should follow this theme and be legible by default without necessity to define a custom sub-theme, which is currently needed for chipTheme in dark mode.

<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)     
    • Flutter version 1.21.0-9.2.pre at C:\Users\mryds\fvm\versions\beta
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 192.7402

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • Nexus 7 (mobile) • 0a99f5e8   • android-arm    • Android 6.0.1 (API 23)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
I was able to reproduce this issue on  latest `master` channel.

<img width="240" height="500" src="https://user-images.githubusercontent.com/67424416/93064342-510f9580-f66f-11ea-9ade-4145b5178f0c.gif">


<details><summary>minimal code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isDarkMode;
  bool colorSchemeTheme;

  @override
  void initState() {
    super.initState();
    isDarkMode = false;
    colorSchemeTheme = false;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Issue Discovery',
      darkTheme: ThemeData.dark(),
      themeMode: isDarkMode ? ThemeMode.dark : ThemeMode.light,
      home: Scaffold(
        appBar: AppBar(title: Text('Issue Discovery')),
        body: ListView(
          padding: EdgeInsets.all(24),
          children: <Widget>[
            SwitchListTile.adaptive(
              title: const Text('Use dark theme'),
              subtitle:
              const Text('OFF for light theme, ON for dark theme.'),
              value: isDarkMode,
              onChanged: (bool value) => setState(() => isDarkMode = value),
            ),
            const Divider(),
            ChoiceChip(
              label: const Text('ChoiceChip selected'),
              selected: true,
              onSelected: (bool value) {},
            ),
            ChoiceChip(
              label: const Text('ChoiceChip not selected'),
              selected: false,
              onSelected: (bool value) {},
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.161 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision cba91c97d0 (10 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by DaVaMa1** [comment]
I think this is caused because ChoiceChip uses different defaults for selectedColor (and labelStyle). Where other chips use either chipTheme.labelStyle or chipTheme.selectedColor, choicheChip replaces the defaults when calling RawChip with either:

`labelStyle: labelStyle ?? (selected ? chipTheme.secondaryLabelStyle : null)` 

or 

`selectedColor: selectedColor ?? chipTheme.secondarySelectedColor`

I can't find why this is, and to me it seems counterintuitive. I would propose replacing the implementations for ChoiceChip to be in line with the other chips, and maybe deprecating the secondarySelectedColor and secondaryLabelStyle on ChipTheme, as their only implementations are in the ChoiceChip.

**Comment by rydmike** [comment]
@DaVaMa1 The Chip's implementation is probably one of those Widgets that were made way before the more consistent design of theming was implemented, so I agree that it could need a more overall refresh.

If you are fine with adding some custom Theming to an app that use ChoiceChips, then the examples I show earlier above can be added to the app's Theme. It only changes the default behavior of the broken dark mode ChoiceChip. I've been using that, it works well for my needs.

Still this bug should of course **not** be in the SDK, but I guess it not a very commonly used widget. Also since you can relatively easily fix the issue by making a small custom sub-theme for it, there is an easy workaround, hence it is not such a critical or hi-prio bug.

A package I made, called [FlexColorScheme](https://pub.dev/packages/flex_color_scheme), it's just a theming convenience helper package nothing revolutionary, but it **contains this theme fix baked in**, among a list of many other [minor theming issues/oddities](https://pub.dev/packages/flex_color_scheme#themedata-default-modifications) that it addresses. (I also offers primary color surface branding with different built-in strengths and bunch of pre-made color schemes.)

---

Sidenote:
**ToggleButtons** is also an older Widget that clashes a bit with default expected Theming behavior of buttons. I should make an issue post of it as well, or two issues for the two issues I know of regarding it, so they can be addressed separately. Need to make samples, but first check if the issues exist already...

**Comment by rydmike** [comment]
This issue has been resolved, closing it. Not sure when it was fixed but it has no existed for a while.

Example of Just default ChoiceChip and other chips in dark theme shown below, from Flutter 3.3.8 stable:

![Screenshot 2022-11-15 at 15 14 01](https://user-images.githubusercontent.com/39990307/201928888-0eb6157d-08df-4eb0-9026-670df65f2b40.png)
