### ISSUE TITLE
Logical key ID generation doesn't match the spec on any platform, and the platforms differ.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#65668]
## The Problem:

The following code works on all platforms except for web, because on the web, the key event that is sent always produces a lowercase `logicalKey` ID and the other platforms produce a logical key ID that matches the case of the character produced.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Pressing SHIFT + N (first SHIFT, then N) works on Web but not Mac 

void main() {
  runApp(KeyboardShortcut());
}

class KeyboardShortcut extends StatefulWidget {
  @override
  _KeyboardShortcutState createState() => _KeyboardShortcutState();
}

class _KeyboardShortcutState extends State<KeyboardShortcut> {
  int pressed;

  @override
  void initState() {
    super.initState();
    pressed = 0;
	const LogicalKeyboardKey uppercaseN = LogicalKeyboardKey(0x0000004e, keyLabel: 'N', debugName: 'Uppercase N');
    RawKeyboard.instance.addListener((RawKeyEvent event) {
	  print('Received: $event');
	  print('Keys Down: ${RawKeyboard.instance.keysPressed}');
      if (event.isKeyPressed(uppercaseN)) {
        print('Pressed Shortcut');
        setState(() {
          pressed += 1;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Center(child: Text('Pressed $pressed times.')));
  }
}
```

The output I get when pressing `SHIFT-N` on web is as follows:

```
Received: RawKeyDownEvent#cfd4a(logicalKey: LogicalKeyboardKey#602ee(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"))
Keys Down: {LogicalKeyboardKey#602ee(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#4393c(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Received: RawKeyDownEvent#f1ccd(logicalKey: LogicalKeyboardKey#0006e(keyId: "0x0000006e", keyLabel: "n", debugName: "Key N"), physicalKey: PhysicalKeyboardKey#70011(usbHidUsage: "0x00070011", debugName: "Key N"))
Keys Down: {LogicalKeyboardKey#0006e(keyId: "0x0000006e", keyLabel: "n", debugName: "Key N"), LogicalKeyboardKey#602ee(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#4393c(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Received: RawKeyUpEvent#aee8a(logicalKey: LogicalKeyboardKey#0006e(keyId: "0x0000006e", keyLabel: "n", debugName: "Key N"), physicalKey: PhysicalKeyboardKey#70011(usbHidUsage: "0x00070011", debugName: "Key N"))
Keys Down: {LogicalKeyboardKey#602ee(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#4393c(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Received: RawKeyUpEvent#4a856(logicalKey: LogicalKeyboardKey#602ee(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"))
Keys Down: {}
```

on Linux (and other platforms), it is:

```
Received: RawKeyDownEvent#f94e3(logicalKey: LogicalKeyboardKey#700e1(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"))
Keys Down: {LogicalKeyboardKey#700e1(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#700e5(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Received: RawKeyDownEvent#4860c(logicalKey: LogicalKeyboardKey#0004e(keyId: "0x0000004e", keyLabel: "N", debugName: "Key N"), physicalKey: PhysicalKeyboardKey#70011(usbHidUsage: "0x00070011", debugName: "Key N"))
Keys Down: {LogicalKeyboardKey#0004e(keyId: "0x0000004e", keyLabel: "N", debugName: "Key N"), LogicalKeyboardKey#700e1(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#700e5(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Pressed Shortcut
Received: RawKeyUpEvent#32696(logicalKey: LogicalKeyboardKey#0004e(keyId: "0x0000004e", keyLabel: "N", debugName: "Key N"), physicalKey: PhysicalKeyboardKey#70011(usbHidUsage: "0x00070011", debugName: "Key N"))
Keys Down: {LogicalKeyboardKey#700e1(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), LogicalKeyboardKey#700e5(keyId: "0x1000700e5", keyLabel: "", debugName: "Shift Right")}
Received: RawKeyUpEvent#d0ab3(logicalKey: LogicalKeyboardKey#700e1(keyId: "0x1000700e1", keyLabel: "", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"))
Keys Down: {}
```

Notice the difference in the `keyId` member.

## Musing

It seems that none of the platforms is following the [spec for the key events](https://github.com/flutter/flutter/blob/master/dev/tools/gen_keycodes/README.md#key-code-id-scheme). There are two bugs here. First, on the web it is always producing a key with id `0x6e` (lowercase n), when, according to the spec, it should be producing an event with a logical key id of `0x4e` (uppercase N) and a `keyLabel` of lowercase "n". Second, the other platforms should always be producing `0x4e`, and instead they are switching between that and `0x6e` based on whether the shift key is pressed or not.

My normal inclination is to fix all the implementations to match the spec. This would mean making all platforms produce a key ID corresponding to uppercase N when the n key is pressed, even without the shift key. The problem is that I'm pretty sure that the information necessary to map a lowercase key to its uppercase equivalent is not available on all platforms, or even most (any?). We might be able to map them to their unmodified (no modifier keys pressed) equivalent as web does now.

As for which way is more useful, I'm not sure.  It's surely intuitive to to say `event.isShiftPressed && event.isKeyPressed(LogicalKeyboardKey.keyN)` (which doesn't work to detect upper case N anywhere but web right now), but at the same time, how would someone who wanted to test for a quote key on a French keyboard be expected to know that they would need to use `LogicalKeyboardKey.digit4` instead of `LogicalKeyboardKey.quote`? Perhaps they should just test the `keyLabel` of the `event.logicalKey` or the `event.character` instead of using the convenience constants.

I think making it act like the spec also implies that in order to test for a lowercase n, you'd have to always test for `!event.isShiftPressed && event.isKeyPressed(LogicalKeyboardKey.keyN)` instead of just comparing the `event.logicalKey` to `LogicalKeyboardKey.keyN`, as you would now. So, to make sure it's just a lowercase "n", you'd have either test that all the modifiers were off each time, or compare the `keyLabel` or `character` to `n`.

Another alternative is to make the web match other platforms and produce IDs that match the Unicode value of the key label. But, the downside of having logical keys represent their Unicode value is that some fairly intuitive code doesn't work as expected. For instance, testing whether the "N" key is pressed regardless of the shift state, without testing both "n" and "N" is not possible unless the physical key is used instead, and is made more confusing by the fact that we don't provide convenience constants for uppercase characters. We don't do that because it's not clear what that means when you consider all keyboard layouts (is a '4' lowercase or uppercase? It depends on keyboard layout).

Perhaps providing convenience constants was a mistake, but they are terribly convenient, even if they are somewhat misleading about case. Providing convenience constants for all Unicode characters is intractable and probably inefficient (although one could argue that they'd all get tree-shaken, it would definitely blow up the number of symbols defined for the analyzer and compiler). We could provide a Latin subset, perhaps.

We could eliminate the convenience constants altogether and force people to compare the `keyLabel` or `character` to the key they want. This is far too breaking to even consider, really, but maybe we could replace the key constants with a class that overrides `operator==` to compare the `keyLabel`s instead of the key IDs. Then, assuming it was possible to implement the spec, we could make things match the spec and keep the convenience.

## My Recommendation

I think we should modify the spec to say that the logical key ID matches the unmodified (i.e. without modifier keys) Unicode value of the key label, and then make all the platforms conform to that (web already works this way). So, on a U.S. keyboard pressing `4 $` key regardless of the shift would give you a key ID of `0x34`, but on a French keyboard, pressing a `' 4` would give you a key ID of `0x22` (the quote character), regardless of the shift state. This means comparing the key event resulting in a '4' to a `LogicalKeyboardKey.digit4` would never work on a French keyboard. Developers should instead compare the `RawKeyEvent.character` value if they actually mean "The key producing the character 4".

This will have to be re-evaluated if it turns out not to be possible on all platform APIs to get the unmodified character value of a key event.

I'll need to think about what this means for the `Shortcuts` API, but it might be possible to produce a similar class to `LogicalKeySet` that takes a set of expected characters, and allow the shortcuts to be defined either way. It would use the event's `character` value to see if it is in the set instead of the event's `logicalKey` value.

Note that we need to fix https://github.com/flutter/flutter/issues/65401 in order for comparing the character to work.

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Pressing SHIFT + N (first SHIFT, then N) works on Web but not Mac

void main() {
  runApp(KeyboardShortcut());
}

class KeyboardShortcut extends StatefulWidget {
  @override
  _KeyboardShortcutState createState() => _KeyboardShortcutState();
}

class _KeyboardShortcutState extends State<KeyboardShortcut> {
  int pressed;

  @override
  void initState() {
    super.initState();
    pressed = 0;
    const LogicalKeyboardKey uppercaseN =
        LogicalKeyboardKey(0x0000004e, keyLabel: 'N', debugName: 'Uppercase N');
    RawKeyboard.instance.addListener((RawKeyEvent event) {
      print('Received: $event');
      print('Keys Down: ${RawKeyboard.instance.keysPressed}');
      if (event.isKeyPressed(uppercaseN)) {
        print('Pressed Shortcut');
        setState(() {
          pressed += 1;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Center(child: Text('Pressed $pressed times.')));
  }
}


```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.138 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 620cd16cf0 (3 days ago), 2020-09-11 10:35:03 -0400
    • Engine revision a0bd862cc0
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by ardera** [comment]
> Second, the other platforms should always be producing 0x4e, and instead they are switching between that and 0x6e based on whether the shift key is pressed or not.

@gspencergoog I'm confused, doesn't the spec say it should always be lowercase and without modifiers (kinda redundant because shift is a modifier)? So it should always be producing a lowercase `n` == `0x6E`?

https://github.com/flutter/flutter/blob/b938dc13df32cd510844863a66856dd240dc3302/dev/tools/gen_keycodes/README.md?plain=1#L70-L72

**Comment by ardera** [comment]
ah you're right, thought I checked that.
