### ISSUE TITLE
[web] take screenshot in ios-safari unit tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#65670]
We are running screenshots unit tests only on Desktop Chrome for Flutter Web Engine.

We can take screenshots using `xcrun simctl io booted screenshot <name>` command, since simulator is already used for io-safari unit tests.

**Comment by MOPineyro** [comment]
@nturgut any guidance on actually getting tests running on ios safari and setting up web installers on CI?

**Comment by nturgut** [comment]
For flutter/engine, these tests are running on ios-safari on LUCI now, when I'm testing with `led`. After my changes merge you can see them on LUCI dashboard. (The changes for recipes go to this repo instead: https://flutter.googlesource.com/recipes/)

For web_installers repo we haven't add LUCI yet. There are instructions but as most recipe development work they need Google credentials. Are you willing to work on LUCI recipe's I think there is a way we can extend credentials to you?

**Comment by nturgut** [comment]
Btw, not that these are [web engine unit tests](https://github.com/flutter/engine/tree/master/lib/web_ui/test). These are different from the unit tests running on flutter/flutter.
