### ISSUE TITLE
Extend the document for updating browsers/drivers

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#65672]
We are using multiple browsers, browser drivers and ios-simulator for running unit/integration tests on the Flutter Web engine.

I added documentation for how to update Chrome version to felt [README](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md#upgrade-browser-version) file. This still needs missing parts such as information on ios-simulator.

**Comment by yjbanov** [comment]
IOS simulator is gone.
