### ISSUE TITLE
I don't get Flutter running.

### ISSUE THREAD

**Issue by xavierhxxs** [flutter/flutter#65684]
Hey Guys,

so I am new at programming and I have been trying to get Flutter on my MacBook 2020. Everything went well and when I type in "flutter doctor" it says erverything is fine except "Android toolchain - develop for Android devices: is partially installed;
    more components are available. (Android SDK version 30.0.2)3. ...". I don't want to program for Android so I think its not a problem. I am following the steps on the flutter website and I typed in "open -a Simulator" and it works well. It opens the simulator with the pre-build app. so I think that's right. But when I try to get the thing where the code for the pre-build App is written I can't find it. what do I have to do that I can get the thing where the code is too? (I am from Germany so maybe my English is not that good.) If there is somebody who wants to help me you can add me on discord and I can screen share  maybe dann its easier to help. 
Discord: xAvIeR#9362

thx for helping

**Comment by Dhruv-Sachdev1313** [comment]
hello @xavierhxxs 
"But when I try to get the thing where the code for the pre-build App is written I can't find it."
Can you explain what 'thing' are you taking about here ??
thankyou

**Comment by iapicca** [comment]
@xavierhxxs 
this repo is meant meant to improve flutter with bug report or feature request
if you need assistance for you personal code or installation please as a question on stackoverflow.com
as for the `I want help writing my application` choice in the [New Issue](https://github.com/flutter/flutter/issues/new/choose) selection

since you have a discord account you may want to  ask help in [Flutter's discord server](https://discord.gg/N7Yshp4)

**Comment by xavierhxxs** [comment]
> @xavierhxxs
> this repo is meant meant to improve flutter with bug report or feature request
> if you need assistance for you personal code or installation please as a question on stackoverflow.com
> as for the `I want help writing my application` choice in the [New Issue](https://github.com/flutter/flutter/issues/new/choose) selection
> 
> since you have a discord account you may want to ask help in [Flutter's discord server](https://discord.gg/N7Yshp4)

k  i am sry

**Comment by xavierhxxs** [comment]
> hello @xavierhxxs
> "But when I try to get the thing where the code for the pre-build App is written I can't find it."
> Can you explain what 'thing' are you taking about here ??
> thankyou

just the place where you write Code. I know how to get the simulator running but I don't have the place to see the code of the pre-build app

**Comment by erickzanardo** [comment]
Like iapicca mentioned, questions and doubts like this can do better on other places.

In addition to the suggestions already mentioned here for where you could get help, I suggest you taking a look on this link https://flutter.dev/docs#new-to-flutter

Closing this for now, but if you find that the documentation is not clear enough, feel free to comment here, or reopen this issue.

Thanks
