### ISSUE TITLE
I want to 

### ISSUE THREAD

**Issue by godalming123** [flutter/flutter#65682]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
I am trying to make a search entry visible if it is focused and there is text in it however I cannot find a n and statement
my code is:
opacity: focusedMemoryEntry and TextController.text != "" ? 1.0, 0.0

**Comment by iapicca** [comment]
@godalming123 
your issue doesn't seem to point to a bug within flutter or its plugin or a feature request.

for assistance on your code the best approach is to ask a question on stackoverflow.com
as selecting `I want help writing my application`  from the [New Issue](https://github.com/flutter/flutter/issues/new/choose) selection

**Comment by PixelToast** [comment]
The Github issue tracker is for bugs and features requests, you are more likely to get help with code questions in [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or one of the other communities at https://flutter.dev/community
