### ISSUE TITLE
Image picker for Flutter not opening gallery in app release

### ISSUE THREAD

**Issue by pythonhubpy** [flutter/flutter#65685]
I have made a simple image picker app. The app works fine and shows my gallery when I install it in my mobile in debug mode with android studio. 

But when I create a release apk with the help of "flutter build apk" there are no errors but when I try to open my gallery from the app for picking images it asks for permission to access my storage once given allow noting happens it still remains in the same screen.
 
The app is not crashing but it is not showing the gallery. 

Please help me solve this issue.

Thanks in advance.

**Comment by Abhishek01039** [comment]
Hi @pythonhubpy 
can you please try with `flutter run --release -v` and send the logs when you are opening a gallery or camera?
and also provide the `flutter doctor -v`.
Thanks.

**Comment by pythonhubpy** [comment]
> Hi @pythonhubpy
> can you please try with `flutter run --release -v` and send the logs when you are opening a gallery or camera?
> and also provide the `flutter doctor -v`.
> Thanks.

No, it is working with flutter run --release but its  is not working when I try `flutter build apk`

**Comment by erickzanardo** [comment]
@pythonhubpy please post the result of your `flutter doctor -v`. It will also help if you share which version of the Android you are testing.

Also, depending on the version of the Android, you will need to set up the correct permissions on your AndroidManifest.xml for this to work.

Thanks

**Comment by pythonhubpy** [comment]
`[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.20.3 at C:\flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\vetri\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`


This is the result of 'flutter doctor -v`.

I am using android to. My device is Redmi Note 9 Pro Max.

**Comment by markusaksli-nc** [comment]
I can't reproduce this on stable `1.20.3` with the latest `image_picker: ^0.6.7+7` using the basic image picker example.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.3 at C:\Development\flutter_stable
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64 • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86   • Android 11 (API 30) (emulator)

• No issues found!
```
</details>
<details>
 <summary>Minimal code sample</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.camera);

    setState(() {
      _image = File(pickedFile.path);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}
```
</details>

@pythonhubpy could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) using the latest version of `image_picker`?

**Comment by pythonhubpy** [comment]
This minimal code is working fine.

**Comment by berrylawchingman** [comment]
❤️

**Comment by BadalAc** [comment]
I am the same issue running on release mode but stuck on build apk
