### ISSUE TITLE
Error on changing ThemeData.dark() on onPressed()

### ISSUE THREAD

**Issue by MoeKyawOo** [flutter/flutter#65691]

**Comment by Abhishek01039** [comment]
Hi @MoeKyawOo 
can you please provide `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
