### ISSUE TITLE
flutter doctor finds device  and flutter run doesn't 

### ISSUE THREAD

**Issue by ikramooe** [flutter/flutter#65694]
Hello  , 
i'm using flutter with vscode and genymotion   when i try to run my app  using flutter run i get no device available but the device does show up in vscode and in flutter doctor

ANY SOLUTION !! 

![Capture](https://user-images.githubusercontent.com/31781110/93001718-71d1d100-f531-11ea-8772-296e8eb3428d.PNG)

**Comment by Abhishek01039** [comment]
Hi @ikramooe 
can you please solve the `Android SDK file not found` error by downloading it or setting the path of it?
Thanks.

**Comment by ikramooe** [comment]
i did set  the path  to ANDROID_HOME  but still not recognized by flutter 
however i don't think  that it's causing the issue since flutter doctor finds the connected device 

![image](https://user-images.githubusercontent.com/31781110/93002017-e60d7400-f533-11ea-8d78-d80d0474272a.png)

**Comment by erickzanardo** [comment]
@ikramooe can you confirm if you have the platform 28 installed?

For example, this is how the sdk manager would look if you have:
<img width="1027" alt="Screen Shot 2020-09-12 at 15 47 57" src="https://user-images.githubusercontent.com/835641/93002627-ba2bc780-f50e-11ea-8b23-af1cddbecdc8.png">

**Comment by jonahwilliams** [comment]
`flutter doctor -v` will show more information on the device. Its possible that it is not usable due to the missing android SDK

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
