### ISSUE TITLE
Pigeon App: The specified language version is too high

### ISSUE THREAD

**Issue by madatr** [flutter/flutter#65692]
Hello,

I have been trying to use the Pigeon plugin but when I try to invoke it using:  **flutter pub run pigeon**  it results in a list of errors from multiple files all quoting: The specified language version is too high

Here are the error codes:

`flutter pub run pigeon \
  --input pigeons/message.dart \
  --dart_out lib/pigeon.dart \
  --java_out ./android/app/src/main/java/com/example/merchant/Pigeon.java \
  --java_package "com.example.merchant"
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/path.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/context.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/style.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/path_exception.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/path_map.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/path_set.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/characters.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/internal_style.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/parsed_path.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file
^
../../../SW/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety/lib/src/style/posix.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.9.
// Copyright (c) 2013, the Dart project authors.  Please see the AUTHORS file`

Please Help,

Thanks

**Comment by hamdikahloun** [comment]
Hi @madatr 
Master channel come with Dart SDK 2.10 so I guess it's not supported.
Can you provide please your `flutter doctor -v`

> The highest supported language version is 2.9.

**Comment by madatr** [comment]
Hi @hamdikahloun 
I was on the beta channel but I thought it was too far ahead so I switched back to master. Here is the flutter doctor output:

`[✓] Flutter (Channel master, 1.22.0-10.0.pre.153, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.153 at /Users/matrouz/Desktop/Projects/bus_proj/bus_project_lite/SW/flutter
    • Framework revision 2e643651a9 (19 hours ago), 2020-09-11 23:07:03 -0400
    • Engine revision 16b900b63e
    • Dart version 2.10.0 (build 2.10.0-117.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/matrouz/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)`

I don't know how to downgrade flutter, can you please tell me how to?

**Comment by hamdikahloun** [comment]
Beta channel too come with Dart SDK 2.10.
You can switch to stable channel.

`flutter channel`
`flutter upgrade`

> • Dart version 2.10.0 (build 2.10.0-117.0.dev)

**Comment by madatr** [comment]
Sorry, i didn't make myself clear.

I have switched to the master flutter channel, how can i downgrade **Dart SDK** to 2.09 so I can test out Pigeon
Thanks,

**Comment by hamdikahloun** [comment]
Master channel support Dart SDK 2.10 . You can't downgrade to 2.9, the only way it's switch to stable channel.

**Comment by madatr** [comment]
I see, I guess I must wait until there is support in Pigeon App for Dart SDK 2.10

**Comment by hamdikahloun** [comment]
If. The issue it's solved you can close it please

**Comment by madatr** [comment]
yep, thanks

**Comment by Byron94odhiambo** [comment]
> Hi @hamdikahloun
> I was on the beta channel but I thought it was too far ahead so I switched back to master. Here is the flutter doctor output:
> 
> `[✓] Flutter (Channel master, 1.22.0-10.0.pre.153, on Mac OS X 10.15.6 19G73, locale en-GB)
> • Flutter version 1.22.0-10.0.pre.153 at /Users/matrouz/Desktop/Projects/bus_proj/bus_project_lite/SW/flutter
> • Framework revision [2e64365](https://github.com/flutter/flutter/commit/2e643651a99102927ddb64443d8d6de0589cfdf3) (19 hours ago), 2020-09-11 23:07:03 -0400
> • Engine revision [16b900b](https://github.com/flutter/flutter/commit/16b900b63e27e4f876bfbaf88140d2d0521fe692)
> • Dart version 2.10.0 (build 2.10.0-117.0.dev)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at /Users/matrouz/Library/Android/sdk
> • Platform android-29, build-tools 29.0.3
> • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Android Studio (version 3.6)
> • Android Studio at /Applications/Android Studio.app/Contents
> • Flutter plugin version 45.1.1
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)`
> 
> I don't know how to downgrade flutter, can you please tell me how to?

>flutter downgrade!!!
