### ISSUE TITLE
Where did the APK get generated?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#657]
After running `flutter apk`, this is what I saw:

```
~/flutter/myapp $ flutter apk
Downloading darwin-x64 artifacts from the cloud, one moment please...
~/flutter/myapp $
```

I don't know if it succeed, and if it did, where did it put my file? :)

Can we add something like:

```
APK generated: path_to_apk
```

?

Thanks!

**Comment by sethladd** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/pull/660
