### ISSUE TITLE
LazyBlockBuilder has incorrect autocomplete information

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#6570]
## Steps to Reproduce

In IntelliJ when using LazyBlockBuilder you get the totally wrong information for its constructor.

<img width="629" alt="screen shot 2016-10-28 at 12 14 52 am" src="https://cloud.githubusercontent.com/assets/253700/19787562/ab6b6a06-9ca3-11e6-9232-fb91d500f6bc.png">

when in fact the constructor actually is IndexWidgetBuilder, int totalExtentEstimator

https://docs.flutter.io/flutter/material/LazyBlockBuilder-class.html

<img width="514" alt="screen shot 2016-10-28 at 12 14 57 am" src="https://cloud.githubusercontent.com/assets/253700/19787632/1745976a-9ca4-11e6-9190-73006ee1fd16.png">

Actually I think it's so messed up that I can't even use the class since analyzer says the arguments are invalid.

## Flutter Doctor

Paste the output of running `flutter doctor` here.
```

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision 949e27ae8f (18 hours ago), 2016-10-26 19:11:55
    • Engine revision 7e5d63513a
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-N, build-tools 24.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • iPhone 6 • AB99FA55-DC63-4011-AF53-40AAC2C798F2 • ios (simulator)

```

**Comment by abarth** [comment]
I think it might just be expanding the typedefs in a confusing way.

**Comment by eseidelGoogle** [comment]
This is presumably an analyzer issue.  @devoncarew @jwren

**Comment by sethladd** [comment]
This issue was moved to flutter/flutter-intellij#388
