### ISSUE TITLE
Flutter iOS build large size

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#65718]
## Details

I'm curious if removing unused plugins that was previously added in the Flutter project will reduce the project's size and IPA build. Once a plugin has been added to the Flutter project, removing the plugin doesn't make the project back to its "original" size. Not really a complaint, but I can't find this documented somewhere. If can someone point it out, or have it documented, it'll really help.

**Steps to reproduce**
I've generated IPAs using five (5) builds. The Flutter project used is the sample 'flutter_app' created using Android Studio.

1. No plugins added in the Flutter project
2. [google_maps_flutter plugin](https://pub.dev/packages/google_maps_flutter) added
3. google_maps_flutter removed after being added
4. google_maps_flutter removed after being added, and manually deleted Pods
5. google_maps_flutter removed after being added, manually deleted Pods, and cleared {YOUR_APP}/build/

Running `flutter build ios` to create a release build on (3) throws an error that the project isn't sync with Podfile.lock and prompts me to manually run a `pod install`

Xcode Archive sizes didn't really change that much even after removing the plugin added.
![image](https://user-images.githubusercontent.com/4143153/93016348-149e5400-f5f3-11ea-920f-c41ffb51077b.png)

Here are the sizes of the IPAs:
![image](https://user-images.githubusercontent.com/4143153/93016369-34ce1300-f5f3-11ea-8b30-523f697ae03e.png)

Build 1: 22.7 MB
Build 2: 194.2 MB
Build 3: 188.5 MB 
Build 4: 188.5 MB 
Build 5: 188.5 MB 

In the end, removing the plugin used doesn't seem to have much of an impact reducing the project's size. I was expecting that removing the plugin added will reduce the IPA's size back to 22.7 MB

**Target Platform:** iOS
**Target OS version/browser:** iOS 13
**Devices:** N/A

## Logs

flutter analyze
```
Analyzing flutter_app...                                                
No issues found! (ran in 1.8s)
```

flutter doctor -v
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-PH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.0)
[✓] Connected device (2 available)

• No issues found!
omarmatthew-macbookpro:flutter_app omarmatthew$ /Users/omarmatthew/Downloads/flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-PH)
    • Flutter version 1.20.3 at /Users/omarmatthew/Downloads/flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/omarmatthew/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xs (mobile)           • 82CF4677-9933-4698-AD5C-823D6E93F283 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by saadmohmed** [comment]
this  will be create

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/47101#issuecomment-567522077
https://github.com/flutter/flutter/issues/50850
https://github.com/flutter/flutter/issues/54440

**Comment by TahaTesser** [comment]
Hi @omatt 
Here on the latest `master` channel, I see the IPA size back to a smaller size when reproducing `google_maps_flutter` , deleting pods, build folder, and pod install 

Default app with no package 

<img width="595" alt="Screenshot 2020-09-14 at 4 15 19 PM" src="https://user-images.githubusercontent.com/48603081/93076958-c8601c00-f6a5-11ea-9dd9-7f061e10151c.png">

Default app with `google_maps_flutter`
<img width="805" alt="Screenshot 2020-09-14 at 4 15 41 PM" src="https://user-images.githubusercontent.com/48603081/93077003-d9109200-f6a5-11ea-816f-8789ada3b5bc.png">

Default app with no package  again after removing everything 
<img width="823" alt="Screenshot 2020-09-14 at 4 15 54 PM" src="https://user-images.githubusercontent.com/48603081/93077033-e463bd80-f6a5-11ea-917c-c544868b4a4d.png">


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.138 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 620cd16cf0 (3 days ago), 2020-09-11 10:35:03 -0400
    • Engine revision a0bd862cc0
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.7
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.102

• No issues found!
```

</details> 


Can you please confirm this with new project with `google_maps_flutter`. Do you just have `google_maps_flutter` or other packages? Can you try on the latest mster

**Comment by omatt** [comment]
How were you able to manage the ipa size to be small? I tried creating an app through Android Studio and the behavior I encountered is still the same. What I noticed, however, is that the "original" size is now 188.5 MB after adding and removing packages. I'm unable to get back to 22.7 MB ipa size again.

How I created the sample flutter_app:

**Android Studio**
New Flutter Project > Flutter Application

AndroidX artifacts is enabled, with support for both Kotlin and Swift
<img width="322" alt="Screen Shot 2020-09-15 at 12 10 47 AM" src="https://user-images.githubusercontent.com/4143153/93110489-f8301380-f6e7-11ea-84ff-2148a1b71f31.png">

main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```

pubspec.yaml (without google_maps_flutter ^0.5.32)
```yaml
name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^0.5.32

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

```

**Comment by xster** [comment]
Please see https://flutter.dev/docs/perf/app-size

**Comment by TahaTesser** [comment]
Hi @omatt 
As mentioned above, please check out https://flutter.dev/docs/perf/app-size#ios and  https://flutter.dev/docs/perf/app-size#reducing-app-size

**Comment by omatt** [comment]
What I noticed now is that the "original" size is now 188.5 MB after adding and removing packages. I'm unable to get back to 22.7 MB ipa size again. Could you confirm if this is an intended behavior?

**Comment by TahaTesser** [comment]
Hi @omatt 
.ipa being that large is normal, it doesn't represent an actual app size. You can create an app size report to get more precise details https://flutter.dev/docs/perf/app-size#ios. Can you post the results of your  App Thinning Size Report 
Thank you

**Comment by omatt** [comment]
Gotcha. Thanks for the feedback.

**Comment by omatt** [comment]
I'll just add more details in this thread regarding my findings with app thinning. It looks like Xcode Archives won't return to its "original" size (212.7 MB) again. On the other hand, the ipa size should go back to its "original" size with app thinning. 

It's likely that the Archive still contain Bitcode sections, which explains its size. I'm unsure if this is its behavior by default and something Flutter can't change.
![image](https://user-images.githubusercontent.com/4143153/93531416-caf69600-f971-11ea-9988-4aa00e5bebb1.png)

#### Google Maps plugin used is `google_maps_flutter: 0.5.32`
Build 1: 19.6 MB (without Bitcode rebuild) pre-gmap plugin
Build 2: 21.2 MB (with Bitcode rebuild) gmap plugin added
Build 3: 15.4 MB (with Bitcode rebuild) gmap plugin removed
Build 4: 21.2 MB (with Bitcode rebuild) gmap plugin added again - I'm trying to see if there will be any changes
Build 5.1: 15.4 MB (with Bitcode rebuild) gmap plugin removed again
Build 5.2: 19.6 MB (without Bitcode rebuild) used the same Archive as Build 5.1, no gmap plugin added 

#### Rebuild from Bitcode' seems to be only available starting from the second Archive. 

First Archive - Bitcode rebuild isn't present
![image](https://user-images.githubusercontent.com/4143153/93531522-f5e0ea00-f971-11ea-9b02-928481a036af.png)

Second Archive - Bitcode rebuild is now present going forward
![image](https://user-images.githubusercontent.com/4143153/93531578-0729f680-f972-11ea-9ccb-f6750bf5354a.png)

**Comment by jmagman** [comment]
@omatt 
This may be https://github.com/flutter/flutter/issues/11819.  Also, maybe the Swift runtime is being embedded the first time a Swift plugin is added, but it's not being cleaned out after?
Can you attach one of the ipa bundles where you would expect no plugins included?  I'll crack it open and see what frameworks are actually being embedded.

**Comment by omatt** [comment]
The size of the ipa is as expected in my findings. `Build 5.2` has the same size as `Build 1` - both has Bitcode rebuild disabled. The reason why `Build 3` and `Build 1` has different sizes despite both of them having no plugins added is because Bitcode rebuild isn't available on `Build 1`.

On the other hand,  Xcode archive size doesn't go back to its original 212.7 MB ([as pictured](https://github.com/flutter/flutter/issues/65718#issuecomment-694517869)). Let me know if the ipa bundles that you've requested is the Xcode archives so I can share them.
