### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled.  Command: /usr/bin/xcodebuild -list

### ISSUE THREAD

**Issue by Paras-Chodavadiya** [flutter/flutter#65715]
## Command
```
flutter build ios --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: /usr/bin/xcodebuild -list
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:389:50)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:108:78)
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:83:43)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.17.5 at /Users/macbook/FlutterLib/flutter
    • Framework revision 8af6b2f038 (2 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1675E3E6-08BE-44D4-842A-58662EE1F6DD • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
agora_rtc_engine-1.0.6
app_settings-3.0.1
cloud_firestore-0.12.9
esys_flutter_share-1.0.2
firebase_admob-0.9.0+9
firebase_auth-0.11.1+12
firebase_core-0.4.0+9
firebase_crashlytics-0.1.2+2
firebase_messaging-6.0.1
firebase_storage-3.0.5
flutter_country_picker-0.1.6
flutter_email_sender-2.2.2
flutter_read_more_text-0.0.1
flutter_share_me-0.8.0
flutter_video_compress-0.3.7+8
fluttertoast-3.1.3
geolocator-5.1.3
google_api_availability-2.0.1
google_maps_flutter-0.5.21+3
image_cropper-1.1.2
image_downloader-0.19.1
image_picker-0.6.1+3
keyboard_visibility-0.5.6
local_auth-0.4.0+1
location-2.4.0
location_permissions-2.0.2
path_provider-1.3.0
permission_handler-4.3.0
photo_manager-0.3.5
screen-0.0.5
shared_preferences-0.5.3+4
social_share_plugin-0.2.0
sqflite-1.1.6+4
url_launcher-5.1.2
video_player-0.10.4+1
webview_flutter-0.3.17

**Comment by Abhishek01039** [comment]
Hi @Paras-Chodavadiya 
you are using the old flutter version 
can you please try with the latest version?
Thanks.

**Comment by pedromassangocode** [comment]
Hi @Paras-Chodavadiya 
I see there's an open issue [here](https://github.com/flutter/flutter/issues/57083) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
