### ISSUE TITLE
ListView make DecoratedBox overflow SizedBox area.

### ISSUE THREAD

**Issue by thangvip4321** [flutter/flutter#65722]
```dart
import 'package:flutter/material.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //var size = MediaQuery.of(context).size;
    return MaterialApp(home: Builder(builder: (_) {
      var size = MediaQuery.of(_).size;

      return Scaffold(
        body: ListView(children: [
          SizedBox(
            width: size.width * 0.8,
            height: size.height * 0.2,
            child: DecoratedBox(decoration: BoxDecoration(color: Colors.red)),
          ),
        ]),
      );
    }));
  }
}

void main() {
  runApp(
    new MyApp(),
  );
}
```
i expect the red box to be 4/5 of the screen width wide. But it seems like the box spanned the entire screen width. ( Sorry for my bad English).

Is this a bug, or there are workaround to constrain the box size?
I am currently using Flutter 1.20.3.

**Comment by Calamity210** [comment]
That behavior is intended, a `ListView`'s children are required to fill on the cross axis.

That being said, you can work around it by wrapping the sized box in an `Align`.

**Comment by darshankawar** [comment]
@thangvip4321,
Please check @Calamity210 solution and see if it resolves your issue.
Thanks.

**Comment by thangvip4321** [comment]
oh i forgot to close it. Yes @Calamity210 solution did solve my issue.
