### ISSUE TITLE
Telecom Providers

### ISSUE THREAD

**Issue by siddzankat** [flutter/flutter#65721]
## Proposal

Add the ability to retrieve telecom providers' names.

**Comment by iapicca** [comment]
to get the ISP you have to :

1. get the [IP address](https://stackoverflow.com/questions/52411168/how-to-get-device-ip-in-dart-flutter)
2. connect to an [API](https://www.google.com/search?q=best+api+for+get+isp+from+ip+a&oq=best+api+for+get+isp+from+ip+a&aqs=chrome..69i57j33.9872j0j7&sourceid=chrome&ie=UTF-8) using the `IP address ` to retrieve the ISP

I don't believe there's much to do for flutter's team here

**Comment by iqbalmineraltown** [comment]
I'm quite sure this could be achieved with method call on the native side
but I don't see why this should be integrated with flutter library

You always can find (or create) plugin for this

**Comment by pedromassangocode** [comment]
Hi @siddzankat 
As suggested in the comments above, you can easily achieve this by creating a plugin using Platform Channels. This does not seems to be a valid proposal for something that should be added into the core of Flutter.

Closing as invalid proposal for Flutter.
