### ISSUE TITLE
Coverage results are different on Linux VM and Linux container using Docker

### ISSUE THREAD

**Issue by SuTran** [flutter/flutter#65738]
I have a repo that generate different result for coverage when running on Mac and Linux
Here is the repo: https://github.com/SuTran/flutter_coverage_03

On Mac:

- `flutter doctor` returns `Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale en-VN)`
- `flutter test --coverage` returns `lines......: 34.8% (8 of 23 lines)`

On Linux

- docker image repo: https://github.com/SuTran/docker-flutter-coverage
- `flutter doctor` returns `Flutter (Channel unknown, 1.20.3, on Linux, locale en_US)`
- `flutter test --coverage` return `lines......: 21.1% (4 of 19 lines)`
- Below are the command to generate coverage with the images
```
docker run --rm \
  -v "$(pwd):/src/" \
  sutran/flutter-coverage \
  bash -c "cd /src/ && flutter pub get && flutter test --coverage"
```

**Comment by TahaTesser** [comment]
Hi @SuTran 
I just tried https://github.com/SuTran/flutter_coverage_03 on both Linux and  Mac, results are identical 


[linux_coverage.zip](https://github.com/flutter/flutter/files/5217809/linux_coverage.zip)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.3 at /home/taha/Code/flutter_stable
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

</details>

**Comment by SuTran** [comment]
Hi @TahaTesser ,

Thanks for your response. Why couldn't you run on docker? Can you share with me the issue? Also can you share any Dockerfile from your side using PopOS?

I think the context of having Docker here is really important. Some developers develop Flutter on their Mac and having CI/CD setup run on Docker so they will expect the result to be the same

I also updated the title to narrow down the issue here

**Comment by TahaTesser** [comment]
Hi @SuTran 
Have you tried running on normal Linux distro without docker? Does it also reproduce different results?

**Comment by SuTran** [comment]
Hi @TahaTesser,


Below are the results between Linux distro and Linux on docker

### On Linux VM

<details>
  <summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor
-v):
[✓] Flutter (Channel unknown, 1.20.3, on Linux, locale
    C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing
      the Android SDK components.
      (or visit
      https://flutter.dev/docs/get-started/install/linux
      #android-setup for detailed instructions).
      If the Android SDK has been installed to a custom
      location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH
      environment variable.

[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

</details>

<details>
  <summary>lsb_release -a</summary>

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

</details>

Coverage results:
```
Overall coverage rate:
  lines......: 34.8% (8 of 23 lines)
```

### On Linux using Docker

Docker file: https://github.com/SuTran/ubuntu_flutter_build_do/blob/master/Dockerfile

<details>
  <summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.20.3, on Linux, locale en_US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

</details>

Coverage results:
```
Overall coverage rate:
  lines......: 21.1% (4 of 19 lines)
```

For the above VM and the docker image, they both use `Ubuntu 20.04`, same softwares and steps to install, and having different coverage result. Do you have any idea about the different?

**Comment by jmagman** [comment]
@jonahwilliams This should move to dart-sdk, right?  Know who to ping?

**Comment by jonahwilliams** [comment]
@SuTran could you upload the coverage files that get generated?

**Comment by SuTran** [comment]
Hi @jonahwilliams . Here are the coverage files
[coverage_linux_docker.zip](https://github.com/flutter/flutter/files/5286051/coverage_linux_docker.zip)
[coverage_mac.zip](https://github.com/flutter/flutter/files/5286052/coverage_mac.zip)

**Comment by eliasyishak** [comment]
@SuTran thank you for your issue, however, this seems to be a bug that is a result of `package:coverage`, here is a link to their [repo and issue tracker](https://github.com/dart-lang/coverage/issues) if you want to file it there
