### ISSUE TITLE
Some tasks failing repeatedly with "application-identifier entitlement does not match" error

### ISSUE THREAD

**Issue by flar** [flutter/flutter#65734]
I'm seeing the following error in logs of failed tasks (for example `complex_layout_ios__start_up`), but the tasks will eventually run if you use the Rerun button. It seems to have runs that affect some hosts and not others, but sometimes the hosts can recover from this state and start passing these same tests on later runs (perhaps someone rebooted the host behind the scenes and I didn't notice).  The error is:

```
stdout: [        ] [ 65%] InstallingEmbeddedProfile
stdout: [        ] [ 70%] VerifyingApplication
2020-09-11T19:37:51.239257: stderr: [ +168 ms] 2020-09-11 19:37:51.237 ios-deploy[73730:44281811] [ !! ] Error 0xe80000be: This application's application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```

At the time I first noticed this, it seemed that mac6 was doing this frequently, but just checking today, mac6 succeeded on this same task after mac12 had issues with it.

I would include a pointer to a specific log, but the Download Logs button does not expose a URL - clicking it goes directly to a download dialog. If you scan the column for `complex_layout_ios__start_up` from about commit 4f62680809607eda5fec4606acff8a214a51644d to several commits before that you will see a lot of yellow "rerun" boxes that show the error a few times.

**Comment by gspencergoog** [comment]
`complex_layout_ios__start_up` is now failing repeatedly (it has run seven times and not succeeded), so I'm going to deem this as blocking the build, and bump this to P0.

I'm not sure if all the failures are associated with the "application-identifier entitlement", but it is a place to start, as it does seem to happen a lot.

**Comment by godofredoc** [comment]
Looks like all the mac machines have been failing randomly. Will reboot all of them to get them to a good initial state to debug better.

**Comment by godofredoc** [comment]
All the machines have been restarted and agent code updated. Please let me know if the problem persists

**Comment by godofredoc** [comment]
The test keeps failing. I don't think this is an infrastructure issue:

```
2020-09-14T12:48:21.883825: INFO [task runner] [complex_layout_ios__start_up] stdout: [   +8 ms] Fail to connect to service protocol: http://127.0.0.1:49443/: HttpException: , uri = http://127.0.0.1:49443/ws

2020-09-14T12:48:21.883975: INFO [task runner] [complex_layout_ios__start_up] stderr: [        ] failed to connect to http://127.0.0.1:49443/

2020-09-14T12:48:21.885816: INFO [task runner] [complex_layout_ios__start_up] stdout: [   +1 ms] "flutter run" took 72,326ms.

2020-09-14T12:48:21.889241: INFO [task runner] [complex_layout_ios__start_up] stderr: [   +3 ms]
```

**Comment by jmagman** [comment]
@godofredoc That would be a different cause than `application-identifier entitlement does not match`. Are there other tests flaking with that message?  I don't see any just downloading random logs, can it be queried?

`platform_views_layout_hybrid_composition` and `platform_views_layout` are reusing that bundle identifier, which they shouldn't be, though that would be benign if the apps are getting uninstalled after the test runs.

**Comment by jmagman** [comment]
> `platform_views_layout_hybrid_composition` and `platform_views_layout` are reusing that bundle identifier, which they shouldn't be, though that would be benign if the apps are getting uninstalled after the test runs.

Fixing in https://github.com/flutter/flutter/pull/65793, not convinced this is causing the issue though.

**Comment by jmagman** [comment]
`complex_layout_ios__start_up` passed on https://github.com/flutter/flutter/commit/7e41425d4af21dec7a7ff072a3ec1387859e32c8, downgrading this to a P2.  Will keep an eye on it on subsequent commits to see if it flakes again.

**Comment by godofredoc** [comment]
Moving this bug out of the ticket queue.

**Comment by jmagman** [comment]
Last test with this error message was 2020-09-13T23:20:17, which is before 7e41425 merged.  Closing for now, we can reopen for more investigation if it pops up again.
