### ISSUE TITLE
How can I change the Flutter default time selection widget text?

### ISSUE THREAD

**Issue by StatTark** [flutter/flutter#65732]
```
showTimePicker(
                            context: context,
                            initialTime:
                                TimeOfDay(hour: DateTime.now().hour, minute: DateTime.now().minute)),
```

![image](https://user-images.githubusercontent.com/33375656/93029133-bc327b00-f621-11ea-95e9-b453c9b8d85f.png)
How can I change the text in the cancel and ok button in the time picker?

**Comment by Calamity210** [comment]
`showTimePicker()` contains optional `cancelText` and `confirmText` parameters https://api.flutter.dev/flutter/material/showTimePicker.html

**Comment by StatTark** [comment]
@Calamity210  
![image](https://user-images.githubusercontent.com/33375656/93059249-1ca0d700-f679-11ea-9768-3c684fd8eb1c.png)
![image](https://user-images.githubusercontent.com/33375656/93059357-3e01c300-f679-11ea-98b9-b49dccd29ae9.png)

Why is it not coming out for me, could it be related to the dart version?

**Comment by pedromassangocode** [comment]
Hi @StatTark 
Could you please run `flutter upgrade --force`. 

Then you can use the optional strings for the `helpText`, `cancelText`, and `confirmText` to override the default values.

If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by StatTark** [comment]
@pedromassangocode 
![image](https://user-images.githubusercontent.com/33375656/93081766-74026f80-f698-11ea-8071-31abcac62f09.png)
How can I fix these errors in flutter doctor.

**Comment by pedromassangocode** [comment]
Hi @StatTark 
Are you able to change the default time selection text after upgrading Flutter?

**Comment by StatTark** [comment]
@pedromassango  yes 
I solved the errors with these commands.
**flutter pub cache repair**   **flutter clean** and  **flutter run**
