### ISSUE TITLE
Plugin don't work in Package

### ISSUE THREAD

**Issue by matteozero** [flutter/flutter#65749]
I create a Package write with dart, and create a Plugin to call ios or android method. 
in my package i call plugin method. then create a new flutter app project call package method . it's shows "Unhandled Exception: NoSuchMethodError",
if i call  Plugin method  in  flutter app project  directly,it works well. so how can i call a plugin method in a package?

**Comment by darshankawar** [comment]
Hi @matteozero,
This question is more suitable on StackOverflow. Also, please see https://flutter.dev/community for resources.
If you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
