### ISSUE TITLE
Touch events missing sound and haptic feedback on Android

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#6574]
On Android, tap events that have an associated click/tap action attached should provide feedback with a "click" sound and possibly vibration (in cases). 

There seems to be some provisions in `SystemSound` and `HapticFeedback` but they're not hooked up(?). 

I tested on an Android device + the emulator but neither work.

Sorry if this is work in progress.

**Comment by eseidelGoogle** [comment]
We definitely had a working HapticFeedback API at one point.  Possible we broke it.

It sounds like you're asking for our default widgets to be wired up to use haptic feedback?
@Hixie do you have any context here by chance?

**Comment by Hixie** [comment]
Some of our widgets definitely try to use haptic feedback. Not sure why it would have broken, maybe it used the old mojo system and it's broken in the new path? cc @abarth

**Comment by abarth** [comment]
When I did the migration, I didn't get the feedback in either case.  I figured I had muted it on my device somehow.  I suspect its an easy fix once we figure out where the wires are getting crossed.

**Comment by eseidelGoogle** [comment]
@cbracken just fixed iOS to not be wired up to vibrate in some of these cases.  It would be ironic if we had iOS properly wired up and Android not.

Putting this in milestone 4 for now.  Let us know if this is important sooner.  The plumbing is likely there but just broken:
https://github.com/flutter/engine/blob/ca6d4fdec88a6c0075657701651de288c0d7c910/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L47
is the method which should end up called.  It's also possible that we need to make more calls from the framework:
e.g.
https://github.com/flutter/flutter/blob/6d135e452032144b2d180a46004e1257f501cdd1/packages/flutter/lib/src/material/date_picker.dart#L608

**Comment by cbracken** [comment]
Confirmed that `DatePicker` and `TimePicker` are still emitting haptic feedback events on Android (but not on iOS). We've got tests for it on `TimePicker`; I'll add one for `DatePicker` as well. 

A quick grep through our source code shows that the two widgets above are the only Material widgets that currently provide haptic feedback. Other than that, I see `LongPressDraggable` from the `widgets` library. 

@lukef can you provide a bit more detail on specific cases where you're expecting feedback but aren't getting it? Are there particular cases that are priorities for you?

**Comment by lukef** [comment]
Some items (like DatePicker as you mentioned) will emit a click (Touch) sound AND a vibrate event. All other items that have an onClick event attached (RecyclerView items, AppBar buttons, regular buttons, etc) should emit a click sound. InputMethods (such as keyboard views) generally all just emit a haptic (vibration) event.

The click sound can be disabled in the system settings under _Sound -> Other Sounds -> Touch Sound_ on a stock Android device.

**Comment by cbracken** [comment]
Thanks @lukef. It's probably worth us giving the `HapticFeedback` class a bit of love as well. Right now we've only got a `vibrate` method, but both Android and iOS provide more nuanced APIs.

**Comment by eseidelGoogle** [comment]
@jason-simmons is our Android expert.  Perhaps he'd be wiling to take a crack at this?  (No huge rush, but this will be needed for completion of Posse's current app.)

**Comment by mravn-google** [comment]
(Just checking if I broke something with platform channel changes) My Android device responds correctly to `SystemSound.play(SystemSoundType.click)` and `HapticFeedback.vibrate()`, including ignoring them, if I change device settings. So the basic wiring seems to be present and working.

**Comment by lukef** [comment]
Not sure if you wanted further clarification. If not, ignore me :) The primary issue relates to the fact that Flutter doesn't respond natively with click sounds for things that Android does (e.g.: Button clicks, tab selection, etc). I feel like those should be out of the box.

**Comment by eseidelGoogle** [comment]
This is basically like our accessibility work.  We just have to turn on all the haptic feedback sounds, navigate around Java android apps for a while, navigate around a Flutter app, notice the differences and add the missing calls.

**Comment by Hixie** [comment]
Is there a list of where you want haptic feedback? I don't get much haptic feedback navigating around Android on my phone, but maybe I have it disabled or something, I'm not sure.

**Comment by eseidelGoogle** [comment]
I suspect we would need to build such a list by navigating ourselves (similar to what we've done with accessibility).  It's also possible the Android team may have such a list we could find?

**Comment by lukef** [comment]
The most noticeable haptic feedback issue is in regards to text selections. On Android they should have haptic feedback. Buttons should have "click" sounds. I suspect @eseidelGoogle is right that a list should be made. Happy to help.

**Comment by lukef** [comment]
The two most noticeable ones are:

1. Haptic (vibration) feedback on any long press operation - selection, long press on an item, invoking the contextual tool/action bar, etc. You can find an example by long pressing on a message in hangouts or selecting text anywhere

2. Click sounds on any tappable item. FABs, menu items, buttons, image buttons, etc. Flutter disables interaction for items with no tap handler (which is a variance) but i think thats ok.

Those are the two most prominent places.

**Comment by Hixie** [comment]
cc @goderbauer
