### ISSUE TITLE
flutter 1.17.5 打包apk后，无法将第三方引入的.so文件打入lib目录下

### ISSUE THREAD

**Issue by zQ4** [flutter/flutter#65741]
my flutter doctor
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2005, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

After I upgraded the flutter sdk from 1.12 to 1.17.5, I found that the third-party .so library introduced by Android gradle, built in debug mode, can be entered into the lib directory normally, but cannot be entered normally when packaged for release Go to the lib directory.

debug:
![image](https://user-images.githubusercontent.com/23376580/93036822-84542380-f673-11ea-857f-f7181ea01060.png)

release:
![image](https://user-images.githubusercontent.com/23376580/93036916-ba91a300-f673-11ea-8722-aca9e84b11ee.png)

thanks

**Comment by pedromassangocode** [comment]
Hi @zQ4 
The `1.17.5` is not the latest stable Flutter channel anymore.  Could you please run `flutter upgrade --force`.
 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
