### ISSUE TITLE
[in_app_purchase] Add currencyCode and priceNumber (as double) to ProductDetails

### ISSUE THREAD

**Issue by erf** [flutter/flutter#65758]
## Use case

Now `ProductDetails.price` is a string formatted in **USD**, which does not make much sense when you want to show the price formatted in local currency, as [described by Apple](https://developer.apple.com/documentation/storekit/in-app_purchase/offering_completing_and_restoring_in-app_purchases):

> To display the price of a product in the UI, use the locale and currency returned by the App Store. For instance, consider a user who is logged into the French App Store and their device uses the United States locale. When attempting to purchase a product, the App Store displays the product’s price in euros. Thus, converting and showing the product’s price in U.S. dollars to match the device’s locale in the UI would be incorrect.

## Proposal

I would suggest to show both **priceNumber** (as double) and **currencyCode** (as String) in `ProductDetails`. You have both items in the wrappers `skProduct` for iOS and `skuDetail` for Android. 

From `skProduct` you would need the `price` and `priceLocale.currencyCode`.

From `SkuDetail` you would need `priceAmountMicros` and `priceCurrencyCode`.

I think these are the most important and commonly used items from both. You would need to convert `price` and `priceAmountMicros` to a double value.

**Comment by erf** [comment]
Here is a `product_details_ext.dart` example extensions i made.

```
import 'package:in_app_purchase/in_app_purchase.dart';
import 'dart:io' show Platform;

extension ProductDetailsExt on ProductDetails {
  double get priceNumber {
    if (Platform.isIOS) {
      return double.tryParse(this.skProduct.price);
    }
    if (Platform.isAndroid) {
      return (this.skuDetail.priceAmountMicros / 1000000.0).toDouble();
    }
    throw Exception('Platform not supported');
  }

  String get currencyCode {
    if (Platform.isIOS) {
      return this.skProduct.priceLocale.currencyCode;
    }
    if (Platform.isAndroid) {
      return this.skuDetail.priceCurrencyCode;
    }
    throw Exception('Platform not supported');
  }
}
```

**Comment by cyanglaz** [comment]
fixed by https://github.com/flutter/plugins/pull/3794
