### ISSUE TITLE
Increasing UI and Raster thread priority on iOS

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#65752]
I was investigating some jank with flutter gallery (which in the end seems to be caused by text layout on home page) and while going through thread states I noticed that on occasion the raster thread gets preempted for a long time, sometimes in order of 100s of milliseconds (for example by location services).

To avoid this, Apple suggests [increasing thread priority and opting out of QoS](https://developer.apple.com/videos/play/wwdc2018/612/):

```cpp
r = pthread_attr_setschedpolicy(&attr, SCHED_RR); // Opt out of Quality of Service
struct sched_param param = {.sched_priority = 45}; // Configure priority 45
r = pthread_attr_setschedparam(&attr, &param); // Set priority
pthread_create(&posixThreadID, &attr, &PosixThreadMainRoutine, NULL); pthread_attr_destroy(&attr);
```

I think we should be able to achieve same effect on running thread using
```cpp
    struct sched_param param {
      .sched_priority = 45
    };
   pthread_setschedparam(pthread_self(), SCHED_RR, &param);
```

Perhaps this should be done for both UI and raster thread?

**Comment by knopp** [comment]
Looks like Chromium is actually [using priority of 50](https://chromium.googlesource.com/chromium/src/base/+/master/threading/platform_thread_mac.mm#174).
```cpp
case ThreadPriority::DISPLAY: {
   // Apple has suggested that insufficient priority may be the reason for
   // Metal shader compilation hangs. A priority of 50 is higher than user
   // input.
   // https://crbug.com/974219.
   [[NSThread currentThread] setThreadPriority:1.0];
   sched_param param;
   int policy;
   pthread_t thread = pthread_self();
   if (!pthread_getschedparam(thread, &policy, &param)) {
   param.sched_priority = 50;
   pthread_setschedparam(thread, policy, &param);
}
```

**Comment by chinmaygarde** [comment]
This looks very reasonable. We already set the thread priority in the Android Shell Holder. But, we definitely don't set the QoS on iOS. This needs to be consolidated.

**Comment by gaaclarke** [comment]
I took a little look at this quickly, just a heads up, there isn't a way to set thread priority with std::thread (which is what we use).  There is `pthread_setschedparam` for nix and [`SetThreadPriority`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreadpriority).  There is some nuances between operating systems too.

`pthread_attr_setschedpolicy` is used to opt of of qos.

https://stackoverflow.com/a/24939577

**Comment by knopp** [comment]
> I took a little look at this quickly, just a heads up, there isn't a way to set thread priority with std::thread (which is what we use). 

There isn't. But you can always call the following
```
 struct sched_param param {
      .sched_priority = 45
 };
 pthread_setschedparam(pthread_self(), SCHED_RR, &param);
```
on raster and UI thread on iOS, i.e. using `FlutterEnginePostCallbackOnAllNativeThreads`.

**Comment by liyuqian** [comment]
`pthread_setschedparam(pthread_self(), SCHED_RR, &param);` looks promising. I wonder how we can test this. For example, could we expect a significant improvement in rendering smoothness (e.g., average frame time, 90th frame time) of a simple Flutter animation that also has an intensive iOS background computation (https://flutter.dev/docs/development/packages-and-plugins/background-processes)?

**Comment by knopp** [comment]
I'm wondering if you're going to be able to consistently test this. I initially looked into this because when profiling I get the raster thread preempted for 300ms by `locationd`, but it was not something I could easily reproduce.

**Comment by dnfield** [comment]
We should be able to see improvements in GC related contention with this.

**Comment by mrcendre** [comment]
It sounds like it could prevent a fair amount of jank on iOS ! Any updates on this, @Hixie @knopp ?

**Comment by JsouLiang** [comment]
https://github.com/flutter/engine/pull/30605

**Comment by chinmaygarde** [comment]
Closing as completed in https://github.com/flutter/engine/pull/30605
