### ISSUE TITLE
Crash when AppLifecycleState.detached is called

### ISSUE THREAD

**Issue by leonardoayres** [flutter/flutter#65764]
When try to finish (calling stop() ) a component when in AppLifecycleState.detached state, the following error is shown:

**════════ Exception caught by widgets library ═══════════════════════════════════**
**The following assertion was thrown while finalizing the widget tree:**
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4182 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

**Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
**

It is important to mention that if i call the .stop() of the component while using the app normally, this kind of error does not crash the app.

Can you guys give some kind of insight about it?

**Comment by PixelToast** [comment]
@leonardoayres

Hi, could you provide a minimal reproducible example?
The assertion being thrown indicates something is calling markNeedsBuild (setState) on a widget that is no longer in the tree, which seem unrelated to the app lifecycle.

**Comment by leonardoayres** [comment]
@PixelToast thanks for the insight. There was the fact indeed; the was a setState being called on the function called on the detached state.

The component (BackgroundGeolocation) still does not stop, but the error is gone :-)

**Comment by darshankawar** [comment]
Hi @leonardoayres,
Since the error is gone, is it safe to close this issue ?
Thanks.

**Comment by leonardoayres** [comment]
Oh, sure! Sorry :-)

No problem at all.
