### ISSUE TITLE
webview_flutter plugin stops responding to touch events on Android

### ISSUE THREAD

**Issue by rpk98c** [flutter/flutter#65761]
When using 3rd party pano2vr JS library within the webview_flutter plugin touch events are not responded to after a touch and hold.

To replicate 

On Android:
 - load the following URL with webview_flutter ensuring JS is unrestricted. 
https://digital-marmoset-foc-tgw-pano.web.app/index-3.html
 - You should be able to pan the view. 
 - Touch and hold anywhere in the web view
 - Now try to pan and it is restricted or non-responsive to touch events. 

The same page in a pure Android app in a web view works without issue. 

Thanks,

Ryan

**Comment by TahaTesser** [comment]
Hi @rpk98c 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and `webview_flutter` version 
Thank you

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
