### ISSUE TITLE
Navigator 2.0 Remaining Work

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#65776]
- [x] Integrate Navigator 2.0 with the web engine (https://github.com/flutter/flutter/issues/64494), PR: https://github.com/flutter/engine/pull/20794
- [ ] Migrate the Stocks app as an example, _in progress_: https://github.com/flutter/flutter/pull/63424
- [x] Deep link support:
  - [x] iOS, https://github.com/flutter/flutter/issues/66294
  - [x] Android, https://github.com/flutter/flutter/issues/66148
- [ ] examples, codelabs, tutorials (https://github.com/flutter/flutter/issues/63429), _in progress_

**Punted:**

- Integrate Navigator 2.0 and state restoration for the web (https://github.com/flutter/flutter/issues/65777)
    - dependent on https://github.com/flutter/flutter/issues/62916
    - see https://github.com/flutter/flutter/issues/65776#issuecomment-692966605

**Comment by goderbauer** [comment]
In a discussion with @mdebbar, @yjbanov, and @chunhtai we decided to punt on #65777. We believe that if users really need to restore state, they can do so manually for now by adding stuff to the history entry (just like you can do in other web frameworks or native web as well, so this is not a regression in Flutter). If we receive feedback that people would like to see this done by the state restoration framework, we can revisit that decision and implement #65777 at a later point. At that point, we will also have to solve https://github.com/flutter/flutter/issues/33615.

**Comment by chunhtai** [comment]
Had a conversation with @johnpryan , Our currently plan is to post a blog post about how to use the router widget, and there is no plan to provide opinionated class at this time.

That means we will have a several code samples along with a tutorial blog post, and the stock app rewrite with the Router. @csells Is there anything else that is required to release the Router?

**Comment by orestesgaolin** [comment]
@chunhtai is the Router approach going to be the recommended one? What about simple Pages API approach where we would just provide a list of pages to the Navigator. Would you also describe this in the blog post as an alternative? From the discussions with folks after the meetup people seem to feel much more comfortable with just Pages API.

**Comment by chunhtai** [comment]
@orestesgaolin Yes we will recommend Router. In the case where developer only wants to use page API, we should make the Route information parsing in Router API optional. For example, something like this should work
```dart
import 'package:flutter/material.dart';
void main() {
  runApp(MaterialApp.router(routerDelegate: MyRouterDelegate(),));
}

class MyRouterDelegate extends RouterDelegate<void> with ChangeNotifier, PopNavigatorRouterDelegateMixin {
  @override
  GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
  @override
  Future<void> setNewRoutePath(void data) => Future<void>.value(null);

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      pages: <Page>[MaterialPage(builder: (BuildContext context) => Placeholder())],
      onPopPage: (_,__) =>false,
    );
  }
}
```

This is currently not working because the RouteInformationParser is a required parameter. We should probably update that.

**Comment by johnpryan** [comment]
@orestesgaolin The main reason to use Router is to handle routes from the host platform. If you just want to have declarative navigation, then using the pages API alone should work.
