### ISSUE TITLE
complex layout ios startup is very flaky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#65775]
It looks like it started flaking more heavily around https://github.com/flutter/flutter/commit/b3d1ebf117589c90a0fc09e76920dc80d92d4dc8

**Comment by Hixie** [comment]
I can't see the logs but I suspect my PR had no effect (or at best changed the timing such that an existing flake got tickled more). There's plenty of failures before as well, and the corresponding complex layout scroll perf benchmark is equally flaky.

I'll look more into this once I can see the logs.

**Comment by Hixie** [comment]
(Still can't see logs.)

**Comment by zanderso** [comment]
As the flakiness was reduced by https://github.com/flutter/flutter/commit/d5b715d7cbd60b0f2e6b25806360eb8d0e4c00a9, it appears this was related to the way that logs were read, rather than the tests themselves.
