### ISSUE TITLE
Fuck Flutter

### ISSUE THREAD

**Issue by youfeed** [flutter/flutter#65772]
Fuck you flutter, if macos adds PATH, it just won’t join, go to hell, you’re so ugly, Google is so big, will the script be configured to die?

**Comment by Abhishek01039** [comment]
Hey @youfeed 
can you please provide the details of what problem you are facing?
please send your `flutter run -v` and `flutter doctor -v` and minimal reproduction code?
Thanks

**Comment by Abhishek01039** [comment]
Flutter team is doing the great
Flutter is one of the most popular frameworks for making apps nowadays.
Flutter is so good and Thanks to the Flutter team for making the awesome framework.

**Comment by cbracken** [comment]
Hi @youfeed, I'd remind you that we require that all discussion on our issue tracker and mailing lists abide by our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).

It sounds like you've run into an issue with handling of `$PATH` on macOS, but it looks like you may have submitted this issue before filling out the issue template. If you're running into a reproducible issue I'd ask that you file a [new issue](https://github.com/flutter/flutter/issues/new/choose) and fill out the template with a clear statement of the issue you're running into and repro steps.
