### ISSUE TITLE
Support Flutter SDK paths with spaces

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#6577]
## Steps to Reproduce
1. Install the SDK in a path containing spaces. e.g., `/Users/someone/Google Drive/Development/dart/flutter-sdk`.
2. Run flutter doctor

``` bash
$ flutter doctor
...
/Users/someone/Google Drive/Development/dart/flutter-sdk/bin/flutter: line 50: $PROG_NAME: ambiguous redirect
```

**Comment by cbracken** [comment]
`flutter doctor` is now working. What's still left to do:
* Add quotes around the `xcode_backend.sh` path in the two build phases we call it in the project templates + all examples.
* A ton of quoting in `xcode_backend.sh` itself.
* `flutter run` on both Android and iOS
* probably more :)

**Comment by cbracken** [comment]
* `xcode_backend.sh` is cleaned up and `flutter build ios` now works.
* iOS Xcode project templates updated.

**Comment by cbracken** [comment]
There's also a bug in the engine (specifically in the Tonic loader) wherein `file://` URIs are not URI-decoded during conversion to filesystem paths. I'll put together a patch and send upstream.

**Comment by cbracken** [comment]
Note: dart-lang/sdk#30059 is a blocker for this.

**Comment by Hixie** [comment]
@bkonyi You did this right?

**Comment by cbracken** [comment]
Verified we handle spaces in SDK path, project path, and Android SDK path for:
[x] macOS: Android apps 
[ ] macOS: iOS apps 
[ ] Linux: Android apps
[ ] Windows: Android apps

**Comment by cbracken** [comment]
Also verified accents and emoji in paths on macOS.

**Comment by cbracken** [comment]
Follow-up work in progress:
- [ ] Update the bots to include a space in the SDK path
- [ ] Remove the doctor warning about spaces

**Comment by cbracken** [comment]
One more patch for `flutter_tester` landing in https://fuchsia-review.googlesource.com/c/topaz/+/121856

**Comment by cbracken** [comment]
This is now resolved. Travis/Appveyor are updated to run all tests in a flutter SDK directory named "flutter sdk".

**Comment by cbracken** [comment]
As an added bonus, we now also support any path that's a valid UTF-8 string.

**Comment by Hixie** [comment]
This patch had a minor regressive impact on the aot_snapshot size metrics.

**Comment by Hixie** [comment]
Please disregard my most recent comment.
