### ISSUE TITLE
Some high-end devices have bad ListView scrolling performance

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#65795]
Two known devices with such problem are Huawei mate 30 pro and honor 9 as noted in these comments [[1]], [[2]].

Notably, Huawei mate 30 pro is a 1-year-old $1000 flagship device which was reported to have poorer performance than a 7-year-old pixel 1.

[1]: https://github.com/flutter/flutter/issues/65224#issuecomment-689950384
[2]: https://github.com/flutter/flutter/issues/65224#issuecomment-691769569

**Comment by zanderso** [comment]
Assigning @liyuqian to obtain a device or devices that exhibits the issue.

**Comment by pedromassangocode** [comment]
Related to https://github.com/flutter/flutter/issues/31637 and https://github.com/flutter/flutter/issues/52207

**Comment by robert-bitguild** [comment]
Hey guys, 

Try to use  [flutter_list_view](https://pub.dev/packages/flutter_list_view)  package in pub.dev. It may resolve the scrolling or animate performance.

**Comment by zanderso** [comment]
Closing as presumed stale.
