### ISSUE TITLE
Failed assertion: 'textCapitalization != null': is not true.

### ISSUE THREAD

**Issue by AntonVTR** [flutter/flutter#65801]
I got this error when entering a name in the TextField and trying cahnge the focus to another field
` TextField(
                          controller: fullNameController,
                          textCapitalization: TextCapitalization.words)`

**Comment by darshankawar** [comment]
Hi @AntonVTR,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
