### ISSUE TITLE
Scaffold body does not appear in Safari 

### ISSUE THREAD

**Issue by realadeel** [flutter/flutter#65819]
I have one screen in an app that which does not appear (is black) in the Safari browser. It's the only screen in the app that does not appear. Plus, everywhere else (iOS, Android, other web browsers) this screen appears fine.
Since it's Safari I can't get the flutter run logs for it but here is basically the widget stack:

Scaffold body:
FutureBuilder
SafeArea
Center
AspectRatio
LayoutBuilder
Container
Stack
PageView.custom
RepaintBoundary
Stack

Also, the drawer for the scaffold works (can be swiped into view), just the body does not appear!
</details>

**Comment by TahaTesser** [comment]
Hi @realadeel 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by yjbanov** [comment]
Does this happen if you pass `--dart-define=FLUTTER_WEB_USE_SKIA=true`? (trying to understand which renderers are affected)

**Comment by realadeel** [comment]
Yes, the behavior is the same in both... body is black but the drawer of the scaffold still works. I'm working on an equivalent minimal app but it's a bit of a complex screen.

**Comment by TahaTesser** [comment]
Hi @realadeel 
Do you have the code sample, please? 
Thank you

**Comment by realadeel** [comment]
The latest beta build resolves this issue. My app now runs fully in Safari.
