### ISSUE TITLE
Release mode is slower than debug mode.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6581]
For my app, release mode is slower than debug mode.
![debug performance](https://cloud.githubusercontent.com/assets/142874/19822282/920fefd6-9d17-11e6-96a2-fdd08e5bb0aa.png)
![release performance](https://cloud.githubusercontent.com/assets/142874/19822283/921030cc-9d17-11e6-95f3-db6b39821eb7.png)

**Comment by Hixie** [comment]
I assume the bottom image is in --profile and the top is in --debug --hot?

**Comment by Hixie** [comment]
Both of those traces look pretty scary though for very different reasons.

**Comment by apwilson** [comment]
Reproduce:

```dart
import 'dart:async';

import 'package:flutter/widgets.dart';

Future main() async {
  runApp(
    new ClipRRect(
      borderRadius: new BorderRadius.circular(12.0),
      child: new Container(
        decoration: new BoxDecoration(
          backgroundImage: new BackgroundImage(
            image: new AssetImage('packages/armadillo/res/Background.jpg'),
            alignment: const FractionalOffset(0.4, 0.5),
            fit: ImageFit.cover,
          ),
        ),
        child: new Slider(
          child: new Opacity(
            opacity: 0.5,
            child: new Container(
              decoration: new BoxDecoration(
                backgroundColor: new Color(0xFFFF0000),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

class Slider extends StatefulWidget {
  final Widget child;
  Slider({this.child});
  @override
  SliderState createState() => new SliderState();
}

class SliderState extends State<Slider> with TickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(
      vsync: this,
      duration: new Duration(milliseconds: 500),
    );
  }

  @override
  Widget build(BuildContext context) {
    return new AnimatedBuilder(
      animation: _controller,
      builder: (BuildContext context, Widget child) {
        if (_controller.value == 1.0) {
          _controller.reverse();
        }
        if (_controller.value == 0.0) {
          _controller.forward();
        }
        return new Transform(
          transform: new Matrix4.translationValues(
            _controller.value * 400.0,
            _controller.value * 100.0,
            0.0,
          ),
          child: child,
        );
      },
      child: config.child,
    );
  }
}
```

**Comment by apwilson** [comment]
The AssetImage is referring to this file:  https://raw.githubusercontent.com/fuchsia-mirror/sysui/master/armadillo/lib/res/Background.jpg

However, if I use a NetworkImage instead of an AssetImage the issue goes away.

**Comment by apwilson** [comment]
And @Hixie, yes that's right.

**Comment by chinmaygarde** [comment]
@apwilson Do you remember what device you were using when you ran into this issue?

**Comment by abarth** [comment]
Nexus 9

**Comment by chinmaygarde** [comment]
Thanks! I prepared a reproducible test case and detailed in [this document](https://docs.google.com/document/d/1B2-3ZmWjiSRvxLvRSKNb5si2Vb3WbrGZ1VaSY_2LTYI/edit?hl=en#heading=h.9r7fv3pdrb0e). This problem was eliminated by our use of TextureImage as [shown here](https://www.youtube.com/watch?v=gNDtEVM_Tpw&feature=youtu.be). But since that uses RGB565 which will cause issues with color correctness, I am sharing the same with the Skia team so they can advise us on how to make this fast while maintaining color correctness.
