### ISSUE TITLE
used cached flutter engine, the widget data and states are retain when second time open it

### ISSUE THREAD

**Issue by niuhb** [flutter/flutter#65829]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
add 2 app, I use cached flutter engine. the flutter page's data and states are retain when I open the same page second time.
**Expected results:** 
add 2 app, I use cached flutter engine. I open the same page second time, the last time data are on screen.
**Actual results:** 
add 2 app, I use cached flutter engine. the flutter page's data and states are retain when I open the same page second time.
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/mac63/work/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac63/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mac63/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)

```

</details>

**Comment by TahaTesser** [comment]
Hi @niuhb 
Can you please provide a complete reproducible minimal code sample with flutter module and native app code (if possible in a zip or GitHub repository) 
Thank you

**Comment by niuhb** [comment]
> Hi @niuhb
> Can you please provide a complete reproducible minimal code sample with flutter module and native app code (if possible in a zip or GitHub repository)
> Thank you
my demo link. Thank you
https://github.com/niuhb/flutter_dmeo

**Comment by niuhb** [comment]
> Hi @niuhb
> Can you please provide a complete reproducible minimal code sample with flutter module and native app code (if possible in a zip or GitHub repository)
> Thank you

I run this sample  ,  find the same result
https://github.com/flutter/samples/tree/master/add_to_app/android_books

**Comment by TahaTesser** [comment]
Hi @niuhb 
Thanks for the code sample, I can run it but not clear what do you mean "second time open". Do you mean the android app or module?  Also not clear what expected results are. I see the list position is the same even after flutter view the second time after closing 

Thank you

**Comment by niuhb** [comment]
> Hi @niuhb
> Thanks for the code sample, I can run it but not clear what do you mean "second time open". Do you mean the android app or module? Also not clear what expected results are. I see the list position is the same even after flutter view the second time after closing
> 
> Thank you
My expectation is the second time I open FLUTTER VIEW, just like a new view, the input is cleared, the list is at the top. But now it's the sliding state is the last time.

**Comment by TahaTesser** [comment]
Hi @niuhb 
Thanks for clarifying, it's a known issue https://github.com/flutter/flutter/issues/63092
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
