### ISSUE TITLE
PlatformView freezes when the camera is launched in ios.

### ISSUE THREAD

**Issue by nishiyamaosamu** [flutter/flutter#65828]
Thanks for the support of flutter!

When I launch the camera on iOS, the webview_flutter using PlatformView freezes. This is not specific to webview_flutter, but seems to be a PlatformView related issue, because the webview_flutter in my developing another app and a widget using a different PlatformView have the same issue.
I've reproduced it in a simple sample app. Here's the repository: 
https://github.com/nishiyamaosamu/flutter_ios_camera_and_platformview_bug_sample

## Steps to Reproduce
Pattern 1. 
- Using image_picker to launch the camera
- When I access the webview, it's freezing

Pattern 2
- Launching the camera from a file upload in webview
- Once you close the webview and go to the webview screen again, it is frozen

## Plugin Info

```
  webview_flutter: ^0.3.22+1
  image_picker: ^0.6.7+7
```
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale ja-JP)
    • Flutter version 1.20.3 at /Users/nishiyama/development/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nishiyama/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Osamu の iPhone (mobile) • 0c127bd757ca9b29396f88f4316c41b46cb61c78 • ios • iOS 13.7
    • iPhone 11 (mobile)      • E6E622F1-FB46-4D90-90C7-48EA88C8D394     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
```

</details>

**Comment by darshankawar** [comment]
Hi @nishiyamaosamu,
Although I am able to replicate the issue, there's a similar issue open describing your case, which involves `google_maps_flutter` plugin instead of `webview_flutter`, [65361](https://github.com/flutter/flutter/issues/65361).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by nishiyamaosamu** [comment]
@darshankawar Thank you for guiding me.
