### ISSUE TITLE
framework not found flutter_plugin_android_lifecycle when tried to run on iOS

### ISSUE THREAD

**Issue by shajedulislam** [flutter/flutter#65820]
This plugin removes automatically after pod update and after that I get this error.

**Comment by darshankawar** [comment]
Hi @shajedulislam,
There's not enough description / information in the issue. Please elaborate on the exact issue you are facing along with `flutter doctor -v` and minimal complete reproducible code sample and steps you took to see this issue.
Thanks

**Comment by shajedulislam** [comment]
> Hi @shajedulislam,
> There's not enough description / information in the issue. Please elaborate on the exact issue you are facing along with `flutter doctor -v` and minimal complete reproducible code sample and steps you took to see this issue.
> Thanks

Problem solved. I faced it because of cache junk in bin. Just removed cache folder from flutter bin. It is solved now. Thanks!
