### ISSUE TITLE
MissingPluginException on iOS ,if I used method : [[FlutterViewController alloc]init],but it has no problem with method : [[FlutterViewController alloc]initWithEngine:]

### ISSUE THREAD

**Issue by Dawnhan** [flutter/flutter#65837]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

**Comment by darshankawar** [comment]
Hi @Dawnhan,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Dawnhan** [comment]
<details>
<summary>flutter doctor -v</summary>

ZCQFlutter % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/zhenghan/flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/zhenghan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 11 Pro     • 33ABC678-1A03-4A23-8921-8F34380DAA1D • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone 11 Pro Max • DF3DA812-267E-4026-B486-BD5F832494E5 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
</details>

I integrated flutter SDK into my iOS project ,  and native page could jump to different flutter page. So I used method without flutterEngine.

<details>
<summary> iOS code </summary>

ZCQFlutterBaseViewController *flutterVC = [[ZCQFlutterBaseViewController alloc]init];
[flutterVC setInitialRoute:routeJson];
[[self getCurrentVC].navigationController pushViewController:flutterVC animated:YES];

</details>

<details>
<summary> debug log </summary>

2020-09-15 17:24:52.231472+0800 zcqappForC[29298:2516676] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
#3      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)
#4      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:44:27)
#5      BaseCacheManager._createFileDir (package:flutter_cache_manager/src/cache_manager.dart:254:41)
#6      BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:23)
#7      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
#8      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
#9      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
#10     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
#11     CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
#12     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
#60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#68     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#74     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#79     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#83     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#84     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
#85     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#86     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#87     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#88     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
#89     _rootRun (dart:async/zone.dart:1184:13)
#90     _CustomZone.run (dart:async/zone.dart:1077:19)
#91     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#92     _invoke (dart:ui/hooks.dart:261:10)
#93     _drawFrame (dart:ui/hooks.dart:219:3)
2020-09-15 17:24:52.254967+0800 zcqappForC[29298:2516676] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
#3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
#4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
#5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
#6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
#7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
#8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
#9      getDatabasesPath (package:sqflite/sqflite.dart:161:54)
#10     CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:43:33)
#11     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:39:49)
#12     BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:12)
#13     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
#14     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
#15     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
#16     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
#17     CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
#18     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
#19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#46     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#74     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#80     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#90     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
#91     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#92     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#93     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#94     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
#95     _rootRun (dart:async/zone.dart:1184:13)
#96     _CustomZone.run (dart:async/zone.dart:1077:19)
#97     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#98     _invoke (dart:ui/hooks.dart:261:10)
#99     _drawFrame (dart:ui/hooks.dart:219:3)

</details>

Thank you for your reply ！

**Comment by darshankawar** [comment]
@Dawnhan thanks for the details. I see that you are on 1.17.5. Can you try to upgrade to latest stable and see if it works ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
