### ISSUE TITLE
overscroll_indicator.dart': Failed assertion: line 478 pos 16: '_displacementTickerLastElapsed == null': is not true

### ISSUE THREAD

**Issue by Ddtarsariya** [flutter/flutter#65845]
```
[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while handling a gesture:[39;49m
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 478 pos 16: '_displacementTickerLastElapsed == null': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      _GlowController.pull[39;49m 
[38;5;244m#3      _GlowingOverscrollIndicatorState._handleScrollNotification[39;49m 
[38;5;244m#4      NotificationListener._dispatch[39;49m 
[38;5;244m#5      Notification.visitAncestor[39;49m 
[38;5;244m#6      Element.visitAncestorElements[39;49m 
[38;5;244m...[39;49m
[38;5;244mHandler: "onUpdate"[39;49m
[38;5;244mRecognizer: VerticalDragGestureRecognizer#2a6a2[39;49m
    [38;5;244mstart behavior: start[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```

**Comment by pedromassangocode** [comment]
Hi @Ddtarsariya 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Ddtarsariya** [comment]
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.21.0-9.2.pre at C:\Users\tarsa\AppData\Local\Android\flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\tarsa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

    • VS Code at C:\Users\tarsa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Infinix X573 (mobile) • 33d7c628 • android-arm64 • Android 8.0.0 (API 26)

**Comment by Ddtarsariya** [comment]
> Hi @Ddtarsariya
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.21.0-9.2.pre at C:\Users\tarsa\AppData\Local\Android\flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\tarsa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

    • VS Code at C:\Users\tarsa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Infinix X573 (mobile) • 33d7c628 • android-arm64 • Android 8.0.0 (API 26)




---------------<code>---------------
return NestedScrollView(
      headerSliverBuilder: (context, innerBoxIsScrolled) => [
        SliverOverlapAbsorber(
          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
          sliver: SliverSafeArea(
            top: false,
            sliver: SliverAppBar(
              actions: [
                /* PopupMenuButton<String>(
                  itemBuilder: (BuildContext context) {
                    return {'Add Student'}.map((String choice) {
                      return PopupMenuItem<String>(
                        value: choice,
                        child: Text(choice),
                      );
                    }).toList();
                  },
                ), */
              ],
              elevation: 0,
              expandedHeight: 200.0,
              pinned: true,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.only(
                    bottomLeft: Radius.circular(5),
                    bottomRight: Radius.circular(5)),
              ),
              title: Text('Subject Name : ${widget.clase.subjectName}',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                  )),
              flexibleSpace: FlexibleSpaceBar(
                background: Container(
                  padding: EdgeInsets.fromLTRB(10, pad.top + 45, 10, 10),
                  child: Card(
                    elevation: 1,
                    shadowColor: Colors.grey,
                    color:
                        Color(int.parse(widget.clase.color)).withOpacity(0.5),
                    child: Container(
                      padding: EdgeInsets.all(20),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Subject Name : ${widget.clase.subjectName}',
                              style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.white)),
                          SizedBox(height: 10),
                          Text('Deprtment : ${widget.clase.department}',
                              style:
                                  TextStyle(fontSize: 16, color: Colors.white)),
                          SizedBox(height: 10),
                          Row(
                            children: [
                              Text('Standard : ${widget.clase.standard}',
                                  style: TextStyle(
                                      fontSize: 15, color: Colors.white)),
                              Text(' / ${widget.clase.division}',
                                  style: TextStyle(
                                      fontSize: 15, color: Colors.white)),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
              backgroundColor: Color(int.parse(widget.clase.color)),
            ),
          ),
        ),
      ],

    );

**Comment by pedromassangocode** [comment]
Hi @Ddtarsariya 
I need a minimal sample code that I can just copy/paste into a main.dart file  and run it. The code you provided contains personal code and I can't run it.
Thank you

**Comment by Ddtarsariya** [comment]
But, this is not a single screen , i am working on whole project so you need to whole project to run.
import 'package:bal_attendance/class/class_tile.dart';
import 'package:bal_attendance/models/class.dart';
import 'package:bal_attendance/screens/home/add_class/add_class.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:provider/provider.dart';

class ClassList extends StatefulWidget {
  @override
  _ClassListState createState() => _ClassListState();
}

class _ClassListState extends State<ClassList> {
  ScrollController _hideFloatingButtoncontroller;
  bool _isShow = true;

  @override
  void initState() {
    super.initState();
    _isShow = true;
    _hideFloatingButtoncontroller = ScrollController();
    _hideFloatingButtoncontroller.addListener(() {
      if (_hideFloatingButtoncontroller.position.userScrollDirection ==
          ScrollDirection.reverse) {
        if (_isShow == true) {
          setState(() => _isShow = false);
        }
      } else {
        if (_hideFloatingButtoncontroller.position.userScrollDirection ==
            ScrollDirection.forward) {
          if (_isShow == false) {
            setState(() => _isShow = true);
          }
        }
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    _hideFloatingButtoncontroller.removeListener(() {});
  }

  @override
  Widget build(BuildContext context) {
    final classes = Provider.of<List<Class>>(context) ?? [];

    return Scaffold(
      floatingActionButton: Visibility(
        visible: _isShow,
        child: Container(
          margin: EdgeInsets.fromLTRB(0, 0, 10, 20),
          child: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {
              Navigator.push(
                  context, MaterialPageRoute(builder: (context) => AddClass()));
            },
          ),
        ),
      ),
      body: ListView.builder(
        controller: _hideFloatingButtoncontroller,
        itemCount: classes.length,
        itemBuilder: (context, index) {
          return ClassTile(clase: classes[index]);
        },
      ),
    );
  }
}


this is a sample code.

**Comment by Ddtarsariya** [comment]
please check above for detailed.

**Comment by TahaTesser** [comment]
Hi @Ddtarsariya 
I just tried to reproduce the issue but your code sample is incomplete
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Not production code 
Thank you
