### ISSUE TITLE
Image.network can't reload another url

### ISSUE THREAD

**Issue by xlunzi** [flutter/flutter#65844]
**Expected results:**  Image.network load a empty url with errorBuilder , than url be a right value , show new resources .

**Actual results:**  Image can show new image ,but the Image always show  errorBuilder .

![image](https://user-images.githubusercontent.com/15652909/93203261-adb1a400-f786-11ea-9182-72ee7a915ba3.png)

![image](https://user-images.githubusercontent.com/15652909/93203124-6aefcc00-f786-11ea-95bf-5625551e6f88.png)

![image](https://user-images.githubusercontent.com/15652909/93203345-dc2f7f00-f786-11ea-93c8-fc6758ffdb53.png)

image.dart ：

![image](https://user-images.githubusercontent.com/15652909/93203621-506a2280-f787-11ea-8770-ba001f5a8a3c.png)

![image](https://user-images.githubusercontent.com/15652909/93203648-5b24b780-f787-11ea-9ddf-4513d652dc88.png)

because the "_lastException" is always not null .

![image](https://user-images.githubusercontent.com/15652909/93203702-72fc3b80-f787-11ea-8188-403d63299a19.png)

is it need set  "_lastException = null" in "_handleImageFrame" method .

It's all, Thank you.

**Comment by pedromassangocode** [comment]
Hi @xlunzi 
I see there's an open issue (https://github.com/flutter/flutter/issues/64752
) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
