### ISSUE TITLE
Update meta dependency in flutter and flutter_test

### ISSUE THREAD

**Issue by ghowen** [flutter/flutter#65854]
I want to use the latest version 4.5.0 of the `xml` package in Flutter 1.20.3. When I add `xml: ^4.5.0
` to my `pubspec.yaml`, I get the error

```
[xxx] flutter pub get
Running "flutter pub get" in xxx...                
Because every version of flutter_test from sdk depends on meta 1.1.8 and xml >=4.3.0 depends on meta ^1.2.0, flutter_test from sdk is incompatible with xml >=4.3.0.

So, because xxx depends on both xml ^4.5.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because xxx depends on both xml ^4.5.0 and flutter_test any from sdk, version solving failed.)
exit code 1

```

The same is true for `flutter` instead of `flutter_test`. Is there a way that I can use the current version of `xml` or does the SDK need to update its dependency on `meta` which then will update its dependency of `xml`?

Thanks.

**Comment by jonahwilliams** [comment]
The SDK is currently using the very latest version of meta `1.3.0-nullsafety.2 `. You did not include the version of flutter you are on, so it seems you must be on an older version/current stable. If you want to use a newer version of meta in the meantime you can use a pub dependency override: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by ghowen** [comment]
Thanks. I am on `1.20.3` stable on MacOS. I am just starting out with Flutter (porting an iOS Swift app). Is it advisable to not work on `stable` but on `beta` or `dev` during development?

**Comment by jonahwilliams** [comment]
I recommend using stable especially if you are new to Flutter. However, using stable means using a version of flutter that is older (and more tested!), which means it is not realistic for it to also have the most up to date versions of every library. These might not have even been published when it was released.

**Comment by ghowen** [comment]
Thanks again. I will stay on stable for now. 

Just so I get it: 
- meta 1.2.2 was published on July 2, 2020
- Flutter 1.20.3 on on Sept. 9, 2020 (2 months later)
- But Flutter 1.20.3 is still on meta 1.1.18 which was published Oct 30, 2019 (almost 1 year ago)

Is that kind of a delay to be expected?

**Comment by pratikbutani** [comment]
Have you checked [this article](https://pratikbutani.medium.com/flutter-2-upgrade-flutter-version-solving-failed-error-33ac1087cb6b)
