### ISSUE TITLE
IFrameElement does not change `src` attribute

### ISSUE THREAD

**Issue by goncalo-palma-3r** [flutter/flutter#65855]
When using an `IFrameElement`, there is no way of checking if the current URL has changed or not.

Methods that we have tried:

* Create a `Stream` that each 200ms checks the `IFrameElement` `src` attribute
* The same `Stream` tries to get the `IFrameElement` by id via the `document`, but the element is always null
```dart
Stream<String> _checkCurrentUri() {
    return Stream.periodic(Duration(milliseconds: 200), (_) {
      var iFrame = iframeElement;
      if (iFrame == null) {
        return "";
      }
      var iFrameUri = iFrame.src;

      if (_currentUri == iFrameUri) {
        return '';
      }

      print("Src has changed");

      return _currentUri = iFrameUri;
    }).where((event) => event.isNotEmpty);
  }
```
* Using the `onLoad` attribute of the `IFrameElement`, however the `Event` does not provide any information into the current URI apart from the `baseUri`

The repository to replicate the issue is here:
https://github.com/goncalo-palma-3r/iframe_redirection_bug

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by yjbanov** [comment]
The reason `document.getElementById` isn't working is likely because the platform view that hosts the iframe is inside shadow DOM (see https://github.com/flutter/flutter/issues/50452). We plan to support platform views without shadow DOM. If you have an alternative way of finding the iframe element, then the `src` attribute should work.

**Comment by goncalo-palma-3r** [comment]
@yjbanov Thanks for the reply :D 

So that I can get a  better understanding of the issue:

As you can see here: https://github.com/goncalo-palma-3r/iframe_redirection_bug/blob/master/lib/main.dart , the platform is registered in the widget, inside the same library, as "usual". Does this implementation create a Shadow DOM element?

```dart
void _initializeState() {
    print("IFrame code: ${widget.uri}");
    iframeElement.src = widget.uri;
    iframeElement.id = "iframe_id";
    iframeElement.width = '100%';
    iframeElement.height = '100%';
    iframeElement.style.border = 'none';

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      "47",
      (int viewId) => iframeElement,
    );

    iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: "47",
    );
  }
```

What alternatives way do I have to find the widget?

As you can see from the example, the widget is cached locally, and in the `Stream`, I'm constantly accessing it and verifying the `src` attribute

Is this what you were referring to?

**Comment by goncalo-palma-3r** [comment]
So @yjbanov after some research I see that a new `<flt-platform-view>` element is created when a new IFrame element is created:

![image](https://user-images.githubusercontent.com/64023725/93472193-4150b500-f8ec-11ea-9d8e-4ade6e340b4d.png)


So I can **try** to get to this `ShadowRoot` element, but I have a question:

What if we have multiple Iframes? How can we differentiate them?

I was trying to search for the `flt-platform-view` element in the `flutter/flutter` repo, but I couldn't retrieve it, do you know where this is?

**Comment by yjbanov** [comment]
Can the `_initializeState` function store the iframes in some `List` or `Map` to find them later?

Otherwise, hopefully soon we'll have a shadow DOM-free variable of platform view. @ditman is working on it right now.

**Comment by goncalo-palma-3r** [comment]
@yjbanov it is storing it, but the problem is that when I access it the `src` still has the previous value.

About Shadow-dom - I accessed the element via it and could get to the updated IFrame, however, I couldn't get any information since accessing the `src` gets me the **previous** URL and accessing **contentwindow** may throw CORS-specific errors :\

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.269 at /Users/tahatesser/Code/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X
      10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by yjbanov** [comment]
It seems I misunderstood the use-case. This is trying to read the src value after it's changed during some activity inside the iframe. This may be disallowed by the browser due to privacy/security constraints. We should verify this and perhaps document this on our docs site to avoid confusion in the future.

**Comment by ditman** [comment]
> @yjbanov it is storing it, but the problem is that when I access it the src still has the previous value.

@goncalo-palma-3r Yegor is right, the browser won't allow you to access the updated src of the iframe, if you're in a cross-domain situation:

* [Cross-domain iframe example](https://jsfiddle.net/ditman/9dk6Lpb8)
* [Same-domain iframe example](https://dit-embedded-iframe-test.firebaseapp.com/iframe.html)

Even if the iframe is accessible, I couldn't see the "src" attribute changing, you need to look into the [contentDocument](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) of the iframe.

More info: [**Access child iFrame DOM from parent page**](https://stackoverflow.com/questions/5181911/access-child-iframe-dom-from-parent-page).

**Comment by goncalo-palma-3r** [comment]
@ditman , thanks a lot for the concise answer!

Yeah, I was getting the same issue when I was trying to get the `contentWindow` of the iFrame via the shadow element. Either we have both domains under our control or it could get tricky.

So in this case the current behavior is the expected? `onLoad` will trigger a new page load without giving us any information about the url, correct?

**Comment by ditman** [comment]
@goncalo-palma-3r I'm surprised you get multiple onLoad events from the outside of the iframe!

**Comment by goncalo-palma-3r** [comment]
Huh...

Then I ask your opinion - what should be done with this issue @ditman ?

Should we add the functionality with the condition that it's only possible on same-domain websites?

**Comment by ditman** [comment]
@goncalo-palma-3r I don't think there's anything to add, if both iframes are in the same domain, you should be able to use `contentWindow` and look at the actual src directly (like in my small examples above), right?

It seems dart:html exposes contentWindow: https://api.dart.dev/stable/2.10.1/dart-html/IFrameElement/contentWindow.html

This is a limitation coming from the security sandbox of the web browser, not really related to dart/flutter, I think!

**Comment by ditman** [comment]
@goncalo-palma-3r can we close this one?

**Comment by goncalo-palma-3r** [comment]
Yes @ditman ! Sorry for not updating this.

We got this to work with another workaround - posting messages to the parent via JavaScript, so we can safely close this

Thanks for the support :pray:

**Comment by ditman** [comment]
Ah yes, postMessage is definitely the way to go. Thanks!

**Comment by zihandev** [comment]
HI, what exactly was the code used to change 'src' attribute. Would be helpful if you paste the code snippet here. 

Regards, 
Zihan

**Comment by ditman** [comment]
@zihandev here's the relevant docs to what @goncalo-palma-3r was talking about: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage. There's many examples online for postMessage.

**Comment by coditori** [comment]
Hi guys is there any update?

**Comment by ditman** [comment]
@coditori This is a fundamental [limitation of web browsers](https://github.com/flutter/flutter/issues/65855#issuecomment-705136612), and you can workaround it by using [postMessage](https://github.com/flutter/flutter/issues/65855#issuecomment-763089936).
