### ISSUE TITLE
Did Google play not accept my update because of this package?

### ISSUE THREAD

**Issue by StatTark** [flutter/flutter#65858]
I published the application on google play, but then I updated it. The only library I have added as new in this update is the flutter device_info library. Google Play did not accept the updates I posted. I don't understand why. Could it be from the device_info library. Are any permissions required when using the device_info library? The only information I get with the device_info library is the phone brand.The ads in the application are google ads. No ads were received from elsewhere.The mail sent to me;
![image](https://user-images.githubusercontent.com/33375656/93235365-206e4f80-f786-11ea-82cd-3ae3c25353d9.png)

The package I use: https://pub.dev/packages/device_info

**Comment by pedromassangocode** [comment]
Hi @StatTark 
This clearly is not related to the package mentioned. Maybe you are using the information retrieved by the package wrong in one of your Ads implementation? 

The rejection is about Google Ads and the way you are using/showing them and not about obtaining the device information.

Closing as this is not an issue with Flutter itself.
Thank you
