### ISSUE TITLE
The Flokk app needs to be updated for Windows

### ISSUE THREAD

**Issue by csells** [flutter/flutter#65865]
The Flokk sample app needs to be updated with a Windows release against the alpha bits: https://github.com/gskinnerTeam/Flokk/

**Comment by stuartmorgan** [comment]
> Flokk was built on the bleeding edge of Flutter, so make sure to use the master branch in their git repo and checkout commit 9c3f0faa6d.
We're aiming to upgrade to an official Flutter version soon to make this easier.

This is three months old; it'll need to be updated to work on a current master before there can be a Windows build.

**Comment by csells** [comment]
Correct. I'm working with gskinner now to make this happen.

**Comment by stuartmorgan** [comment]
There's a windows/ folder and a Windows release; can we close this now?

**Comment by gspencergoog** [comment]
Closing!
