### ISSUE TITLE
Flutter golden tests render incorrectly

### ISSUE THREAD

**Issue by russell-sf** [flutter/flutter#65868]
## Steps to Reproduce

1. Create test project.
2. Make sure flutter_test is added to pubspec as dev_dependency.
2. Add the following test file in test directory...

test/bug_test.dart
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() async {
  testWidgets('StackTest', (WidgetTester tester) async {
    final widget = MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Container(
        color: Colors.grey,
        child: _TestWidget(),
      ),
    );
    await tester.pumpWidget(widget);
    await tester.pumpAndSettle();
    await expectLater(
        find.byType(MaterialApp), matchesGoldenFile('bug_test.png'));
  });
}

class _TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Stack(
        children: [
          Text('Item 1'),
          Text('Item 2'),
        ],
      ),
    );
  }
}
```

Run flutter test --update-goldens test/bug_test.dart

**Expected results:** 

The generated file should show the stack items centered on screen layered one on top of the other.

**Actual results:** 

![bug_test](https://user-images.githubusercontent.com/53881666/93241419-4f1f0280-f753-11ea-9403-affdc8ae5edd.png)

<details>
  <summary>Logs</summary>

```
```

```
```

> flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.1 at /dev/flutter
    • Framework revision 2ae34518b8 (6 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rzornes/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/rzornes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • DE595D8F-B8EA-4128-BCC5-866577C949F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
Issue replicable on latest master.

![bug_test](https://user-images.githubusercontent.com/67046386/93305605-59f19a00-f81c-11ea-8784-8f5f1f486604.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.174, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.174 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 37b03ec2c2 (26 hours ago), 2020-09-14 23:52:04 -0400
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by xu-baolin** [comment]
Why do you think the generated file render incorrectly? the gap between the two rectangles is the char ` `.

**Comment by goderbauer** [comment]
In tests, we render all text with the "Ahem" font, which replaces all characters with a rect. This is to make text rendering more predictable. So, what you're seeing is expected. We should document this better, however. This is tracked by https://github.com/flutter/flutter/issues/41773.

**Comment by russell-sf** [comment]
If I run the same code in an app I get...

![image](https://user-images.githubusercontent.com/53881666/93401263-cafe7500-f84f-11ea-966c-62758d7c5fbc.png)

Which I do expect. I should get the same thing in a golden test or what is the point of having a golden test?
