### ISSUE TITLE
Flutter Gallery release for Windows

### ISSUE THREAD

**Issue by csells** [flutter/flutter#65862]
We need a Windows release against the alpha bits for the Flutter Gallery: https://github.com/flutter/gallery/releases

**Comment by gspencergoog** [comment]
I have an executable built, just need to upload it to the gallery site.

**Comment by stuartmorgan** [comment]
We should also ideally:
- Add the `windows` folder to the repo so that it works out of the box
  - (we never did this for Linux apparently; we should do that too)
- Bump the `url_launcher` dependency to `^5.6.0` so that it includes Windows

**Comment by gspencergoog** [comment]
@stuartmorgan OK, I've created https://github.com/flutter/gallery/pull/325 with all of that in it.
