### ISSUE TITLE
[pigeon] Pigeon generates analysis issues (unused local variable)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#65872]
## Bug

@gaaclarke Using `pigeon` v`1.5.0` on the `video_player` plugin generates code that has analysis issues.

I needed to remove the following block of code *manually*:

https://github.com/flutter/plugins/pull/3032/commits/a068b6d4f5cc0f96d91d83028e467fa13db2c16f

```dart
        final Map<dynamic, dynamic> mapMessage =
            message as Map<dynamic, dynamic>;
```

This is from the `setup` method of the **generated** test host.

## Generation

The `pigeons/messages.dart` that generates this looks as follows:

```dart
@HostApi(dartHostTestHandler: 'TestHostVideoPlayerApi')
abstract class VideoPlayerApi {
  void initialize();
  TextureMessage create(CreateMessage msg);
  void dispose(TextureMessage msg);
  void setLooping(LoopingMessage msg);
  void setVolume(VolumeMessage msg);
  void setPlaybackSpeed(PlaybackSpeedMessage msg);
  void play(TextureMessage msg);
  PositionMessage position(TextureMessage msg);
  void seekTo(PositionMessage msg);
  void pause(TextureMessage msg);
  void setMixWithOthers(MixWithOthersMessage msg);
}
```

The `setup` method of the `TestHostVideoPlayerApi` contains the unused member.

## Steps to reproduce

Luckily this ran on CI, which means that you can get the **exact** steps to reproduce from the CI steps:

https://cirrus-ci.com/task/5805102936096768

This contains all steps, completely reproducible (because it is CI and in `flutter/plugins`).  
(https://github.com/flutter/plugins/runs/1118942372)

**Comment by jmagman** [comment]
@gaaclarke

**Comment by xster** [comment]
I assume this is fixed now @gaaclarke?

**Comment by gaaclarke** [comment]
> I assume this is fixed now @gaaclarke?

yep, thanks
