### ISSUE TITLE
didExceedMaxLines in TextPainter works wrong with latest web version 

### ISSUE THREAD

**Issue by nikpozdnyakov** [flutter/flutter#65886]
I use the "auto_size_text" library on the web platform and it doesn't work correctly (everything is fine on the mobile platform).
I decided to find out what the problem is, and I realized that didExceedMaxLines always returns false, and because of this does not work out the condition in the library
![image](https://user-images.githubusercontent.com/66692704/93259294-4efd2200-f7a8-11ea-8f51-ac723a62e213.png)
![image](https://user-images.githubusercontent.com/66692704/93260330-e747d680-f7a9-11ea-9284-c4f1c42e6b4e.png)

**Comment by darshankawar** [comment]
Hi @nikpozdnyakov,
`auto_size_text` is a 3rd party plugin. Please consider logging this issue in their repo : https://github.com/leisim/auto_size_text/issues
Closing. as this isn't an issue with Flutter.

**Comment by nikpozdnyakov** [comment]
the fact that a third-party library does not work due to the fact that the flutter in the web version does not work correctly didExceedMaxLines in TextPainter
That's why I wrote here.

**Comment by nikpozdnyakov** [comment]
@darshankawar

**Comment by darshankawar** [comment]
@nikpozdnyakov fair point. reopening.

**Comment by darshankawar** [comment]
@nikpozdnyakov I see there's now a new open issue without using the 3rd party plugin, [65940](https://github.com/flutter/flutter/issues/65940). Please follow-up there for updates.
Closing this as duplicate.
