### ISSUE TITLE
Android Scenario builder showing infra failure

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#65881]
P1 as this is potentially blocking a beta release of 1.22, which is needed for the iOS announcement 

PR: https://github.com/flutter/engine/pull/21188

failure: https://ci.chromium.org/p/flutter/builders/try/Linux%20Android%20Scenarios/1156?

/cc @godofredoc @christopherfujino

**Comment by godofredoc** [comment]
The problem was a flake and has not happened again:

https://ci.chromium.org/p/flutter/builders/try/Linux%20Android%20Scenarios
