### ISSUE TITLE
Calculate the path to gems file directly from the generated folder

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#65888]
The gems bundler is adding a the ruby version in the path and it may be different depending on the test bed it is running. We need to get the values to add to the path and GEM_HOME env directly from the generated folder instead of hardcoding the path to a given version of ruby.

**Comment by godofredoc** [comment]
\cc @christopherfujino

**Comment by godofredoc** [comment]
\cc @jmagman @drewroengoogle @ricardoamador this is related to the error in arm64 cross arch tests.

**Comment by christopherfujino** [comment]
The way rubygems is designed does not play nicely with a tool like cipd. @ricardoamador do you have a build log with a relevant crash?

**Comment by ricardoamador** [comment]
@christopherfujino take a look here: https://ci.chromium.org/p/flutter/builders/staging/Mac_arm64%20tool_host_cross_arch_tests?cursor=id%3E8800936530191176481&limit=25
The error reported each time is this:
```
Uncaught Exception: FileNotFoundError('2', 'No such file or directory')
```

**Comment by christopherfujino** [comment]
Per the [stacktrace](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800936626246555681/+/u/RECIPE_CRASH__Uncaught_exception_/logging), it looks like this line is failing:

```
        api.flutter_deps.gems(
            env, env_prefixes, checkout_path.join('dev', 'ci', 'mac')
        )
```

And not the `flutter_deps` module itself, which surprises me.

**Comment by christopherfujino** [comment]
So it looks like we're installing bundler into `gem_dir`: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800936626246555681/+/u/Install_gems/install_bundler/execution_details

Maybe the solution here is to invoke bundler with the absolute path here: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#319

**Comment by ricardoamador** [comment]
Correct. I think that is what Godofredo is saying here.

**Comment by godofredoc** [comment]
Removing myself from this bug, @drewroengoogle @keyonghan this can addressed when landing the changes to the ruby cipd package.

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/38088
