### ISSUE TITLE
Input hint text does not go away and closing keyboard makes text dissapear

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#6589]
## Steps to Reproduce

When the input has a hint, typing text does not make the hint go away, then when the keyboard closes the text disappears.

Android and iOS

Live Android Nexus 6 device, iOS simulator (see doctor below)

See video: https://www.dropbox.com/s/okcnxirzy7ayfcj/hint.mp4?dl=0

```
 Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that
        // was created by the App.build method, and use it to set
        // our appbar title.
        title: new Text(config.title),
      ),
      body: new Center(
        child: new Center(
            child: new Block(children: <Widget>[
          new Container(child: new Text("Username"), padding: new EdgeInsets.all(10.0)),
          new Container(child: new Input(hintText: "faisalabid"), padding: new EdgeInsets.all(10.0)),
          new Container(child: new Text("Username"), padding: new EdgeInsets.all(10.0)),
          new Container(child: new Input(hintText: "faisalabid"), padding: new EdgeInsets.all(10.0))
        ])),
      ),
    );
  }
```
## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.
## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision 949e27ae8f (3 days ago), 2016-10-26 19:11:55
    • Engine revision 7e5d63513a
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • Nexus 6  • ZX1G22KKH4                           • android-arm
    • iPhone 6 • 67C44FE8-57DF-49E8-93E7-EEE76E00042C • ios (simulator)

**Comment by eseidelGoogle** [comment]
Thanks for the extremely detailed report! FYI @mpcomplete

**Comment by mehmetf** [comment]
@FaisalAbid Input, the way you are using it, is stateless. You need to either use forms and form fields to make it stateful: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/text_field_demo.dart

or introduce the state keeping yourself via something like this:

```Dart

class MyWidgetState extends State<MyWidget> {
  var inputStr;

  Widget build() {
     return new Input(
        value: inputStr,
        onValueChanged: (value) {
           setState() {
              inputStr = value;
           }
        },
     );
  }
}

```

**Comment by mpcomplete** [comment]
See also https://github.com/flutter/flutter/issues/6018

**Comment by mpcomplete** [comment]
Closing this as a dupe.
