### ISSUE TITLE
print() not printing to console on external ios device

### ISSUE THREAD

**Issue by hossam-zaki** [flutter/flutter#65893]
I recently upgraded my flutter, and now print() statements to not execute when running on external ios device. They were working previously, before I upgraded, but now that I have upgraded they do not work. Is there any advice? I tried ```flutter clean``` but this didn't work. Any help is appreciated

**Comment by darshankawar** [comment]
@hossam-zaki,
There's similar open issue describing your case, [44718](https://github.com/flutter/flutter/issues/44718).
Please follow-up there for updates and any questions.
Closing this as duplicate.
