### ISSUE TITLE
Overlay docs should be improved to differentiate from Stack

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#65890]
The `Overlay` docs mention a relation with `Stack` but it doesn't explain or make clear the differences between them.

It would be useful to also have an explanation on when to use each one of them and why.

**Comment by believeInJha** [comment]
Hi @feinstein Can I start doing work on it?

**Comment by feinstein** [comment]
If you know what to do, the differences and can make a simple and concise text, then yes.

**Comment by Raj-Dave368** [comment]
where is the Overlay docs located? I am a new bee to open source, so please help me to be a master!

**Comment by Roshan13046** [comment]
anyone working on this issue?
I would like to work on it.

**Comment by feinstein** [comment]
Many thanks @creativecreatorormaybenot !
