### ISSUE TITLE
Mac LUCI builders' Xcode should include iOS 14 SDK

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#65901]
For [this PR](https://github.com/flutter/engine/pull/20972) to build, it needs to have at least iOS SDK version 13.4, and it's on 13.0 right now.

An example of a build failing because of this is this [iOS Engine build](https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/8189?)

**Comment by gspencergoog** [comment]
Any ETA on this? It's blocking some feature work.

Cc @godofredoc

**Comment by godofredoc** [comment]
Does this need be updated across engine, sdk and devicelab?

**Comment by godofredoc** [comment]
We can move the xcode version on the sdk and engine with a small amount of effort but for devicelab that can take up to mid q4.

**Comment by gspencergoog** [comment]
Hmm. I think that if the engine build is updated, then the engine artifacts should work on the devicelab.

**Comment by godofredoc** [comment]
\cc @zanderso @jonahwilliams @jmagman any objections with updating the engine ios version to 13.4?

**Comment by jmagman** [comment]
Do you mean add the iOS 13.4 SDK to the current version of Xcode?  We can do that with some symlinking with Xcode, I think.

We can't upgrade the engine builder clang version (Xcode version) beyond the minimum Xcode version enforced in the tool, or we will break bitcode again.
See [internal documentation](https://docs.google.com/document/d/1MkSm1xUGL57sWZgzxDexozqPlSUnKt_pkbfmsV_mr1s/edit#heading=h.w6yg2p5cjbzg) and [internal post-mortem](http://requiem/doc/postmortem126775).

**Comment by jmagman** [comment]
\cc @nturgut who I think has added newer SDKs to older versions of Xcode in LUCI.
\cc @dnfield to bring down the hammer on us all if we break bitcode again.

**Comment by godofredoc** [comment]
The builders automatically select the mac sdk correlated to the requested ios version. We only provide xcode version.

**Comment by godofredoc** [comment]
We can update both sdk and engine xcode version at the same time but that will most likely break the devicelab.

**Comment by gspencergoog** [comment]
Yes, I think just adding the SDK would work.

**Comment by dnfield** [comment]
SDK should be fine, bitcode just cares about clang version which is tied to the Xcode version.

**Comment by gspencergoog** [comment]
The code has `@available` checks, and I think the reason it's not building is that the SDK doesn't have the symbols it is looking for:

```
FAILED: obj/flutter/shell/platform/darwin/ios/framework/Source/flutter_framework_source.FlutterViewController.o 
/opt/s/w/ir/cache/goma/client/gomacc  ../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/flutter/shell/platform/darwin/ios/framework/Source/flutter_framework_source.FlutterViewController.o.d -DFLUTTER_FRAMEWORK=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_CODEC_DECODES_PNG -DSK_ENCODE_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DSK_DISABLE_REDUCE_OPLIST_SPLITTING -DSK_ENABLE_DUMP_GPU -DSK_DISABLE_AAA -DSK_DISABLE_EFFECT_DESERIALIZATION -DSK_SUPPORT_LEGACY_MATRIX_FACTORIES -DSK_DISABLE_LEGACY_SHADERCONTEXT -DSK_DISABLE_LOWP_RASTER_PIPELINE -DSK_FORCE_RASTER_PIPELINE_BLITTER -DSK_GL -DSK_ASSUME_GL_ES=1 -DSK_ENABLE_API_AVAILABLE -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_NOEXCEPT -I../.. -Igen -I../.. -I../../flutter/third_party/txt/src -I../../third_party/harfbuzz/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/skia -I../../third_party/rapidjson -I../../third_party/rapidjson/include -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../flutter/third_party -I../../flutter -I../../flutter/shell/platform/darwin/common/framework/Headers -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -mios-simulator-version-min=8.0  -fno-strict-aliasing -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-non-c-typedef-for-linkage -Wno-deprecated-copy -Wno-range-loop-construct -Wunguarded-availability -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -Os -fno-ident -fdata-sections -ffunction-sections -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -fno-exceptions -nostdinc++ -isystem /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -Werror=overriding-method-mismatch -Werror=undeclared-selector -fvisibility-inlines-hidden -fobjc-call-cxx-cdtors -std=c++17 -fno-rtti -fno-exceptions -nostdinc++ -isystem /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1  -c ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm -o obj/flutter/shell/platform/darwin/ios/framework/Source/flutter_framework_source.FlutterViewController.o
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:1020:17: error: property 'key' not found on object of type 'UIPress *'
      if (press.key == nil || press.phase == UIPressPhaseStationary ||
                ^
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm:1027:30: error: property 'key' not found on object of type 'UIPress *'
        @"keyCode" : @(press.key.keyCode),
```

The `key` property was introduced in 13.4.

**Comment by jmagman** [comment]
More background: If the version of clang used to build the engine is newer than the version of clang used to build the developer's app, they will see [App Store submission failures](https://github.com/flutter/flutter/issues/49787#issuecomment-583182412).  So we need to keep the builder's clang version (shipped in Xcode) equal to the minimum Xcode version enforced by the tool.  

But newer SDKs can be added to older Xcode versions by symlinking the new SDK into the right spot in the older Xcode app bundle.  So @gspencergoog needs the 13.4 SDK embedded in Xcode 11.  I think @nturgut pulled that off in a LUCI builder before for testing.

**Comment by jmagman** [comment]
Also, updating the SDK on the engine builder won't impact the devicelab.

**Comment by godofredoc** [comment]
I'm not aware that the current xcode cipd packages support that approach, wondering what was the workaround @nturgut implemented.

**Comment by jmagman** [comment]
It's a weird use case for sure, usually you just need to upgrade Xcode to the right version and you get the SDK that's included.  I'd be happy to kick off the process to start requiring developers have Xcode 11.3 for 1.22 (tool change, messaging), but there are devicelab agents still on Xcode 11.0.
Can we maintain our own cipd package?

**Comment by godofredoc** [comment]
I asked the same question to the maintainers of the cipd packages and didn't get a very clear answer. I'll follow up with them to check.

**Comment by xster** [comment]
Yes, we should build using the SDK 14 ideally. Also keep track, we should create an umbrella task to encompass all the near/medium-term work we'll need to do such as eventually moving Xcode to 12 on engine, moving devicelab devices to iOS 14, building on big sur, etc so we can keep track and sequence the work.

**Comment by dnfield** [comment]
@LongCatIsLooong did a workaround sdk upgrade last time.  I think it involved creating a separate cipd package and just grabbing it in the recipe.

**Comment by nturgut** [comment]
> I'm not aware that the current xcode cipd packages support that approach, wondering what was the workaround @nturgut implemented.

@jmagman we didn't implemented it on LUCI. We were investigating if we can use multiple versions to be able to test other Safari (on Simulators) such as with iOS12 or with iOS14.

We made web engine test harness very easy to configure though, if are changing XCode or simulators installed with it, it should be fairly easy for us to use.

**Comment by nturgut** [comment]
> I asked the same question to the maintainers of the cipd packages and didn't get a very clear answer. I'll follow up with them to check.

Yes, as we discussed earlier this is also very useful for web team. 

I might be mistaken but my understanding from that discussion was:
- we will download a new simulator version via XCode
- we will add the file from this directory: `/Library/Developer/CoreSimulator/Profiles/Runtimes/` to a cipd package
- when we download the cipd package on a LUCI bot, we will put the contents to: Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes

**Comment by godofredoc** [comment]
I have only tried the process with swift, we'll need to validate we can use it with the runtimes. If it works then we'll need to create a wrapper around the xcode_sdk model that downloads the additional packages on requests and optimize the caches.

**Comment by jmagman** [comment]
This is blocking https://github.com/flutter/flutter/issues/64502, can't build the ARM simulator frameworks until the builder has iOS 14.

**Comment by jmagman** [comment]
Retitled to make sure the SDK is updated to iOS 14 (or whatever the latest GM'd SDK is available when this is completed).
\cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
I was able to build `ios_debug_sim_unopt` using cipd xcode11 with a symlinked ios 14 iphonesimulator sdk. But before moving forward I want to verify the generated framework is good. What are the checks I should perform @jmagman ?
Currently I have:
1. `xcode-select`ed a stock xcode 11, run an existing flutter project using `flutter run --local-engine=ios_debug_sim_unopt`
2. checked `LC_VERSION_MIN_IPHONEOS`'s `version` is `8.0` and `sdk` is `14.0`

Also do we need to submit a test app to make sure this is not going to get rejected on app store?

**Comment by jmagman** [comment]
After you `flutter run` check the clang version in `Flutter.framework/Info.plist`.
```
plutil -p build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist | grep clang
  "ClangVersion" => "Apple clang version 11.0.0 (clang-1100.0.33.8)"
```
It must exactly equal that version.  If so, we're good to go!

**Comment by LongCatIsLooong** [comment]
Failed to run `compile_ios_jit.sh` for the scenario app. 

ld: in '/Applications/Xcode11.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem_kernel.tbd', building for iOS
 Simulator, but linking in .tbd file (/Applications/Xcode11.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem
_kernel.tbd) built for macOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jmagman** [comment]
@LongCatIsLooong What's the full linker command when you see that?  `-isysroot` looks set correctly in `compile_ios_jit`.

**Comment by LongCatIsLooong** [comment]
it was 
```
 "/Applications/Xcode11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode11.app/Contents/Developer/Toolchains/XcodeDe
fault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -dylib -arch x86_64 -dylib_install_name @rpath/App.framework/App -ios_simulator_version_min 8.0.0 -bitcode_bundle -bi
tcode_process_mode marker -syslibroot /Applications/Xcode11.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -t -o /Users/weiyuhuang/
engine/src/flutter/testing/scenario_app/./build/ios/App.framework/App -rpath @executable_path/Frameworks -rpath @loader_path/Frameworks /var/folders/xh/zqb9lb7s0r92slljdg8l3jnm00m00
f/T/--9791b5.o -lSystem /Applications/Xcode11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.ios.a
/var/folders/xh/zqb9lb7s0r92slljdg8l3jnm00m00f/T/--9791b5.o
```

the tbd file does target macos it seems: https://gist.github.com/LongCatIsLooong/1fa516dd62b60c9311ec2348c884a083

**Comment by jmagman** [comment]
I have Xcode 12 installed (no symlink SDK tricks) and when I run it, it works.  The difference I see is that the Xcode 12 toolchain [swapped out `-ios_simulator_version_min 8.0.0` for `-platform_version ios-simulator 8.0.0 14.0`](https://reviews.llvm.org/D71579). Not sure if that's the problem, though.  

```
  "<redacted>Xcode-12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library <redacted>Xcode-12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib 
  -no_deduplicate 
  -dynamic 
  -dylib 
  -arch x86_64 
  -dylib_install_name @rpath/App.framework/App 
  -platform_version ios-simulator 8.0.0 14.0 
  -bitcode_bundle 
  -bitcode_process_mode marker 
  -syslibroot <redacted>Xcode-12.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk 
  -o /Users/magder/Projects/engine/src/flutter/testing/scenario_app/./build/ios/App.framework/App 
  -rpath @executable_path/Frameworks -rpath @loader_path/Frameworks 
  /var/folders/bx/pyplw7v92lj58gm3_lztz5sc00mfq2/T/moo-789812.o -lSystem <redacted>Xcode-12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.iossim.a
```

**Comment by jmagman** [comment]
I have a bad feeling TAPI had to get a lot more sophisticated with archs/targets with the macOS ARM changes, and the Xcode 11 toolchain won't be able to handle it.  Xcode 11 SDK is using `tapi-tbd-v3` and looks like:
```
--- !tapi-tbd-v3
archs:           [ i386, x86_64 ]
...
platform:        ios
...
  - archs:           [ i386, x86_64 ]
```
and Xcode 12 SDK is on version 4:
```
tbd-version:     4
targets:         [ i386-macos, x86_64-macos, x86_64-maccatalyst, arm64-macos, arm64-maccatalyst ]
...
parent-umbrella:
  - targets:         [ i386-macos, i386-maccatalyst, x86_64-macos, x86_64-maccatalyst, 
                       arm64-macos, arm64-maccatalyst, arm64e-macos, arm64e-maccatalyst ]
...
```

**Comment by jmagman** [comment]
@LongCatIsLooong Do you know if the engine frameworks build with iOS 14 SDK against the Xcode 11 toolchain?  I'm not sure how to override the buildtools `clang` paths.  

I feel like it would have the same problem, but if it does happen to work, can we use the Xcode 11 hybrid package on the engine framework builders only, as opposed to any of the other builders running tests, etc?

**Comment by LongCatIsLooong** [comment]
they do (at least some of them): https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/weiyuhuang_google.com/13a6e979e3da140e383a604d97ef5dc322152c5ca429a9d4404599256d244540/+/annotations?server=chromium-swarm.appspot.com

**Comment by jmagman** [comment]
But if it's pointing on the iOS 13 `SYSROOT` then it's no better than we have now, right?

I was able to get it working by symlinking the Xcode 12 linker into the Xcode 11 toolchain.
```
 ln -s  /path/to/Xcode-12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld   /path/to/Xcode-11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
```

**Comment by LongCatIsLooong** [comment]
The only place I had to use the iOS 13 sdk is the scenario app: https://github.com/flutter/engine/pull/21614/files, the ios frameworks are generated using the iOS 14 sdk. Does the scenario app have to use the iOS 14 sdk?

**Comment by jmagman** [comment]
It looks like it's happening building the framework, too, though not sure why it's a warning and not an error.
https://logs.chromium.org/logs/flutter/led/weiyuhuang_google.com/13a6e979e3da140e383a604d97ef5dc322152c5ca429a9d4404599256d244540/+/steps/build_ios_debug_sim/0/stdout
```
[3791/3800] SOLINK libFlutter.dylib libFlutter.dylib.TOC
ld: warning: building for iOS Simulator, but linking in .tbd file (/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem_kernel.tbd) built for macOS
ld: warning: building for iOS Simulator, but linking in .tbd file (/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem_platform.tbd) built for macOS
ld: warning: building for iOS Simulator, but linking in .tbd file (/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem_pthread.tbd) built for macOS
```

**Comment by LongCatIsLooong** [comment]
Removing the bitcode marker flag used to compile the scenarios app turns that into a warning. I think it probably hit this line:
https://github.com/apple-opensource/ld64/blob/fd3feabb0a1eb18ab5d7910f3c3a5eed99cef6ab/src/ld/PlatformSupport.cpp#L156-L158

The warning only shows up when building simulator targets it seems. Bitcode must be disabled when building with `--simulator` right?

**Comment by jmagman** [comment]
@LongCatIsLooong We support bitcode for add-to-app, which can be run in the simulator (with the bitcode marker).  If all you changed was the SDK and some stuff for the scenario app, it's probably fine if the framework compiles.  If you also turned off bitcode during framework builds, that's a problem.

**Comment by LongCatIsLooong** [comment]
Looks like https://github.com/flutter/engine/pull/20972 was able to build on CI. Closing. 

Thanks for the help @godofredoc and @jmagman!
