### ISSUE TITLE
Android APP Widget support

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#65908]
I mean the widget on home screen, not widget.

Does it supported for now? How to using it?

**Comment by pedromassangocode** [comment]
Hi @jinfagang 
Flutter does not support Android app widgets, because `RemoteViews` support's only view's defined in the supporting list at: https://developer.android.com/reference/android/widget/RemoteViews.html 

Also, see:
https://developer.android.com/guide/topics/appwidgets

**Comment by imReker** [comment]
It could be achieved now, see this https://github.com/imReker/FlutterHomeWidget

**Comment by jinfagang** [comment]
@imReker thank u! that is incredible!
