### ISSUE TITLE
CP request for 1.22: NoSuchMethodError: The method 'cancel' was called on null

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#65903]
This is an error introduced as part of the cache refactor to reduce the occurrence of https://github.com/flutter/flutter/issues/52437 .

Instead of attempting to re-download the asset, the tool will crash with this NSM error. I expect this to be severe since it should match the number of occurrences of the previously fixed issue (which was high) and was independently reported  (https://github.com/flutter/flutter/issues/65449) twice before it was fixed.

The fixing PR is https://github.com/flutter/flutter/pull/65797 which is fairly small, self-contained, and tested.

**Comment by pcsosinski** [comment]
marking as closed to pick up on the CP radar (closed issue w/ label)
