### ISSUE TITLE
FullScreenDialog result

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#6590]
Hello, 

In previous version of my application, I used to get results from full screen dialogs passing a completer in my material route.

Here the code:

`
Completer<LocationPoint> completer =  new Completer<LocationPoint>();
    completer.future.then((LocationPoint val){
     //do something
});

MaterialPageRoute<LocationPoint> route = new MaterialPageRoute<LocationPoint>(
      builder: (BuildContext context) => new ChangeLocationDialog(),
      completer: completer
    );

```
Navigator.push(context, route);` 
```

In last commits the completer has disappeared and I cannot figure out how getting my result using another way.

Can you help me? Thank you

**Comment by abarth** [comment]
Yes.  `Navigator.push` now returns a `Future` that contains the value the route completes too.  You can just wait that `Future` instead of needing to create your own `Completer`.  The `Completer` is now built-in.

**Comment by lequem** [comment]
Thank you Abarth. It's working.

I have two other questions : (I can open another tickets if you prefer):
 
- One concerning the Intent class that have disappeared. Is there another class to do the same thing?

- I would like to open a dialog after the build of my view, when it is ready. What is the best way to do that?

Thank you again,

Vincent

**Comment by abarth** [comment]
> One concerning the Intent class that have disappeared. Is there another class to do the same thing?

If you just want to open a URL, you can use the https://docs.flutter.io/flutter/services/UrlLauncher-class.html class.  If you want to do something more Android-specific, I'd recommend writing a plugin that does that you need.

> I would like to open a dialog after the build of my view, when it is ready. What is the best way to do that?

I'm not sure I understand what you're trying to do.  Does do you mean by "when it is ready"?

Generally, you can call `showDialog` whenever you like.  If you're waiting for some data from the network, for example, you can call `showDialog` when you receive the callback from the network that the data is available.

**Comment by lequem** [comment]
Thank you for your answers, 
For the second question, I would like that my statefullwidget display a dialog as soon as it is displayed.

**Comment by abarth** [comment]
>  I would like that my statefullwidget display a dialog as soon as it is displayed.

You probably want to override `initState` in your `State` subclass and trigger the dialog from there:

https://docs.flutter.io/flutter/widgets/State/initState.html

**Comment by lequem** [comment]
I have tried to add the code that call the showDialog method at the end of the override of initState:

`@override
  void initState() {
    super.initState();
    this._showParametersDialog();
  }`

and I have the following error:

`The following assertion was thrown building _ModalScopeStatus(active):
I/flutter : inheritFromWidgetOfExactType(Theme) was called before SearchDialogState.initState() completed`

**Comment by abarth** [comment]
The microtask call delays the dialog slightly so that the tree finishes building.

**Comment by lequem** [comment]
Thanks!
