### ISSUE TITLE
Color palettes suggestion not appearing when adding colors

### ISSUE THREAD

**Issue by arunchaudharyweb** [flutter/flutter#65919]
**Expected results:** 

![Screenshot (77)](https://user-images.githubusercontent.com/59797321/93303868-bb643980-f819-11ea-9afd-14ddd4ecabbd.png)

**Actual results:** 

![Screenshot (74)](https://user-images.githubusercontent.com/59797321/93303201-c2d71300-f818-11ea-8f16-45abf37f178c.png)

<details>
  <summary>Logs</summary>

```
```

![Screenshot (80)](https://user-images.githubusercontent.com/59797321/93304551-cec3d480-f81a-11ea-8080-28c3e87b6f42.png)

```
```

![Screenshot (79)](https://user-images.githubusercontent.com/59797321/93304631-eef39380-f81a-11ea-9e30-87737bd122b1.png)

```
```

</details>

**Comment by darshankawar** [comment]
Hi @arunchaudharyweb,
This seems to be an issue with the plugin and not Flutter. Please see [this](https://github.com/flutter/flutter/issues/59132) issue and [where](https://github.com/flutter/flutter/issues/59132#issuecomment-652303716) to file / track the issue for this.
Closing, as this isn't an issue with Flutter.
