### ISSUE TITLE
ScrollableGrid: Omitting optional 'children' parameter returns broken widget

### ISSUE THREAD

**Issue by pedrovhb** [flutter/flutter#6591]
When creating a ScrollableGrid widget, not setting the 'children' parameter gives you the red error widget with the text `NoSuchMethodError: The getter 'length' was called on null. Tried calling: length`

Passing `[]` to this parameter gives you an error-free empty ScrollableGrid widget as expected.

Pretty minor but I'd expect either the children parameter to be required or to be assigned the empty list by default.

**Comment by abarth** [comment]
Good point.

**Comment by abarth** [comment]
Patch in https://github.com/flutter/flutter/pull/6592

**Comment by pedrovhb** [comment]
Cool, that was quick.

**Comment by abarth** [comment]
Patch hasn't landed yet.  :)

**Comment by abarth** [comment]
landed now.  :)
