### ISSUE TITLE
Flutter calls the iOS native page. Clicking on the native page, the flutter page behind it can also trigger the click event

### ISSUE THREAD

**Issue by 253CL** [flutter/flutter#65923]
From URL: https://www.flutterchina.club/get-started/install.md

**Comment by TahaTesser** [comment]
**Orginal** 
flutter 调用iOS 原生页面 点击原生页面 后面的flutter 页面也能触发点击控件的事件

**Translated Title**
Flutter calls the iOS native page. Clicking on the native page, the flutter page behind it can also trigger the click event

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
