### ISSUE TITLE
[in_app_purchase] Get receipt from autorenewal subscription

### ISSUE THREAD

**Issue by gabrielmdc** [flutter/flutter#65934]
Hello,

We are currently integrating the [_in_app_purchase_](https://pub.dev/packages/in_app_purchase) plugin into our application. It went super smooth until we had to deal wit receipts. We are quite uncertain on how to validate and receive the receipt for a single purchase in an **auto renewable subscription**. We are able to make a purchase just fine, but we heard that we need to verify the receipt. In order to do that, we set up our Backend code (written in Python) to just do that. We have been sending mocked data to our new Backend, and it does indeed work. Now we wanted to proceed integrating it: 

- How do we actually get the receipt, after receiving the purchase?

Note: we only use the StoreKit wrapper, not the general one, since we are developing this purchase system for iOS only.

```dart
// _purchases = list of current purchases

_subscription = InAppPurchaseService.iap.purchaseUpdatedStream
        .listen((purchases) async {
      if (purchases.length > 0) {
        // Cancell all the 'aborted' transactions
        for (final purchase in purchases) {
          // If the user abort the purchase flow, then remove it from the 'purchase' list
          if (purchase.pendingCompletePurchase) {
            await InAppPurchaseService.iap.completePurchase(purchase);
            _purchases.remove(purchase.productID);
          }
        }
        final purchasesWithoutErrors =
            purchases.where((p) => p.status != PurchaseStatus.error).toList();
        _purchases.addAll(_getPurchaseMap(purchasesWithoutErrors));
      }
      // Verify the purchase and do an action, like get receipt and send to backend (async)
      await _verifyPurchase();
    });
```

**Comment by Thorbenl** [comment]
Can we get some eyes on this? Or is this question not formulated well enough? Please let us know :)

**Comment by gabrielmdc** [comment]
This issue could be close since I have solved it.
After to play a lot with the purchase flow, I got the receipt used to send it to our backend for validation.
