### ISSUE TITLE
[NNBD] Conflicting generic type in Navigator's  push methods

### ISSUE THREAD

**Issue by sma** [flutter/flutter#65938]
In class `Navigator`, there is `Future<T> push<T>(Route<T> route)` and `static Future<T> push<T extends Object>(BuildContext context, Route<T> route)`. The latter restricts `T` to a subclass of `Object` which means that a `Route<void>` doesn't work here. I think, it should be possible to use such a route with both variants. The same if true for other variants of push or replace.

If there is a reason for not allowing `Route<void>` this should be documented, I think. Currently the documentation stats:

```
/// The type argument `T` is the route's return type, as used by
/// [currentResult], [popped], and [didPop]. The type `void` may be used if the
/// route does not return a value.
```

**Comment by ndawod** [comment]
This is a recent change (horrible decision, btw) in Fluter -- it was possible to use void juat yesterday.

The same can be said about many of the changes from today's upgrade. Apps are breaking because of the nullability changes.

**Comment by sma** [comment]
Some time ago I ported a 7000 LOC app to NNBD and now I regularly check the progress and this was the first problem so far. Therefore, I can't deny or confirm other breakage :) I was able to work around this problem by using `Navigator.of(context).push()` and my app still runs.  BTW, I don't think this is a documentation bug but a a typing error.

**Comment by goderbauer** [comment]
/cc @a14n @chunhtai 

I agree that `Route<void>` still needs to be allowed.
