### ISSUE TITLE
Adding a contentPadding parameter to CheckBoxListTile

### ISSUE THREAD

**Issue by ianspryn** [flutter/flutter#65946]
## Use case

In using a `CheckboxListTile()` and setting the `secondary` parameter to an image (and not an icon like usual), I want there to be no padding so that I can produce something like the following:

![image](https://user-images.githubusercontent.com/4182500/93358063-0af13800-f80f-11ea-9328-51f715d216aa.png)

But with using a `CheckBoxListTile()`, the best I can do is the following. Notice the padding of 16px on the left and right.

![image](https://user-images.githubusercontent.com/4182500/93359493-ad5deb00-f810-11ea-85f1-1c0effea17fd.png)

## Proposal

`ListTile()` contains the following parameter:

```
  /// The tile's internal padding.
  ///
  /// Insets a [ListTile]'s contents: its [leading], [title], [subtitle],
  /// and [trailing] widgets.
  ///
  /// If null, `EdgeInsets.symmetric(horizontal: 16.0)` is used.
  final EdgeInsetsGeometry contentPadding;
```

Please add the same parameter to `CheckBoxListTile()` and pass it onto `ListTile()` so that the padding for `CheckBoxListTile()` can be customized.

**Comment by Calamity210** [comment]
Unless I'm misunderstanding your issue, `CheckboxListTile` already has `contentPadding`. Take a look at https://api.flutter.dev/flutter/material/CheckboxListTile/contentPadding.html and https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/checkbox_list_tile.dart

**Comment by ianspryn** [comment]
My apologies, I failed to ensure I was on the latest version of Flutter.

Yes, that is exactly what I was needing!
