### ISSUE TITLE
required or @required?

### ISSUE THREAD

**Issue by HudsonAfonso** [flutter/flutter#65956]
https://github.com/flutter/flutter/blob/0220c3585c12e3f9d3bb778d90b5476b0316a8e8/packages/flutter/lib/src/widgets/scroll_view.dart#L1137

required or @required?

**Comment by Aman9026** [comment]
required

**Comment by jonahwilliams** [comment]
`@required` if you are currently authoring flutter code. In a future release you will be able to opt-in to null-safety gradually, which allows the usage of `required` which has stronger guarantees
