### ISSUE TITLE
Set up special rules for size and tech debt regression alerts

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#65957]
The default step-based regression detection of http://flutter-flutter-perf.skia.org/ would generate too many alerts as every small size or debt change is a perfect step change. We shall set special detection rules (e.g., only alert if the metric jumps more than x%) for those. Otherwise, we'll get a habit of ignoring those alerts and miss the real big regressions.

**Comment by liyuqian** [comment]
@kf6gpe : would you like to take this issue? Please let me know if there's any difficulty in setting up such alert rules.

**Comment by kf6gpe** [comment]
@liyuqian Can you give me a hint and let me know which entities I should be searching on in skia-perf? I get the general idea, but I'm not seeing either one when I drill down in the alerts panel.

If it's easier to discuss on GVC, we can put this off until our next 1:1. Thanks!

**Comment by liyuqian** [comment]
GVC might be easier. Let's go through it in tomorrow's 1:1 then :)

**Comment by kf6gpe** [comment]
Alerts added! Delay was cockpit error on my part --- need to use "sub_result" as the key for adding new values for alerts.
