### ISSUE TITLE
Make a "partial" option for checkbox status instead of only true/false

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#65962]
I'm making a feature where I want a way to check all boxes or no boxes in a list of check boxes.  But I fall into the trap of this third state.  I will have to come up with my own icon I guess for now.  The checkbox in flutter only has two states.  true/false.  But this is a sort of "all or none" checkbox.  So it as three states.  true/fall/null  maybe?  Some third state to show a middle "partial" state.  I see this is other UI's so I think it's pretty common?

**Comment by EdwynZN** [comment]
Have you checked the tristate property? https://api.flutter.dev/flutter/material/Checkbox/tristate.html

`Checkbox(tristate: true);`

**Comment by darshankawar** [comment]
Hi @jdeltoft,
Please check above link which should answer your question on having third state of the checkbox.
Thanks.

**Comment by jdeltoft** [comment]
Oh gosh, thanks!  Happy Friday!  Flutter seems to always have something I need.  I'm not sure why I didn't find this when I was google searching.  Anyway, will go implement it this way.  Thanks so much!
