### ISSUE TITLE
official plugin for encryption/decryption and signing/verification

### ISSUE THREAD

**Issue by nilsmagnus** [flutter/flutter#65963]
## Plugin for working with keychain/keystore

Some packages on pub.dev/flutter implement partial support for generating keypairs of various sorts and using them for signing and encryption. These packages vary in feature-completeness and are not updated frequently enough to provide assurance of correctness and robustness. 

It would be reassuring to use a plugin provided by the flutter dev team for working with keychain/keystore to be sure that the native apis are correctly used and to be sure that the plugins are updated with fixes when/if vulnerabilities are identified.

## Proposal

Create a plugin supported by the flutter team that can be used for encryption/decryption and signing/verification using keys stored in hardware.

**Comment by stuartmorgan** [comment]
Closing as out of scope; this would be best provided by community packages, rather than the Flutter team picking one specific implementation.
