### ISSUE TITLE
Inconsistency in the merged Basic Widgets Overview page

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#6596]
A couple of things I noticed since the Basic Widgets Overview page and the Material Design Catalog page merged:
* There are still two separate links for Basic widgets and Material design catalog in the left navigation pointing to the same page, but there is only the Basic widgets overview link in the main content area of the homepage. See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/348942/19865608/383f1384-9f5a-11e6-900a-6cf4a5423b88.png)

* To address the above inconsistency, maybe we can keep the material design catalog link but point it to the material design section in the merged page? 
* The images for the material design components take a lot more space now in the merged page. Do they need to be this large? It's now a little hard to see the text below the images when they are so large. 
* Do we still want to call the merged page "Basic Widgets Overview"? How about simply calling it "Widgets Overview"?

**Comment by InMatrix** [comment]
@Hixie @qchong

**Comment by qchong** [comment]
@Hixie Not sure why the material design catalog needs to be merged into the basic widgets page. IMHO, these can exist separately. This solves the problem of helping developers who want to quickly find which material design API to use without having to dig through the API docs (or scrolling all the way to the bottom of the current 'basic widgets' page). 

'Basic widgets' (excluding the merged material design section) consists of information that belongs in the API docs. To make this page more helpful, consider adding code snippets to illustrate how the layout, painting, scrolling etc. APIs are used, along with some best practices.

**Comment by Hixie** [comment]
P1 got lost because we had two pages. They didn't understand that there were two parts to the documentation. We figured that it's easier if there's just one document that points people to the dartdocs for each of the most useful widgets. That way if you find the doc, you don't get stuck there.

**Comment by Hixie** [comment]
To address your other point, we're gutting the 'Basic widgets' part and pointing to the dartdocs instead. There's already a page with sample code, that's the intro-widgets page.

**Comment by InMatrix** [comment]
Thanks for making these changes. It looks good to me. Let's see if that helps in the afternoon's study session.

**Comment by Hixie** [comment]
Changes have landed. Sorry about the breakage earlier, I'm editing blind. :-)

**Comment by Hixie** [comment]
Let me know if you spot anything else that needs fixing. I plan to try to add diagrams to the earlier stuff on that page as well, FWIW. Dunno if I'll be done in the next hour.
