### ISSUE TITLE
See if we can lint the firebase configs during Travis builds of website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6597]
Right now, the Travis builds do not attempt to deploy the website or lint the config. This means that the firebase bits of the process ONLY trigger when Travis is ready to actually do the deploy.

We should look to see if we can lint the firebase config, to catch any errors during the PR process.

**Comment by eseidelGoogle** [comment]
I don't see anyway to do that with the `firebase` tool.  It doesn't seem to have a dry-run option on `deploy` nor does it have any sort of linter.  Maybe there are some tricks to perform with the migrate command?
    tools:migrate [options]                    ensure your firebase.json format is up to date

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1829](https://github.com/flutter/website/issues/1829) via [**ZenHub**](https://www.zenhub.com/)
