### ISSUE TITLE
[doctor] Add macOS architecture to doctor output

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#65976]
Now that there are 2 architectures for macOS (x64 and arm64) we should include that information in the `flutter doctor` output.  We often ask people reporting errors to add `flutter doctor` output and this can help us find bugs related to one architecture.

cc @jonahwilliams @jmagman

**Comment by jmagman** [comment]
It's already there (darwin-x64) in `doctor` and `devices`:
```
macOS (desktop)        • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
```

**Comment by jmagman** [comment]
> It's already there (darwin-x64) in `doctor` and `devices`:

Never mind, that's hardcoded.
https://github.com/flutter/flutter/blob/9f040865c92a4c1dc37744248436f98c14b85cad/packages/flutter_tools/lib/src/macos/macos_device.dart#L44

**Comment by jonahwilliams** [comment]
We print darwin-x64 for every mac though @jmagman , we need to fix that too

**Comment by jmagman** [comment]
`uname -m` is reporting `x86_64` when from a dart process, even on ARM, so `flutter doctor` is still showing x86.  I don't know how we can get around that until dart is un-rosettafied.
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.448, on macOS 11.0 20A5299w x86_64, locale en-US)
```

**Comment by gaaclarke** [comment]
@jmagman That's weird since uname is it's own process I wouldn't have expected the parent to make any difference.  You might try changing these parameters to `Process.start` -- ` bool includeParentEnvironment`,  `bool runInShell`
https://api.dart.dev/stable/2.10.0/dart-io/Process-class.html

It's possible uname is just grabbing from an environment variable and since includeParentEnvironment is true it grabs the wrong one.

**Comment by jmagman** [comment]
As of https://github.com/flutter/flutter/pull/67970 this is done for the host in the `[✓] Flutter (Channel master` line.
The rest of the work is to track showing it for macOS device targets.
