### ISSUE TITLE
[plugins]Deprecation & Unchecked warning

### ISSUE THREAD

**Issue by hamdikahloun** [flutter/flutter#65970]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: Add package's from [https://pub.dev/publishers/flutter.dev/packages](https://pub.dev/publishers/flutter.dev/packages) to pubspec.yaml
3. Run `flutter build apk`.

**Expected results:** No Warning

**Actual results:** 

- androidintent : `MethodCallHandlerImpl.java uses unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3043

- camera : `CameraPlugin.java uses or overrides a deprecated API.` **PR** : https://github.com/flutter/plugins/pull/3018

- connectivity : `ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.` **PR** : https://github.com/flutter/plugins/pull/3051

- espresso : `EspressoFlutter.java uses unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3111

- google_maps_flutter : `Some input files use unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3112

- in_app_purchase : `MethodCallHandlerImpl.java uses unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3120

- share : `MethodCallHandler.java uses unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3004

- video_player : `VideoPlayerPlugin.java uses or overrides a deprecated API` **PR** : https://github.com/flutter/plugins/pull/3019

- webview_flutter : `Some input files use or override a deprecated API.` & `FlutterWebView.java uses unchecked or unsafe operations.` **PR** : https://github.com/flutter/plugins/pull/3117

<details>
  <summary>Logs</summary>

```
Analyzing example...
No issues found! (ran in 24.2s)
```

```
flutter doctor -v
[√] Flutter (Channel master, 1.22.0-10.0.pre.39, on Microsoft Windows [version 10.0.19041.508], locale fr-FR)
    • Flutter version 1.22.0-10.0.pre.39 at D:\flutter
    • Framework revision dcace1417d (2 days ago), 2020-09-15 09:36:26 +0100
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
All the linked PRs are closed, so I'm assuming this is fixed. If there are still other things left, please file new issues to track them.
