### ISSUE TITLE
I had a issue about isolate.

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter#65986]
Hi , i had a question about isolate, is when i use isolate in flutter app, it only can by Isolate.Spawn(function), if i generate by Isolate.spawnUri(), will cause a error, why?  

thanks for help me. :)

**Comment by darshankawar** [comment]
Hi @bladeofgod,
There's similar open issue describing your case, [10564](https://github.com/flutter/flutter/issues/10564).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
