### ISSUE TITLE
[in_app_purchase] IOS askToBuy purchaseUpdatedStream not broadcasting

### ISSUE THREAD

**Issue by zodiark23** [flutter/flutter#65996]
**InAppPurchase version** : v0.3.4+8

I simulated the askToBuy functionality on iOS and notice we don't receive update on the stream for transaction that is being **deferred**. We would like to display something to show that we're waiting for the Permission of the Parent/Guardian.

**Comment by darshankawar** [comment]
Hi @zodiark23,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by reyantropia** [comment]
Here's flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.6 19G2021, locale en-PH)
    • Flutter version 1.12.13+hotfix.9 at /Users/flutter/Documents/Development/flutter
    • Framework revision f139b11009 (6 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/flutter/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
```
Just the base example on in app works. By flagging  `sandBoxTesting` to true, this will turn on simulateAskToBuy(parent/guarding permission). When this happen, the `InAppPurchaseConnection.instance.purchaseUpdatedStream` is not broadcasting any changes.

**Comment by darshankawar** [comment]
Hi @zodiark23 @reyantropia, you seem to be on old version of stable. Could you upgrade to latest (1.20.4) and verify to see if the issue still occurs ?
Thanks.

**Comment by zodiark23** [comment]
Okay I'll try it with the latest version

**Comment by zodiark23** [comment]
@darshankawar I upgraded to flutter version to 1.20.4 stable and updated my iOS Physical Device to iOS 14.
Its working a bit now, I can't seem to get past this issue on `flutter devices` .

```
1 connected device:

Reyan’s iPhone (mobile) • 9abef2637b32a96a60753f02adc0571171b14a41 • ios • iOS 14.0

• Error: Reyan’s iPhone is busy: Copying cache files from device. Xcode will continue when Reyan’s iPhone is finished. (code -10)
```

**Comment by zodiark23** [comment]
@darshankawar I upgraded to flutter version to 1.20.4 stable (i also tried 1.22 beta) and updated my iOS Physical Device to iOS 14.
Its working a bit now, I can't seem to get past this issue on `flutter devices` .

```
1 connected device:

Reyan’s iPhone (mobile) • identifier • ios • iOS 14.0

• Error: Reyan’s iPhone is busy: Copying cache files from device. Xcode will continue when Reyan’s iPhone is finished. (code -10)
```

**Comment by darshankawar** [comment]
@zodiark23 glad to know its working for you.
Regarding the `flutter devices` issue, I think it's a known issue related to iOS 14. Please see [this](https://flutter.dev/docs/development/ios-14) for more details and reference.

With that said, are you able to run the app on iOS to check if the plugin broadcasting is working ? If so, do you feel this issue can be closed or need to keep open ?
Thanks.

**Comment by judastatus** [comment]
@zodiark23  Hello, I have the same problem. My  Flutter version number is 1.20.4 stable. My device is ios14. But I didn't solve the problem.

**Comment by zodiark23** [comment]
@judastatus I managed to fix it buy unpairing the device via Xcode's _Devices & Simulator_. After that I cleared the trusted devices (**Settings** > **Developer** > _**Clear Trusted Device**_. Done this multiple times before it worked xD.

**Comment by zodiark23** [comment]
@darshankawar Thanks.

**Comment by darshankawar** [comment]
@zodiark23 Glad to know it's working for you.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.
