### ISSUE TITLE
Error pubspec.yaml: A package may not list itself as a dependency.

### ISSUE THREAD

**Issue by jayantsr** [flutter/flutter#65992]
Not able to Install the package

Error in flutter pub get 

Thanks
Jay
jayantsr@gmail.com

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by darshankawar** [comment]
@jayantsr,
It's not clear which plugin you are trying to add. Please add steps to replicate and the plugin that you want to add. 
Also make sure the plugin name is not same as your project name, that may throw the error you are seeing.
If issue persists, please provide `pubspec.yaml`.
Thanks.

**Comment by jayantsr** [comment]
Sorry I am reporting for the first time in the github.   The Plugin is geofencing 0.1.0 which is released on Sept  10 2020.  https://pub.dev/packages/geofencing.

**Comment by jayantsr** [comment]
@darshankawar 
thankyou very. much.  It was some other issue with my network.  It's working.  Just to answer. the question.  the Plugin is geofencing 0.1.0.  released on Sept 10, 2020.  Thanks, it's working now.
