### ISSUE TITLE
[google_sign_in] Programmatically set server clientId with Flutter GoogleSignIn plugin for Android

### ISSUE THREAD

**Issue by ngminhduong** [flutter/flutter#66005]
I need programmatically set server clientId instead of GoogleSignIn plugin read directly from `default_web_client_id` when request to GoogleSignIn.
Example code with native:

```
gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(appToken)
                .requestServerAuthCode(appToken)
```
Any suggestion to implement this with Flutter?
Thanks,

**Comment by cyanglaz** [comment]
This is done with https://github.com/flutter/plugins/pull/3640, closing the issue.
