### ISSUE TITLE
Google's app InkWell bug

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#66012]
Sorry for off-topic, but can you tell someone in google to fix this in the google app on iOS?

![photo_2020-09-17_12-57-11](https://user-images.githubusercontent.com/42138594/93455680-570eac00-f8e5-11ea-8e9c-02fb8cc8b2f8.jpg)
![photo_2020-09-17_12-57-18](https://user-images.githubusercontent.com/42138594/93455677-56761580-f8e5-11ea-9212-4a13c0240a30.jpg)
![photo_2020-09-17_12-57-21](https://user-images.githubusercontent.com/42138594/93455675-55dd7f00-f8e5-11ea-8b14-2d9b64d78ca1.jpg)

**Comment by pedromassangocode** [comment]
The easiest method for reporting an app as suspicious is to report it through the Google Play Store on your device. 

Closing as this is not a valid Flutter issue.
Thank you
