### ISSUE TITLE
Platform views in Add2App (iOS only) are broken as a result of https://github.com/flutter/engine/pull/20050

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#66026]
I cannot supply a sample app, because after 3 days of trying, I cannot reproduce this in a simple Add2App sample app.

However, I did track down the issue to https://github.com/flutter/engine/pull/20050.

**The problem:** 
Our Add2App experience launches a route that contains Webview widget (from the webview_flutter plugin), and upon first launch of this route, everything works well. However, if the webview (which is a platform view) is inside a SlideTransition (or pretty much anything that translates it I assume), when the widget gets translated, all touch events stop working and the webview is "dead/frozen".

The following very simple code reproduces this issue in our app

<details><summary>Code</summary>

```
class DefaultHomePage extends StatefulWidget {
  DefaultHomePageState createState() => DefaultHomePageState();
}

class DefaultHomePageState extends State<DefaultHomePage> with TickerProviderStateMixin {

  BasicMessageChannel testChannel;

  AnimationController _animationController;

  @override
  void initState() {
    _animationController = AnimationController(duration: Duration(milliseconds: 500), vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    _animationController.dispose();
    _animationController = null;

    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: SlideTransition(
        position: Tween<Offset>(
            begin: Offset.zero,
            end: Offset(0, -0.5)
        ).animate(_animationController),
        child: Center(
          child: Container(
            color: Colors.grey,
            width: 400,
            height: 700,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                SizedBox(height: 100.0),
                Expanded(
                    child: Stack(
                      children: [
                        WebView(
                          javascriptMode: JavascriptMode.unrestricted,
                          initialUrl: "https://google.com",
                        )
                      ],
                    )
                ),
                Padding(
                    padding: EdgeInsets.only(top: 20),
                    child: FlatButton(
                      color: Colors.red,
                      child: Text("Move"),
                      onPressed: () {
                        if (_animationController.isCompleted) {
                          _animationController.reverse();
                        }
                        else {
                          _animationController.forward();
                        }
                      },
                    )
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

This widget tree will show a webview, and a button underneath it labeled "Move". Tapping Move will move the webview up, and as soon as that happens, the webview no longer responds to any touch events. 

**Tag 1.21.0-7.0.pre works properly, but as of tag 1.21.0-9.0.pre, it no longer works.**

From there, I was able to find that this exact commit broke it https://github.com/flutter/flutter/commit/e5ddb820d96dc8a81bd49a02b05233bf17151495. From there, I was able to find that the only actual engine change that is relevant is https://github.com/flutter/engine/pull/20050

Unfortunately, I cannot reproduce this in a very simple Add2App sample. So there is something about our actual app that causes Flutter to break in this case. At least I am 100% confident that this PR is the thing that broke it.

I will attach a very simple Add2App project that loads our flutter engine in the exact same way we do in our actual app, but note that it will not repro the actual problem. I'm really not sure what it is with our app that causes this, but it's a big problem.

As of  1.21.0-9.0.pre, this problem exists.

**Comment by dannyvalentesonos** [comment]
[Add2AppTest (platform views).zip](https://github.com/flutter/flutter/files/5239815/Add2AppTest.platform.views.zip)

**Comment by dannyvalentesonos** [comment]
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-12.0.pre at /Users/danny.valente/Library/flutter/1.22.0-12.0.pre-dev
    • Framework revision a27c242b0e (6 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by blasten** [comment]
Hi Danny, 

I'm sorry to hear that. 

One thing I would suggest is to create a new branch, and then slowly remove code that you think is unrelated. For example, using the example app you attached, use the same Dart code and pub dependencies from the real production app after removing any dependency on the platform such as custom platform channels.

We would really appreciate if you could provide us with a sample app that reproduces this issue.

**Comment by dannyvalentesonos** [comment]
Thanks @blasten. I don't think this is going to be possible. I took the same flutter module (dart code) from the sample app and used that in my real app, and could still reproduce the problem there, but not in the same app.

Our app is very complicated, and uses Navigation controllers among other things, and I don't think I will be able to find the offending piece that causes this bug. Can the change I found (flutter/engine#20050) be taken out? There are quite a number of times that bug fixes I was waiting on got reverted because it broke other clients. In this case, this is breaking us. Could this be reverted?

Thanks!

**Comment by blasten** [comment]
It does make sense to revert it, but that patch was fixing another bug.  I'm afraid that unless we found the root case, this might break again.

**Comment by blasten** [comment]
@cyanglaz to confirm next steps

**Comment by cyanglaz** [comment]
https://github.com/flutter/flutter/issues/66044 might be related.

**Comment by dannyvalentesonos** [comment]
Well I cannot believe it! We set a global tint color as well, and removing that allows our webview to function properly too!
I'm going to add this to my sample app and re-attach here.

Thanks @cyanglaz !!

@blasten  Looks like we found the issue :)

**Comment by cyanglaz** [comment]
@dannyvalentesonos Glad to hear it! Is the global tint necessary for your app? Are you able to workaround it? I'm currently working on another P1 issue. I will cycle back to take a look at this one to see if we can fix it in the flutter engine.

**Comment by dannyvalentesonos** [comment]
Here is the sample Add2App that reproduces the problem. Just search for `self.window.tintColor = UIColor.blackColor;` in the AppDelegate.m.

[Add2AppTest (platform views).zip](https://github.com/flutter/flutter/files/5243337/Add2AppTest.platform.views.zip)

I think given the problem, I bet this can also easily be reproduced in a very simple Flutter app too. I'll see if I can get that attached here too.

As for your question on whether it's needed, I'm pretty sure it is, but I'll check with the team tomorrow. We can comment it out in a dev branch while we wait for a fix, however, we have a release we are working on that lines up with when 1.22 should be getting to Beta, and so we would need this fixed in 1.22.

**Comment by dannyvalentesonos** [comment]
@cyanglaz here is a very simple Flutter app demonstrating the problem. (Ignore the name of the app, seeing this is an app I had previously used to log a rotation bug with platform views).

What I like about the sample apps I'm submitting here is that the route that contains the webview does not run any transition animation so the webview will accept touches until you actually press the Move button on the page which will then run a SlideTransition. This way, it might help you with the debugging.

I hope this helps!

[webview_rotate_app.zip](https://github.com/flutter/flutter/files/5243391/webview_rotate_app.zip)

**Comment by nwparker** [comment]
Potentially related: 66097

**Comment by pedromassangocode** [comment]
I was able to reproduce on latest master channel.

<details><summary>flutter doctor -v</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.251 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision d26268bb9e (10 hours ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 7A82F29E-E49E-4B3C-8609-1570361DBC17 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by dannyvalentesonos** [comment]
> @dannyvalentesonos Glad to hear it! Is the global tint necessary for your app? Are you able to workaround it? I'm currently working on another P1 issue. I will cycle back to take a look at this one to see if we can fix it in the flutter engine.

I asked around, and yes the global setting of tintColor is needed in our app.

**Comment by cyanglaz** [comment]
The fix is ready in https://github.com/flutter/engine/pull/21286, I didn't try add to app scenarios but I have tested it does fix the same issue on a pure flutter app. @dannyvalentesonos If it's not much bother, do you mind testing this patch with your app?

**Comment by dannyvalentesonos** [comment]
@cyanglaz I'd be happy to test this once the engine rolls into the flutter master branch, seeing I have never built the engine before.
If there's any way you can get me an engine to test with, I'd be glad to test it today. I can replace the iOS artifacts if that works. Let me know.

And thanks for the quick fix!

**Comment by dannyvalentesonos** [comment]
We are trying to get onto a stable build, and we were targeting 1.22. This one is really important to us. Is there any chance to get this fix in 1.22?

**Comment by blasten** [comment]
> Is there any chance to get this fix in 1.22, given the fix is really simple?

Yes. It will be. Any PR associated with an issue labeled `cp: <version>` is considered for cherry pick.

**Comment by dannyvalentesonos** [comment]
Awesome, good to know. The addition of the milestone confused me. Thanks @blasten .

**Comment by cyanglaz** [comment]
@dannyvalentesonos https://github.com/flutter/flutter/issues/66044 is closed. I'm going to close this issue too. Please wait until https://github.com/flutter/engine/pull/21286 is rolled into the framework, then try it again.

**Comment by dannyvalentesonos** [comment]
@cyanglaz  I have confirmed the new engine has fixed this issue. Thanks again!
