### ISSUE TITLE
InteractiveViewer OnInteractionUpdate provides (0,0) coordinates when scrolling.

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#66035]
## Steps to Reproduce
Recently, a commit hit master that caused OnInteractionUpdate to be triggered when scrolling. This update provides (0,0) coordinates and breaks applications that rely on interaction updates for coordinate changes of objects within the page.
With the code below you will notice that taps on the screen provide the correct coordinates, but when scrolling, (0,0) is provided.

cc: @justinmc per https://github.com/flutter/flutter/pull/65432#issuecomment-693683213

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          // This is the theme of your application.
          //
          // Try running your application with "flutter run". You'll see the
          // application has a blue toolbar. Then, without quitting the app, try
          // changing the primarySwatch below to Colors.green and then invoke
          // "hot reload" (press "r" in the console where you ran "flutter run",
          // or simply save your changes to "hot reload" in a Flutter IDE).
          // Notice that the counter didn't reset back to zero; the application
          // is not restarted.
          primarySwatch: Colors.blue,
          // This makes the visual density adapt to the platform that you run
          // the app on. For desktop platforms, the controls will be smaller and
          // closer together (more dense) than on mobile platforms.
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home:  MyHomePage(title: 'Flutter Demo Home Page'),
        );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _rowCount = 5;
  int _columnCount = 5;
  bool _text = true;
  bool _color = true;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        title: Text("Column: $_columnCount\nRow: $_rowCount"),
        actions: [
          IconButton(
              icon: Icon(Icons.add),
              onPressed: () {
                setState(() {
                  _rowCount += 5;
                  _columnCount += 5;
                });
              }),
          IconButton(
              icon: Icon(Icons.format_paint),
              onPressed: () {
                setState(() {
                  _color = !_color;
                });
              }),
          IconButton(
              icon: Icon(Icons.text_fields),
              onPressed: () {
                setState(() {
                  _text = !_text;
                });
              })
        ],
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
      ),
      body: InteractiveViewer(
          scaleEnabled: true,
          panEnabled: true,
          constrained: false,
          onInteractionUpdate: (details) {
            print(details.localFocalPoint.toString());
          },
          child: Table(
            columnWidths: <int, TableColumnWidth>{
              for (int column = 0; column < _columnCount; column++)
                column: const FixedColumnWidth(300.0),
            },
            children: <TableRow>[
              for (int row = 0; row < _rowCount; row++)
                TableRow(
                  children: <Widget>[
                    for (int column = 0; column < _columnCount; column++)
                      Container(
                          child: _text
                              ? Text("Column: $_columnCount\nRow: $_rowCount")
                              : null,
                          height: 100,
                          color: _color
                              ? row % 2 + column % 2 == 1
                                  ? Colors.red.withOpacity(0.5)
                                  : Colors.green.withOpacity(0.5)
                              : null),
                  ],
                ),
            ],
          )),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.205, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.205 at C:\src\flutter
    • Framework revision 0220c3585c (24 hours ago), 2020-09-16 23:13:05 +0800
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\Miche\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

```

</details>

**Comment by justinmc** [comment]
@MichealReed Thanks for the clear issue.  I've got a fix coming in https://github.com/flutter/flutter/pull/66065.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Mac OS X 10.15.4 19E2269 x86_64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)

• No issues found!

```

</details>

<img width="1201" alt="Screenshot 2020-09-18 at 12 18 07 PM" src="https://user-images.githubusercontent.com/67046386/93565556-30b24480-f9a9-11ea-8b75-ee988ae2ca4c.png">

**Comment by MichealReed** [comment]
@justinmc seems this is being caused by something else, updated on my end and scrolling still provides (0,0).

**Comment by justinmc** [comment]
Hmm I just tried it on Chrome on a Mac and it's never giving me 0,0.  By scrolling, you just mean vertically scrolling the mousewheel right? I wonder if I'm not reproducing it correctly.

**Comment by MichealReed** [comment]
You are correct in that it no longer provides (0,0), I was mistaken. The behavior is different on the beta channel though and unconstrained coordinates are given versus coordinates constrained by the viewport's dimensions. It seems now, the update only provides coordinates within the constrains regardless of the state of the bool.

**Comment by MichealReed** [comment]
You are correct in that it no longer provides (0,0), I was mistaken. The behavior is different on the beta channel though and unconstrained coordinates are given versus coordinates constrained by the viewport's dimensions. It seems now, the update only provides coordinates within the constraints regardless of the state of the bool. @justinmc

**Comment by MichealReed** [comment]
Seems it may be more a matter of the localFocalPoint no longer providing proper coordinates. Before, even if your InteractiveViewer was larger than your screen, it would provide coordinates beyond the screen max. Now it provides the same value as the non-local version.

**Comment by justinmc** [comment]
I recently made a change to focalPoint and localFocalPoint in https://github.com/flutter/flutter/pull/66065.  Now they should always be normal Flutter coordinates.  If you want scene coordinates you can use [transformationController.toScene](https://master-api.flutter.dev/flutter/widgets/TransformationController/toScene.html).

Sorry for the confusion, I'm still trying to figure out how all this should work.  I think this should be the most flexible, but let me know if that doesn't cover your use case.

**Comment by MichealReed** [comment]
It might make sense for the localFocalPoint to use the local widget's coordinates and focalPoint to provide flutter coordinates. With them being matched at this time, local provides little value, an this would be inline with other widgets. If I put a container larger than the window in my app, local hit test coordinates will be in line with the widget's size and global hit tests will return coordinates within the bound of the window.

**Comment by justinmc** [comment]
I think there are three distinct coordinate systems that all may be useful.  Let me know what you think of this example:

The pink square is the InteractiveViewer, and the checkered square is its child.

<img width="400" src="https://user-images.githubusercontent.com/389558/94489970-5c4be080-019a-11eb-91cd-04033d40f0c7.png" />

As it is now, focalPoint is global, so it's relative to the top left corner of the screen.  localFocalPoint is relative to the top left corner of the InteractiveViewer.  The scene coordinates (achieved with toScene) are relative to the top left corner of the child and include its transformation (so for example the bottom right corner of the child is always at the same scene coordinates, even though the child may be moved around and scaled).

If we changed it so that localFocalPoint actually contained scene coordinates, then it might be hard to determine things like where the InteractiveViewer is on the page.  Also, I think that if you wrap a Transform widget in a GestureDetector widget, focalPoint and localFocalPoint with behave consistently with how InteractiveViewer is now.  And it's always possible to get scene coordinates with toScene.
