### ISSUE TITLE
hotReloadVMReloadMilliseconds hot_mode_dev_cycle_macos_target__benchmark unit regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66038]
https://flutter-flutter-perf.skia.org/e/?begin=1600280522&end=1600303326&keys=Xba25ef7f44f73f21cf9a689250c8ee38&num_commits=50&request_type=1&xbaroffset=21499.

Increasing, and continuing to go up.

**Comment by kf6gpe** [comment]
Wondering if this is actually expected given the PR in question.

**Comment by kf6gpe** [comment]
https://github.com/flutter/flutter/pull/65900 for the suspect commit.

**Comment by HansMuller** [comment]
The benchmark regression could very well be related to https://github.com/flutter/flutter/pull/65900 since the new button classes have added dependencies and the old button classes are still around (for the moment).

**Comment by liyuqian** [comment]
The same commit https://github.com/flutter/flutter/commit/a17b3309807a2fadabf4482d2705edc841f5fcfa seems to also break our memory measurements: [it's now always 0][1]. CC @bkonyi @terrylucas 

[1]: https://flutter-flutter-perf.skia.org/e/?begin=1600280522&end=1600303326&keys=Xd016f0b5cc777a55e96c6729137a36dc&num_commits=50&request_type=1&xbaroffset=21499

**Comment by bkonyi** [comment]
There's an issue with https://github.com/flutter/flutter/commit/a17b3309807a2fadabf4482d2705edc841f5fcfa where VM service clients aren't notified of the registered service extensions when subscribing to the `Service` event stream. I have a fix almost ready for review in the SDK, and I'll upload the new DDS version after that's done. If we can avoid reverting this, that would be great.

**Comment by bkonyi** [comment]
DDS fix up [here](https://dart-review.googlesource.com/c/sdk/+/163263).
