### ISSUE TITLE
mac-20, mac-3 machines need recovery

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66033]
Both iOS devices are failing tests that are otherwise passing locally. Unexpected exit code 1005 usually means the device is out of memory. Unclear what is happening with the cull perf test either.

**Comment by godofredoc** [comment]
If the phone is out of memory rebooting the phone may be enough. I'll verify the logs and reboot phones

**Comment by godofredoc** [comment]
From mac-20 seems like the problem is different:

```
2020-09-17T11:48:23.648849: INFO [task runner] [hot_mode_dev_cycle_macos_target__benchmark] stderr: [   +7 ms] Warning: CocoaPods not installed. Skipping pod install.
stderr:              CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
stderr:              Without CocoaPods, plugins will not work on iOS or macOS.
stderr:              For more info, see https://flutter.dev/platform-plugins
stderr:            To install:
stderr:              sudo gem install cocoapods
stderr:

2020-09-17T11:48:35.416896: INFO [task runner] [hot_mode_dev_cycle_macos_target__benchmark] stderr: [+11768 ms] Exception: CocoaPods not installed or not in valid state.
```

**Comment by godofredoc** [comment]
Phones were cleaned and rebooted and the host machines rebooted. Please let me know if the problem persists.

**Comment by godofredoc** [comment]
Mac 20 references cocoapods which should be only used in mac ios, we need to investigate
