### ISSUE TITLE
Input reopens keyboard after user interacts with a form element other than Input

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6603]
1. Create a simple form with a dropdown button and an Input.
2. Tap on input, keyboard appears.
3. Close the keyboard.
4. Open up the dropdown and select something.
5. As the dropdown closes, Input regains focus and opens the keyboard automatically.

I don't mind Input keeping the focus since dropdown isn't a focusable element (typically) but it should not reopen the keyboard. Keyboard should only open when the input element is tapped.

**Comment by eseidelGoogle** [comment]
Matt is probably the right place to start.

**Comment by Hixie** [comment]
This is tricky. It means we have to distinguish gaining the focus because the user tapped on it or hit "next" or whatever, and gaining the focus because the focus scope changed.
