### ISSUE TITLE
flutter-dashboard bot doesn't remove "work in progress; do not review" label when PR marked as ready to review

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66047]
The bot marks draft PRs as "work in progress; do not review", but doesn't remove the label when the PR is no longer a draft.  This causes PRs to be ignored when the author doesn't have permission to remove the label themselves.

See https://github.com/flutter/flutter/pull/65768#issuecomment-694147787 for example.

**Comment by knaeckeKami** [comment]
I think this is a dupe of https://github.com/flutter/flutter/issues/63210

**Comment by jmagman** [comment]
Surely is, thanks @knaeckeKami.
