### ISSUE TITLE
cull_opacity_perf__timeline_summary timing out

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66046]
cull_opacity_perf__timeline_summary started timing out with https://github.com/flutter/flutter/pull/65044, but the [revert](https://github.com/flutter/flutter/commit/ea75ffc1ba8a0af33bdba352e733c2ba5fa11472) didn't fix it.
[cull_opacity_perf__timeline_summary_48ba488_2.log](https://github.com/flutter/flutter/files/5240887/cull_opacity_perf__timeline_summary_48ba488_2.log)

**Comment by jmagman** [comment]
Failing on mac-20 and mac-21

**Comment by jonahwilliams** [comment]
@jmagman different revert, we could try with  #65044 but when I ran locally it passed

**Comment by jmagman** [comment]
Ah, https://github.com/flutter/flutter/commit/ea75ffc1ba8a0af33bdba352e733c2ba5fa11472 wasn't merged.

**Comment by jmagman** [comment]
Passed on revert https://github.com/flutter/flutter/pull/66051
