### ISSUE TITLE
Standardize labelling among input widgets

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6604]
Complex forms contain many types of input elements (checkboxes, dropdowns, pickers). It is difficult to use a consistent input labeling mechanism approved by Material. Take a look at this for instance:

![image](https://cloud.githubusercontent.com/assets/6687929/19872348/809e11cc-9f76-11e6-9816-b39d80ed14ce.png)

The dropdown input labels "From" and "To" would match perfectly to what the input label will look like for "Location" once a value is entered. In reality, this would be a hack in the client app's code because Location's style and size is provided by the input widget while the "From"/"To" labels of the dropdowns are explicitly drawn by the app.

Leafy chose to fix this by disabling material labeling for all form elements and instead providing a consistent labeling mechanism. Unfortunately, this breaks when intrinsic padding is introduced. Examples:

- Top and bottom padding on Input
- Top and bottom padding on DropdownButton
- Start and end padding on Slider

It would be great if clients could specify the padding (if any) for these elements.

**Comment by eseidelGoogle** [comment]
@mpcomplete is mr. forms.

**Comment by mehmetf** [comment]
Another way to solve this is to standardize labeling across all form elements. That would be very neat and it would not require any workaround on the app side. That way, Input would require no change but things like Slider, Checkbox, DropdownButton would optionally take a "label" argument which would create a label similar to Input's label with the same font/padding/size.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/254 is another (long standing) issue about making associating a label with a control much easier.  There are a bunch of expected behaviors for associated labels which are hard to get right w/o framework help.

**Comment by HansMuller** [comment]
> The dropdown input labels "From" and "To" would match perfectly to what the input label will look like for "Location" once a value is entered. ...

I'm not entirely sure what you're getting at here.  I'm guessing that you want to be able to line up the baselines of the label and the dropdown's value?

![align](https://cloud.githubusercontent.com/assets/1377460/19986551/708e4206-a1d4-11e6-8db0-15bf232de3b7.png)

**Comment by Hixie** [comment]
Fixing #6421 would automatically fix this for the From and To fields here, right?

**Comment by Hixie** [comment]
I spoke with @mehmetf and he clarified that this bug is basically about making sure all the existing input controls (checkboxes, radio buttons, sliders, dropdowns, etc) can be used with the widget we create for #6421 in such a way that they all line up (i.e. removing any default padding in that case).

We could do this by having #6421's widget set some sort of inherited widget that controls whether or not to show default padding, or we could make it simpler and just remove the padding on existing widgets (slider in particular), or make it configurable.
