### ISSUE TITLE
Image Picker Freezes in Android when accessing OneDrive

### ISSUE THREAD

**Issue by sallypeters** [flutter/flutter#66040]
I have upgraded from 1.12.13+Hotfix 5 to Flutter 1.19.0-4.3.pre and have 2 issues regarding ImagePicker 👍 

1) Using ImagePicker 0.6.7+7 within Android (Simulator/Device)- accessing an image on OneDrive causes ANDROID to freeze when there are many (> 500) photos.

Accessing any other image on the local device or GoogleDrive etc works without issue.

On 1.12.13 with Image Picker  0.6.1+4 works without issue - even when there are > 500 photos.

2) Creating a brand new ONEDRIVE Account and having just 10 (MAX) photos to choose from causes ImagePicker to return null for PickedFile, i.e : 
```

var image = await _imagePicker.getImage(source: ImageSource.gallery);
        if (image == null) {
          return;
        }
```

image will be null here when trying to access a ONEDRIVE source.

Both issues only happen in ANDROID.

**Comment by hamdikahloun** [comment]
Hi @sallypeters 
Can you upgrade your flutter version (`flutter upgrade`) please and provide your `flutter doctor -v`

**Comment by darshankawar** [comment]
Hi @sallypeters,
Please see [this](https://github.com/flutter/flutter/issues/47240#issuecomment-628746750) comment which mentions that we need to apply explicit permission to request external storage access.
Also see [this](https://github.com/flutter/flutter/issues/47240#issuecomment-628886393) comment that has link to the updated `readme` of the plugin.
Please check if you have applied required permissions per guidelines.

**Comment by sallypeters** [comment]
@hamdikahloun Unfortunately I cannot upgrade from 1.19 because  a) Plugins I use have not yet upgraded themselves to support the new PodFile format that came into effect with 1.20, b) Using any Cloud Firestore package (Auth, Firestore, Storage) requires significant time to fix the many deprecation issues resulting in the complete re-write of the Transaction code in Cloud Firestore., c) The re-write from invertase for the cloud firestore TX  API has issues which prevents us from upgrading.

@darshankawar As mentioned, have been using the image picker with 1.12.13 without this issue and as far back as Flutter 1.1.2. If permissions were an issue then it would fall over accessing Google based cloud resources (google drive). 

All appropriate permissions are in place for iOS and Android.

The issue is not permissions , security or anything else in terms of Podfile/Gradle configuration as other File plugins work seamlessly to access resources on cloud based platforms. The problem is with the image_picker plugin either not working properly in OneDrive or failing when there are lots of images for it to catalog as thumbnails ...

**Comment by darshankawar** [comment]
Hi @sallypeters 
I tried to load an image from one drive using Android 8.1.0 device on latest beta and was able to load it properly without any issues.

[66040.mp4.zip](https://github.com/flutter/flutter/files/5290541/66040.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (12 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```
Can you provide `flutter doctor -v` and `flutter run --verbose` when you get the freeze ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
