### ISSUE TITLE
Cannot listen for google assistant events when flutter fragment is active.

### ISSUE THREAD

**Issue by atomicfruitcake** [flutter/flutter#66042]
I have an Android application written in Java that loads a FlutterActivity to control a video player.

The app is for Android TV running Pie

Flutter version
```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (5 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

The output of my `flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/sambass/workspace/flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/sambass/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

The FlutterActivity is transparent and is used to control the underlying Java application via Method Channels and Event Channels.

The Java application contains a video player that can be controlled via Google Assistant voice commands. When I run the Android application without the FlutterActivity, the google assistant is able to control the video via callbacks. However, when I then load the transparent FlutterActivity that contains the player controls, the Google Assistant voice commands no longer control the video. I am still able to use MethodChannels to pause/play the video from the FlutterActivity.

Here is my VideoPlayer Fragment

```java
public class PlaybackVideoFragment extends VideoSupportFragment {

    private PlaybackTransportControlGlue<MyMediaPlayerAdapter> mTransportControlGlue;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final Video video = (Video) getActivity().getIntent().getSerializableExtra(DetailsActivity.VIDEO);
        VideoSupportFragmentGlueHost glueHost = new VideoSupportFragmentGlueHost(PlaybackVideoFragment.this);
        MyPlayerAdapter playerAdapter = MyPlayerAdapter.getInstance();
        playerAdapter.setRepeatAction(PlaybackControlsRow.RepeatAction.INDEX_NONE);
        mTransportControlGlue = new PlaybackTransportControlGlue<>(getContext(), playerAdapter);
        mTransportControlGlue.setHost(glueHost);
        mTransportControlGlue.setSeekEnabled(true);

        try {
            playerAdapter.setDataSource(Uri.parse(video.getVideoUrl()));
        } catch (IOException e) {
            e.printStackTrace();
        }
        mTransportControlGlue.addPlayerCallback(
            new PlaybackGlue.PlayerCallback(){
                @Override
                public void onPlayStateChanged(PlaybackGlue glue) {
                super.onPlayStateChanged(glue);
                boolean glueIsPlaying  = glue.isPlaying();
                    if(glueIsPlaying) {
                        playerAdapter.play();
                    } else {
                        playerAdapter.pause();
                    }
                }
            });
        
    }

}
```
This works as expected. However, if I add the following to the end of the `onCreate` functions,
```java
startActivity(
            FlutterActivity
                .withCachedEngine("my_flutter_engine_id")
                .backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent)
                .build(requireContext())
        );
```

I have the flutter activity stored as part of the application in my AndroidManifest.xml
```xml
        <activity
            android:name=".FlutterHost"
            android:label="@string/app_title_flutter"
            android:theme="@style/Theme.Transparent"/>
        <activity
```

The FlutterActivity will load and control the video, but Google Assistant will no longer listen for callbacks

## Steps to Reproduce

1. Run `git clone https://github.com/atomicfruitcake/atvFlutterExample`
2. Run `git clone https://github.com/atomicfruitcake/atvFlutterExampleActivity`
3. Run `cd atvFlutterExampleActivity && flutter pub get`
4. Load the atvFlutterExample into Android Studio.
5. Run the application, select a video and select 'Watch Now'
6. Attempt to pause/play the video with google Assisstant

## Expected results:
Saying 'OK Google, play video' or 'OK Google, pause video' will control the video

## Actual results
Saying 'OK Google, play video' or 'OK Google, pause video' will no longer work

I am aware this sounds like purely an android issue, however I have asked the Android team and was told to raise the issue here

**Comment by TahaTesser** [comment]
Hi @atomicfruitcake 

Can you please try on the latest `stable` channel 
Can you please provide your `flutter doctor -v` with the upgrade,  a complete reproducible minimal code sample in a GitHub repository to better address the issue 

Thank you

**Comment by atomicfruitcake** [comment]
@TahaTesser I have created two example repositories (1 for the Java side, 1 for the flutter side), that can run together to give a reproducible example. I have also added the instructions to use these on the description. 

Thanks

**Comment by TahaTesser** [comment]
Hi @atomicfruitcake 
Is this just happening on  Android TV? 
Your code sample has a lot of error in the module when running, can you please simplify your code sample into minimal code, not a production code
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
