### ISSUE TITLE
ShellTest.SkipAndSubmitFrame is flaky

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#66056]
Saw this fail on the Linux Host Engine `host_release` build today:
```
[ RUN      ] ShellTest.SkipAndSubmitFrame
../../flutter/shell/common/shell_unittests.cc:1039: Failure
Expected equality of these values:
  1
  external_view_embedder->GetSubmittedFrameCount()
    Which is: 2
```

Build: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/6861
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868899425341347024/+/steps/Host_Tests_for_host_release/0/stdout

Test binary in question: `shell_unittests`

**Comment by gw280** [comment]
two more test failures, time to disable as flakey:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868875468653826128/+/steps/Host_Tests_for_host_release/0/stdout
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868877029483924096/+/steps/Host_Tests_for_host_profile/0/stdout

**Comment by blasten** [comment]
I was having trouble reproducing it after 30 min, but I haven't had a chance to look into this in more details.

**Comment by chinmaygarde** [comment]
There are data races in `ShellTestExternalViewEmbedder` as investigated in https://github.com/flutter/flutter/issues/68371#issuecomment-710745061. Since we are seeing this in multiple tests, I am bumping up the priority. Will see if I can fix it over the weekend.

**Comment by chinmaygarde** [comment]
Reducing the priority since this test is not blocking the tree right now. But the test does need to be reworked per the comment in the linked duplicate issue. @blasten I removed your assignment since it did not seem like you were actively working on this. Feel free to add back your assignment in case you were.

**Comment by chinmaygarde** [comment]
`ShellTest.DiscardLayerTreeOnResize` exhibits the same issue.

**Comment by cyanglaz** [comment]
When we re-enable this test, it is likely need to implement thread merging and adjust the submit frame counting just like what i did for |ShellTest.ResubmitFrame| in https://github.com/flutter/engine/pull/22372

@chinmaygarde https://github.com/flutter/engine/pull/22372 might cause the flakiness of ShellTest.DiscardLayerTreeOnResize.

I should have some bandwidth to investigate this issue next week if no one else has time. I'll grab it now and start working on it later. If anyone wants to work on it before next week, feel free to re-assign.
