### ISSUE TITLE
GestureDetector fails if its child is transformed

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#6606]
In the example below the gesture detector's onTap callback isn't called unless the transform line is commented out.

```
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.green[300]),
        width: 300.0,
        height: 400.0,
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            new GestureDetector(
              onTap: () { print(' onTap() '); },
              child: new Container(
                width: 50.0,
                height: 100.0,
                decoration: new BoxDecoration(backgroundColor: Colors.purple[300]),
                transform: new Matrix4.identity()..translate(100.0, 200.0), // !!!
              ),
            ),
          ],
        ),
      )
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new Home()));
}
```

**Comment by Hixie** [comment]
Why is this surprising? The transform is applied to the hit-testing as well, but it transforms the box into the overflow of the container, so the parent doesn't think you're hitting it and so doesn't check the children.

**Comment by HansMuller** [comment]
In this case the child stays within the parent. 

I will track down the source of the problem.

**Comment by HansMuller** [comment]
We've decided this is working as it should.  See: https://github.com/flutter/flutter/pull/6663

**Comment by ArtfulDodgerB92** [comment]
This cannot possibly be "working as it should" because it doesn't work.    If you transform a button to a new location it is precisely because you require the button to be tappable at this new location.  Not from the blank space it originated from.   What a ridiculous thing to say.

**Comment by ZatacaSystems** [comment]
Any news on this??

**Comment by arashbi** [comment]
This simply means that we cannot use gesture detector with a transformed widget.

**Comment by gadearaujo** [comment]
nothing yet?

**Comment by slightfoot** [comment]
> This simply means that we cannot use gesture detector with a transformed widget.

This does NOT mean that. It means that you have to move your transform up in your hierarchy such that the transformed position is not clipped by the parent layout dimensions.
