### ISSUE TITLE
Gray screen showing up when Double Tap an TextFormField In Ios Apps

### ISSUE THREAD

**Issue by darkmehmet** [flutter/flutter#66064]
In Ios when double tapping 2 times (4 taps) to a TextFormField, App become irresponsible and Gray screen is showing up.
Here is screen shots
Before:
https://ibb.co/6N8mdqV

After:
https://ibb.co/Ny33cfS

```
Flutter Doctor Log:
`flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale tr-TR)
    • Flutter version 1.20.3 at /Users/mehmet/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mehmet/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mehmet/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mehmet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Mehmet (mobile) • *****************(private info)********************** • ios • iOS 12.4.7

• No issues found!`
```

**Comment by jacksonw765** [comment]
Are you running in release mode?

**Comment by darkmehmet** [comment]
@jacksonw765 Yes. Actualy it open this issue because Appstore reject app for this reason. I don't know that issue until they told me. I tried in my iPad I got same result.

**Comment by jacksonw765** [comment]
A grey screen like this is the result of an error in flutter that's being rendered. If you run in debug mode it will throw the error and show a red screen with a line number. Are you able to run the application in debug mode?

**Comment by darshankawar** [comment]
Hi @darkmehmet,
I am unable to replicate the issue with given code sample, in both, debug and release mode. 
Double tapping on textformfield, keeps the field responsive and I am able to input.


<img width="366" alt="Screenshot 2020-09-18 at 1 25 03 PM" src="https://user-images.githubusercontent.com/67046386/93572100-fcdc1c80-f9b2-11ea-8313-48618ab164a1.png">
<img width="354" alt="Screenshot 2020-09-18 at 1 26 52 PM" src="https://user-images.githubusercontent.com/67046386/93572118-01a0d080-f9b3-11ea-8936-276d2fa7d209.png">


Tested on iPhone SE simulator and on latest master.

<details>
<summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Mac OS X 10.15.4 19E2269 x86_64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by jacksonw765** [comment]
I am guessing there is some null value elsewhere in the code.

**Comment by darkmehmet** [comment]
Thanks for your kind help. I seems my issue related with localization -> https://github.com/flutter/flutter/issues/13452 . I fix proglem from here.

**Comment by eerbee** [comment]
i have same problem and fixed on https://github.com/flutter/flutter/issues/70767

**Comment by amerwarlus** [comment]
In my case this only happens when using MaterialApp localizationsDelegates.
The bug appears when using a language other than english, and double tapping an input field (the device is probably trying to show the 'Paste' label above the input and failing to do so in the localized language.

To Solve add "GlobalCupertinoLocalizations.delegate" to your list of delegates in the MaterialApp widget.
localizationsDelegates: [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate <---- add this
            ],

**Comment by wijesijp** [comment]
I have the same problem.

By adding GlobalCupertinoLocalizations.delegate was able to fix this for English.

But when the locale is Japanese I am still getting this issue.

I have following in my main.dart file

```
locale: lang.appLocal,
          supportedLocales: [
            const Locale('ja', ''),
            const Locale('en', 'US'),
          ],
          localizationsDelegates: [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate
          ],
```
Is there a work around for this?
