### ISSUE TITLE
Cherry Pick request for Deprecate VelocityTracker default constructor and added VelocityTracker.withKind constructor 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66070]
The PR in question: https://github.com/flutter/flutter/pull/66043

We've gotten feedback that the VelocityTracker change was disruptive, though it did not break any of the flutter framework or customer tests. In order to make the change non-breaking, PointerDeviceKind parameter can be made optional.

Nevertheless, this parameter should be provided so that the existing touch handlers can use more accurate gestures on mouse/stylus inputs, so we can encourage this by deprecating the default constructor and pointing users towards the VelocityTracker.withKind constructor that takes a non-optional parameter

FYI @goderbauer

**Comment by pcsosinski** [comment]
marking the issue as 'closed' to pick up on the CP radar (closed issue w/ label)
