### ISSUE TITLE
Missing required parameter 'client_id' when do deploy to server

### ISSUE THREAD

**Issue by echomartha** [flutter/flutter#66077]
when i try run at local it can show like this
![image](https://user-images.githubusercontent.com/71472725/93539743-3ba6ae00-f984-11ea-908b-f0eebbc1ffc9.png)

and i try deploy to server , this is the message i've got, already change in Credentials page 

![image](https://user-images.githubusercontent.com/71472725/93539847-81fc0d00-f984-11ea-896a-b9a2783cca89.png)

**Comment by echomartha** [comment]
is there something i need change if i wanna deploy ?

**Comment by pedromassangocode** [comment]
Hi @echomartha 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
