### ISSUE TITLE
More dashboard avatar differentiation between authors

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66084]
Jonah and I keep merging back-to-back:
<img width="24" alt="Screen Shot 2020-09-17 at 6 17 22 PM" src="https://user-images.githubusercontent.com/682784/93544377-ce0e6980-f912-11ea-8e99-8753fb444827.png">

If we can't get the GitHub avatars back for some reason, maybe a larger color range?  Different shapes?  More letters of the handle?

\cc @Piinks who last played with this https://github.com/flutter/cocoon/pull/847

**Comment by jmagman** [comment]
Actually @goderbauer last played with it https://github.com/flutter/cocoon/pull/912

**Comment by goderbauer** [comment]
My last change gave different users different color even if they have the same initial letter, but I agree the difference could be bigger!

**Comment by jmagman** [comment]
Closing, https://github.com/flutter/cocoon/pull/946 is way better!
