### ISSUE TITLE
flutter_tools should handle `--target` and `--packages` specified in filesystem-scheme

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#66095]
When `--filesystem-scheme` and `--filesystem-root` are passed, we should be able to specify `--target` and `--packages` in the uri.

E.g. `--filesystem-scheme=root-poth --filesystem-root=some/path --target=root-path:///package/lib/main.dart --packages=root-path:///.packages`

This is supported in `flutter_frontend_server`.

Alternatively, flutter_tools could convert the paths to the uri before passing it to CFE.

Without this, the same file with different path representation (`root-path://` and `file://`) can't be hot reloaded.

Tentatively assigning to @jonahwilliams 

Context: b/168736267

**Comment by mehmetf** [comment]
Jonah, this _might_ be a critical request for hot reload stability in google3. I will spend some time in Q4 understanding the issues with hot reload in google3 which will make it clearer but I wanted to give you a heads up.

I know that it is not a quick fix but please do triage it and give us how costly this fix would be so we can help prioritize. Thanks!

**Comment by jonahwilliams** [comment]
I don't know how to interpret that something might be critical :) 

If this is important for stability, I can start working on it right away. I do want to warn about running code without an associated package though - that is going to lead to surprises when the language version changes

**Comment by mehmetf** [comment]
No need to start working on it. Let me put it another way: We are seeing some stability issues in google3 but we are not sure how much of it is caused by this issue. We need to investigate more.

`.packages` functionality works differently in g3.

**Comment by jonahwilliams** [comment]
> Alternatively, flutter_tools could convert the paths to the uri before passing it to CFE.

This is easy to add back - the tool used to support it but did not seem useful (i.e. no tests failed here on in g3 when i disabled it in favor of only package URI mapping).
