### ISSUE TITLE
Exception caught by rendering library 

### ISSUE THREAD

**Issue by JuriSalesski** [flutter/flutter#66099]
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1759 pos 16: 'constraints.hasBoundedHeight': is not true.
`Widget _getImages(List images) {
    if (images != null && images.length != 0) {
      return Expanded(
        flex: 1,
        child: ListView.builder( //The relevant error-causing widget was: 
  ListView
          scrollDirection: Axis.horizontal,
          shrinkWrap: true,
          itemCount: images.length, 
          itemBuilder: (context, index) {
            return SizedBox(
              height: 100,
              // width: ,
              child: Stack(
                overflow: Overflow.visible,
                children: [
                  Container(
                    margin: EdgeInsets.all(5),
                    padding: EdgeInsets.all(0),
                    child: Image.file(
                      images[index],
                      width: 110,
                      height: 80,
                    ),
                  ),
                  Positioned(
                    bottom: 10,
                    right: -10,
                    child: Opacity(
                      opacity: 0.75,
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(15),
                              topRight: Radius.circular(15),
                              bottomLeft: Radius.circular(15),
                              bottomRight: Radius.circular(15)),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.grey.withOpacity(0.5),
                              spreadRadius: 0,
                              blurRadius: 3,
                              offset:
                                  Offset(0, 3), // changes position of shadow
                            ),
                          ],
                        ),
                        child: CircleAvatar(
                          backgroundColor: blueDark,
                          radius: 15,
                          child: IconButton(
                            padding: EdgeInsets.zero,
                            icon: Icon(Icons.remove_circle_outline),
                            color: golden1,
                            onPressed: () {},
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      );
    } else {
      return Text("Keine Nachweise gewählt");
    }
  }`

**Comment by pedromassangocode** [comment]
Hi @JuriSalesski 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
