### ISSUE TITLE
gmail integration not working in release apk

### ISSUE THREAD

**Issue by kittugithubpandey** [flutter/flutter#66101]
gmail integration not working in release apk

**Comment by hamdikahloun** [comment]
Hi @kittugithubpandey 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Hi @kittugithubpandey 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
