### ISSUE TITLE
Error with 'package:flutter/src/widgets/binding.dart':

### ISSUE THREAD

**Issue by Irewoleo** [flutter/flutter#66105]
'package:flutter/src/widgets/binding.dart': Failed assertion: line 1251 pos 14: '_child != null': is not true.

**Comment by pedromassangocode** [comment]
Hi @Irewoleo 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
