### ISSUE TITLE
keyboard system return key bug

### ISSUE THREAD

**Issue by pbaradziej** [flutter/flutter#66110]
After flutter upgrade, hiding keyboard doesnt work on TextFields when using system return key, checked on 6 different phone models, and different applications

[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.19041.388], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)

**Comment by pedromassangocode** [comment]
Hi @pbaradziej 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pbaradziej** [comment]
flutter doctor -v
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.19041.388], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

flutter run --verbose
[ +124 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +91 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[        ] executing: [C:\src\flutter/] git tag --points-at HEAD
[  +55 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.1.pre
[   +9 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +79 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[   +6 ms] C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +300 ms] Generating C:\Users\pba\AndroidStudioProjects\tests\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +22 ms] ro.hardware = ranchu
[  +26 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +21 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +5 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +6 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\pba\AppData\Local\Temp\flutter_tools.b6c9e27d\flutter_tool.1536574d\app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +13 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +36 ms] Exit code 0 from: C:\Users\pba\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="test.tests" (Raw: "test.tests")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="tests" (Raw: "tests")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="test.tests.MainActivity" (Raw: "test.tests.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +65 ms] Exit code 0 from: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           09-18 13:27:25.892 I/LatinIME( 8470): Starting input. Cursor position = 0,0
[   +1 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +58 ms] Exit code 0 from: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           09-18 13:27:25.892 I/LatinIME( 8470): Starting input. Cursor position = 0,0
[  +67 ms] <- compile package:tests/main.dart
[  +25 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +57 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +64 ms] Building APK
[  +19 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from C:\Users\pba\AndroidStudioProjects\tests\android\gradlew.bat.
[   +1 ms] C:\Users\pba\AndroidStudioProjects\tests\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +123 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +3 ms] executing: [C:\Users\pba\AndroidStudioProjects\tests\android/] C:\Users\pba\AndroidStudioProjects\tests\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\pba\AndroidStudioProjects\tests\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3926 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +111 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +84 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +31 ms] [        ] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[  +26 ms] [        ] executing: [C:\src\flutter/] git tag --points-at HEAD
[        ] [  +59 ms] Exit code 0 from: git tag --points-at HEAD
[        ] [        ] 1.22.0-12.1.pre
[        ] [   +9 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[        ] [  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [  +80 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +61 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +75 ms] Initializing file store
[        ] [  +16 ms] Skipping target: gen_localizations
[        ] [   +7 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +25 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --no-link-platform --packages C:\Users\pba\AndroidStudioProjects\tests\.packages --output-dill C:\Users\pba\AndroidStudioProjects\tests\.dart_tool\flutter_build\c29de57aba542d56cf1d3f7db4d5c2a6\app.dill --depfile
C:\Users\pba\AndroidStudioProjects\tests\.dart_tool\flutter_build\c29de57aba542d56cf1d3f7db4d5c2a6\kernel_snapshot.d package:tests/main.dart
[+7931 ms] [+8359 ms] kernel_snapshot: Complete
[ +697 ms] [ +672 ms] debug_android_application: Starting due to {}
[ +190 ms] [ +166 ms] debug_android_application: Complete
[ +812 ms] [ +854 ms] Persisting file store
[   +1 ms] [   +9 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [  +12 ms] "flutter assemble" took 10 282ms.
[        ] [   +3 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[  +91 ms] [        ] Shutdown hooks complete
[   +1 ms] [        ] exiting with code 0
[ +300 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +616 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +6 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +121 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +102 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +14 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[  +30 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +1 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +15 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +8 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[  +56 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[+1293 ms] > Task :app:packageDebug
[  +85 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 16s
[        ] 31 actionable tasks: 6 executed, 25 up-to-date
[ +571 ms] Running Gradle task 'assembleDebug'... (completed in 17,1s)
[+1605 ms] calculateSha: LocalDirectory: 'C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk'/app.apk
[  +37 ms] calculateSha: reading file took 36us
[ +439 ms] calculateSha: computing sha took 438us
[   +5 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +43 ms] Exit code 0 from: C:\Users\pba\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="test.tests" (Raw: "test.tests")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="tests" (Raw: "tests")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="test.tests.MainActivity" (Raw: "test.tests.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +1 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop test.tests
[+1374 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages test.tests
[ +906 ms] package:test.tests
                    package:com.android.smoketest.tests
[   +2 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat /data/local/tmp/sky.test.tests.sha1
[  +44 ms] 81627d2af8dfd63c670c9652d79643088f9c0ee9
[   +1 ms] Installing APK.
[   +1 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +33 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe
[        ] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +34 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r C:\Users\pba\AndroidStudioProjects\tests\build\app\outputs\flutter-apk\app.apk
[+4180 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 4,2s)
[   +1 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell echo -n 4c076f3dfba696ab1383a8a4001d0a23e078ea1f > /data/local/tmp/sky.test.tests.sha1
[  +78 ms] Android SDK built for x86 startApp
[   +3 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true test.tests/test.tests.MainActivity
[+1091 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=test.tests/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1980 ms] Observatory URL on device: http://127.0.0.1:34962/5PeN7rVAkTY=/
[   +2 ms] executing: C:\Users\pba\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:34962
[  +57 ms] 50292
[   +1 ms] Forwarded host port 50292 to device port 34962 for Observatory
[   +9 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:50292/5PeN7rVAkTY=/
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[ +446 ms] Successfully connected to service protocol: http://127.0.0.1:50292/5PeN7rVAkTY=/
[        ] Waiting for Android SDK built for x86 to report its views...
[   +7 ms] Waiting for Android SDK built for x86 to report its views... (completed in 6ms)
[  +12 ms] DevFS: Creating new filesystem on the device (null)
[  +43 ms] DevFS: Created new filesystem on the device (file:///data/user/0/test.tests/code_cache/testsVJVNDH/tests/)
[   +1 ms] Updating assets
[  +94 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:tests/main.dart b13c7caf-d1b6-43d9-ba5c-d0c919513f7d
[        ] <- b13c7caf-d1b6-43d9-ba5c-d0c919513f7d
[   +2 ms] I/Choreographer(12441): Skipped 49 frames!  The application may be doing too much work on its main thread.
[        ] D/EGL_emulation(12441): eglMakeCurrent: 0x9f5853c0: ver 2 0 (tinfo 0x9f5f6a60)
[ +400 ms] D/EGL_emulation(12441): eglMakeCurrent: 0x9adbb540: ver 2 0 (tinfo 0x9f5f69c0)
[ +994 ms] Updating files
[ +295 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 1 702ms)
[   +1 ms] Synced 1.8MB.
[   +1 ms] <- accept
[  +50 ms] Connected to _flutterView/0x9ad54410.


import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Column(
          children: [
            TextField(

            ),
            TextFormField(

            )
          ],
        ),

      ),
    );
  }
}

After running, when clicking textfield i use system return key the keyboard doesnt close, when clicking on submit button it works normally

**Comment by pcqpcq** [comment]
same with this.

---

```shell
 flutter doctor -v
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.0-12.1.pre at /Users/pcqpcq/Documents/flutter_sdk
    • Framework revision 8b3760638a (5 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/pcqpcq/Documents/android_sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,LOCALHOST
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Redmi Note 5A (mobile) • c5e0e049 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
```

---
 
BTW, when press `done` button, the keyboard can be hidden.

**Comment by TahaTesser** [comment]
Hi @pbaradziej 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
