### ISSUE TITLE
[url_launcher] plugin should use MessageUI on iOS for mailto: URLs

### ISSUE THREAD

**Issue by ghowen** [flutter/flutter#66120]
## Use case
 the
When launching a `mailto:` URL with the url_launcher plugin on iOS, the user leaves the Flutter app when mail app opens with a new email. It would be more elegant and beneficial to both the user and the developer if the url_launcher would use the MessageUI API (https://developer.apple.com/documentation/messageui) which opens an in app mail composer. This way the user finds himself back in the Flutter app after sending or cancelling his email message.

## Proposal

Either add an option to url_launcher to launch in the mail app or an in app message composer or use the in app message composer as default (as this is probably what 99% of the Flutter devs want anyways).

**Comment by stuartmorgan** [comment]
Closing as out of scope for `url_launcher`; it's intended as a general purpose launcher. Specialized UI for specific use cases should be done via plugins targeting those use cases.
