### ISSUE TITLE
ExpansionPanel customization

### ISSUE THREAD

**Issue by nickolight** [flutter/flutter#66121]
Hello.

I use `ExpansionPanelList` for my project and I found that widget very useful. But I faced with the issue of customization `ExpansionPanel`.
Could you add an opportunity to configure `ExpandIcon` for a developer? Or even an opportunity to remove it?

**Comment by TahaTesser** [comment]
Hi @nickolight 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/32802
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
