### ISSUE TITLE
worst_frame_build_time_millis 	cubic_bezier_perf__e2e_summary regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66130]
https://flutter-flutter-perf.skia.org/e/?begin=1600207024&end=1600291175&keys=X197f56aeb2671ed26940c2a2de56e74d&num_commits=50&request_type=1&xbaroffset=21489.

Looks like this commit: https://github.com/flutter/flutter/pull/65900. I suspect given the commit that this is expected?

/cc @HansMuller

**Comment by HansMuller** [comment]
The change in  #65900 doesn't change the benchmarks, just the button that's used to start the benchmarks.

**Comment by liyuqian** [comment]
@HansMuller : yes, it probably include some button animations (e.g., ripple) as we want to include the first frame when the actual bezier curve animation started. So is it expected to increase the worst frame build time of a button animation from ~8ms to ~15ms when we change from `RaisedButton` to `ElevatedButton`?

**Comment by HansMuller** [comment]
OK, yes, ElevatedButton's elevation changing animation can take an additional frame to avoid an old problem with rendering the shadow that goes with the press/release elevation change.

**Comment by liyuqian** [comment]
Cool, I'll then close this as an expected regression.
