### ISSUE TITLE
Engine roll is blocked by warning from transitive dep source_span

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66132]
```
../../cache/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0-nullsafety/lib/src/highlighter.dart:327:17: Warning: Operand of null-aware operation '!' has type '_Highlight' which excludes null.
 - '_Highlight' is from 'package:source_span/src/highlighter.dart' ('../../cache/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0-nullsafety/lib/src/highlighter.dart').
                highlight!.isPrimary ? _primaryColor : _secondaryColor;
```

This is blocking the engine roller and the Flutter repo no longer has clean analysis. There was a work around committed that hasn't been published yet: https://www.google.com/url?sa=j&url=https%3A%2F%2Fgithub.com%2Fdart-lang%2Fsource_span%2Fpull%2F59&uct=1596224968&usg=CwlxcZOEnRpg06Yh_b2srZmah5w.&source=chat

**Comment by jonahwilliams** [comment]
@stereotype441 @jakemac53

**Comment by gw280** [comment]
Re-opening as this is still blocking the roll: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868774790334430080/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_misc/0/stdout

**Comment by gw280** [comment]
Oh, I think this might be that the roller is stuck from a few days ago. Will investigate further, closing for now.
