### ISSUE TITLE
[in_app_purchase] invalid doc in section "Making a purchase"

### ISSUE THREAD

**Issue by erf** [flutter/flutter#66138]
In `README.md` file of the `in_app_purchase` plugin, in the section **Making a purchase** there is the following comment:

```
final ProductDetails productDetails = ... // Saved earlier from queryPastPurchases().
```

The comment i believe is wrong and should state that the `ProductDetails` is coming from a call to `queryProductDetails`.

You also state that both storefronts (App Store and Google Play i presume) handles consumables and non-consumables differantly, and then you tell the user to

> make a distinction here and call the right purchase method

It kind of sounds like you need to make a choice based on storefront, but you only make a choice based on your type of IAP right?

**Comment by stuartmorgan** [comment]
This was fixed in the documentation overhaul for 1.0.
