### ISSUE TITLE
Engine tree red due to Mac infra failure

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#66133]
Example: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Android%20AOT%20Engine/6856

**Comment by digiter** [comment]
Triage: we were out of quota in prod. This is likely going to be fixed next week.

**Comment by godofredoc** [comment]
Turns out this is not because of the GoB quota, we need to checks for OOM in the mac machines and we also need to check for multiple browser process

**Comment by godofredoc** [comment]
This will be transformed to a KR in one of the infra engine OKRs as we haven't been able to identify the problem but it still is a major source of tree closures.

**Comment by digiter** [comment]
Moving out of infra ticket queue as this will take more than one day.

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/68322
