### ISSUE TITLE
complex_layout_scroll_perf_ios__timeline_summary flake, timeout in `setUpAll`, stuck on "This accessory may not be supported"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66153]
Timed out waiting for `FlutterDriver` to connect.
https://github.com/flutter/flutter/blob/c3217dac7fca317af138781e69c6f064038b9e03/dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart#L15-L17
```
2020-09-18T15:54:42.487883: stdout: [+714629 ms] 12:00 [32m+0[0m[31m -1[0m: scrolling performance test (setUpAll) [1m[31m[E][0m[0m
2020-09-18T15:54:42.488728: stdout: [   +1 ms]   TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
2020-09-18T15:54:42.502385: stdout: [  +13 ms]   package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
```
[complex_layout_scroll_perf_ios__timeline_summary_5c85803_2.log](https://github.com/flutter/flutter/files/5248588/complex_layout_scroll_perf_ios__timeline_summary_5c85803_2.log)

**Comment by jmagman** [comment]
I implemented screenshots for some timing out `drive` tests.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8852006777696044672/+/steps/run_complex_layout_scroll_perf_ios__timeline_summary/0/stdout

This one on `flutter-devicelab-mac-6` stuck on a dialog `This accessory may not be supported`.  That may mean the lightning cable is bad?

![drive_01](https://user-images.githubusercontent.com/682784/112084438-030bab00-8b46-11eb-998a-4add870f4404.png)

**Comment by godofredoc** [comment]
As this is a cable swap we'll need to schedule a lab visit.

**Comment by godofredoc** [comment]
Dialog was dismissed and phone reconnected with a different cable.
