### ISSUE TITLE
path_provider 1.6.16 causing "Invalid plugin specification" with older versions of Flutter

### ISSUE THREAD

**Issue by longravuth** [flutter/flutter#66158]
When trying to build Flutter application using the latest version of path_provider, the following error occurs

[   +4 ms] Found plugin path_provider at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.16/
[        ] Found plugin path_provider_linux at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[   +1 ms] Found plugin path_provider_windows at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.2/
[   +4 ms] "flutter get" took 12,611ms.
Invalid plugin specification.
Invalid "windows" plugin specification.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:77:7)
#2      _pluginFromPubspec (package:flutter_tools/src/plugins.dart:282:17)
#3      findPlugins.<anonymous closure> (package:flutter_tools/src/plugins.dart:305:27)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#5      findPlugins (package:flutter_tools/src/plugins.dart:303:12)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:783:32)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:208:5)
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:130:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1465:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1465:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1502:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1465:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#43     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
#46     main (file:///home/ubuntu/flutter_infrastructure/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

It appears the new commit to support window (path_provider_windows) is the culprit.

**Comment by dsokolov-pfpt** [comment]
Temporary fix for those who experience this issue: in pubspec.yaml specify previous version by setting **path_provider: 1.16.14**

**Comment by stuartmorgan** [comment]
What version of Flutter are you using? I would not expect current stable to have this issue.

**Comment by ruaanmaraisklem** [comment]
> What version of Flutter are you using? I would not expect current stable to have this issue.

I'm obviously not OP but I was using v1.17.4 and experienced the same issue, upgraded to v1.20.4 now and getting a new error, but it's probably because you guys are working on this now

"New" error: Because no versions of path_provider_windows match 0.0.2 and no versions of path_provider_windows match >0.0.2 <0.1.0, path_provider_windows ^0.0.2 is forbidden.

**Comment by omgseven** [comment]
Same issues, my flutter version is v1.17.2 and not going to upgrade to v1.20.+(which I tried actually work fun).
finally,  I solved by changing path_provider version to fixed 1.6.14

`path_provider: ^1.6.14` => `path_provider: 1.6.14`

**Comment by stuartmorgan** [comment]
> Because no versions of path_provider_windows match 0.0.2

That sounds like a pub caching issue; 0.0.2 [was published](https://pub.dev/packages/path_provider_windows) before the version of `path_provider` that required it. I suspect if you tried again you wouldn't see that error.

**Comment by thassio-vinicius** [comment]
I'm having the same issue but I have no idea which package is causing this. All I get when I try running pub get is this:

`Invalid plugin specification.
Invalid "windows" plugin specification.
`

I tried removing the "^" sign from all my packages versions but its still not working. 

My Flutter Doctor: 

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.12.13+hotfix.9, on Microsoft Windows [versÃ£o 10.0.18362.1082], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.1)
[√] Connected device (4 available)

• No issues found!
`

**Comment by stuartmorgan** [comment]
> I'm having the same issue but I have no idea which package is causing this. All I get when I try running pub get [...]

`pub get` doesn't upgrade existing packages, due to the lockfile. If you are using `pub` directly, you want `pub upgrade`.

> I tried removing the "^" sign from all my packages versions but its still not working.

All this would do is prevent you from ever getting any bugfix updates to any of your direct dependencies, so I'm not sure why you would expect that to help. You should definitely not do that.

**Comment by thassio-vinicius** [comment]
> All this would do is prevent you from ever getting any bugfix updates to any of your direct dependencies, so I'm not sure why you would expect that to help. You should definitely not do that.

I tried this because it was a suggestion that worked for other people in the comments above lol

**Comment by stuartmorgan** [comment]
> I tried this because it was a suggestion that worked for other people in the comments above

The specific suggestion above was to pin path_provider to 1.6.14 (a version before the issue was introduced), not to arbitrarily pin all plugins to their current versions.

**Comment by thassio-vinicius** [comment]
> The specific suggestion above was to pin path_provider to 1.6.14 (a version before the issue was introduced), not to arbitrarily pin all plugins to their current versions.

Yes, and I did that because I said I didn't know which plugin was causing this issue for me. Are you done?
