### ISSUE TITLE
image_picker Camera activation leads to unresponsive webview_flutter 

### ISSUE THREAD

**Issue by joniaiuser** [flutter/flutter#66165]
## Steps to Reproduce

1. Use this sample project: https://github.com/joniaiuser/webviewbugrepro
2. Use actual iOS device (I used iOS 14 iPhone X, but might work on others too).
3. Run `flutter run`
4. The webview scrolling should work. Hot restart should work. Scrolling after hot restart should work.
5. Press Camera button. Then cancel.
6. Hot restart again.
7. Webview no longer responsive. Cannot scroll.

**This issue is also happening on our Production app without Hot Restart** 
[itms-apps://apps.apple.com/sg/app/joni-ai-5v5-moba-math/id1492657910](itms-apps://apps.apple.com/sg/app/joni-ai-5v5-moba-math/id1492657910)

**When we use a camera feature in the app, the webviews in the app are no longer responsive to touch/scrolling.**

We have had reports from users on Google Play Reviews citing non-scrollable webview as well so it might be linked and affect Android as well but cannot confirm at this stage.

**Expected results:** 
- Expected webview to be scrollable.
**Actual results:** 
- Webview is not scrollable.

`flutter run --verbose`: [https://gist.github.com/joniaiuser/28b80314de89510a8296349117b2ba26](https://gist.github.com/joniaiuser/28b80314de89510a8296349117b2ba26)

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 3.9s)
```

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-SG)
    • Flutter version 1.20.4 at /Users/joniaiuser/Developer/flutter
    • Framework revision fba99f6cf9 (4 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/joniaiuser/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • J’s Phone (mobile) • f82ca4c62c69f335f96fa40b2530343ba2dc0c16 • ios • iOS 14.0
    • iPhone 8 (mobile)  • DC2227DC-0F54-4E94-AB9F-DD49156BDA95     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details>

**Comment by joniaiuser** [comment]
Most likely from: https://github.com/flutter/engine/pull/20050

**Comment by darshankawar** [comment]
Hi @joniaiuser,
There's similar open issue describing your case, [65361](https://github.com/flutter/flutter/issues/65361) and seems to be happening with lot of plugins, not only with `webview_flutter`. Also, see [65927](https://github.com/flutter/flutter/issues/65927)
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
