### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios32 failing consistently even after revert where it started

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#66166]
flutter_gallery__transition_perf_e2e_ios32 started failing in https://github.com/flutter/flutter/commit/409e994cd03749d5a903f01cf4ec5b3ee074a2ee

and continued failing the same way even after that change was reverted https://github.com/flutter/flutter/commit/3e6863ab2bc5cd33b41646ec957969860af7d518

The tests are failing on losing the connection to the device. Normally this would look like an engine crasher, but there were no engine rolls in the range, and the test was consistently green beforehand. All of the attempts are running on mac-11. Maybe it needs a kick?

**Comment by keyonghan** [comment]
Manual intervention is needed to have the bot recovered after the recent power outage. @godofredoc what is our current process to physically recover our devicelab bots?

**Comment by zanderso** [comment]
@bkonyi

**Comment by keyonghan** [comment]
issue to track 32 device recovery: [link](https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=60335)

**Comment by keyonghan** [comment]
The phone is confirmed to be back ([link](https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=60335) marked as done)

**Comment by zanderso** [comment]
@jmagman Can we revert https://github.com/flutter/flutter/pull/66187 ?

**Comment by jmagman** [comment]
Yup! https://github.com/flutter/flutter/pull/66302
