### ISSUE TITLE
Add pigeon doc for using file configuration instead of invocation options

### ISSUE THREAD

**Issue by xster** [flutter/flutter#66168]
Add an example option showing how to use the `configurePigeon` function in the pigeon file instead of the invocation options.

**Comment by xster** [comment]
Would be even nicer if we can bring it into the pubspec.yaml @gaaclarke

**Comment by gnprice** [comment]
This appears to have been done. The package readme points to the example readme, which starts off with a `@ConfigurePigeon` example:
https://github.com/flutter/packages/blob/611aea1657fbfc0d2564a14b08e12dffc70189bb/packages/pigeon/example/README.md#invocation
