### ISSUE TITLE
Catalina devicelab tasks not running

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66160]
[smoke_catalina_start_up_ios](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/smoke_catalina_start_up_ios.dart) and [smoke_catalina_hot_mode_dev_cycle_ios__benchmark](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/smoke_catalina_hot_mode_dev_cycle_ios__benchmark.dart) last ran on https://github.com/flutter/flutter/commit/d26268bb9e6d713a73d6148da7fa75936d442741.  

Does the Catalina agent need a kick after the power outage?

**Comment by godofredoc** [comment]
Recovered mac-19, monitoring to see if it runs the catalina tests.

**Comment by godofredoc** [comment]
This bug requires manual intervention the get the test bed back. Will be scheduled for recovery on 09/21

**Comment by keyonghan** [comment]
Bot has been recovered.
