### ISSUE TITLE
pubspec.lock file changed after exec "flutter packages get"

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#66167]
flutter doctor -v:
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US)
    • Flutter version 1.21.0-9.1.pre at /usr/local/flutter
    • Framework revision be9bc8cb39 (5 weeks ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

pubspec.yaml:
dependencies:
   path_provider: ^1.6.11

pubspec.lock:
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.6.14"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.0.1+2"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.0.4+3"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.3"

run "flutter packages get":
pubspec.yaml:
dependencies:
   path_provider: ^1.6.11

pubspec.lock:
 path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.16"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4+4"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.2"

why pubspec.lock changed by that?

**Comment by iapicca** [comment]
@lyf571321556 your flutter beta version is obsolete, please run `flutter upgrade -f`

**Comment by Abhishek01039** [comment]
Hi @lyf571321556 
can you please provide more information about your issue and also provide the minimal reproduction code?
Thanks.
