### ISSUE TITLE
App for Mobile / Web

### ISSUE THREAD

**Issue by kamalkech** [flutter/flutter#66178]
1- flutter version : ```Flutter 1.22.0-12.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8b3760638a (3 days ago) • 2020-09-15 17:47:13 -0700
Engine • revision 4654fc6cf6
Tools • Dart 2.10.0 (build 2.10.0-110.3.beta)```

2- run :  ```flutter run -d chrome```

3- result : ```This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.
Launching lib\main.dart on Chrome in debug mode...
org-dartlang-app:/web_entrypoint.dart:9:8: Error: Error when reading 'lib/generated_plugin_registrant.dart': Le fichier spécifié est introuvable.

```
import 'package:netflix_responsive/generated_plugin_registrant.dart';
       ^
Syncing files to device Chrome...
org-dartlang-app:/web_entrypoint.dart:14:3: Error: Method not found: 'registerPlugins'.
  registerPlugins(webPluginRegistry);
  ^^^^^^^^^^^^^^^
Syncing files to device Chrome...                               25 845ms (!)
Failed to compile application.

C:\Projets\Flutter\netflix_responsive
λ flutter run -d chrome
This application is not configured to build on the web.
To add web support to a project, run flutter create .
Launching lib\main.dart on Chrome in debug mode...
org-dartlang-app:/web_entrypoint.dart:9:8: Error: Error when reading 'lib/generated_plugin_registrant.dart': Le fichier spécifié est introuvable.

import 'package:netflix_responsive/generated_plugin_registrant.dart';
       ^
Syncing files to device Chrome...
org-dartlang-app:/web_entrypoint.dart:14:3: Error: Method not found: 'registerPlugins'.
  registerPlugins(webPluginRegistry);
  ^^^^^^^^^^^^^^^
Syncing files to device Chrome...                               18 383ms (!)
Failed to compile application.`
`````

**any idea ??**

**Comment by jonahwilliams** [comment]
> This application is not configured to build on the web.
To add web support to a project, run flutter create .

**Comment by darshankawar** [comment]
Hi @kamalkech,
As the error suggests:

`To add web support to a project, run flutter create .`

Run `flutter create .` to enable web support to the app you are building.  Don't forget the `.` in the command.

Also see [this](https://flutter.dev/docs/get-started/web) link for more details.

I am going ahead and closing this, as this isn't an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by kamalkech** [comment]
@darshankawar 
1- upgrade flutter SDK
2- flutter create .
3- result : working successfully

thank u.
