### ISSUE TITLE
Failed to establish connection with the application instance in Chrome.

### ISSUE THREAD

**Issue by trearthor** [flutter/flutter#66174]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
Hi @trearthor 
can you please provide `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
Thanks.

**Comment by darshankawar** [comment]
Hi @trearthor,
Since, there's no description provided, I am assuming this issue is similar to [49482](https://github.com/flutter/flutter/issues/49482), based on the title.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
