### ISSUE TITLE
Invalid plugin specification path_provider_windows.

### ISSUE THREAD

**Issue by zhangyiyiisme** [flutter/flutter#66172]
Yesterday, the code is no problem, but today  run 'flutter pub get ',err info :Invalid plugin specification path_provider_windows.
Invalid "windows" plugin specification,what happened?my flutter sdk version is 1.17.3;My companion too;path_provider: ^1.5.0,but in fluttet sdk cache is path_provider: ^1.6.16?

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/66158
