### ISSUE TITLE
RichText splits text in multiline improperly

### ISSUE THREAD

**Issue by BigBrosh** [flutter/flutter#66179]
![image](https://user-images.githubusercontent.com/30599468/93667870-e35dd200-fa91-11ea-9bcf-effe82c53833.png)

As you can see there's enough of space on the second line but text is getting transferred on the next line
I'm expecting the text to fill the free space

You can open the codepen's link below and shrink screen's size to 360px
https://codepen.io/Big_Brosh/pen/PoNdMKz

**Comment by PixelToast** [comment]
This is intended behavior because you are using WidgetSpan instead of TextSpan.

Replacing `WidgetSpan` with `TextSpan` and using `Text.rich` instead of `RichText` gives us the desired result:

```dart

      body: SafeArea(
        child: Stack(
          children: <Widget>[
            Text.rich(
              TextSpan(
                children: [
                  TextSpan(text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport '),
                  TextSpan(text: 'ut ', style: TextStyle(fontWeight: FontWeight.bold)),
                  TextSpan(text: 'labore et dolore magna aliqua')
                ]
              )
            )
          ]
        )
      )
```

**Comment by BigBrosh** [comment]
I have widgets for typography (they return Text widget) inside my application so WidgetSpan can't be replaced

**Comment by BigBrosh** [comment]
> This is intended behavior because you are using WidgetSpan instead of TextSpan.
> 
> Replacing `WidgetSpan` with `TextSpan` and using `Text.rich` instead of `RichText` gives us the desired result:
> 
> ```dart
>       body: SafeArea(
>         child: Stack(
>           children: <Widget>[
>             Text.rich(
>               TextSpan(
>                 children: [
>                   TextSpan(text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport '),
>                   TextSpan(text: 'ut ', style: TextStyle(fontWeight: FontWeight.bold)),
>                   TextSpan(text: 'labore et dolore magna aliqua')
>                 ]
>               )
>             )
>           ]
>         )
>       )
> ```

I have widgets for typography (they return Text widget) inside my application so WidgetSpan can't be replaced

**Comment by BigBrosh** [comment]
As well if I change screen's size to 560px it renders correctly
So it's not intended behaviour
![image](https://user-images.githubusercontent.com/30599468/93706396-895f1a00-fb2e-11ea-9cc5-3242a6c085f9.png)

**Comment by PixelToast** [comment]
Widgets, including `Text` are rectangular and do not flow with spans, from a layout perspective these text widgets are just boxes that get wrapped separately.

Here you can see the bounding box of your original example with debug paints enabled:

![](https://i.tst.sh/DjIR3.gif)

They wrap no different than regular boxes:

![](https://i.tst.sh/1LBTF.gif)

I suggest not using widgets to define spans like this and instead generate TextSpans in your code, while not elegant this is definitely the expected behavior.

**Comment by darshankawar** [comment]
Hi @BigBrosh,
Please see @PixelToast's suggestion above and see if they resolve / answer your question.
Thanks.

**Comment by BigBrosh** [comment]
Hi @darshankawar 
I've got clarifications and going to add some textSpan getter for my typography factory
Thanks @PixelToast :)
