### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by Jlanglang** [flutter/flutter#66183]
Could not find an option named "androidx". Run 'flutter -h' (or 'flutter   -h') for available flutter commands and options

**Comment by hamdikahloun** [comment]
Hi @Jlanglang 

You use `flutter create newapp` command?
Can you provide please your `flutter doctor -v`

**Comment by Jlanglang** [comment]
> Hi @Jlanglang
> 
> You use `flutter create newapp` command?
> Can you provide please your `flutter doctor -v`

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.18362.1082],
    locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 3.5)
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Jlanglang** [comment]
> Hi @Jlanglang
> 
> You use `flutter create newapp` command?
> Can you provide please your `flutter doctor -v`

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)
    • Flutter version 1.2.1 at D:\flutter
    • Framework revision 8661d8aecd (1 year, 7 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Program Files\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Program Files\sdk
    • Java binary at: D:\Program Files\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\android-studio-ide-191.5977832-windows\android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\ideaIU-2019.3.4.win
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • sdk gphone x86 arm • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by hamdikahloun** [comment]
Can you upgrade to latest version please
`flutter upgrade`

**Comment by Jlanglang** [comment]
> Can you upgrade to latest version please with command `flutter upgrade` or By downloading from [Flutter website](https://flutter.dev/docs/get-started/install)
Thank .I'll try

**Comment by kherld-hussein** [comment]
> Can you upgrade to latest version please with command `flutter upgrade` or By downloading from [Flutter website](https://flutter.dev/docs/get-started/install)

Smart reply

**Comment by Jlanglang** [comment]
download llutter sDK V1.20.4 ,solve the problem
