### ISSUE TITLE
LazyBlock big scroll

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#6618]
Hello,

I use a LazyBlock to render different sizes chlidren.
Here the code (nothing special): 
main part of my children are 288.0 height. The first and the last one are 60.0 height. 

new LazyBlock(
      onScroll: _onscrolltest,
      delegate: new LazyBlockChildren(
        children: <Widget>[ ... mychildren...]
      )
)

With the last modifications, I can observe a weird behavior:
After scrolling to the bottom to render the invisible items, when I scroll to the top, there is a kind of jump  (big scroll). When I scroll to the bottom and I reach the previous new rendered items, the same "jump"  occurs.

I've had a scrollListener to log the scrolloffset, and I can see the "jump":
from top to bottom:

I/flutter : current scroll is 0 .0
I/flutter : current scroll is 9.635969523573563
I/flutter : current scroll is 11.302636190240248
I/flutter : current scroll is 12.969302856906877
I/flutter : current scroll is 14.635969523573563
I/flutter : current scroll is 16.30263619024025
I/flutter : current scroll is 17.96930285690688
I/flutter : current scroll is 19.96930285690688
I/flutter : current scroll is 21.96930285690688
I/flutter : current scroll is 24.30263619024025
I/flutter : current scroll is 26.30263619024025
I/flutter : current scroll is 28.30263619024025
I/flutter : current scroll is 30.30263619024025
I/flutter : current scroll is 32.30263619024025
I/flutter : current scroll is 33.96930285690688
I/flutter : current scroll is 35.635969523573564
I/flutter : current scroll is 37.30263619024025
I/flutter : current scroll is 38.96930285690688
I/flutter : current scroll is 40.635969523573564
I/flutter : current scroll is 42.635969523573564
I/flutter : current scroll is 44.635969523573564
I/flutter : current scroll is 46.30263619024025
I/flutter : current scroll is 47.96930285690688
I/flutter : current scroll is 49.635969523573564
I/flutter : current scroll is 50.96930285690688
I/flutter : current scroll is 52.96930285690688
I/flutter : current scroll is 54.635969523573564
I/flutter : current scroll is 56.30263619024025
I/flutter : current scroll is 57.96930285690688
I/flutter : current scroll is 59.635969523573564
I/flutter : current scroll is 61.96930285690688
I/flutter : current scroll is 64.30263619024025
I/flutter : current scroll is 66.63596952357356
I/flutter : current scroll is 68.96930285690688
I/flutter : current scroll is 71.63596952357356
I/flutter : current scroll is 74.30263619024025
I/flutter : current scroll is 76.63596952357356
I/flutter : current scroll is 79.63596952357356
I/flutter : current scroll is 81.96930285690688
I/flutter : current scroll is 84.63596952357356
I/flutter : current scroll is 87.63596952357356
I/flutter : current scroll is 90.96930285690688
I/flutter : current scroll is 93.96930285690688
I/flutter : current scroll is 97.30263619024025
I/flutter : current scroll is 100.63596952357356
I/flutter : current scroll is 103.96930285690688
I/flutter : current scroll is 107.63596952357356
I/flutter : current scroll is 111.96930285690688
I/flutter : current scroll is 116.30263619024025
I/flutter : current scroll is 121.96930285690688
I/flutter : current scroll is 127.96930285690688
I/flutter : current scroll is 135.30263619024026
I/flutter : current scroll is 142.63596952357358
I/flutter : current scroll is 152.30263619024026
I/flutter : current scroll is 163.63596952357358
I/flutter : current scroll is 178.30263619024026
I/flutter : current scroll is 188.9693028569069
I/flutter : current scroll is 201.30263619024026
I/flutter : current scroll is 231.05208978984604
I/flutter : current scroll is 259.42274453486687
I/flutter : current scroll is 286.68877543213125
I/flutter : current scroll is 312.5949136592942
I/flutter : current scroll is 360.85695969500046
-- beginning of the previously not visible items -- 
I/flutter : current scroll is 629.5285706966721
I/flutter : current scroll is 1208.739321638277
I/flutter : current scroll is 2240.5
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
I/flutter : current scroll is 1924.0
--bottom--

Thank you, Vincent

**Comment by eseidelGoogle** [comment]
@Hixie is in the middle of re-working our scrolling and would likely know what to expect here.

**Comment by lequem** [comment]
Ok thanks, I'm waiting for this update! 
Do you have a public roadmap about the flutter project and when will be available the first beta release?

Vincent

**Comment by eseidelGoogle** [comment]
@lequem all of our bugs are public, most are assigned to milestones.  The dates on those milestones are obviously inaccurately conservative (e.g. I think some are set for 2031), but you can get the general idea of the order we intend to do things.

**Comment by Hixie** [comment]
LazyBlock is gone. If we're lucky, this got resolved in the transition... but it's always possible it hasn't. Would you mind checking if you still see the problem with ListView, and if so, filing a new bug? If you could include a small test program that demonstrates the problem that would be great.

**Comment by lequem** [comment]
Ok, I will check and open a new issue if needed
