### ISSUE TITLE
Move health checks and autorecovery to bot_config

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66193]
This is required before moving the tests beds to LUCI to ensure tasks are using only test beds that are healthy. The bot config file is in the chrome configurations files.

For this we can decide on creating an independent tool, maybe in flutter/packages that runs health checks and force recovery bundled in a cipd package that can be downloded and used from the bot_config file or just embed the validations in bot_config file. 

- [x] Create health check tool in flutter/cocoon
- [x] Create pre-submit builder to test build process
- [x] Create salt state to provision bots with this tool from CIPD.
- [x] Update bot_config to apply this tool.
- [ ] Create and test the config in a staging pool first before in prod.

Part of https://github.com/flutter/flutter/issues/70635

**Comment by godofredoc** [comment]
@keyonghan can we close this bug?

**Comment by keyonghan** [comment]
> @keyonghan can we close this bug?

Not fully completed. Prefer to wait until we implement the cleanup section.

**Comment by godofredoc** [comment]
@keyonghan I believe the work outlined in this bug has been completed. Can we close this bug?
