### ISSUE TITLE
RichText textScaleFactor is ignored if the child TextSpan doesn't contain a TextStyle

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#66196]
## Steps to Reproduce
1. Run this dartpad [code sample](https://dartpad.dartlang.org/b65e7edd460d38507ff39162021030be)

**Expected results:** 
[RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) [textScaleFactor property](https://api.flutter.dev/flutter/widgets/RichText/textScaleFactor.html) should apply to his child [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html)

**Actual results:** 
[RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) [textScaleFactor property](https://api.flutter.dev/flutter/widgets/RichText/textScaleFactor.html) doesn't apply to his child [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html) unless [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) is declared
(try un-commenting the code as described in the sample)

I have no relevant logs to provide

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.269 at
      /home/francesco/development/flutter_master
    • Framework revision 51fa704642 (71 minutes ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

! Doctor found issues in 1 category.
```

</details>

please consider this [PR](https://github.com/flutter/flutter/pull/66197) to fix the issue

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Deepti 's iPhone (mobile) • 0554e90e563e81fd41bfd2ff9a2c6960595b9825 • ios
      • iOS 12.4.5

• No issues found!

```

</details>

![66196_w_style](https://user-images.githubusercontent.com/67046386/93743651-090fe600-fc0e-11ea-9311-511faa25c70e.png)
![66196](https://user-images.githubusercontent.com/67046386/93743655-0a411300-fc0e-11ea-8c6e-e009dcfe14ab.png)

**Comment by Kavantix** [comment]
FWIW, you probably meant to use `Text.rich` instead of `RichText` (which should be named `RawText`)

**Comment by iapicca** [comment]
> FWIW, you probably meant to use `Text.rich` instead of `RichText` (which should be named `RawText`)

@Kavantix 
the use of [RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) is intentional since [Text.rich constructor](https://api.flutter.dev/flutter/widgets/Text/Text.rich.html) inherits [DefaultTextStyle](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html) as referenced [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text.dart#L429)

I fail to see a compelling reason why `RichText`  **_should_** be named differently

**Comment by Kavantix** [comment]
> the use of RichText is intentional since Text.rich constructor inherits DefaultTextStyle as referenced here

Alright just mentioned it since most people expect the behavior of `Text.rich` when using `RichText`

> I fail to see a compelling reason why RichText should be named differently

Well exactly as you say, it doesnt inherit the defaults, which is the opposite of what (most) people expect it to do
