### ISSUE TITLE
Update flutter/test_runner to add support for authentication token and metrics uploading

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66191]
This requires changes in the [devicelab_drone recipe](https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab.py) to generate a token using fuchsia's service_account recipe module to generate a file with an ephemeral auth token and pass it to the test runner.

The [test runner](https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/bin/run.dart) will need to be updated to receive the new auth-token-file parameter and use it to send a request with the benchmarks data.

**Comment by godofredoc** [comment]
@CaseyHillers please let me know if you need more details.

**Comment by CaseyHillers** [comment]
Additionally, this requires updating Cocoon's authentication to be able to accept service account tokens. We'll want to pass a header like `Swarming-Token` in api requests, and Cocoon should check the given token with LUCI.

**Comment by CaseyHillers** [comment]
Next steps:

Cocoon
1. Update authentication to accept luci service account token
2. Update update-task handler logic to take commitSha and taskName as parameters, and construct the task key

Recipes
1. Generate and pass service account token file to the spawned swarming task

**Comment by godofredoc** [comment]
For the recipes part you can use this as an example:

https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/firebase/api.py;l=25

**Comment by CaseyHillers** [comment]
Recipes change at https://flutter-review.googlesource.com/c/recipes/+/8080

Once the Cocoon PR and Recipes CL land I'll trigger a full dry run to validate LUCI tasks can upload results.

**Comment by CaseyHillers** [comment]
There's an authentication issue with the devicelab tasks. `luci-auth` is using the older version of Google OAuth tokens called access token, which needs a new handler in Cocoon.

Currently, Cocoon supports id tokens which are the more recent version. The flow is mostly the same, but there's different endpoints and expectations that need to be walked through. I've started to draft the PR and should have it ready for review tomorrow.

**Comment by CaseyHillers** [comment]
With https://flutter-review.googlesource.com/c/recipes/+/8588 landed, this should be working end to end.

@godofredoc FYI we should be able to enable some devicelab tasks on the prod pool now.

**Comment by CaseyHillers** [comment]
The metrics upload is based on `taskName`, which is not how Cocoon handles LUCI tasks. Instead, I need to change over to using the builder name and pipe that through the various systems.

**Comment by CaseyHillers** [comment]
Successful run: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863243121306182448/+/steps/run_web_benchmarks_html/0/stdout
