### ISSUE TITLE
Error: Error when reading '-': The system cannot find the file specified.

### ISSUE THREAD

**Issue by atharvachavan2000** [flutter/flutter#66209]
## Steps to Reproduce

1. ... flutter create project_app
2. ... cd project_app
3. ... flutter run

## Logs

```
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 in debug mode...
Error: Error when reading '-': The system cannot find the file specified.

Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.8s
Exception: Gradle task assembleDebug failed with exit code 254
```

```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.4 at C:\Flutter\flutter
    • Framework revision fba99f6cf9 (5 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Atharva\AppData\Local\Android\Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Atharva\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.49.0)
    • VS Code at C:\Users\Atharva\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

```

**Comment by hamdikahloun** [comment]
Hi @atharvachavan2000 
Can you provide please your `flutter run --verbose`

**Comment by TahaTesser** [comment]
Hi @atharvachavan2000 
Do you have any `-` in your system path or user name has `-`? Please check your path to project

Can you please provide `flutter run --verbose`
Thank you

**Comment by atharvachavan2000** [comment]
> Hi @atharvachavan2000
> Do you have any `-` in your system path or user name has `-`? Please check your path to project
> 
> Can you please provide `flutter run --verbose`
> Thank you

[ +116 ms] executing: [C:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +216 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fba99f6cf9a14512e461e3122c8ddfaa25394e89
[   +1 ms] executing: [C:\Flutter\flutter/] git tag --contains HEAD
[ +248 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.4
[   +9 ms] executing: [C:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter\flutter/] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [C:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +113 ms] List of devices attached
[   +3 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +190 ms] No supported devices connected.
[  +10 ms] "flutter run" took 381ms.
[  +21 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:343:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +402 ms] ensureAnalyticsSent: 258ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project> flutter run --verbose
[ +115 ms] executing: [C:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +83 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fba99f6cf9a14512e461e3122c8ddfaa25394e89
[   +3 ms] executing: [C:\Flutter\flutter/] git tag --contains HEAD
[ +224 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.4
[  +10 ms] executing: [C:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +75 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter\flutter/] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +97 ms] executing: [C:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +70 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +64 ms] List of devices attached
           258b591d               device product:OnePlus7 model:GM1901 device:OnePlus7 transport_id:1
[   +7 ms] C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 258b591d shell getprop
[ +102 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +86 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +36 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +510 ms] Generating G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter
Project\my_project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +26 ms] ro.hardware = qcom
[  +68 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +27 ms] Skipping target: gen_localizations
[   +7 ms] complete
[  +15 ms] Launching lib\main.dart on GM1901 in debug mode...
[  +18 ms] C:\Flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot--sdk-root C:\Flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\Atharva\AppData\Local\Temp\flutter_tools.1a07c7e7\flutter_tool.1819fcbf\app.dill --packages .packages  
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts    
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +46 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 258b591d shell -x logcat -v time -t 1
[ +209 ms] Exit code 0 from: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 258b591d shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           09-26 13:51:42.199 I//vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service(  903): total connections for client : com.android.chromeare :3
[   +2 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 258b591d shell -x logcat -v time -t 1
[ +192 ms] Exit code 0 from: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe -s 258b591d shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           09-26 13:51:42.642 I//vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service(  903): unbindService is called for service :
           com.google.android.gms/.chimera.PersistentApiService and for client com.google.android.gms.persistent
[  +48 ms] <- compile package:my_project/main.dart
[  +14 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +71 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\Atharva\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +355 ms] Building APK
[  +18 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android\gradlew.bat.
[  +22 ms] G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android\gradlew.bat mode: 33279 rwxrwxrwx.
[ +140 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1461 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +24 ms] executing: [G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android/] G:\[FreeCourseSite.com]
Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\lib\main.dart -Ptrack-widget-creation=true       
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1066 ms] Error: Error when reading '-': The system cannot find the file specified.
[ +190 ms] Running Gradle task 'assembleDebug'... (completed in 2.9s)
[+3664 ms] Exception: Gradle task assembleDebug failed with exit code 254
[   +2 ms] "flutter run" took 8,625ms.
[  +21 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +284 ms] ensureAnalyticsSent: 219ms
[   +2 ms] Running shutdown hooks
[  +21 ms] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by TahaTesser** [comment]
Hi @atharvachavan2000 
As suspected, this is an issue with your system path, you have few `-` in your path to folder
```
[  +24 ms] executing: [G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android/] G:\[FreeCourseSite.com]
Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=G:\[FreeCourseSite.com] Udemy - Flutter & Dart - The Complete Guide [2020 Edition]\Flutter Project\my_project\lib\main.dart -Ptrack-widget-creation=true       
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1066 ms] Error: Error when reading '-': The system cannot find the file specified.
```

Please move your project your `my_project` to a folder without illegal characters such as `-` 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
