### ISSUE TITLE
google_maps_flutter setMapStyle before GoogleMap widget is rendered

### ISSUE THREAD

**Issue by kareldebedts** [flutter/flutter#66207]
Internal: b/249358651

## Use case

It's currently possible to set a custom map style once the GoogleMap widget is rendered.

```
     GoogleMap(
                    onCameraMove: (CameraPosition cameraPosition) {
                      loadNewPubs(cameraPosition);
                    },
                    onMapCreated: _onMapCreated,
                    initialCameraPosition: CameraPosition(
                      target: LatLng(lat, lng),
                      zoom: 15,
                    ),
                    myLocationButtonEnabled: false,
                    myLocationEnabled: true,
                    mapToolbarEnabled: false,
                    zoomControlsEnabled: false,
                    markers: Set<Marker>.of(markers.values),
                  ),
```

```
  void _onMapCreated(GoogleMapController controller) {
    setState(() {
      _mapController = controller;
      _mapController.setMapStyle(_mapStyle).whenComplete(() {
      });
    });
  }
```

This results in a "flash" which is especially disturbing when using a dark map style.

Demonstrated in this video on an iPhone 11 Pro simulator.

The behavior:

1. the widget isn't loaded: a pure white screen is rendered for a few 100 milliseconds.
2. the default map style is rendered white yellow (beige) color, this is more visible.
3. the custom map style is rendered

![ezgif-7-1a215ae5cc85](https://user-images.githubusercontent.com/53168464/93706107-62e7b180-fb23-11ea-831f-6d4a68a8cb33.gif)

## Proposal

To avoid step 1: a possibility to set a custom background color (now it's the color white).
To avoid step 2: a possibility to set the map style before the googleMap widget is rendered and not on onMapCreated.

**Comment by cedvdb** [comment]
At the very least, there needs to be a way to hide the map while the styles haven't loaded. Setting the opacity to 0 won't ever build the controller. Same with size. With a size of one pixel it works but it results in a weird pixel when the map has not loaded.

**Comment by BramDriesen** [comment]
This is also happening when no map style is being used but if the GoogleMap is on a page which is being pushed by a `Navigator.push` in combination with a `MaterialPageRoute`

**Comment by cedvdb** [comment]
@pedromassango you added p4 to this issue but this one https://github.com/flutter/flutter/issues/67631 is p5

The p5 one would fix this issue as well, although it might be a broader change it has wider positives.

**Comment by pedromassango** [comment]
> @pedromassango you added p4 to this issue but this one #67631 is p5

This is a bug, that one is a feature proposal

**Comment by xster** [comment]
Making a P3 to match Google bug b/249358651

**Comment by khyati82** [comment]
@stuartmorgan - Any update on this issue? Requesting response on behalf of 1P customer

**Comment by stuartmorgan** [comment]
No update; I haven't had time to work on this yet.

**Comment by jacobsimionato** [comment]
This is affecting a second Google customer also - see internal bug b/249358651.

**Comment by Caypoh23** [comment]
Hey there, any updates on this issue?

**Comment by cedvdb** [comment]
@Caypoh23 using cloud map id solves this issue

**Comment by Caypoh23** [comment]
> @Caypoh23 using cloud map id solves this issue
@cedvdb
Which type should I create if my app targets both Android and iOS? Should I also create map styles in Google Maps Platform to apply the changes for dark mode?

**Comment by cedvdb** [comment]
> Should I also create map styles in Google Maps Platform to apply the changes for dark mode?

 yes, but go try maybe

**Comment by Caypoh23** [comment]
> > Should I also create map styles in Google Maps Platform to apply the changes for dark mode?
> 
> yes,

I added Cloud Map Id from https://console.cloud.google.com/google/maps-apis/ map management
However, when the map is loading the background is blinking in a dark map style. So nothing is changed

```
GoogleMap(
  myLocationEnabled: true,
  cloudMapId: '[Pasted My Cloud Id]',
  myLocationButtonEnabled: false,
  mapType: MapType.normal,
  initialCameraPosition: bloc.position,
  onMapCreated: bloc.onMapCreated,
  onCameraMove: bloc.onCameraMove,
  onCameraIdle: bloc.onCameraIdle,
),
```

```
void onMapCreated(GoogleMapController controller) {
    mapController = controller;
    mapController!.setMapStyle(mapStyle);
}
```

**Comment by cedvdb** [comment]
@Caypoh23 

Remove this

```
    mapController!.setMapStyle(mapStyle);
```

The map style must be configured online

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/6192 will allow setting an initial style without needing to use cloud styling.

**Comment by stuartmorgan** [comment]
Accidentally closed in the first of the PR chain.
