### ISSUE TITLE
Flutter commands stuck waiting for startup lock

### ISSUE THREAD

**Issue by swkang73** [flutter/flutter#66200]
## Summary
I'm using macOS Catalina v10.15.5, and just installed flutter using git. But whenever I execute flutter commands (flutter doctor, flutter precache), I'm stuck at Waiting for another flutter command to release the startup lock...

Has been leaving it for >30min, still stuck at the error page.

List of solutions I've tried:

- `killall -9 dart` -> gets "No matching processes belonging to you were found FAIL: 1"
- Removing <YOUR FLUTTER FOLDER>/bin/cache/lockfile -> there is no lockfile
- delete the directory & restart PC & download again -> still the same error message

## Steps to Reproduce

1. `git clone https://github.com/flutter/flutter.git`
2. `export PATH="$PATH:`pwd`/flutter/bin"`
3. `flutter doctor`

## Logs
<img width="920" alt="Screen Shot 2020-09-19 at 4 47 42 PM" src="https://user-images.githubusercontent.com/26642482/93691287-d7750e80-fa97-11ea-81c4-b49468041ba6.png">

Verified no dart processes running
<img width="766" alt="Screen Shot 2020-09-19 at 5 21 33 PM" src="https://user-images.githubusercontent.com/26642482/93691630-99c6b480-fa9c-11ea-8089-d7458de16bd3.png">

**Comment by hamdikahloun** [comment]
hI @swkang73 
Can you try `flutter update-packages`

**Comment by Abhishek01039** [comment]
Hi @swkang73 
please refer this as well https://github.com/flutter/flutter/issues/14703

**Comment by ibankm** [comment]
please check that you use old version of flock for osx.
if you use old version of flock, update flock by brew or etc.

**Comment by swkang73** [comment]
Running `flutter update-packages` gave the same error page. 

Found the fix here:
https://stackoverflow.com/questions/63974223/flutter-commands-stuck-waiting-for-startup-lock

**Comment by darshankawar** [comment]
@swkang73 Good to know you found the fix.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.
