### ISSUE TITLE
call dispose on desktop plaform

### ISSUE THREAD

**Issue by amervelic** [flutter/flutter#66214]
Flutter application does not call dispose on desktop platform (macOS) if it is in desktop layout (master / detail) eg Profile / Detalis, widget detail never calls dispose.

@override
  void dispose() {
    _subscriptionStream.cancel();
    _subscriptionTexting.cancel();
    _subscriptionMessages.cancel();
    _subscriptionAddMessages.cancel();

    super.dispose();
  }

**Comment by iapicca** [comment]
@amervelic  can you provide your `flutter doctor -v`?

**Comment by amervelic** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.13.6 17G5019, locale en-BA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (4 available)

**Comment by amervelic** [comment]
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.13.6 17G5019, locale
    en-BA)
    • Flutter version 1.22.0-12.0.pre at /Volumes/Backup/flutter
    • Framework revision a27c242b0e (9 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/Backup/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Volumes/Backup/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode 10.2.1.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
       • macOS (desktop)         • macos        • darwin-x64     • Mac OS X 10.13.6
      17G5019
    • Web Server (web)        • web-server   • web-javascript • Flutter Tools
    • Chrome (web)            • chrome       • web-javascript • Google Chrome
      85.0.4183.10

**Comment by iapicca** [comment]
@amervelic does this [code](https://github.com/flutter/flutter/issues/66214#issuecomment-695785103) work on mac?

**Comment by pedromassangocode** [comment]
Hi @amervelic 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by amervelic** [comment]
@override
  Widget build(BuildContext context) {
    // TODO: implement build
    return ChangeNotifierProvider(
        create: (_) => Chat(),
        builder: (context, child) {
          return Row(children: [
            Flexible(flex: 2, fit: FlexFit.tight, child: HomePage()),
            Flexible(flex: 5,
                child: Consumer<Chat>(
                    builder: (context, chat, child) => ChatScreen(chat: chat)))
          ]);
        });
  }

Master/Detail layout (Home/ChatScreen) never call dispose when close app (- (void)applicationWillTerminate:(UIApplication *)application)

**Comment by stuartmorgan** [comment]
Your original report said:

> widget detail never calls dispose

Your latest comment said:

> Master/Detail layout (Home/ChatScreen) never call dispose when close app (- (void)applicationWillTerminate:(UIApplication *)application)

Which is it? Never calling dispose at all would be a bug; wanting dispose to be called on application exit would be a feature request (one whose use case is probably better covered by https://github.com/flutter/flutter/issues/30735)

**Comment by pedromassangocode** [comment]
Hi @amervelic 
Also, please provide a minimal complete sample code that does not uses third-party plugins/packages.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by kakyoism** [comment]
I have a minimum sample code in [this SO issue](https://stackoverflow.com/questions/67881349/flutter-desktop-cannot-respond-to-lifecycle-events).

Using that code on macOS Big Sur, fultter 2., you'll notice that `dispose()` was never called

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
(16:55) bin.luo@kkMa
```

**Comment by stuartmorgan** [comment]
Your SO question is about `didChangeAppLifecycleState`, not dispose. See the issue I referenced above.
