### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by usamabse048** [flutter/flutter#66211]
Newbie here
i am getting this exception while building gradle

![image](https://user-images.githubusercontent.com/49960687/93710805-b2010700-fb62-11ea-8236-70692fa276dc.png)

**Comment by hamdikahloun** [comment]
Hi @usamabse048 

Can you please delete all folders in `%userprofile%\.gradle\wrapper\dists` and provide your `flutter doctor -v`

**Comment by usamabse048** [comment]
> Hi @usamabse048
> 
> Can you please delete all folders in `%userprofile%\.gradle\wrapper\dists` and provide your `flutter doctor -v`

I have deleted all the folders from dists
![image](https://user-images.githubusercontent.com/49960687/93711207-ceeb0980-fb65-11ea-994a-fb4d4c76c1dd.png)

**Comment by hamdikahloun** [comment]
@hamdikahloun run `flutter run -v` please

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/51195

**Comment by darshankawar** [comment]
@usamabse048,
Please try above listed solution and see if it works for you.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
