### ISSUE TITLE
 Tabbar height problem

### ISSUE THREAD

**Issue by Jlanglang** [flutter/flutter#66219]
I have a problem

I updated the flutter SDK after `v1.20.4`;

UI deviation

![image](https://user-images.githubusercontent.com/17871050/93712756-56e30a80-fb8a-11ea-8ea0-924f80ea939b.png)

![image](https://user-images.githubusercontent.com/17871050/93712782-7aa65080-fb8a-11ea-91a3-f4d6f8cd1820.png)

When the version is lower than v1.20.4, its height can be full

**Comment by iapicca** [comment]
@Jlanglang can you provide more detail about the issue you are encountering
and a runnable minimal code sample

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
