### ISSUE TITLE
Migrate devicelab tests running on VMs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66225]
Some of the devicelab tests are running using linux vms. These tests can run directly using luci linux bots once we have functionality to upload metrics from the test runner.

**Comment by CaseyHillers** [comment]
FYI for https://github.com/flutter/flutter/issues/71749 I created linux_web_benchmarks_canvaskit on LUCI for test purposes. After that issue is fixed, we'll need to migrate the upload_metrics property to be set based on the branch (like what `wbh` does)

**Comment by CaseyHillers** [comment]
I am going to monitor infra logs to look for linux vms still being used. If not, I am going to free the vm instances from flutter-infra. Also, they will need to be removed from agents datastore.

**Comment by CaseyHillers** [comment]
I turned off all vms in flutter-infra GCP. I am going to give soak time before clearing them and wiping them.

Initial results show nothing needing them now other than the agent datastore.

**Comment by CaseyHillers** [comment]
Linux VMs turned down
