### ISSUE TITLE
io.flutter.1.ui (10): EXC_BREAKPOINT (code=1, subcode=0x1acbd79d0)

### ISSUE THREAD

**Issue by coderJW** [flutter/flutter#66220]
When my app is installed on the iOS14 system model, the app crashes; the display name of the app is Runner will not crash, but the display name of the app is Chinese and it will crash;

xcode run tip:
```
malloc: Incorrect checksum for freed object 0x10819e600: probably modified after being freed.
Corrupt value: 0x20202270
malloc: *** set a breakpoint in malloc_error_break to debug
```

breakpoint tip:
```
io.flutter.1.ui (10): EXC_BREAKPOINT (code=1, subcode=0x1acbd79d0)
![图片](https://user-images.githubusercontent.com/15873406/93742206-5006d700-fc20-11ea-9289-03656625dc62.png)
```

log:
```
    Application received signal SIGABRT (null)
    ((
        0 CoreFoundation 0x00000001833325c0 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1185216
        1 libobjc.A.dylib 0x00000001973ac42c objc_exception_throw + 60
        2 CoreFoundation 0x000000018322ea9c 472C9193-115D-34CD-AD1D-0E7E091C9432 + 121500
        3 xxx!UmengSignalHandler
        4 libsystem_platform.dylib 0x00000001ca87e27c DAE36DD6-F44A-39F4-9924-261898BD82CC + 21116
        5 libsystem_pthread.dylib 0x00000001ca883c74 pthread_kill + 272
        6 libsystem_c.dylib 0x000000018c434bb4 abort + 104
        7 AGXMetalA13 0x00000001cbd5fa80 AGXMetalA13 + 2665088
        8 AGXMetalA13 0x00000001cbd61158 AGXMetalA13 + 2670936
        9 Flutter 0x0000000100ee191c Flutter + 3021084
        10 Flutter 0x0000000100e4d64c Flutter + 2414156
        11 Flutter 0x0000000100e0144c Flutter + 2102348
        12 Flutter 0x0000000100df3870 Flutter + 2046064
        13 Flutter 0x0000000100df3df0 Flutter + 2047472
        14 Flutter 0x0000000100e12600 Flutter + 2172416
        15 Flutter 0x0000000100e8b6cc Flutter + 2668236
        16 Flutter 0x0000000100c14a18 Flutter + 84504
        17 Flutter 0x0000000100c2b450 Flutter + 177232
        18 Flutter 0x0000000100c7e500 Flutter + 517376
        19 Flutter 0x0000000100c7ee28 Flutter + 519720
        20 Flutter 0x0000000100c7e7a8 Flutter + 518056
        21 Flutter 0x0000000100c841bc Flutter + 541116
        22 Flutter 0x0000000100c3cb68 Flutter + 248680
        23 Flutter 0x0000000100c3e7e0 Flutter + 255968
        24 CoreFoundation 0x00000001832b0050 472C9193-115D-34CD-AD1D-0E7E091C9432 + 651344
        25 CoreFoundation 0x00000001832afc50 472C9193-115D-34CD-AD1D-0E7E091C9432 + 650320
        26 CoreFoundation 0x00000001832af0c4 472C9193-115D-34CD-AD1D-0E7E091C9432 + 647364
        27 CoreFoundation 0x00000001832a9178 472C9193-115D-34CD-AD1D-0E7E091C9432 + 622968
        28 CoreFoundation 0x00000001832a84bc CFRunLoopRunSpecific + 600
        29 GraphicsServices 0x0000000199d2d820 GSEventRunModal + 164
        30 UIKitCore 0x0000000185c4c734 47154C6D-47DF-3ABB-A152-56B159B014E4 + 12048180
        31 UIKitCore 0x0000000185c51e10 UIApplicationMain + 168
        32 xxx!main [main.m : 7]
        33 libdyld.dylib 0x0000000182f6fe60 90A4E82E-250C-35E3-8B2D-51D6D8B1119B + 3680
    )
    dSYM UUID: 69B8CB46-975D-324D-8D34-4EB3B07F6673
    CPU Type: arm64
    Slide Address: 0x0000000100000000
    Binary Image: xxx
    Base Address: 0x00000001006b4000
```

```
Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/cjw/Flutter/flutter
    • Framework revision f7a6a7906b (4 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cjw/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/cjw/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
```

**Comment by iapicca** [comment]
@coderJW 
your flutter version is obsolete, please run `flutter upgrade -f`

**Comment by coderJW** [comment]
> @coderJW
> your flutter version is obsolete, please run `flutter upgrade -f`

What version should be upgraded to solve this problem

**Comment by Abhishek01039** [comment]
hi @coderJW 
latest stable which is 1.20.4

**Comment by coderJW** [comment]
> hi @coderJW
> latest stable which is 1.20.4

@Abhishek01039 1.20.4 version can solve this problem?

**Comment by iapicca** [comment]
> 1.20.4 version can solve this problem?

@coderJW upgrading to the latest (stable) version of flutter isn't proposed as a solution,
but a pre-requisite for the issue to be workable; 
there isn't much of a point to investigate an error that occurs in an obsolete version of flutter 

if the error does occur with the latest version, 
please provide your `flutter run --release -v` and your updated `flutter doctor -v`

**Comment by coderJW** [comment]
There are still problems upgrading to version 1.20.4;   @iapicca @Abhishek01039 

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/cjw/Flutter/flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cjw/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/cjw/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • CJW的i7 (mobile)            • 1fcaf48fc3505a1a1189fa8c961f66e5308ce857 •
      ios • iOS 14.0
    • iPhone 11 Pro Max (mobile) • 228325AC-F894-4848-9A34-48465E1F04AB     •
      ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

**Comment by TahaTesser** [comment]
Hi @coderJW 
You cannot rename display name from Runner to something else
The correct way to change your app name is to edit `info.plist` and change `CFBundleName` 

**Before**
![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 39 29](https://user-images.githubusercontent.com/48603081/93750287-db7c6a00-fc18-11ea-9fad-74f0729bbc3f.png)


```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>stable_flutter</string>
```

**After**
![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 42 22](https://user-images.githubusercontent.com/48603081/93750315-e8995900-fc18-11ea-9ff8-452237b083f4.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>新名字</string>
```



Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by coderJW** [comment]
> Hi @coderJW
> You cannot rename display name from Runner to something else
> The correct way to change your app name is to edit `info.plist` and change `CFBundleName`
> 
> **Before**
> ![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 39 29](https://user-images.githubusercontent.com/48603081/93750287-db7c6a00-fc18-11ea-9fad-74f0729bbc3f.png)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>CFBundleDevelopmentRegion</key>
> 	<string>$(DEVELOPMENT_LANGUAGE)</string>
> 	<key>CFBundleExecutable</key>
> 	<string>$(EXECUTABLE_NAME)</string>
> 	<key>CFBundleIdentifier</key>
> 	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	<key>CFBundleInfoDictionaryVersion</key>
> 	<string>6.0</string>
> 	<key>CFBundleName</key>
> 	<string>stable_flutter</string>
> ```
> 
> **After**
> ![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 42 22](https://user-images.githubusercontent.com/48603081/93750315-e8995900-fc18-11ea-9ff8-452237b083f4.png)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>CFBundleDevelopmentRegion</key>
> 	<string>$(DEVELOPMENT_LANGUAGE)</string>
> 	<key>CFBundleExecutable</key>
> 	<string>$(EXECUTABLE_NAME)</string>
> 	<key>CFBundleIdentifier</key>
> 	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	<key>CFBundleInfoDictionaryVersion</key>
> 	<string>6.0</string>
> 	<key>CFBundleName</key>
> 	<string>新名字</string>
> ```
> 
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

Thank you very much, solved

**Comment by Shadow-NewBee** [comment]
> Hi @coderJW
> You cannot rename display name from Runner to something else
> The correct way to change your app name is to edit `info.plist` and change `CFBundleName`
> 
> **Before**
> ![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 39 29](https://user-images.githubusercontent.com/48603081/93750287-db7c6a00-fc18-11ea-9fad-74f0729bbc3f.png)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>CFBundleDevelopmentRegion</key>
> 	<string>$(DEVELOPMENT_LANGUAGE)</string>
> 	<key>CFBundleExecutable</key>
> 	<string>$(EXECUTABLE_NAME)</string>
> 	<key>CFBundleIdentifier</key>
> 	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	<key>CFBundleInfoDictionaryVersion</key>
> 	<string>6.0</string>
> 	<key>CFBundleName</key>
> 	<string>stable_flutter</string>
> ```
> 
> **After**
> ![Simulator Screen Shot - iPhone 11 - 2020-09-21 at 14 42 22](https://user-images.githubusercontent.com/48603081/93750315-e8995900-fc18-11ea-9ff8-452237b083f4.png)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>CFBundleDevelopmentRegion</key>
> 	<string>$(DEVELOPMENT_LANGUAGE)</string>
> 	<key>CFBundleExecutable</key>
> 	<string>$(EXECUTABLE_NAME)</string>
> 	<key>CFBundleIdentifier</key>
> 	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	<key>CFBundleInfoDictionaryVersion</key>
> 	<string>6.0</string>
> 	<key>CFBundleName</key>
> 	<string>新名字</string>
> ```
> 
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

It's work. Thanks！I found Chinese Product name will cause crash in iOS 14(but not all apps).

这个能解决我的问题。然后这边发现当把Product Name设置成中文的时候，这边会发生崩溃。所以，改成英文名就可以了。

**Comment by lanistor** [comment]
@coderJW May you explain more? why changing name helps?

**Comment by lanistor** [comment]
@Shadow-NewBee 现在已经可以正常运行了？如果必须用中文名字应该怎么做呢？

**Comment by Shadow-NewBee** [comment]
> @Shadow-NewBee 现在已经可以正常运行了？如果必须用中文名字应该怎么做呢？

product name 一般就是项目的 name, 都是英文吧. 我这边是历史原因将 product name 设置成中文.这边就给它改了. APP 要显示,只要正确设置 display name 就好了.

**Comment by lanistor** [comment]
@Shadow-NewBee  确实是中文名字的问题，改成英文名字就好了。
