### ISSUE TITLE
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. 

### ISSUE THREAD

**Issue by pc1995** [flutter/flutter#66222]
### plugin

```shell
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/opt in PATH, mode 040777
Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing TZImagePickerController (3.4.2)
Installing panchao_image_picker (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

```

**Comment by hamdikahloun** [comment]
Hi @pc1995 

Open the iOS project with xcode (ios folder)
Select Runner From left menu
Select Runner in PROJECT
Select Info
In Profile select the profile configuration
In Debug select the debug configuration
In Release select the release configuration

![IMG_20200920_165422](https://user-images.githubusercontent.com/32666446/93715549-f8a23180-fb61-11ea-890f-8d1ca88c0c19.png)

**Comment by pc1995** [comment]
> Hi @pc1995
> 
> Open the iOS project with xcode (ios folder)
> Select Runner From left menu
> Select Runner in PROJECT
> Select Info
> In Profile select the profile configuration
> In Debug select the debug configuration
> In Release select the release configuration
> 
> ![IMG_20200920_165422](https://user-images.githubusercontent.com/32666446/93715549-f8a23180-fb61-11ea-890f-8d1ca88c0c19.png)

@hamdikahloun 
Thank you so much ，thank you, thank you!

**Comment by darshankawar** [comment]
@pc1995 seems your issue has been resolved.
I am going ahead and closing this based on your last message. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by samcdavid** [comment]
For those who are not iOS devs and stumble upon this hoping that it resolves the issue. I had trouble running my project with `flutter run` after making the changes here.

I was able to resolve the issue by editing my Release.xcconfig file to add these two lines at the bottom:
```
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig"
```
Then I added this line to the bottom of my Debug.xcconfig
```
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
```

For those looking for these two files in XCode, here is where I found them:
![image](https://user-images.githubusercontent.com/773102/97463683-633f4d80-1916-11eb-8772-7d0e576dbd3e.png)

After doing this, pod install worked just fine and so did flutter run. Hopefully, this saves someone else a headache.

Referencing: https://stackoverflow.com/questions/53630136/using-cocoapods-libraries-in-flutter-ios-platform-specific-code

**Comment by codex-joao** [comment]
Thanks @samcdavid you're right

**Comment by adgrover** [comment]
Thanks @samcdavid and @pc1995. Tried both methods. Worked like a charm

**Comment by maheshmnj** [comment]
I had similar issue on the M1 mac  with 

```
flutter 1.22.6
``` 
I tried several things  from 
```
flutter clean 
pod install 
deleted pods directory ,Podfile,podfile.lock
```
but nothing seemed to work finally I  deleted the ios folder and recreated it by running 

```
flutter create .
```
but this is not recommendable if you have an existing flutter project with Ios specific configurations done, since It was my new flutter project without any ios specific configurations I could do it without any problem.

**Comment by sultanmyrza** [comment]
> select the profile
@hamdikahloun
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 2.0.4 at /Users/sultanmyrza/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
```
pubspec.yaml
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.0.4"
  cloud_firestore: "^1.0.6"
```
![Screen Shot 2021-04-25 at 2 07 28 PM](https://user-images.githubusercontent.com/12681781/115982723-0cfa5100-a5bf-11eb-9ca9-48444ea20e20.png)

pod install --verbose
```
-> Pod installation complete! There are 5 dependencies from the Podfile and 24 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

```

**Comment by bdairy** [comment]
any update in this I am stuck with this issue for the last 2 days..??
