### ISSUE TITLE
Run all tasks for a commit from flutter dashboard

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66228]
After moving devicelab tests to luci we will be batching up to 5 commits. This will require to provide functionality to trigger builds for a commit with a single click in the flutter dashboard.

**Comment by CaseyHillers** [comment]
@godofredoc can this be closed in favor of https://github.com/flutter/flutter/issues/66229?

**Comment by godofredoc** [comment]
yes, actually I got several comment in the design related to this being a very low priority.
