### ISSUE TITLE
Adding a single sliver inside the CustomScrollView causes Error!!

### ISSUE THREAD

**Issue by JICA98** [flutter/flutter#66221]
CustomScrollView(
        slivers: <Widget>[
          // SliverList(
          //   delegate: SliverChildListDelegate([]),
          // ),
          streamFirebase()
        ],
      ),

On adding a single sliver (which is a streambuilder returning a sliver list) inside a CustomScrollView,
 I'm getting the following error.

The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1568 pos 12: 'center.parent == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause
'package:flutter/src/rendering/box.dart': Failed assertion: line 1705 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.

The Error disappears as soon as I uncomment the extra sliver. Is it a bug perhaps?
Here streamFirebase() is streambuilder which returns a sliver widget all the time.

**Comment by iapicca** [comment]
@JICA98 
the issue might depend from your implementation,
try running  on [dartpad](https://dartpad.dartlang.org/) the code sample below

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
    const MyHomePage() : super(key: const Key('MyHomePage'));

  Stream<int> _stream() async* {
    for (int i = 0; true; ++i) {
      await Future.delayed(const Duration(seconds: 1));
      yield i;
    }
  }

  @override
  Widget build(BuildContext context) => Material(
        child: CustomScrollView(
          slivers: [
            ...[
              for (int i = 0; i < 5; ++i)
                const SliverToBoxAdapter(
                  child: Center(
                    child: FlutterLogo(
                      size: 80,
                    ),
                  ),
                ),
            ],
            StreamBuilder<int>(
              stream: _stream(),
              initialData: 0,
              builder: (BuildContext context, AsyncSnapshot<int> snapshot) =>
                  SliverToBoxAdapter(
                child: Center(
                  child: Text('${snapshot.data}'),
                ),
              ),
            ),
          ],
        ),
      );
}

```

</details>

**Comment by JICA98** [comment]
Thanks, a single widget does work well.
