### ISSUE TITLE
[tool_crash] "OS Error: Incorrect function" in plugin symlinking if Flutter and project are on different volumes

### ISSUE THREAD

**Issue by SureshKumar311** [flutter/flutter#66224]
## Command
```
flutter build windows
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:276:7)
#1      _Link.createSync (dart:io/link.dart:197:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:22:16)
#3      _createPlatformPluginSymlinks (package:flutter_tools/src/plugins.dart:1113:12)
#4      createPluginSymlinks (package:flutter_tools/src/plugins.dart:1078:5)
#5      buildWindows (package:flutter_tools/src/windows/build_windows.dart:41:3)
#6      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:52:11)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Microsoft Windows [Version 10.0.18362.116], locale
    en-US)
    • Flutter version 1.22.0-10.0.pre.269 at C:\flutter
    • Framework revision 51fa704642 (23 hours ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\sk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\sk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18362.116]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: eaa9b47a4ac278a9439468911d2c361a472b114b
### Plugins
path_provider-1.6.16
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.3
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
url_launcher-5.6.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1
file_chooser
path_provider_fde
menubar
window_size

i was trying to run flutter desktop windows applications i had check flutter doctor but every thinks r correct bu it showing error message as below 
PS E:\project_flutter\flutter-desktop-embedding\testbed> flutter build windows

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot create link, path =
'E:\project_flutter\flutter-desktop-embedding\testbed\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows' (OS Error: Incorrect function.
, errno = 1)".
 
A crash report has been written to E:\project_flutter\flutter-desktop-embedding\testbed\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+create+link%2C+path+%3D+%27E%3A%5Cproject_flutter%5Cflutter-desktop-embedding%5Ctestbed%5Cwindows%5Cflutter%5Cephemeral%5C.plugin_symlinks%5Cpath_provider_windows%27+%28OS+Error%3A+Incorrect+function.%0D%0A%2C+errno+%3D+1%29

plz help me 
thank you advance

**Comment by stuartmorgan** [comment]
> E:\

What kind of drive is `E`? There are limitations on cross-drive symbolic links on Windows, but I'm not clear whether it's all drives, or only non-local drives.

**Comment by SureshKumar311** [comment]
it was local E drive in same hard disk in windows and windows is  also install in c drive for same disk

**Comment by stuartmorgan** [comment]
@clarkezone Do you happen to know the exact requirements around symlink support? Is any cross-drive linking forbidden? If so, that'll be an annoying limitation for building projects 😟

**Comment by SureshKumar311** [comment]
now i change my flutter project to c drive of my system and run and i got this error










 C:\flutter-desktop-embedding\testbed> flutter run        
Launching lib\main.dart on Windows in debug mode...
Exception: Building with plugins requires symlink support. Please enable Developer Mode in your system       
settings.

FileSystemException: Cannot create link, path =
'C:\flutter-desktop-embedding\testbed\windows\flutter\ephemeral\.plugin_symlinks\file_chooser' (OS Error: A  
required privilege is not held by the client.
, errno = 1314)

**Comment by stuartmorgan** [comment]
That second error is expected if you haven't enabled developer mode, thus the error message.

**Comment by SureshKumar311** [comment]
now i had enable devloper mode in system and retry it 
and i got erro 


 C:\flutter-desktop-embedding\testbed> flutter run
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
EGL: Failed to initialize EGL
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(108)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Windows.

**Comment by stuartmorgan** [comment]
Please file a new issue for the EGL error; it's unrelated to the previous issue.

**Comment by stuartmorgan** [comment]
Actually, the EGL error is already filed as https://github.com/flutter/flutter/issues/51286. You can add information about your graphic driver to that issue.

**Comment by SureshKumar311** [comment]
my graphic is 
my cup === Penryn Penryn N/A GenuineIntel Pentium(R) Dual-Core CPU E5200 @ 2.50GHz 45 nm MMX SSE (1, 2, 3) 6 0 7 6 17 6 10676

my graphic ==Windows 10 x64 Edition (Build 9200) Microsoft Corporation 1.1.0 9.0 vs_3_0, ps_2_0 (SW) GDI Generic GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture 2560 16384 16384 3 16 128 32 10 16 10 0.5 10 0.125 0.5 10 0.125 0 0 0 0 6 8 65536 1024 30 0 0 0 0 0 0 0 0\

**Comment by clarkezone** [comment]
The docs appear to not address this, I can try and find an answer to this.

**Comment by nabil6391** [comment]
I am having the same error:

Building with plugins requires symlink support. Please enable Developer Mode in your system settings.

FileSystemException: Cannot create link, path = 'D:\originalprojects\project_flutter\windows\flutter\ephemeral\.plugin_symlinks\path_provider_windows' (OS Error: A required privilege is not held by the client.
, errno = 1314)

I am using Windows 8.1 and I do not see any way to enable developer mode.

**Comment by stuartmorgan** [comment]
@nabil6391 This issue is about the cross-volume symlinking, not the "Building with plugins requires symlink support" message. Please file a new issue about those instructions not being correct for Windows 8.

**Comment by stuartmorgan** [comment]
I was going to fix this while fixing https://github.com/flutter/flutter/issues/66973 but I don't actually have a setup with a network volume. @jonahwilliams since you hit this you presumably do; could you take this one?

**Comment by jonahwilliams** [comment]
I do not, I was scrubbing through crash logs and I found it :(

**Comment by jiajiawei** [comment]
**close 360...** 
It`s useful for my computer

**Comment by stuartmorgan** [comment]
Sounds like the description isn't quite right and there are other volume limitations that will cause this as well, per https://github.com/flutter/flutter/issues/87982#issuecomment-895873256

**Comment by mwoollen** [comment]
For me... 

1. I have G: (Google Drive).  If I try to use gdrive as a shared network folder for developing flutter, I believe that Windows and Google Drive just don't play well together and "symbolic link" creation returns an error from the OS.
2. If I switch to use local Windows C: drive for flutter development, initially, I get the error below... 

```
Exception: Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run 
  start ms-settings:developers
to open settings.
```
3. But if I run the command "start ms-settings:developers" and turn on Developer Mode, then "flutter run" seems to run.
![image](https://user-images.githubusercontent.com/8562131/192379939-ab906919-8f78-4ee5-b162-5bcae9e0c14e.png)

**Comment by mjolnirPH** [comment]
Similar issue, but tool only crashes when I run/debug on Windows; works fine on Android emulator and web based targets.  I'm just learning flutter,  developing using VS Code and the Flutter/Dart plugins. 

As per other threads, I've already enabled developer mode and I've also moved my source folder to the same drive as where Flutter is installed, but the issue persists.

Thanks for any and every help on this.

**Comment by H-MAli** [comment]
The reproduction of this problem is actually easier than that. At least it's what I'm experiencing.
- Have flutter installed on some NTFS volume.
- Create a project on an exFAT volume.
- Try to build your project, et voila! You're presented with this error.

I'm not quite sure whether using any specific Flutter package triggers symlinking or not since I encountered this error when moving an existing project to an exFAT volume with lots of packages already in use.

**Comment by lefour0403** [comment]
@SureshKumar311 do not need to change the location of your project. With Windows App, run your project in Release Mode or close your IDE and rerun as Administrator.  That fixed for me!
