### ISSUE TITLE
Error package:flutter/src/widgets/scroll_position.dart': _pendingDimensions': is not true

### ISSUE THREAD

**Issue by MohsenHaydari** [flutter/flutter#66239]
Today after update flutter sdk to 1.22.0-12.0. wherever the [SmartRefresher ](https://pub.dev/packages/pull_to_refresh)package is used i get this exception in stable and dev chanel but the program works well
`
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.
The relevant error-causing widget was
    MaterialClassicHeader 
            The relevant error-causing widget was
    MaterialClassicHeader 

#2      ScrollPosition.applyNewDimensions 
package:flutter/…/widgets/scroll_position.dart:582
#3      _NestedScrollPosition.applyNewDimensions 
package:flutter/…/widgets/nested_scroll_view.dart:1497
#4      RenderSliverRefresh.performLayout 
package:pull_to_refresh/…/internals/slivers.dart:189
#5      RenderObject.layout 
package:flutter/…/rendering/object.dart:1827
#6      RenderSliverRefresh.layout 
package:pull_to_refresh/…/internals/slivers.dart:147
...

			The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#dd1f3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
RenderObject: RenderSliverRefresh#dd1f3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
    needs compositing
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 452.4, overlap: -1.9, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.left, viewportMainAxisExtent: 452.4, remainingCacheExtent: 702.4, cacheOrigin: 0.0)
    geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
        scrollExtent: 0.0
        hidden
        maxPaintExtent: 0.0
    child: RenderRotatedBox#94682 relayoutBoundary=up2 NEEDS-PAINT
        needs compositing
        parentData: paintOffset=Offset(0.0, 0.0) (can use size)
        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
        size: Size(411.4, 48.0)
        child: RenderFractionalTranslation#55fd9 relayoutBoundary=up3 NEEDS-PAINT
            needs compositing
            parentData: offset=Offset(0.0, 0.0) (can use size)

			constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
            size: Size(411.4, 48.0)
            translation: Offset(0.0, -0.9)
            transformHitTests: true
            child: RenderTransform#08cae relayoutBoundary=up4 NEEDS-PAINT
                needs compositing
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
                size: Size(411.4, 48.0)
                transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
                origin: null
                alignment: center
                textDirection: rtl
                transformHitTests: true
                child: RenderPositionedBox#dfced relayoutBoundary=up5 NEEDS-PAINT
                    needs compositing
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
                    size: Size(411.4, 48.0)
                    alignment: topCenter
                    textDirection: rtl
                    widthFactor: expand
                    heightFactor: expand
════════════════════════════════════════════════════════════════════════════════
`

I played with the code a lot but I could not solve the problem Can anyone give me a solution?

**Comment by pedromassangocode** [comment]
Hi @MohsenHaydari 
I see there's an open issue (https://github.com/flutter/flutter/issues/66240) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
