### ISSUE TITLE
Android Migration

### ISSUE THREAD

**Issue by Rajkumar07793** [flutter/flutter#66234]

**Comment by Rajkumar07793** [comment]
when I downloaded a zip file from github and open it in the Android Studio having below error after run-
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .
Running Gradle task 'assembleDebug'...
(This is taking an unexpectedly long time.)

**Comment by darshankawar** [comment]
Hi @Rajkumar07793,
Can you elaborate on your issue ? What exactly is the issue you are facing, because its not clear from what you have provided above.
Thanks.

**Comment by Rajkumar07793** [comment]
> Hi @Rajkumar07793,
> Can you elaborate on your issue ? What exactly is the issue you are facing, because its not clear from what you have provided above.
> Thanks.

this issue is about AndroidX migration, but now I have solved this issue by migrating my app to AndroidX, thank you very much for your support

**Comment by darshankawar** [comment]
Closing this as solved.
