### ISSUE TITLE
FlutterFragment not registering GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#66230]
Hello,

My problem is a bit complex to reproduce, but I will try to explain it step by step.

Basically I have a Flutter app with multiple entry points and I would like to display each of them through a `FlutterFragment`.
On Android, the code is pretty basic and works well :

```
        supportFragmentManager
                .beginTransaction()
                .add(android.R.id.content, FlutterFragment.withNewEngine()
                        .dartEntrypoint("entrypoint")
                        .initialRoute("initialRoute")
                        .build<FlutterFragment>())
                .addToBackStack(entrypoint)
                .commitAllowingStateLoss()
```

However if I add a plugin like firebase_auth/firebase_core, I will continuously have the following error when calling `FirebaseFirebase.initializeApp()`:

`MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)`

After digging a little bit, it seems that `GeneratedPluginRegistrant` is never attached to the engine, [as this line suggests](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L233).

A fix is to call:

```
        supportFragmentManager.registerFragmentLifecycleCallbacks(
                object : FragmentManager.FragmentLifecycleCallbacks() {

                    // Force the registration of the engine and the GeneratedPluginRegistrant
                    override fun onFragmentAttached(fm: FragmentManager, f: Fragment, context: Context) {
                        super.onFragmentAttached(fm, f, context)

                        (f as FlutterFragment?)?.let {
                            GeneratedPluginRegistrant.registerWith(it.flutterEngine!!)
                        }
                    }
                }, true
        )
```

Shouldn't the `automaticallyRegisterPlugins` attribute of `FlutterActivityAndFragmentDelegate.java` be set to true instead?

**Comment by iapicca** [comment]
@g123k could you provide your `flutter doctor -v` and a minimal reproducible code sample?

**Comment by ninex** [comment]
@g123k I just had a similar issue when I change from FlutterActivity to FlutterFragmentActivity. The solution in my case was to explicitly register the plugins.
Here's the snippet from my MainActivity.kt

`class MainActivity: FlutterFragmentActivity() {

  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    GeneratedPluginRegistrant.registerWith(flutterEngine);`

**Comment by TahaTesser** [comment]
Hi @g123k 
Does the above solve your issue? https://github.com/flutter/flutter/issues/66230#issuecomment-695985836
@g123k could you provide `your flutter doctor -v` and a minimal reproducible code sample?

Thank you

**Comment by g123k** [comment]
@ninex Using a FlutterFragmentActivity is not mandatory with FlutterFragment (please correct me).
@TahaTesser So not really, I will create a repo ASAP

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
