### ISSUE TITLE
APP is crash when I upgrade IOS14 

### ISSUE THREAD

**Issue by pangbai123** [flutter/flutter#66241]
### 1. the crash code:
```dart
Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: 
                Color(0xff000000),
                Color(0xffFFFFFF),
              ]),
        ),
        height: 100,
      )
```
### 2. the crash log:
```
文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
Corrupt value: 0x20
文宝通(741,0x102f2b880) malloc: *** set a breakpoint in malloc_error_break to debug
文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
Corrupt value: 0x20
```
### 3. my environment:
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/pangbai/Desktop/program/flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pangbai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (1 available)
    • 孙毅的 iPhone (mobile) • 0688f7fa0d77cd38c333dfc2d753c4685c15a8af • ios • iOS 14.0

• No issues found!
Process finished with exit code 0
```

**Comment by SeasonLeee** [comment]
possible duplicate: #66175

**Comment by pangbai123** [comment]
> possible duplicate: #66175

Thank you , but it not this issues.

**Comment by SeasonLeee** [comment]
@pangbai123 yeah, I understand the two issues is not the same, but both of you have the similar cause that running app crashing on iOS14 platform, and the issue I pointed out have people shared their solutions, maybe you could find inspiration over there?

**Comment by TahaTesser** [comment]
Hi @pangbai123 
Trying the code sample you provided doesn't the crash the app on iOS 14

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [
                Color(0xff000000),
                Color(0xffFFFFFF),
              ]),
        ),
        height: 100,
      )),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0

• No issues found!

```

</details> 

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by xiaobeifeng** [comment]
> ### 1. the crash code:
> ```dart
> Container(
>         decoration: BoxDecoration(
>           gradient: LinearGradient(
>               begin: Alignment.topCenter,
>               end: Alignment.bottomCenter,
>               colors: 
>                 Color(0xff000000),
>                 Color(0xffFFFFFF),
>               ]),
>         ),
>         height: 100,
>       )
> ```
> 
> ### 2. the crash log:
> ```
> 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> Corrupt value: 0x20
> 文宝通(741,0x102f2b880) malloc: *** set a breakpoint in malloc_error_break to debug
> 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> Corrupt value: 0x20
> ```
> 
> ### 3. my environment:
> ```
> [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
>     • Flutter version 1.20.4 at /Users/pangbai/Desktop/program/flutter
>     • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/pangbai/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0, Build version 12A7209
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 48.1.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     • Flutter plugin version 44.0.3
>     • Dart plugin version 193.6494.35
> 
> [✓] Connected device (1 available)
>     • 孙毅的 iPhone (mobile) • 0688f7fa0d77cd38c333dfc2d753c4685c15a8af • ios • iOS 14.0
> 
> • No issues found!
> Process finished with exit code 0
> ```

请问你解决了吗？我也遇到了这个问题。

**Comment by heartbeat986** [comment]
watch issue #66220 ,it's work for me

**Comment by pangbai123** [comment]
> > ### 1. the crash code:
> > ```dart
> > Container(
> >         decoration: BoxDecoration(
> >           gradient: LinearGradient(
> >               begin: Alignment.topCenter,
> >               end: Alignment.bottomCenter,
> >               colors: 
> >                 Color(0xff000000),
> >                 Color(0xffFFFFFF),
> >               ]),
> >         ),
> >         height: 100,
> >       )
> > ```
> > 
> > 
> > ### 2. the crash log:
> > ```
> > 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> > Corrupt value: 0x20
> > 文宝通(741,0x102f2b880) malloc: *** set a breakpoint in malloc_error_break to debug
> > 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> > Corrupt value: 0x20
> > ```
> > 
> > 
> > ### 3. my environment:
> > ```
> > [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
> >     • Flutter version 1.20.4 at /Users/pangbai/Desktop/program/flutter
> >     • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
> >     • Engine revision d1bc06f032
> >     • Dart version 2.9.2
> >     • Pub download mirror https://pub.flutter-io.cn
> >     • Flutter download mirror https://storage.flutter-io.cn
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> >     • Android SDK at /Users/pangbai/Library/Android/sdk
> >     • Platform android-29, build-tools 29.0.2
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 12.0)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 12.0, Build version 12A7209
> >     • CocoaPods version 1.8.4
> > 
> > [✓] Android Studio (version 4.0)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin version 48.1.2
> >     • Dart plugin version 193.7361
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> > 
> > [✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
> >     • IntelliJ at /Applications/IntelliJ IDEA.app
> >     • Flutter plugin version 44.0.3
> >     • Dart plugin version 193.6494.35
> > 
> > [✓] Connected device (1 available)
> >     • 孙毅的 iPhone (mobile) • 0688f7fa0d77cd38c333dfc2d753c4685c15a8af • ios • iOS 14.0
> > 
> > • No issues found!
> > Process finished with exit code 0
> > ```
> 
> 请问你解决了吗？我也遇到了这个问题。

可以解决，使用Ink控件包裹来做渐变

**Comment by ligastavok** [comment]
If you use old ios Runner it could crash. if you recreate it from scratch it should help

**Comment by TahaTesser** [comment]
Hi @pangbai123 
Can you please provide your `flutter run --verbose` in a plain text file .txt, drop it the attachment in the comment and a complete reproducible minimal code sample
Thank you

**Comment by pangbai123** [comment]
> Hi @pangbai123
> Can you please provide your `flutter run --verbose` in a plain text file .txt, drop it the attachment in the comment and a complete reproducible minimal code sample
> Thank you

Thank you，I have solved the issue ,This is due to the old Podfile, I've just updated it from new project.

**Comment by pangbai123** [comment]
> > ### 1. the crash code:
> > ```dart
> > Container(
> >         decoration: BoxDecoration(
> >           gradient: LinearGradient(
> >               begin: Alignment.topCenter,
> >               end: Alignment.bottomCenter,
> >               colors: 
> >                 Color(0xff000000),
> >                 Color(0xffFFFFFF),
> >               ]),
> >         ),
> >         height: 100,
> >       )
> > ```
> > 
> > 
> > ### 2. the crash log:
> > ```
> > 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> > Corrupt value: 0x20
> > 文宝通(741,0x102f2b880) malloc: *** set a breakpoint in malloc_error_break to debug
> > 文宝通(741,0x102f2b880) malloc: Incorrect checksum for freed object 0x126027800: probably modified after being freed.
> > Corrupt value: 0x20
> > ```
> > 
> > 
> > ### 3. my environment:
> > ```
> > [✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
> >     • Flutter version 1.20.4 at /Users/pangbai/Desktop/program/flutter
> >     • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
> >     • Engine revision d1bc06f032
> >     • Dart version 2.9.2
> >     • Pub download mirror https://pub.flutter-io.cn
> >     • Flutter download mirror https://storage.flutter-io.cn
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> >     • Android SDK at /Users/pangbai/Library/Android/sdk
> >     • Platform android-29, build-tools 29.0.2
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 12.0)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 12.0, Build version 12A7209
> >     • CocoaPods version 1.8.4
> > 
> > [✓] Android Studio (version 4.0)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin version 48.1.2
> >     • Dart plugin version 193.7361
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> > 
> > [✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
> >     • IntelliJ at /Applications/IntelliJ IDEA.app
> >     • Flutter plugin version 44.0.3
> >     • Dart plugin version 193.6494.35
> > 
> > [✓] Connected device (1 available)
> >     • 孙毅的 iPhone (mobile) • 0688f7fa0d77cd38c333dfc2d753c4685c15a8af • ios • iOS 14.0
> > 
> > • No issues found!
> > Process finished with exit code 0
> > ```
> 
> 请问你解决了吗？我也遇到了这个问题。

可能是老的项目构建的podfile文件的问题，你新建一个替换掉ios的podfile文件试试。

**Comment by xiaobeifeng** [comment]
我觉得是flutter对iOS14适配的问题，我这边目前的解决方案是Xcode工程在release下模式运行和打包，安装后没有问题了，与控件Container的decoration属性的使用无关。

**Comment by pangbai123** [comment]
> 我觉得是flutter对iOS14适配的问题，我这边目前的解决方案是Xcode工程在release下模式运行和打包，安装后没有问题了，与控件Container的decoration属性的使用无关。

你的是不是第二次不能打开，这个是ios14的新特性，debug模式只能通过运行项目进入界面，不能通过程序桌面图标进入。

**Comment by xiaobeifeng** [comment]
![image](https://user-images.githubusercontent.com/14256000/93975361-f03c3780-fda9-11ea-882a-8d303583095b.png)
Android Studio debug模式下点击某个进入某个视图日志输出与设备失去连接，然后在Xcode运行项目直接崩溃上图这里了，后来我干脆Xcode release模式下看效果，调试用我另一个没升级到iOS14的设备，不知道以后该咋办。

**Comment by xiaobeifeng** [comment]
> > 我觉得是flutter对iOS14适配的问题，我这边目前的解决方案是Xcode工程在release下模式运行和打包，安装后没有问题了，与控件Container的decoration属性的使用无关。
> 
> 你的是不是第二次不能打开，这个是ios14的新特性，debug模式只能通过运行项目进入界面，不能通过程序桌面图标进入。

这个好像还真如你所说，但我的貌似并不是这种情况

**Comment by TahaTesser** [comment]
Hi @pangbai123 
Glad you resolved the issue, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
