### ISSUE TITLE
google_sign_in grey screen

### ISSUE THREAD

**Issue by jeremyw24** [flutter/flutter#66246]
I currently have an app in beta testing, multiple users have reported an issue which returns a grey screen when they click 'sign in with google'.

The API is scoped down to internal i.e. it only allows users in our gsuite domain to login to the application.

I suspect what is happening is that when a user is already signed into google on their device with an account outside our domain, the app progresses a sign in attempt with this account.

Typical google behavior if a user is already signed in is to ask the user which account to use but this does not see to happen.

I am able to reproduce the problem by signing into Google elsewhere on the device (browser or other app) then attempting to sign in on my app = grey screen. The user does not even get presented with the option to sign in.

Terminating the app returns the login screen again.

I am essentially using the example code with no modifications.

This issue is effecting both Android and iOS Device.s

**Comment by TahaTesser** [comment]
Hi @jeremyw24 
Grey screen indicates crash in release apps if you've grey screen something might be crashing in your app.  

Can you please provide your `flutter doctor -v`, your `pubspec.yaml`  and `flutter run --release --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by jeremyw24** [comment]
Thanks @TahaTesser - I just found the grey screen is a production failure. I have about 20 test users across android/ios for this beta test and so far only 2 android users and 1 ios user has reported the issue, I am unable to reproduce it on my own device via test flight or identify any errors in debug. 

I am just in the process of hooking up sentry to see if I might be able to identify the issue with those specific devices. 

### Flutter Doctor
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.6 18G5033, locale en-AU)
    • Flutter version 1.20.2 at /Users/jeremywest/Documents/Code/sdk/flutter
    • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jeremywest/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.10.0.beta.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • DE75697A-D1D7-4A5E-B5E8-DD515AF5BA6F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

### pubspec.yaml

```
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.1.1
  multi_image_picker: ^4.7.12
  firebase_storage: ^4.0.0
  url_launcher: ^5.5.1
  get_it: ^4.0.4
  firebase_database: ^4.0.0
  cloud_firestore: ^0.14.0+2
  sentry: ">=3.0.0 <4.0.0"
```

Output from flutter run --release --verbose: https://gist.github.com/jeremyw24/700452af2b7598df3bcdd00f15842f8d

Sample of code: https://gist.github.com/jeremyw24/f9be669dae3c6227851372016168d924

I have included the entire opening_screen code where the app checks if the user is logged in, if no current session then the user can login, if session is valid then it goes to the home view.

**Comment by jeremyw24** [comment]
Sentry found my issue, I am pleased to report this is not a flutter/plugin error - just a school boy coding error...

```
NoSuchMethodError: The getter 'displayName' was called on null.
Receiver: null
Tried calling: displayName
```

Closing this issue!
