### ISSUE TITLE
in Debug mode app running smoothly and when create Release APK it hang my device and not working well 

### ISSUE THREAD

**Issue by maulikdadhaniya** [flutter/flutter#66245]
**Framework Versions**

Flutter 1.20.4 • channel stable 
Framework • revision fba99f6cf9 (6 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**My Environment**

> [✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)

Currently i am facing issue like in Debug mode app running smoothly and when create Release APK it hang my device and not working well. It totally hang my device and give this type of error

> I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (31756): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

This is my **flutter run --release --verbose** File = [Verbose Log](https://gist.github.com/maulikdadhaniya/75a64224781fcb8c57824372e754997a)

This is my **pubspec.yaml** file = [pubspec file](https://gist.github.com/maulikdadhaniya/3f7756c9ab42962666b5f41039e6dfb5)

And Here is my init Code = [init Code](https://gist.github.com/maulikdadhaniya/3144cfa4d6f901e1380f8c9f1f83e142)

**Comment by TahaTesser** [comment]
Hi @maulikdadhaniya 
Can you please provide, your `flutter run --release --verbose` logs, your `pubspec.yaml`, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by maulikdadhaniya** [comment]
> Hi @maulikdadhaniya
> Can you please provide, your `flutter run --release --verbose` logs, your `pubspec.yaml`, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> Thank you

Hi @TahaTesser Thanks for reply me . I added flutter run --release --verbose , pubspec.yaml , init code in my asked question. Please find attachments.

**Comment by TahaTesser** [comment]
Hi @maulikdadhaniya 
To better address the issue, can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), **not production code**
Thank you

**Comment by maulikdadhaniya** [comment]
> 

    return Scaffold(
      drawer: Drawer(child: MenuBar()),
      body: Container(
          color: const Color.fromRGBO(240, 242, 245, 1),
          child: SafeArea(
            child: Consumer<AppModel>(
              builder: (context, value, child) {
                if (value.appConfig == null) {
                  return kLoadingWidget(context);
                }
                bool isStickyHeader = value.appConfig["Setting"] != null
                    ? (value.appConfig["Setting"]["StickyHeader"] ?? false)
                    : false;

                return Stack(
                  children: <Widget>[
                    if (value.appConfig['Background'] != null)
                      isStickyHeader
                          ? SafeArea(
                              child: HomeBackground(
                                config: value.appConfig['Background'],
                              ),
                            )
                          : HomeBackground(
                              config: value.appConfig['Background']),
                    HomeLayout(
                      configs: value.appConfig,
                      key: Key(value.locale),
                    ),
                  ],
                );
              },
            ),
          )),
    );

This is my code that i facing this issue

**Comment by TahaTesser** [comment]
Hi @maulikdadhaniya 
Your code sample is incomplete, please provide  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that is runnable 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
