### ISSUE TITLE
flutter application not running gives this error Execution failed for task ':android_intent:generateDebugRFile'. 

### ISSUE THREAD

**Issue by jk-hub** [flutter/flutter#66242]
error:
Launching lib\main.dart on ASUS X00TD in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_intent:generateDebugRFile'.
> java.util.NoSuchElementException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Flutter doctor -v:
D:\daq-dynamic>flutter doctor -v
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.20.3 at C:\flutter
    • Framework revision 216dee60c0 (3 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jk\AppData\Local\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\jk\AppData\Local\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • ONEPLUS A3003 (mobile) • 192.168.0.102:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

please help me out in this issue.
Thanks.

**Comment by TahaTesser** [comment]
Hi @jk-hub 
Can you please provide `flutter run --verbose` logs, and  complete reproducible minimal code sample
Thank you

**Comment by jk-hub** [comment]
this issue is been resolved thanks I run flutter clean cache repair

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
