### ISSUE TITLE
Hot reload fails in latest flutter beta 

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#66255]
sometimes In intellij , hot reload doesn't work. The dart analyser is returning a non zero exit code even when there is no error. it's returning error exit code for `info` messages also.
Since dart analyzer returns non zero exit code for info, the hot reload shows dart analyser has issues and doesn't proceed furthur. When we click on "view issues" there would only be info messages there.

Here are the related issues and PR : 

#61589 
#20855

## Flutter doctor : 
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2020.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

```

**Comment by TahaTesser** [comment]
Hi @nateshmbhat 
Does it happen in intellij? Have you hot reload in terminal? 

Can you please provide a complete reproducible minimal code sample and step by step to reproduce the issue
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
