### ISSUE TITLE
Bad state: Insecure HTTP is not allowed by platform: http://friend.angeleic.com/a62c4605e4bdac1c9b4dcd763b298742.jpg

### ISSUE THREAD

**Issue by pc1995** [flutter/flutter#66275]
### Bad state: Insecure HTTP is not allowed by platform: http://friend.angeleic.com/a62c4605e4bdac1c9b4dcd763b298742.jpg

When I load the image, the following error occurs

```shell
Bad state: Insecure HTTP is not allowed by platform: http://friend.angeleic.com/a62c4605e4bdac1c9b4dcd763b298742.jpg
```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hamdikahloun** [comment]
Hi @pc1995 
Can you provide please your `flutter run -v` , `flutter doctor -v` and your device config (Android , iOS, os version..)

**Comment by stuartmorgan** [comment]
This is behaving as expected; see https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android

**Comment by alexmercerind** [comment]
Why ...

**Comment by 0xM4st3R** [comment]
Why *2

**Comment by JagandeepBrar** [comment]
@stuartmorgan This is a major issue for my application: https://github.com/CometTools/LunaSea

It is a tool to connect to software hosted on a user's desktop or server machines, and commonly is only used through LAN (i.e., `http://192.168.99.1:6789`).

**This is a completely breaking issue for my application**, there should be an optional override, possibly through [HttpOverrides](https://api.flutter.dev/flutter/dart-io/HttpOverrides-class.html) which I already use to globally bypass the bad certificate callback.

**Comment by pkotowski** [comment]
They just want's to https on your labo and dev environments. Supid idiots.

**Comment by JagandeepBrar** [comment]
To add to @pkotowski, to also quickly allow insecure/HTTP requests globally across your application on iOS, you can add this to your `ios/Runner/info.plist` under the main dictionary definition:

```
<key>NSAppTransportSecurity</key>
<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
</dict>
```

Be warned that you will need to have an explanation for Apple's review team when enabling this, otherwise your app will get rejected on submission.

**Comment by tek08** [comment]
Not to be a pain, but [this page on NSAllowsLocalNetworking](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking) says that ATS allows these sorts of connections by default in iOS 10 and later.  So, which decree is right?

Again, trying not to be a pain here, but was a bit frustrated when suddenly my local dev setup stopped working.  What is the correct way to allow for a local server when developing?  Surely it's not to edit the plist file each time before cutting a release / before starting local dev, is it?

**Comment by geisterfurz007** [comment]
Is there a way to enable http only for development? When using an emulator, you connect to the host on `http://10.0.2.2` and constantly run into this.

**Comment by gregaton** [comment]
I would like to voice my support for the concerns of @geisterfurz007.
This is a big problem when working with the emulator.
Modifying the `AndroidManifest.xml` is not a good solution, as the workaround should only be effective for local development.
And having the backend run via https is also not an easy solution as it requires a certificate that is trusted by the emulator.

**Comment by stuz5000** [comment]
> I would like to voice my support for the concerns of @geisterfurz007.
> This is a big problem when working with the emulator.
> Modifying the `AndroidManifest.xml` is not a good solution, as the workaround should only be effective for local development.
> And having the backend run via https is also not an easy solution as it requires a certificate that is trusted by the emulator.

+1 

Is there a workaround here? The link https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android
doesn't show how to disable the excessively restrictive HTTPs requirement in local and debug debugs.

**Comment by tek08** [comment]
One workaround is to use ssh to set up a tunnel to your server.

I use `autossh`, which theoretically keeps the ssh tunnel open even in the event of errors.  Your miles may vary, so please look at documentation for all:

```bash
autossh -M 0 \
    -f \
    -L 0.0.0.0:443:$DOCKER_MACHINE_IP:80 \
    -N 127.0.0.1 || echo "Tunnel failed"
```

**Comment by geisterfurz007** [comment]
@stuz5000 @gregaton Checking the docs again, [this](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android#allowing-cleartext-connection-for-debug-builds) does look like a solution to the issue (explaining both how to allow plaintext connections for debug builds on both Android and iOS).

**Comment by savadmv** [comment]
I got this issue after upgrading to Flutter 2.0  

 flutter doctor -v


```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-QA)
    • Flutter version 2.0.1 at /Users/fegnotechnologies/Developer/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fegnotechnologies/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

**Comment by fzyzcjy** [comment]
Any updates on workaround? It is strongly desired that **when debugging** HTTP is allowed, and **on release** only HTTPS is allowed.

**Comment by geisterfurz007** [comment]
@fzyzcjy I mentioned the updated docs including a workaround in my comment just [a few posts up](https://github.com/flutter/flutter/issues/66275#issuecomment-762720809); I wasn't able to test this myself yet but it sounds very promising!

**Comment by fzyzcjy** [comment]
@geisterfurz007 But that requires doubling the info.plist. and programmers can forget to keep the two files in sync (except for the one difference between two files)

Actually, my code works well *before flutter 2.0*. So I guess it is a problem enforced in flutter 2.0. Can there be a flag to close this feature in debug mode?

**Comment by lakszaidan** [comment]
@geisterfurz007 i just updated the http dependency into the latest one, and it solve the issue.

https://pub.dev/packages/http

**Comment by sarthak-sriw** [comment]
I am still

> They just want's to https on your labo and dev environments. This behaviour may be ommited following migration guide: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android.
> or... just add in android/app/src/main/AndroidManifest.xml:
> `android:usesCleartextTraffic="true"` to `<application/>`
> and above`<application/>`: `<uses-permission android:name="android.permission.INTERNET" />`
> like this:
> 
> ```
>     <uses-permission android:name="android.permission.INTERNET" />
>     <application
>             android:name="io.flutter.app.FlutterApplication"
>             android:label="receipt"
>             android:usesCleartextTraffic="true"
>             android:icon="@mipmap/ic_launcher">
> ```

I am still facing the issue I have made all the necessary changes but still I am getting same error of  **Bad state: Insecure HTTP is not allowed by platform: http://max-image-caption-generator-test.2886795296-80-host19nc.environments.katacoda.com/model/predict**

![image](https://user-images.githubusercontent.com/53507883/117477302-785b0000-af7b-11eb-8dea-fe4b023f62ca.png)

**Comment by tasmcan** [comment]
@sarthak-sriw  you need to add `android:usesCleartextTraffic="true"` inside `<application` not `<activity`

**Comment by flutterq** [comment]
[[Solved] Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform in a flutter
](https://fluttercorner.com/bad-state-insecure-http-is-not-allowed-by-platform-in-a-flutter/)
