### ISSUE TITLE
Flutter run not connecting to external device 

### ISSUE THREAD

**Issue by hossam-zaki** [flutter/flutter#66276]
Hello! I am running my flutter app on an external iPhone running the newest version of iOS 13. I upgraded flutter to the most recent stable version, and am unable to run on my phone properly. Here is the output.
![Screen Shot 2020-09-21 at 1 41 30 PM](https://user-images.githubusercontent.com/55958261/93801810-95bba380-fc10-11ea-8d64-41a6bc7f6257.png)

It just loads here forever. 

My phone used to work quite easily on the previous flutter build, but now on the most recent stable version, I am rarely able to run my flutter app on my external iOS device. Any help is appreciated.

**Comment by darshankawar** [comment]
Hi @hossam-zaki,
There's similar open issue describing your case, [65746](https://github.com/flutter/flutter/issues/65746).
Please follow-up there for updates and any questions.
Closing this as duplicate.
