### ISSUE TITLE
Task Manager shows black screen for flutter app

### ISSUE THREAD

**Issue by CristianTorrado** [flutter/flutter#66288]
Hi i have a bug with a lot of devices for example for Moto g 6 . 

The issue is the task manager shows a black screen for my flutter applications.

I debugged the Android native code and i found the issue. I think in certain circunstancies the screenshot save process for the preview is take more time than onResume() callback call. 

The onResume() callback is executing before the screenshot was ready to show in the task manager. 

I can avoid it adding a little delay into onResume() callback override into the MainActivity: 

```kotlin
 //Workaround to avoid error with screenshot in the task manager
    override fun onPause() {
        Thread.sleep(100)
        super.onPause()
    }
```

**Note** ( only to clarify ): The issue is not related with the **SECURE_FLAG** setup. 

Can you fix the issue into the FlutterActivity please ? 

I attached a stackoverflow issue reported from another programmer: 

https://stackoverflow.com/questions/62980801/flutter-app-showing-black-screen-in-task-manager-in-android-physical-device#

I attached the flutter doctor summary ( i am using the beta channel but the error is for the stable channel too ):

```shell
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (4 available)

• No issues found!

```

**Comment by darshankawar** [comment]
Hi @CristianTorrado,
There's similar open issue describing your case, which shows a black screen while switching to and from recent apps, [66212](https://github.com/flutter/flutter/issues/66212).
Although the root-cause for that issue is unknown yet, but the current behavior is same and happening on specific devices. Hence, I am closing this as duplicate.
If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by CristianTorrado** [comment]
> Hi @CristianTorrado,
> There's similar open issue describing your case, which shows a black screen while switching to and from recent apps, [66212](https://github.com/flutter/flutter/issues/66212).
> Although the root-cause for that issue is unknown yet, but the current behavior is same and happening on specific devices. Hence, I am closing this as duplicate.
> If you disagree, write in comments and I'll reopen.
> Thanks.

Thanks for your comments @darshankawar . I did't see the previous one.  
I will post this details in the main issue, to add more details there and help to we get a best fix from FlutterActivity.
