### ISSUE TITLE
Possible to hide the current snackbar when showsnackbar function is called

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#6628]
When showsnackbar is called and there's already a snackbar in the current scaffold, the snack bar won't show up until the current one disappear. Is there anyway to let the showsnackbar function also dismiss the current snackbar if there's one?

**Comment by abarth** [comment]
That behavior is according to the material design spec.  The snack bars are queued up and shown in turn.

Maybe we should add a function for dismissing the current snackbar so you can achieve that effect.

**Comment by abarth** [comment]
Looks like we already have https://docs.flutter.io/flutter/material/ScaffoldState/removeCurrentSnackBar.html

Does that do what you need?

**Comment by vy0592** [comment]
Yes, thanks!

**Comment by Hixie** [comment]
Is there anywhere that we could have mentioned that in the documentation to help you find it? (For example, where did you look for an answer before filing a bug?)

**Comment by vy0592** [comment]
I was mainly looking for answer inside showsnackbar function documentation and snackbar widget documentation

**Comment by Hixie** [comment]
Cool, thanks.

Adding a "see also: hideSnackBar" in the showSnackBar docs seems legit. Also SnackBar mentioning both show and hide seems reasonable.

**Comment by MarceloRab** [comment]
_scaffoldKey.currentState.removeCurrentSnackBar();

**Comment by kamleshwebtech** [comment]
`ScaffoldMessenger.of(context).removeCurrentSnackBar();`
