### ISSUE TITLE
Windows version of the Gallery App loads images at a lower resolution sometimes

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#66281]
The Gallery, when run on some Windows 10 devices, loads images at a lower resolution that looks horrible.

For instance, on a machine running Windows 10, GeForce RTX 2080, 2560 X 1440, 144hz, gsync monitor, a screen shot looks like this:

![gallery 9_21_2020 10_59_19 AM](https://user-images.githubusercontent.com/8867023/93807564-a879ac80-fbff-11ea-92cd-d1642db06f38.png)

On other devices, like a Windows Surface device, it looks like this:
<img width="1368" alt="Screenshot 2020-09-17 105539" src="https://user-images.githubusercontent.com/8867023/93807674-cf37e300-fbff-11ea-9aa4-fc87386d52c4.png">

Both are running Windows 10.

In the app with the low resolution images, it reports a device pixel ratio of 1.25.

**Comment by goderbauer** [comment]
Is this a dupe of https://github.com/flutter/flutter/issues/63122?

**Comment by gspencergoog** [comment]
Yes, could very well be.  It's not limited to Windows, it turns out.

Closing as a duplicate.

**Comment by jonahwilliams** [comment]
yes looks, like it - thanks!
