### ISSUE TITLE
cupertino_icons 1.0.0 need to be vertically centered

### ISSUE THREAD

**Issue by xster** [flutter/flutter#66285]
The font glyphs are currently centered horizontally but not vertically.

**Comment by jonbhanson** [comment]
I am having the same problem.  It makes my send button look wrong for sending a message:
![IMG_0138](https://user-images.githubusercontent.com/32202698/95906455-239a3280-0d68-11eb-976b-5a509e17c9da.jpeg)

**Comment by DanielEdrisian** [comment]
@jonbhanson Are you able to share a screenshot of what the inspector shows? The rectangular bounds?

**Comment by jonbhanson** [comment]
@DanielEdrisian here is the debug paint from the inspector:

![IMG_0142](https://user-images.githubusercontent.com/32202698/97185016-f2f9c600-1775-11eb-9925-a3a38d6269b9.jpeg)

**Comment by guopeng1994** [comment]
any updates?

**Comment by odonc** [comment]
Any update? This is makes CupertinoIcons basically unusable.

**Comment by xster** [comment]
This is fixed in cupertino_icons 1.0.2 via https://github.com/flutter/cupertino_icons/commit/aa20f42db00f6d3a7248a45c3a9928e219c8bb99. 

You can update your own project via `flutter pub upgrade`.

![Screen Shot 2020-12-16 at 12 26 23 AM](https://user-images.githubusercontent.com/156888/102323438-56fa6880-3f35-11eb-931e-f0cd4b53b411.png)
