### ISSUE TITLE
No console error message upon lack usage keys in info.plist

### ISSUE THREAD

**Issue by DanielEdrisian** [flutter/flutter#66298]
## Steps to Reproduce

1. Create a new project
2. Add `image_picker` to your dependencies and invoke call to ImagePicker.pickImage(source: ImageSource.gallery) using a button.
3. Do not add `<key>NSPhotoLibraryUsageDescription</key>` or `<key>NSCameraUsageDescription</key>` to your info.plist file.
4. Run the app and press the image picker button.

Or just comment out the key in your plist:
<img width="613" alt="Screen Shot 2020-09-21 at 3 47 57 PM" src="https://user-images.githubusercontent.com/11810973/93830118-2ea7ea00-fc24-11ea-8547-7e2917c93eb4.png">

**Expected results:** 

Something along the lines of printing this message in the console: 

> This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

**Actual results:** 

Flutter app crashed. No info about including necessary privacy keys in the console. Outputs:

> Lost connection to device.

<img width="995" alt="Screen Shot 2020-09-21 at 3 47 45 PM" src="https://user-images.githubusercontent.com/11810973/93830130-37002500-fc24-11ea-87fc-5ea14d55b89a.png">
<img width="250" alt="scr" src="https://user-images.githubusercontent.com/11810973/93830224-73338580-fc24-11ea-9b5d-2e8e7406c031.gif">

<details>
  <summary>Logs</summary>

```
```

> No issues found! (ran in 3.1s)

```
```

> [✓] Flutter (Channel master, 1.22.0-10.0.pre.206, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-10.0.pre.206 at /Users/danieledrisian/Desktop/flutter
    • Framework revision bb2ab8838a (5 days ago), 2020-09-16 11:22:02 -0700
    • Engine revision f84e7a0196
    • Dart version 2.10.0 (build 2.10.0-134.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danieledrisian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • iPhone 11 (mobile)     • 6C4CEDBA-B423-46A2-9033-9F7AB9249579 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • iPhone 11 Pro (mobile) • 7268A128-1E5B-4CD6-ACA5-4718E2EDA98C • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.

```
```

</details>

**Comment by xster** [comment]
Not a thorough exploration. But I have some suspicion that it may unfortunately be not possible to detect it at runtime. 

We're already being somewhat conservative in our permission getting https://github.com/flutter/plugins/blob/fce1eeee4ac3c97e3e1983a0ef1d08372088cbfc/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m#L192

It's not very explicit but it seems like Apple docs are saying that it's intended to just crash 

https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos
https://developer.apple.com/documentation/photokit/phphotolibrary/1620745-authorizationstatus?language=objc

We might be able to get more details by running the `ios/Runner.xcworkspace` project in Xcode instead of in the flutter tools. It might catch the exception before crashing, giving us a bit more hint.

**Comment by TahaTesser** [comment]
That's correct ` ios/Runner.xcworkspace` shows helpful message unlike Flutter where it just crashes without any indication 
### Xcode
```
2021-02-10 21:10:48.377042+0530 Runner[48495:572683] flutter: Observatory listening on http://127.0.0.1:62390/a4mFiH8Lt-E=/
2021-02-10 21:10:57.379778+0530 Runner[48495:572657] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
CoreSimulator 732.18.6 - Device: iPhone 12 (BAAA8897-8FC4-4E65-8A47-16C62B67FD83) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12
(lldb) 
```

Flutter
```bash
Launching lib/main.dart on Taha’s iPad in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           19.5s
Connecting to VM Service at ws://localhost:63060/ws
Lost connection to device.
Exited (sigterm)
```


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS 14.4
    • iPhone 12 (mobile)   • BAAA8897-8FC4-4E65-8A47-16C62B67FD83 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
! Doctor found issues in 3 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.255, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.255 at /Users/tahatesser/Code/flutter_master
    • Framework revision 278065284d (14 hours ago), 2021-02-09 17:51:03 -0800
    • Engine revision b3a18f5182
    • Dart version 2.13.0 (build 2.13.0-15.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.4
    • iPhone 12 (mobile)   • BAAA8897-8FC4-4E65-8A47-16C62B67FD83 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>

Thank you

**Comment by stuartmorgan** [comment]
@jmagman Do you happen to know where these permission error logs go? I'm not sure why we're not seeing them when we're not running via Xcode. Are we losing a stream when running via the tool? Are they only logged when there's a debugger attached?

**Comment by jmagman** [comment]
This should be resolved as of https://github.com/flutter/flutter/pull/66399.  The user was running a version from 6 days before that landed.
