### ISSUE TITLE
Application name is being concatenated on the package name when using flutter create --org

### ISSUE THREAD

**Issue by iMrLopez** [flutter/flutter#66297]
## Steps to Reproduce

1. Update Flutter to its latest version
2. Try to create a project with the `flutter create --org com.myorg.myapp MyApp` command
3. The build gradle inside applicationId gets something like this `com.myorg.myapp.MyApp` which breaks the build.
3.1 File location: `./android/app/build.gradle`
4. The AndroidManifest.xml files also get the package with the name concatenated on it
4.1. `/android/app/src/main/AndroidManifest.xml` 
4.2. `/android/app/src/debug/AndroidManifest.xml`
5. Also, the MainActivity gets the name and package concatenated too
5.1 `/android/app/src/main/kotlin/com/myorg/myapp/MyApp/MainActivity.kt`

## Logs
When building the application this is the outcome log:
```
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugGoogleServices'.            
> No matching client found for package name 'com.myorg.myapp.MyApp'
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                             
```

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G73, locale en-CR)
    • Flutter version 1.20.4 at /Users/mrlopez/Documents/DevEnv/flutter
    • Framework revision fba99f6cf9 (7 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/mrlopez/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by iMrLopez** [comment]
The same is happening here: `/android/app/src/main/AndroidManifest.xml` , the package gets the name concatenated on it

**Comment by darshankawar** [comment]
Hi @iMrLopez,
I followed all the steps you mentioned and was able to build the app properly without any issues. I am on latest stable (1.20.4)

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for Android SDK built for x86 to report its views...
```

Also, please see [this](https://flutteragency.com/change-package-name-in-flutter/) article. I believe the command you used to create a new app is usually used if you want to update the package name through your app.

Also, if you try to create new Flutter project from Android Studio, the flutter name is appended into the package name as below:

<img width="478" alt="Screenshot 2020-09-22 at 1 45 06 PM" src="https://user-images.githubusercontent.com/67046386/93858548-f367f280-fcd9-11ea-99e9-691fd3541c03.png">

**Comment by iMrLopez** [comment]
> Hi @iMrLopez,
> I followed all the steps you mentioned and was able to build the app properly without any issues. I am on latest stable (1.20.4)
> 
> ```
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> Installing build/app/outputs/flutter-apk/app.apk...
> Waiting for Android SDK built for x86 to report its views...
> ```
> 
> Also, please see [this](https://flutteragency.com/change-package-name-in-flutter/) article. I believe the command you used to create a new app is usually used if you want to update the package name through your app.
> 
> Also, if you try to create new Flutter project from Android Studio, the flutter name is appended into the package name as below:
> 
> <img alt="Screenshot 2020-09-22 at 1 45 06 PM" width="478" src="https://user-images.githubusercontent.com/67046386/93858548-f367f280-fcd9-11ea-99e9-691fd3541c03.png">

Hey @darshankawar I think we are getting something different based on what it says on that link:

> To avoid renaming the package and bundle identifier, **you can start your project using this command in your terminal**:
> flutter create --org com.yourdomain appname
> It’s recommended to run flutter clean after making changes.

Have a look at my video [here](https://youtu.be/ndoHwLzJLG0) if you want to see what is happening. What I understand is that the command should not append the appname to the domain if I include the full domain onto it 🤔

**Comment by darshankawar** [comment]
@iMrLopez  I am unable to open the video link. Could you resend.

**Comment by iMrLopez** [comment]
https://youtu.be/ndoHwLzJLG0 try again

**Comment by darshankawar** [comment]
@iMrLopez 
I followed all the steps you mentioned and was able to compile and run the app on emulator without any issues.
I am on latest stable (1.22.0).
Are you still getting this error ?
```
Execution failed for task ':app:processDebugGoogleServices'.            
> No matching client found for package name 'com.myorg.myapp.MyApp'
```

If so, that error indicates you may be using `google-services.json` file in which the package name must be conflicting.
Thanks

**Comment by iMrLopez** [comment]
This was a completely new application, so no `google-services.json` file was in it. I think I am on an old version, I will try pulling the latest stable and test again

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Stukz** [comment]
@pedromassangocode Hi i'm reopening this issue due that I'm facing it. 

Right now I'm trying to create a custom CLI for my job.

On (1 IMAGE) I'm prompting the user for the app info also the package name. So the behavior I'm expecting is if I go to android/app/build.gradle the applicationId should be com.example.app but it creates it com.example.app.Example (2 IMAGE)

(1 IMAGE)
![image](https://user-images.githubusercontent.com/57040392/117237546-cd1e3f80-adf0-11eb-9a2c-e4a170118484.png)

(2 IMAGE)
![image](https://user-images.githubusercontent.com/57040392/117237885-79f8bc80-adf1-11eb-9408-31191a2ea502.png)
