### ISSUE TITLE
Error trying to install flutter

### ISSUE THREAD

**Issue by alex1115alex** [flutter/flutter#66307]
I've just tried to reinstall Flutter from the AUR, and this is what happens whenever I try to run ```flutter```, or any other ```flutter``` commands, such as ```flutter doctor```.

Why is the download file corrupt?

Here are my specs and system info if they matter. https://i.imgur.com/93pNkQv.png

```
flutter doctor -v 
Downloading Dart SDK from Flutter engine d1bc06f032f9d6c148ea6b96b48261d6f545004f...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:-0  246M    0  380k    0     0   563k      0  0:07:28 --:--:--  0:03  246M    3 9854k    0     0  5855k      0  0:00:43  0:00:01  0:07  246M    7 18.8M    0     0  7127k      0  0:00:35  0:00:02  0:011  246M   11 27.7M    0     0  7710k      0  0:00:32  0:00:03  0:014  246M   14 36.7M    0     0  8054k      0  0:00:31  0:00:04  0:018  246M   18 45.7M    0     0  8244k      0  0:00:30  0:00:05  0:022  246M   22 55.3M    0     0  8489k      0  0:00:29  0:00:06  0:026  246M   26 65.2M    0     0  8695k      0  0:00:29  0:00:07  0:030  246M   30 74.2M    0     0  8758k      0  0:00:28  0:00:08  0:032  246M   32 81.1M    0     0  8587k      0  0:00:29  0:00:09  0:036  246M   36 90.1M    0     0  8611k      0  0:00:29  0:00:10  0:040  246M   40 98.8M    0     0  8667k      0  0:00:29  0:00:11  0:043  246M   43  108M    0     0  8746k      0  0:00:28  0:00:12  0:047  246M   47  117M    0     0  8797k      0  0:00:28  0:00:13  0:051  246M   51  126M    0     0  8790k      0  0:00:28  0:00:14  0:054  246M   54  135M    0     0  8827k      0  0:00:28  0:00:15  0:058  246M   58  144M    0     0  8880k      0  0:00:28  0:00:16  0:062  246M   62  154M    0     0  8919k      0  0:00:28  0:00:17  0:066  246M   66  163M    0     0  8948k      0  0:00:28  0:00:18  0:068  246M   68  169M    0     0  8841k      0  0:00:28  0:00:19  0:072  246M   72  178M    0     0  8845k      0  0:00:28  0:00:20  0:076  246M   76  188M    0     0  8890k      0  0:00:28  0:00:21  0:079  246M   79  197M    0     0  8913k      0  0:00:28  0:00:22  0:083  246M   83  207M    0     0  8959k      0  0:00:28  0:00:23  0:087  246M   87  216M    0     0  8966k      0  0:00:28  0:00:24  0:091  246M   91  225M    0     0  9003k      0  0:00:28  0:00:25  0:095  246M   95  235M    0     0  9021k      0  0:00:28  0:00:26  0:098  246M   98  244M    0     0  9031k      0  0:00:27  0:00:27 --:-100  246M  100  246M    0     0  9041k      0  0:00:27  0:00:27 --:--:-- 9493k
/opt/flutter/bin/cache/dart-sdk/bin/snapshots/dartdevc.dart.snapshotbad CRC 6c5fdaa5  (should be d9e419e2)

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

**Comment by iqbalmineraltown** [comment]
I'm totally newb to arch, haven't used it,
but is there any difference between cloning from AUR and git clone from Github?
also might want to check if AUR installing Flutter as root, IMHO it might cause problems with file ownership

I haven't seen any official docs about installing Flutter from AUR
AFAIK there are only download the tar file, `git clone`, or via `snapd` for Linux, have you tried any of them?

**Comment by alex1115alex** [comment]
>also might want to check if AUR installing Flutter as root, IMHO it might cause problems with file ownership
Well, that confirms it. After some searching around, I decided to try to uninstall Flutter completely `pamac remove flutter; sudo rm -rf /opt/flutter`, and then clone the git repo and install it that way.

The git version of Flutter threw some weird errors like before but then worked after I tried `flutter run` again. Odd. Anyway, it works now, thanks!

**Comment by iqbalmineraltown** [comment]
about this line:
> The git version of Flutter threw some weird errors like before but then worked after I tried `flutter run` again. Odd. Anyway, it works now, thanks!

You should have asked about this first as you are trying to follow officially supported installation steps but some error occurred. I presume most of us here are already have Flutter running by following those steps 😄 

Anyway, glad to hear that worked out!
