### ISSUE TITLE
Make class Color in Flutter more flexible

### ISSUE THREAD

**Issue by salkuadrat** [flutter/flutter#66301]
## Use case

Color in Flutter is great. But it's kinda limited by the way we initialize custom color.

## Proposal

I have created Flutter package named Colour to show the possible flexibility we can achieve with Color.
Can we make the official class Color to behave like this? 

[https://github.com/salkuadrat/colour](https://github.com/salkuadrat/colour)

```
Colour(0xFFFFFFFF)
Colour(0x00000000)

// with opacity
Colour(0xFFFFFFFF, 0.25)
Colour(0xFFFFFFFF, 0.5)

Colour('121212')
Colour('#121212')
Colour('af12dc')
Colour('#af12dc')
Colour('AF12DC')
Colour('#AF12DC')
Colour('FF121212')
Colour('#FF121212')
Colour('ff1212aa')
Colour('#ff1212aa')

// with opacity
Colour('121212', 0.25)
Colour('#121212', 0.5)
Colour('af12dc', 0.75)
Colour('#af12dc', 1.0)
Colour('AF12DC', 0.0)
Colour('#AF12DC', 0.25)
Colour('FF121212', 0.3)
Colour('#FF121212', 0.8)
Colour('ff1212aa', 0.6)
Colour('#ff1212aa', 0.42)

// RGB
Colour(255, 255, 255)
Colour(0, 0, 0)
Colour(120, 120, 80)

// ARGB
Colour(0, 255, 255, 255) // shorter than Color.fromARGB(0, 255, 255, 255)
Colour(255, 0, 0, 0)
Colour(75, 120, 120, 80)

// RGBO
Colour(255, 255, 255, 0.0) // shorter than Color.fromRGBO(255, 255, 255, 0.0)
Colour(0, 0, 0, 0.5)
Colour(120, 120, 80, 1.0)
```

**Comment by pedromassangocode** [comment]
Hi @salkuadrat
I'm not really sure if we can consider this as a valid proposal for Flutter, you can achieve the same result with the current implementation of the Color class. The Flutter team tries to leave the framework as simple as possible and any other feature can be supported as a package.

You did great in creating a package for this so now, everyone who wants this feature can simply use your package.

**Comment by salkuadrat** [comment]
Hi Pedro, thanks for your explanation.
I kinda wish it can be included, since I prefer to use the official Color than my own package.
It's not that much of a change.
