### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by michelle-marrion** [flutter/flutter#66319]
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=99Netsurfer008583 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader.load (package:yaml/src/loader.dart:48:25)
#2      loadYamlDocument (package:yaml/yaml.dart:51:25)
#3      loadYamlNode (package:yaml/yaml.dart:42:5)
#4      loadYaml (package:yaml/yaml.dart:34:5)
#5      _pluginFromPackage (package:flutter_tools/src/plugins.dart:304:27)
#6      findPlugins (package:flutter_tools/src/plugins.dart:335:27)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#15     loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#24     readAnyConfigFileUri (package:package_config/src/package_config_io.dart)
```
```
[✓] Flutter (Channel stable, 1.20.0, on Microsoft Windows [version 10.0.18362.1082], locale fr-CM)
    • Flutter version 1.20.0 at C:\src\flutter_windows_1.20.0-stable\flutter
    • Framework revision 840c9205b3 (7 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • 16M4HI105024 (mobile) • 99Netsurfer008583 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
### Plugins
cloud_firestore-0.14.0+2
cloud_firestore_web-0.2.0+1
firebase_auth-0.18.0+1
firebase_auth_web-0.3.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
path_provider_linux-0.0.1+2
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7

**Comment by darshankawar** [comment]
Hi @michelle-marrion,
It's not clear from the description, what exactly is the `yaml exception`. Can you provide the entire error log that points to `YamlException` along with `pubspec.yaml` ?
Thanks.

**Comment by michelle-marrion** [comment]
[+1117 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git
-c log.showSignature=false log -n 1 --pretty=format:%H
[+1072 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 840c9205b344a59e48a5926ee2d791cc5640924c
[   +2 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git
tag --contains HEAD
[+1098 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0
[  +54 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[ +262 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git
ls-remote --get-url origin
[ +476 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +678 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git
rev-parse --abbrev-ref HEAD
[ +511 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +730 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[ +135 ms] executing:
C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[ +374 ms] List of devices attached
           99Netsurfer008583      device product:storm model:16M4HI105024
device:16M4HI105024 transport_id:1
[  +40 ms]
C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk\platform-tools\adb.exe -s
99Netsurfer008583 shell getprop
[ +588 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[ +140 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[+1442 ms] Found plugin cloud_firestore at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\cloud_firestore-0.14.0+2\
[ +343 ms] Found plugin cloud_firestore_web at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[ +833 ms] Found plugin firebase_auth at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\firebase_auth-0.18.0+1\
[ +286 ms] Found plugin firebase_auth_web at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\firebase_auth_web-0.3.0+1\
[ +908 ms] Found plugin firebase_core at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\firebase_core-0.5.0\
[ +740 ms] Found plugin firebase_core_web at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\firebase_core_web-0.2.0\
[+1434 ms] Found plugin path_provider_linux at
C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\
pub.dartlang.org\path_provider_linux-0.0.1+2\
[+1975 ms] "flutter run" took 9 389ms.

[ +118 ms] Sending crash report to Google.
fichier
pubspec.yaml

thanks

Le mar. 22 sept. 2020 à 09:44, darshankawar <notifications@github.com> a
écrit :

**Comment by darshankawar** [comment]
@michelle-marrion will also need `pubspec.yaml`.  When do you get this exception ?
Thanks.

**Comment by michelle-marrion** [comment]
when it starts debugging, it starts and after that it shows me this exception.
Please I need to solve this problem very urgently. Thank you for your help


Le mar. 22 sept. 2020 à 13:39, darshankawar <notifications@github.com> a
écrit :

**Comment by michelle-marrion** [comment]
[ +986 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1926 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 840c9205b344a59e48a5926ee2d791cc5640924c
[   +2 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git tag --contains HEAD
[+9413 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0
[  +90 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +471 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git ls-remote --get-url origin
[ +211 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +513 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git rev-parse --abbrev-ref HEAD
[ +778 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +506 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +160 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +413 ms] executing: C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +247 ms] List of devices attached
           99Netsurfer008583      device product:storm model:16M4HI105024 device:16M4HI105024 transport_id:1
[  +32 ms] C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk\platform-tools\adb.exe -s 99Netsurfer008583 shell getprop
[ +386 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +58 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1664 ms] Found plugin cloud_firestore at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[ +734 ms] Found plugin cloud_firestore_web at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[ +672 ms] Found plugin firebase_auth at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[ +333 ms] Found plugin firebase_auth_web at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[ +122 ms] Found plugin firebase_core at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[ +213 ms] Found plugin firebase_core_web at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[ +961 ms] Found plugin path_provider_linux at C:\src\flutter_windows_1.20.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[ +371 ms] "flutter run" took 6 523ms.

[ +140 ms] Sending crash report to Google.
[+2519 ms] Crash report sent (report ID: 1d248bdf95769295)
[ +162 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1665 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[ +140 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +649 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +22 ms] executing: [C:\src\flutter_windows_1.20.0-stable\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[ +313 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 7 weeks ago
[ +219 ms] java -version
[+1436 ms] ro.hardware = mt6735
[   +1 ms] ro.build.characteristics = default
[ +838 ms] executing: C:\Users\ngami_4vnxadk\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
[+31392 ms] Attempting git.io shortener: https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+YamlException&body=%23%23+Command%0A%60%60%60%0Aflutter+--no-color+run+--machine+--verbose+--track-widget-creation+--device-id%3D99Netsurfer008583+--start-paused+--dart-define%3Dflutter.inspector.structuredErrors%3Dtrue+lib%5Cmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AYamlException%0A%60%60%60%0A%230++++++Parser.parse+%28package%3Ayaml%2Fsrc%2Fparser.dart%3A50%3A7%29%0A%231++++++Loader.load+%28package%3Ayaml%2Fsrc%2Floader.dart%3A48%3A25%29%0A%232++++++loadYamlDocument+%28package%3Ayaml%2Fyaml.dart%3A51%3A25%29%0A%233++++++loadYamlNode+%28package%3Ayaml%2Fyaml.dart%3A42%3A5%29%0A%234++++++loadYaml+%28package%3Ayaml%2Fyaml.dart%3A34%3A5%29%0A%235++++++_pluginFromPackage+%28package%3Aflutter_tools%2Fsrc%2Fplugins.dart%3A304%3A27%29%0A%236++++++findPlugins+%28package%3Aflutter_tools%2Fsrc%2Fplugins.dart%3A335%3A27%29%0A%237++++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%238++++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1100%3A19%29%0A%239++++++_FutureListener.handleValue+%28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%2310+++++Future._propagateToListeners.handleValueCallback+%28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%29%0A%2311+++++Future._propagateToListeners+%28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%2312+++++Future._completeWithValue+%28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2313+++++_AsyncAwaitCompleter.complete+%28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2314+++++_completeOnAsyncReturn+%28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%2315+++++loadPackageConfigWithLogging+%28package%3Aflutter_tools%2Fsrc%2Fdart%2Fpackage_map.dart%29%0A%2316+++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1198%3A47%29%0A%2317+++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1100%3A19%29%0A%2318+++++_FutureListener.handleValue+%28dart%3Aasync%2Ffuture_impl.dart%3A143%3A18%29%0A%2319+++++Future._propagateToListeners.handleValueCallback+%28dart%3Aasync%2Ffuture_impl.dart%3A696%3A45%29%0A%2320+++++Future._propagateToListeners+%28dart%3Aasync%2Ffuture_impl.dart%3A725%3A32%29%0A%2321+++++Future._completeWithValue+%28dart%3Aasync%2Ffuture_impl.dart%3A529%3A5%29%0A%2322+++++_AsyncAwaitCompleter.complete+%28dart%3Aasync-patch%2Fasync_patch.dart%3A40%3A15%29%0A%2323+++++_completeOnAsyncReturn+%28dart%3Aasync-patch%2Fasync_patch.dart%3A311%3A13%29%0A%2324+++++readAnyConfigFileUri+%28package%3Apackage_config%2Fsrc%2Fpackage_config_io.dart%29%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+1.20.0%2C+on+Microsoft+Windows+%5Bversion+10.0.18362.1082%5D%2C+locale+fr-CM%29%0A++++%E2%80%A2+Flutter+version+1.20.0+at+C%3A%5Csrc%5Cflutter_windows_1.20.0-stable%5Cflutter%0A++++%E2%80%A2+Framework+revision+840c9205b3+%287+weeks+ago%29%2C+2020-08-04+20%3A55%3A12+-0700%0A++++%E2%80%A2+Engine+revision+c8e3b94853%0A++++%E2%80%A2+Dart+version+2.9.0%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+30.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5Cngami_4vnxadk%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-30%2C+build-tools+30.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+1.8.0_242-release-1644-b01%29%0D%0A++++%21+Some+Android+licenses+not+accepted.++To+resolve+this%2C+run%3A+flutter+doctor+--android-licenses%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+4.0%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+version+49.0.2%0A++++%E2%80%A2+Dart+plugin+version+193.7547%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+1.8.0_242-release-1644-b01%29%0D%0A%0A%5B%21%5D+IntelliJ+IDEA+Ultimate+Edition+%28version+2019.3%29%0A++++%E2%80%A2+IntelliJ+at+C%3A%5CProgram+Files%5CJetBrains%5CIntelliJ+IDEA+2019.3.3%0A++++%E2%9C%97+Flutter+plugin+not+installed%3B+this+adds+Flutter+specific+functionality.%0A++++%E2%9C%97+Dart+plugin+not+installed%3B+this+adds+Dart+specific+functionality.%0A++++%E2%80%A2+For+information+about+installing+plugins%2C+see%0A++++++https%3A%2F%2Fflutter.dev%2Fintellij-setup%2F%23installing-the-plugins%0A%0A%5B%E2%9C%93%5D+Connected+device+%281+available%29%0A++++%E2%80%A2+16M4HI105024+%28mobile%29+%E2%80%A2+99Netsurfer008583+%E2%80%A2+android-arm+%E2%80%A2+Android+6.0+%28API+23%29%0A%0A%21+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+2d2a1ffec95cc70a3218872a2cd3f8de4933c42f%0A%23%23%23+Plugins%0Acloud_firestore-0.14.0%2B2%0Acloud_firestore_web-0.2.0%2B1%0Afirebase_auth-0.18.0%2B1%0Afirebase_auth_web-0.3.0%2B1%0Afirebase_core-0.5.0%0Afirebase_core_web-0.2.0%0Apath_provider_linux-0.0.1%2B2%0Ashared_preferences-0.5.10%0Ashared_preferences_linux-0.0.2%2B2%0Ashared_preferences_macos-0.0.1%2B10%0Ashared_preferences_web-0.1.2%2B7%0A%0A&labels=tool%2Csevere%3A+crash
[+1505 ms] ensureAnalyticsSent: 3ms
[   +8 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by michelle-marrion** [comment]
hello, please i need help

Le mar. 22 sept. 2020 à 18:05, ngami marrion <ngamimarrion@gmail.com> a
écrit :

**Comment by darshankawar** [comment]
@michelle-marrion Please provide your `pubspec.yaml` file.
Thanks,

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
