### ISSUE TITLE
nosuchmethoderror: the method 'tofilepath' was called on null.

### ISSUE THREAD

**Issue by liwei511** [flutter/flutter#66326]
## Steps to Reproduce
nosuchmethoderror: the method 'tofilepath' was called on null.

1. flutter run -d chrome
2. nosuchmethoderror: the method 'tofilepath' was called on null.

垃

**Comment by darshankawar** [comment]
Hi @liwei511,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Abhishek01039** [comment]
Hi @liwei511 
please refer this https://github.com/flutter/flutter/pull/52284 and duplication of https://github.com/flutter/flutter/issues/44459
Thanks

**Comment by jonahwilliams** [comment]
Fixed via  #52284

**Comment by duke7553** [comment]
@jonahwilliams I'm getting this now in Flutter 1.22.0 beta for web.

**Comment by jonahwilliams** [comment]
Actually fixed via https://github.com/flutter/flutter/commit/b9274c7c607bdb287d3b0483c5a3a8dcf5b35fcb sorry, this is on 1.23 which is not the current beta

**Comment by duke7553** [comment]
Ah thanks!
