### ISSUE TITLE
CupertinoTimerPickerMode.hm is broken

### ISSUE THREAD

**Issue by namrata-c** [flutter/flutter#66327]
[https://github.com/flutter/flutter/issues/36112](url)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

Still able to reproduce this issue on iphone SE(2nd generation) 13.5

**Comment by ShekharD175** [comment]
[https://github.com/flutter/flutter/issues/36112](https://github.com/flutter/flutter/issues/36112)  Please refer this link, this one was fixed before, but able to reproduce on flutter version 1.20.1

**Comment by pedromassangocode** [comment]
Hi @namrata-c 
I cannot reproduce this issue on latest `stable` channel.
Can you please upgrade to latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persist please provide your `flutter doctor -v` and a minimal complete reproducible sample code.
Thank you

**Comment by pedromassangocode** [comment]
Hi @namrata-c 
Looks like you are not on a valid Flutter channel.
Can you please upgrade to latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persist please provide your `flutter doctor -v` and minimal complete code sample.
Thank you
