### ISSUE TITLE
[Flutter_web] PWA opens mainfest.json instead of app

### ISSUE THREAD

**Issue by madhavtripathi05** [flutter/flutter#66321]
I've developed a PWA and hosted using Firebase, it works completely fine when opened from Url: https://omjgudhyog.web.app but when I install/add to the home screen and open from there it just loads manifest.json instead of the app. I'm not able to find out any related issue on the internet, Is there anything I'm missing out? here's a ss of page when I open the app.
![WhatsApp Image 2020-09-22 at 9 51 01 AM](https://user-images.githubusercontent.com/22491498/93844173-e63b0b80-fcb9-11ea-9d0b-ff6b1f1245ba.jpeg)

**Comment by jonahwilliams** [comment]
Looks like your start url might be wrong?  "start_url": "#/", should the hash be after the `/` ?

**Comment by madhavtripathi05** [comment]
> Looks like your start url might be wrong? "start_url": "#/", should the hash be after the `/` ?

Thanks! that did work, maybe provide a Note regarding this in docs: https://flutter.dev/docs/deployment/web
