### ISSUE TITLE
Web Flutter: Dead after multiple hot reloads

### ISSUE THREAD

**Issue by MaybeQHL** [flutter/flutter#66335]
## Details

**Target Platform: windows 10 
**Target OS version/browser: Google Chrome  84.0.4147.105 （64）
**Devices: **
   IDE:VS code 1.49.1

## Logs

```
```

```
```

When I use hot reloading many times, it doesn't work.

**Comment by darshankawar** [comment]
Hi @MaybeQHL,
the `hot realod` officially isn't supported on web yet. Please see [this](https://github.com/flutter/flutter/issues/53041) open ticket.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
