### ISSUE TITLE
[web] Card shadow not rendering on flutter_web when using ContinuousRectangleBorder or BeveledRectangleBorder

### ISSUE THREAD

**Issue by PhillDubois** [flutter/flutter#66334]
**Describe the bug**
Using this exact code on both web and mobile results in different rendered output. On mobile, the card has a shadow, on web not.

Working on web **(1)**:
```dart
Card(
  elevation: 10,
  child: Container(
    color: Colors.green,
    height: 100,
    width: 100,
  ),
)
```

**NOT** Working on web **(2)**:
```dart
Card(
  elevation: 10,
  shape: ContinuousRectangleBorder(),
  child: Container(
    color: Colors.green,
    height: 100,
    width: 100,
  ),
)
```

Working on web **(3)**:
```dart
Card(
  elevation: 10,
  shape: const RoundedRectangleBorder(
    borderRadius: BorderRadius.all(Radius.circular(0.0)),
  ),
  child: Container(
    color: Colors.green,
    height: 100,
    width: 100,
  ),
)
```

**NOT** Working on web **(4)**:
```dart
Card(
  elevation: 10,
  shape: const BeveledRectangleBorder(
    borderRadius: BorderRadius.only(
      bottomRight: Radius.elliptical(15, 15),
      topRight: Radius.elliptical(15, 15),
    ),
  ),
  child: Container(
    color: Colors.green,
    height: 100,
    width: 100,
  ),
)
```

## Steps to Reproduce
Use the widgets above and run on mobile, or web.

**Expected results:**
They should have shadows rendered.

**Actual results:** 
**(1)** - Has shadow
![image](https://user-images.githubusercontent.com/62962046/93865545-c100ca00-fcc6-11ea-8d9a-c0df76159803.png)
**(2)** - Has no shadow
![image](https://user-images.githubusercontent.com/62962046/93865490-b0e8ea80-fcc6-11ea-8cfb-42bbb01b0bbb.png)
**(3)** - Has shadow
![image](https://user-images.githubusercontent.com/62962046/93865430-9adb2a00-fcc6-11ea-9e9e-518905e8711f.png)
**(4)** - Has no shadow
![image](https://user-images.githubusercontent.com/62962046/93865229-551e6180-fcc6-11ea-90b1-e58b2cd1e67f.png)

**Flutter Doctor**
![image](https://user-images.githubusercontent.com/62962046/93865727-fdccc100-fcc6-11ea-92f4-ca4d76b15622.png)

**Comment by darshankawar** [comment]
Issue replicable on latest beta. Card with `ContinuousRectangleBorder()` and `BeveledRectangleBorder()` doesn't render the shadow.

<img width="245" alt="Screenshot 2020-09-22 at 5 10 12 PM" src="https://user-images.githubusercontent.com/67046386/93877997-0341ff80-fcf7-11ea-9234-8141125ec8ae.png">
<img width="217" alt="Screenshot 2020-09-22 at 5 10 56 PM" src="https://user-images.githubusercontent.com/67046386/93878004-050bc300-fcf7-11ea-9559-7e67a8641712.png">
<img width="219" alt="Screenshot 2020-09-22 at 5 11 44 PM" src="https://user-images.githubusercontent.com/67046386/93878007-05a45980-fcf7-11ea-98b6-b51672830401.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile)  • emulator-5554
      • android-x86    • Android 10 (API 29) (emulator)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
May be related to [32215](https://github.com/flutter/flutter/issues/32215)

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/65498
