### ISSUE TITLE
dart:async is not required at some places.

### ISSUE THREAD

**Issue by Himanshuranjan30** [flutter/flutter#66336]
dart:async is not required at some places for future and streams as they are already in dart:core which is automatically imported as per Dart 2.1

**Comment by darshankawar** [comment]
Hi @Himanshuranjan30,
Please elaborate on your issue. When you say `at some places`, what do you mean exactly ? Are you facing any issue with that import or causing any unusual behavior ? Also, what difference do you see when you don't use it as compared to when you use it ?
Thanks.

**Comment by Himanshuranjan30** [comment]
dart:async is imported when you use Future or Stream right? So after Dart 2.1 Future and Streams are covered in dart:core package which us automatically imported into the dart files.So no need to import dart: async now.

**Comment by darshankawar** [comment]
@Himanshuranjan30 thanks for the details.
So if we don't need to import that package, we can simply ignore it right ? 
Also, can you elaborate on what's your aim with this ticket ? Is it a proposal, a feature request or just a question on documentation ?
Thanks.

**Comment by Himanshuranjan30** [comment]
yea, we can simply remove that package so the code looks a bit clean.My aim is just to propose a change that bring the number of lines of code down and can help in better understanding @darshankawar .

**Comment by darshankawar** [comment]
@Himanshuranjan30 this proposal may not be related to Flutter, but is more suitable for `dartlang`. Also, I see a similar open ticket in their repo that describes your case too, [34401](https://github.com/dart-lang/sdk/issues/34401).
Please follow-up there for updates and any questions you may have.
Closing this, as it's not related to Flutter. If you disagree, write in comments and I'll reopen.
Thanks.
