### ISSUE TITLE
Documentation - Making animations easier to grasp.

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6633]
The documentation on animations on flutter's  [website](https://flutter.io/animations/) is great but it lacks code samples or implementation example. After reading the docs, it is easy to understand the whereabouts of the animation architecture (more or less though) but difficult to know where to start.
In my opinion, adding code samples will make the documentation way more readable and understandable.

**Comment by eseidelGoogle** [comment]
I believe @qchong has an in-progress re-write of the animations doc?

**Comment by nelsonkam** [comment]
Great ! Is there any draft I could checkout ? Trying to play with animations in a sample app.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/website/pull/283 is likely what I'm thinking of.  Not sure the current status.

**Comment by nelsonkam** [comment]
@eseidelGoogle  Thanks !

**Comment by Sfshaza** [comment]
The animation docs have been reworked (twice) since this bug was filed. Closing.
