### ISSUE TITLE
Add missing `onSelectionHandleTapped` to `CupertinoTextField`

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#66347]
~~There are two places where code to deal with selection handle taps is duplicated (`material/text_field` and `selectable_text`). The behavior is also missing from `CupertinoTextField`. Fix this by making this method a default for `EditableText.onSelectionHandleTapped`.~~

Simply add it to `CupertinoTextField`, since it relies on internals. Also moved a couple methods around to keep things in the same order in the two other places it exists

**Comment by DanielEdrisian** [comment]
> Fix this by making this method a default for `EditableText.onSelectionHandleTapped`.

Just for clarification, what method are you referring to when saying "this"?

**Comment by guidezpl** [comment]
The method is `_handleSelectionHandleTapped` found in both `material/text_field` and `selectable_text`

**Comment by guidezpl** [comment]
This is actually as designed, closing
