### ISSUE TITLE
Ability to use the underlying Driver in Flutter Web Driver Tests

### ISSUE THREAD

**Issue by goncalo-palma-3r** [flutter/flutter#66344]
**Problem**

When doing Flutter Driver tests, we may need to access the underlying driver, for example to do testing on IFrames.

From what I've seen, Flutter driver accesses the `window.$fluterDriver` variable to issue Flutter Driver commands, now my question is: how can I use the driver to send raw commands that have nothing to do with Flutter?

Case in point: I want to access an IFrame and manipulate it on testing. Since it's not under the localhost domain, I cannot have access to it directly due to CORS, so running a custom JS script is not possible (I tried it before). So the only feasible way is to access ChromeDriver and drive the tests.

If not possible, where can I get more information about the Driver being used? Maybe I can access it or expose it in the `window` variable and manipulate the tests that way.

**Comment by nturgut** [comment]
you can reach the underlying driver. Example code from [PR](https://github.com/flutter/engine/pull/21383/files#diff-a375f2eeabeb4e4f443b7f688f0ba20fR40)

```
 final WebFlutterDriver driver =
      await FlutterDriver.connect() as WebFlutterDriver;

  // Learn the browser in use from the webDriver.
  final String browser = driver.webDriver.capabilities['browserName'] as String;
```

Please let me know if it's enough for your use case?

**Comment by goncalo-palma-3r** [comment]
@nturgut the `capabilities` let us access information about the current browser? Or does it let us access the current driver and drive tests?

The current situation is the following:

1. I use Flutter driver to open a new page that has an IFrame
2. I use the Chrome Driver to test that IFrame
3. Eventually we go to another Flutter page in which we can resume testing via Flutter Driver

**Comment by nturgut** [comment]
@goncalo-palma-3r I shared capabilities as an example. During your tests you can access WebDriver (assuming you started the tests with `--browser_name=chrome` it be chromedriver) using the code that I shared:

```
final WebFlutterDriver driver = await FlutterDriver.connect() as WebFlutterDriver;
final WebDriver webDriver = driver.webDriver;
```

WebDriver is a dart package: https://pub.dev/packages/webdriver You can read the repo to see what are the features/methods available for your use: https://github.com/google/webdriver.dart 
For example I know it has a `get` method for example you can use to "navigates to the specified url".

If you want to use features from FlutterDriver use the `driver` variable instead. So for your test scenario all building blocks already exist.
