### ISSUE TITLE
Sliders Number Problem

### ISSUE THREAD

**Issue by erenalpt** [flutter/flutter#66341]
Hi. Flutter is a great project. But I came across something strange while using sliders. The numbers are rolling. Is this normal? I created it as a double. However, this sounded very strange. Is it normal to round the numbers?

[https://i.ibb.co/yfD7FBp/sliderxcf.jpg](https://i.ibb.co/yfD7FBp/sliderxcf.jpg)

  double sliders = 1;

            Text("Selected Sliders"),
            Slider(
              min: 0,
              value: sliders,
              max: 100,
              onChanged: (value) {
                setState(() {
                  sliders = value;
                });
              },
              divisions: 100,
              label: sliders.toString(),
            ),

All done!
[✓] Flutter: is fully installed. (Channel stable, 1.20.4, on Linux,
    locale tr_TR.UTF-8)
[!] Android toolchain - develop for Android devices: is partially
    installed; more components are available. (Android SDK version
    30.0.2)
[✓] Android Studio: is fully installed. (version 4.0)
[!] Android Studio: is partially installed; more components are
    available.
[✓] Connected device: is fully installed. (1 available)

**Comment by darshankawar** [comment]
Hi @erenalpt,
What issue are you seeing exactly ? The screenshot you shared doesn't reveal much. I tried the official Slider [example](https://api.flutter.dev/flutter/material/Slider-class.html) and was able to see the number slide properly without any issues.
Thanks.

**Comment by erenalpt** [comment]
> Hi @erenalpt,
> What issue are you seeing exactly ? The screenshot you shared doesn't reveal much. I tried the official Slider [example](https://api.flutter.dev/flutter/material/Slider-class.html) and was able to see the number slide properly without any issues.
> Thanks.

Yes it is slipping. It just doesn't increase 1 to 1. I think it should go 28-29-30. But it looks like 28.xxxxx instead of 29 as in the picture. This happens at intervals, not for every number.  I am using the Genymotion emulator.

**Comment by darshankawar** [comment]
@erenalpt I don't see the number slipping. Tested on latest beta using Slider official example as mentioned above.

[66341.mov.zip](https://github.com/flutter/flutter/files/5261702/66341.mov.zip)

Can you try on a physical device and see if you get same behavior ? Also please try the Slider official example.
Thanks.

**Comment by erenalpt** [comment]
> e
I'll look at the slider image example. Why am I facing such a situation with the above code. I wonder this.

Video:
[https://streamable.com/sj0rzq](https://streamable.com/sj0rzq)

**Comment by erenalpt** [comment]
> > e
> > I'll look at the slider image example. Why am I facing such a situation with the above code. I wonder this.
> 
> Video:
> https://streamable.com/sj0rzq

I tried it on Xiaomi Mi 8. I still have the same problem with the video. No code errors. Because my code, flutter is the same as the official document.

**Comment by darshankawar** [comment]
I am unable to replicate the issue on devices I tried, but it seems to be happening on certain devices. Keeping this issue open for further analysis.

**Comment by erenalpt** [comment]
> I am unable to replicate the issue on devices I tried, but it seems to be happening on certain devices. Keeping this issue open for further analysis.

Devices I have tried: Xiaomi mi 8, Mi 8 lite (physical device ), and genymotion emulator Google Pixel (API 28 - 9.0), Nexus 4 (API 19 - 4.4), Amazon Fire HD 10 (API 28 - 9.0).

**Comment by darshankawar** [comment]
@erenalpt 
Revisiting this issue, I used Sliders [example](https://api.flutter.dev/flutter/material/Slider-class.html#material.Slider.1) running with latest stable version and on Pixel XL api 33 emulator with which I didn't observe the reported behavior. Can you please try the same at your end on listed devices you mentioned using latest stable to check if the behavior still persist or not ?
