### ISSUE TITLE
Flutter/Plugins `lint_darwin_plugins` is flaky postsubmit

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#66363]
Some example failure logs:
https://cirrus-ci.com/task/4810578143215616
https://cirrus-ci.com/task/6185259014291456

```
ERROR | [iOS] unknown: Encountered an unknown error (CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_2_c_c.txt Response: 400) during validation.
```

**Comment by cyanglaz** [comment]
CC @dnfield

**Comment by dnfield** [comment]
This appears to be failures to reach out to the cocoapods CDN during CI. We should probably add retries for this kind of failure.

**Comment by jmagman** [comment]
They had an outage today, there were failures everywhere.
https://status.cocoapods.org/

**Comment by cyanglaz** [comment]
Lowered priority as it seems to be some temporary outage of cocoa-pods.
I think we can either close this issue or implement some re-tries for similar network errors if possible.

**Comment by cyanglaz** [comment]
Closing it because the failure was caused by cocoa-pods service outage.
