### ISSUE TITLE
[Desktop] If D3D11 is unavailable we fail to fallback to D3D9 and Flutter doesn't start

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#66374]
See https://github.com/flutter/flutter/issues/51286 for more background.

It looks like we need to implement fallback paths for:

D3D11 -> D3D9 -> Software

**Comment by darshankawar** [comment]
Going ahead and labelling it based on these discussions in [51286](https://github.com/flutter/flutter/issues/51286)

https://github.com/flutter/flutter/issues/51286#issuecomment-696945527

https://github.com/flutter/flutter/issues/51286#issuecomment-696963192

https://github.com/flutter/flutter/issues/51286#issuecomment-696935561

**Comment by stuartmorgan** [comment]
Adding to the beta list for doing at least D3D9 fallback, for broader compatibility. Software fallback is probably post-beta, but we can evaluate.

**Comment by clarkezone** [comment]
A working solution has been developed for this: https://github.com/flutter/flutter/issues/51286#issuecomment-715317721

**Comment by zhileichen** [comment]
Here are what I found.

1. The `warp_display_attributes` is as same as `default_display_attributes` in [angle_surface_manager.cc](https://github.com/flutter/engine/blob/master/shell/platform/windows/angle_surface_manager.cc).
And D3D11 WARP (software rendering) works after setting `EGL_PLATFORM_ANGLE_DEVICE_TYPE_ANGLE` to `EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE`
```
 const EGLint warp_display_attributes[] = {
      // These attributes request D3D11 WARP (software rendering fallback) as a
      // last resort.
      EGL_PLATFORM_ANGLE_TYPE_ANGLE,
      EGL_PLATFORM_ANGLE_TYPE_D3D11_ANGLE,
      EGL_PLATFORM_ANGLE_DEVICE_TYPE_ANGLE, 
      EGL_PLATFORM_ANGLE_DEVICE_TYPE_D3D_WARP_ANGLE,
      EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE,
      EGL_TRUE,
      EGL_NONE,
  };
```
2. The attribute `EGL_PLATFORM_ANGLE_ENABLE_AUTOMATIC_TRIM_ANGLE`  will not work on some Windows 7 devices, which failed to get a compatible EGLdisplay.

**Comment by kf6gpe** [comment]
Talked to @gw280, we believe this is done and can be closed.
