### ISSUE TITLE
Adding webview_flutter package issue 

### ISSUE THREAD

**Issue by Shaho87** [flutter/flutter#66381]
I want to add webview_flutter: ^0.3.23 in pubspec.yaml but it gives below error 

```
[webviewexample] flutter pub get
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Running "flutter pub get" in webviewexample...                  
The current Flutter SDK version is 0.0.0-unknown.
Because webviewexample depends on webview_flutter >=0.0.1+1 which requires Flutter SDK version >=0.11.9, version solving failed.
pub get failed (1; Because webviewexample depends on webview_flutter >=0.0.1+1 which requires Flutter SDK version >=0.11.9, version solving failed.)
exit code 1
```

then when I run flutter doctor -v I got below 

PS C:\Users\click\Desktop\flutter webview> flutter doctor -v
```
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1
--pretty=format:%ad --date=iso
Standard out: 
Standard error: fatal: bad config line 1 in file .git/config

Returning 1970-01-01 03:00:00.000 instead.
[√] Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 0.0.0-unknown at C:\src\flutter
    • Framework revision  (), 1970-01-01 03:00:00.000
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
```

**Comment by hamdikahloun** [comment]
Hi @Shaho87 

Can you run `flutter upgrade --force` please and try again

**Comment by Shaho87** [comment]
I run it and below is the result 
PS C:\Users\click\Desktop\flutter webview> flutter upgrade --force
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
ProcessException: Process exited abnormally:
fatal: bad config line 1 in file .git/config
  Command: git fetch --tags

**Comment by hamdikahloun** [comment]
Please check this link [stackoverflow](https://stackoverflow.com/questions/52397496/flutter-upgrade-fail)

**Comment by darshankawar** [comment]
Hi @Shaho87 
There seems to be something wrong with your Flutter installation, as its showing `The current Flutter SDK version is 0.0.0-unknown.`
Please reinstall Flutter from the official link [here](https://flutter.dev/docs/get-started/install), and try again to see if it works for you.
You may also check [this](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted) link for more help on the issue.

**Comment by Shaho87** [comment]
Dears,
 I have delete and reinstall flutter the issue has been fixed thanks a lot .
