### ISSUE TITLE
Migrate Flutter Gallery test to NNBD

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#66395]
Tracks the migration to NNBD, which includes all the dependencies.

## Dependencies

Dependency | Current version | Owner | Issue/PR
-- |-- | -- | -- 
connectivity | 0.4.9+2 | Flutter Ecosystem
connectivity_for_web | 0.3.1+2 | Flutter Ecosystem
connectivity_macos | 0.1.0+4 | Flutter Ecosystem
connectivity_platform_interface | 1.0.6 | Flutter Ecosystem
device_info | 0.4.2+7 | Flutter Ecosystem
device_info_platform_interface | 1.0.1 | Flutter Ecosystem
plugin_platform_interface | 1.0.2 | Flutter Ecosystem | https://github.com/flutter/plugins/pull/3115
url_launcher | 5.5.3 | Flutter Ecosystem
url_launcher_linux | 0.0.1+1 | Flutter Ecosystem
url_launcher_macos | 0.0.1+7 | Flutter Ecosystem
url_launcher_platform_interface | 1.0.8 | Flutter Ecosystem
url_launcher_web | 1.3+2 | Flutter Ecosystem 
video_player | 0.10.6 | @blasten | https://github.com/flutter/plugins/pull/3045
video_player_platform_interface | 1.0.5 | @blasten | https://github.com/flutter/plugins/pull/3045
video_player_web | 0.1.2+3 | Flutter Ecosystem
flutter | <flutter repo> | Flutter Framework | https://github.com/dart-lang/sdk/issues/40146
flutter_web_plugins | <flutter repo> | @ditman | ~~https://github.com/flutter/flutter/issues/69843~~
intl | 0.16.1 | Dart SDK
pub_semver | 1.4.4 | Dart SDK
platform_detect | 1.4.0 | @ditman | ~~https://github.com/flutter/flutter/issues/66385~~
scoped_model | 1.0.1 | 3P
pigeon | 0.1.10 | @gaaclarke | https://github.com/flutter/flutter/issues/59118

/cc @pcsosinski

**Comment by ditman** [comment]
I'll find out if anybody's working on `flutter_web_plugins`, and take it next if nobody is.

**Comment by pomegra** [comment]
leave a comment

**Comment by stuartmorgan** [comment]
`url_windows` will be on this last as of a couple of days ago.

**Comment by stuartmorgan** [comment]
I just checked all the desktop plugins (`url_launcher_windows/macos/linux`, `connectivity_macos`) and they are all using the traditional model of implementing a shared platform channel interface, so none of them have any Dart code outside of the `example/` (which presumably won't need to be migrated for Gallery)

**Comment by kevmoo** [comment]
As discussed elsewhere, the dependency on `scoped_model` should likely be **dropped**.
* It's a 1-file package. (Should be easy to replace/inline)
* It hasn't been touched in ~2 years

CC @pcsosinski
