### ISSUE TITLE
Error thrown by handler. FileSystemException: Cannot open file, path (OS Error: The system cannot find the path specified , errno = 3)

### ISSUE THREAD

**Issue by liwei511** [flutter/flutter#66415]
`
F:\flutter\demo123>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
 9,339ms (!)
ERROR - 2020-09-23 12:03:02.149837
GET /dwds/src/injected/client.js
Error thrown by handler.
FileSystemException: Cannot open file, path = 'C:\b\s\w\ir\k\archive\flutter\.pub-cache\hosted\pub.dartlang.org\dwds-6.0.0\lib\src\injected\client.js' (OS Error: 系统找不到指定的路径。
, errno = 3)
dart:isolate  _RawReceivePortImpl._handleMessage
`

![image](https://user-images.githubusercontent.com/18389869/93965490-d2180c80-fd94-11ea-8d9a-3617f449fbc9.png)

flutter doctor: 

`
F:\flutter\demo123>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.23.0-4.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.49.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

`

![image](https://user-images.githubusercontent.com/18389869/93965512-e5c37300-fd94-11ea-9ed3-568030093f3e.png)

**Comment by maxzod** [comment]
same thing here just new project & run i will try another sdk

**Comment by jmagman** [comment]
We believe this is fixed as of https://github.com/flutter/flutter/pull/65814, which is currently only available on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels).
