### ISSUE TITLE
 EXCEPTION CAUGHT BY SCHEDULER LIBRARY 

### ISSUE THREAD

**Issue by shubhamkatake** [flutter/flutter#66433]
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2623 pos 16: 'node.parent ==
flutter: null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2623:16)
flutter: #3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1087:23)
flutter: #4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:409:21)
flutter: #5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #13     _invoke (dart:ui/hooks.dart:253:10)
flutter: #14     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

While Running flutter Application I am getting this Error

**Comment by hamdikahloun** [comment]
Hi @shubhamkatake 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Hi @shubhamkatake 
I see there's an open issue (https://github.com/flutter/flutter/issues/41134) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
