### ISSUE TITLE
UI - ImeOption on android is null for text fields.

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6643]
While playing with the Gallery app, I noticed that the imeOption of the keyboard was null for all text fields. 

![1478047805241](https://cloud.githubusercontent.com/assets/8492909/19922554/66060cb6-a0e3-11e6-8988-57e5e62c5a64.jpg)

## Device
**TECNO L8** - Running Android 5.1.1

**Comment by eseidelGoogle** [comment]
Thanks for the report!  @jason-simmons or @mpcomplete  are probably our best bet here.

**Comment by mpcomplete** [comment]
It started when we switched away from mojo. The offending line is: https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L75

mConfiguration.getString("actionLabel") is "null" (the string, not `null` itself). If it is `null`, we get a proper submit icon.

Maybe this is a JSON translation error. @abarth ?

**Comment by abarth** [comment]
Seems likely.  We're probably messing up JSON somehow.
