### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by marshallunduemi** [flutter/flutter#66434]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
C:\Users\CodeXpress\Documents\flutter>flutter doctor -v
Downloading android-arm-profile/windows-x64 tools...                2.9s
Downloading android-arm-release/windows-x64 tools...                2.5s
Downloading android-arm64-profile/windows-x64 tools...              2.8s
Downloading android-arm64-release/windows-x64 tools...              2.7s
Downloading android-x64-profile/windows-x64 tools...                3.2s
Downloading android-x64-release/windows-x64 tools...                3.4s
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19042.508], locale en-US)
    • Flutter version 1.20.4 at C:\src\flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\CodeXpress\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\CodeXpress\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by 865102930** [comment]
You don't have AS.

**Comment by hamdikahloun** [comment]
Hi @marshallunduemi 

Can you please connect the Android device with debug mode enabled and run : 

1. `flutter create newapp`

2. `cd newapp`

3. `flutter run -v`

**Comment by pedromassangocode** [comment]
Hi @marshallunduemi 
Why you cannot create a Flutter project? I see you have VS code installed, did you faced any crash?

**Comment by KevalPrajapati** [comment]
Provide the error you get when you try to create project.

**Comment by marshallunduemi** [comment]
> 3\. flutter run -v

Thanks greatly, it works with connected device on debug mode

**Comment by marshallunduemi** [comment]
> Hi @marshallunduemi
> Why you cannot create a Flutter project? I see you have VS code installed, did you faced any crash?

I connected device, now is working. thanks a lot

**Comment by marshallunduemi** [comment]
> You don't have AS.

Ok thanks

**Comment by pedromassangocode** [comment]
Hi @marshallunduemi 
Given your message at https://github.com/flutter/flutter/issues/66434#issuecomment-698316685 I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
