### ISSUE TITLE
Packages conflict with first party

### ISSUE THREAD

**Issue by prajwalprajwal** [flutter/flutter#66438]
You have a dependency on `cupertino_icons` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter_test` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78

This is showing in the terminal, while running on web, please help me.

**Comment by pedromassangocode** [comment]
Hi @prajwalprajwal 
What command did you executed to have this messages? Can you please provide your `flutter doctor -v`, your `pubspec.yaml`?
Thank you

**Comment by prajwalprajwal** [comment]
> Hi @prajwalprajwal
> What command did you executed to have this messages? Can you please provide your `flutter doctor -v`, your `pubspec.yaml`?
> Thank you

I just try to run, first flutter web program. It is just a default program of clicking on button.

**Comment by pedromassangocode** [comment]
Hi @prajwalprajwal 
It is till useful to me to try to reproduce the issue.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
