### ISSUE TITLE
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file

### ISSUE THREAD

**Issue by marshallunduemi** [flutter/flutter#66432]
Was trying to create flutter project

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\CodeXpress\Documents\flutter\ssample\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\src\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".
 
A crash report has been written to C:\Users\CodeXpress\Documents\flutter\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+copy+file+to+%27C%3A%5CUsers%5CCodeXpress%5CDocuments%5Cflutter%5Cssample%5Candroid%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27%2C+path+%3D+%27C%3A%5Csrc%5Cflutter%5Cpackages%5Cflutter_tools%5Ctemplates%5Capp%5Candroid.tmpl%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JUgEt

**Comment by hamdikahloun** [comment]
Hi @marshallunduemi 

Can you please provide your `flutter doctor -v` and your `flutter create -v newapp` ?
Thank you

**Comment by pedromassangocode** [comment]
Hi @marshallunduemi 
I see there's an open issue (https://github.com/flutter/flutter/issues/66432) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
