### ISSUE TITLE
Receive an notification when hot restart

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#66447]
Is there any way that dart code could receive a notification when developer call hot reload(r) or hot restart(R)?

## Use case

Hot restart will break the lifecycle of the Flutter app, some methods won't be called such as `dispose()`. So there may be some native resources or objects that depend on `dispose()` to release, which will not be released.

For example, there's a native video player, and sending player a channel message in `dispose()` in order to tell the native player that player should  be released. Without the `dispose()`, the player won't be released when hot restart.

## Proposal

Is possible to call `dispose()` or call a listener for Flutter code when developer call hot restart?

**Comment by pedromassangocode** [comment]
Hi @talisk 

I'm not sure why do you want to release resource on hot-restart but after Hot-restart your app is just "restarted" and your app will start as it was just opened again.

Please see https://www.educative.io/edpresso/understanding-flutter-hot-reload-and-hot-restart-the-simplest-way.

Closing this as an invalid proposal.
