### ISSUE TITLE
Pigeon: List is not supported in method arguments

### ISSUE THREAD

**Issue by matejdro** [flutter/flutter#66446]
## Steps to Reproduce

Run `flutter pub run pigeon` on top of the following snippet:

```
@HostApi()
abstract class TestApi {
  void provideList(List list);
}
```

**Expected results:** 

Pigeon with List should get generated

**Actual results:**

Generation will error out with `Error: pigeons/pigeons.dart: Unsupported argument type: "List" in API: "TestApi" method: "provideList`

@gaaclarke

**Comment by pedromassangocode** [comment]
Hi @matejdro 
Can you please provide the pigeon version you are using and for what language are you trying to convert?
Thank you

**Comment by gaaclarke** [comment]
You can't use datatypes directly, you have to make a class like so:
```dart
class Foo {
  List list;
}

@HostApi()
abstract class TestApi {
  void provideList(Foo foo);
}
```

There is an outstanding feature request to support builtin datatypes directly.

**Comment by matejdro** [comment]
Can you link to the feature request, please? I could not find it.

**Comment by pedromassangocode** [comment]
Closing as invalid issue.

**Comment by gaaclarke** [comment]
@matejdro I couldn't find it either.  It's something we've discussed, maybe there isn't a feature request for it.  I made one: https://github.com/flutter/flutter/issues/66467
