### ISSUE TITLE
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by dkuye** [flutter/flutter#66454]
Getting this error

```

════════ Exception caught by gesture library ═══════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
I/MediaPlayerNative( 3323): MediaPlayer::notify() prepared
V/MediaPlayer( 3323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3323): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3323): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3323): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3323): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3323): cleanDrmObj: mDrmObj=null mDrmSessionId=null

════════ Exception caught by gesture library ═══════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

```

**Comment by darshankawar** [comment]
Hi @dkuye,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by dkuye** [comment]
@darshankawar Here is my flutter doctor -v output. Thanks.



[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale en-NG)
    • Flutter version 1.20.3 at /Users/dejikuye/flutter
    • Framework revision 216dee60c0 (3 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dejikuye/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@dkuye Would also need a minimal complete reproducible code sample that shows the issue you are facing. Without it, it'll be hard to know what's the exact cause.
Thanks.

**Comment by dkuye** [comment]
Ok, first, let me describe what is causing the problem. It's a children app I'm developing. It contains multiple buttons and images per screen that makes certain sound on-tap. When two or more buttons or images are tapped at the same time, I get that error and the app freezes. 

Everything works fine until the kids tapped two or more buttons or images at the same time.

**Comment by dkuye** [comment]
I'm using FlatButton widget for those buttons
`FlatButton(
    onPressed: () {
        player(fileName);
    },
    child: Text(...)
)`

I use InkWell widget for those images
`InkWell(
    onTap: () {
        player(fileName);
    },
    child: Image.asset(...),
)`

And I'm audioplayers package to play the audio files.
`
import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';

Future<AudioPlayer> player(String fileName) async {
  AudioCache cache = new AudioCache();
  return await cache.play("sounds/" + fileName);
}`

**Comment by darshankawar** [comment]
@dkuye 
`audioplayers` is a 3rd party plugin. We would need a minimal complete code sample that we can simply copy paste and run to see the issue. Please provide the same.
Thanks.

**Comment by darshankawar** [comment]
Also please see [this](https://github.com/flutter/flutter/issues/36350#issuecomment-512567501) ticket and comment for similar error you are getting, but scenario could be different and what code to provide to replicate the issue.

**Comment by ztigunes** [comment]
i have same issue. Are there any bug fix or workaround solution ? When i use tabbar like dummy user with two or three finger (gesture) it freeze all tab bar views.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 416 pos 12: '_initialButtons ==
flutter: kPrimaryButton': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter: https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2 DragGestureRecognizer._checkEnd
package:flutter/…/gestures/monodrag.dart:416
flutter: #3 DragGestureRecognizer.didStopTrackingLastPointer
package:flutter/…/gestures/monodrag.dart:358
flutter: #4 OneSequenceGestureRecognizer.stopTrackingPointer
package:flutter/…/gestures/recognizer.dart:343
flutter: #5 DragGestureRecognizer._giveUpPointer
package:flutter/…/gestures/monodrag.dart:367
flutter: #6 DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart:256
flutter: #7 PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:78

igunes@igunes ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TR)
• Flutter version 1.20.3 at /users/igunes/flutter
• Framework revision 216dee6 (13 days ago), 2020-09-01 12:24:47 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
• Android SDK at /Users/igunes/Library/Android/sdk
• Platform android-30, build-tools 30.0.0
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.7, Build version 11E801a
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.14.1

[✓] Connected device (1 available)
• Mustafa’s iPad (mobile) • ec9cc0171e4772f3dbca05f0c732828429310826 • ios •
iOS 13.5.1

**Comment by dkuye** [comment]
> i have same issue. Are there any bug fix or workaround solution ? When i use tabbar like dummy user with two or three finger (gesture) it freeze all tab bar views.

This is exactly what I'm experiencing.

**Comment by darshankawar** [comment]
@dkuye 
We would still need a complete minimal code sample that shows the issue you are facing.
Thanks.

**Comment by ztigunes** [comment]
If we add a webview as a tabview only and swipe left and right in tabs, both the webview freezes and the swipe between tabpages is broken. (use two finger for swipe and try multi touch) All tabviews freeze. This situation is still happening on ios 13.6 and above. if you give a webview as TabBarView with initial url 'https://www.google.com/maps' at 'https://flutter.dev/docs/cookbook/design/tabs' this sample, you can see all freeze. Also when tabview has gridview as a children also freeze. Critical point is use two or more finger for swipe like dummy user.

**Comment by softronaut** [comment]
I encountered same issue. The `BackButton` on `Scaffold` was throwing this error spontaneously.

**Comment by Abhishek01039** [comment]
duplication of https://github.com/flutter/flutter/issues/36350
Thanks.

**Comment by hosain-mohamed** [comment]
I have the same issue on IPad simluator
