### ISSUE TITLE
Allow Slider track to be specified by theme

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#6646]
Right now sliders only follow the Material Design Guidelines for a light theme. This makes the track oddly bright when in a dark theme. In my application I've resorted to copying the Slider class into my own codebase just to edit some constants.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by lucaslcode** [comment]
I came across this too.

![capture](https://user-images.githubusercontent.com/32044095/39966388-d938d74c-56a2-11e8-990b-abfd384d49ef.PNG)

**Comment by gspencergoog** [comment]
This is fixed since the rewrite of sliders for the latest Material Design specs.
