### ISSUE TITLE
use multi Font Family for multi language at same time just like css

### ISSUE THREAD

**Issue by AbdallahR99** [flutter/flutter#66469]
## Use case
 Use multi Font Family for multi language at same time just like CSS.

## Proposal
I have problem when I use some font family of different language, When I write in English English font become bad so I need some thing like CSS make me use font family for English and another font family for different language works together at same time

**Comment by TahaTesser** [comment]
Hi @AbdallahR99 
Can you please explain the proposal in more detail and give us some examples and use cases?

For the issue, you facing with font
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample including google link for fonts 
Thank you

**Comment by AbdallahR99** [comment]
> Hi @AbdallahR99
> Can you please explain the proposal in more detail and give us some examples and use cases?
> 
> For the issue, you facing with font
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample including google link for fonts
> Thank you

@TahaTesser 

flutter doctor -v

> [√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.450], locale
>     ar-EG)
>     • Flutter version 1.20.4 at C:\flutter
>     • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
> 
>  
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
>     • Android SDK at C:\Users\xGameR99\AppData\Local\Android\Sdk
>     • Platform android-30, build-tools 30.0.0
>     • ANDROID_HOME = C:\Users\xGameR99\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
>       --android-licenses
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 49.0.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.49.1)
>     • VS Code at C:\Users\xGameR99\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.14.1
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 2 categorie
 

flutter run --verbose

> [  +92 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1
> --pretty=format:%H
> [  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] fba99f6cf9a14512e461e3122c8ddfaa25394e89
> [        ] executing: [C:\flutter/] git tag --contains HEAD
> [ +169 ms] Exit code 0 from: git tag --contains HEAD
> [  +15 ms] 1.20.4
> [  +10 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/stable
> [        ] executing: [C:\flutter/] git ls-remote --get-url origin
> [  +22 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +5 ms] https://github.com/flutter/flutter.git
> [  +54 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
> [  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] stable
> [  +34 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
> update.
> [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping   
> update.
> [   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[  +10 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
> update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
> update.
> [  +17 ms] executing: C:\Users\xGameR99\AppData\Local\Android\Sdk\platform-tools\adb.exe
> devices -l
> [  +27 ms] List of devices attached
> [   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
> [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.   
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping     
> update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping   
> update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
> [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.  
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
> update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
> update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [   +8 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.     
> [  +38 ms] No supported devices connected.
> [   +8 ms] "flutter run" took ١٣٨ms.
> [  +17 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
>            #1      RunCommand.validateCommand
> (package:flutter_tools/src/commands/run.dart:343:7)
>            <asynchronous suspension>
>            #2      FlutterCommand.verifyThenRunCommand
>            (package:flutter_tools/src/runner/flutter_command.dart:836:11)
>            <asynchronous suspension>
>            #3      FlutterCommand.run.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command.dart:741:33)
>            <asynchronous suspension>
>            #4      FlutterCommand.run.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command.dart)
>            #5      AppContext.run.<anonymous closure>
>            (package:flutter_tools/src/base/context.dart:150:29)
>            #6      _rootRun (dart:async/zone.dart:1190:13)
>            #7      _CustomZone.run (dart:async/zone.dart:1093:19)
>            #8      _runZoned (dart:async/zone.dart:1630:10)
>            #9      runZoned (dart:async/zone.dart:1550:10)
>            #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)      
>            #11     FlutterCommand.run
> (package:flutter_tools/src/runner/flutter_command.dart:730:20)
>            #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)       
>            #13     FlutterCommandRunner.runCommand.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
>            #14     _rootRunUnary (dart:async/zone.dart:1198:47)
>            #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #17     Future._propagateToListeners.handleValueCallback
>            (dart:async/future_impl.dart:696:45)
>            #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)        
>            #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)  
>            #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)        
>            #22     FlutterVersion.checkFlutterVersionFreshness
> (package:flutter_tools/src/version.dart)
>            #23     _rootRunUnary (dart:async/zone.dart:1198:47)
>            #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #26     Future._propagateToListeners.handleValueCallback
>            (dart:async/future_impl.dart:696:45)
>            #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)        
>            #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #29     Future._asyncCompleteWithValue.<anonymous closure>
>            (dart:async/future_impl.dart:567:7)
>            #30     _rootRun (dart:async/zone.dart:1190:13)
>            #31     _CustomZone.run (dart:async/zone.dart:1093:19)
>            #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
>            #33     _CustomZone.bindCallbackGuarded.<anonymous closure>
> (dart:async/zone.dart:1037:23)
>            #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
>            #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
>            #36     _runPendingImmediateCallback
> (dart:isolate-patch/isolate_patch.dart:118:13)
>            #37     _RawReceivePortImpl._handleMessage
> (dart:isolate-patch/isolate_patch.dart:169:5)
> 
> 
> [ +284 ms] ensureAnalyticsSent: 253ms
> [   +1 ms] Running shutdown hooks
> [   +7 ms] Shutdown hooks complete
> [        ] exiting with code 1

**Comment by TahaTesser** [comment]
Hi @AbdallahR99 
Can you please explain the proposal in more detail and give us some examples and use cases?

For the issue, can you please provide a complete reproducible minimal code sample including google link for fonts
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
