### ISSUE TITLE
flutter create -h: --platforms documentation doesn't specify the format of the argument

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#66472]
```
 --platforms                The platforms supported by this project. This argument only works when the --template is set to app or plugin. Platform folders (e.g. android/) will
                               be generated in the target project. When adding platforms to a plugin project, the pubspec.yaml will be updated with the requested platform. Adding
                               desktop platforms requires the corresponding desktop config setting to be enabled.
                               [ios (default), android (default), windows (default), linux (default), macos (default), web (default)]
```

It sounds like this flag should be accepting a parameter?  It doesn't match the documentation for other parameters that use the following format: `--sample=<id>`  Is this suppose to accept a comma separated list?  `--platforms "ios,andoid"`?  Does it work with the equals sign like other arguments `--platforms="ios,android"`?

**Comment by TahaTesser** [comment]
```
    --platforms                The platforms supported by this project. This
                               argument only works when the --template is set to
                               app or plugin. Platform folders (e.g. android/)
                               will be generated in the target project. When
                               adding platforms to a plugin project, the
                               pubspec.yaml will be updated with the requested
                               platform. Adding desktop platforms requires the
                               corresponding desktop config setting to be
                               enabled.
                               [ios (default), android (default), windows
                               (default), linu
```
<details> 
<summary>flutter doctor -v</summary> 

```bash
✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (6 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.0
    • iPhone 11 (mobile)     • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

**Comment by jmagman** [comment]
> [ios (default), android (default), windows
                               (default), linux (default), macos (default), web
                               (default)]
I think this is just how the [arg parser](https://github.com/dart-lang/args) outputs `defaultsTo` and `allowed` for multioptions.
https://github.com/flutter/flutter/blob/2d9e500523a71f2da57f7eea9654ffa99f001a0d/packages/flutter_tools/lib/src/commands/create.dart#L514-L521

Not sure what would be better here, might be worth filing an issue with [arg parser](https://github.com/dart-lang/args/issues)
\cc @cyanglaz

**Comment by cyanglaz** [comment]
Maybe something like:
```
available options: [a, b, c, d]
default: [a,c]
```

**Comment by gaaclarke** [comment]
When I was working with it I just had to guess that comma separated lists works.  I think even just mentioning a comma separated list would be an improvement.

**Comment by jmagman** [comment]
I think it will format closer to @gaaclarke is expecting if `allowed` is left off, which may be okay since `defaultsTo` and `allowed` are the same thing in this case.
```
(defaults to "ios", "android", "windows", "linux", "macos", "web")
```

But it's still not clear it takes a separated list.  I think this arg code code would be better as
https://github.com/dart-lang/args/blob/29ef927bdde85e8c5a972eee338311f1231cf71b/lib/src/usage.dart#L106-L108
```dart
'(defaults to "' +
                  option.defaultsTo.map((value) => '$value').join(',') +
                  "')');
```

**Comment by jmagman** [comment]
@gaaclarke Want to file this issue against `args`? I don't have permission to transfer it over there.

**Comment by gaaclarke** [comment]
> Want to file this issue against args?

Done.  I also think we may be using isMultiple incorrectly.  `isMultiple` is meant to be used with flags that can show up multiple times, but since our flag is plural it kind of suggests using it once with multiple arguments.

My understanding is that `flutter create --template plugin --platforms ios --platforms android` would possibly work too.

The `isMultiple` flag is just weird.  I would just ban its usage, print out what the format of the argument should be and implement a simple parser that splits on commas.

**Comment by mdrijwan** [comment]
when i tried the following in the terminal
`flutter create --platforms=macos`

i got the following error:
```
"macos." is not an allowed value for option "platforms".
```

**Comment by rogiervandenberg** [comment]
> when i tried the following in the terminal
> `flutter create --platforms=macos`
> 
> i got the following error:
> 
> ```
> "macos." is not an allowed value for option "platforms".
> ```

`flutter create --platforms macos project_name` seems to work

**Comment by Hixie** [comment]
I'm going to close this since we have an upstream issue and it's not actionable on our side at this point. If anyone feels strongly about the current text, please submit a PR to improve it. :-)

**Comment by nerdybunz** [comment]
Excuse me, I'm trying to create a plugin using flutter create, and I am confused by the help file.  Would anyone care to describe the actual verbatim command you would would type in order to create a plugin template for android and ios?  I tried "flutter create -t plugin --platforms [android, ios] my_plugin" and "flutter create -t plugin --platforms ["android", "ios"] my_plugin" (and many many more) and none of my guesses work.

**Comment by jmagman** [comment]
@nerdybunz plenty of examples in the docs: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-1-create-the-package-1
