### ISSUE TITLE
Stale Gold comment in GitHub PR is confusing

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66478]
https://github.com/flutter/flutter/pull/60408#issuecomment-697831532
> This pull request has not been updated in a while. Please update this pull request to receive results from Gold, or close it.

Introduced in https://github.com/flutter/cocoon/pull/945.

I think this comment is confusing.  Most contributors probably don't know what a "Gold" is or how to fix it.  Golds tests aren't really relevant for packages other than the framework package, and definitely wasn't relevant for tool bugs like https://github.com/flutter/flutter/pull/60408.

**Comment by jmagman** [comment]
\cc @Piinks

**Comment by Piinks** [comment]
Whoops, looks like I cast wider net than intended. Thanks for filing!
