### ISSUE TITLE
x86_64 builds in missing for release configuration in xcframeworks

### ISSUE THREAD

**Issue by pingwinator** [flutter/flutter#66474]
Hi.
We have tried to add 1 flutter screen into the existing iOS and Android app. We successfully did it, but we met some problems. The biggest problem for the iOS team is that every developer should have flutter sdk. We used [option A](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk). We have tried other options and they works for us, but problem how to store frameworks.
Our goal is prepare release binaries and integrate them via adependency manager into iOS project. For us is ok that other developers can't debug flutter part.
## Use case

XCode supports binary xcframeworks. It would be nice to have a collection of xcframeworks with all supported architectures. 

## Proposal

Add support for x86_64 in release build for flutter module project.

We have tried build debug configuration and distribute them via [SPM](https://github.com/pingwinator/DemoModuleSPM/blob/master/Package.swift) 
[Demo dummy app](https://github.com/pingwinator/DemoModuleIOS)
We would like to have an option to build a release configuration.

**Comment by jmagman** [comment]
This was done on purpose with https://github.com/flutter/flutter/pull/48002 to fix codesigning issue https://github.com/flutter/flutter/issues/47930.  However, `x86_64` could be left in the `xcframework` Release version (but not universal fat framework) since the structure of the bundle differentiates between simulator and real devices.
I thought we had a duplicate for this but I can't find it.

**Comment by jmagman** [comment]
The `x86_64` Release Flutter.xcframework part will be done with https://github.com/flutter/flutter/pull/71495.  Still need to support Release `x86_64` for the plugins, App.framework, plugin registrant frameworks.

**Comment by jmagman** [comment]
@gogisha I don't know if you still work on a Flutter app, but you requested this back in May. 😃 
Now available on the master channel.
