### ISSUE TITLE
Run IOS: Your Xcode version may be too old for your iOS version for latest Xcode Version

### ISSUE THREAD

**Issue by rmargolinross** [flutter/flutter#66479]
## Steps to Reproduce
 
I have updated my phone to iOS 14 and Xcode to the latest version (12)
When trying to debug on my phone from android studio I get the error:

Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not run build/ios/iphoneos/Runner.ap on #####
Try launching Xcode and Selecting "Product > Run" to fix the problem:

I am able to run the app using xcode but this does not allow me to easily debug it and it does not fix anything.

Flutter Doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by erickzanardo** [comment]
Hey @rmargolinross, by the looks of your flutter doctor, you need to upgrade your flutter version.

As stated on the iOS 14 migration note:

> Due to low-level changes in iOS’s debugger mechanisms, developers using versions of Flutter earlier than 1.20.4 stable won’t be able to launch apps (by using flutter run or a Flutter-enabled IDE) on physical iOS devices running iOS 14. This affects debug, profile, and release builds. Simulator builds, add-to-app modules, and running directly from Xcode are unaffected.

> Upgrading to Flutter 1.22 beta allows you to build, test, and deploy to iOS without issue. Upgrading to 1.20.4 stable allows you to build and deploy to iOS 14, but not debug.

Check the full migration note here: https://flutter.dev/docs/development/ios-14

**Comment by rmargolinross** [comment]
Okay, I guess I will have to wait until a new stable is released then...
