### ISSUE TITLE
 The Share plugin does not work on iPad iOS 13.3 and above

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66485]
This was reported to me by email from someone using pub.dev, so I don't have a reproducible case. I'll @ him in when I get his GitHub account and maybe he can follow up with one:

Lee notes that:
```
It works fine on iPhone all versions, and iPad up to 13.3, but not later.  
Share.share simply does nothing on the broken versions, it doesn't 
appear, and no errors reported in debug console.
```
/cc @cyanglaz @amirh for triage.

**Comment by TahaTesser** [comment]
No issues on XR using `share: ^0.6.5+2` 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale
    en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (5 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by nezoat** [comment]
If by XR you mean iPhone XR, it will work as expected.  This is an iPad only issue.

**Comment by kf6gpe** [comment]
Escalating priority given product-side discussions.

**Comment by cyanglaz** [comment]
I tried on iPad pro simulator iOS 14 and I can repro. @nezoat Did it fail on simulator for you as well?

**Comment by nezoat** [comment]
Yes, it failed on simulators and actual hardware for me.

**Comment by cyanglaz** [comment]
@nezoat Do you mind providing a reduced test case for me to reproduce this issue? I can't reproduce it on iPad pro simulator iOS 14.

**Comment by nezoat** [comment]
Here is example project code.  I created a fresh flutter 'Flutter Demo' project in IntelliJ, and added the Share.share() to the '_incrementCounter()'. Here is main.dart:

`import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      Share.share('counter: $_counter');
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
`

**Comment by nezoat** [comment]
I noticed while in tablet portrait that in upper left of the blue 'Flutter Demo Home Page' header, it darkens just a little when the Share.share() is executed.  I think the share sheet is appearing behind the Flutter Widget.

**Comment by nezoat** [comment]
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.22.0-12.1.pre at /Users/lee/Development/Flutter/flutter
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lee/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] Connected device (9 available)
    • Android SDK built for x86 (mobile)    • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 64 (mobile) • emulator-5556                            • android-x64    • Android 8.0.0 (API 26) (emulator)
    • Gage’s iPad (mobile)                  • 928b1b3da70f852ea557c622a83a456da0158994 • ios            • iOS 13.6
    • Lee’s iPhone (mobile)                 • 00008020-000339880EF8003A                • ios            • iOS 13.7
    • iPhone 11 (mobile)                    • C1474E33-578B-4CCE-918E-5CE2D77BEDE7     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPad Pro (9.7-inch) (mobile)          • 45B8F6A9-8D25-48AE-A22D-8803D9DA8B0B     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • iPhone 11 (mobile)                    • 953B3198-EAE9-42E2-8EF2-B3B4ED597964     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • Web Server (web)                      • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome                                   • web-javascript • Google Chrome 85.0.4183.121

**Comment by TahaTesser** [comment]
I have tired on tried on iPad simulator as well as using official [example](https://pub.dev/packages/share/example)

**Comment by nezoat** [comment]
The issue seems to be that iOS 13.3 and above require a source Rect provided to the UIActivityViewController.   In the FLTSharePlugin.m, starting at line 109, you can change it to this and it will work again:

  if (!CGRectIsEmpty(origin)) {
    activityViewController.popoverPresentationController.sourceRect = origin;
  } else {
    activityViewController.popoverPresentationController.sourceRect = CGRectMake(controller.view.frame.size.width/2, controller.view.frame.size.height/4, 0, 0);
  }

**Comment by cyanglaz** [comment]
Lowering the priority to p3 as it can be workaround by applying the origin.

**Comment by cyanglaz** [comment]
This is fixed with https://github.com/flutter/plugins/pull/3188

**Comment by TahaTesser** [comment]
Can confirm, this is fixed, tested on my new iPad on the latest `share: ^0.6.5+4` 
### Preview 
![IMG_0053](https://user-images.githubusercontent.com/48603081/97433052-e5456b80-1942-11eb-8668-0ed62df9193a.jpg)


### Code Sample
[Official Sample](https://pub.dev/packages/share/example)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (13 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.1

! Doctor found issues in 1 category.
```

</details> 

Also closed https://github.com/flutter/flutter/issues/47220
