### ISSUE TITLE
Performance tweak of ScrollBar, there is one only one AnimationController, use SingleTickerProviderStateMixin  instread of TickerProviderStateMixin

### ISSUE THREAD

**Issue by chinmoy12c** [flutter/flutter#66492]
The `_ScrollbarState` implements the `TickerProviderStateMixin`, however it uses only 1 AnimationController , that is, `_fadeoutAnimationController`. In cases where there is only one AnimationController, a `SingleTickerProviderStateMixin` is more efficient. 

I would like to submit a PR for making this change, if it's an acceptable change.

**Comment by TahaTesser** [comment]
Hi @chinmoy12c 
Thank you for looking out for this issue,
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

Feel create PR as well and mention this issue 
Thank you

**Comment by chinmoy12c** [comment]
Here is the flutter doctor output
<details>
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Linux, locale en_US.utf8)
    • Flutter version 1.22.0-10.0.pre.340 at /home/Chinmoy/MasterFiles/openSource/flutter
    • Framework revision 1fef5912cf (4 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/Chinmoy/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_242-release"
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /home/Chinmoy/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version openjdk version "1.8.0_152-release"

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version openjdk version "1.8.0_242-release"

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • SM M215F (mobile) • RZ8N501AW9E • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
</details>


Here is the minimal code for ScrollBar:
```

import 'package:flutter/material.dart';

void main() {
  runApp(SampleWidget());
}

class SampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Scrollbar(
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text('Item $index'),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(SampleWidget());
}

class SampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Scrollbar(
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text('Item $index'),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.355, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.355 at C:\Code\flutter_master
    • Framework revision da1a42b577 (55 minutes ago), 2020-09-25 00:57:03 -0400
    • Engine revision 435db234e4
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by chinmoy12c** [comment]
Would any additional tests be necessary or just changing it to SingleTickerProviderStateMixin be enough?

**Comment by HansMuller** [comment]
If the fix is just using SingleTickerProviderStateMixin instead, then yes the existing tests should be proof enough. It's like fixing a typo :-).

**Comment by chinmoy12c** [comment]
PR waiting for review :)
