### ISSUE TITLE
gradle_plugin_light_apk test fails consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66495]
Link to logs:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20gradle_plugin_light_apk_test

```

Task result:
{
  "success": false,
  "reason": "Gradle did not exit with error as expected"
}


Finished task "gradle_plugin_light_apk_test"
```

**Comment by keyonghan** [comment]
Ha, already filed https://github.com/flutter/flutter/issues/66392 earlier (since this has been worked on, marking that one as duplicate then).

**Comment by godofredoc** [comment]
The failure was related to line separator in windows platform being \r\n instead of just \n as in linux and mac. This test updates the gradle configuration file to introduce an error condition and it was failing to find the text to replace. Eg. it was looking for something like \n to_replace \n and it didn't find it because in windows it was \r\n to_replace \r\n.

PR with the fix:
https://github.com/flutter/flutter/pull/66496

**Comment by keyonghan** [comment]
Tests are running successfully now.
