### ISSUE TITLE
Improve user-facing error text for debug app launch from iOS 14 homescreen

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#66491]
Current text:

>In iOS 14+, Flutter application in debug mode can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode.
>
>Alternatively, build in profile or release modes to enable re-launching from the home screen.";

Proposing a change to:
>In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode.
>
>Alternatively, build in profile or release modes to enable launching from the home screen.";

 - Google style guide is "apps" rather than "applications"
 - Pluralize apps
 - launching is appropriate here

Fixed in https://github.com/flutter/engine/pull/21362

**Comment by pcsosinski** [comment]
thanks!

**Comment by AvatarDevs** [comment]
what do we do if we're getting this screen from vscode? its running the app fine on my ipad pro ios 14
