### ISSUE TITLE
[pigeon] add support for direct generation to Swift.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#66499]
The title says it all.

I think Swift should be given some priority as the removal of objective C would benefit plugins due to obj-c using a non-protected memory model.
Swift is also closer to dart making code maintence by small teams easier.

**Comment by darshankawar** [comment]
Hi @bsutton,
Does [63284](https://github.com/flutter/flutter/issues/63284) sound similar to your request ?
Thanks.

**Comment by bsutton** [comment]
I don't think so. That seems to be taking about the pubspec creation rather
than the code generation which is what I'm reverting to.

**Comment by darshankawar** [comment]
Thanks @bsutton for confirming.

**Comment by izio38** [comment]
Is this proposal confirmed in some ways ? Like is this issue validated by the flutter team and is open to receive PR ?

**Comment by MrAlek** [comment]
+1 on this. Is there any technical motivation currently for Pigeon using Objective-C as opposed to Swift such as build times, C++ compat or swizzling ability? I'm curious but couldn't find anything in the docs.

Swizzling in Swift for instance, has taken leaps with https://github.com/steipete/InterposeKit

Cc @gaaclarke

**Comment by gaaclarke** [comment]
@MrAlek It was just an economics decision.  Swift has good interop with Objective-C so there wasn't a pressing need for it given a limited budget for features.  It's definitely in our sights for future investments.

**Comment by ailtonvivaz** [comment]
Swift generation is now available in 3.2.0 version as experimental feature

**Comment by stuartmorgan** [comment]
We can close this as completed; removing the experimental flag just requires waiting until it's had some time to bake, rather than specific work we need to track.
