### ISSUE TITLE
Hero gets reused even when it corresponds to a different "most valuable key".

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#665]
1. Tap a row in the stocks app.
2. Tap back.
3. Immediately (during the hero animation) tap a different row.

The arrow from step 2 is reused in the animation to step 3, instead of there being two different animations.

**Comment by Hixie** [comment]
@vlidholt suggests that we could maybe get rid of Most Valuable Keys entirely and just base everything on tags. Since the target page always knows what it's showing anyway, this isn't actually particularly difficult. (Maybe we can replace the tag concept with just using a LocalKey key.)

This would solve the problem of reusing the same hero. However, we also have to support having some heroes continue going back while some heroes go forward. The problem is where should they go when the page they're going to goes away? Should they continue going to where they were going, but fade out as they do so?

**Comment by HansMuller** [comment]
Most Valuable Keys have been removed, #5500.

**Comment by Hixie** [comment]
This was a dupe of https://github.com/flutter/flutter/issues/412
