### ISSUE TITLE
Request for a "Thinking in Flutter" doc

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6651]
We seem to have a documentation gap, between "Getting Started" and "Tour of the Widget Framework". In a recent UX study, we noticed that the high-level concepts and the unique bits of Flutter aren't clearly called out, which made it more challenging for a new user to wrap their heads around what Flutter is and how it thinks.

Initial thoughts on this doc:

* Audience is brand new users for Flutter
* Intended for the "ok, what's this flutter thing? what's different?"
* Intended to be the next doc you read, after getting started, and before you start diving in
* Fairly short, high level

Initial thoughts on table of contents:

* What is Flutter?
  * what problem(s) does it solve
  * who is it for
  * what's special?
* Functional-reactive framework
  * widget lifecycle
  * setState
  * Only rebuilding what needs to be rebuilt (efficient)
  * Customizable/extensible
* Material design
  * full set of widgets out of the box
* Dev cycle
  * Hot reload
  * Fast restart
* Tooling
  * CLI
  * IntelliJ
* Plugins/interop
  * coming soon!

Once a new user scans through this doc, they should know

* What's special about flutter?
* What does functional-reactive mean, for Flutter?
* setState is a thing, and why not to be scared of it
* How to dev cycle
* Where to find additional info on widgets, layout, plugins, etc

Thanks!

(this came up in a recent UX study)

**Comment by Hixie** [comment]
I think the right way to do this is to adapt "Tour of the Widget Framework" and make it "Tour of Flutter".
Having two documents means half the people will read one, the other half will read the other, and so everyone will be missing something. That's why we merged the two widget catalogs, for instance.

**Comment by sethladd** [comment]
> I think the right way to do this is to adapt "Tour of the Widget Framework" and make it "Tour of Flutter".

sgtm!

**Comment by Hixie** [comment]
One of the things to mention is that we use composition heavily.

**Comment by sethladd** [comment]
New homepage is up! W00t!
