### ISSUE TITLE
[iOS 14.0 ] In release mode after the app is started, click to jump to the flutter page, there is a layer of mask, and you cannot click

### ISSUE THREAD

**Issue by dzwing** [flutter/flutter#66528]
It's almost appear every time.

**Comment by TahaTesser** [comment]
Translated Title
From
iOS 14.0 release 模式 APP启动之后点击跳转到flutter页面，有一层蒙层，无法点击 
To
iOS 14.0 release mode After the APP is started, click to jump to the flutter page, there is a layer of mask, and you cannot click

**Comment by dzwing** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/dingzhiwei/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dingzhiwei/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

  flutter run --release --verbose 
 print too much useless code, you can have a try in yourself to recurrence this question.

**Comment by dzwing** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
• Flutter version 1.20.4 at /Users/zzz/flutter
• Framework revision fba99f6 (10 days ago), 2020-09-14 15:32:52 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/zzz/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.0, Build version 12A7209
• CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 44.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

flutter run --release --verbose
print too much useless code, you can have a try in yourself to recurrence this question.

**Comment by TahaTesser** [comment]
Hi @dzwing 
Execute `flutter run --release --verbose ` from the terminal, copy all the logs paste in a plain text file `.txt` and attach in the comments here 
Also please provide  a complete reproducible minimal code sample
Thank you

**Comment by dzwing** [comment]
Have solve this question. Local flutter main.h file home: xxxx can't be annotated in high flutter for iOS.
