### ISSUE TITLE
AlertDialog actions widget alignment for the ButtonBar

### ISSUE THREAD

**Issue by erguerra** [flutter/flutter#66525]
## Use case

When using AlertDialog, there's no option of alignment to the actions passed. Usually the community sugests to move your actions to the content parameter, but in this case your action will be scrolled with the content when the user swipes up or down

## Proposal

It would be nice if it was possible to pass a custom ButtonBar into the AlertDialog class in order to replace the default action. But simply giving the possibility to align the actions through a ALIGNMENT parameter would be enough.

**Comment by HansMuller** [comment]
This feature was (finally!) added in https://github.com/flutter/flutter/pull/85260
