### ISSUE TITLE
.m3u8 format videos are not playable

### ISSUE THREAD

**Issue by asadaly** [flutter/flutter#66529]
I  searched on internet and played every link having .m3u8 format, it works fine.
I have some vidoes in that format and its not working.
https://videos-3.earthcam.com/fecnetwork/15658.flv/playlist.m3u8
https://videos-3.earthcam.com/fecnetwork/eiffelcamHD.flv/playlist.m3u8
these links are not working.
I worked on android native and by using following code I am able to play videos.
val dataSourceFactory: DataSource.Factory =
DefaultDataSourceFactory(
this@OtherVideosPlayer,
Util.getUserAgent(
this@OtherVideosPlayer,
"Webcams"
), defaultBandwidthMeter
)
But in flutter how can i achieve this.

**Comment by darshankawar** [comment]
Hi @asadaly,
Flutter's first party video player plugin is `video_player` and here is the [list](https://exoplayer.dev/supported-formats.html) of support formats by the plugin which is backed by `ExoPlayer`.
You may try to search for 3rd party plugins that may be supporting that format. See [this](https://stackoverflow.com/a/62742768) link for reference and try that plugin to see if it works for you.

I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.
