### ISSUE TITLE
Most Debugging Options are discarded for desktop

### ISSUE THREAD

**Issue by ishitatsuyuki** [flutter/flutter#66532]
Most debugging flags are discarded when targeting desktop. A complete list of such flags can be found [here](https://github.com/flutter/flutter/blob/51ededb92fd7ad9fb3c5cb8733d9c47417a9df5c/packages/flutter_tools/lib/src/commands/run.dart#L392-L428).

This makes it super annoying to debug low-level issues like those with Skia. The fact that no warning is emitted also wasted much of my time figuring out why the flags don't work.

In addition to the CLI discarding the flags, the engine also refuses to accept such flags, at least on Linux. Flutter engine already has a parser for command line option, so this shouldn't be too hard to fix.

Related: #52676

## Proposed fix

1. Make the Linux accept options related to Flutter, not only options for GTK. Same applies for other desktop platforms.
2. Add logic for passing the debugging options to [`DesktopDevice.startApp`](https://github.com/flutter/flutter/blob/1fef5912cf778f9b25767f14fd66875400e3e8b5/packages/flutter_tools/lib/src/desktop_device.dart#L107)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Configure application to run on Linux.
3. `flutter run --trace-skia -d linux`

**Expected results:** Skia Trace events should be emitted.

**Actual results:** No such events are actually emitted.

**Comment by TahaTesser** [comment]
Hi @ishitatsuyuki 
Is this specific to Linux desktop only? Have tried Mac or Windows desktop?

When reproducing on the latest `master`, I see no events are emitted 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.340 at /home/taha/Code/flutter_master
    • Framework revision 1fef5912cf (4 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    •
      Android 10 (API 29) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      •
      Linux
    • Web Server (web)                      • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by ishitatsuyuki** [comment]
The #2 in proposed fix applies to all desktop platforms. As for #1, I haven't investigated Windows and Mac yet.

**Comment by stuartmorgan** [comment]
This depends on https://github.com/flutter/flutter/issues/60393. As that's implemented for each platform, the tool code to set the appropriate flags as environment variables can be added.

> the engine also refuses to accept such flags

The fact that they aren't accepted as command line flags on desktop is intentional.

**Comment by ishitatsuyuki** [comment]
I appreciate that this is in progress of being implemented. In the meantime, can a warning get added so that the user know that the desktop platforms ignores debugging opts?

**Comment by stuartmorgan** [comment]
@jonahwilliams I assume you can do all of these while fixing https://github.com/flutter/flutter/issues/46005?

**Comment by jonahwilliams** [comment]
Yes, assigned to myself
