### ISSUE TITLE
mock_text_input does not work if Input is wrapped in a Navigator

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#6653]
I am using [```mock_text_input.dart```](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widget/mock_text_input.dart)n to test a widget that includes text input interaction.

If that Widget sits inside a Navigator in the WidgetTester, the mock TextInput messages fail to passed through.

## Steps to Reproduce

Example Code: 
```dart
testWidgets('Setter callback is called', (WidgetTester tester) async {
    String fieldValue;

    MockTextInput mockTextInput = new MockTextInput()..register();

    Widget builder() {
      return new Navigator(
        initialRoute: '/',
        onGenerateRoute: (RouteSettings settings) {
          return new MaterialPageRoute<Null>(
            settings: settings,
            builder: (BuildContext context) {
              return new Material(
                child: new Input(
                  onChanged: (InputValue value) {
                    fieldValue = value.text;
                  },
                ),
              );
            },
          );
        }
      );
    }

    await tester.pumpWidget(builder());

    expect(fieldValue, isNull);

    Future<Null> checkText(String testValue) async {
      await tester.idle();
      await tester.tap(find.byType(Input));
      mockTextInput.enterText(testValue);
      mockTextInput.submit();
      await tester.idle();
      // pumping is unnecessary because callback happens regardless of frames
      expect(fieldValue, equals(testValue));
    }

    await checkText('Test');
  });
```

## Logs

Output:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: a value not equal to <0>
  Actual: <0>
   Which: is not a value not equal to <0>

```

The expect in https://github.com/flutter/flutter/blob/master/packages/flutter/test/widget/mock_text_input.dart#L36 fails and so I'm guess the client is not being registered.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/dayang/Flutter
    • Framework revision bed0300b2a (4 weeks ago), 2016-10-07 13:41:59
    • Engine revision f97caf271c
    • Tools Dart version 1.20.0-dev.10.1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] Connected devices
    • Pixel C • 6119001907 • android-arm

**Comment by eseidelGoogle** [comment]
customer: pink says this comes up rather frequently in their testing and would be nice to resolve sooner rather than later.

Given that this mock works fine outside a navigator, this may be a simple fix?

**Comment by abarth** [comment]
Does it work if you use `tester.enterText` rather than managing the `MockTextInput` manually?  I guess could try that myself.

**Comment by abarth** [comment]
Assigned for investigation.

**Comment by abarth** [comment]
`git grep MockTextInput` in flutter.git doesn't turn up anything.  Instead, using `tester.enterText` seems to work as expected (i.e., this test passes):

```dart
  testWidgets('Setter callback is called', (WidgetTester tester) async {
    String fieldValue;

    Widget builder() {
      return new Navigator(
        initialRoute: '/',
        onGenerateRoute: (RouteSettings settings) {
          return new MaterialPageRoute<Null>(
            settings: settings,
            builder: (BuildContext context) {
              return new Material(
                child: new Input(
                  onChanged: (InputValue value) {
                    fieldValue = value.text;
                  },
                ),
              );
            },
          );
        }
      );
    }

    await tester.pumpWidget(builder());

    expect(fieldValue, isNull);

    Future<Null> checkText(String testValue) async {
      await tester.enterText(find.byType(EditableText), testValue);
      await tester.idle();
      // pumping is unnecessary because callback happens regardless of frames
      expect(fieldValue, equals(testValue));
    }

    await checkText('Test');
  });
```
