### ISSUE TITLE
SystemUiOverlayStyle has different behavior between status bar and navigation bar on Android

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#66540]
I use `AnnotatedRegion<SystemUiOverlayStyle>` to automatically change the brightness of status bar and navigation bar.

For example, when exiting from a dark photo page, system ui should be bright.
While status bar is gradually changing its color, navigation bar changes suddenly without any gradual animation, which maybe a bad user experience.

**Comment by TahaTesser** [comment]
Hi @hamberluo 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by hamberluo** [comment]
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-CN)
    • Flutter version 1.20.4 at /Users/hamberluo/Documents/Dev/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hamberluo/Documents/Dev/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/hamberluo/Documents/Dev/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • IN2020 (mobile) • caa4716a • android-arm64 • Android 10 (API 29)
```

Could you please tell me if `AnnotatedRegion<SystemUiOverlayStyle>` is the best practice for auto changing system ui?

**Comment by TahaTesser** [comment]
Hi @hamberluo 
Sure, you can use it, for example, https://github.com/flutter/flutter/issues/65626#issuecomment-697211030
If you've bug.  Can you please provide  your` flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by hamberluo** [comment]
Hi @TahaTesser 
I guess the cause maybe the activity theme.
Flutter uses a single activity without fullscreen theme.
Native uses two activities from normal page to picture page which is fullscreen.

**Comment by TahaTesser** [comment]
Hi @hamberluo 
That's true, `@android:style/Theme.Light.NoTitleBar`

Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
