### ISSUE TITLE
Push transition from native iOS to flutter module 

### ISSUE THREAD

**Issue by dsngeu** [flutter/flutter#66547]
there is transition lag when I push flutterView controller from native iOS and for 1-1.5 seconds black screen appears. 
it is very much visible lag for the first time after that it's not that much visible lag.
Tested on  **Release mode** 

private func showTreatments() {
        
        let flutterEngine = (UIApplication.shared.delegate as! AppDelegate).flutterEngine
        let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
      
        let channel = FlutterMethodChannel.init(name: kFlutterChannel, binaryMessenger: flutterEngine.binaryMessenger)
        let headers = NetworkManager.shared.getCommonHeaders()
        let args: [String : Any] = [kPage : "TreatmentListScreen", kNetwork_Headers : headers];
        channel.invokeMethod(kMethodName_Load_New_Screen, arguments: args)
         self.navigationController?.pushViewController(flutterViewController, animated: true)

        }

Version detail:
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (10 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by TahaTesser** [comment]
Hi @dsngeu 
Can you please provide and a complete reproducible minimal code sample in a repository including **sample**  the flutter module and ios app 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
