### ISSUE TITLE
Scrollable panel does not scroll when it contains scrollable widget(Eg., Page view holds the list view)

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#66555]
## Steps to Reproduce

I was created the custom scroll panel like page view and it scroll with custom animation and interaction. The custom scroll panel does not move to next page(or widget) when the custom scroll panel holds list view like the example specified in below(Page view holds the list view). Is there any possibility to pass the touch to custom scroll panel when inner scroll view(or list view) reaches end?.

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: PageView.builder(
            scrollDirection: Axis.horizontal,
            itemCount: 5,
            itemBuilder: (BuildContext context, int position) {
              return Container(
                  child: ListView(
                scrollDirection: Axis.horizontal,
                children: [
                  Row(
                    children: [
                      Container(
                        margin: EdgeInsets.all(5),
                        color: Colors.red,
                        height: 500,
                        width: 2000,
                      ),
                    ],
                  )
                ],
              ));
            }),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
```

Sample: 
[scrollview_issue.zip](https://github.com/flutter/flutter/files/5276472/scrollview_issue.zip)

**Expected results:** 
List view does pass the touch to page view when it reaches end 

**Actual results:** 
List view does not pass the touch to page view when it reaches end

**Comment by TahaTesser** [comment]
Hi @Sasikumar3595 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by Sasikumar3595** [comment]
Hi @TahaTesser,

[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-9.2.pre at /Users/SasikumarArumugam/Documents/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/SasikumarArumugam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Moto G 5 Plus (mobile) • ZY2243M2LZ • android-arm    • Android 8.1.0 (API 27)
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 2 categories.

**Note: Also the issue replicated in stable channel**

Is there any possibility to pass the touch to custom scroll panel when inner scroll view(or list view) reaches end?.

**Comment by TahaTesser** [comment]
Hi @Sasikumar3595 
You have listview inside pageview
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/50946
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Sasikumar3595** [comment]
Hi @TahaTesser ,

My requirement is how to pass the touch from scroll view(like listview) to scrollable panel(like pageview), I have custom scroll panel like page view and it does not move to next page(or widget) when it holds scroll view(like listview) like Page view holds the list view.

And i was not using page view and list view and i was explained my scenario with page view with list view.

 Is there any possibility to pass the touch to custom horizontal scroll panel when it holds horizontal scroll view(or list view) reaches end?.

Thanks in advance.

**Comment by TahaTesser** [comment]
Hi @Sasikumar3595 
Current it's not possible, the issue has some comments, you can go through them

**Comment by Sasikumar3595** [comment]
Hi @TahaTesser ,

Thank you for your response.
