### ISSUE TITLE
Flutter Beta: If I click on TextField and press back button keyboard not getting close on MIUI and Asus phones.

### ISSUE THREAD

**Issue by ganeshshirole** [flutter/flutter#66556]
If I click on TextField and press back button keyboard not getting close on MIUI and Asus phones.
Steps:
1. Create new project.
2. Add TextField.
3. Run app on beta channel.
4. Click on TextField.
5. Press back button.
6 Keyboard not getting closed.

**Comment by TahaTesser** [comment]
Hi @ganeshshirole 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` running those devices with the code and a complete reproducible minimal code sample
Thank you

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/66036

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
