### ISSUE TITLE
Unify naming convention for perf test and sub_result names, and provide a migration spreadsheet

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#66574]
The "test" and "sub_result" names are used to set up alerts in https://flutter-flutter-perf.skia.org/a/

Having a unified naming convention (e.g., all app size metrics must have "size" in its "sub_result" name) would make it much easier to create those alerts. I propose to name "sub_result" in a format of `<area>_<name>_<unit>` where
- `<area>` could be "size", "speed", "memory", "energy", "wealth" (for tech debt), etc.
- `<name>` would be the old sub_result name such as "average_frame_build_time".
- `<unit>` would be "ms", "bytes", "KB", "MB", "percent" and so on. Having unit inside "sub_result" which is checked into our codebase is more reliable than a separate "unit" key value that has to be manually edited in Cocoon. Right now, I think a lot of units in Cocoon is either missing or wrong.

The "test" name comes from the devicelab task name so this would be also related to https://github.com/flutter/flutter/issues/59202. See #59202 for a proposal on how to unify "test" name convention.

As we're migrating from https://flutter-dashboard.appspot.com/benchmarks.html to https://flutter-flutter-perf.skia.org, changing name is no longer a big problem in terms of being unable to compare historical metrics. We only need to **create a spreadsheet of name migration history**, and then plot both traces that match the old name and the new name in the same graph on https://flutter-flutter-perf.skia.org to do that.

**Comment by flar** [comment]
Another issue to consider is that the microbenchmarks are split up differently than the macro perf tasks. It is a single devicelab task that runs many unrelated benchmarks so the task name is not interesting and each of its measurements is a separate "benchmark" to track.

**Comment by kf6gpe** [comment]
Although not a bug in the engine itself, assigning the engine team, since that's the team predominantly working with the benchmark measurements at this point.

**Comment by jonahwilliams** [comment]
We're not going to rename the metrics
