### ISSUE TITLE
Flutter Web: Google Sign In using google_sign_in_web fails with 'Coundn't sign you in. This browser or app may not be secure' 

### ISSUE THREAD

**Issue by shaiwals** [flutter/flutter#66577]
I have a flutter app that is using google_sign_in and google_sign_in_web.  Google Sign In runs fine on iOS and Android. I recently started working on ensure that it works well on Flutter for Web too.  After following the instructions https://pub.dev/packages/google_sign_in_web to ensure everything is setup file for the web app, I encounter the following issue when I launch the web app on Chrome on my local machine.  The error that I see is:

```
Sign in with Google
Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

```

I am not able to figure out what is going wrong by just looking at this message.  I have tried both Chrome and Edge and also refreshing the screen and trying to sign in multiple times but no luck.  The workflow always blocks at the above failure.

I have attached screen shots and verbose outputs for flutter doctor and flutter run.  Any help resolving the issue would be appreciated.

Thx
Shaiwal

[FlutterDoctor.txt](https://github.com/flutter/flutter/files/5278707/FlutterDoctor.txt)
[FlutterRun.txt](https://github.com/flutter/flutter/files/5278708/FlutterRun.txt)
![GoogleSignIn](https://user-images.githubusercontent.com/24903987/94191100-e544de00-fe61-11ea-95c0-2413c625aff3.jpg)
<img width="456" alt="GoogleSignInFailure" src="https://user-images.githubusercontent.com/24903987/94191106-e5dd7480-fe61-11ea-8fb7-1fd161b0bfac.png">
<img width="605" alt="LoginScreen" src="https://user-images.githubusercontent.com/24903987/94191108-e6760b00-fe61-11ea-9d1d-6060eea15e34.png">

**Comment by darshankawar** [comment]
@shaiwals,
There's similar open issue describing your case, [61155](https://github.com/flutter/flutter/issues/61155).
Please follow-up there for updates.
Closing this as duplicate.
