### ISSUE TITLE
Add autofill detection on TextFields / iOS onStartEditing-Passthrough

### ISSUE THREAD

**Issue by GefaketHD** [flutter/flutter#66578]
## Use case
Detect when email and/or password or name etc. are filled in and focus next field automatically or unfocus all fields because form is completely filled.
(Skip manually pressing submit-button on keyboard to get to next field -> gives a better flow experience on filling stuff out)

## Proposal
Flutter could at least on iOS detect the onStartEditing-Call (which will be triggered very fast twice if autofill was used on a field) and pass them through so the developers can add autofill detection like in native Swift or flutter could detect itself if this is called very fast after another and trigger a onAutofill-Call.

Not sure if it works this way on Android, but I think android-users are not that used to autofill like iOS-users are anyway, if I'm not mistaken...? Correct me if I'm wrong and append your idea, if there is a way to do it on android too.

!Talking about autofill, not autocompletion!

**Comment by TahaTesser** [comment]
Sounds like two different proposals, autofill detection could be a package, it doesn't have to be baked into  Flutter, it would be too specific. 


CC @chunhtai  @justinmc 
Does this proposal sound feasible

**Comment by LongCatIsLooong** [comment]
It would be ideal if we can distinguish autofill from other forms of text input on all platforms, then we would be able to make autofill a self-contained widget. That said, I'm not aware of reliable ways to do that on iOS or web.  About the `onStartEditing` call you were referring to, could you post a link to its documentation?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
