### ISSUE TITLE
[BUG] Found a bug in Flutter Channel dev, 1.23.0-4.0.pre

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#66571]
I have found a bug in the `Expanded` widget that breaks the widget.
The bug is a missing `@` before the `required` keyword. It broke the Widget.
I have the fix and I will submit a PR today rn.

Pull Request: #66572

**Comment by pedromassango** [comment]
It is not a BUG, the framework is being migrated to NNBD!

**Comment by YazeedAlKhalaf** [comment]
Ok I am sorry but it broke my app so I thought it would help people 😞

**Comment by pedromassango** [comment]
What is the error you are receiving?

**Comment by Abhi011999** [comment]
I think there's some versioning error between dart dev sdk and flutter dev sdk. I am receiving these errors too.
For `Expanded` widget - Undefined name `child`
For `ListView.builder` widget - Undefined name `itemBuilder` and `itemCount`

**Comment by YazeedAlKhalaf** [comment]
@pedromassangocode  For me, it got fixed by mysteriously after closing and reopening VS Code although I have edited the file locally and then reverted it.

The file I edited is: `Y:\extra\flutter\packages\flutter\lib\src\widgets\basic.dart` line `4667` after reverting everything went back to normal

@Abhi011999 Try doing the same, close and reopen your ide or even restart the computer.

**Comment by Abhi011999** [comment]
Yeah, it was environment error. Fixed after restart. This issue can be closed now I think.

**Comment by YazeedAlKhalaf** [comment]
Yea I agree too. I will close the PR also.

**Comment by Tokenyet** [comment]
In some situation, I can't fix this by reopen or flutter clean/delete .package...etc.

The solution for me is to downgrade to lower beta version.

The versions not work in my vscode 1.50.1: 1.23.0-18.1.pre, 1.22.0-12.4.pre.
The version works: 1.21.0-7.0.pre

I used [fvm](https://github.com/leoafarias/fvm) to control my flutter version, just comment here for someone who need a `@required` flutter beta version that won't break IDE.
