### ISSUE TITLE
[infra] Mac ios engine builds failing on beta branch to install jazzy

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#66592]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868246371434524672/+/steps/install_jazzy/0/stdout

**Comment by christopherfujino** [comment]
I opened this CL https://flutter-review.googlesource.com/c/recipes/+/6761

**Comment by digiter** [comment]
Triage: we don't need jazzy. /cc @godofredoc

**Comment by christopherfujino** [comment]
Here's a run post CL merge: https://ci.chromium.org/p/flutter/builders/prod/Mac%20beta%20iOS%20Engine/54?

**Comment by godofredoc** [comment]
Closing as obsolete as the versions of the recipes used for beta have been updated a couple of times by now. Please reopen if this is still and issue.
