### ISSUE TITLE
Test that heroes update their destination when their destination moves

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#666]
When a hero is in a scrolling list, and you scroll the list while the hero is being animated towards the list, the hero doesn't adjust for the list's movement.

**Comment by Hixie** [comment]
I'm not sure how we could do this. We don't know where the final destination will be as we're doing the regular transition, except for where it would have been if no unexpected scrolling or animation happened.

**Comment by Hixie** [comment]
@HansMuller did you fix this?

**Comment by HansMuller** [comment]
I did, but I haven't written the tests for this case yet. Will close this bug once I've added the tests.
