### ISSUE TITLE
complex_layout_android__scroll_smoothness generates unexpected numbers

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#66608]
Unlike the numbers in https://github.com/flutter/flutter/pull/61998#issuecomment-682697104, the test is currently generating something like the following both in the device lab and in my local experiment.
```
Task result:
{
  "success": true,
  "data": {
    "janky_count_with_resampler_90Hz": 0.0,
    "average_abs_jerk_with_resampler_90Hz": 0.0,
    "dropped_frame_count_with_resampler_90Hz": 43,
    "janky_count_with_resampler_59Hz": 0.0,
    "average_abs_jerk_with_resampler_59Hz": 0.0,
    "dropped_frame_count_with_resampler_59Hz": 28,
    "janky_count_without_resampler_90Hz": 0.0,
    "average_abs_jerk_without_resampler_90Hz": 0.0,
    "dropped_frame_count_without_resampler_90Hz": 36,
    "janky_count_without_resampler_59Hz": 0.0,
    "average_abs_jerk_without_resampler_59Hz": 0.0,
    "dropped_frame_count_without_resampler_59Hz": 29
  },
  "benchmarkScoreKeys": [
    "janky_count_with_resampler_90Hz",
    "average_abs_jerk_with_resampler_90Hz",
    "dropped_frame_count_with_resampler_90Hz",
    "janky_count_with_resampler_59Hz",
    "average_abs_jerk_with_resampler_59Hz",
    "dropped_frame_count_with_resampler_59Hz",
    "janky_count_without_resampler_90Hz",
    "average_abs_jerk_without_resampler_90Hz",
    "dropped_frame_count_without_resampler_90Hz",
    "janky_count_without_resampler_59Hz",
    "average_abs_jerk_without_resampler_59Hz",
    "dropped_frame_count_without_resampler_59Hz"
  ]
}
```

The problem seems to happen after https://github.com/flutter/flutter/commit/a48e14308e41f75b6f63ee2549f4d597646b0dc4

See https://flutter-flutter-perf.skia.org/e/?begin=1599168329&end=1600967051&queries=sub_result%3Daverage_abs_jerk_with_resampler_59Hz%26sub_result%3Daverage_abs_jerk_without_resampler_59Hz%26test%3Dcomplex_layout_android__scroll_smoothness&requestType=0

**Comment by liyuqian** [comment]
CC @dkwingsmt @CareF

**Comment by CareF** [comment]
I did a local run and I can see that the scrolling gesture is NOT accepted here because a48e143 removed the override to accpet PointerData (which is considerred device input).

**Comment by dkwingsmt** [comment]
@CareF Sorry for not having asked you to review the PR before the merge. 
What do you mean by moving resampler to `handlePointerEvent`, isn't that already the case? https://github.com/flutter/flutter/commit/a48e14308e41f75b6f63ee2549f4d597646b0dc4#diff-6305361e0c7677f0eebfb05dfcbe0336R399

**Comment by CareF** [comment]
> @CareF Sorry for not having asked you to review the PR before the merge.
> What do you mean by moving resampler to `handlePointerEvent`, isn't that already the case? [a48e143#diff-6305361e0c7677f0eebfb05dfcbe0336R399](https://github.com/flutter/flutter/commit/a48e14308e41f75b6f63ee2549f4d597646b0dc4#diff-6305361e0c7677f0eebfb05dfcbe0336R399)

No. I mean move code blocks like https://github.com/flutter/flutter/blob/1510865fb45513124601a587229543c488103b14/packages/flutter/lib/src/gestures/binding.dart#L229-L237 to `handlePointerEvent` so that the resample logic happens in the method that the `WidgetTester` can cover.

**Comment by liyuqian** [comment]
CC @dreveman
