### ISSUE TITLE
Issue flutter APK no internet

### ISSUE THREAD

**Issue by magizhini6** [flutter/flutter#66616]
If internet my APK everything ok 

No internet APK just open Hank white screen long time nothing happens

**Comment by pedromassangocode** [comment]
Hi @magizhini6 
What is exactly the issue here? can you elaborate more?

Also please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by NaagAlgates** [comment]
Do you explicitly check the internet availability in your app? If so, can you please share the sample code of yours.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
