### ISSUE TITLE
shouldUseHotMode should be false when !device.supportsHotMode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6661]
`run.dart` has this code:
```dart
    final bool hotMode = shouldUseHotMode();
    if (hotMode) {
      if (!device.supportsHotMode) {
        printError('Hot mode is not supported by this device. '
                   'Run with --no-hot.');
        return 1;
      }
    }
```

It's not clear why we do this rather than just have `shouldUseHotMode` return false if `!device.supportsHotMode`.

**Comment by zoechi** [comment]
The code was changed https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter_tools/lib/src/commands/run.dart#L326-L331

Is this issue still valid?

**Comment by jonahwilliams** [comment]
This was cleaned up, as above
