### ISSUE TITLE
Failed assertion: line 2632 pos 14: 'node.parent?._dirty != true': is not true.

### ISSUE THREAD

**Issue by mxb9771** [flutter/flutter#66615]
**The Error in Console**
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2632 pos 14: 'node.parent?._dirty != true': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2632:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:449:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:907:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:310:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**flutter doctor -v**
[✓] Flutter (Channel master, 1.22.0-10.0.pre.353, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.353 at /Users/mattewbollinger/Documents/Development/SDK/flutter
    • Framework revision a6a8a14d02 (21 minutes ago), 2020-09-24 18:34:07 -0700
    • Engine revision e56080ab67
    • Dart version 2.11.0 (build 2.11.0-159.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mattewbollinger/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • B83A5904-C493-4180-B610-833689675AE2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

Thank you

**Comment by pedromassangocode** [comment]
Hi @mxb9771 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by mxb9771** [comment]
After looking at the verbose logging I saw that my podfile had the ios target commented out. Removing this and running 
-pod install
fixed the issue for me

Thank you
