### ISSUE TITLE
[webview_flutter] : Support html <input> tag to choose image

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#66626]

**Comment by darshankawar** [comment]
@hamberluo I think the `webview_flutter` plugin already supports html `<input>` tag. Please see [this](https://github.com/flutter/flutter/issues/27924) open issue which talks about unable to select any file using this tag.
Does that ticket sound similar to your request ?
Thanks.

**Comment by hamberluo** [comment]
@darshankawar yes same issue.
I just want to know when it will be merged.

**Comment by darshankawar** [comment]
@hamberluo Please follow-up in that ticket for updates and any questions.
Closing this as duplicate.
Thanks.
