### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by marshallunduemi** [flutter/flutter#66649]
```
C:\Users\CodeXpress\Documents\flutter\newapp>flutter run
Launching lib\main.dart on TECNO CD7 in debug mode...
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\CodeXpress\AppData\Local\Android\sdk\licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".  
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.      
Installing Android SDK Build-Tools 28.0.3 in C:\Users\CodeXpress\AppData\Local\Android\sdk\build-tools\28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.   
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.   
Checking the license for package Android SDK Platform 28 in C:\Users\CodeXpress\AppData\Local\Android\sdk\licenses
License for package Android SDK Platform 28 accepted.
Preparing "Install Android SDK Platform 28 (revision: 6)".              
Running Gradle task 'assembleDebug'...                                  
"Install Android SDK Platform 28 (revision: 6)" ready.
Installing Android SDK Platform 28 in C:\Users\CodeXpress\AppData\Local\Android\sdk\platforms\android-28
"Install Android SDK Platform 28 (revision: 6)" complete.
"Install Android SDK Platform 28 (revision: 6)" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_251' used by Gradle. Make sure Gradle is running on a JDK, 
not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 15s
Running Gradle task 'assembleDebug'...                          
Running Gradle task 'assembleDebug'... Done                       377.9s (!)
Exception: Gradle task assembleDebug failed with exit code 1

C:\Users\CodeXpress\Documents\flutter\newapp>
```

**Comment by TahaTesser** [comment]
Hi @marshallunduemi 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by marshallunduemi** [comment]
> 
> 
> Hi @marshallunduemi
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you


C:\Users\CodeXpress\Documents\flutter\myapp>flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19042.508], locale en-US)
    • Flutter version 1.20.4 at C:\src\flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\CodeXpress\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\CodeXpress\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by marshallunduemi** [comment]
> flutter run --verbose

C:\Users\CodeXpress\Documents\flutter\myapp>flutter run --verbose
[ +180 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +186 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] fba99f6cf9a14512e461e3122c8ddfaa25394e89
[   +3 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +457 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.20.4
[  +37 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +125 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[  +11 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +106 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +197 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +101 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +89 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] executing: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +71 ms] List of devices attached
           054802505I000207       device product:CD7-GL model:TECNO_CD7 device:TECNO-CD7 transport_id:3
[  +12 ms] C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe -s 054802505I000207 shell getprop
[ +188 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +68 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +55 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1693 ms] Generating C:\Users\CodeXpress\Documents\flutter\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +125 ms] ro.hardware = mt6765
[   +3 ms] ro.build.characteristics = default
[ +301 ms] Starting incremental build...
[   +9 ms] Initializing file store
[  +34 ms] Skipping target: gen_localizations
[ +332 ms] complete
[  +24 ms] Launching lib\main.dart on TECNO CD7 in debug mode...
[  +62 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\CodeXpress\AppData\Local\Temp\flutter_tools.21cd8ec6\flutter_tool.91167d76\app.dill --packages .packages-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts     
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +216 ms] executing: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe -s 054802505I000207 shell -x logcat -v time -t 1
[ +208 ms] Exit code 0 from: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe -s 054802505I000207 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           09-25 18:24:59.752 D/IOManager( 2685): wl = 1,rt_time = 0,rt_data = 0,wt_time = 0,wt_data = 0,pid = 0,data = 0
[  +68 ms] executing: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe -s 054802505I000207 shell -x logcat -v time -t 1
[ +195 ms] Exit code 0 from: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe -s 054802505I000207 shell -x logcat -v time -t 1
[   +3 ms] --------- beginning of main
           09-25 18:25:00.026 D/NotificationHeaderViewWrapper( 2061): updateExpandability: expandable:true
[ +125 ms] <- compile package:myapp/main.dart
[  +58 ms] executing: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +108 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\CodeXpress\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +64 ms] Building APK
[  +35 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[ +209 ms] Using gradle from C:\Users\CodeXpress\Documents\flutter\myapp\android\gradlew.bat.
[  +49 ms] C:\Users\CodeXpress\Documents\flutter\myapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +65 ms] executing: [C:\Users\CodeXpress\Documents\flutter\myapp\android/] C:\Users\CodeXpress\Documents\flutter\myapp\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=C:\Users\CodeXpress\Documents\flutter\myapp\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root    
assembleDebug
[ +524 ms] lib/main.dart:1:9: Error: Expected ';' after this.
[   +1 ms] flutter doctor -vimport 'package:flutter/material.dart';
[        ]         ^^^^^^
[  +27 ms] lib/main.dart:1:16: Error: Expected a declaration, but got '-'.
[  +41 ms] flutter doctor -vimport 'package:flutter/material.dart';
[   +1 ms]                ^
[   +1 ms] lib/main.dart:1:17: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
[   +2 ms] Try adding the name of the type of the variable or the keyword 'var'.
[   +1 ms] flutter doctor -vimport 'package:flutter/material.dart';
[   +1 ms]                 ^^^^^^^
[  +27 ms] lib/main.dart:1:17: Error: Expected ';' after this.
[   +1 ms] flutter doctor -vimport 'package:flutter/material.dart';
[        ]                 ^^^^^^^
[        ] lib/main.dart:1:25: Error: Expected a declaration, but got ''package:flutter/material.dart''.
[        ] flutter doctor -vimport 'package:flutter/material.dart';
[        ]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] lib/main.dart:1:56: Error: Unexpected token ';'.
[  +92 ms] flutter doctor -vimport 'package:flutter/material.dart';
[   +1 ms]                                                        ^
[        ] lib/main.dart:1:1: Error: Type 'flutter' not found.
[   +1 ms] flutter doctor -vimport 'package:flutter/material.dart';
[        ] ^^^^^^^
[        ] lib/main.dart:7:21: Error: Type 'StatelessWidget' not found.
[        ] class MyApp extends StatelessWidget {
[        ]                     ^^^^^^^^^^^^^^^
[        ] lib/main.dart:10:3: Error: Type 'Widget' not found.
[  +16 ms]   Widget build(BuildContext context) {
[  +25 ms]   ^^^^^^
[   +6 ms] lib/main.dart:10:16: Error: Type 'BuildContext' not found.
[   +1 ms]   Widget build(BuildContext context) {
[  +56 ms]                ^^^^^^^^^^^^
[   +1 ms] lib/main.dart:34:26: Error: Type 'StatefulWidget' not found.
[   +1 ms] class MyHomePage extends StatefulWidget {
[   +1 ms]                          ^^^^^^^^^^^^^^
[   +1 ms] lib/main.dart:35:15: Error: Type 'Key' not found.
[   +1 ms]   MyHomePage({Key key, this.title}) : super(key: key);
[   +1 ms]               ^^^
[   +1 ms] lib/main.dart:52:32: Error: Type 'State' not found.
[        ] class _MyHomePageState extends State<MyHomePage> {
[  +14 ms]                                ^^^^^
[  +12 ms] lib/main.dart:52:32: Error: Expected 0 type arguments.
[   +1 ms] class _MyHomePageState extends State<MyHomePage> {
[   +1 ms]                                ^
[  +75 ms] lib/main.dart:67:3: Error: Type 'Widget' not found.
[  +91 ms]   Widget build(BuildContext context) {
[        ]   ^^^^^^
[   +1 ms] lib/main.dart:67:16: Error: Type 'BuildContext' not found.
[  +12 ms]   Widget build(BuildContext context) {
[   +1 ms]                ^^^^^^^^^^^^
[        ] lib/main.dart:1:1: Error: 'flutter' isn't a type.
[        ] flutter doctor -vimport 'package:flutter/material.dart';
[        ] ^^^^^^^
[        ] lib/main.dart:4:3: Error: Method not found: 'runApp'.
[        ]   runApp(MyApp());
[   +2 ms]   ^^^^^^
[  +12 ms] lib/main.dart:10:16: Error: 'BuildContext' isn't a type.
[        ]   Widget build(BuildContext context) {
[        ]                ^^^^^^^^^^^^
[   +1 ms] lib/main.dart:11:12: Error: The method 'MaterialApp' isn't defined for the class 'MyApp'.
[  +16 ms]  - 'MyApp' is from 'package:myapp/main.dart' ('lib/main.dart').
[  +11 ms] Try correcting the name to the name of an existing method, or defining a method named 'MaterialApp'.
[        ]     return MaterialApp(
[        ]            ^^^^^^^^^^^
[        ] lib/main.dart:13:14: Error: The method 'ThemeData' isn't defined for the class 'MyApp'.
[   +1 ms]  - 'MyApp' is from 'package:myapp/main.dart' ('lib/main.dart').
[  +16 ms] Try correcting the name to the name of an existing method, or defining a method named 'ThemeData'.
[  +13 ms]       theme: ThemeData(
[        ]              ^^^^^^^^^
[        ] lib/main.dart:23:24: Error: The getter 'Colors' isn't defined for the class 'MyApp'.
[        ]  - 'MyApp' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
[  +14 ms]         primarySwatch: Colors.blue,
[        ]                        ^^^^^^
[        ] lib/main.dart:27:24: Error: The getter 'VisualDensity' isn't defined for the class 'MyApp'.
[   +1 ms]  - 'MyApp' is from 'package:myapp/main.dart' ('lib/main.dart').
[  +14 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'VisualDensity'.
[        ]         visualDensity: VisualDensity.adaptivePlatformDensity,
[  +24 ms]                        ^^^^^^^^^^^^^
[   +1 ms] lib/main.dart:35:15: Error: 'Key' isn't a type.
[        ]   MyHomePage({Key key, this.title}) : super(key: key);
[        ]               ^^^
[        ] lib/main.dart:35:45: Error: No named parameter with the name 'key'.
[        ]   MyHomePage({Key key, this.title}) : super(key: key);
[        ]                                             ^^^
[        ] lib/main.dart:56:5: Error: The method 'setState' isn't defined for the class '_MyHomePageState'.
[        ]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'setState'.
[   +1 ms]     setState(() {
[  +12 ms]     ^^^^^^^^
[        ] lib/main.dart:67:16: Error: 'BuildContext' isn't a type.
[   +1 ms]   Widget build(BuildContext context) {
[   +1 ms]                ^^^^^^^^^^^^
[        ] lib/main.dart:99:22: Error: 'Widget' isn't a type.
[  +14 ms]           children: <Widget>[
[   +1 ms]                      ^^^^^^
[   +1 ms] lib/main.dart:74:12: Error: The method 'Scaffold' isn't defined for the class '_MyHomePageState'.
[  +14 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Scaffold'.
[   +1 ms]     return Scaffold(
[  +15 ms]            ^^^^^^^^
[  +16 ms] lib/main.dart:75:15: Error: The method 'AppBar' isn't defined for the class '_MyHomePageState'.
[   +7 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'AppBar'.
[   +1 ms]       appBar: AppBar(
[   +1 ms]               ^^^^^^
[   +1 ms] lib/main.dart:78:16: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
[        ]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Text'.
[        ]         title: Text(widget.title),
[  +26 ms]                ^^^^
[   +1 ms] lib/main.dart:78:21: Error: The getter 'widget' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
[   +1 ms]         title: Text(widget.title),
[   +1 ms]                     ^^^^^^
[   +1 ms] lib/main.dart:80:13: Error: The method 'Center' isn't defined for the class '_MyHomePageState'.
[  +32 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Center'.
[  +17 ms]       body: Center(
[  +10 ms]             ^^^^^^
[   +1 ms] lib/main.dart:83:16: Error: The method 'Column' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Column'.
[  +18 ms]         child: Column(
[   +5 ms]                ^^^^^^
[   +1 ms] lib/main.dart:98:30: Error: The getter 'MainAxisAlignment' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'MainAxisAlignment'.
[   +1 ms]           mainAxisAlignment: MainAxisAlignment.center,
[   +1 ms]                              ^^^^^^^^^^^^^^^^^
[   +2 ms] lib/main.dart:100:13: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
[  +23 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Text'.
[   +1 ms]             Text(
[   +1 ms]             ^^^^
[   +1 ms] lib/main.dart:103:13: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +5 ms] Try correcting the name to the name of an existing method, or defining a method named 'Text'.
[  +24 ms]             Text(
[   +1 ms]             ^^^^
[   +1 ms] lib/main.dart:105:22: Error: The getter 'Theme' isn't defined for the class '_MyHomePageState'.
[   +6 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[  +37 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'Theme'.
[   +2 ms]               style: Theme.of(context).textTheme.headline4,
[   +1 ms]                      ^^^^^
[   +1 ms] lib/main.dart:110:29: Error: The method 'FloatingActionButton' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[  +24 ms] Try correcting the name to the name of an existing method, or defining a method named 'FloatingActionButton'.
[   +1 ms]       floatingActionButton: FloatingActionButton(
[   +1 ms]                             ^^^^^^^^^^^^^^^^^^^^
[   +1 ms] lib/main.dart:113:16: Error: The method 'Icon' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'Icon'.
[   +1 ms]         child: Icon(Icons.add),
[  +25 ms]                ^^^^
[   +1 ms] lib/main.dart:113:21: Error: The getter 'Icons' isn't defined for the class '_MyHomePageState'.
[   +1 ms]  - '_MyHomePageState' is from 'package:myapp/main.dart' ('lib/main.dart').
[   +1 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'Icons'.
[   +1 ms]         child: Icon(Icons.add),
[   +1 ms]                     ^^^^^
[+4420 ms] Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

**Comment by TahaTesser** [comment]
Hi @marshallunduemi 
Your logs are incomplete, can your complete `flutter run --verbose` logs **while connected toa device/emulato**r and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
