### ISSUE TITLE
Request for a official flutter documentation in Pdf format

### ISSUE THREAD

**Issue by satviksinha12** [flutter/flutter#66643]
Hello flutter team I wanted to convey that there should be a pdf for flutter documentation , because the people who  have trouble with internet in their area for example - remote areas won't be able to access internet to visit flutter documentation all the times. This will cause them to Drop flutter language as they will be unable to learn and use the language on time and it will severely cost them time.

**Comment by TahaTesser** [comment]
Hi @satviksinha12 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/61335
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
