### ISSUE TITLE
[image_picker] It is possible to pick disallowed images and use them on iOS 14

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#66650]
The fact that we are able to see all images in the gallery seems WAI from Apple's perspective. You will see the entire photos library but you won't have access to the assets selected if you have not given permission. https://developer.apple.com/videos/play/wwdc2020/10652/?t=734

However, the clients are reporting that they are not only able to see all the photos, they are able to use the picked photos in the app even though the user did not give permission. This is a privacy issue. 

I am quite surprised by this. That plugin just calls standard iOS APIs. We are not doing anything "fishy" :) Seems like a security hole in Apple's design. Perhaps we are expected to call an API on the asset object and verify the app has access.

See internal bug for videos: b/169290910

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/65995

**Comment by mehmetf** [comment]
Thanks @TahaTesser . It does indeed seem to be the same thing. Though, we are not observing the crash for whatever reason.

The request here is more around privacy where we should not be able to **use** images that the user has not given permission to. We should return the appropriate error to the app. Viewing and selecting all images is WAI.

**Comment by mehmetf** [comment]
Dupe of #65995
