### ISSUE TITLE
Flutter iOS: only executed the native code without entering the main method

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#66655]
The following situations currently only appear on iOS：

I have a flutter project, and recently I found a problem. The code in the main method is often not executed, which means that no flutter code will be executed.

The way of expression is that after starting the App, it stays on the start-up diagram page and there is no obvious error message. Does anyone know why? Even though AppDelegate.m only has basic code, this is the case.

Hope the following is helpful:

[stackoverflow](https://stackoverflow.com/questions/64067657/flutter-ios-only-executed-the-native-code-without-entering-the-main-method)

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15.7 19H2,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/lizhuoyuan/Development/flutter
    • Framework revision 0b8abb4724 (8 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lizhuoyuan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lizhuoyuan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ONEPLUS A5000 • f6f90654 • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by darshankawar** [comment]
Hi @lizhuoyuan,
You seem to be on very old version of Flutter. First of all, upgrade to latest Flutter version and try again to see if it works.
If problem persists, please provide minimal complete code sample that shows the issue along with `pubspec.yaml`.
thanks.

**Comment by lizhuoyuan** [comment]
Sorry, it's the configuration problem of my own file：ios/Runner.xcodeproj/project.pbxproj
