### ISSUE TITLE
Hardware buttons plugin doesn't help disable home button

### ISSUE THREAD

**Issue by Ashutosh3011** [flutter/flutter#66667]
I want my app to not go on homescreen or lock fir security purpose...i tried using hardware_buttons plugin...but that doesn't help with my issue... does flutter have a plugin/ function for doing this or it's an issue with flutter?

Please suggest a way if anyone knows

**Comment by iapicca** [comment]
[hardware_buttons](https://pub.dev/packages/hardware_buttons) is a [deprecated plugins](https://github.com/flutter-moum/flutter_hardware_buttons#deprecated)

if you need help to write you application it's better to ask a question on [StackOverflow](https://stackoverflow.com/)
as indicated in the [new issue](https://github.com/flutter/flutter/issues/new/choose) template for `I want help writing my application`

**Comment by darshankawar** [comment]
@Ashutosh3011 
Per above comment, your question seem to be better suited for StackOverflow. You may use the `new issue` template to ask your question or please see https://flutter.dev/community for resources and asking questions like this.
If you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
