### ISSUE TITLE
Possible regression in diff-min test flutter_gallery__back_button_memory

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66660]
https://flutter-flutter-perf.skia.org/e/?begin=1600811383&end=1600821849&keys=X4eb663bdedf7de585454f04faae3e6fb&num_commits=50&request_type=1&xbaroffset=21587

Memory dashboard entries are typically pretty noisy, but there's a peak up towards the end probably worth investigating.

Looks like some recent tools commits are what started the trend, but I'm _really_ skeptical about this.

See, for example, https://github.com/flutter/flutter/pull/66266.

I'm giving this a relatively low priority, because I'm not 100% convinced it's a real regression, and it's small.

**Comment by jonahwilliams** [comment]
There is zero chance that the tool PR affected this, because that only added an interface without using to the tool - in order to first roll it to g3

**Comment by kf6gpe** [comment]
Downgrading to a P3. cc @liyuqian and @dnfield for performance musings. I agree with Jonah; this isn't the tools PRs.

**Comment by liyuqian** [comment]
It looks like a noise to me when I zoomed out (press `s`): https://flutter-flutter-perf.skia.org/e/?begin=1597118164&end=1601403861&keys=X4eb663bdedf7de585454f04faae3e6fb&requestType=0&xbaroffset=21587

**Comment by kf6gpe** [comment]
Good. I'd believe that. Closing.
