### ISSUE TITLE
Gallery missing "run configs" for IntelliJ

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6666]
I'd like to open the Gallery in IntelliJ and then run it, via IntelliJ.

It looks like we don't have run configs checked in for the gallery, so when I open/import Gallery into IntelliJ, I see this:

![screen shot 2016-11-02 at 2 19 47 pm](https://cloud.githubusercontent.com/assets/5479/19947911/6ecbaf30-a107-11e6-987e-8059f1c7348b.png)

Notice how I don't have any run configs here.

Should we check in configs for flutter's default modes? (debug, profile, release)

**Comment by mit-mit** [comment]
@devoncarew what are we missing here?

**Comment by devoncarew** [comment]
The flutter repo's generally set up to be opened as one IntelliJ project, opening all the submodules in packages/ and examples/. If you do that, you get the launch configurations defined in //.idea/runConfigurations.

If we want to support opening the gallery package as its own separate project, we'd need to copy  //.idea/runConfigurations/flutter_gallery.xml to //examples/flutter_gallery/.idea/runConfigurations.

**Comment by sethladd** [comment]
If the best practice is to open the entire flutter repo in order to run the gallery, I can do that. Maybe we should add something to the gallery README?

I will try opening the main repo and let you know what happens.

Thanks for the guidance.

**Comment by mit-mit** [comment]
@devoncarew, please review: https://github.com/flutter/flutter/pull/6759
