### ISSUE TITLE
Update flutter daemon API docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6667]
Once we're stable again, we should update this wiki page to document the new `flutter run --machine` and `flutter daemon` protocols:

https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode

@devoncarew @danrubel

**Comment by danrubel** [comment]
daemon mode wiki pages [have been updated](https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode/_compare/619bd3de14a68824b05c910afb972cde90c9fe19...950b94b459a7bba2fb08a704c1ba13a7ed990001).
