### ISSUE TITLE
Engine roller blocked due to switch statements enforcing non-null enums

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#66674]
A recent change to the Dart SDK will throw an exception if a null value is passed to an exhaustive switch statement on a non-nullable enum type.
(see https://github.com/dart-lang/sdk/commit/2414b293e1a6756bd8e0b32d3fad4927ec38076f)

This is causing failures in some tests.  In particular, tests that pass a mock `HttpResponse` to `consolidateHttpClientResponseBytes` will now need to populate the `compressionState` field.

**Comment by zanderso** [comment]
The roll is now failing on https://github.com/flutter/flutter/issues/66829
