### ISSUE TITLE
Install flutter using snap

### ISSUE THREAD

**Issue by rooton** [flutter/flutter#66681]
Nothing special just follow https://flutter.dev/docs/get-started/install/linux

1. Operating System: Linux Mint 18.3
2. run: sudo snap install flutter --classic
3. run: flutter doctor 

flutter: command not found

Where is it installed **/home/username/** doesn't contain snap directory
/snap/flutter/current contains, but its impossible to add it to VS Code and running flutter command from terminal unsuccessful.

What is wrong...with flutter?

**Comment by jonahwilliams** [comment]
Please file issue for the flutter snap at https://github.com/canonical/flutter-snap . This is not maintained as part of the Flutter SDK
