### ISSUE TITLE
Gestures outlast IgnorePointer

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#667]
Inserting an IgnorePointer between the root and an object that currently has an ongoing gesture should interrupt the gesture, because otherwise you can do things like this:

1. Tap and hold a row in the stocks app.
2. Tap another row.
3. Release the first tap before the animation has finished.
4. Hit back before the animation has finished.
5. See a snack bar appear.

...or:

1. Tap two rows simultaneously, but slightly out of sync so that one tap ends in a frame after the frame in which the other ends, but before the animation ends.
2. See two stock view pages come up.

**Comment by abarth** [comment]
We fixed this by making the navigator cancel ongoing gestures.
