### ISSUE TITLE
Don't bundle Roboto font by default on iOS

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#6670]
Post #4956, we now default to San Francisco on iOS 9+ and the system default (Helvetica Neue) for iOS < 9. Since Roboto is no longer used by default, it shouldn't be bundled in the .flx unless the developer explicitly requests it.

**Comment by xster** [comment]
Generalizing this to remove automatic bundling of any fonts.

Any dissent?

**Comment by abarth** [comment]
We might need to include the MaterialIcon font if the app `uses-material-design`

**Comment by xster** [comment]
Yes, leaving the material icon font

**Comment by xster** [comment]
https://fuchsia-review.googlesource.com/c/21667/

**Comment by cbracken** [comment]
@xster is this complete now?

**Comment by cbracken** [comment]
Nice! That's 2MB back on every iOS Flutter app that doesn't use Roboto!

**Comment by sethladd** [comment]
W00t!!
