### ISSUE TITLE
Migrate deploy_gallery to LUCI

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#66707]
Please migrate deploy_gallery for mac and linux to luci. This test requires many secrets which have been already added to gcp KMS.

This test should be implemented as a adhoc test.

**Comment by keyonghan** [comment]
Per discussion with @xster , we will stop deploying to play store for linux case in this test. FWIW: deployment of new gallery will be automated on LUCI.

Related issue: https://github.com/flutter/gallery/issues/337

**Comment by godofredoc** [comment]
@keyonghan  Can we close this bug?

**Comment by keyonghan** [comment]
> @keyonghan Can we close this bug?

Yes. Closing.
