### ISSUE TITLE
How Can I listen the Page is current page

### ISSUE THREAD

**Issue by hamicyy** [flutter/flutter#66717]
I open PageA and Open PageB in A，use pushReplacementNamed Open pageC in B，When I closed pageC，how can I listen the PageA is the current page？my flutter version is 1.20.4，the old sdk 1.12.13 can use deactivate method to listen，but 1.20.4 is useless

**Comment by darshankawar** [comment]
Hi @hamicyy 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
