### ISSUE TITLE
CustomPainter allows painting outside even if canvas.clipRect(rect) called correctly

### ISSUE THREAD

**Issue by maRci002** [flutter/flutter#66719]
On Android emulator `Pixel 2 (1080 * 1920; 420 dpi; API: 29)` I was able to paint outside of `CustomPainter`'s bounds which shouldn't happen because `canvas.clipRect(rect)` was called with the correct size.

Minimal code to reproduce:
```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Canvas test')),
      body: Padding(
        padding: EdgeInsets.all(40.0),
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(
              color: Colors.black,
              width: 1.0,
            ),
          ),
          child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints bc) {
              final size = Size(bc.maxWidth, bc.maxHeight);
              return CustomPaint(
                painter: TestPainter(),
                size: size,
              );
            },
          ),
        ),
      ),
    );
  }
}

class TestPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final rect = Offset.zero & size;
    canvas.clipRect(rect);

    final paint = Paint();
    paint
      ..style = PaintingStyle.fill
      ..color = Colors.red;
    paint.strokeWidth = 3.0;

    var offsets = [
      Offset(rect.width - 30, rect.height / 2),
      Offset(rect.width + 30, rect.height / 2),
      Offset(rect.width + 30, rect.height / 2 + 60),
      Offset(rect.width - 30, rect.height / 2 + 60),
    ];

    canvas.drawPoints(PointMode.points, [...offsets, offsets[0]], paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

Result:
![image](https://user-images.githubusercontent.com/8436039/94337058-e738a980-ffe7-11ea-8a1e-f6021734a4fe.png)

Result if `canvas.clipRect(rect);` commented out (which is correct):
![image](https://user-images.githubusercontent.com/8436039/94337086-10593a00-ffe8-11ea-9b5a-8722a49b9965.png)

If I change `PointMode.lines` to `PointMode.polygon`
![image](https://user-images.githubusercontent.com/8436039/94337145-852c7400-ffe8-11ea-9ce5-eccb9d01399d.png)

If I change `PointMode.lines` to `PointMode.polygon` and comment out `paint.strokeWidth = 3.0;` then everything works fine, I think `strokeWidth` ruins the whole thing.
![image](https://user-images.githubusercontent.com/8436039/94337162-bb69f380-ffe8-11ea-8a5d-546aa8b4c968.png)

<details>
<summary>flutter doctor</summary>
<pre>
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale hu-HU)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\maRci002\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\maRci002\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
</pre>
</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

**Comment by xu-baolin** [comment]
@liyuqian Hi,
This question is probably related to Skia, I think this is your area of expertise ：）

**Comment by jason-simmons** [comment]
This regressed with a change to Skia clipping: https://github.com/google/skia/commit/9716414e93f7b279e547595fab08b68235c4b2be

@lhkbob

**Comment by lhkbob** [comment]
I was able to reproduce and identify the cause, I have a fix in the works for Skia here: https://skia-review.googlesource.com/c/skia/+/320965.
