### ISSUE TITLE
Could not build the application for the simulator - Error launching application on iPhone 8.

### ISSUE THREAD

**Issue by gireeshkbogu** [flutter/flutter#66730]
I have installed the latest flutter and Xcode and tried all possible solutions on Stackoverflow (for ex: flutter clean) but still running into this issue. I am so excited to try Flutter but It is frustrating to get stuck at installation for so many hours.  

```
$ flutter run
Launching lib/main.dart on iPhone 6s in debug mode...
 
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         9.2s
Xcode build done.                                           36.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ld: unknown option: -target
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 6s.
```

**Comment by erickzanardo** [comment]
Hey @gireeshkbogu can you please post the result of your `flutter doctor -v` here?

**Comment by gireeshkbogu** [comment]
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.380, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by gireeshkbogu** [comment]
I found the solution [here](https://github.com/flutter/flutter/issues/20685). Thanks anyways.

**Comment by darshankawar** [comment]
@gireeshkbogu 
Can you try to run app from Xcode and see if you get same error ?
Also provide the build target version mentioned in Xcode along with podfile.
Thanks.

**Comment by gireeshkbogu** [comment]
Yes, it works with Xcode. I am not sure If I understand your second question. How can I do something like that?

**Comment by darshankawar** [comment]
@gireeshkbogu 
The build target or deployment target can be found in Xcode, as below:

<img width="979" alt="Screenshot 2020-09-28 at 6 50 27 PM" src="https://user-images.githubusercontent.com/67046386/94437695-bdd07700-01bb-11eb-84e3-4df46b4b3bbd.png">

And `podfile` is located inside your project's `ios` folder:

<img width="330" alt="Screenshot 2020-09-28 at 6 51 17 PM" src="https://user-images.githubusercontent.com/67046386/94437761-d6d92800-01bb-11eb-8003-cc73b6d1ddc3.png">

**Comment by gireeshkbogu** [comment]
Thanks. I didn't find pod file though. 

<img width="897" alt="Screen Shot 2020-09-28 at 10 50 55 AM" src="https://user-images.githubusercontent.com/3885659/94468151-d8cdc780-0178-11eb-88a6-725d1fd5d8af.png">

<img width="752" alt="Screen Shot 2020-09-28 at 10 52 49 AM" src="https://user-images.githubusercontent.com/3885659/94468163-db302180-0178-11eb-8182-599b605ac371.png">

**Comment by darshankawar** [comment]
@gireeshkbogu Usually the `ios` folder should have the `podfile` and `podfile.lock`.
Can you cd to ios folder and run `pod install` and then `cd ..` and run `flutter run` ?
Thanks.

**Comment by gireeshkbogu** [comment]
I ran into. this error. 
```
$ pod install
[!] No `Podfile' found in the project directory.
```

**Comment by gireeshkbogu** [comment]
I tried this 

```
$ pod init
$ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.

[!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

**Comment by darshankawar** [comment]
@gireeshkbogu 
Can you create a new project and check if you see `Podfile` inside `ios` folder ? Usually following files should be present inside `ios` folder. If some files are missing after creating a new project, then I think your Flutter sdk setup seems to be incomplete or not installed correctly.

<img width="314" alt="Screenshot 2020-09-30 at 11 11 30 AM" src="https://user-images.githubusercontent.com/67046386/94647334-dbadf100-030d-11eb-8f56-c10dc9e7f6bc.png">

**Comment by erickzanardo** [comment]
@darshankawar The `Podfile` only exists inside the `ios` if your project has any plugins, otherwise it don't exists, so in a freshly created project, the `Podfile` will not exist, so I think the Podfile is not the issue here.

@gireeshkbogu I noticed something on your description:

```
$ flutter run
Launching lib/main.dart on iPhone 6s in debug mode...
```

As fas as I remember, XCode 12 don't come with the iPhone 6s simulator

Can you confirm if your xcode has that simulator by opening xcode and clicking the simulator button on the top bar.

Example, this is what my xcode shows me
![Captura de Tela 2020-09-30 às 09 30 46](https://user-images.githubusercontent.com/835641/94685313-a1d5ee00-02ff-11eb-9e21-070b957422ec.png)

**Comment by gireeshkbogu** [comment]
@erickzanardo yes it does 
@darshankawar I could reinstall it maybe?

**Comment by darshankawar** [comment]
@darshankawar please give it a try and see if it works.

**Comment by gireeshkbogu** [comment]
I reinstalled both Xcode and Flutter and still the same issue. 
I did everything according to the flutter tutorial. Still the same issue. 

```
@x86_64-apple-darwin13 my_app1 % flutter run      
Launching lib/main.dart on iPhone 8 in debug mode...
 
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         2.0s
Xcode build done.                                           19.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ld: unknown option: -target
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8.
```
<img width="395" alt="Screen Shot 2020-10-07 at 9 55 45 AM" src="https://user-images.githubusercontent.com/3885659/95362766-67ca9600-0883-11eb-9ff7-e68a4a65d276.png">

**Comment by gireeshkbogu** [comment]
Finally it worked. It seems Catalina mac os you need to put the flutter bin path .zprofile instead of .bash_profile. Thank you for all the help.
