### ISSUE TITLE
[google_maps_flutter] iOS BUILD FAILED - Google Maps and Google Places conflicts

### ISSUE THREAD

**Issue by dospringer** [flutter/flutter#66746]
"flutter run" failed on iOS with the following message, but on Android it works without any problems.

<details>
  <summary>flutter run</summary>
`✗ flutter run          
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running Xcode build...                                                  
                                                   
Xcode build done.                                           14.4s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-09-26 20:42:41.830 xcodebuild[62503:856039] warning:  The file reference for "GoogleMaps.debug.xcconfig" is a member of multiple groups ("Support Files"
    and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be
    unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2020-09-26 20:42:41.830 xcodebuild[62503:856039] warning:  The file reference for "GoogleMaps.release.xcconfig" is a member of multiple groups ("Support
    Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will
    be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    ** BUILD FAILED **

Xcode's output:
↳
    While building module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    In file included from :1:
    In file included from /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GoogleMaps.h:56:
    In file included from /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacePicker.h:11:
    In file included from /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacePickerConfig.h:12:
    In file included from /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesClient.h:15:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:28:14: warning: expected quoted string
    after equals sign [-Wdocumentation]
       * community and support page.
                ~^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:28:19: warning: HTML start tag
    prematurely ended, expected attribute name or '>' [-Wdocumentation]
       * community and support page.
                      ^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:35:14: warning: expected quoted string
    after equals sign [-Wdocumentation]
       * community and support page.
                ~^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:35:19: warning: HTML start tag
    prematurely ended, expected attribute name or '>' [-Wdocumentation]
       * community and support page.
                      ^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:64:4: warning: HTML start tag
    prematurely ended, expected attribute name or '>' [-Wdocumentation]
       * href="https://developers.google.com/places/ios-api/usage">usage limits guide for more
       ^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:63:63: note: HTML tag started here
       * the API that far exceeds normal request levels. See the ' [-Wdocumentation]
       * href="https://developers.google.com/places/ios-api/usage">usage limits guide for more
       ^
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:72:63: note: HTML tag started here
       * the API that far exceeds normal request levels. See the  *types;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSAddressComponent.h:28:48: note: but in 'GoogleMaps'
    found property name 'name'
    @property(nonatomic, readonly, copy) NSString *name;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlaceLikelihoodList.h:38:10: error:
    'GMSPlaceLikelihoodList' has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSPlaceLikelihoodList' found
    default 'nullability' property attribute
    @property(nonatomic, copy, readonly, nullable) NSAttributedString *attributions;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlaceLikelihoodList.h:38:10: note: but in
    'GoogleMaps' found no written or default attribute for property
    @property(nonatomic, copy, readonly) NSAttributedString *GMS_NULLABLE_PTR attributions;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAutocompletePrediction.h:79:10: error:
    'GMSAutocompletePrediction' has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSAutocompletePrediction'
    found default 'nullability' property attribute
    @property(nonatomic, copy, readonly, nullable) NSAttributedString *attributedSecondaryText;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSAutocompletePrediction.h:68:10: note: but in
    'GoogleMaps' found no written or default attribute for property
    @property(nonatomic, copy, readonly) NSAttributedString *GMS_NULLABLE_PTR attributedSecondaryText;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAutocompleteFilter.h:83:10: error:
    'GMSAutocompleteFilter' has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSAutocompleteFilter' found
    default 'nullability' property attribute
    @property(nonatomic, copy, nullable) NSString *country;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSAutocompleteFilter.h:70:10: note: but in 'GoogleMaps'
    found no written or default attribute for property
    @property(nonatomic, copy) NSString *GMS_NULLABLE_PTR country;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlacePhotoMetadata.h:29:10: error:
    'GMSPlacePhotoMetadata' has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSPlacePhotoMetadata' found
    default 'nullability' property attribute
    @property(nonatomic, readonly, copy, nullable) NSAttributedString *attributions;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacePhotoMetadata.h:31:10: note: but in 'GoogleMaps'
    found no written or default attribute for property
    @property(nonatomic, readonly, copy) NSAttributedString* GMS_NULLABLE_PTR attributions;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlace.h:113:58: error: 'GMSPlace' has different
    definitions in different modules; first difference is definition in module 'GooglePlaces.GMSPlace' found property 'name' with type 'NSString * _Nullable'
    @property(nonatomic, copy, readonly, nullable) NSString *name;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlace.h:49:48: note: but in 'GoogleMaps' found
    property 'name' with type 'NSString * _Nonnull'
    @property(nonatomic, copy, readonly) NSString *name;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlaceLikelihood.h:37:1: error:
    'GMSPlaceLikelihood' has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSPlaceLikelihood' found method
    with designater initializer
    - (instancetype)initWithPlace:(GMSPlace *)place
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlaceLikelihood.h:37:1: note: but in 'GoogleMaps'
    found method with no designater initializer
    - (instancetype)initWithPlace:(GMSPlace *)place likelihood:(double)likelihood;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlacesClient.h:121:1: error: 'GMSPlacesClient'
    has different definitions in different modules; first difference is definition in module 'GooglePlaces.GMSPlacesClient' found return type is 'BOOL' (aka
    '_Bool')
    + (BOOL)provideAPIKey:(NSString *)key;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesClient.h:102:1: note: but in 'GoogleMaps' found
    different return type 'void'
    - (void)reportDeviceAtPlaceWithID:(NSString *)placeID;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAutocompleteViewController.h:118:10: error:
    'GMSAutocompleteViewController' has different definitions in different modules; first difference is definition in module
    'GooglePlaces.GMSAutocompleteViewController' found default 'nullability' property attribute
    @property(nonatomic, weak, nullable) IBOutlet id delegate;
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'GoogleMaps' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSAutocompleteViewController.h:103:10: note: but in
    'GoogleMaps' found no written or default attribute for property
    @property(nonatomic, weak)
    ~~~~~~~~~^~~~~~~~~~~~~~~~~
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.m:82:36: warning:
    'autocompleteBoundsMode' is deprecated: autocompleteBoundsMode property is deprecated in favor of autocompleteFilter.locationBias or
    autocompleteFilter.locationRestriction [-Wdeprecated-declarations]
                autocompleteController.autocompleteBoundsMode = kGMSAutocompleteBoundsModeRestrict;
                                       ^
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAutocompleteViewController.h:134:54: note:
    'autocompleteBoundsMode' has been explicitly marked deprecated here
        GMSAutocompleteBoundsMode autocompleteBoundsMode __GMS_PLACES_AVAILABLE_BUT_DEPRECATED_MSG(
                                                         ^
    In module 'GooglePlaces' imported from
    /Users/dominikspringer/.pub-cache/hosted/pub.dartlang.org/google_places_picker-2.1.0+2/ios/Classes/GooglePlacesPickerPlugin.h:2:
    /Users/dominikspringer/Code/git/meisight/ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSPlacesDeprecationUtils.h:19:56: note: expanded
    from macro '__GMS_PLACES_AVAILABLE_BUT_DEPRECATED_MSG'
    #define __GMS_PLACES_AVAILABLE_BUT_DEPRECATED_MSG(msg) __deprecated_msg(msg)
                                                           ^
    In module 'UIKit' imported from /Users/dominikspringer/Code/git/meisight/ios/Pods/Target Support
    Files/google_places_picker/google_places_picker-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framewor
    k/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.fra
    mework/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation
    .framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/sys/cdefs.h:200:48: note:
    expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    7 warnings and 9 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).`
</details>

<details>
 <summary>flutter doctor -v</summary>
flutter doctor -v
`[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-DE)
    • Flutter version 1.20.4 at /Users/dominikspringer/Code/DevTools/flutter/flutter
    • Framework revision fba99f6cf9 (12 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominikspringer/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 399DDF14-7DE4-4B13-9909-1943FAFCE08A • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)`
<details>

**Comment by pedromassangocode** [comment]
Hi @dospringer 
Can you please provide a minimal complete reproducible code sample and the content of your `Podfile`?
Thank you

**Comment by dospringer** [comment]
Thanks for your response @pedromassangocode 

Currently I use this Podfile:

platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
  end
end

**Comment by pedromassangocode** [comment]
Hi @dospringer 
I also need you to provide a minimal complete reproducible code sample, and the content of your `pubspec.yaml`.
Thanks

**Comment by dospringer** [comment]
<detail>
<summary>pubspec.yaml</summary>
version: 2.3.12+49

environment:
  sdk: ">=2.2.2 <3.0.0"
  
flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/app_icon_meisight.png"
    image_path_android: "assets/app_icon_meisight.png"
    adaptive_icon_background: "assets/app_icon_hintergrund.png"
    adaptive_icon_foreground: "assets/app_icon_symbol.png"

dependencies:
  flutter:
    sdk: flutter
 
  #User Interface Packages
  flutter_widgets: ^0.1.11
  fluttertoast: ^7.0.2
  flutter_slidable: ^0.5.5
  flutter_widget_from_html_core: ^0.4.2

  #Firebase
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1 #^0.16.1
  firebase_database: ^4.0.0 #^3.0.7
  firebase_storage: ^4.0.0 #^3.0.3
  cloud_firestore: ^0.14.0+2
  
  #Geo Packages
  google_maps_place_picker: 0.9.5
  google_maps_flutter: 0.5.30 
  search_map_place: ^0.3.0
  geocoder: ^0.2.1
  google_maps_cluster_manager: ^0.1.0
  maps_launcher: ^1.2.2
  google_places_picker: ^2.1.0+2
  geoflutterfire: ^2.2.1

  #Image Packages
  image_picker: ^0.6.7+4
  cached_network_image: ^2.2.0+1

  #Single Sign On Packages
  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0
  flutter_auth_buttons: ^0.8.0

  #AWS Packages
  aws_s3_client: ^0.1.1
  flutter_aws_s3_client: ^0.5.2

  #Sonstige
  ntp: ^1.0.7
  device_info: ^0.4.1+4
  facebook_app_events: ^0.6.0
  permission_handler: ^5.0.1 #Update verfügbar - allerdings müssen dafür große Änderungen vorgenommen werden
  validators: ^2.0.0
  package_info: ^0.4.1 #Zum auslesen der App-Version (Prüfung ob Version immernoch supportet wird)
  store_redirect: ^1.0.2 # Zum weiterleiten in die Stores

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
</detail>

**Comment by pedromassangocode** [comment]
Hi @dospringer 
Can you create a new Flutter project and add only the `google_maps_flutter` package?

This may be caused by a third-party or a first-party package and if you are able to reproduce with just first-party package please provide your `pubspec.yaml` again.
Thank you
