### ISSUE TITLE
Please stop wasting my disk with multiples Android/Java stacks - Share one Docker image between IDEs

### ISSUE THREAD

**Issue by Joca63** [flutter/flutter#66747]
Surely would be better put it inside Android SDK public repo but it doesn't exists.

For each IDE that is installed  on my machine I get another copy of Android stack, Visual Studio install one Android Stack, Android Studio install another Android Stack and so on for another ones each one with a different path. It would be wonderful if there is an official Google android SDK here on GitHub but Google keep the source locked inside they own git servers, would be great even a clone read-only here, Im thinking about put all the Android stack inside a Docker/VM image that would be shared for everyone, it can be even a shared image between Microsoft and Google , look at Eclipse Che project, there everything is a docker container.

**Comment by pedromassangocode** [comment]
Hi @Joca63 
This clearly is not an issue with Flutter and I'm not sure where this issue should be filled.

For Android or Android Studio issues you can try filling at Issue Tracker: https://developers.google.com/issue-tracker

You can also try to fill this issue into the related IDEs you think is causing this issue.
Closing this as this is not a valid Flutter issue.
Thank you
