### ISSUE TITLE
customization for text background

### ISSUE THREAD

**Issue by arjendevos** [flutter/flutter#66740]
## Use case
My goal is to make a background with text like in Instagram stories or Tiktok. I can archive this if i wrap the text in a container but this doesn't work if i have multiple lines. The container becomes a box and doesn't wrap around the text as big the line is. So i used the background property of text. This however doesn't have any customization other than color. 

## Proposal
My proposel is to make 2 new features on the TextStyle from text widget. Padding and borderradius.

Here is the result i want to archive:
[
![WhatsApp Image 2020-09-25 at 19 54 13](https://user-images.githubusercontent.com/67794681/94346340-4ddfb680-002c-11eb-9b00-f404f900d84d.jpeg)
](url)

**Comment by bdlukaa** [comment]
I actually made a package for this: https://pub.dev/packages/rounded_background_text:

![rounded_background_text showcase](https://github.com/bdlukaa/rounded_background_text/raw/main/assets/showcase.png)

**Comment by zanderso** [comment]
Thanks @bdlukaa! Thats great. I'm going to close this issue as it does not appear to require any new support from the Flutter Engine.
