### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Emred360** [flutter/flutter#66756]
![image](https://user-images.githubusercontent.com/33384064/94355113-01997400-0036-11eb-99af-709d85e77c17.png)

Please someone should help...

I've tried all I could, did not work.

**Comment by darshankawar** [comment]
@Emred360 
Please provide `flutter doctor -v`, `build.gradle` and `app/build.gradle`. Also provide `flutter run --verbose` in text format and not as screenshots.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
