### ISSUE TITLE
[Intellij Plugin] Provide a dedicated button for hot reload.

### ISSUE THREAD

**Issue by sureshg** [flutter/flutter#6675]
## Steps to Reproduce

Something similar to android studio's `instant run` , it would be nice to show a dedicated icon for flutter `hot reload` action in the main toolbar. 

<img width="236" alt="instant run" src="https://cloud.githubusercontent.com/assets/356994/19954082/0c746d92-a132-11e6-938e-b2786f1efc39.png">

**Comment by sureshg** [comment]
I was running the app in release mode. It shows on debug mode.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter-intellij/issues/407 for ideas on how to tweak the UX here.

Thanks for the feedback!
