### ISSUE TITLE
build.gradle from android

### ISSUE THREAD

**Issue by Emred360** [flutter/flutter#66757]
Hi @TahaTesser 
Can your please `build.gradle` from `android` folder and `build.gradle` from` android/app` folder 
Thank you

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/60465#issuecomment-651818967_

Please, how can I do this [ Can your please `build.gradle` from `android` folder and `build.gradle` from` android/app` folder ]

**Comment by pedromassangocode** [comment]
Hi @Emred360 
Please reply on the same issue as it is still opened.
