### ISSUE TITLE
Plugin: database

### ISSUE THREAD

**Issue by joeblew99** [flutter/flutter#6676]
this was discussed on https://gitter.im/flutter/flutter

There is a need for a Database for flutter apps, that is easy to get going with.

two options were discussed:
https://github.com/adamlofts/leveldb_dart might be interesting
it looks like it has a binary component to it as well, which might require some integration work

https://github.com/pylaligand/dart-sqlite looks similar

---

i also found https://github.com/tekartik/sembast.dart
It works with flutter now apparently.
i have not tried it yet.

**Comment by sethladd** [comment]
What kind of database are you thinking? What kind of data did you need to store?

Both platforms expose sqlite. There's also 3rd party services like Realm.

**Comment by sureshg** [comment]
@sethladd how do we access it in flutter, using platform services (https://flutter.io/platform-services/) ? It would be nice if we have one abstracted dart API to store data, without writing the boilerplate for each host platform.

**Comment by sethladd** [comment]
> It would be nice if we have one abstracted dart API to store data

True, but unfortunately there isn't One True Way to store and retrieve data. Some people want SQL. Some people want key/value. Some apps want to optimize for size on disk. Some apps want to sync to the cloud. Etc, etc.

That said, I think it's fairly common to want to store structured, queriable data locally in some sort of SQL-esque database. Both platforms have APIs for these. Perhaps that's a good place to start.

In the meantime, yes, you can use the "platform services" API.

**Comment by joeblew99** [comment]
@sethladd 

i agree that there is no one true DB :) a KV store like the one i linked is a good start.

https://flutter.io/platform-services/ allow calling out to Android java Land and IOS objc 7 Swift land, which is not what i am proposing because its not cross platform.

We can do better.
What i am proposing is a pure Dart DB (https://github.com/tekartik/sembast.dart)
Its a basic kv style store.

I currently run this on mobiles, desktop and server. Its very useful to be able to run the same queries everywhere ..

**Comment by sureshg** [comment]
@sethladd I agree. But the thing is, for any non-trivial mobile app requires some database to store it's data/config and providing a data store out of the box would be great instead of writing the host platform interfacing code in both java and obj c/swift (if you are targeting cross platform).

**Comment by joeblew99** [comment]
I will add to this. I was using golang to build mobile database using bolt DB.
It works, but the amount of plumbing you need to put in so that your GUI code can talk to the DB code is insane. 
I dont want to do it that way anymore :)

**Comment by mit-mit** [comment]
Someone in the community just published a SQLite plugin:
https://pub.dartlang.org/packages/sqflite

**Comment by ZakTaccardi** [comment]
A reactive SQLite DB in the vein of Room is an absolute necessity.

**Comment by LouisCAD** [comment]
I agree with @ZakTaccardi, a Room-like API for Flutter that work on all target platforms would be really great

**Comment by Hixie** [comment]
This is not something that's on our priority list for the next few months. It seems like a project that would be ripe for making as a separate plugin, though.

**Comment by jaumard** [comment]
A first ORM support can be found here https://github.com/Jaguar-dart/jaguar_orm, an sqflite adapter is ongoing and for now a first basic support is already working

**Comment by timsneath** [comment]
At this time, there are a number of plugins that support various types of persistent store, including [SQLite](https://flutter.dev/docs/cookbook/persistence/sqlite), [Firebase Realtime Database](https://pub.dev/packages/firebase_database) and [MongoDB](https://pub.dev/packages/mongo_dart). 

Closing this issue for now, since the parent use case is increasingly well provided for; feel free to open other issues for more specific needs that remain unaddressed with the current Google and community offerings.
