### ISSUE TITLE
 in release mode:[ERROR:flutter/shell/gpu/gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.

### ISSUE THREAD

**Issue by laorencel** [flutter/flutter#66769]
I build apk as release and install apk on phone(Huawei honor),the problem come:
E/flutter (19456): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.

I know most of people get this problem when run in debug mode, and can be fixed by edit configuration with '--enable-software-rendering',and it do work for me in debug mode too;
but more important is mine is in release mode,so I don't know how to fix it.

if you have some methods, please tell me,thanks very much!

**Comment by darshankawar** [comment]
@laorencel 
Please provide `flutter doctor -v` and a minimal code sample that shows the issue.
Thanks.

**Comment by darshankawar** [comment]
Similar to [47804](https://github.com/flutter/flutter/issues/47804) and [51447](https://github.com/flutter/flutter/issues/51447)

**Comment by Payam-Dehkordy** [comment]
I face same issue and according to #24738 I can't use --enable-software-rendering , I checked all related topics and find no solution , as I fine it also may happen on real devices , so what's the final solution !

**Comment by Payam-Dehkordy** [comment]
E/flutter (12146): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(71)] Failed to setup Skia Gr context.
D/EGL_emulation(12146): eglMakeCurrent: 0x78cfb9341ee0: ver 3 1 (tinfo 0x78cfb93be9c0)
F/libc    (12146): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 12197 (1.raster), pid 12146 (platform.whocan)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64:10/QSR1.200715.002/6695061:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2020-10-01 17:24:08+0400
pid: 12146, tid: 12197, name: 1.raster  >>> com.platform.whocan <<<
uid: 10133
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Cause: null pointer dereference
    rax 00000000fffffff9  rbx 0000000000000000  rcx 0000000000000000  rdx 000078cf6a7735c0
    r8  0000000000000000  r9  0000000000000000  r10 018cc64ac0000000  r11 0000000000000202
    r12 0000000000000000  r13 000078cf6a773608  r14 000078cf6a773478  r15 0000000000000000
    rdi 0000000000000000  rsi 0000000000000004
    rbp 0000000000000004  rsp 000078cf6a7732d8  rip 000078cf6bf8ba4c
backtrace:
      #00 pc 0000000001489a4c  /data/app/com.platform.whocan-S5H1rHrelE7I-f0XMprREA==/lib/x86_64/libflutter.so (BuildId: 8d7059558a6faf42b5a51608ea115b8c7532885b)
      #01 pc 0000000001488a65  /data/app/com.platform.whocan-S5H1rHrelE7I-f0XMprREA==/lib/x86_64/libflutter.so (BuildId: 8d7059558a6faf42b5a51608ea115b8c7532885b)
Lost connection to device.

**Comment by Payam-Dehkordy** [comment]
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.4 at C:\flutter\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\payam\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by Payam-Dehkordy** [comment]
This crash happen when I choose an image and I click on image this error crash and close the app , its ok when I work any where in my app and also when I access to device files as I clicked on image it crash .

**Comment by Payam-Dehkordy** [comment]
Future getImage(ImageSource source) async {
    if (source == ImageSource.gallery) {
      if (await Permission.accessMediaLocation.request().isGranted) {
        final pickedFile =
            await picker.getImage(source: ImageSource.gallery, maxWidth: 600.0, maxHeight: 600.0);
        if (pickedFile != null) {
          setState(() {
            image = File(pickedFile.path);
          });
        }
      }
    }
    if (source == ImageSource.camera) {
      if (await Permission.camera.request().isGranted) {
        final pickedFile = await picker.getImage(source: ImageSource.camera);
        if (pickedFile != null) {
          setState(() {
            image = File(pickedFile.path);
          });
        }
      }
    }
  }

**Comment by laorencel** [comment]
Hi,guys:
I fixed this problem, when I do this:

> 1:I upgrade my flutter sdk from v1.12.13+hotfix.5 to v1.12.13+hotfix.9;
> 2:upgrade ext.kotlin_version = '1.3.50' to ext.kotlin_version = '1.3.72' in application build.gradle;

I don't know which is correct method, but now it do not crash in my Huawei phone.(in other phones, it's ok originally, just Huawei--Honor phones--EMUI 8.x has this problem).

notice:before,I try 'getIntent().putExtra("enable-software-rendering", true)' in MainActivity,it can work,but also lead to another question :when I apply to map plugin(amap_all_fluttify),app will crash.so I also tell you this for improve your efficiency.

**Comment by darshankawar** [comment]
@laorencel 
Glad to know your issue is fixed.
I am going ahead and closing this as resolved. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by laorencel** [comment]
ok,you can close this as resolved,thanks for reply. @darshankawar
