### ISSUE TITLE
Works for me. You are Great :)

### ISSUE THREAD

**Issue by Halil-ibrahim-GUNBULAK** [flutter/flutter#66766]
Works for me.

Building apk using the below commands.

`flutter build apk --no-shrink`

or

`flutter build apk --split-per-abi --no-shrink`

_Originally posted by @musabibnusiraj in https://github.com/flutter/flutter/issues/59427#issuecomment-690003323_

**Comment by PixelToast** [comment]
The GitHub issues are for bugs and feature requests, as this does not contain either I have closed the issue.
