### ISSUE TITLE
issues on inactive InputConnection

### ISSUE THREAD

**Issue by vaishnavsree** [flutter/flutter#66768]
W/IInputConnectionWrapper(18004): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(18004): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(18004): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(18004): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(18004): endBatchEdit on inactive InputConnection

I only have TextField(controller:textpathController,), as code.
I searched everywhere, but found no solution. 
Problem occurs when i tap on textfield.

**Comment by darshankawar** [comment]
@vaishnavsree 
There's similar open issue describing your case, [9471](https://github.com/flutter/flutter/issues/9471).
Closing this as duplicate.
