### ISSUE TITLE
flutter混合编译，软键盘遮挡住编辑框

### ISSUE THREAD

**Issue by luoboo525** [flutter/flutter#66761]
1、在安卓环境下一切正常
2、在ios环境下如果不在纯原生页面弹出一次软键盘也一切正常。但是当我在原生页面弹出一次软件盘后再回到flutter页面点击编辑框的时候，软键盘会把编辑框遮盖住。这时flutter似乎不能检测到键盘弹出。因为MediaQuery.of(context).viewInsets.bottom的值始终是0。而正常时它会随着键盘弹起而变化。
3、以下是我的部分flutter代码。
`showModalBottomSheet(
      context: context,
      isScrollControlled: true, // !important
      builder: (BuildContext context) {
        return StatefulBuilder(
          // 布局外部添加一层StatefulBuilder 使setState生效
          builder: (BuildContext context, setState2) {
            writeState = setState2;
            double bottomPadding = MediaQuery.of(context).viewInsets.bottom;
            if(bottomPadding<=0 && Platform.isIOS){//经测试发现，只要在ios的原生页面弹出一次键盘，所有flutter的弹键盘的地方都会跟着出问题。暂时写死,等发现更好的解决方法后再做更新
              bottomPadding = 303.0;
            }
            return SingleChildScrollView(
              // !important
              child: Container(
                color: Colors.white,
                padding: EdgeInsets.only(bottom: bottomPadding), // !important
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Row(
                      children: <Widget>[
                        Expanded(
                            child: TextField(
                          controller: textController,
                          cursorColor: ModaColor.fontBlack,
                          cursorWidth: 1.5,
                          textInputAction: TextInputAction.send,
                          style: TextStyle(
                            color: ModaColor.fontBlack,
                            fontSize: 16.0,
                          ),
                          autofocus: true,
                          decoration: InputDecoration(
                              fillColor: Color(0xFFFFFFFF),
                              filled: true,
                              enabledBorder: OutlineInputBorder(
                                borderSide: BorderSide(color: Color(0x00FF0000)),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderSide: BorderSide(color: Color(0x00000000)),
                              ),
                              contentPadding: EdgeInsets.all(10),
                              hintText: hintText,
                              hintStyle: TextStyle(fontSize: 14)),
                          onChanged: (value) {
                            if (textController.text.length == 0) {
                              writeState(() {
                                canSend = false;
                              });
                            } else {
                              writeState(() {
                                canSend = true;
                              });
                            }
                          },
                          onSubmitted: (value) {
                            addComment();
                          },
                        )),
                        // 发送按钮
                        canSend == false
                            ? Icon(
                                Icons.send,
                                color: Colors.grey,
                              )
                            : GestureDetector(
                                child: Icon(Icons.send, color: ModaColor.theme),
                                onTap: () => addComment(),
                              ),
                        Padding(padding: EdgeInsets.only(right: 10))
                      ],
                    )
                  ],
                ),
              ),
            );
          },
        );
      },
    );`

**Comment by darshankawar** [comment]
Hi @luoboo525 
Please update the ticket in English and provide `flutter doctor -v` and a well formatted code sample that shows the issue.
Also provide the description of the issue so that we can understand the issue better.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
