### ISSUE TITLE
Upgrading pre 1.12 Android projects to results in missing platform exception for path_provider

### ISSUE THREAD

**Issue by rr0055256** [flutter/flutter#66767]
Followed the steps mentioned in the against - https://flutter.dev/go/android-project-migration

Results in missing platform exception post upgrade

**Comment by pedromassangocode** [comment]
Hi @rr0055256 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by rr0055256** [comment]
I have downgraded the version and been using it. I will re-upgrade and update the thread.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
