### ISSUE TITLE
ADB disconnects from device between build & install phases.

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#66779]
Hi, 

Recently I upgraded from 1.20.0 to 1.20.4 and I started to notice that I was getting unusual `Streamed Install` failures.
Usually when I get one of these it involves the `dynamic` keyword somewhere in my code.
However this time I noticed something weird, that wasn't related to the above.

Upon launching the app and starting the build phase, the device is recognized.
Otherwise we would get the 'no devices' message and the process aborts, as usual.
For some reason, `adb` loses connection with the device in the middle of trying to install the app.
(I checked if I didn't knock the cable out, everything was still properly attached)

I got either `device XXX not found` or `device XXX offline` from adb, besides the error message about the streamed install.

## Steps to Reproduce

- Connect a device to test with.
- Verify that it shows up as a recognized device (using `flutter devices`, or the selection menu in Android Studio for example)
- Run a flutter app using `flutter run` (The actual flutter code seems irrelevant, since it looks more like a tool/ `adb` issue. )
- Wait for the build to finish & the app to start.

**Expected results:**

The app launches correctly.

**Actual results:**

```
Launching lib\main.dart on motorola one in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install E:\Documenten\WeForza\weforza\weforza\build\app\outputs\flutter-apk\app.apk:
Uninstalling old version...
adb.exe: device offline
Application finished.
```

ADB version (just in case)
```
Android Debug Bridge version 1.0.41
Version 30.0.4-6686687
```

Doctor output: 
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale nl-BE)
    • Flutter version 1.20.4 at E:\Flutter\flutter
    • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\Android\Sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android\AndroidStudio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • motorola one (mobile) • ZL5228NFL7 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by darshankawar** [comment]
@navaronbracke,
There's similar open issue describing your case, [52887](https://github.com/flutter/flutter/issues/52887).
Closing this as duplicate.
