### ISSUE TITLE
Typos and Malformed Flutter project name in Codelabs (Building beautiful UIs with Flutter)

### ISSUE THREAD

**Issue by d-y** [flutter/flutter#66772]
The  [Building beautiful UIs with Flutter](https://codelabs.developers.google.com/codelabs/flutter) has a number of minor errors.

### In Part 3. Start a new Flutter project
It says to use ```FriendlyChat``` as the Flutter project name. This is an invalid name. It should be ```friendly_chat```.

### In Part 5. Add a UI for composing messages

```In _buildTextComposer(), wrap the Container in an IconThem:.```
should be
```In _buildTextComposer(), wrap the Container in an IconTheme:```

and

```3. Start typing Row, and select IconTheme from the list. The child property is surrounded by a red box, and the analyzer tells you that the data property is required.```
should be
```3. Start typing IconTheme, and select IconTheme from the list. The child property is surrounded by a red box, and the analyzer tells you that the data property is required.```

### In Part 7. Add a UI for displaying messages
There are six places where you can find
```ChatScreenState```
all six should be
```_ChatScreenState```

### in Part 8. Animate your app
Where it says 
```Add an animation controller to the _handleSubmitted() method:```
There is a code snippet:
```void _handleSubmitted(String text) {
  _textController.clear();
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      Duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );                                               // NEW
  setState(() {
    _messages.insert(0, message);
  });
  _focusNode.requestFocus();
  message.animationController.forward();           // NEW
}
```
it has mistakes on line 6 and 9. It should be
```void _handleSubmitted(String text) {
  _textController.clear();
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );
  setState(() {
    _messages.insert(0, message);
  });
  _focusNode.requestFocus();
  message.animationController.forward();           // NEW
}
```
There are multiple places where you can find
```ChatScreenState```
all should be
```_ChatScreenState```

**Comment by pedromassangocode** [comment]
@sfshaza2 where this should be fixed?

**Comment by chinmoy12c** [comment]
I think the source of codelabs.developers.google.com is only restricted to googlers.

**Comment by d-y** [comment]
There is another similar issue at
https://github.com/flutter/website/issues/4374

**Comment by domesticmouse** [comment]
I just migrated this codelab to a new repository, and also migrated the code to null safety. The code is at https://github.com/flutter/codelabs/tree/master/friendly_chat and the updated codelab itself is still at https://codelabs.developers.google.com/codelabs/flutter

I believe I have closed out at least some of the issues. I'm currently too close to the code, can you please update the body of the issue with the still outstanding issues please?

**Comment by domesticmouse** [comment]
Ok, I'm going to close this issue out. For remaining issues, please open new reports for each individual issue. That way we can track closing out issues as they are fixed. Thanks!
