### ISSUE TITLE
Flutter Driver scrolling occasionally gets stuck

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#66770]
Hello

**FlutterDoctor:**
Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)

**Problem**
Scrolling during UI Tests execution occasionally stucks.
Please see video evidence: https://youtu.be/3nnqnnxA9vc This is from my app [Well Spoken](https://well-spoken.app)
I cannot put these tests on CI, because whenever scrolling gets stuck, I need to manually just scroll it myself.
I don't scroll to element UI Test is trying to find, I just move it few pixels up and down and it continues to scroll to find the element.

This list is very complicated. It's created using ListView.builder, its children are of different types, each constructed with column, there are AdMob banners, there is lazy loading. In the real application, long definitions are shrunk with "read more" button, however, I disabled it during the execution of UI Tests - it improved the situation, but the issue persists.
I cannot share the real source code, however, this is a function that is scrolling.

```
Future scrollToItem(
    int index, {
    bool expectDefinition = false,
    bool expectSubscription = false,
    bool expectDailyReminder = false,
    bool expectRate = false,
    bool expectDifficulty = false,
  }) async {
    await driver.scrollUntilVisible(
      list,
      item(index),
      dyScroll: -(await driver.scrollableHeight),
    );

    await driver.waitForAbsent(loadingMore(index));

    if (expectDefinition) {
      await driver.waitFor(definition(index));
    }

    if (expectSubscription) {
      await driver.waitFor(subscription(index));
    }

    if (expectDailyReminder) {
      await driver.waitFor(dailyReminder(index));
    }

    if (expectRate) {
      await driver.waitFor(rate(index));
    }

    if (expectDifficulty) {
      await driver.waitFor(difficulty(index));
    }
  }
```

**Comment by TahaTesser** [comment]
Hi @chris-rutkowski 
Can you please provide your `flutter doctor -v` your `flutter driver -t test_driver/example.dart ` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
