### ISSUE TITLE
Not clear how to add a text label on a radio button

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#6678]
It's not clear how to add a text label next to a radio button. 

The sample app uses radio buttons with no labels:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/example_code.dart#L148

The docs have no mentioning of labels:
https://docs.flutter.io/flutter/material/Radio-class.html

On Android you simple set the `:text` property:
https://developer.android.com/guide/topics/ui/controls/radiobutton.html

**Comment by eseidelGoogle** [comment]
Feels a bit similar to https://github.com/flutter/flutter/issues/254.  We have a bunch of issues around forms which @mpcomplete is processing through for customer: leafy.  This may already be on his list via another bug, not sure.

**Comment by nelsonkam** [comment]
On flutter, you can do this:
`new Row(children: [new Radio(...), new Text("Radio Label"),])`
Also works for checkboxes.

**Comment by mit-mit** [comment]
That doesn't quite work, as pressing the text then doesn't do anything (the radio and text are supposed to be one big button in terms of selection).

**Comment by nelsonkam** [comment]
@mit-mit Yeah, I understand your point here.

**Comment by mpcomplete** [comment]
Yeah, this is #254.

**Comment by kras95** [comment]
I solved this by using a Text widget in the same row and surrounding the Text widget with a GestureHandler, which invokes the setState(){}, method, which updates the enum value for the switch.
