### ISSUE TITLE
Allow audio from other apps to continue playing

### ISSUE THREAD

**Issue by banool** [flutter/flutter#66799]
## Use case

I have a video player, using the video_player package, in my app. Whenever a video plays, even if I call `setVolume(0.0)` before initializing the player, any other audio playing on the device stops.

## Proposal

In iOS and Android there are individually ways to declare that your player or even your whole app does not use sound at all, or at least declare that mixing audio is okay. I would love for there to be a way to declare this for flutter apps.

## More
I have a StackOverflow question about this, but there haven't been many ideas: https://stackoverflow.com/questions/63984586/how-to-disable-audio-capabilities-for-entire-app.

**Comment by pedromassangocode** [comment]
Hi @banool 
Is your proposal to integrate this feature into the video_player plugin?
Can you point to some Android/iOS documentation that shows that this proposal is possible?
Thank you

**Comment by banool** [comment]
These settings make it that other audio will keep playing:

In iOS:
```
try AVAudioSession.sharedInstance().setCategory(
    AVAudioSession.Category.playback,
    mode: AVAudioSession.Mode.default,
    options: [
        AVAudioSession.CategoryOptions.ambient 
    ]
)
```
From here: https://developer.apple.com/documentation/avfoundation/avaudiosession/category.

In Android I can't find how to do it, but I can keep looking.

**Comment by recastrodiaz** [comment]
@banool Is this feature what you are looking for https://github.com/flutter/plugins/pull/2939/files#diff-6b5d92ec170999804dfe2d546ff7162ad2812754fb454d172854a21512b0be66R272 ?

**Comment by banool** [comment]
@recastrodiaz I will experiment and see if this does the trick.

**Comment by banool** [comment]
Awesome yeah that does the trick, thanks!
