### ISSUE TITLE
Failed to establish connection with the application instance in Chrome.

### ISSUE THREAD

**Issue by Jagan2412** [flutter/flutter#66806]
## Steps to Reproduce

1. Run `flutter run -d chrome`.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due to a firewall.</summary>

  D:\Projects Collections\FLUTTER\demoproject> flutter run --verbose
[ +349 ms] executing: [D:\Projects Collections\2020 New Learning\Fluter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +434 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 83dd176777cd04bd2aaca050f6bb6cb9edbf56a1
[  +36 ms] executing: [D:\Projects Collections\2020 New Learning\Fluter\flutter/] git tag --points-at HEAD
[+2403 ms] Exit code 0 from: git tag --points-at HEAD
[   +5 ms] 1.23.0-4.0.pre
[ +267 ms] executing: [D:\Projects Collections\2020 New Learning\Fluter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +114 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[   +1 ms] executing: [D:\Projects Collections\2020 New Learning\Fluter\flutter/] git ls-remote --get-url origin
[ +109 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +195 ms] executing: [D:\Projects Collections\2020 New Learning\Fluter\flutter/] git rev-parse --abbrev-ref HEAD
[ +197 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[ +339 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +54 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +149 ms] executing: C:\Users\Jagan\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +160 ms] List of devices attached
[  +51 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +217 ms] Multiple devices found:
[ +168 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[  +51 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
[ +315 ms] Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.63
[  +66 ms] [0]: Web Server (web-server)
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +3 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+10207 ms] 1
[ +523 ms] Generating D:\Projects Collections\FLUTTER\demoproject\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +216 ms] Launching lib\main.dart on Chrome in debug mode...
[ +243 ms] Updating assets
[ +437 ms] Syncing files to device Chrome...
[ +104 ms] Generating D:\Projects Collections\FLUTTER\demoproject\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[+1348 ms] <- reset
[  +20 ms] D:\Projects Collections\2020 New Learning\Fluter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\Projects Collections\2020 New
Learning\Fluter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\Projects Collections\2020 New Learning\Fluter\flutter\bin\cache\flutter_web_sdk/  
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Jagan\AppData\Local\Temp\flutter_tools.9999b28c\flutter_tool.2b8d311b\app.dill --libraries-spec
file:///D:/Projects%20Collections/2020%20New%20Learning/Fluter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation 
--filesystem-root C:\Users\Jagan\AppData\Local\Temp\flutter_tools.9999b28c\flutter_tools.dac4e322 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill    
--platform file:///D:/Projects%20Collections/2020%20New%20Learning/Fluter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +47 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+33815 ms] Syncing files to device Chrome... (completed in 35,276ms, longer than expected)
[  +14 ms] Synced 26.9MB.
[  +93 ms] <- accept
[  +20 ms] Caching compiled dill
[+7258 ms] [CHROME]:
[+2369 ms] [CHROME]:DevTools listening on ws://127.0.0.1:63504/devtools/browser/07c5c582-6e55-428e-bf36-4711a67dc5ed
[+29380 ms] "flutter run" took 87,531ms.
[  +60 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
[  +61 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:505:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:603:37)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #4      _rootRunUnary (dart:async/zone.dart:1198:47)
           #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #13     _rootRunUnary (dart:async/zone.dart:1198:47)
           #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #20     _rootRun (dart:async/zone.dart:1190:13)
           #21     _CustomZone.run (dart:async/zone.dart:1093:19)
           #22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[ +593 ms] ensureAnalyticsSent: 256ms
[   +3 ms] Running shutdown hooks
[  +18 ms] Shutdown hook priority 4
[  +14 ms] Shutdown hooks complete
[  +23 ms] exiting with code 1
PS D:\Projects Collections\FLUTTER\demoproject>

PS D:\Projects Collections\FLUTTER\demoproject> flutter analyze
Analyzing demoproject...

No issues found! (ran in 167.9s)

PS D:\Projects Collections\FLUTTER\demoproject> flutter doctor -v
[√] Flutter (Channel dev, 1.23.0-4.0.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.23.0-4.0.pre at D:\Projects Collections\2020 New Learning\Fluter\flutter
    • Framework revision 83dd176777 (6 days ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Jagan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\Jagan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.63

• No issues found!
PS D:\Projects Collections\FLUTTER\demoproject> 

</details>

**Comment by darshankawar** [comment]
@Jagan2412 
There's similar open issue describing your case, [49482](https://github.com/flutter/flutter/issues/49482).
Closing this as duplicate.
