### ISSUE TITLE
 The GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by SureshKumar311** [flutter/flutter#66809]
i am suresh kumar
i has upgrade my flutter for new version 
i am in master channel 

(PS E:\project_flutter\wind> flutter  --version
Flutter 1.22.0-10.0.pre.385 • channel master • https://github.com/flutter/flutter.git
Framework • revision 73b6398932 (6 hours ago) • 2020-09-28 11:07:32 +0800
Engine • revision 3a73d073c8
Tools • Dart 2.11.0 (build 2.11.0-161.0.dev)

i am trying to  run and build windows application but i  has commited  to error 
when use run 👍 
PS E:\project_flutter\wind> flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
EGL: Failed to initialize EGL
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Windows. 

the application is created but not working  
  flutter doctor has no issues

**Comment by darshankawar** [comment]
@SureshKumar311 
There's a similar open issue describing your case, [51286](https://github.com/flutter/flutter/issues/51286)
Please follow-up there for updates.
Closing this as duplicate.
