### ISSUE TITLE
Create static widget comparison tool for Cupertino

### ISSUE THREAD

**Issue by xster** [flutter/flutter#66804]
Related to https://github.com/flutter/flutter/issues/22862. 

Create a simple UIKit/SwiftUI program that embeds Flutter and has translucent UI that allows for easy overlay and side-by-side comparison of native UI components and Flutter's Cupertino widgets.

Add to https://github.com/flutter/platform_tests

**Comment by DanielEdrisian** [comment]
Started off with https://github.com/DanielEdrisian/FlutterSwiftUIOverlay

**Comment by DanielEdrisian** [comment]
Closing with https://github.com/flutter/platform_tests/pull/3
