### ISSUE TITLE
Invalid website search result

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#6681]
Not sure if this is in Flutter's domain or if it's a Google Search issue, but just in case...

I was looking for documentation on the DropDownMenuItem class, so I searched flutter.io:

<img width="809" alt="screen shot 2016-11-03 at 9 28 06 am" src="https://cloud.githubusercontent.com/assets/15093990/19975325/c7bc94aa-a1a8-11e6-9e07-f93e79fc63ee.png">

Clicking on the first result gave me this error screen:

<img width="702" alt="screen shot 2016-11-03 at 9 28 32 am" src="https://cloud.githubusercontent.com/assets/15093990/19975379/ee0dcb4c-a1a8-11e6-89dd-64641222be36.png">

Looks like the first page was trying to take me to https://docs.flutter.io/flutter/material/DropDownMenuItem/DropDownMenuItem.html
but the page I was looking for was actually at https://docs.flutter.io/flutter/material/DropdownMenuItem-class.html

I searched through a few more pages in the search results, and did not find the second link.

**Comment by sethladd** [comment]
Hm, that looks like a Google Custom Search Engine issue. Hopefully this will resolve itself soon :(

**Comment by sethladd** [comment]
Thanks for reporting this. Definitely keep the feedback coming. I'm going to close because I think this will resolve itself.
