### ISSUE TITLE
Codelab has malformed comment in sample code

### ISSUE THREAD

**Issue by d-y** [flutter/flutter#66817]
At this Codelab: [Building beautiful UIs with Flutter. 4. Build the main user interface](https://codelabs.developers.google.com/codelabs/flutter/#3), the first section has a link to sample code:

[Try the finished app on DartPad!](https://dartpad.dev/99243efc05f92cd541af5e279c012050)

The first line in the sample code has a malformed comment:

```/ Copyright 2017, 2020 The Flutter team. All rights reserved.```

should be 

```//Copyright 2017, 2020 The Flutter team. All rights reserved.```

**Comment by pedromassangocode** [comment]
Hi @d-y 
Ii is fine for me as you can see in the image bellow.

![gif](https://user-images.githubusercontent.com/67424416/94425038-23544180-0183-11eb-8e9d-95b202ea6679.gif)

Can you confirm that it is working as expected now?
Thank you

**Comment by d-y** [comment]
Hi @pedromassangocode 
When I open a new tab in Chrome, in incognito mode it works.
When I try it again in a new tab in Chrome, but NOT in incognito mode, I get the malformed comment.

I suspect the bad code is somehow tied to my browser session, or might be related to caching. I think I accidentally modified the code myself, but I'm surprised that I still see the changes.

In any case the code on your side is working as expected. Sorry for the trouble.

Could you tell me the name of the program you used to create that gif?

**Comment by pedromassangocode** [comment]
> Could you tell me the name of the program you used to create that gif?

I used KAP!

**Comment by pedromassangocode** [comment]
Yes, this is probably your browser caching the URL content.
