### ISSUE TITLE
[google_maps_flutter] Unhandled PlatformException when a screen with GoogleMaps widget closes.

### ISSUE THREAD

**Issue by kabazyba** [flutter/flutter#66812]
I have the same exception in my application and in your example.

<details><summary>Logs</summary>

```
E/MethodChannel#flutter/platform_views(20006): Failed to handle method call
E/MethodChannel#flutter/platform_views(20006): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map
E/MethodChannel#flutter/platform_views(20006): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:113)
E/MethodChannel#flutter/platform_views(20006): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:62)
E/MethodChannel#flutter/platform_views(20006): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter/platform_views(20006): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(20006): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:681)
E/MethodChannel#flutter/platform_views(20006): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(20006): 	at android.os.MessageQueue.next(MessageQueue.java:329)
E/MethodChannel#flutter/platform_views(20006): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter/platform_views(20006): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/MethodChannel#flutter/platform_views(20006): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(20006): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/MethodChannel#flutter/platform_views(20006): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
E/flutter (20006): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.util.Map, null)
E/flutter (20006): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (20006): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (20006): <asynchronous suspension>
E/flutter (20006): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (20006): #3      AndroidViewController.dispose (package:flutter/src/services/platform_views.dart:534:43)
E/flutter (20006): #4      _AndroidViewState.dispose (package:flutter/src/widgets/platform_view.dart:494:17)
E/flutter (20006): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
E/flutter (20006): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
E/flutter (20006): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #8      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
E/flutter (20006): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (20006): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (20006): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
E/flutter (20006): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (20006): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (20006): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (20006): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #29     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
E/flutter (20006): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (20006): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
E/flutter (20006): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
E/flutter (20006): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
E/flutter (20006): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
E/flutter (20006): #39     _InactiveElements._unmount (package:flutter/src/
```
</details>

**Comment by pedromassangocode** [comment]
Hi @kabazyba 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by kabazyba** [comment]
[✓] Flutter (Channel master, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /home/........../development/flutter
    • Framework revision 0bffc8a391 (3 months ago), 2020-07-01 07:08:02 -0400
    • Engine revision 712f619737
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/........../Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/........../Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by kabazyba** [comment]
[  +86 ms] W/ResourceType(11168): No package identifier when getting name for resource number 0x00000000
[  +10 ms] I/Google Maps Android API(11168): Google Play services package version: 203315021
[ +178 ms] W/ResourceType(11168): No package identifier when getting name for resource number 0x00000000
[ +395 ms] W/art     (11168): Suspending all threads took: 7.238ms
[   +8 ms] E/MethodChannel#flutter/platform_views(11168): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views(11168): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map
[        ] E/MethodChannel#flutter/platform_views(11168):       at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:113)
[        ] E/MethodChannel#flutter/platform_views(11168):       at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:62)
[        ] E/MethodChannel#flutter/platform_views(11168):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
[        ] E/MethodChannel#flutter/platform_views(11168):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/MethodChannel#flutter/platform_views(11168):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:681)
[        ] E/MethodChannel#flutter/platform_views(11168):       at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter/platform_views(11168):       at android.os.MessageQueue.next(MessageQueue.java:329)
[        ] E/MethodChannel#flutter/platform_views(11168):       at android.os.Looper.loop(Looper.java:142)
[        ] E/MethodChannel#flutter/platform_views(11168):       at android.app.ActivityThread.main(ActivityThread.java:6375)
[        ] E/MethodChannel#flutter/platform_views(11168):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter/platform_views(11168):       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
[        ] E/MethodChannel#flutter/platform_views(11168):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
[   +2 ms] I/flutter (11168): contoller dispose
[  +11 ms] I/art     (11168): Background sticky concurrent mark sweep GC freed 82702(3MB) AllocSpace objects, 34(2MB) LOS objects, 2% free, 31MB/32MB, paused 11.258ms total 94.154ms
[  +64 ms] E/flutter (11168): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.util.Map, null)
[        ] E/flutter (11168): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
[        ] E/flutter (11168): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
[        ] E/flutter (11168): <asynchronous suspension>
[        ] E/flutter (11168): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
[        ] E/flutter (11168): #3      AndroidViewController.dispose (package:flutter/src/services/platform_views.dart:534:43)
[        ] E/flutter (11168): #4      _AndroidViewState.dispose (package:flutter/src/widgets/platform_view.dart:494:17)
[        ] E/flutter (11168): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
[        ] E/flutter (11168): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
[        ] E/flutter (11168): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #11     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
[        ] E/flutter (11168): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
[        ] E/flutter (11168): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
[        ] E/flutter (11168): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[  +35 ms] E/flutter (11168): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #32     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
[        ] E/flutter (11168): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
[        ] E/flutter (11168): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
[        ] E/flutter (11168): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
[        ] E/flutter (11168): #40     _InactiveElemen

**Comment by kabazyba** [comment]
> and a minimal complete reproducible code sample?

Sorry, I can't, but I have the same issue with the google_maps_flutter example.

**Comment by pedromassangocode** [comment]
Hi @kabazyba 
Please provide the complete output of your `flutter run --verbose`, if it is too long you can attach it here as a `.txt` file. Also please provide the steps to reproduce.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kabazyba** [comment]
After Flutter update, the problem resolved itself.
