### ISSUE TITLE
Handle ActivityNotFoundException in the url_launcher plugin

### ISSUE THREAD

**Issue by jeroen1602** [flutter/flutter#66826]
## Use case

According to the [Android documentation](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-urls-browser-or-other-app) there is a chance for a call to `startActivity()` can throw a `ActivityNotFoundException`.

Currently the `launch` function doesn't handle this exception.

## Proposal

My proposal is to add an extra `LaunchStatus` to the Android `launch` function that is returned if the `ActivityNotFoundException` exception occurs.

Using this the new state can be handled in the `onLaunch` handler and a new error state can be returned.

Using `ftp://localhost` should cause the exception in an emulator.

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/41019

**Comment by mvanbeusekom** [comment]
Closing this issue as this is fixed in url_launcher 5.7.8 (as per PR flutter/plugins#3125)
