### ISSUE TITLE
Engine -> FW Roll failures due to FlutterUITests failures

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#66829]
The rolls have been failing for ~3 days. Investigating the probable cause. e.g, https://github.com/flutter/flutter/pull/66671

https://github.com/flutter/engine/pull/21355 could the potential culprit.

Logs [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867913046316999344/+/steps/run_module_test_ios/0/stdout).

```
[module_test_ios] [STDOUT] stderr: Failing tests:
[module_test_ios] [STDOUT] stderr: 	FlutterUITests:
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testDualCold]
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testFullScreenColdPop]
[module_test_ios] [STDOUT] stderr: 
[module_test_ios] [STDOUT] stderr: ** TEST FAILED **
```

cc: @zanderso , @dnfield

**Comment by dnfield** [comment]
I mentioned in chat - based on looking at roll attempts, this seems like the most likely candidate (the module ios test was succeeding on my DPR PR, and failing after this one which contained a couple other seemingly unrelated PRs).

I couldn't get the test running properly locally (was getting build failures), but @jmagman might know how to do that better.

**Comment by iskakaushik** [comment]
I created a revert at https://github.com/flutter/engine/pull/21456. I wasn't able to get the tests to run with local engine. Agreed that this seems to be the most likely candidate.

**Comment by jmagman** [comment]
"Host crashed in <external symbol>" isn't very helpful...

```
[module_test_ios] [STDOUT] stdout: Test Case '-[FlutterUITests testFullScreenColdPop]' started.
[module_test_ios] [STDOUT] stdout:     t =     0.00s Start Test at 2020-09-28 05:35:22.964
[module_test_ios] [STDOUT] stdout:     t =     0.02s Set Up
[module_test_ios] [STDOUT] stdout:     t =     0.02s Open io.flutter.add2app.Host
[module_test_ios] [STDOUT] stdout:     t =     0.03s     Launch io.flutter.add2app.Host
[module_test_ios] [STDOUT] stdout:     t =     0.03s         Terminate io.flutter.add2app.Host:13568
[module_test_ios] [STDOUT] stdout:     t =     0.16s             Assertion Failure: <unknown>:0: Host crashed in <external symbol>
[module_test_ios] [STDOUT] stdout:     t =     0.17s Tear Down
```

**Comment by dnfield** [comment]
Nope, but these are regular XCUITests and I suspect that's what the framework is giving us.

**Comment by iskakaushik** [comment]
I was able to get a better stack-trace for this

```
* thread #28, name = 'io.flutter.3.ui', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000019c94b5ec libobjc.A.dylib`objc_msgSend + 44
    frame #1: 0x000000010279a334 Flutter`-[VSyncClient dealloc] + 32
    frame #2: 0x000000010279a084 Flutter`flutter::VsyncWaiterIOS::~VsyncWaiterIOS() + 52
    frame #3: 0x000000010279a038 Flutter`flutter::VsyncWaiterIOS::~VsyncWaiterIOS() + 12
    frame #4: 0x0000000102a6d140 Flutter`flutter::Animator::~Animator() + 412
    frame #5: 0x0000000102a7037c Flutter`flutter::Engine::~Engine() + 580
    frame #6: 0x0000000102a6ff7c Flutter`flutter::Engine::~Engine() + 12
```

Cause is definitely my PR.

**Comment by zanderso** [comment]
Engine -> Framework roll to monitor is here: https://github.com/flutter/flutter/pull/66840

**Comment by jmagman** [comment]
> Nope, but these are regular XCUITests and I suspect that's what the framework is giving us.

Oh for sure, nothing we can do about it (AFAIK), I was just complaining.
