### ISSUE TITLE
Flutter Web: Cannot compile flutter engine for Flutter Web

### ISSUE THREAD

**Issue by Auties00** [flutter/flutter#66830]
Hello, I'm trying to clone and compile the flutter engine to make some modifications to the web part.

I've followed [this](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) guide provided by the flutter team to set up my development environment, I tried both on Windows and Linux just to be sure this wasn't a Windows-only issue

Then, without changing anything from the source, I tried to compile the engine for the web to verify that everything was working as expected. I followed the instructions provided [here] by the flutter team(https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web)

But while running felt build I got lots of errors:
https://pastebin.com/5Gxn9Ei4
These errors are obviously being thrown because the dart compiler doesn't recognize the analysis-options.yaml file that should enable those preview features. Is this a widespread issue or am I doing something wrong?

**Comment by TahaTesser** [comment]
Hi @Auties00 
I just tried to reproduce the issue following docs and there are no errors when executing `felt build --watch` or `felt build`
```
taha@pop-os:~/Desktop/engine$ felt build 
Running gn...
Generating GN files in: out/host_debug_unopt
Done. Made 687 targets from 226 files in 294ms
Running autoninja...
ninja: Entering directory `/home/taha/Desktop/engine/src/out/host_debug_unopt'
ninja: no work to do.
taha@pop-os:~/Desktop/engine$ 
```

App also runs with no issues when attaching the local web engine 

<details> 
<summary>logs</summary> 

```bash
taha@pop-os:~/AndroidStudioProjects/master_flutter$ flutter run --local-engine=/home/taha/Desktop/engine/src/out/host_debug_unopt  -d chrome
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
 9,203ms (!)                                       
Debug service listening on ws://127.0.0.1:37047/JXri1dRvCTU=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.406, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.406 at /home/taha/Code/flutter_master
    • Framework revision 5872b70b8c (3 hours ago), 2020-09-29 05:47:04 -0400
    • Engine revision 1c462e28a2
    • Dart version 2.11.0 (build 2.11.0-176.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

```

</details> 

Note: I didn't edit any engine files or made any modifications so whatever the changes you've made probably causes the issue

Can you please try again with a fresh setup without modifications which reproduces this issue if it is a bug 
Thank you

**Comment by Auties00** [comment]
> Hi @Auties00
> I just tried to reproduce the issue following docs and there are no errors when executing `felt build --watch` or `felt build`
> 
> ```
> taha@pop-os:~/Desktop/engine$ felt build 
> Running gn...
> Generating GN files in: out/host_debug_unopt
> Done. Made 687 targets from 226 files in 294ms
> Running autoninja...
> ninja: Entering directory `/home/taha/Desktop/engine/src/out/host_debug_unopt'
> ninja: no work to do.
> taha@pop-os:~/Desktop/engine$ 
> ```
> 
> App also runs with no issues when attaching the local web engine
> 
> logs
> flutter doctor -v
> Note: I didn't edit any engine files or made any modifications so whatever the changes you've made probably causes the issue
> 
> Can you please try again with a fresh setup without modifications which reproduces this issue if it is a bug
> Thank you

That's probably because you're on Linux, I tried many times and it always worked on there. I've tried to reproduce the procedure and it turns out that felt build works perfectly on Git Bash while throwing all of those errors for the Windows' command prompt

**Comment by TahaTesser** [comment]
Hi @Auties00 
You said ", I tried both on Windows and Linux just to be sure this wasn't a Windows-only issue", which implies this is not windows only issue & you didn't mention it works for you on Linux  

Nevertheless, you are `felt build`, which is not used windows to compile engine web, you need to follow the steps below https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web-on-windows

I tried https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web-on-windows  and the engine is built web app is running on Windows 

`flutter run --local-engine=C:\Code\engine\src\out\host_debug_unopt -d chrome`
![image](https://user-images.githubusercontent.com/48603081/94680996-4d9f2e00-0340-11eb-8abb-7c8a8ae43384.png)

Closing, as this isn't an issue with Flutter or docs itself. If you disagree, please write in the comments and I will reopen it.
Thank you
