### ISSUE TITLE
overrides a deprecated API.

### ISSUE THREAD

**Issue by erwinagpasa** [flutter/flutter#66838]
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/erwin/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.2/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.

**Comment by Abhishek01039** [comment]
Hi @erwinagpasa 
This is just a warning that this package uses java and many things are deprecated in that plugin so you can ignore it.
This warning is not affecting your app performance or app size.
Thanks

**Comment by erwinagpasa** [comment]
great thank you for the response

**Comment by Abhishek01039** [comment]
Hi @erwinagpasa, I guess you have got the answer.
you can close this issue now.
Thanks

**Comment by erwinagpasa** [comment]
Hi @Abhishek01039 

Yep thank you
