### ISSUE TITLE
[devicelab] linux-7 cannot find attached device

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#66850]
The linux-7 test bed cannot find the attached android device, I have tried rebooting the host.
```
flutter@flutter-devicelab-linux-7:~$ adb devices -l
List of devices attached
```

**Comment by godofredoc** [comment]
the problem is that machine has two versions of adb. One installed in the root system and the other one installed in flutter home directory. The adb server was using the adb from system which was incompatible with the one in home.

Killing the adb server fixed the problem

**Comment by digiter** [comment]
Thanks for the fix!
