### ISSUE TITLE
Drawer causing first DropdownButton 'DropdownMenuItem list' to hit 'SafeArea' inconsistently

### ISSUE THREAD

**Issue by billbarni** [flutter/flutter#66856]
## Steps to Reproduce

1. Create a simple App with the following Drawer:

```
Drawer(
  child: Column(
    children: <Widget>[
      Container(	
        // padding: EdgeInsets.only(top: 56),
        child: DropdownButtonHideUnderline(
          child: ButtonTheme(
            alignedDropdown: true,
            child: DropdownButton<String>(
              value: 'Company 1',
              onChanged: (String newValue) {
                // TODO change company
              },
              items: <String>['Company 1', 'Company 2', 'Company 3', 'Company 4'].map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    ],
  ),
),
```

2. Insert a DropdownButton aligned to the top of the Drawer
3. Run the app
4. When you click the DropdownButton, the dropdown menu is misaligned as if the 'top' is being pushed down.

**Expected results:**
When clicking the DropdownButton, the list should be aligned to the button itself when at least enough padding is given for the 'Button list' to grow it's forehead.

**Actual results:**
'DropdownMenuItem list' from the DropdownButton always gets pushed down incorrectly as if it is hitting the "SafeArea" of the screen. It is as if the 'shadow' of one of the components, or the 'DropdownMenuItem list' itself is being pushed down by something and misaligning.

[Image pointing the 'forehead' of the 'DropdownMenuItem list' that is being pushed down.](https://i.stack.imgur.com/zvmc1.png)

[Image illustrating the ammount of padding that is required just for the menu to open 'aligned' to the button.](https://i.stack.imgur.com/JcqwJ.png)

Workaround to see the effects of the 'ghost' SafeArea that DropdownButton requires to be aligned to the opening content:

5. Uncomment 'padding' attribute from the Container:
 ```
    ...     
    Container(
        padding: EdgeInsets.only(top: 56),
        child: DropdownButtonHideUnderline(
    ...

```

6. Observe that the 'dropdown menu' from the Button now opens correctly, but requires A LOT more padding to the top than expected. I was expecting having to add 20 pixels. 56 is too much and breaks the design objective.

So... how can I make the 'dropdown menu' to ignore the 'safe area'?

https://stackoverflow.com/questions/64107746/drawer-causing-first-dropdownbutton-child-to-inhert-top-padding-margin-in-its-d

`flutter doctor -v` :

> [√] Flutter (Channel master, 1.22.0-10.0.pre.396, on Microsoft Windows [versÃ£o 10.0.17763.1457], locale pt-BR)
>     • Flutter version 1.22.0-10.0.pre.396 at C:\flutter
>     • Framework revision 549de844ed (22 hours ago), 2020-09-28 13:04:38 -0700
>     • Engine revision 67b1219d83
>     • Dart version 2.11.0 (build 2.11.0-173.0.dev)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\Administrador\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 49.0.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2019.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
>     • Flutter plugin version 45.0.1
>     • Dart plugin version 192.7761
> 
> [√] VS Code, 64-bit edition (version 1.48.2)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.14.1
> 
> [√] Connected device (2 available)
>     • Web Server (web) • web-server • web-javascript • Flutter Tools
>     • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
> 
> • No issues found!
>

**Comment by darshankawar** [comment]
@billbarni 
Please provide `flutter doctor -v`.
Thanks

**Comment by billbarni** [comment]
> 
> 
> @billbarni
> Please provide `flutter doctor -v`.
> Thanks

`flutter doctor -v` added.

**Comment by darshankawar** [comment]
@billbarni 
If you wrap `Scaffold` with `SafeArea`, then you'll see the dropdownmenu opening properly without cutting off the taskbar.

![66856](https://user-images.githubusercontent.com/67046386/94648174-97bbeb80-030f-11eb-9b9f-2a32f8eea272.png)

```
return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
          ),
          drawer: Drawer(
            child: Column(
              children: <Widget>[
                Container(
                //  padding: EdgeInsets.only(top: 56),
                  child: DropdownButtonHideUnderline(
```

Also, please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by billbarni** [comment]
The dropdown is misaligned. It does not open over the Dropdown button, it is pushed many pixels down when it opens, and if you push the Button iself down to allow the Dropdown menu to show using padding, it does not work either.
