### ISSUE TITLE
Dropdown Button has weird offset if the navigator it uses does not cover the full screen

### ISSUE THREAD

**Issue by RosilBelli** [flutter/flutter#66870]
When I started my first flutter web business application my goal was to place the MaterialApp navigator just inside the place where I want all pages to be loaded. Therefore I used the MaterialApp builder to accomplish that. This builder gives me the context and navigator and I can return the widget tree I desire.

Everything was great, I created and returned a widget tree that looked like the code below:
```
Scaffold(
  appBar: MyAppBar(),
  body: Row(children: [
    MySideBar(),
    Expanded(
      child: navigatorFromTheMaterialAppBuider,
    ),
  ]),
)
```

By doing this way I have a fixed sidebar and appbar, and all pages are loaded without any rebuild on the fixed part.

The problem began when I needed to place some widgets that depend on the Overlay class inside my sidebar. Because sidebar is outside the MaterialApp navigator an overlay can't be found. Another side effect of doing this kind of layout was that any widget placed inside my pages and therefore inside the navigator displayed its overlay entries with the exact offset of the sidebar width and appbar height.

To avoid change that layout structure and make appbar and sidebar part of every page of my web application, I'd like to know if there is a way of placing an Overlay above the navigator (or even above the MaterialApp widget) that can be used instead of the MaterialApp navigator overlay for the entire tree of widgets.

## Steps to Reproduce
I created a dartpad sample code to make it clearer. https://dartpad.dev/140e1e8a9ca0620301b43d0313e20bdb

<details>
 <summary>Flutter Doctor</summary>
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.49.2)
[√] Connected device (3 available)
</details>

**Comment by darshankawar** [comment]
Hi @RosilBelli 
Can you elaborate more on the issue you are facing and what should be the expected layout ? I replicated your code and saw below exception after tapping on `sidebar`:

```
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a
descendant of a Navigator widget.
```

**Comment by RosilBelli** [comment]
Hi @darshankawar 

This assertion happens because there is no Navigator on the sidebar and therefore there is no way to get the overlay where the dropdown items are shown. This is what happens with any widget that is outside the navigator and needs to use the Overlay.

The other dropdown button that is inside the navigator, where pages will be loaded through normal routing, you can observe that the dropdown is opened with an offset (x,y) that is exactly the width of the sidebar (for the x) and the height of the appbar (for the y). This occurs because the navigator is not covering the entire screen and therefore the mapping to global coordinates does not consider that.

The expected result, if the Overlay was something outside the navigator, was to be able to have any kind of widget working properly on the sidebar and no offset on the overlayentries of widgets that are under a navigator that is occupying just a portion of the screen as on the proposed layout, very common on web applications.

I tried to create an outer Overlay above my entire tree, but it is not reachable by any widget that requires an overlay, I don't know why but even the sidebar dropdown couldn't find it.

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.

**Comment by RosilBelli** [comment]
I couldn't dig it very deeply but in my opinion, it can be solved just by moving the Overlay up to the MaterialApp widget as its stack is intended to cover the entire screen and be the topmost area that widgets can rely on to display floating UI.

**Comment by slecoustre** [comment]
I have the same problem on the mobile platform

**Comment by RosilBelli** [comment]
Hi! Is there any estimated time for this issue?

**Comment by chunhtai** [comment]
moving the overlay does not really solve the problem, the sidebar needs a navigator parent. Since you want to build a side bar above the MaterialApp's navigator, you will need to create another navigator above that. so the correct fix will be wrapping the scaffold within another navigator. See the below example. Closeing as WAI

<details>

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      builder: (_, nav) =>Navigator(
       onGenerateRoute: (RouteSettings s) {
         return MaterialPageRoute(builder: (_)=> Scaffold(
           appBar: AppBar(
             title: Text('Global App Bar'),
           ),
           body: Row(
             mainAxisSize: MainAxisSize.max,
             children: [
               Container(
                 color: Colors.grey,
                 width: 300,
                 child: Column(
                   children: [
                     Container(
                       padding: EdgeInsets.all(20.0),
                       child: DropdownButton(
                         value: 1,
                         items: [
                           DropdownMenuItem(
                             child: Text("First Item"),
                             value: 1,
                           ),
                           DropdownMenuItem(
                             child: Text("Second Item"),
                             value: 2,
                           ),
                           DropdownMenuItem(child: Text("Third Item"), value: 3),
                           DropdownMenuItem(child: Text("Fourth Item"), value: 4)
                         ],
                         onChanged: (value) => print(value),
                       ),
                     ),
                   ],
                 ),
               ),
               Expanded(
                 child: nav,
               ),
             ],
           ),
         ));
       },
      ),
      initialRoute: '/',
      routes: {
        // When navigating to the "/" route, build the FirstScreen widget.
        '/': (context) => MyWidget(),
        // When navigating to the "/second" route, build the SecondScreen widget.
        //'/second': (context) => SecondScreen(),
      },
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text('Hello, World!', style: Theme.of(context).textTheme.headline4),
        Container(
          padding: EdgeInsets.all(20.0),
          child: DropdownButton(
            value: 1,
            items: [
              DropdownMenuItem(
                child: Text("First Item"),
                value: 1,
              ),
              DropdownMenuItem(
                child: Text("Second Item"),
                value: 2,
              ),
              DropdownMenuItem(child: Text("Third Item"), value: 3),
              DropdownMenuItem(child: Text("Fourth Item"), value: 4)
            ],
            onChanged: (value) => print(value),
          ),
        ),
      ],
    );
  }
}
```

</details>

**Comment by RosilBelli** [comment]
Hi @chunhtai 
This approach just solves the problem of navigator not present for the widget placed on the sidebar (outside nav).
All widgets that are **inside nav** still have that offset because nav is not fulfilling the entire screen.
I think that in the case that now we can have multiple navigators, widgets should use the overlay from the first one in the tree.

[Offset Issue](https://github.com/RosilBelli/files/blob/main/overlay-offset.png)

**Comment by chunhtai** [comment]
the inner sidebar does uses the nearest navigator, the fact that it has a weird offset sounds like a bug in the DropDownMenuButton, i will update this issue to track the offset problem.

**Comment by RosilBelli** [comment]
This happens not only with the dropdown button but with any widget that uses overlay, because they get, by default, the nearest navigator's overlay, and if it is not a fullscreen navigator, the offset is present.

**Comment by chunhtai** [comment]
repro:

<details>

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        // When navigating to the "/" route, build the FirstScreen widget.
        '/': (context) => MyWidget(),
        // When navigating to the "/second" route, build the SecondScreen widget.
        //'/second': (context) => SecondScreen(),
      },
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
        Container(
          height: 200,
          child:Text('Hello, World!', style: Theme.of(context).textTheme.headline4)),
        ConstrainedBox(
          constraints: BoxConstraints(maxWidth: 500, maxHeight: 200),
          child: Navigator(
            onGenerateRoute: (_) {
              return MaterialPageRoute(builder: (_) {
                return Scaffold(
                  body: Container(
                    child: DropdownButton(
                      value: 1,
                      items: [
                        DropdownMenuItem(
                          child: Text("First Item"),
                          value: 1,
                        ),
                        DropdownMenuItem(
                          child: Text("Second Item"),
                          value: 2,
                        ),
                        DropdownMenuItem(child: Text("Third Item"), value: 3),
                        DropdownMenuItem(child: Text("Fourth Item"), value: 4)
                      ],
                      onChanged: (value) => print(value),
                    ),
                  ),
                );
              });
            },
          ),
        ),
        Container(
          child: DropdownButton(
            value: 1,
            items: [
              DropdownMenuItem(
                child: Text("First Item"),
                value: 1,
              ),
              DropdownMenuItem(
                child: Text("Second Item"),
                value: 2,
              ),
              DropdownMenuItem(child: Text("Third Item"), value: 3),
              DropdownMenuItem(child: Text("Fourth Item"), value: 4)
            ],
            onChanged: (value) => print(value),
          ),
        ),
        ],
      ),
    );
  }
}
```

</details>

**Comment by chunhtai** [comment]
@RosilBelli Do you have other example that uses overlay alone?

**Comment by chunhtai** [comment]
so the issue with the dropdown button is that we always uses the global offset of the button to position the dropdown menu. However,  if the overlay does not covering the full screen, the position will be off. This can be fixed by using the button offset related to the nearest overlay to position the dropdown menu. I am not sure if our current API support local to nearest overlay transform, will keep digging.

**Comment by RosilBelli** [comment]
No, I don't have a sample code using overlay anymore, but I assure you that the same thing happens.
The problem is exactly with the position conversion. It assumes that the navigator/overlay will be always fullscreen. That's why the more logical approach for me was to stripe overlay out from Navigator and make it a declarative widget or at least put it on MateriaApp. 
To maintain compatibility with widgets that already get overlay from the Navigator, Navigator should then get it transparently from above (MaterialApp or the OverlayWidget) if any. 

I really don't understand why it should depend on the Navigator as it is just a stack that should really be always fullscreen. Also because its activation method is imperative (and does not depend on any navigator method to add entries to the overlay).

**Comment by chunhtai** [comment]
If there are other widgets that has the same issue, we need to fix them 1 by 1 because it is bug for the overlay entry to calculate its position based on global offset.

**Comment by RosilBelli** [comment]
As far as I could realize, widgets that use the overlay to display floating widgets that base their position related to its "parent" widget make a call to RenderBox.localToGlobal method to convert its coordinates to the global (overlay) equivalent position. 
Maybe this method can take care of this offset when the nearest navigator is not fullscreen.

You can see this exact call on dropdownbutton._handleTap method.

**Comment by RosilBelli** [comment]
The problem with an overlay that is not fullscreen just because its navigator is not, goes beyond this offset issue.
Suppose that localToGlobal is replaced on all widgets to localToNearestNavigator, it will make impossible to any widget to show something floating aligned to the entire screen. Also it will be impossible to show something floating outside the nearest 
navigator boundaries. 

That's why I insist to consider a way to guarantee that Overlay is really something that will always be full screen regardless of its navigator size, instead of changing how coordinates are converted, because it will not solve all issues around this topic.

**Comment by chunhtai** [comment]
if you want to float outside of the nearest navigator boundaries, you need to push the route/overlay to the root navigator which cover the full screen.

In your example, the navigator MaterialApp created does not cover the full screen because you wrapped it with a scaffold. In this case, you will be responsible for creating the outer navigator if the static content need to push route/overlay to parent navigator.

**Comment by chunhtai** [comment]
> As far as I could realize, widgets that use the overlay to display floating widgets that base their position related to its "parent" widget make a call to RenderBox.localToGlobal method to convert its coordinates to the global (overlay) equivalent position.
> Maybe this method can take care of this offset when the nearest navigator is not fullscreen.
> 
> You can see this exact call on dropdownbutton._handleTap method.

Yes, I have a fix for it in the PR

**Comment by RosilBelli** [comment]
> if you want to float outside of the nearest navigator boundaries, you need to push the route/overlay to the root navigator which cover the full screen.
> 
> In your example, the navigator MaterialApp created does not cover the full screen because you wrapped it with a scaffold. In this case, you will be responsible for creating the outer navigator if the static content need to push route/overlay to parent navigator.

By the way, how am I supposed to handle web deep links when using more than one Navigator as on this sample code?
I could not find examples in the community for this kind of scenario.
