### ISSUE TITLE
[video player] Aspect ratio does not work correctly for iOS 14

### ISSUE THREAD

**Issue by thang510023** [flutter/flutter#66878]
I was having a problem in iOS 14, only the vertical video uploaded from the gallery was not working properly with its aspect ratio. Nice to have the help of the flutter developer.
Here is the example code to reproduce the error:

import 'package: flutter / material.dart';
import 'package: video_player / video_player.dart';

void main () => runApp (VideoApp ());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState () => _VideoAppState ();
}

class _VideoAppState extends State <VideoApp> {
  VideoPlayerController _controller;

  static const BASE_API = "http://gc.vietprojectgroup.com/storage/ripples/";

  @override
  void initState () {
    super.initState ();
    String uploadFromLibraryIOS = "u2d1IAA2MqPXzkLxDz45c93gFypKUSYPOx1Yu85z.qt";
    _controller = VideoPlayerController.network (BASE_API + uploadFromLibraryIOS)
      ..initialize (). then ((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        print ("AspectRatio: $ {_ controller.value.aspectRatio}");
        setState (() {});
      });
  }

  @override
  Widget build (BuildContext context) {
    return MaterialApp (
      title: 'Video Demo',
      home: Scaffold (
        body: Center (
          child: _controller.value.initialized
              ? AspectRatio (
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer (_controller),
                )
              : Container (),
        ),
        floatingActionButton: FloatingActionButton (
          onPressed: () {
            setState (() {
              _controller.value.isPlaying
                  ? _controller.pause ()
                  : _controller.play ();
            });
          },
          child: Icon (
            _controller.value.isPlaying? Icons.pause: Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose () {
    super.dispose ();
    _controller.dispose ();
  }
}

**Comment by darshankawar** [comment]
@thang510023 
There's similar open issue describing your case, [66413](https://github.com/flutter/flutter/issues/66413).
Please follow-up there for updates.
Closing this as duplicate.

**Comment by thang510023** [comment]
> @thang510023
> There's similar open issue describing your case, [66413](https://github.com/flutter/flutter/issues/66413).
> Please follow-up there for updates.
> Closing this as duplicate.

thanks for your advice
