### ISSUE TITLE
Video Not Playing [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)

### ISSUE THREAD

**Issue by jk-hub** [flutter/flutter#66877]
Hello 

## Steps to Reproduce

1. The path which I have given it show in my file manager and also video gets stored there but I'm unable to play this video it gives the error of open failed: ENOENT (No such file or directory) please help me out in this issue.

2.error: E/flutter (19622): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1600060851325.mp4: open failed: ENOENT (No such file or directory), null)

3.E/ExoPlayerImplInternal(19622): com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1600060851325.mp4: open failed: ENOENT (No such file or directory)

## Logs

```
```

D:\daq-dynamic>flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jk\AppData\Local\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\jk\AppData\Local\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • ONEPLUS A3003 (mobile) • 192.168.0.100:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

```
```
---------------------------------------------------------------------------------------------------------------------------------------

you can refer to my repo [git repo](https://github.com/jk-hub/Custom_camera)https://github.com/jk-hub/Custom_camera
clone and check it. if you need any thing more please tell me also please looking into this video player issue 
Thanks,

**Comment by darshankawar** [comment]
@jk-hub 
What are the steps to replicate the issue ? I cloned your repo but see `video` and `camera` options but can't choose any video from storage. Am I missing anything ?
Thanks.

**Comment by jk-hub** [comment]
> @jk-hub
> What are the steps to replicate the issue ? I cloned your repo but see `video` and `camera` options but can't choose any video from storage. Am I missing anything ?
> Thanks.

@drashankawar just click on video btn and start recording after stopping the video i have passed the path to video player for viewing the video but as soon as we stop the video and video player get the path of the clicked video but the path that i have given it of storage/0/ then our custom folder so it can not read that file that the issue I hope you got the point 
if not I can explain again 
Thank you.

**Comment by darshankawar** [comment]
@jk-hub 
I am unable to stop video recording after tapping on it. Also, I get below exception:

`Unhandled Exception: FileSystemException: Creation failed, path = 'storage/emulated/0/Own_Camera_Demo' (OS Error: Permission denied, errno = 13)`

Can you try the official video_player plugin example and see if you get same error which you are getting originally ?
Thanks.

**Comment by jk-hub** [comment]
> @jk-hub
> I am unable to stop video recording after tapping on it. Also, I get below exception:
> 
> `Unhandled Exception: FileSystemException: Creation failed, path = 'storage/emulated/0/Own_Camera_Demo' (OS Error: Permission denied, errno = 13)`
> 
> Can you try the official video_player plugin example and see if you get same error which you are getting originally ?
> Thanks.

@darshankawar  please go in app info and give  storage permission the path creation is failed because of that so please give the permission and try again also i tried with official video player plugin example but there same error is occurred which was initial occurred  so I request to you please check this issue.

error: E/flutter ( 7738): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1601442884367.mp4: open failed: ENOENT (No such file or directory), null)

Thank you.

**Comment by darshankawar** [comment]
Issue replicable. Tested on Android device 8.1.0. After recording video, app throws below exception:

`E/flutter (16380): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1601445645494.mp4: open failed: ENOENT (No such file or directory), null, null)`

Not sure if this is implementation or plugin issue. Keeping this open for further analysis.

**Comment by jk-hub** [comment]
> Issue replicable. Tested on Android device 8.1.0. After recording video, app throws below exception:
> 
> `E/flutter (16380): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1601445645494.mp4: open failed: ENOENT (No such file or directory), null, null)`
> 
> Not sure if this is implementation or plugin issue. Keeping this open for further analysis.

so now who is going to check this error or issue or who is going to resolve this issue @darshankawar 
Thank you.

**Comment by jk-hub** [comment]
> Issue replicable. Tested on Android device 8.1.0. After recording video, app throws below exception:
> 
> `E/flutter (16380): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1601445645494.mp4: open failed: ENOENT (No such file or directory), null, null)`
> 
> Not sure if this is implementation or plugin issue. Keeping this open for further analysis.

Any update on this till when this issue will get resolved.

**Comment by jk-hub** [comment]
> > Issue replicable. Tested on Android device 8.1.0. After recording video, app throws below exception:
> > `E/flutter (16380): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Own_Camera_Demo/Media/1601445645494.mp4: open failed: ENOENT (No such file or directory), null, null)`
> > Not sure if this is implementation or plugin issue. Keeping this open for further analysis.
> 
> Any update on this till when this issue will get resolved.

Any update on this issue

**Comment by hamdikahloun** [comment]
Hi @jk-hub 

**Change**
 `final path = Directory("/storage/emulated/0/$folderName/$subFolderName");`
**To**
`final path = Directory("/storage/emulated/0/$folderName/$subFolderName");`

**Comment by maheshmnj** [comment]
Hi @Jk-hub,
Looks like there was a implementation issue in your code and not  issue with the plugin,

I have updated your two files with

<details>
<summary>globals.dart</summary>

```
library own_camera.globals;

import 'dart:io';

import 'package:path_provider/path_provider.dart';

String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

Future<String> getDir() async {
  var folderName = 'Own_Camera_Demo';
  var subFolderName = 'Media';
  final Directory extDir = await getApplicationDocumentsDirectory();
  final String dirPath = '${extDir.path}/$folderName/$subFolderName';
  await Directory(dirPath).create(recursive: true);
  final String path = '$dirPath/${timestamp()}.mp4';
  return path;
}

```
</details>  


<details>
<summary>camera_screen.dart</summary>


modified startVideo recording function. 

```
  Future<String> startVideoRecording() async {
    print('startVideoRecording');
    if (!_controller.value.isInitialized) {
      return null;
    }
    setState(() {
      _isRecording = true;
    });
    _timerKey.currentState.startTimer();

    // final Directory extDir = await getApplicationDocumentsDirectory();
    // final String dirPath = '${extDir.path}/media';
    // await Directory(dirPath).create(recursive: true);
    var filePath = await globals.getDir();
    // final String filePath = '$dir/${_timestamp()}.mp4';

    if (_controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }

    try {
      videoPath = filePath;
      await _controller.startVideoRecording(filePath);
    } on CameraException catch (e) {
      _showCameraException(e);
      setState(() {
        _isRecording = false;
      });
      return null;
    }
    return filePath;
  }
```
</details>  

With these changes I was able to record and play the recorded video.  For more advanced features  I would recommend you to look at the [sample example in the camera plugin.](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example).

Since this is not an issue with flutter but with your code, I am going to close this issue if you disagree feel free to comment and I will reopen it.
