### ISSUE TITLE
We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high

### ISSUE THREAD

**Issue by EchoPuda** [flutter/flutter#66890]
1. Hi, we want to achieve a gifs effect, and we used Animation to controller Image.
Then it led to a severe heating of the equipment(Thermal State: Serious)
Is that normal? Is there any optimization that we can do?

2.
<details>
<summary>code sample</summary>

```
 _controller = new AnimationController(
        duration: Duration(milliseconds: maxTime), vsync: this);
    _controller.addStatusListener((AnimationStatus status) {
      if(status == AnimationStatus.completed) {
        Future.delayed(Duration(milliseconds: 10000), () {
          _controller.forward(from: 0.0);
        });
      }
    });

    _animation = new Tween<double>(begin: 0, end: imageCount.toDouble()).animate(_controller)
      ..addListener(() {
        setState(() {
          index = _animation.value.floor() % widget._assetList.length;
        });
      });

    _controller.forward();`

`    return Image.asset(
      widget._assetList[index],
      width: widget.width,
      height: widget.height,
      gaplessPlayback: true,
    );`
```

</details>

**Target Platform: iOS**
**Target OS version/browser: ios12+**
**Devices: IPhone 8, IPhone 8 plus**

[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/zhengjiaming/Flutter1.20.2/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zhengjiaming/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/zhengjiaming/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by darshankawar** [comment]
@EchoPuda 
Please provide a minimal complete reproducible code sample that we can directly use and run to see the issue. Also how do you measure the phone temperature ?
After you stopped the app, did the temperature go down ? does it happen with any other native app  that has animations ?
thanks.

**Comment by EchoPuda** [comment]
`import 'dart:async';
import 'package:flutter/material.dart';

/// Frame animation
/// @author jm
class FrameAnimateImage extends StatefulWidget {
  final List<String> _assetList;
  final double width;
  final double height;
  final int interval;

  FrameAnimateImage(this._assetList, {this.width, this.height, this.interval : 100});

  @override
  State<StatefulWidget> createState() {
    return _FrameAnimateImageState();
  }
}

class _FrameAnimateImageState extends State<FrameAnimateImage>
    with SingleTickerProviderStateMixin {
  // 动画控制
  Animation<double> _animation;
  AnimationController _controller;
  int interval = 200;
  int index = 0;
  Timer _timer;
  bool _active = true;

  @override
  void initState() {
    super.initState();

    init();
  }

  void init() {
    if (widget.interval != null) {
      interval = widget.interval;
    }

    final int imageCount = widget._assetList.length;
    final int maxTime = interval * imageCount;
    
    _controller = new AnimationController(
        duration: Duration(milliseconds: maxTime), vsync: this);
    _controller.addStatusListener((AnimationStatus status) {
      if(status == AnimationStatus.completed) {
        Future.delayed(Duration(milliseconds: 2000), () {
          _controller.forward(from: 0.0);
        });
      }
    });

    _animation = new Tween<double>(begin: 0, end: imageCount.toDouble()).animate(_controller)
      ..addListener(() {
        setState(() {
          index = _animation.value.floor() % widget._assetList.length;
        });
      });

    _controller.forward();


  }

  @override
  void dispose() {
    if (_controller != null) {
      _controller.dispose();
    }
    if (_timer != null) {
      _timer.cancel();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return _buildImages();
  }

  Widget _buildImages() {

    return Image.asset(
      widget._assetList[index],
      width: widget.width,
      height: widget.height,
      gaplessPlayback: true,
    );
    
  }

}`

**Comment by EchoPuda** [comment]
use:

```
FrameAnimateImage(
              ['your images path'],
              width: 70.5,
              height: 72,
              interval: 50,
            )
```

**Comment by EchoPuda** [comment]
I run the project directly in XCode, and then Debug can check the Energy Impact.

I compared the situations of using and not using, and found that the fever was severe only when using and normal when not using. Aslo when I stop it, it go down after a few minutes.

We only developed with Flutter, so there was no native app, sorry.

**Comment by EchoPuda** [comment]
import 'dart:async'; import 'package:flutter/material.dart'; /// Frame animation /// @author jm class FrameAnimateImage extends StatefulWidget {   final List<String&gt; _assetList;   final double width;   final double height;   final int interval;   FrameAnimateImage(this._assetList, {this.width, this.height, this.interval : 100});   @override   State<StatefulWidget&gt; createState() {     return _FrameAnimateImageState();   } } class _FrameAnimateImageState extends State<FrameAnimateImage&gt;     with SingleTickerProviderStateMixin {   Animation<double&gt; _animation;   AnimationController _controller;   int interval = 200;   int index = 0;   @override   void initState() {     super.initState();     init();   }   void init() {     if (widget.interval != null) {       interval = widget.interval;     }     final int imageCount = widget._assetList.length;     final int maxTime = interval * imageCount;          _controller = new AnimationController(         duration: Duration(milliseconds: maxTime), vsync: this);     _controller.addStatusListener((AnimationStatus status) {       if(status == AnimationStatus.completed) {         Future.delayed(Duration(milliseconds: 2000), () {           _controller.forward(from: 0.0);         });       }     });     _animation = new Tween<double&gt;(begin: 0, end: imageCount.toDouble()).animate(_controller)       ..addListener(() {         setState(() {           index = _animation.value.floor() % widget._assetList.length;         });       });     _controller.forward();   }   @override   void dispose() {     if (_controller != null) {       _controller.dispose();     }     super.dispose();   }   @override   Widget build(BuildContext context) {     return _buildImages();   }   Widget _buildImages() {     return Image.asset(       widget._assetList[index],       width: widget.width,       height: widget.height,       gaplessPlayback: true,     );        } }


use:
FrameAnimateImage(     ['your images path'],     width: 70.5,     height: 72,     interval: 50, )



I run the project directly in XCode, and then Debug can check the Energy Impact.

I compared the situations of using and not using, and found that the fever was severe only when using and normal when not using. Aslo when I stop it, it go down after a few minutes.

We only developed with Flutter, so there was no native app, sorry.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 晚上7:33
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda
 Please provide a minimal complete reproducible code sample that we can directly use and run to see the issue. Also how do you measure the phone temperature ?
 After you stopped the app, did the temperature go down ? does it happen with any other native app  that has animations ?
 thanks.

**Comment by EchoPuda** [comment]
import 'dart:async'; import 'package:flutter/material.dart'; /// Frame animation /// @author jm class FrameAnimateImage extends StatefulWidget {   final List<String&gt; _assetList;   final double width;   final double height;   final int interval;   FrameAnimateImage(this._assetList, {this.width, this.height, this.interval : 100});   @override   State<StatefulWidget&gt; createState() {     return _FrameAnimateImageState();   } } class _FrameAnimateImageState extends State<FrameAnimateImage&gt;     with SingleTickerProviderStateMixin {   Animation<double&gt; _animation;   AnimationController _controller;   int interval = 200;   int index = 0;   @override   void initState() {     super.initState();     init();   }   void init() {     if (widget.interval != null) {       interval = widget.interval;     }     final int imageCount = widget._assetList.length;     final int maxTime = interval * imageCount;          _controller = new AnimationController(         duration: Duration(milliseconds: maxTime), vsync: this);     _controller.addStatusListener((AnimationStatus status) {       if(status == AnimationStatus.completed) {         Future.delayed(Duration(milliseconds: 2000), () {           _controller.forward(from: 0.0);         });       }     });     _animation = new Tween<double&gt;(begin: 0, end: imageCount.toDouble()).animate(_controller)       ..addListener(() {         setState(() {           index = _animation.value.floor() % widget._assetList.length;         });       });     _controller.forward();   }   @override   void dispose() {     if (_controller != null) {       _controller.dispose();     }     super.dispose();   }   @override   Widget build(BuildContext context) {     return _buildImages();   }   Widget _buildImages() {     return Image.asset(       widget._assetList[index],       width: widget.width,       height: widget.height,       gaplessPlayback: true,     );        } }


use:
FrameAnimateImage(     ['your images path'],     width: 70.5,     height: 72,     interval: 50, )



I run the project directly in XCode, and then Debug can check the Energy Impact.

I compared the situations of using and not using, and found that the fever was severe only when using and normal when not using. Aslo when I stop it, it go down after a few minutes.

We only developed with Flutter, so there was no native app, sorry.




It only happen below IPhone X








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 晚上7:33
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda
 Please provide a minimal complete reproducible code sample that we can directly use and run to see the issue. Also how do you measure the phone temperature ?
 After you stopped the app, did the temperature go down ? does it happen with any other native app  that has animations ?
 thanks.

**Comment by darshankawar** [comment]
@EchoPuda Still getting compile errors while running your code.

```
return MaterialApp(
      home: FrameAnimateImage(_assetList),
    );
```

```
lib/main.dart:18:31: Error: The getter '_assetList' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:newios/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_assetList'.
      home: FrameAnimateImage(_assetList),

```

Please provide complete code that we don't have to fix and simply run.
Thanks

**Comment by EchoPuda** [comment]
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() =&gt; _MyAppState();
}

class _MyAppState extends State<MyApp&gt; {
  List<String&gt; shopBagImageList = [];

  @override
  void initState() {
    super.initState();
    for (int i = 1; i < 46; i++) {
      shopBagImageList.add("images/shop_bag/$i.png");
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Center(
          child: FrameAnimateImage(
            shopBagImageList,
            width: 70.5,
            height: 72,
            interval: 50,
          ),
        ),
      ),
    );
  }

}


example above, import the FrameAnimateImage that I have sent. And the images in the attachment.


flutter:
  uses-material-design: true
  assets:
    - images/shop_bag/


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 下午2:30
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda Still getting compile errors while running your code.
 return MaterialApp(       home: FrameAnimateImage(_assetList),     );  lib/main.dart:18:31: Error: The getter '_assetList' isn't defined for the class 'MyApp'.  - 'MyApp' is from 'package:newios/main.dart' ('lib/main.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named '_assetList'.       home: FrameAnimateImage(_assetList),  
Please provide complete code that we don't have to fix and simply run.
 Thanks

**Comment by darshankawar** [comment]
@EchoPuda 
It's a bit hard to join all the pieces of code that you have sent above. I'd suggest to create a demo repo, put all the required code there and share the repo link here, so that we can clone and run the code directly.
Thanks.

**Comment by EchoPuda** [comment]
Sorry for replying you so late
This is the demo.
https://github.com/EchoPuda/test_animation


And I found that this also happened with svgaplayer_flutter and lottie, even worse




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 晚上7:56
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda
 It's a bit hard to join all the pieces of code that you have sent above. I'd suggest to create a demo repo, put all the required code there and share the repo link here, so that we can clone and run the code directly.
 Thanks.

**Comment by EchoPuda** [comment]
oh, if there is only one animation, it seems to be ok.
Is it possible that we have more UI on the current page, "setState" along with this animation?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 晚上7:56
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda
 It's a bit hard to join all the pieces of code that you have sent above. I'd suggest to create a demo repo, put all the required code there and share the repo link here, so that we can clone and run the code directly.
 Thanks.

**Comment by darshankawar** [comment]
@EchoPuda 
Cloned your repo and ran app on iPhone 6s with iOS 14 using latest stable version, but didn't notice any high temperature of the phone. Kept the app running for 5 minutes and it didn't heat up at all.

I'd suggest you to upgrade to latest stable and try again to see if it works.
Thanks.

**Comment by EchoPuda** [comment]
oh, it happened at least 30 minutes later. And maybe it's because the current page has a large number of widgets. The more widgets there have, the less time it takes to heat up.
However, after we try to remove this animation, no matter how long it will not cause temperature anomaly.&nbsp;
Now we're going to use Native to implementation and compare.


Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 下午2:40
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"灬JoM in"<513219857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] We used Animation to achieve the gifs effect, which caused the temperature of the phone to be too high (#66890)





 
@EchoPuda
 Cloned your repo and ran app on iPhone 6s with iOS 14 using latest stable version, but didn't notice any high temperature of the phone. Kept the app running for 5 minutes and it didn't heat up at all.
 
I'd suggest you to upgrade to latest stable and try again to see if it works.
 Thanks.

**Comment by EchoPuda** [comment]
OK, we finally found that the animation was on the same page as the Gaussian blur effect used for the background of the page, which caused the problem. After we remove this effect, it solved.
Thanks for your time.
