### ISSUE TITLE
我iOS 14启用了本地网络，仍然不能运行

### ISSUE THREAD

**Issue by Zhaimm** [flutter/flutter#66895]
![WechatIMG1325](https://user-images.githubusercontent.com/32920612/94543637-e5d3df00-027c-11eb-9c69-33aa0e66e014.jpeg)
![WechatIMG1326](https://user-images.githubusercontent.com/32920612/94543643-e79da280-027c-11eb-9f77-040d311a79a2.jpeg)

**Comment by darshankawar** [comment]
@Zhaimm 
There's similar open issue describing your case, [66408](https://github.com/flutter/flutter/issues/66408).
Please follow-up there for updates.
Closing this as duplicate.
