### ISSUE TITLE
Need a way of interrupting a misbehaving app

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#6689]
## Steps to Reproduce

I have a fork of the gallery that I seem to have introduced a bug into (https://github.com/dart-lang/flit/tree/flitted_gallery/flitted_gallery)

When run the app via Flutter run, on the iOS simulator, it behaves until I tap "Shrine" -- which is probably where I have introduced the bug.

After this, the simulator stops responding, and "R" takes multiple minutes to complete.  There is no error shown on the simulator or on the console. Connecting to the observatory doesn't work. 

Interaction from the IntellIJ plugin, such as breaking, doesn't appear to have an effect.

## Recommendations

- Restart should work independently of the state of the app
- It would be great to be able to have a way to forcibly pause an app, even if it was misbehaving, to inspect the stack trace
- When the FPS of an app drops below say 1 fps, for more than 5s, it is almost certainly broken. It would be great to have a mode where the app would halt itself if it was misbehaving that badly to give the developer an opportunity to understand what was going on.

**Comment by Hixie** [comment]
The link above is 404.

Can you reduce your test case to something short? I'm not sure what specific action we could do to resolve this issue.

**Comment by johnmccutchan** [comment]
Closing as stale.
