### ISSUE TITLE
Hot reload error

### ISSUE THREAD

**Issue by RaghavAggiwal** [flutter/flutter#66899]
**Error:**

`
Hot Reload Error reloadSources: (105) Isolate must be runnable Isolate must be runnable before this request is made
`

**Platform:** Android Studio

**Flutter doctor:**

[√] Flutter (Channel master, 1.22.0-10.0.pre.406, on Microsoft Windows [Version 10.0.17763.678], locale en-IN)
    • Flutter version 1.22.0-10.0.pre.406 at C:\src\flutter
    • Framework revision 5872b70b8c (86 minutes ago), 2020-09-29 05:47:04 -0400
    • Engine revision 1c462e28a2
    • Dart version 2.11.0 (build 2.11.0-176.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\raghav.aggiwal\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\raghav.aggiwal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • SM A105F (mobile) • RZ8M5004SKZ • android-arm • Android 10 (API 29)

• No issues found!

**pubspec.yaml:**

environment:
  sdk: ">=2.10.0-0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: ^0.2.0
  provider: ^4.3.2+1
  path_provider: ^1.6.14
  flutter_secure_storage: ^3.3.3
  google_sign_in: ^4.5.1
  flutter_html: ^1.0.0
  flutter_svg: ^0.18.0
  cached_network_image: ^2.2.0+1
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  logger: ^0.9.1
  url_launcher: ^5.4.10
  http: ^0.12.1
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.0.2
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  flutter_launcher_icons: ^0.7.5
  firebase_messaging: ^7.0.0
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.7.1
  build_runner: ^1.10.2

**Comment by darshankawar** [comment]
@RaghavAggiwal 
There's similar open issue describing your case, [26953](https://github.com/flutter/flutter/issues/26953).
Please follow-up there for updates.
Closing this as duplicate.
