### ISSUE TITLE
TextFormField prefix icon doesn't turn red on validation error

### ISSUE THREAD

**Issue by TMaxedCode** [flutter/flutter#66903]
## Steps to Reproduce
Create and validate the TextFormField below:
```
  TextFormField(
    decoration: InputDecoration(
        labelText: "Password",
        border: OutlineInputBorder(),
        prefixIcon: Icon(Icons.lock_outline)),
    validator: (value) {
      if (value.isEmpty) {
        return 'Please enter some text';
      }
      return null;
    },
  )
```

**Expected results:** 
![expectation](https://user-images.githubusercontent.com/57564335/94555383-17a17180-028e-11eb-95e0-4a36bfddcebd.png)

**Actual results:** 
![reality](https://user-images.githubusercontent.com/57564335/94555501-3d2e7b00-028e-11eb-9a21-1491787c1b4e.png)

**Comment by pedromassangocode** [comment]
Hi @TMaxedCode 
Based on Material Design specs (That Flutter follows) the `prefix` icon is not supposed to change its color if the text field has validation error but the `suffixIcon` property is the one that should change its color to red if there is a validation error.

Please see
https://material.io/components/text-fields

I'm closing this as working as expected. 
Thank you
