### ISSUE TITLE
Your app(s) are vulnerable to Intent Redirection

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter/flutter#66901]
i tried to upload my flutter app to play store, but i got this message "Your app(s) are vulnerable to Intent Redirection" i dont know from where this issue arises. Please help!

**Comment by gangov** [comment]
this error means, that some of your classes are exposing user's data. Can you share the full error and your app code?

**Comment by faisalmushtaq007** [comment]
This is the message from Google:
Hello Google Play Developer,

We reviewed Hi Tech Group, with package name com.rationaltabs.hitechgroup, and found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please migrate your apps to use the updated software as soon as possible and increment the version number of the upgraded APK.
Intent Redirection
Your app(s) are vulnerable to Intent Redirection.

To address this issue, follow the steps in this Google Help Center article.

**Comment by pedromassangocode** [comment]
Hi @faisalmushtaq007 
Can you please provide your `flutter doctor -v` and your `pubspec.yaml`?
Thank you

**Comment by faisalmushtaq007** [comment]
@pedromassangocode My pubspec.yaml:
name: hitech_shop_flutter
description: A new Flutter project.


version: 1.0.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.0
  shimmer: ^1.1.1
  flutter_slidable: ^0.5.7
  flutter_rating: ^0.0.2
  intro_views_flutter: ^2.8.2
  url_launcher: ^5.7.2
  global_configuration: ^1.6.0
  http: ^0.12.2
  shared_preferences: ^0.5.12
  mvc_pattern: 6.0.0
  cached_network_image: ^2.3.2+1
  flutter_form_builder: ^3.13.6
  razorpay_flutter: ^1.2.2
  loading: ^1.0.2
  progress_dialog: ^1.2.4
  toast: ^0.1.5
  no_context_navigation: ^1.0.3
  flutter_plugin_android_lifecycle: ^1.0.4
  onesignal_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/cfg/app_settings.json
    - assets/img/google.png
    - assets/img/handshake.png
    - assets/img/icon_facebook.png
    - assets/img/logo.png
    - assets/img/Rectangle.png
    - assets/img/girl.png
    - assets/img/loginscreenbackground.png
    - assets/img/search.png
    - assets/img/search2.png
    - assets/img/chat.png
    - assets/img/notifications-button.png
    - assets/img/servicepay.jpg
    - assets/icon/book.png
    - assets/icon/camera.png
    - assets/icon/fashion.png
    - assets/icon/food.png
    - assets/icon/game.png
    - assets/icon/handphone.png
    - assets/icon/health.png
    - assets/icon/mesin.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/img/flashsaleicon.png
    - assets/imgItem/hiislider1.jpg
    - assets/imgItem/hiislider2.jpg
    - assets/imgItem/hiislider3.jpg
    - assets/img/notmessage.png
    - assets/img/noNotification.png
    - assets/icon/truck.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/paytm.png
    - assets/img/bag.png
    - assets/img/courier.png
    - assets/img/house.png
    - assets/img/order.png
    - assets/img/payment.png
    - assets/icon/girlcallcenter.png
    - assets/icon/facebook.png
    - assets/icon/instagram.png
    - assets/icon/yahoo.png
    - assets/icon/splash_back.jpg
    - assets/icon/hi_tech_logo.png
    - assets/img/1.jpg
    - assets/img/2.jpg
    - assets/img/3.jpg
    - assets/img/img_no_internet.png
    - assets/img/checklist.png
    - assets/img/favourite.png
    - assets/icon/creditAcount.png
    - assets/img/flashsalebanner.png
    - assets/icon/flashSaleIcon.png
    - assets/img/product_placeholder.jpg
    - assets/img/headerProfile.png
    - assets/img/cancel.png
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/holding-phone.png
    - assets/imgIllustration/IlustrasiOnBoarding1.png
    - assets/imgIllustration/IlustrasiOnBoarding2.png
    - assets/imgIllustration/IlustrasiOnBoarding3.png
    - assets/imgIllustration/IlustrasiCart.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

**Comment by faisalmushtaq007** [comment]
@pedromassangocode My flutter doctor -v output:
flutter doctor -v
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.20.0 at C:\src\flutter
    • Framework revision 840c9205b3 (8 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Faisal Mushtaq\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\Faisal Mushtaq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.0

[√] Connected device (1 available)
    • POCO F1 (mobile) • 3964932c • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by pedromassangocode** [comment]
Based on my research this may be caused by one of the plugins being used in your project. Please read more on the link bellow and let me know if it fix the issue for you.

**Remediation for Intent Redirection Vulnerability**
https://support.google.com/faqs/answer/9267555?hl=en

Thanks

**Comment by faisalmushtaq007** [comment]
@pedromassangocode I tried to use this, but i don't know how and where.
In my project i am using url_launcher package to open Whatsapp from my app, thats it. its the only external intent i use.
Now how will i apply your solution to that. Could you guide me

**Comment by pedromassangocode** [comment]
Hi @faisalmushtaq007 
The link I provided may only be used from the package maintainer of one of the packages you use.
Can you remove the packages you that you think is causing this issue and try to upload your app into Google Play?

**Comment by faisalmushtaq007** [comment]
@pedromassangocode I first thought its because of url_launcher package, so i commented it and uploaded back but its showing the same thing again. Now i think that its because of RazorPay payment gateway. Now what will i do?

**Comment by pedromassangocode** [comment]
I suggest you to try to comment the package and try again. Since it is a payment gateway it may eventually start an intent for some reason and that may be the cause.

**Comment by faisalmushtaq007** [comment]
@pedromassangocode I tried this also, but still same thing is happening. Any other suggestions?

**Comment by pedromassangocode** [comment]
No. All I can tell is that this is not an issue with Flutter because this warning is caused by some Intent actions and as far as I know Flutter does not start any Android intent internally.

I can only suggest you to verify each plugin used in your project carefully to find which one is causing this.

Will leave this opened to track this issue and this should be closed after some time.

**Comment by rahuldange09** [comment]
Hi @faisalmushtaq007  have you solved this, because I also started getting same issue recently. 
Can you please tell me if you fixed this as this is critical thing.

thank you

**Comment by ZipoNamberwan** [comment]
@faisalmushtaq007 i also got same issue, i also used razorpay. Can you please tell me how you solved the issue?

**Comment by pedromassangocode** [comment]
For anyone facing this issue, please try to remove suspicious plugins and try to submit the app again to find out which plugin is causing this.

**Comment by ZipoNamberwan** [comment]
so is this caused by razorpay plugin?

**Comment by pedromassangocode** [comment]
This might be caused by any plugin the starts an [Intent](https://developer.android.com/reference/android/content/Intent) on Android.

**Comment by rahuldange09** [comment]
I'm also using razorpay.
I think then we must report to razorpay regarding this

**Comment by ZipoNamberwan** [comment]
I am using razorpay_flutter 1.2.2. The last time this package updated is 22 July 2020, which is been so long ago

**Comment by rahuldange09** [comment]
There is no issue regarding razorpay I think.

**I successfully removed that issue by doing following things.**
Check if you any older app version in internal, alpha or beta testing and if there any replace it with newer version.
And after that wait for some hours even after it gets live.
Then check on console this alerts will be dismissed.

**Comment by ZipoNamberwan** [comment]
I dont have any alpha, beta or internal testing release

**Comment by ZipoNamberwan** [comment]
Any other solution?

**Comment by ZipoNamberwan** [comment]
I manage to solve the issue by removing cashfree_pg package from my app. This package is the culprit of this intent redirection vulnerability.

**Comment by faisalmushtaq007** [comment]
@ZipoNamberwan can you please provide your punspec.yaml file

**Comment by faisalmushtaq007** [comment]
i got this in my mail from google developers group:
![Screenshot (43)](https://user-images.githubusercontent.com/24683159/97805559-df21f880-1c7c-11eb-8d21-44d7702508eb.png)

**Comment by ZipoNamberwan** [comment]
cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  after_layout: ^1.0.7+2
  font_awesome_flutter: ^8.8.1
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  dotted_border: ^1.0.5
  image_picker: ^0.6.7+12
  sqflite: ^1.3.0+1
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2
  location: ^3.0.2
  flutter_spinkit: ^4.1.2+1
  pin_code_fields: ^3.0.1
  shared_preferences: ^0.5.7+3
  smooth_star_rating: 1.1.1
  package_info: ^0.4.1
  device_info: ^0.4.2+4
  dio: ^3.0.9
  firebase_auth: ^0.18.1+1
  google_sign_in: ^4.5.1
  flutter_facebook_login: 3.0.0
  razorpay_flutter: ^1.2.2
  google_fonts: ^1.1.0
  scratcher: 1.4.0
  modal_bottom_sheet: ^0.2.2
  mask_text_input_formatter: ^1.0.7
  firebase_messaging: ^7.0.2
  flutter_local_notifications: ^1.4.4+2
  share: ^0.6.4+3
  video_player: ^0.10.11+2
  sms_autofill: ^1.2.3
  url_launcher: ^5.5.0
  youtube_player_flutter: ^6.0.3
  stripe_payment: ^1.0.7
  fluttertoast: ^7.0.2
  scrollable_positioned_list: ^0.1.7
  cashfree_pg: 0.0.4+9
  mapbox_gl: ^0.8.0
  html: ^0.14.0+3
  apple_sign_in: ^0.1.0
  firebase_core: ^0.5.0
  clipboard: ^0.1.2+8

@faisalmushtaq007 cashfree is the one that create the issue in my case, so i remove it

**Comment by faisalmushtaq007** [comment]
Has anyone solved this issue?

**Comment by ZipoNamberwan** [comment]
@faisalmushtaq007 you can try to remove suspected packages one by one. For testing, you can use internal testing. Then, you can see your inbox if the apk you upload to internal testing still has the issue or not. Pay attention to the version code. I managed to solve the issue using this way.

**Comment by faisalmushtaq007** [comment]
@ZipoNamberwan i am using these packages


cupertino_icons: ^1.0.0
flutter_launcher_icons: ^0.8.0
shimmer: ^1.1.1
flutter_slidable: ^0.5.7
flutter_rating: ^0.0.2
intro_views_flutter: ^2.8.2
global_configuration: ^1.6.0
image_picker: ^0.6.7+15
http: ^0.12.2
intl: ^0.16.1
shared_preferences: ^0.5.12
mvc_pattern: ^6.0.0
cached_network_image: ^2.3.2+1
flutter_form_builder: ^3.14.0
razorpay_flutter: ^1.2.3
loading: ^1.0.2
progress_dialog: ^1.2.4
toast: ^0.1.5
no_context_navigation: ^1.0.3
flutter_plugin_android_lifecycle: ^1.0.11
onesignal_flutter: ^2.6.1
url_launcher: ^5.7.10
provider : ^4.0.4
pub_semver: ^1.4.4
package_info: ^0.4.3
