### ISSUE TITLE
Flutter CLI breaking

### ISSUE THREAD

**Issue by nandubatchu** [flutter/flutter#66904]
```Failed to download https://storage.googleapis.com/flutter_infra/flutter/b863200c37df4ed378042de11c4e9ff34e4e58c9/darwin-x64/font-subset.zip. Ensure you have network connectivity and then try again.```

Is this resource down?

**Comment by HaythamEssam17** [comment]
did you find any answer?

**Comment by pedromassangocode** [comment]
Hi @nandubatchu 
Can you please provide your `flutter doctor -v` and the steps to reproduce this issue?
Thank you

**Comment by sideeg** [comment]
> Hi @nandubatchu
> Can you please provide your `flutter doctor -v` and the steps to reproduce this issue?
> Thank you

Downloading package sky_engine...                                  32.7s
Downloading flutter_patched_sdk tools...                            0.2s
Downloading flutter_patched_sdk tools...                            0.6s
Failed to download
https://storage.googleapis.com/flutter_infra/flutter/5babba6c4d25fa237bbf755ab85c9a0c50b3c6ec/flutter_patched_sdk.zip.
Ensure you have network connectivity and then try again.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1486:11)
<asynchronous suspension>
#2      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:717:29)
<asynchronous suspension>
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:923:27)
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _runZoned (dart:async/zone.dart:1630:10)
#13     runZoned (dart:async/zone.dart:1550:10)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#17     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _runZoned (dart:async/zone.dart:1630:10)
#23     runZoned (dart:async/zone.dart:1550:10)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:281:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:223:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:230:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _runZoned (dart:async/zone.dart:1630:10)
#34     runZonedGuarded (dart:async/zone.dart:1618:12)
#35     runZoned (dart:async/zone.dart:1547:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     run.<anonymous closure> (package:flutter_tools/runner.dart)
#38     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#39     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _runZoned (dart:async/zone.dart:1630:10)
#44     runZoned (dart:async/zone.dart:1550:10)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#46     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#47     run (package:flutter_tools/runner.dart:46:10)
#48     main (package:flutter_tools/executable.dart:77:9)
#49     main (file:///D:/sideeg%20tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by sideeg** [comment]
fixed to me 
it was just a vpn problem I am in blocked Country  and i was using a VPN in blocked country 
i just change my VPN and it worked 
but was the error message is  (Ensure you have network connectivity and then try again) ?? i think it must be (Forbidden client error  ) with response code 403 to indicates that the server understood the request but refuses to authorize it

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Mahmoud-msr98** [comment]
@sideeg What name vpn  did you use? Thanks

**Comment by MilkBiscuit** [comment]
`Downloading ios tools...
Downloading ios tools...
Failed to download https://storage.googleapis.com/flutter_infra/flutter/05e680e202af9a92461070cb2d9982acad46c83c/ios/artifacts.zip. Ensure you have network connectivity and then try again.
Exception: 404
`



~% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-arm, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by osabogal10** [comment]
> `Downloading ios tools... Downloading ios tools... Failed to download https://storage.googleapis.com/flutter_infra/flutter/05e680e202af9a92461070cb2d9982acad46c83c/ios/artifacts.zip. Ensure you have network connectivity and then try again. Exception: 404 `
> 
> ~% flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-arm, locale en-NZ)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.2)
> [✓] VS Code (version 1.56.2)
> [✓] Connected device (2 available)
> 
> • No issues found!

We are having the same issue, it appeared first in our CI building for our next prod release. We were able to replicate it locally running `flutter precache`

Even `fvm releases` fails trying to fetch a json file from `flutter_infra` cloud storage bucket.
`Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra/releases/releases_macos.json`

I did notice however that `flutter_infra_release` works just fine
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json

https://storage.googleapis.com/flutter_infra/flutter/5d8bf811b3072390933d69f3e289a4bb673636c4/android-arm-profile/linux-x64.zip [403 Error]
https://storage.googleapis.com/flutter_infra_release/flutter/5d8bf811b3072390933d69f3e289a4bb673636c4/android-arm-profile/linux-x64.zip [OK]
