### ISSUE TITLE
"flutter build bundle" outputs a warning that seems wrong

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#66906]
Between flutter versions 1.19.0-0.0.pre (dev) and 1.19.0-4.1.pre (beta), something changed that `flutter build bundle` now outputs: `Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.`

The Dev 1.19.0-0.0.pre version does _not_ do this, but Beta 1.19.0-4.1.pre does.

`flutter build bundle` is only really generating the files needed to build, so can this warning be suppressed in this case?

The problem still exists in the latest Beta 1.22.0-12.2.pre. I'm putting my doctor output using the latest beta.

<details><summary>Flutter doctor</summary>

[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-12.2.pre at /Users/danny.valente/Library/flutter/1.22.0-12.2.pre-beta
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
</details>

**Comment by pedromassangocode** [comment]
My output running on Beta channel.

```
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutterb build bundle
Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
MacBook-Pro-de-MacBook:flutter_example pedromassango$ 
```

My output running on Master channel.

```
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutterm build bundle
Font subsetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
MacBook-Pro-de-MacBook:flutter_example pedromassango$ 
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-12.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 7A82F29E-E49E-4B3C-8609-1570361DBC17 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           • web-javascript •
      Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.

```
</details>

**Comment by jonahwilliams** [comment]
This is probably wrong and we should ensure that tree-shake-icons defaults to false for that command. 

Genuinely curious @dannyvalentesonos , what are you using this command for? I cannot imagine it being useful outside of custom embedders

**Comment by dannyvalentesonos** [comment]
> This is probably wrong and we should ensure that tree-shake-icons defaults to false for that command.
> 
> Genuinely curious @dannyvalentesonos , what are you using this command for? I cannot imagine it being useful outside of custom embedders

We embed a flutter module into our existing app. The only way we know how to actually generate the pieces we need to embed is by running `flutter build bundle`. If there's a better or newer way we should be doing this, please do let me know.

Thanks.

**Comment by jonahwilliams** [comment]
That only creates a debug bundle though, what are you doing for release builds?

**Comment by dannyvalentesonos** [comment]
I'm not sure I follow. It creates a bundle which can be used to integrate into an existing app. For example, on iOS you call the **xcode_backend.sh** script and set the correct mode to run flutter in (Debug/Release/Profile).
This has always been working for us for all 3 modes.

The bundle always contains Debug and Release configurations that can be used at actual build time of the existing app.

**Comment by jmagman** [comment]
> I'm not sure I follow. It creates a bundle which can be used to integrate into an existing app. 

Off topic from the warning, but that's interesting, I've never heard of anyone doing this directly with `flutter bundle`.  Did you just read the source to figure it out, or is there a blog post floating around somewhere?
For reference, here's Flutter add-to-app embedding instructions for [iOS](https://flutter.dev/docs/development/add-to-app/ios/project-setup) and [Android](https://flutter.dev/docs/development/add-to-app/android/project-setup).

**Comment by dannyvalentesonos** [comment]
We've been using it this way for 2 years. I'm not sure how it was discovered, but we found that it generates the .ios and .android directories which are needed, seeing we don't commit those to source control.

The Android instructions we use are directly from that page you linked, and we use [Option B](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code), which needs the .android directory.

I'm not sure how else to generate the .ios and .android directories. Is there some other way?

**Comment by jmagman** [comment]
> I'm not sure how else to generate the .ios and .android directories. Is there some other way?

After you create a flutter module, nearly any `flutter` command should create these directories if they are missing (we recommend `flutter pub get` in those docs).  You guys were such early adopters I'm sure you had to come up with your own solutions.  If it's working for you, keep doing it!

**Comment by dannyvalentesonos** [comment]
Thanks @jmagman

I will try `flutter pub get` as `flutter build bundle` runs `pub get` anyway, and if it gets rid of this warning, that'll be great too!

Thanks for the tip!

**Comment by sabersingh** [comment]
Hey @dannyvalentesonos ,
I am quite new to Flutter and I faced similar issue, I think you should try `flutter build appbundle` instead. 

This worked for me.
