### ISSUE TITLE
engine gn updates required for simulator on macOS arm

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66926]
- Currently the engine simulator target hardcodes an x64 architecture. This needs to be changed to allow a configurable target CPU (https://github.com/flutter/engine/blob/master/tools/gn#L163).
- This will also require the existing chrome infra recipes to be updated to specify an x64 arch.
- Finally, the target arch needs to be included in either the output folder or bundle path, so that the tool can select the appropriate version.

Blocked by https://github.com/flutter/flutter/issues/66925
Blocked by https://github.com/flutter/flutter/issues/65901

**Comment by jmagman** [comment]
> * Finally, the target arch needs to be included in either the output folder or bundle path, so that the tool can select the appropriate version.

Or, we can do https://github.com/flutter/flutter/issues/60109.  That will create one bundle with all the architectures (layout details at https://github.com/flutter/flutter/issues/36204#issuecomment-511545864), and clang/Xcode will know how to link on the right pieces.

**Comment by jonahwilliams** [comment]
That sounds like it would simplify distribution. The output folder still needs to be changed so the builds don't clobber eachother on the build bots

**Comment by jmagman** [comment]
> That sounds like it would simplify distribution. The output folder still needs to be changed so the builds don't clobber eachother on the build bots

Ah, you're right.  Plus, to build an xcframework you need all the individual frameworks, then you run a command that smooshes them all together.

**Comment by jeco1996** [comment]
any ETA?

**Comment by jmagman** [comment]
I believe @gw280 tracked down relevant issues and was able to land https://github.com/flutter/buildroot/pull/422.

**Comment by jmagman** [comment]
Next step is https://github.com/flutter/flutter/issues/73066.
