### ISSUE TITLE
App Crash when click on textfield In Google Pixel 3 In Flutter

### ISSUE THREAD

**Issue by anilpatel101** [flutter/flutter#66927]
App crash when click on TextField in Google Pixel 3 but Working in Emulator.Also Working fine in other device but crash on Google pixel device.

And another Issue not hide keyboard when click on back button in Samsung device.

Code : Simple textfield in column widget with SingleChildScrollView.

flutter doctor -v for everthing true without android toolchain.
•Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.6 x86_64) • Dart version 2.10.0 (build 2.10.0-136.0.dev)

Please help.

**Comment by chinmoy12c** [comment]
Please attach the minimal reproducible code for the above issue.

**Comment by xu-baolin** [comment]
May be relate to #66036

**Comment by darshankawar** [comment]
@anilpatel101 
Please switch to latest master or stable and see if it works there. There was similar [issue](https://github.com/flutter/flutter/issues/66791#issuecomment-700487729) raised and author confirmed that it's working in master / stable.

**Comment by anilpatel101** [comment]
Thanks.
Working fine in Stable channel (Flutter version 1.20.4) below both issue.

App crash when click on TextField in Google Pixel 3 but Working in Emulator.Also Working fine in other device but crash on Google pixel device.

And another Issue not hide keyboard when click on back button in Samsung device.
