### ISSUE TITLE
[Flutter macOS] Get absolute path to the user's home directory.

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#66923]
Is there a way to get the user's home directory path in Flutter for macOS when the `com.apple.security.app-sandbox` entitlement is set as true?

When the sandbox is enabled in a macOS app the [path_provider](https://pub.dev/packages/path_provider) package does not return correct home directory. When I try call the `getDownloadsDirectory()` method, it's returning something like: '/Users/username/Library/Containers/com.example.org/Data/Downloads'.

How do I get the user's correct home or downloads directory in a macOS flutter application when the `app sandbox` is enabled?

## Steps to Reproduce

DebugProfile.entitlements:
```xml
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
        <key>com.apple.security.files.user-selected.read-write</key>
        <true/>
</dict>

```

```dart
import 'package:path_provider/path_provider.dart';

print(await getDownloadsDirectory());

````

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.406, on Mac OS X 10.15.6 19G73
    x86_64, locale en-IN)
    • Flutter version 1.22.0-10.0.pre.406 at /Users/username/Library/Application
      Support/fvm/versions/master
    • Framework revision 5872b70b8c (9 hours ago), 2020-09-29 05:47:04 -0400
    • Engine revision 1c462e28a2
    • Dart version 2.11.0 (build 2.11.0-176.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.6 19G73 x86_64

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> When the sandbox is enabled in a macOS app the [path_provider](https://pub.dev/packages/path_provider) package does not return correct home directory. When I try call the `getDownloadsDirectory()` method, it's returning something like: '/Users/username/Library/Containers/com.example.org/Data/Downloads'.

That is the correct downloads directory for a sandboxed application. It seems like you're misunderstanding how the macOS app sandbox works.

This doesn't really seem to be a Flutter question; you'd have exactly the same behavior in a non-Flutter sandboxed macOS application. I would suggest reading more about the sandbox entitlements, and SO questions related to this topic.
