### ISSUE TITLE
[build_dashboard] Settings overlay has some opacity making it difficult to read

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#66929]
Platform: Chrome on MacOS

It would be easier to read if the background was solid.

![Screen Shot 2020-09-29 at 12 14 53 PM](https://user-images.githubusercontent.com/2148558/94605092-71ce1280-024d-11eb-9deb-e4aba37ef1f5.png)

**Comment by CaseyHillers** [comment]
\cc @flar

**Comment by flar** [comment]
The intention was to be able to see the results through it.

Alternatives wold be:

- a different fixed opacity
- a slider to set the opacity with a higher default for first-time readability
- switching to a sidebar or top/bottom bar location for the property sheet

**Comment by CaseyHillers** [comment]
> The intention was to be able to see the results through it.

Ahh I see. We can leave this for now and see what others think. Only a few users take advantage of the branch switching.

Cocoon has [accessibility_test.dart](https://github.com/flutter/cocoon/blob/master/app_flutter/test/widgets/accessibility_test.dart) where we could add a test to verify its meeting the standards.

**Comment by Piinks** [comment]
Ah! you bet me to it. :) 
This is mainly a test contrast issue. If the text were darker/bolder in the image above, and maybe the opacity reduced a smidge I think that would suffice. The a11y meetsGuideline(textContrastGuideline) test should be able to tell.
We'll have to check both the light and dark theme.

**Comment by Piinks** [comment]
![Screen Shot 2020-09-29 at 12 00 06 PM](https://user-images.githubusercontent.com/16964204/94612833-49eca800-0269-11eb-9329-2eb08449a1f3.png)

Here it is in the dark theme currently (above it the light theme).

**Comment by flar** [comment]
Here is a change that I'm working on with the following changes:

- Increased alpha from 0xc0 to 0xe0
- Added `Apply` button that navigates to the path with the appropriate parameters (so you can copy and paste the URL into a bug report, among other possibilities)
- Changed `Reset` to `Defaults`

(Note the navigation URL in the browser address bar, it was `b` last time I hit apply and I've changed it to `bob` which is why the `Apply` button is clickable)

<img width="691" alt="Screen Shot 2020-09-29 at 1 35 26 PM" src="https://user-images.githubusercontent.com/50503328/94612932-aa271e00-0258-11eb-8502-eca4f1eb17b4.png">

**Comment by flar** [comment]
I found a few hard-coded color values in the code and deleted them. Here are the new light and dark theme samples:

<img width="691" alt="Screen Shot 2020-09-29 at 1 50 25 PM" src="https://user-images.githubusercontent.com/50503328/94614315-d80d6200-025a-11eb-914d-43d45074e912.png">

<img width="691" alt="Screen Shot 2020-09-29 at 1 48 30 PM" src="https://user-images.githubusercontent.com/50503328/94614324-dc397f80-025a-11eb-9aa7-1b1e881c6f54.png">

**Comment by flar** [comment]
> Cocoon has [accessibility_test.dart](https://github.com/flutter/cocoon/blob/master/app_flutter/test/widgets/accessibility_test.dart) where we could add a test to verify its meeting the standards.

I added some `meetsGuideline(textContrastGuideline)` tests in both of the golden tests.
