### ISSUE TITLE
iOs devices are unable to process interface components and remain deformed.

### ISSUE THREAD

**Issue by MattheusOliveira** [flutter/flutter#66928]
## Steps to Reproduce

The application for Android and Ios is already in production. However, iOs devices are unable to process interface components, as the bottomNavigationBar and FloatActionButton icons, avatar image and card content remain deformed. This happens from time to time.

![1](https://user-images.githubusercontent.com/29807852/94602155-e2cff300-026a-11eb-9d17-dde1049ecd0b.png)
![2](https://user-images.githubusercontent.com/29807852/94602184-ea8f9780-026a-11eb-9cd9-7d7854f8da93.png)

Excerpt from the code on this page. Does anyone have any idea why this is happening?

![page2](https://user-images.githubusercontent.com/29807852/94607770-bddf7e00-0272-11eb-8556-5c32079ab3f4.png)
![page4](https://user-images.githubusercontent.com/29807852/94607983-17e04380-0273-11eb-8d82-bb9d0954204d.png)

 [✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/matheus/Documents/Dev/flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/matheus/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/matheus/Android/Sdk
    • Java binary at: /home/matheus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/matheus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.5)
    • Android Studio at /home/matheus/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/matheus/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.6911.18
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see

```
```

</details>

**Comment by darshankawar** [comment]
Hi @MattheusOliveira,
By deformed, do you mean some widgets are not rendered properly on iOS ?
Can you please provide a minimal complete reproducible code sample involving those widgets that shows the issue ? The screenshot you shared won't help, please provide the sample in text format that we can copy paste and run in IDE. Also provide the iOS devices on which you are experiencing this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
