### ISSUE TITLE
ui_thread crashes in --debug mode on Pixel

### ISSUE THREAD

**Issue by adlr** [flutter/flutter#6693]
## Steps to Reproduce

Using Pixel phone

flutter create myapp
cd myapp
flutter run

## Logs

Run your application with `flutter run` and attach all the log output.

Installing build/app.apk...                          3860ms
Timed out while waiting for a debug connection.
Error launching DevFS loader on Pixel.
wall time: flutter run completed in 28 seconds

logcat:

11-03 12:43:52.280  1192 11167 I ActivityManager: START u0 {act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x30000000 cmp=com.yourcompany.myapp/org.
domokit.sky.shell.SkyActivity (has extras)} from uid 2000 on display 0
11-03 12:43:52.289  1192 11167 D QCOM PowerHAL: LAUNCH HINT: ON
11-03 12:43:52.297  1192 11167 I QCOM PowerHAL: Activity launch hint handled
11-03 12:43:52.309  1192 11167 I ActivityManager: Start proc 7980:com.yourcompany.myapp/u0a216 for activity com.yourcompany.myapp/org.domokit.sky.shell.SkyActivity
11-03 12:43:52.311  7969  7969 D AndroidRuntime: Shutting down VM
11-03 12:43:52.327  7980  7980 I art     : Late-enabling -Xcheck:jni
11-03 12:43:52.345  7980  7987 E art     : Failed writing handshake bytes (-1 of 14): Broken pipe
11-03 12:43:52.345  7980  7987 I art     : Debugger is no longer active
11-03 12:43:52.345  7980  7987 I art     : Starting a blocking GC Instrumentation
11-03 12:43:52.346  1192  4864 I WindowManager: Failed to capture screenshot of Token{57adb49 ActivityRecord{2fd2d50 u0 com.google.android.apps.inbox/com.google.an
droid.apps.bigtop.activities.MainActivity t2860}} appWin=Window{552145f u0 com.google.android.apps.inbox/com.google.android.apps.bigtop.activities.MainActivity} dr
awState=4
11-03 12:43:52.386  7980  7980 I cr.library_loader: Time to load native libraries: 7 ms (timestamps 9718-9725)
11-03 12:43:52.386  7980  7980 I cr.library_loader: Expected native library version number "", actual native library version number ""
11-03 12:43:52.466  7980  7980 E ApkAssets: Error while loading asset assets/icudtl.dat: java.io.FileNotFoundException: This file can not be opened as a file descr
iptor; it is probably compressed
11-03 12:43:52.470  7980  7980 I Adreno  : QUALCOMM build                   : a5b4970, If5818605d9
11-03 12:43:52.470  7980  7980 I Adreno  : Build Date                       : 10/12/16
11-03 12:43:52.470  7980  7980 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
11-03 12:43:52.470  7980  7980 I Adreno  : Local Branch                     : N24D
11-03 12:43:52.470  7980  7980 I Adreno  : Remote Branch                    : 
11-03 12:43:52.470  7980  7980 I Adreno  : Remote Branch                    : 
11-03 12:43:52.470  7980  7980 I Adreno  : Reconstruct Branch               : 
11-03 12:43:52.533  7980  8004 I OpenGLRenderer: Initialized EGL, version 1.4
11-03 12:43:52.533  7980  8004 D OpenGLRenderer: Swap behavior 1
11-03 12:43:52.582  2695  5899 I Icing   : Indexing 6BE5355CF8E17C178F29EC639D363295AAC56949 from com.google.android.googlequicksearchbox
11-03 12:43:52.630  7980  8002 F libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xca1586e4 in tid 8002 (ui_thread)
11-03 12:43:52.631   557   557 W         : debuggerd: handling request: pid=7980 uid=10216 gid=10216 tid=8002
11-03 12:43:52.706  8008  8008 E         : debuggerd: process stopped due to unexpected signal 27
11-03 12:43:52.708  1192  8009 W ActivityManager:   Force finishing activity com.yourcompany.myapp/org.domokit.sky.shell.SkyActivity

Run `flutter analyze` and attach any output of that command also.

Analyzing lib/main.dart...
No analyzer warnings! (ran in 10.8s)

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Linux, channel master)
    • Flutter at /mnt/ext/adlr/flutter/flutter
    • Framework revision 594c4f998a (6 hours ago), 2016-11-03 15:19:57
    • Engine revision 16077d474b
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/adlr/Android/Sdk
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Pixel • FA6890301609 • android-arm • Android 7.1.1 (API 25)

**Comment by eseidelGoogle** [comment]
The ui_thread crashing would suggest it's Dart or c++ engine code crashing, not Skia or GPU bindings I think.  This may or may not be specfic to pixel.

Ideally we'd be able to get a Tombstone file showing the full crash.  They're located at `/data/tombstones/tombstone_01`, etc. if written, but it doesn't look from the logs like this crash wrote one for whatever reason.

**Comment by eseidelGoogle** [comment]
Working on getting our hands on a Pixel to debug.  We have a couple still in the mail.  https://github.com/flutter/flutter/issues/6492 is likely not the same issue, but also seems to be pixel-specific and might end up related.

**Comment by adlr** [comment]
Cool. Also, doing the release build did work, fwiw.

**Comment by eseidelGoogle** [comment]
Oh, odd.  So this is a debug-only, pixel-only crash.  --release uses Dart's AOT (Ahead of Time) compilation mode instead of JIT (which i used for --debug).  I wonder if the Dart JIT crashes on a Pixel.  Will have to see when we have one in our hands.  Thanks again for the report!

This actually probably is the same as  #6492 , but I think I'm going to dupe to this one since it has more info.

**Comment by eseidelGoogle** [comment]
FYI @a-siva.
