### ISSUE TITLE
Confining a cursor

### ISSUE THREAD

**Issue by YmiYugy** [flutter/flutter#66937]
## Use case
Limiting a movement of a draggable.

## Proposal
Have a Widget that confines a cursor to its borders.

**Comment by darshankawar** [comment]
@YmiYugy 
Please provide more details on this proposal. What issues / limitations are you facing and how would the proposal would resolve that ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
