### ISSUE TITLE
Firebase initialize

### ISSUE THREAD

**Issue by Aristide99** [flutter/flutter#66945]
PlatformException(firebase_core, java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.firebase.firestore.ListenerRegistration.remove()' on a null object reference, null, null

**Comment by darshankawar** [comment]
@Aristide99 
This is Firebase related issue which has separate repo for tracking. Please open this issue here:
https://github.com/FirebaseExtended/flutterfire/issues.
