### ISSUE TITLE
url_launcher cannot run with flutter SDK >= 2.7 < 3.0.0

### ISSUE THREAD

**Issue by duyjack** [flutter/flutter#66949]
url_launcher >=3.0.0 requires Flutter SDK version >=0.1.4 <2.0.0 and url_launcher <3.0.0 requires SDK version <2.0.0, url_launcher is forbidden

**Comment by darshankawar** [comment]
@duyjack 
Please provide `flutter doctor -v` and `pubspec.yaml`.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
