### ISSUE TITLE
[add2app]platformview block issue;  content of which is clipped though position is correct when used in a Flutter Module on iOS

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#66968]
when add one module using platformview to ios app viewcontroller; when the viewcontroller.view is not positioned at top,left (0,0), then platform view will be hidden; 

both flutter 1.20 stable and 1.22 beta has such problem, reproducible with following code;

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children:[MyWebView()],
    );
  }
}

class MyWebView extends StatelessWidget {
  Widget build(BuildContext context) {
    var webView=WebView(
      initialUrl: 'https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen?tab=vc-swift-tab',
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        //  _controller.complete(webViewController);
      },
      onPageFinished: (String url) {
        print('Page finished loading');
      },
    );
    print("${webView.userAgent} ");
    return webView;
  }
}
```

```
@objc func showFlutter() {
      let flutterEngine = (UIApplication.shared.delegate as! AppDelegate).flutterEngine
      let flutterViewController =
          FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
        flutterViewController.view.backgroundColor = UIColor.gray
        flutterViewController.view.frame = CGRect(x: 50, y: 50, width: 1200, height: 900)
        self.view.addSubview(flutterViewController.view)
    }
```
![image](https://user-images.githubusercontent.com/3118573/94676089-5ba77b80-034d-11eb-9e3d-5e71b3106fee.png)

from the picture, we can't left part of the page is hidden

**Comment by wanjm** [comment]
![example picture](https://user-images.githubusercontent.com/3118573/94676256-a0331700-034d-11eb-9850-b54df59f409e.png)

**Comment by wanjm** [comment]
[Demo.zip](https://github.com/flutter/flutter/files/5304892/Demo.zip)
all demo code

**Comment by KiritoBeater** [comment]
Same problem , still exist in master
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.428, on Mac OS X 10.15.6 19G73 x86_64, locale
    zh-Hans-CN)
    • Flutter version 1.22.0-10.0.pre.428 at /Users/liyang/Library/Developer/flutter
    • Framework revision a06f385145 (9 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/liyang/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

```

**Comment by TahaTesser** [comment]
Hi @wanjm 
Thanks for filing this issue,  I can reproduce it  using demo from https://github.com/flutter/flutter/issues/66968#issuecomment-701314681

### Screenshots
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-09-30 at 18 08 46](https://user-images.githubusercontent.com/48603081/94686218-251b3200-0348-11eb-9f73-b974fb1e5780.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-30 at 18 05 50](https://user-images.githubusercontent.com/48603081/94686323-4845e180-0348-11eb-959f-fc7ee7a99994.png)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      568097D9-D464-4E46-8CC4-A73D85236C41 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details>

**Comment by wanjm** [comment]
@TahaTesser 
the position of PlatformView is correct, the content is clipped; so change the name to "content of PlatformView is clipped though position is correct when used in a Flutter Module on iOS

as there are many add-to-app usage of flutter, so it is a block issue for release of PlatformView and will block many IOS developers; so I think the priority should be server to trigger more people pay attention to it;

is there any developer involved. it is urgent for me now.  we chose to use flutter to  rewrite our project for ten month. but we plan to deploy it, we found we are blocked by #66260 which crash in android; and this one which blocked IOS; 
so we are totally blocked by flutter;

could you please help me to follow this. I need it resolved as soon as possible;

thanks

**Comment by wanjm** [comment]
it is delight to see the stable announce of platformview, but if we use partical screen platformview, then we will come accross this problem. or is there any workaround?

**Comment by wanjm** [comment]
is there any update? I think this is a block issue for the release of PlatformView

**Comment by Gavinpub** [comment]
How about this issue?  I see this issue too.., it's also block my project.   Any workaround ? Thanks @TahaTesser @ianloic @anaisbetts

**Comment by wanjm** [comment]
there is no such problem in 1.17 stable; but exists in 1.20 and 1.22; 
I hope it can be fixed soon, as it is introduced in recently stable versions;

**Comment by wanjm** [comment]
this bug is fixed in stable 1.22.4 as no one take care of it;

**Comment by wanjm** [comment]
sorry, this is not fixed, please reopen it.

**Comment by chinmaygarde** [comment]
@blasten @xster  This looks like an issue with the mutator stack entries not being applied to platform views.

**Comment by cyanglaz** [comment]
> the position of PlatformView is correct, the content is clipped; so change the name to "content of PlatformView is clipped though position is correct when used in a Flutter Module on iOS
> 

It looks like the offset of FlutterViewController.view is (50,50) in the example code above. And since the platform view is a subview of `FlutterViewController.view`.  The position of the PlatformView looks correct to me. And it seems like the issue is actually that the PlatformView's offset is wrong.
