### ISSUE TITLE
firebase Notification in flutter error

### ISSUE THREAD

**Issue by choudhryr723** [flutter/flutter#66970]
`<Plugin project :firebase_core_web not found. Please update settings.gradle. Plugin project :location_web not found. Please update settings.gradle. e: /Users/apple/Documents/Developer/arrow_mob/android/app/src/main/kotlin/com/rayz/arrow/application.kt: (16, 48): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected  FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:compileDebugKotlin'. > Compilation error. See log for more details  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 12s Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by choudhryr723** [comment]
plz solve this.

**Comment by Abhishek01039** [comment]
please refer this
https://stackoverflow.com/questions/43848845/errorexecution-failed-for-task-appcompiledebugkotlin-compilation-error and https://github.com/flutter/flutter/issues/49419.
Thanks

**Comment by Abhishek01039** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/2599

**Comment by darshankawar** [comment]
@choudhryr723 
Firebase related issues are tracked [here](https://github.com/FirebaseExtended/flutterfire/issues/).
Please open this issue in above linked repo.
Closing from here.
