### ISSUE TITLE
SwitchListTile and CheckboxListTile cannot be styled as a ListTile, missing shape parameter

### ISSUE THREAD

**Issue by talamaska** [flutter/flutter#66982]
## Trying to round corners of the SwitchTileList and CheckboxListTile  

There is a missing parameter for adding shape. I can't make the tiles in a Drawer look the same.
I also tried to wrap the whole SwitchListTile with ClipRRect without success,

## Proposal

I would imagine that exposing the shape parameter of ListTile would do the job. Most of the props are already forwarded to ListTile like dense, selected, contentPadding etc.

**Comment by darshankawar** [comment]
Leaving this for reference : custom shape to ListTile was added in this [issue](https://github.com/flutter/flutter/issues/57730).

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue.

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR, PTAL whenever you get some time :)
