### ISSUE TITLE
Regression in worst_frame_build_time_millis	cubic_bezier_perf__e2e_summary.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66986]
https://flutter-flutter-perf.skia.org/e/?begin=1600827934&end=1601429824&keys=X197f56aeb2671ed26940c2a2de56e74d&requestType=0&xbaroffset=21704

Pretty clear signal at https://github.com/flutter/flutter/pull/66743. Looks to me like a test change --- so we should likely accept this one, right? Marking lower-priority as a result.

/cc @liyuqian

**Comment by liyuqian** [comment]
#66743 seems to be a very small and innocent change which shouldn't affect this benchmark... I [zoomed out the time a little][1] and see a similar regression before https://github.com/flutter/flutter/issues/66130 that has the similar level of regression as this one. I agree that this is of lower priority, and we may want to have someone to try to reproduce this locally to make sure that it's not some noisy results from infra changes.

[1]: https://flutter-flutter-perf.skia.org/e/?begin=1599070267&end=1601429824&keys=X197f56aeb2671ed26940c2a2de56e74d&requestType=0&xbaroffset=21704

**Comment by chinmaygarde** [comment]
@liyuqian This looks bimodal. Are you able to dedicate some time to reproduce this locally. Either way, I don't think this is severe enough for a P2. Please revise the priority if you disagree.
![Screen Shot 2020-10-05 at 10 37 14 AM](https://user-images.githubusercontent.com/44085/95113253-0675bc00-06f7-11eb-8d79-887771599ac1.png)

**Comment by kf6gpe** [comment]
This has recovered since 19 October. Closing. 
https://flutter-flutter-perf.skia.org/e/?begin=1602565416&end=1605551441&queries=test%3Dcubic_bezier_perf__e2e_summary&requestType=0
