### ISSUE TITLE
Disable "Assertion Failed" dialog in unit-test harnesses on Windows.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#66998]
When unit-tests trip on non-test assertions on Windows, they tend to show dialogs like the following:

![Microsoft_Visual_C_Runtime_Library_9_30_2020_11_08_13_AM](https://user-images.githubusercontent.com/44085/94734454-1ddf2e80-031e-11eb-8294-64e7cde190ea.png)

These dialogs tend to suspend the process and in the absence of interactive input on bots, the tests eventually time out instead of failing.

These dialogs can [apparently be disabled](https://stackoverflow.com/questions/13943665/how-can-i-disable-the-debug-assertion-dialog-on-windows/31611163#31611163). The command line Dart embedder also disables the same by calling [`Platform::Initialize`](https://github.com/dart-lang/sdk/blob/master/runtime/bin/platform_win.cc#L34). Flutter does not call  this method because it hijacks signal handlers that user installed crash reporting solutions may depend on. But, on unit-tests harnesses this is not a concern.

When disabling the dialog, the following subtleties must be accounted for:
* `Platform::Initialize` if used from dart-lang/sdk, must not be used in the engine. Instead, it must be explicitly set in [`run_all_unittests.cc`](https://github.com/flutter/engine/blob/572c343568f8ad95d42f7393df2ccf81627fb1e7/testing/run_all_unittests.cc#L39). This will avoid the signal handler hijacking detailed above.
* The suppression of the alert dialog must occur early enough the assertions during static initialization are accounted for. That is, main is probably too late.

**Comment by dnfield** [comment]
We want this in run_all_unittests.cc right?  Not in tester_main, which is for flutter_test, which doesn't seem to have this problem.

**Comment by chinmaygarde** [comment]
You are correct I edited my comment at the same time you added yours :)
