### ISSUE TITLE
Global enable/disable of tooltips in Flutter apps and provide API control over widget tooltips

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#66993]
## Use case

As Flutter is entering more and more into both the desktop and web arena the usage and presence of tooltips via mouse hover is more obvious than on long press on device apps. To ensure that tooltips never get in the way or become a nuisance, some improvements on their presence should be considered.

Tooltips provide nice guidance for new users to applications on web and desktop applications. However, as users get more used to an application it is a good practice to in the app provide a user/app settings that allows the user to turn off the tooltips. 

Tooltips may get in the way and bothersome when you are familiar with an application, being able to turn them off when no longer desired increases the user experience. 

It would be very useful for such a use case scenario if tooltips could be enabled/disabled on a MaterialApp level and if SDK widgets always included a control for it as well, including easy API control over the actual tooltip string(s). Currently many SDK widgets do not offer any capability to turn off built in tooltips and they provide limited control over their tooltip strings.

## Proposal App tooltip enable/disable

Provide a setting for Material(/Cupertino/Widget) apps that can be used to disable tooltips for all SDK Widgets used in the app that implement tooltips.

For example:

```dart
MaterialApp(
  title: 'Demo',
  useTooltips: true
  home: MyStatefulWidget(),
);
```

If some platforms support enabling/disabling tooltips in the platform (now or will in the future), then certainly consider having it as an enum with platform, on, off values instead, similar to the theme mode. For example:

```dart
enum Tooltips {platform, on, off}`
```

Could default to `Tooltips.on` for backwards compatibility.

```dart
MaterialApp(
  title: 'Demo',
  useTooltips: Tooltips.on
  home: MyStatefulWidget(),
);
```

## Widget tooltip control

When Flutter SDK widgets implement tooltips, please ensure that such widgets always includes an API for enabling/disabling its tooltips.  Widgets that implement tooltips should always also include an API that can be used to set the tooltip string to a value that differs from its default tooltip string(s).

### Case examples

The following two issues are example where the lack of tooltip APIs has been reproted to be an issue:

1. https://github.com/flutter/flutter/issues/60418 "PopupMenuButton has no option remove tooltip"
2. https://github.com/flutter/flutter/issues/71049 "BottomNavigationBar has no option remove tooltip or change the tooltip from its icon label [Web] [Desktop]"

---

The `BottomNavigationBarItem` case is just one example case, there might be more Widgets with similar tooltip issues on web and desktop.

## Update 22.11.2020

Removed the 2nd part and instead added specific reported cases as examples where the lack of API to control the tooltips is reported as an issue.

----

<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[√] Flutter (Channel beta, 1.22.0-12.3.pre, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.22.0-12.3.pre at C:\Users\mryds\fvm\versions\beta
    • Framework revision d408d302e2 (22 hours ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 192.7402

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.63

• No issues found!

```
</details>

**Comment by rydmike** [comment]
@mariamhas That it is "impossible" to get rid of the tooltips on Web with the newer API on the BottomNavigationBar is a bit of an issue. We always try to provide an option for 'advanced' users of our web/desktop apps to turn of tooltips entirely if they so prefer. Similar issues might exist on other widgets too, but this was a case where we run into the limitation.

I also thought that tooltips enable/disable on an app level would be a nice addition to the SDK so I added a rough proposal for it. Naturally it needs support in all SDK widgets that implement tooltips to become feasible.
Just improving the tooltip situation on BottomNavigationBar is trivial, and can be a step on the path, but does not fully address the need to be able to turn on/off all tooltips in an app.

**Comment by rydmike** [comment]
@gspencergoog 

If it helps with keeping things clearer and separating concerns, I could add (split out) a separate issue about the `BottomNavigationBar` that I used as a case example for the rationale of the general tooltip enable/disable proposal. I could then update this issue to be just about topic #1 and have #2 as separate more short term actionable issue.

Just thinking it might make sense to split this out for this particular problem widget case, from the more general better design around tooltips topic, that I think will also be useful and beneficial for both Web and Desktop platforms going forward,

That the new `BottomNavigationBar` when you use the newer `BottomNavigationBarItem` API property `label` on web and desktop apps on hover always shows a tooltip label that is identical to the icon label (when one is used), is imo an issue. Showing tooltips that are identical to something that is already on the screen does not offer any additional value, it actually quickly becomes a nuisance. 

Not sure, but there might be more widgets with similar issue on Web usage, but this one at least happened to be the first one that I came across and it started with the newer API that added the tooltips when using `label` instead of `title` that is being deprecated.

cc: @mariamhas

**Comment by CNMathon** [comment]
I had this problem too. What I can do is just use old `title` API, but it is not a good way to resolve it. Because `title` API should be deprecated.

**Comment by CNMathon** [comment]
And I got tooltips when I long press on back button of Navigator, too.

**Comment by markusaksli-nc** [comment]
I think a more systematic approach makes sense so per-widget issues like https://github.com/flutter/flutter/issues/60418 should be closed (I haven't looked around for more of them).

> Is there any way we can disable display of the tooltips visually, but still continue to provide the semantics that they provide?

Tried adding a dirty `if (widget.hide ?? false) return;` below here
https://github.com/flutter/flutter/blob/a44f3732d09cd1dc5f7dfa9f44fed63491e15972/packages/flutter/lib/src/material/tooltip.dart#L431
and it works, semantics remains in the debug view and the tooltip doesn't show.

**Comment by rydmike** [comment]
Hi @gspencergoog, thanks for the ping. 

I just had a look at the PR, it solves the problem elegantly.

Thanks @markusaksli-nc for this nice implementation.

We certainly use tooltips too, but we like to provide users with an easy way to turn them off once they are familiar with the application and feel they no longer need them, or are useful to them for accessibility reasons. I agree that keeping the semantics they provide, like here, is appropriate. This feature makes it straight forward to add this capability to applications.

Thank you 😃 ! Closing this issue.
