### ISSUE TITLE
alarm manager reschedule issue

### ISSUE THREAD

**Issue by aidooyaw1992** [flutter/flutter#67004]
i have a function that gets current location but it doesnt work after restart

void runBackgroundTask() async {
  print("RUNNING BACKGROUND TASK");
  WidgetsFlutterBinding.ensureInitialized();
  final document = await path.getApplicationDocumentsDirectory();
  print(document.path);
  var loc = await getCurrentPosition();
  print(loc);
}

initAlarm()async{
await AndroidAlarmManager.periodic(
            const Duration(seconds: 5),
            taskId,
            runBackgroundTask,
            rescheduleOnReboot: true,
          );
}

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/66959
