### ISSUE TITLE
after warm flutter engine first animation is absent

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#67008]
https://github.com/Alexufo/test_r
I run code in Studio 4.0.1

start project and press button 3.

Did you see animation navigation "in" to page2? I see only animation "out" (back).
If you will do it twice (press button 3 again) you will see animation "in" and "out". But first animation after flutter start is absent.

=
[√] Flutter (Channel master, 1.22.0-10.0.pre.417, on Microsoft Windows [Version 10.0.18362.1082], locale ru-RU)
    • Flutter version 1.22.0-10.0.pre.417 at C:\flutter
    • Framework revision e605b7c225 (25 hours ago), 2020-09-29 22:51:21 +0200
    • Engine revision a6a6fd163b
    • Dart version 2.11.0 (build 2.11.0-177.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Salo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\Salo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

**Comment by darshankawar** [comment]
@Alexufo 
Tried your code sample on Samsung S10+ device and see an `in` animation upon navigation everytime, ie, when I tapped on button at first attempt and during subsequent attempts. I noticed similar behavior.

[67008.mp4.zip](https://github.com/flutter/flutter/files/5310658/67008.mp4.zip)

Can you provide a video of the behavior you are seeing and what should be the expected result ?
Thanks.

**Comment by Alexufo** [comment]
After "ocr Result" message I press button 3. 
[2020_10_01_15_03_08.zip](https://github.com/flutter/flutter/files/5311893/2020_10_01_15_03_08.zip)

I press button and except first atempt all works as expected

Mi a2 lite

**Comment by darshankawar** [comment]
@Alexufo 
Tried to master version (1.22.0-10.0.pre.405) and saw expected animation at first and after that, ie, next screen opens with `in` animation.

[67008.mov.zip](https://github.com/flutter/flutter/files/5312119/67008.mov.zip)

Tested on Pixel 3 (Android 10) emulator.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.22.0-10.0.pre.405 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9d7bdb5903 (2 days ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Since I am unable to replicate the issue on devices I tried and it may not be related to Flutter, I am going ahead and closing it.
If you disagree, write in comments and I'll reopen.
Thanks.
