### ISSUE TITLE
[web] Safari loads blank page

### ISSUE THREAD

**Issue by guveniscan** [flutter/flutter#67007]
My small web app works fine on chrome but on safari it loads blank page. The problem occurs in both mobile and desktop Safari on release mode and while debugging. The console output looks like below in debug mode on desktop safari:

<img width="1271" alt="Skärmavbild 2020-09-30 kl  22 51 20" src="https://user-images.githubusercontent.com/3617820/94738295-7f7bb900-036f-11eb-86fe-8a3d7fcf8b44.png">

I'm on beta channel currently but it happens on dev as well
Flutter 1.22.0-12.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (26 hours ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

Is there any way to further debug this issue, Safari dev console doesn't look as helpful as Chrome's?

**Comment by darshankawar** [comment]
@guveniscan 
Please provide a minimal complete code sample that shows the issue. Also how are you running on safari ? Copy pasting the localhost on safari browser ?
Thanks.

**Comment by guveniscan** [comment]
@darshankawar I found out where the bug was, the project is both for mobile and web. An my main function looked like below. SystemChrome.setPreferredOrientations was breaking it for Safari but not for Firefox or Chrome. 

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
   SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
       .then((_) {
    runApp(new MyApp());
   });

  SharedPrefsManager.sharedInstance
      .getSelectedAccount();
}
```

Fixed it with a conditional around it
