### ISSUE TITLE
google_maps_flutter v1.0.0 not working

### ISSUE THREAD

**Issue by Milkessa-Oljira** [flutter/flutter#67016]
when trying to depend on google_maps_flutter the following error message gets thrown on the pub output:

Because [PROJECT_NAME] depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.
pub get failed (1; Because [PROJECT_NAME] depends on google_maps_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.)
exit code 1

Any help Please!

**Comment by marcosmko** [comment]
As it says, you should use flutter sdk version v1.22 > (ahead of stable version).

If you really want to use the `google_maps_flutter v1.0.0`, you can upgrade your flutter by running `flutter version 1.22` on CLI.

If you want to keep using the stable version of flutter, then you should downgrade `google_maps_flutter` to `v0.5.33`.

**Comment by Milkessa-Oljira** [comment]
So, then why are they taking it out of developer preview if it's not ready for the stable version?

**Comment by marcosmko** [comment]
I think even though it isn't on stable channel, it doesn't mean it is not stable too.

The _unstable_ ones should be the beta, master and dev, while the tagged versions are potential candidates to be released on stable channel.

(I don't know, really).

**Comment by Mastersam07** [comment]
@Milkessa-Oljira I think there are issues with the latest plugin version updated around 6 hours ago. From the plugin pubspec.yaml, it can be seen that:

```
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"
```
- This implies that the plugin would not work for any other flutter version as even the stable version doesn't fall under that constraint.
- While there was a commit to bump the plugin to v 1.0.0, the docs still carries **Developers preview**

### Fix
Use the previous plugin version google_maps_flutter 0.5.33, see the [docs](https://pub.dev/packages/google_maps_flutter/versions/0.5.33)

**Comment by darshankawar** [comment]
@Milkessa-Oljira 
As suggested above, please use other version than `1.0.0`, as the changes have been done just few hours ago. Also see [this](https://github.com/flutter/plugins/pull/3091#issuecomment-701634385) comment which says since 1.22 is not released yet.
This plugin version should work once 1.22 is released.
Closing.
