### ISSUE TITLE
Rich Text Editor Very important！

### ISSUE THREAD

**Issue by freedemocracy** [flutter/flutter#67039]
flutter team so slothful，Haven't implemented this widget for 5 years！

**Comment by darshankawar** [comment]
Closing as duplicate of [12675](https://github.com/flutter/flutter/issues/12675)

**Comment by freedemocracy** [comment]
> 结束于[12675的副本](https://github.com/flutter/flutter/issues/12675)

Zefyr ----Not a good choice
