### ISSUE TITLE
Stream controller doesn't receive events from add() method inside await function

### ISSUE THREAD

**Issue by serpentarius-hollow** [flutter/flutter#67030]
I'm trying to fire a callback inside my await function that add an event to my controllerstream. here is the code:

```
StreamController<EventDownload> streamController = StreamController();

try {
  final data = await remoteSource.getDocument(
    loginId,
    documentType,
    onReceived: (received, total) {
      streamController.add(event.copyWith(
        documentType: documentType,
        received: received.toDouble(),
        total: total.toDouble(),
      ));
    },
  );

  if (data.documentFile != null && data.documentFile.isNotEmpty) {
    streamController.add(event.copyWith(
      isKtpFinished: true,
      dataKtp: Base64Decoder().convert(data.documentFile),
    ));
  }
} catch (err) {
  print(err);
} finally {
  streamController.close();
}
```
it seems like my streamcontroller doesn't receive the event from add() method, but when I write it like this:

```
remoteSource.getDocument(
  loginId,
  documentType,
  onReceived: (received, total) {
    streamController.add(event.copyWith(
      documentType: documentType,
      received: received.toDouble(),
      total: total.toDouble(),
    ));
  },
).then((data) {
  if (data.documentFile != null && data.documentFile.isNotEmpty) {
    streamController.add(event.copyWith(
      isKtpFinished: true,
      dataKtp: Base64Decoder().convert(data.documentFile),
    ));
  }
}).whenComplete(() => streamController.close());
```

I get the expected result. The streamcontroller received the events. What's the difference in my code there? I want to achieve the result using async/await function like in my first code for readability purpose.

**Comment by darshankawar** [comment]
@serpentarius-hollow your question is better suited for StackOverflow. Also see https://flutter.dev/community for resources, and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
