### ISSUE TITLE
Either the assertion indicates an error in the framework itself

### ISSUE THREAD

**Issue by Niroop4444** [flutter/flutter#67040]
<details><summary>Logs</summary>

```
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      Localizations.of (package:flutter/src/widgets/localizations.dart:453:12)
#3      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:73:23)
#4      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:94:4)
#5      showDialog (package:flutter/src/material/dialog.dart:934:10)
#6      _LoginScreenState.showLoaderDialog (package:dishoom/screens/authentication/login_screen.dart:483:5)
#7      _LoginScreenState.dispose (package:dishoom/screens/authentication/login_screen.dart:70:5)
#8      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#71     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#82     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#83     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1944:25)
#84     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2754:27)
#85     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2558:15)
#86     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2753:7)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:18)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#91     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#95     _invoke (dart:ui/hooks.dart:253:10)
#96     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.`
```
</details>

**Comment by pedromassangocode** [comment]
Hi @Niroop4444 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Niroop4444** [comment]
➜ flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Niroop\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Niroop\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.47.2)
    • VS Code at C:\Users\Niroop\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by Niroop4444** [comment]
➜ flutter run --verbose
[ +428 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +332 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] bbfbf1770cca2da7c82e887e4e4af910034800b6
[   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +753 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[  +28 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +92 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +121 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +227 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +353 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] stable
[ +609 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: C:\Users\Niroop\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +138 ms] List of devices attached
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +324 ms] No supported devices connected.
[  +35 ms] "flutter run" took 603ms.
[  +61 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:343:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +340 ms] ensureAnalyticsSent: 324ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

**Comment by pedromassangocode** [comment]
Hi @Niroop4444 
Please make sure you have a supported device connected before running the command.
Thank you

**Comment by Abhishek01039** [comment]
Hi @Niroop4444 
`[ +324 ms] No supported devices connected.`
your device is not connected 
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
