### ISSUE TITLE
Regression; average_abs_jerk_without_resampler_59Hzaverage_abs_jerk_without_resampler_90Hzdropped_frame_count_without_resampler_59Hzjanky_count_without_resampler_59Hzjanky_count_without_resampler_90Hz complex_layout_android__scroll_smoothness

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#67054]
See

https://flutter-flutter-perf.skia.org/e/?begin=1601418723&end=1601489750&keys=Xb4abff6ba04c1a09ce0327435d235ea6&num_commits=50&request_type=1&xbaroffset=21711

Looks like https://github.com/flutter/flutter/pull/66611, which I think is intended; it's a test change.

@CareF @liyuqian can you confirm?

Giving a relatively low priority based on my hypothesis.

**Comment by CareF** [comment]
It's intended. 
Previous zero results are because of a bug introduced by #64846, and #66611 is a bug fix. See #66608
