### ISSUE TITLE
Colors.______ API usability issues

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6706]
We saw this slight bit of friction in two UX studies.

`Colors.blue` is actually a map of blues. We saw two different participants type/code-complete `Colors.blue` and then be surprised that they then need to use the map syntax to find the right actual blue.

There's no code completion of values inside the map.

A few observations:

* Colors.blue is singular, but it's returning a collection, which is plural
* Code completion doesn't help after Colors.blue

Strawman suggestions:

* Colors.blues (make it plural)
* Enable code completion after "blues", so the user can see all the options (use an enum?)

Similar to how our icons work, code completion Icons._____ shows each option (with a pretty picture, if using Atom! :)

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
I don't have a strong opinion on this. `Colors.blue[400]` reads well ("Colors, blue 400"). `Colors.blues` does more accurately set the expectation that this is more than just one blue. I'm not sure how much that helps with people figuring out that they have to index into it like a map. I think our real benefits will come from good autocomplete and good analyzer feedback, regardless of the name.

**Comment by sethladd** [comment]
Are there options other than a map? Options like enums potentially code
complete better.

**Comment by sethladd** [comment]
Ran into this again with UXers. They got to Colors.blue and then... ??? they didn't know how to proceed.

If we can code complete the options, that makes it much easier.

Thanks!

**Comment by sethladd** [comment]
If we could code complete a const map, we might not have to change the fact that we use a map. https://github.com/dart-lang/sdk/issues/28289

But, it might be a lot quicker for just to just use an enum (or something that is code completable).

**Comment by HansMuller** [comment]
Perhaps we should reserve Colors.foo (or use Color.foo) for the ~150 CSS color names, and put them in the widgets library. The Material colors are specific to Material Design, so maybe they should be called Material.colors or MaterialColors. Like MaterialColors.red[300].

**Comment by sethladd** [comment]
If you're going to rejigger this, consider not using a Map. It doesn't code-complete :(

**Comment by HansMuller** [comment]
New proposal: The material colors are ColorSwatches and ColorSwatch is-a Color. Colors.blue would be the same const value as Colors.blue.shade400, and Colors.blue[400]. 

Color.blue would code complete to a color. So a new user would find happiness. Color.blue would also expose several shades of blue. So a new user could find enlightenment (without a Map). And Color.blue[index] would continue to exist for the sake of color shade arithmetic and because operator [] overloading.

**Comment by sethladd** [comment]
If we're going to get Colors.blue.shade400, Colors.blue.shade500, etc, then yay! That will code complete. :)

**Comment by abarth** [comment]
nit: Colors.blue should be the same hex value as Colors.blue[500]

**Comment by HansMuller** [comment]
@abarth I think you mean Colors.blue[400], I believe that's what we use for the primary color
