### ISSUE TITLE
 SwitchListTile and CheckboxListTile will need a tileColor as well

### ISSUE THREAD

**Issue by talamaska** [flutter/flutter#67063]
##  Use case
For consistent look of all the tiles in a list, specifically in drawer, but valid for other cases.
I noticed that there is a PR https://github.com/flutter/flutter/pull/63887
which adds a tileColor to the ListTile. I would use it to represent the checked state with an additional background, currently the selected boolean controls if the 2 tiles are in a selected state which applies the primary color to the text and the icons in the tile. 

## Proposal
It would be nice if the tileColor is exposed for SwitchListTile and CheckboxListTile

**Comment by pedromassangocode** [comment]
I can work on this!

**Comment by talamaska** [comment]
Btw there is also a selectedTileColor, which probably needs to be exposed as well. I didn't know when I have submitted the issue.

**Comment by talamaska** [comment]
@pedromassangocode Should I submit a separate issue for the selectedTileColor property, cause I don't see it in the merged PR?

**Comment by pedromassangocode** [comment]
That would be great. Sorry I didn't make it on that PR

**Comment by talamaska** [comment]
@pedromassangocode This is the least I can do. And thanks for the efforts.
