### ISSUE TITLE
Flutter webview plugin not working in master channel

### ISSUE THREAD

**Issue by kjawadDeveloper** [flutter/flutter#67060]
The current Flutter SDK version is 1.22.0-10.0.pre.451.

Because flutter_app_saloon depends on webview_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.
pub get failed (1; Because flutter_app_saloon depends on webview_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.)

**Comment by BeshoyMelika** [comment]
I have the same error in the beta channel

**Comment by BeshoyMelika** [comment]
I upgrade my flutter SDK and solved the issue
just run `flutter upgrade`
@kjawadDeveloper

**Comment by chuckntaylor** [comment]
Switching from dev channel to the beta channel worked for me.

**Comment by darshankawar** [comment]
@kjawadDeveloper 
The latest Master version is: `1.23.0-8.0.pre.105`. Upgrading to this version and then adding `webview_flutter: ^1.0.0` should resolve your issue.

```
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in newios...                              1.7s
Process finished with exit code 0
```

<details>
<summary>flutter doctor</summary>

```
Flutter 1.23.0-8.0.pre.105 • channel master • https://github.com/flutter/flutter.git
Framework • revision f1013e6873 (5 hours ago) • 2020-10-02 09:50:33 +0800
Engine • revision 0522ff22cc
Tools • Dart 2.11.0 (build 2.11.0-181.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-8.0.pre.105, on Mac OS X 10.15.4 19E2269 x86_64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (3 available)

• No issues found!

```

</details>

Closing, as upgrading to latest master resolves the issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by praharshbhatt** [comment]
I need to make it work on the stable channel for my production app.
I cannot switch to master.
