### ISSUE TITLE
showDateRangePicker shows the wrong keyboard on Android

### ISSUE THREAD

**Issue by hunterdowns** [flutter/flutter#67065]
## Steps to Reproduce

1. Create new default flutter app with a FloatingActionButton
2. Replace the onPressed callback for the FAB with the following:
```
        onPressed: () async {
          await showDateRangePicker(
              context: context,
              firstDate: DateTime(DateTime.now().year - 100),
          lastDate: DateTime(DateTime.now().year + 20),
          initialEntryMode: DatePickerEntryMode.input,
          initialDateRange: DateTimeRange(
          start: DateTime(
          DateTime.now().year-10, DateTime.now().month, DateTime.now().day),
          end: DateTime.now(),
          ),
          );
        },
 ```

3. Run on an Android platform (ios works fine)...I'm using a Samsung Galaxy S10
4. Try to enter the start date. 

**Expected results:** 
Keyboard shown should be able to add '/' to separate month/day/year

**Actual results:** 
Keyboard doesn't not include '/' as a key to enter...keyboard is just a number entry keyboard

If you don't delete the '/' i.e. clear the date...you can enter the date but if you start typing with the date preselected (the default behavior), you lose the '/'s and can no longer enter them because the keyboard just allows number entry and doesn't include '/'s (U.S. locale...I don't know about others)

<details>

Waiting for SM G973U1 to report its views...
Debug service listening on ws://127.0.0.1:49363/OQYttb35Aho=/ws
Syncing files to device SM G973U1...
D/ViewRootImpl@9b5ee99[MainActivity](18828): ViewPostIme pointer 0
D/ViewRootImpl@9b5ee99[MainActivity](18828): ViewPostIme pointer 1
D/InputMethodManager(18828): SSI - flag : 0 Pid : 18828 view : com.area10labs.flutterbug
D/InputMethodManager(18828): prepareNavigationBarInfo() DecorView@b60959d[MainActivity]
D/InputMethodManager(18828): getNavigationBarColor() -855310
V/InputMethodManager(18828): Starting input: tba=com.area10labs.flutterbug ic=io.flutter.plugin.editing.InputConnectionAdaptor@c7a0dd3 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(18828): startInputInner - Id : 0
I/InputMethodManager(18828): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18828): Input channel destroyed: 'ClientS', fd=90
D/InputMethodManager(18828): prepareNavigationBarInfo() DecorView@b60959d[MainActivity]
D/InputMethodManager(18828): getNavigationBarColor() -855310
D/InputMethodManager(18828): prepareNavigationBarInfo() DecorView@b60959d[MainActivity]
D/InputMethodManager(18828): getNavigationBarColor() -855310
**V/InputMethodManager(18828): Starting input: tba=com.area10labs.flutterbug ic=io.flutter.plugin.editing.InputConnectionAdaptor@9dd43c5 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false**
D/InputMethodManager(18828): startInputInner - Id : 0
I/InputMethodManager(18828): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18828): Input channel destroyed: 'ClientS', fd=91
W/IInputConnectionWrapper(18828): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(18828): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(18828): requestCursorAnchorInfo on inactive InputConnection
D/ViewRootImpl@9b5ee99[MainActivity](18828): MSG_RESIZED: frame=(0,0,1080,2280) ci=(0,112,0,876) vi=(0,112,0,876) or=1
D/ViewRootImpl@9b5ee99[MainActivity](18828): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=4 res=0x1 s={true 497497755648} ch=false
W/IInputConnectionWrapper(18828): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(18828): getSelectedText on inactive InputConnection

</details>

**Comment by darshankawar** [comment]
@hunterdowns 
There's similar open issue describing your case, [62401](https://github.com/flutter/flutter/issues/62401).
Please follow-up there for updates and any questions.
Also see [this](https://github.com/flutter/flutter/issues/64928) issue which was closed in favor of above referenced one.
Closing this as duplicate.
