### ISSUE TITLE
Icons not loading in flutter Web In Hosting #Godaddy But working perfectly in Firebase 

### ISSUE THREAD

**Issue by Awaisoop** [flutter/flutter#67077]
<img width="1440" alt="Screenshot 2020-10-02 at 12 24 02 AM" src="https://user-images.githubusercontent.com/57310043/94854228-0733f700-0446-11eb-920c-7d589b2870da.png">
**The issue which i am facing is that icon not loading in #godaddy hosting but working fine in firebase hosting if i insepct elemnt it shows some menifest error** 
if i inspect element it shows some menifest error im trying to fixed but still facing issues ...

**Comment by darshankawar** [comment]
@Awaisoop 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample. Also please elaborate on how you are hosting (configuration / setup) on external platforms such as the domain you mentioned.
Thanks.

**Comment by Awaisoop** [comment]
<img width="1440" alt="Screenshot 2020-10-02 at 8 16 49 PM" src="https://user-images.githubusercontent.com/57310043/94939911-3b61f300-04ec-11eb-8780-9997b85bf647.png">

**Comment by Awaisoop** [comment]
as per doc i build web realease then put it into godaddy hosting

**Comment by darshankawar** [comment]
@Awaisoop You'll need to provide a minimal complete reproducible code sample along with the issue that you mentioned.
Thanks.

**Comment by Awaisoop** [comment]
if you are using godaddy domain for hosting then you need to give access to .JSON files

**Comment by epomeranz** [comment]
> if you are using godaddy domain for hosting then you need to give access to .JSON files

Give access to who/what? to which JSON files? And where can we grant this access (in my IDE or firebase or Godaddy)?

Thanks for the clarification :)
