### ISSUE TITLE
Is there  an example that show how to open a url within flutter app?

### ISSUE THREAD

**Issue by lajunta** [flutter/flutter#6707]
I search a lot of time , but none works,  like this one:

```
void launchUrl(String url){
  Intent intent = new Intent()
    ..action = "android.intent.action.VIEW"
    ..url = url;
  activity.startActivity(intent);
}
```
It shows --  type 'Intent' is not loaded .

So is there an working example in current flutter version?

**Comment by abarth** [comment]
https://docs.flutter.io/flutter/services/UrlLauncher-class.html has a `launch` function that should open a URL.

**Comment by lajunta** [comment]
It works, thanks abarth.

**Comment by somelikebit** [comment]
https://pub.dartlang.org/packages/android_intent

i like this one it solved my problem.
