### ISSUE TITLE
flutter downgrade to version

### ISSUE THREAD

**Issue by pvegh** [flutter/flutter#67109]
I have 
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (3 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

when I do
~ flutter downgrade
Downgrade flutter to version 1.20.1
? [y|n]

but the previous stable is 1.20.4

It would be nice to be able to specify the version to downgrade to. Especially in cases when flutter gets it wrong, but there may be other reasons too.

**Comment by pedromassangocode** [comment]
Hi @pvegh 
Flutter does not support downgrade to a specific version. Please see the following for more info:
https://github.com/flutter/flutter/issues/63635#issuecomment-676654404

**Comment by serdarpolat** [comment]
which channel are you using?

**Comment by verscph** [comment]
Flutter Version Manager might help!

https://medium.com/better-programming/discover-flutter-flutter-version-manager-fvm-411dc2bff4b4
