### ISSUE TITLE
Share.share doesn't display text inside iOS share sheet

### ISSUE THREAD

**Issue by varundroid** [flutter/flutter#67102]
`await Share.share("Some text",
        subject: "Some Subject");`

For some reason, iOS share sheet ignoring the text. I follow the correct instructions but still can't get it to work. Any help here would be appreciated.

Thanks

**Comment by pedromassangocode** [comment]
Hi @varundroid 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
