### ISSUE TITLE
Flutter inspector api to be able to get widget properties through the flutter driver

### ISSUE THREAD

**Issue by arturk** [flutter/flutter#67113]
While testing our application we want to be able to verify widget margins on some pages. For now it has to be done manually but it would be awesome if flutter_driver would have a capability to request widget properties from flutter driver extension or from flutter inspector somehow. So within the automated tests we can check that widgets are positioned as we want.
In order to identify the widget the flutter inspector itself can have something like "Copy Path" context menu (XPath analogue but which works for flutter or uuid analogue) so this widget can be identified in code using this finder and queried for its properties.

**Comment by goderbauer** [comment]
You can get this data via FlutterDriver with the [GetDiagnosticsTree](https://master-api.flutter.dev/flutter/flutter_driver/GetDiagnosticsTree-class.html) API.
