### ISSUE TITLE
A syntax error in flutter sdk src

### ISSUE THREAD

**Issue by MarkFediashov** [flutter/flutter#67121]
Hello. Today I update a flutter sdk to 1.22 for my app. I use a LinearGradient widget on same page, but analyzer in intellj idea show a syntax error. I sure that bug in required annotation that used in constructor without '@'. Now flutter lib contain this code
const LinearGradient({
  this.begin = Alignment.centerLeft,
  this.end = Alignment.centerRight,
  required List<Color> colors,
  List<double>? stops,
  this.tileMode = TileMode.clamp,
  GradientTransform? transform,
}) : assert(begin != null),
     assert(end != null),
     assert(tileMode != null),
     super(colors: colors, stops: stops, transform: transform);

But I suggest it must be something like this

const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    @required List<Color> colors = const <Color>[],
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);

Thank you!

**Comment by pedromassangocode** [comment]
Hi @MarkFediashov 
This is not an issue with Flutter. `required` is a new keyword coming with the NNBD feature and Flutter has started migrating to use it.

This is just the analyzer complaining because it is not aware of the new keyword. You still can run your code without problems.
