### ISSUE TITLE
in_app_purchase: ^0.3.4+10 crashes when fetching product's detail from the Google Play Store

### ISSUE THREAD

**Issue by yetunnaing18121996** [flutter/flutter#67126]
I have already add billing library "com.android.billingclient:billing-ktx:3.0.0" to my gradle file , uploaded app to google play as production and defined some of my in app products in my play console. After then I start implementing the flutter code, fetching product's detail from the google play console, my app crash and I got those error messages in my log cat.

java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.test.inapppurchase/base.apk)
E/AndroidRuntime(20258): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27)
E/AndroidRuntime(20258): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49)
E/AndroidRuntime(20258): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185)
E/AndroidRuntime(20258): 	at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)

how can I solve that?
please

**Comment by pedromassangocode** [comment]
Hi @yetunnaing18121996 
I see there's an open issue (https://github.com/flutter/flutter/issues/59400) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
