### ISSUE TITLE
Unable to work on flutter -Android sdk/java error

### ISSUE THREAD

**Issue by Amz42** [flutter/flutter#67128]
Hello! I installed flutter today as guided by the documentation, but I ran into an error.
Below is the output for "flutter doctor -v" command:

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
C:\Users\MY_USERNAME>flutter doctor -v
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.0 at C:\flutter
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MY_USERNAME\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Java\jdk-13.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 13.0.1+9)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\aman gupta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
As stated by the above output. I executed `flutter doctor --android-licenses` on cmd & output was:

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
C:\Users\MY_USERNAME>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

I'm new to flutter development & also have no knowledge about Java. Please help.
Flutter & Java JDK path is all set & works fine.

Thanks! in advance.

**Comment by amanv8060** [comment]
> but I ran into an error.

What is the error ? 

For the issue related to license it is because the current sdk version is incompatible with Java version

Also for the other issue in `flutter doctor` do you have android studio installed , if no , you can download as mentioned or if the `flutter doctor` still shows that issue you could set the path to android studio 

`flutter config --android-studio-dir /path/to/android/studio`

**Comment by pablo384** [comment]
@Amz42 That's because your version of java is not right, you may not have the rigt variable sets.

Uninstall java and following these stepts in the next video:
[How to install Android Studio](https://www.youtube.com/watch?v=ZZlRs8ZNgk0)

I hope it helps ✌️

**Comment by pedromassangocode** [comment]
Hi @Amz42 
As the comments above and the output of the doctor command, please install Android Studio and try again.

**Comment by sidrao2006** [comment]
> Android Studio will download and install all required tool for Android development with Flutter.

Actually, I had to download jdk separately as even after downloading Android Studio, I was getting somewhat similar errors

**Comment by Amz42** [comment]
I've downloaded Android Studio & now I have the latest Android SDK & latest Flutter SDK. Still, the error is same after running the command `flutter doctor --android-licenses`.
I think that's the error of Java version.
Please specify the java version I'll need to download & install to work on.

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
C:\Users\MY_USERNAME>java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

C:\Users\MY_USERNAME>javac -version
javac 13.0.1

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by Amz42** [comment]
Thanks! @amanv8060, @pablo384, @pedromassangocode ,@sidrao2006 for your help. 
I found that Flutter runs smoothly with Java JDK 8, So I installed it & now everything is working fine.

**Comment by liudonghua123** [comment]
I have the same issue. The following is the console log. The errors were still exists when I switched the jdk 8,

```cmd
C:\Users\Liu.D.H>flutter upgrade                                                                                        Upgrading Flutter from D:\apps\flutter...                                                                               Checking Dart SDK version...                                                                                            Downloading Dart SDK from Flutter engine 3a73d073c8bedb678d82ee78daf05037b3a7a85e...                                    Building flutter tool...
Running pub upgrade...

Upgrading engine...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Material fonts...                                       1.2s
Downloading Android Maven dependencies...                         104.1s
Downloading android-arm-profile/windows-x64 tools...                1.1s
Downloading android-arm-release/windows-x64 tools...                1.0s
Downloading android-arm64-profile/windows-x64 tools...              1.0s
Downloading android-arm64-release/windows-x64 tools...              0.8s
Downloading android-x64-profile/windows-x64 tools...                0.8s
Downloading android-x64-release/windows-x64 tools...                0.8s
Downloading android-x86 tools...                                   11.5s
Downloading android-x64 tools...                                   14.0s
Downloading android-arm tools...                                    5.5s
Downloading android-arm-profile tools...                            3.8s
Downloading android-arm-release tools...                            2.7s
Downloading android-arm64 tools...                                  5.4s
Downloading android-arm64-profile tools...                          3.4s
Downloading android-arm64-release tools...                          2.1s
Downloading android-x64-profile tools...                            2.6s
Downloading android-x64-release tools...                            1.8s
Downloading android-x86-jit-release tools...                        3.5s
Downloading package sky_engine...                                   0.9s
Downloading flutter_patched_sdk tools...                            6.2s
Downloading flutter_patched_sdk_product tools...                    5.7s
Downloading windows-x64 tools...                                   10.6s
Downloading windows-x64/font-subset tools...                        1.2s

Flutter 1.23.0-7.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision db6e2d8aa5 (9 days ago) • 2020-09-25 06:47:03 -0400
Engine • revision 3a73d073c8
Tools • Dart 2.11.0 (build 2.11.0-161.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
[✓] Android Studio (version 4.0)
[✓] VS Code, 64-bit edition (version 1.49.2)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝


C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

C:\Users\Liu.D.H>where java
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe

C:\Users\Liu.D.H>set PATH=C:\Program Files\Java\jdk1.8.0_191\bin\;%PATH%

C:\Users\Liu.D.H>where java
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe

C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

C:\Users\Liu.D.H>
```

**Comment by oliverfunk** [comment]
Hi all.

I resolved this issue by properly configuring flutter using:
`flutter config --android-sdk=/home/oliver/Android/Sdk`
`flutter config --android-studio-dir=/usr/local/android-studio`

Obviously, set those to match where your Android SDK and Android Studio is.

You should make the `flutter doctor` checks pass for Android Studio.

I'm not exactly sure why this worked, I didn't even need to download and install a JDK (for example I can't run java from the bash shell).
Maybe it uses the java runtime used to run Android Studio (that's just my massive guess).

**Comment by mahimakaushik-oss** [comment]
I am having java version like:
C:\Users\Mahima Kaushik>java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
 and in Android studio its having 11.8.0

C:\Users\Mahima Kaushik>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
    • Flutter version 1.22.5 at C:\Users\Mahima Kaushik\flutter\flutter
    • Framework revision 7891006299 (10 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Mahima Kaushik\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Mahima Kaushik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available



can any one help me to solve error as i run command in cmd like: 

C:\Users\Mahima Kaushik>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

**Comment by liudonghua123** [comment]
Just set `JAVA_HOME` to jdk 1.8 will fix this error.

**Comment by mahimakaushik-oss** [comment]
@liudonghua123  thank you dear, it works :)

**Comment by coderfeye13** [comment]
Hi everyone I have some errors. Pls, help me!
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1083], locale tr-TR)
    • Flutter version 2.2.2 at C:\SRC\flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ffyyl\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java
      binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\ffyyl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 2 categories.
