### ISSUE TITLE
Allow --only option in doctor

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#67131]
The `flutter doctor` command currently has to be run completely even if we need to check the status for a single platform.
Moreover, this makes it difficult for people who develop for a multiple environments for need to test for a single environment which is currently having some problems

**Comment by pedromassangocode** [comment]
Hi @sidrao2006 
Can you elaborate more what is the issue in running flutter doctor "completely"?

> this makes it difficult for people who develop for a multiple environments for need to test for a single environment which is currently having some problems

I'm not sore if I understood you right but what tests are you talking about? can you elaborate more?
What are the use cases that the current command does not cover?
What is the new option for?

**Comment by sidrao2006** [comment]
`flutter doctor` runs all doctor checks. However if we need to view the result for only a single environment (eg. web), it usually takes time to check android licenses and for other platforms. This time can be saved by adding the `--only` (`-o`) option

**Comment by andrewkolos** [comment]
The `flutter` CLI tool provides a massive breadth of features, each of which incurs a maintenance burden. When considering adding new functionality, we should be confident its benefits will exceed the complexity it adds to the tool.

Keeping this in mind, my (rhetorical) question is how much time would this feature save users? How often do users run `flutter doctor`?

I imagine the vast majority of runs are done when users are setting up Flutter or are reporting an issue, both of which are not frequently occurring scenarios for most users. In my experience, `flutter doctor` never takes more than 10 seconds. If my assumptions are correct, then—for the _vast_ majority of users of `flutter doctor`—this feature would provide little value. Even if this feature would be valuable for a few users, how many of them would discover it?

As a result, while this is a valid feature request, I'm declining and closing it. Those who believe this feature would be more valuable than I think it would be are welcome to comment (or open a new issue if this one is locked).
