### ISSUE TITLE
Invalid warning "Your Flutter application is created using an older version of the Android embedding."

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#67130]
If I run `flutter pub upgrade` in a package project (a shareable package project containing only Dart code), I get this warning:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
From my understanding there is nothing to fix in a package project (there is no platform specific code).

[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.49.2)
[√] Connected device (1 available)

**Comment by pedromassangocode** [comment]
Hi @kinex 
Can you share a minimal reproducible project sample that running the command you mentioned shows that message?

**Comment by kinex** [comment]
If I delete the file `android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java` the problem seems to disappear. But the file is regenerated at some point when I clean or rebuild my project and then I have the issue again.

I also noticed the migration [documentation](https://flutter.dev/go/android-project-migration) has been updated after I updated my app project several months ago. At least the `configureFlutterEngine` override has been removed totally (it was in the doc earlier and my code still has it).

Maybe it is better that I will check my migration following the latest documentation and reopen this again if needed.

**Comment by kinex** [comment]
I fixed this by deleting manually all the generated  `GeneratedPluginRegistrant.java` files from all of my package projects. Not sure if this is related, but I also updated MainActivity.kt in the app project as follows (I had already made all other changes described [in the doccumentation](https://flutter.dev/go/android-project-migration) several months ago):
OLD:
```dart
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```
NEW:
```dart
class MainActivity: FlutterActivity() {
}
```
I have now cleaned and built my project several times and the generated files have not been restored.  I don't know why the generated file was restored once earlier.

**Comment by shpy2001** [comment]
I have same warning after upgrade Flutter from 1.20.4 to 1.22.0 . 
My project was created at Flutter 1.54

**Comment by kinex** [comment]
There is still an issue that `GeneratedPluginRegistrant.java` files are created sometimes e.g. if you run `flutter packages upgrade`. You have to always delete them manually to avoid this warning. I guess those files are not really needed as I can still build and run my app successfully even if I delete those files.

Maybe the actual issue is that Flutter generates `GeneratedPluginRegistrant.java` files unnecessarily.

**Comment by SaberHardy** [comment]
go to  --> "android/app/src/main/AndroidManifest.xml" add this "<meta-data android:name="flutterEmbedding" android:value="2" /> " under **activity** tag.
good luck.

**Comment by samrat19** [comment]
I have deleted the android and iOS folder and run `flutter create .` and if got fixed

**Comment by josh256k** [comment]
You can add this to AndroidManifest.xml under activity tag.

<meta-data
         android:name="flutterEmbedding"
         android:value="2" />
