### ISSUE TITLE
Create benchmarks that measure test failures / flakiness

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#67140]
Similar to our technical debt benchmark, it would be useful to have a continuously-updated benchmark of test failures and flakiness. These are valuable since tree closures affect every committer and stop automated rolls, causing bigger, riskier rolls when the tree re-opens.

The two benchmarks I'm proposing here are:
- **Test failures**: measure of how frequently the tree is closed due to one or more test failures (failed run and re-run) some fraction of these are flakes that failed both run and re-run. Result in immediate tree closures which are critical to avoid.
- **Test flakes**: measure of how frequently we see a test fail its run and pass its re-run. Don't result in immediate tree closure but some fraction of these fall into the failure bucket by failing twice in a row. This metric provides an indication of how badly flakes are impacting the team.

It seems like we have all the infrastructure required to collect the data we need:
- [ ] Fetch dashboard test results for last N runs prior to the current run (since we don't have complete data for the current run).
- [ ] Compute a (weighted?) average of average of red dashboard squares per commit.
- [ ] Emit the benchmark for the commit prior to the current commit (for the reasons described above)

If we wanted to translate to a dollar figure similar to the technical debt benchmark, we could take something like:

    avg_failures_per_commit * guess_of_avg_time_to_resolve_one_failed_square * some_representative_swe_pay_rate 

as the avg cost to make the head row green (re-open the tree) at any given time.

**Comment by godofredoc** [comment]
Is that different from the data in these two dashboards?

* Devicelab, https://datastudio.google.com/c/reporting/1o_27AedMBxv-sa_HE78BMWff7uhPglj9/page/dwwAB
* LUCI, https://datastudio.google.com/c/reporting/1o_27AedMBxv-sa_HE78BMWff7uhPglj9/page/JfCdB

**Comment by cbracken** [comment]
> Is that different from the data in these two dashboards?

Nope -- those are awesome! I had no idea this already existed! Thanks!

**Comment by Hixie** [comment]
Can we make those public?

**Comment by godofredoc** [comment]
\cc @CaseyHillers @keyonghan can we add this as a requirement for the PH metrics you are working on.

**Comment by CaseyHillers** [comment]
This data is okay to expose as flakiness is derived from already public information. If anyone asks we should be able to give the metrics.

There isn't an easy way to make the dashboards public since they're based on internal tools. The only option I see is adding more functionality to Cocoon to expose key metrics, and recreating the dashboards there.

We could automate weekly snapshots of the dashboards for publishing to the community, but I'm not sure where would make sense to publish those reports.

**Comment by godofredoc** [comment]
We may still need a security review before sharing, isn't data studio available to the public?

**Comment by keyonghan** [comment]
>\cc @CaseyHillers @keyonghan can we add this as a requirement for the PH metrics you are working on.

We can definitely include them in the PH. (but as @CaseyHillers  mentioned, the go/flutter-dash is for internal only)

>We may still need a security review before sharing, isn't data studio available to the public?

Yes. It is. We can create a specific report for public usage only.

**Comment by CaseyHillers** [comment]
> isn't data studio available to the public?

This is similar to why when creating Flutter design docs we use fcontrib.org. We could look into moving the dashboards to be owned by fcontrib.org, but i'm not sure if that could easily hook into the BigQuery data that lives in google.com.

**Comment by cbracken** [comment]
I may be misremembering but I think @yjbanov may have used BigQuery for public stuff (querying for usage particular Angular APIs maybe).

/cc'ed in case he has info to share.

**Comment by godofredoc** [comment]
This has been already implemented.
