### ISSUE TITLE
Not possible overrride splashFactory and highlightColor  in ButtonStyleButton

### ISSUE THREAD

**Issue by HeebeLee** [flutter/flutter#67149]
I like the TextButton introduced in 1.22, and I try to expand it into my own favorite style.
But I found that I cannot set the splashFactory, because the splashFactory parameter in _ButtonStyleState is a fixed value "InkRipple.splashFactory".
This is really boring, because I can't get rid of the click effect.

I think it should be the same as the previous Button, following the setting of Theme instead of a fixed value.

```
child: InkWell(
          ...
          splashFactory: InkRipple.splashFactory, // this.
          overlayColor: overlayColor,
          highlightColor: Colors.transparent, // and here
          ...
```

@HansMuller

**Comment by TahaTesser** [comment]
Hi @HeebeLee 
I believe this is by design, `button_style_button` follows material design guidelines
 
https://github.com/flutter/flutter/blob/a0a65fc60442285b99d179ce7923430d129819a4/packages/flutter/lib/src/material/button_style_button.dart#L356-L360

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextButton(
            style: ButtonStyle(
              backgroundColor: MaterialStateProperty.all<Color>(Colors.white),
              elevation: MaterialStateProperty.all(5),
            ),
            onPressed: () {},
            child: Text('Press here')),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.132, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.132 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5e97eed895 (71 minutes ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2
      x86_64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details> 


but I kinda understand the need to remove Splash Effect so labelling as a proposal rather than a bug

**Comment by nt4f04uNd** [comment]
This is very bad design decision. This was allowed with previous implementation of material buttons, why would you do that? Why would we have `ThemeData.splashFactory` then?  Now we cannot customize our splash colors in any way at all (I mean, we cannot even change splash color, what on earth is that)

**Comment by windrunner414** [comment]
+1 I need remove splash effect

**Comment by CalomanX** [comment]
If this is Hans Muller flutter_buttons code, there is

`splashFactory: InkRipple.splashFactory, // TODO put this in ButtonStyle`

 I thing this was one of those to things that passed to the final version or a bad decision, unless IOS development is a second class citizen. In there is kind-of unacceptable to have google's splash thing.

+1 for this...

**Comment by HansMuller** [comment]
You're (all) correct, ButtonStyle should support overriding the splash factory. Will restore that.

**Comment by HeebeLee** [comment]
Thank you for understanding.  In fact, in addition to making components
comply with standards, flexible design and matching are also very important.
