### ISSUE TITLE
Make it easy to change plugin package name

### ISSUE THREAD

**Issue by emreakcan** [flutter/flutter#67162]
Capital letters are not allowed on package names (on pub.dev) I created a plugin with capital letter package name, I couldn't publish because of that. (Wish it warned me at beginning) I spent my whole day do rename the package, please make that easy.

**Comment by Abhishek01039** [comment]
Hi @emreakcan 

https://stackoverflow.com/questions/51534616/how-to-change-package-name-in-flutter
see the accepted edited answer
it is really easy to rename package name.

Thanks

**Comment by emreakcan** [comment]
@Abhishek01039, I'm asking about plugin package name, not the app.

**Comment by TahaTesser** [comment]
Hi @emreakcan 
non-capital letter package is a standard naming convention on  https://pub.dev/ and the tool doesn't support changing package or plugin, the tool doesn't have the refracting ability so you have to change your code manually or moving your files into the newly created plugin, use Android Studio to refracted code for all classes 

Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by emreakcan** [comment]
@TahaTesser maybe it can prevent to create plugins with faulty package name?
