### ISSUE TITLE
ChoiceChips doesn't appear all text inside label,it appear only when i put mouse over the text

### ISSUE THREAD

**Issue by liodali** [flutter/flutter#67160]
hi,
i have list of group of choicechips,
i found little problem in web, that text doesn't appear all the text,it appear only when i put the mouse over the text
screenshot for the problem
![tscreenshot_from_2020-10-02_21-37-13](https://user-images.githubusercontent.com/16631886/94968943-be3d7a80-04f9-11eb-99b8-6a96f3d39714.png)

**Comment by iapicca** [comment]
@liodali if you believe this is a bug
please provide your` flutter doctor -v` and most importantly a minimal reproducible code sample
if you need help for your application I recommend to ask a question on `StackOverflow`
as indicated by the option `I want help writing my application` in the [new issues menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by liodali** [comment]
this bug exist only in chrome  because i tested in firefox and the problem is gone 
here example of code
`class MyWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _StateWIdget();
}

class _StateWIdget extends State<MyWidget> {
  bool selected1 = false;
  bool selected2 = false;
  bool selected3 = false;
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 250,
      color: Colors.grey[200],
      child: Wrap(
        children: [
          ChoiceChip(
            onSelected: (v) {
              setState(() {
                selected1 = true;
              });
            },
            selected: selected1,
            label: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 5.0),
              child: Text(
                "label_chip_1",
                style: TextStyle(
                  color: selected1 ? Colors.white : Colors.black,
                ),
              ),
            ),
            avatar: selected1 ? Icon(Icons.done) : null,
            selectedColor: Colors.green,
          ),
        ],
      ),
    );
  }
}`

**Comment by iapicca** [comment]
@liodali I'm not experiencing the issue running this [dartpad code sample](https://dartpad.dev/46f2f7083086570b337c347ac855128e) on chrome
