### ISSUE TITLE
https://flutter.io/assets-and-images/ is out of date

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6717]
Looks like it only got half-updated after my last pass at images.

For example, it still mentions AssetVendor.

**Comment by Hixie** [comment]
Also the `Asset variants` section makes no sense at all...

**Comment by Hixie** [comment]
The `Specifying assets` section should say that if you have an asset in `images/foo.png` then the name of the asset is `images/foo.png` (not just `foo.png`).

**Comment by sethladd** [comment]
Thanks for noticing and filing this!

**Comment by sethladd** [comment]
Should we just remove those sections of the doc in the meantime?

**Comment by Hixie** [comment]
I think I fixed this eventually.
