### ISSUE TITLE
[doc] BottomNavigationBarItem : Update title with label to reflect correct message. 

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#67185]
I noticed that the API documentation for [BottomNavigationBarItem](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html) is out of date.

It mentions:
> The argument `icon` should not be null and the argument `title` should not be null when used in a Material Design's BottomNavigationBar.

However, since `title` is now deprecated, shouldn't this message be revised to say `label` instead?

**Comment by Abhishek01039** [comment]
Hello @awhitford 
Thanks for opening an issue. 
I have created PR from your issue which you can check.
if you have any suggestions then please let me know
Thanks.

**Comment by darshankawar** [comment]
Although the implementation does say to use `label` instead, the concerned line could be updated.

https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html

**Comment by HansMuller** [comment]
CC @johnsonmh

**Comment by Abhishek01039** [comment]
Hi @awhitford 
now you can close the issue because PR has been merged.
Now you can check here https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html
Thanks

**Comment by awhitford** [comment]
@Abhishek01039 The [BottomNavigationBarItem](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html) doc still references `title` (deprecated) instead of `label`.
> The argument `icon` should not be null and the argument `title` should not be null when used in a Material Design's BottomNavigationBar.

This issue does not look resolved to me.
