### ISSUE TITLE
LUCI infra failure: Mac tool_tests

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#67181]
https://ci.chromium.org/p/flutter/builders/try/Mac%20tool_tests/691

It succeeded when I re-tried, so it's a flake.

**Comment by godofredoc** [comment]
This is OOM issues on mac, we are leaking processes and or memory from tests/builds

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/68322
