### ISSUE TITLE
Android: Buy consumable product from google playstore got "the item is no longer available error"

### ISSUE THREAD

**Issue by yetunnaing18121996** [flutter/flutter#67189]
I have already uploaded my test app on google play store production channel, have defined some of my in app product list and test accounts in that console also. At that time, when I try to fetch those products from google play console and showing as list in my flutter application. Although they product lists show but when I try to buy one of them, the google play store got pop up dialog and show error message like that. How can I solve that? please

![Screenshot_1601692476](https://user-images.githubusercontent.com/38392529/94981866-a7c80b00-055b-11eb-9418-7f90962e7e2d.png)

**Comment by yetunnaing18121996** [comment]
Yep. What's the problem with you @ankitbatra11 . How can I help you?

**Comment by ankitbatra11** [comment]
I am also facing "This item is not available" error message while trying to purchase an in app product through my app.

**Comment by yetunnaing18121996** [comment]
@ankitbatra11 Please make sure that 
1. Fristly, you need to generate and upload the apk  that consists of "google play billing" library for android, for flutter "in_app_purchase" library and then you need to upload the app on at least on beta or alpha channel.
2. You need to add license testers in play store account
3. You need to login that license tester account on your phone's google play store .
Have you already done those steps?

**Comment by ankitbatra11** [comment]
Will verify and come back if required.
