### ISSUE TITLE
colors in LinearGradient not working

### ISSUE THREAD

**Issue by amuchand47** [flutter/flutter#67186]
Today I have upgraded to 1.22 stable version, but **colors** is not working in **LinearGradient**.

**Comment by Andy-Python-Programmer** [comment]
Hi @amuchand47 It will be nice to have some reproducible steps. `flutter doctor` logs and a screenshot of the bug will be helpful.

**Comment by Jankeelol** [comment]
if you attempt to compile, it will run. however, this is a syntax error on flutters part I assume.

**Comment by Jankeelol** [comment]
https://github.com/flutter/flutter/pull/67127
@amuchand47 I found a link to the fix!
Happy coding!

**Comment by amuchand47** [comment]
> 
> 
> if you attempt to compile, it will run. however, this is a syntax error on flutters part I assume.

Thanks,
