### ISSUE TITLE
No longer able to use "flutter drive" to run integration tests with multiple devices attached to the host machine

### ISSUE THREAD

**Issue by weifengsonos** [flutter/flutter#67192]
Repro Steps:

1) attach an Android device to the host machine (mine is a Mac)
2) bring up an iOS simulator (mine is the "iPhone X 12.2")
3) open a terminal window and then navigate to the "module" folder in your app
4) run the command line below:

flutter attach -d "iPhone X"

5) launch your app in the iOS simulator and then invoke a Flutter UI that you want to test
6) you will see something like this in the terminal window in Step 4: 

An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:57394/SmkDaniLTTU=/

7) open another terminal window and then navigate to the "module" folder in your app
8) run your integration tests with the command line below:

flutter drive --driver=<test_file_patth> --use-existing-app=http://127.0.0.1:57394/SmkDaniLTTU=/

[Expected Result]
Integration tests should be running.

[Actual Result]
I am getting the following output instead:

Multiple devices found:
SM G950U (mobile) • 98897a445150574e5a                   • android-arm64 • Android 9 (API 28)
iPhone X (mobile) • 0DDF4B41-4E38-4B7F-BDD2-02FCC385B076 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[0]: SM G950U (98897a445150574e5a)
[1]: iPhone X (0DDF4B41-4E38-4B7F-BDD2-02FCC385B076)
Please choose one (To quit, press "q/Q"):

[Comment]
This used to work fine for us with Flutter SDK "1.19.0-4.1.pre-beta".  But it becomes broken once we upgraded to Flutter SDK "1.22.0-12.2.pre-beta".  The current workaround is just to simply make sure there is no any other device attached to the host machine.  In my case, I just unplug my Android device from Mac first before running my tests.

**Comment by darshankawar** [comment]
@weifengsonos 
I tested the scenario by adding an Android device and iPhone SE simulator. I then ran a [sample](https://flutter.dev/docs/cookbook/testing/integration/introduction) flutter driver test by using `-d` flag and specifying the device ID as below:

`flutter drive -d 5200763ebcfa861f --target=test_driver/app.dart`

which picked up the Android device and ran the test properly.

I am on latest stable (1.22.0).

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

Can you try using `-d` flag and see if it works for you ?
See a [similar](https://github.com/flutter/flutter/issues/3173) issue for reference.

**Comment by weifengsonos** [comment]
Sorry for not being clear!  Our app is actually a hybrid Flutter app, meaning only part of the app is built with Flutter (https://flutter.dev/docs/development/add-to-app).  That is why you need to perform Step 4 first to get a Flutter observatory port and then use it in the command line below:

flutter drive --driver=<test_file_patth> --use-existing-app=http://127.0.0.1:<port_from_Step_4>

**Comment by jmagman** [comment]
Does specifying the device work? 
```
flutter drive -d iPhone X --driver=<test_file_patth> --use-existing-app=http://127.0.0.1:57394/SmkDaniLTTU=/
```

**Comment by weifengsonos** [comment]
Yes, it does!  Previously we didn't need to specify "-d iPhone X" in the command above because we already did that in Step 4 to obtain a Flutter observatory port.  Is this still a regression or just the new design then?

**Comment by jmagman** [comment]
Probably not on purpose, fallout from #57349.  I'm surprised that leaving off the `-d` flag ever worked.

**Comment by tupobi** [comment]
I have a big problem that makes me headache: 
I am using the integration_test which migrate from flutter_driver, cause flutter_driver has been deprecated.
But the flutter is a module contained in native app, and i want to execute flutter ui test.
How can i uese --use-existing-app, it appears:

> Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.

As a module, how to execute cmd:

`flutter test integration_test`

or 

`flutter test integration_test --use-existing-app`

I want to attach the existing-app to make integration test.

Please help me.
thanks!

**Comment by weifengsonos** [comment]
> I have a big problem that makes me headache: I am using the integration_test which migrate from flutter_driver, cause flutter_driver has been deprecated. But the flutter is a module contained by native app, and i want to execute flutter ui test. How can i uese --use-existing-app, it appears:
> 
> > Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.
> 
> **As a module**, how to execute cmd:
> 
> `flutter test integration_test`
> 
> or
> 
> `flutter test integration_test --use-existing-app`
> 
> I want to attach the existing-app to make integration test.
> 
> The official doc doesn't help: https://flutter.dev/docs/testing/integration-tests
> 
> Please help me. Thanks very very much.

**Comment by weifengsonos** [comment]
> I have a big problem that makes me headache: I am using the integration_test which migrate from flutter_driver, cause flutter_driver has been deprecated. But the flutter is a module contained by native app, and i want to execute flutter ui test. How can i uese --use-existing-app, it appears:
> 
> > Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.
> 
> **As a module**, how to execute cmd:
> 
> `flutter test integration_test`
> 
> or
> 
> `flutter test integration_test --use-existing-app`
> 
> I want to attach the existing-app to make integration test.
> 
> The official doc doesn't help: https://flutter.dev/docs/testing/integration-tests
> 
> Please help me. Thanks very very much.

@tupobi:
To run integration tests against a Flutter module hosted in a native app, you will use the "flutter drive" command.  And also, you will need to create & open a Flutter observatory port first.  If you follow my steps described at the beginning of this post, you should be able to run your tests.  Hope that helps:-).

**Comment by AhkamKhalaaf** [comment]
@darshankawar when run flutter drive  on android emulator ,  it can not sense with connectivity ,
always say no internet connection ,using flutter 3.0.0

**Comment by darshankawar** [comment]
@AhkamKhalaaf 
Please file a new issue with all required details so that we can address it accordingly.
