### ISSUE TITLE
LinearGradient has an error. 

### ISSUE THREAD

**Issue by DanielMohammadii** [flutter/flutter#67198]
Trying to use a repo from GitHub but I get " The color parameter is not defined " ,Checking the  flutter src , there is a color par.
```
import 'package:flutter/material.dart';

class Palette {
  static const Color scaffold = Color(0xFFF0F2F5);

  static const Color facebookBlue = Color(0xFF1777F2);

  static const LinearGradient createRoomGradient = LinearGradient(
    colors: [Color(0xFF496AE1), Color(0xFFCE48B1)],
  );

  static const Color online = Color(0xFF4BCB1F);

  static const LinearGradient storyGradient = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Colors.transparent, Colors.black26],
  );
}

```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment]
Hi @DanielMohammadii 
I have not any problem 
![{EBE4920C-02BD-4ECB-B4CD-E2F8C5ED8910} png](https://user-images.githubusercontent.com/56479665/94987206-0902d500-0582-11eb-90a8-227ce1c86313.jpg)

you can see the screenshot of vs code.
I am using flutter 1.22 (stable channel)

Thanks.

**Comment by sidrao2006** [comment]
I was **NOT** able to reproduce this issue on latest master.

<details>

<summary>Logs</summary>

## `flutter run -v`
[run.log](https://github.com/flutter/flutter/files/5321349/run.log)

## Screenshot
![Screenshot](https://user-images.githubusercontent.com/66567899/94987995-c643fb80-0587-11eb-9643-ecaa835bda8a.png)

## `flutter doctor -v`

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.111, on Microsoft Windows [Version
    10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.111 at C:\Users\Aneesh\Documents\development\flutter    • Framework revision fc85492d7c (15 hours ago), 2020-10-02 11:42:02 -0700
    • Engine revision 87a10f240f
    • Dart version 2.11.0 (build 2.11.0-181.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Aneesh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)        

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\Aneesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121       
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.63        

• No issues found!
```

## Reproducible code sample
```
import 'package:flutter/material.dart';

main() => runApp(
      MaterialApp(
        home: MyHomePage(),
      ),
    );

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(decoration: BoxDecoration(
        gradient: Palette.createRoomGradient,
      ),
      ),
    );
  }
}

class Palette {
  static const Color scaffold = Color(0xFFF0F2F5);

  static const Color facebookBlue = Color(0xFF1777F2);

  static const LinearGradient createRoomGradient = LinearGradient(
    colors: [Color(0xFF496AE1), Color(0xFFCE48B1)],
  );

  static const Color online = Color(0xFF4BCB1F);

  static const LinearGradient storyGradient = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Colors.transparent, Colors.red],
  );
}
```


</details>

**Comment by andreitere** [comment]
Came here for the same issue. Seems somehow IDE related. I am using Android Studio and disabling and enabling again the Dart plugin apparently fixed the issue.

**Comment by DanielMohammadii** [comment]
@andreitere  Thank you! Andrei. So I guess the problem is the channel. Cuz for this project, I'm using Beta.Lemm check

**Comment by PixelToast** [comment]
When upgrading your Flutter version, make sure to restart your IDE or analysis server.

You shouldn't need to outright disable the Android Studio/IntelliJ Dart plugin, simply pressing the restart button in the analysis server tab should work.

See #63922

**Comment by DanTup** [comment]
I think this may be the same issue described in https://github.com/dart-lang/sdk/issues/43532. You may need to fetch packages and *then* restart the editor. If the packages have been fetched prior to the analysis server starting, then this should not occur.

**Comment by DanielMohammadii** [comment]
I changed the Flutter channel  Stable and upgrade again. now it's working
Flutter channel stable
Flutter upgrade

**Comment by darshankawar** [comment]
@DanielMohammadii 
You may try the solution as mentioned [here](https://github.com/flutter/flutter/issues/67198#issuecomment-703494279) and see if it works for you if you want to try and replicate the issue on beta, where you were getting the issue originally.
Also check [this](https://github.com/flutter/flutter/issues/67198#issuecomment-703293422) comment for reference.

I am going ahead and closing this issue for now. If you again encounter this issue on beta or think this should be kept open, please write in comments and I'll reopen.
Thanks.
