### ISSUE TITLE
[gen_I10n] Infer defaults for lack of "@{message}"

### ISSUE THREAD

**Issue by szotp** [flutter/flutter#67207]
Consider this localization file:
```json
{
    "@@locale": "en",
    "@@last_modified": "2020-10-03T09:49:55.929624",
    "cancel": "Cancel",
    "@cancel": {
        "placeholders": {},
        "description": "",
        "type": "text"
    },
}
```

The cancel metadata does not look very interesting, it does not have any placeholders, and it's clear enough that it doesn't need any description. For such simple cases it would be nice to be able to omit it completely:

```json
{
    "@@locale": "en",
    "@@last_modified": "2020-10-03T09:49:55.929624",
    "cancel": "Cancel",
}
```
But if I tried to use it, I would get error:
```
Resource attribute "@cancel" was not found. Please ensure that each resource has a corresponding @resource.
```

And code generator should just infer it. Ideally it would detect placeholders, but it's good enough if it uses the same default meta every time.

@shihaohong Does this sound good? If yes, I could try to implement this and submit PR

Related ticket: https://github.com/flutter/flutter/issues/41437

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by HansMuller** [comment]
This sounds reasonable to me, although I think it would be helpful to include a flag that allows one to require a non-empty metadata description. The metadata, assuming that it's not just empty, is supposed to be useful to translators. So apps may want to ensure that a non-empty @foo description has been provided for every message.

CC @shihaohong
