### ISSUE TITLE
Material icons seems broken in play store for my app after uploading a version on the latest stable flutter version i.e. 1.22.0

### ISSUE THREAD

**Issue by piyushbhatia891** [flutter/flutter#67201]
Material icons seem broken in the play store for my app after uploading a version on the latest stable flutter version i.e. 1.22.0.
For example. In place of the home icon, I m seeing the play icon and for the forward icon, I m seeing the battery icon. 
In the emulator its all fine, but the issue is after uploading the app to the play store.
Whereas Eva icons properly fine every where.

**Comment by sidrao2006** [comment]
Mmhh this looks wierd. Have you tried it on a real device as well?

**Comment by sidrao2006** [comment]
Also, could you post the output of `flutter doctor -v`

**Comment by piyushbhatia891** [comment]
@sidrao2006 
Output for flutter doctor looks ok. Well I suspect while switching between stable and beta versions have caused mis mapping of files. I feel thats the reason. But for now I have updated the play store version by replacing the icons with eva versions. And in next release I will test once with material icons again In alpha testing in next week. If it works well, I will close the issue and promote the release to prod or else I will share my findings.

**Comment by piyushbhatia891** [comment]
It works now. I guess while switching between the channels I didn't do flutter clean. so it messed the icons file.
So closing this issue.
