### ISSUE TITLE
[in_app_purchase] InAppPurchaseConnection not avaible

### ISSUE THREAD

**Issue by stefanoromanello** [flutter/flutter#67215]
Hi, I'm trying to use in_app_purchase in my flutter application. I've already tried RevenueCat and it is working fine but I've discovered it manage badly the refounds. 
I've tried to implement in_app_purchase by following the tutorial in the pub.dev page but I always get InAppPurchaseConnection.instance.isAvailable() false. 

If can help the instance has "purchaseUpdatedStream field with the following error 
```
error: org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_purchaseUpdatedStream' isn't defined for the class 'GooglePlayConnection'.
 - 'GooglePlayConnection' is from 'package:in_app_purchase/src/in_app_purchase/google_play_connection.dart' ('/E:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.4+10/lib/src/in_app_purchase/google_play_connection.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_purchaseUpdatedStream'.
_purchaseUpdatedStream
```

Ps: I've added InAppPurchaseConnection.enablePendingPurchases() in the main.dart, my app is signed and successfully approved in the play console.

**Comment by said017** [comment]
how do you solve this problem?

**Comment by stefanoromanello** [comment]
> how do you solve this problem?

I'm sorry but I have no clue. Strange that I haven't written here how I solved it. Most likely was a very stupid mistake...
