### ISSUE TITLE
InteractiveViewer panTo method

### ISSUE THREAD

**Issue by devteam-tchs** [flutter/flutter#67211]
## Use case

`InteractiveViewer` should support programmatically changing the current coordinates, with this you could use InteractiveViewer as a map for a game where you could center the "camera" around a player character while walking around as well as allowing you to go to a certain point on the map after panning around.

## Proposal

A new method should be added to InteractiveViewer:

`panTo` - Accepts X and Y coordinates corresponding to a point inside the `InteractiveViewer`, when called it will pan to that location with a smooth animation. The ability to disable the smooth animation would also be useful. It should also take the current scale into consideration.

**Comment by devteam-tchs** [comment]
@justinmc I noticed you are very involved in this widget so I'm tagging you in this issue.

**Comment by justinmc** [comment]
I see this issue has been closed, so maybe you've figured it out, but for posterity you can do things like this using TransformationController.  There is an example in the docs: https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/transformationController.html

It may get tricky for advanced usages though.  Let me know if you have any other suggestions.  I may expose the internal _matrixTranslate method to help make it easier to translate to specific points.

**Comment by dillibabun** [comment]
Hi @justinmc / @devteam-tchs ,

Is there any workaround to achieve. I have placed a singlechildscrollview inside interactiveviewer. I need to pan to list's relative postion. That's 10 item in the list, i have offset of the list and x coordinate to jump. I am unaware go to pan to that location. Can you help me out ?

**Comment by justinmc** [comment]
Programmatic panning can be achieved using TransformationController, see my previous comment.

I'm not sure exactly what you need based on your comment, though.  Putting a ListView, which can scroll, inside of InteractiveViewer, which can pan, could be a tricky situation.

You might want to ask on StackOverflow with some code and a full explanation.  I'm happy to take a look if you post a link.

**Comment by RomanJos** [comment]
I also wouldn't say no to a panTo function, if it could accept a zoom value too that would be perfect !
I use InteractiveViewer to display a map and I need to zoom where the user's gps is, I tried to implement a hacky solution by creating a ValueNotifier inside the controller and do the same thing when a user zoom when this value change but I believe there should be a better solution.

I also tried to write the controller.value directly inside the controller but its too complicated to calculate the left and top number for me plus there is all kind of checks inside the `_matrixTranslate()` function that would be ignored.

So yeah, if you could implement this it will be super cool 😄 !
