### ISSUE TITLE
Java (from Oracle) is not recognised by 'flutter doctor' although already installed

### ISSUE THREAD

**Issue by samiq** [flutter/flutter#6722]
## Steps to Reproduce

On a Mac Sierra laptop with Xcode, Android Studio and IntelliJ already installed, after cloning the git and running flutter doctor, Java shows as not installed, it then is prompted to download from Oracle, which I do, install and then run again and same. 

When flutter doctor is ran, a dialog is shown that says: To user the "java" command-line tool you need to install a JDK, clicking OK takes you to Oracle's page.

## Logs

N/A

## Flutter Doctor Output (with the Oracle runtime)

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/gcorrales/Projects/sdks/flutter
    • Framework revision 34fdc44b58 (19 hours ago), 2016-11-04 15:48:46
    • Engine revision 16077d474b
    • Tools Dart version 1.21.0-dev.3.0

[-] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/gcorrales/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    x No Java SDK found; you can download Java from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices

## Flutter Doctor Output (with the Apple runtime)

to fix this I had to download and install Apple's Java runtime, even though is marked as legacy, this is the result after the runtime was installed

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/gcorrales/Projects/sdks/flutter
    • Framework revision 34fdc44b58 (19 hours ago), 2016-11-04 15:48:46
    • Engine revision 16077d474b
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/gcorrales/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
Thanks for the report!
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart
is the code which looks for java installed on the system in case you're curious.

**Comment by samiq** [comment]
thanks @eseidel checking the code and the process that goes in it seems like there is space for confusion in the workflow. Apple's dialog will take you to download the java runtime not the jdk, therefore the jdk never gets installed (only the runtime, which installs as a browser plugin). I think there should be more explicit that it's the JDK what is needed and not just the runtime, what is interesting is that Android Studio and IntelliJ where both already installed and never asked for a jdk to be installed before.

**Comment by cbracken** [comment]
Fixed by #7629
