### ISSUE TITLE
Cannot build android engine on Windows host machine

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#67229]
Haven't investigated further yet. Building an android engine on a windows host, the build will stop and hang at `kernel-service:frontend_server`:

```
PS C:\Users\Jonah\engine\src>  ninja -C .\out\android_debug_unopt_arm64\
ninja: Entering directory `.\out\android_debug_unopt_arm64\'
[0/78] ACTION //third_party/dart/utils/kernel-service:frontend_server(//build/toolchain/win:clang_x64) 
```

I've let this run for 30+ minutes and it never finishes. Need to investigate what is going on.

**Comment by dnfield** [comment]
Our build rules are just messed up here. I think at one point we were blocked on difference between MSVC and Clang, but that should be less of an issue. It's likely that we just are missing a bunch of rules/dependencies for Windows builds though
