### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by mrmayurgithub** [flutter/flutter#67222]
`Can't load Kernel binary: Invalid kernel binary format version.`
I recently upgraded Flutter to version 1.22.0, but I got some errors related to a dart package that I used, so I tried to downgrade flutter by using command `flutter downgrade`, but that wasn't successful. There were 10 tries, but all failed. Now I get **Can't load Kernel binary: Invalid kernel binary format version.** this error every time I use any Flutter command....
- flutter pub get
- flutter upgrade 
- flutter
- flutter clean
- flutter downgrade
Every time it just shows **Can't load Kernel binary: Invalid kernel binary format version.**

**Comment by jonahwilliams** [comment]
To work around @mrmayurgithub  try `rm FLUTTER_ROOT/bin/cache/flutter_tools.stamp`

**Comment by mrmayurgithub** [comment]
> 
> 
> To work around @mrmayurgithub try `rm FLUTTER_ROOT/bin/cache/flutter_tools.stamp`

Entering this code is giving me this error
rm : Cannot find path 'C:\apps\notado\FLUTTER_ROOT\bin\cache\flutter_tools.stamp' because it does not exist.
Then I checked my Flutter installation directory, and there's no cache folder there, I might have deleted it accidentally while trying to fix the error.

**Comment by jonahwilliams** [comment]
`FLUTTER_ROOT` is not an actual folder, just where the root of your flutter installation is

**Comment by mrmayurgithub** [comment]
> 
> 
> `FLUTTER_ROOT` is not an actual folder, just where the root of your flutter installation is

I tried deleting flutter_tools.stamp manually from **flutter/bin/cache/**, but still nothing's happening.

**Comment by khoatd92** [comment]
Any update? Got similar issue

**Comment by khoatd92** [comment]
@mrmayurgithub did you fix this?

**Comment by khoatd92** [comment]
@jonahwilliams can you help to take a look pls?

**Comment by mrmayurgithub** [comment]
> 
> 
> @jonahwilliams can you help to take a look pls?

I tried completely replacing the flutter file downloaded from flutter's website, and it worked.

**Comment by hassanasif0423** [comment]
@mrmayurgithub  Hi Sir,
I will face this error in running the app Can't load Kernel binary: Invalid kernel binary format version.
if anyone resolved this issue kindly help me.

**Comment by Mizumaki** [comment]
@hassanasif0423  For me, [this advice](https://github.com/flutter/flutter/issues/67222#issuecomment-703127102) is enough.

> try `rm FLUTTER_ROOT/bin/cache/flutter_tools.stamp`

In my case,

```
which flutter
=> /Users/{UserName}/Applications/flutter/bin/flutter

rm /Users/{UserName}/Applications/flutter/bin/cache/flutter_tools.stamp
```

**Comment by bubnenkoff** [comment]
Same issue after install https://pub.dev/packages/dhttpd

**Comment by yvesloy** [comment]
I have the same issue too.

**Comment by mrmayurgithub** [comment]
> I have the same issue too.

I solved this issue by downloading the flutter sdk from the flutter website and replacing with the one in pc.

**Comment by yvesloy** [comment]
I fixed it now - the issue was that I had installed flutter before and flutter took parts of the old version to initialize. 
To solve it, I had to delete the old one.

**Comment by Tuigirl** [comment]
> To work around @mrmayurgithub try `rm FLUTTER_ROOT/bin/cache/flutter_tools.stamp`

worked

**Comment by ameenbadri7** [comment]
deleting the flutter_tools.stamp works.

thanks

**Comment by hoanganhtran1010** [comment]
I have the same issue because install flutter 1.x and flutter 2.0 at the same computer. Fixed by remove one.
