### ISSUE TITLE
USB Functionalities for Linux & Windows Desktop

### ISSUE THREAD

**Issue by mjafartp** [flutter/flutter#67223]
## Use case

Need to add Printing functionalities via USB esc/pos & interface to other usb devices 

## Proposal

Need a plugin or functionalities to enable USB communication like https://github.com/tessel/node-usb

**Comment by gspencergoog** [comment]
At this time, we don't have any plans to implement this plugin as a first party plugin.

This would be a great project for someone in the community to take up.

**Comment by Sunbreak** [comment]
> At this time, we don't have any plans to implement this plugin as a first party plugin.
> 
> This would be a great project for someone in the community to take up.

You mean something like https://github.com/timsneath/win32?
