### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jkhoward** [flutter/flutter#67230]
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/index.html?index=..%2F..index#4

"Once you've entered RandomWords as the name of the stateful widget, the IDE automatically updates the accompanying State class, naming it **_RandomWordState."**

Should be: "_RandomWordsState"

**Comment by christopherfujino** [comment]
This sounds like it should actually be filed against whichever IDE plugin you were using. If you were using VSCode, it would be [here](https://github.com/Dart-Code/Dart-Code/issues). If IntelliJ/Android Studio, it would be [here](https://github.com/flutter/flutter-intellij/issues).
