### ISSUE TITLE
App crashing due to memory issue IOS (ImagePicker)

### ISSUE THREAD

**Issue by Dinesh41** [flutter/flutter#67243]
> Environmental Details:
> 
> IOS version: ios13
> Iphone: 8
> 
> My code:
> `await ImagePicker.pickImage(source: ImageSource.camera);`
> 
> Description:
> In my case, its crashing randomly. I have an app where I'm adding image one by one,
> 
> Random crash scenarios
> 
> 1. While adding 250th image
> 2. While adding 350th image
> 
> Can anyone help me to solve this? I'm not getting any logs.

I found the issue. While adding each image, some garbage collection is happening. Due to that when it reached 250th image, there is no memory to access. Due to memory issue app is crashing. If we open app again, it will work till it reaches to 250 - 350 images, again it will crash due to memory issue.

Any quick solution?

_Originally posted by @Dinesh41 in https://github.com/flutter/flutter/issues/34691#issuecomment-703195506_

**Comment by darshankawar** [comment]
@Dinesh41 
Please provide `flutter doctor -v`, `flutter run --verbose` and a minimal code sample that shows the issue.
Thanks,

**Comment by Peet-A** [comment]
same issue here

**Comment by Dinesh41** [comment]
@darshankawar  https://github.com/flutter/flutter/issues/54757#issuecomment-703362583
The above method solved this issue.

**Comment by darshankawar** [comment]
@Dinesh41 
Thanks for confirming. Given your last message, I am going ahead and closing this as solved.
If you disagree, write in comments and I'll reopen.
Thanks.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
