### ISSUE TITLE
lib/Authentication/register.dart:1:8: Error: Not found: 'dart:html' import 'dart:html';

### ISSUE THREAD

**Issue by foxyharith** [flutter/flutter#67250]
Hello, i am getting this error **'lib/Authentication/register.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';**

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
Invalid depfile: C:\Users\user\Desktop\feka\.dart_tool\flutter_build\c5badfdae6d71fd83b4ca0eaef8e6c54\kernel_snapshot.d
Invalid depfile: C:\Users\user\Desktop\feka\.dart_tool\flutter_build\c5badfdae6d71fd83b4ca0eaef8e6c54\kernel_snapshot.d
lib/Authentication/register.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/flutter_windows_1.20.4-stable/flutter/packages/flutter/lib/src/foundation/_platform_web.dart:7:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/flutter_windows_1.20.4-stable/flutter/packages/flutter/lib/src/foundation/_platform_web.dart:22:41: Error: Getter not found: 'window'.
  final String navigatorPlatform = html.window.navigator.platform?.toLowerCase() ?? '';
                                        ^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only s
upports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dar
t:574:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)

#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///C:/b/s/w/ir/
cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
#7      _startIsolate.<anon
ymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handle
Message (dart:isolate-patch/isolate_patch.dart:168:12)

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter_windows_1.20.4-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter_windows_1.20.4-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
@foxyharith 
can you run 
```console
flutter upgrade -f
flutter doctor -v
flutter run -v
```
and provide the `logs` and your `doctor`

among other errors
it seems that you are using firebase in your project
```console
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
```
for firebase issue I recommend to open an issue [here](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by foxyharith** [comment]
@iapicca 
Hello dear
The issue was that in one of the dart files
there was an **import dart.html** that was not used, i removed it, and it worked 
Thank u

**Comment by iapicca** [comment]
@foxyharith 
I'm glad you fixed the issue
regardless consider upgrading to the latest stable running `flutter upgrade -f`
