### ISSUE TITLE
Getting Android license status unknown error

### ISSUE THREAD

**Issue by Abdulrahman-Falyoun** [flutter/flutter#67251]
I am trying to build an application to test the `FFI` interface and as [docs](https://flutter.dev/docs/development/platform-integration/c-interop) refers: 

Firstly, I am trying to create a new flutter app using

```
flutter create --platforms=android,ios --template=plugin native_add
```

When I hit enter, I get

> Could not find an option named "platforms".
> 
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

`flutter doctor` outputs: 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] VS Code (version 1.49.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Days ago, everything was working perfectly and the issue raised suddenly.

However, I if type ``flutter doctor --android-licenses`` I get the following error:

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

here is the ***SDK manager*** located on my pc:

[![SDK manager][2]][2]  

**Note**
 
* I have tried both Java 8 and Java 9+ (i.e. normal JDK and open JDK) both no desired outcome

* I have tried the below command and a new problem arises

`set JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'` 

  [2]: https://i.stack.imgur.com/1gaYP.png

**Comment by iapicca** [comment]
@Abdulrahman-Falyoun 
it seems you are facing several issue at the same time
before getting any further in using [dart:ffi](https://api.dart.dev/stable/2.9.2/dart-ffi/dart-ffi-library.html)

Please note that you are 2 stable versions behind,
I recommend you to run `flutter upgrade -f`

does `flutter doctor --android-licenses` fail after upgrading?

(please do not post pictures if not strictly necessary)

**Comment by Abdulrahman-Falyoun** [comment]
@iapicca 
I've already tried it, the issue is still there

**Comment by iapicca** [comment]
try these possible solutions [1](https://github.com/flutter/flutter/issues/51712#issuecomment-601720915) [2](https://github.com/flutter/flutter/issues/31116#issuecomment-593046969)

**Comment by darshankawar** [comment]
@Abdulrahman-Falyoun 
I see a similar [issue](https://github.com/flutter/flutter/issues/51670) that describes your case which has several solutions that you can try.
Can you try [this](https://github.com/flutter/flutter/issues/51670#issuecomment-592943797) solution from it and see if it works for you ?

Also checkout above listed helpful link and see if any of them work for you.
Thaks.

**Comment by Abdulrahman-Falyoun** [comment]
@darshankawar thank you, after navigating through the links I got it resolved by following:

```
Seems like latest version of Android SDK renamed the 'Android SDK tools' package into 'Android-SDK command line tools'.
 But unfortunately current stable version of the Flutter SDK (v1.12.13+hotfix.8) is not compatible with this change and it keeps showing error message.
```

So I have just installed `Android-SDK command line tools` and no issue.

**Comment by darshankawar** [comment]
Closing this as resolved per above comment.
