### ISSUE TITLE
Problem with DatePicker keyboard on Samsung

### ISSUE THREAD

**Issue by VPyskach** [flutter/flutter#67253]
When I want to enter a date in TextField, I can't find the "/" character on the open keyboard, but I need it.

**Comment by sidrao2006** [comment]
Hello @VPyskach ,
Could you please post the output of `flutter doctor -v` and a minimal reproducible code sample
Thank you!

**Comment by VPyskach** [comment]
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1082], locale uk-UA)
    • Flutter version 1.20.3 at D:\flutter\soft\flutter
    • Framework revision 216dee60c0 (5 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\VasylPyskach\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by VPyskach** [comment]
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _openDatePicker(BuildContext context) async {
    await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime.now().subtract(Duration(days: 30)),
        lastDate: DateTime.now().add(Duration(days: 30)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _openDatePicker(context);
        },
        child: Icon(Icons.date_range),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by darshankawar** [comment]
@VPyskach 
There's similar open issue describing your case, [62401](https://github.com/flutter/flutter/issues/62401).
Please follow-up there for updates and any questions.
Closing this as duplicate.
Thanks.
