### ISSUE TITLE
ImageDescriptor.encoded not returning thrown exception on await, when given corrupted image

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [flutter/flutter#67256]
I'm trying to load an image from storage to ui.Image. The following code works fine with good images. 

```code
import 'dart:ui' as ui;

Future<ui.Image> imageLoadFromDevice(String path) async {
    var fileImage = File(path);
    Uint8List imageUint8List =  await fileImage.readAsBytes();

    final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(imageUint8List);
    final ui.ImageDescriptor descriptor = await ui.ImageDescriptor.encoded(buffer);

    final ui.Codec codec = await descriptor.instantiateCodec();
    final ui.FrameInfo frameInfo = await codec.getNextFrame();
    return frameInfo.image;
}
```

When the given image is corrupted, I see in the console:
```log
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Invalid image data
E/flutter (21721): #0      _futurize (dart:ui/painting.dart:4856:5)
E/flutter (21721): #1      ImageDescriptor.encoded (dart:ui/painting.dart:4724:12)
```
This error is pointing to "ImageDescriptor.encoded". I'm trying to catch this exception above imageLoadFromDevice function, but it is never raised. As far as I understand it should be returned by ImageDescriptor.encoded future, am I wrong on this?
I have found this problem by first using decodeImageFromList, and then instantiateImageCodec, with corrupted images, that both printed "Unhandled Exception: Exception: Invalid image data", but never raised the exception for me to catch.
Can you please check if it a bug or an intended behavior? And if it is intended behavior how exceptions from ImageDescriptor.encoded should be caught?

```log
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-4.0.pre.92, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (2 available)

• No issues found!

$ flutter --version
Flutter 1.23.0-4.0.pre.92 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1fef5912cf (10 days ago) • 2020-09-23 21:37:08 -0700
Engine • revision dd35b5b659
Tools • Dart 2.10.0 (build 2.10.0-156.0.dev)

$ flutter channel
Flutter channels:
* master
  dev
  beta
  stable
```

**Comment by jonahwilliams** [comment]
It looks like `_futurize` is busted - if it receives an error synchronously it needs to rethrow synchronously, but instead it is being added to the Completer which makes this an unhandled zone exception.

**Comment by jonahwilliams** [comment]
@a-l-e-x-d-s-9 can you share an exmaple image that reproduces this problem? I'm using the following code with a file that is not an image.

```

import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/widgets.dart';

void main() async {
  try {
    await imageLoadFromDevice('lib/gallery/example_code.dart');
  } catch (err) {
    print('CAUGHT: $err');
  }
}

Future<ui.Image> imageLoadFromDevice(String path) async {
    var fileImage = File(path);
    Uint8List imageUint8List =  await fileImage.readAsBytes();

    final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(imageUint8List);
    final ui.ImageDescriptor descriptor = await ui.ImageDescriptor.encoded(buffer);

    final ui.Codec codec = await descriptor.instantiateCodec();
    final ui.FrameInfo frameInfo = await codec.getNextFrame();
    return frameInfo.image;
}
```

Running this on the windows embedding, I get `flutter: CAUGHT: Exception: Invalid image data`

**Comment by a-l-e-x-d-s-9** [comment]
@jonahwilliams thanks for your reply. I tried your code and it is catching the exception as expected. 
Apparently, I was trying to catch ImageException type of exception, because of the "Invalid image data" text, but the thrown exception is of general type.
