### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2396 pos 12:

### ISSUE THREAD

**Issue by rehamalraee** [flutter/flutter#67261]
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2396 pos 12:

always appears !!1

**Comment by sidrao2006** [comment]
Hello @rehamalraee,
Could you please post the complete error logs (`flutter run -v`) and the output of `flutter doctor -v`
Thank you!

**Comment by Andy-Python-Programmer** [comment]
https://github.com/flutter/flutter/blob/8485580bb95295e0d6fce1de7d5f3d7adaf2d680/packages/flutter/lib/src/widgets/navigator.dart#L2396

That line is just a comment 😐

**Comment by Abhishek01039** [comment]
Hi @rehamalraee 
if you are trying to give black color to `IconTheme` then please try like `Color(0xff000000)` this once.
Thanks.

**Comment by rehamalraee** [comment]
Fixed
