### ISSUE TITLE
LinearGradient not works with stable channel in v1.22.0 

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#67268]
I have used **LinearGradient** in my application, but with the latest stable release(v1.22.0), I can't use **colors**, **stops** and **transform** properties of LinearGradient and they have shown the below errors.

<img width="1037" alt="Screenshot 2020-10-04 at 7 59 04 PM" src="https://user-images.githubusercontent.com/19346074/95018250-19977600-067c-11eb-90ec-0b4b21c17892.png">

But I could see the above properties are available in LinearGradient class. And this is not detected with **flutter analyze** command too, shown this in below screenshot. However, I couldn't run my application due to the above errors.

<img width="387" alt="Screenshot 2020-10-04 at 8 24 03 PM" src="https://user-images.githubusercontent.com/19346074/95018858-d0e1bc00-067f-11eb-9fbf-cc3f5895c691.png">

I have attached the main.dart file for your reference which can be found below.

[main.dart.zip](https://github.com/flutter/flutter/files/5323430/main.dart.zip)

**Flutter doctor:**

<img width="590" alt="Screenshot 2020-10-04 at 8 30 15 PM" src="https://user-images.githubusercontent.com/19346074/95018986-71d07700-0680-11eb-8ea1-1cb4b810a8dc.png">

Kindly let me know if you need further information on this.

**Comment by sidrao2006** [comment]
Hello, could you please try restarting your ide or the dartanalyzer as mentioned in #67198.

**Comment by PixelToast** [comment]
Closing as duplicate
