### ISSUE TITLE
Flutter version 1.20.2 is showing some unexpected errors.

### ISSUE THREAD

**Issue by mrmayurgithub** [flutter/flutter#67260]
I am facing problems with flutter version 1.20.2, I recently changed my flutter version to this version,
Now I am getting unexpected errors, like 
- **Icons.home_outlined** isn't defined [but **Icons.home** is correct here]
- Similar problems with other icons too.
- And it isn't recognizing **tileColor** property in **ListTile**
![f error](https://user-images.githubusercontent.com/58694295/95012832-59993180-0659-11eb-8287-300054e4ad4c.PNG)

**Comment by sidrao2006** [comment]
Hello @mrmayurgithub ,
Could you please post the outputs of `flutter analyze` and `flutter doctor -v`
Thank you!

**Comment by mrmayurgithub** [comment]
> 
> 
> Hello @mrmayurgithub ,
> Could you please post the outputs of `flutter analyze` and `flutter doctor -v`
> Thank you!

Analyzing notado...                                                     

   info - Unused import: 'package:notado/models/user_model.dart' - lib\global\database_helper\database_helper.dart:7:8 - unused_import
   info - This function has a return type of 'FutureOr<List<Note>>', but doesn't end with a return statement - lib\global\helper\global_helper.dart:35:20 -
          missing_return
   info - This function has a return type of 'FutureOr<List<Note>>', but doesn't end with a return statement - lib\global\helper\global_helper.dart:39:20 -
          missing_return
   info - Unused import: 'package:notado/ui/screens/splash_page/splash_Screen.dart' - lib\main.dart:10:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\main.dart:15:8 - unused_import
   info - Unused import: 'package:meta/meta.dart' - lib\models\user_model.dart:1:8 - unused_import
   info - Unused import: 'package:flutter_bloc/flutter_bloc.dart' - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:6:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:7:8 - unused_import
   info - Unused import: 'package:notado/models/note_model/note_model.dart' - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:13:8 - unused_import
   info - Unused import: 'package:notado/ui/screens/add_zefyr_note/bloc/zefyr_bloc.dart' - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:14:8 - unused_import   
   info - Unused import: 'package:notado/ui/screens/home_page/bloc/home_bloc.dart' - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:15:8 - unused_import
   info - The value of the field '_showNetworkError' isn't used - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:107:8 - unused_field
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:311:10 -
          missing_return
   info - The value of the local variable 'file' isn't used - lib\ui\screens\add_zefyr_note\add_zefyr_note.dart:312:11 - unused_local_variable
   info - Unused import: 'package:notado/ui/components/note_tile.dart' - lib\ui\screens\home_page\bloc\home_bloc.dart:12:8 - unused_import
   info - Unused import: 'package:notado/ui/screens/add_zefyr_note/bloc/zefyr_bloc.dart' - lib\ui\screens\home_page\bloc\home_bloc.dart:13:8 - unused_import        
   info - Unused import: 'package:provider/provider.dart' - lib\ui\screens\home_page\bloc\home_bloc.dart:14:8 - unused_import
   info - Unused import: 'dart:ffi' - lib\ui\screens\home_page\home_screen.dart:2:8 - unused_import
   info - Unused import: 'package:flutter_gradients/flutter_gradients.dart' - lib\ui\screens\home_page\home_screen.dart:9:8 - unused_import
   info - Unused import: 'package:logger/logger.dart' - lib\ui\screens\home_page\home_screen.dart:12:8 - unused_import
   info - Unused import: 'package:notado/ui/screens/login_page/login_screen.dart' - lib\ui\screens\home_page\home_screen.dart:24:8 - unused_import
   info - The value of the field '_showNetworkError' isn't used - lib\ui\screens\home_page\home_screen.dart:54:8 - unused_field
   info - This function has a return type of 'FutureOr<bool>', but doesn't end with a return statement - lib\ui\screens\home_page\home_screen.dart:76:16 -
          missing_return
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\screens\home_page\home_screen.dart:809:50 - non_constant_identifier_names
 ** error - The named parameter 'tileColor' isn't defined - lib\ui\screens\home_page\home_screen.dart:834:53 - undefined_named_parameter
  error - The named parameter 'selectedTileColor' isn't defined - lib\ui\screens\home_page\home_screen.dart:921:53 - undefined_named_parameter**
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\screens\home_page\home_screen.dart:975:46 - non_constant_identifier_names
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\ui\screens\home_page\home_screen.dart:1099:10 - missing_return
  error - The getter 'note_rounded' isn't defined for the type 'Icons' - lib\ui\screens\home_page\home_screen.dart:1107:29 - undefined_getter
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\ui\screens\login_page\bloc\login_bloc.dart:3:8 - unused_import
   info - The declaration '_checkConnection' isn't referenced - lib\ui\screens\trash_page\trash_screen.dart:24:16 - unused_element
   info - The declaration '_onBackPressed' isn't referenced - lib\ui\screens\trash_page\trash_screen.dart:31:16 - unused_element
   info - This function has a return type of 'FutureOr<bool>', but doesn't end with a return statement - lib\ui\screens\trash_page\trash_screen.dart:31:16 -        
          missing_return
warning - The parameter 'builder' is required - lib\ui\screens\trash_page\trash_screen.dart:60:12 - missing_required_param

34 issues found. (ran in 3.0s)

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
[√] Flutter (Channel beta, 1.20.2, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\mrmay\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\mrmay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.68

• No issues found!

**Comment by AchalYash** [comment]
Did you try Invalidating Cache? I was facing similar issue with some keywords and Invalidating Cache worked for me.

**Comment by mrmayurgithub** [comment]
> 
> 
> Did you try Invalidating Cache? I was facing similar issue with some keywords and Invalidating Cache worked for me.

I tried replacing whole flutter folder with other update that I manually downloaded from the flutter website, and it worked.
