### ISSUE TITLE
ToggleButton's documentation need to be updated with renderBorder is false to remove border, rather than borderWidth is null

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#67276]
According to the [documentation](https://api.flutter.dev/flutter/material/ToggleButtons-class.html#togglebutton-borders), setting the `borderWidth` to null should remove the borders, but as [this DartPad example](https://dartpad.dev/d632c78dc60556c24e7700791a327fcf) demonstrates, this does not happen.

Looking at one of the border methods, [`_getLeadingBorderSide`](https://github.com/flutter/flutter/blob/d408d302e22179d598f467e11da5dd968dbdc9ec/packages/flutter/lib/src/material/toggle_buttons.dart#L448), it turns out I need to set `renderBorder` to `false`.

The documentation just needs to be updated to reflect this.

**Comment by AyushBherwani1998** [comment]
@GhostOfSpartan10 would you like to send a PR and make your first contribution to Flutter? Looking at the code base, 
you need to change this line
 
https://github.com/flutter/flutter/blob/d408d302e22179d598f467e11da5dd968dbdc9ec/packages/flutter/lib/src/material/toggle_buttons.dart#L147

to 
```dart 
/// To remove the border, set [renderBorder] to false. Setting [borderWidth] to
```
