### ISSUE TITLE
FBLPromises have started causing problems with iOS builds

### ISSUE THREAD

**Issue by GenixPL** [flutter/flutter#67285]
FBLPromises have started to crash iOS builds (problems with bitcode). This has started to happen with the last Xcode update. We have Apple Watch Extension in our project and have to have bitcode enabled. We had problems with it since the beginning, but now we can't fix that anyhow.

Reproduction steps:
1. Create a new Flutter app
2. Add `firebase_analytics: ^6.0.1` to pubspec, and run `flutter pub get` and `pod install`
3. Open the project in Xcode, and add Watch Extension 
4. Set `Enable bitcode` to `YES` in both Targets and Pods
Build fails with:
`'/Users/genix/Library/Developer/Xcode/DerivedData/Runner-dvhalylvikwyaogirxlqkoialkzv/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/genix/Library/Developer/Xcode/DerivedData/Runner-dvhalylvikwyaogirxlqkoialkzv/Build/Products/Debug-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64`

My doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
[✓] VS Code (version 1.49.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by ykjchen** [comment]
I think you'll need to enable bitcode for all Pod targets too. See https://github.com/google/promises/issues/159#issuecomment-703451166

**Comment by TahaTesser** [comment]
Hi @GenixPL 
Does the above [solution](https://github.com/flutter/flutter/issues/67285#issuecomment-703452066) solve your issue? 
Thank you

**Comment by GenixPL** [comment]
Thanks for the fast response,

specifying `config.build_settings['ENABLE_BITCODE'] = 'YES'` in podfile indeed fixed the problem in the case of the reproduction project, I guess some command overrides it to `NO` by default, but unfortunately in our project we had it for a long time and it was still crushing.

But in the process of trying to reproduce the problem once again, I have finally found a cause of it. Specifying `BITCODE_GENERATION_MODE` to `bitcode` in `Runner target` causes builds to fail, at least in the case of my project, and leaving it empty allows them to succeed. Probably something has changed lastly because we had that flag for a long time and it started to cause problems only recently.


I have almost no idea of how the iOS build process works, so unless you think that specifying the flag to `bitcode` shouldn't be a problem, you can close the issue.

**Comment by TahaTesser** [comment]
Hi @GenixPL 
Looking at this proposal https://github.com/flutter/flutter/issues/39356, it makes sense it `NO` by default. 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
