### ISSUE TITLE
Not able to see full error in console. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#67284]
Sorry this error isn't reproducible because I am not able to figure out yet who is causing this error. 

**Screenshot:**

![image](https://user-images.githubusercontent.com/40364434/95045990-7e39eb80-06e3-11eb-8c82-1ec7ccb37ff1.png)

**Flutter Doctor:**
```
[✓] Flutter (Channel dev, 1.23.0-7.0.pre on macOS)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
[✓] VS Code (version 1.49.0)
[✓] Connected device (4 available)

• No issues found!
```

Let me know if more information is needed.

**Comment by Abhishek01039** [comment]
Hi @iLoveDocs 
can you please try with `fluter run -v` to see the full logs?
Thanks.

**Comment by iLoveDocs** [comment]
@Abhishek01039  Not on the machine at this moment, but I know it would work. The question was why the logs are not displayed in the console.

**Comment by Abhishek01039** [comment]
@iLoveDocs Because your verbose flag`(-v)` is not there.
Android studio and vs code doesn't provide the verbose flag by default you have to configure it.
Thanks.

**Comment by darshankawar** [comment]
@iLoveDocs 
Can you purposely try to fire an exception in the log and see if you get similar logs or in full ?
Do you see all details when you run `flutter run --verbose` ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
