### ISSUE TITLE
[pigeon] provide additional detail around rules for api

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#67281]
Attention @gaaclarke 

The pigeon readme states:

4. Method declarations on the Api classes should have one argument and a return value whose types are defined in the file or be void.

This sentence probably needs to be expanded. I got to the point of raising this issue before I worked out what the sentence actually meant. 

Perhaps:

4. The method declarations MUST take only one argument and the type for that argument MUST be declared in the Api file.
5. The return type of a method declarations must be either void or return a type that is declared in the Api file.

The above statements also leave me wondering whether I can pass/return an intrinsic type such as a String.

**Comment by bsutton** [comment]
The doco may also be incorrect as it looks (based on generated code) that a method may also take zero arguments. Is this intended?

**Comment by stuartmorgan** [comment]
All of these restrictions will be obsolete shortly; @gaaclarke if this is still in the documentation in should likely be changed in your current PR.

**Comment by gaaclarke** [comment]
The requirements are listed in the documentation, the tool wasn't doing a good job of enforcing them though.  Half of these are already implemented, the parsing of multiple parameters will be fixed in https://github.com/flutter/packages/pull/428
