### ISSUE TITLE
Installation fails on Android emulators without Google APIs without a clear indication of the cause

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#6728]
Tried setting up a flutter app on my personal linux laptop, flutter run failed to start the app on this Android 24 emulator:

![image](https://cloud.githubusercontent.com/assets/14947366/20047076/8a0b96e6-a465-11e6-8bd6-94712f7183cd.png)

Changing the architecture to use Google APIs resolved this issue, but it was unclear from the errors I got that that was an appropriate resolution.  Flutter run provided no indication of the error, and I get the following cryptic output from ADB logcat:

`11-06 20:45:43.000  1246  1246 W art     : Unexpected CPU variant for X86 using defaults: x86`

Full ADB output:
http://pastebin.com/CEghLXgj

Note: this is unrelated to leafy, I'm just trying out the third party workflow.

**Comment by eseidelGoogle** [comment]
FYI @danrubel 

I'm not sure what using Google APIs vs. not means and why Flutter would fail/not with or without one or the other.

The warning from `art` looks like maybe we're packaging our x86 binary in the APK with the wrong capitalization?

**Comment by DaveShuckerow** [comment]
Google APIs I believe means compilation with or without Google Play Services, but I'm not positive.  It's one of the configuration options for CPU/ABI:

Intel Atom (x86)
Intel Atom with Google APIs (x86)

Using the second configuration works, but using the first does not.

**Comment by Hixie** [comment]
Closing as covered by https://github.com/flutter/flutter/issues/13379
