### ISSUE TITLE
Widget problem

### ISSUE THREAD

**Issue by ayesha-eng** [flutter/flutter#67297]
Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4017 pos 12: '_history.isNotEmpty': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///home/linuxlite/AndroidStudioProjects/flutter_app/lib/main.dart:5:21

**Comment by Abhishek01039** [comment]
Hi @ayesha-eng 
you are trying to pop the screen but there is not any screen there which can you pop that's why this error is coming.
see the navigation section of docs(https://flutter.dev/docs/cookbook/navigation/navigation-basics) 
Thanks.

**Comment by darshankawar** [comment]
@ayesha-eng 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
