### ISSUE TITLE
Do we have to rebuild and reinstall the app when you're restarting hot mode?

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6729]
If the engine hasn't changed, then couldn't we just use the same app as the last time? We're going to be sending all the source and assets over anyway, right?

cc @johnmccutchan

**Comment by johnmccutchan** [comment]
Yes, we only need to rebuild / reinstall in hot mode if some native code (iOS bits, Android bits, or a plugin) changed.

**Comment by jonahwilliams** [comment]
We don't currently rebuild the APK/IPA during hot restart (it sounds like we used to?). This issue is likely obsolete.
