### ISSUE TITLE
"The getter 'emulatorPath' was called on null" when calling daemon getEmulators() command

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#67293]
This came up in https://github.com/Dart-Code/Dart-Code/issues/2844#issuecomment-703092792.

When VS Code calls getEmulators(), the daemon threw this error:

```
NoSuchMethodError: The getter 'emulatorPath' was called on null.
Receiver: null
Tried calling: emulatorPath

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)\n#1      AndroidEmulators._getEmulatorAvds (package:flutter_tools/src/android/android_emulator.dart:59:45)\n#2      AndroidEmulators.emulators (package:flutter_tools/src/android/android_emulator.dart:55:43)
#3      EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart:81:41)
#4      Future.forEach.<anonymous closure> (dart:async/future.dart:512:26)
#5      Future.doWhile.<anonymous closure> (dart:async/future.dart:554:26)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1042:26)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart)
<asynchronous suspension>
#19     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart)
#20     Future.forEach.<anonymous closure> (dart:async/future.dart:512:26)
#21     Future.doWhile.<anonymous closure> (dart:async/future.dart:554:26)
#22     _rootRunUnary (dart:async/zone.da…
```

There may be something wrong with the SDK, but it shouldn't bring down this request (it's valid to not have an emulators, or only the iOS Simulator).

**Comment by DanTup** [comment]
This was a trivial fix - got a PR at https://github.com/flutter/flutter/pull/67295.

**Comment by DanTup** [comment]
Fixed by #67295.

**Comment by PaulBombay** [comment]
I have the same error "The getter 'emulatorPath' was called on null" when calling daemon getEmulators()  and i don't know what is the solution.
How can i fix this problem ??

**Comment by DanTup** [comment]
@PaulBombay the error occurs only if you do not have an Android SDK, so one way to prevent this is to make sure you have an Android SDK set up. Otherwise, you'll need to wait for the fix above to be included in a Flutter release (or switch to a channel that already has it - I suspect it's available on the `beta` channel, but not yet the `stable` channel).

**Comment by bphd** [comment]
I have aur/android-sdk installed and I get this error, I'm using Flutter 1.22.5

**Comment by DanTup** [comment]
@bphd could you post the full output of the error in the log file, and also the full output of `flutter doctor -v`? If seeing this inside VS Code, please use the **Flutter: Run Flutter Doctor** command instead of `flutter doctor -v`.

**Comment by katlehoM** [comment]
NoSuchMethodError: The getter 'emulatorPath' was called on null.
Receiver: null
Tried calling: emulatorPath this is the error im getting
