### ISSUE TITLE
Textfield behaves abnormally when Flutter Web App is loaded on some android devices running Webview on a native Android app

### ISSUE THREAD

**Issue by ashank96** [flutter/flutter#67291]
I built a flutter app and ran to on web and it works pretty smoothly.
But when I load the same webapp on an android webview, the textfield behaves abnormally in the webview.

**Expected results:** Textfield should behave normally.

**Actual results:** Text field behaves abnormally. The cursor position changes with extra spaces at the end of the text, as the text length increases.

Please refer gif:
<img src="https://user-images.githubusercontent.com/22197948/95058554-51063100-0715-11eb-8b4f-161348fe49b9.gif"  width="400" height="800" />

Flutter web app link : https://ashank96.github.io/build/web/

Android Native web-view code
```
package com.ashank.nativeflutterwebview;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.TextUtils;
import android.webkit.ValueCallback;
import android.webkit.WebChromeClient;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        webView = findViewById(R.id.webView);
        webView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url);
                return false;
            }
        });
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setVerticalScrollBarEnabled(true);
        webView.setHorizontalScrollBarEnabled(true);
        webView.loadUrl("https://ashank96.github.io/build/web/");

    }
}
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.22.0 at /Users/ashankbharati/Applications/flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ashankbharati/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • SM M315F (mobile) • RZ8N60E21VM • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @ashank96 
No issues when running in a new native on Android 10. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/95095806-259d3980-0749-11eb-9138-39dccb4c556f.gif)

Can you please try the same native app on another device with a different keyboard? it could Samsung keyboard related issue

**Comment by ashank96** [comment]
@TahaTesser 
Yeah in some devices it's working. But how to fix this for all ? 
Especially SAMSUNG devices.

**Comment by TahaTesser** [comment]
Hi @ashank96 
Thanks for the additional information

### Sample Android APK with native webview and flutter URL
[app-debug.apk.zip](https://github.com/flutter/flutter/files/5332219/app-debug.apk.zip)


@darshankawar Just tried on Samsung device running Android, it seems to be working fine as well 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/95173111-e0731900-07d5-11eb-9383-3ae13771b7d0.gif)

However, Textfield does behave abnormally on Samsung running Android 10
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/95175198-c4bd4200-07d8-11eb-8dd3-fb71cfe87c05.gif)

**Comment by ashank96** [comment]
> However, Textfield does behave abnormally on Samsung running Android 10

@TahaTesser then its an os-specific issue right ?

**Comment by TahaTesser** [comment]
Hi @ashank96 
It's device-specific since I can't reproduce.  the issue on another device running the same Android 10

**Comment by ferhatb** [comment]
@nturgut not sure if its a dup issue. It does effect web-10 customer.

**Comment by ashank96** [comment]
@ferhatb whats dup issue ?

**Comment by nturgut** [comment]
@ashank96 I don't have a duplicate issue for this case. I want to confirm you also experience this problem with webview right? Does text fields normally work for you with the Flutter Android application?

**Comment by nturgut** [comment]
One suggestion I have is using the master channel instead of the beta channel. We did improvements on the text measurement which might address this issue -> "extra spaces at the end of the text, as the text length increases."

**Comment by ashank96** [comment]
@nturgut Yes, it works fine with Flutter Android app. It also works fine on flutter webapp. 
It just does not work fine if we run the same flutter web app, in an android webview.

**Comment by ashank96** [comment]
> One suggestion I have is using the master channel instead of the beta channel. We did improvements on the text measurement which might address this issue -> "extra spaces at the end of the text, as the text length increases."

Sure will try this @nturgut. 
But in that case, I would need to take only those changes from master, as we cannot afford to overlook the stability that beta provides, by shifting fully to master, for the whole app.

**Comment by ashank96** [comment]
@nturgut Can you please let me know the file(s)/PR(s) in which the changes have been done, so that I can accommodate those changes only?

**Comment by nturgut** [comment]
Can you check with the most recent beta channel? Looks like our change also made it to the beta channel.

/cc @mdebbar is this text measurement related?

**Comment by ashank96** [comment]
@nturgut I upgraded to flutter beta latest and checked. But the issue still persists.
Can you please let me know, what all files in master channel may have this fix, I will try to make those changes and check ?

**Comment by ashank96** [comment]
@nturgut @ferhatb Can we please prioritise this? Or can you give some hints on the fix, so that I can try fixing it? Actually we have to go to production, and just this bug is a blocker. 
We don't want to change our codebase setup from flutter web, just because of this issue.

**Comment by nturgut** [comment]
@mariamhas can you evaluate the priority? This is measurement inside text field for Flutter Web App loaded as a webview. (According to the comments it's also not reproducible on every device)

**Comment by ferhatb** [comment]
@ashank96 , have you tried adding a font asset, making that font default text style for app?.  @mdebbar : could this be due to different default stylesheet for a browser on specific device?

**Comment by ashank96** [comment]
@ferhatb No I haven't. How will that help? 
Given that I am opening the fluter web app in an android native webview, where should I add the font asset ?

**Comment by ashank96** [comment]
@mdebbar @ferhatb anyway I can test this fix merged to the engine ? How do I use this engine code in latest flutter master/beta? Or is there any timeline for new engine release for the flutter repo?
Can you please help here?
I just want to confirm if the issue is actually resolved by testing it. 
TIA.

**Comment by ferhatb** [comment]
@ashank96 it first rolls into master. It should be in dev channel by next week. You can test today with master.

**Comment by ashank96** [comment]
@ferhatb the issue still persists with the latest master update too. Can we please reopen this issue ?

**Comment by mdebbar** [comment]
@ashank96 I was able to repro this issue on all browsers before (even on desktop Chrome/Firefox/Safari). But now I'm not able to reproduce it anywhere.

Please make sure you are using the master channel and update it. If you are still seeing the issue, would you mind starting a new issue with all the details (reproduction steps, code sample, flutter doctor output, etc).
