### ISSUE TITLE
flutter analyze should avoid adding duplicate files

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#673]
If you're in one of the demo app directories when you run `flutter analyze --flutter-repo`, it will include that directory twice (once because of the crawl, once because of the current directory having a package), which seems to result in duplicate errors sometimes? (The latter might be an analyzer bug.)

**Comment by sethladd** [comment]
Is this still a problem?

**Comment by sethladd** [comment]
Closing because we didn't get a response :)  We can reopen if this is still an issue.

**Comment by Hixie** [comment]
you could try it :-)

looks like it's been solved.
