### ISSUE TITLE
Got error after upgrade to Flutter 1.22.0 on Mac

### ISSUE THREAD

**Issue by husainazkas** [flutter/flutter#67301]
- AnimationController parameter has missing `vsync`

- LinearGradient parameter has missing `colors`

All of these still available on Flutter 1.22.0 Stable Channel (Windows), but missing on Mac.

Here's my `flutter doctor -v`

``` 
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.22.0 at /Users/user-pc/flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user-pc/android-sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • 90A2DC43-5E7C-4D08-93F0-C0CBC3D35556 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.```

**Comment by darshankawar** [comment]
@husainazkas 
There was similar issue describing your case, [67198](https://github.com/flutter/flutter/issues/67198).
From that issue, please see [this](https://github.com/flutter/flutter/issues/67198#issuecomment-703494279) and [this](https://github.com/flutter/flutter/issues/67198#issuecomment-703293422) comment and check if it works for you.
Thanks.

**Comment by husainazkas** [comment]
> @husainazkas
> There was similar issue describing your case, [67198](https://github.com/flutter/flutter/issues/67198).
> From that issue, please see [this](https://github.com/flutter/flutter/issues/67198#issuecomment-703494279) and [this](https://github.com/flutter/flutter/issues/67198#issuecomment-703293422) comment and check if it works for you.
> Thanks.

Thank you for your reference. I don't know how it happen, but my code was correctly worked now after I turn on back my computer today.
