### ISSUE TITLE
Flutter Web - incorrect deferred parts URIs lead to "broken" application because of browser cache.

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#67303]
## Steps to Reproduce

In case of using "import deferred as" and loadLibrary() application will be compiled as main.dart.js and some deferred parts: main.dart.js_1.part.js, main.dart.js_2.part.js, ...
In index.html main.dart.js will be referenced with autogenerated version, like:
```html
<script src="main.dart.js?v=2541470921" type="application/javascript"></script>
```
But for parts in main.dart.js the following declaration will be generated:
```js
deferredPartUris:["main.dart.js_1.part.js","main.dart.js_2.part.js"]
```
**This is wrong**, because leads to extensive caching of parts by browser, so after future redeployments main.dart.js will be loaded from new version, but parts will be loaded from browser cache as old versions, as result app will fail after loadLibrary()
The proper declaration for parts must be:
```
deferredPartUris:["main.dart.js_1.part.js?v=2541470921","main.dart.js_2.part.js?v=2541470921"]
```
That way both main.dart.js and parts will be reloaded by browser consistently when new version of app is deployed.
I have changed main.dart.js manually and it works just fine after that.

**Comment by darshankawar** [comment]
@slavap 
Please provide `flutter doctor -v` and a minimal code sample along with details on `import deferred as`. 
Can you also provide details on how to replicate the `main.dart.js` in parts as you shown above ?
Thanks.

**Comment by jonahwilliams** [comment]
@slavap this should be addressed by https://github.com/flutter/flutter/commit/84aae22c3eb0b0b7c37333ae0d23769e34534b84 , but even if you're not on that version you could make those changes to the flutter_service worker locally.

**Comment by slavap** [comment]
@darshankawar 
```
flutter doctor -v
[√] Flutter (Channel beta, 1.22.0-12.3.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-12.3.pre at c:\Programs\flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = c:\Programs\chrome-debug.bat

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.49.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

@jonahwilliams I'll try to test it with 1.23 version and let you know, thanks.

**Comment by slavap** [comment]
@jonahwilliams @darshankawar 
Tested on 1.23.0-18.1.pre
Looks like in this version all checks are occurring in service worker only, I don't see any ?v=123 added to js files.
I see that js parts are reloaded by browser when changed on web server by me, but not clearly understand how all this "magic" is actually working 😁 Would be nice to have some explanation in documentation.

**Comment by johnpryan** [comment]
https://github.com/flutter/website/issues/5165 created to add documentation for deferred loading. We could add more explanation about how this is implemented, but it sounds like this is fixed by https://github.com/flutter/flutter/commit/84aae22c3eb0b0b7c37333ae0d23769e34534b84
