### ISSUE TITLE
Avatar Circle

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#6731]
When using this widget it always say that need a child. If the child is null the app crash.
I don't know if the chid field it has to be not null or what is happening.

**Comment by eseidelGoogle** [comment]
Maybe child needs to be marked @required?

https://docs.flutter.io/flutter/material/CircleAvatar-class.html

**Comment by arcas0803** [comment]
And what widget should use? I put an input widget and flutter draws inside the avatar.

**Comment by eseidelGoogle** [comment]
Here are some examples: https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=CircleAvatar

**Comment by arcas0803** [comment]
So the only way to use this widget is with text? or we can use some icon? I already see the examples and you're always using with text.
Thanks for reply so quickly.

**Comment by Hixie** [comment]
Text, Image, Icon, whatever you want. :-)
