### ISSUE TITLE
ios32 device is down in the devicelab

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#67321]
The tests are reporting "no device found"

**Comment by dnfield** [comment]
@godofredoc @keyonghan

**Comment by jonahwilliams** [comment]
Resolved?

**Comment by dnfield** [comment]
Seems so. I reran the tests on the dashboard and they're now passing.

**Comment by godofredoc** [comment]
I didn't do anything, is this a problem related with the timeout to find devices in the flutter tool?

**Comment by godofredoc** [comment]
A few weeks ago we had to add a 10s timeout because that specific phone was very slow and not discovered within the previous 2 seconds.
