### ISSUE TITLE
Input rendering

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#6732]
The input widget fails when the device keyboard goes up. The input may have move to be visible to the user but that never happen. 
And just a question of this widget. Are there options to set the type (number, password...) and floating labels?

**Comment by eseidelGoogle** [comment]
We're in the process of re-working the input widget as we speak.  Can you be more specific as to hat you see as "fails" when the keyboard comes up?

Is this iOS or Android?  Can you provide more information about the device/OS in question?

FYI @HansMuller @mpcomplete

**Comment by mpcomplete** [comment]
You can set the keyoboard type. See https://docs.flutter.io/flutter/material/Input/keyboardType.html

Otherwise this bug sounds like https://github.com/flutter/flutter/issues/6602

**Comment by arcas0803** [comment]
Nexus 9
Android 7.0
The input stays back from the kerboard while is on focus mode, so you cant see what are yo writing.
Also i notice that the content you are writing stays above the label text.

**Comment by eseidelGoogle** [comment]
Nexus 9 is a tablet.  I suspect that we don't have landscape/tablet mode of the keyboard entirely wired up correctly yet?

**Comment by eseidelGoogle** [comment]
Could you provide a screenshot of the badness you're seeing?  `flutter screenshot` knows how to pull one for you from an attached android device.

**Comment by arcas0803** [comment]
Ok i have to screenshots:
![flutter_01](https://cloud.githubusercontent.com/assets/4893111/20069962/f600fa94-a51e-11e6-817b-c44d134a5665.png)
This is taken on a nexus 4. The input focus is on the second input just behind the keyboard.
![flutter_02](https://cloud.githubusercontent.com/assets/4893111/20070005/2486c650-a51f-11e6-92f2-5e06811f43d5.png)
 This one shows the content of the input and the label text at the same time.
I know that some people is having trouble with the gpu of this soc but i have the same problem on the nexus 9.
Thanks.

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/6733 - should correct the problem you're seeing with the input label and the input hint rendering on top of each other.
