### ISSUE TITLE
Toolbar and handles do not appear when selecting text in a TextField in Flutter 1.22

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#67329]
The toolbar when selecting text in a TextField do not show on iOS, in Flutter 1.22.

I've confirmed that `void showHandles()` from text_selection.dart gets called, but the handles never appear, nor does the toolbar.

![Simulator Screen Shot - iPhone X - 2020-10-05 at 14 36 12](https://user-images.githubusercontent.com/40898687/95118356-2bc6f200-0718-11eb-9626-20af5cac1760.png)

```

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TextSelectionHomePage(),
    );
  }
}

class TextSelectionHomePage extends StatefulWidget {
  _TextSelectionHomePageSate createState() => _TextSelectionHomePageSate();
}

class _TextSelectionHomePageSate extends State<TextSelectionHomePage> {

  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController(
      text: "This is a test that shows some odd behavior with Text Selection!"
    );

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Container(
        color: Colors.grey,
        child: Center(
          child: Container(
            color: Colors.red,
            width: 500,
            height: 600,
            child: Center(
              child: Padding(
                padding: const EdgeInsets.only(left: 20.0, right: 20.0),
                child: TextField(),
              )
            )
          )
        ),
      )
    );
  }
}

```

<details><summar>Flutter doctor</summar>

[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-12.2.pre at /Users/danny.valente/Library/flutter/1.22.0-12.2.pre-beta
    • Framework revision 2bafdc8226 (10 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

</details>

**Comment by dannyvalentesonos** [comment]
@xster Here's a regression in TextFields in 1.22. 
Thanks!

**Comment by xster** [comment]
Thanks for following up. I believe this is https://github.com/flutter/flutter/issues/66149 and should be hotfixed soon. Could you check whether this is still an issue on beta channel (where it's merged already)?

**Comment by dannyvalentesonos** [comment]
Yep, that's the same. Thanks.

**Comment by xster** [comment]
Great. Please let us know if you run into more issues.
