### ISSUE TITLE
[Web] : Text doesn't render properly

### ISSUE THREAD

**Issue by SandeepMalviya1999** [flutter/flutter#67327]
I created a new project and inserted "Raised Button" with "Text" wigets.

The text on button, "Login" is displaying as "Logi" and on mouse hover, "Login" is displayed.

**Comment by Abhishek01039** [comment]
Hi @SandeepMalviya1999 
can you please provide `flutter run -v`, `flutter doctor -v` and minimal reproduction code?
Thanks

**Comment by SandeepMalviya1999** [comment]
Please get the following details from here:

[Code](https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/main.dart)

[flutter run -v.](https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/flutter%20run%20-v.txt)

[flutter doctor -v](https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/flutter%20doctor%20-v.txt)


And to elaborate my issue. Below is the output image.

![Issue Output](https://raw.githubusercontent.com/SandeepMalviya1999/flutter_bug_report/main/button%20text.png)

And on mouse hover,

![Issue Output on Mouse Hover](https://raw.githubusercontent.com/SandeepMalviya1999/flutter_bug_report/main/button%20text%20on%20mouse%20hover.png)

**Comment by darshankawar** [comment]
@SandeepMalviya1999 
Is this on web ?

**Comment by SandeepMalviya1999** [comment]
Yes! This is on web..

**Comment by darshankawar** [comment]
@SandeepMalviya1999 
Tried on latest beta with your code sample and didn't see any issues. the button and text is rendered properly over hover.

[67237.mov.zip](https://github.com/flutter/flutter/files/5338782/67237.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0
    • Web Server (web)          • web-server                               •
      web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```

</details>

Probably it has to do something with caching.
Please try `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if you issue still persists.
If so, please provide video of the issue.
Thanks.

**Comment by SandeepMalviya1999** [comment]
I tried the command you asked for, but it didn't work.

![Video Link](https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/Flutter%20Bug%20Output%20Video.mp4) of the issue:


I tried on other laptop also, there its working fine. But this issue is constant on "Dell Insipiron 5567". Can it be related to Graphics Cards?

**Comment by SandeepMalviya1999** [comment]
I tried an sample application and hosted on firebase.

https://nearby.sandytech.co.in

Then, tried on different browsers (Mozilla, Chrome and Edge). On Edge it is working perfectly, but not on the other browser.

![Video Link](https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/output_on_different_browser.mp4) of the comparision.

**Comment by darshankawar** [comment]
@SandeepMalviya1999 
Can you try by running the app on all those browsers before hosting on firebase and see if you still get the issue ?
Thanks.

**Comment by SandeepMalviya1999** [comment]
> Yes! This is on web..

    Yeah I have tried the same but with no luck.

**Comment by SandeepMalviya1999** [comment]
Yes! I habe tried the same, but with no luck.

I opened the site on all browsers as well different laptops. On others laptop its working fine.

But on mine and my friend laptop, which are same, the issue is there on both laptop.

"Dell Inspiron 5567"

**Comment by darshankawar** [comment]
@SandeepMalviya1999 
Can you try by running this command and see if issue persists ?

`flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true`

**Comment by SandeepMalviya1999** [comment]
Yes this solves the issue. Thanks.

So, do I have to run this same command again to run app?

Or is there any fix.. so that I would be easy for me to just run..

flutter run

**Comment by darshankawar** [comment]
@SandeepMalviya1999 
Can you try by creating a new project and run `flutter run -d chrome` and see if you get similar behavior ? If so, then run the above command. If same behavior perists, please provide video of both scenarios. Probably it could be related to skia rendering.
Thanks.

**Comment by SandeepMalviya1999** [comment]
@darshankawar 
Yes! I guess it is due to skia rendering. Here is the video of both scenarios. 

https://github.com/SandeepMalviya1999/flutter_bug_report/blob/main/Flutter%20Bug%20Report.mp4

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis, since it's working on Mac, but seem to be happening on Windows per above video shared.

**Comment by TimWhiting** [comment]
I see a similar problem occasionally on my site. It cuts off whole words or the last character of the word. Sometimes it is there and sometimes not. It depends on the day / time. Randomly works as expected and randomly I see this. Accessed on mobile web with same device so it isn't a padding or margin sizing error. I can't reproduce it on demand since it is random. I tried the skia flag at some point and it wasn't even displaying text on chrome on android. Maybe I'll try the skia flag again since I know there has been updates to skia since I last tried.

**Comment by MagsMagnoli** [comment]
There is another open issue related to Firefox on Windows text issues: #61614
