### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: E:\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 2

### ISSUE THREAD

**Issue by nihalsarwar17** [flutter/flutter#67335]
## Command
```
flutter create meriPehliApp
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: E:\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 2
```

```
```
[✓] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.22.0 at E:\flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment]
@nihalsarwar17 does the file `E:\flutter\bin\cache\dart-sdk\bin\pub.bat` exist in your flutter checkout?

**Comment by jonahwilliams** [comment]
Also could you please include the full stack trace?

**Comment by nihalsarwar17** [comment]
let me see

> E:\flutter\bin\cache\dart-sdk\bin\pub.bat

it does exist but not working.unnu

**Comment by nihalsarwar17** [comment]
> @nihalsarwar17 does the file `E:\flutter\bin\cache\dart-sdk\bin\pub.bat` exist in your flutter checkout?

It does exist but not working.

**Comment by nihalsarwar17** [comment]
> Also could you please include the full stack trace?

Will soon..

**Comment by jonahwilliams** [comment]
What happens if you type `E:\flutter\bin\cache\dart-sdk\bin\pub.bat` in the command line? Does the program run or does it complain about a file not found?

**Comment by jonahwilliams** [comment]
Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.
