### ISSUE TITLE
Equivalent of FlatButton.disabledTextColor with TextButton

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#67330]
Consider the following code that specifies `disabledTextColor` for a `FlatButton`:
```dart
FlatButton.icon(
  icon: const Icon(Icons.check_box),
  label: const Text('Foo'),
  disabledTextColor: Colors.black,
  onPressed: null,
),
```

There does not seem to be a way to translate the `disabledTextColor` property to the equivalent for `TextButton`.

I figure I need to override `style`, but I can't seem to get `TextButton.styleFrom` to work, and `Theme.of(context).textButtonTheme.style` is _null_.

**Comment by darshankawar** [comment]
`disabledTextColor` property isn't supported / implemented for `TextButton.

**Comment by HansMuller** [comment]
It _is_ possible to change the TextButton's text/icon foreground for just the disabled state.  By default, TextButton uses the color scheme's `onSurface` color for the button's foreground in the disabled state (see https://api.flutter.dev/flutter/material/TextButton/defaultStyleOf.html). One can override the onSurface color's value like this:

```dart
TextButton.icon(
  style: TextButton.styleFrom(onSurface: Colors.black),
  onPressed: null,
  icon: const Icon(Icons.check_box),
  label: const Text('Foo'),
)
```
This and many other examples of how to migrate from the old button classes to the new ones can be found here:  
flutter.dev/go/material-button-migration-guide

**Comment by awhitford** [comment]
@HansMuller Your suggestion did not work for me.

Code:
```dart
            FlatButton.icon(
              icon: const Icon(Icons.check_box),
              label: const Text('FlatButton'),
              disabledTextColor: Colors.black,
              onPressed: null,
            ),
            TextButton.icon(
              icon: const Icon(Icons.check_box),
              label: const Text('TextButton'),
              style: TextButton.styleFrom(onSurface: Colors.black),
              onPressed: null,
            ),
```

Result:


<img width="149" alt="Screen Shot 2020-10-07 at 9 28 05 AM" src="https://user-images.githubusercontent.com/123887/95359906-84fd6580-087f-11eb-828d-1a7345adf911.png">

**Comment by awhitford** [comment]
I managed to get the desirable outcome with this `style` override:
```dart
          style: ButtonStyle(
            foregroundColor: MaterialStateProperty.all(Colors.black),
          ),
```
🎉

**Comment by HansMuller** [comment]
Sorry, my mistake. TextButton uses the color scheme's onSurface color with 0.38 opacity by default.

**Comment by HansMuller** [comment]
In your example, you're overriding the foregroundColor for _all_ states, not just the disabled state. Here's a link an example that should do exactly what you want: https://dartpad.dartlang.org/5974ce0b0d86e7e5ca4be04b74d2d320

```dart
TextButton.icon(
  icon: const Icon(Icons.check_box),
  label: const Text('TextButton'),
  style: ButtonStyle(
    foregroundColor: MaterialStateProperty.resolveWith<Color>(
      (Set<MaterialState> states) => states.contains(MaterialState.disabled) ? Colors.black : null,
    ),
  ),
  onPressed: null,
)
```

Sorry about the confusion, I was dashed off the initial reply without thinking.
