### ISSUE TITLE
LUCI recipe links are broken

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#67348]
LUCI recipe links are broken.

For example, https://ci.chromium.org/p/flutter/builders/try/Linux%20web_integration_tests/2873 points to https://source.chromium.org/search?q=file:recipes%2Fflutter%2Fflutter_drone.py, which shows:

<img width="575" alt="Screen Shot 2020-10-05 at 1 55 53 PM" src="https://user-images.githubusercontent.com/211513/95131184-7e051480-0712-11eb-973a-3349bf7c7edd.png">

**Comment by yusufm** [comment]
This was fixed by https://github.com/flutter/flutter/issues/69927
