### ISSUE TITLE
Potential logical operator bug introduced in recent PR

### ISSUE THREAD

**Issue by flar** [flutter/flutter#67343]
I was looking at some code in platform_view.dart and saw what I think is a bug. Here is the line of code.

https://github.com/flutter/flutter/blob/3a00c4e73cd2d706204e612aa4adf36420f130ca/packages/flutter/lib/src/rendering/platform_view.dart#L208

The precedence of logical operators would result in this test being `(width_test) || (height_test && clip_none_test)` but I believe that the intention was probably `(width_test || height_test) && (clip_none_test)`.

Here is the relevant PR: https://github.com/flutter/flutter/pull/65910

**Comment by flar** [comment]
The previous PR was reviewed by @goderbauer and @liyuqian

**Comment by darshankawar** [comment]
Leaving [this](https://github.com/flutter/flutter/pull/65910#discussion_r499855547) here for reference that indicates the logical operation need to be fixed.

**Comment by goderbauer** [comment]
@liyuqian Can you fix this?

**Comment by liyuqian** [comment]
Sure, see https://github.com/flutter/flutter/pull/67446
