### ISSUE TITLE
Dartdoc for Column widget seems to talk about Row

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#6734]
The DartDoc starts out:

> A widget that lays out its children in a vertical array.
>
> Each child of a **Row** widget is either flexible or inflexible. The **Row** first lays out its inflexible children and subtracts their total **width** to determine how much free space is available. The **Row** then divides this free space among the flexible children in a ratio...

## Steps to Reproduce

Look at https://docs.flutter.io/flutter/material/Column-class.html

## Logs

N/A

## Flutter Doctor

N/A

**Comment by Hixie** [comment]
Woops, my bad.
