### ISSUE TITLE
Keyboard stays up after flutter app goes to background on some Android devices

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#67341]
With this very simple flutter app example, on a Huawei MediaPad running Android 9, and a Huawei Mate 20 running Android 10, the keyboard stays open after the flutter app goes to the background if a TextField has focus.

See the video attached.

```

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TextSelectionHomePage(),
    );
  }
}

class TextSelectionHomePage extends StatefulWidget {
  _TextSelectionHomePageSate createState() => _TextSelectionHomePageSate();
}

class _TextSelectionHomePageSate extends State<TextSelectionHomePage> {

  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController(
      text: "This is a test that shows some odd behavior with Text Selection!"
    );

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Container(
        color: Colors.grey,
        child: Center(
          child: Container(
            color: Colors.red,
            width: 500,
            height: 600,
            child: Center(
              child: Padding(
                padding: const EdgeInsets.only(left: 20.0, right: 20.0),
                child: TextField(),
              )
            )
          )
        ),
      )
    );
  }
}

```

<details><summary>Flutter doctor</summary>

[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
• Flutter version 1.22.0-12.2.pre at /Users/danny.valente/Library/flutter/1.22.0-12.2.pre-beta
• Framework revision 2bafdc8 (10 days ago), 2020-09-25 12:48:22 -0700
• Engine revision f763b5b9b9
• Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/danny.valente/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.4.1, Build version 11E503a
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 47.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

</details>

**Comment by dannyvalentesonos** [comment]
[keyboard_issue.zip](https://github/flutter/flutter/files/5329841/keyboard_issue.zip)

@xster here's another regression in 1.22. Thanks!

**Comment by dannyvalentesonos** [comment]
@xster looks like this issue was somehow related to #67329 as well, because with the latest beta 1.22.0-12.3.pre, we can no longer reproduce this. I think this can be closed too.

**Comment by xster** [comment]
Yes, I strongly suspect it's the same PR. Thanks for checking!
