### ISSUE TITLE
Flutter 1.22 .0 doesn't define "@required" but "require" instead, which is breaking the APIs

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#67366]
I updated to Flutter 1.22 (from 1.20.4) and now several of my widgets are shown with error marks in IntelliJ IDEA, saying the parameters they use don't exist.

For example:

![image](https://user-images.githubusercontent.com/8120472/95145572-fc34db80-0751-11eb-9c53-09073780ef28.png)
![image](https://user-images.githubusercontent.com/8120472/95145585-07880700-0752-11eb-8f22-7bcf00952683.png)

So I entered the `LinearGradient` source code and this what I see:

![image](https://user-images.githubusercontent.com/8120472/95145632-27b7c600-0752-11eb-907c-0f2b372c2c00.png)

It changed to `required List<Color> colors,`, when it was supposed to be `@required`.

Dart Analysis isn't much happy about it:

![image](https://user-images.githubusercontent.com/8120472/95145687-52a21a00-0752-11eb-8318-2309922b3093.png)

I am wondering how this got changed and pushed into the stable channel. Is this a new Dart feature that was being tested and it's incompatible with this version?

I have problems with `LinearGradient`, `RadialGradient`, `AnimationController`, but I guess there are others out there as well, I just happen to not use them.

I suggest a post-mortem on this.

**Comment by Calamity210** [comment]
required is actually recently became a keyword, but this issue is one multiple others have faced. It tends to be fixed by either restarting your IDE or analysis server.
#63922

**Comment by feinstein** [comment]
I remember reading something about it a while ago, but I couldn't find it on Google, so I assumed I was remembering it wrong about `required`.

The dart team should have added it to the dart 2.10 release blog post.

**Comment by Andy-Python-Programmer** [comment]
This is null safety related change. So the `@required` annotation will be a keyword `required`

**Comment by feinstein** [comment]
Yep, those were the first places I went to verify if things changed.

**Comment by PixelToast** [comment]
NNBD features aren't stable yet, which is why it was not included in release notes or in related documentation

Restarting your analysis server or IDE should solve the errors, see #63922

**Comment by feinstein** [comment]
So, NNBD isn't stable yet.... But the code is being pushed into the stable branch, and there are known errors that are deliberately not mentioned on any release notes?! 

I would have expected the opposite. The release notes and blog posts should include a message about how this and that restarting the IDE or Analysis Server should fix it.

**Comment by feinstein** [comment]
So, NNBD isn't stable yet.... But the code is being pushed into the stable branch, and there are known errors that are deliberately not mentioned on any release notes?! 

I would have expected the opposite. The release notes and blog posts should include a message about how this and that restarting the IDE or Analysis Server should fix it.

**Comment by feinstein** [comment]
So, NNBD isn't stable yet.... But the code is being pushed into the stable branch, and there are known errors that are deliberately not mentioned on any release notes?! 

I would have expected the opposite. The release notes and blog posts should include a message about how this and that restarting the IDE or Analysis Server should fix it.

**Comment by PixelToast** [comment]
Sorry for not being clear, Flutter opts-in to the NNBD preview through its analysis options (the `non-nullable` experiment) so it's use of the required keyword is perfectly valid in the current stable

The underlying issue here is that IDEs do not restart the analyzer when the SDK version changes, causing otherwise valid code to be temporarily linted under the wrong version of dart

Some more information:
* https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3
* https://github.com/dart-lang/samples/tree/master/null_safety/calculate_lix
* https://github.com/flutter/flutter-intellij/issues/760

**Comment by feinstein** [comment]
Thanks, I am aware of the NNBD experiment (and quite excited about it tbh), I just think there should be a more public notice about how updating can generate temporary errors.

I almost rolled back my Flutter version because of this, and stopped all my work to provide a good issue report here, thinking this was something new, because I couldn't find any information on it.

**Comment by TZ-TimZhang** [comment]
modify "environment" in pubspec.yaml  to sdk: ">=2.10.0 <3.0.0" then pub get

**Comment by burekas7** [comment]
Hi,
I have a question regarding the 'required' keyword.
Why does when I want to use it, it doesn't recognize it? so instead I still need to use as '@required'.
But when I go into some widgets I do see it without the '@'.
So what is the difference, why does some other widgets can use it as 'required' but I can't?

Thanks.

**Comment by feinstein** [comment]
Because it's a feature that will be available when you enable NNBD.

**Comment by burekas7** [comment]
> Because it's a feature that will be available when you enable NNBD.

What do you mean by "enable", is it a setting or do you mean by define a variable as NNBD?

And how does I see some widgets that defined some of the constructor args as required while the variable is defined as Nullable (?)

**Comment by PixelToast** [comment]
Hi @burekas7

For information on how to enable and use null safety see https://flutter.dev/docs/null-safety, as this issue is closed you will have a better chance of getting help at one of our communities at https://flutter.dev/community

**Comment by feinstein** [comment]
It's a beta feature of the language for now, so you have to give a special flag for the compiler/VM/IDE, just search about Dart and null safety.

**Comment by dokumanx** [comment]
I faced the same issue. Currently I am working on null-safety. I cannot no longer use **@required**. Instead, it became **required** keyword. See: 

`class Test {
  static void test({int a = 2, required int b}) {
    print(a);
    print(b);
  }
}
`
