### ISSUE TITLE
Flutter desktop error message [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(242)] 

### ISSUE THREAD

**Issue by kiranojhanp** [flutter/flutter#67372]
The application works fine but Debug console keeps on showing this message
```
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:57550/_qudLV1DRU8=/ws
[ERROR:flutter/shell/gpu/gpu_surface_gl.cc(242)] Could not make the context current to acquire the frame.

```

**Comment by darshankawar** [comment]
@kiranojhanp 
Please provide `flutter doctor -v` and a minimal complete code sample.
Can you try to create a new desktop project and see if you get the same error there too ?
Thanks.

**Comment by kiranojhanp** [comment]
The error doesn't occur anymore after a reboot. Don't know what the issue really was.
