### ISSUE TITLE
driver: SetInputText/SubmitInputText should use IME to set/submit text

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#6737]
The current implementations only pretend to change/submit text by emitting the corresponding events. Instead, we should use IME to inject raw keyboard events into the framework.

**Comment by tvolkert** [comment]
FYI @cbracken since you've recently been on the periphery of text widgets

**Comment by cbracken** [comment]
Sounds like #9383 might be a dupe of this? @yjbanov is the intent the same?

**Comment by yjbanov** [comment]
Yeah, I think the two can be deduped.

**Comment by cbracken** [comment]
De-duped. 

Worth noting that iOS doesn't have APIs for injecting key events. Worst-case scenario is we could manually support this by shimming into part of our implementation of `UITextInput`.

**Comment by yjbanov** [comment]
Closing this and will reopen https://github.com/flutter/flutter/issues/9383, because the other issue more accurately describes status quo, which is, we don't have any support for this right now.
