### ISSUE TITLE
Feature Request: Disable icon tree shaking for specific packages

### ISSUE THREAD

**Issue by pd4d10** [flutter/flutter#67388]
According to https://github.com/flutter/flutter/issues/63248#issuecomment-670813117 , ` --no-tree-shake-icons` could be passed to disable tree shaking. Is there any plan to disable it just for specify packages?

The use case is, sometimes we need to dynamic get the icon, for example the [file_icon](https://github.com/git-touch/file-icon) package. The file name is dynamic, and it determines which icon to use by user input file name extension.

1. For static icons: enable tree shaking to benefit from bundle size reduction
1. For dynamic icons: disable tree shaking to leave it as is

Thanks!

**Comment by jonahwilliams** [comment]
If the entire Icon invocation is not constant, i don't believe we can even determine the font family. that means its not safe to tree shake any of the icons.

@dnfield  to confirm.

**Comment by dnfield** [comment]
Correct - as soon as your program introduces even a single dynamically generated `Icon`, we can no longer be confident about which font file is dynamically used, and we can no longer safely shake out icons from any font file.

I'm going to close this as infeasible.

**Comment by dnfield** [comment]
(That should be dynamically generated `IconData`)
