### ISSUE TITLE
Erroneous main methods in flutter_goldens and flutter_test

### ISSUE THREAD

**Issue by jensjoha** [flutter/flutter#67382]
These files have erroneous main methods wrt nnbd:

packages/flutter_goldens/lib/flutter_goldens.dart
packages/flutter_test/test/custom_exception_reporter/flutter_test_config.dart

The first parameter needs to be a supertype of List<String>.

https://github.com/dart-lang/sdk/commit/4c29f26fc69d4ced6f58bc5ed854eb3d20283225

**Comment by johnniwinther** [comment]
This is due to new rules for the 'main' method in null safe libraries. See https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-main-function

**Comment by johnniwinther** [comment]
The reported error is:
```
test/flutter_test_config.dart: Error: The type 'FutureOr<void> Function()' of the first parameter of the exported 'main' method is not a supertype of 'List<String>'.
 - 'List' is from 'dart:core'.
../flutter_goldens/lib/flutter_goldens.dart:30:14: Context: This is exported 'main' declaration.
Future<void> main(FutureOr<void> testMain()) async {
             ^^^^
../flutter_goldens/lib/flutter_goldens.dart:30:14: Error: The type 'FutureOr<void> Function()' of the first parameter of the 'main' method is not a supertype of 'List<String>'.
 - 'List' is from 'dart:core'.
Future<void> main(FutureOr<void> testMain()) async {
             ^^^^
```

Note that this error is only report in null safe libraries.

**Comment by pcsosinski** [comment]
this is currently blocking the dart->engine roll
