### ISSUE TITLE
[google_maps_flutter_web] shows more than one infoWindow

### ISSUE THREAD

**Issue by Sammius** [flutter/flutter#67380]
<img width="572" src="https://user-images.githubusercontent.com/29778745/95167085-adba2800-07b7-11eb-87d1-ce3e936ab7c5.png">

This behaviour is opposite to the behaviour of the plugin in applications and does not comply with the recommendations from Google maps [Add an info window](https://developers.google.com/maps/documentation/javascript/infowindows?hl=pt-br#add)

```
% flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-8.0.pre.131, on Mac OS X 10.15.7 19H2 x86_64, locale en-CY)
    • Flutter version 1.23.0-8.0.pre.131 at /Users/Sammius/Flutter/flutter
    • Framework revision 8485580bb9 (18 hours ago), 2020-10-04 14:47:02 -0400
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Sammius/android
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/Sammius/android
    • ANDROID_SDK_ROOT = /Users/Sammius/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.7402

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@Sammius 
When do you see this behavior ? It seems to showing `infoWindow` for respective marker, but overlapped ? Or should it show one `infoWindow` when hovering on the marker ?
Thanks.

**Comment by Sammius** [comment]
@darshankawar 

From [Add an info window](https://developers.google.com/maps/documentation/javascript/infowindows?hl=pt-br#add)

>Best practices: For the best user experience, only one info window should be open on the map at any one time. Multiple info windows make the map appear cluttered. If you only need one info window at a time, you can create just one InfoWindow object and open it at different locations or markers upon map events, such as user clicks. If you do need more than one info window, you can display multiple InfoWindow objects at the same time.

The problem is not even that several `infoWindow`s are displayed at once. In principle, *Google maps* do not prohibit this but only recommend.

But this behaviour is opposite to the behaviour of `infoWindow`s in the same plugin for mobile applications, which is bad.

**Comment by ditman** [comment]
This is correct, I thought the core plugin was keeping track of this, but it seems that the implementation needs to happen on the platform code: 

* Core plugin: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/lib/src/controller.dart#L218-L222

This needs to be added to the "MarkersController" in the web implementation ([near here](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_web/lib/src/markers.dart#L103), probably calling "hideInfoWindow" in every other controller, or attempting to keep track of what infowindows are open)

**Comment by ditman** [comment]
I'm labeling this as "new feature", because this never was implemented for web. Thanks for the report @Sammius!

**Comment by ditman** [comment]
@balvinderz contributed a fix for this, I'll merge it ASAP!

Thanks!

**Comment by ditman** [comment]
The fix for this is now published as [`google_maps_flutter_web: ^0.1.0+6`](https://pub.dev/packages/google_maps_flutter_web/changelog#0106)! Thanks again @balvinderz!

**Comment by yahyanasser** [comment]
This feature has been added to Flutter Web. 

 How about Flutter Android And IOS ??

**Comment by balvinderz** [comment]
> This feature has been added to Flutter Web.
> 
> How about Flutter Android And IOS ??

this feature is already there in android and ios.
