### ISSUE TITLE
[e2e] e2e plugin is not reflecting its deprecation on pub.dev

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#67397]
## Steps to Reproduce

When you visit the [repository directory for e2e plugin](https://github.com/flutter/plugins/tree/master/packages/e2e) you'll notice that it's described as deprecated. However, on [pub.dev](https://pub.dev/packages/e2e) there's no indication that users should migrate to [integration_test](https://pub.dev/packages/integration_test).

As user I would be happy to be notified about this in the pub.dev description or changelog

## Logs

```
```

```
```

**Comment by dnfield** [comment]
I've updated the publication there.
