### ISSUE TITLE
Flutter Favorite program should add accessibility as an explicit part of its criteria

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#67394]
## Description
I described in https://github.com/dart-lang/pub-dev/issues/3848 the idea of a accessibility score for PubDev. In this move @timsneath noticed that accessibility is not yet a criterion for the [Flutter Favorite program](https://flutter.dev/docs/development/packages-and-plugins/favorites). @sigurdm therefore suggested to create a ticket for this.

## Current criterions
![image](https://user-images.githubusercontent.com/24459435/95179223-a3505c00-07c0-11eb-8b10-2c9d7da1fcb3.png)

Link: https://flutter.dev/docs/development/packages-and-plugins/favorites#metrics

## Accepts of accessibility
![image](https://user-images.githubusercontent.com/24459435/95179385-d7c41800-07c0-11eb-9287-cfc555ad0569.png)

Link: https://flutter.dev/docs/development/accessibility-and-localization/accessibility#accessibility-release-checklist

**Comment by darshankawar** [comment]
Hi @AndroidNils 
I think this issue belongs to Flutter website repo :  https://github.com/flutter/website/issues
Since the source point to flutter website : https://github.com/flutter/website/blob/6faf8dc552f2e8309b02891c5afeda59acc6d79b/src/docs/development/packages-and-plugins/favorites.md#metrics

Closing from here. Please consider opening this issue at repo referred above.
Thanks

**Comment by timsneath** [comment]
@darshankawar Actually that's not right. This would belong at https://github.com/dart-lang/pana, which is our repo for analyzing packages.

**Comment by timsneath** [comment]
@AndroidNils I don't think GitHub provides us with tools to transfer issues from one organization to another (you can only transfer within repos in the same org). Would you be so kind as to open a fresh issue in the dart-lang/pana repo, and we'll triage this appropriately? 

I'm also interested in any thoughts you have on how to measure this through code -- the biggest obstacle to this has been that we don't do manual testing of package submissions, so it needs to be something that we can measure objectively through code analysis.

**Comment by AndroidNils** [comment]
@timsneath I will open a new ticket 👍

I already thought it. It's very difficult. Even for the Flutter Favorite program is there only the option to scan the source code, right? I have some ideas, but I do not know if they can be implemented. I will comment them at the new issue.

**Comment by timsneath** [comment]
Thank you. For Flutter Favorites the committee does a short human review: https://flutter.dev/docs/development/packages-and-plugins/favorites

I suspect there are some heuristic tests we can apply to some of these accessibility areas, for example that very first rule about `onPressed` not being a no-op. There is also good prior art from the Chrome team that could likely be translated into Flutter/Dart equivalents: https://web.dev/accessibility-scoring/

One concern is not penalizing non-visual packages like provider based off their lack of detectable visual accessibility integration. Although even there, I suspect there's scope to test examples...
