### ISSUE TITLE
ExpansionPanelList  isExpanded=true

### ISSUE THREAD

**Issue by ismanong** [flutter/flutter#67406]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
```
The following assertion was thrown building ExpansionPanelList(dependencies: [_LocalizationsScope-[GlobalKey#63a3b]], state: _ExpansionPanelListState#61f06):
'package:flutter/src/material/mergeable_material.dart': Failed assertion: line 456 pos 18: '_children[j] is MaterialGap': is not true.
```

**Comment by Abhishek01039** [comment]
Hi @ismanong 
can you please provide `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
Thanks

**Comment by darshankawar** [comment]
@ismanong 
Please provide above details.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by huan220** [comment]
An error occurred while dynamically adding expansionPanel call to setState
