### ISSUE TITLE
The correct steps of obfuscation toward release version for google app store?

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#67417]
Hi,
    I need some confirmation from some experts here whether I am doing all correct or not. I am about to publish my app to the google app store. So I followed this link https://flutter.dev/docs/deployment/android#publishing-to-the-google-play-store. Coming to this step https://flutter.dev/docs/deployment/obfuscate with regards to obfuscating. I just says run this command flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>. Normally I do run this command too when I would want to test it on my phone etc. So will this command be the last command and then I go the /myapp/build/app/outputs/apk/release/myapp.apk and then I submit the file ready? My question is do I need to also follow and set this configuration too https://medium.com/@swav.kulinski/flutter-and-android-obfuscation-8768ac544421 ? Here its about proguard right? Here is where I am lost please could someone help me confirm which is the right direction and securing my app?

**Comment by sidrao2006** [comment]
Hello @newbieflutter , since this is not an issue with flutter, please close this issue.

For help please refer to https://flutter.dev/community

**Comment by PixelToast** [comment]
Hi @newbieflutter 

The issue tracker is for bugs and feature requests, questions like this are better suited for StackOverflow or one of our communities at https://flutter.dev/community

The `--obfuscate` option will obfuscate the native code that Flutter generates (minification is already done in non-debug builds by default), this option is a separate mechanism from Android's proguard and r8 which is only for java code. If you do not want to obscure other platform specific code, just passing `--obfuscate` to flutter build should be sufficient.

**Comment by newbieflutter** [comment]
Hi PixelToast,
                      Thank you. Now I have better understanding and details on this. So when I run this command flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory> do I need to add this section --split-debug-info=/<project-name>/<directory> or can I omit this will that be enough?

**Comment by sidrao2006** [comment]
Hey @newbieflutter , --split-debug-info is required with obfuscate.

You could also look into --shrink

**Comment by newbieflutter** [comment]
Hi Sidrao,
                I followed the link and this what I did finally flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --obfuscate --split-debug-info=myfiles. What do you think of this command ?
