### ISSUE TITLE
[camera by flutter.dev] I'm using ultraHigh resolution preset (3840x2160), but I only get 1920x1080

### ISSUE THREAD

**Issue by stephancapistrano** [flutter/flutter#67413]
I'm trying to use de ultraHigh resolution (3840x2160), but the max resolution I get is 1920x1080. How do I get a better resolution?

plugin version: camera: ^0.5.5

code: example code

flutter doc -v:

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.20.4 at /Users/stephan/Tools/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM A107M (mobile) • R9QN7016PNN • android-arm • Android 10 (API 29)

**Comment by darshankawar** [comment]
@stephancapistrano 
There's similar open issue describing your case, [58163](https://github.com/flutter/flutter/issues/58163).
Please follow-up there for updates and any questions.
Closing this as duplicate.
