### ISSUE TITLE
Pesto recipe page layout only partially fills the screen on a tablet

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#6742]
I ran Gallery/Pesto on a Nexus 9 and noticed that the recipe page layout is being constrained to a hardcoded width and only fills a region in the upper left corner of the screen.

This was introduced by https://github.com/flutter/flutter/commit/e7d5c7d6b771ad5772f733335790ba7877402cb8

@mpcomplete @Hixie

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by zoechi** [comment]
I believe this is stale because of https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/demos.dart#L530-L531
