### ISSUE TITLE
Load local assets html in Flutter web view iOS

### ISSUE THREAD

**Issue by adawi9** [flutter/flutter#67431]
Hi,

I ma using flutter webview 1.00 with flutter 1.22.0 

I embeded the flutter webview and read html file from assets and inject som dynamic html into it, every thing working on Android but on iOS nothing appear below the code

```
Expanded(
                        child: Container(
                          color: Colors.red,
                          child: WebView(
                            initialUrl: '',
                            javascriptMode: JavascriptMode.unrestricted,
                            onWebViewCreated:
                                (WebViewController webViewController) {
                              _controller = webViewController;
                               _loadHtmlFromAssets(content);
                            },
                            navigationDelegate: (NavigationRequest request) {
                              // print(request.url);
                              if(request.url != '') {
                                launchURL(request.url);
                                return NavigationDecision.prevent;
                              }
                              return NavigationDecision.navigate;
                            },
                          ),
                        ),
                      ),

  String getFontUri(ByteData data, String mime) {
    final buffer = data.buffer;
    return Uri.dataFromBytes(
        buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        mimeType: mime)
        .toString();
  }

  Future<String> addFontToHtml(
      String htmlContent, String fontAssetPath, String fontMime) async {
    final fontData = await rootBundle.load(fontAssetPath);
    final fontUri = getFontUri(fontData, fontMime).toString();
    final fontCss =
        '@font-face { font-family: customFont; src: url($fontUri); } * { font-family: customFont; }';
    return '<style>$fontCss</style>$htmlContent';
  }
  _loadHtmlFromAssets(Content content) async {

    String fileText = await rootBundle.loadString('assets/templates/content_template.html');
    fileText = fileText.replaceAll("{{Data}}", content.body);
    if(content.isContainImage)
    fileText = fileText.replaceAll("{{imageSRC}}", content.imagePath);
    fileText = await addFontToHtml(fileText,
        "assets/fonts/myfont.ttf", "font/opentype");

    // print("HTML: " + fileText);
    String url = Uri.dataFromString(fileText,
        mimeType: 'text/html',encoding: Encoding.getByName('utf-8'))
        .toString();
    print(url);
    _controller.loadUrl(url);
  }
```

The error

**flutter: Could not launch data:text/html;charset=utf-8,%3Chtml%20dir=%22rt......etc**

```
Flutter Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-JO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by darshankawar** [comment]
@adawi9 
Can you provide complete code sample ? I am getting compile errors while using the code above.

` _loadHtmlFromAssets(Content content) async {`.  Should it be Context ?

Thanks

**Comment by adawi9** [comment]
No not context it is a custome object you can replace the function with the belwo


_loadHtmlFromAssets(String body, String imagePathe) async {

    String fileText = await rootBundle.loadString('assets/templates/content_template.html');
    fileText = fileText.replaceAll("{{Data}}", body);
    if(content.isContainImage)
    fileText = fileText.replaceAll("{{imageSRC}}",imagePath);
    fileText = await addFontToHtml(fileText,
        "assets/fonts/myfont.ttf", "font/opentype");

    // print("HTML: " + fileText);
    String url = Uri.dataFromString(fileText,
        mimeType: 'text/html',encoding: Encoding.getByName('utf-8'))
        .toString();
    print(url);
    _controller.loadUrl(url);
  }

**Comment by darshankawar** [comment]
@adawi9 
This seems to be a known issue. See a similar [open](https://github.com/flutter/flutter/issues/27086) issue for your reference.
Does it resemble your issue ?
Thanks.

**Comment by adawi9** [comment]
Is it solved there or not yet?

**Comment by darshankawar** [comment]
@adawi9 
That issue is open and has got more traction. So I would suggest you to follow-up there for updates and any questions.
I am going ahead and closing it. If you disagree, write in comments and I'll reopen.
Thanks.
