### ISSUE TITLE
missing @ at colors parameter in LinearGradient widget's constructor

### ISSUE THREAD

**Issue by bhargavprajapati949** [flutter/flutter#67444]
In LinearGradient widget at package:flutter/src/painting/gradient.dart,

![Capture](https://user-images.githubusercontent.com/42943056/95252513-b4d64a00-083a-11eb-88f3-48ef9de69dd4.PNG)

It should be @required List<Color> colors,

**Comment by Calamity210** [comment]
This is intentional, `required` recently became a keyword. If you are facing any issues, try restarting your IDE or analysis servers

**Comment by goderbauer** [comment]
Closing as per previous comment.
