### ISSUE TITLE
Motivate developers to use dart and flutter by decrease google play commission from 30 to 25 percent ! =)

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#67450]
During last conflicts between google and big companies it is great idea to find consensus and make flutter community better and bigger.

**Comment by YazeedAlKhalaf** [comment]
I think this is irrelevant and needs to be sent to google play store team. Plus this is for the framework. You may use other channels such as the subreddit r/FlutterDev

**Comment by Renesanse** [comment]
Hello @YazeedAlKhalaf, the idea is  - scratch up about thousand likes to make it visible for google managers =)

**Comment by narcodico** [comment]
Google should decrease it to 25% and Apple should increase it to 35%. There you go, problem solved, everyone is happy! ✌

**Comment by Renesanse** [comment]
Pls, don't tell to apple =)

**Comment by stuartmorgan** [comment]
The Play Store is not part of the Flutter project. Closing as off-topic.

**Comment by Renesanse** [comment]
> The Play Store is not part of the Flutter project. Closing as off-topic.

Hello @stuartmorgan do you have any suggestions for me how to pay attention to ideas which can help flutter grow?
