### ISSUE TITLE
Hot Reload deserves its own docs on the website, graduates from the Wiki

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6746]
https://github.com/flutter/flutter/wiki/Hot-Reload can probably be "upgraded" to a formal doc(s) on the website.

The Wiki is intended for "early access" features. Hot Reload is supported now, we should move relevant content over to the website and then remove this wiki page.

**Comment by Hixie** [comment]
We probably don't really need a doc for hot reload. It's just how you use flutter. The intro doc is probably sufficient.

If we need a doc, it's more of a Dart-level doc explaining how it works so that you can reason about it. Not really a Flutter-level doc.

cc @johnmccutchan

**Comment by Hixie** [comment]
Closing on the basis that we don't need a dedicated doc.
