### ISSUE TITLE
flutter doctor issues even with java 8 on Ubuntu

### ISSUE THREAD

**Issue by AdenSTL** [flutter/flutter#67464]
I'm using Ubuntu 18.04LTS, Android Studio v3.0.1, installed latest Android SDK API 30 & 29, Android SDK Build tools, Platform tools & Command-line tools(latest),downgraded to java jdk1.8, installed Dart plugin on VSCode, installed Dart and Flutter plugin on Android Studio, installed flutter using snap on terminal.

But when I run `flutter doctor`, i get this

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
It says the plugin not installed even after I installed it and restarted android studio as well.

When i run `flutter doctor --android-licenses`, i get all licenses and accept them by typing `Y` in the terminal and even after this when i run `flutter doctor` it still gives me same result.

There was an issue with Java 9 so downgraded JDK to 1.8 and yet issue isn't resolved.

**Comment by TahaTesser** [comment]
Hi @AdenSTL 
This is probably you're a very old version of Android Studio, please update to the latest stable Android Studio and do the setup which locates your java and android SDK, complete the setup then try` flutter doctor -v`

Also, Android Studio comes with java 1.8 and it will locate when you set up Android Studio

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
