### ISSUE TITLE
Unwanted piece of material sliding in from the bottom when tapping on image

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6747]
When you tap on an image in the grid, it grows to full screen. Nice!

Also, a piece of material slides up from the bottom as the image fullscreens, but the user never sees this material when the image is done fullscreening, because the image is, well, fullscreen.

Looking at Google Photos, it doesn't slide a piece of material up from the bottom. It just grows the photo and then puts a black background behind it.

In the gallery's grid, not sure we need to slide material up from the bottom when the image grows fullscreen.

If we don't need it, we could take it out and simplify things.

**Comment by sethladd** [comment]
cc @Hixie any thoughts on this one?

**Comment by abarth** [comment]
That material is the one provided by the scaffold.  We should probably change the transition to a fade.

**Comment by sethladd** [comment]
Nice, glad to know we can change it/override it. Does it require something new from the framework/scaffold, or can the Gallery control this behavior today?

**Comment by zoechi** [comment]
Not sure what part of Gallery this is referring to but I just checked Studies > Shrine and it seems to do what you ask for (only grow the image without material).

Is this issue still relevant?

**Comment by zoechi** [comment]
I assume this is stale.
