### ISSUE TITLE
v0.0.0 flutter stable libs depend on prerelease nullsafety libs (Flutter 1.20 => 1.22 upgrade)

### ISSUE THREAD

**Issue by brunobowden** [flutter/flutter#67473]
Several (maybe all?) Flutter official libs report their version as **v0.0.0**.... I believe this is causing a mistaken dependency on the prerelease nullsafety version of the Flutter standard libs. The `pubspec.yaml` in the WHO COVID-19 app only specifies stable versions, so it shouldn't depend on anything prerelease. When running `flutter pub get` after upgrading from 1.20 to 1.22, it now pulls in the prerelease libs. This mistaken dependency is visible in the `flutter pub get --verbose` logs below.

The problem first occurred when upgrading from Flutter 1.20 to 1.22. So I'm guessing it's a combination of existing **0.0.0** libraries not having a version and then some kind of change in a dependency or the dart tooling. See another dart SDK issue that cause `pub get` to pull in prerelease libraries: https://github.com/dart-lang/sdk/issues/42657.

Libraries reporting version as **v0.0.0** and causing the nullsafety dependencies:
```
flutter 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
flutter_test 0.0.0 from sdk depends on test_api 0.2.19-nullsafety.2
flutter_localizations 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
flutter_web_plugins 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
```

## Steps to Reproduce

```
flutter upgrade
flutter --version
# Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision d408d302e2 (8 days ago) • 2020-09-29 11:49:17 -0700
# Engine • revision 5babba6c4d
# Tools • Dart 2.10.0

git clone https://github.com/WorldHealthOrganization/app
cd app/client/flutter
flutter pub get --verbose &> log.txt
```

## Logs

Selected output from last command above. Full logs available [here](https://gist.github.com/brunobowden/8a57ec246a89bb0f6a931ed0f438bbb9).

<details>
<summary>

```
[  +17 ms] SLVR: fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR: fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.19-nullsafety.2
```
</summary>

```
Full Logs....
[  +17 ms] SLVR:         fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.19-nullsafety.2
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on path 1.8.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on fake_async 1.2.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on clock 1.1.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.10.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on async 2.5.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.1.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on charcode 1.2.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.10-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on source_span 1.8.0-nullsafety.2
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.1.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.1.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.2.0-nullsafety.1
[        ] SLVR:         fact: flutter_test 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:           selecting flutter_test 0.0.0 from sdk
[        ] SLVR:           derived: typed_data 1.3.0-nullsafety.3
[        ] SLVR:           derived: term_glyph 1.2.0-nullsafety.1
[        ] SLVR:           derived: string_scanner 1.1.0-nullsafety.1
[        ] SLVR:           derived: stream_channel 2.1.0-nullsafety.1
[        ] SLVR:           derived: source_span 1.8.0-nullsafety.2
[        ] SLVR:           derived: meta 1.3.0-nullsafety.3
[        ] SLVR:           derived: matcher 0.12.10-nullsafety.1
[        ] SLVR:           derived: collection 1.15.0-nullsafety.3
[        ] SLVR:           derived: charcode 1.2.0-nullsafety.1
[        ] SLVR:           derived: characters 1.1.0-nullsafety.3
[        ] SLVR:           derived: boolean_selector 2.1.0-nullsafety.1
[        ] SLVR:           derived: async 2.5.0-nullsafety.1
[        ] SLVR:           derived: vector_math 2.1.0-nullsafety.3
[        ] SLVR:           derived: stack_trace 1.10.0-nullsafety.1
[        ] SLVR:           derived: clock 1.1.0-nullsafety.1
[        ] SLVR:           derived: fake_async 1.2.0-nullsafety.1
[        ] SLVR:           derived: path 1.8.0-nullsafety.1
[        ] SLVR:           derived: test_api 0.2.19-nullsafety.2
```
</details>

<details>
<summary>

```
[  +44 ms] SLVR: fact: flutter_localizations 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR: fact: flutter_localizations 0.0.0 from sdk depends on intl 0.16.1
[        ] SLVR: fact: flutter_localizations 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
```
</summary>

```
Full Logs....
[  +44 ms] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on intl 0.16.1
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on path 1.8.0-nullsafety.1
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:           fact: flutter_localizations 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[        ] SLVR:             selecting flutter_localizations 0.0.0 from sdk
[        ] SLVR:             derived: intl 0.16.1
```
</details>

<details>
<summary>

```
[  +24 ms] SLVR: fact: flutter 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR: fact: flutter 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
```
</summary>

```
Full Logs:
[  +24 ms] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[   +4 ms] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[        ] SLVR:                                                                           fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:                                                                             selecting flutter 0.0.0 from sdk
 ```
</details>

<details>
<summary>

```
[   +2 ms] SLVR: fact: flutter_web_plugins 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR: fact: flutter_web_plugins 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
```
</summary>

```
Full Logs...
[   +2 ms] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[        ] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:
fact: flutter_web_plugins 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[        ] SLVR:
selecting flutter_web_plugins 0.0.0 from sdk

```
</details>

## flutter doctor -v
<details>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0 at /Users/brunobowden/dev/flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/brunobowden/dev/android-sdk-macosx
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/brunobowden/dev/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 1 category.
```
</details>

**Comment by speaking-in-code** [comment]
This is causing some ecosystem problems, e.g. the [screenshots package broke due to library interface changes](https://github.com/mmcc007/screenshots/issues/215).

**Comment by brunobowden** [comment]
@a14n - thanks for your work on nullsafety. My understanding is that nullsafety is still prerelease but after upgrading flutter from v1.20.0 => v1.22.0, the `flutter pub get` pulled in a number of `-nullsafety.x` prerelease libs as unexpected dependencies... the `pubspec.yaml` only refers to stable releases and I thought shouldn't depend on anything prerelease.

I believe this may be happening as a number (maybe all?) of the flutter libs report their version number as **v0.0.0**, which I think may be screwing with the dependency resolution in Dart.

Diff that added nullsafety as dependency on flutter libs:
https://github.com/flutter/flutter/commit/f32a73711a826c6f1157c2637fb419a597e8ef87#diff-afa141921d14a02769e479c13b0b775c

**Comment by brunobowden** [comment]
FYI @mit-mit - my compliments on a somewhat related but beautifully described issue: https://github.com/dart-lang/sdk/issues/42657#issue-654672867

**Comment by mit-mit** [comment]
Hi @brunobowden, let me try to respond to some of the questions and comments from the top of this thread:

### packages with `0.0.0` versions

> Several (maybe all?) Flutter official libs report their version as v0.0.0.... 

Flutter has a few core packages that are so-called SDK packages. These are not distributed on pub.dev, but rather in the framework itself. You can see these in your `pubspec.yaml` having a special `sdk: flutter` line below them, e.g.:

```
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Because these are not coming from pub.dev, they are not part of the resolution that the `pub` client does. I'm not sure why the solver prints them as having version `0.0.0`; it would be more correct to say that they don't have a version at all.

### prerelease dependencies in Flutter stable 1.22

> I believe this is causing a mistaken dependency on the prerelease nullsafety version of the Flutter standard libs. 

It is correct that Flutter stable 1.22 has dependencies on prerelease packages, specifically the ones *pinned* here: https://github.com/flutter/flutter/blob/1.22.0/packages/flutter/pubspec.yaml#L10

This is a temporary measure to enable us to make progress on migrating the Flutter framework to null safety. Note that 1) these packages are fully backwards compatible with apps and packages that do *not* use null safety, and 2) despite their prerelease version we ran these through full stable testing, so they are essentially stable.

> The pubspec.yaml in the WHO COVID-19 app only specifies stable versions, so it shouldn't depend on anything prerelease. When running flutter pub get after upgrading from 1.20 to 1.22, it now pulls in the prerelease libs. 

Yes, this is a bit of an anomaly. The pub solver only picks these prerelease versions because it has no other choice; there is no stable version of these available.

> The problem first occurred when upgrading from Flutter 1.20 to 1.22.

That's right. This is a transition we have to work through; there was no way we could land a change as large as null safety within a single stable release. We hope to have a stable release of Flutter early next year that has a stable null safety feature, and with that regular stable version core package dependencies. And as I mentioned above, don't worry about these packages from a stability point of view; they are stable quality.

**Comment by mit-mit** [comment]
Closing as by-design.

**Comment by speaking-in-code** [comment]
I'd like to reopen discussion on this to ask about one of the assumptions: "these packages are fully backwards compatible with apps and packages that do not use null safety."

Is that really true?

flutter 1.2.2 switched from process ^3.0.x to process ^4.0.x, platform 2.2.x to platform 3.0x, and file 5.0.x to file 6.0.x. Those all included non-backwards compatible API changes. 

I'm not sure how big the ecosystem breakage extends, but it's definitely present. One of the popular screenshots packages is broken by this change, so folks who had CI/CD for app store releases are in bad shape.

**Comment by brunobowden** [comment]
@mit-mit - thanks for a thoughtful response. I'm satisfied with your statement about it being a stable quality even if prerelease. I couldn't find this decision documented anywhere. So it might be good thing to document in the release notes or some other place.... but I'll leave it to your discretion on whether to do that. At the very least, it's documented here.

@speaking-in-code - I think @mit-mit may be speaking about backwards compatibility with the sdk libraries. The `platform`, `process` and `file` are not sdk libraries. Perhaps there were breaking changes in them but that would be a separate issue. The Flutter 1.22.0 release notes mentions a number of breaking changes:
https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-1.22.0

**Comment by mit-mit** [comment]
My statement about backwards compatibility was regarding the null safety aspect: these packages are compatible with both app/packages that choose to use null safety, and ones that don't.

It looks like there may have been other breaking changes in some of these packages. For example, I see that `package:file` had some functionality removed for record/play according it's [changelog](https://github.com/google/file.dart/blob/master/packages/file/CHANGELOG.md). @jonahwilliams can you elaborate?

**Comment by speaking-in-code** [comment]
The other non-backwards compatible changes I've hit while trying to upgrade are

package:platform: FakePlatform no longer mutable:
https://github.com/google/platform.dart/commit/33bb07771d6d459a8fd1cafc7ad3195144bc4b51

package:process: RecordingProcessManager no longer exists:
https://github.com/google/process.dart/commit/1df10c6fd7684f6862afc4f3ed4cb8c5d13852fb

There are also a couple of breaking dart SDK changes coming in. Not sure if the ecosystem will be forced to merge those at the same time, hopefully not?

dart:io: HttpHeaders now has preserveLowerCase option (which was a known breaking change):
https://github.com/dart-lang/sdk/commit/d39cdf03f83a4b76d0bda122b3745109fcd03299

dart:io: HttpClientRequest now has an abort method.
https://github.com/dart-lang/sdk/commit/56d40bad75255688772a6b306fd459a59cd737c8
