### ISSUE TITLE
flutter create creates the wrong template for Android

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#67483]
Looking at [this migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) we can see we need to remove from the Manifest:

```
android:name="io.flutter.app.FlutterApplication"
```

But running `flutter create .` this is the Android Manifest being created:

![image](https://user-images.githubusercontent.com/8120472/95279195-7768c100-0828-11eb-97a2-c0eb0c45a4f7.png)

**Comment by TahaTesser** [comment]
Hi @feinstein 
This is already addressed in the `dev` and `master channels 

### `dev` & `master` channels
<img width="554" alt="Screenshot 2020-10-07 at 2 58 59 PM" src="https://user-images.githubusercontent.com/48603081/95313566-e3d9d380-08ad-11eb-9c24-7daabb8cf770.png">

### `stable` & `beta` channels
<img width="631" alt="Screenshot 2020-10-07 at 2 59 29 PM" src="https://user-images.githubusercontent.com/48603081/95313560-e1777980-08ad-11eb-995d-183d0d06ea1d.png">


Closing as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by feinstein** [comment]
@TahaTesser ok thanks!
