### ISSUE TITLE
How come I don't get the .cirrus.yml file when downloaded?

### ISSUE THREAD

**Issue by iNeedHelpX** [flutter/flutter#67486]
Hey downloaded flutter and realized some files are missing. Here is a pic of my flutter file and what I got. How come no .cirrus.yml file??
<img width="882" alt="Screen Shot 2020-10-06 at 10 23 53 PM" src="https://user-images.githubusercontent.com/41366455/95280619-72554300-0823-11eb-96b9-b29b91dcaed5.png">

## Steps to Reproduce

1. Download flutter via the cli

## flutter doctor -v

```
juliapak@julias-MacBook-Pro ~ % flutter doctor -v  
[✓] Flutter (Channel master, 1.23.0-8.0.pre.185, on Mac OS X 10.15.7 19H2
    x86_64, locale en-CA)
    • Flutter version 1.23.0-8.0.pre.185 at /Users/juliapak/flutter
    • Framework revision 6620f831e9 (72 minutes ago), 2020-10-06 18:15:15 -0700
    • Engine revision 7e6191de07
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/juliapak/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 568C53C9-FD02-4357-96FF-262CE4EC4FA9 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

**Comment by josecfreittas** [comment]
Files that starts with a `.` (dot) are hidden files on Linux and Mac. Search how to show hidden files.

**Comment by iNeedHelpX** [comment]
> Files that starts with a `.` (dot) are hidden files on Linux and Mac. Search how to show hidden files.

thank you. Im trying to figure out what's wrong with my flutter install as my projects keep creating duplicates!!

**Comment by iNeedHelpX** [comment]
> Files that starts with a `.` (dot) are hidden files on Linux and Mac. Search how to show hidden files.

`
<img width="923" alt="Screen Shot 2020-10-06 at 11 19 34 PM" src="https://user-images.githubusercontent.com/41366455/95283816-a4b66e80-082a-11eb-8a21-4c276211f742.png">
`

**Comment by iNeedHelpX** [comment]
```
 Command+Shift+Dot to show hidden files on mac
```

**Comment by darshankawar** [comment]
@iNeedHelpX 
Seems your issue is resolved, as I see the concerned file `.cirrus.yml` being created but was hidden.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks
