### ISSUE TITLE
Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist.

### ISSUE THREAD

**Issue by ThanhPhungTien** [flutter/flutter#67492]
I can not Distribute iOS App after upgrade flutter to 1.22.
Flutter doctor
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

**Comment by darshankawar** [comment]
@ThanhPhungTien 
What's your current minimum OS version ? Can you change it to 9.0 in info.plist and in Xcode, try again and see if it works ?
Thanks.

**Comment by suztomo** [comment]
I received the same error. I specify 9.0 as iOS Deployment Target.

<img width="783" alt="Screen Shot 2020-10-07 at 7 39 21 AM" src="https://user-images.githubusercontent.com/28604/95326213-3ac0b800-0870-11eb-88ba-49ec83d77952.png">

I couldn't find corresponding information in Info.plist.

The only diffrence I found is that flutter 1.22 somehow set `CFBundleVersion` to `2`.

```
~/Documents/hitomemo/ios $ git diff -- Runner/Info.plist
diff --git a/ios/Runner/Info.plist b/ios/Runner/Info.plist
index 0d23bb5..f2b8d99 100644
--- a/ios/Runner/Info.plist
+++ b/ios/Runner/Info.plist
@@ -49,7 +49,7 @@
                </dict>
        </array>
        <key>CFBundleVersion</key>
-       <string>$(CURRENT_PROJECT_VERSION)</string>
+       <string>2</string>
        <key>ITSAppUsesNonExemptEncryption</key>
        <false/>
        <key>LSRequiresIPhoneOS</key>
```

**Comment by suztomo** [comment]
Same issue found https://github.com/flutter/flutter/issues/64954 (closed due to insufficient information).

**Comment by suztomo** [comment]
https://github.com/flutter/flutter/issues/64954#issuecomment-687403438 's comment on updating Flutter/AppFrameworkInfo.plist having to specify MinimumOSVersion to 9.0 fixed for my problem.

<img width="922" alt="Screen Shot 2020-10-07 at 10 02 09 AM" src="https://user-images.githubusercontent.com/28604/95347749-3e156d00-088b-11eb-8f2b-15bae1e3dcb6.png">

**Comment by ThanhPhungTien** [comment]
![image](https://user-images.githubusercontent.com/23505450/95408712-4f717e80-094a-11eb-9c73-f860bb0a51f3.png)
![image](https://user-images.githubusercontent.com/23505450/95409526-015d7a80-094c-11eb-9069-1634d62822b9.png)
![image](https://user-images.githubusercontent.com/23505450/95409445-d2df9f80-094b-11eb-9384-da731940812d.png)
It still not woking.

**Comment by ThanhPhungTien** [comment]
Works perfectly !!!.  I forgot "flutter clean". Thanks.

**Comment by darshankawar** [comment]
Closing this as resolved per above comment.
