### ISSUE TITLE
[video_player] Leaks Timer (notifying Listeners) when calling Play consecutively

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#67495]
## Steps to Reproduce

1. Use `video_player: 0.11.0`.
1. Attach a listener to your `VideoPlayerController` (and debug when that is being called).
1. Call `VideoPlayerController.play`.
1. Call `VideoPlayerController.play` again.
1. Call `VideoPlayerController.pause`.
1. See your listener get called indefinitely at periodic intervals because the timer of the first `play` call is leaking.

**Expected results:** listener should not receive events periodically after `pause`.

**Actual results:** listener leaks.

## Fix

I found this issue in code and provided a PR to fix it: https://github.com/flutter/plugins/pull/3119

**Comment by stuartmorgan** [comment]
Closing, as the linked PR landed.
