### ISSUE TITLE
Getting Started says `flutter run` targets all connected devices

### ISSUE THREAD

**Issue by kwalrath** [flutter/flutter#6750]
...but if more than one device is connected, you're prompted to specify a device.

```
$ flutter run
More than one device connected; please specify a device with the '-d <deviceId>' flag.

XT1060         • ...    • android-arm • Android 5.1 (API 22)
iPhone 6s Plus • ...    • ios         • iOS 9.3 (simulator)
```

So "all connected devices and simulators" should probably be "a connected device or simulator". The deviceId isn't labeled as an ID in the output, so that's something else that could be clarified.

**Comment by sethladd** [comment]
Good catch! Patches welcome :)
