### ISSUE TITLE
LinearGradient not working

### ISSUE THREAD

**Issue by quanghai29** [flutter/flutter#67508]
LinearGradient not work in verion  dart: ">=2.10.0-110 <2.11.0"

**Comment by darshankawar** [comment]
@quanghai29 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by omaroskars** [comment]
It seems the colors parameters is missing the "@" symbol before required

**Comment by RoyARG02** [comment]
@omaroskars that's intentional, see #67444

**Comment by darshankawar** [comment]
Closing per referred issue and corresponding comment.

**Comment by quanghai29** [comment]
Thank You. I fixed it. The vs code path has some problem.

**Comment by darshankawar** [comment]
Closing this as resolved per above comment.
