### ISSUE TITLE
[Flutter Engine] No such file or directory when running ./flutter/tools/gn --android --unoptimized

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#67505]
I followed every step on https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment and https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-android-from-macos-or-linux 

But when I run the command `./flutter/tools/gn --android --unoptimized`, I get 

```
:~/flutter_engine/engine/src$ ./flutter/tools/gn --android --unoptimized
Generating GN files in: out/android_debug_unopt
Traceback (most recent call last):
  File "./flutter/tools/gn", line 443, in <module>
    sys.exit(main(sys.argv))
  File "./flutter/tools/gn", line 411, in main
    gn_call_result = subprocess.call(command, cwd=SRC_ROOT)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I am on Ubuntu 18.04

**Comment by TahaTesser** [comment]
Hi @tolotrasamuel 
Make sure you've one https://github.com/flutter/flutter/wiki/The-flutter-tool setup 
Do you need to have python 2 installed and execute `gclient sync` with a stable internet connection 
Thank you

**Comment by tolotrasamuel** [comment]
I already have python 2 installed and did `gclient sync` in both engine root directory and engine/src directory.

**Comment by tolotrasamuel** [comment]
It was because I run Ubuntu on VM on windows host. gclient sync downloaded a file containing a coma ":" in its filename. I shared the engine folder with Windows host so the host does not support this character in its filename hence leading to a slient error, the file was not written

**Comment by TahaTesser** [comment]
Hi @tolotrasamuel 
Is your issue resolved then?

**Comment by tolotrasamuel** [comment]
Yes

**Comment by tolotrasamuel** [comment]
It wouls be nice

**Comment by TahaTesser** [comment]
Hi @tolotrasamuel 
This feels too specific for documentation, not everybody would use VM shared folder for setting the engine environment 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
