### ISSUE TITLE
Flutter Ask for build version 28.0.3

### ISSUE THREAD

**Issue by MrR1pp3r** [flutter/flutter#67509]
I recently setup android environment using Android Studio. Its work fine on beginning.. but i make change's in main.dart file and its asking for Build-tool v28.0.3

My config
API LEVEL : 30
BUILD TOOL : 30.0.2
FLUTTER : 1.22.0
PLATFORM: WINDOWS 10.0.19041.XXX
ANDROID STUDIO : v4.0
VSCODE : 1.49.3
MOBILE : SAMSUNG M series

main.dart (code)
```
home: Scaffold
   body: Center
      child: FloatButton
           onPressed
                    player = AudioCache()
                    player.play("music.mp3")

```
Package: audioplayers ^0.16.1

Experience: I use **HOT RESTART**
(No problem) & after this I stop and re-run **flutter run**

**Comment by darshankawar** [comment]
@MrR1pp3r 
When does it ask you to build version 28.0.3 ? Can you try by removing the package `audioplayers` and run with Flutter core code, repeat the scenario to see if it again asks you that message ?
Thanks.

**Comment by MrR1pp3r** [comment]
I really sorry.. I'm new too report bugs..

After post here, I remove audioplayers package and my app run once again.. I make new report on audioplayers github repo.

**Comment by darshankawar** [comment]
Closing this as non-issue per above comment.
