### ISSUE TITLE
[AddToApp] I want to using .android gradle version 6.1.1

### ISSUE THREAD

**Issue by ybin0823** [flutter/flutter#67504]
## Steps to Reproduce
Flutter version: 1.20.4
Target platform: Android

For example, our project structure like below, 
https://flutter.dev/docs/development/add-to-app/android/project-setup
```
Master Project
   |_ Android project
   |_ iOS project
   |_ add_to_app_flutter
```

1. Run `flutter build aar`.
2. show `.android` gradle version
![스크린샷 2020-10-07 오후 4 11 08](https://user-images.githubusercontent.com/7553607/95298876-babe4080-08b7-11eb-99dd-8dccee36bb1e.png)

### build.gradle.tmpl
https://github.com/flutter/flutter/blob/6620f831e93a74ca12e65b501748a6d1df310863/packages/flutter_tools/templates/app/android-kotlin.tmpl/app/build.gradle.tmpl#L26

### flutter.gradle
https://github.com/flutter/flutter/blob/6620f831e93a74ca12e65b501748a6d1df310863/packages/flutter_tools/gradle/flutter.gradle#L30

I want to upload `minSdk` and `gradle` in the our private library, but flutter is fixed. Because 
`build.gradle.tmpl` using flutter.gradle and flutter.gradle fixed 3.5.0. Overall, it is used in 3.5.0 everywhere. It is target sdk 29, could you review support with gradle 6.1.1?

Thank you :)

**Comment by TahaTesser** [comment]
Hi @ybin0823 
This is no support newer Gradle version yet https://github.com/flutter/flutter/issues/58247  https://github.com/flutter/flutter/issues/65399  https://github.com/flutter/flutter/issues/58479

When there is support for newer Gradle, you would be able to use it everywhere 
Thank you
