### ISSUE TITLE
When I click the [Flutter Hot Restart] button in Android studio to restart the application, the function of IOS status bar back to the top fails

### ISSUE THREAD

**Issue by 515445681** [flutter/flutter#67503]
questions: When I click the [Flutter Hot Restart] button in Android studio to restart the application, the function of IOS status bar back to the top fails

expect: scroll to top available

tools: Android Studio

code:

```
void main(){
  // WidgetsFlutterBinding.ensureInitialized();
  // SystemChrome.setPreferredOrientations(
  //     [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

  runApp(MaterialApp(
    home: Scaffold(body: SingleChildScrollView(
      primary: true,
      child: Container(
          height: 3000,
          child: Column(
            children: [
              Container(
                height: 1000,
                color: Colors.red,
              ),
              Container(
                height: 1000,
                color: Colors.blue,
              )
            ],
          )),
    ),),
  ));
}
```

step:
1. click [Run 'main.dart'].At this time, everything is good
![image](https://user-images.githubusercontent.com/11323678/95296489-72992100-08ab-11eb-95cf-9a05394bda1a.png)

2. click [Flutter Hot Restart].At this time, back to the top fails.
![image](https://user-images.githubusercontent.com/11323678/95296586-9c524800-08ab-11eb-8590-c6a26f7a928b.png)

I debug the scaffold.dart.I found that the following code threw an exception after [Flutter Hot Restart].

![image](https://user-images.githubusercontent.com/11323678/95296772-efc49600-08ab-11eb-815f-5d54b09448c7.png)

flutter doctor: 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@515445681 
By status bar back to top, do you mean the `Up the stack trace` button is disabled after hot restart ?
Can you try the same with Android native project and see ?
Thanks.

**Comment by 515445681** [comment]
> @515445681
> By status bar back to top, do you mean the `Up the stack trace` button is disabled after hot restart ?
> Can you try the same with Android native project and see ?
> Thanks.

哦，我说的"回到顶部"，是指的在ios设备上，点击状态栏时，滚动条会回到顶部。

但是当我点击Android Studio控制台的[Flutter Hot Restar]按钮后，这个功能就不可用了。

**Comment by darshankawar** [comment]
@515445681 
Since I don't understand the language you replied, I'd request you to write in English.
Thanks.

**Comment by 515445681** [comment]
> @515445681
> Since I don't understand the language you replied, I'd request you to write in English.
> Thanks.

Oh, by "back to top", I mean that on IOS devices, when you click the status bar, the scroll bar will go back to the top.
But when I click the [fluent hot restart] button on the Android studio console, this function is not available.

**Comment by darshankawar** [comment]
@515445681 
I am unable to replicate this issue. I see hot restart button intact and active after going back to top on iOS device.

<img width="416" alt="Screenshot 2020-10-12 at 12 37 37 PM" src="https://user-images.githubusercontent.com/67046386/95715714-f1b19f00-0c87-11eb-8ae7-b6243c294538.png">
<img width="274" alt="Screenshot 2020-10-12 at 12 38 16 PM" src="https://user-images.githubusercontent.com/67046386/95715727-f413f900-0c87-11eb-8399-20c9aa720158.png">

**Comment by 515445681** [comment]
> @515445681
> I am unable to replicate this issue. I see hot restart button intact and active after going back to top on iOS device.
> 
> <img alt="Screenshot 2020-10-12 at 12 37 37 PM" width="416" src="https://user-images.githubusercontent.com/67046386/95715714-f1b19f00-0c87-11eb-8ae7-b6243c294538.png">
> 
> <img alt="Screenshot 2020-10-12 at 12 38 16 PM" width="274" src="https://user-images.githubusercontent.com/67046386/95715727-f413f900-0c87-11eb-8399-20c9aa720158.png">

The order is wrong.
Restart first, then go back to the top

**Comment by 515445681** [comment]
> @515445681
> I am unable to replicate this issue. I see hot restart button intact and active after going back to top on iOS device.
> 
> <img alt="Screenshot 2020-10-12 at 12 37 37 PM" width="416" src="https://user-images.githubusercontent.com/67046386/95715714-f1b19f00-0c87-11eb-8ae7-b6243c294538.png">
> 
> <img alt="Screenshot 2020-10-12 at 12 38 16 PM" width="274" src="https://user-images.githubusercontent.com/67046386/95715727-f413f900-0c87-11eb-8399-20c9aa720158.png">

How is it, did you find the problem?

**Comment by darshankawar** [comment]
@515445681 
Tried first with restart and was able to go back to the top.
Not sure what your exact issue is. Provide a video if you could that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
