### ISSUE TITLE
App crash when resuming - Flutter problem or my app?  How to troubleshoot?

### ISSUE THREAD

**Issue by craigjp99** [flutter/flutter#67511]
Hi guys,
I have an app that I've written.  It's my first flutter app (well, aside from a couple of very basic demo apps when I was first trying to figure Flutter out!), and I guess it's got a bit going on.  I've got a Google Maps plug-in that shows some markers, a list that displays on another tab, and a handful of other screens that pop up, to do settings, or search.

Anyhow, the specific details of the app may not matter at this point ....  I'm using Visual Studio Code on Windows 10 with Android Studio running a Pixel emulator.  I'm traditionally a C# / SQL developer, so had a bit of a learning curve with Flutter, I'll admit.  Is everything done "exactly" right in my app? - I'd guess probably not.  But when I first build it and deploy it to the emulated device, everything works fine.  It does a couple of calls to a local web-server running on my PC and those requests happen successfully and screens update when they need to.  (I've tried 2 different emulations so far - a Pixel 3 with Android 8.1 and a Pixel 3a with Android 10.0)

My issue comes when I close the app (ie. just click the "Home" button on the emulated phone), and then open the app again from the icon.  When I do that, the app crashes (the app very briefly appears, but it's like only a second or so, and then crash).  Because the debug connection is still active in VS, then below is the tail-end of the output.  (After the crash has occurred, then I can open the app again and it runs like it's starting fresh - then if I do the close/resume thing, it will crash again)

My initial question is - is this error occurring because of an underlying Flutter problem, or something specific within my app?  I would have thought that if it was a specific line in my app causing an exception (particular a null reference), then because VS is still connected I would get a break on the particular line that threw the exception?  How do I go about troubleshooting further, to see if I can determine whether it's a specific component of my app?  I'm happy to try and do more troubleshooting myself, but I'm just not sure how to go about it .... and it's difficult to determine from the oodles of things online about this particular error.

```
I/flutter (18023): MyApp state = AppLifecycleState.resumed
D/EGL_emulation(18023): eglMakeCurrent: 0xbea42d40: ver 1 0 (tinfo 0xbee82240)
D/EGL_emulation(18023): eglMakeCurrent: 0xedc7fd00: ver 3 0 (tinfo 0xe2bae960)
E/flutter (18023): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(72)] Failed to setup Skia Gr context.
D/EGL_emulation(18023): eglMakeCurrent: 0xdab1a0c0: ver 3 0 (tinfo 0xc07d37a0)
D/eglCodecCommon(18023): setVertexArrayObject: set vao to 1 (1) 11 6
D/eglCodecCommon(18023): setVertexArrayObject: set vao to 0 (0) 11 2
F/libc    (18023): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 18061 (1.raster), pid 18023 (.shows_near_me1)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-10-07 19:23:00+1100
pid: 18023, tid: 18061, name: 1.raster  >>> com.example.shows_near_me1 <<<
uid: 10140
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    eax 00000000  ebx c280bfd0  ecx fffffff9  edx 00000000
    edi 00000004  esi 00000000
    ebp c2e1b6a8  esp c2e1b6a8  eip c215aa95
backtrace:
      #00 pc 013caa95  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #01 pc 013e3323  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #02 pc 0146b23e  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #03 pc 0163e793  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #04 pc 0163e665  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #05 pc 0163eb53  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #06 pc 0163e93f  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #07 pc 011f4134  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #08 pc 011f4d64  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #09 pc 011f5b8c  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #10 pc 011a2d1b  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #11 pc 011f463e  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #12 pc 011f43a6  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
      #13 pc 012024c9  /data/app/com.example.shows_near_me1-QOqnRJygpl8RlZbgT9cqvw==/lib/x86/libflutter.so (BuildId: 9a9e0c319c62d5760a80e7d286af8e82efdf7747)
Lost connection to device.
```

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.546], locale en-AU)
    • Flutter version 1.22.0 at C:\ggle\flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\craig\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\craig\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\craig\AppData\Local\Android\Sdk
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\craig\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```
```

</details>

**Comment by darshankawar** [comment]
@craigjp99 
There's similar open issue describing your crash, [66921](https://github.com/flutter/flutter/issues/66921).
Please follow-up there for updates and any questions.
Closing this as duplicate. 
Thanks
