### ISSUE TITLE
TextField with MaxLength (or any other TextInputFormatter) keeps invalid string and breaking the DELETE button.

### ISSUE THREAD

**Issue by arielbh** [flutter/flutter#67513]
## Steps to Reproduce

Create a new flutter app and add a TextField with maxLength = 2 and maxLengthEnforced = true and notice how the delete button doesn't work as the user expects.
Delving deeper, if you create a custom text input formatter it can be observed that while the user doesn't see the new value it is still retained. So in this example if the user types more than 2 characters: "abcde" , "ab" will be displayed but the control still keeps the "abcde" string. Now when the user deletes, it will delete from the retained string: "abcd" -> "abc" -> "ab" and only now the user will have a visible response that the delete button works: "a".
``` import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            TextField(
              maxLength: 2,
              maxLengthEnforced: true,
            )
          ],
        ),
      ),
    );
  }
}
```
**Expected results:** When the user hits the delete button it should delete from the visible characters on screen.

**Actual results:** When the user hits the delete button it deletes from an invalid string retained by the control

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-IL)
    • Flutter version 1.22.0 at /Users/arielbh/dev/flutter
    • Framework revision d408d302e2 (8 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/arielbh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (2 available)            
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro (mobile)             • GUID • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: XXX is not connected. Xcode will continue when XXX is connected. (code -13)

• No issues found!
</details>

**Comment by darshankawar** [comment]
@arielbh 
There's similar open issue describing your case, [67236](https://github.com/flutter/flutter/issues/67236).
Closing this as duplicate.

**Comment by arielbh** [comment]
@darshankawar OK. Thanks!
