### ISSUE TITLE
Regression, TextField.maxLength is ignored

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#67519]
Hello!

This commit introduced a regression bug: https://github.com/flutter/flutter/commit/2c3652b8fbe2294b3afdb3898f485bc7fdf7968b

I'm experiencing this issue on Samsung A40 (SM-A405FN) using Samsung keyboard, on Android of course. My colleague with iOS simulator can't reproduce the bug.

Let's create a simple TextField with `maxLength`.

```dart
TextField(
  maxLength: 10,
),
```

Start inputting some text without spaces, only characters. For example "dfjsdflsdnfsdnvsdnv" (random tapping at the keyboard). The length limit is exceeded and not enforced. But once I add space (which probably finishes the _composing_) the text is truncated to the correct size.

This is not how it should work! When I'm typing the text on the keyboard I want it to be limited exactly when I exceed the limit, not after I put a space.

Also, continuing on this example, when I press that space and then try to input more characters, they won't appear in the `TextField`, but will appear on my keyboard suggestions bar. After tapping backspace I am deleting those invisible characters and only after that the ones that were shown in the text field.

```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (8 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

**Comment by darshankawar** [comment]
@Albert221 
There's a similar open issue describing your case, [67236](https://github.com/flutter/flutter/issues/67236).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
