### ISSUE TITLE
API docs are difficult to read for some users

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#67527]
More context at https://github.com/flutter/flutter/pull/48073

The basic problem seems to be around how font weights are used. This is probably something that should be fixed in dartdoc, so I filed https://github.com/dart-lang/dartdoc/issues/2374 as well - depending on how that issue goes, we could potentially fix it in our own repo.

**Comment by TahaTesser** [comment]
@dnfield 
Duplicate of https://github.com/flutter/flutter/issues/67527?

**Comment by dnfield** [comment]
Ah, yes it is, closing
