### ISSUE TITLE
Debug freeze Android/IOS

### ISSUE THREAD

**Issue by brenoasm** [flutter/flutter#67524]
Hi, since I updated my app to 1.22, when running in debug mode from vscode the debug "freeze" and nothing happens anymore (breakpoints are not being hit, hot restart and reload just don't run).  I've experiencing this in both IOS and Android.

**Comment by TahaTesser** [comment]
Hi @brenoasm 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
