### ISSUE TITLE
Flutter Fuchsia tests are consistently losing the connection to the device

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#67538]
https://chromium-swarm.appspot.com/task?id=4f1ca55724894a10

@arbreng 

Marking P1 due to blocking Fuchsia SDK rolls.

**Comment by godofredoc** [comment]
Not sure exactly what is happening here, I'll need to keep digging to find what is causing this flakiness.

**Comment by zanderso** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/67942
