### ISSUE TITLE
[flutter_tools] Add --verify-only flag to flutter upgrade

### ISSUE THREAD

**Issue by RoyARG02** [flutter/flutter#67532]
## Use case
When running `flutter upgrade` it begins to pull the latest update immediately. Asking the user first before downloading may help in case of bandwidth constraints.
Currently a similar functionally is exhibited by running `flutter doctor`.

## Proposal
`flutter upgrade` should first look for new versions, and then display (if available), the upgrade version along with the version installed in the user's system asking if it would continue (y/N). Additional information, for example, changelog or size of download can be included.

Running something like `flutter upgrade -y` would immediately download the update skipping the behavior mentioned above.

Consequently in that case the ability to check for updates by running `flutter doctor` would then have to be removed (or not, since it doesn't quite behave like the proposal).

**Comment by feinstein** [comment]
IMHO if you run `flutter upgrade` you are commanding it to upgrade. You could add a flag like `flutter upgrade --verify` or similar that would just check if there's an upgrade, as you wish.

**Comment by christopherfujino** [comment]
I agree with @feinstein, it sounds like what you are asking for is a new, non-destructive command that will inform you of whether or not there is a newer version available. Or is there another reason for changing the default behavior of `flutter upgrade`?

**Comment by RoyARG02** [comment]
Having the y/N option to download a newer update would prevent fetching updates if the user didn't wanted to, and will behave similar to a typical package manager; and in case the user did want to, they can continue nonetheless without typing another command by just pressing `y`(or directly provide `flutter upgrade -y`, which would make more sense considering the y/N option).

Making the upgrade check be done by flags like `flutter upgrade --verify` or `flutter upgrade --check` would defeat the purpose of making one command fit all needs, and at the same time users may not know the existence of such flags in the first place.

**Comment by christopherfujino** [comment]
> Having the y/N option to download a newer update would prevent fetching updates if the user didn't wanted to

Why would they type `flutter upgrade` if they didn't want to upgrade?

Changing the default behavior of `flutter upgrade` would be a major breaking change. It's important to note also, that many (most?) invocations of `flutter upgrade` are on CI or by the IDE plugins without an interactive terminal, where providing STDIN `"y"` would be nontrivial. This would be a significant break to Flutter's own CI setup.

> Making the upgrade check be done by flags like flutter upgrade --verify or flutter upgrade --check would defeat the purpose of making one command fit all needs

I don't think the goal of the tool is to have a single command fit all needs. This especially complicates testing (tests that provide STDIN to a CLI tool are difficult to write and tend to be flaky). It's easier to test simpler commands that have a stable behavior.

**Comment by RoyARG02** [comment]
>Why would they type flutter upgrade if they didn't want to upgrade?

So that they can check whether a new update is available. As I have said in the OP, `flutter doctor` does exactly that without informing the version differences between the user the current latest.

>Changing the default behavior of flutter upgrade would be a major breaking change. It's important to note also, that many >(most?) invocations of flutter upgrade are on CI or by the IDE plugins without an interactive terminal, where providing STDIN "y" >would be nontrivial. This would be a significant break to Flutter's own CI setup.

I understand. Adding additional flags to only check updates would then make sense.

In that case, is it possible for the `A new version of Flutter is available!` message of `flutter doctor` be appended with something like
```
...
For more information, run "flutter upgrade --check".
To upgrade now, run "flutter upgrade".
```

**Comment by christopherfujino** [comment]
Updated the title to add a `flutter upgrade --verify-only` flag, which I think would be a great value add. I can try getting around to implementing this next week, or if you file a PR @RoyARG02 I can review it.

**Comment by RoyARG02** [comment]
@christopherfujino I've created the appropriate PR, please have a look whenever you get some time.

**Comment by christopherfujino** [comment]
> @christopherfujino I've created the appropriate PR, please have a look whenever you get some time.
> 
> Should I file a new issue to add the command to the `flutter doctor` message?

Awesome, thanks for the PR! Will review today. And yeah, could file the other issue for the doctor message? Feel free to cc me on it. I suspect rather than directing them to `flutter upgrade --verify-only` we could probably just tell them what the newer version is, but we can discuss on our options on the issue you create.
