### ISSUE TITLE
Luci Windows pre-submit builds are green, but logs report failures

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#67540]
While validating Gold behavior in https://github.com/flutter/flutter/pull/67468, I noticed there was no image for a Windows build:
 https://flutter-gold.skia.org/search?crs=github&fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&issue=67468&limit=50&master=false&match=name&metric=combined&neg=false&offset=0&pos=false&query=source_type%3Dflutter&sort=desc&unt=true

Upon checking the builds, I noticed the Windows builds passed, but the logs specify that 
`ERROR: The process "flutter_tester.exe" not found.` 
It appears that the tests are not actually running, despite reporting a passing result.

Here are the builds in question: 

https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests/2855?

And the logs for each:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867084871833288144/+/steps/Killing_Windows_Processes/0/steps/stop_flutter_tester/0/stdout

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867084871833288160/+/steps/Killing_Windows_Processes/0/steps/stop_flutter_tester/0/stdout

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867084871833288176/+/steps/Killing_Windows_Processes/0/steps/stop_flutter_tester/0/stdout

**Comment by Piinks** [comment]
I checked another PR as well, it appears to be affecting all PRs:

PR: https://github.com/flutter/flutter/pull/67525/checks?check_run_id=1221004617
Build: https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests/2854?
`ERROR: The process "flutter_tester.exe" not found.`

**Comment by godofredoc** [comment]
This is working as intended, the killing windows processes step always try to kill dart, flutter_tester, and some other processes to ensure the task is not leaking processes. If the flutter_tester is being correctly closed then the killing process won't find it when trying to kill it, this is an acceptable outcome and that's the reason why is green.

**Comment by Piinks** [comment]
Are windows tests actually being run though? Gold is not receiving images from Windows.

**Comment by godofredoc** [comment]
Moving to P2 while we triage the remaining issues.

**Comment by Piinks** [comment]
OH I think I see now. Sorry, the UI is confusing.

**Comment by Piinks** [comment]
I think we can close this, I was looking in the wrong place on the build dashboard.
