### ISSUE TITLE
Consider cleaning up PR template

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#67544]
Can we make the PR template shorter, and then augment it with bot-posted help, similar to how we detect missing tests?

**Comment by xster** [comment]
Seems like we don't actually link to https://github.com/flutter/flutter/wiki/Running-and-writing-tests anywhere. We probably should and document how to run tools tests whether it's in the blanket template or in a bot response.

**Comment by Hixie** [comment]
We should also link to wiki/Chat.
