### ISSUE TITLE
webview_flutter package

### ISSUE THREAD

**Issue by dcruzwil** [flutter/flutter#67551]
Keyboard does not close after search results returned.
1. Go to any website enter a search string in the search field and press enter on the keyboard.
2. the search page displays the result but the keyboard remains open.

Tested on www.google.com and other websites.
![flutterwebview](https://user-images.githubusercontent.com/66650545/95377803-0e795b80-08b1-11eb-839a-e094fe6feb2c.gif)

**Comment by darshankawar** [comment]
@dcruzwil 
There's similar open issue describing your case, [36478](https://github.com/flutter/flutter/issues/36478).
Please follow-up there for updates and any questions.
Closing this as duplicate.
