### ISSUE TITLE
Crashes on startup for simple Flutter apps

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6755]
I'm regularly getting crashes like the following on startup:

11-07 22:48:20.926 23429 23447 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 23447 (ui_thread)

I haven't noticed a particular pattern to it.

**Comment by abarth** [comment]
Is there a stack?  That looks like a null pointer dereference.

**Comment by Hixie** [comment]
I haven't seen a stack, no. Agreed that it looks like a null deref.

**Comment by Hixie** [comment]
Just got this, happened after a hot reload:

11-07 23:26:31.169 23574 23592 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 23592 (Thread-3)

**Comment by Hixie** [comment]
I was running with a several-day-old debug android build, and got the same again, this time just out of the blue (I wasn't doing anything with the app, it was just running on the phone next to me):

11-07 23:46:09.412 25437 25455 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 25455 (Thread-3)

No stack (I thought maybe a debug build would show one, but no).

**Comment by Hixie** [comment]
Could be OOMs maybe?

**Comment by Hixie** [comment]
(In which case https://github.com/flutter/flutter/issues/6500 is about how this is hard to diagnose currently.)

**Comment by Hixie** [comment]
heap.global.used.max was at 31MB when it crashed just now.

**Comment by Hixie** [comment]
The last few have been crashes while the app is up. Just now I got a crash on startup with this message (no libc crash log entry):

11-08 00:53:09.063 29226 29248 W flutter : LEAK: 20 RenderObject

**Comment by Hixie** [comment]
So it looks like I get "LEAK: 12 RenderObject" (or 20, like above) when the code being run is bogus somehow. It finished the file sync, then tries to launch the app and immediately crashes without a stack.

**Comment by Hixie** [comment]
Might not be OOM, I later took the heap to 47MB without issue.

**Comment by eseidelGoogle** [comment]
ui_thread could be dart vm.  Could you update with flutter version and device info?

**Comment by Hixie** [comment]
Tip of tree everything as of yesterday, and my Nexus 6.

**Comment by Hixie** [comment]
Haven't seen this so much anymore.

**Comment by rxlabz** [comment]
I have exactly the same error on a low end Android 7.0 device ( 1GRAM, QuadCore 1.3GHz). First it was only when the flutter app downloaded a large file, now it sometimes happens even at launch.
Is there some Flutter minimum requirement ?
I never had this error on my regular "medium end" devices, but my client buy some of these (https://www.archos.com/fr/products/tablets/platinum/archos_101platinum3g/index.html), only to use my Flutter app, and the app keeps crashing. What kind of info can I add here to help find the reason of this crash.

**Comment by eseidelGoogle** [comment]
@rxlabz I recommend opening a new bug, I suspect your crash is unrelated to this old one?

The device type as well as a stacktrace or tombstone from the android crash (or playstore logs) would help us to fix!  Very happy to look with that information.

**Comment by rxlabz** [comment]
Thanks @eseidelGoogle. I think that I "miraculously" found a workaround to my problem.

=> my app needs to download files. If I use the http `readBytes()` and `file.writeAsBytes(bytes)`, app crashes on some devices when the user try to download large files ( 150Mo ), but seems to work if I use HttpClientResponse.pipe( new File('my file.mp4').openWrite() ). Does it sounds plausible ? 

Do you think it worth a new issue with more details ?
