### ISSUE TITLE
Engine build_and_benchmark_linux_release blocking LUCI migration

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#67579]
build_and_benchmark_linux_release is one of the remaining tasks in Cirrus and it is currently blocking migration to LUCI.

To be able to migrate this task we need to update metrics_center to run from within  a luci context.

The current metrics_center code is coming from a private repository:

https://cs.opensource.google/flutter/engine/+/master:testing/benchmark/pubspec.yaml;l=8

We'll need to move the code to one of the flutter projects and update it to use the token generated by luci when running from a luci contex.

Link to the blocking task:
https://cs.opensource.google/flutter/engine/+/master:.cirrus.yml;l=35

**Comment by godofredoc** [comment]
\cc @pcsosinski

**Comment by liyuqian** [comment]
I'll set this as one of my highest priority task with an estimated October milestone.

**Comment by godofredoc** [comment]
I think I still owe you the instructions to pass the luci token. I'm enabling the docs task and will share the instructions once I make that task work.

**Comment by iskakaushik** [comment]
This is currently blocking https://github.com/flutter/flutter/pull/67563.

**Comment by chinmaygarde** [comment]
@liyuqian Any progress on this issue?

**Comment by liyuqian** [comment]
I'm still waiting for @godofredoc 's [instructions to pass the luci token][1]. Meanwhile, I'm checking KMS as suggested by Dan.

[1]: https://github.com/flutter/flutter/issues/67579#issuecomment-705262832

**Comment by godofredoc** [comment]
Sorry about the delay, here is an example of how to generate the token:

https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/firebase/api.py;l=25

The token is written to a file and passed as an env to the perf tool. The tool can read the token and use it directly in the "Authorization: Bearer <content of token file>" header of the skia requests.

This would enable to write directly to skia without having to save the data to the datastore.

**Comment by chinmaygarde** [comment]
@liyuqian put a doc out for this and is working on it this quarter.

**Comment by liyuqian** [comment]
This will be closed by https://github.com/flutter/engine/pull/22240 soon.

**Comment by liyuqian** [comment]
This is done. Closing.
