### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#6757]
Change pub manager to flutter packages manager in the plugin for atom and intellj.

**Comment by eseidelGoogle** [comment]
I'm not sure exactly what this means, but @pq would know.

**Comment by arcas0803** [comment]
Means that you need to use the package manager to upgrade the pubspect.yaml with the flutter sdk inside, so instead of using the terminal just expand the plugin to update those packages using flutter tools.

**Comment by sethladd** [comment]
Ah, thanks! So, in IntelliJ, when coding a Flutter project, if you right-click on a pubspec.yaml and select "pub get", the plugin should run "flutter packages get" instead of "pub get".  Makes sense :)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
I think we effectively do - we set the FLUTTER_ROOT env variable before running pub get. /cc @pq

**Comment by pq** [comment]
This *should* work with the updated Dart plugin.  See https://github.com/flutter/flutter-intellij/issues/390 for a bit more context.

**Comment by sethladd** [comment]
@arcas0803 can you please try again? We think this should work. I'm going to close this issue, but if the behavior isn't as you expect in the latest version of the plugin, please reopen and provide reproduction instructions. Thank you!
