### ISSUE TITLE
Test platform views on iOS using metal backend

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#67573]
after https://github.com/flutter/engine/pull/17881 we'll be able to run metal simulator tests, but we need updated goldens and be able to make sure that we can handle any differences between various mac minis in the fleet of macs we use.

Ideally we'd use Skia gold for this.

/cc @cyanglaz @Piinks @nturgut (who I think is also looking at gold for the engine repo)

**Comment by Piinks** [comment]
Do you mean we need a way to test metal goldens and non-metal goldens?

**Comment by dnfield** [comment]
If we can test the metal goldens it's probably not as essential to test the non-metal goldens.

But if we start testing metal goldens, Gold would be able to help us with:

- Tracking changes across SDK versions
- Tracking differences across different host GPU versions on different mac minis

**Comment by cyanglaz** [comment]
This is awesome, we might need to migrate the scenario app screenshot tests to metal simulators.

**Comment by jonahwilliams** [comment]
Closing as obsolete
