### ISSUE TITLE
Use app deltas for faster and smaller incremental iOS app installs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#67580]
Figure out how to get app deltas working in Xcode/[ios-deploy](https://github.com/ios-control/ios-deploy/pull/434) to avoid recopying the same files across installs.

@anirudhb started this investigation https://github.com/flutter/flutter/pull/60408#issuecomment-656947978:

> fwiw I did try the new ios-deploy with app deltas, but it seems that Flutter builds the app in such a way that app deltas copies the entire app again (including Flutter.framework, which shouldn't've even changed.)
> 
> The app install time is extremely noticeable over wireless, whereas over USB it's not as significant.

and https://github.com/flutter/flutter/pull/60408#issuecomment-657124511:

> I did some investigation on this, and the gist of it is that Xcode only uses modification time to determine whether to copy a file or not. Some things in the build that change modification time include code signing and framework thinning. Cocoapods additionally does this as well (this could be an upstream issue). After modifying the scripts to preserve modification time across codesign/thin, ~Xcode was successfully able to use app deltas!~ edit: Crazy run errors including a white screen on launch.
> 
> A proper implementation of this would probably involve hash comparisons, since Xcode doesn't do this for some reason when computing app deltas.

**Comment by xster** [comment]
Also https://github.com/ios-control/ios-deploy/issues/475#issuecomment-689059894

**Comment by jmagman** [comment]
This feature will bring second and subsequent install time down from minutes to seconds.  The incremental app installation with app deltas only works if the files in the app bundle haven't been modified (by time stamp) since the last installation.

The dart compilation is already skipped on second builds, so the modifications that would need to be skippable are:

- [x] Thinning the App framework https://github.com/flutter/flutter/pull/76834
- [x] Thinning the Flutter framework https://github.com/flutter/flutter/pull/77007
- [x] Bitcode stripping the Flutter framework https://github.com/flutter/flutter/pull/77329
- [ ] Codesigning
- [ ] Embedding the App and Flutter frameworks
- [ ] Adding [`NSBonjourServices` to the Info.plist](#65138)

Then:
- [ ] Implement app deltas (this issue)
- [ ] Add benchmarks for a second-install to make sure the time doesn't regress

**Comment by xster** [comment]
This would be a superb fix!

**Comment by jmagman** [comment]
The `Thin Binary` build script inputs would be (with `USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES=YES`):
```
${BUILT_PRODUCTS_DIR}/App.framework
${BUILT_PRODUCTS_DIR}/Flutter.framework
${TARGET_BUILD_DIR}/${INFOPLIST_PATH}
```
and outputs:
```
${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/App.framework
${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Flutter.framework
```

> Adding [`NSBonjourServices` to the Info.plist](#65138)

However the Info.plist change is the thing that's tripping the app deltas up.  On an incremental install, Xcode will regenerate the `Info.plist` if it's been changed.  When it changes, `flutter` needs to re-add the `NSBonjourServices` key.  And they thrash so the app always has a timestamp change and the entire app is re-installed every time.

**Comment by jmagman** [comment]
PR for non-prebuilt binaries (the normal `flutter run` or `build` flow at https://github.com/flutter/flutter/pull/77756.

> I ran some numbers (on my machine) building and installing the new non-trivial [gallery app](https://github.com/flutter/gallery) after a `flutter clean`
> The first number is the amount of time `flutter run` takes where I force an exit as soon as the app is launched. The second number is the same, run a second time with no `clean`.
> 
|   | stable      | master |  this PR |
| ----------- | ----------- | ----------- | ----------- |
| 1st | 1:15.08      | 1:14.95       | 1:17.53 |
| 2nd | 48.379   |   45.479      |31.096 |
> So the improvements with thinning (#76834 and #77007), bitcode stripping (#77329), and codesigning (#77664) improved matters by ~3 seconds. App deltas gave us another ~14 seconds.

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/67580#issuecomment-793287831 sounds like this is a recent-ish regression right? Would https://github.com/flutter/flutter/pull/77420 have caught this if something similar happened again?

**Comment by jmagman** [comment]
> However the Info.plist change is the thing that's tripping the app deltas up.  On an incremental install, Xcode will regenerate the `Info.plist` if it's been changed.  When it changes, `flutter` needs to re-add the `NSBonjourServices` key.  And they thrash so the app always has a timestamp change and the entire app is re-installed every time.

That wasn't true at all, I thought the entire app is re-installed every time because the app was being re-signed, caused by the Info.plist change.  The problem was actually because `flutter` was copying around the app bundle to a new directory every time it built, which was updating all the timestamps and defeating the incremental installer.  https://github.com/flutter/flutter/blob/047dcc70de3b46edd9c943a6d15ca829fdadebd0/packages/flutter_tools/lib/src/ios/mac.dart#L433-L441

I fixed that by making it an rsync instead https://github.com/flutter/flutter/pull/77756.
https://github.com/flutter/flutter/blob/08b225e03deaaf55ac12e8f3f87c8092ecbaedaa/packages/flutter_tools/lib/src/ios/mac.dart#L435-L440

> [#67580 (comment)](https://github.com/flutter/flutter/issues/67580#issuecomment-793287831) sounds like this is a recent-ish regression right? Would #77420 have caught this if something similar happened again?

I don't think it's a regression, it's just preventing `Thin Binary` from being skippable with input and output files from https://github.com/flutter/flutter/issues/67580#issuecomment-793287831.  Which isn't a big deal now that app deltas are working, that script phase only takes a few milliseconds to run a second time, and while it does make the app binary resign and therefore reupload to the device, it's a really small file.  The small amount of time is probably not worth regressing the local network permission behavior.  The main chunk of remaining time is coming from elsewhere.

**Comment by jmagman** [comment]
The remaining work being tracking is to implement app deltas with `flutter run --use-application-binary`.

**Comment by jmagman** [comment]
The `flutter run` case was done in https://github.com/flutter/flutter/pull/77756 and is in 2.2.0-10.0.pre.  https://github.com/flutter/flutter/issues/90842 is tracking the less-common `--use-application-binary` case.
Closing in favor of that more focused issue.
