### ISSUE TITLE
[pigeon] java: add checks for null nested classes.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#67588]
@gaaclarke 
I have a nested class that I'm passing down to the platform.

```dart

class TrackProxy {
    MediaFormatProxy mediaFormat;
}
```

During development I forgot to initialise the nested 'mediaFormat' class.
The result was an NPE in the java code caused by the following code:

```dart
 static TrackProxy fromMap(HashMap map) {
      TrackProxy fromMapResult = new TrackProxy();
      Object mediaFormat = map.get("mediaFormat");
      fromMapResult.mediaFormat = MediaFormatProxy.fromMap((HashMap)mediaFormat);
```

The call to `map.get("mediaFormat")` correctly returned a null causing the `fromMap` method to throw an NPE when it tried to deserialise the mediaFormat.

The error that is returned provides no details on what went wrong:

```dart
2020-10-08 11:45:59.036 7191-7224/com.bsutton.sounds.sounds_example E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference, null, null)
    #0      SoundsToPlatformApi.startPlayer (package:sounds_platform_interface/sounds_platform_interface.dart:868:7)
    <asynchronous suspension>
    #1      SoundPlayer.play (package:sounds/src/sound_player.dart:310:19)
    <asynchronous suspension>
    #2      SoundPlayerUIState._start (package:sounds/src/ui/sound_player_ui.dart:447:21)
    <asynchronous suspension>
```

To resolve the issue I had to trace through the pigeon java code. 
This process feels onerous.

I think the generated code should include checks that nested objects have been initialised before we try to deserialise the object.
The check then should return a helpful error.

**Comment by xster** [comment]
@gaaclarke we can close this one now right?

**Comment by gaaclarke** [comment]
@xster You talking about after the null safety PR?  That fixed Dart, I haven't looked into this for Java.  I have unit tests for java generated code I'd like to land to assert things like this.

**Comment by xster** [comment]
ah right

**Comment by bsutton** [comment]
If there are concerns about performance we could place the null checks behind a 'debug' build option for pigeon. However I really don't think it will be necessary and not for v 1.0.

**Comment by fmolina199** [comment]
Hi guys, that's still happening on 0.2.2 for Android/Java generated code. Is there any branch where it is sorted?

**Comment by gibahjoe** [comment]
Still happens on current version. Any workarounds apart from manually editing the code?

**Comment by gaaclarke** [comment]
I would have expected this to be resolved in 0.3.0 when we moved to the custom codec.  I haven't gotten around to verifying it yet though.  Care to share what code change you had to make in 0.3.0?

**Comment by gaaclarke** [comment]
I just looked into this a bit further.  It still happens in 0.3.0, but it is a bit different.  To be clear, we don't to remove the error, that is correct.  We want to make the error more clear.

**Comment by gaaclarke** [comment]
I added the following test:
```java
  @Test
  public void encodeWithNullField() {
    Pigeon.NestedRequest request = new Pigeon.NestedRequest();
    request.setContext("hello");
    MessageCodec<Object> codec = Pigeon.NestedApi.getCodec();
    ByteBuffer message = codec.encodeMessage(request);
  }
```

Pigeon:
```dart
enum LoadingState {
  loading,
  complete,
}

class SetRequest {
  int? value;
  LoadingState? state;
}

class NestedRequest {
  String? context;
  SetRequest? request;
}

@HostApi()
abstract class Api {
  void setValue(SetRequest request);
}

@HostApi()
abstract class NestedApi {
  void setValueWithContext(NestedRequest request);
}
```

The exception was:
```
java.lang.NullPointerException
	at com.example.android_unit_tests.Pigeon$NestedRequest.toMap(Pigeon.java:99)
	at com.example.android_unit_tests.Pigeon$NestedApiCodec.writeValue(Pigeon.java:199)
	at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:73)
	at com.example.android_unit_tests.PigeonTest.callWithNullField(PigeonTest.java:112)
        ...
```

Pigeon.java:99 is `toMapResult.put("request", request.toMap());`

I don't think it is that difficult to debug currently, right?

**Comment by fmolina199** [comment]
Hi @gaaclarke,

Could you explain the choice of keeping the NPE? 
By the Flutter code, on your sample, those are not mandatory fields, SetRequest is nullable in NestedRequest. And it would make sense for me to not have all parameters in that object. Adding a validation for null and ignoring the object if not sent is not more compatible with the generated code on Flutter?

Thank you in advance.

**Comment by gaaclarke** [comment]
Okay, I was wrong.  I was thinking we wanted NPE because we wanted those to be nonnull fields but are working around the limitations of Java's null safety.

What I'm realizing is that the code looks like this in pigeon:
```dart
class Foo {}
class Bar {
  Foo? foo;
}
@HostApi()
abstract class Api {
  void x(Bar bar);
}
```

That means that the `foo` field should be allowed to be null.  That's how it works in Dart and how it should work in Java.  I was mistaken.  I'll fix it.  Thanks for pushing back.

**Comment by gaaclarke** [comment]
I've posted a fix for it here: https://github.com/flutter/packages/pull/430  But just know that I'm in the midst of a massive overhaul of pigeon for a 1.0 release and this PR is in the middle of it.  So it's probably going to delay the time until it is posted to pub.
