### ISSUE TITLE
Flutter project duplicates files within itself(ie adds android files under ios section

### ISSUE THREAD

**Issue by iNeedHelpX** [flutter/flutter#67599]
Hey something weird is going on here! When I run my project the entirety of the project duplicates within! This isnt normal. Seems to be slightly tied to updating Xcode (this hell started happening to me a few weeks ago when I updated)and/or adding my developer account in the Signing and Capabilities section. But def these things started occurring when I updated to Xcode 12...

The actual error is "/Users/juliapak/Documents/allnew/ios/Runner/AppDelegate.swift:10:5: error: cannot find
    'GMSServices' in scope" However that's actually where it is supposed to be, however I think its getting lost in all these duplicated files! GRR...
 
<img width="294" alt="Screen Shot 2020-10-07 at 11 50 36 PM" src="https://user-images.githubusercontent.com/41366455/95413394-4c9a6d80-08f9-11eb-8b75-fc51d3430d7d.png">

## Output of flutter run

```
juliapak@julias-MacBook-Pro allnew % flutter run
Running "flutter pub get" in allnew...                              0.6s
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              3.6s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.1s
Xcode build done.                                           28.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/juliapak/Documents/allnew/ios/Runner/AppDelegate.swift:10:5: error: cannot find
    'GMSServices' in scope
        GMSServices.provideAPIKey("MYAPIKEYSHHHSECRET!")
        ^~~~~~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```
## Steps to Reproduce

1. added development team in xcode
2. flutter run

I've also tried removing Derived Data, clean build folder and flutter clean to get it to run

##Output of flutter doctor -v

```
juliapak@julias-MacBook-Pro allnew % flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-8.0.pre.217, on Mac OS X 10.15.7 19H2 x86_64, locale en-CA)
    • Flutter version 1.23.0-8.0.pre.217 at /Users/juliapak/flutter
    • Framework revision 8d9e0d4b95 (3 hours ago), 2020-10-07 18:07:10 -0700
    • Engine revision 7e6191de07
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/juliapak/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • ECDF0608-2613-4A15-8DDC-FC0A2DF44704 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @iNeedHelpX 
Does this reproduce ina new project without `GMSServices`? 
I tried on the latest `master` channel, app runs fines and there are duplicate files in the project and also tried with maps podfile and `GMSServices.provideAPIKey("MYAPIKEYSHHHSECRET!")`  inside `AppDelegate` 

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        10.2s
Xcode build done.                                           24.5s
Waiting for iPhone 11 Pro Max to report its views...                 6ms
Syncing files to device iPhone 11 Pro Max...                       281ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
http://127.0.0.1:60914/TvBggtSNatY=/
```
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.222, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.222 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision d2858f00dd (4 hours ago), 2020-10-08 09:39:13 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 8077196C-CC09-401F-8842-06A94368FF46 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by iNeedHelpX** [comment]
I think it may have something to do with the files in my flutter install. This is how it looks 
<img width="882" alt="Screen Shot 2020-10-08 at 9 47 07 AM" src="https://user-images.githubusercontent.com/41366455/95467546-96ac3f00-094b-11eb-8078-b6f1e18fa4c2.png">

**Comment by iNeedHelpX** [comment]
> Hi @iNeedHelpX
> Does this reproduce ina new project without `GMSServices`?
> I tried on the latest `master` channel, app runs fines and there are duplicate files in the project and also tried with maps podfile and `GMSServices.provideAPIKey("MYAPIKEYSHHHSECRET!")` inside `AppDelegate`
> 
> ```
> Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
>  
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                        10.2s
> Xcode build done.                                           24.5s
> Waiting for iPhone 11 Pro Max to report its views...                 6ms
> Syncing files to device iPhone 11 Pro Max...                       281ms
> 
> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h Repeat this help message.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).
> An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
> http://127.0.0.1:60914/TvBggtSNatY=/
> ```
> 
> flutter doctor -v

No, in a new project everything does fine

**Comment by iNeedHelpX** [comment]
This may be an ongoing issue, but I'll close for now until I'm able to do some more digging :)

**Comment by myoganugraha** [comment]
hi,
i have same problem, and the answer from so solve my problem
with add 
`import GoogleMaps`
to AppDelegate.swift

[](https://stackoverflow.com/questions/33862893/use-of-unresolved-identifier-gmsservices)

**Comment by DaniSalermi** [comment]
> hi,
> i have same problem, and the answer from so solved my problem
> just add
> `import GoogleMaps`
> to AppDelegate.swift
> 
> [stackoverflow](https://stackoverflow.com/questions/33862893/use-of-unresolved-identifier-gmsservices)

This solve the problem for me :D 
Thank you
