### ISSUE TITLE
Brand-new app does not analyze cleanly with dart 1.14-dev.1.0

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#676]
On the alpha branch.
Just ran `flutter init -o .`
Then, ran `flutter analyze lib/main.dart`

Expected: No errors/warnings/hints

Actual:

```
~/flutter/coolbeans $ flutter analyze lib/main.dart 
[error] Field declaration HitTestEntry.target cannot be overridden in BoxHitTestEntry. (/Users/sethladd/Code/flutter/packages/flutter/lib/src/rendering/box.dart, line 280, col 3)
[error] Field declaration Simulation.tolerance= cannot be overridden in SimulationGroup. (/Users/sethladd/Code/flutter/packages/newton/lib/src/simulation_group.dart, line 36, col 3)
```

FWIW, the version of Dart that I'm using:

```
~/flutter/coolbeans $ dart --version
Dart VM version: 1.14.0-dev.1.0 (Wed Nov 18 18:01:44 2015) on "macos_x64"
```

Flutter version:

```
~/flutter/coolbeans $ flutter --version
Flutter
Repository: git@github.com:flutter/flutter.git
Branch: alpha
Revision: 4472d06e022cd5fb604c83a850ff20d54073906b (2 days ago)
```

**Comment by sethladd** [comment]
cc @Hixie can we get to zero errors/warnings/hints for a starter project?

**Comment by Hixie** [comment]
Are these new checks in 1.14? Or are they things we missed? I thought we checked an init-created package in Travis.

**Comment by abarth** [comment]
I'm confused about what version of the Dart SDK we support.  Currently we support the stable version of the Dart SDK, which is 1.13.

I don't think we want to support multiple versions of the Dart SDK.  Should we pin the version of the Dart SDK to require an exact version to be clear about what's supported?

**Comment by Hixie** [comment]
q.v. https://github.com/flutter/flutter/issues/546

**Comment by jamesr** [comment]
What's the relationship between the Dart SDK the package declares it supports and the VM source you can use?  In Mojo (and in some internal codebases) we're building from Dart VM version: 1.14.0-dev.1.0, would this version of the Dart tools no longer work with Flutter if the constraint was written this way?

**Comment by abarth** [comment]
> What's the relationship between the Dart SDK the package declares it supports and the VM source you can use?

The Dart SDK controls the version of Dart we use to execute code on the host machine.  It has no relation to the version of Dart we use to execute code inside Flutter on the target machine.

> would this version of the Dart tools no longer work with Flutter if the constraint was written this way?

Depends what you mean by "building from".  Do you mean "use to execute Dart code on the host machine" or you do mean "compile and link into a binary that runs on a target machine"?

**Comment by jamesr** [comment]
The analyzer runs on the host so I think that would be the relevant one for this particular issue, right?  Wouldn't you want that to match up with the version of Dart used by the snapshot binary on the host (which has to exactly match the VM on the target)?

**Comment by jamesr** [comment]
Adam helped me get sorted out offline.  For reference, Mojo (and other internal repos) are currently targeting the 1.14.0-dev.1.0 SDK for access to dart:developer for tracing stuff as of domokit/mojo@653331f1044ffe38a010e6bc33450fbdc9794cc5.

**Comment by abarth** [comment]
@sethladd I thought it might be easier to fix those warnings, but I don't understand them.  Can you help me understand why they're flagging those lines as errors?

**Comment by zoechi** [comment]
@abarth Looks like dart-lang/sdk#24928

**Comment by abarth** [comment]
@zoechi Thanks.  I wonder if we should suppress this error since it appears to be related to DDC (which we don't use).  I guess we should ask how this impacts AOT compilation for DartVM.

**Comment by Hixie** [comment]
Yeah we should silence this error.

**Comment by sethladd** [comment]
cc @leafpeterson - Should we see this error from strong mode? (is it really an error?)

BoxHitTestEntry (child): https://github.com/flutter/flutter/blob/11da9b02ab80a4465c05d907c5042f49b113662b/packages/flutter/lib/src/rendering/box.dart#L305 where target returns a `RenderBox` (which extends RenderObject which implements HitTestTarget https://github.com/flutter/flutter/blob/335f583564aeb1f24f28e4a0ffc950be2e275dba/packages/flutter/lib/src/rendering/object.dart#L393)

HitTestEntry (parent): https://github.com/flutter/flutter/blob/e0107b05369c1a3a3cdf9afd2f79011adcddaf0a/packages/flutter/lib/src/rendering/hit_test.dart#L21 where target returns a `HitTestTarget`


>  Currently we support the stable version of the Dart SDK, which is 1.13.

This is true. Consider this bug an early warning. Once 1.14 goes stable, this will hit us.

**Comment by zoechi** [comment]
It's a strong-mode error but `.analysis_options` should already support to disable it

dart-lang/sdk#25104

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/task/strong/info.dart#L506

**Comment by sethladd** [comment]
Thanks @zoechi . Something for @pq to help us with in _embedder.yaml ?

**Comment by leafpetersen** [comment]
This is currently a strong mode error, but one that is primarily there to avoid making every field a virtual getter.  @vsm provides some context towards the bottom of the discussion in dart-lang/sdk#24928 .  

This is pretty likely to be a performance anti-pattern for any AOT Dart compiler - if you override a field with a getter, then every access to that field is implicitly a call to a virtual getter, and can only be codegen'ed as a field load if the compiler can prove that no instances of the subclass reach the use site.

We've discussed separating these codegen based warnings from the pure static-analysis related warnings, and/or providing annotations to opt-out on a per declaration basis, but these are currently fairly low on our priority list.  There's also an argument that one of the primary motivations for strong mode is to delineate a "well-lit path" within the Dart language for which AOT compilation is likely to be successful (and even more, modular AOT compilation).  From that perspective, there's value in surfacing these even for code which is not solely targeting DDC.

**Comment by Hixie** [comment]
Do you have any advice for how we should implement the things that are hitting this warning?

**Comment by pq** [comment]
> Thanks @zoechi . Something for @pq to help us with in _embedder.yaml ?

Nearly there. :)

@leafpetersen : I'm guessing the codes to suppress are `STRONG_MODE_INVALID_FIELD_OVERRIDE` and `STRONG_MODE_INVALID_METHOD_OVERRIDE`?

**Comment by leafpetersen** [comment]
@pq `STRONG_MODE_INVALID_FIELD_OVERRIDE` is the one for this error.  `STRONG_MODE_INVALID_METHOD_OVERRIDE` is the strong mode method override error, which I think the flutter team may want to suppress as well.

**Comment by leafpetersen** [comment]
@ianh  The patterns for working around this depend a bit on what you're trying to accomplish.

One pattern is to move the fields into the subclasses, and make the super class abstract with a getter.  At quick glance that looks like it might work here.

Another pattern (if all you want to do is tighten the type) is to make the super class generic over the field type, and then make the subclasses implement a concrete specialization of the super class.  This doesn't scale very well to multiple fields though.

In the general case where you really do want the virtual getter semantics, then you can put a private field on the super class with a getter, and then override the getter in the sub classes.  This doesn't avoid the performance issue - it's just a way of explicitly opting in to the virtual dispatch.

**Comment by iposva-google** [comment]
@leafpetersen Please do not bunch DDC and the VM's AOT compilation into one group. They have completely different performance characteristics. And what that "well-lit" path is supposed to be is entirely unclear depending on the implementation.
