### ISSUE TITLE
Android - Keyboard should not suggest when hideText on an Input is activate

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#6760]
## Steps to Reproduce

On Android when `hideText: true` on an Input, the keyboard is still showing suggestion.
I don't want the keyboard to show my password in the suggestion box.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/lejard_h/flutter
    • Framework revision 04e7446b2b (16 hours ago), 2016-11-07 15:48:50
    • Engine revision 16077d474b
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/lejard_h/Library/Android/sdk
    • Platform android-25, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Ultimate Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

**Comment by eseidelGoogle** [comment]
This came up in Gitter today.

**Comment by cbracken** [comment]
Related iOS bug #9411

**Comment by cbracken** [comment]
Will be fixed on next engine roll.
