### ISSUE TITLE
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by okarpov** [flutter/flutter#67607]
## Steps to Reproduce

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';

List<CameraDescription> cameras;

class TakePicturePage extends StatefulWidget {
  final CameraDescription camera;
  final Orientation orientation;
  TakePicturePage({@required this.camera, this.orientation=Orientation.landscape});

  @override
  _TakePicturePageState createState() => _TakePicturePageState();
}

class _TakePicturePageState extends State<TakePicturePage> {
  CameraController _cameraController;
  Future<void> _initializeCameraControllerFuture;
  Orientation orient=Orientation.landscape;

  @override
  void initState() {
orient = widget.orientation;

    SystemChrome.setPreferredOrientations([orient == Orientation.landscape ? 
      DeviceOrientation.landscapeLeft: DeviceOrientation.portraitUp]);
    super.initState();

    

    _cameraController =
        CameraController(cameras[0]/*widget.camera*/, ResolutionPreset.ultraHigh);
        
        
    _initializeCameraControllerFuture = _cameraController.initialize();
    _initializeCameraControllerFuture.then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
    
  }

  void _takePicture(BuildContext context) async {
    
    try {
      await _initializeCameraControllerFuture;

      final path =
          join((await getTemporaryDirectory()).path, '${DateTime.now()}.png');

      await _cameraController.takePicture(path);

      Navigator.pop(context,path);

    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Stack(children: <Widget>[
      FutureBuilder(
        future: _initializeCameraControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return  RotatedBox(
        quarterTurns: orient == Orientation.landscape ? 3 : 0,//MediaQuery.of(context).orientation == Orientation.landscape ? 3 : 0,
        child: AspectRatio(
          aspectRatio: _cameraController.value.aspectRatio,
          child: CameraPreview(_cameraController),
        ));
      
          } else {
            return Center(child: CircularProgressIndicator());
          }
        },
      ),
      SafeArea(
        child: Align(
          alignment: orient == Orientation.landscape ?Alignment.topRight:Alignment.bottomRight,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: FlatButton(
              shape: RoundedRectangleBorder(borderRadius: new BorderRadius.circular(30.0)),
              padding: EdgeInsets.all(20),
            splashColor: Colors.red,
              color: Colors.green,
              child: Icon(Icons.camera, size: 56,),
              onPressed: () {
                _takePicture(context);
              },
            ),
          ),
        ),
      )
    ]);
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp,DeviceOrientation.landscapeLeft,DeviceOrientation.portraitDown,DeviceOrientation.landscapeRight]);
    _cameraController.dispose();
    super.dispose();
  }
}

## Logs

E/CameraCaptureSession( 9632): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 9632): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 9632): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2231)
E/CameraCaptureSession( 9632): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1241)
E/CameraCaptureSession( 9632): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession( 9632): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:480)
E/CameraCaptureSession( 9632): 	at io.flutter.plugins.camera.Camera.close(Camera.java:486)
E/CameraCaptureSession( 9632): 	at io.flutter.plugins.camera.Camera$2.onError(Camera.java:187)
E/CameraCaptureSession( 9632): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1629)

```
```

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19042.546], locale en-US)
    • Flutter version 1.20.2 at D:\Install\Android\flutter_sdk\flutter
    • Framework revision bbfbf1770c (8 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\OKarpov\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

```
```
debugging under Pixel 2 API 30 emulator
using virtual camera

**Comment by okarpov** [comment]
one time error was

W/Gralloc4(10846): allocator 3.x is not supported
E/BufferQueueProducer(10846): [SurfaceTexture-0-10846-0](id:2a5e00000000,api:4,p:408,c:10846) dequeueBuffer: attempting to exceed the max dequeued buffer count (3)
E/CameraCaptureSession(10846): Session 0: Exception while stopping repeating:

**Comment by okarpov** [comment]
E/Surface (11674): getSlotFromBufferLocked: unknown buffer: 0x0
I/flutter (11674): CameraException(Uninitialized CameraController., takePicture was called on uninitialized CameraController)

**Comment by okarpov** [comment]
E/BufferQueueProducer( 4818): [SurfaceTexture-0-4818-7](id:12d200000015,api:4,p:401,c:4818) dequeueBuffer: attempting to exceed the max dequeued buffer count (3)
E/CameraCaptureSession( 4818): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 4818): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:459: Camera 0: Error clearing streaming request: Function not implemented (-38)

so the issue mainly with the virtual scene camera

**Comment by okarpov** [comment]
W/Gralloc4( 5726): allocator 3.x is not supported
E/BufferQueueProducer( 5726): [SurfaceTexture-0-5726-0](id:165e00000000,api:4,p:401,c:5726) dequeueBuffer: attempting to exceed the max dequeued buffer count (3)
E/CameraCaptureSession( 5726): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 5726): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:459: Camera 0: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1009)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1251)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:789)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
E/CameraCaptureSession( 5726): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession( 5726): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession( 5726): 	at android.os.Looper.loop(Looper.java:223)
E/CameraCaptureSession( 5726): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/CameraCaptureSession( 5726): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 5726): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/CameraCaptureSession( 5726): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/CameraCaptureSession( 5726): Caused by: android.os.ServiceSpecificException: cancelRequest:459: Camera 0: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession( 5726): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
E/CameraCaptureSession( 5726): 	at android.os.Parcel.createException(Parcel.java:2357)
E/CameraCaptureSession( 5726): 	at android.os.Parcel.readException(Parcel.java:2340)
E/CameraCaptureSession( 5726): 	at android.os.Parcel.readException(Parcel.java:2282)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:732)
E/CameraCaptureSession( 5726): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession( 5726): 	... 11 more

**Comment by darshankawar** [comment]
@okarpov 
There's similar open issue describing your case, [61544](https://github.com/flutter/flutter/issues/61544).
Please follow-up there for updates and any questions.
Closing this as duplicate.

**Comment by darshankawar** [comment]
Also, since you are using api 30, try adding below permission in manifest and try again to see if it works.

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

**Comment by okarpov** [comment]
so the issue mainly with the virtual scene camera for API 30
(also have one client with real device and the same issue)

**Comment by okarpov** [comment]
> Also, since you are using api 30, try adding below permission in manifest and try again to see if it works.
> 
> `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

didn't help

**Comment by SaloxiddinTursunaliev** [comment]
Hey, have you found a solution to your problem?

**Comment by SaloxiddinTursunaliev** [comment]
Hey @okarpov and @darshankawar ! 
Have you found a solution for this issue?
I am also having this issue
