### ISSUE TITLE
No Option to wrap hintText of TextField.

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter#67619]
There is no option in a flutter to set the `overFlow` property of `hintText` in flutter textField.

**Comment by sidrao2006** [comment]
Hello @DhavalRKansara , you can use `InputDecoration` which is passed as decoration to the `TextField`

**Comment by DhavalRKansara** [comment]
@sidrao2006 Using `InputDecoration` I can set the `maxLine`, TextStyle of the `hintText` but If there is no option for setting `textOverFlow` property for the `hintText`

**Comment by sidrao2006** [comment]
You have to set the style of the hint text. `TextStyle` has an overflow property

**Comment by DhavalRKansara** [comment]
```
  const TextStyle({
    this.inherit = true,
    this.color,
    this.backgroundColor,
    this.fontSize,
    this.fontWeight,
    this.fontStyle,
    this.letterSpacing,
    this.wordSpacing,
    this.textBaseline,
    this.height,
    this.locale,
    this.foreground,
    this.background,
    this.shadows,
    this.fontFeatures,
    this.decoration,
    this.decorationColor,
    this.decorationStyle,
    this.decorationThickness,
    this.debugLabel,
    String fontFamily,
    List<String> fontFamilyFallback,
    String package,
  }) : fontFamily = package == null ? fontFamily : 'packages/$package/$fontFamily',
       _fontFamilyFallback = fontFamilyFallback,
       _package = package,
       assert(inherit != null),
       assert(color == null || foreground == null, _kColorForegroundWarning),
       assert(backgroundColor == null || background == null, _kColorBackgroundWarning);
```

@sidrao2006 Where???

**Comment by sidrao2006** [comment]
I am really sorry

You can set `hintMaxLines` to a number greater than 1. That may help

**Comment by DhavalRKansara** [comment]
> You can set `hintMaxLines` to a number greater than 1. That may help

Look at my question @sidrao2006 I want to set `overFlow` property.

**Comment by sidrao2006** [comment]
> This value is passed along to the Text.maxLines attribute of the Text widget used to display the hint text. TextOverflow.ellipsis is used to handle the overflow when it is limited to single line.

From the docs

And if you are requesting for this feature, please checkout - #20569

**Comment by DhavalRKansara** [comment]
> And if you are requesting for this feature, please checkout - #20569

Yeah great, I am closing this issue as [#20569](https://github.com/flutter/flutter/issues/20569) is already open.
