### ISSUE TITLE
Webview, how to block any subrequests from webview.

### ISSUE THREAD

**Issue by Bes79** [flutter/flutter#67618]
Hi. I have a question - is any way to block all subrequests from webview. I want to get simple html, but this process is taking too long due to subqueries like ajax, css, javascript, iframe, img, etc.

**Comment by darshankawar** [comment]
@Bes79 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
