### ISSUE TITLE
class TextSelection required fields on Flutter 1.22.0

### ISSUE THREAD

**Issue by 2math** [flutter/flutter#67610]
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale bg-BG)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

After upgrading to 1.22.0 , 
_TextSelection.collapsed(offset: _tcTextEditingController.text.length)_ is showing an error _"error: The named parameter 'offset' isn't defined."._

When I checked inside the code is
```
const TextSelection.collapsed({
    required int offset,
    this.affinity = TextAffinity.downstream,
  })
```

I think is missed @ for "@required" param.

To hide the error I need to do this _TextSelection.collapsed(int: _tcTextEditingController.text.length)_, but then there is a build error, because there is no such filed int :) .
If I use **offset** the app builds and is OK, but Dart Analysis tab is glowing

I can see same thing on default constructor

```
 const TextSelection({
    required this.baseOffset,
    required this.extentOffset,
    this.affinity = TextAffinity.downstream,
    this.isDirectional = false,
  })
```

Do I need to install some extra packages, for that to be recognized on my side?

**Comment by darshankawar** [comment]
@2math 
See [this](https://github.com/flutter/flutter/issues/67444#issuecomment-704530907) comment for your reference. Try to restart your IDE and try again to see if it works.
Thanks.

**Comment by 2math** [comment]
Thanks @darshankawar ,
Restarting Android Studio didn't work, but restart computer after that did the trick
