### ISSUE TITLE
cant get ios build

### ISSUE THREAD

**Issue by sepehr13494** [flutter/flutter#67617]
I'm trying to build ios wih [codemagic.io](https://codemagic.io/).
here is the error in "installing dependencies" part : 

Did not find any Bundle IDs matching specified filters: identifier=io.flutter.plugins.urlLauncher, platform=IOS.
Creating new Bundle ID: identifier: io.flutter.plugins.urlLauncher, name: 'io flutter plugins urlLauncher', platform: IOS

POST https://api.appstoreconnect.apple.com/v1/bundleIds returned 409: An attribute in the provided entity has invalid value - An App ID with Identifier 'io.flutter.plugins.urlLauncher' is not available. Please enter a different string.

Build failed :|
Failed to fetch signing files using App Store Connect API

**Comment by TahaTesser** [comment]
Hi @sepehr13494 
This is related to Codemagic CI/CD
I recommend you to ask for support directly on their [Slack](https://join.slack.com/t/codemagicio/shared_invite/enQtNzQyODExMTQyMDcwLTQ2NTJjODE3NTA2Njg3Y2ViYmZiNGE1MWMyYWNjY2I0MzRmM2M2YmZhOTE1YTc5YjNkMmI0MzQzZWU0MzA4OGM)
Closing, as this isn't an issue with Flutter itself.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by StanfordLin** [comment]
I was trying to get codemagic to work as well and encountered the same error. 
I fixed it by specifying a bundle identifier in the Build settings -> Publish -> iOS code signing.

I got the the bundle identifier from opening the Runner.xcworkspace in my Flutter project's ios directory, clicking Runner on the left side -> Under Targets, selected Runner -> General tab -> Bundle Identifier
