### ISSUE TITLE
Flutter Web App Error: CHROME_EXECUTABLE= “…” is not executable

### ISSUE THREAD

**Issue by nesjessi** [flutter/flutter#67622]
I wanted to disable web security for my flutter web application. 

I tried:

1. Set `export CHROME_EXECUTABLE=/path/to/google-chrome-unsafe.sh` in `$HOME/.zshrc`
2. Create `google-chrome-unsafe.sh` with the content `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir="tmp-dir" $*`
3. Make it executable with `chmod a+x google-chrome-unsafe.sh`

At first this is how it worked. However, now there is always an error message. Does anyone have any idea how to solve the problem?

![Unbenannt](https://user-images.githubusercontent.com/72548524/95443209-9b2d2380-095c-11eb-84ba-a9783de12632.png)

**Comment by darshankawar** [comment]
@nesjessi 
This question is better suited for StackOver flow. Please see https://flutter.dev/community for resources, and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.

Also, see these comments and check if they are helpful.

https://github.com/flutter/flutter/issues/46904#issuecomment-631247809
https://github.com/flutter/flutter/issues/46904#issuecomment-653088177

**Comment by nesjessi** [comment]
I have a similar problem to #46904 (comment) and #46904 (comment). But it doesn't work anymore. Maybe there is a different problem. Please can you reopen it?
I have no coding problem, it's a problem with starting chrome simulator without web security for flutter.
