### ISSUE TITLE
[share] Provide a way to know if the share was aborted or not

### ISSUE THREAD

**Issue by dotel-saramsz** [flutter/flutter#67637]
Currently the function `share` returns a `Future<void>` which I believe is resolved right after the method `'share'` is invoked on the `MethodChannel` : `plugins.flutter.io/share`. However, this provides no information about whether the user proceeded with the share or aborted the share action.

The platform's share sheet can be closed by:
1. Clicking on the region outside the sheet
2. Pressing the back button on Android
3. Choosing of the options in the share sheet which opens the respective application

A way to differentiate between the cases 1,2 and case 3 would allow us to know if the particular content was **actually shared** or not. I am thinking something like resolving the `Future` with a `bool` upon the dismissal of the share sheet could be added.
```
Share.share("A sample text to share").then((bool isAborted) {
    // Do something now that the share sheet has closed
});
```

However, I also came across [a similar issue](https://stackoverflow.com/questions/27241227/how-to-confirm-android-share-intent-is-successful-or-complete/27241319#27241319) which points out that this is difficult to implement in Android in general.

Is this sort of implementation viable? Or is there any workaround to this?

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
