### ISSUE TITLE
Flutter web app loads slow AFTER installing ssl-certificate

### ISSUE THREAD

**Issue by BlaineFredrickson** [flutter/flutter#67636]
Flutter v1.22

App works GREAT, loads quickly.  Then I installed an ssl-certificate (GoDaddy is site host, and purchased cert from GoDaddy - they helped install).

Load time _was 0.5 - 1.0 second_, **now 4.0 - 5.0 seconds**.

Do I need to do any additional Flutter config to make the app aware of the cert?  Is anyone else experiencing this large change in app load time when going from http to https?

Any ideas are greatly appreciated!

Blaine

**Comment by TahaTesser** [comment]
Hi @BlaineFredrickson 
This doesn't look like it's related to flutter, as there are many queries available on Google for slow loading with SSL 
In your case, for example, https://in.godaddy.com/community/SSL-And-Security/SSL-certificate-install-slowed-down-site/td-p/4588

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
