### ISSUE TITLE
[url_launcher] Add chrome custom tabs

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#67639]
The url_launcher should have the ability to open urls as a custom tab instead of a webview, when the url should be opened in-app.

**Comment by MrBirb** [comment]
@pedromassangocode Duplicate of #18589

**Comment by pedromassangocode** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/18589. For anyone interested in this feature, please follow up on https://github.com/flutter/flutter/issues/18589.

Thanks for the heads up!
