### ISSUE TITLE
[image_picker] Lost Connection

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#67641]
When i pick image second time from ImageGalery, the app crashes without any exception.

But there is log.

image_picker: ^0.6.7+11 is installed

`flutter:
path/Users/mac/Library/Developer/CoreSimulator/Devices/180A9467-FA04-4866-BE10-B5FCFD527D6C/data/Containers/Data/Application/80863F86-972F-4256-B4A0-7A89496A35F0/tmp/image_picker_FFC8F9D7-94FC-422E-88F2-072CA8173573-17517-0000021
EEAAF9B12.jpg
[+5975 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[  +10 ms] DevFS: Deleting filesystem on the device
(file:///Users/mac/Library/Developer/CoreSimulator/Devices/180A9467-FA04-4866-BE10-B5FCFD527D6C/data/Containers/Data/Application/80863F86-972F-4256-B4A0-7A89496A35F0/tmp/davrpayvFISLm/davrpay/)
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +7 ms] "flutter run" took 313 414ms.
[ +261 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 0
`

**Comment by Abhishek01039** [comment]
Hi @II11II 
can you please provide `flutter doctor -v` and minimal reproduction code and also device's android or iOS version?
Thanks.

**Comment by II11II** [comment]
More about crash:
It was detected on Simulator, only.
The code I used is from example of plug-in page in pub.dev

**Comment by anhtaoth** [comment]
> Hi @II11II
> can you please provide `flutter doctor -v` and minimal reproduction code and also device's android or iOS version?
> Thanks.


[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/macos/Documents/flutter
    • Framework revision f30b7f4db9 (2 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.beta.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • D8548E43-3775-4F99-932B-31D6555CCE64 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
