### ISSUE TITLE
Web text field unfocus behaviour.

### ISSUE THREAD

**Issue by shariful2011** [flutter/flutter#67646]
I am developing a web app using flutter web in the master channel there is a small feature that is required in other websites or web applications if I focus on a text field and press outside the text field losses focus but in flutter that doesn't happen.
My Flutter Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.23.0-8.0.pre.147, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)   
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[√] Connected device (4 available)

• No issues found!

**Comment by shariful2011** [comment]
- 

- 

1. 

- 

-

**Comment by nturgut** [comment]
Marking as duplicate: https://github.com/flutter/flutter/issues/32433
