### ISSUE TITLE
[url_launcher] doesn't work when iOS default browser is not set to Safari

### ISSUE THREAD

**Issue by emaddoma** [flutter/flutter#67647]
## Steps to Reproduce

Implement can_launch() and launch()

**Expected results:** 

The url launches

**Actual results:** 

Nothing happens at all

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Closing this as duplicate of [65936](https://github.com/flutter/flutter/issues/65936)
