### ISSUE TITLE
[camera] BitRate and FrameRate

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#67642]
i needed a Feature for camera 

Please work to set the videoBitRate and audioBitRate or Video FrameRate from the flutter

I can't work with ultraHighor or veryHigh and etc

**Comment by TahaTesser** [comment]
Hi @mbfakourii 
I see there is an open issue for the frame rate and I modified the title to bit rate a well, it's easier to reach the issue that way 
Closing as duplicate of https://github.com/flutter/flutter/issues/54339
Thank you
