### ISSUE TITLE
Semantics for text fields behaves oddly on web

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#67649]
When using a textfield on flutter web, the screen reader behavior is quite different from iOS/android.

This is the semantics tree for the textfield:

```
├─SemanticsNode#11
           │   Rect.fromLTRB(24.0, 50.0, 130.0, 130.0)
           │   actions: tap
           │   flags: isTextField, isMultiline
           │   label: "Hour"
           │   value: "07"
           │   textDirection: ltr
           │   currentValueLength: 2
```

If you have a text field configured with a value of `7` and hint text of `Hour`, this is verbalized as a single node on android like so:
`07 hour edit box`

However on web (tested in chrome on macOS), it behaves as multiple nodes and causes an odd experience:
`Hour group`
`Hour text element`
`07 text area`
`end of hour group`

**Comment by nturgut** [comment]
I did a lot of fixes for text editing with the 2 PRs:

https://github.com/flutter/engine/pull/23361
https://github.com/flutter/engine/pull/23256

I think they are very easy to use now. I tested with 5 different combinations (voiceover desktop, voiceover mobile, chromevox desktop, talkback, narrator). Please take another look.

**Comment by rami-a** [comment]
Thanks, it seems to work better now
