### ISSUE TITLE
Flutter is not available for download on my Android and I see Android screenshots in the repository.

### ISSUE THREAD

**Issue by major101x** [flutter/flutter#67650]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by lordvins226** [comment]
Flutter provide sdk for windows, linux and MacOs. You can’t download flutter for android but you can use Flutter to make android app.

**Comment by TahaTesser** [comment]
Hi @major101x 
It's not clear what do you mean by the title, please follow https://flutter.dev/docs/get-started/install to install flutter Closing, Closing, If you disagree, please write in the comments and I will reopen it.
Thank you
