### ISSUE TITLE
InteractiveViewer inside Alert Dialog doesn't show the text while zooming in and out

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#67658]
I have a class that contains the interactiveViewer and I experience the text disappearing when displaying on both of my devices:
1- iPhone 11 (14.0)
2- iPhone 7 (13.5.1)
Simulation mode seems to be fine.
Text, interactiveViewer and RaisedButton are in a column.

My system info:
iMac: 27"
OS: macOS Catalina 10.15.7
VS Code: 1.49.3
Xcode: 12.0

==================== code =============
```
Text(
   'Pinch to Zoom',
    textAlign: TextAlign.center,
    style: TextStyle(
           color: Colors.black,
           fontWeight: FontWeight.bold,
           fontSize: 13.0),
),


ButtonTheme(
    height: 35.0,
    minWidth: 110.0,
    child: RaisedButton(
    color: Colors.white,
    shape: RoundedRectangleBorder(
           borderRadius: BorderRadius.circular(5.0)),
                 child: Text(
                 'Cancel',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                  fontSize: 13.0),
),
```

**Comment by darshankawar** [comment]
@jerryhamby 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by jerryhamby** [comment]
========== my doctor -v ======================

jerryhamby@Jerrys-iMac vdex % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/jerryhamby/Desktop/FlutterExamples/flutter
    • Framework revision f30b7f4db9 (24 hours ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jerryhamby/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7208
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio copy.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone11 (mobile) • 00008030-000650610E40802E • ios • iOS 14.0.1

• No issues found!

========== basic column code  ======================
========== app is too large to include the full class, but this should be enough to reproduce the error ==================

Column(
	children: <Widget>[
	  SizedBox(height: 15),
	  Text(
		'Pinch to Zoom',
		textAlign: TextAlign.center,
		style: TextStyle(
			color: Colors.black,
			fontWeight: FontWeight.bold,
			fontSize: 13.0),
	  ),
	  SizedBox(height: 5),
	  InteractiveViewer(
		boundaryMargin: EdgeInsets.all(20.0),
		minScale: 0.1,
		maxScale: 2.0,
		transformationController: _controller,
		onInteractionEnd: (value) {
		  _controller.value = Matrix4.identity();
		},
		child: Image.network(
		  MyVars.largeimageurl,
		  fit: BoxFit.cover,
		),
	  ),
	  SizedBox(height: MyVars.enlargediff),
	  Padding(
		  padding: const EdgeInsets.only(
			  left: 20.0, right: 10.0, top: 10.0, bottom: 10.0),
		  child: ButtonTheme(
			  height: 35.0,
			  minWidth: 110.0,
			  child: RaisedButton(
				color: Colors.white,
				shape: RoundedRectangleBorder(
					borderRadius: BorderRadius.circular(5.0)),
				child: Text(
				  'Cancel',
				  textAlign: TextAlign.center,
				  style: TextStyle(
					  color: Colors.black,
					  fontWeight: FontWeight.bold,
					  fontSize: 13.0),
				),
				onPressed: () {
				  setState(() {
					Navigator.pop(context);
				  });
				},
			  ))),
	],
  )

**Comment by darshankawar** [comment]
@jerryhamby 
Tried your code sample on latest stable using iPhone 6s (OS 14). Zoomed in and out the image but text color seemed to be fine. Did I miss anything to replicate ?
Can you provide video of the issue ?

[RPReplay-Final1602483962.MP4.zip](https://github.com/flutter/flutter/files/5363296/RPReplay-Final1602483962.MP4.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

**Comment by jerryhamby** [comment]
I looked at your video, but the problem is not with the zoom effect in the interactiveViewer.

The problem is that the text does not appear at that the top of the screen or inside the button.
I have noticed that sometimes the text will appear on the first try but the second time, it disappears.

Sorry I didn't know how to create a video on my iPhone. Got any suggestions?
PS, I only work with the stable version, I'm now on 1.22.1.

**Comment by darshankawar** [comment]
@jerryhamby 
https://support.apple.com/en-in/HT207935 on how to record video on iphone.

**Comment by jerryhamby** [comment]
I have made a video of the problem. My apologies for the quickness of the video.

But it does show, on the screen with the large flowers, that the “pinch to zoom” textfield
is gone and the “cancel” text inside the button is missing. The problem is on this screen with 
the interactive viewer. No where else am I having this disappearing text problem.

This was done on my iPhone 11 running 14.0.1.
I’m also having the exact problem on my iPhone 7 running 13.5.1

Here is a link:
https://www.vdex.com/misc/RpReplay_final1602729711.MP4

**Comment by darshankawar** [comment]
@jerryhamby 
From your video, I see that you are trying to zoom in the picture from an `alert Dialog`. Is that correct ? If so, That is a different case, so you'll need to provide the corresponding minimal code that has alert dialog in it, in order for use to replicate. Because with your original given code sample, I was unable to replicate the issue as you saw in the video I shared earlier.
Thanks.

**Comment by jerryhamby** [comment]
Here is the class I call which opens the popup (includes the column I gave you earlier).
There are a lot of other classes that are required for this to work effectively, 
but my project is so large and it's impossible for me to include everything.

I hope this helps, FYI, I will remove this file shortly.

https://www.vdex.com/misc/expanded.dart.zip <https://www.vdex.com/misc/expanded.dart.zip>

**Comment by darshankawar** [comment]
@jerryhamby 
I tried a simple code sample that opens an alert dialog and then shows a text and image in column and tried to replicate the issue. When the alert dialog opens and I try to zoom in and zoom out the image, the text `Pinch to Zoom` doesn't appear at the top of the image while moving around. Is this a correct interpretation of your issue ?

[67658.mp4.zip](https://github.com/flutter/flutter/files/5389505/67658.mp4.zip)


<details>
<summary>code sample </summary>

```
body: Center(
        child: RaisedButton(
          onPressed: () {
            _showMyDialog();
          },
          child: Text('Open'),
        )
      )
....

Future<void> _showMyDialog() async {
    return showDialog<void>(
      context: context,
      barrierDismissible: false, // user must tap button!
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('AlertDialog Title'),
          content: SingleChildScrollView(
            child: Column(
              children: <Widget>[
                SizedBox(height: 15),
                Text(
                  'Pinch to Zoom',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: Colors.black,
                      fontWeight: FontWeight.bold,
                      fontSize: 13.0),
                ),
                SizedBox(height: 5),
                InteractiveViewer(
                  boundaryMargin: EdgeInsets.all(20.0),
                  minScale: 0.1,
                  maxScale: 2.0,
                  transformationController: _transformationController,
                  onInteractionEnd: (value) {
                    _transformationController.value = Matrix4.identity();
                  },
                  child: Image.network(
                    'https://picsum.photos/250?image=9',
                    fit: BoxFit.cover,
                  ),
                ),
                SizedBox(height: 20),
                Padding(
                    padding: const EdgeInsets.only(
                        left: 20.0, right: 10.0, top: 10.0, bottom: 10.0),
                    child: ButtonTheme(
                        height: 35.0,
                        minWidth: 110.0,
                        child: RaisedButton(
                          color: Colors.white,
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5.0)),
                          child: Text(
                            'Cancel',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                                color: Colors.black,
                                fontWeight: FontWeight.bold,
                                fontSize: 13.0),
                          ),
                          onPressed: () {
                            setState(() {
                              Navigator.pop(context);
                            });
                          },
                        ))),
              ],
            )
          ),
          actions: <Widget>[
            TextButton(
              child: Text('Approve'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }
}
```

</details>

**Comment by jerryhamby** [comment]
Yes, in my app the “pinch to zoom” also disappears because they are in a column and it sets behind the interactiveViewer.
(maybe I will rearrange later)

But #67658 is about both instances of text disappearing when the alert is opened. 
As I said before, I don’t have any problems with text anywhere else within my app.

As you can see from my video, the Alert box (containing the interactiveViewer) was opened from another Alert box, 
but I did call Navigator.pop before opening the final Alert box with interactiveViewer.

This has to be within Flutter, because of my success elsewhere in the app.
What more can I do to help?

**Comment by darshankawar** [comment]
If I understand the issue properly, the `InteractiveViewer` in an alert dialog while zooming doesn't show the text above the image as it would do it [here](https://github.com/flutter/flutter/issues/67658#issuecomment-706898602).
Keeping this issue open for further analysis.

**Comment by jerryhamby** [comment]
Sorry, but I want to be super clear. The missing text is not caused by the zooming effect, if I just open the alert box the text is missing. This problem in an alert box, which contains an interactiveViewer, but you don't need to zoom to see the issue.

**Comment by jerryhamby** [comment]
Any progress on this issue?

**Comment by jerryhamby** [comment]
I haven’t heard anything lately about this issue. Can you update me. I’m very close to going to a release version, but this needs to work.
Jerry

**Comment by jerryhamby** [comment]
This problem still exists in the latest version.
Flutter: 1.22.6
VSC:  1.53.2
Woks on my IOS simulator
Does not work on my iPhone 11

**Comment by jerryhamby** [comment]
Just created a stateful IOS InteractiveViewer demo and this seems to work perfectly in both simulator and on my iPhone 11 (14.4).
Both my text item and button finally show the text I provided.
There must be something happening in my real app that uses 24 different packages. The text just doesn't appear.

**Comment by jerryhamby** [comment]
I fixed this issue but I had to do a lot of rethinking and online searching.

First I tried to use a page/class:
class ExpandImageState extends State<ExpandImage>
    with TickerProviderStateMixin {
  ……..

I finally settled on the following:
Future<void> _showMyDialog(context) async {
  TransformationController _controller = TransformationController();
  return showDialog<void>(
  ……..

There is an issue using the first method, but I couldn't figure it out,
maybe the Flutter team can look into this.
