### ISSUE TITLE
args 0.13.6+1 breaks flutter tools

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#6766]
As described in https://github.com/dart-lang/args/issues/58, `CommandRunner.run` no longer returns the results of `Command.run`, which causes flutter tools to always have an exit code of `0`.

**Comment by danrubel** [comment]
https://github.com/flutter/flutter/pull/6765 works around this problem by pinning flutter tools (and many other parts of flutter) to args package v0.13.6.

**Comment by chinmaygarde** [comment]
This has been fixed upstream https://github.com/dart-lang/args/commit/72a6cff9fc349a2835e627ae0f05525e7af49ff2

**Comment by danrubel** [comment]
Yes. I was already 1/2 way through the flutter tools change at that point. The change makes the flutter code more clear and concise, so I'm finishing what I started.

**Comment by danrubel** [comment]
These three PRs combined allowed me to reduce the code base by ~140 lines of code.
