### ISSUE TITLE
Inkwell Ripple effect doesn't work on stack 

### ISSUE THREAD

**Issue by Baluds** [flutter/flutter#67660]
Inkwell ripple effect is not visible on stack items.
Add icon on red container doesn't show ripple effect but the Add icon which is outside of stack seems to show ripple effect
Steps to reproduce:
``` import 'package:flutter/material.dart';

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Stack(
              alignment: AlignmentDirectional.center,
              children: [
                Container(
                  height: 300,
                  width: 300,
                  color: Colors.red,
                ),
                Center(
                  child: InkWell(
                    hoverColor: Colors.grey[400],
                    borderRadius: BorderRadius.circular(50),
                    child: Container(
                      height: 45,
                      width: 45,
                      decoration: BoxDecoration(shape: BoxShape.circle),
                      child: Icon(
                        Icons.add,
                        size: 30,
                      ),
                    ),
                    onTap: () {},
                  ),
                ),
              ],
            ),
            InkWell(
              hoverColor: Colors.grey[400],
              borderRadius: BorderRadius.circular(50),
              child: Container(
                height: 45,
                width: 45,
                decoration: BoxDecoration(shape: BoxShape.circle),
                child: Icon(
                  Icons.add,
                  size: 30,
                ),
              ),
              onTap: () {},
            ),
          ],
        ),
      ),
    );
  }
}
 ```

flutter doctor log
```Doctor summary (to see all details, run flutter doctor -v): 
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[√] Connected device (4 available)

• No issues found!

**Comment by iapicca** [comment]
@Baluds 
just wrap the inkwell in a widget with fixed size

<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';
​
void main() => runApp(MyApp());
​
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}
​
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Material(
        child: Stack(
          alignment: AlignmentDirectional.center,
          children: [
            Center(
              child: SizedBox(
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
                child: InkWell(
                  hoverColor: Colors.grey[400],
                  borderRadius: BorderRadius.circular(50),
                  child: Container(
                    height: 45,
                    width: 45,
                    decoration: BoxDecoration(shape: BoxShape.circle),
                    child: Icon(
                      Icons.add,
                      size: 30,
                    ),
                  ),
                  onTap: () {},
                ),
              ),
            ),
          ],
        ),
      );
}
```
</details>

​

**Comment by lordvins226** [comment]
Wrap your inkwell with material

**Comment by Baluds** [comment]
> Wrap your inkwell with material

worked wrapped with material and assigned color property of material to transparent. Thank you

**Comment by Baluds** [comment]
> @Baluds
> just wrap the inkwell in a widget with fixed size
> 
> sample
> ```dart
> import 'package:flutter/material.dart';
> ​
> void main() => runApp(MyApp());
> ​
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => MaterialApp(
>         home: MyHomePage(),
>       );
> }
> ​
> class MyHomePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Material(
>         child: Stack(
>           alignment: AlignmentDirectional.center,
>           children: [
>             Center(
>               child: SizedBox(
>                 height: MediaQuery.of(context).size.height,
>                 width: MediaQuery.of(context).size.width,
>                 child: InkWell(
>                   hoverColor: Colors.grey[400],
>                   borderRadius: BorderRadius.circular(50),
>                   child: Container(
>                     height: 45,
>                     width: 45,
>                     decoration: BoxDecoration(shape: BoxShape.circle),
>                     child: Icon(
>                       Icons.add,
>                       size: 30,
>                     ),
>                   ),
>                   onTap: () {},
>                 ),
>               ),
>             ),
>           ],
>         ),
>       );
> }
> ```
> 
> ​

Tried it still if the fixed size is smaller than the stack element it doesnt show

**Comment by Baluds** [comment]
> Wrap your inkwell with material

But i still didn't understand, why was their need to use material . Normally ripple should be present right?

**Comment by lordvins226** [comment]
> > Wrap your inkwell with material
> 
> But i still didn't understand, why was their need to use material . Normally ripple should be present right?

Check this https://stackoverflow.com/questions/45424621/inkwell-not-showing-ripple-effect

**Comment by Baluds** [comment]
> > > Wrap your inkwell with material
> > 
> > 
> > But i still didn't understand, why was their need to use material . Normally ripple should be present right?
> 
> Check this https://stackoverflow.com/questions/45424621/inkwell-not-showing-ripple-effect

Thank you 👍
