### ISSUE TITLE
[web]: get a final working build offline

### ISSUE THREAD

**Issue by anoureddini** [flutter/flutter#67663]
We build for mobile and standalone apk or iOS app setup file is generated. Why doesn't `flutter build web` give us a standalone working offline version of the website? Why do we need to have a running server to be able to run the web version of our app?

**Comment by iapicca** [comment]
@anoureddini 
in theory the could just run `flutter run -d chrome --release`
but if you want the "full deployment" experience 
I recommend [dhttpd](https://pub.dev/packages/dhttpd), you can follow these 

<details>
<summary>6 simple steps</summary>
##
1. [install Dart SDK](https://dart.dev/get-dart#install)
2. [update your path](https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path)
3. run `pub global activate dhttpd`
4. `cd <app directory>`
5. run
```console
flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release
cd build/web
dhttpd --port <your port>
```
6. paste in your browser `http://localhost:<your port>/`

</details>

**Comment by jonahwilliams** [comment]
Thanks @iapicca 

Also answered in https://github.com/flutter/flutter/issues/67664

**Comment by anoureddini** [comment]
> @anoureddini
> in theory the could just run `flutter run -d chrome --release`
> but if you want the "full deployment" experience
> I recommend [dhttpd](https://pub.dev/packages/dhttpd), you can follow these
> 
> 5 simple steps

Thank you @jonahwilliams and @iapicca  for your quick answers.
I think I wrote my question poorly. Let me put it this way:
This is my expectation:
After I run `flutter build web` I expect to be able to go to `build/web` and run `index.html` without having any server running. Since the files are static data (html & js) having a server running doesn't seem necessary.

Another version of my problem: After I build the web version, I want to zip the `[project]/build/web/` folder and send it to some random non-technical guy. He must be able to run `index.html` and see what I have created. How is this possible?

Thanks again, in advance.

**Comment by iapicca** [comment]
> [..] After I build the web version, I want to zip the `[project]/build/web/` folder and send it to some random non-technical guy. He must be able to run `index.html` and see what I have created. How is this possible?

@anoureddini 
I'm don't think that such a feature exist for flutter or for most other frameworks for the matter,
at least I never encountered it in my very short .net career.

to show the web app externally just deploy to some service like [netlify](https://www.netlify.com/) ad nuke it after a few days
