### ISSUE TITLE
LUCI failure fetching from googlesource.com: "The requested URL returned error: 429"

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#67661]
https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20AOT%20Engine/9575?

**Comment by christopherfujino** [comment]
Release build is facing infra failure:

https://ci.chromium.org/p/flutter/builders/prod/Mac%20beta%20build_tests/5

```
fatal: unable to access 'https://chromium.googlesource.com/a/external/github.com/flutter/flutter/': The requested URL returned error: 429
[W git.go:289] Transient error string identified in STDERR: "fatal: unable to access 'https://chromium.googlesource.com/a/external/github.com/flutter/flutter/': The requested URL returned error: 429\n"
[W git.go:300] Retrying after 3s (rc=128): transient error string encountered
```

Looks like a quota issue?

**Comment by christopherfujino** [comment]
possibly related https://github.com/flutter/flutter/issues/66133

**Comment by godofredoc** [comment]
From quota dashboard doesn't seem like a quota problem. I opened a bug to the git team to check:

b/170410985

**Comment by keyonghan** [comment]
We are gonna to keep monitoring after https://flutter-review.googlesource.com/c/recipes/+/7620.

**Comment by keyonghan** [comment]
Not reproducible. Please reopen if hitting the issue again.
