### ISSUE TITLE
Pin our external dependencies to specific versions

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6767]
This will ensure that the stability of our codebase is hermetic.

@chinmaygarde @danrubel

**Comment by tvolkert** [comment]
We should also check in a script that updates all our dependencies to the latest version.  We can use that script to update our project and vet it before checking in the updated deps.

**Comment by matanlurey** [comment]
Similar to https://github.com/flutter/flutter/issues/4696, we need this for Angular Dart as well, as we are splitting into several sub-packages. Potential collaboration here too.

**Comment by eseidelGoogle** [comment]
FYI @kevmoo for tracking potential pub user needs.
