### ISSUE TITLE
print statement in onPressed prints twice in debug

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#6768]
```
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 04e7446b2b (22 hours ago) • 2016-11-07 15:48:50
Engine • revision 16077d474b
Tools • Dart 1.21.0-dev.3.0
```

**I've only tested on the iOS simulator currently.**

I have an empty app with a `Scaffold` with the following `body`:

```
body: new Center(
    child:
        new FlatButton(
            child: new Text('New'),
            onPressed: () {
                counter++;
                print("tapped $counter");
            },
        ),
    )
```

If running the app in debug mode print will be displayed twice, if running in release, print will be displayed once. It doesn't seem to execute twice because if i attach a `counter` variable, the counter will only increment once.

Example:

```
Running lib/main.dart on iPhone 7...
tapped 1
tapped 1
tapped 2
tapped 2
```

**Comment by devoncarew** [comment]
Is this from the command-line or IntelliJ?

**Comment by lukef** [comment]
IntelliJ, sorry

**Comment by devoncarew** [comment]
I think you're hitting this guy: https://github.com/flutter/flutter-intellij/issues/406. It's fixed in master, and will be available in the next release of the plugin (likely next Monday). Thanks for the report!
