### ISSUE TITLE
App partially hangs when running in VSCode debugger (iOS), but not using `flutter run`

### ISSUE THREAD

**Issue by jrmiddle** [flutter/flutter#67698]
## Description

Since yesterday, running Flutter apps in the VSCode debugger comes with what seems like a ~1m hang, during which time no logs flow in the VSCode debugger panel, and bundled assets don't render (even though UI layout has already happened). During this period, however, I *am* able to interact with the UI and  use the app (which makes numerous network calls) as expected.

After the "hang", assets render and logs resume. This correlates with a couple of other observations:

1. A pause in messaging in `vmServiceLog` of about 41s (see below).
2. Despite logs not flowing in the VSCode debug panel, they DO flow for the device Console.app.
3. The `Code Helper (Renderer)` process used 99% cpu on my lowly MBP for the duration of the hang. Immediately after the hang ended, this notched down to about 53%, and after a few seconds fell out of the top 20.
4. The hang and associated shenanigans do not occur when running via the command line, using `flutter run`.

This seems perhaps related in spirit to what was being reported in #67524, which was closed due to lack of info earlier.

### 1. Clean and update libs

```
flutter clean && flutter pub upgrade
```

### 2. Run in VSCode

1. Ensure all breakpoints are disabled.
2. Configure the VSCode dart plugin to log vm interaction (in `settings.json`):

```json
{
    ...,
    "dart.vmServiceLogFile": "/path/to/flutterVmServiceLog.log",
    ...
}
```

3. `tail` the log

```sh
tail -f /path/to/flutterVmServiceLog.log
```

4. Run the app.

## Expected results

Assets are rendered exactly at or very shortly after the time the UI appears.

## Observed Results

1. The app hangs about 10 seconds after build/install completion, with an
   activity indicator showing.

2. App logging ceases in the VSCode debug panel during this time. However, logs continue to flow
   for the device/process in Console.app.

3. Looking at the `vmServiceLog`, the following stands out:
   
   * At `1:40:59 (T  =  0s)`, message `1794/setExceptionPauseMode` is sent.
   * At `1:40:59 (T +=  0s)`, message `1795/getIsolate(isolates/2505264372133715)` is sent.
   * At `1:41:40 (T += 41s)`, message `streamNotify` is called, again referencing `isolates/2505264372133715`.   **This corresponds exactly with the time the app seemed "hung".**
   * At `1:41:40 (T +=  0s)`, a response to message `1794/setExceptionPauseMode` is received.
   * At `1:41:40 (T +=  0s)`, another message referencing `isolates/2505264372133715`, with a large JSON payload (truncated in log) was received.

     Here's the critical section of the log in question; it's also attached in full:
     
     ```
     1:40:59 PM]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/3683636927764127","name":"main","number":"3683636927764127"},"timestamp":1602189634869,"extensionData":{"number":173,"startTime":27564138803,"elapsed":5145,"build":3468,"raster":1414}}}}
     [1:40:59 PM]: ==> {"id":"1794","jsonrpc":"2.0","method":"setExceptionPauseMode","params":{"isolateId":"isolates/2505264372133715","mode":"None"}}
     [1:40:59 PM]: ==> {"id":"1795","jsonrpc":"2.0","method":"getIsolate","params":{"isolateId":"isolates/2505264372133715"}}
     [1:41:40 PM]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","id":"isolates\/2505264372133715","name":"_spawn","number":"2505264372133715"},"timestamp":1602189659089,"_debuggerSettings":{"_exceptions":"none"}}}}
     [1:41:40 PM]: <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"1794"}
     [1:41:40 PM]: <== {"jsonrpc":"2.0", "result":{"type":"Isolate","id":"isolates\/2505264372133715","name":"_spawn","number":"2505264372133715","_originNumber":"3683636927764127","startTime":1602189633486,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":1,"avgCollectionPeriodMillis":25603.206,"used":525536,"capacity":2097152,"external":0,"time":0.00044},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":3,"used":43811040,"capacity":46120960,"external":0,"time":0.002913,"avgCollectionPeriodMillis":8534.411666666667}},"runnable":true,"livePorts":0,"pauseOnExit":false,"_isReloading":false,"pauseEvent":{"type":"Event","kind":"PauseStart","isolate":{"type":"@Isolate","id":"isolates\/2505264372133715","name":"_spawn","number":"2505264372133715"},"timestamp":1602189633823},"rootLib":{"type":"@Library","fixedId":true,"id":"libraries\/@1195189369","name":"","uri":"package:hubspace\/main_debug.dart"},"_numZoneHandles":10,"_numScopedHandles":43,"_tagCounters":{"names":["Idle","LoadWait","VM","LoadBytecode","CompileOptimized","CompileUnoptimized","ClassLoading","CompileParseRegExp","DartCompiled","DartInterpreted","GCNewSpace","GCOldSpace","GCIdle","Embedder","Runtime","Native"],"counters":[0,0,220,0,0,2,0,0,0,0,0,0,0,0,0,0]},"libraries":[{"type":"@Library","fixedId":true,"id":"libraries\/@0150898","name":"dart.core","uri":"dart:core"},{"type":"@Library","fixedId":true,"id":"libraries\/@1026248","name":"dart.isolate","uri":"dart:isolate"},{"type":"@Library","fixedId":true,"id":"libraries\/@2408521","name":"dart.mirrors","uri":"dart:mirrors"},{"type":"@Library","fixedId":true,"id":"libraries\/@3220832","name":"dart.collection","uri":"dart:collection"},{"type":"@Library","fixedId":true,"id":"libraries\/@4048458","name":"dart.async","uri":"dart:async"},{"type":"@Library","fixedId":true,"id":"libraries\/@5383715","name":"dart.developer","uri":"dart:developer"},{"type":"@Library","fixedId":true,"id":"libraries\/@6320332","name":"nativewrappers","uri":"dart:nativewrappers"},{"type":"@Library","fixedId":true,"id":"libraries\/@7027147","name":"dart.typed_data","uri":"dart:typed_data"},{"type":"@Library","fixedId":true,"id":"libraries\/@8050071","name":"dart.ffi","uri":"dart:ffi"},{"type":"@Library","fixedId":true,"id":"libraries\/@9179448","name":"dart.wasm","uri":"dart:wasm"},{"type":"@Library","fixedId":true,"id":"libraries\/@10003594","name":"dart.convert","uri":"dart:convert"},{"type":"@Library","fixedId":true,"id":"libraries\/@11040228","name":"dart._internal","uri":"dart:_internal"},{"type":"@Library","fixedId":true,"id":"libraries\/@12383281","name":"dart.math","uri":"dart:math"},{"type":"@Library","fixedId":true,"id":"libraries\/@13168694","name":"dart._vmservice","uri":"dart:_vmservice"},{"type":"@Library","fixedId":true,"id":"libraries\/@14069316","name":"dart.io","uri":"dart:io"},{"type":"@Library","fixedId":true,"id":"libraries\/@15463476","name":"dart._http","uri":"dart:_http"},{"type":"@Library","fixedId":true,"id":"libraries\/@16065589","name":"dart.ui","uri":"dart:ui"},{"type":"@Library","fixedId":true,"id":"libraries\/@17205832","name":"vmservice_io","uri":"dart:vmservice_io"},{"type":"@Library","fixedId":true,"id":"libraries\/@18094069","name":"activity","uri":"package:afero_activity\/activity.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@19519856","name":"","uri":"package:afero_activity\/src\/models\/activity_view_model.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@20059937","name":"","uri":"package:afero_activity\/src\/redux\/activity_actions.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@21506628","name":"","uri":"package:afero_activity\/src\/redux\/activity_middleware.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@22194880","name":"","uri":"package:afero_activity\/src\/redux\/activity_reducer.dart"},{"type":"@Library","fixedId":true,"id":"libraries\/@23331152","name":"","uri":"package:afero_activity\/src\/redux\/activity_state.dart"},{…
     [1:41:40 PM]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/3683636927764127","name":"main","number":"3683636927764127"},"timestamp":1602189681565,"extensionData":{"number":174,"startTime":27610826101,"elapsed":52595,"build":46176,"raster":6078}}}}
     [1:41:40 PM]: ==> {"id":"1796","jsonrpc":"2.0","method":"setLibraryDebuggable","params":{"isolateId":"isolates/2505264372133715","libraryId":"libraries/@0150898","isDebuggable":true}}
     [1:41:40 PM]: <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"1796"}
     [1:41:40 PM]: ==> {"id":"1797","jsonrpc":"2.0","method":"setLibraryDebuggable","params":{"isolateId":"isolates/2505264372133715","libraryId":"libraries/@0150898","isDebuggable":true}}
     ```

One thing to note: while one of my colleagues was experiencing the issue, I had local branch of the code that hadn't been changed in a while. I was able to run that in VSCode **without** experiencing the hang. I then switched to latest `master`, cleaned and did a `flutter pub upgrade`, and was able to reproduce the problem. I then switched back to my old branch, did a `flutter clean && flutter pub upgrade`, and the problem persisted where it previously had not reproduced. 

Next, I restored a week-old version of the tree from a Time Machine backup. As it was already configured in its current state, I did not clean it or upgrade packages. Upon running in VSCode, I reproduce the issue, even though this tree did NOT exhibit the described behavior when I last touched it.

## Environment Info

All of the following environments reproduce this issue:

### VSCode

```
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z (1 day ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Dart/Flutter Extension 3.15.0
```

```
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
Dart/Flutter Extension 3.15.0
```

```
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
Dart/Flutter Extension 2.8.4
```

## Macos XCode/iOS

```
Macos 10.15.6 (19G2021)
Xcode 11.7 (11E801a)
iPhone SE (Model A1662, A1723, A1724)
iOS 13.6.1 (17G80)
```

## Flutter

* Flutter 1.17.5: 
  ```
  [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale en-US)
   
  [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
  [✓] Xcode - develop for iOS and macOS (Xcode 11.7)
  [✓] Android Studio (version 3.6)
  [!] IntelliJ IDEA Community Edition (version 2020.2.1)
      ✗ Flutter plugin not installed; this adds Flutter specific functionality.
      ✗ Dart plugin not installed; this adds Dart specific functionality.
  [✓] VS Code (version 1.50.0)
  [✓] Connected device (1 available)
  ```
* Flutter 1.22.x (sorry, don't have the specific patch here)

## Full vmServiceLog

[flutterVmServiceLog.log](https://github.com/flutter/flutter/files/5351868/flutterVmServiceLog.log)

**Comment by jonahwilliams** [comment]
@DanTup

**Comment by TahaTesser** [comment]
HI @jrmiddle 
Tried to reproduce on the latest stable in a new project, 

1. Are you experiencing this issue on the latest stable? 
2. Does this reproduce in a new project? 
3. Can you please provide  a complete reproducible minimal code sample

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ListView.builder(
          itemCount: 12,
          itemBuilder: (BuildContext context, int index) {
            return Image.asset('assets/dash.png');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

[flutterVmServiceLog.log.zip](https://github.com/flutter/flutter/files/5354442/flutterVmServiceLog.log.zip)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f30b7f4db9 (15 hours ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

**Comment by jrmiddle** [comment]
Thanks @TahaTesser . It may take me a bit to get a code example. Nevertheless, here's my `flutter doctor -v`: 

```
(base)  ✘  ~  flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.17.5 at /Users/corafera/flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/corafera/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/corafera/Library/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[!] Connected device
    • Error: Missy deserved better. is not connected. Xcode will continue when Missy deserved better. is connected. (code -13)
    • Error: Jenkins iPhone SE is not connected. Xcode will continue when Jenkins iPhone SE is connected. (code -13)
    • Error: Donna is not connected. Xcode will continue when Donna is connected. (code -13)
```

**Comment by DanTup** [comment]
The logs make it seem like the delay is on the VM-side of the VM Service, though it coinciding with a Code Helper process maxing out makes me suspicious that the logging has just been delayed because the debug adapter process is busy (it runs in a NodeJS process which is single threaded). If you're able to interact with the app, that checks out too - as the app would normally be paused during that part, so I wouldn't expect you to be able to interact with it at all.

Can you reproduce this using a project you can share? If not, if I made a build of the Dart extension with more logging in the debug adapter, would you be able to install it and reproduce using that?

**Comment by DanTup** [comment]
I'd be interested to see more of the log too. I just noticed the first line is a `Flutter.Frame` event, but I wouldn't expect to see them during startup as the app should be paused. I'm curious what happened in the lines just before this occurred.

Also - if you capture the logs by using the **Dart: capture Logs** command (untick **Analysis Server** but leave everything else ticked), you'll get some additional logging that may or may not help (it'll also force Flutter into verbose mode).

**Comment by jrmiddle** [comment]
@DanTup I can't say I _can't_ reproduce in a project I can share, but I don't think I can in a reasonable timeframe given other priorities I and my team are juggling. A debug build of the Dart extension would be most welcome, and I think the team would be happy to try that. Thanks for offering!

Thanks for the tips in your second comment as well. As far as the log I posted is concerned, TMK what's there begins at app launch; I cleared it immediately prior to launching the app in the debugger. I will try **Dart: capture logs** in my runs today.

Thanks!

**Comment by DanTup** [comment]
Great - I'll make a build with more logging for tomorrow that might help understand what's happening. Thanks!

**Comment by DanTup** [comment]
@jrmiddle there's a build of the extension here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.16.0-dev.dap-logging.1

It logs the Debug-Adapter-Protocol requests in addition to the VM Service traffic which might help understand what code is running in the debug adapter at the time this happens. To use it:

- Download the vsix file from that release
- Run the **Extensions: Install from VSIX** command in VS Code and select that file
- Click the **Reload** button to reload the extension
- Run the **Dart: Capture Logs** command in VS Code, unticking **Analysis Server** but leaving everything else ticked and click OK
- Reproduce the issue
- While the CPU is high, run `code --status` in a terminal window and grab that output too
- Click **Cancel** on the logging notification to stop logging and open the log

The log will be pretty big. Mostly I'm interested in the stuff around the delay (and a little while before). If you're unsure what's relevant, you can also zip and send me the whole log by email (logs@dartcode.org).

There may be a little performance overhead using this build, so you may wish to uninstall it and re-install from the marketplace once you're done.

Thanks!

**Comment by jrmiddle** [comment]
Awesome, thanks @DanTup ! I'll check this out this morning.

**Comment by DanTup** [comment]
I've tracked down a performance issue in the latest extension when printing large messages. Based on the symptoms and log above, it seems like this could be the same. Do you know if you were printing anything large (probably a few thousand characters or above)?

I've got an issue open at https://github.com/Dart-Code/Dart-Code/issues/2877 about this and hope to release a patch today or tomorrow with a fix.

**Comment by jrmiddle** [comment]
Hey @DanTup first off, sorry I wasn't able to get back to you yesterday. Meeting day etc.

Regarding what you found, it is absolutely possible and quite likely that we're logging some things that are super huge. It should be relatively easy to see if omitting those has an effect since they're generally logged at `Level.FINEST`.

I should be able to verify that very soon, and will update you with results shortly.

Thanks!

**Comment by DanTup** [comment]
No worries! If there's a chance you're logging a lot, I'm confident it's the same issue so if it's not easy to test removing the logging, you should be able to just test with the fix soon (it'll be tomorrow now, I won't have time to fix/ship it today).

**Comment by jrmiddle** [comment]
Thanks @DanTup, that's stellar turnaround! In the meantime, I've emailed you the requested logging output from the debug VSIX you sent. Let me know if I can provide more info.

**Comment by DanTup** [comment]
@jrmiddle While fixing the issue I found, I discovered that it mostly only occurred when running on Chrome, since the output is generally truncated from Flutter (it still occurred, it was just less severe). In the logs you sent me, the longest hangs do all appear to occur after largish output events, so I'm hopeful the fix I've made will resolve it.

There's a test build here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.15.1-beta.1

Instructions to install are in the notes on that page. Be sure to reload after installing it to make sure you get the new version. It definitely resolves my contrived case, but it'd be good to know if it solves yours before I release it.

Thanks!

**Comment by DanTup** [comment]
v3.15.1 has been published to the marketplace now (a few other people that reported issues confirmed it resolve theirs), so you don't need to use the beta above, you can just run **Extensions: Check for Updates** from the VS Code command palette.

Please me know if it also resolves your issue or not. Thanks!

**Comment by jrmiddle** [comment]
Hey @DanTup, apologies for the delay in responding, but I can confirm that recent changes were effective for us. Thanks so much for the quick turnaround on this!

**Comment by DanTup** [comment]
Great, glad to hear!
