### ISSUE TITLE
in_app_purchase  doesn't work correctly in some ios phones

### ISSUE THREAD

**Issue by ShamsFaraj** [flutter/flutter#67710]
I added in_app_purchase plugin for payment in my flutter app. It works perfectly in android and sandbox, but after publishing the app, it didn't work correctly with real card for all iphones. It worked in ios 12, 13, and some of 14 (iphone 11 pro), but didn't work in the other iphones I tried with the version of ios 14.  Payment is completed successfully, coins should have been added, but didn't.

in_app_purchase: ^0.3.4+12
(I checked older version of plug in, result is the same)

Here's my code:

 _initialize() async {
    _available = await _iap.isAvailable();
    if (_available) {
      await _getProducts();
      _subscription =
          _iap.purchaseUpdatedStream.listen((purchases) => setState(() {
                print('New purchase');
                _purchases.addAll(purchases);
                Platform.isIOS ? _getPastPurchases() : _verifyPurchase();
              }));
    }
  }

  Future<void> _getPastPurchases() async {
    QueryPurchaseDetailsResponse response = await _iap.queryPastPurchases();
    print(response.pastPurchases);
    for (PurchaseDetails purchaseDetails in response.pastPurchases) {
      print('Purchase status: ${purchaseDetails.status}');
      _iap.completePurchase(purchaseDetails);

      if (purchaseDetails.status == PurchaseStatus.purchased) {
        _verifyPurchase();
      }
    }
    if(mounted) {
      setState(() => _purchases = response.pastPurchases);
    }
  } 

    _verifyPurchase() {
    PurchaseDetails purchaseDetails = _hasPurchased(widget.productID);
    if(purchaseDetails != null && purchaseDetails.status == PurchaseStatus.purchased) {
         // my logic to add purchased coins
     }
  }

**Comment by darshankawar** [comment]
@ShamsFaraj 
Didn't you open a [same](https://github.com/flutter/flutter/issues/67630) issue yesterday ? I see same code sample and description in this issue. Please don't open duplicate issues for same reason.
Closing this as duplicate.
thanks.
