### ISSUE TITLE
Extract "_dropAreaMargin" and "elevation" from ReorderableListView

### ISSUE THREAD

**Issue by Paolo9711** [flutter/flutter#67716]
## Use case

When you use a **`ReorderableListView`** whenever you make a longPress on a cell it is elevated by a certain value `elevation` and a bottom padding of a certain value `_dropAreaMargin` is added.

## Proposal
It would be useful to be able to extract these parameters to make them customizable by the user by adding them to the **`ReorderableListView`** class constructor.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
With the recent refactoring of the `ReorderableListView` (PRs: #74299 and #74697), we have added the ability to override the the default decoration for the item being dragged with a `proxyDecorator` property. It can be used to add your own custom look to the dragged item:

```dart
  Widget proxyDecorator(Widget child, int index, Animation<double> animation) {
    return AnimatedBuilder(
      animation: animation,
      builder: (BuildContext context, Widget? child) {
        final double animValue = Curves.easeInOut.transform(animation.value);
        final double elevation = lerpDouble(0, 6, animValue)!;
        return Material(
          child: child,
          elevation: elevation,
        );
      },
      child: child,
    );
  }

...

  ReorderableListView(
     ...
     proxyDecorator: proxyDecorator,
     ...
  )
```

Which mimics the default look from the `ReorderableListView`. You can wrap the item in whatever look you desire.
