### ISSUE TITLE
EXCEPTION CAUGHT BY RENDERING LIBRARY

### ISSUE THREAD

**Issue by amitgujral** [flutter/flutter#67726]
The following assertion was thrown during performLayout():
Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is
undefined.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 444 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  Row file:///C:/Android/WorkFolder/AndroidStudioProjects/flutter_helloworld_app/lib/main.dart:34:12

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:444:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:657:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderView.performLayout (package:flutter/src/rendering/view.dart:170:13)
#6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#8      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderFlex#373dc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: Row ← HelloWorldApp ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=392.7, h=759.3)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderConstrainedBox#27afb NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderDecoratedBox#7a594 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPadding#bbdb3 NEEDS-LAYOUT NEEDS-PAINT
    child 2: RenderConstrainedBox#1b0e3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderDecoratedBox#e3e97 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPadding#7da59 NEEDS-LAYOUT NEEDS-PAINT
    child 3: RenderConstrainedBox#c5b8e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderDecoratedBox#4120e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPadding#1bebd NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is undefined.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 444 pos 18: 'textDirection != null'
The relevant error-causing widget was: 
  Row file:///C:/Android/WorkFolder/AndroidStudioProjects/flutter_helloworld_app/lib/main.dart:34:12
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method '>' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The method '>' was called on null.
Receiver: null
Tried calling: >(1e-10)
The relevant error-causing widget was: 
  Row file:///C:/Android/WorkFolder/AndroidStudioProjects/flutter_helloworld_app/lib/main.dart:34:12
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Calamity210** [comment]
I'm going to jump to the assumption that you are not using a [WidgetsApp](https://api.flutter.dev/flutter/widgets/WidgetsApp-class.html) or widgets that build upon `WidgetsApp` such as [MaterialApp](https://api.flutter.dev/flutter/material/MaterialApp-class.html) or [CupertinoApp](https://api.flutter.dev/flutter/cupertino/CupertinoApp-class.html) above your Row. Those widgets provide a configuration that the `Row` could use to determine the textDirection. In your case the Row isn't given anything so its got no idea whether its LTR or RTL. You could either:
- Pass `textDirection` to your Row.
- Wrap your in a `Directionality` Widget
- Use `WidgetsApp` or similar widgets that build upon it.

**Comment by PixelToast** [comment]
@gujralam
Thanks for taking the time to file an issue

If the explanation above was not sufficient please provide a minimal working example, the output of `flutter doctor`, and describe the expected behavior

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
