### ISSUE TITLE
ExpansionTile class, add a controller option to pass to its constructor or expose the controller property.

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#67724]
It's doing what it was designed for. I am merely suggesting another property that I find valuable. To allow for expanding and collapsing the widget programmatically. From the source code, this action of expanding and collapsing is being handled by an AnimationController widget. By simply calling reverse or the forward method of the controller, we are able to control the expansion etc. Could we expose the controller property to the widget's API so that we can have access it to.

Consider this scenario:

I want to programmatically collapse ExpansionTile after 10 seconds. Right now this is quite impossible, given the current strucutre of the ExpansionTile code snippet. But it would be possible if we had acccess to the controller as so

`ExpansionTile(controller: controller)`

We will have to create and dispose the AnimationController ourselves.

or You could also expose the controller. Right now it is a private property

**Comment by darshankawar** [comment]
@therenca 
Check [this](https://github.com/flutter/flutter/issues/22351#issuecomment-578122412) solution and see if it works for you.
Thanks.

**Comment by therenca** [comment]
[Here](https://github.com/flutter/flutter/issues/22351#issuecomment-578122412), we still have to interact with the widget to update state. Besides, [this](https://github.com/flutter/flutter/issues/22351#issuecomment-578122412) solution could have been done with an ExpansionPanel widget. Is there a solution where the expansion tile can expand and collapse by using a timer and a callback without user interacting with the widget?

**Comment by david072** [comment]
I recently had the same issue. If the goal is just to expand / collapse the ˋExpansionTileˋ programmatically, wouldn't it be easier to make `_ExpansionTileState` public and add a `setExpanded(bool)` method? This could then easily be accessed using a key (see ˋFormState.validate()ˋ).

Any opinions on this? If this is a good idea, I'd like to look into it.

**Comment by mateusfccp** [comment]
Is this issue still valid? I think `ExpansionTileController` solves this issue.

**Comment by HansMuller** [comment]
This has been fixed, see `ExpansionTileController` (as noted in https://github.com/flutter/flutter/issues/67724#issuecomment-1838994137)
