### ISSUE TITLE
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by JeetBhattachariya** [flutter/flutter#67721]
I am getting this error after adding firebase_admob to my yaml file . I have tried creating a new project but it still gives me this error .
Restarted application in 903ms.
E/flutter (19955): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (19955): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (19955): <asynchronous suspension>
E/flutter (19955): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (19955): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
E/flutter (19955): #4      main (package:rokkhakortafinal/main.dart:23:27)
E/flutter (19955): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (19955): #6      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (19955): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19955): #8      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (19955): #9      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (19955): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (19955): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (19955): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (19955):

Flutter doctor output
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.2)
[√] Connected device (1 available)

```
```

**Comment by Abhishek01039** [comment]
Hi @JeetBhattachariya 
maybe this will help you https://github.com/flutter/flutter/issues/41119#issuecomment-625128400
Thanks.

**Comment by darshankawar** [comment]
@JeetBhattachariya 
After adding `admob`, did you run `flutter pub get` ? Are you trying to hot restart your app after adding or removing that plugin ? If so, you need to first stop the app intance, run `flutter pub get` and then `flutter run` to see if it works.  Also try `flutter clean` before running `flutter run`, as I see you are hot restaring your app:

`Restarted application in 903ms.`

If issue persists, provide a minimal code sample along with `pubspec.yaml`.

**Comment by JeetBhattachariya** [comment]
> Hi @JeetBhattachariya
> maybe this will help you [#41119 (comment)](https://github.com/flutter/flutter/issues/41119#issuecomment-625128400)
> and the duplication of #61226
> Thanks.

I tried this already, but it is not working.

**Comment by JeetBhattachariya** [comment]
> @JeetBhattachariya
> After adding `admob`, did you run `flutter pub get` ? Are you trying to hot restart your app after adding or removing that plugin ? If so, you need to first stop the app intance, run `flutter pub get` and then `flutter run` to see if it works. Also try `flutter clean` before running `flutter run`, as I see you are hot restarting your app:
> 
> `Restarted application in 903ms.`
> 
> If issue persists, provide a minimal code sample along with `pubspec.yaml`.

@darshankawar I created a sample app with minimum code. The error is still with plugin exception:
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  static const MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
    testDevices: null,
    nonPersonalizedAds: true,
    keywords: <String>['books', 'games'],
  );

  BannerAd bannerAd;
  BannerAd createBannerAd() {
    return BannerAd(
        adUnitId: 'ca-app-pub-2911445656330171/9401368832',
        size: AdSize.banner,
        targetingInfo: targetingInfo,
        listener: (MobileAdEvent event) {
          print('bannerAd $event');
        });
  }

  @override
  void initState() {
    FirebaseAdMob.instance
        .initialize(appId: 'ca-app-pub-2911445656330171~6358981528');
    bannerAd = createBannerAd()
      ..load()
      ..show();
    super.initState();
  }

  @override
  void dispose() {
    bannerAd.dispose();
    super.dispose();
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}




Pubspec.yaml


name: adtest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_admob: ^0.10.0+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



Error while running the app:
D/OnePlusJankManager(16266):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.example.adtest/com.example.adtest.MainActivity--- jank level = 3
E/FA      (16266): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/flutter (16266): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel plugins.flutter.io/firebase_admob)
E/flutter (16266): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (16266): <asynchronous suspension>
E/flutter (16266): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (16266): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:612:61)
E/flutter (16266): #3      FirebaseAdMob.initialize (package:firebase_admob/firebase_admob.dart:574:12)
E/flutter (16266): #4      _MyHomePageState.initState (package:adtest/main.dart:75:10)
E/flutter (16266): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (16266): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #44     Element.inflateWidget (package:flutter/src/widgets/framework
E/flutter (16266): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method loadBannerAd on channel plugins.flutter.io/firebase_admob)
E/flutter (16266): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (16266): <asynchronous suspension>
E/flutter (16266): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (16266): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:612:61)
E/flutter (16266): #3      BannerAd.load (package:firebase_admob/firebase_admob.dart:290:12)
E/flutter (16266): #4      _MyHomePageState.initState (package:adtest/main.dart:77:9)
E/flutter (16266): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (16266): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569
E/flutter (16266): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method showAd on channel plugins.flutter.io/firebase_admob)
E/flutter (16266): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (16266): <asynchronous suspension>
E/flutter (16266): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (16266): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:612:61)
E/flutter (16266): #3      MobileAd.show (package:firebase_admob/firebase_admob.dart:236:12)
E/flutter (16266): #4      _MyHomePageState.initState (package:adtest/main.dart:78:9)
E/flutter (16266): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (16266): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (16266): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (16266): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (16266): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (16266): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (16266): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (16266): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (16266): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (16266): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (16266): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)

**Comment by darshankawar** [comment]
@JeetBhattachariya 
This seems to be an issue with Firebase plugin you are using, which has a separate repo for tracking. Please consider opening this issue here : https://github.com/FirebaseExtended/flutterfire/issues
Closing from here, since it. doesn't seem to be related to Flutter.
Thanks.

**Comment by flutterq2** [comment]
All Possible working solution added [[Solved] No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider](https://fluttercorner.com/no-implementation-found-for-method-getapplicationdocumentsdirectory-on-channel-p/)
