### ISSUE TITLE
[web]: Trying to use web support to test application.

### ISSUE THREAD

**Issue by dholiya** [flutter/flutter#67729]
Could not load content for org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_primitives.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

**Comment by Abhishek01039** [comment]
Hi @dholiya 
can you please provide `flutter doctor -v`, `flutter run -v`, and minimal reproduction code?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
