### ISSUE TITLE
[Snackbar] action text dose not have style option 

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#67730]
Hi, in SnackBarAction there is no option to control the test style, pls add new option to control text style for SnackBarAction
```
SnackBarAction(
            label: 'undo',
            textColor: Colors.white,
            onPressed: () { 
            },
          )
```

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/46599
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by kw2019ltd** [comment]
I see that issue is closed.
