### ISSUE TITLE
extend package_info plugin to return installer info

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#67739]
This is a feature request for package_info plugin to return installer info in the PackageInfo structure.

For Android it is returned from `PackageManager.getInstallerPackageName`

```
PackageManager pm = applicationContext.getPackageManager();
String installerPackage = pm.getInstallerPackageName(applicationContext.getPackageName());
map.put("installer", installerPackage);
```

For iOS it is either Apple store or TestFlight

```
NSString *appStoreReceipt = [[[NSBundle mainBundle] appStoreReceiptURL] path];
...
@"installer" : [appStoreReceipt containsString:@"CoreSimulator"] ? @"com.apple.simulator"
    : [appStoreReceipt containsString:@"sandboxReceipt"] ? @"com.apple.testflight" : @"com.apple"
```

**Comment by caiopo** [comment]
Hey, I had a similar requirement recently and couldn't find any package that made this, so I made my own.

Here it is: https://pub.dev/packages/installer_info

If you decide to use it and face any issues, please let me know. Thanks!

**Comment by stuartmorgan** [comment]
Closing as `package_info` is deprecated in favor of [`package_info_plus`](https://pub.dev/packages/package_info_plus).
