### ISSUE TITLE
Flutter Not Work on Linux

### ISSUE THREAD

**Issue by MrR1pp3r** [flutter/flutter#67734]
![4](https://user-images.githubusercontent.com/48425460/95596855-6e047200-0a3d-11eb-979d-302c36771192.png)
![2](https://user-images.githubusercontent.com/48425460/95596250-a9527100-0a3c-11eb-9d5a-f5ba50004b57.png)
![3](https://user-images.githubusercontent.com/48425460/95596260-ae172500-0a3c-11eb-999b-c17b0dca3495.png)

Specs:
Android 10 Device
Android API 30
Android build-tool 30.0.2
Android Platform 30

I use to create flutter app using ... `flutter create app` then cd app && `flutter run`.. nothing else

**Comment by TahaTesser** [comment]
Hi @MrR1pp3r 
Can you download API 28 packages from SDK manager GUI  inside Android Studio and try again? 
Thank you

**Comment by Abhishek01039** [comment]
Hi @MrR1pp3r 
please download build-tools using `sdkmanager.bat “build-tools;28.0.3”`
please follow this https://dev.to/ejgamer21/install-flutter-without-android-studio-58bi or https://medium.com/@quicky316/install-flutter-sdk-on-windows-without-android-studio-102fdf567ce4
Thanks

**Comment by MrR1pp3r** [comment]
Thank You..
I getting problem after install 29v.. & trace back the prob.. 

edit on build.gradle 

SdkVersion 30
BuildVersion 30.0.2

Fixed my problem.. 

I really sorry once again.. nxt time i google it..

**Comment by MrR1pp3r** [comment]
And Linux take only 7 seconds to build my app.. kinda faster than Windows

**Comment by PixelToast** [comment]
Closing as the author seems to have solved the original issue
