### ISSUE TITLE
Flutter run stuck at 'Installing build\app\outputs\flutter-apk\app.apk...' when Debug app uninstalled from device

### ISSUE THREAD

**Issue by sumanth-vs** [flutter/flutter#67742]
(Android)
How to reproduce: 
1. Uninstall the debug application from the app drawer 
2. Run main.dart or flutter run

(*)  Issue seems to be connected with debug app not being completely uninstalled from device (Not uninstalled for all users)
(*) Issue persists when 'Multiple Users' is disabled 

Expected Behaviour:
(*) Flutter run should only install app for current user (?)
(*) Uninstalling the debug app should completely remove it from the device

**Comment by darshankawar** [comment]
@sumanth-vs 
Please provide `flutter doctor -v`. The line where you say the app gets stuck seem to be installing a release build ? but if you run `flutter run`, it will install debug mode app. What does` multiple users` mean ?
Also provide the devices on which you are seeing this behavior.
Thanks.

**Comment by sumanth-vs** [comment]
@darshankawar  I am unable to reproduce this issue currently. I was not installing a release build, debug mode itself (VSCode, just run the main.dart file using the 'Start Debugging' Button).

By multiple users I mean the [User Profiles on Android ](https://www.howtogeek.com/333484/how-to-set-up-multiple-user-profiles-on-android/). 
My Device is a Xiaomi Mi A2.


For reference : [Flutter stuck at Installing build\app\outputs\apk\app.apk](https://stackoverflow.com/questions/53394504/flutter-stuck-at-installing-build-app-outputs-apk-app-apk)

**Comment by darshankawar** [comment]
@sumanth-vs 
I am unable to replicate the issue. I'd suggest you to keep an eye on it if you are able to replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and reopen when you have concrete steps.
Thanks.

**Comment by anticafe** [comment]
https://stackoverflow.com/questions/53394504/flutter-stuck-at-installing-build-app-outputs-apk-app-apk

I got the same issue due to Work Profile. After remove app in Work Profile, then it's ok now.

**Comment by anmolsatija** [comment]
I also got the same problem, I created a new app with the same fields and everything same still it was showing the same error, so I think it may be related to some kind of memory leak or something else.
Solution to this problem is restart your physical device and then re-install the app.
