### ISSUE TITLE
Picture.toImage

### ISSUE THREAD

**Issue by dannyhendrix** [flutter/flutter#6774]
## New Feature request

There should be a way to construct an image from a Picture. This would allow to construct images in memory and manipulate them.

Usecase:
```
Picture p1 = ..;

ui.window.onBeginFrame = (){
	//update p1
	//create canvas c1
	c1.drawPicture(p1);
	c1.DrawRect(..);
	..
        //create Picture from c1
	p1 = PictureRecorder.Build();
	..
	//Create scene with p1 and render scene
	..
	ui.window.render(..);
};
```
This currently results in huge drawing instruction list in p1 because it keeps adding now Pictures. It is not possible to construct an intermediate image from the Picture. Also there is no way to get the pixel data from a Picture.

**Comment by Hixie** [comment]
I totally agree that we should have a `toImage()` method on `Picture`, but I don't really understand how you think it's going to help your case. Why not just move the `p1` declaration into your frame function?

**Comment by dannyhendrix** [comment]
I agree that the example is not very clear. What I am doing in the onBeginFrame-loop is update p1 instead of creating a new Picture. Consider p1 to be an image that contains tiles. In the loop I only want to repaint the tiles that have changed and draw those on p1. Painting one tile can be complex so you want to avoid repainting all tiles. I hope that clears things up a little :).

**Comment by Hixie** [comment]
Why not just record each tile as a separate Picture, and then assemble them as a new picture each frame? That's how we do it in the framework, essentially.

**Comment by dannyhendrix** [comment]
Each tile may contain about 5 images. If there are 30 tiles, the main Picture contains 150 drawing instructions for drawing an image, each frame. It will work but it will hurt performance.

**Comment by Hixie** [comment]
Pictures are automatically rasterized and cached by the engine, so if you reuse a Picture unchanged it shouldn't be expensive.

**Comment by Hixie** [comment]
Sorry, @abarth points out to me that I'm wrong about that. PictureRecord with Canvas.addPicture won't rasterize and cache. SceneBuilder.addPicture will. So you'd create each tile as a separate Picture, then use SceneBuilder to combine them. (That's what the framework does.)

This is not to say that we shouldn't just provide the API you're asking for, we definitely should. I'm just describing what you could do today to get better performance.

**Comment by Hixie** [comment]
Proposal (all in `dart:ui`):
```
  Future<Picture> Scene.toPicture();
  Future<Image> Picture.toImage(int width, int height); // arguments in physical pixels
  Future<Uint8List> Image.toByteData(); // returns raw pixel data in RGBA form, row-primary
```

**Comment by abarth** [comment]
Looks reasonable.  Two comments:

1) It will be more efficient for us to go directly from Scene to Image, so we might want to have a toImage on Scene rather than forcing folks through the Picture intermediate.

2) Not all Scenes can be converted to Pictures (or to Images).  Some scenes will contain system-composited content (e.g., hardware decoded videos or references to other application's layer).  We probably just need to document that and decide what to do with that.

3) Issue (2) becomes more acute on Fuchsia with the physical renderer because effects like shadows and lighting will be system composited.  That means you're going to loose a lot of effects in this code path.

**Comment by Hixie** [comment]
Can we manually composite (or have the system off-screen composite) scenes to avoid issue 3? (Getting the effect a little like how on macOS, a screenshot of a window will include the shadow but not what's below it?)

Issue 2 is normally resolved by substituting a checkerboard pattern or similar (I vote for a [test pattern](https://en.wikipedia.org/wiki/Test_card)) for content that can't be rendered.

```dart
  Future<Image> Scene.toImage(int width, int height);
  Future<Image> Picture.toImage(int width, int height);
  Future<Uint8List> Image.toByteData(); // returns raw pixel data in RGBA form, row-primary
```

**Comment by abarth** [comment]
Depends what sorts of readbacks are allowed.  It's certainly a feature we can ask for.

**Comment by abarth** [comment]
Those APIs seem safer than promising that we can get a Picture out of a Scene.

**Comment by tvolkert** [comment]
In order to use this to capture a screenshot, seems like we'd also need the following:

```
typedef void SceneCallback(Scene scene);
SceneCallback Window.onRenderScene;
```

**Comment by Hixie** [comment]
Why? Just capture the Scene that you draw.

**Comment by abarth** [comment]
One thing we should be careful about: resolving this future will require returning to the real event look, which might interact poorly with the fake-async world of testing.

**Comment by tvolkert** [comment]
@Hixie I didn't see an easy way in the framework to get access to a `Scene` (say, for example, in the gallery app).

**Comment by abarth** [comment]
I chatted with @tvolkert .  It's not easy today but we can reshuffle things on the framework side to make it easy.

**Comment by Hixie** [comment]
@tvolkert We don't currently expose it, since there's not yet any reason to, but it would be trivial to do so. The framework is where we create the Scene in the first place.

**Comment by jhirth** [comment]
This is a major roadblock for the 2 game projects I had planned. One is a port of a browser game with procedural graphics and the other was supposed to rasterize some kind of vector graphics at the appropriate size on start up and resize.

Rendering to an image is something I was able to do in Java and inside browsers. I assumed I could do something like this in Flutter as well.

**Comment by abarth** [comment]
@jhirth For your use cases, do you need to be able to read back the contents of the Image or just draw it to the screen?

**Comment by jhirth** [comment]
@abarth Just drawing. Up to ~2000 times per frame, that is.

**Comment by abarth** [comment]
Great.  Then this is the right bug for you.
