### ISSUE TITLE
engine-flutter-autoroll and fluttergithubbot alternate adding and removing "waiting for tree to go tree" label

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#67746]
https://github.com/flutter/flutter/pull/66157
![Screen Shot 2020-10-09 at 10 11 45 AM](https://user-images.githubusercontent.com/682784/95612222-e8220000-0a17-11eb-8f6f-d6a60d1390c3.png)

Lamest battlebot fight ever.

**Comment by godofredoc** [comment]
This is expected, the roller failed some tests and was not closed then the autoroller updated the pr and added the label again, and continued with that cycle.

**Comment by godofredoc** [comment]
obsolete
