### ISSUE TITLE
[Web] Please support a custom stylesheet for platform views

### ISSUE THREAD

**Issue by sma** [flutter/flutter#67740]
Flutter Web encapsulates all HTML created via `HtmlElementView` in a shadow DOM of a custom `flt-platform-view` element. The shadow DOM automatically get a [style reset][] attached before the HTML element is added. This makes external customization of the HTML very difficult if not impossible. This is by design, I guess, but I'd like to globally customize the styles via an external .css file and not use inline styles for my HTML in each and every `HtmlElementView`.

Therefore, please support overwriting the `all: initial` style reset with a different style definition. An easy way would be to pass with `ShadowRoot` via `getCreatedView` to the callback, so that I can remove the reset and add my own style elements.

[style reset]: https://github.com/flutter/engine/blob/3d0f12974d043b7ccfe65df44a67b1d560ae5ea4/lib/web_ui/lib/src/engine/html/platform_view.dart#L46

**Comment by ditman** [comment]
We're doing some work to make the Shadow DOM optional; this is a good new feature to add to that work. Let's link this two issues together:

https://github.com/flutter/flutter/issues/50452

**Comment by ditman** [comment]
Platform views now live OUTSIDE the shadow DOM, so they can be styled with standard CSS in the index.html of one's app. This shouldn't be an issue any longer.

Closing, but feel free to reopen if there's still trouble with this!
