### ISSUE TITLE
iOS Simulator has to be restarted before app will launch

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#6775]
## Steps to Reproduce

Run app from command line.

Kill app at command line.

Repeat launch and kill a few times.

ERROR:

SpringBoard: BSXPCMessage received error for message: Connection invalid
com.apple.CoreSimulator.SimDevice.ELIDED.launchd_sim[78460] (UIKitApplication:com.example.Mulligan.dev[0x9e33]: Service exited due to signal: Broken pipe: 13
SpringBoard: Application 'UIKitApplication:com.example.Mulligan.dev[0x9e33]' exited abnormally via signal.
SpringBoard: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port

**Comment by Hixie** [comment]
@gavindoughtie does this still happen for you?

**Comment by Hixie** [comment]
Closing due to lack of response. Please don't hesitate to file a new bug if you still see this.
