### ISSUE TITLE
Randomly blank PlatformView on some Android devices

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#67759]
I compiled and installed https://github.com/iktakahiro/flutter_platformview_example on both a Lenovo TB X505 and a ONEPLUS A3003.

The ONEPLUS always shows both PlatformViews, but the Lenovo randomly shows none, one, or both PlatformViews at every restart: 

![IMG_6235](https://user-images.githubusercontent.com/435817/95625323-9bbadc80-0a78-11eb-81c8-525f0115d38a.jpeg)

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.5 19F101, locale en-DE)
    • Flutter version 1.22.1 at /Users/darolf/dev/flutter
    • Framework revision f30b7f4db9 (27 hours ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/darolf/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/darolf/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Lenovo TB X505F (mobile) • HGAJNWKZ • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by hamdikahloun** [comment]
Hi @derolf 
Can you provide please your `flutter run -v`  .
Thank you

**Comment by TahaTesser** [comment]
Hi @derolf 
Have you noticed this issue on any other device other than Lenovo? 
Can you provide please your `flutter run -v ` 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
