### ISSUE TITLE
Can't see "Linux Fuchsia" logs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#67760]
https://github.com/flutter/engine/pull/21572 links to
https://github.com/flutter/engine/pull/21572/checks?check_run_id=1229291841 links to
https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/15810? links to
https://chromium-swarm.appspot.com/task?id=4f24150e8b44cf10 which says 
"You must sign in to see anything useful."
...but no amount of signing in is making anything happen.

**Comment by godofredoc** [comment]
This is because the fuchsia task is being scheduled directly with swarming and it should be using buildbucket instead. The fix will consolidate the fuchsia builders from sdk and engine using the fuchsia module instead of the current bash script.

**Comment by godofredoc** [comment]
Moving out of the ticket of the ticket queue as implementation will take more than a week.

**Comment by dnfield** [comment]
FYI - if you are signed in with a Google internal account, you will be able to see the swarming job and its logs.

**Comment by Hixie** [comment]
I don't have a Google account on my workstation, so that's not an option.

**Comment by godofredoc** [comment]
To fix this problem we need to use buildbucket instead of swarming apis in the engine build.

**Comment by pcsosinski** [comment]
what needs to happen to get this closed?  is the work above scheduled?  is it really a P1?

**Comment by dnfield** [comment]
With the newer LUCI UI this is not a problem anymore AFAICT.
