### ISSUE TITLE
TextFormField suffix icon still shows even when the container it's in has size 0

### ISSUE THREAD

**Issue by BrainyWayne** [flutter/flutter#67768]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by sidrao2006** [comment]
Hey @BrainyWayne , if you check the source code, it applies a minimum constraints of 48px x 48px. So even if you pass an empty container, it will take up some space
