### ISSUE TITLE
ExpansionPanelList, there is no way to change the color of the arrow icon on the far right. 

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#67771]
Also, is it possible to make it optional, since we can also induce the same effect with the `canTapOnHeader` property for the `ExpansionPanel`.

**Comment by darshankawar** [comment]
@therenca 
Please check this [PR](https://github.com/flutter/flutter/issues/18992) and see if it works for you.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 86driver** [comment]
> Also, is it possible to make it optional, since we can also induce the same effect with the `canTapOnHeader` property for the `ExpansionPanel`.

have you solved this question yet?

**Comment by aDrIaNo34500** [comment]
How no distributed messages on boxmail ?
