### ISSUE TITLE
Update documentation on text input.

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6779]
Is the website's documentation on text input handling up-to-date ? With @mpcomplete #6569 pull request, text input implementation seems unclear...

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/8725#issuecomment-286158769

**Comment by sethladd** [comment]
I'm collecting places where we do document text input, in some fashion. Here's what I found thus far:

* https://docs.flutter.io/flutter/services/TextInput-class.html
* https://docs.flutter.io/flutter/material/Input-class.html
* https://docs.flutter.io/flutter/material/TextField-class.html
* https://docs.flutter.io/flutter/widgets/InputValue-class.html
* https://docs.flutter.io/flutter/material/InputContainer-class.html
* https://docs.flutter.io/flutter/services/TextInputClient-class.html
* https://flutter.io/text-input/

A vision:

* A single library for basic text input, which can get all the doc love and tell a holistic story, with an example.
* A widget for "materialized text input" in the material library
* A widget for "cupertinoized text input" in the cupertino library

If we determine we need more docs, beyond the "input library-level docs", we can update a HOWTO (simple cookbook style input solution).

**Comment by sethladd** [comment]
Related issue: https://github.com/flutter/flutter/issues/7575

**Comment by eseidelGoogle** [comment]
@abarth is also looking at our Text Input APIs as we speak and likely will touch this some.

**Comment by sethladd** [comment]
We can also attempt to answer http://stackoverflow.com/questions/42747394/flutter-inputfield-keyoard

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/9119 has the new hotness for text input widgets.

**Comment by eseidelGoogle** [comment]
@abarth did this.
