### ISSUE TITLE
API for Accessibility

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#678]
Tracking issue for adding necessary APIs for accessibility.

**Comment by sethladd** [comment]
See also https://github.com/flutter/engine/blob/master/sky/specs/accessibility.md

**Comment by eseidelGoogle** [comment]
WIP https://github.com/flutter/engine/pull/2277 and #1309

**Comment by Hixie** [comment]
A basic API now exists and is wired up for Android. I've [filed bugs](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22affects%3A+accessibility%22) for all the remaining issues I'm aware of. I'm closing this so that I feel like I accomplished something. :-)
