### ISSUE TITLE
basic_types.dart assertion textdirection failed

### ISSUE THREAD

**Issue by Babwenbiber** [flutter/flutter#67807]
I am trying to get a simple widget test done.

test:
```
testWidgets('test post tiles', (WidgetTester tester) async {
    await tester.pumpWidget(
      PostTiles(),
    );
```

SUT:
```
class PostTiles extends StatefulWidget {
  PostTiles({Key key}) : super(key: key);
 @override
  State<StatefulWidget> createState() => PostTilesState();
}

class PostTilesState extends State<PostTiles> {
@override
  Widget build(BuildContext context) {
    return ListView.builder(
      padding: EdgeInsets.only(
        top: 5.0,
      ),
      shrinkWrap: true,
      itemCount: 5,
      physics: const NeverScrollableScrollPhysics(),
      itemBuilder: (_, index) {
        return Container();
      },
    ); // NotificationListener
  }
```

I get the following output when I run the test:
I follow the recommendation to create an issue for that :)

> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Listener:
'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
!= null': is not true.

> Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

> The relevant error-causing widget was:
  ListView
  file://<mydir>/lib/core/presentation/widgets/post_tiles.dart:51:21

> When the exception was thrown, this was the stack:
#2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
#3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:150:16)
#4      ShrinkWrappingViewport.createRenderObject (package:flutter/src/widgets/viewport.dart:326:58)
#5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5434:28)
#6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6175:11)
...     Normal element mounting (90 frames)
#96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3512:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3267:20)
#98     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#99     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#100    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#102    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2673:33)
#103    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1088:18)
#104    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#105    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#106    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#107    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:961:9)
#110    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#111    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:948:27)
#112    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:524:22)
#115    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#116    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:521:27)
#117    main.<anonymous closure> (file:///<mydir>/feed_page_test.dart:27:18)
#118    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>

> #119    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#120    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>

> #123    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#124    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#125    FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#130    withClock (package:clock/src/default.dart:48:10)
#131    FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#136    FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#137    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#138    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#139    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>

> #140    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#145    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#146    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#151    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#152    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>

> #153    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#158    Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#159    Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#160    Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#167    Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#168    LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#169    RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#174    RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#175    RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#193    _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#194    new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#198    CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#232    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#240    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#241    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#251    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#260    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#261    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 117 frames from class _AssertionError, dart:async, and package:stack_trace)

> ════════════════════════════════════════════════════════════════════════════════════════════════════

> Test failed. See exception logs above.
The test description was: test post tiles

**Comment by darshankawar** [comment]
@Babwenbiber 
Tried your code sample on latest stable and the test passed successfully. Didn't get `basic_types.dart` error. I wrapped `ListView.builder` with `MaterialApp`.

<img width="1162" alt="Screenshot 2020-10-12 at 3 25 25 PM" src="https://user-images.githubusercontent.com/67046386/95733029-2c730180-0c9f-11eb-87cf-e47912ee6b46.png">

Code sample used:

```
void main() {
  testWidgets('test post tiles', (WidgetTester tester) async {
    await tester.pumpWidget(
      PostTiles(),
    );
  });
}

class PostTiles extends StatefulWidget {
  PostTiles({Key key}) : super(key: key);
  @override
  State<StatefulWidget> createState() => PostTilesState();
}

class PostTilesState extends State<PostTiles> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          padding: EdgeInsets.only(
            top: 5.0,
          ),
          shrinkWrap: true,
          itemCount: 5,
          physics: const NeverScrollableScrollPhysics(),
          itemBuilder: (_, index) {
            return Container();
          },
        ) // NotificationListener,
      ),
    );
  }
}
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

Can you try with above code sample and check if you get same error ?
Thanks.

**Comment by Babwenbiber** [comment]
this code works for me.
However, if I take away the MaterialApp, I get the error from above.

**Comment by darshankawar** [comment]
@Babwenbiber 
When I remove `MaterialApp` and `Scaffold`, it does throw me an error which is different from what you got.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Scrollable(axisDirection: down, physics:
NeverScrollableScrollPhysics, restorationId: null, dirty, state: ScrollableState#acc24(position:
ScrollPositionWithSingleContext#44378(offset: 0.0, range: null..null, viewport: null,
ScrollableState, NeverScrollableScrollPhysics -> ClampingScrollPhysics ->
RangeMaintainingScrollPhysics, IdleScrollActivity#02fdb, ScrollDirection.idle), effective physics:
NeverScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics)):
No Directionality widget found.
Scrollable widgets require a Directionality widget ancestor to determine the cross-axis direction of
the scroll view.
```

This is an expected exception, because the test is looking for `MaterialApp` widget which is the base class for all the widgets you are using in your test. If it can't find the base class, it'll not know how to render the inherited widgets.

**Comment by Babwenbiber** [comment]
I thaught widget testing can be done for any widget (e.g. a custom button).
I don' want to wrap everything with a materialapp, since it is only included by pages.
Nevertheless, I just posted this issue, because the error itself told me to do that :)
If I shell execute some more stuff to examine the "bug" in the lib, I am happy to do it.

**Comment by darshankawar** [comment]
My point is, I am unable to replicate the issue you mentioned originally.  Looking at your error, it's trying to assert at `AxisDirection`:

```
AxisDirection textDirectionToAxisDirection(TextDirection textDirection) {
  assert(textDirection != null);
  switch (textDirection) {
    case TextDirection.rtl:
      return AxisDirection.left;
    case TextDirection.ltr:
      return AxisDirection.right;
  }
}
```

But looking at your code sample, I am not sure how it could possibly throw that exception. Is there more to the code you are trying to test ?
Thanks.

**Comment by Babwenbiber** [comment]
Thats my entire code:
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('test post tiles', (WidgetTester tester) async {
    await tester.pumpWidget(
      PostTiles(),
    );
  });
}

class PostTiles extends StatefulWidget {
  PostTiles({Key key}) : super(key: key);
  @override
  State<StatefulWidget> createState() => PostTilesState();
}

class PostTilesState extends State<PostTiles> {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      padding: EdgeInsets.only(
        top: 5.0,
      ),
      shrinkWrap: true,
      itemCount: 5,
      physics: const NeverScrollableScrollPhysics(),
      itemBuilder: (_, index) {
        return Container();
      }, // NotificationListener,
    );
  }
}
```

Output just like in my post.
Flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.0-9.0.pre, on Linux, locale en_US.UTF-8)
 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

> ! Doctor found issues in 2 categories.

You might ignore the android studio issue. since it popped up today.

**Comment by darshankawar** [comment]
@Babwenbiber Tried above code but not getting that error you mentioned. If you look at the official `widget testing` documentation and [example](https://flutter.dev/docs/cookbook/testing/widget/introduction), `MaterialApp` is used in it. After adding it, there's no error as we noticed, So not sure what more we can do to this issue.

**Comment by Babwenbiber** [comment]
I am sorry, that I couldn't help you...
I'm closing this issue. Feel free to open it and contact me again if I can help.
