### ISSUE TITLE
I am getting this error after flutter build

### ISSUE THREAD

**Issue by collinsNyakoni** [flutter/flutter#67804]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
E/flutter (10418): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (10418): <asynchronous suspension>
E/flutter (10418): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (10418): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)
E/flutter (10418): #3      PackageInfo.fromPlatform (package:package_info/package_info.dart:43:25)
E/flutter (10418): #4      _SplashPageState._checkAppVersion (package:dukago_vendor_hub/page/common/splash.dart:53:49)
E/flutter (10418): #5      _SplashPageState.timer (package:dukago_vendor_hub/page/common/splash.dart:35:32)
E/flutter (10418): #6      _SplashPageState.initState.<anonymous closure> (package:dukago_vendor_hub/page/common/splash.dart:29:7)
E/flutter (10418): #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter (10418): #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
E/flutter (10418): #9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
E/flutter (10418): #10     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (10418): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10418): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10418): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10418): #14     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10418): #15     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10418): #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (10418): #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10418): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (10418): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (10418): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (10418):

**Comment by sidrao2006** [comment]
Hey @collinsNyakoni , could you please provide a minimal reproducible code sample and the output of `flutter doctor -v`

Thanks

**Comment by darshankawar** [comment]
@collinsNyakoni 
Please provide above requested details.
Thanks.

**Comment by dassaniansh** [comment]
Hey @collinsNyakoni ,
I had this issue before and this is what I have done to fix it:
    Run flutter clean then Run flutter pub get
After that delete your app from device and again run it.
Hope this works :)
Thank you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
