### ISSUE TITLE
AnimatedContainer unexpected behaviour

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#67815]
I wannt animate container height, my problem is:

**buttons can not be shrink height**

I dont' know if this is a bug or my false usage.

Picture say a thousand words:

I have a AnimatedContainer and a Row inside it, serveral widgets in a Row:
![image](https://user-images.githubusercontent.com/21303438/95652668-530d2d00-0b25-11eb-8a2c-76febb8a2e38.png)

When shrink down, you will see, all widgets can shrink down. except button:

![image](https://user-images.githubusercontent.com/21303438/95652680-68825700-0b25-11eb-9141-5544e47d49f7.png)

any body knows why?

**Comment by iapicca** [comment]
@jinfagang 
can you provide a minimal reproducible code sample

**Comment by jinfagang** [comment]
@iapicca  I solve by replace IconButton with a Text widget, icons can not be hide, while text and others can, I don't know why.

I need using hide feature, so that AnimatedContainer can help me hide also with a nice animation. I dont need scroll here.

**Comment by pedromassangocode** [comment]
Hi @jinfagang 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
