### ISSUE TITLE
pushNamedAndRemoveUntil does not call Route.dispose()

### ISSUE THREAD

**Issue by leobispo** [flutter/flutter#67817]
When calling pushNamedAndRemoveUntil from Navigator it is not calling the Route.dispose method.

The Dependency Injection system from Getx depends on the .dispose() method to be called, otherwise it cannot know that a Widget has disposed and cannot release the Dependency from the Dependency tree.

In my opinion each pop operation in the navigation tree should call the Route.dispose method.

If my Assumption is correct let me know and I will change the code to have this behavior.

**Comment by pedromassangocode** [comment]
Hi @leobispo 
Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
