### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by mahimtk2** [flutter/flutter#67824]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1413:15)
#4      Cache.downloadFile (package:flutter_tools/src/cache.dart:491:5)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:640:23)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:636:55)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:785:13)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:831:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#22     _rootRun (dart:async/zone.dart:1190:13)
#23     _CustomZone.run (dart:async/zone.dart:1093:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.2 at G:\flutter\bangla\flutter
    • Framework revision bbfbf1770c (8 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision <<<<<<< HE
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Mahim\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\Mahim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • V85 (mobile) • H3565Y28GA10B1 • android-arm • Android 5.1 (API 22)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/50880
Thanks.

**Comment by jonahwilliams** [comment]
@Abhishek01039 why do you think these are duplicates?

**Comment by jonahwilliams** [comment]
@mahimtk2 can you please provide the output of `flutter doctor -vv` ?

**Comment by iapicca** [comment]
this should be fixed in master https://github.com/flutter/flutter/issues/66415#issuecomment-701003004 https://github.com/flutter/flutter/pull/65814

**Comment by mahimtk2** [comment]
@jonahwilliams 
PS C:\Users\Mahim> flutter doctor
>>
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The current Dart SDK version is 2.9.1.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <2.11.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Error: 'pub upgrade' still failing after 10 tries, giving up.
Downloading package sky_engine...

Oops; flutter has exited unexpectedly: "FileSystemException: Creation failed, path =
'G:\flutter\bangla\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\@lt@@lt@@lt@@lt@@lt@@lt@@lt@
HEAD
9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
=======
75bef9f6c8ac2ed4e1e04cdfcd88b177d9f1850d
@gt@@gt@@gt@@gt@@gt@@gt@@gt@ f30b7f4db93ee747cd727df747941a28ead25ff5' (OS Error: The system cannot find the path
specified.
, errno = 3)".

A crash report has been written to C:\Users\Mahim\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Creation+failed%2C+path+%3D+%27G%3A%5Cflutter%5Cbangla%5Cflutter%5Cbin%5Ccache%5Cdownloads%5Cstorage.googleapis.com%5Cflutter_infra%5Cflutter%5C%40lt%40%40lt%40%40lt%40%40lt%40%40lt%40%40lt%40%40lt%40+HEAD%0D%0A9d5b21729ff53dbf8eadd8bc97e0e30d77abec95%0D%0A%3D%3D%3D%3D%3D%3D%3D%0D%0A75bef9f6c8ac2ed4e1e04cdfcd88b177d9f1850d%0D%0A%40gt%40%40gt%40%40gt%40%40gt%40%40gt%40%40gt%40%40gt%40+f30b7f4db93ee747cd727df747941a28ead25ff5%27+%28OS+Error%3A+The+system+cannot+find+the+path+specified.%0D%0A%2C+errno+%3D+3%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JTUPO

PS C:\Users\Mahim>
