### ISSUE TITLE
Flutter Stepper - Data persist on Navigating from Step1 to Step2 (& Step2 to Step 3 and so on)

### ISSUE THREAD

**Issue by Aravin** [flutter/flutter#67829]
I am working on a flutter application with Stepper with 3 step.

Stepper is wrapped with form controller.

when I fill the form data in step 1 and navigate to second step - Data entered in the step 1 are shown in step 2.

And Step 2 data shown in step 3.

I have verified the code multiple times, there is not issue in code. I guess it as a Flutter Issue.

**Screenshots**

![Screenshot_1602348430](https://user-images.githubusercontent.com/4869265/95660711-3bdf3700-0b47-11eb-9779-74d43433268e.png)

![InkedScreenshot_1602348434_LI](https://user-images.githubusercontent.com/4869265/95660687-1eaa6880-0b47-11eb-8311-ceaeeffb0997.jpg)

**Full Source Code** 

[Github Repo](https://github.com/Aravin/WarrantyManager/blob/2fd22e30d985c2feeecc4b53a1e5cf8242b593cf/lib/screens/add.dart#L207)

**Environment**

    Version: 1.50.0 (system setup)
    Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
    Date: 2020-10-07T06:10:52.432Z
    Electron: 9.2.1
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Windows_NT x64 10.0.18363

    [√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
     
    [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    [√] Android Studio (version 4.0)
    [√] VS Code, 64-bit edition (version 1.50.0)
    [√] Connected device (1 available)

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/flutter/issues/63907
@Aravin consider the proposed workaround https://github.com/flutter/flutter/issues/63907#issuecomment-674852746

**Comment by Aravin** [comment]
@iapicca 

1. Yes it is third party package, that package internally uses your widget.

2. I don't see it has 3rd party package issue. Since many other people had that issue.

3. You can refer this bug for flutter native bug : #63907 

4. Yes, initially I aksed in stackoverflow and then I found it is a bug from flutter. Nobody can fix flutter bug :/ than a you guys.

4. flutter upgrade -f
```
C:\Windows\system32>flutter upgrade -f
Flutter is already up to date on channel stable
Flutter 1.20.3 • channel stable • https://github.com/Aravin/flutter.git
Framework • revision 216dee60c0 (6 weeks ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

**Comment by TahaTesser** [comment]
Hi @Aravin 
It does look like a duplicate of https://github.com/flutter/flutter/issues/63907
Can you please provide a complete reproducible minimal code sample without using third-party package? not a production code 
Thank you

**Comment by Aravin** [comment]
I am able to overcome this issue using uniqueKey.

--
Thanks.
