### ISSUE TITLE
Data Table Class, couldn't use few properties

### ISSUE THREAD

**Issue by yash-1th** [flutter/flutter#67836]
I got the following problem when I tried to use the below-mentioned properties in the **Data Table class**

**Problem**: The named parameter '_(below properties)_' isn't defined.

**Problematic Properties:**
1. dataTextStyle
2. headingRowColor
3. headingTextstyle
4. showBottomBorder

**Comment by darshankawar** [comment]
@yash-1th 
Tried the official `data table` code sample and was able to use above listed properties without any issues.

```
return DataTable(
      headingRowColor:,
      dataTextStyle: ,
      headingTextStyle: ,
      showBottomBorder: ,
```

I am on latest Master. Try [this](https://api.flutter.dev/flutter/material/DataTable-class.html) code sample and see if it works for you.
Thanks.

**Comment by yash-1th** [comment]
I tried the official code sample, the problem still exists.

**Comment by darshankawar** [comment]
@yash-1th 
Try to run `flutter clean` and then check if it still happens. If so, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
