### ISSUE TITLE
Input field keeps losing focus.

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6783]
As you can see in the GIF below, the input field keeps losing focus each time the user tries to interact with.
![screenshot](https://cloud.githubusercontent.com/assets/8492909/20158822/1d8b82c2-a6dd-11e6-8f4c-31b772a500fd.gif)

The portion of code responsible for the Input field:

```
new Form(
      key: new GlobalKey<FormState>(),
      child: new Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          new InputFormField(
            labelText: "Title",
            onSaved: (InputValue val) {
              ....
           },
         ),
          ...
        ],
      ),
    );

**Comment by Hixie** [comment]
The problem is that you're creating an entirely new Form each time you build, because you're giving it a new different anonymous key each time.

**Comment by sethladd** [comment]
I wonder if we should add some docs to https://flutter.io/text-input/ ?

**Comment by Hixie** [comment]
This particular issue is not Form- or Input-specific. But yes, we should help people who end up in this situation, certainly.

**Comment by nelsonkam** [comment]
@Hixie I get it, the key should be a top-level constant right ?

**Comment by nelsonkam** [comment]
@sethladd [https://flutter.io/text-input/](https://flutter.io/text-input/) has no documentation on Forms, InputFormFields and FormFields

**Comment by Hixie** [comment]
re the key, it depends what you're doing. In general a Form doesn't require a key.

re the docs, yeah those are new as of the last week. We're iterating on them right now, we'll update the docs when we're more stable in a few weeks I expect.

**Comment by nelsonkam** [comment]
@Hixie Okay thanks for your help !
