### ISSUE TITLE
image_picker issue with bitcode when building release for ios

### ISSUE THREAD

**Issue by momoDragon** [flutter/flutter#67831]
**Steps to reproduce**
add image_picker plugin to project 
run `flutter build ios --release`

**Error Thrown**

`Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    /Users/mozesong/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+11/ios/Classes/FLTImagePickerPlugin.m:149:20: warning: 'UIAlertView' is deprecated:
    first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:@"Error"
                       ^
    In module 'UIKit' imported from /Users/mozesong/Documents/GitHub/Green-Hero-Apps-2.0/green_hero_vendor/ios/Pods/Target Support Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12
    : note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    /Users/mozesong/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+11/ios/Classes/FLTImagePickerPlugin.m:149:20: warning: 'UIAlertView' is deprecated:
    first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:@"Error"
                       ^
    In module 'UIKit' imported from /Users/mozesong/Documents/GitHub/Green-Hero-Apps-2.0/green_hero_vendor/ios/Pods/Target Support Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12
    : note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    ld: bitcode bundle could not be generated because '/Users/mozesong/Documents/GitHub/Green-Hero-Apps-2.0/green_hero_vendor/ios/Flutter/Flutter.framework/Flutter' was built
    without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file
    '/Users/mozesong/Documents/GitHub/Green-Hero-Apps-2.0/green_hero_vendor/ios/Flutter/Flutter.framework/Flutter' for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
`

**Flutter Doctor**
`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-MY)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.50.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

`

**Note:**
Works perfectly fine when building to ios simulator

**Comment by darshankawar** [comment]
@momoDragon 
Tried the official `image_picker` plugin example on iPhone 6s and was able to build a release version without any issues.

```
dhs@Dhss-MacBook-Pro example % flutter build ios --release
Building io.flutter.plugins.imagePickerExample for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Found saved certificate choice "Apple Development: Darshan Kawar (HJWLFNL782)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (HJWLFNL782)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        11.1s
Xcode build done.                                           18.4s
Built /Users/dhs/Documents/NCFlutter/plugins/packages/image_picker/image_picker/example/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro example % 

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0d8d4f77aa (4 days ago), 2020-10-08 09:26:30 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 x86_64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

```

</details>

Can you provide a minimal complete code sample that shows the issue ? Also please try the official plugin example and see if it works for you or throw same error.

Thanks.

**Comment by jnsmith0274** [comment]
I am able to produce the same warning:

`
/Users/jason/Development/frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+10/ios/Classes/FLTImagePickerPlugin.m:149:20: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
`

In order to do this, I modified the Podfile to target a minimum of iOS 9.0 using the following:

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
`

Note that this is only a warning and not an error.  Perhaps it is time to move to using UIAlertControllerStyleAlert?

**Comment by tomcajot** [comment]
I get the same issue :/

**Comment by jpetro416** [comment]
This is happening to me as well, doesn't work on both the emulator or an iphone 8 with all the latest updates... Don't close this issue!

`Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           125.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+17/ios/Classes/FLTImagePickerPlugin.m:149:20: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
        [[[UIAlertView alloc] initWithTitle:NSLocalizedString(@"Error", nil)
                       ^
    In module 'UIKit' imported from /Users/jpetro/Documents/GitHub/test-flutter-app/ios/Pods/Target Support Files/image_picker/image_picker-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    1 warning generated.
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+RoundedCorner.m:60:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight {
    ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+RoundedCorner.m:11:1: note: method 'addRoundedRectToPath:context:ovalWidth:ovalHeight:' declared here
    - (void)addRoundedRectToPath:(CGRect)rect context:(CGContextRef)context ovalWidth:(CGFloat)ovalWidth ovalHeight:(CGFloat)ovalHeight;
    ^
    1 warning generated.
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:96:99: warning: enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
                [NSException raise:NSInvalidArgumentException format:@"Unsupported content mode: %d", contentMode];
                                                                                                 ~~   ^~~~~~~~~~~
                                                                                                 %ld  (long)
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:155:13: warning: enumeration values 'UIImageOrientationUp' and 'UIImageOrientationUpMirrored' not handled in switch [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:155:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:175:13: warning: 4 enumeration values not handled in switch: 'UIImageOrientationUp', 'UIImageOrientationDown', 'UIImageOrientationLeft'... [-Wswitch]
        switch (self.imageOrientation) {
                ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:175:13: note: add missing switch cases
        switch (self.imageOrientation) {
                ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:110:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:12:1: note: method 'resizedImage:transform:drawTransposed:interpolationQuality:' declared here
    - (UIImage *)resizedImage:(CGSize)newSize
    ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:152:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize {
    ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Resize.m:16:1: note: method 'transformForOrientation:' declared here
    - (CGAffineTransform)transformForOrientation:(CGSize)newSize;
    ^
    5 warnings generated.
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Alpha.m:97:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size {
    ^
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/UIImage+Alpha.m:10:1: note: method 'newBorderMask:size:' declared here
    - (CGImageRef)newBorderMask:(NSUInteger)borderSize size:(CGSize)size;
    ^
    1 warning generated.
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+3/ios/Classes/FlutterNativeImagePlugin.m:77:19: warning: unused variable 'fileName' [-Wunused-variable]
            NSString *fileName = [[fileArgument lastPathComponent] stringByDeletingPathExtension];
                      ^
    1 warning generated.
    /Users/jpetro/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-2.0.13+1/ios/Classes/Music.swift:612:25: warning: initialization of variable 'error' was never used; consider replacing with assignment to '_' or removing it
                        var error = item.error
                        ~~~~^~~~~
                        _
    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.
                MediaQuery.of(context, nullOk: true)?.textScaleFactor ??
                                       ^^^^^^
    ../../../flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
      static MediaQueryData of(BuildContext context) {
                            ^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.`

**Comment by Jamesfleming1** [comment]
I am getting the same exact errors as jpetro, please reopen this issue

**Comment by rafterco** [comment]
Same exact issue here, please reopen.

**Comment by taiyrbegeyev** [comment]
The same issue occurs for me!

**Comment by rafterco** [comment]
I fixed this on my build: 

1) I uncommenting this line in ios/Podfile and updated to '10.0':
     `platform :ios, '10.0'

2) Lots of warnings but one error indicated an issue with Firebase.  Running this command fixed that error and allowed the build to work:  
   `pod update Firebase/Firestore`
