### ISSUE TITLE
Flutter web not working in hosted site .

### ISSUE THREAD

**Issue by SAMYAK99** [flutter/flutter#67845]
I have published my site with codemagic hosting . This site works completely fine in my console but keeps loading in hosted site .
#URL - https://newsrecital.codemagic.app
#Github Repo - https://github.com/SAMYAK99/NewsRecital

**Comment by iapicca** [comment]
@SAMYAK99 I have a [workaround](https://github.com/flutter/flutter/issues/67655) for you :)

**Comment by SAMYAK99** [comment]
@iapicca yeah ! I saw you have same issue .
Did you find any solution for this ?

**Comment by iapicca** [comment]
> @iapicca yeah ! I saw you have same issue .
> Did you find any solution for this ?

I did in my initial post at the bottom there is a workaround
that was suggested to me on [stackoverflow](https://stackoverflow.com/a/64250708/9836706)
([it works](http://yakforward.com/))

**Comment by SAMYAK99** [comment]
@iapicca my asssets are loading but the data which i am fetching from the api in the json format is not loading 😐

**Comment by darshankawar** [comment]
@SAMYAK99 
Usually when we host a web app on to external domains, we need to give access to JSON files. Have you looked into this aspect ? If not, can you try by giving the required access and see if it works ?
Thanks.

**Comment by SAMYAK99** [comment]
I have used an open source API ! still the contents of API is not loading in hosted site . It works perfectly fine in my local host .

**Comment by darshankawar** [comment]
@SAMYAK99 
Have you reached out to codemagic on this issue ? It could be issue at their end.

**Comment by SAMYAK99** [comment]
@darshankawar Its not about codemagic . I have tried hosting the flutter site on Netlify and Github Pages still this error exists . 
Here is the repo link  , you can try hosting it any server . I guess Flutter web is still in beta version , that can be issue  😐
Repo - https://github.com/SAMYAK99/NewsRecital

**Comment by iapicca** [comment]
@SAMYAK99 the link you provided looks like production code
with several 3rd party plugins 
[flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)
[google_fonts](https://pub.dev/packages/google_fonts) ( **_this doesn't support web!_** )
[dynamic_theme](https://pub.dev/packages/dynamic_theme)
[flutter_tts](https://pub.dev/packages/flutter_tts)

I recommend to provide a minimal reproducible code sample
that doesn't rely on 3rd party plugin 
and making sure that the packages in use support web

**Comment by SAMYAK99** [comment]
@iapicca here is another project . I have used only http package to fetch the data from the api . I am using an open source api which does not required any credentials 
Repo link for code - https://github.com/SAMYAK99/flutterwebtest 
Repo link for web - https://github.com/SAMYAK99/fwebtest
hosted site - https://samyak99.github.io/fwebtest/

# Expected output in the hosted site 
![debug](https://user-images.githubusercontent.com/54956876/95845054-55f76000-0d67-11eb-8a65-6e7fb6575593.png)

# Recived Output 
Blank screen

**Comment by iapicca** [comment]
@SAMYAK99 
I tested your [sample](https://github.com/SAMYAK99/flutterwebtest) with [dhttpd](https://pub.dev/packages/dhttpd) and seems to work just fine
I suspect @darshankawar is right, it might depend from the host

<details>
<summary>logs</summary>

```bash
francesco@francesco-yoga720  ~/projects/other  cd flutterwebtest                                                                                                                     ✔  4324  13:01:38 
 francesco@francesco-yoga720  ~/projects/other/flutterwebtest  master  flutter_master build web --release                                                                           ✔  4325  13:01:47 
Downloading Web SDK...                                             15.4s
Running "flutter pub get" in flutterwebtest...                      1.4s
Compiling lib/main.dart for the Web...                             31.3s
 francesco@francesco-yoga720  ~/projects/other/flutterwebtest  master ●  cd build/web                                                                                               ✔  4326  13:02:54 
 francesco@francesco-yoga720  ~/projects/other/flutterwebtest/build/web  master ●  dhttpd --port 8888                                                                               ✔  4327  13:03:02 
Server started on port 8888
2020-10-13T13:03:28.686031  0:00:00.017155 GET     [200] /
2020-10-13T13:03:28.768809  0:00:00.000730 GET     [200] /main.dart.js
2020-10-13T13:03:28.991073  0:00:00.000622 GET     [200] /assets/FontManifest.json
2020-10-13T13:03:29.026789  0:00:00.001740 GET     [200] /assets/fonts/MaterialIcons-Regular.otf
2020-10-13T13:03:29.030651  0:00:00.000414 GET     [200] /assets/fonts/CircularStd-Medium.ttf
2020-10-13T13:03:29.031947  0:00:00.000328 GET     [200] /favicon.png
2020-10-13T13:03:29.033543  0:00:00.000376 GET     [200] /assets/fonts/CircularAir-Light.ttf
2020-10-13T13:03:29.034786  0:00:00.000456 GET     [200] /assets/fonts/CircularStd-Bold.ttf
2020-10-13T13:03:29.036568  0:00:00.000414 GET     [200] /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
2020-10-13T13:03:29.252904  0:00:00.000723 GET     [200] /flutter_service_worker.js?v=1936611791
2020-10-13T13:03:29.273203  0:00:00.000671 GET     [200] /?revision=7a50a6ee7ae47282153b636e6fe699bb
2020-10-13T13:03:29.274834  0:00:00.000411 GET     [200] /main.dart.js?revision=cf4be343706c96103b223da275b0e45f
2020-10-13T13:03:29.276820  0:00:00.000825 GET     [200] /index.html?revision=7a50a6ee7ae47282153b636e6fe699bb
2020-10-13T13:03:29.279239  0:00:00.000668 GET     [200] /assets/NOTICES?revision=0f4f8e2395b7a8a5ef55ca7bea8f4850
2020-10-13T13:03:29.282474  0:00:00.000766 GET     [200] /assets/AssetManifest.json?revision=601ae85404135d5e521edc950ce826bf
2020-10-13T13:03:29.284798  0:00:00.000702 GET     [200] /assets/FontManifest.json?revision=9401f0dc37eed668d80deced33c61e72
^C
```


</details>

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/95846980-d2347800-0d54-11eb-8cd5-498e3b750bf7.png)

</details>

**Comment by SAMYAK99** [comment]
@iapicca like I said it is working completely fine on my local host . Can you please host it on any server like github pages , netlify etc... and give me the link ?

**Comment by iapicca** [comment]
> @iapicca like I said it is working completely fine on my local host . Can you please host it on any server like github pages , netlify etc... and give me the link ?

dhttpd is a sever-like hosting

**Comment by SAMYAK99** [comment]
@ianloic  can you generate any url with dhttpd ?

**Comment by darshankawar** [comment]
@iapicca thanks for digging in.
@SAMYAK99 since there seem to be different issues while trying to host web app, like assets, fonts aren't loading properly, irrespective on which host you try to deploy, your issue could also be related to it. Would you be okay to track this in [67655](https://github.com/flutter/flutter/issues/67655) to have all these issues at one place ?
Thanks.

**Comment by SAMYAK99** [comment]
@darshankawar my issue is different .  Assets, fonts are loading properly but no data is received from the api in the hosted web version . 
URL - https://newsrecital.codemagic.app

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.

**Comment by azbuky** [comment]
@SAMYAK99 When loading your web page I get an error log in the browser's console `Failed to load resource: the server responded with a status of 426 ()`

[This article](https://community.netlify.com/t/getting-error-426-from-newsapi-org/16101) indicates that the free API key from newsapi.org does not work in production, only on localhost.

**Comment by SAMYAK99** [comment]
> @azbuky  here is another project . I have used only http package to fetch the data from the api . I am using an open source api which does not required any credentials . You can try to host this project in any server and share the url 😀 . Likewise you can use any project , I just want to see is it possible with flutter web to parse the json data from the api in the hosted server . 


> Repo link for code - https://github.com/SAMYAK99/flutterwebtest
> Repo link for web - https://github.com/SAMYAK99/fwebtest
> hosted site - https://samyak99.github.io/fwebtest/
> 
> # Expected output in the hosted site
> ![debug](https://user-images.githubusercontent.com/54956876/95845054-55f76000-0d67-11eb-8a65-6e7fb6575593.png)
> 
> # Recived Output
> Blank screen

**Comment by azbuky** [comment]
@SAMYAK99 you are not correctly deploying your sample project at https://samyak99.github.io/fwebtest . Check the console in Chrome for errors, main.dart.js is not found (404) so there is nothing to load.

**Comment by iapicca** [comment]
> @SAMYAK99
> I tested your [sample](https://github.com/SAMYAK99/flutterwebtest) with [dhttpd](https://pub.dev/packages/dhttpd) and seems to work just fine
> I suspect @darshankawar is right, it might depend from the host

> @SAMYAK99 you are not correctly deploying your sample project at https://samyak99.github.io/fwebtest . Check the console in Chrome for errors, main.dart.js is not found (404) so there is nothing to load.

I concur with @azbuky 
the issue is very likely related to a problem with the host or the deployment itself 
rather than a bug caused by flutter

**Comment by SAMYAK99** [comment]
So the conclusion is  as of now Flutter web does not  support JSON parsing in any hosted server 🤨

**Comment by SAMYAK99** [comment]
@azbuky yes you are right 😀 . I have hosted in different server and it works . 
URL - https://fweb.codemagic.app/#/
But I still have a doubt , is it possible to host flutter project which require credentials like News api . 
If Yes can you please guide me how to host my first project 😅.

**Comment by iapicca** [comment]
@SAMYAK99 since the problem isn't with flutter I recommend you to close this issue
for 

> [...] can you please guide me how to host my first project .

this type of question should be asked on Stackoverflow and not discussed on Flutter github repo

**Comment by SAMYAK99** [comment]
sure

**Comment by loreliemiranda** [comment]
> @azbuky yes you are right 😀 . I have hosted in different server and it works .
> URL - https://fweb.codemagic.app/#/
> But I still have a doubt , is it possible to host flutter project which require credentials like News api .
> If Yes can you please guide me how to host my first project 😅.

Hi @SAMYAK99, I encountered the same issue now using code magic. How did you manage to make it work? Thank you!

**Comment by radsen** [comment]
Guys, I don't know if this could help anyone else.

For us, the spread(...) operator was not supported in release mode (No idea why). So, we replaced the operator in the API calls and we started getting responses in release mode.

This probably can happen with other libraries as well
