### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by Zeehshan** [flutter/flutter#67846]
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 110 pos 12: '_positions.isNotEmpty'

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_swiper/flutter_swiper.dart';
import 'package:tour_app/comman/config.dart';
import 'package:tour_app/model/json/response.dart';
import 'package:tour_app/utils/repo.dart';

import 'listing_image.dart';

class HeaderSection extends StatelessWidget {
  final List<ListPictureHome> data;
  final List<String> title;
  HeaderSection({@required this.data, this.title});
  @override
  Widget build(BuildContext context) {
    double w = MediaQuery.of(context).size.width;
    double h = MediaQuery.of(context).size.height;
    Orientation orien = MediaQuery.of(context).orientation;
    bool screen = orien == Orientation.portrait ? true : false;
    return Swiper(
      autoplayDisableOnInteraction: false,
      autoplay: data.length > 1 ? true : false,
      loop: data.length > 1 ? true : false,
      itemBuilder: (context, index) {
        return Column(
          children: <Widget>[
          title == null ? Container() :  Container(margin: EdgeInsets.symmetric(horizontal: 20),child: Center(child: Text(title[index],style: TextStyle(fontSize: 18),))),
            title == null ? Container() :  SizedBox(height: 10,),
//            Expanded(
//              child: HomeImage(
//                w: w,
//                borderRadius: BorderRadius.circular(0),
//                image:serverConfig["baseUrl"]+"uploads/${data[index].picture}",
//              ),
//            ),
            Expanded(
              child: Container(
                width: w,
                color: Colors.black,
                child: CachedNetworkImage(
                  imageUrl:serverConfig["baseUrl"]+"uploads/${data[index].picture}",
                  placeholder: (context, url) => Container(
                    width: w,
                    height: h,
                    color: Colors.black,
                    child: Center(child: CircularProgressIndicator(valueColor: AlwaysStoppedAnimation<Color>(Colors.white),strokeWidth: 2.0,)),
                  ),
                  errorWidget: (context, url, error) => Container(
                    width: w,
                    height: h,
                    color: Colors.grey.withOpacity(.2),
                  ),
                ),
              ),
            ),
          ],
        );
      },
      itemCount: data?.length ?? 0,
//      control: new SwiperControl(
//        color: Util.baseColor,
//        disableColor: Colors.transparent,
//        padding: EdgeInsets.only(top: h*.9, right: 40, left: 40)
//      ),
      pagination: new SwiperPagination(
          margin: new EdgeInsets.all(5.0),
          builder: new DotSwiperPaginationBuilder(
              color: Colors.grey, activeColor: Utils.baseColr)),
    );
  }
}

**Comment by iapicca** [comment]
@Zeehshan can you provide a **_reproducible_** code sample

**Comment by Abhishek01039** [comment]
Hi @Zeehshan 
```
new Swiper(
          itemBuilder: (BuildContext context, int index) {
            return new Image.asset(
              images[index],
              fit: BoxFit.fill,
            );
          },
          autoplay: true,
          itemCount: images.length,
          scrollDirection: Axis.vertical,
          pagination: new SwiperPagination(alignment: Alignment.centerRight),
          control: new SwiperControl(),
        ));
```
please provide the SwiperControl object to the control parameter.
Thanks.

**Comment by Zeehshan** [comment]
thanks for you concentration i git it
