### ISSUE TITLE
[Improvement] Alignment#toString should have prefix `Alignment.`

### ISSUE THREAD

**Issue by HeavenOSK** [flutter/flutter#67859]
Currently, when the `Alignment` is at a fixed point, such as `Alignment.center`, the [Alignment#toString](https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/painting/alignment.dart#L349) does not output the class name.

This is an unfriendly output when developers debugging.

## Proposal
I suggest adding a prefix`Alignment` to `Alignment#toString`.In the case of [AlignmentDirectional#toString](https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/painting/alignment.dart#L538), it seems to be outputting the class name, so I thought we should do the same.

**Comment by shihaohong** [comment]
Closing since that has been fixed with https://github.com/flutter/flutter/pull/67860
