### ISSUE TITLE
Child override parent widget background color

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#67850]
![image](https://user-images.githubusercontent.com/21303438/95668946-138a2380-0bad-11eb-98b8-b4feda078b13.png)

I have a Card, and a container inside it, the code liek this:

```
 Card(
            margin: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            color: Color(tasks.projectColor),
            shadowColor: Colors.grey.withAlpha(18),
            elevation: 4,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
            borderOnForeground: true,
            child: InkWell(
              borderRadius: BorderRadius.circular(16),
              child: Container(
                height: 80,
                margin: EdgeInsets.only(left: 12, top: 0, bottom: 0),
                decoration: BoxDecoration(
                  color: Theme.of(context).scaffoldBackgroundColor,
                  // color: Colors.red,

                  // borderRadius: BorderRadius.only(
                  //     topLeft: Radius.circular(16),
                  //     bottomRight: Radius.circular(16)),
                ),
                child:
```

The card set color to pink, and container is full fill parent with a padding on left, with white background color.

But **there always some 1pixel pink color from parent widget**, I dont want it, is that a bug or something? I have set all paddings and margins to zero.

**Comment by sidrao2006** [comment]
Hey @jinfagang , you are giving the container a fixed height. So the height of the card is heater than that of the Container.

**Comment by sidrao2006** [comment]
Could you removing the height of the container and instead pass the size to the Card

**Comment by jinfagang** [comment]
@sidrao2006  I set height to same. I uncomment height of card ,same effect.

**Comment by TahaTesser** [comment]
Hi @jinfagang 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
