### ISSUE TITLE
[web]: Flutter web navigator showing error "!navigator._debugLocked is not true"

### ISSUE THREAD

**Issue by ujjwalbe** [flutter/flutter#67870]
Everytime i try to use Navigator.pop() or popAndPushRenamed() this error appear without navigating me to defined page/screen
And nothing happen except the error. Tried with Navigator.of(context) the error seems to remain same.

Flutter 1.22.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (3 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1

Google Chrome -> Version 85.0.4183.121 (Official Build) (64-bit)
```
Error: Assertion failed: 
../…/widgets/navigator.dart:2416
!navigator._debugLocked
is not true
    at Object.throw_ [as throw] (http://localhost:37551/dart_sdk.js:4328:11)
    at Object.assertFailed (http://localhost:37551/dart_sdk.js:4275:15)
    at http://localhost:37551/packages/flutter/src/widgets/widget_span.dart.lib.js:20583:60
    at thunk (http://localhost:37551/packages/flutter/src/scheduler/ticker.dart.lib.js:292:9)
    at _RootZone.runUnary (http://localhost:37551/dart_sdk.js:37447:58)
    at _FutureListener.then.handleValue (http://localhost:37551/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:37551/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:37551/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:37551/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:37551/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:37551/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:37551/dart_sdk.js:37714:13)
    at http://localhost:37551/dart_sdk.js:33226:9
```

**Comment by Abhishek01039** [comment]
Hi @ujjwalbe 
can you please provide the minimal reproduction code?
Thanks.

**Comment by ujjwalbe** [comment]
Here is the sample code, it works when i push a material route but does not work when i try to use anything with pop

```
class AdminMainPage extends StatefulWidget {
  @override
  _AdminMainPageState createState() => _AdminMainPageState();
}

class _AdminMainPageState extends State<AdminMainPage> {
  TokenService _tokenService = TokenService();
  NetworkService _networkService = NetworkService();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 18.0),
            child: IconButton(
                icon: Icon(Icons.refresh),
                onPressed: () {
                  setState(() {});
                }),
          ),
          MaterialButton(
            color: Colors.white,
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => SearchPage()));
            },
            child: Row(
              children: [
                Icon(Icons.search),
                Center(
                    child: Text(
                  "Search",
                  style: TextStyle(fontSize: 20.0),
                )),
              ],
            ),
          ),
          SizedBox(width: 20.0),
          IconButton(
              icon: Icon(Icons.exit_to_app_rounded),
              onPressed: () {
                _tokenService.deleteKey();

                Navigator.popAndPushNamed(context, '/login');
              }),
          SizedBox(width: 20.0),
        ],
        leading: Container(),
        title: Text("Admin Page"),
      ),
      body: Container(
        child: FutureBuilder(
          future: _networkService.getAlluser(),
          builder: (context, AsyncSnapshot<UserModel> snapshot) {
            if (snapshot.hasData) {
              final UserModel result = snapshot.data;
              final data = result.data;
              print(data.length);
              return ListView.builder(
                  itemCount: data.length,
                  itemBuilder: (context, int index) {
                    return ItemCard(
                      onPress: () {
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) =>
                                    UpdateUserMainPage(userData: data[index])));
                      },
                      imgUrl: data[index].photo,
                      occupation: data[index].profession,
                      cityLocation:
                          data[index].city != null ? data[index].city : "N/A",
                      daysCount: data[index].countDays,
                      userName: data[index].name,
                      license: data[index].license != null
                          ? data[index].license
                          : "N/A",
                      available: data[index].online,
                    );
                  });
            } else
              return Center(child: CircularProgressIndicator());
          },
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment]
@ujjwalbe 
Please provide a complete minimal reproducible code sample that we can copy paste and run directly in IDE. I tried your above code sample, but getting compile errors. I don't know what `TokenService`, `NetworkService` and `UserModel` class is.
Thanks.

**Comment by ujjwalbe** [comment]
Here's the full code you can add and run

Token service doing just one thing it's deleting the key ,

`class UserModel {
  bool success;
  List<UserData> data;

  UserModel({this.success, this.data});

  UserModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      data = new List<UserData>();
      json['data'].forEach((v) {
        data.add(new UserData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class UserData {
  String role;
  String city;
  String resume;
  String photo;
  int countDays;
  bool online;
  bool profileComplete;
  String createdAt;
  String sId;
  String name;
  int phone;
  String license;
  String profession;
  int iV;
  List<Events> events;
  String id;

  UserData(
      {this.role,
      this.city,
      this.resume,
      this.photo,
      this.countDays,
      this.online,
      this.profileComplete,
      this.createdAt,
      this.sId,
      this.name,
      this.phone,
      this.profession,
      this.iV,
      this.events,
      this.id,
      this.license});

  UserData.fromJson(Map<String, dynamic> json) {
    role = json['role'];
    license = json['license'];
    city = json['city'];
    resume = json['resume'];
    photo = json['photo'];
    countDays = json['countDays'];
    online = json['online'];
    profileComplete = json['profileComplete'];
    createdAt = json['createdAt'];
    sId = json['_id'];
    name = json['name'];
    phone = json['phone'];
    profession = json['profession'];
    iV = json['__v'];
    if (json['events'] != null) {
      events = new List<Events>();
      json['events'].forEach((v) {
        events.add(new Events.fromJson(v));
      });
    }
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['role'] = this.role;
    data['city'] = this.city;
    data['resume'] = this.resume;
    data['photo'] = this.photo;
    data['countDays'] = this.countDays;
    data['online'] = this.online;
    data['profileComplete'] = this.profileComplete;
    data['createdAt'] = this.createdAt;
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['phone'] = this.phone;
    data['profession'] = this.profession;
    data['license'] = this.license;
    data['__v'] = this.iV;
    if (this.events != null) {
      data['events'] = this.events.map((v) => v.toJson()).toList();
    }
    data['id'] = this.id;
    return data;
  }
}

class Events {
  String sId;
  String date;
  String details;
  String user;
  int iV;

  Events({this.sId, this.date, this.details, this.user, this.iV});

  Events.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    date = json['date'];
    details = json['details'];
    user = json['user'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['date'] = this.date;
    data['details'] = this.details;
    data['user'] = this.user;
    data['__v'] = this.iV;
    return data;
  }
}
`

NetWork service
`
class NetworkService{
TokenService _tokenService = TokenService();

 Future<UserModel> getAlluser() async {
    String token = await  _tokenService.getToken();
    print("Got request from future builder");
    final response = await http.get(
      kUrlAdminGetAll,
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Authorization': 'Bearer $token'
      },
    );
    if (response.statusCode == 200) {
      var body = response.body;
      print(body);
      final UserModel data = UserModel.fromJson(json.decode(body));
      return data;
    }
    return null;
  }
}

`
TokenService Class
To run this code you need to add sharedpref along with shared pref web 

`
class TokenService {
  SharedPreferences prefs;

 

  Future<String> getToken() async {
    prefs = await SharedPreferences.getInstance();
    String token = prefs.getString('token');
    if (token == null) {
      print("no token found");
      return null;
    }
    return token;
  }



  void setToken(String token) async {
    prefs = await SharedPreferences.getInstance();
    bool isSaved = await prefs.setString("token", token);
    print("Token Saved to browser: $isSaved");
  }

  Future<void> deleteKey() async {
    prefs = await SharedPreferences.getInstance();
    await prefs.remove("token");
    //await _storage.delete(key: "token");
    print('Key deleted');
  }
}
`

**Comment by darshankawar** [comment]
@ujjwalbe 
Still it doesn't look like complete code. I am getting compile errors on `ItemCard` , `UpdateUserMainPage`, `kUrlAdminGetAll`.

Please note and keep in mind that, whenever you are providing a code sample, make sure to provide all corresponding code. There's no way for us to know what does custom code / widget like `ItemCard` contains or what does `kUrlAdminGetAll` mean.
I'd suggest you create a github repo, put all your code in it and share the repo link that we can clone which should run directly.
Thanks.

Also, try to search over internet for the error you are getting `!navigator._debugLocked is not true` and possible solutions. It's related to how you are trying to `push` and `pop`.

**Comment by ujjwalbe** [comment]
I'm closing this issue it is solved, i was routing from the future builder before it completed building the widgets, though i did not used beta version. I ported the code to flutter stable version and was same issue so i find out this. Thanks for all your support.
