### ISSUE TITLE
Error Message build apk relesase with google_maps_flutter-1.0.2

### ISSUE THREAD

**Issue by joharputr** [flutter/flutter#67889]
![image](https://user-images.githubusercontent.com/32647004/95703265-ef941400-0c78-11eb-9670-8d32e1be9037.png)

this is occur when i run flutter build apk. but apk work properly

**Comment by hamdikahloun** [comment]
Hi @joharputr 
There's similar [open](https://github.com/flutter/flutter/issues/65970) issue in which you can follow-up for updates and any questions.
Thank you

**Comment by TahaTesser** [comment]
Hi @joharputr 
An open issue addressing the case you described.  https://github.com/flutter/plugins/pull/3117
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
