### ISSUE TITLE
BottomNavigationBar. selectedLabelStyle is not working

### ISSUE THREAD

**Issue by Lanch92** [flutter/flutter#67897]
only set selectedLabelStyle, the color not work. have to set selectedItemColor

**Comment by Lanch92** [comment]
> only set selectedLabelStyle, the color not work. have to set selectedItemColor

BottomNavigationBar(
      backgroundColor: Colors.white,
      selectedItemColor: MAIN_COLOR,
      unselectedLabelStyle: TextStyle(
          color: Color(0xFFB6B6B6), fontWeight: FontWeight.w500, fontSize: 10),
      selectedLabelStyle: TextStyle(
          color: MAIN_COLOR, fontWeight: FontWeight.w500, fontSize: 10),
      items: _items
          .map((e) => BottomNavigationBarItem(
                icon: e.icon,
                activeIcon: e.activeIcon,
                label: e.title,
              ))
          .toList(),
      type: BottomNavigationBarType.fixed,
      currentIndex: _currentIndex,
      onTap: _onTabBarTap,
    )

**Comment by pedromassangocode** [comment]
Hi @Lanch92 
Can you elaborate more on what are you trying to change and what is not working?
Also please provide your `flutter doctor -v` and a minimal reproducible code sample that I can just copy/paste to reproduce the issue.
Thank you

**Comment by RCSandberg** [comment]
Not sure if @Launch92 means the same error. 
But I experience that using the color property of TextStyle() on selectedLabelStyle and unselectedLabelStyle doesn't work.

       bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'First',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.exit_to_app),
            label: 'Second',
          ),
        ],
        selectedLabelStyle: TextStyle(
          color: Colors.red,
          fontSize: 22.0,
        ),
        unselectedLabelStyle: TextStyle(
          color: Colors.blue,
          fontSize: 32.0,
        ),
        //selectedItemColor: Colors.green,
      )
With the snippet above, the first item is not red but default blue, according to attached picture.
![Capture](https://user-images.githubusercontent.com/18184100/96766100-deff3e80-13da-11eb-8bf4-6f996c75be06.PNG)

Uncommenting the ```//selectedItemColor: Colors.green,``` will change the color of the item to green.

```
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.14393], locale sv-SE)
    • Flutter version 1.22.1 at C:\dev\flutter\flutter
    • Framework revision f30b7f4db9 (13 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\es012194\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```

**Comment by Lanch92** [comment]
> Not sure if @Launch92 means the same error.
> But I experience that using the color property of TextStyle() on selectedLabelStyle and unselectedLabelStyle doesn't work.
> 
> ```
>    bottomNavigationBar: BottomNavigationBar(
>     items: const <BottomNavigationBarItem>[
>       BottomNavigationBarItem(
>         icon: Icon(Icons.home),
>         label: 'First',
>       ),
>       BottomNavigationBarItem(
>         icon: Icon(Icons.exit_to_app),
>         label: 'Second',
>       ),
>     ],
>     selectedLabelStyle: TextStyle(
>       color: Colors.red,
>       fontSize: 22.0,
>     ),
>     unselectedLabelStyle: TextStyle(
>       color: Colors.green,
>       fontSize: 32.0,
>     ),
>     //selectedItemColor: Colors.green,
>   )
> ```
> 
> With the snippet above, the first item is not red but default blue, according to attached picture.
> ![Capture](https://user-images.githubusercontent.com/18184100/96766100-deff3e80-13da-11eb-8bf4-6f996c75be06.PNG)
> 
> Uncommenting the `//selectedItemColor: Colors.green,` will change the color of the item to green.
> 
> ```
> [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.14393], locale sv-SE)
>     • Flutter version 1.22.1 at C:\dev\flutter\flutter
>     • Framework revision f30b7f4db9 (13 days ago), 2020-10-08 10:06:30 -0700
>     • Engine revision 75bef9f6c8
>     • Dart version 2.10.1
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\es012194\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 49.0.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code, 64-bit edition (version 1.50.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.15.1
> 
> [√] Connected device (1 available)
>     • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
> 
> • No issues found!
> ```

YES

**Comment by Lanch92** [comment]
> Hi @Lanch92
> Can you elaborate more on what are you trying to change and what is not working?
> Also please provide your `flutter doctor -v` and a minimal reproducible code sample that I can just copy/paste to reproduce the issue.
> Thank you

reference @RCSandberg

**Comment by Lanch92** [comment]
> > Hi @Lanch92
> > Can you elaborate more on what are you trying to change and what is not working?
> > Also please provide your `flutter doctor -v` and a minimal reproducible code sample that I can just copy/paste to reproduce the issue.
> > Thank you
> 
> reference @RCSandberg

when I using the color property of TextStyle() on selectedLabelStyle and unselectedLabelStyle，the TextStyle's color property is not working

**Comment by Lanch92** [comment]
> > Not sure if @Launch92 means the same error.
> > But I experience that using the color property of TextStyle() on selectedLabelStyle and unselectedLabelStyle doesn't work.
> > ```
> >    bottomNavigationBar: BottomNavigationBar(
> >     items: const <BottomNavigationBarItem>[
> >       BottomNavigationBarItem(
> >         icon: Icon(Icons.home),
> >         label: 'First',
> >       ),
> >       BottomNavigationBarItem(
> >         icon: Icon(Icons.exit_to_app),
> >         label: 'Second',
> >       ),
> >     ],
> >     selectedLabelStyle: TextStyle(
> >       color: Colors.red,
> >       fontSize: 22.0,
> >     ),
> >     unselectedLabelStyle: TextStyle(
> >       color: Colors.green,
> >       fontSize: 32.0,
> >     ),
> >     //selectedItemColor: Colors.green,
> >   )
> > ```
> > 
> > 
> > With the snippet above, the first item is not red but default blue, according to attached picture.
> > ![Capture](https://user-images.githubusercontent.com/18184100/96766100-deff3e80-13da-11eb-8bf4-6f996c75be06.PNG)
> > Uncommenting the `//selectedItemColor: Colors.green,` will change the color of the item to green.
> > ```
> > [√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.14393], locale sv-SE)
> >     • Flutter version 1.22.1 at C:\dev\flutter\flutter
> >     • Framework revision f30b7f4db9 (13 days ago), 2020-10-08 10:06:30 -0700
> >     • Engine revision 75bef9f6c8
> >     • Dart version 2.10.1
> > 
> >  
> > [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> >     • Android SDK at C:\Users\es012194\AppData\Local\Android\sdk
> >     • Platform android-30, build-tools 30.0.2
> >     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> >     • All Android licenses accepted.
> > 
> > [√] Android Studio (version 4.0)
> >     • Android Studio at C:\Program Files\Android\Android Studio
> >     • Flutter plugin version 49.0.2
> >     • Dart plugin version 193.7547
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> > 
> > [√] VS Code, 64-bit edition (version 1.50.1)
> >     • VS Code at C:\Program Files\Microsoft VS Code
> >     • Flutter extension version 3.15.1
> > 
> > [√] Connected device (1 available)
> >     • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
> > 
> > • No issues found!
> > ```
> 
> YES

only color property not work, other property is working

**Comment by pedromassangocode** [comment]
Hi @Lanch92 
I see there's an open issue (https://github.com/flutter/flutter/issues/66738) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
