### ISSUE TITLE
Future keyword excessive CPU use

### ISSUE THREAD

**Issue by SazinSamin** [flutter/flutter#67893]
Whenever i type  "Future<List<User>>" ,  my PC clock speed go to its maximum frequency and temperature go to 70-80 C and also it stops to give any kind of suggestion. I find this problem to another project few month ago.

I OS is Ubuntu 20.04 and i type codes in Android Studio.

**Comment by sidrao2006** [comment]
Hello @SazinSamin ,
Could you please post the output of `flutter doctor -v` and provide a minimal reproducible code sample
Thank you!

**Comment by pedromassangocode** [comment]
Hi @SazinSamin 
Can you please provide the information requested above?

**Comment by SazinSamin** [comment]
I am extremely sorry for delay.

Output of flutter doctor -v : 

samin@samin-VivoBook-S15-X530UA:~/AndroidStudioProjects/testcase$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0 at /home/samin/snap/flutter/common/flutter
    • Framework revision d408d302e2 (2 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/samin/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.





----------------------------------------------------------------------------------------------------------------------------------------
After new update of Android Studio flutter doctor show Android Studio not found but in my machine it is already installed.

**Comment by SazinSamin** [comment]
The code reproducible code sample : 



    Future<List<Note>> getNoteList()async{
    
       var noteMapList = await getNoteList();
       int count = noteMapList.length;
    
       List<Note> noteList = List<Note>();
       for(int i=0; i<count; i++){
         noteList.add(Note.fromMapObject(noteMapList[i]));
       }
       return noteList;
     }

**Comment by pedromassangocode** [comment]
Hi @SazinSamin 
Can you provide a complete code sample?
The code you shared is not complete as it does not shows how are you using this method and how the Note class is declared.

**Comment by SazinSamin** [comment]
Just write this line the problem happen

    Future<Map<List>>

**Comment by pedromassangocode** [comment]
Hi @SazinSamin 
I asked you to provide a minimal complete reproducible code sample. Please provide it for me to reproduce the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
