### ISSUE TITLE
Provide an API for the back button handling

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#679]
When running an app in Mojo shell, the back button is handled by the application.  The relevant code snippet is https://github.com/vanadium/syncslides/blob/master/dart/lib/main.dart#L41  We need to implement the same functionality in the new Navigator API, but Navigator.pop() requires a context instance which we may not have when the back button callback is invoked.

**Comment by abarth** [comment]
You should just call ui.window.onPopRoute.  That will send the event to the appropriate listeners.

**Comment by mishadynin** [comment]
With @abarth's help, I implemented the back button behavior without any API changes on the Flutter side.  Closing the bug.
