### ISSUE TITLE
If more than 3 tabs in the BottomNavigationBar, the tabs turn white.

### ISSUE THREAD

**Issue by karamage** [flutter/flutter#67903]
## Overview

I always appreciate the development of Flutter! 

Is it a known issue that having more than 3 tabs in the BottomNavigationBar causes the tabs to turn white?

I am trying to display 4 items in a tab with the following code.

I don't get an error, but the icons are no longer visible.
I can see the icons when I tap on them.

If the tab has 3 items, you can view them.

## Environment

———————————————
Mac/Android Studio 4.0
Xcode 11.3.1
Flutter 1.22.1 • channel stable 
Framework • revision f30b7f4db9 (4 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1
————————————————

## Code

```Dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'BottomNavigationBar'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(),
      bottomNavigationBar: BottomNavigationBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('1')),
          BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('2')),
          BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('3')),
          BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('4')),
        ],
      ),
    );
  }
}
```

## ScreenShot
<img width="535" alt="スクリーンショット 2020-10-12 16 35 08" src="https://user-images.githubusercontent.com/330715/95720259-f8520d80-0cab-11eb-89f8-9f28cb144785.png">

## Workaround

A workaround for now.
If you specify "type: BottomNavigationBarType.fixed", the tab will be displayed. 

Every Thanks.

**Comment by xu-baolin** [comment]
This is designed, see also: https://github.com/flutter/flutter/blob/f30b7f4db9/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L52

**Comment by karamage** [comment]
Thanks for your reply.

I understand.

I specified a selectedItemColor and an unselectedItemColor and the tabs came up!

I'm grateful.

**Comment by errorsolve** [comment]
[[Solved] Flutter BottomNavigationBar not working with more than three items](https://fluttercorner.com/flutter-bottomnavigationbar-not-working-with-more-than-three-items/)
