### ISSUE TITLE
Json data not loaded using compute() when running test_driver.

### ISSUE THREAD

**Issue by SuryaChinnadurai** [flutter/flutter#67902]
I am using "compute" method to read the JSON data and do some process in my application. It works when running the application normally. However, it is not working while launching the application through integration testing. 

To cross check, I have ensured the same with the code snippet in the below link.
https://flutter.dev/docs/cookbook/networking/background-parsing

1.app.dart code snippet:

```
import 'package:flutter_driver/driver_extension.dart';
import 'package:sample/main.dart' as app;

void main() {
  enableFlutterDriverExtension();
  
  app.main();
}
```

2.app_test.dart code snippet:

```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Loading json data App', () {
    FlutterDriver driver;

    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('simple testing', () async {
      
    });

  });
}
```

flutter doctor -v:
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
• Flutter version 1.22.0 at C:\src\flutter
• Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
• Engine revision 5babba6c4d
• Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\SuryaChinnadurai\AppData\Local\Android\sdk
• Platform android-29, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Users\SuryaChinnadurai\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 44.0.2
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.49.2)
• VS Code at C:\Program Files\Microsoft VS Code
• Flutter extension version 3.15.0

[√] Connected device (3 available)
• AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
• Web Server (web) • web-server • web-javascript • Flutter Tools
• Chrome (web) • chrome • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

**Comment by darshankawar** [comment]
@SuryaChinnadurai 
There was similar [issue](https://github.com/flutter/flutter/issues/24703) that was fixed and [merged](https://github.com/flutter/flutter/pull/65703) in Master. 

Can you try to switch to latest Master and try again to check if it works ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by SujathaBabu** [comment]
We are unable to run the automation using master branch, we are facing an issue and it has logged. Please find the issue report link - https://github.com/flutter/flutter/issues/70083
