### ISSUE TITLE
url_launcher launch native app directly in android

### ISSUE THREAD

**Issue by Sujal1** [flutter/flutter#67906]
I am using url_launcher to launch Zoom from my app. The code snippet is as below.

 if (await canLaunch(url)) {
      final bool launchSucceded = await launch(
        url,
        forceSafariVC: false,
        universalLinksOnly: true,
      );
      print(launchSucceded);
 }

In case of iOS, if there is Zoom app installed in the device, then Zoom app is launched with the above settings. However, in case of android, I get app options to open the url, when the launch method is fired. Screenshot is shown below.

<img width="309" alt="Screen Shot 2020-10-12 at 14 03 30" src="https://user-images.githubusercontent.com/6914866/95723807-4871a580-0c95-11eb-976e-6858a0467155.png">

And, the launch method returns true when the options are shown. I would like behaviour similar to ios i.e. if there is Zoom app installed in the android device, launch it, other return false. (or at least know that the user has selected one of the apps to launch the url) Is this achievable in the current version of the library?

**Comment by darshankawar** [comment]
@Sujal1 
In case of iOS, does it return `false` if it couldn't find the app ? or returns `true` ?

**Comment by Sujal1** [comment]
@darshankawar with the above code, it returns **false** in case the app is not found.

**Comment by stuartmorgan** [comment]
`url_launcher` just hands URLs off to the OS for launching; the difference you see between iOS and Android is a fundamental difference in how the two OSes handle opening a URL.

If you want more detailed control over what happens on Android, a plugin for managing Android Intents may let you accomplish what you want.
