### ISSUE TITLE
Numberformat with Locale doesn´t work properly with IOS

### ISSUE THREAD

**Issue by Friedlman** [flutter/flutter#67904]
On android parsing and formatting works fine but with IOS I have problems if the localeCodes are for example 'en_IT'.
I added the languages to the Info.plist

## Steps to Reproduce
```
import 'dart:ui' as ui;

  static String getStringFromLocaleNumber(double number) {
    try {
      return NumberFormat.currency(
        symbol: '',
        locale: ui.window.locale,
      ).format(number).trim();
    } catch (ex) {
      print('Exception' + ex);
      return '';
    }
  }

  static double getNumberFromLocaleString(String value, BuildContext context) {
      var number = NumberFormat.currency(symbol: '', locale: ui.window.locale)
          .parse(value);
      return number;
  }

```

**Expected results:** 

with language English and Country IT  ('en_IT'): 
If I use the method below getStringFromLocaleNumber with the double 2.15 i need "2,15" as string (DOESNT WORK RIGHT).  

with language and Country ('en_US')
works properly

**Actual results:** 

with language English and Country IT  ('en_IT'): 
If I use the method below getStringFromLocaleNumber with the double 2.15 i get back "2.15" as string.  But the Textformfield (KeyboardType: TextInputType.numberWithOptions(decimal: true)) has the decimal seperator ',' on the keyboard.

with language and Country ('it_IT' or 'de_DE')
It works properly: I get "2,15" form the double 2.15 and the IOS keyboard shows the ',' decimal seperator.

with language and Country ('en_US')
It works properly too: "2.15" string from double 2.15 and IOS keyboard shows the '.'

If more information is needed I am happy to provide it.

Greetings Lukas

**Comment by TahaTesser** [comment]
Hi @Friedlman 
Please follow https://flutter.dev/docs/development/accessibility-and-localization/internationalization
Can you please provide your `flutter doctor -v`  a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
