### ISSUE TITLE
Date Picker jumps back to initialDatePickerMode after day selection

### ISSUE THREAD

**Issue by the-ginger-geek** [flutter/flutter#67909]
### Steps to reproduce
1. Show a date picker with the `initialDatePickerMode` set to `DatePickerMode.year`
2. Make a year selection. 
3. Make a month and day selection.

**Expected results**
The picker should remain on the day selection, when selected, until the `OK` or `CANCEL` button is pressed

**Actual results**
After selecting the day the picker jumps back to year selection.

### Code
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Click the button to open calendar',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => showDatePicker(
          initialDatePickerMode: DatePickerMode.year,
          context: context,
          firstDate: DateTime(1970),
          lastDate: DateTime(2020),
          initialDate: DateTime(2010),
        ),
        tooltip: 'Calendar',
        child: Icon(Icons.calendar_today),
      ),
    );
  }
}
```

### Below image illustrates result after selection
![Screenshot_1602494235](https://user-images.githubusercontent.com/2182638/95728994-7eeef680-0c7c-11eb-9121-7ee22dd1473c.png)

## Flutter Doctor
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/mukuru/development/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mukuru/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API
      29) (emulator)

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

[67909.mp4.zip](https://github.com/flutter/flutter/files/5365532/67909.mp4.zip)

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by alexmarkley** [comment]
Two dumb questions:
1. If https://github.com/flutter/flutter/pull/67926 fixes this issue (and it seems like that PR is intended to fix this issue) should we close this issue?
2. When should we expect this issue to be resolved in Flutter stable channel?

Thanks!

**Comment by alexmarkley** [comment]
When can we expect this fix to make its way into Flutter stable? Looks like 1.22.6 is still affected by this problem.

**Comment by darrenaustin** [comment]
Indeed this should be closed with #67926.

Not sure when this will be hitting stable, but from the tags it has made it to [1.26.0-17.3.pre](https://github.com/flutter/flutter/releases/tag/1.26.0-17.3.pre), which is on the beta channel, so it is working its way through the release process.

**Comment by alexmarkley** [comment]
@darrenaustin thanks for your reply! Are you aware of any public documentation on how Flutter's release management works? Eg. policies on cherry picking fixes for a stable release and so forth?

**Comment by darrenaustin** [comment]
> @darrenaustin thanks for your reply! Are you aware of any public documentation on how Flutter's release management works? Eg. policies on cherry picking fixes for a stable release and so forth?

The main ones that I am aware of are:

https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

Which includes a link to the cherry pick process here:

https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

Hope this helps.
