### ISSUE TITLE
On Android phones, the bottom of the text in the long-press prompt box is cropped a little

### ISSUE THREAD

**Issue by binqiiyuenan** [flutter/flutter#67910]
As is shown in：

![WechatIMG4](https://user-images.githubusercontent.com/19378921/95730568-022a3f80-0cb1-11eb-8c5c-4f8e6eb96006.jpeg)

**Comment by sidrao2006** [comment]
Hello @152dyn ,
Could you please post the output of `flutter doctor -v` and a minimal reproducible code sample
Thank you!

**Comment by darshankawar** [comment]
@152dyn 
Please provide above requested details that shows the issue.
Thanks.

**Comment by 152dyn** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

• No issues found!

**Comment by 152dyn** [comment]
This scenario occurs in TextField, when long pressing the prompt box

The prompt box is not my custom

In Android, this is going to happen to all textfields in my app

**Comment by 152dyn** [comment]
@darshankawar @sidrao2006 

I just found out that only when it's set to Chinese will it be cropped

This is what I set up for the MaterialApp：
```dart
         MaterialApp(
              title: 'Demo',
              theme: themeConfig,
              navigatorObservers: [
                routeObserver, 
              ],
              onGenerateRoute: widget._router.getRoute,
              localizationsDelegates: [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
                DefaultCupertinoLocalizations.delegate
              ],
              supportedLocales: [
                const Locale('zh', 'CH'),
              ],
              home: SplashPage()
          )
```

**Comment by reidbaker** [comment]
@binqiiyuenan the glyph's cropped or is the box cropped?
