### ISSUE TITLE
Flutter shared_preferences not persistent?

### ISSUE THREAD

**Issue by OrkhanS** [flutter/flutter#67925]
## Shared Preferences not working
I have been using shared_preferences in flutter, was working fine until now. Suddenly it stopped working, both in iOS and Android. I debugged it step by step and it stores data to pref and while app is on, data still persists, but after hot restart _preferencecache always is empty. How can I solve this? (version is 0.5.12)

**What I did** 

```
final prefs = await SharedPreferences.getInstance();
 final userData = json.encode(
  {
    'user_id': userID,
  },
 );
prefs.setString('userData', userData);
```

**Actual results: when user restarts again**  
```
final prefs = await SharedPreferences.getInstance();
if (!prefs.containsKey('userData')) {
// print("no user data in shared preference");
  return false;
}

```

But the abpve function returns false, that's the issue, I checked the previous version of shared_preferences as well, but no solution.

**Comment by lablnet** [comment]
> ## Shared Preferences not working
> I have been using shared_preferences in flutter, was working fine until now. Suddenly it stopped working, both in iOS and Android. I debugged it step by step and it stores data to pref and while app is on, data still persists, but after hot restart _preferencecache always is empty. How can I solve this? (version is 0.5.12)
> 
> **What I did**
> 
> ```
> final prefs = await SharedPreferences.getInstance();
>  final userData = json.encode(
>   {
>     'user_id': userID,
>   },
>  );
> prefs.setString('userData', userData);
> ```
> 
> **Actual results: when user restarts again**
> 
> ```
> final prefs = await SharedPreferences.getInstance();
> if (!prefs.containsKey('userData')) {
> // print("no user data in shared preference");
>   return false;
> }
> ```
> 
> But the abpve function returns false, that's the issue, I checked the previous version of shared_preferences as well, but no solution.

I am using latest version of shared preference it works I think you should clear your build and run app with higher version like that.

`flutter clean`
`flutter run -v`

Thanks 😊

**Comment by darshankawar** [comment]
@OrkhanS 
I tried the official `shared_preferences` plugin [example](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences/example) and verified by hot-restarting the app and it showed the persistent data properly.

Can you try the same example and see if you still see the issue ?
Thanks.
