### ISSUE TITLE
Gray square in place of widget - only if app is instaled from Google Play Store 

### ISSUE THREAD

**Issue by lukaszSieczkowski** [flutter/flutter#67920]
**Problem Description:**
[Gray square in place of widget - only if app is instaled from Google Play Store #67868](https://github.com/flutter/flutter/issues/67868)

**Problem cause:**
After removing in Text child widget **textAlign: TextAlign.justify,** works fine.
In this case **Text** Widget is a problem.

**Comment by TahaTesser** [comment]
Hi @lukaszSieczkowski 
Looks like you have filed this issue  already 
Closing as duplicate of https://github.com/flutter/flutter/issues/67868

**Comment by lukaszSieczkowski** [comment]
Yes but is closed without understanding a problem
