### ISSUE TITLE
[Material] AppBar background color should check for ColorScheme.primary

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#67921]
Currently, the AppBar checks for ThemeData.primary, but does not check to use ColorScheme.primary. When the backgroundColor is resolved, it should check to use ColorScheme.primary if its not null.

**Comment by pedromassangocode** [comment]
Reproducible code sample and `flutter doctor -v` would help anyone who wants to fix this issue!

**Comment by HansMuller** [comment]
The PR that "fixed" this issue, #69251, was reverted: https://github.com/flutter/flutter/pull/70212
