### ISSUE TITLE
iOS platform view crash with forwarding gesture recognizer.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#67933]
Originally reported in https://github.com/flutter/flutter/issues/61991#issuecomment-706835198

> I encountered a new crash, the following is the stack information. @jason-simmons @jmagman @gspencergoog
> 
> ```
> Thread 0 Crashed:
> 0   libobjc.A.dylib                 objc_msgSend + 16
> 1   Flutter                         -[ForwardingGestureRecognizer touchesBegan:withEvent:] (FlutterPlatformViews.mm:642)
> 2   UIKitCore                       -[UIGestureRecognizer _touchesBegan:withEvent:] + 252
> 3   UIKitCore                       -[UITouchesEvent _sendEventToGestureRecognizer:] + 288
> 4   UIKitCore                       __47-[UIGestureEnvironment _updateForEvent:window:]_block_invoke + 68
> 5   UIKitCore                       -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 220
> 6   UIKitCore                       -[UIGestureEnvironment _updateForEvent:window:] + 204
> 7   UIKitCore                       -[UIWindow sendEvent:] + 3112
> 8   UIKitCore                       -[UIApplication sendEvent:] + 340
> 9   UIKitCore                       __dispatchPreprocessedEventFromEventQueue + 1768
> 10  UIKitCore                       __handleEventQueueInternal + 4828
> 11  UIKitCore                       __handleHIDEventFetcherDrain + 152
> 12  CoreFoundation                  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
> 13  CoreFoundation                  __CFRunLoopDoSource0 + 88
> 14  CoreFoundation                  __CFRunLoopDoSources0 + 176
> 15  CoreFoundation                  __CFRunLoopRun + 1004
> 16  CoreFoundation                  CFRunLoopRunSpecific + 436
> 17  GraphicsServices                GSEventRunModal + 104
> 18  UIKitCore                       UIApplicationMain + 212
> ```
> 
> flutter doctor
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel unknown, v1.9.1+hotfix.107, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> [!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
>    ! CocoaPods out of date (1.6.0 is recommended).
>        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>        Without CocoaPods, plugins will not work on iOS or macOS.
> ```

**Comment by cyanglaz** [comment]
@seeuli Do you mind include a list of all the plugins that you use in the app. This crash is caused by platform views which means some plugins using platform views caused it. It would be helpful if we know which one(s).

**Comment by seeuli** [comment]
> @seeuli Do you mind include a list of all the plugins that you use in the app. This crash is caused by platform views which means some plugins using platform views caused it. It would be helpful if we know which one(s).

@cyanglaz  There are no other plugin references except for the creation of PlatformView, and there are no gesture-related operations in the plugin.

plugins list
> map_plugin
> navi_plugin

**Comment by pedromassangocode** [comment]
Hi @seeuli 
Looks like you are using an old version of Flutter.
Can you please upgrade to the latest stable channel and see if the issue reproduces?
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by seeuli** [comment]
> Hi @seeuli
> Looks like you are using an old version of Flutter.
> Can you please upgrade to the latest stable channel and see if the issue reproduces?
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`

@pedromassangocode  I'm afraid not.
There is no stable recurrence steps for this issue. And there is a lot of work to be done to directly upgrade to the latest stable version.

**Comment by pedromassangocode** [comment]
I'm not sure if we can validate an issue reported from an old version of the Framework.
Please share any additional information if you face this issue on with the latest versions of Flutter.

Will leave this up to @cyanglaz to decide if this should remain opened or should be close since it is a report from a old Flutter version and may not be valid on latest versions of Flutter.

**Comment by cyanglaz** [comment]
@pedromassangocode Thanks for pointing it out. I didn't realize that this issue was observed on a version older than stable.

@seeuli I'm going to close this issue for now. If you could repro this issue on the latest stable, please share more details and cc me. I will reopen the issue and investigate. :) Thank you in advance for understanding.
