### ISSUE TITLE
Collect memory/cpu/process info after LUCI mac task executions

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#67934]
Both engine and framework are hitting `retcode: -9` error.

Engine: [example](https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/5177)
```
recipe infra failure: Infra Failure: Step('Ensure checkout cache') (retcode: -9)
```
Framework:[example](https://ci.chromium.org/p/flutter/builders/try/Mac%20SDK%20Drone/5410?)
```
recipe infra failure: Infra Failure: Step('Checkout flutter/flutter.git fetch') (retcode: -9)
```

More information about memory/cpu usage/process list is needed to identify potential memory of process leaks causing the infra failures.

Related issues: https://github.com/flutter/flutter/issues/67181, https://github.com/flutter/flutter/issues/66133, 

/cc @godofredoc @zanderso

**Comment by keyonghan** [comment]
Latest failed build: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7284
-9 error happened on the `OS info` step...
Will try moving that step earlier.

**Comment by godofredoc** [comment]
@keyonghan  Can we close this bug?
