### ISSUE TITLE
codesigning bot hostname not found

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#67937]
Our codesigning bot is not responding to its hostname.

cc @keyonghan

**Comment by keyonghan** [comment]
Filed http://t/200057064. waiting for updates.

**Comment by keyonghan** [comment]
techstop confirmed everything is okay from network side: now it is pingable, but cannot ssh.
Manual intervention seems needed to bring it back.

**Comment by christopherfujino** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/70779
