### ISSUE TITLE
Flaky Fuchsia failures cause frequent tree closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#67942]
An example of such failures is https://chromium-swarm.appspot.com/task?id=4f32a561503b9b10. Currently, a substantial number of recent failures on Fuchsia are due to this error. 
![Screen Shot 2020-10-12 at 11 26 34 AM](https://user-images.githubusercontent.com/44085/95778852-cc1f9800-0c7d-11eb-9d1c-035a8133b6e4.png)
The error looks like a machine is unreachable
```
ssh: connect to host fd5d:df04:d8c7:0:73b7:3bb5:6468:26a7 port 22: Network is unreachable
```

**Comment by chinmaygarde** [comment]
cc @chaselatta

**Comment by chaselatta** [comment]
There was a recent netstack change which was causing connection failures. The change is being reverted so this should be resolved shortly.

**Comment by chinmaygarde** [comment]
Excellent. Can you please cross-reference the patchset so someone can followup on it to decide when we can close this issue?

**Comment by chaselatta** [comment]
The revert is https://fuchsia-review.googlesource.com/c/fuchsia/+/437874

**Comment by chinmaygarde** [comment]
The tree seems to be closed for that revert to land.

@zanderso: We may need to attempt retries manually or disable these checks to unblock ourselves in the meantime. Or just wait it out :)

**Comment by chinmaygarde** [comment]
Per the internal thread. Change is being force submitted.

**Comment by chinmaygarde** [comment]
The patch has landed but not yet rolled into the engine because the engine tree is red (because the issue the patch purportedly fixes).

**Comment by chinmaygarde** [comment]
The patch [was rolled into the engine](https://chromium.googlesource.com/external/github.com/flutter/engine/+/6cdb2f69a4ef8402cf37e9e4279fba00942f9fe3) and I don't see any new failures after the roll. I'm going to call this one a success.

**Comment by zanderso** [comment]
This reoccurred here https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/5815, so I'm reopening this.

**Comment by zanderso** [comment]
When I retriggered the build for the most recent Fuchsia SDK roll, it failed again the same way, so I am going to try reverting the roll: https://github.com/flutter/engine/pull/21823.

**Comment by zanderso** [comment]
I have reverted the Fuchsia SDK roll to back before the flake started. If/When that clears things up, I'll downgrade this from P0.

**Comment by kf6gpe** [comment]
@chaselatta told me via other channels that:

"I got a conversation started with the netstack team and some of the flutter folks. We also have created a bug (fxb/61962) which is tracking this internally with the connectivity team and it's been added to the chaselist."

**Comment by godofredoc** [comment]
Mitigation for this problem:

* https://github.com/flutter/packages/pull/227
* https://github.com/flutter/infra/pull/243
* https://github.com/flutter/engine/pull/21828

**Comment by chinmaygarde** [comment]
@zanderso says this should be fixed upstream by the Fuchsia netstack team. He will followup on the roll into the engine.

**Comment by chinmaygarde** [comment]
From triage of presubmit flakes reported by users, this one still seems to be an ongoing issue with the following report:
* https://chromium-swarm.appspot.com/task?id=4f391f8860d55610

**Comment by zanderso** [comment]
@chinmaygarde that presubmit run was before the Fuchsia SDK roll that included the fix here https://github.com/flutter/engine/commit/ea2aea1c610242ffdf57d0b813f5281ff17fdd16. Since then I haven't seen any flakes, so I will close this.
