### ISSUE TITLE
Allow for more customizable Button Text Color Theme

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#67948]
Currently AFAIK there isn't a simple way to customize a theme for a button's text color.

I can create a `buttonTheme` such as:

```dart
buttonTheme: ButtonTheme.of(context).copyWith(
  buttonColor: primaryColor
  disabledColor: disabledColor,
  textTheme: ButtonTextTheme.accent,
  colorScheme: Theme.of(context).colorScheme.copyWith(
        primary: primaryColor,
        secondary: Theme.of(context).colorScheme.onPrimary,
      ),
  shape: StadiumBorder(),
)
```

But this only works if I set `ButtonTextTheme.accent`, any other options and the buttons will just ignore the secondary color for their texts.

**Comment by HansMuller** [comment]
ButtonTheme, FlatButton, RaisedButton, OutlineButton, (MaterialButton) will be deprecated soon. The new button classes and their themes - please see flutter.dev/go/material-button-migration-guide - allow one to customize the text (foreground) color of buttons per button state or for all states.

**Comment by feinstein** [comment]
@HansMuller will I be able to also customize the button text to be always capitalized (when the language can handle capitalization)?

**Comment by HansMuller** [comment]
I'm afraid that the new buttons and their themes do not include support for automatically applying a string transformation, like capitalization, to descendant Text strings.

**Comment by feinstein** [comment]
Do you think this is useful? Should I create a new issue to track this?

**Comment by HansMuller** [comment]
If you think it would be useful then create an issue, if only to discover if other developers would also find it useful. Defining text transformations like this would probably complicate localization.

**Comment by feinstein** [comment]
Ok, I will, IIRC there's a Material Design recommendation on this, at least there was on the first version, so that's why have it in mind.

**Comment by feinstein** [comment]
Done: #68236.
