### ISSUE TITLE
Flutter Image Picker crashes when using two different sessions/instances from two Views IOS

### ISSUE THREAD

**Issue by flightwonder** [flutter/flutter#67955]
I'm trying to use multiple sessions of image pickers(NOT A MULTI IMAGE PICKER), one for images to post and one for profile image. When I use the image picker to pick an image to post it works fine. But when I go to the profile page to select a profile picture, it crashes.

This is the function being called from view 1.

   ```
 Future<File> selectVisualImage() async {
        File _james;
        final _picker = ImagePicker();
        final _image = await _picker.getImage(source: ImageSource.gallery);
        if (_image != null) {
          final File file = File(_image.path);
          _james = await _cropVisualImage(file);
          return _james;
        }
        return null;
      }
```

This is function being called from view 2.

   ```
 Future<File> selectProfileImage() async {
        File _kames;
        final _picker = ImagePicker();
        final _image = await _picker.getImage(source: ImageSource.gallery);
        if (_image != null) {
          final File file = File(_image.path);
          _kames = await _cropDIFVisualImage(file);
          return _kames;
        }
        return null;
      }
```

SelectVisualImage works properly but when I go to view 2 and use selectProfileImage. it crashes immediately.This is the line that crashes.

`    var _image = await ImagePicker().getImage(source: ImageSource.gallery);`

I just want to pick regular images to post and one profile image without it crashing. Any ideas?

**Comment by qarniha** [comment]
All

**Comment by qarniha** [comment]
Q we

**Comment by darshankawar** [comment]
@flightwonder 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
