### ISSUE TITLE
Adding a Badge to Circle Avatar using Stack to be on top returns error

### ISSUE THREAD

**Issue by vashisth00** [flutter/flutter#67958]
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
Rect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 31: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    CircleAvatar 
```
lib/…/chat/chat_list_item.dart:35
When the exception was thrown, this was the stack
#2      _rectIsValid  (dart:ui/painting.dart:31:10)
#3      Canvas.drawImageRect  (dart:ui/painting.dart:4127:12)
#4      paintImage 
package:flutter/…/painting/decoration_image.dart:565
#5      DecorationImagePainter.paint 
package:flutter/…/painting/decoration_image.dart:276
#6      _BoxDecorationPainter._paintBackgroundImage 
package:flutter/…/painting/box_decoration.dart:466
```
...
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#ee24a

**Comment by JigneshPatel23** [comment]
@vashisth00 can you please share a sample code?

**Comment by darshankawar** [comment]
@vashisth00 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by vashisth00** [comment]
It is resolved by wrapping CircleAvatar with a badge
