### ISSUE TITLE
Flutter web not hot reloading after adding a widget

### ISSUE THREAD

**Issue by michaeldadzie** [flutter/flutter#67978]
Hot reload Error
hotRestart: (-32000) Service connection disposed
 
![Capture](https://user-images.githubusercontent.com/52431642/95802436-ed6b9d00-0cec-11eb-9006-c5b0dc88f6d4.PNG)

[√] Flutter (Channel master, 1.23.0-4.0.pre.86, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-4.0.pre.86 at D:\Program Files\flutter
    • Framework revision 57cda51f7e (3 weeks ago), 2020-09-23 16:52:02 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dadzi\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\dadzi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.38

! Doctor found issues in 1 category.

`if (!ResponsiveWidget.isSmallScreen(context))
Row(
mainAxisAlignment: MainAxisAlignment.end,
 children: <Widget>[
IconButton(
onPressed: () {}
icon: Icon(Icons.add)
)
]
)`

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@michaeldadzie 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
