### ISSUE TITLE
“https://storage.flutter-io.cn”cannot be opened

### ISSUE THREAD

**Issue by q-11063355** [flutter/flutter#67982]
When I found out that "pub get" had an error and the service was not linked. I clicked on https://storage.flutter-io.cn and found that the following io.cn did not respond properly

**Comment by darshankawar** [comment]
@q-11063355 
Please elaborate on the issue with detailed steps. What were you trying to do when you say `pub get" had an error and the service was not linked`. Also provide `flutter doctor -v`.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
