### ISSUE TITLE
 'previousOwner._heroControllerFromScope != newHeroController': is not true.

### ISSUE THREAD

**Issue by chrissen0814** [flutter/flutter#67999]
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24:
'previousOwner._heroControllerFromScope != newHeroController': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      NavigatorState._updateHeroController.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2785:24)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#9      _invoke (dart:ui/hooks.dart:251:10)
#10     _drawFrame (dart:ui/hooks.dart:209:3)
(elided 5 frames from class _AssertionError and dart:async)

**Comment by darshankawar** [comment]
@chrissen0814 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by chrissen0814** [comment]
[✓] Flutter (Channel unknown, v1.22.1, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/chrissen/Flutter/flutter
    • Framework revision f7a6a7906b (5 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chrissen/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G9600 • 1a5089d0bb0b7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

**Comment by chrissen0814** [comment]
Expanded(
                  flex: 0,
                  child: GestureDetector(
                    onTap: (){
                      //[FlutterBoost Information](https://github.com/alibaba/flutter_boost)
                      FlutterBoost.singleton.open(RouterPageAddressList, urlParams: {
                        'editable': false,
                      });
                    },
                    child: Text("Edit", style: TextStyle(color: Colors.grey[600])),
                  ),
                )


Widget _buildRow(BuildContext context, int index) {
    TradeAddressesRow addressModel = showRows[index];
    String name = addressModel.receiver ?? "";
    String phone = addressModel.phone ?? "";
    String address =
        "${addressModel.province ?? ""} ${addressModel.city ?? ""} ${addressModel.district ?? ""} ${addressModel.address ?? ""}";
    bool isDefault = addressModel.isDefault ?? false;
    return GestureDetector(
      onTap: () {
        //[EventBus Information](https://github.com/marcojakob/dart-event-bus)
        EventBusManager().postEvent(EventDepositBoxSendOut(addressModel));
          FlutterBoost.singleton.closeCurrent(result: {}, exts: {});
      },
      child: Padding(
        padding: EdgeInsets.only(bottom: 1),
        child: Container(
          width: screenWidth,
          color: Colors.white,
          child: Padding(
            padding: EdgeInsets.only(left: 15, top: 10, bottom: 10, right: 15),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Row(
                  children: <Widget>[
                    Flexible(
                      child: RichText(
                        overflow: TextOverflow.ellipsis,
                        text: TextSpan(
                            text: name, style: TextStyle(color: Colors.black)),
                        strutStyle: StrutStyle(fontSize: 14),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(left: 10),
                      child: Text(
                        phone,
                        style: TextStyle(color: Colors.grey, fontSize: 12),
                      ),
                    ),
                    Visibility(
                        visible: isDefault,
                        child: Padding(
                          padding: EdgeInsets.only(left: 10),
                          child: Container(
                            decoration: BoxDecoration(
                                color: Colors.green,
                                shape: BoxShape.rectangle,
                                borderRadius:
                                    BorderRadius.all(Radius.circular(8.0))),
                            child: Padding(
                              padding:
                                  EdgeInsets.only(left: 6, right: 6, bottom: 2),
                              child: Text("默认",
                                  style: TextStyle(
                                      fontSize: 12, color: Colors.white)),
                            ),
                          ),
                        ))
                  ],
                ),
                Text(
                  address,
                  style: TextStyle(color: Colors.black, fontSize: 12),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }

**Comment by darshankawar** [comment]
@chrissen0814 
I see lot of custom code in your code sample. Please provide a sample that we can directly copy paste and run in IDE that doesn't include any 3rd party plugin code.

**Comment by chrissen0814** [comment]
Sorry, I think this is a bit difficult. Our Flutter project is a sub-project of the main project. Between the main project and the sub-projects, navigation is achieved through the FlutterBoost project. At present, we have solved this problem by modifying the version number of Flutter. I guess the cause of this problem may be the inconsistent version.

**Comment by darshankawar** [comment]
@chrissen0814 based on your last message, seems your issue has been solved. I am going ahead and closing this as resolved. If you face similar issue again, write in comments and I'll reopen.
Thanks.
