### ISSUE TITLE
Swipe to change between Tabs

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#68]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:23 GMT_
_Originally opened as https://github.com/flutter/engine/issues/21_

----

_From @eseidelGoogle on July 16, 2015 16:44_

This came up in one of our customer meetings yesterday.  On android you can swipe left/right in the content area to change between tabs in a tab view.

@HansMuller 

_Copied from original issue: domokit/mojo#328_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 05:03 GMT_

----

The difficulty here is that not only should the body be pageable, but the indicator should be animated (with the animation slaved to the pager position) when the user is swiping.

**Comment by Hixie** [comment]
@HansMuller Is this easier to do now that you have the TabSelection widget?

**Comment by HansMuller** [comment]
Yes, it should be.

**Comment by Hixie** [comment]
Is this fixed now?

**Comment by HansMuller** [comment]
I'm working on a bug fix (the bug showed up in the game's tabs).  I'll close this issue after the bug fix has landed.

**Comment by HansMuller** [comment]
As of https://github.com/flutter/flutter/pull/969 this feature should be working reasonably well.
