### ISSUE TITLE
Platform adaptive icons

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#68016]
This issue tracks support for platform adaptive icons

- [x] Arrow back
    - [ ] Would replace `BackButtonIcon`, to be deprecated or made private. `BackButtonIcon`  should return the rounded variant of the iOS  should be `Icons.arrow_back_ios_rounded` (not `Icons.arrow_back_ios`) now that it is available.
- [x] Arrow forward
- [x] Share
- [x] More
    - [x] Would replace https://github.com/flutter/flutter/blob/3e069a433b2b423d952407b3964d868c0c7cc4fe/packages/flutter/lib/src/material/popup_menu.dart#L1115 #70773
- [x] FlipCamera

Related to #33830

- [x] https://flutter.dev/docs/resources/platform-adaptations#iconography should be updated https://github.com/flutter/website/pull/6515

**Comment by guidezpl** [comment]
cc @HansMuller What do you think of the naming convention? PlatformShareIcon and PlatformMoreIcon might make more sense, but differ from the existing BackButtonIcon

**Comment by HansMuller** [comment]
Personally, I like `Icons.adaptive.X` and I think it's OK to deprecate BackButtonIcon, as long as the substitution is straightforward.
