### ISSUE TITLE
[feature] Add padding property for card

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#68029]
Use case

Card does not have padding parameter , so if I currently want its child to have padding , I need to wrap it in container or padding first . then i can have its child my desired widget . 

## Proposal

I want Card to have custom padding for its child

**Comment by goderbauer** [comment]
Widgets are composable, so you can just wrap the child that you pass to the Card in a Padding widget to achieve the same effect. I don't think there's reason to build this into the Card widget and add yet another parameter to it.

**Comment by amanv8060** [comment]
@goderbauer 
OK! but i already mentioned that we can wrap the child in padding . 

Since the card uses Container and  providing padding right there should not cause any issue . I dont feel that we should use an extra widget if thats achievable without it .

https://github.com/flutter/flutter/blob/31925d91fd80620e14d78d038a1449b792fd7d14/packages/flutter/lib/src/material/card.dart#L201
