### ISSUE TITLE
Gradle, Project Structure, Flutter doctor problems after Android Studio 4.1 update

### ISSUE THREAD

**Issue by AndrewByk** [flutter/flutter#68024]
After Android Studio 4.1. update I missing Project Structure option in File menu 

![pic5](https://user-images.githubusercontent.com/53439982/95869368-31998480-0d63-11eb-82a4-ce1adf135411.png)

And for each new project, I need to manually update Gradle to 6.+
![pic7](https://user-images.githubusercontent.com/53439982/95869572-6dcce500-0d63-11eb-8288-15937c363d6d.png)

flutter doctor -v
![pic0](https://user-images.githubusercontent.com/53439982/95869739-9bb22980-0d63-11eb-9050-8ff3e2086af4.png)

**Comment by TahaTesser** [comment]
Hi @AndrewByk 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/67986
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by AndrewByk** [comment]
Thank you
