### ISSUE TITLE
[webview_flutter] Load html string with base url natively

### ISSUE THREAD

**Issue by rubenferreira97** [flutter/flutter#68027]
## Use case
Currently the only way to load a html string in webview_flutter is to parse html to a URI using the following method `Uri.dataFromString()`. This seems a bit clunky and can lead to some rendering problems in some html elements. 

## Proposal
Since currently WebView widget is backed by a WKWebView on iOS and WebView on Android, have some way to call `loadHTMLString()` on IOS and `loadDataWithBaseURL()` on Android.

This might be a duplicate #49203 but it's closed and it did not really solve the problem, just a workaround. If I am not mistaken in the past this proposal would be difficult to implement, however with hybrid composition this seems easier to implement.

**Comment by dkaera** [comment]
Hey, `WebViewController` provides a named parameter `baseUrl`.

```dart
Future<void> loadHtmlString(
    String html, {
    String? baseUrl,
  }) {...}
```
Looks like exactly what you need :)

**Comment by stuartmorgan** [comment]
Closing, as this was addressed a while ago; it looks like the PR just didn't get linked to this issue.
