### ISSUE TITLE
[Camera] Unexpected B&W Photo preview on Pixel 4 XL with the latest Android 11 OS update

### ISSUE THREAD

**Issue by PeterSvitla** [flutter/flutter#68031]
## Steps to Reproduce

The application has to be launched on my Pixel 4 XL phone, and on-camera preview, I can see everything in black and white.
When I am trying to use any other real Android and iPhone device, it works well. 
I have tried to restart the phone, but it is still the same for the latest OS version update(since the last week). 
The camera application version for Pixel 4 XL is 7.5.107.326355469, and Nexus 5x is 5.1.018.177470874.

**Expected results: Colorful photo preview and captured image

**Actual results: B&W image in image preview. 

There is no exception and nothing special between logs for that particular device with B&W and all others where it is working as expected.

Analytics: 0 issues found. (ran in 6.7s)

Doctor: Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-ES)
    • Flutter version 1.22.1 at /Users/Peter/development/flutter_1.7
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Peter/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[✓] Connected device (3 available)
    • Nexus 5X (mobile) • 025d5dc9bc77716f • android-arm64 • Android 8.1.0 (API 27)
    • Pixel 4 XL (mobile) • 9B081FFBA011SN • android-arm64 • Android 11 (API 30)
    • iPhone (Peter) (mobile) • 544084cfd5e9424b4638c616288705bad487a393 • ios           • iOS 14.0.1

</details>

**Comment by darshankawar** [comment]
@PeterSvitla 
Although I don't have Pixel 4XL device with OS 11, I tried the official `camera` plugin example on Samsung S10+, Samsung Galaxy A2Core (8.1.0) and on iPhone 6s (OS 14) and saw camera preview in color. The closest I could get was Pixel 3XL emulator with api 30 and see color preview.

<img width="419" alt="Screenshot 2020-10-14 at 1 12 08 PM" src="https://user-images.githubusercontent.com/67046386/95959027-92869280-0e1f-11eb-9b15-68e6ca8b65e0.png">

Could you show us image from the device ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
