### ISSUE TITLE
Is "flutter build web" now clearing the build directory?

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#68045]
Before updating flutter to `1.23.0-13.0.pre` whenever I build my app for web, it would just overwrite the web directory inside build, but the dir was not being completely erased.

That allowed me to have a git repo there that I was using to deploy my website, since the git folder would just stay there.

Now it looks like the build/web folder is being completely wiped out with every build. Is this new? Is this expected?

Thank you

**Comment by jonahwilliams** [comment]
yes, this is expected. If you want a stable output folder I suggest copying somewhere else

**Comment by jlubeck** [comment]
Ok, thank you for confirming
