### ISSUE TITLE
Increase Flutter LUCI windows capacity

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#68056]
With cirrus tasks migrated to LUCI, we have almost same number of Windows builders as Linux ones, but a smaller number of Windows bots in pools. This has resulted in long queue time for Windows tests.

We need to increase the Windows capacity to be at least same as Linux.

**Comment by godofredoc** [comment]
Added 10 machines we may need with Windows Server. Will monitor the SLOS and request the additional 20 machines.

**Comment by godofredoc** [comment]
We are back within SLO, closing this bug.
