### ISSUE TITLE
Linter crashes on Mac due to absent stdout on result of WorkerJob.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68053]
This occurred on a Mac host while trying to [reproduce a linter error on the bot](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866520425304092736/+/steps/lint_test/0/stdout).

The stack trace in the linter was:
```
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (file:////engine/src/flutter/ci/bin/lint.dart:248:28)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

[The line that caused the exception](https://github.com/flutter/engine/blob/7959d80c10d586a71f2671febe877bfba3d2d014/ci/bin/lint.dart#L248) reads `if (job.result?.stdout.isEmpty ?? true)` which indicates that the `ProcessRunnerResult.stdout` was `null`. Unclear why this can be the case.

**Comment by chinmaygarde** [comment]
cc @zanderso and @gspencergoog as authors of the linter harness.

**Comment by zanderso** [comment]
It's probably the `result` field of `job` that is `null`, and another `?.` is needed.

**Comment by chinmaygarde** [comment]
That just suppresses information about failures.

```
Jobs:   0% done,   0/16  completed,  0 in progress,   0 pending,  16 failed.    
No lint problems found.
```

**Comment by zanderso** [comment]
Ah, in that case, we'll have to get advice from @gspencergoog on `package:process_runner`.

**Comment by gspencergoog** [comment]
I added a suggested fix to the PR.

**Comment by zanderso** [comment]
I think the processes are throwing `ProcessException`s. I think we need to print `pool.failedJobs`. I'm out of time for right now, but I'll return to this in a bit unless @gspencergoog wants to pick it up.

**Comment by gspencergoog** [comment]
I can take a look.
