### ISSUE TITLE
Scroll physics should be included on Theme

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68063]
It would be nice if we could change the whole app's scroll physics by just adding it to the Theme, instead of relying on the platform or having to sublclass a `ScrollBehavior` and edit it.

**Comment by HansMuller** [comment]
Is [ScrollConfiguration](https://api.flutter.dev/flutter/widgets/ScrollConfiguration-class.html) sufficient?

**Comment by feinstein** [comment]
I am using it, but it's a bit more cumbersome, as I requires  that we create a specialized 'ScrollBehavior` and then a `builder` in the `MaterialWidget` so we can then rap all the new routes in it. 

It works, but it's not as polished or simple to use.

**Comment by HansMuller** [comment]
So I suppose the idea here would be to use a Theme property to construct a ScrollConfiguration, essentially as a convenience.

**Comment by feinstein** [comment]
Yes.

**Comment by goderbauer** [comment]
@Piinks

**Comment by Piinks** [comment]
I have potentially wonderful news. While this has not been added to theme, it has been added for app-wide setting through MaterialApp.scrollBehavior and CupertinoApp.scrollBehavior. 🎉 
I am going to close this as completed, but please do let us know if it does not address your issue. Thanks!

**Comment by feinstein** [comment]
Sounds good to me :) thanks!
