### ISSUE TITLE
Problem with UserCredential in Firebase

### ISSUE THREAD

**Issue by DanielMohammadii** [flutter/flutter#68079]
I'm having an error with Firebase for the first time, and not sure why it keeps showing the error.
Error : 
The name 'UserCredential' is defined in the libraries 'package:firebase/src/auth.dart (via package:firebase/firebase.dart)' and 'package:firebase_auth/firebase_auth.dart'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.",

```
import 'package:firebase_auth/firebase_auth.dart';
class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Create user object based on FirebaseUser
  CustomUsers _customModelForFirebaseUser(user) {
    return user != null ? CustomUsers(uid: user.uid) : null;
  }

  // auth changed user stream
  Stream<CustomUsers> get user {
    return _auth.authStateChanges().map(_customModelForFirebaseUser);
  }

  //Signin Anon
  Future signInAnon() async {
    try {
      UserCredential userCredential = await _auth.signInAnonymously();
      CustomUsers user = userCredential.user;
      print(_customModelForFirebaseUser(user));
    } catch (e) {
      print(e.toString());
      return null;
    }
  }

```

**Comment by darshankawar** [comment]
@DanielMohammadii 
Please checkout the official usage of `UserCredential` class [here](https://firebase.flutter.dev/docs/auth/usage/) and see if you missed anything in your implementation.
If problem persists, please consider to open this issue in Firebase dedicated repo [here](https://github.com/FirebaseExtended/flutterfire/issues).

Closing from here.
