### ISSUE TITLE
Stream builder failing to create snacker

### ISSUE THREAD

**Issue by faridg18** [flutter/flutter#68070]
## Steps to Reproduce

I have a Stream Builder that should display snackbar if a state was provided. 

Like so:
```
  final snackBar = SnackBar(content: Text('Yay! A SnackBar!'));
  
if(state)
   Scaffold.of(context).showSnackBar(snackBar);
```

**Actual results:** 

I get the following: 

flutter: The following assertion was thrown building StreamBuilder<LoginEvent>(dirty, state:
flutter: _StreamBuilderBaseState<LoginEvent, AsyncSnapshot<LoginEvent>>#14f96):
flutter: setState() or markNeedsBuild() called during build.
flutter: This Scaffold widget cannot be marked as needing to build because the framework is already in the
flutter: process of building widgets.  A widget can be marked as needing to be built during the build phase
flutter: only if one of its ancestors is currently building. This exception is allowed because the framework
flutter: builds parent widgets before children, which means a dirty descendant will always be built.
flutter: Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   Scaffold
flutter: The widget which was currently being built when the offending call was made was:
flutter:   StreamBuilder<LoginEvent>

<details>
  <summary>Logs</summary>

```
```

```
```

Here is my flutter doctor: 

[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/faridgarciayala/Downloads/flutter
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/faridgarciayala/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iP
```
```

</details>

**Comment by darshankawar** [comment]
@faridg18 
Please provide complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by iapicca** [comment]
@faridg18 try this

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamController<bool> _controller;

  static const _snack = SnackBar(content: Text('Yay! A SnackBar!'));

  @override
  void initState() {
    super.initState();
    _controller = StreamController<bool>.broadcast();
  }

  @override
  void dispose() {
    _controller?.close();
    super.dispose();
  }

  void _show(BuildContext context) {
    Scaffold.of(context).hideCurrentSnackBar();
    Scaffold.of(context).showSnackBar(_snack);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: StreamBuilder(
              stream: _controller.stream,
              builder: (BuildContext context, AsyncSnapshot snapshot) {
                _controller.stream.listen((_) => _show(context));
                return !snapshot.hasData
                    ? const CircularProgressIndicator()
                    : snapshot.hasError
                        ? const Icon(Icons.error)
                        : const FlutterLogo(size: 80);
              }),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => _controller.sink.add(true),
          child: const Icon(Icons.refresh),
        ),
      );
}

```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
