### ISSUE TITLE
InteractiveViewer doesn't scroll panned edges when child is Scrollable Widget and panEnabled = true

### ISSUE THREAD

**Issue by grantespo** [flutter/flutter#68073]
InteractiveViewer panning works fine on non-scrollable widget. Ex:

    return InteractiveViewer(
             panEnabled: true,
             boundaryMargin: EdgeInsets.all(0),
             minScale: 0.5,
             maxScale: 4,
             child: Image.network("image_url")
      );

However, when the child is a scrollable widget, I am not able to view the top/bottom of the widget while panning.

    return InteractiveViewer(
             panEnabled: true,
             boundaryMargin: EdgeInsets.all(0),
             minScale: 0.5,
             maxScale: 4,
             child: Listview(children: [Image.network("image_url")])
      );

The interactiveViewer isn't respecting the child's panned edges to be scrollable.

@justinmc you requested me to tag you in this issue. Let me know if you need any extra info about this bug. Should be pretty straight forward to reproduce

**Comment by darshankawar** [comment]
Hi @grantespo 
I tried to replicate the issue. Was able to scroll and zoom in, zoom out the widget. Could you provide more info on not able to scroll the panned edges if I missed anything to replicate exactly ?

[68073.mp4.zip](https://github.com/flutter/flutter/files/5377144/68073.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (2 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      86.0.4240.75

• No issues found!

```

</details>

**Comment by justinmc** [comment]
I can't exactly reproduce it either, but I'm also unsure what the desired behavior is.  What do you expect to happen when you have something that scrolls inside of something that pans like this?

<details>

<summary>Example app code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Flutter Bug"),
          actions: [
          ],
        ),
        body: Center(
          child: InteractiveViewer(
             panEnabled: true,
             boundaryMargin: EdgeInsets.all(0),
             minScale: 0.5,
             maxScale: 4,
             child: ListView(children: [Image.network("https://placekitten.com/200/800")])
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by grantespo** [comment]
@justinmc I was able to reproduce with your sample code on iOS SE (2nd gen) simulator (14.0)

simply replace the image url with this: 
https://upload.wikimedia.org/wikipedia/commons/7/74/Earth_poster_large.jpg

After zooming in on the image to the maximum, try scrolling up to view the panned content.

**Comment by darshankawar** [comment]
Following @grantespo steps above, I zoomed in the image to the max. Although I was able to scroll sideways, but not vertically. 

[68073.mp4.zip](https://github.com/flutter/flutter/files/5382894/68073.mp4.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

Keeping this open for further analysis.

**Comment by justinmc** [comment]
Ok I can reproduce it too, but I'm not sure what InteractiveViewer should be doing in this case.  @grantespo What is your use case for this?  Why put a ListView inside of InteractiveViewer?

If the objective is just to get an overscroll effect, there is an issue to add that to InteractiveViewer: https://github.com/flutter/flutter/issues/58042.

**Comment by grantespo** [comment]
@justinmc 

>Why put a ListView inside of InteractiveViewer?

I need listview of images which should be zoomable.

**Comment by justinmc** [comment]
No problem.  I wonder if you could implement this instead as each image having its own InteractiveViewer?  So the images are zoomable, but not the list itself.

Otherwise I worry that the experience isn't going to be nice. If the InteractiveViewer is the only child of the ListView, then you are losing out on the performance benefits of ListView.  You might as well just use a Column (along with `constrained: false`) and let the InteractiveViewer handle the "scrolling".
