### ISSUE TITLE
Use fast path in Skia for rendering shadows.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#6807]
In the latest versions of Skia, the `SkShadowMaskFilter` can render shadows in a faster/more efficient manner.

Work Items:

- [ ] Roll Skia to latest.
- [ ] Use the `SkShadowMaskFilter` for rendering shadows in Flutter. [Examples are available](https://skia.googlesource.com/skia/+/9c2249f51c861f3d0db089fbba38b8ac1d63d160/samplecode/SampleAndroidShadows.cpp#370).
- [ ] Capture before/after traces in an OpenGL profiler.

**Comment by ds84182** [comment]
Has there been any work on this? This would greatly improve performance on slower devices since I've observed some terrible shadow performance on both my Moto X 2013 and my Moto Z Play.

**Comment by chinmaygarde** [comment]
I rolled Skia and did some initial work on integration of `SkShadowMaskFilter`. Got pulled away before I could finish my work and profile. Will get back to it ASAP.

**Comment by eseidelGoogle** [comment]
@chinmaygarde if this isn't on your short list, maybe you could help @jason-simmons to work on this?  @abarth tells me this is a potentially big win and I know you have a lot on your plate atm. :)

**Comment by chinmaygarde** [comment]
This has been addressed.
