### ISSUE TITLE
google_sign_in account picker

### ISSUE THREAD

**Issue by kaarens93** [flutter/flutter#68082]
Looking for a configuration like `prompt=select_account+consent` . Depending on what device I'm using, the google window is not consistent. On some devices, I have to enter my credentials. On others, I can choose which account to select. Why is the account picker not shown by default and only shown sometimes?

**Comment by darshankawar** [comment]
@kaarens93 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing. It'll also be helpful if you could add screenshots of the devices (along with OS versions )on which you are seeing this discrepancy.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
