### ISSUE TITLE
I got that very same behavior on Android Studio 4.1 after update to new version yesterday

### ISSUE THREAD

**Issue by sandipborad** [flutter/flutter#68084]
I got that very same behavior on Android Studio 3.2 RC3:

`[✓] Android Studio (version 3.2)`
`    • Android Studio at /home/fabio/DevTools/beta/android-studio`
`    ✗ Flutter plugin not installed; this adds Flutter specific functionality.`
`    ✗ Dart plugin not installed; this adds Dart specific functionality.`
`    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)`

_Originally posted by @febs in https://github.com/flutter/flutter/issue_comments/422395091_

**Comment by sandipborad** [comment]
![Screenshot 2020-10-14 at 11 29 02 AM](https://user-images.githubusercontent.com/13064698/95949894-3fa5de80-0e11-11eb-9748-f20a5c366c2d.png)
Here is flutter doctor output and i clarify sevral times to check plugins , that plugins already installed  , this happen after i update my android studio to 4.1 latest stable channel.

**Comment by darshankawar** [comment]
@sandipborad 
Please see this similar issue, [67986](https://github.com/flutter/flutter/issues/67986) and related comments on plugins not being installed. 

https://github.com/flutter/flutter/issues/67986#issuecomment-707881534
https://github.com/flutter/flutter/issues/67986#issuecomment-707511812

Closing this as duplicate.

**Comment by sandipborad** [comment]
@darshankawar it's say it's warning #67986, it's also working flutter projects in my side , problem is how i can fix so `flutter doctor -v` work without any issue of the category.

**Comment by jakoss** [comment]
You can't, and you don't have to. Just use flutter as it is - it will be fixed in later update
