### ISSUE TITLE
Subject/Message/Description Text

### ISSUE THREAD

**Issue by braysonjohn148** [flutter/flutter#68085]
Allow to share on whastapp,insta.... with a text on it. Not just the link.

**Comment by Raj-Dave368** [comment]
I am not getting an idea of what do you want. can you please explain a bit with an **example**?

**Comment by pedromassangocode** [comment]
Yes, @Raj-Dave368 is right, we need more details about this proposal.

Is this a proposal for a new/existing plugin?
How that would work?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
