### ISSUE TITLE
Text fields' values do not get trimmed correctly when `textDirection: TextDirection.rtl`

### ISSUE THREAD

**Issue by HasanAlyazidi** [flutter/flutter#68093]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Create a simple widget
3. Add a `TextFormField` or `TextField` widget with `textDirection: TextDirection.rtl`
4. Print trimmed value inside `onChanged`

**Expected results:**
I expect when i call `trim()` on the value of the text field returned from `onChanged` or `controller.text`, it should get trimmed.

when i type "   str   ", "str ", " str" it should remove the leading and trailing whitespaces and return: 'str'

**Actual results:**
It does not get trimmed correctly if `textDirection: TextDirection.rtl`, but, it works just fine if `textDirection: TextDirection.ltr`.

Here is a working demo of the bug:
https://dartpad.dev/b6130da3c610e01d4cc2ddf0ab278d3e

<details>
  <summary>Logs</summary>

No exceptions

```
```

Analyzing bug...
No issues found! (ran in 3.4s)

```
```

[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.4 at X:\Development\Configurations\flutter
    • Framework revision fba99f6cf9 (4 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at X:\Development\Configurations\android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = X:\Development\Configurations\android\sdk
    • ANDROID_SDK_ROOT = X:\Development\Configurations\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\USR\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>


```
TextInput: (this ‎is ‎not ‎working ‎ ‎ ‎ ‎ ‎ ‎ ‎)
TextDirection.ltr: (around)
TextDirection.ltr: (around)


```

**Comment by LongCatIsLooong** [comment]
I think the directionality markers we inserted prevented `trim` from removing the surrounding whitespaces. @GaryQian .

**Comment by AlaaEldeenYsr** [comment]
```dart
  String trim(String string) {
    assert(string != null);
    final stringList = string.characters.toList();
    final whitespaces = ['8206', '8207', '32'];
    while (whitespaces.contains(stringList.last.runes.join())) stringList.removeLast();
    while (whitespaces.contains(stringList.first.runes.join())) stringList.remove(stringList.first);
    return stringList.join();
  }
```
