### ISSUE TITLE
45% performance regression from maxLines patch

### ISSUE THREAD

**Issue by fsc8000** [flutter/flutter#6809]
I bisected this regression to revision https://github.com/flutter/flutter/commit/d39eb84ac44fc58f3057753140b88e431ab7f37e

## Steps to Reproduce
```
cd dev/benchmarks/microbenchmarks
flutter run --profile -t lib/stocks/layout_bench.dart
```

I used a Nexus 4.

## Logs

before (rev 97dbd9eacf6f1940d1ff2afc6fc1b3835f1e4bfd)
I/flutter : Stock layout: 1042.2µs per iteration

after:
I/flutter : Stock layout: 1512.3µs per iteration

**Comment by Hixie** [comment]
cc @mpcomplete

**Comment by mpcomplete** [comment]
I tracked this regression down to this line: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L527

The setState call triggers more builds than before. However, I think this is fixing a bug. The content/container extents are changing, so the state is changing. We should be triggering a rebuild.

I could look into this further, but I imagine the scrollable rework will make this obsolete anyway.

**Comment by Hixie** [comment]
Closing as obsolete as matt said.
