### ISSUE TITLE
missing @

### ISSUE THREAD

**Issue by a-h-mzd** [flutter/flutter#68095]
there are several places where @ is missing before "required".
places which I've found so far:
```dart
LinearGradient({
    required List<Color> colors,
  })
```
```dart
AnimationController({
    required TickerProvider vsync,
  })
```

<details>
<summary>flutter --version</summary>
<p>

```bash
Flutter 1.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f30b7f4db9 (6 days ago) • 2020-10-08 10:06:30 -0700
Engine • revision 75bef9f6c8
Tools • Dart 2.10.1
```

</p>
</details>

**Comment by sidrao2006** [comment]
Hey @a-h-mzd , the @ is not missing. With null safety, required is now a keyword.

**Comment by darshankawar** [comment]
@a-h-mzd 
`require` is now a keyword w.r.t `null safety`. See [this](https://github.com/flutter/flutter/issues/67444#issuecomment-704530907) comment for more details.
Closing this as non-issue.
