### ISSUE TITLE
Pageview auto animate to the last page when a textview on the first page gains focus

### ISSUE THREAD

**Issue by isiyemijoe** [flutter/flutter#68101]
I have a pageview with three pages, each page has a list of textfields, i pass a voidcallback from the parent to the f
![giterror](https://user-images.githubusercontent.com/56980642/95988452-d29a4500-0e20-11eb-9b17-1142ea47340e.png)
irst page of the pageview, whenever I click on the textview in within the first page it auto animates to the last page of the page view and i get this error;

ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 112 pos 12: '_positions.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

The relevant error-causing widget was: 
  AddSuitor file:///C:/Users/Isiyemi%20Joseph/AndroidStudioProjects/match_manager/lib/Mainactivity.dart:171:39
When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:112:12)
#3      

> PageController.animateToPage (package:flutter/src/widgets/page_view.dart:203:41)

#4      _AddSuitorState.nextPage (file:///C:/Users/Isiyemi%20Joseph/AndroidStudioProjects/match_manager/lib/routes/MainActivity/addSuitor.dart:206:21)
#5      _AddSuitorState.build (file:///C:/Users/Isiyemi%20Joseph/AndroidStudioProjects/match_manager/lib/routes/MainActivity/addSuitor.dart:120:37)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)``

**Comment by darshankawar** [comment]
@isiyemijoe 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample in text format that highlights the issue.
Providing a screenshot of the code won't help.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
