### ISSUE TITLE
A PointerData::Change::kDown may cause extra frames with the same picture layers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#6810]
The raster cache picks up this repetition of `SkPicture`s and attempts to rasterize these pictures. These pictures may be large and expensive to rasterize (causing us to lose frames). Since the `kDown` is usually followed by `kMove`, the rasterized image is immediately thrown away. So a lot of work is done for nothing.

Steps to reproduce are shown [in the attached video](https://www.youtube.com/watch?v=Dv2Rz8siyUc&feature=youtu.be). We frequently lose frames in the Pesto demo on touch down because of the extra rasterize of the entire frame that is subsequently discarded. Once fixed, the `kDown` should show no change to the checkerboard pattern.

**Comment by Hixie** [comment]
The scrolling code is probably giving redundant setStates. I'll try to remember to avoid that when I get to that part of my scrolling refactor.

**Comment by chinmaygarde** [comment]
@Hixie says we can make the following changes to mitigate this:
* Mark the root layer as complicated so the cache never rasterizes the whole screen.
* Get rid of redundant `setState`s in the scrolling code.

Both changes are in the framework.

**Comment by Hixie** [comment]
Do you know which layer is getting rasterised?

At the framework level, we only have hints for PictureLayers. The root layer is TransformLayer.

**Comment by Hixie** [comment]
I'm unlicking this cookie because I have too much on my plate.

**Comment by Hixie** [comment]
@chinmaygarde Did the scrolling refactor affect this at all?

**Comment by jonahwilliams** [comment]
We're moving away from raster caching. Closing as obsolete
