### ISSUE TITLE
I want to create line chart like this.

### ISSUE THREAD

**Issue by Darkhorse07232020** [flutter/flutter#68108]
![image](https://user-images.githubusercontent.com/67903345/96011416-8d3f3d00-0e4b-11eb-8cb0-42fdd3d90b80.png)

Hello, everyone.
I am learning flutter, and I am creating the simple flutter application.
I tried to add line chart like this, but I can't find the chart package for this one.
How can I create this chart?

**Comment by PixelToast** [comment]
Closing with the above comment, you have higher chance of getting help with questions at one of our communities such as [StackOverflow](https://stackoverflow.com/tags/flutter)
