### ISSUE TITLE
Not able to migrate existing project to AndroidX  [androidx-migration]

### ISSUE THREAD

**Issue by HostilePixie** [flutter/flutter#68112]
I am creating a new project using flutter and when I got to Refactor > Migrate to AndroidX... It gives an error in a popup that says "No usages found in the project"

**Comment by pedromassangocode** [comment]
Hi @HostilePixie 
How are you creating the Project?
Please provide the output of `flutter doctor -v`.

Thank you

**Comment by HostilePixie** [comment]
I used the flutter create app_name command to create my project

**Comment by HostilePixie** [comment]
Here is a my result of `flutter doctor -v`:


[✓] Flutter (Channel master, 1.23.0-8.0.pre.69, on Mac OS X 10.15.6 19G2021 x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.69 at /Users/rohan/tools/flutter
    • Framework revision a06f385145 (2 weeks ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/rohan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[!] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[!] Connected device                          
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by pedromassangocode** [comment]
Hi @HostilePixie 
can you please provide the your `<project-name>/android/gradle.properties`?
Thanks

**Comment by HostilePixie** [comment]
Here is my `gradle.properties`:

`
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
`

**Comment by HostilePixie** [comment]
here is my `gradle.properties`

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true

**Comment by Abhishek01039** [comment]
Hi @HostilePixie 
your app is already migrated to AndroidX
Thanks

**Comment by HostilePixie** [comment]
But still why was android studio giving me the error, can you tell me how to solve it.

**Comment by pedromassangocode** [comment]
HI @HostilePixie 
In the latest Flutter versions newly created projects will be created with androidX automatically. 
Please see https://flutter.dev/docs/development/androidx-migration#how-do-i-know-if-my-project-is-using-androidx.

This simply mean that newly created projects will have the option to use AndroidX enabled by default by adding those options in `gradle.properties`:

```
android.useAndroidX=true
android.enableJetifier=true
```

 And since new projects don't have decencies that uses AndroidX nothing changes at this moment.

This is not an error, this message means that your project does not contains native dependencies that should be migrated to AndroidX. If you native project had some it would be migrated automatically.

I'm closing this as everything works as expected.
Thanks

**Comment by HostilePixie** [comment]
Ok, thank you for all your help. I really appreciate it.
