### ISSUE TITLE
22% performance regression from ellipsizing patch

### ISSUE THREAD

**Issue by fsc8000** [flutter/flutter#6811]
I bisected this regression to revision https://github.com/flutter/flutter/commit/21acf223016789b48ad582777118b3fef01344cf

## Steps to Reproduce
```
cd dev/benchmarks/microbenchmarks
flutter run --profile -t lib/stocks/layout_bench.dart
```

## Logs

before: (rev 88d9cbaa01c3e6e92e02d5cb25ef3fe868c6ce53)
I/flutter : Stock layout: 852.2µs per iteration

after:
I/flutter : Stock layout: 1100.6µs per iteration

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by cbracken** [comment]
Closing as obsolete.
