### ISSUE TITLE
TargetPlatform.linux for google maps plugin

### ISSUE THREAD

**Issue by theRealBitcoinClub** [flutter/flutter#68114]
I just built my Flutter app for web and I noticed that the maps plugin does not support my OS.

Is that soon to be realized?

**Comment by TahaTesser** [comment]
Hi @theRealBitcoinClub 
Please check out this [stackoverflow](https://stackoverflow.com/a/60429399) answer
Closing, as this isn't an issue with `google_maps_flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by theRealBitcoinClub** [comment]
OK, instead of just forgetting about this, maybe it provides value to the community to post a workaround here.

So the workaround would be:

1. Check inside the code of my app if the Flutter app is built for web:
https://stackoverflow.com/questions/57937280/how-can-i-detect-if-my-flutter-app-is-running-in-the-web

2. Then remove the button that the user would tap in the mobile version

**Anyway is there anyone working on a web compatible version of the Flutter google-maps-plugin?**

I think that would be appreciated and it might make sense to put that on the road map?

**Comment by Ao99** [comment]
There is a simple solution from the Flutter team - just add [google_maps_flutter_web](https://pub.dev/packages/google_maps_flutter_web) to your dependencies.
