### ISSUE TITLE
We should track the layout_bench microbenchmark on the dashboard

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6812]
To catch things like https://github.com/flutter/flutter/issues/6809 and https://github.com/flutter/flutter/issues/6811.

Ideally there would be thresholds that trigger automatic bug filing.

cc @yjbanov

**Comment by yjbanov** [comment]
We do have thresholds now (called "baseline"). If you look at https://flutter-dashboard.appspot.com/benchmarks.html you'll notice that we have new color coding:

- red - missed the baseline - should probably fix if it's happening consistently
- blue - meeting the baseline but have not reached the goal
- green - met the goal, time to celebrate (and probably tighten the baseline)

**Comment by yjbanov** [comment]
Oh :+1: to adding the microbenchmarks to the devicelab.

**Comment by Hixie** [comment]
Ah, excellent. Is there any automated bug filing or e-mail sending or anything for missing baselines?

**Comment by yjbanov** [comment]
No, but we do have a big screen TV that could be reviewed once in a while (and I actually do review it frequently and [file bugs](https://github.com/dart-lang/sdk/issues/27783) when I see something suspicious).

**Comment by Hixie** [comment]
I'd love to get e-mails the way that e.g. Travis and Coveralls mail me all the time. I'm not always at the office looking at the big monitors. :-) Also, it's much better if we can catch regressions within minutes of checkin than within days...

**Comment by Hixie** [comment]
Looks like this is in now, as microbenchmarks.stock_layout_iteration.
