### ISSUE TITLE
share-0.6.5+2 warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#68125]
I am trying to build a release version of my app with share enabled, but after upping the targetSDK to 30, I am getting this error::
```
share-0.6.5+2\android\src\main\java\io\flutter\plugins\share\Share.java:169: warning: [deprecation] getExternalStor
ageDirectory() in Environment has been deprecated
      File externalDir = Environment.getExternalStorageDirectory();
```

Possible fix https://stackoverflow.com/questions/57116335/environment-getexternalstoragedirectory-deprecated-in-api-level-29-java

                                    ^

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by giorgio79** [comment]
looks like a dupe https://github.com/flutter/flutter/issues/68011 @dnfield  is working on a release

**Comment by giorgio79** [comment]
Hmm, I am not sure it is a dupe. I am using Flutter, and Kotlin, so downgrading to JDK 8 is probably not a solutoin.

**Comment by hamdikahloun** [comment]
Hi @giorgio79 
PR already merged : https://github.com/flutter/plugins/pull/3152
Thank you

**Comment by giorgio79** [comment]
Thanks @hamdikahloun :) When will this merge result in a new Share plugin version? Or should I switch to Flutter master branch for immediate effect?

**Comment by hamdikahloun** [comment]
@giorgio79 the new version will be available soon without changing your channel.

**Comment by giorgio79** [comment]
I ended up forking your repo :) Thanks

**Comment by dnfield** [comment]
Just published https://pub.dev/packages/share/versions/0.6.5+3
