### ISSUE TITLE
[engine] Kill dart/safari/chrome processes after LUCI mac task executions

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#68137]
Engine post-commit builders have been failing occasionally with `retcode: -9`.
Related issues:
https://github.com/flutter/flutter/issues/66133
More failed builds:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7233
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7241

This may be due to OOM, and this issue is to track to kill leaking processes after task execution.

Related issue:
https://github.com/flutter/flutter/issues/67934

**Comment by godofredoc** [comment]
Can we close this one?

**Comment by keyonghan** [comment]
Changes have been implemented.
