### ISSUE TITLE
Stable branch failing to build "Mac ios Engine"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#68149]
The hotfix PR is https://github.com/flutter/engine/pull/21841

An example failing build: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/9907

@gaaclarke was able to successfully build locally.

**Comment by keyonghan** [comment]
saw the chat discussions. Does it still need triage from infra side?

**Comment by christopherfujino** [comment]
@keyonghan I will optimistically close this issue. If the PR fails post-submit, I will re-open.
