### ISSUE TITLE
video_player can't play pure audio file in ios but works in android

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#68154]
when using video_player to play pure audio file in IOS, it will not be initialized;
after reading the code, we found that , if there is no height and width, code will assume that it is not ready and return; comment this code , audio can be played;

I want to know why does it have such code, can we use other method to let it support audio play;

**Comment by wanjm** [comment]
```
- (void)sendInitialized {
  if (_eventSink && !_isInitialized) {
    CGSize size = [self.player currentItem].presentationSize;
    CGFloat width = size.width;
    CGFloat height = size.height;

    // The player has not yet initialized.
      
    if (height == CGSizeZero.height && width == CGSizeZero.width) {
      return;
    }
      
    // The player may be initialized but still needs to determine the duration.
    if ([self duration] == 0) {
      return;
    }

    _isInitialized = true;
    _eventSink(@{
      @"event" : @"initialized",
      @"duration" : @([self duration]),
      @"width" : @(width),
      @"height" : @(height)
    });
  }
}
```

suggest to remove following code;
```
    if (height == CGSizeZero.height && width == CGSizeZero.width) {
      return;
    }
```

**Comment by TahaTesser** [comment]
Hi @wanjm 
`video_player` is meant to play a video file not an audio file 
There is an open issue for the audio package https://github.com/flutter/flutter/issues/47105
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wanjm** [comment]
I think there is no need to block audio play in video_player ; for the native library it depends on can also play audio;

**Comment by wanjm** [comment]
38480 also has the same request;
