### ISSUE TITLE
Upgrade flutter-devicelab-mac-15 to latest Big Sur beta

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#68167]
We have reports https://github.com/flutter/flutter/pull/68050 doesn't work on newer betas.  Upgrade flutter-devicelab-mac-15 (currently running 20A5299w) to the newest beta (currently beta 10).

**Comment by keyonghan** [comment]
Tried updating via `System Preferences`, but hit 
```
An error occurred while downloading the selected updates. Please check your internet connection and try again.
```
![Screen Shot 2020-10-15 at 12 57 26 PM](https://user-images.githubusercontent.com/54558023/96179679-199e3e00-0ee6-11eb-95bc-11c4cf669e22.png)

Following https://developer.apple.com/forums/thread/653343?answerId=632205022#632205022, tried downloading it directly and then upgrade, but hit: 
```
This copy of the Install macOS Big Sur Beta application is damaged, and can‘t be used to install macOS.
```
![Screen Shot 2020-10-15 at 1 04 00 PM](https://user-images.githubusercontent.com/54558023/96180228-fa53e080-0ee6-11eb-8039-da3f32a23610.png)

**Comment by jmagman** [comment]
That's unfortunate, looks like a common problem too.  Are you able to restore it from the new image without going into the lab? Or boot into recovery mode? https://developer.apple.com/forums/thread/653347

**Comment by keyonghan** [comment]
Tried a couple of times, but the new image doesn't work..
Manual intervention seems needed for `boot to recovery mode`. Once we reboot, we are losing connection to the bot, then not able to press any button to enter the recovery mode from remote.

**Comment by godofredoc** [comment]
@jmagman did you get access to the lab to get the machine?

**Comment by jmagman** [comment]
Got it! Being able to book into recovery didn't help, I'm stuck [on beta 1](https://developer.apple.com/forums/thread/663103).  Waiting for @timsneath to send me the ipsw to try restoring with Configurator.

**Comment by jmagman** [comment]
I was able to restore to beta 10 with the ipsw.  Closing.
