### ISSUE TITLE
Typo error in Flutter code lab

### ISSUE THREAD

**Issue by hieuwu** [flutter/flutter#68169]
Below is the url to the issue including image.
"becausehot reload" should be editted as "because hot reload"
https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..index#3
![image](https://user-images.githubusercontent.com/43868345/96072144-d8019900-0ecd-11eb-8e59-01781640b730.png)

**Comment by sidrao2006** [comment]
Hey @hieuwu , this issue tracker is used for bugs and feature requests in the flutter tool and some packages. 
Please open this issue here - https://github.com/flutter/codelabs/issues

**Comment by hieuwu** [comment]
Sorry for my mistake.
But that repository has no issue part to be opened. Would you mind finding
one for me?
*Vũ Hoàng Hiếu*
*University of Science - VNU HCM City*
*Mobile:* (+84) 963 877 417
*Email:* star.hieu.99@gmail.com
*LinkedIn:* linkedin.com/in/hieuvu99/
<https://www.linkedin.com/in/hieuvu99/>
*Facebook:* fb.com/vu.hieu.5500


Vào Th 5, 15 thg 10, 2020 vào lúc 11:22 Aneesh Rao <
notifications@github.com> đã viết:
