### ISSUE TITLE
Missing dart.exe

### ISSUE THREAD

**Issue by ketrab2004** [flutter/flutter#68179]
## Steps to Reproduce

1. i tried to upgrade with flutter upgrade
2. antivirus deleted dart.exe
3. i undid the removing of dart.exe and added it and flutter to the antivirus exceptions
4. dart.exe is gone again
5. when reinstalling from .zip at the end it says it doesnt have permission to move dart.exe to its bin (even with antivirus off)

## Logs

"flutter upgrade"
```
'"C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

"flutter doctor -v"
```
'"C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ketrab2004** [comment]
my antivirus is bitdefender

**Comment by ketrab2004** [comment]
if i change the name of dart.exe to dart2.exe i can move it into the folder but then i can't change it's name back

**Comment by TahaTesser** [comment]
Hi @ketrab2004 
Are you using Windows? Make sure have no other program such as Windows Security deleting dart.exe on your system
Try this, add flutter to whitelist in  Bitdefender/Windows Security, restart your PC, and then  reinstall flutter

This should be addressed n https://github.com/flutter/flutter/issues/61997
Duplicate of  https://github.com/flutter/flutter/issues/50273

**Comment by ketrab2004** [comment]
now i'm having the issue that it gets stuck on
```
Running pub upgrade...
```
"flutter doctor --verbose"
```
Building flutter tool...
Running pub upgrade...
```

**Comment by ketrab2004** [comment]
```
Running pub upgrade...
Got socket error trying to find package args at https://pub.dartlang.org.
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
```

**Comment by Abhishek01039** [comment]
Hi @ketrab2004 
Disable the Antivirus while installing flutter
Thanks

**Comment by ketrab2004** [comment]
turning off my antivirus and it's firewall worked 😊
