### ISSUE TITLE
[web][IE]text is disapeared when autoscroll multi-line text fields

### ISSUE THREAD

**Issue by nttd-baozhenwang** [flutter/flutter#68175]
steps:
1. open https://gallery.flutter.dev/#/demo/text-field
2. Type multi-lines in [略歴] overflow the height
3. text is disapeared when autoscroll multi-line text fields at IE. the same issue is not occurred at chrome

**Comment by TahaTesser** [comment]
Hi @nttd-baozhenwang 
Flutter web doesn't support iE, please check for support browsers here https://flutter.dev/docs/development/platform-integration/web#which-web-browsers-are-supported-by-flutter

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
