### ISSUE TITLE
Wrong attribute in sample code in Flutter Codelabs

### ISSUE THREAD

**Issue by hieuwu** [flutter/flutter#68172]
The attribute of `animationController` should be `duration`, the current is `Duration`.
Should edit from 
```dart
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      Duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );   
```
To
```dart
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );   
```
Here are url to the issue including the screenshot:
https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..index#7

![image](https://user-images.githubusercontent.com/43868345/96078711-4e59c780-0edd-11eb-990c-95763bdb2045.png)

**Comment by pedromassangocode** [comment]
Hi @hieuwu 
Thanks for filling this issue, it looks like this was already reported https://github.com/flutter/flutter/issues/64104.

I'm going to close this as duplicate. Please follow up on that issue.
Thank you
