### ISSUE TITLE
Application can't send data to the server after a while in the background

### ISSUE THREAD

**Issue by narritt** [flutter/flutter#68188]
## Steps to Reproduce

1. Make an application, that should run in the background and pass some data to the server from the background.
2. Leave the application in the background for 30+ minutes or like that, I can't tell the exact time.

**Expected results:** 
The application sends data to the server and handles the response.

**Actual results:** 
Catching exception:
`SocketException: OS Error: Connection timed out, errno = 110, address = *my-api*.com, port = 43894`
If you put the app in the foreground - all data immediately starts sending to the server and the response handles. The issue repeats after some time in the background.

I thought it may be caused by Android's battery saver restrictions, but the issue reproduces even I choose "No restrictions". 
This happens on Xiaomi Mi8 Lite (Android 10, MiUI 12.0.3) and Samsung S20(Android 10).
I tried to use the default HTTP package and [Dio](https://pub.dev/packages/dio) - the same thing.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
The issue about Flutter and Dart plugin appeared after updating AS to 4.1, everything works OK, the described problem existed before the update.

</details>

**Comment by TahaTesser** [comment]
Hi @narritt 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by narritt** [comment]
```
Future<Map> sendDataToServer(Map data, String id) async {
  print("Sending data: $data");
  Dio dio = Dio();
  var url = baseUrl + dataRequestSuffix';
  var dataToSend = {
    "id": id,
    "data": json.encode(data)
  };
  int retries = 0;
  while (retries < 3) {
    if(retries > 0)
      await Future.delayed(Duration(seconds: 5));
    try {
      var response = await dio.post(url, data: FormData.fromMap(dataToSend));
      Map responseData = json.decode(response.data);
      printLog(Debug.serverData, "Response: $responseData");
      return responseData;
    } on DioError catch (e) {
      retries++;
      print("Send data failed $retries time, ${e.type}, ${e.message}");
    }
  }
  return Map();
}
```

"Complete reproducible minimal code sample" - sorry, I didn't fully understand. This is a function, that sends data to the server. Also, the 5 seconds delay is not 5 seconds in the background:
```
11:16:39.042 flutter : Send data failed 1 time, DioErrorType.DEFAULT, SocketException: OS Error: Connection timed out, errno = 110, address = *my-api*.com, port = 43662
11:17:15.202 flutter : Send data failed 2 time, DioErrorType.DEFAULT, SocketException: OS Error: Connection timed out, errno = 110, address = *my-api*.com, port = 43664
11:17:51.316 flutter : Send data failed 3 time, DioErrorType.DEFAULT, SocketException: OS Error: Connection timed out, errno = 110, address = *my-api*.com, port = 43668
```

**Comment by TahaTesser** [comment]
Hi @narritt 
What method/package are you using to execute this in the background? Did you experience this issue besides the two devices you mentioned? Is just Android?  What type of server are you using here?
Thank you

**Comment by narritt** [comment]
@TahaTesser, thanks for the answer!
It executes as a callback while receiving data from the Bluetooth device. I'm new in flutter and didn't find a package to keep BT connection and process data on Android and iOS, so I just lock the application in the bacground.
The issue appears only on Android with Android 10, as I can see. I don't experience it on Oneplus A3010 on Android 9.

**Comment by TahaTesser** [comment]
Hi @narritt 
It might be some configuration on Android 10 that needs to be addressed, hence not reproducing on Android 9
Can you please provide a complete reproducible minimal code sample (if possible in a repository or zip file) 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
