### ISSUE TITLE
InteractiveViewer + CustomMultiChildLayout: initially invisible widgets are not clickable

### ISSUE THREAD

**Issue by SeAl92** [flutter/flutter#68187]
I'm trying to create clickable board of widgets by **InteractiveViewer + CustomMultiChildLayout** but have some unexpectable problem: all widgets (and their's parts) which appeared on visible part of the board are totally clickable. But all other widgets which appeared on invisible part of the board are totally unclickable.

[Screen 1][1] - it is basicly visible part of board and you see what tap on one of the bricks showed snackbar.

[Screen 2][2] - it is all board with all bricks after scaling (by interactiveViewer). If tapped on bricks from screen 1 (for example - brick 6) snackbar will be appeared. But if tapped on bricks which was basicly invisible (for example - brick 2) - there was no effect. Snackbar wasn't shown and nothing work.

So tell me please - what I need to do to make all bricks clickable? What's wrong with my code?

Body of main scaffold - InteractiveViewer:

        Container(
          child: InteractiveViewer(
            boundaryMargin: EdgeInsets.all(boardSize * 2),
            onInteractionEnd: (details) {
              getBricks();
            },
            child: CustomMultiChildLayout(
              delegate: BoardLayoutDelegate(
                bricks: bricks,
              ),
              children: [
                ...getBricks(),
              ],
            ),
          ),
        );

Delegate of CustomMultiChildLayout:

      void performLayout(Size size) {
        bricks.forEach((brick) {
          //Check every brick
          if (hasChild(brick.id)) {
            layoutChild(
              brick.id,
              BoxConstraints.expand(
                width: SizePro.brickWidth,
                height: SizePro.brickHeight,
              ),
            );
            positionChild(
              brick.id,
              Offset(brick.centerX - SizePro.brickWidth / 2,
                  brick.centerY - SizePro.brickHeight / 2),
            );
          }
        });
      }

[Full project on gitlab][3]

Thank you for your attention

  [1]: https://i.stack.imgur.com/1P3ui.jpg
  [2]: https://i.stack.imgur.com/HtjQ4.jpg
  [3]: https://gitlab.com/Seednov/brickswall

**Comment by pedromassangocode** [comment]
Reproducible on latest stable channel. Not really sure if the implementation is causing the issue.

Here is a visualization of the issue, you can't click on the items that were invisible when `InteractiveViewer` was built.

Cc @justinmc 

<img width="230" height="500" src="https://user-images.githubusercontent.com/67424416/96110347-a68dcb00-0ed7-11eb-8fd0-a23b52def343.gif">


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.1 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 913ADC1E-400E-4AA0-8302-D955869FF1C9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by pedromassangocode** [comment]
Updating title to describe the issue better.

**Comment by SeAl92** [comment]
@pedromassangocode thank you so much for quick visualisation and updating! 

Waiting for solving..

**Comment by justinmc** [comment]
The solution here is to set `constrained: false` on InteractiveViewer and implement `getSize` on BoardLayoutDelegate.

Currently, your CustomMultiChildLayout is sizing itself to the size of the screen, but you are drawing outside of its size.  When you pan it and tap on one of the bricks that was initially offscreen, you are tapping on empty space, not on the CustomMutliChildLayout.  The problem could be visualized by wrapping CustomMultiChildLayout in a ClipRect:

<img width="156" alt="Screen Shot 2020-10-16 at 11 49 01 AM" src="https://user-images.githubusercontent.com/389558/96297380-9c3a0280-0fa5-11eb-847a-13f1e1f099e5.png">

By implementing getSize and returning the actual size of your widget (bigger than the screen size), Flutter know how big this widget actually wants to be.  When you also set `constrained: false`, then the screen size constraints are relaxed, and Flutter is actually able to make your widget as big as it wants.   Then all of your bricks are contained inside the CustomMultiChildLayout and able to receive events.

I'm going to update the docs a bit to explain this.  Thanks for bringing this to my attention!

**Comment by SeAl92** [comment]
Thank you for you answer!

It's working but only for right and bottom sides of the screen. Left and top almost unclickable.

I set `constrained: false`,  implemented `getSize`, colored CustomMultiChildLayout by amber and taken a new screenshot. [It's here](https://user-images.githubusercontent.com/72915376/96300880-016e1200-0fff-11eb-9ce6-2b5e42214bbe.jpg)

So how can I changing the position of interactive part of CustomMultiChildLayout?  Maybe I can set a center of sizable area?

PS [repository](https://gitlab.com/Seednov/brickswall) updated

**Comment by justinmc** [comment]
Ah I didn't think of that, you're right that this needs something else.  From here I think you need to:

  1. Render the bricks inside of the CustomMultiChildLayout.
  2. Position the CustomMultiChildLayout so that the bricks appear centered.

For 1 you'll have to modify BoardLayoutDelegate so that it draws the bricks centered in the Size that performLayout receives.  All the bricks should fully fit within the amber box in your screenshot.

Once you've done that, for 2 you need to center the CustomMultiChildLayout (inside of InteractiveViewer).   I'm sure you can do that manually with a Positioned widget.  There might be a nicer solution than that, but I don't think a Center will work.

**Comment by SeAl92** [comment]
Thought about it but also thought what this problem have another solution..

First step is ok. But the second step has got some problem. `Center` doesn't work, `Positioned` moving bricks on the CustomMultiChildLayout  without CustomMultiChildLayout:

Result after [first step](https://user-images.githubusercontent.com/72915376/96317334-849b6200-1017-11eb-8f6e-6711a520d1b5.JPG) and [second step](https://user-images.githubusercontent.com/72915376/96317560-941aab00-1017-11eb-823a-c39e61208083.JPG)

So both of them positioned CustomMultiChildLayout's left-top-corner into left-top-corner of initial screen..

My code for this:

```Dart
InteractiveViewer(
        constrained: false,
        scaleEnabled: true,
        minScale: 0.1,
        maxScale: 10.0,
        boundaryMargin: EdgeInsets.all(boardSize),
        onInteractionEnd: (details) {
          getBricks();
        },
        child: Container(
          color: Colors.amber,
          width: boardSize,
          height: boardSize,
          child: Stack(
            children: [
              Positioned(
                width: boardSize,
                height: boardSize,
                left: boardSize / 2,
                child: CustomMultiChildLayout(
                  delegate: BoardLayoutDelegate(
                    bricks: bricks,
                    boardSize: boardSize,
                    offset: (boardSize / 2) - (SizePro.screenWidth / 2),
                  ),
                  children: [
                    ...getBricks(),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
```


What else I can do with `Positioned` to achieve needed result? Or maybe I need to use another widget?

**Comment by justinmc** [comment]
I updated the repo but I think something else has changed as I had trouble getting the bricks to be visible.

Can you not position the bricks using the `left` parameter of Positioned?  Maybe make it negative.

**Comment by SeAl92** [comment]
Thank you! But I don't see any updates in repo..

**Comment by justinmc** [comment]
Sorry, I meant that I did `git pull` in my local checkout of your repo, but couldn't get the bricks onscreen.

**Comment by SeAl92** [comment]
Yeah, sorry, it's happened because of `positioned`. I removed all about positioned and updated repo. Bricks are visible now.

**Comment by justinmc** [comment]
Ok I see, thanks for updating that.  Unfortunately I'm having trouble centering it using widgets as well due to the infinite constraints...  I think what you'll need to do is to use [TransformationController](https://master-api.flutter.dev/flutter/widgets/TransformationController-class.html) to set the initial translation of your child.  So with a default transformation matrix of Matrix4.identity, the child will be aligned to the top left corner of the screen, as we see now.  If instead you set the value of transformationController to `Matrix4.identity()..translate(-boardSize / 2)`, then it should be centered.

**Comment by SeAl92** [comment]
It's exactly what I need! Thank you so much!

**Comment by justinmc** [comment]
Awesome!  Glad we got it. 🎉
