### ISSUE TITLE
Device Info Memory size

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#68181]
## Use case
I want to enable lite mode on Google map if device memory is less than 1.5 GB
because I got crash issues and the app is slow on iPad 4 which has only 1 GB memory ram.

## Proposal

I wonder if device_info plugin could add the actual device ram memory size?

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
