### ISSUE TITLE
Document that you can call runApp many times

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6818]
It is typical for a Flutter app to have async init (such as initializing certain Flutter plugins). It would be nice for the framework to support some sort of splash screen that can be inserted before runApp().

Currently we do this:

```Dart
void main() {
  someFuture.then((_) => runApp(new MyApp()));
}
```

Unfortunately, until the async resource is resolved, the screen is blank. Perhaps something like this can be supported:

```Dart
void main() {
  runApp(
    splash: new SplashWidget(),
    resolve: someFuture,
    app: new MyApp(),
  );
}
```

This can be easily internalized within the app itself but since it is a common pattern, I wanted to file this as an improvement to the current API.

**Comment by sethladd** [comment]
Curious, just displaying a static image?

**Comment by mehmetf** [comment]
For flexibility, it would be better to allow a full screen widget. The client should be able to choose whether to display a static image or an animation loop or something else.

To be clear, this isn't hard to do w/o flutter explicitly supporting it. For others who stumble on this, here's a way to do it in the app itself:

```Dart
class MyApp extends StatefulWidget {
  final Future<Null> initializer;

  MyApp(this.initializer);

  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _isInited;

  @override
  void initState() {
    super.initState();
    _isInited = config.initializer == null;
  }

  @override
  Widget build(BuildContext context) {
    if (_isInited) {
      return new MyActualApp();
    } else {
      config.initializer.then((_) {
        setState(() {
          _isInited = true;
        });
      });
      return new _SplashScreen();
    }
  }
}

class _SplashScreen extends StatelessWidget {
  // My splash screen
}
```

**Comment by abarth** [comment]
You can call `runApp` as many times as you like.  One way to approach this issue is to call `runApp` right away with your splash screen widget and then later call `runApp` again once your async initialization is complete.

```dart
main() async {
  runApp(new SplashScreen());
  var foo = await init();
  runApp(new FullApp(foo: foo));
}
```

**Comment by mehmetf** [comment]
I did not know that @abarth , thanks! That does make the API much nicer so I will close this.

**Comment by Hixie** [comment]
Let's make sure this is documented in the relevant dartdocs.
