### ISSUE TITLE
Fire didChangeAppLifecycleState on closing Android notification drawer

### ISSUE THREAD

**Issue by JustChris** [flutter/flutter#68184]
## Use case

didChangeAppLifecycleState doesn't fire when user opens/closes Android Notification Drawer.
I am checking some service states like location service when user resumes back to the app via didChangeAppLifecycleState, so I can ask the user to enable the corresponding service.
But when the user deactivates location service via Android notification drawer, I can not catch this event.

## Proposal

I would be great, if didChangeAppLifecycleState would also fire when the user closes the Android notification drawer.

**Comment by pedromassangocode** [comment]
Hi @JustChris 
`didChangeAppLifecycleState` is used for exactly that: listen for app lifecycle states, and not for system events.
You can create a plugin and use it in your project. I'm not really sure if this is even possible in the native side.

What you can do is to create a plugin to listen for location services state changes if that is possible.
