### ISSUE TITLE
flutter run

### ISSUE THREAD

**Issue by Ahmed-Mohammed-Anwar** [flutter/flutter#68186]
can any one help me to solve the problem please, i attached a pic about the error
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/53219477/96100795-0d5db500-0ed5-11eb-8fc5-392dbcfe30a6.png">

**Comment by TahaTesser** [comment]
Hi @Ahmed-Mohammed-Anwar 
Please read the above error message about JAVA_HOME, it's required to set up on Android Studio 4.1 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Abhishek01039** [comment]
Hi @Ahmed-Mohammed-Anwar 
please set the JAVA HOME variable in your PC.
you can refer to this https://stackoverflow.com/questions/32241179/setting-up-enviromental-variables-in-windows-10-to-use-java-and-javac
Thanks

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
