### ISSUE TITLE
[web] Content Security Policy violation error for main.dart.js

### ISSUE THREAD

**Issue by kaustubhcholkar** [flutter/flutter#68193]
The JS file generated for flutter web seems to be using Function() calls which are generally flagged as a security risk. Attached is a screenshot of the error thrown if the Content Security Policy forbids 'unsafe-eval'.

Is there any plan to get rid of the eval() code in the JS file? And any temporary workaround to remove the eval() functions in the script?

Flutter 1.22.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (2 weeks ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

![image](https://user-images.githubusercontent.com/800354/96115681-f59e2500-0f04-11eb-8466-ce58bc66862b.png)

**Comment by TahaTesser** [comment]
Hi @kaustubhcholkar 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by jonahwilliams** [comment]
@kaustubhcholkar see the output of `flutter build web -h`:

```
Build a web application bundle.
...

    --csp                      Disable dynamic generation of code in the generated output. This is necessary to satisfy CSP restrictions (see http://www.w3.org/TR/CSP/).


Run "flutter help" to see global options.
``` 

You need to pass the --csp option.

**Comment by kaustubhcholkar** [comment]
Thanks @jonahwilliams . This fixed the issue.
