### ISSUE TITLE
[pigeon] StandardFileSystem only supports file:* and data:* URIs

### ISSUE THREAD

**Issue by ipipip1735** [flutter/flutter#68196]
![image](https://user-images.githubusercontent.com/12948715/96121582-d910e580-0f22-11eb-9bde-de3787603846.png)

![image](https://user-images.githubusercontent.com/12948715/96121694-ffcf1c00-0f22-11eb-8444-c2694665d3a8.png)

```
E:\Program\AndroidStudio\Flutter\basics>flutter pub run pigeon ^
More? --input pigeons/message.dart ^
More? --dart_out lib/pigeon.dart ^
More? --objc_header_out ios/Runner/pigeon.h ^
More? --objc_source_out ios/Runner/pigeon.m ^
More? --java_out ./android/app/src/main/java/dev/flutter/pigeon/Pigeon.java ^
More? --java_package "mine.pigeon"
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: /C:/Users/ADMINI~1/AppData/Local/Temp/ee87bb06/_pigeon_temp_.dart:1:8: Error: Error when reading 'e
:ProgramAndroidStudioFlutter%08asicspigeonsmessage.dart': StandardFileSystem only supports file:* and data:* URIs
import 'E:\Program\AndroidStudio\Flutter\basics\pigeons\message.dart';
       ^
pub finished with exit code 255








=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
the code created is incorrect
`import 'E:\Program\AndroidStudio\Flutter\basics\pigeons\message.dart';`

```

**Comment by TahaTesser** [comment]
Hi @ipipip1735 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by ipipip1735** [comment]
flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1139], locale zh-CN)
    • Flutter version 1.20.4 at D:\SoftWare\Flutter\flutter-1.20.4
    • Framework revision fba99f6cf9 (4 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\SoftWare\Android\SDK
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\SoftWare\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

[√] Android Studio (version 4.0)
    • Android Studio at D:\SoftWare\Android\AndroidStudio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
![image](https://user-images.githubusercontent.com/12948715/96192264-40a55000-0f78-11eb-893f-af4bd441d73e.png)




=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[code sample]
pigeons/message.dart
```
import 'package:pigeon/pigeon.dart';

class SearchRequest {
  String query;
}

class SearchReply {
  String result;
}

@HostApi()
abstract class Api {
  SearchReply search(SearchRequest request);
}
```



[Reproducible Example]
https://github.com/ipipip1735/one.git



=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[Error]
```
flutter pub run pigeon ^
  --input pigeons/message.dart ^
  --dart_out lib/pigeon.dart ^
  --objc_header_out ios/Runner/pigeon.h ^
  --objc_source_out ios/Runner/pigeon.m ^
  --java_out ./android/app/src/main/java/dev/flutter/pigeon/Pigeon.java ^
  --java_package "dev.flutter.pigeon"
```

```
E:\Program\Flutter\one>flutter pub run pigeon ^
More?   --input pigeons/message.dart ^
More?   --dart_out lib/pigeon.dart ^
More?   --objc_header_out ios/Runner/pigeon.h ^
More?   --objc_source_out ios/Runner/pigeon.m ^
More?   --java_out ./android/app/src/main/java/dev/flutter/pigeon/Pigeon.java ^
More?   --java_package "dev.flutter.pigeon"
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: /C:/Users/ADMINI~1/AppData/Local/Temp/5d0452a4/_pigeon_temp_.dart:1:8: Error: Error when reading 'e
:ProgramFlutteronepigeonsmessage.dart': StandardFileSystem only supports file:* and data:* URIs
import 'E:\Program\Flutter\one\pigeons\message.dart';
       ^
pub finished with exit code 255
```
![image](https://user-images.githubusercontent.com/12948715/96193249-5fa4e180-0f7a-11eb-818c-9234547210ed.png)

**Comment by TahaTesser** [comment]
Hi @ipipip1735 
Looks like you have a special character in your path 
![image](https://user-images.githubusercontent.com/48603081/96239601-8afcf000-0fbd-11eb-83e3-7da5febdbd5c.png)
Can you please change your path and try again?
I am not getting the same error using your code repository

**Comment by ipipip1735** [comment]
Create flutter plugin
![image](https://user-images.githubusercontent.com/12948715/96312202-b45d6080-103d-11eb-8567-8331767bd36c.png)


Declare  dart API  for  platform(Android / iOS) in  .dart file

![image](https://user-images.githubusercontent.com/12948715/96312302-e53d9580-103d-11eb-896e-e0ac4db6aac8.png)



there is an error using `flutter pub run pigeon`.
in windows 10, `flutter pub run pigeon` creates a .dart file in Windows's temporary directory.
it seems that `import absolute path` is incorrect syntax in temp .dart created.

compiler says `StandardFileSystem only supports file:* and data:* URIs`


there is no example using `import absolute path` in [doc](https://dart.dev/guides/libraries/create-library-packages)





i try to use `/` as Path Delimiter, but it doesn't work.
![image](https://user-images.githubusercontent.com/12948715/96319513-7282e900-1042-11eb-8f38-c93a9d74f2c9.png)

**Comment by ipipip1735** [comment]
in youtube, i find no video about making API files for android/iOS with pigeon. it seems that pigeon isn't a well-known plugin.

**Comment by TahaTesser** [comment]
Trying on WIndows, I am getting the following error with your  project
```
C:\Users\Taha\AndroidStudioProjects\one>flutters pub run pigeon ^ --input ./pigeons/message.dart ^ --dart_out lib/pigeon.dart ^ --objc_header_out ios/Runner/pigeon.h ^ --objc_source_out ios/Runner/pigeon.m ^ --
java_out ./android/app/src/main/java/dev/flutter/pigeon/Pigeon.java ^ --java_package "dev.flutter.pigeon"
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: ../../AppData/Local/Temp/9d5269b2/_pigeon_temp_.dart:1:8: Error: Error when reading '../../AppData/Local/Temp/9d5269b2/........AndroidStudioProjectsonepigeonsmess
age.dart': The system cannot find the file specified.

import '..\..\..\..\AndroidStudioProjects\one\pigeons\message.dart';
       ^
pub finished with exit code 255
```



Same as here https://github.com/flutter/flutter/issues/67227#issuecomment-711196865

CC @gaaclarke

**Comment by creativecreatorormaybenot** [comment]
I am wondering if I introduced this 🤔 

I find it strange that the implementation was working for me on Windows when I made #216, however, now I also see this error.

**Comment by gaaclarke** [comment]
@creativecreatorormaybenot don't worry about it, we need to get Windows CI tests at some point.  Not your fault we don't have those yet.  I'll get a windows machine setup later today, I'm sure it's something silly.

**Comment by gaaclarke** [comment]
PR is up for review that fixes this.  It turns out that Dart on windows didn't like import statements that use backslashes.  I would have expected that to work.  It might be that different versions of dart behave differently.

**Comment by gaaclarke** [comment]
published fix in 0.1.13

**Comment by ipipip1735** [comment]
if the same issue still exists when you update the lastest pigeon, also try to the following way.


1.locate pigeon.dart.
on windows:
`Your FlutterSDK\.pub-cache\hosted\pub.dartlang.org\pigeon-0.1.13\bin\pigeon.dart`




2.modify pigeon.dart to with hard code.
from:
```
  final String code = """$importLine
import 'dart:io';
import 'dart:isolate';
import 'package:pigeon/pigeon_lib.dart';

void main(List<String> args, SendPort sendPort) async {
  sendPort.send(await Pigeon.run(args));
}
""";
```
to:
```
final String code = """
import '/E:/Program/AndroidStudio/Flutter/FTA/flutter_plugin_one/pigeons/message.dart';
import 'dart:io';
import 'dart:isolate';
import 'package:pigeon/pigeon_lib.dart';

void main(List<String> args, SendPort sendPort) async {
  sendPort.send(await Pigeon.run(args));
}
""";
```
here, absolute path begins with `/`. such as:
`import '/E:/Program/AndroidStudio/Flutter/FTA/flutter_plugin_one/pigeons/message.dart';`



3. run `flutter clean`




4. re-add  dependency in pubspec.yaml, then `flutter pub get`
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^0.1.13
```




5. if `ios/Runner/`  and `./android/app/` doesn't exist in skeleton files, make folders.
iOS: `ios/Runner`  
Android: `android/src/main/java/dev/flutter/pigeon/`







6. run the following command:
```
flutter pub run pigeon \
  --input pigeons/message.dart \
  --dart_out lib/pigeon.dart \
  --objc_header_out ios/Runner/pigeon.h \
  --objc_source_out ios/Runner/pigeon.m \
  --java_out ./android/src/main/java/dev/flutter/pigeon/Pigeon.java \
  --java_package "dev.flutter.pigeon"
```


updateing to 0.1.13 doesn't work for me, so i have to use hard code.
hope this is helpful to you.

**Comment by gaaclarke** [comment]
@ipipip1735 I think there were 2 issues, only one got fixed.
1) Dart doesn't like import statements with backslashes (fixed)
1) Windows can't do relative paths between drives (not verified, not fixed, I think this is your current issue)

Can you verify that pigeon works if the input file is on the same drive as your temp directory (probably c:)?  We have an issue for that here https://github.com/flutter/flutter/issues/68583
