### ISSUE TITLE
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.

### ISSUE THREAD

**Issue by Jeet1912** [flutter/flutter#68195]
```
When the exception was thrown, this was the stack
#2      _NestedOuterBallisticScrollActivity.applyMoveTo 
package:flutter/…/widgets/nested_scroll_view.dart:1606
#3      BallisticScrollActivity._tick 
package:flutter/…/widgets/scroll_activity.dart:541
#4      AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:136
#5      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:796
#6      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:238
...
The AnimationController notifying listeners was: AnimationController#3b696(▶ 371.049; for _NestedOuterBallisticScrollActivity)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by Abhishek01039** [comment]
Hi @Jeet1912 
can you please provide `flutter run -v`, flutter doctor -v`, and minimal reproduction code?
Thanks.

**Comment by Jeet1912** [comment]
**flutter run -v**
![Screenshot 2020-10-15 at 6 31 12 PM](https://user-images.githubusercontent.com/51080094/96129721-a06a0f80-0f14-11eb-8634-2ad92f627024.png)

**flutter doctor -v**
![Screenshot 2020-10-15 at 6 35 24 PM](https://user-images.githubusercontent.com/51080094/96130186-32721800-0f15-11eb-9f34-458d0dd55cde.png)

**Minimal reproduction code**
Scaffold's body: 
CustomScrollView(
        slivers: [
          SliverPersistentHeader(
            pinned: true,
            floating: true,
            delegate: PersistentHeader(context: context, petPic: widget.petPic),
          ),
          SliverPadding(
            padding: EdgeInsets.only(
              top: 30,
            ),
          ),
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.only(
                top: 15.0,
                left: 15.0,
              ),
              child: Container(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(left: 5.0),
                      child: Text(
                        "Filters",
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Container(
                      height: 100.0,
                      child: ListView(
                        scrollDirection: Axis.horizontal,
                        padding: EdgeInsets.all(5),
                        children: <Widget>[
                          filterCategory("Female"),
                          filterCategory("Golden\nRetriever"),
                          filterCategory("3 months"),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 15,
              ),
              child: ownerBox(),
            ),
          ),
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.symmetric(
                vertical: 10.0,
                horizontal: 20,
              ),
              child: Container(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "About",
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Padding(
                      padding: const EdgeInsets.only(left: 10.0),
                      child: Text(
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                        style: TextStyle(
                          fontSize: 15.0,
                          height: 1.5,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: MediaQuery.of(context).size.height / 10,
            ),
          )
        ],
      ),



Persistent Header:

class PersistentHeader extends SliverPersistentHeaderDelegate {
  final BuildContext context;
  final String petPic;

  PersistentHeader({@required this.context, @required this.petPic});
  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Stack(fit: StackFit.expand, children: [
      Hero(
        tag: petPic,
        child: Container(
          height: MediaQuery.of(context).size.width,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(
                30,
              ),
              bottomRight: Radius.circular(
                30,
              ),
            ),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(
                30,
              ),
              bottomRight: Radius.circular(
                30,
              ),
            ),
            child: Opacity(
              opacity: responsiveOpacity(shrinkOffset),
              child: Image(
                image: AssetImage(
                  petPic,
                ),
                filterQuality: FilterQuality.high,
                fit: BoxFit.cover,
              ),
            ),
          ),
        ),
      ),
      Positioned(
        bottom: 20,
        left: 20,
        child: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                "Marley",
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: Colors.white.withOpacity(
                    responsiveOpacity(shrinkOffset),
                  ),
                ),
              ),
              Text(
                "Golden Retriever",
                style: TextStyle(
                  color: Colors.white.withOpacity(
                    responsiveOpacity(
                      shrinkOffset,
                    ),
                  ),
                  fontSize: 15,
                ),
              ),
            ]),
      ),
      Positioned(
        bottom: 20,
        right: 20,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Text(
              "3 months",
              style: TextStyle(
                fontSize: 15.0,
                color: Colors.white.withOpacity(
                  responsiveOpacity(
                    shrinkOffset,
                  ),
                ),
              ),
            ),
            Row(
              children: <Widget>[
                Icon(
                  Icons.location_on,
                  color: Colors.white.withOpacity(
                    responsiveOpacity(
                      shrinkOffset,
                    ),
                  ),
                ),
                Text(
                  "Bangalore",
                  style: TextStyle(
                    color: Colors.white.withOpacity(
                      responsiveOpacity(
                        shrinkOffset,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
      Positioned(
        left: 0,
        right: 0,
        top: 0,
        child: Container(
          decoration: BoxDecoration(
            color: makeStickyHeaderBgColor(shrinkOffset),
            borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(30),
              bottomRight: Radius.circular(30),
            ),
          ),
          // Background color
          child: SafeArea(
            bottom: false,
            child: Container(
              height: 55,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Padding(
                    padding: const EdgeInsets.only(left: 12.0),
                    child: IconButton(
                      icon: Icon(
                        Icons.arrow_back_ios,
                        color: this.makeStickyHeaderTextColor(
                            shrinkOffset, true), // Return icon color
                      ),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(right: 20.0),
                    child: Text(
                      "Marley",
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.w500,
                        color: this.makeStickyHeaderTextColor(
                            shrinkOffset, false), // Title color
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(right: 12.0),
                    child: FavoriteButton(),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    ]);
  }

  double responsiveOpacity(double shrinkOffset) {
    return 1.0 - max(0.0, shrinkOffset) / maxExtent;
  }

  Color makeStickyHeaderBgColor(shrinkOffset) {
    final int alpha = (shrinkOffset / (this.maxExtent - this.minExtent) * 255)
        .clamp(0, 255)
        .toInt();
    return Color.fromARGB(alpha, 185, 129, 93);
  }

  Color makeStickyHeaderTextColor(shrinkOffset, isIcon) {
    if (shrinkOffset <= 50) {
      return isIcon ? Colors.grey : Colors.transparent;
    } else {
      final int alpha = (shrinkOffset / (this.maxExtent - this.minExtent) * 255)
          .clamp(0, 255)
          .toInt();
      return Color.fromARGB(alpha, 255, 255, 255);
    }
  }

  @override
  OverScrollHeaderStretchConfiguration get stretchConfiguration =>
      OverScrollHeaderStretchConfiguration();

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => MediaQuery.of(context).size.width;

  @override
  double get minExtent => 80;
}

**Comment by TahaTesser** [comment]
Hi @Jeet1912 
Can you please simplify the code, `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Instead of screenshots 
Thank you

**Comment by Abhishek01039** [comment]
Maybe the duplication of https://github.com/flutter/flutter/issues/63825

**Comment by Jeet1912** [comment]
**flutter run -v**

] flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
[   +2 ms] flutter: The following assertion was thrown while notifying listeners for AnimationController:
[   +2 ms] flutter: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result':
[        ] flutter: is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      _NestedOuterBallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/nested_scroll_view.dart:1606:12)
[        ] flutter: #3      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:541:10)
[        ] flutter: #4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:136:19)
[        ] flutter: #5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:796:5)
[        ] flutter: #6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[        ] flutter: #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[        ] flutter: #8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1031:11)
[   +1 ms] flutter: #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] flutter: #10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1029:17)
[        ] flutter: #11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:963:5)
[        ] flutter: #15     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #16     _beginFrame (dart:ui/hooks.dart:192:3)
[   +4 ms] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter:
[        ] flutter: The AnimationController notifying listeners was:
[        ] flutter:   AnimationController#ef363(▶ 278.977; for _NestedOuterBallisticScrollActivity)
[  +21 ms] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +8 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +14 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +11 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +22 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +10 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +21 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +12 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +16 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +16 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[  +18 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.
[   +2 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1606 pos 12: 'result': is not true.


**flutter doctor -v**

[✓] Flutter (Channel master, 1.23.0-14.0.pre.10, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-14.0.pre.10 at /Users/jxxt/flutter
    • Framework revision 6620f831e9 (9 days ago), 2020-10-06 18:15:15 -0700
    • Engine revision 7e6191de07
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jxxt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Iphone (6) (mobile) • 3e5b2a5d7485d3a52450cd22fd55ef6ad3679516 • ios • iOS 12.4.8

• No issues found!


***Minimal Reproduction Code:***

**main.dart**
import 'package:flutter/material.dart';

import 'persistent_header.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverPersistentHeader(
                pinned: true,
                floating: true,
                delegate: PersistentHeader(context: context),
              ),
            ),
          ];
        },
        body: Builder(
          builder: (BuildContext context) {
            return CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      vertical: 10.0,
                      horizontal: 20,
                    ),
                    child: Container(
                      child: Column(
                        children: [
                          Text(
                            "About",
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          SizedBox(
                            height: 10,
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}


**persistent_header.dart**
import 'dart:math';

import 'package:flutter/material.dart';

class PersistentHeader extends SliverPersistentHeaderDelegate {
  final BuildContext context;

  PersistentHeader({@required this.context});
  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(
      height: MediaQuery.of(context).size.width,
      child: Opacity(
        opacity: responsiveOpacity(shrinkOffset),
        child: Image(
          image: AssetImage(
            'assets/Home_image.png',
          ),
          fit: BoxFit.cover,
        ),
      ),
    );
  }

  double responsiveOpacity(double shrinkOffset) {
    return 1.0 - max(0.0, shrinkOffset) / maxExtent;
  }

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => MediaQuery.of(context).size.width;

  @override
  double get minExtent => 80;
}

**Comment by TahaTesser** [comment]
Hi @Jeet1912 
I tried a lot of back and forth but no exception using your code sample, I only replaced asset image with network image 
[video.zip](https://github.com/flutter/flutter/files/5390330/video.zip)
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

import 'dart:math';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverPersistentHeader(
                pinned: true,
                floating: true,
                delegate: PersistentHeader(context: context),
              ),
            ),
          ];
        },
        body: Builder(
          builder: (BuildContext context) {
            return CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      vertical: 10.0,
                      horizontal: 20,
                    ),
                    child: Container(
                      child: Column(
                        children: [
                          Text(
                            "About",
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          SizedBox(
                            height: 10,
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

class PersistentHeader extends SliverPersistentHeaderDelegate {
  final BuildContext context;

  PersistentHeader({@required this.context});
  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(
      height: MediaQuery.of(context).size.width,
      child: Opacity(
        opacity: responsiveOpacity(shrinkOffset),
        child: Image(
          image: NetworkImage(
            'https://i.imgur.com/QCNbOAo.png',
          ),
          fit: BoxFit.cover,
        ),
      ),
    );
  }

  double responsiveOpacity(double shrinkOffset) {
    return 1.0 - max(0.0, shrinkOffset) / maxExtent;
  }

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => MediaQuery.of(context).size.width;

  @override
  double get minExtent => 80;
}


```

</details> 



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.77, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.23.0-19.0.pre.77 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 046cb5ad07 (5 hours ago), 2020-10-15 23:47:06 -0400
    • Engine revision 1bc025d6cb
    • Dart version 2.11.0 (build 2.11.0-222.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.0.1
    • iPhone 11 (mobile)     • 193EBBC9-CC2A-4477-B8A0-A5F12BB51400 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details> 

Meanwhile this odes reproducible https://github.com/flutter/flutter/issues/63825

**Comment by Jeet1912** [comment]
Hello @TahaTesser
Strangely, even I don't face that error anymore. So I decided to fill up the screen text. The error is thrown this time.


<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

import 'persistent_header.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverPersistentHeader(
                pinned: true,
                floating: true,
                delegate: PersistentHeader(context: context),
              ),
            ),
          ];
        },
        body: Builder(
          builder: (BuildContext context) {
            return CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      vertical: 10.0,
                      horizontal: 20,
                    ),
                    child: Container(
                      child: Column(
                        children: [
                          Text(
                            "About",
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          SizedBox(
                            height: 10,
                          ),

                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),

                          // Add the following widget to main.dart so that it covers your screen (It's a guess)

                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}


```
</details>



<details> 
<summary>flutter doctor -v</summary> 

```dart


[✓] Flutter (Channel master, 1.23.0-14.0.pre.10, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-14.0.pre.10 at /Users/jxxt/flutter
    • Framework revision 6620f831e9 (9 days ago), 2020-10-06 18:15:15 -0700
    • Engine revision 7e6191de07
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jxxt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Iphone (6) (mobile) • 3e5b2a5d7485d3a52450cd22fd55ef6ad3679516 • ios • iOS 12.4.8

```
</details>


**Demos**
> Asset image 
[video_iphon5.mov.zip](https://github.com/flutter/flutter/files/5390956/video_iphon5.mov.zip)

> Network image
[IMG_2980.MOV.zip](https://github.com/flutter/flutter/files/5391128/IMG_2980.MOV.zip)

**Comment by TahaTesser** [comment]
Hi @Jeet1912 
I just tried on physical as well as on iPhone  8 and 11 simulator, there is no issue 
<details> 
<summary>complete code sample</summary> 

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverPersistentHeader(
                pinned: true,
                floating: true,
                delegate: PersistentHeader(context: context),
              ),
            ),
          ];
        },
        body: Builder(
          builder: (BuildContext context) {
            return CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      vertical: 10.0,
                      horizontal: 20,
                    ),
                    child: Container(
                      child: Column(
                        children: [
                          Text(
                            "About",
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          SizedBox(
                            height: 10,
                          ),

                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),

                          // Add the following widget to main.dart so that it covers your screen (It's a guess)

                          Padding(
                            padding: const EdgeInsets.only(left: 10.0),
                            child: Text(
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et odio pellentesque diam volutpat commodo sed egestas. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.",
                              style: TextStyle(
                                fontSize: 15.0,
                                height: 1.5,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

class PersistentHeader extends SliverPersistentHeaderDelegate {
  final BuildContext context;

  PersistentHeader({@required this.context});
  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(
      height: MediaQuery.of(context).size.width,
      child: Opacity(
        opacity: responsiveOpacity(shrinkOffset),
        child: Image(
          image: NetworkImage(
            'https://i.imgur.com/nbUqZPw.jpg',
          ),
          fit: BoxFit.cover,
        ),
      ),
    );
  }

  double responsiveOpacity(double shrinkOffset) {
    return 1.0 - max(0.0, shrinkOffset) / maxExtent;
  }

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => MediaQuery.of(context).size.width;

  @override
  double get minExtent => 80;
}

```

</details> 

I see you're on more than week old master channel
\Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by phijma** [comment]
Same problem for me.
