### ISSUE TITLE
We need a shortcut to delete all comments of a specific page at once.

### ISSUE THREAD

**Issue by seadhant** [flutter/flutter#68205]
For Example- 
We should be able to delete all the comments in pages like `pubspec.yaml` safely with only a simple shortcut as it is delicate to indentation, so to make life easier for users who already have read all the guidelines.

**Comment by sidrao2006** [comment]
Hey @seadhant , since this is not an issue with the flutter tool, please close this it.

This issue would be suitable in the following repos -

- https://github.com/Dart-Code/Dart-Code for VSCode
- https://github.com/flutter/flutter-intellij for IntelliJ

Thanks

**Comment by TahaTesser** [comment]
Hi @seadhant 
This is not related to flutter or flutter plugins, you asking for a feature that is general to comments in a YAML file and YAML with comments exist out of flutter too.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
