### ISSUE TITLE
Looks like something went wrong while downloading the dart sdk. Can you delete the `cache` folder inside `bin` and then run `flutter doctor` again? What's the output?

### ISSUE THREAD

**Issue by Mr-Perfectuz** [flutter/flutter#68211]
Looks like something went wrong while downloading the dart sdk. Can you delete the `cache` folder inside `bin` and then run `flutter doctor` again? What's the output?

Are you by any chance behind a firewall (or using a proxy) that might be blocking the download of the dart sdk?

_Originally posted by @goderbauer in https://github.com/flutter/flutter/issue_comments/339395571_

**Comment by Mr-Perfectuz** [comment]
this makes terminal stuck at  Building flutter tool...
Running pub upgrade...

**Comment by darshankawar** [comment]
@Mr-Perfectuz 
Please provide `flutter doctor -v` and elaborate on what are you trying to do when you get this error. The original link you pasted above throws 404, so if you have the proper link of the issue, please provide that too.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
