### ISSUE TITLE
[Web] ClipRect offsets image by some constant value in Y-direction

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#68213]
When using `ClipRect` in combination with an Image, the Image is offset by some constant value in y-direction.

In this code snipped, I overlay two images, you would expect to only see the blue image on top of the stack.

        Stack(
          alignment: AlignmentDirectional.centerEnd,
          children: [
            Image.network(
              "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Square_-_black_simple.svg/1200px-Square_-_black_simple.svg.png",
              color: Colors.red
            ),
            ClipRect(
              child: Image.network(
                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Square_-_black_simple.svg/1200px-Square_-_black_simple.svg.png",
                color: Colors.blue
              ),
            ),
          ]
        ),

however this is the result

![Bildschirmfoto 2020-10-15 um 17 55 36](https://user-images.githubusercontent.com/38528004/96154938-a6a9bd00-0f0f-11eb-91a2-0a3e438f3d1a.png)

as you can see, the Image that is wrapped in a `ClipRect` is offset in the y-direction. This only occurs on web.

**Comment by darshankawar** [comment]
Issue replicable on latest beta on web. Works well on Android.

![68213](https://user-images.githubusercontent.com/67046386/96226638-95fd5380-0fb0-11eb-8f6f-cd439d135003.png)
<img width="647" alt="Screenshot 2020-10-16 at 1 05 47 PM" src="https://user-images.githubusercontent.com/67046386/96226639-972e8080-0fb0-11eb-9f47-1586425ad288.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d408d302e2 (2 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android
      11 (API 30) (emulator)
    • Web Server (web)            • web-server       • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome           • web-javascript • Google
      Chrome 86.0.4240.80

• No issues found!

```

</details>

**Comment by ferhatb** [comment]
Landed in master.
