### ISSUE TITLE
FlutterError messages missing explanation 

### ISSUE THREAD

**Issue by Peet-A** [flutter/flutter#68210]
when debugging , I am facing an issue , the debug error message  is missing the explanation and details. here is the debug console output :
<img width="807" alt="Screen Shot 2020-10-15 at 4 51 05 PM" src="https://user-images.githubusercontent.com/22204356/96151503-bf17d880-0f0b-11eb-9485-ba549d031e41.png">
```
Flutter Doctor
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-EG) • Flutter version 1.22.1 at /Users/XXXXX/flutter • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700 • Engine revision 75bef9f6c8 • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2) • Android SDK at /Users/XXXXXX/Library/Android/sdk • Platform android-29, build-tools 29.0.2 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593) • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6) • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 11.6, Build version 11E708 • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin version 50.0.1 • Dart plugin version 193.7547 • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.1) • IntelliJ at /Applications/IntelliJ IDEA CE.app • Flutter plugin version 34.0.4 • Dart plugin version 191.6183.88

[✓] VS Code (version 1.48.2) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.12.2

[✓] Connected device (3 available) • iPhone 11 Pro Max (mobile) • AECA9290-F1AE-45BF-8D0C-6D6A7F6B648D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Comment by Abhishek01039** [comment]
Hi @Peet-A 
can you please provide `flutter run -v` and minimal reproduction code?
Thanks

**Comment by TahaTesser** [comment]
Hi @Peet-A 
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
