### ISSUE TITLE
Selecting a space should select previous word in SelectableText on mobile

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#68226]
Issue https://github.com/flutter/flutter/issues/67634 mentioned this feature for CupertinoTextField, and it was fixed in https://github.com/flutter/flutter/pull/68227 for everything except for SelectableText.  We should add this functionality to SelectableText on mobile.

To reproduce, run an app with SelectableText, such as the example below.  Double tap on the space between the "blah"s.  On mobile, the first blah should be selected, but instead the space is selected.

<details>

<summary>Example app</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SelectableText(' blah blah'),
      ),
    );
  }
}
```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

![68226](https://user-images.githubusercontent.com/67046386/96223276-46685900-0fab-11eb-805d-b424979e48cf.png)

**Comment by Renzo-Olivares** [comment]
@justinmc Hello, I was wondering if anyone was actively working on this, and if not could I work on it?

**Comment by justinmc** [comment]
@Renzo-Olivares Nope it's all you.  I'll assign you.  Thanks Renzo!

FYI I'm currently working on refactoring how EditableText and RenderEditable manipulate text editing state ([WIP design doc](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit), but it's probably at least a month out right now.  Some small platform-specific behaviors like this can be hard to get right without breaking anything else right now, which is why I want to refactor.  If this issue seems very fiddly and takes a long time, you may consider waiting until the refactor is done.  If it's a relatively quick fix though, go for it.

**Comment by Renzo-Olivares** [comment]
@justinmc Awesome thanks for letting me know. I'll still give it a shot.
