### ISSUE TITLE
[doc] Null safety in InputDecorator's Properties

### ISSUE THREAD

**Issue by Abhishek01039** [flutter/flutter#68223]
Null safety is there in the constructor of InputDecoration(https://api.flutter.dev/flutter/material/InputDecoration-class.html) but this does not reflect the Documentation of it as the documentation of BoxDecoration(https://api.flutter.dev/flutter/painting/BoxDecoration-class.html.)

Thanks.

**Comment by amanv8060** [comment]
https://master-api.flutter.dev/flutter/material/InputDecorator-class.html ,is that what  you are looking for? .

**Comment by Abhishek01039** [comment]
Hello @amanv8060 I am talking about https://api.flutter.dev/flutter/material/InputDecoration-class.html

**Comment by amanv8060** [comment]
Those are Stable docs 
Stable file for input decoration : https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/material/input_decorator.dart

Stable file for box decoration : https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/painting/box_decoration.dart

you can clearly see that input decoration of stable does not have null safety yet  and so do the docs .

**Comment by Abhishek01039** [comment]
Yes that's why I have done only for the master branch 
And the docs are shown for `InputDecoration` there is not for stable branch https://github.com/flutter/flutter/blob/f30b7f4db9/packages/flutter/lib/src/material/input_decorator.dart#L2478
