### ISSUE TITLE
Add Text capitalization option fo Button Themes

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68236]
The [Material Design specs](https://material.io/components/buttons#anatomy) recommend button text capitalization (for languages 
that support it).

![image](https://user-images.githubusercontent.com/8120472/96184046-46fee200-0f0e-11eb-8412-b8d5dd843d01.png)

There should be a Button Theme option to enforce text capitalization for buttons.

PS: The text mention text buttons and contained buttons, but not outlined button. I believe this is because outlined buttons were included later, so someone forgot to add them on the website text. Please forward this to the Material Design team so they can update the website.

**Comment by pedromassangocode** [comment]
Cc @willlarche

**Comment by willlarche** [comment]
I have no problem with this idea but leave it to @HansMuller to decide.

**Comment by pedromassangocode** [comment]
Related to https://github.com/flutter/flutter/issues/28567

**Comment by HansMuller** [comment]
This an interesting idea. Unfortunately, a general international implementation would be expensive (w3.org/TR/charmod-norm/#definitionCaseFolding) and would stretch the scope of ThemeData quite a bit. And ThemeData is still recovering from the stretching it's been through as the toolkit has evolved over the past 5 years -  flutter.dev/go/material-theme-system-updates.

I'm going to close this issue. We do appreciate the suggestion though.

**Comment by feinstein** [comment]
Thank you for considering and analyzing it.
