### ISSUE TITLE
CanvasKit strokeCap and strokeJoin don't always work

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#68233]
We noticed that in some conditions (oddly it's on certain browsers) the strokeCap and strokeJoin stop working on some shapes. 

It's hard to repro in isolation, so I took a peek at what the CanvasKit Paint->SkPaint glue does and it seems like strokeCap and strokeJoin don't get set when Paint object is resurrected. I could verify if this resurrection is the cause if there were a way to force trigger a resurrect (is there?).

**Note that when the SkPaint gets resurrected, the strokeCap, strokeJoin, and strokeMiter are not set. I think this might be the cause of the issue:**

https://github.com/flutter/engine/blob/dc848f154b9c5534262e5b8d3f0360a1beafdeb5/lib/web_ui/lib/src/engine/canvaskit/painting.dart#L218-L231

I've been seeing this issue since 1.22, but I'm currently on:
```
[✓] Flutter (Channel unknown, 1.23.0-13.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
```

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by yjbanov** [comment]
I think you're right. The resurrection code looks broken.

**Comment by yjbanov** [comment]
This also explains why this happens on certain browsers only. Most browsers have WeakRef, so we don't need to use resurrection at all. Safari and older versions of other browsers still need to resurrect.

**Comment by luigi-rosso** [comment]
That must be it then, all the reports are on Safari!
