### ISSUE TITLE
LUCI curl failure in bin/internal.sh

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68242]
```
Downloading Dart SDK from Flutter engine b22809b084345daecb2c2160cba5c9de9637c3f8...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 31  170M   31 53.4M    0     0   188M      0 --:--:-- --:--:-- --:--:--  187M
100  170M  100  170M    0     0   276M      0 --:--:-- --:--:-- --:--:--  276M
curl: (16) Error in the HTTP2 framing layer

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/b22809b084345daecb2c2160cba5c9de9637c3f8/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

**Comment by jonahwilliams** [comment]
Never seen this before. Should we add a retry?

**Comment by jonahwilliams** [comment]
Happened again: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866338247679797984/+/steps/flutter_doctor/0/stdout

**Comment by jonahwilliams** [comment]
We currently provide --retry 3.

**Comment by e-e** [comment]
Also experiencing this

**Comment by zanderso** [comment]
This has recently started happening more frequently

**Comment by jmagman** [comment]
Recent example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8854216271587252464/+/steps/flutter_doctor/0/stdout

**Comment by yusufm** [comment]
By any chance do we have curl's --verbose output with these errors?

**Comment by godofredoc** [comment]
@jonahwilliams do we use a backoff along with the retries? additionally would it be possible to print the headers of the response? I wonder if we are somehow being rate limited.

@yusufm is this happening only on VMs or this is also happening on the devicelab test beds?

**Comment by jonahwilliams** [comment]
I believe the default behavior of curl --retry is exponential backoff. This is done here: https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.sh

**Comment by yusufm** [comment]
Could we have curl run with --verbose when running on our infrastructure? Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1690971

**Comment by jonahwilliams** [comment]
do we set an environment variable to detect our infra? alternatively, we could add checks for something like `FLUTTER_VERBOSE_SDK_DOWNLOAD` and use that in the bash to conditionally set verbose

**Comment by godofredoc** [comment]
Yes we set "LUCI_CI: True" when running from LUCI.

**Comment by jonahwilliams** [comment]
One of the jobs in my PR failed, with the verbose flag this is what I've got:

```
Downloading Dart SDK from Flutter engine 6c1e7843b0fbfdf0b7a5e95c923c3c0f51bc4f54...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.217.212.128...
* TCP_NODELAY set
* Connected to storage.googleapis.com (172.217.212.128) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2770 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [148 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.storage.googleapis.com
*  start date: Jan 26 09:04:57 2021 GMT
*  expire date: Apr 20 09:04:56 2021 GMT
*  subjectAltName: host "storage.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x555d1fad1ee0)
} [5 bytes data]
> GET /flutter_infra_release/flutter/6c1e7843b0fbfdf0b7a5e95c923c3c0f51bc4f54/dart-sdk-linux-x64.zip HTTP/1.1
> Host: storage.googleapis.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 200 
< x-guploader-uploadid: ABg5-UxFklR3S7RZ8PyNZRbU1TRYpA_L3df_jpp2eLuunqtxd9Dl_kJ6eNIoJb8OOH4aKfKlgQl60c__YTyLELaqIWOiJbgRWg
< expires: Mon, 01 Mar 2021 20:46:51 GMT
< date: Mon, 01 Mar 2021 19:46:51 GMT
< cache-control: public, max-age=3600
< last-modified: Mon, 01 Mar 2021 17:43:52 GMT
< etag: "065ecaaddb630bdbf340580027f18017"
< x-goog-generation: 1614620632421594
< x-goog-metageneration: 1
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 208563235
< content-type: application/zip
< x-goog-hash: crc32c=e2umLQ==
< x-goog-hash: md5=Bl7KrdtjC9vzQFgAJ/GAFw==
< x-goog-storage-class: STANDARD
< accept-ranges: bytes
< content-length: 208563235
< access-control-allow-origin: *
< access-control-expose-headers: Content-Type
< server: UploadServer
< 
{ [5 bytes data]

  2  198M    2 4096k    0     0  19.4M      0  0:00:10 --:--:--  0:00:10 19.4M
 27  198M   27 54.4M    0     0  46.5M      0  0:00:04  0:00:01  0:00:03 46.4M
 66  198M   66  133M    0     0  59.9M      0  0:00:03  0:00:02  0:00:01 59.9M
 99  198M   99  198M    0     0  62.7M      0  0:00:03  0:00:03 --:--:-- 62.7M* Curl_http_done: called premature == 1

100  198M  100  198M    0     0  62.7M      0  0:00:03  0:00:03 --:--:-- 62.7M
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (16) Error in the HTTP2 framing layer

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra_release/flutter/6c1e7843b0fbfdf0b7a5e95c923c3c0f51bc4f54/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china

```

Not sure if that helps

**Comment by godofredoc** [comment]
Seems like an issue with curl https://github.com/curl/curl/issues/3750. Do we use the systems curl or does flutter bundles its own?

**Comment by jonahwilliams** [comment]
whatever is on the bots

**Comment by godofredoc** [comment]
@yusufm do you know if this is happening only on linux bots? it is easier to see from the milo uis:

* https://ci.chromium.org/p/flutter/g/framework/console
* https://ci.chromium.org/p/flutter/g/devicelab/console

**Comment by yusufm** [comment]
Its looking like it might be only on linux. I haven't found this error elsewhere yet.

**Comment by jmagman** [comment]
I also see this happening on Cirrus on macOS https://github.com/cirruslabs/cirrus-ci-docs/issues/805.

**Comment by godofredoc** [comment]
Landed changes to ensure we are using a recent version of curl. Please let us know if you see more failures like this as we may have missed updating some builders.

**Comment by godofredoc** [comment]
Moving to P2 for monitoring

**Comment by moorthi07** [comment]
In Mac
curl: (16) Error in the HTTP2 framing layer

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra_release/flutter/17f6bfc480b742c6659415981fa60caf1f6cac73/dart-sdk-darwin-x64.zip

**Comment by godofredoc** [comment]
@moorthi07 you'll need to update your system's curl version. We updated to 7.75.0 in our linux bots.

**Comment by godofredoc** [comment]
Have been monitoring the framework linux tasks and we haven't seen the problem anymore.

**Comment by christopherfujino** [comment]
> Seems like an issue with curl [curl/curl#3750](https://github.com/curl/curl/issues/3750). Do we use the systems curl or does flutter bundles its own?

We use system curl. Seems like we either need to rev the OS...or configure a CIPD curl and put it first on the path.

**Comment by christopherfujino** [comment]
> Have been monitoring the framework linux tasks and we haven't seen the problem anymore.

thanks!

**Comment by christopherfujino** [comment]
Re-opening this as it is currently affecting the engine. Fix to the engine is imminent.

**Comment by godofredoc** [comment]
Fix for the webengine framework tests: https://flutter-review.googlesource.com/c/recipes/+/10820

**Comment by godofredoc** [comment]
Closing this bug, please reopen if you find more builds failing with the same symptoms.

**Comment by godofredoc** [comment]
Change to use curl from cipd in devicelab has landed. Closing this issue.
