### ISSUE TITLE
showTimePicker not accepting the Done button on the keyboard

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68249]
When opening the `showTimePicker` in `initialEntryMode: TimePickerEntryMode.input` and trying to save the time using the keyboard, the `showTimePicker` dialog ignores the keyboard command and stays there:

```dart
onPressed: () async {
  TimeOfDay selectedTime = await showTimePicker(
    context: context,
    initialTime: widget.initialTime ?? TimeOfDay.now(),
    initialEntryMode: TimePickerEntryMode.input,
  );
  _controller.text = _formatCompactTime(selectedTime);
},
```

![image](https://user-images.githubusercontent.com/8120472/96194332-83d3d480-0f20-11eb-8b5a-928297bf2ac0.png)

Clicking on the "Confirm" button, pointed by the red arrow, does nothing, but usual user experience is to have it accept the value, just like pressing the OK Button.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!

```

</details>

![68249](https://user-images.githubusercontent.com/67046386/96228784-a19e4980-0fb3-11eb-85db-1728c37dd924.png)

**Comment by darshankawar** [comment]
May be related to [49810](https://github.com/flutter/flutter/issues/49810)

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by TahaTesser** [comment]
This is caused by `onEditingComplete` on `_HourMinuteTextField`
https://github.com/flutter/flutter/blob/ee204880a5f28465f1f682868b6cba4d4bd41909/packages/flutter/lib/src/material/time_picker.dart#L1778

[onEditingComplete](https://master-api.flutter.dev/flutter/widgets/EditableText/onEditingComplete.html) callback override the default behavior of such action

> Providing onEditingComplete prevents the aforementioned default behavior.



For `TimePicker`, based on this issue, we don't want this behavior but wanna keep `onEditingComplete`, I've filed a PR which will unfocus the `_HourMinuteTextField` when pressing `done`.
