### ISSUE TITLE
[pigeon] How to use FlutterApi？

### ISSUE THREAD

**Issue by liuyi999111** [flutter/flutter#68267]
Is there any examples?

**Comment by sudipghimire533** [comment]
did you checked [video player example](https://github.com/flutter/plugins/tree/master/packages/video_player)

**Comment by darshankawar** [comment]
@liuyi999111 
Please check above link for video player plugin that uses pigeon library. Hope it helps.

https://github.com/flutter/plugins/pull/2544/files

I am going ahead and closing this, as above links should provide example of what you are looking for. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by liuyi999111** [comment]
@sudipghimire533 @darshankawar 
This example do not use FlutterApi but only HostApi.

**Comment by darshankawar** [comment]
@liuyi999111 
What do you mean by Flutterapi ? Can you elaborate on your issue / question ?
thanks.
