### ISSUE TITLE
Flutter back button pressed, not hide the keyboard on Android phone ( some devices )

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#68278]
### Device Details : 
Samsung A7 2018 model.
Android 10.0
Samsung keyboard.
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Linux, locale en_US.UTF-8)

As stated here : https://github.com/flutter/flutter/issues/66791

on any text field, whenever i press device back button (not app back button) , the keyboard will close and then reopen again.

I tested this on my oneplus 7 device with android 10, Nexus 5x emulator with Android 10 , Pixel 4 with Android 9.0 and all of them worked fine.

**Comment by sidrao2006** [comment]
Hello @nateshmbhat ,
Could you please post the output of `flutter run -v` and some screenshots or video clips if possible.
Thank you!

**Comment by nateshmbhat** [comment]
@sidrao2006 
the issue is not happening on current stable channel. 

The video clip looks exactly like shown in #66791

**Comment by sidrao2006** [comment]
Hey @nateshmbhat , if this issue is not reproducible in the latest stable version, then it means that the issue is already resolved.
Thanks

**Comment by nateshmbhat** [comment]
Anyway upgrading flutter to : `Flutter 1.23.0-18.1.pre` fixed it :+1:
