### ISSUE TITLE
Default analysis options for Flutter projects

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#68275]
We should consider updating our default analysis options for flutter projects.

- [ ] We need to go through and audit the lints, enabling those that make sense for all Flutter apps, e.g. `no_logic_in_create_state`. See https://github.com/flutter/flutter/issues/75663 for discussion.
- [ ] We should probably create an analysis_options.yaml file by default, to help people who want to change the settings.
- [ ] That file should include a comment mentioning https://github.com/dart-lang/linter/blob/master/example/all.yaml (or similar) for people who want to see the whole list, as well as mentioning things like implicit-casts and implicit-dynamic, etc.

**Comment by mateusfccp** [comment]
Don't you think `implicit-casts` and `implicit-dynamic` should be `false` by default?

**Comment by goderbauer** [comment]
This is done. Lints are published in package:flutter_lints.
