### ISSUE TITLE
(With 3-core-line reproducible sample & Version 1.22.1) Error rendering long paragraph with link and image (RichText + TextSpan.recognizer + WidgetSpan => Exception) :(

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#68276]
## Steps to Reproduce

Thanks very much for Flutter! However I am encountering a bug as follows. There are only 3 core lines that matters in this bug:

1. A TextSpan containing lots of texts, which makes the other WidgetSpan and clickable TextSpan off-screen.
2. A TextSpan with `recognizer`.
3. A WidgetSpan.

Of course, there may be some other reproducing conditions that I did not discover. Then, when RenderParagraph `assembleSemanticsNode`, the `children` parameter is empty array, but then the WidgetSpan (which has `isPlaceholder` true) needs to consume an element in the `children` parameter, causing errors.

In my humble opinion, this bug is **a fairly common use-case** when using it. Very commonly, people render long paragraphs with links and images. That is the case!

1. Run `flutter create bug`.
2. Update the files as follows: ... 

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Bug!')),
        body: ListView(children: [
          RichText(
              text: TextSpan(style: TextStyle(color: Colors.black), children: [
            TextSpan(text: '0123456789HelloWorld' * 200),
            TextSpan(text: 'I_AM_CLICKABLE', recognizer: TapGestureRecognizer()..onTap = () => print('hi tap')),
            WidgetSpan(child: Container(width: 50, height: 50, color: Colors.red)),
          ]))
        ]));
  }
}
```

3. Run and look at console. 

P.S. Currently I have to [disable the semantics](https://stackoverflow.com/questions/64384431/disable-semantics-system-in-flutter) to avoid this bug. But since semantics is so important, this is not a good idea :/

**Expected results:** 
No error.

**Actual results:** 
Has error:

```

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
RangeError (index): Invalid value: Valid value range is empty: 0
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
Bad state: Future already completed
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
RangeError (index): Invalid value: Valid value range is empty: 0
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following RangeError was thrown during a scheduler callback:
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:177:60)
flutter: #1      List.elementAt (dart:core-patch/growable_array.dart:386:16)
flutter: #2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:921:50)
flutter: #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3717:13)
flutter: #4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3709:16)
flutter: #5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3663:18)
flutter: #6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3709:16)
flutter: #7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3709:16)
flutter: #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3709:16)
flutter: #9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3663:18)
flutter: #10     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3663:18)
flutter: #11     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3709:16)
flutter: #12     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3587:16)
flutter: #13     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2631:25)
flutter: #14     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1081:16)
flutter: #15     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:441:21)
flutter: #16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
flutter: #17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #20     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
flutter: (elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

<details>
  <summary>Logs</summary>

```
See: https://gist.github.com/fzyzcjy/a23133efea803d92d061afbe5f46b02f
```

```
Analyzing bug...                                                        
No issues found! (ran in 8.5s)
```

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale
    zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/tom/opt/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

**Comment by darshankawar** [comment]
@fzyzcjy 
Tried your code sample on latest stable using Android 8.1.0 device and was able to top on the very last line which prints in console properly, without throwing any exception.

```
I/flutter (30158): hi tap
I/flutter (30158): hi tap
I/flutter (30158): hi tap
I/flutter (30158): hi tap
I/flutter (30158): hi tap
I/flutter (30158): hi tap
I/flutter (30158): hi tap
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!
```

</details>

Are there any specific steps to replicate the exception ?

**Comment by fzyzcjy** [comment]
@darshankawar Thanks for the reply! I use an iOS simulator of `iPhone SE - 2nd generation` with iOS 14.0 on Mac Mini 10.15.7. I just *run* the app and the error happens - *no need* to tap the text, just wait for its first rendering and error automatically happens. Maybe these information is useful to reproduce it?

**Comment by darshankawar** [comment]
@fzyzcjy 
Tried again on iPhone SE simulator (OS 14) and didn't see any exception. Also waited for some time to render the screen properly. I was able to scroll up and down and tap on the clickable text.

Waiting for iPhone SE (2nd generation) to report its views...
Debug service listening on ws://127.0.0.1:49891/iSkxISa2QoA=/ws
Syncing files to device iPhone SE (2nd generation)...
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap
flutter: hi tap

So this isn't reproducible at my end. Could you provide video of the issue if that happens consistently ? Not sure if mac mini you mentioned has something to do with it.
Thanks.

**Comment by fzyzcjy** [comment]
[flutter_bug_screen_video.zip.001.zip](https://github.com/flutter/flutter/files/5394965/flutter_bug_screen_video.zip.001.zip)

[flutter_bug_screen_video.zip.002.zip](https://github.com/flutter/flutter/files/5394967/flutter_bug_screen_video.zip.002.zip)

**Comment by fzyzcjy** [comment]
Since github only allow 10MB size and limited extensions, here is the compression:

1. unzip the `.zip.001.zip` and `.zip.002.zip`, get `.zip.001` and `.zip.002`
2. combine two `.00x` files and unzip them together. you will get `flutter_bug_screen_video.mov`

**Comment by darshankawar** [comment]
@fzyzcjy 
If possible, please upload the video on youtube and share the link. 
Thanks.

**Comment by fzyzcjy** [comment]
@darshankawar Sorry I do not have a YouTube account :/ Could you please download that zip file?

**Comment by darshankawar** [comment]
@fzyzcjy If you could upload it on google drive and share the link, it would be helpful rather than to download all all zips and then combine them together.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
