### ISSUE TITLE
It should detect and run on iOS emulator

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#68272]
Right now flutter didn't detect ios simulator evenif its open due to its requirement of latest `xcode`.But its should work without latest `xcode` also. means if `simulator` is open for `ios` then it should detect and allow to run.It may happen not everyone has latest of `xcode`. Hope that will understand my concern.
Thank you!

**Comment by sidrao2006** [comment]
Hey @mehtahardikr , flutter requires the developer tools provided by xcode to buold and run the app. So if Xcode is not installed then flutter will not work.

Workaround - Use an older version of flutter.
Though it is better if you could update Xcode

Thanks

**Comment by mehtahardikr** [comment]
@sidrao2006 : i have xcode installed , but issue is that why simulator not use just because of xcode is older ?

**Comment by sidrao2006** [comment]
Hey @mehtahardikr , I think it happens because if you have an older version of Xcode, the tools are incompatible and it may not be possible to build for a newer OS installed on your Simulator.

**Comment by sidrao2006** [comment]
@mehtahardikr can you provide the output of `flutter devices` and `flutter emulators`

Thanks

**Comment by mehtahardikr** [comment]
flutter emulators
2 available emulators:

```
apple_ios_simulator • iOS Simulator  • Apple  • ios
Pixel_2_API_29      • Pixel 2 API 29 • Google • android
```

flutter devices
1 connected device:

`SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)`

**Comment by sidrao2006** [comment]
Hey @mehtahardikr , your Simulator is being detected. But it's not being able to run because of the reason I mentioned above

**Comment by mehtahardikr** [comment]
@sidrao2006 : still ,my question same , if its able to detect then why not able to run ? xcode updates ,may not change their internal commnads who run apps to simulators.

**Comment by Abhishek01039** [comment]
Hi @mehtahardikr 
First,Maybe you haven't start the iOS emulator.
start the iOS emulator and run `flutter devices`
this command should have emulator and simulator both 
Thanks

**Comment by sidrao2006** [comment]
Hey @mehtahardikr , I found [this article](https://medium.com/@nqtuan86/how-to-debug-on-recent-ios-simulators-and-devices-using-old-xcode-93a4fc092e7b), could you please try the steps?

Thanks

**Comment by mehtahardikr** [comment]
@Abhishek01039 : apple_ios_simulator • iOS Simulator  • Apple  • ios. 

this emulator is running . now tell me further steps.

**Comment by Abhishek01039** [comment]
Hi @mehtahardikr 
please send the output of `Flutter devices -v `
Thanks

**Comment by mehtahardikr** [comment]
+27 ms] executing: sw_vers -productName
[ +155 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 17G65
[  +99 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +169 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +33 ms] executing: /usr/bin/xcode-select --print-path
[  +38 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[+2353 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 10.1
           Build version 10B61
[   +9 ms] executing: /Users/UserA/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Xcode not found. Run 'flutter doctor' for more information.
[ +240 ms] List of devices attached
                    42007d3b9a168429       device usb:342884352X product:j7maxltedd model:SM_G615FU device:j7maxlte transport_id:46
[   +7 ms] 1 connected device:
           
[   +6 ms] /Users/VishakhaP/Library/Android/sdk/platform-tools/adb -s 42007d3b9a168429 shell getprop
[ +106 ms] ro.hardware = mt6757
[        ] ro.build.characteristics = default
[   +9 ms] SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)
[   +5 ms] executing: /Users/UserA/Library/Android/sdk/platform-tools/adb devices -l
[ +240 ms] List of devices attached
                    42007d3b9a168429       device usb:342884352X product:j7maxltedd model:SM_G615FU device:j7maxlte transport_id:46
[   +2 ms] Xcode not found. Run 'flutter doctor' for more information.

**Comment by Abhishek01039** [comment]
Hi @mehtahardikr 
you haven't started the emulator yet
please start it

**Comment by Abhishek01039** [comment]
The output of `flutter devices` should be like this if you are starting an emulator
```
catalina@Catalinas-iMac tudoflutter % flutter devices
2 connected devices:

sdk gphone x86 (mobile)    • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
iPhone 11 Pro Max (mobile) • 9A923687-50FF-4700-BC75-4D445139AA35 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
```
Thanks

**Comment by mehtahardikr** [comment]
![Screen Shot 2020-10-16 at 2 11 19 PM](https://user-images.githubusercontent.com/12496655/96236332-8b938780-0fb9-11eb-93f5-1e56f98be298.png)

here its already open

**Comment by Abhishek01039** [comment]
Please send the output of `flutter doctor -v`

**Comment by sidrao2006** [comment]
> flutter emulators
> 2 available emulators:
> 
> ```
> apple_ios_simulator • iOS Simulator  • Apple  • ios
> Pixel_2_API_29      • Pixel 2 API 29 • Google • android
> ```
> 
> flutter devices
> 1 connected device:
> 
> `SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)`
> 
> 

Was the emulator running when you ran this command?
Thanks

**Comment by mehtahardikr** [comment]
> > flutter emulators
> > 2 available emulators:
> > ```
> > apple_ios_simulator • iOS Simulator  • Apple  • ios
> > Pixel_2_API_29      • Pixel 2 API 29 • Google • android
> > ```
> > 
> > 
> > flutter devices
> > 1 connected device:
> > `SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)`
> 
> Was the emulator running when you ran this command?
> Thanks

yes

**Comment by mehtahardikr** [comment]
> Please send the output of `flutter doctor -v`
> Thanks

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.22.1 at /Users/VishakhaP/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/VishakhaP/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM G615FU (mobile) • 42007d3b9a168429 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by Abhishek01039** [comment]
@mehtahardikr 
you are using the Xcode which is not supported by Flutter
please Update your Xcode to 11.0.0
Thanks

**Comment by mehtahardikr** [comment]
@Abhishek01039  :  Thats my question. its always need to update xcode to run app on old simulator ?

**Comment by Abhishek01039** [comment]
Please refer to this
https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on

**Comment by mehtahardikr** [comment]
> Please refer to this
> https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on

as per this it should work without issue

Mobile operating systems: Android Jelly Bean, v16, 4.1.x or newer, and iOS 8 or newer.

Mobile hardware: iOS devices (iPhone 4S or newer) and ARM Android devices.

Flutter supports building ahead-of-time (AOT) compiled libraries for x86_64, armeabi-v7a, and arm64-v8a.

Apps built for ARMv7 or ARM64 run fine (using ARM emulation) on many x86 Android devices.

We support developing Flutter apps with Android and iOS devices, as well as with Android emulators and the iOS simulator.

and i have `12.1`

**Comment by Abhishek01039** [comment]
But you need Xcode with at least 11.0.0 version

**Comment by mehtahardikr** [comment]
> But you need Xcode with at least 11.0.0 version
> you need to upgrade your Xcode not simulator's OS

I don't know why you ask for update ide as we are targetting cross platfoms if  device compatible then why need to update its development ide.  there might be issue with flutter.

**Comment by Abhishek01039** [comment]
``` • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
```
@mehtahardikr

**Comment by sidrao2006** [comment]
Hey @mehtahardikr , newer versions of flutter require recent versions of Xcode to build the app. It's not tye IDE that flutter is concerned with. Xcode also ships a set of development tools with it which is required to build the app. If you need to work with older versions of Xcode, please downgrade flutter. As mentioned above, the Simulator is dependent on Xcode and hence it has version constraints.
Check out [this medium article](https://medium.com/@nqtuan86/how-to-debug-on-recent-ios-simulators-and-devices-using-old-xcode-93a4fc092e7b) to solve it.
Thanks

**Comment by TahaTesser** [comment]
hI @mehtahardikr 
Also, you can't ship your app using Xcode 10, you would have to upgrade your setup Xcode and fluter for your project if you plan to publish it.
On the other hand, if you want to stick with an older Flutter SDK, any bugs for an older  Flutter SDK version won't get new bug fixes 
I would recommend min Xcode 11, If yo can

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
