### ISSUE TITLE
2x Image assets are not being displayed 

### ISSUE THREAD

**Issue by Ian0903** [flutter/flutter#68289]
"pubspec.yaml中asset部分中的每一项都应与实际文件相对应，但主资源项除外。当主资源缺少某个资源时，会按分辨率从低到高的顺序去选择 （译者语：也就是说1x中没有的话会在2x中找，2x中还没有的话就在3x中找）。"

如果1x没有对应图片时，读取2x图片的设备并不会去2x中找，而是直接不显示。。。

**Comment by TahaTesser** [comment]
Google Translate
`"Every item in the asset section of pubspec.yaml should correspond to the actual file, except for the main resource item. When the main resource lacks a certain resource, it will be selected in descending order of resolution (Translator Language : That is to say, if there is none in 1x, it will be found in 2x, and if there is not in 2x, it will be found in 3x)."
If 1x does not have a corresponding picture, the device that reads the 2x picture will not find it in 2x, but will not display it. `

**Comment by TahaTesser** [comment]
Hi @Ian0903 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
