### ISSUE TITLE
mega_gallery has many analyzer errors

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6829]
I happened to be analyzing the entire flutter repo when I ran the tests and it noticed a bunch of errors in the mega_gallery. Is that expected?

**Comment by devoncarew** [comment]
It's not. I'll validate that it's still happy. You may have an old copy; you may want to `rm -rf dev/benchmarks/mega_gallery/` or `dart dev/tools/mega_gallery.dart`.

**Comment by devoncarew** [comment]
A new copy shows as clean for me:

```
Analyzing 835 files...
No analyzer warnings! (ran in 23.1s; 56 public members lack documentation)
```

so you may want to just delete your copy.

**Comment by Hixie** [comment]
Odd, I had cleaned my whole repo and the errors appeared when I ran the tests. I'll close this and file a new one if I notice this again and have more data.
