### ISSUE TITLE
unrecognized selector sent to instance STARTUP Crash AppDelegate

### ISSUE THREAD

**Issue by Gastrolize** [flutter/flutter#68303]
Hello, I've not changed my code just upgraded my Plugins and now im getting following error:
`2020-10-16 14:59:37.133562+0200 Runner[361:8860] -[__NSCFConstantString objectForKey:]: unrecognized selector sent to instance 0x2070fe720
2020-10-16 14:59:37.133870+0200 Runner[361:8860] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString objectForKey:]: unrecognized selector sent to instance 0x2070fe720'
*** First throw call stack:
(0x1af2785ac 0x1c32f242c 0x1af182a2c 0x1af27b130 0x1af27d420 0x101efacd0 0x101ef8720 0x101efb034 0x101f1122c 0x101f111a4 0x1b17b6d24 0x1b1d0e218 0x1b1d0e0b0 0x1b1b97648 0x1b1b97b64 0x1b1b96380 0x1b1227d70 0x1b17734d4 0x1b12288c0 0x1b122838c 0x1b12286d0 0x1b1227f48 0x1b1230078 0x1b1685c28 0x1b178b810 0x1b122fdf0 0x1b1064eb0 0x1b106386c 0x1b1064ad8 0x1b1b94668 0x1b16ae274 0x1be22a2dc 0x1be254a00 0x1be238d24 0x1be2546d0 0x10ef515f0 0x10ef54e70 0x1be27c0e0 0x1be27bd88 0x1be27c2ac 0x1af1f581c 0x1af1f5718 0x1af1f4a28 0x1af1eed20 0x1af1ee4bc 0x1c5c73820 0x1b1b92734 0x1b1b97e10 0x10082d024 0x1aeeb5e60)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString objectForKey:]: unrecognized selector sent to instance 0x2070fe720'
terminating with uncaught exception of type NSException`

My Flutter Doctor:
`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale de-DE)
    • Flutter version 1.22.1 at /Users/sobhihammoud/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sobhihammoud/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPad von Sobhi (mobile) • 00008027-001550490131802E • ios • iOS 14.0.1
    

• No issues found!`

I can not debug the issue. Tried with run --verbose but there are no logs. Tried `flutter clean`, deleted the DerivedData, deleted the build folder but nothing happenes.

It started not working since I was handling with android on another flutter App and upgraded plugins depended on firebase and Firestore. Since then im getting this error.

` 0x1b1b97dfc <+148>: adrp   x8, 365444
    0x1b1b97e00 <+152>: ldr    x0, [x8, #0x3a0]
    0x1b1b97e04 <+156>: adrp   x8, 284969
    0x1b1b97e08 <+160>: add    x1, x8, #0xfc8            ; =0xfc8 
    0x1b1b97e0c <+164>: bl     0x1aeead830
->  0x1b1b97e10 <+168>: adrp   x0, 2010                     // <- HERE IS THE ERROR
    0x1b1b97e14 <+172>: add    x0, x0, #0x7bb            ; =0x7bb 
    0x1b1b97e18 <+176>: bl     0x1b837ac58               ; abort_report_np`

**Comment by darshankawar** [comment]
@Gastrolize Please elaborate on the issue. Which plugins did you upgrade ? When do you get this error ? Please provide `pubspec.yaml` alongwith a minimal complete reproducible code sample.

**Comment by Gastrolize** [comment]
My pub spec.yaml:

`name: gastrolize_kassensystem
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter_screenutil: 1.1.0
  auto_size_text: ^2.1.0
  screenshot: ^0.1.1
  shared_preferences: 0.5.12+2
  sumup_flutter: ^0.0.3
  uuid: ^2.0.4
  http: 0.12.1
  dio: ^3.0.9
  flutter_mailer: ^0.4.1+1
  flare_flutter: ^2.0.3
  flutter_spinkit: ^4.1.2
  flutter_statusbarcolor: ^0.2.3
  firebase_crashlytics: ^0.2.1+1
  firebase_storage: 4.0.1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  firebase_core: 0.5.0+1
  firebase_analytics: ^6.0.2
  flutter_colorpicker: ^0.3.4
  flutter_speed_dial: ^1.2.5
  simple_animations: ^1.3.11
  badges: ^1.1.1
  intl: 0.16.1
  reorderables: 0.3.2
  property_change_notifier: ^0.2.0
  threading: ^0.0.10
  overlay_support: 1.0.3
  assets_audio_player: ^2.0.10
  qr_flutter: 3.2.0
  provider: 4.0.5+1
  keyboard_avoider: 0.1.2
  connectivity: ^0.4.8+6
  data_connection_checker: ^0.3.4
  permission_handler: ^5.0.1+1
  majascan: ^0.3.7
  flutter_nfc_reader: ^0.1.0
  shimmer: ^1.0.1
  auto_animated: 2.1.0
  modal_bottom_sheet: ^0.2.0+1
  charts_flutter: ^0.9.0
  onesignal_flutter: ^2.6.1
  date_utils: ^0.1.0
  encrypt: ^4.0.2
  scrollable_positioned_list: 0.1.6
  image_picker: ^0.6.7+11
  mailer: ^3.0.4
  uni_links: ^0.4.0
  tse_kassensystem:
    path: /users/SobhiHammoud/tse_kassensystem

  pos_printer:
    path: /users/SobhiHammoud/pos_printer
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  hive_generator: 0.7.1
  analyzer: 0.39.14
  build_runner: 1.10.1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9



flutter_native_splash:
  image: images/splash.png
  color: "ffffff"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/plant.png
    - images/icons/single_layer.png
    - images/icons/multi_layer.png
    - images/kasse.png
    - images/products.png
    - images/drink.png
    - images/shisha.png
    - images/tick-2.png
    - images/database.png
    - images/table.png
    - images/drink-white.png
    - images/essen-white.png
    - images/shisha-white.png
    - images/essen.png
    - images/terminal.png
    - images/cash.png
    - images/sumup.png
    - images/interface.png
    - images/add_cat.png
    - images/add_uncat.png
    - images/set_unc.png
    - images/cat_set.png
    - images/flare/success.flr
    - images/flare/error.flr
    - images/order.png
    - images/payment.png
    - images/coupon.png
    - images/coupon_change.png
    - images/placeholder-qr.png
    - images/question.png
    - cert/cert.crt
    - images/drucker.jpg
    - images/bon.png
    - images/locker.png
    - images/info.png
    - images/info-2.png
    - images/reserved.png
    - images/waiter.png
    - images/glass.png
    - images/inventar_glass.png
    - images/waiter-2.png
    - images/no.png
    - images/cancel.png
    - images/fee.png
    - images/inventory.png
    - images/shield.png
    - images/add.png
    - images/food-tray.png
    - images/see.png
    - images/checklist.png
    - images/folder.png
    - images/closed.png
    - images/shopping-center.png
    - images/permission.png
    - images/permis.png
    - images/printer.png
    - images/ipad.jpg
    - images/swiftly.mp3


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sansBold
      fonts:
        - asset: fonts/sansBold.otf
    - family: sansMedium
      fonts:
        - asset: fonts/sansMedium.otf
    - family: harlow
      fonts:
        - asset: fonts/harlow.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

I just clicked on packages upgrade in android studio

im getting this issue since today

**Comment by Gastrolize** [comment]
Found the Solution. It was the info.plist where I had trusted domains. That caused the problem , removed it and now it works!

**Comment by IlyaOstashkov** [comment]
> Found the Solution. It was the info.plist where I had trusted domains. That caused the problem , removed it and now it works!

remove from Info.plist 
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<string></string>
		</dict>
	</dict>
```
