### ISSUE TITLE
Some code like material page route works while in debug mode and when i upload it to play store it stop working.

### ISSUE THREAD

**Issue by deviilrider** [flutter/flutter#68305]
RichText _convertHashtag(String text) {
    List<String> split = text.split(RegExp("#"));
    List<String> hashtags = split.getRange(1, split.length).fold([], (t, e) {
      var texts = e.split(" ");
      if (texts.length > 1) {
        return List.from(t)
          ..addAll(["#${texts.first}", "${e.substring(texts.first.length)}"]);
      }
      return List.from(t)..add("#${texts.first}");
    });

    return RichText(
      text: TextSpan(
        children: [
          TextSpan(text: split.first, style: TextStyle(color: Colors.black))
        ]..addAll(hashtags.map((text) {
            return text.contains("#")
                ? TextSpan(
                    recognizer: TapGestureRecognizer()
                      ..onTap =
                          () => Navigator.of(context).push(MaterialPageRoute(
                              builder: (context) => HashTagView(
                                    tag: text,
                                  ))),
                    text: text,
                    style: TextStyle(color: Colors.blue))
                : TextSpan(text: text, style: TextStyle(color: Colors.black));
          }).toList()),
      ),
    );
  }

this is my code and when I run it on debug mode It works properly but when I upload it on play store then it the route doesn't run and shows blank screen on next page.

**Comment by sidrao2006** [comment]
Hello @deviilrider ,
Could you please post the outputs of `flutter build apk-v` or `flutter build ios -v` and `flutter doctor -v`
Thank you!

**Comment by darshankawar** [comment]
@deviilrider 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that we can copy paste and run directly that shows the issue.
