### ISSUE TITLE
Configurable Tooltip GestureDetector 

### ISSUE THREAD

**Issue by JulienMalige** [flutter/flutter#68306]
## Use case

I would like the tooltip opens **onTap** rather than **onLongPress**.

Also related to https://stackoverflow.com/questions/59826172/tooltip-ontap-rather-than-onlongpress-possible.

## Proposal

Make the [Tooltip GestureDetector](https://github.com/JulienMalige/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/material/tooltip.dart#L404) overridable via property or have a property which allows to choose between onTap/onLongPress.

**Comment by JulienMalige** [comment]
it seems to go against the spec material design (https://material.io/components/tooltips#placement). 
My point may be more about the duration of the press than the event itself.
On mobile, it can be difficult for the user to understand that a longPress is going to make something appear.

**Comment by darshankawar** [comment]
@JulienMalige 
Since this proposal would go against the material design, probably it would make more sense to add the duration of the press in documentation to make it more clear. Thought ?

**Comment by JulienMalige** [comment]
I think we will use another component. Thanks for the consideration.

**Comment by darshankawar** [comment]
@JulienMalige 
Given your last message, I am going ahead and closing this issue. If you disagree, write in comments and I'll reopen.
Thanks.
