### ISSUE TITLE
SwitchListTile and CheckboxListTile will need a selectedTileColor as well

### ISSUE THREAD

**Issue by talamaska** [flutter/flutter#68304]
## Use case

For consistent look of all the tiles in a list, specifically in drawer, but valid for other cases.
I saw that there is a PR  #67135  closing #67063 
Which adds a tileColor to the SwitchListTile and CheckboxListTile. 

I would use it to represent the checked state with an additional background, currently the selected boolean controls if the 2 tiles are in a selected state which applies the primary color to the text and the icons in the tile.
and tileColor have to be manually changed according to the selected State.

## Proposal

It would be nice if the selectedTileColor is exposed for SwitchListTile and CheckboxListTile,
so we don't have to change that mannually.

**Comment by yash1200** [comment]
@talamaska I would like to work on this issue.

**Comment by HansMuller** [comment]
CC @darrenaustin
