### ISSUE TITLE
delta_99th_percentile_frame_rasterizer_time_millis flutter_gallery__transition_perf_with_semantics regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#68317]
See https://flutter-flutter-perf.skia.org/e/?begin=1602618650&end=1602692077&keys=X02f875eeec6c861313c90cec51cf7ebc&num_commits=50&request_type=1&xbaroffset=21991.

It started at https://github.com/flutter/flutter/pull/68060, but I'm skeptical and again wondering if it's the roll at https://github.com/flutter/flutter/pull/68148.

**Comment by gaaclarke** [comment]
@jonahwilliams Is this regression expected as a result from https://github.com/flutter/flutter/pull/68060?

@kf6gpe Why are you skeptical?

**Comment by jonahwilliams** [comment]
This commit changed how the APK was built. Its possible the configuration is now different. I will investigate

**Comment by jonahwilliams** [comment]
If I checkout #68060, I get:

`delta_99th_percentile_frame_rasterizer_time_millis: -0.815`

If I checkout the commit following (The engine roll)

`delta_99th_percentile_frame_rasterizer_time_millis 2.1430000000000007`

So it was definitely the engine roll. We might have a problem in our commit attribution? I'm not familiar with the Skia perf code

**Comment by gaaclarke** [comment]
-0.815 for the time to render a frame?  That isn't suspicious at all.

**Comment by jonahwilliams** [comment]
Its a delta

**Comment by gaaclarke** [comment]
Even when a delta it's surprising for the measurement to switch signs, I'd have to read through the test though.  I'm not saying it wasn't the engine roll, the sign switch is suspect though.

**Comment by gaaclarke** [comment]
This doesn't appear to be a regression.  We are back to where we were.  Check out https://flutter-flutter-perf.skia.org/e/?begin=1602290433&end=1602741424&queries=sub_result%3Ddelta_99th_percentile_frame_rasterizer_time_millis&requestType=0&xbaroffset=21991

![Screen Shot 2020-10-16 at 3 29 37 PM](https://user-images.githubusercontent.com/30870216/96319405-6b1cfa80-0fc4-11eb-9c51-93eef65570a0.png)

The levels are the same they were the day before, https://github.com/flutter/flutter/commit/fd11d149f7281824f6a600414cbbb7fd8287d7e7 created a temporary dip in performance.  Interestingly that commit had to do with installations too.

@jonahwilliams You don't have a theory why https://github.com/flutter/flutter/commit/fd11d149f7281824f6a600414cbbb7fd8287d7e7 caused the dip do you?

**Comment by jonahwilliams** [comment]
It looks like the test depends on some aspects of the IPA being preserved across installs? Perhaps it is doing something weird?

Thanks for the investigation, I'm going to mark this down to a P4. If the test is sensitive to this sort of thing its got some serious problems.
