### ISSUE TITLE
[Navigator 2.0] Screen resizing doesn't cause Page/Route rebuilding

### ISSUE THREAD

**Issue by proninyaroslav** [flutter/flutter#68326]
## Steps to Reproduce

I'm using adaptive dialogs in the app. I also use Navigator 2.0 for navigation. The idea is simple: if the screen width is < `600` (phone), `Scaffold` + `MaterialPageRoute` is used, if width >= `600` (tablet, desktop) `AlertDialog` + `PopupRoute` is used. 
`PopupRoute` is needed to make the background semi-transparent and change the transition animation. It looks like this:

![1_compress](https://user-images.githubusercontent.com/7840559/96295165-1eeaae00-0ff6-11eb-98a1-c8e92b34027e.gif)

<details>
  <summary>Code</summary>

```
```Dart

class MyApp extends StatelessWidget {
  ...
  final MyRouterDelegate _routerDelegate = MyRouterDelegate();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      ...
      routerDelegate: _routerDelegate,
      ...
    );
  }
}

class class MyRouterDelegate extends RouterDelegate<MyRoutePath>
  with ChangeNotifier, PopNavigatorRouterDelegateMixin<MyRoutePath> {
  ...
  @override
  Widget build(BuildContext context) {
    return Navigator(
      pages: [
        MaterialPage(
          key: ...,
          child: Home(),
        ),
        if (showAddAccount) 
          MyAdaptivePage(
            key: ...,
            child: AddAccount(),
          ),
      ]
      ...
    );
  }
  ...
}
class MyAdaptivePage<T> extends Page<T> {
   ...
   @override
   Route<T> createRoute(BuildContext context) {
     if (MediaQuery.of(context).size.width < 600) {
       return MaterialPageRoute(
         builder: (context) => child,
         settings: this,
       );
     } else {
       return MyPopupRoute(
         builder: (context) => child,
         settings: this,
       );
     }
   }
}
```
</details>

This works fine, but if my adaptive dialog is open and I try to resize the screen, `Page.createRoute` and` RouterDelegate.build` don't call. 
This causes a big problem: `Route` isn't changed. This means that if I change the screen size, for example, from phone to tablet, the background will be black, not transparent, because the current `Route` is `MaterialPageRoute`, not `MyPopupRoute`. Also the transition animation doesn't change.
This issue is relevant on desktop/foldable devices as the user can resize the window/fold the display.
This is what the problem looks like:

![2_min](https://user-images.githubusercontent.com/7840559/96299419-b81cc300-0ffc-11eb-88da-b0d1411c8d15.gif)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.22.1 at ...
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at ...
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = ...
    • Java binary at: .../android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at .../android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at .../intellij-idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @proninyaroslav 
Can you please provide a minimal complete reproducible code sample?
The code you provided is missing some parts of it for me to run it.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
