### ISSUE TITLE
Remove or update devicelab tests that listen to adb stream

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68323]
To simplify the devicelab code, we need to reduce the amount of one-off and special handling that is in the runners, and move it to either a driver test script or the flutter tool itself when appropriate. To that end, I'd like to remove the special handlers for `adb logcat`. 

There are several tests that use this pattern:
* All memory info benchmarks
* image list duration tests

These could be rewritten as driver tests in the applications under test. For memory info, the flutter_tool exposes a VM service protocol method (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/vmservice_integration_test.dart#L56 ) which returns the data in a structured format.

The image list duration tests could use events or custom requests in the flutter_driver.

**Comment by godofredoc** [comment]
obsolete
