### ISSUE TITLE
The "Delete mac deriveddata" is flaky and causes tree closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68359]
An example of this failure [is here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866246486827142320/+/steps/Delete_mac_deriveddata/0/logs/execution_details/0). Curiously, all that the step attempts to do is `rm -rf` a directory:

```
Executing command [
  '/bin/rm',
  '-rf',
  '/Users/chrome-bot/Library/Developer/Xcode/DerivedData/',
]
```

**Comment by keyonghan** [comment]
It is also a `-9` error code, and have included it in the failed scenarios in https://github.com/flutter/flutter/issues/68322
We already have some earlier failure on `top` step: [Step('OS info') (retcode: -9)](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/7284)
Thanks for creating this issue, but gonna to combine this one with the above issue as well.

**Comment by keyonghan** [comment]
Sorry forgot to check: please let me know if you need a manual re-trigger (saw there is already a new commit running though).

**Comment by chinmaygarde** [comment]
> let me know if you need a manual re-trigger.

There have been quite a few flakes of this kind today so we have been ignoring presubmits that fail this way. I just wanted to make sure this was tracked though. If you think other issues adequate cover this failure, then great!
