### ISSUE TITLE
[Infra Doc Fixit] Refresh documentation for Stackdriver Cocoon alerts

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#68352]
Hi!

To close this issue:
1. Are you still the owner? Update the spreadsheet if not and reassign.
2. If you don't consider any work is needed, close.
3. Please double check if the documentation is up to date and prune any stale
information
  i. Review markdown docs in related code repos
  ii. Review associated sites and wikis
4. Review the cookbook
  i. If one does not exist, create it and link it on the team page
  ii. Add and review common tasks
5.  Review related dashboards
  i. If this service does not have a dashboard, but should create it!
  ii. Ensures it's on the Fuchsia infra teams dashboards

Thank you for keeping our service's documentation up to date!

**Comment by godofredoc** [comment]
I'll consolidate this alert doc with all the other available alerts.

**Comment by godofredoc** [comment]
Docs updated!
