### ISSUE TITLE
ProcessException: ProcessException: Operation not permitted

### ISSUE THREAD

**Issue by 00AhmedMokhtar00** [flutter/flutter#68354]
## command

flutter build appbundle

## exception

ProcessException: ProcessException: Operation not permitted
  Command: /Users/mokhtar/AndroidStudioProjects/restaurant_flutter_application/android/gradlew -q -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true bundleRelease

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-EG)
    • Flutter version 1.20.4 at /Users/mokhtar/Developer/flutter
    • Framework revision fba99f6cf9 (5 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mokhtar/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

## Flutter Application Metadata
**Type**: null
**Version**: 1.1.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
firebase_messaging-6.0.16
flutter_plugin_android_lifecycle-1.0.9
fluttertoast-4.0.1
google_maps_flutter-0.5.29
location-3.0.2
location_web-1.0.0
path_provider-1.6.16
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.3
screen-0.0.5
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
video_player-0.10.12+3
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by hamdikahloun** [comment]
Hi @00AhmedMokhtar00 

This issue was [fixed](https://github.com/flutter/flutter/issues/50880)  and [merged](https://github.com/flutter/flutter/pull/63540) .

Also see [this](https://github.com/flutter/flutter/issues/67093#issuecomment-702497613)  comment and try the same at your end to see if it works.

Thank you

**Comment by 00AhmedMokhtar00** [comment]
Thanks @hamdikahloun for your quick response.
I tried 'flutter upgrade' but it didn't work, the same problem appears.
as for the iOS 'flutter build ios' succeeds normally, but 'flutter build apk', 'flutter build appbundle' always fail.

the problem is only with specific project, all ther flutter projects are working fine

**Comment by hamdikahloun** [comment]
@00AhmedMokhtar00 Can you switch to master channel please : 

1. `flutter channel master`

2. `flutter upgrade`

**Comment by 00AhmedMokhtar00** [comment]
> @00AhmedMokhtar00 Can you switch to master channel please :
> 
> 1. `flutter channel master`
> 2. `flutter upgrade`

I did that, then I tried  `flutter build appbundle` and had this ERROR: 

`null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
current user.`

**Comment by mehrdad-shokri** [comment]
@00AhmedMokhtar00 I guess error is telling that flutter upgrade didn't upgrade completely. Maybe use a VPN for ``upgrade``?

**Comment by hamdikahloun** [comment]
Hi @00AhmedMokhtar00 

If you install flutter somewhere that doesn't have rwx for the current user it won't work.

Thank you

**Comment by darshankawar** [comment]
@00AhmedMokhtar00 
As the error says `The flutter tool cannot access the file or directory. Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user`, try to have your SDK at a location outside of your current path which can be accessed by flutter tool properly.
If issue perists, please provide `flutter build appbundle --verbose`.

**Comment by maen9911** [comment]
still have the same issue

**Comment by hamdikahloun** [comment]
@maen9911 did you create the project or the flutter folder with sudo ? 
If you did, Can you please try `sudo flutter build appbundle --verbose`

**Comment by maen9911** [comment]
> @maen9911 did you create the project or the flutter folder with sudo ?
> If you did, Can you please try `sudo flutter build appbundle --verbose` or `cd android` and `sudo ./gradlew assembleRelease`

no the project were zip file from another computer 
`[  +50 ms] Running Gradle task 'bundleRelease'... (completed in 183ms)
[   +3 ms] "flutter appbundle" took 1,473ms.
[   +6 ms] null. The flutter tool cannot access the file or directory.
           Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:672:3)
           #2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:627:3)
           #3      _run (package:flutter_tools/src/base/error_handling_io.dart:474:7)
           <asynchronous suspension>
           #4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:568:12)
           #5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:473:28)
           #6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:492:35)
           #7      buildGradleApp (package:flutter_tools/src/android/gradle.dart:391:43)
           #8      _AndroidBuilderImpl.buildAab (package:flutter_tools/src/android/android_builder.dart:121:13)
           #9      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:90:26)
           #10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1033:18)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +314 ms] ensureAnalyticsSent: 255ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`

**Comment by maen9911** [comment]
> @maen9911 did you create the project or the flutter folder with sudo ?
> If you did, Can you please try `sudo flutter build appbundle --verbose` or `cd android` and `sudo ./gradlew assembleRelease`


this is the second command output

`Maens-MacBook-Pro:android maen$ sudo ./gradlew assembleRelease
sudo: unable to execute ./gradlew: Operation not permitted
Maens-MacBook-Pro:android maen$ `

**Comment by hamdikahloun** [comment]
```
cd android
chmod +x gradlew
./gradlew assembleRelease
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
