### ISSUE TITLE
Trouble installing flutter, stuck on running pub upgrade. 

### ISSUE THREAD

**Issue by heavenlyfist** [flutter/flutter#68362]
This is my output. Also just to be able to run the command I find that deleting the cache folder in bin helps run this command. Is this going to be fixed anytime soon or is it happening from my end? I am running on a Windows 8.1. Any help appreciated greatly this has been a nightmare and I am kind of a noob. 
![Screenshot (495)](https://user-images.githubusercontent.com/39553621/96320130-7cbfcb80-0fdf-11eb-818c-ee16de44eb6b.png)

**Comment by Abhishek01039** [comment]
Hi @heavenlyfist 
what you have done so far?
And please don't use screenshot.
Please refer to this https://flutter.dev/docs/get-started/install
Thanks.

**Comment by darshankawar** [comment]
@heavenlyfist 
I see that the command you are trying to run is `flutter docto -vv` whereas it should be `flutter doctor -v`. Fix this and try again to see if it works.
Also, where have you installed Flutter, ie location of SDK ? Please provide the path where have you installed it.
thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
