### ISSUE TITLE
Flutter Web : i got a lot of problems after upgrading Flutter

### ISSUE THREAD

**Issue by Abdelmjid-ASOUAB** [flutter/flutter#68369]
after upgrading Flutter in Windows to last version i got a lot of problems like Flutter compelator can't Identify some widget Properties like this:

[image](https://i.stack.imgur.com/NE9hi.png)

error:
The named parameter 'child' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'child'

**Flutter Doctor**
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [version 10.0.19041.572], locale fr-FR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)

• No issues found!
```
can you give a some solution !

**Comment by shashkiranr** [comment]
Did you try Flutter clean. If using Android Studio Try File-> Invalidate cache and restart

**Comment by sidrao2006** [comment]
Restarting the IDE also solves this error

**Comment by Abhishek01039** [comment]
RaisedButton class is obsolete, please use ElevatedButton instead.
https://api.flutter.dev/flutter/material/ElevatedButton-class.html
Thansk
