### ISSUE TITLE
Can't define border to a specific side of the new buttons (TextButton, ElevatedButton, and OutlinedButton)

### ISSUE THREAD

**Issue by lsarruda** [flutter/flutter#68368]
Hi,

After the last update of Flutter 1.22.2 • 2020-10-16 the new types of buttons have emerged that will give way to the old types.

I noticed that we now have new properties for the ButtonStyle, but I can no longer control the edges of the buttons.

My question is: It is really no longer possible to control the edges of the buttons or I am not knowing how to use the new properties.

In the past we could put a shape: Border, but now the shape properties are of the type: MaterialStateProperty.all <OutlinedBorder> which does not allow Border ().

We also have the side property of type: MaterialStateProperty.all <BorderSide> which also does not allow Border ().

Remembering that I only want a button with a Border: Top and Bottom.

Has anyone ever experienced this?

Thank you.

**Comment by emem365** [comment]
Hi @lsarruda , seems like you're having problems setting simple values with the new buttons.
These buttons take a property called ButtonStyle which take all the MaterialStateProperties which I agree can seem a little confusing. You can set the simple values using the static constructor of ButtonStyle called styleFrom.
For example, a code to get an elevated button with color green would be
```
ElevatedButton(
  style: ElevatedButton.styleFrom(primary: Colors.green),
)
```
We also have properties like `side` and `shape` here. Maybe they help you out achieving the desired effect.
Read about  [Button.styleFrom here](https://api.flutter.dev/flutter/material/ElevatedButton/styleFrom.html)

**Comment by pedromassangocode** [comment]
Hi @lsarruda 
As stated above you should use the `style` parameter and provide a shape parameter.

```dart
ElevatedButton(
        child: Text('Flutter'),
        onPressed: () {},
        style: ElevatedButton.styleFrom(
          shape: RoundedRectangleBorder(
            side: BorderSide(color: Colors.red),
            borderRadius: BorderRadius.circular(16)
          )
        ),
      )
```

**Comment by lsarruda** [comment]
Hi @pedromassango  and @emem365,

My problem is not to leave the colored border or to control the border, I already saw that I can do it in many ways.

My problem is to do something like this:

`FlatButton(
         shape: Border(
              top: BorderSide(color: Colors.black),
            ),
            child: Text(
              cidades[index].nome,
            ),
            onPressed: () => Navigator.pop(context, cidades[index].nome),
          ),`

The old buttons the shape property accepted a Border and the new shape property did not accept. With that I can't put a border only on the Top.

If anyone can help me.

Thank you.

**Comment by pedromassangocode** [comment]
Hi @Lsarruda
Thanks for making the issue clear.
This seems valid since currently there is no way to change the border of a specific side.

Tried to find a workaround using `ClipRRect` but does not seems to work as expected. It does not applies the radius on the topRight corner only.

```dart
          ClipRRect(
            borderRadius: BorderRadius.only(
              topRight: Radius.circular(50)
            ),
            child: ElevatedButton(
              child: Text('Flutter'),
              onPressed: () {},
            ),
          ),
```

![Screen Shot 2020-10-20 at 08 20 27](https://user-images.githubusercontent.com/67424416/96553507-29829d00-12ad-11eb-9e45-53cfb593cb78.png)


Cc @HansMuller

**Comment by HansMuller** [comment]
@pedromassango - To create an elevated button whose shape has one rounded corner:
```dart
ElevatedButton(
  style: ElevatedButton.styleFrom(
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.only(topRight: Radius.circular(24)),
    ),
  ),
  onPressed: () { },
  child: Text('ElevatedButton'),
)
```
<img width="145" alt="Screen Shot 2020-10-20 at 11 34 14 AM" src="https://user-images.githubusercontent.com/1377460/96629390-63ad6800-12c8-11eb-9478-67e54317b399.png">

**Comment by HansMuller** [comment]
@lsarruda - is this sufficient for your use case?
```dart
DecoratedBox(
  decoration: BoxDecoration(
    border: Border(
      top: BorderSide(color: Colors.black),
    ),
  ),
  child: TextButton(
    onPressed: () { },
    child: Text('TextButton'),
  ),
)
```

That produces:

<img width="106" alt="Screen Shot 2020-10-20 at 11 47 38 AM" src="https://user-images.githubusercontent.com/1377460/96630932-8a6c9e00-12ca-11eb-94cf-8c7d0143185d.png">

If you want a TextButton with black text, you can override the primary color used to create the TextButton's default style:

```dart
TextButton(
  style: TextButton.styleFrom(primary: Colors.black),
  onPressed: () { },
  child: Text('TextButton'),
)
```

**Comment by lsarruda** [comment]
Hi @HansMuller,

This solution that you sent does work. But the question here is not just to make the effect, but to know if this option was really removed from the buttons or if we are doing something wrong.

Thank you.

**Comment by HansMuller** [comment]
@lsarruda - you are not doing anything wrong, support for decorating the edges of a button's border was inadvertently left out of ButtonStyle. Fortunately, it's easy to use [composition with BoxDecoration](https://github.com/flutter/flutter/issues/68368#issuecomment-713068819) to get the same effect.

**Comment by maheshmnj** [comment]
This still looks valid as of today with stable 3.3 and master 3.6. I tried to add a border to one side of a outlined button Button couldn't find an option to do so.

```dart
  OutlinedButton(
     style: OutlinedButton.styleFrom(
     // top border no such property
     border: Border(
        top: BorderSide(
           color: Colors.black,
           width: 1,
        ),
     ) 
   ),
   onPressed: () {},
   child: const Text('Button'),
)
```

**Comment by HansMuller** [comment]
@lsarruda - if you're still interested (I realize that it's been a very long time), there's a solution in #116940 and a [DartPad example](https://dartpad.dev/?id=34adb8b46d34c933751bf8b21d06686f&channel=master) you can try out.
