### ISSUE TITLE
vm-service: Error: Unhandled exception 

### ISSUE THREAD

**Issue by transmeta01** [flutter/flutter#6837]
## Steps to Reproduce

**after running**
brew install ideviceinstaller
brew install ios-deploy

flutter --verbose
vm-service: Error: Unhandled exception:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _SimpleUri._toFilePath (dart:core/uri.dart:4423)
#1      _SimpleUri.toFilePath (dart:core/uri.dart:4417)
#2      _loadFile (loader.dart:407:26)
#3      _handleResourceRequest (loader.dart:510:5)
#4      _processLoadRequest (loader.dart:941:7)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

## Flutter Doctor
**(before installing ideviceinstaller and ios-deploy)**
flutter doctor 
Downloading Dart SDK 1.21.0-dev.3.0...
######################################################################## 100.0%
Building flutter tool...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.io                   ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and basic    ║
  ║ crash reports to Google in order to help Google contribute improvements to ║
  ║ Flutter over time. See Google's privacy policy:                            ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics reporting.        ║
  ╚════════════════════════════════════════════════════════════════════════════╝
  
Downloading Material fonts...                       1076ms
Downloading package sky_engine...                   768ms
Running 'flutter packages get' in sky_engine...     310ms
Building Dart SDK summary...                        1356ms
Downloading engine artifacts android-arm...         6564ms
Downloading engine artifacts android-arm-profile... 5644ms
Downloading engine artifacts android-arm-release... 5018ms
Downloading engine artifacts android-x64...         3962ms
Downloading engine artifacts android-x86...         4601ms
Downloading engine artifacts ios...                 7069ms
Downloading engine artifacts ios-profile...         7426ms
Downloading engine artifacts ios-release...         6102ms
Downloading darwin-x64 tools...                     9705ms
Downloading android-arm-profile/darwin-x64 tools... 1444ms
Downloading android-arm-release/darwin-x64 tools... 1395ms
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/kepler/flutter
    • Framework revision e384c0d982 (12 hours ago), 2016-11-13 22:09:03
    • Engine revision 84a060820a
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /Users/kepler/Library/Android/sdk
    • Platform android-24, build-tools 24.0.0
    • Java(TM) SE Runtime Environment (build 1.7.0_71-b14)

[-] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • None

**note: on another machine that has no installation of either ideviceinstaller or ios-deploy, the bug does not manifest.**

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
So the command reporting the error is just `flutter --verbose` correct?

**Comment by transmeta01** [comment]
any comment reports the error...after installation of ideviceinstaller and ios-deploy. 

**flutter --verbose** shows the state before the installation mentioned above.

**Comment by eseidelGoogle** [comment]
That's very unfortunate. :(  @danrubel any ideas?

**Comment by transmeta01** [comment]
brew remove ideviceinstaller
brew remove ios-deploy
rm -Rf flutter 

then re-install 
1-flutter
2-ideviceinstaller
3-ios-deploy

seem to have fixed the issue

**Comment by mit-mit** [comment]
Closing this as there have been no other reports of this, and it sounds like the original issue boiled down to a config issue on a single machine.
