### ISSUE TITLE
downgrade flutter to 1.22.0-12.1.pre failed

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#68378]
I upgraded flutter beta to the latest version, but found that it still has some errors in flutter web, so I plan to roll back this version to 1.22.0-12.1.pre, I executed flutter downgrade 1.22.0-12.1.pre, but The fallback is version 1.22.0， below is the command details:

haowmazss-MacBook-Pro:flutter_agent_web haowmazs$ flutter downgrade 1.22.0-12.1.pre
Downloading Dart SDK from Flutter engine 1d12d82d9cb54876f58044aa52198d53ec841c3d...
** Resuming transfer from byte position 138878976
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.8M  100 37.8M    0     0  10.9M      0  0:00:03  0:00:03 --:--:-- 10.9M
Building flutter tool...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...                                   0.3s
Downloading flutter_patched_sdk tools...                            1.0s
Downloading flutter_patched_sdk_product tools...                    1.0s
Downloading darwin-x64 tools...                                     2.9s
Downloading darwin-x64/font-subset tools...                         0.3s
Downgrade flutter to version 1.22.0
? [y|n]:

**Comment by stoneLee81** [comment]
Downgrade can only roll back to the version before the upgrade. If I wanted to roll back to the specified version before, how should I execute it? The flutter version [specified version number] command has been deleted

**Comment by sidrao2006** [comment]
Hey @stoneLee81 , you are right,  you can only downgrade to the version before the upgrade. So, now you have 2 options - 

1. The better option is to delete flutter and download it from [the flutter website](https://flutter.dev/docs/development/tools/sdk/releases).

2. Use `git checkout <version>` in the flutter sdk directory, but this will leave flutter in a detached state and you may not be notified of new releases.

**Comment by stoneLee81** [comment]
In fact, the previous “Flutter version xxx” specified version rollback command is very easy to use, why remove it?

**Comment by sidrao2006** [comment]
Not sure, but if you are able to use the version that you wanted to without any problems, please close this issue.
Thanks
