### ISSUE TITLE
Run flutter doctor --verbose command

### ISSUE THREAD

**Issue by FelixYin66** [flutter/flutter#68385]
When run flutter doctor --verbose,terminal report some problem.

Logs:
[☠] Connected device (the doctor check crashed)     ✗ Due to an error, the doctor check did not complete. If the error message       below is not helpful, please let us know about this issue at       https://github.com/flutter/flutter/issues.     ✗ FormatException: Unexpected character (at character 2)       [DVTPlugInCompatibilityUUIDifier] NSBundle       </Users/felixyin/Library/Applica...

**Comment by FelixYin66** [comment]
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected character (at character 2)
      [DVTPlugInCompatibilityUUIDifier] NSBundle
      </Users/felixyin/Library/Applica...
       ^

    • #0      _ChunkedJsonParser.fail
      (dart:convert-patch/convert_patch.dart:1404:5)
      #1      _ChunkedJsonParser.parseNumber
      (dart:convert-patch/convert_patch.dart:1271:9)
      #2      _ChunkedJsonParser.parse
      (dart:convert-patch/convert_patch.dart:936:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
      #5      JsonCodec.decode (dart:convert/json.dart:156:41)
      #6      XCDevice._getAllDevices
      (package:flutter_tools/src/macos/xcode.dart:310:48)
      <asynchronous suspension>
      #7      XCDevice.getAvailableIOSDevices
      (package:flutter_tools/src/macos/xcode.dart:422:53)
      #8      IOSDevices.pollingGetDevices
      (package:flutter_tools/src/ios/devices.dart:123:28)
      #9      PollingDeviceDiscovery._populateDevices
      (package:flutter_tools/src/device.dart:467:60)
      #10     PollingDeviceDiscovery.devices
      (package:flutter_tools/src/device.dart:457:12)
      #11     DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:171:20)
      #12     DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:975:55)
      #13     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #14     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #15     _rootRun (dart:async/zone.dart:1190:13)
      #16     _CustomZone.run (dart:async/zone.dart:1093:19)
      #17     _runZoned (dart:async/zone.dart:1630:10)
      #18     runZonedGuarded (dart:async/zone.dart:1618:12)
      #19     runZoned (dart:async/zone.dart:1547:12)
      #20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #21     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:191:9)
      #22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #23     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:59:47)
      #24     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:977:18)
      #25     _rootRunUnary (dart:async/zone.dart:1198:47)
      #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #27     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #28     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:696:45)
      #29     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #30     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #31     Future._asyncCompleteWithValue.<anonymous closure>
      (dart:async/future_impl.dart:567:7)
      #32     _rootRun (dart:async/zone.dart:1190:13)
      #33     _CustomZone.run (dart:async/zone.dart:1093:19)
      #34     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #35     _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:1037:23)
      #36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #38     _runPendingImmediateCallback
      (dart:isolate-patch/isolate_patch.dart:118:13)
      #39     _RawReceivePortImpl._handleMessage
      (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by darshankawar** [comment]
@FelixYin66 
What Flutter version are you on ? Can you try `flutter doctor -v` and see if it works ? What devices are connected when you try to run the command ?

**Comment by FelixYin66** [comment]
> @FelixYin66
> What Flutter version are you on ? Can you try `flutter doctor -v` and see if it works ? What devices are connected when you try to run the command ?

@darshankawar 
When I install Flutter 1.17~1.22 version and then run flutter doctor -v.Finally,report some errors.I don't connected any device.But I install Flutter 1.12 version ,run flutter doctor -v,no any error.Now I don't why.

**Comment by FelixYin66** [comment]
> @FelixYin66
> What Flutter version are you on ? Can you try `flutter doctor -v` and see if it works ? What devices are connected when you try to run the command ?

My Computer system version is mac os Catelina 10.15.7,Android Studio is 4.1

**Comment by darshankawar** [comment]
@FelixYin66 Here you said, `flutter doctor -v` reports some errors. What are the errors? Can you provide them here in text format ? I am still not clear on what Flutter channel you are on and on which version.
Also, you should use the latest stable version which is 1.22.2.  Please upgrade to it and then try `flutter doctor -v` to see if you still get the error.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by FelixYin66** [comment]
flutter doctor -v report some errors.I hope you can helop me solve this problem.

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/felixyin/Documents/Flutter/FlutterSDK/flutter2/flutter
    • Framework revision 7891006299 (6 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/felixyin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected character (at character 2)
      [DVTPlugInCompatibilityUUIDifier] NSBundle </Users/felixyin/Library/Applica...
       ^

    • #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
      #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
      #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
      #5      JsonCodec.decode (dart:convert/json.dart:156:41)
      #6      XCDevice._getAllDevices (package:flutter_tools/src/macos/xcode.dart:317:48)
      <asynchronous suspension>
      #7      XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcode.dart:429:53)
      #8      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:123:28)
      #9      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:467:60)
      #10     PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:457:12)
      #11     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:171:20)
      #12     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:975:55)
      #13     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #14     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #15     _rootRun (dart:async/zone.dart:1190:13)
      #16     _CustomZone.run (dart:async/zone.dart:1093:19)
      #17     _runZoned (dart:async/zone.dart:1630:10)
      #18     runZonedGuarded (dart:async/zone.dart:1618:12)
      #19     runZoned (dart:async/zone.dart:1547:12)
      #20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #21     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:191:9)
      #22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #23     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
      #25     _rootRunUnary (dart:async/zone.dart:1198:47)
      #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #27     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #29     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #30     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #31     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #32     _rootRun (dart:async/zone.dart:1190:13)
      #33     _CustomZone.run (dart:async/zone.dart:1093:19)
      #34     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 2 categories.
