### ISSUE TITLE
Flutter: How find created twilio room and join that room using firebase in Twilio_programmable_video?

### ISSUE THREAD

**Issue by Tarumoy** [flutter/flutter#68383]
I am trying to run the Twilio_programmable_video example in flutter from this link :  https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video/example
1. I have Created twilio account and upgrade it to Blaze plan as said here.
2. also created Firebase account  as said here.
Didn't do the NodeJs part as i am using firebase as backend.

3. I ran the command  `npm install -g firebase-tools`  in the terminal of Android studio in my project path
4. and follow all the step in the terminal of Android studio as it mentioned in the section "Setting up Firebase". 
5. Configure the environment variables for the Cloud Functions using this `firebase functions:config:set` in terminal of Android studio as mentioned in the link.
6. After that successfully deploy firebase using 'firebase deploy' in the terminal of Android studio.
7. then Configure Android as said.

Now i am run the project and it is asking the enter room name. How can i set the room name in twilio? How to know whether room created or not in twilio using firebase? 
![not_found](https://user-images.githubusercontent.com/5503269/96328985-6e68c280-1066-11eb-9bba-cf546bca3569.png)

**Comment by sidrao2006** [comment]
Hey @Tarumoy ,
This issue tracker is used for reporting bugs and feature requests for the flutter tool.

Since this is an error with a third party package, please report the issue in that repository.
Thanks

**Comment by darshankawar** [comment]
@Tarumoy 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and asking questions like this. If you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Tarumoy** [comment]
I understand. Thank you.
