### ISSUE TITLE
statefulwidget and state class are defined separately

### ISSUE THREAD

**Issue by bharatsingh100** [flutter/flutter#68396]
SatefulWidget class and State class can be merged, so that users don't have to define these classes separately

**Comment by sidrao2006** [comment]
Hey @bharatsingh100 , as mentioned in the flutter docs, the State element is managed separately so it needs a separate Widget

**Comment by sidrao2006** [comment]
Check out [this video](https://youtu.be/CXedqMlLo7M) and [this one](https://youtu.be/AqCMFXEmf3w) to understand it better.

**Comment by bharatsingh100** [comment]
thanks. it was helpful 👍

**Comment by Calamity210** [comment]
Along with a couple other, a major reason for the separated classes is that StatefulWidgets extend [Widget](https://api.flutter.dev/flutter/widgets/Widget-class.html), hence they too are immutable. To store **mutable** state, StatefulWidgets create a _mutable [State](https://api.flutter.dev/flutter/widgets/State-class.html)_ class.

**Comment by bharatsingh100** [comment]
Ok I got it 👍
