### ISSUE TITLE
Trying to build APK - Build failed with an exception Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 646

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#68395]
I am following the steps here https://flutter.dev/docs/deployment/android to build an APK (building an appbundle worked fine!), but getting an exception that does not say much...

Possibly related to

-  https://github.com/flutter/flutter/issues/58583
- https://stackoverflow.com/questions/61706981/flutter-stable-run-for-android-throwtoolexit-packageflutter-tools-src-base-c

```

flutter -v build apk --split-per-abi

[+4024 ms] FAILURE: Build failed with an exception.
[  +10 ms] * Where:
[   +4 ms] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 646
[   +4 ms] * What went wrong:
[ +116 ms] A problem occurred evaluating root project 'android'.
[   +6 ms] > A problem occurred configuring project ':app'.
[        ]    > The value for this property cannot be changed any further.
[   +3 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +9 ms] BUILD FAILED in 3s
[ +572 ms] Running Gradle task 'assembleRelease'... (completed in 5,3s)
[  +16 ms] "flutter apk" took 8 103ms.
[   +8 ms] Gradle task assembleRelease failed with exit code 1
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +115 ms] ensureAnalyticsSent: 92ms
[   +3 ms] Running shutdown hooks

```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
C:\Users\....\AndroidStudioProjects\.....>flutter -v doctor
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.16299.2045], locale hu-HU)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (9 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\....\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\.....\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by murshid1988** [comment]
I have the similar issue but on Linux

**Comment by edwinludik** [comment]
I had this exact same issue on my MacBook.

Downgrading Gradle fixed it for me:
android/build.gradle
```
...
 classpath 'com.android.tools.build:gradle:4.0.0'
...
```
and 
android/gradle/wrapper/gradle-wrapper.properties
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
...
```

**Comment by murshid1988** [comment]
In my case, I was using a slightly older version (**0.10.0+1**) of [firebase_admob](https://pub.dev/packages/firebase_admob). So I updated it to version **0.10.0+2**.

Then this brought another issue, which was
`Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-20.0 (com.google.guava:guava:20.0) and jetified-listenablefuture-1.0 (com.google.guava:listenablefuture:1.0)`

To fix this I had to add, 
`implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'`
in my **app/build.gradle**

**Comment by giorgio79** [comment]
No need for downgrade as these steps solved it for me! 

Apparently, you need to build in this order, otherwise the release build will complain of missing debug.jars or profile.jars...
```
flutter build apk --debug
flutter build apk --profile
flutter build apk --release
```
https://stackoverflow.com/questions/62394034/flutter-can-not-build-android-apk

**Comment by edwinludik** [comment]
Thanks! I hoped a better solution than downgrading would pop up in this thread.

**Comment by rebootcode** [comment]
Hi, this is seriously getting hit, are there any solution so far?

**Comment by joy2012bd** [comment]
> No need for downgrade as these steps solved it for me!
> 
> Apparently, you need to build in this order, otherwise the release build will complain of missing debug.jars or profile.jars...
> 
> ```
> flutter build apk --debug
> flutter build apk --profile
> flutter build apk --release
> ```
> 
> https://stackoverflow.com/questions/62394034/flutter-can-not-build-android-apk

Same error after giving 3rd command.

**Comment by jaguaarc388** [comment]
> I had this exact same issue on my MacBook.
> 
> Downgrading Gradle fixed it for me:
> android/build.gradle
> 
> ```
> ...
>  classpath 'com.android.tools.build:gradle:4.0.0'
> ...
> ```
> 
> and
> android/gradle/wrapper/gradle-wrapper.properties
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ...
> ```

This Worked for me

**Comment by jpbassinello** [comment]
Same issue here.

But for me, the build doesn´t fail if I run

`flutter build apk`
or
`fluter build appbundle`

it fails only with the `--split-per-abi` flag

**Comment by heshanka** [comment]
@jpbassinello Hi, Im having the same issue at the moment. Did you manage to solve it?

**Comment by moak13** [comment]
Hi everyone, I am currently facing the same issue. I downgraded just like this post suggested, I can't even run a debug app anymore. Has anyone found a reliable solution. I am currently stuck with flutter 1.22.6 due to some pending projects. Kindly assist on how to get this fixed.

> I had this exact same issue on my MacBook.
> 
> Downgrading Gradle fixed it for me:
> android/build.gradle
> 
> ```
> ...
>  classpath 'com.android.tools.build:gradle:4.0.0'
> ...
> ```
> 
> and
> android/gradle/wrapper/gradle-wrapper.properties
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ...
> ```

**Comment by moak13** [comment]
Hi everyone, I am currently facing the same issue. I downgraded just like this post suggested, I can't even run a debug app anymore. Has anyone found a reliable solution. I am currently stuck with flutter 1.22.6 due to some pending projects. Kindly assist on how to get this fixed.

> I had this exact same issue on my MacBook.
> 
> Downgrading Gradle fixed it for me:
> android/build.gradle
> 
> ```
> ...
>  classpath 'com.android.tools.build:gradle:4.0.0'
> ...
> ```
> 
> and
> android/gradle/wrapper/gradle-wrapper.properties
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ...
> ```
