### ISSUE TITLE
[SplashScreen]How to use Interface SplashScreen

### ISSUE THREAD

**Issue by ipipip1735** [flutter/flutter#68398]
[the document](https://flutter.dev/docs/development/ui/advanced/splash-screen) describes how to Implement a custom splash View，but it seems not to be full.
![image](https://user-images.githubusercontent.com/12948715/96335731-2faa2b00-10ad-11eb-80f1-7a906a2afd6a.png)

i find [the post](https://stackoverflow.com/questions/59814406/flutter-splashscreen-implementation-with-custom-view) as my problem. what to do with the interface SplashScreen?

**Comment by lablnet** [comment]
@ipipip1735  
You can use plugin to create splash screen for cross platform and then you can customize it according to your need/.

here is ref: https://pub.dev/packages/flutter_native_splash

**Comment by TahaTesser** [comment]
Hi @ipipip1735 
I see there's an open issue addressing the case you described. https://github.com/flutter/website/issues/3938
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
