### ISSUE TITLE
Bad Centering in Gallery Demos

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6839]
At least 4 demos regressed from the body-stretching change last week @Hixie, @HansMuller.  I'm going to use older gallery builds for demos for now until these are fixed.

See screenshots:
![img_0690](https://cloud.githubusercontent.com/assets/11857803/20275220/9121742c-aa4c-11e6-8cc9-10959074a9e0.png)
![img_0691](https://cloud.githubusercontent.com/assets/11857803/20275223/934bface-aa4c-11e6-8913-0adebd5b2ceb.png)
![img_0694](https://cloud.githubusercontent.com/assets/11857803/20275227/95f0fb94-aa4c-11e6-96f8-e806156915fa.png)
![img_0695](https://cloud.githubusercontent.com/assets/11857803/20275231/9ab9c890-aa4c-11e6-82c2-702a1b6e177d.png)

**Comment by b-strauss** [comment]
I also saw this effect last week as I recreated your dev summit demo steps for some colleagues - whoops ;). The stuff inside Column didn't stretch to the whole body of the Scaffold.

**Comment by HansMuller** [comment]
This appears go be due to https://github.com/flutter/flutter/pull/6692. Investigating...

**Comment by sethladd** [comment]
Good catch!

**Comment by Hixie** [comment]
@abarth this was the fallout you were expecting
