### ISSUE TITLE
AGP 4.1 not allowed -WError in some official flutter plugin

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#68400]
e.g. camera, shared_preferences

**Comment by hamdikahloun** [comment]
Hi @hamberluo 

Flutter don't support AGP 4.0+ yet - see #58247

Thank you

**Comment by hamberluo** [comment]
@hamdikahloun 
In my project, it works with AGP 4.0.2.

**Comment by darshankawar** [comment]
@hamberluo 
Can you elaborate when you say `it works in my project`. Does it use Flutter first party plugins ? Per the comment [here](https://github.com/flutter/flutter/issues/68011#issuecomment-708549779), Flutter doesn't officially support 4.1 AGP for all plugins yet. So I'd suggest you to follow-up [here](https://github.com/flutter/flutter/issues/58247) for updates and any questions.
I am going ahead and closing it as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
