### ISSUE TITLE
Exception when running flutter linux desktop app

### ISSUE THREAD

**Issue by malown** [flutter/flutter#68401]
This is the output i get when i try to run a newly created linux desktop app:

> $ flutter run
> Launching lib/main.dart on Linux in debug mode...
> CMake Error at CMakeLists.txt:21 (target_compile_features):             
>   target_compile_features no known features for CXX compiler            
>                                                                         
>   "Clang"                                                               
>                                                                         
>   version 6.0.0.                                                        
> Call Stack (most recent call first):                                    
>   CMakeLists.txt:44 (apply_standard_settings)                           
>                                                                         
>                                                                         
> Building Linux application...                                           
> Exception: Unable to generate build files

I am running Pop_OS 20.04 and installed flutter (1.23.0-18.0.pre) via snap

_______________________________

flutter doctor output:
> [✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale en_US.UTF-8)
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
> [✓] Linux toolchain - develop for Linux desktop
> [!] Android Studio (not installed)
> [✓] VS Code (version 1.50.1)
> [✓] Connected device (1 available)

**Comment by sidrao2006** [comment]
Hello @malown ,
Could you please post the output of `flutter run -v`
Thank you!

**Comment by malown** [comment]
> $ flutter run -v
> [  +83 ms] executing: [/home/malown/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
> --pretty=format:%H
> [  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [        ] 37ebe3d82a9d5faeda7d3c1a6ad193030210a2cc
> [        ] executing: [/home/malown/snap/flutter/common/flutter/] git tag --points-at HEAD
> [   +9 ms] Exit code 0 from: git tag --points-at HEAD
> [        ] 1.23.0-18.0.pre
> [   +7 ms] executing: [/home/malown/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic
> @{u}
> [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/dev
> [        ] executing: [/home/malown/snap/flutter/common/flutter/] git ls-remote --get-url origin
> [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [  +35 ms] executing: [/home/malown/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
> [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] dev
> [  +36 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +51 ms] executing: /home/malown/Android/Sdk/platform-tools/adb devices -l
> [  +39 ms] List of devices attached
> [   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +160 ms] Generating
> /media/INTERN2/Projekte/geometrysolver/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistr
> ant.java
> [  +62 ms] Starting incremental build...
> [   +3 ms] Initializing file store
> [   +7 ms] Skipping target: gen_localizations
> [   +7 ms] complete
> [   +3 ms] Launching lib/main.dart on Linux in debug mode...
> [   +4 ms] /home/malown/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
> /home/malown/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapsho
> t --sdk-root
> /home/malown/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
> --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
> -Ddart.developer.causal_async_stacks=true --output-dill
> /tmp/flutter_tools.WENXLU/flutter_tool.SLPYSF/app.dill --packages .packages -Ddart.vm.profile=false
> -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
> --initialize-from-dill build/01094840f26094a3fe371d8be6b9cb48.cache.dill.track.dill --flutter-widget-cache
> [  +15 ms] Building Linux application...
> [  +11 ms] <- compile package:geometrysolver/main.dart
> [   +1 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
> /media/INTERN2/Projekte/geometrysolver/linux
> [  +36 ms] CMake Error at CMakeLists.txt:21 (target_compile_features):
> [   +2 ms]   target_compile_features no known features for CXX compiler
> [        ]   "Clang"
> [        ]   version 6.0.0.
> [        ] Call Stack (most recent call first):
> [        ]   CMakeLists.txt:44 (apply_standard_settings)
> [        ] -- Configuring incomplete, errors occurred!
> [        ] See also "/media/INTERN2/Projekte/geometrysolver/build/linux/debug/CMakeFiles/CMakeOutput.log".
> [        ] See also "/media/INTERN2/Projekte/geometrysolver/build/linux/debug/CMakeFiles/CMakeError.log".
> [   +9 ms] Building Linux application... (completed in 0.1s)
> [+6297 ms] Exception: Unable to generate build files
> [   +1 ms] "flutter run" took 6,740ms.
> [   +4 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
>            <asynchronous suspension>
>            #2      FlutterCommand.verifyThenRunCommand
>            (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
>            #3      _rootRunUnary (dart:async/zone.dart:1198:47)
>            #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
>            #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
>            #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
>            #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
>            #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
>            #12     _rootRunUnary (dart:async/zone.dart:1198:47)
>            #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
>            #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
>            #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
>            #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
>            #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
>            #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
>            #19     _rootRun (dart:async/zone.dart:1190:13)
>            #20     _CustomZone.run (dart:async/zone.dart:1093:19)
>            #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
>            #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
>            #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
>            #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
>            #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
>            #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
>            
>            
> [ +254 ms] ensureAnalyticsSent: 252ms
> [   +2 ms] Running shutdown hooks
> [        ] Shutdown hook priority 4
> [  +11 ms] Shutdown hooks complete
> [   +1 ms] exiting with code 1

**Comment by TahaTesser** [comment]
hI @malown 
Based on your logs, clang seems to be 6.0.0
```
[ +36 ms] CMake Error at CMakeLists.txt:21 (target_compile_features):
[ +2 ms] target_compile_features no known features for CXX compiler
[ ] "Clang"
[ ] version 6.0.0.
[ ] Call Stack (most recent call first):
[ ] CMakeLists.txt:44 (apply_standard_settings)
[ ] -- Configuring incomplete, errors occurred!
[ ] See also "//linux/debug/CMakeFiles/CMakeOutput.log".
[ ] See also "/*************/build/linux/debug/CMakeFiles/CMakeError.log".
```
Please check https://ubuntu.pkgs.org/20.04/ubuntu-universe-i386/clang-10_10.0.0-4ubuntu1_i386.deb.html

Can you please provide your `flutter doctor -v` with verbose
Thank you

**Comment by malown** [comment]
> Please check https://ubuntu.pkgs.org/20.04/ubuntu-universe-i386/clang-10_10.0.0-4ubuntu1_i386.deb.html
> 
> Can you please provide your `flutter doctor -v` with verbose

It looks like the snap package comes with it's own clang

> $ flutter -v doctor
> Downloading android-arm-profile/linux-x64 tools...                  1.3s
> Downloading android-arm-release/linux-x64 tools...                  0.8s
> Downloading android-arm64-profile/linux-x64 tools...                0.5s
> Downloading android-arm64-release/linux-x64 tools...                0.5s
> Downloading android-x64-profile/linux-x64 tools...                  0.6s
> Downloading android-x64-release/linux-x64 tools...                  0.5s
> [✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.23.0-18.0.pre at /home/malown/snap/flutter/common/flutter
>     • Framework revision 37ebe3d82a (6 days ago), 2020-10-13 10:52:23 -0700
>     • Engine revision 6634406889
>     • Dart version 2.11.0 (build 2.11.0-213.0.dev)
> 
> [!] Android toolchain - develop for Android devices
>     • Android SDK at /usr/lib/android-sdk
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
>       instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
>     ✗ No valid Android SDK platforms found in /usr/lib/android-sdk/platforms. Directory was empty.
>     • Try re-installing or updating your Android SDK,
>       visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
>       instructions.
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
>     • cmake version 3.10.2
>     • ninja version 1.8.2
>     • pkg-config version 0.29.1
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
>       instructions).
> 
> [✓] VS Code (version 1.50.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.15.0
> 
> [✓] Connected device (1 available)
>     • Linux (desktop) • linux • linux-x64 • Linux
> 
> ! Doctor found issues in 2 categories.
>

**Comment by TahaTesser** [comment]
Hi @malown 
For Flutter on snap related issues, please file an issue on their dedicated Github [repository](https://github.com/canonical/flutter-snap/issues) 
As this isn't an issue with a standard git clone installation 
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
