### ISSUE TITLE
[url_launcher] Uri.toString() for "mailto" does not encode spaces properly (`+` instead of `%20`)

### ISSUE THREAD

**Issue by Delgan** [flutter/flutter#68406]
Hi.

Supposing one wants to encode a `mailto` subject or body containing spaces. It's not clear if there should be converted to `+` (`encodeQueryComponent()`) or to `%20` (`encodeComponent()`).

There is two examples in the [`url_launcher`](https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher) Readme and they do not use the same encoding: 

> `mailto:smith@example.org?subject=News&body=New%20plugin`

> `mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21`.

The second one is automatically constructed after calling `Uri(...).toString()`. The main issue is that the subject will be displayed like this in the mail app:

> Example+Subject+&+Symbols+are+allowed!

The mail app does not seems to handle `+` correctly, while it works fine using `%20`.

I tested this with `url_launcher` v5.7.5, `flutter` v1.23.0, `dart` v2.10.0, Android v8.0.0 and opening the link with Gmail app.

Should the spaces be automatically converted to `%20` instead to ensure portability?

Related:
* #10032
* #42279
* https://github.com/flutter/plugins/pull/2172

**Comment by sidrao2006** [comment]
Hey @Delgan , since this is an issue with `Uri` which is a part of the dart core library, please open this issue [here](https://github.com/dart-lang/sdk)

**Comment by Delgan** [comment]
@sidrao2006 Thanks for pointing that out. :+1: 

I moved the issue to https://github.com/dart-lang/sdk/issues/43838.
