### ISSUE TITLE
performence issue and Leakage of information

### ISSUE THREAD

**Issue by mosheee** [flutter/flutter#68408]
If you have found a performance problem, then fill out the template below.
     Please read our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

1.  I create a listview.builder of checkBoxListTile according the number of people which specified a screen before and pass as an argument. 
The checkBoxListTile holds TextFormField and checkBox . The list of those CheckBoxListTile are locate in Form which controll the TextFormFields. 
The problem is when i fill in the TextFormFields at the top of the list and then scroll d
[dart_devtools_2020_10_17-1602954509193000.zip](https://github.com/flutter/flutter/files/5396106/dart_devtools_2020_10_17-1602954509193000.zip)
[WhatsApp Video 2020-10-17 at 20.06.58.zip](https://github.com/flutter/flutter/files/5396107/WhatsApp.Video.2020-10-17.at.20.06.58.zip)

own for fill in the rest,the string is written above has been deleted.
the performence are poor at this stage.

2. https://gist.githubusercontent.com/mosheee/a5a33da60bb58bee62271582728f833b/raw/e12ee7338f609a6f285014b2a59b7a862b92a69f/Main.dart

https://gist.githubusercontent.com/mosheee/a5a33da60bb58bee62271582728f833b/raw/e12ee7338f609a6f285014b2a59b7a862b92a69f/Main.dart

4. 
[WhatsApp Video 2020-10-17 at 20.06.58.zip](https://github.com/flutter/flutter/files/5396107/WhatsApp.Video.2020-10-17.at.20.06.58.zip)

5.  

[dart_devtools_2020_10_17-1602954509193000.zip](https://github.com/flutter/flutter/files/5396106/dart_devtools_2020_10_17-1602954509193000.zip)

**Target Platform: android**
**Target OS version/browser:**
**Devices: redmi 4**

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.572], locale he-IL)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (2 months ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\win10\AppData\Local\android\Sdk
    • Platform android-29, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Redmi Note 4 (mobile) • d044e0940504 • android-arm64 • Android 7.0 (API 24)

• No issues found!

```
```

**Comment by iapicca** [comment]
@mosheee 

>    [...] The problem is when i fill in the [TextFormFields](https://api.flutter.dev/flutter/material/TextFormField-class.html) at the top of the list and then scroll [...]

I believe the problem you are encountering isn't caused by flutter, but is caused by your implementation 
specifically using both a [ListView.builder](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html) and **_not_** providing a [TextEditingController](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html)
both choices are fine separately or if you don't care about storing the data while scrolling (but apparently you do care)

you may run the code below on [dartpad](https://dartpad.dartlang.org/) and see the correct behavior

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _numberOfPlayers = 1000;
  List<TextEditingController> _controllers;
  GlobalKey<FormState> _formKey;

  @override
  void initState() {
    _formKey = GlobalKey<FormState>();
    _controllers = [
      for (int i = 0; i < _numberOfPlayers; i++) TextEditingController()
    ];
    super.initState();
  }

  @override
  void dispose() {
    for (var _controller in _controllers) {
      _controller?.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Material(
        child: Form(
          key: _formKey,
          child: ListView.builder(
            itemCount: _numberOfPlayers,
            itemBuilder: (context, index) => Padding(
           
              padding: const EdgeInsets.only(
                bottom: 10,
              ),
              child: PlayerWidget(
                index: index,
                controller: _controllers[index],
              ),
            ),
          ),
        ),
      );
}

class PlayerWidget extends StatelessWidget {
  PlayerWidget({
    @required this.index,
    @required this.controller,
  }) : super(key: ValueKey(index));
  final int index;
  final TextEditingController controller;
  @override
  Widget build(BuildContext context) => ListTile(
        leading: Text('player $index'),
        title: TextFormField(controller: controller),
      );
}
```
</details>

please not that this isn't a workaround, note the description of **ListView._builder_**
> This constructor is appropriate for list views with a large (or infinite) number of children because the builder is called only for those children that are actually visible.

therefore it is expected that the widgets are disposed when not visible
