### ISSUE TITLE
Update Dart SDK once dependent packages are fixed.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#6840]
We currently can't update to a new Dart SDK pending fixes in a few dependent packages.  This meta issue tracks progress.

**Background:**  A [recent change](https://github.com/dart-lang/yaml/issues/21) in the `yaml` package now treats duplicate map entries as an error which bubbles up through `pub` if you have an offending pubspec.  The rub is that there are packages out there on which we depend, [json_schema](https://pub.dartlang.org/packages/json_schema), for example, that in fact contain duplicate entries.  

```
[~/src/git/clones/flutter] (master) $  flutter update-packages --upgrade
Building flutter tool...
Error on line 27, column 3 of /Users/pquitslund/.pub-cache/hosted/pub.dartlang.org/json_schema-1.0.3/pubspec.yaml: Duplicate mapping key.
  yaml: "^2.1.0"
```

**Next steps.**

To get us on track we need:

  * [x] json_schema [fixed](https://github.com/patefacio/json_schema/pull/6)
  * [x] json_schema published
  * [x] id [fixed](https://github.com/patefacio/id/pull/2) _[DEP DROPPED]_
  * [x] id published _[DEP DROPPED]_
  * [x] ebisu [fixed](https://github.com/patefacio/ebisu/pull/1) _[DEP DROPPED]_
  * [x] ebisu published _[DEP DROPPED]_

Then:
  * [x] land new Dart SDK in flutter tools (https://github.com/flutter/flutter/pull/6861)
  * [x] ping https://github.com/flutter/flutter/issues/5865 to let us know we can try const asserts again

Finally:

  * [x] fix the uploaded `json_schema` to not include any references to `drudge` (@patefacio)

FYI @abarth @Hixie (for why SDK rolls have stalled)

**Comment by pq** [comment]
Update: `ebisu` needs fixing as well.

**Comment by nex3** [comment]
The duplicate mapping thing comes from dart-lang/yaml#21, a bug that I fixed a month ago. The YAML language doesn't allow duplicate keys in mappings, but we were parsing them incorrectly and only including the latter definition. We now correctly emit a syntax error.

**Comment by kevmoo** [comment]
The description from @nex3 is accurate. Worth mentioning: this means that packages that were already published and "working" with duplicate keys now fail, which as an unfortunate and unmitigated regression.

**Comment by patefacio** [comment]
Did not know json_schema was being used. I'll just remove dependency on ebisu which transitively removes dependency on id and I'll update those later. Ebisu is what I use(d) to [generate the library code](https://github.com/patefacio/json_schema/blob/master/codegen/json_schema.ebisu_dart.dart#L81-L354) and I created it well before the *marvelous* source_gen we heard so much about at summit :)

**Comment by patefacio** [comment]
I published json_schema 1.0.5 and id and ebisu are no longer dependencies.

**Comment by pq** [comment]
Thank you @patefacio!

Related question, while we've got you.  We used to pin our dependency on `1.0.3` since `1.0.4` introduced the following warning about the "drudge" package:

```
[flutter_tools] pub get
Resolving dependencies...
...
Got dependencies!
Precompiling executables...
Loading source assets...
A transformer imported unknown package "drudge" (in "package:drudge/drudge.dart").
exit code 0
```

With `1.0.5` we obviously get this warning back.  Any thoughts on where it's coming from?

Thanks again for your quick help!

**Comment by patefacio** [comment]
I'm not too up on what transformers do - I don't specify any in json_schema. But one of them likely does things with scripts in the bin folder or my codegen folder? I use code generation and I wrote a little package (drudge) to check the filesystem and auto-regenerate code when sources are saved. When it generates source it generates a drudge script that I can then run tailored to the package I'm writing. My approach to developing is atypical - I model the code artifacts (libs, classes, members) with ebisu and generate the bulk. Honestly don't know why you would see that warning now that ebisu and id are not dependencies (they did have dev_dependency on drudge). Is this a *clean* build - whatever that means? On [travis](https://travis-ci.org/patefacio/json_schema/jobs/175928217) that warning does not happen.

**Comment by patefacio** [comment]
BTW - I thought allowing duplicates in pubspec was a great feature. Often I would have a dependency on some packages and due to pub constraints it would not complete. Very painful to figure out. So when you want to take your chances and move forward anyway you could just *copy* that specified dependency that caused trouble down into the dependency_override section and you'd be back in business, at least for a while. Or similarly you could throw in a path package spec in override section to quickly try out your own code of a dependency update and remove later once published.

**Comment by nex3** [comment]
The transformer import error is kind of a misnomer—it also comes up when an executable in bin/ imports a package that's not defined in the package's dependencies.

@patefacio The pubspec still allows `dependency_overrides` to override packages that are already defined in `dependencies`. The only thing that changed is that `dependencies` can't define two constraints for the same package.

**Comment by pq** [comment]
> The transformer import error is kind of a misnomer—it also comes up when an executable in bin/ imports a package that's not defined in the package's dependencies.

That's really helpful.  Thanks!  It'd be great if the message where less ambiguous, but then messages are hard!

Looking at the [uploaded package](https://storage.googleapis.com/pub.dartlang.org/packages/json_schema-1.0.5.tar.gz) I see `drudge.json_schema.dart` which appears to be the culprit.  @patefacio : could you consider uploading a version that does not include this file?  That will be nicer for folks downstream.  (I was tempted to open an issue on https://github.com/patefacio/json_schema but the issue tracker isn't enabled; if you turn it on, I'll be happy to file an issue there.)  Again, thanks for the help!

(I'll keep this issue open until we get this last bit sorted.)

**Comment by patefacio** [comment]
That file does exist for me locally but was never checked into the pubspec.yaml's referenced github repo. I would've thought that meant it would not be published but maybe pub update does not use something like 'git ls-files' and just publishes all files in folders like *bin*. I've removed the file, bumped the version and republished.

**Comment by nex3** [comment]
`pub publish` does use `git ls-files`, but only to respect `.gitignore`. We want to be able to publish generated files that aren't ignored but might also not be checked into git.

**Comment by patefacio** [comment]
ok. I hope we are good here now.

**Comment by pq** [comment]
Thanks so much!

Updated our dep w/ dbacf77 and the import errror is gone.

🍻
