### ISSUE TITLE
App Store Connect Operation Error. Invalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist.

### ISSUE THREAD

**Issue by youraleangseng** [flutter/flutter#68404]
## Flutter Doctor

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-KH)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
<img width="746" alt="Screen Shot 2020-10-17 at 9 30 37 PM" src="https://user-images.githubusercontent.com/19517411/96339669-663d7100-10c0-11eb-8285-6a90fea78d82.png">

**Comment by bwysistemas** [comment]
Run `flutter clean`, after change **MinimumOSVersion** in **Runner/Flutter/AppFrameworkInfo.plist** for your minimum OS Version (in my case is 10.0), and change the **iOS Deployment Target** in **Project Runner** and **Target Runner** to the same OS Version.
It works for me.

**Comment by darshankawar** [comment]
@youraleangseng Try [this](https://github.com/flutter/flutter/issues/67492#issuecomment-704991881) solution and see if it works for you. After updating minimum OS version, don't forget to run `flutter clean`.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
