### ISSUE TITLE
Flutter 1.22.1 iOS 14.0 crash

### ISSUE THREAD

**Issue by hardypatel30** [flutter/flutter#68426]
Hello folks!  Is anyone facing copy paste in ... 

    TextFormfield
copy paste functionality ? Please help me for below issues :

Configurations :

> os : 14.1  
> device : iphone 6s
> flutter version : 1.22.1

Here is the firebase logs from Crashlytics:

> Precompiled_Stub_CallAutoScopeNative + 80
> Precompiled__EventHandler_15069316__timerMillisecondClock_15069316_1006 + 40

Other Crashlytics crash reports :
> Metal -> invocation function for block in MTLCompilerFSCache::getElement(MTLUINT256_t, void**, unsigned long*) + 352
> Crashed: io.flutter.1.raster  -> SIGABRT ABORT 0x00000001cc29e95c

Note : This is one fix problem i found other are many with **iphone6s** and **iphone7** having **14.1.0** os  .

- randomly scroll app with sliver and app just stops 

- bottomsheet having cliprect causes app crash.

**Comment by sidrao2006** [comment]
Hello @hardypatel30 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v`
Thank you!

**Comment by PixelToast** [comment]
Thanks for taking the time to file an issue, along with the above logs could you provide a detailed description of how to reproduce this crash?

**Comment by sanekyy** [comment]
![image](https://user-images.githubusercontent.com/18647037/96454668-df55d900-1224-11eb-84ac-e3fbc7bf55f5.png)

**Comment by brianb-sf** [comment]
We see this crash as well on an iPhone 11 Pro on iOS 14.0.1 on a non-released beta version of our application. We do not have any deterministic steps to reproduce the crash but our Crashlytics logs match the screenshot above exactly.

<summary>Flutter Doctor Output</summary>

<details>
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at
      /Users/brianblanchard/workspaces/sf/mobile-indigo/vendor/flutter
    • Framework revision f30b7f4db9 (3 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/brianblanchard/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • E7985C65-ED26-4B86-B785-19265342EF88 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
</details>

**Comment by pawlowskim** [comment]
We also have the same problem on production. We don't have any re-producible example.  Crash log: https://gist.github.com/pawlowskim/aac5f1f52dacf404dbbf1877c2da91f1
flutter: 1.22.2

**Comment by ITyongzhen** [comment]
I have exactly the same problem

![image](https://user-images.githubusercontent.com/23075407/98759664-88e74f00-240c-11eb-8d74-b55242aa6c89.png)

**Comment by NicolasCELLA** [comment]
same issue
<img width="1511" alt="Capture d’écran 2020-12-07 à 11 05 25" src="https://user-images.githubusercontent.com/27723625/101337569-1e46f900-387c-11eb-9b17-9bf41e33ff26.png">

**Comment by chensifang** [comment]
A lot of crash！ A lot of crash！

Flutter Version：1.22.4

0 Metal | -[MTLIOAccelCommandBuffer commandBufferResourceInfo] + 12
-- | --
1 AGXMetalA11 | 0x00000001bb84e000 + 500280
2 AGXMetalA11 | 0x00000001bb84e000 + 657580
3 Flutter | GrMtlCommandBuffer::getBlitCommandEncoder() (GrMtlCommandBuffer.mm:45)
4 Flutter | GrMtlGpu::onWritePixels(GrSurface*, int, int, int, int, GrColorType, GrColorType, GrMipLevel const*, int, bool) (GrMtlGpu.mm:0)
5 Flutter | GrGpu::writePixels(GrSurface*, int, int, int, int, GrColorType, GrColorType, GrMipLevel const*, int, bool) (GrGpu.cpp:465)
6 Flutter | GrGpu::createTexture(SkISize, GrBackendFormat const&, GrRenderable, int, SkBudgeted, GrProtected, GrColorType, GrColorType, GrMipLevel const*, int) (GrGpu.cpp:205)
7 Flutter | GrResourceProvider::createTexture(SkISize, GrBackendFormat const&, GrColorType, GrRenderable, int, SkBudgeted, GrProtected, GrMipLevel const*, int) (SkTemplates.h:150)
8 Flutter | _ZNSt3__110__function6__funcIZN15GrProxyProvider27createMippedProxyFromBitmapERK8SkBitmap10SkBudgetedE3$_1NS_9allocatorIS7_EEFN14GrSurfaceProxy18LazyCallbackResultEP18GrResourceProviderRKNSA_15LazySurfaceDescEEEclEOSD_SG_ (SkRefCnt.h:320)
9 Flutter | GrSurfaceProxyPriv::doLazyInstantiation(GrResourceProvider*) (SkRefCnt.h:320)
10 Flutter | GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipmapped, SkBackingFit, SkBudgeted) (GrProxyProvider.cpp:305)
11 Flutter | GrBitmapTextureMaker::refOriginalTextureProxyView(GrMipmapped) (SkRefCnt.h:320)
12 Flutter | SkImage::MakeCrossContextFromPixmap(GrDirectContext*, SkPixmap const&, bool, bool) (SkRefCnt.h:298)
13 Flutter | _ZNSt3__110__function6__funcIZN7flutterL17UploadRasterImageE5sk_spI7SkImageEN3fml7WeakPtrINS2_9IOManagerEEERKNS6_7tracing9TraceFlowEE3$_3NS_9allocatorISE_EEFvvEEclEv (SkRefCnt.h:298)
14 Flutter | fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) (mutex:501)
15 Flutter | _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZZN7flutter12ImageDecoder6DecodeENS2_6RefPtrINS5_15ImageDescriptorEEEjjRKNS_8functionIFvNS5_13SkiaGPUObjectI7SkImageEEEEEEN3$_1clEvEUlvE_EENS_9allocatorISK_EEFvvEEclEv (functional:1757)
16 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:122)
17 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
18 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
19 CoreFoundation | ___CFRunLoopDoTimer + 864
20 CoreFoundation | ___CFRunLoopDoTimers + 248
21 CoreFoundation | ___CFRunLoopRun + 1844
22 CoreFoundation | CFRunLoopRunSpecific + 436
23 Flutter | fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
24 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:96)
25 libsystem_pthread.dylib | __pthread_body + 128
26 libsystem_pthread.dylib | _pthread_start + 44

**Comment by thinhphamlifetechvn** [comment]
@NicolasCELLA same issue 

![Screen Shot 2020-12-25 at 10 51 02](https://user-images.githubusercontent.com/51937117/103117926-49fd1800-469f-11eb-9589-5cd21934d1d5.png)

**Comment by sxsdjkk** [comment]
Same issue！
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/10103345/103214189-c2d3cc80-494a-11eb-8ddb-90468e99e4a9.png">

**Comment by PixelToast** [comment]
As this issue is closed and is not being looked at by the team, please file new issues for each unique crash report.

**Comment by hardypatel30** [comment]
But how can they close it if the issue is still therr and everyone is having crash report?
And what if those another issues get closes by boat itself? 
@PixelToast

**Comment by PixelToast** [comment]
@hardypatel30

This issue was closed because the original poster unfortunately did not get back to us with the details needed to properly track the issue (full crash log, flutter version). Additionally, none of the other posts by other users contain crash logs appear to be related to the original.
