### ISSUE TITLE
1.22.2 - Flutter plugin not installed; this adds Flutter specific functionality.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#68429]
How do I fix this android plugin error? This error is being come after upgrade to 1.22.2 

**flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 1 category.
```

**Android Studio**
<img width="1010" alt="Screenshot 2020-10-18 at 12 51 35" src="https://user-images.githubusercontent.com/34953062/96361127-c3790700-1140-11eb-8d31-dc5d828e00de.png">

**Comment by sidrao2006** [comment]
@bhanuka96 
The plugin warnings do not matter. See [this](https://github.com/flutter/flutter/issues/67986#issuecomment-707881534) comment for reference. Also this is similar to [67986](https://github.com/flutter/flutter/issues/67986).

_Originally posted by @darshankawar in https://github.com/flutter/flutter/issues/68274#issuecomment-709924282_

**Comment by darshankawar** [comment]
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986) 
Even if you are getting those errors, you should be able to build without any issues. See the above referred link for more details.

**Comment by kyughost** [comment]
Hey @bhanuka96  try this line of code, worked for me 

`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by bhanuka96** [comment]
@kyughost now working

**Comment by westindiantech** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks this worked for me just now.

**Comment by Juenchine** [comment]
@kyughost thank you from France ;) it works.

**Comment by kyughost** [comment]
> @kyughost thank you from France ;) it works.

My pleasure, from Congo

**Comment by hebaothman** [comment]
@kyughost Thanks it worked :)

**Comment by MuttakinHasib** [comment]
@kyughost Thank you from Bangladesh :) it works

**Comment by Raphaelmbewe** [comment]
@kyughost does this also work on windows?

**Comment by kyughost** [comment]
> @kyughost does this also work on windows? 

No sir. Sorry

**Comment by Raphaelmbewe** [comment]
please people how can I fix this problem on windows?

**Comment by KingKhan1234** [comment]
Thanks so much! just got a new Macbook Air 2020, and was giving me the same problem.

**Comment by kyughost** [comment]
> please people how can I fix this problem on windows?

I'm sorry. Mac user here

**Comment by bennybat50** [comment]
Thanks @kyughost  It worked for me too too

**Comment by SupremeQingHong** [comment]
> 嘿@ bhanuka96 试试这一行代码，对我有用
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`
nice！

**Comment by kamamuri** [comment]
Funcionó :) perfecto, muchas gracias

**Comment by lynnscode** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks, this worked for me

**Comment by GP1024** [comment]
how to do for win10

**Comment by GP1024** [comment]
how to do for win10?

**Comment by nezzard** [comment]
How to fix it? On win 10 i tried all solutions, buyt nothing work ( 
Only work on dev brunch, but i need stable

**Comment by saifamer2030** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanx bro this worked for me :)

**Comment by JekMx** [comment]
Nice !! Thanx !!! 

> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by zazaliu** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

worked for me thx!

**Comment by infinZero** [comment]
Can I use this

**Comment by infinZero** [comment]
I've android studio 4.1.2 so Can I used this instead of 4.1 ? 
Like as?


ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1.2/plugins ~/Library/Application\ Support/AndroidStudio4.1.2

**Comment by japneetbhatia** [comment]
Can someone please tell how to resolve this issue in win10 ?

**Comment by infinZero** [comment]
> Can someone please tell how to resolve this issue in win10 ?

for win10 you can consult with [this](https://github.com/flutter/flutter/issues/67986) for windows

**Comment by madura7** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks. This is working

**Comment by RYgithub1** [comment]
`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by domicoder** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thank you. Worked for me!

**Comment by aboutuoba** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Thanks. It work!

**Comment by osamasorani** [comment]
please, how can solve this problem in win10 ?

**Comment by garshom** [comment]
ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

this worked for me as well. thanks

**Comment by FlutterD** [comment]
I have just upgraded android studio to the latest version 4.1.2, and the problem were fixed

**Comment by iNeedHelpX** [comment]
> > 嘿@ bhanuka96 试试这一行代码，对我有用
> > `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`
> > nice！

I can't thank you enough!! It was perplexing me!!

**Comment by germanngc** [comment]
> Hey @bhanuka96 try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

(Y) Worked

**Comment by anjali-tiwari24** [comment]
I was facing the same problem but this works for me.( https://github.com/flutter/flutter/issues/11940#issuecomment-728005813 )

**Comment by stuarthua** [comment]
For Android Studio 4.2.1
```
Flutter 1.22.5 • channel unknown • unknown source
Framework • revision 7891006299 (6 个月前) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
```
just change version: 
```
ln -s ~/Library/Application\ Support/Google/AndroidStudio4.2/plugins ~/Library/Application\ Support/AndroidStudio4.2
```
Worked for me.

**Comment by exeptionerror** [comment]
3 Working Solution Added [Flutter plugin not installed error. When running flutter doctor](https://fluttercorner.com/flutter-plugin-not-installed-error-when-running-flutter-doctor/)
