### ISSUE TITLE
'flutter create' lets me create an all-numeric app name, but 'flutter run' fails with such a name

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6842]
Numeric app names are bad juju. pub fails because of the number in pubspec.yaml, flutter fails because of the number if flutter.yaml, adb fails because of the number in AndroidManifest.xml...

**Comment by eseidelGoogle** [comment]
We added some rules in this vein this for handling Info.plist restrictions ('-' gets converted to '_' iirc).  Presumably those rules aren't tight enough.  FYI @danrubel

**Comment by eseidelGoogle** [comment]
@pq and @devoncarew hit something similar with intellij recently.  We clearly need to tighten our naming rules in various places.

**Comment by pq** [comment]
Right.  The `disallowed` [regexp](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L193) is overly permissive.  We need to make sure that it only allows legal Dart identifiers (which can't lead with a number).

The bug on the IntelliJ side is being tracked here: https://github.com/flutter/flutter-intellij/issues/609.

Section "16.33 Identifier Reference" of the [Dart language spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) has the grammar we want to crib.

**Comment by Hixie** [comment]
This is fixed now.
