### ISSUE TITLE
handle new Observatory URL

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#6843]
In Dart 1.22 the URL to the service protocol and Observatory will change.

The message printed by the VM now look like `http://127.0.0.1:<port>/<token>/`.
For example:
```
Observatory listening on http://127.0.0.1:54804/PTwjm8Ii8qg=/
```
It is strongly recommended that tools scrape the whole base URL so as to be protected against future changes to the base URL.

Flutter tools needs to be updated to scrape the whole URL instead of just the port.
For example:
```
const kObservatoryListening = 'Observatory listening on ';
if (line.startsWith(kObservatoryListening)) {
  uri = Uri.parse(line.substring(kObservatoryListening.length));
}
```

To see this new Observatory behavior...
```
$ dart -DDART_SERVICE_USE_AUTH=true --observe ~/hello_world.dart
Observatory listening on http://127.0.0.1:54804/PTwjm8Ii8qg=/
```

**Comment by eseidelGoogle** [comment]
I'd be curious to learn more about the context of this change.  I feel like when I've developed for Dart in the past I've left a window in my browser open to localhost:8080 across restarts of my application and then just hit reload when I've brought up a new version.   Will that workflow still work after this DartVM change, or will I need to click a new URL every time I launch a new Dart CLI or Flutter app for debugging?

**Comment by danrubel** [comment]
@johnmccutchan Can you comment on this?

**Comment by johnmccutchan** [comment]
@eseidelGoogle This completely breaks that workflow because each instance of the VM has a different random auth token. You are not alone in relying on this work flow, however, a security review from a few months ago came back with this suggestion and my usability argument did not win out.

**Comment by johnmccutchan** [comment]
@danrubel are you planning on implementing support for this? Please make sure that flutter_tools passes around the complete Uri object instead of the port + auth token.

**Comment by danrubel** [comment]
Yes and will do.

**Comment by danrubel** [comment]
My understanding is that the Observatory URL will not change for Flutter, so no change needed in Flutter tools. Please reopen if that is not the case.

**Comment by danrubel** [comment]
Apparently it will change.... reopening issue.

**Comment by eseidelGoogle** [comment]
Can your provide context?

**Comment by danrubel** [comment]
@johnmccutchan indicated that we are moving ahead with this.

**Comment by johnmccutchan** [comment]
There is two things:

1) We should fix the code in flutter_tools to always return a Uri object instead of a port. This is a general cleanup that we should do regardless of the authentication token.

2) Siva and the security folks have reached a compromise where the URL would be valid for 1-week at a time and we plan on discussing this with you after the holidays.

**Comment by Hixie** [comment]
Is there a description of the problem we're trying to solve here somewhere?

I've had debugging sessions that have lasted more than a week at home, where I connect observatory to a long-running Dart process running on a server, and do a bit more work every few days.

**Comment by johnmccutchan** [comment]
@Hixie Context is spread out all over the place. The token will not expire for an existing session.
