### ISSUE TITLE
english_words package is not available

### ISSUE THREAD

**Issue by kurabi1966** [flutter/flutter#68431]
I tried to use the english_words package, but unfortunately it is not available, so I replaced it with random_words: ^1.0.2

**Comment by SeasonLeee** [comment]
@kurabi1966 hey, what do you mean that package is not available?

I can still search it from pub.dev, right?

![image](https://user-images.githubusercontent.com/13610283/96365034-76148e00-1170-11eb-93ee-8510a352063a.png)

**Comment by sidrao2006** [comment]
Hey @SeasonLeee , could you please post the outputs of `flutter doctor-v` , `flutter pub --version -v`, `flutter pub get -v` and your pubspec.yaml (if possible)

**Comment by iapicca** [comment]
@kurabi1966 
[english_words](https://pub.dev/packages/english_words) is a 3rd party package I recommend to close this issue
and open a new issue in the dedicated [github](https://github.com/filiph/english_words/issues)

**Comment by kurabi1966** [comment]
You can close the issue.

english_words as mentioned by iapicca is a 3ed party package.

[1]
in may main.dart I added 
import 'package:english_words/english_words.dart';

[2]
in my pubspec.yaml, I added to the dependency section:
english_words: ^3.1.5

[3]
I clicked Pug get in Android studio.

The error happened in my main.dart.
When I hover over the line that contains import 'package:english_words/english_words.dart'; it is telling me
Target of URI doesn't exist: 'package:english_words/english_words.dart'. 

What I did to solve the problem is to replace the english_words package with random_words package.

Every thing is working fine now.

I am sorry, I am very new to flutter and dart.

Thanks

**Comment by kurabi1966** [comment]
> @kurabi1966 hey, what do you mean that package is not available?
> 
> I can still search it from pub.dev, right?
> 
> ![image](https://user-images.githubusercontent.com/13610283/96365034-76148e00-1170-11eb-93ee-8510a352063a.png)

try https://pub.dev/packages?q=english_words please.
Can you find it in the list?

**Comment by Abhishek01039** [comment]
@kurabi1966 
restart your IDE or code editor.
and try to run with cmd as well
Thanks

**Comment by darshankawar** [comment]
@kurabi1966  Here's the [link](https://pub.dev/packages/english_words) to the package you are looking for.
Closing this as not related to Flutter.
