### ISSUE TITLE
[doc]the command to create sample fail

### ISSUE THREAD

**Issue by SeasonLeee** [flutter/flutter#68432]
I was trying to run the example project locally with the command display under the interactive dart code pad

![image](https://user-images.githubusercontent.com/13610283/96364851-56309a80-116f-11eb-800a-419ae6320355.png)

I failed with this error message showing in the terminal:

![image](https://user-images.githubusercontent.com/13610283/96364914-b3c4e700-116f-11eb-8603-677c83d455c3.png)

Then I tried to open that 404 url on browser, and I got this:

![image](https://user-images.githubusercontent.com/13610283/96364936-cf2ff200-116f-11eb-9fc1-3bbcd735c053.png)

Not sure if other example and command will fail as well, but my bet is they all will fail assuming they all use resource from this url...

**Comment by amanv8060** [comment]
It is FutureBuilder
You can close this issue thanks

**Comment by SeasonLeee** [comment]
Oh!!! I see that now! Thank you!! hahaha

**Comment by amanv8060** [comment]
@PixelToast  this can be closed
