### ISSUE TITLE
Failed assertion: line 3580 pos 12: '!_debugLocked': is not true

### ISSUE THREAD

**Issue by Numanshakir** [flutter/flutter#68438]
i got this error while using drawer

**Comment by ufolux** [comment]
Hello @Numanshakir
Could you pls post the outputs of `flutter run -v` and `flutter doctor -v` and reproduce steps?
Thank you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
