### ISSUE TITLE
Setting callback of MethodChannel, that has pending message, to null will freeze whole app

### ISSUE THREAD

**Issue by matejdro** [flutter/flutter#68430]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 

[main.dart.txt](https://github.com/flutter/flutter/files/5397190/main.dart.txt)
[MainActivity.kt.txt](https://github.com/flutter/flutter/files/5397191/MainActivity.kt.txt)

3. Run the demo app

**Expected results:** 

Demo app should function as expected (e.g. pressing on + button should increase the counter)

**Actual results:** 

App freezes

**Comment by aissat** [comment]
@matejdro same bug  for demo app
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-18 at 10 35 20](https://user-images.githubusercontent.com/4768203/96363708-ba326f00-112d-11eb-9282-c62f0219bfe2.png)

**Comment by darshankawar** [comment]
@matejdro 
Tried your code sample on latest Master using Android 8.1.0 device and was able to run and increase counter properly without any issues.

[68430.mp4.zip](https://github.com/flutter/flutter/files/5401203/68430.mp4.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-19.0.pre.95, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.23.0-19.0.pre.95 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a837557634 (24 hours ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details>

Please provide your `flutter doctor -v` and  `flutter run --verbose` for logs.

**Comment by matejdro** [comment]
Can you check with debugger what happens when you go into `channelB.setMethodCallHandler(null)` line? 

For me, code eventually reaches `DefaultBinaryMessenger.setMessageHandler`. Where it gets stuck on the [`ui.channelBuffers.drain`](https://github.com/flutter/flutter/blob/804c3ff31f6e517799bdd262c6b6cbe6eafac793/packages/flutter/lib/src/services/binding.dart#L316) infinite loop - Drain method appears to be calling provided lambda until buffer is empty. But since there is no listener attached to that binary handler, buffer will never be empty.

My doctor output:

```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.2 at /opt/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/matej/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /usr/bin/java
    • Java version openjdk version "11.0.8" 2020-07-14
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • GM1913 (mobile) • a6734f0a • android-arm64 • Android 10 (API 29)
```

Even on verbose logs, there is nothing really there. I only get bunch of compiling logs, but app itself does not provide any (since it freezes on startup).

**Comment by darshankawar** [comment]
@matejdro 
Debugged `channelB.setMethodCallHandler(null)` and noticed it doesn't stuck anywhere and moves past it smoothly.
What platform are you seeing freeze on ?

**Comment by matejdro** [comment]
Android. Can you check how does `ui.channelBuffers.drain` exit the loop considering there are pending messages in the buffer?

**Comment by darshankawar** [comment]
It seems to come out of `DefaultBinaryMessenger.setMessageHandler` without getting stuck anywhere. Can't put video here as the size is too big to upload.

<img width="1260" alt="Screenshot 2020-10-20 at 12 31 29 PM" src="https://user-images.githubusercontent.com/67046386/96551646-411f4d00-12d0-11eb-8ef6-5717a805cb56.png">

<img width="1261" alt="Screenshot 2020-10-20 at 12 31 04 PM" src="https://user-images.githubusercontent.com/67046386/96551638-3cf32f80-12d0-11eb-8f6b-ef5d22d65022.png">

**Comment by matejdro** [comment]
Can you print contents of ui.channelBuffers when .drain is called?

**Comment by darshankawar** [comment]
@matejdro 
It does get stuck if I try to do that, but in the UI, I was able to increase the counter with no issues as you saw in the video.

**Comment by matejdro** [comment]
That is interesting. Does it somehow run on different thread for you?

**Comment by darshankawar** [comment]
@matejdro Don't think so, I just used your code sample to run the app which didn't freeze for me. 
Can you try [this](https://flutter.dev/docs/development/platform-integration/platform-channels) official example and check if you see similar behavior ?

**Comment by matejdro** [comment]
What exactly do you want me to check on the sample? Do you want me to add freezing code to the sample?

**Comment by darshankawar** [comment]
@matejdro 
Yes, just to check if there's anything different that's happening at your end using Flutter's official code sample.

**Comment by matejdro** [comment]
I could not get that sample to compile (just downloading sample from git and attempting to run it with zero changes produced a bunch of dependency errors).

Instead I'm uploading complete reproducing hello world project here instead of just changed files: [bug.zip](https://github.com/flutter/flutter/files/5417297/bug.zip). hopefully it helps.

**Comment by darshankawar** [comment]
@matejdro 
Tried your latest code and saw app not responding to button tap. What changed now ? How it worked for me earlier and not now ?

**Comment by matejdro** [comment]
I'm not sure, I performed the exact steps from the first post (ran `flutter create bug` and replaced the files).

**Comment by darshankawar** [comment]
@matejdro 
Probably it's working on Master and not on stable. Can you confirm that ?

**Comment by matejdro** [comment]
Is there any guide on compiling flutter form master? I'm pretty new to this whole flutter thing.

**Comment by darshankawar** [comment]
@matejdro 
No, just do `flutter channel master`, then `flutter upgrade` and run the project.

**Comment by matejdro** [comment]
Thanks for your help, tested it with master and the issue is gone. I've checked the code just to be sure and yeah, it was fixed: https://github.com/flutter/flutter/commit/cb232ddad5ba5914064639cd3927635a3598742c
