### ISSUE TITLE
webview_flutter not support v2.x.x

### ISSUE THREAD

**Issue by diegothucao** [flutter/flutter#68445]
when i using webview_flutter for my app 
but when app gets installation, it shows error

[it-app] flutter pub get
Running "flutter pub get" in it-app...                          
The current Flutter SDK version is 1.20.1.

Because app depends on webview_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.
pub get failed (1; Because app depends on webview_flutter >=1.0.0 which requires Flutter SDK version >=1.22.0 <2.0.0, version solving failed.)
exit code 1

**Comment by diegothucao** [comment]
sorry

**Comment by Mandoh** [comment]
how did you fix this?
