### ISSUE TITLE
 Failed assertion: line 4016 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by hossam1244** [flutter/flutter#68444]
When I click the back button on the android device I got this navigation error. I'm still searching for the cause and the error message doesn't give me the reason for the cause!

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
_WidgetsAppState#21af8](dirty, dependencies: [HeroControllerScope], state:
NavigatorState#b7fb7(tickers: tracking 1 ticker)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4016 pos 12: '!_debugLocked':
is not true.

When the exception was thrown, this was the stack:
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:4016:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#16     _invoke (dart:ui/hooks.dart:253:10)
#17     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

**Comment by hamdikahloun** [comment]
Hi @hossam1244 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Thank you

**Comment by hossam1244** [comment]
Hi @hamdikahloun 

   I have resolved the issue. it was basically a wrong way to navigate throw the widgets.
   I was closing the app in log in using   `Navigator.popUntil(context, ModalRoute.withName('/'));``
   so instead in the splash screen, I have replaced it the push with push replacement navigation using pushReplacementNamed. which solved the issue.

Thanks @hamdikahloun
