### ISSUE TITLE
[app2app][XCode12] 'GeneratedPluginRegistrant' has different definitions in different modules; first difference is defined here found method 'registerWithRegistry:'

### ISSUE THREAD

**Issue by lolapriego** [flutter/flutter#68456]
Hi, I am running into build issues after upgrading to XCode 12. I don't recall seeing this issue in almost 2y of using Flutter!

## Steps to Reproduce

1. Upgrade to XCode 12.0.1 while using app to app configuration
2. Run your build

**Expected results:**  The build runs

**Actual results:** The build fails with the following errors

`'GeneratedPluginRegistrant' has different definitions in different modules; first difference is defined here found method 'registerWithRegistry:' with 1st parameter of type 'NSObject<FlutterPluginRegistry> *__strong'`

on the GeneratedPluginRegistrant.h but it flags a file within Development Pods. Note that this seems to be an issue known with [XCode12](https://developer.apple.com/forums/thread/658012?page=2). Developers find themselves renaming classes for 3rd party libraries but this one is difficult to solve

![Screen Shot 2020-10-18 at 10 06 34 PM](https://user-images.githubusercontent.com/1484573/96393794-3492db80-118e-11eb-9057-a5dd526e767b.png)

![Screen Shot 2020-10-18 at 10 04 21 PM](https://user-images.githubusercontent.com/1484573/96393776-29d84680-118e-11eb-9439-2b8707a8d2d5.png)

<details><summary>flutter doctor -v</summary>

```
Downloading libimobiledevice...                                     0.2s
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/lolapriego/development/flutter
    • Framework revision 198df796aa (3 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/lolapriego/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = /Users/lolapriego/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lolapriego/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830


[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile)   • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)           • 0B132F4B-D601-47D3-AA44-9B3D71B481E0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • iPod touch (7th generation) (mobile) • DD755704-6AD7-47C2-B134-67E578819096 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                     • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 86.0.4240.80

! Doctor found issues in 1 category.

```
</details>

**Comment by lolapriego** [comment]
Note that I manage to build the app if I rename the primary GeneratedPluginRegistrant interface within my workspace to something different but this is generated code so it feels like a tmp solution.

**Comment by pedromassangocode** [comment]
Hi @lolapriego 
Can you please provide and a minimal complete reproducible code sample?
Thank you

**Comment by lolapriego** [comment]
Hi @pedromassangocode not sure how to provide a reproducible code sample as this just happens with the [app to app](https://flutter.dev/docs/development/add-to-app/ios/project-setup) setup when upgrading to XCode 12.

Are you referring to a code snippet or a pointer to a codebase? If you are referring to the former, no snippet will come handy as the code is failing on both gen (GeneratedPluginRegistry) classes for Flutter.

**Comment by pedromassangocode** [comment]
Hi @lolapriego 
You can share a sample project where the issue happens.

I tried this https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk and had no issues.

Which add-to-app steps did you used?

**Comment by lolapriego** [comment]
Hey @pedromassangocode I'm working on a private repo I'm going to try to reproduce it with a sample project. Which version of XCode are you on?

**Comment by pedromassangocode** [comment]
Hi @lolapriego 
I'm on XCode `12.0.1 (12A7300)`.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
