### ISSUE TITLE
[web] CanvasKit ignoring letterSpacing property of TextStyle

### ISSUE THREAD

**Issue by UliPrantz** [flutter/flutter#68454]
The title says it all. I don't know about the wordSpacing property of TextStyle probably it's ignored too.

**Comment by darshankawar** [comment]
@UliPrantz 
Tried a sample `Text` and `TextField` widget with `letterSpacing` property set to 5 and it seem to work properly. I am on latest Master.

<img width="491" alt="Screenshot 2020-10-19 at 4 41 34 PM" src="https://user-images.githubusercontent.com/67046386/96443459-41fda380-122a-11eb-8dba-903e6d99ddfa.png">
<img width="374" alt="Screenshot 2020-10-19 at 4 43 09 PM" src="https://user-images.githubusercontent.com/67046386/96443465-445ffd80-122a-11eb-9fb8-029a06f8a082.png">

```
Center(
          child: Text('This is sample text', style: TextStyle(
     letterSpacing: 5
    ))
      ),
```

Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by UliPrantz** [comment]
@darshankawar 
Oh ok nice I'm on beta will test it today. But you did use CanvasKit, didn't you? Not the normal `flutter build web`! You have to enable it by adding the following and it only takes effect on release builds: `--dart-define=FLUTTER_WEB_USE_SKIA=true`

**Comment by darshankawar** [comment]
@UliPrantz 
Tried the code sample using below command and saw the `letterSpacing` rendered properly.

`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

<img width="971" alt="Screenshot 2020-10-19 at 7 18 54 PM" src="https://user-images.githubusercontent.com/67046386/96459892-3fa64400-1240-11eb-99b7-1bbc1dba1a62.png">


Please provide details and issue from your side.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
