### ISSUE TITLE
Black Patches On Text Fields

### ISSUE THREAD

**Issue by m-zaink** [flutter/flutter#68463]
I'm currently using the [flutter_neumorphic](https://pub.dev/packages/flutter_neumorphic) package.
And all the text-fields there have black patches on them. (Left side in the below screenshot).

![Screenshot_20201015_182457](https://user-images.githubusercontent.com/32197186/96406247-a6a20980-11fc-11eb-904c-d2d20efc1bbc.jpg)

It's device-specific issues (such as in Samsung and Vivo devices). 
Please help.

**Comment by sidrao2006** [comment]
Hey @,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is a bug with a 3rd party package, please close this issue and open it [here](https://github.com/Idean/Flutter-Neumorphic/issues) instead.

Thanks

**Comment by m-zaink** [comment]
Hey sure. Thank you @sidrao2006. I will post it there.
