### ISSUE TITLE
How to archive IOS add 2 app .ipa?  And Distribute to Appstore?

### ISSUE THREAD

**Issue by shi1234ww** [flutter/flutter#68469]
Usual ,   We can archive iOS project with Xcode ===>> Product === > Archive,  Then few seconds later , when Xcode tip Archive success,  An Archive will show in   Xcode === > Window === > Organizer  .  then  we can  validate this App , or Distribute this app ,  But , when Add flutter module to IOS native project   ,,  when archive finished , the .xcarchive  Can't see in the  Xcode === > Window === > Organizer .   So ,  How to archive an flutter add 2  ios ,app  , and distribute it's to APPSTORE???

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.41, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-CN)
    • Flutter version 1.23.0-19.0.pre.41 at
      /Users/shiweiwei/Desktop/Study/flutter
    • Framework revision ed2a4809da (4 days ago), 2020-10-14 20:02:04 -0400
    • Engine revision ce75dda492
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at
      /Users/shiweiwei/Desktop/Study/Android/Android_SDK/android-sdk-macosx
    • Platform android-29, build-tools 30.0.2
    • ANDROID_HOME =
      /Users/shiweiwei/Desktop/Study/Android/Android_SDK/android-sdk-macosx
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • shiweiwei’s iPhone (mobile) • c578619393aa85cd066dfbd1864f5886c51a35d8 •
      ios • iOS 13.3.1
    • iPhone 8 (mobile)           • 6175D695-E8F0-4608-80E8-4D5062F5748F     •
      ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: shiweiwei’s iPhone is busy: Copying cache files from device. Xcode
      will continue when shiweiwei’s iPhone is finished. (code -10)

• No issues found!
``

</details>

**Comment by shi1234ww** [comment]
I have see this document :    [https://flutter.dev/docs/deployment/ios](url)   , And it only introduce the situation  about how Pure Flutter app build and release to APPSTORE,    and no information about how to build and release  and add flutter module 2  existing iOS project ,

**Comment by jmagman** [comment]
You should be able to archive your host app in Xcode, there's nothing Flutter-specific about it once the frameworks are embedded.
> the .xcarchive Can't see in the Xcode === > Window === > Organizer

This sounds like an Xcode bug, Flutter isn't involved at this point.  I think it should be in `~/Library/Developer/Xcode/Archives`?

**Comment by shi1234ww** [comment]
Hi!  I can find the .xcarchive in directory ~/Library/Developer/Xcode/Archives ,  but it's size is Zero bytes ??   Maybe is not available ,  So  Xcode === > Window === > Organizer don't show this file ,  Could you please provide a more detaild process about how to archive add flutter module to host app In Xcode ?

**Comment by jmagman** [comment]
@shi1234ww Can you attach your archive log?
![Uploading Screen Shot 2020-10-20 at 2.52.18 PM.png…]()

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
