### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.firestore.firebasemessaging 

### ISSUE THREAD

**Issue by sujindra-kodiary** [flutter/flutter#68461]
My app is getting crash after I upgrade firebase packages. The firebase packages I have used in the pubspec.yaml file is as follows:
```
firebase_core: 0.5.0+1
  cloud_firestore: 0.14.0+2
  cloud_functions: 0.6.0
  firebase_auth: 0.18.1+2
  firebase_analytics: 6.0.0
  firebase_database: ^4.0.0
  firebase_messaging: ^6.0.16
  firebase_remote_config: ^0.4.0
  firebase_storage: ^4.0.0
  firebase_dynamic_links: ^0.6.0
```

The crash log is as follows:
`io.flutter.plugin.common.StandardMessageCodec.writeValue (Unknown Source:400)
io.flutter.plugin.common.StandardMessageCodec.writeValue (Unknown Source:377)
io.flutter.plugin.common.StandardMessageCodec.writeValue (Unknown Source:377)
io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall (Unknown Source:16)
io.flutter.plugin.common.MethodChannel.invokeMethod (Unknown Source:11)
io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.executeDartCallbackInBackgroundIsolate (Unknown Source:82)
io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.access$000
io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService$1.run (Unknown Source:6)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7860)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)`

**Comment by sidrao2006** [comment]
Hey @sujindra-kodiary , this issue tracker is used to track problems with flutter

Since this is an error with firebase package, please close this issue [here](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by sujindra-kodiary** [comment]
Okay @sidrao2006. Thanks.
