### ISSUE TITLE
Android: focusing widgets to be able to navigate using a hardware keyboard is impossible

### ISSUE THREAD

**Issue by lorenzOliveto** [flutter/flutter#68471]
## Steps to Reproduce

Scenario:
Android device navigating with an hardware keyboard, a `Scaffold` is pushed with `Navigator.of(context).pushReplacement` after the user confirms with the `Enter` key in a `TextField` (in  `onSubmitted`).
The new `Scaffold` doesn't have the back button in the `AppBar` but a couples of buttons in the body.

**Expected results:** 
The keyboard focuses on the first button after the push.

**Actual results:** 
The focus of the keyboard is broken and the app can't be navigated with the keyboard.

<details>
  <summary>Example</summary>

``` dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class KeyboardTextFieldPushReplacement extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: TextField(
          onSubmitted: (text) => _pushNewScaffold(context),
        ),
      ),
    );
  }

  _pushNewScaffold(BuildContext context) {
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(
        builder: (context) => PushedScaffold(),
      ),
    );
  }
}

class PushedScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
      ),
      body: Column(
        children: [
          FlatButton(
            child: Text('Button1'),
            onPressed: () {},
          ),
          FlatButton(
            child: Text('Button2'),
            onPressed: () {},
          ),
        ],
      ),
    );
  }
}
```
</details>

<details>
  <summary>$ flutter doctor -v output</summary>

```
[✓] Flutter (Channel master, 1.23.0-19.0.pre.95, on Mac OS X 10.15.7 19H2
    darwin-x64, locale it-IT)
    • Flutter version 1.23.0-19.0.pre.95 at
      /Users/lorenzooliveto/Flutter/flutter
    • Framework revision a837557634 (23 hours ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lorenzooliveto/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/lorenzooliveto/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone di Lorenzo (mobile) • 63e1defd8bca92bd059530106598ec853b3609ac •
      ios • iOS 14.0.1
    ! Error: iPhone di Lorenzo is busy: Copying cache files from device. Xcode
      will continue when iPhone di Lorenzo is finished. (code -10)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Hi @lorenzOliveto 
The keyboard is removed because the widget that called it is removed from the tree.

What do you mean by "The focus of the keyboard is broken and the app can't be navigated with the keyboard"? Can you please elaborate?

As far as I know the is no way to navigate to another page using a keyboard. Are you suggesting something?

**Comment by lorenzOliveto** [comment]
Hi @pedromassango, 
The scenario is that there's an hardware keyboard (not the software keyboard that's visible on screen) attached to the device (via bluetooth or USB) and it's used to "navigate" the app, to move around the app, for accessibility reasons. https://developer.android.com/training/keyboard-input/navigation

The focus is visualized as this image (the last row is focused), but with the steps described it's removed and I haven't found a way to make it re-appear.

![Screenshot_1603102809](https://user-images.githubusercontent.com/3470464/96433321-74e17080-1205-11eb-9486-4ce7bb75273a.png)

**Comment by pedromassangocode** [comment]
Got it now. I don't have a Bluetooth/USB keyboard but I think this is currently possible to do that.

Have you tried the Focus widget? 
https://api.flutter.dev/flutter/widgets/Focus-class.html

**Comment by lorenzOliveto** [comment]
Yes, I've tried setting the focus to the button, with `FocusScope.of(context).requestFocus(BUTTON_FOCUS_NODE)`.
The focus is moved (I see the gray background) but I can't navigate with the keyboard anymore, pressing the tab key or the arrows doesn't move the focus.

**Comment by pedromassangocode** [comment]
Thanks.
So looks like the problem with the actual workaround is that one should use the Focus widget everywhere to get this working which is not a good solution.

**Comment by gmoraja** [comment]
@gspencergoog

**Comment by gspencergoog** [comment]
Have you tried adding the `autofocus: true` attribute to the button you think should receive focus?

For example, this seems to work in this [dartpad example](https://dartpad.dartlang.org//447a184bc695451c567bcc07f997d190):

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light),
      home: Scaffold(
        appBar: AppBar(title: Text('test')),
        body: Center(child: KeyboardTextFieldPushReplacement()),
      ),
    );
  }
}

class KeyboardTextFieldPushReplacement extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: TextField(
          onSubmitted: (text) => _pushNewScaffold(context),
        ),
      ),
    );
  }

  _pushNewScaffold(BuildContext context) {
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(
        builder: (context) => PushedScaffold(),
      ),
    );
  }
}

class PushedScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
      ),
      body: Column(
        children: [
          FlatButton(
            child: Text('Button1'),
            autofocus: true, // Setting this to true will cause it to automatically be focused.
            onPressed: () {},
          ),
          FlatButton(
            child: Text('Button2'),
            onPressed: () {},
          ),
        ],
      ),
    );
  }
}
```

**Comment by gspencergoog** [comment]
Oh, running it on Android, I see what you mean. I'll check it out.

**Comment by gspencergoog** [comment]
A PR (flutter/engine#22304) that I've been meaning to re-land anyhow seems to fix this issue.

I suspect that there may still be an underlying problem that we keep the text input connection open when the new route is pushed, causing the keydown events that would have been sent to the framework to be sent to the text input plugin instead (and since there is no text field anymore, the key is lost). The framework is calling the close method on the text input connection, but for some reason the engine's text input plugin is still accepting text.

The PR solves this by sending the keys to the framework to be processed before sending it to the text input plugin, but we still shouldn't be keeping the text input plugin connected in this situation, I don't think.

**Comment by gspencergoog** [comment]
Reopening because this change was reverted.
