### ISSUE TITLE
[webview_flutter] Monitor all network requests in the page

### ISSUE THREAD

**Issue by januwA** [flutter/flutter#68476]
```
 flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale zh-CN)
    • Flutter version 1.22.2 at D:\my-tools\flutter
    • Framework revision 84f3d28555 (3 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\my-tools\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\my-tools\Android\sdk
    • Java binary at: D:\my-tools\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at D:\my-tools\Android\AndroidStudio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

I want to be notified whenever a web request occurs on the page. 

It's like opening the F12 console in the Chrome browser.

![image](https://user-images.githubusercontent.com/22570563/96439653-61e89380-1239-11eb-8401-e368c01877e8.png)

thanks. ❤

**Comment by sidrao2006** [comment]
Hey @,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please see https://flutter.dev/community for resources and asking queries doubts and assistance on personal code. You may get some help if you post it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=flutter) and if you need help with your code, please check https://www.reddit.com/r/flutterhelp/.

If you are requesting this feature for devtools, it has already been implemented [here](https://flutter.dev/docs/development/tools/devtools/network).

Thanks

**Comment by pedromassangocode** [comment]
Hi @januwA 
Please refer to the comment above for more information.

I'm closing this as invalid Flutter issue.
Thank you
