### ISSUE TITLE
IOS crushed after update flutter sdk(dartworker: signal SIGABRT)

### ISSUE THREAD

**Issue by xueenze** [flutter/flutter#68472]
After update the lastest stable channel,ios crushed
`libsystem_kernel.dylib`__pthread_kill:
    0x1ccf2a954 <+0>:  mov    x16, #0x148
    0x1ccf2a958 <+4>:  svc    #0x80
->  0x1ccf2a95c <+8>:  b.lo   0x1ccf2a978               ; <+36>     **DartWorker (16): signal SIGABRT**
    0x1ccf2a960 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1ccf2a964 <+16>: mov    x29, sp
    0x1ccf2a968 <+20>: bl     0x1ccf081dc               ; cerror_nocancel
    0x1ccf2a96c <+24>: mov    sp, x29
    0x1ccf2a970 <+28>: ldp    x29, x30, [sp], #0x10
    0x1ccf2a974 <+32>: ret    
    0x1ccf2a978 <+36>: ret    `

**Comment by sidrao2006** [comment]
Hello @xueenze ,
Could you please post the outputs of `flutter run -v` , `flutter doctor -v` and a minimal reproducible code sample
Thank you!

**Comment by darshankawar** [comment]
@xueenze 
Is this crashing in debug mode or in release mode  ? Please provide `flutter doctor -v` and most importantly a complete reproducible minimal code sample that shows the crash. What command you tried to run which led to the crash ?
Also provide `flutter run --verbose` to see the complete log.

**Comment by xueenze** [comment]
> Hello @xueenze ,
> Could you please post the outputs of `flutter run -v` , `flutter doctor -v` and a minimal reproducible code sample
> Thank you!

`[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale
    zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/enzexue/Develop/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/enzexue/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/enzexue/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • “enzexue”的 iPhone (mobile) • 23a45b1fdffaf43554f7682c3afe84913b854644 •
      ios • iOS 14.0.1`

**Comment by xueenze** [comment]
> @xueenze
> Is this crashing in debug mode or in release mode ? Please provide `flutter doctor -v` and most importantly a complete reproducible minimal code sample that shows the crash. What command you tried to run which led to the crash ?
> Also provide `flutter run --verbose` to see the complete log.

debug mode,detail:
`[ +128 ms] Could not run build/ios/iphoneos/国泰基金.app on
                    23a45b1fdffaf43554f7682c3afe84913b854644.
[   +2 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 50.2s)
[        ] Error launching application on “enzexue”的 iPhone.
[   +4 ms] "flutter run" took 110,348ms.
[   +6 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues
(package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +256 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +7 ms] exiting with code 1
`

**Comment by darshankawar** [comment]
@xueenze 
Will need a minimal code sample that shows the crash.

**Comment by xueenze** [comment]
> @xueenze
> Will need a minimal code sample that shows the crash.

your email?

**Comment by darshankawar** [comment]
@xueenze 
Please provide a complete minimal reproducible code sample in text format here that we can copy paste and run directly in IDE that would show the crash you are getting.
Thanks.

**Comment by wH1t3-l0tUs** [comment]
I got the same problem after upgrade to the newest Flutter version

this is my `flutter doctor` result:
```
➜ flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)
    ! Error: Dat Nguyen is busy: Waiting for Device. Xcode will continue when Dat Nguyen is finished. (code -10)
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
