### ISSUE TITLE
[in-app-purchase] [iOS] SKErrorDomain - Cannot connect to iTunes Store

### ISSUE THREAD

**Issue by vinothvino42** [flutter/flutter#68483]
inapp_purchase version 0.3.4+15

**Expected behavior**

I'm expecting to buy IAP item after providing password in the confirm purchase dialog.

**Actual behavior**

It ask me two times for entering password (2 confirm purchase alert dialog) when requesting for purchase, after entering the password (2 times) it shows an exception `SKErrorDomain - {NSLocalizedDescription: Cannot connect to iTunes Store}`

**Steps to reproduce the behavior**

Just buying an IAP flow only. Last week it worked fine, but today it's not working as expected. I've tried many solutions. I tried neilc solution in this thread https://developer.apple.com/forums/thread/90594. Still I'm facing this issue and also I'm using only the Sandbox Testing account (which is not an apple account, just created a new gmail account and created sandbox tester account in the apple appstoreconnect). Also I checked apple's system status https://www.apple.com/in/support/systemstatus/ and everything is in green color.

**Flutter doctor summary**

```
✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-IN)
    • Flutter version 1.22.2 at /Users/vinothvino/Developer/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vinothvino/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/vinothvino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[✓] Connected device (1 available)            
    • Vinoth’s iPhone (mobile) • ios • iOS 12.4.7

• No issues found!
```

Anyone please fix this issue. Thank you.

**Comment by TahaTesser** [comment]
Hi @vinothvino42 
Does the issue appear after changing in_app_purchase or upgrading from last week as you mentioned? 
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by vinothvino42** [comment]
I don't know exactly but today I tried it, it's not working. Simply it's asking me to enter password for two times with Confirm Purchase dialog. I googled for this, most of the people are saying it's working good in iOS 14 but not working in iOS 11, 12 and 13.

**Comment by amlzq** [comment]
> 嗨@TahaTesser
> 我不知道确切，但今天我尝试了一下，它不起作用。只是要求我在“确认购买”对话框中输入两次密码。我用谷歌搜索，大多数人说它在iOS 14上运行良好，但在iOS 11、12和13上运行不正常。
> 
> **样例代码**
> 
> ```
> import 'dart:async';
> 
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> import 'package:in_app_purchase/in_app_purchase.dart';
> 
> import '../../../core/models/course/course.dart';
> import '../../../core/utils/alert_dialog_helper.dart' as alert_helper;
> import '../../widgets/card_button.dart';
> 
> class CourseDetailPage extends StatefulWidget {
>   final Course course;
> 
>   const CourseDetailPage({Key key, this.course}) : super(key: key);
> 
>   @override
>   _CourseDetailPageState createState() => _CourseDetailPageState();
> }
> 
> class _CourseDetailPageState extends State<CourseDetailPage> {
>   InAppPurchaseConnection iap = InAppPurchaseConnection.instance;
>   bool available = true;
>   List<ProductDetails> products = [];
>   StreamSubscription subscription;
> 
>   @override
>   void initState() {
>     _initialize();
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     subscription.cancel();
>     super.dispose();
>   }
> 
>   void _initialize() async {
>     print('Initialized IAP');
>     iap = InAppPurchaseConnection.instance;
>     available = await iap.isAvailable();
>     if (available) {
>       print('Get products called');
>       await _getProducts();
>     }
> 
>     subscription = iap.purchaseUpdatedStream.listen((products) {
>       final myFirstCourse = products[0];
>       print('Product ID ' + myFirstCourse.productID);
>       // print('Server Verification Data' + myFirstCourse.verificationData?.serverVerificationData ?? '');
>       _listenToPurchaseUpdates(products);
>     }, onDone: () {
>       subscription.cancel();
>     }, onError: (error) {
>       alert_helper.showErrorAlert(error.toString() ?? '');
>     });
>   }
> 
>   Future<void> _getProducts() async {
>     print('Get products method called');
>     Set<String> ids = Set.from([
>       widget.course.appleProductId,
>     ]);
>     ProductDetailsResponse response = await iap.queryProductDetails(ids);
> 
>     setState(() {
>       products = response.productDetails;
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Container(
>       child: CardButton(
>         title: 'BUY NOW',
>         onPressed: () async {
>           payWithApplePay();
>         },
>       ),
>     );
>   }
> 
>   void payWithApplePay() async {
>     print('IAP Product Length : ${products?.length ?? 0}');
>     final iapProduct = products.firstWhere((element) => element.id == widget.course.appleProductId);
>     print('IAP PRODUCT **** : ${iapProduct.id}');
> 
>     final PurchaseParam course = PurchaseParam(productDetails: iapProduct, sandboxTesting: true);
>     iap.buyNonConsumable(purchaseParam: course).catchError((error) {
>       if (error is PlatformException && error.code == "storekit_duplicate_product_object") {
>         alert_helper.showErrorAlert('storekit_duplicate_product_object');
>       }
>     });
>   }
> 
>   void _listenToPurchaseUpdates(List<PurchaseDetails> purchaseDetailsList) {
>     purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
>       if (purchaseDetails.status == PurchaseStatus.pending) {
>         print('Pending State');
>       } else {
>         if (purchaseDetails.status == PurchaseStatus.error) {
>           print('Error State');
>           if (purchaseDetails.error.details is String) {
>             alert_helper.showErrorAlert(purchaseDetails.error.details);
>           } else {
>             alert_helper.showErrorAlert(purchaseDetails.error.message);
>           }
>           print(purchaseDetails.error.details);
>         } else if (purchaseDetails.status == PurchaseStatus.purchased) {
>           print('Purchased State');
>           bool valid = await _verifyPurchase(purchaseDetails);
>           if (valid) {
>             deliverProduct(purchaseDetails);
>           } else {
>             _handleInvalidPurchase(purchaseDetails);
>             return;
>           }
>           await InAppPurchaseConnection.instance.completePurchase(purchaseDetails);
>         }
>         if (purchaseDetails.pendingCompletePurchase) {
>           print('Pending Complete State');
>           await InAppPurchaseConnection.instance.completePurchase(purchaseDetails);
>         }
>       }
>     });
>   }
> 
>   Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) {
>     // IMPORTANT!! Always verify a purchase before delivering the product
>     // Verify by sending the transaction details to our abservetech server
>     print('Verify Purchase Method called');
>     return Future<bool>.value(true);
>   }
> 
>   void _handleInvalidPurchase(PurchaseDetails purchaseDetails) {
>     // verifying purchase is failed
>   }
> 
>   void deliverProduct(PurchaseDetails purchaseDetails) async {
>     print('Deliver Product Method called : ${purchaseDetails.verificationData.serverVerificationData}');
>     // IMPORTANT!! Always verify a purchase purchase details before delivering the product.
>   }
> }
> ```
> 
> **flutter run --verbose**（按“立即购买”按钮后的日志）
> 
> ```
> [+8331 ms] flutter: Buy Now tapped
> [   +3 ms] flutter: iOS Apple Pay
> [   +3 ms] flutter: IAP Product Length : 1
> [  +14 ms] flutter: IAP PRODUCT **** : com.edustar.learn_python_masterclass
> [  +24 ms] flutter: Product ID com.edustar.learn_python_masterclass
> [ +189 ms] flutter: Pending State
> [+8299 ms] flutter: state = AppLifecycleState.inactive
> [+12126 ms] flutter: state = AppLifecycleState.resumed
> [+21905 ms] flutter: state = AppLifecycleState.inactive
> [+11969 ms] flutter: state = AppLifecycleState.resumed
> [+28315 ms] flutter: Product IDcom.edustar.learn_python_masterclass
> [        ] flutter: Error State
> [  +42 ms] flutter: {NSLocalizedDescription: Cannot connect to iTunes Store}
> [        ] flutter: Pending Complete State
> ```

I also encountered the same problem, please help!

**Comment by ceokin** [comment]
I am currently facing the same issue. It worked correctly 5 days ago, but suddenly I got the same error than @vinothvino42 .  I use an iPhone running on 13.7.

It is weird because I can retrieve the product of In App Purchases however I cannot buy them.

I got in touch with Apple to know further about this. No answer so far. Could you please help us?

**Comment by vinothvino42** [comment]
> I am currently facing the same issue. It worked correctly 5 days ago, but suddenly I got the same error than @vinothvino42 . I use an iPhone running on 13.7.
> 
> It is weird because I can retrieve the product of In App Purchases however I cannot buy them.
> 
> I got in touch with Apple to know further about this. No answer so far. Could you please help us?

Hi @ceokin, Have you ever tried running it in iOS 14 device? I don't have one, if you have device running iOS 14 then give it a try. Maybe it'll work!

**Comment by ceokin** [comment]
Hi @vinothvino42 I just tried it on iOS 14.0.1 and it finally worked. I am not getting that error anymore. I do not know why it stopped working on iOS 13.7. I have another issue, I do not why a popup is shown requesting paternal permission. Any help with this? I press on the request button and it does nothing.

![WhatsApp Image 2020-10-20 at 17 07 51](https://user-images.githubusercontent.com/9987374/96607179-61fb9880-12f8-11eb-9f5a-43e748d520ad.jpeg)

**Comment by phuongtinhbien** [comment]
> Hi @vinothvino42 I just tried it on iOS 14.0.1 and it finally worked. I am not getting that error anymore. I do not know why it stopped working on iOS 13.7. I have another issue, I do not why a popup is shown requesting paternal permission. Any help with this? I press on the request button and it does nothing.
> 
> ![image](https://user-images.githubusercontent.com/9987374/96607557-c3236c00-12f8-11eb-905a-91ab694ab7ff.jpg)

I got the same issue on iOS 14.0.1 with testing by Sandbox

**Comment by fbardecio** [comment]
I think the error about paternal permission is related to the sandbox option in purchase param, this options doesn't set the sandbox environment, instead it enables the parent permission sandbox testing, try to set it to false!

**Comment by ceokin** [comment]
Thanks a lot @fbardecio I set it to false and the parent permission no longer appears. Thank you so much.

**Comment by TahaTesser** [comment]
Hi @vinothvino42 
Can you please try https://github.com/flutter/flutter/issues/68483#issuecomment-712985351 and does it solve your issue?

**Comment by vinothvino42** [comment]
Yes, it's working good. But this problem is not related to [#68483 (comment)](https://github.com/flutter/flutter/issues/68483#issuecomment-712985351) parental permission. Initially, it displays the Confirm Purchase dialog two times for entering password (I tried it with [flutter_in_app_purchase](https://pub.dev/packages/flutter_inapp_purchase) package also, the same error only). Today I tried IAP again with that (flutter_in_app_purchase) package and worked fine. Now again I tried with this **in_app_purchase** package, IAP is working well. May be the problem is from the Apple side. Thank you so much for the help! @TahaTesser
