### ISSUE TITLE
Can't auto-play video from a flutter web app

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#68482]
## Steps to Reproduce
Use the example plugin from video_player plugins.
Since mixWithOthers is not implemented on web.
Just remove the video player option from the main.dart in the initState method.
so comment or remove this line
`videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),`

Also change the folowwing line in the initState
`_controller.initialize(); `
with
`_controller.initialize().then((value) => _controller.play());`

**Expected results:**
Since we are running in an application, we would like to be able to play the video even if the user does not interact with the player.

**Actual results:** 
The video is not playing because of:
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Flutter Doctor:**

<details> 
<summary>flutter doctor -v</summary> 

```bash

[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [version 10.0.19041.508], locale fr-CA)
    • Flutter version 1.23.0-18.1.pre at C:\dev\flutter
    • Framework revision 198df796aa (4 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\mathu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\mathu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.68

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @wer-mathurin 
Please try this code sample on the latest ` video_player: ^0.11.1+2`, it plays a video on the web with no issues 

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize().then((_) {
        _controller.play();

        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (4 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 193EBBC9-CC2A-4477-B8A0-A5F12BB51400 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 86.0.4240.80

• No issues found!
```

</details>

**Comment by wer-mathurin** [comment]
Hi @TahaTesser,

Nope !

It will not work until you interact with the player.

I started the provided sample from the terminal :
**flutter run -d chrome --verbose**

<details>
PS C:\temp\video> flutter run -d chrome --verbose
[  +97 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 198df796aa80073ef22bdf249e614e2ff33c6895
[        ] executing: [C:\dev\flutter/] git tag --points-at HEAD
[  +51 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.23.0-18.1.pre
[   +9 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/beta
[   +2 ms] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +83 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] executing: C:\Users\mathu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] executing: C:\Users\mathu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +66 ms] Found plugin video_player at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+2\
[   +8 ms] Found plugin video_player_web at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.4\
[ +154 ms] Found plugin video_player at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+2\
[   +3 ms] Found plugin video_player_web at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.4\
[  +15 ms] Generating C:\temp\video\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +41 ms] List of devices attached
[  +66 ms] Launching lib\main.dart on Chrome in debug mode...
[  +19 ms] List of devices attached
[ +114 ms] Updating assets
[  +89 ms] Syncing files to device Chrome...
[  +22 ms] Found plugin video_player at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+2\
[   +2 ms] Found plugin video_player_web at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.4\
[  +19 ms] Found plugin video_player at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+2\
[  +13 ms] Found plugin video_player_web at C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.4\
[  +10 ms] Generating C:\temp\video\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +69 ms] <- reset
[  +13 ms] C:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\dev\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\dev\flutter\bin\cache\flutter_web_sdk/        
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill C:\Users\mathu\AppData\Local\Temp\flutter_tools.1cc4058b\flutter_tool.a3b40724\app.dill --libraries-spec
file:///C:/dev/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root C:\Users\mathu\AppData\Local\Temp\flutter_tools.1cc4058b\flutter_tools.75d2520a      
--filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform
file:///C:/dev/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +20 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+11920 ms] Syncing files to device Chrome... (completed in 12 085ms, longer than expected)
[   +1 ms] Synced 28.2MB.
[   +1 ms] <- accept
[   +8 ms] Caching compiled dill
[ +205 ms] Using Ouverture dans une session de navigateur existante.

[ +261 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:61473/devtools/browser/d94af899-cd5f-4b9d-ac1e-d1dbae903bf4
[+5353 ms] Debug service listening on ws://127.0.0.1:61506/k7Tnf4P7e-o=

[ +229 ms] Debug service listening on ws://127.0.0.1:61506/k7Tnf4P7e-o=
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[ +693 ms] NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
</details>

**Comment by MichealReed** [comment]
You can only autoplay videos on web if the volume is first muted.

**Comment by wer-mathurin** [comment]
@MichealReed ,

it work,
but setting the volume to 0 and call the play() after everything works!
