### ISSUE TITLE
Request for the Async version of hello_services

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6848]
The current hello_services example is useful for the sync API, but many APIs prefer an async API. That is, from the Dart side, the request is sent and the response is a Future that completes later. On the Java/ObjC side, the results aren't immediately available, but do complete at some point.

We'd love an example in hello_services that shows off OnMessageListenerAsync (on the Java side, and its equivalent ObjC code), and PlatformMessages.sendJSON on the Dart side.

Thanks!

**Comment by sethladd** [comment]
fyi @faisalabid

**Comment by sethladd** [comment]
We might also want to use this opportunity to show how to trigger and wait for a runtime permission for Android M+ users. Since that forces you into an async world anyway, we can show both async service interop and triggering a runtime permission request in this sample.

**Comment by sethladd** [comment]
We had an internal evaluator ask why Flutter can't do async host messages. :) We might want to bump this up when we're ready to merge Hello_services with the main workflow.

**Comment by mit-mit** [comment]
The new plugin framework is now available and uses async, and there is a sample available:
https://github.com/flutter/flutter/tree/master/examples/platform_services

https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-from-using-PlatformMessages-to-using-channels
