### ISSUE TITLE
Services: not displaying errors/exceptions from Java side in flutter logs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6849]
If there's a runtime exception in the Java code of a running Flutter app, we don't see an actionable log entry in the flutter logs output.

Here's what we see in the Flutter console output:

```
Built android/app/build/outputs/apk/app-debug.apk (7.5MB).
Running lib/main.dart on Moto G 4...
E/flutter (14047): [ERROR:../../flutter/assets/unzipper_provider.cc(16)] Unable to open zip file: /data/user/0/com.example.flutter/app_sky_shell/app.flx
F/flutter (14047): [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report
```

See "unable to open zip file" , which is a bit weird because the actual error on the Java side was actually about not getting a file path correct. :)

Since we knew enough of adb, we did display the log. But, for the less experienced developer, we'll want to show log entries from the Java code from a Flutter app (especially, the Java code the user wrote).

**Comment by sethladd** [comment]
fyi @faisalabid

**Comment by sethladd** [comment]
How does this work in the new interop infra? Have we looked at a case like this?

cc @mit-mit

**Comment by mit-mit** [comment]
@mravn-google?

**Comment by mravn-google** [comment]
Errors occurring in platform code can be transferred to the Flutter side in a standard way using the new API. Log entries created in platform code is not handled by the interop API.

**Comment by mit-mit** [comment]
Closing: This should be handled by the fact that you can handle the exceptions on the Dart side using the new API.

**Comment by Hixie** [comment]
I don't think this is an interop API issue. I think it's a tool issue. If there's an exception on the Java or ObjectiveC side, even unrelated to the plugin API, we should still show it in the logs in `flutter run` and `flutter logs`.

**Comment by eseidelGoogle** [comment]
@jason-simmons indicated interest.

@Hixie suggested possibly showing everything from the flutter process.

Presumably our filtering is too aggressive in `flutter logs`.
