### ISSUE TITLE
Add selectionOverlay parameter to CupertinoTimerPicker 

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#68509]
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-RU)

**Comment by DanielEdrisian** [comment]
@sanekyy Can you provide more context on this issue?

**Comment by sanekyy** [comment]
I can't provide selectionOverlay to CupertinoTimerPicker to override default value of this parameter.

I want customize it, but I can't with current api.

**Comment by lecicdjuro** [comment]
CupertinoDatePicker don't have optional param for selectionOverlay Widget, so it can't be overriden or changed.
This class should have the same option as CupertinoPicker, so we can change this overlay widget.

**Comment by daadu** [comment]
I think the right design for this would be to not add `Widget selectionOverlay` to either `CupertinoTimePicker` or `CupertinoDateTimePicker`,  or any other "Picker".

Instead I propose to add `pickerSelectionColor` to `CupertinoTheme` (defaulting to `CupertinoColors.tertiarySystemFill`), and the `CupertinoPickerDefaultSelectionOverlay` used underneath `CupertinoPicker`, defaults to `CupertinoTheme.pickerSelectionColor`.

**Comment by TetrixGauss** [comment]
what is going on with that update????

**Comment by Deepakuklan** [comment]
Any update? or everything in flutter we need to rebuild from scratch!

**Comment by PashnyukD** [comment]
It was open since 2020, how long to wait?!

**Comment by nosovk** [comment]
It would be nice to have that in base library (without using some handmaid stuff, just from the box)

**Comment by HansMuller** [comment]
A fix appears to be underway - https://github.com/flutter/flutter/pull/143079

**Comment by MitchellGoodwin** [comment]
Fixed as a part of #143079
