### ISSUE TITLE
On tip of trunk Flutter the web debugging flow fails with null safety related type errors

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#68507]
Repro: try to debug any flutter web application with tip of trunk Flutter and DDC. You will see the following failure due to type errors in the VM service running as part of (flutter tools?).
![image](https://user-images.githubusercontent.com/1226812/96496230-d271bf00-11fd-11eb-84c4-c8d11a3c9838.png)

**Comment by jonahwilliams** [comment]
Is this in a particular IDE? I don't believe the tool calls anything called addFields anywhere - from the identifier that looks like the Java VM Service code?

**Comment by jacob314** [comment]
This was just command line. It is possible some dependencies have already been updated and this no-longer repros.

**Comment by ferhatb** [comment]
Cannot repro. Several null issues were closed this week.
