### ISSUE TITLE
Services: Not clear you need to pass JSON-compatible data with MessageResponse.send(String)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6850]
`FlutterView.MessageResponse.send()` takes a _String_, but sometimes it actually has to be passed JSON-compatible strings, when the Dart side called `sendJSON`.

If you pass a non-JSON string in response to `sendJSON`, you will get an exception.

For API navigation and clarity when code completing, it would be really nice if there was something like `MessageResponse.send(JSON json)` in response to Dart's `sendJSON`. This makes it very clear that the response _must_ be JSON.

Thanks!

**Comment by sethladd** [comment]
fyi @faisalabid

**Comment by mit-mit** [comment]
@mravn I think this doesn't apply in the new framework?

**Comment by mravn-google** [comment]
No longer applies.
