### ISSUE TITLE
JavaScript source code instead of Dart source code is shown when displaying toString for closures

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#68506]
It would be more useful for users if we showed the source mapped Dart source code instead like we source map stack traces. An alternative could be to just display the type signature and let users navigate to the source location if they want to see the implementation.

Repro: view any closure in the debugger. You will see the distracting JS source code.
![image](https://user-images.githubusercontent.com/1226812/96496011-86267f00-11fd-11eb-8257-46bdc280c87a.png)

Fyi @nshahan

**Comment by nshahan** [comment]
cc @annagrin

**Comment by grouma** [comment]
What's the behavior on the VM? I agree, we should at the very least show the type signature. Getting the complete source code may be difficult.

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/1184
