### ISSUE TITLE
msg's executing time is too long

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#68519]
```
[+6191 ms] E/ANR_LOG (22835): >>> msg's executing time is too long
[   +7 ms] E/ANR_LOG (22835): Blocked msg = { when=-12s299ms what=0 target=android.os.Handler
callback=UF } , cost  = 5562 ms
[  +57 ms] E/ANR_LOG (22835): >>>Current msg List is:
[  +70 ms] E/ANR_LOG (22835): Current msg <1> = { when=-7s255ms what=0 target=mn
callback=com.google.maps.api.android.lib6.impl.bn }
[  +64 ms] E/ANR_LOG (22835): Current msg <2> = { when=-5s686ms what=0
target=android.view.Choreographer$FrameHandler
callback=android.view.Choreographer$FrameDisplayEventReceiver }
[  +57 ms] E/ANR_LOG (22835): Current msg <3> = { when=-5s417ms what=0 target=mn
callback=com.google.maps.api.android.lib6.gmm6.api.b }
[  +60 ms] E/ANR_LOG (22835): Current msg <4> = { when=-5s417ms what=0 target=mn
callback=com.google.maps.api.android.lib6.impl.w }
[  +53 ms] E/ANR_LOG (22835): Current msg <5> = { when=-4s517ms what=1 target=ig obj=ny@8f9ce9f }
[   +4 ms] E/ANR_LOG (22835): Current msg <6> = { when=+59s901ms what=0 target=android.os.Handler   
callback=UF }
[  +10 ms] E/ANR_LOG (22835): >>>CURRENT MSG DUMP OVER<<<
[  +48 ms] I/hnology.ime.ap(22835):
Thread[5,tid=22846,WaitingInMainSignalCatcherLoop,Thread*=0x79f1f43c00,peer=0x131c0360,"Signal      
Catcher"]: reacting to signal 3
[  +17 ms] I/hnology.ime.ap(22835): 
[  +47 ms] W/hnology.ime.ap(22835): Suspending all threads took: 25.655ms
[  +10 ms] W/hnology.ime.ap(22835): Suspending all threads took: 38.785ms
[+1220 ms] V/NativeCrypto(22835): Read error: ssl=0x7991abd888: SSL_ERROR_WANT_READ occurred. You
should never see this.
[ +214 ms] I/LooperMessageSuperviser(22835): NoSuchMethodException :
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[  +96 ms] W/System.err(22835): java.lang.NoSuchMethodException:
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[  +20 ms] W/System.err(22835):         at java.lang.Class.getMethod(Class.java:2072)
[  +50 ms] W/System.err(22835):         at java.lang.Class.getDeclaredMethod(Class.java:2050)
[   +9 ms] W/System.err(22835):         at
android.os.LooperMessageSuperviser.callDeclaredMethod(LooperMessageSuperviser.java:155)
[   +6 ms] W/System.err(22835):         at
android.os.LooperMessageSuperviser.endLooperMessage(LooperMessageSuperviser.java:112)
[  +59 ms] W/System.err(22835):         at android.os.Looper.loop(Looper.java:263)
[  +53 ms] W/System.err(22835):         at android.app.ActivityThread.main(ActivityThread.java:7853)[  +10 ms] W/System.err(22835):         at java.lang.reflect.Method.invoke(Native Method)
[  +50 ms] W/System.err(22835):         at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[  +14 ms] W/System.err(22835):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[ +457 ms] I/Choreographer(22835): Skipped 541 frames!  The application may be doing too much work
on its main thread.
[ +516 ms] I/hnology.ime.ap(22835): Wrote stack traces to tombstoned
[+4822 ms] I/Choreographer(22835): Skipped 1 frames!  The application may be doing too much work on
its main thread.
[+8650 ms] F/crash_dump64(13198): crash_dump.cpp:465] failed to attach to thread 512: Permission
denied
[+23937 ms] I/hnology.ime.ap(22835): Background young concurrent copying GC freed 132075(5532KB)
AllocSpace objects, 16(320KB) LOS objects, 26% free, 15MB/21MB, paused 219.705ms total 601.526ms    
[+2218 ms] E/ANR_LOG (22835): >>> msg's executing time is too long
[   +4 ms] E/ANR_LOG (22835): Blocked msg = { when=-3s0ms what=0
target=android.view.Choreographer$FrameHandler
callback=android.view.Choreographer$FrameDisplayEventReceiver } , cost  = 3000 ms
[  +65 ms] E/ANR_LOG (22835): >>>Current msg List is:
[  +59 ms] E/ANR_LOG (22835): Current msg <1> = { when=+16s454ms what=0 target=android.os.Handler
callback=UF }
[  +86 ms] E/ANR_LOG (22835): Current msg <2> = { when=+57s759ms what=0
target=com.google.android.gms.internal.measurement.zzm
callback=com.google.android.gms.measurement.internal.zzah }
[  +69 ms] E/ANR_LOG (22835): >>>CURRENT MSG DUMP OVER<<<
[ +645 ms] I/LooperMessageSuperviser(22835): NoSuchMethodException :
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[  +93 ms] W/System.err(22835): java.lang.NoSuchMethodException:
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[ +114 ms] W/System.err(22835):         at java.lang.Class.getMethod(Class.java:2072)
[  +11 ms] W/System.err(22835):         at java.lang.Class.getDeclaredMethod(Class.java:2050)
[  +70 ms] W/System.err(22835):         at
android.os.LooperMessageSuperviser.callDeclaredMethod(LooperMessageSuperviser.java:155)
[  +64 ms] W/System.err(22835):         at
android.os.LooperMessageSuperviser.endLooperMessage(LooperMessageSuperviser.java:112)
[ +121 ms] W/System.err(22835):         at android.os.Looper.loop(Looper.java:263)
[   +5 ms] W/System.err(22835):         at android.app.ActivityThread.main(ActivityThread.java:7853)[  +70 ms] W/System.err(22835):         at java.lang.reflect.Method.invoke(Native Method)
[  +11 ms] W/System.err(22835):         at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[  +76 ms] W/System.err(22835):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[  +62 ms] I/Choreographer(22835): Skipped 1 frames!  The application may be doing too much work on
its main thread.
[+5082 ms] F/crash_dump64(13456): crash_dump.cpp:465] failed to attach to thread 512: Permission
denied
[ +556 ms] E/ANR_LOG (22835): >>> msg's executing time is too long
[   +6 ms] E/ANR_LOG (22835): Blocked msg = { when=-5s757ms what=159
target=android.app.ActivityThread$H obj=ClientTransaction hashCode, mActivityToken =
android.os.BinderProxy@6a0c07c mLifecycleStateRequest null mActivityCallbacks
[TopResumedActivityChangeItem{onTop=false}] } , cost  = 5757 ms
[  +72 ms] E/ANR_LOG (22835): >>>Current msg List is:
[  +67 ms] E/ANR_LOG (22835): Current msg <1> = { when=-5s716ms what=0
target=android.graphics.SurfaceTexture$1 }
[  +14 ms] E/ANR_LOG (22835): Current msg <2> = { when=-5s396ms what=159
target=android.app.ActivityThread$H obj=ClientTransaction hashCode, mActivityToken =
android.os.BinderProxy@6a0c07c mLifecycleStateRequest
PauseActivityItem{finished=true,userLeaving=false,configChanges=0,dontReport=false}
mActivityCallbacks [] }
[ +129 ms] E/ANR_LOG (22835): Current msg <3> = { when=-3s426ms what=6
target=android.view.ViewRootImpl$ViewRootHandler }
[  +22 ms] E/ANR_LOG (22835): Current msg <4> = { when=-81ms what=0
target=com.google.android.gms.internal.tasks.zzb callback=com.google.android.gms.tasks.zzp }        
[  +65 ms] E/ANR_LOG (22835): Current msg <5> = { when=+9s155ms what=0 target=android.os.Handler
callback=UF }
[   +6 ms] E/ANR_LOG (22835): Current msg <6> = { when=+50s460ms what=0
target=com.google.android.gms.internal.measurement.zzm
callback=com.google.android.gms.measurement.internal.zzah }
[  +66 ms] E/ANR_LOG (22835): >>>CURRENT MSG DUMP OVER<<<
[ +118 ms] I/LooperMessageSuperviser(22835): NoSuchMethodException :
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[  +60 ms] W/System.err(22835): java.lang.NoSuchMethodException:
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[ +262 ms] Service protocol connection closed.
[  +20 ms] Lost connection to device.
```

**Comment by sidrao2006** [comment]
Hello @imeDevelopers ,
Could you please post the output of `flutter doctor -v` and a complete minimal reproducible code sample
Thank you!

**Comment by darshankawar** [comment]
@imeDevelopers 
Please provide above requested details in order to properly analyse the issue.

**Comment by imeDevelopers** [comment]
[ +204 ms] E/ANR_LOG ( 9036): >>> msg's executing time is too long
[  +46 ms] E/ANR_LOG ( 9036): Blocked msg = { when=-13s595ms what=0 target=android.view.Choreographer$FrameHandler
callback=android.view.Choreographer$FrameDisplayEventReceiver } , cost  = 10413 ms
[  +79 ms] E/ANR_LOG ( 9036): >>>Current msg List is:
[  +61 ms] E/ANR_LOG ( 9036): Current msg <1> = { when=-1d4h46m54s519ms what=0
target=android.view.ViewRootImpl$ViewRootHandler
callback=android.view.-$$Lambda$ViewRootImpl$7A_3tkr_Kw4TZAeIUGVlOoTcZhg }
[  +15 ms] E/ANR_LOG ( 9036): Current msg <2> = { when=-13s269ms what=0 target=mn
obj=com.google.android.gms.clearcut.service.START }
[  +65 ms] E/ANR_LOG ( 9036): Current msg <3> = { when=-13s112ms what=2
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=398 }
[  +60 ms] E/ANR_LOG ( 9036): Current msg <4> = { when=-13s112ms what=2
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=398 }
[  +62 ms] E/ANR_LOG ( 9036): Current msg <5> = { when=-13s91ms what=3
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=398 }
[   +6 ms] E/ANR_LOG ( 9036): Current msg <6> = { when=-13s91ms what=3
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=398 }
[  +55 ms] E/ANR_LOG ( 9036): Current msg <7> = { when=-13s10ms what=1
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=399 }
[  +64 ms] E/ANR_LOG ( 9036): Current msg <8> = { when=-13s10ms what=1
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=399 }
[   +7 ms] E/ANR_LOG ( 9036): Current msg <9> = { when=-11s901ms what=2
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=399 }
[  +58 ms] E/ANR_LOG ( 9036): Current msg <10> = { when=-11s901ms what=2
target=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate arg1=399 }
[  +62 ms] E/ANR_LOG ( 9036): >>>CURRENT MSG DUMP OVER<<<
[  +12 ms] I/LooperMessageSuperviser( 9036): NoSuchMethodException : android.app.IActivityManager.sendTheiaEvent
[class java.lang.String]
[  +57 ms] W/System.err( 9036): java.lang.NoSuchMethodException: android.app.IActivityManager.sendTheiaEvent [class
java.lang.String]
[  +56 ms] W/System.err( 9036):         at java.lang.Class.getMethod(Class.java:2072)
[  +11 ms] W/System.err( 9036):         at java.lang.Class.getDeclaredMethod(Class.java:2050)
[  +46 ms] W/System.err( 9036):         at
android.os.LooperMessageSuperviser.callDeclaredMethod(LooperMessageSuperviser.java:155)
[  +15 ms] W/System.err( 9036):         at
android.os.LooperMessageSuperviser.endLooperMessage(LooperMessageSuperviser.java:112)
[  +68 ms] W/System.err( 9036):         at android.os.Looper.loop(Looper.java:263)
[  +50 ms] W/System.err( 9036):         at android.app.ActivityThread.main(ActivityThread.java:7853)
[   +9 ms] W/System.err( 9036):         at java.lang.reflect.Method.invoke(Native Method)
[  +56 ms] W/System.err( 9036):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[  +74 ms] W/System.err( 9036):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[  +50 ms] D/ColorViewRootUtil( 9036): nav bar mode ignore false downX 435 downY 994 mScreenHeight 1600 mScreenWidth
720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN,
actionButton=0, id[0]=0, x[0]=435.0, y[0]=994.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE,   
metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=103604452, downTime=103604452,       
deviceId=6, source=0x1002, displayId=0 }
[ +130 ms] I/Choreographer( 9036): Skipped 660 frames!  The application may be doing too much work on its main
thread.
E/chromium( 9036): [ERROR:aw_browser_terminator.cc(123)] Renderer process (2887) crash detected (code -1).

**Comment by imeDevelopers** [comment]
device: realme 5
android: 10
dev system: windows 10
channel: master
editor: VS code

**Comment by darshankawar** [comment]
@imeDevelopers 
Please provide `pubspec.yaml` and a minimal complete reproducible code sample that could possibly show the log you are seeing.
Thanks.

**Comment by CiriousJoker** [comment]
@darshankawar 
I usually don't throw shade at people on the internet, but this guy apparently doesn't want to read or follow basic troubleshooting instructions as evidenced by his comment history.

My personal highlight and the reason why I clicked on his profile originally is this: https://github.com/ezet/stripe-sdk/issues/75

As for actually solving the issue, I'd look up the meaning of this:

```
Read error: ssl=0x7991abd888: SSL_ERROR_WANT_READ occurred. You
should never see this.
```
It seems to be the most interesting part. 

Maybe the minSdk was updated and SSL broke with one of the APIs getting deprecated? At this point anything is speculation though obv..

**Comment by vickys297** [comment]
Even i had the same issue with Physical Device which is Realme X.
My Issue is when i try to retrieve contact using paging library 3 the process was too slow
`2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: >>> msg's executing time is too long
2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: Blocked msg = { when=-12s283ms what=0 target=android.os.Handler callback=androidx.fragment.app.FragmentManager$4 } , cost  = 12240 ms
2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: >>>Current msg List is:
2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <1>  = { when=-12s254ms what=0 target=android.os.Handler callback=android.view.-$$Lambda$1kvF4JuyM42-wmyDVPAIYdPz1jE }
2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <2>  = { when=-12s254ms what=0 target=android.os.Handler callback=android.view.-$$Lambda$1kvF4JuyM42-wmyDVPAIYdPz1jE }
2021-05-29 22:28:57.008 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <3>  = { when=-12s254ms what=0 target=android.os.Handler callback=android.view.-$$Lambda$1kvF4JuyM42-wmyDVPAIYdPz1jE }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <4>  = { when=-12s253ms what=0 target=android.os.Handler callback=android.view.-$$Lambda$1kvF4JuyM42-wmyDVPAIYdPz1jE }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <5>  = { when=-12s240ms what=0 target=android.os.Handler callback=androidx.fragment.app.FragmentManager$4 }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <6>  = { when=-12s235ms what=6 target=android.view.ViewRootImpl$ViewRootHandler }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <7>  = { when=-12s232ms what=6 target=android.view.ViewRootImpl$ViewRootHandler }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <8>  = { when=-12s168ms barrier=83 }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <9>  = { when=-1ms what=0 target=android.view.ViewRootImpl$ViewRootHandler callback=androidx.fragment.app.FragmentAnim$EndViewTransitionAnimation }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: Current msg <10>  = { when=+949ms what=131 target=android.app.ActivityThread$H obj=android.app.ActivityThread$ProviderRefCount@44a3334 }
2021-05-29 22:28:57.009 14250-14250/com.v.simplydo E/ANR_LOG: >>>CURRENT MSG DUMP OVER<<<`

Above is my log 

But Using my emulator i didn't had any issue ui was was more smooth than my physical device.

Not sure about the issue need some help
