### ISSUE TITLE
IOS /ANDROID Home widgets

### ISSUE THREAD

**Issue by edwin-alvarez** [flutter/flutter#68515]
We really need home widgets 
https://9to5mac.com/2020/10/19/widgetsmith-ios-14-home-screen-widgets/

**Comment by TahaTesser** [comment]
Hi @edwin-alvarez 
You can all iOS 14 related issues here https://github.com/flutter/flutter/issues/61047 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/60026
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
