### ISSUE TITLE
Moto G4 with serial ZY223TDZ45 is failing tests because of insufficient storage

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#68517]
Looks like the Moto G4 with serial ZY223TDZ45 is failing tests because of insufficient storage. It probably needs to be cleaned out.

An example failure are the builds for complex_layout_android__scroll_smoothness on ref 8c03ff8c1d42d25387e4a049c69b74a0f4949227 (sorry, can't find any good way to link to the logs here).

**Comment by jonahwilliams** [comment]
Storage is filling up much more quickly now. The startup tests will install the same application 15 times, which leads to 14 old apk files kept in temp. This is going to be addressed in https://github.com/flutter/flutter/pull/68516

**Comment by godofredoc** [comment]
Cleaning up phone.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/68537 for tracking issue on fixing devicelab tests

**Comment by godofredoc** [comment]
Phone has been cleaned up
