### ISSUE TITLE
Services: missing example of the error case in hello_services

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6851]
We're not sure how to handle an error when writing a service. We didn't see an example of error cae in https://github.com/flutter/flutter/blob/master/examples/hello_services/android/app/src/main/java/com/example/flutter/ExampleActivity.java

We'd love to know:

* how to signal an error back up to Dart from the Java and ObjC code

**Comment by sethladd** [comment]
fyi @faisalabid

**Comment by mit-mit** [comment]
@szakarias @mravn-google don't we have this now?

**Comment by mit-mit** [comment]
In https://github.com/flutter/flutter/tree/master/examples/platform_services, I mean

**Comment by mravn-google** [comment]
It's part of platform_services now, yes.
