### ISSUE TITLE
[web] Text selection is not giving TextPosition results using TextSpans on web

### ISSUE THREAD

**Issue by WillCanU** [flutter/flutter#68525]
Text selection is not giving TextPosition results on Paragraph._getPositionForOffset when using TextSpans with different styles. I believe this is the issue referenced in the [Zefyr package here](https://github.com/memspace/zefyr/issues/110#issuecomment-701147373).

## Here is a rough code snippet to reproduce: 
Note, this works on mobile, but not web

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  // This widget is the root of your application.
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController controller;

  @override
  void initState() {
    controller = CustomTextEditingController()
      ..text = 'Here is some <*>text</*> that is changing on the fly';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: TextField(
            controller: controller,
          ),
        ),
      ),
    );
  }
}


class CustomTextEditingController extends TextEditingController {
  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    final newText = text.split('<*>');

    return TextSpan(
        style: style,
        children: newText.map((text) {
          final styleSplit = text.split('</*>');

          if (styleSplit.length > 1) {
            return TextSpan(
                style: TextStyle(color: Colors.red), text: styleSplit.first);
          } else {
            return TextSpan(text: styleSplit.first);
          }
        }).toList());
  }
}

```
[Edit]
<details>
<summary>flutter doctor -v</summary>

> [✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
>     • Flutter version 1.23.0-18.1.pre at /Users/willissmith/flutter
>     • Framework revision 198df796aa (5 days ago), 2020-10-15 12:04:33 -0700
>     • Engine revision 1d12d82d9c
>     • Dart version 2.11.0 (build 2.11.0-213.1.beta)
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0.1, Build version 12A7300
>     • CocoaPods version 1.9.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.50.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.15.0
> 
> [✓] Connected device (2 available)
>     • Web Server (web) • web-server • web-javascript • Flutter Tools
>     • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.80

</details>

**Expected behavior** When clicking on a character in the TextField the text cursor should move to that position to input text at that new position.  

**Actual behavior** When clicking on a character in the TextField the text cursor jumps to the start of the TextField.

**Comment by darshankawar** [comment]
@WillCanU 
Please provide `flutter doctor -v` and expected behavior when you say text selection is not giving text position.

**Comment by WillCanU** [comment]
I have updated the original post with flutter doctor -v and expected behavior. 

However, I think it is [related to this issue](https://github.com/flutter/flutter/issues/55587)

**Comment by darshankawar** [comment]
@WillCanU Thanks for updating the issue. Would you be okay to follow-up in the related issue and close this one as duplicate ?

**Comment by WillCanU** [comment]
Closing as duplicate, see [this issue for progress](https://github.com/flutter/flutter/issues/55587)
