### ISSUE TITLE
re-enable test "flutter_driver_screenshot_test_ios" in framework repo

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#68524]
Location: https://github.com/flutter/flutter/tree/master/dev/integration_tests/flutter_driver_screenshot_test

This test was disabled because we wanted to move the golden image out of the flutter/flutter repo, we should re-enable it as soon as possible, it might be done in one of the two ways:
1. Move the golden image to the flutter/golden repo and do the image diff with a remote image.
2. Update the golden api so that we can use it in the device lab.

**Comment by goderbauer** [comment]
(triage) Closing this since the test has been deleted in #76575
