### ISSUE TITLE
[url_launcher_web] class 'UrlLauncherPlugin' is missing implementations

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#68545]
I'm on the dev channel.  I can't run my web app.

This worked previously. 

Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.4+1/lib/url_launcher_web.dart:22:7: Error: The non-abstract class 'UrlLauncherPlugin' is missing implementations for these members:
 - UrlLauncherPlatform.linkDelegate
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class UrlLauncherPlugin extends UrlLauncherPlatform {
      ^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.9/lib/url_launcher_platform_interface.dart:43:20: Context: 'UrlLauncherPlatform.linkDelegate' is defined here.
  LinkDelegate get linkDelegate;
                   ^^^^^^^^^^^^
Failed to compile application.

**Comment by liudonghua123** [comment]
I have the same issue.  `url_launcher_web-0.1.4+1` does not compatiable with `url_launcher_platform_interface-1.0.9`.  The `url_launcher_platform_interface-1.0.9` breaks the dependences.

I have a github ci/cd (https://github.com/liudonghua123/system_network_proxy/runs/1279010922?check_suite_focus=true) failed with this error.

Now I add the following snippets.

```yaml
dependency_overrides:
  url_launcher_platform_interface: 1.0.8
```

**Comment by darshankawar** [comment]
@sgehrman 
Can you provide a complete minimal reproducible code sample that shows the issue.
Thanks/

**Comment by deakjahn** [comment]
I can't see why a reproducible sample should be needed. :-) The interface got a new item:

https://github.com/flutter/plugins/blob/9560b2ac8eaf23bc5568aafca229de2ef83dac5e/packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart#L43

This has to be implemented in all plugins using that interface.

**Comment by liudonghua123** [comment]
That's really strange, I have correct `pubspec.lock` file which contains resolved `url_launcher: 5.7.4` and  `url_launcher_platform_interface: 1.0.8`. And the local `flutter build web` success without errors. However it seems the github ci runner got `url_launcher: 5.7.4` and  `url_launcher_platform_interface: 1.0.9` when execute `flutter pub get`.

**Comment by liudonghua123** [comment]
I also tried update `url_launcher: ^5.7.5` and run `flutter pub get` and `flutter pub upgrade`, the `pubspec.lock` contains resolve `url_launcher: 5.7.5` and `url_launcher_platform_interface: 1.0.9`. But the ci still failed with the same issue.

See more details on https://github.com/liudonghua123/system_network_proxy/runs/1281506660.

**Comment by mdebbar** [comment]
This was my bad. I'm on it. This PR (https://github.com/flutter/plugins/pull/3155) should fix it.

**Comment by ditman** [comment]
Closing the loop here: Mouad [published](https://pub.dev/packages/url_launcher_web/changelog#015) the fix for the build issue. Apologies for the breakage!
