### ISSUE TITLE
ShellTest.ResubmitFrame is flakey for linux

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#68540]
Examples:
  - https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/7319
  - https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/7258

Text:
```
[ RUN      ] ShellTest.ResubmitFrame
../../flutter/shell/common/shell_unittests.cc:1076: Failure
Expected equality of these values:
  1
  external_view_embedder->GetSubmittedFrameCount()
    Which is: 2
```

https://github.com/flutter/engine/pull/21831 was reverted for this flake but now it seems to have manifested itself without that PR.

**Comment by chinmaygarde** [comment]
Duplicate https://github.com/flutter/flutter/issues/66056
