### ISSUE TITLE
Services: we aren't publishing Javadocs for the Java side of the services APIs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6855]
We realized we don't have published/hosted javadocs for the Java side of our services integrations. Specifically, FlutterView and related classes.

Ideally, we'd publish those docs just like we do for the Dart side of interop.

(we'll want to do the same thing for the objc side of interop, too)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/4546 is a related bug.

**Comment by mit-mit** [comment]
Actually, $4546 is the same (I widened it's title a bit), so closing the present issue.
