### ISSUE TITLE
An urgent problem: IOS will be stuck when it opens the route for the first time, and it will become smooth when it is opened again

### ISSUE THREAD

**Issue by ihongwu** [flutter/flutter#68552]
## Details

**Target Platform: IOS**
**Target OS version/browser: 12.4、13.5.1、14.0.1**
**Devices: iPhone6、Iphone6s plus、Other phones have not been tested**
**Flutter version: 1.22.2**

## steps 
Open the app after installing or restarting the mobile phone for the first time. After opening the route for the first time, you can feel obvious stuck. Only when you open the route for the second or third time, the jump will become smooth. This problem only occurs on the IOS platform. When I download other apps developed by flutter in the app store, I found the same problem
## video link
<a href="http://cdn.banaitime.com/test/8697ea757b883cd82572df2d29fdcdbf.mp4">Video Link</a>

## code
```
RaisedButton(
                child: Text("Go"),
                onPressed: () {
                  Future.delayed(Duration(milliseconds: 10),(){
                    Routes.navigateTo(
                      context,
                      Routes.setting,
                      transition: TransitionType.cupertino
                    );
                  });
                },
              ),

              RaisedButton(
                child: Text("Go2"),
                onPressed: () {
                  Future.delayed(Duration(milliseconds: 10),(){
                    Navigator.push(context, CupertinoPageRoute(
                      builder: (context) => Test2(),
                      title: 'ddd',
                    ));
                  });
                },
              ),
            RaisedButton(
                child: Text("Go3"),
                onPressed: () {
                  Future.delayed(Duration(milliseconds: 10),(){
                    Navigator.push(context, CupertinoPageRoute(
                      builder: (context) => CupertinoSharePage(),
                      // title: 'ddd',
                    ));
                  });
                },
              ),

              RaisedButton(
                child: Text("Go4"),
                onPressed: () {
                  Future.delayed(Duration(milliseconds: 10),(){
                    showCupertinoModalBottomSheet(
                      // expand: true,
                      context: context,
                      elevation:30,
                      transitionBackgroundColor:Colors.purple[500],
                      builder: (context, scrollController) => Container(
                        height: 600,
                        child: Test4(),
                      ),
                    );
                  });
                },
              ),
```

**Comment by CosmosExmo** [comment]
Hello, maybe warming up SkSL would help as shown here.

https://flutter.dev/docs/perf/rendering/shader

**Comment by ihongwu** [comment]
@CosmosExmo Sksl compilation has been tested, but the problem has not been solved

**Comment by CosmosExmo** [comment]
@ihongwu You can try OpenGL with SkSL caching. As far as i know SkSL caching doesn't work properly on iOS devices after iPhone 5s. You can find more info in the links below.

#61450 
https://github.com/acoutts/flutter-engines-no-metal

**Comment by ihongwu** [comment]
@CosmosExmo Thank you. I'll try it

**Comment by darshankawar** [comment]
@ihongwu 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that we can copy paste and run directly which shows the issue.
Thanks.

**Comment by ihongwu** [comment]
@darshankawar I'm sorry, I'm not at the computer right now, but the latest version of flutter and dart is the latest version main.dart This problem can be reproduced by simply writing a route jump

**Comment by darshankawar** [comment]
@ihongwu 
It would be good if you could provide the complete code sample, a route jump can be interpreted differently that may not replicate the issue you are facing.

**Comment by ihongwu** [comment]
@CosmosExmo Thank you for the solution, which has successfully made my application smoother. I use the sksl of the new engine flutter engines (metal disabled) to generate flutter_01 sksl.json Can it be applied to the IOS devices used ？

**Comment by ihongwu** [comment]
@darshankawar Thank you. I've used another solution to solve this problem, but I still hope that the official flutter can solve this thorny problem

**Comment by darshankawar** [comment]
@ihongwu 
Glad to know your issue is resolved. I am going ahead and closing this. If you face similar issue again, please open a new issue  by providing all required details or write in comments here and I'll reopen.
Thanks.
