### ISSUE TITLE
iOS builds are blocking non-ssl connections to local network IPs, citing an outdated iOS policy

### ISSUE THREAD

**Issue by tek08** [flutter/flutter#68550]
## Steps to Reproduce

1. Run a Flutter app on iOS (debug, say) that connects to any local network IP address without using SSL, e.g. an API call that hits http://10.0.0.5/sync or a NetworkImage etc...

**Expected results:** 
Up until recently, these connections succeeded, allowing for easy local development.

**Actual results:**
Now, these connections are being denied by Flutter, which on the new [network policy breaking changes page](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android) cites that since iOS 9, ATS has disallowed non-ssl connections by default.  However, that doesn't seem quite correct.  [This page at Apple](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking) explains that ATS enforcement with respect to local IP addresses was reversed in iOS 10.  

The workaround suggests modifying `Info.plist` to add in exceptions for your dev machine IP.  This seems to unnecessarily complicate cutting a production release of an iOS app.  Given [warnings from others](https://github.com/flutter/flutter/issues/66275#issuecomment-710724723) that Apple requires explanation for NSExceptionDomains, are we supposed to modify the plist file before each release, and then again when we want to start debugging locally using our dev server?  Modify our local servers to use SSL?  

If I've done a dumb, let me know, but at the moment, this seems to be a somewhat unnecessary breaking change, at least for iOS.

<details>
  <summary>Logs</summary>

```
I/flutter (28401): Bad state: Insecure HTTP is not allowed by platform: http://10.0.0.15:4000/parcels/
I/flutter (28401):
I/flutter (28401): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
I/flutter (28401): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
I/flutter (28401): #2      IOClient.send
package:http/src/io_client.dart:31
I/flutter (28401): #3      BaseClient._sendUnstreamed
package:http/src/base_client.dart:91
I/flutter (28401): #4      BaseClient.post
package:http/src/base_client.dart:32
I/flutter (28401): #5      ApiClient.invokeAPI
package:openapi/api_client.dart:190
I/flutter (28401): #6      ParcelServiceApi.getParcelsWithHttpInfo
package:openapi/api/parcel_service_api.dart:103
I/flutter (28401): #7      ParcelServiceApi.getParcels
package:openapi/api/parcel_service_api.dart:120

```

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/tek/Library/flutter
    • Framework revision 198df796aa (4 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tek/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • Pixel 2 (mobile) • HT7BG1A05728 • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server   • web-javascript • Flutter Tools
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 86.0.4240.80
```

</details>

**Comment by tek08** [comment]
Never mind.  Looks like ATS encourages https for all connections, including local.  For those looking for a quick and dirty solution to this, [Caddy](https://caddyserver.com/) works alright...

Closed, but with protest, though mostly against Apple.

**Comment by spkersten** [comment]
This [page](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android) mentions settings (Info plist or manifest) that can be changed to allow insecure connections. However, none of those are needed for our app on platforms more recent than those mentioned, and it can still connect over http to a local IP. So I don't think Flutter should be more strict than the platforms.

In our case, we want to connect to an older IoT device that doesn't support HTTPS. Setting `NSAllowsArbitraryLoads` seems too much for that. (We don't want to allow arbitrary connections to the internet.)
