### ISSUE TITLE
Here‘s a hint of "The named parameter 'colors' isn't defined" when I use LinearGradient

### ISSUE THREAD

**Issue by PillarChen** [flutter/flutter#68555]
Here‘s a hint of "The named parameter 'colors' isn't defined" when I use LinearGradient.Because there's one missing @.
gradient.dart @required List<Color> colors
Flutter version 1.22.2 Dart version 2.10.2

**Comment by sidrao2006** [comment]
Hey @PillarChen , this issue occurs usually when you upgrade the flutter tool.
Try restarting your editor.

If this doesn't solve your problem, please post the outputs of `flutter analyze` and `flutter doctor -v`

**Comment by PillarChen** [comment]
The same problem was found in animationcontroller,but it solved my problem as you said.Thank you very much!

**Comment by PillarChen** [comment]
Firstly,I run flutter analyze and flutter doctor -v,and then reopen my project.The problem is gone

**Comment by pedromassangocode** [comment]
Hi @PillarChen 
This is not an issue with Flutter, it is just the analyzer complaining because it was not migrated to null safety yet.
