### ISSUE TITLE
ListView.builder controller listener not listening

### ISSUE THREAD

**Issue by evalsxonted** [flutter/flutter#68564]
## Steps to Reproduce

    import 'dart:developer';

    import 'package:flutter/material.dart';

    class Request extends StatefulWidget {
      @override
      _RequestState createState() => _RequestState();
    }

    class _RequestState extends State<Request> {
      final listController = ScrollController();
      @override
      void initState() {
        listController.addListener(()=> myListener());
        super.initState();
      }
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: ListView.builder(
            reverse: true,
            controller: listController,
            itemCount: 5,
            itemBuilder: (context, index){
              return Container(
                padding: EdgeInsets.all(20),
                margin: EdgeInsets.all(20),
                color: Colors.red,
              );

            },
          ),
        );
      }
      myListener(){
        log("this text will not be shown");
      }
    }

**Expected results:** 
listener should listen to any event like scrolling and so on. or not??? but it will listen when listview is full. if i set itemCount to 20 it will work. but not working if itemCount is 5 for example.

**Actual results:** 
listener not listening to any event.

<details>

```
```

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.20.2 at C:\Users\xonted\flutter-sdk\flutter
    • Framework revision bbfbf1770c (10 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\xonted\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.50.1)
    • VS Code at C:\Users\xonted\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```
```

</details>

**Comment by darshankawar** [comment]
@evalsxonted 
The listView need to be scrollable in order for the listener to listen to events. If you have 5 items in list, the listview won't be scrollable, hence you won't see anything in the logs. But if you have 8 items in the list, the listview becomes scrollable and will listen to the events.

I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen.
Thanks.
