### ISSUE TITLE
The keyboard will disappear when switch focus on two TextField when secure keyboard is enabled 

### ISSUE THREAD

**Issue by ondev** [flutter/flutter#68571]
On my login page, I have two TextField, one for username(obscureText: false,), one for password(obscureText: true,).

after finish the username input, I click in the password textfield, the keyboard will disappear even if the password textfield get the focus. It will appear when click again!  Then, click username textfield again, the keyboard not appear also.

I have open the system secure keyboard:
To enable Secure Keyboard, go to [Settings] > [Additional Settings] > [Keyboard & Input Method] and toggle on [Use Secure Keyboard When Entering a Password].

If I close the system secure keyboard, everything is ok!!

this is my flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)
```

**Comment by pedromassangocode** [comment]
Hi @ondev 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by bmxbandita** [comment]
I have a very similar issue, since i upgraded to Flutter 1.22.2 Stable this morning:
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale hu_HU.UTF-8)
    • Flutter version 1.22.2 at /home/fazekas/flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

Two Textfields in a column like this:
              TextField(
                controller: usernameController,
                textInputAction: TextInputAction.next,
                autofocus: true,
                onSubmitted: (v) {FocusScope.of(context).nextFocus();},
                decoration: InputDecoration(
                  labelText: 'Username',
                ),
              ),
              SizedBox(height: 12.0),
              TextField(
                textInputAction: TextInputAction.done,
                controller: passwordController,
                decoration: InputDecoration(
                  labelText: 'Password',
                ),
                obscureText: true,
              ),

It was working as intended (when i entered the username, and hit the 'Next' button, the focus moved to the password textfield) until the upgrade happened. Since then, when i hit the Next button, the keyboard just disapperars, and nothing happens.

**Comment by bmxbandita** [comment]
> I have a very similar issue, since i upgraded to Flutter 1.22.2 Stable this morning:
> [✓] Flutter (Channel stable, 1.22.2, on Linux, locale hu_HU.UTF-8)
> • Flutter version 1.22.2 at /home/fazekas/flutter
> • Framework revision [84f3d28](https://github.com/flutter/flutter/commit/84f3d28555368a70270e9ac8390a9441df95e752) (5 days ago), 2020-10-15 16:26:19 -0700
> • Engine revision b8752bbfff
> • Dart version 2.10.2

Quick update, i downgraded flutter to 1.20.4, and everything is working fine again.

**Comment by ondev** [comment]
> Hi @ondev
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> The `flutter doctor` you provided is not complete!
> 
> Thank you

Here is my sample code,  If I close the 'Use Secure Keyboard When Entering a Password' in the device system setting, have no such issue. It's same as the system use two keyboards to switch.
`Column(
      children: [
        TextField(
          decoration: const InputDecoration(
            hintText: 'Username',
            contentPadding: const EdgeInsets.all(10.0),
          ),
          onChanged: (val) {
            print(val);
          }
        ),
        TextField(
          obscureText: true,
          decoration: const InputDecoration(
            hintText: 'password',
            contentPadding: const EdgeInsets.all(10.0),
          ),
          onChanged: (val) {
            print(val);
          }
        )
      ],
    )`

`[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (5 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
`

**Comment by pedromassangocode** [comment]
Hi @ondev 
Can you please confirm what device are you using to test this?

I tried to test on a **Xiaomi Redmi 5Plus** but it don't have this "Use Secure Keyboard When Entering a Password" option.

**Comment by doc-rj-celltrak** [comment]
I have the same issue as @bmxbandita and the issue started with flutter 1.22. Possible workaround here: https://stackoverflow.com/a/64227418/5765232

**Comment by doc-rj-celltrak** [comment]
I can confirm the [workaround](https://stackoverflow.com/a/64227418/5765232) works. Tested on iPhone SE with Flutter 1.22.2. The [documentation and sample code for onSubmitted](https://api.flutter.dev/flutter/widgets/EditableText/onSubmitted.html) does say that it should work, but it does not. So, it seems a bug was introduced in 1.22. However, using onEditingComplete does seems to work in its place. Not sure if there are any drawbacks to using this callback instead?

**Comment by TahaTesser** [comment]
Hi everyone,  I can reproduce it on Android 10

Note: Keyboard just disappears when secure keyboard is on, there is no flash as seen in the gif when keyboard disappear, recording only shows black it's the case when you using the app 

| Secure Keyboard **off** |  Secure Keyboard **on** |
| --------------- | --------------- |
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/96842729-07367e00-146b-11eb-8263-32265f92c361.gif) | ![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/96842818-2208f280-146b-11eb-8893-6ec3982ab8ea.gif)



<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController usernameController = TextEditingController();
  TextEditingController passwordController = TextEditingController();

  @override
  void dispose() {
    usernameController.dispose();
    passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            TextField(
              controller: usernameController,
              textInputAction: TextInputAction.next,
              autofocus: true,
              onSubmitted: (v) {
                FocusScope.of(context).nextFocus();
              },
              decoration: InputDecoration(
                labelText: 'Username',
              ),
            ),
            SizedBox(height: 12.0),
            TextField(
              textInputAction: TextInputAction.done,
              controller: passwordController,
              decoration: InputDecoration(
                labelText: 'Password',
              ),
              obscureText: true,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (7 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[✓] Connected device (3 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!

```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-GB)
    • Flutter version 1.24.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 12bea61c29 (7 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7
      19H2 darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.111, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-2.0.pre.111 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision fe189baf34 (6 hours ago), 2020-10-21 22:25:53 -0400
    • Engine revision f459a86610
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7
      19H2 darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment]
cc @xster @blasten Could this be related to the platform views migration?

**Comment by blasten** [comment]
There's no platform views in the attached sample app. The flash looks similar to https://github.com/flutter/flutter/issues/68018#issuecomment-708273369  

I wonder if it's related to keyboard animation fix for Android 10.

**Comment by xster** [comment]
@LongCatIsLooong I vaguely remember we made a similar fix for iOS (wrt non-overlapping view lifecycles).

**Comment by xster** [comment]
This is on 1.20. I don't think either the platform view or the Android 10 changes were present back then. This might be in the original auto-complete related refactor.

**Comment by LongCatIsLooong** [comment]
I can't find the said option either. Tried my own android device and Android 10 emulator image. I'll ask around if anyone has a device with the secure keyboard thing.

On a side note, specifying `textInputAction: TextInputAction.next` and calling `nextFocus()` in the `onSubmitted` callback is roughly equivalent to calling `nextFocus()` twice. In the case when the focus scope only contains 2 focusable text fields (e.g., "user name" and "password" text fields), it goes back to the initial field. I'll add this to the api docs if it's not explained there.

**Comment by LongCatIsLooong** [comment]
Oh it does happen on Android 10 emulator when I tried @TahaTesser's repro.  Removing the redundant `onSubmitted` fixed that for me. 

But @ondev 's code sample doesn't have any of those so looks like it's a different issue. Reminds me of https://github.com/flutter/flutter/issues/65144.

**Comment by doc-rj-celltrak** [comment]
@LongCatIsLooong This may be the wrong thread for this (sorry), but the onSubmitted/nextFocus worked correctly prior to 1.22. The [docs](https://api.flutter.dev/flutter/widgets/EditableText/onSubmitted.html) say: "When a non-completion action is pressed, such as "next" or "previous", it is often desirable to move the focus to the next or previous field. **To do this, handle it as in this example, by calling FocusNode.nextFocus in the onFieldSubmitted callback of TextFormField.**"

In the code sample in the same docs, they specify both the textInputAction and onSubmitted.

Also, the focus doesn't go back to the initial field. The focus just goes away, and the keyboard goes away too of course.

**Comment by LongCatIsLooong** [comment]
@doc-rj-celltrak that's probably because we were not handling `next` back then: https://github.com/flutter/flutter/pull/63592. I'll update the documentation.

> Also, the focus doesn't go back to the initial field
The focus can move to a different `FocusNode` that's not associated with a text field. For instance the floating action button also has a focus node, so if you have a FAB in the repro the FAB may get focused instead of the first text field.

**Comment by doc-rj-celltrak** [comment]
@LongCatIsLooong Sounds good, thanks. Seems like this was a breaking change for some folks. I guess this documentation also needs updating: https://api.flutter.dev/flutter/services/TextInputAction-class.html

**Comment by TahaTesser** [comment]
@LongCatIsLooong 
Let me know if need help with reproduction, I have a Realme 6 device that is used to test this issue with the secure keyboard on.

**Comment by LongCatIsLooong** [comment]
Lowering the priority since the issue seems to be device-specific. I'll try to get my hands on some test devices tomorrow.

**Comment by StarOfLife** [comment]
The same in HUAWEI nova

**Comment by hardmen** [comment]
My team occurred this problem in device Oppo Neo 3 with Android 10, And we tested HUAWEI with Android 10 also faced the same problem. When you turn system secure keyboard off, the issue will disappear.
We found a way to solve this issue, but not sure there would have any side effect. Nice to hear some feedback. 
```
 final _accountFocus = FocusNode();
 final _passwordFocus = FocusNode();

Column(
      children: [
        Listener(
          onPointerDown: (e) => FocusScope.of(context).requestFocus(_accountFocus),
          child: TextField(
            focusNode: _accountFocus
          ),
        ),
        Listener(
          onPointerDown: (e) => FocusScope.of(context).requestFocus(_passwordFocus),
          child: TextField(
            focusNode: _passwordFocus,
            obscureText: true,
          ),
       ),
    ],
)
```

**Comment by hr1995** [comment]
I also face the same wrong. flutter sdk 2.0.6 stable, is there any good solution for solving the problem?

The problem is normal in iOS device, but appears on Android.

**Comment by lastmeta** [comment]
We, too, are running into this issue, and it seems @hardmen's solution doesn't work in our case, perhaps because we're using the TextFormField instead of TextField....

**Comment by LongCatIsLooong** [comment]
I can't reproduce the issue on Funtouch OS_9 PD1913_A_1.16.5. I have the "Security Input" feature enabled. Sample code used: https://github.com/flutter/flutter/issues/68571#issuecomment-713231927.

**Comment by TahaTesser** [comment]
@LongCatIsLooong 
I can still reproduce with Secure Keyboard turned on a Realme device 

Used the following minimal code sample

<details> 
<summary>complete minimal runnable code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController usernameController = TextEditingController();
  TextEditingController passwordController = TextEditingController();

  @override
  void dispose() {
    usernameController.dispose();
    passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            TextField(
              controller: usernameController,
              textInputAction: TextInputAction.next,
              autofocus: true,
              onSubmitted: (v) {
                FocusScope.of(context).nextFocus();
              },
              decoration: InputDecoration(
                labelText: 'Username',
              ),
            ),
            SizedBox(height: 12.0),
            TextField(
              textInputAction: TextInputAction.done,
              controller: passwordController,
              decoration: InputDecoration(
                labelText: 'Password',
              ),
              obscureText: true,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>


### With `Secure Keyboard` 
https://user-images.githubusercontent.com/48603081/135284489-b8e32070-cdb5-4982-b3d6-dfad05d0d98a.mp4


### Without `Secure Keyboard`
https://user-images.githubusercontent.com/48603081/135284517-07d5bedb-5005-493b-b8c5-6c0414756c48.mp4

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.47

• No issues found
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.135, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-12.0.pre.135 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3074c9e04b (9 hours ago), 2021-09-28 22:08:04 -0700
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)        • EUYTFEUSQSRGDA6D • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows          • windows-x64     • Microsoft Windows [Version 10.0.22000.194]
    • Windows (UWP) (desktop) • winuwp           • windows-uwp-x64 •
    • Chrome (web)            • chrome           • web-javascript  • Google Chrome 94.0.4606.61
    • Edge (web)              • edge             • web-javascript  • Microsoft Edge 93.0.961.47

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

**Comment by LongCatIsLooong** [comment]
I was able to reproduce the issue on a RMX2001. It seems the keyboard isn't showing up because the framework calls `showSoftInput` first and then tells the input method to restart immediately. Switching the order of these 2 calls seems to fix the problem. Also tapping on the target field again should bring up the text field.
