### ISSUE TITLE
Linux Web Framework Test presubmits are flaky.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68579]
This was a user submitted report of a presubmit flake. The specific issues is also hard to determine as tons of steps are purple but clicking into them reveals no issues.

An instance of this failure is:
* https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Framework%20tests/691

![Screen Shot 2020-10-20 at 12 43 19 AM](https://user-images.githubusercontent.com/44085/96556061-629b1d00-126d-11eb-994e-eae7b7c1fda4.png)

@godofredoc: Fixing the flake aside, can we do something about making the flake easier to diagnose?
CC @jason-simmons who actually clicked through all the fields to hypothesize about the actual issue. Sorry I didn't jot down what you said, can you add that context here please.

**Comment by jason-simmons** [comment]
This was the exception log from the swarming task.  Something went wrong during cache setup:

```
8245 2020-10-16 23:49:35.587 E: internal failure: installation directory u'/b/s/w/ir/cache/builder' already exists
Traceback (most recent call last):
  File "/b/s/swarming_bot.1.zip/client/run_isolated.py", line 1088, in map_and_run
    with data.install_named_caches(run_dir):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/b/s/swarming_bot.1.zip/client/run_isolated.py", line 1803, in install_named_caches
    named_cache.install(path, name)
  File "/b/s/swarming_bot.1.zip/client/local_caching.py", line 909, in install
    'installation directory %r already exists' % dst)
NamedCacheError: installation directory u'/b/s/w/ir/cache/builder' already exists
Sending the crash report ... done.
Report URL: https://isolateserver.appspot.com/restricted/ereporter2/errors/5663981520814080
installation directory u'/b/s/w/ir/cache/builder' already exists
```

**Comment by keyonghan** [comment]
There seem to be leaking processes here, and will update from recipe side to make sure clean up happens on all builders.

**Comment by chinmaygarde** [comment]
Triage: This seems to be an issue still:
* https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Framework%20tests/1231

**Comment by godofredoc** [comment]
This is an error mounting caches:

```
NamedCacheError: installation directory u'/b/s/w/ir/cache/builder' already exists
Sending the crash report ... done.
Report URL: https://isolateserver.appspot.com/restricted/ereporter2/errors/5764354789081088
installation directory u'/b/s/w/ir/cache/builder' already exists
````

https://chromium-swarm.appspot.com/task?id=4fb75ff1486bff10&o=true&w=true

@keyonghan can you please ask in the fuchsia infra team chat?

**Comment by godofredoc** [comment]
well actually luci-users chat may be more relevant

**Comment by keyonghan** [comment]
It was advised that the previous task may not have cleaned up correctly. Did a quick check, all the failed builds had a common previous task run, which is `Linux Android Scenarios`.

For example:
`Linux Web Framework Test` [build 1241](https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Framework%20tests/1241), failed on `Linux SDK Drone (2)` [build 104148](https://ci.chromium.org/p/flutter/builders/try/Linux%20SDK%20Drone/104148?), which ran after `Linux Android Scenarios` [build 3544](https://luci-milo.appspot.com/p/flutter/builders/try/Linux%20Android%20Scenarios/3544?) 
![Screen Shot 2020-11-09 at 4 07 56 PM](https://user-images.githubusercontent.com/54558023/98610966-c2517a80-22a5-11eb-98b4-16f3f308d3d7.png)

We original suspect leaking processes cause clean up failures, and have implemented https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipes/engine/scenarios.py;l=150 to kill `chrome, dart, flutter` processes post task execution. But the error still happens.

Seeing that `engine/scenario.py` was implemented https://flutter-review.googlesource.com/c/recipes/+/5520. @blasten Do you have any idea what other leaking processes from `Linux Android Scenarios` may cause this failure?

**Comment by godofredoc** [comment]
Scenarios tests are starting an android emulator to run tests. The dependencies of the emulators are in the cache folder and because the process is still running the folder can not be deleted causing the mount problem in the next task.

Here is the CL to fix the problem:

https://flutter-review.googlesource.com/c/recipes/+/8584

**Comment by godofredoc** [comment]
Java and adb have to be killed too:
https://flutter-review.googlesource.com/c/recipes/+/8621

**Comment by pcsosinski** [comment]
what needs to happen to get this closed?

**Comment by godofredoc** [comment]
This is complete and can be closed.
