### ISSUE TITLE
CircleAvatar onBackgroundImageError throw exception

### ISSUE THREAD

**Issue by jjoelp** [flutter/flutter#68573]
Hello !

I'm using CircleAvatar widget and I want to detect when there is error on background image provided.

This is my code : 

`Widget _circleImage() {

        var radius = (widget.width ?? 48) / 2;
        return CircleAvatar(
            radius: radius,
            backgroundColor: CustomColors.grey,
            child: CircleAvatar(
                radius: radius - 2,
                backgroundColor: CustomColors.white,
                backgroundImage: _imageProvider,
                onBackgroundImageError: (_, __) {
                    setState(() {
                        this._isError = true;
                    });
                },
                child: (this._isError) ? widget.errorWidget : widget.child
            ),
        );
    }`

when I run app,  there is an exception :

> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building CustomCircleAvatar(dirty, state: _CustomCircleAvatarState#022a9):
'package:flutter/src/material/circle_avatar.dart': Failed assertion: line 71 pos 15: 'backgroundImage != null || onBackgroundImageError == null': is not true.

I checked the source code and I see in the second assertion that I can't put backgroundImage and onBackgroundImageError together on CircleImage. However, in view desciption  it says :

> /// The [onBackgroundImageError] parameter must be null if the [backgroundImage]
/// is null.

I'm now confused to find the way to detect the case where backgroundImage has error.

flutter doctor

[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.2 19C57 x86_64, locale fr-MG)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.0)
[✓] Connected device (1 available)
• No issues found!

**Comment by EmreSURK** [comment]
Hi,
I tried your code and it seems working.
I m using: Flutter (Channel stable, 1.22.2, . . . 

Can you switch to a stable channel and give a try? 

I did little changes, I do not think these will affect the code but here are my changes;

```
         CircleAvatar(
            radius: radius,
            backgroundColor: Colors.grey,
            child: CircleAvatar(
                radius: radius - 2,
                backgroundColor: Colors.white,
                backgroundImage: NetworkImage(""),
                onBackgroundImageError: (_, __) {
                  setState(() {
                    //this._isError = true;
                  });
                },
                child: CustomViews
                    .randomViewContainer() //(this._isError) ? widget.errorWidget : widget.child
                ),
          ), 
```

**Comment by pedromassangocode** [comment]
Hi @jjoelp 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Hi @jjoelp 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by jjoelp** [comment]
I tried the code provided by @EmreSURK , it works.
Then I verified my code line by line and see my mistake when getting _imageProvider value.

Sorry I should have sent the entire code !

Thanks !
