### ISSUE TITLE
Ninja invocation on Windows may fail because of failure to remove intermediate build artifacts.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68576]
The specific error is:
```
ninja: error: remove(obj/third_party/angle/src/libANGLE/renderer/gl/libANGLE_base.VertexArrayGL.obj.rsp): Permission denied
```

This was a user submitted reported of a flake in our presubmits. A specific instance of this error is:
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866347945979210480/+/steps/build_host_debug/0/stdout

This was the only reported instance of this error so the failure rate may be lower than other flakes.

I also seem to recall running into such issues on Windows where I ran multiple `ninja` invocations at the same time from multiple terminals. Pretty sure we don't do this on the bots and I am unclear if this is indeed the issue.

**Comment by cbracken** [comment]
I've definitely hit this one in presubmit.

**Comment by zanderso** [comment]
We haven't seen this in a while, so I will close it as stale.
