### ISSUE TITLE
[gen-l10n] Make generated code null safe

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#68598]
Once the `intl` package is migrated to NNBD and the Flutter framework is completely migrated to be null safe, we will likely need to create a new option to specify whether or not to generate null-safe code for `flutter gen-l10n`. This is particularly important for Flutter apps that plan to use NNBD since the `gen-l10n` tool currently isn't null safe.

Proposal: Update gen-l10n to use NNBD, but create an option to generate non-null safe code for backwards compatibility as some users may require more time to carry over.

cc/ @HansMuller @pennzht

**Comment by HansMuller** [comment]
The proposal sounds OK to me.

**Comment by jonahwilliams** [comment]
You do not need to make null safety configurable - It is perfectly acceptable to import null-safe code from un-safe code.

**Comment by edwardaux** [comment]
FWIW, I just got bitten by this today. Running this command:
```
flutter gen-l10n \
  --arb-dir lib/l10n \
  --output-dir=lib/l10n \
  --output-localization-file=translations.dart \
  --output-class=Translations \
  --template-arb-file=messages_en.arb \
  --no-synthetic-package 
```
generates the following code:
```
abstract class Translations {
  ...
  static Translations of(BuildContext context) {
    return Localizations.of<Translations>(context, Translations);
  }
  ...
}
```
The `of` function doesn't compile - the error is:
> A value of type 'Translations?' can't be returned from method 'of' because it has a return type of 'Translations'.

I toyed with the idea of modifying the generated code, but that doesn't seem like something I want to keep having to do. So, just in case anyone else is following along, I ended up adding the following as an additional parameter to the call above get the compiler to stop complaining:
```
--header "// @dart=2.9"
```

**Comment by shihaohong** [comment]
I've already started working on a PR for this. However, it is currently blocked by https://github.com/flutter/flutter/pull/68645. Once that has merged, I'll open my PR.

**Comment by Sominemo** [comment]
```diff
- AppLocalizations.of(context).helloWorld
+ AppLocalizations.of(context)!.helloWorld
```

Adding the `!` all the time for actually sucks, any plans on changing current/introducing a new one non-nullable method?

**Comment by edwardaux** [comment]
Yeah, I agree. If I understand this correctly, it means either every Flutter dev will be littering their codebase with `!` or they’re going to have to create a helper function that checks for null and throws an exception if that’s the case. 

Either way, it isn’t a great public API. I’m not near my computer at the moment, so it is hard for me to dig deeper and offer an actual suggestion, but I definitely feel like there’s opportunity here to make this easier for consumers of this api.

**Comment by shihaohong** [comment]
There's an open issue about this: https://github.com/flutter/flutter/issues/78947
