### ISSUE TITLE
Compatibility with NSuserdafults stored with Objective C

### ISSUE THREAD

**Issue by Sergio719** [flutter/flutter#68592]
Hi,
I am trying to read data from an old version of the iOS app written in objective C.

Data were stored in NSuserdefault using Bool and String format.

I am reading these with Xcode in AppDelegate.m but I am not able to read the same with Flutter using Shared_Preferences plugin.

What am I missing? is there a compatibility issue? In case is there a way to pass data between Xcode and Flutter?

Thanks
Sergio

**Comment by pedromassangocode** [comment]
Hi @Sergio719 
As you can see in the link bellow, the Shared_Preferences plugin only loads data inserted with it. Basically there is this "flutter." string which is used to validate that a key were added using this plugin. So you are not able to load your custom keys with this package.

You can use method_channels to load your custom keys in your app.

https://github.com/flutter/plugins/blob/9560b2ac8eaf23bc5568aafca229de2ef83dac5e/packages/shared_preferences/shared_preferences/ios/Classes/FLTSharedPreferencesPlugin.m#L69-L81

Closing as this is not an issue with Flutter.
Thanks
