### ISSUE TITLE
i have recently updated android studio to 4.1 and installed all flutter plugins but when i run flutter doctor it shows flutter plugins are not installed

### ISSUE THREAD

**Issue by E1itedarklord** [flutter/flutter#68612]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by E1itedarklord** [comment]
C:\Users\Vostro\AndroidStudioProjects\covid_tracker>flutter doctor -v
Error: PowerShell executable not found.
       Either pwsh.exe or PowerShell.exe must be in your PATH.
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 6.1.7601], locale en-US)

    • Flutter version 1.22.2 at C:\src\flutter
    • Framework revision 84f3d28555 (5 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Vostro\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Vostro\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more
      details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\Vostro\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

**Comment by E1itedarklord** [comment]
I also have java 14.0.2 installed and path is set but it shows an earlier version here

**Comment by darshankawar** [comment]
@E1itedarklord 
There's a similar [issue](https://github.com/flutter/flutter/issues/67986) which describes that the flutter plugins don't matter. You still would be able to create and run the project from AS as usual.

https://github.com/flutter/flutter/issues/67986#issuecomment-707881534

https://github.com/flutter/flutter/issues/67986#issuecomment-707511812

Closing this as duplicate
