### ISSUE TITLE
Engine rolls blocked by golden file diffs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#68614]
On the roll here https://github.com/flutter/flutter/pull/68563, there are golden test diffs. Is https://github.com/flutter/engine/pull/21499 related?

@ferhatb @yjbanov 

Marking P0 since this is blocking sound null safety work.

**Comment by ferhatb** [comment]
The golden diffs are expected. There are subpixel level changes due to using svg vs canvas elements.

**Comment by pcsosinski** [comment]
what do we need to do to mark this as closed if the diffs are expected?

**Comment by vsmenon** [comment]
@ferhatb - can someone on your team close this properly?  It's blocking TP2 right now.

**Comment by ferhatb** [comment]
When rolling into Google3, accept scuba change. There is nothing to do on the engine repo.

**Comment by zanderso** [comment]
The engine has rolled into the framework, so I think this can be closed.
