### ISSUE TITLE
video_player can’t play videos from assets directory

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#68610]
Steps to reproduce:
1. Run video_player example app
2. Tap on the assets tab

Expected behavior:
Video should automatically play, but it doesn’t.

Culprit: https://github.com/flutter/plugins/commit/0e27dc2bf87de057af2285737768bdaeb4a87b72

cc @xster

**Comment by hamdikahloun** [comment]
Related issue https://github.com/flutter/flutter/issues/66627

**Comment by blasten** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/66627
