### ISSUE TITLE
Why doesn't Widgets in Flutter have enabled/disabled property/function?

### ISSUE THREAD

**Issue by Jayvd** [flutter/flutter#68621]
Hi, I am wondering why there is no **SIMPLE** enabled/disabled method/property on Widgets like buttons and TextField? 

I have seen many people requested this feature and it has been years since the first requests were made. 

I am honestly wondering what would be the issue behind this? Is there a technically difficulty in implementing this **BASIC** feature?

**Comment by Zazo032** [comment]
`TextField` has an `enabled` param: https://api.flutter.dev/flutter/material/TextField/enabled.html

To disable a button, just set the `onPressed` param to `null`:

```dart
ElevatedButton(
  child: Text('disabled'),
  onPressed: null,
),
```

**Comment by darshankawar** [comment]
@Jayvd 
There's a way to enable and disable as described above. Also this [PR](https://github.com/flutter/flutter/pull/16027) which added the said functionality to the TextField. If this answers your question, then you may go ahead and close this.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
