### ISSUE TITLE
Add golden iOS engine test to check that the Flutter engine actually outputs pixels

### ISSUE THREAD

**Issue by xster** [flutter/flutter#68625]
https://github.com/flutter/flutter/issues/68399 regressed with https://github.com/flutter/engine/pull/21877 despite our tests. 

The hole is that framework golden tests don't use the real iOS engine. Devicelab tests run against a real iOS physical device. Engine goldens are all for platform views which render on a different CALayer and the PR doesn't seem to have broken the rendering pipeline or accessibility etc, just the pixel output. 

Add another simulator test (which our scenario app tests are) and perform a golden check to make sure it checks pixel output.

**Comment by iskakaushik** [comment]
One of the added golden tests should account for presence of platform views.

**Comment by xster** [comment]
Most of our existing tests are already checking for platform views if I understand correctly https://github.com/flutter/engine/blob/master/testing/scenario_app/ios/Scenarios/ScenariosUITests/PlatformViewGoldenTestManager.m

**Comment by iskakaushik** [comment]
Got it, I somehow read this as making the framework pre-submit tests run with the real engine. I wasn't sure if the framework golden tests had platform views in them. But this makes sense.

**Comment by xster** [comment]
Sorry, I meant adding engine repo integration tests. No framework involved.

**Comment by jmagman** [comment]
This was done awhile ago, the golden scenario tests run on every engine commit.
