### ISSUE TITLE
CustomMultiChildLayout docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6863]
Customer feedback:
> CustomMultiChildLayout is still inpenetrable. Perhaps Dartdoc should hint at the use of LayoutId.

**Comment by abarth** [comment]
More confusion about this class:

> I'm puzzled by CustomMultiChildLayout.
> I supply it a MultiChildLayoutDelegate, which has a method performLayout(Size size). I override that, but how do I actually do the layout? I can give my implementation I suppose the list of children, but actually setting width/height/x/y, I don't see how for my chldren StatelessWidgets??

**Comment by sethladd** [comment]
I think this is a dupe of https://github.com/flutter/flutter/issues/5695
