### ISSUE TITLE
No way to find a matching Action without knowing the Intent type at compile time

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#68635]
Hello there,

I am writing some code that maps intents to actions, in much the same way that the `Shortcut` widget works. 

I'd intended to use `Actions.find<T extends Intent>()` to find an appropriate action to invoke, but discovered that the method's type parameter is necessary to find matching actions. Since I'm working from a map of intents of various subtypes, I cannot supply an appropriate type argument. 

`Actions.handler<T extends Intent>()` has similar behavior, despite having an intent in hand.

**Request**: It would be really nice to have a `Actions.find` equivalent method that uses an intent's `runtimeType` to look up actions instead of relying on a type parameter, similar to how `Actions.invoke` works.

For now, I'm having to rely on `Actions.invoke` with `nullOk: false`, using the exception as flow control. It works, but it's ugly.

Thanks!

@gspencergoog

**Comment by shyndman** [comment]
Also, if you agree, happy to put a PR together.

**Comment by gspencergoog** [comment]
I literally just submitted a fix for this, so good timing!

Take a look at https://github.com/flutter/flutter/pull/67359, specifically at [the interface for `find`](https://github.com/flutter/flutter/pull/67359/files#diff-dfd72deb299579a1df3462e65e8a8ca7735c69845f72c15a4be790ac8210e102R537).  It now takes an intent object to get the type at runtime.

**Comment by gspencergoog** [comment]
Please reopen if that's not sufficient.

**Comment by shyndman** [comment]
Dude! This is perfect. Thank you. :)
