### ISSUE TITLE
flutter test passes unused flags to pub

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#68648]
I would like to be able to use `flutter test --reporter expanded`, where `--reporter expanded` is used by pub.

However, flutter test captures this output and throws:

```
Could not find an option named "reporter".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by jonahwilliams** [comment]
This was just added in https://github.com/flutter/flutter/commit/5fedad91730ef2a5bf90cfa5b72cac3b85c7211ahttps://github.com/flutter/flutter/commit/5fedad91730ef2a5bf90cfa5b72cac3b85c7211a
