### ISSUE TITLE
Add the ability to build fat APKs with flutter build

### ISSUE THREAD

**Issue by Pacane** [flutter/flutter#6864]
Right now, the APK built with `flutter build apk` doesn't work on an android emulator.

After talking to @eseidelGoogle on gitter, he asked me to open an issue:

> @Pacane I think having the ability to build fat apks using flutter build is a very reasonable request. Would you mind filing a bug?

Note: The reason was that I was sending the built .apk to my tester, lacking a better workflow, and it didn't work.

```
 ❯ flutter install                                                                                                                                                                                                       [12:49:10]
Installing app.apk to Android SDK built for x86 64...
Installing build/app.apk...                              
Failed to install build/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Oops; flutter has exited unexpectedly: "Exit code 1 from: /opt/android-sdk/platform-tools/adb -s emulator-5554 install -r build/app.apk".
Crash report written to /home/joel/code/dart/catalogue-mouches/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by eseidelGoogle** [comment]
So it is possible to build an apk for a simulator with `flutter build apk --target-arch=x86`, but we don't currently have the ability to bundle more than one arch in a single apk from that command.

**Comment by Pacane** [comment]
@eseidelGoogle Although I just tried it, and received this:

```
 ❯ flutter build apk --target-arch=x86                                                         [13:28:12]
Profile and release builds are only supported on ARM targets.
```
I have just upgraded Flutter too.

**Comment by eseidelGoogle** [comment]
@Pacane that's true, you'd have to pass `--debug --target-arch=x86`. :/   So it's possible that fat APKs don't actually make sense at least x86 vs. arm.  Maybe arm and arm64.

**Comment by Pacane** [comment]
Gotcha, works fine, thanks!

**Comment by eseidelGoogle** [comment]
This might get fixed as part of moving `flutter build` onto gradel.  FYI @mit-mit

**Comment by mit-mit** [comment]
@jakobr-google, also covered?

**Comment by jakobr-google** [comment]
Yep. We are actually building a fat APK right now, we just only include native binaries for ARM... It'll be fixed as part of my work.

I'm leaning towards having split APKs as the default, to keep APK size down, but we can discuss this separately.
