### ISSUE TITLE
Hot reload error using breakpoints in web app

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#68660]
## Steps to Reproduce

1. Create a new Flutter project in IntelliJ
1. Select Chrome device
1. Press the debug button to run the app using the default run/debug configuration
1. set a breakpoint in the _incrementCounter function (line 58)
1. Hot reload the app
1. Observe crash

<details>
  <summary>Logs</summary>

```
Hot Reload Error hotRestart: (-32000) removeBreakpoint: (102) WipError -32602 Invalid parameters #0 Debugger._removeBreakpoint (package:dwds/src/debugging/debugger.dart:353:7)   #1 Debugger.removeBreakpoint (package:dwds/src/debugging/debugger.dart:330:11) #2 ChromeProxyService.disableBreakpoints (package:dwds/src/services/chrome_proxy_service.dart:254:31)   #3 _disableBreakpointsAndResume (package:dwds/src/dwds_vm_client.dart:113:28)   #4 DwdsVmClient.create.  (package:dwds/src/dwds_vm_client.dart:57:13) #5 VmService._routeRequest (package:vm_service/src/vm_service.dart:2182:37) #6 VmService._processRequest (package:vm_service/src/vm_service.dart:2153:25) #7 VmService._processMessageStr (package:vm_service/src/vm_service.dart:2119:9) #8 VmService._processMessage (package:vm_service/src/vm_service.dart:2076:7) #9 _rootRunUnary (dart:async/zone.dart:1198:47) #10 _CustomZone.runUnary (dart:async/zone.dart:1100:19) #11 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7) #12 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11) #13 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7) #14 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11) #15 _MapStream._handleData (dart:async/stream_pipe.dart:224:10) #16 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13) #17 _rootRunUnary (dart:async/zone.dart:1198:47) #18 _CustomZone.runUnary (dart:async/zone.dart:1100:19) #19 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7) #20 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11) #21 _DelayedData.perform (dart:async/stream_impl.dart:611:14) #22 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11) #23 _PendingEvents.schedule.  (dart:async/stream_impl.dart:687:7) #24 _rootRun (dart:async/zone.dart:1182:47) #25 _CustomZone.run (dart:async/zone.dart:1093:19) #26 _CustomZone.runGuarded (dart:async/zone.dart:997:7) #27 _CustomZone.bindCallbackGuarded.  (dart:async/zone.dart:1037:23) #28 _rootRun (dart:async/zone.dart:1190:13) #29 _CustomZone.run (dart:async/zone.dart:1093:19) #30 _CustomZone.runGuarded (dart:async/zone.dart:997:7) #31 _CustomZone.bindCallbackGuarded.  (dart:async/zone.dart:1037:23) #32 _microtaskLoop (dart:async/schedule_microtask.dart:41:21) #33 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5) #34 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13) #35 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-2.0.pre.91, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
[✓] VS Code (version 1.50.0)
[✓] Connected device (2 available)
```

```
flutter --version
Flutter 1.24.0-2.0.pre.91 • channel master • git@github.com:flutter/flutter.git
Framework • revision cb5865d86c (5 hours ago) • 2020-10-20 09:50:31 -0700
Engine • revision ea2aea1c61
Tools • Dart 2.11.0 (build 2.11.0-234.0.dev)
```

</details>

**Comment by johnpryan** [comment]
cc: @jacob314

**Comment by pedromassangocode** [comment]
Hot Reload Error hotRestart: (-32000) removeBreakpoint: (102) WipError -32602 Invalid parameters #0 Debugger._removeBreakpoint (package:dwds/src/debugging/debugger.dart:353:7)   #1 Debugger.removeBreakpoint (package:dwds/src/debugging/debugger.dart:330:11) #2 ChromeProxyService.disableBreakpoints (package:dwds/src/services/chrome_proxy_service.dart:254:31)   #3 _disableBreakpointsAndResume (package:dwds/src/dwds_vm_client.dart:113:28)   #4 DwdsVmClient.create.  (package:dwds/src/dwds_vm_client.dart:57:13) #5 VmService._routeRequest (package:vm_service/src/vm_service.dart:2182:37) #6 VmService._processRequest (package:vm_service/src/vm_service.dart:2153:25) #7 VmService._processMessageStr (package:vm_service/src/vm_service.dart:2119:9) #8 VmService._processMessage (package:vm_service/src/vm_service.dart:2076:7) #9 _rootRunUnary (dart:async/zone.dart:1198:47) #10 _CustomZone.runUnary (dart:async/zone.dart:1100:19) #11 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7) #12 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11) #13 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7) #14 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11) #15 _MapStream._handleData (dart:async/stream_pipe.dart:224:10) #16 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13) #17 _rootRunUnary (dart:async/zone.dart:1198:47) #18 _CustomZone.runUnary (dart:async/zone.dart:1100:19) #19 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7) #20 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11) #21 _DelayedData.perform (dart:async/stream_impl.dart:611:14) #22 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11) #23 _PendingEvents.schedule.  (dart:async/stream_impl.dart:687:7) #24 _rootRun (dart:async/zone.dart:1182:47) #25 _CustomZone.run (dart:async/zone.dart:1093:19) #26 _CustomZone.runGuarded (dart:async/zone.dart:997:7) #27 _CustomZone.bindCallbackGuarded.  (dart:async/zone.dart:1037:23) #28 _rootRun (dart:async/zone.dart:1190:13) #29 _CustomZone.run (dart:async/zone.dart:1093:19) #30 _CustomZone.runGuarded (dart:async/zone.dart:997:7) #31 _CustomZone.bindCallbackGuarded.  (dart:async/zone.dart:1037:23) #32 _microtaskLoop (dart:async/schedule_microtask.dart:41:21) #33 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5) #34 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13) #35 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by grouma** [comment]
Looks like I can't reproduce this with VS Code. I am able to reproduce this with Intellij. I'll dig in more.

**Comment by grouma** [comment]
Ok I found the root cause. It appears when you add a breakpoint in Intellij it actually calls the VM Service protocol `addBreakpointWithScriptUri` twice.

We do have guards in `package:dwds` to check if a provided breakpoint already [exists](https://github.com/dart-lang/webdev/blob/844ec3422d99334979cdaeb025049e40a473bd9a/dwds/lib/src/debugging/debugger.dart#L708) but since the calls happen in quick succession, the first breakpoint isn't established by the time we get the second request. We probably should refactor that logic to better handle this situation.

Regardless, this requires a change to the IntelliJ plugin to properly fix.

**Comment by grouma** [comment]
This should now be resolved at master.
