### ISSUE TITLE
HTTPS is inappropriately enforced in debug builds

### ISSUE THREAD

**Issue by lewcianci** [flutter/flutter#68667]
## Steps to Reproduce

1. Create an app
2. Try to access a HTTP resource
3. Observe that `Bad state: Insecure HTTP is not allowed by platform: http://**url**

**Expected results:**

Plaintext HTTP access in debug builds would work.

**Actual results:**

State error thrown saying that HTTP access is not allowed by the platform.

<details>
  <summary>Logs</summary>

[ +452 ms] E/flutter (26575): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unhandled error Bad
state: Insecure HTTP is not allowed by platform

`
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-AU)
    • Flutter version 1.23.0-18.1.pre at E:\flutter
    • Framework revision 198df796aa (5 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at E:\android
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = E:\android
    • ANDROID_SDK_ROOT = E:\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\lewci\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.38

! Doctor found issues in 1 category.
`

</details>

In the previous Flutter beta, these connections were allowed, thus the use of the phrase 'Insecure HTTP is not allowed by platform' is not appropriate as the platform (Android) was allowing these connections. It appears this PR last month introduced this issue: https://github.com/dart-lang/sdk/commit/ae0fbde71c23c9353b1095d1f480c5e239927abd

Considering the payoff of using HTTPS in a development/debug scenario, compared with the relative difficulty in installing certificates on Android Emulators (i.e: Setting up a lock screen on the Android Emulator), I would think this shouldn't be the default design. It also breaks a lot of people developing for Flutter today, using HTTP in Development.

In Development, I would think that HTTP Plaintext connections are okay. I would expect to see this enforced in a release build, but certainly not in debug.

**Comment by darshankawar** [comment]
@lewcianci 
Insecure HTTP connections are disabled by default on both platforms. See [this](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android) document for more details and on workarounds for both platforms.
If this answers your question, can this issue be closed ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
