### ISSUE TITLE
Can't replay video from assets (iOS)

### ISSUE THREAD

**Issue by VJSmall** [flutter/flutter#68677]
I am trying using the video_player package to try and load, play, and then replay a video from assets. The video loads correctly and plays fine on the first run through. However when I try to replay the video using _controller.seekTo(Duration.zero) and _controller.play() it remains frozen on the last frame of the video and won't replay back.

This occurs only in iOS but not in Android where it behaves as expected. And it only occurs for videos loaded from assets. If I load a video from a url using VideoPlayerController.network it also behaves as expected.

Below is the class I modified from the video_player example.

```
import 'package:video_player/video_player.dart
import 'package:flutter/material.dart';

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/video/MOV_GET_OUT_BED.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Column(
          children: <Widget>[
        Center(
          child: _controller.value.initialized
              ? AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller),
          )
              : Container(),
        ),
            GestureDetector(
              onTap: () async {
                await _controller.seekTo(Duration.zero);
                setState( () {
                  _controller.play();
                } );
              },
              child: Text("Restart video")
            ),
        ]
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```

**Comment by triztian** [comment]
Hey @VJSmall I've created a small repository that is able to play the video in a loop. It think that what was missing from your code was the `_controller.setLooping(true);` before initializing the video controller.

  * https://github.com/triztian/flutter_issue_68677

I used the following [Package: Video Player](https://pub.dev/packages/video_player) and just followed the examples along with your sample code.

**Comment by VJSmall** [comment]
> Hey @VJSmall I've created a small repository that is able to play the video in a loop. It think that what was missing from your code was the `_controller.setLooping(true);` before initializing the video controller.
> 
> * https://github.com/triztian/flutter_issue_68677
> 
> I used the following [Package: Video Player](https://pub.dev/packages/video_player) and just followed the examples along with your sample code.

Thanks for the reply! Sorry I should have been more specific but I don't want the video to loop. I was trying to get the video to be played and then replayed on a button press rather than in a continuous loop. I hope that makes sense.

**Comment by triztian** [comment]
Ok, thank you for the clarification. I've updated the repo and kept the `setLooping(true)` call, the update I did was the following to the button:

```dart
if (_controller.value.isPlaying) {
  _controller.pause();
  return;
}

_controller.seekTo(Duration.zero);
_controller.play();
```

**Comment by darshankawar** [comment]
@VJSmall 
Tried your code sample on iPhone SE simulator (iOS 14) using latest dev version and was able to restart, pause, restart video without any issues.

[Screen Recording 2020-10-21 at 3.04.37 PM.mov.zip](https://github.com/flutter/flutter/files/5414880/Screen.Recording.2020-10-21.at.3.04.37.PM.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-1.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 12bea61c29 (6 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!

```

</details>

Can you provide `flutter doctor -v` and a video of the issue you are facing ?

**Comment by VJSmall** [comment]
Thanks all for your help! After running the code in the repo that @triztian put together it turns out the problem was with the videos I was trying to play. Something about them (maybe the compression or resolution issues) causes them to freeze after they've been played, when I substituted the sample video provided everything worked as expected.
