### ISSUE TITLE
upgraded my flutter and Android studios to 4.1 

### ISSUE THREAD

**Issue by ianperera** [flutter/flutter#68679]
Information:10/20/20, 10:29 PM - Build completed with 2 errors and 0 warnings in 1 s 850 ms
/Users/irperera/Developer/flutterProjects/Dev/mrfungiftshop/android/app/src/main/kotlin/com/utreehost/mr_fun_gift_shop/Application.kt
Error:(3, 12) Kotlin: Unresolved reference: transistorsoft
Error:(12, 9) Kotlin: Unresolved reference: BackgroundFetchPlugin

please help

**Comment by darshankawar** [comment]
@ianperera 
There's too little information you provided in order to help you properly. Please elaborate on the issue you are facing. Provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.

**Comment by ianperera** [comment]
@darshankawar 
/Users/irperera/Developer/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/irperera/Developer/flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/irperera/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • FC29695B-2094-45BB-95AC-B0B30444E7C8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by ianperera** [comment]
@darshankawar 

also getting this

Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.

**Comment by darshankawar** [comment]
@ianperera 
We would need a minimal complete reproducible code sample that shows the issue.

**Comment by Prasad342** [comment]
@ianperera 
I had the same problem flutter sdk was crashed i just reinstalled it problem was solved .
I hope it will help.
Thank You

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
