### ISSUE TITLE
Migrate connectivity_macos to nnbd

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#68670]
Note: connectivity depends on `connectivity_macos`

**Comment by stuartmorgan** [comment]
Is there pubspec metadata that needs to be changed for the migration? The entirety of the Dart code for `connectivity_macos` is:
```
// Analyze will fail if there is no main.dart file. This file should
// be removed once an example app has been added to connectivity_macos.
// https://github.com/flutter/flutter/issues/51007
```

**Comment by cyanglaz** [comment]
You are right, doesn't seem like any migration is required for this plugin. I'll close it. 
cc @blasten

**Comment by blasten** [comment]
@stuartmorgan I was wondering about this as well for `url_launcher`.  We just need to bump the Dart SDK in `pubspec.yaml`.
 Although this might not be required if the Dart file is never imported.
