### ISSUE TITLE
Android Studio 4.1 on update path on Mac have loss the path

### ISSUE THREAD

**Issue by Tavorn** [flutter/flutter#68685]
At first I only have:
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

After I updated using flutter config --android-studio-dir='/Users/myhome/Library/Android/sdk'

then I get this message:

Unable to find any JVMs matching version "1.8".
No Java runtime present, try --request to install.
Unable to find any JVMs matching version "1.8".
No Java runtime present, try --request to install.
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-TH)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Could not determine java version
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/myhome/Library/Android/sdk/Contents

After used flutter 'config --android-studio-dir=' to fixed, I only get the message about:
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

I had uninstall dart and flutter in plugin and reinstall still can't work.
How can I update this?

**Comment by darshankawar** [comment]
@Tavorn 
There's a similar [issue](https://github.com/flutter/flutter/issues/67986) and related comments about plugins not installed. Basically, even if you see that plugins are not installed, they are just a message and you can use them to create new project as usual. Also, you don't have to do anything from your side. Wait for the fix.

https://github.com/flutter/flutter/issues/67986#issuecomment-707881534
https://github.com/flutter/flutter/issues/67986#issuecomment-707511812
https://github.com/flutter/flutter/issues/68084#issuecomment-708335541

Closing this as duplicate.
