### ISSUE TITLE
Flutter: Is the official documentation for align wrong?

### ISSUE THREAD

**Issue by LuodiJackShen** [flutter/flutter#68680]
When I was reading through Align's documentation I found the following explanation.

[![enter image description here][1]][1]

The link is [https://api.flutter.dev/flutter/widgets/Align-class.html#widgets.Align.2][2]

The 0.2 is the xAlign and the 0.6 is the YAlign, follow the formulas in the official documentation and finally calculate a point `(36.0,48.0)`. When xAlign is less than zero or yAlign is less than zero, the calculation according to this formula is always positive. And the formula for calculating the offset of `FlutterLogo` and `Container` in the source code is as follows(`alignment.dart` `lines:290`):

    Offset other = size - child!.size as Offset;
    final double centerX = other.dx / 2.0;
    final double centerY = other.dy / 2.0;
    childParentData.offset = Offset(centerX + xAlign * centerX, centerY + yAlign * centerY);

The result according to the formula in the source code does not seem to have any relation to `(36,48)`. Did I misunderstand or did the document say something wrong?

  [1]: https://i.stack.imgur.com/87CZX.png
  [2]: https://api.flutter.dev/flutter/widgets/Align-class.html#widgets.Align.2

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.
