### ISSUE TITLE
When `flutter devices` doesn't see any devices we could offer users help

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6869]
We could point them to an FAQ entry via URL, etc.  We just had a user confused in gitter.im/flutter/flutter about how to get `flutter devices` to see his Android device.  Similar confusion can happen with iOS.

**Comment by sethladd** [comment]
Here's what it says now:

```
~ $ flutter devices
No devices detected.

If you expected your device to be detected, please run "flutter doctor" to diagnose
potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.
```

Maybe we want to detect if you are on a Mac, and if you have the Simulator installed, suggest how to run the simulator?

We link to the Setup docs. Do we think that is sufficient? What was the original problem that prompted this issue?
