### ISSUE TITLE
Stock viewer page should not slide in, it should fade in

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#687]
Right now, MaterialApp hard-codes all routes to use MaterialPageRoute. We should allow different routes to use different PageRoute subclasses.

**Comment by sethladd** [comment]
Can we re-title this issue to make it clearer what the bug with the framework is? (I assume this issue is really about something we'd like to do in the framework... ?)

**Comment by abarth** [comment]
We fixed this in several different ways.  We still might want to have a bug about making it easier to customize the transition, but that's separate from the request here.
