### ISSUE TITLE
[web]: Material icons are not rendering in release mode

### ISSUE THREAD

**Issue by ErnestoAbram** [flutter/flutter#68704]
Describe your issue and include the command you're running, flutter_web version, browser version

**Comment by ErnestoSevilla** [comment]
flutter doctor 

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /google/flutter/flutter
    • Framework revision 198df796aa (hace 6 días), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ernesto/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/93/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/93/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

this is my .yaml : 

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cloud_firestore: ^0.14.1+3

  provider: ^4.3.2

  intl: ^0.16.1

  fluttertoast: ^7.1.1

  crypto: ^2.1.5
  file_picker: ^2.0.8
  sprintf: ^5.0.0
  smart_dialogs: ^2.1.2
  font_awesome_flutter: ^8.10.0
  qr_flutter: ^3.2.0
  url_launcher: ^5.7.5

  csv: ^4.0.3
  

  email_validator: '^1.0.6'

  table_calendar: ^2.3.0
  flutter_email_sender: ^3.0.1

  video_player: ^0.11.1+2

  flutter_linkify: ^3.1.3
  clipboard: ^0.1.2+8

  google_fonts: ^1.1.1  


but in debug mode work ok.
Just a basic program work ok. 
It does not work in chrome or in other browsers.
I change to another system, (windows) and don't work.

**Comment by darshankawar** [comment]
@ErnestoSevilla 
When you say `material icon doesn't work`, what does that mean exactly ? Is it not rendering at all in release mode, but works in debug mode ?
Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by ErnestoSevilla** [comment]
> @ErnestoSevilla
> When you say `material icon doesn't work`, what does that mean exactly ? Is it not rendering at all in release mode, but works in debug mode ?
just it, the icon is not rendering or rendering wrong, but it works in debug mode.
> Can you provide a minimal complete reproducible code sample that shows the issue ?
I try, but when i made a new project and try to reproduced it, it work correctly. My project is big and I don't know the point that start to fault this.

But in version 1.20 works ok, in release or in debug mode.

Perhaps it was Tree shaking optimsing, but I don't know how to disable it in web.
Thanks.
> Thanks.

**Comment by sidrao2006** [comment]
Hey @ErnestoSevilla to disable tree shaking, pass the `--no-tree-shake-icons` argument to `flutter build web`

**Comment by ErnestoSevilla** [comment]
Thanks, @sidrao2006  I compile with --no-tree-shake-icons and get the same problem. :(

![When I compile release mode](https://user-images.githubusercontent.com/3041635/96769123-fccea280-13de-11eb-8669-17b7d5d0caa8.jpeg)

![When I compile debug mode](https://user-images.githubusercontent.com/3041635/96769134-00fac000-13df-11eb-8857-2b08e778df2e.jpeg)

**Comment by darshankawar** [comment]
@ErnestoSevilla 
Tried a sample Icon widget in release mode and was able to see the icon rendering properly.

<img width="723" alt="Screenshot 2020-10-22 at 12 22 36 PM" src="https://user-images.githubusercontent.com/67046386/96835574-668f9080-1461-11eb-8054-26fafbc78c17.png">


```
return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
               Icon(
                   Icons.ac_unit_sharp
                   ),
              Icon(
                  Icons.expand
              )
                ],
              )
          ),
        )
      );
```

Make sure you are not using an 3rd party icons. Also provide the code sample that we can try to see if we can replicate it.

**Comment by ErnestoSevilla** [comment]
I try, and it works ok.
after i tried with my pubspec.yaml and work ok in relase mode. In the pubspec.yaml there is  font_awesome_flutter: ^8.10.0, but it work in your try.

**Comment by ErnestoSevilla** [comment]
I have put the code that you sent me instead of mine in main.dart (in my project) and the icons have not been shown either.

**Comment by darshankawar** [comment]
@ErnestoSevilla 
Tried the `font_awesome_flutter` plugin on latest Beta and was able to see the icon rendering properly.  

<img width="214" alt="Screenshot 2020-10-23 at 11 47 33 AM" src="https://user-images.githubusercontent.com/67046386/96963716-c13ef000-1526-11eb-9fda-c6abc3de1c75.png">

Sample code tried:

```
return Scaffold(
      body: Center(
        child: IconButton(
          // Use the FaIcon Widget + FontAwesomeIcons class for the IconData
            icon: FaIcon(FontAwesomeIcons.gamepad),
            onPressed: () { print("Pressed"); }
        )
      )
    );
```

Used below commands to run in release mode which works well:

`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
`flutter run -d chrome --release`

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (7 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!

```

</details>

**Comment by ErnestoSevilla** [comment]
Hello, I try your test, but work ok.

![testwithAwesomeSikaEnable](https://user-images.githubusercontent.com/3041635/97078926-2b6f9780-15f0-11eb-971b-196cf32156f0.jpeg)
![testwithsikadisable](https://user-images.githubusercontent.com/3041635/97078927-2dd1f180-15f0-11eb-95d3-cdb224ca3418.jpeg)

**Comment by ErnestoSevilla** [comment]
I try with this, but with the hole program.
![bothIconsDebugMode](https://user-images.githubusercontent.com/3041635/97078973-99b45a00-15f0-11eb-800a-2cf6c9b64999.jpeg)
![bothIconswhithSikaEnable](https://user-images.githubusercontent.com/3041635/97079040-18a99280-15f1-11eb-83e1-1d3a7e6ba89a.jpeg)
![bothIconswithSikaDisable](https://user-images.githubusercontent.com/3041635/97079077-58707a00-15f1-11eb-9623-cacf23b03e9f.jpeg)



  return MaterialApp(
        locale: Locale('es', 'ES'),
        title: 'EQA Plataforma ',
        localizationsDelegates: getLocalizationsDelegates(),
        supportedLocales:
            getSupportedLocales(), // localizationsDelegates: getLocalizationsDelegates(),

        home: Scaffold(
            body: Column(children: [
          IconButton(
            icon: Icon(Icons.close),
            onPressed: () => print("pressed"),
          ),
          IconButton(
              // Use the FaIcon Widget + FontAwesomeIcons class for the IconData
              icon: FaIcon(FontAwesomeIcons.gamepad),
              onPressed: () {
                print("Pressed");
              }),

        ])))

**Comment by ErnestoSevilla** [comment]
Hello, i made this test if it can help you, the left is in debug mode, and the rigth is in release.
it is like the list of icons was wrong in --release


![iconsTest](https://user-images.githubusercontent.com/3041635/97091030-03585680-1639-11eb-893a-ff570d74bcb1.jpeg)

**Comment by darshankawar** [comment]
@ErnestoSevilla 
I am unable to replicate the issue using your code sample. What command are you running to build on web ?

**Comment by ErnestoSevilla** [comment]
Flutter run -- release for exanple. Other Commander IS the sale, except debut.
Note that un firefox os the sale.

**Comment by ErnestoSevilla** [comment]
Firefox os the same

**Comment by darshankawar** [comment]
Tried again on latest master on chrome and on Firefox, and see icons rendering properly.

<img width="903" alt="Screenshot 2020-10-26 at 3 47 04 PM" src="https://user-images.githubusercontent.com/67046386/97160665-b1334480-17a2-11eb-9637-ac184f4a050b.png">

Not sure what's going on at your end. Try to create a fresh project and run the same code to see if you still get the error or not ? Also provide any more details you think that could help to replicate the issue.
Thanks.

**Comment by ErnestoSevilla** [comment]
there is anthoer therad about this, https://github.com/flutter/flutter/issues/64389#issuecomment-716414939

**Comment by darshankawar** [comment]
@ErnestoSevilla That doesn't help much. We would need concrete steps so that we can try to replicate at our end to see what's causing the issue.

**Comment by ErnestoSevilla** [comment]
Darsahnwakwar, i try to help how much i can. But in small project the problem do not shown. I say you all I know.

**Comment by iapicca** [comment]
@ErnestoSevilla does this issue occur upgrading to master?

**Comment by ErnestoSevilla** [comment]
Not a week ago, but today I will try again.

**Comment by ErnestoSevilla** [comment]
in other computer whith windows, new instalation, master channel
calling the test in main, but all the aplication behind.

 flutter doctor -v
[√] Flutter (Channel master, 1.23.0-19.0.pre.13, on Microsoft Windows [VersiÃ³n 10.0.17763.1158], locale es-ES)
    • Flutter version 1.23.0-19.0.pre.13 at C:\Users\ernesto\flutter
    • Framework revision 085f1daa43 (13 days ago), 2020-10-13 13:42:02 -0700
    • Engine revision 6cdb2f69a4
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\ernesto\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 2 categories.


![IMG_20201026_230900](https://user-images.githubusercontent.com/3041635/97234322-d9da2f00-17e0-11eb-81cf-bde48dd7ec83.jpg)

**Comment by darshankawar** [comment]
@ErnestoSevilla 
The latest master version is 1.24. Please upgrade to this version and try again to see if you see same behavior.

**Comment by ErnestoSevilla** [comment]
the same :(

[√] Flutter (Channel master, 1.24.0-4.0.pre.98, on Microsoft Windows [VersiÃ³n 10.0.17763.1158], locale es-ES)
    • Flutter version 1.24.0-4.0.pre.98 at C:\Users\ernesto\flutter
    • Framework revision 36f9af3f55 (56 minutes ago), 2020-10-27 11:30:24 -0700
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\ernesto\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
I am unable to replicate this issue on browsers I tried on both master and beta channels, but OP has been seeing this issue consistently. Keeping this issue open for further analysis.

**Comment by ErnestoSevilla** [comment]
Ok. if I get more information or in future release it will be reparied, I say you.
anyway i will try to made more test.

**Comment by ferhatb** [comment]
@ErnestoSevilla are you seeing issue on firefox only ? have you tried chrome. I'm working on a clipping issue in firefox and checking if this may be same reason for failure.

**Comment by ErnestoSevilla** [comment]
I have done the test in chrome, but also in firefox, both in windows and in linux.

**Comment by ErnestoSevilla** [comment]
this is with firefox
![iconosfirefox](https://user-images.githubusercontent.com/3041635/97568737-5c344000-19e7-11eb-94fa-ac52d3d5a164.jpg)

**Comment by ferhatb** [comment]
@ErnestoSevilla , can you please save your DOM element tree (Chrome Inspect , elements tab, then you can just copy/paste the html to share).

**Comment by ErnestoSevilla** [comment]
Of course, 
[VersionRenderOk
[releasVersionBadRender.txt](https://github.com/flutter/flutter/files/5467978/releasVersionBadRender.txt)
](https://github.com/flutter/flutter/files/5467974/debugVersionWorkOk.txt)

**Comment by ErnestoSevilla** [comment]
Of course, I send you two files, one with the version debug that render Ok, and other with the version release that don't render the icons.

[releasVersionBadRender.txt](https://github.com/flutter/flutter/files/5467988/releasVersionBadRender.txt)

**Comment by ErnestoSevilla** [comment]
this is in debug mode.
[debugVersionRenderOk.txt](https://github.com/flutter/flutter/files/5467992/debugVersionRenderOk.txt)

**Comment by riuson** [comment]
One application. Windows Desktop. Latest flutter version. Building with command
```
flutter build windows
```
Left - runned from building directory.
Right - runned from another **drive**, not where app was build.

![Screenshot 2020-11-02 002013](https://user-images.githubusercontent.com/415202/97812156-405bc300-1ca1-11eb-8fd9-c639811f0cf0.png)

**Comment by ferhatb** [comment]
I see <p style="font-size: 24px; font-family: &quot;packages/font_awesome_flutter/FontAwesomeSolid&quot;, Arial, sans-serif; color: rgba(0, 0, 0, 0.867); position: absolute; white-space: pre-wrap; overflow-wrap: break-word; overflow: hidden; height: 28px; width: 24px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 8, 48);"></p>

@hterkelsen : any idea why font family name has packages/font_awesome_flutter/ in it ?

**Comment by ErnestoSevilla** [comment]
what about this problem? I do not find any solution yet. If you need more information, please, ask me.

**Comment by Nv7-GitHub** [comment]
I am having a similar issue with material icons. I put some info on my issue at https://github.com/flutter/flutter/issues/71890. That issue seemed similar to this one, so that one was closed. Any ideas on how to fix this?

**Comment by ErnestoAbram** [comment]
Not by the moment. :(

**Comment by ferhatb** [comment]
@ErnestoAbram , one more ask. Can you specify where you installed flutter (path) , where your app is located (path). And please attach your pubspec.yaml. Also which locale do you have on your machine. I'm suspecting this is related to asset paths/tooling since nobody is able to repro.

**Comment by i-supchat** [comment]
Same issue. @ErnestoAbram were you able to fix that?

**Comment by dkim-kelly** [comment]
I ran into same issue when building it on VS Code, but when I built it with the command in powershell, 
`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
it started rendering correct icons.

**Comment by ErnestoAbram** [comment]
I made obsolete the version and I am starting a new aplication by scratch. If you need more information for other users, I would send you, but if I am the only user with that problem, maybe it is better to close the ticket.
Thanks, Ernesto.

**Comment by filiponegrao** [comment]
I am having this same issue! Works perfectly running on my machine, in develop mode. 
When I deploy (using --release flag) to server, there is no icon that loads.

Any solution?

**Comment by abnerh69** [comment]
Same problem here.

Downloaded MaterialIcons-Regular.ttf and saved in web/assets/fonts.

Created FontManifest.json in web/assets with:

[
  {
    "family": "SegoeUI",
    "fonts": [
      {
        "asset": "assets/fonts/SegoeUI.ttf"
      }
    ]
  },
  {
    "family": "SegoeUIBold",
    "fonts": [
      {
        "asset": "assets/fonts/SegoeUIBold.ttf"
      }
    ]
  },
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "assets/fonts/MaterialIcons-Regular.ttf"
      }
    ]
  },
  {
    "family": "GoogleSans",
    "fonts": [
      {
        "asset": "assets/fonts/GoogleSans-Regular.ttf"
      }
    ]
  },
  {
    "family": "GalleryIcons",
    "fonts": [
      {
        "asset": "assets/fonts/GalleryIcons.ttf"
      }
    ]
  }
]
![Screen Shot 2021-05-06 at 12 37 48 PM](https://user-images.githubusercontent.com/6172846/117341544-e0b8bd00-ae67-11eb-83ac-bb6d4381be84.png)

**Comment by joachimschmidt** [comment]
[ #32540 (comment)](https://github.com/flutter/flutter/issues/32540#issuecomment-707900491)
As this nice gentleman pointed out, In my case I was using workaround which no longer works, and additionaly breaks new implementation of icons on web. 
I had to delete `MaterialIcons-Regular.ttf` and `FontManifest.json` and Material Icons are working perfectly now!
Wasted many hours trying to fix this so I hope this also will work for you

**Comment by thachnb85** [comment]
I have similar issue, on the debug mode icons are shown OK:
![image](https://user-images.githubusercontent.com/21049491/133190864-57bbbff7-79ae-41f0-ad4e-b0d089e9e1fa.png)

But when I deployed the flutter web app to my backend (loaded in an i-frame), it shows wrong icons:
![image](https://user-images.githubusercontent.com/21049491/133190649-2531daaf-5517-4278-9e32-ea61f6aaeb14.png)

Any idea?

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.3.1 20E241 darwin-x64, locale en-CA)
    • Flutter version 2.5.0 at /Users/nbt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nbt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
```

**Comment by asifimtiazahmed** [comment]
same issue here

**Comment by FMorschel** [comment]
Same issue here

```cmd
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.19042.1288], locale fr-FR)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\felip\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\felip\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.0)
    • VS Code at C:\Users\felip\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • SM G780F (mobile) • 192.168.200.26:45025 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

**Comment by guidezpl** [comment]
Without a reproducible example, this is difficult to fix. If anyone encountering this issue could provide their project and commands, that would be helpful
