### ISSUE TITLE
Problem with new Hybrid platform view rendering on certain devices

### ISSUE THREAD

**Issue by kemphack** [flutter/flutter#68706]
## Steps to Reproduce

Run hybrid version of platform view on API 19 device in this case Samsung SM-T231.

**Expected results:** Not crushing platformview

**Actual results:** Platformview cant call render part connected with android.media.ImageReader.nativeImageSetup;

<details>
  <summary>Logs</summary>

E/flutter (19832): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
E/flutter (19832):      at android.media.ImageReader.nativeImageSetup(Native Method)
E/flutter (19832):      at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:292)
E/flutter (19832):      at android.media.ImageReader.acquireNextImage(ImageReader.java:338)
E/flutter (19832):      at android.media.ImageReader.acquireLatestImage(ImageReader.java:242)
E/flutter (19832):      at io.flutter.embedding.android.FlutterImageView.acquireLatestImage(FlutterImageView.java:203)
E/flutter (19832):      at io.flutter.embedding.android.FlutterView.acquireLatestImageViewFrame(FlutterView.java:1101)
E/flutter (19832):      at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:803)
E/flutter (19832):      at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:856)
E/flutter (19832):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19832):      at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (19832):      at android.os.Looper.loop(Looper.java:131)
E/flutter (19832):      at android.app.ActivityThread.main(ActivityThread.java:5602)
E/flutter (19832):      at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (19832):      at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (19832):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/flutter (19832):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/flutter (19832):      at dalvik.system.NativeStart.main(Native Method)
E/flutter (19832):
F/flutter (19832): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1241)] Check failed: CheckException(env).
F/libc    (19832): Fatal signal 6 (SIGABRT) at 0x00004d78 (code=-6), thread 19832 (exmapkitexample)

[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale ru-RU)
    • Flutter version 1.22.2 at C:\src\flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\username\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • SM T231 (mobile) • 3100425c93096200 • android-arm • Android 4.4.2 (API 19)

• No issues found!

</details>

**Comment by darshankawar** [comment]
@kemphack 
Can you elaborate when you say `run hybrid version of platform view`?  Can you point to the document / code sample that you are trying to run ? Also can you provide a reproducible code sample that we can copy paste and run in IDE that will show the issue ?

**Comment by kemphack** [comment]
https://github.com/kemphack/yandex_mapkit/commit/13b488ff116844322cbacbaea52df95150ce08a7
all in example app works properly until params.onPlatformViewCreated is called

**Comment by darshankawar** [comment]
@kemphack 
Although I am able to replicate the issue on api 19 emulator, I think it could be related to [this](https://github.com/flutter/flutter/issues/62496) issue, ie, platformviews are not visible on api 21 and below.  Would you be okay to close this as duplicate and follow-up in related issue ?
Thanks.
