### ISSUE TITLE
Cherry-pick flutter-engine b2ace0c into stable

### ISSUE THREAD

**Issue by danilofuchs** [flutter/flutter#68717]
We currently have users complaining the app does not load as they have files on their clipboard but we only read text and don't use file read permissions.

This was fixed in:
https://github.com/flutter/engine/pull/21290

Could it perhaps be cherry-picked into stable (1.22.x)?

**Comment by pedromassangocode** [comment]
Cc @goderbauer @christopherfujino

**Comment by christopherfujino** [comment]
@danilofuchs thanks for suggesting this. Per https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#process-flow, I am going to close this issue and instead apply the cherry pick request label to https://github.com/flutter/flutter/issues/66108, please follow their for updates.
