### ISSUE TITLE
Error With flutter doctor --android-licenses

### ISSUE THREAD

**Issue by EvanThomasKaduthanam** [flutter/flutter#68711]
I Was Having Flutter In Another Device(An Old One), And When I Tried To Download And Set It Up, Its Showing This. I Didn't Get Any Useful Info In The Internet. Plz Help Me. If You Want Anymore Info Please Ask.
![image](https://user-images.githubusercontent.com/73238368/96730642-0a325f80-13d4-11eb-8737-e31d8c05c631.png)
![image](https://user-images.githubusercontent.com/73238368/96731129-8e84e280-13d4-11eb-9697-fd25db4a2843.png)

**Comment by sidrao2006** [comment]
Hey @EvanThomasKaduthanam , could you please post your java jdk and jre version (`java --version`)

**Comment by EvanThomasKaduthanam** [comment]
![image](https://user-images.githubusercontent.com/73238368/96747195-9a2cd500-13e5-11eb-8300-352845d245e8.png)

**Comment by sidrao2006** [comment]
Hey @EvanThomasKaduthanam , flutter fails to verify android licences with newer java versions.
It works best with java jdk v8.
Thanks

**Comment by EvanThomasKaduthanam** [comment]
How Do I Change It?

**Comment by sidrao2006** [comment]
@EvanThomasKaduthanam try reinstalling it

**Comment by EvanThomasKaduthanam** [comment]
K, Thank You So Much.

**Comment by EvanThomasKaduthanam** [comment]
![image](https://user-images.githubusercontent.com/73238368/96750758-f72a8a00-13e9-11eb-9bf7-675ebc744716.png)
This One Right?

**Comment by sidrao2006** [comment]
@EvanThomasKaduthanam yes

**Comment by darshankawar** [comment]
@EvanThomasKaduthanam 
There's similar [issue](https://github.com/flutter/flutter/issues/51670) which has various solutions to try. Check those and see if anyone fixes your issue.
Also check [this](https://github.com/flutter/flutter/issues/51670#issuecomment-592943797) solution and see if it works for you.
Thanks.

**Comment by EvanThomasKaduthanam** [comment]
Thank You So Much.

**Comment by darshankawar** [comment]
@EvanThomasKaduthanam 
Did above link resolved your issue ? Can this be closed ?

**Comment by EvanThomasKaduthanam** [comment]
Is iy important to be closed

**Comment by EvanThomasKaduthanam** [comment]
I am new here

**Comment by darshankawar** [comment]
@EvanThomasKaduthanam Can you confirm if your issue is resolved ? Can this issue be closed ?

**Comment by EvanThomasKaduthanam** [comment]
Its Working, Thank You So Much.
