### ISSUE TITLE
app crashed from using listview on flexible

### ISSUE THREAD

**Issue by Suryapratap-R** [flutter/flutter#68724]
## Steps to Reproduce

# Sorry for the poor Explanation, I tried my best. this is my first time reporting an issue

1. Run `flutter create bug`.
2.
3. ... run app > there is the only page, scroll listview(horizontal) to right-> scroll a few times app crashes
I have tried flutter clean, upgrade, doctor, removing the app from the emulator, restarting vs code and emulator

please find attached pubspec.yaml and main.dart in txt file as cannot attach here.
## this is just UI
[main.txt](https://github.com/flutter/flutter/files/5417581/main.txt)
[pubspec.txt](https://github.com/flutter/flutter/files/5417582/pubspec.txt)

**Expected results:** Nothing, just scroll normally
**Actual results:** 
app crashed
`event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in demo...}
event sent after app closed: {id: 0, progressId: null, finished: true}
[38;5;248mLaunching lib\main.dart on Android SDK built for x86 in debug mode...[39;49m
 lib\main.dart
√ Built build\app\outputs\flutter-apk\app-debug.apk.
D/EGL_emulation(26838): eglMakeCurrent: 0xdb4020c0: ver 2 0 (tinfo 0xdb4faff0)
I/OpenGLRenderer(26838): Davey! duration=758ms; Flags=1, IntendedVsync=86998025815730, Vsync=86998025815730, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=86998029506900, AnimationStart=86998029587600, PerformTraversalsStart=86998029646500, DrawStart=86998713999300, SyncQueued=86998715053000, SyncStart=86998720538300, IssueDrawCommandsStart=86998721302600, SwapBuffers=86998740674900, FrameCompleted=86998789992300, DequeueBufferDuration=13441000, QueueBufferDuration=445000,
I/Choreographer(26838): Skipped 45 frames!  The application may be doing too much work on its main thread.
Connecting to VM Service at ws://127.0.0.1:63330/6w3BGqornhU=/ws
D/EGL_emulation(26838): eglMakeCurrent: 0xf037ed40: ver 2 0 (tinfo 0xe50e1120)
W/om.example.dem(26838): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/om.example.dem(26838): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/om.example.dem(26838): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/om.example.dem(26838): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
F/libc    (26838): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 26865 (1.raster), pid 26838 (om.example.demo)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-10-21 22:04:05+0530
pid: 26838, tid: 26865, name: 1.raster  >>> com.example.demo <<<
uid: 10135
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    eax c557c501  ebx c4eb75f0  ecx d99589b8  edx 00000ab1
    edi c557c5c0  esi 00000000
    ebp c557c5c0  esp c557c570  eip 00000008
backtrace:
      #00 pc 00000008  <unknown>
      #01 pc 000fcb4f  [anon:libc_malloc]
Lost connection to device.
Exited (sigterm)
`

<details>
  <summary>Logs</summary>

```
```

```
![image](https://user-images.githubusercontent.com/45616777/96751044-57b9c700-13ea-11eb-9d2d-1a3a0b747750.png)

```

![image](https://user-images.githubusercontent.com/45616777/96750958-378a0800-13ea-11eb-8f7b-92f23cc06ea9.png)

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Suryapratap-R 
I'm not able to reproduce the issue on latest `stable` channel. 
Please run your code with `flutter run -v` and once the app crash provide the output here.

Thank you

**Comment by Suryapratap-R** [comment]
hi @pedromassangocode 
I am also unable to replicate the bug, closing the issue.

thanks
