### ISSUE TITLE
libimobiledevice is wonky - crashes and phantom devices

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#6872]
## Steps to Reproduce

Not sure how to reproduce - will investigate more later this evening.

## Logs

- A component of libimobiledevice crashes, a lot.
- A devices which is not connected to my machine shows up. Has been showing up since I started using `flutter`. I thought it was because wifi sync was enabled, so thought nothing of it until something made me go 'hrmm' then check and wifi sync is disabled, yet `flutter devices` sees it and always has seen in.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/orion/dev-build/flutter
    • Framework revision 15ea399fdd (50 minutes ago),
    • Engine revision a3a13f4a94
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/orion/Library/Android/sdk
    • Platform android-22, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Community Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed
```

**Comment by eseidelGoogle** [comment]
I presume you installed via `brew install --HEAD libimobiledevice`?

**Comment by mikemimik** [comment]
Yes. `flutter doctor` mentioned that the install needed to be from `--HEAD`.

**Comment by cbracken** [comment]
@mikemimik Is this still an issue? If so, can you provide logs?

**Comment by cbracken** [comment]
@mikemimik are you still running into this?

**Comment by mikemimik** [comment]
@cbracken I will attempt to test this out this weekend. My sincerest apologies for getting back to you so late!

**Comment by cbracken** [comment]
No problem! Thanks for checking into this. I landed a bunch of fixes in March around libimobiledevice. Running `flutter doctor` with an iOS device plugged in should provide instructions that ensure everything's up-to-date.

**Comment by Hixie** [comment]
@mikemimik We're going to close this since we haven't heard from you on this bug in a while, but please don't hesitate to reopen if this is still a problem! Thanks!
