### ISSUE TITLE
`tester` test failures when enabling nnbd by default

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#68730]
See the failures here https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865884803271263360/+/steps/flutter_test_tool_tests/0/stdout.

I cannot figure out exactly what is happening here or even which test is attempting to be compiled - but it looks to me like possibly the test framework is not properly passing the language version info for the root package through to the compiler, so the tests are being opted in when they should not be.

Part of https://github.com/dart-lang/sdk/issues/43872

**Comment by jonahwilliams** [comment]
I think that the best course of action here is probably to swap these to dart test on CI, and then I can investigate the correct fixes for tester when I have more time
