### ISSUE TITLE
I am unable to load assets using rootBundle.loadString() for Flutter Tests, even following previous issues

### ISSUE THREAD

**Issue by anthonyorona** [flutter/flutter#68745]
Flutter 1.22.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (3 weeks ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

I have a line in my code that loads json from file:
     return await rootBundle.loadString('assets/settings.json');

This is the valid path for the directory. I am running the tests from the root directory of the project using android studio
     
    /<path>/flutter --no-color test --machine --start-paused test/test_settings.dart

My test class is structured as follows:

    import 'package:flutter_test/flutter_test.dart';
    import 'package:app/models/setting.dart';

    void main() {
        TestWidgetsFlutterBinding.ensureInitialized();

      SettingsClass settings = new SettingsClass();

      group('Settings Tests', ()
      {
        testWidgets('initalization is successful', (WidgetTester tester) async {
          await tester.runAsync(() async {
            await providerUnderTest.initializeConfigSettings();
          });
        });
      });
    }

This test never completes. It just hangs. I have included TestWidgetsFlutterBinding.ensureInitialized(); as suggested: https://github.com/FirebaseExtended/flutterfire/pull/11

And, I am following the pattern w.r.t how I should use testWidgets. When my tests get to the line in the class under test where
          return await rootBundle.loadString('assets/settings.json');
is called, the tests just hang. Am I doing something wrong here?

**Comment by darshankawar** [comment]
@anthonyorona 
Per the official [documentation](https://api.flutter.dev/flutter/services/rootBundle.html), it is recommended to use AssetBundle instead of rootBundle. Give it a try using this method and see if it works.

**Comment by anthonyorona** [comment]
@darshankawar Thank you, I was able to run tests after making this change. It would be nice if I did not have to load my assets in the context of an inherited widget as I can't then bury the code in a util class and have it called from a provider instead.
