### ISSUE TITLE
Can't generate docs on Windows

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#68748]
After installing the Windows version of the SDK, I would like to run `./bin/dev/docs.sh` on Windows. I [installed the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) but I get an error:

```
/mnt/c/src/flutter/bin/flutter: line 5: $'\r': command not found
```

I *am* able to run `analyze-sample-code.dart` since it is a dart file:

```
cd dev\bots
dart pub get
dart pub run .\analyze-sample-code.dart
```

I don't see any mention of Windows in the [Dartdoc generation README](https://github.com/flutter/flutter/tree/master/dev/snippets), maybe we should warn Windows users?

**Comment by TahaTesser** [comment]
Hi @johnpryan 
Are you generating docs from the repository in windows or Linux distro in WSL?  I doubt you can access Windows 10 SDK from inside WSL.

If you do the setup in windows with the necessary tools, you should be able to generate docs

**Comment by darshankawar** [comment]
Hello @johnpryan 
Revisiting this issue to reflect correct status, just would like to know if this is still the case and need to keep it open ?

**Comment by TahaTesser** [comment]
> Hello @johnpryan Revisiting this issue to reflect correct status, just would like to know if this is still the case and need to keep it open ?

I have WSL on my personal machine. I'll verify and update the issue tomorrow.

**Comment by TahaTesser** [comment]
A different error is thrown when generating docs in WSL on the latest `master`  channel. For sone reason `version` file is removed.

```console
taha@DESKTOP-8A8RR1A:~/flutter$ ls
AUTHORS             CONTRIBUTING.md  README.md              bin                   examples             version
CODEOWNERS          LICENSE          TESTOWNERS             dartdoc_options.yaml  flutter_console.bat
CODE_OF_CONDUCT.md  PATENT_GRANT     analysis_options.yaml  dev                   packages
taha@DESKTOP-8A8RR1A:~/flutter$ ./dev/bots/docs.sh
Thu Aug 17 00:19:00 EEST 2023: Running docs.sh
cat: /home/taha/flutter/version: No such file or directory
taha@DESKTOP-8A8RR1A:~/flutter$ ls
AUTHORS             CONTRIBUTING.md  README.md              bin                   examples
CODEOWNERS          LICENSE          TESTOWNERS             dartdoc_options.yaml  flutter_console.bat
CODE_OF_CONDUCT.md  PATENT_GRANT     analysis_options.yaml  dev                   packages
taha@DESKTOP-8A8RR1A:~/flutter$
```

**Comment by darshankawar** [comment]
Thanks for verifying @TahaTesser. Based on latest findings as above, updating labels as applicable.

**Comment by christopherfujino** [comment]
Responding to the original issue, @johnpryan it looks like you checked out the Flutter SDK with git for Windows, with the settings to convert unix style line endings to Windows style, then you executed a bash script from that checkout on the Windows subsystem for Linux. This is not a supported use case, if you want to run scripts from WSL, I would recommend cloning the SDK from WSL to an ext4 partition.

Also, it was my understanding that we never inteded `bin/dev/docs.sh` to be run by end users. If there's anywhere we recommend that, we should reconsider that.
