### ISSUE TITLE
[Webview_flutter]When will macOS be supported

### ISSUE THREAD

**Issue by frendguo** [flutter/flutter#68755]
[Flutter has previewed desktop applications](https://flutter.dev/desktop), but I can’t use Webview_flutter on mac OS (Windows/Linux). Does WebView_flutter have any plans to support the desktop?

**Comment by balvinderz** [comment]
Platform views are not supported on desktop currently , so it is currently not possible to make webview_flutter support desktops right now.

**Comment by darshankawar** [comment]
Closing this as duplicate of [41725](https://github.com/flutter/flutter/issues/41725)
