### ISSUE TITLE
Flutter doctor, flutter devices  or just the command flutter does not run the file is hidden (windows PC)

### ISSUE THREAD

**Issue by akashgkrishnan** [flutter/flutter#68757]
## Steps to Reproduce

1. ... Make the unzipped flutter with the bin file hidden
2. ... run the command flutter, flutter devices, flutter doctor etc
3. ... The system does not respond and we have to quit out the terminal

I'm expecting at least an error message

## Logs

```
```

```
```

**Comment by darshankawar** [comment]
@akashgkrishnan 
Why do you want to make the Flutter files hidden at first place ? What use case are you trying to achieve by hiding the files ?
Usually whenever Flutter is installed and unzipped on any platform, the ideal way is to run `flutter doctor` command without making any changes to the file structure. Even if files are hidden, the flutter commands won't find it anyway, so what's the point of doing it ?

**Comment by Prasad342** [comment]
Unzip the flutter file and store in C:/src/flutter 
Also provide the environmental variable in path to flutter sdk.
I hope it will help 

thank you
