### ISSUE TITLE
CircleAvatar backgroundImage is not scaling the image

### ISSUE THREAD

**Issue by daplo** [flutter/flutter#68767]
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.teal,
        body: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,

            children: [
              CircleAvatar(
                radius:50.0,
                backgroundColor: Colors.yellow,
                backgroundImage: AssetImage('images/avatar.png')
              ),
            ],
          )
        )
      ),
    );
  }
}
```

If a Container has: crossAxisAlignment: CrossAxisAlignment.stretch, then the background image is not sized properly. 

![flutter-issue](https://user-images.githubusercontent.com/11730937/96842258-8aba9400-1498-11eb-966a-f81fc567aeea.JPG)
![flutter-no-issue](https://user-images.githubusercontent.com/11730937/96842261-8bebc100-1498-11eb-809e-839b374c324e.JPG)

**Comment by pedromassangocode** [comment]
> If a Container has: crossAxisAlignment: CrossAxisAlignment.stretch, then the background image is not sized properly.

Based on the docs from `CrossAxisAlignment.stretch`:

> /// Require the children to fill the cross axis.
>   ///
>   /// This causes the constraints passed to the children to be tight in the
>   /// cross axis.

So this is an expected behavior. I'm not sure what you want exactly, but, if you want to scale the image you should use the radius parameter as you did.

I'm closing this for now.
