### ISSUE TITLE
PluginCodelab needs to be renamed to plugin_codelab

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#68762]
Per [travis](https://travis-ci.org/github/flutter/codelabs/jobs/737922562#L958) the `PluginCodelab` is incorrectly named:

```
+/home/travis/build/flutter/codelabs/flutter/bin/flutter analyze
Analyzing example...                                            
   info • Use `lowercase_with_underscores` for package names • pubspec.yaml:1:7
          • package_names
1 issue found. (ran in 2.8s)
The command "./travis.sh" exited with 1.
```

This is currently erroring out on the `dev` channel, but I presume it will start failing on `beta` sooner or later.

**Comment by Roshan13046** [comment]
I would like to work on this issue.
Can you share the source code file link? or suggest some tips to start working on this issue?

**Comment by domesticmouse** [comment]
Eep, my bad.

This work was carried out in https://github.com/flutter/codelabs/pull/32 and https://github.com/flutter/codelabs/pull/34
