### ISSUE TITLE
Detect home, recent key on Android, iOS & default behaviour

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#68770]
## Use case

I have a online exam app where i don't want the user to go out of the app while giving exam.

## Proposal

Maybe there can be a class to handle to override the behaviour of the key.

**Comment by pedromassangocode** [comment]
Hi @Faiyyaz 
You can currently to this by using some native code and sending actions to Flutter using `MethodChannel`.
See https://stackoverflow.com/questions/8881951/detect-home-button-press-in-android

As far as I know there is no a native (and official) way of doing this on Android (nor iOS). For Android see the link above for some solutions.

I'm not sure if this is a valid proposal so I will leave this opened for the right person to take action.

Cc @xster

**Comment by Faiyyaz** [comment]
There is a concept called screen pinning in android native but even I am not sure how it works. Just that it pins the current app and no notification is visible while the app is pinned

**Comment by pedromassangocode** [comment]
This seems to be unrelated to the issue.

You can write a plugin that call the methods to enable screen-pinning on Android, see
https://stackoverflow.com/a/28213072

Not sure if there is something similar for iOS!

**Comment by msarkrish** [comment]
@pedromassangocode like WillPopScope we need widget to handle home, recent, volume up, volume down buttons.

**Comment by stuartmorgan** [comment]
We can't make a plugin to do something that the OS doesn't support, so closing.

**Comment by msarkrish** [comment]
@stuartmorgan @pedromassangocode is there any other way is there for detecting home, recent button press?

**Comment by pedromassangocode** [comment]
You may want to research how it can be done in Android and iOS (if possible), then you write a plugin to wrap the implementation and use that plugin in your project.

There is a old long thread about this in SO, I'm not sure if it works nowadays but it may be a starting point:
https://stackoverflow.com/questions/8881951/detect-home-button-press-in-android
