### ISSUE TITLE
I would like to have the native browser scrollbar on flutter web

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#68781]

**Comment by TahaTesser** [comment]
Hi @arualana 
Can you please explain in detail what the exact behavior you want?  
Flutter widgets have their own style of the scrollbar and there are dedicated scrollbar widgets like in material and Cupertino

**Comment by arualana** [comment]
@TahaTesser when the content of the flutter web app overflows the viewport I would like to be able to scroll down or up with the browser's scroll bar.
Currently there is no browser scroll bar, I can wrap my content in the Scrollbar widget, but the scroll bar it shows first it is not draggable (it has a very weird behavior when trying to drag it) so I am only left with the option of scrolling using mouse wheel. 

I would like to be able to use the browser scroll bar when content overflows, just like I do with a regular website, if this is not clear please let me know and I will try to post an example with code

**Comment by Piinks** [comment]
Hi @arualana, there is already a request for this feature in https://github.com/flutter/flutter/issues/31753
The CupertinoScrollBar currently supports dragging though if that is helpful as a workaround in the meantime.
Thank you for filing an issue! :)
