### ISSUE TITLE
[flutter_tools] Wrong docs in wrapText function

### ISSUE THREAD

**Issue by raapperez** [flutter/flutter#68783]
In https://github.com/flutter/flutter/pull/63831 the param `columnWidth` in function `wrapText` stopped having a default value:
```
columnWidth ??= globals.outputPreferences.wrapColumn;
```
But the function docs was not updated:
```
/// If [columnWidth] is not specified, then the column width will be the
/// [outputPreferences.wrapColumn], which is set with the --wrap-column option.
```

I found this because I started to get the error calling  wrapText after updating flutter:
```
NoSuchMethodError: The method '-' was called on null.
```

(We are using the wrapText function in our own tools)

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/blob/fe189baf34099914f1dcb27231e06ba383897f59/packages/flutter_tools/lib/src/base/utils.dart#L199-L212

**Comment by jmagman** [comment]
@raapperez It sounds like you already did all the work. Pull requests are always welcome 😉

**Comment by jmagman** [comment]
@raapperez Out of curiosity, how are you using this in your own tools?  This isn't a stable API layer and we reserve the right to change it at any time (though you're right about updating docs)

**Comment by raapperez** [comment]
@jmagman Every time we update Flutter we need to fix all the breaking changes. We're already used to it.

**Comment by jmagman** [comment]
@raapperez I meant, for what reason are you using this?
