### ISSUE TITLE
Error in command: "flutter doctor"

### ISSUE THREAD

**Issue by aybbega** [flutter/flutter#68797]
flutter doctor shows that there are no plugins installed in android studio: Dart and Flutter. But in android studio they are and you can run the application on flutter in the emulator without any problems. I have an operating system arch linux, maybe this will help. Android studio 4.1.

**Comment by Jamilusalis** [comment]
> flutter doctor shows that there are no plugins installed in android studio: Dart and Flutter. But in android studio they are and you can run the application on flutter in the emulator without any problems. I have an operating system arch linux, maybe this will help. Android studio 4.1.

It is a Flutter issue on **1.22 channel stable version due to upgrading to Android Studio 4.1. It was already fixed on 1.23 version (dev channel) and you can switch to it by running: `flutter channel dev` and` flutter upgrade`

**Comment by darshankawar** [comment]
@aybbega 
See [this](https://github.com/flutter/flutter/issues/67986) issue and correpsonding comments on the issue. You may upgrade to latest per above comment and see if it works for you.
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986)

**Comment by OsamaAkram** [comment]
i have same error, how can fixed =, please
