### ISSUE TITLE
AppBar can't function in a container that's less than 64 dp wide

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6879]
See: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app_bar.dart#L61

**Comment by Hixie** [comment]
Yeah, this is part of https://github.com/flutter/flutter/issues/6537

**Comment by jason-simmons** [comment]
Fixed (https://github.com/flutter/flutter/pull/6894)
