### ISSUE TITLE
VM FlagList claims that sound-null-safety is disabled even when an application is run in sound null safe mode

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68808]
I'm not seeing sound-null-safety set to true. I tried reading values from the flag list using hello_world.

Step 1: update examples/hello_world

```
diff --git a/examples/hello_world/lib/main.dart b/examples/hello_world/lib/main.dart
index 3cefcf3662..a3a48e6e10 100644
--- a/examples/hello_world/lib/main.dart
+++ b/examples/hello_world/lib/main.dart
@@ -2,6 +2,7 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+// @dart = 2.11
 import 'package:flutter/widgets.dart';
 
 void main() =>

```

Step 2: print out flag value during flutter run

```
diff --git a/packages/flutter_tools/lib/src/resident_runner.dart b/packages/flutter_tools/lib/src/resident_runner.dart
index ac8c6ac639..f3d141ee47 100644
--- a/packages/flutter_tools/lib/src/resident_runner.dart
+++ b/packages/flutter_tools/lib/src/resident_runner.dart
@@ -513,6 +513,11 @@ class FlutterDevice {
 
   Future<void> initLogReader() async {
     final vm_service.VM vm = await vmService.getVM();
+    final vm_service.FlagList flagList = await vmService.getFlagList();
+    final vm_service.Flag soundNullSafety = flagList.flags.firstWhere((vm_service.Flag flag) {
+      return flag.name == 'sound_null_safety';
+    }, orElse: () => null);
+    print('IS SOUND NULL SAFETY ENABLED: ${soundNullSafety?.valueAsString}|${soundNullSafety?.modified}');
     final DeviceLogReader logReader = await device.getLogReader(app: package);
     logReader.appPid = vm.pid;
   }
```

Step 3:

```
flutter run --sound-null-safety --enable-experiment=non-nullable
...
IS SOUND NULL SAFETY ENABLED: false|false
```

The flag is not actually ever being set, which is not making it possible to report whether a hot reload has happened in weak or sound mode for https://github.com/flutter/flutter/issues/67322

**Comment by jonahwilliams** [comment]
From talking with @bkonyi , the flag is set https://dart-review.googlesource.com/c/sdk/+/166260 . but it is possible the engine is not providing that.

FYI @chinmaygarde @jason-simmons

**Comment by chinmaygarde** [comment]
Sound null-safety is a per isolate attribute and depends on whether the snapshot used to create the isolate specific the same. So, when you ask the VM service for its flags, I am not sure how it can know which isolate to query the sound-null-safety attributes of. Also, in debug mode, the [service isolate always runs in weak null-safety](https://github.com/flutter/flutter/issues/68663). So could it be that you are checking the attributes of the service isolate and not the root application isolate?

**Comment by jonahwilliams** [comment]
We could certainly check isolate flags instead. There is some question in my mind as to whether that is the right approach, I hadn't considered the service isolate.

There are probably some edge cases in add2app but I don't think those will have an impact on the overall numbers

**Comment by chinmaygarde** [comment]
> some question in my mind as to whether that is the right approach...

In debug mode, the service isolate snapshot is present in the engine binary itself, so depending on how the engine packages that snapshot, you'll get a binary response for analytics. And, in multi-tenant instances, you'll have to ask each isolate anyway right?

**Comment by jonahwilliams** [comment]
Yeah, fair enough.

**Comment by jonahwilliams** [comment]
Going to de-dupe into https://github.com/flutter/flutter/issues/67322
