### ISSUE TITLE
Suppress "Double-quoted include in framework header" warnings in Pods

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#68813]
CocoaPods turned the new `-Wquoted-include-in-framework-header` Xcode 12 warning off by default https://github.com/CocoaPods/CocoaPods/issues/9902.  Copy this behavior so Flutter users on older CocoaPods versions do not see the warning.

Worse, some pods set `GCC_TREAT_WARNINGS_AS_ERRORS` but then have double quoted includes, so just fail to build.
https://github.com/CocoaPods/Specs/blob/master/Specs/b/c/f/GoogleDataTransportCCTSupport/3.2.0/GoogleDataTransportCCTSupport.podspec.json#L56

Reported at https://github.com/flutter/flutter/issues/60025#issuecomment-714436203

**Comment by jmagman** [comment]
\cc @paulb777 who was interested in this.

**Comment by paulb777** [comment]
@jmagman thanks for the pointer. I'll stop adding that option in the next release, since we check for warnings in our CI and should avoid causing failures if future versions of Xcode introduce warnings.

In the meantime, updating to CocoaPods 1.10.0 will likely address this warning.
