### ISSUE TITLE
Tree is red due to repeated infra failures in mac tool and build tests

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68811]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20tool_tests

Twice in a row so far. Should I retry again?

**Comment by godofredoc** [comment]
This is related to mac leaking memory and killing the processes.

**Comment by keyonghan** [comment]
The error is retcode -9, marking as duplicate of https://github.com/flutter/flutter/issues/68322
