### ISSUE TITLE
cmd crash when using any flutter command

### ISSUE THREAD

**Issue by andrei5000** [flutter/flutter#68820]
I am using Windows 8 and whenever I try to use any command that begins with "flutter" it says that it's checking for SDK, then it crashes a second later. Flutter is a fresh install, so no idea why.

[flutterdoctorCrash.zip](https://github.com/flutter/flutter/files/5425604/flutterdoctorCrash.zip)

**Comment by Jamilusalis** [comment]
Hi @andrei5000, could you please provide the following details to see if I could be of help?
1. Specify the flutter version you downloaded (optional)
2. Where the flutter was extracted
3. Your environment variable PATH where you add Flutter to.

 _screenshot of **(2)** and **(3)** above will be of g the explorer window if possible_

**Comment by TahaTesser** [comment]
Hi @andrei5000 
Also, make sure you've flutter SDK located in a directory with write permissions
Thank you

**Comment by Prasad342** [comment]
hi @andrei5000 
Check with environmental variable for the flutter sdk path ,
If still the problem remains same reinstall flutter on ur system .
Thank You

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Nabeel20** [comment]
I am having the same issue.```
Windows 8 
Flutter last version (I cloned the GitHub repository) (Can't run flutter --version)
I installed flutter sdk on E:\ and updated PATH

**Comment by shashika1986** [comment]
Same happens with Windows 10.
git version 2.14.1.windows.1
Just even can't run 'flutter' in command prompt, it crashes. just hour ago I cloned flutter.

**Comment by himideb** [comment]
I am facing similar issue. While trying to run flutter commands, it's shows - "Checking DART sdk version..." and then it would crash.
![Capture](https://user-images.githubusercontent.com/49477075/104852971-c643ed80-5923-11eb-8af2-739cd3a238f8.JPG)

I am using a Windows 8.1
Git 2.30.0.2
I have updated the PATH in Environmental variables. I tried installing in different drives, same issue persists.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ycdaskin** [comment]
Adding powershell.exe path to system variables solved the issue for me.

C:\Windows\System32\WindowsPowerShell\v1.0

**Comment by zhang52104** [comment]
update WindowsPowerShell to 5.0

**Comment by DSCMbararaUST** [comment]
> Adding powershell.exe path to system variables solved the issue for me.
> 
> C:\Windows\System32\WindowsPowerShell\v1.0

Thanks this too worked for me

**Comment by desderymedard** [comment]
> Adding powershell.exe path to system variables solved the issue for me.
> 
> C:\Windows\System32\WindowsPowerShell\v1.0

thannk you

**Comment by darshantogadiya** [comment]
> Adding powershell.exe path to system variables solved the issue for me.
> 
> C:\Windows\System32\WindowsPowerShell\v1.0

Thanks, It's works for me

**Comment by anon-000** [comment]
C:\Program Files\Git\bin
C:\Program Files\Git\cmd
C:\Windows\System32
C:\Windows\SysWOW64\WindowsPowerShell\v1.0
C:\src\flutter\bin

Add all of these paths to your env variables. The path may vary according to your folder structure. But make sure that you add the paths of the above things and install git. 

I've come across this problem recently and the above solution worked for me. Just give it a try,  I hope it'll solve your problem too.

**Comment by khushi2699** [comment]
> Adding powershell.exe path to system variables solved the issue for me.
> 
> C:\Windows\System32\WindowsPowerShell\v1.0

Worked for me too!!
Thanks a lot
