### ISSUE TITLE
Our only ios32 agent flutter-devicelab-mac-11 seems to be down

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#68827]
See https://flutter-dashboard.appspot.com/#/build?taskFilter=ios32

**Comment by godofredoc** [comment]
\cc @jonahwilliams did your change to reboot the phones landed?

This phone requires manual intervention after rebooting and requires a physical lab visit.

**Comment by jonahwilliams** [comment]
No, I did not land that

**Comment by godofredoc** [comment]
Submitted issue to get help recovering the device: fxb/62625

**Comment by godofredoc** [comment]
The phone was rebooted and dialogs dismissed, however the test bed is still down

**Comment by keyonghan** [comment]
Bot is back by updating the agent token.
