### ISSUE TITLE
[web] After upgrade from 1.22.0-12.4.pre to 1.23.0-18.1.pre cache busting is not working

### ISSUE THREAD

**Issue by archie-sh** [flutter/flutter#68824]
## Steps to Reproduce

I release my app to aws s3 with the following script:

```
flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
cd build
aws s3 sync web/ s3://[myBucket]/ --exclude index.html
aws s3 cp web/index.html s3://[myBucket]/ --cache-control no-cache
```

after upgrading to 1.23.0-18.1.pre changes to the application will not display. Downgrading to 
1.22.0-12.4.pre solves the problem. 

Official documentation does not mention cache busting https://flutter.dev/docs/deployment/web and something changed between versions.

**Comment by TahaTesser** [comment]
Hi @archie-sh 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
