### ISSUE TITLE
Need a way to pecify the height of TabBar in AppBar

### ISSUE THREAD

**Issue by kuyum** [flutter/flutter#68839]
I need to specify the height of TabBar in AppBar, but it can't be done.
I found it is hard-coded. I have tried PreferredSize, but it does't work.
We are using a package naming flutter_screenutil. We want to specify the height of TabBar according different device.
For now I have to extend the class TabBar to achieve my goal.
I don't think it is a good idea to hard-coded the height.
sample code:
```
AppBar(
    title: some widget,
    bottom: TabBar(
        tabs: tabs,
        isScrollable: true,
        controller: tabController)
)
```

**Comment by Dasunx** [comment]
#68842 This is the same issue.

**Comment by kuyum** [comment]
> #68842 This is the same issue.
I don't know why it posts repeatedly. Thanks
