### ISSUE TITLE
Linux Web Framework tests are timing out on the buildbucket.collect step.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68837]
An [example of this failure is here](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/466).

This appears to be consistent and is backing up further runs.

![Screen Shot 2020-10-22 at 6 07 18 PM](https://user-images.githubusercontent.com/44085/96945095-8b9bf780-1491-11eb-9032-8925df2e4729.png)

**Comment by godofredoc** [comment]
This builds were also affected by the slow uploads/downloads to GCS from the datacenter the bots are running from. This issue has been resolved.
