### ISSUE TITLE
xcode 12  Flutter 1.22  无法运行debug模式

### ISSUE THREAD

**Issue by D-Rusty** [flutter/flutter#68838]
报错如下：
To launch in debug mode in iOS 14+, run flutter run from Flutter tools, run from an IDE with a Flutter IDE plugin or run the iOS project from Xcode.
Alternatively profile and release mode apps can be launched from the home screen.

我的运行环境：
![image](https://user-images.githubusercontent.com/17473495/96946345-ad898e80-1512-11eb-8e95-7c08f573dfec.png)

**Comment by softmarshmallow** [comment]
Please use english

**Comment by erickzanardo** [comment]
Hey, it is not clear what is the problem here, is the debug mode not working somehow?

Please explain better what is the issue and if there is any error happening, attach the logs and a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) of the problem.

Thanks

**Comment by Geek-James** [comment]
Please use English~

**Comment by D-Rusty** [comment]
Sorry, this is issuue for the first time,The mistakes I encountered are as follows，thank you：
![image](https://user-images.githubusercontent.com/17473495/98184055-6b197600-1f44-11eb-9a75-7c39f1b2b4f0.png)

**Comment by pedromassangocode** [comment]
Hi @D-Rusty 
Can you please follow the suggestion given in the logs?
Also see https://flutter.dev/docs/development/ios-14
Thank you

**Comment by D-Rusty** [comment]
thank you，Let me learn

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
