### ISSUE TITLE
[flutter_releases] Because of cloud storage caching, a user can download old artifacts

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#68835]
When a user (or CI build) attempts to download a binary artifact that we have uploaded to cloud storage, they hit a cached version. This becomes a problem when we generate our release packages, because:

1) when we codesign engine binaries, we overwrite the same file path pointing to the unsigned archives with the signed archives
2) we often immediately trigger the packaging build after codesigning, meaning that the packaging build MIGHT download a new signed artifact or an old unsigned artifact.

**Comment by godofredoc** [comment]
@christopherfujino was this fixed with the TTL header on the artifacts?

**Comment by christopherfujino** [comment]
yup, i'm pretty sure that covers it.
