### ISSUE TITLE
Linux Fuchsia builders are failing because of recipe crashes.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68836]
An [example of the failure is here](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/5951). The [specific error](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865699758255557600/+/steps/RECIPE_CRASH__Uncaught_exception_/0/stdout) is:

```
Infra Failure
recipe infra failure: Uncaught Exception: TypeError('not all arguments converted during string formatting',)
```

This seems to be happening for all build attempts by this builder.

![Screen Shot 2020-10-22 at 6 03 14 PM](https://user-images.githubusercontent.com/44085/96944882-fdc00c80-1490-11eb-81aa-9b7960dfa60d.png)

**Comment by chinmaygarde** [comment]
Correction, [one of the builds in the column I highlighted](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/5949) was because the build timed out after 1h and 30mins. It did not seem to be stuck either. It was just uploading some symbols to a server. It just seems like it took a long time to schedule and the builder was slower than usual?

**Comment by godofredoc** [comment]
This was a problem with very slow uploads/downloads to gcs from one of the datacenters. This has been resolved.
