### ISSUE TITLE
After switch to master channel and upgrade to 1.24.0, some parameters of widgets gone

### ISSUE THREAD

**Issue by ShiinaManatsu** [flutter/flutter#68847]
For some reason I use version 1.20.0 for a while, and this days I upgrade to master channel and this showed.
Like `child` `onPressed`, navigate to source code I found the `required` dose start with `@`

Is the only way to fix this is to re-download the SDK?

![Snipaste_2020-10-23_10-48-37](https://user-images.githubusercontent.com/20186095/96950761-9f8d3b00-151d-11eb-9e47-894c27982d3e.png)

![Snipaste_2020-10-23_10-52-14](https://user-images.githubusercontent.com/20186095/96950841-d19e9d00-151d-11eb-965c-870be87ae96e.png)

**Comment by ShiinaManatsu** [comment]
After I tried to clone flutter git this situation still there :(

**Comment by amanv8060** [comment]
`@required` is now `required` . Please include output of `flutter doctor -v`
Thanks

**Comment by jonahwilliams** [comment]
You may need to restart your analyzer

**Comment by ShiinaManatsu** [comment]
> `@required` is now `required` . Please include output of `flutter doctor -v`
> Thanks

`flutter doctor -v` here
<details>

[✓] Flutter (Channel unknown, 1.20.0, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.20.0 at D:\flutter
    • Framework revision 840c9205b3 (3 months ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Flutter.Dev\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Flutter.Dev\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Flutter.Dev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.48

• No issues found!
</details>

**Comment by ShiinaManatsu** [comment]
> You may need to restart your analyzer

I don't know if restart vscode can do that, but if it is, I tried

**Comment by pedromassangocode** [comment]
Hi @ShiinaManatsu 
As said above required is now a keyword in Dart, it was introduced along with Null Safety.
This is just the analyzer complaining about it.

Closing this as invalid Flutter issue.
