### ISSUE TITLE
windows 7, "EGL: Failed to initialize EGL" error is always shown when executing "flutter run", and the executable built could not run

### ISSUE THREAD

**Issue by leolovesmile** [flutter/flutter#68861]
## Environment
- OS: windows 7 SP1

- `flutter doctor` result
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel master, 1.24.0-2.0.pre.111, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
> [√] Android Studio (version 3.6)
> [√] IntelliJ IDEA Ultimate Edition (version 2020.1)
> [√] Connected device (1 available)
 
> • No issues found!

- `flutter --version` output:
> Flutter 1.24.0-2.0.pre.111 • channel master • https://github.com/flutter/flutter.git
> Framework • revision fe189baf34 (28 hours ago) • 2020-10-21 22:25:53 -0400
> Engine • revision f459a86610
> Tools • Dart 2.11.0 (build 2.11.0-242.0.dev)

## Steps to Reproduce
- run `flutter create win7flutter` under the working directory *win7flutter*
- run `cd win7flutte`
- run `flutter run` and get the following console output with error **EGL: Failed to initialize EGL**. 
> Launching lib\main.dart on Windows in debug mode...
> Building Windows application...
> EGL: Failed to initialize EGL
> [ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(108)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
> [FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
> Error connecting to the service protocol: failed to connect to http://127.0.0.1:51045/yanMSoQOdfQ=/
> 
- Expected results: no error shows, the application dialogs pops up with no problem, just like I have got in another PC with Windows 10 OS.
- Actual results: error shows as above

## other helpful information
- I googled and found one issue similar (same error but not in Windows OS): https://github.com/flutter/flutter/issues/62664, but with no solution with it.
- Run `flutter build windows` and the executable result could be generated successfully, but the executable will start with error similar as the following one (but the generated executable  could run without error in **another Windows 10 PC**):
![image](https://user-images.githubusercontent.com/12458587/96967163-a332b900-1541-11eb-8efe-a0888fdad730.png)

**Comment by TahaTesser** [comment]
Hi @leolovesmile 
There's a similar open issue describing your case, [51286](https://github.com/flutter/flutter/issues/51286)
Please follow-up there for updates.
Closing this as duplicate.
