### ISSUE TITLE
ClipRRect's borderRadius property should be of type BorderRadiusGeometry and not BorderRadius class

### ISSUE THREAD

**Issue by abdulmuaz97** [flutter/flutter#68869]
Hi, I'm reporting this issue that I found.. firstly I thought there should a way that somehow I can play around it, but couldn't.

### Problem
The **ClipRRect** has a property of Type **BorderRadius** class and when someone try to use the **BorderRadiusDirectional** it gives an error that tells us:
`The argument type 'BorderRadiusDirectional' can't be assigned to the parameter type 'BorderRadius'`

and it is totally make sense since the the borderRadius property of the ClipRRect should be of type **BorderRadiusGeometry**.

### Code sample
```dart
Widget buildImage() {
  return ClipRRect(
    // gives an error here
    borderRadius: BorderRadiusDirectional.only(
      topStart: Radius.circular(10),
      topEnd: Radius.circular(10),
    ),
  );
}
```

### Solution
Replacing the **BorderRadius** by **BorderRadiusGeometry** class property in the **ClipRRect**.

I also made a pull request for review/merge that solves this little issue.

**Comment by darshankawar** [comment]
@abdulmuaz97 
There's a similar open issue describing your case, [62011](https://github.com/flutter/flutter/issues/62011).
You may want to follow-up there.
Closing this as duplicate.
