### ISSUE TITLE
It'd be nice to have a DismissDirection.none to make a widget wrapped with Dismissible become non-dismissible

### ISSUE THREAD

**Issue by vannevar-morgan** [flutter/flutter#68862]
https://api.flutter.dev/flutter/widgets/DismissDirection-class.html

There's no "none" value in the DismissDirection enum.

If a widget is dismissible we only need to set the direction value in a Dismissible to change the dismiss behavior.

But for a widget that may be dismissible or non-dismissible we need to check whatever criteria decides dismissible vs. non-dismissible - then either return the widget or the widget wrapped with a dismissible.

It would be cleaner if we have a DismissDirection.none to indicate a widget is non-dismissible.

It's part of flutter core and should not be provided by an alternative package.

e.g.:
Currently:
```
if(isDismissible){
  return Dismissible(
    direction: dismissDirection,
    child: Widget(...),
    ...
  );
}else{
  return Widget(...);
}
```

Proposed:
add a "DismissDirection.none"
then:
```
return Dismissible(
  direction: dismissDirection,
  child: Widget(...),
  ...
);
```

**Comment by sidrao2006** [comment]
Hey @vannevar-morgan ,
Thanks for the feature request.

Currently you could wrap `Dismissible` with `IgnorePointer` and set the `ignoring` to true when you want to disable `Dismissible`

Thanks

**Comment by pedromassangocode** [comment]
Hi @vannevar-morgan 
In order to prevent the `Dismissible` widget to dismiss you should `false` in the `confirmDismiss` callback.
Please read more in https://api.flutter.dev/flutter/widgets/Dismissible/confirmDismiss.html

**Comment by vannevar-morgan** [comment]
> Hi @vannevar-morgan
> In order to prevent the `Dismissible` widget to dismiss you should `false` in the `confirmDismiss` callback.
> Please read more in https://api.flutter.dev/flutter/widgets/Dismissible/confirmDismiss.html

That's not ideal because the Widget can still be dragged.  I guess I didn't make it clear in the OP but for a Widget wrapped with Dismissible to be "non-dismissible" via a "DismissDirection.none" the widget should behave exactly as though it is not wrapped with Dismissible.  It should not be able to be dragged.

**Comment by pedromassangocode** [comment]
Hi @vannevar-morgan 
Thanks for making this clear

**Comment by chinmoy12c** [comment]
May I work on this issue?
