### ISSUE TITLE
[web] Adding a icon to the AppBar via Text.rich() throws exception with ..._USE_SKIA=true

### ISSUE THREAD

**Issue by wf227** [flutter/flutter#68879]
#68421  Steps to Reproduce

While trying to debug an animation problem in a web project I came across this problem first: I wanted to have an icon as part of the AppBar title property and came up with the idea of using Text.rich() to combine text and icon:
'''
```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(55.0),
        child: AppBar(
          title: const Text.rich(
            TextSpan(
              style: TextStyle(fontSize: 12, fontWeight: FontWeight.w100),
              children: [
                WidgetSpan(
                  child: SizedBox(
                    width: 30.0,
                    height: 30.0,
                    child: Icon(Icons.fingerprint, size: 30.0),
                  ),
                ),
                TextSpan(
                  style: TextStyle(fontSize: 32, fontWeight: FontWeight.w100),
                  text: 'see the icon to the left?',
                ),
              ],
            ),
          ),
        ),
      ),
      body: Center(
        child: Text(
          'You have pushed the button this many times:',
        ),
      ),
    );
  }
}
```
'''
This works in iOS simulator, flutter run web and using Safari, and Chrome, but does not work when using:

flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true

The following RenderObject was being processed when the exception was fired:
RenderParagraph#98d3c relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE:
  creator: RichText ← Text ← _AppBarTitleBox ← Semantics ← DefaultTextStyle ←
  MediaQuery ←
    LayoutId-[<_ToolbarSlot.middle>] ← CustomMultiChildLayout ←
    NavigationToolbar ← DefaultTextStyle ←
    IconTheme ← Builder ← ⋯
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=1168.0, 0.0<=h<=Infinity)
  size: MISSING
  textAlign: start
  textDirection: ltr
  softWrap: no wrapping except at line break characters
  overflow: ellipsis
  locale: en_US
  maxLines: unlimited
This RenderObject had the following descendants (showing up to depth 5):
    text: TextSpan
      TextSpan
        WidgetSpan#6bfa9
        TextSpan

**Expected results:** 
Consistent behaviour and a clear solution like which widget to use to wrap the widget_span containing the icon widget.

**Actual results:** 
The title part of the app bar is empty

```
appbar_bug % flutter doctor -v
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-DE)
    • Flutter version 1.23.0-18.1.pre at /Users/wf/Flutterei/flutter
    • Framework revision 198df796aa (8 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/wf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • B697C488-2080-4908-8B19-3C4F6B5A1F09 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@wf227 Although I was able to replicate the issue, I think it could be related to [this](https://github.com/flutter/flutter/issues/55587) open issue.

<img width="1198" alt="Screenshot 2020-10-23 at 7 19 45 PM" src="https://user-images.githubusercontent.com/67046386/97011934-ece0cb00-1564-11eb-97c9-90072ebebbfc.png">

Can you go through the link issue and check if it resembles your issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
