### ISSUE TITLE
Plugins are not detected

### ISSUE THREAD

**Issue by rohit5577** [flutter/flutter#68878]
Flutter and dart plugins are not detected even if i installed them

**Comment by darshankawar** [comment]
@rohit5577 
Even though it says plugins are not detected, they are just warnings and you can continue to create project as usual. There was a similar [issue](https://github.com/flutter/flutter/issues/67986) fixed. 
You may try to upgrade to latest version of dev or master and check if it resolves your issue.
Closing this as duplicate.
