### ISSUE TITLE
Ability to select and copy part of text

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#6887]
When using `Text` or `RichText` widgets, resulting text could not be selected and copied. It would be nice to have a possibility for more native behaviour of Text in some cases (like in Pesto example, copy part of recipe to clipboard or share).

**Comment by abarth** [comment]
We have copy for input widgets, but, yeah, we should also make it possible to copy regular text widgets.

**Comment by sethladd** [comment]
Valentyn, Where does this fall on your list? Top or bottom? :)

**Comment by olostan** [comment]
@sethladd just "nice to have". Absolutely not critical.

**Comment by olostan** [comment]
Just small clarification - I see label "text input" but it is not about text _input_ but more about output. Especially about `RichText` that can contain different `TextSpan` widgets...

**Comment by abarth** [comment]
I've removed the text input label.

**Comment by mpcomplete** [comment]
This is https://github.com/flutter/flutter/issues/5422

**Comment by patelkrunal78** [comment]
Your Solution At Here https://icetutor.com/question/how-to-make-copyable-text-widget-in-flutter
