### ISSUE TITLE
FlutterFire error

### ISSUE THREAD

**Issue by austinevick** [flutter/flutter#68873]
I keep having this error in my flutter projects after adding the firebase plugin (FlutterFire).
Please any help will be appreciated.
![Capture](https://user-images.githubusercontent.com/51150248/96998040-c0a85880-152a-11eb-89fd-b69b3d36d512.PNG)

**Comment by darshankawar** [comment]
@austinevick 
You seem to be on an obsolete version of Flutter (1.12.13+hotfix.5). Current stable version is 1.22.2. Please upgrade to latest and try again.
Also, FlutterFire issues need to be reported in separate repo : https://github.com/FirebaseExtended/flutterfire/issues
Closing this from here.
