### ISSUE TITLE
Upgrade ios-deploy to support new iPad and iPhones

### ISSUE THREAD

**Issue by ivanhernandez13** [flutter/flutter#68881]
ios-deploy has been updated to [v 1.11.3](https://github.com/ios-control/ios-deploy/releases/tag/1.11.3) and supports the new iPad 8, iPad Air 4, and the iPhone 12 models. 

Not sure if any work needs to be done on flutter to support this.

**Comment by jonahwilliams** [comment]
FYI @christopherfujino @jmagman

**Comment by christopherfujino** [comment]
> ios-deploy has been updated to [v 1.11.3](https://github.com/ios-control/ios-deploy/releases/tag/1.11.3) and supports the new iPad 8, iPad Air 4, and the iPhone 12 models.
> 
> Not sure if any work needs to be done on flutter to support this.

Thanks @ivanhernandez13

**Comment by jmagman** [comment]
Missed this, was done awhile ago, ios-deploy mirror is at https://github.com/ios-control/ios-deploy/commit/8670979f8ad61ef5623ff4e95702aa6bba07d340 (1.12.0)
