### ISSUE TITLE
openContainer deleted "Looking up a deactivated widget's ancestor is unsafe" on navigation pop

### ISSUE THREAD

**Issue by edmbn** [flutter/flutter#68912]
Hello everyone, 

I'm using openContainer inside an item created from a streamBuilder. Page is opened well but, if the stream changes and the item which had the openContainer is removed, when I go back I get this error: 

"Looking up a deactivated widget's ancestor is unsafe". 

Do you know what can happen? Thank you!

**Comment by Abhishek01039** [comment]
Hi @edmbn 
can you please provide `flutter run -v`, flutter doctor -v`, and minimal reproduction code?
Thanks.

**Comment by edmbn** [comment]
I just firgured it out. It is about using context inside the widgets that composed the closed openContainer. By passing its parent context the error is not shown anymore.
