### ISSUE TITLE
Dev and Beta release branches are uploading docs to stable.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#68916]
Seems like https://master-api.flutter.dev/ was uploaded to the stable documentation  https://api.flutter.dev/

![image](https://user-images.githubusercontent.com/54371434/97056634-4eda0a00-153e-11eb-8f6e-988fe4675550.png)

**Comment by godofredoc** [comment]
The problem is that dev, and beta are uploading docs to stable.

**Comment by pedromassangocode** [comment]
@godofredoc can you confirm that this was fixed by https://github.com/flutter/infra/pull/251?

**Comment by pcsosinski** [comment]
is this fixed?  I don't think we need to do any cherrypicking for an infra fix?  @christopherfujino fyi

**Comment by christopherfujino** [comment]
Oh wow, @godofredoc the stable docs have the branch name fixed. how did that happen? master still has no branch...

**Comment by godofredoc** [comment]
Not sure, it may be that my manual updates worked and I thought it didn't work because I was looking at the wrong PR. Anyway if the hash and branch are correct we can close this bug.
