### ISSUE TITLE
[video_player] video not rendered properly

### ISSUE THREAD

**Issue by danielwalczak** [flutter/flutter#68919]
## Steps to Reproduce

I have noticed that some video files are not rendered properly (see attachment), it could be from assets or gallery, but after its upload it to server and convert to mp4 it will render properly. 

1. video from gallery https://drive.google.com/file/d/1JZHi0a-t2cx5CdYhES_AtnnLobHFO8S0/view?usp=sharing

it is correct in the gallery
![IMG_7849](https://user-images.githubusercontent.com/3720039/97057076-79d15780-1558-11eb-9b9c-3c24b8e4c518.PNG)

but not in video_player
![IMG_8BD5DCE66D99-1](https://user-images.githubusercontent.com/3720039/97057129-99688000-1558-11eb-8a96-25139059f189.jpeg)

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)
```

</details>

**Comment by hamdikahloun** [comment]
Hi @danielwalczak 

Can you please provide your full `flutter doctor -v` and `flutter run --verbose` ?

Thank you

**Comment by darshankawar** [comment]
@danielwalczak 
Please provide a minimal complete reproducible code sample that shows the issue.

**Comment by recastrodiaz** [comment]
@danielwalczak can you try my `develop2` video_player fork? Your video displays correctly on a sample video_app I have:

https://github.com/flutter/plugins/pull/1307#issuecomment-656175989

**Comment by danielwalczak** [comment]
@recastrodiaz sure I will thanks

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
