### ISSUE TITLE
Coming Soon: Test new @immutable annotation

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6892]
meta package now has `@immutable`. See https://github.com/dart-lang/sdk/issues/27750

Analyzer supports `@immutable` on HEAD, which ensures all fields are final.

**Comment by sethladd** [comment]
See https://codereview.chromium.org/2775863004/

(landed, but not rolled...)

**Comment by sethladd** [comment]
Blocked by https://github.com/flutter/flutter/issues/9042

**Comment by abarth** [comment]
Apparently we need a dev.11 build.  I've started experimenting in https://github.com/flutter/flutter/pull/9152

**Comment by sethladd** [comment]
Sorry for the confusion on the dev version. :/

Here's the new blocking roll issue: https://github.com/flutter/flutter/pull/9151
