### ISSUE TITLE
Incorrect usage of Material in the test codebases?

### ISSUE THREAD

**Issue by znjameswu** [flutter/flutter#68939]
While refitting some Flutter test codes for my own library, I found the results of some test code are quite suspicious. I'm not sure if it is error or just me understanding it wrong.

### Example
https://github.com/flutter/flutter/blob/6823fbf9187df58b7dce51f1cfb9fd2a11370f78/packages/flutter/test/widgets/selectable_text_test.dart#L3868-L3877

According to my understanding, placing a `SelectableText` under `Material` under `MaterialApp` will force the `SelectableText` to take up full screen (due to the min constraints passed through). Then `getCenter` will return nothing but garbage.

### Demo
```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: SelectableText('abc def ghi'), // The whole screen becomes SelectableText
        ),
      ),
    );
```

https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

I initially planned to open up a PR for this file, but soon realized this might exist in other part of Flutter test codebases as well. Perhaps a lint is needed.

**Comment by shihaohong** [comment]
The behavior is expected because `SelectableText` _is_ taking up the entire screen. `tester.getCenter` returns an `Offset` for the center of the `SelectableText` widget. For example, in your test, if you just print the value, you'll get 
```dart
 await tester.pumpWidget( 
   const MaterialApp( 
     home: Material( 
       child: SelectableText('abc def ghi'), 
     ), 
   ), 
 ); 
  
 // Gets the center position of the widget.
 final Offset selectableTextPos = tester.getCenter(find.byType(SelectableText)); 
 print(selectableTextPos); // prints 'Offset(400.0, 300.0)'
```

It seems you might be misunderstanding the `getCenter` API. Perhaps what you're looking for is [`WidgetTester.tap`](https://master-api.flutter.dev/flutter/flutter_test/WidgetController/tap.html).

**Comment by znjameswu** [comment]
> The behavior is expected because `SelectableText` _is_ taking up the entire screen. `tester.getCenter` returns an `Offset` for the center of the `SelectableText` widget. For example, in your test, if you just print the value, you'll get
> 
> ```dart
>  await tester.pumpWidget( 
>    const MaterialApp( 
>      home: Material( 
>        child: SelectableText('abc def ghi'), 
>      ), 
>    ), 
>  ); 
>   
>  // Gets the center position of the widget.
>  final Offset selectableTextPos = tester.getCenter(find.byType(SelectableText)); 
>  print(selectableTextPos); // prints 'Offset(400.0, 300.0)'
> ```
> 
> From your code comment, it seems like you might be attempting to simulate a double tap instead? Perhaps what you're looking for is [`WidgetTester.tap`](https://master-api.flutter.dev/flutter/flutter_test/WidgetController/tap.html).

The problem is that this is effectively firing gestures the emptyness of the screen, far away from the actual text, which is inherently wierd.

Since indeed it still somewhat fulfilled the test purpose, I'll close this for now.
