### ISSUE TITLE
flutter/packages builds are not hermetic

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#68934]
flutter/packages .cirrus config fetches directly from latest master and uses `pub global activate` to install `flutter_plugin_tools`. A build that succeeds at one point in time can fail next time at the same commit simply by fetching a different version of Flutter or plugin tools ([example build breakage](https://github.com/flutter/packages/pull/234)).

Culprit: https://github.com/flutter/packages/blob/85135ddad047d82aa5025496410a41b031c4c5df/.cirrus.yml#L7-L11

**Comment by godofredoc** [comment]
Should we start by defining owners of the repo?

**Comment by stuartmorgan** [comment]
I recently changed the tools version to be pinned, so that's resolved. For Flutter, using the latest master/stable is generally a feature, so I wouldn't want to change that without having an autoroller constantly moving the version forward (which would certainly be better).

**Comment by stuartmorgan** [comment]
`master` switched to an autoroller a while ago, so the only piece left here is the unpinned `stable`, which will be fixed by https://github.com/flutter/packages/pull/2328
