### ISSUE TITLE
It is found that in Android phones, pictures/videos taken right after the camera control initialized (say within 500 ms), are very dark.  My work around is: `await Thread.sleep(500);` after the camera control initialization and then take picture or capture video.

### ISSUE THREAD

**Issue by gkoulomz** [flutter/flutter#68932]
It is found that in Android phones, pictures/videos taken right after the camera control initialized (say within 500 ms), are very dark.  My work around is: `await Thread.sleep(500);` after the camera control initialization and then take picture or capture video.

_Originally posted by @lhcdims in https://github.com/flutter/flutter/issues/24575#issuecomment-467392944_

**Is this an issue with Flutter, or with the underlying Android camera2 API?**

**Comment by gkoulomz** [comment]
Is this an issue with Flutter, or with the underlying Android camera2 API?

**Comment by sidrao2006** [comment]
Hey @gkoulomz ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please see https://flutter.dev/community for resources on asking queries doubts and assistance on personal code. You may get some help if you post it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=flutter) and if you need help with your code, please check https://www.reddit.com/r/flutterhelp/.

Also there is an open issue #24575 addressing this problem please follow up there.
Thanks

**Comment by darshankawar** [comment]
@gkoulomz 
You will need to follow-up in [24575](https://github.com/flutter/flutter/issues/24575). Once this issue is fixed, your question will be answered.
Closing this as duplicate.
