### ISSUE TITLE
reflect getDeclaredMethods does not work for flutter sdk 1.22.2

### ISSUE THREAD

**Issue by shufit** [flutter/flutter#68946]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>
when i run flutter  build apk --debug and intall apk on device, the reflect getDeclaredMethods is ok; but when i run flutter build apk --release and install apk on device,the reflect getDeclaredMethods does not work

```
```

```
```

```
Flutter (Channel stable, 1.22.2, on Mac OS X 10.14.6 18G4032, locale en-CN)
    • Flutter version 1.22.2 at /Users/jxoppo/Desktop/flutter
    • Framework revision 84f3d28555 (8 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

**Comment by TahaTesser** [comment]
Hi @shufit 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by shufit** [comment]
I find it is caused by Code shrinking, when i disable shrinking in build.gradle, it is fine.
Thank you

**Comment by TahaTesser** [comment]
Hi @shufit 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
