### ISSUE TITLE
Not able to release the apk for my app (build failed with an execution)

### ISSUE THREAD

**Issue by sainiteshb** [flutter/flutter#68950]
Hey guys im currently having a problem for releasing my app to play store
The keystone file is at C:/Users/saini/key.jks

my key.properties file:

storePassword=******
keyPassword=******
keyAlias=key
storeFile=/Users/saini/key.jks

build.gradile:
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
localPropertiesFile.withReader('UTF-8') { reader ->
localProperties.load(reader)
}
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
compileSdkVersion 29

sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
}

lintOptions {
    disable 'InvalidPackage'
}

defaultConfig {
    // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
    applicationId "app.id"
    minSdkVersion 16
    targetSdkVersion 29
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
}
signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
        storePassword keystoreProperties['storePassword']
    }
}
buildTypes {
    release {
        signingConfig signingConfigs.release
    }
}
}

flutter {
source '../..'
}

dependencies {
implementation 'com.android.support:multidex:1.0.3'
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation 'com.google.firebase:firebase-analytics:17.5.0'
}

When I run the command flutter build apk

i get this error:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:validateSigningRelease'.
Keystore file 'C:\Users\saini\AndroidStudioProjects\spaceiva\android\app\Users\saini\key.jks ' not foun
d for signing config 'release'.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
tput. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done 8.3s
Gradle task assembleRelease failed with exit code 1

Can anyone please help me in this issue as I have to publish my app to the play store but this issue is stopping me

**Comment by ashutosh1211** [comment]
storePassword=******
keyPassword=******
keyAlias=key
**storeFile=C:\\Users\\saini\\key.jks**

Change store file path.

**Comment by sainiteshb** [comment]
Should i replace path with this?
