### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/habtish/Downloads/TelegramDownloads/driver/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by habtish1** [flutter/flutter#68959]
## Command
```
flutter build apk --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/habtish/Downloads/TelegramDownloads/driver/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-ET)
    • Flutter version 1.22.1 at /Users/dawitassefa/Documents/flutter
    • Framework revision f30b7f4db9 (2 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/habtish/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24
### Plugins
cloud_firestore-0.12.11
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_remote_config-0.3.1+1
flutter_local_notifications-0.8.4+3
flutter_plugin_android_lifecycle-1.0.11
geocoder-0.2.1
geoflutterfire-2.0.3+5
google_maps_flutter-0.5.33
location-3.0.2
location_web-1.0.0
package_info-0.4.3
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
sqflite-1.3.1+1
url_launcher-5.7.2
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1
wakelock-0.1.4+2

**Comment by hamdikahloun** [comment]
Hi @habtish1 

Can you please upgrade to latest version (`flutter upgrade`) and provide your full `flutter build apk --verbose`?

Thank you

**Comment by darshankawar** [comment]
@habtish1 
Try [this](https://github.com/flutter/flutter/issues/65149#issuecomment-686255862) solution and see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by anaman9** [comment]
create a new project..
just replace gradlew file from new project to old project..

and just boom.
