### ISSUE TITLE
Flutter web rendering anomaly

### ISSUE THREAD

**Issue by syfulin** [flutter/flutter#68957]
Some things look much better in mobile browsers.
At the same time, I noticed that sometimes the quality of icons in Flutter Web on a desktop browser can improve if some neighboring widgets are accidentally changed (for example, the size).

**Desktop browser:**
![bad](https://user-images.githubusercontent.com/20333151/97084899-20deed80-1644-11eb-8b09-6ad7e17acef9.png)

**Mobile browser:**
![good](https://user-images.githubusercontent.com/20333151/97084902-23414780-1644-11eb-97f0-db6587a69907.png)

**Comment by hamdikahloun** [comment]
Hi @syfulin 

Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?

Thank you

**Comment by syfulin** [comment]
@hamdikahloun, thanks for the answer.

I have reinstalled Flutter SDK and the "anomalous gray line" is gone 🤷🏻‍♂️:
![Безымянный](https://user-images.githubusercontent.com/20333151/97141910-39f5b480-1792-11eb-96cd-7eab85cc4296.png)

The icons could be prettier too, but no 😑.

I'll try to find out when changing which code the icons lose quality and write here

`flutter doctor -v`:
![Безымянный222](https://user-images.githubusercontent.com/20333151/97142877-24818a00-1794-11eb-8c63-abee42f5f329.png)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
