### ISSUE TITLE
Visual Studio Code does not recognize ElevatedButton

### ISSUE THREAD

**Issue by pstricks-fans** [flutter/flutter#68965]
## Minimal Example
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Hello World'),
        ),
        body: Center(
          child: RaisedButton(// change it to ElevatedButton to reproduce the issue!
            child: Text('Click Me'),
            onPressed: () {},
          ),
        ),
      ),
    );
  }
}

```

## Steps to Reproduce

1. Create a project, copy the given minimal example above.  It should run without any issue.
2. Change `RaisedButton` to `ElevatedButton` and I get the following errors.

## Logs

![vsc-1](https://user-images.githubusercontent.com/50270635/97093900-f90a7c80-1679-11eb-8132-fd40ea2afbb7.png)

![elevatedbutton](https://user-images.githubusercontent.com/50270635/97093912-117a9700-167a-11eb-971c-724038e3626f.png)

## My Settings

![package-version](https://user-images.githubusercontent.com/50270635/97093945-438bf900-167a-11eb-8b03-da99ed3a043c.png)

![VSC](https://user-images.githubusercontent.com/50270635/97093953-5a325000-167a-11eb-9d57-3ab8d368d1b5.png)

![flutter-version](https://user-images.githubusercontent.com/50270635/97099817-e5820480-16bf-11eb-8522-2159420f0feb.png)

**Comment by ram231** [comment]
Have you tested this on dartpad yet? You can check it here.
https://dartpad.dev/ba816904e0aefbde80e6840aae24fd2c

**Comment by iNoles** [comment]
What is your Flutter version? 
```
flutter --version
```
on the Terminal

It is possible that your flutter version is not up to date.

**Comment by pstricks-fans** [comment]
See my updated question.

**Comment by pstricks-fans** [comment]
Updating the flutter sdk solved the problem.
