### ISSUE TITLE
[A11Y] Hybrid compositing webview: talkback item order not correct

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#68970]
b/171449547

I can swipe to navigate native flutter elements, and enter webview. However, order after is quite weird, not as expected. Back from webview does not go to appbar. Only way to access appbar is to go from last element -> first element.

See attached video in the internal bug.

**Comment by mehmetf** [comment]
Upgrading to P2. Customer:money is trying to move to hybrid compositing model and they are blocked by this.

**Comment by chinmaygarde** [comment]
cc @blasten: Are you blocked on this investigation?

**Comment by blasten** [comment]
@chinmaygarde b/171449547 contains the latest updates.

**Comment by chinmaygarde** [comment]
For tracking purposes here: The last update on the internal bug seems to indicate work in progress on a reduced test case.

**Comment by chinmaygarde** [comment]
The internal assignee is having trouble reproducing this issue. @blasten can you take a look at the query on the internal discussion on how to create a reduced test case?

**Comment by blasten** [comment]
This issue was fixed, and applied to g3
