### ISSUE TITLE
Found 0 newly paused isolate(s).

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#68990]
```
Updating files.
[ +675 ms] DevFS: Sync finished
[  +11 ms] Syncing files to device RMX1911... (completed in ٧٫٢s)
[  +56 ms] Synced 3.6MB.
[ +723 ms] <- accept
[   +5 ms] reloaded 21 of 1423 libraries
[ +406 ms] Reassembling application
[+2006 ms] This is taking a long time; will now check for paused isolates.
[ +998 ms] Found 0 newly paused isolate(s).
[+41574 ms] Ignoring terminal input: "r" because we are busy.
```

and then never accept any reload or restart command ...

this force me to kill the debug session and re-run the debug again ..

it happens after i updated flutter only yesterday ..

**Comment by pedromassangocode** [comment]
Hi @imeDevelopers 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
