### ISSUE TITLE
[proposal] avoid TextFormField.reset() to call setState() twice

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68997]
I was reviewing the `TextFormField` code and I found its `reset` code calls `setState`:

https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/material/text_form_field.dart#L346-L352

But before that, `reset` calls `super.reset()`, and this's the code for `super.reset()`:

https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/form.dart#L442-L450

So in the end there will be 2 calls to `setState()` from inside the `reset()` function.

Not a major bug or performance impact, but a minor improvement.

**Comment by pedromassangocode** [comment]
Cc @justinmc
