### ISSUE TITLE
sky.ColorFilter needs operator==

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#69]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:25 GMT_
_Originally opened as https://github.com/flutter/engine/issues/25_

----

_From @abarth on July 15, 2015 19:7_

When someone sets a sky.ColorFilter on either a ColorFilter widget or on an Image widget, we call operator== to check whether the filter has changed.  If it has changed, we mark ourselves as needing paint.  However, sky.ColorFilter doesn't implement operator==, which means we're just getting object identity, which means we're invalidating paint more often than necessary.

/cc @mpcomplete 

_Copied from original issue: domokit/mojo#324_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:25 GMT_

----

_From @eseidel on July 16, 2015 4:19_

Would be nice to be able to catch these errors in some way.  In obj-c one could override -[NSObject equals:] to warn using a "category".  I know dart doesn't have those, but maybe there is another solution we should use.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 05:05 GMT_

----

@abarth You said you were planning on changing how this works so that ColorFilter would be a pure Dart class, right? With the data sent over to the C++ in an efficient manner at the last minute?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Oct 26, 2015 at 05:24 GMT_

----

That's right.  The steps are:

- [ ] Start using the new binding system for `window`, replacing `view`.
- [ ] Switch the `Canvas` interface over to the new bindings system.
- [ ] Lift `Paint`-related classes up into Dart using the new bindings system.

**Comment by eseidelGoogle** [comment]
It looks like ColorFilter is still a wrapped native:
https://github.com/flutter/engine/blob/master/sky/engine/core/painting/ColorFilter.h

**Comment by abarth** [comment]
Fixed!
