### ISSUE TITLE
Using TextFiled problems

### ISSUE THREAD

**Issue by hjzlzh123** [flutter/flutter#69003]
Hello,there are some problems when I use TextFiled:
1. TextField is used and the number of input words is limited. And it works. However, when i type many times, there will be a problem. If delete with the soft keyboard, it will be deleted until the number of input times is satisfied. Is this a bug? Or how can I avoid this problem? 
2. Another problem is calling TextField Controller.clear (), how can I block the text disappearing animation just like Android native

**Comment by chinmoy12c** [comment]
Maybe this issue was fixed with #67892 . Please test it on master branch and see if you still face the same issue.

**Comment by pedromassangocode** [comment]
I can confirm that this was fixed by https://github.com/flutter/flutter/pull/67892.

The fix is currently on master and should land on next stable release.

**Comment by hjzlzh123** [comment]
Thank you for your feedback

**Comment by Ntu-odo** [comment]
Hi there !

@pedromassangocode When can we expect to get the next stable release ?

Thank you for your time.

**Comment by pedromassangocode** [comment]
There is no a fixed date for a new release.

Please see our release process https://github.com/flutter/flutter/wiki/Release-process.
