### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

### ISSUE THREAD

**Issue by mahee715** [flutter/flutter#69009]

**Comment by darshankawar** [comment]
@mahee715 
Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
Did you upgrade recently ? If so, what was the earlier version you upgraded from ?

**Comment by Leviosar** [comment]
I'm having the same problem, just tried to add web support for an existing app which uses package_info, it still works on Android and iOS but i can't run it on web.

Am i correct to just assume that this plugin doesn't support flutter web or it should be running normally?

Output of `flutter doctor -v`:

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\flutter
    • Framework revision 198df796aa (11 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Joao\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\Joao\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files (x86)\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.43

! Doctor found issues in 1 category.
```

**Comment by kurtDenuyo** [comment]
same issue here

**Comment by abdullah432** [comment]
Same issue
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = app.laguiadigital.mx, port = 35933`
After 5-second data is returned successfully, data is hosted on live server, on each api request I'm getting this error and after 5 seconds of wait data returned successfully

**Comment by MrCsabaToth** [comment]
This exact exception is happening for me release only (`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)`). Either this or something else causes the release build to hang after start with a blank white screen. EXTREMELY nagging, this is the third time over many month this happens. See also https://github.com/miguelpruivo/flutter_file_picker/issues/545

**Comment by jimmy-to-goldenowl** [comment]
> same issue here. working fine on IOS but not in android

same. every function call to android native will get this error

**Comment by MrCsabaToth** [comment]
> > same issue here. working fine on IOS but not in android
> 
> same. every function call to android native will get this error

In my case it turned out to be to eager class removal by R8 (ProGuard) and I was able to cure it by a couple of ProGuard rules
https://csaba.page/blog/the-dreaded-missing-plugin-exception.html

**Comment by jaredgreener** [comment]
> > > same issue here. working fine on IOS but not in android
> > 
> > 
> > same. every function call to android native will get this error
> 
> In my case it turned out to be to eager class removal by R8 (ProGuard) and I was able to cure it by a couple of ProGuard rules
> https://csaba.page/blog/the-dreaded-missing-plugin-exception.html
> 
> There are several tickets about this and they keep getting closed but it's very clear that developers and plugin developers are in distress.

Hello -- can you share exactly which R8 rules you added and where? Facing a similar issue...

**Comment by MrCsabaToth** [comment]
> > In my case it turned out to be to eager class removal by R8 (ProGuard) and I was able to cure it by a couple of ProGuard rules
> > https://csaba.page/blog/the-dreaded-missing-plugin-exception.html
> > There are several tickets about this and they keep getting closed but it's very clear that developers and plugin developers are in distress.
> 
> Hello -- can you share exactly which R8 rules you added and where? Facing a similar issue...

Right now I have more than the original two (one for the LifeCycle and one for flutter_blue) rules I had
```
-verbose
-keep class androidx.lifecycle.** { *; }
-keepclassmembers class * implements androidx.lifecycle.LifecycleObserver {
    <init>(...);
}
-keepclassmembers class * extends androidx.lifecycle.ViewModel {
    <init>(...);
}
-keepclassmembers class androidx.lifecycle.Lifecycle$State { *; }
-keepclassmembers class androidx.lifecycle.Lifecycle$Event { *; }
-keepclassmembers class * {
    @androidx.lifecycle.OnLifecycleEvent *;
}

-keep class com.pauldemarco.flutter_blue.** { *; }

-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
```
Not every of these rule might be needed, but I rather overdo it a little than miss something and be presented with a malfunction in the release. Also keep in mind that the `flutter_blue` part is specific to my app, you may not need it. I'll write a blog post about a generic solution: basically I'd take all the class paths from `GeneratedPluginRegistrant.kt` and add a rule for each plugin listed there. This is to be on the safe side.

**Comment by ayushgupta87** [comment]
In the main app file
import this"
from werkzeug.serving import WSGIRequestHandler

And before the app.run(...) :

WSGIRequestHandler.protocol_version = "HTTP/1.1"

**Comment by MrCsabaToth** [comment]
> In the main app file
> import this"
> from werkzeug.serving import WSGIRequestHandler
> 
> And before the app.run(...) :
> 
> WSGIRequestHandler.protocol_version = "HTTP/1.1"

Could you explain why? You cited some Python code. WSGI is the standardized web server portion of Python stacks, but I cannot fit it into Flutter desktop. However most Flutter solutions are still mobile (Android and iOS). So we deal with Dart, Java or Kotlin and iOS related languages.
