### ISSUE TITLE
when I have a pageView in ListView  , Scrollable.recommendDeferredLoadingForContext just like not work right；

### ISSUE THREAD

**Issue by genglei** [flutter/flutter#69008]
just when I have use pageView to show Image from netWork,and I alos see the flutter team has use ScrollAwareImageProvider to improve the preformance ,but when the pageView also in listView,it just like not work right ; 
 ListView.builder(
            controller: _controller,
            itemCount: list.length,
            itemBuilder: (context, i) {
              String url = list[i];
              return Container(
                height:386,
                width: 686 ,
                child: PageView.builder(
                    scrollDirection: Axis.horizontal,
                    itemBuilder: (context, index) {
                      return Image.network(
                        url,
                        width: 686,
                        height: 386,
                      );
                    }),
              );
            }),

**Comment by pedromassangocode** [comment]
Hi @genglei 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` a minimal complete reproducible code sample and the expected vs actual results?
Thank you

**Comment by genglei** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/genglei5/jd-flutter-sdk/flutter_1.17.5
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by pedromassangocode** [comment]
Hi @genglei 
You still need to upgrade Flutter. The latest stable version is 1.22.2!

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
