### ISSUE TITLE
SelectableText sometimes show selection handles on Flutter Web

### ISSUE THREAD

**Issue by znjameswu** [flutter/flutter#69001]
## Before you read
This "should" be an issue of the gesture detector. But a satisfying demo for GestureDetector takes too long time to write, I just use a `SelectableText` for the demo purpose.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: SelectableText('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', style: TextStyle(fontSize: 50)),
        ),
      ),
    );
```

Try this demo on DartPad (Flutter 1.23.0-18.1.pre Dart SDK 2.10.2. Chrome): https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

1. Select any text by dragging IMMEDIATELY and AS FAST AS POSSIBLE after press down the mouse button
2. If you are not doing it fast enough, refresh the window.

**Expected results:** 
No selection handles on web.

**Actual results:** 
If you drag fast enough, selection handles will appear.

The following demos the action: fast selection -> fast selection -> slow selection -> fast selection -> fast selection

![chrome-capture](https://user-images.githubusercontent.com/61373469/97121997-c4c9a700-16df-11eb-923a-942833a35a72.gif)

### Cause of this bug
Appearance of the selection handles is controlled by https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L895

This variable should be set to false in the tapdown handler.
https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L916-L927

Gesture detector promised to trigger `onTapDown` even if this is a long press.
https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L1180-L1183

But in my debugging experience, if you drag fast enough, `onTapDown` will not be triggered. So `showSelectionHandle` will not be set to false.

I suspect the longpress gesture recognizer declared the victory way too fast.

**Comment by pedromassangocode** [comment]
I was able to reproduce this issue on Dartpad as well.

![Screen Shot 2020-10-26 at 08 07 41](https://user-images.githubusercontent.com/67424416/97143166-6db8e600-1762-11eb-85da-215a524c40d9.png)

**Comment by xu-baolin** [comment]
I am currently working on this.

**Comment by znjameswu** [comment]
I think we should also do some thing about the description in https://github.com/flutter/flutter/blob/bced0351aedd719f65429d02b0baa8c8653342ea/packages/flutter/lib/src/widgets/text_selection.dart#L1180-L1183

because the onTapDown are not actually guaranteed to fire in a long press. Maybe we should open up a new issue regarding the gesture system? @xu-baolin
