### ISSUE TITLE
I am trying to use Geolocator package in my app amd tried to print the location. But its not displaying anything.
Location service is enabled in android emulator, still its showing that the location service is disabled.

### ISSUE THREAD

**Issue by RohitDhingra27** [flutter/flutter#69006]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@RohitDhingra27 
geolocator is a 3rd party plugin. Please consider opening this issue in plugin owner's repo : https://github.com/Baseflow/flutter-geolocator/issues.
Closing this as not an issue with Flutter. If you think otherwise, write in comments and I'll reopen.
Thanks.
