### ISSUE TITLE
Google map in flutter doesn't appear

### ISSUE THREAD

**Issue by tarektaamali** [flutter/flutter#69012]
I have problem with Google map in flutter 

- flutter version

> flutter122 --version
> Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 84f3d28555 (il y a 10 jours) • 2020-10-15 16:26:19 -0700
> Engine • revision b8752bbfff
> Tools • Dart 2.10.2

-plugin map version

>   google_maps_flutter: ^1.0.3

 **The bug is when navigate between pages of my app and move app to background ,after that i resume app ,The result 
  sometimes  the map disapear .**

<img width="230" height="500" src="https://user-images.githubusercontent.com/17914433/97149536-2be16d00-176d-11eb-9eb1-2a92177452f3.png">

**Comment by tarektaamali** [comment]
@iapicca

**Comment by tusharojha** [comment]
Hi @tarektaamali 
Have you added the google maps API key in `AndroidManifest.xml`?

**Comment by tarektaamali** [comment]
@tusharojha yes i added and map it's work,but this problem happened only when navigate between page and move the app in the background of the system , and reopen (resume) the app sometimes appear this problem . 

![Screenshot_20201026-105132 (1)](https://user-images.githubusercontent.com/17914433/97158229-6fda6f00-1779-11eb-8e60-fc13bac85d39.png)

**Comment by pedromassangocode** [comment]
Hi @tarektaamali 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by tarektaamali** [comment]
> [✓] Flutter (Channel stable, 1.22.2, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.22.2 at /home/bilel/Bureau/FlutterSDK/flutter122/flutter
    • Framework revision 84f3d28555 (il y a 10 jours), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bilel/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bilel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.5)
    • Android Studio at /home/bilel/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Mi A3 (mobile)                     • 0bf622c3c2bb  • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 6.0 (API 23) (emulator)

**Comment by tarektaamali** [comment]
when I try this workground [https://stackoverflow.com/questions/59374010/flutter-googlemap-is-blank-after-resuming-from-background/59435683#59435683](url)  .the problem not happened ,it's temporiry fixed .

**Comment by pedromassangocode** [comment]
Hi @tarektaamali 
I see there's an open issue (https://github.com/flutter/flutter/issues/40284) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
