### ISSUE TITLE
Debug-only Crash on startup with Xiaomi Mi5

### ISSUE THREAD

**Issue by lohmander** [flutter/flutter#6901]
## Steps to Reproduce

I'm trying to run the default startup project on a Xiaomi Mi5, but it crashes upon startup. I realise that you probably don't test on Xiaomi devices, but maybe you could point me in the right direction to get this running. 

Android version: 6.0.1
MIUI: 8.1.2.0

```
▶ flutter --version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 9cb914df17 (12 hours ago) • 2016-11-16 17:19:00
Engine • revision cea5ed2b9b
Tools • Dart 1.21.0-dev.6.0
```

### flutter run
```
Installing build/app.apk...                         5011ms
Timed out while waiting for a debug connection.
Error launching DevFS loader on MI 5.
```

### logcat
```
                   libc  F  Fatal signal 4 (SIGILL), code 1, fault addr 0xdc155584 in tid 5771 (ui_thread)
                  DEBUG  F  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
                         F  Build fingerprint: 'Xiaomi/gemini/gemini:6.0.1/MXB48T/V8.1.2.0.MAAMIDI:user/release-keys'
                         F  Revision: '0'
                         F  ABI: 'arm'
                         F  pid: 5749, tid: 5771, name: ui_thread  >>> com.yourcompany.testflutter <<<
                         F  signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xdc155584
                         F      r0 000003e8  r1 00000000  r2 dc155560  r3 dd03f930
                         F      r4 dd1817b9  r5 dc006529  r6 dc007051  r7 dd03f078
                         F      r8 dd181ac4  r9 dc006509  sl eee2a100  fp dd03f08c
                         F      ip 000007d0  sp dd03f074  lr dc1552f8  pc dc155584  cpsr 200d0010
                         F  backtrace:
                         F  #00 pc 00015584  <unknown>
                         F  #01 pc 000152f4  <unknown>
      WtEventController  I  Receive am_crash event for pid: 1503
                  DEBUG  F  Tombstone written to: /data/tombstones/tombstone_02
                         E  AM write failed: Broken pipe
        ActivityManager  W    Force finishing activity com.yourcompany.testflutter/org.domokit.sky.shell.SkyActivity
              octvm_klo  I  get event file: /data/tombstones/tombstone_02
                         I  klo lock
           BootReceiver  I  Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
        ActivityManager  E  Invalid thumbnail dimensions: 0x0
    WtProcessController  D  onAMPauseActivity callback
              octvm_klo  I  start gathering logcat log...
          GraphicsStats  D  Buffer count: 8
                 Zygote  I  Process 5749 exited due to signal (4)
        InputDispatcher  W  channel 'aec6349 com.yourcompany.testflutter/org.domokit.sky.shell.SkyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
                         E  channel 'aec6349 com.yourcompany.testflutter/org.domokit.sky.shell.SkyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
            WindowState  I  WIN DEATH: Window{aec6349 u0 com.yourcompany.testflutter/org.domokit.sky.shell.SkyActivity}
        InputDispatcher  W  Attempted to unregister already unregistered input channel 'aec6349 com.yourcompany.testflutter/org.domokit.sky.shell.SkyActivity (server)'
            WindowState  I  WIN DEATH: Window{dc03bb0 u0 SurfaceView}
           DpmTcmClient  I  RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
         BoostFramework  V  BoostFramework() : mPerf = com.qualcomm.qti.Performance@857f63f
                         V  BoostFramework() : mPerf = com.qualcomm.qti.Performance@e353b0c

                            Process com.yourcompany.testflutter (PID: 5749) ended
```
## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/hanneslohmander/SDK/flutter
    • Framework revision 9cb914df17 (12 hours ago), 2016-11-16 17:19:00
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/hanneslohmander/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

**Comment by eseidelGoogle** [comment]
Would you be willing to attach `/data/tombstones/tombstone_02`?  That will contain the full crash stack.

**Comment by lohmander** [comment]
I actually haven't rooted the device (so I'm unable to pull the tombstone) and do not have access to any PC at to moment to root it right now. Wasn't able to find any good advice on how to root it I will try to do it within the next couple of days though...

**Comment by lohmander** [comment]
Also, everything works fine when running it in release mode.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/6457 is another debug-only crash.

**Comment by eseidelGoogle** [comment]
@rmacnak-google @jason-simmons we have one of these phones available in the central lab if you'd like to debug.  Presumably this is another jit-only crash.  This is a very modern phone: http://www.gsmarena.com/xiaomi_mi_5-6948.php

**Comment by joeblew99** [comment]
BTW does the team have a markdown page for phones tested to be able to run flutter and debug flutter ? 

It would be useful for devs and their enterprise customers in making purchasing decisions.

**Comment by eseidelGoogle** [comment]
We do not yet have a whitelist of phones known to work well, but we're working on building out our testing so we could produce something like that.  This specific issue should be fixed today.  The fix has been committed, it just has to wait to roll into Flutter from Dart.

**Comment by joeblew99** [comment]
@eseidel ok thanks for the update . Nice.

**Comment by lohmander** [comment]
Haven't had time to play more with flutter until now. Anyways, after upgrading everything works smoothly!

**Comment by eduardkieser** [comment]
I have the same problem with Redmi 4A and Redmi Note 4 (Works fine on galaxy S5 and One plus 5)
```
flutter --version
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58
```
```
flutter run
Launching lib/main.dart on Redmi 4A in debug mode...
Initializing gradle...                                       0,9s
Resolving dependencies...                                    1,4s
Running 'gradlew assembleDebug'...                           7,6s
Built build\app\outputs\apk\debug\app-debug.apk.
```
White screen appears and disappears on phone, then nothing. Running from intellij and I can't seem to get more debugging info. Android monitor asks me to please configure SDK and Dart Analysis has nothing to show.
Do have any advice for me?

**Comment by eseidelGoogle** [comment]
@eduardkieser it looks like this bug has already been closed.  Would you be willing to file a new bug with the above info?  I don't want your report to get lost!
