### ISSUE TITLE
in app purchase issue with paypal 

### ISSUE THREAD

**Issue by nitneuq33** [flutter/flutter#69029]
Hello, all my users who make in app purchase with paypal have issue... the purchase finished and my users received google bill but my product isn't delivered. All works ok with normal purchase, but not with paypal...

I use the exact example from flutter in app purchase package, just finish with the add of my product if all is validate. 

thank you

**Comment by darshankawar** [comment]
@nitneuq33 
This seems to be an issue with paypal services and not with the plugin, since the plugin is used to buy digital goods from google and play store. 
Please check with paypal integration. I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.
