### ISSUE TITLE
When not using TabBar in AppBar rendering fails: The following NoSuchMethodError was thrown during performLayout(): The method 'toStringAsFixed' was called on null

### ISSUE THREAD

**Issue by joeyda3rd** [flutter/flutter#69035]
It seems that the TabBar needs to have space reserved for it on the render tree, if you're not putting it on the bottom of an AppBar. Couldn't find that anywhere in docs. If I just see didn't it, then I apologize.  I don't know if this is a bug, but I couldn't find the answer in the documentation and it was difficult to solve. Putting it here for posterity and maybe it needs better documentation or error handling. 

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The method 'toStringAsFixed' was called on null.
Receiver: null
Tried calling: toStringAsFixed(1)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ViewportOffset.debugFillDescription (package:flutter/src/rendering/viewport_offset.dart:248:39)
#2      ScrollPosition.debugFillDescription (package:flutter/src/widgets/scroll_position.dart:896:11)
#3      ScrollPositionWithSingleContext.debugFillDescription (package:flutter/src/widgets/scroll_position_with_single_context.dart:261:11)
#4      ViewportOffset.toString (package:flutter/src/rendering/viewport_offset.dart:233:5)
```

## Steps to Reproduce

Place a TabBar outside of App Bar in any fashion, I've placed it in a column row below.

```dart
class _ReferralsNestedTabViewState extends State<ReferralsNestedTabView>
    with TickerProviderStateMixin {
  TabController _nestedTabController;
  int _index;

  @override
  void initState() {
    super.initState();
    _nestedTabController = TabController(
      length: 2,
      vsync: this,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TabBar(
          onTap: (index) {
            _nestedTabController.index = index;
          },
          controller: _nestedTabController,
          indicatorColor: Colors.blue,
          labelColor: Colors.blue,
          unselectedLabelColor: Colors.black54,
          isScrollable: true,
          tabs: [
            Tab(text: 'Tab 1'),
            Tab(text: 'Tab 2'),
          ],
        ),
        Container(
//          height: MediaQuery.of(context).size.height * .70,       //<---- adding size to other row in 2 row column solves the render issue
          child: TabBarView(controller: _nestedTabController, children: [
            ReferralListView(),
            GuestListView(),
          ]),
        ),
      ],
    );
  }
}

```

**Expected results:** 

A TaBar displayed in column row

**Actual results:** 

No TabBar, but the problem was solved by defining the height of the container taking its space creating a void for it to render in.

**Comment by darshankawar** [comment]
@joeyda3rd 
Please check [this](https://github.com/flutter/flutter/issues/17459) issue and corresponding solution on how to use tabbar without appbar.
Hope it helps.

**Comment by joeyda3rd** [comment]
This technically does work, but doesn't solve the problem of removing the TabBar from the AppBar, if it's required there, then that's acceptable, just needs documented. There is currently no way to remove tabbar from appbar without requiring a manually sized void from other widgets rendered in the space it would normally occupy if it would reserve it's own space. 

Title of this issue should read "When not using TabBar in AppBar rendering fails: The following NoSuchMethodError was thrown during performLayout(): The method 'toStringAsFixed' was called on null"

**Comment by sm2017** [comment]
@darshankawar @joeyda3rd  I have similar problem I want to show tab bar in middle of page without appbar my `TabBarView` crashed with 

```
The following NoSuchMethodError was thrown during performLayout():
The method 'toStringAsFixed' was called on null.
Receiver: null
Tried calling: toStringAsFixed(1)
```

Why the following code not works?


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          body: Column(
            children: [
              TabBar(
                tabs: [
                  Tab(icon: Icon(Icons.directions_car)),
                  Tab(icon: Icon(Icons.directions_transit)),
                  Tab(icon: Icon(Icons.directions_bike)),
                ],
              ),
              TabBarView(
                children: [
                  Icon(Icons.directions_car),
                  Icon(Icons.directions_transit),
                  Icon(Icons.directions_bike),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by joeyda3rd** [comment]
This is the problem. I can't get any code to work without declaring a size for the widget under the tabbar that will leave space for the tab bar to fill. 

Try this package a friend of mine made, it's new and still needs some work, but it may solve the problem for you. 
https://pub.dev/packages/contained_tab_bar_view

**Comment by kurzekar-rohit** [comment]
Wrap your TabBarView in the Expanded widget.  This resolves my issue.

**Comment by normancarcamo** [comment]
@kurzekar-rohit in my use case it doesn't apply because I'm on a list of slivers.
```sh
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while applying parent data.:
flutter: Incorrect use of ParentDataWidget.
flutter: The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a
flutter: RenderObject, which has been set up to accept ParentData of incompatible type
flutter: SliverPhysicalParentData.
flutter: Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically,
flutter: Expanded widgets are placed directly inside Flex widgets.
flutter: The offending Expanded is currently placed inside a SliverToBoxAdapter widget.
flutter: The ownership chain for the RenderObject that received the incompatible parent data was:
flutter:   _ScrollSemantics-[GlobalKey#3b293] ← Scrollable ← NotificationListener<ScrollNotification> ←
flutter: PageView ← NotificationListener<ScrollNotification> ← TabBarView ← Expanded ← Container ←
flutter: SliverToBoxAdapter ← Viewport ← ⋯
```

**Comment by normancarcamo** [comment]
@kurzekar-rohit **update** in my use-case it works if I wrap it into a `SliverFillRemaining` yay!.

**Comment by davorkomusanac** [comment]
> Wrap your TabBarView in the Expanded widget. This resolves my issue.

Thank you, been searching all over for how to implement a TabBar outside an AppBar, and kept playing a whack-a-mole with issues, fix one, another pops up, until I finally solved it.

**Comment by saadamin94** [comment]
@sm2017 Just wrap your TabBarView with an Expanded widget. It's tested to work.

```dart
void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          body: Column(
            children: [
              TabBar(
                tabs: [
                  Tab(icon: Icon(Icons.directions_car)),
                  Tab(icon: Icon(Icons.directions_transit)),
                  Tab(icon: Icon(Icons.directions_bike)),
                ],
              ),
              Expanded(
                child: TabBarView(
                  children: [
                    Icon(Icons.directions_car),
                    Icon(Icons.directions_transit),
                    Icon(Icons.directions_bike),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by saadamin94** [comment]
@joeyda3rd I had the same issue but with AppBarView. The following is an excerpt from my code where I have the TabBar somewhere in the body.
The key is to wrap your Column and TabBarView in Expanded so that it resolves the height of the parent Flex (which I am guessing is another Column)

```dart
DefaultTabController(
              length: 2,
              child: Expanded(
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  children: <Widget>[
                    Container(
                      child: TabBar(
                        tabs: [
                          Tab(text: "Home"),
                          Tab(text: "Articles"),
                        ],
                      ),
                    ),
                    Expanded(
                      child: Container(
                        constraints: BoxConstraints.expand(),
                        child: TabBarView(children: [
                          Center(
                            child: Text(
                              "Home Body",
                              style: TextStyle(color: Colors.white),
                            ),
                          ),
                          Center(
                            child: Text(
                              "Articles Body",
                              style: TextStyle(color: Colors.white),
                            ),
                          ),
                        ]),
                      ),
                    ),
                  ],
                ),
              ),
            )```

**Comment by pumuckelo** [comment]
> @kurzekar-rohit **update** in my use-case it works if I wrap it into a `SliverFillRemaining` yay!.

Omg thank you so much, this also works in CustomScrollView for example

**Comment by pumuckelo** [comment]
nvm, now the TabBarView doesn't have an unlimited height. Does anyone know how to give a TabBarView inside of a CustomScrollView enough height for the children?

**Comment by normancarcamo** [comment]
@pumuckelo I don't know what you're trying to compose, but I have an example for you:
https://gist.github.com/normancarcamo/031191ccd2eb2f4c2878c588db506e76

**Comment by pumuckelo** [comment]
Thank you for the quick response! 

What I am trying to do is to render a TabBarView and the TabBar inside of a CustomScrollView. 

I'll a code example tomorrow, I'm on my phone rn.

**Comment by normancarcamo** [comment]
@pumuckelo I think the example I did does what you are looking for, if not :) good luck.

**Comment by pumuckelo** [comment]
@normancarcamo in the example, you have a CustomScrollView inside of a TabBarView. What I am trying to achieve is the opposite, to have TabBarView inside of a CustomScrollView. 

Your info to use SliverFillRemaining helped me to fix the "toStringAsFixed" error but now I got the problem that the tabbarview inside of the customscrollview only gets the size of the screen as height so it overflows on the bottom if the content is larger

**Comment by normancarcamo** [comment]
@pumuckelo I understand you, good luck bro!.

**Comment by joeyda3rd** [comment]
@saadamin94 is correct, wrapping in expanded widget resolves the height of the parent.
