### ISSUE TITLE
Set and retrieve SkyShell window size

### ISSUE THREAD

**Issue by brnndnn** [flutter/flutter#6903]
Looking for these capabilities with regards to window size:
- programmatically set the window size on launch (from Dart)
- keep track of window size changes (in Dart) in order to be able to restore window size on subsequent launches

**Comment by brnndnn** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
> keep track of window size changes (in Dart) in order to be able to restore window size on subsequent launches

This has already been implemented in the Desktop shell. Do you have the latest `SkyShell.app` on Mac? https://github.com/flutter/engine/pull/3215 was a change to an interface builder file.

> programmatically set the window size on launch (from Dart)

I'll add this functionality as a plugin.

**Comment by brnndnn** [comment]
Tested, the updated SkyShell achieves what we need. (No need to track and restore if the size gets automatically restored). Thanks!
