### ISSUE TITLE
Add flutter tool support for building the local engine

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#69036]
When developing for tool, flutter will automatically recompile the tool when a new SHA is present in the repository.  We should do something similar for the engine.

Imagine you could say `flutter install-local-engine ~/path-to-engine --ios --runtime-mode debug --unoptimized --simulator`.  Then flutter will download the engine source, gn, repo tools, ninja, and start compiling the engine, then point flutter to use that built engine when it is complete.  Then it will trigger recompiles if it detects new SHAs like we do for the tool.

For Windows, it will be a bit more complicated but we could make something work.

This isn't a problem for engine developers but it is a problem when we ask people who are not engine developers to help debug engine problems.  It would also make the barrier of entry for engine development lower.

**Comment by jonahwilliams** [comment]
This would imply a circular dependency between the tooling and the engine - changes to the engine build scripts could break this tooling workflow.

**Comment by christopherfujino** [comment]
Yeah, I don't think the tool should know about gn flags or even the exact build dependencies. I think it would be worth creating tooling in the engine to bootstrap the dev environment. And then we could add a script in the framework like, `dart ./setup_local_engine.dart --engine-path $HOME/dev/flutter-engine` that clone the engine and then run the engine's environment bootstrap script.

**Comment by gaaclarke** [comment]
> This would imply a circular dependency between the tooling and the engine - changes to the engine build scripts could break this tooling workflow.

This is a workflow that engine developers use already.  It just would automate the process.

> I don't think the tool should know about gn flags or even the exact build dependencies

It would have to if you wanted it to be able to compile the engine.

It would also be nice if the tool had a way to permanently select which engine you are using.  Right now if you use the `--local-engine` flags it does get cached locally but the next time you use flutter without it, it gets wiped out.  You wouldn't want that to happen if you've installed the local engine.

```
$ flutter install-local-engine --select
[0] builtin (current)
[1] ~/dev/engine/out/ios_profile
[2] ~/dev/engine/out/android_debug_unopt
```

**Comment by christopherfujino** [comment]
> > I don't think the tool should know about gn flags or even the exact build dependencies
> 
> It would have to if you wanted it to be able to compile the engine.

I guess my concerns would not be applicable if we just blindly passed the flags to gn. But I still don't think that the tool should know anything about the engine's build deps, and should instead call a script in the engine that handles that.

**Comment by jonahwilliams** [comment]
This will/should be covered by the new engine tool
