### ISSUE TITLE
Dashboard commits are not updating

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69039]

**Comment by keyonghan** [comment]
Hit this when refreshing github commit:

```
GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:400:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:36:33)
<asynchronous suspension>
#3      GithubService.listCommits (package:cocoon_service/src/service/github_service.dart:38:54)
#4      RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:70:66)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
```

**Comment by keyonghan** [comment]
Something wrong when fetching commits of branch: `experimental_skshaper`. 
workaround to skip that branch to make the dashboard rolling.

Still looking at the `experimental_skshaper` branch issue.

**Comment by keyonghan** [comment]
This is caused by missing branch experimental_skshaper in github flutter/flutter, whereas that branch is still in cocoon: https://github.com/flutter/cocoon/blob/master/app_dart/dev/branches.txt. The backend is trying to fetch commits of that branch, which doesn't exist anymore.

**Comment by jason-simmons** [comment]
experimental_skshaper should not have been deleted.  I've repushed it to flutter/flutter.

**Comment by keyonghan** [comment]
Fix got pushed to latest cocoon.
