### ISSUE TITLE
dev/bots/analyze-sample-code.dart failing with NNBD flag flip

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#69042]
See the failure here https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865360821001700848/+/steps/flutter_analyze/0/stdout, this is the `flutter analyze` step of the `flutter-engine-linux-try` bot.

It looks like this is failing because the samples are being opted in.

Marking as a P1 since this will be blocking the 2.12 release.

**Comment by jakemac53** [comment]
This is still failing it looks like, but on different samples https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865278440977658192/+/steps/flutter_analyze/0/stdout

**Comment by jonahwilliams** [comment]
I think https://github.com/flutter/flutter/pull/69122 should have fixed the rest, please LMK if that is not the case

**Comment by jakemac53** [comment]
it looks good now thanks :)
