### ISSUE TITLE
Disable the Dart profiler by default and allow enabling it via a flag to the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#6904]
Currently, the Dart profiler is disabled on all platforms where LLDB is the default debugger. This is because the signals generated during profiling cause LLDB to be overwhelmed and make the application unresponsive while it is being debugger, and in rare cases, cause the Xcode IDE to crash.

Users are encouraged to launch the application once from Xcode to make sure their code signing and entitlements are correctly setup. Xcode launched the application with LLDB attached. So enabling the profiler by default and expecting the tools to never connect via LLDB (which they don't)  will lead to a poor experience on first launch for the user.

Possible solutions:
* Disable the profiler on all platforms. Allow it to be enabled via a flag (tentatively `--enable-dart-profiler`). The tools must then pass in the flag explicitly when they launch the application (when they can be sure no native debugger is attached).
* Always enable the profiler on all platforms. Except, detect the case in the engine when a debugger is attached and disable the profiler at runtime.
* Fix the issue in LLDB. I have investigated this a lot but am no closer to a fix.

I think the first one is easy to get done.

cc @johnmccutchan

**Comment by Hixie** [comment]
It is sad that we are making profiling harder. Profiling is a core part of making fast apps and that's one of our core values.

**Comment by chinmaygarde** [comment]
> It is sad that we are making profiling harder.

We are actually enabling profiling on iOS at all. Before this, it was unconditionally disabled.

**Comment by Hixie** [comment]
This does affect Android too, though, right?

**Comment by johnmccutchan** [comment]
Yeah, I don't want to disable the profiler for default on Android where it causes no issues. For iOS the flag can enable it there. We should also file an issue about this lldb problem against flutter that references the upstream lldb bug report so we remember to turn it on by default for iOS again

**Comment by chinmaygarde** [comment]
> Yeah, I don't want to disable the profiler for default on Android where it causes no issues.

The profiler will always be on when used with the tools on all platforms. Having different defaults on Android and iOS may become confusing IMO.

Are you thinking of workflows where the user may need the profiler but has not launched the application via the tools? If so, the different defaults might make sense.
