### ISSUE TITLE
Upload the SkyShell.app on Mac to cloud storage.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#6905]
Teams internally have been using the Mac `SkyShell.app` for development. But since we don't distribute the bundle (only the binary that is capable of running in both interactive and non-interactive modes), they acquired the bundle once and would symlink the latest binary from the tools. This is hacky but works as long as the bundle does not change (which it rarely does). It did change recently and they did not get the updates. We should just update the `SkyShell.app` to cloud storage. Even if the tools aren't wire up, the updated assets will still show up in `bin/cache`.

I realize this would mean the `precache` would need to download only extra archive, but I think we are cleaning that up to make it leaner anyway right? Whatever options we decide to use to control what we download later, we can add this extra bit too. For now, the archive size of quite small.

**Comment by abarth** [comment]
I don't think we should support this use case.
