### ISSUE TITLE
Expose the underlying StreamSubscription in StreamBuilder

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#69053]
## Use case

I have a StreamBuilder that displays asynchronous query results to the user in a ListView. I'd like to pause the query's stream when I don't need to display more results and resume it when the user scrolls to the bottom of the results fetched so far and more results need to be displayed.

Since StreamBuilder doesn't expose it's internal subscription ([see code](https://github.com/flutter/flutter/blob/d2858f00dd2f305ad59dde8acd3f347105f7f8fa/packages/flutter/lib/src/widgets/async.dart#L104)), users have to listen on the stream directly and forward it's values to a new StreamBuilder stream to be used in the StreamBuilder in order to access a pausable/resumable StreamSubscription. This is needless boilerplate that may not occur to many users.
See [stackoverflow](https://stackoverflow.com/questions/59597138/how-to-control-stream-start-pause-resume-in-streambuilder/64544638#64544638)

## Proposal

Expose the `_subscription` attribute in StreamBuilder so that users can pause and resume the StreamBuilder's underlying stream. Alternate, comparable, solutions:

- give StreamBuilder `pause` and `resume` methods that pause and resume the underlying stream (cancel too?)
- expose the StreamSubscription as an argument in StreamBuilder's builder function so that the stream can easily be paused or resumed from within the builder

**Comment by darshankawar** [comment]
@caseycrogers 
There's a similar open issue describing your case, [28117](https://github.com/flutter/flutter/issues/28117).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
