### ISSUE TITLE
Video player looping issue

### ISSUE THREAD

**Issue by Azzeccagarbugli** [flutter/flutter#69064]
I'm currently using the `video_player` plugin and everything is going perfectly fine. I would love to **loop a specific video but at the same time know when it's reach the end** so that I can trigger an action.

With the following snippet of code I'm just able to check when the video starts and ends for the first time but I **don't have** info about the others reproductions:
```dart
if (videoPlayerController.value.position == Duration()) {
      print('Video started');
}

if (videoPlayerController.value.position == videoPlayerController.value.duration) {
      print('Video ended');
}  
```

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.23.0-14.0.pre.128, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-14.0.pre.128 at /Users/azzeccagarbugli/dev/flutter
    • Framework revision 10c78c264a (2 weeks ago), 2020-10-12 12:51:37 -0700
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/azzeccagarbugli/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • GM1910 (mobile) • aacc598d • android-arm64 • Android 10 (API 29)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

• No issues found!
```
</details>

I hope that I was clear enough! Cheers 👋

**Comment by Calamity210** [comment]
@Azzeccagarbugli you can achieve this using the [seekTo](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerController/seekTo.html) method

**Comment by Azzeccagarbugli** [comment]
> @Azzeccagarbugli you can achieve this using the [seekTo](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerController/seekTo.html) method

With this method I would be able to set the video at a specific timestamp **but is not** what I'm looking for. I want to know when a video ends even if the looping option is active and I still didn't find a way to do it...

**Comment by darshankawar** [comment]
@Azzeccagarbugli 
Check [this](https://flutter.dev/docs/cookbook/plugins/play-video) official documentation on video_player and how to loop a video.

**Comment by Azzeccagarbugli** [comment]
> @Azzeccagarbugli 
> Check [this](https://flutter.dev/docs/cookbook/plugins/play-video) official documentation on video_player and how to loop a video.

I already checked the documentation and I'm still not able to achieve what I suggested, so I'm guessing that at the current state of the plugin this is not possible but I would rather prefer to be wrong 😅

**Comment by soulwriter** [comment]
Video_player has a loop function. You may set it to true during video_player controller initialization.

` late final VideoPlayerController _controller;
  late Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    _controller = VideoPlayerController.asset('assets/videos/reversed.mp4')..setLooping(true);
    _initializeVideoPlayerFuture = _controller.initialize();
    super.initState();
  }`
