### ISSUE TITLE
wifi_info_flutter  android channel name error

### ISSUE THREAD

**Issue by LaoHuan** [flutter/flutter#69073]
Android Native Code use    "plugins.flutter.io/wifi_flutter_info"
but 
flutter use  "plugins.flutter.io/wifi_info_flutter"

**Comment by darshankawar** [comment]
@LaoHuan 
Is it causing any error or unexpected behavior if channel name differs in Flutter ?

**Comment by LaoHuan** [comment]
> @LaoHuan
> Is it causing any error or unexpected behavior if channel name differs in Flutter ?

Calling getBSSID on Android will give you an error。

**Comment by bobatsar** [comment]
I just hit the same bug. When will the updated wifi_info_flutter 1.0.1 be published?

One small addition, the README tells to use `WifiFlutter()...` but in the implementation it is `WifiInfo()...`

**Comment by bparrishMines** [comment]
@bobatsar it should be published now
