### ISSUE TITLE
Ability to use ExpansionTile as Sliver inside of CustomScrollView

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#69084]
I can't use ExpansionTile as Sliver inside of CustomScrollView

Example of usage:

ListView -> ExpansionTile -> ListView -> Card

Without Sliver we have to use shrinkWrap and render entire ExpansionTIle with all items inside of it.

https://drive.google.com/file/d/10l5-kVmbpyQz18nMTlHUrnhCsZsfjHR9/view?usp=sharing

**Comment by pedromassangocode** [comment]
Hi @sanekyy 
Can you please share a minimal reproducible code sample and the actual vs expected results?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
