### ISSUE TITLE
Ignoring Files when Publishing - gitignore doesn't work

### ISSUE THREAD

**Issue by TheHighriser** [flutter/flutter#69090]
I have searched through the issues already and I don't find anything. Either I am doing something completely wrong or this wasn't used by anyone.

I am trying to exclude certain things from publishing. So e.g. I am trying to exclude the folder "pleaseIgnoreMe/". So I will enter "pleaseIgnoreMe/" into the .gitignore file. When doing a publish --dry-run, I can still see the folder "pleaseIgnoreMe". I then tried to do a normal publish, because I though maybe this is not working for --dry-run and exclude a folder which was not needed and it still is not working. The published artifact has "pleaseIgnoreMe". 

The documentation says the only way is the .gitignore file (https://dart.dev/tools/pub/publishing#what-files-are-published). Is this working for anybody?

**Comment by TahaTesser** [comment]
Hi @TheHighriser 
This is not related to flutter repository,  this is related to pub publish 
Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub-dev/issues).
Closing, as this isn't an issue with Flutter itself.  
Thank you
