### ISSUE TITLE
reversed ListView.builder inside NestedScrollView's body argument reverses scroll direction

### ISSUE THREAD

**Issue by miruts** [flutter/flutter#69098]
I have ListView.builder inside NestedScrollView's body argument, but when setting reverse to true, scrolling up goes down and scrolling down goes up

## Steps to Reproduce

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Slivers',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: TestNestedScrollView(),
    );
  }
}
class TestNestedScrollView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (context, isInnerScrolled) {
          return [
            SliverAppBar(
              expandedHeight: 200,
              pinned: true,
              flexibleSpace: FlexibleSpaceBar(
                title: Text('NestedScrollView'),
              ),
            )
          ];
        },
        body: ListView.builder(
          itemBuilder: (context, index) {
            return Container(
              height: 75,
              alignment: Alignment.center,
              color: Colors.purple[100 + (index % 9) * 100],
              child: Text('Item: $index'),
            );
          },
          reverse: true,
        ),
      ),
    );
  }
}
```
</details>

1. Run the app on a device
2. Scroll the ListView either up or down
3. Notice scrolling up goes down and scrolling down goes up 

## Logs
Flutter Doctor output
>flutter doctor -v
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.1 at C:\NewFlutter\flutter
    • Framework revision f30b7f4db9 (3 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\miruts\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\miruts\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM A105F (mobile) • RZ8M40WMMHY • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
I was able to reproduce this on latest stable channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.81, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-4.0.pre.81 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 05ab0eba19 (9 hours ago), 2020-10-26 19:22:25 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 913ADC1E-400E-4AA0-8302-D955869FF1C9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by Piinks** [comment]
Hi @mirtus this appears to be a duplicate of https://github.com/flutter/flutter/issues/39134 which was closed as working as intended.

The NestedScrollView is predicated on the fact that the inner and outer scroll views share the same scroll direction. The NestedScrollView itself has a reverse property you can set, but the scroll views cannot operate in different directions. There is a discussion about this in #39134 along with some suggestions in solving common design patterns that give the appearance of the desired effect.

Let me know if that solves the issue you are having. Thank you!

**Comment by miruts** [comment]
okay thanks @Piinks
