### ISSUE TITLE
Need Platform.isFuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6911]

**Comment by abarth** [comment]
Way ahead of you, but with bad news: https://github.com/dart-lang/sdk/issues/27103

**Comment by sethladd** [comment]
Can Fuchsia / Flutter inject something into the "environment" via the embedder, so you can do something like `bool.fromEnvironment('platform.fuschia')` ?

See https://api.dartlang.org/stable/1.20.1/dart-core/bool/bool.fromEnvironment.html
