### ISSUE TITLE
AutoFill unexpected behavior; TextInput.finishAutofillContext() doing nothing; Cannot save user input

### ISSUE THREAD

**Issue by hawkinsjb1** [flutter/flutter#69111]
I am attempting to use an Autofill service for my login screen and the behaviour has been inconsistent, especially across services.

I wanted to use the Google Autofill service primarily for testing, but when I do, `TextInput.finishAutofillContext()` **never** prompts the user. Instead when I use LastPass, `TextInput.finishAutofillContext()` usually prompts the user (though sometimes it doesn't) however LastPass doesn't recognize the (email, username) hints and instead only the password.

I realize each Autofill service may behave differently, but I have yet to find a fully working (save + grouped email/password) implementation. 

This is a simplified version of what I'm trying to do:

```
  return AutofillGroup(
    child: Column(
      children: [
        TextField(
          autofillHints: [
            AutofillHints.email,
            // AutofillHints.username,
          ],
          keyboardType: TextInputType.emailAddress,
          textInputAction: TextInputAction.next,
        ),
        TextField(
          autofillHints: [
            AutofillHints.password,
          ],
          keyboardType: TextInputType.visiblePassword,
          textInputAction: TextInputAction.done,
          obscureText: true,
          onSubmitted: (_) =>
              TextInput.finishAutofillContext(shouldSave: true),
        ),
      ],
    ),
  );
```

Flutter Doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-4.0.pre.64, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.0)
[√] Connected device (4 available)
```

@LongCatIsLooong keying you in, as I've seen you across multiple related threads

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: AutofillGroup(
          child: Column(
            children: [
              TextField(
                autofillHints: [
                  AutofillHints.email,
                  // AutofillHints.username,
                ],
                keyboardType: TextInputType.emailAddress,
                textInputAction: TextInputAction.next,
              ),
              TextField(
                autofillHints: [
                  AutofillHints.password,
                ],
                keyboardType: TextInputType.visiblePassword,
                textInputAction: TextInputAction.done,
                obscureText: true,
                onSubmitted: (_) =>
                    TextInput.finishAutofillContext(shouldSave: true),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.107, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.107 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 35a94f70e1 (68 minutes ago), 2020-10-27 23:47:04 -0700
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • iPhone 12 (mobile) • BAFAB765-173F-4B78-93AC-F6FB6E6783C3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by hawkinsjb1** [comment]
@TahaTesser Can confirm my issue is happening running that exact code sample. I downgraded to stable 1.22.2, and seeing the same behaviour.

Also, I'm only explicitly calling `.finishAutofillContext()` because the automatic prompt upon group disposal isn't happening, granted i'm not manually disposing the AutoFillGroup, i'm still replacing the screen which should handle the disposal and prompt the user.

Is anyone else even having these problems? If so this is a pretty big issue since i'm in stable and nothing is really acting as expected.

**Comment by srcnysf** [comment]
same here. iOS can not askin to save credentials

**Comment by LongCatIsLooong** [comment]
@srcnysf password save on iOS does not work out-of-box. You need to set the associated domains for the app: https://developer.apple.com/documentation/security/password_autofill.

**Comment by srcnysf** [comment]
@LongCatIsLooong thanks for the info. Is there any release date for that or is it under dev?

**Comment by srcnysf** [comment]
@LongCatIsLooong although i am setting associated domains, when I come the login it not prefers my related credentials at the top of the keyboard. It only shows passwords so I can click and chose one. 

Can I get some help about that ?

**Comment by LongCatIsLooong** [comment]
> Is there any release date for that or is it under dev?
Not sure which feature/bug fix you are referring to?

> It only shows passwords so I can click and chose one
Did you set up the associated domain on your website? I think it worked when I tested it.

**Comment by srcnysf** [comment]
@LongCatIsLooong yes I added but no suggestion was made. 

<img width="993" alt="Screenshot 2020-11-06 at 10 45 17 PM" src="https://user-images.githubusercontent.com/11577082/98422206-1f79e000-209c-11eb-935b-53e2fe0479b7.png">

Here is the associated links and here is the code

```
AutofillGroup(
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
TextFormField(
keyboardType: TextInputType.emailAddress,
autofillHints: [AutofillHints.email],
.
.
.
TextFormField(
obscureText:true,
keyboardType: TextInputType.text,
autofillHints: [AutofillHints.password],
.
.
.
```
and the suggestion not happening also it not asking about saving the credentials on first log in
<img width="360" alt="Screenshot 2020-11-07 at 2 02 07 AM" src="https://user-images.githubusercontent.com/11577082/98422627-3ec53d00-209d-11eb-887c-c22952165203.png">

**Comment by LongCatIsLooong** [comment]
@srcnysf your website needs to serve an `apple-app-site-association`: https://developer.apple.com/documentation/safariservices/supporting_associated_domains

**Comment by srcnysf** [comment]
what if there is no website  ? 🤔 @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
@srcnysf AFAIK webcredentials is required for autofill to on iOS. Without it strong password does not work, and the user will have to manually select the autofill entry.

**Comment by srcnysf** [comment]
Thanks so much 🤗 @LongCatIsLooong

**Comment by hawkinsjb1** [comment]
@LongCatIsLooong Are you sure associated domains are needed on iOS even if a user is using an independant AutoFill service (ex: LastPass)? The relevant [docs](https://developer.apple.com/documentation/security/password_autofill) have a separate section for 3rd party password managers, **Integrate a Password Management App with Password AutoFill**, and its not clear whether associated domains are needed for this, but it seems limiting to require a website if credentials are stored in 3rd party managers.

Android still seems to be a mystery

**Comment by LongCatIsLooong** [comment]
@hawkinsjb1 Without setting up associated domains, if I remember correctly, autofill still worked for me, but I was given a large list of credentials instead of more targeted results, and strong password didn't work. I have not tested 3rd party autofill on iOS, but according to this wwdc video (https://developer.apple.com/videos/play/wwdc2018/721/), the user-perceived autofill flow with a 3rd party autofill provider is not drastically different.

**Comment by hawkinsjb1** [comment]
@LongCatIsLooong = I see, I wonder if someone else can get 3rd party AutoFill to work on iOS to determine if the issue similarly affects both platforms as I haven't had luck with either (not using associated domains)

**Comment by hawkinsjb1** [comment]
Hmm, I just pulled down master and it doesn't seem like https://github.com/flutter/engine/pull/21534 made any difference. Could this issue remain open? (i'm not entirely convinced its an Android-only issue)

**Comment by LongCatIsLooong** [comment]
@hawkinsjb1 tested on my android device with the repro code from OP, and on iOS with a previous project I set up for autofill, they both worked (the iOS app didn't show a dialog but it did save the password to "Autofill Passwords"). Do you mind opening a new issue with repro steps?

**Comment by BelfDev** [comment]
@LongCatIsLooong I can confirm I'm experiencing a similar issue. I cannot make the password manager (Google) 'save' prompt show up consistently on Android.

**Use Case**

My UI is composed of two `TextField`s grouped within a `Column` which is wrapped by an `AuofillGroup` -- as expected. The only way I can trigger Google's  'save credentials' dialog is if I **fill out both fields and then tap on the email field once again** before pressing on a 'Submit' button.

**Resources**

<details>
<summary>UI preview; click to expand</summary>
<p>

| Filled Out Inputs | Successful Google prompt |
|:-----------------:|:-----------:|
| <img src="https://user-images.githubusercontent.com/11461969/100459968-25fce580-30a5-11eb-8d08-14fecafa755e.png" width="250"> | <img src="https://user-images.githubusercontent.com/11461969/100459975-285f3f80-30a5-11eb-8ee5-16012eb42dde.png" width="250">

_Test device: Samsung S8_

</p>
</details>  

<details>
<summary>Sample code; click to expand</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  TextEditingController _emailController = TextEditingController();
  TextEditingController _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    TextInput.finishAutofillContext(shouldSave: true);
    return Scaffold(
      appBar: AppBar(
        title: Text('Autofill Experiment'),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16.0),
        child: ListView(
          children: [
            AutofillGroup(
              onDisposeAction: AutofillContextAction.cancel,
              child: Column(
                children: <Widget>[
                  TextField(
                    autofocus: true,
                    controller: _emailController,
                    autofillHints: [AutofillHints.email],
                    keyboardType: TextInputType.emailAddress,
                    textInputAction: TextInputAction.next,
                  ),
                  TextField(
                    controller: _passwordController,
                    autofillHints: [AutofillHints.password],
                    textInputAction: TextInputAction.done,
                    obscureText: true,
                  ),
                ],
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 16.0),
              child: ElevatedButton(
                onPressed: () async {
                  FocusScope.of(context).unfocus();
                  TextInput.finishAutofillContext(shouldSave: true); // Iconsistent behavior
                },
                child: Text('Submit'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</p>
</details>  

<details>
<summary>Flutter doctor output; click to expand</summary>
<p>

```bash
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
```

</p>
</details>

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by TahaTesser** [comment]
This issue still reproduces on `stable` and `beta`, closed https://github.com/flutter/flutter/issues/72083 with confirmation 
CC @pcsosinski

**Comment by sabreys** [comment]
still don't work save credential.

**Comment by ricardobrg** [comment]
@TahaTesser I would like to work on this. Is there anyone working on this already?
