### ISSUE TITLE
All code samples and snippets need to be updated for null safety

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69123]
In https://github.com/flutter/flutter/pull/69122 I will opt out all of the snippets from null safety. I've also added language versions to the templates.

At some point after the flag flip, we'll need to update these to null safety.

@gspencergoog

**Comment by jonahwilliams** [comment]
Big list of errors from snippets: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865278440977658192/+/steps/flutter_analyze/0/stdout

**Comment by Hixie** [comment]
There's a problem currently with some of the samples where they don't run until you enable "null safety" from the ... menu, for example see: https://master-api.flutter.dev/flutter/widgets/AnimatedContainer-class.html
Not sure if that's expected or not but we should definitely make sure that works. :-)

**Comment by goderbauer** [comment]
Regarding the previous comment, it appears that you cannot opt out of null safety in dart pad by using `// @dart = 2.9`. That breaks the example. You actually need to turn "null safety" off in the three dot menu to run that code. And there's another confusion: Initially, even though null-safety is turned on, there's no checkmark next to it in the three dot menu.

I'll file issues about that with dartpad.
