### ISSUE TITLE
Expand SnackBar docs to answer questions herein

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6912]
We need to perform certain actions when snackbar expires from the screen. This pattern is common for snackbars that have "undo" action because the app typically commits a modification when undo is no longer an option (i.e. when snackbar disappears).

We are looking for something similar to Android snackbar [callback](https://developer.android.com/reference/android/support/design/widget/Snackbar.Callback.html): A callback that gets invoked with the "dismissal reason".

**Comment by mehmetf** [comment]
I am marking this as a top request as we have to implement a couple of ugly workarounds.

**Comment by Hixie** [comment]
showSnackBar returns a ScaffoldFeatureController which has a `closed` property that is a `Future` that resolves when the snack bar closes. Does that solve your problem?

**Comment by mehmetf** [comment]
The problem is that future will fire whether the snackbar disappears on its own or whether the undo action is clicked. I need to differentiate between the two. Can you recommend a workaround w/o keeping local state?

**Comment by abarth** [comment]
If the user undoes the action, won't the commit operation realize that the transaction has been aborted by the time the `closed` future resolves?  That seems more robust (e.g., if there's more UI that can trigger an undo).

**Comment by mehmetf** [comment]
Ideally I would like to keep the model calls sane. In most implementations, it is actually an error to call commit after you have aborted a transaction since it typically signals a problem in the code.

Robustness should be up to the client to ensure. We only allow undo via snackbar and there can only be one snackbar active at a time. We manually remove the old one if a new one comes through. So you can't, say, delete a bunch of items back to back and then undo all of them. The second delete will immediately invalidate the first delete's snackbar which will commit the action.

**Comment by mehmetf** [comment]
Can the completer return the state of the snackbar when it disappears? (Whether it was closed via an action or animation end or by calling ```removeCurrentSnackbar```?)

**Comment by Hixie** [comment]
It's probably worth noting that the future on the controller is not guaranteed to complete. For example, if the app is closed with the snackbar up, you might never get notified that the snackbar closed. Or if the app crashed, or if the user went to another page, or if the user shows a dialog (which IIRC prevents the snackbar timer from ticking), etc. So relying on this for model management is probably not reliable.

**Comment by mehmetf** [comment]
Noted. Nothing we can do about most of those situations. If the app is closed or crashed immediately after swiping to delete something, that op won't be committed. We are okay with that.

What happens to the snackbar when a dialog shows? When its timer is stopped, does it simply disappear or does it just stay on the screen? After the dialog goes away, does it resume?

The most concerning case is the page switch. It would be common for users not to wait for the snackbar to close to move onto another page. I know the scaffold (and its context) is torn down but could we somehow detect that the snackbar is about to be disposed and handle it? Could it be handled the same as removeCurrentSnackbar?

**Comment by Hixie** [comment]
Before closing this bug I'll definitely make sure to look at all those questions and update the docs accordingly. I don't know the answer off hand.

One thing you could do on your end is to have a `Completer<bool>` that you complete with false if you get the undo action callback, and with true when the closed future resolves, if the completer is not `isCompleted` already. That way you could easily extend your logic later if you decide to undo from other UI affordances.

We're reluctant to expose how the snackbar closed in the `closed` future because we think that that will lead to brittle designs.

**Comment by Hixie** [comment]
After more discussion, I have been convinced that it's ok to expose how the snackbar was closed. We should probably have an enum for the various ways that it can be closed. The clinching argument was that creating a wrapper widget like I describe is so trivial that it wouldn't really discourage people from doing it anyway.

**Comment by abarth** [comment]
Brainstorming values for the enum:

1. Closed because action was taken
2. Closed because user dismissed the snackbar (e.g., by dragging down)
3. Closed because removeSnackbar was called
4. Closed because the timeout expired
