### ISSUE TITLE
How can I achieve this?

### ISSUE THREAD

**Issue by Linaks** [flutter/flutter#69120]
How can I achieve this?

_Originally posted by @Linaks in https://github.com/flutter/flutter/issues/15507#issuecomment-717374246_

**Comment by skoustubha** [comment]
This isn't a issue @Linaks I request you to google about it. Also if you wouldn't find I recommend you to use #stackOverflow.


#not_an_issue
#to_be_closed.

**Comment by PixelToast** [comment]
The GitHub issue tracker is for bug reports and feature requests, questions like this are better suited for [StackOverflow](https://stackoverflow.com/tags/flutter) or one of our other communities at https://flutter.dev/community

**Comment by Linaks** [comment]
Thank you guys :)
