### ISSUE TITLE
Flutter run stuck at "Waiting for observatory port to be available..."

### ISSUE THREAD

**Issue by MoeEarthDimensionC137** [flutter/flutter#69133]
`$flutter run --verbose`
....
`[ +284 ms] executing: /usr/bin/xcrun simctl install 52F1DD4F-3459-4FDD-ABBA-15CD4E7B2F38
/Users/mohammadkhaled/Documents/Developer/flutterProjects/PriceG/build/ios/iphonesimulator/Runner.app
[+1125 ms] executing: /usr/bin/plutil -convert json -o -
/Users/mohammadkhaled/Documents/Developer/flutterProjects/PriceG/build/ios/iphonesimulator/Runner.app
/Info.plist
[  +20 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/mohammadkhaled/Documents/Developer/flutterProjects/PriceG/build/ios/iphonesimulator/Runner.app
/Info.plist
[   +1 ms]
{"CFBundleName":"PriceG","DTXcode":"1210","DTSDKName":"iphonesimulator14.1","UILaunchStoryboardName":
"LaunchScreen","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon60x60","AppI
con76x76"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"18A8394","CFBundleDevelopmentRegion":"en","CF
BundleVersion":"1","BuildMachineOSBuild":"19H2","DTPlatformName":"iphonesimulator","CFBundlePackageTy
pe":"APPL","UIMainStoryboardFile":"Main","CFBundleSupportedPlatforms":["iPhoneSimulator"],"CFBundleSh
ortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"Runner","DTComp
iler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrien
tationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UII
nterfaceOrientationLandscapeRight"],"MinimumOSVersion":"12.0","CFBundleIdentifier":"com.example.Price
G","UIDeviceFamily":[1,2],"DTPlatformVersion":"14.1","CFBundleSignature":"????","CFBundleIcons":{"CFB
undlePrimaryIcon":{"CFBundleIconFiles":["AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild"
:"12A7403","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortr
ait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerB
asedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"18A83
94","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect and debug your
application. This prompt will not appear on release builds."}
[  +25 ms] executing: /usr/bin/xcrun simctl launch 52F1DD4F-3459-4FDD-ABBA-15CD4E7B2F38
com.example.PriceG --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +413 ms] com.example.PriceG: 74541
[        ] Waiting for observatory port to be available...`

**Comment by ezhamkarim** [comment]
Do you run on iOS or android simulator?

**Comment by darshankawar** [comment]
@MoeEarthDimensionC137 
There's similar open issue describing your case, [33214](https://github.com/flutter/flutter/issues/33214).
Also try this possible [solution](https://github.com/flutter/flutter/issues/33214#issuecomment-568733832) and see if it works for you.
Closing this as duplicate.
