### ISSUE TITLE
Could not find a generator for route RouteSettings(“chat”, null) in the _CustomTabViewState

### ISSUE THREAD

**Issue by yashwp** [flutter/flutter#69132]
I have been facing this issue for months now! but found out **no solution** for it. 

I have a set of routes that I have defined in the `routes.dart` and these routes are linked in the `main.dart` file as below.

```
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        StreamProvider<ConnectivityStatus>(
          create: (_) => ConnectionService().connectionStatusController.stream,
        ),
        ...
        ChangeNotifierProvider<AuthNotifier>(
          create: (_) => AuthNotifier(),
        ),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        routes: Routes.routes,
        home: SplashScreen(),
      ),
    );
  }
```

### `Routes.dart` file:
```
class Routes {
  Routes._();

  static const chat = '/chat';

  static final routes = <String, WidgetBuilder>{
    chat: (BuildContext ctx) => CircleChat(),
  };
}
```

I have a button that is triggering the above route but throwing error.
```
FlatButton(
  Navigator.of(context).pushReplacementNamed(Routes.chat);
)
```

### Error -

> The following assertion was thrown while handling a gesture:
> Could not find a generator for route RouteSettings("chat", null) in the
> _CustomTabViewState. Generators for routes are searched for in the following order:
>  1. For the "/" route, the "builder" property, if non-null, is used.
>  2. Otherwise, the "routes" table is used, if it has an entry for the route.
>  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "builder" and "routes".
>  4.  Finally, if all else fails `onUnknownRoute` is called. Unfortunately, onUnknownRoute was not set.
> 
> When the exception was thrown, this was the stack:
> #0      _CustomTabViewState._onUnknownRoute.<anonymous closure>

**P.S. - For a similar error I went through [this][1] and [this][2], but I didn't find the explanation, that why it is not working when all semantics are correct.**

  [1]: https://stackoverflow.com/questions/59488673/flutter-could-not-find-a-generator-for-route-routesettings-homepage-null
  [2]: https://stackoverflow.com/questions/52405521/could-not-find-a-generator-for-route-home-page-in-the-materialappstate/52406650#52406650

**Comment by darshankawar** [comment]
@yashwp 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
