### ISSUE TITLE
ResTable_typeSpec entry count inconsistent

### ISSUE THREAD

**Issue by marhyno** [flutter/flutter#69149]
I have an issue after upgrading to newest flutter. 

flutter doctor -v
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-GB)
    • Flutter version 1.23.0-18.1.pre at d:\SideProjects\MyHorse.sk\flutter
    • Framework revision 198df796aa (12 days ago), 2020-10-15 12:04:33 -0700
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\stefa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Moto G 5S Plus (mobile) • ZY322HCR5P • android-arm • Android 8.1.0 (API 27)

• No issues found!

ERROR:
I cannot login to my application, nor I cant call Facebook Login, error I get is this

Reloaded 2 of 748 libraries in 3,437ms.
I/zygote  (30442): Do full code cache collection, code=243KB, data=226KB
I/zygote  (30442): After code cache collection, code=243KB, data=172KB
W/ResourceType(30442): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(30442): ResTable_typeSpec entry count inconsistent: given 5346, previously 5347
W/ResourceType(30442): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(30442): ResTable_typeSpec entry count inconsistent: given 5346, previously 5347

**Comment by marhyno** [comment]
Oh my god, sorry, I forgot I have renamed my API route to the test server, and test server was not running ...

**Comment by TahaTesser** [comment]
Hi @marhyno 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by igonzarec** [comment]
I'm still having this same issue.

Launching lib/main.dart on Moto G 5S Plus in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for Moto G 5S Plus to report its views...
Debug service listening on ws://127.0.0.1:59637/uWWctaiPMFA=/ws
Syncing files to device Moto G 5S Plus...
W/DynamiteModule(  799): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(  799): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(  799): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 5486, previously 5487
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 5486, previously 5487
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 5486, previously 5487
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 5486, previously 5487
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(  799): ResTable_typeSpec entry count inconsistent: given 5486, previously 5487
I/zygote  (  799): The ClassLoaderContext is a special shared library.
I/zygote  (  799): The ClassLoaderContext is a special shared library.
V/NativeCrypto(  799): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
I/zygote  (  799): Do partial code cache collection, code=29KB, data=30KB
I/zygote  (  799): After code cache collection, code=29KB, data=30KB
I/zygote  (  799): Increasing code cache capacity to 128KB
I/ProviderInstaller(  799): Installed default security provider GmsCore_OpenSSL
I/flutter (  799): Instance of 'QuerySnapshot'
