### ISSUE TITLE
[iPad] : UiKitView flickering problem started with version 1.22.2

### ISSUE THREAD

**Issue by majdi21** [flutter/flutter#69142]
Hello,

   I have a problem that started with Flutter version 1.22.2. It worked perfectly fine on 1.22.1.

   The problem is when using UiKitView. The attached zip file contains a video showing the problem. Notice that after using UiKitView, opening the app drawer flickers the entire screen.

[UiKitView_Causing_Flickering_Demo.mov.zip](https://github.com/flutter/flutter/files/5448146/UiKitView_Causing_Flickering_Demo.mov.zip)

   I created a sample application (used in the video). The code for the sample app can be retrieved from (It's larger than 10MB so I couldn't attach it) https://cmicglobal-my.sharepoint.com/:u:/g/personal/majdi_cmic_ca/EcC2xmPcBXtJt_oFAJmziTABuOw3lt9u1E5z50QzWiulsQ?e=nl5vOV

   Considering this works fine with Flutter 1.22.1. I'm assuming it's a bug with Flutter 1.22.2. Let me know if there's anything I can do to help investigate or fix this.

Regards

**Comment by darshankawar** [comment]
@majdi21 
I tried your code sample on latest stable using iPhone 6s (OS 14), but didn't see the flickering while opening the drawer, as you mentioned.

[RPReplay-Final1603873066.MP4.zip](https://github.com/flutter/flutter/files/5450512/RPReplay-Final1603873066.MP4.zip)

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (12 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

Also verified the same on latest master and didn't observe the screen flicker. Can you provide what device and OS version are you seeing this issue on ?

**Comment by majdi21** [comment]
Hello @darshankawar ,

  I'm seeing the problem on an iPad simulator running iOS 14.1. I tried iphone 8 simulator and I don't see the problem there. Here's the output of flutter doctor:

flutter doctor -v

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.22.2 at /Users/fluttertest/dev/tools/flutter
    • Framework revision 84f3d28555 (13 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/fluttertest/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPad Pro (9.7-inch) (mobile) • 78605178-9CBE-4874-BE6B-10A7C2CBEA91 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!

Regards,

**Comment by darshankawar** [comment]
Issue replicable on latest stable. Tested with ipad simulator.  Same issue doesn't occur in latest master.

[69142_stable.mov.zip](https://github.com/flutter/flutter/files/5456472/69142_stable.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (13 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPad Pro (9.7-inch) (mobile) • 7526F522-D072-4806-B424-66E9BD88D078 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

**Comment by majdi21** [comment]
Hello,

   This is still reproducible in 1.22.3.

Regards,

**Comment by majdi21** [comment]
Hello,

Just confirming that this is still reproducible in 1.22.4.

@darshankawar anything I can do to help? would this just be ignored because latest master doesn't have the issue?

Regards

**Comment by chinmaygarde** [comment]
cc @blasten @cyanglaz

**Comment by JordanADavies** [comment]
This is still happening in stable 1.22.6.

**Comment by darshankawar** [comment]
@majdi21 
I tried verifying this issue using latest stable version (3.13.6) but the code sample link you provided in original description doesn't seem to be accessible anymore. Can you provide us the code sample if the reported behavior still persists on latest stable ?
