### ISSUE TITLE
OutlinedButton splash color property missing

### ISSUE THREAD

**Issue by AndrewByk** [flutter/flutter#69147]
I'm new into Flutter and cannot find OutlinedButton splashColor property. Is anyone knows how to change the splash color?

**Comment by darshankawar** [comment]
@AndrewByk 
Please check the migration [guide](https://docs.google.com/document/d/1yohSuYrvyya5V1hB6j9pJskavCdVq9sVeTqSoEPsWH0/edit) mentioned in  OutlineButton class [doc](https://api.flutter.dev/flutter/material/OutlineButton-class.html).

**Comment by AndrewByk** [comment]
Thank you

**Comment by darshankawar** [comment]
@AndrewByk 
I am assuming you got your answer on how to use splash color for the said widget. I am going ahead and closing it. If you disagree, write in comments and I'll reopen.
thanks.
