### ISSUE TITLE
File (Image) exists on path but can not be loaded

### ISSUE THREAD

**Issue by bobanminic96** [flutter/flutter#69153]
Ok, so I have problem to load image downloaded from Firebase Storage.

Flow is that I show Network.Image() as image thumbnail until image downloads from Firebase Storage. In meantime, if you click on thumbnail, it appears new screen where it should open file from app folder.

I added check in Inkwell, on tap, to check if file exists on path so it could proceed to next screen or wait for while/next try until image downloads, and it passes as true, but then, in next screen, it seems that image is not fully downloaded yet, and Widget breaks. And then when I trigger setState() somehow, image loads as expected.

Is there any way to check if file can be loaded or ?

This is code sample how I check for image exsistance.

`
static bool imageDownloaded(String imageName){
    String tempPath = dirPath + imageName;
    final File tempFile = File(tempPath);
    if(tempFile.existsSync()){
      print("ImageRepo.imageDownloaded : Image donwloaded and exicts on path: $tempPath .");
      return true;
    }
    print("ImageRepo.imageDownloaded : Image not downloaded yet.");
    return false;
  }
`

**Comment by darshankawar** [comment]
@bobanminic96 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources.
If you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
