### ISSUE TITLE
"video_player: ^ 0.10.12 + 5 " unable to play video in  IOS and android app

### ISSUE THREAD

**Issue by ZHANGBADAO** [flutter/flutter#69158]
Embed the flutter as a module in IOS and android app, and use "video_player: ^ 0.10.12 + 5 " play the video, unable to play, the video area is blank; 

on IOS console: No error logs appear;

on android console:
Unhandled Exception: type 'PlatformException' is not a subtype of type 'String'
    #0      _reportError (package:flutter_module/main.dart:37:26)
    #1      main.<anonymous closure> (package:flutter_module/main.dart:32:11)
    #2      _rootRunBinary (dart:async/zone.dart:1222:13)
    #3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
    #4      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
    #5      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
    #6      Future._propagateToListeners (dart:async/future_impl.dart:610:16)
    #7      Future._completeError (dart:async/future_impl.dart:537:5)
    #8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
    #9      VideoPlayerController.initialize (package:video_player/video_player.dart)

**but in pure flutter app, it can play normally on IOS and Android**

my development environment :
flutter SDK: 1.22.2

**Comment by ezhamkarim** [comment]
Have you tried to upgrade your package to latest one? [video_player ](https://pub.dev/packages/video_player) and rebuild the project? Also try to use `try` and `catch` block to handle any exception

**Comment by ZHANGBADAO** [comment]
> 
> 
> Have you tried to upgrade your package to latest one? [video_player ](https://pub.dev/packages/video_player) and rebuild the project? Also try to use `try` and `catch` block to handle any exception

I have updated to the latest version(video_player: ^0.11.1+2),  The problem remains;

Added try and catch. No errors were caught
`try{
            _controllerVideo = VideoPlayerController.network(arr[index])
              ..initialize();
            child = VideoPlayer(_controllerVideo);
          }catch(e){
            print('*****************视频初始化错误 $e');
          }`

**Comment by ezhamkarim** [comment]
> > Have you tried to upgrade your package to latest one? [video_player ](https://pub.dev/packages/video_player) and rebuild the project? Also try to use `try` and `catch` block to handle any exception
> 
> I have updated to the latest version(video_player: ^0.11.1+2), The problem remains;
> 
> Added try and catch. No errors were caught:
> `try{ _controllerVideo = VideoPlayerController.network(arr[index]) ..initialize(); child = VideoPlayer(_controllerVideo); }catch(e){ print('*****************视频初始化错误 $e'); }`

Can you try add this code `on PlatformException catch(e) { //print error}` in between of `try` and `catch` blocks. Let see if the error still can be catch 😀

**Comment by 1291431532** [comment]
I think the problem has to do with Android API Level. Are you using AVD?

**Comment by TahaTesser** [comment]
Hi @ZHANGBADAO 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
