### ISSUE TITLE
Flutter Web issues(compressed) after updating to (Channel beta, 1.23.0-18.1.pre)

### ISSUE THREAD

**Issue by cenezoic123** [flutter/flutter#69152]
After I updating it to latest flutter beta version(Channel beta, 1.23.0-18.1.pre),
we encountered these problems.

1. The height of the textfield changed.
2. The spacing of the widgets.

Is these really normal for the new updates?
The issues only occur in web but in mobile its working fine.

Just refer to the attached images. 

![BEFORE](https://user-images.githubusercontent.com/64458514/97377577-582af400-18fb-11eb-9c96-dab6b92cd3a2.PNG)

![AFTER](https://user-images.githubusercontent.com/64458514/97377593-5eb96b80-18fb-11eb-88ff-c5cf9423dcae.PNG)

**Comment by pedromassangocode** [comment]
Hi @cenezoic123 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
