### ISSUE TITLE
[package_info] BuildNumber is 1 in Debug mode, but 1001 under release

### ISSUE THREAD

**Issue by CaiXiaoBai** [flutter/flutter#69169]
In the pubspec.yaml file, the version is 1.0.0+1

But the buildNumber is 1 in Debug mode, but 1001 under release, why?

**Comment by 1291431532** [comment]
https://github.com/flutter/plugins

**Comment by darshankawar** [comment]
@CaiXiaoBai 
This seems to be a known issue with the plugin. See [this](https://github.com/flutter/flutter/issues/59636) similar open issue.
Closing this as duplicate.
