### ISSUE TITLE
How do I use apread in the ternary operator?

### ISSUE THREAD

**Issue by liwei511** [flutter/flutter#69165]
var item = [1, 2, 3];
var one = [...item, 4]; // right
var two = [true ? ...item : 4]; // error: Expected an identifier

please，How do I use apread in the ternary operator? ( 三目运算符里怎么用 ...)

**Comment by nimi0112** [comment]
Not sure what are you trying to do inside the array?
This can be done by 

```final result= true ? item1 : item2;```

**Comment by PixelToast** [comment]
The GitHub issue tracker is for bug reports and feature requests, questions like this are better suited for [StackOverflow](https://stackoverflow.com/tags/flutter) or one of our other communities at https://flutter.dev/community

In the case you describe, using collection-if should work:
```dart
var two = [
  if (condition)
    ...item
  else
    4,
]
```
