### ISSUE TITLE
MaterialColor canot be compared directly with Color type

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#69162]
@shihaohong Hi,
Continue of https://github.com/flutter/flutter/pull/68171#discussion_r512738517

https://github.com/flutter/flutter/blob/f55117840818eae1b3972a6abe9d2784fc8fb9b4/packages/flutter/lib/src/material/theme_data.dart#L348

I believe this should be a typo instead of accentColor.value == primaryColor.value.
Most of the time, `primaryColor` is MaterialColor type and `accentColor` is Color type. They cannot be compared directly with ==, otherwise, it will not be the expected result.

Fix this typo will break somethings, but it doesn’t seem right if you let it as-is. It’s really a tricky problem.

**Comment by pedromassangocode** [comment]
Hi @xu-baolin 
Is there a practical way to prove that the current implementation is wrong?
Thank you

**Comment by HansMuller** [comment]
This doesn't address this specific problem however in the fullness of time: TabBar et al should just depend on TabBarTheme, and by default it should configure itself in terms of the overall theme's ColorScheme.  TabBarTheme needs to morph into a TabBarTheme/TabBarThemeData pair that matches the conventions in flutter.dev/go/material-theme-system-updates.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
