### ISSUE TITLE
TextField auto input when reveive sms code

### ISSUE THREAD

**Issue by chaseDeil** [flutter/flutter#69179]
Hello, I have a question about TextField: When there is a TextField in the page and the focus has been obtained, when the SMS verification code is received, can the verification code be automatically filled to the top of the keyboard like an iOS native APP? If it cannot be achieved, are there other solutions for reference. Thank you

**Comment by taimoorhassan-work** [comment]
You need to read the content of the recieved sms and put it into the textfield yourself (using TextEditingController). There is no way to  have message content automatically inserted to a textfield or any other widget for that matter. That won't even be practical

Consider this. Your server sends the following message to the phone

> Your verification code is 1234213

Now, there is no way for the textfield or your app to know which part of the sms should be inserted into the textfield.

Consider using the [https://pub.dev/packages/sms_receiver](This plugin) and write custom logic to retrieve the verification code (or something else that you want) from the message and then change the text in Your textfield manually
if you want to write custom code for intercepting incoming messages. That is another animal. [https://stackoverflow.com/a/61415796](This may help)

**Comment by pedromassangocode** [comment]
Hi @chaseDeil 
Flutter support autofill for OTP and many other types, please see:
https://api.flutter.dev/flutter/material/TextField/autofillHints.html

For one time code you will have something like this:

```dart
TextFormField(
    autofillHints: [AutofillHints.oneTimeCode],
)
```

Closing as this is not an issue with Flutter itself.

**Comment by chaseDeil** [comment]
> ```dart
> TextFormField
> ```



> Hi @chaseDeil
> Flutter support autofill for OTP and many other types, please see:
> https://api.flutter.dev/flutter/material/TextField/autofillHints.html
> 
> For one time code you will have something like this:
> 
> ```dart
> TextFormField(
>     autofillHints: [AutofillHints.oneTimeCode],
> )
> ```
> 
> Closing as this is not an issue with Flutter itself.

Thanks for your reply, it solved my problem

**Comment by khalid-al-shehri** [comment]
@chaseDeil 
Hi, you said your problem solved and this is great.
can you please share an example how to get otp from SMS and make it autofill ?

**Comment by chaseDeil** [comment]
> @chaseDeil
> Hi, you said your problem solved and this is great.
> can you please share an example how to get otp from SMS and make it autofill ?

Refer to this reply：https://github.com/flutter/flutter/issues/69179#issuecomment-718295709
In the new version of Flutter, you can replace textField with TextFormField

**Comment by khalid-al-shehri** [comment]
Unfortunately, not working. Could you please check this code?

`return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Wait until receive SMS with code',
            ),
            TextFormField(
              controller: _textController,
              autofillHints: [AutofillHints.oneTimeCode],
              onChanged: (value){
                setState(() {
                  _textController.text = value;
                });
              },
              keyboardType: TextInputType.number,
              style: TextStyle(fontSize: 32),
            ),


            RaisedButton(
                child: Text("Verify"),
                onPressed: (){
                  print(_textController.value.text);
                }
            ),

          ],
        ),
      ),
    );`
