### ISSUE TITLE
module/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

### ISSUE THREAD

**Issue by HuangJsong** [flutter/flutter#69174]
Users/a10.11.5/ymt-ios/ios_main/../my_flutter/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
========================================================================
ERROR: Unknown FLUTTER_BUILD_MODE: daily.
Valid values are 'Debug', 'Profile', or 'Release' (case insensitive).
This is controlled by the FLUTTER_BUILD_MODE environment variable.
If that is not set, the CONFIGURATION environment variable is used.

You can fix this by either adding an appropriately named build
configuration, or adding an appropriate value for FLUTTER_BUILD_MODE to the
.xcconfig file for the current build configuration (Daily).
========================================================================
cp: /Users/a10.11.5/flutter/bin/cache/artifacts/engine/unknown/Flutter.podspec: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by darshankawar** [comment]
@HuangJsong Not sure where exactly are you getting the error and what the actual error is. Looking at what you provided, I see this : `ERROR: Unknown FLUTTER_BUILD_MODE: daily.
Valid values are 'Debug', 'Profile', or 'Release' (case insensitive).`

So you probably need to use valid values such as listed in it per your environment you want to build on.
If issue persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by HuangJsong** [comment]
When I run xcode  the files in the （..flutter_module/.ios/Flutter/engine ） will be deleted
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale zh-Hans)
    • Flutter version 1.22.0 at /Users/a10.11.5/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/a10.11.5/Library/Android/sdk
    • Platform android-29, build-tools 30.0.2
    • ANDROID_HOME = /Users/a10.11.5/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

@darshankawar

**Comment by darshankawar** [comment]
@HuangJsong you'll need to provide a complete minimal reproducible code sample that we can copy paste and run to see the issue. you may upload all code in github and share the link here if that's suitable for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
