### ISSUE TITLE
Add a CalendarMultiDatePicker to cater discrete multi-date selection

### ISSUE THREAD

**Issue by fish-like-mammal** [flutter/flutter#69184]
## Use case

The current calendar pickers in Flutter only allows single-date selection or range selection, but in many situations users want to select several separate days / ranges of days. A CalendarMultiDatePicker should serve for the above usage.

## Proposal

By changing the selected type from DateTime to List<DateTime> and amending relative codes, enabling multi-date selection in a calendar picker. I actually made one for the app I am currently working on, just want to see if it is a good idea to also implement such widget in Flutter.

**Comment by darshankawar** [comment]
@fish-like-mammal 
Does this [open](https://github.com/flutter/flutter/issues/22621) issue sound similar to your proposal ?

**Comment by fish-like-mammal** [comment]
@darshankawar 
Yes I think the issue is duplicated and I'm closing this issue, thanks :D
