### ISSUE TITLE
FlatButton & Text produce inconsistent height

### ISSUE THREAD

**Issue by sooxt98** [flutter/flutter#69198]
The gap between each flatbutton shows that the height is inconsistent. 

![IMG_1534](https://user-images.githubusercontent.com/13378059/97454104-59970380-1971-11eb-8150-99dd2079e159.jpg)

```
Container(
                                            width: double.infinity,
                                            margin: EdgeInsets.only(bottom:15),
                                            child: FlatButton(child: Text("a"*200), onPressed: (){}, color: Colors.red,),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            margin: EdgeInsets.only(bottom:15),
                                            child: FlatButton(child: Text("a"*10), onPressed: (){}, color: Colors.red,),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            margin: EdgeInsets.only(bottom:15),
                                            child: FlatButton(child: Text("a"*400), onPressed: (){}, color: Colors.red,),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            margin: EdgeInsets.only(bottom:15),
                                            child: FlatButton(child: Text("a"*100), onPressed: (){}, color: Colors.red,),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            margin: EdgeInsets.only(bottom:15),
                                            child: FlatButton(child: Text("a"*10), onPressed: (){}, color: Colors.red,),
                                          ),
```

**Comment by HansMuller** [comment]
This issue, which presumably affects TextButton as well, may be related to https://api.flutter.dev/flutter/widgets/DefaultTextHeightBehavior-class.html

**Comment by pedromassangocode** [comment]
Hi @sooxt98 
I'm not sure if I understood the issue correctly. Can you please elaborate and what is your expected vs actual results?
I need you to provide your `flutter doctor -v`.
Thank you

**Comment by sooxt98** [comment]
@pedromassangocode I believe this issue exist since flutter first release until now; as you can see the code provided margin is set to 15, but the white margin in the output result is giving different height which different than 15

**Comment by pedromassangocode** [comment]
| With padding: 15 | Without padding |
| ----------------- | -----------------|
<img width="230" height="500" src="https://user-images.githubusercontent.com/67424416/97580377-81c74680-19f3-11eb-924a-43df67f00424.png"> | <img width="230" height="500" src="https://user-images.githubusercontent.com/67424416/97580389-855acd80-19f3-11eb-8e09-8b238f7b58bf.png">

Will assign the latest master version since this seems to happen with all Flutter versions.

**Comment by Piinks** [comment]
FlatButton has been removed from the framework and replaced with TextButton. Does this behavior persist in the new API?
