### ISSUE TITLE
[NavigationRail] Ability to add vertical space between icons

### ISSUE THREAD

**Issue by FaanNewbDev** [flutter/flutter#69193]
When using the NavigationRail, there is no possibility to create more vertical space between the Icons.
I want the minimum width of the NavigationRail. With no labels. "NavigationRailLabelType.none".
Therefore is it not possible to make the rail dynamic.

**Comment by chinmoy12c** [comment]
Working on this issue. Will adding a SizedBox be an appropriate approach?

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by FaanNewbDev** [comment]
Personally I think that adding a SizedBox after each element would be perfect. Individual and common, gives great layout possibilities.

**Comment by chinmoy12c** [comment]
I've added a ```verticalSpacing``` property to add same amount of spacing after each ```NavigationRailDestination```. Should I also add a property for a ```NavigationRailDestination``` so that the ```verticalSpacing``` can be overridden by each item individually if necessary?

**Comment by FaanNewbDev** [comment]
Thx, if whe could override each one, it would be more then perfect. It would open even more layout possibilities. Thank you for tile and effort

**Comment by shihaohong** [comment]
I took a quick look at @chinmoy12c's PR, and I think just adding vertical spacing after each element is not exactly the appropriate solution. 

Wouldn't it be better to have an API like so:
- Each navigation rail item can take a `padding` property. This `padding` property would then just wrap each item with a `Padding` widget (https://master-api.flutter.dev/flutter/widgets/Padding-class.html) that is adjusted by an EdgeInsetsGeometry.
- I think that adding a padding property to the `NavigationRail` itself is tricky. You can have the following scenarios:
    - You want padding only between each item, not before the first button and after the last button
    - You want padding surrounding each item, including before the first button and after the last button
    - You want a different amount of padding between the top and bottom of the navigation rail vs between each button

We could start off with giving each rail item a padding property, and in a separate PR, address providing the NavigationRail itself with a property to apply padding/spacing uniformly to all buttons.

**Comment by chinmoy12c** [comment]
> I took a quick look at @chinmoy12c's PR, and I think just adding vertical spacing after each element is not exactly the appropriate solution.
> 
> Wouldn't it be better to have an API like so:
> 
> * Each navigation rail item can take a `padding` property. This `padding` property would then just wrap each item with a `Padding` widget (https://master-api.flutter.dev/flutter/widgets/Padding-class.html) that is adjusted by an EdgeInsetsGeometry. This would also expand the tappable InkWell area by the padding area passed in.
> * I think that adding a padding property directly to the `NavigationRail` itself is tricky. You can have the following scenarios:
>   
>   * You want padding only between each item, not before the first button and after the last button
>   * You want padding surrounding each item, including before the first button and after the last button
>   * You want a different amount of padding between the top and bottom of the navigation rail vs between each button
>   * We also need to define whether this spacing encompasses the tappable area. My hunch for this particular property is probably not.
> 
> We could start off with giving each rail item a padding property, and in a separate PR, address providing the NavigationRail itself with a property to apply padding/spacing uniformly to all buttons.

Yes, I guess this implementation would indeed be better. I'll open a separate PR for the other case of uniform spacing/padding.

So to summarize this PR:

Each NavigationRail item would be wrapped in a ```Padding``` widget, which would be provided by a ```padding``` property of each ```NavigationRailDestination``` item and would be implemented as ```EdgeInsets.all(padding)``` . Am I correct?

**Comment by shihaohong** [comment]
Yes, basically adding a padding parameter that takes an `EdgeInsetsGeometry` would be consistent with the rest of the framework and be the most flexible approach. We also want to make sure that we correctly decide whether or not to wrap the padding with InkResponse. cc/ @FaanNewbDev

**Comment by chinmoy12c** [comment]
> Yes, basically adding a padding parameter that takes an `EdgeInsetsGeometry` would be consistent with the rest of the framework and be the most flexible approach. We also want to make sure that we correctly decide whether or not to wrap the padding with InkResponse. Padding for buttons tend to place the Padding widget so that its tappable space grows within the bounds of the button, so I assume this is probably what's desired here as well?
> 
> cc/ @FaanNewbDev

Sure :+1: , I'll land the updated PR once the tappable space discussion has been resolved. :)
