### ISSUE TITLE
url_launcher 5.7.8 causes build to fail

### ISSUE THREAD

**Issue by jbuda** [flutter/flutter#69192]
I have added the latest version of url_launcher (5.8.7) to my app, but when adding the import statement into the file i am greeted with the following error when building.

```
../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.9/lib/link.dart:85:21: Error: Method not found: 'SystemNavigator.routeInformationUpdated'.
    SystemNavigator.routeInformationUpdated(location: routeName);       
                    ^^^^^^^^^^^^^^^^^^^^^^^                             
../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.9/lib/link.dart:108:12: Error: Getter not found: 'Router'.
    return Router.of(context) != null;                                  
           ^^^^^^                                                       
                                                                        
FAILURE: Build failed with an exception.
```

This is the flutter version i am using

```
Flutter 1.22.0 • channel master • https://github.com/flutter/flutter.git
Framework • revision c44e5a32b5 (3 months ago) • 2020-07-21 09:35:40 -0700
Engine • revision 5a73d4dc25
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)
```

**Comment by iNoles** [comment]
Upgrade your Flutter!!!

**Comment by TahaTesser** [comment]
Hi @jbuda 
Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the probem persists with the upgrade, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by jbuda** [comment]
Thanks @iNoles @TahaTesser . Upgrading Flutter did the trick. 

Thought i had already done it. Clearly not!
