### ISSUE TITLE
90th_percentile_vsync_transitions_missed99th_percentile_frame_rasterizer_time_millisaverage_vsync_transitions_missedworst_frame_rasterizer_time_millis flutter_gallery_sksl_warmup__transition_perfflutter_gallery_sksl_warmup__transition_perf_e2e regressions 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69206]
https://flutter-flutter-perf.skia.org/e/?begin=1603669622&end=1603752548&keys=Xd5f06ed0bf6f897c371d6f777fb1dccc&num_commits=50&request_type=1&xbaroffset=22190

Started around https://github.com/flutter/flutter/pull/68887. If that really is the commit, I think these are related to the tests themselves, and not true regressions.

**Comment by zanderso** [comment]
These benchmarks were affected the first time the noted change was landed and reverted, so it is probably related, but I agree that the tool's drive command refactoring probably shouldn't have been able to have such a big effect on these numbers. @jonahwilliams @liyuqian

**Comment by liyuqian** [comment]
The tools could have a big impact on performance and "[flutter_tools] fix --use-existing-app for flutter drive #69237" does seem to be a promising fix. Specifically, `flutter_gallery_sksl_warmup__transition_perfflutter_gallery_sksl_warmup__transition_perf_e2e` verifies that the existing app built SkSL cache is fast. If the tool doesn't properly run the existing app built with SkSL cache, then there will be regressions.

**Comment by zanderso** [comment]
It looks like this one recovered on https://github.com/flutter/flutter/commit/735f6eec2caf0c123d6328cf2a9e6f1be21ee274
