### ISSUE TITLE
[video_player] android: add tests to make sure playing local assets is successful

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#69209]
We should add tests to make sure the local assets could be loaded by the video player plugin.

Issue: https://github.com/flutter/plugins/pull/3123

This PR fixed the issue, but was landed without tests: https://github.com/flutter/plugins/pull/3123

There is already a test available in the plugin, we just couldn't enable it on CI due to some issues. https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/test_driver/video_player_test.dart#L17

**Comment by cyanglaz** [comment]
Since it's been a while, we might need to re-investigate the test to see if we can enable it now https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/test_driver/video_player_test.dart#L17

**Comment by KyleFin** [comment]
This should've been closed when https://github.com/flutter/plugins/pull/3219 was merged, right?
