### ISSUE TITLE
Add resolveWith functions to MaterialStateBorderSide and MaterialStateOutlinedBorder

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#69203]
Follow up from https://github.com/flutter/flutter/pull/68596.

To make `MaterialStateBorderSide` and `MaterialStateOutlinedBorder` easier to use, it would help to mimic the rest of `MaterialStateColor`. Apps and examples could write `MaterialStateBorderSide.resolveWith(myCallback)`, which can take a bit of the sting out of using a MaterialStateProperty.

**Comment by craiglabenz** [comment]
Resolved by #78731
