### ISSUE TITLE
regression in 90th_percentile_vsync_transitions_missed large_image_changer_perf_ios

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69204]
https://flutter-flutter-perf.skia.org/e/?begin=1603526223&end=1603867624&keys=X7728d6094a7f0aebd80375845eda2829&requestType=0&xbaroffset=22225

At commit https://github.com/flutter/flutter/pull/69067.

Not sure why a tools commit would result in a vsync transitions regression, though.

Including both engine and tools for triage.

**Comment by kf6gpe** [comment]
Could also be https://github.com/flutter/engine/pull/22118; there are other regressions around this roll.

**Comment by zanderso** [comment]
https://github.com/flutter/flutter/pull/69237 did not appear to help. /cc @jonahwilliams

**Comment by dnfield** [comment]
Seems like the same problem discussed in https://github.com/flutter/flutter/issues/69205#issuecomment-720641300

**Comment by chinmaygarde** [comment]
Duplicate of https://github.com/flutter/flutter/issues/69205
