### ISSUE TITLE
Use "experimental" ndk build in hello_services example

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#6921]
If you try using android-ndk-r13b in hello_services, you get the following error:
./gradlew build -> Execution failed for task ':app:lintVitalRelease'

hello_services should be converted to latest android/ndk build system as documented here:
http://tools.android.com/tech-docs/new-build-system/gradle-experimental

@eseidel added:
ideally hello_services should just be the default flutter create workflow instead of a side-example.

I attempted to update the build.gradle format, but I end up getting the following:
"Must provide Flutter source directory" which I'm guessing refers to this in build.gradle:
flutter {
    source '../..'
}

**Comment by mit-mit** [comment]
Assigning to self for reproing; perhaps this was resolved as part of this weeks build changes?

**Comment by mit-mit** [comment]
@jtrunick a few weeks back we changed `flutter create` and `hello_services` to build for android using gradle ([see changes here](https://github.com/flutter/flutter/commit/b246c5e7e9f7eb482766970f205082199b32ad8c#diff-062601bc7edee6f7d00db063c7c74106)). Can you take a peek to see if that enables using the NDK?

**Comment by mit-mit** [comment]
Closing for now. Fell free to reopen with more details if needed.
