### ISSUE TITLE
Windows Plugins presubmit is failing on flutter/plugins

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#69232]
New PRs to `flutter/plugins` are getting a failed "Windows Plugins" presubmit, the cirrus link directs to the flutter dashboard which has no useful information.

Sample PRs with the failure:
* https://github.com/flutter/plugins/pull/3220
* https://github.com/flutter/plugins/pull/3213

This is currently blocking all flutter/plugins PRs.

**Comment by godofredoc** [comment]
This is because now Windows build_tests are competing for the same bots used by plugins. To fix this problem we need to:

* First move capacity from the windows 10 machines to windows server.
* Move all framework-luci devicelab tests to use windows server.
* Move all framework builds to use windows server.

**Comment by keyonghan** [comment]
based on competition, shall the `plugins` builds remain in the queue rather than directly fail?

**Comment by godofredoc** [comment]
I thought they were failing after a few mins, the ones linked here are failing immediately which means there are 0 Windows Server machines available

**Comment by godofredoc** [comment]
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.try&f=os%3AWindows-Server&k=os&s=id I see machines available.

I would expect long queue time but not seeing failures immediately.

**Comment by keyonghan** [comment]
Are all these windows bots the same config of 8 cores? We used to have 32 cores bots, which flutter/plugins are currently using.

**Comment by godofredoc** [comment]
![image](https://user-images.githubusercontent.com/54371434/97491666-afdb5680-191f-11eb-9662-c8c4b83ea49f.png)

The windows machines got downgraded yesterday to use 8 cores. We need to remove the explicit dimension for 32 cores

**Comment by keyonghan** [comment]
Working on a PR to fix this.

**Comment by stuartmorgan** [comment]
Meta-issue question: can we make the bot status page linked from PRs give useful feedback here (e.g., "Unable to schedule job; zero available machines meet job requirements") instead of a page that just has no information and essentially a link to nowhere?

**Comment by keyonghan** [comment]
The link in [checks](https://github.com/flutter/plugins/pull/3220/checks?check_run_id=1322883358) page will link to the build details only if the task is scheduled. If failed before being scheduled, the build id will not be available.

Instead if we can obtain the taks id (like [4f86ca6c72bfff10](https://chromium-swarm.appspot.com/task?id=4f86ca6c72bfff10)), then it is more useful to have this link.

But as currently supported from cocoon backend, the build is triggered via `buildbucket`, the task id maybe not available AFAIK.

**Comment by keyonghan** [comment]
The new config has been propagated. Just retried the failed builds from the above two PRs, and they are running now.

**Comment by godofredoc** [comment]
Let's open a bug for the usability request there are many of those that we'll need to address once we have the reliability and scalability parts under control.

**Comment by keyonghan** [comment]
Created issue to track the usability: https://github.com/flutter/flutter/issues/69242.

**Comment by amirh** [comment]
This still doesn't seem to be resolved...
https://github.com/flutter/plugins/pull/3213

**Comment by godofredoc** [comment]
That is a test/build problem https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865161897106601168/+/steps/Run_plugin_tests/0/steps/drive_examples/0/stdout

**Comment by amirh** [comment]
Ohh thanks, that is being worked on as well.
