### ISSUE TITLE
Unable to run native iOS plugin code on physical iPhone through Xcode 12.1

### ISSUE THREAD

**Issue by peterIrving** [flutter/flutter#69233]
## Steps to Reproduce

0. I am running Xcode version 12.1 on MacOS Catalina 10.15.6. I am using an iPhone 8 running iOS 14.1
1. I have created a basic plugin through android studio
2. I am able to run the example on my physical iPhone when ran through flutter run/Android Studio
3. When I open the native iOS module for the plugin (not example) in Xcode (through the Android Studio - open iOS module in Xcode command) I am notified that " Signing for "Runner" requires a development team. Select a development team in the Signing & Capabilities editor."
4. In Xcode - Signing & Capabilities, I have my development team selected, and my 'IOS Team Provisioning Profile' isn't set to expire for 11 months.

Note: native iOS applications are building just fine, so I have reason to believe this is a communication issue between Xcode and Flutter, not something to do with my provisioning profile. 

**Expected results:** 
Provisioning profile build error in Xcode to be removed upon verifying provisioning profile is selected and for the application to run

**Actual results:** 
Provisioning profile build error in Xcode does not disappear and application is not run

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0 at /Users/peterirving/devSDKs/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/peterirving/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 202.7319.5
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.50.1)
    • VS Code at /Users/peterirving/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Diagnostics’s iPhone (mobile) • 7080520af2c9db96ef1ecdff7cd7e200ca31633b • ios • iOS 14.1

! Doctor found issues in 2 categories.

```

</details>

**Comment by TahaTesser** [comment]
Hi @peterIrving 
just open ios plugin pod in Xcode through Android Studio
<img width="320" alt="Screenshot 2020-10-29 at 4 12 21 PM" src="https://user-images.githubusercontent.com/48603081/97558996-e2aa4b00-1a02-11eb-9821-e08635eb3461.png">
<img width="320" alt="Screenshot 2020-10-29 at 4 20 11 PM" src="https://user-images.githubusercontent.com/48603081/97559000-e3db7800-1a02-11eb-917f-bd617923a523.png">
<img width="320" alt="Screenshot 2020-10-29 at 4 20 47 PM" src="https://user-images.githubusercontent.com/48603081/97559005-e50ca500-1a02-11eb-9236-c1f6bb81aad1.png">

Having no issues when signing or building 
Can you please provide errors you might be getting and clear steps to reproduce the same results
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.1

! Doctor found issues in 1 category.
```

</details>

**Comment by peterIrving** [comment]
Thanks for your super quick response, I appreciate it.

I take it the example app when creating the flutter plugin is the Runner app in the Xcode project structure?

The goal is to be able to run the example in Xcode and debug the plugin at the same time. Currently, because the signing issues I cannot run the example in Xcode and am compiling and running in Android studio every time. 

Attempting to sign
<img width="1191" alt="Screen Shot 2020-10-29 at 11 03 56 AM" src="https://user-images.githubusercontent.com/46767992/97601503-3ce1e680-19d8-11eb-9109-3e19f58b7fa1.png">

Plugin code
<img width="1240" alt="Screen Shot 2020-10-29 at 11 13 58 AM" src="https://user-images.githubusercontent.com/46767992/97601589-55ea9780-19d8-11eb-8a93-b2f05fdc3405.png">

I signed the plugin like you did, but Xcode will not build due to "Signing for "Runner" requires a development team. Select a development team in the Signing & Capabilities editor."

Any ideas?

**Comment by peterIrving** [comment]
An additional note, trying to run a regular flutter project natively in Xcode also gives me the same bug.

**Comment by TahaTesser** [comment]
hI @peterIrving 
Have no issues running signed app from code on a physical device and if you're using experiencing the same issue with a regular flutter project, it might be something from your side, make sure you have the proper account signed in, you have the necessary permissions as well, log out of the apple account and log in

**Comment by peterIrving** [comment]
Taha, thank you for all of your help. What ended up working for me was updating from MacOS 10.15.6 to 10.15.7. Not sure if it was the OS version or if the update did something to refresh my credentials.

For anyone curious, I am running
iOS 14.1
MacOS 10.15.7
Xcode 12.1
Flutter 1.22.2 

Thanks!
