### ISSUE TITLE
drawer: misaligned background on Android api 22 device

### ISSUE THREAD

**Issue by moodstubos** [flutter/flutter#69235]
A customer reported an odd display of main drawer. I was not able to reproduce this on my devices nor emulator. Today he send me the device and I can confirm there is a strange issue with flutter drawer. 
It **only** happens in portrait mode. 

**screenshot**

![issue](https://user-images.githubusercontent.com/5072232/97488993-467b3800-195f-11eb-9d76-d9053e37e888.gif)

landscape
![sec](https://user-images.githubusercontent.com/5072232/97489562-fd77b380-195f-11eb-8d5b-40e23c86be13.gif)

**minimal code example**
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home:Scaffold(
          appBar: AppBar(),
          body: Text("drawer issue"),
        drawer: Drawer(child: Container(color: Colors.red),),),
    );
  }
}
```

**real device:** 

- Medion LIFETAB S1036X
- android-x86
- Android 5.1.1 (API 22)

**flutter doctor -v**

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale de-DE)
    • Flutter version 1.22.2 at E:\SDK\flutter
    • Framework revision 84f3d28555 (13 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\SDK\android\
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\X\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (2 available)
    • LIFETAB S1036X (mobile)     • DEA6T026B8    • android-x86 • Android 5.1.1 (API 22)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```
also testet with current beta (1.23.0-18.1.pre) as well as master (1.24.0-4.0.pre.119).
The same issue comes up with an endDrawer (just the other way around).

**Comment by darshankawar** [comment]
@moodstubos 
Although I don't have the said device (api 22), I tried your code sample on Emulator with api 19 on latest stable, but didn't see the issue you mentioned.

[69235.mov.zip](https://github.com/flutter/flutter/files/5456821/69235.mov.zip)

Can you confirm if this is only happening on devices with api 22 ? or below 21 and above 23 too have this issue ? Can you also check on any latest device you have if it persists ?
Thanks.

**Comment by moodstubos** [comment]
@darshankawar 
I tried it on all my real devices, api 30, 29, 28, 25. No problems there. I also tried on **EMULATOR api 22** - no problem. 
Only on this api 22 real device. 

After some investigations it seems there is an issue with Align widthFactor in combination with RepaintBoundary. 

in flutter/packages/flutter/lib/src/material/**drawer.dart** I have changed the following lines

```
              Align(
                alignment: _drawerOuterAlignment,
                child: Align(
                  alignment: _drawerInnerAlignment,
                  /* widthFactor: _controller.value, */
   --->               widthFactor: min(_controller.value, 0.9999),      <----   widthFactor should not become 1.0
                  child: /* RepaintBoundary(     <---- comment out
                    child: */
                      FocusScope(
                    key: _drawerKey,
                    node: _focusScopeNode,
                    child: widget.child,
                  ),
                  /*),*/
                ),
              ),
```
This works.

**Comment by moodstubos** [comment]
I know testet on a nexus 7 (2012): 

- Nexus 7
- android-arm
- Android 5.1.1 (API 22)

also on this devices it works like expected even though it has the same api level (22) as the problematic device. Only difference is the smaller screen and **android-arm** instead of **android-x86**

I think it is a low level issue.

**Comment by darshankawar** [comment]
Thanks for the device details. I will leave it open as device-specific, since it's only happening on certain api level device, which I don't have to verify.

**Comment by moodstubos** [comment]
is there anything i could do at the moment?
I could do some tests on this device or send log files - something like this.

**Comment by camsim99** [comment]
This issue is prioritized P3 given the number of Android devices impacted. If you see this on other devices, please leave a comment!
