### ISSUE TITLE
Pre-submit LUCI checks from PRs are not informative before builds get scheduled

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#69242]
Pre-submit LUCI tasks are triggered via buildbucket for different repos. If builds are successfully scheduled, the `Checks` page will provide link to the specific build ID.

However, when the queue time is high, and the build is in the queue before scheduled, the above link will simply link to go/flutter-build. This is also the case when a build fails before scheduled. It is not easy/clear to tell what is going on for such cases.
<img width="722" alt="Screen Shot 2020-10-28 at 2 30 43 PM" src="https://user-images.githubusercontent.com/54558023/97499142-97bd0480-192a-11eb-9361-e47e4f293525.png">

A more informative link or message should be helpful. such as direct link to [task ID](https://chromium-swarm.appspot.com/task?id=4f89e3965803b110&o=true&w=true) rather than [build ID](https://ci.chromium.org/p/flutter/builders/try/Windows%20Plugins/940?).

**Comment by godofredoc** [comment]
Try put some text telling people the build hasn't been schedule yet will be a huge improvement to the UI

**Comment by godofredoc** [comment]
We'll need help from @kf6gpe to update the hook information to present a better message.

**Comment by kf6gpe** [comment]
Sounds good. @godofredoc I'll coordinate with you directly.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
