### ISSUE TITLE
Consider style guide addition for shorthand functions with return type void

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#6924]
I just read the style guide and wondered if it would a good idea to mention that shorthand function syntax should not be used for functions with return type `void`

**bad**

    set someProp(String value) => _someProp = value

    void foo() => doSomething();

**Comment by Hixie** [comment]
Why shouldn't it be used for functions that return void?

**Comment by zoechi** [comment]
because shorthand function implicitly return the result of the expression.
@lhrn mentioned that no PR would pass his review containing such code

**Comment by Hixie** [comment]
If the return type doesn't match, then the analyzer will report it. But if it does match, e.g. in your `doSomething` example assuming `doSomething` returns void itself, I don't understand the problem.

**Comment by zoechi** [comment]
Right, it does for 

```dart
void foo() => doSomething();
```

but it doesn't for 
```dart
set someProp(String value) => _someProp = value
```

Perhaps that is the actual bug to report?

**Comment by Hixie** [comment]
If the analyzer doesn't warn about the type mismatch in that case then yes, that seems like a good thing to report to the analyzer team.
