### ISSUE TITLE
about video hole support in flutter

### ISSUE THREAD

**Issue by lxb0478** [flutter/flutter#69258]
Hi, I'm wondering if there is video hole support in flutter. I tried to use video plugin which is implemented via texture, the video quality is not as good as playing with native video player. So I want to make a hole in graphic plane and play video in video plane. Seems that this method needs to modify flutter engine, will engine support this in the future? I think this method has better performance and better graphic quality.

**Comment by stuartmorgan** [comment]
The engine already supports adding native views to the rendering tree: https://flutter.dev/docs/development/platform-integration/platform-views

**Comment by lxb0478** [comment]
I think platform view is still using texture method, which is the same as video plugin, and also has low image quality issue

**Comment by stuartmorgan** [comment]
"Hybrid composition requires Flutter 1.22 (version 1.22.2 is recommended). This mode appends the native android.view.View to the view hierarchy."
