### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Jparrgam** [flutter/flutter#69250]
Hi, I have the following error reported in firebase crashlytics, do you have any idea what could cause it?

`Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for io.flutter.view.FlutterCallbackInformation io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(long) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation and Java_io_flutter_embedding_engine_FlutterJNI_nativeLookupCallbackInformation__J)
       at io.flutter.embedding.engine.FlutterJNI.nativeLookupCallbackInformation(FlutterJNI.java)
       at io.flutter.view.FlutterCallbackInformation.lookupCallbackInformation(FlutterCallbackInformation.java:30)`

**Comment by darshankawar** [comment]
@Jparrgam 
Please provide more information on the issue. Is it coming from production app ? Can you provide a minimal reproducible use case that could possibly throws this issue in non-prod environment ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by meomap** [comment]
I've just got the same issue. Fixed it by moving `FlutterEngine` initialization to before callback lookup. Please see here for reference.
https://github.com/flutter/plugins/commit/de56da50ca78ef275a95b4e59ce8d5e119eadd7a#diff-e57a1a7ffb729ad174b597626202429c1c87e4168e19b2aa9decc1be84e8777b
