### ISSUE TITLE
Support newer quiver version

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#6926]
```
 (master) $ flutter packages upgrade
Running 'flutter packages upgrade' in myapp...           
Incompatible version constraints on quiver:
- bwu_ng_mdl 0.1.0 depends on version ^0.22.0
- fhir_client 0.1.0 depends on version ^0.22.0
- flutter_test 0.0.0 depends on version ^0.21.4
pub upgrade failed (1)
```

**Comment by eseidelGoogle** [comment]
I suspect a new version just works.  If someone is interested in fixing, the file in question should be:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml

```
flutter update-packages --upgrade
flutter analyze --flutter-repo
flutter test --flutter-repo
```
should tell you if the new package works or not.  Also Travis would do so when posting the PR.

**Comment by cbracken** [comment]
Fixed (or at least improved based on the discussion in #6940) in #7349.
