### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildRelease'

### ISSUE THREAD

**Issue by mohamedhasan2002** [flutter/flutter#69275]
I'm getting this issue when I tried to clone a git project. A basic app without clone I am able to build...
OS: Linux ubuntu 64bit
IDE: Visual studio code
source:https://github.com/ibmkynl/ChitChat

`hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/ChitChat-master$ flutter build apk
Running "flutter pub get" in ChitChat-master...                  1,730ms
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more: https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.4/lib/src/datetime_picker_theme.dart:15:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DatePickerTheme({                                               
        ^^^^^^^^^^^^^^^                                                 
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,                                           
        ^^^^^^^^^                                                       
../../snap/flutter/common/flutter/packages/flutter/lib/src/cupertino/route.dart:547:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({                                 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/extended_image.dart:713:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^                       
../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {                      
                        ^^                                              
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/hasan/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 900
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/home/hasan/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 51s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      51.9s
Gradle task assembleRelease failed with exit code 1`

Flutter doctor -v output:
`hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/ChitChat-master$ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-4.0.pre.138, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.24.0-4.0.pre.138 at /home/hasan/snap/flutter/common/flutter
    • Framework revision 13896b3bd1 (4 hours ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/hasan/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

**Comment by darshankawar** [comment]
@mohamedhasan2002 
This seems to be an issue with the third party plugin you are using, flutter_datetime_picker`. Please consider opening this issue in plugin owner's repo : https://github.com/Realank/flutter_datetime_picker/issues/128.

Closing this as not an issue with flutter. If you disagree or think removing 3rd party plugins is still causing the issue, write in comments and I'll reopen.
Thanks.
