### ISSUE TITLE
Xcode12 can not run

### ISSUE THREAD

**Issue by Lanch92** [flutter/flutter#69279]
Runner's architectures (armv7, arm64) include none that iPhone 8 can execute (Intel 64-bit).

**Comment by TahaTesser** [comment]
Hi @Lanch92 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample and steps to reproduce 
Thank you

**Comment by Tortu-Ch** [comment]
did you checke flutter doctor -v ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
