### ISSUE TITLE
An annotation error in engine/lib/ui/painting.dart

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#69282]
location: `engine/lib/ui/painting.dart : 4408`

![image](https://user-images.githubusercontent.com/26687012/97540627-d9b77a80-19fe-11eb-96aa-189c8884a521.png)

Here should use `Colors.white` to get a white color, not `Color.white`. It maybe a little mistake.

**Comment by pedromassangocode** [comment]
Can confirm that there is a typo in the docs:
https://github.com/flutter/engine/blob/ca05bdccc171f87a9804532013292c90544d384f/lib/ui/painting.dart#L4408
