### ISSUE TITLE
TextField can't handle writing in both RTL and LTR

### ISSUE THREAD

**Issue by naamapps** [flutter/flutter#69288]
## Problem Description
When the app directionality is RTL and writing text that is both RTL and LTR the TextField is going crazy and can't handle spaces and alignments.
I have found out a few things while testing this behaviour: 
1. If I write in a RTL language and the directionality of the app is also RTL, the textfield is working fine. However, if I write in a LTR language and the directionality of the app is RTL - the issue come up.
The issue also persists the other way around - Writing in RTL when the app the directionality of the app is LTR.
3. Once the issue comes up - the TextField will not go back to the normal behaviour, even if I write in RTL.
2. If I set `maxLines` to `null` in the constructor of the textField, the issue seems to go away.

<details>
  <summary>Flutter doctor -v</summary>
[✓] Flutter (Channel master, 1.24.0-4.0.pre.138, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-IL)
    • Flutter version 1.24.0-4.0.pre.138 at /Users/naamapps/flutter
    • Framework revision 13896b3bd1 (7 hours ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/naamapps/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM N985F (mobile) • R58N75RG9NJ • android-arm64 • Android 10 (API 29)

• No issues found!

</details>

<details>
  <summary>Sample code</summary>

Material App widget:
```
import 'package:flutter/material.dart';
import 'package:test_project/test_widget.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home:
          Directionality(textDirection: TextDirection.rtl, child: TestWidget()),
    );
  }
}
```
The TextField widget:
```
import 'package:flutter/material.dart';

class TestWidget extends StatefulWidget {
  TestWidget({Key key}) : super(key: key);

  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  final TextEditingController _textEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Center(
        child: Container(
          margin: EdgeInsets.fromLTRB(
            20,
            0,
            20,
            MediaQuery.of(context).viewInsets.bottom,
          ),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8),
            color: Colors.grey[200],
          ),
          padding: EdgeInsets.only(left: 16, right: 8),
          child: ConstrainedBox(
            constraints: BoxConstraints(minHeight: kToolbarHeight),
            child: Row(
              children: [
                CircleAvatar(
                  radius: 20,
                  backgroundImage: NetworkImage(
                      'https://cdn.pixabay.com/photo/2020/10/01/09/35/bee-5618012_1280.jpg'),
                ),
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.only(left: 16, right: 8),
                    child: TextField(
                      maxLines: 1, // Set this to null to make the issue go away!
                      textInputAction: TextInputAction.send,
                      keyboardType: TextInputType.text,
                      controller: _textEditingController,
                      decoration: InputDecoration(
                          hintText: 'הגב', border: InputBorder.none),
                    ),
                  ),
                ),
                InkWell(
                  onTap: () {},
                  child: Container(
                    padding:
                        const EdgeInsets.symmetric(vertical: 8, horizontal: 8),
                    child: Text(
                      'שלח',
                      style: TextStyle(color: Colors.blue[300]),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _textEditingController.dispose();
    super.dispose();
  }
}

```

</details>

**Comment by darshankawar** [comment]
@naamapps Can you elaborate on `if I write in a LTR language and the directionality of the app is RTL - the issue come up.`

**Comment by naamapps** [comment]
@darshankawar Sorry I forgot to upload the video I recorded for the issue. 
Here it is

[RTL issue.mp4.zip](https://github.com/flutter/flutter/files/5457507/RTL.issue.mp4.zip)

Hope it's clearer now

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.82, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-4.0.pre.82 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e5814756a2 (2 days ago), 2020-10-27 01:47:03 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!

```

</details>

[69288_mast.mp4.zip](https://github.com/flutter/flutter/files/5458378/69288_mast.mp4.zip)

**Comment by naamapps** [comment]
@darshankawar Although you already put those tags, I'm afraid the video you sent shows a different (and still relevant) bug (the one where you can't delete spaces).
To see the bug I've talked about you need to write in both RTL and LTR languages at same time.
You only have written in English, which does have a bug as well with RTL directionality, bug not the bug I showed in my video.
Please try again, and this time write in Hebrew (or any other RTL language) and English.
Thank you

**Comment by LongCatIsLooong** [comment]
I'm planning to fix this in https://github.com/flutter/flutter/pull/68166.

**Comment by naamapps** [comment]
Hi @LongCatIsLooong 
I was curious to ask if there is any progress on this?
Thank you very much

**Comment by LongCatIsLooong** [comment]
Ah I thought the problem was `_WhitespaceDirectionalityFormatter` not being applied but it seems the problem is with `_WhitespaceDirectionalityFormatter` itself. 
@GaryQian could you take a look?

**Comment by naamapps** [comment]
Hey! 
Any updates on this?
