### ISSUE TITLE
Custom background SnackBar

### ISSUE THREAD

**Issue by moisesvs** [flutter/flutter#6928]
I was talking with @eseidel about how I could change the background snackbar and he commented me that I will open a support issue. I want to change background of the snackbar.

I was trying the below code:
```
scaffoldKey.currentState.showSnackBar(new SnackBar(
    content: new DecoratedBox(
        decoration:
            new BoxDecoration(backgroundColor: ColorsApp.COLOR_BBVA_1),
        child: new Text(textError))));
```

But that code don't change the background...

What is the way for doing this?

**Comment by eseidelGoogle** [comment]
It looks like you can change it today by changing the Theme:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L154

We also could add a specific parameter for changing just this aspect.  Thoughts @HansMuller @Hixie?

**Comment by HansMuller** [comment]
The snackbar's background color appears to be wired down per the Material spec:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L204

It would be easy enough to make the snack bar background configurable.
