### ISSUE TITLE
my flutter app do not run in iphone device from android studio 

### ISSUE THREAD

**Issue by mohammad-alshelleh** [flutter/flutter#69289]
> When I run for the application from the xcode it works, and same thing in simulator , but when I do the run from the Android Studio in iphone device, It displays a white screen and then shuts down, and it appears like this 

`Automatically signing iOS for device deployment using specified development team in Xcode project: 7R6D66J964
Running Xcode build...
Xcode build done.                                           11.2s
Installing and launching...
Error launching application on iPhone.`

> flutter doctor
```
Admins-MBP:mmmmmmm admin$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-2.0.pre.55, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!

```

**Comment by darshankawar** [comment]
@mohammad-alshelleh 
See if [this](https://github.com/flutter/flutter/issues/66862#issuecomment-711111238) solution works for you.

**Comment by mohammad-alshelleh** [comment]
@darshankawar 
thank you , i updated flutter , But it became an application after run in my device and killed from history and open again , do not open , i do not have any error in code , why ?

**Comment by darshankawar** [comment]
@mohammad-alshelleh sorry didn't understand your comment. Is your original issue of app not running on iphone is resolved or not yet ?

**Comment by mohammad-alshelleh** [comment]
yes resolved

**Comment by darshankawar** [comment]
Closing this as resolved.
