### ISSUE TITLE
On click to push notification not navigate to other page why?

### ISSUE THREAD

**Issue by marqueetest** [flutter/flutter#69293]
![Screenshot 2020-10-29 152846](https://user-images.githubusercontent.com/59277680/97554783-4762a700-19fd-11eb-98e4-f3d28c2137f7.jpg)

I configure everything according to firebase document for push notification and we got notification message on the simulator but on click to the notification is not navigate to other pages in flutter why. what I am doing wrong in below code. 
1) add the google-service.json file.
2) add dependencies and apply the plugin to app and project level Gradle file in a flutter.
3) Add intent filter inside of the activity element of your AndroidManifest.

<intent-filter>
  <action android:name="FLUTTER_NOTIFICATION_CLICK" />
  <category android:name="android.intent.category.DEFAULT" />
</intent-filter> 

there code for FCM in main.dart file
========================================
import 'package:flutter/material.dart';
  import 'package:firebase_messaging/firebase_messaging.dart';
  import 'package:firebase_database/firebase_database.dart';

  void main() => runApp(new MyApp());

  class MyApp extends StatefulWidget {
    @override
    _MyAppState createState() => _MyAppState();
  }

  class _MyAppState extends State<MyApp> {
    String textValue = 'Hello World !';
    FirebaseMessaging firebaseMessaging = new FirebaseMessaging();

    @override

    void initState() {
	  initFirebase();
	  initFlutterLocalNotification();
	}

    void initFirebase() {
     _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        log("onMessage: $message");
        showNotification(
            title: message['notification']['title'],
            body: message['notification']['body'],
            payload: message['data']['type']);
        //_navigateToDetail(message);
      },
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        _navigateToDetail(message);
        log("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        log("onResume: $message");
        _navigateToDetail(message);
      },
    );

    _firebaseMessaging.requestNotificationPermissions(const IosNotificationSettings(sound: true, badge: true, alert: true, provisional: true));
    _firebaseMessaging.onIosSettingsRegistered.listen((IosNotificationSettings settings) {

      print("Settings registered: $settings");
    });
    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      print("Push Messaging token: $token");
      setState(() {
        firebaseDeviceToken=token;
        print('Firebase Token :- $firebaseDeviceToken');
        isLogin();
      });
    });
  }
  
  void initFlutterLocalNotification() {
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');

    final IOSInitializationSettings initializationSettingsIOS = new IOSInitializationSettings(defaultPresentAlert: true,defaultPresentBadge: true,defaultPresentSound: true,requestAlertPermission: true,requestBadgePermission: true,requestSoundPermission: true);
    const MacOSInitializationSettings initializationSettingsMacOS = MacOSInitializationSettings(requestAlertPermission: false,requestBadgePermission: false,requestSoundPermission: false);
    final InitializationSettings initializationSettings = InitializationSettings(android: initializationSettingsAndroid,iOS: initializationSettingsIOS,macOS: initializationSettingsMacOS);
    flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }

  void _navigateToDetail(Map<String, dynamic> message) {
    print('Message--##=> ::- $message');
    Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => CompanyProtocols()));
  }

  showNotification({String title, String body, String payload}) async {
    print('show');
    final AndroidNotificationDetails androidPlatformChannelSpecifics = AndroidNotificationDetails('your channel id','your channel name','your channel description',
      importance: Importance.max, priority: Priority.high, when: DateTime.now().millisecondsSinceEpoch - 120 * 1000,
    );
    const IOSNotificationDetails iOSPlatformChannelSpecifics = IOSNotificationDetails();

    const MacOSNotificationDetails macOSPlatformChannelSpecifics = MacOSNotificationDetails();

    final NotificationDetails platformChannelSpecifics = NotificationDetails(android: androidPlatformChannelSpecifics,iOS: iOSPlatformChannelSpecifics,macOS: macOSPlatformChannelSpecifics);

    await flutterLocalNotificationsPlugin.show(0, title, body, platformChannelSpecifics, payload: 'WeCARE');
  }
  
  
  Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) {
  if (message.containsKey('data')) {
    // Handle data message
    final dynamic data = message['data'];
    log("NOTIFICATION:::$data");
  }

  if (message.containsKey('notification')) {
    // Handle notification message
    final dynamic notification = message['notification'];
    log("NOTIFICATION:::$notification");
  }

  return Future<dynamic>.value(message);
  // Or do other work.
}

**Comment by darshankawar** [comment]
@marqueetest 
Firebase issues are tracked in this repo: https://github.com/FirebaseExtended/flutterfire/issues.
Closing this from here.
