### ISSUE TITLE
Querying the current media using MediaQuery.of will cause your widget to rebuild automatically whenever the MediaQueryData changes

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#69291]
code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int i = 0;

  @override
  Widget build(BuildContext context) {
    MediaQueryData mediaQuery = MediaQuery.of(context);

    print('----build:$i');
    i++;

    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Center(
        child: TextField(),
      ),
    );
  }
}

```
gif:
![image](https://user-images.githubusercontent.com/15923901/97552719-931e4c00-1a0f-11eb-9190-b1da5a6744b9.png)

And i saw this：
![image](https://user-images.githubusercontent.com/15923901/97550502-b693c780-1a0c-11eb-96a4-4f85dba17fa9.png)

Is there any way for me to use MediaQuery.of but avoid rebuild？

**Comment by darshankawar** [comment]
@lizhuoyuan 
Your question is better suited for StackOverflow.  Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
