### ISSUE TITLE
DartDoc failed because Diagnostics

### ISSUE THREAD

**Issue by mit-73** [flutter/flutter#69290]
## Where does the error

dart: `>=2.10.0 <2.11.0`
flutter: `>=1.22.0 <2.0.0`
Using plugin: `webview_flutter: ^ 1.0.5`

I think these errors come from `foundation/diagnostics.dart`, as there are some shortcomings in the documentation.

## Steps to Reproduce

1. Run `dartdoc`
2. ...
3. dartdoc failed
<details>
  <summary>Logs</summary>

> admins-MBP:Tinkoff-Acquiring-SDK-Flutter mit$ dartdoc
> Documenting tinkoff_acquiring...
> Initialized dartdoc with 563 libraries in 58.8 seconds
> Generating docs for library tinkoff_acquiring_core from package:tinkoff_acquiring/tinkoff_acquiring_core.dart...
> Generating docs for library tinkoff_acquiring_ui from package:tinkoff_acquiring/tinkoff_acquiring_ui.dart...
>   error: unresolved doc reference [new DiagnosticsNode.message]
>     from tinkoff_acquiring_ui.WebView3DS.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>     in documentation inherited from diagnostics.DiagnosticableTree.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>   error: unresolved doc reference [DiagnosticsProperty<Object>]
>     from tinkoff_acquiring_ui.WebView3DS.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>     in documentation inherited from diagnostics.DiagnosticableTree.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>   error: unresolved doc reference [RenderTable.debugDescribeChildren]
>     from tinkoff_acquiring_ui.WebView3DS.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>     in documentation inherited from diagnostics.DiagnosticableTree.debugDescribeChildren: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3457:25)
>   error: unresolved doc reference [int]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [DiagnosticsTreeStyle]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [ColorProperty]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [Color]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [IconDataProperty]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [IconData]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [TransformProperty]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
>   error: unresolved doc reference [Matrix4]
>     from tinkoff_acquiring_ui.WebView3DS.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/widgets/framework.dart:509:8)
>     in documentation inherited from diagnostics.Diagnosticable.debugFillProperties: (file:///Users/mit/SDK/flutter/versions/1.22.0/packages/flutter/lib/src/foundation/diagnostics.dart:3342:8)
> Validating docs...
>   warning: dartdoc generated a broken link to: README.ru.md, linked to from package-tinkoff_acquiring: file:///Users/mit/Projects/Tinkoff-Acquiring-SDK-Flutter
> found 1 warning and 11 errors
> Documented 2 public libraries in 5.2 seconds
> 
> dartdoc failed: dartdoc encountered 11 errors while processing..
> #0      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:231:9)
> <asynchronous suspension>
> #1      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:15)
> #2      _rootRun (dart:async/zone.dart:1190:13)
> #3      _CustomZone.run (dart:async/zone.dart:1093:19)
> #4      _runZoned (dart:async/zone.dart:1630:10)
> #5      runZonedGuarded (dart:async/zone.dart:1618:12)
> #6      Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:498:5)
> #7      main (file:///b/s/w/ir/cache/builder/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:24:11)
> <asynchronous suspension>
> #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> 

</details>

**Comment by darshankawar** [comment]
@mit-73 
Assuming you are using [dartdoc](https://pub.dev/packages/dartdoc) plugin, issues related to it may have to report in this repo : https://github.com/dart-lang/api.dart.dev/issues

**Comment by mit-73** [comment]
Okay, I have [duplicated this issue](https://github.com/dart-lang/api.dart.dev/issues/79)

**Comment by darshankawar** [comment]
@mit-73 Thanks. I am closing this from here. Feel free to comment if you think it need to be kept open in this repo.
