### ISSUE TITLE
Analyze flutter/plugins as part of flutter/flutter tests

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#69309]
This will be a stepping stone towards: https://github.com/flutter/flutter/issues/33440

Running the entire flutter/plugins test suite is too slow for it to be included as-is in flutter/tests. Though running just the analysis step should detect early:

- Dart build errors.
- New failing lints.
- Dependency resolution issues.

Work plan:

- [x] Remove custom analysis_options and fix all result lint errors for in_app_purchase (done https://github.com/flutter/plugins/pull/3220).
- [x] Remove custom analysis_options and fix all result lint errors for camera (in progress https://github.com/flutter/plugins/pull/3229).
- [x] Remove custom analysis_options and fix all result lint errors for video_player_web (https://github.com/flutter/plugins/pull/3238).
- [x] Remove custom analysis_options and fix all result lint errors for url_launcher_web (https://github.com/flutter/plugins/pull/3238).
- [x] Remove custom analysis_options and fix all result lint errors for google_maps_flutter_web (https://github.com/flutter/plugins/pull/3238).
- [x] Add a flutter/flutter sharded test for executing the flutter/plugins analysis phase (https://github.com/flutter/flutter/pull/70887, https://github.com/flutter/flutter/pull/71166).
- [x] Configure a Luci builder for running the new test shard.
- [x] Set-up a process that promises regular updates for flutter/plugins version we're testing against.
- [x] Make the new test a tree blocker.

**Comment by amirh** [comment]
Removing the custom analysis_options for video_player_web, url_launcher_web, and google_maps_flutter_web is blocked on https://github.com/flutter/flutter/issues/55000 which is blocked on https://github.com/flutter/flutter/issues/41563.

@ditman Until these are resolved, what do you think about working around with conditional imports?

**Comment by ditman** [comment]
@amirh I'll try [this technique](https://github.com/flutter/flutter/issues/41563#issuecomment-626765363) in the Google Maps plugin, which is the one I've modified the most during the last couple of weeks. I'll try to post a PR by EOD today to see if it's enough for us to remove the custom analysis files. If it works well, I'll do it for the other two packages.

**Comment by amirh** [comment]
The tactic for this issue has been changed a little.
Based on https://github.com/flutter/tests/pull/66#issuecomment-730008377 (TL;DR this test is too slow, we don't want it to bite into the flutter/tests run time budget) we're going to add it as it's own flutter/flutter test shard instead of as part of flutter/tests.

Based on post-submit feedback for https://github.com/flutter/flutter/pull/70887 we will be pinning the flutter/plugins commit hash that's tested, and we need some process for regularly updating this pinned version.

**Comment by amirh** [comment]
We set-up an internal weekly rotation that includes rolling flutter/plugins -> flutter/flutter as a temporary thing until we setup an autoroller (I'm talking to the Skia autoroller person about that).

At this point we are ready to mark the tests as tree blocking.

**Comment by amirh** [comment]
The test is a tree blocker following https://github.com/flutter/flutter/pull/71502

Marking this issue as closed.

**Comment by amirh** [comment]
An auto-roller is now set up at: https://autoroll.skia.org/r/flutter-plugins-flutter-autoroll
