### ISSUE TITLE
regression in maxAdbTotalmaxRss complex_layout_scroll_perf__devtools_memory

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69304]
https://flutter-flutter-perf.skia.org/e/?begin=1603909324&end=1603931718&keys=X7469377cae2d91a391bef4f1e3972ea6&num_commits=50&request_type=1&xbaroffset=22247

Started at https://github.com/flutter/flutter/pull/69237; cc @jonahwilliams. I'm not really sure why only this regressed, and not a number of benchmarks, so I'm not convinced that this is the PR that caused it.

**Comment by zanderso** [comment]
It does look related. The fix adding back `--use-existing-app` caused the memory usage to go back up to the level that it had been at for quite awhile before @jonahwilliams started working on `drive`. Closing as working as expected.
