### ISSUE TITLE
`barrierDismissible` doesn't prevent Android back button usage

### ISSUE THREAD

**Issue by mzegar** [flutter/flutter#69325]
## Steps to Reproduce

1. Create some modal/page that has `barrierDismissible` set to `false`
2. Open this modal/page
3. On an Android device, hit the `back` button
4. The modal will be dismissed.

Expected results: The modal shouldn't be dismissed.
Actual results: The modal is dismissed.

**Comment by darshankawar** [comment]
@mzegar 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.
