### ISSUE TITLE
flutter pub get failed

### ISSUE THREAD

**Issue by hatimkh20** [flutter/flutter#69329]
Running "flutter pub get" in calculator...
pub get failed (1; no message)
Exited (1)

**Comment by swebreza** [comment]
Can you please show us your `pubspec.yaml` file, that will be helpful to resolve your issue

**Comment by darshankawar** [comment]
@hatimkh20 
Provide more information on the issue with details like `flutter doctor -v` and console log that shows why it's failing. What are the steps you took that led to this issue ?

**Comment by hatimkh20** [comment]
> @hatimkh20
> Provide more information on the issue with details like `flutter doctor -v` and console log that shows why it's failing. What are the steps you took that led to this issue ?

here is my flutter doctor code
F:\Flutter\Project>flutter doctor -v
[√] Flutter (Channel master, 1.24.0-4.0.pre.144, on Windows, locale en-US)
    • Flutter version 1.24.0-4.0.pre.144 at F:\Flutter\flutter
    • Framework revision 470346f775 (16 hours ago), 2020-10-29 09:56:28 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by hatimkh20** [comment]
> @hatimkh20
> Provide more information on the issue with details like `flutter doctor -v` and console log that shows why it's failing. What are the steps you took that led to this issue ?

mate It was fine back 2 days but yesterday i tried to run my old project so in debug console "flutter pub get failed" message received and then i tried to create another project through cmd so the same error also came i also tried to upgrade my flutter version but no outcome :(

**Comment by hatimkh20** [comment]
> Can you please show us your `pubspec.yaml` file, that will be helpful to resolve your issue

name: calculator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by darshankawar** [comment]
@hatimkh20 
Can you confirm if the failure isn't due to network ? Also, we'll need logs that will show some kind of exceptions. Can you provide `flutter run --verbose` ?

**Comment by hatimkh20** [comment]
> @hatimkh20
> Can you confirm if the failure isn't due to network ? Also, we'll need logs that will show some kind of exceptions. Can you provide `flutter run --verbose` ?

no it's not due to network issue. wait a minute I also run this command

**Comment by hatimkh20** [comment]
> @hatimkh20
> Can you confirm if the failure isn't due to network ? Also, we'll need logs that will show some kind of exceptions. Can you provide `flutter run --verbose` ?

F:\Flutter\Project\calculator>flutter run --verbose
[ +190 ms] executing: [F:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +80 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 470346f77591d38234fa2930583a6f4f582e77e7
[   +1 ms] executing: [F:\Flutter\flutter/] git tag --points-at HEAD
[  +52 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [F:\Flutter\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +77 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.24.0-3.0.pre-144-g470346f775
[  +12 ms] executing: [F:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [F:\Flutter\flutter/] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +94 ms] executing: [F:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +70 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +75 ms] List of devices attached
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +63 ms] No supported devices connected.
[  +15 ms] "flutter run" took 305ms.
[  +27 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:420:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1032:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:926:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:915:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:302:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +264 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[  +38 ms] exiting with code 1

**Comment by darshankawar** [comment]
@hatimkh20 
Provide `flutter precache -v` to see if it shows anything failing.

**Comment by hatimkh20** [comment]
> @hatimkh20
> Provide `flutter precache -v` to see if it shows anything failing. Also, are you able to run your app or create a new project ?

i was able to create new project and also run it 3 days back but not now. now I am not able to create new project nor I am able to view my old projects

**Comment by darshankawar** [comment]
@hatimkh20 
Did you upgrade Flutter between then and now ? It's hard to tell what exactly is causing issue if there's no error log. Try to find what exactly is causing the issue you are facing by seeing what worked earlier and why isn't working now. 

you may try to uninstall and install Flutter again to see if it works. Also, provide `flutter precache -v`

**Comment by hatimkh20** [comment]
> @hatimkh20
> Did you upgrade Flutter between then and now ? It's hard to tell what exactly is causing issue if there's no error log. Try to find what exactly is causing the issue you are facing by seeing what worked earlier and why isn't working now.
> 
> you may try to uninstall and install Flutter again to see if it works. Also, provide `flutter precache -v`

**Comment by hatimkh20** [comment]
> @hatimkh20
> Did you upgrade Flutter between then and now ? It's hard to tell what exactly is causing issue if there's no error log. Try to find what exactly is causing the issue you are facing by seeing what worked earlier and why isn't working now.
> 
> you may try to uninstall and install Flutter again to see if it works. Also, provide `flutter precache -v`

F:\Flutter\Project\calculator>flutter precache -v
[ +166 ms] executing: [F:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +370 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 470346f77591d38234fa2930583a6f4f582e77e7
[   +3 ms] executing: [F:\Flutter\flutter/] git tag --points-at HEAD
[+1587 ms] Exit code 0 from: git tag --points-at HEAD
[   +3 ms] executing: [F:\Flutter\flutter/] git describe --match *.*.* --first-parent --long --tags
[ +258 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[   +1 ms] 1.24.0-3.0.pre-144-g470346f775
[  +14 ms] executing: [F:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [F:\Flutter\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +97 ms] executing: [F:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +155 ms] F:\Flutter\flutter\bin\cache\artifacts\gradle_wrapper\gradle\wrapper\gradle-wrapper.jar mode: 33206
rw-rw-rw-.
[   +5 ms] F:\Flutter\flutter\bin\cache\artifacts\gradle_wrapper\gradlew mode: 33206 rw-rw-rw-.
[   +2 ms] F:\Flutter\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat mode: 33279 rwxrwxrwx.
[        ] F:\Flutter\flutter\bin\cache\flutter_gradle_wrapper.1567b886\gradlew.bat mode: 33279 rwxrwxrwx.
[  +40 ms] Downloading Android Maven dependencies...
[  +44 ms] executing: D:\Android Studio\jre\bin\java -version
[ +442 ms] Exit code 0 from: D:\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +5 ms] executing: F:\Flutter\flutter\bin\cache\flutter_gradle_wrapper.1567b886\gradlew.bat -b
F:\\Flutter\\flutter\packages\flutter_tools\gradle\resolve_dependencies.gradle --project-cache-dir
F:\Flutter\flutter\bin\cache\flutter_gradle_wrapper.1567b886 resolveDependencies
[+2009 ms] > Task :resolveDependencies UP-TO-DATE

                    BUILD SUCCESSFUL in 1s
[   +3 ms] Failed to download the Android dependencies
[  +22 ms] Downloading Android Maven dependencies... (completed in 2,508ms)
[  +20 ms] Downloading android-x86 tools...
[ +704 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-x86/artifacts.zip
md5 hash: LDEkOHOKKgo5OeK07MC2KA==
[+41621 ms] Downloading android-x86 tools... (completed in 42.3s)
[+4904 ms] Downloading android-x64 tools...
[ +518 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-x64/artifacts.zip
md5 hash: o/zeF4yQx7f+XAWSzWeTww==
[+47713 ms] Downloading android-x64 tools... (completed in 48.0s)
[+4418 ms] Downloading android-arm tools...
[ +318 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm/artifacts.zip
md5 hash: 2aCSZFiwCXG5QFfMUGlQhA==
[+132416 ms] Downloading android-arm tools... (completed in 132.7s)
[ +135 ms] Downloading android-arm-profile tools...
[ +259 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm-profile/artifa
cts.zip md5 hash: RWXccyFmOejKwvksj2QuEg==
[+113216 ms] Downloading android-arm-profile tools... (completed in 113.5s)
[ +241 ms] Downloading android-arm-release tools...
[ +319 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm-release/artifa
cts.zip md5 hash: LKqCv020iFcwzbgOPKnhcw==
[+21288 ms] Downloading android-arm-release tools... (completed in 21.6s)
[ +102 ms] Downloading android-arm64 tools...
[ +342 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm64/artifacts.zi
p md5 hash: MSEBl2SZ6QUtwZzRSoRuWQ==
[+18067 ms] Downloading android-arm64 tools... (completed in 18.4s)
[ +412 ms] Downloading android-arm64-profile tools...
[  +28 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm64-profile/arti
facts.zip md5 hash: cWY0h5gJNTpanH4vjNpGPA==
[+9137 ms] Downloading android-arm64-profile tools... (completed in 9.2s)
[ +132 ms] Downloading android-arm64-release tools...
[ +655 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-arm64-release/arti
facts.zip md5 hash: b25nUItdC8ah8yxVzI/lIQ==
[+6961 ms] Downloading android-arm64-release tools... (completed in 7.6s)
[ +120 ms] Downloading android-x64-profile tools...
[ +256 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-x64-profile/artifa
cts.zip md5 hash: akTsLu+aWdKyWWV2Vt8myA==
[+9518 ms] Downloading android-x64-profile tools... (completed in 9.8s)
[ +232 ms] Downloading android-x64-release tools...
[ +256 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-x64-release/artifa
cts.zip md5 hash: sJMGw+Byz/witISvVm5J0Q==
[+7328 ms] Downloading android-x64-release tools... (completed in 7.6s)
[ +264 ms] Downloading android-x86-jit-release tools...
[ +681 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/073263e39d1d12313c9622ac3788cc9f2b01f582/android-x86-jit-release/ar
tifacts.zip md5 hash: K8MiDfuAuSeVwW2nBjg14A==
[+12009 ms] Downloading android-x86-jit-release tools... (completed in 12.7s)
[ +403 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +15 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +234 ms] "flutter precache" took 438,000ms.
[ +285 ms] ensureAnalyticsSent: 254ms
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

**Comment by darshankawar** [comment]
@hatimkh20 Can you try to uninstall and install Flutter sdk again and see if it works ?
Thanks.

**Comment by hatimkh20** [comment]
> @hatimkh20 Can you try to uninstall and install Flutter sdk again and see if it works ?
> Thanks.

i already did that but same error getting

**Comment by darshankawar** [comment]
Can you try [this](https://github.com/flutter/flutter/issues/63112#issuecomment-691620053) solution and see if it works for you ?

**Comment by hatimkh20** [comment]
bro it still didn't work. now i am installing windows again :(

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
