### ISSUE TITLE
ci/licenses.sh script not being run in LUCI

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#69327]
This was previously run as part of the build_test on cirrus, however when the test was migrated to LUCI the license test was not included. As a temporary mitigation I added a cirrus step to explicitly run the license test (and updated the goldens). Once this issue is resolved, we should delete the licenses_test cirrus step added in https://github.com/flutter/engine/pull/22201.

**Comment by christopherfujino** [comment]
cc @godofredoc

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by kf6gpe** [comment]
Since we have a valid workaround, should we downgrade this?

**Comment by godofredoc** [comment]
Yes, let's move it to a P3

**Comment by godofredoc** [comment]
Licenses are now running as https://ci.chromium.org/p/flutter/builders/prod/Linux%20License
