### ISSUE TITLE
ReorderableListView should have a builder function like ListView.builder

### ISSUE THREAD

**Issue by UnicornsOnLSD** [flutter/flutter#69337]
## Use case

I'm using a ListView.builder for a list of ListTiles I have. These ListTiles are dismissible so they benefit from the index that ListView.builder provides. While I could manually map the list that I'm using to a list of widgets to give to ReorderableListView, that wouldn't be a very elegant solution. ListView.builder also benefits from the improved efficiency of not needing to render all the items at once, which would be especially helpful for me since each ListTile in my ListView.builder has an image, which would put a large load on the device if all of these images needed to be loaded at once.

Here's my ListView.builder, if you're interested:

```dart
          final List<MediaItem> queue = snapshot.data;
          return ListView.builder(
            controller: widget.scrollController,
            itemCount: queue.length,
            itemBuilder: (context, index) {
              return Dismissible(
                onDismissed: (direction) async {
                  queue.removeAt(index);
                  await AudioService.customAction("removeQueueItem", index);
                },
                key: Key(queue[index].id),
                child: ListTile(
                  leading: AlbumImage(
                    itemId: queue[index].id,
                  ),
                  title: Text(queue[index].title,
                      style: AudioService.currentMediaItem == queue[index]
                          ? TextStyle(color: Colors.lightGreen)
                          : null),
                  subtitle: Text(queue[index].artist),
                ),
              );
            },
          );
```

## Proposal

Like ListView, ReorderableListView should have a builder function to handle dynamically building widgets. This would work in the same way as ListView.builder.

**Comment by darshankawar** [comment]
@UnicornsOnLSD 
There's an [open](https://github.com/flutter/flutter/issues/66080) issue to track upcoming changes in `ReorderableListView`.
Please follow-up there for updates and any questions you may have.
Closing this as duplicate.
