### ISSUE TITLE
Add ARM simulator architecture slice to App.framework to support Apple Silicon

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#69334]
With the upcoming support for [Apple Silicon ARM simulators](https://github.com/flutter/flutter/issues/69334), App.framework (and add-to-app xcframework) needs a simulator ARM slice on ARM macOS.  Universal (fat) App.framework can no longer contain architectures for both `iphoneos` and `iphonesimulator` since they need to be build against different SDKs, but they can no longer be `lipo`d together (`lipo` complains both binaries contain arm64 and fails).

Primarily this is a problem when building the debug stub framework:
https://github.com/flutter/flutter/blob/cb67513f29dbf7f41818c9eb8cc42d845e243fca/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L106-L111

And in `flutter build ios-framework` that smush together plugin frameworks.

- [x] https://github.com/flutter/flutter/pull/69699 Output App.framework to different `iphoneos` and `iphonesimulator` directories
- [x] https://github.com/flutter/flutter/pull/69731 Refactor the build system to take either the `iphoneos` and `iphonesimulator` SDK from Xcode instead of trying to guess from the architectures (to stop assuming x86 == simulator).  Use it for `aot`
- [x] https://github.com/flutter/flutter/pull/69840 Remove `lipo`ing from debug stub framework step and only use the requested `iphoneos` or `iphonesimulator` SDK, not for both.  Refactor `flutter build ios-framework` as needed.
- [x] https://github.com/flutter/flutter/pull/69720 Deprecate `flutter build ios-framework --universal`
- [x] https://github.com/flutter/website/pull/4956 Update add-to-app website docs to use xcframework
- [x] https://github.com/flutter/samples/pull/582 Update add-to-app sample to use xcframework
- [x] https://github.com/flutter/flutter/issues/69733 Remove `flutter build ios-framework --universal`
- [x] https://github.com/flutter/flutter/issues/49562 Deprecate `flutter build aot`
- [ ] Add the ARM architecture slice

Flutter.framework engine work tracked in https://github.com/flutter/flutter/issues/64502

**Comment by jmagman** [comment]
Not sure this will be possible without also doing https://github.com/flutter/flutter/issues/36204 since the iphoneos and iphonesimulator ARM frameworks can't be lipo'd together.

**Comment by xster** [comment]
Moving the milestone to March

**Comment by entonio** [comment]
What will be the correct command line to build a module that can be integrated using Option A from https://flutter.dev/docs/development/add-to-app/ios/project-setup ?

**Comment by jmagman** [comment]
@entonio What do you mean, are you seeing a problem related to option A and the ARM simulator?
Don't forget to update `EXCLUDED_ARCHS ` in your host app https://flutter.dev/docs/development/add-to-app/ios/project-setup#apple-silicon-arm64-macs
