### ISSUE TITLE
rootBundle is giving exxeption

### ISSUE THREAD

**Issue by aifrosals** [flutter/flutter#69332]
The following code is giving me exception 

 `return await rootBundle.loadString('assets/images/null.png');`

the exception is:

`Exception: FormatException: Unexpected extension byte (at offset 0)`

**Comment by darshankawar** [comment]
@aifrosals 
Please check [this](https://api.flutter.dev/flutter/services/rootBundle.html) document on how to use `rootBundle` and see if you are properly added the assets in `pubspec.yaml`. 
If problem persists, provide `flutter doctor -v` and minimal reproducible code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by iinoten** [comment]
I'm not the owner, but I have the same symptoms.

code sample
``` code sample
Future<String> loadAsset() async {
  return await rootBundle.loadString('assets/Image/Icon.png');
}
```

```
assets:
    - assets/Image/Icon.png
```

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale ja-JP)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ntete\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\ntete\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • SCV36 (mobile) • 988ad0374259505444 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

`Image.assets('assets/Image/Icon.png')` ← This is displayed without any problem, so I don't think the path is wrong. What do you think
