### ISSUE TITLE
Flutter doctor claims flutter and dart plugins not installed; they are installed

### ISSUE THREAD

**Issue by stereotype441** [flutter/flutter#69330]
## Steps to Reproduce

1. Fresh mac
2. Install command line tools for XCode 12
3. Install Flutter
4. Install Android Studio
5. Open Android Studio, and without opening any project, click Configure -> Preferences, go to Plugins, and install the Dart and Flutter plugins.
6. Install XCode (I'm guessing this step isn't actually relevant, but it's what I did next)
7. Run "flutter doctor"

Expected behavior: Flutter doctor sees that the flutter and dart plugins are installed.
Observed behavior: Flutter doctor complains that they aren't installed.

Note: after doing this, I installed cocoapods, cloned a Flutter project from a git repo, and opened it in Android Studio.  I'm certain that the dart plugin is installed because I'm getting dart analysis results on my project.  I'm pretty sure the flutter plugin is installed because I have access to the flutter inspector, flutter outline, and flutter performance tabs through android studio.  Also, if I go back to android studio preferences and click "plugins", it shows both plugins as successfully installed.

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by husen-hn** [comment]
same problem.

system: Manjaro linux
Android Studio 4.1 (installed from aur)
Dart 2.9 (installed from aur)
Flutter 1.22 (Installed manually)

.bashrc
```
export PATH="$PATH:/home/username/.flutter/flutter/bin"
export ANDROID_HOME="/home/username/Android/Sdk"
export ANDROID_TOOLS="/home/username/Android/Sdk/tools"
export ANDROID_PLATFORM_TOOLS="/home/username/Android/Sdk/platform-tools"
PATH=$PATH:$ANDROID_HOME:$ANDROID_TOOLS:$ANDROID_PLATFORM_TOOLS
```
-> sudo flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /root/Android/Sdk/platforms. Directory was empty.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment]
@stereotype441 
Here's the [original](https://github.com/flutter/flutter/issues/67986) issue which was fixed and merged. 
Even though it says plugins not installed, they are just warnings, but you may continue to use those as usual in your project.
https://github.com/flutter/flutter/issues/67986#issuecomment-707881534
https://github.com/flutter/flutter/issues/67986#issuecomment-707511812
You want check by switching to latest master version and see if this is fixed.

Closing this as duplicate.
