### ISSUE TITLE
"Mac stable build_gallery" failed with ruby dep when previous build on branch succeeded

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#69341]
This test failed because it could not find bundler on 10/29 with the flutter/flutter_1_22_0 recipe, while the previous build with the same recipe which ran on 10/21 passed https://ci.chromium.org/p/flutter/builders/prod/Mac%20beta%20build_gallery/2.

```
+ bundle exec fastlane build_and_deploy_testflight
iOS Flutter Gallery built
Testing archiving with distribution profile...
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /opt/s/w/ir/k/flutter/dev/ci/mac/Gemfile.lock. (Gem::GemNotFoundException)
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865070562829642336/+/steps/prepare_environment/0/steps/Build_gallery/0/steps/build_gallery/0/stdout

**Comment by keyonghan** [comment]
The failed build didn't seem to run on top of https://github.com/flutter/flutter/pull/67349/files, whereas the success one did.

**Comment by godofredoc** [comment]
This is a change that needs to be cherry picked from the framework master to stable.

**Comment by jmagman** [comment]
This can be closed when https://github.com/flutter/flutter/commit/74c3ea4d41ffea6372b09fe6360baa194a694e62 hits stable (1.23.0-13.0.pre), and I'm about to delete this test completely in https://github.com/flutter/flutter/pull/74463.
