### ISSUE TITLE
 [gen_l10n] Raw strings are being incorrectly used when generating messages

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69345]
Disabled here: https://github.com/flutter/flutter/commit/ca47b4e12cccb4b13a19e734682595fb41dc2e8e

These tests started failing on https://github.com/flutter/flutter/commit/e5f7726c7b6e43236569443c0814d6619d98aa37 which doesn't seem possible unless the test is not hermetic.

@shihaohong

**Comment by shihaohong** [comment]
This was an actual regression introduced by #69025, which introduced the use of raw string in certain circumstances. However, the way that the Material/Cupertino localizations are generated is different, so it's acceptable in that part of the codebase, but not for the `gen_l10n` tool. I've put out a fix.
