### ISSUE TITLE
Building flutter tool... freezed when install flutter in centos 7

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#69360]
I want to install `dev` channel of flutter in my centos 7 and start some desktop development. However I got `Building flutter tool...` freezed when I execute `flutter upgrade`

## Steps to Reproduce

1. install prerequites, `yum install wget tar unzip ruby ruby-devel make autoconf automake redhat-rpm-config lcov           gcc gcc-c++ libstdc++.i686 java-1.8.0-openjdk-devel xz git mesa-libGL mesa-libGLU
`
2. install flutter via `snap` or manually `git clone ...`, add PATH
3. flutter doctor, flutter channel dev, flutter upgrade

## Logs

```shell
[vncuser@localhost ~]$ which flutter
/var/lib/snapd/snap/bin/flutter
[vncuser@localhost ~]$ flutter --version
Flutter 1.22.2 \u2022 channel stable \u2022 https://github.com/flutter/flutter.git
Framework \u2022 revision 84f3d28555 (2 weeks ago) \u2022 2020-10-15 16:26:19 -0700
Engine \u2022 revision b8752bbfff
Tools \u2022 Dart 2.10.2
[vncuser@localhost ~]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[\u2713] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
[\u2717] Android toolchain - develop for Android devices
    \u2717 Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
[vncuser@localhost ~]$ flutter channel dev
Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:    37ebe3d82a..2783f8e2e1  dev              -> origin/dev
git:    fa988ba83a..3be77241de  dwds-integration -> origin/dwds-integration
git:    84f3d28555..8874f21e79  flutter-1.22-candidate.12 -> origin/flutter-1.22-candidate.12
git:  * [new branch]            flutter-1.24-candidate.2 -> origin/flutter-1.24-candidate.2
git:  * [new branch]            flutter-1.24-candidate.3 -> origin/flutter-1.24-candidate.3
git:  * [new branch]            flutter-1.24-candidate.4 -> origin/flutter-1.24-candidate.4
git:  * [new branch]            flutter-1.24-candidate.5 -> origin/flutter-1.24-candidate.5
git:  * [new branch]            flutter-1.24-candidate.6 -> origin/flutter-1.24-candidate.6
git:    3393566b56..44d0e52d20  master           -> origin/master
git:  * [new branch]            revert-67320-provide_old_layers -> origin/revert-67320-provide_old_layers
git:  * [new tag]               1.24.0-1.0.pre   -> 1.24.0-1.0.pre
git:  * [new tag]               1.24.0-3.0.pre   -> 1.24.0-3.0.pre
git: Switched to a new branch 'dev'
git: Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Successfully switched to flutter channel 'dev'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
[vncuser@localhost ~]$ flutter upgrade
Downloading Dart SDK from Flutter engine defa8be2b10650dad50dfee9324ed8d16eeec13f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  173M  100  173M    0     0  7834k      0  0:00:22  0:00:22 --:--:-- 8774k
Building flutter tool...
^CError: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
^C[vncuser@localhost ~]$ 
```

I have waiting `Building flutter tool...` almost a night.

```
[vncuser@localhost ~]$ flutter doctor -v
Building flutter tool...


```

**Comment by TahaTesser** [comment]
Hi @liudonghua123 
This could be a network issue, can you please make sure you're using a stable connection or switch to a different network.
Also try this possible [solution](https://github.com/flutter/flutter/issues/12666#issuecomment-339395571)
Thank you

**Comment by liudonghua123** [comment]
@TahaTesser Hi, I removed `cache` directory and tried again, but it was the same.

```bash
[vncuser@localhost bin]$ mv cache/ /tmp/cache_snap
[vncuser@localhost bin]$ flutter doctor -v
Downloading Dart SDK from Flutter engine defa8be2b10650dad50dfee9324ed8d16eeec13f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  173M  100  173M    0     0  7971k      0  0:00:22  0:00:22 --:--:-- 8535k
Building flutter tool...


```

Is there any more verbose option of flutter which I can see more details on what's going on.

**Comment by christopherfujino** [comment]
> @TahaTesser Hi, I removed `cache` directory and tried again, but it was the same.
> 
> ```shell
> [vncuser@localhost bin]$ mv cache/ /tmp/cache_snap
> [vncuser@localhost bin]$ flutter doctor -v
> Downloading Dart SDK from Flutter engine defa8be2b10650dad50dfee9324ed8d16eeec13f...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  173M  100  173M    0     0  7971k      0  0:00:22  0:00:22 --:--:-- 8535k
> Building flutter tool...
> ```
> 
> Is there any more verbose option of flutter which I can see more details on what's going on.

@liudonghua123 reading the source code of https://github.com/flutter/flutter/blob/master/bin/internal/shared.sh#L141, it seems the first thing it tries to run `pub upgrade`. Once that succeeds, it tries to generate the flutter cli tool snapshot.

It would help if you could edit this file, and add echo statements to determine if it's hanging in the `retry_upgrade` function, or while trying to generate the dart snapshot.

**Comment by christopherfujino** [comment]
@liudonghua123 oh also, if you update this line https://github.com/flutter/flutter/blob/master/bin/internal/shared.sh#L139 to be:

`VERBOSITY="--verbosity=all"`

You should get verbose logging from `pub`.

**Comment by liudonghua123** [comment]
@christopherfujino @TahaTesser Thanks, I find it's a network issue finally. After I reset the network, it is ok now.
