### ISSUE TITLE
Scenarios UI test PlatformViewMutationOpacityTests testPlatformView is flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#69361]
In the past two days it has failed on ~6 commits. E.g.: https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/7509

```
    t =     4.53s Assertion Failure: GoldenPlatformViewTests.m:72: failed - Goldens to not match. Follow the steps in the README to update golden named golden_platform_view_opacity_iPhone 8_simulator if needed.
    t =     4.53s Tear Down
Test Case '-[PlatformViewMutationOpacityTests testPlatformView]' failed (4.535 seconds).
Test Suite 'PlatformViewMutationOpacityTests' failed at 2020-10-29 19:19:44.991.
```

There was an uptick in the frequency of this flake shortly after the Skia roll here https://github.com/flutter/engine/pull/22140, but I have no idea if that is relevant.

@dnfield @cyanglaz @gaaclarke

**Comment by zanderso** [comment]
PR to delete the test is here https://github.com/flutter/engine/pull/22218

**Comment by gaaclarke** [comment]
Did you look at the images to see what the difference is?  I believe I changed golden image logic to use RMSE with a fixed threshold.  We could adjust that threshold something about this test is not deterministic but also not wrong.

**Comment by cyanglaz** [comment]
I couldn't repro the flake locally. And we have 7 consecutive success runs on LUCI now. 
+1 on adjust the threshold for the opacity test.

**Comment by zanderso** [comment]
This just failed again at tip-of-tree. I'd suggest landing https://github.com/flutter/engine/pull/22230 on red so we can start getting more info.

**Comment by cyanglaz** [comment]
@zanderso Will do

**Comment by zanderso** [comment]
Out of a recent run:
```
GOLDEN DIFF FAILED: image diff greater than threshold. Current diff: 0.5563932631407086, threshold: 0.5
```

**Comment by gaaclarke** [comment]
That isn't much of a change, we should update the golden image with the latest skia or increase the threshold.  It's probably just a slight difference in antialiasing or alphas for example.
