### ISSUE TITLE
An typo error in engine/lib/ui/painting.dart doc.

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#69367]
location: ` engine/lib/ui/painting.dart : 4544`

![image](https://user-images.githubusercontent.com/26687012/97662487-345dde80-1ab2-11eb-9097-a52e46cd4443.png)

location: ` engine/lib/ui/painting.dart : 4604`

![image](https://user-images.githubusercontent.com/26687012/97662410-efd24300-1ab1-11eb-9e9c-251840c6caa9.png)

---
the same mistake `transformList[i * 4 + 2]` , it should be `transformList[i * 4 + 3]` to move on Y axis.

**Comment by xxrlzzz** [comment]
another typo I found in painting.dart:1741

  /// class MyImageHolder {
  ///   MyImageLoader(this.image);
  ///
  ///   final Image image;
  ///
  ///   void draw(Canvas canvas) {
  ///     canvas.drawImage(image, Offset.zero, Paint());
  ///   }
  ///
  ///   void dispose() => image.dispose();
  /// }

the Constructor should be MyImageHolder.
