### ISSUE TITLE
Flutter 1.22.2 navigation pop transition duration not matching push

### ISSUE THREAD

**Issue by CalvinTp** [flutter/flutter#69362]
I have just recently upgraded to Flutter 1.22.2 and saw some differences even though Flutter release notes indicated that navigation system remains the same.

I have 2 pages and I use push method to transition from the 1st page to the 2nd page. I have added a Transition Duration from 1st to 2nd page (code below). Prior to this version, when I pop from 2nd page to 1st page, the delay is matching the 1st to 2nd page. After the update, the when I pop from 2nd page to 1st page, the animation is very fast.

Code:

```
Navigator.push(
      context,
      PageRouteBuilder(
        transitionDuration: Duration(seconds: 1),
        pageBuilder: (_, __, ___) => goto2ndPage(),
        transitionsBuilder: (_, animation, __, child) => FadeTransition(
          opacity: animation,
          child: child,
        ),
      ),
    );

```
For pop:
```
            onPressed:
                () => Navigator.of(context).pop(),
          ),
```

Can someone advice how I can delay the pop transition from 2nd page to 1st page?

flutter doctor -v output:

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E266, locale en-MY)
    • Flutter version 1.22.2 at /Users/calvin/Documents/development/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/pohthiamteoh/Library/Android/sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

**Comment by darshankawar** [comment]
@CalvinTp 
You may check the new navigation design [doc](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit) that has details around how pop() works with new design and see if it answers your question.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
