### ISSUE TITLE
SliverAppBar's flexibleSpace glitch on iOS when NestedScrollView's body is a ScrollView

### ISSUE THREAD

**Issue by peerwaya** [flutter/flutter#69376]
This issue was fixed in #29264. I am referencing it here because the issue still happens and the steps still apply: cc @Piinks 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-4.0.pre.165, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.0)
[✓] Connected device (3 available)

```

**Comment by darshankawar** [comment]
@peerwaya 
I tried the code [sample](https://github.com/flutter/flutter/issues/29264#issue-420271738) from original issue and verified on iphone 6s (OS 14) using latest master version, but didn't see the issue.

[RPReplay-Final1604055750.MP4.zip](https://github.com/flutter/flutter/files/5464738/RPReplay-Final1604055750.MP4.zip)

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.24.0-4.0.pre.165, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.24.0-4.0.pre.165 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e444b1e3fa (7 hours ago), 2020-10-30 00:41:52 -0400
    • Engine revision 99cc50dfff
    • Dart version 2.11.0 (build 2.11.0-266.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)           • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Web Server (web)                    • web-server                               •
      web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                                   •
      web-javascript • Google Chrome 86.0.4240.111

• No issues found!


```

</details>

Can you provide video of the issue you are facing along with device and OS version ?

**Comment by peerwaya** [comment]
![RPReplay-Final1604012713](https://user-images.githubusercontent.com/14053870/97774463-442ffe00-1b58-11eb-9d39-04ca8c5523d7.gif)

Device: Iphone XR. iOS 14.0.1

**Comment by peerwaya** [comment]
[RPReplay_Final1604012713.MP4.zip](https://github.com/flutter/flutter/files/5468751/RPReplay_Final1604012713.MP4.zip)
Device: Iphone XR. iOS 14.0.1

**Comment by peerwaya** [comment]
It happens when you do a fast fling, it bounces back

**Comment by darshankawar** [comment]
@peerwaya 
I am unable to replicate it on device (6s) and simulator (iphone SE) I tried using the sample code mentioned in original issue.Are you using any different code sample to replicate it ?

**Comment by peerwaya** [comment]
`
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.light,
        primaryColor: Colors.indigo,
        accentColor: Colors.pinkAccent,
      ),
      home: const Me(),
    );
  }
}

class _TabContent extends StatefulWidget {
  const _TabContent({
    Key key,
    @required this.index,
  })  : assert(index != null),
        super(key: key);

  final int index;

  @override
  _TabContentState createState() => _TabContentState();
}

class _TabContentState extends State<_TabContent>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context); // AutomaticKeepAliveClientMixin
    return CustomScrollView(
      key: PageStorageKey<String>('tab-${widget.index}'),
      slivers: <Widget>[
        SliverOverlapInjector(
          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return ListTile(
                title: Text('Item $index'),
              );
            },
            childCount: 50,
          ),
        )
      ],
    );
  }
}

class _TabBarDelegate extends SliverPersistentHeaderDelegate {
  _TabBarDelegate({this.controller, this.isScrolled = false});

  final TabController controller;
  final bool isScrolled;
  @override
  double get minExtent => 48;

  @override
  double get maxExtent => 48;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Material(
      color: Theme.of(context).appBarTheme.color,
      elevation: 0,
      // elevation: isScrolled || (shrinkOffset > maxExtent - minExtent) ? 4.0 : 0,
      child: TabBar(
        controller: controller,
        indicatorColor: Theme.of(context).colorScheme.primary,
        tabs: <Widget>[
          Tab(
            icon: Icon(
              Icons.calendar_today,
            ),
          ),
          Tab(
            icon: Icon(Icons.favorite),
          ),
        ],
      ),
    );
  }

  @override
  bool shouldRebuild(covariant _TabBarDelegate oldDelegate) {
    return oldDelegate.controller != controller;
  }
}

class Me extends StatefulWidget {
  const Me({
    Key key,
  }) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    return _MeState();
  }
}

class _MeState extends State<Me> with TickerProviderStateMixin {
  final List<String> listItems = [];

  final ScrollController _scrollController = ScrollController();

  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  List<Widget> _buildHeaderSlivers(
      BuildContext context, bool innerBoxIsScrolled) {
    return <Widget>[
      SliverToBoxAdapter(
        child: Container(
          padding: EdgeInsets.all(16.0).copyWith(bottom: 0),
          color: Theme.of(context).appBarTheme.color,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(
                width: 100.0,
                height: 100.0,
                child: Stack(
                  fit: StackFit.expand,
                  children: <Widget>[
                    CircleAvatar(
                      backgroundColor: Theme.of(context).colorScheme.primary,
                      child: Icon(
                        Icons.person_outline,
                        color: Theme.of(context).colorScheme.onPrimary,
                        size: 64.0,
                      ),
                    ),
                    Container(
                      alignment: Alignment.bottomRight,
                      child: Container(
                        height: 24.0,
                        width: 24.0,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          color: Theme.of(context).scaffoldBackgroundColor,
                          borderRadius: BorderRadius.all(
                            Radius.circular(20),
                          ),
                        ),
                        child: Icon(
                          Icons.add_circle,
                          size: 24.0,
                          color: Theme.of(context).colorScheme.primary,
                        ),
                      ),
                    )
                  ],
                ),
              ),
              const SizedBox(
                height: 16.0,
              ),
              Text(
                'John Doe',
                style: Theme.of(context).textTheme.headline5,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
              // _buildUsername(context),
              const SizedBox(
                height: 8.0,
              ),
              OutlineButton(
                textColor: Theme.of(context).colorScheme.primary,
                highlightedBorderColor: Theme.of(context).colorScheme.primary,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4.0),
                ),
                child: Text(
                  'Edit Profile',
                ),
                onPressed: () {},
              )
            ],
          ),
        ),
      ),
      SliverOverlapAbsorber(
        // This widget takes the overlapping behavior of the SliverAppBar,
        // and redirects it to the SliverOverlapInjector below. If it is
        // missing, then it is possible for the nested "inner" scroll view
        // below to end up under the SliverAppBar even when the inner
        // scroll view thinks it has not been scrolled.
        // This is not necessary if the "headerSliverBuilder" only builds
        // widgets that do not overlap the next sliver.
        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
        sliver: SliverPersistentHeader(
          pinned: true,
          delegate: _TabBarDelegate(
              controller: _tabController, isScrolled: innerBoxIsScrolled),
        ),
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox.expand(
      child: Column(
        children: [
          AppBar(
            leading: IconButton(
              icon: Icon(Icons.person_add),
              onPressed: () {},
            ),
            centerTitle: true,
            title: Text(
              "Me",
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.headline6,
            ),
            // backgroundColor: Theme.of(context).canvasColor,
            brightness: Theme.of(context).brightness,
            elevation: 0,
            actions: <Widget>[
              IconButton(
                icon: Icon(Icons.more_horiz),
                onPressed: () {},
              )
            ],
          ),
          Expanded(
            child: NestedScrollView(
              headerSliverBuilder: _buildHeaderSlivers,
              controller: _scrollController,
              body: TabBarView(controller: _tabController, children: [
                _TabContent(
                  key: PageStorageKey('tab0'),
                  index: 0,
                ),
                _TabContent(
                  key: PageStorageKey('tab1'),
                  index: 1,
                ),
              ]),
            ),
          )
        ],
      ),
    );
  }
}

`

**Comment by peerwaya** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.light,
        primaryColor: Colors.indigo,
        accentColor: Colors.pinkAccent,
      ),
      home: const Me(),
    );
  }
}

class _TabContent extends StatefulWidget {
  const _TabContent({
    Key key,
    @required this.index,
  })  : assert(index != null),
        super(key: key);

  final int index;

  @override
  _TabContentState createState() => _TabContentState();
}

class _TabContentState extends State<_TabContent>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context); // AutomaticKeepAliveClientMixin
    return CustomScrollView(
      key: PageStorageKey<String>('tab-${widget.index}'),
      slivers: <Widget>[
        SliverOverlapInjector(
          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return ListTile(
                title: Text('Item $index'),
              );
            },
            childCount: 50,
          ),
        )
      ],
    );
  }
}

class _TabBarDelegate extends SliverPersistentHeaderDelegate {
  _TabBarDelegate({this.controller, this.isScrolled = false});

  final TabController controller;
  final bool isScrolled;
  @override
  double get minExtent => 48;

  @override
  double get maxExtent => 48;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Material(
      color: Theme.of(context).appBarTheme.color,
      elevation: 0,
      // elevation: isScrolled || (shrinkOffset > maxExtent - minExtent) ? 4.0 : 0,
      child: TabBar(
        controller: controller,
        indicatorColor: Theme.of(context).colorScheme.primary,
        tabs: <Widget>[
          Tab(
            icon: Icon(
              Icons.calendar_today,
            ),
          ),
          Tab(
            icon: Icon(Icons.favorite),
          ),
        ],
      ),
    );
  }

  @override
  bool shouldRebuild(covariant _TabBarDelegate oldDelegate) {
    return oldDelegate.controller != controller;
  }
}

class Me extends StatefulWidget {
  const Me({
    Key key,
  }) : super(key: key);
  @override
  State<StatefulWidget> createState() {
    return _MeState();
  }
}

class _MeState extends State<Me> with TickerProviderStateMixin {
  final List<String> listItems = [];

  final ScrollController _scrollController = ScrollController();

  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  List<Widget> _buildHeaderSlivers(
      BuildContext context, bool innerBoxIsScrolled) {
    return <Widget>[
      SliverToBoxAdapter(
        child: Container(
          padding: EdgeInsets.all(16.0).copyWith(bottom: 0),
          color: Theme.of(context).appBarTheme.color,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(
                width: 100.0,
                height: 100.0,
                child: Stack(
                  fit: StackFit.expand,
                  children: <Widget>[
                    CircleAvatar(
                      backgroundColor: Theme.of(context).colorScheme.primary,
                      child: Icon(
                        Icons.person_outline,
                        color: Theme.of(context).colorScheme.onPrimary,
                        size: 64.0,
                      ),
                    ),
                    Container(
                      alignment: Alignment.bottomRight,
                      child: Container(
                        height: 24.0,
                        width: 24.0,
                        alignment: Alignment.center,
                        decoration: BoxDecoration(
                          color: Theme.of(context).scaffoldBackgroundColor,
                          borderRadius: BorderRadius.all(
                            Radius.circular(20),
                          ),
                        ),
                        child: Icon(
                          Icons.add_circle,
                          size: 24.0,
                          color: Theme.of(context).colorScheme.primary,
                        ),
                      ),
                    )
                  ],
                ),
              ),
              const SizedBox(
                height: 16.0,
              ),
              Text(
                'John Doe',
                style: Theme.of(context).textTheme.headline5,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
              // _buildUsername(context),
              const SizedBox(
                height: 8.0,
              ),
              OutlineButton(
                textColor: Theme.of(context).colorScheme.primary,
                highlightedBorderColor: Theme.of(context).colorScheme.primary,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4.0),
                ),
                child: Text(
                  'Edit Profile',
                ),
                onPressed: () {},
              )
            ],
          ),
        ),
      ),
      SliverOverlapAbsorber(
        // This widget takes the overlapping behavior of the SliverAppBar,
        // and redirects it to the SliverOverlapInjector below. If it is
        // missing, then it is possible for the nested "inner" scroll view
        // below to end up under the SliverAppBar even when the inner
        // scroll view thinks it has not been scrolled.
        // This is not necessary if the "headerSliverBuilder" only builds
        // widgets that do not overlap the next sliver.
        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
        sliver: SliverPersistentHeader(
          pinned: true,
          delegate: _TabBarDelegate(
              controller: _tabController, isScrolled: innerBoxIsScrolled),
        ),
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox.expand(
      child: Column(
        children: [
          AppBar(
            leading: IconButton(
              icon: Icon(Icons.person_add),
              onPressed: () {},
            ),
            centerTitle: true,
            title: Text(
              "Me",
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.headline6,
            ),
            // backgroundColor: Theme.of(context).canvasColor,
            brightness: Theme.of(context).brightness,
            elevation: 0,
            actions: <Widget>[
              IconButton(
                icon: Icon(Icons.more_horiz),
                onPressed: () {},
              )
            ],
          ),
          Expanded(
            child: NestedScrollView(
              headerSliverBuilder: _buildHeaderSlivers,
              controller: _scrollController,
              body: TabBarView(controller: _tabController, children: [
                _TabContent(
                  key: PageStorageKey('tab0'),
                  index: 0,
                ),
                _TabContent(
                  key: PageStorageKey('tab1'),
                  index: 1,
                ),
              ]),
            ),
          )
        ],
      ),
    );
  }
}

```

**Comment by darshankawar** [comment]
@peerwaya 
Tried again on latest stable and latest master by sliding fast but didn't notice the glitch. 

[RPReplay-Final1604901451.MP4.zip](https://github.com/flutter/flutter/files/5508388/RPReplay-Final1604901451.MP4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

</details>

As you said, the issue happens rarely and not consistently, I'd suggest you to keep an eye on the pattern and frequency with which you observe the issue. If you have concrete steps to replicate it, feel free to write in the comments and I'll reopen it.
Closing.
