### ISSUE TITLE
Engine has very limited testing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6937]
We should test more things on the engine bots, such as (in order of how easy they would be to add, easiest first):

- [x] all possible combinations of builds, including e.g. `android_profile_unopt` which just broke without the bots noticing (https://github.com/dart-lang/sdk/issues/27862)
- [x] we should verify that the host test binary runs without crashing
- [x] test some basic framework tests (can't test anything too complicated, because otherwise we would not be able to change APIs since it would break the engine tests where they got out of sync)
- [x] Skia pixel tests for parts of the Canvas API

**Comment by Hixie** [comment]
We should also look at adding compilation testing to Travis PR tests.

**Comment by chinmaygarde** [comment]
The action items listed have been completed.
