### ISSUE TITLE
'showSnackBar' is deprecated and shouldn't be used

### ISSUE THREAD

**Issue by mohamedhasan2002** [flutter/flutter#69373]
WHEN I TRIED TO CLONE THIS FILE(FLUTTER)
**SOURCE:** [](https://github.com/ibmkynl/ChitChat)
**ERROR** 
{
	"resource": "/home/hasan/Desktop/ChitChat-master/lib/ProfileSetPage/Profile_Form.dart",
	"owner": "dart",
	"code": {
		"value": "deprecated_member_use",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#deprecated_member_use",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "deprecated_member_use"
		}
	},
	"severity": 2,
	"message": "'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre..\nTry replacing the use of the deprecated member with the replacement.",
	"source": "dart",
	"startLineNumber": 92,
	"startColumn": 17,
	"endLineNumber": 92,
	"endColumn": 29,
	"tags": [
		2
	]
}
**CODE:**
@override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return BlocListener(
        bloc: _loginBloc,
        listener: (BuildContext context, LoginState state) {
          if (state.isFailure) {
            Scaffold.of(context)
              ..showSnackBar(
                SnackBar(
                  content: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Login Failure',
                      ),
                      Icon(Icons.error)
                    ],
                  ),
                ),
              );
          }
          if (state.isSubmitting) {
            Scaffold.of(context)
              ..showSnackBar(
                SnackBar(
                  content: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('Logging In...'),
                      CircularProgressIndicator(),
                    ],
                  ),
                ),
              );
          }

**Comment by yash1200** [comment]
This will help.
```
// Instead of calling ,
Scaffold.of(context).showSnackBar(...);
// call:
ScaffoldMessenger.of(context).showSnackBar(...);
```

**Comment by mohamedhasan2002** [comment]
Thx solved!
