### ISSUE TITLE
'crumb' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by SUBARAJ101** [flutter/flutter#69375]
i have been working with flutter for past 6 months. I never had issue like this. The flutter .bat file inside bin folder gives this error but the flutter_console.bat file executes everything fine. The issue is i cant use any IDE (android studio ) or VS code, because they show me no devices found even i have my device connected.Vs code shows flutter daemon has terminated when i click no devices at the bottom. I have my env variables set. What is the issue..pls help soon. I have project work
![Screenshot (119)](https://user-images.githubusercontent.com/40908678/97670788-fd38fe80-1aac-11eb-9bd8-18a5713ba3d3.png)
![Screenshot (118)](https://user-images.githubusercontent.com/40908678/97670825-13df5580-1aad-11eb-8820-1c8c66b3616d.png)
![Screenshot (116)](https://user-images.githubusercontent.com/40908678/97670867-28bbe900-1aad-11eb-8978-447e4e9117ce.png)

**Comment by SUBARAJ101** [comment]
@DanTup

**Comment by TahaTesser** [comment]
Hi @SUBARAJ101 
Are you able to run apps from the terminal? 
Can you please provide your `flutter doctor -v` your `flutter run --verbose`
Thank you

**Comment by SUBARAJ101** [comment]
i can other apps. But the problem is with (bin/flutter.bat). When i tried to open this in terminal in gives this even though i have environment variables set
![Screenshot (121)](https://user-images.githubusercontent.com/40908678/97701157-f7561400-1ad2-11eb-8afa-56b6193178ee.png)
when i tried the same thing in flutter_console.bat it gives
![Screenshot (120)](https://user-images.githubusercontent.com/40908678/97701236-15bc0f80-1ad3-11eb-8a48-fb91159204a1.png)

same thing happens when i tried to execute the command(flutter run --verbose)

Running in terminal gives the sae output('crumb' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.)

But dlutter console does the job

**Comment by TahaTesser** [comment]
Hi @SUBARAJ101 
You need to install git on your system, please install it and add it in your path if it is already installed  try again 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by akshaytheau** [comment]
Facing similar issue of crumb not being recognized as internal command and git not in path
