### ISSUE TITLE
Widget not working properly

### ISSUE THREAD

**Issue by mummyk** [flutter/flutter#69386]
I upgraded my flutter version and all my widget stopped working properly like I got errors all over, I am using 
Flutter version 1.23.0-18.1.pre, channel beta
and this is because I want to use the web version

**Comment by pedromassangocode** [comment]
Hi @mummyk 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Can you describe what you mean by "all my widget stopped working properly like I got errors all over"? what kind of errors?

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
