### ISSUE TITLE
Infowindow isnt customizable 

### ISSUE THREAD

**Issue by DanielRobert1** [flutter/flutter#69389]
I want to create a map  like uber that shows the two pickup location and drop  off location like a tooltip on the map markers? there is no way to do this right now.

**Comment by TahaTesser** [comment]
Hi @DanielRobert1 
There are several ways achieve this but unfortunately info window doesn't support these customizations options 

There are several issues open for this already 
1. https://github.com/flutter/flutter/issues/32145
2. https://github.com/flutter/flutter/issues/52878
3. https://github.com/flutter/flutter/issues/34463
4. https://github.com/flutter/flutter/issues/33091

Please follow up on those issues, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
