### ISSUE TITLE
Asset variant detection should only work on directory names that are parse-able by the framework (2x, 3x)

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#69388]
## Steps to Reproduce

Can repro from 1.17 to 1.23 master.

Run https://github.com/AlexV525/flutter_test_app (test-assets-conflict-page) for repro demo with master.

1. Add two assets with same name, but not the same path. (e.g. `assets/a.png` and `assets/b/a.png`)
2. Display those images in Flutter App.

![image](https://user-images.githubusercontent.com/15884415/97690869-8a457d00-1ad8-11eb-8821-82418eba86ed.png)

**Expected results:** Display two different pictures/assets.

**Actual results:** Displayed same pictures/assets, which is the deeper one.

```
[✓] Flutter (Channel update-length-limiting-formatter, 1.23.0-19.0.pre.78, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
```

**Comment by AlexV525** [comment]
P1 maybe? Couldn't believe we have this kind of issue. 😢

**Comment by yash1200** [comment]
Changing your assets list to this : 
```
final List<String> assets = <String>[
  'ii.png',
  'something/ii.png',
];
```
and pubspec.yaml to this : 
```
flutter:
  uses-material-design: true
  assets:
    - assets/
```
These changes fixed your issue.

**Comment by AlexV525** [comment]
@yash1200 That's weird. Since when we could use undeclared assets? Doc ref:https://flutter.dev/docs/development/ui/assets-and-images#specifying-assets

**Comment by yash1200** [comment]
I just experimented and it worked with this.
Here's a screenshot:

![Screenshot_2020-10-30_16-30-22](https://user-images.githubusercontent.com/38391570/97698183-27e77f00-1ace-11eb-8b55-85e90852d5f8.png)

**Comment by pedromassangocode** [comment]
I was able to reproduce however not sure if the implementation is the correct one.

**Comment by AlexV525** [comment]
> I just experimented and it worked with this.

Thanks for the quick clarify! So there must be something broken with assets loading.

**Comment by AlexV525** [comment]
cc @jonahwilliams

**Comment by pedromassangocode** [comment]
Maybe P3 since this is not blocking any customer?
Feel free to increase the priority if necessary.

**Comment by jonahwilliams** [comment]
This is mostly an intention feature - asset variants. The idea is that you can automatically pick up multiple resolutions of the same image and have the framework select them at runtime.

```
a.png
2x/a.png
3x/a.png
```

Of course, it is not actually restricted to 2x, 3x as you've discovered here....

**Comment by AlexV525** [comment]
> Of course, it is not actually restricted to 2x, 3x as you've discovered here....

When it comes to production cases, assets like the demo in my test app, such as separate placeholder can cause confusing behaviors.

And what about the solution that @yash1200 suggested?

**Comment by jonahwilliams** [comment]
I think the right fix would to restrict the asset variant code to strings that the framework can parse

**Comment by christopherfujino** [comment]
cc @eliasyishak

**Comment by jonahwilliams** [comment]
I think this one might be an interesting first issue for @andrewkolos , if you haven't already looked at it @eliasyishak .
