### ISSUE TITLE
RadioListTile will need the same properties exposed as SwitchListTile and CheckboxListTile

### ISSUE THREAD

**Issue by talamaska** [flutter/flutter#69390]
## Use case
I have already requested shape, tileColor and selectedTileColor for SwitchListTile and CheckboxListTile
in those #66982, #67063, #68304. And they are done and merged thanks to everybody
I'm hoping they will get to the next stable release. 

## Proposal
I overlooked to mention RadioListTile in all three feature requests and it didn't get the love.
Now I'm making this feature request specifically for RadioListTile - it will also need shape, tileColor and selectedTileColor.
I think this can be done without any confrontation with Material spec, just as the other control tiles before it in the sake of consistency.

**Comment by yash1200** [comment]
@talamaska I would like to work on this one.
