### ISSUE TITLE
[Engine] assert(custom_sysroot != "")

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#69408]
Beta channel: 1d12d82d9cb54876f58044aa52198d53ec841c3d

This came in on a commit since yesterday.

```
Generating GN files in: out/linux_debug_arm64
ERROR at //build/config/BUILDCONFIG.gn:491:3: Assertion failed.
  assert(custom_sysroot != "")
  ^-----
```

**Comment by jwinarske** [comment]
@csells

**Comment by TahaTesser** [comment]
Hi @jwinarske 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample or steps to reproduce 
Thank you

**Comment by jwinarske** [comment]
I'm cross compiling the flutter engine.  The commit I referenced refers to beta channel.

**Comment by TahaTesser** [comment]
Hi @jwinarske 
Checking  out https://github.com/flutter/engine/commit/1d12d82d9cb54876f58044aa52198d53ec841c3d  locally 

<img width="1226" alt="Screenshot 2020-11-03 at 12 57 59 PM" src="https://user-images.githubusercontent.com/48603081/97958917-38507000-1dd4-11eb-9429-528a50372bf0.png">


`assert(custom_sysroot != "")` doesn't show anywhere 
<img width="317" alt="Screenshot 2020-11-03 at 12 56 22 PM" src="https://user-images.githubusercontent.com/48603081/97958806-ff180000-1dd3-11eb-9a79-6104bb53ad10.png">

**Comment by jwinarske** [comment]
Hmm.  I've since moved on from this issue.

What would it take to make the flutter engine build logic be a first class cross compilation citizen?

Some scenarios:

1. Cross compiling for x86-64.  It thinks it's a host build, and unit tests pull in things not present in the rootfs.  Instead make a specific unit test gate on it's dependency.

2. Building target and host artifacts in the same build pass.  Ideally target artifacts are built in one pass, host in a separate pass.  Setup toolchain for one, build, etc.  All in all it makes it more scalable, and easier to manage.  Having to maintain something that does both can be painful.  To support host side Dart tools in Yocto, they have to be built out of tree.

**Comment by TahaTesser** [comment]
Hi @jwinarske 
`ERROR at //build/config/BUILDCONFIG.gn:491:3: Assertion failed.`  might from the engine build,  I haven't tried compiling the engine for Linux yet.  However, without steps to reproduce the issue, it's hard to locate the issue. 

If you have a proposal or feature request, please file a separate issue for it 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
