### ISSUE TITLE
Doctor command should check that you have SDK constraints in your package

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#69403]
## Use case

The min Dart SDK constraint specifically now has meaning, as it determines your language version. All packages, even non-published ones _should_ have an SDK constraint to prevent breakage by new language features which may be breaking (ie: null safety). 

## Proposal

The `doctor` command should check that you have a min sdk constraint on the Dart SDK, and if not suggest one.

It may need to suggest two alternatives, one for null safety and one without null safety? Or it could try to see if the package _is_ null safe already and suggest the latest in that case, and otherwise suggest `2.9`?

**Comment by mit-mit** [comment]
`flutter doctor` checks the installation, not a project. But @pq is adding linting for `pubspec.yaml` right now, I think we could fairly easily add a lint for it?

We also have `flutter fix` that could perhaps add the missing constraint?

**Comment by jakemac53** [comment]
If that means that `flutter analyze` would cover it that might be enough - but note that the output of that in this scenario will be overwhelming because the package will be opted in but not migrated. So I doubt it will be very  useful?

**Comment by pedromassangocode** [comment]
Important to note that flutter doctor can be executed outside of a valid Flutter project so this new addition should cover that (ignore the proposed check?) as well.

**Comment by mit-mit** [comment]
Related issue: https://github.com/dart-lang/sdk/issues/44013

**Comment by christopherfujino** [comment]
> `flutter doctor` checks the installation, not a project. But @pq is adding linting for `pubspec.yaml` right now, I think we could fairly easily add a lint for it?

I agree that `flutter doctor` would not be the appropriate place for this check. @jakemac53 do we still need to add some check for this, or did the analyzer end up checking it?

**Comment by jakemac53** [comment]
It looks like pub does have a check, and it will refuse to fetch any package deps without a min SDK constraint:

```
$ dart pub get
Resolving dependencies... 
pubspec.yaml has no lower-bound SDK constraint.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '^3.3.0-edge.0fa13d4627c4c5874c679512fc2520ea1ac9557a'

See https://dart.dev/go/sdk-constraint
```
