### ISSUE TITLE
websocket_impl.dart file has uri bug

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#69410]
## Steps to Reproduce
This is very simple to reproduce. Due to this bug websocket_impl.dart can't connect using WebSocket.
Go to https://dart.dev/#try-dart and enter following code
main() {
  String url = 'wss://hello.world.com/myHub?v=abcdefgh';
  Uri uri = Uri.parse(url);
  uri = Uri(
      scheme: uri.scheme == "wss" ? "https" : "http",
      userInfo: uri.userInfo,
      host: uri.host,
      port: uri.port,
      path: uri.path,
      query: uri.query,
      fragment: uri.fragment);
  print(uri.toString());
}
 
**Actual results:** 
https://hello.world.com:0/myHub?v=abcdefgh#

**Expected results:** 
https://hello.world.com/myHub?v=abcdefgh#
There should be no port 0 for url scheme wss. In the websocket_impl.dart and method static Future<WebSocket> connect obvious Exception occurs in the following line
return _httpClient.openUrl("GET", uri).then((request) {

<details>
  <summary>Logs</summary>

Above issue has nothing to do with my app

Above issue has nothing to do with my app

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.5 19F101, locale en-CA)
    • Flutter version 1.22.0 at /Users/borismisic/Developer/SDKs/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/borismisic/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (3 available)            
    • Boris’s iPhone (mobile)             • e6d57534fdc9f9c6de90bbe1029d3e6f91069973 • ios • iOS 13.5.1
    • iPhone 8 (mobile)                   • 86CECABE-4A8C-4622-9789-56F866DD0B7D     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • iPhone SE (2nd generation) (mobile) • A1B22118-9D9A-4FA2-B6B7-ECA34922CCAF     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

</details>

**Comment by darshankawar** [comment]
@misici234 
I believe this issue belongs to `dart-lang` repo : https://github.com/dart-lang/api.dart.dev/issues
Please consider to open this issue there.
Closing it from here. If you disagree, write in comments and I'll reopen.
Thanks.
