### ISSUE TITLE
[video_player] 0.11.1+3 and 0.11.1+4 not published

### ISSUE THREAD

**Issue by alexodus** [flutter/flutter#69413]
on pub.dev the last is 0.11.1+2

**Comment by darshankawar** [comment]
@alexodus 
What's the issue here ? Where do you see the `0.11.1+3 and 0.11.1+4` versions ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
