### ISSUE TITLE
Slider activeColor should support coloring the thumb of the slider at min position

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#6941]
Create a slider that has 3 segments with a unique color for each value. Select segment 1:

```Dart
new Slider(
  value: 1.0,
  max: 3.0,
  divisions: 3,
  activeColor: Colors.deepOrange[300],
)
```
results in:

![image](https://cloud.githubusercontent.com/assets/6687929/20460176/d88f5796-ae90-11e6-9d96-c7012a11a606.png)

However selecting segment 0 with a color:

```Dart
new Slider(
  value: 0.0,
  max: 3.0,
  divisions: 3,
  activeColor: Colors.orangeAccent[100],
)
```

results in:

![image](https://cloud.githubusercontent.com/assets/6687929/20460180/fb1807b8-ae90-11e6-82f4-b037d968d0f1.png)

I understand material design suggests the min value to always be gray but I presume that should be left to the app's discretion since sliders can be used in a variety of contexts and min does not necessarily mean "inactive".

I propose that activeColor to be renamed "color" and apply to min position as well.

**Comment by abarth** [comment]
The slide actually looks a bit different when inactive.  (The head is smaller is filled in with grey.)

This boils down to how much we want to support people building off-spec.  /cc @Hixie for thoughts.

**Comment by Hixie** [comment]
People want to build off-spec, and will do it whether we make it easy or not. We should probably just get guidance from the material team about what is ok to offer and what isn't.

**Comment by mehmetf** [comment]
I would not have made this request if I believed ours was a niche case. Material design is often limiting in terms of real-world functionality and thus should be extended where applicable. For instance, I want a volume slider where the minimum value is 10. 10 isn't "off" so it should not be grayed out. I can think of a whole slew of use cases along similar lines.

I would be happy to make this case to the material team if you include me in the communication.

**Comment by sethladd** [comment]
We want to allow folks to build UIs that are off-spec or not-spec, as there are many degrees of freedom in app UIs. This is especially important as we look for external teams to start using Flutter, as many teams will want to create brand-driven or customized designs. This is an area that Flutter can excel at :)

**Comment by abarth** [comment]
Ok, sounds like we want to do this.  Will do.

**Comment by abarth** [comment]
The designers have also concluded that this should be an option.
