### ISSUE TITLE
Animated Icon: add_Close

### ISSUE THREAD

**Issue by arfeenmushtaq** [flutter/flutter#69424]
Hi guys,
  I need an Animated Icon which starts with Add Icon and ends with Close Icon. this is a very simple request and in the absence of this icon a lot of developers including myself are coding these icons

**Comment by darshankawar** [comment]
@arfeenmushtaq 
I see few articles on how to achieve it using Animated Icon widget. Check below and see if it serves your need. 

https://medium.com/@bimsina/animated-icons-in-flutter-3ca7e921500a
https://medium.com/@pinkesh.earth/how-to-animate-icons-in-flutter-b96fe856a5b8

**Comment by charlee** [comment]
if the simple transition between the two icons is enough `simple_animated_icon` package might be useful
