### ISSUE TITLE
Flake in long running web integration tests: connection reset by peer

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69421]
```
▌17:30:00▐ ELAPSED TIME: 3min 27.271s for ../../../bin/flutter drive --dart-define=FLUTTER_WEB_USE_SKIA=true --driver=test_driver/transitions_perf_e2e_test.dart --target=test_driver/transitions_perf_e2e.dart --browser-name=chrome -d web-server --profile in dev/integration_tests/flutter_gallery
Integration test passed.
Unhandled exception:
OS Error: Connection reset by peer, errno = 104
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864995775464176832/+/steps/run_test.dart_for_web_long_running_tests_shard_and_subshard_1/0/stdout

**Comment by yjbanov** [comment]
@jonahwilliams Do you have any intuition about what might be printing this error message? Is it in the tool? How can we get a stack trace out of it?

**Comment by jonahwilliams** [comment]
If it has the tool you would see a stack trace or error report
