### ISSUE TITLE
windows build tests failing on infra failure: could not read recipe result file at "C:\b\s\w\ir\tmp\recipe-result.json":

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69434]
For example: https://ci.chromium.org/p/flutter/builders/prod/Windows%20build_tests

This has closed the tree and will block rolling the null safe dart into flutter

**Comment by jonahwilliams** [comment]
This might be related to some tests that were timing out and disabled here: https://github.com/flutter/flutter/commit/25622246650f1693ebabda4e4f17deb3453c614a

**Comment by christopherfujino** [comment]
Pre-submit occurrences:
https://ci.chromium.org/p/flutter/builders/try/Windows%20Plugins/977?
https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_tests/4974?
https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests/4209?

**Comment by godofredoc** [comment]
Seems like a test related problem:

```
▌18:12:07▐ ELAPSED TIME: 8.791s for ..\..\bin\flutter.bat test test_smoke_test\disallow_error_reporter_modification_test.dart in dev\automated_tests
▌18:12:07▐ ELAPSED TIME: 9.412s for ..\..\bin\flutter.bat test test_smoke_test\crash2_test.dart in dev\automated_tests
▌18:12:08▐ ELAPSED TIME: 9.735s for ..\..\bin\flutter.bat test test_smoke_test\missing_import_test.broken_dart in dev\automated_tests
▌18:12:09▐ ELAPSED TIME: 10.724s for ..\..\bin\flutter.bat test test_smoke_test\syntax_error_test.broken_dart in dev\automated_tests
▌18:12:09▐ RUNNING: cd packages\flutter_driver; ..\..\bin\flutter.bat drive --show-test-device -d flutter-tester -t test_driver\success.dart
Terminate batch job (Y/N)? 
```

**Comment by godofredoc** [comment]
Tests are getting blocked until the task times out and gets killed (50 mins ) after:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864990060682553360/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/commit/25622246650f1693ebabda4e4f17deb3453c614a opens the tree.
