### ISSUE TITLE
could not read recipe result file at "C:\b\s\w\ir\tmp\recipe-result.json"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#69435]
Multiple reports (from different PRs) of LUCI windows framework presubmit infra failures (across different shards) failing to find the file recipe-result.json.

https://ci.chromium.org/p/flutter/builders/try/Windows%20Plugins/977?
https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_tests/4974?
https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests/4209?

**Comment by zanderso** [comment]
Duplicate of https://github.com/flutter/flutter/issues/69434

**Comment by christopherfujino** [comment]
beat me by a minute :)
