### ISSUE TITLE
Engine LUCI doesn't report screenshot for ScenarioApp tests

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#69436]
The scenario tests failure on Engine LUCI doesn't record the failing image screenshot, which makes debugging very hard. 

For example, in below output of a failed run: 
```
Test session results, code coverage, and logs:
	/Users/chrome-bot/Library/Developer/Xcode/DerivedData/Scenarios-fjbbnoocezxtwtagptzjfpfixapr/Logs/Test/Test-Scenarios-2020.10.30_12-40-41--0700.xcresult

Testing started on 'iPhone 8'
Failing tests:
	ScenariosUITests:
		-[PlatformViewMutationOpacityTests testPlatformView]

** TEST FAILED **
```

The log pointed out the test results is in `/Users/chrome-bot/Library/Developer/Xcode/DerivedData/Scenarios-fjbbnoocezxtwtagptzjfpfixapr/Logs/Test/Test-Scenarios-2020.10.30_12-40-41--0700.xcresult`, but this file is deleted upon finishing the task.

We should update the LUCI engine recipe so that this result is uploaded to logs when tests fail.

**Comment by godofredoc** [comment]
This is going to be implemented in a generic way for all the recipes. At the beginning of the execution of the recipe a temporary folder will be created and the path added to an env variable. The recipe will inspect the tmp folder at the end and will upload logs to isolate and provide links in the milo ui.

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by jmagman** [comment]
Blocked by https://github.com/flutter/flutter/issues/74344

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
