### ISSUE TITLE
'package:flutter/src/widgets/title.dart': Failed assertion: line 26 pos 16: 'color != null && color.alpha == 0xFF': is not true.

### ISSUE THREAD

**Issue by asketsystem** [flutter/flutter#69441]
'package:flutter/src/widgets/title.dart': Failed assertion: line 26 pos 16: 'color != null && color.alpha == 0xFF': is not true.

**Comment by sidrao2006** [comment]
Hello @asketsystem ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample
Thank you!

**Comment by asketsystem** [comment]
Hello.., I was able to fix it. Thanks

**Comment by davidryan-mu** [comment]
> Hello.., I was able to fix it. Thanks

Hi! Could you leave some details on how you fixed this? Thanks!
