### ISSUE TITLE
Image losses quality with imagepicker

### ISSUE THREAD

**Issue by Abhijithsp** [flutter/flutter#69456]
I am trying to capture image with imagepicker but after i capture image i am compressing image with luban library,but in samsung phone the vertically taken image are losing quality but in other phones there is no problem at all,the vertically image taken from other phones are perfectly fine,There are no problem in flutter doctor,does't throw any error nothing but this problem occurs only in 

Problem occurs phones
Samsung A20
Samsung A51
Samsung A71

Worked phones
Realme 7
Motorola XT1706

Flutter version 1.22.2
Imagepicker version  image_picker: ^0.6.7+12

## Steps to Reproduce
  
```
Future getImage() async {
    PickedFile image =
        await Imagepicker.getImage(source: ImageSource.camera, maxHeight: 900);

    setState(() {
      _image = File(image.path);
    });
    final tempDir = await getTemporaryDirectory();

    CompressObject compressObject = CompressObject(
      imageFile: _image,
      path: tempDir.path,
      quality: 95,
      step: 4,
      mode: CompressMode.LARGE2SMALL,
    );

    Luban.compressImage(compressObject).then((imageFile) {
      setState(() {
        compressedFile = File(imageFile);

      });
    });
  }
```

**Comment by darshankawar** [comment]
@Abhijithsp 
`flutter_luban` is a 3rd party plugin. Try to remove the relevant plugin code and check if you still getting the quality issue. If not, then it might be the issue with the plugin and you may need to open this issue in plugin owner's repo.

**Comment by Abhijithsp** [comment]
By removing the luban plugin it works fine,but the compression problem occurs only in portrait mode photos.@darshankawar

**Comment by darshankawar** [comment]
@Abhijithsp 
That seems to be an issue with the luban plugin @Abhijithsp. Please consider opening this issue in plugin owner's repo.
Closing this from here. If you disagree, write in comments and I'll reopen.
Thanks.
