### ISSUE TITLE
Widget Test does not load local asset until 2nd test runs

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#69452]
I have a widget test for a screen that contains an icon PNG image. When I run that test, the icon does not appear to load.

By accident, I discovered that if I run 2 tests that display the PNG image, the 2nd test will show it. This seems to indicate some kind of timing issue. However, even if I `await tester.pumpAndSettle()` on the 1st test, the image still never loads.

Here is a minimal repro for a test suite. As far as I know you can put any PNG asset in this example:

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Asset loading bug', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.black,
          body: Center(
            child: Image.asset('assets/add_account.png'),
          ),
        ),
      ),
    );

    await expectLater(
      find.byType(MaterialApp),
      matchesGoldenFile('test/goldens/asset_bug.png'),
    );
  });

  testWidgets('Now it loads', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.black,
          body: Center(
            child: Image.asset('assets/add_account.png'),
          ),
        ),
      ),
    );

    await expectLater(
      find.byType(MaterialApp),
      matchesGoldenFile('test/goldens/asset_bug_2.png'),
    );
  });
}
```

Flutter version:
```
Flutter 1.22.0-10.0.pre.9 • channel master • git@github.com:flutter/flutter.git
Framework • revision 8fa5c55e54 (9 weeks ago) • 2020-08-30 19:05:20 -0700
Engine • revision 1e302a111d
Tools • Dart 2.10.0 (build 2.10.0-76.0.dev)
```

**Comment by matthew-carroll** [comment]
CC @chunhtai because you've worked on issues related to test asset loading in the past.

**Comment by chunhtai** [comment]
@matthew-carroll have you tried precacheImage?

**Comment by pedromassangocode** [comment]
<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-7.0.pre.72, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-7.0.pre.72 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision a2a4e9eda4 (3 hours ago), 2020-11-02 20:12:47 -0800
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by matthew-carroll** [comment]
@chunhtai I am not currently using that, but I just looked up the docs for `precacheImage` and it looks like I have to specify each and every image. The issue here is that devs writing golden tests really shouldn't need to know or care about every image that might appear on a given screen or within a given flow. 

For example, the project I'm working on right now uses a number of SVG and PNG images as custom icons. It's tedious to figure out which of these are used on various screens within a flow where we're generating goldens.

Is there are more generic way to handle this issue?

**Comment by chunhtai** [comment]
This has been an issue that the a lot of widget does not provide a way to wait for its async future. This is related to https://github.com/flutter/flutter/issues/22193

I don't think there is a generic way to handle async image load at this moment.

**Comment by matthew-carroll** [comment]
@chunhtai I noticed that `precacheImage()` requires a `BuildContext`. Is there no way to run `precacheImage()` from a global test entrypoint? Do we really need to invoke it in every single test?

**Comment by chunhtai** [comment]
@matthew-carroll I am not sure if I understand your use case, can you explain a little bit more? or maybe some code snippet?

**Comment by matthew-carroll** [comment]
I'm just taking simple screenshots. One screen here, one screen there. These screens include PNG and SVG assets. As far as I know, what I'm doing is the most vanilla use of golden tests.

**Comment by chunhtai** [comment]
I think I am confused at global test entrypoint is, but you are likely to need to call for every single test.
If you are calling precacheImage, the widget must already be created, at that point you should be able to get BuildContext from the tester.element(find.byType(Image)).

**Comment by matthew-carroll** [comment]
Ok, it sounds like we have a really poor solution for this use-case then. Who would be the best person for me to work with to design a better solution? Should I chat with a dev, or maybe @csells ?

**Comment by chunhtai** [comment]
For the Image specific, I think @dnfield probably has most insight. I remember precacheImage does not really solve the async problem, there are also image decoding that we cannot await for.

**Comment by goderbauer** [comment]
The previous answer is basically the answer here.

**Comment by matthew-carroll** [comment]
@goderbauer I don't think we've received a reasonable answer to this question. I don't see how, in general, a developer is expected to write golden tests when that developer is responsible for explicitly and manually loading whatever image might be relevant for a golden test.

Saying "don't load images" is a terrible answer.

Saying "you need to know what images are loaded, and you need load them in every golden test you write" is an intractable answer.

I'd like for you to re-open this and consider it a meaningful use-case that Flutter currently fails to support.
