### ISSUE TITLE
Adopt a Widget - WillPopScope

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69469]
The [WillPopScope](https://master-api.flutter.dev/flutter/widgets/WillPopScope-class.html) widget needs:

- A code / DartPad sample
- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by sidrao2006** [comment]
I would like to be assigned to this issue.
Thanks

**Comment by Chinmay-KB** [comment]
I would like to contribute to this

**Comment by Chinmay-KB** [comment]
WillPopScope has 2 references now. What kind of references can be added to this to improve the docs, could you give an example?

**Comment by jamesblasco** [comment]
`WillPopScope` is used inside `Form`, it would be nice to reference it. Also, it is a great example to understand why someone would need it.

**Comment by Chinmay-KB** [comment]
Oh that's right, that can be done!!

**Comment by Chinmay-KB** [comment]
I'd love to add a dartpad sample in addition to a code sample, but I don't think we can simulate back button presses in dartpad. Any workaround?

**Comment by sidrao2006** [comment]
@Chinmay-KB , you could create a scaffold, with an AppBar. So the back button will be displayed on the AppBar itself.
It should be enough to simulate the action.
