### ISSUE TITLE
Adopt a Widget - LongPressDraggable

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69473]
The [LongPressDraggable](https://master-api.flutter.dev/flutter/widgets/LongPressDraggable-class.html) widget needs:

- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by kevinrodriguez-io** [comment]
I would like to be assigned to this widget

**Comment by kevinrodriguez-io** [comment]
Awesome, starting on it!

**Comment by pranitb10** [comment]
Hey @johnpryan I'd like to work on it, can you please assign the issue to me?

**Comment by johnpryan** [comment]
@kevinrodriguez-io Can you give us an update today? Otherwise we would like to reassign the issue.

**Comment by kevinrodriguez-io** [comment]
@johnpryan Sure, I've been a little bit heads down but I should be able to test and make a PR today/tomorrow morning. Otherwise I think @pranitb10 is good to go 👍

**Comment by johnpryan** [comment]
No rush, we just need an update.

**Comment by JuYeong0413** [comment]
Hey @johnpryan, the PR has been closed since there hasn't been any updates. Can I work on this issue?

**Comment by johnpryan** [comment]
I think I'm going to close this since the campaign has ended, but feel free to submit a pull request!
