### ISSUE TITLE
Adopt a Widget - SliverWithKeepAliveWidget

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69470]
The [SliverWithKeepAliveWidget](https://master-api.flutter.dev/flutter/widgets/SliverWithKeepAliveWidget-class.html) widget needs:

- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by chihempat** [comment]
Hey, I would like to be assigned for the task :)
