### ISSUE TITLE
Adopt a Widget - Draggable

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69479]
The [Draggable](https://master-api.flutter.dev/flutter/widgets/Draggable-class.html) widget needs:

- A code / DartPad sample
For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by parzuko** [comment]
Hey, I would like to work on this.

**Comment by parzuko** [comment]
Alright awesome!
Just a few doubts:
1) Should I follow [this ](https://github.com/flutter/flutter/blob/master/dev/snippets/config/templates/stateful_widget_ticker.tmpl) documenting / writing style guide ?
2) Is the commit supposed to be in a particular directory or within this issue itself ? 

Cheers!
