### ISSUE TITLE
Adopt a Widget - Stepper

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69471]
The [Stepper](https://master-api.flutter.dev/flutter/material/Stepper-class.html) widget needs:

- A code / DartPad sample
- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by obitodarky** [comment]
@johnpryan I would like to take this issue :D

**Comment by AliAkberAakash** [comment]
can I take this if its still available?

**Comment by viralkachhadiya** [comment]
Hello,

https://master-api.flutter.dev/flutter/material/Stepper-class.html#material.Stepper.1

This above link you see that only provided a sample code of snippet not a dartpad. So that we can not run on there without dartpad.

If you want to assign me then I will complete it.

**Comment by viralkachhadiya** [comment]
> Hello,
> 
> https://master-api.flutter.dev/flutter/material/Stepper-class.html#material.Stepper.1
> 
> This above link you see that only provided a sample code of snippet not a dartpad. So that we can not run on there without dartpad.
> 
> If you want to assign me then I will complete it.

@johnpryan

**Comment by johnpryan** [comment]
That sounds great, thanks.
