### ISSUE TITLE
Adopt a Widget - CircularProgressIndicator

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69476]
The [CircularProgressIndicator / LinearProgressIndicator](https://master-api.flutter.dev/flutter/material/CircularProgressIndicator-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by sidrao2006** [comment]
I would like to be assigned to this issue
Thanks

**Comment by sidrao2006** [comment]
Thanks!
I'll begin working on it right away

**Comment by victormanuelfrancodev** [comment]
I would like to be assigned to this issue
Thanks

**Comment by yash1200** [comment]
@pedromassango The PR related to this issue is merged and this issue should be closed now.

**Comment by sidrao2006** [comment]
Yes please. I tagged this issue on discord too!

**Comment by pedromassango** [comment]
Hi, thanks for letting me know.

**Comment by pedromassangocode** [comment]
Hi, thanks for letting me know.
