### ISSUE TITLE
Adopt a Widget - Hero

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69477]
The [Hero](https://master-api.flutter.dev/flutter/widgets/Hero-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by cv692001** [comment]
Hey @johnpryan  Can you Please assign this to me .

**Comment by JaiAravindh-git** [comment]
I would like to be assigned to this issue.

**Comment by cv692001** [comment]
Hey , Sorry for the delay but I am trying to submit a PR . As it is my first time , I am facing some issues but I will try to figure this out ASAP.

**Comment by johnpryan** [comment]
@cv692001 No problem, don't hesitate to ask questions in the [Discord channel](https://discord.com/channels/608014603317936148/771798504355528704)

**Comment by MrUnfunny** [comment]
Hi, 
I'd like it to work on it, in case, the assignee decides to pass it on.

**Comment by cv692001** [comment]
Started Working on it , will try to submit PR by tonight .Please understand 👍

**Comment by johnpryan** [comment]
@cv692001 No problem, thanks for the update!

**Comment by cv692001** [comment]
I have completed the changes but while pushing this it showing that commit history not same .
![Screenshot (81)](https://user-images.githubusercontent.com/64506066/98099546-b769a500-1eb5-11eb-82a3-02a593fad687.png)

**Comment by cv692001** [comment]
This can be because instead of cloning the forked repo I have downloaded zip and then did further changes . Please help !!

**Comment by MrUnfunny** [comment]
> 
> 
> This can be because instead of cloning the forked repo I have downloaded zip and then did further changes . Please help !!

I don't think downloading zip will work. You should read [this](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment) to properly setup the environment.

**Comment by paulveliz** [comment]
Hi!
I would like to be assigned this issue.

**Comment by kishanhitk** [comment]
I would like to be assigned this issue if it is still available.
