### ISSUE TITLE
Adopt a Widget - Tooltip

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69489]
The [Tooltip](https://master-api.flutter.dev/flutter/material/Tooltip-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by sidrao2006** [comment]
I would like to be assigned to this issue
Thanks

**Comment by tsvillain** [comment]
I would like to be assigned to this issue

**Comment by tsvillain** [comment]
Will start working on it right away
