### ISSUE TITLE
Adopt a Widget - AbsorbPointer

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69484]
The [AbsorbPointer](https://master-api.flutter.dev/flutter/widgets/AbsorbPointer-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by CaptainIRS** [comment]
Hi! I'd like to work on this issue
