### ISSUE TITLE
Adopt a Widget - ReorderableListView

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69482]
The [ReorderableListView](https://master-api.flutter.dev/flutter/material/ReorderableListView-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by sanjoli63** [comment]
I would like to be assigned to this issue

**Comment by anon-000** [comment]
I would like to be assigned to this issue if there is no response from the assignee.

**Comment by sanjoli63** [comment]
i m a beginner, i  m still working on it. It might take some time.. please bare with me.
