### ISSUE TITLE
Adopt a Widget - IgnorePointer

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69485]
The [IgnorePointer](https://master-api.flutter.dev/flutter/widgets/IgnorePointer-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by sidrao2006** [comment]
I would like to be assigned to this issue
Thanks

**Comment by johnpryan** [comment]
@sidrao2006 We assigned you to #69476. We can only assign one issue to each person at a time. Thanks!

**Comment by YazeedAlKhalaf** [comment]
I would like to be assigned to this issue 🚀

**Comment by SANSKARJAIN2** [comment]
hi!
I would like to be assigned this issue.
Thank you.

**Comment by johnpryan** [comment]
Hi @YazeedAlKhalaf , can you give us an update today? Otherwise we would like to reassign this issue.

**Comment by YazeedAlKhalaf** [comment]
I have done a dartpad

I need to generate the docs to make sure it looks good and no typos and will do a pull request today or tomorrow at most 🚀
