### ISSUE TITLE
Adopt a Widget - PageView

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69487]
The [PageView](https://master-api.flutter.dev/flutter/widgets/PageView-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by alistairholmes** [comment]
Hi, may you please assign me to this issue

**Comment by alistairholmes** [comment]
Thank you

**Comment by anon-000** [comment]
I would like to be assigned to this issue if there is no response from the assignee.

**Comment by alistairholmes** [comment]
I had responded and working on the issue mate

**Comment by anon-000** [comment]
> I had responded and working on the issue mate

Nice : )  Keep contributing  👍

**Comment by SANSKARJAIN2** [comment]
Hi!
I would like to be assigned this issue.
Thank you.

**Comment by johnpryan** [comment]
@alistairholmes could you provide an update today? Otherwise we would like to reassign this issue.

**Comment by alistairholmes** [comment]
Hi @johnpryan , yeah sure I'm finishing up my Dart Pad example

**Comment by singhmitesh** [comment]
Hi is there an update? if not, I would like to be assigned this issue.

**Comment by SANSKARJAIN2** [comment]
> Hi is there an update? if not, I would like to be assigned this issue.

I think the concerned person is working on the issue.

**Comment by singhmitesh** [comment]
> > Hi is there an update? if not, I would like to be assigned this issue.
> 
> I think the concerned person is working on the issue.

oh, then it's alright I guess.

**Comment by SANSKARJAIN2** [comment]
hi, I would like to be assigned this issue.
Thank you.

**Comment by johnpryan** [comment]
gentle ping @alistairholmes

**Comment by singhmitesh** [comment]
I would also like to help complete the DartPad example for PageView. @SANSKARJAIN2 I think we should collaborate on this one. If we get assigned. Looking forward to hearing from you. 

Regards
Mitesh

**Comment by JuYeong0413** [comment]
If there's no update, I would like to open a pull request for this issue.
I am ready for the sample code. :-)

**Comment by johnpryan** [comment]
@alistairholmes since we haven't heard back, we're going to re-assign to the next person who expresses interest after this comment.

**Comment by singhmitesh** [comment]
I would like to be assigned this issue. please thank you.

**Comment by SANSKARJAIN2** [comment]
Hi!
I would be like to assigned this issue.
Thank you

**Comment by JuYeong0413** [comment]
I would be like to assigned this issue.

**Comment by singhmitesh** [comment]
Thanks for the assignment. I have started working on it. :-)

**Comment by singhmitesh** [comment]
Hi @johnpryan, 
I forked and pulled the master branch and ran the `./dev/bots/docs.sh` right away and it didn't finish and got struck at :
```
dartdoc:stderr: found 0 warnings and 714 errors
dartdoc:stdout: Documented 163 public libraries in 596.4 seconds
dartdoc:stderr:
dartdoc:stderr: dartdoc failed: dartdoc encountered 714 errors while processing..
dartdoc:stderr: #0      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:231:9)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #1      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:9)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr:
```
Please help me. what should i do?

**Comment by SANSKARJAIN2** [comment]
hi,
you can use the official [discord ](https://discord.gg/BS8KZyg)channel of flutter for discussions, doubts, and help.
There are many developers who are ready to help.
you can also go to this [link](https://github.com/flutter/flutter/wiki/Chat) to understand how to use the chat channel.
Thank you.

**Comment by singhmitesh** [comment]
> hi,
> you can use the official [discord ](https://discord.gg/BS8KZyg)channel of flutter for discussions, doubts, and help.
> There are many developers who are ready to help.
> you can also go to this [link](https://github.com/flutter/flutter/wiki/Chat) to understand how to use the chat channel.
> Thank you.

Thanks @SANSKARJAIN2  for the link to the discord server I couldn't find it and the link on https://flutter.dev/adoptawidget is also not working.
