### ISSUE TITLE
Adopt a Widget - ActionListener

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69480]
The [ActionListener](https://master-api.flutter.dev/flutter/widgets/ActionListener-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by oroblesr** [comment]
I would like to be assigned this issue

**Comment by yash1200** [comment]
I would like to be assigned to this issue if there is no response from the assignee.

**Comment by oroblesr** [comment]
I'm working on the task
