### ISSUE TITLE
Adopt a Widget - ColorFiltered

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69491]
The [ColorFiltered](https://master-api.flutter.dev/flutter/widgets/ColorFiltered-class.html) widget needs:

- A code / DartPad sample
- More references

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by Muskan4010** [comment]
i would like to be assigned for the task

**Comment by shaan-saz** [comment]
I would like to be assigned to this issue if there is no response from the assignee.

**Comment by Muskan4010** [comment]
I am a beginner and still trying to figure out this, please bare with me a little more. I am working on this.

**Comment by shaan-saz** [comment]
No issues. All the Best, Keep contributing.

**Comment by Rexfordasamoah51** [comment]
Hey ya😃, I want to adopt this widget. Kindly, Assign me to it🥳
