### ISSUE TITLE
Adopt a Widget - SnackBar

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69490]
The [SnackBar](https://master-api.flutter.dev/flutter/material/SnackBar-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by Thesmader** [comment]
I would like to be assigned to this issue.

**Comment by Thesmader** [comment]
Some widgets such as ListTile have images in the code samples for illustration([example](https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)). I am a little confused as to how I can contribute these images in a PR.

**Comment by JaiAravindh-git** [comment]
I would like to be assigned to this issue.

**Comment by seonar22** [comment]
I would like to be assigned to this issue.
