### ISSUE TITLE
Adopt a Widget - PreferredSizeWidget

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#69492]
The [PreferredSize / PreferredSizeWidget](https://master-api.flutter.dev/flutter/widgets/PreferredSizeWidget-class.html) widget needs:

- A code / DartPad sample

For details about how to participate, see [flutter.dev/adoptawidget](https://flutter.dev/adoptawidget)

**Comment by nayakastha** [comment]
I want to work on this

**Comment by nayakastha** [comment]
Hey! Can I get the file to make the changes to? There's nothing mentioned in the issue

**Comment by SergioEric** [comment]
> Hey! Can I get the file to make the changes to? There's nothing mentioned in the issue

The instructions are in https://flutter.dev/adoptawidget, you have to clone the flutter repo and follow the guidelines

also, I would like to be assigned to this issue

**Comment by nayakastha** [comment]
I am sorry it's difficult for me to figure out stuff. @johnpryan please assign it to someone else

**Comment by yash1200** [comment]
Don't give up so early, if you need any help ask us on discord. We'll be happy to you help out.

**Comment by SergioEric** [comment]
I would like to adopt this widget.

**Comment by husbycodereis** [comment]
Up for task and would love to adopt the widget!

**Comment by PixelToast** [comment]
Assigning to @SergioEric as the previous assignee unfortunately removed their assignment

**Comment by johnpryan** [comment]
@nayakastha That's okay, we can assign it to the next volunteer. Thanks for participating.

**Comment by AliAkberAakash** [comment]
Hi, I'd like to adopt this widget

**Comment by Rexfordasamoah51** [comment]
Hey ya😃, I want to adopt this widget. Kindly, Assign me to it🥳

**Comment by victormanuelfrancodev** [comment]
Hi!
I would be like to assigned this issue.
Thank you
