### ISSUE TITLE
I'm trying to build a UI as facebook app. The app works fine on the android but the web version gives me this following error. On running flutter devices command in the terminal it does show that there are 3 devices(including chrome) detected. ERROR- "Finished with error: Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues." I have tried updating chrome to the latest version as well. It still shows this error. 

### ISSUE THREAD

**Issue by AadeshGujjar** [flutter/flutter#69496]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hamdikahloun** [comment]
Hi @AadeshGujjar 

I see there's an open issue addressing the case you described : https://github.com/flutter/flutter/issues/68417
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.

Thank you
