### ISSUE TITLE
Errors when running flutter doctor command

### ISSUE THREAD

**Issue by cmee123** [flutter/flutter#69493]
Ok, so I am trying to download flutter and the related apps and set them up. So far I have downloaded the flutter sdk, git, and the android studio. When I run the flutter doctor command I get these errors:

![image](https://user-images.githubusercontent.com/73676421/97782381-392c9c00-1b5f-11eb-8e30-52616ce89c51.png)

I don't know what any of these problems mean or how to solve them. I have already downloaded the android studio and installed the flutter and dart plugins, but it does not recognize that they are there. I also don't know where the android SDK is, because on android studio it says it is set to a place I can't find in my files. What are these errors, what do they mean, and how do I solve them? I am new to this and don't really know what I am doing, so i may need a little more detail for the solutions.

**Comment by hamdikahloun** [comment]
Hi @cmee123 

Failing to detect the plugins will not affect Flutter development at all. The Flutter CLI tool does not touch the plugins, only your editor does. Because of this, we plan to deprecate the plugin validators : https://github.com/flutter/flutter/issues/61246 .

For Powershell warning, Can you try this please https://github.com/flutter/flutter/issues/69462#issuecomment-719917052 .

Thank you

**Comment by cmee123** [comment]
Ok so I think I did that, but it didn’t change anything. I went to the environment variables and then path and pasted it in. I did it on both Variable spots, like the user one and the other one i can’t remember what it’s called, because I didn’t know the difference between them. I ran the command again and nothing changed. Also is there anything I need to do about the “unable to locate android sdk” error? Thanks for your help.

**Comment by cmee123** [comment]
Here are my screenshots: 

![image](https://user-images.githubusercontent.com/73676421/97807555-267d9a00-1c27-11eb-8384-7d3ff0489316.png)

![image](https://user-images.githubusercontent.com/73676421/97807566-31382f00-1c27-11eb-864e-029739547673.png)

**Comment by cmee123** [comment]
Ok so I fixed some of the problems so now when I run the flutter doctor command I get this:

![image](https://user-images.githubusercontent.com/73676421/97807943-4ca43980-1c29-11eb-824f-f1c97cdc55ba.png)

**Comment by pedromassangocode** [comment]
Hi @cmee123 
I would suggest you to try to create and run a Flutter app to see if there is any issue.
As mentioned above sometimes Android Studio does not detect the Flutter plugins but it does not stops you to use Flutter.

I'm closing this for now as this looks like you are looking for assistance.
Thank you
