### ISSUE TITLE
Typo in Codelabs documentation. Prone to confusion

### ISSUE THREAD

**Issue by nahuelbergamo** [flutter/flutter#69504]
Affected page: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#4

Under "Create boilerplate code for a stateful widget." section
The sentence "The boilerplate code for two classes appears, and the cursor is positioned for you to enter the name of your stateless widget."
should read instead: "The boilerplate code for two classes appears, and the cursor is positioned for you to enter the name of your stateful widget."
(replace stateless for stateful) -> Confused a newbie like me, which is the intended audience of this codelab.
![Capture54](https://user-images.githubusercontent.com/3587343/97789143-cb06ca00-1b9c-11eb-9494-785a8bf291ac.PNG)

**Comment by rjayroso** [comment]
If you don't mind I'll take a shot at this

**Comment by chihempat** [comment]
Hey, Can I fix this? 😄

**Comment by domesticmouse** [comment]
Fixed. Thanks for the report!
