### ISSUE TITLE
Document how hot reload can be triggered from inside IntelliJ

### ISSUE THREAD

**Issue by raju-bitter** [flutter/flutter#6950]
Currently the [Run your Flutter app](https://flutter.io/getting-started/#run-your-flutter-app) section of the [Getting Started](https://flutter.io/getting-started/) guide does not provide any information on how to trigger hot reload from within IntelliJ.
https://flutter.io/getting-started/#run-your-flutter-app

### IntelliJ Debug Panel Buttons
![image](https://cloud.githubusercontent.com/assets/296926/20493787/7b267018-b01a-11e6-9231-34e6a904a962.png)
The documentation should contain information on the following buttons in the debug panel of IntelliJ:

- Hot Reload
- Full Application Restart
- Mention 'Rerun main.dart' button on the left, and how it differs from 'Full Application Restart'

### Document Keyboard shortcuts
- Document current keyboard shortcuts for both Mac and Linux for _Hot Reload_ and _Full Application Restart_.
- Link to IntelliJ documentation for how to change keyboard mappings.
- Document _Find action_ command (⇧⌘A on OS X, using settings or menu on Linux) to look for current Flutter keyboard shortcuts.

**Comment by sethladd** [comment]
Agreed, thanks for pointing this out. I think our Getting Started guide should take you through a single change, thus showing you Hot Reload.

I don't think I'd include "Open Observatory", though, in the Getting Started guide.

**Comment by sethladd** [comment]
cc @Sfshaza this one might be a good starter issue?

**Comment by raju-bitter** [comment]
Yes, you are right. "Open Observatory" is probably not useful for beginners.

**Comment by raju-bitter** [comment]
Created pull request: https://github.com/flutter/website/pull/326

**Comment by mit-mit** [comment]
PR was landed, closing bug
