### ISSUE TITLE
Use inline button pictures rather that text description

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#6951]
Page https://flutter.io/intellij-ide says:

"click the **Hot Reload button** (shown with an icon containing a lightning bolt, and a play symbol)"
"click the **Full Application Restart button** (shown with an icon containing a circular arrow)"

Instead, it could simply embed a picture of the corresponding button inline with the text. For example:

"click the ![hot-reload-button](https://cloud.githubusercontent.com/assets/211513/20494473/f4de352e-afd1-11e6-896e-45694ac6f664.png) Hot Reload button"

/cc @mit-mit

**Comment by sethladd** [comment]
Good catch. Thanks!

**Comment by raju-bitter** [comment]
For https://github.com/flutter/flutter/issues/6950 I've already added an image describing the debug toolbar icons, which should be part of "Getting Started. Here's what the image looks like:
![image](https://cloud.githubusercontent.com/assets/296926/20538936/990e9a86-b0f3-11e6-9e1d-970b8aa58257.png)
Same image could be added to page https://flutter.io/intellij-ide/.

**Comment by yjbanov** [comment]
Page no longer exists. Closing.
