### ISSUE TITLE
How to put an widget sticky on the keyboard...with keyboard animation up and down? (especially on iOS)

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#69515]
When the keyBoard open or close,the widget at the bottom in scaffold will jump to new positon,instead of animate to that positon with keyboard animation .So i want to know how to let this widget to sticky on the iOS keyboard..

my flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B5012d, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)


```

**Comment by sidrao2006** [comment]
@luckysmg , if your layout is simple, then you could add a padding around the widget at the  bottom.
Something like this -

```dart
Padding(
  padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom)
  child: // Bottom widget
)
```

**Comment by luckysmg** [comment]
When I tap the TextField.the value of MediaQuery.of(context).viewInsets.bottom will be return twice in a few moment.The first value is 0.0 ,the second value is 335 ,which is the iOS keyboard height,but I need to get the 335 at first time....but I need to wait it to call build twice.....emmm  how to solve this.....

**Comment by sidrao2006** [comment]
@luckysmg , MediaQuery is an InheritedWidget. So, it's dependents (bottom widget in your case) will be rebuilt when it's value changes. So, you don't have to listen for changes and then rebuild the widget

**Comment by luckysmg** [comment]
I know....but I need the val 335,because i need this val to be a tween 's end value........

**Comment by sidrao2006** [comment]
viewInsets.bottom is 0 by default . It represents the system insets (from the bottom). So when the keyboard is closed, the value will be 0, when open, it will be the the height of the keyboard

**Comment by luckysmg** [comment]
Yes,that 's the problem to me....Because I want to get the keyboard height at first time when I tap textfield......hahahahha

Maybe my logic is wrong....

**Comment by sidrao2006** [comment]
Since, this is not an issue with flutter, can you please close this issue?

Thanks!

**Comment by luckysmg** [comment]
Yap
