### ISSUE TITLE
[engine] systemNavigationBarDividerColor is ignored on Android 

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#69528]
https://github.com/flutter/engine/blob/db507f8f0e0c4a082d98366d092138a0a6d1e232/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L271-L274

**Comment by freitzzz** [comment]
Also having problems on beta channel, divider does not show up at all, but is traceable if construction lines are displayed

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Please provide more details about the issue and what's effecting, steps to reproduce, please be descriptive 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by nt4f04uNd** [comment]
@TahaTesser I don't understand you. The enssense of the issue is represented in the title - for some reason the lines of code I attached that are responsible for changing the divider color via the call of `setSystemUIOverlayStyle` are commented out. There's nothing else to say here. 

If you want my flutter doctor so much, here you are
```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.57, on Microsoft Windows [Version 10.0.19041.572], locale ru-RU)
    • Flutter version 1.24.0-4.0.pre.57 at c:\dev\src\flutter
    • Framework revision fdac8a9d1f (8 days ago), 2020-10-25 19:47:02 -0400
    • Engine revision d4a3c9c471
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Yes, it probably not implemented yet
https://github.com/flutter/engine/blob/db507f8f0e0c4a082d98366d092138a0a6d1e232/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L271-L274

Uncommenting that fails to failure on compiling engine for Android
```java
warning: ../../third_party/android_tools/sdk/build-tools/30.0.1/core-lambda-stubs.jar(java/lang/invoke/LambdaMetafactory.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java:273: error: cannot find symbol
      window.setNavigationBarDividerColor(systemNavigationBarDividerColor);
                                          ^
  symbol:   variable systemNavigationBarDividerColor
  location: class PlatformPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
1 warning

[1331/3845] ACTION //third_party/dart/...y(//build/toolchain/android:clang_arm)
ninja: build stopped: subcommand failed.
```

**Comment by nt4f04uNd** [comment]
@TahaTesser shouldn't this be ok if you wrap it with this?
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {

}
```

**Comment by TahaTesser** [comment]
@nt4f04uNd 
Makes sense, let me try it and get back to you soon

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Adding the following, I can compile engine,  `systemNavigationBarDividerColor` variable doesn't exist  this class  so i  provided hardcoded value in this class 
```bash
    if (systemChromeStyle.systemNavigationBarDividerColor != null) {
      // Not available until Android P.

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
          window.setNavigationBarDividerColor(0XFFC70039);
      }
      // window.setNavigationBarDividerColor(systemNavigationBarDividerColor);
    }
```

However, it'snot working even when changing min SDK and providing systemNavigationBarDividerColor value in mind.art 

![flutter_01](https://user-images.githubusercontent.com/48603081/98116215-015e8500-1ece-11eb-93d5-fe6d6b252ca9.png)

I'm not experienced with the engine, somebody would look at this soon 

Docs https://api.flutter.dev/flutter/services/SystemUiOverlayStyle/systemNavigationBarDividerColor.html

**Comment by hamdikahloun** [comment]
Hi @TahaTesser  @nt4f04uNd 

For this to take effect, the window must be drawing the system bar backgrounds with WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS and WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION must not be set.

```
if p != null) {
      // Not available until Android P.

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
          window.setNavigationBarDividerColor(0XFFC70039);
      }
      //window.setNavigationBarDividerColor(systemNavigationBarDividerColor);
    }
```

**Comment by hamdikahloun** [comment]
Hi @nt4f04uNd 

Issue fixed in master channel.

Thank you
