### ISSUE TITLE
AOT snapshotter crashes with "native function ... cannot be found"

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#6952]
[Full log file](https://uberchromegw.corp.google.com/i/client.flutter/builders/Linux/builds/2140/steps/flutter%20build%20apk%20stocks/logs/stdio)

This has been on and off. The earliest build showing it was https://uberchromegw.corp.google.com/i/client.flutter/builders/Linux/builds/2125.

Excerpt from the log:

```
[   +3 ms] /b/build/slave/Linux/build/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --vm_isolate_snapshot=build/aot/snapshot_aot_vmisolate --isolate_snapshot=build/aot/snapshot_aot_isolate --packages=.packages --url_mapping=dart:ui,/b/build/slave/Linux/build/flutter/bin/cache/pkg/sky_engine/dart_ui/ui.dart --url_mapping=dart:jni,/b/build/slave/Linux/build/flutter/bin/cache/pkg/sky_engine/dart_jni/jni.dart --url_mapping=dart:vmservice_sky,/b/build/slave/Linux/build/flutter/bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --embedder_entry_points_manifest=/b/build/slave/Linux/build/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points.txt --embedder_entry_points_manifest=/b/build/slave/Linux/build/flutter/bin/cache/artifacts/engine/android-arm-release/dart_io_entries.txt --rodata_blob=build/aot/snapshot_aot_rodata --instructions_blob=build/aot/snapshot_aot_instr --embedder_entry_points_manifest=/b/build/slave/Linux/build/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points_android.txt --no-sim-use-hardfp --no-use-integer-division /b/build/slave/Linux/build/flutter/examples/stocks/lib/main.dart
[+1018 ms] Error: 'dart:_internal-patch/class_id.dart': error: line 8 pos 3: native function 'ClassID_byName' (1 arguments) cannot be found
             static int _lookup(String name) native "ClassID_byName";
             ^
[        ] Dart snapshot generator failed with exit code 254
[   +1 ms] Error: 'dart:_internal-patch/class_id.dart': error: line 8 pos 3: native function 'ClassID_byName' (1 arguments) cannot be found
             static int _lookup(String name) native "ClassID_byName";
             ^
[   +3 ms] 'flutter apk' took 1529ms.
Failed to build AOT snapshot
```

/cc @rmacnak-google

**Comment by rmacnak-google** [comment]
@a-siva

**Comment by a-siva** [comment]
Appears to be an issue with NativeResolver not being set when a snapshot is being generated.

**Comment by abarth** [comment]
I believe we investigated this issue and determined it was due to gen_snapshot reading source files from disk instead of using the versions it has compiled in.  The buildbot has newer versions of these source files at the magical path because it also builds the engine on the same file system.  The short-term solution is to roll the engine in flutter.git.  The long-term solution is to stop gen_snapshot from reading source files off disk if they happen to exist.

/cc @Hixie @jason-simmons

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2518233003

**Comment by Hixie** [comment]
I... don't understand how that patch fixes this bug. :-)

**Comment by johnmccutchan** [comment]
Adding @a-siva in case there is a remaining issue with different native resolvers.

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/issues/27860 has been submitted, please roll Dart and see if the issue is fixed.
