### ISSUE TITLE
cannot find zipfile directory in one of  flutter/bin/cache/dart-sdk-darwin-x64.zip 

### ISSUE THREAD

**Issue by Sherafatpour** [flutter/flutter#69526]

**Comment by iapicca** [comment]
possible duplicate (with solution) of https://github.com/flutter/flutter/issues/54175#issuecomment-610213239

**Comment by darshankawar** [comment]
@Sherafatpour 
Please check the above referred issue and possible solution and see if it works for you.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
