### ISSUE TITLE
Failed assertion when clearing

### ISSUE THREAD

**Issue by treeplate** [flutter/flutter#69546]
When you press left arrow on a textfield on mac, and you are at index 0, it throws `Failed assertion: line 564 pos 12: 'index >= 0 && index <= string.length': is not true.`

**Comment by pedromassangocode** [comment]
Hi @treeplate 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by treeplate** [comment]
Actually, the problem is when you are at the end of the text field and you `clear` the controller

**Comment by treeplate** [comment]
I cannot reproduce anymore...
