### ISSUE TITLE
SliverAppBar Empty Space 

### ISSUE THREAD

**Issue by tharwatsamy** [flutter/flutter#69551]
when using a sliver app bar there is a space reserved for the leading , title and actions widget weather I used them or not but the problem is that space takes the same color as the sliver app bar but in some cases I want it to be of a different color.  I did solve it but it took me a bit of effort to make it responsive and i think that there should be a color attribute for that space or a bool value that let me git rid of it  that would be a lot easier and it is something I expected it to be there . so I think this is an issue with flutter
![Capture](https://user-images.githubusercontent.com/63080646/97825490-76ac3900-1cc7-11eb-8573-1103b3fcd6b8.JPG)

**Comment by iapicca** [comment]
@tharwatsamy 
what is the use case of assigning a `Color` to an empty space?
Isn't your feature request obtainable simply passing a `LayoutBuilder` + `Container` as in this [code sample](https://dartpad.dartlang.org/62e57b21d04bdf7f519a8a74bc1e2a5e)?

 @TahaTesser opinion?

**Comment by TahaTesser** [comment]
Hi  @tharwatsamy 
@iapicca made some good points, can you please provide more details and try this above code sample

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
