### ISSUE TITLE
Consider deprecating StatusTransitionWidget

### ISSUE THREAD

**Issue by PixelToast** [flutter/flutter#69558]
## Background

[`StatusTransitionWidget`](https://api.flutter.dev/flutter/widgets/StatusTransitionWidget-class.html) was added 5 years ago and is not used within the framework, it seems to serve the same role as [`AnimatedBuilder`](https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html) but has a more confusing name and requires a `Animation<double>` instead of a more generic ` Listenable`.

## Proposal

This widget should be deprecated and removed.

**Comment by Sameerkash** [comment]
If this is approved I'd like to deperacte and remove it. 

If there's any special process please let me know. 

@PixelToast

**Comment by PixelToast** [comment]
@Sameerkash There is no assignee so you are free to draft a PR, thanks!

**Comment by Sameerkash** [comment]
How do I approach this? Any pointers ?@PixelToast

**Comment by PixelToast** [comment]
To deprecate a class we would use the [Deprecated](https://api.dart.dev/dev/2.12.0-51.0.dev/dart-core/Deprecated-class.html) annotation, you can search through existing code and other PRs to see what the message usually contains.

Since this is a breaking change we would also need to draft a migration guide, the whole process is detailed here: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

If you have further questions feel free to ask on Discord: https://github.com/flutter/flutter/wiki/Chat

**Comment by Sameerkash** [comment]
Thanks, @PixelToast ! I'll follow the same

**Comment by Hixie** [comment]
As far as I can tell this widget is a more efficient specialization of AnimatedBuilder -- it only builds when the status of the animation changes, not when the value changes. Is it causing any harm?

**Comment by goderbauer** [comment]
As Hixie says above, the widget is not causing any harm and it provides useful functionality. I don't see reason to deprecate it.
