### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by mohamedhasan2002** [flutter/flutter#69560]
**Hey, I had built an app using GitHub the first time my code runs perfect but later I duplicated the file and made changes now I can install my app but it fails to open(getting crash) There is no error can anyone help me to fix.**

[](https://drive.google.com/file/d/1dnaGYyAj4V9_Odok8V5GayUtF1-oCTT_/view?usp=sharing)

**Comment by pedromassangocode** [comment]
Hi @mohamedhasan2002 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by mohamedhasan2002** [comment]
**flutter doctor -v**
hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/CODE/ChitChat-master$ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-7.0.pre.47, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.24.0-7.0.pre.47 at /home/hasan/snap/flutter/common/flutter
    • Framework revision 2f18e0b23d (22 hours ago), 2020-11-01 20:58:04 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/hasan/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**flutter run --verbose**

hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/CODE/ChitChat-master$ flutter run --verbose
[ +334 ms] executing: [/home/hasan/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +92 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 2f18e0b23d83f7272dfd0d7c1f7dcde2c3504c60
[   +2 ms] executing: [/home/hasan/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +24 ms] Exit code 0 from: git tag --points-at HEAD
[   +5 ms] executing: [/home/hasan/snap/flutter/common/flutter/] git describe --match *.*.* --first-parent --long
--tags
[  +52 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.24.0-6.0.pre-47-g2f18e0b23d
[  +29 ms] executing: [/home/hasan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/hasan/snap/flutter/common/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +124 ms] executing: [/home/hasan/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +158 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +242 ms] executing: /home/hasan/Android/Sdk/platform-tools/adb devices -l
[  +92 ms] List of devices attached
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +145 ms] No supported devices connected.
[  +27 ms] "flutter run" took 566ms.
[  +52 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:420:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1034:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:925:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:914:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:302:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[ +315 ms] ensureAnalyticsSent: 302ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +5 ms] exiting with code 1

**Comment by pedromassangocode** [comment]
Hi @mohamedhasan2002 
Make sure you have a supported device connected before running the command.

**Comment by mohamedhasan2002** [comment]
it works before but now the app crashes!

**Comment by hamdikahloun** [comment]
Hi @mohamedhasan2002 


> • Java version OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)

Can you try please with JDK 8 : 

1. Installing OpenJDK 8

```
sudo apt update
sudo apt install openjdk-8-jdk
```

2. Setting the Default Version

```
sudo update-alternatives --config java

Output : 

There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
```

3. Verify the installation by checking the Java version:
```
java -version

Output:

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by mohamedhasan2002** [comment]
**NOT WORKING BRUH!**
**AGAIN GETTING CRASH**
hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/CODE/ChitChat-master$ flutter build apk
Running "flutter pub get" in ChitChat-master...                     3.7s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more: https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-1.4.3+2/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+2/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1/android/src/main/java/io/flutter/plugins/cloud_firestore_web/FirestoreWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/android/src/main/java/io/flutter/plugins/firebaseauth_web/FirebaseAuthWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+2/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.3/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:31: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry;                         
                               ^                                        
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:46: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) { 
                                  ^                                     
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:60: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
        binding.getApplicationContext(), binding.getFlutterEngine().getDartExecutor());
                                                ^                       
3 warnings                                                              
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+2/android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/android/src/main/java/com/baseflow/location_permissions/LocationPermissionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     299.8s
✓ Built build/app/outputs/flutter-apk/app-release.apk (21.3MB).
hasan@hasan-Lenovo-ideapad-320-15IAP:~/Desktop/CODE/ChitChat-master$

**Comment by hamdikahloun** [comment]
Hi @mohamedhasan2002 

Thank you for your feedback. 

From what I can see, there is no crash and the application has been successfully compiled : 

> Running Gradle task 'assembleRelease'... Done 299.8s
> ✓ Built build/app/outputs/flutter-apk/app-release.apk (21.3MB).

**Comment by pedromassangocode** [comment]
Hi @mohamedhasan2002 
Make sure you have a supported device connected before running the command and then run `flutter run --verbose` and once the crash happens share the logs here.

**Comment by mohamedhasan2002** [comment]
**HOWDY**
@hamdikahloun thanks for replying...
I'm able to build APK but when I run on my device the app crashes!!!
and @pedromassangocode when the run device it closes...

_I made this before getting the error(forgot to mention): On the Find & Replace box I find the word 'ChitChat' and I replaced with 'FlirtBak' after making these changes I'm getting my app crash when I opened!!!_

**Comment by pedromassangocode** [comment]
> I'm able to build APK but when I run on my device the app crashes!!!
> and @pedromassangocode when the run device it closes...

I think that you can still get the crash logs from the console.

**Comment by mohamedhasan2002** [comment]
![launch](https://user-images.githubusercontent.com/28563234/98079865-892a9c00-1e9a-11eb-9bdf-87f5e661ffbc.png)

@pedromassangocode

**Comment by mohamedhasan2002** [comment]
Running "flutter pub get" in ChitChat-master...
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
 lib/main.dart
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-1.4.3+2/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+2/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1/android/src/main/java/io/flutter/plugins/cloud_firestore_web/FirestoreWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/android/src/main/java/io/flutter/plugins/firebaseauth_web/FirebaseAuthWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.3/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+2/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:31: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
import io.flutter.plugin.common.PluginRegistry;
                               ^
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:46: warning: [deprecation] PluginRegistry in io.flutter.plugin.common has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                  ^
/home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.1.1/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:60: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
        binding.getApplicationContext(), binding.getFlutterEngine().getDartExecutor());
                                                ^
3 warnings
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_image-0.0.5+2/android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/android/src/main/java/com/baseflow/location_permissions/LocationPermissionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/hasan/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/hasan/Desktop/CODE/ChitChat-master/android/app/src/debug/AndroidManifest.xml Error:
	Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-27 value=(com.chitchat)
	has a different value=(com.newstroopp.flirtbak) declared in main manifest at AndroidManifest.xml:2:5-38
	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
		flavorName {
			applicationId = "com.chitchat"
		}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-27 value=(com.chitchat)
  	has a different value=(com.newstroopp.flirtbak) declared in main manifest at AndroidManifest.xml:2:5-38
  	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
  		flavorName {
  			applicationId = "com.chitchat"
  		}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 39s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by pedromassangocode** [comment]
Hi @mohamedhasan2002 
Please make sure you follow the suggestion in the message logs:

```
/home/hasan/Desktop/CODE/ChitChat-master/android/app/src/debug/AndroidManifest.xml Error:
Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-27 value=(com.chitchat)
has a different value=(com.newstroopp.flirtbak) declared in main manifest at AndroidManifest.xml:2:5-38
Suggestion: remove the overlay declaration at AndroidManifest.xml and place it in the build.gradle:
flavorName {
applicationId = "com.chitchat"
}
```

Closing as this is not an issue with Flutter itself.
