### ISSUE TITLE
windows batch file not running

### ISSUE THREAD

**Issue by darshanhk18** [flutter/flutter#69569]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

![Screenshot (144)](https://user-images.githubusercontent.com/64367776/97867237-7cd7ff00-1d33-11eb-8f7f-264b16a16f1d.png)
![Screenshot (145)](https://user-images.githubusercontent.com/64367776/97867249-82354980-1d33-11eb-91e0-f50c38b5ce6d.png)

```
```

**Comment by TahaTesser** [comment]
Hi @darshanhk18 
Please follow the steps form https://flutter.dev/docs/get-started/install/windows and install the tools including Android SDK manager 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
