### ISSUE TITLE
TextFormField should be validate independently of the form

### ISSUE THREAD

**Issue by oom-** [flutter/flutter#69577]
## Use case

I have a huge `Form` with a lot of `TextFormField`, my `validator` callback is checking if the length of the actual text is empty + has matches with Regex.

If I set up the `autovalidateMode` of my `Form` to ` AutovalidateMode.always` all my TextFormField turn red instantly (because they are all empty).
But I want to call the validator of the actual field `onChanged` event.

This allow the user to understand directly if what he is writting is good or no, instead of having to scroll to the bottom of the page to click on the `Form` validation button.

## Proposal
Add a `validate` methods to the `TextFormField` widget not only to the `Form`

**Comment by sidrao2006** [comment]
@oom- , have you tried using `AutoValidateMode.onUserInteraction`? Does that solve your problem? 
Thanks

**Comment by TahaTesser** [comment]
Hi @oom- 
I think it's not the solution to add validate`TextFormField` itself
Can you please `onUserInteraction` ?
Thank you

**Comment by oom-** [comment]
> @oom- , have you tried using `AutoValidateMode.onUserInteraction`? Does that solve your problem?
> Thanks

Hello @sidrao2006 and @TahaTesser , I just tryed it, doesn't seems to do nothing. No validation at all.
(I tried to add `autovalidateMode: AutovalidateMode.onUserInteraction` in the Form and/or in the TextField itself).

There is my actual version of Flutter: 
> Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git 
> Framework • revision 8874f21e79 (10 days ago) • 2020-10-29 14:14:35 -0700
> Engine • revision a1440ca392
> Tools • Dart 2.10.3

`flutter doctor -v`
> [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [version 10.0.19041.572], locale fr-FR)
>     • Flutter version 1.22.3 at D:\FlutterSDK\flutter
>     • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
>     • Engine revision a1440ca392
>     • Dart version 2.10.3
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at D:\AndroidSDK
>     • Platform android-30, build-tools 29.0.2
>     • ANDROID_SDK_ROOT = D:\AndroidSDK
>     • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
>     • All Android licenses accepted.
> 
> [!] Android Studio (version 3.1)
>     • Android Studio at D:\Program Files\Android\Android Studio
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
> 
> [√] VS Code (version 1.51.0)
>     • VS Code at C:\Users\OOM\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.16.0
> 
> [√] Connected device (1 available)
>     • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> ! Doctor found issues in 1 category.

I'm using VSCode then I do not need Android studio plugins

**Comment by Gowtham-mg** [comment]
Im using onUserInteration for autoValidate in Form, but the screen looks clean on 1st rendering. But once user taps on any one TextFormField and start changing something, other TextFormField's which are not focused by user are all validated and shows error text, which is an unusual behaviour. 

For environment reference: I'm using Flutter 2.0.5 Flutter stable and Dart sdk 2.12.3, Framework revision adc687823a, Engine revision b09f014e96.

**Comment by renatomotorline** [comment]
@TahaTesser 
I have the same problem of @Gowtham-mg
