### ISSUE TITLE
My app is working fine on debug but release version only shows a white screen 

### ISSUE THREAD

**Issue by Abdulbasit096** [flutter/flutter#69578]
![image](https://user-images.githubusercontent.com/55397611/97881074-bf093c80-1d43-11eb-9b96-16ce1d95e747.png)

**Comment by sidrao2006** [comment]
Hello @Abdulbasit096 ,
Could you please try updating to the latest beta with `flutter upgrade`, post the output of `flutter run -v` and a provide complete minimal reproducible code sample?
Thank you!

**Comment by TahaTesser** [comment]
Hi @Abdulbasit096 
If you're loading from network, please make sure you've internet permissions 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
