### ISSUE TITLE
InputDatePickerFormField should implement textInputAction

### ISSUE THREAD

**Issue by oom-** [flutter/flutter#69572]
## Use case

I'm actually creating a Form with multiples inputs. I can easily pass from one to another with the `textInputAction: TextInputAction.next,`. But the `InputDatePickerFormField` that is in the middle of the form break the chain because the option doesn't exist.

## Proposal
Add a property similar to `textInputAction` to be able to focus on the next field without hiding the keyboard.

**Comment by yash1200** [comment]
If the issue get proposal label then I would like to work on this issue

**Comment by TahaTesser** [comment]
Hi @oom-  @yash1200 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/68057
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
