### ISSUE TITLE
linux_chrome_dev_mode windows_chrome_dev_mode SecondStartupTime regressions...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69584]
https://flutter-flutter-perf.skia.org/e/?begin=1603931826&end=1604318285&keys=X38049179c4cfa0117ce7066e6ed46258&requestType=0&xbaroffset=22297.

Might be a test issue? It occurs at https://github.com/flutter/flutter/pull/69405.

@jonahwilliams I hate to throw this one to you; it seems like I pick on you a lot for these. But this went up at your commit. When you have a minute can you comment and let me know how to route this? Thanks!

**Comment by jonahwilliams** [comment]
I'm going to downgrade the priority and investigate separately, this is not a regression that would block a release

**Comment by jonahwilliams** [comment]
I'm not currently looking at this

**Comment by Hixie** [comment]
Given that we didn't immediately track this regression down, we should probably close it, we'll never figure it out now.

**Comment by darshankawar** [comment]
Based on @Hixie's above comment, I am closing this issue. Please write in comments if it need to be kept open.
