### ISSUE TITLE
all_elements_iteration MatrixUtils_affine_transformRect_iteration MatrixUtils_persp_transformPoint_iteration regressions in microbenchmarks microbenchmarks_ios

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#69586]
See https://flutter-flutter-perf.skia.org/e/?begin=1603922986&end=1604318285&keys=X240a894f758f176e8e069a4a26976380&requestType=0&xbaroffset=22291. Looks like engine roll https://github.com/flutter/flutter/pull/69353.

**Comment by zanderso** [comment]
These microbenchmarks might have been affected by the VM/compiler changes in the Dart roll here https://github.com/flutter/flutter/pull/69353: https://dart.googlesource.com/sdk.git/+log/6e015bd9cddb..9c6e76468ca4

**Comment by chinmaygarde** [comment]
@jason-simmons attempted to reproduce this regression at the specified commit and was not successful. He was using Android (Moto G4 armv7). @liyuqian, Do you know which device these benchmarks run on? @zanderso suspects that this may be VM related and possible to reproduce on an 64 bit device.

**Comment by liyuqian** [comment]
According to https://github.com/flutter/flutter/blob/8291f4810f5107d2df498d383c4a656c92f22c90/dev/devicelab/manifest.yaml#L380 `microbenchmarks` perf test is running on a Moto G4 that's connected to a Mac Mini host.

**Comment by jason-simmons** [comment]
The Skia dashboard link above is showing a 25% increase in the `microbenchmarks`/`all_elements_iteration` metric on Android starting at https://github.com/flutter/flutter/commit/e444b1e3fa6f0478c885565a78498480591cc980

I have not been able to reproduce this on the 32-bit (Moto G4) and 64-bit (Nexus 5x) devices that I've tried.  The results on the Nexus 5x have been bimodal but I have not found a correlation with that engine roll.

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/dart-lang/sdk/commit/8f5f6971a90609f1ea7dd2dc766527e28ba89475

**Comment by mkustermann** [comment]
@jason-simmons We have identified a regression from that commit as well on golem. The fix was landed yesterday in https://github.com/dart-lang/sdk/commit/132bec50fcd4bc8dff85b9e4debfd61b1df2d960 . The next roll should pick it up.

**Comment by zanderso** [comment]
This recovered in https://github.com/flutter/flutter/commit/bf94fa072d4eca3e9ebcecde044874384b157f0c
