### ISSUE TITLE
Problem with android 8 devices

### ISSUE THREAD

**Issue by EDnny12** [flutter/flutter#69587]
I’m have this problem: reports in my play console: a5xcontext::hwpatchfordirectrendering(esxrenderbucket*, esxlinkedlist*, unsigned int)

Now only android 8

**Comment by hamdikahloun** [comment]
Hi @EDnny12 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal complete reproducible code sample?

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
