### ISSUE TITLE
Enable tests on Mac bots

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6958]
Turns out we're still not actually running the tests on Mac bots.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/6961 has to be fixed first

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/6964 too

**Comment by yjbanov** [comment]
I think it would be better if we could run them on Travis' Mac environment, which would allow us to catch regressions earlier, but last time I checked (https://github.com/flutter/flutter/pull/4027) the tests froze at random locations.

**Comment by Hixie** [comment]
Well we should run them in both places, but running them on either is better than none...

**Comment by Hixie** [comment]
Done.
