### ISSUE TITLE
Report Dart language version in analytics

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#69601]
We'd like to be able to gauge null safety usage. With the experiment flag being removed, that won't give us an indication. It would be great if we could track the language version that an app is being run/analyzed/build (basically any action that analysis/compiles Dart code).

**Comment by jonahwilliams** [comment]
Since different libraries can be opted into different versions, I assume we want the single language version from the SDK constraint in the pubspec.yaml?

**Comment by mit-mit** [comment]
I think the best would be the language version of the entry point root package. I think it may be easier to get this from `.dart_tool/package_config.json` (this is from a Dart app called `pubs`):

```
    {
      "name": "pubs",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.8"
    }
```

?

**Comment by mit-mit** [comment]
cc @lrhn @leafpetersen if they have thoughts on this

**Comment by leafpetersen** [comment]
This would be great data to get.  The top level bit would be "what language version is specified for this package by whatever package_config.json controls this package/app".  A second order bit that would be nice to have is what mode builds/runs are done in (sound null safety or no sound null safety).

**Comment by jonahwilliams** [comment]
FYI The tooling has no idea what mode an app is built in, we can only measure sound mode via a vm service query.

**Comment by jonahwilliams** [comment]
(We could distinguish the cases where a user provided --sound-null-safety or --no-sound-null-safety, but not autodetect)

**Comment by leafpetersen** [comment]
Detecting default package language version + explicit --no-sound-null-safety would probably be a reasonable set of data.

**Comment by mit-mit** [comment]
Agree!

**Comment by devoncarew** [comment]
What are the questions we're going to want answered with this info? General uptake of null safety? General language version uptake (who's using 2.12, how fast the ecosystem is migrating, ...)?

I'm wondering if it would be sufficient to sample this information (the package language version) for specific commands. So, to just collect it for a `pub get`, or just for a `flutter run`.

**Comment by Hixie** [comment]
The ultimate questions I'd be answering with this data are:
 * Is it time to tell people to migrate their applications?
 * Is it time to remove the redundant null asserts in the framework?
 * Is it time to remove non-null-safe support?
 * Do we need to do more to migrate the ecosystem?

To answer these questions, I'd ideally use the following data, ideally collected into some sort of 28 day aggregate, based on users in the field running applications:
 * How many dependencies are not yet migrated, and thus preventing the application from migrating?
 * What fraction of the application's dependencies are not yet migrated, and thus preventing the application from migrating?
 * Is the application itself migrated?
 * What mode did the application run in?
 * Was the migration tool executed?
 * What are the SDK constraints specified in the pubspec.yaml?
 * How many files, or what fraction of files, involved in a compilation were explicitly opted in/out of null safety?

So for example, I might look at a histogram showing the highest number of dependencies are not yet migrated for each user in the last 28 days, or a graph showing the median of that number varying over time. I might look at the fraction of our users who, at some point in the last 28 days, compiled code in non-null-safe mode, and how that number varies over time.

**Comment by jonahwilliams** [comment]
@devoncarew  is there a way to tell if `dart migrate` has been run on a project?

**Comment by devoncarew** [comment]
No, it doesn't leave behind any uniquely identifying artifacts. Just things like bumping the min sdk constraint in the pubspec and re-writing source files, but not token that's unique to 'dart migrate'.

**Comment by jonahwilliams** [comment]
I've landed a first pass at this in  #71487. Once we start getting some measurements I'll follow up to make sure we're on the right track

**Comment by jonahwilliams** [comment]
(Also bumping to P4 and removing assignment since we are now waiting)

**Comment by jonahwilliams** [comment]
We have measurements coming in for language versions now. If there are future questions we need help answering we can open new issues
