### ISSUE TITLE
LinearProgressIndicator is not working 

### ISSUE THREAD

**Issue by FrancescoMasaia** [flutter/flutter#69619]
Flutter is already up to date on channel beta
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (3 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)

given error:
═══════════════════════ Exception caught by widgets library ═════════════════════════════
Unexpected null value.
The relevant error-causing widget was: 
  LinearProgressIndicator

with Circular one is working without problems

**Comment by HansMuller** [comment]
Can you provide a small self-contained example that demos the problem, as well as the output from flutter doctor?

**Comment by pedromassangocode** [comment]
Hi @FrancescoMasaia 
We will need a clear actual vs expected results of the issue.

**Comment by FrancescoMasaia** [comment]
```
import 'package:flutter/material.dart';
void main() => runApp(MyApp());

class BookPages extends StatefulWidget {
  @override
  _BookPagesState createState() => _BookPagesState();
}

class _BookPagesState extends State<BookPages> {
  @override
  Widget build(BuildContext context) {
    //return new CircularProgressIndicator();
    return new LinearProgressIndicator();
    );
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: BookPages(),
      ),
    );
  }
}
```

return new CircularProgressIndicator, works but when I switch to LinearProgressIndicator() it gives me that error

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.47.3)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by HansMuller** [comment]
This appears to be a consequence of https://github.com/flutter/flutter/pull/69060.  Including a widget that include a Directionality widget, like MaterialApp, will fix the problem.

CC @goderbauer

**Comment by goderbauer** [comment]
The LinearProgressIndicator always needed a Directionality widget, even before #69060. However, before that PR you were getting a undescriptive error null assertion error. With this change in place you get the more descriptive error that tells you to wrap your app in a MaterialApp or Directionality widget. Doing so is the right fix here.
