### ISSUE TITLE
White screen on IOS version of the Flutter app

### ISSUE THREAD

**Issue by Schweinsei007** [flutter/flutter#69639]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Schweinsei007 
There's no description / details of the issue you are facing. Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
