### ISSUE TITLE
Flutter stuck in state "Waiting for another flutter command to release the startup lock..." due to issues with flock

### ISSUE THREAD

**Issue by Ashok-Varma** [flutter/flutter#69635]
## Steps to Reproduce

1. I tried upgrading flutter and since process is taking long i cancelled it (^c)
2. Flutter state never recovered from then, every flutter command gives error `Waiting for another flutter command to release the startup lock...` including `flutter doctor`

**System Info**
- System : mac 10.15.6 (catalina)
- Network : 500 Mbps ethernet (no VPN)
- OS : Mac Catalina 10.15.6
-  Version : Flutter (1.20.0), Dart (dart packaged with flutter 1.20.0)
- `flutter pub pub get --verbose` gives same `Waiting for another flutter command to release the startup lock...` error. (Any flutter command is giving same error)

## Tried solutions (But these didn't work)
1. Removed lockfile
2. cleaned repo `git clean -fdx`
3. cloned repo to new folder and changed ENV to reflect new folder
4. removed all flutter related caches that i can see
```
rm -rf ~/.pub-cache
rm -rf ~/.dart
rm -rf ~/.dartServer
rm -rf ~/.flutter
rm -rf ~/.flutter_tool_state
```

## Working Solution 
[As mentioned in this thread](https://github.com/dart-lang/pub/issues/2609#issuecomment-710783662) by @RoelandW

> Please first check if you have flock installed by executing flock in the terminal. If you have, please try the following:

Edit file FLUTTER_HOME/bin/internal/shared.sh.

Change line 46 from:
flock --nonblock --exclusive 7 2>/dev/null
to:
flock -n 7 2>/dev/null

### Similar Issues

- [dart-lang/pub#2609](https://github.com/dart-lang/pub/issues/2609)
- #63259
- #63264

**Comment by hiashutoshsingh** [comment]
delete your lock file in `flutter/bin/cache/lockfile` and run flutter pub get again @Ashok-Varma

**Comment by darshankawar** [comment]
@Ashok-Varma 
When you say `due to issues with flock`, are you using the `flock` plugin by any chance ?

**Comment by ceeyang** [comment]
```shell
➜  rm /Users/username/development/flutter/bin/cache/lockfile
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
