### ISSUE TITLE
customer_testing failures

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#69646]
In the last few days, I've been noticing that a few PRs have been failing the `*customer_testing` checks, just like this: https://github.com/flutter/flutter/pull/69562/checks?check_run_id=1344873525

Initially, I recommended merging/rebasing with the latest `master` since the test failures seem unrelated to the changes. However, this does not work and the only way it has worked for me is by deleting my copy of flutter and reforking a fresh copy of the framework.

Maybe this doesn't require a fix anywhere, but does anybody have a recommendation for how to resolve the check failures in a different way?

**Comment by christopherfujino** [comment]
This issue should be fixed by https://github.com/flutter/flutter/pull/69726. The underlying issue was that when merging upstream, the tool would not consider version tags from the merged in branch. A rebase would have solved (but can be difficult).
