### ISSUE TITLE
自定义plugin  腾讯地图map 在某些apple手机上显示异常

### ISSUE THREAD

**Issue by pomegra** [flutter/flutter#69640]
自定义plugin  腾讯地图map 在某些apple手机上显示异常: iPhone8plus iOS13.5     

map在界面上渲染异常,导致地图widget周边出现4条黑线，排查过暂时无法解决,请问如何解决

**Comment by pedromassangocode** [comment]
Hi @pomegra 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

[Google Translate]

嗨@pomegra
您能否提供您的Flutter Doctor -v，您的Flutter运行--verbose，您的pubspec.yaml和一个最小的完整可复制代码示例？
谢谢

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
