### ISSUE TITLE
When I used bottomNavigationBar + IndexedStack with PageTransitionSwitcher, I tried to save the state of each page, which caused PageTransitionSwitcher to lose the animation effect.

### ISSUE THREAD

**Issue by FieeA** [flutter/flutter#69649]
When I used bottomNavigationBar + IndexedStack with PageTransitionSwitcher, I tried to save the state of each page, which caused PageTransitionSwitcher to lose the animation effect.
----------------------------------------------------
here is the code

```
List<Widget> _navPageList = [PageA(), PageB(), PageC()];

return Scaffold(
      body: PageTransitionSwitcher(
        transitionBuilder: (
          Widget child,
          Animation<double> animation,
          Animation<double> secondaryAnimation,
        ) {
          return FadeThroughTransition(
            animation: animation,
            secondaryAnimation: secondaryAnimation,
            child: child,
          );
        },
        child: IndexedStack(
          index: _navIndex,
          children: _navPageList,
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        onTap: didTapBottomItem,
        currentIndex: _navIndex,
        items: _items,
      ),
    );
```

**Comment by darshankawar** [comment]
@FieeA 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by FieeA** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/imac/Desktop/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

------------------
class NavigationPage extends StatefulWidget {
  @override
  _NavigationPageState createState() => _NavigationPageState();
}

class _NavigationPageState extends State<NavigationPage> {
  List<BottomNavigationBarItem> _items = [
    BottomNavigationBarItem(
      title: Text('PageA'),
      icon: Icon(Icons.business),
    ),
    BottomNavigationBarItem(
      title: Text('PageB'),
      icon: Icon(Icons.colorize),
    ),
    BottomNavigationBarItem(
      title: Text('PageC'),
      icon: Icon(Icons.person),
    ),
  ];
  List<Widget> _navPageList = [PageA(), PageB(), PageC()];
  int _navIndex = 0;

  didTapBottomItem(int index) {
    setState(() {
      _navIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageTransitionSwitcher(
        transitionBuilder: (
          Widget child,
          Animation<double> animation,
          Animation<double> secondaryAnimation,
        ) {
          return FadeThroughTransition(
            animation: animation,
            secondaryAnimation: secondaryAnimation,
            child: child,
          );
        },
        child: IndexedStack(
          index: _navIndex,
          children: _navPageList,
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        onTap: didTapBottomItem,
        currentIndex: _navIndex,
        items: _items,
      ),
    );
  }
}

------------------
I usually use BottomNavigationBar + IndexedStack to implement the bottom navigation bar and maintain the state, but when I nest PageTransitionSwitcher outside of IndexedStack, its animation effect is invalid.

thanks!

**Comment by darshankawar** [comment]
@FieeA 
You seem to be on older version of Flutter. Please upgrade to latest stable (1.22.3) and try again to see if you still experience the issue.
Thanks.

**Comment by FieeA** [comment]
I update my flutter version to 1.22.3 , but it still doesent work. Whether PageTransitionSwitcher does not support keepalive of single pages in the bottom navigation bar?

**Comment by darshankawar** [comment]
@FieeA 
You seem to be using a third party plugin for `PageTransitionSwitcher` and `FadeThroughTransition`. Can you remove the relevant plugin code and use Flutter's core animation transitions to see if you get similar behavior ? If so, please provide the updated code sample.
Thanks.

**Comment by FieeA** [comment]
after all i tried,i decide not use this plugin,anyway thank you very much for your reply
