### ISSUE TITLE
TextFlied Crash

### ISSUE THREAD

**Issue by liujiada-star** [flutter/flutter#69655]
Textflied was copied and pasted on version 1.22, which broke or jammed directly。

This problem also exists in version 1.23 of flutter. I hope to give a solution

**Comment by liujiada-star** [comment]
iOS14

**Comment by pedromassangocode** [comment]
Hi @liujiada-star 
Did you closed this by mistake?

If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you
