### ISSUE TITLE
TextField Crash

### ISSUE THREAD

**Issue by liujiada-star** [flutter/flutter#69656]
For Flutter 1.22 version，TextField was copied and pasted on version iOS14, which broke or jammed directly。

This problem also exists in version 1.23 of flutter. I hope to give a solution

**Comment by pedromassangocode** [comment]
Hi @liujiada-star 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by mapleslong** [comment]
I had same problem on iOS14.1  、flutter SDK 1.22.3 
it also happened in flutter SDK1.20.3  .
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.3 at /Applications/flutter
    • Framework revision 8874f21e79 (9 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Applications/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

**Comment by tion126** [comment]
i have same problem, flutter run & build will crash on ios 14 only, but it works fine when i run in xcode directly.

**Comment by pedromassangocode** [comment]
Hi @mapleslong @tion126 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by tion126** [comment]
> Hi @mapleslong @tion126
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you

i solved this by use flutter create regenerate the project. I think it's the Xcode project configuration problem

**Comment by tion126** [comment]
> Hi @mapleslong @tion126
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you



> For Flutter 1.22 version，TextField was copied and pasted on version iOS14, which broke or jammed directly。
> 
> This problem also exists in version 1.23 of flutter. I hope to give a solution

You can try to regenerate the project

**Comment by tenutos** [comment]
In iOS14.1, a long press on the textField will cause the program to terminate directly. The branch has been switched from dev to beta and then to stable. This problem still cannot be solved. Now, the built ipa package will be directly rejected by the Apple review team for this reason;

This is a headache and I hope it can be resolved.

**Comment by mapleslong** [comment]
> You can try to regenerate the project

I tried it and it worked , Thanks  

But which configuration caused the problem, after the upgrade, is it a compatibility problem or what needs to be found, otherwise more developers will encounter this problem

**Comment by tion126** [comment]
> > You can try to regenerate the project
> 
> I tried it and it worked , Thanks
> 
> But which configuration caused the problem, after the upgrade, is it a compatibility problem or what needs to be found, otherwise more developers will encounter this problem
中文项目名的原因吧  外国人遇不到的

**Comment by eerbee** [comment]
i have same problem on ipad with IOS 12.4.8 when long press or double tap on textformfield suddenly show grey screen.
im using flutter Channel stable, 1.22.4

**Comment by eerbee** [comment]
> i have same problem on ipad with IOS 12.4.8 when long press or double tap on textformfield suddenly show grey screen.
> im using flutter Channel stable, 1.22.4

fix on https://github.com/flutter/flutter/issues/70767
