### ISSUE TITLE
E/flutter (20081): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(72)] Failed to setup Skia Gr context.

### ISSUE THREAD

**Issue by hiddenMonster** [flutter/flutter#69660]
Hi developers, 
I still having problems since the latest update of Android Studio version 4.1ed in particular when I test the apps in the emulator, in the attached example I have reported your codebase as an example that does not work when I switch from foreground mode to background and the other way around.
I hope you can resolve this, thanks and good luck

[backtrace.txt](https://github.com/flutter/flutter/files/5480292/backtrace.txt)

**Comment by pedromassangocode** [comment]
Hi @hiddenMonster 
I see there's an open issue (https://github.com/flutter/flutter/issues/40284) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
