### ISSUE TITLE
flutter run --release my app not work

### ISSUE THREAD

**Issue by lmr520** [flutter/flutter#69661]
```
Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.1 
    • Framework revision f30b7f4db9 (4 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/lmr/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)


bug: my app debug is ok,but release not work it stop first page,like all plugins not depended



log:I/flutter (24286): didPush route: ModalRoute(RouteSettings("/", null), animation: <optimized out>#1a1ab(⏭ 1.000; paused; for TransitionRoute(/))),previousRoute:null
E/flutter (24286): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (24286): 
```

**Comment by darshankawar** [comment]
@lmr520 
Please provide a complete minimal reproducible code sample that shows the issue along with `pubspec.yaml`.

**Comment by lmr520** [comment]
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: #多语言
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  common_utils: ^1.2.1
  cupertino_icons: ^0.1.3
  amap_location_fluttify: ^0.2.7+d2eb645
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  sqflite: ^1.3.0
  dio: ^3.0.9
  flutter_screenutil: ^1.0.2
  fluro: ^1.6.3
  fluttertoast: ^3.1.3
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  permission_handler: ^5.0.1
  path_provider: ^1.6.18
  extended_image: ^0.7.1
  get_it: ^3.0.3
  audioplayers: ^0.15.1
  flutter_easyrefresh: ^2.0.8
  cached_network_image: ^2.0.0
  extended_text: ^0.6.6
  loading_more_list: ^1.0.4
  webview_flutter: ^0.3.9+1
  marquee_flutter: ^0.1.2
  protobuf: ^1.0.0
  date_format: ^1.0.8
  event_bus: ^1.1.0
  loading_dialog: ^0.0.1+1 #latest version
  flutter_slidable: ^0.5.4
  flutter_downloader: ^1.4.0
  flutter_swiper : ^1.1.6
  qr_code_flutter_plugin: # 0.5.7+1
    path: plugin/qr_code_flutter_plugin
  photo: ^0.4.8       #相册多图选择  
  flutter_spinkit: ^4.1.2
  image_picker: ^0.6.3+1  #相机拍照，单图选择
  image_gallery_saver: '^1.6.0' #保存到相册
  file_picker: ^2.0.11 #文件选择
  open_file: ^3.0.3 #打开文件
  flutter_plugin_record: ^0.2.5
  flutter_sound: any
  #音频处理
  socket_io: ^0.9.4
  socket_io_client: ^0.9.11
  fixnum: ^0.10.9
  connectivity: ^0.4.9+5
  pbconv: ^0.5.9
    # 图片手势 https://pub.dev/packages/photo_view
  photo_view: 0.9.2
  # 消息订阅
  flutter_time_axis:
     git: https://github.com/luhenchang/flutter_time_axis.git
  gzx_dropdown_menu: ^2.1.0
  w_popup_menu: ^0.3.1
  #通知
  flutter_local_notifications: ^2.0.0
  #桌面通知徽标
  flutter_app_badger: ^1.1.2
  #徽标气泡
  flutter_qq_bubble: ^1.0.2
  badges: ^1.1.3
  #微亮 骨架屏
  shimmer: ^1.1.1
  #评分
  flutter_rating_bar: ^3.0.0
  #获取通讯录
  easy_contact_picker: ^0.0.2
  #可以滚动到指定item
  scrollable_positioned_list: ^0.1.7
  # 拨打电话 浏览器
  url_launcher: ^5.5.2
  # 选择器
  flutter_picker: ^1.1.5
  #全局content
  one_context: ^0.4.0
  #验证码
  flutter_verification_box: 1.0.1
  #json
  json_annotation: ^2.4.0
  #edge_insert
  edge_insert_observer: ^0.0.2
   #toast
  flutter_styled_toast: ^1.4.0+1
dev_dependencies:
  json_serializable: ^3.0.0


only android  has this problem    


then  i update   com.android.tools.build:gradle:4.0.0 to 3.5.4  that work  ok

**Comment by darshankawar** [comment]
@lmr520 
Seems your issue is resolved. I am going ahead and closing this. If you disagree or see similar issue again, write in comments and I'll reopen.
Thanks.
