### ISSUE TITLE
MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#69663]
After flutter run --release, an error is reported on the real machine
![image](https://user-images.githubusercontent.com/24307960/97971301-c856df80-1dfd-11eb-9d80-dc2a7493545b.png)

**Comment by mulieli** [comment]
After flutter run --release, an error is reported on the real machine

**Comment by darshankawar** [comment]
@mulieli 
Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by mulieli** [comment]
> @mulieli
> Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
> Thanks.

我之前用的
build.gradle 中的dependencies 中的gradle版本是 
com.android.tools.build:gradle:4.0.1
wrapper里的gradle的版本是
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

后来我改回到
com.android.tools.build:gradle:3.5.0
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
可以正常发布release包

**Comment by mulieli** [comment]
> @mulieli
> Please provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
> Thanks.

我之前用的
build.gradle 中的dependencies 中的gradle版本是 
com.android.tools.build:gradle:4.0.1
wrapper里的gradle的版本是
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

后来我改回到
com.android.tools.build:gradle:3.5.0
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
可以正常发布release包
