### ISSUE TITLE
Add `include/*` files to Flutter SDK

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#69677]
The standalone Dart SDK has files in `include/*`, however these are missing in the Dart SDK release inside Flutter.

See https://github.com/flutter/flutter/issues/63255#issuecomment-721182337

**Comment by Dolaned** [comment]
thank you

**Comment by dcharkes** [comment]
From what I can see the Dart SDK is included here:

```gn
group("flutter") {
  # ...

    if (build_engine_artifacts) {
      public_deps += [
        "//flutter/flutter_frontend_server:frontend_server",
        "//third_party/dart:create_sdk",
      ]

  # ...
}
```

https://github.com/flutter/engine/blob/a9f332c0427d9475b8df4f44794fc2bbe4691ab4/BUILD.gn#L63

It depends on `//dart:create_sdk`, which depends on `//dart/sdk:create_sdk`, which depends on `//dart/sdk:create_common_sdk`, which depends on `//dart/sdk/copy_headers` which copies the headers.

```gn
# This rule copies header files to include/
copy("copy_headers") {
  visibility = [ ":create_common_sdk" ]
  sources = [
    "../runtime/include/dart_api.h",
    "../runtime/include/dart_api_dl.c",
    "../runtime/include/dart_api_dl.h",
    "../runtime/include/dart_native_api.h",
    "../runtime/include/dart_tools_api.h",
    "../runtime/include/dart_version.h",
    "../runtime/include/internal/dart_api_dl_impl.h",
  ]

  # Some magic to recover the folder structure inside the include folder.
  outputs = [ "$root_out_dir/dart-sdk/include/{{source_root_relative_dir}}/../../{{source_file_part}}" ]
}
```

https://github.com/dart-lang/sdk/blob/520165383eed4dd7c65d0934845d5465fc3f9838/sdk/BUILD.gn#L713-L728

The actual Flutter release folder contents might not be directly created by GN, this requires some more digging.

**Comment by dcharkes** [comment]
@Dolaned in the latest downloaded zip they are in `flutter/bin/cache/dart-sdk` for me, that is where the Dart SDK is nested.

**Comment by jaween** [comment]
I seem to be missing these files in the Dart SDK packaged with Flutter 2.0.3, so I download a standalone version of the Dart SDK from the releases page on GitHub. I'm using the finalizers feature.

Not sure if I can be of any help, but I have attached a list of files in both both Flutter's packaged Dart SDK and the standalone Dart SDK for Dart 2.12.2.

[flutter_2.0.3_dart_sdk_2.12.2.txt](https://github.com/flutter/flutter/files/6194021/flutter_2.0.3_dart_sdk_2.12.2.txt)
[standalone_dart_sdk_2.12.2.txt](https://github.com/flutter/flutter/files/6194026/standalone_dart_sdk_2.12.2.txt)

**Comment by chinmaygarde** [comment]
Closing this as stale.
