### ISSUE TITLE
[video_player] Play only a part of a video

### ISSUE THREAD

**Issue by Extazx2** [flutter/flutter#69673]
Hello

Is there a way to display only a part of a video through the video player ?
There is the `seekTo` but I don't see any "stop at" method

Is it possible ?

I'm using the player through chewie so the versions are the following :

Flutter : 1.20.0
chewie : 0.9.10
video_player : 0.10.12+5

**Comment by darshankawar** [comment]
@Extazx2 
Per `seekTo` document,

`Sets the video's current timestamp to be at moment. The next time the video is played it will resume from the given moment.`

You may play around this method to see if it serves your purpose.

**Comment by qbait** [comment]
@Extazx2 I would like to achieve the same thing, give `start` and `stop` and play this part in the loop. Have you found any solution?

@darshankawar `seekTo` was mentioned in the question.

**Comment by Extazx2** [comment]
@darshankawar as @qbait mentioned, I know of `seekTo`.

My intended goal is to have a loop like @qbait described

**Comment by darshankawar** [comment]
@Extazx2 
Does [this](https://github.com/flutter/flutter/issues/69064) open issue sound similar to yours ?

**Comment by Extazx2** [comment]
Yes it is.

**Comment by darshankawar** [comment]
@Extazx2 Thanks for confirming.
Closing this as duplicate. Please follow-up in linked issue for updates and any questions you may have.
If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by rekonvald** [comment]
Hi! Have the same issue. Have you found solution?
