### ISSUE TITLE
Flutter codelab sample mistake

### ISSUE THREAD

**Issue by johnwiese-ms** [flutter/flutter#69679]
In this step there is a mistake in the code https://codelabs.developers.google.com/codelabs/flutter/index.html#7
```
void _handleSubmitted(String text) {
  _textController.clear();
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      Duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );                                               // NEW
  setState(() {
    _messages.insert(0, message);
  });
  _focusNode.requestFocus();
  message.animationController.forward();           // NEW
}
```

Note that you you have "Duration" as the property name on AnimationController, when it should be "duration" lowercase 'd'

**Comment by markusaksli-nc** [comment]
Hi @johnwiese-ms 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/64104.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
