### ISSUE TITLE
Collapse a widget through a fade in (equal to the spotify playlist bar)

### ISSUE THREAD

**Issue by LuisCampos97** [flutter/flutter#69675]
Can someone help me implement a widget like the Spotify playlist bar? 
I have a SingleChildScrollView, and I have the Not Collapsed widget, and when I pull it up, when the widget is no longer visible, Collapsed widget appears through a fade in. 
Thanks!

Not Collpased
![image](https://user-images.githubusercontent.com/33434500/97995468-7357a100-1dde-11eb-9793-2a509e2be5f9.png)

Collapsed
![image](https://user-images.githubusercontent.com/33434500/97995546-8bc7bb80-1dde-11eb-9b8c-312daa1890ff.png)

**Comment by sidrao2006** [comment]
Hey @LuisCampos97 ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please see https://flutter.dev/community for resources and asking queries doubts and assistance on personal code. You may get some help if you post it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=flutter) and if you need help with your code, please check https://www.reddit.com/r/flutterhelp/.

Thanks

**Comment by LuisCampos97** [comment]
Ok, sorry.
Thanks!
