### ISSUE TITLE
[local_auth] Change default text

### ISSUE THREAD

**Issue by callmejm** [flutter/flutter#69682]
## Use case
How can change the **Touch fingerprint sensor** , **Not recognized**, **Too many attempt , try again later** etc , all the default message under the fingerprint image 
![image](https://user-images.githubusercontent.com/6957533/98014638-de34c680-1e36-11eb-85c3-3bcc399e6cec.png)

## Proposal
Please add those wording to **AndroidAuthMessages** , so we can set the language we want

Similar from ios
https://github.com/flutter/flutter/issues/43507

**Comment by stuartmorgan** [comment]
Those messages come from the OS, not the plugin; I do not see any way to change them in the relevant Android API. I would expect them to be translated automatically.

@xster I know for iOS [manual steps](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle) are needed to indicate supported languages as applies to native UI; is there a similar process for Android?

**Comment by stuartmorgan** [comment]
@blasten do you know the answer to my question above?

**Comment by blasten** [comment]
yes - it's provided by the system. Heading/subheading can be customized as noted: https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo


You would need to change the language of the device.

**Comment by blasten** [comment]
closing as it's unfeasible
