### ISSUE TITLE
Provide better error messages about disabled insecure HTTP connections

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#69685]
**Context:**
https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android
https://medium.com/flutter-community/solving-the-new-https-requirements-in-flutter-7abe240fbf23

Can we update the error message to include the fix? Instead of just saying that HTTP is blocked, we could tell people to either a) replace the URL with an HTTPS connection or b) enable HTTP (with all the caveats)

This is the kind of friction point that we can easily mitigate.

**Comment by tvolkert** [comment]
@mehmetf can we fix this before the next stable cut?

**Comment by tvolkert** [comment]
FYI @timsneath

**Comment by mehmetf** [comment]
Possible things we can do:

- Include a link in the error message that explains all this such as: https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android. I think embedding all this information in the error message itself is likely too much. I can push this through.

- We can consider changing the Flutter Android embedding to add `10.0.2.2` to the list of allowed addresses. I would not want to do this because it would mean release apps are also allowed to connect to this address and that's not good.

- We could change the flutter tooling to add android:usesCleartextTraffic="true" automatically to debug AndroidManifest.xml so users don't run into issues while debugging. I am not sure how feasible it is but I have seen similar code changes to tooling for iOS 14 that required additional plist attributes for debugging. I don't have bandwidth to do this unfortunately.

**Comment by mehmetf** [comment]
I have opened a PR to update the main article. Right now, the #1 google hit when someone searches this error message + flutter is https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android. 

It is unlikely that we can provide a 2-3 sentence solution. It will be more confusing. For instance, in most cases, HTTPS is not feasible. What if I just want to debug something? What if I am trying to connect to my local server? Allowing all cleartext traffic has serious caveats that won't fit to an error message. For instance, Apple might reject your app.

I am all for lower friction but it doesn't feel like we can do much else here. If you have an exact error message in mind, happy to hear it :)

**Comment by timsneath** [comment]
I think a simple message that says something like "Change your app to use
the HTTPS protocol, or visit this page for other solutions:
https://blah.blah.blah" or similar will be just fine, honestly. Even if
it's the #1 search result, we should do everything we can to signpost
solutions. Does that make sense?

**Comment by mehmetf** [comment]
Upstream Dart CL open for this: https://dart-review.googlesource.com/c/sdk/+/171020

**Comment by mehmetf** [comment]
Yep. One alternative as I mentioned in the CL description is to let embedder customize the error message.

**Comment by tvolkert** [comment]
@aam this is fixed now, correct?  (and has rolled into the framework with https://github.com/flutter/flutter/pull/83119)

**Comment by aam** [comment]
Yes, the changes were rolled into the engine, so when [`--disallow-insecure-connections`](https://github.com/flutter/engine/blob/master/shell/common/switches.h#L188) flag is used the better error message will be given to the user/developer.
I am not sure whether anything needs to be changed in flutter framework to start using this flag though. Could not find any tests around this functionality in flutter.

**Comment by tvolkert** [comment]
@zanderso ^---

**Comment by tvolkert** [comment]
FYI, the fix was reverted in https://github.com/flutter/engine/pull/26371 (and will be re-applied)

**Comment by aam** [comment]
The fix did reland as https://github.com/flutter/engine/pull/26400, we still need to figure out next steps.

**Comment by zanderso** [comment]
By next steps do you mean figuring out how to expose this to internal and external tooling? /cc @xster for internal tooling, @jonahwilliams for external tooling.

**Comment by jonahwilliams** [comment]
Do we actually want to disallow insecure connections by default, or does this behavior only make sense in a stricter environment like g3? We can certainly expose the flag to allow users to turn it on, but I'm not sure how much use that would get unless there are folks asking for it.

**Comment by zanderso** [comment]
@jonahwilliams Maybe off by default with a tool flag to enable it for release builds?

**Comment by jonahwilliams** [comment]
But this is a runtime flag, it can only be provided when the tool launches the application. In order to support builds with this, we'd need to also teach the engine to read this value from a define in the snapshot.

**Comment by aam** [comment]
I'm not up to speed with all the work that @mehmetf did in this space, but looking at https://github.com/flutter/engine/pull/20218 it seems that intent was to use android/ios configuration options to determine whether insecure connections are allowed or not.

**Comment by jonahwilliams** [comment]
Ahh, if its configured via metadata in the android manifest we don't need to do anything in the tool as far as I can tell. We could add a flag to override the setting, but the user might just as easily change their manifest.

**Comment by aam** [comment]
> At the moment, the default value of the flag allows insecure connections to any domain. Internal tooling may override that default, but I don't have a pointer to that code handy.

external engine flag `disallow-insecure-connections` with default value is defined here https://github.com/flutter/engine/blob/b71a2fd8f50ecd66b7e65192ef3077a7d0d76f52/shell/common/switches.h#L192

flipped over from "disallow" to `may_insecurely_connect_to_all_domains` for internal use here:
https://github.com/flutter/engine/blob/b71a2fd8f50ecd66b7e65192ef3077a7d0d76f52/shell/common/switches.cc#L261

**Comment by aam** [comment]
@tvolkert wrote

> the current status that insecure network connections are disabled with no way to enable them -- and that we want to allow app-level overrides by plumbing through platform-native configuration directives (such as [android:usesCleartextTraffic](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) for Android)?
>  ...the error messages have been improved...

@zanderso wrote

> Further platform specific plumbing is needed, yes. 

That's the current state of things.

**Comment by gmackall** [comment]
From Android triage: It looks like the error messages themselves have been fixed, which is what the original issue was about. 

At this point any follow up work for platform-specific plumbing should be filed as a separate issue. Please feel free to re-open if you disagree!
