### ISSUE TITLE
migrate Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. 

### ISSUE THREAD

**Issue by gaurav1903** [flutter/flutter#69690]
Your Flutter application is created using an older version of the Androidembedding. It's being deprecated in favor of Android embedding v2. 
I am running into this error from last 3 apps.All are malfunctioning even after fixing this issue.I want to fix this properly for once. Also why does this error occur?

**Comment by markusaksli-nc** [comment]
Hi @gaurav1903 
Android embeddign v2 is summarized [here](https://flutter.dev/go/android-migration-summary). Have you followed the [migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)? What malfunctions are present after following the guide?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
