### ISSUE TITLE
Framework tests fail when using DDC on H/H/H bots due to applyPaint during preroll

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#69698]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864987986065765328/+/steps/flutter_test_web_tests/0/stdout

**Comment by pedromassangocode** [comment]
@ferhatb does https://github.com/flutter/engine/pull/22273 fixes this issue?

**Comment by ferhatb** [comment]
yes, fixed.
