### ISSUE TITLE
Increase timeout on Mac iOS Engine

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#69701]
The tree is currently closed on a timeout. I triggered a rebuild. Successful runs are in the 45-55 minute range with a 1hr timeout, which seems too short.

https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine

/cc @cbracken

**Comment by godofredoc** [comment]
Do we know where the extra 15 mins are being used:

![image](https://user-images.githubusercontent.com/54371434/98035340-33d48900-1dcd-11eb-8ddc-b38257610735.png)

**Comment by godofredoc** [comment]
There are several builds that are not running on a goma context:

![image](https://user-images.githubusercontent.com/54371434/98035603-9f1e5b00-1dcd-11eb-8251-b3666fa9439d.png)

**Comment by dnfield** [comment]
If we can shard these into separate builders, we should.

Otherwise, this builder needs a longer timeout. Copying here from chat: these do not use GOMA because GOMA does not support using Xcode's clang as a compiler.

**Comment by dnfield** [comment]
(and bitcode enabled builds have to use Xcode's clang)
