### ISSUE TITLE
Flutter does not install latest build on ios simulator.

### ISSUE THREAD

**Issue by safield** [flutter/flutter#69705]
I am am running an ios simulator. I am using "flutter build ios --debug" to build the app. I am then using "flutter install ios --debug" to install on the device.

The first install of the app works. But subsequent installs, do not reflect the changes. I change my dart code, then run the two commands above, and the app does not reflect the changes. I have to completely wipe the simulator (manually uninstalling doesn't work) to have the new app install with the correct changes.

Mac OS version: 10.15.7
Xcode Version: 12.1
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (5 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

I have attached the output of "flutter install ios --debug --verbose".
[install.txt](https://github.com/flutter/flutter/files/5483679/install.txt)

**Comment by nt4f04uNd** [comment]
Weird stuff, but why not to use flutter run

**Comment by safield** [comment]
> Weird stuff, but why not to use flutter run

Did not see that coming...

**Comment by stephenkite** [comment]
use flutter run

**Comment by darshankawar** [comment]
@safield 
Try above command and see if it works for you.

**Comment by nouveau-riche** [comment]
You can run this command 
flutter clean 
and then build again.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
