### ISSUE TITLE
flutter run: SIGUSR1 not always caught by Dart process

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6970]
Sometimes, when I have `flutter run` running, and I send a SIGUSR1 to the process, I see:

```
~/dev/flutter/bin/flutter: line 53: 14926 User defined signal 1   "$DART" "$SNAPSHOT_PATH" "$@"
```

cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@Hixie do you have a reproduction? If the signal is being delivered to the shell script this is likely a bug in our dart:io implementation.

**Comment by johnmccutchan** [comment]
also, this bug may be better filed against Dart and not Flutter.

**Comment by Hixie** [comment]
I have no idea how to reproduce this reliably, no. :-( I've seen it twice so far.

**Comment by Hixie** [comment]
I later figured out that this happens if you send SIGUSR1 before the hot reload stuff has hooked the signal. Maybe we should make sure we delete the pid file while we're not ready for the signal?

**Comment by zanderso** [comment]
We could address this partially by installing (a) signal handler(s) before we start launching an app, like here: https://github.com/flutter/flutter/blob/ad44b05ca40e58a29940986373394326db3bd127/packages/flutter_tools/lib/src/commands/run.dart#L562

But a race would still be possible if you are a very fast typer.
