### ISSUE TITLE
Google map and ListView making Its scroll buggy.

### ISSUE THREAD

**Issue by it-sam** [flutter/flutter#69729]
Google map and ListView makes list view scroll buggy.

On starting the app its working fine. But **after the change in app life cycle List view is not able to scroll properly.** 
As soon as we remove GoogleMap, it starts working fine.
This happens on debug and release mode with iOS Simulator and device. It is working fine with Android fleet.
Thanks

[Video link](https://drive.google.com/file/d/1IFrVfFViSd0lD5_d25ZYqKSQkhh0BotF/view?usp=sharing)
[Code zip](https://drive.google.com/file/d/1LFY2_1VfpYyM_A89LHYNFdmPNRpuhxnU/view?usp=sharing)

>  flutter doctor -v
> [✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale en-AU)
>     • Flutter version 1.22.3 at /Users/<MyName>/flutter/flutter
>     • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
>     • Engine revision a1440ca392
>     • Dart version 2.10.3
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
>     • Android SDK at /Users/<MyName>/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0
>     • ANDROID_HOME = /Users/<MyName>/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.1, Build version 12A7403
>     • CocoaPods version 1.10.0
> 
> [!] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.50.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (2 available)
>     • iPhone 8 (mobile)      • 42E6453F-E54B-47D1-840F-421BE8DAE3EC • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
>     • iPhone 12 Pro (mobile) • C35FF92B-ED29-4800-AE72-3954C77D5680 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
>     ! Error: iPhone 7 Gold is not connected. Xcode will continue when iPhone 7 Gold is connected. (code -13)
> 
> ! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Issue replicable on latest stable and only seems to be affecting iOS. On Android, same code works well without any issues.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

**Comment by shreymahendru** [comment]
@darshankawar any update on this? This is causing us issues in production.

**Comment by wreppun** [comment]
Just wanted to add a note that #70069 tracked down the engine commit which broke this behavior.

(flutter/engine#20708)

**Comment by darshankawar** [comment]
Verified this on latest master and stable on physical iOS device + simulator using the code sample provided in issue description and observed that the noted behavior isn't occuring anymore.


https://user-images.githubusercontent.com/67046386/117977182-2edd2d00-b34e-11eb-87b3-3043a22adca0.MP4

@it-sam 
Can you confirm the same from your end ? 

<details>
<summary>stable and master flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.3.0-2.0.pre.139, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.139 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e621ebfb34 (3 hours ago), 2021-05-11 23:29:03 -0400
    • Engine revision 8e332453b8
    • Dart version 2.14.0 (build
      2.14.0-edge.b99466d472e369990eb22de332cb5b2967b3ea00)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

</details>
