### ISSUE TITLE
Improve console log handling

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6972]
Right now, we're being too aggressively in our filtering of Android logs, and we're being too permissive in iOS simulators.  Though we have different logging systems on Android, iOS simulators, and iOS devices, we should try to unify the logic around how to filter what we show to the user in the console.

**Comment by tvolkert** [comment]
@cbracken is overhauling a bunch of our log handling code.  Chris, should this be duped against another issue or closed, or is there actionable work covered here?

**Comment by Hixie** [comment]
I'm going to close this because it's vague. If there's specific changes we should make, we can open specific bugs.
