### ISSUE TITLE
Real machine can't run in VSCode when I run Flutter

### ISSUE THREAD

**Issue by harleyGit** [flutter/flutter#69737]
My Xcode is upgraded to Xcode12, but my flutter project can run in Xcode, but it cannot run in vscode. When vscode is running on a real device, the black screen is stuck after the startup page pops up. Please help me, thanks.

Console print:
```bash
**event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in 太阳系...}
event sent after app closed: {id: 0, progressId: null, finished: true}
Launching lib/main.dart on TMPhone in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: BFTR54X3SG
Xcode build done.** 


hen the pop-up window keeps loading the prompt:

**Syncing files to device TMPhone...**
```

**Comment by TahaTesser** [comment]
Hi @harleyGit 
Are you experiencing it from the terminal as well? 
Can you please provide your `flutter doctor -v` your `flutter run --verbose`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by harleyGit** [comment]
> Hi @harleyGit
> Are you experiencing it from the terminal as well?
> Can you please provide your `flutter doctor -v` your `flutter run --verbose`
> Thank you

I solve this proplem,because this problem is I upgrade Xcode, thank you

**Comment by harleyGit** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

I solve this problem, thank you

**Comment by Bonchoisland12** [comment]
Why I can't access to my account

**Comment by Bonchoisland12** [comment]
Thank you for your kindness and fixed it right away

**Comment by harleyGit** [comment]
> Why I can't access to my account

what do you want to access account
