### ISSUE TITLE
Flutter engine iOS platform code for SystemNavigator.pop doesn't work in add-to-app scenario when using a UINavigationController to manage the FlutterViewController

### ISSUE THREAD

**Issue by sianxz** [flutter/flutter#69738]
Scenario and fix is similar to https://github.com/flutter/flutter/issues/67103. We assume that the root VC is a UINavigationController in https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L218. 

I'll make a PR when I get the time.

**Comment by TahaTesser** [comment]
Hi @sianxz 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
