### ISSUE TITLE
bug inTextField when LengthLimitingTextInputFormatter

### ISSUE THREAD

**Issue by hu70258tao** [flutter/flutter#69743]
如果输入框,限制了文本长度为n,当在软键盘上输入m个字符后,想要删除输入框的内容时,前m-n次点击删除键不会删除输入框内容,导致客户认为APP有问题.

**Comment by xu-baolin** [comment]
Fixed via #67828 please get the latest code.
主干已经修复了 请更新你的flutter版本哈

**Comment by darshankawar** [comment]
Translation : If the input box, the text length is limited to n, when you want to delete the content of the input box after inputting m characters on the soft keyboard, the first mn clicks of the delete key will not delete the content of the input box, causing the customer to think that there is a problem with the APP .

**Comment by darshankawar** [comment]
@hu70258tao 
Please switch and upgrade to latest master and try again to see the fix as mentioned by @xu-baolin .

**Comment by AlexV525** [comment]
Closing, since it has been published in Flutter 1.22.3 stable. Feel free to report more information if it doesn't work as expected.
