### ISSUE TITLE
fatal: bad config line 1 in file .git/config Building flutter tool... Running pub upgrade...

### ISSUE THREAD

**Issue by vipuluthaiah** [flutter/flutter#69746]
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...

$ flutter create matcher
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Invalid project name: 'matcher' - this will conflict with Flutter package dependencies.

$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "windows_x64"

lcome@DESKTOP-87FIKKA MINGW64 /e/flutter loaction
$ flutter doctor
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):
Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard out:
Standard error: fatal: bad config line 1 in file .git/config

Returning 1970-01-01 05:30:00.000 instead.
[√] Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by sidrao2006** [comment]
Hey @vipuluthaiah , according to the logs, you are not on any channel.

Could you please try `flutter channel stable` (or beta, dev or master) and then try `flutter upgrade`

Thanks!

**Comment by vipuluthaiah** [comment]
@sidrao2006 shall i delete my flutter sdk and re install?

**Comment by sidrao2006** [comment]
@vipuluthaiah , as of now, I don't think that's required. Please the running the above mentioned commands.
Thanks!

**Comment by darshankawar** [comment]
@vipuluthaiah 
Usually you'll get this error `fatal: bad config line 1 in file .git/config` if you haven't initialized `git` using `git init` command.
Check if you have cloned `flutter sdk` properly by following the instructions in the document.

**Comment by vipuluthaiah** [comment]
After git init
I tried
flutter create myapp
fatal: bad config line 1 in file .git/config Building flutter tool... Running pub upgrade

**Comment by darshankawar** [comment]
@vipuluthaiah 
You can't directly run `flutter create` command after git init.  Do you have the Flutter sdk installed already ? Have you run `flutter doctor -v` and switched to a valid Flutter version ?

**Comment by vipuluthaiah** [comment]
@sidrao2006 
flutter channel stable
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Running pub upgrade...
^C^CTerminate batch job (Y/N)? y

**Comment by darshankawar** [comment]
@vipuluthaiah 
Can you show where have you installed Flutter sdk ? Are you on Windows ?
Do you see below folders inside `flutter` folder when you installed it ?

<img width="308" alt="Screenshot 2020-11-04 at 6 05 18 PM" src="https://user-images.githubusercontent.com/67046386/98112517-58615b80-1ec8-11eb-9911-85cd89b92ccc.png">

If so, from `flutter` folder path, can you run `git checkout stable` and see what you get ?

**Comment by vipuluthaiah** [comment]
Been using flutter 6 months 
From yesterday i am.facing this issue

**Comment by darshankawar** [comment]
@vipuluthaiah 
Can you provide `.git/config` ?

**Comment by vipuluthaiah** [comment]
$ flutter channel stable
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Switching to flutter channel 'stable'...
git: fatal: bad config line 1 in file .git/config
Switching channels failed with error code 128.

**Comment by vipuluthaiah** [comment]
@darshankawar 
\$ flutter doctor -v
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard out:
Standard error: fatal: bad config line 1 in file .git/config

Returning 1970-01-01 05:30:00.000 instead.
[√] Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 0.0.0-unknown at D:\Flutter\flutter
    • Framework revision  (), 1970-01-01 05:30:00.000
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\welcome\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\welcome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by vipuluthaiah** [comment]
@darshankawar 
path:

‪C:\Users\welcome\.gitconfig
[user]
	name = vipuluthaiah
	email = kechamadavipul@gmail.com

**Comment by vipuluthaiah** [comment]
closing this issue 
i resolved by 
deleting my flutter sdk and installing latest version
