### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally "JSON text did not start with array or object and option to allow fragments not set." 

### ISSUE THREAD

**Issue by GhagSagar23** [flutter/flutter#69751]
## Command
```
flutter build ios --flavor Production -t lib/main_prod.dart --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode_11.6.app/Contents/Developer/usr/bin/xcodebuild -list

2020-11-04 13:56:24.289 xcodebuild[44915:385831] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /Users/sunflower/Documents/Sagar/Work/Dispatcher App/dispatcher_app_owner/Owner_Flutter/ios/Runner.xcodeproj
  Command: /usr/bin/xcodebuild -list
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:389:50)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:108:78)
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:83:43)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale en-IN)
    • Flutter version 1.17.5 at /Users/sunflower/Documents/Development/Tools/flutter_dev
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sunflower/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode_11.6.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
clipboard_manager-0.0.4
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_crashlytics-0.1.4+1
firebase_messaging-6.0.16
firebase_performance-0.3.2
geocoder-0.2.1
geolocator-5.3.2+2
google_api_availability-2.0.4
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
permission_handler-5.0.1+1
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3

**Comment by darshankawar** [comment]
@GhagSagar23 
Can you upgrade to latest stable and try again to see if it works ?
Thanks.

**Comment by GhagSagar23** [comment]
Thanks for the reply @darshankawar.
I got it solved by updating the path for flutter in the VSCode Dart Settings.
1. Open VSCode and press "Cmd" + ",".
2. Search for `Dart SDK Path`.
3. Click on **"Edit in settings.json"**
4. Update the value as you flutter SDK path for key **"dart.flutterSdkPath"**.

**Comment by darshankawar** [comment]
@GhagSagar23 Glad to know your issue is resolved.
Closing this.
