### ISSUE TITLE
iOS ,present StatefulWidget,just build Container

### ISSUE THREAD

**Issue by helidong** [flutter/flutter#69752]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/view.dart': Failed assertion: line 164 pos 12: '_size.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderView.performLayout (package:flutter/src/rendering/view.dart:164:12)
#3      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
#4      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
#5      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
#6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
...
The following RenderObject was being processed when the exception was fired: RenderView#e0df9 NEEDS-LAYOUT NEEDS-PAINT
...  debug mode enabled - ios
...  window size: Size(0.0, 0.0) (in physical pixels)
...  device pixel ratio: 1.0 (physical pixels per logical pixel)
...  configuration: Size(375.0, NaN) at 0.0x (in logical pixels)
RenderObject: RenderView#e0df9 NEEDS-LAYOUT NEEDS-PAINT
  debug mode enabled - ios
  window size: Size(0.0, 0.0) (in physical pixels)
  device pixel ratio: 1.0 (physical pixels per logical pixel)
  configuration: Size(375.0, NaN) at 0.0x (in logical pixels)
...  child: RenderSemanticsAnnotations#34a36 NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: <none>
...    constraints: BoxConstraints(w=375.0, h=666.7)
...    size: Size(375.0, 666.7)
...    child: RenderSemanticsAnnotations#337aa NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=375.0, h=666.7)
...      size: Size(375.0, 666.7)
...      child: RenderCustomPaint#54b55 NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=375.0, h=666.7)
...        size: Size(375.0, 666.7)
...        child: _RenderTheatre#a41c9 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=375.0, h=666.7)
...          size: Size(375.0, 666.7)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by darshankawar** [comment]
@helidong 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
