### ISSUE TITLE
flutter engine    gclient sync   error 

### ISSUE THREAD

**Issue by ylrs** [flutter/flutter#69764]
`
________ running 'cipd ensure -log-level error -root /Users/zhulongfei/Documents/Flutter/engine -ensure-file /var/folders/pr/s351rqx91ss6pq24ph_566fh0000gn/T/tmpr_7q3b82.ensure' in '.'
Errors:
  failed to resolve fuchsia/third_party/clang/mac-amd64@git_revision:7e9747b50bcb1be28d4a3236571e8050835497a6 (line 4): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve gn/gn/mac-amd64@git_revision:1e3fd10c5df6b704fc764ee388149e4f32862823 (line 7): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/embedding_bundle@last_updated:2020-05-20T01:36:16-0700 (line 16): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/google-java-format@version:1.7-1 (line 19): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/ndk/mac-amd64@version:r21.0.6113669 (line 22): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/sdk/build-tools/mac-amd64@version:30.0.1 (line 25): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/sdk/platform-tools/mac-amd64@version:30.0.4 (line 28): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve flutter/android/sdk/platforms@version:30r3 (line 31): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
  failed to resolve dart/dart-sdk/mac-amd64@version:2.10.0-79.0.dev (line 37): prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 172.217.160.84:443: i/o timeout
Error: Command 'cipd ensure -log-level error -root /Users/zhulongfei/Documents/Flutter/engine -ensure-file /var/folders/pr/s351rqx91ss6pq24ph_566fh0000gn/T/tmpr_7q3b82.ensure' returned non-zero exit status 1
`

**Comment by ylrs** [comment]
why?

**Comment by TahaTesser** [comment]
Hi @ylrs 
Based on the logs, looks some sort of connectivity issue, make you've stable internet,  update` src/flutter` repo, make sure there is no firewall or protected network blocking your network or any VPN

**Comment by ylrs** [comment]
Can not access of ”https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion“ ，other can

**Comment by ylrs** [comment]
![image](https://user-images.githubusercontent.com/3962127/98193094-57c3d600-1f57-11eb-86c2-34090b455937.png)

**Comment by ylrs** [comment]
![Uploading image.png…]()

**Comment by ylrs** [comment]
![image](https://user-images.githubusercontent.com/3962127/98193262-b5582280-1f57-11eb-9502-8e4846b03679.png)

**Comment by ylrs** [comment]
How should I do ?

**Comment by TahaTesser** [comment]
Hi @ylrs 
Weirdly I cannot access it either, can you link the documentation you following to execute these commands?  So I can reproduce it exactly 
Thank you

**Comment by ylrs** [comment]
@TahaTesser thank you very much, By configuring hosts, it seems to be resolved

**Comment by AsteriskZuo** [comment]
log content : post https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion, so, you maybe use tool postman simulate it.
