### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\user\Desktop\flutter\workshop0\android\app\src\main\res\mipmap-mdpi\ic_launcher.png', OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by AzzaHadded** [flutter/flutter#69767]

**Comment by TahaTesser** [comment]
Hi @AzzaHadded 
Your issue is missing necessary details from the crash report, look at this https://github.com/flutter/flutter/issues/69762
Please file a new issue and exactly copy generated crash report
Thank you
