### ISSUE TITLE
Allow different base href in index.html for flutter web app for build

### ISSUE THREAD

**Issue by sturmf** [flutter/flutter#69760]
## Use case

If I want to release my flutter web app I run `flutter build web`. Unfortunately I then need to deploy my app to a non root URL e.g. http://server.org/myapp/ and therefore I have to manually correct the base href in the index.html
I would like to set the base href e.g. in the build command something like this "flutter build web -Dhref=/myapp/ or similar.

Of course I can always post process the index.html with sed, but this is a litle bit less integrated.

If I just edit the index.html file directly then the debug use case does not work anymore.

## Proposal
Allow to set the base href during build time.

If something like this is possible already, I probably would have expected to find the documentation here: https://flutter.dev/docs/deployment/web

**Comment by atgnatus** [comment]
Angular has this feature:  ng build --base-href.   https://angular.io/cli/build   This is handy for deploying files to a CDN

**Comment by clebersa** [comment]
Hi @sturmf ,

As far as I understood, you are changing the base URL after you compile the project. Am I right? In that case, you should change the base URL of your Flutter web app by setting it in the `index.html` file in the `web` folder before you compile it:
```html
<base href="/">
```
As the comment in the file states, the base URL should start and end with `/`.

This way, all resources used in your app will have the right base URL, making your app work correctly and preventing 404 errors.
I hope this is useful for your or others who end up here.

**Comment by technolion** [comment]
> you should change the base URL of your Flutter web app by setting it in the index.html file in the web folder 

I think this issue is about setting the `base href` of `index.html` dynamically when building for web. This would allow for a better continuous integration while developing. Especially if you want deploy builds from development branches into different webserver subdirectories.

**Comment by daraul** [comment]
Could try a workaround with sed:

`sed -i 's#<base href="/">#<base href="/your-path-here">#g' build/web/index.html`

**Comment by architsangal** [comment]
Here is a link which can be helpful - https://flutter.dev/docs/development/ui/navigation/url-strategies

Also, if you want to comment that that line out, comment it in `base_folder/web/index.html`.

And the use the command `flutter build web`.

**Comment by erikhuizinga** [comment]
Another option is to replace `<base href="/">` with `<base href="/your/app/path/">` in web/index.html. Note: that's not build/web/index.html, but the source web/index.html file!

Benefits that work well for me:

- It puts the base path in the source and therefore, if you want, under version control.
- `flutter run` respects the path and points the browser to `localhost:port/your/app/path".
- `flutter build web` copies the path into build/web/index.html.

**Comment by patniemeyer** [comment]
As mentioned above Flutter web supports changing the base tag and also appears to work in a relative fashion if you remove the base tag.

**Comment by danteCarvalho** [comment]
i removed the <base href="/"> and it seems to work anywhere

**Comment by balvinderz** [comment]
this issue can be closed now @jonahwilliams

**Comment by jonahwilliams** [comment]
cool!

**Comment by naufil12** [comment]
Error: The base href in "web/index.html" must be absolute (i.e. start with a "/"), but found: `<base href="$FLUTTER_BASE_HREF">`.
For example, to serve from the root use:

    <base href="/">

To serve from a subpath "foo" (i.e. http://localhost:8080/foo/ instead of http://localhost:8080/) use:

    <base href="/foo/">

For more information, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base. 
this is my error coming
