### ISSUE TITLE
Migrate AlertDialog from ButtonBar to OverflowBar

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#69779]
## Use case

The `ButtonBar` is a legacy Component, that was was part of the old Button Universe and should be replaced by the new, more elegant `OverflowBar`.

This issue is a discussion point regarding the breaking changes that need to be done to achieve this, as the `OverflowBar` has a slightly different API.

After that is done, a bottom Padding issue that was caused by the `BottomBar` can be fixed. This step will cause Golden Tests to fail. And needs to be handled respectively:
![image](https://user-images.githubusercontent.com/10547444/98140692-0586a480-1ec6-11eb-8b6e-3c99e32695d4.png)

## Proposal

`buttonPadding` is not supported by the OverflowBar. The equivalent would be `spacing`, but `buttonPadding` is a `EdgeInsetsGeometry` while `spacing` is a `double`
- Step 1: 
  - Add a new parameter called `actionsButtonSpacing` which will be converted to a `EdgeInsetsGeometry` so that it can be used by the ButtonBar.
  - Deprecate the `buttonPadding` property.
- Step 2:
  - Replace the ButtonBar with the new OverflowBar. This will make `buttonPadding` useless, so `buttonPadding` can be removed or stay without any functionality
- Step 3:
  - Fix the bottom padding issue which was caused by the weird architecture of the `ButtonBar`

Right now I don't really see a way to Integrate the OverflowBar by still having buttonPadding work.
Do you have any idea regarding this problem?

**Comment by lazylazyllama** [comment]
@HansMuller Now that I had to close my old PR I think this is a good place to discuss my plans. :)

**Comment by HansMuller** [comment]
I believe the overall goal here is to replace AlertDialog's ButtonBar with an OverflowBar.

If AlertDialog.buttonPadding is specified we could wrap the OverflowBar with the button themes, passing buttonPadding along:
```dart
TextButtonTheme(
  padding: buttonPadding,
  child: ElevatedButtonTheme(
    padding: buttonPadding,
    child: OutlinedButtonTheme(
      padding: buttonPadding,
      child: OverflowBar(...)
    ),
  ),
)
```

**Comment by lazylazyllama** [comment]
This seems like a good solution to keep backwards compatibility.

But i still would prefer to move over to the new `spacing` property and deprecate the `buttonPadding` in the long term, as I would consider this as a much cleaner solution. But with this addition `buttonPadding` could still work simultaneous to the new operator. That's a good thing.

**Comment by lazylazyllama** [comment]
I'm sorry, I tried your code, but it does not work.
The code you posted itself is not working in general, so I think what you meant is this:

```dart
TextButtonTheme(
  data: TextButtonThemeData(
    style: TextButton.styleFrom(
      padding: buttonPadding,
    ),
  ),
  child: ElevatedButtonTheme(
    data: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        padding: buttonPadding,
      ),
    ),
    child: OutlinedButtonTheme(
      data: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          padding: buttonPadding,
        ),
      ),
      child: OverflowBar(...)
    ),
  ),
),
```

I put `buttonPadding` to `EdgeInsets.all(18)` and this is the result:
![98140692-0586a480-1ec6-11eb-8b6e-3c99e32695d4](https://user-images.githubusercontent.com/10547444/98234700-17695580-1f61-11eb-86ca-cef27510d629.png)

So this is not working.
`buttonPadding` was used to set the distance between two buttons, but with your new code it would be a padding within the button itself.

**Comment by HansMuller** [comment]
Sorry, that's what I get for just typing the code without trying it.

**Comment by lazylazyllama** [comment]
So should I create a PR introducing the new `actionsButtonSpacing` property then? Or do you have another idea?

**Comment by lazylazyllama** [comment]
@HansMuller
