### ISSUE TITLE
When I have IntelliJ IDEA Community Edition & Android Studio running "flutter doctor" gives me errors

### ISSUE THREAD

**Issue by EthanDevelops** [flutter/flutter#69773]
I am on the newest version of flutter and android studio. And have the most up-to-date official Flutter And Dart plugins in Android Studio. I am running Windows 10, and have  IntelliJ IDEA Community Edition installed on my system.

Here is my output for 'flutter doctor':

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

I belive what is causing the issue is my installation of  IntelliJ IDEA Community Edition installation, as it and Android Studio are very similar. As shown in [this StackOverflow Post](https://stackoverflow.com/a/51861066/13475152)

Any fixes for this would be helpful! 
Thanks.

**Comment by StarTrooper08** [comment]
If you dont mind can I give you suggestion?
That may help you.

**Comment by pedromassangocode** [comment]
Hi @EthanDevelops 
Those are not errors but warnings. The difference is that warnings does not prevent you to use Flutter but error does. That said you can use Flutter and ignore those warnings.

This is caused by the new version of the Android Studio where they have changed the path of the plugins.

See https://github.com/flutter/flutter/issues/67986

**Comment by EthanDevelops** [comment]
Ok. Thanks! Are they going to fix Android Studio?

**Comment by pedromassangocode** [comment]
Hi @EthanDevelops 
Yes, I remember seeing a PR to fix this but can't find it right now.
