### ISSUE TITLE
Update Flutter packages to a Dart 2.12 SDK constraint

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#69771]
Currently the Flutter packages (e.g. `flutter_test`) are using Dart 2.10 SDK lower constraints. After we rolled to Dart 2.12, this triggers pub warnings:
```
The package resolution is not fully migrated to null-safety.

package:flutter_test is not opted into null safety in its pubspec.yaml:
  ╷
5 │   sdk: ">=2.10.0-0.0.dev <3.0.0"
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵

Either downgrade your sdk constraint, or invoke dart/flutter with
`--no-sound-null-safety`.
```

Issue https://github.com/dart-lang/sdk/issues/44031 tracks resolving that for all Dart core packages. The present bug tracks resolving it for Flutter packages (both the ones shipped in the Flutter SDK, and the ones shipped on pub.dev).

**Comment by mit-mit** [comment]
Whomever ends up working on this, should probably coordinate with @jakemac53 and @natebosch who are working on this for Dart-owned packages (via https://github.com/dart-lang/sdk/issues/44031)

**Comment by blasten** [comment]
The constraint should be `">=2.12.0-0 <3.0.0"`

**Comment by pcsosinski** [comment]
who's owning the resolution of this?  @zanderso ?

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/69900
