### ISSUE TITLE
Roll pinned deps to Dart 2.12-enabled packages

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#69770]
Once we resolve https://github.com/dart-lang/sdk/issues/44031, we need to update the pinned Flutter package dependencies to pick up these Dart 2.12 enabled packages.

**Comment by zanderso** [comment]
@mit-mit the pinned packages are:
```
  'flutter_gallery_assets': '^0.2.0',
  'mockito': '4.1.1',  // Prevent mockito from upgrading to the source gen version.
  'vm_service_client': '0.2.6+2', // Final version before being marked deprecated.
  'flutter_template_images': '1.0.1', // Must always exactly match flutter_tools template.
  'shelf': '0.7.5',
  // Dart team owned nnbd deps
  'async': '2.5.0-nullsafety.2',
  'boolean_selector': '2.1.0-nullsafety.2',
  'characters': '1.1.0-nullsafety.4',
  'charcode': '1.2.0-nullsafety.2',
  'clock': '1.1.0-nullsafety.2',
  'collection': '1.15.0-nullsafety.4',
  'fake_async': '1.2.0-nullsafety.2',
  'js': '0.6.3-nullsafety.2',
  'matcher': '0.12.10-nullsafety.2',
  'meta': '1.3.0-nullsafety.5',
  'path': '1.8.0-nullsafety.2',
  'pedantic': '1.10.0-nullsafety.2',
  'pool': '1.5.0-nullsafety.2',
  'source_maps': '0.10.10-nullsafety.2',
  'source_map_stack_trace': '2.1.0-nullsafety.3',
  'source_span': '1.8.0-nullsafety.3',
  'stack_trace': '1.10.0-nullsafety.5',
  'stream_channel': '2.1.0-nullsafety.2',
  'string_scanner': '1.1.0-nullsafety.2',
  'term_glyph': '1.2.0-nullsafety.2',
  'test': '1.16.0-nullsafety.7',
  'test_api': '0.2.19-nullsafety.4',
  'test_core': '0.3.12-nullsafety.7',
  'typed_data': '1.3.0-nullsafety.4',
  'vector_math': '2.1.0-nullsafety.4',
  // Flutter team owned nnbd deps
  'platform': '3.0.0-nullsafety.3',
  'file': '6.0.0-nullsafety.3',
  'process': '4.0.0-nullsafety.3',
  'process_runner': '4.0.0-nullsafety.4',
  // https://github.com/dart-lang/build/issues/2772
  'build_runner_core': '5.2.0',
  'build_modules': '2.10.1',
  'path_provider': '1.6.14',
  'video_player': '2.0.0-nullsafety.1',
  'url_launcher': '6.0.0-nullsafety',
  'connectivity': '3.0.0-nullsafety',
  'device_info': '2.0.0-nullsafety',
```

Is this issue just for the `Dart team owned nnbd deps` and `Flutter team owned nnbd deps`, or are you saying that things like `mockito` and `build_runner_core` also need to have `nullsafety` versions?

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
Only the dependencies of flutter & flutter_test need to be updated. Other packages in the sdk like flutter_tools will not be able to migrate until there are null safe versions, but that does not block any of our users from migrating

**Comment by zanderso** [comment]
These deps of `package:flutter` still need an update

https://github.com/google/platform.dart/blob/master/pubspec.yaml
https://github.com/google/process.dart/blob/master/pubspec.yaml
https://github.com/google/file.dart/blob/master/packages/file/pubspec.yaml
https://github.com/dart-lang/stack_trace/blob/master/pubspec.yaml

@natebosch @jakemac53 for `package:stack_trace`

**Comment by zanderso** [comment]
`package:flutter_test` deps are a subset of `package:flutter` deps.

**Comment by natebosch** [comment]
I expect `stack_trace` to be published today. It was waiting for internal validation after some bug fixes.

**Comment by natebosch** [comment]
`stack_trace` is published.

**Comment by pcsosinski** [comment]
what's left to do here?

**Comment by jonahwilliams** [comment]
We need to land https://github.com/flutter/flutter/pull/69900

**Comment by jonahwilliams** [comment]
Done with https://github.com/flutter/flutter/pull/69900
