### ISSUE TITLE
[LUCI] Add devicelab_drone to led_tests presubmit

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#69778]
https://flutter-review.googlesource.com/c/recipes/+/8241 made changes to the devicelab_drone recipe that broke flutter/flutter presubmit.

My expectation was that the recipe was not in use yet. Including it in the LED presubmit builder will prevent future breakages.

**Comment by CaseyHillers** [comment]
the recipes-with-led cq job detected changes in the CL, and listed it as a recipe to invoke a test for. However, the `all tryjobs` step did not return a builder that uses the devicelab_drone recipe

**Comment by CaseyHillers** [comment]
Issue is that [commit_queue.cfg](https://cs.opensource.google/flutter/infra/+/master:/config/generated/flutter/luci/commit-queue.cfg) does not contain these builders.

Instead, they are invoked from [cr-buildbucket.cfg].

(https://cs.opensource.google/flutter/infra/+/master:config/generated/flutter/luci/cr-buildbucket.cfg).

@godofredoc @keyonghan do you know if its intentional that the recipe led_tests only tests the commit queue jobs instead of the ones from buildbucket?

**Comment by keyonghan** [comment]
IIRC We need to add the `add_cq` in the config to enable `led_tests` run.
https://devops-console-oss.corp.google.com/flutter/infra/+/master:config/framework_config.star;l=551

**Comment by godofredoc** [comment]
The add_cq property of the builders force them to get added to commit_queue.cfg. The builders are not added by default because we are not using LUCI CQ.

The led tests read commit_queue.cfg to determine the available builders for testing.

**Comment by CaseyHillers** [comment]
Thank you Godofredo and Keyong. This is fixed https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8864532880508866752?
