### ISSUE TITLE
Keyboard type doesnt change

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [flutter/flutter#69772]
I have two inputs, the first is a default text input, the second one is a number only input, so I use KeyboardType.number, the problem is that when I change focus the keyboard type doesnt change automatically

![video](https://user-images.githubusercontent.com/29608698/98122982-0e5c8380-1e90-11eb-93a0-89c203cef16e.gif)

**Comment by pedromassangocode** [comment]
Hi @diego-lipinski-de-castro 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by diego-lipinski-de-castro** [comment]
Hello, I went to create a reproducible code sample, but it just worked as expected, and then I went back to my app, and it worked as expected too, I dont know exactly what happened but it went away
