### ISSUE TITLE
Inconsistent test results for flutter/tests

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#69785]
Presubmits on https://github.com/flutter/tests/pull/61 show that one of the flutter/tests test is failing (this shouldn't be due to that PR as it's just a comment change).

While the customer_testing tasks on Flutter dashboard are all green (e.g https://ci.chromium.org/p/flutter/builders/prod/Mac%20customer_testing/610).

@dnfield suggests the failure showing on presubmit is real, so I'd expect the customer_testing task to be red.

Is it possible that we're not properly running the `flutter/tests` tests as part of the customer_testing tasks?

**Comment by godofredoc** [comment]
That test runs a script that passes/fails according to the exit code. This is the script:

https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/adhoc_validation/resources/customer_testing.sh

The test seems to be passing an skip pattern bin/cache/pkg/tests/registry/*.test is this expected?

I'd suggest to convert this adhoc script to a sharded test runner test to get it back to the flutter repo.

**Comment by amirh** [comment]
Seems like the `--skip-template` means just to skip `template.test` (https://github.com/flutter/flutter/blob/5034d57546ba904a88a122088b425cc55495b7c3/dev/customer_testing/run_tests.dart#L48).

The bin/cache/pkg/tests/registry/*.test should mean run all *.test files in that path...

**Comment by godofredoc** [comment]
From infra everything seems working as expected, we may need someone more familiar with the test itself to take a look.

**Comment by jason-simmons** [comment]
The run of the `flutter_svg` test in https://github.com/flutter/tests/pull/61 is checking out an older commit of the `flutter_svg` repository.

Try rebasing the PR to the latest flutter/tests head (including https://github.com/flutter/tests/commit/b6eaea2ad77d8f2dc5d224e0841714c2024539ac)

**Comment by godofredoc** [comment]
Thanks @jason-simmons reassigning to @amirh

**Comment by amirh** [comment]
@jason-simmons that was it 🤦  thanks!
