### ISSUE TITLE
Ability to turn off Android deeplink 

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#69786]
b/172394233

We recently added android deeplink support https://github.com/flutter/engine/pull/21275
However, this become a breaking change for apps that handles deeplink by writing their own plugin.

We should have a way to turn it on or off.

**Comment by chunhtai** [comment]
@johnpryan Regarding this, do you think we should turn it on by default?

@gaaclarke I remember we can turn it off for iOS by writing a plugin that return yes for openURL. I am thinking can we have a more straight forward way of doing this? For example add meta tag in info.Plist for iOS or AndroidManifest.xml to toggle the functionality directly?

**Comment by johnpryan** [comment]
Is it possible support deep linking with Navigator 2 *unless* a plugin is being used to add deep linking?

**Comment by gaaclarke** [comment]
![deeplinkingios](https://user-images.githubusercontent.com/30870216/98299992-7cc34380-1f6d-11eb-8aa3-bc0adb50a111.png)

Here's a diagram of the current logic.  We do have a straightforward way which is to not to support a certain protocol in the Info.plist.

**Comment by chunhtai** [comment]
Talked with @gaaclarke , we agree we should have a unify way to opt in to the deeplink

This will be the workflow.
In order to opt for deeplinking in Android
you need to add intent filter and a meta flag `forward_url_to_flutter` in AndroidManifest.xml

In order to opt for deeplinking in iOS
you need to add scheme and a meta flag `ForwardURLToFlutter` in info.Plist

@johnpryan  does this sound good to you?

@gaaclarke  There is one more thing we need to figure out. What happen if developer opt for deeplinking in iOS but also write plugin to return yes?

**Comment by johnpryan** [comment]
SGTM

**Comment by xster** [comment]
May or may not be the right place to address this, but @matthew-carroll pointed out an interesting potential difference between the Android and iOS implementation. https://github.com/flutter/engine/pull/21275 seems to have used the initialRoute mechanism and https://github.com/flutter/engine/pull/21336 seems to have used the push mechanism. Might have been discussed before. Is that intentional?

**Comment by chunhtai** [comment]
If user deeplink into iOS app, the app will launch first without any URL. After a moment later, it will then receive the openURL request with the URL. By the point the app receives the openURL the app may have already been running, and the set initial route may be too late. That is why we decided to do a push mechanism in iOS.

**Comment by xster** [comment]
Understood. Thanks for clarifying. I imagine if both uses navigator 2, the navigation stack in both cases will be the same? The only difference is that the root/initial route in iOS could be visible momentarily and may have an animation when the push comes in?

**Comment by chunhtai** [comment]
yes, that is correct.

**Comment by matthew-carroll** [comment]
Is there a guide that demonstrates how to utilize deep links on iOS and Android?

**Comment by chunhtai** [comment]
We are in the middle of writing one. cc @johnpryan
