### ISSUE TITLE
Setup XCUITest to test IAP flow in the in_app_purchase plugin

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#69796]
We should be able to follow https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode?language=objc to set up a local environment for the in_app_purchase example app on iOS.
Then with that set up, we should be able to follow https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#setting-up-xcuitests to set up automated UITests.

**Comment by cyanglaz** [comment]
cc @LHLL

**Comment by LHLL** [comment]
Two links are the same, is that intentional? @cyanglaz

**Comment by cyanglaz** [comment]
@LHLL oops my mistake, fixed.

**Comment by cyanglaz** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/79286
