### ISSUE TITLE
Popup menu isn't stateful

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#698]
The stocks demo app has a checkbox in its popup menu but you can never toggle it visibly.

**Comment by Hixie** [comment]
I worked around this in https://github.com/flutter/flutter/pull/718, but we should probably take a closer look and decide if that's sufficient or if we want a more "real" solution.

**Comment by abarth** [comment]
This looks roughly fixed now.  We now have a PopupMenuButton widget that manages showing the menu for you and a CheckedPopupMenuItem that manages the checkbox.  You can still reproject arbitrary widgets through the menu, so you can still technically encounter this issue, but that's now an esoteric usage and probably ok to require some more careful state management.
