### ISSUE TITLE
Upgrade CocoaPods gem version on builders

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#69808]
The version of CocoaPods on the mac builders is 1.8.4
```
Fetching cocoapods 1.8.4
Installing cocoapods 1.8.4
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864533259479547856/+/steps/Install_gems/0/steps/install_gems/0/stdout

Upgrade to version 1.9.3.

The tool will soon recommend a minimum of 1.9 https://github.com/flutter/flutter/issues/69807

**Comment by godofredoc** [comment]
Cocoapods is installed from here https://cs.opensource.google/flutter/flutter/+/master:dev/ci/mac/Gemfile which doesn't have any pins.

**Comment by jmagman** [comment]
That version is coming from the Gemfile.lock:
https://github.com/flutter/flutter/pull/69809/files#diff-f2773caa767840c5fae06c4f189e4bc26b6a78bf8c54a79fc21546db902b59b4L15
