### ISSUE TITLE
Web hot reload tests are flaky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69804]
These are failing on pre and post-submit. Add more logging and run in a loop locally to see what is broken.

**Comment by bernaferrari** [comment]
Hey @jonahwilliams! Glad to see this issue again (there are a few duplicates somewhere, like https://github.com/flutter/flutter/issues/67635). I have this issue with hot reload and hot restart every day. It is hard to reproduce and seems to happen at random times. However... There is a project where this fails every single time! Yes, you read right.

Could you try running this project? https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login
You don't need any key, just download and run. Then, try to change something simple, like the "sign up" text into anything, like "sign up!". Try to hot reload. It should get into an infinite loop.

**Comment by yjbanov** [comment]
Doesn't look like this is happening any more. If it happens again the new flake detection will file a bug.
