### ISSUE TITLE
How to handle a binary data from REST request as arraybuffer ? 

### ISSUE THREAD

**Issue by Harrisonnguyen1210** [flutter/flutter#69819]
Hi,
I come across a problem when making a REST request which returns a binary data image (the same as this stackoverflow [thread](https://stackoverflow.com/questions/23013871/how-to-parse-into-base64-string-the-binary-image-from-response)). The solution in this thread is to convert the response into arraybuffer, aka response.arraybuffer()

Is there any solution the same as this for Flutter, I have tried many ways to convert the weird binary string like this (�(f���G���X?����pF4.0׉�X����CgU�I�|,�����t���) 

by base64.decode() or utf8.encode() but no use.

Thank you. Hope to hear from you soon.

**Comment by darshankawar** [comment]
@Harrisonnguyen1210 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Harrisonnguyen1210** [comment]
Hi @darshankawar 
I have posted it in [stackoverflow](https://stackoverflow.com/questions/64688053/do-we-have-any-solution-to-convert-an-api-response-to-arraybuffer) and [reddit](https://www.reddit.com/r/flutterhelp/comments/jofulx/is_there_any_way_to_handle_a_binary_data_from/) but seems there is no solution for it. 
Probably there is a missing feature from flutter to support XHR2 blob/arraybuffer types in http request

**Comment by Harrisonnguyen1210** [comment]
@darshankawar Can you please reopen the issue? There seems to be no solution for this

**Comment by darshankawar** [comment]
@Harrisonnguyen1210 Reopening.

**Comment by sigmundch** [comment]
@Harrisonnguyen1210 can you share more details on how you are trying to fetch the data?

Dart's XHR API supports both `blob` and `arraybuffer` by setting the response type, just like the JavaScript API does. For instance via:

```dart
import 'dart:html';
import 'dart:typed_data';

...
var request = HttpRequest()
      ..open('GET', uri, async: true)
      ..responseType = 'arraybuffer';
request.send();
await request.onLoad.first;
var body = (request.response as ByteBuffer).asUint8List();
...
```

**Comment by Harrisonnguyen1210** [comment]
Oh I forgot to mention that this is for Flutter mobile, not web platform. I think somehow I manage to fetch the data as bytebuffer:
```
      final response = await dio.get(
        Consts.baseUrl + endPointUrl,
        queryParameters: {'_id': xxx, 'type': 'xxx'},
        options: Options(
          responseType: ResponseType.bytes,
          headers: {'Authorization': Consts.apiKey},
          contentType: 'application/octet-stream',
        ),
      );
```
Then the bytebuffer can be accessed with:
**response.data.buffer**

**Comment by ferhatb** [comment]
@Harrisonnguyen1210 looks like you resolved issue. If not please provide a sample we can repro with.
