### ISSUE TITLE
Upgrade Devicelab machines to at least CocoaPods 1.9

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#69829]
Make sure devicelab machines are running at least CocoaPods 1.9 (they may be already).

The tool will soon recommend a minimum of 1.9 https://github.com/flutter/flutter/issues/69807

**Comment by godofredoc** [comment]
Moving this request to the regular triage meeting.

**Comment by godofredoc** [comment]
This is not going be needed after the migration to luci.

**Comment by jmagman** [comment]
We're getting really close to needing this.  It's blocking https://github.com/flutter/flutter/pull/71170 which is necessary to adopt ARM macOS.

I saw a flutter-devicelab-mac-12 error log (not sure what other agents need the upgrade):
```
2020-11-24T14:19:29.465133: stderr: Warning: CocoaPods recommended version 1.9.0 or greater not installed.
```

**Comment by godofredoc** [comment]
This is now controlled completely from the mac dependencies file in flutter.
