### ISSUE TITLE
Fix legacy import violations in web_ui

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#69824]
We are adding a new analyzer lint for legacy library imports (non-nnbd) from opted in libraries.

We got some flutter failures on the cl, https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864529598122711632/+/steps/analyze_flutter_engine/0/stdout.

It looks like the null safe packages need to be pinned here.

This is a high priority because we want to ship the lint with the beta release.

**Comment by jakemac53** [comment]
Part of https://github.com/dart-lang/sdk/issues/44063

**Comment by yjbanov** [comment]
I'm confused by the analyzer warning "The library 'package:js/js.dart' is legacy, and should not be imported into a null safe library". Are we expected to stop using this library?

**Comment by yjbanov** [comment]
If so, what's the replacement?

**Comment by jakemac53** [comment]
The problem is most likely just that you are not depending on the null safe version of these packages.

They all have `-nullsafety.<x>` versions published which will need to be explicitly depended on since they are pre-releases.

**Comment by yjbanov** [comment]
Gotcha. Can the lint message be improved? What it says is far from what you just explained :)

**Comment by jakemac53** [comment]
The issue for the hint is here https://github.com/dart-lang/sdk/issues/44063
