### ISSUE TITLE
Fluxstore issue in v1.7.5 when I run flutter run

### ISSUE THREAD

**Issue by vashisth00** [flutter/flutter#69830]
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3
    or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/
    SKStoreReviewController.h:27:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 9.0.0
    + (void)requestReview API_AVAILABLE(macos(10.14)) API_DEPRECATED_WITH_REPLACEMENT("-[SKStoreReviewController requestReviewInScene:]", ios(10.3, 14.0))
    API_UNAVAILABLE(watchos) __TVOS_PROHIBITED;
    ^
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to
    silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on
    iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/StoreKit.framework/Headers/
    SKStoreReviewController.h:17:110: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 9.0.0
    SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED @interface SKStoreReviewController : NSObject
                                                                                                                 ^
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+3/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an @available
    check to silence this warning
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:4: warning:
    'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
       ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNMutableNotificationContent : UNNotificationContent
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:1: note: annotate
    'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                             API_AVAILA
                                                                                                                                                                                             BLE(ios(10
                                                                                                                                                                                             .0))
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:74: warning:
    'UNNotificationRequest' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                             ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationRequest.h:16:12: note: 'UNNotificationRequest' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNNotificationRequest : NSObject <NSCopying, NSSecureCoding>
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:1: note: annotate
    'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                             API_AVAILA
                                                                                                                                                                                             BLE(ios(10
                                                                                                                                                                                             .0))
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:137: warning:
    'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                                                                                            ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNMutableNotificationContent : UNNotificationContent
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:484:1: note: annotate
    'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                             API_AVAILA
                                                                                                                                                                                             BLE(ios(10
                                                                                                                                                                                             .0))
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:4: warning:
    'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
       ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNMutableNotificationContent : UNNotificationContent
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:1: note: annotate
    'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                            API_AVAILA
                                                                                                                                                                                            BLE(ios(10
                                                                                                                                                                                            .0))
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:73: warning:
    'UNNotificationRequest' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                            ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationRequest.h:16:12: note: 'UNNotificationRequest' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNNotificationRequest : NSObject <NSCopying, NSSecureCoding>
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:1: note: annotate
    'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                            API_AVAILA
                                                                                                                                                                                            BLE(ios(10
                                                                                                                                                                                            .0))
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:136: warning:
    'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                                                                                           ^
    In module 'UserNotifications' imported from
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UserNotifications.framework
    /Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 9.0.0
    @interface UNMutableNotificationContent : UNNotificationContent
               ^
    While building module 'OneSignal' imported from /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.4.1/ios/Classes/OneSignalPlugin.h:29:
    In file included from <module-includes>:1:
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:485:1: note: annotate
    'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
    + (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request
    withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
    ^
                                                                                                                                                                                            API_AVAILA
                                                                                                                                                                                            BLE(ios(10
                                                                                                                                                                                            .0))
    6 warnings generated.
    6 warnings generated.
    Command CompileSwift failed with a nonzero exit code
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/location-3.0.2/ios/Classes/LocationPlugin.m:148:13: warning: 'UIAlertView' is deprecated: first deprecated in iOS
    9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIA
    lertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/omkar.vilankar/.pub-cache/hosted/pub.dartlang.org/location-3.0.2/ios/Classes/LocationPlugin.m:148:48: warning: 'UIAlertView' is deprecated: first deprecated in iOS
    9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIA
    lertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:17:13: error: cannot find 'OneSignal' in
    scope
                OneSignal.didReceiveNotificationExtensionRequest(self.receivedRequest, with: self.bestAttemptContent)
                ^~~~~~~~~
    /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:26:13: error: cannot find 'OneSignal' in
    scope
                OneSignal.serviceExtensionTimeWillExpireRequest(self.receivedRequest, with: self.bestAttemptContent)

**Comment by sanjidbillah** [comment]
I worked with fluxstore, This is not a flutter issue ..
you need to setup one signal properly..

**Comment by vashisth00** [comment]
I did still this issue persists, my flutter version is 1.24.0-8.0.pre.74 can that be an issue?

**Comment by darshankawar** [comment]
@vashisth00 
Not sure what `fluxstore` is, but from your logs, I see you are using `OneSignal` sdk for Flutter. You may need to open this issue in their repo as it idoesn't seem to be an issue with Flutter.
Closing. If you disagree, write in comments and I'll reopen.
Thanks.
