### ISSUE TITLE
* What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Failed to find Build Tools revision 29.0.2

### ISSUE THREAD

**Issue by triadityaa** [flutter/flutter#69845]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find Build Tools revision 29.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sidrao2006** [comment]
Hey @triadityaa , could you please check whether you have installed the android sdk? Please provide the output of `flutter doctor -v`
Thanks

**Comment by darshankawar** [comment]
@triadityaa 
As the error says `Failed to find Build Tools revision 29.0.2`.  Please check if you have installed the said sdk version from sdk manager.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kishankumarhs** [comment]
what i getting after run flutter doctor -v

[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\kishan kumar\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\kishan kumar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\kishan kumar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 86.0.622.56

• No issues found!

**Comment by nggepe** [comment]
> what i getting after run flutter doctor -v
> 
> [√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
> • Flutter version 2.0.1 at C:\src\flutter
> • Framework revision [c5a4b40](https://github.com/flutter/flutter/commit/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c) (2 days ago), 2021-03-04 09:47:48 -0800
> • Engine revision 40441def69
> • Dart version 2.12.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\Users\kishan kumar\AppData\Local\Android\Sdk
> • Platform android-29, build-tools 29.0.3
> • ANDROID_HOME = C:\Users\kishan kumar\AppData\Local\Android\Sdk
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
> • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin can be installed from:
> https://plugins.jetbrains.com/plugin/9212-flutter
> • Dart plugin can be installed from:
> https://plugins.jetbrains.com/plugin/6351-dart
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.54.1)
> • VS Code at C:\Users\kishan kumar\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.20.0
> 
> [√] Connected device (2 available)
> • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
> • Edge (web) • edge • web-javascript • Microsoft Edge 86.0.622.56
> 
> • No issues found!

I got the same issue at flutter stable chanel 2.0.1

**Comment by nggepe** [comment]
@kishankumarhs hello.. you can download the sdk build here https://developer.android.com/studio/releases/build-tools

**Comment by ErikQQY** [comment]
Hello guys, I had the same problem yesterday, to solve the problem, I directly deleted the .gradle file in C:\Users\Administrator\ and this method worked for me. Wish you can solve it.

**Comment by ErikQQY** [comment]
> Hello guys, I had the same problem yesterday, to solve the problem, I directly deleted the .gradle file in C:\Users\Administrator\ and this method worked for me. Wish you can solve it.

And also I tried checking my SDK manager, which still don't work for me.

**Comment by nggepe** [comment]
@ErikQQY may you can try to run the gradlew test first

**Comment by ErikQQY** [comment]
Yes, I think it is a problem relating to gradle, but directly delete the .gradle file indeed solve the problem.

**Comment by udaykumaruking** [comment]
I have deleted the .gradle file even though I am facing this problem.

**Comment by mathiasgodwin** [comment]
Deleting .gradle folder solved the problem for me too. just head-on into your usual project dir and navigate into android and you'd find .gradle folder waving a hand in there. I hope this help some out there

**Comment by nintendaii** [comment]
Hey! I am facing the same issue on my MacBook Pro 16. I tried to delete the gradle folder but it doesn’t help. Flutter doctor is outputting that everything is fine. Any other suggestions how to fix this?
