### ISSUE TITLE
The Flutter is embedded in a native FlutterFragment, but the system return key cannot be listened to using WillPopScope

### ISSUE THREAD

**Issue by lv823063712** [flutter/flutter#69855]
The Flutter is embedded in a native FlutterFragment, but the system return key cannot be listened to using WillPopScope
Here's the code for the Android native side
![image](https://user-images.githubusercontent.com/44794626/98204384-ec86fd80-1f70-11eb-934e-98f614509210.png)
Here is how the return key is handled in the native
![image](https://user-images.githubusercontent.com/44794626/98204412-f7419280-1f70-11eb-9535-cc437a838557.png)
Listening in Flutter
![image](https://user-images.githubusercontent.com/44794626/98204531-2c4de500-1f71-11eb-89bd-ff61de83fafc.png)

**Comment by darshankawar** [comment]
@lv823063712 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample in text format that we can use to replicate the issue. Also provide what should be  the expected behavior / result as compared to actual behavior when we run the code.
Thanks.

**Comment by lv823063712** [comment]
`
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version
    10.0.18363.1139], locale zh-CN)
    • Flutter version 1.22.2 at E:\job\flutter\flutter
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2
)
    • Android SDK at E:\job\androidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:\job\androidSDK
    • Java binary at: E:\job\androidStudio\jre\bin\java
`


Specific question me a more detailed description, is me in my android native project, to replace the home page, patients, the three fragments of my module, and then in my module jump to other page weight, return key when I click on my system, is expected to happen should return to the 'I' the weight, but the Activity of my native project prompted again, click the back button will exit the APP.
That's a lot of code and I think the screenshot that I gave you clearly illustrates my presentation logic.

**Comment by lv823063712** [comment]
I want to click the system's back key when I'm on another Weight page to return to my previous weight, rather than responding to my native Activity action

**Comment by darshankawar** [comment]
@lv823063712 
We will need a minimal reproducible code sample that will help to analyse the issue better. You provided code in screenshots that we can't use.

**Comment by lv823063712** [comment]
I already wrote the Demo .The address of the native Android project is [https://github.com/lv823063712/FlutterDemo](url) ,The address of the mashup project Flutter is [https://github.com/lv823063712/Flutter_lab](url),I think you can see what I'm trying to say from these two demos

**Comment by TahaTesser** [comment]
Can confirm, no issues on the latest master on API 23
<details> 
<summary>flutter doctor -v</summary> 

```bash
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: TextField(),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>
<details> 
<summary>logs</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.268, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-8.0.pre.268 at C:\Code\flutter_master
    • Framework revision e803b13f01 (7 hours ago), 2020-11-16 22:55:59 -0800
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 6.0 (API 23) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @lv823063712 
I see that you're `flutter_boost`  in your app, can you provide a code sample without using a third-party package 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
