### ISSUE TITLE
BottomNavigationBar Icon mechanism is too restrictive

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#6985]
- Framework revision 9c1a24fa72 (4 days ago), 2016-11-18 21:22:32
- Engine revision cea5ed2b9b
- Tools Dart version 1.21.0-dev.6.0

Currently it is very difficult to set an image asset other than an `Icon` for the `BottomNavigationBar`. There doesn't seem to be a way to convert an `AssetImage` to an `Icon` and `DestinationLabel` requires an `Icon` value.

From Gitter (@abarth), re: `DestinationLabel`:
> @required Icon icon
> looks like an oversight
> one sec
> hum... it needs to determine the size of the icon as part of its animation

It would be great if we could either use a "generic" image asset of some kind or be able to use a widget that supports image rendering.

**Comment by Hixie** [comment]
ImageIcon is supposed to address this need, we'll have to make BottomNavigationBar allow any widget and then find another way to read the size. Or alternatively, have Icon and ImageIcon implement some interface that exposes the size, and have it require that instead.

**Comment by lukef** [comment]
Regarding the `Icon` and `ImageIcon`: is the intention that they always be square? In the case of `ImageIcon` it appears that it uses `ImageFit.scaleDown` as the fit mode. Not sure if there is a benefit to allowing non-square images.

Regardless, would it just make sense for both classes to extend a common interface/class so that size could be returned for both?

**Comment by Hixie** [comment]
Yeah, the intent is that icons be square.

Exactly how to get the size isn't something I've looked into. If it's possible to get the size during layout that's probably the right solution rather than limiting what widgets go here.
