### ISSUE TITLE
Crashlytics ios error

### ISSUE THREAD

**Issue by Aman2two** [flutter/flutter#69861]
Crashlytics are not working as expected in ios.But working fine in android.

Expected result:Crash Logs visible on firebase portal.

Actual results: No logs visible on firebase portal.

Logs at app start:

Configuring the default Firebase app...

[Crashlytics] Version 3.14.0 (144)

Configured the default Firebase app __FIRAPP_DEFAULT.

[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize

[Crashlytics:Crash:Reports] Packaged report with id '70fe706678874704bbfda74a9049a231' for submission

[Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

flutter doctor

[✓] Flutter (Channel master, 1.20.0, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.20.0 at /Users/decimal/Documents/flutterDev/flutter
    • Framework revision 5663e02645 (5 months ago), 2020-05-27 18:32:01 -0400
    • Engine revision 2663be8370
    • Dart version 2.9.0 (build 2.9.0-11.0.dev e007545c42)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/decimal/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (1 available)            
    • iPhone • 25ea7936364fe6369e214fff6c8bb78c55f43046 • ios • iOS 12.4.8

• No issues found!

**Comment by darshankawar** [comment]
@Aman2two 
Firebase related issues are tracked here https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
