### ISSUE TITLE
Android Studio can not find the Flutter plugin and Dart plugin

### ISSUE THREAD

**Issue by NayoLx** [flutter/flutter#69867]
**when i upgrade to 1.22.3, Android Studio can not find the Flutter plugin and Dart plugin, how can i fix it, !!!**

already install the Flutter plugin and Dart plugin
![image](https://user-images.githubusercontent.com/36600238/98221697-ec93f700-1f8a-11eb-90d8-34ff864e2ff1.png)

PS C:\Users\coco\Desktop> flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale zh-CN)
    • Flutter version 1.22.3 at D:\softwares\flutter
    • Framework revision 8874f21e79 (7 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download 
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Tools\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Tools\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\coco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by hg42** [comment]
I also have this...

may be it's related to another effect:
Neither my android device(s) nor emulator(s) are not found.
The flutter device selection seems to be designed to be on the left of the module selection (as shown in videos), but there is also the usual device selection on the right of the module selection, but it is disabled (and shows my device!). So run button from toolbar doesn't work.
Apart from that "flutter run" works in the Android Studio "Terminal" tab.

The plugin is not found by flutter doctor, but obviously is integrated in the UI in some way (e.g. in the menu).

**Comment by darshankawar** [comment]
@NayoLx 
This [issue](https://github.com/flutter/flutter/issues/67986) has been fixed and merged. Even though you are seeing plugins not installed, they are just warnings and don't matter. You can still used them in your project like earlier.
You may switch to latest master and try again to see the fix.
Closing this as duplicate and fixed.
