### ISSUE TITLE
The TextField widgetcannot limit input to only two decimal places

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#69860]
The TextField widgetcannot limit input to only two decimal places

**Comment by darshankawar** [comment]
@gionchat 
Please provide `flutter doctor -v` and a minimal code sample that shows the issue you are facing.
Thanks.

**Comment by RivaanRanawat** [comment]
I think you mean that you can't add more than two digits after decimal point. It can be fixed by putting this in your TextField widget: 
inputFormatters: [DecimalTextInputFormatter(decimalRange: 2)], 
or using regex:
inputFormatters: [WhitelistingTextInputFormatter(RegExp(r'^\d+\.?\d{0,2}')),],

**Comment by gionchat** [comment]
> I think you mean that you can't add more than two digits after decimal point. It can be fixed by putting this in your TextField widget:
> inputFormatters: [DecimalTextInputFormatter(decimalRange: 2)],
> or using regex:
> inputFormatters: [WhitelistingTextInputFormatter(RegExp(r'^\d+.?\d{0,2}')),],

yes，Thanks！

**Comment by gionchat** [comment]
> > I think you mean that you can't add more than two digits after decimal point. It can be fixed by putting this in your TextField widget:
> > inputFormatters: [DecimalTextInputFormatter(decimalRange: 2)],
> > or using regex:
> > inputFormatters: [WhitelistingTextInputFormatter(RegExp(r'^\d+.?\d{0,2}')),],
> 
> yes，Thanks！

Thanks！
