### ISSUE TITLE
flutter run fails on Windows 10 (flutter desktop)

### ISSUE THREAD

**Issue by utsukprani** [flutter/flutter#69872]
## Steps to Reproduce

1. I followed the following page to try and create a flutter desktop application [https://flutter.dev/desktop](https://flutter.dev/desktop)
2. After following the article I did, Run `flutter create myapp`.

**Expected results:** 
Demo application should run.

**Actual results:** 
Running "flutter pub get" in myapp...                              803ms
Launching lib\main.dart on Windows in debug mode...
C:\SelfLearning\flutterprjs\myapp\windows\runner\main.cpp(28,11): error C2039: 'set_dart_entrypoint_arguments': is not a member of
'flutter::DartProject' [C:\SelfLearning\flutterprjs\myapp\build\windows\runner\myapp.vcxproj]
Building Windows application...
Exception: Build process failed.

<details>
  <summary>
flutter doctor log

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.17763.1457], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
</summary>

```
```

```
```

```
```

</details>

**Comment by spekary** [comment]
I had the same problem running a default application from the Android Studio IDE.

**Comment by spekary** [comment]
Looks like this is fixed on the master.

Run `flutter channel master` and try again. It should work.

**Comment by bosskmk** [comment]
It was modified in the master, but the web behavior in the master is strange.

Some of the widgets in the listView are invisible and appear when tapped.

**Comment by darshankawar** [comment]
@utsukprani 
Can you try as suggested [here](https://github.com/flutter/flutter/issues/69872#issuecomment-722696080) and see if it works for you ?

**Comment by ScottHuangZL** [comment]
I encounter same issue. So now channel master already support desktop? thanks.

**Comment by yahu1031** [comment]
I got this issue on **Master channel**

```console
Running "flutter pub get" in flutter_installer...
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart(462,37): error GBF4691A2: No named parameter with the name 'shadowThemeOnly'. [C:\Users\minnu\Documents\Projects\Flutter\flutter_installer\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart(655,43): error GBF4691A2: No named parameter with the name 'shadowThemeOnly'. [C:\Users\minnu\Documents\Projects\Flutter\flutter_installer\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```
the same code works on linux perfectly fine but I'm getting this issue in windows.

This error on **Dev channel**

```console
Running "flutter pub get" in installer...                           3.6s
Launching lib\main.dart on Windows in debug mode...
C:\Users\minnu\Documents\Projects\Flutter\installer\windows\runner\main.cpp(28,11): error C2039: 'set_dart_entrypoint_arguments': is not a member of 'flutter::DartProject' [C:\Users\minnu\Documents\Projects\Flutter\installer\build\windows\runner\installer.vcxproj]
Building Windows application...
Exception: Build process failed.
```
This my Doctor result on dev
`flutter doctor -v`

```console
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19042.610], locale en-IN)
    • Flutter version 1.24.0-7.0.pre at C:\src\flutter
    • Framework revision a0860f6e87 (8 days ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\minnu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\minnu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\minnu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\minnu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.610]

• No issues found!
```

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/pull/68931 landed slightly before https://github.com/flutter/engine/pull/22094 rolled into Flutter in https://github.com/flutter/flutter/pull/69353, so there was accidentally a small window of builds where `flutter create` would make projects that couldn't run with that version of the engine (but will run with newer versions).

@gw280 FYI for the future, you have to be careful about waiting for rolls when there are dependencies.

**Comment by stuartmorgan** [comment]
> I got this issue on Master channel
> [...]
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart(462,37): error

That has nothing at all do to with this issue, and is in a third-party package; please don't report issues with third-party code here. Looks like it's already filed in that package's issue tracker: https://github.com/jonataslaw/getx/issues/762

**Comment by utsukprani** [comment]
> @utsukprani
> Can you try as suggested [here](https://github.com/flutter/flutter/issues/69872#issuecomment-722696080) and see if it works for you ?

Hi @darshankawar @spekary it worked after I did 'flutter channel master'.
So it seems that the documentation at [https://flutter.dev/desktop](https://flutter.dev/desktop) needs update.

thanks for the help !

**Comment by utsukprani** [comment]
> I got this issue on **Master channel**
> 
> ```
> Running "flutter pub get" in flutter_installer...
> Launching lib\main.dart on Windows in debug mode...
> lib\main.dart:1
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart(462,37): error GBF4691A2: No named parameter with the name 'shadowThemeOnly'. [C:\Users\minnu\Documents\Projects\Flutter\flutter_installer\build\windows\flutter\flutter_assemble.vcxproj]
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get_navigation-3.12.0/lib/src/extension_navigation.dart(655,43): error GBF4691A2: No named parameter with the name 'shadowThemeOnly'. [C:\Users\minnu\Documents\Projects\Flutter\flutter_installer\build\windows\flutter\flutter_assemble.vcxproj]
> Exception: Build process failed.
> Exited (sigterm)
> ```
> 
> the same code works on linux perfectly fine but I'm getting this issue in windows.
> 
> This error on **Dev channel**
> 
> ```
> Running "flutter pub get" in installer...                           3.6s
> Launching lib\main.dart on Windows in debug mode...
> C:\Users\minnu\Documents\Projects\Flutter\installer\windows\runner\main.cpp(28,11): error C2039: 'set_dart_entrypoint_arguments': is not a member of 'flutter::DartProject' [C:\Users\minnu\Documents\Projects\Flutter\installer\build\windows\runner\installer.vcxproj]
> Building Windows application...
> Exception: Build process failed.
> ```
> 
> This my Doctor result on dev
> `flutter doctor -v`
> 
> ```
> [✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19042.610], locale en-IN)
>     • Flutter version 1.24.0-7.0.pre at C:\src\flutter
>     • Framework revision a0860f6e87 (8 days ago), 2020-10-29 20:07:34 -0700
>     • Engine revision 073263e39d
>     • Dart version 2.11.0 (build 2.11.0-260.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\minnu\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: C:\Users\minnu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.7.30621.155
>     • Windows 10 SDK version 10.0.19041.0
> 
> [✓] Android Studio (version 4.1.0)
>     • Android Studio at C:\Users\minnu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [✓] VS Code (version 1.51.0)
>     • VS Code at C:\Users\minnu\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (1 available)
>     • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.610]
> 
> • No issues found!
> ```

Hi @yahu1031  I was getting exact C2039 error on my windows. But with channel as master, it worked for me.

**Comment by spekary** [comment]
So, I guess the real question is ... why are people pushing code to flutter that break the build, even for the basic default project created by the IDE? Are there really no CI hooks that check for basic unit tests before allowing a merge to master?

**Comment by stuartmorgan** [comment]
> Are there really no CI hooks that check for basic unit tests

There are many unit tests. But running the full Flutter tool to create a new project from scratch and then build it, including the call out to the native build tools (Visual Studio on the Windows case) is not a unit test, it's an end-to-end integration test. The first Windows integration test (which builds an existing project, not a freshly created project) was only very recently brought online due to CI infrastructure complexities, and it hasn't expanded to full coverage yet.

**Comment by stuartmorgan** [comment]
> So it seems that the documentation at https://flutter.dev/desktop needs update.

The documentation is correct. There was a bug in one specific dev channel build, which isn't the same thing as dev channel not being supported.

**Comment by FranzMe** [comment]
Hi, I'm just trying to use flutter desktop for the first time and I have the same issue. Looking in the code I think that are missing these two declare in the public section of dart_project.h:

 
   // Sets the command line arguments that should be passed to the Dart
   // entrypoint.
   void set_dart_entrypoint_arguments(std::vector<std::string> arguments) {
     dart_entrypoint_arguments_ = std::move(arguments);
   }
 
   // Returns any command line arguments that should be passed to the Dart
   // entrypoint.
   const std::vector<std::string>& dart_entrypoint_arguments() const {
     return dart_entrypoint_arguments_;
   }

I have compared it with the dart_project.h from master channel.

Once fixed it using the dev channel I have a new error code: MSB6006

Using the master channel the app is compiled and run.

**Comment by Abhi011999** [comment]
The commit is still not there in `dev` branch of tag `1.24.0-7.0.pre`. How to get this commit working without switching to `master` branch ?
Cherry-pick ??
