### ISSUE TITLE
Flutter PlatformPlugin on Android's "popSystemNavigator" does not handle the FlutterFragment case in Add To App scenario

### ISSUE THREAD

**Issue by wugeo0824** [flutter/flutter#69879]
## Steps to Reproduce

1. Add Flutter to existing app
2. Use FlutterFragment inside existing feature flow, where there are Android Fragments and FlutterFragment added into the same hosting Activity
3. When user is on FlutterFragment, and fragment back stack looks like "FlutterFragment -> Android Fragment A -> Android Fragment B"
4. User is on initialRoute on Flutter feature
5. User presses back button

**Expected results:** 

When user presses back button, the top FlutterFragment should be popped, and Android Fragment A should be visible

**Actual results:** 

When user presses back button, the entire Activity was closed. 

After some digging, the issue might be caused by Android side's Flutter PlatformPlugin implementation. Inside "io.flutter.plugin.platform.PlatformPlugin", it implements the `popSystemNavigator` callback as
```
  private void popSystemNavigator() {
    activity.finish();
  }
```
It will instruct the hosting activity to finish itself, regardless of how many fragments are there in the back stack.

<details>
  <summary>Logs</summary>

```
```

```
```

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.7 19H2, locale en-SG)
    • Flutter version 1.20.2 at /Users/xijun.li/Workspace/flutter
    • Framework revision bbfbf1770c (3 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xijun.li/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/xijun.li/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by hamdikahloun** [comment]
Hi @wugeo0824 

Can you please provide a minimal complete reproducible code sample (Git repo if you can) ?

Thank you

**Comment by wugeo0824** [comment]
Hi @hamdikahloun ,

Here is the reproducible code sample: https://github.com/wugeo0824/flutter_fragment_bug

In this sample, you can reproduce the bug by
1. compile and launch the app
2. on the first screen, click on "Open Flutter Fragment"
3. on the second screen, press hardware back button

**Actual Result:**
4. notice that the application closes itself

**Expected Result:**
4. when there are 2 fragments in the back stack, (one Flutter fragment and one Android Fragment), with FlutterFragment being on top, back button press should pop the top FlutterFragment and show AndroidFragment

**Comment by darshankawar** [comment]
@wugeo0824 
See [this](https://github.com/flutter/flutter/issues/67011) open issue and confirm if it resembles your issue.

**Comment by hamdikahloun** [comment]
Hi @wugeo0824 

For handling Back Button Navigation in fragments, We must add `addToBackStack()`. By calling `addToBackStack()`, the replace transaction is saved to the back stack so the user can reverse the transaction and bring back the previous fragment by pressing the Back button.

**But if we change the code to :**

```
override fun openFlutterFragment() {
        val flutterFragment = FlutterFragment.createDefault()
        supportFragmentManager.beginTransaction()
                .add(R.id.container, flutterFragment, FirstFragment.TAG)
                .addToBackStack(null)
                .commit()
    }
```

<details>
  <summary>main.dart</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

**Expected results:** In Second Route, by pressing the Back Button, we must navigate to the First Route

**Actual results:** In Second Route, by pressing the Back Button, The `FlutterFragment` is closed

See : https://github.com/flutter/flutter/issues/67011

**Comment by wugeo0824** [comment]
Hi @darshankawar ,

These two issues are related, both are about Flutter Fragment navigation, but from what I understand, they are focusing on different parts.
[This](https://github.com/flutter/flutter/issues/67011) is about onBackPressed callback for nested fragments, while I am reporting on the "popSystemNavigator" call not suitable for Fragment Add to app usecase (it finishes the activity no matter how many fragments are in the back stack).

**Comment by darshankawar** [comment]
@wugeo0824 
Thanks for confirming. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

• No issues found!


```

</details>

[69879.mp4.zip](https://github.com/flutter/flutter/files/5510062/69879.mp4.zip)

**Comment by hamdikahloun** [comment]
New PR will be available soon. 

Expected result :

![ezgif com-gif-maker](https://user-images.githubusercontent.com/32666446/98865187-56b90a00-246b-11eb-9530-68eff82973c2.gif)

**Comment by wugeo0824** [comment]
that looks like the fix we need. thanks! @hamdikahloun @darshankawar
