### ISSUE TITLE
Broken keyboard hide logic on back button click

### ISSUE THREAD

**Issue by worldofsites** [flutter/flutter#69886]
After typing some text in textbox and trying to tap back on navigation bar keyboard not hiding.
![image](https://user-images.githubusercontent.com/23352829/98257417-40660680-1fb2-11eb-972e-2098179fb2d7.png)

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-8.0.pre.97, on Microsoft Windows [Version 10.0.19041.572], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!
```
Checked by reseting to commits on flutter master branch and looks like broken after https://github.com/flutter/flutter/commit/4bd89b399e901fed8a46057268fadbba2ed24da9

And after reverting that commit by @jonahwilliams in https://github.com/flutter/flutter/commit/ef4ec09a06cdc88d335179f542ee01ffd2b0c12d all works as before

**Comment by zanderso** [comment]
@gspencergoog for https://github.com/flutter/engine/pull/22304
