### ISSUE TITLE
Shared Preferences MissingPluginException

### ISSUE THREAD

**Issue by rehamalraee** [flutter/flutter#69881]
Hello, when I tried to access shared preferences in the background function I got this 
MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)
how to solve it?

**Comment by darshankawar** [comment]
@rehamalraee 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by rehamalraee** [comment]
> flutter doctor -v

[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.0 at C:\Users\ThinkPad\Downloads\flutter
    • Framework revision d408d302e2 (5 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\ThinkPad\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

**Comment by rehamalraee** [comment]
<
<



< and I call callService in my main
void callService(){
  var channel = const MethodChannel('com.mediaworldiq/vrbtService');
  var callbackHandle = PluginUtilities.getCallbackHandle(backgroundMain);
  channel.invokeMethod('startService', callbackHandle.toRawHandle());
}
void startmooding() async{
  String ass;
  Stream.periodic(Duration(seconds: 1)).listen((_) async {
    await SharedPreferences.getInstance().then((SharedPreferences sp) {
      ass = sp.getString("assets");
      print(ass);
    });
    if(ass != null)
    {
      bubbleOverlay.openVideoBubble(ass,
          startTimeInMilliseconds: 00000, controlsType: ControlsType.STANDARD);
      print("startOverlay");
    }
  });
}
/>

**Comment by darshankawar** [comment]
@rehamalraee 
Can you try to upgrade to latest stable (1.22.3) and check if you get same error ?
If so, please provide complete code sample. The one you provided above isn't complete. We will need code sample that we can copy paste and run directly.
Also you may try the official shared_preferences plugin example and see if you get same error using that example or not.
Thanks.

**Comment by rehamalraee** [comment]
@darshankawar  I've used the shared preferences inside my code and works fine, but it does not work on any background call, such as onBackgroundMessage when I use firebase

**Comment by rehamalraee** [comment]
@darshankawar  Can you please provide me a sample of how to use shared-preferences in onBackgroundMessage for example?

**Comment by rehamalraee** [comment]
@darshankawar this is another code snippent where I face the same exception 
Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
  if (message.containsKey('data')) {
    final dynamic data = message['data'] ;
    if(data != null){
      SharedPreferences.getInstance().then((SharedPreferences sp) {
      sp.setString("filenameBKNotificatoin",data["filename"]);
      });
    }
    print("Push Messaging message: $data");
  }

  if (message.containsKey('notification')) {
    // Handle notification message
    final dynamic notification = message['notification'];
  }

  // Or do other work.
}

**Comment by rehamalraee** [comment]
@darshankawar  I upgraded to the latest channel
![feesfefwe](https://user-images.githubusercontent.com/71270985/98377608-b5d2e500-204d-11eb-9847-aee8816842bb.PNG)
, and upgrade all my libraries,

**Comment by Abhishek01039** [comment]
Hello @rehamalraee 
can you please try `flutter clean` then try `flutter run -v`?
Thanks.

**Comment by rehamalraee** [comment]
hello @Abhishek01039 
![image](https://user-images.githubusercontent.com/71270985/98481185-44d42e80-2201-11eb-9208-71ef187c03f5.png)

**Comment by darshankawar** [comment]
@rehamalraee Please try [this](https://github.com/flutter/flutter/issues/65334#issuecomment-689609774) solution and see if it works for you.

**Comment by rehamalraee** [comment]
@darshankawar  I've read before , I'm already have com.android.tools.build:gradle:3.5.1 in my project and it never changed, I checked it many times. :(

**Comment by darshankawar** [comment]
@rehamalraee 
Can you put your project on github and share repo link here, so that we can clone it and try to replicate the issue ? Note that, it should only contain the necessary code that you think is required to replicate the issue. No 3rd party plugin code.
Thanks.

**Comment by lijy91** [comment]
I think the problem is that one of the plugins has crashed, causing shared_preferences to not register successfully, resulting in this error.

Debug your `GeneratedPluginRegistrant` file, you may find that an exception occurs at one of the plugins

**Comment by rehamalraee** [comment]
@lijy91  @darshankawar  
I caught this exception also (
**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine) but could not find and invoke the GeneratedPluginRegistrant** 
) It seems because of it the shared preferences registration failed?
I tried the provided solutions on GitHub, they are not working with me :( any suggestions?

**Comment by darshankawar** [comment]
@rehamalraee 
Check [this](https://github.com/flutter/flutter/issues/58113) similar issue and underlying comments and possible solutions to fix the issue you are seeing. Also check [this](https://github.com/flutter/flutter/issues/58113#issuecomment-636833955) comment.

**Comment by rehamalraee** [comment]
@darshankawar  I explored this, and I checked the mentioned configurations all is correct in my project. :( not working :(

**Comment by rehamalraee** [comment]
@darshankawar  Also, I've created a new project, not fixed! 
all of my plugins are up to date, the android studio also is.

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.

**Comment by rehamalraee** [comment]
@darshankawar  @lijy91 These exceptions appear when the app goes running in the background 
@darshankawar shall I open a new issue? 
![image](https://user-images.githubusercontent.com/71270985/99097566-76257380-25e0-11eb-9848-f9a2ab6f0c89.png)

**Comment by xinoxapps** [comment]
I wrapped shared preferences around save code and then the error still occurs but at least is not causing problems.

The other plug-ins appear to be working fine.

My list is.

```
  flutter_svg: ^0.19.1
  lottie: ^0.7.0+1
  keyboard_visibility: ^0.5.6
  firebase_dynamic_links: ^0.6.1
  shared_preferences: ^0.5.12+4
  webview_flutter: ^1.0.6
  flutter_barcode_scanner: ^1.0.1

  google_fonts: ^1.1.1
  firebase_core: 0.5.1
  firebase_auth: 0.18.2
  firebase_analytics: ^6.1.0
  cloud_firestore: ^0.14.2
  cloud_functions: ^0.7.0
  firebase_messaging: ^7.0.3

  intl: ^0.16.1
  bloc: ^6.1.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.2
  cupertino_icons: ^1.0.0
```

Root Gradle:

distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-all.zip
```
buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

App Gradle

```
compileSdkVersion 29
..
        minSdkVersion 22
        targetSdkVersion 29
..
dependencies {
    implementation 'com.google.firebase:firebase-analytics:17.4.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.0'
}
```
flutter:
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on macOS 11.0.1 20B29 x86_64, locale nl-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by ipcjs** [comment]
solution: https://github.com/flutter/flutter/issues/58479#issuecomment-734099445

**Comment by a7mdragab** [comment]
I have the same problem and tried every possible solutions!
Any updates?

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.406, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-8.0.pre.406 at E:\elshab7\Work\Flutter_Work\flutter
    • Framework revision 60bdcf55fe (8 hours ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:/elshab7/Work/Android_Work/Tools/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:/elshab7/Work/Android_Work/Tools/Sdk
    • Java binary at: E:\elshab7\Work\Android_Work\Tools\android-studio-ide-192.5871855-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at E:\elshab7\Work\Programs_Installation\VS2019
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\elshab7\Work\Android_Work\Tools\android-studio-ide-192.5871855-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\elshab7\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```

**Comment by yaizudamashii** [comment]
Seeing the same problem for add-to-app for iOS

**Comment by rehamalraee** [comment]
I solved by:         SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))

**Comment by ashishoffice** [comment]
> I solved by:         SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))
> 

How to implement?

**Comment by markjoseultra** [comment]
> I solved by: SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))

Hi how did you add this?

**Comment by expertdev-designer** [comment]
@followthemoney1 

Please let me know exact location where i can add this line 
SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"))

I don't get where i need to add.

Thanks
