### ISSUE TITLE
[test] Split web-related flutter_tools tests into a separate shard

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#69909]
Currently all the tests under flutter_tools are run in a the same shard called `tool_tests` that includes all subshards from `flutter_tools/test` directory.  This makes it hard to separate into web-related and non-web-related tests that is needed to run `flutter hhh web` and `flutter hhh` bots:

https://github.com/flutter/flutter/blob/ad9b30b38dafdf5623f2d51d608ef2818064731d/dev/bots/test.dart#L127

Splitting the web related tests into a separate directory would solve this problem, and make it much simpler to classify the problems that pop up on hhh bots into "vm" or "web" category.

Related issue: web tests breaking on non-web hhh bot: https://github.com/flutter/flutter/issues/69711

**Comment by jonahwilliams** [comment]
This is done
