### ISSUE TITLE
[Builder] link to LUCI recipe is broken

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#69927]
On this build detail page: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20Debug%20Engine/15609/overview

The recipe link provided:

![image](https://user-images.githubusercontent.com/463376/98311598-a3d93f80-1f84-11eb-8bd8-8215e842fd0d.png)

ends up linking to:

https://source.chromium.org/search/?q=file%3Arecipes%2Fengine.py

which shows no results found.

**Comment by yusufm** [comment]
I think the correct url might be:

https://cs.opensource.google/search?q=file%3Arecipes%2Fengine.py

**Comment by godofredoc** [comment]
This is difficult to fix because hardcoded in the milo UI. We can try to add the recipes to chromium search.

**Comment by yusufm** [comment]
Filed a luci bug to track creation of the mirror repo: https://bugs.chromium.org/p/chromium/issues/detail?id=1149431

**Comment by yusufm** [comment]
Note: discussed modifying the existing code to add a conditional for the flutter link construction with the luci team.
It was agreed adding the special conditional would only increase complexity and not be a long term solution. The mirror seems to be a feasible stop gap solution till a longer term solution for customizable links can be designed and implemented.

Note2: FYI, here are the potential locations that would need to be modified to add the conditional to handle the new links:

https://source.chromium.org/chromium/infra/infra/+/master:go/src/go.chromium.org/luci/milo/frontend/ui/build.go;l=181?q=source.chromium.org&ss=chromium

https://source.chromium.org/chromium/infra/infra/+/master:go/src/go.chromium.org/luci/milo/frontend/resultui/src/models/build_ext.ts;l=97?q=source.chromium.org&ss=chromium

**Comment by yusufm** [comment]
After discussing with the ops team about mirroring the flutter repo, we determined that it added a significant overhead and maintenance burden.

Therefore, we are adding the conditional code as a stop gap till the long term solution is ironed out by the luci team.

Change for the short term fix is:

https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/2546036

**Comment by yusufm** [comment]
Verified the change is deployed to prod and working fro legacy and new style result page.
