### ISSUE TITLE
ScaffoldMessenger should be more helpful with nested Scaffolds

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#69929]
b/171649782

See discussion in https://github.com/flutter/flutter/pull/69907

Suggested by @mehmetf, ScaffoldMessenger could be more helpful if it could assert when registering a Scaffold that is a descendent of an already registered Scaffold.. something like:

```dart
void _register(ScaffoldState scaffold) {
    assert(_scaffolds does not contain any item that is a parent of the scaffold, 'You should really scope your Scaffolds....');
    _scaffolds.add(scaffold);
    if (_snackBars.isNotEmpty) {
      scaffold._updateSnackBar();
    }
  }
```

We should also expand the docs on troubleshooting nested Scaffolds, and add this to the migration guide as well:
https://api.flutter.dev/flutter/material/Scaffold-class.html
https://flutter.dev/docs/release/breaking-changes/scaffold-messenger

**Comment by Piinks** [comment]
@mehmetf I looked at this today, and realized asserting on nested Scaffolds would be really breaking to those who are not currently using the ScaffoldMessenger.

Right now, the ScaffoldState.[SnackBar methods] are only deprecated, so having nested un-scoped Scaffolds is ok. Asserting on nested Scaffolds right now would break these users and force them to migrate to the ScaffoldMessenger, since there is a default ScaffoldMessenger at the root of the application.

I'll continue to put together more resources and documentation around this, but I don't know that we can safely assert as previously thought. 🤔

**Comment by mehmetf** [comment]
We could trigger the assertion if the ScaffoldMessenger actually receives a message. Would that work?

```dart
/* Some internal state that signals we found problematic nesting */
bool _nestedScaffoldFound;

showSnackbar(...) {
  assert(!_nestedScaffoldFound, 'Should not nest scaffolds');
  ...
}
```

We can also hide the _nestedScaffoldFound computation inside an assert fn to prevent the expensive operation from being performed in release mode.

**Comment by Piinks** [comment]
Gotcha! Thanks!

**Comment by Piinks** [comment]
Internal customer has asked we do not land this as it will break their current implementation that contains nested Scaffolds. Working with the customer to migrate before adding this handling.

**Comment by sanekyy** [comment]
Found this issue while use nested Scaffolds, one is main page with bottom navitagation, and second is pages/tabs with AppBar.

I can't use  ScaffoldMessenger, due to it trying to show SnackBars on both Scaffolds.

**Comment by Piinks** [comment]
> Found this issue while use nested Scaffolds, one is main page with bottom navitagation, and second is pages/tabs with AppBar.
> 
> I can't use ScaffoldMessenger, due to it trying to show SnackBars on both Scaffolds.

Hi @sanekyy, if you have nested Scaffolds, then you will need to use the ScaffoldMessenger in between to scope your SnackBars so there will not be duplication. There are several examples of this in: https://youtu.be/sYG7HAGu_Eg?t=10249
