### ISSUE TITLE
debugDisableShadows docs should explain usage

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#69925]
The `debugDisableShadows` property can be used within tests to enable shadows for a given test for screenshots.

The only way this property works is if you set it to `false` in a single test case, then set it back to `true` before the end of the test case. If you try to alter it outside of an individual test, an exception is thrown. If you don't remember to set it back at the end of a test, an exception is thrown.

The docs for `debugDisableShadows` should clearly articulate how it is expected to be used.

https://api.flutter.dev/flutter/painting/debugDisableShadows.html

**Comment by Roshan13046** [comment]
I will like to work on this issue.
