### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by jchenx2** [flutter/flutter#69931]
group="main" sCount=0 dsCount=0 obj=0x74f10658 self=0xa4c04400
--
sysTid=1244 nice=-10 cgrp=default sched=0/0 handle=0xa78ce534
state=R schedstat=( 1600313136 744165252 3463 ) utm=117 stm=43 core=1 HZ=100
stack=0xbe32e000-0xbe330000 stackSize=8MB
held mutexes= "mutator lock"(shared held)at java.util.concurrent.atomic.AtomicLong.getAndIncrement(AtomicLong.java:146)at io.flutter.embedding.engine.renderer.FlutterRenderer.createSurfaceTexture(FlutterRenderer.java:100)at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:168)at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)at android.os.MessageQueue.nativePollOnce(Native method)at android.os.MessageQueue.next(MessageQueue.java:323)at android.os.Looper.loop(Looper.java:136)at android.app.ActivityThread.main(ActivityThread.java:6121)at java.lang.reflect.Method.invoke!(Native method)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.47.0)
[√] Connected device (1 available)

• No issues found!

**Comment by pedromassangocode** [comment]
Hi @jchenx2 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a the steps to reproduce this issue?
Thank you

**Comment by jchenx2** [comment]
i'm sorry,i have no reproduce step,only happen once
$ flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:/Users/jchenx2/AppData/Local/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:/Users/jchenx2/AppData/Local/Android/sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.47.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • azalea (mobile) • DP000071 • android-arm • Android 7.1.2 (API 25)

• No issues found!

**Comment by kf6gpe** [comment]
@jchenx2 Do you have a minimal reproducible case we can use to debug this? Thanks!

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
