### ISSUE TITLE
Flutter inspector not opening...

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [flutter/flutter#69936]
It just shows this dialogue when I try opening flutter inspector...
![image](https://user-images.githubusercontent.com/67002144/98322175-d464bc00-200c-11eb-8d5b-85a9ed7509fd.png)

**Comment by sidrao2006** [comment]
Hey @,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with the intelliJ plugin, please close this issue and open it [here](https://github.com/flutter/flutter-intellij/issues) instead.

Thanks
