### ISSUE TITLE
Can not Build apk correctly

### ISSUE THREAD

**Issue by ShengjieGeng** [flutter/flutter#69942]
Hi，I could not get the newest changed apk every time run 'flutter build apk'.
But， it will generate correctly unless  deleting the build directory before building.
Below is my computer environment：
![image](https://user-images.githubusercontent.com/18364968/98350885-e79c7980-2056-11eb-926a-b2d228890b9d.png)

**Comment by pedromassangocode** [comment]
Hi @ShengjieGeng 
How are you verifying that the `.apk` didn’t changed?
Can you run (making sure you have an existing `apk` in the build folder) `flutter build apk -v` and provide the output?
Thank you

**Comment by ShengjieGeng** [comment]
> Hi @ShengjieGeng
> How are you verifying that the `.apk` didn’t changed?
> Can you run (making sure you have an existing `apk` in the build folder) `flutter build apk -v` and provide the output?
> Thank you

Hi，
AndroidStudio  analyzes the apk to check the versionName, and found that it is the old verionName.
I just run 'flutter build apk -v', which generated the newest apk correctly.
thank you very much.
PS:
Normally, I will click Android Studio's menu bar:  build->flutter->build apk

**Comment by pedromassangocode** [comment]
Hi @ShengjieGeng 
Just to make sure, did you solved the issue?

**Comment by ShengjieGeng** [comment]
> Hi @ShengjieGeng
> Did you solved the issue?

Yes,absolutely.

**Comment by pedromassangocode** [comment]
Hi @ShengjieGeng 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
