### ISSUE TITLE
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#69943]
After I added MethodChannel on Android, it reported an error, The addition is as follows.
![image](https://user-images.githubusercontent.com/24307960/98351579-d869fb80-2057-11eb-80d5-e96c8ef4660f.png)

The following is the error:
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked

**Comment by pedromassangocode** [comment]
Hi @mulieli 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

My code sample I mean the Android side (that I can copy/paste) and the dart code as well.

Thank you

**Comment by mulieli** [comment]
Thank you , 

> Hi @mulieli
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> 
> My code sample I mean the Android side (that I can copy/paste) and the dart code as well.
> 
> Thank you

Thank you
The reason for this error is that there is a problem with my code writing, I have found the correct way to write it
