### ISSUE TITLE
Adding GoogleMap widget is causing Android 10 device to restart. 

### ISSUE THREAD

**Issue by snrweb** [flutter/flutter#69945]
```
It keeps restarting the physical android phone after successful installation. The phone is running on android 10. The app runs if i remove this `GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),`

The app works perfectly fine with on lower android version i.e android 9 downward

[repo link](https://github.com/snrweb/transport)


`lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
I/nsport_app_use( 9632): Background young concurrent copying GC freed 21653(1229KB) AllocSpace objects, 10(488KB) LOS objects, 14% free, 4104KB/4778KB, paused 7.123ms total 298.276ms
I/System.out( 9632): [okhttp]:check permission begin!
I/System.out( 9632): [okhttp]:not MMS!
I/System.out( 9632): [okhttp]:not Email!
I/System.out( 9632): [OkHttp] sendRequest<<
I/nsport_app_use( 9632): Background concurrent copying GC freed 21153(823KB) AllocSpace objects, 12(576KB) LOS objects, 49% free, 3617KB/7234KB, paused 3.196ms total 116.370ms
V/FA      ( 9632): Inactivity, disconnecting from the service
Connecting to VM Service at ws://127.0.0.1:51892/WupUculXlGg=/ws
I/GED     ( 9632): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/BufferQueue( 9632): [unnamed-9632-0](this:0x87970000,id:0,api:0,p:-1,c:-1) BufferQueue core=(9632:com.example.transport_app_user)
W/nsport_app_user( 9632): type=1400 audit(0.0:21223): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=8178 scontext=u:r:untrusted_app:s0:c100,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
W/nsport_app_user( 9632): type=1400 audit(0.0:21224): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=8178 scontext=u:r:untrusted_app:s0:c100,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    ( 9632): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer( 9632): [unnamed-9632-0](this:0x87970000,id:0,api:0,p:-1,c:9632) connect(C): consumer=(9632:com.example.transport_app_user) controlledByApp=true
E/libc    ( 9632): Access denied finding property "vendor.debug.bq.dump"


W/nsport_app_user( 9632): type=1400 audit(0.0:21225): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=8178 scontext=u:r:untrusted_app:s0:c100,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/BufferQueueConsumer( 9632): [unnamed-9632-0](this:0x87970000,id:0,api:0,p:-1,c:9632) setConsumerName: unnamed-9632-0
E/libc    ( 9632): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:0,p:-1,c:9632) setConsumerName: SurfaceTexture-0-9632-0
I/BufferQueueConsumer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:0,p:-1,c:9632) setDefaultBufferSize: width=720 height=1380
E/GraphicExt( 9632): GraphicExtModuleLoader::CreateGraphicExtInstance false
I/zzbz    ( 9632): Making Creator dynamically
I/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) connect(P): api=1 producer=(1738:???) producerControlledByApp=false
W/Gralloc3( 9632): allocator 3.x is not supported
E/ion     ( 9632): ioctl c0044901 failed with code -1: Invalid argument
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
I/DynamiteModule( 9632): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule( 9632): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule( 9632): Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0


D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
D/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) cancelBuffer: slot 0
I/Google Maps Android API( 9632): Google Play services client version: 12451000
I/Google Maps Android API( 9632): Google Play services package version: 203915033
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)


W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)


W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/nsport_app_use( 9632): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)

E/OpenGLRenderer( 9632): Display event receiver pipe was closed or an error occurred.  events=0x9
W/SurfaceComposerClient( 9632): ComposerService remote (surfaceflinger) died [0x9b134280]
I/BufferQueueProducer( 9632): [SurfaceTexture-0-9632-0](this:0x87970000,id:0,api:1,p:1738,c:9632) disconnect(P): api 1
Lost connection to device.
Exited (sigterm)

`
```

**Comment by WojuadeAA** [comment]
can you try the app on another phone?

**Comment by snrweb** [comment]
> can you try the app on another phone?

@WojuadeAA it works on android 5/lollipop but not on android 10

**Comment by WojuadeAA** [comment]
@snrweb which SDK platform did you develop the app on?

**Comment by snrweb** [comment]
> @snrweb which SDK platform did you develop the app on?

@WojuadeAA `minSdkVersion 20
        targetSdkVersion 30`

**Comment by darshankawar** [comment]
@snrweb 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by snrweb** [comment]
> flutter doctor -v

`[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.959], locale en-GB)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (8 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Oluwatobi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Oluwatobi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Nokia 2 3 (mobile) • PT99621AA19B1400661 • android-arm • Android 10 (API 29)

! Doctor found issues in 2 categories.`

**Comment by snrweb** [comment]
> @snrweb
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

this is the repo lin [https://github.com/snrweb/transport](url)

and intentionally removed the map api keys

**Comment by darshankawar** [comment]
@snrweb I cloned your repo but is complaining about google services json which I see is empty.
Can you just provide a minimal complete reproducible code sample that only involves Google Maps flutter plugin that'll help to replicate the issue ?

**Comment by snrweb** [comment]
> @snrweb I cloned your repo but is complaining about google services json which I see is empty.
> Can you just provide a minimal complete reproducible code sample that only involves Google Maps flutter plugin that'll help to replicate the issue ?

{
  "project_info": {
    "project_number": "719360737864",
    "firebase_url": "https://transportapp-288804.firebaseio.com",
    "project_id": "transportapp-288804",
    "storage_bucket": "transportapp-288804.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:719360737864:android:0ad81d7874363180c3ce7d",
        "android_client_info": {
          "package_name": "com.example.transport_app_user"
        }
      },
      "oauth_client": [
        {
          "client_id": "719360737864-oud2s6h1hu63eklo58n5pdnk2l7m10fr.apps.googleusercontent.com",
          "client_type": 1,
          "android_info": {
            "package_name": "com.example.transport_app_user",
            "certificate_hash": "942c19624ceac3acb77f6bdafc5a447b922ec857"
          }
        },
        {
          "client_id": "719360737864-vovvooag70ln9ahrdrcr6kesmm55si11.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "AIzaSyD5mis8ZKoW*****"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "719360737864-vovvooag70ln9ahrdrcr6kesmm55si11.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}

**Comment by darshankawar** [comment]
I see the maps loading properly and the phone didn't restart. I am on Samsung S10+ device.

![69945](https://user-images.githubusercontent.com/67046386/98359917-f121e380-204e-11eb-97d9-1ff51d6e49c5.png)

From your log, it says:

`E/OpenGLRenderer( 9632): Display event receiver pipe was closed or an error occurred.`

Is it happening consistently when you have GoogleMaps ? And not when you remove it?
Is it only happening with Google Maps or with other plugins too ?

**Comment by snrweb** [comment]
> I see the maps loading properly and the phone didn't restart. I am on Samsung S10+ device.
> 
> ![69945](https://user-images.githubusercontent.com/67046386/98359917-f121e380-204e-11eb-97d9-1ff51d6e49c5.png)
> 
> From your log, it says:
> 
> `E/OpenGLRenderer( 9632): Display event receiver pipe was closed or an error occurred.`
> 
> Is it happening consistently when you have GoogleMaps ? And not when you remove it?
> Is it only happening with Google Maps or with other plugins too ?

It doesn't crash when i remove GoogleMaps.
And it doesn't happen with other plugin. 
The app crashes and phone restarts the moment i add the GoogleMap widget

**Comment by darshankawar** [comment]
@snrweb 
Can you try couple of things: 

1.  Add below in manifest and try again to see if issue persists.

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/> `

2. If above doesn't solve issue, remove that manifest entry, try by setting `targetsdkversion` to 29 and check on same device again.

**Comment by snrweb** [comment]
> @snrweb
> Can you try couple of things:
> 
> 1. Add below in manifest and try again to see if issue persists.
> 
> `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/> `
> 
> 1. If above doesn't solve issue, remove that manifest entry, try by setting `targetsdkversion` to 29 and check on same device again.

I did a flutter clean and applied the solutions you suggested and the error still persists. Phone restarts and the same error log

**Comment by darshankawar** [comment]
I am unable to replicate this issue since it works at my end on Android 10 device using latest stable version. Keeping this issue open for further analysis.

**Comment by snrweb** [comment]
The map finally worked after I did a proper restart

**Comment by carlosyenh** [comment]
I solved a similar problem on a Samsung A01 device running Android 10 by adding the following two permissions and also adding try - catch in all my functions related to the GoogleMapsFlutter widget
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
It works for me y hope it can help someone.
