### ISSUE TITLE
Rotating device displays flash of incorrectly scaled content

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#6995]
On iOS simulator (iOS 8.4, XCode 8.1), display flutter app UI and then rotate from portrait to landscape.

expected: smooth transition (dissolve or fade through) from portrait to landscape layout.
actual: brief flash of old UI stretched to the new orientation, before correctly laid-out new UI is shown.

**Comment by eseidelGoogle** [comment]
@chinmaygarde knows these sorts of things. :)

**Comment by cbracken** [comment]
Looks like we need to expose better support for `viewWillTransitionToSize:withTransitionCoordinator:` in `FlutterViewController`.

**Comment by tvolkert** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/16322, which contains more detail.
