### ISSUE TITLE
[AppStore build upload] ITMS-90853 Invalid Font

### ISSUE THREAD

**Issue by swiftbacon** [flutter/flutter#69961]
Hello guys, I have issue when I want to upload new build to TestFlight.

ITMS-90853: Invalid font - There was an error validating the font at 'Runner.app/Frameworks/App.framework/flutter_assets/packages/open_iconic_flutter/assets/open-iconic.woff'. Font not supported by platform.

Can You give me some tips. I make "flutter clean", I have latest Flutter version.

I try to change this file to .ttf but this is Dart Packages framework and after build its back to woff. Cupertiono_icons and Chewie use this.

Is this possible that adding Home Widget writing in swiftUI generate this problem?

**Comment by darshankawar** [comment]
@swiftbacon 
.woff fonts are not supported by the platform as also mentioned in the error. You may need to use the .tff equivalent of the font and try again.  See [this](https://github.com/flutter/flutter/issues/13823) issue for more details.

Closing this as non-issue from Flutter framework.
