### ISSUE TITLE
Need a null safety version of cupertino icons

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#69963]
I don't see one here:
https://pub.dev/packages/cupertino_icons/versions

Given this is in the `flutter create` template, it would mean that `flutter create` + `dart migrate` will fail with no possible migration.

**Comment by mit-mit** [comment]
cc @zanderso

**Comment by zanderso** [comment]
@xster ptal

**Comment by zanderso** [comment]
@mit-mit Could you please describe more specifically what needs to be done here.

**Comment by xster** [comment]
Do you specifically mean https://github.com/flutter/cupertino_icons the package and not https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/icons.dart the SDK class right? What does https://github.com/flutter/cupertino_icons  need to be a "null safety version"? There's no Dart code in that package.

**Comment by mit-mit** [comment]
I mean the package that's on https://pub.dev/packages/cupertino_icons/

All I think you need to do, is to update https://github.com/flutter/cupertino_icons/blob/master/pubspec.yaml#L14 to have `sdk: ">=2.12.0-0 <3.0.0"` (note the `-0` after 12.0). I'm about to go offline so cc @natebosch @jakemac53 in case there are follow-up questions.

**Comment by xster** [comment]
Sorry, I'm not entirely looped in in the nnbd context. What's the end goal? For all packages past a certain Flutter SDK version to use exclusively packages with sdk constraints past a Flutter SDK version? 

i.e. you're saying I should push a new cupertino_icons 1.0.1 with new constraints and then change the Flutter SDK's create template to consume cupertino_icons 1.0.1?

**Comment by jakemac53** [comment]
Just changing the constraints should do it. The issue is that pub will complain today if the package is not opted in even if it has no Dart files at all.

Opting in the package with the sdk constraint of `>=2.12.0-0 <3.0.0`, publishing, and updating the template to use that version will fix the erroneous pub warning that users see.

**Comment by xster** [comment]
Slight tangential question: how come I don't see that constraint being applied to our first party plugins in the plugins repository?

**Comment by jakemac53** [comment]
It should be soon, everything migrated to null safety should have that constraint going forward (at least until 2.12.0 stable is released)

**Comment by xster** [comment]
`Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
  See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases.`

umm this seems like a relevant issue. Any recommendations? I think having pre-release version usages in the Flutter SDK itself causes downstream test failures too.

**Comment by jakemac53** [comment]
Assuming this package doesn't actually rely on anything from the dev SDK you can just publish as stable safely and ignore the warning.

**Comment by mit-mit** [comment]
Confirmed working, yay:

```
flutter create f90
cd f90
dart migrate --apply-change
flutter analyze
```

=> no errors.

Thanks @xster
