### ISSUE TITLE
Flutter should provide a way to block the GPU rendering pipeline if the embedder says to

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#69968]
I have not yet looked into this on the Metal or Vulkan backends, so using the GL backend as an example. At any rate, I'm assuming the Skia `GrDirectContext::flushAndSubmit(true)` call is portable between them.

Today, when we submit a frame on the GL backend, we flush the Skia canvas but we do not necessarily block on all GL commands finishing (i.e. by calling `context_->flushAndSubmit(true)` or otherwise invoking `glFinish()`). This saves us some time during frame rendering, but may allow for the GPU driver to allocate more memory than we absolutely currently need to display the scene, since we are potentially starting new GL based work before the current scene's commands have finished.

Local testing of adding this to the gpu_surface_gl.cc reduces memory spikes when undergoing fast/heavy animations:

```diff
diff --git a/shell/gpu/gpu_surface_gl.cc b/shell/gpu/gpu_surface_gl.cc
index a539c985706..0b677f9399b 100644
--- a/shell/gpu/gpu_surface_gl.cc
+++ b/shell/gpu/gpu_surface_gl.cc
@@ -281,6 +281,11 @@ bool GPUSurfaceGL::PresentSurface(SkCanvas* canvas) {
     onscreen_surface_->getCanvas()->flush();
   }
 
+  {
+    TRACE_EVENT0("flutter", "GrDirectContext::flushAndSubmit");
+    context_->flushAndSubmit(true);
+  }
+
   if (!delegate_->GLContextPresent(fbo_id_)) {
     return false;
   }
```

On a macOS desktop application running on a fairly high end MacBook Pro, this adds ~2-3 ms per frame. We should not do this by default, but it may be helpful on memory constrained platforms at times where memory is running low, to avoid getting OOM killed by the OS.

/cc @chinmaygarde @zanderso @jason-simmons @bsalomon @liyuqian

**Comment by chinmaygarde** [comment]
Closing as WAI. We want the CPU to do work concurrently with the GPU. We have the pipeline to make sure we don't generate too many frames for the GPU already.

**Comment by zanderso** [comment]
@chinmaygarde can you clarify whether adjusting the pipeline is the right way for @dnfield to solve the problem that he's facing, and if so give a pointer to where to do that?

**Comment by dnfield** [comment]
This is more about slowing down under low memory conditions. Is there a way to do that with the pipeline today/

**Comment by chinmaygarde** [comment]
> This is more about slowing down under low memory conditions.

You can work with the VSync with reduce the frame rate by rendering at every n'th frame interval to reduce the frame rate but still keep the frames aligned to vsync.

But, I would like to understand what memory savings you are observing by doing this. Stalling the CPU to save memory doesn't add up.

**Comment by liyuqian** [comment]
I think our pipeline is only to coordinate UI and raster threads so the former won't generate too many frames for the latter if it's behind. Regardless of adding Dan's `flushAndSubmit` or not, I think the CPU and GPU will continue to do the work concurrently.

What Dan did here seems to be just on the raster thread. With or without the pipeline, the raster thread can only handle one frame at a time. Previously, `SkCanvas::flush` is called on that thread, which I believe is used to ensure that the GPU work is finished before another frame is handled on raster thread. However, Dan's experiment seems to suggest the GPU work could still overlap with `flush`. The only way to truly have GPU handle one frame at a time is by calling `flushAndSubmit `. It has speed cost, and a memory benefit.

**Comment by dnfield** [comment]
SkCanvas::flush does not seem to do as much work as `flushAndSubmit(true)`. It might be worth seeing if we can just replace the canvas flush with a flushAndSubmit and whether that has any detriment time-wise.

**Comment by dnfield** [comment]
I'm trying to create as reduced a test case as I can, although I think the easiest way to trigger it is using Flare. I'll try to come up with a shareable example for Monday. @chinmaygarde - in the mean time I'm going to reopen this so I don't lose track. I'll assign it to myself and we can hopefully figure out a way to resolve what I'm seeing (whether it's using this specific method or not).

**Comment by dnfield** [comment]
I am no longer able to reproduce this - I thought at first it was because my "minimal" example wasn't enough, but I can't get it even with examples where I saw it before.

If I can get a reproduction for this, I'll re-open.

**Comment by zanderso** [comment]
Closing based on @dnfield's last comment.

**Comment by dnfield** [comment]
(whups, hit the comment button instead of the close haha)
