### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by TejasG-007** [flutter/flutter#69977]
After uploading code successful on server its take too much time to load site and sometime it wont appear until we refresh the page will always have to wait while site display.

**Comment by hamdikahloun** [comment]
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal complete reproducible code sample?

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
