### ISSUE TITLE
iOS builds broken

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6997]
`flutter run --no-hot`
`flutter run --hot`
`flutter build ios --simulator`

All yield a crashing app.

https://gist.github.com/tvolkert/dad97e6a01b1928009765acaf33ff350

The important bit is:

```
[        ] [DEVICE LOG] Nov 22 20:57:56 tvolkert-macbookpro3 Runner[56726]: [INFO:../../flutter/shell/gpu/gpu_surface_gl.cc(87)] 
[        ] [INFO:../../flutter/shell/gpu/gpu_surface_gl.cc(86)] Failed to setup GL context. Aborting.
```
Crash report here: https://gist.github.com/tvolkert/cbc5efeee99f8571d679478b0d1c545e

**Comment by eseidelGoogle** [comment]
@chinmaygarde

**Comment by eseidelGoogle** [comment]
I wonder if this is causing https://github.com/flutter/flutter/pull/6969?
