### ISSUE TITLE
Exit when create flutter project with OS Error: Access is denied. , errno = 5

### ISSUE THREAD

**Issue by DTharaka** [flutter/flutter#69978]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by hamdikahloun** [comment]
Hi @DTharaka 

Can you please provide your `flutter create -v newapp` .

Thank you

**Comment by hamdikahloun** [comment]
Hi @DTharaka 

Can you please provide the full log of your `flutter build -v apk --debug` and your ` flutter doctor -v` too .

Thank you

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/flutter/issues/69116
