### ISSUE TITLE
We should coordinate Shell::NotifyLowMemoryWarning with systemChannel memoryPressure

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#69973]
Today, each embedder has to both call `Shell::NotifyLowMemoryWarning` (which in turn calls `Dart_NotifyLowMemory`), and also send a platform message to the framework about memory pressure.

The problem with this is that both of these trigger asynchronous messages that result in freeing memory, but the order matters.

For example, if the Dart isolate processes the low memory notification before the framework, it may trigger collection and heap compaction, followed by application code letting go of more objects _without triggering another GC_. This can be really bad if, e.g., a nearly full application cache is cleared right after a GC, and no GC is run again, making the process memory stay high.

For images, this should be taken care of now that `dispose` gets called on them if they're really not being used, but other caches will suffer from this.

We could probably improve this by either waiting to call `Dart_NotifyLowMemory` after a response from the framework `memoryPressure` message, or calling it again after the response.

/cc @rmacnak-google @chinmaygarde @liyuqian @xster

**Comment by chinmaygarde** [comment]
Today, the routines for sending the platform messages for the low memory signal are in the various embedders. You can move this to `Shell::NotifyLowMemoryWarning` and attach a response handle to the message in which you call `Dart_NotifyLowMemory`. That call does not require isolate scope and can be called on any thread as long as there is a running VM. Attempt acquiring a VM ref in the callback before making the call.
