### ISSUE TITLE
pub null-safety analysis fails on sky_engine

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69981]
```
jonahwilliams-macbookpro2:flutter jonahwilliams$ flutter pub get
Downloading package sky_engine...                                  344ms
Downloading flutter_patched_sdk tools...                           732ms
Downloading flutter_patched_sdk_product tools...                   509ms
Downloading darwin-x64 tools...                                  1,060ms
Downloading darwin-x64/font-subset tools...                        289ms
Could not decide if this package resolution is fully migrated to null-safety:
                                                                        
Could not analyze package:sky_engine/ui/window.dart.                    
Running "flutter pub get" in flutter...               
```

**Comment by jonahwilliams** [comment]
pub probably shouldn't try to analyze sky_engine, or should adjust the heuristics so that they work for it

**Comment by zanderso** [comment]
@mit-mit @leafpetersen

**Comment by leafpetersen** [comment]
cc @jonasfj

**Comment by jonasfj** [comment]
@jonahwilliams can you add the dart version being used here?

**Comment by jonasfj** [comment]
I agree, we should avoid looking at SDK dependencies.. I was just patching `pub outdated` to do this earlier today (still on review).

**Comment by jonahwilliams** [comment]
This is ToT, Dart SDK version: 2.12.0-27.0.dev (dev) (Fri Nov 6 06:09:09 2020 -0800) on "macos_x64"

**Comment by tvolkert** [comment]
Just ran into this at 8e7748e74c1454edad6caa3e418db82a9f332680

**Comment by jonasfj** [comment]
Ah, as I suspected this is the null-safety warning we removed Friday, but failed to roll to Flutter, see https://github.com/flutter/flutter/issues/70013#issuecomment-723892022.

**Comment by mit-mit** [comment]
I think this is working now that we rolled to dev.28; @jonahwilliams can you confirm?

**Comment by jonahwilliams** [comment]
I don't see this on hello_world, will check on the gallery once it relands

**Comment by pcsosinski** [comment]
any update here?

**Comment by jonahwilliams** [comment]
This is fixed
