### ISSUE TITLE
Snap package does not expose the Dart SDK on Linux

### ISSUE THREAD

**Issue by Szaki** [flutter/flutter#69985]
Despite what [flutter.dev](https://flutter.dev/docs/get-started/install/linux) says about the Dart SDK, it is not available from the Flutter SDK when it is installed via Snappy.

## Steps to Reproduce

1. Install the Flutter SDK as a snap package.
2. Try to run `dart`.

## Logs

```
% dart
zsh: command not found: dart
% which flutter dart
/snap/bin/flutter
dart not found
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.3 at /home/szaki/snap/flutter/common/flutter
    • Framework revision 8874f21e79 (8 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/szaki/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
For issues with the flutter snap please file here: https://github.com/canonical/flutter-snap/issues

**Comment by TahaTesser** [comment]
Hi @Szaki 
As mentioned above, please file an issue on  https://github.com/canonical/flutter-snap/issues  [Reference](https://github.com/flutter/flutter/issues/63325#issuecomment-672371502)
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by iapicca** [comment]
> For issues with the flutter snap please file here: https://github.com/canonical/flutter-snap/issues

https://github.com/canonical/flutter-snap/issues/16
