### ISSUE TITLE
Stocks example: 404 on resolving image assets

### ISSUE THREAD

**Issue by tobrun** [flutter/flutter#7]
When running the sample application, material icons seem to be missing from the UI

![device-2015-05-01-204028](https://cloud.githubusercontent.com/assets/2151639/7435261/6033a1f2-f042-11e4-996c-b44165f971af.png)

Verifying the output in the terminal, I noticed the lines with a 404 code:

![screen shot 2015-05-01 at 20 35 06](https://cloud.githubusercontent.com/assets/2151639/7435277/835d45c0-f042-11e4-9f2a-80901c245059.png)

I went to check the mentioned paths and they were indeed non-exisitent. I stumbled on this [python script](https://github.com/domokit/mojo/blob/master/sky/sdk/packages/sky/lib/download_material_design_icons) to download the assets. In the screenshot below you can see the result after execution:

![screen shot 2015-05-01 at 20 48 45](https://cloud.githubusercontent.com/assets/2151639/7435378/88bfc168-f043-11e4-9254-bb5277d255f7.png)

Running the application and remove/reinstalling the application resulted in the same 404 messages.

**Comment by tobrunvannuland** [comment]
I noticed that the path mentioned in terminal is not the same as path of the resource:

packages/sky/**lib**/assets/material-design-icons/navigation/2x-web

Versus

/packages/sky/assets/material-design-icons/navigation/2x-web

**Comment by abarth** [comment]
@eseidelGoogle: Would you be willing to take a look at this on issue?

**Comment by abarth** [comment]
You might want to try running this script: https://github.com/domokit/sky_sdk/blob/master/packages/sky/lib/download_material_design_icons

**Comment by tobrunvannuland** [comment]
To be sure I did a new test today: 
- clean git clone of sky sdk 
- took the steps form README.md to get the stocks example running
- noticed that the icons were missing
- invoked the script @abarth mentioned
- removed and clean installed the application

I'm seeing this output:

![screen shot 2015-05-03 at 10 33 27](https://cloud.githubusercontent.com/assets/2151639/7444396/89c4ae50-f180-11e4-84d8-4025a464f794.png)

When verifying the path I'm seeing no files in the assets folder:

![screen shot 2015-05-03 at 10 34 17](https://cloud.githubusercontent.com/assets/2151639/7444400/9e3f3828-f180-11e4-8240-d82059490804.png)

**Comment by abarth** [comment]
We've addressed this issue by introducing an FLX file that contains all the assets your app needs.
