### ISSUE TITLE
Canvas constructor crashes with bad arguments

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#70]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:25 GMT_
_Originally opened as https://github.com/flutter/engine/issues/23_

----

_From @Hixie on July 15, 2015 21:0_

My reading of the Canvas constructor is that it'll crash if you call it with a null first argument.
The comment also explicitly says that it'll crash if you call it with a PictureRecorder in the wrong state.

The APIs the C++ expose to the Dart code should never be able to crash the app.

_Copied from original issue: domokit/mojo#326_

**Comment by sethladd** [comment]
Is this still an issue?

**Comment by Hixie** [comment]
The first case listed here is fixed. The second is also filed as https://github.com/flutter/flutter/issues/2531, so I'll close this one.
