### ISSUE TITLE
Add newer iOS devices to devicelab

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70004]
According to the devicelab hardware spreadsheet, the newest device is an iPhone 6s (though we had an iPhone X at some point).  Ideally smoke tests would be run on every generation of iPhones to at least confirm `flutter run` works.

**Comment by jmagman** [comment]
For example, I added [engine logic](https://github.com/flutter/engine/pull/22377) that will only run on `arm64e` devices, and we have no devices from that 2018 or later when that architecture was introduced.

**Comment by godofredoc** [comment]
Can you please recommend which phone version to add?

**Comment by jmagman** [comment]
iPhone 11 works for now, though it would be awesome to have smoke tests running on each generation of iPhones.  😄

**Comment by godofredoc** [comment]
Given that we need to add redundancy(at least two phones per version) we only may be able to accommodate a max of 3 versions in total: 6s, .. 11.

**Comment by jmagman** [comment]
@godofredoc Fair enough.  2 iPhone 11s would be great then.  And maybe next year we replace with 2 iPhone 12s, etc.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
