### ISSUE TITLE
[arm32] libapp.so support hard floating arm target?

### ISSUE THREAD

**Issue by thatsBlinc** [flutter/flutter#70009]
the term "armeabi" in flutter indicate softfp architecture?  whatif we wish to ship to a hard floating  target?

**Comment by darshankawar** [comment]
@thatsBlinc 
Check [this](https://github.com/flutter/flutter/issues/26773) issue and underlying comments to know about hard floating targets and see if it answers your question.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
