### ISSUE TITLE
Proposal to add border radius attribute to CheckBox widget.

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#70003]
In most cases, users might want rounded corner radius of checkbox

**Comment by yash1200** [comment]
Maybe `shape` property can help you.

**Comment by jinfagang** [comment]
@yash1200 Where do u found a `shape` in Checkbox widget.

**Comment by yash1200** [comment]
I'm sorry, I checked checkboxListTile by mistake.

**Comment by sayannath** [comment]
Even the shape does not make the checbox round in CheckBoxListTile

**Comment by hisnameispum** [comment]
@sayannath Check out this Pub. https://pub.dev/packages/roundcheckbox

**Comment by gotlostinparadise** [comment]
> Even the shape does not make the checkbox round in CheckBoxListTile. How to make the checkbox rounded in CheckBoxListTile.

This worked out for me.

```dart
Theme(
  data: ThemeData(
          checkboxTheme: CheckboxThemeData(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(5),
            ),
          ),
        ),
  child: your_checkbox_widget()
);
```
