### ISSUE TITLE
pub get slows down dramatically after updating package to null safety

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#70013]
On the old flutter gallery at 52d49fb358f591318801eab2b219b58612d9eac3

```
jonahwilliams-macbookpro2:flutter_gallery jonahwilliams$ time flutter pub get
Running "flutter pub get" in flutter_gallery...                    575ms

real	0m1.611s
user	0m1.739s
sys	0m0.379s
```

at f9b69bb5aa0b92429d349fa0aab527037b92586b

```time flutter pub get
jonahwilliams-macbookpro2:flutter_gallery jonahwilliams$ time flutter pub get
Could not decide if this package resolution is fully migrated to null-safety:
                                                                        
Could not analyze package:flutter_web_plugins/src/navigation/utils.dart.
Running "flutter pub get" in flutter_gallery...                     5.4s

real	0m6.404s
user	0m8.660s
sys	0m1.030s
```

**Comment by jonahwilliams** [comment]
@jonasfj @mit-mit

**Comment by tvolkert** [comment]
@jonasfj do we know what's causing this?

**Comment by jonasfj** [comment]
Not entirely sure, yet... We made a lot of small changes to pub, but we're investigating.

**Comment by sigurdm** [comment]
It seems that you get a warning that null-safety could not be decided.

That probably is what took the time. It loads all the code in the import graph to check if there are any opt-out markers.

We ended up removing that check in https://github.com/dart-lang/pub/commit/332ea049c75a9616b9984a722dee80ee5899995a .

That has been rolled with: https://dart-review.googlesource.com/c/sdk/+/170690 .
That should have rolled to engine already.

**Comment by jonasfj** [comment]
Seems engine rolls are failing in #70039 due to missing SDK constraints in `pubspec.yaml` (see https://github.com/dart-lang/sdk/issues/44072), with a fix coming in https://github.com/flutter/flutter/pull/70078 adding missing SDK constraints to Flutter.

**Comment by mit-mit** [comment]
@jonahwilliams can you please try again now that we rolled to dart dev.28 ?

**Comment by jonahwilliams** [comment]
I do not see this on hello_world anymore, will need to re-check on gallery once it relands but seems back to normal

**Comment by jonahwilliams** [comment]
This is fixed
