### ISSUE TITLE
Cloud DefaultTabController support onTabChanged event

### ISSUE THREAD

**Issue by wangbo4020** [flutter/flutter#70019]
## Use case

```dart
DefaultTabController(length: 5, child: child, onChanged: (index) {
  // do something
})
```

## Proposal
  1.22.0 is not support

**Comment by iapicca** [comment]
@wangbo4020 

please consider using the code below to achieve this feature
you can try it on [dartpad](https://dartpad.dartlang.org/db0c502d76fa543ed728a2b8001db548)

<details><summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  static const _myTabs = <Tab>[
    Tab(text: 'left'),
    Tab(text: 'right'),
  ];

  @override
  Widget build(BuildContext context) => DefaultTabController(
      length: _myTabs.length,
      child: OnChangeWidget(
        onChange: (int i) => print('index: $i'),
        child: Scaffold(
          appBar: AppBar(bottom: const TabBar(tabs: _myTabs)),
          body: TabBarView(
            children: [
              for (Tab t in _myTabs)
                Center(child: Text('This is the ${t.text}} tab'))
            ],
          ),
        ),
      ));
}

class OnChangeWidget extends StatelessWidget {
  const OnChangeWidget({@required this.child, this.onChange})
      : super(key: const Key('OnChangeWidget'));
  final Widget child;
  final void Function(int) onChange;
  @override
  Widget build(BuildContext context) {
    final _controller = DefaultTabController.of(context);
    if (onChange != null) {
      _controller.addListener(() {
        if (_controller.indexIsChanging) {
          onChange(_controller.index);
        }
      });
    }
    return child;
  }
}
```
</details>

**Comment by wangbo4020** [comment]
> @wangbo4020
> 
> please consider using the code below to achieve this feature
> you can try it on [dartpad](https://dartpad.dartlang.org/db0c502d76fa543ed728a2b8001db548)
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp() : super(key: const Key('MyApp'));
> 
>   @override
>   Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
> }
> 
> class MyHomePage extends StatelessWidget {
>   const MyHomePage() : super(key: const Key('MyHomePage'));
> 
>   static const _myTabs = <Tab>[
>     Tab(text: 'left'),
>     Tab(text: 'right'),
>   ];
> 
>   @override
>   Widget build(BuildContext context) => DefaultTabController(
>         length: _myTabs.length,
>         child: OnChangeWidget(
>           onChange: (int i) => print('index: $i'),
>           child: Scaffold(
>             appBar: AppBar(title: const TabBar(tabs: _myTabs)),
>             body: TabBarView(
>               children: [
>                 for (Tab t in _myTabs)
>                   Center(child: Text('This is the ${t.text} tab'))
>               ],
>             ),
>           ),
>         ),
>       );
> }
> 
> class OnChangeWidget extends StatelessWidget {
>   const OnChangeWidget({@required this.child, this.onChange})
>       : super(key: const Key('OnChangeWidget'));
>   final Widget child;
>   final void Function(int) onChange;
>   @override
>   Widget build(BuildContext context) {
>     final _controller = DefaultTabController.of(context);
>     if (onChange != null) {
>       _controller.addListener(() {
>         if (_controller.indexIsChanging) {
>           onChange(_controller.index);
>         }
>       });
>     }
>     return child;
>   }
> }
> ```

Thanks
