### ISSUE TITLE
 Is it possible to modify the content of the index.html file when build flutter web？

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#70024]
How to modify the content of index.html when publishing the package, in the index.html file, reference external development and production js

**Comment by iapicca** [comment]
@stoneLee81  
this repository is dedicated to improve flutter with bug reporting and feature requests,
if you have question I recommend you to follow `I want help writing my application` tab
on the [new issues menu](https://github.com/flutter/flutter/issues/new/choose)
