### ISSUE TITLE
Bring up more build tests for Windows desktop

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70027]
The initial desktop integration tests are running now, but they need to be expanded beyond the initial gallery build test; filing this to make sure that planned work is captured in the issue tracker. This should be much more straightforward that getting the first one running was, since the bot work is all complete.

In particular we should ensure we are testing building a freshly created project to catch errors in template changes. (I haven't checked where that test lives on existing platforms; it may be a device lab test, which still needs desktop bring-up).

**Comment by yaakovschectman** [comment]
Limiting this bug to Windows only. Will create an additional issue for the same goal for Mac OS, but as their work will be done separately, we will want to be able to link code changes separately.

**Comment by a-wallen** [comment]
@yaakovschectman, here's the issue fork for `platform-mac` [flutter/flutter#109633](https://github.com/flutter/flutter/issues/109633)

**Comment by yaakovschectman** [comment]
Compilation and startup devicelab tests now up for Widnows.
