### ISSUE TITLE
Add error handling to the application template.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#70059]
## Use case

Create application from template.

## Proposal

It takes research and mental capacity to add error handling to a flutter application, i.e. in case of an unhandled error the app should do two things:

1. Show a nice screen with actionable message 
2. Report error to a logging system

As error handling is needed in any application exposed to end user, I suggest to include the code into application template.

**Comment by polina-c** [comment]
I created PR for this: https://github.com/flutter/flutter/pull/70043
Some tests fail for it. I have difficulties to locate the failing tests. Can somebody help, please?

**Comment by pedromassangocode** [comment]
Hi @polina-c 
You can always Google it and you will find lots of article out there.

We try to keep the template as simple as possible for many reasons and one of them is to make it simple for beginners.

There is a webpage that explains error handling in Flutter, see https://flutter.dev/docs/testing/errors.

**Comment by polina-c** [comment]
Then how about updating this page with example of custom error widget: 
https://github.com/flutter/website/pull/4973.

It it not easy to figure it out.
