### ISSUE TITLE
Multiple TextFormField with autovalidatemode.OnUserInteraction in a form will trigger all fields to validate on one click

### ISSUE THREAD

**Issue by TerrenceAddison** [flutter/flutter#70050]
I created a form that contains multiple textformfields and give them the autovalidatemode: AutoValidateMode.OnUserInteraction property and what happens is the moment I click any of the textformfield, all of the validation of the multiple textformfields will be triggered returning all the "empty field" errors. I am unsure if this is an intended feature or a bug which is why I decided to bring it up as an issue. I was expecting it for the validation to trigger when the particular field is selected, but what happen is that when any field is selected all fields are instantly triggered Sample code as below:

`

class RegisterForm extends StatefulWidget {
  RegisterForm({Key key}) : super(key: key);

  @override
  _RegisterFormState createState() =>
      _RegisterFormState();
}

class _RegisterFormState extends State<RegisterForm> {
  final _formKey = GlobalKey<FormState>();

  bool _enabledButton = false;
  TextEditingController emailController = TextEditingController();
  TextEditingController passwordController = TextEditingController();
  TextEditingController passwordVerificationController =
      TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Form(
        key: _formKey,
        onChanged: () =>
            setState(() => _enabledButton = _formKey.currentState.validate()),
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _rowUpdatableText("email", emailController, "cannot be empty"),
              _passwordText("password", passwordController, "cannot be empty"),
              _passwordVerifierText(
                  "re-enter password", passwordVerificationController, "cannot be empty"),
              Align(
                alignment: Alignment.center,
                child: FlatButton(
                    color: Color.fromRGBO(47, 43, 43, 1),
                    disabledColor: Color.fromRGBO(212, 212, 212, 1),
                    height: 48,
                    minWidth: 279,
                    onPressed: _enabledButton
                        ? () {
                            createUser();
                          }
                        : null,
                    child: Text(
                      "register",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w600,
                          fontSize: 16),
                    )),
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget _passwordText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        controller: controller,
        obscureText: true,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          } else if (value.length < 6 || value.length > 20) {
            return "greater than 6 but less than 20";
          }
          return null;
        },
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  Widget _passwordVerifierText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          } else if (value.length < 6 || value.length > 20) {
            return "密碼須為至少6位數，不可超過20位數";
          } else if (passwordVerificationController.text !=
              passwordController.text) {
            return "兩次密碼不相符";
          }
          return null;
        },
        controller: controller,
        obscureText: true,
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  Widget _rowUpdatableText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          }
          return null;
        },
        controller: controller,
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  void createUser() {
    _formKey.currentState.save();

  }
}

`

Apologies if there are any formatting error as this is only a snippet

**Comment by amanv8060** [comment]
<details><summary>Reproducible Code</summary>

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: RegisterForm(),
        ),
      ),
    );
  }
}

class RegisterForm extends StatefulWidget {
  RegisterForm({Key key}) : super(key: key);

  @override
  _RegisterFormState createState() => _RegisterFormState();
}

class _RegisterFormState extends State {
  final _formKey = GlobalKey<FormState>();

  bool _enabledButton = false;
  TextEditingController emailController = TextEditingController();
  TextEditingController passwordController = TextEditingController();
  TextEditingController passwordVerificationController =
      TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Form(
        key: _formKey,
        onChanged: () {
            setState(() => _enabledButton = _formKey.currentState.validate());},
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _rowUpdatableText("email", emailController, "cannot be empty"),
              _passwordText("password", passwordController, "cannot be empty"),
              _passwordVerifierText("re-enter password",
                  passwordVerificationController, "cannot be empty"),
              Align(
                alignment: Alignment.center,
                child: FlatButton(
                    color: Color.fromRGBO(47, 43, 43, 1),
                    disabledColor: Color.fromRGBO(212, 212, 212, 1),
                    height: 48,
                    minWidth: 279,
                    onPressed: _enabledButton
                        ? () {
                            createUser();
                          }
                        : null,
                    child: Text(
                      "register",
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w600,
                          fontSize: 16),
                    )),
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget _passwordText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        controller: controller,
        obscureText: true,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          } else if (value.length < 6 || value.length > 20) {
            return "greater than 6 but less than 20";
          }
          return null;
        },
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  Widget _passwordVerifierText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          } else if (value.length < 6 || value.length > 20) {
            return "密碼須為至少6位數，不可超過20位數";
          } else if (passwordVerificationController.text !=
              passwordController.text) {
            return "兩次密碼不相符";
          }
          return null;
        },
        controller: controller,
        obscureText: true,
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  Widget _rowUpdatableText(
      String labelText, TextEditingController controller, String errorMessage) {
    return Container(
      margin: EdgeInsets.only(top: 24),
      child: TextFormField(
        autovalidateMode: AutovalidateMode.onUserInteraction,
        validator: (value) {
          if (value.isEmpty) {
            return errorMessage;
          }
          return null;
        },
        controller: controller,
        decoration: InputDecoration(
          labelText: labelText,
          contentPadding: EdgeInsets.all(16.0),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }

  void createUser() {
    _formKey.currentState.save();
  }
}
```
</details>

The problem lies in the line
```
onChanged: () {
            setState(() => _enabledButton = _formKey.currentState.validate());},
```

you are validating the entire form on the change in any form element  . You need to remove that line .

**Comment by TerrenceAddison** [comment]
apologies! seems like it's an issue from my side thank you @amanv8060 !
