### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by PartapSBimrah** [flutter/flutter#70051]
Hey,

I am using Android Studio 4.1. I have also installed the flutter and dart plugins on my system. But when I run the "`flutter doctor`" command and show me this error. Please let me know. why it does happen. Right side you can see I have installed. But my left side CMD shows me that plugins are missing in it. 

![Screenshot (302)](https://user-images.githubusercontent.com/39325207/98464679-8e654f00-21ea-11eb-8630-7c750c737bec.png)

**Comment by Abhishek01039** [comment]
Hi @PartapSBimrah 
please restart cmd then try `flutter doctor -v`
Thanks.

**Comment by PartapSBimrah** [comment]
Thank you I check and let you know if have any problem.

**Comment by amanv8060** [comment]
Related #68180

**Comment by pedromassangocode** [comment]
Hi @PartapSBimrah 
This is just a warning, you can still use Flutter.
For more information see https://github.com/flutter/flutter/issues/67986.

Closing as this is not an issue with Flutter itself.
Thank you
