### ISSUE TITLE
Animation freezes after changing AppLifecycleState or rebuilding complex UI with PlatformView in iOS

### ISSUE THREAD

**Issue by mkc188** [flutter/flutter#70069]
Hi,

My app is using “google_maps_flutter 1.0.6” and “rubber 0.4.0” as the video shown below. 

![video](https://media.giphy.com/media/g3UsEfwKYpEX0GsXaF/giphy.gif)

00:00-00:12 Normal behaviour
00:13-00:44 The way to reproduce the bug. Since I have simplified the UI for illustration, it took me a little bit longer to reproduce it
00:45-01:07 Animation freezes and no longer responds to any taps

The spring animation of the bottom sheet stops when changing AppLifecycleState by going to the home screen or opening control center. Especially when there are heavy UI updates, such as the camera position of google maps is moving, the padding of google maps is changing, or calling setState() in different widgets. Besides that, the bottom sheet widget does not respond to any gestures when the animation freezes.

This bug occurs when using after Flutter 1.20.3 or after. Flutter 1.20.2 is fine. I found that it is due to PR#20708. 

https://github.com/flutter/engine/pull/20708

I have tried to use the code base of Flutter engine of 1.22.3 and revert the changes in PR#20708 to build the local engine, then the bug goes away.

Moreover, I have tried to use DraggableScrollableSheet, AnimationController and NotificationListener<DraggableScrollableNotification> instead of the rubber library. But the bug still occurs. If I show a dialog using showDialog() or navigating to different screens, the animation will be reset and it will no longer freeze.

**Comment by darshankawar** [comment]
@mkc188 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that we can use that will show the animation freeze.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by shreymahendru** [comment]
Reproducable code: 

`
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> _tapped = [];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox.expand(
        child: Stack(
          children: [
            GoogleMap(
              initialCameraPosition: CameraPosition(target: LatLng(43.6426, -79.3871), zoom: 12),
            ),
            DraggableScrollableSheet(
              maxChildSize: 0.95,
              minChildSize: 0.25,
              initialChildSize: 0.40,
              builder: (ctx, controller) => this._buildScrollView(ctx, controller),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildScrollView(BuildContext context, ScrollController controller) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Color(0x272c4141),
            offset: Offset(0, -6),
            blurRadius: 12,
            spreadRadius: 0,
          )
        ],
        borderRadius: BorderRadius.only(
          topRight: Radius.circular(40),
          topLeft: Radius.circular(40),
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.only(
          topRight: Radius.circular(40),
          topLeft: Radius.circular(40),
        ),
        child: CustomScrollView(
          controller: controller,
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) => ListTile(
                  title: Text("Tile number $index"),
                  selected: this._tapped.contains(index),
                  selectedTileColor: Colors.teal,
                  onTap: () => this._onListTileTapped(index),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _onListTileTapped(int index) {
    this.setState(() {
      this._tapped.add(index);
    });
  }
}
`

`flutter doctor -v`: 
`
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-CA)
    • Flutter version 1.22.4 at /Users/shreymahendru/sofdev/flutter/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shreymahendru/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 4a73f0279f94a695a6be7080c429e9bc1dfd5e04 • ios • iOS
      14.2
    ! Error: iPhone is busy: Copying cache files from device. Xcode will
      continue when iPhone is finished. (code -10)

! Doctor found issues in 1 category.
`
