### ISSUE TITLE
[ERROR:flutter/shell/common/shell.cc(209)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null.

### ISSUE THREAD

**Issue by oliwa01** [flutter/flutter#70062]
Yesterday I running My App in Flutter everything is fine when I use emulator in Android Studio 4.1, But when I Transfer to my Galaxy Note 8 ,  i get this error and my app .  it occurs when I try to save a png image generate in the app in the storage firebase. 

 ```
RenderRepaintBoundary renderRepaintBoundary = _containerKey.currentContext
        .findRenderObject();
    ui.Image boxImage = await renderRepaintBoundary.toImage(pixelRatio: 1.113);
    ByteData byteData = await boxImage.toByteData(
        format: ui.ImageByteFormat.png);
    Uint8List uInt8List = byteData.buffer.asUint8List();
    this.setState(() {
      loading = true;
    });
    fs.Reference ref = fs.FirebaseStorage.instance
        .ref()
        .child("Lua_04_${widget.nomefamilia}${DateTime.now().millisecond}.png");
    await ref.putData(uInt8List).whenComplete(() {
      Navigator.pushReplacement(context,
          MaterialPageRoute(
              builder: (context) =>
                  GeraFotos(
                      widget.nome,
                      widget.email
                  )));
    });
```

**Comment by oliwa01** [comment]
G:\projetos_flutter\geradordefotos_app>flutter doctor -v
[√] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [versÃ£o 10.0.18362.1139], locale pt-BR)
    • Flutter version 1.24.0-7.0.pre at D:\src\flutter
    • Framework revision a0860f6e87 (10 days ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\UTIL\android_sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\UTIL\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!

G:\projetos_flutter\geradordefotos_app>

**Comment by oliwa01** [comment]
E/flutter (31232): [ERROR:flutter/shell/common/shell.cc(209)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null.
E/flutter (31232): Receiver: null
E/flutter (31232): Tried calling: _handles, stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (31232): #1      new Image._ (dart:ui/painting.dart:1592:12)
E/flutter (31232): #2      Scene.toImage.<anonymous closure>.<anonymous closure> (dart:ui/compositing.dart:35:24)
E/flutter (31232): 
D/ViewRootImpl@b73bc72[MainActivity](31232): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 2960, 1440) ci=Rect(168, 84 - 0, 0) vi=Rect(168, 84 - 0, 0) or=2
D/ViewRootImpl@b73bc72[MainActivity](31232): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 2960, 1440) ci=Rect(168, 84 - 0, 0) vi=Rect(168, 84 - 0, 0) or=2
D/ViewRootImpl@b73bc72[MainActivity](31232): Relayout returned: old=[0,0][2960,1440] new=[0,0][2960,1440] result=0x23 surface={valid=true 503685414912} changed=false
W/libEGL  (31232): EGLNativeWindowType 0x7545fd8010 disconnect failed
D/OpenGLRenderer(31232): eglDestroySurface = 0x7545f8bd80, 0x7545fd8000
D/mali_winsys(31232): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(31232): eglCreateWindowSurface = 0x7545f8bd80, 0x7545fd8010
D/SurfaceView(31232): show() Surface(name=SurfaceView - com.example.geradordefotosapp/com.example.geradordefotos_app.MainActivity@a3d2dbe@0[31232])/@0xef08e1f io.flutter.embedding.android.FlutterSurfaceView{a3d2dbe V.E...... ......ID 0,0-2792,1440}
D/SurfaceView(31232): surfaceChanged (2792,1440) 1 #5 io.flutter.embedding.android.FlutterSurfaceView{a3d2dbe V.E...... ......ID 0,0-2792,1440}
W/libEGL  (31232): EGLNativeWindowType 0x753912b010 disconnect failed
D/mali_winsys(31232): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl@b73bc72[MainActivity](31232): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 2960, 1440) ci=Rect(168, 84 - 0, 0) vi=Rect(168, 84 - 0, 0) or=2

**Comment by darshankawar** [comment]
@oliwa01 
Please provide a complete minimal reproducible code sample that shows the issue. Where's the code which calls / uses `_handles` ? It seems the way you are calling `_handles` or storing value of `_handles` in null. Before assigning the `_handles` value, check if it exists.

**Comment by oliwa01** [comment]
Hi @darshankawar ,I have no idea, what's "_handles", is. It doesn't have any class´, variable, module ... with this name. This App is a little complex, and big, the app size with the images.png is 1.5 GB.  I create an app that builds a PNG file in high definition, I use a RepaintBoundary with a child Container widget width 12000 height 4000, to create an image that I will generate in png format using
 ui.Image boxImage = await renderRepaintBoundary.toImage(pixelRatio: 1.113);
    ByteData byteData = await boxImage.toByteData(
        format: ui.ImageByteFormat.png);
    Uint8List uInt8List = byteData.buffer.asUint8List(); 
It works perfectly in android emulator, but when I try in a Mobile Samsung , this error occurs,

Do you have any idea about what the "_handles', is? I don't have any referend to in my code.

**Comment by darshankawar** [comment]
@oliwa01 Your question is better suited for StackOver flow. You may need to debug where this exception occurs and see where and how `_handles` is getting called. 

Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
