### ISSUE TITLE
 NavigatorState#

### ISSUE THREAD

**Issue by puneetsethi25** [flutter/flutter#70076]
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (32367): _WidgetsAppState#ec8da](dirty, dependencies: [HeroControllerScope], state:
I/flutter (32367): NavigatorState#8b17b(tickers: tracking 4 tickers)):
I/flutter (32367): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4080 pos 12: '!_debugLocked':
I/flutter (32367): is not true.
I/flutter (32367): 
I/flutter (32367): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (32367): more information in this error message to help you determine and fix the underlying cause.
I/flutter (32367): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (32367):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (32367): 
I/flutter (32367): The relevant error-causing widget was:

**Comment by pedromassangocode** [comment]
Hi @puneetsethi25 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
