### ISSUE TITLE
InteractiveViewer to work with PageView

### ISSUE THREAD

**Issue by Oklahomawhore** [flutter/flutter#70081]
I'm creating a PageView with a list of images, and I want to add interactiveViewer to each image so it can be resized to view details.

here is what I wrote:

```
PageView.builder(
                  dragStartBehavior: DragStartBehavior.start,
                  physics: _viewing ?  NeverScrollableScrollPhysics() : ClampingScrollPhysics(),
                  controller: _pageController,
                  itemBuilder: (context, index) {
                    return Container(
                        child: Expanded(
                          child: Image.network(widget.snapshotList[index].imgUrl),
                        )
                    );
                  },
                  onPageChanged: (index) {
                    setState(() {
                      this.position = index;
                      _transformationController.value = Matrix4.identity();
                    });
                  },
                  itemCount: widget.snapshotList.length,
              )
```

But the two scrollables seem to compete with each other and the behavior is messy.

e.g. once the image is enlarged the scroll gesture also triggers page move, seems that because the viewport is not enlarged with the image itself.

Any solutions?

**Comment by pedromassangocode** [comment]
Hi @Oklahomawhore 
I see there's an open issue addressing the case (https://github.com/flutter/flutter/issues/68594) you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
