### ISSUE TITLE
MissingPluginException when withCachedEngine 

### ISSUE THREAD

**Issue by oliverchu** [flutter/flutter#70089]
I create my Flutter Activity like this:
```kotlin
flutterEngine = FlutterEngine(this)

        flutterEngine.getDartExecutor().executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )
        FlutterEngineCache
            .getInstance()
            .put("my_engine_id", flutterEngine);

        startActivity(
            FlutterActivity
                .withCachedEngine("my_engine_id")
                .build(this)
        )
```
But I found "MissingPluginException",

image_picker: ^0.6.7+12

flutter_bluetooth_serial: ^0.2.2

...

**Expected results:**

Invoke successfully.

**Actual results:**

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/oliver/Work/Android/flutter
    • Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/oliver/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Users/oliver/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Mi 10 Pro (mobile) • dae0d3b • android-arm64 • Android 10 (API 29)

! Doctor found issues in 4 categories.

```
```

</details>

**Comment by oliverchu** [comment]
it works well withNewEngine.

**Comment by darshankawar** [comment]
@oliverchu 
Check [this](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen) document and from it, it seems `withCachedEngine` is used if engine is pre-warmed and is an optional way.  Does your use case fit for `cachedEngine` or `NewEngine` ?  If you remove `image_picker`, does it complain about other plugins ?

**Comment by oliverchu** [comment]
> @oliverchu
> 检查[此](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen)文档，从中开始看来`withCachedEngine`，如果引擎已预热，则似乎可以使用它，并且它是可选的方式。您的用例适合`cachedEngine`还是`NewEngine`？如果删除`image_picker`，它是否会抱怨其他插件？

if i use this method to launch a flutter activity , the plugin works well:

`startActivity(FlutterActivity.withNewEngine().build(getContext()));`

My use case is cachedEngine, I use with a FlutterFragment . So I don't know why the plugins don't work when I create a cachedEngine....I really need your help, thank you very much. 

I try to register the plugin  manually:
```
GeneratedPluginRegistrant.registerWith(FlutterEngineCache.getInstance().get(engineId));
 GeneratedPluginRegister.registerGeneratedPlugins(FlutterEngineCache.getInstance().get(engineId));
```
but it doesn't help.

**Comment by darshankawar** [comment]
@oliverchu 
If you remove `image_picker` plugin, does it complain about other plugins ? or only with `image_picker` ?

**Comment by oliverchu** [comment]
> @oliverchu
> If you remove `image_picker` plugin, does it complain about other plugins ? or only with `image_picker` ?

i add these plugins：

flutter_bluetooth_serial: ^0.2.2
wifi_iot: ^0.1.1

they all don't work no matter whether I remove `image_picker`.
so I don't think it is  `image_picker`'s problem..

**Comment by oliverchu** [comment]
> @oliverchu
> If you remove `image_picker` plugin, does it complain about other plugins ? or only with `image_picker` ?

newFlutterEngine: 
`image_picker` `flutter_bluetooth_serial` work well;

cachedEngine:
plugin list:
```
  image_picker: ^0.6.7+12
  flutter_bluetooth_serial: ^0.2.2
```

1. only image_picker , work well;
2. image_picker and flutter_bluetooth_serial, don't work either;
3. only flutter_bluetooth_serial, don't work

Exception: 
 Another exception was thrown: MissingPluginException(No implementation found for method listen on channel flutter_bluetooth_serial/state)
error=PlatformException(bluetooth_unavailable, bluetooth is not available, null, null)

**Comment by darshankawar** [comment]
@oliverchu 
`flutter_bluetooth_serial` is a 3rd party plugin and you may need to open this issue in plugin owner's repo : https://github.com/edufolly/flutter_bluetooth_serial/issues.
Since, with `image_picker` the `withCachedEngine` works well per your comment, I am going ahead and closing this as non-issue from Flutter framework side. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by oliverchu** [comment]
> @oliverchu
> `flutter_bluetooth_serial` is a 3rd party plugin and you may need to open this issue in plugin owner's repo : https://github.com/edufolly/flutter_bluetooth_serial/issues.
> Since, with `image_picker` the `withCachedEngine` works well per your comment, I am going ahead and closing this as non-issue from Flutter framework side. If you disagree, write in comments and I'll reopen.
> Thanks.

But I create a new flutter engine, they works well all.
