### ISSUE TITLE
Failed assertion: line 567 pos 15: 'textDirection != null': is not true.

### ISSUE THREAD

**Issue by gt562559842** [flutter/flutter#70088]
════════ Exception caught by widgets library ══════════════════════════════════
The following assertion was thrown building Overlay(state: OverlayState#201d9(entries: [OverlayEntry#af44c(opaque: false; maintainState: false), OverlayEntry#961af(opaque: false; maintainState: false)])):
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 567 pos 15: 'textDirection != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md****

**Comment by pedromassangocode** [comment]
Hi @gt562559842 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by SnowWolf817** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/15921937/98780429-b396cf00-242f-11eb-9437-508b3ec26bf8.png">

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
