### ISSUE TITLE
SelectableText widget have no Controller

### ISSUE THREAD

**Issue by AliHoseinpoor** [flutter/flutter#70103]
i need access to the selected part of a text , but Selectabletext() does not have this capability and I have to use the TextField() so that I can get the selected text with its controller.

**Comment by darshankawar** [comment]
@AliHoseinpoor 
Does [this](https://github.com/flutter/flutter/issues/69460) issue sound similar to your request ?

**Comment by pedromassango** [comment]
Hi @AliHoseinpoor 
You can get the selected text by registering a onSelectionChanged callback.

It is was introduced by https://github.com/flutter/flutter/pull/65320 and is currently available on `master` channel only. You can see its doc in https://master-api.flutter.dev/flutter/widgets/SelectionChangedCallback.html

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
