### ISSUE TITLE
Flutter WebView does not pause video playback when app is in background

### ISSUE THREAD

**Issue by safield** [flutter/flutter#70108]
I am testing flutter WebView on an Android Emulator.

The webpage that the webview is rendering contains an embedded vimeo video.

When I put the application in the background using the android home button, the video continues to play in the background.

The expected behaviour would be that the webview pauses all content.

**Comment by darshankawar** [comment]
@safield 
There's similar open issue describing your case, [32363](https://github.com/flutter/flutter/issues/32363). Also see [this](https://github.com/flutter/flutter/issues/32363#issuecomment-608457487) comment on similar behavior you mentioned above. 
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
