### ISSUE TITLE
Hindi font is not showing.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70118]
https://buganizer.corp.google.com/issues/172586348.

**Comment by hello-addweb** [comment]
Please use below document : [https://www.developerlibs.com/2019/03/flutter-localization-or-multi-language-example.html](https://www.developerlibs.com/2019/03/flutter-localization-or-multi-language-example.html)

**Comment by chinmaygarde** [comment]
Marked as fixed.
