### ISSUE TITLE
Web: change SDK selection when NullSafetyMode.autodetect is working

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#70121]
From @jonahwilliams 

> [NullSafetyMode.autodetect is when] the user did not pass a null safety flag
> so what we should do is look at the SDK version and entrypoint to determine if it is opted in
> but that is not implemented so it falls back to unsound on web

We didn't fall back to unsound. So in https://github.com/flutter/flutter/pull/70120 I changed it to actually fall back to the unsound SDK.

**Comment by jonahwilliams** [comment]
Still need to make sure the web asset server knows which mode was selected

**Comment by vsmenon** [comment]
FYI - @pcsosinski for beta tracking.

**Comment by pcsosinski** [comment]
does this block a beta release?

**Comment by jonahwilliams** [comment]
This should be fixed but waiting for another cleanup CL. It should not block a beta
