### ISSUE TITLE
Engine RasterCache usage can lead to double-caching of layers

### ISSUE THREAD

**Issue by flar** [flutter/flutter#70124]
Currently every layer that wants to cache itself or its children will recursively preroll their children and then evaluate if they can cache. The problem with this is that the children may also want to cache themselves and will do so on every frame even though the parent may already have cached them.

Consider an ImageFilterLayer (A) that has a child which is an ImageFilterLayer (B). If A decides to cache itself or its children then it does not need to cache B. However, it needs to visit B during Preroll in order for B to verify its state. As part of its Preroll, B may populate the layer cache with a copy of itself. Further complicating the logic here is that A may fail to cache itself for some reason that won't be known until B returns from the Preroll. That complication means that A can't do something to prevent B from Prerolling because it may be wrong.

The extra cache of B isn't necessarily bad for the frame where A initially does the caching as it will help during the rendering of A or its children. But, on subsequent frames where A is already cached, the cache of B is unneeded and could be freed to use less memory. This must be done carefully, though, so that we don't decide to re-cache B on the next frame.

It looks like the logic to prepare a layer cache will mark it as used even if it is never rendered, so we will avoid recreating the B cache by never releasing it. This may prevent the runaway "re-cache on every other frame" condition, but we still have the extra memory being used since we don't actually need the cache of B.

**Comment by flar** [comment]
Solving this puzzle may require adding a new tree traversal during scene rendering. Preroll would be responsible for identifying layers and layer-children that should be cached without actually doing the caching - and then a separate pass could cache those children once all of the information for the entire tree is available and in a way that avoids duplication. Finally we render with those cached layers.

Some extra credit may be due on low-memory devices if such render-to-cache operations could be done in a "just in time" manner (perhaps using a bottom up approach) so that we could combine the SaveLayer and RasterCache mechanisms into a single "represent a subtree as a raster" general mechanism.

The decisions to cache may also intersect with our Dirty Region Management information and decisions so I am tagging @knopp  for further consideration.

**Comment by knopp** [comment]
You might not need another tree traversal. Perhaps something like this:

```cpp

class AutoGatherLayers {
 public:
  explicit AutoGatherLayers(std::vector<ContainerLayer*>& layers)
      : current_layer_(nullptr),
        layers_(layers),
        initial_size_(layers.size()) {}

  void AddCurrentLayer(ContainerLayer* current_layer) {
    current_layer_ = current_layer;
  }

  ~AutoGatherLayers() {
    if (current_layer_) {
      layers_.resize(initial_size_);
      layers_.push_back(current_layer_);
    }
  }

 private:
  ContainerLayer* current_layer_;
  std::vector<ContainerLayer*>& layers_;
  size_t initial_size_;
};

struct PrerollContext {
   ....
   std::vector<ContainerLayer*> raster_cached_layers;
}

void OpacityLayer::Preroll(...) {
   AutoGatherLayers raster_cached_layers(context->raster_cached_layers);
   ...
   if (needs_raster_cache) {
      raster_cached_layers.AddCurrentLayer(this);
   }
}
```

Add the end of preroll you would end up with preroll_context->raster_cached_layers for each subtree that needs to be raster cached, but just the top level layers.

**Comment by flar** [comment]
@knopp your solution only solves the issue for nested layers themselves. Some layers (see ImageFilterLayer) can cache either themselves or their children. We also have Picture and DisplayList layers that want to cache their pictures which may be obsoleted by a parent caching all children. The "list" needs to be more general than this and have entries for layers caching themselves, layers caching their children, as well as pictures and display lists.

Also, it's not just the intent to cache that matters here, there may be reasons that a layer can't cache itself - such as exceeding a maximum for cache textures. If each AutoGather prunes all children based on the intent then we have no backup plan.

In the end, regardless of whether you've gathered the list of layers to attempt to cache, we still need a separate pass to cache them before rendering and to evict cache entries that haven't been tagged before we do that rasterization. The list may have fewer items in it than a tree pass, but it's still an extra step in the rasterization.

**Comment by JsouLiang** [comment]
@flar I have some change, and could you help me see if it's what you want? https://github.com/flutter/engine/pull/31892

**Comment by flar** [comment]
This issue is really meant to be fixed in the context of https://github.com/flutter/flutter/issues/91923 which it looks like the proposed PR will accomplish, so that's good.

I think the mechanism could be much much simpler, though. Basically, in preroll just record every item that wants to cache. For layers that have children, they record their potential interest before they preroll their children and then when the descendants return they record how many descendant entries there are in the list (so they can be skipped if necessary) and then make final decisions on whether their potential need is accurate or not.

Something like:
```
  cache_entries.emplace_back([me, I might want to cache]);
  auto my_cache_entry = cache_entries.back();
  // Preroll children
  my_cache_entry.num_child_entries = N;
  my_cache_entry.needs_caching = /* logic */;
```

then in the cache phase you simply do:
```
  // Possibly prune the cache of anything not in the cache_entries
  // Minimally preroll might have already marked their entries in
  // the raster cache as "in use", but that could potentially mark
  // entries that are going to be obsoleted by their parents.
  // The exact cache evictions would require some processing,
  // perhaps best left to a follow-on PR...?
  for (int i = 0; i < cache_entries.size(); i++) {
    auto cache_entry = cache_entries[i];
    if (cache_entry.needs_caching) {
      // PrepareCache...
      i += cache_entry.num_child_entries - 1;
      // (Or advance the iterator by N-1 entries?
    }
  }

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks

**Comment by JsouLiang** [comment]
@fzyzcjy hello, you can see this pr: https://github.com/flutter/engine/pull/31892
This pr is the solution for this issue.

**Comment by fzyzcjy** [comment]
@JsouLiang Hi thanks for the reply, the PR looks promising :)

P.S. Maybe a bit related: https://github.com/flutter/flutter/issues/106388

**Comment by JsouLiang** [comment]
@fzyzcjy Hi thank you for your attention, we will land this pr as soon as we can, with @flar

**Comment by ColdPaleLight** [comment]
Closing it var https://github.com/flutter/engine/pull/31892
