### ISSUE TITLE
Link to DevTools more prominently than Observatory from `flutter run`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#70129]
To do this, we likely will need to switch to launching from pub.

From Jonah: "Some thought needs to be put into whether we should always activate the latest version, or should roll a pinned version."

CC @jonahwilliams

**Comment by jonahwilliams** [comment]
Another caveat here is that users may use the printed VM Service URL for other purposes, such as connecting to the VM Service through separate testing scripts.

So changing the existing message will probably be breaking, but adding another message for devtools is probably fine

**Comment by kenzieschmoll** [comment]
Related: https://github.com/flutter/flutter/issues/71688. If the DevTools is launched by default from pub at app run, this would be as simple as adding a devtools link to the existing message.
