### ISSUE TITLE
flutter run -d id_of_device_on_usb does not work on MacOS/iPhone

### ISSUE THREAD

**Issue by TillCity** [flutter/flutter#70122]
Flutter is good - I tried it out to develop an Android app and was consistently pleasantly surprised at how easy and elegant it all was.  I then tried to run the app off my Mac Mini on the iPhone emulator and that too turned out to be an effortless process.  However, when I try to run the app on an iPhone attached to the Mac via USB I have been unable to make much headway.

`flutter run -d deviceID` returns the message _Could not run build/ios/iphoneos/Runner.app_ and the suggestion that I run XCode -> Product -> Run to fix the problem.  Doing so produces the message

_The operation couldn’t be completed. Unable to launch com.example.app because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user._.  Why is this happening and what can be done to fix it?

I have tried this with the latest version of Flutter on MacOS Catalina with XCode 12.1.  Flutter doctor does not report any errors.

**Comment by pedromassangocode** [comment]
Hi @TillCity 
Looks like you have the developer account you are using is not trusted by the device you are trying to run on.
To solve this see https://stackoverflow.com/a/61865411 for more information.

Closing this as this is not an issue with Flutter itself.
Thank you

**Comment by TillCity** [comment]
Thank you.  That fixed the problem.  However, it would help a whole horde of Flutter newbies if the Flutter docs mentioned two things on the subject of iOS

1. When asked to login to the keychain that stores the Apple Developer certificate you need to click the "Always Allow" button since the XCode build process appears to access this cert some 30+ times during the build.
2. On the host iOS device you need to navigate to Settings > General > Profiles or Settings > General > Device Management and explicitly trust Apps coming from the relevant source/team.

While these may not be pure Flutter issues you are doing Flutter a disservice by not mentioning them.
