### ISSUE TITLE
accentColor: has no effect

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7013]
I saw redAccent[200] work for some reason only once. Seems very flakey, system seems intent on the color being teal for some reason.

```
final ThemeData _darkTheme = new ThemeData(
    brightness: Brightness.dark,
    accentColor: Colors.cyanAccent[200],
);

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Test app',
      theme: _darkTheme,
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```

**Comment by Hixie** [comment]
If you make other changes, like changing the MyHomePage title, does that take effect?

I'm trying to determine if this is a theme bug or a hot reload bug or something else.

**Comment by Hixie** [comment]
(If you could post the entire program that would aid in reproduction.)

**Comment by Hixie** [comment]
Without clear steps to reproduce I don't know how to address this problem.
