### ISSUE TITLE
cipd ensire -log-level error -root .. -ensure-file .. returned non-zero exit status 2

### ISSUE THREAD

**Issue by YuvarajVelumani82** [flutter/flutter#70134]
I am trying to build flutter engine, but getting the below error

| ________ running 'cipd ensure -log-level error -root /home/yvelumani/code/build/tmp/work/aarch64-poky-linux/flutter-engine/git-r0/git -ensure-file /tmp/tmpT3CAuQ.ensure' in '.'
| wget: --user-agent: Invalid value ‘depot_tools/HEAD\n???’.
| Error: Command 'cipd ensure -log-level error -root /home/yvelumani/code/build/tmp/work/aarch64-poky-linux/flutter-engine/git-r0/git -ensure-file /tmp/tmpT3CAuQ.ensure' returned non-zero exit status 2
| WARNING: /home/yvelumani/code/build/tmp/work/aarch64-poky-linux/flutter-engine/git-r0/temp/run.do_patch.11923:1 exit 1 from 'gclient.py sync --nohooks --no-history --revision 678b96d4e3af62b1218775bcd5ccbcaaf6e9835a -j 12 -v'

Can anyone help me.

Thanks in advance

**Comment by TahaTesser** [comment]
Hi @YuvarajVelumani82 
What command you running that is causing this issue?  Which platform are you compiling the engine for? 
Please follow all steps from https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment and make sure you've run step 7 with Linux scripts 
Provide steps, please
Thank you

**Comment by YuvarajVelumani82** [comment]
Hi @TahaTesser 
I am trying to build the flutter engine for aarch64. 
Basically I am using the meta-flutter recipes which is an Yocto Layer for Flutter Engine on my Yocto Poky environment.
Do I still need to follow step 7 for Non-native Linux environment also?
The bitbake script has passed "False" argument to deps.
Refer File flutter-engine_git.bb from : [https://github.com/jwinarske/meta-flutter/tree/zeus/recipes-graphics/flutter-engine]

```
gclient.py config --spec 'solutions = [
     {
            "managed" : False,
            "name" : "src/flutter",
            "url" : "git@github.com:flutter/engine.git",
            "custom_vars" : {
                "download_android_deps" : False,
                "download_windows_deps" : False,
        }
    }
]'
```

So, should I still need to run 
```
sudo ./build/install-build-deps-android.sh
sudo ./build/install-build-deps.sh
sudo ./flutter/build/install-build-deps-linux-desktop.sh
```
Thank you for help in advance.

**Comment by TahaTesser** [comment]
Hi @YuvarajVelumani82 
If you're experiencing the issue following steps from official documentation and after doing steps that are required, it should have no problem. 
Otherwise,  I suggest you file an issue on the third party repository for  the steps which are part of the official documentation
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
