### ISSUE TITLE
Errors don't inform the user of --no-sound-null-safety

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#70145]
### Steps to reproduce:

1. Upgrade your app to null safety
2. Introduce a package dependency for which the package has no null safe version
3. Run `flutter run`

### Expected results

You expect the error message to tell you _both_ why it's unable to run in sound mode (because the dependencies aren't null safe) _and_ how to get around the error (by running with `--no-sound-null-safety`).

### Actual results

It tells you why it failed to build and how to inspect the package versions, but it doesn't tell you how to sidestep the problem for now...

```
> flutter run -t lib/main.dart -d iphone --debug
Running "flutter pub get" in payouts...                            458ms
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                           1,746ms
Running Xcode build...                                                  
Xcode build done.                                           15.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Error: This project cannot run with sound null safety, because one or more project dependencies do not
    support null safety:

     - package:http
     - package:intl
     - package:http_parser

    Run 'pub outdated --mode=null-safety' to determine if versions of your
    dependencies supporting null safety are available.

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

Sure enough, in this example, running `flutter run --no-sound-null-safety ...` allowed the app to run.

**Comment by jonahwilliams** [comment]
For both the CFE and flutter, the correct flag in this case is `--no-sound-null-safety`, so the CFE error messages could be updated to vaguely reference "running" with that flag and still be correct for both flutter and Dart.

Alternatively, the compiler could return a specific error code that the tool could interpret to add an additional footer with more context.

The tool could also try and parse the stdout, but I think that would be very fragile - given that the message output by CFE may need to evolve anyway and that would make many changes to it breaking.

**Comment by jonahwilliams** [comment]
@mit-mit

**Comment by mit-mit** [comment]
Moving to the Dart SDK tracker; this is indeed in the CFE.

**Comment by mit-mit** [comment]
Moved to https://github.com/dart-lang/sdk/issues/44149
