### ISSUE TITLE
Consider renaming State.config to State.widget

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7015]
The term "config" comes from an old version of the system where it made more sense.  It might be more sensible to use the name "widget" now that we consistently call the configuration objects "widgets".

It's a fairly big change, so we should be mindful of the churn it will cause.

(Also, if we made this change, we'll probably want to rename didUpdateConfig as well.)

**Comment by sethladd** [comment]
Yes please. :) That makes more sense to me, at least.

**Comment by Hixie** [comment]
Oh man, that's quite the disruptive change. Better do it ASAP if we want to do it.

We do use the term "configuration" in various places, but I agree that it doesn't seem to have sunk in.

**Comment by HansMuller** [comment]
I like this change as well.  It would be consistent with Element's getter (which will hopefully by documented as "This element's widget"):
```
  /// The configuration for this element.
  @override
  Widget get widget => _widget;
```

**Comment by Hixie** [comment]
"This element's widget" for a getter called `widget` on a class called `Element` wouldn't pass our style guide. :-)

I think there is value in continuing to use the term "configuration" for what a widget is to an element, especially if we change the name of the member to `widget`, because that gives people two ways to think about it and one might get through...

**Comment by abarth** [comment]
IntelliJ refused this refactoring because `widget` is used as a local variable in subclasses of State, which would then shadow this getter.  That's probably a common pattern that we'd have to be careful about when making this change.

**Comment by xster** [comment]
If everyone agrees, I don't mind doing this manually and try to do something reasonably for the local variable case by case.

**Comment by Hixie** [comment]
If you're willing to try it, let's try it and see how it feels. I'm guessing this is a win.

**Comment by xster** [comment]
Ok 2816 config instances, here I come

**Comment by xster** [comment]
Ok, I'm thinking

Step 1 - change everything in the flutter repo, leave a deprecated config getter and a deprecated didUpdateConfig
Step 2 - change the website and various docs and slides I can find
Step 3 - change all downstream usages in google3
Step 4 - patch what I can in downstream github users
Step 5 - delete deprecated code

**Comment by eseidelGoogle** [comment]
Do we know if `@deprecated` works for google's source base?  I seem to recall "warnings" were not possible there.   Reach out to @cbracken or @tvolkert to confirm privately would be my recommendation. :)

**Comment by abarth** [comment]
> Step 3 - change all downstream usages in google3

We're also on the hook for updating fuchsia.googlesource.com.

Your plan sounds great.

**Comment by abarth** [comment]
> Do we know if `@deprecated` works for google's source base?

I didn't do much last time I tried.  However, staging the change as @xster describes will make it possible to update internal customers incrementally, which is quite useful.

**Comment by cbracken** [comment]
`@deprecated` is OK for the internal source base; developers will get the warning in their IDEs, but it won't break tests, and we can do a global fixup on the code as soon as we're ready.

**Comment by tvolkert** [comment]
Yep, +1 for @xster's plan - we'll make a sweep and update all internal call sites

**Comment by xster** [comment]
ya, we don't need @deprecated to work per se. It'll probably become a P4 bug that'll sit for 2 years anyway. We'll just go do it for them. 

The annotation will just be for people adding stuff during the transition.

Understood for the fuchsia codebase.
