### ISSUE TITLE
Android video play not full screen

### ISSUE THREAD

**Issue by ggao15-ford** [flutter/flutter#70168]
the plugin android  FlutterWebChromeClient not override onShowCustomView,and onHideCustomView. so it can not full screen, could you add the function. thanks.

**Comment by darshankawar** [comment]
@ggao15-ford 
Please elaborate on your request along with a detailed use case ? Which plugin are you referring to ?

**Comment by hello-addweb** [comment]
use Chewie plugin, you can install it right here: https://pub.dev/packages/chewie And this is the code that I implemented it

`VideoPlayerController _videoPlayerController;
ChewieController _chewieController;
double _aspectRatio = 16 / 9;
@override
initState() {
super.initState();
print(widget.videoUrl);
_videoPlayerController = VideoPlayerController.network(widget.videoUrl);
_chewieController = ChewieController(
allowedScreenSleep: false,
allowFullScreen: true,
deviceOrientationsAfterFullScreen: [
DeviceOrientation.landscapeRight,
DeviceOrientation.landscapeLeft,
DeviceOrientation.portraitUp,
DeviceOrientation.portraitDown,
],
videoPlayerController: _videoPlayerController,
aspectRatio: _aspectRatio,
autoInitialize: true,
autoPlay: true,
showControls: true,
);
_chewieController.addListener(() {
if (_chewieController.isFullScreen) {
SystemChrome.setPreferredOrientations([
DeviceOrientation.landscapeRight,
DeviceOrientation.landscapeLeft,
]);
} else {
SystemChrome.setPreferredOrientations([
DeviceOrientation.portraitUp,
DeviceOrientation.portraitDown,
]);
}
});
}`

**Comment by hello-addweb** [comment]
use Chewie plugin, you can install it right here: https://pub.dev/packages/chewie And this is the code that I implemented it

` VideoPlayerController _videoPlayerController;

ChewieController _chewieController;

double _aspectRatio = 16 / 9;

@override

initState() {

super.initState();

print(widget.videoUrl);

_videoPlayerController = VideoPlayerController.network(widget.videoUrl);

_chewieController = ChewieController(

allowedScreenSleep: false,

allowFullScreen: true,

deviceOrientationsAfterFullScreen: [

DeviceOrientation.landscapeRight,

DeviceOrientation.landscapeLeft,

DeviceOrientation.portraitUp,

DeviceOrientation.portraitDown,

],

videoPlayerController: _videoPlayerController,

aspectRatio: _aspectRatio,

autoInitialize: true,

autoPlay: true,

showControls: true,

);

_chewieController.addListener(() {

if (_chewieController.isFullScreen) {

SystemChrome.setPreferredOrientations([

DeviceOrientation.landscapeRight,

DeviceOrientation.landscapeLeft,

]);

} else {

SystemChrome.setPreferredOrientations([

DeviceOrientation.portraitUp,

DeviceOrientation.portraitDown,

]);

}
});
} `

**Comment by hello-addweb** [comment]
use Chewie plugin, you can install it right here: https://pub.dev/packages/chewie And this is the code that I implemented it


```
VideoPlayerController _videoPlayerController;
ChewieController _chewieController;
double _aspectRatio = 16 / 9;
@override
initState() {
super.initState();
print(widget.videoUrl);
_videoPlayerController = VideoPlayerController.network(widget.videoUrl);
_chewieController = ChewieController(
allowedScreenSleep: false,
allowFullScreen: true,
deviceOrientationsAfterFullScreen: [
DeviceOrientation.landscapeRight,
DeviceOrientation.landscapeLeft,
DeviceOrientation.portraitUp,
DeviceOrientation.portraitDown,
],
videoPlayerController: _videoPlayerController,
aspectRatio: _aspectRatio,
autoInitialize: true,
autoPlay: true,
showControls: true,
);
_chewieController.addListener(() {
if (_chewieController.isFullScreen) {
SystemChrome.setPreferredOrientations([
DeviceOrientation.landscapeRight,
DeviceOrientation.landscapeLeft,
]);
} else {
SystemChrome.setPreferredOrientations([
DeviceOrientation.portraitUp,
DeviceOrientation.portraitDown,
]);
}
});
}
```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
