### ISSUE TITLE
Hi guys, in my VS Code editor a pop up said to upgrade Flutter and I clicked it. Now it says no available devices and when I click to add a device it says "The Flutter Daemon has terminated".

### ISSUE THREAD

**Issue by muhamadkhuram** [flutter/flutter#70169]
Hi guys, in my VS Code editor a pop up said to upgrade Flutter and I clicked it. Now it says no available devices and when I click to add a device it says "The Flutter Daemon has terminated". 
![Screenshot (21)](https://user-images.githubusercontent.com/69458508/91635959-5a1b2880-ea1a-11ea-8f9e-572d564aba98.png)
And when i run flutter doctor command it shows me this
![Screenshot (22)](https://user-images.githubusercontent.com/69458508/91635966-6f905280-ea1a-11ea-8717-ed530b050934.png)
Please help me guys as soon as possible

_Originally posted by @Saurabh619SIngh in https://github.com/flutter/flutter/issues/59726#issuecomment-683278917_

**Comment by darshankawar** [comment]
@muhamadkhuram 
Please try [this](https://github.com/flutter/flutter/issues/20326#issuecomment-415479741) solution and see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
