### ISSUE TITLE
[web] chinese display Incorrectly in RichText 

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#70170]
I use maxLines and overflow in RichText,like below:

```
Expanded(
                flex: 4,
                child: Container(
                  child: RichText(
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    text: TextSpan(
                        style: const TextStyle(
                            height: 1.5,
                            fontSize: 16,
                            fontWeight: FontWeight.normal,
                            color: OnesColors.primaryGray),
                        children: highLightText == null
                            ? [
                                TextSpan(
                                  style: const TextStyle(
                                      height: 1.5,
                                      fontSize: 16,
                                      fontWeight: FontWeight.normal,
                                      color: OnesColors.primaryGray),
                                  text: title,
                                )
                              ]
                            : MessageHelper.makeHighLightText(
                                title, highLightText,
                                spanContentHandle: (value) => value
                                    .replaceAll(r"""<em>""", "").replaceAll(
                                        r"""</em>""", ""))),
                  ),
                )
)
```

Android brower:
![image](https://user-images.githubusercontent.com/2295872/98664093-e1730980-2384-11eb-9274-8acf2f07d2ad.png)

iOS brower:
![image](https://user-images.githubusercontent.com/2295872/98663838-8b05cb00-2384-11eb-96d7-b2a6a43f00a7.png)

╰ flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.21.0-9.1.pre at /Users/liuyanfeng/Library/flutter
    • Framework revision be9bc8cb39 (3 months ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by pedromassangocode** [comment]
Hi @lyf571321556 
Looks like you are running an old Flutter version, please upgrade by running the commands bellow:
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists then please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
Thank you

**Comment by stuz5000** [comment]
I also see the same behavior in TextPainter (maybe the underlying casues) -- the text height is incorrectly calculated and results in the same clipping when rendered into a canvas sized to the text height determined by the TextPainter.
