### ISSUE TITLE
On Flutter Web CircularProgressIndicator() takes 100% of CPU

### ISSUE THREAD

**Issue by abuanwar072** [flutter/flutter#70174]
If I always show CircularProgressIndicator() on the web it creates an infinite number of verbose.

please check this video:
https://imgur.com/r0UPFAy

**Comment by pedromassangocode** [comment]
Hi @abuanwar072 
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
Thank you

**Comment by PixelToast** [comment]
This appears to be a debug build, so the verbose diagnostics and high CPU usage is expected

@abuanwar072 could you please test if the issue persists in release or profile mode?

**Comment by abuanwar072** [comment]
@PixelToast Thank you so much 😊, It works properly on the release or profile mode. 
If anyone faces this same problem please run `flutter run --profile`
