### ISSUE TITLE
[web] Incorrect focus handling for flutter in IFrame

### ISSUE THREAD

**Issue by MariaMelnik** [flutter/flutter#70173]
**Steps to Reproduce**

Flutter doc can be example to reproduce this issue.
1. Go to https://flutter.dev/docs/cookbook/forms/focus#interactive-example.
2. Put cursor on input and type some text.
3. Put cursor to the left side (code). Note, that cursor is not disappeared from the right side (app preview).
4. Put cursor back to the input where you leave it. Note, that cursor is not disappeared from the left side (app code).
5. Try to type something in input.

What I expect:
I am typing in the TextField.

What actually happens:
I am typing in the code part.

I experience same behaviour with flutter version:
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.14.6 18G4032 x86_64, locale en-RU)
    • Flutter version 1.23.0-18.1.pre 
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)
```

**Comment by darshankawar** [comment]
@MariaMelnik 
Can you provide a minimal complete reproducible code sample for the issue you are seeing in Flutter version ?
I saw the issue you mentioned with interactive example from flutter doc link. Curious to see the same with Flutter version.

**Comment by MariaMelnik** [comment]
@darshankawar I will try to make example (actually any example with TextField will be good if flutter app will be in iframe).

But I have solution for this (I believe flutter should handle it itself):

```
import 'dart:html' as html;

html.window.onBlur.listen((e) {
    FocusManager.instance.primaryFocus.unfocus();
  });
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kuro7766** [comment]
> @darshankawar I will try to make example (actually any example with TextField will be good if flutter app will be in iframe).
> 
> But I have solution for this (I believe flutter should handle it itself):
> 
> ```
> import 'dart:html' as html;
> 
> ...
> 
> html.window.onBlur.listen((e) {
>     FocusManager.instance.primaryFocus.unfocus();
>   });
> ```

I have the same problem in using iframe and textfield. This code solves my problem.
