### ISSUE TITLE
linux_docs failing on infra closing the framework tree.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#70187]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs

**Comment by keyonghan** [comment]
CL: https://flutter-review.googlesource.com/c/recipes/+/8360 was submitted yesterday, and https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/adhoc_validation/api.py;l=63 needs corresponding change to the correct dir.

Working on a fix.

**Comment by keyonghan** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/8480

**Comment by keyonghan** [comment]
Fix submitted, and the issue should be fixed. Please reopen if it persists.

**Comment by flar** [comment]
The latest build still has the problem.

**Comment by keyonghan** [comment]
> The latest build still has the problem.
> https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs/970

The recipe may take some time to get propagated. Let's see if the latest one succeeds.

@godofredoc how long does it take for a submitted recipe to get propagated?

**Comment by keyonghan** [comment]
Uh, the `doc_path` is not using the injected value, but re-assigned. https://devops-console-oss.corp.google.com/flutter/recipes/+/master:recipe_modules/firebase/api.py;l=35

Working on a follow-up fix.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/8481

**Comment by keyonghan** [comment]
Tree is open. Closing.
