### ISSUE TITLE
In flutter gallery android app 

### ISSUE THREAD

**Issue by PythonRam** [flutter/flutter#7018]
UI fix 
In dark mode in tool tips, the phone icon is not visible.

**Comment by eseidelGoogle** [comment]
![simulator screen shot nov 25 2016 8 56 28 pm](https://cloud.githubusercontent.com/assets/11857803/20638131/ad0284ac-b351-11e6-9a5a-ee29a0f3db27.png)

**Comment by eseidelGoogle** [comment]
Thanks for the report!
