### ISSUE TITLE
Allow building a skeleton UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70196]
This tracks getting a preliminary UWP embedding engine build working, without actually being functional:
- [x] [Dart support for a UWP variant](https://github.com/dart-lang/sdk/issues/43762)
- [x] [Buildroot changes](https://github.com/flutter/buildroot/pull/409)
- [x] Skia changes ([PR](https://skia-review.googlesource.com/c/skia/+/345219))
- [x] [Engine target stub](https://github.com/flutter/engine/pull/21754)
- [x] Engine CoreWindow implementation https://github.com/flutter/engine/pull/23573
- [x] Changes for engine to link cleanly for AppContainer
- [X] SKIA fix type ([branch](https://skia-review.googlesource.com/c/skia/+/370226))
- [x] Second wave of Buildroot changes ([PR: Fix linker to enable successful builds of the --winuwp target (#438)](https://github.com/flutter/buildroot/commit/e7857d269381e23d1a89a3cbf017854992bda15a)): landed, not yet rolled into Flutter engine
- [ ] Windows: Fix fml::GetFullHandlePath for WINUWP target ([PR: Windows: Fix fml::GetFullHandlePath for WINUWP target](https://github.com/flutter/engine/pull/24422))
- [ ] ANGLE changes re-land ([PR: Reland "Add support for building in Flutter Windows UWP configuration"](https://chromium-review.googlesource.com/c/angle/angle/+/2693639))

**Comment by MrBirb** [comment]
Hey @clarkezone ! Looks like all the options are done and the issue was moved to Done in the Windows project. Is there any more work to do here or can this be closed?
