### ISSUE TITLE
`felt test --integration-tests-only` fails with "pubspec.yaml file not found"

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#70193]
When I run `felt test --integration-tests-only` the command fails with the following error:

```
Unhandled exception:
Bad state: ERROR: pubspec.yaml file not found in the test project in the directory /home/yjbanov/code/flutter/engine/src/flutter/e2etests/web/.dart_tool.
#0      IntegrationTestsManager._validateTestDirectory (file:///home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:216:7)
#1      IntegrationTestsManager._validateAndRunTests (file:///home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:106:5)
#2      IntegrationTestsManager._runTests (file:///home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:92:50)
<asynchronous suspension>
#3      IntegrationTestsManager.runTests (file:///home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:36:14)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#5      main (file:///home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/dev/felt.dart:39:26)
<asynchronous suspension>
```

The exit code is 255.

/cc @nturgut

**Comment by yjbanov** [comment]
This affects `felt test` too.

**Comment by nturgut** [comment]
Can you share which commit branch are you using? I'm not able to reproduce these errors. Also which directory are you using felt tool from? (it should not effect the outcome, I'm curious to see if it's the reason I'm not able to produce the error).

**Comment by nturgut** [comment]
A small note, `felt` is used on all recipes (Windows, Linux, Mac), since the tree is green for the latest engine commit I assume this a local issue. I might be able to help with more details provided though :)

**Comment by yjbanov** [comment]
> Can you share which commit branch are you using? I'm not able to reproduce these errors. Also which directory are you using felt tool from? (it should not effect the outcome, I'm curious to see if it's the reason I'm not able to produce the error).

I'm running locally on a clean master branch (no local changes) on a Linux computer. I ran it from `lib/web_ui`.

> I also recommend running `felt clean` between branch changes.

I just did but the result is the same.

Full log: https://gist.github.com/yjbanov/99b2696d5c73a96c23255a662d191ef7

I also noticed that some tests throw exceptions but then say "All tests passed" ([example](https://gist.github.com/yjbanov/99b2696d5c73a96c23255a662d191ef7#file-felt-integration-tests-txt-L332), [example](https://gist.github.com/yjbanov/99b2696d5c73a96c23255a662d191ef7#file-felt-integration-tests-txt-L354)).

**Comment by yjbanov** [comment]
I also tried `cd e2etests/web/regular_integration_tests` and running the test directly using this command:

```
flutter drive --target=test_driver/profile_diagnostics_integration.dart -d web-server --profile --browser-name=chrome --local-engine=/home/yjbanov/code/flutter/engine/src/out/host_debug_unopt --web-renderer=canvaskit
```

However, that fails for an entirely new reason:

```
Unable to detect a Flutter engine build directory in /home/yjbanov/code/flutter/engine/src/flutter/.dart_tool.
Please ensure that /home/yjbanov/code/flutter/engine/src/flutter/.dart_tool is a Flutter engine 'src' directory and that you have compiled the engine in
that directory, which should produce an 'out' directory
```

**Comment by yjbanov** [comment]
It seems I had a stray `.dart_tool` directory under `e2etests/web`. The original error was gone after I deleted it. It hasn't come back so far (although I don't know what created it in the first place). I will close the issue for now.

I filed separate issues for other behaviors I observed:

- https://github.com/flutter/flutter/issues/70400
- https://github.com/flutter/flutter/issues/70402
