### ISSUE TITLE
Add UWP test support to flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70209]
Before landing any UWP plugin support in flutter/plugins, we'll need to bring up UWP CI testing for that repo. I expect we'll be able to use the same bots, so it'll be script/tooling work.

**Comment by moko256** [comment]
I'll close this because it is for obsolete UWP engine.
See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
