### ISSUE TITLE
SharedPreferences values lost when after notification receive

### ISSUE THREAD

**Issue by awshakam1998** [flutter/flutter#70203]
I'm store the data of notification in sharedPreferences and print the data from sharedPrefernces in the same function  this is works well,
But if call the preferences from another function its return null 
This is the code of store in sharedPreferences :
```
`Future<dynamic> setSharedPreferences(Map<String, dynamic> message) async {
  SharedPreferences.setMockInitialValues({});
  SharedPreferences prefses = await SharedPreferences.getInstance();
  FcmNoification fcm = FcmNoification.fromJson(message['data']);
  String stateOrder = findStatTrue(fcm);
  var fcmNot = {'ord_state': '$stateOrder', 'order': fcm.toJson()};
  await prefses.setString('order_state', '${jsonEncode(fcmNot)}');
  prefses.commit();
  print('NOTIFICATION  ${prefses.getString('order_state')}');
}
`
Here the data is printed correctly , But when I call into button printing it prints null such as :
`
 RaisedButton(
          onPressed: () {
  print('NOTIFICATION  ${prefses.getString('order_state')}');
},
          child: const Text(
            'Print preferences',
            style: TextStyle(fontSize: 20)
          ),
        ),
`
```

**Comment by darshankawar** [comment]
@awshakam1998 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that we can copy paste and run in IDE that helps to replicate the issue you are facing.
Thanks.

**Comment by serik9599** [comment]
Zm

**Comment by serik9599** [comment]
Zm

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
