### ISSUE TITLE
[shared_preferences] Add UWP support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70208]
Once we have a stable UWP embedding API, we'll need to add support for it to shared_preferences.

This may not require any additional implementation work once path_provider_windows supports UWP, but we'll need to at least update examples/tests.

**Comment by moko256** [comment]
I'll close this because it is for obsolete UWP engine.
See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
