### ISSUE TITLE
Use cppwinrt to create WinRT headers for UWP embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#70205]
We'll need to fetch cppwinrt as part of gclient hooks, and then generate headers (likely as a build step).

**Comment by cbracken** [comment]
Taking a look at building the CIPD package for this.

**Comment by cbracken** [comment]
I've created a [CIPD package](https://chrome-infra-packages.appspot.com/p/flutter_internal/tools/cppwinrt/windows-amd64/+/) of version 2.0.210301.1 and tagged `latest`.

**Comment by cbracken** [comment]
Looks like in terms of usage in the recipes, we'll need to do something like this in the recipe in which we'd like to use it:
```python
cppwinrt_path = ‘path to the desired location’
pkgs = api.cipd.EnsureFile()
pkgs.add_package('flutter_internal/tools/cppwinrt/windows-amd64', ’latest’)
api.cipd.ensure(cppwinrt_path, pkgs)
```

**Comment by cbracken** [comment]
I've deleted the above-mentioned CIPD package since it needs to be under the flutter/ CIPD root, not the flutter_internal root.

Added docs on the process of creating/updating/tagging in flutter/engine#24770.

**Comment by Sunbreak** [comment]
Hi, @cbracken is there any example to take advantage of https://github.com/flutter/engine/pull/24770?

Something like https://github.com/woodemi/quick_blue/commit/c3ede66b3b3a1e81f4756a5ed6f1595c994293f0 ?

```cmake
find_program(NUGET_EXE NAMES nuget)
if(NOT NUGET_EXE)
	message("NUGET.EXE not found.")
	message(FATAL_ERROR "Please install this executable, and run CMake again.")
endif()

exec_program(${NUGET_EXE}
    ARGS install "Microsoft.Windows.CppWinRT" -Version 2.0.201102.2 -ExcludeVersion -OutputDirectory ${CMAKE_BINARY_DIR}/packages)
```

**Comment by cbracken** [comment]
@Sunbreak We'll likely add a `.gni` file that adds a build rule that emits C++ header libraries viathis tool.

An example of a similar case, where we use a tool to generate some intermediate file which then becomes an input to a later part of the build, might be the [dart_kernel](https://github.com/flutter/engine/blob/master/tools/fuchsia/dart_kernel.gni) rule, which compiles a Dart program into a kernel `.dill` file.

**Comment by cbracken** [comment]
Note from @clarkezone flutter/engine#24770, so we don't forget:

>  There is a potential bug in the generated output of the tool that I thought had been fixed. Need to confirm that it is still a problem (`std::terminate()` not working as expected; fixed using `abort()` instead); if that is the case we'll need to re-ingest tool once the fix is in.

**Comment by clarkezone** [comment]
Consuming this cppwinrt tool here:

flutter/buildroot#442
https://github.com/flutter/engine/pull/24861

**Comment by clarkezone** [comment]
This issue is now fixed.
