### ISSUE TITLE
What are the exacts system requirements for Flutter?

### ISSUE THREAD

**Issue by UltraBurstXD** [flutter/flutter#70210]
Hi,
I've low-end weak PC, so I cannot use android studio (it's costly, nearly all memory footprint's gone)  to code system or intensive android apps (4GB RAM and 2GB Swap), so I'm considering moving to flutter. I'm willing to use gedit on Linux and some comandline tools like I do with Rust, but what are the exacts system requirements to use Flutter efficiently?

**Comment by iapicca** [comment]
https://flutter.dev/docs/get-started/install/linux#system-requirements

**Comment by darshankawar** [comment]
@UltraBurstXD 
Hope the above link shared answers your question. If you have any specific issue or feature request in the framework, feel free to comment or log a new issue with required details.
Closing this for now.
