### ISSUE TITLE
initState is not documented on docs.flutter.io

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#7022]
I had to go find it in https://flutter.io/reading-writing-files/

I was looking for the place to hang my load-my-data-model code off of.

**Comment by eseidel** [comment]
It's possible we want to document the "where to hang your loading code off of" in https://flutter.io/assets-and-images/#loading-assets.

**Comment by eseidel** [comment]
I see, lifecycle is available here: https://docs.flutter.io/flutter/material/State-class.html just not reachable via search on docs.flutter.io.

**Comment by eseidel** [comment]
Or it is reachable: https://docs.flutter.io/flutter/material/State/initState.html just search turns up less useful things first, and is not scrollable.

**Comment by abarth** [comment]
I see.  There are just tons of overrides and you want the base class.  Probably a dartdoc bug to prioritize the base class's version of a function over the overrides.

**Comment by Hixie** [comment]
That's https://github.com/dart-lang/dartdoc/issues/896
