### ISSUE TITLE
"pub" doesn't work on ReleaseARM builds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7023]
I have the Dart SDK's `.gclient` file at `/home/ianh/dev/dart-sdk`. I run `gclient sync`, then `./tools/build.py -m release -a arm runtime`. I have `/home/ianh/dev/dart-sdk/sdk/sdk/bin` in my path. If I run `pub get` I get:

```
/home/ianh/dev/dart-sdk/sdk/sdk/bin/pub: line 85: /home/ianh/dev/dart-sdk/sdk/sdk/../out/ReleaseARM/dart-sdk/bin/dart: No such file or directory
```

**Comment by abarth** [comment]
Sounds like an issue for https://github.com/dart-lang/sdk

**Comment by Hixie** [comment]
I could have sworn I was on the right repo. Sigh.
