### ISSUE TITLE
Black screen with dialog on top if we switch apps

### ISSUE THREAD

**Issue by sidvenu** [flutter/flutter#70232]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Create a Dialog in a Native Module or simply request permissions
3. Open the app, and open the dialog
4. Go to home screen (don't close the app)
5. Come back to the app

**Expected results:** The same screen I had before going to the home screen

**Actual results:** Imagine an entire screen black, with the dialog on top of it (the dialog area alone is good)

Related issues: #58002, https://github.com/Baseflow/flutter-permission-handler/issues/363

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_IN)
    • Flutter version 1.22.3 at /home/sidvenu/snap/flutter/common/flutter
    • Framework revision 8874f21e79 (12 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/sidvenu/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/sidvenu/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_272-8u272-b10-0ubuntu1~20.04-b10)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • LLD AL20 (mobile) • CYG3Y18809010153 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@sidvenu 
Please provide a complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
