### ISSUE TITLE
Test Flutter Desktop on Big Sur

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#70243]
macOS 11 (Big Sur) comes out on November 12th. We should test it and ensure there are no major issues.

cc @cbracken @stuartmorgan

**Comment by gw280** [comment]
cc @csells

**Comment by shreeve** [comment]
Is there a list of known issues with Flutter and Big Sur?

**Comment by gw280** [comment]
We don't yet have a list of issues for Flutter on Big Sur. I will be working on that when I get a Big Sur development machine, likely in a couple of weeks.

**Comment by jmagman** [comment]
I haven't seen any issues from the community, and I personally haven't hit any on my own test Big Sur machine.  If you see issues, please file them.

**Comment by jmagman** [comment]
I would argue this meta question issue should be closed, and individual issues addressed as reported.  And if there are enough issues to warrant it, create a meta issue like https://github.com/flutter/flutter/issues/61047 or https://github.com/flutter/flutter/issues/36290.

**Comment by jmagman** [comment]
Actually, found one: https://github.com/flutter/flutter/issues/64961

**Comment by stuartmorgan** [comment]
> I would argue this meta question issue should be closed

This isn't a meta question issue, this is tracking the work item of someone working on desktop doing a sanity check of desktop on Big Sur. The fact that there were (off-topic) meta questions asked here doesn't change the original goal of this issue.

**Comment by jmagman** [comment]
🤷‍♀️  @gw280 reached out and asked me.

**Comment by gw280** [comment]
Yep sorry for the confusion. I knew that @jmagman had been doing some work on Big Sur and Apple Silicon, so wanted to check if there were any resources from that effort that already existed. This issue was filed by me to do an initial test/bringup of Flutter Desktop on Big Sur to see what is/isn't broken and triage them accordingly.

Let's keep this thread on that topic from now on.

**Comment by hibeekaey** [comment]
After updating to Big Sur, I get his when I try to run any flutter command:
```
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:678:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1043:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1050:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1071:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by timsneath** [comment]
Closing at this point -- Big Sur is out and lots of people are now using it as their primary desktop OS for desktop development.
