### ISSUE TITLE
ExpansionTile can't be programmatically opened or closed

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7024]
Need a way to close (or open) TwoLevelListItem programmatically

**Comment by eseidelGoogle** [comment]
Thanks for the bug.  Note there is some work soon to be done on TwoLevelListItem in https://github.com/flutter/flutter/issues/4765 and https://github.com/flutter/flutter/issues/4430.

**Comment by HansMuller** [comment]
Sounds like a useful feature. 

Presently TwoLevelSublists aren't expanded initially. We should provide a way to specify the initial value for isExpanded and a TwoLevelListState method for expanding or collapsing the sublist. 

This approach implies that programmatically expanding/collapsing sublists is not the common case. Doing so will require adding a GlobalKey to the sublist so that you can refer to its state later.

Sound OK?

**Comment by jtrunick** [comment]
I imagine it would not be the "usual case" as well. Sounds reasonable to me.

**Comment by zoechi** [comment]
For workarounds see 
- https://stackoverflow.com/questions/48930372/flutter-collapsing-expansiontile-after-choosing-an-item
- https://stackoverflow.com/questions/51378727/flutter-expansiontile-expand-and-collapse-on-click

**Comment by boominadhaprakash** [comment]
Hi @zoechi 

I am very much eager to know about any updates on this issue?

**Comment by dipendra-sharma** [comment]
Use Random Key for a workaround. `key: PageStorageKey("${Random().nextInt(10000)}"),`

**Comment by Alekcei** [comment]
need public state or animate controller

**Comment by aydin-faruk** [comment]
This great solution

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ExpansionTile Collapse',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'ExpansionTile Collapse'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  // selected's value = 0. For default first item is open.
  int selected = 0; //attention

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,title: Text('ExpansionTile Collapse', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
      ),
      body: Container(color: Colors.white,
          child: SingleChildScrollView(
              child : Column( 
                children : [                  
                  ListView.builder(

                      key: Key('builder ${selected.toString()}'), //attention

                      padding: EdgeInsets.only(left: 13.0, right: 13.0, bottom: 25.0),
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemCount: 5,
                      itemBuilder: (context, index) {                        
                        return Column(
                          children: <Widget>[
                            Divider(
                              height: 17.0,
                              color: Colors.white,
                            ), 
                                  ExpansionTile(  

                                        key: Key(index.toString()), //attention                                                                  
                                        initiallyExpanded : index==selected, //attention

                                        leading: Icon(Icons.person, size: 50.0, color: Colors.black,),
                                        title: Text('Faruk AYDIN ${index}',style: TextStyle(color: Color(0xFF09216B), fontSize: 17.0, fontWeight: FontWeight.bold)), 
                                        subtitle: Text('Software Engineer', style: TextStyle(color: Colors.black, fontSize: 13.0, fontWeight: FontWeight.bold),),
                                        children: <Widget>[                                       
                                          Padding(padding: EdgeInsets.all(25.0), 
                                                      child : Text('DETAİL ${index} \n' + 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using "Content here, content here", making it look like readable English.',)
                                                      ) 
                                        ],
                                        onExpansionChanged: ((newState){
                                            if(newState)
                                                setState(() {
                                                  Duration(seconds:  20000);
                                                  selected = index; 
                                                });
                                                else setState(() {
                                                  selected = -1; 
                                                });        
                                        })
                                      ),
                                 
                              ]
                            );
                      },
                        )
                ]
                    ),
          )           
        )
    );
  }
}

```

**Comment by deshario** [comment]
@aydin-faruk How to  add space before every sublist depend on its depper level

**Comment by aydin-faruk** [comment]
> @ aydin-faruk Her alt listeden önce nasıl boşluk eklenir varsayılan [örnekte](https://github.com/flutter/flutter/blob/master/examples/catalog/lib/expansion_tile_sample.dart) derinlik düzeyine bağlıdır[](https://github.com/flutter/flutter/blob/master/examples/catalog/lib/expansion_tile_sample.dart)

you can Use

```
Container(
width: 200.0,
height : 200,) 
```

or 

```
SizedBox(
  width: 200.0,
  height: 300.0,)
```

**Comment by deshario** [comment]
@aydin-faruk I found this better way to do it.
`https://gist.github.com/deshario/9981b58b870a019d60ec889cea0c73f4`

**Comment by aydin-faruk** [comment]
I can't run to your code. Can you share your Entry Model?

**Comment by deshario** [comment]
@aydin-faruk 
```
class Entry {

  String title,key,hub;
  int amount;
  List<Entry>children;

  Entry(
    this.title,
    this.key,
    this.amount,
    [this.children = const <Entry>[]]
  );

  String getTitle() => this.title;
  void setTitle(title) => this.title = title;

  String getKey() => this.key;
  void setKey(key) => this.key = key;

  int getAmount() => this.amount;
  void setAmount(amount) => this.amount = amount;

  List<Entry> getChildren() => this.children;

}
```

**Comment by aydin-faruk** [comment]
class Entry wants "List<Entry>children"
This is vicious circle. What do you think ?

**Comment by deshario** [comment]
@aydin-faruk I'm not sure maybe ... If u have better solution i'm ready to change my code

**Comment by bero93** [comment]
@aydin-faruk  why there is Duration(seconds:20000) in your code?

> This great solution
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'ExpansionTile Collapse',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'ExpansionTile Collapse'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
> 
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
> 
>   // selected's value = 0. For default first item is open.
>   int selected = 0; //attention
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         centerTitle: true,title: Text('ExpansionTile Collapse', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
>       ),
>       body: Container(color: Colors.white,
>           child: SingleChildScrollView(
>               child : Column( 
>                 children : [                  
>                   ListView.builder(
> 
>                       key: Key('builder ${selected.toString()}'), //attention
> 
>                       padding: EdgeInsets.only(left: 13.0, right: 13.0, bottom: 25.0),
>                       shrinkWrap: true,
>                       physics: NeverScrollableScrollPhysics(),
>                       itemCount: 5,
>                       itemBuilder: (context, index) {                        
>                         return Column(
>                           children: <Widget>[
>                             Divider(
>                               height: 17.0,
>                               color: Colors.white,
>                             ), 
>                                   ExpansionTile(  
> 
>                                         key: Key(index.toString()), //attention                                                                  
>                                         initiallyExpanded : index==selected, //attention
> 
>                                         leading: Icon(Icons.person, size: 50.0, color: Colors.black,),
>                                         title: Text('Faruk AYDIN ${index}',style: TextStyle(color: Color(0xFF09216B), fontSize: 17.0, fontWeight: FontWeight.bold)), 
>                                         subtitle: Text('Software Engineer', style: TextStyle(color: Colors.black, fontSize: 13.0, fontWeight: FontWeight.bold),),
>                                         children: <Widget>[                                       
>                                           Padding(padding: EdgeInsets.all(25.0), 
>                                                       child : Text('DETAİL ${index} \n' + 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using "Content here, content here", making it look like readable English.',)
>                                                       ) 
>                                         ],
>                                         onExpansionChanged: ((newState){
>                                             if(newState)
>                                                 setState(() {
>                                                   Duration(seconds:  20000);
>                                                   selected = index; 
>                                                 });
>                                                 else setState(() {
>                                                   selected = -1; 
>                                                 });        
>                                         })
>                                       ),
>                                  
>                               ]
>                             );
>                       },
>                         )
>                 ]
>                     ),
>           )           
>         )
>     );
>   }
> }
> ```

**Comment by HansMuller** [comment]
This was fixed some time ago, see https://api.flutter.dev/flutter/material/ExpansionTile/initiallyExpanded.html

**Comment by 2ZeroSix** [comment]
@HansMuller it doesn't fixed yet.
`initiallyExpanded` applies only for initial state, so the key of the widget should be changed to apply changes
