### ISSUE TITLE
Flutter code mistake in AnimationController  at version 1.22.3

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter#70259]
## Steps to Reproduce

A code mistake in AnimationController at flutter,channel stable , version  1.22.3.
one of it's constructor's param : @required TickerProvider vsync  . is missing a '@'.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hqwlkj** [comment]
> A code mistake in AnimationController at flutter,channel stable , version 1.22.3.
> one of it's constructor's param : @required TickerProvider vsync . is missing a '@'.

I also have this problem after upgrading, how did you deal with it in the end?
