### ISSUE TITLE
Could not find bin\devtools.dart in package devtools. pub finished with exit code 66 in Android Studio

### ISSUE THREAD

**Issue by nhingo-312** [flutter/flutter#70253]
I can't start Devtools from Android Studio even when it's already activated.
It showed me the warning after being activated:
Package devtools is currently active at version 0.9.4.
Resolving dependencies...
+ args 1.6.0
+ async 2.4.2
+ browser_launcher 0.1.7
+ charcode 1.1.3
+ clock 1.1.0-nullsafety.2 (1.1.0-nullsafety.3 available)
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ devtools 0.9.4
+ devtools_server 0.9.4
+ devtools_shared 0.9.4
+ http 0.12.2
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ intl 0.17.0-nullsafety.1 (0.17.0-nullsafety.2 available)
+ logging 0.11.4
+ meta 1.2.3
+ mime 0.9.7
+ path 1.8.0-nullsafety.2 (1.8.0-nullsafety.3 available)
+ pedantic 1.9.2
+ shelf 0.7.9
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.8
+ source_span 1.7.0
+ sse 3.6.0
+ stack_trace 1.9.6
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
+ uuid 2.2.2
+ vm_service 5.5.0
+ webkit_inspection_protocol 0.7.4
Installed executable devtools.
Warning: Executable "devtools" runs "bin\devtools.dart", which was not found
 in devtools.
Warning: Pub installs executables into C:\src\flutter\.pub-cache\bin, which
is not on your path.
You can fix that by adding that directory to your system's "Path" environmen
t variable.
A web search for "configure windows path" will show you how.
Activated devtools 0.9.4.

I also add the path into my system's 'Path' environment variables, it keeps throwing me that messages and then this messages when i try running it:
Could not find bin\devtools.dart in package devtools.
pub finished with exit code 66.

Please help!!!

**Comment by TahaTesser** [comment]
Hi @nhingo-312 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by nhingo-312** [comment]
@TahaTesser Here it is:
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\src\flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\DELL\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

And btw, it seems the reason came from the folder in which Devtools has been installed was dart-sdk/bin, inside flutter/bin instead of flutter/bin itself, I try to run Devtools from dart-sdk/bin and it finally works TT_TT
Thank you so much for your support anyway!!
I am closing this issue after this, thank you!
