### ISSUE TITLE
[iOS AppClip] How to update scribe to write FLUTTER_BUILD_NAME & FLUTTER_BUILD_NUMBER into  iOS AppClip Target ?

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#70260]
1. I have create an app clips target in pure flutter project.
2. but it need to update the `build number` to sync with target `Runner` to avoid build error when every time I updating build number in `pubspec.yaml`.  (Because iOS App Clips need to have some build number with parent target `Runner`)
<img width="583" alt="Screen Shot 2020-11-11 at 10 40 58 AM" src="https://user-images.githubusercontent.com/6405390/98759759-baf8b100-240c-11eb-9755-ab25feac7f1e.png">

3. I know it's should be as bellow in info.plist.     

```xml
<key>CFBundleShortVersionString</key>
<string>$(FLUTTER_BUILD_NAME)</string>
<key>CFBundleVersion</key>
<string>$(FLUTTER_BUILD_NUMBER)</string>
```
4. but I miss the part how to sync this value in `ios/Runner.xcodeproj/project.pbxproj`

I guess it should be related to script, I would like to do some try, but I just wonder where can I do this from.

**Comment by TahaTesser** [comment]
Hi @jerryzhoujw 
Please follow the steps from https://flutter.dev/docs/development/platform-integration/ios-app-clip  and try the official sample https://github.com/flutter/samples/tree/master/ios_app_clip and if you want to follow a video https://www.youtube.com/watch?v=pZgsD1rJXUU

**Comment by jerryzhoujw** [comment]
Hi @TahaTesser , 

I'm a litter different since I use SwiftUI for App Clip. 

Looks like I just miss the `Add the Build Phases` part.

I'll keep check it until I release the App Clip feature.

Thank  you.

**Comment by TahaTesser** [comment]
Hi @jerryzhoujw
Please follow the steps as they are, this is still experimental 
```
 Important: This support is offered experimentally on Flutter version 1.22, may not be stable, and may change in the future.
```
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
