### ISSUE TITLE
[Mac] Rubber band scrolling is not supported when scrolling with the touchpad in Mac OS

### ISSUE THREAD

**Issue by fanchou** [flutter/flutter#70275]

**Comment by darshankawar** [comment]
@fanchou 
Please elaborate on this issue. Is this specific to macOS desktop or mobile ?

**Comment by stuartmorgan** [comment]
Duplicate of #23604. The reason it doesn't overscroll is that currently trackpad scrolling is treated as a series of scroll wheel events due to the lack of framework sorry for trackpad gestures.
