### ISSUE TITLE
Flutter Vibrate on Stop .Untill The User Cancle it

### ISSUE THREAD

**Issue by vipuluthaiah** [flutter/flutter#70276]
```
`   RaisedButton(
                    child: Text('Vibrate for 1000ms'),
                    onPressed: () {
                      Vibration.vibrate(duration: 100 * 60 * 60,  );
                      // Vibration.vibrate(duration: Duration.secondsPerMinute);
                      // Vibration.vibrate(duration:d1.inMinutes *100*60*60);
                      Vibration.vibrate(duration:dur.inMinutes );


                    },
                  ),`
```
i want a button when tapped should vibrate non stop.
Packages only vibrate for some minutes.
Is there any packages or flutter dont support this?

**Comment by abhishekbhambure** [comment]
You might find it at pub.dev

**Comment by vipuluthaiah** [comment]
i did but one packages works for long

**Comment by darshankawar** [comment]
@vipuluthaiah 
You may try to use `Haptic feedback` and see if it works for you. https://api.flutter.dev/flutter/services/HapticFeedback-class.html

Also see [this](https://stackoverflow.com/questions/56413987/how-to-implement-vibration-with-flutter-for-both-android-and-ios) for your reference.

Furthermore, your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
