### ISSUE TITLE
Error: No named parameter with the name 'itemCount'.          itemCount: myData.length,I have just published this:

### ISSUE THREAD

**Issue by azmaltech** [flutter/flutter#70288]
> I have just published this:
> 
>    https://pub.dartlang.org/packages/indexed_list_view
> 
> Similar to a ListView, but lets you programmatically jump to any item, by index. Items may have different sizes, it doesn't matter, the jump is always cheap and it doesn't need to build all widgets between the old and new positions. You can jump millions of items, instantly. Please run the example in the Example tab.
> 
> Currently, the list is always infinite, both to positive and negative indexes. In other words, it can be scrolled indefinitely both to the top and to the bottom. This is useful for some use cases, but it's a serious limitation for others. I don't understand the scrolling API well enough to allow passing lower and upper bounds as to make the list finite, so I would very much appreciate if someone could help me with that.
> 
> Having created that package, it's my opinion that solving https://github.com/flutter/flutter/issues/20608 would make it trivial to programmatically scroll to ListView index in both small and big lists.

_Originally posted by @marcglasberg in https://github.com/flutter/flutter/issues/12319#issuecomment-412762768_

**Comment by azmaltech** [comment]
i am trying to scrolling to an specific index by its index number in at ListView. i used to IndexedListView builder from https://pub.dev/packages/indexed_list_view/example. but i got error in "itemCount: myData.length", so have been unable to use a fix arrange in ListView. 

    class MyHomePage extends StatelessWidget {

    static IndexedScrollController controller =
      IndexedScrollController(initialIndex: 0);

    @override
      Widget build(BuildContext context) {
    
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: IndexedListView.builder(
              controller: controller,
              itemBuilder: (BuildContext context, int index) {
                return Card(
                  child: Container(
                    height: 500,
                    child: Center(child: Text('ITEM $index')),),);},),),
          Container(height: 3.0, color: Colors.black),
          Container(
            color: Colors.grey[800],
            child: Column(
              children: <Widget>[
                GestureDetector(onTap: () {controller.jumpToIndex(5);},
                  child: Container(
                    color: Colors.green,
                    width: MediaQuery.of(context).size.width,
                    height: 100,
                    child: Center(child: Text("Button to go to An specific index", style: TextStyle(color: Colors.white)),),),)],),),],),);}
       }

**Comment by TahaTesser** [comment]
Hi @azmaltech 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample without a third patty package 
Thank you

**Comment by azmaltech** [comment]
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.17.5 at /Users/azmal/FlutterSDK/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (1 available)            
    • iPhone SE (2nd generation) • A5B143ED-2326-4805-83BB-0FC0CA207E59 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @TahaTesser 

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample without a third party package

For issue related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/marcglasberg/indexed_list_view/issues).

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
