### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0x5c (at offset 60)

### ISSUE THREAD

**Issue by VVVVVincent** [flutter/flutter#70280]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter daemon

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x5c (at offset 60)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:446:15)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#11     _StreamController._add (dart:async/stream_controller.dart:642:7)
#12     _StreamController.add (dart:async/stream_controller.dart:588:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#14     _rootRunUnary (dart:async/zone.dart:1138:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#20     _StreamController._add (dart:async/stream_controller.dart:642:7)
#21     _StreamController.add (dart:async/stream_controller.dart:588:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by pedromassangocode** [comment]
Hi @VVVVVincent 
Can you please provide your `flutter doctor -v`, your `flutter daemon --verbose`?
Thank you

**Comment by VVVVVincent** [comment]
> Hi @VVVVVincent
> Can you please provide your `flutter doctor -v`, your `flutter daemon --verbose`?
> Thank you

lhj@lihuijuandeMacBook-Pro ~ % flutter doctor -v

Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error:
Operation timed out, errno = 60, address = clients2.google.com, port = 49251
Oops; flutter has exited unexpectedly.
 
Crash report written to /Users/lhj/flutter_01.log;               
please let us know at https://github.com/flutter/flutter/issues.

**Comment by VVVVVincent** [comment]
I try to delete bin/catch/lokfile,but there is no effect

**Comment by VVVVVincent** [comment]
all the flutter_xx.log show that"FormatException: FormatException: Bad UTF-8 encoding 0x5c (at offset 60)"

**Comment by pedromassangocode** [comment]
Hi @VVVVVincent 
What about `flutter daemon --verbose`? can you provide that?
Also, can you please describe the steps you did to get this issue?

**Comment by VVVVVincent** [comment]
> Hi @VVVVVincent
> What about `flutter daemon --verbose`? can you provide that?
> Also, can you please describe the steps you did to get this issue?


Hi,@pedromassangocode,thanks for your reply~
I opened my flutter project,run the "flutter  packages get "shell, Always display error“Waiting for another flutter command to release the startup lock...”

I have tried the following steps：
> delete bin/catch/lokfile
> restart AS 
> run "kill all  -9 dart"
> run"flutter doctor" 
> run "flutter doctor -v"
all the flutter_xx.log show that"FormatException: FormatException: Bad UTF-8 encoding 0x5c (at offset 60)"

Here are the results of my run “flutter daemon --verbose”:
[  +16 ms] executing: [/Users/lhj/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/lhj/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.8-0-g0b8abb4724
[   +9 ms] executing: [/Users/lhj/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[        ] executing: [/Users/lhj/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git

Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error:
Operation timed out, errno = 60, address = clients2.google.com, port = 49811
Oops; flutter has exited unexpectedly.
 
Crash report written to /Users/lhj/flutter_05.log;               
please let us know at https://github.com/flutter/flutter/issues.

Looking forward to your reply～

**Comment by pedromassangocode** [comment]
Hi @VVVVVincent 
I'm not sure if this was caused by the commands you ran somehow, but without more logs it is a little difficult to find the cause.

Will leave this opened for an expert with the tools to take a look.

**Comment by darshankawar** [comment]
@VVVVVincent 
Are you still facing this issue using latest stable version ?
