### ISSUE TITLE
My flutter app is very slow on Iphone 11 over https

### ISSUE THREAD

**Issue by twn39** [flutter/flutter#70292]
## Details

my app runs very slow, I use devtools to debug and find that it run fast and smooth over http , but slow  and block the UI over https,  It's the same api server.

![截屏2020-11-11 下午10 01 02](https://user-images.githubusercontent.com/1572872/98822178-76e8c900-246b-11eb-95f4-cd1202985a0e.png)

![截屏2020-11-11 下午9 58 20](https://user-images.githubusercontent.com/1572872/98822229-89630280-246b-11eb-9bf2-3038b8b8cfb0.png)

I don't know it is the issue of flutter or iphone system. 

my api server:

```
curl -v "https://poetrydev.lightfly.cn"                                                                                  (base) 22:02:49
*   Trying 129.211.11.159...
* TCP_NODELAY set
* Connected to poetrydev.lightfly.cn (129.211.11.159) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=poetrydev.lightfly.cn
*  start date: Sep 30 18:16:51 2020 GMT
*  expire date: Dec 29 18:16:51 2020 GMT
*  subjectAltName: host "poetrydev.lightfly.cn" matched cert's "poetrydev.lightfly.cn"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc0bd00dc00)
> GET / HTTP/2
> Host: poetrydev.lightfly.cn
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< content-type: Application/json;charset=utf-8
< vary: Accept-Encoding
< cache-control: no-cache, private
< date: Wed, 11 Nov 2020 14:03:07 GMT
< x-robots-tag: noindex
< server: Microsoft-IIS
<
* Connection #0 to host poetrydev.lightfly.cn left intact
{"code":0,"data":{"title":"poetry api server","version":"0.1.0","stage":"dev"},"msg":"ok"}* Closing connection 0
```

**Iphone version:  11** 
**Flutter version:**
```
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (13 天前) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

**Comment by pedromassangocode** [comment]
Hi @twn39 
Can you please elaborate what is exactly wrong?
Can you please provide a minimal reproducible code sample, the actual vs expected results and the steps in how to reproduce?

Thank you

**Comment by twn39** [comment]
@pedromassangocode Sorry for that, after search by google these days, I found this issue is relate to #55586 .  It seems have no good solution but change the certificate service.

**Comment by pedromassangocode** [comment]
Hi @twn39 
From the logs I can see that you may be located in China and a mentioned in https://github.com/flutter/flutter/issues/55586#issuecomment-714543427 this issue may still happen in some locations and the only workaround is to configure you server properly.

I'm going to close this as per https://github.com/flutter/flutter/issues/55586#issuecomment-714543427 there is not much Flutter/Dart can do about this. If you disagree please feel free to comment and I will reopen it.
Thank you

**Comment by twn39** [comment]
Hi @pedromassangocode 
You can close this issue, thanks a lot for help.
