### ISSUE TITLE
nested .gitignore breaks ios projects

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7029]
## Steps to Reproduce

1. `flutter create MyApp`
2. Push entire project (`MyApp/`) to a repo (anywhere)
3. `rm -rf MyApp`
4. `git clone https://repoStore.com/{username}/MyApp.git`
5. `cd MyApp`
6. `flutter run`
7. App explodes

The main error is `The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Due to the fact that `MyApp/ios/.gitignore` exists and ignores a bunch of crucial files, `flutter run` simply doesn't do enough when you have a 'fresh clone' of a repo.

## Solution
> Install CocoaPods `brew install cocoapods` or `gem install cocoapods`

- Inside `MyApp/ios/` run the command `pod install`

This will regenerate all the files that the `.gitignore` left out.

Edit:
## Further Realizations
Running `pod install`, while fixing the `flutter run` issue (project actually runs and loads, might break the ios build. The following list of files are showing as changed or need to be added to the repo after running `pod install`:
```
ios/Pods/Pods.xcodeproj/project.pbxproj (modified)
ios/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata (newly created)
ios/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-Runner.xcscheme (modified)
ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-resources.sh (modified)
ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig (modified)
ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig (modified)
ios/Runner.xcodeproj/project.pbxproj (modified)
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (modified)
ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (modified)
```

**Comment by collinjackson** [comment]
tested with ```
flutter create myapp && cd myapp && git init && git add . && git commit -m "init" && rm -rf * && git checkout . && flutter run
```
