### ISSUE TITLE
RaisedButton.icon is not found by CommonFinders

### ISSUE THREAD

**Issue by yerzhant** [flutter/flutter#70293]
The following code does not find a button:

`expect(find.byType(RaisedButton), findsOneWidget);`

which is created like this (inside a Column widget, if it makes sense):
```
                  RaisedButton.icon(
                    onPressed: () {},
                    icon: const Icon(Icons.refresh),
                    label: const Text('ОБНОВИТЬ'),
                  ),
```
If a button is created with RaisedButton (w/o icon factory) then the finder find the button.

[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)

**Comment by HansMuller** [comment]
RaisedButton.icon and its replacement, Elevatedbutton.icon, are factories that create an instance of a private class that extends RaisedButton or ElevatedButton.

**Comment by yerzhant** [comment]
Ok, thanks.

**Comment by yerzhant** [comment]
Is there any way to tap an _ElevatedButtonWithIcon (i.e. created with ElevatedButton.icon)?

**Comment by yerzhant** [comment]
Tried to find by text and icon and key. Non of them worked out.

`    await tester.tap(find.byKey(const Key('toy-card-page-add-button')));`
`    await tester.tap(find.byIcon(Icons.add_shopping_cart));`
`    await tester.tap(find.text('ДОБАВИТЬ В КОРЗИНУ'));`
