### ISSUE TITLE
: error: cannot find symbol import io.flutter.FlutterInjector;                  ^   symbol:   class FlutterInjector   location: package io.flutter

### ISSUE THREAD

**Issue by Shubham1998k** [flutter/flutter#70297]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Shubham1998k** [comment]
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:11: error: cannot find symbol
import io.flutter.FlutterInjector;
                 ^
  symbol:   class FlutterInjector
  location: package io.flutter
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
    final FlutterInjector injector = FlutterInjector.instance();
          ^
  symbol:   class FlutterInjector
  location: class VideoPlayerPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.0\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
    final FlutterInjector injector = FlutterInjector.instance();
                                     ^
  symbol:   variable FlutterInjector
  location: class VideoPlayerPlugin
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Shubham1998k** [comment]
Please help me in this issue

**Comment by darshankawar** [comment]
@Shubham1998k 
Seems you are not on latest stable version (1.22.3). If so, please upgrade to latest which should resolve your issue.
See [this](https://github.com/flutter/flutter/issues/69754) similar issue for reference.
Closing this as duplicate.

**Comment by Ahmed11300** [comment]
There is problem in VideoPlayer package so you need to go to pubspec.yaml and delete the package then press Pup get or     ~>flutter pub get . Until they solve the package problem

**Comment by realappie** [comment]
@Ahmed11300 What problem are you talking about? Any links would be useful, thanks!
