### ISSUE TITLE
misleading information displayed in Flutter Debug Loader App

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7030]
Information Text:
```
This is a hot-relead-enabled debug-mode Flutter
application. To launch this application, please
use the "flutter run" command. To be able to
launch a Flutter application in debug mode from
the device, please use "flutter run --no-hot". To
install a release mode build of this application on
your device, use "flutter install".
```
However, `flutter install` (afaik) just pushes what ever application is built in `build/` to your device. So if the last build you did was a hot-reload application, this is what gets pushed onto your device. Which is not intuitive with what is described in the message on device.

If the intent for `flutter install` was to create a release version of your application, then it should be changed to do this, which is basically running `flutter run --release` or `flutter build ios`.

## Steps to Reproduce
- `flutter run`
- terminate the dev cycle `q`
- uninstall the app from device
- `flutter install`
- open app on device
> Still hot-reload version of app.

**Comment by Hixie** [comment]
The text was aspirational. We should make `flutter install` imply `flutter build --release`, and we should make _that_ imply the appropriate kind of `build` for the current device(s).

But it's a moot point, because the loader is gone now. Hot reload works without a loader.
