### ISSUE TITLE
FocusTraversal issues in GridView

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#70303]
## Problem

I'm working on a project in Flutter for Android TV and Deskop. While FocusTraversal mostly works fine, I'm experiencing some glitches in GridView.

My code creates something like a GridView.builder(itemBuilder(_, _) => RawMaterialButton(node: _node, ...))
The Buttons are traversed correctly with the keyboard most of the time, but there are still some glitches which can be seen in the following video.

I tried wrapping GridView with FocusTraversalGroup() with WidgetOrderTraversalPolicy() and I additionally tried wrapping RawMaterialButton() with FocusOrder(order:x) which had no effect. The value of order can also be seen in the video next to the movie-title.

https://drive.google.com/file/d/132G2iOSBcHhIDbVZu4s0Xg-6cG91-5Pd/view

## Minimum example

Run this as a Windows Desktop App or in an Android TV Emulator, and navigate with the arrow-keys (or d-pad)... You will notice how the traversal, sometimes does not follow the navigation.

Left, left, left, down, left, right, right, left, down down down down left

At some point, you will notice, that right does not result a change from "grid X" to "grid X+1", but rather "grid X" to "grid X-8", and from there navigating left will result in "grid X+8" instead of "grid X-1". 

```dart

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: GridView.builder(
        itemCount: 100,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 9,
            // childAspectRatio: 0.6666,
            childAspectRatio: 1,
            crossAxisSpacing: 0,
            mainAxisSpacing: 0),
        itemBuilder: (ctx, index) => RawMaterialButton(
          onPressed: () {},
          child: Text('Grid $index'),
        ),
      )),
    );
  }
}
```

## flutter doctor -v

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.194, on Microsoft Windows [Version 10.0.20251.1], locale en-AT)
    • Flutter version 1.24.0-8.0.pre.194 at D:\Projects\Development\Flutter\flutter-sdk-win
    • Framework revision 018467cdb1 (10 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\adonis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30709.132
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\adonis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.20251.1]

• No issues found!
``` 

Cheers,

**Comment by darshankawar** [comment]
@ad-on-is 
I believe this is the same issue as you reported [here](https://github.com/flutter/flutter/issues/67814).
Let's track this in original [issue](https://github.com/flutter/flutter/issues/67814).  
Closing this from here.

**Comment by ad-on-is** [comment]
Yes, I thought I was supposed to open a new one, since it was stated in the  the original one, which was closed and all the labels were removed. Sorry for duplicating and confusion.
