### ISSUE TITLE
Procure and set up an Apple Silicon M1 mac mini in the lab

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70308]
We will need an ARM Mac in the lab to test [host](https://github.com/flutter/flutter/issues/60118) and [target](https://github.com/flutter/flutter/issues/60113) support.  We'll need to return the DTK test mac mini we have to Apple at some point.

They are shipping now: https://www.apple.com/shop/buy-mac/mac-mini

**Comment by jmagman** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=1147828

**Comment by Sanmejie** [comment]
> 另请参阅https://bugs.chromium.org/p/chromium/issues/detail?id=1147828

Permission denied.

**Comment by jmagman** [comment]
Sorry for the internal link, it was a note for the infrastructure team.  Infrastructure is one of the rare corners of Flutter where we can't share everything due to security concerns.  Thanks for your understanding!

**Comment by apereira2001** [comment]
Hey guy,

I'm using a Macbook Pro M1. 

flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0 20A2411 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.


When a try to install cocoapods I received the following error message:

sudo gem install cocoapods
Password:
ERROR:  Loading command: install (LoadError)
	dlopen(/Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle - /Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
apereira@apereiras-MacBook-Pro m1_app % sudo gem update                  
ERROR:  Loading command: update (LoadError)
	dlopen(/Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle - /Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

Thanks in advanced for any help.

**Comment by zgosalvez** [comment]
@apereira2001, have you tried running the terminal using Rosetta? https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-655870749

**Comment by apereira2001** [comment]
Hi,

I've tried running the terminal using Rosetta, but I can't install CocoaPods.

I've tried to run gem list and received de following message:

sudo gem list
ERROR:  Loading command: list (LoadError)
	dlsym(0x7fdcc654c9c0, Init_date_core): symbol not found - /Library/Ruby/Gems/2.6.0/gems/date-3.0.1/lib/date_core.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

Thanks in advanced for any help.

**Comment by jmagman** [comment]
@zgosalvez You don't need to run flutter command line tools in a Rosetta terminal, it will automatically use Rosetta for you.
@apereira2001 That's a CocoaPods crash.  You should [file an issue](https://github.com/CocoaPods/CocoaPods/issues) with them so they can investigate while they work on Apple Silicon support.

This is an issue tracking a specific request from our infrastructure team.  If you see issues running on an M1 we want to hear about it!  Please file new issues, completely filling out the template, and we'll triage and take a look.

**Comment by jeveloper** [comment]
I am 100% sure that back in June, Google received mac minis with A12Z chip.

**Comment by babyfacehugg** [comment]
Ok thanks

**Comment by xster** [comment]
@godofredoc: what do you think? Since this might have a long cycle, we might have to start thinking for Q1 planning

**Comment by godofredoc** [comment]
There was already one in the lab, are we planning to get it back or should we plan to get a new one?

**Comment by jmagman** [comment]
We should plan to get a new one.

> We'll need to return the DTK test mac mini we have to Apple at some point.

Also, we need a real production M1 device because Android emulators will never work work on the DTKs due to virtualization issues.

**Comment by xster** [comment]
+1. Let's use production devices. I suspect we'll also need more than one going forward.

**Comment by jmagman** [comment]
Even for the first batch it would be great to have two: one each with tethered iOS and Android devices.

**Comment by timsneath** [comment]
Hmm... did we not order a few? I thought we were going to try and get these done with 2020 budget? Now is the time if it's going to land before the end of the fiscal :) @tvolkert

**Comment by godofredoc** [comment]
Closing this bug, we already have a Mac M1 running on staging.
