### ISSUE TITLE
[cocoon] app_dart test flake in PushBuildStatusToGithub

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#70312]
The PR had no changes related to this code, and only introduced log files. This is reproducible with

```
pub run test --test-randomize-ordering-seed=3238131233
```

on flutter/cocoon#a05c467

[Link to run](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863900273953135664/+/steps/app_dart/0/stdout)
```
00:30 [32m+29[0m[33m ~1[0m[31m -1[0m: test/request_handlers/push_build_status_to_github_test.dart: PushBuildStatusToGithub in non-development environment updates GitHub and datastore update if statuses have changed since last update - multiple branches [1m[31m[E][0m[0m
  NoSuchMethodError: The method '>' was called on null.
  Receiver: null
  Tried calling: >(1605123351316)
  dart:core                                                 int.<
  package:cocoon_service/src/service/datastore.dart 211:38  DatastoreService.queryLastStatusUpdate.<fn>
  dart:collection                                           ListMixin.reduce
  package:cocoon_service/src/service/datastore.dart 210:38  DatastoreService.queryLastStatusUpdate
```

**Comment by eseidelGoogle** [comment]
Tests here: https://github.com/flutter/cocoon/tree/master/app_dart

Attempted with 2a91fe32383704560017ab211a1571558715e4e6 on mac.

dart test --test-randomize-ordering-seed=3238131233

Passed  fine.

It's possible this can be closed?  Or it's possible this is just a flake and it would need a different seed to reproduce reliably now?

**Comment by CaseyHillers** [comment]
Thanks Eric, we recently cleaned up this code and I am not able to reproduce this either. Closing.
