### ISSUE TITLE
[Pigeon] add support for C/C++ handlers

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#70310]
The public platform channels API doesn't support this but we support it internally.  We'd have to make that API public, create a new code generator and somehow make it easy to get the generated code compiled and linked into the plugin/app.

related issue: https://github.com/flutter/flutter/issues/70254

**Comment by Sunbreak** [comment]
As multi-threaded callback on Dart function is quite hard: https://api.flutter.dev/flutter/dart-ffi/Pointer/fromFunction.html

> The returned function address can only be invoked on the mutator (main) thread of the current isolate. It will abort the process if invoked on any other thread.

We are working heavily on Windows/macOS C/C++ plugin implementation

Any update for `Pigeon` support for `C/C++`?

**Comment by gaaclarke** [comment]
@Sunbreak There's currently no timetable for this feature.  There is more and more interest to contribute to Pigeon internally and from external contributors, but I wouldn't expect it in the next 6 months.
