### ISSUE TITLE
RoundedRectangleBorder.copyWith takes a BorderRadius rather than the constructors BorderRadiusGeometry

### ISSUE THREAD

**Issue by olof-dev** [flutter/flutter#70313]
Is there a reason that the `copyWith` method of `RoundedRectangleBorder` takes a `BorderRadius`, when the class constructor takes a `BorderRadiusGeometry`? I'm trying to implement a variant of the class, so thought I'd check to see that I'm not misunderstanding something.

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L39-L40

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L96-L101

**Comment by jason-simmons** [comment]
@HansMuller looks like the various `copyWith` methods added in https://github.com/flutter/flutter/commit/26dc70dc18864a95140ac96dfd8afc410f5573b0 should take a `BorderRadiusGeometry`

**Comment by HansMuller** [comment]
Yes they should. That's an easy fix; I'll make one shortly.

**Comment by payam-zahedi** [comment]
@HansMuller I just created a PR and attached it to this Issue.
