### ISSUE TITLE
Need to rationalise the names of the *Input* and *Field* classes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7031]
As of today:

InputField is not an Input and is not a FormField. It contains a RawInput.
InputContainer is not an Input and is not a Container.
Input builds an InputContainer containing an InputField.
InputFormField extends FormField and builds an Input.

This is very confusing. We should rationalise these names.

See also https://github.com/flutter/flutter/issues/7017 about documenting all this better.

cc @HansMuller, @mpcomplete, @abarth

**Comment by HansMuller** [comment]
Also, per https://github.com/flutter/flutter/pull/6733#discussion_r86873884, in the Material spec and in many GUI toolkits, Input is called TextField.

**Comment by mpcomplete** [comment]
Proposal:

Input => TextField (to match Material spec)
InputContainer => TextFieldDecorator
InputField => TextFieldEditable
InputFormField => TextFormField

Let's decide on this soon. The longer we wait, the more people we will break.

**Comment by Hixie** [comment]
InputContainer/TextFieldDecorator isn't just about Inputs/TextFields. How about something like ControlLabel or something for that one?

Form uses FormFields. TextField and FormField sound like they'd be related, but aren't in this model.

I like that today InputFormField is a FormField.

I do like the TextField name, that makes sense to me. We could find another term for FormField, maybe FormControl? then you can have TextFieldControl for the version of TextField that is a Control. Or TextFieldFormControl but that's a bit long.

RawInput could be RawTextField. Today's InputField is between TextField and RawInput, maybe PlainTextField? But that suggests it's a "plain-text field", as opposed to a "plain text-field". Maybe UndecoratedTextField?

What does TextField add? Could we drop it and require that people either use TextFieldControl or ControlLabel+PlainTextField? In which case we could rename that latter one to just TextField? But then it's weird that TextFieldControl does more than just add the FormControl to the TextField, it also adds the ControlLabel...

In general, if Foo is a class, then BarFoo should be a subclass of Foo that adds bar-related functionality, and FooBaz should be a helper class for Foos that handles baz-related logic.

**Comment by mpcomplete** [comment]
I like UndecoratedTextField. It's the most accurate description. I suspect most people won't use it anyway.

TextField is the Material-spec implementation and should be most common, so I think we should keep that.

I also like the Foo => BarFoo naming convention. I was trying to avoid the repetition of "Field", but maybe that's not worth it.

Something about "FormControl" seems wrong to me. Maybe it's just me.

New proposal:

RawInput => RawTextField
Input => TextField
InputContainer => TextFieldDecorator
InputField => UndecoratedTextField
InputFormField => TextFieldFormField or TextFieldFormControl (these options are my least favorite)

**Comment by Hixie** [comment]
InputContainer is for any kind of form control, right? Not just text fields.

In general I would avoid a name FooBar if both Foo and Bar are classes because that's confusing (is it a subclass of Bar, or a utility class for Foo?).

**Comment by Hixie** [comment]
RawTextField/UndecoratedTextField/TextField seems good to me.

I think we should broaden the scope of renames to include Form, FormField, and FormState (which by the way has no documentation). (Not saying we need to rename all of these, just that including them in the list is good for noticing if your names are consistent.)

**Comment by mpcomplete** [comment]
Oops you're right, I glossed over InputContainer for some reason. That one's hard to name, because it's such a weird grab bag of stuff. WidgetThatAddsSomeTextFieldLikeDecorationsToChild would be accurate...

**Comment by Hixie** [comment]
Maybe InputFieldDecorator or something like that?

**Comment by abarth** [comment]
Here's a slate:

- Form
- FormState
- FormAssociatedWidget
- RawEditableText
- EditableText
- InputFieldDecorator
- TextField
- TextFormField

**Comment by Hixie** [comment]
What is FormAssociatedWidget?

**Comment by abarth** [comment]
Yes.  It's a base class for other widgets, which with tend to name either with a "Widget" suffix (e.g., AnimatedWidget) or with an "able" suffix (e.g., Pageable).

**Comment by Hixie** [comment]
One thing is that EditableText is material-specific (it uses material UI for its popup menu). It's weird that we'd have a RawEditableText in widgets/ an EditableText + TextField in material/. I think Matt's UndecoratedTextField/TextField might be better.

**Comment by abarth** [comment]
Ah, I missed that UndecoratedTextField was material-specific.  It's usually a bad pattern to name something after what it isn't.  Maybe RawTextField?

**Comment by mpcomplete** [comment]
FormAssociatedWidget is a mouthful. It's not just a base class. It ends up getting used for most other widgets that are more complicated than Input. (e.g. for sliders, you may want to use the field value as part of the label and maybe the color, like the expansion panels demo does, so you can't use a premade widget).

**Comment by abarth** [comment]
New slate:

- Form
- FormState
- FormField

- RawTextInput
- TextInput
- TextField

- InputDecorator

(In this slate, Input disappears an becomes an implementation detail of TextField)

**Comment by mpcomplete** [comment]
TextField has one limitation (though it's easily addressed). We don't expose the `onChanged` handler, so you can't respond to each individual keypress (e.g. if you want to update an autocomplete search field). This is https://github.com/flutter/flutter/issues/7210

**Comment by mpcomplete** [comment]
InputFormField (proposed TextField) now has feature parity with Input, so we could merge the two.

**Comment by mpcomplete** [comment]
New slate from latest in-person discussion:

* Form
* FormState
* FormField
* EditableText (the widgets version)
* MaterialEditableText (the material version)
* TextField (same as old InputFormField, which Input is now an impl detail of)
* InputDecorator

**Comment by Hixie** [comment]
SGTM. Let's do it.

**Comment by sethladd** [comment]
So many merges! Did we address this, or more to come?

**Comment by Hixie** [comment]
More to come. :-(

**Comment by abarth** [comment]
This issue is going to slip unto next quarter.

**Comment by abarth** [comment]
New proposal:

* Form
* FormState
* FormField
* EditableText (the widgets version)
* TextField
  - all-sing, all-dance text field control
  - input decoration is optional, but enabled by default
  - not a form field
* TextFormField
  - All the dancing and singing of TextField but also a FormField
* InputDecorator

**Comment by abarth** [comment]
Also, InputDecoration, which bundles up all the consty parameters to InputDecorator to make them easier to deal with.

**Comment by Hixie** [comment]
SGTM
