### ISSUE TITLE
Dialogs don't get out of the way of system padding (e.g. from on-screen keyboards)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7032]
I pop a dialog with a single autofocussing text field.
- ~~The keyboard doesn't pop up (it does in e.g. the android system settings wifi "add network" dialog)~~ https://github.com/flutter/flutter/issues/7035
- ~~Once I pop the keyboard up, the text behind the dialog all disappears. I'm using nested Scaffolds, which is likely the issue.~~ https://github.com/flutter/flutter/issues/7036
- The dialog doesn't move (and so gets covered by the keyboard).
- ~~Also the text field uses my primary color and my buttons use the accent color. The dialog has no black at all.~~ That's what the spec says. I added a title and it looks ok.
- ~~Even the cursor is the primary color, unlike the text itself, which is black. this looks weird.~~ That's what the spec says.

code to show the dialog:
```dart
  Future<String> showMessageDialog() {
    String result;
    return showDialog(
      context: context,
      child: new Form(
        child: new Builder(
          builder: (BuildContext context) {
            return new AlertDialog(
              content: new Block(
                children: <Widget>[
                  new InputFormField(
                    labelText: 'Message',
                    autofocus: true,
                    onSaved: (InputValue value) {
                      result = value.text;
                    },
                  ),
                ],
              ),
              actions: <Widget>[
                new FlatButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: new Text('CANCEL'),
                ),
                new FlatButton(
                  onPressed: () {
                    Form.of(context).save();
                    Navigator.pop(context, result);
                  },
                  child: new Text('SEND'),
                ),
              ],
            );
          }
        ),
      ),
    );
  }
```

The app has a Scaffold containing a Block. The dialog above is triggered from a FlatButton in that Block.

**Comment by ds84182** [comment]
Wrapping this code around a dialog fixed this issue for me:

```dart
class _SystemPadding extends StatelessWidget {
  final Widget child;

  _SystemPadding({Key key, this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var mediaQuery = MediaQuery.of(context);
    return new AnimatedContainer(
        padding: mediaQuery.padding,
        duration: const Duration(milliseconds: 300),
        child: child);
  }
}
```

With that ^ dialogs animate *almost* exactly how they do on Android, but I don't know if that's correct for iOS.

**Comment by abarth** [comment]
Neat.

**Comment by Hixie** [comment]
Moving out of m3 since this is not one of our current priorities, though it is something we want to work on. Please let us known if this is something that's affecting you and you need it resolved sooner.

**Comment by Mohammed90** [comment]
Not sure if the API behavior has changed since March, but now @ds84182's snippet needs the following edit for the correct behavior:
```dart
// ...
padding: mediaQuery.viewInsets,
// ...
```

**Comment by eggzotic** [comment]
This broken for CupertinoAlertDialog, sadly. For identical code, but with AlertDialog it works great. Possible to fix CupertinoAlertDialog also?

**Comment by lukepighetti** [comment]
We need more support from Flutter team for views that move out of the way of keyboards.

**Comment by lukepighetti** [comment]
Might I recommend something in this vein.

```dart

class KeyboardAvoiding extends StatelessWidget {
  final Widget child;
  final Curve curve;
  final Duration duration;
  final double kFactor;

  KeyboardAvoiding({
    this.child,
    this.curve = Curves.easeInOut,
    this.duration = const Duration(milliseconds: 200),
    this.kFactor = 1.0,
  });

  @override
  Widget build(BuildContext context) {
    final _verticalOffset = MediaQuery.of(context).viewInsets.bottom * -kFactor;

    return AnimatedContainer(
      duration: duration,
      curve: curve,
      transform: Matrix4.translationValues(
        0.0,
        _verticalOffset,
        0.0,
      ),
      child: child,
    );
  }
}
```

**Comment by zoechi** [comment]
Please create a new issue. This one is long closed.

**Comment by lukepighetti** [comment]
@zoechi it's better to open new issues than reopen old ones?

**Comment by MilkBiscuit** [comment]
I just created a new issue  https://github.com/flutter/flutter/issues/27629

**Comment by DokkarRachidReda** [comment]
`margin: MediaQuery.of(context).viewInsets,`  solved the problem for me

**Comment by ride4sun** [comment]
> `margin: MediaQuery.of(context).viewInsets,` solved the problem for me

Where do you apply the margins. I guess on a Container and the TextField is the Child. Or is it a Container which wraps the Dialog?
I see the Problem on IOS but not on IOS. I see so many of these Issues around that problem created but I have a hard time fixing this.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.0)
[✓] Connected device (1 available)

**Comment by ShohidulProgrammer** [comment]
you can add SingleChildScrollView with reverse = true

**Comment by hienhodeveloper** [comment]
@ShohidulProgrammer  Best answer!!
