### ISSUE TITLE
[google_maps_flutter] Refactor Map widget creationParams

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#70330]
The current version of the `buildView` method in Google Maps' platform interface is completely oriented towards the Method Channel implementation (there are other examples, but this is the worst offender).

The core plugin eagerly transforms everything into a JSON-ifiable object (`Map<String, dynamic>`) here:

https://github.com/flutter/plugins/blob/0d5dd3a2d93ec545653ee26a3c59b72459fb51ac/packages/google_maps_flutter/google_maps_flutter/lib/src/google_map.dart#L227-L235

This causes problems in the web implementation, that normally needs one extra step to undo that transformation so it can operate with less _stringly typed_ data structures.

Another problem of this, is that Controller methods operate with the normal data structures until it's strictly necessary to convert them, so any fixes in Web need to verify the "initial geometry case" (handling the early serialization), and the "controller injected changes" (which don't serialize and handle the proper data structures).

## Proposal

1. Introduce a new `buildView` platform method that uses semantic parameters and proper types (the same as the Controller methods)
2. Keep the supplied types for as long as possible, and convert those ".toJson" only when doing a MethodChannel call.
3. Remove all the code required to handle the early serialization from the interface and the web implementation.

_This would allow web to remove a good chunk of [this file](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart), which deals with converting `rawOptions` to proper types again._

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/3539 half fixes this problem. It now passes more structured data, but the inner `options` map is still being past in post-serialized form because `GoogleMapOptions` needs to be refactored out of the app-facing package (and its construction from a widget moved into the widget class) and into the interface package so that it can be used as a parameter.

Doing that should probably involve some thought about what changes if any could be made to reconcile it with the similar class in the web plugin.

**Comment by ditman** [comment]
Yes, definitely the GoogleMapOptions (or similar) should be extracted to the common interface, and used throughout. This is being serialized just because it's what the method channel wants. It should be serialized only in the method_channel implementation.

In web, we could remove/simplify 100s of lines of code and tests that parse the JSON to something the web SDK understands.
