### ISSUE TITLE
If I switch apps while typing text, the text is lost

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7033]
1. Type in a Flutter text field on Android.
2. Double tap the square system button to switch to another app. I was switching to the "Add network" dialog in wifi settings.
3. Double tap back. The text you were typing is gone.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/6827 is possibly related?

**Comment by Hixie** [comment]
I don't think so; the app itself isn't being shut down (if it was, we'd lose more than just the text field, we'd go back to the start of the app).

**Comment by jason-simmons** [comment]
The task switcher triggers a pause/resume cycle, and after the activity resumes Android calls FlutterView.onCreateInputConnection.

The TextInputPlugin will create an InputConnection based on the "incoming state" supplied by RawInputState in the Flutter framework.  However, the plugin's "incoming state" may be out of sync with the "outgoing state" sent to the framework by the InputConnection after each change to the text.

How should the incoming state be kept in sync?  Is the framework supposed to echo each outgoing state change back to the incoming state?  Or should the incoming state be updated internally within the plugin?

@abarth
