### ISSUE TITLE
Flutter tools that derive language versions from pubspec.yaml should interpret a missing min constraint as 2.7

### ISSUE THREAD

**Issue by leafpetersen** [flutter/flutter#70349]
Per [discussion](https://github.com/dart-lang/sdk/issues/44013), we are changing the interpretation of a missing min sdk constraint (either because the constraint has no lower bound or because there is no constraint at all) as implying language version 2.7 instead of the latest language version.  I believe that there is at least one tool in flutter which derives this to produce a package_config.json, and hence must be updated.

This is blocker for beta, and will need to be cherry picked if it doesn't make the beta branch cut.

cc @pcsosinski @mit-mit @franklinyow 

cc @jonahwilliams @amirh @zanderso @jakemac53 @natebosch

**Comment by mit-mit** [comment]
We have Flutter tools that look directly at the pubspec? That is new to me. I would have thought that they just look at the package_config.json; that seems better from a layering point of view?

**Comment by jakemac53** [comment]
This is the tool that _generates_ the `package_config.json` for at least the engine repo. It does not use pub for fetching third party deps (it uses the DEPS file similar to the sdk).

**Comment by zanderso** [comment]
It looks like this is already defaulting to 2.8

https://github.com/flutter/engine/blob/master/tools/generate_package_config/bin/generate_from_legacy.dart#L49

Should it be changed to 2.7?

**Comment by zanderso** [comment]
Anyway, here is a PR to change 2.8 -> 2.7 just in case it's needed: https://github.com/flutter/engine/pull/22469

**Comment by zanderso** [comment]
I've landed the change in the engine. AFAIK that is the only spot so I will close this. Still interested in the 2.7 vs. 2.8 question though.
