### ISSUE TITLE
Checkbox widget cannot set default and active images.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#70347]
Checkbox widget cannot set default and active images.

**Comment by darshankawar** [comment]
@gionchat 
Please elaborate on your issue along with providing `flutter doctor -v` and a use case where you find this limitation.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
