### ISSUE TITLE
Option to disable microphone usage on the camera plugin on iOS / Android

### ISSUE THREAD

**Issue by kleysonr** [flutter/flutter#70342]
I'm using the camera plugin on my flutter app but apple is asking me to give a meaningful description to NSMicrophoneUsageDescription for the microphone usage even not using it.

Is it possible disable the ask permission for microphone for iOS and Android ?

If not, please add it.

**Comment by jonahwilliams** [comment]
@kleysonr this doesn't seem like a bug with our continuous integration system, why did you use infrastructure label?

**Comment by kleysonr** [comment]
Hi, @jonahwilliams 

```why did you use infrastructure label?```

It was not intentionally. My bad.

**Comment by darshankawar** [comment]
@kleysonr 
Since the permissions are implemented using `permission_handler`, you may check out [this](https://github.com/Baseflow/flutter-permission-handler/issues/273) issue and see if it answers your question.

**Comment by kleysonr** [comment]
Great @darshankawar.

It worked.
