### ISSUE TITLE
Keyboard doesn't pop up for autofocussed text fields in dialogs.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7035]
We've gone back and forth on this a bunch but I've discovered a case where autofocussed fields do get the keyboard to autopopup: dialogs with text fields where the field is focused when the dialog shows.

See, for instance, the Android wifi system settings "Add Network" dialog.

cc @mpcomplete

**Comment by mpcomplete** [comment]
One solution is to auto show the keyboard whenever the Input's `autofocus` property is true.

**Comment by mpcomplete** [comment]
We need to strike a balance between https://github.com/flutter/flutter/issues/6603 and this.

Sometimes, like in the dialog case in this bug, we want to show the keyboard immediately upon focus. Other times, like in #6603, an input can re-acquire focus - and we don't want to show the keyboard then. Using autofocus as a signal for auto-showing the keyboard seems like a reasonable compromise.
