### ISSUE TITLE
Fluter engine crash in customer:money

### ISSUE THREAD

**Issue by meiwin** [flutter/flutter#70350]
customer:money reported crash on the Flutter engine.

```
Thread 18 (id: 0x0000af03) CRASHED [EXC_BAD_ACCESS / KERN_INVALID_ADDRESS @ 0x00000100 ]Show exception record
0x000000010604661c(Flutter + 0x003e661c)		
0x0000000106046604(Flutter + 0x003e6604)		
0x000000010613e080(Flutter + 0x004de080)		
0x000000010613c7bc(Flutter + 0x004dc7bc)		
0x000000010613c3a0(Flutter + 0x004dc3a0)		
0x00000001061be4e0(Flutter + 0x0055e4e0)		
0x0000000106176c04(Flutter + 0x00516c04)		
0x00000001f6849ca4(libsystem_pthread.dylib + 0x00001ca4)	
```

There isn't reproduction step available at the moment.

**Comment by meiwin** [comment]
@flutter-symbolizer-bot defa8be2b10650dad50dfee9324ed8d16eeec13f release arm64

**Comment by mraleph** [comment]
@flutter-symbolizer-bot engine#defa8be2b10650dad50dfee9324ed8d16eeec13f release arm64 internal ios

**Comment by mraleph** [comment]
@flutter-symbolizer-bot engine#defa8be2b10650dad50dfee9324ed8d16eeec13f release arm64 internal ios https://github.com/flutter/flutter/issues/70350#issue-741245225

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/70350#issue-741245225 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
Well that didn't work :D I wonder if the hash is incorrect.

**Comment by mehmetf** [comment]
or may be the format is incorrect? Trying again.

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot #70350 (comment) internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/70350#issue-741245225 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
Bingo.

security_context_macos.cc problem again.

**Comment by mehmetf** [comment]
This was fixed a couple of weeks back. The error is coming from an older version of customer's binary.

**Comment by mraleph** [comment]
I will fix the RegExp :)
