### ISSUE TITLE
FocusTraversal issues with multiple ListViews and GridView

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#70364]
## Problem

I encountered some FocusTraversal issues with ListView combined with another ListView or GridView when navigating on Desktop with arrow-keys or on an Android TV with the d-pad. The navigation does not behave as expected when reaching the end or the beginning of a ListView or GridView. I've sumarized some scenarios, their actual behavior and my expected behavior.

## Reproducing examples

**Scenario 1.**
Start fresh and right arrow (or right d-pad) and navigate to the end of the green list. Keep pressing the right button and notice how the Focus jumps from "Green 19" to "Blue 11" continuing to navigate through the blue ListView.

Expected behavior: Navigating with right arrow-key should stop at the last element of the green ListView.

**Scenario 2.**
Start fresh and navigate one down to the blue ListView and navigate right (or right d-pad) to the end of the blue list. Keep pressing the right button and notice how the Focus jumps from "Blue 19" to "Green11" continuing to navigate through the green ListView.

Expected behavior: Navigating with right arrow-key should stop at the last element. of the blue ListView.

**Scenario 3.**
Start fresh and navigate down to the Grid. Navigate to the end of any row, Notice how the focus jumps from "Grid 8" or "Grid 17", etc.. to "Blue 11" continuing to navigate through the blue ListView.

Expected behavior: Navigating with right arrow-key should stop at the last element of a grids row.

**Scenario 4.**
Navigate to the end of the green ListView, and then navigate to the end of the blue ListView. Now, still in the blue ListView, navigate back (left arrow or left d-pad) to the beginning of the blue ListView. Keep navigating back with the left arrow and notice how the focus jumps from "Blue 0" to "Green 8".

Expected behavior: Navigating with left arrow-key should stop at the first element of the ListView.

**Scenario 5.**
Navigate to the end of the blue ListView. Navigate down to the Grid. Navigate back in the GridView from "Grid 8" to "Grid 0", or "Grid 17" to "Grid 9", etc.... Keep navigating back with the left arrow and notice how the focus jumps from "Grid 0" (or Grid 9, etc...) to "Blue 8".

Expected behavior: Navigating with left arrow-key should stop at the first element of the grids row.

```dart

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            Container(
              color: Colors.green,
              height: 100,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: 20,
                itemBuilder: (ctx, index) => RawMaterialButton(
                  onPressed: () {},
                  child: Text('Green $index'),
                ),
              ),
            ),
            Container(
              color: Colors.blue,
              height: 100,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: 20,
                itemBuilder: (ctx, index) => RawMaterialButton(
                  onPressed: () {},
                  child: Text('Blue $index'),
                ),
              ),
            ),
            Expanded(
              child: GridView.builder(
                itemCount: 200,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 9,
                    childAspectRatio: 1,
                    crossAxisSpacing: 0,
                    mainAxisSpacing: 0),
                itemBuilder: (ctx, index) => RawMaterialButton(
                  onPressed: () {},
                  child: Text('Grid $index'),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

## flutter doctor -v

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.194, on Microsoft Windows [Version 10.0.20251.1], locale en-AT)
    • Flutter version 1.24.0-8.0.pre.194 at D:\Projects\Development\Flutter\flutter-sdk-win
    • Framework revision 018467cdb1 (10 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\adonis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30709.132
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\adonis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.20251.1]

• No issues found!
```

**Comment by darshankawar** [comment]
@ad-on-is Again this seems to be similar to [67814](https://github.com/flutter/flutter/issues/67814). I'd suggest you to follow-up there since it has been reopened.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by ad-on-is** [comment]
No, this is a totally different issue. The other describes the behavior in the GridView itself, this, on the other hand, describes the issue related between multiple ListViews and GridViews.

**Comment by ad-on-is** [comment]
@darshankawar Could you please reopen this one?
