### ISSUE TITLE
[Desktop] Windows X86 support

### ISSUE THREAD

**Issue by yeganaaa** [flutter/flutter#70360]
I'm a flutter developer and I'm using flutter to make content management system for our company,
Android, IOS, Linux X64, macOS, Windows X64 builds are very perfect for my requirements and all is well,
but our some customers are still using X86 version of Windows7,
I'm tried running flutter desktop windows build of my app on windows7 x86 but it won't be run,
also I'm tried running Flutter web on Google chrome browsers in windows7 x86 but gets very poor performance.

so can I build flutter to desktop x86 anyway?
or have any advice for this?
thank you.

**Comment by darshankawar** [comment]
@yeganaaa 
Please see [this](https://github.com/flutter/flutter/issues/37777) open issue and underlying comments for reference on your question.
Closing this as duplicate.
