### ISSUE TITLE
Nested Scaffolds redundantly move contents up when there's a keyboard

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7036]
Scaffolds indiscriminately apply the `MediaQuery.of(context).padding`, so if you nest them they double up on trying to get out of the way of keyboards.

They should probably put a MediaQuery around their body themselves that removes the padding that they handle.

(A workaround in the meantime is to tell your inner scaffold not to `resizeToAvoidBottomPadding`.)

**Comment by abarth** [comment]
Yeah, we need to consume the padding in the scaffold.

**Comment by Hixie** [comment]
Probably we should also make sure we handle the status bar.

**Comment by Hixie** [comment]
cc @cbracken  I think we did this, right?

**Comment by Heasummn** [comment]
Running Flutter 1.0.0 and SDK 28.0.3, I still see this bug. Using `resizeToAvoidBottomPadding` on the inner scaffold fixes the problem, but I feel as if there is a better way to do this.

**Comment by zoechi** [comment]
@Heasummn is there a specific reason you need to nest `Scaffold`? `Scaffold` is not designed to be nested.

**Comment by Heasummn** [comment]
I have repeated logic/ui that uses a FAB and general content, but I would like the App Bar to be seperate from that logic. If there's another way to get a FAB without a scaffold, I would definitely use that instead.

**Comment by zoechi** [comment]
@Heasummn I'd suggest to ask support questions in one of the other channels listed at http://flutter.io/support .

**Comment by aryzhov** [comment]
Nested scaffolds are necessary. Consider an app that has a bottom navigation bar, and each tab has has a different app bar (with different actions, for example). An example is described in detail [in this blog article](https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf).

**Comment by aryzhov** [comment]
Perhaps the whole concept of a scaffold is broken, as this widget tries to do too many things: managing model popups, involved in navigation, etc. If nested scaffolds are not possible, we need Scaffold to be composed of multiple, reusable widgets.

**Comment by zoechi** [comment]
@aryzhov that was changed recently to make nested Scaffolds work. Try `dev` or `master` channel.

**Comment by zoechi** [comment]
@aryzhov feel free to build your own widget that does exactly what you need instead of using provided ones.

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/pull/26259

**Comment by aryzhov** [comment]
As of 1.1.8, nested scaffolds appear to be working but `resizeToAvoidBottomPadding: false` is still necessary for the outer Scaffold.
