### ISSUE TITLE
Update the In-app-purchase plugin readme and examples to be actually useful

### ISSUE THREAD

**Issue by AvatarDevs** [flutter/flutter#70362]
This is the most pathetic example and readme i have ever seen. The goal is to guide the user on how to actually use the plugin - this does the opposite. Example is a jumbled mess, no one should ever use that in a real application. 

This is mind boggling. Please for the love of god make a clear and concise example

**Comment by darshankawar** [comment]
@AvatarDevs Please see and follow the [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) 

Closing this as duplicate of:

https://github.com/flutter/flutter/issues/51013
https://github.com/flutter/flutter/issues/34525
