### ISSUE TITLE
Plugins should default to Kotlin 1.4 instead of 1.3

### ISSUE THREAD

**Issue by larssn** [flutter/flutter#70367]
## Use case
So creating a platform plugin (`flutter create --org com.myorg --template=plugin --platforms=android myplugin`) defaults to Kotlin 1.3.50.

## Proposal
That new plugins use Kotlin 1.4, or at most, the latest version of 1.3 (1.3.72 as of writing).
But Kotlin 1.4 has a lot of neat new features and I'm not gonna list them here.

**Comment by jmagman** [comment]
\cc @xster Any idea what would need to be tested to do this?

**Comment by xster** [comment]
Should revive https://github.com/flutter/flutter/pull/59037 at some point. 1.3.50 was indeed buggy. We don't have a lot of kotlin code in our repos. Most likely will be a manual test in flutter/samples.

**Comment by larssn** [comment]
So after raising this issue, I've been testing out v1.4.10 (because the coroutine package recommends it). It's been working great and I've not run into any problems with coroutines.

**Comment by stuartmorgan** [comment]
See also https://github.com/flutter/flutter/issues/78875. Based on the issue linked from there, it seems like doing this without a migration strategy for existing apps will be problematic.

**Comment by stuartmorgan** [comment]
This was fixed in https://github.com/flutter/flutter/pull/95383
