### ISSUE TITLE
[mac] mouse_tracking Failed assertion: line 301 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#70375]
Causes:
Sometimes it will cause, and it has caused for more than a thousand times since i first used flutter.
It cause for no reason, and randomly.
While on phone it will never throw this problem maybe no mouse tracking...

Log: 
```sh
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 301 pos 12: '!_debugDuringDeviceUpdate': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BaseMouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracking.dart:301:12)
#3      BaseMouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracking.dart:408:7)
#4      BaseMouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracking.dart:290:9)
#5      BaseMouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracking.dart:407:5)
#6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:276:22)
#7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#11     _rootRunUnary (dart:async/zone.dart:1206:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#14     _invoke1 (dart:ui/hooks.dart:172:10)
#15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:279:7)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)```

**Comment by PassionPenguin** [comment]
Really confused, as every time i move my cursor onto the application window, it will throw dozens of exceptions....
While sometimes it never throws any of them...

**Comment by darshankawar** [comment]
@PassionPenguin 
Please provide `flutter doctor -v` and minimal complete reproducible code sample along with the steps you take that shows the issue you are facing.
Thanks.

**Comment by amarildolacerda** [comment]
I've noticed the same when:
Draggable -> InkWell -> ListTile
to solve it I changed:
Draggable -> ListTile -> IconButton

After I constraint in IconButton (restrict area to click), it solved.

**Comment by PassionPenguin** [comment]
right, actually for me, it seems to be a random bug more than a known-reason one. The exception seems not be able to represent unless weare lucky enough....

**Comment by TahaTesser** [comment]
Hi @PassionPenguin  @amarildolacerda 
To better address the issue, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by CauliflowerGoer** [comment]
> 我注意到以下情况相同：可
> 拖动-> InkWell-> ListTile
> 以解决该问题我更改了：可
> 拖动-> ListTile-> IconButton
> 
> 在我约束IconButton（限制点击区域）后，它解决了。


thank you very much , 
This solved my problem

**Comment by SethKitchen** [comment]
Same error with InkWell -- weird it doesn't care about directionality until a random drag time. I Tried to wrap my App with Directionality but it doesn't work.

errors.dart:167 Uncaught Error: No Directionality widget found.
_InkResponseStateWidget widgets require a Directionality widget ancestor.
The specific widget that could not find a Directionality ancestor was:
_InkResponseStateWidget
The ownership chain for the affected widget is: "_InkResponseStateWidget ← InkWell ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#bc79c ink renderer] ← NotificationListener ← CustomPaint ← ShapeBorderPaint ← PhysicalShape ← ⋯"
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree. It determines the ambient reading direction and is used, for example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
at Object.throw [as throw] (errors.dart:216)
at debug.dart:271
at Object.debugCheckHasDirectionality (debug.dart:290)
at Function.of (basic.dart:117)
at ink_well._InkResponseState.new.updateHighlight (ink_well.dart:850)
at ink_well._InkResponseState.new.[_handleHoverChange] (ink_well.dart:1059)
at ink_well._InkResponseState.new.[_handleMouseEnter] (ink_well.dart:1047)
at Function._handleDeviceUpdateMouseEvents (mouse_tracking.dart:502)
at mouse_tracking.MouseTracker.new.handleDeviceUpdate (mouse_tracking.dart:510)
at mouse_tracking.dart:428
at mouse_tracking.MouseTracker.new.[_deviceUpdatePhase] (mouse_tracking.dart:306)
at mouse_tracking.dart:408
at mouse_tracking.MouseTracker.new.[_monitorMouseConnection] (mouse_tracking.dart:290)
at mouse_tracking.MouseTracker.new.updateWithEvent (mouse_tracking.dart:407)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:276)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (binding.dart:316)
at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:280)
at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:238)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:221)
at Object.invoke1 (platform_dispatcher.dart:907)
at _engine.EnginePlatformDispatcher..invokeOnPointerDataPacket (platform_dispatcher.dart:170)
at _engine.PointerBinding..[onPointerData] (pointer_binding.dart:128)
at pointer_binding.dart:513
at pointer_binding.dart:485
at pointer_binding.dart:208
DartError @ errors.dart:167
throw @ errors.dart:216
(anonymous) @ debug.dart:271
debugCheckHasDirectionality @ debug.dart:290
of @ basic.dart:117
updateHighlight @ ink_well.dart:850
[_handleHoverChange] @ ink_well.dart:1059
[_handleMouseEnter] @ ink_well.dart:1047
_handleDeviceUpdateMouseEvents @ mouse_tracking.dart:502
handleDeviceUpdate @ mouse_tracking.dart:510
(anonymous) @ mouse_tracking.dart:428
[_deviceUpdatePhase] @ mouse_tracking.dart:306
(anonymous) @ mouse_tracking.dart:408
[_monitorMouseConnection] @ mouse_tracking.dart:290
updateWithEvent @ mouse_tracking.dart:407
dispatchEvent @ binding.dart:276
[_handlePointerEventImmediately] @ binding.dart:316
handlePointerEvent @ binding.dart:280
[_flushPointerEventQueue] @ binding.dart:238
[_handlePointerDataPacket] @ binding.dart:221
invoke1 @ platform_dispatcher.dart:907
invokeOnPointerDataPacket @ platform_dispatcher.dart:170
[_onPointerData] @ pointer_binding.dart:128
(anonymous) @ pointer_binding.dart:513
(anonymous) @ pointer_binding.dart:485
(anonymous) @ pointer_binding.dart:208
32errors.dart:167 Uncaught Error: Assertion failed: file:///D:/git/flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:301:12
!debugDuringDeviceUpdate
is not true
at Object.throw [as throw] (errors.dart:216)
at Object.assertFailed (errors.dart:24)
at mouse_tracking.MouseTracker.new.[_deviceUpdatePhase] (mouse_tracking.dart:301)
at mouse_tracking.dart:408
at mouse_tracking.MouseTracker.new.[_monitorMouseConnection] (mouse_tracking.dart:290)
at mouse_tracking.MouseTracker.new.updateWithEvent (mouse_tracking.dart:407)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:276)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (binding.dart:316)
at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:280)
at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:238)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:221)
at Object.invoke1 (platform_dispatcher.dart:907)
at _engine.EnginePlatformDispatcher..invokeOnPointerDataPacket (platform_dispatcher.dart:170)
at _engine.PointerBinding..[_onPointerData] (pointer_binding.dart:128)
at pointer_binding.dart:513
at pointer_binding.dart:485
at pointer_binding.dart:208

**Comment by kokocooler2020** [comment]
**I encountered the same problem, and I don't know how to reproduce this exception. It may happen when the mouse pointer moves from another window to the app window, but I am not sure.

I used ‘go-flutter’ to compile an app to run in macOS (MacOS Catalina 10.15.7)，The following exceptions are thrown from time to time:**

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception:'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 322 pos 12:'(event is PointerAddedEvent) == ( lastEvent is PointerRemovedEvent)': is not true.
#0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2 BaseMouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracking.dart:322:12)
#3 BaseMouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracking.dart:404:10)
#4 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:276:22)
#5 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#6 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#7 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#8 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#9 _rootRunUnary (dart:async/zone.dart:1206:13)
#10 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#12 _invoke1 (dart:ui/hooks.dart:176:10)
#13 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
#14 _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

**Because I don’t use mouse-related code, only onTap(), and the exception stack does not point to a known onTap(), so I cannot provide the code, please help and thank you.**

flutter doctor -v
  
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.24.0-10.2.pre at /Users/zhiguoli/LocalSpace/Sdk/FlutterSdk/flutter
    • Framework revision 022b333a08 (7 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain-develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zhiguoli/LocalSpace/Sdk/AndroidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/zhiguoli/LocalSpace/Sdk/FlutterSdk/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin: /Library/Apple/usr/bin:/Users/zhiguoli/.pub-cache/bin:/Users/zhiguoli/LocalSpace/Sdk/AndroidSdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode-develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by gerardsimons** [comment]
@TahaTesser : I am having this issue with a custom painter on Mac OS Big Sur, but not always ... Just as I was writing this comment it went away for no apparent reason. Anywho, here is my `doctor -v`:

```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.1 20C69 darwin-arm, locale en-NL)
    • Flutter version 1.26.0-12.0.pre at /opt/homebrew/Caskroom/flutter/1.22.5/flutter
    • Framework revision a706cd2112 (8 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gerard/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 11.1 20C69 darwin-arm
```

**Comment by PassionPenguin** [comment]
> @TahaTesser : I am having this issue with a custom painter on Mac OS Big Sur, but not always ... Just as I was writing this comment it went away for no apparent reason. Anywho, here is my `doctor -v`:
> 
> ```
> [✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.1 20C69 darwin-arm, locale en-NL)
>     • Flutter version 1.26.0-12.0.pre at /opt/homebrew/Caskroom/flutter/1.22.5/flutter
>     • Framework revision a706cd2112 (8 days ago), 2021-01-14 18:20:26 -0500
>     • Engine revision effb529ece
>     • Dart version 2.12.0 (build 2.12.0-224.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/gerard/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.1
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.52.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.18.1
> 
> [✓] Connected device (1 available)
>     • macOS (desktop) • macos • darwin-arm64 • macOS 11.1 20C69 darwin-arm
> ```

it's pretty an interesting prob.... For one year dev, I faced the probs for times, but it will surely be fixed the next start....even hot reload

**Comment by TahaTesser** [comment]
@gerardsimons 
Can you please file a new issue 
Thank you

**Comment by gerardsimons** [comment]
@TahaTesser :

Happy to do it but to be honest I haven't had this issue for a long time and wouldn't be able to reproduce it , especially not now, so I am not sure how much use such an issue would be. If I get it again I'll definitely try get something reproducible and make an issue!

**Comment by krjw-eyev** [comment]
I had this issue with `FittedBox  -> Column -> [Row -> [FittedBox, FittedBox, FittedBox, ...], ... ]`. I got rid of both `FittedBox` and it disappeared.

**Comment by katiecs3** [comment]
I had this same issue - try upgrading Flutter to the latest stable and the flutter/dart plugins. I seemed to have this issue  because I was running an old VSCode plugin with new flutter.

**Comment by duncanmak** [comment]
I just got this on the latest SDK, I'm only targeting Mac:

```
hangul:noticias (main) % sw_vers
ProductName:	macOS
ProductVersion:	11.3
BuildVersion:	20E232
```

```
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.3.0-0.1.pre at /Users/duncan/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (3 days ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.3 20E232 darwin-x64

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by KDCinfo** [comment]
Hi there, Not asking for an issue to be opened, just wanted to inform of an observation in that, I just got this `mouse_tracking` error on DartPad.dev (which I'm not sure I can run the flutter doctor on). And I was able to recreate it using incognito (although it still could be anecdotal to my system---which is also why I'm not opting for a new issue). 

1. On [dartpad.dev](https://dartpad.dev), 
2. using the code below, 
3. click the "Run" button and keep the cursor in the code window. 
4. Once built, move the cursor into the app window, and there will be **no error**. 
5. Click the "Run" again, and again leaving the cursor in the code window. 
6. Once built (the 2nd time), move the cursor into the app window, and the DartPad console will show a "**script error**". 
7. Click the "Run" again, but move the cursor into the app window before the app is built. 
8. Once built, you are free to move the cursor in and out of the app window with no script error. 

This can be done with either null safety or without, just remove the two `?`s. 
I'm on Windows using Chrome and below is the code I was testing on DartPad. 

Thanks to the [mention above](https://github.com/flutter/flutter/issues/70375#issuecomment-754441125) by @kokocooler2020 about the mouse being in another window. 
```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _textEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('CupertinoDatePicker Example'),
        ),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(20.0),
            child: TextField(
              onTap: () => _selectDate(),
              controller: _textEditingController,
              decoration: InputDecoration(hintText: 'Birth Date'),
            ),
          ),
        ),
      ),
    );
  }

  DateTime _initialDate = DateTime.now();
  DateTime _tempPickedDate = DateTime.now();

  _selectDate() async {
    DateTime? pickedDate = await showModalBottomSheet<DateTime>(
      context: context,
      builder: (context) {
        _tempPickedDate = _initialDate;
        return Container(
          height: 250,
          child: Column(
            children: <Widget>[
              Container(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    CupertinoButton(
                      child: Text('Cancel'),
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                    ),
                    CupertinoButton(
                      child: Text('Done'),
                      onPressed: () {
                        print(_tempPickedDate);
                        Navigator.of(context).pop(_tempPickedDate);
                      },
                    ),
                  ],
                ),
              ),
              Divider(
                height: 0,
                thickness: 1,
              ),
              Expanded(
                child: Container(
                  child: CupertinoDatePicker(
                    mode: CupertinoDatePickerMode.date,
                    onDateTimeChanged: (DateTime dateTime) {
                      _tempPickedDate = dateTime;
                    },
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );

    if (pickedDate != null && pickedDate != _initialDate) {
      setState(() {
        _initialDate = pickedDate;
        _textEditingController.text = pickedDate.toString();
      });
    } else {
      setState(() {
        _textEditingController.text = _initialDate.toString();
      });
    }
  }
}
/// Outside of a few slight modifications, the code above is from:
/// https://flutteragency.com/ios-like-datepicker-using-cupertinodatepicker-in-flutter/
```
