### ISSUE TITLE
Facing problem to upgrade latest version firebase_crashlytics 0.2.3.

### ISSUE THREAD

**Issue by SwapnilDhotre** [flutter/flutter#70378]
When I updated firebase crashlytics to latest version it prints below logs. In dependencies I have only firebase_crashlytics so there could not be any other dependency conflict. In long logs I found below to be important one add below.

[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In snapshot (Podfile.lock):
    Firebase/CoreOnly (= 6.34.0)

  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.5.2, which depends on
      Firebase/CoreOnly (~> 6.33.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/CoreOnly` inside your development pod `firebase_core`.
   You should run `pod update Firebase/CoreOnly` to apply changes you've made.

Full logs could be found below
[ErrorLogs.txt](https://github.com/flutter/flutter/files/5530764/ErrorLogs.txt)

**Comment by darshankawar** [comment]
@SwapnilDhotre 
Firebase related issues are logged and tracked here : https://github.com/FirebaseExtended/flutterfire/issues
Please open this issue in above referred repo.
Closing from here.
