### ISSUE TITLE
problem with flutter install and setup IDE (Android Studio) on ubuntu 20.04

### ISSUE THREAD

**Issue by theech** [flutter/flutter#70381]
### Try to run flutter doctor errors detection
since I installed all requirement that following from flutter docs, I am really sure that everything had installed on my Debian machine (ubuntu 20)

The result after running
`flutter doctor -v`
This command brings me up  
``` 
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.3 at /home/themakerguy/sdks/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/themakerguy/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories
```

Since I running 
`flutter doctor --android-licenses`
The result said
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found
```

-->> An android studio had been installed but it still reminded
`[!] Android Studio (not installed)`

It would be great if you can help me thought the issue 
Thanks in advance

**Comment by sidrao2006** [comment]
@theech , android licences has a problem with java v8+.

Please try using java jdk v8.
Thanks.

As for the android studio problem, it should be fixed by now.
cc @jonahwilliams

**Comment by TahaTesser** [comment]
Hi @theech 
Please follow the steps from  https://flutter.dev/docs/get-started/install/linux and you can existing Java 1.8, which comes with Android Studio to your system path. Wouldn't recommend using another version  than 1.8

`export JAVA_HOME=/home/your_user/your_android_studio_directory/android-studio/jre`


If the problem persists with official docs, please provide `flutter doctor -v` with changes and `flutter doctor --android-licenses -v`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
