### ISSUE TITLE
App Store issue with package webview_flutter when uploading our flutter app

### ISSUE THREAD

**Issue by JoeMan97** [flutter/flutter#70394]
We used the package webview_flutter (wich is backed by a WKWebView) for integrate paypal to our app, when we tried to upload it, apple replied:

**ITMS-90809: Deprecated API Usage** - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

**Comment by TahaTesser** [comment]
Hi @JoeMan97 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/60687
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
