### ISSUE TITLE
hello_services does not understand MaterialIcons font

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7039]
TwoLevelListItem open/close icon does not appear correctly in Android "real-mode"

**Comment by eseidelGoogle** [comment]
I'm not sure what "real-mode" is?  Do you have a link?

**Comment by eseidelGoogle** [comment]
From gitter, it sounds like you meant `flutter run --release`.

**Comment by HansMuller** [comment]
The appearance of two level lists is based on: https://material.google.com/components/lists-controls.html#lists-controls-types-of-list-controls

I assume you're referring to the color of the open/close icon? Per the spec, its color doesn't change when it's open. However its appearance is the same in debug/release mode.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/20680521/40c58816-b554-11e6-920c-d2c2659b1d74.png)

**Comment by jtrunick** [comment]
I'll get a screenshot for me it looks nothing like the < ^ that I see in "slow mode" .

**Comment by jtrunick** [comment]
![screenshot_2016-11-28-19-11-29](https://cloud.githubusercontent.com/assets/1335296/20693211/7c0f6d1c-b5a2-11e6-86a9-f3dacf0e2379.png)

**Comment by abarth** [comment]
Looks like we're missing the icon font.

**Comment by jtrunick** [comment]
FWIW, I'm using a hello_services based-build (in case it makes a difference picking up the icon resources).

**Comment by eseidelGoogle** [comment]
hello_services does not know how to include the material design icons font, no.

You'll want to add bin/cache/artifacts/material_fonts/MaterialIcons-Regular.ttf (or you can download it yourself: http://google.github.io/material-design-icons/) to your Android and iOS project (forked from hello_services).  We've not yet fully integrated the `hello_services` model into the default `flutter build` flow.

**Comment by jtrunick** [comment]
hello_services doesn't have a flutter.yaml file, I added one with this line:
uses-material-design: true

and that did the trick.

**Comment by eseidelGoogle** [comment]
FYI @jakobr-google, not sure if this is still an issue?

**Comment by jakobr-google** [comment]
hello_services doesn't have `uses-material-design: true`, so in that sense this is still an issue. It sounds like things work if you add that, so we just have to decide whether hello_services should include this by default.

I think it should, since this is something that surprises people. And maybe we should have the framework emit an error if you use the material design widgets, but haven't specified `uses-material-design: true` in pubspec.yaml?

**Comment by abarth** [comment]
> I think it should

Good idea.

> And maybe we should have the framework emit an error if you use the material design widgets, but haven't specified uses-material-design: true in pubspec.yaml?

That's a good idea too.  Would you be willing to file a separate bug about that?

**Comment by jakobr-google** [comment]
Filed #8086. (Woo!)

Update to hello_services coming up.
