### ISSUE TITLE
flutter tool could inform you when you're ready to migrate to nnbd

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#70409]
Idea: When `flutter` runs `pub` and the list of dependencies changes, we could check if all the dependencies are null-safe-aware, and if so, but the current package is not, we could then print a hint message saying that it might be worth upgrading, maybe linking to a web page that says how to do so or suggesting "dart migrate" or some such.

**Comment by jonahwilliams** [comment]
Some breadcrumbs:

We already process the package_config.json file generated by pub in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L441 .

To determine if all dependencies except for the main application are null safe, you could read the current package from the pubspec.yaml, and then iterate through each `Package` object from the `PackageConfig` and check the language version for >= 2.12.

To avoid writing the message too often, this method could write a time stamp or something similar into the package's .dart_tool directory and only display the message every X block of time.

**Comment by Hixie** [comment]
cc @timsneath

**Comment by mit-mit** [comment]
I really like this idea. I think there are two ways we could do it:

1. After a `pub get`, tell the user when they are on a set of versions that all support null safety. We could do that by looking at the language version as Jonah suggested. This is a cheap lookup, and would not add any latency.

1. After a `pub get`, tell the user when a compatible set of versions exist that they could `pub upgrade` to and get null safety versions of all deps. The logic for this is already in `pub outdated --mode=null-safety`. However, this is a pretty expensive check (it downloads the most recent version of all deps), and would add a bunch of latency.

cc @jonasfj

**Comment by jonasfj** [comment]
> tell the user when a compatible set of versions exist that they could `pub upgrade` to and get null safety versions of all deps. 

Migration guidelines recommend that authors publish new major versions when migrating to null-safety. So users who follow our current recommendations to have a `^1.2.3` version constraint in `pubspec.yaml` will not be able to upgrade to null-safety compatible dependencies using `dart pub upgrade`.

Moreover, **they should not want to**, when moving to null-safety compatible versions it's often preferable to ensure that constraints in `pubspec.yaml` are updated, such that you cannot be downgraded to a pre-null-safety version of some dependency in the future.

------------------

I think it would make sense to do this in `pub get`, but it won't have much impact on flutter until we resolve the issue where `flutter pub get` doesn't show output from `pub get`.

**Comment by parlough** [comment]
Now that the null safety migration is completed and the currently maintained versions of the relevant tooling (pub) no longer support null safety, I suppose this issue is stale.

If you'd like to see something here more generic in relation to suggestions when language versions are incompatible, please open a new issue for the [pub tool](https://github.com/dart-lang/pub).

Thanks :D
