### ISSUE TITLE
`felt test --integration-tests-only` does not fail when it should

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#70400]
`felt test --integration-tests-only` does not fail when it should.

I have observed two behaviors:

## "All tests passed" (when they didn't)

One is when a test throws exceptions, but then reports "All tests passed" ([example](https://gist.github.com/yjbanov/99b2696d5c73a96c23255a662d191ef7#file-felt-integration-tests-txt-L332), [example](https://gist.github.com/yjbanov/99b2696d5c73a96c23255a662d191ef7#file-felt-integration-tests-txt-L354)). This one may actually be a bug in `package:integration_test` rather than `felt`. The "All tests passed" is probably printed by [integration_test_driver.dart](https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/integration_test/lib/integration_test_driver.dart#L76), which then [exist with 0](https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/integration_test/lib/integration_test_driver.dart#L80). So `felt` does the right thing and reports success.

## "Failed to run test" with exit code 0

The second behavior is when the test fails and `felt` [knows](https://github.com/flutter/engine/blob/d50a83c15bc8140fe2ce2b8a164cea32a884f06a/lib/web_ui/dev/integration_tests_manager.dart#L220) that it failed (otherwise it wouldn't have printed "Failed to run test"). However, `felt` then exits with exit code 0. Also in this case `felt` prints a mysterious "info" message that reads: "INFO: 20 tests run. 0 passed and 0 failed.". Example:

```
ERROR: Golden file focused_text_field-chrome.png did not match the image generated by the test.
(1.0029% of pixels were different. Maximum allowed rate is: 0.5000%).
You can view the test report in your browser by opening:
/home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/.dart_tool/test_results/focused_text_field-chrome.report.html
To update the golden file call matchGoldenFile('focused_text_field-chrome.png', write: true).
Golden file: /home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/.dart_tool/test_results/focused_text_field-chrome.expected.png
Actual file: /home/yjbanov/code/flutter/engine/src/flutter/lib/web_ui/.dart_tool/test_results/focused_text_field-chrome.actual.png

result {"result":"false","failureDetails":["{\"methodName\":\"Focused text field creates a native input element\",\"details\":\"\"}"]}
Failure Details:
Failure in method: Focused text field creates a native input element

end of failure 1



ERROR: Failed to run test. Exited with exit code 1. To run text_editing_integration.dart locally use the following command:

flutter drive --target=test_driver/text_editing_integration.dart -d web-server --profile --browser-name=chrome --local-engine=host_debug_unopt --web-renderer=canvaskit
INFO: 20 tests run. 0 passed and 0 failed.
yjbanov@yegor-home:~/code/flutter/engine/src/flutter/lib/web_ui$ echo $?
0
```

**Comment by nturgut** [comment]
Thanks for reporting, I'll take a look soon.

**Comment by yjbanov** [comment]
Here's an example of this happening on LUCI right now: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863876687311720384/+/steps/felt_test_chrome/0/stdout

**Comment by yjbanov** [comment]
Reopening. I just realized that https://github.com/flutter/engine/pull/22483 only handles the "Failed to run test" case, but not the "All tests passed" case.

**Comment by nturgut** [comment]
Can you please add an example? Since this is P2 I assume it needs immediate attention.

What does it mean "All tests passed" can you add more details?

**Comment by nturgut** [comment]
I'm not seeing any failures in the prod instances: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863162125760000832/+/steps/felt_test_chrome/0/stdout

There is only 2 failing methods (one failed golden, one failed diagnostics). Both are failure tests (they are expected to fail).

Can you please let me know, why are you observing "does not fail when it should"? 

Since this is super critical, I'm making this one a P1 and assigning to @yjbanov for now. @yjbanov please add as many details as possible, it is better to make sure all tests fail when they should especially before the break! Thanks for filing the issue.

**Comment by nturgut** [comment]
I'm re-closing the issue. both for local run and the run on LUCI tests are failed as expected: https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Engine/12027? All tests pass/fail as expected. 
Also in the local tests I have observed non-zero exit code, after running `felt`.

There is a "All tests passed" info log after each single integration test, written by e2e. I believe that might have been the log that has been observed for this case. Please open another issue for wrong/unexpected e2e logs (if that was the case).

**Comment by yjbanov** [comment]
Oh, I didn't realize those were intentional failures. Closing SGTM.

**Comment by yjbanov** [comment]
Sorry for the false alarm.
