### ISSUE TITLE
Cirrus tasks marked as pending in cocoon

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70410]
Cirrus tasks are showing as pending in the devicelab, even though they have run and succeeded.
https://cirrus-ci.com/build/flutter/flutter/cca1215939af648f9f35e4a6ce1b32467708b7cf?branch=master

<img width="95" alt="Screen Shot 2020-11-12 at 3 16 21 PM" src="https://user-images.githubusercontent.com/682784/99007922-063cbd80-24fa-11eb-8d69-54439cc5f28b.png">

**Comment by keyonghan** [comment]
Fix: https://github.com/flutter/cocoon/pull/1001
