### ISSUE TITLE
Package Google Sign In - Keyboard can't be displayed in iOS when we login by Google

### ISSUE THREAD

**Issue by fanyresfulany** [flutter/flutter#70437]
We had an issue when login by google in iOS. The keyboard can't be displayed when we try to input email or password for login by Google.

This  is the package version that we're using: 
google_sign_in: ^4.5.6

Please fix this issue asap. Thanks.

**Comment by pedromassangocode** [comment]
Hi @fanyresfulany 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by fanyresfulany** [comment]
Here is our flutter doctor -v and code sample
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ikaru/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM A705F (mobile) • RR8M602S2AF • android-arm64 • Android 10 (API 29)

• No issues found!

# Code Sample 

 GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: <String>['email']
  );

   Future loginByGoogle() async {
    _googleSignIn.signIn().then((result) {
      result.authentication.then((googleKey) {
        String token = googleKey.accessToken;
        String currentName = _googleSignIn.currentUser.displayName;
        String emailUser = _googleSignIn.currentUser.email;
      });
    }).catchError((onError) {
      Utils.setLog("[ ERROR ] Error login by google : $onError");
    });
  }

**Comment by pedromassangocode** [comment]
Hi @fanyresfulany 
Please provide the complete output of `flutter doctor -v` and your `pubspec.yaml` file as well.
Thank you

**Comment by fanyresfulany** [comment]
[google_sign_new_request.log](https://github.com/flutter/flutter/files/5544101/google_sign_new_request.log)

here is our flutter doctor -v and pubspec.yaml file

**Comment by pedromassangocode** [comment]
Hi @aalhadhoud 
I cannot reproduce this issue on latest stable channel.

![gif44](https://user-images.githubusercontent.com/67424416/99221068-2ca37700-27e0-11eb-96aa-deb5a9bd086b.gif)

Please provide more details about your device and the steps to reproduce the issue. Make sure you provide your `flutter doctor -v` as well.

<details><summary>Code</summary>

```
void main() => runApp(MyApp3());

class MyApp3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String userName;
  bool iSignedIn = false;
  GoogleSignInAccount _currentUser;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        setState(() {
          iSignedIn = true;
          userName = account.displayName;
          print("");
        });
      }
    });
    _googleSignIn.signInSilently().then((value) {
      if (value != null) {
        setState(() {
          userName = value.displayName;
        });
      }
    });
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn().then((value) {
        value.authentication.then((valueq) {
          print(valueq.idToken);
        });
      });
    } catch (error) {
      print(error);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(iSignedIn ? userName : 'empty user name'),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        icon: Icon(Icons.add),
        label: Text(iSignedIn ? 'Sign Out' : 'Sign In'),
        onPressed: () {
          if (!iSignedIn) {
            _handleSignIn();
          } else {
            _googleSignIn.signOut();
            setState(() {
              iSignedIn = false;
            });
          }
        },
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by fanyresfulany** [comment]
Can you please try in real device?

Cause it works in iOS 14.1 emulator, but not working in real device.

For reproduce in emulator, please use iOS 13.5 emulator.

Here is the ss when we try it on iOS 13.5 emulator: 
![image](https://user-images.githubusercontent.com/74396981/99233896-69925c80-2826-11eb-8b25-333ceb26a22e.png)

**Comment by fanyresfulany** [comment]
Hi @pedromassangocode 

it already works now. 

it was because we put a function wrong. Thanks for your help! Have a good day!
