### ISSUE TITLE
flutter_localizations null safety issue

### ISSUE THREAD

**Issue by ductranit** [flutter/flutter#70433]
I use package [jiffy](https://github.com/jama5262/jiffy) which depends on [intl](https://pub.dev/packages/intl) 0.16.0. After I upgrade into latest master it conflicts with the `intl` 0.17.0-nullsafety.2 from `flutter_localizations`
```
Because no versions of jiffy match >3.0.1 <4.0.0 and jiffy 3.0.1 depends on intl ^0.16.0, jiffy ^3.0.1 requires intl ^0.16.0.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, jiffy ^3.0.1 is incompatible with flutter_localizations from sdk.
```
I then try resolve version conflict by using 
```
dependency_overrides:
   intl: ^0.16.0
```
But when I run the app, I have some null safety issues on flutter_localizations
```
../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
      ^^^^^^^^^^^^
../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:550:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$licenseCount', formatDecimal(licenseCount));
      ^^^^^^^^^^^^
../flutter/packages/flutter_localizations/lib/src/material_localizations.dart:659:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$remainingCount', formatDecimal(remainingCount));
      ^^^^^^^^^^^^

```

Is there anyway to disable null safety on `flutter_localizations` ? My project is quite big and refactor to null safety takes so much time.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.228, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.228 at /Users/admin/Documents/Soft/flutter
    • Framework revision 9860f52ea5 (3 hours ago), 2020-11-12 18:14:03 -0800
    • Engine revision c5c7e83b9e
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @ductranit 
I believe you can't disable it null safety on a package, entire source has to be different, you can downgrade to a flutter version that doesn't have null safety in  `flutter_localizations`   until `jiffy` updates their dependencies, FYI package isn't updated from a while. 

You can find an alternative package or downgrade IMO
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by sanekyy** [comment]
same issue

**Comment by espresso3389** [comment]
Even official plugins like [local_auth](https://pub.dev/packages/local_auth) has the identical issue. Any workaround other than using older commits?

**Comment by ductranit** [comment]
I found another workaround:
```
dependency_overrides:
   intl: ^0.17.0-nullsafety.2
```
Instead of forcing `intl 0.16.0`, I force the new null safety version `0.17.0-nullsafety.2`, and it can run well even though I don't enable null safety on my project.
I don't see any issue with the [jiffy](https://github.com/jama5262/jiffy) code

**Comment by normancarcamo** [comment]
> I found another workaround:
> 
> ```
> dependency_overrides:
>    intl: ^0.17.0-nullsafety.2
> ```
> 
> Instead of forcing `intl 0.16.0`, I force the new null safety version `0.17.0-nullsafety.2`, and it can run well even though I don't enable null safety on my project.
> I don't see any issue with the [jiffy](https://github.com/jama5262/jiffy) code

Thanks!.

**Comment by muhammadshoaib06** [comment]
Hey!
In my project, intl and easy_localization have conflict. 
I try to override intl dependence but it show error:

/Users/*****/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/Users/*****/Desktop/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
/Users/*****/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:83:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/*****/Desktop/flutter/packages/flutter/lib/src/material/scaffold.dart:1449:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
/Users/*****/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:276:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/Users/*****/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieControllerProvider)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/*****/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/shoaib/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by KhaderMurtaja** [comment]
Because flutter_material_pickers >=1.9.2 depends on intl >=0.16.0 <=0.17.0-nullsafety.2 and best depends on intl ^0.17.0, flutter_material_pickers >=1.9.2 is forbidden.

I've upgraded flutter_material_pickers and import intl package.

Any ideas??

**Comment by LuckyArthas** [comment]
I have same error please help me

**Comment by JasonPhui** [comment]
I also have same error please help me

**Comment by exeptionerror** [comment]
All Possible working solution added [[Solved] flutter_localizations from SDK depends on intl 0.17.0 and fstore depends on intl ^0.16.1, flutter_localizations from SDK is forbidden](https://fluttercorner.com/flutter-localizations-from-sdk-depends-on-intl-0-17-0-and-fstore-depends-on-intl/)
