### ISSUE TITLE
Web requires '#' symbol at beginning of path

### ISSUE THREAD

**Issue by carloshwa** [flutter/flutter#70431]
## Steps to Reproduce

This can be reproduced with the nested router sample in the Navigator 2.0 Medium article:
https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

Code:
http://gist.github.com/bbca91e23bbb4d39247fa922533be7c9

When running this sample on web, going directly to:
http://localhost/#/book/0

loads correctly, but:
http://localhost/book/0

does not. The following error is reported in the browser console:
```
Refused to execute script from 'http://localhost:53127/book/0/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
The script has an unsupported MIME type ('text/html').
(index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:53127/book/0/') with script ('http://localhost:53127/book/0/flutter_service_worker.js'): The script has an unsupported MIME type ('text/html').
```

Is it possible to not require the preceding `#` in the path of the URL?

**Expected results:** http://localhost/book/0 loads the correct page

**Actual results:** http://localhost/book/0 loads a blank page

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
    • Flutter version 1.24.0-7.0.pre at /Users/panda/pandamonium/flutter
    • Framework revision a0860f6e87 (2 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)
```

</details>

**Comment by sidrao2006** [comment]
@carloshwa , this is the intended behaviour since flutter creates a single page application. Flutter doesn't really have multiple folders and files so it uses 'web ids' to navigate and Navigator 2.0 takes advantage of this feature and keeps the url bar in sync with the app

Thanks!

**Comment by strotter11** [comment]
That wasn't a real app

**Comment by pedromassangocode** [comment]
Hi @carloshwa 
There are so many threads talking about this where you can learn why this is required, see https://github.com/flutter/flutter/issues/33245.
If you want to remoe the # from the Url then see this comment https://github.com/flutter/flutter/issues/33245#issuecomment-705095853.

Thank you

**Comment by carloshwa** [comment]
That worked great, thanks for the heads up @pedromassangocode ! It's hard to search for existing issues for something like this.
