### ISSUE TITLE
Request for an "Effective Flutter" doc

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7044]
Request from a user:

"How about something broader for new developers set them on the right path so to speak. Coding standards,  naming conversions ..."

We could extend the Effective Dart guides with Flutter specifics.

In the meantime, maybe a wiki page might help get this going?

- [ ] "it is generally considered bad form for the State constructor to have arguments"
- [ ] "the "initialState" property on StatelessWidget should be final"

**Comment by sethladd** [comment]
See also this thread: https://groups.google.com/forum/#!topic/flutter-dev/9pXaZ4p7SIM

**Comment by Hixie** [comment]
>So far we've found that an observer pattern is the most resilient.
>
>You provide a Listenable subclass (e.g. a ChangeNotifier subclass), or an object with a similar subscribe/unsubscribe model, to the widget when you create it.
>
>In the State, you subscribe during initState, unsubscribe from the old one and subscribe to the new one during didUpdateConfig, and unsubscribe during dispose. The listener that you provide when subscribing just reads the data and updates local variables on the State using setState.
>
>This pattern has the advantage that it works really well with CustomPainter and other classes that take a Listenable to decide when to update. We're currently rewriting how scrolling works and we've used this pattern as the core mechanic for deciding how to handle scroll position changes, for example.

**Comment by sethladd** [comment]
Here's another item for Effective Flutter: https://github.com/flutter/flutter/issues/8952#issuecomment-288863378

Something about how when working with State fields that are lists, you should always create a new List inside the setState call, instead of modifying the list.

**Comment by sethladd** [comment]
Another item for Effective Flutter: all widgets (stateful, stateless) should be immutable.

**Comment by sethladd** [comment]
Another item: 
If you want your app to adapt to the platform on which it is running, you can use Theme.of(context).platform in your build() function to decide whether to build a Switch or a CupertinoSwitch, for example.

**Comment by sethladd** [comment]
Another item: https://github.com/flutter/flutter/issues/1220#issuecomment-301177908

"when a subclass of State defines a constructor (it should use the default constructor and access its configuration with the widget getter)."

**Comment by goderbauer** [comment]
For hero animations, the size of the hero at the destination needs to be defined at the first frame of the hero animation (e.g. if you hero an image, it takes a frame or two until the (destination) image is loaded and its size is known. Fix: wrap the image in a container of pre-defined size).

**Comment by Hixie** [comment]
https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/StatelessWidget-class.html and https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/StatefulWidget-class.html have some comments about how to optimise build methods for performance.

Something else we should probably say is that when a build method gets long, rather than factoring it out into separate methods, it's better to factor it out into separate self-contained widgets.

**Comment by sethladd** [comment]
> it's better to factor it out into separate self-contained widgets.

Curious, why?

**Comment by Hixie** [comment]
It will minimize how much of the tree needs to be walked when things get dirtied, which makes things much cheaper. The bigger the value returned from a build function, the more expensive things are.

**Comment by Hixie** [comment]
Avoid this pattern:
1. build with nothing visible
2. set off a slow load (e.g. get network data)
3. setState when you get the data
4. build with the data visible, including another widget that uses the same pattern.
Instead, structure the code so that all the network traffic happens up front, in model objects, and have the widgets just be the on-screen representation of that data. That would make the entire page have the final layout immediately, then as data comes in it can fade it in without the layout jumping around.

**Comment by sethladd** [comment]
Also:

Don't call setState from within the build() method. setState is like saying "call build()".

**Comment by sethladd** [comment]
Also:

If you are doing computationally intensive work, something that would exceed your frame budget, you can do that work in an Isolate. Isolates will run on another thread, and they use message passing to exchange information. Here is an example: https://github.com/flutter/flutter/blob/master/examples/layers/services/isolate.dart

**Comment by sethladd** [comment]
From @abarth on this thread: https://groups.google.com/forum/#!topic/flutter-dev/zRnFQU3iZZs

A) someDate changes because of something that happens to the parent widget. For example, if FoobarWidget's job is just to display the date in a fancy way, then when the parent rebuilds, it can create a new instance of FoobarWidget with the new state.  In this case, you can just use a simple StatelessWidget:

class FoobarWidgetA extends StatelessWidget {
  final DateTime someDate;

  FoobarWidget({ Key key, this.someDate }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new Text("the date is ${someDate}");
  }
}

B) someDate changes because of something that happens FoobarWidget and the parent needs to know about the new date. For example, if FoobarWidget's job is to let the user select a date, then the parent needs to be informed about which date the user has selected.  In this case, a good pattern to use is the "Checkbox" pattern (see https://docs.flutter.io/flutter/material/Checkbox-class.html).  In this pattern, the parent supplies both the someDate value and a callback that FoobarWidget should call when it wants to change the value.  The parent receives the new value, calls setState on itself, and rebuilds FoobarWidget with the new value, updating the UI:

class FoobarWidgetB extends StatelessWidget {
  final DateTime someDate;
  final ValueChanged<DateTime> onChanged;

  FoobarWidget({ Key key, this.someDate }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new Column(
      children: [
        new Text("the date is ${someDate}"),
        new RaisedButton(
          onPressed: () {
            onChanged(someDate.add(new Duration(day: 1)));
          },
          child: new Text("NEXT"),
        ),
      ],
    );
  }
}

C) someDate changes because of something that happens FoobarWidget and the parent does not need to know about the new date.  For example, if FoobarWidget's job is to let the use explore the phases of the moon on various dates.  In this case, a good pattern to use is the "initial value pattern".  In this pattern, the parent supplies an initial value, which FoobarWidget copies into a mutable field in its State object when the state object initializes.  As the user interacts with FoobarWidget, the field in the State object is mutated and setState causes FoobarWidget to rebuild with the new value.  The parent is never informed of the new value and if the parent rebuilds with a new initial value, the FoobarWidget ignores the new initial value because its state machine has advanced beyond initialization:

class FoobarWidgetC extends StatefulWidget {
  final DateTime initialDate;

  FoobarWidget({ Key key, this.initialDate }) : super(key: key);

  @override
  _FoobarWidgetState createState() => new _FoobarWidgetState();
}

class _FoobarWidgetCState extends State<FoobarWidgetC> {
  DateTime someDate;

  @override
  void initState() {
    super.initState();
    someDate = widget.initialDate;
  }

  void _advanceDate() {
    setState(() {
      someDate = someDate.add(new Duration(day: 1));
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Column(
      children: [
        new Text("the date is ${someDate}"),
        new RaisedButton(
          onPressed: _advanceDate,
          child: new Text("NEXT"),
        ),
      ],
    );
  }
}

**Comment by xster** [comment]
If a widget subtree is being animated and that subtree below the animation itself doesn't change based on the animation, turn debugProfileBuildsEnabled on and make sure in the Timeline that that subtree isn't building on each animation frame.

This will catch inefficient uses of listening to AnimationController ticks directly etc when a simpler solution like using a subclass of AnimatedWidget or a subclass of ImplicitlyAnimatedWidget is possible.

**Comment by xster** [comment]
Turn on debugPrintMarkNeedsPaintStacks and if complex subtrees are being repainted during animations or during scrolls, wrap the subtree of widgets with a RepaintBoundary if the subtree doesn't change depending on the animation or scrolling

**Comment by xster** [comment]
To TL;DR the 2 above, emphasize that while Dart object construction is cheap, part of the Flutter performance magic sauce is to do as little as possible. 

In other words, the ideal situation should be that during scrolls and during animations, close to nothing rebuilds or repaints unless the subtree meaningfully changes while scrolling/animating which is less common.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1985](https://github.com/flutter/website/issues/1985) via [**ZenHub**](https://www.zenhub.com/)
