### ISSUE TITLE
ExpansionTile border

### ISSUE THREAD

**Issue by adnanjpg** [flutter/flutter#70446]
**Expected results:**  I am Using ExpansionTile inside a Card With a shape of RoundedRectangleBorder and elevation

Here is an Example of the widget: 
Card(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      elevation: 5,
    )

**Actual results:** on expanded, the ExpasnsionTile's borders look bad on the top of the Card Widget.
 I managed to solve the problem by commenting out the lines of _ExpansionTileState > _buildChildren > Container > decoration > border property

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en)
    • Flutter version 1.22.3 at /Users/adnanfahed/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/adnanfahed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
```
</details>

here are screenshots of the difference after commenting out _ExpansionTileState > _buildChildren > Container > decoration > border property

![Screenshot_1605255928](https://user-images.githubusercontent.com/54329101/99056130-e74a3400-25aa-11eb-9c5e-3fba67e30287.png)
![Screenshot_1605255961](https://user-images.githubusercontent.com/54329101/99056148-ed401500-25aa-11eb-9c8f-cdaca0e6b63e.png)

**Comment by pedromassangocode** [comment]
Hi @adnanjpg 
Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample?
Also is is a bit unclear what is the actual vs expected behavior, please elaborate more.
Thank you

**Comment by adnanjpg** [comment]
Hi @pedromassangocode 
Thank you for your response. I've already provided my `flutter doctor -v` output in the issue. I'm sorry for not providing enough example code to reproduce. here is an example piece of code:

Card(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            elevation: 5,
            child: ExpansionTile(
              title: Text('The Title'),
              children: [
                Column(
                  children: List.generate(3, (idx) => Text(idx.toString())),
                )
              ],
            ),
          ),
 this is the output without commenting out the _ExpansionTileState > _buildChildren > Container > decoration > border property: 
![Screenshot_1605263255](https://user-images.githubusercontent.com/54329101/99062481-203ad680-25b4-11eb-9e27-328acd402f45.png)
and this is the output after commenting out:
![Screenshot_1605263265](https://user-images.githubusercontent.com/54329101/99062548-38aaf100-25b4-11eb-9825-a66c5e3689f7.png)

Thank you

**Comment by szrbdk** [comment]
Apparently the border is not removed with parameters. I found a package you can use instead. I recommend that you check out the [Expandable](https://pub.dev/packages/expandable) package.

**Comment by adnanjpg** [comment]
The problem was solved by adding any `clipBehaviour` property to `Card` other than the default which is `Clip.none`.

resulting in a code piece like this:
```

Card(
  clipBehavior: Clip.antiAlias,
      shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(20),
  ),
  elevation: 5,
  child: ExpansionTile(
    title: Text('The Title'),
    children: [
      Column(
        children: List.generate(3, (idx) => Text(idx.toString())),
      )
    ],
  ),
),
```
