### ISSUE TITLE
NavigatorState.pushAndRemoveUntil Failed assertion: line 3639 pos 12: '!_debugLocked': is not true

### ISSUE THREAD

**Issue by appliedrd** [flutter/flutter#70456]
probably my misuse....
my app has a navigate widget that invokes a survey on timer countdown
sometimes on start up, when the timer expires, I get this exception

code fragment:

```
class Navigate extends StatefulWidget {
  @override
  _NavigateState createState() => _NavigateState();
}
...
class _NavigateState extends State<Navigate> {

  @override
  Widget build(BuildContext context) {
...
 if (mounted && hasUserGoals == Constants.HAS_GOALS) {
        timeNowEpoch = DateTime.now().millisecondsSinceEpoch;
        int weekDiff = weeklySurveyTimeEpoch - timeNowEpoch;
        int monthDiff = monthlySurveyTimeEpoch - timeNowEpoch;
        print('weekDiff = ' + weekDiff.toString() + ' monthDiff = ' + monthDiff.toString());

        if (weekDiff < 1000) { 
          setState(() {
            updateSurveyStatus(); // a bunch of firebase stuff
          });
          return NavWeeklyScreen(userGoals);
        } else if (monthDiff < 1000) {
          return NavMonthlyScreen(userGoals);
        } else {
          // Build the widget with data.
          return Center(
              child: Container(
                  child: TimerScreen(weeklySurveyTimeEpoch,
                      nextWeeklySurveyDateTime, userGoals)));
        }
      }

-----------------
when TimerScreen expires it navigates back to my  navigate widget
  
@override
  Widget build(BuildContext context) {
    // int endTime = DateTime.now().millisecondsSinceEpoch + 1000 * 60 * 60;
    return CountdownTimer(
      endTime: widget.endTime,
      onEnd: () {
        print('onEnd');
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(
            builder: (BuildContext context) => Navigate(),
          ),
          ModalRoute.withName('/'),
        );
      },
      textStyle: TextStyle(fontSize: 30, color: Colors.teal),
      widgetBuilder: (_, CurrentRemainingTime time) {
        if (time == null) {
          return Text('');
        }
        var days, hour, min;
        if (time.days == null) {
          days = '';
        } else {
          days = '${time.days} days | ';
        }
        if (time.hours == null) {
          hour = '00';
        } else {
          hour = '${time.hours}';
        }
        if (time.min == null) {
          min = '00';
        } else {
          min = '${time.min}';
        }
        return Text(
          '$days $hour:$min:${time.sec}',
          //textAlign: TextAlign.center,
          style: TextStyle(fontSize: 20, color: Colors.teal),
        );
      },
    );
  }
}
```
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building NavWeeklyScreen(dirty, dependencies: [_LocalizationsScope-[GlobalKey#d5e4d]], state: _NavWeeklyScreenState#433ba):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3639 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  NavWeeklyScreen file:///Users/edwardhill/Documents/workspace/muhc_goal_setting_mac/lib/screens/navigate.dart:73:18
When the exception was thrown, this was the stack: 
#2      NavigatorState.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3639:12)
#3      Navigator.pushAndRemoveUntil (package:flutter/src/widgets/navigator.dart:1893:34)
#4      _NavWeeklyScreenState.build (package:GoalWizard/screens/nav_weekly_screen.dart:38:17)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)

════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by appliedrd** [comment]
debugging in android studio v4.1  with an iPad attached

edwardhill@Edwards-Mac-mini muhc_goal_setting_mac % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-CA)
    • Flutter version 1.22.3 at /Users/edwardhill/development/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edwardhill/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/edwardhill/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/edwardhill/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Edward’s iPad (mobile) • ef0f7732effeb36243428a04958637663dff78b0 • ios • iOS 14.1
    ! Error: Edward’s iPad is busy: Copying cache files from device. Xcode will continue when Edward’s iPad is finished. (code -10)

• No issues found!

**Comment by appliedrd** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building NavWeeklyScreen(dirty, dependencies: [_LocalizationsScope-[GlobalKey#d8da4]], state: _NavWeeklyScreenState#b2903):
setState() or markNeedsBuild() called during build.

This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Overlay-[LabeledGlobalKey<OverlayState>#b6134]
  state: OverlayState#922a2(entries: [OverlayEntry#5aefe(opaque: true; maintainState: false), OverlayEntry#4ae12(opaque: false; maintainState: true), OverlayEntry#3ff3c(opaque: false; maintainState: false), OverlayEntry#c997b(opaque: false; maintainState: true)])
The widget which was currently being built when the offending call was made was: NavWeeklyScreen
  dirty
  dependencies: [_LocalizationsScope-[GlobalKey#d8da4]]
  state: _NavWeeklyScreenState#b2903
The relevant error-causing widget was: 
  NavWeeklyScreen file:///Users/edwardhill/Documents/workspace/muhc_goal_setting_mac/lib/screens/navigate.dart:73:18
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
#3      OverlayState.rearrange (package:flutter/src/widgets/overlay.dart:400:5)
#4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3287:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by TahaTesser** [comment]
Hi @appliedrd 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Instead of snippets 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
