### ISSUE TITLE
Add this rule to Flutter's non-breaking policy: "Don't create weird behaviors for UI elements with time-honored traditions"

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#70462]
I think the Flutter breaking-changes policy is broken. It can't be only about not breaking tests. I propose the non-breaking policy should be amended with this rule: 

**"Don't create weird behaviors for very common UI elements with time-honored traditions".**

We've had problems with this at least here (https://github.com/flutter/flutter/issues/67898) and here (https://github.com/flutter/flutter/issues/18761).

If someone wishes to change the way some important UI element (like TextField, Text, Checkboxes etc) works they should first:

1) Create a document clearly explaining the change.
2) Get the OK from an usability expert in the Flutter team, not from regular developers without profound usability experience. 
2) Discuss with the community, and seek their approval.
3) Create the changes in another element. For example, `NewTextField` instead of `TextField`, and then wait a few months for people to use it and really make sure the change makes sense.

Note, this rule needs to apply for very common UI elements only. It should not apply for, say, `InteractiveViewer`.

As a corollary to this rule, I'd add this: If behavior changes would improve something in some locale but make it worse for others, it should be done for that locale only. That's what localization and internationalization is about. It's not about finding the lowest common denominator, and it's not about finding a single way which kind of works more or less for everyone. It's about knowing where the user is from an adapting. We do have LTR and RTL, right? We don't write text top-to-bottom as a middle ground.

**Comment by pedromassangocode** [comment]
Not really sure what are the proper labels for this one.
Cc @Hixie

**Comment by Hixie** [comment]
This would be more appropriate for the style guide and tree hygiene policies, not the breaking change policy.

But in any case it's not a controversial position. We don't intentionally create weird behaviors. :-) Sometimes weird behaviours happen as a result of us making a mistake, or as a result of us trying something novel (e.g. to improve performance) in a way that has unintended consequences.
