### ISSUE TITLE
Search UI bug

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#7046]
If you search something from flutter.io, you'd see a search button without label and a messed-up search box. I saw the same bug in both Chrome and Safari on OS X. Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/348942/20680178/d40348ea-b552-11e6-928d-bfa8eeb15568.png)

**Comment by sethladd** [comment]
Yikes, thanks for the feedback. Patches welcome.

**Comment by eseidelGoogle** [comment]
@emesx just ran into this and reported to me privately over chat.

**Comment by sethladd** [comment]
Should be fixed by https://github.com/flutter/website/pull/523
