### ISSUE TITLE
url launcher doesn't work in real android device

### ISSUE THREAD

**Issue by da-production** [flutter/flutter#70472]
when i run flutter in VM device url launcher work 
with all android version from 7.0.0 to 10
but when i run flutter in real android device url throw an exception and doesn't work it's work only with youtube link

**Comment by sidrao2006** [comment]
Hello @da-production ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by aseef17** [comment]
> when i run flutter in VM device url launcher work 
> 
> with all android version from 7.0.0 to 10
> 
> but when i run flutter in real android device url throw an exception and doesn't work it's work only with youtube link

Are you adding http:// prior to your URL ?

**Comment by da-production** [comment]
> 
> 
> > when i run flutter in VM device url launcher work
> > with all android version from 7.0.0 to 10
> > but when i run flutter in real android device url throw an exception and doesn't work it's work only with youtube link
> 
> Are you adding http:// prior to your URL ?

of course

**Comment by da-production** [comment]
i get this error

E/flutter (26313): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Could not launch https://www.cnac.dz/
E/flutter (26313): #0      UrlLauncher.browserView
package:cnac/services/urllauncher-service.dart:24
E/flutter (26313): <asynchronous suspension>
E/flutter (26313): #1      _AccueilScreenState._iconBuilder.<anonymous closure>
package:cnac/…/fr/accueil-screen.dart:95
E/flutter (26313): #2      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (26313): #3      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (26313): #4      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (26313): #5      BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter (26313): #6      PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter (26313): #7      PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter (26313): #8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (26313): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (26313): #10     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter (26313): #11     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter (26313): #12     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358
E/flutter (26313): #13     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (26313): #14     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (26313): #15     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (26313): #16     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (26313): #17     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (26313): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (26313): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (26313): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (26313): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (26313): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (26313):

**Comment by da-production** [comment]
### i have old version flutter 1.20.4 
## i get this error:
Note: D:\program files\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by TahaTesser** [comment]
Hi @da-production 
Please describe the issue more concisely and clearly. Are you only experiencing the issue with the Youtube link on physical running Android 7? 

You're not connected to any device device when running the `flutter un --verbose` command 
```bash
[  +76 ms] No supported devices connected.
[  +13 ms] "flutter run" took 250ms.
[  +17 ms] 
```

and in this comment, https://github.com/flutter/flutter/issues/70472#issuecomment-727164417 you have a different link than Yoitube 

I have no issues when running official with youtube link or your link

<details> 
<summary>flutter doctor -v</summary> 

```bash
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'URL Launcher',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'URL Launcher'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<void> _launched;
  String _phone = '';

  Future<void> _launchInBrowser(String url) async {
    if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: false,
        forceWebView: false,
        headers: <String, String>{'my_header_key': 'my_header_value'},
      );
    } else {
      throw 'Could not launch $url';
    }
  }

  Future<void> _launchInWebViewOrVC(String url) async {
    if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: true,
        forceWebView: true,
        headers: <String, String>{'my_header_key': 'my_header_value'},
      );
    } else {
      throw 'Could not launch $url';
    }
  }

  Future<void> _launchInWebViewWithJavaScript(String url) async {
    if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: true,
        forceWebView: true,
        enableJavaScript: true,
      );
    } else {
      throw 'Could not launch $url';
    }
  }

  Future<void> _launchInWebViewWithDomStorage(String url) async {
    if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: true,
        forceWebView: true,
        enableDomStorage: true,
      );
    } else {
      throw 'Could not launch $url';
    }
  }

  Future<void> _launchUniversalLinkIos(String url) async {
    if (await canLaunch(url)) {
      final bool nativeAppLaunchSucceeded = await launch(
        url,
        forceSafariVC: false,
        universalLinksOnly: true,
      );
      if (!nativeAppLaunchSucceeded) {
        await launch(
          url,
          forceSafariVC: true,
        );
      }
    }
  }

  Widget _launchStatus(BuildContext context, AsyncSnapshot<void> snapshot) {
    if (snapshot.hasError) {
      return Text('Error: ${snapshot.error}');
    } else {
      return const Text('');
    }
  }

  Future<void> _makePhoneCall(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    const String toLaunch = 'https://www.cnac.dz/';
    // const String toLaunch = 'https://www.youtube.com/watch?v=zrn7V3bMJvg';
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: TextField(
                    onChanged: (String text) => _phone = text,
                    decoration: const InputDecoration(
                        hintText: 'Input the phone number to launch')),
              ),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _makePhoneCall('tel:$_phone');
                }),
                child: const Text('Make phone call'),
              ),
              const Padding(
                padding: EdgeInsets.all(16.0),
                child: Text(toLaunch),
              ),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchInBrowser(toLaunch);
                }),
                child: const Text('Launch in browser'),
              ),
              const Padding(padding: EdgeInsets.all(16.0)),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchInWebViewOrVC(toLaunch);
                }),
                child: const Text('Launch in app'),
              ),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchInWebViewWithJavaScript(toLaunch);
                }),
                child: const Text('Launch in app(JavaScript ON)'),
              ),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchInWebViewWithDomStorage(toLaunch);
                }),
                child: const Text('Launch in app(DOM storage ON)'),
              ),
              const Padding(padding: EdgeInsets.all(16.0)),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchUniversalLinkIos(toLaunch);
                }),
                child: const Text(
                    'Launch a universal link in a native app, fallback to Safari.(Youtube)'),
              ),
              const Padding(padding: EdgeInsets.all(16.0)),
              RaisedButton(
                onPressed: () => setState(() {
                  _launched = _launchInWebViewOrVC(toLaunch);
                  Timer(const Duration(seconds: 5), () {
                    print('Closing WebView after 5 seconds...');
                    closeWebView();
                  });
                }),
                child: const Text('Launch in app + close after 5 seconds'),
              ),
              const Padding(padding: EdgeInsets.all(16.0)),
              FutureBuilder<void>(future: _launched, builder: _launchStatus),
            ],
          ),
        ],
      ),
    );
  }
}

```

</details>

Can you please provide `flutter run --verbose` with errors logs when connected to physical device, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
