### ISSUE TITLE
[CI] Flutter Test Coverage Issues - GithubActions

### ISSUE THREAD

**Issue by Nexushunter** [flutter/flutter#70478]
### Problem

When running `flutter test --coverage` in Github actions, the coverage file is empty. This is not an issue locally.

# Flutter Information
Channel: master
Version: 1.24
HOST OS: ubuntu:latest

[GH Action Minimal Example](https://github.com/Nexushunter/NexusDesktopEnvironment/runs/1397237364?check_suite_focus=true) 

Attached to the run is the coverage file that is generated by Flutter.

I'm not 100% sure why this is occurring, do I need to have a base lcov file added to the repo prior for it to work with GH Actions?

**Comment by pedromassangocode** [comment]
Hi @Nexushunter 
if the issue does not occur locally, but only with your CI/CD
I recommend you to ask support directly to the service provider.
Closing, as this isn't an issue with Flutter itself.
If you disagree, please write in the comments and I will reopen it.
Thank you
