### ISSUE TITLE
Application Lifecycle Docs:  Where to hang my startup code?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7047]
@sethladd asked me to file.  I would like some guidance from the docs on where to put my startup/initialization code.  Presumably part of some larger lifecycle documentation?

Example lifecycle events we could/should document (or provide examples for):
- Where startup code goes
- Application about to background
- application resume from background
- application about to quit

Maybe more?

Examples from iOS:
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html

And Android:
https://developer.android.com/training/basics/activity-lifecycle/index.html

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1994](https://github.com/flutter/website/issues/1994) via [**ZenHub**](https://www.zenhub.com/)
