### ISSUE TITLE
flutter attach does not show logs

### ISSUE THREAD

**Issue by CastixGitHub** [flutter/flutter#70473]
related to: https://github.com/flutter/flutter/issues/41357 and probably needed by https://github.com/flutter/flutter/issues/70457

### steps to reproduce
1. open a flutter project
2. run flutter run
3. detach with `d`
4. (without closing the app) attach with `flutter attach`

#### what's wrong

```
Waiting for a connection from Flutter on SM G903F...
Waiting for SM G903F to report its views...                         23ms
Syncing files to device SM G903F...                                     
 2,648ms (!)                                       

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
...
no logs here
```

#### temporary solution
`flutter logs & flutter attach`
https://github.com/flutter/flutter/issues/41357#issuecomment-562698875

##### doctor
`[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)`

**Comment by CastixGitHub** [comment]
I did do nothing, and it just started working again
scrolling the terminal up, I noticed `Error connecting to the service protocol: connection to device ended too early`

should this stay open for further investigation as the logs were present and the app was reload-able?

**Comment by TahaTesser** [comment]
Hi @CastixGitHub 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/70223
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
