### ISSUE TITLE
Improve search results from flutter.io

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#7049]
## Steps to Reproduce

If you search "scroll" from flutter.io (not docs.flutter.io), all the results on the first page are issues and code in Github. None of the results was really helpful in terms of finding widgets to implement a scrollable view. A couple of participants in the user study attempted to search for widgets but they immediately exited the search results page upon seeing the first few items. 

## Suggestions

Can we make Github an optional search scope? For example, by default the search would return items from the Flutter website and the API doc, but we can provide a checkbox to allow the user to include results from Github. Alternatively, we can simply direct the user to Github if he/she wants to search issues and code.

**Comment by sethladd** [comment]
I don't think we can make GitHub an optional search. We can remove it. Are we sure that GitHub results are almost-never what people want here? If so, easy to remove.

**Comment by InMatrix** [comment]
I think people who search from the homepage are not really interested in Github content, especially issues, most of which are no longer relevant to the latest version of Flutter anyway. 

I don't know how much we can tune the search settings. It seems that organic search ranking won't be very good even after we remove Github, since few external sites link to pages on flutter.io.

**Comment by sethladd** [comment]
OK. Removing github from search results.

**Comment by sethladd** [comment]
Done!

**Comment by InMatrix** [comment]
Thanks!

**Comment by eseidelGoogle** [comment]
When the Flutter framework is more stable, we could consider moving our examples out of the core sdk, and then one could imagine making search urls which only searched the examples.  That's a long way off though.
