### ISSUE TITLE
[infra] Mac web_tool_tests bot is failing due to incorrect chrome configuration

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#70503]
The mac bot for web_tools_test is failing right now in milo ui  due to configuration issues:

https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/18

I can see that chrome is installed in "chrome and driver dependency" step but when the flutter doctor runs in "flutter doctor" step, it shows chrome as not executable (it should be `Google Chrome` instead). Looks like `CHROME_EXECUTABLE` environment variable is set incorrectly.

**Comment by godofredoc** [comment]
I see some builds passing. Do we need to close this bug and open a new one for the current issue?

**Comment by annagrin** [comment]
Yes, this is fixed in https://flutter-review.googlesource.com/c/recipes/+/8646
