### ISSUE TITLE
Unnecessary null assertion and comment in Text

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#70523]
https://github.com/flutter/flutter/blob/87746c767408e3936093f338f9427e9b3ae4bfa7/packages/flutter/lib/src/widgets/text.dart#L358

Since data is of type `String`, not `String?` in the parameter, it can never be null, and thus this comment (and the assert below) is redundant, isn't it? 

Same for `InlineSpan span` in the rich text constructor:
https://github.com/flutter/flutter/blob/87746c767408e3936093f338f9427e9b3ae4bfa7/packages/flutter/lib/src/widgets/text.dart#L392

/cc @a14n

**Comment by cebr76** [comment]
I'm new to this repo, would you mind me taking this as my first issue? It sounds like an easy fix to get to know the processes

**Comment by a14n** [comment]
In weak mode you can pass `null` from an opted-out code to a non nullable value in opted-in code (and AFAICT there's no analyzer warning/hint/lint to catch those mistakes). Thus unless `--null-assertions` flag is enable by defaut everywhere assert non null should still be there.

```dart
//-------- a.dart  (opted-in)
String a = ''; // non null

//-------- b.dart  (opted-out)
// @dart=2.7
import 'a.dart';
void main() {
  a = null;   // no issue
}
```

**Comment by timsneath** [comment]
Ah, got it. Thanks for the explanation.
