### ISSUE TITLE
A crash report has been written to /Users/my user nameAndroidStudioProjects/flutter_apptest/flutter_01.log.

### ISSUE THREAD

**Issue by Hasan723** [flutter/flutter#70543]
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/my user name/Developer/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.".

**Comment by iapicca** [comment]
@Hasan723 
please provide your `flutter doctor -v` and your `flutter run -v`

**Comment by TahaTesser** [comment]
Hi @Hasan723 
Can you please find the `flutter_01.log` and paste it here 
Also please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
