### ISSUE TITLE
Cursor position is incorrect on Mac OS when typing many characters

### ISSUE THREAD

**Issue by kanekv** [flutter/flutter#70544]
![typing-bug](https://user-images.githubusercontent.com/521149/99155215-cfd28000-266a-11eb-87d6-11fecff9cf26.gif)

With every typed symbol cursor gets further apart from the text.

**Comment by TahaTesser** [comment]
Hi @kanekv 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
