### ISSUE TITLE
Writing regression tests that depend on animations can be difficult

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7054]
Writing tests that involve animation timing can be difficult. 

The snack bar tests (https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/snack_bar_test.dart)  are an example of this (my contribution is particularly bad). The durations animation tests depend on tend to be internal constants and it can be difficult to diagnose problems whose solution is to pump yet another frame.

**Comment by Hixie** [comment]
Not really sure what we can do about this.

**Comment by abarth** [comment]
pumpUntilNoTransientCallbacks might be the solution here.  Please re-open if that's not the case.
