### ISSUE TITLE
Navigator push

### ISSUE THREAD

**Issue by FMutunda** [flutter/flutter#70548]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _EffectiveTickerMode(effective mode: enabled):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2036 pos 12: '_elements.contains(element)': is not true.

**Comment by Abhishek01039** [comment]
Hello @FMutunda 
can you please provide the `flutter run -v`, `flutter doctor -v`, and minimal reproduction code?
Thanks.

**Comment by pedromassangocode** [comment]
Hi @FMutunda 
Please provide what was asked in the comment above.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
