### ISSUE TITLE
Separate Colour for Custom comments and Class completion comments 

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [flutter/flutter#70545]
## Use case

While adding a custom comment nearby a class completion comment, the comment gets mixes with them, since they are both of same colour. This image would make it more clear.
![Flutterfeauture](https://user-images.githubusercontent.com/55295915/99155434-e5cd5880-26dd-11eb-8dfd-6181a2711576.png)
It is difficult to distinguish them.
 

## Proposal

It would have been better if the custom comments and the other ones were of different colour.

**Comment by YazeedAlKhalaf** [comment]
I think this is in the dart package of vs code, syntax highlighting. You can use better comments in vs code to color comments, for sure you will find an alternative to the package.￼

**Comment by iapicca** [comment]
@Ankur-Khandelwal 
you may want to open this issue [here](https://github.com/Dart-Code/Dart-Code/issues)

**Comment by Ankur-Khandelwal** [comment]
@iapicca Actually, I am facing this issue in Android Studio.

**Comment by iapicca** [comment]
> @iapicca @YazeedAlKhalaf Actually, I am facing this issue in Android Studio.

@Ankur-Khandelwal 
yours seems to me a feature request rather than an "issue you are facing ", since nothing is broken;
I shouldn't have used that term myself.
Anyhow if you want to open a feature request for intellij plugin as well you can do so [here](https://github.com/flutter/flutter-intellij/issues)

in any case this doesn't seem to be an issue or a feature request for flutter as a framework

**Comment by Ankur-Khandelwal** [comment]
@iapicca Yes, it's a feature request. It's not an issue exactly.

**Comment by Ankur-Khandelwal** [comment]
Infact, I would like to work on adding this feature. I don't know exactly how to do that, however if the maintainers or the contributers can guide me a bit, I would be very happy to do that.

**Comment by iapicca** [comment]
@Ankur-Khandelwal this is not something that should be discussed on the flutter repository
if you want guidance on how to contribute I recommend to do so on [discord](https://discord.gg/N7Yshp4)

this feature request doesn't seems to be related to flutter, but rather to [vscode](https://github.com/Dart-Code/Dart-Code/issues) and [intelliJ](https://github.com/flutter/flutter-intellij/issues) plugins
in my opinion this feature request should be closed and addressed in the dedicated github pages

**Comment by TahaTesser** [comment]
Hi @Ankur-Khandelwal 
This is a Flutter plugin feature request, as @iapicca mentioned https://github.com/flutter/flutter/issues/70545#issuecomment-727606458, please file an issue on the plugin repository 
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
