### ISSUE TITLE
Flutter doctor not finding Android Studio Dart and Flutter plugins on a fresh install

### ISSUE THREAD

**Issue by zhengzhu88** [flutter/flutter#70551]
Filing this bug because https://github.com/flutter/flutter/issues/21881 said to open a new issue if the issue reproduces.
## Steps to Reproduce

1. Start with a Macbook that hasn't had Android Studio or Flutter installed before
2. Follow instructions at [Get Flutter SDK](https://flutter.dev/docs/get-started/install/macos#get-sdk) for the `git clone ... stable` option
3. Follow instructions at [Install Android Studio](https://flutter.dev/docs/get-started/install/macos#install-android-studio)
4. Install Flutter and Dart plugins in Android studio using the plugin manager.
4. Run `flutter doctor -v` to get logs below

Note: this is a completely fresh install on the latest stable versions. XCode installation is incomplete because it's still downloading from App Store.
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/zhengzhu/projects/dependencies/flutter
    • Framework revision 1aafb3a8b9 (30 hours ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zhengzhu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

It's not clear whether this interferes with development yet. As far as I know, everything could work fine and it's just sync issue with the tool or something. Still waiting for Xcode installation to complete. Attached screenshots to Android studio version and that Android Studio has the plugins installed.

<img width="889" alt="Android Studio version" src="https://user-images.githubusercontent.com/5005270/99160075-f8bd3a00-2697-11eb-8fe0-eac622122928.png">

<img width="912" alt="Android Studio installed plugins" src="https://user-images.githubusercontent.com/5005270/99160057-d9bea800-2697-11eb-99b5-b2107c4d8476.png">

**Comment by zhengzhu88** [comment]
I'm able to run the flutter demo app on both Android and iOS, so it doesn't seem to interfere with development. `flutter doctor -v` still shows the same issue
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/zhengzhu/projects/dependencies/flutter
    • Framework revision 1aafb3a8b9 (2 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zhengzhu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by pedromassangocode** [comment]
Hi @zhengzhu88 
This is a known issue, it happens because the latest version of Android Studio changed the path where the plugins are located and Flutter tools can't find it. This is just a warning and you can still use Flutter without worries.

Thank you

**Comment by DanTup** [comment]
@pedromassangocode do you know if there's an issue for about fixing this (or if it's already fixed)? Someone reported it to me but the only ones I can find are closed and it's not clear if fixed. It seems like a bug if Flutter isn't detecting the plugins (even if it's not preventing things from working).
