### ISSUE TITLE
Would like a rosetta stone "flutter for X devs" (where X = iOS, Android, Web, etc.)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7055]
customer: mulligan has asked for this, and I believe I've heard others ask for something similar.

The idea would be some way to relate existing concepts into the Flutter world, targeting different classes of developers.  mulligan was an iOS dev before Flutter, so their request is specific to iOS.

- [ ] Flutter for the web developer
- [ ] Flutter for the Android developer
- [ ] Flutter for the iOS developer

@Hixie or @sethladd would have opinions.

**Comment by sethladd** [comment]
This is a really big request. Not sure how we handle meta-issues, but we probably want to split this into separate issues.

For the web: https://github.com/flutter/flutter/issues/5107

For the Android developer: https://github.com/flutter/flutter/issues/7139

For the iOS developer: https://github.com/flutter/flutter/issues/7140

Will close this for now, as we have individual issues open.

**Comment by eseidelGoogle** [comment]
This may in part by solved by eventual examples built across multiple platforms too.
