### ISSUE TITLE
[Share] When sharing video with Facebook, the video is not shown in the message.

### ISSUE THREAD

**Issue by shanxus** [flutter/flutter#70578]
In iOS, when sharing video via file url with Facebook by the share plugin, the video is not shown in the message.(but it works with Message and AirDrop).

Screenshot:
![3A14A58B-44ED-47CC-8AAE-ECF007AECDD0](https://user-images.githubusercontent.com/9797361/99202784-43030000-27eb-11eb-81f7-b5571860330b.JPG)

Flutter doctor:
<img width="673" alt="截圖 2020-11-16 上午9 11 30" src="https://user-images.githubusercontent.com/9797361/99202973-02f04d00-27ec-11eb-8259-db0a00230343.png">

**Comment by TahaTesser** [comment]
Hi @shanxus 
Can you please provide `flutter run --verbose` and a complete reproducible minimal code sample and sample video, it is all videos? Is it recorded on iPhone or downloaded video, what the video format is? 
Thank you

**Comment by shanxus** [comment]
Hi @TahaTesser 

1. For **the reproducible minimal code sample**:
(I just simply export video to the album, and share the exported url of that video with share plugin)

`final url = await getExportedURL();`
`Share.shareFiles([url]);`

2. **The url is like below**
`file:///private/var/mobile/Containers/Data/Application/9A1233FC-76C4-4DE3-94F5-435562B70112/tmp/output_video.mp4`. And it could be recorded on iPhone or downloaded video, and the format is **.mp4**.


3. **The sample video**(As described in the issue title, when sharing video with Facebook, the video is not shown in the message):
https://youtu.be/xEkUaMLL3I8


4. **flutter run --verbose**(The logs is too much. This is part of the logs.):
[ +101 ms] executing: [/Users/shanovo2/Desktop/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8874f21e79d7ec66d0457c7ab338348e31b17f1d
[        ] executing: [/Users/shanovo2/Desktop/flutter/] git tag --points-at HEAD
[  +17 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.3
[   +9 ms] executing: [/Users/shanovo2/Desktop/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/shanovo2/Desktop/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +38 ms] executing: [/Users/shanovo2/Desktop/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +4 ms] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2
[  +34 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: /Users/shanovo2/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[ +849 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 12.2
           Build version 12B45b
[   +1 ms] executing: xcrun --find xcdevice
[  +12 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +27 ms] List of devices attached
[ +120 ms] // List of devices...
[  +15 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +140 ms] Found plugin device_apps at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/device_apps-1.2.0/
[   +4 ms] Found plugin device_info at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/
[   +6 ms] Found plugin firebase_analytics at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[   +2 ms] Found plugin firebase_analytics_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[   +2 ms] Found plugin firebase_core at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.1/
[   +3 ms] Found plugin firebase_core_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +1 ms] Found plugin firebase_crashlytics at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.2.2/
[   +4 ms] Found plugin flutter_inappwebview at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/
[   +2 ms] Found plugin flutter_native_timezone at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_native_timezone-1.0.4/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +8 ms] Found plugin image_picker at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+11/
[   +2 ms] Found plugin in_app_purchase at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.4+16/
[  +21 ms] Found plugin package_info at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3/
[   +4 ms] Found plugin path_provider at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.18/
[   +1 ms] Found plugin path_provider_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[   +1 ms] Found plugin path_provider_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/
[   +3 ms] Found plugin permission_handler at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/
[   +3 ms] Found plugin photo_manager at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.5.8/
[   +9 ms] Found plugin share at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/share-0.6.5+4/
[   +1 ms] Found plugin shared_preferences at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12/
[   +1 ms] Found plugin shared_preferences_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+2/
[   +1 ms] Found plugin shared_preferences_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[   +2 ms] Found plugin shared_preferences_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[   +1 ms] Found plugin shared_preferences_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.1+1/
[   +8 ms] Found plugin sqflite at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/
[  +16 ms] Found plugin uni_links at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/uni_links-0.4.0/
[   +1 ms] Found plugin url_launcher at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.5/
[        ] Found plugin url_launcher_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[        ] Found plugin url_launcher_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+8/
[   +2 ms] Found plugin url_launcher_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.4+1/
[   +1 ms] Found plugin url_launcher_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+1/
[   +2 ms] Found plugin video_player at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/video_player-0.11.1+2/
[   +1 ms] Found plugin video_player_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.4/
[ +106 ms] Found plugin device_apps at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/device_apps-1.2.0/
[        ] Found plugin device_info at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/
[   +2 ms] Found plugin firebase_analytics at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.16/
[        ] Found plugin firebase_analytics_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[        ] Found plugin firebase_core at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.1/
[        ] Found plugin firebase_core_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[        ] Found plugin firebase_crashlytics at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.2.2/
[   +1 ms] Found plugin flutter_inappwebview at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/
[        ] Found plugin flutter_native_timezone at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_native_timezone-1.0.4/
[        ] Found plugin flutter_plugin_android_lifecycle at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.11/
[   +2 ms] Found plugin image_picker at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+11/
[        ] Found plugin in_app_purchase at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.4+16/
[   +5 ms] Found plugin package_info at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3/
[   +1 ms] Found plugin path_provider at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.18/
[        ] Found plugin path_provider_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[        ] Found plugin path_provider_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/
[   +1 ms] Found plugin permission_handler at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/
[   +1 ms] Found plugin photo_manager at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/photo_manager-0.5.8/
[   +3 ms] Found plugin share at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/share-0.6.5+4/
[        ] Found plugin shared_preferences at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12/
[        ] Found plugin shared_preferences_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+2/
[        ] Found plugin shared_preferences_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[        ] Found plugin shared_preferences_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[        ] Found plugin shared_preferences_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.1+1/
[   +3 ms] Found plugin sqflite at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/
[   +5 ms] Found plugin uni_links at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/uni_links-0.4.0/
[        ] Found plugin url_launcher at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.5/
[   +1 ms] Found plugin url_launcher_linux at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[        ] Found plugin url_launcher_macos at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+8/
[        ] Found plugin url_launcher_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.4+1/
[        ] Found plugin url_launcher_windows at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+1/
[   +1 ms] Found plugin video_player at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/video_player-0.11.1+2/
[        ] Found plugin video_player_web at /Users/shanovo2/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.4/
[  +35 ms] Generating /Users/shanovo2/ycvbeauty/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +107 ms] Starting incremental build...
[   +1 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +3 ms] Launching lib/main.dart on Shan iPhone11 in debug mode...

Hope this information can help. Thanks.

**Comment by TahaTesser** [comment]
Hi @shanxus 
I just tried to reproduce this using the latest `share 0.6.5+4` & `image_picker: ^0.6.7+14`  on iSO 14.2 physical device using both `.mp4` and `.mov` formats, video is shared to Facebook with no issues

### Video file
[avng_mpfour.mp4.zip](https://github.com/flutter/flutter/files/5552518/avng_mpfour.mp4.zip)

### Code Sample
Using official example https://pub.dev/packages/share/example
Just changed  `getImage` to `getVideo
```dart
                      final pickedFile = await imagePicker.getVideo(
                        source: ImageSource.gallery,
                      );
```
### Preview
![IMG_0659](https://user-images.githubusercontent.com/48603081/99373097-074d6080-28e7-11eb-886f-9d85c9070509.jpg)

<img width="180" alt="Screenshot 2020-11-17 at 3 11 03 PM" src="https://user-images.githubusercontent.com/48603081/99373239-2ea42d80-28e7-11eb-908b-a96d5e7a807d.png">



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.2

! Doctor found issues in 1 category.

```

</details>


Can you please try the official sample with the same video

**Comment by shanxus** [comment]
Hi, @TahaTesser 

As your suggestion, I tried the example with `getVideo`. I found using file path instead of file url would make it work!

For example, for the file url `file:///private/var/mobile/Containers/Data/Application/9A1233FC-76C4-4DE3-94F5-435562B70112/tmp/output_video.mp4.` case, using path `/private/var/mobile/Containers/Data/Application/9A1233FC-76C4-4DE3-94F5-435562B70112/tmp/output_video.mp4.` would make the sharing work.

There is no issue now. Thanks for your help!
