### ISSUE TITLE
[tool_crash] RPCError: The client closed with pending request "_flutter.listViews"

### ISSUE THREAD

**Issue by RenFeiYu** [flutter/flutter#70579]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
Oops; flutter has exited unexpectedly: "_flutter.listViews: (-32000) Bad state:
The client closed with pending request "_flutter.listViews".".
⣽Lost connection to device.
A crash report has been written to /Users/r/Desktop/chamberlain/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+_flutter.listViews%3A+%28-32000%29+Bad+state%3A+The+client+closed+with+pending+request+%22_flutter.listViews%22.

[✓] Flutter (Channel unknown, 1.24.0-7.0.pre, on Mac OS X 10.15.7 19H2
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.24.0-7.0.pre at /Users/r/flutter
    • Framework revision a0860f6e87 (2 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/r/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 2FB646C7-C1F8-4970-82C6-E27B0C1995F0 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e70236e36ce1d32067dc68eb55519ec3e14b6b01
### Plugins
flutterautotext-edc93450782282315a05298e0e55bbed24112126
barcode_scan-1.0.0
device_info-1.0.0
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-7.1.1
image_picker-0.6.7
package_info-0.4.3+2
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
permission_handler-3.3.0
screen-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3
video_player-0.10.12+5
video_player_web-0.1.4
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by pedromassangocode** [comment]
I found similar logs on https://github.com/flutter/flutter/issues/63025.

**Comment by jmagman** [comment]
@RenFeiYu Can you attach the log file `/Users/r/Desktop/chamberlain/flutter_01.log` so we can see the stack?

**Comment by jonahwilliams** [comment]
There is no stack in this crash, what is happening is that the app itself is crashing while we are still setting up the vm service connection, and that causes an unhandled async exception in dds. That should be fixed by https://github.com/flutter/flutter/pull/70847

**Comment by jonahwilliams** [comment]
err, not that one, this one: https://github.com/flutter/flutter/pull/70712

**Comment by jonahwilliams** [comment]
We're still seeing this

**Comment by Kirstygoodary** [comment]
Hi, I'm getting a similar error but the pending request was "_createDevFS"

A full log can be found at [](https://github.com/flutter/flutter/issues/72753#issue-772477118 )

**Comment by pedromassangocode** [comment]
Hi @slightfoot 
Was this closed by mistake in your fork of the Dart lang repository? just to confirm!

**Comment by jmagman** [comment]
Looks like @bkonyi fixed in https://dart-review.googlesource.com/c/sdk/+/175163 / https://github.com/dart-lang/sdk/commit/fc892d7fca37932c373f34aad1e82c5e8f8cb11f

**Comment by pedromassangocode** [comment]
FYI, https://github.com/flutter/flutter/issues/73815 seems similar!
