### ISSUE TITLE
Document how to build and publish an app on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7057]
(tracking issue)

A user requested documentation for "build and publish" workflows.

**Comment by olostan** [comment]
It would be great to have something "for real beginners" like https://ionicframework.com/docs/guide/publishing.html that describe how to publish app even if you don't know basics of Android/iOS development workflow (signing APKs etc)

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/6825  (how to sign an APK)

**Comment by mit-mit** [comment]
Splitting this bug into two; one for iOS (https://github.com/flutter/flutter/issues/8366), and one for Android (present bug)
