### ISSUE TITLE
[Web] Flutter beta branch switch from stable with find some program

### ISSUE THREAD

**Issue by zhuyonghao** [flutter/flutter#70584]
![image](https://user-images.githubusercontent.com/18735317/99218880-74dd8c00-2816-11eb-9fa1-68802333457f.png)
some widgets can‘t find property

**Comment by TahaTesser** [comment]
Hi @zhuyonghao 
Please restart your IDE and try again
If the problem persists, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by zhuyonghao** [comment]
Thank you， Switch to Dev, then switch back to Beta, and it gets better
