### ISSUE TITLE
“Unable to load asset: null” in my flutter app

### ISSUE THREAD

**Issue by macphailmagwira** [flutter/flutter#70583]
When my app loads, no image loads at all, and t just crashes and i keep getting this error in my flutter app but I can't seem to find the problem, usually, when it can't find load an asset it tells me which asset, but this time it just says unable to load asset null, I don't know how to find the problem

it shows a breakpoint at this point

/// An [AssetBundle] that loads resources using platform messages.
class PlatformAssetBundle extends CachingAssetBundle {
  @override
  Future<ByteData> load(String key) async {
    final Uint8List encoded = utf8.encoder.convert(Uri(path: Uri.encodeFull(key)).path);
    final ByteData? asset =
        await defaultBinaryMessenger.send('flutter/assets', encoded.buffer.asByteData());
    if (asset == null)
      throw FlutterError('Unable to load asset: $key');   ******RIGHT HERE IS THE BREAKPOINT
    return asset;
  }
}

**Comment by roxifas** [comment]
It's most likely that you passed a `null` where you needed to use an asset name string, so you should check your code. Also this sounds like a support question, your issue will probably get closed.

**Comment by pedromassangocode** [comment]
Hi @macphailmagwira 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by macphailmagwira** [comment]
hey guys,  found the problem, i passed a null, cleared the issue

**Comment by macphailmagwira** [comment]
thanks everyone
