### ISSUE TITLE
Regression: SliverAppBar & SliverList exhibiting different behaviour on iPhone 8 and iPhone 11/12 Pro Simulators | Severe Bug on iPhone 8

### ISSUE THREAD

**Issue by joniaiuser** [flutter/flutter#70589]
## Steps to Reproduce
**Minimal Reproducible Sample**
https://github.com/joniai/reproSliverBug

1. Set up SliverList and SliverAppBar with navigators on tap for the list items.
2. Flutter run on iPhone 8 simulator iOS 14.2 on latest stable.

**Expected results:** 
Expected same behaviour in both simulators.

**Actual results:** 
I am seeing weird behaviour for my SliverList and SliverAppBar on **iPhone 8 Simulator**.

1. When tapping on the SliverAppBar area, it responds(in the example, it will print the onTap from the SliverList item) as if I am clicking on one of the items in the Sliver list below.
2. When tapping an item in the sliver list, it seems to call onTap twice.

This behaviour is NOT seen on iPhone 11/12 Pro Simulators. I haven't tested on other simulators. The app works perfectly on those.

<details>
  <summary>Logs</summary>

```
```

```
No errors found.
```

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
 
[✓] Connected device (2 available)
```

</details>

**Comment by joniaiuser** [comment]
Have added a minimal reproducible sample at this link:

https://github.com/joniai/reproSliverBug

**Comment by pedromassangocode** [comment]
Hi @joniaiuser 
Can you please provide your `flutter doctor -v` and the steps to reproduce the issue? it is not clear what do to with the code provided and what is the actual vs expected results.
Thank you

**Comment by joniaiuser** [comment]
Flutter doctor -v

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-SG)
    • Flutter version 1.22.4 at /Users/********/Developer/flutter
    • Framework revision 1aafb3a8b9 (3 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/*******/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile)      • 3968A55D-9355-433B-97EE-B4BA39F7CBC1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • iPhone 12 Pro (mobile) • 53739417-5B07-49D5-B9BF-1A27941B131D • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
```

@pedromassangocode as mentioned, run the code on iPhone 8 simulator and tap on any of the list items, it will trigger onTap twice instead of once.. When you tap on the SliverAppBar it triggers onTap even though there is no gesture detector for it.

This behaviour is not observed on iPhone 11 Pro and iPhone 12 Pro simulators. I haven't tested with others yet.

This is a regression as it used to work fine on all devices last tested 2 weeks ago.

**Comment by joniaiuser** [comment]
The reason why this is a severe bug for us is because it breaks any kind of interactions with Sliver on iPhone 8, tapping items leads to onTap called twice and hence navigators being called twice; tapping SliverAppBar triggers a tap of SliverList item instead. The entire widget is basically unusable when testing on iPhone 8 Simulator, even though it works perfectly with iPhone 11/12 Pro that I've tested. Not sure what's the scale of the issue and if it affects physical devices as well, but it's certainly worth investigating further.

**Comment by joniaiuser** [comment]
Are you able to repro? Or need additional help. Thanks

**Comment by pedromassangocode** [comment]
Hi @joniaiuser 
I just tested in iPhone 8 simulator and iPhone 12 Pro and got the same behavior on `stable` and `master` channel: when you tap on items, it prints only once.

If you have any additional information please share it here.
Thank you

**Comment by joniaiuser** [comment]
@pedromassangocode Are you on the same iOS and MacOS versions? I'm using Big Sur.

**Comment by pedromassangocode** [comment]
@stuartmorgan wondering if this may have the same root cause as https://github.com/flutter/flutter/issues/64961.

**Comment by stuartmorgan** [comment]
We don't know enough about the root cause of that issue for me to speculate at this point. It seems potentially possible though.

**Comment by joniaiuser** [comment]
This issue has self-resolved. Not sure why/how. Will close.
