### ISSUE TITLE
Issue from website page 入门: 在macOS上搭建Flutter开发环境

### ISSUE THREAD

**Issue by PrayerT** [flutter/flutter#70590]
From URL: https://www.flutterchina.club/get-started/setup_macos.md
I'm a student in China, I've done all the things wrote on the website including editing mynahs_profile. But it still doesn't work on my Mac even with an VPN . Creating a new flutter project  on Android Studio will be stuck with "Running 'flutter pub upgrade' in XXX". It really upset me so much.
I hope to hear any reply from you soon.

**Comment by chenls** [comment]
It could be the same problem：
https://github.com/flutter/flutter/issues/70591#issue-743562659

**Comment by benjaminwan** [comment]
@PrayerT 
从macOS Catalina开始，mac的shell换成了zsh，所以要编辑用户目录下的```~/.zshrc```才是对的。
.bash_profile只能针对更早版本的macOS。

**Comment by PrayerT** [comment]
> @PrayerT
> 从macOS Catalina开始，mac的shell换成了zsh，所以要编辑用户目录下的`~/.zshrc`才是对的。
> .bash_profile只能针对更早版本的macOS。

好的清楚了，非常感谢
