### ISSUE TITLE
Create CLI using flutter

### ISSUE THREAD

**Issue by dheerajmpai** [flutter/flutter#70599]
## Use case

I am quite fascinated to see how flutter can be used to create Android, ios, linux, MacOS, Windows and Web App. Would be awesome if there is a way to extend to create CLIs too.

**Comment by pedromassangocode** [comment]
Hi @dheerajmpai 
Can you please elaborate what exactly you are proposing?
Thank you

**Comment by stuartmorgan** [comment]
Flutter is a UI framework; https://dart.dev/tools/dart2native is probably what you are looking for.
