### ISSUE TITLE
Unable to install flutter 

### ISSUE THREAD

**Issue by ssharanyab** [flutter/flutter#70593]
I installed flutter and ran flutter doctor. I am getting the following error
![image](https://user-images.githubusercontent.com/39287772/99225493-27f5b780-280e-11eb-811a-39da3268b4f1.png)

**Comment by prithviraj324** [comment]
Flutter is already installed (v1.22.4). Its shows a green tick next to Flutter, that means its installed. 
You might want to install the flutter and dart plugins for Android Studio Code

**Comment by pedromassangocode** [comment]
For more information see the install guide https://flutter.dev/docs/get-started/install
