### ISSUE TITLE
Error starting app on Android - open zip file app.flx

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7060]
I'm seeing this, wondering if it's related to the expand/close controls not appearing correctly:

Running lib/main.dart on XT1060...
E/flutter (18139): [ERROR:../../flutter/assets/unzipper_provider.cc(16)] Unable to open zip file: /data/data/com.example.flutter/app_sky_shell/app.flx

I seem to have room on the device.

**Comment by jtrunick** [comment]
In debug mode the same code ends up with this

E/flutter ( 8725): [ERROR:../../flutter/runtime/dart_init.cc(137)] Isolate vm-service exited with an error
E/flutter ( 8725): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 8725): FileSystemException: Creation of temporary directory failed, path = '/data/local/tmp' (OS Error: Permission denied, errno = 13)
E/flutter ( 8725): #0      _Directory.createTemp.<anonymous closure> (directory_impl.dart:128)
E/flutter ( 8725): #1      _RootZone.runUnary (dart:async/zone.dart:1404)
E/flutter ( 8725): #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
E/flutter ( 8725): #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
E/flutter ( 8725): #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
E/flutter ( 8725): #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
E/flutter ( 8725): #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
E/flutter ( 8725): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter ( 8725): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
E/flutter ( 8725): #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
E/flutter ( 8725): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/6619 has a similar error.  Unclear if it's related.

**Comment by eseidel** [comment]
@olostan just reported a similar error via gitter.  He was using genymotion and said it went away when he moved to an AVD emulator.
