### ISSUE TITLE
Upgrading pre 1.12 Android projects missing guide for pre-warming a FlutterEngine

### ISSUE THREAD

**Issue by bsheen** [flutter/flutter#70602]
The documentation [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#migrating-flutterview-uses) states the following:
>Some apps may have required pre-warming a Flutter experience. It is now recommended that all add-to-app use-cases pre-warm Flutter experiences to achieve optimal visual performance when initially rendering a Flutter UI. Please refer to the [Flutter guide for pre-warming a FlutterEngine](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) (TODO: mattcarroll) to update your code for pre-warming Flutter.

[Flutter guide for pre-warming a FlutterEngine](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
is circular link to the same documentation.

The TODO mentions mattcarroll, however, given @matthew-carroll appears here https://github.com/flutter/flutter/graphs/contributors I assume this is the @matthew-carroll the TODO is referring?

**Comment by bsheen** [comment]
@matthew-carroll are you able to point me in the right direction for a guide to pre-warming a FlutterEngine?

**Comment by pedromassangocode** [comment]
Hi @bsheen 
You can follow up on the link bellow to see how to cache a FlutterEngine instance (aka pre-warming FlutterEngine):
https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-3-optional-use-a-cached-flutterengine

Will leave this opened to update the WiKi properly.

**Comment by bsheen** [comment]
Thanks @pedromassangocode. Exactly the information we need to proceed. Greatly appreciated.

**Comment by Roshan13046** [comment]
I am interested in working on this issue.

**Comment by Alameen688** [comment]
@chinmaygarde could you help update the wiki to the point to the correct link https://github.com/flutter/flutter/issues/70602#issuecomment-727888533
Thanks

**Comment by daadu** [comment]
@kf6gpe (if you have the permission) Reminder: Can you update the wiki to point to the current link: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-3-optional-use-a-cached-flutterengine

**Comment by eggfly** [comment]
I removed todo in the wiki(https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) of pre-warming engine with the add-to-app cached engine link. This issue can be closed.
