### ISSUE TITLE
Regression in memory benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70621]
https://flutter-flutter-perf.skia.org/e/?begin=1605294663&end=1605316383&keys=X88c5e148d6aa81219b137a12610c0016&num_commits=50&request_type=1&xbaroffset=22532

diff-maxdiff-median diff-minend-maxend-medianend-min & flutter_gallery__back_button_memory.

Looks like this engine roll: https://github.com/flutter/flutter/pull/70490

**Comment by chinmaygarde** [comment]
https://github.com/flutter/engine/pull/22203 looks like the related commit that changed lifecycle management on Android. @jason-simmons is going to take a look at finding the root cause.
