### ISSUE TITLE
FloatingLabelBehaviour not being inherited from InputDecorationTheme

### ISSUE THREAD

**Issue by emem365** [flutter/flutter#70625]
While using TextFields in pone of my apps, I found that even if I set FloatingLabelBehaviour to something in InputDecorationTheme inside the ThemeData, this made no affect on the FloatingLabelBehaviour of any TextField. I had to set the FloatingLabelBehaviour in each TextField individually. 

While investigating the code I came accross the contructor for InputDecoration where it said : 
`this.floatingLabelBehavior = FloatingLabelBehavior.auto,`
and later while applying defaults 
`floatingLabelBehavior: floatingLabelBehavior ?? theme.floatingLabelBehavior,`
It seems obvious that since floatingLabelBehaviour is never set to null. The behaviour from theme would never be used!

Is this intentional? Or a bug? I am not sure.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Copy the code from [this gist](https://gist.github.com/emem365/45c9fc9e0581f654e7951301844e87ae) to main.dart
3. Run `flutter run`

**Expected results:** 
 Expected was that once I set floatingLabelBehaviour in InputDecorationTheme, all TextFields would follow that unless otherwise specified in the widget.

**Actual results:** 

The TextField seems to be set default  to FloatingLabelBehaviour.auto regardless of whether you set something in InputDecorationTheme.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/47733983/99284198-f6a3d880-285b-11eb-9ff2-592e7e32e6be.gif)

I dont think run logs are necessary for this, as no crash or anything of that sort occur. The bug (If this is not intentional) lies in the code as mentioned above.

flutter --version :
```
Flutter 1.24.0-8.0.pre.252 • channel master • https://github.com/flutter/flutter.git
Framework • revision bf2c9dfc05 (2 days ago) • 2020-11-14 22:38:02 -0500
Engine • revision 3e77d854a7
Tools • Dart 2.12.0 (build 2.12.0-45.0.dev)
```

**Comment by xu-baolin** [comment]
This high probability is a bug, I will fix it.
