### ISSUE TITLE
[web]: OffsetLayer.toImage support in Canvaskit

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#70627]
Currently OffsetLayer.toImage is not supported in Cavanskit. https://github.com/flutter/engine/blob/c712e4d1957078b19f5a128d3a5d701fca829089/lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart#L20

**Comment by luigi-rosso** [comment]
We use this in desktop Rive to provide a color loupe in our color picker. This is preventing us from supporting this feature on the web!
![loupe](https://user-images.githubusercontent.com/454182/99306068-78b6e180-2809-11eb-9bd8-6db41bbe3ce0.png)

**Comment by yjbanov** [comment]
Assigning to @hterkelsen who has something almost working already

**Comment by hterkelsen** [comment]
Fixed by https://github.com/flutter/engine/pull/22085
