### ISSUE TITLE
testFlutterViewWarm flake

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#70630]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863455884397541584/+/steps/run_module_test_ios/0/stdout#L30855_0

text:
```
 [module_test_ios] [STDOUT] stdout:     t =     5.89s     Wait for io.flutter.add2app.Host to idle
 [module_test_ios] [STDOUT] stdout:     t =     5.92s Waiting 1.0s for "Button tapped 1 time." Other to exist
 [module_test_ios] [STDOUT] stdout:     t =     6.92s     Checking `Expect predicate `exists == 1` for object "Button tapped 1 time." Other`
 [module_test_ios] [STDOUT] stdout:     t =     6.93s         Checking existence of `"Button tapped 1 time." Other`
 [module_test_ios] [STDOUT] stdout:     t =     6.94s         Capturing element debug description
 [module_test_ios] [STDOUT] stdout:     t =     6.95s Checking existence of `"Button tapped 1 time." Other`
 [module_test_ios] [STDOUT] stdout:     t =     6.97s Assertion Failure: FlutterUITests.m:54: (([app.otherElements[@"Button tapped 1 time."] waitForExistenceWithTimeout:1.0]) is true) failed
 [module_test_ios] [STDOUT] stdout:     t =     7.00s Tear Down
```

Flaked on post submit closing the tree.

**Comment by dnfield** [comment]
Increasing the timeout to 60 seconds did not resolve this - see e.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863168602568196768/+/steps/run_module_test_ios/0/stdout?format=raw where this still timed out after 60s.

@gaaclarke @jmagman - any thoughts on this?

**Comment by dnfield** [comment]
@stuartmorgan mentioned that sometimes these kinds of tests are just flaky. I'm going to disable this test for the time being to get the tree green again.

**Comment by jmagman** [comment]
I turned off all the module_test_ios XCUITests in https://github.com/flutter/flutter/pull/71730.
