### ISSUE TITLE
Hot reload is not working on VSCode

### ISSUE THREAD

**Issue by francoismari** [flutter/flutter#70644]
Hi! VSCode is always telling me this error when I'm trying to use hot reload.

> Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancelling, message: Error while starting Kernel isolate task}]}

I'm on the last stable version of Flutter and I've tried every solutions on the web but none of them are working. Is there a fix for that? Thanks.

**Comment by pedromassangocode** [comment]
Hi @francoismari 
I see there's an open issue (https://github.com/flutter/flutter/issues/64758) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
