### ISSUE TITLE
Investigate and identify graphics memory usage, and document our findings

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#70658]
Internal: b/174239899

At a high level, provide a better understanding for the Flutter team:

- Why do similar Android and Flutter applications have significantly different graphics memory usage?
- What, if anything, can we do to reduce graphics memory usage in Flutter by default?
- What, if anything, can we do to inform developers about how to reduce graphics memory usage in a Flutter application?

There are no specific asks of Skia yet, but some initial areas of investigation are the resource cache size for Skia and the raster/layer cache.

Initial poking at this shows:

- ~60mb of graphics memory usage for a vanilla "flutter create" app.
- ~26mb of graphics memory usage for a vanilla Android app that has similar graphical features (text, a few buttons, a few shadows)

Reducing the resource cache limit from a mulitplier of 12 screens to 4 screens significantly reduces memory usage: ~60mb to ~56 MB.

Disabling the raster and layer cache reduces it by about another 10mb.

Going to poke at this further to figure out where memory is going and what we can do about it.

**Comment by joniaiuser** [comment]
Just to add on, this is also a huge problem for iOS. My local assets often cannot fit into the cache and have to be reloaded causing bad transitions. We are constantly tweaking the size of our assets to try to overcome this problem on most phones.

**Comment by dnfield** [comment]
Here's a particularly simple app that initially reaches > 50mb of graphics memory usage:

```dart
import 'dart:ui';

void main() {
  window.onBeginFrame = beginFrame;
  window.scheduleFrame();
}

void beginFrame(Duration timeStamp) {
  final builder = SceneBuilder();
  final recorder = PictureRecorder();
  final canvas = Canvas(recorder);
  canvas.drawRect(
    const Rect.fromLTRB(10, 10, 300, 300),
    Paint()..color = const Color(0xFFABCDEF),
  );
  final picture = recorder.endRecording();
  builder.addPicture(Offset.zero, picture);
  final scene = builder.build();
  window.render(scene);
  scene.dispose();
}
```

If you background it, it does a good job of reducing graphics memory usage to almost nothing. Foregrounding again gets a more sane 20-30mb usage (I guess?). But if you rotate the screen a bit it jumps back up to the 50-60 range.

**Comment by dnfield** [comment]
So here are some high level findings:

- On Android, the window wants to allocate buffers for its own GL operations.
- We then make a SurfaceView, which also allocates buffers for Flutter's GL operations.

You end up with an additional three buffers over what would be used "out of the box". You can see these in `adb shell dumpsys SurfaceFlinger`.

This is basically what happens with any app that renders egl content in a SurfaceView - e.g. Google Maps has similar characteristics. 

It seems unlikely to me that we'll be able to do much about this, but there mightbe one or two more levers to try.

**Comment by dnfield** [comment]
That said, there are other ways we can reduce memory usage, even if we can't feasibly reduce graphics memory usage.

**Comment by dnfield** [comment]
One significant contributor for some customers is path masks. That is improved by flutter/engine#22620

**Comment by Hixie** [comment]
Is the goal of this bug a doc, a tool, or fixes?

**Comment by dnfield** [comment]
Doc

**Comment by dnfield** [comment]
Document is going through internal review and pending wider release. I'm going to close this for now. I expect to open further issues going forward (or prioritize existing issues) based on discussions that follow with Flutter and related teams.
