### ISSUE TITLE
Skip running checks on draft PRs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#70659]
Infra will always run builds and tests against any PR, regardless of the current state it is in. Contributors can mark PRs with either the `work-in-progress` label or use GitHub's draft PR tool to indicate a PR is not ready for review.

I think this should also be used as a signal for infra to not run checks against the PR. For example, we should not be spending capacity on these draft PRs until they are marked ready.

**Comment by CaseyHillers** [comment]
\cc @Hixie I brought this up in the infra bug triage, and was told you had a counter argument for why we should run tests all the time. I'm interested in hearing it, can you share?

**Comment by Hixie** [comment]
Say someone doesn't have a Mac, and wants to submit a patch. They're not sure if their patch will even work, so they don't want people to review it yet, but they want to be able to run the tests on that patch. Submitting the patch as a work in progress PR is basically the way to do that.

I can't actually think of any time where I would _not_ want to run at least basic tests like analysis on a PR.

In general I think we should have three tiers of tests:

 - basic tests (including Dart analysis, docs analysis, framework tests) on Cirrus, which should run on every PR.
 - cheap LUCI tests (e.g. all the above, plus probably a bit more), on LUCI, which should run on every PR once a trusted contributor (which could be the person submitting the PR) has verified that the PR is not obviously someone trying to mine bitcoin.
 - all the LUCI tests (ideally including e.g. devicelab), on LUCI, once a PR has been deemed ready for final tests.

I'm happy for the tests that are only in the third tier to be disabled on WIP PRs.

**Comment by CaseyHillers** [comment]
> so they don't want people to review it yet, but they want to be able to run the tests on that patch

Ahh I see. I think my misunderstanding came from how contributors can get reviews.

> I'm happy for the tests that are only in the third tier to be disabled on WIP PRs.

That sounds good to me, and actually makes a lot of sense to incorporate as part of the auto submit functionality.

I'm going to leave this open to keep in mind when we enable the DeviceLab tests on presubmit runs (https://github.com/flutter/flutter/issues/65046)
