### ISSUE TITLE
Allow for instrumentation/replacement of compute

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#70664]
On some platforms, spawning an isolate is particularly expensive memory wise. Packages and/or the framework may use `compute` (or otherwise spawn an isolate) to avoid jank when decoding a large chunk of data, e.g. to json parse or otherwise decode a serialized format.

It would be helpful to make it clearer when an isolate is spawned, particularly for developers who are working on memory related issues and trying to understand what might be causing a sudden increase in memory usage.

At the very least, we should be able to allow instrumentation of `compute` in foundation. We might be able to do something in the engine with the isolate create callback, if that is in fact invoked every time an isolate is created. Otherwise, we may need some additional support upstream in Dart.

/cc @terrylucas @jacob314 
/cc @chinmaygarde  @jason-simmons @zanderso

**Comment by jacob314** [comment]
From DevTools we already know when isolates are spawned so we could surface that in the timeline if it is valuable.

**Comment by dnfield** [comment]
Probably. However, I think we also need a way to drop in a replacement for this for apps that just don't want anyone out there spawning an isolate, or may want to reuse an already spawned isolate for `compute` tasks.

**Comment by dnfield** [comment]
@aam @mkustermann - do you have any thoughts about the need for this with the lightweight isolates work?

I'm partially under the impression that the lightweight isolate work would make replacing this less necessarily, as long as we resolve https://github.com/flutter/flutter/issues/79573

**Comment by mkustermann** [comment]
> @aam @mkustermann - do you have any thoughts about the need for this with the lightweight isolates work?
> I'm partially under the impression that the lightweight isolate work would make replacing this less necessarily, ...

I agree. The spawn-latency and memory overhead should decrease by order(s) of magnitude and is unlikely going to be an issue.

**Comment by dnfield** [comment]
In that case I'm going to close this as obsolete.
