### ISSUE TITLE
Problem with path_provider plugins after migrate to Embedding V2

### ISSUE THREAD

**Issue by mrdemqn** [flutter/flutter#70677]
After updating Flutter SDK I started migrating to Embedding V2 and there was a problem with the path_provider plugin.

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

Changed plugin versions, tried different versions,
did flutter clean / invalidate cache many times, tried to register the plugin manually via PathProviderPlugin.registerWith (registry.registrarFor ("io.flutter.plugins.pathprovider.PathProviderPlugin")); ... Nothing works. Help me please.

flutter doctor --verbose:
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale ru-BY)
    • Flutter version 1.22.4 at /Applications/FlutterSDK/flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dimon/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G950F (mobile) • ce031713a3704f1203 • android-arm64 • Android 9 (API 28)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 2 categories.

### MainActivity.tk

import android.content.Intent
import android.widget.Toast
import io.flutter.embedding.android.FlutterActivity
import io.flutter.plugin.common.MethodChannel
import io.branch.referral.Branch
import io.branch.referral.BranchError
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.view.FlutterMain
import org.json.JSONObject

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "wifi_display")
                .setMethodCallHandler { call, result ->
                    if (call.method == "show_display") {
                        result.success(wifiSettings())
                    }
                }
    }

    private fun wifiSettings() {
        /* Открывает настройки screen mirroring, если телефон поддерживает,
        * Можно подключится в телевизору.  */
        try {
            startActivity(Intent("android.settings.CAST_SETTINGS"))
            return
        } catch (exception1: Exception) {
            Toast.makeText(applicationContext, "Device not supported", Toast.LENGTH_LONG).show()
        }
    }

    override fun onStart() {
        super.onStart()
        // Branch init
        Log.i("BRANCH SDK", "onStart fun BranchInit")
        Branch.sessionBuilder(this).withCallback(BranchListener).withData(this.intent?.data).init()
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        this.intent = intent
        Log.i("BRANCH SDK", "onNewIntent fun")
        // Branch reinit (in case Activity is already in foreground when Branch link is clicked)
        Branch.sessionBuilder(this).withCallback(BranchListener).reInit()
    }

    object BranchListener: Branch.BranchReferralInitListener {
        override fun onInitFinished(referringParams: JSONObject?, error: BranchError?) {
            Log.i("BRANCH SDK", "BranchListener")
            if (error == null) {
                Log.i("BRANCH SDK -> Error == NULL", referringParams.toString())
                Log.i("BRANCH SDK", referringParams.toString())
                // Retrieve deeplink keys from 'referringParams' and evaluate the values to determine where to route the user
                // Check '+clicked_branch_link' before deciding whether to use your Branch routing logic
            } else {
                Log.e("BRANCH SDK", error.message)
            }
        }
    }
}

**Comment by pedromassangocode** [comment]
Hi @mrdemqn 
I see there's an open issue (https://github.com/flutter/flutter/issues/46679) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by mrdemqn** [comment]
> Hi @mrdemqn
> I see there's an open issue (#46679) addressing the case you described.
> Please follow up on that issue, I'm closing the current one as a duplicate.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

None of the above in this issue helped.

**Comment by crushman1** [comment]
> > Hi @mrdemqn
> > I see there's an open issue (#46679) addressing the case you described.
> > Please follow up on that issue, I'm closing the current one as a duplicate.
> > If you disagree, please write in the comments and I will reopen it.
> > Thank you
> 
> None of the above in this issue helped.

Im not sure if this will make a difference for you but if you're using `flutter_facebook_login` , Remove it, `flutter clean` then try running the app again. for some reason thats the only thing that worked for me. this facebook plugin was affecting many other plugins as well such as flutter_tts and vibration
