### ISSUE TITLE
Text input, you need to click twice to hide the keyboard

### ISSUE THREAD

**Issue by JokerGHit** [flutter/flutter#70671]
When I enter an input box that already has content, in order to close the keyboard, I need to click twice

--flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.239], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

**Comment by JokerGHit** [comment]
flutter version 1.22.2

**Comment by JokerGHit** [comment]
> When I enter an input box that already has content, in order to close the keyboard, I need to click twice

flutter version 1.22.2

**Comment by pedromassangocode** [comment]
Hi @JokerGHit 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
