### ISSUE TITLE
Stuck at: Syncing files to device Chrome when trying to run a project

### ISSUE THREAD

**Issue by khallediRA** [flutter/flutter#70684]
The process that i have made in order to create my project was :
**flutter channel beta
flutter upgrade
flutter config --enable-web
flutter create projectname**

I tried to run this project via flutter run -d Chrome and w white screen on google appeared and doesn't seem to be in progress, 
I tried to : 
**flutter clean
flutter run -d Chrome,**
Same issue is persisting.

I tried to **flutter run -v -d chrome** and here is the result
![capture 1 stack](https://user-images.githubusercontent.com/72705387/99380672-8da77980-28ca-11eb-89a0-6487a385f197.PNG)

![capture 2 stack](https://user-images.githubusercontent.com/72705387/99380698-94ce8780-28ca-11eb-8d91-ad6bf3172d70.PNG)

**Comment by pedromassangocode** [comment]
Hi @khallediRA 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?

Please avoid posting images as it is difficult to see and copy the logs.

Thank you

**Comment by khallediRA** [comment]
Hello @pedromassangocode,
Sorry for the screen shots,
I have just started my project and here is how it look like 
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        backgroundColor: Colors.black,
      ),
    );
  }
}
`
Thank you.
[run verbose.txt](https://github.com/flutter/flutter/files/5553882/run.verbose.txt)
[flutter doctor .txt](https://github.com/flutter/flutter/files/5553886/flutter.doctor.txt)

**Comment by khallediRA** [comment]
Hello @pedromassangocode  ,
Sorry for the screen shots,
I have just started my project and here is how it look like.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        backgroundColor: Colors.black,
      ),
    );
  }
}
```
And here's requested files : 
[run verbose.txt](https://github.com/flutter/flutter/files/5554836/run.verbose.txt)
[flutter doctor .txt](https://github.com/flutter/flutter/files/5554841/flutter.doctor.txt)

Thank you.

**Comment by pedromassangocode** [comment]
Hi @khallediRA 
Based on the logs (and the images) you provided it seems that the build succeeded, it just took longer than expected. It usually happens with me as well.

```
[  +33 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10702 ms] Syncing files to device Chrome... (completed in 10 868ms, longer than expected)
[   +2 ms] Synced 27.7MB.
[   +2 ms] <- accept
[   +1 ms] Caching compiled dill
[ +584 ms] Using Ouverture dans une session de navigateur existante.
[ +573 ms] [CHROME]:
[  +35 ms] [CHROME]:DevTools listening on ws://127.0.0.1:55085/devtools/browser/7144a30d-32d9-40e9-aa39-54329f8b0daa
```

**Comment by khallediRA** [comment]
I waited for more than an hour and nothing happened

**Comment by pedromassangocode** [comment]
Reopening. This happened to me while triaging an issue today.

I can confirm that the issue only happens on beta, and that all other channels are fine, including `master`. So leaving this opened just to make sure that team is aware of it.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-18.1.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)
      (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      86.0.4240.198

• No issues found!

```
</details>

**Comment by kf6gpe** [comment]
@ferhatb Do you think this is still a problem? @pedromassango If you have time, would you mind re-testing when you get a moment?

**Comment by pedromassangocode** [comment]
Hi @kf6gpe 
Sorry for the late response, I was able to reproduce the issue on first run using Android emulator.  The message in the Logs stops at "syncing files to device <device-name>" but I'm able to interact with the app.

```console
Launching lib/main.dart on sdk gphone x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
I/flutter_exampl( 6616): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl( 6616): Unquickening 12 vdex files!
W/flutter_exampl( 6616): Unexpected CPU variant for X86 using defaults: x86_64
W/flutter_example( 6616): type=1400 audit(0.0:49): avc: denied { read } for name="max_map_count" dev="proc" ino=135681 scontext=u:r:untrusted_app_27:s0:c167,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.example.flutter_example
W/flutter_exampl( 6616): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_exampl( 6616): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl( 6616): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl( 6616): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Debug service listening on ws://127.0.0.1:58557/11l24gN9IsM=/ws
Syncing files to device sdk gphone x86 64...
```

It gives the impression that the build is stuck but we can interact with the app once it is launched. I literally can reproduce this every time I run on Emulator on Beta channel.

### Web

I cannot reproduce this running on Chrome.

```console
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:58958/IjIzaBw4N50=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:58958/IjIzaBw4N50=/ws
```

**Comment by ferhatb** [comment]
@pedromassangocode , so the issue is launching mobile android build not web Chrome correct? I will remove platform-web label if thats the case.

**Comment by pedromassangocode** [comment]
Right, I filled https://github.com/flutter/flutter/issues/75407 focused on Android Emulators.

**Comment by WaterHashira** [comment]
can you please reopen the issue i am facing this issue with chrome, it was running fine just a while ago, but when i reloaded it it got stuck
