### ISSUE TITLE
[triage] the "lock bot" doesn't seems to work

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#70685]
the [lock bot](https://github.com/flutter/flutter/issues/50552) [[PR](https://github.com/flutter/flutter/pull/53723)] does not seem to work.
it's barely a mild annoyance, but I'm having plenty notification from very old **closed** issues

**Comment by godofredoc** [comment]
@christopherfujino can you please point us to the location of the lock bot configs?

**Comment by christopherfujino** [comment]
Here's the config file: https://github.com/flutter/flutter/blob/master/.github/lock.yml

**Comment by godofredoc** [comment]
The configuration does not have any filters but there are many bugs that are not being locked. This is an example:

https://github.com/flutter/flutter/issues/74692

**Comment by godofredoc** [comment]
@christopherfujino anything else that we can check?

**Comment by christopherfujino** [comment]
> @christopherfujino anything else that we can check?

Not that I know of. I think any further investigation would have to happen upstream.

**Comment by christopherfujino** [comment]
Looks like the one we're using is deprecated, and the readme recommends migrating to a newer github action version? https://github.com/dessant/lock-threads-app

**Comment by godofredoc** [comment]
@Hixie would it be safe to enable the new app or is there a process for approval?

**Comment by Hixie** [comment]
There's Google-internal documentation about what apps we are allowed to enable (anything that gets write access to the repo is definitely out, but there may be other rules). Assuming the bot fits within the framework the OSPO team has set out, there's no process. To put it another way, the process is for one of us (you, me, or the other admins) to verify that the app fulfills the rules set out by OSPO and then approve it.

**Comment by godofredoc** [comment]
This is now fixed.
