### ISSUE TITLE
Triggering a route transition (or a state change) when app is inactivated

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#70697]
There are a couple of use cases from customer:money where they would like to change the state of the UI in response to user putting the app in the background (e.g. pressing the home button). This is currently not possible in a smooth way since Flutter does not schedule frames in inactive state.

Example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Named Routes Demo',
    // Start the app with the "/" named route. In this case, the app starts
    // on the FirstScreen widget.
    initialRoute: '/',
    routes: {
      // When navigating to the "/" route, build the FirstScreen widget.
      '/': (context) => FirstScreen(),
      // When navigating to the "/second" route, build the SecondScreen widget.
      '/second': (context) => SecondScreen(),
    },
  ));
}

class FirstScreen extends StatefulWidget {
  @override
  FirstScreenState createState() => FirstScreenState();
}

class FirstScreenState extends State<FirstScreen> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.inactive) {
      Navigator.push(context, PageRouteBuilder(
        pageBuilder: (context, animation1, animation2) => SecondScreen(),
        transitionDuration: Duration(seconds: 0),
      ));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Launch screen'),
          onPressed: () {
            // Navigate to the second screen using a named route.
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            // Navigate back to the first screen by popping the current route
            // off the stack.
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

This app switches the user to page two when home button is pressed. However, if you run this on the simulator and inspect the recording, you will see that page one is still displayed until the app is fully in view and then the switch happens. This leads to a jarring experience.

Is there a way to instruct Flutter to schedule at least N frames before pausing? or perhaps signal that the task is "urgent" and should not be paused?

I advised the team to do this in the native platform since it depends on the lifecycle and there might be other race conditions that cause problems if we try to solve this in Flutter (such as user rapidly relaunching the app).

**Comment by mehmetf** [comment]
@HansMuller @Hixie for their thoughts.

**Comment by HansMuller** [comment]
CC @goderbauer @chunhtai - more extensions to the new navigator API?

**Comment by chunhtai** [comment]
Either way seems like a hack. I think this is a rare use case, and my opinion is that we should not support this natively in Flutter.

**Comment by mehmetf** [comment]
We sort of support it already. Just not in a smooth way.

Perhaps we can treat route changes as special and allow them to build and "display" even if the application is not showing yet? I know there are gotchas there but even a placeholder (such as rendering the base material layer) would be less jarring than a sudden blink or transition as the page changes.

**Comment by chunhtai** [comment]
We only know there is animation going on in the scheduling layer. even if we do have a way to determine whether the route change has finished, I still think this is a really weird change. If such functionality has to exist, it should be put into a third party plugin or package.

**Comment by mehmetf** [comment]
Hm.. OK. So the bottom line is because it would be quite difficult to know when the target page has actually finished rendering, we cannot support this properly in the framework. That's a fine statement.

I am still curious why you think this change is weird. I think responding to lifecycle changes is just like responding to any other state and displaying different UI/dialog/whatever upon lifecycle change is a normal thing to do.

**Comment by chunhtai** [comment]
I think drawing frame in inactive state itself is a change that against our existing design, and can be error prompt.

Now I think of this, if they are using Navigator 2.0 or has access to the page api. they can push a route on top of the screen without any animation by specify the transition delegate.

**Comment by mehmetf** [comment]
That would still cause the same issue, correct? When you push a route on app lifecycle change, the route isn't actually rendered until the app is back in resumed state.

**Comment by chunhtai** [comment]
yes, you are right. there is still one frame delay.

Regarding this feature request, I still think we should not include such functionality in framework. I will close this issue for now. Feel free to reopen if you have other concerns.
