### ISSUE TITLE
Regression in worst_frame_rasterizer_time_millis complex_layout_scroll_perf_ios__timeline_summary

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70699]
https://flutter-flutter-perf.skia.org/e/?begin=1605143043&end=1605596159&keys=Xbfbd070798d6e4e3d002b460a596e7d0&requestType=0&xbaroffset=22543. 

Started to climb at https://github.com/flutter/flutter/pull/68794. Increasingly bad at https://github.com/flutter/flutter/pull/70657.

**Comment by jason-simmons** [comment]
I don't have an iOS setup that can reproduce this exactly.  But I can reproduce a change in rasterizer metrics on an Android (Moto G4) device starting with https://github.com/flutter/engine/commit/ecfe5aec50e5a8d97e4818addbcef47f7300d2d1.

On the Moto G4 `worst_frame_rasterizer_time_millis` and `99th_percentile_frame_rasterizer_time_millis` decrease slightly with that change.  `90th_percentile` and `average` metrics look unaffected.

If the regression on the iOS benchmark only affects `worst_frame_rasterizer_time_millis` but not the average or 90th percentile metrics then I'd vote for rebaselining the benchmark.

@flar

**Comment by Hixie** [comment]
(see also https://github.com/flutter/flutter/issues/70700)

**Comment by flar** [comment]
> On the Moto G4 `worst_frame_rasterizer_time_millis` and `99th_percentile_frame_rasterizer_time_millis` decrease slightly with that change. `90th_percentile` and `average` metrics look unaffected.

That's a good thing, right? (i.e. not a regression you are calling out)

> If the regression on the iOS benchmark only affects `worst_frame_rasterizer_time_millis` but not the average or 90th percentile metrics then I'd vote for rebaselining the benchmark.
> 
> @flar

There is no re-baselining for Skia perf - it is self analyzing with respect to regressions.

**Comment by jason-simmons** [comment]
Yes - in my tests on the Moto G4 the https://github.com/flutter/engine/commit/ecfe5aec50e5a8d97e4818addbcef47f7300d2d1 change yielded a small performance improvement

**Comment by zanderso** [comment]
Closing based on discussion above. Worst case frame appears bi- or tri- modal with the new most common value in line with previous modes.
