### ISSUE TITLE
Categorize total memory usage to help debugging memory issues

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#70706]
This issue will focus on categorize the total memory usage on the top level into the following categories as suggested in https://github.com/flutter/flutter/issues/56486#issuecomment-696390318

- [ ] Dart; 
- [ ] native (memory allocated by engine, Skia, and other C/C++ code) 
- [ ] graphics (memory allocated by GPU drivers, mainly driven by Skia); 
- [ ] Platform (e.g., memory allocated by Java code in Android, ObjC/Swift code in iOS, or some custom embedders). See also #55934.

Further partitions can be made to dive deeper. See, e.g., https://github.com/flutter/flutter/issues/70658 and https://github.com/flutter/flutter/issues/57229.

**Comment by dnfield** [comment]
One thing that's been helpful to me in looking at graphics usage is the contents of `adb shell dumpsys SurfaceFlinger`, looking specifically at the Graphics Allocation Buffers related to the process.

**Comment by toneyzeng** [comment]
I have done a similar feature in UC Browser. Maybe i can make a PR if helpful.

![image](https://user-images.githubusercontent.com/5031712/99475381-619efd80-2989-11eb-9849-03807b3d5c01.png)

**Comment by pouloghost** [comment]
> I have done a similar feature in UC Browser. Maybe i can make a PR if helpful.
> 
> ![image](https://user-images.githubusercontent.com/5031712/99475381-619efd80-2989-11eb-9849-03807b3d5c01.png)

looking forward for a pr or some source code. at least we can merge to our own engine for perf analysis while developing
