### ISSUE TITLE
Text widget is cutting last part of strings in Firefox in Flutter Web

### ISSUE THREAD

**Issue by codesxt** [flutter/flutter#70705]
I'm using flutter web to develop an app but I got a report that text looks incomplete. This problem is not present in Chrome.

This is how it looks in Chrome (good):

![Captura de pantalla de 2020-11-17 13-21-47](https://user-images.githubusercontent.com/5240873/99416798-fd703100-28d7-11eb-9e01-e55ceba30944.png)

And this is how it looks on Firefox (bad):

![Captura de pantalla de 2020-11-17 13-23-26](https://user-images.githubusercontent.com/5240873/99416919-1d9ff000-28d8-11eb-897c-7db341c6144d.png)

This is my result from flutter doctor -v:

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.269, on Linux, locale es_CL.UTF-8)
    • Flutter version 1.24.0-8.0.pre.269 at /home/bruno/Desarrollo/SDK/flutter
    • Framework revision 543d3cfa57 (hace 22 minutos), 2020-11-18 00:03:02 +0800
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/bruno/Desarrollo/SDK/Android/Sdk
    • Platform android-30, build-tools 28.0.3
    • ANDROID_HOME = /home/bruno/Desarrollo/SDK/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      80.0.3987.149

• No issues found!
```

I'm using Firefox Quantum 68.6.0esr (64-bit).

I've created a minimal example that reproduces this behaviour.

I've defined a basic City object, a basic card view that displays a City and a column structure similar to the one that I'm using in my app.

In this column structure, I added the following examples:

- A City card with a string of several words
- A City card with a single word
- A Text widget with several words
- A Text widget with a single word

The results are as follows in Chrome (good):

![Captura de pantalla de 2020-11-17 15-17-21](https://user-images.githubusercontent.com/5240873/99430509-31535280-28e8-11eb-8fe6-30f25ba9d5c6.png)

And the errors can be seen as follows in Firefox (bad):

![Captura de pantalla de 2020-11-17 15-19-12](https://user-images.githubusercontent.com/5240873/99430567-47f9a980-28e8-11eb-991b-4c4608d21df7.png)

The source code of the example that I made is:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    City city = City(
      id: 1,
      name: 'Example City Loaded in build()'
    );
    City city2 = City(
      id: 2,
      name: 'Arica'
    );
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        physics: ScrollPhysics(),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            CityCard(city: city),
            CityCard(city: city2),
            Text('This is a line.'),
            Text('Word.'),
          ],
        )
      )
    );
  }
}

class CityCard extends StatelessWidget {
  CityCard({
    this.city
  });
  City city;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Container(
        padding: EdgeInsets.all(10.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              city.name,
              style: Theme.of(context).textTheme.headline6,
            )
          ]
        )
      )
    );
  }
}

class City {
  final int id;
  final String name;

  City({this.id, this.name});

  factory City.fromJson(Map<String, dynamic> json) {
    return City(
      id: json['id'],
      name: json['name']
    );
  }
}

```

This may be related to https://github.com/flutter/flutter/issues/61614 and https://github.com/flutter/flutter/issues/49946 but I'm not sure since in those cases strings are not being cut.

**Comment by codesxt** [comment]
I also had a very similar issue to this one while using DropDownMenuItem and a list of "Regions".

Here is how the list looked on Chrome (good):

![Captura de pantalla de 2020-11-17 15-30-49](https://user-images.githubusercontent.com/5240873/99431764-0538d100-28ea-11eb-946e-8c79345aafee.png)

And here is how it looked on Firefox (bad):

![Captura de pantalla de 2020-11-17 15-30-28](https://user-images.githubusercontent.com/5240873/99431801-1386ed00-28ea-11eb-9f79-7be88f9462f3.png)

If you look at where it should say "Región de Ñuble", you still can see the top part of the Ñ letter, so it seems that the text is being cut and sent to the next line:

![Captura de pantalla de 2020-11-17 15-34-29](https://user-images.githubusercontent.com/5240873/99432141-8001ec00-28ea-11eb-9df2-72b5e04cb0b7.png)

In the end for this case I solved it by switching from this code:

```
DropdownMenuItem(
  value: region.id.toString(),
  child: Text(region.name)
)
```

to this code:

```
DropdownMenuItem(
  value: region.id.toString(),
  child: Container(
    width: double.infinity,
    child: Text(region.name)
  )
)
```

**Comment by TahaTesser** [comment]
Hi @codesxt 
`I'm using Firefox Quantum 68.6.0esr (64-bit).` indicates a very old version of Firefox if i am not, i tried downloading latest Firefox quantum, it says 83.0

Tried on Deskptop with  mobile preview, text looks normal
Please try on the latest firefox stable at least 
<img width="753" alt="Screenshot 2020-11-18 at 6 00 45 PM" src="https://user-images.githubusercontent.com/48603081/99531109-3daedc80-29c8-11eb-8096-69f58e956b61.png">
<img width="1436" alt="Screenshot 2020-11-18 at 6 00 33 PM" src="https://user-images.githubusercontent.com/48603081/99531111-3ee00980-29c8-11eb-9337-9774eb100f35.png">

Firefox on mobile
![Screenshot_2020-11-18-18-06-27-55_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/48603081/99531570-f4ab5800-29c8-11eb-894e-e7c5d1ad80a9.jpg)



![Screenshot_2020-11-18-18-06-34-64_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/48603081/99531578-f5dc8500-29c8-11eb-97e1-a872d2f80c00.jpg)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.291, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.291 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision c1042314a9 (6 hours ago), 2020-11-18 01:38:02 -0500
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)     • B46BCEDD-9601-4CD0-8D0B-CE4EF96ACD93 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.198

• No issues found!

```

</details>

**Comment by codesxt** [comment]
@TahaTesser Thanks for pointing that out! I just realized that I misconfigured automatic updates a while ago 😅

Clossing the issue then.
