### ISSUE TITLE
Regression in several benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70700]
```
90th_percentile_frame_build_time_millis 
99th_percentile_frame_build_time_millis 99th_percentile_vsync_transitions_missed
MatrixUtils_affine_transformRect_iteratio
naverage_frame_build_time_millis
worst_frame_build_time_millis
```

See https://flutter-flutter-perf.skia.org/e/?begin=1605313686&end=1605556258&keys=X12a0c84fa6dd149fe7e6b00cdeb56b5f&num_commits=50&request_type=1&xbaroffset=22542.

Looks like the roll at https://github.com/flutter/flutter/pull/70554.

**Comment by jason-simmons** [comment]
This started with the roll of ICU version 68.1 into the engine (https://github.com/flutter/engine/commit/8bb47c5446541d58f8eb158feb79382dc316c0b1).  Construction of ICU break iterators (used during text layout) is now more expensive.

See https://github.com/flutter/flutter/issues/70623
