### ISSUE TITLE
Tasks failing "Could not find an option named "luci-builder"."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70720]
LUCI presubmit tasks on https://github.com/flutter/flutter/pull/70647 are all failing.
```
Could not find an option named "luci-builder".
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863348911970552624/+/steps/run_gradle_plugin_bundle_test/0/stdout

**Comment by CaseyHillers** [comment]
Rebasing should fix. This change landed recently in https://github.com/flutter/flutter/commit/a228a17c57976eeabb0655b0f0ed8e3b4e7787f2

**Comment by CaseyHillers** [comment]
FYI https://github.com/flutter/flutter/issues/68668

**Comment by christopherfujino** [comment]
this will break all the release channel builds

**Comment by CaseyHillers** [comment]
> this will break all the release channel try builds

I created a revert of the recipe change here to unblock: https://flutter-review.googlesource.com/c/recipes/+/8846

@christopherfujino would it be okay if I move this arg to only the post submit tests? My assumption is that the post submit tests for releases is using a separate recipe.

**Comment by CaseyHillers** [comment]
Revert landed and everything has propagated. I'm going to move this arg to only run on post submit devicelab tasks that are marked to upload results.
