### ISSUE TITLE
Flutter Doctor: IntelliJ IDEA not detect plugins not installed in channel beta

### ISSUE THREAD

**Issue by rodrigorahman** [flutter/flutter#70729]
In the beta channel, I run the command flutter doctor and is not showing me the warning about plugins flutter and dart in intellij not installed.

**flutter doctor in channel stable:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale pt-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**flutter doctor in channel beta**

Building flutter tool...
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (5 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
 ~  flutter doctor                                                                                  ✔  31s  21:14:44
Downloading package sky_engine...                                   0,6s
Downloading flutter_patched_sdk tools...                            0,7s
Downloading flutter_patched_sdk_product tools...                    0,6s
Downloading darwin-x64 tools...                                     1,0s
Downloading darwin-x64/font-subset tools...                         0,1s
Downloading android-arm-profile/darwin-x64 tools...                 0,3s
Downloading android-arm-release/darwin-x64 tools...                 0,3s
Downloading android-arm64-profile/darwin-x64 tools...               0,2s
Downloading android-arm64-release/darwin-x64 tools...               0,3s
Downloading android-x64-profile/darwin-x64 tools...                 0,3s
Downloading android-x64-release/darwin-x64 tools...                 0,3s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on macOS 11.0.1 20B29 x86_64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.51.1)
[!] Connected device

**Comment by pedromassangocode** [comment]
This is not an error it is just a warning caused by the new Android Studio version where they changed the plugins path and Flutter can detect the plugins. You can still use Flutter.
