### ISSUE TITLE
[webview_flutter] Add more access to Webview settings

### ISSUE THREAD

**Issue by tfinlay** [flutter/flutter#70731]
## Use case

I'm migrating an existing application from [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) to webview_flutter, and am sorely missing some of the extra WebView settings that flutter_webview_plugin exposes.

Primarily (for my use-case at least) I'm missing:
* useWideViewPort
* withZoom

As these allow me to force the webview to display webpages that are designed for desktop. Without these options enabled the webpage is squashed to fit the frame, instead of being rendered zoomed out, which I would prefer in this case (Chrome shows the page zoomed out on the same phone).

## Proposal

The addition of these two parameters to the WebView constructor, or exposing them as settings on WebViewController.

**Comment by Faiizii** [comment]
I am also facing the same issue, since I need to modify the Web Setting to run my code.

Android WebView allows to define/update the webview setting like 

        `WebSettings settings = webView.getSettings();

       //how can I set these in flutter webview?
        settings.setAllowContentAccess(true); 
        settings.setAllowFileAccessFromFileURLs(true); 
        settings.setAllowUniversalAccessFromFileURLs(true);

        settings.setMediaPlaybackRequiresUserGesture(false);

        webView.clearCache(true);
        webView.clearHistory();//it is also unavailable, I think.
        webView.setWebViewClient(new WebViewClient());`

**Comment by LongXiangGuo** [comment]
Suggest also support setTextZoom, as the android font will follow the font changes set by the system, the behavior is different from IOS.

**Comment by Maxim-Gorin** [comment]
any news?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/3325 should address the use case described here; if there are other settings you'd like, please file a new issue.

**Comment by Aulig** [comment]
I've filed a new issue for useWideViewPort here: https://github.com/flutter/flutter/issues/93125
