### ISSUE TITLE
Google Sign in Package w.r.t. Google Security Change 1/4/2021

### ISSUE THREAD

**Issue by dcoleyoung** [flutter/flutter#70738]
Apologies if this is the wrong forum for this question.  

Using the flutter package google_sign_in (https://pub.dev/packages/google_sign_in) and was made aware of this security change that impacts Jan 2021 - 
https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html

Do I need to take action for this package?

**Comment by pedromassangocode** [comment]
Hi @dcoleyoung 
I don't think so, please see https://flutter.dev/community for resources and asking questions like this. I highly suggest you to post this question on Discord in the Plugins channel.
