### ISSUE TITLE
Flutter app flashes when you bring it back to foreground on some Android phones,such as Oppo.

### ISSUE THREAD

**Issue by chiuhol** [flutter/flutter#70745]

**Comment by chiuhol** [comment]
Both the official demo have the problems.

**Comment by chiuhol** [comment]
![1071605672480_ pic](https://user-images.githubusercontent.com/55732167/99500108-d63b6180-29b4-11eb-83b7-13ceff57a215.jpg)

**Comment by TahaTesser** [comment]
Hi @chiuhol 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by chiuhol** [comment]
Hi @TahaTesser 
I'm running the official sample code as the same problem.
The following is `flutter doctor -v` and `flutter run --verbose`.
![flutter_doctor_v](https://user-images.githubusercontent.com/55732167/99614519-9e83f680-2a54-11eb-91e2-75e71cb2d328.png)
![1](https://user-images.githubusercontent.com/55732167/99614524-a2b01400-2a54-11eb-83c6-bf0f534fa96d.png)

**Comment by TahaTesser** [comment]
Hi @chiuhol 
Please refrain from posting screenshot if not needed, please copy logs and paste it here
By official example code, you mean code counterexample when a project is created?
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by chiuhol** [comment]
Hi @TahaTesser 
That's what i mean
My device is  `Pixel 3 XL API 28(android-x64 emulator)`
The following is `flutter run --verbose` 
`[ +169 ms] Generating /Users/chiuhol/hello_world/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +50 ms] Using hardware rendering with device Android SDK built for x86 64. If you notice graphics artifacts, consider enabling software rendering with
           "--enable-software-rendering".
[  +22 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +4 ms] Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
[   +5 ms] /Users/chiuhol/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/chiuhol/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/chiuhol/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill /var/folders/7t/qj2_w8mn01xg9z4x6z01lf080000gn/T/flutter_tools.6HflCX/flutter_tool.1wj6jW/app.dill --packages
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +14 ms] executing: /Users/chiuhol/Library/Android/sdk/build-tools/30.0.1/aapt dump xmltree /Users/chiuhol/hello_world/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[  +74 ms] Exit code 0 from: /Users/chiuhol/Library/Android/sdk/build-tools/30.0.1/aapt dump xmltree /Users/chiuhol/hello_world/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.example.hello_world" (Raw: "com.example.hello_world")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello_world" (Raw: "hello_world")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello_world.MainActivity" (Raw: "com.example.hello_world.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell -x logcat -v time -t 1
[  +45 ms] Exit code 0 from: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           11-20 11:51:33.695 I/GnssLocationProvider( 1969): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@4ddc242)
[   +1 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell -x logcat -v time -t 1
[  +19 ms] Exit code 0 from: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           11-20 11:51:33.695 I/GnssLocationProvider( 1969): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@4ddc242)
[  +13 ms] <- compile package:hello_world/main.dart
[  +10 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb version
[  +19 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as /Users/chiuhol/Library/Android/sdk/platform-tools/adb
[   +4 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb start-server
[  +17 ms] Building APK
[  +19 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/chiuhol/hello_world/android/gradlew.
[        ] /Users/chiuhol/hello_world/android/gradlew mode: 33261 rwxr-xr-x.
[  +14 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +13 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PAC
KAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1
.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio4.0","idea.executable":"stu
dio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests
access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-193.6911.18.40.6626763","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An
application in Android Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":tr
ue,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"4.0","NSMicrophoneUsageDescription":"An
application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the
user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundl
eIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","N
SDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application
in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a
network volume.","CFBundleGetInfoString":"Android Studio 4.0, build AI-193.6911.18.40.6626763. Copyright JetBrains s.r.o., (c)
2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a removable volume."}
[   +7 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +182 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +1 ms] executing: [/Users/chiuhol/hello_world/android/] /Users/chiuhol/hello_world/android/gradlew -Pverbose=true -Ptarget-platform=android-x64
-Ptarget=/Users/chiuhol/hello_world/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +880 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+9991 ms] > Task :app:compileFlutterBuildDebug
[        ] [ +126 ms] executing: [/Users/chiuhol/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[        ] [        ] executing: [/Users/chiuhol/flutter/] git tag --points-at HEAD
[        ] [  +97 ms] Exit code 0 from: git tag --points-at HEAD
[        ] [        ] 1.22.4
[   +1 ms] [   +9 ms] executing: [/Users/chiuhol/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/chiuhol/flutter/] git ls-remote --get-url origin
[        ] [  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +52 ms] executing: [/Users/chiuhol/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +10 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +17 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +67 ms] Initializing file store
[        ] [   +8 ms] Done initializing file store
[        ] [  +30 ms] Skipping target: gen_localizations
[        ] [ +512 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[        ] [  +22 ms] /Users/chiuhol/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/chiuhol/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/chiuhol/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --no-link-platform --packages /Users/chiuhol/hello_world/.packages --output-dill
/Users/chiuhol/hello_world/.dart_tool/flutter_build/a8d453f737cf899cab25843d54be2719/app.dill --depfile
/Users/chiuhol/hello_world/.dart_tool/flutter_build/a8d453f737cf899cab25843d54be2719/kernel_snapshot.d package:hello_world/main.dart
[+5766 ms] [+6319 ms] kernel_snapshot: Complete
[ +600 ms] [ +562 ms] Skipping target: debug_android_application
[        ] [        ] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 7,575ms.
[        ] [   +3 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +300 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +397 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +100 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[ +299 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +100 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +103 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +97 ms] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[  +96 ms] > Task :app:assembleDebug
[  +50 ms] BUILD SUCCESSFUL in 18s
[        ] 31 actionable tasks: 5 executed, 26 up-to-date
[ +364 ms] Running Gradle task 'assembleDebug'... (completed in 19.4s)
[  +30 ms] calculateSha: LocalDirectory: '/Users/chiuhol/hello_world/build/app/outputs/flutter-apk'/app.apk
[  +17 ms] calculateSha: reading file took 17us
[ +417 ms] calculateSha: computing sha took 416us
[   +3 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +3 ms] executing: /Users/chiuhol/Library/Android/sdk/build-tools/30.0.1/aapt dump xmltree /Users/chiuhol/hello_world/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[  +17 ms] Exit code 0 from: /Users/chiuhol/Library/Android/sdk/build-tools/30.0.1/aapt dump xmltree /Users/chiuhol/hello_world/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.example.hello_world" (Raw: "com.example.hello_world")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello_world" (Raw: "hello_world")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello_world.MainActivity" (Raw: "com.example.hello_world.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +11 ms] Stopping app 'app.apk' on Android SDK built for x86 64.
[        ] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell am force-stop com.example.hello_world
[ +224 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell pm list packages com.example.hello_world
[ +307 ms] package:com.example.hello_world
[   +2 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell cat /data/local/tmp/sky.com.example.hello_world.sha1
[  +38 ms] c1f35b1701cd5ec58b51fad7dc5d9954b044107c
[        ] Latest build already installed.
[        ] Android SDK built for x86 64 startApp
[   +3 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.hello_world/com.example.hello_world.MainActivity
[ +110 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hello_world/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+3738 ms] Observatory URL on device: http://127.0.0.1:41506/SS8h2yI-zsE=/
[   +1 ms] executing: /Users/chiuhol/Library/Android/sdk/platform-tools/adb -s emulator-5556 forward tcp:0 tcp:41506
[  +25 ms] 59309
[        ] Forwarded host port 59309 to device port 41506 for Observatory
[   +3 ms] Caching compiled dill
[  +80 ms] Connecting to service protocol: http://127.0.0.1:59309/SS8h2yI-zsE=/
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[ +401 ms] Successfully connected to service protocol: http://127.0.0.1:59309/SS8h2yI-zsE=/
[        ] Waiting for Android SDK built for x86 64 to report its views...
[   +6 ms] Waiting for Android SDK built for x86 64 to report its views... (completed in 5ms)
[  +37 ms] DevFS: Creating new filesystem on the device (null)
[  +37 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.hello_world/code_cache/hello_worldJXMAGW/hello_world/)
[   +2 ms] Updating assets
[ +118 ms] Syncing files to device Android SDK built for x86 64...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:hello_world/main.dart 2cdd4da0-b289-437b-8e30-d1655482803e
[        ] <- 2cdd4da0-b289-437b-8e30-d1655482803e
[ +139 ms] Updating files
[ +290 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86 64... (completed in 434ms)
[        ] Synced 1.8MB.
[        ] <- accept
[  +23 ms] Connected to _flutterView/0x73d8e49ee020.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Android SDK built for x86 64 is available at: http://127.0.0.1:59309/SS8h2yI-zsE=/
[ +297 ms] I/Choreographer(26403): Skipped 98 frames!  The application may be doing too much work on its main thread.
[  +35 ms] D/EGL_emulation(26403): eglMakeCurrent: 0x73d8e7c50ae0: ver 3 0 (tinfo 0x73d8e7d9e440)
[  +32 ms] D/eglCodecCommon(26403): setVertexArrayObject: set vao to 0 (0) 1 2
[ +157 ms] I/OpenGLRenderer(26403): Davey! duration=1888ms; Flags=1, IntendedVsync=287004311959379, Vsync=287005945292647, OldestInputEvent=9223372036854775807,
NewestInputEvent=0, HandleInputStart=287005960579591, AnimationStart=287005960632591, PerformTraversalsStart=287005960654591, DrawStart=287006008825591,
SyncQueued=287006012778591, SyncStart=287006014158591, IssueDrawCommandsStart=287006047344591, SwapBuffers=287006122257591, FrameCompleted=287006201589591,
DequeueBufferDuration=25507000, QueueBufferDuration=2502000, 
[ +678 ms] D/EGL_emulation(26403): eglMakeCurrent: 0x73d8e62f7680: ver 3 0 (tinfo 0x73d8e7c0dce0)
[  +34 ms] D/eglCodecCommon(26403): setVertexArrayObject: set vao to 0 (0) 1 0`

**Comment by chiuhol** [comment]
Hi @TahaTesser
That's what i mean
My device is Pixel 3 XL API 28(android-x64 emulator)
Here is flutter run --verbose [https://gist.github.com/chiuhol/069d00d352a9a05aa52c79ab147d0237](url)

**Comment by TahaTesser** [comment]
Hi @chiuhol 
I can reproduce the issue on multiple Android emulators running Android 10 and Android 8,

I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/59552
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by chiuhol** [comment]
HI @TahaTesser 
ok,thanks for your help!
