### ISSUE TITLE
 Build layout website page is 404

### ISSUE THREAD

**Issue by liushengqiangGitHub** [flutter/flutter#70753]
From URL: https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/main.dart

示例代码404了.

**Comment by TahaTesser** [comment]
Hi @liushengqiangGitHub 
Can you please provide the source of this link? Where did you find this link? 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
