### ISSUE TITLE
Fix flutter_gallery_ios__start_up on iOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7075]
We're missing timeline events for this test. A fix for this test will also likely fix `complex_layout_ios__start_up` as well.

Test code: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_gallery_ios__start_up.dart

https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/complex_layout_ios__start_up.dart

**Comment by cbracken** [comment]
@yjbanov fixed now?

**Comment by yjbanov** [comment]
Yep.
