### ISSUE TITLE
Fix complex_layout_scroll_perf_ios__timeline_summary on iOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7076]
For some reason this test is looking for `adb`.

Test code: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/complex_layout_scroll_perf_ios__timeline_summary.dart

**Comment by eseidelGoogle** [comment]
Do we have a verbose log which might tell us what adb command it's trying to run?

**Comment by yjbanov** [comment]
I found the issue. It's a misconfigured mac mini. I'll fix it.

**Comment by eseidelGoogle** [comment]
@yjbanov does this mean that our Mac bots will soon turn green?  Or was this just part of the problem?

**Comment by yjbanov** [comment]
This particular test should go green. I logged separate issues for the start-up tests.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/7132. It's green now.
