### ISSUE TITLE
[Image_picker] Constant Resetting on Samsung Tab A

### ISSUE THREAD

**Issue by Rossdex** [flutter/flutter#70762]
I am getting constant crashes on the app I am developing when using the image_picker so rather than looking into if any other plugins were clashing with this one I used the example app on the image_picker plugin. 

This happens constantly on my Samsung Tab A. 

Unfortunately the "Handling MainActivity destruction on Android" will not work for my app as the end user is required to login before they are able to take pictures so I cannot rescue the lost image. You also state that this is a **very rare** occurrence but I am experiencing this constantly as are many of my end users. 

## Steps to Reproduce

1. Run the image_picker example app
2. Select image picker camera
3. Repeat until the app crashes (I have crashes after 3-4 photos)

**Expected results:** Photo is viewable

**Actual results:** App resets to the default page (no crash log). 

**Flutter Version:**
Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.630], locale en-GB)

• Flutter version 1.22.3 at C:\src\flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

**Comment by TahaTesser** [comment]
Hi @Rossdex 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/70751
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
