### ISSUE TITLE
ScrollController attached to multiple scroll views. 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12: '_positions.length == 1'

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#70764]
`When` I used the component listview in flutter to nest the listview and set the scroll listener for the listview, the following error was reported: ScrollController attached to multiple scroll views.

'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 111 pos 12:'_positions.length == 1'

My code 
```

`class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;


  ScrollController scrollController= new ScrollController();
  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    scrollController.addListener(() {
      var index=scrollController.offset;
      print("这个数是输出的$index");
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: ListView.builder(itemBuilder: (BuildContext context,int index){
        return  ItemWidget();


      },itemCount: 30,
      controller: scrollController,
    ),



      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Widget ItemWidget(){

    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5),
        //color: Colors.pinkAccent,
      ),
      height: 90,
      width: MediaQuery.of(context).size.width,
      child: Stack(
        children: <Widget>[
          Positioned(
            top: 0,
            left: 2,
            child: Text('标题',style: TextStyle(color: Colors.pinkAccent),),
          ),
          Positioned(
            top: 15,
            left: 2,
            child: Container(
              height: 45,
              width: MediaQuery.of(context).size.width,
              child: ListView.builder(
                controller: scrollController,
                  scrollDirection:Axis.horizontal,
                  itemCount: 10,itemBuilder: (BuildContext context,int index){
                return Container(
                  height: 40,
                  width: 40,
                  margin: EdgeInsets.all(5),
                  color: Colors.blue,
                );
              }),
            )

          ),
          Positioned(
            top: 70,
            left: 5,
            child: Text('稀释舒克舒克快速开始可快速开始'),
          ),

        ],
      ),
    );
  }
}`

```

My environment

[✓] Flutter (Channel stable, v1.17.3, on macOS 11.0.1 20B29, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/hyplo/Downloads/flutter
    • Framework revision b041144f83 (6 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/hyplo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 12 Pro Max • 04047B89-E391-4D7C-B35B-491A6C13AE66 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

**Comment by pedromassangocode** [comment]
Hi @haibowen 
Looks like you are using a too old version of Flutter.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v`.

**Comment by haibowen** [comment]
> Hi @haibowen
> Looks like you are using a too old version of Flutter.
> Can you please upgrade to the latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the issue persists, please provide your `flutter doctor -v`.


Hi @pedromassangocode 
I tried to follow the above steps and the problem still exists

My environment

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Comment by pedromassangocode** [comment]
Hi @haibowen 
Can you please edit the code you provide to make it complete? I should be able to reproduce the issue by just copy/pasting the code above.
Thank you

**Comment by haibowen** [comment]
> Hi @haibowen
> Can you please edit the code you provide to make it complete? I should be able to reproduce the issue by just copy/pasting the code above.
> Thank you

Hi @pedromassangocode 

this is my code
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ScrollController scrollController = new ScrollController();

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    scrollController.addListener(() {
      var index = scrollController.offset;
      print("这个数是输出的$index");
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemBuilder: (BuildContext context, int index) {
          return ItemWidget();
        },
        itemCount: 30,
      ),

      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Widget ItemWidget() {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5),
        //color: Colors.pinkAccent,
      ),
      height: 90,
      width: MediaQuery.of(context).size.width,
      child: Stack(
        children: <Widget>[
          Positioned(
            top: 0,
            left: 2,
            child: Text(
              '标题',
              style: TextStyle(color: Colors.pinkAccent),
            ),
          ),
          Positioned(
              top: 15,
              left: 2,
              child: Container(
                  height: 45,
                  width: MediaQuery.of(context).size.width,
                  child: ListView.builder(
                      controller: scrollController,
                      scrollDirection: Axis.horizontal,
                      itemCount: 10,
                      itemBuilder: (BuildContext context, int index) {
                        return Container(
                          height: 40,
                          width: 40,
                          margin: EdgeInsets.all(5),
                          color: Colors.blue,
                        );
                      }),
              )),
          Positioned(
            top: 70,
            left: 5,
            child: Text('稀释舒克舒克快速开始可快速开始'),
          ),
        ],
      ),
    );
  }
}
`

**Comment by haibowen** [comment]
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ScrollController scrollController = new ScrollController();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    scrollController.addListener(() {
      var index = scrollController.offset;
      print("这个数是输出的$index");
    });
  }

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemBuilder: (BuildContext context, int index) {
          return ItemWidget();
        },
        itemCount: 30,
      ),

      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Widget ItemWidget() {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5),
        //color: Colors.pinkAccent,
      ),
      height: 90,
      width: MediaQuery.of(context).size.width,
      child: Stack(
        children: <Widget>[
          Positioned(
            top: 0,
            left: 2,
            child: Text(
              '标题',
              style: TextStyle(color: Colors.pinkAccent),
            ),
          ),
          Positioned(
              top: 15,
              left: 2,
              child: Container(
                  height: 45,
                  width: MediaQuery.of(context).size.width,
                  child: ListView.builder(
                      controller: scrollController,
                      scrollDirection: Axis.horizontal,
                      itemCount: 10,
                      itemBuilder: (BuildContext context, int index) {
                        return Container(
                          height: 40,
                          width: 40,
                          margin: EdgeInsets.all(5),
                          color: Colors.blue,
                        );
                      }),
              )),
          Positioned(
            top: 70,
            left: 5,
            child: Text('稀释舒克舒克快速开始可快速开始'),
          ),
        ],
      ),
    );
  }
}
`

**Comment by pedromassangocode** [comment]
Hi @haibowen 
This error is expected because you are using the same scroll controller for multiple ListViews and this is not accepted. Make sure each Item has its own controller.
