### ISSUE TITLE
Execution failed for task ':video_player:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by AyaFathy577** [flutter/flutter#70761]
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
C:\Users\xxx\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:10: error: cannot find symbol
import io.flutter.FlutterInjector;
                 ^
  symbol:   class FlutterInjector
  location: package io.flutter
C:\Users\xxx\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
    final FlutterInjector injector = FlutterInjector.instance();
          ^
  symbol:   class FlutterInjector
  location: class VideoPlayerPlugin
C:\Users\xxx\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-1.0.1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
    final FlutterInjector injector = FlutterInjector.instance();
                                     ^
  symbol:   variable FlutterInjector
  location: class VideoPlayerPlugin
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_player:compileDebugJavaWithJavac'.

//////////////// flutter doctor //////////////////////////
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.630], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

**Comment by sidrao2006** [comment]
Hello @AyaFathy577 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by pedromassangocode** [comment]
Hi @AyaFathy577 
It seems you are using a really old version of Flutter,
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists please provide your `flutter doctor -v`.

**Comment by AyaFathy577** [comment]
Hi @pedromassangocode 
I need to use this version because I used plugin that work on it.
can I use old version of vedio_player ?

**Comment by AyaFathy577** [comment]
Thanks @pedromassangocode 
it runs when using video_player: 0.11.0
