### ISSUE TITLE
package:flutter/src/widgets/framework.dart': Failed assertion: line 5022 pos 16: 'child is! ParentDataElement<ParentData>': is not true

### ISSUE THREAD

**Issue by bogdy9912** [flutter/flutter#70769]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
Scaffold
lib\screens\auth_screen.dart:28
When the exception was thrown, this was the stack
#2      ParentDataElement._applyParentData.applyParentDataToChild
package:flutter/…/widgets/framework.dart:5022
#3      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4681
#4      ParentDataElement._applyParentData
package:flutter/…/widgets/framework.dart:5026
#5      ParentDataElement.notifyClients
package:flutter/…/widgets/framework.dart:5070
#6      ProxyElement.updated
package:flutter/…/widgets/framework.dart:4997
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Incorrect use of ParentDataWidget.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
Scaffold
lib\screens\auth_screen.dart:28
════════════════════════════════════════════════════════════════════════════════

**Comment by sidrao2006** [comment]
Hello @bogdy9912 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by pedromassangocode** [comment]
Hi @bogdy9912 
Please provide what was asked above.

**Comment by bogdy9912** [comment]
Sorry but I already solve the problem and I don't really remember the code. The problem appeared when I used PageView inside Stack. Next time I will provide the complete information about the issue.

**Comment by wangshunji** [comment]
我也遇到了同样的问题 

════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (11690): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5022 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
E/flutter (11690): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (11690): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (11690): #2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5022:16)
E/flutter (11690): #3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
E/flutter (11690): #4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5023:15)
E/flutter (11690): #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
E/flutter (11690): #6      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5026:5)
E/flutter (11690): #7      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5070:5)
E/flutter (11690): #8      ProxyElement.updated (package:flutter/src/widgets/framework.dart:4997:5)
E/flutter (11690): #9      ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
E/flutter (11690): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter (11690): #12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter (11690): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter (11690): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (11690): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (11690): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter (11690): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (11690): #21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (11690): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (11690): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter (11690): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter (11690): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (11690): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (11690): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter (11690): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter (11690): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (11690): #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (11690): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (11690): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter (11690): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (11690): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (11690): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (11690): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter (11690): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter (11690): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:1
I/flutter (11690): push后,显示的页面 ExceptionPageState

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building DefaultTextStyle(debugLabel: (dense body1 2014).merge(blackMountainView bodyText2), inherit: false, color: Color(0xdd000000), family: Roboto, size: 15.0, weight: 400, baseline: ideographic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5022 pos 16: 'child is! ParentDataElement<ParentData>': is not true.
