### ISSUE TITLE
What is onAppPrivateCommand?

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#70777]
I have no idea what this does: 

https://api.flutter.dev/flutter/widgets/EditableText/onAppPrivateCommand.html

The docs should explain it.

**Comment by RivaanRanawat** [comment]
I think this command is similar to the command in Android Development as well.

Make sure to check these links:
https://developer.android.com/reference/android/media/tv/TvInputService.Session#onAppPrivateCommand(java.lang.String,%20android.os.Bundle)
https://api.flutter.dev/flutter/widgets/EditableText/onAppPrivateCommand.html

**Comment by marcglasberg** [comment]
@RivaanRanawat Thanks for the link. Now I know it has something to do with TVs, and probably of no use to me at the moment. But still I think it merits more documentation. That link also doesn't explain much.

**Comment by LongCatIsLooong** [comment]
You can find updated (and more detailed) docs here: https://master-api.flutter.dev/flutter/widgets/EditableText/onAppPrivateCommand.html (except that a few hyperlinks are not working).
