### ISSUE TITLE
Worked great on macOS Big Sur. Thank you for the fix

### ISSUE THREAD

**Issue by ChristianMocha** [flutter/flutter#70778]
@yuesaka FWIW, I had the same issue and downgrading to `1.7.5` worked for me too.  Thanks for suggesting the workaround.  `sudo gem install cocoapods` without specifying a version ends up installing version `1.8.0` and subsequently running `pod setup` ended up installing nothing.

_Originally posted by @c-p-i-o in https://github.com/flutter/flutter/issues/41291#issuecomment-535216215_

**Comment by sidrao2006** [comment]
Hey @ChristianMocha ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please close this issue or please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?

Thank you!
