### ISSUE TITLE
Re-enable codesigning bot

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#70779]
Codesigning bot was taken offline, this affects releases.

**Comment by pcsosinski** [comment]
marking as P1 - our ability to release is impacted

**Comment by godofredoc** [comment]
This is a blocker for the next two weeks.

**Comment by christopherfujino** [comment]
Upgrading this to p0, as we currently are unable to codesign releases.

**Comment by christopherfujino** [comment]
Resolved!
