### ISSUE TITLE
Add to Navigator's pushNamed fullscreenDialog param

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#70784]
## Use case
When you use only named routes in your app, sometimes you need to puh the next page as a fullscreenDialog. Ordinary Navigator.push() has this option, but Navigator.pushNamed() doesn't.

## Proposal
Add the same params to Navigator.pushNamed() as for Navigator.push()

**Comment by TahaTesser** [comment]
Hi @alectogeek 
Can you please provide details on how would work if implemented? Inside ` Navigator.push()` can take widget but how would pass fullscreenDialog to Navigator.pushNamed()? 
Thank you

**Comment by RivaanRanawat** [comment]
Please check this out: https://stackoverflow.com/questions/53304340/navigator-pass-arguments-with-pushnamed

**Comment by RivaanRanawat** [comment]
Please check this out: https://stackoverflow.com/questions/53304340/navigator-pass-arguments-with-pushnamed

**Comment by alectogeek** [comment]
@TahaTesser 
This is an example of `push()` method:
```
  Navigator.push(
      context,
      CupertinoPageRoute<bool>(
        builder: (context) => SomePage(),
        fullscreenDialog: true,
      ));
```
So I expected that `pushNamed()` would provide something like:
```
Navigator.pushNamed(
      context,
      '/some-route'
    fullscreenDialog: true,
  );
```

I understand that `push()` takes the `CupertinoPageRoute` object and `fullScreenDialod` is specified there but it would be great to be able to specify in `pushNamed` this param as well, if possible.

**Comment by alectogeek** [comment]
> Please check this out: https://stackoverflow.com/questions/53304340/navigator-pass-arguments-with-pushnamed

@RivaanRanawat yep, I did something similar for my case and it worked well.

**Comment by hello-addweb** [comment]
```
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
),
initialRoute: '/',
onGenerateRoute: (RouteSettings settings) {
switch (settings.name) {
case "/":
return MaterialPageRoute(
builder: (context) => MyHomePage(
title: "Demo",
));
case "/dialog":
return MaterialPageRoute(
builder: (context) => YourDialog(), fullscreenDialog: true);
}
});
}

Navigator.pushNamed(context, '/dialog');
```

**Comment by alectogeek** [comment]
@hello-addweb ok
