### ISSUE TITLE
Enable  "Dart", "Embedder", and "GC" Timeline streams by default when running a Flutter app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#70794]
An important profiling use case is tracing app start. In order to use Dart DevTools to visualize Timeline trace from the start of an application, the proper Timeline recording streams need to be set before Dart DevTools connect. DevTools manually sets the "Dart", "Embedder", and "GC" timeline flags when connecting to an app, but this only guarantees that events on these streams will be recorded after DevTools has set those flags.

Even outside of the startup case, having these streams enabled before connecting to tools like DevTools is important so that a user can see a performance problem in their app and immediately open DevTools to analyze the issue. Without the flags set by default, the user would open DevTools, expecting recent app activity to be loaded and ready to analyze, but see nothing. This makes it seem like the tooling is broken, when in reality, it is an issue with the availability of data.

cc @zanderso @rmacnak-google @jonahwilliams @liyuqian

**Comment by kenzieschmoll** [comment]
Copying some info from offline thread.

@jonahwilliams:
> It looks like those flags are only set when --trace-startup is set?
> https://github.com/flutter/engine/blame/e78e405e6a2fcb79956280be019e916a12a8de05/runtime/dart_vm.cc#L376

@jason-simmons:
> "flutter run --trace-startup" will enable various timeline streams, collect performance metrics during startup, and then exit the tool.  You can see the accumulated timeline data by running "flutter attach" after it exits and using the observatory.
> 
> I vaguely recall that some of the timeline streams used to be recorded by default in old versions of the engine.  I tried to verify this but it looks like old builds of the observatory are not compatible with current versions of Chrome.
> 
> If users need timeline recording from the start of the app, then we could expose the Dart VM --timeline_streams flag in the engine and tools.

@jonahwilliams:
> I don't really understand why they aren't enabled in the first place. Turning these streams on does not have the memory implications that something like --endless-trace-buffer does right?

@zanderso:
> IIRC, the VM buffers for the non-endless timeline are allocated lazily, and are in the 10s of MBs. I'd be reluctant to hardcode in the engine the up-font allocation of these buffers, but if this is something that an engine embedder (think small Fuchsia/CastOS devices, etc.) can configure, then I think it would be okay for the default on desktop, iOS, and Android to be to start with tracing enabled.

@rmacnak-google:
> All of the timeline recorders have negligible memory usage until events are recorded. (The fixed-size recorders are allocated up front, but this is direct virtual memory that isn't explicitly initialized, so it doesn't get backed by memory until events are recorded or the timeline is queried.) Which categories/streams are recorded at startup is a policy question for the embedder. 
> 
> I find it confusing that `flutter run --trace-startup` automatically kills the application instead of merely enabling streams and choosing the startup recorder.

@liyuqian:

> Agree that `--trace-startup` is very confusing. See https://github.com/flutter/flutter/issues/64781#issuecomment-686089179 and https://github.com/flutter/flutter/issues/58869.
> 
> For the missing tracing events during startup, I wonder if it's related to "Fix timeline events lost before dart init https://github.com/flutter/engine/pull/18027"

**Comment by zanderso** [comment]
From the discussion it sounds like enabling these streams by default should be low overhead. @chinmaygarde do you have any concerns with this? @liyuqian Do we have any memory footprint benchmarks that would be able to surface any issues with this change?

**Comment by kenzieschmoll** [comment]
Any update on this issue? The "missing" timeline events when a user opens DevTools came up again in a user study. Can we get this fixed soon?

**Comment by zanderso** [comment]
We're unlikely to be able to look at this until next month.

**Comment by jonahwilliams** [comment]
drive by comment, we could get 80% of this by making all of the device class just pass --trace-startup by default and ignoring the command line flag, which has additional complicated behavior

**Comment by kenzieschmoll** [comment]
> drive by comment, we could get 80% of this by making all of the device class just pass --trace-startup by default and ignoring the command line flag, which has additional complicated behavior

I tried the workflow of running "flutter run --trace-startup", followed by "flutter attach", and I was able to open both Observatory and DevTools with the connected app. The timeline streams are still not enabled though.

**Comment by jonahwilliams** [comment]
Interesting! as far as I could tell that flag would enable them, so there might be something more going on

**Comment by cobblest** [comment]
We observed this as one of the big pain points of UI perf debugging process as well [Link](https://docs.google.com/presentation/d/19PAAeBjXqXKxP1OpyHCq72Z9B2SIpctpPFBZ7KpOGlU/edit?resourcekey=0-GNMH_FHchg68YfpiXMWgBg#slide=id.g89bb417694_0_175)

- Many noted that it was hard to correlate actions, UI jank, and Timeline events because there is a delay between the UI jank and refreshing the Timeline page. Thus it was easy to miss UI jank issues on the Timeline event chart. 
- The timeline chart on the Timeline page, performance overlay, and IDE frame rendering chart were also inconsistent.
- Participants hoped Timeline could be more automatic and continuous running, just like the IDE plugin performance tools.

**Comment by zanderso** [comment]
This should be addressed after https://github.com/flutter/flutter/commit/2c23c6c217daf003e09e3dcae8b78cbbd65d4a1d. The engine commit for this https://github.com/flutter/engine/pull/23729 was flagged as causing a perf regression on Golem. I'll keep this open while I investigate that.

**Comment by zanderso** [comment]
The above engine change has rolled into the framework.
