### ISSUE TITLE
Builds failing randomly with missing ios 13.0 sdk

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#70793]
This seems like a test problem because the ios sdk shipped with the xcode version being used is 13.6.

Some examples:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863328391455486464/+/steps/run_test.dart_for_build_tests_shard_and_subshard_0/0/stdout#L23291_0
https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_gallery/521
https://chromium-swarm.appspot.com/task?id=4ff61307bb367510

**Comment by godofredoc** [comment]
\cc @dnfield

**Comment by jmagman** [comment]
`13.6` is not being passed in by Flutter tooling, it's what Xcode seems to think the SDK root is set to.  The tool is passing `-sdk iphoneos` to `xcodebuild` which just means "build against your iOS SDK", and Xcode is interpreting this as `iphoneos13.6`.

```
/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/opt/s/w/ir/k/flutter/dev/integration_tests/non_nullable/build/ios -sdk iphoneos ...

           Build settings from command line:
...
               SDKROOT = iphoneos13.6
```

You should be able to see what it thinks the default is by running `xcrun --show-sdk-path -sdk iphoneos`.

Total guess, but maybe the `select XCode` step needs additional setup? Does `sudo xcodebuild -runFirstLaunch` do anything (it will show a progress bar).

**Comment by godofredoc** [comment]
Found the issue, turns out this happens when a build times out while cleaning up:

This build polluted the xcode installation:

https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/5849?

Then the first build failing was:

https://chromium-swarm.appspot.com/task?id=4fedd1f9142ee910

**Comment by godofredoc** [comment]
This will be addressed creating our own packages for xcode.

**Comment by gw280** [comment]
Just happened again on the latest roll attempt: https://github.com/flutter/flutter/pull/72148

**Comment by godofredoc** [comment]
This is finally fixed by https://github.com/flutter/flutter/issues/72301. Please reopen if it happens again.
