### ISSUE TITLE
Define sufficient gallery performance testing strategy

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7079]
Define/ensure that our gallery performance is measured in a complete and sufficient way

/cc @sethladd

**Comment by sethladd** [comment]
Yay!

Framerates (gallery transitions, animations, motion)
Input latency (time between tap and callback in Dart code)
Cold Startup (to first interactible frame)
Constant-cost disk space (minimum cost for APK and uncompressed on disk)
Compiled size of Dart code for representative app (compressed, uncompressed)
Power Consumption (idle, animations)
Peak CPU performance (under stressful algorithm, ideally driving complex animations)

**Comment by yjbanov** [comment]
Cool! What should we do so that when we close this issue the definition is not lost?

**Comment by yjbanov** [comment]
Idea: go over https://github.com/flutter/flutter/projects/6 and ensure the list of issues fully covers this definition. When we fix all issues in that project, we'll consider ourselves as conforming to this definition.

**Comment by yjbanov** [comment]
It looks like we now have most of the metrics above and at least decent proxies for others (such as power consumption). Considering it done and closing.
