### ISSUE TITLE
Figure out what our lowest end devices should be

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7080]
We currently test on Nexus 5 and iPhone 6.

/cc @sethladd

**Comment by sethladd** [comment]
Asking inside of Google, I got a recommendation to test on a Moto G4.

Specs for a G4: http://www.devicespecifications.com/en/model/8afc3c08

G4 CPU: : 4x 1.5 GHz ARM Cortex-A53, 4x 1.2 GHz ARM Cortex-A53, 

A Xiomi Redmi 3S (http://www.gsmarena.com/xiaomi_redmi_3s-8150.php) was also recommended, which has a CPU of Octa-core 1.4 GHz Cortex-A53

Compare that to a Nexus 5, which seems to have a faster CPU. So I recommend we consider testing Flutter on a device with a less powerful CPU.

Specs for a Nexus 5: http://www.devicespecifications.com/en/model/3dfd2923
Nexus 5 CPU: : Krait 400, 2300 MHz, 4 cores

**Comment by sethladd** [comment]
Here are some more popular devices, across the globe:

Samsung Galaxy J2: ARM Cortex A7, 1300 MHz, 4 cores. GPU: ARM Mali-T720 MP1 533 MHz

Galaxy J5: Krait 400, 2500 Mhz, 4 cores. GPU: Adreno 330, 578 Mhz, 4 cores

Moto G (2nd edition): Cortex-A7, 1200 MHz, 4 cores. GPU: Adreno 305, 405 MHz, 1 core.

**Comment by sethladd** [comment]
Looks like we might want to consider how Flutter performs for the 1.5Ghz range of CPUs

**Comment by yjbanov** [comment]
We've successfully figured it out. Next step is to implement it, which is out of scope of this project. Closing.
