### ISSUE TITLE
Flutter detects move gesture slowly than android

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#70806]

**Comment by TahaTesser** [comment]
Hi @hamberluo 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by hamberluo** [comment]
Hi, @TahaTesser 

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-CN)
    • Flutter version 1.22.4
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

When you slow move on screen, compare flutter and android scroll behavior then you can get my point.

I think maybe the field `dragStartDistanceMotionThreshold` in `ScrollPhysics` is the root cause. But it doesn't work when override its value.

**Comment by TahaTesser** [comment]
Hi @hamberluo 
To better address the issue, Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by hamberluo** [comment]
Can developer customize
```dart
  @override
  bool _hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind) {
    return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
  }
```
to follow more quickly user's finger move event?
