### ISSUE TITLE
Failed to create platform view rendering surface

### ISSUE THREAD

**Issue by lj3069** [flutter/flutter#70811]
When I update flutter SDK from v1.12.13+hotfix.5 to v1.24.0-8.0.pre.My flutter app cannot work in iOS.
This is error log:

> 2020-11-19 10:45:49.927339+0800 Runner[355:22342] Metal GPU Frame Capture Enabled
2020-11-19 10:45:49.927614+0800 Runner[355:22342] Metal API Validation Enabled
2020-11-19 10:45:50.066676+0800 Runner[355:22342] [VERBOSE-2:platform_view.cc(81)] Failed to create platform view rendering surface
2020-11-19 10:45:50.103803+0800 Runner[355:22540] flutter: Observatory listening on http://127.0.0.1:52306/RAcRjVg3wOk=/

flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.252, on Mac OS X 10.15.6 19G73
    darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)
• No issues found!

**Comment by lj3069** [comment]
@xster Have you encountered this situation?

**Comment by xster** [comment]
What's the repro steps? You might have hit some transient issues on head since you're on master. @iskakaushik might know.

**Comment by lj3069** [comment]
> What's the repro steps? You might have hit some transient issues on head since you're on master. @iskakaushik might know.

I just upgraded the SDK according to the documentation and error prompts

**Comment by pedromassangocode** [comment]
Hi @lj3069 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
I would suggest you to try the `stable` channel as the master could be broken some times.

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by denes16** [comment]
I have the same problem on a M1 Macbook

**Comment by asdk2006** [comment]
I have the same problem on  Macbook pro i9

**Comment by denes16** [comment]
> I have the same problem on Macbook pro i9

I solved it downloading xcode 12 from the app store and not from the web page

**Comment by denes16** [comment]
> > I have the same problem on Macbook pro i9
> 
> I solved it downloading xcode 12 from the app store and not from the web page, note: firist delete the versions from the web

**Comment by asdk2006** [comment]
i have xcode 12.5 and work good on macbook pro i9 and i publish app to appstore they tell me there bug in ipad is 14.6 i install xcode 13 beta 2  from appstore and i have this problem [VERBOSE-2:platform_view.cc(87)] Failed to create platform view rendering surface
any sulotion
