### ISSUE TITLE
image_picker change png to jpg

### ISSUE THREAD

**Issue by joharputr** [flutter/flutter#70812]
when i upload file with .png extension , image_picker change to jpg 
![icon](https://user-images.githubusercontent.com/32647004/99620268-cc1e6f00-2a57-11eb-88a9-cdc006aa2f40.png)

**Comment by hello-addweb** [comment]
Please follow the answer from [same](https://github.com/flutter/flutter/issues/17947).

**Comment by pedromassangocode** [comment]
Hi @joharputr 
Are you facing this on iOS or Android?
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
