### ISSUE TITLE
A typo issue in section 8

### ISSUE THREAD

**Issue by damybe** [flutter/flutter#70827]
https://codelabs.developers.google.com/codelabs/flutter#7
The property name 'Duration' should be 'duration'. 
![image](https://user-images.githubusercontent.com/49179810/99654978-1ff17e00-2a81-11eb-8019-92f63940a2d9.png)

**Comment by pedromassangocode** [comment]
Hi @damybe 
I see there's an open issue (https://github.com/flutter/flutter/issues/64104) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
