### ISSUE TITLE
Allow usage of local config file for default values

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#70826]
Flutter uses a config file stored in the home directory to manage web, desktop support and other configurations.
However, a local config file which specifies the default values for commands is missing

This is useful while passing experiment flags or when using flavors

**Comment by pedromassangocode** [comment]
> However, a local config file which specifies the default values for commands is missing

Which commands? can you elaborate on that?

> This is useful while passing experiment flags or when using flavors

What are the drawbacks of the current implementation? Do you have any specific use-case?
Can you please elaborate on the whole proposal?
Thank you

**Comment by sidrao2006** [comment]
Arguments like `-v` or `--flavor` may have to be appended to every command.
Using a config file with the `verbose` arguments' value set to true and `flavor`'s value set to the default flavor.

### Drawbacks of current system

- Some arguments (as mentioned above) have to be passed with every command
- Some arguments could use a different default value
- Default values of all commands/arguments could be made more legible ( Currently, one has to search the command line docs )

**Comment by jonahwilliams** [comment]
This is not something we should do, if you are running with an IDE most already have launch configs. If you are running from the CLI, just write a little wrapper script.

**Comment by sidrao2006** [comment]
@jonahwilliams , however a config file file would by way easier to manage and display default values..making the tool more customizable
