### ISSUE TITLE
A typo in "Write Your First Flutter App, part 1 tutorial"

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#70822]
In the 5th part of "Write Your First Flutter App, part 1 tutorial" it says
"Once you've entered RandomWords as the name of the stateful widget, the IDE automatically updates the accompanying State class, naming it **_RandomWordState**. By default, the name of the State class is prefixed with an underscore. Prefixing an identifier with an underscore enforces privacy in the Dart language and is a recommended best practice for State objects."

However, it should be **_RandomWordsState** as it is plural. This is a pretty small mistake, but it confused me for a second. Just thought I might help out

**Comment by JuYeong0413** [comment]
similar issue: https://github.com/flutter/website/issues/4542

**Comment by pedromassangocode** [comment]
Cc @sfshaza2

**Comment by Roshan13046** [comment]
> For reference: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/index.html?index=..%2F..index#4
> Cc @sfshaza2

I would like to work on it.
Where can I find its source code?

**Comment by JuYeong0413** [comment]
@Roshan13046 The codelabs source are not accessible to non-Googlers.

**Comment by Roshan13046** [comment]
> @Roshan13046 The codelabs source are not accessible to non-Googlers.

Thanks! for the quick reply.

**Comment by Abhishek01039** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
I've changed `_RandomWordState` to `_RandomWordsState` in the source doc. Once @sfshaza2 lgtm's the change, it'll be up on the site.

**Comment by domesticmouse** [comment]
Thanks for the heads up @Abhishek01039 =)

**Comment by Abhishek01039** [comment]
Thanks @domesticmouse for looking at this issue.

**Comment by domesticmouse** [comment]
Keeping everything updated is an ongoing task, thanks for keeping us honest =)
