### ISSUE TITLE
Error: No 'main' method found in plugin package

### ISSUE THREAD

**Issue by tan-yaka** [flutter/flutter#70830]
I'm trying to build an app that uses a plugin hosted locally. When building the app I get the following:
```
tanyaka@Tans-MBP exalt-flutter-app % flutter build apk -t lib/main_local.dart --debug
Error: Error when reading 'lib/main_local.dart': No such file or directory
package:my_plugin/main_local.dart: Error: No 'main' method found.
```
I don't understand why the compiler is looking for `main_local.dart` in my plugin?

In pubspec.yaml:
```
  my_plugin:
    path: ../../../my_plugin/
```
No issues with `flutter doctor`

If I remove all references to the plugin the app builds ok.

**Comment by pedromassangocode** [comment]
The `-t` argument is used to provide the main entry-point file of  the application, as run on the device. The main entry-point is always expected to have a main function which will be used as the main entry-point.
