### ISSUE TITLE
tiles_scroll_perf_ios__timeline_summary, run_smoke_catalina_start_up_ios fails on devicelab with iOS 14

### ISSUE THREAD

**Issue by xster** [flutter/flutter#70869]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863190037146164880/+/steps/run_tiles_scroll_perf_ios__timeline_summary/0/stdout

```
------ Debug phase ------
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] Starting debug of 4e131215b69d6679703d698c2418e1e3ddcdf8c6 (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [ +227 ms] [  0%] Looking up developer disk image
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [  +12 ms] [ 95%] Developer disk image mounted successfully
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [ +575 ms] [100%] Connecting to remote debug server
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] -------------------------
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [  +82 ms] (lldb) command source -s 0 '/tmp/8FA4CF1A-CF39-467C-B286-CEEE0573B1DF/fruitstrap-lldb-prep-cmds-4e131215b69d6679703d698c2418e1e3ddcdf8c6'
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] Executing commands in '/tmp/8FA4CF1A-CF39-467C-B286-CEEE0573B1DF/fruitstrap-lldb-prep-cmds-4e131215b69d6679703d698c2418e1e3ddcdf8c6'.
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     platform select remote-ios --sysroot '/Users/swarming/Library/Developer/Xcode/iOS DeviceSupport/14.1 (18A8395)/Symbols'
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   Platform: remote-ios
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]  Connected: no
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   SDK Path: "/Users/swarming/Library/Developer/Xcode/iOS DeviceSupport/14.1 (18A8395)/Symbols"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     target create "/opt/s/w/ir/k/flutter/dev/benchmarks/complex_layout/build/ios/iphoneos/Runner.app"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [ +134 ms] Current executable set to '/opt/s/w/ir/k/flutter/dev/benchmarks/complex_layout/build/ios/iphoneos/Runner.app' (arm64).
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/3228A605-4F95-48AD-9780-CA24ED478A14/Runner.app"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [ +299 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:49960"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     script fruitstrap_output_path=""
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     script fruitstrap_error_path=""
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     target modules search-paths add /usr "/Users/swarming/Library/Developer/Xcode/iOS DeviceSupport/14.1 (18A8395)/Symbols/usr" /System "/Users/swarming/Library/Developer/Xcode/iOS DeviceSupport/14.1 (18A8395)/Symbols/System" "/private/var/containers/Bundle/Application/3228A605-4F95-48AD-9780-CA24ED478A14" "/opt/s/w/ir/k/flutter/dev/benchmarks/complex_layout/build/ios/iphoneos" "/var/containers/Bundle/Application/3228A605-4F95-48AD-9780-CA24ED478A14" "/opt/s/w/ir/k/flutter/dev/benchmarks/complex_layout/build/ios/iphoneos" /Developer "/Users/swarming/Library/Developer/Xcode/iOS DeviceSupport/14.1 (18A8395)/Symbols/Developer"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +6 ms] (lldb)     command script import "/tmp/8FA4CF1A-CF39-467C-B286-CEEE0573B1DF/fruitstrap_4e131215b69d6679703d698c2418e1e3ddcdf8c6.py"
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +3 ms] (lldb)     command script add -f fruitstrap_4e131215b69d6679703d698c2418e1e3ddcdf8c6.connect_command connect
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_4e131215b69d6679703d698c2418e1e3ddcdf8c6.run_command run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_4e131215b69d6679703d698c2418e1e3ddcdf8c6.autoexit_command autoexit
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_4e131215b69d6679703d698c2418e1e3ddcdf8c6.safequit_command safequit
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] (lldb)     connect
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [  +77 ms] (lldb)     run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [+40052 ms] error: timed out waiting for app to launch
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [        ] Could not run build/ios/iphoneos/Runner.app on 4e131215b69d6679703d698c2418e1e3ddcdf8c6.
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [        ]   open ios/Runner.xcworkspace
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ] Installing and launching... (completed in 43.9s)
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [        ] Application failed to start on attempt: 2
``` 

Though I couldn't reproduce locally.

**Comment by xster** [comment]
The top level command that failed was 
`script -t 0 /dev/null /opt/s/w/ir/k/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 4e131215b69d6679703d698c2418e1e3ddcdf8c6 --bundle build/ios/iphoneos/Runner.app --debug --no-wifi --args --enable-dart-profiling --disable-service-auth-codes --disable-observatory-publication --start-paused --enable-checked-mode --verify-entry-points --verbose-logging --trace-startup
`

**Comment by xster** [comment]
ios-deploy failing at that stage could be a provisioning issue. Looks like we're using the fastlane match mechanism for this test.

**Comment by xster** [comment]
@godofredoc can you point me to match bits for this recipe? https://ci.chromium.org/p/flutter/builders/prod/Mac%20tiles_scroll_perf_ios__timeline_summary/42 is this run. I didn't see a step for getting the provisioning profiles. Looking at the gem install step, I didn't see fastlane being installed either. (or maybe was it in the image and not installed via gems?)

**Comment by godofredoc** [comment]
You can click on the recipes link it is now working:

![image](https://user-images.githubusercontent.com/54371434/99727340-a64f9500-2a6c-11eb-94af-e118fc85bca1.png)

If we need fastlane then we need to install it either using cipd or as part of the gems files in flutter. The assumption for LUCI bots is that they only have the OS, secrets and certificates. Everything else will be provided at runtime.

**Comment by godofredoc** [comment]
If it can be installed via gems maybe we can add it here:

https://cs.opensource.google/flutter/flutter/+/master:dev/ci/mac/Gemfile;l=1

No other changes will be needed, certificate provisioning is already handled by the bot provisioning automation.

**Comment by xster** [comment]
Can you point me to where the other non-xcode 12 builders are installing fastlane and calling match? That's what we need to replicate here. 

Unfortunate that the xcode builds here are referencing the match installed provisioning profiles and there's no errors from xcode...

**Comment by godofredoc** [comment]
Which command I need to look for? I took a quick look and we are not doing anything special in the agent for this test.

**Comment by xster** [comment]
It would be a call to something like cl/313648878. I don't remember why I updated the doc. Might be during the LUCI migration. @keyonghan was involved in setting up the new signing I think. 

If it's not sync'ed during the run, the provisioning profiles might have been baked into the images under `~/Library/MobileDevice/Provisioning Profiles` somewhere. It would have been slightly unexpected but possible.

**Comment by godofredoc** [comment]
I took a look and the provisioning profiles are created at bot provisioning time http://fxb/64916. At runtime we pass manual provisioning with the environment variables https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/flutter_deps/api.py;l=348

**Comment by xster** [comment]
That actually looks reasonable (it expires in a week but still right currently). 2 questions: 

1. I didn't see the accompanying certificate in the same folder. How is that installed?
2. Did we specifically add the provisioned devices to our account for the devices that are connected to the new agents? (you can see a list of device IDs by pressing cmd-I on the mobileprovision file. i.e. did we ever try to run any apps on them through Xcode?

**Comment by godofredoc** [comment]
1) yes the certificate is called development.p12 and the development.mobileprovision contains the uuid of the connected phone.
2) yes, the phone for mac-9 is in the list.

**Comment by xster** [comment]
Connected and manually trying 1.24.0-8.0.pre.361 on mac-9. The signing was indeed fine. 

Turns out even Xcode can't handle it :) 

```
Details

Could not launch “Runner”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: timed out waiting for app to launch
User Info: {
    DVTRadarComponentKey = 855031;
    RawLLDBErrorMessage = "timed out waiting for app to launch";
}
--


System Information

macOS Version 10.15.7 (Build 19H2)
Xcode 12.1 (17222)
```

The connected phone was stuck with:

![Screen Shot 2020-11-24 at 9 23 50 PM](https://user-images.githubusercontent.com/156888/100186701-5cffab00-2e9b-11eb-82ee-3bbbbf84af2c.png)

Seems like this state was more potent than expected. Even deleting all the Flutter apps on the phone from the host doesn't dismiss the dialog. @jmagman 

Do we have provisions for phones being stuck like these? I remember someone saying there was a script to tap dialog buttons? Also, did we enroll these devices to MDM to remote reboot? I took a look at Apple Configurator 2 but as far as I can tell, it ends up enrolling it into MDM too to use "advanced" features like reboot?

**Comment by xster** [comment]
aha! https://apple.stackexchange.com/questions/150880/any-way-to-reboot-a-idevice-that-is-connected-to-a-usb-port-via-terminal-mac-te

libimobiledevice to the rescue

**Comment by xster** [comment]
I think the takeaway is that we must avoid running anything that doesn't go through https://github.com/flutter/flutter/pull/67452 on those mac bots. 

_Maybe_ we should also just always run `idevicediagnostics restart` as the last step on the recipe. Just to seal the deal. 

Unrelated: I'm now running into this issue on the device. Last failing step is 

`/Users/flutter/manual_testing_remove_me/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --verbose --id 4e131215b69d6679703d698c2418e1e3ddcdf8c6 --bundle build/ios/iphoneos/Runner.app --debug --no-wifi --args "--enable-dart-profiling --disable-service-auth-codes --disable-observatory-publication --start-paused --enable-checked-mode --verify-entry-points --verbose-logging --trace-startup"`

in `dev/benchmarks/complex_layout`. 

The breaking lines were

```
------ Debug phase ------
Starting debug of 4e131215b69d6679703d698c2418e1e3ddcdf8c6 (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
Device Class: iPhone
build: 18A8395
version: 14.1
version: 14
2020-11-24 22:32:37.468 ios-deploy[2813:30349] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```

The line that says `version: 14` is strange. There's some mismatch but I'm not sure what it is. The [xcode-selected xcode 12a7403 
from cipd]/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.1/DeveloperDiskImage.dmg exists. Not sure if ios-deploy is looking at the right place.

**Comment by xster** [comment]
mac-10 was also stuck on 
![Screen Shot 2020-11-24 at 10 45 01 PM](https://user-images.githubusercontent.com/156888/100192379-b15c5800-2ea6-11eb-8558-de942412fe08.png)

**Comment by xster** [comment]
Might have ran it wrong. Got it to run correctly on an ephemeral xcode and flutter on mac-10.

**Comment by xster** [comment]
Slowly catching up but it looks like we're starting to get some greens :) 

<img width="1073" alt="Screen Shot 2020-11-25 at 12 24 39 AM" src="https://user-images.githubusercontent.com/156888/100201205-9db7ee00-2eb4-11eb-9e01-023b0416e7a0.png">

**Comment by jmagman** [comment]
I think this was fixed by https://github.com/flutter/flutter/pull/75163 or something similar.
This test looks green now, the failures look unrelated to the actual test run https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20tiles_scroll_perf_ios__timeline_summary
