### ISSUE TITLE
Flutter not functioning with latest SDK and Tools - hardcoded tools path inside flutter cli

### ISSUE THREAD

**Issue by violen** [flutter/flutter#70868]
## Steps to Reproduce

1. Have the latest JDK LTS (current is 11 as of writing)
2. Have the latest Android SDK incl. cmdline-tools
3. Set up env vars like this:
![grafik](https://user-images.githubusercontent.com/5476301/99719178-437dee00-2aac-11eb-8377-1222431c0504.png)
![grafik](https://user-images.githubusercontent.com/5476301/99719203-51337380-2aac-11eb-8df9-dc90556140db.png)
PATH:
![grafik](https://user-images.githubusercontent.com/5476301/99720038-64930e80-2aad-11eb-9c9d-6a2a35f0e48c.png)
4. run `flutter doctor`
5. Get this:
![grafik](https://user-images.githubusercontent.com/5476301/99719447-9788d280-2aac-11eb-880a-bdc727f9aea0.png)
6. run `flutter doctor --android-licenses`
7. Get this:
![grafik](https://user-images.githubusercontent.com/5476301/99719543-b8512800-2aac-11eb-9724-6b6d578606fe.png)

**Expected results:** 

Android SDK shall be correctly found and licenses are activated.
Flutter is using the cmdline-tools if installed.
Flutter could ask about cmdline tools directory or to setup the PATH

**Actual results:** 

Forces you to use old software.
#51670  #67251 #58737
Uses hardcoded path of deprecated software.

**Comment by jonahwilliams** [comment]
This has nothing to do with hardcoded paths. The Android SDK tools required a 1.8 JDK or JRE.

**Comment by violen** [comment]
Well thats not entirely true. If you are using the cmdline-tools they are compatible with newer versions of Java. Even though gradle works with higher versions of Java nowadays. 
You can compile your Android App with higher JDK Versions. So somewhere in the flutter toolchain must be something like `$Android_Root/tools/bin/...`
Only the old `sdkmanager` binary forces you to have JDK / JRE 8 available. This haven't to be. (Step 7 output)

**Comment by pedromassangocode** [comment]
Hi @violen 
Currently Flutter requires a 1.8 JDK/JRE. Please see https://github.com/flutter/flutter/issues/62924#issuecomment-668904152 and https://github.com/flutter/flutter/issues/66458#issuecomment-697483466.

Closing as this has nothing to do with Flutter tools. See the comments above and subscribe on that issue for more updated.
Thank you
