### ISSUE TITLE
[customer:money (g3)] [US] [<Platform: Android/iOS>] - Crash Signature: GrMtlGpu::insertFence-4e2ec500

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70877]
https://b.corp.google.com/issues/173700659 for Google discussion. Conversation should occur there, please.

cc @zanderso.

**Comment by kf6gpe** [comment]
There's now a screenshot on the upstream bug, but I'm not sure how useful it is.

**Comment by chinmaygarde** [comment]
Will bring this up with Skia in the sync later today.

**Comment by chinmaygarde** [comment]
Update: The Skia team is unable to reproduce this and looking for help with a reduced test case.

**Comment by chinmaygarde** [comment]
This should be fixed by https://github.com/google/skia/commit/f557aef55f5df1666920677e0b84ce5fef425033 in Skia.
