### ISSUE TITLE
Establish a weekly critical metrics report for the team

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7089]
This is so we increase visibility into how we're doing w.r.t. our critical metrics.

**Comment by Hixie** [comment]
I don't think we need this. We're doing great just watching the benchmarks daily. A week latency would be too much to actually fix regressions anyway, it needs to be right away or we don't fix it.

cc @eseidel

**Comment by eseidelGoogle** [comment]
sgtm.  When @yjbanov and I last discussed this the goal was to save him from constantly build-coping.  But we're a small team, we can do unscalable things for now.  I'm fine with closing.

**Comment by yjbanov** [comment]
Aye
