### ISSUE TITLE
Performance regression in 99th_percentile_frame_build_time_millid imagefiltered_transform_animation_perf__timeline_summary

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70894]
See https://flutter-flutter-perf.skia.org/e/?begin=1605639734&end=1605667984&keys=Xecf9a55edeacb08ed17ff469c1596870&num_commits=50&request_type=1&xbaroffset=22571

May be Dart roll https://github.com/flutter/flutter/pull/70712.

/cc @bkonyi @liyuqian. I can provide a Moto G4 if needed to one of you to bisect & repro.

**Comment by chinmaygarde** [comment]
The results seemed bimodal and an unrelated package update seems to be the culprit. I am lowering the priority as this doesn't seem actionable.

**Comment by a-siva** [comment]
Why not close it if there is nothing actionable.
