### ISSUE TITLE
Android Studio installing devtools... Not complete.

### ISSUE THREAD

**Issue by wigl** [flutter/flutter#70892]
## Steps to Reproduce

1. Android Studio 4.0.1: New flutter project.
2. Debug or run project with iPhone 12 simulator.
3. Result: "installing devtools.." unsuccessful for a long time.
<img width="831" alt="error" src="https://user-images.githubusercontent.com/12051109/99735047-e52e2b00-2afe-11eb-81a2-66b2d93b4cd9.png">

I tried to solve the problem, searched stackoverflow and github, but there is no valid information, please help me, thank you.

## Logs

```
[✓] Flutter (Channel stable, 1.22.0, on macOS 11.0.1 20B29, locale zh-Hans-CN)
    • Flutter version 1.22.0 at /Users/**/flutter
    • Framework revision d408d302e2 (7 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/**/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 06E796A4-AC7D-4694-B993-E9874BCE14C8 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
• No issues found!
```

**Comment by iapicca** [comment]
this seems an issue with android studio rather with flutter

**Comment by wigl** [comment]
> this seems an issue with android studio rather with flutter

@iapicca 

My other computer(mac mini), the same Android Studio 4.0.1, no problem. 

Do you know how to determine that the problem with android studio rather with flutter？

**Comment by wigl** [comment]
[stackoverflow: Flutter inspector stucked on “Installing Dev tools”](https://stackoverflow.com/q/64725383)

By running (android studio) `File > Invalid Caches / Restart... `, not work to me.

**Comment by pedromassangocode** [comment]
Hi @wigl, 
to report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
