### ISSUE TITLE
TabBar animation not showing if the indicator color changes

### ISSUE THREAD

**Issue by valentinoguerra** [flutter/flutter#70891]
## Steps to Reproduce

Run this code: 
`class TestTabBar extends StatefulWidget {
  @override
  _TestTabBarState createState() => _TestTabBarState();
}

class _TestTabBarState extends State<TestTabBar> with SingleTickerProviderStateMixin {
  TabController _controller;
  int _tabIndex;
  @override
  void initState() {
    super.initState();
    _tabIndex = 0;
    _controller = TabController(length: 2, vsync: this)
      ..addListener(() => setState(() => _tabIndex = _controller.index));
  }

  @override
  Widget build(BuildContext context) {
    return TabBar(
      controller: _controller,
      unselectedLabelColor: Colors.black,
      indicator: BoxDecoration(color: _tabIndex == 0 ? Colors.red : Colors.blue),
      tabs: [Tab(text: 'A'), Tab(text: 'B')],
    );
  }
}
`

**Expected results:** Animated indicator that changes its color when switching tabs 

**Actual results:**  The indicator changes its color but the slide animation is not showing

**Comment by iapicca** [comment]
@valentinoguerra 
try it copy paste it on [dartpad](https://dartpad.dartlang.org/) for a larger screen, 
it does animate and it just the red decoration "disappear" when the index changes,
but this is expected looking at the code, if you want to animate this effect you may want to consider 
creating your own [animation](https://flutter.dev/docs/development/ui/animations/tutorial)


```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  static const List<Tab> _tabs = <Tab>[
    Tab(text: 'Tab 1'),
    Tab(text: 'Tab 2'),
    Tab(text: 'Tab 3'),
  ];
  var _index = 0;
  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: _tabs.length)
      ..addListener(() => setState(() => _index = _tabController.index));
  }

  @override
  void dispose() {
    _tabController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              indicator:
                  BoxDecoration(color: _index == 0 ? Colors.red : Colors.blue),
              controller: _tabController,
              tabs: _tabs,
            ),
          ),
          body: TabBarView(
            controller: _tabController,
            children: <Widget>[
              for (Tab t in _tabs) Center(child: Text(t.text)),
            ],
          ),
        ),
      );
}

```

**Comment by pedromassangocode** [comment]
Hi @valentinoguerra 
As said in the comment above, you may want to create a custom TabBar which support color animation. See the link provided to learn how to do that.

Closing as working as expected.
