### ISSUE TITLE
[camera] createCaptureSession used by camera deprecated in API level 30

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#70897]
This can be replaced by the suggested alternative in the link.
https://developer.android.com/reference/android/hardware/camera2/CameraDevice#createCaptureSession(java.util.List%3Candroid.view.Surface%3E,%20android.hardware.camera2.CameraCaptureSession.StateCallback,%20android.os.Handler)

**Comment by ditman** [comment]
Related? https://github.com/flutter/flutter/issues/69883

**Comment by blasten** [comment]
duplicate of https://github.com/flutter/flutter/issues/69883
