### ISSUE TITLE
Mouse scroll not working in WEB

### ISSUE THREAD

**Issue by ReniDelonzek** [flutter/flutter#70902]
Creating a list within a list causes the mouse scroll to stop working. Holding and dragging still works.
This problem was introduced in the latest version of the dev channel, before that it worked correctly

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E287 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.51.1)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

Sample Code:

```
import 'package:flutter/material.dart';

class Example extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return ExampleState();
  }
}

class ExampleState extends State<Example> {
  @override
  Widget build(BuildContext context) {
    return ListView(
        children: List.generate(100, (index) => index)
            .map((e) => ListView(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  children: [
                    Card(
                      child: Container(
                        child: Text('Test'),
                      ),
                    )
                  ],
                ))
            .toList());
  }
}
```

**Comment by iapicca** [comment]
try removing this line

```dart
                  physics: NeverScrollableScrollPhysics(),
```

**Comment by pedromassangocode** [comment]
Hi @ReniDelonzek 
Please try the suggestion in the comment above.
If the issue persists, provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by ReniDelonzek** [comment]
If I remove the physics, I am unable to scroll the entire page when I have the mouse on top of the second list. What I want is that only the first list has a scroll, and the second (the daughter) just appears and does not interfere with scrolling.

This approach worked perfectly until the previous version of the flutter on the dev channel

Flutter doctor outputs and code samples are in my original comment

**Comment by iapicca** [comment]
> If I remove the physics, I am unable to scroll the entire page when I have the mouse on top of the second list. What I want is that only the first list has a scroll, and the second (the daughter) just appears and does not interfere with scrolling.
> 
> This approach worked perfectly until the previous version of the flutter on the dev channel
> 
> Flutter doctor outputs and code samples are in my original comment

@ReniDelonzek 
all the above isn't clear from the code sample you procided,
can you provide a minimal reproducible code sample that reproduce the issue you are experiencing

**Comment by ReniDelonzek** [comment]
This is related [to](https://github.com/flutter/flutter/issues/70948) that was opened later, but the problem is the same

**Comment by Piinks** [comment]
Looks like a dupe of https://github.com/flutter/flutter/issues/70948 - I have a fix on the way for that one if it is the same we can close this. :)

**Comment by ReniDelonzek** [comment]
@Piinks Looking forward to seeing! I'll close this
