### ISSUE TITLE
Scan and listen to events from Bluetooth devices in background with flutter

### ISSUE THREAD

**Issue by kheuss** [flutter/flutter#70901]
I want to set up a mobile application with flutter which also runs in the background. this application allows you to scan bluetooth devices and listen to events to launch a notification and / or start a ringtone. I managed to do all this and it works very well with the flutter_blue plugin. But my problem is that the application has to keep running in the background.

I came here to seek help.

The app does exactly what this app does https://play.google.com/store/apps/details?id=com.antilost.app3&hl=fr&gl=US

**Comment by iapicca** [comment]
@kheuss 
this issue doesn't seem a feature request or a bug report,
If you need help writing your application
choose the option **I want help writing my application**  in the [new issue [](menu](https://github.com/flutter/flutter/issues/new/choose))
which will head you to stackoverflow

**Comment by pedromassangocode** [comment]
See the comment above.

Closing as invalid.
