### ISSUE TITLE
Flutter is always looking for the pubspec.yaml in C:\User\<username> folder and can not find it.

### ISSUE THREAD

**Issue by prince13207** [flutter/flutter#70905]
1. I followed the steps mention on flutter website for installation i.e. download zip and extract, set env path and install android studio and plugins.
2. Now when i try to do flutter pub get from Android Studio or Command line , the command always searches for pubspec.yaml file in the C:\User\<username> directory and not in the project directory  and throw an error as below 
![image](https://user-images.githubusercontent.com/25677327/99749483-a7340580-2b04-11eb-8f63-bbbadab8ff6e.png)

3. I have tried multiple solutions but nothing has worked so far. I have reinstalled flutter , android studio multiple time. Also tried to clear cache folder in Appdata\local\Pub but nothing worked. Please help me understand what i am doing wrong.
Here is my doctor summoary:
![image](https://user-images.githubusercontent.com/25677327/99749810-2aedf200-2b05-11eb-9079-59d79eca81ee.png)

**Comment by RivaanRanawat** [comment]
Please have a look on this link: https://stackoverflow.com/questions/27217278/could-not-find-a-file-named-pubspec-yaml-in
Hope it helps you.

**Comment by prince13207** [comment]
@RivaanRanawat I tried deleting the cache folder and also flutter pub cache repair but that is not solving the problem. The flutter pub get command keeps throwing the same error and it keeps searching for pubspec.yaml in the below location even when i am running the command from my project directory on different drive
![image](https://user-images.githubusercontent.com/25677327/99768053-2be54a80-2b2a-11eb-94fc-8c5eb7dce3de.png)

**Comment by pedromassangocode** [comment]
Hi @... 
The version of Flutter you are running is almost one year old, please make sure you use the latest stable version by running the commands bellow:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by sidrao2006** [comment]
@prince13207 , you are using q very old version of flutter.

Please try upgrading to the latest version. If that did not solve your problem, please provide the output of `flutter doctor -v`
Thank you!

**Comment by prince13207** [comment]
I upgraded the flutter to latest stable version but the error is still coming . The verbose logging helped identifying where the problem could be (io.dart) but i am still not sure what exactly the issue is as i am not altering any of the files that come in the flutter download and simply running for first time. Also flutter doctor is not able to flutter and dart plugins installed in android studio .  Please find screen shots below:


![image](https://user-images.githubusercontent.com/25677327/99827320-7f35b800-2b7f-11eb-8473-7e6b547225b2.png)

**Flutter --upgrade verbose output**
C:\Users\princ\demo2>flutter pub upgrade --verbose
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[ +168 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +150 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +2 ms] executing: [C:\src\flutter/] git tag --points-at HEAD
[  +92 ms] Exit code 0 from: git tag --points-at HEAD
[  +27 ms] 1.22.4
[  +19 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +115 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +74 ms] Exit code 0 from: git ls-remote --get-url origin
[  +34 ms] https://github.com/flutter/flutter.git
[ +138 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +102 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +31 ms] stable
[  +72 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +33 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +33 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +39 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +41 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +33 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +108 ms] Running "flutter pub upgrade" in demo2...
[  +35 ms] executing: [C:\Users\princ\demo2/] C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose upgrade --no-precompile
[ +176 ms] FINE: Pub 2.10.4
[  +38 ms] IO  : Spawning "cmd /c ver" in C:\Users\princ\.
[  +72 ms] IO  : Finished ver. Exit code 0.
[  +31 ms]     | stdout:
[   +4 ms]     | |
[  +15 ms]     | | Microsoft Windows [Version 10.0.18363.719]
[  +40 ms]     | Nothing output on stderr.
[  +34 ms] ERR : Could not find a file named "pubspec.yaml" in "C:\Users\princ".
[  +33 ms] FINE: Exception type: FileException
[  +34 ms] FINE: package:pub/src/pubspec.dart 469:7          new Pubspec.load
[  +32 ms]     | package:pub/src/package.dart 140:27         new Package.load
[  +26 ms]     | package:pub/src/entrypoint.dart 173:24      new Entrypoint.current
[  +32 ms]     | package:pub/src/command.dart 46:59          PubCommand.entrypoint
[  +32 ms]     | package:pub/src/command/upgrade.dart 47:11  UpgradeCommand.run
[  +30 ms]     | package:args/command_runner.dart 197:27     CommandRunner.runCommand
[  +35 ms]     | package:pub/src/command_runner.dart 182:39  PubCommandRunner.runCommand.<fn>
[  +34 ms]     | dart:async                                  new Future.sync
[  +32 ms]     | package:pub/src/utils.dart 113:12           captureErrors.wrappedCallback
[  +31 ms]     | package:stack_trace                         Chain.capture
[  +33 ms]     | package:pub/src/utils.dart 126:11           captureErrors
[  +33 ms]     | package:pub/src/command_runner.dart 182:13  PubCommandRunner.runCommand
[  +34 ms]     | ===== asynchronous gap ===========================
[  +36 ms]     | dart:async                                  Future.catchError
[  +32 ms]     | package:pub/src/utils.dart 113:52           captureErrors.wrappedCallback
[  +32 ms]     | package:stack_trace                         Chain.capture
[  +32 ms]     | package:pub/src/utils.dart 126:11           captureErrors
[  +33 ms]     | package:pub/src/command_runner.dart 182:13  PubCommandRunner.runCommand
[  +27 ms]     | dart:async                                  _completeOnAsyncReturn
[  +30 ms]     | package:pub/src/command_runner.dart         PubCommandRunner._validatePlatform
[  +23 ms]     | dart:async                                  _completeOnAsyncReturn
[  +28 ms]     | package:pool/pool.dart                      Pool.withResource
[  +29 ms]     | dart:async                                  _completeOnAsyncReturn
[  +24 ms]     | package:pub/src/io.dart                     runProcess.<fn>
[  +50 ms] Running "flutter pub upgrade" in demo2... (completed in 1.2s)
[  +28 ms] "flutter upgrade" took 2,173ms.
[  +12 ms] pub upgrade failed (66;     | package:pub/src/io.dart                     runProcess.<fn>)
[  +22 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:335:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
           #17     _rootRun (dart:async/zone.dart:1190:13)
           #18     _CustomZone.run (dart:async/zone.dart:1093:19)
           #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +297 ms] ensureAnalyticsSent: 252ms
[  +32 ms] Running shutdown hooks
[  +13 ms] Shutdown hooks complete
[  +32 ms] exiting with code 66


![image](https://user-images.githubusercontent.com/25677327/99827485-b1471a00-2b7f-11eb-853b-2546b2597d1d.png)
![image](https://user-images.githubusercontent.com/25677327/99827518-befc9f80-2b7f-11eb-90d1-faaed0302844.png)

**Comment by prince13207** [comment]
@pedromassangocode Did you get what this issue . I am really stuck at this point and not able to move forward.

**Comment by pedromassangocode** [comment]
I have no idea, never seen this before.
I would try to install Flutter in another directory (in the user's folder) and see if that works.

**Comment by jonahwilliams** [comment]
Without an example that reproduces this problem we will be unable to make progress on this issue

**Comment by jmagman** [comment]
```
[ +35 ms] executing: [C:\Users\princ\demo2/] C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose upgrade --no-precompile
[ +176 ms] FINE: Pub 2.10.4
[ +38 ms] IO : Spawning "cmd /c ver" in C:\Users\princ.
```
Maybe something is changing the working directory?  `cmd /c ver` doesn't specify a working directory, so why is it running one level up?
https://github.com/flutter/flutter/blob/17cdf5559d5a475ee7dba63fccaccc06fd3e8f4d/packages/flutter_tools/lib/src/base/os.dart#L407-L408

**Comment by nico151999** [comment]
Please, check if your project's pubspec.yaml contains any reference to another folder. For example there could be a dependency that is fetched from a local source.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
