### ISSUE TITLE
Google sign in solid black line moving across the screen

### ISSUE THREAD

**Issue by kovalyovi** [flutter/flutter#70907]
I implemented Google sign-in with my Flutter application and everything works like a charm except the black solid line about 15 pixels in height and full-width that moves across the screen from top to bottom right after the successful sign-in takes place. Here is a GIF that demonstrates that. I recorded 3 seconds right after I chose from Google accounts on the device.

![image](https://i.stack.imgur.com/cQMAq.gif)

[link to another web example (file too big to include)](https://miro.medium.com/max/576/1*hXZ812wi-CH-DPAARJIKQg.gif)

There is nothing special about it. I just followed the instructions on the plugin and implemented the Google Sign in and this black line has always been there. It was weird though that I found some online examples without it (primarily on Mac OS). It happens both on Android Emulator and on the real device (Galaxy S8). I haven't tested on an iPhone. 

My system is Windows 10 x64 Education
Ryzen 5 3600
32 GB Ram

Here is the `log` for the process of logging in (between the pressing of the Google sign-in button and the moment this black line disappears): 
```
[+21295 ms] I/th_from_scratc(25190): NativeAlloc concurrent copying GC freed 65193(3638KB) AllocSpace objects, 36(2036KB) LOS objects, 49% free,
4561KB/9122KB, paused 1.393ms total 169.416ms
[+6565 ms] I/flutter (25190): ilia.kovaliov@gmail.com
[ +176 ms] I/BiChannelGoogleApi(25190): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzao@f2321e3
[+1064 ms] D/FirebaseAuth(25190): Notifying id token listeners about user ( qkm7gYAeGkeDP2ZYNQyaBEBmgJ62 ).
[   +1 ms] D/FirebaseAuth(25190): Notifying auth state listeners about user ( qkm7gYAeGkeDP2ZYNQyaBEBmgJ62 ).
[  +96 ms] I/flutter (25190): qkm7gYAeGkeDP2ZYNQyaBEBmgJ62
[  +87 ms] W/DynamiteModule(25190): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
[  +15 ms] I/DynamiteModule(25190): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module
com.google.android.gms.providerinstaller.dynamite:0
[   +1 ms] W/ProviderInstaller(25190): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
[  +30 ms] I/th_from_scratc(25190): The ClassLoaderContext is a special shared library.
[ +106 ms] I/th_from_scratc(25190): The ClassLoaderContext is a special shared library.
[   +1 ms] V/NativeCrypto(25190): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 288 native methods...
[  +61 ms] W/th_from_scratc(25190): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection,
allowed)
[  +32 ms] I/ProviderInstaller(25190): Installed default security provider GmsCore_OpenSSL
[ +415 ms] W/th_from_scratc(25190): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
[   +1 ms] W/th_from_scratc(25190): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking,
allowed)
[  +17 ms] W/th_from_scratc(25190): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking,
allowed)
[  +19 ms] W/th_from_scratc(25190): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
[  +21 ms] W/th_from_scratc(25190): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection,
allowed)
[  +62 ms] W/th_from_scratc(25190): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy;
(greylist,core-platform-api, linking, allowed)
[   +1 ms] W/th_from_scratc(25190): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
[ +262 ms] I/flutter (25190): User qkm7gYAeGkeDP2ZYNQyaBEBmgJ62 has 3 roles
[+1095 ms] I/flutter (25190): Started pulling data from the DB
[ +433 ms] I/flutter (25190): Started pulling data from the DB
[ +661 ms] I/flutter (25190): Execution with after-state took 0:00:01.085934 time
[ +164 ms] I/flutter (25190): Execution with after-state took 0:00:01.097923 time
```

`flutter analyze` results
```
$ flutter analyze
   info - Unused import: 'package:addfaith_from_scratch/shared/enum_helper.dart' - lib\introduction_screens\seed_select.dart:13:8 - unused_import
   info - Unused import: 'package:flare_flutter/flare_actor.dart' - lib\introduction_screens\seed_select.dart:14:8 - unused_import
```

`flutter doctor -v` results
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ILYA\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

• No issues found!
```

How can I get rid of that line or that's 'expected' behavior? I couldn't find any information online about that except this question that has never been answered.

I assume it has to do with the status bar that it's transparent in my application but when the Google Sign-in activity terminates, the animation of 'sliding down' 'pulls' that dark status bar and creates this **ugly** effect. It's my first issue filed so if there is any extra information needed or I need to talk to a different place, let me know.

**Comment by RivaanRanawat** [comment]
Hey @kovalyovi I have used google sign in in one of my projects and I dont see the black line on the screen.

Code:
`Future<String> loginUserWithGoogle() async {
    String retVal = "error";
    GoogleSignIn _googleSignIn = GoogleSignIn(
      scopes: [
        'email',
        'https://www.googleapis.com/auth/contacts.readonly',
      ],
    );

    try {
      GoogleSignInAccount _googleUser = await _googleSignIn.signIn();
      GoogleSignInAuthentication _googleAuth = await _googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
          idToken: _googleAuth.idToken, accessToken: _googleAuth.accessToken);
      AuthResult _authResult = await _auth.signInWithCredential(credential);
      if (_authResult.additionalUserInfo.isNewUser) {
        UserModel _user = UserModel(
          uid: _authResult.user.uid,
          email: _authResult.user.email,
          fullName: _authResult.user.displayName,
          accountCreated: Timestamp.now(),
          notifToken: await _firebaseMessaging.getToken(),
        );
        String _returnString = await DBFuture().createUser(_user);
        if (_returnString == "success") {
          retVal = "success";
        }
      }
      retVal = "success";
    } on PlatformException catch (e) {
      retVal = e.message;
    } catch (e) {
      print(e);
    }
    return retVal;
  }`

pubspec.yaml:
`google_sign_in:`


Hope this solves your issue.

**Comment by RivaanRanawat** [comment]
Hey @kovalyovi I have used google sign in in one of my projects and I dont see the black line on the screen.

Code:
`Future loginUserWithGoogle() async {
String retVal = "error";
GoogleSignIn _googleSignIn = GoogleSignIn(
scopes: [
'email',
'https://www.googleapis.com/auth/contacts.readonly',
],
);

try {
  GoogleSignInAccount _googleUser = await _googleSignIn.signIn();
  GoogleSignInAuthentication _googleAuth = await _googleUser.authentication;
  final AuthCredential credential = GoogleAuthProvider.getCredential(
      idToken: _googleAuth.idToken, accessToken: _googleAuth.accessToken);
  AuthResult _authResult = await _auth.signInWithCredential(credential);
  if (_authResult.additionalUserInfo.isNewUser) {
    UserModel _user = UserModel(
      uid: _authResult.user.uid,
      email: _authResult.user.email,
      fullName: _authResult.user.displayName,
      accountCreated: Timestamp.now(),
      notifToken: await _firebaseMessaging.getToken(),
    );
    String _returnString = await DBFuture().createUser(_user);
    if (_returnString == "success") {
      retVal = "success";
    }
  }
  retVal = "success";
} on PlatformException catch (e) {
  retVal = e.message;
} catch (e) {
  print(e);
}
return retVal;
}`

pubspec.yaml:
google_sign_in:

Hope this solves your issue.

**Comment by RivaanRanawat** [comment]
Hey @kovalyovi I have used google sign in in one of my projects and I dont see the black line on the screen.

Code:

`Future loginUserWithGoogle() async {
String retVal = "error";
GoogleSignIn _googleSignIn = GoogleSignIn(
scopes: [
'email',
'https://www.googleapis.com/auth/contacts.readonly',
],
);

try {
GoogleSignInAccount _googleUser = await _googleSignIn.signIn();
GoogleSignInAuthentication _googleAuth = await _googleUser.authentication;
final AuthCredential credential = GoogleAuthProvider.getCredential(
idToken: _googleAuth.idToken, accessToken: _googleAuth.accessToken);
AuthResult _authResult = await _auth.signInWithCredential(credential);
if (_authResult.additionalUserInfo.isNewUser) {
UserModel _user = UserModel(
uid: _authResult.user.uid,
email: _authResult.user.email,
fullName: _authResult.user.displayName,
accountCreated: Timestamp.now(),
notifToken: await _firebaseMessaging.getToken(),
);
String _returnString = await DBFuture().createUser(_user);
if (_returnString == "success") {
retVal = "success";
}
}
retVal = "success";
} on PlatformException catch (e) {
retVal = e.message;
} catch (e) {
print(e);
}
return retVal;
}`

pubspec.yaml:
google_sign_in:

Hope this solves your issue.

**Comment by RivaanRanawat** [comment]
Hi @kovalyovi I have implemented google sign in in one of my apps and i didnt face this issue.
Code:
Future loginUserWithGoogle() async {
String retVal = "error";
GoogleSignIn _googleSignIn = GoogleSignIn(
scopes: [
'email',
'https://www.googleapis.com/auth/contacts.readonly',
],
);

try {
GoogleSignInAccount _googleUser = await _googleSignIn.signIn();
GoogleSignInAuthentication _googleAuth = await _googleUser.authentication;
final AuthCredential credential = GoogleAuthProvider.getCredential(
idToken: _googleAuth.idToken, accessToken: _googleAuth.accessToken);
AuthResult _authResult = await _auth.signInWithCredential(credential);
if (_authResult.additionalUserInfo.isNewUser) {
UserModel _user = UserModel(
uid: _authResult.user.uid,
email: _authResult.user.email,
fullName: _authResult.user.displayName,
accountCreated: Timestamp.now(),
notifToken: await _firebaseMessaging.getToken(),
);
String _returnString = await DBFuture().createUser(_user);
if (_returnString == "success") {
retVal = "success";
}
}
retVal = "success";
} on PlatformException catch (e) {
retVal = e.message;
} catch (e) {
print(e);
}
return retVal;
}

pubspec.yaml:
google_sign_in:

Hope this solves your issue.

**Comment by pedromassangocode** [comment]
Hi @kovalyovi 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by kovalyovi** [comment]
Thank you for offering help. This black line is the status bar that has a different color than my status bar because I made it transparent but the google sign-in package doesn't pull my settings and makes the status bar for that sign-in screen black. 

This is the duplicate of [issue #48371](https://github.com/flutter/flutter/issues/48371) with a potential workaround [here](https://github.com/flutter/flutter/issues/48371#issuecomment-629549018).
