### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by chenyongze** [flutter/flutter#70911]
报错信息：
Can't load Kernel binary: Invalid kernel binary format version.
Dart snapshot generator failed with exit code 254
Can't load Kernel binary: Invalid kernel binary format version.
Dart snapshot generator failed with exit code 254

Command PhaseScriptExecution failed with a nonzero exit code

系统：

![image](https://user-images.githubusercontent.com/4531363/99755107-db1f2300-2b24-11eb-9588-d249c4676d89.png)

![image](https://user-images.githubusercontent.com/4531363/99755114-e2463100-2b24-11eb-8926-19f0a5df15a3.png)

**Comment by chenyongze** [comment]
![image](https://user-images.githubusercontent.com/4531363/99755191-1cafce00-2b25-11eb-9507-b4d1c2b5ac4d.png)

**Comment by TahaTesser** [comment]
Hi @chenyongze 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by chenyongze** [comment]
Thank you. It's been fixed. Downloaded the flutter again.

**Comment by darshankawar** [comment]
@chenyongze Closing this as solved based on your comment above.
