### ISSUE TITLE
Migrate package:integration_test tests in flutter/packages to the new reporting API

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#70922]
flutter/plugins uses the legacy API for reporting test results. This means that using `test()` to run tests will not work, and can lead to confusion such as #60943.

I think this should be done after #66264, to reduce the amount of intermediate boilerplate that is needed. Even if we have that though, I'm not sure how to resolve the dependency issues. The new API was added to the `package:integration_test` plugin after it was moved to flutter/flutter. It is only compatible with the master channel, not stable, but flutter/plugins runs CI against both channels. Either we can wait for `package:integration_test` (from flutter/flutter) to hit stable, or we can choose to run the `package:integration_tests` tests in flutter/plugins only on the master channel. Don't know if there are better alternatives for this – cc @dnfield

**Comment by stuartmorgan** [comment]
What is the new API? I'm not sure what this change involves, concretely.

**Comment by jiahaog** [comment]
Instead of running the tests on CI with 

```
flutter drive \
  --driver=test_driver/<driver_file> \
  --target=integration_test/<test file>
```

use 

```
flutter test integration_test
```

Note that the latter does not support web (yet), so we might want to fix that first.

**Comment by stuartmorgan** [comment]
I made that change recently, so in that case this is fixed.
