### ISSUE TITLE
unable to run"adb",check your android sdk installation and ANDROID_SDK_ROOT enviroment variable: c:\users\sayan\appdata\local\android\sdk\platfotm-tools\adb.exe" how can i solve this issue

### ISSUE THREAD

**Issue by sayan-dot** [flutter/flutter#70924]
when i am running flutter doctor in my command promt and error pops up saying 

"connected device : (the doctor check crashed )
due to an error, the doctor check did not complete.
 exception: unable to run"adb",check your android sdk installation and ANDROID_SDK_ROOT enviroment variable:
c:\users\sayan\appdata\local\android\sdk\platfotm-tools\adb.exe"

i dont know hoe to solve this error i will be greatfull if anybody helps me to solve this

"connected device : (the doctor check crashed )
due to an error, the doctor check did not complete.
 exception: unable to run"adb",check your android sdk installation and ANDROID_SDK_ROOT enviroment variable:
c:\users\sayan\appdata\local\android\sdk\platfotm-tools\adb.exe"

**Comment by iapicca** [comment]
can you provide your full `flutter doctor -v`
and you output of `flutter emulators`

**Comment by sidrao2006** [comment]
Hello @sayan-dot ,

Could you please run `echo $ANDROID_SDK_ROOT` and check if the output is a valid path to the Android SDK?

Thanks

**Comment by pedromassangocode** [comment]
Hi @sayan-dot 
Please provide what was requested above.

**Comment by sayan-dot** [comment]
hy guys thanks for your help the issue has been solved successfully by adding paths of ANDROID_SDK_ROOT to enviorment variable so closing the issue her
