### ISSUE TITLE
Flutter has no SQLite ORM framework.

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#70920]
Flutter has no SQLite ORM framework.

**Comment by iapicca** [comment]
NOSQL
[shared_preferences](https://pub.dev/packages/shared_preferences)
[hive](https://pub.dev/packages/hive)
[sembast](https://pub.dev/packages/sembast)

SQLite
[sqflite](https://pub.dev/packages/sqflite)

SQL + ORM
[moor](https://pub.dev/packages/moor) 

SQLite + ORM
[sqfentity](https://pub.dev/packages/sqfentity)
