### ISSUE TITLE
"Exception: FileSystemException; OS Error: Permission denied" in android 10 using targetSdkVersion 29

### ISSUE THREAD

**Issue by Joao-b4** [flutter/flutter#70939]
"Exception: FileSystemException; OS error: Permission denied" on Android 10 using targetSdkVersion 29, even with permissions granted and requestLegacyExternalStorage = "true"

Exception:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: FileSystemException: Cannot open file, path = '/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201119-WA0050.jpg' (OS Error: Permission denied, errno = 13)
```

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-10.0.pre.131, on Microsoft Windows [versÃ£o 10.0.18363.1198], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
```

AndroidManifest.xml
```
    ...
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
    <uses-permission android:name="android.permission.CAMERA"  tools:remove="android:maxSdkVersion" />
    <application
        ...
        android:requestLegacyExternalStorage="true"
     ...
```

example: 
```
List<int> imageBytes = imageNow.readAsBytesSync();
```

**Comment by darshankawar** [comment]
@Joao-b4 
I see that there's a space in the folder name `WhatsApp Images`:

`path = '/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201119-WA0050.jpg' (OS Error: Permission denied, errno = 13)`
Can you fix the folder name and try again to see if it works ?
Also I noticed that you are on older version of master. Current master version is `1.24.0`. You may want to upgrade to latest and try again if above doesn't work.

**Comment by Joao-b4** [comment]
the problem was not in the way of the image, because I tested it with others images.
I upgraded to version 1.24.0 but my packages are not compatible with null-safety, and I had to revert to version 1.22.4 stable.

now the app works, but only with "compileSdkVersion: 28"
"compileSdkVersion: 29" still has errors

**Comment by darshankawar** [comment]
@Joao-b4 
When you say `my packages are not compatible with null-safety`, what do you mean exactly ?
Can you provide a minimal complete reproducible code sample that shows the issue ?

**Comment by Joao-b4** [comment]
solved the "FileSystemException" when updating the FilePicker, now I take the bytes of the image directly from it, without taking the path of the file and then reading the bytes.

when updating to the latest version of the master my editor is pointing out these null safety errors, and to compile it also contains errors related to null safety.

![image](https://user-images.githubusercontent.com/34102271/100233067-f2d11f80-2f07-11eb-81d8-126ae627eed6.png)

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-8.0.pre.366, on Microsoft Windows [versÃ£o 10.0.18363.1198], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[!] Connected device
    ! No devices available
```

**Comment by darshankawar** [comment]
@Joao-b4 
Please provide minimal complete reproducible code sample along with `pubspec.yaml` that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
