### ISSUE TITLE
CupertinoTextField I have to tap twice to past instead of once.

### ISSUE THREAD

**Issue by danielwalczak** [flutter/flutter#70949]
## Steps to Reproduce

```
CupertinoTextField()
```

**Expected results:** 
Using flutter CupertinoTextField or TextField, user have to tap twice in order to display `paste` dialog where native ios component it will show after one tap. Probably it has something to do with android compatibility where the native behavior is different from ios.
 
<details>
  <summary>Logs</summary>

```

```

```
Analyzing ios...                                                        
No issues found! (ran in 1.5s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by sidrao2006** [comment]
Hello @danielwalczak ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by darshankawar** [comment]
@danielwalczak 
There's similar open issue describing your case, [48434](https://github.com/flutter/flutter/issues/48434).
Please follow-up there for updates.
Closing this as duplicate.
