### ISSUE TITLE
Expansion Panels demo wraps poorly on iPhone SE

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7094]
![img_0005](https://cloud.githubusercontent.com/assets/11857803/20733828/70a5ea7a-b64a-11e6-840d-a6d13f560c7e.PNG)

FYI @HansMuller

**Comment by eseidelGoogle** [comment]
Maybe the wrapping is not bad?  Not sure. I was surprised.

**Comment by HansMuller** [comment]
In cases like this the developer has implied that the text they've provided will fit in the available space. I think they're also implying that the text should never ever wrap like that :-). 

I'll fix it.
