### ISSUE TITLE
[file_selector] replace its locally-defined types by the ones provided by cross_file

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#70950]
## Use case
[file_selector]() defines its own types: [XFile](https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_platform_interface/lib/src/types/x_file) and [XTypeGroup](https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group). 

Those types are general enough to be extracted and used across multiple plugins that deal with file entities.

## Proposal
Replace the local [types](https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_platform_interface/lib/src/types) definitions with the ones provided by [cross_file](https://pub.dev/packages/cross_file
)

****

**Comment by ditman** [comment]
/cc @mvanbeusekom I think Maurits was working on this!

Thanks for creating the issue @tugorez!

**Comment by mvanbeusekom** [comment]
I have created a pull request to replace the local `XFile` types with those from the cross_file package.

@tugorez, @ditman, would it make sense to also move the `XTypeGroup` types to the cross_file package?

**Comment by ditman** [comment]
@mvanbeusekom I thought about this, and I think the XTypeGroup should live in the file_selector package. I think it's a file_selector-only concept.

**Comment by ditman** [comment]
I've merged this, I'll publish as soon as the CI passes on master!
