### ISSUE TITLE
Latest Flutter roll causes a compilation error for <elided platform>

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#70952]
See https://buganizer.corp.google.com/issues/173774628. Escalated to roller, engine chats.

**Comment by jason-simmons** [comment]
Should be fixed by https://github.com/flutter/buildroot/pull/414

**Comment by pedromassangocode** [comment]
https://github.com/flutter/buildroot/pull/414 seems to be merged now. Is it safe to close this issue? I can't verify if this was fixed or not.

**Comment by chinmaygarde** [comment]
This should be fixed once the commit that updates the reference to the buildroot has rolled into Google3. There doesn't seem to be anything actionable here.
