### ISSUE TITLE
On iOS, animations "jump" when returning to a Flutter app from an opened URL

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#7096]
## Steps to Reproduce

A standard thing to want to do is have a widget that triggers an animation and opens a URL at the same time when tapped. For example, closing the drawer by popping the Navigator and opening up a web page. On iOS, when returning to the app using the back link in the upper left hand corner of Safari, the app displays the last frame it drew before being backgrounded until the Safari app has fully navigated away, then it finally draws a frame and the drawer snaps back to the closed position.

I think we might be able to fix this by using UIApplicationWillEnterForegroundNotification instead of UIApplicationDidBecomeActiveNotification in FlutterViewController.mm.

@chinmaygarde

**Comment by collinjackson** [comment]
I talked with Chinmay and he thinks that the solution is to make the vsync_waiter use a time counter that pauses when the app isn't running, instead of ftl::TimePoint::Now()

I don't think this is a particularly urgent issue, but it might manifest more as developers integrate with SDKs that launch into other apps

**Comment by xster** [comment]
This issue has been fixed at the beginning of the year.
