### ISSUE TITLE
Add customer test to verify that Flutter supports Gradle 5.6

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#70964]
This is indirectly tested by building the public Flutter gallery, which is currently pinned to https://github.com/flutter/gallery/commit/8542ca8beebc8e989adee160f7f1f0841a734db2 in https://github.com/flutter/flutter/blob/b18e2a1cc4d9093580bedaa671171e75187e63cf/dev/devicelab/lib/versions/gallery.dart#L6

However, it's preferred to have an explicit customer test with a few more variants: `build apk`/`build app bundle`.

**Comment by christopherfujino** [comment]
Closing as I don't think we will ever prioritize this
