### ISSUE TITLE
iOS flutter.1.profile thread always causing CPU usage

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#70960]
In a Flutter Add2App scenario, after we've loaded a flutter view once, the flutter.1.profile thread is always doing something in the latest 1.22 release, causing 4% CPU on a iPhone SE (latest edition), whereas before the CPU would always be at 0%.

This happens when the Flutter View is present, with no animations or any redraws, and also after dismissing the FlutterViewController.

![Screen Shot 2020-11-20 at 10 27 44 AM](https://user-images.githubusercontent.com/40898687/99840550-bc2b8b80-2b3a-11eb-97fb-d393e8a4ad13.png)

Flutter doctor:
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.2 at /Users/danny.valente/Library/flutter/1.22.2-stable
    • Framework revision 84f3d28555 (5 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

**Comment by dannyvalentesonos** [comment]
The screenshot and reported CPU usage I'm quoting in this bug was taken from a Debug build.

**Comment by jason-simmons** [comment]
Flutter on iOS now contains a sampling profiler (see https://flutter.dev/go/engine-cpu-profiling and https://github.com/flutter/engine/tree/master/shell/profiling).  It is not enabled in release mode builds of the engine.

@iskakaushik

**Comment by darshankawar** [comment]
@dannyvalentesonos 
Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
