### ISSUE TITLE
package:flutter/src/widgets/navigator.dart': Failed assertion: line 4016 pos 12: '!_debugLocked': is not true

### ISSUE THREAD

**Issue by yusufz09** [flutter/flutter#70973]
![image](https://user-images.githubusercontent.com/67047353/99860656-479e2e80-2bc6-11eb-9b9b-b0a6a02d056f.png)

**Comment by sidrao2006** [comment]
Hello @yusufz09 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by darshankawar** [comment]
@yusufz09 
Just posting screenshot is of no help. Instead we look for a minimal reproducible use case that shows the issue you are facing along with `flutter doctor -v. Please provide the same.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
