### ISSUE TITLE
InputContainer should support multi-line labels (and error text)

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#7097]
If the label text is too long, InputContainer truncates it. We should be able to render multi-line error text and label text within InputContainer.

**Comment by eseidelGoogle** [comment]
I believe @HansMuller is working on this?

**Comment by HansMuller** [comment]
Just talked this over with @mehmetf 

We think that making InputContainer more flexible and configurable might not be the right tack. Given InputField it looks like it might be better to build an app-specific container like InputContainer that does exactly what the app needs.

**Comment by mpcomplete** [comment]
Should we close this bug?

**Comment by mehmetf** [comment]
We are switching to using our own InputContainer as suggested by @HansMuller
