### ISSUE TITLE
Adding a ScrollController to CustomScrollView breaks the scroll without errors

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#70971]
This piece of code makes the scrolling stop working:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ScrollController _scrollController;

  @override
  void initState() {
    _scrollController = ScrollController();
    super.initState();
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        controller: _scrollController,
        slivers: [
              SliverAppBar(
                flexibleSpace: FlexibleSpaceBar(
                  title: Text(widget.title),
                ),
              ),
            ],
      ),
    );
  }
}
```

As soon as you comment out the `controller: _scrollController,` line, scrolling works again. 

Using dartpad Based on Flutter 1.23.0-18.1.pre Dart SDK 2.10.4

**Comment by darshankawar** [comment]
@jlubeck 
If you specify ` _scrollController = ScrollController(initialScrollOffset: 1);`, the scrolling works. Can you try that and see if it resolves your query ?

**Comment by jlubeck** [comment]
Yes, that seems to fix the issue. Actually any number that is not 0 makes it work again. 
Is that expected? Doesn't sound like it should like that...

**Comment by darshankawar** [comment]
@jlubeck 
`initialScrollOffset` defaults to 0.0 and is used to initialise scroll offset. You may read it more here : https://api.flutter.dev/flutter/widgets/ScrollController/initialScrollOffset.html

**Comment by jlubeck** [comment]
Yes, I saw that, but what I don't understand is why leaving it at 0 just disables the scrolling altogether.

**Comment by darshankawar** [comment]
@jlubeck There doesn't seem to be explicit mention in the document regarding the behavior if we leave it to 0. If you original issue is resolved, you may close this and open a new issue on `initialScrollOffset`'s behavior.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
