### ISSUE TITLE
Error in Application

### ISSUE THREAD

**Issue by PartapSBimrah** [flutter/flutter#70976]
Hey there,

I'm using the backend as a firebase. But When I tried to import this function like this. It shows me an error. But If I used `var` it shows me an error in the `onComplete` function. You can see the coding and screenshot down below. 

Please see the screenshot carefully, one shows the `StorageReference` error and the other is `onComplete`

![Screenshot (316)](https://user-images.githubusercontent.com/39325207/99864627-69011980-2bca-11eb-81bd-d3acb87d18d8.png)

![Screenshot (317)](https://user-images.githubusercontent.com/39325207/99864629-6b637380-2bca-11eb-865d-cbdcef91cb8f.png)

**Comment by sidrao2006** [comment]
Hey @PartapSBimrah ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a Firebase, please close this issue and open it [here](https://github.com/FirebaseExtended/flutterfire/issues) instead.

Thanks

**Comment by amitkhairnar44** [comment]
@PartapSBimrah 

Instead of `StorageReference` use `Reference`

**Comment by PartapSBimrah** [comment]
Thank for confirming but I have confusion in onComplete method or function. Could you please clarify?

**Comment by amitkhairnar44** [comment]
> Thank for confirming but I have confusion in onComplete method or function. Could you please clarify?

The code you're trying to use is old.

Check https://pub.dev/packages/firebase_storage/changelog
And this: https://firebase.flutter.dev/docs/storage/usage

**Comment by amanv8060** [comment]
Agrre with @amitkhairnar44 . The code has been changed  .
These are the breaking changes mentioned [here](https://pub.dev/packages/firebase_storage/changelog#500-dev1) .

This issue can be closed .

**Comment by PartapSBimrah** [comment]
Thank you for eveyone

**Comment by darshankawar** [comment]
Looking at above comments, I am going ahead and closing this as solved.
@PartapSBimrah If you still face similar issues, please consider opening firebase related issues here:https://github.com/FirebaseExtended/flutterfire/issues
