### ISSUE TITLE
Theme.of shadowThemeOnly removed, without breaking change?

### ISSUE THREAD

**Issue by hpoul** [flutter/flutter#70981]
A recent commit https://github.com/flutter/flutter/commit/0490fd75aa5d59a7f2a4dae4c62543fc6e7b33cf#diff-a8a9a3cded64a0f45ac193fd0d6654c2c8ede69600c4c0773a282a68169a6dbdL127-L134 the `shadowThemeOnly` parameter for `Theme.of` was removed. But I couldn't [find any breaking change for it](https://flutter.dev/docs/release/breaking-changes).

And the parameter is actually still mentioned in the documentation for `isMaterialApp`: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme.dart#L52-L61

Shouldn't this warrant a breaking change? This breaks for example the [flutter_datetime_picker package](https://github.com/Realank/flutter_datetime_picker/issues/197))

**Comment by sidrao2006** [comment]
cc @goderbauer

**Comment by pedromassangocode** [comment]
Cc @goderbauer who made this change in https://github.com/flutter/flutter/pull/68922.

**Comment by goderbauer** [comment]
Per our policy, it is only a breaking change if it breaks a test in our customer_testing shard. For details (and how to contribute your tests to that shard) see https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change. 

I will update the docs of isMaterialAppTheme though, probably by removing the flag altogether.

**Comment by goderbauer** [comment]
Check out this PR to see how you can migrate away from shadowThemeOnly by using the CapturedTheme mechanism: https://github.com/flutter/flutter/pull/69050/files#diff-2cbc1634ed6b61d61dfa090e7bfbbb7c60b74c8abc3a28df6f79eee691fd1b73
