### ISSUE TITLE
I have problem when i start run this issue came can any one  know how to solve this problem

### ISSUE THREAD

**Issue by mazin-dotcom** [flutter/flutter#70987]
```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_platform_interface-1.0.4/lib/path_provider_platform_interface.dart:10:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_platform_interface-1.0.3/lib/plugin_platform_interface.dart': The system cannot find the path specified.

import 'package:plugin_platform_interface/plugin_platform_interface.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_platform_interface-1.0.4/lib/path_provider_platform_interface.dart:11:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_platform_interface-1.0.3/lib/plugin_platform_interface.dart': The system cannot find the path specified.

import 'package:plugin_platform_interface/plugin_platform_interface.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-1.1.1/lib/src/platform_interface/image_picker_platform.dart:8:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_platform_interface-1.0.3/lib/plugin_platform_interface.dart': The system cannot find the path specified.

import 'package:plugin_platform_interface/plugin_platform_interface.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_platform_interface-1.0.4/lib/path_provider_platform_interface.dart:22:45: Error: Type 'PlatformInterface' not found.
abstract class PathProviderPlatform extends PlatformInterface {
                                            ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-1.1.1/lib/src/platform_interface/image_picker_platform.dart:20:44: Error: Type 'PlatformInterface' not found.
abstract class ImagePickerPlatform extends PlatformInterface {
                                           ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_platform_interface-1.0.4/lib/path_provider_platform_interface.dart:24:34: Error: No named parameter with the name 'token'.
  PathProviderPlatform() : super(token: _token);
                                 ^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_platform_interface-1.0.4/lib/path_provider_platform_interface.dart:38:5: Error: Getter not found: 'PlatformInterface'.
    PlatformInterface.verifyToken(instance, _token);
    ^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-1.1.1/lib/src/platform_interface/image_picker_platform.dart:22:33: Error: No named parameter with the name 'token'.
  ImagePickerPlatform() : super(token: _token);
                                ^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-1.1.1/lib/src/platform_interface/image_picker_platform.dart:38:5: Error: Getter not found: 'PlatformInterface'.
    PlatformInterface.verifyToken(instance, _token);
    ^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finishe
```

**Comment by mazin-dotcom** [comment]
please  help me (:

**Comment by iapicca** [comment]
@mazin-dotcom 
can you provide your `flutter doctor -v`, your `flutter run -v` and a minimal reproducible code sample

**Comment by darshankawar** [comment]
@mazin-dotcom 
Please provide above requested details. Also you may try to run `flutter pub cache repair` or `flutter clean` to see if it works.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by RupeshSK30** [comment]
> @mazin-dotcom
> Please provide above requested details. Also you may try to run `flutter pub cache repair` or `flutter clean` to see if it works.

I  got same issue and I was searching for the solution for a long time. This solved my error. Thank you for your contribution!!

**Comment by emexbazz** [comment]
Am still having this error 

the output of flutter run -v (I stopped at where the error started)

[ +360 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +352 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[   +3 ms] executing: [C:\src\flutter/] git tag --points-at
b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[ +241 ms] Exit code 0 from: git tag --points-at
b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[   +5 ms] 2.2.0
[  +26 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +195 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/stable
[   +3 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +157 ms] Exit code 0 from: git ls-remote --get-url origin
[   +5 ms] https://github.com/flutter/flutter.git
[ +520 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +199 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +8 ms] stable
[ +388 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +28 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +7 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[  +11 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[  +28 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +329 ms] executing: C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[ +247 ms] List of devices attached
                    02003106B0305817       device product:X557B1
                    model:Infinix_HOT_4_Lite device:X557-Lite transport_id:2
[  +29 ms] C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe -s
02003106B0305817 shell getprop
[+1240 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[+6009 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +969 ms] Skipping pub get: version match.
[ +415 ms] Found plugin audioplayers at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.18.3\
[+2437 ms] Found plugin path_provider at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider-2.0.2\
[ +121 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_linux-2.0.0\
[ +108 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_macos-2.0.0\
[ +315 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_windows-2.0.1\
[ +528 ms] Found plugin shared_preferences at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.7+3\
[  +84 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_macos-0.0.1+11\
[ +237 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_web-0.1.2+7\
[+3029 ms] Found plugin audioplayers at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.18.3\
[  +86 ms] Found plugin path_provider at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider-2.0.2\
[  +10 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_linux-2.0.0\
[  +11 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_macos-2.0.0\
[  +14 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_windows-2.0.1\
[  +23 ms] Found plugin shared_preferences at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.7+3\
[  +10 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_macos-0.0.1+11\
[  +11 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_web-0.1.2+7\
[+3532 ms] Generating
C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\android\app\src\main\java\io\fl
utter\plugins\GeneratedPluginRegistrant.java
[+1132 ms] ro.hardware = mt6580
[   +6 ms] ro.build.characteristics = default
[ +315 ms] Initializing file store
[ +182 ms] Skipping target: gen_localizations
[  +33 ms] complete
[  +27 ms] Launching lib\main.dart on Infinix HOT 4 Lite in debug mode...
[  +43 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Bazz\AppData\Local\Temp\flutter_tools.8233dca9\flutter_tool.b12bdf4d\app.dill
--packages
C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[ +515 ms] executing: C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe -s
02003106B0305817 shell -x logcat -v time -t 1
[  +79 ms] <- compile package:flame_gameapp/main.dart
[ +163 ms] --------- beginning of main
                    06-03 08:52:29.653 D/agps    ( 2125): [agps][n][CP] [MD_1] write
                    pmtk [$PMTK733,6*2F
                    06-03 08:52:29.653 D/agps    ( 2125): ]
[ +300 ms] executing: C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe
version
[ +457 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.2-7242960
                    Installed as
                    C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +27 ms] executing: C:\Users\Bazz\AppData\Local\Android\sdk\platform-tools\adb.exe
start-server
[ +193 ms] Building APK
[  +77 ms] Running Gradle task 'assembleDebug'...
[ +903 ms] Using gradle from
C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\android\gradlew.bat.
[ +104 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1886 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java
-version
[   +6 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +9 ms] executing:
[C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\android/]
C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-arm
-Ptarget=C:\Users\Bazz\Documents\CODES\FlutterDojo\flame_gameapp\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+37822 ms] Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status
for details
[+49133 ms]
/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-2.0.2/lib/path_provid
er.dart:9:8: Error: Error when reading
'/C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider_platform_interface-2
.0.1/lib/path_provider_platform_interface.dart': The system cannot find the path
specified.
[  +47 ms] import
'package:path_provider_platform_interface/path_provider_platform_interface.dart';
[   +4 ms]        ^
[   +4 ms]



THE OUTPUT OF flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985],
    locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.2)
[√] Android Studio
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)


what caused this error?
how do i resolve it?
what do i do


• No issues found!
