### ISSUE TITLE
Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by abusufianshibli** [flutter/flutter#70984]

**Comment by iapicca** [comment]
@abusufianshibli 
can you provide your `flutter doctor -v`, your `flutter run -v` and  minimal reproducible code sample

**Comment by deveshgarg-max** [comment]
Hey @abusufianshibli,
This generally happens when you are showing any widget using functions via initstate(), didchangedependency() before let flutter build the current screen on the device hope it helps you.

Thank you.

**Comment by darshankawar** [comment]
@abusufianshibli 
Please provide requested details as commented here:

https://github.com/flutter/flutter/issues/70984#issuecomment-731579969

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
