### ISSUE TITLE
initializing flutter failed with version solving failed

### ISSUE THREAD

**Issue by KentWong0612** [flutter/flutter#70992]
I have been using VScode to run flutter as usual, and suddenly it stops working today. Stuck at here forever.
![error](https://user-images.githubusercontent.com/48284979/99881274-b1184e80-2c53-11eb-80c9-34cf730a5bca.jpg)

And I run flutter doctor/ flutter run, the following error occurs :\
```
(base) PS C:\Users\Home\FYP\social_map> flutter doctor
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.9.2.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

I am a beginner at programming and I don't sure what else information I can provide. Any help would save me so hard.

**Comment by sidrao2006** [comment]
Hello @KentWong0612 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by KentWong0612** [comment]
Same output as above :(
```
(base) PS C:\Users\Home\FYP\social_map> flutter run -v
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.9.2.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

```
(base) PS C:\Users\Home\FYP\social_map> flutter doctor -v
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.9.2.

Because flutter_tools depends on test >=1.16.0-nullsafety which requires SDK version >=2.10.0-0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

I can't really provide any code sample now, like when I try to create a new flutter project in VScode, and it is just empty and nth will be created
![empty](https://user-images.githubusercontent.com/48284979/99881886-68629480-2c57-11eb-9997-4337ab4494fe.jpg)

**Comment by KentWong0612** [comment]
Have just tried to upgrade Dart SDK from here: dart.dev/get-dart. Still not working, but one thing I notice is that it said Dart.sdk is not installed instead of being upgraded in the process, not so sure if that matters

**Comment by sidrao2006** [comment]
Could you please try `flutter upgrade -v` and post it's output.

If it fails, please try reinstalling the flutter SDK following the [getting started guide](https://flutter.dev/docs/get-started/install/windows?gclid=Cj0KCQiAkuP9BRCkARIsAKGLE8WH_O9HxPVlpJg0FTqOoxQj7-3c_f5EY43cHpuLFSPVLUCOZuq99TMaAl_LEALw_wcB&gclsrc=aw.ds

**Comment by pedromassangocode** [comment]
Hi @KentWong0612 
Please provide what were asked in the comment above.

**Comment by KentWong0612** [comment]
Reinstalled the flutter SDK and it works again, thank you for your help
