### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'animateCamera' was called on null.

### ISSUE THREAD

**Issue by kadnan0900** [flutter/flutter#70990]
class MapView extends StatefulWidget {
  const MapView({Key key}) : super(key: key);

  @override
  _MapViewState createState() => _MapViewState();
}

class _MapViewState extends State<MapView> {
  LatLng currentLocation = LatLng(-2.142869, -79.923845);

  TextEditingController locationController = TextEditingController();

  GoogleMapController _mapController;

  LatLng get initialPos => currentLocation;

  bool searching = false;

  String header = "";

  @override
  void initState() {
    getUserLocation();
    super.initState();
  }

  void getMoveCamera() async {
    List<Placemark> placemark = await placemarkFromCoordinates(
        currentLocation.latitude, currentLocation.longitude);
    locationController.text = placemark[0].name;
    setState(() {
      header = placemark[0].name.toString();
    });
  }

  void getUserLocation() async {
    Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.best);
    List<Placemark> placeMark =
        await placemarkFromCoordinates(position.latitude, position.longitude);
    currentLocation = LatLng(position.latitude, position.longitude);
    locationController.text = placeMark[0].name;
    _mapController.animateCamera(CameraUpdate.newLatLng(currentLocation));
  }

  void onCreated(GoogleMapController controller) {
    _mapController = controller;
  }

  void onCameraMove(CameraPosition position) async {
    setState(() {});
    searching = false;
    currentLocation = position.target;
  }

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<MapViewModel>.reactive(
      builder: (context, model, child) => ResponsiveWidget(
        backgroundColor: Colors.white,
        appBar: BaseAppBar(
          title: Text(Strings.CURRENT_LOCATION),
          appBar: AppBar(),
        ),
        builder: (context) {
          return SafeArea(
              child: Stack(
            children: [
              GoogleMap(
                initialCameraPosition:
                    CameraPosition(target: currentLocation, zoom: 15.7),
                minMaxZoomPreference: MinMaxZoomPreference(10.5, 16.8),
                zoomControlsEnabled: false,
                myLocationEnabled: true,
                myLocationButtonEnabled: false,
                onCameraMove: onCameraMove,
                onMapCreated: onCreated,
                onCameraIdle: () async {
                  searching = true;
                  setState(() {});
                  getMoveCamera();
                },
              ),
              Align(
                alignment: Alignment.center,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    searching == true
                        ? Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10.0),
                              color: AppColors.greenColor.withOpacity(0.9),
                            ),
                            width: 195,
                            height: 38,
                            padding: const EdgeInsets.only(right: 5, left: 5),
                            child: Center(
                              child: Text(
                                "$header",
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 13.2,
                                ),
                                textAlign: TextAlign.center,
                                maxLines: 2,
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                          )
                        : Container(
                            padding: EdgeInsets.symmetric(
                                horizontal: 17, vertical: 12),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10.0),
                              color: AppColors.greenColor.withOpacity(0.9),
                            ),
                            width: 48,
                            height: 38,
                            child: Center(
                              child: CircularProgressIndicator(
                                valueColor:
                                    AlwaysStoppedAnimation(Colors.white),
                                strokeWidth: 2.6,
                              ),
                            ),
                          ),
                    SizedBox(
                      height: 5,
                    ),
                    Padding(
                      padding: const EdgeInsets.only(bottom: 80),
                      child: SvgPicture.asset(
                        AssetsPathStrings.PIN_MARKER,
                        height: 40,
                        width: 40,
                      ),
                    ),
                  ],
                ),
              ),
              searching == true
                  ? Positioned(
                      bottom: 0,
                      right: 0,
                      left: 0,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.end,
                        children: [
                          FloatingActionButton(
                            mini: true,
                            onPressed: getUserLocation,
                            backgroundColor: Colors.white,
                            child: Icon(
                              Icons.gps_fixed,
                              color: Colors.green,
                              size: 28,
                            ),
                          ),
                          SizedBox(
                            height: 15,
                          ),

                          Container(
                            width: double.infinity,
                            padding: EdgeInsets.symmetric(
                                horizontal: 20, vertical: 10),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20.0),
                                topRight: Radius.circular(20.0),
                              ),
                            ),
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                SizedBox(
                                  height: 10,
                                ),
                                CustomTextField(
                                  title: Strings.YOUR_CURRENT_LOCATION,
                                  textStyle:
                                      Theme.of(context).textTheme.headline3,
                                ),
                                Divider(
                                  color: AppColors.subTitleColor,
                                ),
                                Row(
                                  children: [
                                    SvgPicture.asset(
                                      AssetsPathStrings.PIN_MARKER,
                                      height: 20,
                                      width: 20,
                                    ),
                                    SizedBox(
                                      width: 20,
                                    ),
                                    Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        CustomTextField(
                                          title: Strings.YOUR_LOCATION,
                                          textStyle: Theme.of(context)
                                              .textTheme
                                              .subtitle1,
                                        ),
                                        Container(
                                            alignment: Alignment.topLeft,
                                            width: MediaQuery.of(context)
                                                    .size
                                                    .width /
                                                1.3,
                                            child: Text(
                                              "$header",
                                              style: Theme.of(context)
                                                  .textTheme
                                                  .headline3
                                                  .merge(
                                                      TextStyle(fontSize: 15)),
                                              maxLines: 2,
                                              overflow: TextOverflow.ellipsis,
                                            ))
                                      ],
                                    )
                                  ],
                                ),
                                SizedBox(
                                  height: 20,
                                ),
                                Center(
                                  child: RoundedButtonWidget(
                                    height: ScreenUtil().setWidth(60),
                                    width: ScreenUtil().setWidth(380),
                                    buttonText:
                                        Strings.CONFIRM_DELIVERY_LOCATION,
                                    onPressed: () =>
                                        locator<NavigationService>()
                                            .navigateTo(Routes.home),
                                  ),
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                              ],
                            ),
                          ),
                          // ),
                        ],
                      ),
                    )
                  : Container()
            ],
          ));
        },
      ),
      viewModelBuilder: () => MapViewModel(),
    );
  }
}

**Comment by bossbeagle1509** [comment]
How was this solved ? I'm having the same issue
