### ISSUE TITLE
The page will not be updated

### ISSUE THREAD

**Issue by WangVkwind** [flutter/flutter#70991]
I changed my code, but when I hot restarted or recompiled, the page didn't change. The version of flutter is 1.22.3.
![image](https://user-images.githubusercontent.com/49427221/99880935-78777580-2c51-11eb-959c-d9131e20efc5.png)
![image](https://user-images.githubusercontent.com/49427221/99880938-81684700-2c51-11eb-83ae-74fac1d52bd0.png)

**Comment by sidrao2006** [comment]
Hello @WangVkwind ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by WangVkwind** [comment]
@sidrao2006 For example, I added a new menu option, but it is not displayed on the app page. I deleted the build folder, recompiled, and restarted; none of this worked.
