### ISSUE TITLE
can flutter run on Raspberry pi?

### ISSUE THREAD

**Issue by albertog** [flutter/flutter#7099]
We are developing a app for IoT projects in near future and I would like know if  we can run flutter app on Raspberry pi?

**Comment by eseidelGoogle** [comment]
We only provide tooling and prebuilt binaries for iOS and Android.  That said, Flutter's code is highly portable and our tooling is extensible.  I've seen Flutter run on all sorts of devices, I'm sure it could be made work on a Pi:
https://github.com/flutter/engine/wiki/Porting-Flutter's-Engine

**Comment by raju-bitter** [comment]
@albertog I tried Flutter with Exton Linux version of Android for Raspberry Pi 2, and I could run apps. Performance was not great, though. Tried running on Android Things on Raspberry Pi 3, but the current image does not have OpenGL support, Flutter crashed when the framework tries to initialize an EGL context.

**Comment by albertog** [comment]
good idea, I hope soon that will be fix. raspberry is very good platform for iot and flutter must be an actor on that world.

**Comment by eseidelGoogle** [comment]
We recently added support for a software graphics backend (currently only used on iOS simulators): https://github.com/flutter/flutter/issues/6135  I suspect with some hacking one could make flutter/engine use a software backend on the raspberry pi.  That's not a configuration we're looking to support, but just pointing out that it should be possible if you modify & build your own flutter/engine.   Instructions for flutter/engine can be found at https://github.com/flutter/engine/blob/master/CONTRIBUTING.md

**Comment by raju-bitter** [comment]
Android Things team announced support for GPU based rendering with the 0.5 release, but Flutter does still not run on it.
Release notes:

> OpenGL 2.0 Support
> With the update to Android O, OpenGL ES 2.0 is now supported. Platforms with a GPU (such as Raspberry Pi 3) also now support hardware acceleration.

Flutter error message:
```
[ +314 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.yourcompany.hello_test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1671 ms] Diagnostic server URL on device: http://127.0.0.1:37594/
[   +7 ms] /Users/raju/Library/Android/sdk/platform-tools/adb -s 192.168.0.15:5555 forward tcp:8103 tcp:37594
[  +12 ms] Forwarded host port 8103 to device port 37594 for Diagnostic server
[ +159 ms] Observatory URL on device: http://127.0.0.1:37928/
[   +1 ms] /Users/raju/Library/Android/sdk/platform-tools/adb -s 192.168.0.15:5555 forward tcp:8102 tcp:37928
[  +39 ms] Forwarded host port 8102 to device port 37928 for Observatory
[  +56 ms] Connected to service protocol: http://127.0.0.1:8102/
[   +3 ms] getVM: {}
[ +124 ms] E/flutter ( 1442): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(176)] Could not wrap onscreen surface.
```

**Comment by stefanhuber** [comment]
Any news on the progress of running flutter on a raspberry pi?

**Comment by allanclempe** [comment]
I got flutter preview 2 running on Raspberry PI 3 model B and Android Things. No issues so far.

**Comment by alexissantos** [comment]
@allanclempe How's performance?

**Comment by allanclempe** [comment]
@alexissantos it's not that bad. Raspberry PI suffers a bit with flutter animations. For example, shade colors / highlight color changing when you press and hold a button. I would recommend creating your own animations, without fade in/out effect. I haven't explored much yet, my GPIO communication still written in Java and using channels (https://flutter.io/platform-channels/) to do the integration.
