### ISSUE TITLE
The Play Store has some fairly restrictive policies over SMS and call permissions:

### ISSUE THREAD

**Issue by dsourav** [flutter/flutter#70995]
The Play Store has some fairly restrictive policies over SMS and call permissions:

https://play.google.com/about/privacy-security-deception/permissions/

my guess is this has something to do with the `RECEIVE_SMS` permission - do you really need it?

If what you're trying to do is invite users to your app, you may be better off with the share plugin, which will launch the platform's share functionality:

https://pub.dev/packages/share

_Originally posted by @MichaelMarner in https://github.com/flutter/flutter/issues/32594#issuecomment-491657383_

**Comment by iapicca** [comment]
@dsourav 
this issue doesn't seem to be a feature request or a bug report,
but just a question regarding [share](https://pub.dev/packages/share) plugin.
I recommend to ask this type of question on stackoverflow rather than on flutter's github repo

**Comment by MichaelMarner** [comment]
I don't understand why a suggestion I made on someone else's issue over a year ago has been turned into a new issue here. Suggest closing.

**Comment by iapicca** [comment]
@MichaelMarner 
the issue you are referencing was closed by the reporter himself;
what suggestion, that regards flutter, are you making?

**Comment by MichaelMarner** [comment]
The original comment on _this_ issue is a post I made on a different issue, as linked in the initial comment. I do not know why my comment from over a year ago has now been used in this new issue.

I'm only here because I was tagged into this issue by the OP.

**Comment by iapicca** [comment]
I'm sorry @MichaelMarner I completely misread your [comment](https://github.com/flutter/flutter/issues/70995#issuecomment-731697174) 
I agree with you, this issue should be closed  as does not offer any concrete feature request, proposal or reporting any bug
