### ISSUE TITLE
Many of our components draw outside their paintBounds

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#71]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:25 GMT_
_Originally opened as https://github.com/flutter/engine/issues/26_

----

_From @Hixie on July 14, 2015 17:22_

You can now easily tell what components paint outside their bounds by turning on debugPaintBoundsEnabled in sdk/lib/base/debug.dart. I noticed at least the following in the stocks app:

 - radio buttons
 - switches
 - anything with shadows, including drawer, popup menu, toolbar, floating action button, dialog
 - circles in the stock row

/cc @collinjackson @iansf 

_Copied from original issue: domokit/mojo#321_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 28, 2015 at 02:23 GMT_

----

@abarth Any update on whether we are going to drop the paintBounds concept?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Wednesday Oct 28, 2015 at 02:59 GMT_

----

We can remove paintBounds.  There's some chance we'll need it later, but if that happens we can add it back.  We should still make most things paint in bounds so they'll hit test and clip correctly.

**Comment by eseidelGoogle** [comment]
Sounds like we can close this?

**Comment by abarth** [comment]
Sure, but we should file a code health bug to remove `paintBounds` from the system.

**Comment by Hixie** [comment]
And we should probably still verify that the widgets (switch in particular) stay within their bounds. Right now a number of them overflow.
