### ISSUE TITLE
Convert jpg to bytes wrongly.

### ISSUE THREAD

**Issue by nailcankara** [flutter/flutter#71004]
I have photo 96x96 resolution.

I am reading this jpg file using this code
`decodeJpg(File(jpgfile.path).readAsBytesSync());`

Then I use `readBytes().toList()` and I see my photo has 4 channel which is RGBA. How I realize? I tried to reshape it (96,96,3) I got error. But If I resize it to (96,96,4), there is no problem. My bytes are like this [[[110,47,85,255],[64,43,101,255],....]] 

My tflite model gets (1,96,96,3) as input. If I have (96,96,3) I can reshape it. How can I get rid of the 4th channel?

**Comment by jonahwilliams** [comment]
You are reading encoded image bytes, not color channel values. You need to decode the JPG first

The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community.

**Comment by nailcankara** [comment]
This is for those who suffer like me:

I solved the issue. I thought there was no parameter for `readBytes()` but there is a optional parameter which is format. `getBytes(format: Format.rgb)` I put this parameter and my issue is solved.
