### ISSUE TITLE
i can't find a way to display an array field into a listtile with flutter

### ISSUE THREAD

**Issue by cherkaouijamal57** [flutter/flutter#71002]
I managed to get the values of the array field thanks to the print method  but still I cant display data in a list view;

can you help me with this, also, I am wondering if there is a way to have full documentation on how to use flutter with firebase,

I am asking because I found it very difficult to find a solution on the internet for that problem and many others, for example how to export firestore collection to a CSV.
`class ListClients2 extends StatefulWidget {

@override
_ListClients2 createState() => _ListClients2();
}

class _ListClients2 extends State<ListClients2> {

@override
Widget build (BuildContext context) {

return Scaffold(
body: FutureBuilder(
future: getList(),

builder: (context, AsyncSnapshot<List<dynamic>> snapshot) {
if (snapshot.connectionState == ConnectionState.waiting) {
return CircularProgressIndicator();
} else {
return Center(
child: ListView.builder(
padding: const EdgeInsets.only(bottom: 20.0),
scrollDirection: Axis.vertical,
shrinkWrap: true,
itemCount: snapshot.data.length,
itemBuilder: (context, index) {

return Center(
child: ListTile(
title: Text(
snapshot.data[0].data), //snapshot data should dispaly in this text field
),
);
}),
);
}
},
)

);

}
Future<List<dynamic>> getList() async {
var firestore = Firestore.instance;

DocumentReference docRef = firestore.collection('admin_users').document(idUser);

// ignore: missing_return
return docRef.get().then((datasnapshot) {
if (datasnapshot.exists) {
List<dynamic> info = datasnapshot.data['clients'].toList();
print('#');
print(info); //this line prints [aa, aghshs, fffg, fug, ghh, fggg, ghhh]
print(info.length); //this line prints 7
return info;
}
});
}
![erreur compli array in a list](https://user-images.githubusercontent.com/74839381/99888780-862bfb80-2c4f-11eb-834f-bf171949ccc0.PNG)
`

**Comment by cherkaouijamal57** [comment]
PLEASE ANY HELP

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
