### ISSUE TITLE
[Bad state: Future already completed] run 'flutter doctor -v' or other commands failed

### ISSUE THREAD

**Issue by Rino-T** [flutter/flutter#71006]
## Steps to Reproduce

I'm sure it will only be reproduced on my personal Mac Book Pro. It doesn't seem to work on my company's iMac, Windows, or a friend's Mac.

The same problem occurs not only with `flutter docto`r, but also with other commands such as `flutter build`, `flutter pub upgrade`, etc.

## Logs

```
chibatoshinorinoMacBook-Pro:tools chibatoshinori$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale ja)
    • Flutter version 1.22.4 at /Users/chibatoshinori/tools/flutter
    • Framework revision 1aafb3a8b9 (8 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

⣻Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
chibatoshinorinoMacBook-Pro:tools chibatoshinori$
```

```
chibatoshinorinoMacBook-Pro:record_book chibatoshinori$ flutter build ios
Unhandled exception:                                                    
Bad state: Future already completed                                     
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)    
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Running "flutter pub get" in record_book...                             
pub get failed (255; #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12))
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
chibatoshinorinoMacBook-Pro:record_book chibatoshinori$ 
```

* This problem occurred after updating the Mac OS to Big Sur.
* I hadn't updated my version of Flutter, so the version of Flutter was 1.17.x when I first saw this problem (I forget the minor version)
* I’m not behind proxy.
* I removed the entire Flutter directory and reinstalled the latest version of Flutter (1.22.4), but no improvement was made.
* I didn't see the same problem on my company's iMac and Windows.
* I'm in Japan.

### related issue
* https://github.com/flutter/flutter/issues/40734

**Comment by darshankawar** [comment]
@Rino-T 
Please see below issues and corresponding solutions in comments that helped them to resolve the issue:

https://github.com/flutter/flutter/issues/70596
https://github.com/flutter/flutter/issues/68999

**Comment by Rino-T** [comment]
@darshankawar 
Thank you!
I quit Kaspersky, Flutter is now working properly as well.

**Comment by glofru** [comment]
Sorry for the delay in answering but I covered a total different part and I did not see you messages.

The problem fixed on itself but there is something strange that I am noting now, that is that sometimes camera package works and sometimes no. So actually the problem is not totally solved, I was too hasty to close it.

Definitely I cannot understand why, but sometimes it works and others does not.

**Comment by erperejildo** [comment]
I have no antivirus running. `flutter config --no-analytics` didn't help either
