### ISSUE TITLE
Fetch Json data working differently for web and android app

### ISSUE THREAD

**Issue by RDXV** [flutter/flutter#71039]
## Steps to Reproduce

1. Run the below code in web and android App
```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  // Future<Album> newAlbum;
  List drinks = List();
  bool loading = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    newFetch();
    // newAlbum = fetchAlbum();
    // print('newAlbum is $newAlbum');
  }

  newFetch() async {
    setState(() {
      loading = true;
    });
    final res = await http.get('https://jsonplaceholder.typicode.com/albums');
    if (res.statusCode == 200) {
      drinks = jsonDecode(res.body) as List;
      print(drinks);
// HERE is the main PROBLEM as mentioned below
      setState(() {
        loading = false;
      });
      // Its a list by default though
    } else {
      throw Exception('Cannot load the Album data');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData.dark(),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data example'),
        ),
        body: Center(
            child: ListView.builder(
          itemCount: drinks.length,
          itemBuilder: (context, index) {
            return Padding(
              padding: EdgeInsets.all(8),
              // child: Text(drinks[index]),
              child: Text(drinks[index]['title'] + ' $index'),
            );
          },
        )),
      ),
    );
  }
}
```
 -->

When I print drinks variable in the WEB APP all the drinks get printed with their respective data whereas in Android App only some part of data is printed, When I made the listView builder for android app it showed all the data both in mobile and emulator and showed part of the drinks data when print('drinks') was done as mentioned in the newFetch() function.

**Expected Outcome**(Present Outcome in WebApp)
![webapp](https://user-images.githubusercontent.com/56734311/99902614-15cfb980-2ce5-11eb-8f05-4dc837979013.png)

**Present Outcome**(In Android real and emulator device)
![apk](https://user-images.githubusercontent.com/56734311/99902637-444d9480-2ce5-11eb-93cc-fd62476aa2ef.png)

Flutter Doctor:
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (4 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\VARUN ARORA\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\VARUN ARORA\AppData\Local\Programs\Microsoft VS Code   
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Redmi Note 7 (mobile) • b7b7c4e0   • android-arm64  • Android 10 (API 29)  
    • Web Server (web)      • web-server • web-javascript • Flutter Tools        
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)            • edge       • web-javascript • Microsoft Edge 86.0.622.69

**Comment by iapicca** [comment]
@RDXV 
are you getting the same output running the app from terminal instead of `VScode`?

**Comment by RDXV** [comment]
> @RDXV
> are you getting the same output running the app from terminal instead of `VScode`?

Yes. Same output for android app as in the picture above is what I am getting from terminal too. Just to mention that earlier I was working with the beta build which did not have null safety and now since it has, the http package does not have sound null safety because of which I had to go back to stable build to try the app from terminal. I dont think it has something related to it but something related to flutter or dart for fetching Json data from internet.

**Comment by darshankawar** [comment]
Issue replicable on latest master also.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.344, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-8.0.pre.344 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision de56c6ad72 (15 hours ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (6 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!


[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (5 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!


```

</details>

**Comment by jason-simmons** [comment]
Try using `debugPrintThrottled` if the printed string is being truncated by the log reader:

`debugPrintThrottled(drinks.toString(), wrapWidth: 100);`

See https://api.flutter.dev/flutter/foundation/debugPrintThrottled.html

**Comment by RDXV** [comment]
Yes. After using the debugPrintThrottled(drinks.toString()); function instead of print statement the problem was solved and output same as that of web app but before closing the issue I would like this problem to be solved as it is not easy to find out what the problem was because I was printing the same thing in web app and output was different. Thanks @jason-simmons for solving it for me.

**Comment by jmagman** [comment]
@jason-simmons should this go to engine? dart?  Not sure what triage labels to throw on this.

**Comment by ferhatb** [comment]
@jmagman suggest filing this bug on Dart SDK and closing this one.

**Comment by jmagman** [comment]
@ferhatb  I don't have write permissions on dart-sdk, are you able to `Transfer issue`?

**Comment by jason-simmons** [comment]
I don't think this is a Dart SDK issue.  The tool's log reader or the target platform's logging service may not be able to keep up with a large amount of log data.  Flutter provides `debugPrintThrottled` to help in this situation.

I'd suggest closing this as WAI.
