### ISSUE TITLE
my code doesnot work after using firebase  code

### ISSUE THREAD

**Issue by karandhami2054** [flutter/flutter#71036]
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';

import 'package:loginapp10/loginScreen.dart';
import 'package:loginapp10/main.dart';
import 'package:loginapp10/mainscreen.dart';

class RegistrationScreen extends StatefulWidget {
  static const String idScreen = "register";
  @override
  _RegistrationScreenState createState() => _RegistrationScreenState();
}

class _RegistrationScreenState extends State<RegistrationScreen> {
  TextEditingController emailTextEditingController = TextEditingController();
  TextEditingController contactTextEditingController = TextEditingController();
  TextEditingController nameTextEditingController = TextEditingController();
  TextEditingController passwordTextEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(12.0),
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                SizedBox(height: 150.0),
                Text(
                  'It is Registration page',
                ),
                Padding(padding: EdgeInsets.only(left: 20.0)),
                TextField(
                  controller: nameTextEditingController,
                  keyboardType: TextInputType.emailAddress,
                  decoration: InputDecoration(
                      labelText: "Name",
                      labelStyle: TextStyle(
                        fontSize: 14.0,
                      ),
                      hintStyle: TextStyle(
                        color: Colors.grey,
                        fontSize: 10,
                      )),
                  style: TextStyle(fontSize: 14.0),
                ),
                SizedBox(
                  height: 12.0,
                ),
                TextField(
                  controller: emailTextEditingController,
                  keyboardType: TextInputType.emailAddress,
                  decoration: InputDecoration(
                      labelText: "Email",
                      labelStyle: TextStyle(
                        fontSize: 14.0,
                      ),
                      hintStyle: TextStyle(
                        color: Colors.grey,
                        fontSize: 10,
                      )),
                  style: TextStyle(fontSize: 14.0),
                ),
                SizedBox(height: 12.0),
                TextField(
                  controller: contactTextEditingController,
                  keyboardType: TextInputType.phone,
                  decoration: InputDecoration(
                      labelText: "Contact no.",
                      labelStyle: TextStyle(
                        fontSize: 14.0,
                      ),
                      hintStyle: TextStyle(
                        color: Colors.grey,
                        fontSize: 10,
                      )),
                  style: TextStyle(fontSize: 14.0),
                ),
                SizedBox(height: 12.0),
                TextField(
                  controller: passwordTextEditingController,
                  obscureText: true,
                  decoration: InputDecoration(
                      labelText: "Password",
                      labelStyle: TextStyle(
                        fontSize: 14.0,
                      ),
                      hintStyle: TextStyle(
                        color: Colors.grey,
                        fontSize: 10,
                      )),
                  style: TextStyle(fontSize: 14.0),
                ),
                SizedBox(
                  height: 12.0,
                ),
                RaisedButton(
                  onPressed: () {
                    // print('register button is pressed');
                    if (nameTextEditingController.text.length < 3) {
                      flutterToastDisplayMessage(
                          'Enter length grater than 3', context);
                    } else if (emailTextEditingController.text.isEmpty) {
                      flutterToastDisplayMessage(
                          'Enter your emai address', context);
                    } else if (!emailTextEditingController.text.contains("@")) {
                      flutterToastDisplayMessage(
                          "Enter correct email address", context);
                    } else if (contactTextEditingController.text.isEmpty) {
                      flutterToastDisplayMessage(
                          "Enter your phone number", context);
                    } else if (passwordTextEditingController.text.length < 7) {
                      flutterToastDisplayMessage(
                          "Enter password greater than 7", context);
                    }
                    // registernewUser(context);
                  },
                  color: Colors.pink,
                  textColor: Colors.white,
                  child: Container(
                    height: 50.0,
                    child: Center(
                      child: Text(
                        "Create Acount",
                        style: TextStyle(fontSize: 14.0),
                      ),
                    ),
                  ),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(24.0)),
                ),
                FlatButton(
                    onPressed: () {
                      // print('Click ');
                      // Navigator.pushReplacement(
                      //     context,
                      //     MaterialPageRoute(
                      //         builder: (context) => LoginScreen()));

                      Navigator.pushNamedAndRemoveUntil(
                          context, LoginScreen.idScreen, (route) => false);
                    },
                    child: Text('Alrready  have an accout? Login  Here.')),
              ],
            ),
          ),
        ),
      ),
    );
  }

  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
  registernewUser(BuildContext context) async {
    final User user = (await _firebaseAuth
            .createUserWithEmailAndPassword(
                email: emailTextEditingController.text,
                password: passwordTextEditingController.text)
            .catchError((errMsg) {
      flutterToastDisplayMessage("Error:" + errMsg.toString(), context);
    }))
        .user;

    if (user != null) {
      Map userDataMap = {
        "name": nameTextEditingController.text.trim(),
        "email": emailTextEditingController.text.trim(),
        "contact": contactTextEditingController.text.trim(),
      };
      usersRef.child(user.uid).set(userDataMap);
      flutterToastDisplayMessage("user created successfully", context);
      Navigator.pushNamedAndRemoveUntil(
          context, MainScreen.idScreen, (route) => false);
    } else {
      flutterToastDisplayMessage("User has not been created.", context);
    }
  }
}

flutterToastDisplayMessage(String message, BuildContext context) {
  Fluttertoast.showToast(msg: message);
}

**Comment by iapicca** [comment]
@karandhami2054 
issue with firebase should be opened [here](https://github.com/FirebaseExtended/flutterfire/issues) and not in flutter's repo

**Comment by darshankawar** [comment]
@karandhami2054 
As mentioned above, please consider opening this issue in Firebase [repo](https://github.com/FirebaseExtended/flutterfire/issues). Closing from here.
