### ISSUE TITLE
Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

### ISSUE THREAD

**Issue by ahmedeltigani** [flutter/flutter#71037]

**Comment by iapicca** [comment]
@ahmedeltigani 
can you provide your `flutter doctor -v` your `flutter run -v` and a minimal reproducible code sample

**Comment by darshankawar** [comment]
@ahmedeltigani 
Please provide above requested details.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
