### ISSUE TITLE
Flutter command not found

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#71047]
Flutter team really need to make it easy to add flutter command to the $PATH. I have tried every possible solution and I still get it to work. Maybe add this in the installation. Once the installation is completed then ask the user to add the flutter to the path.

**Comment by iapicca** [comment]
@azamsharp 
please `update your path`,  here are the instructions for 
[linux](https://flutter.dev/docs/get-started/install/linux#update-your-path), [mac](https://flutter.dev/docs/get-started/install/macos) and [windows](https://flutter.dev/docs/get-started/install/windows)
if the issue persist provide your `flutter doctor -v`

**Comment by azamsharp** [comment]
I followed all the instructions it does not recognize the flutter command. Flutter doctor does not work since flutter command was not found

**Comment by iapicca** [comment]
@azamsharp 
it's most likely an issue with your set-up rather than an issue with flutter, 
regardless, can you provide info about your OS

**Comment by darshankawar** [comment]
@azamsharp 
Please double check / re-visit installation [steps](https://flutter.dev/docs/get-started/install/) per your platform and confirm if you have followed all of them.

**Comment by hello-addweb** [comment]
1. first flutter upgrade or flutter upgrade --force
2.Restart the Android studio or editor
3.and set the your flutter downloaded sdk path location
like this
PATH="$PATH://Users/Project/development/flutter/bin/"

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
