### ISSUE TITLE
Support for borderless windows

### ISSUE THREAD

**Issue by mengrayan** [flutter/flutter#71042]
Would it be possible to add support for borderless window mode on desktop? Thanks!

**Comment by darshankawar** [comment]
Leaving [this](https://stackoverflow.com/a/63399864) here for reference.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/31373

**Comment by Rayan749** [comment]
Thanks! #31373 is helpful.
