### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

### ISSUE THREAD

**Issue by FromJeju** [flutter/flutter#71045]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_360: ^0.1.5
  font_awesome_flutter: ^8.10.0
  http: ^0.12.2
  json_annotation: ^3.1.1
  google_maps_flutter: ^1.0.6
  i18n: ^1.2.2
  flutter_map_marker_popup: ^0.1.4
  geolocator: ^5.3.2+2
  flutter_svg: ^0.18.0
  select_dialog: ^1.2.1
  pull_to_refresh: ^1.6.3
  intl: ^0.16.1
  provider: ^4.3.2+2
  share: ^0.6.5+4  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  flutter_launcher_icons: ^0.8.1

video_player_360 must be used.

[✓] Flutter (Channel master, 1.24.0-8.0.pre.180, on Mac OS X 10.15.5 19F101 darwin-x64, locale ko-KR)
    • Flutter version 1.24.0-8.0.pre.180 at /Users/lonnie/Applications/flutter
    • Framework revision 84a8bd3f5a (12 days ago), 2020-11-10 05:21:14 -0800
    • Engine revision e50ac2c552
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/lonnie/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

</details>

**Comment by darshankawar** [comment]
@FromJeju 
See [this](https://github.com/flutter/flutter/issues/39470) issue and corresponding comments and check if any of those are applicable in your case.

**Comment by FromJeju** [comment]
> @FromJeju
> See [this](https://github.com/flutter/flutter/issues/39470) issue and corresponding comments and check if any of those are applicable in your case.

I've already checked.
The document is not helpful.

**Comment by darshankawar** [comment]
@FromJeju 
You may need to go through each of your plugins (especially 3rd party) to see if they use `UIWebView` and act accordingly.

**Comment by TahaTesser** [comment]
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/60687
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
