### ISSUE TITLE
TextField controlled controller.addListener(() gets called multiple time after using the controller.clear

### ISSUE THREAD

**Issue by masoudpaidar** [flutter/flutter#71048]
TextField controlled controller.addListener(() gets called multiple time after using the controller.clear.
in this when the condition in the if statement is correct the body of if is Execute twice and print the Hello world twice

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController controller = new TextEditingController();
  change() {
    String text = controller.text;
    if (text.isNotEmpty) {
      if (text.length >= 5) {
        print("Hello world");
        controller.clear();
      }
    }
  }

  @override
  void initState() {
    controller.addListener(change);
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.only(left: 50, right: 50),
          child: TextFormField(
            controller: controller,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}

and my flutter doctor  result is:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by pedromassangocode** [comment]
Hi @masoudpaidar  
This may be caused by your implementation because when you update the controller's content inside of a listener it will call the listener again.

If you want to clear the text field's content after it changed it is recommended to use the onChanged callback:

```dart
class _MyHomePageState extends State {
  TextEditingController controller = new TextEditingController();
  void change(String text) {
    if (text.isNotEmpty) {
      if (text.length >= 5) {
        print("Hello world");
        controller.clear();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.only(left: 50, right: 50),
          child: TextFormField(
            controller: controller,
            onChanged: change,
          ),
        ),
      ),
    );
  }
}
```

**Comment by masoudpaidar** [comment]
thanks @pedromassangocode
 i do the this solution but i have the same problem 
and this is not work

**Comment by pedromassangocode** [comment]
Hi @masoudpaidar 
Make sure you have the latest version of Flutter!

**Comment by masoudpaidar** [comment]
HI @pedromassangocode
i use the pinput: ^0.2.4 package and i thinks this package have this issues

**Comment by pedromassangocode** [comment]
You may want to file an issue on that package's repository!

**Comment by masoudpaidar** [comment]
yes i should  to report  this issue and its take a lot of time of me
thanks @pedromassangocode for your help
