### ISSUE TITLE
BottomNavigationBar has no option to remove tooltip or change the tooltip from its icon label [Web] [Desktop]

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#71049]
BottomNavigationBar has no API for enabling/disabling its tooltips.  Widgets that implement and use tooltips must also include an API that can be used to set the tooltip string to a value that differs from its default tooltip string(s) and to completely disable its tooltips. **BottomNavigationBar** now always shows its icon label as a tooltip on Web and Desktop, which seldom adds any value to the often already shown icon label.

Then newer `BottomNavigationBar` that uses `BottomNavigationBarItem` that deprecates `title` in favor of `label` is **currently not very desktop/web friendly** when it comes to providing control over its tooltips. It misbehaves to the extent that it **is an issue**.

1) There is no way to turn of the tooltips!
2) There is no way to provide a tooltip label that differs from the icon label!

**Q:** What value does the additional tooltip label that is identical to the already shown icon label provide? 

![bottom-tooltip](https://user-images.githubusercontent.com/39990307/94720939-c791e000-035d-11eb-8694-1c6783a08206.gif)

If there was a way to via the API e.g. as a new property in `BottomNavigationBarItem` to provide a separate `tooltipLabel` that could provide some additional info in addition to the already visible string in the icon label, then its tooltips might be made more useful. 

For `BottomNavigationBarItem` it could e.g. be added so that it uses `label` for tooltips by default and a separate `tooltipLabel` value if one is provided. There still needs to be a way to turn of the tooltips as you might not want to have tooltips at all on desktop and web when using the widget.

>Many web and desktop may want to implement a global user controllable feature that enables and disables tooltips in the app entirely. Tooltips are nice for beginners when you are not familiar with the app, but when you know the app they tend to get annoying and get in the way of using the app. Providing users a feature where you can turn off tooltips is a nice way to increase the UX for more experienced users of your app.
>Currently many widget in Flutter that uses tooltips make it impossible (or at least more difficult than it needs to be) to implement this feature as they have no way of turning off tooltips at all. The `BottomNavigationBar` is one critical widget that fails in this respect.

This example with the bottom navigation bar is based on the API docs sample:
https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html

Where the deprecated (in beta channel and higher) `title` was replaced with `label`. On web and desktop platforms this results in a bottom navigation bar where there always is a rather useless extra tooltip that is identical to the label, with no apparent way of turning it off in the API or changing the tooltip label to something else. The only way to fix this now seems to be to fork both `BottomNavigationBarItem` and `BottomNavigationBar` and make custom versions of them, which from a maintenance point of view is less than ideal.

Example `BottomNavigationBar` code snippet: 
https://gist.github.com/rydmike/e97d29789886b9b406618d851d765fff

Can be tried in DartPad here: 
https://dartpad.dev/e97d29789886b9b406618d851d765fff

![image](https://user-images.githubusercontent.com/39990307/99915115-55f56300-2d0a-11eb-9b21-73b656a55b23.png)

---

## Related issues

The `BottomNavigationBarItem` case is just one example case, there might be more Widgets with similar tooltip issues on web and desktop. One found related sister topic is the similar issue with `PopupMenuButton` https://github.com/flutter/flutter/issues/60418.

## Background

This issue was previously included as the 2nd part of the new feature proposal **"Global enable/disable of tooltips in Flutter apps and provide API control over widget tooltips"** https://github.com/flutter/flutter/issues/66993. I removed this issue part from that proposal and added this specific topic as a more actionable issue instead, just mentioning it and also its related sister issue https://github.com/flutter/flutter/issues/60418 as case examples where the lack of proper tooltip APIs are an issue. 

The proposal https://github.com/flutter/flutter/issues/66993 itself is a bit more broad and includes a suggestion of providing an built in app level toggle to enable and disable tooltips.

----

<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Users\mryds\fvm\versions\beta
    • Framework revision 022b333a08 (4 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Nexus 7 (mobile) • 0a99f5e8   • android-arm    • Android 6.0.1 (API 23)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.41

• No issues found!
```
</details>

**Comment by rydmike** [comment]
@mariamhas FYI

**Comment by pedromassangocode** [comment]
Reproducible on master as well.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.344, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.344 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision de56c6ad72 (16 hours ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.198

• No issues found!

```
</details>

**Comment by yash1200** [comment]
Possible Solution : 
Adding a `showTooltip` bool property in BottonNavBar
Adding a `tootTip` string property in BottomNavBarItem which will be shown if `showTooltip` is true.
@pedromassangocode I want to work on this one.

**Comment by rydmike** [comment]
Thanks @pedromassangocode it is indeed a correct observation that it is now also reproducible on master.

Also since with the current **stable** version, the usage of `title` is also preferred over `label`, the issue now also applies to stable.

On stable the issue is perhaps not as obvious, as long as we can only build for Android and iOS on stable, and since a long press is required to show a tooltip on a device, the tooltips do not present themselves as easily and are seldom in the way or repetitive, even if the the icon label and tooltip are identical.

An easy way to disable tooltips on devices could still have it usage on devices too, especially since iOS does not have the concept of tooltips at all, thus if you want to use a Material component on iOS that has tooltips, then being able to hide/disable the platform foreign tooltips elements might also be useful there.

That being said, not being able to disable tooltips is more of an issue on Web and Desktop platforms. Currently the only way to hide the tooltips on ´BottomNavigationBar` is to use it with the `BotomNavigationBarItem` deprecated `title` property that takes a Widget based label and not a String label, and that has no default tooltip, unless you build one into the the used Widget yourself.

---

Thanks @yash1200 for offering to pick up the ball on this. Your suggestion is exactly what I would like to see on this particular case and Widget as well. Plus with backwards compatible default behavior, it would just be additive and not break anything.

Then maybe one day when all Widgets that have similar String based built in tooltips and implement a `showTooltip` flag, that flag could be connected to an optional MaterialApp level flag for showing hiding tooltips, that sets the current app wide default for all Widgets that have built in tooltips. See concept idea and suggestion here: https://github.com/flutter/flutter/issues/66993. 

Until then you can of course easily implement such a feature yourself, as long as the individual Widgets you use support enabling/disabling the tooltips. The proposal https://github.com/flutter/flutter/issues/66993 is more about supporting such a feature out of the box and making coding with Flutter even more delightful than it already is.

**Comment by rydmike** [comment]
An interesting observation about the `BottomNavigationBar` is also the fact that it currently shows tooltips that are identical to already visible icon labels and that this does not adhere to the Material guidelines concerning tooltip usage: 

![image](https://user-images.githubusercontent.com/39990307/100102670-9b31a600-2e6c-11eb-9796-69420185f8f9.png)
here: https://material.io/components/tooltips#placement

**Comment by sanekyy** [comment]
Same feature request.

**Comment by utkudenis** [comment]
Hi, we want to decrease infos ( warnings) in VSCode but we don't want to show tooltip.Therefore, as I understand, you suggest that usage of title but dart give warning because of the title usage :( , How can we decrease infos :(

**Comment by yash1200** [comment]
Use label with `tooltip = ''` (empty string), this will work.

**Comment by utkudenis** [comment]
> @utkudenis
> Use label with `tooltip = ''` (empty string), this will work.
bu it shows empty tooltip on long touch

**Comment by yash1200** [comment]
@utkudenis Share your flutter doctor as well the code.
