### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s) (replacement): Must not be null

### ISSUE THREAD

**Issue by mengheangrat** [flutter/flutter#71057]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s) (replacement): Must not be null
```
#0      _StringBase.replaceAll (dart:core-patch/string_patch.dart:637:30)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:856:8)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:944:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1005:5)
#4      generateLocalizations (package:flutter_tools/src/build_system/targets/localizations.dart:66:9)
#5      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:123:5)
#6      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#8      new Future.sync (dart:async/future.dart:223:31)
#9      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#10     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#12     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:64:30)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:949:13)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZoned (dart:async/zone.dart:1550:10)
```
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-KH)
    • Flutter version 1.22.3 at /Users/mengheang/.flutter/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mengheang/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • B4FC1842-3F92-4458-855E-870DBC700BDE • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Parker is not connected. Xcode will continue when Parker is connected. (code
      -13)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
### Plugins
connectivity-0.4.8+1
connectivity_macos-0.1.0+1
devicelocale-0.3.3
flutter_facebook_auth-1.0.1
flutter_libphonenumber-0.3.11
flutter_plugin_android_lifecycle-1.0.11
flutter_secure_storage-3.3.1+1
fluttertoast-7.1.1
geocoder-0.2.1
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-1.0.6
google_sign_in-4.5.6
google_sign_in_web-0.9.2
location_permissions-3.0.0+1
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
shared_preferences_windows-0.0.1+3
sqflite-1.3.2+1

**Comment by jmagman** [comment]
Crashing line is `locale` replacement:
https://github.com/flutter/flutter/blob/8dfd42f6b7194598eb93985fbbd7eaf58588f918/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L856
#53374

**Comment by jmagman** [comment]
\cc @shihaohong

**Comment by shihaohong** [comment]
Hi @mengheangrat could you share a minimal reproducible sample here? What particular use case causes this failure?

**Comment by marchellodev** [comment]
I believe that the absence of `"@variable": {}` for every `"variable": "translation"` in `.arb` files causes the crash

**Comment by ram231** [comment]
I just encountered one of these.  and i'm using artemis client package. everything seems okay except i get the same error. does this happen due to reserved keywords?

**Comment by jmagman** [comment]
> I just encountered one of these. and i'm using artemis client package. everything seems okay except i get the same error. does this happen due to reserved keywords?


> could you share a minimal reproducible sample here? What particular use case causes this failure?
> 
> Edit: Judging from the clue that the crashing line is `locale` replacement, it has something to do with how the locale/language is defined in the arb file when using the gen-l10n tool

**Comment by ram231** [comment]
I'll try to reproduce. I can't say that it has something to do with artemis. but this one query gives me errors when it gave me a value of null.

when I tried it this morning, it works now. the problem with my end might be that there are null values that my package won't allow to be fetched.

**Comment by jmagman** [comment]
@mengheangrat This is a tools crash we'd like to track down and fix.  Please keep open for investigation.

**Comment by ram231** [comment]
I'd like to give feedback regarding this issue. It seems that the  [json_serializable](https://pub.dev/packages/json_serializable) occurs an error when a date is nullable from the REST API and cannot parse it.
From: 
```dart
DateTime dateFromJson(String dateTime){
   return DateTime.parse(dateTime);
}
```
To:
```dart
DateTime dateFromJson(String dateTime){
  if(dateTime == null){
   /// return something;
   }
  return DateTime.parse(dateTime);
}
```

**Comment by yuyenkan** [comment]
I had also experience this issue when the `filename` or `@@locale` value is not in the iso language code. eg: Japanese I put `jp` and it is `ja` in iso.

**Comment by danagbemava-nc** [comment]
Hi @jmagman, can this be considered fixed? The code for `describeLocale` method has gone through some changes. See https://github.com/flutter/flutter/blob/ffea970ce8c5513f28f8058ac4714f31e535fd84/packages/flutter_tools/lib/src/localizations/localizations_utils.dart#L196

Also, if I create a .arb file with the wrong locale I get this error

```
Generating synthetic localizations package failed with 1 error:

Error: The following .arb file's locale could not be determined: 
/Users/nexus/projects/nevercode/bot/lib/l10n/app_js.arb 
Make sure that the locale is specified in the file's '@@locale' property or as part of the filename (e.g. file_en.arb)
```

If I add the locale key but I specify it incorrectly, I get this error (from the current describeLocale method)

```
Generating synthetic localizations package failed with 1 error:

Error: "js" is not a supported language code.
See https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry for the supported list.
```

So far, the tool hasn't crashed for me.
