### ISSUE TITLE
[web]: Getting "git: git@github.com: Permission denied (publickey)" error, while deploying flutter web application using docker file.

### ISSUE THREAD

**Issue by rohitTQ** [flutter/flutter#71056]
I have a complex scenario and need help to solve this issue.

 
Issue -

 
we have implemented multi-layer architecture where we are integrating modules through git repository adding dependencies in .yaml file.

 
Now when we run this project on mobile apps, it deploys smoothly, whereas when I try to deploy the same for Web application through docker I'm unable to access the git repo for the same.

 
One more challenge is, the git url is private and we cannot grant access to public due to which we are facing this issue while using through docker.

 
How can we resolve this without changing the permissions on git repository.?

 
Error :
#14 5.078 git: git@github.com: Permission denied (publickey).
#14 5.081 git: fatal: Could not read from remote repository.
#14 5.084 git: Please make sure you have the correct access rights
#14 5.085 git: and the repository exists.

**Comment by hello-addweb** [comment]
You need to generate public/private key set : 
Please follow this [answer](https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git).

**Comment by rohitTQ** [comment]
@hello-addweb We are using public and private key set, but we are facing following error.

Error : 
=> ERROR [build-env 11/15] RUN ssh -vT git@github.com                                                                                       0.9s
------                                                                                                                                            
 > [build-env 11/15] RUN ssh -vT git@github.com:                                                                                                  
#16 0.242 OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019                                                                            
#16 0.243 debug1: Reading configuration data /etc/ssh/ssh_config                                                                                  
#16 0.243 debug1: /etc/ssh/ssh_config line 19: Applying options for *                                                                             
#16 0.246 debug1: Connecting to github.com [13.234.176.102] port 22.                                                                              
#16 0.266 debug1: Connection established.
#16 0.267 debug1: SELinux support disabled
#16 0.267 debug1: identity file /root/.ssh/id_rsa type -1
#16 0.268 debug1: identity file /root/.ssh/id_rsa-cert type -1
#16 0.268 debug1: identity file /root/.ssh/id_dsa type -1
#16 0.268 debug1: identity file /root/.ssh/id_dsa-cert type -1
#16 0.268 debug1: identity file /root/.ssh/id_ecdsa type -1
#16 0.269 debug1: identity file /root/.ssh/id_ecdsa-cert type -1
#16 0.269 debug1: identity file /root/.ssh/id_ed25519 type -1
#16 0.270 debug1: identity file /root/.ssh/id_ed25519-cert type -1
#16 0.270 debug1: identity file /root/.ssh/id_xmss type -1
#16 0.270 debug1: identity file /root/.ssh/id_xmss-cert type -1
#16 0.271 debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
#16 0.649 debug1: Remote protocol version 2.0, remote software version babeld-c863b32e
#16 0.650 debug1: no match: babeld-c863b32e
#16 0.650 debug1: Authenticating to github.com:22 as 'git'
#16 0.650 debug1: SSH2_MSG_KEXINIT sent
#16 0.651 debug1: SSH2_MSG_KEXINIT received
#16 0.651 debug1: kex: algorithm: curve25519-sha256
#16 0.651 debug1: kex: host key algorithm: rsa-sha2-512
#16 0.651 debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
#16 0.651 debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
#16 0.653 debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
#16 0.861 debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
#16 0.862 debug1: read_passphrase: can't open /dev/tty: No such device or address
#16 0.862 Host key verification failed.
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c ssh -vT git@github.com]: runc did not terminate sucessfully

**Comment by iapicca** [comment]
@rohitTQ this issue seems to be related to git and github rather than flutter,
I should probably be asked on stackoverflow.com

**Comment by pedromassangocode** [comment]
Right, this does not seems related to Flutter.
