### ISSUE TITLE
[video_player] Playing video from network asset on Android throws an exception

### ISSUE THREAD

**Issue by smedic** [flutter/flutter#71055]
I see this error when trying to play a video file from URL (network resource).
I saw somebody said it's fixed but I still can reproduce it on video_player: ^1.0.1

'`package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true., stack: #0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39) 
I/flutter (22365): #1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5) 
I/flutter (22365): #2 new PlatformException (package:flutter/src/services/message_codec.dart:111:15) 
I/flutter (22365): #3 VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205:13) 
I/flutter (22365): <asynchronous suspension>
I/flutter (22365): #4 MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42) 
I/flutter (22365): #5 VideoPlayerController.initialize (package:video_player/video_player.dart:282:45)`

[✓] Flutter (Channel unknown, 1.22.3, on Mac OS X 10.15.5 19F101, locale en-US)
• Flutter version 1.22.3 at /Users/smedic/fvm/versions/1.22.3
• Framework revision 8874f21 (3 weeks ago), 2020-10-29 14:14:35 -0700
• Engine revision a1440ca392
• Dart version 2.10.3

Any ideas?

**Comment by iapicca** [comment]
@smedic 
can you provide your `flutter run -v`
are you experiencing the issue with the [example app](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example)?

**Comment by darshankawar** [comment]
@smedic 
Please provide a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by smedic** [comment]
@darshankawar I cannot provide source code but I can a snippet how we set player.

`  @override
  void initState() {
    super.initState();
    if (widget.playerController == null) {
      _shouldDisposeController = true;
      _controller = VideoPlayerController.network(widget.video.url);
    } else {
      _controller = widget.playerController;
    }
  }

  @override
  void afterFirstLayout(BuildContext context) {
    if (widget.autoPlay) {
      _setupPlayer();
    }
  }

  Future<void> _setupPlayer() async {
    if (!_controller.value.initialized) {
      try {
        await _controller.initialize();

        if (widget.controllerInitialized != null) {
          widget.controllerInitialized(_controller);
        }

        if (mounted) {
          setState(() {
            _currentChild = VideoPlayer(_controller);
          });
        }
      } catch (e, s) {
        unawaited(CrashReporting.report(e, s, context: 'while setting up player, errorDescription: ${_controller.value.errorDescription}'));

        if (widget.onPlayerFailed != null) {
          setState(() {});

          widget.onPlayerFailed(_controller.value.errorDescription, widget.vid);
        }
      }
    }

    if (!_controller.value.initialized) return;

    if (widget.muted) {
      unawaited(_controller.setVolume(0.0));
    } else {
      unawaited(_controller.setVolume(1.0));
    }

    if (widget.autoPlay && ModalRoute.of(context).isCurrent) {
      unawaited(_controller.seekTo(Duration(seconds: 0)));
      unawaited(_controller.play());
    }

    _controller.addListener(_playerListener);
  }
`

This was okay in previous versions and now it's buggy. I guess something is changed in library.

**Comment by iapicca** [comment]
@smedic 
do not provide production code, but has mentioned

> Please provide a **_minimal complete reproducible_** code sample that shows the issue you are facing.

together with your `flutter doctor -v` and your `pubspec.yaml`

**Comment by smedic** [comment]
@iapicca I am just giving url to the video player and it cannot play it. Why do you need more code? Library is quite simple to use.

**Comment by darshankawar** [comment]
@smedic 
Tried official `video_player` plugin example which has an instance of playing video through network url, using latest stable version on Android 8.1.0 device and it ran properly without any issues.

[71055.mp4.zip](https://github.com/flutter/flutter/files/5587849/71055.mp4.zip)

Code snippet:

```
void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      closedCaptionFile: _loadCaptions(),
      videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize();
  }
```

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[✓] Connected device (1 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>

Can you try the official plugin example and see if you get similar error ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
