### ISSUE TITLE
Android studio has installed the flutter plug-in, but the flutter doctor is still upgraded and not installed

### ISSUE THREAD

**Issue by SongHuaixu** [flutter/flutter#71058]
```

[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/xxxxx/flutter
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

```

**Comment by SongHuaixu** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/15318808/99932259-7d900e00-2d92-11eb-9a76-4f6fef533a60.png">

**Comment by SilentlyYc** [comment]
I have the same problem.

**Comment by hello-addweb** [comment]
Solution that worked for me:

    1. Just install plugins.
    **Studio>File>Settings>Plugins>Browse Repositories**
    2. Search for flutter.
    3. Tap on Install (a dialog will pop regarding dart dependency. click Yes).
    4. Once the installation is finished restart android studio.

**Comment by sidrao2006** [comment]
Hi @SongHuaixu 
This is a known issue, it happens because the latest version of Android Studio changed the path where the plugins are located and Flutter tools can't find it. This is just a warning and you can still use Flutter without worries.

Similar to #70551

Thank you

**Comment by SongHuaixu** [comment]
> Hi @SongHuaixu
> This is a known issue, it happens because the latest version of Android Studio changed the path where the plugins are located and Flutter tools can't find it. This is just a warning and you can still use Flutter without worries.
> 
> Similar to #70551
> 
> Thank you

OK Thank you
