### ISSUE TITLE
GestureBinding resampling is broken on Pixel 1

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#71060]
b/173978009

GestureBinding resampling is kind of broken on Pixel1. (This is only observed on Pixel 1 so far).
When tapping quickly, it works fine.
When tapping slightly slowly, with maybe a fat finger, the tap event isn't registered/handled.

To reproduce just enable resampling on hello flutter.

When tapping, I see these events:
a) PointerDownEvent
b) PointerMoveEvent(s) (slight movements)
c) PointerUpEvent
My guess is before (c) happens, it's interpreting (a) and (b) as a drag/fling.

**Comment by mehmetf** [comment]
@liyuqian FYI

**Comment by dreveman** [comment]
It would be useful to know what events you see when this goes wrong. Can you capture the events and post them here? Ideally we capture the events prior to resampling so we can use that to construct a test case.

When resampling is on, the position of the down event is resampled using previous add/hover events and future move/up events. It's possible that this results in a more significant movement that is detected as a drag on some devices but I'd need to understand that better before I can determine the correct fix.

**Comment by mehmetf** [comment]
Do you have a Pixel 1 device? If not, I strongly recommend you acquire one (and expense it) otherwise it would not be possible to test the fix. If yes, you should be able to reproduce this easily since _any_ simple button seems to exhibit the problem.

In the meantime, I will ask this question on the bug and see if we can get a response.

**Comment by mossmana** [comment]
As the underlying buganizer issue is now fixed, I am closing this issue. Please file a new issue with repro steps against the latest version of Flutter if incorrect GestureBinding behavior is encountered again.
