### ISSUE TITLE
Unable to pick and upload image as i changed and upgraded target androidSDK to 29

### ISSUE THREAD

**Issue by karambitmonger** [flutter/flutter#71067]
This issue is specific to samsung devices only,as i have tried on other devices and they work. Anybody have a workaround?
I am using  image_picker: ^0.6.2

**Comment by iapicca** [comment]
@karambitmonger 
can you update [image_picker](https://pub.dev/packages/image_picker) to the latest version `^0.6.7+14`
if the issue persists please provide 
your `flutter doctor -v` 
your `flutter run -v` (while attempting the operation that fails)
and your `pubspec.yaml`

**Comment by darshankawar** [comment]
@karambitmonger 
Please follow the steps mentioned above and provide the requested details.
Thanks.

**Comment by hello-addweb** [comment]
1.First add latest version image_picker
2.and if you use targeted androidSDK to 29 so change minSdkVersion to 21
3.and build again and run it

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
