### ISSUE TITLE
Flutter Notification Complex implementation in Android & IOS

### ISSUE THREAD

**Issue by halimpuckjava** [flutter/flutter#71065]

**Comment by iapicca** [comment]
@halimpuckjava 
this issue seems more a statement / opinion rather than a bug report or a feature request,
can you provide a minimal code sample to explain your case together with your `flutter doctor -v`

**Comment by halimpuckjava** [comment]
@iapicca 

i mean notification in flutter is complex implementation

**Comment by darshankawar** [comment]
@halimpuckjava 
Are you facing any issue or do you have a proposal for Flutter framework on notifications ?
If you have any issues, please provide a complete reproducible code sample that we can analyze. If you want change in Flutter notifications, please provide a use case followed by proposal that contains how can it help to make notification less complex.

Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
