### ISSUE TITLE
Issue from website page Flutter框架概览

### ISSUE THREAD

**Issue by luoyujiecn** [flutter/flutter#71066]
From URL: https://www.flutterchina.club/technical-overview.md

**Comment by zhaopingfu** [comment]
## 链接404

![a](https://user-images.githubusercontent.com/23115961/99946389-3feead80-2db1-11eb-9c10-4a5ef5f84109.png)

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/71046

**Comment by pedromassangocode** [comment]
This issue does not seems related to Flutter.
