### ISSUE TITLE
Flutter use its own font family instead of system font

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#71068]
It doesn't follow with system font.

**Comment by hello-addweb** [comment]
Check this [article](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6) that how you can use the system font.

**Comment by darshankawar** [comment]
Closing this as duplicate of [48381](https://github.com/flutter/flutter/issues/48381)
