### ISSUE TITLE
Lookup L10n from Locale without BuildContext

### ISSUE THREAD

**Issue by lukaslihotzki** [flutter/flutter#71071]
## Use case
Our app needs to access L10n for local notifications (in background). In this case, there is no App and no BuildContext available. It is possible to use a specific (hard-coded) L10n with `L10nEn()` (and `import 'package:flutter_gen/gen_l10n/l10n_en.dart';`) for example. We can write our own switch statement to get the matching L10n for a `Locale.languageCode`, but we need to maintain the different languages (cases) manually. We would prefer a solution without this maintenance burden.

## Proposal
`flutter_gen/gen_l10n/l10n.dart` has an auto-generated `_lookupL10n` function that implementes this switch statement. We propose to make it public (by changing the replace of `@(lookupName)` from `_lookup$className` to `lookup$className` in ` flutter/packages/flutter_tools/lib/src/localizations/gen_l10n.dart`).

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @lukaslihotzki,

Could you elaborate a little more on your use case? I just want to make sure we're solving the right problem. From what I understand, you want this method to be public:
```dart
AppLocalizations lookupAppLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'en': return AppLocalizationsEn();
    case 'es': return AppLocalizationsEs();
  }

  throw FlutterError(
    'AppLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.'
  );
}
```

So that, somewhere in your Flutter app, you can then go:
```dart
if (_lookupAppLocalizations(locale) is AppLocalizationsEn) {
  // do something
} else {
  // do something else
}
```

I'm still a little unclear -- If a `BuildContext` isn't available, where is the `Locale` coming from? The logic for `_lookupAppLocalizations` is also pretty straightforward, so wouldn't it be possible to just recreate something like that. in your app? Maybe a small sample could help clarify what's needed here.

**Comment by lukaslihotzki** [comment]
The use case is to read a localized string from L10n to display it as a notification (for example, an `unreadMessage` string) in a detached isolate (for example onBackgroundHandler from firebase_messaging). `window.locale` is used to get the locale without App or BuildContext. It seems to be ok to use `window.locale` in this case:

> The only place that WidgetsBinding.instance.window is inappropriate is if a Window is required before invoking runApp(). In that case, it is acceptable (though unfortunate) to use this object statically.

So we do something like `lookupAppLocalizations(window.locale).unreadMessage` to get the string in the correct language to display it as a notification (for example, by passing it to flutter_local_notifications).

We want to avoid to recreate this `lookupAppLocalizations` function, because it would need manual updating if the supported langauges change.

**Comment by tiloc** [comment]
+1 Same issue here. My very crude solution was to run the output of the gen_l10n tool through `sed` and replace `_lookup` with `lookup`. Problem solved, but would prefer if it wasn't private to begin with.

**Comment by assemblethis** [comment]
> The use case is to read a localized string from L10n to display it as a notification (for example, an `unreadMessage` string) in a detached isolate (for example onBackgroundHandler from firebase_messaging). `window.locale` is used to get the locale without App or BuildContext. It seems to be ok to use `window.locale` in this case:
> 
> > The only place that WidgetsBinding.instance.window is inappropriate is if a Window is required before invoking runApp(). In that case, it is acceptable (though unfortunate) to use this object statically.
> 
> So we do something like `lookupAppLocalizations(window.locale).unreadMessage` to get the string in the correct language to display it as a notification (for example, by passing it to flutter_local_notifications).
> 
> We want to avoid to recreate this `lookupAppLocalizations` function, because it would need manual updating if the supported langauges change.

+1 Same exact use case here for push notifications with data payloads that create local notifications. I'm just replicating _lookupAppLocalizations for the _onBackgroundMessageHandler. 

Slightly off topic, but I had problems getting the locale from window.locale. I only got 'und' for languageCode which is undefined. I fixed this issue by instead doing the following:

```
final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
final locale = widgetsBinding.platformDispatcher.computePlatformResolvedLocale(supportedLocales);

```

**Comment by shihaohong** [comment]
The method should now be public on the `master` branch
