### ISSUE TITLE
Cursor drag handle does not adjust for scroll position

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#7107]
1) Go to the Text Fields page in Gallery
2) Tap on "Life Story", type some text, and tap to move the cursor midway through the text.  A cursor drag handle will appear.
3) Scroll the page while the on-screen keyboard is visible.  The drag handle will not move to match the scroll.

This will also happen when the page scrolls due to the on-screen keyboard being shown and hidden:
1) Tap on the password field.  The page will scroll up so that the field is visible above the keyboard.
2) Tap on "Life Story" again to show a drag handle.
3) Dismiss the keyboard.

Hiding the keyboard reverts the scrolling, but the drag handle doesn't update its position.

@abarth @mpcomplete

**Comment by mpcomplete** [comment]
This is https://github.com/flutter/flutter/issues/3861 .
