### ISSUE TITLE
isolate:Illegal argument in isolate message : (object is a StackTrace)

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#71081]
cant send error with too big stackTrace, error is : Invalid argument(s): Illegal argument in isolate message : (object is a StackTrace)

**Comment by pedromassangocode** [comment]
Hi @chongbo2013 
You can share the logs in a .txt file.
Provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample as well.
Thank you

**Comment by chongbo2013** [comment]
isolate FlutterMethodChannel cannot work pls.

**Comment by pedromassangocode** [comment]
Hi @chongbo2013 
I can't help if you don't provide the requested information.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
