### ISSUE TITLE
Would like line numbers in AOT builds

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7108]
This request comes from customer:fast.  They're getting crash logs from their production app (via package:logging) but no line numbers in --release builds.  If possible, they would like line numbers.

Possible?  @a-siva @zanderso?

**Comment by eseidelGoogle** [comment]
b/33054420 is an example report missing line numbers.

**Comment by Hixie** [comment]
This presumably would come at a cost. Isn't the whole point of release mode to not pay that cost?

**Comment by eseidelGoogle** [comment]
Possibly.  Just trying to understand whether this is intentional omission or a bug or a configuration option or what.

**Comment by Hixie** [comment]
I'm pretty sure it's intentional but I would love to hear confirmation from someone on the Dart team.

**Comment by rmacnak-google** [comment]
This is intentional. AOT builds remove the metadata that is normally used to include line numbers to reduce the size of the app. Note also that stack traces in AOT lack frames for inlined methods.

**Comment by Hixie** [comment]
I think we should WONTFIX this, or punt it to post-1.0, where we would implement this as an optional new feature of `build/run --release` which includes the data needed for stack traces.

**Comment by Hixie** [comment]
This was done, but in a way regressed our size benchmarks significantly. We are tracking further work at https://github.com/dart-lang/sdk/issues/28785.
