### ISSUE TITLE
what would happen if future iOS introduced radical changes in design paradigm

### ISSUE THREAD

**Issue by shuoch-g** [flutter/flutter#71082]
This is a hypothetic question.

Let's say Apple introduced a completely redesign in iOS 15 next year, much like what happened on iOS 7 by Jony Ive https://en.wikipedia.org/wiki/IOS_7#Design. What does it mean for flutter ?

Since flutter does its own UI drawing instead of delegating to platform UI controls, I assume flutter team will need to maintain support for two versions of UI drawing

1. For flutter App installed on iOS < 15, keep using the old design, **even if the flutter app gets upgraded flutter version.**
2. For flutter App installed on iOS >= 15, use the new design.

Now flutter engine would switch on platform version (iOS 15) to draw differently internally while dart code doesn't need change much.

Am I getting this right ? Thanks !

**Comment by sidrao2006** [comment]
Hey @shuoch-g ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please see https://flutter.dev/community for resources and asking queries doubts and assistance on personal code. You may get some help if you post it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=flutter) and if you need help with your code, please check https://www.reddit.com/r/flutterhelp/.

Thanks
