### ISSUE TITLE
Add border radius to all progress indicators

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#71085]
This applies `ProgressIndicator` and all its derived classes:
* `LinearProgressIndicator `
* `CircularProgressIndicator `
* `RefreshProgressIndicator `

### Examples for each of the indicators

<div style="display:flex;">
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99975823-bee4e580-2db3-11eb-8f47-03f9f183d0a6.png"/>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99976710-d8d2f800-2db4-11eb-895c-ca4e3a6d3c44.png"/>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99976133-1e42f580-2db4-11eb-97bd-4d613856339b.png"/>
</div>

### Current appearance

<div style="display:flex;">
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99979600-4fbdc000-2db8-11eb-9505-c4f1a6f8ec12.png"/>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99979366-12f1c900-2db8-11eb-8b1b-58d92837fd52.png"/>
<img width="33%" src="https://user-images.githubusercontent.com/39104740/99979917-b511b100-2db8-11eb-9bbd-0e569f63fd5d.png"/>
</div>

**Comment by adeolaex** [comment]
Hey @nt4f04uNd 

I think the property you are looking for is `strokeWidth` .
As per the [documentation](https://api.flutter.dev/flutter/dart-ui/Paint/strokeWidth.html)

**Comment by nt4f04uNd** [comment]
@adeolaex stroke width and border radius are not the same thing

**Comment by iapicca** [comment]
@nt4f04uNd 
as mentioned in this [comment](https://github.com/flutter/flutter/issues/71075#issuecomment-732227177) 
[LinearProgressIndicator](https://api.flutter.dev/flutter/material/LinearProgressIndicator-class.html), 
[CircularProgressIndicator](https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html), 
[RefreshProgressIndicator](https://api.flutter.dev/flutter/material/RefreshProgressIndicator-class.html)
are part of Flutter's [Material](https://flutter.dev/docs/development/ui/widgets/material) that is supposed to replicate [material design](https://material.io/design) not to be customized

you can already create your own [custom widget](https://stackoverflow.com/questions/61717754/how-to-get-custom-circular-progress-indicator-as-shown-in-image-with-flutter) if you want to

**Comment by nt4f04uNd** [comment]
@iapicca got it

**Comment by Piinks** [comment]
Re-opening https://github.com/flutter/flutter/issues/109137 as an unresolved duplicate of this issue.

There are a lot of widgets in the material library that match the material spec, _and_ offer customizations beyond the spec. This is a fair feature request.
