### ISSUE TITLE
RefreshProgressIndicator doesn't look like native

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#71086]
This issue relates to mismatches of `RefreshProgressIndicator` with swipe to refresh [material specs](https://material.io/design/platform-guidance/android-swipe-to-refresh.html) and native appearance

Related issue about `RefreshIndicator` #71075 

## Description
This is how `RefreshProgressIndicator` looks like now in flutter

* https://youtu.be/DWODhzmkSLU

Native swipe to refresh examples

* [Material spec](https://kstatic.googleusercontent.com/files/327b57850a9283ed6ff7af86d242a34626e959e71fcc991fbcc15b360b527329e2f37a06e3d5a233ab15e7d8a998d1d9879393f3b6e29aca8d0f663210222d98)
* FastHub https://youtu.be/cXjU_BWrM1U
* Google Chrome https://youtu.be/9J_PE3OqI-0
* GitHub https://youtu.be/TbltPdKOIWo

The arrow simply looks different and has different animation

Also, it's transperency at the start doesn't look good - arrow head is too small and you can see that the arrow actually consists of two parts

<div style="display:flex">
<img src="https://user-images.githubusercontent.com/39104740/99962363-1fb6f280-2da1-11eb-977f-aad55fd4fc78.jpg" />
<img src="https://user-images.githubusercontent.com/39104740/99962368-204f8900-2da1-11eb-9738-8aa8e78d165b.jpg" />
</div>

**Comment by iapicca** [comment]
@nt4f04uNd 
how this issue differs from these?
https://github.com/flutter/flutter/issues/71075
https://github.com/flutter/flutter/issues/71085

I recommend to close as duplicate

**Comment by nt4f04uNd** [comment]
@iapicca this is getting annoying, honestly

#71085 relates to border radius, which goes out of material specs, as you said. I closed it
#71075 is related to `RefreshProgress` behaviour

this issue is related to `RefreshProgressIndicator` appearance
