### ISSUE TITLE
Feature: Scribble on iPad

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#71091]
iOS 14.0 has a new iPad feature enabling hand-written letters to be converted into text. There's a specific API that requires writing custom code, so it's not clear to me if this is something Flutter can support.

- [Sample code](https://developer.apple.com/documentation/pencilkit/customizing_scribble_with_interactions)
- [WWDC Video](https://developer.apple.com/videos/play/wwdc2020/10106/)

**Comment by fbcouch** [comment]
This seems like a duplicate of (certainly related to) #61278

**Comment by nilsreichardt** [comment]
I agree @fbcouch. I think this is a duplicate of #61278

**Comment by gaaclarke** [comment]
Closing as duplicate: https://github.com/flutter/flutter/issues/61278
