### ISSUE TITLE
[web]: InkWell or other button onTap is not working randomly

### ISSUE THREAD

**Issue by gabrielarlo** [flutter/flutter#71090]
Describe your issue and include the command you're running, flutter_web version, browser version

I am developing for the web, then when I use InkWell or any button widget with onHover it works, when I use onTap or onPressed randomly it is not working. When I use a tablet or mobile simulator then it works. It is very annoying.

Flutter Version: Channel beta, 1.24.0-10.2.pre
Browser: Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by juanxme** [comment]
I Have the same issue

**Comment by darshankawar** [comment]
@gabrielarlo 
Please provide a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by ignaciotcrespo** [comment]
same issue here, randomly stop working, the onTap is not called anymore. I have many buttons in the screen, when onTap fails I need to click in another button to make it work again.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by sajaadem** [comment]
please any update for this issue ?

**Comment by ignaciotcrespo** [comment]
hi @sajaadem for me it was not fixed, I always had the problem in macos with default screen resolution. But I didnt try with the latest flutter version, can not confirm it is fixed now.

**Comment by AliYar-Khan** [comment]
I have same problem on android as well !!!
