### ISSUE TITLE
Gallery should have Android Round Icon support

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7110]
As an example of doing such in a Flutter App:
https://developer.android.com/preview/api-overview.html#circular-icons

**Comment by Hixie** [comment]
Moving out of m3 since this doesn't match any of our current priorities.

**Comment by TahaTesser** [comment]
Looks like gallery has round icon support 
https://github.com/flutter/gallery/blob/master/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png

Closing as fixed 
Thank you
