### ISSUE TITLE
[iOS] Textfields auto selection with black color

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#71111]
Hi guys,

I have problems with all textfields in my app.
Im writing text to text field fast and after i stop, black rectangle appears as you can see in the pictures.
then I write again (adding text) and it disappear.

I think it since 1.22.4 or one before

```
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (10 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```
![IMG_4150](https://user-images.githubusercontent.com/42498461/100023271-59ade600-2ded-11eb-98ad-661ad40f7eb4.PNG)
![IMG_4151](https://user-images.githubusercontent.com/42498461/100023279-5ca8d680-2ded-11eb-8505-43de58b34331.PNG)

**Comment by pedromassangocode** [comment]
Hi @dvird 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample? Is this happening on Android devices as well?
Thank you

**Comment by dvird** [comment]
I dont have any reason to print that doctor output for that kind of problem.
I've sent you the data you need.

about the "minimal complete reproducible" just open new project and add edittext. 
after investigate this problem, i found that there auto selection of the text.

write text, and delete and then write again and stop. the text will be auto selected.
about the black color its just a color but when you open new project so its blue.

**Comment by pedromassangocode** [comment]
Hi @dvird 
I see what you mean now. This is not a bug this is intentional to match the native behavior, see https://github.com/flutter/flutter/issues/63130#issuecomment-670204627 and https://github.com/flutter/flutter/issues/63130#issuecomment-670220564.

It is black because you probably changed the color for the selection!? Please provide a code that reproduces the issue about the black color.

**Comment by dvird** [comment]
Oh thanks ! cant find why it's black but i assume thats my problem so i will find it.

**Comment by Rickyballs** [comment]
`autocorrect: false,` can slove it!
