### ISSUE TITLE
FlutterEngine init causing 'unrecognized selector sent to instance' crash on iOS

### ISSUE THREAD

**Issue by AmroShohoud** [flutter/flutter#71110]
I'm trying to integrate Flutter into an existing iOS app. I followed the instructions here: https://flutter.dev/docs/development/add-to-app/ios/project-setup. It was working at one point and then not sure what I changed and now I'm getting an error at the line that initializes the FlutterEngine. Note - It works fine when flutter is on the "flutter-1.21-candidate.9" branch. But when on "stable", it throws the error.
The error is as follows:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean objectForKey:]: unrecognized selector sent to instance 0x1f8c9fdc0'
```

AppDelegate.h
```
#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>

@class NotificationsHandler;
@class BackgroundTasksManager;
@class ServiceCall;

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (readonly, strong) NSPersistentContainer *persistentContainer;

- (void)saveContext;

@end
```

AppDelegate.m:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    // Override point for customization after application launch.
    //check if this fixes connection issue and random crashes
    [[NSURLCache sharedURLCache] setMemoryCapacity:0];
    [[NSURLCache sharedURLCache] setDiskCapacity:0];
    
    self.flutterEngine = [[FlutterEngine alloc] initWithName:@"my flutter engine"];
    // Runs the default Dart entrypoint with a default Flutter route.
    [self.flutterEngine run];
    
    
    return YES;
}
```
Podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QBank_Redesigned' do

  flutter_application_path = '../flutter_project_folder'
    load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


  install_all_flutter_pods(flutter_application_path)
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QBank_Redesigned

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Firestore'
pod 'SSZipArchive'
pod 'Charts'
pod 'FittedSheets'

  target 'QBank_RedesignedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
I've tried uninstalling and reinstalling Flutter. I've tried deleting my XCode and Flutter folders and re-cloning them and reverting to previous commits.

Note, it works in another brand new project but not this one I'm currently working on.

Flutter version 1.22.4

XCode 12.2

Attempting to run on iPhone 11 with iOS 13.5.1 and iPad mini 3 with iPadOS 12.4.8.

flutter doctor -v:
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-US)
    • Flutter version 1.22.4 at /Users/ashohoud/Documents/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ashohoud/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile)                     •
      77DCF44C-3B25-4392-978E-A92B08A230CA • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • iPhone 11 Pro Max (mobile)                     •
      B11E5A17-CF98-4AA2-8B73-F5C331D1E4EF • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      8CEF1E92-35AF-426C-B053-BC9C8140DE50 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```

**Comment by darshankawar** [comment]
@AmroShohoud 
Please provide complete `flutter doctor -v` and a minimal complete reproducible code sample that we can use to replicate the issue.

**Comment by AmroShohoud** [comment]
I've added the flutter doctor -v output and the AppDelegate.h along with the Podfile. I think it has to do with the project configuration so I may not be able to provide a fully replicable code sample.

**Comment by darshankawar** [comment]
@AmroShohoud 
As the exception says `NSInvalidArgumentException', reason: '-[__NSCFBoolean objectForKey:]:` , you are probably using `YES` instead of `true`. 
Please check your `info.plist` XML file and compare it with the brand new project you created.

**Comment by AmroShohoud** [comment]
It works fine when flutter is on the "flutter-1.21-candidate.9" branch. But when on "stable", it shows the above error (without changing the info.plist). It's an objective-c project so info.plist converts true to YES.

**Comment by darshankawar** [comment]
@AmroShohoud 
Not sure what is `flutter-1.21-candidate.9` branch, but it doesn't sound like you are on either of `dev, beta, stable or master` on which we ideally should be.
Can you switch to latest master and try again ?

**Comment by AmroShohoud** [comment]
Sorry if it wasn't clear. I was originally running on '''stable''' branch and was getting the error. So I tried reverting to an older version of flutter (because I had it working before I upgraded) which is why I was on the '''flutter-1.21-candidate.9''' branch. The error exists on the '''stable''' branch

**Comment by darshankawar** [comment]
@AmroShohoud 
Is it possible to compare your current project configuration with the new one you created and see where possibly the difference could be ?
In order to exactly check why it may be causing the crash, a minimal code sample would be very helpful.

**Comment by phil10xs** [comment]
Having same issues. Any solution yet?

**Comment by gbbest15** [comment]
i got this error now, Did anyone find the solution
