### ISSUE TITLE
[wiki] Typo on wiki page of `Setting up the Engine development environment`

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#71124]
Accoding to [Setting up the Engine development environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment):

- [VSCode with C/C++ Intellisense [C/C++]](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment#vscode-with-cc-intellisense-cc)

> Intellisense can also use our `compile_commands.json` for more robust functionality. Either symlink `src/out/compile_commands.json` to the project root at `src/flutter` or provide an absolute path to it in the `c_cpp_properties.json` config file

It does NOT work to soft symlink to `src/flutter` and open `src/flutter` in VS Code.
It works, however, with symlinking to `src/` and opening `src/` in VS Code

**Comment by chinmaygarde** [comment]
Thanks. I updated the wiki.
