### ISSUE TITLE
[gen-l10n] output-dir not forwarded in `l10n.yaml`

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#71127]
The `output-dir` option is not properly forwarded in the `l10n.yaml` file. The only way to get this working currently is to use the command line `flutter gen-l10n --output-dir=<path>`.

Discovered in https://github.com/flutter/flutter/issues/70840, when trying to suggest using `--no-synthetic-package` with `--output-dir`

**Comment by castrors** [comment]
How can I test this implementation? I already changed to flutter channel master but couldn't use the l10n.yaml with:
`output-dir: lib/l10n
synthetic-package: false`

**Comment by paulpopiel** [comment]
Any update on this? 

currently not working on:
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (4 months ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

**Comment by shihaohong** [comment]
I just tested this on the `master` branch with [this repo](https://github.com/shihaohong/gen_l10n_l10n_yaml_test). And it seems to generate correctly. Could you file a new issue with reproducible code?

**Comment by chaoxiongTian** [comment]
I clone code and run flutter pub get , but can`t generate app_localizations.dart in lib/l10n.


 ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.2.0, on Mac OS X 10.14.6 18G8022 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

**Comment by chaoxiongTian** [comment]
I raised a new [issues](https://github.com/flutter/flutter/issues/84979)
