### ISSUE TITLE
[package_info] When the IOS is not released, the version number and other information cannot be obtained during the test on the real machine

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#71135]
![image](https://user-images.githubusercontent.com/24307960/100060702-e0070e00-2e67-11eb-82a5-d50f04d74943.png)
Is it because my app is not released?

-------- 
Can not be obtained by running flutter run --release
It can be obtained by running xcode, but I can get it in the newly created test project

**Comment by pedromassangocode** [comment]
Hi @mulieli 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by mulieli** [comment]
> Hi @mulieli
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

![image](https://user-images.githubusercontent.com/24307960/100065918-5c511f80-2e6f-11eb-8ef8-a8195f0b1842.png)
This is the result of flutter doctor -v

**Comment by mulieli** [comment]
> Hi @mulieli
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

**Comment by mulieli** [comment]
> Hi @mulieli
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
> Thank you

@pedromassangocode 
I run on a real machine through xcode, package_info can get information,
However, running package_info on a real machine with flutter run --release cannot get the version information

I can’t provide reproducible projects because the problem lies in existing projects

**Comment by mulieli** [comment]
@pedromassangocode 
Maybe package_info conflicts with other packages?

**Comment by pedromassangocode** [comment]
Hi @mulieli 
I'm not really sure about that, Can you please provide your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by mulieli** [comment]
@pedromassangocode 
I found a temporary solution. After modifying the version information of xcode, the version information can be obtained, but I feel that it is not the final solution

**Comment by mulieli** [comment]
@pedromassangocode 

name: paraApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
# version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^3.2.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter_swiper: ^1.1.6
  fluttertoast: ^7.1.4
  flutter_statusbarcolor: ^0.2.3
  flutter_custom_dialog: ^1.0.16
  pull_to_refresh: ^1.6.2
  dotted_line: ^2.0.2
  flutter_rating_bar: ^3.0.1+1
  json_annotation: ^3.1.0
  dio:  ^3.0.10
  provider: ^4.3.2+2
  date_format: ^1.0.8
  permission_handler: ^5.0.1+1
  image_gallery_saver: ^1.6.5
  shared_preferences: ^0.5.12+2
  event_bus: ^1.1.1
  qr_flutter: ^3.2.0
  camera: ^0.5.8+11
  path: ^1.7.0
  path_provider: ^1.6.22
  badges: ^1.1.4
  image_picker: ^0.6.7+12
  flutter_downloader: ^1.5.2
  package_info: '>=0.4.3+2 <2.0.0'
  flutter_picker: ^1.1.5
  flutter_widget_from_html_core: ^0.5.1+4
  cached_network_image: ^2.3.3
  flutter_svg: ^0.18.1
  webview_flutter: ^1.0.5
  photo_view: ^0.10.2
  money2: ^1.4.3
  qrscan: ^0.2.17
  fluwx: ^2.4.0
  url_launcher: ^5.7.10
  http: ^0.12.2
  percent_indicator: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^1.10.4
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconFont
      fonts:
        - asset: iconfont/iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by pedromassangocode** [comment]
This may be related to https://github.com/flutter/flutter/issues/20761#issuecomment-493434578.

Will close this for now and keep an eye on it, I will reopen if this get too much activity!
Thank you
