### ISSUE TITLE
Ability to set custom output directory for `flutter build` commands

### ISSUE THREAD

**Issue by mymikemiller** [flutter/flutter#71130]
## Use case

As described in [this issue](https://github.com/flutter/flutter/issues/18140), it would be nice to be able to specify the output directory for flutter builds. For example, when building a flutter-for-web app with `flutter build web`, my output *always* ends up in the `/build/web` folder. I'd like to be able to specify where the built files end up, similar to what I can do for individual dart files with Dart2js's --out flag.

## Proposal

Add a --out flag to the the flutter build command to allow specifying the build directory. For example, `flutter build web --out=my_custom_build/web`

**Comment by kenthinson** [comment]
I would love this as well. For now I'm using a bash script.

**Comment by NidheeshMt** [comment]
This will be great

**Comment by esDotDev** [comment]
Do you have any current workarounds? I guess we have to make our own script to do the post-build copy?

**Comment by onatcipli** [comment]
Hey @jmagman, I could help with this future. Currently, I'm working on building a CI that automatically creates builds for our flutter project for different customers, and the output directory option needed for the CI that I'm building. 

I can achieve this with the SH scripts but If you mentor and direct me I can create PR for that.

and other flutter developers will be able to use that feature 😊

cc @justinmc

**Comment by jmagman** [comment]
You can probably accomplish what you need in CI with `flutter config --build-dir=<out>`, which is a feature that's been around awhile #5601.  That's a global option that would impact all `flutter` commands, not a one off like an option on `flutter build`.

**Comment by onatcipli** [comment]
Thanks @jmagman, That's great!

**Comment by elirov** [comment]
Updates on this?

**Comment by cmaster11** [comment]
This would be quite useful for Flutter Web (similar to @esDotDev comment), where we may need to build multiple entrypoints in different dirs (e.g. one entrypoint for the main app, one for a docs app, and so on). 

Yes, you can use a workaround, but basically any build tool has a flag to set an output directory, so why not Flutter too? :D

**Comment by ayush-mandowara-bst** [comment]
My use case: I want to create a debug app and a test app every day from the master branch and store them, so I can use them when needed and not have to wait for the output. However, in the process, I don't want my last app to be altered, as the new app could be broken and it would hamper my development.

I guess I could keep a backup of my current app as well, but having `--output` flag would be much cleaner. One could specify the file name as well (like for example storing app with a version number for my own use case).

So far, I have created a python script that would make a copy of the existing app in the output folder to a backup folder with version number and app type appended to it.

**Comment by jithware** [comment]
Would like to have this feature as well. My workaround is this: 
```
flutter build web
cp -avr build/web/* docs/
```

**Comment by thomas-vl** [comment]
@jithware Thanks!

**Comment by MrBirb** [comment]
@eliasyishak I believe this can be closed now?

**Comment by Wissperwind** [comment]
In which release this is included?

**Comment by eliasyishak** [comment]
@MrBirb yes this can be closed now.

And I'm not sure when the release will be available with this update but if you're working off the master branch you should be good to go now @Wissperwind

**Comment by jmagman** [comment]
@eliasyishak are you tracking the non-web output directory in another issue?

**Comment by jmagman** [comment]
> In which release this is included?

https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-versions-that-contain-framework-commit-x

**Comment by eliasyishak** [comment]
Yes just created it now, and thank you for linking the wiki, hope that helps @Wissperwind

Link to issue tracking build subcommands: https://github.com/flutter/flutter/issues/114538
