### ISSUE TITLE
[IN APP PURCHASES] Retrieve Introducy offer on an auto-renewable subscription on iOS

### ISSUE THREAD

**Issue by chamartt** [flutter/flutter#71146]
Hi,

I use the plugin since one year to display Android and IOS subscriptions and make purchases on them; everything is working well.
Since a week, I'm trying to add a new subscription with an introducy offer (one price for the first year then a regular price per year).

On Android, my introducy offer on my new subscription is retrieved but I have problem on iOS.
The introducy offer is not display : there is only one price which is the regular price.

On the same new subscription, I've also implemented a free trial period of 1 week which is correctly display and available, so the problem is only on the introducy offer.
This one has been correctly accepted by Apple.

Is there something to do in particular to retrieve/display introducy offers (even when free trial period is correctly retrieved and available) ?

Thank you for your help.

**Comment by nt4f04uNd** [comment]
I make a guess that there's nothing to deal with from the side of plugin and this is a sandbox environment bug. Have you tried releasing it?

**Comment by chamartt** [comment]
Yes I released it but the introducy offer doesn't appear when I try to subscribe to the new offer.
Is there nothing particular to do on XCode during the build ?
In Flutter,  is it possible to have an iOS subscription with one free trial period AND one introducy offer ?
One more time, with my Android subscription, everything is ok, I have both promotion.

Thank you for your help.

**Comment by vintage** [comment]
@chamartt 

> In Flutter, is it possible to have an iOS subscription with one free trial period AND one introducy offer ?

AFAIK it's not possible to have iOS subscription with multiple Introductory Offers. You can define whether there is a discount for the first year OR a free trial. Not both at the same time. How did you manage to configure such subscription in the Apple dashboard in the first place?

![App_Store_Connect](https://user-images.githubusercontent.com/729785/110756908-0f8d2b00-824b-11eb-835c-bd5dcbfe5704.png)

After adding new in Introductory Offer to the subscription, the previous got simply deleted.

**Comment by chamartt** [comment]
Hi,

Finally, I changed my subscription system to achieve my requirments and bypass Apple limitations.
I close this ticket.
