### ISSUE TITLE
Flutter command is not working (Access is denied)

### ISSUE THREAD

**Issue by abbasi-saqib** [flutter/flutter#71149]
Flutter installation issue

When i type flutter command i get this error (Access is denied)

![image](https://user-images.githubusercontent.com/38981666/100079099-b47f2600-2e5d-11eb-9c93-daf123a8a3fa.png)

Environment Variable is already set

![image](https://user-images.githubusercontent.com/38981666/100078778-53efe900-2e5d-11eb-81dc-39596d2b0c8f.png)

Permission is given for every one who is using this laptop

Remember I m using the most recent version of the flutter

**Comment by darshankawar** [comment]
@abbasi-saqib 
Can you specify at what location have you installed the sdk ?
Usually you should avoid at path like `C:\Users` and install somewhere in `Documents`. 
Check [this](https://flutter.dev/docs/get-started/install/windows) official documentation on how to install on Windows platform and see if your setup is proper as mentioned.
Thanks.

**Comment by abbasi-saqib** [comment]
Darshankar ,
Did everything according to the guideline . Even created directory in c:/src/flutter . But same error . Even set the permission to flutter director for everyone but still find the issue

**Comment by darshankawar** [comment]
@abbasi-saqib 
Can you try to run the command as admin and check if you get same error ?
Also Do you have any other driver apart from C ? where you can install the sdk ?

**Comment by abbasi-saqib** [comment]
There is no other drive apart from C: and same error even for running as administrator

**Comment by darshankawar** [comment]
Keeping this issue open for further triage, as I am unable to replicate this issue.

**Comment by kf6gpe** [comment]
Since this is in the tools queue, dropping `waiting for customer response`.

**Comment by christopherfujino** [comment]
> Did everything according to the guideline . Even created directory in c:/src/flutter . But same error . Even set the permission to flutter director for everyone but still find the issue

DId you add `C:/src/flutter` to your path? the screenshot you linked has a flutter path under Documents on your path, so I would assume when you type `flutter` in the command line, it is running the binary in Documents and then failing because your user does not have permissions.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
