### ISSUE TITLE
why this error?

### ISSUE THREAD

**Issue by ruhulamin602** [flutter/flutter#71147]
Why this Error?

I/flutter ( 7906): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7906): The following assertion was thrown during performLayout():
I/flutter ( 7906): 'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 279 pos 12:
I/flutter ( 7906): 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
I/flutter ( 7906): not true.

**Comment by darshankawar** [comment]
@ruhulamin602 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by ruhulamin602** [comment]
Thanks for your reply.
I think I found a solution.

**Comment by darshankawar** [comment]
@ruhulamin602 Closing this based on your comment above.
