### ISSUE TITLE
In-app purchase plugin - subscription change support

### ISSUE THREAD

**Issue by 33-Elephants** [flutter/flutter#71148]
Please add an ability to upgrade/downgrade subscriptions on Android platform: [Documentation](https://developer.android.com/google/play/billing/subscriptions#change)

Currently there is no way to pass old SKU and proration mode to in-app purchase engine.

**Comment by darshankawar** [comment]
Closing this as duplicate of [32395](https://github.com/flutter/flutter/issues/32395)
