### ISSUE TITLE
[firebase_auth][ios] Unable to catch exception from PhoneAuthProvider.credential

### ISSUE THREAD

**Issue by sooxt98** [flutter/flutter#71158]
Flutter just throw PlatformException and ignore the try catch, and the verification code is valid

``` dart
try {
      final AuthCredential credential = PhoneAuthProvider.credential(
        verificationId: _verificationId,
        smsCode: mySmsCode,
      );
} catch (e) {
      return e.toString();
}
```

Native exception:
`PlatformException (PlatformException(invalid-verification-code, The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user., {code: invalid-verification-code, message: The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user., nativeErrorMessage: The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user., nativeErrorCode: 17044, additionalData: {}}, null))`

Related issue:
https://stackoverflow.com/questions/64479245/how-can-i-catch-the-error-when-the-wrong-sms-code-is-entered-in-flutter

My Dependencies:
firebase_core: "0.5.2"
firebase_auth: "^0.18.3"

**Comment by iapicca** [comment]
@sooxt98 
to report a bug with **firebase** please open an issue in the dedicated [github repo](https://github.com/FirebaseExtended/flutterfire/issues)
