### ISSUE TITLE
CachingAssetBundle._loadString does not handle load() returning null

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#7115]
```dart
 Future<String> _fetchString(String key) async {
    final ByteData data = await load(key);
    return UTF8.decode(data.buffer.asUint8List());
  }
```
Yet clearly some implementations of load() do return null.

**Comment by eseidel** [comment]
Yeah, if you attempt to loadString with an invalid key you hit this.

[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The getter 'buffer' was called on null.
Receiver: null
Tried calling: buffer
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:138:29)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

**Comment by Hixie** [comment]
The theory behind asset bundles is that you know what's in them, so you'd never request something that wasn't there...

...but yeah, we should at a minimum display a pretty error in checked mode.

**Comment by jason-simmons** [comment]
Fixed by https://github.com/flutter/flutter/pull/9325
