### ISSUE TITLE
local_auth - TouchID Bypass (iOS)

### ISSUE THREAD

**Issue by michaelgobbers** [flutter/flutter#71150]
## Use case

We have noticed that it is not possible to set the accessControl parameter on iOS for the  LocalAuthentication.authenticateWithBiometrics method in the local_auth package. This would allow attackers with physical device acces to bypass the biometrics auth using objection (https://github.com/sensepost/objection).
More info on the vulnerability can be found here: https://github.com/sensepost/objection/wiki/Understanding-the-iOS-Biometrics-Bypass
 
## Proposal

Add a parameter to the authenticateWithBiometrics method of LocalAuthentication class in the local_auth pacakge that allows us to set the accessControl parameter of the evaluateAccessControl method in LAContext method.
```
func evaluateAccessControl(_ accessControl: SecAccessControl, 
                 operation: LAAccessControlOperation, 
           localizedReason: String, 
                     reply: @escaping (Bool, Error?) -> Void)
```

**Comment by stuartmorgan** [comment]
> We have noticed that it is not possible to set the accessControl parameter on iOS for the LocalAuthentication.authenticateWithBiometrics method in the local_auth package. This would allow attackers with physical device acces to bypass the biometrics auth using objection (https://github.com/sensepost/objection).

Unless I'm misunderstanding the docs there, an "attacker" could create a *new copy* of the application that bypasses biometrics checks, and sideload it. It's not clear to me how that constitutes an attack.

> More info on the vulnerability can be found here: https://github.com/sensepost/objection/wiki/Understanding-the-iOS-Biometrics-Bypass

That doesn't seem to be describing a vulnerability. The prerequisite for this working is that the person changing the behavior has the ability to patch the binary. If someone can patch a binary, they can change its behavior in arbitrary ways.

> Add a parameter to the authenticateWithBiometrics method of LocalAuthentication class in the local_auth pacakge that allows us to set the accessControl parameter of the evaluateAccessControl method in LAContext method.

The plugin doesn't use that method, so I'm not sure what you are proposing adding it to. It's also not clear to me how this proposal relates to the above; someone with the ability to patch arbitrary ObjC calls can simply call the reply callback with `true` and get the same behavior.

Closing, as this doesn't appear to be describing a security issue, or an effective mitigation even if it were. If I'm misunderstanding, please provide a link to a discussion of how this constitutes an actual security issue and how your proposed change would prevent it.
