### ISSUE TITLE
Interesting stable branch bug

### ISSUE THREAD

**Issue by computervirus91** [flutter/flutter#71159]
I am using flutter stable to build a simple app.
PFA for the bug.

The full code is under main.dart with some SQLite code that help in code generation in a different file.
The committed branch(on the left) runs, but the right one doesn't. I built and ran quite a number of changes and then this started happening without any reason.
![ksnip_20201124-222231](https://user-images.githubusercontent.com/45018854/100126593-25e1c780-2ea4-11eb-849f-3ef690656f8a.png)

**Comment by sidrao2006** [comment]
Hello @computervirus91 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you!

**Comment by computervirus91** [comment]
@sidrao2006 thk u 4 rply...this was from jsonDecoder for a json string with a comma before ']'.
