### ISSUE TITLE
Allow us to change margin of the checkbox in a DataTable

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#71156]
## Use case

Currently the margin between the checkbox and content in the first column is the horizontalMargin:
https://api.flutter.dev/flutter/material/DataTable/horizontalMargin.html

I want to be able to change the margin for the checkbox independently.

## Proposal

Add new property to the DataTable and DataTableThemeData called `checkboxHorizontalMargin` to allow us to set this value independently of horizontalMargin.

**Comment by chinmoy12c** [comment]
Working on this issue.
