### ISSUE TITLE
Devicelab "smoke_catalina_hot_mode_dev_cycle_ios__benchmark" failure "Error while starting Kernel isolate task"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#71178]
https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyL2IxOGYxYjgxZmUwOWExZjJiZWEzOWVhYWM5Y2M3MDllMWFjNjAwY2YMCxIEVGFzaxiAgJitlZL0Cww

```
2020-11-24T13:18:51.833071: stdout: Performing hot restart...                                       
2020-11-24T13:18:51.833173: stdout: Restarted application in 1,622ms.
2020-11-24T13:19:01.844560: stdout: Benchmarking hot reload
2020-11-24T13:19:02.336088: stdout: Performing hot reload...                                        
2020-11-24T13:19:02.341727: stdout: Reloaded 0 libraries in 491ms.
2020-11-24T13:19:02.344558: stdout: 
2020-11-24T13:19:06.671623: stderr: Hot reload was rejected:
2020-11-24T13:19:06.671728: stderr: Error while starting Kernel isolate task.
stderr: Try performing a hot restart instead.
2020-11-24T13:19:06.672008: stdout: Performing hot reload...                                        
2020-11-24T13:19:06.672084: stdout: Try again after fixing the above error(s).
2020-11-24T14:16:27.981250: Task execution finished
```

**Comment by christopherfujino** [comment]
This could have been broken by any of the following 3 engine rolls:

* https://github.com/flutter/flutter/commit/e5c43848a716e43e55e01db3e4312cca70db0f01
* https://github.com/flutter/flutter/commit/8241757eb192e6eaa98a00767e5fbed35f65e584
* https://github.com/flutter/flutter/commit/13ce828e32e8b209886725f79fd424029d422523

**Comment by iskakaushik** [comment]
I'm pausing the engine->framework roller until this is resolved.

**Comment by christopherfujino** [comment]
This appears to be a pre-existing flake, I can find the same failure as early as https://github.com/flutter/flutter/commit/8e73bab94c6051317c9fa4279a3733b6ee2a3ef2 (and likely earlier)

https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyLzhlNzNiYWI5NGM2MDUxMzE3YzlmYTQyNzlhMzczM2I2ZWUyYTNlZjIMCxIEVGFzaxiAgJi5tqKfCgw

**Comment by christopherfujino** [comment]
Since this test repeatedly fails on https://github.com/flutter/flutter/commit/b18f1b81fe09a1f2bea39eaac9cc709e1ac600cf, while it passed on the previous, I landed a revert to see if it will fix the tree https://github.com/flutter/flutter/pull/71180

**Comment by keyonghan** [comment]
Unfortunately it hangs with the same error on the revert.

**Comment by christopherfujino** [comment]
Ok, I will re-land goderbauer's commit.

**Comment by christopherfujino** [comment]
This test was marked flaky in https://github.com/flutter/flutter/pull/71188

**Comment by Piinks** [comment]
I am going to downgrade this since it is not breaking the build anymore in its flaky state. Currently tasks are backed up so we are waiting to evaluate if the flakiness has persisted.

**Comment by jonahwilliams** [comment]
The error message comes from https://github.com/dart-lang/sdk/blob/55bb15a8cbbe7c5ff2242d74c5e18370ba9b6922/runtime/vm/kernel_isolate.cc#L1016

Unfortunately it doesn't tell us much about what failed. Ideally there would be a verbose mode that would include more error logs during the hot reload. @zanderso @aam do you know what flag controls OS::PrintErr?

**Comment by zanderso** [comment]
The logging in that file is guarded by the Dart VM command line flag `--trace-kernel`.

**Comment by aam** [comment]
@jonahwilliams asked:

> do you know what flag controls OS::PrintErr?

There is no generic flag for that. 
You can try adding --trace-reload and --trace-reload-verbose flags that enable more trace prints during hot reload to https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L63.

**Comment by jonahwilliams** [comment]
The latest run of this is passing

**Comment by jonahwilliams** [comment]
Test is still passing, might have been a device issue? I'm lowering the priority but still plan to up the verbosity

**Comment by jonahwilliams** [comment]
removing assignment because I will be OOO
