### ISSUE TITLE
Flutter testing throwsA() matcher doesn't match exception of async functions.

### ISSUE THREAD

**Issue by UliPrantz** [flutter/flutter#71183]
## The problem

I want to test that a function which is async and normally returns a future throws a specific type of error when the input is in a bad state. The problem is the the following:

```
Expected: throws Type:<MyCostumeError>
  Actual: <Instance of 'Future<dynamic>'>
```
## Steps to reproduce

And the code looks like this:

```dart
class MyCostumeError extends Error {}

Future<String> myAsyncFunction(String input) async {
  String result = await someComputation(input); // --> this one throws MyCostumeError()
  return result;
}

void main() {
  test("Test async throws meaningful error", () {
    expect(myAsyncFunction("Test input"), throwsA(isA<MyCostumeError>()));
  }
}
````

The only thing that works as a matcher is `throwsException` everything I tried to match the type of the exception just throws the error mentioned at the top. Seems like `throwsA()` and all the not deprecated type matchers doesn't work for async functions. I already tried a bunch different combinations for the expect() function. Things like `await myAsyncFunction()` or `isInstanceOf<>()` instead of `isA<>()` and many others but nothing worked.

By the way what is up with the matchers most of them are deprecated but the new API uses the exact same classes under the hood just wrapped in lambda functions.

The output of `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale de-DE)
    • Flutter version 1.22.4 at /Users/Uli/opt/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Uli/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/Uli/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Uli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Hi @UliPrantz 
What should be the expected exception / error message in this case ?
I tried your code sample and get below:

<img width="852" alt="Screenshot 2020-11-25 at 1 26 47 PM" src="https://user-images.githubusercontent.com/67046386/100198887-7ac42300-2f22-11eb-9262-5870e728ea23.png">

**Comment by UliPrantz** [comment]
Yeah thats the thing! This is as said in my issue a test case which expects that an error is thrown. Therefore the test should pass! It should say test passed because the expected error was thrown. Not error.

Do you understand? Hope I could clarify it.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!


```

</details>

**Comment by kf6gpe** [comment]
I'm not sure what team should be working on this if we choose to do it. Any pointers?

**Comment by UliPrantz** [comment]
I don't know the different teams of flutter. But I would assign it to the team who coded it (the test framework of flutter). Which team ever coded the test framework should be responsable for it.
Maybe just look at the commits of the `throwsA()` function and assign it to the team which implemented this function. Unfortunately I currently haven't got time to do anything flutter related.

**Comment by Hixie** [comment]
`expect` comes from the `test` package, I would file a bug there: https://github.com/dart-lang/test/issues/new/choose

**Comment by goderbauer** [comment]
I modified the code posted in the first comment to make it actually runnable:

```dart
import 'package:flutter_test/flutter_test.dart';

class MyCostumeError extends Error {}

Future<String> myAsyncFunction(String input) async {
  final String result = await Future<String>.delayed(const Duration(seconds: 1), () {
    throw MyCostumeError();
  });
  return result;
}

void main() {
  test('Test async throws meaningful error', () {
    expect(myAsyncFunction('Test input'), throwsA(isA<MyCostumeError>()));
  });
}
```

This test passes as expected.

If you're still experiencing the issue, can you post code that is fully runnable (not just pseudo code), which reproduces the problem you're seeing? Thanks!

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rk0cc** [comment]
Sorry for late response, it solved when you parse as a function

```dart
expect(() => myAsyncFunction("Test input"), throwsA(isA<MyCostumeError>()));
```
