### ISSUE TITLE
AuthenticatedClientError for "Linux web_benchmarks_html"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#71182]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_benchmarks_html/850/overview

```
Unhandled exception:
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 500
  Response body:
Expected to find 1 task for Linux web_benchmarks_html, but found 0
```

**Comment by keyonghan** [comment]
@CaseyHillers Do you mind take a look?

**Comment by keyonghan** [comment]
This error seems to happen when builder calls `update-task-status` which then iterate to check builderName before the builderName is ready. A rerun should fix the tree, but the issue needs to be fixed.

Remove it out of queue.

**Comment by christopherfujino** [comment]
> This error seems to happen when builder calls `update-task-status` which then iterate to check builderName before the builderName is ready. A rerun should fix the tree, but the issue needs to be fixed.
> 
> Remove it out of queue.

I'm going to reland the commit i reverted, which should essentially re-run the test

**Comment by CaseyHillers** [comment]
Thanks Keyong. This is from my PR. As a quick fix forward, do you think we can update the cron job on the chromebot statuses to be every 1 minute? It's at 3 minutes which is too slow (https://github.com/flutter/flutter/issues/66846)

**Comment by CaseyHillers** [comment]
Actually, I can put up a revert. I need to investigate why the in progress rerun task is still failing with a 5 minute run time.

**Comment by keyonghan** [comment]
chromebot status update API takes time. I am not sure if 1 min is enough.

**Comment by CaseyHillers** [comment]
> chromebot status update API takes time. I am not sure if 1 min is enough.

Oh interesting, do you know how long? I didn't account for it to be a long running endpoint. In that case, i'll need to prioritize the pub sub issue linked above.

**Comment by keyonghan** [comment]
seems around 30-50 seconds - based on https latency.
