### ISSUE TITLE
Embedding can send bad mouse events on Big Sur

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#71190]
This is potentially the root cause of https://github.com/flutter/flutter/issues/64961. Full explanation of the incoming events is at https://github.com/flutter/flutter/issues/70529#issuecomment-733330469

There is a workaround being investigated at the Framework level for this, but really we should be ensuring that the embedding sends valid events in the first place.

Steps to Reproduce:

Enable HiDPI, follow instructions at https://github.com/flutter/flutter/issues/64961#issue-689402208

Follow up:

(From @stuartmorgan:) `If you are able to repro once you enable HiDPI, I would just need a log of everything going through [FlutterEngine sendPointerEvent:] during a bad click as a starting point to debug.`

**Comment by Hixie** [comment]
Moving to P2 since this is blocking a P2 bug.

**Comment by cbracken** [comment]
Fix is out for desktop in https://github.com/flutter/engine/pull/23111

**Comment by cbracken** [comment]
This has landed in the engine, it'll be fixed in the framework once it rolls the the framework -- this typically happens within a day.

**Comment by cbracken** [comment]
This has now rolled to the framework on master branch.
