### ISSUE TITLE
Flutter engine crash in customer

### ISSUE THREAD

**Issue by meiwin** [flutter/flutter#71197]
Internal: b/174118592

Stacktrace:

```
Thread 0 (id: 0x00000303) CRASHED [EXC_BAD_ACCESS / KERN_INVALID_ADDRESS @ 0x00000000 ]
0x00000001053f5880(Flutter + 0x00031880)
0x00000001053f5878(Flutter + 0x00031878)
0x0000000105451640(Flutter + 0x0008d640)
0x000000010544dc60(Flutter + 0x00089c60)
0x0000000105451c40(Flutter + 0x0008dc40)
0x000000010544dc60(Flutter + 0x00089c60)
0x0000000105450468(Flutter + 0x0008c468)
0x000000010544dc60(Flutter + 0x00089c60)
0x0000000105451c40(Flutter + 0x0008dc40)
0x000000010544dc60(Flutter + 0x00089c60)
0x000000010544bea4(Flutter + 0x00087ea4)
0x00000001056d6f2c(Flutter + 0x00312f2c)
0x00000001056d7b34(Flutter + 0x00313b34)
0x00000001056d7244(Flutter + 0x00313244)
0x00000001056ddf44(Flutter + 0x00319f44)
0x0000000105402bc4(Flutter + 0x0003ebc4)
0x0000000105404b38(Flutter + 0x00040b38)
```

There isn't repro steps available at the moment.

**Comment by darshankawar** [comment]
Hi @meiwin 
Can you provide more information (if any) on this crash, like, platform on which customers are seeing this, Flutter version the app is on and anymore details that can help to analyze this issue better.
Thanks.

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/71197#issue-750419154 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/71197#issue-750419154 internal engine#defa8be2b10650dad50dfee9324ed8d16eeec13f ios release arm64

**Comment by mehmetf** [comment]
This is similar to https://github.com/flutter/flutter/issues/70577

**Comment by iskakaushik** [comment]
Adding @cyanglaz in-case he has some context.

**Comment by gaaclarke** [comment]
Looks like a nullptr: https://github.com/flutter/engine/blob/96d63e5b226cf9f3cc424a8c6be6a95ffd1b2d27/shell/platform/darwin/ios/ios_external_view_embedder.mm#L71

That function just calls a method on an object that is retained as as shared_ptr.

```c++
SkCanvas* IOSExternalViewEmbedder::CompositeEmbeddedView(int view_id) {
  TRACE_EVENT0("flutter", "IOSExternalViewEmbedder::CompositeEmbeddedView");
  FML_CHECK(platform_views_controller_);
  return platform_views_controller_->CompositeEmbeddedView(view_id);
}
```

**Comment by cyanglaz** [comment]
@gaaclarke wouldn't `FML_CHECK(platform_views_controller_);` crash first? Does `FML_CHECK` run on release?

**Comment by chinmaygarde** [comment]
Triage: In the tree at commit https://github.com/flutter/engine/commit/defa8be2b10650dad50dfee9324ed8d16eeec13f the platform views controller is a raw pointer. @iskakaushik changed that to be shared pointer in https://github.com/flutter/engine/commit/279c1cffbe. @iskakaushik: I don't see an explicit assertion there to make sure that the shared pointer cannot be null. @cyanglaz's point is well made however that the `FML_CHECK` should trip in release builds. But, we are not seeing the error on line 70. The internal issue seems to point to https://github.com/flutter/flutter/issues/70577 as a likely fix.

So, based on the following, we can surmise that: 
1. The state of tree is significantly different from what it was.
2. There is a likely fix for this issue.
3. There is no reproducible test case yet.

@meiwin: Can you try reproducing this at ToT or with the suggested fixes incorporated and report if you see this issue again?

**Comment by chinmaygarde** [comment]
@Hixie: Why was the the milestone removed? The comment requested a reply from the author.

**Comment by Hixie** [comment]
(quoting from #announcements:) I have updated the Issue Hygiene page to no longer require that any assigned issue also have a milestone, and will no longer be chasing people down when the milestone field isn't set. This change was made because in practice milestones were not proving to be a useful tool across the project. You are still welcome to use the field if you find it useful for your own purposes. I expect we will further tweak how we use this field in the coming months to be more driven by and useful for the release process specifically. As part of this the Overdue milestone has been removed and bugs will no longer be automatically moved out of milestones each month if they have slipped past their milestone date. The "Cannot assign" and "No milestone needed" milestones are similarly gone since they're no longer relevant.

**Comment by chinmaygarde** [comment]
The internal bug has no updates to the previous query. Adjusting the priority here appropriately.

**Comment by meiwin** [comment]
> The internal bug has no updates to the [previous query](https://github.com/flutter/flutter/issues/71197#issuecomment-744643052). Adjusting the priority here appropriately.

My apology for slow in replying.

I have just checked and no longer seeing this crash in the latest app version -- as mehmetf@ pointed out, it is similar to #70577.

I'm closing the bug.
