### ISSUE TITLE
Contributing guide mentions Atom

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7119]
For https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

We probably want to remove the Atom references from this doc.

Thanks to @raju-bitter for the report!

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
@sethladd who knows about the test coverage stuff (lcov)?

**Comment by abarth** [comment]
Probably me.  What would you like to know?

**Comment by mit-mit** [comment]
Is there a lcov plugin for IntelliJ that you happen to know is working against the files we generate?

**Comment by mit-mit** [comment]
@devoncarew do you have any experience with lcov in IntelliJ

**Comment by devoncarew** [comment]
I don't, but IntelliJ does have good support for code coverage in general. @jwren and @stevemessick would know more; I know we've wired up support for code coverage with our test runner (for the Dart plugin).

When we wire up running tests via `flutter test`, we'll want to make sure we get coverage support as well.

**Comment by jwren** [comment]
Is there something that you can do with Icov that you can not do with the coverage support in Dart right now?

@alexander-doroshko

**Comment by alexander-doroshko** [comment]
I don't know what lcov does. IntelliJ IDEA is able to collect/show coverage for Dart Command Line Apps. If it is possible to run tests as a standard dart app (not as 'pub run test' or 'flutter test') then just configure Dart Command Line App in Run | Edit Configuration and click Run With Coverage button.

**Comment by mit-mit** [comment]
@alexander-doroshko lcov is a format for capturing code coverage information. It looks like IntelliJ supports it when testing js coverage with Karma:
https://www.jetbrains.com/help/idea/2016.3/coverage-tool-window.html

But looks like the coverage tool window is not available for dart code?

**Comment by alexander-doroshko** [comment]
Yes, looks like Coverage tool window is not shown. Only gutter marks in the editor and file count in the Project View.

**Comment by eseidelGoogle** [comment]
Flutter collects coverage via `flutter test --coverage`  It also has a --merge-coverage and --coverage-path directive which one can use when you want to iterate on part of the system (and still get coverage data) without doing a full coverage run.

I believe we only use the lcov tool itself for --merge-coverage, and otherwise just spit out lcov-compatible files since afaict that's the standard format.  @abarth and @cbracken wired this all up an would know more if you need.

**Comment by sethladd** [comment]
Where did we end up with this? Can we just remove the mention of Atom from our CONTRIBUTING guide?

**Comment by abarth** [comment]
The CONTRIBUTING.md documents how to contribute to the flutter.git repository.  Currently Atom is required for some kinds of contribution (specifically having to do with visualizing lcov test coverage data).  It's possible that we could improve IntelliJ to support those use cases, but it does not support those use cases today.  (IMHO, we should improve IntelliJ in this way.)

I'll clean up CONTRIBUTING.md to clarify that you only need Atom if you're working with test coverage.

**Comment by abarth** [comment]
I filed https://github.com/flutter/flutter-intellij/issues/718 requesting support for lcov in IntelliJ
