### ISSUE TITLE
Url_launcher on iOs: canlaunch returns false for valid app schema

### ISSUE THREAD

**Issue by xale76** [flutter/flutter#71205]
hello, canLaunch returns false for myschema://otp/a/b url where myschema:// is a custom url from my Cordova app tested on iOs to be launchable (i.e. from a link in a webpage or from another app of mine).
Please help I need to release asap

**Comment by darshankawar** [comment]
@xale76 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.

**Comment by Alessandro-PM** [comment]
@darshankawar 

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Versione 10.0.19041.630], locale it-IT)
    • Flutter version 1.22.4 at C:\flutter\flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\asbenagl\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.8052

• No issues found!

in the code

 goToVisitami() async {
    String utol = 'visitami://';
    if (await canLaunch('visitami://') == true) {
      await launch(utol);
    } else {
      // qui differenziare se ios o android, per iOs = https://itunes.apple.com/it/app/pages/id1045569314?mt=8
      String uri = (Platform.isIOS)
          ? 'https://<url to store>'
          : 'https://<url to store>';
      await launch(uri);
    }
  }

info.plist

<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>visitami</string>
    </array>

if I put <a href="visitami://">test</a> in a web page the app starts on iOs

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mzm008** [comment]
I got the soma problem, and  can not resolved  . wow
