### ISSUE TITLE
Change the way a button is disabled

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#71211]
## Use case

when we set the `onPressed` to null and the button becomes disabled, it does not really seem so convenient.

Currently to disable a button we do the following:
```dart
ElevatedButton(
   child: Text('I am a disabled button!'),
   onPressed: null,
);
```

A better way would be:
```dart
ElevatedButton(
  child: Text('I am a disabled button!'),
  enabled: false, // this is way better
  onPressed: () {
        // some code here
  },
);
```

## Proposal

Adding a new property to buttons which is `enabled`, takes a boolean, by default is true, and if false the button is disabled!

**Comment by YazeedAlKhalaf** [comment]
The code is in here for the material library:
https://github.com/flutter/flutter/blob/2ceb371d214cfe9122c2aeec7625863b21a1e41c/packages/flutter/lib/src/material/button.dart#L278-L282

```
  /// Whether the button is enabled or disabled.
  ///
  /// Buttons are disabled by default. To enable a button, set its [onPressed]
  /// or [onLongPress] properties to a non-null value.
  bool get enabled => onPressed != null || onLongPress != null;
```

**Comment by GaspardMerten** [comment]
I think that it generally makes sense to disable a button based on the fact that there is no action specified. That way, when the button is disabled, it can literally not call any method, in a way we could argue that it is more secure. Just writing the following code is sufficient.

`
void myFunc() => print('Hello World');

ElevatedButton(
   child: Text('I am a disabled button!'),
   onPressed: enabled ? myFunc : null,
);`

**Comment by pedromassangocode** [comment]
Hi @YazeedAlKhalaf 
I see there's an open issue (https://github.com/flutter/flutter/issues/58867) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
