### ISSUE TITLE
Issue with gradle gradle-6.1.1-all.zip

### ISSUE THREAD

**Issue by momoDragon** [flutter/flutter#71212]
**Error When running:** `flutter build apk`

* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/mozesong/Documents/GitHub/propo/propo_customer/build/app/intermediates/flutter/profile/libs.jar.
         > Transform's input file does not exist: /Users/mozesong/Documents/GitHub/propo/propo_customer/build/app/intermediates/flutter/profile/libs.jar. (See https://issuetracker.google.com/issues/158753935)

**gradle-wrapper.properties**

#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Followed a workaround here:** 
https://issuetracker.google.com/issues/158753935

**Issue:**
Release apk size was x2 larger than previously and crashes on launch

**Comment by darshankawar** [comment]
@momoDragon 
Flutter doesn't yet support AGP 4.0+. You may need to switch to AGP < 4.
See [this](https://github.com/flutter/flutter/issues/58247) open issue for further details and reference.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
