### ISSUE TITLE
Developers don't know how to test the performance of their apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7121]
The Flutter Framework/engine being fast is only one part of a final app being fast.  Customers also need to know how to test their apps for performance.  We could offer some guidance here.

Specifically customer: charts has been asking for some docs around this topic.  They currently use Google's internal testing setup, so we may have more options for their case.

**Comment by eseidelGoogle** [comment]
#5550 is about debugging performance, this is about testing/maintaining performance once fixed. :)

**Comment by Hixie** [comment]
@filiph @Sfshaza @LarkAscending Is this something that is on your radar?

**Comment by sethladd** [comment]
@Sfshaza is this a dupe issue, or is this the canonical issue for "how do I think about and do anything about performance?" doc

**Comment by Sfshaza** [comment]
I see this as a dupe issue of https://github.com/flutter/flutter/issues/13503.  Closing.
