### ISSUE TITLE
connectivity_macos

### ISSUE THREAD

**Issue by weiwei00200** [flutter/flutter#71214]

**Comment by GaspardMerten** [comment]
Please provide a description of your issue. Otherwise, we can not really help you. If you desire that MacOS support for the connectivity package, please create a [Feature request](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=).

**Comment by darshankawar** [comment]
@weiwei00200 
As mentioned above, please provide details on the issue / question you are facing.

**Comment by stuartmorgan** [comment]
> If you desire that MacOS support for the connectivity package

It already does.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
