### ISSUE TITLE
add new version gradle to gradle-wrapper

### ISSUE THREAD

**Issue by mohammadmohseni9** [flutter/flutter#71226]
hi dear . 
when i start a new project with vs code or android studio
the project runs with old version of gradle . this in itseld causes problem such as inefficiency and incompatibility with new code.
thats why i add this here , i hope this taken into flutter project.

android/gradle/gradle-wrapper

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

Replace top line of code with the next line

--->>
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

**Comment by pedromassangocode** [comment]
Hi @mohammadmohseni9 
This was recently fixed by https://github.com/flutter/flutter/pull/70808 and the changes are on master branch.
