### ISSUE TITLE
ThemeData.copyWith missing primarySwatch

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#7122]
final myTheme = Theme.of(context).copyWith(primarySwatch: Colors.blue);

myTheme will still use the default primarySwatch. Looking at the copyWith implementation, it appears to simply be missing any logic to copy that parameter (though the param is specified in the signature)

**Comment by HansMuller** [comment]
Looks like a simple oversight. I'll fix it.

**Comment by Hixie** [comment]
Gavin, can you elaborate on what you're trying to do?
