### ISSUE TITLE
Using 'as' in cast results in runtimetype error on android

### ISSUE THREAD

**Issue by Goatmaster-Hub** [flutter/flutter#71221]
Hi, 
when i run the following code it works fine in the browser but when i try to run the same code on a android Device i get the an exception.
Codesample:
 int test = 1;
 double myDouble = test as double;

Error:
E/flutter ( 6634): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'double' in type cast

My flutter doctor -v output: 
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale de-DE)
    • Flutter version 1.24.0-10.2.pre at C:\Flutter\flutter
    • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\SDK\
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\SDK\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
PS C:\Users\Timon Geisbauer\git\modules\module-tester> flutter doctor -v
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale de-DE)
    • Flutter version 1.24.0-10.2.pre at C:\Flutter\flutter
    • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\SDK\
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\SDK\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (5 available)
    • SM T510 (mobile)                   • R52M614Q3KX   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (5 available)
    • SM T510 (mobile)                   • R52M614Q3KX   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!

**Comment by darshankawar** [comment]
@Goatmaster-Hub 
This issue I believe belongs to dart-lang repo and not Flutter. Also, please check [this](https://github.com/dart-lang/site-www/issues/736#issuecomment-383169613) issue comment as to when to use `cast` term. 

If you have further question or issue related to it, please open an issue here https://github.com/dart-lang.
Closing. If you disagree, write in comments and I'll reopen it.
