### ISSUE TITLE
CupertinoThemeData equals and hashCode

### ISSUE THREAD

**Issue by pak3nuh** [flutter/flutter#71222]
Hello all.

In my app, I allow users to change some colors of the theme.
I use MaterialApp as the main widget so it uses ThemeData under the covers. It all works well unless I set the cupertinoOverrideTheme property.
The issue is the CupertinoThemeData doesn't respect the equals and hashCode contracts, unlike every other property on ThemeData. Even the equals operator in ThemeData seems to suggest this.

## Steps to Reproduce

    test('should respect equals and hashCode', (){
      final a = CupertinoThemeData();
      final b = CupertinoThemeData();
      expect(ThemeData(cupertinoOverrideTheme: a), equals(ThemeData(cupertinoOverrideTheme: b)));
    });

**Expected results:**
Test should pass

**Actual results:**
Test is failing

Tested with flutter 1.22.0 but it seems that it hasn't changed in [master](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/theme.dart#L168) as well.

**Comment by darshankawar** [comment]
@pak3nuh I get following test failure running your code sample:

<img width="881" alt="Screenshot 2020-11-25 at 6 23 52 PM" src="https://user-images.githubusercontent.com/67046386/100230227-72341280-2f4b-11eb-8ac6-b49bd97e05e3.png">

Is this the correct interpretation of the issue ?

**Comment by pak3nuh** [comment]
@darshankawar yes it is correct.
If we apply the same rationale for other ThemeData properties, the test passes.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>
