### ISSUE TITLE
Change Select Flexible instead of Select Row

### ISSUE THREAD

**Issue by cmoulicms** [flutter/flutter#71230]
[https://codelabs.developers.google.com/codelabs/flutter#4](url)

**Add a responsive Send button Section**

Wrap the TextField inside a Flexible 

Wrong: 1. Select Row
Right: 1. Select Flexible

**Comment by iapicca** [comment]
![image](https://user-images.githubusercontent.com/45637986/100270453-c695bd00-2f60-11eb-9523-d9a3a29a17f9.png)

isn't it textfield instead of row?

**Comment by darshankawar** [comment]
@cmoulicms 
There's [similar](https://github.com/flutter/website/issues/4881) issue reported a while back which has been transferred to Flutter's website github [repo](https://github.com/flutter/website/issues/4881). I'd suggest you to follow-up there for updates and any questions.
Closing from here. If you disagree, write in comments and I'll reopen it.
