### ISSUE TITLE
[file_selector] Update example app to show what to do when a user press the cancel button.

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#71237]
## Use case

None of the example calls handle the user pressing cancel (in which case the returned path will be null). Right now canceling any dialog in the example will throw an exception.

## Proposal
Update all examples to handle the **null** case.

**Comment by stuartmorgan** [comment]
I'll have a PR soon in the flutter-desktop-embedding repository that will temporarily add file_selector implementations for desktop (until we can figure out a testing story, and move them to flutter/plugins), which will make testing this easier.

**Comment by stuartmorgan** [comment]
I fixed this during the NNBD migration for the plugin, and forgot to close this issue:
https://github.com/flutter/plugins/search?q=%22operation+was+canceled+by+the+user%22
