### ISSUE TITLE
Proposal to add Groups icon to Flutter Material Icons class.

### ISSUE THREAD

**Issue by NeatFastro** [flutter/flutter#71233]

**Comment by neattike** [comment]
"groups" icon from material library is not present in flutters default material icons collections
![Material groups icon snip](https://user-images.githubusercontent.com/50900820/100272242-a093fc80-2f0f-11eb-94c7-2823f19c6a3a.png)

**Comment by guidezpl** [comment]
Cc @willlarche

**Comment by neattike** [comment]
I want to add the missing icon but i need a little guidance.
i have this flutter repo cloned at my local machine but its behind from this repo.
should run "git pull" in it and then add the icon (code) and then run "push it"?
do i need tests for this kind of feature?

**Comment by guidezpl** [comment]
Unfortunately, updating icons requires internal Google access https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by neattike** [comment]
> Unfortunately, updating icons requires internal Google access https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons

Yeah find out when i tried to fix (add) it.

**Comment by willlarche** [comment]
I have a request to
The icon team to generate an updated font. Should be unblocking us soon.

**Comment by YazeedAlKhalaf** [comment]
> I have a request to
> The icon team to generate an updated font. Should be unblocking us soon.

Great 😎
