### ISSUE TITLE
[url_launcher] can't launch external url on ios 14 if default browser is set to chrome

### ISSUE THREAD

**Issue by SamBergeron** [flutter/flutter#71245]
IOS 14 gives you the opportunity to swap default browsers (ref: [here](https://support.apple.com/en-us/HT211336)), it appears that the `canLaunch()` function returns false in the case where Chrome is now the default browser on ios. The logic works fine on Android or on IOS 14 phones with safari set as the default and on IOS phones pre IOS 14 (because obviously safari is the default)

The `launch()` method appears to work regardless of if `canLaunch()` returns false.

snippet of the code
```
Future<bool> launchURL(String url) async {
    if (await canLaunch(url)) {
        return launch(url, forceSafariVC: false);
    }
    return false;
}
```

Pubspec import
```
# https://pub.dev/packages/url_launcher
  url_launcher: 5.7.10
```

Flutter doctor output:
```
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.1 at C:\flutter\flutter
    • Framework revision f30b7f4db9 (7 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.
```

Could be related to issue #71205

**Comment by darshankawar** [comment]
Hi @SamBergeron 
Check [this](https://github.com/flutter/flutter/issues/65936#issuecomment-720954413) issue comment and try the solution mentioned to see if it works for you.
Thanks.

**Comment by SamBergeron** [comment]
Yup that solved it, looks like I didn't look deep enough in the bugs.
