### ISSUE TITLE
iphone 7 crashed

### ISSUE THREAD

**Issue by theLeftBank** [flutter/flutter#71255]
Thread 43 crashed  io.flutter.1.ui
0 Flutter | txt::ParagraphTxt::Layout(double) (WordBreaker.cpp:55)
-- | --
1 Flutter | txt::ParagraphTxt::Layout(double) (memory:2621)
2 Flutter | flutter::Paragraph_layout(_Dart_NativeArguments*) (paragraph.cc:40)
3 Flutter | dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (native_arguments.h:169)
4 Flutter | dart::NativeEntry::LinkNativeCall(_Dart_NativeArguments*) (native_entry.cc:0)
5 App | Precompiled_Stub_CallBootstrapNative + 72
6 App | Precompiled_Paragraph__layout_16065589_1592 + 52
7 App | Precompiled_Paragraph_layout_7407 + 40
8 App | Precompiled_DefaultShaderWarmUp_warmUpOnCanvas__async_op_15011 + 2192
9 App | Precompiled__Closure_0150898_call_15448 + 68
10 App | Precompiled__AsyncAwaitCompleter_4048458_start_11291 + 68
11 App | Precompiled_DefaultShaderWarmUp_warmUpOnCanvas_2977 + 248
12 App | Precompiled_ShaderWarmUp_execute__async_op_15015 + 388
13 App | Precompiled__Closure_0150898_call_15448 + 68
14 App | Precompiled__AsyncAwaitCompleter_4048458_start_11291 + 68
15 App | Precompiled_ShaderWarmUp_execute_2978 + 308
16 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_27399801_initInstances_3052 + 228
17 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_SemanticsBinding_27399801_initInstances_2906 + 32
18 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_SemanticsBinding_RendererBinding_27399801_initInstances_3041 + 36
19 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_SemanticsBinding_RendererBinding_WidgetsBinding_27399801_initInstances_2984 + 36
20 App | Precompiled_BindingBase_BindingBase__2084 + 64
21 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_27399801__WidgetsFlutterBinding_BindingBase_GestureBinding_27399801__2882 + 344
22 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_27399801__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_27399801__3084 + 492
23 App | Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_SemanticsBinding_RendererBinding_WidgetsBinding_27399801__WidgetsFlutterBinding_BindingBase_GestureBinding_ServicesBinding_SchedulerBinding_PaintingBinding_SemanticsBinding_RendererBinding_WidgetsBinding_27399801__2936 + 316
24 App | Precompiled_WidgetsFlutterBinding_ensureInitialized_3046 + 48
25 App | Precompiled____main__anonymous_closure__15203 + 72
26 App | Precompiled_____rootRun_4048458_421 + 232
27 App | Precompiled_____rootRun_4048458__rootRun_4048458_342 + 504
28 App | Precompiled__CustomZone_4048458_run_11655 + 240
29 App | Precompiled_____runZoned_4048458_295 + 244
30 App | Precompiled____runZonedGuarded_443 + 468
31 App | Precompiled____main_15060 + 132
32 App | Precompiled____main_main_15061 + 100
33 App | Precompiled__Closure_0150898_call_15448 + 68
34 App | Precompiled_____runMainZoned_16065589__anonymous_closure___anonymous_closure__15269 + 496
35 App | Precompiled_____rootRun_4048458_421 + 232
36 App | Precompiled_____rootRun_4048458__rootRun_4048458_342 + 504
37 App | Precompiled__CustomZone_4048458_run_11655 + 240
38 App | Precompiled_____runZoned_4048458_295 + 244
39 App | Precompiled____runZonedGuarded_443 + 468
40 App | Precompiled_____runMainZoned_16065589__anonymous_closure__15270 + 136
41 App | Precompiled__Closure_0150898_call_15448 + 68
42 App | Precompiled_____startIsolate_1026248__anonymous_closure__15216 + 588
43 App | Precompiled__Closure_0150898_call_15449 + 72
44 App | Precompiled__RawReceivePortImpl_1026248__handleMessage_1026248_615 + 52
45 App | Precompiled_Stub_InvokeDartCode + 252
46 Flutter | dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) (dart_entry.cc:190)
47 Flutter | dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >) (dart_entry.cc:36)
48 Flutter | dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) (message_handler.cc:233)
49 Flutter | _ZNSt3__110__function6__funcIZN5tonic18DartMessageHandler9OnMessageEPNS2_9DartStateEE3$_0NS_9allocatorIS6_EEFvvEEclEv (message_handler.cc:294)
50 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:116)
51 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
52 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
53 CoreFoundation | ___CFRunLoopDoTimer + 880
54 CoreFoundation | ___CFRunLoopDoTimers + 276
55 CoreFoundation | ___CFRunLoopRun + 1640
56 CoreFoundation | CFRunLoopRunSpecific + 424
57 Flutter | fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
58 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:96)
59 libsystem_pthread.dylib | _pthread_start + 156

**Comment by theLeftBank** [comment]
~ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/jessica/flutter
    • Framework revision 1ad9baa8b9 (5 months ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jessica/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jessica/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • xuan的iPhone                • 00008020-000E65DC3492002E            • ios • iOS 13.3.1
    • iPhone SE (2nd generation) • 10BB4183-EE85-4385-8C7E-9E317F9CD2EF • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @theLeftBank 
Looks like you are using a very old Flutter version.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v`.

**Comment by theLeftBank** [comment]
> Hi @theLeftBank
> Looks like you are using a very old Flutter version.
> Can you please upgrade to the latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the issue persists, please provide your `flutter doctor -v`.

we can not upgrade to the latest Flutter version. I used flutter_boost which do not support the latest Flutter version to reach mixed. Is this issue a known issue?

**Comment by pedromassangocode** [comment]
Hi @theLeftBank 
I'm not sure, I've never seen this specific issue.
Maybe this has been fixed already and you can only verify it by upgrading. Even if Flutter fix it you will need to upgrade because we cannot update old versions.

I'm closing this for now, feel free to comment back if you update and the issue still appearing.
Thank you
