### ISSUE TITLE
Need A Widget To Prevent The Rendering Of Child Widget Rather Than Hiding

### ISSUE THREAD

**Issue by CNMathon** [flutter/flutter#71252]
In fact, I know that `Offstage` is good, but when I use `Offstage`, the widget is only hidden rather than prevented from rendering child widget. We need a way to prevented rendering. I would like to know if the team has any development plans in the near future? Thanks!

**Comment by darshankawar** [comment]
@CNMathon 
Can you elaborate on your use case along with proposal as how would you like the widget to address the issue ?
Thanks.

**Comment by azbuky** [comment]
@CNMathon have you tried using the [`Visibility`](https://api.flutter.dev/flutter/widgets/Visibility-class.html) widget?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
