### ISSUE TITLE
Not able to build apk file - "font-subset” can’t be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by jasnicaa** [flutter/flutter#71256]
Hi everyone,

I tried to build my apk file on my Mac Catalina but I am getting - "font-subset” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information. Chrome downloaded this file yesterday at 10:30 from flutter.dev". 

When I open the file in finder the path is flutter->bin->cache->artifacts->engine->darwin-x64->font-subset.

Tried deleting cash and restarting didn't help although I am able to build app in debug mode on my device.

Flutter doctor:

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/jasna.mitrovic/Developer/flutter
    • Framework revision 1aafb3a8b9 (13 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jasna.mitrovic/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM A217F (mobile) • R58N66EWBWB • android-arm64 • Android 10 (API 29)

Any thoughts on this?

**Comment by darshankawar** [comment]
Hi @jasnicaa 
Can you try by running `flutter build ios --no-tree-shake-icons` and see if it works ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by csells** [comment]
I ran into this today too and I was able to fix it with the instructions here: https://www.tenorshare.com/mac-os/apple-cannot-check-it-for-malicious-software.html
