### ISSUE TITLE
How can I stop installing devtools.

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#71251]
I am using Android Studio develop my Flutter app, but I found when I run my flutter app, it always run 'Installing DevTools' which I don't want to run.Though I clear my AS cache, it will still be run.Any help? 
![image](https://user-images.githubusercontent.com/32046282/100312413-3782b680-2fed-11eb-9f0f-471c34561ee7.png)

**Comment by darshankawar** [comment]
@tongyangsheng 
your question is better suited for StackOverflow, as this isn't a bug or feature request. Please consider asking this question on support channels.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
