### ISSUE TITLE
CameraImage ResolutionPreset.veryHigh's (1080 * 1920) width * height * 4 not equal planes[0].bytes.length.

### ISSUE THREAD

**Issue by obf1313** [flutter/flutter#71254]
Hello,
  IOS environment 
  When I using CameraImageStream, what I get in ResolutionPreset.veryHigh's planes[0].bytes.length is 8355840, but width * height * 4 is only 829440. the planes[0].bytesPerRow is  4352, what I wish is 1080 * 4, but I got 1088 * 4.
  Can anyboy tell me why?
  `Image.fromBytes(cameraImage.width, cameraImage.height, cameraImage.planes[0].bytes, format: Format.bgra)`
  out of range hanppend.
Thanx.

**Comment by darshankawar** [comment]
@obf1313 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing along with expected and actual behavior.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
