### ISSUE TITLE
Flutter startup first frame seems to be pre-empted by a Dart_NotifyIdle garbage collect

### ISSUE THREAD

**Issue by xster** [flutter/flutter#71253]
Comparing a launch trace vs last year, noticed that on the UI thread, the very first thing we do when launching a Flutter instance seems to open up with a garbage collect rather than drawing the first frame.

See screenshot for stack:

![Screen Shot 2020-11-25 at 10 23 38 PM](https://user-images.githubusercontent.com/156888/100315072-de733e00-2f6c-11eb-81a7-c9c4ca310fcc.png)

Next CPU sample:
![Screen Shot 2020-11-25 at 10 24 01 PM](https://user-images.githubusercontent.com/156888/100315110-eb902d00-2f6c-11eb-8295-39865228aac6.png)

Next sample:
![Screen Shot 2020-11-25 at 10 24 16 PM](https://user-images.githubusercontent.com/156888/100315132-f5199500-2f6c-11eb-942c-9cee95a7df22.png)

The sampling is every 1ms but it seems like the first 20ms were spent garbage collecting. @dnfield may have recent context. Could we add some special casing to not do an Engine::NotifyIdle until the first frame is drawn?

**Comment by dnfield** [comment]
It should be the animator calling notifyidle right?  Also are you sure it's from notify idle and not something else that could trigger a GC?

It would help to have the dart timeline for this trace. NotifyIdle should emit some timeline events.

**Comment by xster** [comment]
> It should be the animator calling notifyidle right?

Right. See stack from the first sample
![Screen Shot 2020-11-25 at 10 33 06 PM](https://user-images.githubusercontent.com/156888/100315885-437b6380-2f6e-11eb-85ef-e66a80edd478.png)

**Comment by dnfield** [comment]
Maybe @chinmaygarde would know better but I thought the animator would not notify idle before the first frame is drawn. Maybe what's happening is it's waiting for vsync and thinks it has time. At any rate it seems like a fine thing to change to me. 

However it'd be good to make sure this actually helps things. In particular I'd wonder if we could just prioritize the dart workers better so the ui thread had enough cpu to work uninterrupted

**Comment by kf6gpe** [comment]
May be related to #70119?

@chinmaygarde Do you know if the animator is notifying idle before first frame (@dnfield's question)?

**Comment by kf6gpe** [comment]
Correction --- this is related to #70636, not the issue I linked in the previous comment.

**Comment by gnprice** [comment]
Cool, glad to hear this was fixed.

Was there a known change that fixed this? Or did it just stop reproducing at some point?
