### ISSUE TITLE
Webview showing blank screen with some initial urls (might be redirect issue)

### ISSUE THREAD

**Issue by e-oj** [flutter/flutter#71268]
The Webview loads a blank screen when the initial url is a twitch oAuth url. I suspect it has something to do with the url redirecting to twitch's login page (If the user isn't logged in already). I'm testing on android.

## Steps to Reproduce
Create a webview and set the initial url to: https://id.twitch.tv/oauth2/authorize?client_id=fx9d4xcwzswjzwt8cfzj8lh8paphdu&redirect_uri=https://www.eswagers.com/oauth&state=twitchAuth&scope=user:read:email&response_type=token

**Expected results:** Redirect to Twitch login page. 
**Actual results:** Blank screen

Here's some code: 
```dart
  WebView authenticate({@required Function onDone}){
    String authUrl = '$baseUrl'
        '?client_id=$clientID'
        '&redirect_uri=$redirectUri'
        '&state=$state'
        '&scope=$scope'
        '&response_type=token';

    print('auth url: $authUrl');
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

    return WebView(
      initialUrl: authUrl,
      onPageStarted: (url) async {
        if (url.startsWith(redirectUri)){
          String token = _getToken(url);
          onDone(token);
        }
      },
    );
  }
```

**Comment by darshankawar** [comment]
@e-oj 
This could be due to the parameter `initialUrl` probably isn't capable to handling extra parameters and currently loads only simple / regular urls.

**Comment by e-oj** [comment]
It works for FB oath though.

**Comment by darshankawar** [comment]
@e-oj 
Check [this](https://discuss.dev.twitch.tv/t/issues-with-webview-and-oauth/24960/27) link which may be indicating that the issue could be from twitch side ?

**Comment by e-oj** [comment]
It's a different issue. The user over there is trying to embed a twitch stream+chat in an app that's already running in a web view. Opening the link on my mobile browsers works fine.

**Comment by e-oj** [comment]
I believe this is related to #25351

**Comment by e-oj** [comment]
I found the solution! Javascript is disabled by default in the webview. I simply needed to enable it in the constructor. Here's the updated code:

```dart
WebView authenticate({@required Function onDone}){
    String authUrl = '$baseUrl'
        '?client_id=$clientID'
        '&redirect_uri=$redirectUri'
        '&state=$state'
        '&scope=$scope'
        '&response_type=token';

    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

    return WebView(
      initialUrl: authUrl,
      // Enable JS
      javascriptMode: JavascriptMode.unrestricted,
      onPageStarted: (url) async {
        print(url);
        if (url.startsWith(redirectUri)){
          String token = _getToken(url);
          onDone(token);
        }
      }
    );
  }
```
Hopefully someone else will find this helpful.

**Comment by darshankawar** [comment]
@e-oj Glad to know you found the solution. Closing this as resolved.
