### ISSUE TITLE
Turkish character (ş, ç, ü, ğ, ı) is not displayed correctly.

### ISSUE THREAD

**Issue by musahinist** [flutter/flutter#71288]
Turkish character (ş, ç, ü, ğ, ı) is not displayed correctly.

**Comment by iapicca** [comment]
@musahinist 
could you please provide you `flutter doctor -v`

testing the code below on dartpad


```dart
import 'package:flutter/material.dart';

void main() => runApp(
     const MaterialApp(
        home: Material(
          child: Center(
            child: Text('ş, ç, ü, ğ, ı'),
          ),
        ),
      ),
    );

```

gives this result

![image](https://user-images.githubusercontent.com/45637986/100396091-6714db80-304c-11eb-9ddb-b1b084df6474.png)

the last one looks a bit different, but the other look kind of identical to me,
but I'm no expert, maybe depends from the fonts

**Comment by darshankawar** [comment]
@musahinist 
Please provide `flutter doctor -v` and on which platform are you seeing this issue.
Thanks.

**Comment by musahinist** [comment]
Today I discovered that the editor I used was causing the problem. Thank you for your interest.
