### ISSUE TITLE
Hot reload benchmark regressed

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7128]
The hot reload benchmark has become very spiky, which hasn't been the case before. It now routinely exceeds the 900ms baseline up to 3x.

[Dashboard](https://flutter-dashboard.appspot.com/benchmarks.html)

![hot reload perf regression](https://cloud.githubusercontent.com/assets/211513/20815301/2afcaa98-b7d2-11e6-8c32-27f7dd5fec97.png)

/cc @johnmccutchan @turnidge

**Comment by sethladd** [comment]
cc @mit-mit 

This is on a real device?

**Comment by yjbanov** [comment]
Yes, this is on Nexus 5.

**Comment by johnmccutchan** [comment]
I've noticed this too. We are currently measuring three separate stages (devfs sync, VM reload, flutter reassemble) with one number. I'm going to measure each stage independently so we can determine which stage(s) has started to regress.

**Comment by eseidelGoogle** [comment]
Sounds like @johnmccutchan is owning this?  Please feel free to unassign if not the case.

**Comment by johnmccutchan** [comment]
I have updated the benchmark to report fine grained metrics. I'm still blocked on Yegor surfacing this.

**Comment by johnmccutchan** [comment]
https://github.com/flutter/flutter/issues/7238

**Comment by johnmccutchan** [comment]
@Hixie This is the original bug tracking the perf regression.

**Comment by yjbanov** [comment]
After a recent engine roll (https://github.com/flutter/flutter/commit/1e1463216adaf96cc729a5a09761738d2309d548) the benchmark is not as spiky any more, but it's still showing worse numbers than what we saw in the past.

<img width="197" alt="screen shot 2017-01-24 at 3 12 42 pm" src="https://cloud.githubusercontent.com/assets/211513/22271114/d9a2a922-e247-11e6-80f0-ee8d888ba117.png">

**Comment by Hixie** [comment]
Is this on iOS? Maybe the old spikiness was the weirdness around not pushing frames/microtasks.

**Comment by Hixie** [comment]
The more recent regression might be the tab thing @HansMuller is looking at.

**Comment by yjbanov** [comment]
This is Android.

**Comment by johnmccutchan** [comment]
State dump:

* We are now tracking fine grained performance metrics on Android (still waiting on @yjbanov for iOS).
* Fine grained benchmarks show that the framework's `reassemble` for the Gallery app has regressed in performance and now takes ~1.5 seconds (used to be ~500 milliseconds).
* Given a single library change, we are preserving most unoptimized code and are not suffering from a compilation storm. Also, we are not being suspended for a GC.
* A 100 millisecond performance oddity was discovered in the VM [tracked here](https://github.com/dart-lang/sdk/issues/28652)
* An idea was floated by @abarth of a `Map<Type, Callback>` where the VM would detect which types have been reloaded and call the callback. I believe the motivation is that it avoid having to mark the entire widget tree as dirty. VM team is unsure of the performance / robustness of this and are hesitant to add it. @rmacnak-google for comment. 
* Marking the widget tree is taking 50% of `reassemble` time. I'd expect there is a cheap atomic way of marking the entire widget tree dirty (reassemble serial number?)
* Calling the build methods is taking the other 50% of `reassemble` time. Not sure what can be done here. @Hixie has more information.

**Comment by Hixie** [comment]
Making the widget tree dirty is far less that 50%. Gallery home page, second hot reload, no changes, on my device (rounding to the nearest 5ms, this is very rough eyeballing from the timeline graph):
50ms Reload.
10ms Unaccounted for in timeline.
10ms Something in Dart (unlabeled).
90ms Unaccounted for in timeline.
40ms Dirty widget tree.
35ms Dirty render tree.
120ms Rebuild widget tree.
40ms Relayout render tree.
10ms Repaint render tree.
15ms Waiting for vsync from engine.
20ms GPU time.

Walking the widget tree is therefore about one sixth to one seventh of the framework time. The expensive time is rebuilding everything, which we could almost entirely omit if we knew what instances needed rebuilding (right now we rebuild everything). That would also knock out most of the relayout time, and all the dirtying time.

In theory, when nothing has changed ("Reloaded 0 of 455 libraries" as here), we should be able to get this whole process down to the time it takes to determine that nothing has changed, and a round-trip to the device. When only one line has changed (a common case), we should be able to just make this incrementally more work but still not go all the way to reloading the world.

**Comment by johnmccutchan** [comment]
@Hixie Thanks for the more precise numbers, I was going off of my memory from last week.

**Comment by Hixie** [comment]
We studied the bot. Turns out the bot is measuring first reload, not second reload, and is actually going WAY faster than I see on my local machine. No idea why compilation takes longer for me than the bot sees...

**Comment by eseidelGoogle** [comment]
Is there more to do here?

**Comment by yjbanov** [comment]
`hotReloadMillisecondsToFrame` is currently ~2s. It used to be <1s. Whether there's more to do depends on whether we consider 2s reload good enough.

<img width="261" alt="screen shot 2017-02-23 at 9 40 43 am" src="https://cloud.githubusercontent.com/assets/211513/23271436/38650c18-f9ac-11e6-834c-5c9fba0a0b52.png">

**Comment by mit-mit** [comment]
Is `hotReloadMillisecondsToFrame` the first reload as Hixie mentioned above, or the 2+ reload? If the latter, I think this is a bad regression we should strive to fix.

**Comment by yjbanov** [comment]
[The test](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/hot_mode_dev_cycle__benchmark.dart) runs `flutter run --hot --benchmark` then scrapes the numbers from the `hot_benchmark.json` file. @johnmccutchan might be able to comment on what the `--benchmark` option does internally to get those numbers.

**Comment by johnmccutchan** [comment]
@Hixie A thought occurred to me that the regression may have been caused by invalidating all const static fields. By re-evaluating all const fields we end up compiling a lot more code after reloading, slowing down the reassemble.

**Comment by johnmccutchan** [comment]
Performance seems better today:

Windows bot: ~1200 milliseconds
Other bot: ~1500 milliseconds

**Comment by yjbanov** [comment]
This is back to normal. Closing.
