### ISSUE TITLE
Proposal to add new SliverGridDelegate with fixed main axis extent instead of aspectRatio

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#71282]
I think it would be a great feature to be able to create a cell with a fixed extent.

I find this considerably easy to implement and a great advantage. Right now for GridView and SliverGridView the cell size can be defined by:
 -   SliverGridDelegateWithFixedCrossAxisCount
 -  SliverGridDelegateWithFixedCrossAxisExtent

In both, the main axis extent can only be defined by a ratio relative to the crossAxisExtent. This becomes difficult to use when you expect to have a card/tile with the same extent even if the window is resized.

|  Extent(Proposal) |  AspectRatio |
|---|---|
|<img height="200" src="https://user-images.githubusercontent.com/19904063/100370307-5c375800-3006-11eb-868b-7fffeecfe79d.gif">| <img  height="200" src="https://user-images.githubusercontent.com/19904063/100370329-60fc0c00-3006-11eb-9b21-bb1b57bf427d.gif">| 

The code needed is simple and it could be added as new constructor for both current delegates or create 2 new SliverGridDelegate.

```dart
class SliverGridDelegateWithFixedCrossAxisCountAndMainAxisExtent extends SliverGridDelegate {
  /// Creates a delegate that makes grid layouts with a fixed number of tiles in
  /// the cross axis and a fixed main axis extent.
  ///
  /// All of the arguments must not be null. The `mainAxisSpacing` and
  /// `crossAxisSpacing` arguments must not be negative. The `crossAxisCount`
  /// and `mainAxisExtent` arguments must be greater than zero.
  const SliverGridDelegateWithFixedCrossAxisCountAndMainAxisExtent({
    required this.crossAxisCount,
    required this.mainAxisExtent,
    this.mainAxisSpacing = 0.0,
    this.crossAxisSpacing = 0.0,
  }) : assert(crossAxisCount != null && crossAxisCount > 0),
       assert(mainAxisSpacing != null && mainAxisSpacing >= 0),
       assert(crossAxisSpacing != null && crossAxisSpacing >= 0),
       assert(mainAxisExtent != null && mainAxisExtent > 0);

  /// The number of children in the cross axis.
  final int crossAxisCount;

  /// The number of logical pixels between each child along the main axis.
  final double mainAxisSpacing;

  /// The number of logical pixels between each child along the cross axis.
  final double crossAxisSpacing;

  /// The main-axis extent of each child.
  final double mainAxisExtent;

  bool _debugAssertIsValid() {
    assert(crossAxisCount > 0);
    assert(mainAxisSpacing >= 0.0);
    assert(crossAxisSpacing >= 0.0);
    assert(mainAxisExtent > 0.0);
    return true;
  }

  @override
  SliverGridLayout getLayout(SliverConstraints constraints) {
    assert(_debugAssertIsValid());
    final double usableCrossAxisExtent = math.max(0.0,
        constraints.crossAxisExtent - crossAxisSpacing * (crossAxisCount - 1));
    final double childCrossAxisExtent = usableCrossAxisExtent / crossAxisCount;
    final double childMainAxisExtent = mainAxisExtent;
    return SliverGridRegularTileLayout(
      crossAxisCount: crossAxisCount,
      mainAxisStride: childMainAxisExtent + mainAxisSpacing,
      crossAxisStride: childCrossAxisExtent + crossAxisSpacing,
      childMainAxisExtent: childMainAxisExtent,
      childCrossAxisExtent: childCrossAxisExtent,
      reverseCrossAxis: axisDirectionIsReversed(constraints.crossAxisDirection),
    );
  }

  @override
  bool shouldRelayout(SliverGridDelegateWithFixedCrossAxisCountAndMainAxisExtent oldDelegate) {
    return oldDelegate.crossAxisCount != crossAxisCount
        || oldDelegate.mainAxisSpacing != mainAxisSpacing
        || oldDelegate.crossAxisSpacing != crossAxisSpacing
        || oldDelegate.mainAxisExtent != mainAxisExtent;
  }
}
```

**Comment by darshankawar** [comment]
@jamesblasco 
Can you provide platform on which you would like this proposal, along with your `flutter doctor -v.
Thanks.

**Comment by jamesblasco** [comment]
It would be for all platforms as it not depends on any. Just a new SliverGridDelegate or modify the current ones.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.230, on macOS 11.0.1 20B29 darwin-x64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ! CocoaPods 1.8.4 out of date (1.9.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

**Comment by chinmoy12c** [comment]
Working on this issue. :+1:

**Comment by Captcha123** [comment]
Thanks for replying

**Comment by chinmoy12c** [comment]
PR ready for review :).
