### ISSUE TITLE
Flutter - Streambuilder + Firestore returning null snapshot after using background location plugin

### ISSUE THREAD

**Issue by hordeariibarley** [flutter/flutter#71294]
## Steps to Reproduce

1. StreamBuilder working correctly for all collections from Firestore on the app
2. Use carp_background_location plugin at one specific screen (https://pub.dev/packages/carp_background_location) like on the example/lib/main.dart 
3. All streams of the app return null on snapshot.data without error (basically it stops streaming)
4. Close and open the app on emulator again and it backs to normal (if I run background location -> step 3.)

I suspect it is something related to AppLifecycleState/WidgetsBindingObserver, but I couldn't solve it without error log.

**Expected results:**  Continue streaming data from Firestore with Streambuilder after using plugin

**Actual results:** Get Snapshot.data null from Streambuilder without error log

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)
• No issues found!
```

</details>

Thanks!

**Comment by darshankawar** [comment]
@hordeariibarley 
`carp_background_location` is 3rd party plugin. Please consider opening this issue in plugin owner's repo : https://github.com/cph-cachet/flutter-plugins/issues.

Closing this as it doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen it.
Thanks.
