### ISSUE TITLE
[video_player]  Edited videos are distorted when played on iOS

### ISSUE THREAD

**Issue by brxxxx** [flutter/flutter#71299]
When I run the sample video_player plugin app with a particular mp4 file, the playback is incorrect. The Video doesn't appear to fit on the screen properly. This only effects iOS, everything is perfect on Android. The offending mp4 file has rotation metadata in the file and I suspect that the native iOS code relating to the video player is not handling the rotation metadata correctly.

## Steps to Reproduce
Run the video_player sample project and replace the mp4 url with the following url: https://squiredev.com/golf.mp4

**Expected results:**
I expected the video to play normally like it would any other mp4 file but the video is not fitting onto the screen correctly

**Actual results:**
The video plays however it is not fitting onto the screen properly. I noticed that the FFMPEG output for the file has a rotation value in the meta data, maybe this is being ignored?

**Here is a screenshot of how it looks on iOS**

![Image-1](https://user-images.githubusercontent.com/66548748/100412677-e8e62280-30a7-11eb-9cf3-2708aac07e05.jpg)

If I re-encode the file using FFMPEG then the video plays perfectly as expected. Here is the command I use to re-encode the file:

`ffmpeg -i golf.mp4 golf_reencoded.mp4`

**Here is a screenshot of how the re-encoded file looks:**

![Image-2](https://user-images.githubusercontent.com/66548748/100413403-d4a32500-30a9-11eb-9873-f533a26b5d46.jpg)

**FFMPEG outputs:**

Here is the FFMPEG output of the original mp4 file:

```
$ ffmpeg -i golf.mp4          
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'golf.mp4':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2020-11-26T07:39:11.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 12.631108
    com.apple.quicktime.location.ISO6709: +51.9998+000.9766+046.756/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone XR
    com.apple.quicktime.software: 14.1
    com.apple.quicktime.creationdate: 2020-11-18T10:46:15+0000
  Duration: 00:00:03.80, start: 0.000000, bitrate: 3307 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 175 kb/s (default)
    Metadata:
      creation_time   : 2020-11-26T07:39:11.000000Z
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 3120 kb/s, 30.24 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2020-11-26T07:39:11.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
```

Here is the FFMPEG output of the re-encoded file, the re-encoded file plays perfectly in the video_player sample app. It may be worth noting that during the re-encoding process, FFMPEG **drops the meta/rotation data** and **resizes the video from 1280x720 to 720x1280** .  This leads me to think this could be a problem in the iOS native Video Player, relating to the handling of the meta/rotation data. If you would like to test the re-encoded file file yourself then it can be found at the following url: https://squiredev.com/golf_reencoded.mp4

```
$ ffmpeg -i golf_reencoded.mp4 
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'golf_reencoded.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:03.84, start: 0.000000, bitrate: 2105 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x1280, 1967 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio

```

$ flutter doctor -v
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/brx/software/flutter
    • Framework revision 022b333a08 (8 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/brx/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/brx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/brx/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

**Comment by darshankawar** [comment]
Issue replicable on latest stable. Verified on iphone 6s (OS 14).

![IMG-0492](https://user-images.githubusercontent.com/67046386/100425855-f60a0e00-30b5-11eb-89fb-0bca2bb0a38a.PNG)

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

 
[✓] Connected device (1 available)            
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0

• No issues found!

```

</details>

**Comment by blaneyneil** [comment]
This happens with any video that is edited, whether it's cropped, truncated, etc.

**Comment by brxxxx** [comment]
> This happens with any video that is edited, whether it's cropped, truncated, etc.

What tests have you done to confirm this? How does the player know that the video has been cropped or truncated? What specifically about such files could cause the playback issues?

To be honest I am still leaning towards this being a metadata problem because when I remove the metadata by re-encoding the file, the problem disappears. If you have any further information please provide it, thanks in advance.

**Comment by blaneyneil** [comment]
not disagreeing that it's the metadata, just wanted to note that it's not specific to rotation.  simply cutting a :30 second video down to :20 will produce the same effect in VideoPlayerController.file()

**Comment by brxxxx** [comment]
> not disagreeing that it's the metadata, just wanted to note that it's not specific to rotation. simply cutting a :30 second video down to :20 will produce the same effect in VideoPlayerController.file()

Thanks for the extra information. Can you please post the ffmpeg output of the file if it isn't too much trouble?

``` ffmpeg -i video.mp4 ```

**Comment by TahaTesser** [comment]
Hey everyone, 
I can reproduce with any edited video on iOS (reproducible when you edit a video in the iOS editor) 
1. Record a video and edit it using the  iOS video editor
2. Load ti an asset  and reproduce  using the official [example](https://pub.dev/packages/video_player/example)

**Comment by lennyd7** [comment]
Some additional insights from my testing: 
1. If you edit a video using the iOS video editor and save it as a new file (instead of replacing the original) you can play the new file without any trouble (likely because it is saved as a new original without additional metadata). 
2. Minor changes as mute the video leads again to trouble of displaying (again metadata on the video). 
3. Playing a received video (e.g. WhatsApp) again causes the same trouble

**Comment by BrutalCoding** [comment]
Is there any progress on this issue? I just encountered the same thing

**Comment by fauzipadlaw** [comment]
Is there any progress on this issue?

**Comment by juanmartin8a** [comment]
same issue on 2.1.6 any progress/solution?

**Comment by juanmartin8a** [comment]
The following might be a solution for this problem. I was trying better_player package and the problem didn't seem to be happening there so I looked at the native IOS code and based on that I changed the following block of code in ios/Classes/FLTVideoPlayerPlugin.m from video_player newest version 2.1.10 which solved the problem for me

original code:
`- (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
  CGAffineTransform transform = videoTrack.preferredTransform;
  // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
  // At least 2 user videos show a black screen when in portrait mode if we directly use the
  // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
  // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
  if (transform.tx == 0 && transform.ty == 0) {
    NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
    NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
          videoTrack.naturalSize.width, videoTrack.naturalSize.height);
    if (rotationDegrees == 90) {
      NSLog(@"Setting transform tx");
      transform.tx = videoTrack.naturalSize.height;
      transform.ty = 0;
    } else if (rotationDegrees == 270) {
      NSLog(@"Setting transform ty");
      transform.tx = 0;
      transform.ty = videoTrack.naturalSize.width;
    }
  }
  return transform;
}`

new code 
`- (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
  CGAffineTransform transform = videoTrack.preferredTransform;
  // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
  // At least 2 user videos show a black screen when in portrait mode if we directly use the
  // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
  // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
  NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
  NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
        videoTrack.naturalSize.width, videoTrack.naturalSize.height);
  if (rotationDegrees == 90) {
    NSLog(@"Setting transform tx");
    transform.tx = videoTrack.naturalSize.height;
    transform.ty = 0;
  } else if (rotationDegrees == 180) {
    transform.tx = videoTrack.naturalSize.width;
    transform.ty = videoTrack.naturalSize.height;
  } else if (rotationDegrees == 270) {
    NSLog(@"Setting transform ty");
    transform.tx = 0;
    transform.ty = videoTrack.naturalSize.width;
  }
  return transform;
}`

**Comment by Slaine066** [comment]
Do you guys have some updates? This is a pretty annoying bug

**Comment by LeGoffMael** [comment]
I can still reproduce this issue with the latest versions of image_picker: 0.8.4+4 and video_player: 2.2.7.

**Comment by LeGoffMael** [comment]
> The following might be a solution for this problem. I was trying better_player package and the problem didn't seem to be happening there so I looked at the native IOS code and based on that I changed the following block of code in ios/Classes/FLTVideoPlayerPlugin.m from video_player newest version 2.1.10 which solved the problem for me
> 
> original code:
> 
> ```
> - (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
>   CGAffineTransform transform = videoTrack.preferredTransform;
>   // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
>   // At least 2 user videos show a black screen when in portrait mode if we directly use the
>   // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
>   // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
>   if (transform.tx == 0 && transform.ty == 0) {
>     NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
>     NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
>           videoTrack.naturalSize.width, videoTrack.naturalSize.height);
>     if (rotationDegrees == 90) {
>       NSLog(@"Setting transform tx");
>       transform.tx = videoTrack.naturalSize.height;
>       transform.ty = 0;
>     } else if (rotationDegrees == 270) {
>       NSLog(@"Setting transform ty");
>       transform.tx = 0;
>       transform.ty = videoTrack.naturalSize.width;
>     }
>   }
>   return transform;
> }
> ```
> 
> new code
> 
> ```
> - (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
>   CGAffineTransform transform = videoTrack.preferredTransform;
>   // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
>   // At least 2 user videos show a black screen when in portrait mode if we directly use the
>   // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
>   // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
>   NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
>   NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
>         videoTrack.naturalSize.width, videoTrack.naturalSize.height);
>   if (rotationDegrees == 90) {
>     NSLog(@"Setting transform tx");
>     transform.tx = videoTrack.naturalSize.height;
>     transform.ty = 0;
>   } else if (rotationDegrees == 180) {
>     transform.tx = videoTrack.naturalSize.width;
>     transform.ty = videoTrack.naturalSize.height;
>   } else if (rotationDegrees == 270) {
>     NSLog(@"Setting transform ty");
>     transform.tx = 0;
>     transform.ty = videoTrack.naturalSize.width;
>   }
>   return transform;
> }
> ```

@juanmartin8a solution seems to fix the problem on all my videos!
could you do a pull request with this ? it is a very annoying bug

**Comment by AlexV525** [comment]
/cc @jmagman @stuartmorgan 

https://github.com/flutter/flutter/issues/71299#issuecomment-878506319 could be a valid solution, but I have no idea what to test and how to test, otherwise, I can make a PR for it.

**Comment by jmagman** [comment]
@AlexV525 A PR would be great! Unfortunately the existing transform code isn't tested.  There are limited existing unit and integration `XCTest` native tests in the example project, you can take a look at those.

**Comment by zachchou** [comment]
This bug may only appear on devices below iOS15, I looked for a few iOS15 devices did not appear, in an iOS14 device appeared on top

**Comment by zachchou** [comment]
This bug may only appear on devices below iOS15, I looked for a few iOS15 devices did not appear, in an iOS14 device appeared on top,  [#71299(comment)](https://github.com/flutter/flutter/issues/71299#issuecomment-878506319) solution

**Comment by klartraum-medien** [comment]
> This bug may only appear on devices below iOS15, I looked for a few iOS15 devices did not appear, in an iOS14 device appeared on top, [#71299(comment)](https://github.com/flutter/flutter/issues/71299#issuecomment-878506319) solution

I cannot confirm this. The bug appears also on iOS 15.2 for me. The [suggestion above](https://github.com/flutter/flutter/issues/71299#issuecomment-878506319) does fix the issue for me completely though as well.

**Comment by AlexV525** [comment]
I filed a PR for this, but any help with tests would be great. ❤️
