### ISSUE TITLE
Does FFI support iOS static library？

### ISSUE THREAD

**Issue by JackPanda8** [flutter/flutter#71295]
as the official doc :
Symbols from a statically linked library can be loaded using DynamicLibrary.executable or DynamicLibrary.process.

but i got the error: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, pause_all_task): symbol not found)，

-------------here is my code--------------------------------
```
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:ffi/ffi.dart';

// C function signatures
typedef pause_all_task_t = ffi.Void Function();
typedef get_cache_instance = ffi.Pointer<ffi.Void> Function();

// Dart function signatures
typedef PauseALLTask = void Function();
typedef GetCacheInstance = ffi.Pointer<ffi.Void> Function();

// Getting a library that holds needed symbols
ffi.DynamicLibrary _lib = Platform.isAndroid
		? ffi.DynamicLibrary.open('libflash-downloader-lib.so')
		: ffi.DynamicLibrary.process();

// Looking for the functions
final PauseALLTask pauseAllTaskF = _lib
		.lookup<ffi.NativeFunction<pause_all_task_t>>('pause_all_task')
		.asFunction();
final GetCacheInstance getCacheInstanceF = _lib
		.lookup<ffi.NativeFunction<get_cache_instance>>('get_cache_instance')
		.asFunction();
```

```
#include "dart_ffi_adapter.h"
//#include "YKCacheCenter.h"
extern "C" {
attribute((visibility("default"))) attribute((used))
void* get_cache_instance(void) {
printf("my_download:调用GetCacheInstance构造单例");
void* p;
return p;
}
attribute((visibility("default"))) attribute((used))
void pause_all_task(void) {
// yk_cache::IYKCache *cache = yk_cache::GetCacheInstance();
// cache->pauseAllTask();
printf("my_download:调用pause_all_task暂停所有下载中的任务");
}
attribute((visibility("default"))) attribute((used))
void ff_pause_all_task(){
printf("my_download:call ff_pause_all_task");
}
}
```

**Comment by darshankawar** [comment]
@JackPanda8 
Check out this document for reference and see if it answers your question.

`You add the sources to the ios folder, because CocoaPods doesn’t allow including sources above the podspec file, but Gradle allows you to point to the ios folder. It’s not required to use the same sources for both iOS and Android; you may, of course, add Android-specific sources to the android folder and modify CMakeLists.txt appropriately.`

**Comment by dcharkes** [comment]
See discussion on symbols not being found on https://github.com/flutter/flutter/issues/62666#issuecomment-668377567.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by zjrwdl** [comment]
i meet the same error.
add  use_frameworks!  in pod file  can solve this problem.
but i do not know the reason.
