### ISSUE TITLE
The Flutter log level problem

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#71298]
When I was developing my Flutter application, the incomprehensible logging was a big problem because there was no quick way to filter my logs based on the severity of the problem.For example, the Android log level Verbose Debug Info Warn Error.

**Comment by darshankawar** [comment]
@gionchat 
Please provide `flutter doctor -v` and practical code sample along with logs that you think are an issue.

**Comment by hamedtayeban22** [comment]
#17298
