### ISSUE TITLE
[local_auth] didn't get PlatformException

### ISSUE THREAD

**Issue by callmejm** [flutter/flutter#71306]
import 'package:flutter/services.dart';
	import 'package:local_auth/error_codes.dart' as auth_error;

	try {
	  bool didAuthenticate = await local_auth.authenticateWithBiometrics(
               useErrorDialogs:false,
	      localizedReason: 'Please authenticate to show account balance');
	} on PlatformException catch (e) {
	  if (e.code == auth_error.notEnrolled) {
	    // Handle this exception here.
	  }
	}

I using local_auth for biometric validation, if user didn't set up fingerprint, system will throw PlatformException error as mention in the doc, however the error is throw to debug console instead of the try catch method. This is kind a weird

**Comment by darshankawar** [comment]
@callmejm 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample along with expected and actual behavior.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
