### ISSUE TITLE
[wiki] Typo on wiki page "Chat"

### ISSUE THREAD

**Issue by gsouf** [flutter/flutter#71309]
Hi,

At https://github.com/flutter/flutter/wiki/Chat In the list of discord chanels there is a typo at `#hackes-devexp`. Expecting `hackers-devexp`

![image](https://user-images.githubusercontent.com/3215399/100435995-08c51880-309f-11eb-9cc6-4c470d8b1cf8.png)

**Comment by pedromassangocode** [comment]
Hi @gsouf.
Thanks for filling this issue, I just fixed it!
