### ISSUE TITLE
Build failed after flutter upgrade

### ISSUE THREAD

**Issue by jennerstrom** [flutter/flutter#71307]
## Steps to Reproduce

I ran flutter upgrade --force to be able to update my version and now I can't build the app on my simulator

## Logs

**Error message**

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/jensauguststrom/Desktop/Aspirantgruppen/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.22/ios/Classes/FLTPathProviderPlugin.m:5:
    /Users/jensauguststrom/Desktop/Aspirantgruppen/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.22/ios/Classes/FLTPathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone Xs.

**Output of flutter run --verbose**

[ +569 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone Xs.
[   +6 ms] "flutter run" took 89.278ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1119:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:974:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:264:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

```
```

**Output of Flutter doctor -v**

[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Mac OS X 10.15.7 19H2 darwin-x64, locale da-DK)
    • Flutter version 1.24.0-8.0.pre.374 at /Users/JAS/Desktop/anB/flutter
    • Framework revision 183f0e797a (14 hours ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/JAS/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone Xs (mobile) • 5201B32F-92B3-4352-B35B-6DFD734FAF43 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 86.0.4240.198

```
```

**Comment by darshankawar** [comment]
@jennerstrom 
I tried `flutter upgrade --force` in master branch and then compiled a sample app which ran properly without any issues.

```
Running "flutter pub get" in newtest...
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           33.6s
Debug service listening on ws://127.0.0.1:59391/whfIVTZi4Rc=/ws
Syncing files to device iPhone SE (2nd generation)...

```

Can you provide a minimal complete reproducible code sample along with `pubspec.yaml` ? Also what command are you trying to run to compile on ios ?

**Comment by Abhishek01039** [comment]
Hello @jennerstrom 
Remove ios/Flutter/Flutter.framework from your project

Run pod install in ios directory. ```Flutter. framework``` should be generated, including Headers/Flutter.h file

Run build

try these steps, please
Thanks

**Comment by jennerstrom** [comment]
@Abhishek01039 I don't have a flutter.framework file in ios/Flutter. I ran pod install but I still don't have it and I am getting the same build fail error. Do you know if I can get the flutter.framework file another way?

@darshankawar I wouldn't know what part of my code to include as everything was working before flutter upgrade

**Comment by Abhishek01039** [comment]
Hello @jennerstrom 
whenever you are running your app in Mac OS then this folder is created 
like this 
![image](https://user-images.githubusercontent.com/56479665/100533470-ce888200-322a-11eb-9a72-5e67be60108d.png)
Thanks

**Comment by Lafannn** [comment]
I have same issue. @Abhishek01039 Your solution didn't work for me.

**Comment by Abhishek01039** [comment]
Hello @Lafannn and @jennerstrom 
Please refer to this https://stackoverflow.com/questions/50671286/flutter-h-not-found-error/60847368 and https://stackoverflow.com/questions/55985841/flutter-flutter-flutter-h-not-found-when-using-the-google-sign-in-library and https://github.com/flutter/flutter/issues/53029

Thanks.

**Comment by iFrez** [comment]
@Abhishek01039 No one of this helps. Already tried all of them.

**Comment by Abhishek01039** [comment]
@iFrez What about Android, is working fine?

**Comment by Lafannn** [comment]
I found source of my problem. MacOS Big Sure not allowed to launch iproxy that required to start debugging of flutter app. I allowed launch in system Security & Privacy settings

**Comment by Abhishek01039** [comment]
@Lafannn 
Do you have Mac with an M1 chip?

**Comment by Lafannn** [comment]
@Abhishek01039  Nope. iMac 2019

**Comment by Abhishek01039** [comment]
@iFrez and @jennerstrom 
you both are in Big Sur?

**Comment by Lafannn** [comment]
1. Open system preferences -> Security & Privacy -> General
2. Launch debugging
3. Wait when system request access to launch `iproxy`
4. Tap allow always
5. Stop debugging and relaunch app

**Comment by iFrez** [comment]
@Abhishek01039 Yes I am in Big Sur.

**Comment by Abhishek01039** [comment]
Thanks @Lafannn

**Comment by darshankawar** [comment]
@jennerstrom 
Can you provide full logs of the command you are running to build ?

**Comment by jennerstrom** [comment]
I tried several solutions from similar issues and questions on StackOverflow to fix my ios folder (I'm new to flutter and programming in general and if you are too DO NOT do this it makes it WAY harder to find the issue and solve it, I just ended up with a whole different set of build errors). 

What finally did the trick for me because I had tried so many different solutions was deleting the ios folder and running `flutter create` to recreate it and then adding firebase to the new ios folder. Thanks for all the help.

**Comment by rajeshtaneja** [comment]
I am getting same issue with no Pod file. Default flutter app when I build it:
```
Command PhaseScriptExecution failed with a nonzero exit code
           
           
[  +66 ms] "flutter ios" took 25,011ms.
[   +8 ms] Encountered error while building for device.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:274:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by cpc84** [comment]
i have a same problem. My Mac has an M1 Chip... Can anybody Help me? Thx

**Comment by jay2jp** [comment]
I also have the same issue 
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/17814331/127384300-f33b2697-c130-45fa-86d1-aeb5477706a7.png">

**Comment by cpc84** [comment]
i have fixed the problem.

i have installed ruby, cocoapods and new developer certificates.
