### ISSUE TITLE
Failed assertion: line 855 pos 12: '!debugBuildingDirtyElements': is not true.

### ISSUE THREAD

**Issue by pengboboer** [flutter/flutter#71300]
No more information was provided, and I had no idea what the mistake was

The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 855 pos 12: '!debugBuildingDirtyElements': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:855:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)

**Comment by darshankawar** [comment]
@pengboboer 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that can help to replicate this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by kashish958** [comment]
I got this error when i added loading progress indicator in my main .dart file while fetching the data from api .

here is the code please any one help 



import 'dart:convert';
import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'dart:async';
import 'model.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  // This widget is the root of your application.

State<StatefulWidget>createState(){
  return Myappstate();
}
}
class Myappstate extends State<MyApp>{

final String url = "https://raw.githubusercontent.com/nitishk72/flutter_json_list/master/json_example.json";
bool _loading;

List <model> r;  //model type ki isisliye bnayi kyunki har baar model instance banega for each and every entry in map //
  void initState(){
    super.initState();
   getdata();
    _loading = false;
  }

Future <List<String>> getdata() async{

  var response = await http.get(Uri.parse(url),
      headers: {"Accept": "application/json"});     //getting only json data from url //

print(response.body);

List<dynamic> data =  json.decode(response.body);
// decoding the raw json data into the list//

   r = data.map((data) =>model.fromJson(data)).toList();
//constructing the new model instance from a map structure.

setState(() {
  _loading = !_loading;
});

}
  @override
  Widget build(BuildContext context) {

    return MaterialApp(

      home: Scaffold(
  appBar:customappbar(),
        body:
            Column(
              children:[
       _loading ? LinearProgressIndicator() : Text(
        "Please wait",
        style: TextStyle(fontSize: 25)),

        ListView.builder(

            itemCount: r == null ? 0 : r.length,
            itemBuilder: (BuildContextcontext,index){

              return(
Container(

  padding: EdgeInsets.all(10.0),
  child:

      Card(elevation: 8.0,
       child: Column(
            children:[
              Text("Name :  ${r[index].name}"),
              Text("Email :  ${r[index].email}"),
              Text("ID :  ${r[index].id}"),
              Text("Address :  ${r[index].address}")


     ]
      )

    )

)


              );
        }

        )


    ]  ),
      )
    );

}


}
customappbar(){
  return PreferredSize(
    preferredSize: Size.fromHeight(40),
    child: Container(
        height: 70,
        decoration: BoxDecoration(
            gradient: LinearGradient(
                begin: Alignment.centerLeft,
                end: Alignment.centerRight,
                colors: [Colors.cyanAccent, Colors.redAccent]),),
        child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: <Widget>[
              IconButton(icon: Icon(Icons.home), onPressed: () {}),
              Text(
                "Json Testing",
                style: TextStyle(fontSize: 27),
              ),
              IconButton(icon: Icon(Icons.menu), onPressed: () {}),
            ])),
  );
}
