### ISSUE TITLE
Flutter update element create by ui.platformViewRegistry.registerViewFactory class

### ISSUE THREAD

**Issue by khushi-shettigar** [flutter/flutter#71311]
I am working with Google Map for flutter Website. As most tutorial said that, the map is displayed through ui.platformViewRegistry.registerViewFactory

below is the code example. As you see, i create the widget with the variable and tried to give the _lat and _lng from outside. But after i tried to give the value, the ui.platformViewRegistry.registerViewFactory is not triggered.

Anyone have idea about this?

` Widget getMap(double _lat, double _lng) {
  String htmlId = "map-canvas";

  ui.platformViewRegistry.registerViewFactory(htmlId, (int viewId) {
    final mapOptions = new MapOptions()
      ..zoom = 8
      ..center = new LatLng(_lat, _lng)
      ..mapTypeControl = false;

    final elem = DivElement()
      ..id = htmlId
      ..style.width = "100%"
      ..style.height = "100%"
      ..style.border = "none";

    final map = new GMap(elem, mapOptions);

    Marker(MarkerOptions()
      ..position = LatLng(_lat, _lng)
      ..map = map
      ..title = 'Green Energy');

    return elem;
  });
  return HtmlElementView(
    viewType: htmlId,
  );
} `

**Comment by pedromassangocode** [comment]
Hi @khushi-shettigar 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample and the steps to reproduce the issue?
Thank you

**Comment by khushi-shettigar** [comment]
`[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/insight/Documents/flutter
    • Framework revision 022b333a08 (9 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/insight/Documents/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/insight/Documents/Android/sdk
    • ANDROID_SDK_ROOT = /Users/insight/Documents/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.67
    ! Device 42007451e0506300 is offline.

• No issues found!
`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
