### ISSUE TITLE
No examples for GlowingOverscrollIndicator

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#7131]
There is a widget `OverscrollIndicator` ( https://docs.flutter.io/flutter/material/OverscrollIndicator-class.html ) but there is no usages in `examples` folder and documentation of it does not explain where to put it and how to use (for example, with `ScrollableGrid`

Would be nice to have some even very small example

**Comment by sethladd** [comment]
Thanks for the request. Curious, what question are you looking for an answer?

**Comment by Hixie** [comment]
This widget is documented now, but still doesn't have examples:
https://docs.flutter.io/flutter/widgets/GlowingOverscrollIndicator-class.html

**Comment by Mericusta** [comment]
packages\flutter\test\widgets\overscroll_indicator_test.dart

might help~

**Comment by workerbee22** [comment]
Also noticed that this test: https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/overscroll_indicator_test.dart

Does not test **showLeading:** or **showTrailing:** properties.

**Comment by markusaksli-nc** [comment]
Closing as this is clearly fixed in the [api.flutter.dev page for this widget](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html).
