### ISSUE TITLE
[webview_flutter] Webview oauth iOS intermittent redirect problem

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#71320]
flutter 1.22.3
webview_flutter 1.0.7

On Android the problem does not happen.

**iOS problem**: after outh authentication with another app, when returning to my app and trying to navigate to the callback url, webview receives the url but does not navigate with `NavigationDecision.navigate`.
If you insist several times, one hour it works.

The callback goes to an nginx + angular page

I need some urgent solution or alternative, as my app will go into production.

the only thing that appears in the xcode log:
2020-11-20 14:28:53.814070-0300 Runner[699:278292] [ProcessSuspension] 0x28223fa40 - WKProcessAssertionBackgroundTaskManager: Ignored request to start a new background task because the application is already in the background

**Comment by darshankawar** [comment]
@mdmota 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by mdmota** [comment]
```
return WebView(
        initialUrl: url
        javascriptMode: JavascriptMode.unrestricted,
        navigationDelegate: (request) =>_navigationDelegate(request)
    );
```
```
FutureOr<NavigationDecision> _navigationDelegate(NavigationRequest request) async{
    String url = request.url;

    .....

    return NavigationDecision.navigate;
  }
```
callback return url like: https://xxxx.aaa.bb?code=xxx&code_challenge=yyy

**Comment by mdmota** [comment]
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [versÃ£o 10.0.19041.630], locale pt-BR)
    • Flutter version 1.22.3 at c:\flutter
    • Framework revision 8874f21e79 (5 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mateus\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@mdmota 
We would need a complete minimal reproducible code sample that we can simply copy paste and run in IDE. Also please provide what should be the expected behavior.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
