### ISSUE TITLE
gallery colors demo scrolling tabs

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#7133]
Hello,

In the Colors demo of the gallery app, when you scroll only the tabs, we jump from the first color tab ("red") to the last color tab ("blue grey)" directly,

I think it is the same problem than #6618 and the problem of scrolling you can observe in the licences panel of gallery app.

I test on Android 6.0.1 on nexus 5.

I know that @Hixie is refactoring scrolling. I'm looking forward for this feature!! Do you have an idea when it will be available?
Thank you

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/5288 is the great refactor @Hixie is working on at the moment.  But this also may just be a bug.  @HansMuller owns much of the gallery and widgets.

**Comment by HansMuller** [comment]
I wasn't aware of this problem. I'm out this morning; will take a look this afternoon.

**Comment by lequem** [comment]
Hello, 
@HansMuller , did you observe the bug?
Let me know! 
Vincent

**Comment by HansMuller** [comment]
Sorry, I neglected to update the issue :-(.

I have observed the bug and I have a fix which I'll upload shortly.
