### ISSUE TITLE
[Proposal][Flutter web] : Add a flag to `flutter build web` to update version to prevent cache

### ISSUE THREAD

**Issue by iqfareez** [flutter/flutter#71333]
## Use case
To force browser to reload / fetch the updated web app version instead of using the cached file.

## Proposal

We can update the version in `main` file. Something similar to this [question](https://stackoverflow.com/questions/61286756/stop-saving-in-cache-memory-flutter-web-firebase-hosting). 

Make `flutter build web` command automatically increase the version number.

<details><summary>My flutter version</summary>
<p>

```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (6 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```
</p>
</details>

**Comment by iapicca** [comment]
@iqfareez 

> Make `flutter build web` command automatically increase the version number.

I can see this being an option, maybe something like 
```console
flutter build web --bump-version=true
```
but **enforcing** this by default might not be desirable for everyone

**Comment by darshankawar** [comment]
@iqfareez 
As suggested above, `forcing` to increase version number is not a feasible proposal, but we may propose to add a parameter / flag to the command that'll do the job. Retitling this issue for properly describe the proposal.

**Comment by jonahwilliams** [comment]
If you do not want to use the server worker caching you can provide `--pwa-strategy=none`. Otherwise the app will update after the new version has been downloaded and the page revisited.

**Comment by tazik561** [comment]
> ```
> --bump-version=true
> ```
When I run
` fvm flutter build web --bump-version=true
`I got :

`Could not find an option named "bump-version".
`

**Comment by iqfareez** [comment]
@tazik561 He just proposed a concept. Not an actual implementation.

**Comment by tazik561** [comment]
I build a flutter web app and deployed it via nginx hosting on my local. 

Now I deployed a newer version of my pwa but I still get the old website shown form the first deploy. I added **version number** in `build/web/index.html` 

`      <script src="main.dart.js?version=1" type="application/javascript"></script>
`
and then I restarted nginx, after lunching my project on mobile I changed **version=1** to **version=2** and again I restarted nginx. But When I launch my project on mobile again , I see old website again ?

Thanks a lot for any help!

This is all index.html inside build/web folder:

```
    <!DOCTYPE html>
    <html>
    <head>
      <!--
        If you are serving your web app in a path other than the root, change the
        href value below to reflect the base path you are serving from.
    
        The path provided below has to start and end with a slash "/" in order for
        it to work correctly.
    
        Fore more details:
        * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
      -->
      <base href="/">
    
      <meta charset="UTF-8">
      <meta content="IE=Edge" http-equiv="X-UA-Compatible">
      <meta name="description" content="test">
    
      <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
      <meta http-equiv="Pragma" content="no-cache" />
      <meta http-equiv="Expires" content="0" />
    
      <!-- iOS meta tags & icons -->
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-status-bar-style" content="black">
      <meta name="apple-mobile-web-app-title" content="tttt">
      <link rel="apple-touch-icon" type="image/png" href="./icons/Icon-512.png">
    
      <!-- Favicon -->
      <link rel="icon" type="image/png" href="./icons/Icon-512.png"/>
    
      <title>test title</title>
      <link rel="manifest" href="./manifest.json">
    </head>
    <body>
      <!-- This script installs service_worker.js to provide PWA functionality to
           application. For more information, see:
           https://developers.google.com/web/fundamentals/primers/service-workers -->
      <script>
        if ('serviceWorker' in navigator) {
          window.addEventListener('flutter-first-frame', function () {
            navigator.serviceWorker.register('flutter_service_worker.js?v=3725191275');
          });
        }
      </script>
      <script src="main.dart.js?version=2" type="application/javascript"></script>
    </body>
    </html>
```

**Comment by technolion** [comment]
If your `index.html` gets cached on the client browser, it not enough to change the URL parameter of `main.dart.js`.
For this approach to work, you'd have to instruct your web server to tell browsers _never_ to cache `index.html`.

**Comment by tazik561** [comment]
> If your `index.html` gets cached on the client browser, it not enough to change the URL parameter of `main.dart.js`.
> For this approach to work, you'd have to instruct your web server to tell browsers _never_ to cache `index.html`.

I added 
```
      <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
      <meta http-equiv="Pragma" content="no-cache" />
      <meta http-equiv="Expires" content="0" />
```
inside ``index.html` . This is not enough to prevent that user's browser caching ?

**Comment by technolion** [comment]
> inside ``index.html` . This is not enough to prevent that user's browser caching ?

You can check, which backend serves this file by taking a look a chrome's network inspector. I also witnessed that the Service worker sometimes serves this file, without making a call to the web server. I improved the situation by using `--pwa-strategy none` when building the flutter web application.
