### ISSUE TITLE
Failed assertion: line 4731 pos 12: '_state._element == null': is not true.

### ISSUE THREAD

**Issue by subhashDev11** [flutter/flutter#71336]
```bash
The following assertion was thrown building DefaultTextStyle(debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4731 pos 12: '_state._element == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///E:/flutter%20project%20package/app/lib/main.dart:54:12
When the exception was thrown, this was the stack: 
#2      new StatefulElement (package:flutter/src/widgets/framework.dart:4731:12)
#3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:904:38)
...     Normal element mounting (230 frames)
#233    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
```

**Comment by iapicca** [comment]
@subhashDev11 
can you provide your `flutter doctor -v` your full `flutter run -v`
and most importantly a minimal reproducible code sample

**Comment by subhashDev11** [comment]
Thanks for response
This is my flutter doctor -v-
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.22.2 at C:\flutter
    • Framework revision 84f3d28555 (6 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pc\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • vivo 1906 (mobile) • c9fc9741 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by subhashDev11** [comment]
Either pwsh.exe or PowerShell.exe must be in your PATH.
[ +157 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 84f3d28555368a70270e9ac8390a9441df95e752
[   +1 ms] executing: [C:\flutter/] git tag --points-at HEAD
[  +36 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.2
[  +13 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +79 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +72 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +53 ms] List of devices attached
           c9fc9741               device product:1906 model:vivo_1906 device:1906 transport_id:1
[   +8 ms] C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell getprop
[  +90 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +203 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +8 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +4 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +13 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +7 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +4 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[ +198 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +2 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +3 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +9 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +3 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +3 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[  +43 ms] Generating E:\flutter project subhash\LMS\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +60 ms] ro.hardware = qcom
[  +56 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +5 ms] Launching lib\main.dart on vivo 1906 in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\pc\AppData\Local\Temp\flutter_tools.83a37c7c\flutter_tool.91f3f9eb\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +20 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree E:\flutter project subhash\LMS\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[  +14 ms] Exit code 0 from: C:\Users\pc\AppData\Local\Android\sdk\build-tools\30.0.2\aapt dump xmltree E:\flutter project
subhash\LMS\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.dki.LMS" (Raw: "com.dki.LMS")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="LMS" (Raw: "LMS")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.dki.LMS.MainActivity" (Raw: "com.dki.LMS.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=46)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040001
                   E: intent-filter (line=50)
                     E: action (line=51)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=53)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=60)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +9 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell -x logcat -v time -t 1
[ +220 ms] Exit code 0 from: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           11-30 11:33:47.582 I/inkedin.androi(24488): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 51.113ms
[   +3 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell -x logcat -v time -t 1
[ +174 ms] Exit code 0 from: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           11-30 11:33:47.582 I/inkedin.androi(24488): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 51.113ms
[  +41 ms] <- compile package:LMS/main.dart
[  +46 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +74 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +22 ms] Building APK
[  +34 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from E:\flutter project subhash\LMS\android\gradlew.bat.
[   +1 ms] E:\flutter project subhash\LMS\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +11 ms] executing: [E:\flutter project subhash\LMS\android/] E:\flutter project subhash\LMS\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=E:\flutter project subhash\LMS\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug

**Comment by TahaTesser** [comment]
Hi @subhashDev11 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by subhashDev11** [comment]
flutter run --verbose

Error: PowerShell executable not found.
       Either pwsh.exe or PowerShell.exe must be in your PATH.
[ +145 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +127 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 84f3d28555368a70270e9ac8390a9441df95e752
[   +1 ms] executing: [C:\flutter/] git tag --points-at HEAD
[ +228 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.2
[  +19 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +95 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +25 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] executing: C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +37 ms] List of devices attached
           c9fc9741               device product:1906 model:vivo_1906 device:1906 transport_id:2
[  +10 ms] C:\Users\pc\AppData\Local\Android\sdk\platform-tools\adb.exe -s c9fc9741 shell getprop
[ +134 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +199 ms] Found plugin camera at C:\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.8+11\
[ +176 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +4 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +11 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +7 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +9 ms] Found plugin permission_handler at C:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-3.0.0\
[  +28 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +4 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[   +4 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +7 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +5 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[ +187 ms] Found plugin camera at C:\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.8+11\
[  +28 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +1 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +3 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +3 ms] Found plugin permission_handler at C:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-3.0.0\
[   +6 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +3 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +1 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[  +74 ms] Generating E:\flutter project package\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +40 ms] ro.hardware = qcom
[  +62 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations

**Comment by TahaTesser** [comment]
Hi @subhashDev11 
Your logs are incomplete, doesn't have the error mention in the title 
Can you please provide your **complete** `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by subhashDev11** [comment]
> Hi @subhashDev11
> Your logs are incomplete, doesn't have the error mention in the title
> Can you please provide your **complete** `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

after removing dialog my issue is resolved 
Thanks you
