### ISSUE TITLE
Ww

### ISSUE THREAD

**Issue by fahad3344** [flutter/flutter#71332]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by fahad3344** [comment]
Zzxx

**Comment by fahad3344** [comment]
sudo snap install code --classic

**Comment by Bonchoisland12** [comment]
Ok how do I?

**Comment by iapicca** [comment]
@fahad3344 can you please provide more details about this issue, as it's hardly workable for now

**Comment by fahad3344** [comment]
_@@_

**Comment by YeungKC** [comment]
It appears to be an invalid issue at the moment, but I will reopen the issue if there are any valid updates.

**Comment by fahad3344** [comment]
> - 
https://www.sahafah24.net/news13613862.html?amp
وصفه بالأهبل والناعق.. فهد القرني يرد على الحجوري (جعفر) الذي دعا ...
https://www.sahafah24.net/news13613862.html?amp
وصفه بالأهبل والناعق.. فهد القرني يرد على الحجوري (جعفر) الذي دعا ...
https://www.sahafah24.net/news13613862.html?amp
وصفه بالأهبل والناعق.. فهد القرني يرد على الحجوري (جعفر) الذي دعا ...
