### ISSUE TITLE
Would be nice to have a way to fetch Assets from NSBundle or AssetManager

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7134]
Both iOS:
https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html#//apple_ref/doc/uid/10000123i-CH104-SW2
and Android:
https://developer.android.com/reference/android/content/res/Resources.html

Have ways to load resources.  Currently the Flutter framework only supports loading resources from within the .flx (which is itself a resource on these platforms) or from the network.  Would be nice to support loading using the platform bundling for cases where it's needed.

We likely still want to encourage developers to use .flx or some other shared system so they don't have to set up their assets twice, but there are likely always going to be times when the OEM asset systems are needed.

FYI @Hixie @tvolkert

**Comment by sethladd** [comment]
From @eseidelGoogle : There will be cases where the developer will want to load up an asset from a 3rd-party SDK.

**Comment by Hixie** [comment]
IIRC this is moot now.
