### ISSUE TITLE
Android 10 permission denied on creating file and folder.

### ISSUE THREAD

**Issue by glennmichaelmejias** [flutter/flutter#71355]
```
`E/flutter ( 2834): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mobilegameengine' (OS Error: Permission denied, errno = 13)
E/flutter ( 2834): #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117:11)
E/flutter ( 2834): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 2834): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 2834): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 2834): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 2834): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 2834): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 2834): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 2834): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 2834): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 2834): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 2834): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 2834): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2834): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`
```

**Comment by iapicca** [comment]
@glennmichaelmejias 
can you please provide your `flutter doctor -v `

possible duplicate of https://github.com/flutter/flutter/issues/71218

**Comment by darshankawar** [comment]
@glennmichaelmejias 
Along with `flutter doctor -v` requested above, please provide a minimal reproducible code sample that shows the issue. Also, Which device are you seeing this issue on ? can you try the same on Android OS < 10 and see if you get same error ?

**Comment by glennmichaelmejias** [comment]
`
➜  ~ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Linux, locale en_PH.UTF-8)
    • Flutter version 1.24.0-8.0.pre.374 at /home/mikeytronix/flutter
    • Framework revision 183f0e797a (4 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /home/mikeytronix/Android/Sdk/
    • Platform android-30, build-tools 29.0.0-rc2
    • ANDROID_HOME = /home/mikeytronix/Android/Sdk/
    • Java binary at: /home/mikeytronix/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /home/mikeytronix/Desktop/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (3 available)
    • Custom Phone (mobile) • 192.168.57.101:5555 • android-x86    • Android 10 (API 29)
    • Web Server (web)      • web-server          • web-javascript • Flutter Tools
    • Chrome (web)          • chrome              • web-javascript • Google Chrome 81.0.4044.92

• No issues found!
➜  ~ 
`

**Comment by glennmichaelmejias** [comment]
@darshankawar All phone with android 10 has issues reported on my app on google play.

**Comment by darshankawar** [comment]
@glennmichaelmejias 
Would like to see how you are creating file and folder using a sample code that'll help to analyse this issue better.
Thanks.

**Comment by glennmichaelmejias** [comment]
@darshankawar 
```
Future makeappprojectsdir() async {
  await requeststoragepermission();
  final String _appDocDir =
      await ExtStorage.getExternalStorageDirectory() + "/mobilegameengine";
  final Directory _appDocDirFolder = Directory('$_appDocDir/projects');
  if (await _appDocDirFolder.exists()) {
    return;
  }

  final Directory _appDocDirNewFolder =
      await _appDocDirFolder.create(recursive: true);

  return _appDocDirNewFolder.path;
}

```

**Comment by darshankawar** [comment]
@glennmichaelmejias 
This doesn't seem to be a complete code sample. We would need a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can simply copy paste and run in IDE to see the issue.

**Comment by glennmichaelmejias** [comment]
@darshankawar 
Thank you so much for giving me clue. It's just depracated api on android 10.
https://stackoverflow.com/questions/57116335/environment-getexternalstoragedirectory-deprecated-in-api-level-29-java/57116787#57116787

**Comment by darshankawar** [comment]
@glennmichaelmejias 
It seems you've found root-cause and possible solution to resolve your issue. Is this safe to close ?

**Comment by glennmichaelmejias** [comment]
Yes. Thank you so much.

**Comment by IbneUmmah** [comment]
@glennmichaelmejias  can you tell me how you fixed it because I am facing the same issue? I would appreciate it.

**Comment by glennmichaelmejias** [comment]
@IbneUmmah I have no idea, i suggest use plugin for file explorer or store your files on applications folder.
