### ISSUE TITLE
[web] How to extend (overwrite safe area) the content in a flutter web app ? 

### ISSUE THREAD

**Issue by 0xAMPS** [flutter/flutter#71359]
Hello, 

I'am trying to make a website with flutter web, but the content of the website do not want to 'stretch' because of the notch on iPhone X and later models. It works fine when using safe area and putting all the corners to false for an app running on iOS, but not on web with safari or chrome. 

I already tried to add in index.html a meta viewport with viewport-fit=cover but it did nothing.
## Steps to Reproduce

0. flutter web must be enabled and (python3 installed if you don't have an iPhone with notch or Xcode simulator)
1. Create a web project (use the default project generated). 
2. In the terminal, open the root of your project and run : flutter build web
3. In the terminal, open the build/web folder of your project and run : python3 -m http.server 8000
4. Open safari on your iOS simulator (if you don't have an iPhone with notch) or on your physical iPhone 
5. Find your ip (for macOS user go to System Preferences > Network > Advanced .. > TCP/IP and note the IPv4 address
6. Go to http://<yourIPv4Address>:8000 on safari of the iOS simulator or safari on a physical device with the same wifi as the computer. It should open the flutter web app on safari on an iPhone.
7. Rotate the device and note the white spacing and the content not overwriting the safe area as wanted.

**Expected results:** 

https://www.hostpic.org/images/2011290754270127.png

**Actual results:** 

https://www.hostpic.org/images/2011290755290113.png

<details>
  <summary>Logs</summary>

```
```

Analyzing flutx...                                                      
No issues found! (ran in 2.3s)

[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on macOS 11.0.1 20B29
    darwin-x64, locale fr-BE)
    • Flutter version 1.24.0-8.0.pre.374 at /Users/asikh/Flutter_dev/flutter
    • Framework revision 183f0e797a (2 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/asikh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.198

</details>

**Comment by darshankawar** [comment]
@0xAMPS 
I believe there's similar open issue describing your case, [71278](https://github.com/flutter/flutter/issues/71278)
Please follow-up there for updates. Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
