### ISSUE TITLE
ChoiceChips.shape Breaking Change

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#71352]
After enabling matrix builds on my library, I see that the code is working with `stable`, but breaking on `beta` and `dev`.

It appears that `shape` was changed from `ShapeBorder` to `OutlinedBorder` for `ChoiceChip`:
* https://github.com/flutter/flutter/commit/92d9630eaf9d2e59aaba02f5bd110c2cfcb5d291

I do not see any reference to this on the [Breaking Changes](https://flutter.dev/docs/release/breaking-changes) list.

My build reports `argument_type_not_assignable` errors:
```
  error • The argument type 'ShapeBorder' can't be assigned to the parameter type 'OutlinedBorder' • lib/src/fields/form_builder_choice_chips.dart:323:25 • argument_type_not_assignable
  error • The argument type 'ShapeBorder' can't be assigned to the parameter type 'OutlinedBorder' • lib/src/fields/form_builder_filter_chips.dart:130:23 • argument_type_not_assignable
```

_Was this break intentional?_

**Comment by pedromassangocode** [comment]
Hi @awhitford 
Can you please provide a sample code that this changes breaks?
Thank you

**Comment by awhitford** [comment]
Can I point you to the GitHub project in question?  Here are the two cases:

https://github.com/danvick/flutter_form_builder/blob/d4f862d662242a4887c03613260791a0f3f660b8/lib/src/fields/form_builder_choice_chips.dart#L323

and

https://github.com/danvick/flutter_form_builder/blob/d4f862d662242a4887c03613260791a0f3f660b8/lib/src/fields/form_builder_filter_chips.dart#L130

The project provides _wrappers_ for the built-in classes so that it can add some extra support for field management, validation, etc.  So the wrapper class has a `ShapeBorder shape`, and now can't pass that to the _new_ `OutlinedBorder shape`.

**Comment by HansMuller** [comment]
Please accept our apologies for not having been up front about this breaking API change, and for taking so long to review this issue. It looks like https://github.com/danvick/flutter_form_builder has migrated to the updated API; we appreciate your flexibility!
