### ISSUE TITLE
[web]: Flutter Web Doesn't Provide Link for Firestore Index

### ISSUE THREAD

**Issue by jbryanh** [flutter/flutter#71353]
In creating a Firestore query, I am not provided a link for creating an index with Firestore in the way that I am when developing an App or a regular web site with JavaScript.  

Primary Issue:
1. No link provided to create compound Index with Firestore.
2. There is some sort of double callback where, after an index is manually created, the data appears and suddenly disappears.

Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64, locale en-US)
Chrome Version 87.0.4280.67 (Official Build) (x86_64)

Nothing comes up in my debug console in Android Studio or the Browser console. I then manually created the composite index, but I'm still unable to get the query working. Some investigation on stackoverflow shows universal confusion on this issue, and nothing's been submitted here I can find.

Example of code I'm trying to run:

```
return facilityList.doc(facility)
.collection('attendance archive')
.where('dateTime', isGreaterThanOrEqualTo: newDate)
.where('id', whereIn: [childID])
.orderBy('dateTime').limit(20)
.snapshots()
.map(_archiveListFromSnapshot);
```

can run just fine with only one .where, but combined, and doesn't function.

**Comment by jbryanh** [comment]
This is very related to #774 and #18948, however they were not Flutter Web issues, and original App issues.  This issue continues for Web.  In addition, adding the compound query manually doesn't seem to resolve it.  The behavior is nearly identical with the double fire, and data showing and suddenly disappearing.

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/bryanhunsberger/Developer/flutter
    • Framework revision 198df796aa (6 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/bryanhunsberger/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67

• No issues found!

**Comment by jbryanh** [comment]
Update:
As with #774 and #18948 there appears to be a double callback.  At first I have data, and then none.  My manual index is working.  The data appears and then suddenly disappears.

**Comment by iapicca** [comment]
@jbryanh 
issue related to firebase with flutter should be opened in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by darshankawar** [comment]
Closing this from here, as this seems to be an issue with Firestore plugin. @jbryanh Please open this issue in above referred repo link.

**Comment by jbryanh** [comment]
done. [#4270 in FirebaseExtended/flutterfire ](https://github.com/FirebaseExtended/flutterfire/issues/4270)
