### ISSUE TITLE
Rebuilding a TabBarView with new data crashes

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#7135]
Run "flutter create" and replace main.dart with this gist: https://gist.github.com/gavindoughtie/264e2ba1e2cbb960f4996073abc3a753

The first tab bar view renders correctly (you can swipe through the various shades of red).

Clicking one  of the other color buttons should re-render the tab bar view with a different color palette, but instead there's this stack trace:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building TabBarSelection<Color>(current tab:
Color(0xffa5d6a7); available tabs: [Color(0xffa5d6a7), Color(0xff81c784), Color(0xff66bb6a),
Color(0xff4caf50), Color(0xff43a047), Color(0xff388e3c)]; state:
TabBarSelectionState<Color>(267201042; ticker inactive)):
The null object does not have a method '-'.
NoSuchMethodError: method not found: '-'
Receiver: null
Arguments: [1]
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _TabBarViewState._updateItemsForSelectedIndex (package:flutter/src/material/tabs.dart:1161:46)
#3      _TabBarViewState.didUpdateConfig (package:flutter/src/material/tabs.dart:1131:7)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:2783:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#7      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:2787:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#13     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#14     StatelessElement.update (package:flutter/src/widgets/framework.dart:2716:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3169:26)
#17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3542:17)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#20     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:2905:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3169:26)
#24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3542:17)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#27     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:2905:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#31     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#32     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#37     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#38     StatelessElement.update (package:flutter/src/widgets/framework.dart:2716:5)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#43     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#44     StatelessElement.update (package:flutter/src/widgets/framework.dart:2716:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#49     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#50     StatelessElement.update (package:flutter/src/widgets/framework.dart:2716:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#53     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#57     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#61     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:1963:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678:16)
#65     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567:5)
#66     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1668:33)
#67     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:297:20)
#68     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:152:5)
#69     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:648:15)
#70     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:583:9)
#71     _beginFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:48)

**Comment by gavindoughtie** [comment]
FYI, here's a workaround:

https://gist.github.com/gavindoughtie/7c3cdfe2585ae0914189ea925b4983ff

**Comment by HansMuller** [comment]
The tabs implementation was rewritten late last year and the issue raised here no longer occurs.

Here's a version of the test app that does the right thing:
https://gist.github.com/HansMuller/88abe25c0c1e0d9f8ae61349c9bb59ee
