### ISSUE TITLE
Sending a Uint8List via the MethodChannel from Dart to iOS

### ISSUE THREAD

**Issue by kostasoft** [flutter/flutter#71357]
Hello!
Need help sending Uint8List via MethodChannel from Dart to iOS.
If everything is clear with the transfer from Swift to Dart:
wrap a variable of type Data like this:
         FlutterStandardTypedData (bytes: Data) and pass it.
What about the postback?
Dart has a UInt8List, you need to get Data in Swift-e, or at least [Uint8]

**Comment by iapicca** [comment]
@kostasoft 
this platform is meant to improve flutter with bug report and feature request;
if you need help with your code please follow the link under `I want help writing my application ` in the [new issue choices](https://github.com/flutter/flutter/issues/new/choose)

you may want to take a look to [pigeon](https://pub.dev/packages/pigeon) for this task

**Comment by darshankawar** [comment]
@kostasoft 
Please follow above links to better address your question.
Also, this issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by TahaTesser** [comment]
Hi @kostasoft 
Check out https://www.programmersought.com/article/43331167274/

Just tried it by modifying [platform_channel_swift example](https://github.com/flutter/flutter/tree/master/examples/platform_channel_swift)
```dart

  Future<void> _getBatteryLevel() async {
    Uint8List data = (await NetworkAssetBundle(Uri.parse('https://i.imgur.com'))
            .load('/QCNbOAo.png'))
        .buffer
        .asUint8List();

    String batteryLevel;
    try {
      final int result =
          await methodChannel.invokeMethod('getBatteryLevel', data);
      batteryLevel = 'Battery level: $result%.';
    } on PlatformException {
      batteryLevel = 'Failed to get battery level.';
    }
    setState(() {
      _batteryLevel = batteryLevel;
    });
  }
```
```swift
     [weak self] (call: FlutterMethodCall, result: FlutterResult) -> Void in
      guard call.method == "getBatteryLevel" else {
        result(FlutterMethodNotImplemented)
        return
      }
        
        let uintInt8List =  call.arguments as! FlutterStandardTypedData
        let byte = [UInt8](uintInt8List.data)
        
        let pointer = UnsafeMutablePointer<UInt8>.allocate(capacity: 4)
        pointer.advanced(by: 0).pointee = byte[0]
        pointer.advanced(by: 1).pointee = byte[1]
        pointer.advanced(by: 2).pointee = byte[2]
        pointer.advanced(by: 3).pointee = byte[3]
        
        print("byte data : %s", byte)
      self?.receiveBatteryLevel(result: result)
    })
```

You can convert it back to `FlutterStandardTypedData`  as  well
