### ISSUE TITLE
[pigeon] Support Dart null safety

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#71360]
The code generated by `pigeon` is not yet migrated to null safety (it is still `@dart=2.8`).

If we want to have sound null safety in our package code, we will want to have pigeon support null safety.

---

I thought this was related to https://github.com/flutter/flutter/issues/59118#issue-635859306, however, I think that issue is talking about platform nullability.

**Comment by iapicca** [comment]
aa requested in [pigeon feedback](https://pub.dev/packages/pigeon#feedback) cc @gaaclarke

**Comment by ammaratef45** [comment]
I wonder if there's an investigation that tells if #71929 is related to this issue or not?

**Comment by Hixie** [comment]
Duplicate of https://github.com/flutter/flutter/issues/59118
