### ISSUE TITLE
I can not install Flutter, and flutter doctor says android Studio does not have Dart or flutter, and refuses to allow me to accept licenses.

### ISSUE THREAD

**Issue by aortax** [flutter/flutter#71362]
## Steps to Reproduce
I do not really know how to reproduce this, because I just installed Flutter, according to the standard instructions, and did nothing special. I followed a couple of different youtube videos and my professors, and I don't see any difference, and I rewatched a couple of times, so not an execution issue. Just before I set Java to the path, but I don't think that is very relevant, but that is the only special thing I'd say I did. Moreover, on this same computer before, I was able to successfully set up Flutter and work it in Android Studio.

1. ...When I use Flutter doctor I am told I do not have Flutter or Dart in android studio when I do.
![image](https://user-images.githubusercontent.com/60589475/100532758-3ef2bd00-31b1-11eb-909d-8641c9d9ff4c.png)
![image](https://user-images.githubusercontent.com/60589475/100532765-4fa33300-31b1-11eb-8357-d23e0583296e.png)
As you see here I have them both, and it is working in Android Studio.
![image](https://user-images.githubusercontent.com/60589475/100532768-647fc680-31b1-11eb-9aea-cd8d12b965a0.png)
I also am able to run the demo basic flutter application, but it does not respond, which is another really weird thing for me. I do not know how it says I don't have a flutter in the android studio when it lets me make the flutter project, and even run it.

2. ...When I try to accept the flutter license and run it I get
C:\Users\Huzaifa>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
Not sure how to fix this one at all.
3. ...

## Logs

```
```

```
```[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.4 at C:\Users\Huzaifa\Documents\flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Huzaifa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\Huzaifa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
![image](https://user-images.githubusercontent.com/60589475/100532795-b7597e00-31b1-11eb-98d5-1888a4b9a367.png)

**Comment by Abhishek01039** [comment]
Hello @aortax 
you can refer to this https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a
Thanks

**Comment by aortax** [comment]
> 
> 
> Hello @aortax
> you can refer to this https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a
> Thanks

I followed set JAVA_OPTS=-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee, and then I got 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found

![image](https://user-images.githubusercontent.com/60589475/100551518-f03b3680-3235-11eb-9582-fedfa311d9cc.png)

**Comment by aortax** [comment]
I found the solution 

Just had this error, solved by downloading the Android SDK Command-line Tools (latest) on Android Studio, under settings > Appearance & Behavior > System Settings > Android SDK > SDK Tools and re-running flutter doctor --android-licenses

![image](https://user-images.githubusercontent.com/60589475/100551730-773cde80-3237-11eb-9f9d-b4333599fdf3.png)
![image](https://user-images.githubusercontent.com/60589475/100551732-7ad06580-3237-11eb-80d5-045f04234d9e.png)
credit to 
![image](https://user-images.githubusercontent.com/60589475/100551743-8c197200-3237-11eb-90dc-1a8c580f8205.png)

**Comment by Abhishek01039** [comment]
Android license is accepted @aortax ?

**Comment by TahaTesser** [comment]
Hi @aortax 
I take it (based on https://github.com/flutter/flutter/issues/71362#issuecomment-735443463), the android license issue is resolved. 
When it comes Plugin not detected isn't critical in `flutter doctor -v`, it won't affect flutter functionality, please check https://github.com/flutter/flutter/issues/67986#issuecomment-715452201

Closing,  If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by aortax** [comment]
Yup, it has been solved, and I agree with Taha, everything is working right now. I do not see any issue as of right now.
