### ISSUE TITLE
Fonts don't seem to be tree shaked properly on web

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#71361]
## Details

1. Download this minimal example project: [broken_tree_shaking.zip](https://github.com/flutter/flutter/files/5611581/broken_tree_shaking.zip)
2. **Optional (if you want to build yourself):** `flutter build web --release --tree-shake-icons` and remove the serviceworker
3. cd into `build/web`
4. Run a local `python3 -m http.server` or `python -m SimpleHTTPServer` (I ran into unrelated caching issues with http.server)
5. Generate a Lighthouse report
6. Check the network tab and reload

### Optimal result in a perfect world:
- `CupertinoIcons.ttf` is completely removed since it isn't referenced anywhere except in the `pubspec.yaml`
- `MaterialIcons-Regular.otf` is completely stripped of everything except the 3 or so referenced icons
- `BrandIcons.ttf` is completely stripped as well
- `Catamaran-*.ttf` are completely removed. In the original project, `Catamaran-VariableFont_wght.ttf` is never used anywhere, but in this one, none of them are.

### Actual result
- Every font file from pubspec.yaml is included in the final build
- Lighthouse perf score is pretty bad (50 in my case), but since its a local unoptimized dev server that could be misleading

### About the example project:
- I include different Catamaran ttfs
- I include MaterialIcons-Regular.otf to fix missing icons
- I include CupertinoIcons.ttf (even though i don't need them)
- I also disabled the service worker because it creates extra noise in the network tab that isn't relevant to this issue
- I include `BrandIcons.ttf`, which is referenced via `brand_icons_icons-dart` (generated via a tool)
- Only a few icons are actually used (some material ones, some brandicons)
- None of the Catamaran fonts are actually used anywhere. In my original project, I'm actually using the non-variable Catamaran fonts, but since that apparently doesn't make a difference, I've skipped part where I use them in this project.

---

**Target Platform:** Web
**Target OS version/browser:** 87.0.4280.67 (Official Build) (x86_64)
**Devices:** -

## Logs

<details>
<summary>logs</summary>

```
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on macOS 11.0 20A5343i darwin-x64, locale de-DE)
    • Flutter version 1.24.0-10.2.pre at ...
    • Framework revision 022b333a08 (10 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ...
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = ...
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • macOS 11.0 20A5343i darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67

! Doctor found issues in 1 category.
```

</details>

**Comment by CiriousJoker** [comment]
Sorry for not doing my research before. I just realized there's this open issue:
https://github.com/flutter/flutter/issues/57181

Are any of my points still valid? Like, would all of the mentioned issues be fixed if this was implemented?

**Comment by jonahwilliams** [comment]
> would all of the mentioned issues be fixed if this was implemented?

Yes
