### ISSUE TITLE
Flutter Roadmap

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#71377]
ignore me - do not delete - will be filled

**Comment by iapicca** [comment]
@YazeedAlKhalaf 
I suspect this being related to this issue,
but **_IF_** the proposal is accepted 
it would be better if team members themselves present a roadmap

maybe this issue is premature

**Comment by YazeedAlKhalaf** [comment]
Yea I just thought about it 😁😅

**Comment by stuartmorgan** [comment]
Per the other issue, the roadmap is in the wiki, not the issue tracker.
