### ISSUE TITLE
Navigator assertion issue

### ISSUE THREAD

**Issue by Gabbar8** [flutter/flutter#71374]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 

[bug.zip](https://github.com/flutter/flutter/files/5612228/bug.zip)

3. ... 

**Expected results:** 
![image](https://user-images.githubusercontent.com/32429428/100543435-28626980-3276-11eb-9481-7098ef19ccd8.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/32429428/100543506-9018b480-3276-11eb-92d8-faa12cdbb557.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@Gabbar8 
the zipped sample you provided contains the basic counter app,
can you provider a code sample that represent the issue you are describing
together with your `flutter doctor -v`

**Comment by TahaTesser** [comment]
Hi @Gabbar8 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
