### ISSUE TITLE
[Question] Flutter TabBarView expands children

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#71373]
Sorry for question, I'm asked in [stackoverflow](https://stackoverflow.com/questions/65059996/flutter-tabbarview-expands-children) before

In the following code TabBarView expands children LinearProgressIndicator , How can I fix it ?

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              LinearProgressIndicator(),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}

```

Why wrapping `Column` works but `ConstrainedBox`, `SizedBox` or `Container` with `double.infinite` height not?

**Comment by fahad3344** [comment]
git config --global alias.ignore \
'!gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi'

**Comment by pedromassangocode** [comment]
Hi @sm2017 
It seems you are asking for assistance on personal code. Please see https://flutter.dev/community for resources and asking questions like this, if you need help with your code, please see https://www.reddit.com/r/flutterhelp/



Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
