### ISSUE TITLE
FATAL EXCEPTION - couldn't find "libflutter.so

### ISSUE THREAD

**Issue by carlfost** [flutter/flutter#71386]
My application crashed on startup  using the appbundle built and test with Google Play Console Internal Test.  App also crashed using Android Studio when App startup; however the app works find on Flutter Run with the emulator.  This started after Flutter Upgrade and Android Studio upgrade.
The the error from Android Studio Logcat log is below.

## Steps to Reproduce
1) Build the App with appbundle and create an Internal Test release in Google Console, or
2) Run the App from Android Studio

**Expected results:**
App runs without crashing on startup.

**Actual results:**
App crashed - FATAL EXCEPTION: couldn't find "libflutter.so

<details>
  <summary>Logs</summary>
2020-11-29 18:14:59.169 30120-30120/com.outafire.myevents E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.outafire.myevents, PID: 30120
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.outafire.myevents/com.outafire.myevents.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/base.apk"],nativeLibraryDirectories=[/data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/lib/x86, /data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libflutter.so"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
```

Analyzing church_events...                                              
No issues found! (ran in 10.4s)
```
```
PS C:\development\church_events> flutter doctor -v 
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\src\flutter\flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\carlfost\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\carlfost\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code
    • VS Code at C:\Users\carlfost\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @carlfost 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by carlfost** [comment]
PS C:\development\church_events> flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
• Flutter version 1.22.4 at C:\src\flutter\flutter
• Framework revision 1aafb3a (2 weeks ago), 2020-11-13 09:59:28 -0800
• Engine revision 2c956a31c0
• Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
• Android SDK at C:\Users\carlfost\AppData\Local\Android\Sdk
• Platform android-30, build-tools 30.0.2
• ANDROID_HOME = C:\Users\carlfost\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[!] Android Studio (version 4.1.0)
• Android Studio at C:\Program Files\Android\Android Studio
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code
• VS Code at C:\Users\carlfost\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.16.0

[√] VS Code, 64-bit edition (version 1.51.1)
• VS Code at C:\Program Files\Microsoft VS Code
• Flutter extension version 3.16.0

[√] Connected device (1 available)
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by carlfost** [comment]
Crash log filtered on FATAL

2020-11-29 18:14:59.169 30120-30120/com.outafire.myevents E/AndroidRuntime: FATAL EXCEPTION: main Process: com.outafire.myevents, PID: 30120 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.outafire.myevents/com.outafire.myevents.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/base.apk"],nativeLibraryDirectories=[/data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/lib/x86, /data/app/com.outafire.myevents-qO9j7AlSaDLY1gNIuqdxSg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libflutter.so" at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by carlfost** [comment]
PubSpec.yaml

name: churchevents
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  http: ^0.12.2
  dropdown_formfield: ^0.1.2
  provider: ^4.3.2+1 
  path_provider: any
  equatable: ^1.2.5
  shared_preferences: ^0.5.10
  scoped_model: ^1.0.1
  image_picker: ^0.6.7+7
  json_annotation: ^3.0.1
  dio: ^3.0.10
  flutter_typeahead: ^1.8.8
  google_fonts: ^1.1.0
  badges: ^1.1.1
  flutter_local_notifications: ^1.4.4+4
  youtube_player_flutter: 
  smooth_star_rating: ^1.1.1
  carousel_slider: ^2.1.1
  rxdart: ^0.24.1
  url_launcher: ^5.5.2
  stripe_payment: ^1.0.8
  flutter_webrtc: ^0.2.8
  sdp_transform: ^0.2.0
  flutter_ringtone_player: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/bulletin.png
   - assets/images/bus.jpg
   - assets/images/ansinmap.jpg
   - assets/images/mapicon.bmp
   - assets/images/mailbox.jpg
   - assets/images/embededVideo.png
   - assets/images/utubeid.png
   - assets/images/loading.gif
   - assets/images/church.jpg
   - assets/images/coordinator.jpg
   - assets/images/event.jpg
   - assets/images/review.jpg
   - assets/images/notes.png
   - assets/images/register.jpg
   - assets/images/settings.png
   - assets/images/video.png
   - assets/images/login.png
   - assets/images/programs.jpg
   - assets/images/bible2.jpg
   - assets/images/offering2.jpg
   - assets/images/mainscrn.jpg

  # - Language transilation files
   - lib/lang/en.json 
   - lib/lang/es.json 
   - lib/lang/fr.json

**Comment by carlfost** [comment]
> Hi @carlfost
> Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
> Thank you

Please note that the Flutter Run built worked on VSCode, but failed on Android Studio.  Also the AppBungle built failed (crashed on startup) when tested via Google Play Console Internal Test.

**Comment by carlfost** [comment]
> flutter run --release --verbose

PS C:\development\church_events> flutter run --release --verbose
[ +132 ms] executing: [C:\src\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +1 ms] executing: [C:\src\flutter\flutter/] git tag --points-at HEAD
[  +87 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.4
[   +9 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url origin
[  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[  +49 ms] https://github.com/flutter/flutter.git
[  +72 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +15 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] executing: C:\Users\carlfost\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +39 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[   +6 ms] C:\Users\carlfost\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +71 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +180 ms] Found plugin flutter_inappwebview at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-4.0.0+4\
[  +11 ms] Found plugin flutter_keyboard_visibility at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\
[  +10 ms] Found plugin flutter_local_notifications at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-1.5.0+1\
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.9\
[   +4 ms] Found plugin flutter_ringtone_player at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_ringtone_player-2.0.0\
[   +6 ms] Found plugin flutter_webrtc at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webrtc-0.2.8\
[  +11 ms] Found plugin image_picker at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+9\
[  +32 ms] Found plugin path_provider at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.16\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+4\     
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.3\   
[  +21 ms] Found plugin shared_preferences at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.10\
[  +12 ms] Found plugin shared_preferences_linux at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+2\
[   +2 ms] Found plugin shared_preferences_macos at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +4 ms] Found plugin shared_preferences_web at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +23 ms] Found plugin stripe_payment at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.8\
[  +12 ms] Found plugin url_launcher at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.6.0\
[   +5 ms] Found plugin url_launcher_linux at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\       
[   +2 ms] Found plugin url_launcher_macos at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+8\       
[   +3 ms] Found plugin url_launcher_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.3+2\
[   +9 ms] Found plugin url_launcher_windows at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+1\   
[ +249 ms] Found plugin flutter_inappwebview at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-4.0.0+4\
[   +2 ms] Found plugin flutter_keyboard_visibility at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-3.2.2\
[  +14 ms] Found plugin flutter_local_notifications at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-1.5.0+1\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.9\
[   +2 ms] Found plugin flutter_ringtone_player at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_ringtone_player-2.0.0\
[   +3 ms] Found plugin flutter_webrtc at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webrtc-0.2.8\
[   +5 ms] Found plugin image_picker at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+9\
[  +10 ms] Found plugin path_provider at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.16\
[  +10 ms] Found plugin path_provider_linux at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\     
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+4\     
[   +4 ms] Found plugin path_provider_windows at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.3\   
[  +23 ms] Found plugin shared_preferences at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.10\
[   +5 ms] Found plugin shared_preferences_linux at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+2\
[   +1 ms] Found plugin shared_preferences_macos at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +3 ms] Found plugin shared_preferences_web at
C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +12 ms] Found plugin stripe_payment at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-1.0.8\
[   +4 ms] Found plugin url_launcher at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.6.0\
[   +6 ms] Found plugin url_launcher_linux at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+8\       
[   +2 ms] Found plugin url_launcher_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.3+2\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+1\   
[  +29 ms] Generating C:\development\church_events\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +30 ms] ro.hardware = ranchu
[  +23 ms] "flutter run" took 1,061ms.
[   +5 ms] Release mode is not supported by Android SDK built for x86.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +139 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by pedromassangocode** [comment]
Hi @carlfost 
Do you have a physical device to run the command I've asked to? The emulator you used is not supported for release builds!

**Comment by carlfost** [comment]
I ran flutter pub cache repair, and then upgraded all the plugins to the latest versions.
This fixed the problem.
