### ISSUE TITLE
Developers would like guidance on how to log from their app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7138]
A question from a current Flutter developer: "It would be useful to have information on logging and debugging".

**Comment by eseidelGoogle** [comment]
I think we have some debugging info: https://flutter.io/debugging/
Logging may be covered in part by https://pub.dartlang.org/packages/logging

**Comment by Hixie** [comment]
Moving out of m3 since this doesn't fit our current priorities.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1998](https://github.com/flutter/website/issues/1998) via [**ZenHub**](https://www.zenhub.com/)
