### ISSUE TITLE
Flutter windows: Failed to download sky_engine.zip, then flutter failed to open said zip file

### ISSUE THREAD

**Issue by TomGao2001** [flutter/flutter#71383]
## Steps to Reproduce

1. Run flutter channel dev, flutter upgrade, flutter config --enable-windows-desktop (as per https://flutter.dev/desktop#additional-windows-requirements)
2. Run anything else (flutter doctor, or flutter create, or flutter devices) that triggers a download of sky_engine.zip
3. "Failed to download ... sky_engine.zip" and "Exception: flutter failed to open a file at ...sky_engine.zip"

## Logs

```
C:\Users\gzm20\Desktop\Development\flutterDev>flutter doctor -v
Downloading package sky_engine...                                2,195ms
Downloading package sky_engine...                                  102ms
Failed to download https://storage.googleapis.com/flutter_infra/flutter/07c1eed46b9d9b58df78566e9b8b2e42e80d3380/sky_engine.zip. Ensure you have network connectivity and then try again.
Exception: Flutter failed to open a file at
"C:\Users\gzm20\Desktop\Development\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\07c1eed46b9d9b58df78566e9b8b2e42e80d3380\sky_engine.zip". The flutter tool cannot access
the file.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1768:11)
#2      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1720:12)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:914:29)
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:693:11)
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:563:24)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1035:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

FYI:
If I paste the URL I can download sky_engine.zip to my computer via my browser; when I put it in the specified folder, flutter still tries to download it (and fails).
I have had OS access troubles with flutter before as well. I've done everything I can to make sure it's not an access problem (disabled read-only, given all access privileges (rwx), run as admin). It still keeps happening.

**Comment by TahaTesser** [comment]
Hi @TomGao2001 
Are you located in a restricted ocuntry? Can you please try a different internet connection or VPN?
No issues for when running flutter on windows on the latest  dev or master channel 
Thank you

**Comment by TomGao2001** [comment]
Nope. I live in the US & internet is normal afaik.
I was able to copy-paste the URL and get the file manually (though flutter still tries to re-download it).
I don't know if windows firewall/antivirus/etc etc have been blocking this, but flutter has been able to switch channels, upgrade, etc. from the command line so I doubt that's the issue.
Any existing issues you can point me towards?

**Comment by TahaTesser** [comment]
Hi @TomGao2001 
Can you please disable antivirus/firewall, it could be causing it even if you can upgrade or switch channels, 
https://github.com/flutter/flutter/issues/61997
Try moving flutter SDK to a different folder? or clone a fresh copy from `git clone -b master https://github.com/flutter/flutter.git`

**Comment by TomGao2001** [comment]
Ok, it seems to be the antivirus! Glad I tried that.
Added flutter SDK path and project path to whitelist.
```
C:\Users\gzm20>flutter doctor
Downloading package sky_engine...                                  486ms
Downloading flutter_patched_sdk tools...                         1,231ms
Downloading flutter_patched_sdk_product tools...                 2,575ms
Downloading windows-x64 tools...                                 2,852ms
Downloading windows-x64/font-subset tools...                       361ms
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

• No issues found!
```
By default Avast free antivirus blocks default behavior of flutter. I think this is probably worthy of note in the tutorial/install instructions.

**Comment by TahaTesser** [comment]
@TomGao2001 
Yes, it is recommended to add in the allowlist/whitelist, https://github.com/flutter/flutter/issues/61997 is open to address this
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by Java-Jagdish** [comment]
Hi All, I am getting same error, even I have disabled the windows defender

C:\flutter>flutter doctor -v
Downloading package sky_engine...                                1,553ms
Downloading package sky_engine...                                  692ms
Failed to download
https://storage.googleapis.com/flutter_infra/flutter/a243f4df071192948599e4535f87563a78295694/sky_engine.zip. Ensure youhave network connectivity and then try again.
SocketException: OS Error: Access is denied.
, errno = 5, address = storage.googleapis.com, port = 59005

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1769:11)
<asynchronous suspension>
#2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:913:7)
<asynchronous suspension>
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:692:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)

Please give me any solution if possible

**Comment by TomGao2001** [comment]
@Java-Jagdish  I had avast antivirus, and I basically added my whole flutter path to a setting so they wouldn't even scan that path. I don't think Windows Defender had anything related to it.

**Comment by Java-Jagdish** [comment]
@TomGao2001  
I didn't have any antivirus.

**Comment by TomGao2001** [comment]
@Java-Jagdish No idea then, I solved my problem above by disabling my antivirus scan at that folder. Maybe something else is blocking the download?
