### ISSUE TITLE
[share] iOS system sharing dialog not showing the document title

### ISSUE THREAD

**Issue by adario** [flutter/flutter#71407]
Hello,

On iOS (14.x), in certain cases the share 0.6.5+4 package does not show the name of shared files — the actual sharing operation works file, but the system sharing dialog appears titleless.  I've attached two screenshots — one of a file that displays the title, the other of a file that doesn't.  Output from flutter doctor is available below:

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IE)
    • Flutter version 1.22.4 at /Users/darioaccornero/Applications/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/darioaccornero/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM G960F (mobile) • 2591e03728057ece                         • android-arm64 • Android 10 (API 29)
    • iPhone X (mobile) • a08a91f17d8101c51c475bb449ddc5ff5a0fcfca • ios           • iOS 14.2

• No issues found!
![IMG_A67524CED28A-1](https://user-images.githubusercontent.com/440938/100625906-6b2f4a80-3325-11eb-8d76-417234378577.jpeg)
![IMG_8C6D2B74B9BF-1](https://user-images.githubusercontent.com/440938/100625943-74b8b280-3325-11eb-9fcd-ed6a860fdd48.jpeg)

**Comment by darshankawar** [comment]
@adario 
There's similar open issue describing your case, [55061](https://github.com/flutter/flutter/issues/55061).
Please follow-up there for updates.
Closing this as duplicate.
