### ISSUE TITLE
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.

### ISSUE THREAD

**Issue by giacomok** [flutter/flutter#71409]
Suddenly (times ago I didn't have these errors) I have this problem when I launch the debug of app:

`Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
`

This is the result of flutter doctor -v:

    [√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Versione 6.1.7601], locale it-IT)
        • Flutter version 1.22.4 at H:\flutter
        • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
        • Engine revision 2c956a31c0
        • Dart version 2.10.4

    [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
        • Android SDK at H:\Android\sdk
        • Platform android-30, build-tools 30.0.2
        X Android SDK file not found: H:\Android\sdk\build-tools\30.0.2\aapt.
        • Try re-installing or updating your Android SDK,
          visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

    [!] Android Studio (version 4.1.0)
        • Android Studio at C:\Program Files\Android\Android Studio
        X Flutter plugin not installed; this adds Flutter specific functionality.
        X Dart plugin not installed; this adds Dart specific functionality.
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

    [√] Connected device (1 available)
        • SM G935F (mobile) • 988674375232393850 • android-arm64 • Android 8.0.0 (API 26)

    ! Doctor found issues in 2 categories.

But this file (`H:\Android\sdk\build-tools\30.0.2\aapt`) does exist, and the dart and flutter plugins are both installed.  
What I've tried is:

- flutter config --android-sdk "H:\Android\sdk"
- flutter doctor --android-licenses

I am reading a lot of topics on the net, but I do not know howto solve it.

**Comment by iapicca** [comment]
@giacomok 
this seems more a question for [stackoverflow](https://stackoverflow.com/questions/52754146/unable-to-locate-a-development-device-please-run-flutter-doctor-for-informati) than a bug with flutter

**Comment by giacomok** [comment]
I've already read that post and I did not solve my problem.

**Comment by darshankawar** [comment]
@giacomok 
`Android SDK file not found: H:\Android\sdk\build-tools\30.0.2\aapt.` probably indicates the platform-tools are not installed fully or properly. 

You may check and confirm that from `Setting > Android SDK >SDK platform>` and see if all required build-tools and platform-tools are installed. You may also need to double-check the path environment and setup.

**Comment by giacomok** [comment]
@darshankawar you right, the problem was the platform-tools version 30.0.2 was not properly installed.

To solve I just deleted that folder.
