### ISSUE TITLE
iOS developers would like an easy onboard to Flutter, and map their knowledge to Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7140]
Developers with a lot of iOS development experience would like to know how to map their current understanding/knowledge to Flutter.

What concepts are similar? Different? What's new in Flutter? If they knew how to do X in iOS, how do they do it in Flutter?

**Comment by Sfshaza** [comment]
[Flutter for iOS Developers](https://flutter.io/flutter-for-ios/) was launched some time ago. Closing.
