### ISSUE TITLE
hotReloadFlutterReassembleMillisecondsAfterLargeChange hot_mode_dev_cycle_macos_target__benchmark regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#71416]
https://flutter-flutter-perf.skia.org/e/?begin=1605740041&end=1606414348&keys=Xa755124da5edffa05dde0d36df7a7f93&requestType=0&xbaroffset=22624 shows the peak, although I think the suspect commit is https://github.com/flutter/flutter/pull/70965. 

@dnfield This looks like your commit. Can you have a look and confirm? I think it's really a test issue.

**Comment by jonahwilliams** [comment]
That change was to fix the benchmark, it is working as expected now.

Thanks for the heads up though!
