### ISSUE TITLE
Web. TextOverflow.fade sets the Text background color to white.

### ISSUE THREAD

**Issue by louisdeveseleer** [flutter/flutter#71413]
## Steps to Reproduce

A Text that overflows from its container and is set to `overflow: TextOverflow.fade,` will get a white background. If using ellipsis, if there is no overflow, of if compiled for mobile, the issue does not appear.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: Container(
            width: 200,
            height: 35,
            child: Text(
              'This is a long text that will not fit on a single line.',
              style: TextStyle(color: Colors.red),
              overflow: TextOverflow.fade,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Expected results:** Same as mobile : the text fades correctly.

**Actual results:** White background on the text that overflows.

Doctor: 
All done!
[√] Flutter: is fully installed. (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1198], locale en-BE)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.0)
[√] Chrome - develop for the web: is fully installed.
[√] Android Studio: is fully installed. (version 4.1.0)
[√] Connected device: is fully installed. (3 available)

**Comment by darshankawar** [comment]
Verified and issue replicable on latest beta and on master.

Web:

<img width="318" alt="Screenshot 2020-12-01 at 12 28 18 PM" src="https://user-images.githubusercontent.com/67046386/100708525-7be9ca00-33d2-11eb-88c4-33658e4638fd.png">

Android:

<img width="264" alt="Screenshot 2020-12-01 at 12 37 11 PM" src="https://user-images.githubusercontent.com/67046386/100708541-81471480-33d2-11eb-9a84-1800175cd1d6.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.67

• No issues found!



```

</details>

**Comment by mdebbar** [comment]
I did some investigation and here's what I found.

The framework implements this by doing the following:
* Creates a [linear gradient shader](https://github.com/flutter/flutter/blob/afe3d0d2973590497b79daf8861a756f4fa5921e/packages/flutter/lib/src/rendering/paragraph.dart#L711-L715).
* During the painting phase, it calls [`saveLayer`](https://github.com/flutter/flutter/blob/afe3d0d2973590497b79daf8861a756f4fa5921e/packages/flutter/lib/src/rendering/paragraph.dart#L753).
* Draws the paragraph.
* Draws a rect with the linear gradient shader and the `modulate` blend mode [here](https://github.com/flutter/flutter/blob/afe3d0d2973590497b79daf8861a756f4fa5921e/packages/flutter/lib/src/rendering/paragraph.dart#L788-L791).

Our implementation of `saveLayer` has a [TODO](https://github.com/flutter/engine/blob/7c2da3bf62f428813188d75ffbbf30a37c8daae9/lib/web_ui/lib/src/engine/html/recording_canvas.dart#L221) that could be one of the issues going on here.

cc @ferhatb and @hterkelsen if they have any ideas.

**Comment by yjbanov** [comment]
Yes, `saveLayer` in the HTML renderer is the same as `save`, which has similar but not the same effect. Typically when someone uses `saveLayer` they specifically want the "layer" semantic. This should be relatively straightforward to implement if everything is drawn using HTML elements. `<canvas>` is trickier.

**Comment by yjbanov** [comment]
@mdebbar Thanks for the detailed analysis!

**Comment by diaz-wmg** [comment]
We are having this problem with HTML renderer as well! Any updates on this issue?

**Comment by thgoebel** [comment]
> We are having this problem with HTML renderer as well! 

Please note https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-comments-to-bugs

> Any updates on this issue?

https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed should answer this question.

**Comment by yjbanov** [comment]
This is caused by the lack of `saveLayer` support in the HTML renderer. Deduplicating with https://github.com/flutter/flutter/issues/48417. For now, you can treat `TextOverflow.fade` as unsupported and use a different effect.

**Comment by yjbanov** [comment]
(that is if you need to use the HTML renderer; CanvasKit supports it)
