### ISSUE TITLE
Move default branch from master to main

### ISSUE THREAD

**Issue by hemish11** [flutter/flutter#71419]
Recently, Github has changed the master branch to main, so we should also take this step and change the branch of a flutter from master to main.

Here are all the commands that need to run to make a clone of this branch with a different name:
`git branch -m master main`
`git push -u origin main`
`git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main`

After all this, we need to change the default branch from the settings of the repo.

And finally, run this command to delete the master branch
`git push origin --delete master`

Thanks a lot.

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/121564
