### ISSUE TITLE
Error building flutter web --no-sound-null-safety

### ISSUE THREAD

**Issue by diegoflassa** [flutter/flutter#71428]
## Steps to Reproduce

Sorry  to bother. I know realize that it was a faulty HD, with corrupted files.

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
I'm building my web app, with flutter --non-sound-null-safety param, and i'm getting the errors below

**Expected results:** 
The app being build, or an significant error message

**Actual results:** 

The error below:

call flutter build web --no-sound-null-safety
Running "flutter pub get" in theheroesbook...                       7.9s
Target dart2js failed: Exception:
../../../SDKs/flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/bitmap_canvas.dart:615:7:
Warning: Operand of null-aware operation '!' has type 'CanvasRenderingContext2D' which excludes null.
 - 'CanvasRenderingContext2D' is from 'dart:html'.
      ctx!.fillText(line.displayText!, x, y);
      ^
../../../SDKs/flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/bitmap_canvas.dart:630:9:
Warning: Operand of null-aware operation '!' has type 'CanvasRenderingContext2D' which excludes null.
 - 'CanvasRenderingContext2D' is from 'dart:html'.
        ctx!.fillText(char, x, y);
        ^
../../../SDKs/flutter/packages/flutter/lib/src/widgets/basic.dart:5750:14:
Error: The method 'debugGetOpenHandleStackTraces' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
      image?.debugGetOpenHandleStackTraces()?.isNotEmpty ?? true,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/widgets/basic.dart:5755:21:
Error: The method 'clone' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
      image: image?.clone(),
                    ^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/widgets/basic.dart:5777:14:
Error: The method 'debugGetOpenHandleStackTraces' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
      image?.debugGetOpenHandleStackTraces()?.isNotEmpty ?? true,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/widgets/basic.dart:5782:24:
Error: The method 'clone' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
      ..image = image?.clone()
                       ^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/rendering/image.dart:93:50:
Error: The method 'isCloneOf' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
    if (value != null && _image != null && value.isCloneOf(_image!)) {
                                                 ^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/decoration_image.dart:440:11:
Error: The method 'debugGetOpenHandleStackTraces' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
    image.debugGetOpenHandleStackTraces()?.isNotEmpty ?? true,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/image_stream.dart:51:20:
Error: The method 'clone' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
      image: image.clone(),
                   ^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/image_stream.dart:89:24:
Error: The method 'isCloneOf' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
    return other.image.isCloneOf(image)
                       ^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/image_stream.dart:120:19:
Error: The method 'debugGetOpenHandleStackTraces' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
    assert((image.debugGetOpenHandleStackTraces()?.length ?? 1) > 0);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/image_stream.dart:877:34:
Error: The method 'clone' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
        image: _nextFrame!.image.clone(),
                                 ^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/painting/image_stream.dart:932:34:
Error: The method 'clone' isn't defined for the class 'Image'.
 - 'Image' is from 'dart:ui'.
        image: _nextFrame!.image.clone(),
                                 ^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/semantics/semantics.dart:3654:47:
Error: Getter not found: 'isSlider'.
  bool get isSlider => _hasFlag(SemanticsFlag.isSlider);
                                              ^^^^^^^^
../../../SDKs/flutter/packages/flutter/lib/src/semantics/semantics.dart:3656:28:
Error: Getter not found: 'isSlider'.
    _setFlag(SemanticsFlag.isSlider, value);
                           ^^^^^^^^
Error: Compilation failed.

Compiling lib\main.dart for the Web...                             80.5s
Exception: Failed to compile application for the Web.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale
    en-US)
    • Flutter version 1.24.0-10.2.pre at d:\Users\Diego\Programming\SDKs\flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Users\Diego\Programming\SDKs\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Users\Diego\Programming\SDKs\android-sdk
    • ANDROID_SDK_ROOT = D:\Users\Diego\Programming\SDKs\android-sdk
    • Java binary at: C:\Program Files\Java\jdk-11.0.9\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Diego\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\202.8194.7
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\Diego\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • MotoG3 (mobile)  • 0022539160 • android-arm    • Android 9 (API 28)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.61

! Doctor found issues in 1 category.
```

</details>

**Comment by jonahwilliams** [comment]
You have not included any steps on how to reproduce the problem

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
