### ISSUE TITLE
Default tooltip style is not legible on desktop and web builds with device pixel ratio 1.0

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#71429]
## None legible default tooltips on desktop and web

The new default tooltip theme now defaults to a style that is **not legible on desktop and web builds** that have device pixel ratio 1.0. The new style also broke past default desktop and web style. The breaking change and none legible tooltip style was introduced when the new Material desktop tooltip design was implemented in Flutter.

**Observations**
* Is the change according to new Material design for tooltips? **[YES]**
* Did the change break past default tooltip style on desktop and web? **[YES]**
* Does the change work visually (is it easy to read?) on desktops with device pixel ratio 1.0? **[NO]**
* Does the change work visually (is it easy to read?) in Chrome browser on Windows platform? **[NO]**

Below is a size comparison with samples of tooltips on Windows platform, both desktop builds and Web builds on windows. The **poor readability of the default font size 10dp is clearly demonstrated below**.

> Note: All images below need to be clicked on in Web GitHub to open the image at native pixel size. To get a sense of the look on a standard desktop, the desktop used for viewing the images should also use device pixel ratio 1.0.

![image](https://user-images.githubusercontent.com/39990307/100095256-e2b33480-2e62-11eb-8c00-eace5caf506b.png)

The above composite example was generated by running this simple tooltip size simulator 
https://gist.github.com/rydmike/82d2817761d52aa2c1eb47d0edf4bb5f

Using different builds and combining them into one PNG file and adding a few screenshot samples of Windows platform native tooltips to it as well for size and legibility comparison. I call the above sample code a "tooltip" simulator, since it is not using the actual Tooltip widget, but instead just the style the current tooltip uses. The used style was copied from the Tooltip widget on Flutter Channel dev, 1.24.0-10.2.pre.

In the above composite screenshot example it is shown that the current **Material default size of 10dp**, is **not very clear, nor easy to read** on Windows, not with any of the presented build types and use cases. The used font size and resulting default font type on Windows is too small for Flutter to be able to render the tooltip text clearly at device pixel ratio 1.0.

The above example also at the same time show the effect of what I suspect is related to issue https://github.com/flutter/flutter/issues/67034.

## Summary of Findings

On Windows, when using an external monitor the most common device pixel ratio is 1.0, often on a 1920x1080 (full HD) monitor. Going forward with both Flutter Web apps and Desktop apps on Windows Platform, it is both relevant and convenient if the Material design would consider **using a default dp size for tooltips that produces clear and legible tooltips at device pixel ratio 1.0.** 

Fixing the the slight extra blurriness that font rendering in Flutter currently suffers from (https://github.com/flutter/flutter/issues/67034) will still not improve the situation to the extent that font size 10dp and the default platform font used in the tooltips, would become clear enough at device pixel ratio 1.0.

**This legibility issue also applies to Linux and MacOS platforms when device pixel ratio 1.0 is used.**

I also got a report that the 10dp tooltip text has accessibility score 0 and the 10dp with lost pixels, via white text on semi transparent background has accessibility score -1.

**For the tooltips to be legible on a screen with device pixel ratio 1.0, a minimum of 12dp is required.**

Users can of course change the tooltip theme into something more legible themselves in their applications. I already did so for my applications. However, when I noticed this change and legibility issue, it just seemed a bit  **negligent, to leave the default theme for Flutter tooltips in a state that is no longer legible** on the majority of desktops in the world and browsers on them. 
That is why I thought it might be helpful and useful to bring up this minor design issue. 

----

> NOTE: This issue was reported earlier with another topic. Based on @HansMuller recommendation here https://github.com/flutter/flutter/issues/71052#issuecomment-733108486, it is opened as a new issue with focus on the new style not being legible. cc: @mariamhas @timsneath  

----

## Bitmaps sources for the composite comparison image

The source of the used bitmaps in the above composite image, were taken from the images below. The screenshots below also include dark mode examples for comparison.

### Windows Desktop Build

![image](https://user-images.githubusercontent.com/39990307/100096099-35d9b700-2e64-11eb-89f8-0690e999dcdb.png)

![image](https://user-images.githubusercontent.com/39990307/100096108-3a9e6b00-2e64-11eb-8b4c-c6fa4a3746d2.png)

### DomCanvas Web Build running on Windows in Chrome

![image](https://user-images.githubusercontent.com/39990307/100096245-6de0fa00-2e64-11eb-8e80-4afe7b137dfd.png)

![image](https://user-images.githubusercontent.com/39990307/100096256-71748100-2e64-11eb-8419-78ddc82097c2.png)

### CanvasKIT Web Build running on Windows in Chrome

![image](https://user-images.githubusercontent.com/39990307/100096315-8224f700-2e64-11eb-8681-eebc18fd8acf.png)

![image](https://user-images.githubusercontent.com/39990307/100096326-86511480-2e64-11eb-9d0f-10ddd96fa266.png)

### CanvasKIT + CanvasText Web Build running on Windows in Chrome

![image](https://user-images.githubusercontent.com/39990307/100096519-ce703700-2e64-11eb-881d-cd825400e971.png)

![image](https://user-images.githubusercontent.com/39990307/100096536-d3cd8180-2e64-11eb-9398-3ae6b22ac342.png)

----

## Footnote: What about higher device pixel ratios?

At higher device pixel ratios than 1.0, the amount of physical screen pixels available to render the font with, increases with the device pixel ratio amount per dimension. Small fonts thus become much easier to read, even if the screen pixel density would also be very high and the physical size thus small.

If you make bitmap renders at a higher device pixel ratio, the size of the actual image increases with the device pixel ratio, at the same time you can also see the impact the added pixels has in the font renders clearly.

Below are some screen shots of Desktop builds at device pixel ration 1.5, 1.75 and 2.0.

These are factors that may sometimes be in use on Windows laptops or hybrid laptop/tablet devices with hires screen and some times on external monitors when using e.g. a physically small 4k monitor where text size at device pixel ratio 1.0 becomes very small. The user then "zooms" the desktop with a factor of 150%, 175% or 200% (or similar) to make the text larger, this creates a "simulated" higher device pixel ratio also on desktops. Using zoming on a Windows desktop is corectly detected by Flutter and reported via `MediaQuery.of(context).devicePixelRatio`.

### Desktop zoomed 150% (Device pixel ratio 1.5)

![image](https://user-images.githubusercontent.com/39990307/100099613-5b68bf80-2e68-11eb-974e-403634dc0c4f.png)

![image](https://user-images.githubusercontent.com/39990307/100099623-60c60a00-2e68-11eb-9f76-0d3eab23632b.png)

### Desktop zoomed 175% (Device pixel ratio 1.75)

![image](https://user-images.githubusercontent.com/39990307/100099708-805d3280-2e68-11eb-8276-abbe87906f5e.png)

![image](https://user-images.githubusercontent.com/39990307/100099723-83f0b980-2e68-11eb-884a-e26021dabd21.png)

### Desktop zoomed 200% (Device pixel ratio 2.0)

![image](https://user-images.githubusercontent.com/39990307/100099759-8c48f480-2e68-11eb-8d22-4feecac886bf.png)

![image](https://user-images.githubusercontent.com/39990307/100099833-9bc83d80-2e68-11eb-8d67-30d4de407acd.png)

----

<details>
  <summary>Flutter doctor</summary>
```
flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Users\mryds\fvm\versions\beta
    • Framework revision 022b333a08 (4 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mryds\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\mryds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (5 available)
    • Nexus 7 (mobile)                 • 0a99f5e8      • android-arm    • Android 6.0.1 (API 23)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Web Server (web)                 • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 87.0.664.41

• No issues found!
```
</details>

**Comment by HansMuller** [comment]
Internal Google issue about this topic: b/174500564

**Comment by creativecreatorormaybenot** [comment]
I like the smaller tooltip sizes.

Everything in Flutter is way too big by default on web and desktop at the moment.

Would rather see a comparison to other web apps.

**Comment by creativecreatorormaybenot** [comment]
I like the smaller tooltip sizes.  
Everything in Flutter is way too big by default on web and desktop at the moment and tooltips were too before the change.

---

Also, how did you determine it is not legible?  
Would rather see a comparison to other web apps.

**Comment by rydmike** [comment]
@creativecreatorormaybenot Yes I also think that 14dp that is used as default size for tooltips on devices, is indeed a bit too large on desktop designs. This was used as default on desktop and web too prior to the new standard that made it 10dp. 

However, the used 10dp makes the text none legible if the device pixel ratio is 1.0, since there is just not enough pixels to render it sharp enough. If the device pixel ratios is 1.5 or higher the situation is improved even if the font is still very small, but at least it is the legible. However, the majority of desktops when using an external display uses device pixel ratio 1.0 so therefore it would be nice for newcomer if the text was legible by default without resorting to customizing the theme.

Personally I think 12dp could be suitable balance between size and readability.

Here is comparison of Flutter's new default Web desktop tooltip, compared to a very common Web design, Bootstrap:

![image](https://user-images.githubusercontent.com/39990307/100671374-131a3780-3369-11eb-904d-a62fac9c825b.png)

**Comment by rydmike** [comment]
In this image I also added the 12dp sized tooltips to the comparison (below the buttons in same order):

![image](https://user-images.githubusercontent.com/39990307/100672437-9be5a300-336a-11eb-9b60-6dbc68804d60.png)

(Click on the image to open it with a pixel accurate view)
Even they are still smaller than default Bootstrap style, but imo large and legible enough. Especially if Flutter also one day solves issue https://github.com/flutter/flutter/issues/67034

**Comment by timsneath** [comment]
My sense is that the issue is in _part_ about the quality of rendering at small font sizes. While I'd support slightly larger sizing (and tighter padding), it's worth noting that ([on Windows in particular](https://docs.microsoft.com/en-us/windows/win32/controls/images/tt-desktop.png)) tooltips can contain a sentence or two of information, so I'm cautious about having these be too large. 

For example:
![image](https://user-images.githubusercontent.com/2319867/100673638-9f503e80-3318-11eb-8917-f2d72a81330f.png)
This tooltip is about 150x40px. Nudging our default to 12dp seems reasonable, but 14dp would be challenging.

**Comment by rydmike** [comment]
@timsneath 
I agree and also think that 14dp font size would be excessive, both on web-desktop and native desktop apps. I also totally agree that there is no need for the large padding that is still used on devices and that was used on desktop/web before the new Material desktop tooltip guide.

However, the 10dp font size is just a bit too small, even if the current fuzziness that Flutter text rendering suffers from is solved, it will still not be possible to render 10dp font size with crisp sharpness if the device pixel ratio is 1.0, if it is 1.5, then sure no problem.

Just for demonstration purposes, here is how that last tooltip you added looks when compared to Flutter's current Windows desktop renders. Web renders are fairly similar as shown earlier above so I did not add them to this desktop comparison, their sizes are equivalent, but yes there are pixel differences.

This screen shot composite is just for comparing the sizes at current 10dp and then imo the best matching size candidate 12dp as well as 14dp. I used the same tooltip text as in the Windows example you added, since it makes the comparison easier and more obvious and added the last tooltip from your Windows native tooltip example so they can be compared side by side.

![image](https://user-images.githubusercontent.com/39990307/100755197-9765cc80-33f4-11eb-97ff-be1418b25c27.png)

The Flutter Desktop tooltips where taken from this Flutter rendered Windows desktop screenshot:
![image](https://user-images.githubusercontent.com/39990307/100750312-844ffe00-33ee-11eb-80fd-a34e09e53959.png)

And the above screen was generated with this playground: https://gist.github.com/rydmike/483bee488423664b80c6b755c9b88a3b

The text at the bottom is wrapped with an actual Tooltip with the same message string, just to show that an actual tooltip shown from it, is identical to the simulated 10dp example shown above.

----

Another minor issues with the default Flutter Material tooltip theme is that it does not support multiline tooltips very well out of the box. 

This is due to how the height is constrained to min 24dp by the default theme, but it has no vertical padding beyond that. As soon as the height is **higher than 24 dp the default tooltips have no vertical padding at all**. 

This does not necessarily look so good either, there should always be few dp vertical padding, not a lot, but a tiny bit at least. Like there is on your provided native Windows tooltip as well, which if you compare it to the Flutter multiline tooltips look a bit better due to this slight vertical padding. The custom themed tooltip on the right side of your provided Windows native tooltip show a Flutter tooltip at the same comparable 12dp font size with a slight vertical padding, just to make the text and style more comparable to the Windows native tooltip, I also made it with dark txt on light background

**Comment by willlarche** [comment]
Confirmed that design is comfortable with a larger default text size for this case. What do you think would be the best value? 

For multiline, please create a separate issue. 

Also, fantastic work debugging this @rydmike ! Thank you!

**Comment by rydmike** [comment]
Thanks @willlarche for confirming this. 👍🏻 

> What do you think would be the best value?

Based on above provided renders, I think **12dp** on desktops and web (that use device pixel ratio 1.0) is a nice compromise between being compact and still legible. 

- On Web it results in a size that is still slightly smaller than Bootstrap's default tooltips, a style many are used to in Web apps.
- On Windows desktop the size is pretty much the same size as native desktop tooltips. Yes there is a minor difference in both size and clarity on desktop (native using ClearType sub-pixel rendering, is as expected sharper), but those are caused by the differences in used font rendering engines.

> For multiline, please create a separate issue.

Sure, I can do that. Might be good to record it as a design reminder to consider at a later stage for desktop design and usage.

For Material design I don't think it is so important either, since the recommendation is to keep tooltips so short that they fit on one line. Thus making multiline tooltips not inline with that, hence I think user's (even I *smirk*) are fine with an explanation that default Material tooltips are designed to work/look well for one line tooltips and if you want better looking multiline ones, please make your own tooltip theme with some bottom padding, like I did in my previous comment. All you need is about 2dp padding on the bottom so that the text does not touch the bottom edge, which as shown above does not look so pretty when it does.

---

For the size I'm pleased that an increase is considered for the default design. Not because I needed it. I'm happy to design my own theme for tooltips when so needed. Theming tooltips like most things in Flutter works really well.

I'm pleased because I think a default themed tooltip that is not legible out of the box for Web and Desktop, could potentially frustrate newcomers to the framework. Additionally the current too small and fuzzy desktop/web tooltips, look a bit out of place compared to the otherwise nice and balanced out of the box default designs.

**Comment by creativecreatorormaybenot** [comment]
@rydmike I have something nice to compare against: **Twitter** now displays tooltips on hover of the follower count :)

You could check how that compares to your previous findings.

**Comment by rydmike** [comment]
@creativecreatorormaybenot 

It appears to be 12dp, well based on the visual size when a screenshot of it is composited into the above size comparisons.

Below I inserted a screenshot of the Twitter tooltip into the Flutter renders of 9, 10 (current Flutter default), 11, 12, and 13 dp sized tooltip renders. It visually matches the 12dp size.

![image](https://user-images.githubusercontent.com/39990307/101421252-981ec700-38fc-11eb-902c-92aa1a908370.png)


(Another question is of course why Twitter shows the following / followers count as tooltip when it is already shown as number in the label that the tooltip comes from, their use case makes no sense 😄 )

**Comment by rydmike** [comment]
@creativecreatorormaybenot Correction, I think it might even be 14dp in Twitter after all. I will make better comparison, with the same letters (numbers) in the Flutter renders as in the Twitter tooltip. I will also double check my Twitter browser scaling window to make sure it is at 100%, not 90% like I think it was when I made the screen shot from Twitter above. In my haste I did not verify it like I normally do for browser screenshots. so I will be back later with a better comparison.

**Comment by rydmike** [comment]
@creativecreatorormaybenot 

Here is a visually better and easier size comparison of the Twitter tooltip you mentioned and different sizes of Flutter tooltips with the same content, but at sizes 9, 10, 11, 12, 13, and 14dp (with 10dp being the current Flutter default). It should make the comparison visually easier when they have the same content.

Quite an interesting comparison, thanks for pointing out this case example as well.

Looks like my initial assessment was close enough, visually the font size in Twitter's tooltips look close to what we get with 12dp font size in Flutter, perhaps even 13dp? But definitely not 10dp or 11dp. 

This applies to both Windows Desktop builds and Web CanvasKit builds rendered by Chrome on Windows platform, browser zoomed to 100%. All screens shots rendered at standard (well most common anyway) desktop device pixel ratio of 1.0.

I'm just comparing the font size here, the paddings are different of course. As one line tooltips, both are fine imo. It is only the multi-line tooltips in Flutter that looks a bit wonky regarding bottom padding when letters like **j p** and **q** touch/reach the bottom edge of the tooltip.


### Twitter Web Tooltip compared with Flutter Windows Desktop build tooltips sizes

![image](https://user-images.githubusercontent.com/39990307/101427760-28aed480-3908-11eb-9ae7-6ff6dd72f392.png)

### Twitter Web Tooltip compared with Flutter Web CanvasKit build tooltip sizes on Chrome on Windows platform

![image](https://user-images.githubusercontent.com/39990307/101428060-aecb1b00-3908-11eb-8ab8-e1c595f84cd5.png)

---

The Twitter tooltip size example was taken from this screenshot:

![image](https://user-images.githubusercontent.com/39990307/101428125-cd311680-3908-11eb-9b6a-294ca13f39fb.png)
