### ISSUE TITLE
Custom Embedder devtools api

### ISSUE THREAD

**Issue by ConnorRigby** [flutter/flutter#71420]
## Use case

my company builds an embedded linux device, we are looking to use Flutter with a custom embedder (similar to [Flutter-PI](https://github.com/ardera/flutter-pi)). Currently everything boots and runs as expected. the next trick will be get all the nice dev tools working. 

## Proposal

After a few minutes of skimming code, I found that it looks like most of the device discovery code happens in [device.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/device.dart) and related code. I propose that a new "device" be added that may allow a user to custom define the `device` implementation. i'm not exactly certain how that would look in practice, but i'd be happy to discuss if this is something the team is interested in.

**Comment by jonahwilliams** [comment]
What do you think about something like https://github.com/flutter/flutter/issues/65067 ?

**Comment by jonahwilliams** [comment]
Its not currently being worked on, because I've not heard from anyone that would be interested in prototyping it

**Comment by ConnorRigby** [comment]
I actually ended up partially solving my problem by using a similar solution to the `go-flutter` guys: https://github.com/go-flutter-desktop/go-flutter/issues/129#issuecomment-513590141
This is close enough for me to move forward right now, but i i've skimmed #65067 and it looks like there's some useful stuff in there as well. I will move further comments to that issue.
