### ISSUE TITLE
Skia roll causes minor changes in the way we render things

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#71436]
https://github.com/flutter/engine/pull/22754 is the candidate roll. I think its the https://skia.googlesource.com/skia.git/+/420a9ba7b5e99a3a6d539190cbff4198d1ee9e7e that might have started this.

## In the case of Flutter SVG:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8862180433793644048/+/steps/prepare_environment/0/steps/Customer_testing/0/steps/customer_testing/0/stdout is the failure. Patched in https://github.com/flutter/tests/pull/68/files.

## Also causes failures in gold

https://flutter-gold.skia.org/search?issue=71430&crs=github&corpus=flutter

**Comment by iskakaushik** [comment]
Tentative plan is:

1. Resolve all the other issues seen in: https://github.com/flutter/flutter/pull/71430
2. Land https://github.com/flutter/tests/pull/68
3. Shepherd the new roll to success.

cc: @jason-simmons , @dnfield

**Comment by zanderso** [comment]
fyi @cbracken

**Comment by Piinks** [comment]
@cbracken I think this has been resolved now that you were able to land the roll. 🎉  Ok to close this now?
