### ISSUE TITLE
[Web] : Canvas.drawVertices is not rendered correctly.

### ISSUE THREAD

**Issue by simplicialsoftware2** [flutter/flutter#71442]
I'm using the following code in a CustomPainter:

```
  @override
  void paint(Canvas canvas, Size screenSize) {
    canvas.drawVertices(
      Vertices(VertexMode.triangles, [
        Offset(10, 100),
        Offset(100, 100),
        Offset(100, 10),
      ]),
      BlendMode.srcOver,
      Paint()
        ..color = Colors.green
        ..style = PaintingStyle.fill,
    );
  }
```

On chrome (built with flutter build web) I see an unfilled triangle. I expect a filled triangle. 
On android (built with flutter build apk) I see a filled triangle as expected.

If I change the PaintingStyle to .stroke nothing changes.
On chrome I see an unfilled triangle as expected.
On android I see a filled triangle. I expect an unfilled triangle. 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.51.1)
[√] Connected device (5 available)

• No issues found!

**Comment by darshankawar** [comment]
Verified and issue replicable on latest beta.

1. With `flutter run -d chrome`:

<img width="445" alt="Screenshot 2020-12-01 at 1 24 17 PM" src="https://user-images.githubusercontent.com/67046386/100712553-ef8ed580-33d8-11eb-9045-32337fe060ea.png">

2. With `flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true`:

<img width="385" alt="Screenshot 2020-12-01 at 1 26 28 PM" src="https://user-images.githubusercontent.com/67046386/100712600-03d2d280-33d9-11eb-9aec-426e018c9c9e.png">

3. Android:

<img width="210" alt="Screenshot 2020-12-01 at 1 25 19 PM" src="https://user-images.githubusercontent.com/67046386/100712622-0c2b0d80-33d9-11eb-9008-1738b944b580.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.67

• No issues found!


```

</details>

<details>
<summary>complete code sample</summary>

```

import 'package:flutter/material.dart';
import 'dart:ui';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: CustomPaint(
          painter: ShapePainter()
        )
        ),
      );
  //  );
  }
}

class ShapePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size screenSize) {
    canvas.drawVertices(
      Vertices(VertexMode.triangles, [
        Offset(10, 100),
        Offset(100, 100),
        Offset(100, 10),
      ]),
      BlendMode.srcOver,
      Paint()
        ..color = Colors.green
        ..style = PaintingStyle.fill,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
   return true;
  }
}



```

</details>

**Comment by simplicialsoftware2** [comment]
Depending on what the expected behavior is when using Canvas.drawVertices with a PaintingStyle of stroke,  this issue may also effect non web versions of flutter (or it may be a "different" issue). When using .stroke I expect to see only the edges of the triangle, but I still see a filled triangle on an Android emulator. I have not tried this on the stable release of flutter.
