### ISSUE TITLE
Divider cannot set dashed lines

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#71453]
Divider cannot set dashed lines

**Comment by jeanluc243** [comment]
Default flutter does not allow this but there is a great package that does a great job. 

🌟 [https://pub.dev/packages/fdottedline](https://pub.dev/packages/fdottedline)

**Comment by darshankawar** [comment]
@gionchat Please elaborate on your issue. Which platform are you describing this issue for ? Can you provide `flutter doctor -v` and minimal reproducible code sample along with actual and expected behavior ?

**Comment by hello-addweb** [comment]
Without plugin you can do this like below : 

```
class DashedLinePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    double dashWidth = 9, dashSpace = 5, startX = 0;
    final paint = Paint()
      ..color = Colors.grey
      ..strokeWidth = 1;
    while (startX < size.width) {
      canvas.drawLine(Offset(startX, 0), Offset(startX + dashWidth, 0), paint);
      startX += dashWidth + dashSpace;
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```
