### ISSUE TITLE
No hot-reload with 'hello_service'-style app

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#7145]
When starting `flutter run` on `hello_service` example (at least for Android), it starts `gradlew` that does not have hot reload feature. However in [documentation](https://github.com/flutter/flutter/wiki/Hot-Reload) stated that it should by default.

**Comment by eseidelGoogle** [comment]
In order to support hot reload in hello_services we'll need to establish the observatory connection after the fact.  FYI @johnmccutchan 

Also note that we may have to solve some flavor of this bug as part of integrating hello_services into the default workflow: https://github.com/flutter/flutter/issues/4796

**Comment by jakobr-google** [comment]
Something must've changed in the meantime. Hot reload works fine for me on hello_services (running on a Nexus 5X). Gradle is only used to build the initial APK. The workflow for running the app should be the same for both build types.

Please reopen if you can still reproduce this.

**Comment by johnmccutchan** [comment]
I believe Dart's hot reload should work fine here. 

I wonder if the bug is asking for Android's 'InstantRun' to also work for Java code?

**Comment by jakobr-google** [comment]
Yep, Dart's hot reload works fine. The issue description links to Flutter's Hot Reload wiki page, so I assumed that's what we were talking about here.

I'll be looking at supporting Android Instant Run for the Java code as part of the gradle work.

**Comment by eseidelGoogle** [comment]
@olostan is active in our gitter, so he can comment as to what he meant.  But Hot Reload didn't work in hello_services at one point, so presumably that is what he ran into.  Closing.  Please feel free to re-open if I've misunderstood.

**Comment by olostan** [comment]
@eseidelGoogle currently I am on vacation so quite far from computer and can't check, but can confirm that when I was working on project that used hello_service model, there were no option to use hot reload in the way how it was stated in documentation. Anyway I am glad that it works right now! I'll check again and post here if there would be any trouble.
