### ISSUE TITLE
.

### ISSUE THREAD

**Issue by x-abgth** [flutter/flutter#71454]
.

**Comment by YazeedAlKhalaf** [comment]
The best thing to do is to recreate the project by running `flutter create .` in the directory of the project. make sure that it is the same organization name and app name so it does not create a duplicate.

Make sure you know what changes you made to the android or iOS folder. It seems you made your project a very long time ago.

If you need help just reply to this message here.

**Comment by darshankawar** [comment]
@x-abgth 
Along with above suggestion, you may look at [this](https://github.com/flutter/flutter/issues/44906) issue and see if it works for you.
