### ISSUE TITLE
Cannot run flutter app on Android!

### ISSUE THREAD

**Issue by dungnguyentri3110** [flutter/flutter#71463]
Hi guys! I'm writing my app and build on android. But it throw an error, although i'm not do task relate to Date Time. Please help me. Thanks you! 
![Screen Shot 2020-12-01 at 2 26 55 PM](https://user-images.githubusercontent.com/54011066/100709791-48fb0280-33e1-11eb-967f-184117f546ae.png)

**Comment by hamdikahloun** [comment]
Hi @dungnguyentri3110 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal complete reproducible code sample?

Thank you

**Comment by dungnguyentri3110** [comment]
> Hi @dungnguyentri3110
> 
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal complete reproducible code sample?
> 
> Thank you

# Here this is my flutter doctor -v
![Screen Shot 2020-12-01 at 2 51 22 PM](https://user-images.githubusercontent.com/54011066/100712044-b5c3cc00-33e4-11eb-9297-c54818caff46.png)

# This is my flutter run --verbose
[  +74 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] executing: [/Volumes/transcend/flutterSDK/flutter/] git tag --points-at a7f5fd5360007518644597c60a1f2169eacccc2b
[ +164 ms] Exit code 0 from: git tag --points-at a7f5fd5360007518644597c60a1f2169eacccc2b
[   +4 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git describe --match *.*.* --long --tags a7f5fd5360007518644597c60a1f2169eacccc2b
[  +63 ms] Exit code 0 from: git describe --match *.*.* --long --tags a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] 1.24.0-7.0.pre-375-ga7f5fd5360
[  +52 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Volumes/transcend/flutterSDK/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2
[        ] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] executing: /Users/ntrdung/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +792 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.0.1
           Build version 12A7300
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +3 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +47 ms] List of devices attached
           c7b82e339905           device usb:339935232X product:vince model:Redmi_5_Plus device:vince transport_id:1
[ +120 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.tvOS-14-0" : [

                        ],
                        "com.apple.CoreSimulator.SimRuntime.iOS-14-0" : [
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/FC616E27-3AFD-40F2-AE48-EBAA31CD5E34\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/FC616E27-3AFD-40F2-AE48-EBAA31CD5E34",
                            "udid" : "FC616E27-3AFD-40F2-AE48-EBAA31CD5E34",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-",
                            "state" : "Shutdown",
                            "name" : "iPad Pro (9.7-inch)"
                          }
                        ],
                        "com.apple.CoreSimulator.SimRuntime.iOS-12-0" : [
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/913DB7EF-BBEE-4342-81AB-19C197831DFC\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/913DB7EF-BBEE-4342-81AB-19C197831DFC",
                            "udid" : "913DB7EF-BBEE-4342-81AB-19C197831DFC",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s",
                            "state" : "Booted",
                            "name" : "iPhone 6s"
                          },
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/5B8E9B04-9C26-47AE-BB6A-844C5C6A8F95\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/5B8E9B04-9C26-47AE-BB6A-844C5C6A8F95",
                            "udid" : "5B8E9B04-9C26-47AE-BB6A-844C5C6A8F95",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus",
                            "state" : "Shutdown",
                            "name" : "iPhone 6s Plus"
                          },
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/C214F681-B4BC-4A79-A325-B8A685D8417A\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/C214F681-B4BC-4A79-A325-B8A685D8417A",
                            "udid" : "C214F681-B4BC-4A79-A325-B8A685D8417A",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-X",
                            "state" : "Shutdown",
                            "name" : "iPhone X"
                          }
                        ],
                        "com.apple.CoreSimulator.SimRuntime.watchOS-7-0" : [
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/6FE63D84-B80E-4F7C-B88B-87449AA8A26B\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/6FE63D84-B80E-4F7C-B88B-87449AA8A26B",
                            "udid" : "6FE63D84-B80E-4F7C-B88B-87449AA8A26B",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm",
                            "state" : "Shutdown",
                            "name" : "Apple Watch Series 5 - 40mm"
                          },
                          {
                            "dataPath" : "\/Users\/ntrdung\/Library\/Developer\/CoreSimulator\/Devices\/8BDBB7DD-0E17-4FF9-8C88-5E8D99B5FD1D\/data",
                            "logPath" : "\/Users\/ntrdung\/Library\/Logs\/CoreSimulator\/8BDBB7DD-0E17-4FF9-8C88-5E8D99B5FD1D",
                            "udid" : "8BDBB7DD-0E17-4FF9-8C88-5E8D99B5FD1D",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm",
                            "state" : "Shutdown",
                            "name" : "Apple Watch Series 5 - 44mm"
                          }
                        ]
                      }
                    }
[+3722 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.0 (18A372)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "FC616E27-3AFD-40F2-AE48-EBAA31CD5E34",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-9point7-a1674-b9b7ba",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "12.0 (16A366)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,6",
                        "identifier" : "C214F681-B4BC-4A79-A325-B8A685D8417A",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-x-1",
                        "modelName" : "iPhone X",
                        "name" : "iPhone X"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "12.0 (16A366)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone8,2",
                        "identifier" : "5B8E9B04-9C26-47AE-BB6A-844C5C6A8F95",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-6s-plus-b9b7ba",
                        "modelName" : "iPhone 6s Plus",
                        "name" : "iPhone 6s Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,4",
                        "identifier" : "8BDBB7DD-0E17-4FF9-8C88-5E8D99B5FD1D",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series5-1",
                        "modelName" : "Apple Watch Series 5 - 44mm",
                        "name" : "Apple Watch Series 5 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,3",
                        "identifier" : "6FE63D84-B80E-4F7C-B88B-87449AA8A26B",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series5-1",
                        "modelName" : "Apple Watch Series 5 - 40mm",
                        "name" : "Apple Watch Series 5 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "12.0 (16A366)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone8,1",
                        "identifier" : "913DB7EF-BBEE-4342-81AB-19C197831DFC",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-6s-b9b7ba",
                        "modelName" : "iPhone 6s",
                        "name" : "iPhone 6s"
                      }
                    ]
[   +5 ms] /Users/ntrdung/Library/Android/sdk/platform-tools/adb -s c7b82e339905 shell getprop
[  +49 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] Multiple devices found:
[   +3 ms] ro.hardware = qcom
[   +5 ms] Redmi 5 Plus (mobile) • c7b82e339905                         • android-arm64 • Android 7.1.2 (API 25)
[        ] iPhone 6s (mobile)    • 913DB7EF-BBEE-4342-81AB-19C197831DFC • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)
[   +1 ms] [0]: Redmi 5 Plus (c7b82e339905)
[        ] [1]: iPhone 6s (913DB7EF-BBEE-4342-81AB-19C197831DFC)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+95327 ms] 0
[  +22 ms] Skipping pub get: version match.
[ +147 ms] Generating /Volumes/TRANSCEND/Project/yuka_flutter_app/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +79 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +3 ms] Launching lib/main.dart on Redmi 5 Plus in debug mode...
[   +6 ms] /Volumes/transcend/flutterSDK/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Volumes/transcend/flutterSDK/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Volumes/transcend/flutterSDK/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill /var/folders/gn/gjb0bw952xzgctbkv6j21gkw0000gp/T/flutter_tools.5Rg61A/flutter_tool.RlWPit/app.dill --packages
/Volumes/TRANSCEND/Project/yuka_flutter_app/foo/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/01094840f26094a3fe371d8be6b9cb48.cache.dill.track.dill --flutter-widget-cache
[  +26 ms] executing: /Users/ntrdung/Library/Android/sdk/platform-tools/adb -s c7b82e339905 shell -x logcat -v time -t 1
[  +14 ms] <- compile package:foo/main.dart
[ +105 ms] --------- beginning of main
                    12-01 14:53:34.824 I/PowerCenterProvider( 3530): call METHOD_GET_POWER_SUPPLY_INFO, quick_charge:false
[  +11 ms] executing: /Users/ntrdung/Library/Android/sdk/platform-tools/adb version
[   +6 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /Users/ntrdung/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/ntrdung/Library/Android/sdk/platform-tools/adb start-server
[   +6 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Volumes/TRANSCEND/Project/yuka_flutter_app/foo/android/gradlew.
[        ] /Volumes/TRANSCEND/Project/yuka_flutter_app/foo/android/gradlew mode: 33261 rwxr-xr-x.
[  +99 ms] executing: [/Volumes/TRANSCEND/Project/yuka_flutter_app/foo/android/] /Volumes/TRANSCEND/Project/yuka_flutter_app/foo/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/Volumes/TRANSCEND/Project/yuka_flutter_app/foo/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3852 ms] > Task :app:compileFlutterBuildDebug
[        ] [ +108 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] [        ] executing: [/Volumes/transcend/flutterSDK/flutter/] git tag --points-at a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] [ +143 ms] Exit code 0 from: git tag --points-at a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] [   +1 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git describe --match *.*.* --long --tags a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] [  +65 ms] Exit code 0 from: git describe --match *.*.* --long --tags a7f5fd5360007518644597c60a1f2169eacccc2b
[        ] [        ] 1.24.0-7.0.pre-375-ga7f5fd5360
[        ] [  +48 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/Volumes/transcend/flutterSDK/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +48 ms] executing: [/Volumes/transcend/flutterSDK/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +64 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +81 ms] Initializing file store
[   +1 ms] [   +9 ms] Done initializing file store
[        ] [  +40 ms] Skipping target: gen_localizations
[        ] [ +458 ms] Skipping target: kernel_snapshot
[ +376 ms] [ +350 ms] Skipping target: debug_android_application
[        ] [        ] Persisting file store
[        ] [   +7 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [  +12 ms] "flutter assemble" took 1,051ms.
[        ] [   +4 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +3 ms] exiting with code 0
[ +103 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +294 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +175 ms] > Task :app:compileDebugJavaWithJavac FAILED
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[        ] 18 actionable tasks: 5 executed, 13 up-to-date
[ +357 ms] Running Gradle task 'assembleDebug'... (completed in 5.3s)
[+3804 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 109,864ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1119:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:974:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:264:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +194 ms] ensureAnalyticsSent: 178ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1

# This is my pubspec.yaml
![Screen Shot 2020-12-01 at 2 56 22 PM](https://user-images.githubusercontent.com/54011066/100712533-7944a000-33e5-11eb-9f64-122c0ab4f476.png)

**Comment by darshankawar** [comment]
@dungnguyentri3110 
See [this](https://github.com/flutter/flutter/issues/69643) similar issue and corresponding issue [comment](https://github.com/flutter/flutter/issues/69643#issuecomment-723171794) that resolved the issue. Try that for yourself and see if it works for you.

**Comment by dungnguyentri3110** [comment]
> comment

Thank you. I'm using Java 9 but it still throw that error
![Screen Shot 2020-12-02 at 10 10 41 AM](https://user-images.githubusercontent.com/54011066/100823397-b9a82a80-3486-11eb-8639-655a1c89b8ab.png)
Let me try another version.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
