### ISSUE TITLE
/Users/mac/desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/ios/Classes/FLTSharedPreferencesP     lugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found     #import <Flutter/Flutter.h>

### ISSUE THREAD

**Issue by darshanna** [flutter/flutter#71469]

**Comment by darshanna** [comment]
In file included from
    /Users/mac/desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/ios/Classes/FLTSharedPreferencesP
    lugin.m:5:
    /Users/mac/desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/ios/Classes/FLTSharedPreferencesP
    lugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by TahaTesser** [comment]
Hi @darshanna 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/70895

Can you please upgrade to the latest  `master` and try again, it should be fixed
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`


Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
