### ISSUE TITLE
Probable there`s a  expression mistake in date_picker_widget

### ISSUE THREAD

**Issue by ReinHarDtt** [flutter/flutter#71466]
## Steps to Reproduce

version: 1.22.2

Step: Scroll by one unit of month picker, such as scroll month 11 to month 10

**Expected results:** 

**Actual results:** 
The following assertion was thrown while handling a gesture:
**Failed assertion: boolean expression must not be null**

When the exception was thrown, this was the stack
#0      _DatePickerWidgetState._changeDateRange
package:flutter_cupertino_date_picker/…/widget/date_picker_widget.dart:289
#1      _DatePickerWidgetState._changeMonthSelection
package:flutter_cupertino_date_picker/…/widget/date_picker_widget.dart:255
#2      _DatePickerWidgetState._renderDatePickerWidget.<anonymous closure>.<anonymous closure>
package:flutter_cupertino_date_picker/…/widget/date_picker_widget.dart:191
#3      _CupertinoPickerState._handleSelectedItemChanged
package:flutter/…/cupertino/picker.dart:252
#4      _ListWheelScrollViewState.build.<anonymous closure>
package:flutter/…/widgets/list_wheel_scroll_view.dart:766
...

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @ReinHarDtt 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by ReinHarDtt** [comment]
import&nbsp;'package:flutter/material.dart';
import&nbsp;'package:flutter/rendering.dart';
import&nbsp;'package:flutter_screenutil/flutter_screenutil.dart';
import&nbsp;'package:flutter_cupertino_date_picker/flutter_cupertino_date_picker.dart';

class&nbsp;Test&nbsp;extends&nbsp;StatefulWidget&nbsp;{
&nbsp;&nbsp;Test({Key&nbsp;key})&nbsp;:&nbsp;super(key:&nbsp;key);
&nbsp;&nbsp;@override
&nbsp;&nbsp;State<StatefulWidget&gt;&nbsp;createState()&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;new&nbsp;_Test();
&nbsp;&nbsp;}
}

class&nbsp;_Test&nbsp;extends&nbsp;State<Test&gt;&nbsp;{

&nbsp;&nbsp;@override
&nbsp;&nbsp;Widget&nbsp;build(BuildContext&nbsp;context)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Container(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;child:&nbsp;DatePickerWidget(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;minDateTime:&nbsp;DateTime.parse('2020-01-01'),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;maxDateTime:&nbsp;DateTime.parse('2020-12-31'),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;initialDateTime:&nbsp;DateTime.parse('2020-06-01'),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pickerTheme:&nbsp;DateTimePickerTheme(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;itemTextStyle:&nbsp;TextStyle(fontSize:&nbsp;35.sp,&nbsp;color:&nbsp;Colors.red),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pickerHeight:&nbsp;400.0.w,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;titleHeight:&nbsp;100.w,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;itemHeight:&nbsp;100.0.w,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;onChange:&nbsp;(dateTime,&nbsp;selectedIndex)&nbsp;{},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),
&nbsp;&nbsp;&nbsp;&nbsp;);
&nbsp;&nbsp;}
}


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 下午5:47
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"Mr.J"<1368350514@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] Probable there`s a  expression mistake in date_picker_widget (#71466)





 
Hi @ReinHarDtt
 Can you please provide your flutter doctor -v and a minimal complete reproducible code sample?
 Thank you

**Comment by pedromassangocode** [comment]
Hi @ReinHarDtt 
Can you please provide a valid minimal complete reproducible code sample and your `flutter doctor -v`?
Thank you

**Comment by ReinHarDtt** [comment]
sorry, that`s third-party plugin mistake, thanks for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 晚上10:06
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"Mr.J"<1368350514@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] Probable there`s a  expression mistake in date_picker_widget (#71466)





 
Hi @ReinHarDtt
 Can you please provide a valid minimal complete reproducible code sample and your flutter doctor -v?
 Thank you
