### ISSUE TITLE
Quickly switching back in task switcher crashes

### ISSUE THREAD

**Issue by sfanxiang** [flutter/flutter#7147]
## Steps to Reproduce
Tested on Android 6.0.1.
1. Open any flutter app.
2. Tap the square button.
3. Instead of waiting for the animation to finish, tap back to the app.

## Logs
[flutter_task_switch_crash.txt](https://github.com/flutter/flutter/files/629218/flutter_task_switch_crash.txt)

**Comment by eseidelGoogle** [comment]
Can you tell us what device this is on?

The crash is due to failing to get the GL context
```
12-04 09:04:49.746 13002 13002 E flutter : [ERROR:../../flutter/shell/platform/android/android_context_gl.cc(178)] Could not create the EGL surface.
12-04 09:04:49.746 13002 13002 E flutter : [ERROR:../../flutter/shell/platform/android/android_context_gl.cc(49)] EGL Error: EGL_BAD_ALLOC (12291)
12-04 09:04:49.746 13002 13002 I flutter : [INFO:platform_view_android.cc(98)] Could not create the OpenGL Android Surface.
```

And it's likely just our error, but it also could be specific to the device.

**Comment by sfanxiang** [comment]
It was running on Moto X Style(XT1572), but the problem appears in Android Emulator too when I try to fast-switch tasks twice in a row. Logcat shows exactly the same error and this can be reproduced as long as Android version is around 6.0. On Android 7 nothing goes wrong.
