### ISSUE TITLE
Flutter Web Navigator.pushNamedAndRemoveUntil issue

### ISSUE THREAD

**Issue by SantyTaco** [flutter/flutter#71488]
I found this error using flutter web:
Another exception was thrown: Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:5098:14

`@override
  void debugDeactivated() {
    assert(() {
      assert(_dependents.isEmpty);
      return true;
    }());
    super.debugDeactivated();
  }`

It appears when the app is using Navigator.pushNamedAndRemoveUntil(context, homeRoute, (route) => false) and running in debug mode. The screen changes to red completely, in release mode the error does not appear anymore. 

flutter doctor:

[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.17763.1577], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] VS Code (version 1.51.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (3 available)

**Comment by darshankawar** [comment]
@SantyTaco 
You seem to be on older version of Flutter. Current beta version is 1.24. I suggest you upgrade to latest version and try again to see if it works.
If issue persists, please provide updated `flutter doctor -v` and complete minimal reproducible code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
