### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by jclaessens97** [flutter/flutter#71483]
I created an [issue](https://github.com/Dart-Code/Dart-Code/issues/2972) in the dart-code repository, but they redirected me here because it seems to be a flutter issue and not a dart-code issue.

Every flutter command I try to run I get the following exception:

```
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5    …
```
Inside vscode if I click on run to launch the flutter project, also get the same error as this [issue](https://github.com/flutter/flutter/issues/43063).
## Steps to Reproduce
Unclear, first time I have it, Installed 2 days ago, could use it 2 days in a row, while putting my pc to sleep inbetween, today after a whole day of working on other things in vscode, this happened. Even after a restart it keeps happening now. 

## Logs

![](https://user-images.githubusercontent.com/10177148/100672945-4cec3d80-336b-11eb-92db-9a4e9e7f3403.png)

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-BE)
    • Flutter version 1.22.4 at /Users/jclaessens/.asdf/installs/flutter/1.22.4-stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

⣽Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by TahaTesser** [comment]
Hi @jclaessens97 
Do you have any antivirus/firewall installed, please add flutter to the whitelist or disable Antivirus/Firewall and try again
Related https://github.com/flutter/flutter/issues/71006#issuecomment-732148092
Thank you

**Comment by jclaessens97** [comment]
Aha, apparently AdGuard was also the problem here. Not sure how to add it to the whitelist instead of disabling it, but I'll figure. Thanks!

**Comment by OlalKeith** [comment]
> Aha, apparently AdGuard was also the problem here. Not sure how to add it to the whitelist instead of disabling it, but I'll figure. Thanks!
> 
> Running `flutter config --no-analytics` also worked, with AdGuard enabled.

This does solve the issue. I have a MacOS Big Sur installed.

**Comment by erperejildo** [comment]
> Aha, apparently AdGuard was also the problem here. Not sure how to add it to the whitelist instead of disabling it, but I'll figure. Thanks!
> 
> Running `flutter config --no-analytics` also worked, with AdGuard enabled.

didn't work for me

**Comment by rahulrvp** [comment]
I have been going through all the issue threads related to this. Everywhere people mention quitting/disabling the AdGuard or anti-virus software. I do not have AdGuard installed and uninstalling or disabling anti-virus software doesn't seem like an option to me due to my company policies. Now, how do I get this working?

The `flutter config --no-analytics` command only helps me to get the `flutter doctor` command to work. Once you start a project, the `flutter pub get` command is not working due to the very same error!

Totally stuck now!! Seeing this issue still occurring in March 2021 even though this was reported in q4 of 2020, I think this is a bit of a negligible towards the @flutter community.

```
Running "flutter pub get" in my_app...                

Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub get failed (255; #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12))
Process finished with exit code 255
```

**Comment by ceeyang** [comment]
> > Aha, apparently AdGuard was also the problem here. Not sure how to add it to the whitelist instead of disabling it, but I'll figure. Thanks!
> > Running `flutter config --no-analytics` also worked, with AdGuard enabled.
> 
> didn't work for me, it also throws this issue

I have this problem too.  
`flutterr config --no-analytics` not work for me .
But `flutter pub get` work fine after I had closed the Adguard.

Are there other solutions?
