### ISSUE TITLE
[web] integration tests flaky due to chrome failing to start

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#71508]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8862086434858666720/+/steps/felt_test_chrome/0/stdout#L39178_0

Text:

```
UnknownException (13): unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /b/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/chrome/768968/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 4.9.0-11-amd64 x86_64)
```

Failed on presubmit

@nturgut @yjbanov

**Comment by zanderso** [comment]
This has flaked 4 out of the last 13 builds on Mac Web Engine: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine.

This is too flaky, so I am bumping this up to P1.

**Comment by yjbanov** [comment]
Lowering back to P4. The original issue is due to Chrome process failing to start:

```
UnknownException (13): unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /b/s/w/ir/cache/builder/src/flutter/lib/web_ui/.dart_tool/chrome/768968/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 4.9.0-11-amd64 x86_64)
```

Updating the issue description

**Comment by yjbanov** [comment]
In some other test runners I added some protection against this, but I'm not sure if those fixes covered integration tests.

**Comment by yjbanov** [comment]
Well, more specifically I added handling of a flaky glibc bug: https://github.com/flutter/flutter/pull/67466. I'm not sure if this crash is due to the same bug.

**Comment by yjbanov** [comment]
I haven't seen this flake in a long time. Closing for now.
