### ISSUE TITLE
Some animations are very slow on Samsung Galaxy S4

### ISSUE THREAD

**Issue by gazialankus** [flutter/flutter#7150]
In my Samsung Galaxy S4 phone, most animations work very slowly, around 1 FPS or slower. There are intermittent delays between frames. Doing the same thing over and over usually makes the action smooth after a while. Here are some specific observations: 

- In Gallery, the app bar enlarging/shrinking while scrolling at the top (this was always slow no matter how many times I tried, or maybe I didn't try enough number of times since it takes too long)
- In stocks app, scrolling enough so that new cells are populated (tiny-distance scrolls are usually smooth)
- Left menu appearing for the first couple of times in Stocks app (afterwards it's always smooth)
- First tab switch in stocks app (afterwards it's smooth)
- Going into a stock in stocks app (pressing back and going into the stock again is smooth)
- Optimistic/pessimistic switching in stocks app (after 4-5 switches it became smooth)

Also, when I check "Performance Overlay" in Gallery, nothing changes. I do not see that profiler kind of graph at all. Checkerboard Raster Cache Images works though. 

These are the Gallery app that I run using `flutter run --release` and Gallery and Stocks apps that I downloaded from here: https://build.chromium.org/p/client.flutter/waterfall?show=Linux . Unfortunately I cannot test Flutter Gallery et al. in Play store since they are not available in my country. 

Here are details about my phone: 
Samsung Galaxy S4 (GT-I9500)
Android 5.0.1
Rom: Omega v28 - UBUHOE3 

@eseidelGoogle said it may be a quirk related to this device's GPU. I'd be happy to run things and send back logs, or help in any other way.

**Comment by eseidelGoogle** [comment]
Could you add the output of `adb shell dumpsys | grep GLES`?  It should be one line which describes your GPU model (The Samsung S4 supposedly shipped with two different GPUs depending on country).

**Comment by gazialankus** [comment]
Yes there are a couple of S4s, I think i9500 is a unique model number for mine. Here's the output: 
GLES: Imagination Technologies, PowerVR SGX 544MP, OpenGL ES 2.0 build 1.10@2359475

**Comment by gazialankus** [comment]
I found a friend that has a different Galaxy S4 (a i9505). He had  none of these issues. It has an Adreno 320 GPU. I'll see if I can find someone else with an i9500 like mine

**Comment by eseidelGoogle** [comment]
Well "PowerVR SGX544" is a super common GPU at 2.9% of devices according to http://hwstats.unity3d.com/mobile/gpu-android.html  Same GPU as the iPad 4 iirc.  We have this exact device in our central lab as far as I can tell.

**Comment by eseidelGoogle** [comment]
@chinmaygarde if you're interested in investigating, we can get this device from the central lab.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by mixedCase** [comment]
I can reproduce the OP's claims in a Galaxy S3 International (i9300), which has quite different hardware. Animations are janky, specially the first time they're triggered; afterwards they're smooth.

Some animations like the main menu header resizing are always slow.

**Comment by mixedCase** [comment]
As suggested on gitter, I am attaching a screen capture of the timeline when I first try to open the main navigation drawer for the first time (where the animation is janky)

![Screenshot](https://i.imgur.com/Q5VEUae.png)

**Comment by eseidelGoogle** [comment]
Thanks for the trace!  Definitely looks slowness from the gpu-side of things (either the way we're driving the gpu, or a bug in the driver, etc we'll need to work around).  I don't have this particular phone in our cube, but I believe we have some in the central lab (which I've provided @abarth instructions on how to borrow from).

**Comment by eseidelGoogle** [comment]
@jason-simmons did we ever get a copy of this phone?  I'm happy to order one.

**Comment by jason-simmons** [comment]
AFAIK we don't have one

**Comment by Hixie** [comment]
cc @eseidel This is waiting on action from you, I believe.

**Comment by gazialankus** [comment]
Although these are older hardware, this will be a pain point for choosing Flutter. There will be customers who can't use your app and there's nothing you can do about it.

**Comment by eseidelGoogle** [comment]
Typically when we hit issues like this (very long frame times) it's due to a bug in our graphics stack specific to the exact phone/gpu in question.

I"ll order a i9500 S4 and we can test on the actual hardware and see.

**Comment by eseidelGoogle** [comment]
I've ordered one.  They are also available for checkout from the central lab if someone wants one before January.

**Comment by eseidelGoogle** [comment]
Phone arrived.  I've placed it on @jason-simmons's desk.

**Comment by cbracken** [comment]
Got a report from @lastempirestudio in Gitter over the weekend, who also ran into this.

**Comment by volkans80** [comment]
Flutter 1.0.0
Samsung Galaxy S4 GT-I9500
Android 5.0.1
PowerVR SGX544MP
OpenGL ES 2.0 build 1.10@2359475
Still low frame rate with pushed button demo.

**Comment by MHandosa** [comment]
Flutter 1.5.4-hotfix.2
Samsung Galaxy S4 GT-I9500
The pushed button demo is too slow. Any updates?

**Comment by amrosama2020** [comment]
Is there any work around for this? Or anyway we can help?

**Comment by eseidelGoogle** [comment]
Wow, this is a very old bug.  If we actually have one of these phones still, root causing this is probably a matter of taking a trace of the slowness on this phone (using a profile build) and then comparing that with a trace from another phone to figure out where/how this phone is abnormally slow.  From such information we can figure out where to route this bug.  For example, if it's in GPU work, this may be something we need to work on with the Skia team (there are lots of phone-specific GPU bugs Skia has to work around and it's possible this specific phone just has another one).
https://flutter.dev/docs/perf/rendering/ui-performance

**Comment by liyuqian** [comment]
Both https://github.com/flutter/flutter/issues/7150#issuecomment-402176945 and https://github.com/flutter/flutter/issues/7150#issuecomment-279204534 seem to suggest that the slowness only happens on the first time of an animation. Later it will become much smoother. Therefore I suspect that this is related with shader compilations. Maybe the GPU driver in those devices just takes a very long time to compile shaders. If one can record a trace with `flutter run --profile --trace-skia`, that could give us some definite answers. @jason-simmons : I can't seem to find Galaxy S4 in our device library spreadsheet. Do you know where that device is? Also CC @xster as Xiao is sitting next to the actual device library.

**Comment by reidbaker** [comment]
Last update indicated shader compilations as the core issue. Project Impeller, currently available on ios, should be available on android in 3.12 as a preview focuses specifically on improving shader compilation jank. If you hit this issue try out impeller and give us feedback. https://docs.flutter.dev/perf/impeller
