### ISSUE TITLE
[flutter_tools] quality pass on windows build

### ISSUE THREAD

**Issue by eduardo-cervantes** [flutter/flutter#71500]
A while ago @jonahwilliams made persistent changes to the "quality pass on (Windows, Linux and MacOS) build". However, only Windows failed.

**According to Cirrus CI automated tests:**
```
Failed to delete C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_vmservice_integration_test.26c47fdd-859b-11ea-a63b-c3047c67b1e6: FileSystemException: Deletion failed, path = 'C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_vmservice_integration_test.26c47fdd-859b-11ea-a63b-c3047c67b1e6' (OS Error: Access is denied.
, errno = 5)
```

My question is whether we have any alternatives today to be able to use "_--dart-defines_" in the native Windows language, c++. Or if the resource was left out.

**Comment by jonahwilliams** [comment]
@eduardo-cervantes I have no idea what you are talking about

**Comment by eduardo-cervantes** [comment]
I'm sorry for the confusion, but in the [commit](https://github.com/flutter/flutter/commit/543186f1052aa2fcfc14836ec11f4044560b3081#diff-588f6863fb5e59bdbf211cff5b89515b19b8eeed41399a2a6d7bfba0856ac3f7) it seems to me that a way to search for the `DART_DEFINES` variables was added to the `build_windows.dart` file, but I was looking at the wrong file, which in this case would be the `tool_backend.dart.`

I also hadn't identified the next commit "Address comments".
Again, I'm sorry.

However, can you help me with one thing?
How can I retrieve the values of `--dart-define`, using c++ on Windows?

**Comment by TahaTesser** [comment]
Hi @eduardo-cervantes 
Looks like you answered your own question, I am gonna close the issue as non-actionable 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by eduardo-cervantes** [comment]
> How can I retrieve the values of `--dart-define`, using c++ on Windows?

Yes, really @TahaTesser, I understood my mistake myself. But in the end I asked a question.
