### ISSUE TITLE
Migrate all dev/ code to null-safe Dart

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71505]
We should start migrating all our code in //flutter/flutter/dev to null safety.

- [x] automated_tests
- [ ] benchmarks
- [ ] bots
- [x] ci
- [ ] customer_testing
- [ ] devicelab
- [ ] docs
- [ ] integration_tests
- [ ] manual_tests
- [x] missing_dependency_tests
- [ ] snippets
- [ ] tools
- [x] tracing_tests

**Comment by goderbauer** [comment]
Updated top-level comment with a check list.

**Comment by goderbauer** [comment]
Migrating most of the things is blocked on rolling `args` to a null-safe version.

**Comment by stuartmorgan** [comment]
Presumably this issue is outdated and the migration is complete?

**Comment by goderbauer** [comment]
This is done.
