### ISSUE TITLE
flutter-devicelab-mac-18 is not responding

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#71510]
`flutter-devicelab-mac-18` is not responding, making the tree red on `platform_interaction_test (devicelab)`

https://flutter-dashboard.appspot.com/#/build
https://flutter-dashboard.appspot.com/#/agents

**Comment by godofredoc** [comment]
is mac-18 taking tasks? it is quarantined. We fixed a couple of machines only to unblock the tree

**Comment by Piinks** [comment]
The tree is currently red with a task on that machine, it just went red after being yellow for a long while. I wasn't able to rerun it before, it may have just resolved..

**Comment by Piinks** [comment]
Tree is now green again.

**Comment by midoo844** [comment]
Hi
