### ISSUE TITLE
[android_intent] Add the possibility to open an app chooser

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#71518]
Hello folks,

As in title this is as feature request it will be nice to be able to open an app chooser for `android`.

My example use case will be to be able to open the chooser in case there is not a default email app:

```java
Intent intent = new Intent(Intent.ACTION_MAIN);
intent.addCategory(Intent.CATEGORY_APP_EMAIL);
startActivity(intent);
startActivity(Intent.createChooser(intent, getString(R.string.ChoseEmailClient)));
```

**Comment by miquelbeltran** [comment]
Hi @nerder , why do you call to `startActivity` twice in your example? or is it a typo?

 I am asking because I am thinking this could be added to https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_intent_plus

**Comment by nerder** [comment]
Hey @miquelbeltran , I guess it's a typo actually since I've taken this from a SO question when I was attempting to launch the chooser using `android_intent` in flutter.

**Comment by nerder** [comment]
Actually now that i'm taking a look at this it seems like is not a typo as is in the proposed answer from the SO question: https://stackoverflow.com/a/13849013/4420152

**Comment by stuartmorgan** [comment]
Closing as `android_intent` is deprecated in favor of [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).
