### ISSUE TITLE
Documentation spelling mistake.

### ISSUE THREAD

**Issue by Frostrix** [flutter/flutter#71536]
Just a quick one in the Wiki for [Tree Hygine](https://github.com/flutter/flutter/wiki/Tree-hygiene).
![Documentation Image](https://user-images.githubusercontent.com/51069105/100840055-2e588480-34da-11eb-8886-2534f4a687a8.png)
Notably the missing `)` bracket.

**Comment by TahaTesser** [comment]
Hi @Frostrix 
I just fixed it, removed the extra bracket, added `,` instead.  https://github.com/flutter/flutter/wiki/Tree-hygiene
Thanks for filing the issue
