### ISSUE TITLE
Installing flutter on linux without curl.

### ISSUE THREAD

**Issue by happy-san** [flutter/flutter#71532]
I cloned the flutter repo and added it to my $PATH variable, [as suggested](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually). Then running `$ flutter doctor` returns:

```
Downloading Dart SDK from Flutter engine 20caf549695193a9920ca37752eca4f141bbef31...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: storage.googleapis.com

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/20caf549695193a9920ca37752eca4f141bbef31/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

According to the [official guide](https://flutter.dev/docs/get-started/install/linux) for installation, `curl` is a necessary tool for installing flutter and this is happening because of my system constraints (`toolbox` container in EndlessOS), because of which I don't have internet access so `curl` cannot resolve any host. So I took the link provided in the error message and downloaded the file. Now how do I "notify" `flutter` about this?

**Comment by TahaTesser** [comment]
Hi @happy-san 
You can unzip the downloaded SDK zip file and paste into the flutter directory in the following location
flutter -> bin -> cache -> paste `dart-sdk` folder here and run `flutter doctor -v`. (I am not sure this will be enough but worth a try) 

However,  curl is a necessity for most command-line tools,  hope this helps.

**Comment by happy-san** [comment]
Thanks for responding, I'll try it out.

**Comment by happy-san** [comment]
The unzip procedure didn't work. But downloading the tar.xz bundle and then setting the path variable did. Thankyou.
