### ISSUE TITLE
flutter run --profile --trace-skia  can't see timeline v1.12.16

### ISSUE THREAD

**Issue by takete2** [flutter/flutter#71549]
`flutter run --profile --trace-skia `

Open Observatory

see timeline

```
timeline.js:538 Uncaught ReferenceError: tr is not defined
    at updateTimeline (timeline.js:538)
    at populateTimeline (timeline.js:562)
    at onMessage (timeline_message_handler.js:29)
```

**Comment by TahaTesser** [comment]
Hi @takete2 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by takete2** [comment]
localhost:flutter_test_app syswin$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/syswin/Documents/flutter
    • Framework revision f139b11009 (8 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/syswin/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/syswin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • BND AL10 • LMXNW18326005524 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 3 categories.

**Comment by takete2** [comment]
just new flutter project ,the sample code。
flutter run --profile 
in Observatory,everything else can be checked, but timeline  has some problems.
timeline can be exported but the chart is blank.

**Comment by takete2** [comment]
localhost:flutter_test_app syswin$ flutter run --profile --trace-skia --verbose
[  +25 ms] executing: [/Users/syswin/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/syswin/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +60 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b11009
[   +8 ms] executing: [/Users/syswin/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'develop_660_flutter'
[  +12 ms] executing: [/Users/syswin/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] develop_660_flutter
[  +33 ms] executing: /usr/bin/xcode-select --print-path
[  +12 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +1 ms] executing: /usr/bin/xcodebuild -version
[   +4 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is
a command line tools instance
[  +76 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb devices -l
[  +14 ms] Exit code 0 from: /Users/syswin/android-sdk-macosx/platform-tools/adb devices -l
[        ] List of devices attached
           LMXNW18326005524       device usb:336855040X product:BND-AL10 model:BND_AL10 device:HWBND-H transport_id:1
[  +24 ms] executing: /Users/syswin/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +51 ms] executing: /usr/bin/xcodebuild -version
[   +3 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is
a command line tools instance
[  +14 ms] /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell getprop
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +230 ms] Generating
/Users/syswin/Desktop/study/flutter_test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +26 ms] ro.hardware = hi6250
[        ] ro.build.characteristics = default
[  +10 ms] executing: /usr/bin/xcodebuild -version
[  +11 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is
a command line tools instance
[  +38 ms] executing: /Users/syswin/android-sdk-macosx/build-tools/29.0.2/aapt dump xmltree
/Users/syswin/Desktop/study/flutter_test_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: /Users/syswin/android-sdk-macosx/build-tools/29.0.2/aapt dump xmltree
/Users/syswin/Desktop/study/flutter_test_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.systoon.fluttertestapp" (Raw: "com.systoon.fluttertestapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="fluttertestapp" (Raw: "fluttertestapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.systoon.fluttertestapp.MainActivity" (Raw: "com.systoon.fluttertestapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Launching lib/main.dart on BND AL10 in profile mode...
[   +3 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell -x logcat -v time -t 1
[  +75 ms] Exit code 0 from: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           12-03 10:29:52.985 I/EventHub( 1178): EventHub monitor: no key events in the past 769s, no motion events in the past 67s
[   +8 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb version
[   +2 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 logcat -v time -T 12-03 10:29:52.985
[  +10 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as /Users/syswin/android-sdk-macosx/platform-tools/adb
[   +2 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb start-server
[  +14 ms] Building APK
[  +26 ms] Running Gradle task 'assembleProfile'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/syswin/Desktop/study/flutter_test_app/android/gradlew.
[ +153 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +15 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"MainClass":"com.intellij.idea.Main","ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\
/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$A
PP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","Properties":{"idea.home.path":"$APP
_PACKAGE\/Contents","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.paths.selector":"AndroidStudio3.5"},"WorkingDi
rectory":"$APP_PACKAGE\/Contents\/bin"},"LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-191.8026.42.35.5977832","CFBundleDevelop
mentRegion":"English","CFBundleDocumentTypes":[{"CFBundleTypeExtensions":["ipr"],"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeIconFile":"studio.icns","CFBundleTypeRole":"Editor"},{"CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"LS
TypeIsPackage":false,"CFBundleTypeName":"All
documents","CFBundleTypeRole":"Editor"}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"stud
io.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"3.5","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"stu
dio","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"],"CFBundleTypeRole
":"Editor"}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleS
ignature":"????","LSMinimumSystemVersion":"10.8","CFBundleGetInfoString":"Android Studio 3.5, build AI-191.8026.42.35.5977832. Copyright
JetBrains s.r.o., (c) 2000-2019"}
[  +12 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +75 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +2 ms] executing: [/Users/syswin/Desktop/study/flutter_test_app/android/] /Users/syswin/Desktop/study/flutter_test_app/android/gradlew
-Pverbose=true -Ptarget=/Users/syswin/Desktop/study/flutter_test_app/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleProfile
[ +939 ms] > Task :app:compileFlutterBuildProfile UP-TO-DATE
[  +84 ms] > Task :app:packLibsflutterBuildProfile UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preProfileBuild UP-TO-DATE
[        ] > Task :app:compileProfileAidl NO-SOURCE
[        ] > Task :app:checkProfileManifest UP-TO-DATE
[        ] > Task :app:compileProfileRenderscript NO-SOURCE
[        ] > Task :app:generateProfileBuildConfig UP-TO-DATE
[        ] > Task :app:javaPreCompileProfile UP-TO-DATE
[        ] > Task :app:cleanMergeProfileAssets
[        ] > Task :app:mergeProfileShaders UP-TO-DATE
[        ] > Task :app:compileProfileShaders UP-TO-DATE
[        ] > Task :app:generateProfileAssets UP-TO-DATE
[        ] > Task :app:mainApkListPersistenceProfile UP-TO-DATE
[        ] > Task :app:mergeProfileAssets
[        ] > Task :app:copyFlutterAssetsProfile
[        ] > Task :app:generateProfileResValues UP-TO-DATE
[        ] > Task :app:generateProfileResources UP-TO-DATE
[  +97 ms] > Task :app:mergeProfileResources UP-TO-DATE
[        ] > Task :app:createProfileCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processProfileManifest UP-TO-DATE
[        ] > Task :app:processProfileResources UP-TO-DATE
[        ] > Task :app:compileProfileJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileProfileSources UP-TO-DATE
[        ] > Task :app:checkProfileDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarProfileFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexProfile UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForProfile UP-TO-DATE
[        ] > Task :app:mergeDexProfile UP-TO-DATE
[  +77 ms] > Task :app:processProfileJavaRes NO-SOURCE
[        ] > Task :app:mergeProfileJavaResource UP-TO-DATE
[        ] > Task :app:validateSigningProfile UP-TO-DATE
[        ] > Task :app:signingConfigWriterProfile UP-TO-DATE
[        ] > Task :app:mergeProfileJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeProfileNativeLibs UP-TO-DATE
[        ] > Task :app:stripProfileDebugSymbols UP-TO-DATE
[        ] > Task :app:packageProfile UP-TO-DATE
[        ] > Task :app:assembleProfile UP-TO-DATE
[        ] BUILD SUCCESSFUL in 1s
[        ] 29 actionable tasks: 3 executed, 26 up-to-date
[ +376 ms] Running Gradle task 'assembleProfile'... (completed in 1.8s)
[  +40 ms] calculateSha: LocalDirectory: '/Users/syswin/Desktop/study/flutter_test_app/build/app/outputs/apk'/app.apk
[  +20 ms] calculateSha: reading file took 19us
[ +125 ms] calculateSha: computing sha took 125us
[   +3 ms] ✓ Built build/app/outputs/apk/profile/app-profile.apk (8.9MB).
[   +3 ms] executing: /Users/syswin/android-sdk-macosx/build-tools/29.0.2/aapt dump xmltree
/Users/syswin/Desktop/study/flutter_test_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +9 ms] Exit code 0 from: /Users/syswin/android-sdk-macosx/build-tools/29.0.2/aapt dump xmltree
/Users/syswin/Desktop/study/flutter_test_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.systoon.fluttertestapp" (Raw: "com.systoon.fluttertestapp")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="fluttertestapp" (Raw: "fluttertestapp")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.systoon.fluttertestapp.MainActivity" (Raw: "com.systoon.fluttertestapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on BND AL10.
[        ] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell am force-stop
com.systoon.fluttertestapp
[ +152 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell pm list packages
com.systoon.fluttertestapp
[ +657 ms] package:com.systoon.fluttertestapp
[   +4 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell cat
/data/local/tmp/sky.com.systoon.fluttertestapp.sha1
[  +35 ms] 6735173f1b0362127070d73c935e3827dc6c8151
[   +1 ms] Latest build already installed.
[        ] BND AL10 startApp
[   +3 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 shell am start -a android.intent.action.RUN
-f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez trace-skia true
com.systoon.fluttertestapp/com.systoon.fluttertestapp.MainActivity
[  +79 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.systoon.fluttertestapp/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +638 ms] Observatory URL on device: http://127.0.0.1:33982/26uGHzE9DPM=/
[   +1 ms] executing: /Users/syswin/android-sdk-macosx/platform-tools/adb -s LMXNW18326005524 forward tcp:0 tcp:33982
[  +10 ms] 53184
[        ] Forwarded host port 53184 to device port 33982 for Observatory
[  +11 ms] Connecting to service protocol: http://127.0.0.1:53184/26uGHzE9DPM=/
[ +118 ms] Successfully connected to service protocol: http://127.0.0.1:53184/26uGHzE9DPM=/
[   +3 ms] Sending to VM service: getVM({})
[   +6 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Unknown, operatingSystem: android, targetCPU: arm64, version: 2.7.2
(Mon Mar 23 22:11:27 2020 +0100) on "android_arm64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 19043, startTime: 16069...
[   +5 ms] Sending to VM service: getIsolate({isolateId: isolates/2142979739503311})
[   +3 ms] Sending to VM service: _flutter.listViews({})
[   +6 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7cc3a53b20, isolate: {type: @Isolate, fixedId:
true, id: isolates/2142979739503311, name: main.dart$main-2142979739503311, number: 2142979739503311}}]}
[   +5 ms] Application running.
[        ] Sending to VM service: _flutter.listViews({})
[  +29 ms] Result: {type: Isolate, id: isolates/2142979739503311, name: main, number: 2142979739503311, _originNumber: 2142979739503311,
startTime: 1606962596643, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[  +10 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7cc3a53b20, isolate: {type: @Isolate, fixedId:
true, id: isolates/2142979739503311, name: main.dart$main-2142979739503311, number: 2142979739503311}}]}
[        ] Connected to BND AL10
[   +1 ms] An Observatory debugger and profiler on BND AL10 is available at: http://127.0.0.1:53184/26uGHzE9DPM=/
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+528721 ms] W/InputMethodManager(19043): startInputReason = 8
[  +67 ms] V/ActivityThread(19043): Finishing stop of ActivityRecord{5599891 token=android.os.BinderProxy@332cfa0
{com.systoon.fluttertestapp/com.systoon.fluttertestapp.MainActivity}}
[  +32 ms] W/libEGL  (19043): EGLNativeWindowType 0x7ca27da010 disconnect failed
[        ] W/InputMethodManager(19043): startInputReason = 3
[+5119 ms] W/libEGL  (19043): EGLNativeWindowType 0x7ca2782010 disconnect failed
[  +14 ms] V/ActivityThread(19043): Handle window ActivityRecord{5599891 token=android.os.BinderProxy@332cfa0
{com.systoon.fluttertestapp/com.systoon.fluttertestapp.MainActivity}} visibility: false

**Comment by takete2** [comment]
i know....
I upgrade to version 1.22 and it's OK

**Comment by TahaTesser** [comment]
Hi @takete2 
Sounds like resolved with an upgrade to the latest stable, 8 months old Flutter would definitely cause problems. 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
