### ISSUE TITLE
flutter desktop platformview  

### ISSUE THREAD

**Issue by leielyq** [flutter/flutter#71558]
Very necessary！！！！！！！！！！！！

How to make a video player plug-in in windows

**Comment by TahaTesser** [comment]
Hi @leielyq 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/37673
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
