### ISSUE TITLE
A white screen appears after splash screen instead of flutter view

### ISSUE THREAD

**Issue by naamapps** [flutter/flutter#71568]
Currently I'm on Android and I can't test this on iOS at the moment.
I have a custom native splash screen set to my app.
When entering the app (when it's not in memory) the splash screen appears as expected, but after a few seconds it fades out to a white screen instead of the flutter view.
Then the white screen just cuts to the flutter view.
My app is nearly done, and it has an hefty amount of widgets and code (I suspect this what causes the white screen because when creating a blank flutter project and running it, it doesn't show a white screen, even on debug mode).
Unfortunately, I can't share some code because the app is almost done as I said.
It's important to note that I have set the file launch_background.xml to show a custom logo and color. 

This happens in debug mode and release mode.
When in debug mode the white screen appears for 5 seconds at least.
In release mode the white screen appears for under a second (really fast, but still noticeable).

Here is a gif showing the problem in release mode:
In the gif you can see the splash screen appears first as expected (the grey background), after that it just fades out to a white screen, and then it shows the actual flutter view.

![SM-G955F_20201202165059](https://user-images.githubusercontent.com/37176893/100888721-17586900-34bf-11eb-89ed-88f1a37b70da.gif)

<details>
  <summary>Flutter doctor -v</summary>
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-IL)
    • Flutter version 1.22.3 at /Users/naamapps/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/naamapps/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • SM G955F (mobile) • ce031713b9cc111e01 • android-arm64 • Android 9 (API
      28)

! Doctor found issues in 1 category.
</details>

**Comment by Shivam1337** [comment]
If you are doing any user validation or any async operation before rendering the first state of the application, it causes some delay in rendering which results in white screens like this one.

**Comment by darshankawar** [comment]
@naamapps 
Please provide a complete minimal reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by naamapps** [comment]
I actually found out that the package [easy_localization](https://pub.dev/packages/easy_localization) is loading the translation assets and in the meantime it show a blank screen.
Here is the package github issue, if anyone also experience this problem.
https://github.com/aissat/easy_localization/issues/267
Sorry for the inconvenience.

**Comment by tranvantam310** [comment]
I fixed that bug when rewrite by link.    https://androworldblog.wordpress.com/2017/08/31/removing-blank-white-screen-before-app-start-upsplash-screen/
