### ISSUE TITLE
TabBar index listener issue

### ISSUE THREAD

**Issue by halimpuckjava** [flutter/flutter#71564]
hi

1.  when to addListener to track index change we must add this condition to check if realy index is changed (behavior not necessary because addListener goal is tracked any change in index)
```
if (tabController.indexIsChanging)
  ......
``` 

2. with TabView and when swipe its work fine (not necessary to add previews block to check indexIsChanging every time), however when tap on any tab the change event is fired twice 

i using flutter 1.22.4 & dart 2.10.4

**Comment by pedromassangocode** [comment]
Hi @halimpuckjava 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
