### ISSUE TITLE
a problem occured while configuring project 'camera'.

### ISSUE THREAD

**Issue by akshat102** [flutter/flutter#71565]
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_twitter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\<name>\.gradle\caches\transforms-2\files-2.1\cc05cbb20248c793dee14f7d6605fdfb\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariati
onSettings not found.

     C:\Users\<name>\.gradle\caches\transforms-2\files-2.1\cc05cbb20248c793dee14f7d6605fdfb\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex no
t found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 20s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     382.5s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    9.3s


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

The plugin camera could not be built due to the issue above.

**Comment by akshat102** [comment]
This is my flutter doctor -v output

C:\Users\<name>\AndroidStudioProjects\ak_flash_chat>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\aknit\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\aknit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Redmi Note 5 Pro (mobile) • 92ec6a26 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment]
Hi @akshat102 
Looks you've SDK is not detected in located in app > android > local.properties file
```bash
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

1. Please execute ``flutter doctor --android-licenses``, accepts al the licenses
2. As error suggest, add `ANDROID_HOME` environment for your Android SDK or make sure you've sdk located in local.properties
```bash
sdk.dir=/Users/loaction_to/sdk
flutter.sdk=/Users/loaction_to/flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```

Then try running the app
Thank you

**Comment by akshat102** [comment]
1. On executing flutter doctor --android-licences

output-->



Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ... 5 more


2. i set my sdk.dir variable to my desired android sdk location

**Comment by TahaTesser** [comment]
Hi @akshat102 
Can you please make sure you've command-line tools, SDK tools, build tools, installed
Check out https://github.com/flutter/flutter/issues/57017#issuecomment-696559427 
After installing, try running the command `flutter doctor --android-licences` again
Thanks

**Comment by akshat102** [comment]
yes i have added these but still the problem persists

**Comment by TahaTesser** [comment]
Hi @akshat102 
Can you please provide flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by akshat102** [comment]
i have accepted the android licenses but still not able to build my app in release mode

**Comment by TahaTesser** [comment]
Hi @akshat102 
To better address the issue, please provide details Can you please provide `flutter run --verbose` and a complete reproducible minimal code sample without third-party packages.
Thank you

**Comment by mvysny** [comment]
You need to use JDK 8; `flutter doctor --android-licenses` is not compatible with Java 9+. You can temporarily force java by running `export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/` then running `flutter doctor --android-licenses`.
