### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by RandSohail** [flutter/flutter#71570]
when i run flutter doctor on the cmd this is happen 
i can not run any thing on vscode
![Capture](https://user-images.githubusercontent.com/32583123/100893335-efb7cf80-34c3-11eb-9ed3-7a45d71bf125.PNG)

**Comment by darshankawar** [comment]
@RandSohail 
Check [this](https://github.com/flutter/flutter/issues/27342) similar issue and corresponding issue [comment](https://github.com/flutter/flutter/issues/27342#issuecomment-459403078) to see if it resolves your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
