### ISSUE TITLE
Scaffold open drawer and background "dimness"

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7157]
I'd like to control how dim the background is behind an open drawer. I didn't see a parameter for that. I'm guessing that's maybe a material designs standard, but in my case it's useful to "preview" changes made in the drawer.

**Comment by eseidelGoogle** [comment]
So this is where the color is set up:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/drawer.dart#L237

Not sure how you'd want it configurable.  You are trying to change the max darkness to something lighter?

**Comment by jtrunick** [comment]
I'd want to change the "end:" color. That property is final so no chance there, not sure how this gets "evaluated" though.

  backgroundColor: _color.evaluate(_controller)

**Comment by Sh1d0w** [comment]
I also need this to be configurable so I can change the end colour of the backdrop.

**Comment by rami-a** [comment]
I believe this is already possible with a [parameter](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L1479) on `Scaffold`. Additionally, [this PR](https://github.com/flutter/flutter/pull/89237) will make it possible to do it at the theme level.
