### ISSUE TITLE
[flutter_tools] save size analysis files (created from --analyze-size) to .flutter-devtools folder

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#71585]
As of https://github.com/flutter/devtools/pull/2510, DevTools can now load files from the ~/.flutter-devtools/ directory. This is the only location from which DevTools can serve files for security reasons.

The --analyze-size command saves apk-analysis files to a default location. Can we change this to save the size analysis files to `~/.flutter-devtools/`? This will be a key part of adding a quick link from command line that can launch DevTools with the generated size analysis file.

@jonahwilliams

**Comment by jonahwilliams** [comment]
Does it have to only be `~/.flutter-devtools`, IIRC we do some specific logic to support XDG base directory specification for linux/macOS?

The output directory is configured here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L803 , so that could be updated.

**Comment by kenzieschmoll** [comment]
it just needs to be `<user-home-directory>/.flutter-devtools/` however that is implemented. This is the path we specify in devtools: https://github.com/flutter/devtools/blob/master/packages/devtools_server/lib/src/file_system.dart#L18

**Comment by kenzieschmoll** [comment]
Flutter tools should also be responsible for creating the `<user-home-directory>/.flutter-devtools/` directory if it is not already created. This would be the case for a user who has never opened DevTools.

**Comment by jonahwilliams** [comment]
You might consider expanding that to include https://github.com/flutter/flutter/issues/59430 .
