### ISSUE TITLE
Implement an auto-roller for test Chromium and Firefox versions

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#71589]
Currently our test browser versions are specified in two places:

- The [browser_lock.yaml](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/browser_lock.yaml#L20) file.
- CIPD packages.

The upgrade process is tedious and manual. As a result we frequently test on severely out-of-date browsers because nobody bothers to upgrade. For example, as of this writing we test on Firefox 72 while the current stable Firefox is 83, i.e. 11 versions ahead. Current stable Chrome is 87, but we test on 84. On top of that, few team members are familiar with CIPD and the upgrade process.

An auto-roller would improve our testing story considerably. Unfortunately, we cannot roll Safari because it's locked to the OS version, and therefore requires a coordinated effort with the infra team. However, Chromium and Firefox should be straightforward to auto-roll.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
