### ISSUE TITLE
Cocoon agent dashboard needs to fail gracefully if the underlying data is invalid

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#71592]
See #71584, where a couple of entries with null values broke the whole dashboard page. We should fail gracefully so that only the broken entries are not shown.

**Comment by godofredoc** [comment]
Close this one after devicelab migration to luci is complete.

**Comment by CaseyHillers** [comment]
@godofredoc @yusufm have we migrated the last of the agents to swarming? Can we close this?
