### ISSUE TITLE
Running a test with package:integration_test should supress warnings about missing plugin for package:integration_test

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#71594]
When we run from `flutter drive`, the user sees a message like this:

> Warning: integration_test test plugin was not detected.

This is confusing for users. We should avoid trying to communicate on the channel in that case so the message wn't show up.

/cc @csells @johnpryan

**Comment by jiahaog** [comment]
Fixing this would be fairly involved... Currently there's no synchronization mechanism to tell the app that it has been started from `flutter drive` – when the app starts it automatically runs the tests. The driver script only makes a single call to gather the results.

An approach to doing this might be to make the tests wait for a signal from the driver, before starting the tests. But this will unfortunately break the other methods of running the app such as reporting to FTL which do not need this signal. Perhaps this could be another use case for the executable proposed in #66264 which can automatically add some codegen into the app to tell it that the tests are triggered from the `flutter drive`.

Or we could also figure out if we can unconditionally include those native plugins, but I'm not sure how plugin integration works upstream when `package:integration_test` is a `dev_dependency` and used by scripts not in `lib/`

**Comment by dnfield** [comment]
Before we print the error we could see if anything has connected to the driver extension, right?

**Comment by jiahaog** [comment]
I think that could be prone to race conditions. Without synchronization the driver might end up connecting late after the test has completed and the warning will still be printed.

**Comment by dnfield** [comment]
If the driver connects that late would the message even be printed?

At any rate, Flutter's style guide says no logging messages unless they contain clear instructions for a user to take action on. This message is not actionable. We should only be printing it if we're in the case where the plugin would have been expected to load. 

I strongly suspect we can solve this without doing codegen. For example, we could set a dart define environment variable and read it when launching from drive, if we don't do that already.

**Comment by dnfield** [comment]
i.e. `flutter drive` could add a `--dart-define` like `flutter.driver=true`, and `integration_test` could check whether `bool.fromEnvironment('flutter.driver', false)` is true.

**Comment by darshankawar** [comment]
The warning persists on latest stable using `integration_test` plugin example.

```
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:53337/FOyiNdCU4lg=/
VMServiceFlutterDriver: Isolate found with number: 3209385638218435
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: failing test example
VMServiceFlutterDriver: Connected to Flutter application.
flutter: 00:00 +1: (tearDownAll)
**flutter: Warning: integration_test test plugin was not detected.**
flutter: 00:00 +2: All tests passed!
All tests passed.

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>
