### ISSUE TITLE
Use consistent Firefox/geckodriver versions across all tests

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#71617]
Currently our Firefox testing situation is complicated because we use different Firefox installations for different kinds of tests:

- Unit-tests: use downloaded Firefox based on browser_lock.yaml; geckodriver doesn't matter; they don't use it.
- Integration tests: use system Firefox and geckodriver stored in CIPD.

This leads to all sorts of version mismatches.

We should change it so that all tests, unit- and integration tests, use the Firefox and geckodriver specified in the browser_lock.yaml.

**Comment by nturgut** [comment]
Thanks for filing the issue. For this I'll use the following approach (we partially do this today for chrome/chromedriver)

1) Choosing the browser and geckodriver versions by reading browser_lock.yaml from the recipe
2) Setting firefox binary to the path

**Comment by godofredoc** [comment]
@nturgut is this something you will be working on?

**Comment by nturgut** [comment]
@godofredoc yes I'll work on this. Thanks for checking!

**Comment by yjbanov** [comment]
Closing since integration tests were removed from the engine
