### ISSUE TITLE
Migrate devicelab linux tests from staging to prod

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#71615]
Devicelab linux tests have been running in staging for a while, and tests are stable. It is time to migrate linux tests from staging to prod.

Action items:

- [x] Reinstall OS on linux linux7 and linux8 to ensure a clean state
- [x] Provision four more devicelab bots (linux1, 2, 3, 4) to swarming bots
- [x] Together with existing two bots in staging, mark these six bots as prod
- [x] Update config to trigger post tests to prod pool
- [x] Disable triggering devicelab agent tests
- [x] Provision the remaining four devicelab bots to swarming and make them available in prod.

Part of https://github.com/flutter/flutter/issues/70635

**Comment by godofredoc** [comment]
We also need to reinstall the OS in those two machines to ensure they are in a clean state

**Comment by keyonghan** [comment]
Linux migration is done, with all linux tasks running in LUCI, 7 bots in prod, and 1 bot in staging. Closing.
