### ISSUE TITLE
flutter test --platform chrome (null-safety beta) doesn't respect default language version for file-imports

### ISSUE THREAD

**Issue by jonasfj** [flutter/flutter#71612]
```
# Use beta channel
flutter channel beta
flutter upgrade

# Create myapp
flutter create -t app myapp
cd myapp

# Create a test/utils.dart file that does something that's not allowed in language version 2.12
# This is allowed prior to null-safety, not not after null-safety
echo 'int badNullable() => null;' > test/utils.dart

# Import utils.dart in test/widget_test.dart
cat <(echo 'import "utils.dart";') test/widget_test.dart > test/widget_test.dart

# Run test
flutter test --platform chrome
Running "flutter pub get" in myapp...                              375ms

AssetNotFoundException: myapp|test/utils.ddc.js
Error compiling dartdevc module:myapp|test/utils.ddc.js

test/utils.dart:1:22: Error: The value 'null' can't be returned from a function with return type 'int' because 'int' is not nullable.
int badNullable() => null;
                     ^



Failed after 212ms
Failed to compile tests
```

**Note::**
 * The `pubspec.yaml` has `environment.sdk: '>=2.7.0 <3.0.0'`, so the _default language version_ is **2.7**.
 * The default language version for `myapp` applies to all files in the application, including `lib/` and `test/`, etc..

I'm guessing this has to do with how the code is compiled when running tests. It doesn't happen with `flutter pub run test -p chrome` (but that requires that you're not using widget_test).

**Comment by jonahwilliams** [comment]
I did not implement autodetection for flutter test --platform=chrome, since the `platform=chrome` part is hidden/currently used only for the SDK. We could definitely make this work for real with some time investment.

**Comment by jonahwilliams** [comment]
Nevermind, this isn't an issue with auto-detect. The problem is that we set the test directory as an org-dartlang-app root which means the compiler does not pick up the applications default language version. Either the tool needs to generate a new package config or remove the org-dartlang-app root for tests.

**Comment by jonahwilliams** [comment]
removing assignment because I will be OOO

**Comment by jonahwilliams** [comment]
This is out of date as null safety is required now
