### ISSUE TITLE
enable null assertions for web compilers 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#71614]

**Comment by srujzs** [comment]
Original issue here: https://github.com/dart-lang/sdk/issues/44259

Parent bug: https://github.com/dart-lang/sdk/issues/43780

This flag needs to be turned on by default in both compilers. The work here involves not only enabling it by default, but providing a way for users to disable it to be unblocked. We'd like to be able to link the documentation to disable it as well in the markdown file below like we did for build_web_compilers. Ideally, we'd like to get this in before the stable release for Flutter web, so we can tackle any incoming issues around it. Currently, this flag will only throw errors if in sound mode on both web compilers.

More information on what this flag does and what it looks like in both compilers here:
https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/doc/NATIVE_NULL_ASSERTIONS.md

**Comment by jonahwilliams** [comment]
This is enabled by default in the flutter tool now

**Comment by jonahwilliams** [comment]
The remaining work here would be to enable this for the web engine tests in flutter/engine. There are documents on how to do this with: https://github.com/dart-lang/build/blob/master/docs/native_null_assertions.md

**Comment by srujzs** [comment]
Thanks for doing this, Jonah! Do you know who can take over enabling/testing this for the web engine tests?

**Comment by jonahwilliams** [comment]
I brought this up with @nturgut today and she mentioned she would take a look, but from what I understand all of their current tests are either @dart=2.6 or already using the flutter tool.

**Comment by jonahwilliams** [comment]
Removing tool designation since the tool work is completed

**Comment by srujzs** [comment]
Hi, @nturgut, is there anything here left to do? Thanks!

**Comment by nturgut** [comment]
In order to enable null assertions for Flutter for Web tests we need to migrate the test harness. It still has the `@2.6` annotations. 
@ferhatb @mariamhas how shall we prioritize?

**Comment by srujzs** [comment]
I don't think it's a priority for code that isn't migrated yet. In other words, we only are worried about enabling this for code that is already migrated/is going to be migrated. If there is no motivating reason yet to migrate, that's fine.

**Comment by dnfield** [comment]
I think this is done. Closing, please re-open if it'm missing something - but there are no more 2.6 annotations in the web engine.
