### ISSUE TITLE
Can run on iOS from Xcode but not from Android studio

### ISSUE THREAD

**Issue by cls8428181** [flutter/flutter#71629]
I think the problem may have something to do with what it calls the "observatory port". When I'm running from the command line, it says "Waiting for observatory port" and that is where things stand for a few seconds before it gets into trouble.

What happens then is interesting, however. If I'm running from Android Studio, the app crashes on the iPhone and I see the array of app icons. But if I'm running from the command line, the error happens as shown in the attached log, but after that the app actually starts running on the iPhone, even though it is detached from the computer at that point.

Thanks
[bug.docx](https://github.com/flutter/flutter/files/5633418/bug.docx)

**Comment by TahaTesser** [comment]
Hi @cls8428181 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/71402
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
