### ISSUE TITLE
Explain SkyApplication in AndroidManifest.xml template and possibly rename it

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#7162]
## Steps to Reproduce

It's got a strange package name for legacy reasons and developers might not know whether they are supposed to customize it.

We can update the package name and deprecate but keep the old one around for legacy purposes.

**Comment by collinjackson** [comment]
@Hixie

**Comment by Hixie** [comment]
Collin's explanation:

>SkyApplication is implemented here: https://github.com/flutter/engine/blob/master/shell/platform/android/org/domokit/sky/shell/SkyApplication.java
>
>It's an ```android.app.Application``` that also calls ```FlutterMain.startInitialization(this);``` in the ```onCreate``` method.
>
>In most cases you would want to leave this field as-is and use ```org.domokit.sky.shell.SkyApplication```. The "package" attribute of the "manifest" tag is where you should name your application.
>
>However, if you want to override other behavior of the Android application, you can subclass ```SkyApplication```, or you can define your own class that subclasses ```android.app.Application``` and calls ```startInitialization```
