### ISSUE TITLE
Creating a state object to pass around for DartIsolate, RuntimeController, etc.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#71620]
We have some very long parameter lists in ui_dart_state.h dart_isolate.h, runtime_controller.h, and engine.h that basically just get forwarded around from Shell to engine to runtime controller to dart isolate to dart state.

Every time we update this list, it gets more unweidly and a bunch of unrelated tests have to get updated. It should be pretty straightforward to refactor this so that it uses a common object to encapsulate these state items, which could allow for sensible defaults for tests and avoid lots of long parameter lists.

Low priority since we don't add these often and this is just about internal code health.

/cc @jason-simmons @chinmaygarde fyi

**Comment by chinmaygarde** [comment]
I've thought about this before and while creating a state or arguments object (constructed via builder) is certainly doable, there are also a ton of things specified to the isolate constructors that look like a violation of the single responsibility principle. For instance, the Dart isolate constructor taking a reference to the unref queue or image decoders which are rendering concerns. We should also clean those up but putting them inside a virtual context object or something.

This is not to say that we can't do the two things separately though. Its just that refactoring away one might make the second step moot.

**Comment by bdero** [comment]
This was completed in flutter/engine#26247.
