### ISSUE TITLE
[Web]: Korean and custom font is not rendering on some devices

### ISSUE THREAD

**Issue by taz1208** [flutter/flutter#71627]
My app is web app
I used korean and custom font(NotoSansKR)
but some device text cut-off last character lite this
<img width="533" alt="Screen Shot 2020-12-03 at 10 32 31 AM" src="https://user-images.githubusercontent.com/50230038/100951960-ee81b380-3552-11eb-8670-038abce59537.png">

The correct is '사용 후기 등록하기', but some device '사용 후기 등록하',
I think this problem reproduced only at high resolution(Perhaps over FHD)

I tested this list
```
MacBook Pro (Retina, 15-inch, Mid 2015) -> fine,
MacBook Pro (15-inch, 2017) -> not fine,
galaxy note 10+ -> not fine, 
galaxy note 8 -> fine,
Iphone8+ -> fine,
Iphone6 -fine,
```
and my flutter -v doctor here

```
[✓] Flutter (Channel master, 1.25.0-4.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-KR)
    • Flutter version 1.25.0-4.0.pre at /Users/taz/Documents/flutter_channels/flutter_mastar
    • Framework revision a7f5fd5360 (3 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/taz/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/taz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by darshankawar** [comment]
@taz1208 
Tried the text on latest master on web, which rendered properly:

<img width="219" alt="Screenshot 2020-12-03 at 12 50 27 PM" src="https://user-images.githubusercontent.com/67046386/100976946-4675e580-3566-11eb-8df5-c3076837bcb2.png">


My machine : `MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)`

Can you provide a complete reproducible code sample that shows the issue ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.45, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-5.0.pre.45 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 81e1f7d1ed (6 hours ago), 2020-12-02 17:19:57 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!


```

</details>

**Comment by taz1208** [comment]
My code snippet here
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TEXT BUGGY',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: LayoutBuilder(
          builder: (context, constraints) => SubmitButton(
            isMobile: constraints.maxWidth > 800,
          ),
        ),
      ),
    );
  }
}

class SubmitButton extends StatelessWidget {
  final bool isMobile;
  const SubmitButton({
    Key key,
    this.isMobile = false,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      child: Container(
        margin: const EdgeInsets.only(top: 100),
        width: isMobile ? 240 : 337,
        height: 52,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(5)),
          color: Theme.of(context).accentColor,
        ),
        child: Text(
          '사용 후기 등록하기',
          style: TextStyle(
            fontFamily: 'NotoSansKR',
            fontSize: 14,
            fontWeight: FontWeight.w500,
            color: Color(0xff303030),
          ),
        ),
      ),
    );
  }
}
```

and pubspect setup here

```
fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Regular.otf
```

font is download from https://fonts.google.com/specimen/Noto+Sans+KR?query=noto

I found another clue.
The problem only occurs when applying the font.

**Comment by darshankawar** [comment]
@taz1208 
Tried your code sample with the font, but didn't see the rendering issue. Also tried the same on Pixel 3XL emulator and iPhone SE simulator (14) and saw no issues.

<img width="412" alt="Screenshot 2020-12-03 at 4 08 37 PM" src="https://user-images.githubusercontent.com/67046386/100999852-33bdd980-3583-11eb-90e5-081786627ea9.png">
<img width="222" alt="Screenshot 2020-12-03 at 4 13 29 PM" src="https://user-images.githubusercontent.com/67046386/100999855-36203380-3583-11eb-8f43-d24571d891ca.png">
<img width="273" alt="Screenshot 2020-12-03 at 4 15 06 PM" src="https://user-images.githubusercontent.com/67046386/100999861-36b8ca00-3583-11eb-8f88-ce20f991481d.png">

Are you consistently seeing the rendering issue ? 
I don't have the said machine `MacBook Pro (15-inch, 2017)` on which you said the rendering has issue, so can't really replicate.

**Comment by taz1208** [comment]
@darshankawar  
Yes, it still  same problems at same devices
My step is

1. `flutter build web`
2. deploy to my webserver(use golang in my case)
3. And then access to web from all device web browser 

I tried same browser (Chrome) on all devices

Did you test in real device?

The problem is not showing in mobile mode in Chroem developer tools.

I think the each devices different only resolution (but maybe it's barking up the wrong tree)

**Comment by taz1208** [comment]
This is working fine on Mac (MacBook Pro (Retina, 15-inch, Mid 2015))
![image](https://user-images.githubusercontent.com/50230038/101109145-8649d500-3619-11eb-8b76-774c061274e5.png)
and
this is not fine on Galaxy note 10+
![image](https://user-images.githubusercontent.com/50230038/101109176-9b266880-3619-11eb-96d0-11ed99135e43.png)
and resolution of Galaxy note 10+
![image](https://user-images.githubusercontent.com/50230038/101109198-aaa5b180-3619-11eb-9c3e-01f34d8792ca.png)

**Comment by darshankawar** [comment]
@taz1208 
I tried `flutter build web` and used localhost to verify on Web chrome which worked well and iphone SE simulator which also worked well:

<img width="360" alt="Screenshot 2020-12-04 at 12 12 31 PM" src="https://user-images.githubusercontent.com/67046386/101131766-d762c480-362b-11eb-8ee9-d35b3f8032f0.png">

Can you also check by trying `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true` and see if you get same issue ?

**Comment by taz1208** [comment]
@darshankawar 
It's not working fine form this command `flutter run -d chrome` on MacBook Pro (15-inch, 2017)
But it working fine when use the command `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

How can I fix when deploy webserver?

**Comment by taz1208** [comment]
additional
.svg not showing when use the command `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

pacakge : https://pub.dev/packages/websafe_svg

**Comment by darshankawar** [comment]
@taz1208 
Regarding .svg issue, you may need to open issue in the said package and follow-up there for updates.

**Comment by taz1208** [comment]
`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
![image](https://user-images.githubusercontent.com/50230038/101561953-a7d80180-3a09-11eb-8689-d71d8c84a2cb.png)

`flutter run -d chrome`
![image](https://user-images.githubusercontent.com/50230038/101561970-af97a600-3a09-11eb-8deb-8e77796dd7f3.png)


Tail icon is .svg

**Comment by taz1208** [comment]
`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
![image](https://user-images.githubusercontent.com/50230038/101562116-12893d00-3a0a-11eb-907e-09c603a7996c.png)

`flutter run -d chrome`
![image](https://user-images.githubusercontent.com/50230038/101562172-364c8300-3a0a-11eb-8b2b-985c94c1f14f.png)

Tail icon is .svg

**Comment by darshankawar** [comment]
@taz1208 
the svg are not supported on web yet. Check this open issue, https://github.com/dnfield/flutter_svg/issues/173

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis, since I am unable to replicate this issue on the devices I tried, per https://github.com/flutter/flutter/issues/71627#issuecomment-738605612 and https://github.com/flutter/flutter/issues/71627#issuecomment-737863568

**Comment by taz1208** [comment]
@darshankawar Thank you for your guidance.
I'm opened issue here : https://github.com/peiffer-innovations/websafe_svg/issues/15#issue-759912120

**Comment by hterkelsen** [comment]
It seems the original issue (Korean text rendering dropping last character) is not a problem in CanvasKit according to https://github.com/flutter/flutter/issues/71627#issuecomment-740309659

Removing the CanvasKit label.

**Comment by mdebbar** [comment]
@taz1208 is there any non-canvaskit issue to be reported here?

**Comment by taz1208** [comment]
hmm.. It's iffy situation.
same SDK version, same code.
It only the machine is different.

As I mentioned before
```
MacBook Pro (Retina, 15-inch, Mid 2015) -> fine,
MacBook Pro (15-inch, 2017) -> not fine,
galaxy note 10+ -> not fine, 
galaxy note 8 -> fine,
Iphone8+ -> fine,
Iphone6 -fine,
```

Usually only problem in the latest models.

**Comment by taz1208** [comment]
It's very strange..:(

It working differently on the same widget structure on the same device 

For example.
my widget like this

```
Column(
   children:[
      Text('안녕하세요'),
      Text('반갑습니다'),
   ]
);
```

First child works fine like '안녕하세요',
but second child not works fine like '반갑습니' (last character cut-off)

**Comment by yjbanov** [comment]
Can you please try this on the latest master channel? This was fixed recently.

**Comment by taz1208** [comment]
I tried this version about 5days ago

```
 Flutter (Channel master, 1.26.0-2.0.pre.177, on macOS 11.1 20C69 darwin-x64, locale en-KR)
    • Flutter version 1.26.0-2.0.pre.177 at /Users/ylabs/Documents/flutter_channels/flutter_mastar
    • Framework revision 7c26c8fbb1 (3 weeks ago), 2021-01-05 01:19:03 -0500
    • Engine revision b9dc0cf1d8
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)
```
 It still problem

**Comment by mdebbar** [comment]
@taz1208 could you upgrade the master channel? Yours is 3 weeks old.

**Comment by taz1208** [comment]
Awesome, It very cool
When I upgrade SDK, It solved all problem
Thanks every one!
