### ISSUE TITLE
[firebase_core] Big Problem

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#71631]
this is the stable versions ..
firebase_core: 0.5.0+1 #Error was here
cloud_firestore: 0.14.1+3 #depends on firebase_core
cloud_functions: 0.6.0 #depends on firebase_core
firebase_admob: 0.10.0+2 #depends on firebase_core
firebase_auth: 0.18.1+1 #depends on firebase_core
firebase_remote_config: 0.4.0 #depends on firebase_core
firebase_storage: 4.0.0 #depends on firebase_core

if you used the above packages on the latest versions you will face duplicated classes problem ..
and i need to use the latest versions but i can't do this , i set 10 days to find why i always get duplicated classes error everytime i try to run my app in debug session ..

i hope firebase_core developers to care about it and fix this error as soon as possible

**Comment by darshankawar** [comment]
@imeDevelopers 
Please consider opening this issue here : https://github.com/FirebaseExtended/flutterfire/issues
Closing.
