### ISSUE TITLE
Flutter build ios is OK! But no App.framework was create.

### ISSUE THREAD

**Issue by codeliu6572** [flutter/flutter#71632]
```bash
/Users/zcy/opt/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/zcy/opt/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zcy/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Codeliu 的 iPhone (mobile)  • 7bd2b5f58d52dbcdcc9a49f4cc76f0d51c33fd7c • ios • iOS 14.2
    • iPhone 12 Pro Max (mobile) • 81BBC7EF-634C-4C37-A244-E77DDA2C4CBE     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!
Process finished with exit code 0
```

**Comment by codeliu6572** [comment]
zcy@LHHdeMacBook-Pro signature % flutter build ios
Running "flutter pub get" in signature...                           2.7s
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 
Building cn.gov.zcy.GPCClientApp for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: KS98R2TSVP
Running pod install...                                             11.8s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           316.1s
Built /Users/zcy/Desktop/zcy/signature/build/ios/iphoneos/Runner.app.

**Comment by codeliu6572** [comment]
I tried :
flutter clean
removed cash, removed lockfile, remove deviceData
it does not work!
flutter build ios not have error, but App.framework still not create.
Xcode run and flutter run is ok, but not have App.framework

**Comment by TahaTesser** [comment]
Hi @codeliu6572 
Just tried to reproduce on the stable channel,
`App.framework` is generated when executing `flutter build ios`
`/Users/tahatesser/AndroidStudioProjects/stable_flutter/build/ios/iphoneos/Runner.app/Frameworks/App.framework` 

Can you open contensts of ths Runner and check if there is App.framework `Built /Users/zcy/Desktop/zcy/signature/build/ios/iphoneos/Runner.app.`

If the problem persists, Can you please provide your `flutter build ios --verbose` and a complete reproducible minimal code sample
Thank you
