### ISSUE TITLE
cant build flutter apk in release mode

### ISSUE THREAD

**Issue by akshat102** [flutter/flutter#71637]
FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 646

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > The value for this property cannot be changed any further.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      47.7s
Gradle task assembleRelease failed with exit code 1

**Comment by darshankawar** [comment]
@akshat102 
Check [this](https://github.com/flutter/flutter/issues/64510) issue and corresponding issue comments that have solutions to resolve this issue. See if they work for you.

**Comment by proninyaroslav** [comment]
@darshankawar 
Gradle version downgrade can't be a solution. Why hasn't this been fixed yet??

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by samerkh** [comment]
I had the same problem with andriod gradle plugin 4.1.1 and gradle version 6.5, I downgraded to 3.5.0 and 5.6.2 and it worked

**Comment by serkanayaz** [comment]
This working:
flutter build apk --target-platform android-arm,android-arm64,android-x64


But this not working:
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
