### ISSUE TITLE
Flutter app crashes after the native splash screen (Android issue ~ SecurityException)

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#71638]
## Steps to Reproduce

1. The issue is only reproducible with one of my apps: https://play.google.com/store/apps/details?id=com.svprdga.birthdays
2. Launch the previous app in a Galaxy A3 (2017), I haven't tested if the bug also happens in other devices

**Expected results:**

The app is launched successfully.

**Actual results:** 

The app crashes just after the native splash screen.

<details>
  <summary>Stacktrace:</summary>

> 2020-12-03 06:55:44.035 4910-4910/? E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(44)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
>         at android.os.Parcel.readException(Parcel.java:1967)
>         at android.os.Parcel.readException(Parcel.java:1913)
>         at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:8579)
>         at android.app.Activity.reportFullyDrawn(Activity.java:2015)
>         at io.flutter.embedding.android.e.c(Unknown Source:6)
>         at io.flutter.embedding.android.f$a.c(Unknown Source:6)
>         at io.flutter.embedding.android.m$b.c(Unknown Source:28)
>         at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(Unknown Source:21)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:325)
>         at android.os.Looper.loop(Looper.java:142)
>         at android.app.ActivityThread.main(ActivityThread.java:6944)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

</details>

**NOTE 1:** If I try to open the app just after it has crashed, I can open it without problems. It only happens the very first time I open it. (If I kill the process and try to open it again, the crash happens).
**NOTE 2:** The error doesn't happen in debug builds, only in the production signed build.

**Comment by darshankawar** [comment]
@svprdga 
Can you provide a minimal complete reproducible code sample from your project that helps to replicate the issue locally ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by yrom** [comment]
Some Samsung SM-G9350 customers of my APP run into the same crash. 
Logs:
```
07-15 17:59:56.789 17653 17653 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
07-15 17:59:56.789 17653 17653 E flutter : at android.os.Parcel.readException(Parcel.java:1967)
07-15 17:59:56.789 17653 17653 E flutter : at android.os.Parcel.readException(Parcel.java:1913)
07-15 17:59:56.789 17653 17653 E flutter : at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:8587)
07-15 17:59:56.789 17653 17653 E flutter : at android.app.Activity.reportFullyDrawn(Activity.java:2015)
```

My app was built with Flutter 2.2.2.
