### ISSUE TITLE
shared_preferences not persistence succeeded

### ISSUE THREAD

**Issue by fangzhouguang** [flutter/flutter#71639]
When I use shared_ Preferences，After the app exits  it enters again，The data read is null
the shared_preferences version is 0.5.12+4

**Comment by darshankawar** [comment]
@fangzhouguang 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by fangzhouguang** [comment]
LoginPage:
 ///保存登录信息到本地
   _saveLoginInfo(dynamic result) async{
     SharedPreferences prefs = await SharedPreferences.getInstance();
     prefs.setString("mobile", result['mobile']);
     prefs.setString("cert", result['cert']);
     prefs.setInt("time", result['time']);
     prefs.setString("deviceId", _deviceData['host']);
     _showToast('登录成功');
     Navigator.pop(context);
   }
OtherPage:
 _getLoginInfo() async{
    SharedPreferences _preferences =await SharedPreferences.getInstance();
    String mobile=_preferences.getString("mobile");
    print('mobile=$mobile');
  }
notes:
If you don't exit the app, you can print out the mobile,but if After the app exits it enters again，The mobile read is null

flutter doctor -v:

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.22.4 at E:\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\sdk\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • HMA AL00 (mobile) • 66J5T18A19017614 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by mohammadsm220** [comment]
can you show the code so we can understand the problem better

**Comment by darshankawar** [comment]
@fangzhouguang 
We would need a complete minimal code sample that we can copy paste and run in IDE that shows the issue.
Also, I tried the official `shared_preferences` plugin example on latest stable which worked properly without any issues. The data persisted across restarts and after stopping and running the app instance again.

You may want to check the plugin to see if you are missing anything in implementation.

**Comment by fangzhouguang** [comment]
Sorry, it's my problem. I called setmockinitialvalues on other pages, resulting in this result
Thanks.
