### ISSUE TITLE
URL Launcher Plugin fails to verify canLaunch

### ISSUE THREAD

**Issue by HangingClowns** [flutter/flutter#71634]
Flutter: 1.22.0
host: Mac OS Big Sur
device: iPhone 11 Pro Max iOS 14.2
url_launcher: 5.7.10

```dart
onPressed: () async {
                  const url = 'https://bit.ly/XXX';
                  if (await canLaunch(url)) {
                  await launch(url);
                  } else {
                  throw 'Could not launch $url';
                  }
                },
```
The above throws the exception. Skipping `canLaunch` will still let us use `launch` successfully on iOS.

**Comment by TahaTesser** [comment]
hi @HangingClowns 
if you non-safari browser as your default, you need to add the following in your info.plist 
```bash
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>https</string>
  <string>http</string>
</array>
```
https://github.com/flutter/flutter/issues/65936#issuecomment-720954413
Let me know  if this solves your issue

**Comment by HangingClowns** [comment]
thanks for that. maybe we can put this on the README or somewhere?

**Comment by TahaTesser** [comment]
@HangingClowns 
I have a PR pending for review https://github.com/flutter/plugins/pull/3252
