### ISSUE TITLE
flutter pub get --offline didn't work in 1.22.4 stable

### ISSUE THREAD

**Issue by leo7723** [flutter/flutter#71641]
I used to use pub get --offline in my project.
Because I cann't access pub.dev on CI server. The --offline mode is very important for me.
I can correct use with version 1.17.5. But when I use it on 1.22.4 the fllowing alert came out.
It seems like the **vector_math** version from origin sdk is not available.
Can you upgrade the version to make --offline work correctly?
```shell
Because every version of flutter_localizations from sdk depends on vector_math any which is forbidden, flutter_localizations from sdk is forbidden.
So, because flutter_module depends on flutter_localizations any from sdk, version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because every version of flutter_localizations from sdk depends on vector_math any which is forbidden, flutter_localizations from sdk is forbidden.
So, because flutter_module depends on flutter_localizations any from sdk, version solving failed.
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

**Comment by darshankawar** [comment]
@leo7723 
I think this issue belongs to dart-lang/pub. Please consider opening this issue here : https://github.com/dart-lang/pub/issues
Closing this from here. If you disagree, or think this is a Flutter issue and not dart-lang, write in comments and I'll reopen it.
Thanks.
