### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by monxarat** [flutter/flutter#71642]
Hi guys,

When I ran `flutter pub get` the bellow error has occurred. How to fix solve this issue.

```
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub get failed (255; #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12))

```

$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B50, locale en-JP)
    • Flutter version 1.22.2 at /Users/user/Documents/data/libs/flutter
    • Framework revision 84f3d28555 (7 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment]
@monxarat 
Check out [this](https://github.com/flutter/flutter/issues/71483#issuecomment-737096037) issue comment and see if that solution helps to resolve your issue.
You may also check out issues listed in below comment and see if they help.

https://github.com/flutter/flutter/issues/71006#issuecomment-732068735

**Comment by monxarat** [comment]
@darshankawar 
Thank you for your comment, I have turnoff Web Shield's feature in  Avast. This issue has resolved.

<img width="1120" alt="Screen Shot 2020-12-03 at 18 43 48" src="https://user-images.githubusercontent.com/4075787/100992406-7d182400-3597-11eb-83cc-6a2dcad506f9.png">

**Comment by quentin7b** [comment]
Same here with AVG, need to disable Web Shield

**Comment by yashmittalJTG** [comment]
i dont have any defender or blocker installed in my mobile but console.firebase is still reporting crash 
:Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Future already completed
       at _AsyncCompleter.complete(_AsyncCompleter.java)
       at _WebViewPageState.<fn>(_WebViewPageState.java:213)
       at _WebViewState._onWebViewPlatformCreated(_WebViewState.java:442)
       at SurfaceAndroidWebView.<fn>(SurfaceAndroidWebView.java:120)
       at AndroidViewController.create(AndroidViewController.java:753)
       at .suspension>(.java)

**Comment by yashmittalJTG** [comment]
i dont have any defender or blocker installed in my mobile but console.firebase is still reporting crash
:Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Future already completed
at _AsyncCompleter.complete(_AsyncCompleter.java)
at _WebViewPageState.(_WebViewPageState.java:213)
at _WebViewState._onWebViewPlatformCreated(_WebViewState.java:442)
at SurfaceAndroidWebView.(SurfaceAndroidWebView.java:120)
at AndroidViewController.create(AndroidViewController.java:753)
at .suspension>(.java
