### ISSUE TITLE
Neither user 10167 nor current process has android.permission.ACCESS_NETWORK_STATE

### ISSUE THREAD

**Issue by dengjack** [flutter/flutter#71645]

**Comment by dengjack** [comment]
use connectivity 2.0.2  error
Neither user 10167 nor current process has android.permission.ACCESS_NETWORK_STATE

in manifest 
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by darshankawar** [comment]
@dengjack 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
