### ISSUE TITLE
Failed to extract manifest from APK: ProcessException: The command failed

### ISSUE THREAD

**Issue by MohiniThakkar1995** [flutter/flutter#71647]
I have just created one project in VS studio for flutter, and when i try to run the project, i'm getting error.
Error :
Failed to extract manifest from APK: ProcessException: The command failed
Command: D:\SDK_NEW\sdk\build-tools\29.0.3\aapt dump xmltree E:\button_click_demo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

I have created flutter project from android studio and got same error, can someone please give me solution for this issue, i'm stuck with this error since last 2 days.

Please find the screen shot of error which i'm getting
https://prnt.sc/vuxqk8

**Comment by hello-addweb** [comment]
Try below : 
1. `flutter clean `

then do next : 
- In the android studio 'File->Invalidate Caches/Restart'.
After that run your application.

**Comment by MohiniThakkar1995** [comment]
Tried the same, but still getting same error. @hello-addweb

**Comment by MohiniThakkar1995** [comment]
When i open android module separate, it's working fine. But when i run as flutter project it's giving me this error.
So can you please provide any other solution which can work in my case? @hello-addweb

**Comment by darshankawar** [comment]
@MohiniThakkar1995 
There's similar open issue describing your case, [50677](https://github.com/flutter/flutter/issues/50677)
Please follow-up there for updates and any questions.
Closing this as duplicate.
