### ISSUE TITLE
First install and open ios app release version,every screen will jank fisrt time open,but will be smooth on next time.And close 、reopen app will perfom normal!Android perform well all the time!

### ISSUE THREAD

**Issue by 1232209** [flutter/flutter#71643]
## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

**Comment by 1232209** [comment]
#60315

**Comment by adeolaex** [comment]
Hey @1232209. You can follow up over at #61450 and/or #32170

Feel free to close the issue if that helps.

**Comment by 1232209** [comment]
> Hey @1232209. You can follow up over at #61450 and/or #32170
> 
> Feel free to close the issue if that helps.

Thank you for your reminder. I have read these two issues, but it seems that this issue is not resolved now. My app has been transferred to the test, I think this will not pass.

**Comment by adeolaex** [comment]
Yeah the issue hasn't been resolved sadly.

**Comment by 1232209** [comment]
> Yeah the issue hasn't been resolved sadly.

I heard my friends say that there will be no problems after publishing the app to the app store. Do you know the relevant information? Also, do you know the progress of this problem? This problem seems to have appeared for a long time. Does the official say in which version it will be fixed?

**Comment by adeolaex** [comment]
No let me clarify. Even if your application has a startup jank or jank in general, it won't be rejected on either app stores.

As for an estimate for the fix, I don't think the Flutter team has given any **solid** news on that. Although you can try using [#61450 (comment)](https://github.com/flutter/flutter/issues/61450#issuecomment-709907845) to reduce the jank for now.

**Comment by adeolaex** [comment]
> > Yeah the issue hasn't been resolved sadly.
> 
> I heard my friends say that there will be no problems after publishing the app to the app store. Do you know the relevant information? Also, do you know the progress of this problem? This problem seems to have appeared for a long time. Does the official say in which version it will be fixed?

No let me clarify. Even if your application has a startup jank or jank in general, it won't be rejected on either app stores.

As for an estimate for the fix, I don't think the Flutter team has given any **solid** news on that. Although you can try using [#61450 (comment)](https://github.com/flutter/flutter/issues/61450#issuecomment-709907845) to reduce the jank for now.

**Comment by 1232209** [comment]
OK，thanks
