### ISSUE TITLE
Flutter not detecting android studio and intellij idea and android studio plugins

### ISSUE THREAD

**Issue by ahmedrabeasmaha** [flutter/flutter#71658]
I use ubuntu i have downloaded
ideauIU-2020.3.tar.gz
and
android-studio-ide-201.6953283-linux.tar.gz
and
flutter_linux_1.22.4-stable.tar.gz
I have extract idea and android studio and flutter to
```
/home/$USERNAME/Files
```
When i run
```
flutter doctor - v
```
in terminal
I get that android not installed as this
```
[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
```
I used this command
```
flutter config --android-studio-dir=/home/$USERNAME/android-studio
```
Flutter found android studio but the problem flutter not found android studio plugin and not found intellij idea

**Comment by TahaTesser** [comment]
Hi @ahmedrabeasmaha 
Plugins not being detected won't affect Flutter functionality, check out https://github.com/flutter/flutter/issues/67986#issuecomment-715452201
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ahmedrabeasmaha** [comment]
And i said the flutter didn't detecting intellij idea not intellij idea plugins

**Comment by ahmedrabeasmaha** [comment]
> Hi @ahmedrabeasmaha
> Plugins not being detected won't affect Flutter functionality, check out [#67986 (comment)](https://github.com/flutter/flutter/issues/67986#issuecomment-715452201)
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you

And i said the flutter didn't detecting intellij idea not intellij idea plugins answer or don't play with open and close button

**Comment by TahaTesser** [comment]
`flutter config --android-studio-dir=/home/$USERNAME/android-studio` should solve the  Android studio/intellij not being detected   and you confirmed 

> Flutter found android studio but the problem flutter not found android studio plugin and not found intellij idea

**Comment by ahmedrabeasmaha** [comment]
> `flutter config --android-studio-dir=/home/$USERNAME/android-studio` should solve the Android studio/intellij not being detected and you confirmed it.
> 
> > Flutter found android studio but the problem flutter not found android studio plugin and not found intellij idea

You didn't add any thing new flutter didn't detect intellij idea

**Comment by TahaTesser** [comment]
@ahmedrabeasmaha 
Can you please switch to the beta channel, it should detect both IDEs 
Thanks
