### ISSUE TITLE
Fail to connect to service protocol: http://127.0.0.1:52683/eNHj5XhYzRs=/

### ISSUE THREAD

**Issue by marcoramosw** [flutter/flutter#71650]
## Steps to Reproduce

1. flutter run "app name"

[  +38 ms] package:com.example.example
[   +2 ms] executing: C:\Users\mramos\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat /data/local/tmp/sky.com.example.example.sha1
[  +31 ms] f18940528e9bae85fadf6eaf95159845b1e58531
[   +1 ms] Latest build already installed.
[        ] sdk gphone x86 startApp
[   +2 ms] executing: C:\Users\mramos\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.example/com.example.example.MainActivity
[  +40 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +530 ms] Observatory URL on device: http://127.0.0.1:34227/eNHj5XhYzRs=/
[   +1 ms] executing: C:\Users\mramos\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:34227
[  +27 ms] 52683
[        ] Forwarded host port 52683 to device port 34227 for Observatory
[   +4 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://127.0.0.1:52683/eNHj5XhYzRs=/
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[+130074 ms] Fail to connect to service protocol: http://127.0.0.1:52683/eNHj5XhYzRs=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:52683/eNHj5XhYzRs=/ws
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:52683/eNHj5XhYzRs=/
[  +11 ms] "flutter run" took 136,961ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[  +97 ms] ensureAnalyticsSent: 91ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[        ] exiting with code 2

**Comment by darshankawar** [comment]
@marcoramosw 
Please provide `flutter doctor -v` and `flutter run --verbose`. Also check out [this](https://github.com/flutter/flutter/issues/47204#issuecomment-571878888) issue comment to see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
