### ISSUE TITLE
[iOS]TextField does not delete charactor correctly while pressing keyboard delete button

### ISSUE THREAD

**Issue by icespring** [flutter/flutter#71655]
## Steps to Reproduce

1. build a flutter app with any TextFiled.
2.insert some charactors in the TextFiled.
3.move the cursor to the very front of the text.
4.hold press the keyboard's delete button when touch the end of the text so that the cursor moves to the end of the text
5.it wouldn't delete any charactor

min reproduced code 
```
         Scaffold(
            body: Center(
              child: TextField(

              ),
            ),
          );
```

flutter doctor -v 

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/icespring/bin/flutter
    • Framework revision 8af6b2f038 (5 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/icespring/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/icespring/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[!] Android Studio (version 4.1)
    • Android Studio at /Users/icespring/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • “icespring”的 iPhone • 00008020-000565163A79002E • ios • iOS 14.0

**Comment by darshankawar** [comment]
@icespring 
You seem to be on obsolete version of Flutter. Current stable version is 1.22.4. I'd recommend you to upgrade to latest and try again to see if issue persists or works as expected.
Thanks.

**Comment by icespring** [comment]
Hi @darshankawar 
I have upgraded to the latest version. It seems this issue is still there.  

ps. from keyborad side, when touch to the end of text, `textDidChanged` callback won't be invoked 

```
[✓] Flutter (Channel stable, 1.22.5-0.0.pre.1, on Mac OS X 10.15.7 19H15
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5-0.0.pre.1 at /Users/icespring/bin/flutter
    • Framework revision b441cac054 (18 hours ago), 2020-12-03 16:11:17 +0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/icespring/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • “icespring”的 iPhone (mobile) • 00008020-000565163A79002E • ios • iOS 14.0

```

**Comment by darshankawar** [comment]
@icespring 
I am unable to replicate the issue using latest stable version (1.22.4) and using iPhone SE Simulator (OS 14). Can you provide video of the issue ?
Also, I see that you are on `Channel stable, 1.22.5-0.0.pre.1`, but latest stable is 1.22.4, not sure how did you end up on that version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
