### ISSUE TITLE
Add a "blacklisted methods" test

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#7166]
The following async file I/O methods should never be called -- they create undue overhead in the async wiring required to accomplish them, and their corresponding sync versions require minimal overhead.

- [ ] `File.lastModified()`
- [ ] `FileSystemEntity.isDirectory()`
- [ ] `FileSystemEntity.isFile()`
- [ ] `FileSystemEntity.isLink()`
- [ ] `FileSystemEntity.type()`
- [ ] `FileSystemEntity.exists()`
- [ ] `FileSystemEntity.stat()`

We should convert all existing uses of these methods (in flutter_tools - we don't use them in the framework) to use the sync versions, and we should add a test that ensures we don't re-introduce them.  Over time, if any other such methods come up, we can just add them to this method blacklist.

@johnmccutchan

**Comment by Hixie** [comment]
We should definitely either always use one or always use the other.

Having said that, some people use NFS, and NFS can take a _long_ time to return from these calls...

**Comment by danrubel** [comment]
Landed a new lint to [discourage use of specific async i/o methods](https://github.com/dart-lang/linter/commit/42e227ad7268a569418349bc4cbbd04dcec220)

**Comment by johnmccutchan** [comment]
@danrubel nice!

**Comment by Hixie** [comment]
I was running the linter over some code recently and ran into this lint.

I'm not convinced this is actually a good idea. Won't these methods risk entirely locking up the app when run on networked file systems or file systems with bad disks?

**Comment by tvolkert** [comment]
They'll lock up the app to the extent that the syscalls hang (whereas with async, we could add a timeout).  So bottom-line: yes.

That said, for local disk access, what spawned this issue is that @johnmccutchan and I were seeing real slowdowns in the Flutter tool due to the use of these async ops (in loops, for instance) -- where converting to sync calls saved a few hundred milliseconds.

**Comment by Hixie** [comment]
A difficult trade-off. We definitely have users on NFS, but we also have many users on local disks...
