### ISSUE TITLE
Samsung devices on Android 9 do not show a proper date/time keyboard - most noticeable with the missing / character needed for proper date input.

### ISSUE THREAD

**Issue by GenuineRex** [flutter/flutter#71670]
https://github.com/flutter/flutter/blob/c5f8edd9eeabafc0458c98e51433ba8d44d5c997/packages/flutter/lib/src/material/input_date_picker_form_field.dart#L246

See https://github.com/material-components/material-components-android/issues/682 for similar issue and fix in android components.

**Comment by TahaTesser** [comment]
Hi @GenuineRex 
Is it specific to Android 9? Have you experienced it on others Android versions on Samsung devices? 
this [comment](https://github.com/material-components/material-components-android/issues/682#issuecomment-707902546) says there are versions who have this issue
What Samsung device are you using for testing on Android? 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mbalmer** [comment]
This is still the case.  My Galaxy Tab A shows a numeric only keyboard when I select datetime as the keyboard type.  So no ':' to separate hours from minutes.

Flutter stable channel, updated to the latest release.

**Comment by TahaTesser** [comment]
@mbalmer 
This issue is closed, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
