### ISSUE TITLE
Text styling discrepencies between CanvasKit and DOMCanvas

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter#71673]
```dart
              SelectableText.rich(
                TextSpan(
                    children: List.generate(
                  8,
                  (index) =>
                      TextSpan(text: 'TEST $index\n', style: Theme.of(context).textTheme.bodyText1.merge(fonts[index])),
                )),
              ),
```
![image](https://user-images.githubusercontent.com/7407478/101078169-71842780-35ae-11eb-987c-ec1804901698.png)

Left is normal DOMCanvas, and the right is `--dart-define=FLUTTER_WEB_USE_SKIA=true`

Not only is there padding differences, but the normal dom canvas seems blurry.

```
Flutter 1.24.0-10.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (2 weeks ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)
```

This is easily reproducible, just have any RichText or SelectableText.rich widget with any text inside. The theme doesn't matter, although I did notice that it defaults to a red color until you specify Theme.of(context).textTheme.bodyText1 (or whatever texttheme you have)

Here's a full app you can try:
```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SelectableText.rich(
      TextSpan(
        children: List.generate(
            8,
            (index) => TextSpan(
                text: 'TEST $index\n',
                style: Theme.of(context).textTheme.bodyText1)),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @SwissCheese5 
I can reproduce the issue 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/70479
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
