### ISSUE TITLE
Flutter Plugin Added in Android Studio but Flutter doctor Shows error

### ISSUE THREAD

**Issue by Abdullah-Sheikh** [flutter/flutter#71681]
I clone the stable version of Flutter from Github and Add Dart and Flutter plugin in Android studio and Intellji Idea.
but when I run :
```flutter doctor```
it shows the Dart and Flutter plugins are not install in Android Studio.
<img width="822" alt="Screenshot 2020-12-04 at 2 03 45 AM" src="https://user-images.githubusercontent.com/62107887/101088840-16fec180-35d6-11eb-9721-3a680de6b611.png">

<img width="912" alt="Screenshot 2020-12-04 at 2 12 30 AM" src="https://user-images.githubusercontent.com/62107887/101088929-33026300-35d6-11eb-9915-4b5ebf0c3c7a.png">

**Comment by TahaTesser** [comment]
Hi @Abdullah-Sheikh 
Plugins not being detected won't affect Flutter functionality. Please check https://github.com/flutter/flutter/issues/67986#issuecomment-715452201 for more details
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
