### ISSUE TITLE
Slow shrine hero animations in debug build

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#7168]
@HansMuller @Hixie 

I looked into if there was any obvious performance bottleneck affecting shrine hero animations (shrine -> product order page). I've attached screenshots of the profile and then the profile with the assertion call expanded. There don't appear to be any obvious bottlenecks.

![slow-shrine-hero-1](https://cloud.githubusercontent.com/assets/224266/20935800/14be61e2-bb95-11e6-8867-f101d71337df.png)
![slow-shrine-hero-2](https://cloud.githubusercontent.com/assets/224266/20935801/14bf026e-bb95-11e6-9eb2-c1886305cbce.png)

**Comment by sethladd** [comment]
In production mode, on the devices I've tested with, I've seen that the first hero UP misses frames. Then, the second, third, etc hero UPs perform much better. See also: https://github.com/flutter/flutter/issues/5363

**Comment by Hixie** [comment]
My guess is that there's two things at work here; one is that we suddenly have to compile a bunch of code that hasn't run before (hence why it's better the second time), and the other is that when you first build a bunch of new widgets (e.g. the first page of the next route) we run a bunch of expensive O(N²) layout assertions.
