### ISSUE TITLE
Flutter command doesn't run

### ISSUE THREAD

**Issue by blob84** [flutter/flutter#71685]
Flutter doesn't execute commands, it give no output.
I tried deleting the lock file or downloading dart sdk.
If I run command on android studio I get the error: Waiting for another flutter command to release the startup lock.
![flutterhang](https://user-images.githubusercontent.com/231464/101093619-5bc92f00-35bb-11eb-994a-1340c3d57daa.png)

**Comment by darshankawar** [comment]
@blob84 
Please check out the official [documentation](https://flutter.dev/docs/get-started/install) on installing Flutter sdk and confirm you have followed the steps correctly.
`waiting for another flutter command` means some other flutter command is running in the background process. try to kill all background dart processes that might be running and then start afresh to see if it works.

https://stackoverflow.com/a/53573543

**Comment by Daring-Deekshith** [comment]
@blob84  Kindly check your Environment Variables Path. Make sure the Path of the Flutter SDK Bin is perfectly set it up.

**Comment by blob84** [comment]
I reinstalled flutter, now is working.

**Comment by darshankawar** [comment]
@blob84 Closing this as resolved based on your comment above.
Thanks.
