### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by AConteh33** [flutter/flutter#71682]
```bash
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 113 pos 12: '_positions.length == 1'
```

I keep receiving this error about scrollController i don even use it in my app

**Comment by TahaTesser** [comment]
Hi @AConteh33 
Please check out https://github.com/flutter/flutter/issues/62855#issuecomment-669132093
Are you using multiple scroll view?
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by AConteh33** [comment]
class _HomeTestState extends State<HomeTest> {

  final PageController _pageController = PageController();

  String pagesname = 'Ask Howl';

  String plustxt = 'Ask';

  int selectedpage;


  @override
  void initState() {
    super.initState();
  }


  


  setBottomBarIndex(index) {
    setState(() {
      selectedpage = index;
    });
  }

  void _onTappedBar(int value) {
    setState(() {
      selectedpage = value;
    });
    _pageController.jumpToPage(value);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: CustomBottomNavigationBar(
        iconList: [
          Icons.home,
          Icons.card_giftcard,
          Icons.pie_chart,
          Icons.person,
        ],
        onChange: (val) {
          setState(() {
            selectedpage = val;
          });
          _onTappedBar(val);
          setBottomBarIndex(val);
        },
        defaultSelectedIndex: 0,
      ),
      appBar: AppBar(
        backgroundColor: Colors.white,
        title: Center(
          child: TextLiquidFill(
            text: 'Ask Howl ',
            waveColor: Colors.orangeAccent,
            loadDuration: Duration(milliseconds: 6300),
            waveDuration: Duration(milliseconds: 1445),
            boxBackgroundColor: Colors.white,
            textStyle: TextStyle(
              fontSize: 21.0,
              color: Colors.orangeAccent,
              fontWeight: FontWeight.bold,
            ),
            boxHeight: 300.0,
          ),
        ),
        actions: [
          Hero(
              tag: 'logo',
              child: Container(
                child: Image.asset('images/logo1.png'),
              )),
        ],
      ),
        drawer: AppDrawer(),
      floatingActionButton: FloatingActionButton(
          backgroundColor: Colors.orange,
          child: Text(plustxt),
          elevation: 0.1,
          onPressed: () {

            setState(() {
              if (selectedpage == 0){

                plustxt = 'Ask';

                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => Ask()));

              }else if(selectedpage == 1) {
                plustxt = 'Post';
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => PostonWall()));

              }else if(selectedpage == 2){
                plustxt = 'Add';
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => Ask()));
              }else if (selectedpage == 3){
                plustxt = 'Edit';
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => EditProfile()));
              }
            });

          }) ,
      body: Container(
        child:
            PageView(
                physics: NeverScrollableScrollPhysics(),
                onPageChanged: (pageIndex) {
                  setState(() {
                    selectedpage = pageIndex;
                  });
                },
                controller: _pageController,
                allowImplicitScrolling: false,
                children: <Widget>[
                  QuestionList(),
                  WallVs(),
                  Ask(),
                  Profile_OverView(),
                ],
              ),
      ),

    );

  }
}

**Comment by AConteh33** [comment]
Thank you so much for replying

**Comment by AConteh33** [comment]
I applied the code that was on the comment that you provided to me.
it seem to work at first but didn't when i went through the custom navigation.
it gets stuck even tho all of the listviews have a Controller

**Comment by AConteh33** [comment]
the doctor -v response

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\bObOx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • RMX2001 (mobile) • KJ5TGAMJPBV8LZVC • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @AConteh33 
Your code is incomplete and isn't minimal,  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
