### ISSUE TITLE
Log spam in tests due to failed attempts at loading ELF for fixtures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#71696]
The specific error is:
```
[ERROR:flutter/testing/elf_loader.cc(72)]
  App AOT file does not exist for this fixture.
  Attempts to launch the Dart VM with these AOT symbols will fail.
```

[This error is benign](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8861902876217066512/+/steps/Host_Tests_for_host_profile/0/stdout) but makes it hard to read logs while investigating unrelated failures on bots.

This was introduced with the recent change to split loading AOT code.

**Comment by chinmaygarde** [comment]
cc @GaryQian

**Comment by GaryQian** [comment]
Ahh, I'll remove this message, it is unnecessary.
