### ISSUE TITLE
Investigate hooks for exposing debug information relevant to engine developers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#71697]
The need for tools built on exposing information relevant to only engine developers (and subject to no stability guarantees) was raised in issue triage. We don't want to expose these over the service protocol as tools expecting stability of these API might be built which would lead to additional maintenance burden down the line. From conversations with @zanderso, the private namespace for service protocol extensions (by prepending an underscore to the extension name) is not enforced and widely ignored by tooling.

This is an open-ended issue exploring the need to for such tooling for engine developers.

**Comment by chinmaygarde** [comment]
cc @dnfield @zanderso

**Comment by jonahwilliams** [comment]
> private namespace for service protocol extensions (by prepending an underscore to the extension name) is not enforced and widely ignored by tooling.

A number of the "private" VM Service APIs are actually quite critical to the developer workflow (listViews, restart, et cetera); it seems more like a case of them never being graduated to full APIs and/or a bit of copy paste programming.

If the engine had actual private APIs I would certainly have no problem with enforcing a policy of not using them.

**Comment by chinmaygarde** [comment]
I didn't suggest that the private endpoints already used by tooling be restricted. I understand that these are necessary for vital workflows. It's just that once we expose an endpoint, there is no way for us to enforce the policy that that private namespaces not be used.

Maybe the `_` hint is too subtle? We could use something like `_flutter._engine._private`?

**Comment by dnfield** [comment]
Needed for https://github.com/flutter/engine/pull/22559

**Comment by jonahwilliams** [comment]
We're pulling Impeller stats out of the timeline now. That is as debug as it gets
