### ISSUE TITLE
Use html to replace  Widget build(BuildContext context)

### ISSUE THREAD

**Issue by wch1618** [flutter/flutter#71698]
![1](https://user-images.githubusercontent.com/33046233/101107969-77a9f080-360e-11eb-92aa-fb5d8980f52b.gif)

**Comment by TahaTesser** [comment]
Hi @wch1618 
Not sure if this is a proposal dart with HTML and why? Nevertheless, doesn't sound like a valid proposal.
Closing, as invalid proposla. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wch1618** [comment]
OK，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Taha Tesser"<notifications@github.com&gt;; 
发送时间: 2020年12月4日(星期五) 下午4:14
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "Look"<692251618@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] Use html to replace  Widget build(BuildContext context) (#71698)





 
Closed #71698.
 
&mdash;
