### ISSUE TITLE
Reduce the timeout on the web engine builders

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#71692]
The timeout was temporarily increased to 90 minutes because the web build is not sharded. When we move to a sharded build, we should reduce the timeout back to 1 hour.

**Comment by godofredoc** [comment]
@nturgut can we close this one?

**Comment by nturgut** [comment]
Yes, but we need to roll back this change first: https://github.com/flutter/infra/pull/283/files

**Comment by nturgut** [comment]
@godofredoc I assigned the issue back to you to revert the PR. Please let me know if there is anything I can help!

**Comment by godofredoc** [comment]
Sounds good I thought it was already reverted. Let me send the change to close it.

**Comment by godofredoc** [comment]
Sent the change for review

**Comment by godofredoc** [comment]
This is the PR reverting the original change:

https://github.com/flutter/infra/pull/295
