### ISSUE TITLE
Raised button not detect gesture when using RenderShiftedBox

### ISSUE THREAD

**Issue by saravanakumar007** [flutter/flutter#71706]
I have raised button which has been placed into the SingleChildRenderObjectWidget and child parentData offset value has been changed in performlayout method. When I touch on raisedbutton , onPressed event is not triggered,

Please find the below code  

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            decoration: BoxDecoration(color: Colors.red),
            child: ChartRenderObject(
                child: RaisedButton(
                    child: Text('Flutter'),
                    onPressed: () {
                      print('trigger');
                    }))));
  }
}

class ChartRenderObject extends SingleChildRenderObjectWidget {
  ChartRenderObject({Key key, Widget child}) : super(child: child, key: key);

  @override
  RenderObject createRenderObject(BuildContext context) {
    return ChartRenderBox();
  }

  @override
  void updateRenderObject(
      BuildContext context, covariant RenderObject renderObject) {
    super.updateRenderObject(context, renderObject);
  }
}

class ChartRenderBox extends RenderShiftedBox {
  ChartRenderBox({RenderBox child}) : super(child);

  @override
  bool hitTest(BoxHitTestResult result, {Offset position}) {
    return hitTestChildren(result, position: position);
  }

  @override
  void performLayout() {
    child.layout(constraints, parentUsesSize: true);
    size = constraints.constrain(Size(child.size.width, child.size.height));
    if (child.parentData is BoxParentData) {
      final BoxParentData childParentData = child.parentData;
      childParentData.offset = Offset(200, 200);
      // final Matrix4 transform = child.getTransformTo(this);
      // transform.translate(childParentData.offset.dx, childParentData.offset.dy);
      // child.applyPaintTransform(child, transform);
    }
  }
}

**Comment by pedromassangocode** [comment]
Hi @saravanakumar007 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by saravanakumar007** [comment]
Hi @pedromassangocode,

Sorry for the delay,


[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.1 at D:\Flutter Work Development\Flutter SDK\flutter
    • Framework revision f30b7f4db9 (3 months ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\SaravanaKumarKanagav\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\SaravanaKumarKanagav\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\SaravanaKumarKanagav\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

Thanks

**Comment by pedromassangocode** [comment]
Hi @saravanakumar007 
Can you please upgrade Flutter to the latest stable version?
If the issue persists please provide your `flutter doctor -v`.
Thank you
