### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "streamListen".

### ISSUE THREAD

**Issue by Zhaimm** [flutter/flutter#71703]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=f9f26d7759236eb95ba310a41710228aca9f7f28 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: The client closed with pending request "streamListen".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.336, on Mac OS X 10.15.6 19G2021 x86_64, locale zh-Hans-CN)
    • Flutter version 1.22.0-10.0.pre.336 at /Users/BCT-iMac/flutter
    • Framework revision 192f9e5eb4 (2 months ago), 2020-09-23 17:27:06 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/BCT-iMac/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Zhaimm的 iPhone (mobile)       • f9f26d7759236eb95ba310a41710228aca9f7f28 • ios • iOS 14.0
    • iPhone 11 Pro Max (mobile) • 5A1597F2-5FBA-49A5-8B6F-EDCC0FC6E0DB     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Zhaimm的 iPhone is busy: Copying cache files from device. Xcode will continue when Zhaimm的 iPhone is finished. (code -10)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.2.4+2012032
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 192f9e5eb43bd2e3e5e7eaacbf2a0d2980dd7340
### Plugins
image_picker_saver-065338f1549ff9f2001b466877b5fef7dffa6d69
image_pickers-131b4f5908bd0a53af2e75b541db05304a06e8e6
city_pickers-0.1.30
connectivity-0.4.9+3
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+5
device_info-0.4.2+8
flutter_alibc-0.0.15
flutter_kepler-0.0.1
flutter_webview_plugin-0.3.11
fluttertoast-3.1.3
fluwx-2.3.0
imei_plugin-1.2.0
jpush_flutter-0.1.0
jverify-0.6.22
ota_update-2.4.1
package_info-0.4.3
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
sqflite-1.3.1+1
unique_ids-1.0.10
url_launcher-5.7.1
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1
video_player-0.10.12+4
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.24

**Comment by pedromassangocode** [comment]
Hi @Zhaimm 
It looks like you are using an old version of Flutter.
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
