### ISSUE TITLE
Flutter driver is unable to close application instance after all tests are passed

### ISSUE THREAD

**Issue by asifnawaz1123** [flutter/flutter#71710]
@asifnawaz2311 it's not really related to the workaround I posted. It's some other issue with flutter driver. I think we should report it as a separate ticket, so it get resolved in the driver.

As a quick workaround I added to `tearDownAll`:

    await Future.delayed(Duration(seconds: 1), () => exit(0));

But that will mark all your builds as passed, because it returns 0. To implement it properly the logic is going to be much more complicated, that's a wrong thread to discuss it

_Originally posted by @tomrozb in https://github.com/flutter/flutter/issues/42433#issuecomment-738615532_

**Comment by asifnawaz1123** [comment]
I am unable to stop application instance and it get stuck here and don't end the test execution. There is no solution anywhere to this
![bug](https://user-images.githubusercontent.com/67258281/101140421-c2d6fa00-3634-11eb-8660-543a17d26127.png)

**Comment by TahaTesser** [comment]
Hi @asifnawaz1123 
Can you please provide your `flutter doctor -v` your `flutter driver -t test_driver/example.dart --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by asifnawaz1123** [comment]
sure @TahaTesser 
**flutter doctor -v**
`[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-PK)
    • Flutter version 1.22.4 at G:\DevTools\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at G:\DevTools\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = G:\DevTools\Sdk
    • Java binary at: G:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at G:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!`

My **app_test.dart**
`// Imports the Flutter Driver API.

import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
import 'methods/MainIsolate.dart';

void main() {
  group('SMA App', () {
    FlutterDriver driver;

    setUpAll(() async {
      print('Connecting driver');
      final mainIsolate = await getMainIsolate();
      await mainIsolate.loadRunnable();
      driver = await FlutterDriver.connect(isolateNumber: mainIsolate.number);
      await Future.delayed(Duration(seconds: 10));
      print('Driver connected');
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
      print('driver closing..');
    });

    //Test for flutter Driver Health
    test('check flutter driver health', () async {
      await driver.clearTimeline();
      await driver.runUnsynchronized(() async {
        print('flutter driver health test started');
        Health health = await driver.checkHealth();
        print(health.status);
        print('flutter driver health test finished');
      });
    }, timeout: Timeout(Duration(minutes: 1)));
  });
}`


**MainIsolate.dart** used to get the driver, which I was not able to get previously

`import 'dart:io';

import 'package:flutter_driver/flutter_driver.dart';
import 'package:vm_service_client/vm_service_client.dart';

Future<VMIsolateRef> getMainIsolate() async {
  final dartVmServiceUrl = Platform.environment['VM_SERVICE_URL'];
  final VMServiceClientConnection connection = await vmServiceConnectFunction(
    dartVmServiceUrl,
    headers: <String, dynamic>{},
  );
  final VMServiceClient client = connection.client;
  final VM vm = await client.getVM();
  print("Available isolates:");
  vm.isolates.forEach((element) {
    print("Isolate: ${element.name} ${element.number}");
  });
  return Future.value(
    vm.isolates.firstWhere((VMIsolateRef isolate) => isolate.name == "main"));
}


`

**Comment by asifnawaz1123** [comment]
Any updates related this issue? @TahaTesser

**Comment by TahaTesser** [comment]
Hi @asifnawaz1123 
I can reproduce the issue, related https://github.com/flutter/flutter/issues/66917

<details> 
<summary>logs</summary> 

```bash
Starting application: test_driver/app.dart
"build/app/outputs/flutter-apk/app.apk" does not exist.
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        33.9s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.2s
I/flutter (28179): Observatory listening on http://127.0.0.1:38383/w0du6oLVgFk=/
00:00 +0: SMA App (setUpAll)

Connecting driver

Available isolates:

Isolate: main 2882238128866227

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:52511/w0du6oLVgFk=/
VMServiceFlutterDriver: Isolate found with number: 2882238128866227
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
Driver connected

00:14 +0: SMA App check flutter driver health

flutter driver health test started

HealthStatus.ok

flutter driver health test finished

00:15 +1: SMA App (tearDownAll)

driver closing..

00:15 +1: All tests passed!


```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

</details>

However when I try to reproduce the same on the beta channel, I can `vm_service_client` error, I looked up and it's [discontinued](https://pub.dev/packages/vm_service_client) 

Can you please use the alternative provided and  try if it reproduces on the beta or master channel?
`This package is DISCONTINUED. Use package:vm_service instead.`

If the reproduces with alternative as well, please provide an updated code sample
Thanks

**Comment by asifnawaz1123** [comment]
I have used `package:vm_service/vm_service.dart
` and tried the same thing to resume isolate if they are paused and also I have call dispose method to shutdown the vmservice, Now My test are running on codemagic and also ending application instance when all test are executed. @TahaTesser thankyou for suggesting **package:vm_service** , I am posting the code to implement this:

```
// Imports the Flutter Driver API.

import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
import 'package:vm_service/vm_service_io.dart';
import 'package:vm_service/vm_service.dart';

void main() {
  group('SMA App', () {
    FlutterDriver driver;
    VmService serviceClient;

    setUpAll(() async {
      print('Connecting driver');
      String dartVmServiceUrl = Platform.environment['VM_SERVICE_URL']
              .replaceFirst(new RegExp(r'http:'), 'ws:') +
          "ws";
      
      serviceClient = await vmServiceConnectUri(dartVmServiceUrl);
      final VM vm = await serviceClient.getVM();
      vm.isolates.forEach((element) {
        print("Isolate: ${element.name} ${element.number}");
      });
      final mainIsolate = vm.isolates
          .firstWhere((IsolateRef isolate) => isolate.name == "main");
      await serviceClient.resume(mainIsolate.id);
      driver = await FlutterDriver.connect(
      isolateNumber: int.parse(mainIsolate.number));
      print('Driver connected');
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
      print('driver closing..');
      serviceClient.dispose();
      await serviceClient.onDone;
      print('service client shut down');
    });

    //Test for flutter Driver Health
    test('check flutter driver health', () async {
      await driver.clearTimeline();
      await driver.runUnsynchronized(() async {
        print('flutter driver health test started');
        Health health = await driver.checkHealth();
        print(health.status);
        print('flutter driver health test finished');
      });
    }, timeout: Timeout(Duration(minutes: 1)));
  });
}
```

**Comment by TahaTesser** [comment]
hI @asifnawaz1123 
Glad to help, I can also confirm, instance is closed after all test are passed

<details> 
<summary>logs</summary> 

```bash
tahatesser@Tahas-MacBook-Pro stable_flutter % flutters drive --target=test_driver/app.dart -d rmx
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 4.3s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         5.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter (19950): Observatory listening on http://127.0.0.1:43943/RR3MaBduyMM=/
00:00 +0: SMA App (setUpAll)

Connecting driver

Isolate: main 3562916069783579

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50783/RR3MaBduyMM=/
VMServiceFlutterDriver: Isolate found with number: 3562916069783579
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
Driver connected

00:03 +0: SMA App check flutter driver health

flutter driver health test started

HealthStatus.ok

flutter driver health test finished

00:03 +1: SMA App (tearDownAll)

driver closing..

service client shut down

00:03 +1: All tests passed!

Stopping application instance.
tahatesser@Tahas-MacBook-Pro stable_flutter % 
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
