### ISSUE TITLE
VS Code Flutter hot reload hangs

### ISSUE THREAD

**Issue by GeorgeKnap** [flutter/flutter#71716]
After editing code , vsocde shows popup `Performing Hot Reload...` which hangs there indefinitely. App doesn't get realoded and I need to restart debugging manually. No error is logged in debug console.

possibly relates to this [#67194](https://github.com/flutter/flutter/issues/67194)

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.21, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.23.0-8.0.pre.21 at C:\flutter\flutter
    • Framework revision ec40df9576 (10 weeks ago), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jirka\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\jirka\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Mi 9 SE (mobile) • 77823bad • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @GeorgeKnap 
Does it only reproduce it in VS Code or also on the terminal?
Can you consistently reproduce the issue? For [example](https://github.com/flutter/flutter/issues/71560#issuecomment-737774890)
 Does it reproduce with a different or emulator?  Web or mobile?
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pontiac1-1** [comment]
> Hi @GeorgeKnap
> Looks like you're running 10 weeks old `master` channel, for master it is quite an old version
> Can you please upgrade to the latest `master` and try again
> `flutter channel master`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> Does it only reproduce it in VS Code or also on the terminal?
> Can you consistently reproduce the issue? For [example](https://github.com/flutter/flutter/issues/71560#issuecomment-737774890)
> Does it reproduce with a different or emulator? Web or mobile?
> Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

Hi @TahaTesser 
I am too experiencing this issue! It feels like this bug is project specific as it appears no matter what emulator, which editor im using, if i run it in vs code, android studio or in the terminal, using a physical device results the same...

**Comment by GeorgeKnap** [comment]
@TahaTesser 
Latest master caused the same problems, however after downgrading to stable flutter branch hot realod in vscode works again as expected.

**Comment by crivatz11** [comment]
I'm on the stable channel, version 2.0.2 and I'm experiencing the same issue.

**Comment by TahaTesser** [comment]
@crivatz11 
please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

**Comment by siva636** [comment]
I am also experiencing the same issue, my `flutter doctor -v` as follows:
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-LK)
    • Flutter version 2.0.6 at /Applications/flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/siva/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```
