### ISSUE TITLE
webview_flutter , platformview consumes a lot of memory in ios

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#71719]
when use webview_flutter or widgets depends on platformview, it will consume about 150M memory; but use webview in ios directory by objectC, it comsumes only 15M meomory;
why does platformview use so much memory; as my app need to show native views by using platformview, then it crashes for short of memory;

is there any plan to optimize it?

**Comment by TahaTesser** [comment]
Hi @wanjm 
There are a couple of issues trying to address this issue
https://github.com/flutter/flutter/issues/62579
https://github.com/flutter/flutter/issues/47992

Please follow up on these issues I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wanjm** [comment]
i am focus on the memory platformview consumed. it cost 150m memory when created. webview is just one case for platformview

**Comment by wanjm** [comment]
#46666 is has the similar problem ; it is different from memory leak;

**Comment by TahaTesser** [comment]
@wanjm 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by wanjm** [comment]
@TahaTesser  is there official guide for how much memory should each  webview_flutter use;
