### ISSUE TITLE
flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by subaharan** [flutter/flutter#71712]
flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error: 'Flutter/Flutter.h' file not found

Not able to take build in Ios

**Comment by TahaTesser** [comment]
Hi @subaharan 
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/70895
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
