### ISSUE TITLE
Idea for Showcase

### ISSUE THREAD

**Issue by markmusic2727** [flutter/flutter#71727]
Hi, I'm [Mark](https://twitter.com/home). I've been a massive fan of Flutter/Dart for almost a year now. About a month ago, I started to work on [Safe](https://www.safelabs.app/), a powerful tool for personal and community safety. We tried to use React-Native but Flutter was just way better for the job. I know you guys are currently trying to showcase cool projects built with Flutter. If you guys would like to showcase Safe, feel free to!

Reach out to me at: mark@safelabs.app

**Comment by iapicca** [comment]
@markmusic2727 
it would be nice if the flutter would be mentioned in your [webisite](https://www.safelabs.app/) or your [press kit](https://www.safelabs.app/press-kit)

**Comment by darshankawar** [comment]
@markmusic2727 
It would be great if you could reach out / tweet this to Flutter's official handle https://twitter.com/FlutterDev. 
This repo is used to keep track of bugs and feature requests for Flutter framework. I am going ahead and closing this from here.
