### ISSUE TITLE
[Crash] Native crash at pthread_mutex_lock) (BuildId: @@@] : Segmentation fault

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#71724]
https://buganizer.corp.google.com/issues/174525944. Reported from the field.

**Comment by chinmaygarde** [comment]
As far as we can tell, there is no reproducible case here and this is gathered from logs collected on device. @jason-simmons has a hypothesis that JNI weak refs can be made strong in the middle of finalization. He is going to change this to use Java weak refs instead. This change is still speculative. Changing priority to P3 to reflect the impact of this.

**Comment by enetor** [comment]
Internal bug b/174525944 is marked as P2 so marking this issue as P2 as well.

**Comment by chinmaygarde** [comment]
@enetor P2 is used for issues that are likely to be customer blockers and the priority levels here are not meant to be kept in sync with the priority level of the bug in the tracker that customer may use. So, is this a blocker? My reading of the bug did not make it seem like it was. Resetting the priority here. Please re-adjust as necessary.

**Comment by enetor** [comment]
@chinmaygarde That comment was generated from the internal bug_sync utility, not added manually by me. The oncall runs that tool weekly. If this isn't a blocking bug, please feel free to downgrade the internal bug accordingly. The oncall engineer isn't aware of much on GitHub. And I only found out this "at" mention by accident.

**Comment by bryanoltman** [comment]
No longer a blocking issue for customers: dream(g3) and money(g3)

**Comment by chinmaygarde** [comment]
The internal issue was obsoleted.
