### ISSUE TITLE
[Proposal][video_player]: Make Readme IOS Permissions optional

### ISSUE THREAD

**Issue by torbenkeller** [flutter/flutter#71731]
Why is there the recommendation to add this into the Podfile?

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
``` 

This can be a security nightmare for all Apps using this. Just have a look at this:
https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

Please remove this or mark it as `not recommended`

**Comment by darshankawar** [comment]
@torbenkeller 
Can you provide use case where you are facing any issue with above ?

**Comment by torbenkeller** [comment]
Oh Sorry, I just forgot to tell you the plugin this is from. It's the video player plugin: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player

So if you look into the readme, there is the advice to add this code snippet into the `Info.plist` file

**Comment by darshankawar** [comment]
@torbenkeller 
According to the `readme`, that settings `allows your app to access video files by URL.`.
Have you tried by removing that entry and then accessing the video url, to see if it works ?

**Comment by torbenkeller** [comment]
It depends on. When you already have permissions to visit the website where the video is stored, or it is a https connection, it works without it. But even if you need permissions because your server has only http, this snippet is granting way too much permissions.

> Apple strongly recommends against completely disable ATS by setting the `NSAllowsArbitraryLoads` key (https://developer.apple.com/forums/thread/3544?answerId=642411022#642411022)

It would be better to say:

When the video is stored on a server which can only be accessed by http then add this

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>example.com</key>
    <dict>
      <!--Include to allow subdomains-->
      <key>NSIncludesSubdomains</key>
      <true/>
      <!--Include to allow HTTP requests-->
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <!--Include to specify minimum TLS version-->
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>
```

**Comment by stuartmorgan** [comment]
This is actually a duplicate of https://github.com/flutter/flutter/issues/54955
