### ISSUE TITLE
firstDate and lastDate parameters in showDatePicker can be optional

### ISSUE THREAD

**Issue by SirusCodes** [flutter/flutter#71736]
## Use case

As currently `firstDate` and `lastDate` are required in `showDatePicker` but sometimes only one of them is required.

For example:
- If we want to get the birth date of a user then only the `lastDate` is needed to be set and `firstDate` could be left as null.
- For a future date where `lastDate` is unknown this could give a problem.

## Proposal

Making `firstDate` and `lastDate` in `showDatePicker` as optional.

**Comment by preetshah21699** [comment]
Trust me, you don't want to leave them null. The user can select anything and your code may or may not be ready to handle it all. See, these parameters are kept as required so that people can validate the dates and there's a limited amount of options for years or months to select from.

**Comment by SirusCodes** [comment]
Yes got it a user can add dumb values like 99999999999🤦‍♂️
