### ISSUE TITLE
[devicelab] Fix datastore returning 0 tasks on LUCI runs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#71749]
We disabled upload metrics as there seems to be an issue where Cocoon was not finding any related tasks. This requires investigation on the timing with LUCI to discover why we're not finding any corresponding tasks even when they should exist.

**Comment by CaseyHillers** [comment]
To get started, we need a full e2e LUCI builder in prod that is being stored in Cocoon datastore. We can mark it as flaky until we figure out this issue to not cause tree outages.

**Comment by CaseyHillers** [comment]
Issue is with the test runner. Cocoon is trying to create the following commit key:

`flutter/flutter/HEAD /b372c52b2f428c477cb0cdcff9a299ac633b279d`

The `gitBranch` param is wrong and has an extra space!

**Comment by CaseyHillers** [comment]
The issue is that HEAD makes sense the bot will check out a specific commit.

@christopherfujino do you know of a way I can collect the branch during a devicelab test run? Currently the runner uses `git rev-parse --abbrev-ref HEAD`

One idea I have is we can assume `master` if it returns HEAD, but i'm not sure how the release branch checkout process works.

**Comment by christopherfujino** [comment]
> The issue is that HEAD makes sense the bot will check out a specific commit.
> 
> @christopherfujino do you know of a way I can collect the branch during a devicelab test run? Currently the runner uses `git rev-parse --abbrev-ref HEAD`
> 
> One idea I have is we can assume `master` if it returns HEAD, but i'm not sure how the release branch checkout process works.

So are you saying that `git rev-parse --abbrev-ref HEAD` is returning `HEAD `?

**Comment by christopherfujino** [comment]
Per https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git, that (or the newer `git branch --show-current`) is the way to grab the branch name. I'm unclear on where `HEAD ` is coming from.

**Comment by CaseyHillers** [comment]
> So are you saying that git rev-parse --abbrev-ref HEAD is returning HEAD ?

Yes. My current thought is maybe infra has git in a detached state when it checkouts a commit on tip of tree. I'm not familiar with the git logic in Flutter recipes, so i'll need to investigate more.

I'll put up a PR to see if the newer command work.

**Comment by christopherfujino** [comment]
> > So are you saying that git rev-parse --abbrev-ref HEAD is returning HEAD ?
> 
> Yes. My current thought is maybe infra has git in a detached state when it checkouts a commit on tip of tree. I'm not familiar with the git logic in Flutter recipes, so i'll need to investigate more.

Ahh, yeah, if our HEAD is detached then we are not on a branch, so there's no (reliable) way to determine the channel.

**Comment by CaseyHillers** [comment]
> Ahh, yeah, if our HEAD is detached then we are not on a branch, so there's no (reliable) way to determine the channel.

Ah tricky. Do you know if this is also the case for the release branches in infra? If this is only on the main branch, I could add logic to default to master if HEAD is given.

**Comment by christopherfujino** [comment]
> > Ahh, yeah, if our HEAD is detached then we are not on a branch, so there's no (reliable) way to determine the channel.
> 
> Ah tricky. Do you know if this is also the case for the release branches in infra? If this is only on the main branch, I could add logic to default to master if HEAD is given.

we discussed offline, but for posterity, our LUCI recipes by default detach the HEAD to the desired commit. Post-submit, the branch is available to recipe as api.gitiles_commit.ref.

**Comment by CaseyHillers** [comment]
Recipes has the property `"branch": "refs/heads/master"`. We can pass this to the test runner to unblock the DeviceLab migration for now.

@christopherfujino do you have opinions on how I should pass this to the test runner? I think I want to have the recipe splice this to `master`, so nowhere else needs to worry about the git tiles format. However, I'm flexible on what should have the responsibility of cutting this to just master.

**Comment by christopherfujino** [comment]
> Recipes has the property `"branch": "refs/heads/master"`. We can pass this to the test runner to unblock the DeviceLab migration for now.
> 
> @christopherfujino do you have opinions on how I should pass this to the test runner? I think I want to have the recipe splice this to `master`, so nowhere else needs to worry about the git tiles format. However, I'm flexible on what should have the responsibility of cutting this to just master.

I would also rather have the recipe pass just the branch, so that the source repo doesn't need to know anything about gitiles. I just hope that the format is never anything other than `"refs/heads/$BRANCH_NAME"`...

**Comment by christopherfujino** [comment]
Per the protobuf:

```
// Commit ref, e.g. "refs/heads/master".
  | // NOT a branch name: if specified, must start with "refs/".
  | string ref = 4;
```

So I guess so?

https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/common.proto#154

**Comment by christopherfujino** [comment]
Actually, this is defined by whatever we set as refs when we create the pollers: https://github.com/flutter/infra/blob/master/config/framework_config.star#L76

```
    trigger_name = branch + "-gitiles-trigger-framework"
    luci.gitiles_poller(
        name = trigger_name,
        bucket = "prod",
        repo = repos.FLUTTER,
        refs = [testing_ref],
    )
```

And we map these to branch names, so it should be safe to chop off the beginning `refs/heads/` in the recipe.

**Comment by CaseyHillers** [comment]
Once the linked PR lands, we'll need to land this recipe CL to pass the branch:  https://flutter-review.googlesource.com/c/recipes/+/9160

**Comment by christopherfujino** [comment]
> Once the linked PR lands, we'll need to land this recipe CL to pass the branch: https://flutter-review.googlesource.com/c/recipes/+/9160

what about the cocoon agent code? isn't that also calling `//dev/devicelab/bin/run.dart`?

**Comment by CaseyHillers** [comment]
> what about the cocoon agent code? isn't that also calling //dev/devicelab/bin/run.dart?

Cocoon agent handles uploading to the backend in the agent. It has access to the task key which makes it trivial to do a backend update.

We refactored this logic in the test_runner and backend for LUCI runs. There's two separate update paths, and the changes here do not modify any of the agent paths.

**Comment by CaseyHillers** [comment]
The issue is that the key being constructed for `Commit` is not returning any commits.

Using the datastore GQL, `SELECT * FROM Checklist WHERE __key__ = KEY(Checklist, 'flutter/flutter/master/f172c827cb07f17666978d925d5d56be652db144')` does return commits.

Somewhere the backend query is having an issue.

**Comment by CaseyHillers** [comment]
Update from my debugging session:

Here are the bytes of the sha in datastore
```
[49, 50, 49, 57, 100, 100, 55, 98, 54, 50, 49, 52, 55, 102, 102, 97, 100, 55, 102, 101, 57, 99, 56, 97, 48, 99, 102, 52, 97, 48, 55, 50, 102, 97, 97, 55, 57, 97, 52, 100]
```

Here's the malformed sha being processed by the backend:
```
[49, 50, 49, 57, 100, 100, 55, 98, 54, 50, 49, 52, 55, 102, 102, 97, 100, 55, 102, 101, 57, 99, 56, 97, 48, 99, 102, 52, 97, 48, 55, 50, 102, 97, 97, 55, 57, 97, 52, 100, 10]
```

The diff is the processed sha has an additional byte at the end for `LF` (ASCII 10 = LF) What's weird is this does not show up in the log viewer.

We'll need to trim the input for whitespace before using it.
