### ISSUE TITLE
integration_test_macos plugin does not build

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#71758]
## Steps to Reproduce
```
$ cd ./packages/integration_test/example/
$ flutter build macos
```
Fails
```
[!] The name of the given podspec `IntegrationTestMacOS` doesn't match the expected one `integration_test_macos`
```

`integration_test_macos.podspec` name should be `integration_test_macos` instead of `IntegrationTestMacOS`.

https://github.com/flutter/plugins/blob/89794a635a5efad6705e3d7ccc29e8139318d947/packages/integration_test/integration_test_macos/macos/integration_test_macos.podspec#L5

**Comment by jmagman** [comment]
@dnfield Do you know why `integration_test_macos` is in the iOS-only `integration_test` directory?
https://github.com/flutter/plugins/tree/89794a635a5efad6705e3d7ccc29e8139318d947/packages/integration_test.  I was expecting something like
- integration_test
    - integration_test
    - integration_test_macos

or
- integration_test
    - ios
    - macos

but it's
- integration_test
    - ios
    - example
    - integration_test_macos
        - macos

**Comment by dnfield** [comment]
It was started as a federated plugin.

**Comment by jmagman** [comment]
@dnfield So should it look like https://github.com/flutter/plugins/tree/master/packages/path_provider with each platform as sibling directories?

**Comment by dnfield** [comment]
I think it'll look like that eventually yes - @stuartmorgan was looking at this

**Comment by stuartmorgan** [comment]
This is what a quick semi-federation looks like; it should indeed have been done one of the ways you listed, but instead the federated macos plugins was added inside the existing plugin.

We should just make that plugin not be federated. Also, the macOS implementation doesn't actually do anything; we could likely just remove it for now.
