### ISSUE TITLE
scrollOffsetCorrection 

### ISSUE THREAD

**Issue by hongdnn** [flutter/flutter#71763]

**Comment by iapicca** [comment]
@hongdnn 
please provide more details about the issue,
including your `flutter doctor -v` and a minimal reproducible code sample

**Comment by darshankawar** [comment]
@hongdnn 
There's no description of the issue, so we don't know if you are facing an issue or if you have a proposal / feature request related to `scrollOffsetCorrection`. Please provide above requested details.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
