### ISSUE TITLE
[PathProvider] Get access to "external" cache directory on Android

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#7176]
Currently `PathProvider` on Android provides access only to folder returned by `getCacheDir()`. However this folder is limited to 1MB. However for average application it is not enough to cache some data.  According to documentation:

> if your app requires a larger cache (larger than 1 MB), you should use getExternalCacheDir() instead.
https://developer.android.com/reference/android/content/Context.html#getCacheDir()

So it would be nice to have access to "external cache dir" additionally.

**Comment by eseidelGoogle** [comment]
For now you can expose that path via your own HostMessages/plugin.

**Comment by jaggs6** [comment]
@eseidelGoogle Would this be possible to add to use in cache_manager library?

**Comment by eseidelGoogle** [comment]
I don't know what you're asking @jaggs6.  What's cache_manager?  https://pub.dartlang.org/packages/flutter_cache_manager

**Comment by stuartmorgan** [comment]
This was added quite a while ago in https://github.com/flutter/plugins/pull/2049, but wasn't associated with this issue so didn't close it out.
