### ISSUE TITLE
Wrong link for ScrollableLazyList documentation

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#7177]
## Steps to Reproduce

Visit the [Widgets Overiew](https://flutter.io/widgets/) and scroll down to ScrollableLazyList, then click Documentation.  That Documentation link directs to [ScrollableList](https://docs.flutter.io/flutter/widgets/ScrollableList-class.html) but it should link to [ScrollableLazyList](https://docs.flutter.io/flutter/widgets/ScrollableLazyList-class.html).

**Comment by Hixie** [comment]
Those classes are gone now.
