### ISSUE TITLE
totalAmount is always zero

### ISSUE THREAD

**Issue by foxyharith** [flutter/flutter#71777]
Hello, 
I am working on a basic eCommerce app, now in this file, the double variable totalAmount is supposed to add the chosen items total amount, but it always ends up showing zero, any help is appreciated, thank you 

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:e_shop/Config/config.dart';
import 'package:e_shop/Address/address.dart';
import 'package:e_shop/Widgets/customAppBar.dart';
import 'package:e_shop/Widgets/loadingWidget.dart';
import 'package:e_shop/Models/item.dart';
import 'package:e_shop/Counters/cartitemcounter.dart';
import 'package:e_shop/Counters/totalMoney.dart';
import 'package:e_shop/Widgets/myDrawer.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:e_shop/Store/storehome.dart';
import 'package:provider/provider.dart';
import '../main.dart';

class CartPage extends StatefulWidget {
  @override
  _CartPageState createState() => _CartPageState();
}

class _CartPageState extends State<CartPage>
{
  double totalAmount;
  @override
  void initState() {
    super.initState();

    totalAmount = 0;
    Provider.of<TotalAmount>(context, listen: false).display(0);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton.extended(
        onPressed: ()
        {
          if(EcommerceApp.sharedPreferences.getStringList(EcommerceApp.userCartList).length == 1)
            {
              Fluttertoast.showToast(msg: "Your cart is empty");
            }
            else
              {
              Route route = MaterialPageRoute(builder: (c) => Address(totalAmount: totalAmount));
              Navigator.pushReplacement(context, route);
              }

        },
        label: Text("Check Out"),
        backgroundColor: Colors.pink,
        icon: Icon(Icons.navigate_next),
      ),
      appBar: MyAppBar(),
      drawer: MyDrawer(),
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Consumer2<TotalAmount, CartItemCounter>(builder: (context, amountProvider, cartProvider, c)
            {
              return Padding(
                padding: EdgeInsets.all(8.0),
                child: Center (
                  child: cartProvider.count ==0
                  ? Container()
                  : Text(
                    "Total Price: ${amountProvider.totalAmount.toString()}",
                        style: TextStyle(color: Colors.black, fontSize: 20.0, fontWeight: FontWeight.w500),
                  ),
                ),
              );
            },),
          ),
          StreamBuilder<QuerySnapshot>(
            stream: EcommerceApp.firestore.collection("items")
                .where("shortInfo", whereIn: EcommerceApp.sharedPreferences.getStringList(EcommerceApp.userCartList)).snapshots(),
            builder: (context, snapshot)
            {
              return !snapshot.hasData
                  ? SliverToBoxAdapter(child: Center(child: circularProgress(),),)
                  : snapshot.data.documents.length == 0
                  ? beginBuildingCart()
                  : SliverList(
                delegate: SliverChildBuilderDelegate(
                    (context, index)
                    {
                      ItemModel model = ItemModel.fromJson(snapshot.data.documents[index].data);

                      if(index == 0)
                        {
                          totalAmount = 0;
                          totalAmount = model.price + totalAmount;
                        }
                      else
                        {
                          totalAmount = model.price + totalAmount;
                        }
                      if (snapshot.data.documents.length - 1 == index)
                      {
                        WidgetsBinding.instance.addPostFrameCallback((t) {
                          Provider.of<TotalAmount>(context, listen: false).display(totalAmount);
                        });
                      }

                      return sourceInfo(model, context, removeCartFunction: () => removeItemFromUserCart(model.shortInfo));
                    },
                    childCount: snapshot.hasData ? snapshot.data.documents.length : 0,
                ),
              );
            },
          ),
        ],
      ),
    );
  }

  beginBuildingCart ()
  {

  }
  removeItemFromUserCart (String shortInfoAsId)
  {

  }
}

**Comment by preetshah21699** [comment]
This is not an issue that you. Where exactly are u=you updating the value of totalAmount?

**Comment by foxyharith** [comment]
@preetshah21699 
I changed the following 
"Total Price: ${amountProvider.totalAmount.toString()}",
to 
"Total Price: $(totalAmount.toString()}",  
and it finally worked
it turned out that the above line is bringing another totalAmount value from another class

**Comment by preetshah21699** [comment]
Actually, it just means you are not using the Provider properly. Working with provider is fun if you have a proper app architecture.
