### ISSUE TITLE
purchaseUpdatedStream not work when restore purchase in ios

### ISSUE THREAD

**Issue by ArwenChan** [flutter/flutter#71772]
purchaseUpdatedStream not work when restore purchase in ios, while a SKTransactionObserverWrapper observe skPaymentQueueWrapper can work. But it's not good idea to add mutiple observer.

**Comment by iapicca** [comment]
@ArwenChan 
I assume your issue refers to [in_app_purchase](https://pub.dev/packages/in_app_purchase)
can you provide your `flutter doctor -v` , your `pubspec.yaml` and most importantly a minimal reproducible code sample

**Comment by darshankawar** [comment]
@ArwenChan 
Please provide above requested details. Also check out [this](https://github.com/flutter/flutter/issues/65733) issue and see if it resembles your case.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
