### ISSUE TITLE
Processing FCM payload even the app is closed

### ISSUE THREAD

**Issue by raunak-many-ac** [flutter/flutter#71773]
I have an app that needs to process FCM payload so that the data inside the app(sqlite) stays in sync. When the app is closed we don't have any feature or callback method inside firebase_messaging package to execute code even if the app is not running.
 
Lack of this feature has drastically screwed up my UX because every time the app opens i have to refresh from the server, any help or package improvement in firebase_messaging package will be appreciated.

In native android even if we close the app we can still see logs in debug console but in flutter when the app closes we can't debug or process data (that also a big disadvantage).

I have been waiting for this feature on flutter since one year and still don't see any progress.

I hope this issue will be addressed.

**Comment by lazylazyllama** [comment]
It definitely is possible. See: https://firebase.flutter.dev/docs/messaging/usage#background-messages

**Comment by raunak-many-ac** [comment]
> It definitely is possible. See: https://firebase.flutter.dev/docs/messaging/usage#background-messages

Thanks @lazylazyllama i will check this out but a year ago it wasn't working fine I guess, maybe i missed something out... thanks again

**Comment by lazylazyllama** [comment]
> > It definitely is possible. See: https://firebase.flutter.dev/docs/messaging/usage#background-messages
> 
> Thanks @lazylazyllama i will check this out but a year ago it wasn't working fine I guess, maybe i missed something out... thanks again

They reworked the whole thing and especially setting the priority field within the message to high did the trick for me :)
Also keep in mind, that you don't need to modify your application.java file anymore and you should be using Android embedding v2.
