### ISSUE TITLE
HTTP problems in flutter

### ISSUE THREAD

**Issue by sc00n** [flutter/flutter#71781]
I have problems with connecting to my server. 

The very simple 

```
String urlTemp='https://m-Path.io/php/findCarer.php';
var response = await http.get(urlTemp).timeout(Duration(seconds: 10));;
```

times out every time on some networks. I used this code in the example app of flutter to make sure the problem is not somewhere else in the app.

- If I do the same thing in in Android in Kotlin, there is no problem
- If I go on this device to internet browser and go to https://m-Path.io/php/findCarer.php, there is no problem
- I have the problem both on Android as well as iOS in my flutter app
- A month ago I didn't seem to have this problem

On my home network it works just fine, but I get contacted with more and more problems. When I test on the devices from BrowserStack I always have this problem.

<details>
  <summary>flutter doctor -v</summary>
  [√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale nl-BE)
    • Flutter version 1.22.4 at C:\src\flutter\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\u0084978\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
</details>

**Comment by iapicca** [comment]
@sc00n 
it seems more a problem with [http](https://pub.dev/packages/http) than with flutter,
I recommend to open an issue in the dedicated [github](https://github.com/dart-lang/http/issues)

**Comment by sc00n** [comment]
Hey @iapicca , as I'm having the same problem with the [DIO package](https://pub.dev/packages/dio), as well as with the [core HttpClient class](https://api.flutter.dev/flutter/dart-io/HttpClient-class.html), I don't think it is a problem of the package.

**Comment by iapicca** [comment]
@sc00n 
it seems to be `XMLHttpRequest error`
try follow the possible solutions proposed [here](https://github.com/flutter/flutter/issues/32892)

**Comment by sc00n** [comment]
> @sc00n
> it seems to be `XMLHttpRequest error`
> try follow the possible solutions proposed [here](https://github.com/flutter/flutter/issues/32892) and [here](https://stackoverflow.com/a/58793440/9836706)

But my app is not a flutter web app, it is just a flutter app for Android or iOS phones. The solutions you mention seem to be specific for flutter web apps. I'll look at them anyway.

**Comment by darshankawar** [comment]
@sc00n 
Ran your code sample and received below as response, but not sure what's the expected behavior in your case.

`I/flutter (22817): { "status" : 0, "list" : []}`

I used the same url in browser and received same response as above. What should be  the expected response ?
Also, can you elaborate on when you said `A month ago I didn't seem to have this problem` ?

**Comment by sc00n** [comment]
Hey @darshankawar thank you for testing it out. You indeed get the correct, expected behavior. The problem is that from some networks the server cannot be reached trough flutter (but can trough Android or a browser). In those networks the call from Flutter will time out. We have this problem consistently when testing on [browserstack](https://www.browserstack.com/). Since a month, more and more people are complaining that they cannot reach the server anymore.

**Comment by darshankawar** [comment]
@sc00n 
It's difficult to know the reason behind network timeout if that's happening for some networks but not for others. Have you also reached out to browserstack and checked if there's something from their end ?

**Comment by sc00n** [comment]
We found that our university (a big university in Europe) tried to block everything related to dart:io. It was labeled as some kind of cyber security. They now removed it from the potential risk list and everything seems to work find again.

I hope no other organizations use this list...
