### ISSUE TITLE
CupertinoSliverNavigationBar trailing widget gets stretched

### ISSUE THREAD

**Issue by asmodeoux** [flutter/flutter#71780]
## Steps to Reproduce

1. Create a screen with CustomScrollView and CupertinoSliverNavigationBar
2. Add trailing widgets, in my example these are Icon and RaisedButton
3. Open software keyboard
4. Switch between these screens using push and pop

**Expected results:**
Trailing widgets should not be stretched while closing the keyboard

**Actual results:**
Image is clickable to see the GIF, trailing widgets get stretched while keyboard is being closed
[![20-12-05-22-21-07_01.md.gif](https://s8.gifyu.com/images/20-12-05-22-21-07_01.md.gif)](https://gifyu.com/image/jJBv)

<details>
  <summary>Logs</summary>
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale ru-RU)
    • Flutter version 1.22.3 at /Users/asmodeoux/FlutterSDK/flutter
    • Framework revision 8874f21e79 (5 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/asmodeoux/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

</details>

**Comment by Plegizplegiz** [comment]
la 5.12.2020 klo 21.40 asmodeoux <notifications@github.com> kirjoitti:

**Comment by darshankawar** [comment]
@asmodeoux 
Please provide a minimal reproducible code sample that shows the issue along with expected and actual behavior.
Thanks.

**Comment by asmodeoux** [comment]
Try this:
`return CustomScrollView(slivers: <Widget>[
                CupertinoSliverNavigationBar(
                    largeTitle: Text('Test'),
                    trailing: Padding(
                            padding: const EdgeInsets.only(top: 4.0, bottom: 5.0),
                            child: SizedBox(
                                child: RaisedButton(
                                    onPressed: () {
                                      print('test');
                                      },
                                    child: Text('Test', style: TextStyle(color: CupertinoColors.white)),
                                    color: CupertinoColors.destructiveRed,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10.0))),
                                width: 78,
                                height: 40),
                          )),
                          SafeArea(
                            top: false,
                            bottom: false,
                            child: Padding(
                              padding: const EdgeInsets.only(left: 8.0, right: 8.0, top: 8.0),
                              child: CupertinoTextField(
                                  textCapitalization: TextCapitalization.sentences,
                                  placeholder: "Test textfield")
              ),
            )
]);`

Push to this screen, open keyboard and then pop that route — the trailing widget in the top right corner (in this case it's SizedBox) will stretch and look weird during the animation (at least on Android). The expected behavior is not stretching it and keeping the size during animation. You can see that clearly on attached GIF in the original post.

**Comment by darshankawar** [comment]
@asmodeoux 
Tried your code sample but it's throwing compile error:

<img width="333" alt="Screenshot 2020-12-08 at 11 26 09 AM" src="https://user-images.githubusercontent.com/67046386/101445965-62073480-3948-11eb-86ff-47834fecac1d.png">

Please provide a complete reproducible code sample that we can copy paste and run in IDE that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
