### ISSUE TITLE
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.

### ISSUE THREAD

**Issue by AndrewTran2018** [flutter/flutter#71788]
```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=11524, thread=22616, isolate_group=main(000001EE426655F0), isolate=main(000001EE4261D640)
isolate_instructions=7ff62c4ef230, vm_instructions=7ff62c4ef240
  pc 0x00007ff62c6800ec fp 0x000000b58e9fe7a0 Unknown symbol
-- End of DumpStackTrace
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=16972, thread=12008, isolate_group=main(0000022AD7A3B300), isolate=main(0000022AD79EB160)
isolate_instructions=7ff62c4ef230, vm_instructions=7ff62c4ef240
  pc 0x00007ff62c6800ec fp 0x00000079b39fec20 Unknown symbol
-- End of DumpStackTrace

Run flutter doctor:
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\abc\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

```

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 6.44 AndrewTran2018 <notifications@github.com> kirjoitti:

**Comment by darshankawar** [comment]
@AndrewTran2018 
Check [this](https://github.com/flutter/flutter/issues/63356#issuecomment-678617731) issue comment and see if it helps.
If issue persists, please provide a minimal reproducible code sample that shows this issue.
Does it also happen on a physical device ?

**Comment by Sandwich2080** [comment]
Same as above.

> Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=10692, thread=16788, isolate_group=main(000001CB1891E310), isolate=main(000001CB1D312460)
isolate_instructions=1cb1bd60000, vm_instructions=7ff7a9abf240
  pc 0x00007ff7a9c500ec fp 0x00000026b6ffe300 Unknown symbol
-- End of DumpStackTrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
the Dart compiler exited unexpectedly.
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by AndrewTran2018** [comment]
> @AndrewTran2018
> Check [this](https://github.com/flutter/flutter/issues/63356#issuecomment-678617731) issue comment and see if it helps.
> If issue persists, please provide a minimal reproducible code sample that shows this issue.
> Does it also happen on a physical device ?

Closing AS and restarting Windows, or Invalidate and Restart Cache sometimes works, sometime does not, so I do not think that is a good workaround. I finally end up in "removing Chrome"

**Comment by darshankawar** [comment]
@AndrewTran2018 Does that mean you don't see the issue anymore and has been resolved ?

**Comment by Sandwich2080** [comment]
Restarting AS can't solve this issue completely, it can happen again after a little while.  This may be not a good solution.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by benyaminbeyzaie** [comment]
I have same issue here 
```
Launching lib\main.dart on SM A505F in debug mode...
 lib\main.dart
.
./../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=5672, thread=8176, isolate_group=main(000001A551D1EA10), isolate=main(000001A55673EB30)
isolate_instructions=1a5551a0000, vm_instructions=7ff67080f240
  pc 0x00007ff6709a00ec fp 0x00000055e67fe810 Unknown symbol
-- End of DumpStackTrace

../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=3044, thread=14936, isolate_group=main(0000022E6931A7B0), isolate=main(0000022E693280C0)
isolate_instructions=7ff67080f230, vm_instructions=7ff67080f240
  pc 0x00007ff6709a00ec fp 0x0000005aca2f9a60 Unknown symbol
-- End of DumpStackTrace
Exited (3221226505)
```

**Comment by rromaniz** [comment]
Same error here

../../third_party/dart/runtime/vm/thread_pool.cc: 299: error: Could not start worker thread: result = 22.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=10528, thread=1984, isolate_group=(nil)(0000000000000000), isolate=(nil)(0000000000000000)
isolate_instructions=0, vm_instructions=7ff7bb5df240
  pc 0x00007ff7bb7700ec fp 0x00000062192ff730 Unknown symbol
-- End of DumpStackTrace

**Comment by Toseefsaim** [comment]
Solution...!
1) you have to increase space of C file
2) then in android studio you have of open (File) and in file you click(invalidate caches/ restart)

**Comment by benyaminbeyzaie** [comment]
I install Ubuntu on my computer and it has solved my problem! windows consume so much RAM on building applications! My CPU is i7 10th generation and I have 16GB of RAM but android studio was so slow on windows, on Linux everything is working great!
