### ISSUE TITLE
Can Dart remove semicolons and keyword "new" ?

### ISSUE THREAD

**Issue by ultimateHandsomeBoy666** [flutter/flutter#71792]
## Use case

I'm an android developer writing in kotlin. And I started studying flutter recently. All things about flutter are good, except for the annoying grammar
of Dart, which to me looks like a mix-up of Java & Koltin/python/or any other simple modern language...
I mean, if you wanna make the language simple, then make it simple enough.
now that Dart has allowed instantiating an object without the keyword "new", so why you guys still keep it as an alternative option?
 JUST REMOVE IT. And the world may be cleaner.
And also, remove semicolons. The coding prompt for writing dart in android studio is bad, cuz I need to jump to the end of the line to add a semicolon every time I pick prompt code.
If the studio doesn't prompt code with a semicolon, why just remove those semicolons in the language, Like Kotlin/python, which needs no semicolon.
After all, those semicolons seem to be useless and ugly. 

## Proposal
Wish dart remove semicolons and keyword "new"🙏🙏🙏 
Thank you guys

**Comment by ZainUrRehmanKhan** [comment]
With Dart 2 ([click for the announcement with more information](https://medium.com/dartlang/announcing-dart-2-80ba01f43b6#da82)) the new and also const keywords were made optional.

This means that new Widget() does the exact same as Widget() on its own.

**Comment by iapicca** [comment]
@ultimateHandsomeBoy666 
this issue doesn't seem being related to `flutter` but to `dart`;
while `new` is already optional, as @ZainUrRehmanKhan pointed out 
there's already an [open proposal](https://github.com/dart-lang/language/issues/69) about optional semicolon

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 11.47 Zain Ur Rehman <notifications@github.com> kirjoitti:

**Comment by ultimateHandsomeBoy666** [comment]
I know that Dart 2 supports optional keyword new. I just wonder why the dart team made it optional rather than removing it entirely, like disallowing to calling constructor with `new`. Is it for compatibility or something?
And thank you for telling me there has been an proposal about semicolon omitting @iapicca .

**Comment by iapicca** [comment]
@ultimateHandsomeBoy666 
as I fail to comprehend what could be the advantage 
or the use case of removing an optional constructor,
I personally I believe this proposal is not valid.

Assuming the validity of this proposal 
it should not be addressed to `flutter`, but to `dart` in the appropriate [repo](https://github.com/dart-lang/language/issues)

**Comment by bdlukaa** [comment]
About semi-colons, there is an open issue in the dart repo.

Link: https://github.com/dart-lang/language/issues/69

**Comment by TahaTesser** [comment]
Hi @ultimateHandsomeBoy666 
Please follow up on https://github.com/dart-lang/language/issues/69
As @iapicca, mentioned https://github.com/flutter/flutter/issues/71792#issuecomment-739488488, this discussion is better suited on dart repository. 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
