### ISSUE TITLE
Mapper 3.x is not supported!

### ISSUE THREAD

**Issue by Faizzy7** [flutter/flutter#71799]
I'm developing a chat app using android studio, when i successfully debugged in my android 10 , it showing mapper 3.0x is not supported and i cannot search for bluetooth devices in my app after debugging!

**Comment by iapicca** [comment]
@Faizzy7 
can you provide your `flutter doctor -v `
your `flutter run -v `and most importantly a minimal reproducible code sample

**Comment by Faizzy7** [comment]
> @Faizzy7
> can you provide your `flutter doctor -v `
> your `flutter run -v `and most importantly a minimal reproducible code sample
](url)

**Comment by Faizzy7** [comment]
> @Faizzy7
> can you provide your `flutter doctor -v `
> your `flutter run -v `and most importantly a minimal reproducible code sample

![16072623151756534244584111238654](https://user-images.githubusercontent.com/75571307/101281833-7ab40500-37f7-11eb-951c-13648375c41d.jpg)

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 15.20 Faizzy7 <notifications@github.com> kirjoitti:

**Comment by TahaTesser** [comment]
Hi @Faizzy7 
Please refrain from posting screenshots/pic of the logs, simply copy logs and paste it here
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample, not production code
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
