### ISSUE TITLE
slow debugging

### ISSUE THREAD

**Issue by EvgeniBR** [flutter/flutter#71794]
## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

**Comment by EvgeniBR** [comment]
hi , when i run debugging my pc start to lag and ecomes very slow

**Comment by iapicca** [comment]
@EvgeniBR 
this situation might depend by a number of factors:

- What operative system are you using?
- Are you using android studio , vscode or other IDEs?
- Are you using a physical or virtual device?

Can you please provide more details and your `flutter doctor -v`

**Comment by EvgeniBR** [comment]
I'm on windows os
vscode
 virtual device from  android studio (pixel 4)

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 13.06 Evgeni Bershadsky <notifications@github.com>
kirjoitti:

**Comment by iapicca** [comment]
> I'm on windows os
> vscode
> virtual device from android studio (pixel 4)

android studio is quite a resource hungry IDE
and using a virtual device takes a toll on your machine resources as well

if you are using a low spec machine (like myself)
I personally suggest vscode + physical device 

I don't believe this is an issue with flutter at all

**Comment by EvgeniBR** [comment]
got it , thank you
