### ISSUE TITLE
I am running flutter web and the app is failing to open in Chrome from the device dropdown list, instead have to run -d web-server

### ISSUE THREAD

**Issue by RobynKing88** [flutter/flutter#71800]
Hi, I am trying to create a flutter web application and run it in Chrome. Everything is working and I see Chrome in the devices list but if I try run from there it fails to connect:

```bash
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Finished with error: Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
```
My Chrome is up to date and it works when I run: flutter run -d web-server

**Comment by iapicca** [comment]
@RobynKing88 
can you provide your `flutter doctor -v `and your `flutter run -d chrome -v`

**Comment by RobynKing88** [comment]
Sure:

**flutter doctor -v**

[√] Flutter (Channel master, 1.25.0-5.0.pre.90, on Microsoft Windows [Version 10.0.18362.1016], locale en-GB)
    • Flutter version 1.25.0-5.0.pre.90 at C:\src\flutter
    • Framework revision a17bbb9bbe (27 hours ago), 2020-12-05 07:58:03 -0500
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ryk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\ryk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

**flutter run -d chrome -v**

[  +85 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +122 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] a17bbb9bbe7a44603c5b155416720ac22726fcf0
[        ] executing: [C:\src\flutter/] git tag --points-at a17bbb9bbe7a44603c5b155416720ac22726fcf0
[  +98 ms] Exit code 0 from: git tag --points-at a17bbb9bbe7a44603c5b155416720ac22726fcf0
[   +1 ms] executing: [C:\src\flutter/] git describe --match *.*.* --long --tags a17bbb9bbe7a44603c5b155416720ac22726fcf0
[ +121 ms] Exit code 0 from: git describe --match *.*.* --long --tags a17bbb9bbe7a44603c5b155416720ac22726fcf0
[        ] 1.25.0-4.0.pre-90-ga17bbb9bbe
[  +37 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +99 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +125 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +126 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +116 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] executing: C:\Users\ryk\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +228 ms] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Skipping pub get: version match.
[ +152 ms] Generating C:\Users\ryk\Documents\LOCAL\MyProjects\FlutterWeb\esg_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +193 ms] Launching lib\main.dart on Chrome in debug mode...
[ +110 ms] Updating assets
[  +88 ms] Waiting for connection from debug service on Chrome...
[ +154 ms] <- reset
[   +6 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc
--debugger-module-names --experimental-emit-debug-metadata --output-dill C:\Users\ryk\AppData\Local\Temp\flutter_tools.e59c8790\flutter_tool.a120178a\app.dill --libraries-spec file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
C:\Users\ryk\Documents\LOCAL\MyProjects\FlutterWeb\esg_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\ryk\AppData\Local\Temp\flutter_tools.e59c8790\flutter_tools.3350fbd1 --filesystem-scheme org-dartlang-app --initialize-from-dill build\fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[ +286 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+20061 ms] Waiting for connection from debug service on Chrome... (completed in 20.5s)
[   +2 ms] Synced 28.4MB.
[  +12 ms] <- accept
[   +1 ms] Caching compiled dill
[ +582 ms] Using Opening in existing browser session.

[ +576 ms] Failed to launch browser. Command used to launch it: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --user-data-dir=C:\Users\ryk\AppData\Local\Temp\flutter_tools.e59c8790\flutter_tools_chrome_device.6d0dabaa --remote-debugging-port=56102
--disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:56080
[   +9 ms] "flutter run" took 22,737ms.
[  +13 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
[   +5 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1414:9)
           #3      _rootRun (dart:async/zone.dart:1178:47)
           #4      _CustomZone.run (dart:async/zone.dart:1090:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:101:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:165:13)
           #11     _rootRun (dart:async/zone.dart:1178:47)
           #12     _CustomZone.run (dart:async/zone.dart:1090:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #22     _rootRun (dart:async/zone.dart:1178:47)
           #23     _CustomZone.run (dart:async/zone.dart:1090:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #34     _rootRun (dart:async/zone.dart:1178:47)
           #35     _CustomZone.run (dart:async/zone.dart:1090:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:815:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:670:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:663:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2014:21)
           #44     _rootRunUnary (dart:async/zone.dart:1202:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1097:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1002:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:807:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:681:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1550:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1048:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[ +263 ms] ensureAnalyticsSent: 252ms
[   +8 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +17 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

**Comment by TahaTesser** [comment]
Hi @RobynKing88
Running on Chrome 86, I had no issues then I updated chrome to match yours and I ran into the issue, however, when I tried again it runs without any issues
```bash
PS C:\Users\Taha\AndroidStudioProjects\master_flutter> flutterm run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             15.0s
Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server
instead and filing an issue at https://github.com/flutter/flutter/issues.
PS C:\Users\Taha\AndroidStudioProjects\master_flutter> flutterm run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             18.7s
Debug service listening on ws://127.0.0.1:50383/atD01CIoIw0=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
```

I thought it might happen on the first run, so I created a new project and tried to reproduce the issue several times but it doesn't reproduce anymore. Looks it was just after the chrome upgrade. Can you please reproduce it again?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
