### ISSUE TITLE
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

### ISSUE THREAD

**Issue by ramnath30** [flutter/flutter#71811]
The code below causes an assertion failure. The stack trace of the failure is pasted after the code.

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CAppbar(
        context,
        'Resources',
        /*actions: [ActionType.ADVANCED_SEARCH, ...CAppbar.DEFAULT_ACTIONS,],*/
      ),
      body: Column(
        children: [
          Container(
            decoration: BoxDecoration(color: Color.fromRGBO(255, 100, 255, .1)),
            padding: const EdgeInsets.only(
              left: 10,
              top: 8,
              right: 10,
            ),
            child: Text(
              'Enter text for Simple Search below.',
              style: Theme.of(context).textTheme.bodyText1,
              textAlign: TextAlign.center,
            ),
          ),
          _buildSearchField(),
          Expanded(
            child: _buildGrid(),
          ),
        ],
      ),
      resizeToAvoidBottomInset: false,
    );
  }

  Widget _buildGrid() {
    print('_buildGrid itemCount: ${_resourceModel.resources.length}');
    if (_resourceModel.isCallInProgress(ResourceModel.FETCH_RESOURCES_CALL) &&
        _resourceModel.resources.length < 1) {
      return Center(
        child: CircularProgressIndicator(
          backgroundColor: progressBarColor,
        ),
      );
    } else if (_resourceModel.error) {
      return Text(
        'Sorry, an error occurred. Please try again.',
        style: errorStyle(context),
      );
    } else if (_resourceModel.resources.length < 1) {
      return Text(
        'No Results. Please try again.',
        style: errorStyle(context),
      );
    }

    return ListView.builder(
        itemCount: _resourceModel.resources.length,
        scrollDirection: Axis.vertical,
        itemBuilder: (BuildContext context, int index) {
          final resource = _resourceModel.resources[index];
          return GestureDetector(
            onTap: () {
              CRouter.route(
                context,
                ROUTE_ADD_TO_CART,
                arguments: resource,
              );
            },
            child: Card(
              elevation: 10,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(15.0)),
              margin: EdgeInsets.symmetric(
                horizontal: 3,
                vertical: 10,
              ),
              // ),
              child: Column(
                children: [
                  _image(resource.imageUrl),
                  _caption(resource.name, resource.price),
                ],
              ),
            ),
          );
        });
  }

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  FittedBox file:///xxxxx:174:14
When the exception was thrown, this was the stack: 
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:320:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2429:58)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:12)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
...
The following RenderObject was being processed when the exception was fired: RenderFittedBox#b346b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=386.7, h=90.0)
...  size: MISSING
...  fit: scaleDown
...  alignment: center
...  textDirection: ltr
RenderObject: RenderFittedBox#b346b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=386.7, h=90.0)
  size: MISSING
  fit: scaleDown
  alignment: center
  textDirection: ltr
...  child: RenderSemanticsAnnotations#1709e relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: Size(0.0, 0.0)
...    child: RenderImage#058d0 relayoutBoundary=up2 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(0.0, 0.0)
...      image: null
...      alignment: center
...      invertColors: false
...      filterQuality: low
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by pedromassangocode** [comment]
Hi @ramnath30 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample? I need a ccode that one can just copy/paste and run it
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
