### ISSUE TITLE
Explicit reflection support

### ISSUE THREAD

**Issue by TheMisir** [flutter/flutter#71810]
## Use case

I know reflection is **disabled** in Flutter for optimizing performance and app size. But using code generators for json (de)serialization actually s***s. I know it works but that's not enough. The code becomes pretty ugly which makes its hard to understand as codebase grows. My proposal is adding a feature for explicitly enabling serialization for specific classes we create. 

## Proposal

For example we could use annotations to annotate classes to be reflectable (not exactly but like `[Serializable]` attribute in C#).

```dart
@serializable()
class Product {
  String name;
  double price;
}
```

In that way we'll not have to generate de/serialization code each time we change base class fields without sacrificing performance or app size (dart compiler will have to only save reflection data for classes annotated with `@serializable()` annotation).

I know this proposal probably will be declined but I have hope. Cause without this kind of features it's hard to write productive code. I don't want to feel lazy because of boring `build_runner` / code generation process.

**What about 3rd party packages?**

I think reflection could be limited to first party (project related) code only. Because otherwise lots of packages will opt-in for using reflection without even if app doesn't uses that feature.

**Comment by pedromassangocode** [comment]
For reference https://github.com/flutter/flutter/issues/1150.

**Comment by chinmaygarde** [comment]
This must be filed in the Dart issue tracker.
