### ISSUE TITLE
[flutter_tools]Add --dart-define option support to build aar command.

### ISSUE THREAD

**Issue by hyiso** [flutter/flutter#71827]
## Use case
Now as we can use --dart-define to provide custom constant at build time with `flutter run`, `flutter build apk`, `flutter build ios`... build commands, except `flutter build aar`.
![image](https://user-images.githubusercontent.com/5681324/101319306-ba80f800-389c-11eb-9d63-32902028ca17.png)

## Proposal
Add this support to make `flutter build aar` more conveniently

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/71829#event-4104047802
