### ISSUE TITLE
Your Flutter application is created using an older version of the Android embedding

### ISSUE THREAD

**Issue by Deosaur-coder** [flutter/flutter#71828]
i used a shareable dart file ,i got this error ,plss some one help to fix this

C:\src\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in mi_card_flutter...                     6.8s
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i got this error,and my flutter doctor is perfect

**Comment by pedromassangocode** [comment]
Hi @Deosaur-coder 
Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by mhmdanas** [comment]
@Deosaur-coder you're supposed to follow the instructions at https://flutter.dev/go/android-project-migration as the warning (no, it's not an error) states.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
