### ISSUE TITLE
Skia's particles module available from Flutter

### ISSUE THREAD

**Issue by ppave** [flutter/flutter#71845]
Hello.
Do you have any plans to make [Skia's particles module](https://skia.org/user/modules/particles) available from Flutter?
Thanks.

**Comment by TahaTesser** [comment]
Hi @ppave 
Can you please provide explain why we need it and provide any use cases for this particle module in flutter? 
Thank you

**Comment by ppave** [comment]
Hi @TahaTesser 
I see that there are custom implementations like here https://github.com/gskinnerTeam/flutter_vignettes. So I am curios what's the best way to do that now and in the nearest future.
Thanks

**Comment by TahaTesser** [comment]
Hi @ppave 
I think it's best to utilize third-party packages such as
 https://pub.dev/packages/flutter_particle_background 
 https://pub.dev/packages/particles  
https://pub.dev/packages/spritewidget

**Comment by ppave** [comment]
Hi @TahaTesser 
Thank you
