### ISSUE TITLE
FileSystemException: FileSystemException: Cannot copy file 

### ISSUE THREAD

**Issue by UncleSam-tech** [flutter/flutter#71840]
I have been having this issue for a while now and I have tried to change my Flutter SDK directory as well but it is not working.
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\DELL\Documents\Flutter\tutorial\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\DELL\Documents\Apps\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

**Comment by pedromassangocode** [comment]
Hi @UncleSam-tech 
I see there's an open issue (https://github.com/flutter/flutter/issues/69116) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by UncleSam-tech** [comment]
Okay, but please can I get a solution today.

**Comment by pedromassangocode** [comment]
I'm not sure about that.

This usually happens when Flutter is installed in a directory where he does not have sufficient permissions to copy/read/write. You can try give permissions to Flutter or move Flutter SDK to a different directory.

**Comment by UncleSam-tech** [comment]
I have done all this and it is still the same error I get.
