### ISSUE TITLE
Example app link is not working

### ISSUE THREAD

**Issue by aatikakhan** [flutter/flutter#71857]
Hi, your example app for demonstration link is not working and it's giving error 404.

**Comment by darshankawar** [comment]
@aatikakhan 
Which example app are you referring to ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
