### ISSUE TITLE
with_coverage_time_ms, without_change_elapsed_time_ms flutter_test_performance regressions.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#71851]
https://flutter-flutter-perf.skia.org/e/?begin=1607101951&end=1607126887&keys=Xcdf4b4870fdb6d16ea08ac351176954f&num_commits=50&request_type=1&xbaroffset=22738

Same roll as https://github.com/flutter/flutter/issues/71850; https://github.com/flutter/flutter/pull/71699.

**Comment by chinmaygarde** [comment]
cc @cbracken. I believe we need to bisect this to an SDK roll.

**Comment by Hixie** [comment]
Reassigned per @cbracken.

**Comment by zanderso** [comment]
@gw280 I believe you mentioned you were working on the bisect. Please give a shout if you are blocked on anything.

**Comment by gw280** [comment]
Bisect is still ongoing. I keep hitting roadblocks, the latest one being getting a working android environment setup on my P920 which (I believe) is the reason the test isn't running locally.

**Comment by gw280** [comment]
It's this Dart SDK roll: https://github.com/flutter/engine/pull/22801

**Comment by zanderso** [comment]
@jensjoha several PR is this area in that roll:

https://dart.googlesource.com/sdk.git/+log/7a2a3968ef53..e9a03fd98faa

**Comment by gw280** [comment]
I just bisected that roll, it's due to this change: https://dart.googlesource.com/sdk.git/+/27ed7912af86426288107bfaa09b31c36099e4ba

**Comment by jensjoha** [comment]
Should be fixed with https://dart-review.googlesource.com/c/sdk/+/175724.

**Comment by chinmaygarde** [comment]
The linked fix landed 3 days ago but the autoroller was paused for https://github.com/flutter/flutter/issues/72158. I have re-enabled it now and it should be rolled in soon-ish.

**Comment by gw280** [comment]
https://flutter-flutter-perf.skia.org/e/?begin=1606867006&queries=sub_result%3Dwithout_change_elapsed_time_ms&requestType=0 - looks like we're back down to the old figures again. Closing.
