### ISSUE TITLE
GPU traces (and likely other embedder traces) use multiple incompatible trace types

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7187]
We use [two APIs](https://github.com/flutter/engine/blob/master/glue/trace_event.h) to publish traces from the embedder. However, one sends "duration" events, the other sends begin/end pairs. This can complicate the extraction of events for the purposes of tracking per-frame performance. Can/should we unify them? Which format should it be?

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
We now use the tracing implementation in FML which boils down to calling the same Dart timeline APIs.
