### ISSUE TITLE
Building with --release produces a runtime error

### ISSUE THREAD

**Issue by DRSchlaubi** [flutter/flutter#71877]
## Steps to Reproduce
Pick a contact in this example: https://github.com/DRSchlaubi/contact_picker/tree/master/contact_picker/example

**Expected results:** Get same result as in debug mode

**Actual results:** Runtime error

<details>
  <summary>Logs</summary>

js_helper.dart:1130 Uncaught TypeError: a.gAA is not a function
    at Object.a6R (picker.js.dart:60)
    at Ri.$1 (contact_picker_plugin.dart:129)
    at at.aa (iterable.dart:411)
    at cP.n (iterable.dart:340)
    at Object.a09 (core_patch.dart:472)
    at Object.ai (core_patch.dart:479)
    at at.cb (iterable.dart:211)
    at contact_picker_plugin.dart:130
    at Wi.a (async_patch.dart:316)
    at Wi.$2 (async_patch.dart:341)

```
```

D:\WORK\contact_picker\contact_picker\example>flutter analyze
Analyzing example...
No issues found! (ran in 11.7s)

```
```

D:\WORK\contact_picker\contact_picker\example>flutter doctor -v
[✓] Flutter (Channel master, 1.25.0-5.0.pre.100, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.25.0-5.0.pre.100 at C:\flutter
    • Framework revision 03013ce42a (51 minutes ago), 2020-12-07 13:49:11 -0800
    • Engine revision 69dacc4138
    • Dart version 2.12.0 (build 2.12.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\micha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\micha\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\micha\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 52.0.2
    • Dart plugin version 202.8070

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\micha\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 0A021FDD4007SZ • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 87.0.664.55
    ! Device emulator-5554 is offline.

• No issues found!

```
```

</details>

When I build my example app using flutter run everything works but if I build the release version of it a function that works completely fine in the debug version throws the error attached in the logs above. I have no way of debugging this error, as the function name is obfuescated and the chrome debugger sends me to something like https://<host>C:/flutter/.pub-cache/hosted/pub.dartlang.org/contact_picker_web-4.0.2/lib/src/js/picker.js.dart, when trying tto clicck the line.

Is there any way to disable name obfuescation? compiling with `--source-maps` didn't help as it only seems to provide a source map for main.dart

**Comment by iapicca** [comment]
@DRSchlaubi 
this seems more an issue with the 3rd party package [fluttercontactpicker](https://pub.dev/packages/fluttercontactpicker)
rather than flutter itself

**Comment by DRSchlaubi** [comment]
The problem is it's my plugin and the error is not giving me enough information to fix it

**Comment by darshankawar** [comment]
@DRSchlaubi 
Since it's an issue with your plugin and not Flutter, your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
You may also see [this](https://stackoverflow.com/questions/62833628/how-to-disable-code-obfuscation-in-flutter-release-apk) link and see if it helps. 
Closing from here.

**Comment by DRSchlaubi** [comment]
If the dart Dev compiler is able to compile my plugin just fine but the production compiler compiles it so it produces a unreadable runtime error how exactly is this a problem with my plugin @darshankawar

**Comment by DRSchlaubi** [comment]
After further testing I am pretty sure  the issue is caused by minification of the js code which i can't disable
