### ISSUE TITLE
Would be nice to have an example LazyBlockDelegate in flutter_gallery

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7188]
I think I need to write one for the app I'm experimenting with, and I was surprised we didn't have one in the gallery.

https://github.com/flutter/flutter/search?q=LazyBlockDelegate&type=Code&utf8=%E2%9C%93

**Comment by abarth** [comment]
LazyBlockChildren and LazyBlockBuilder might be more approachable.

**Comment by Hixie** [comment]
These are gone now.
