### ISSUE TITLE
How to track the video playback progress in android webView

### ISSUE THREAD

**Issue by Joealtidore1** [flutter/flutter#71881]
I am trying to play a list of videos using a web video and i need to mark each one as completed when it has finished playing so that the next one can load immediately but i can't seem to find my way around it. this is my code snippet:

 ```
private void playVideo(String lessonURL) {
    WebViewPlayer.setVisibility(View.VISIBLE);
    WebViewPlayer.getSettings().setJavaScriptEnabled(true);

    WebViewPlayer.getSettings().getAllowContentAccess();
    WebViewPlayer.getSettings().setDomStorageEnabled(true);
    WebViewPlayer.getSettings().setAppCacheEnabled(true);
    WebViewPlayer.getSettings().setAppCachePath(getApplicationContext().getFilesDir().getAbsolutePath() + "/cache");
    WebViewPlayer.getSettings().setDatabaseEnabled(true);
    WebViewPlayer.getSettings().setDatabasePath(getApplicationContext().getFilesDir().getAbsolutePath() + "/databases");
    WebViewPlayer.getSettings().setPluginState(WebSettings.PluginState.ON);
    WebViewPlayer.setWebChromeClient(new WebChromeClient());
    WebViewPlayer.setWebViewClient(new WebViewClient());
    WebViewPlayer.loadUrl(lessonURL);
}
```
The video is playing but then i need to mark the current video as completed when it is done playing. How can i implement it?

    ```
 private boolean isCompleted(){
        //how do i implement this?
     }
```

**Comment by darshankawar** [comment]
@Joealtidore1 
There's a similar open feature request [issue](https://github.com/flutter/flutter/issues/35607) to let dev know if the video is completed or not. You may follow-up there for updates.

Also, your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing from here.

**Comment by Joealtidore1** [comment]
@darshankawar 
Thanks for the reply but my code base is in Java and not flutter. I have raised the issue on stackoverflow [here](https://stackoverflow.com/questions/64940798/is-there-a-way-to-monitor-the-progress-of-a-video-that-is-played-with-a-web-view) and I haven't got a response. I will really appreciate it if you if you can help me out.
