### ISSUE TITLE
Make platform views less expensive in the CanvasKit renderer

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#71884]
Currently embedding a platform view immediately induces a new canvas that sits on top of it. Each extra platform view add another canvas. The extra canvases are expensive as each is the size of the entire window. Frequently a platform view does not intersect with pictures that follow it in paint order, and the layers can be reordered such that the platform view is on top, removing the need for the extra canvas.

When we fix this, we should also update the docs at https://docs.flutter.dev/platform-integration/web/web-images#use-img-in-a-platform-view and drop the reference to slow platform views.

More details in https://flutter.dev/go/flutter-web-scenelets

**Comment by dannnnthemannnn** [comment]
@yjbanov Do you have any guidance on how many platform views would be a problem? 

I have a video chat app and have a platform view for each video stream. I am trying to use canvaskit as its a pretty CPU intensive process to display lots of video streams and I'm hoping that canvaskit will have higher performance. 

Is 5-16 platform views showing a video element going to be a significant problem or do you have any estimates for that?

**Comment by yjbanov** [comment]
@dannnnthemannnn 

I think it's specific to the OS/browser/hardware combination. Because the issue is essentially resource utilizations, the more resources your local setup makes available the more WebGL contexts we can create. You can check the resources your browser provides to WebGL at https://webglreport.com/?v=2.

However, off the top of my head, I'd say perhaps up to 7 is reasonable. Higher than that would be pushing it. What you can do, however, if you have a grid of `<video>` elements all appearing together you can use one platform view to display all of them. You'd have to use HTML/CSS to lay them out, of course, but otherwise embedding them in Flutter should work.

**Comment by yjbanov** [comment]
Reopening this issue. https://github.com/flutter/flutter/issues/86868 was fixed by a more targeted optimization. We still do not track intersections between pictures and platform views and create more canvases than necessary.
