### ISSUE TITLE
Is there a way to communicate between multiple navigator

### ISSUE THREAD

**Issue by ahuruConnect** [flutter/flutter#71891]
I'm experiment an app that has  page A that with a button that allows it to push to another page B with it's own navigator, navigator1, implmeted using navigator 2. navigator1 has a list screen and a detail screen.

There are two problems at the moment:
1. list screen in navigator1 does not show a back button.
2. when on Detail screen, physical back button or ios "swip back" takes the app back to Page A, instead of going back to list screen of navigatorA.

I know Navigator 2 handles nested navigators really well but what about parallel navigators? Any suggestions of how to deal with this?

flutter doctor -v:
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-NZ)
    • Flutter version 1.22.4 at /Users/pengfeihuang/fvm/versions/stable
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pengfeihuang/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/pengfeihuang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Nokia 7 2 (mobile)                  • D0AA002844JA0810015                  • android-arm64 • Android 10 (API 29)
    • iPhone SE (2nd generation) (mobile) • 01768AA3-066A-483C-BAED-91EDC3E50665 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@ahuruConnect 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue # 1 and 2 you listed above.

**Comment by ahuruConnect** [comment]
Please check out this sample repo and let me know if it doesn't work.
https://github.com/PandaGeek1024/navigatorSample

**Comment by darshankawar** [comment]
@ahuruConnect 
Cloned your repo and verified on Android emulator Pixel 3XL.

For # 1: I see below.

<img width="329" alt="Screenshot 2020-12-08 at 6 41 06 PM" src="https://user-images.githubusercontent.com/67046386/101488093-25a5f980-3985-11eb-8dae-52452090de98.png">

Per your question, this should show a back button ?

For # 2: I tapped on `Open List Page` -> `Foundation` and tapped on emulator back button which took me to `Open List Page`

[71891.mov.zip](https://github.com/flutter/flutter/files/5659452/71891.mov.zip)

Are you seeing a different behavior than above ?

Also, can you also provide `flutter doctor -v` and OS platform on which you are seeing the issues ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!


```

</details>

**Comment by ahuruConnect** [comment]
flutter doctor -v is provided. Im also running on both android and iOS.

With the sample app, we have 3 pages:
homePage -> ListPage -> DetailPage

ListPage and DetailPage are on another navigator, so the detailed structure is more like:
homePage -> OtherNavigator(ListPage(Sacaffold) -> DetailPage(Sacaffold))

what happens:
1. ListPage should show a back button in appbar so it can navigate back to homePage, but it is not. Maybe I should add it manually but still expecting a more official approach.
2. For the video, that's exactly the same behaviour that Im seeing: clicking physical back button on detailPage lead it back to homePage, which is not expected. It should go back to ListPage first and then homePage.

The reason for me to put ListPage and Detailpage in another navigator is because I want to provide a provider or bloc for just that flow. So when it exit list page, the bloc/provider is gone as well. But with the current Navigator, it doesn't seem like a way?

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis. https://github.com/flutter/flutter/issues/71891#issuecomment-740612847

**Comment by chunhtai** [comment]
>>ListPage should show a back button in appbar so it can navigate back to homePage, but it is not. Maybe I should add it manually but still expecting a more official approach.

The back button is created based on whether there is a route below in the CURRENT navigator. In your use case, there is no other route underneath in the OtherNavigator. There is no plan to change this behavior. The correct way will be implement your own back button.

>>For the video, that's exactly the same behaviour that Im seeing: clicking physical back button on detailPage lead it back to homePage, which is not expected. It should go back to ListPage first and then homePage.

There is multiple way you can do this, the cleanest way will be convert you top most MaterialApp to MaterialApp.router, and then in you book apps, you should create child backbuttondispatcher

for example:
```dart

class BooksApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _BooksAppState();
}

class _BooksAppState extends State<BooksApp> {
  BookRouterDelegate _routerDelegate = BookRouterDelegate();
  BookRouteInformationParser _routeInformationParser = BookRouteInformationParser();

  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    BackButtonDispatcher dispatcher = Router.of(context).backButtonDispatcher.createChildBackButtonDispatcher();
    dispatcher.takePrioirty();
    return MaterialApp.router(
      title: 'Books App',
      routerDelegate: _routerDelegate,
      routeInformationParser: _routeInformationParser,
      backButtonDispatcher: dispatcher,
    );
  }
}
```

**Comment by chunhtai** [comment]
closing as WAI
