### ISSUE TITLE
GestureDetector  onTap is hard to work on macos

### ISSUE THREAD

**Issue by gaoxuefeng** [flutter/flutter#71904]
GestureDetector  onTap  is very hard to run click method, maybe it is because click it too quilcky, it works sometimes when i click it slowly.
it works when change method to onTapdown
Hope to improve the experience on macos

**Comment by darshankawar** [comment]
@gaoxuefeng 
Please provide `flutter doctor -v` and minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by stuartmorgan** [comment]
Are you on Big Sur? This sounds like that known issue.

**Comment by gaoxuefeng** [comment]
@stuartmorgan yes it`s  Big Sur

**Comment by gaoxuefeng** [comment]
@darshankawar 
 flutter doctor -v result:
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.25.0-4.0.pre at /Users/gaoxuefeng/Library/Android/flutter1.22.3/flutter
    • Framework revision a7f5fd5360 (9 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gaoxuefeng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME =
      ./usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin:/Users/gaoxuefeng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.2
    • Dart plugin version 201.7846.93

[✓] Connected device (4 available)
    • Mi 10 (mobile)   • c63dd70d   • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos      • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

[problem code](https://github.com/gaoxuefeng/flutter_app_channel/blob/master/lib/channel_build_home_page.dart)

**Comment by darshankawar** [comment]
@gaoxuefeng 
There's similar open issue describing your case, specific to BigSur, https://github.com/flutter/flutter/issues/64961.
Please follow-up there for updates.
Closing this as duplicate.
