### ISSUE TITLE
debug_full_compile_millis basic_material_app_ios__compile regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#71921]
https://flutter-flutter-perf.skia.org/e/?begin=1607031697&end=1607399282&keys=Xd61f3cc19ae5389d72e2be592db3c1b6&requestType=0&xbaroffset=22764

First occurs at https://github.com/flutter/flutter/pull/71866. 

@jmagman, why would making a test no longer flaky cause this regression, do you think?

It's a moderate regression (5s, if I'm doing my division right), so I'm going to mark this high-priority, but not a P0, as it's flagged by a test change and may not be a real issue.

**Comment by kf6gpe** [comment]
Oh, perhaps it's https://github.com/flutter/flutter/pull/70240, which shows the same thing. @dnfield care to comment as well? Again, nothing that convinces me that this isn't a test change.

**Comment by dnfield** [comment]
I think this is expected - there's now a plugin in the template, which increases compilation time somewhat.

Although really the integration test plugin shouldn't get added to non-test-target applications. That's being tracked  in https://github.com/flutter/flutter/issues/56591 - or at least, something like it.

**Comment by dnfield** [comment]
There's also some more context in https://github.com/flutter/flutter/pull/45816's discussion

**Comment by kf6gpe** [comment]
Thanks, Dan. Closing as WAI.
