### ISSUE TITLE
Pigeon documentation

### ISSUE THREAD

**Issue by ammaratef45** [flutter/flutter#71926]
Pigeon seems to be a very useful tool for writing plugins, but, It's poorly documented and no clear examples of its usage can be found.

**Comment by darshankawar** [comment]
@ammaratef45 
There's similar open issue requesting to improve documentation, https://github.com/flutter/flutter/issues/66511.
Please follow-up there for updates or any specific example you would like to be added in the documentation.
Closing this as duplicate.
