### ISSUE TITLE
[devicelab] iOS Catalina bot fails to pick up tasks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#71931]
It seems have been couple of days that the iOS Catalina bot failed to run tasks:

<img width="335" alt="Screen Shot 2020-12-08 at 11 25 11 AM" src="https://user-images.githubusercontent.com/54558023/101531527-413edf00-3948-11eb-9d44-7f53863f2730.png">

**Comment by godofredoc** [comment]
mac-12 was failing because of bad provisioning profile. The correct provisioning profile was installed and tests are now running and passing.
