### ISSUE TITLE
Regression: Top overflow is not working anymore since #71303

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#71936]
Since #71303 is merged, when you scroll up inside a refreshindicator sub widget, there is no overscroll effect anymore. 
If you scroll up with momentum you should get an overscroll effect, but it does not happen anymore.

The overscroll effect should only be disabled, if you reached the top and continue to swipe.

**Comment by chunhtai** [comment]
cc @xu-baolin , is it ok to assign this issue to you?

**Comment by xu-baolin** [comment]
Sure, go ahead.
