### ISSUE TITLE
UserAccountsDrawerHeader accountName and accountEmail don't need to be Widgets

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7193]
They should be Strings instead.

**Comment by Hixie** [comment]
This would prevent e.g. making a part of it bold. Is that what you want?

**Comment by abarth** [comment]
I think this is wont-fix.  We use `Widget` almost everywhere instead of `String` because it is much more flexible.

**Comment by eseidelGoogle** [comment]
OK.  I recall it feeling awkward to use this widget, but I see the reasoning.

I felt like when I was using this widget that I wanted it to be highly opinionated.
