### ISSUE TITLE
Allow icon button constructor to specify a left or right icon

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter#71941]
Currently we can not create Buttons with an icon at the right, well we can if we build it by our own, but flutter already have one constructor to help with that, the missing part is that it only allows you to put icons at the left of the button.

I was thinking to add the code and create a PR so I wanted to get some feedback before.

# Current
`FlatButton` or others have a named constructor `FlatButton.icon` which lets you specify an icon.
This icon is always on the left, the code looks like:

https://github.com/flutter/flutter/blob/8f3a12f1447b4baad06910eadd48b30a0a95e305/packages/flutter/lib/src/material/flat_button.dart#L300-L307

# Expected
Have one way to show it in the left or in the right, possible options:
- Add two named constructors, `leftIcon` and `rightIcon`.
- Add two parameters, `leftIcon` and `rightIcon` and only one of those can be supplied.

**Comment by jeet2307** [comment]
allow icon button to align in left or right side

**Comment by YazeedAlKhalaf** [comment]
I think this is important, I may be able to do a pull request.

**Comment by YazeedAlKhalaf** [comment]
> * Add two parameters, `leftIcon` and `rightIcon` and only one of those can be supplied.

I would prefer a boolean called `isRightIcon` by default false and is optional

**Comment by RoyARG02** [comment]
How about a parameter for the IconButton called `iconAlignment` which takes an enum `IconAlignment` which could be either `IconAlignment.left`(the default) or `IconAlignment.right`?

**Comment by YazeedAlKhalaf** [comment]
> How about a parameter for the button called `iconAlignment` which takes an enum `IconAlignment` which could be either `IconAlignment.left`(the default) or `IconAlignment.right`?

I think it will be a great solution and is scalable also. I will start working on it

**Comment by RoyARG02** [comment]
> One question though, since the IconAlignment will be used multiple times. Do I create a file for it or copy and paste it?

I think that should be defined at the same file as the class from which all buttons inherit their properties.

I'm not sure, but such change might require to be included twice in different places:
 - For old buttons(FlatButton, RaisedButton, and OutlineButton) in `flutter/packages/flutter/lib/src/material/button.dart`.
 - For new buttons(TextButton, ElevatedButton, and OutlinedButton) in `flutter/packages/flutter/lib/src/material/button_style_button.dart`.

Also, it might be great if this change depends on directionality(LTR or RTL text direction).

**Comment by YazeedAlKhalaf** [comment]
@RoyARG02 can you take a look at my PR and suggest things if it is possible

**Comment by YazeedAlKhalaf** [comment]
Thanks @RoyARG02 for your efforts

**Comment by YazeedAlKhalaf** [comment]
> Also, it might be great if this change depends on directionality(LTR or RTL text direction).

For RTL suport yuo can wrap a button with `Directionality()` widget and give it `textDirection` of `TextDirection.rtl` which makes everything start from right. That is why in PR I named the alignment properties start and end.

**Comment by HansMuller** [comment]
To reverse the default order in which the icon and label widgets appear, why not just write

```dart
TextButton.icon(label: bar, icon: foo)
```
instead of 
```dart
TextButton.icon(label: foo, icon: bar)
```

Also noted here: https://github.com/flutter/flutter/pull/71984#issuecomment-758280967

**Comment by sadespresso** [comment]
@HansMuller does it mess up the semantics?

**Comment by piedcipher** [comment]
All ButtonStyleButton widgets now have an [iconAlignment](https://api.flutter.dev/flutter/material/ButtonStyleButton/iconAlignment.html) property. Hence closing this issue.
