### ISSUE TITLE
Flutter precache doesn't cache configured platforms

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#71954]
`flutter precache` should populate the Flutter tool's cache of binary artifacts for all configured platforms by default.

The primary use case for this feature is to download the assets a user needs so that they can go offline and continue working.

Today it precaches iOS and Android, even if those platforms are disabled, and does not precache other configured platforms. This is non-intuitive and will lead to users who go offline having a mismatch between cached artifacts and available artifacts. (See, for example, [this log](https://gist.githubusercontent.com/timsneath/4ca67d86fba1c8f24229e2e8721c318a/raw/b684c2af055b914afa53bb915d4558c55b8daec4/precache.txt).) In addition, there's no reason why iOS and Android should be 'blessed' as the default -- in the future, Flutter users may be as likely to develop for other targets as those two mobile operating systems.

We should simplify the options from the current set of eight choices to two general usage patterns:
 - No flags set: cache artifacts for platforms that are enabled in `flutter config`
 - `--all-platform` flag: cache artifacts for all platforms

**Comment by jmagman** [comment]
@timsneath Can you chime in with your preference in https://github.com/flutter/flutter/issues/37184?  Duplicate.
