### ISSUE TITLE
Support web target

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7195]
Add support to deploy application to the web... Lots of similar framework do so, Haxe, LibGDX, Love2D, Juce, etc.

If someone could write-up how one would go about this technically, I'd be interested in contributing.

**Comment by eseidelGoogle** [comment]
We're not pursuing the Web as a deployment target for Flutter at this time.
https://flutter.io/faq/#does-flutter-run-on-the-web

Angular2 Dart is one way to share Dart-written code between Flutter-using apps and Web-targeted apps.
