### ISSUE TITLE
Unsupported conditional import of `dart:ui` for tests running on Chrome

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#71961]
## Steps to Reproduce

1. Create a Dart file in `lib` that has a conditional export like this:

```dart
export 'stub.dart'
    if (dart.library.html) 'dart:ui';
```

2. Use that code somewhere, so it is not tree-shaked.
3. Create a test that depends on that file.
4. Run the tests using `flutter test --platform chrome`.

**Expected results:** tests should run like normal (how they do do using just `flutter test`).

**Actual results:** 

>Invalid argument(s): Unsupported conditional import of `dart:ui` found in lib/created_file.dart.

<details>
  <summary>Doctor (click to expand)</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
```

</details>

**Comment by creativecreatorormaybenot** [comment]
I could not try it on `dev` because the code **does not use null safety**, however, `flutter test --platform chrome` on `dev` acts like the code uses NNBD 🤷 (non-null compile time errors).

**Comment by pedromassangocode** [comment]
Hi @creativecreatorormaybenot 
Can you please provide a minimal complete reproducible code sample?

This sounds a Dart issue to me, does it makes sense to file this bug in https://github.com/dart-lang/sdk/issues?
Thank you

**Comment by creativecreatorormaybenot** [comment]
@pedromassango Well, the reason I filed it here is because `flutter test` works just fine - just `flutter test --platform chrome` does not.

## Comprehensive reproducible example

1. `flutter channel beta`
2. `flutter channel upgrade`
3. `flutter config --enable-web`
4. `flutter create bug`
5. `cd bug`
6. Edit `lib/main.dart` to be the following:

```dart
import 'package:flutter/material.dart';

export 'dart:ui' // This would be a stub for the platform registry in a real app.
  if (dart.library.html) 'dart:ui';

void main() => runApp(Foo());

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container();
}
```

7. Edit `test/widget_test.dart` to be the following:

```dart
import 'package:bug/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('smoke', (tester) async {
    await tester.pumpWidget(Foo());
  });
}
```

8. `flutter test`
9. See that "All tests passed!"
10. `flutter test --platform chrome`
11. See the bug.

**Comment by creativecreatorormaybenot** [comment]
@pedromassango Well, the reason I filed it here is because `flutter test` works just fine - just `flutter test --platform chrome` does not.

## Comprehensive reproducible example

1. `flutter channel beta`
2. `flutter channel upgrade`
3. `flutter config --enable-web`
4. `flutter create bug`
5. `cd bug`
6. Edit `lib/main.dart` to be the following:

```dart
import 'package:flutter/material.dart';

export 'dart:ui';
export 'package:flutter/material.dart' // This would be a stub for the platform registry in a real app.
  if (dart.library.html) 'dart:ui';

void main() => runApp(Foo());

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container();
}
```

7. Edit `test/widget_test.dart` to be the following:

```dart
import 'package:bug/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('smoke', (tester) async {
    await tester.pumpWidget(Foo());
  });
}
```

8. `flutter test`
9. See that "All tests passed!"
10. `flutter test --platform chrome`
11. See the bug.


### Setup

Obviously my setup in the real app makes sense, whereas this does not make any sense. However, this is a minimal complete reproducible code sample.

**Comment by pedromassangocode** [comment]
I was able to reproduce this.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by yjbanov** [comment]
This was fixed in https://github.com/flutter/engine/pull/22874

**Comment by yjbanov** [comment]
Sorry, commented on the wrong issue.

**Comment by ditman** [comment]
@creativecreatorormaybenot is this to circumvent the web-only dart:ui methods?

This is how we've done this for the web plugins: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player_web/lib/src/shims

(The only difference is that we're exporting a file that exports 'dart:ui', instead of exporting 'dart:ui' directly, it seems?)

**Comment by creativecreatorormaybenot** [comment]
@ditman Yes, I did it the same way as you. However, I export `dart:ui` by default as well, so I can use a single "dart_ui" import instead of also importing `dart:ui` when importing the custom file.

Furthermore, I do not think it matters because the bug also happens for other conditional import cases, e.g. for https://github.com/znjameswu/flutter_math/blob/427e4ef8fe96977be56c06339d03fa6dcf462a7f/lib/src/render/svg/web/platform_svg.dart#L9.

**Comment by ditman** [comment]
Maybe related?

* https://github.com/flutter/flutter/issues/71612
* https://github.com/flutter/flutter/issues/50594

**Comment by creativecreatorormaybenot** [comment]
I think #50594 is not related (look into it before opening this one) because of #70714.

#71612 might be - I have certainly seen that issue occur while debugging this one..

**Comment by ferhatb** [comment]
@ditman : This might require ecosystem to reach sound mode everywhere or non-mixed language. Is the workaround acceptable, if so please set to low priority.

**Comment by ditman** [comment]
I am not entirely sure how to go about this. The latest tests I've written for web have all used `flutter drive` instead of `flutter test --platform chrome`. IIRC tests pass, and are able to use conditional exports of dart:ui (and other libs).

There are definitely some mentions of pain because of non-migrated code (which normally get solved by adding the `//@dart = 2.10` annotation), but this might be different.

(However, @ferhatb is correct, I haven't been able to migrate web plugin code to Null Safety yet because of some tools not being migrated yet.)

@creativecreatorormaybenot did you find a workaround for this?

**Comment by creativecreatorormaybenot** [comment]
@ditman No, I do not think I found a workaround, however, it is also not high priority for me.

**Comment by ditman** [comment]
Let's revisit this once null safety propagates everywhere in the ecosystem then!

**Comment by kevmoo** [comment]
I *think* conditional imports only support importing package libs – not `dart:`

CC @munificent @leafpetersen

**Comment by munificent** [comment]
> I _think_ conditional imports only support importing package libs – not `dart:`
> 
> CC @munificent @leafpetersen

I definitely could be wrong, but I wasn't aware of any limitations like that on conditional imports.

**Comment by ditman** [comment]
In a kinda tangentially related (but not really) turn of events, I've found myself running tests with platform chrome in a package that does conditional exports:

https://github.com/flutter/packages/pull/1756

However it's `dart test -p chrome`, not `flutter test`.

While investigating the above PR, I found that `flutter test` and `dart test` are similar (but quite different), so this is very likely some sort of flutter tool or flutter_test bug.

Apologies for the non-update, but I got reminded of this by the PR above (U_U)

**Comment by darshankawar** [comment]
Verified this issue by using below code sample (updated as applicable) and ran on latest stable (3.19.0) and beta with which there were no errors reported upon running the tests.

1. File structure and code sample used:

`main.dart`:

```
import 'package:flutter/material.dart';

export 'dart:ui';
export 'stub.dart' // This would be a stub for the platform registry in a real app.
if (dart.library.html) 'dart:ui';

void main() => runApp(Foo());

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container();
}
```

`lib/stub.dart`:

```
export 'stub.dart'
if (dart.library.html) 'dart:ui';
```

`widget_test.dart`:

```
import 'package:app_foo_stable/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('smoke', (tester) async {
    await tester.pumpWidget(Foo());
  });
}
```

```
dhs@Dhss-MacBook-Pro app_foo_stable % flutter test
00:08 +1: All tests passed!                                                                                                                                                
dhs@Dhss-MacBook-Pro app_foo_stable % flutter test --platform chrome
00:02 +1: All tests passed!                                                                                                                                                
dhs@Dhss-MacBook-Pro app_foo_stable % 

```

With above results, I'll go ahead and optimistically close as resolved. If anybody disagrees or still sees same error, write in comments and I'll reopen it.
