### ISSUE TITLE
Clicking on Autofill popup doesn't refresh screen

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#71977]
I have a form with TextFormFields.

I click to select the phone field.  The autofill comes up, I click it and visually nothing happens, but if I type a number, the full phone number appears

I noticed that the addlistener is not being called on the autofill popup click. 

Same for email, but autofill on name seems to work.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.25.0-5.0.pre.125, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

**Comment by pedromassangocode** [comment]
Hi @sgehrman 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
