### ISSUE TITLE
BottomNavigatorBar widget has problem with Color property

### ISSUE THREAD

**Issue by pallavc34** [flutter/flutter#71974]
BottomNavigationBar widget in flutter has a color problem where if I apply backgroundColor to BottomNavigationBar it does not change color but when I apply color to the first item in the list of BottomNavigationBar widgets, the whole bottom navigation bar changes color. 

Steps to Reproduce.
```
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class BottomNavigationBarWidget extends StatefulWidget {
  BottomNavigationBarWidget({@required this.selectedIndex});
  int selectedIndex;

  @override
  _BottomNavigationBarWidgetState createState() =>
      _BottomNavigationBarWidgetState();
}

class _BottomNavigationBarWidgetState extends State<BottomNavigationBarWidget> {
  @override
  Widget build(BuildContext context) {
    return BottomNavigationBar(
      // selectedItemColor: Colors.grey,
      // unselectedItemColor: Colors.blue,
      onTap: (value) {
        setState(() {
          widget.selectedIndex = value;
        });
      },
      currentIndex: widget.selectedIndex,
      items: [
        BottomNavigationBarItem(
          icon: FaIcon(
            FontAwesomeIcons.home
          ),
          label: "HomeScreen",
          // activeIcon: FaIcon(
          //   FontAwesomeIcons.home,
          //   size: 22,
          //   color: Colors.blue,
          // ),
        ),
        BottomNavigationBarItem(
          icon: FaIcon(
              FontAwesomeIcons.calendar
          ),
          label: "Calender",
          // activeIcon: FaIcon(
          //   FontAwesomeIcons.calendar,
          //   size: 22,
          //   color: Colors.blue,
          // ),
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.bar_chart),
          label: "Stats",
          // activeIcon: FaIcon(
          //   Icons.bar_chart,
          //   size: 22,
          //   color: Colors.blue,
          // ),
        ),
        BottomNavigationBarItem(
          icon: FaIcon(
              FontAwesomeIcons.cog
          ),
          label: "Settings",
          // activeIcon: FaIcon(
          //   FontAwesomeIcons.cog,
          //   size: 22,
          //   color: Colors.blue,
          // ),
        ),
      ],
    );
  }
}
```

Just put this code in any file and call the widget with any index from 0,1,2,3. 
Apply backgroundColor to BottomNavigationBar(). 

The color of the whole bar should change BUT IT DOES NOT CHANGE COLOR,

Now apply backgroundColor to BottonNavigationBarItem with label "HomeScreen" 

The whole color of BottomNavigationBar Changes INSTEAD OF JUST CHANGING THE COLOR OF FIRST ITEM

My flutter doctor summary.
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.662], locale en-IN)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pallav\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Redmi Note 4 (mobile) • 34f0409d0604 • android-arm64  • Android 9 (API 28)
    • Web Server (web)      • web-server   • web-javascript • Flutter Tools
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)            • edge         • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!

**Comment by ZainUrRehmanKhan** [comment]
**This is not an issue.**

There are two types of BottomnavigationBar: Fixed & Shifted, if the items in `BottomNavigationBar` is less then 4, the default type will be fixed. If it's 4 or greater then the type will be shifted. `BottomNavigationBarType.shifted` takes the color of its items and if null default will be white.

**Documentation From Code:**

```
/// The bottom navigation bar's [type] changes how its [items] are displayed.
/// If not specified, then it's automatically set to
/// [BottomNavigationBarType.fixed] when there are less than four items, and
/// [BottomNavigationBarType.shifting] otherwise.
///
///  * [BottomNavigationBarType.fixed], the default when there are less than
///    four [items]. The selected item is rendered with the
///    [selectedItemColor] if it's non-null, otherwise the theme's
///    [ThemeData.primaryColor] is used. If [backgroundColor] is null, The
///    navigation bar's background color defaults to the [Material] background
///    color, [ThemeData.canvasColor] (essentially opaque white).
///  * [BottomNavigationBarType.shifting], the default when there are four
///    or more [items]. If [selectedItemColor] is null, all items are rendered
///    in white. The navigation bar's background color is the same as the
///    [BottomNavigationBarItem.backgroundColor] of the selected item. In this
///    case it's assumed that each item will have a different background color
///    and that background color will contrast well with white.
```

```
  /// The color of the [BottomNavigationBar] itself.
  ///
  /// If [type] is [BottomNavigationBarType.shifting] and the
  /// [items] have [BottomNavigationBarItem.backgroundColor] set, the [items]'
  /// backgroundColor will splash and overwrite this color.
  final Color backgroundColor;
```
