### ISSUE TITLE
status of audio component

### ISSUE THREAD

**Issue by ross-albertson** [flutter/flutter#7198]
## Steps to Reproduce

What is the status of the audio playback component of Flutter? Please keep me posted at magnusthegood@yahoo.com. My name is Ross Albertson. 

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by sethladd** [comment]
Thanks for reaching out! I believe we removed the audio support, to be replaced with a "services plugin" (similar to how https://github.com/flutter/flutter/tree/master/examples/hello_services works). We'll work to make the services interop more accessible to developers so you (and others) can add awesome audio to Flutter.

I'm going to close this issue (hopefully the question has been answered), but keep us posted with your feedback.
