### ISSUE TITLE
[Issue] : Not able to control the Status Bar text colour and background after interaction with webView

### ISSUE THREAD

**Issue by achalukkhal** [flutter/flutter#71995]
```
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B29, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
```
Not able to control the Status Bar text colour and background. Once in-app browser/ WebView is opened as full-screen dialogue and popped out of the Navigation stack This issue is faced only on Android.

`
 SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
          statusBarColor: Colors.black,
          statusBarBrightness:
              Brightness.dark // dark == white status bar -- for IOS.
          ));`

The above code is working on IOS but not on Android.

Please Refer :
https://github.com/MaikuB/flutter_appauth/issues/159

**Comment by TahaTesser** [comment]
Hi @achalukkhal 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
