### ISSUE TITLE
Column intrinsic height measurement broken on latest dev

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#71990]
The cause of this issue is the transition from Flutter `dev` version `1.24.0-10.2.pre` (**working** height measurement) to Flutter `dev` version `1.25.0-4.0.pre`.  
I have two versions of the same app deployed with the **only difference** (confirmed in Git commit) being that SDK (+ Dart SDK) change in `pubspec.lock`.

## Problem

We are using `flutter_markdown` in a Flutter web app. In the Markdown, we display **lists**. I have nailed it down to `flutter_markdown` using a `Column` to display that list (see [code](https://github.com/flutter/flutter_markdown/blob/bb8f8fbe868a4d83669df16d989b6ba49c845c8e/lib/src/builder.dart#L295)).  

This is how the height measurement looks like between the versions in our use with Markdown.

| ### `1.24.0-10.2.pre`                                                                                                                                                     | ### `1.25.0-4.0.pre`                                                                                                                                                      |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="170" alt="Screen Shot 2020-12-09 at 10 57 55 AM" src="https://user-images.githubusercontent.com/19204050/101621237-66495580-3a0d-11eb-8783-b0c13b93de9f.png"> | <img width="175" alt="Screen Shot 2020-12-09 at 10 56 52 AM" src="https://user-images.githubusercontent.com/19204050/101621125-41ed7900-3a0d-11eb-87b2-655995c3d6eb.png"> |

### Context

The implementation of the widget that displays the `flutter_markdown` widgets in a table like that (the screenshots are parts of a table) uses the **intrinsic heights** of the Markdown widgets to figure out its height.

## Cause

> "Intrinsics are not available for CrossAxisAlignment.baseline."

It its [this commit](https://github.com/flutter/flutter/commit/7a3a29e71f0da5b3c45ac359b02582fc3b2514c0#diff-431d7468fa46efb49098b5710fab36c25a4c87cedd341322611fe7420d59d651) that broke this (in #70656).

**Comment by creativecreatorormaybenot** [comment]
cc @goderbauer 

I think [your commit](https://github.com/flutter/flutter/commit/7a3a29e71f0da5b3c45ac359b02582fc3b2514c0#diff-431d7468fa46efb49098b5710fab36c25a4c87cedd341322611fe7420d59d651) broke this (in #70656).

cc @dnfield 

Because you are probably familiar with the matter.

**Comment by creativecreatorormaybenot** [comment]
Okay, so the problem is pretty simple:

> "Intrinsics are not available for CrossAxisAlignment.baseline."

@goderbauer How is this supposed to be handled now / is this changed described somewhere?

@dnfield Does `flutter_markdown` need to be update to account for this change or do we need to change something?

**Comment by creativecreatorormaybenot** [comment]
So I found a migration guide in https://github.com/flutter/website/pull/5007, however, this is only for `RenderObject` subclasses that are used in render objects that depend on intrinsic sizes. This applies to **neither** `flutter_markdown` _nor_ to our table because that one does not need to report intrinsic sizes itself anymore (as far as I understand).

### Render object subclasses

@goderbauer Is this an intended breaking change in this case? I do not see render object subclasses in `flutter_markdown` and our own render object is the root of the screenshot, so would also not apply to that migration guide I think 🤔

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser Would say in this case all necessary information was already available - here you go anyway:

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19041.630], locale en-150)
    • Flutter version 1.25.0-4.0.pre
    • Framework revision a7f5fd5360 (9 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)
```

</details>

<details>
<summary>Complete reproducible minimal code sample</summary>

### `pubspec.yaml`

```dart
name: bug
description: https://github.com/flutter/flutter/issues/71990
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.5.1
```

### `main.dart`
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: IntrinsicHeight(
          child: Row(
            children: [
              MarkdownBody(
                  data:
                      '* A list entry.\n* Another list entry.\n* And yet another one.\n* Guess what? Here is another one.\nDid you think I was done already or what?'),
              MarkdownBody(
                  data:
                      '* So here we go again, I suppose.\n* Adding another entry to the list.\n* And maybe another one.\n* And just one more - this is the last one. I promise :)'),
            ],
          ),
        ),
      ),
    ),
  ));
}
```

</details>

The works before #70656 and throws afterwards (broken on current `dev` version, works on previous). I explained the situation above. I reckon @goderbauer knows.

**Comment by HansMuller** [comment]
CC @goderbauer

**Comment by goderbauer** [comment]
@creativecreatorormaybenot Can you post the full exception you're seeing (not just the error message)?

**Comment by goderbauer** [comment]
```
I/flutter (15890): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15890): The following assertion was thrown during performLayout():
I/flutter (15890): Intrinsics are not available for CrossAxisAlignment.baseline.
I/flutter (15890): 'package:flutter/src/rendering/flex.dart':
I/flutter (15890): Failed assertion: line 523 pos 9: 'RenderObject.debugCheckingIntrinsics'
I/flutter (15890): 
I/flutter (15890): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15890): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15890): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15890):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter (15890): 
I/flutter (15890): The relevant error-causing widget was:
I/flutter (15890):   IntrinsicHeight file:///Users/goderbauer/dev/playground/lib/main.dart:9:16
I/flutter (15890): 
I/flutter (15890): When the exception was thrown, this was the stack:
I/flutter (15890): #2      RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:523:9)
I/flutter (15890): #3      RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:632:12)
I/flutter (15890): #4      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1373:23)
I/flutter (15890): #5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:301:23)
I/flutter (15890): #6      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1371:42)
I/flutter (15890): #7      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1731:12)
I/flutter (15890): #8      RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:635:60)
I/flutter (15890): #9      RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:543:39)
I/flutter (15890): #10     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:632:12)
I/flutter (15890): #11     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1373:23)
I/flutter (15890): #12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:301:23)
I/flutter (15890): #13     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1371:42)
I/flutter (15890): #14     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1731:12)
I/flutter (15890): #15     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:635:60)
I/flutter (15890): #16     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:594:58)
I/flutter (15890): #17     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:632:12)
I/flutter (15890): #18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1373:23)
I/flutter (15890): #19     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:301:23)
I/flutter (15890): #20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1371:42)
I/flutter (15890): #21     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1731:12)
I/flutter (15890): #22     RenderIntrinsicHeight._computeSize (package:flutter/src/rendering/proxy_box.dart:797:38)
I/flutter (15890): #23     RenderIntrinsicHeight.performLayout (package:flutter/src/rendering/proxy_box.dart:817:12)
I/flutter (15890): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #25     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:430:14)
I/flutter (15890): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #27     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (15890): #28     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:911:7)
I/flutter (15890): #29     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (15890): #30     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
I/flutter (15890): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #35     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1373:11)
I/flutter (15890): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #52     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3364:13)
I/flutter (15890): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #56     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
I/flutter (15890): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #65     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:518:11)
I/flutter (15890): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
I/flutter (15890): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (15890): #71     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
I/flutter (15890): #72     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (15890): #73     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (15890): #74     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:454:19)
I/flutter (15890): #75     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:900:13)
I/flutter (15890): #76     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
I/flutter (15890): #77     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
I/flutter (15890): #78     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1057:9)
I/flutter (15890): #79     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
I/flutter (15890): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (15890): 
I/flutter (15890): The following RenderObject was being processed when the exception was fired: RenderIntrinsicHeight#0b5e2 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (15890):   creator: IntrinsicHeight ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (15890):     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (15890):     _InkFeatures-[GlobalKey#7f0f6 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (15890):     PhysicalModel ← ⋯
I/flutter (15890):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (15890):   constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=813.1)
I/flutter (15890):   size: MISSING
I/flutter (15890): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (15890):     child: RenderFlex#1e298 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):       child 1: RenderFlex#b095f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):         child 1: RenderFlex#74c1f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):           child 1: RenderConstrainedBox#b9af8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child: RenderParagraph#5b30c NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):           child 2: RenderFlex#ff0e1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child 1: RenderWrap#54e29 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):         child 2: RenderConstrainedBox#bb66c NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):         child 3: RenderFlex#8f31b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):           child 1: RenderConstrainedBox#fdb08 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child: RenderParagraph#8b6a6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):           child 2: RenderFlex#acaf5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child 1: RenderWrap#e3e68 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):         child 4: RenderConstrainedBox#e07ba NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):         child 5: RenderFlex#49203 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):           child 1: RenderConstrainedBox#c5900 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child: RenderParagraph#57fb8 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):           child 2: RenderFlex#4b309 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child 1: RenderWrap#1429c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):         child 6: RenderConstrainedBox#37486 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):         child 7: RenderFlex#da40e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):           child 1: RenderConstrainedBox#f8c89 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child: RenderParagraph#54d3e NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890):           child 2: RenderFlex#48567 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child 1: RenderWrap#fa837 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):       child 2: RenderFlex#65fcf NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):         child 1: RenderFlex#c32bd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):           child 1: RenderConstrainedBox#f82d6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (15890):             child: RenderParagraph#3df25 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (15890): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by creativecreatorormaybenot** [comment]
@goderbauer Sorry, I should have included it with the sample. Thanks for posting it!

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Thanks for the reproducible code sample, I can reproduce the issue 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.25.0-4.0.pre at C:\Code\flutter_dev
    • Framework revision a7f5fd5360 (10 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 87.0.664.57

• No issues found!
```

</details>

**Comment by creativecreatorormaybenot** [comment]
@goderbauer Do you have some insights or steps on how this can be resolved?

**Comment by goderbauer** [comment]
I am surprised that you identified #70656 as the breaking commit. Can you double-check that this wasn't "broken" before? My guess is that this should have started "breaking" with https://github.com/flutter/flutter/pull/70139. "Breaking" this was the whole intention of that commit.

Some Background: Flutter cannot calculate the intrinsic sizes of widgets, whose size depend on a child's baseline since the baseline metrics are only available after a full layout pass. Prior to https://github.com/flutter/flutter/pull/70139 a column or row configured with `CrossAxisAlignment.baseline` would just lie and report an incorrect intrinsic size, resulting in incorrect rendering (i.e. the column/row did not actually baseline-align its children as specified when wrapped in an Intrinsics widget). In https://github.com/flutter/flutter/pull/70139 we make that problem explicit by throwing if a basline-aligned column/row is asked for its intrinsics.

Long story, short: If you need intrinsics, you cannot use `CrossAxisAlignment.baseline`. Or if you want `CrossAxisAlignment.baseline` you can't use intrinsics. Again, that's not really a new limitation. Previously, we were just silently ignoring the baseline alignment in this combination.

In the example in https://github.com/flutter/flutter/issues/71990#issuecomment-741840079 why do you need the IntrinsicsHeight widget to begin with? I don't know much about the internals of the markdown package, but it does seem odd to me that MarkdownBody want to take up all available vertical space instead of just sizing itself to its content. If it were to do that, my guess is you wouldn't need intrinsics?

(The other way to fix this would of course be for flutter to lie again and report incorrect intrinsics sizes for baseline alignment, but I'd really prefer to not do that as it results in incorrect (and often unexpected) rendering results...)

**Comment by creativecreatorormaybenot** [comment]
@goderbauer Thanks so much for your answer ❤️ 

Well, I suppose I overlooked #70139 - so thank you for pointing that out.

It strikes me that it was "lying" before because the intrinsic height always seemed correct in the cases 🤔   
That PR also explains why it is broken in release mode as well (because it is not only the assertion; you are also returning `0.0`).

---

### Why do we need the intrinsic height?

The example was just dumbed-down, to have something minimal. In our actual implementation, we have a table.  
In that table, we want to be able to set background colors for whole cells, for example.

In order to do that, each cell **in a row** needs to know _the height of its row_. The row in the table will be sized based on the intrinsic heights and that will be passed as the height constraint to each cell in that row. Flutter's [`Table`](https://api.flutter.dev/flutter/widgets/Table-class.html) widget **does not** use intrinsic height measurements, which is also why you are not able to set background colors for cells if the row has cells with different heights.

By the way, we simple use a custom `RenderBox` that layouts its `children` (`MultiChildRenderObjectWidget`) in a table, with rows and columns that go way beyond what the basic `Table` widget offers. As a consequence, we need intrinsic sizing.

### Markdown

I do not think that `MarkdownBody` wants to size itself to full available vertical space. Again, we use intrinsic heights not for constraining height - instead we use it for _expanding_ the height of cells in a row that are not as tall as the tallest cell in a row.

Here is an illustration:

![image](https://user-images.githubusercontent.com/19204050/102427377-1d932d00-4009-11eb-9539-caf9383b9e47.png)

If we were not to use intrinsic height measurements for the first row in that table, we would not be able to center the outer two cells and color them as well.

### Baseline alignment

In fact, we do not use baseline alignment anywhere.

The only place where it is used is in `flutter_markdown`: https://github.com/flutter/flutter_markdown/blob/bb8f8fbe868a4d83669df16d989b6ba49c845c8e/lib/src/builder.dart#L324

@dnfield Is there a way to get rid of that baseline alignment somehow?

**Comment by goderbauer** [comment]
So you need the intrinsics because the cells are painting their own background and they need to fill all available space? As a suggestion, could cells size themselves to their natural size and then your table render object positions them where they need to be (centered) and also draws the background into all available space behind them? With that approach you probably get away without intrinsics (and thus also get a more performant implementation).

**Comment by dnfield** [comment]
From some offline discussion with @goderbauer -  it's unfortunate that we have this incompatibility in the way layouts work in the framework, where two different packages can make widgets that are not allowed to be composed and there's no way to determine that until runtime.

For flutter_markdown - I'm not super familiar with the package, but maybe it's possible to have it take some kind of flag to determine what kind of baselining it uses, with documentation about the caveats of each (e.g. one gives proper baselining when you have multiple lines of text but doesn't allow intrinsics, and one allows intrinsics but will fail for certain types of text). I've added that idea to the markdown bug.

It would be helpful to just have a small example of what's causing this - that could help determine if there's some way to work around this, and may be helpful to other users arriving at this issue.

**Comment by creativecreatorormaybenot** [comment]
@goderbauer @dnfield Thanks so much for your input - I will see what I can do.

Unfortunately, the background color is not the only reason it is useful to use intrinsic sizing. It would probably be possible to write a render box that take care of all of this (positioning, coloring, etc.) of all cells, however, that severely limits what kind of widgets can be used in cells. As of now, we do not work with parent data at all because the table content is completely dynamic (based on loaded content), which is convenient.

I think making a PR to make the baseline alignment optional in `flutter_markdown` is the way to go for this problem 👌

**Comment by creativecreatorormaybenot** [comment]
I consider this issue resolved from the Flutter side of things.

flutter/flutter_markdown#311 for further reference.
