### ISSUE TITLE
Add examples of Material Design Card Content Blocks to gallery demo

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#72]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/28_

----

_From @eseidelGoogle on July 14, 2015 16:58_

Cards have specific layout patterns for their content:
http://www.google.com/design/spec/components/cards.html#cards-content-blocks

We should provide some helpers to get those layouts as part of the Sky Framework.

FYI @HansMuller 

_Copied from original issue: domokit/mojo#319_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_

----

_From @eseidelGoogle on July 14, 2015 16:59_

I may actually work on this some as part of the address_book demo I'm building as part of implementing proper text fields, we'll see:
http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

**Comment by Hixie** [comment]
There are so many different kinds here, it's not clear how useful it would be to actually prepackage these. We should probably have a few examples in the material gallery but not make explicit widgets. (We do need widgets for all the subparts, but that's mostly done already except for icon buttons.)

**Comment by sethladd** [comment]
Hi @HansMuller is this something we're doing now, or plan to do in the Gallery?

**Comment by HansMuller** [comment]
Yes, a collection of demos based on https://www.google.com/design/spec/components/cards.html is needed for the gallery. We also need a relatively simple demo of cards/elevations/shadows.

**Comment by sethladd** [comment]
Ah, https://github.com/flutter/flutter/issues/1551 dupes this issue. Closing this one.
