### ISSUE TITLE
Add support for hover, add, and remove pointers

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#720]
- [x] The "Pointer" struct doesn't represent a pointer, it represents a snapshot of pointer state. We should rename it to "PointerStateSnapshot" or "PointerData" or some such.
- [x] The "PointerPacket" class should then be renamed something like "PointerDataPacket" or something.
- [x] The "PointerType" enum should be renamed "PointerDisposition" or some such.
- [x] The "Pointer" struct should lose its "down" (redundant with the stream of events), "primary" (not going to be supported), and "distance_min" (always 0 by definition) fields.
- [x] We should implement all the fields on the Java side (distance, radius, orientation, tilt, and stylus/mouse aren't yet supported).
- [x] We should add add/remove notifications.
- [ ] We should actually send add/remove notifications.
- [ ] We should add support for hover pointers.
- [ ] The service side should never send an "up" event that is moved away from where the last "move" event was. (Same for "cancel", and, if hover events are supported, "down".)

**Comment by sethladd** [comment]
Did we want to include this work in the "API stability" efforts?

**Comment by Hixie** [comment]
Not sure. We have to do it eventually. Some of these changes are pretty low-level and many aren't critical for our near-term goals.

**Comment by abarth** [comment]
I did a bunch of these, but there are more left to do.  Unassigning.

**Comment by abarth** [comment]
I think we can remove this from the API stability label.  The API is in the shape we want (and we send all the events we're considering on Fuchsia).  We just might start sending more events on more platforms.

**Comment by zoechi** [comment]
Related #5504

**Comment by gspencergoog** [comment]
I believe that all of these are addressed.
