### ISSUE TITLE
Canvas constructor shouldn't require a cull rect

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7201]
For most use cases, we can use the cull rect that the picture recorder computes.

**Comment by Riyuzakii** [comment]
Hey,It's my first time on Github.
I would like to help, if you tell me how to.
I have a Linux system and some free time.

**Comment by eseidelGoogle** [comment]
Is this still a valid issue?  With API stability declared, unclear if we'll want to do this?  I guess we could make the cull rect optional?
