### ISSUE TITLE
iOS: Share engine thread hosts between multiple engines

### ISSUE THREAD

**Issue by xster** [flutter/flutter#72019]
Let engines in a FlutterEngineGroup share the same threads.

**Comment by gaaclarke** [comment]
The work done in https://github.com/flutter/flutter/issues/72319 and https://github.com/flutter/flutter/issues/72010 makes this work for iOS.  Some work needs to be done on the Android embedder side to make this true for Android.  @xster

**Comment by eggfly** [comment]
Is it ok to close this issue of iOS now?
