### ISSUE TITLE
Share font collections between multiple engines

### ISSUE THREAD

**Issue by xster** [flutter/flutter#72024]
Let engine instances in the same FlutterEngineGroup use the same font collection and thus share the various downstream glyph layout metrics data etc. 

There's still seemingly a bug in https://docs.google.com/document/d/1wRl4vEbxgj7Q247xdxQ9hYDbiakT1g2dXmdprPIUatE/edit?ts=5f8881bc#heading=h.jw17g9alwqpy possibly relating to asset bundled custom fonts that would need addressing too.

**Comment by gaaclarke** [comment]
This will be easier to do once the plumbing is done in https://github.com/flutter/engine/pull/23549 since the FontCollection lives in the Engine.
