### ISSUE TITLE
Create multi-engine memory benchmark

### ISSUE THREAD

**Issue by xster** [flutter/flutter#72026]
Create an integration test as a memory benchmark on Android and iOS to launch 1 engine, then launch multiple other engines and then asserting that the overhead cost of additional engine doesn't regress past the initial accepted threshold (currently looking to be 58kB on iOS and 570kB on Android in Dec 2020 prototype).

**Comment by gaaclarke** [comment]
**Offline message from infra team:**

1. Create a new `add_to_app_benchmark.dart` file in https://github.com/flutter/flutter/tree/master/dev/devicelab/bin/tasks
2. Write `add_to_app_benchmark.dart` such that running `dart add_to_app_benchmark.dart` on a devicelab machine with an Android/iOS device attached would generate a json file with metrics.
3. Create corresponding prod builders (mac/linux) in flutter/infra config: https://github.com/flutter/infra/blob/master/config/devicelab_config.star
  3.1 this will allow a flutter PR to automatically trigger the test once merged.
  3.2 Linux/android and Mac/android are done migration, which means no blocker on an android test
  3.3 Mac/ios is still WIP, and there is some blocker.
4. If you want this test to affect the tree status, then enable it: https://github.com/flutter/flutter/blob/master/dev/prod_builders.json

**JSON format:**

Please refer to `TaskResult`: https://github.com/flutter/flutter/blob/998d1c6523513c15c58d5b66f01dffcc381ddf54/dev/devicelab/bin/run.dart#L115
