### ISSUE TITLE
[engine] On Win7, build of engine targeting Windows fails with SDK (10.0.19041.0)

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#72038]
**This issue is only for the record**

Win7 is not officiall supported as build environment of Flutter engine targeting Windows platform, according to https://discord.com/channels/608014603317936148/608020180177780791/785695884682854440
It works somehow

---

## Steps to Reproduce

1. Prepare an Win7
  - System image: https://msdn.itellyou.cn/
  - PowerSehll 3.0+: https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7
  - .Net 4.5+: https://www.microsoft.com/en-us/download/details.aspx?id=30653
2. Install VS 2019 with workload `Desktop development with C++`
  - The workload comes with a Windows 10 SDK
  - You could uncheck the Windows 10 SDK and install a standalone version later
3. Install standalone Windows 10 SDK (10.0.19041.0)
  - https://docs.microsoft.com/en-us/visualstudio/releases/2019/history
  - Install `Debug Tools for Windows` only if you uncheck the SDK in step 2. Or Install a full SDK
4. Do everything else to build the Flutter engine targting Windows
  - https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows

---

If you install an earlier version, i.e. 10.0.18362,0, eirther withing workload or a standalone, installing 19041 will fails the build as well.

Upgrading the `Debug Tools for Windows` is enough to fail the build

Downgrading the SDK doesn't work. Reinstall the system is the only way I find works.

## Logs

build log

```cmd
[87/639] ACTION //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/win:clang_x64)
FAILED: gen/flutter/lib/snapshot/vm_isolate_snapshot.bin gen/flutter/lib/snapshot/vm_snapshot_instructions.bin gen/flutter/lib/snapshot/isolate_snapshot.bin gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin
C:/tools/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe ../../build/gn_run_binary.py gen_snapshot.exe --enable-experiment=non-nullable --snapshot_kind=core --enable_mirrors=false --vm_snapshot_data=C:/Users/user/flutter-engine/engine-bisect/src/out/host_debug_unopt/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin --vm_snapshot_instructions=C:/Users/user/flutter-engine/engine-bise
ct/src/out/host_debug_unopt/gen/flutter/lib/snapshot/vm_snapshot_instructions.bin --isolate_snapshot_data=C:/Users/user/flutter-engine/engine-bisect/src/out/host_debug_unopt/gen/flutter/lib/snapshot/isolate_snapshot.bin --isolate_snapshot_instructions=C:/Users/user/flutter-engine/engine-bisect/src/out/host_debug_unopt/gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin --enable_asserts C:/U
sers/user/flutter-engine/engine-bisect/src/out/host_debug_unopt/flutter_patched_sdk/platform_strong.dill
ninja: build stopped: subcommand failed.
```

engine git log

```git
commit 8d4b7f3a68a77aaf11fc2e54229030397af16eb3
Author: Gary Qian <garyq@google.com>
Date:   Tue Dec 8 23:58:01 2020 -0700

    Add split AOT loading unit failure/error code path (#22857)
```

**Comment by gspencergoog** [comment]
Windows7 builds are not officially supported, so we're (bug triage) going to close this, now that it has been recorded.

**Comment by Sunbreak** [comment]
As the build crashed at the last step of linking, I guess it is related to Clang update https://crrev.com/8ad4334aaaf0bab5b56a981174ed92421ab1cc20

Something similar happened:

 - Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1150302#c9
 - Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1699228
