### ISSUE TITLE
Calling popAndPushNamed throws exception

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#7203]
If there's more than one route in the current stack and when popAndPushNamed is called(or calling pop and then push), the following exception will be thrown:

I/flutter ( 6710): NoSuchMethodError: The getter 'subtreeContext' was called on null.
I/flutter ( 6710): Receiver: null
I/flutter ( 6710): Tried calling: subtreeContext
I/flutter ( 6710): When the exception was thrown, this was the stack:
I/flutter ( 6710): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter ( 6710): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter ( 6710): #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:579)
I/flutter ( 6710): #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:653)
I/flutter ( 6710): #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:596)
I/flutter ( 6710): #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)

**Comment by eseidelGoogle** [comment]
@Hixie and @HansMuller know about heros and routes. :)

**Comment by vy0592** [comment]
any updates on this issue?

**Comment by HansMuller** [comment]
I've also run into it as part of fixing #7365, #6544 (see https://github.com/flutter/flutter/issues/7365#issuecomment-273947240). Working on a fix today.
