### ISSUE TITLE
GOMA builds for developers are broken since switching to Fuchsia RBE 

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#72032]
per @godofredoc - we need to use binaries from Fuchsia and use the right endpoint.

@cbracken, myself, and him tried some different attempts at getting it working locally but something still seems off.

/cc @flar @xster who were also in those chats

I'm not quite sure of the right priority for this, but it seems like it should be high. Local builds take a substantial amount of time for engine developers without GOMA.

@cyanglaz may know the steps.

**Comment by godofredoc** [comment]
Can you please give it a try to the following script?

```
#!/bin/bash
  

readonly GOMA_AUTH="$HOME/flutter_goma/goma_auth.py"
readonly GOMA_CTL="$HOME/flutter_goma/goma_ctl.py"
readonly GOMACC="$HOME/flutter_goma/gomacc"
readonly GOMA_HTTP2_PROXY="$HOME/flutter_goma/http_proxy"
readonly GOMA_HTTP2_PROXY_PORT="8199"
GOMA_CACHE_DIR="$HOME/flutter_goma_cache"
# The URL of the backend cannot be read from prebuilt. Hard-code it for now.
BACKEND_URL="rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog"

# Download client
echo 'fuchsia/third_party/goma/client/${platform}  release' | ~/depot_tools/cipd ensure -ensure-file - -root $HOME/flutter_goma

# Authenticate
$HOME/flutter_goma/goma_auth login
GOMA_LOCAL_OUTPUT_CACHE_DIR="$GOMA_CACHE_DIR" "$GOMA_CTL" ensure_start
```

**Comment by dnfield** [comment]
I still get mostly backend errors and very slow compilation.

**Comment by dnfield** [comment]
![image](https://user-images.githubusercontent.com/8620741/101809872-eedafb00-3acc-11eb-9958-6dfb604eba5c.png)

**Comment by godofredoc** [comment]
seems like we need some additional steps:

```
# run the script above
unset $USE_GOMA
rm -rf $HOME/goma
export GOMA_DIR=$HOME/flutter_goma
./flutter/tools/gn --unopt --goma
autoninja -C out/host_debug_unopt
```

I rebooted my machine to make it easier for me to validate the steps. We may require to kill some other processes too.

**Comment by dnfield** [comment]
I did some steps similar to those, but still get the 200 backend errors. Could this be some kind of auth/permissions issue?

**Comment by dnfield** [comment]
Quick update:

At this point, I'm pretty sure thi shas to do with my local Xcode toolchain being unsupported by Fuchsia RBE. If I build Android it seems to work fine, and Goodfredo is building on Linux which is working fine. CI is working fine for macOS host, but it's also using Xcode 11.0 whereas I'm using 12.2.

We're going to try to follow up with some Fuchsia GOMA folks to see if we can get the backend to support some more toolchains.

**Comment by dnfield** [comment]
Ok, the problem is that RBE doesn't allow for headers or sources outside of the parent directory - so a workaround is to make symlinks for the SDK/sysroot and pointing ninja towards those, and then RBE works again. e.g.:

```
ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain buildtools/XcodeDefault.xctoolchain
ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk buildtools/MacOSX11.0.sdk
```

and then setting the right GN args. We can update our buildroot to just do this automatically if you're using GOMA.

/cc @chinmaygarde @cbracken who might have an even brighter idea.

**Comment by dnfield** [comment]
Remaining here: document how to use the new changes to buildroot locally.

**Comment by dnfield** [comment]
I think once flutter/engine#23150 lands we can close this.

I've updated the wiki at https://github.com/flutter/flutter/wiki/Compiling-the-engine with up to date instructions for building with goma for iOS/macOS targets.
