### ISSUE TITLE
image cache randomly swaps content / returns wrong image on armv7l

### ISSUE THREAD

**Issue by nicoroy2561** [flutter/flutter#72054]
I have a customer that has an old Motorola Moto g4, architecture armv7l.
My app (a game) uses a lot of images (loaded mostly with Image.asset()), and on his phone after a while they randomly swap (an image appearing in the place of another, at random). They aren't even always from within the same folder, so their keys should be different in the cache.
The images themselves being pixel-art aren't big at all - they total out at less than 1.5MB of memory, with around 500 images in cache.
I did try clearing the image cache frequently, but the issue is still present.
Also, it seems not to matter wether the address of the image is a static one (eg "assets/images/folderA/1.png") or a dynamically calculated one (eg "assets/images/folderA/${i+1}.png"). It is not that the phone is doing some weird calculations, it seems the cache is returning the wrong data for the given key.
It seems not to be present on any other device so far.

## Steps to Reproduce
Just having an armv7l phone, I guess. I couldn't find one to test and reproduce it myself, but it seems to happen pretty consistently.

**Expected results:** 
The images in their correct place.

**Actual results:** 
Images swapping seemingly at random.

<details>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale ja-JP)
    • Flutter version 1.22.4 at /Users/Roy/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Roy/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>

**Comment by pedromassangocode** [comment]
Hi @nicoroy2561 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
I'm not sure if we can consider this as a valid issue without a reproducible code sample.

I would suggest you to try to copy the code that you use to show the images and create a minimal reproducible code sample. There is nothing to do with this issue without a minimal code sample that reproduces the issue.

Thank you

**Comment by nicoroy2561** [comment]
@pedromassangocode 
It's hard for me to provide some code because It seems to happen randomly.
What I mean is that there isn't a specific part of the game where it happens, it just happens to affect any image.
It seems to me that, when it occurs, both animations and Transforms break as well (judging from the pictures my customer sent me). But it's hard to say.

The specific code that I use to show images is the following:
```
Image.asset(
                          "assets/images/" + src,
                          filterQuality: FilterQuality.none,
                          fit: BoxFit.fill,
                          width: width,
                          height: height,
                          color: color,
                        )
```

Would attaching screenshots that show the issue help?

**Comment by pedromassangocode** [comment]
> Would attaching screenshots that show the issue help?

I think a reproducible test case would help better find the cause.

**Comment by dnfield** [comment]
Yes, a reproduction would be really helpful. We do run a lot of tests on the Moto G4, but I don't think we actually do screen diffing against images loaded from the cache on them.

Does this problem go away if you completely disable the image cache?

Does it go away if you avoid specific images, or a specific number of images?

If they're sprites - are you sure it's actually the wrong asset, or are you just sometimes getting the wrong "slice" of the sprite?

**Comment by nicoroy2561** [comment]
@pedromassango @dnfield
It seems the bug happens pretty often / ban be rather easily reproduced on my live app (https://play.google.com/store/apps/details?id=com.dungeonmasters.app) - on a Moto G4.
My client has since switched to playing on BlueStacks - where there are no issues. Also, no other phone for now has been reported doing this.

I haven't tried disabling the image cache..I might try it just to report it here, but otherwise it doesn't sound like a solution (worst performance on every device except that 4-yo one?).
Given I am not able to reproduce the bug myself, I do not know if it goes away avoiding specific images. The screenshots that 

I was shown showed stuff from different folders, swapping at seemingly random. All the pictures in my game are PNGs - all those confirmed swapping are.

I double checked the logic behind showing the sprites that were found swapping, and there were no errors there - some were not even computing the asset file path at runtime (it was just a hard-coded string).
Also, I do not use single assets that I then slice within the app - I just have a separate PNG for each sprite.

**Comment by dnfield** [comment]
To be clear - disabling the image cache isn't meant to be a fix, but to try to eliminate possible sources of the problem :)

**Comment by pedromassango** [comment]
@nicoroy2561 
I think what you can do to help us, is to kind like copy/paste the code that loads the images in a brand new flutter app and provide it here. It is almost impossible to find a bug without any code that reproduce the issue. This may be a device specific issue, but if you provide some code, anyone with that same device specifications can confirm the issue.

**Comment by nicoroy2561** [comment]
I'll close this issue as I can't reproduce it myself (seems to be only present on a handful of old devices) and I haven't had reports of this happening of recent.

Thank you all for the time.
