### ISSUE TITLE
Launching lib\main.dart on sdk gphone x86 arm in debug mode... Running Gradle task 'assembleDebug'...

### ISSUE THREAD

**Issue by ShadowProcess** [flutter/flutter#72053]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:4.1.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:4.1.1.
         > Could not get resource 'http://jcenter.bintray.com/com/android/tools/build/gradle/4.1.1/gradle-4.1.1.pom'.
            > Could not HEAD 'http://jcenter.bintray.com/com/android/tools/build/gradle/4.1.1/gradle-4.1.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72.
         > Could not get resource 'http://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.72/kotlin-gradle-plugin-1.3.72.pom'.
            > Could not HEAD 'http://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.72/kotlin-gradle-plugin-1.3.72.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ShadowProcess** [comment]
help me

**Comment by ShadowProcess** [comment]
I didn't use any agent;
I am in China.

**Comment by ShadowProcess** [comment]
The following is my configuration:

![image](https://user-images.githubusercontent.com/47808183/101739987-3f6d4b00-3b03-11eb-9bdf-935465ff2859.png)

**Comment by ShadowProcess** [comment]
flutter doctor:

![image](https://user-images.githubusercontent.com/47808183/101740166-75123400-3b03-11eb-9a08-00225b48a108.png)

**Comment by pedromassangocode** [comment]
Hi @ShadowProcess 
Looks like you are using an old version of Flutter. The current stable version is `1.22.4`.

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by ShadowProcess** [comment]
> 嗨@ShadowProcess
> 看起来你使用的是旧版本的颤振。当前的稳定版本是`1.22.4`。
> 
> 您能否升级到最新版本， `stable`然后重试
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`

First of all, thank you for your answer,I did as you said, But the result is the same

![image](https://user-images.githubusercontent.com/47808183/101856995-75f9a300-3ba1-11eb-82cd-7b974d5f99c9.png)

![image](https://user-images.githubusercontent.com/47808183/101857980-ab06f500-3ba3-11eb-8885-fc02b9fa9fd5.png)

![image](https://user-images.githubusercontent.com/47808183/101858043-c5d96980-3ba3-11eb-9ac4-46f2488a0de1.png)

Still so:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':path_provider'.
> Could not resolve all artifacts for configuration ':path_provider:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.3.0.
     Required by:
         project :path_provider
      > Could not resolve com.android.tools.build:gradle:3.3.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.3.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> Could not get unknown property 'android' for project ':path_provider' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ShadowProcess** [comment]
I did three things, Then a miracle happened, it is ready;

step 1:  I opened the agent
![image](https://user-images.githubusercontent.com/47808183/101867883-2f16a800-3bb7-11eb-834f-d1223f3c15a2.png)

step 2: I imported three certificates, respectively are "dl.google.com"、"storage.flutter-io.cn"、"jcenter.bintray.com"
![image](https://user-images.githubusercontent.com/47808183/101867867-1e663200-3bb7-11eb-8cff-3c4ba7693f72.png)

step 3: I added a repository
![image](https://user-images.githubusercontent.com/47808183/101867804-ff67a000-3bb6-11eb-88cc-efcb0fa05179.png)

**Comment by ShadowProcess** [comment]
I Think only the third one is useful,
I put the problem down to China`s internet controls,
Thanks,my friend.
