### ISSUE TITLE
After running, switch to The Chinese keyboard, TextField control input Chinese will crash. English keyboard input English and numbers will not crash.

### ISSUE THREAD

**Issue by Sunshine218** [flutter/flutter#72051]
flutter: Observatory listening on http://127.0.0.1:61481/vsds7rQTGrU=/
flutter: will switch to default route name:login
2020-12-10 11:42:14.437897+0800 letalk[64246:2049380] resize window
flutter: init account list=[{account: 2526018, password: zzz13579}, {account: 2547189, password: zzz13579}, {account: 2525841, password: zzz13579}])
2020-12-10 11:42:46.276695+0800 letalk[64246:2049380] Metal API Validation Enabled
2020-12-10 11:42:50.115947+0800 letalk[64246:2049380] [General] An uncaught exception was raised
2020-12-10 11:42:50.116034+0800 letalk[64246:2049380] [General] -[__NSCFString replaceCharactersInRange:withString:]: Range or index out of bounds
2020-12-10 11:42:50.131452+0800 letalk[64246:2049380] [General] (
	0   CoreFoundation                      0x00007fff39d4b2fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff64440a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff39d4b12f +[NSException raise:format:] + 201
	3   CoreFoundation                      0x00007fff39d8912a mutateError + 261
	4   FlutterMacOS                        0x0000000100355a81 -[FlutterTextInputPlugin setMarkedText:selectedRange:replacementRange:] + 193
	5   AppKit                              0x00007fff37c79bfb -[NSTextInputContext(NSInputContext_WithCompletion) setMarkedText:selectedRange:replacementRange:completionHandler:] + 193
	6   AppKit                              0x00007fff37c74310 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.360 + 119
	7   AppKit                              0x00007fff375b2e1d -[NSTextInputContext tryHandleTSMEvent_setMarkedText_withContext:dispatchCondition:setupForDispatch:dispatchWork:continuation:] + 99
	8   AppKit                              0x00007fff37c739e2 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.321 + 270
	9   AppKit                              0x00007fff37c73817 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2.315 + 217
	10  AppKit                              0x00007fff37c7306f __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.265 + 2976
	11  AppKit                              0x00007fff375ad512 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 + 74
	12  AppKit                              0x00007fff375ad49a -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 87
	13  AppKit                              0x00007fff375acc92 -[NSTextInputContext handleTSMEvent:completionHandler:] + 1749
	14  AppKit                              0x00007fff375ac545 _NSTSMEventHandler + 306
	15  HIToolbox                           0x00007fff38ef122e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
	16  HIToolbox                           0x00007fff38ef05df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
	17  HIToolbox                           0x00007fff38ef0465 SendEventToEventTargetWithOptions + 45
	18  HIToolbox                           0x00007fff38f57f8f SendTSMEvent_WithCompletionHandler + 383
	19  HIToolbox                           0x00007fff390f8f61 __SendTextInputEvent_WithCompletionHandler_block_invoke + 489
	20  HIToolbox                           0x00007fff390f7749 SendTextInputEvent_WithCompletionHandler + 1126
	21  HIToolbox                           0x00007fff3915b264 -[IMKInputSession _postEvent:completionHandler:] + 170
	22  HIToolbox                           0x00007fff3916ded9 __83-[IMKInputSession setMarkedText:selectionRange:replacementRange:completionHandler:]_block_invoke + 98
	23  HIToolbox                           0x00007fff3916ed08 __55-[IMKInputSession selectedRange_withCompletionHandler:]_block_invoke + 502
	24  HIToolbox                           0x00007fff38f5adb9 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
	25  AppKit                              0x00007fff37c7626a __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.508 + 97
	26  AppKit                              0x00007fff375acbbb -[NSTextInputContext handleTSMEvent:completionHandler:] + 1534
	27  AppKit                              0x00007fff375ac545 _NSTSMEventHandler + 306
	28  HIToolbox                           0x00007fff38ef122e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
	29  HIToolbox                           0x00007fff38ef05df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
	30  HIToolbox                           0x00007fff38ef0465 SendEventToEventTargetWithOptions + 45
	31  HIToolbox                           0x00007fff38f57f8f SendTSMEvent_WithCompletionHandler + 383
	32  HIToolbox                           0x00007fff390f8f61 __SendTextInputEvent_WithCompletionHandler_block_invoke + 489
	33  HIToolbox                           0x00007fff390f7749 SendTextInputEvent_WithCompletionHandler + 1126
	34  HIToolbox                           0x00007fff3915b264 -[IMKInputSession _postEvent:completionHandler:] + 170
	35  HIToolbox                           0x00007fff3916e861 -[IMKInputSession selectedRange_withCompletionHandler:] + 288
	36  HIToolbox                           0x00007fff39158c54 __72-[IMKInputSession _updateIMKMarkedRange:markedLength:completionHandler:]_block_invoke.823 + 74
	37  HIToolbox                           0x00007fff39158aee -[IMKInputSession tryUpdateIMKMarkedRange_withDispatchCondition:dispatchWork:continuation:] + 86
	38  HIToolbox                           0x00007fff39158bde -[IMKInputSession _updateIMKMarkedRange:markedLength:completionHandler:] + 174
	39  HIToolbox                           0x00007fff3916de68 -[IMKInputSession setMarkedText:selectionRange:replacementRange:completionHandler:] + 545
	40  HIToolbox                           0x00007fff3916e420 -[IMKInputSession setMarkedText:selectionRange:replacementRange:validFlags:completionHandler:] + 127
	41  HIToolbox                           0x00007fff3915e9cd __89-[IMKInputSession imkxpc_setMarkedText:selectionRange:replacementRange:validFlags:reply:]_block_invoke + 595
	42  CoreFoundation                      0x00007fff39cd1764 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	43  CoreFoundation                      0x00007fff39c94e87 __CFRunLoopDoBlocks + 394
	44  CoreFoundation                      0x00007fff39c94be4 __CFRunLoopRun + 2772
	45  CoreFoundation                      0x00007fff39c93ebe CFRunLoopRunSpecific + 455
	46  HIToolbox                           0x00007fff38f3e867 -[IMKInputSessionXPCInvocation invocationAwaitXPCReply] + 551
	47  HIToolbox                           0x00007fff3914d811 __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke_2.441 + 1575
	48  HIToolbox                           0x00007fff3914cd0b __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke_2.411 + 449
	49  HIToolbox                           0x00007fff3913b0f2 -[IMKClient switchedInputMode:completionHandler:] + 400
	50  HIToolbox                           0x00007fff3914bce6 -[IMKInputSession tryHandleEventSwitchedInputMode:eventWasHandled:continuationHandler:] + 116
	51  HIToolbox                           0x00007fff3914cb08 __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke.410 + 205
	52  HIToolbox                           0x00007fff3914c944 __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke + 271
	53  HIToolbox                           0x00007fff39157d5b -[IMKInputSession _eventIsOn:completionHandler:] + 2085
	54  HIToolbox                           0x00007fff3914c1c8 -[IMKInputSession handleEvent:completionHandler:] + 823
	55  HIToolbox                           0x00007fff39107b8c IMKInputSessionProcessEventRefWithCompletionHandler + 114
	56  HIToolbox                           0x00007fff391072fe InputMethodInstanceProcessEventRef_WithCompletionHandler + 122
	57  HIToolbox                           0x00007fff390f6c32 __TSMEventToInputMethod_WithCompletionHandler_block_invoke + 117
	58  HIToolbox                           0x00007fff390fa165 __SendTSMDocumentLockEvent_WithCompletionHandler_block_invoke + 95
	59  HIToolbox                           0x00007fff38f5adb9 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
	60  AppKit                              0x00007fff375ac9ac -[NSTextInputContext handleTSMEvent:completionHandler:] + 1007
	61  AppKit                              0x00007fff375ac545 _NSTSMEventHandler + 306
	62  HIToolbox                           0x00007fff38ef122e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
	63  HIToolbox                           0x00007fff38ef05df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
	64  HIToolbox                           0x00007fff38ef0465 SendEventToEventTargetWithOptions + 45
	65  HIToolbox                           0x00007fff38f57f8f SendTSMEvent_WithCompletionHandler + 383
	66  HIToolbox                           0x00007fff390f6b76 TrySendLockEvent_BeforeEventToInputMethod_WithContinuationHandler + 315
	67  HIToolbox                           0x00007fff390f6a01 TSMEventToInputMethod_WithCompletionHandler + 147
	68  HIToolbox                           0x00007fff390f694e TSMEventToKeyboardInputMethod_WithCompletionHandler + 120
	69  HIToolbox                           0x00007fff38f574a1 TSMKeyEvent_WithCompletionHandler + 556
	70  HIToolbox                           0x00007fff38f5725a __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 + 250
	71  HIToolbox                           0x00007fff38f57089 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 + 257
	72  HIToolbox                           0x00007fff38f56dce __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 + 282
	73  HIToolbox                           0x00007fff38f56b32 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke + 274
	74  HIToolbox                           0x00007fff38f56127 TSMProcessRawKeyEventWithOptionsAndCompletionHandler + 3398
	75  AppKit                              0x00007fff37c77cd9 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3.779 + 110
	76  AppKit                              0x00007fff37c772d6 __204-[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:]_block_invoke.734 + 115
	77  AppKit                              0x00007fff37c771c7 -[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:] + 245
	78  AppKit                              0x00007fff37c77892 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 1286
	79  AppKit                              0x00007fff37c77086 -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 107
	80  FlutterMacOS                        0x0000000100354db3 -[FlutterTextInputPlugin keyDown:] + 67
	81  FlutterMacOS                        0x0000000100359602 -[FlutterViewController keyDown:] + 306
	82  AppKit                              0x00007fff374bc033 forwardMethod + 211
	83  AppKit                              0x00007fff373f8367 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6840
	84  AppKit                              0x00007fff373f6667 -[NSWindow(NSEventRouting) sendEvent:] + 478
	85  AppKit                              0x00007fff372968a9 -[NSApplication(NSEvent) sendEvent:] + 2953
	86  AppKit                              0x00007fff372845e0 -[NSApplication run] + 755
	87  AppKit                              0x00007fff37273ae8 NSApplicationMain + 777
	88  letalk                              0x000000010000596d main + 13
	89  libdyld.dylib                       0x00007fff65c0e3d5 start + 1
)

![WechatIMG869](https://user-images.githubusercontent.com/18003878/101727437-70dc1b80-3aef-11eb-8bd5-55aba29d1c14.jpeg)

**Comment by pedromassangocode** [comment]
Hi @Sunshine218 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
