### ISSUE TITLE
Flutter initialization failed Could not find working copy of Flutter

### ISSUE THREAD

**Issue by mehranshoqi** [flutter/flutter#72056]
hello,

i try to install flutter SDK on ubuntu 20.04 with sudo snap install flutter --classic  Command.
when instalation finished and i type flutter on Terminal, it say's:

```bash
Initializing Flutter
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
.releases[] | select(.hash==).archive                            
jq: 1 compile error
Downloading /
curl: (3) <url> malformed
tar: latest_stable.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Flutter initialization failed
Could not find working copy of Flutter
```

**Comment by TahaTesser** [comment]
Hi @mehranshoqi 
For Flutter on Snap related installation issues, please create a new issue n their dedicated [repository ](https://github.com/kenvandine/flutter-snap/issues).
Meanwhile, you can install it via git clone https://flutter.dev/docs/get-started/install/linux
