### ISSUE TITLE
module 'path_provider' not found @import path_provider

### ISSUE THREAD

**Issue by pierre-gancel** [flutter/flutter#72069]
```bash
Undefined symbols for architecture arm64:
                          "_OBJC_CLASS_$_FLTPathProviderPlugin", referenced from:
                              objc-class-ref in GeneratedPluginRegistrant.o
                        ld: symbol(s) not found for architecture arm64
```

**Comment by pierre-gancel** [comment]
linked with https://github.com/flutter/flutter/issues/72057

**Comment by pierre-gancel** [comment]
flutter new projet ios builds all smooth,
add **path_provider: ^1.6.24** (or previous version) in the yaml and it breaks down

<img width="987" alt="Screenshot 2020-12-10 at 15 56 37" src="https://user-images.githubusercontent.com/69810198/101788647-9faebd80-3b00-11eb-94bd-24e6956fca48.png">


here is what the doctor says : 

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/pierre/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pierre/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

 
[✓] Connected device (1 available)            
    • iPhone 12 Pro Max (mobile) • D01C55C0-7258-4B4A-A584-19C33F644B7C • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.

**Comment by pierre-gancel** [comment]
alternatively I also get

    /ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'path_provider'
    not found
    @import path_provider;
     ~~~~~~~^~~~~~~~~~~~~

- pod are installed 
- xcode team is configured
- project is opened at the xcworkspace level
- apples are laid all over the desk
- custom prayers and rituals have been whispered

**Comment by TahaTesser** [comment]
Hi @pierre-gancel 
Jut tried to reproduce the issue using `path_provider` in a new project on the latest `stable` app run with no issues
 ```bash
tahatesser@Tahas-MacBook-Pro ~ % pod --version
1.10.0
```

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.24
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (13 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS
      14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

Can you please execute `pod install` and `pod update` from the root of your ios folder and try again
Thank you

**Comment by pierre-gancel** [comment]
Hello @TahaTesser,
Thank you so much for your quick reply and kind help,

I upgraded to 1.22.5 and did run required commands.
I still get module **'path_provider' not found @import path_provider;**
I renamed the issue accordingly.

Below is the code from **GeneratedPluginRegistrant.m** where the error is detected 
Hope this could help,

> GeneratedPluginRegistrant.m
```
//
//  Generated file. Do not edit.
//

#import "GeneratedPluginRegistrant.h"

#if __has_include(<path_provider/FLTPathProviderPlugin.h>)
#import <path_provider/FLTPathProviderPlugin.h>
#else
**@import path_provider;**
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
}

@end

```

> Xcode's output:
> ↳
>     /Users/pierre/Desktop/test_4/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module
>     'path_provider' not found
>     @import path_provider;
>      ~~~~~~~^~~~~~~~~~~~~
>     1 error generated.
>     note: Using new build system
>     note: Building targets in parallel
>     note: Planning build
>     note: Constructing build description

**Comment by pierre-gancel** [comment]
I removed the folder **.pub-cache** 
from my machine's Flutter folder,
all back to normal
