### ISSUE TITLE
[integration_test] ensureInitialized() inside setUpAll() fails, and tests hangs

### ISSUE THREAD

**Issue by vrnvorona** [flutter/flutter#72063]
## Steps to Reproduce

1. Get any sample app
2. According to [integration_test guide](https://flutter.dev/docs/testing/integration-tests#migrating-from-flutter_driver) create `integration_test/app_test.dart` and `test_driver/integration_test.dart` files with following contents:
```dart
// app_test.dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import '../lib/main.dart' as app;

void main() {
  group('end-to-end test', () {
    setUpAll(() async {
      IntegrationTestWidgetsFlutterBinding.ensureInitialized();
    });
    testWidgets("failing test example", (WidgetTester tester) async {
      app.main();
      await tester.pumpAndSettle();
      expect(2 + 2, equals(5));
    });
  });
}
```
```dart
// integration_test.dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```
3. Launch tests with `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart` command

**Expected results:** Failed tests

**Actual results:** App hangs because there is Exception inside `ensureInitialized()`: `'WidgetsBinding.instance is IntegrationTestWidgetsFlutterBinding': is not true`, it's actually `LiveTestWidgetsFlutterBinding`. Logs are in Logs section.

If i move `ensureInitialized()` out of `setUpAll()` or even outside of test group, everything is working as expected.

You can reproduce those steps in this [samples fork branch](https://github.com/vrnvorona/samples/tree/integration_test_test) in `experimental/form_app` sample app.

<details>
  <summary>Logs</summary>

Can't really run tests as `run` so here is `flutter drive` command
```
➜  form_app git:(integration_test_test) ✗ flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart           
Using device iPhone 8 Plus.
Starting application: integration_test/app_test.dart
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.8s
Xcode build done.                                           18.1s
flutter: Observatory listening on http://127.0.0.1:59246/0vXGpRjutM0=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:59246/0vXGpRjutM0=/
VMServiceFlutterDriver: Isolate found with number: 2407297073875927
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: end-to-end test (setUpAll)
flutter: 00:00 +0: end-to-end test (setUpAll) [E]
flutter:   'package:integration_test/integration_test.dart': Failed assertion: line 131 pos 12: 'WidgetsBinding.instance is IntegrationTestWidgetsFlutterBinding': is not true.
flutter:   dart:core-patch/errors_patch.dart 46:39                                           _AssertionError._doThrowNew
  dart:core-patch/errors_patch.dart 36:5                                            _AssertionError._throwNew
  package:integration_test/integration_test.dart 131:12                             IntegrationTestWidgetsFlutterBinding.ensureInitialized
  Users/voronin/samples/experimental/form_app/integration_test/app_test.dart 11:44  main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 310:70                                 Declarer._setUpAll.<fn>.<fn>.<fn>
  dart:async/future.dart 512:26                                                     Future.forEach.<fn>
  dart:async/future.dart 554:26                                                     Future.doWhile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26                      StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15            <…>
flutter: 00:00 +0 -1: end-to-end test (tearDownAll)
flutter: 00:00 +1 -1: Some tests failed.
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
```

```
Analyzing form_app...                                                   
No issues found! (ran in 2.8s)
```

```
[✓] Flutter (Channel unknown, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-RU)
    • Flutter version 1.22.2 at /usr/local/flutter
    • Framework revision 84f3d28555 (8 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/voronin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/voronin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode-12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.43

[!] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 8 Plus (mobile) • AD6DDB6C-44AB-4655-81C4-AAC5C241F4A2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 2 categories.

```
I don't use VSC or Android Studio so I guess it's ok.
</details>

**Comment by darshankawar** [comment]
@vrnvorona 
Your `flutter doctor` shows `Channel unknown, 1.22.2`, but I am presuming you are on stable.
Recently the `integration_test` template was added in master branch, so we don't need to explicitly create the `integration_test` and underlying folders and files. 
Can you try to switch to latest master and try your code sample with built-in `integration_test` folder and see if you get similar behavior ?

<img width="261" alt="Screenshot 2020-12-10 at 7 13 00 PM" src="https://user-images.githubusercontent.com/67046386/101779819-bf9faa80-3b1b-11eb-80dc-f09fd0919887.png">

**Comment by vrnvorona** [comment]
@darshankawar I didn't get the built-in folder thing, so I tried upgrading flutter and running it again, but had issue with building app after due to [this problem](https://stackoverflow.com/questions/65197799/flutter-pod-install-problem-undefined-method-each-child-for-dir0x00007fa6). I am glad to try, but lack competence to do so :(

**Comment by darshankawar** [comment]
@vrnvorona 
I tried the official `integration_test` plugin [example](https://github.com/flutter/plugins/tree/master/packages/integration_test/example) on latest stable and I was able to run the tests properly without any issues.

```
dhs@Dhss-MacBook-Pro example % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart
Using device sdk gphone x86 arm.
Starting application: integration_test/example_test.dart
"build/app/outputs/flutter-apk/app.apk" does not exist.
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        96.7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.2s
I/flutter (20162): Observatory listening on http://127.0.0.1:45433/xgBGAlGx4Ss=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50679/xgBGAlGx4Ss=/
VMServiceFlutterDriver: Isolate found with number: 1151613769436767
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (20162): 00:00 +0: verify text
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (20162): 00:07 +1: (tearDownAll)
I/flutter (20162): 00:10 +2: All tests passed!
All tests passed.
Stopping application instance.
dhs@Dhss-MacBook-Pro example %
```


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!


```

</details>

Can you cross-check your setup with the official plugin example and see if you are missing anything ?
Thanks.

**Comment by vrnvorona** [comment]
@darshankawar 
Ran it from plugins master, both on iOS sim and Android emu, same thing.

[here](https://github.com/vrnvorona/plugins/tree/integration_test_test) is my forked branch with failing test. I ran it `flutter drive --driver=test_driver/integration_test.dart --target=test_driver/test_fail.dart` like this.

<details>
<summary>log for android</summary>
I/flutter ( 8401): Observatory listening on http://127.0.0.1:35973/i5guleqVXqg=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:50873/i5guleqVXqg=/
VMServiceFlutterDriver: Isolate found with number: 4421906460903287
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter ( 8401): 00:00 +0: end-to-end test (setUpAll)
I/flutter ( 8401): 00:00 +0: end-to-end test (setUpAll) [E]
I/flutter ( 8401):   'package:integration_test/integration_test.dart': Failed assertion: line 130 pos 12: 'WidgetsBinding.instance is IntegrationTestWidgetsFlutterBinding': is not true.
I/flutter ( 8401):   dart:core-patch/errors_patch.dart 46:39                                                   _AssertionError._doThrowNew
I/flutter ( 8401):   dart:core-patch/errors_patch.dart 36:5                                                    _AssertionError._throwNew
I/flutter ( 8401):   package:integration_test/integration_test.dart 130:12                                     IntegrationTestWidgetsFlutterBinding.ensureInitialized
I/flutter ( 8401):   Users/voronin/plugins/packages/integration_test/example/test_driver/test_fail.dart 13:44  main.<fn>.<fn>
I/flutter ( 8401):   package:test_api/src/backend/declarer.dart 310:70                                         Declarer._setUpAll.<fn>.<fn>.<fn>
I/flutter ( 8401):   dart:async/future.dart 512:26                                                             Future.forEach.<fn>
I/flutter ( 8401):   dart:async/future.dart 554:26                                                             Future.doWhile.<fn>
I/flutter ( 8401):   package:stack_trace/src/stack_zone_specification.dart 126:26                              StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
I/flutter ( 8401):   package:stack_trace/src/stack_z
I/flutter ( 8401): 00:00 +0 -1: end-to-end test (tearDownAll)
I/flutter ( 8401): 00:00 +1 -1: Some tests failed.
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
</details>

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-RU)
    • Flutter version 1.22.5 at /usr/local/flutter
    • Framework revision 7891006299 (11 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/voronin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/voronin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode-12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.43

[!] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

</details>

**Comment by darshankawar** [comment]
I am getting same error as above if I follow https://github.com/flutter/flutter/issues/72063#issue-761180615 , but not when I follow the official `integration_test` plugin example as https://github.com/flutter/flutter/issues/72063#issuecomment-742992090, which seem to indicate something is amiss.

Keeping this issue open for further analysis.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!

```

</details>

**Comment by jonmountjoy** [comment]
I have the same problem, but have narrowed the problem down.  At the very least, the error message is completely wrong (suggesting calling `enableFlutterDriverExtension()` which explicitly contradicts the docs). 

Mine fails with [✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)

I can make the official test fail too.  If you go to [_extended_test_io.dart](https://github.com/flutter/plugins/blob/master/packages/integration_test/example/integration_test/_extended_test_io.dart) and move the `IntegrationTestWidgetsFlutterBinding.ensureInitialized()` into a `setUpAll()`, then everything stops working.

ie. 
```
// IntegrationTestWidgetsFlutterBinding.ensureInitialized();
group('Porridge', () {
   setUpAll(() async {
      IntegrationTestWidgetsFlutterBinding.ensureInitialized();
    });
....
});
...
```

**Comment by workerbee22** [comment]
I moved it out of setupAll and it now works:

```
void main() {
  // required for integration_test, also see /test_driver/integration_test.dart
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('Startup Test', () {
    // Smoke Test
    testWidgets('Smoke Test', (WidgetTester tester) async {
      // build the app and trigger a frame
      MyApp.main();

      // trigger a frame
      await tester.pumpAndSettle();
      // verify the Onboarding first page is shown
      expect(
        find.byWidgetPredicate(
          (Widget widget) => widget is Text && widget.data.startsWith('Flutter'),
        ),
        findsOneWidget,
      );
    });
  });
}
```

**Comment by SoftWyer** [comment]
Slightly off-topic, but am I correct in thinking that all integration tests live in the one `testWidgets` function as this is where the app is started?

I've tried having multiple `testWidgets` running the same tests and the subsequent ones always fail even if the first passes. The docs could do with showing how to structure more complex testing scenarios.

**Comment by danielpirs** [comment]
> Slightly off-topic, but am I correct in thinking that all integration tests live in the one `testWidgets` function as this is where the app is started?
> 
> I've tried having multiple `testWidgets` running the same tests and the subsequent ones always fail even if the first passes. The docs could do with showing how to structure more complex testing scenarios.

You have to start the app in each 'testWidgets' separately. Then it will work.
But I agree whole integration_test is 1.0.0 version (or actually 1.0.1) and is still missing some maturity and especially documentation how it works and examples how to use. But it is much better approach then the old fultter driver.

**Comment by abrose1** [comment]
> I moved it out of setupAll and it now works:
> 
> ```
> void main() {
>   // required for integration_test, also see /test_driver/integration_test.dart
>   IntegrationTestWidgetsFlutterBinding.ensureInitialized();
> 
>   group('Startup Test', () {
>     // Smoke Test
>     testWidgets('Smoke Test', (WidgetTester tester) async {
>       // build the app and trigger a frame
>       MyApp.main();
> 
>       // trigger a frame
>       await tester.pumpAndSettle();
>       // verify the Onboarding first page is shown
>       expect(
>         find.byWidgetPredicate(
>           (Widget widget) => widget is Text && widget.data.startsWith('Flutter'),
>         ),
>         findsOneWidget,
>       );
>     });
>   });
> }
> ```

Hi, I'm having the same issue, but moving my ensureInitialized statement outside of the setupAll doesn't seem to have fixed it. I'm pretty new to all of this; could someone please let me know what I am missing? I'm not using the example test, but it should be pretty similar. I would appreciate any help resolving this.

```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:flutter/material.dart';
import 'package:creditcardcurator/main.dart' as app; //this is the package for my app

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group("Initial tests", () {

    testWidgets('check button click', (WidgetTester tester) async {
      app.main();
      await tester.pumpAndSettle();

      var button = find.text('Tell me more?');
      tester.tap(button);
      await tester.pumpAndSettle();
      expect(find.text('Got it!'), findsOneWidget);
    });
  });
}
```

**Comment by omartinma** [comment]
Same here, moving out the   IntegrationTestWidgetsFlutterBinding.ensureInitialized(); works perfect!

**Comment by cyanglaz** [comment]
cc @dnfield

**Comment by dnfield** [comment]
Added a comment on the linked PR. @jiahaog this seems related to the test reporter stuff you've been working on.

**Comment by jiahaog** [comment]
Yeah the documentation is not correct, `IntegrationTestWidgetsFlutterBinding.ensureInitialized()` should be called as soon as possible after `main`. I have commented on the linked PR as well.

> I've tried having multiple testWidgets running the same tests and the subsequent ones always fail even if the first passes.

@SoftWyer can you share a minimal example of this happening?

**Comment by SoftWyer** [comment]
@jiahaog if you run an integration test against the flutter demo app, with the following test code:

```

void main() async {
  testWidgets('Test 1', (tester) async {
    app.main();
    await tester.pumpAndSettle();
    expect(find.byType(FloatingActionButton), findsOneWidget);
  });

  testWidgets('Test 2', (tester) async {
    // This test fails if the app.main is commented out.
    // app.main();
    await tester.pumpAndSettle();
    expect(find.byType(FloatingActionButton), findsOneWidget);
  });
}
```

The you get this error:

```
Failure in method: Test 2
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type
"FloatingActionButton" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Users/wyerk/Documents/bsl/FlutterDemo/integration_test/demo_tests.dart:17:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Users/wyerk/Documents/bsl/FlutterDemo/integration_test/demo_tests.dart line 17
The test description was:
  Test 2
═════════════════════════════════════════════════════════════════

end of failure 1
```

**Comment by jiahaog** [comment]
Yes, that is expected. `testWidgets` resets the widget tree to a clean slate, so you will have to call `app.main()` (which calls `runApp` under the hood), or perhaps call `tester.pumpWidget` to pump the widgets for each test.

https://github.com/flutter/flutter/blob/2a188eeca3653254d6796a7e3e059d40acaca0b7/packages/flutter_test/lib/src/binding.dart#L779

**Comment by SoftWyer** [comment]
Thanks, that is what we surmised.

Our core app is large though, with a long startup cost. So unlike the 'old' integration way of having many tests, we now have one `testWidget` in which all the integration steps are run. We do lose out on some of the nice stats reporting (e.g. x tests run) but we can always roll our own.

**Comment by omartinma** [comment]
Related to the case of @SoftWyer is there any way to do like a common setup for every test? So far what I did to not repeat code is just create some private methods, but dont kwow if it is a clean solution.

**Comment by joanofdart** [comment]
I'm a bit confused myself with all this. Recently started to play with tests.

**Comment by jiahaog** [comment]
> is there any way to do like a common setup for every test?

You could factor out the common setup code and place them in a `setUp` or `setUpAll` in the test files, just like a widget test.

**Comment by spajker** [comment]
I have also issue with test hanging. It is non determitic, in most times this test suit pass but once a time it hangs on "Flutter Driver extension is taking a long time to become available" and waits forever. Then when I restart job, same suite pass correctly.

btw I am not having enableFlutterDriverExtension() anywhere in apo.main() as in documentation example, I tried add but it not helps

## Code

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test group', () {
    testWidgets("test",
        (WidgetTester tester) async {
      app.main();
      await tester.pumpAndSettle(Duration(seconds: 5));
     (...)
      await tester.pumpAndSettle(Duration(seconds: 5));
      //
      expect((...));
    });
  });
}

 

## Logs

<details>
<summary>Logs</summary>
I/flutter ( 7781): 00:47 +1: (tearDownAll)
I/flutter ( 7781): 00:47 +2: All tests passed!
All tests passed.
Stopping application instance.
+ let INDEX=0+1
+ for TEST_FILE in integration_test/*"_test".dart
+ [[ 1 -eq 0 ]]
+ flutter drive --driver=test_driver/integration_test.dart --target=integration_test/loading3_test.dart --flavor=mock --no-build
Using device sdk gphone x86.
Starting application: integration_test/loading3_test.dart
I/flutter ( 8140): Observatory listening on http://127.0.0.1:37599/UPJjPotYcaU=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:55002/UPJjPotYcaU=/
VMServiceFlutterDriver: Isolate found with number: 6954286070879
VMServiceFlutterDriver: Unknown pause event type VMNoneEvent. Assuming application is ready.
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
</details>

**Comment by rfitz123** [comment]
Moving `IntegrationTestWidgetsFlutterBinding.ensureInitialized();` did not change the behavior for me. I've reduced my test down to the code below and am getting the error: 
```
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
```

```
import 'package:agape_native_app/alpha-main.dart' as app;
import 'package:dartbase_admin/auth/user_record.dart';
import 'package:dartbase_admin/dartbase_admin.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Individual Account Creation Flow', (WidgetTester tester) async {
    app.main();
    await tester.pumpAndSettle();

    expect(2 + 2, 5);
  });
}
```

I am running with a flavor like below, could that have something to do with it?
```
flutter drive \                                                                                
  --driver=test_driver/integration_test.dart \
  --target=integration_test/accountCreation_test.dart \
  --flavor=testing
```

**Comment by snowb1shop** [comment]
Hello, 

I'm experiencing the same problem when trying to build integration tests on iOS.
Test app hangs with the error: 

`VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().`


I have the latest stable Flutter version:  2.2.3, tested on both real device and simulator with iOS 14.6.
Automatic tests implemented based on the documentation: https://flutter.dev/docs/testing/integration-tests


On Android I also have experienced hanging tests, but what helped me was the workaround from @samuelstroschein written here: https://github.com/flutter/flutter/issues/73355

This workaround doesn't work unfortunately for iOS system.
Can anyone confirm that this issue is still happening and that we should reopen #72063? 



flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1
```
