### ISSUE TITLE
showing exception

### ISSUE THREAD

**Issue by manas-96** [flutter/flutter#72067]
SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    print(sharedPreferences.getString("id"));
this is not working showing exception-

E/flutter (19705): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

**Comment by darshankawar** [comment]
@manas-96 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample.

**Comment by moroumo** [comment]
If you upgrade Gradle to 4.0.0 recently and got this issue in Android, follow below, details see this [issue/58479](https://github.com/flutter/flutter/issues/58479)

add bellow line to app/proguard-rules.pro

`-keep class androidx.lifecycle.DefaultLifecycleObserver`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
