### ISSUE TITLE
PageView inside PageView, child doesn't respond until parent's scrolling is stopped

### ISSUE THREAD

**Issue by intraector** [flutter/flutter#72071]
I have a `PageView.builder` with `scrollDirection: Axis.vertical`.<br /> Every child of it is `PageView` with `scrollDirection: Axis.horizontal`.<br />
Everything's working just fine, a user can scroll vertically and horizintally using swipes.

**The problem is:** after scrolling vertically a user must wait until the scrolling animation is fully stopped before being able to scroll horizontally.

[Gif][1]

I've tried every possible solution (including custom `GestureDetector` and custom `ScrollPhysics`, still can't deal with it. Any help or hint would've greatly appreciated.

  [1]: https://i.postimg.cc/wxcV8P0T/ezgif-com-resize.gif

**Comment by darshankawar** [comment]
@intraector 
Your question seems to be better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
