### ISSUE TITLE
Linking against the dart-sdk shipped with Flutter

### ISSUE THREAD

**Issue by DominikStarke** [flutter/flutter#72084]
Flutter (Channel master, 1.25.0-5.0.pre.144, on Microsoft Windows [Version 10.0.19041.630], locale de-DE)

I'm currently developing a small Flutter plugin that requires acces to Dart_PostCObject_DL() to send a message from a different thread back to Flutter.
So I added the dart-sdk shipped with flutter to my CMakeLists.txt in my windows plugin folder:

```
get_filename_component(DART_SDK_PATH "cache/dart-sdk/"
                       REALPATH BASE_DIR "$ENV{DART_SDK}")

add_library(${PLUGIN_NAME} SHARED
  "${SRC_ROOT}/ffi.cpp"
  "${DART_SDK_PATH}/include/third_party/dart/dart_api_dl.c"
)

set_source_files_properties("${DART_SDK_PATH}/include/third_party/dart/dart_api_dl.c" PROPERTIES LANGUAGE CXX )
```

$ENV{DART_SDK} points to the bin folder in my flutter installation directory.
And this works, builds and I can post messages between dart isolates and threads back and forth all day long.

The issue is that I have to duplicate the folder "runtime" and rename it to "internal" because dart_api_dl.c looks for dart_api_dl_impl.h in internal.
Should we even use the included SDK or is it better to roll our own copy within the plugin?

**Comment by dcharkes** [comment]
`dart_api_dl.c` and `dart_api_dl_impl.h` are designed to be copyable.

In general when you publish a plugin, it might be linked against a different version of the DartVM. Whether you distribute a compiled shared object or push the copied sources to a repo, in both cases you can encounter another version of the DartVM than that you were developing the plugin for. `dart_api_dl.c` contains versioning internally to check whether the DartVM it is dynamically linked against is compatible with it.

Note that if you're writing the C code yourself and publishing a Flutter app directly, you wont encounter this version skew. In this case you could link against the files in the Dart SDK, but copying them is fine as well. The versioning will warn you if you ever need to update them.

**Comment by DominikStarke** [comment]
Works for me. Thank you.
