### ISSUE TITLE
Every child of a RenderCustomMultiChildLayoutBox must have an ID in its parent data

### ISSUE THREAD

**Issue by haiderajmal** [flutter/flutter#72085]
I'm facing the above error I'm using the class of other files in the scaffold body and the above error shown

**Comment by darshankawar** [comment]
@haiderajmal 
This sounds more of a code implementation issue than Flutter framework issue. Try to search for the similar issue over the internet and see if it helps.
Check out [this](https://stackoverflow.com/questions/63068383/every-child-of-a-rendercustommultichildlayoutbox-must-have-an-id-in-its-parent-d) link also.
If issue persists, provide `flutter doctor -v` and minimal complete reproducible code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
