### ISSUE TITLE
AppBarBehavior.scroll requires you to pad your body element

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7209]
Is this expected?  You have to pad the body so it's not under the appbar, but you also don't know how tall the AppBar is to do this.  Seems like one of the two of those needs to change.

@HansMuller says the gallery gets around this by specifying an AppBar size, but that doesn't work when the AppBar should change its size based on portrait/landscape/etc.

**Comment by abarth** [comment]
FIxed with SliverAppBar.
