### ISSUE TITLE
Create a third_party/freetype2 repository for Flutter

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#72099]
We are currently using Fuchsia's third_party/freetype2 repository but may need to diverge from their build scripts

**Comment by keyonghan** [comment]
I don't seem to have the `Create Project` capability: https://gerrit-review.googlesource.com/Documentation/access-control.html#capability_createProject
/cc @godofredoc

**Comment by godofredoc** [comment]
Updated permissions, can you please give it another try?

**Comment by keyonghan** [comment]
Created: https://flutter.googlesource.com/third_party/freetype2/

**Comment by godofredoc** [comment]
The project is ready, please let us know if you find issues with permissions.

**Comment by jason-simmons** [comment]
Permissions are required to import the repository's history

**Comment by godofredoc** [comment]
@jason-simmons can you please share the source repository and commands?

**Comment by jason-simmons** [comment]
The repository should start from this commit in Fuchsia's FreeType repository:
  https://fuchsia.googlesource.com/third_party/freetype2/+/f91671ab0d50a073631cd69823d8bb32f16216ce

**Comment by godofredoc** [comment]
This is done, please take a look and reopen if something does not work.

https://flutter.googlesource.com/third_party/freetype2/
