### ISSUE TITLE
"Cannot evaluate" error in Chrome

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#72094]
Debugging in Chrome and evaluating an expression shows a "Cannot evaluate" in the Result pane.

I wasn't able to make a smaller reproducible case, so this involved cloning a specific project.

## Steps to Reproduce

1. `git@github.com:johnpryan/malison_flutter.git`
2. open project in IntelliJ
3. Set a breakpoint on line 37 of `lib/src/painter.dart`
4. Create a new Flutter Run / Debug configuration for `example/lib/main.dart`
5. Select Chrome device and press debug
6. When stopped at breakpoint, right click on a local variable and press "Evaluate expression" (e.g. `x`, or `y`)
7. Observe "Cannot Evaluate" is printed

Note that the Variables panel displays the values of local variables correctly.

```
flutter doctor -v
[✓] Flutter (Channel master, 1.25.0-9.0.pre.21, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale en)
    • Flutter version 1.25.0-9.0.pre.21 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 78cbfbff42 (33 minutes ago), 2020-12-10 12:56:02 -0800
    • Engine revision 827aa5d073
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by johnpryan** [comment]
cc: @markzipan

**Comment by Markzipan** [comment]
Thanks for reporting! 

I have [a change out](https://dart-review.googlesource.com/c/sdk/+/175445) that fixes some of the surface errors. After patching those in and rebuilding, I see this compile error:
```
org-dartlang-debug:synthetic_debug_expression:1:1: 
CompilationError: The getter 'x' isn't defined for the class 'TerminalPainter'.
 - 'TerminalPainter' is from 'package:malison_flutter/src/painter.dart' ('../lib/src/painter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'x'.
x
^
```

This may be CFE related. Any thoughts here @johnniwinther @annagrin?

**Comment by johnniwinther** [comment]
The error indicates that the local `x` is not in scope and `x` therefore is interpreted as `this.x`. So is looks that an error in computing the right scope, since `x` is available in line 37 (being declared in line 35).

**Comment by Markzipan** [comment]
I think my error above may be a red herring. Anna will comment with more details shortly.

**Comment by annagrin** [comment]
@johnpryan thanks for finding a bug! 

I am getting  a `ReferenceError: backColor is not defined` from JavaScript, so in my case there is no compilation error from frontend. Looks like we are including variables in dart scope on expression evaluation that should not be there. Will fix!
