### ISSUE TITLE
[WebView_Flutter] evaluateJavascript in onPageStart with iOs works on loadUrl but not on subsequent page transitions

### ISSUE THREAD

**Issue by noeama** [flutter/flutter#72106]
```dart
WebView(
        key: _key,
        javascriptMode: JavascriptMode.unrestricted,
        javascriptChannels: <JavascriptChannel>[
          _testJavascriptChannel(context),
        ].toSet(),
        onPageStarted: (String url) {
          widget.model.controller.evaluateJavascript(jsOverLoad).then((result) {
            print('***** OVERLOAD EVALUATED');
          });
        },
        onPageFinished: (url) {
          print('***** LOADED URL: $url');
        },
        onWebViewCreated: (WebViewController webViewController) {
          widget.model.controller = webViewController;
          Map<String, String> headers = {
            'Authorization': 'Bearer ${_token}'
          };
          webViewController.loadUrl(widget.model.itemUrl, headers: headers);
        });
```

This works great for the initial load and page transitions in Android. But in iOS the JS is not getting injected on page transitions.

**Comment by TahaTesser** [comment]
Hi @noeama 
Can you please provide your `flutter doctor -v`, your `webview_fliutter` version and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
