### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:FAILURE: Build failed with an exception.* What went wrong:Project 'app' not found in root project 'android'.

### ISSUE THREAD

**Issue by shahharoon** [flutter/flutter#72118]

**Comment by pedromassangocode** [comment]
Hi @shahharoon 
Can you provide the logs of the crash?
Thank you

**Comment by shahharoon** [comment]
it has been solved, actually the app could not find the include ":app" in setting.gradle.

i created new project and copy all files and then it works. Thank You
