### ISSUE TITLE
Flutter for web renders non-clamp gradients shifted

### ISSUE THREAD

**Issue by flar** [flutter/flutter#72112]
The following sample code runs fine on Android and with the Skia/CanvasKit backend for Flutter web, but when run on the HTML/DOM backend for Flutter web the mirror and repeated versions of the gradient are shifted.

All 3 gradients should have the colors centered on the reverse diagonal (UR -> LL) as you see with the clamp mode. The mirror and repeated versions will begin/end on that diagonal with the Dom renderer.

Basically, the Upper Right and Lower Left corners should look the same between all 3 gradients.

<details><summary>Sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Gradient TileMode Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Gradient TileMode Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget _makeChild(TileMode tileMode) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Text(tileMode.toString()),
        SizedBox(width: 20),
        Container(
          width: 100,
          height: 100,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(-0.25, -0.25),
              end: Alignment(0.25, 0.25),
              tileMode: tileMode,
              colors: <Color>[Colors.blue, Colors.yellow, Colors.red],
              stops: <double>[0.0, 0.9, 1.0],
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: TileMode.values.map(_makeChild).toList(),
        ),
      ),
    );
  }
}
```
</details>

<details><summary>HTML/DOM output (shifted)</summary>
<img width="282" alt="DOM Screen Shot 2020-12-10 at 5 23 03 PM" src="https://user-images.githubusercontent.com/50503328/101849393-73993980-3b0c-11eb-93dd-49f122b15c1d.png">
</details>
<details><summary>Skia/CanvasKit output (correct)</summary>
<img width="282" alt="CanvasKit Screen Shot 2020-12-10 at 5 22 17 PM" src="https://user-images.githubusercontent.com/50503328/101849388-7300a300-3b0c-11eb-80f1-e7e89ac2bf5a.png">
</details>

**Comment by dnfield** [comment]
@flar do you know? It's been a while for me since I looked at this code.

**Comment by flar** [comment]
Yes, sorry, it looks like both mirror and repeat are offset.

(Also, I fixed the code comment formatting.)

**Comment by flar** [comment]
To be clear, the correct rendering is that the reverse diagonal of the square should be green in all tile modes (including the brand new Decal mode). Just above and to the left of that green reverse diagonal should be a parallel diagonal of blue. Just down and to the right of the green diagonal should be a parallel diagonal of red. What happens outside of that should reflect the tile mode.

All 3 Skia outputs in the description match this correct output. Only the clamp output with the DOM renderer matches. I haven't checked the new decal mode on DOM or Web-Skia.

**Comment by flar** [comment]
I just double checked with the new tile mode and Decal and Clamp are both correct on the DOM back-end. Repeated and Mirror are off.  All modes look correct in the CanvasKit/Skia back-end (and on my Moto G 4).

**Comment by ferhatb** [comment]
Thanks Jim, if fixed the DOM repeat and mirror.

My question was mirror mode for skia seems off (not centered at center of
object).

**Comment by flar** [comment]
@ferhatb does it look off in the pictures I posted above? Can you post a snapshot of what you are seeing that looks wrong?

**Comment by ferhatb** [comment]
@flar TileMode.mirror below looks off center
<img width="282" alt="CanvasKit Screen Shot 2020-12-10 at 5 22 17 PM" src="https://user-images.githubusercontent.com/50503328/101849388-7300a300-3b0c-11eb-80f1-e7e89ac2bf5a.png">

**Comment by flar** [comment]
The mirroring makes it hard to see. It looks off center because the your eye wants to consider that the red lines should be evenly distributed, but that would depend on the tile mode.

The gradient is defined from 0.0 (blue) to 1.0 (red). It is centered around the reverse diagonal so the diagonal is at the 0.5 point on the gradient.

For repeat, every unit distance of gradient sample has the full gradient so you get red just to one side of an integer sample and blue just on the other side. In this case, red and blue are both about 0.5 gradient distances away from the center line.

For mirror mode, though, each adjacent gradient reverses. So, at 0.0 you no longer have blue followed immediately by red, it's blue followed by more blue. You won't see red again until the ramp goes through one more full sweep and gets to -1.0. Thus, the diagonal at 0.5 is half a gradient distance from the red line at 1.0, but 1.5 gradient sweeps away from the next red line at -1.0. Since the eye is drawn to the red lines as a landmark, it sees the "next red line" way over there at the -1.0 sample line and thinks that is too far away. Perceptually you can see this as "off-center", but really it is on center with a gradient that isn't symmetric around 0.5.

If you change the sample points to (0,0) & (0.5, 0.5) then the blue line will be on the diagonal and the red lines will straddle the gradient evenly. It will also "look" more even if you change them to (-0.5, -0.5) to (0, 0) and the red line will be on the diagonal and the blue lines will "look" even.

**Comment by flar** [comment]
Basically, is the diagonal greenish, which is the color the gradient has at 0.5? Then it is centered correctly...
