### ISSUE TITLE
Spelling mistake in overlay package doc

### ISSUE THREAD

**Issue by Roshan13046** [flutter/flutter#72116]
There is a spelling mistake in the documentation of the Overlay package.
The highlighted "aa" should be changed to "a".
Link: https://pub.dev/packages/overlay
![overlayDocSpellEr](https://user-images.githubusercontent.com/55108788/101862263-f915fb80-3b97-11eb-8c51-720e1e2358ca.png)

**Comment by Roshan13046** [comment]
I am working on this issue.

**Comment by iapicca** [comment]
@Roshan13046 
this issue should be addressed to the 3rd party package [overlay](https://pub.dev/packages/overlay) [repo](https://github.com/maddyb99/flutter_overlay/issues)
not to flutter's repo

**Comment by pedromassangocode** [comment]
Closing as invalid Flutter issue, see comment above for where to file this issue.
