### ISSUE TITLE
Input Widget on iOS does not show caret and does not allow editing

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#7211]
Create an Input widget inside another widget. Note that while the text can be changed, it does not display an editing caret and the "move the cursor" widget does not work.

**Comment by eseidelGoogle** [comment]
@mpcomplete would know.

**Comment by mpcomplete** [comment]
Can you give a snippet of sample code that demonstrates this?

**Comment by Hixie** [comment]
Without steps to reproduce it's not clear how to proceed.
