### ISSUE TITLE
tonic::DartInvokeField creates a Dart_NewStringFromCString every time

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#72117]
This method is called every frame for `_beginFrame`, and every time we have to `DispatchPointerDataPacket`. More often than not, the NewCString call ends up being cheap (a few microseconds of wall/cpu time), but in a trace I'm looking at now it occasionally is much more expensive (1+ ms).

We should cache the Dart Strings as a Dart_NewPersistentHandle here, like we do with the private constructor name in `DartState::SetIsolate` and for class library lookups. This should be fairly easy to do and eliminate the unfortunate cases where it takes a bit longer.

/cc @jason-simmons - may know a better way to handle this.

**Comment by jason-simmons** [comment]
`PlatformConfiguration::DidCreateIsolate` could call `Dart_GetField` for all of the hook methods and cache them as persistent handles.  The hooks can then be called using `Dart_InvokeClosure` or Tonic's `DartInvoke`.

**Comment by dnfield** [comment]
Another thing to explore might be using dart:ffi
