### ISSUE TITLE
Search at docs.flutter.io is broken due to jquery redirect?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7212]
This is a bad regression for our users.

```
https://code.jquery.com/jquery-2.1.4.min.js Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
typeahead.bundle.min.js:7 Uncaught ReferenceError: jQuery is not defined
    at typeahead.bundle.min.js:7
    at typeahead.bundle.min.js:7
script.js:153 Uncaught ReferenceError: $ is not defined
    at initTypeahead (script.js:153)
    at XMLHttpRequest.<anonymous> (script.js:198)
```

**Comment by eseidelGoogle** [comment]
Looks like our jquery is very old? Could that be contributing to the problem?

**Comment by eseidelGoogle** [comment]
I'm not sure if this is dartdoc related or what.  @sethladd might know.

**Comment by devoncarew** [comment]
Perhaps intermittent? I was able to do a search for MaterialApp.

**Comment by devoncarew** [comment]
But it looks like the latest on the 2.0 branch is `https://code.jquery.com/jquery-2.2.4.min.js`.

**Comment by eseidelGoogle** [comment]
Odd.  May be a google-specific issue.  Works fine in incognito, but not in a normal tab (which has google-specific proxy settings).

**Comment by sethladd** [comment]
Just tested at work. Search is working for me. Does this still happen for you?

**Comment by eseidelGoogle** [comment]
Nope.
