### ISSUE TITLE
help me ,Thanks

### ISSUE THREAD

**Issue by Tmysk** [flutter/flutter#72128]
PS C:\Windows\system32> flutter doctor
Building flutter tool...
Running pub upgrade...
Sorry, but pub is not supported on Windows XP.
Error (64): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

help me ,Thanks

**Comment by TahaTesser** [comment]
Hi @Tmysk 
Unfortunately, Flutter and Pub  aren't supported on Windows XP
Please checkout [Windows install System requirements](https://flutter.dev/docs/get-started/install/windows#system-requirements)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
