### ISSUE TITLE
In app purchase issue android : several user purchase aren't detected

### ISSUE THREAD

**Issue by nitneuq33000** [flutter/flutter#72127]
Hello, I have a trouble with in app purchase.

On iOS I have no problem 100% of user have the purchase well detected after purchase.
But on Android ( same code ) I have 50% and perhaps more of user who have a purchase completed but, plugin not finish the processus to distribute the product. User received well the google bill by email but not my product.

I use exactly the structure of in app purchase example

**Comment by TahaTesser** [comment]
Hi @nitneuq33000 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by nitneuq33** [comment]
I never successed to reproduce, all purchase test in debug works, but after launch in production, the finalisation/detection is random

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
