### ISSUE TITLE
Missing selection area of the text after copy text in Flutter on IOS

### ISSUE THREAD

**Issue by AlexFox63** [flutter/flutter#72124]
## Steps to Reproduce
1. Select text or Select all text (only on IOS)
2. Copy text
3. The selection of text is missing but on the native IOS apps selection is remain.

CupertinoTextField also not working as IOS component.

Video with the problem https://drive.google.com/file/d/1JWJ_xsYNQPgBpbEynoPTPW5YekrUGQha/view?usp=sharing

**Comment by pedromassangocode** [comment]
Hi @AlexFox63 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by AlexFox63** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

 ```
CupertinoTextField(
  textCapitalization: TextCapitalization.sentences,
  controller: widget.contentController,
  focusNode: widget.descriptionFocusNode,
  placeholder: getStringById(context, StringId.WRITE_SOMETHING),
  minLines: 5,
  maxLines: 20,
  padding: const EdgeInsets.symmetric(horizontal: 35),
),
```

**Comment by pedromassangocode** [comment]
Hi @AlexFox63 
Can you please make it clear what the issue here?
As you can see the text copied is completely pasted in the default messages app.

![gif](https://user-images.githubusercontent.com/67424416/101892960-53b55480-3ba4-11eb-9602-4d1a6cd6af23.gif)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (15 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro (mobile)      • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by AlexFox63** [comment]
I attach the video https://drive.google.com/file/d/1JWJ_xsYNQPgBpbEynoPTPW5YekrUGQha/view?usp=sharing. 
When you copy text on IOS text should be stay selected after pressing the copy button.

**Comment by pedromassangocode** [comment]
Hi @AlexFox63 
Thanks for making this clear, I was able to reproduce the issue (see my video in https://github.com/flutter/flutter/issues/72124#issuecomment-743115074).

**Comment by AlexFox63** [comment]
Hey, yes, the first part of ur video is about my problem. Thanks for the quick response.

**Comment by pedromassangocode** [comment]
Somehow related to https://github.com/flutter/flutter/issues/62193.

**Comment by justinmc** [comment]
Thanks for this issue @AlexFox63!  I can't believe I didn't notice something so obvious.  It should be fixed and tested in master now.
