### ISSUE TITLE
ScaffoldMessenger throws a hero animation error and the screen becomes all black

### ISSUE THREAD

**Issue by biklas7** [flutter/flutter#72139]
## Steps to Reproduce

1. Show snackBar with `ScaffoldMessenger.of(context).showSnackBar(...)`
2. Immediately after pop the current page with `Navigator.of(context).pop()`
3. Enter the original page again without waiting for the snackBar to disappear
4. The error is thrown in the background and the original page will show all black

**Expected results:**
The snackBar should do a hero animation and show it on the previous scaffold and the user should be able to navigate to the route that originated the snackBar with no issues. Also, there should be no error thrown since the animation worked perfectly.

**Actual results:**
Visually everything works as expected, the snackBar shows on both pages with a smooth transition. The error is thrown in the background but seems to have no impact on the UI **unless** the user tries to navigate to the page from where the snackBar was shown originally, which will become all black.
This does not happen if the user waits for the snackBar to disappear before reentering the original page.

<details>
  <summary>Logs</summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <SnackBar Hero tag - Row(direction: horizontal, mainAxisAlignment: center, mainAxisSize: min, crossAxisAlignment: center)>

Here is the subtree for one of the offending heroes: Hero
  tag: <SnackBar Hero tag - Row(direction: horizontal, mainAxisAlignment: center, mainAxisSize: min, crossAxisAlignment: center)>
  state: _HeroState#35499
When the exception was thrown, this was the stack: 
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:266:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:277:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:296:21)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4729:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
...
====================================================================================================
```

</details>

**Comment by biklas7** [comment]
Tried to create a new sample project to reproduce the error and it's not happening. I'm assuming that the problem must be related to my code and not Flutter itself. 
If anyone has faced the same issue please comment below, otherwise sorry for opening it without checking it first on a sample project.

**Comment by Tameflame** [comment]
I have this same issue, but resulting in a blackscreen major error. it's very hard to reproduce but it's happening consistently in my code and the only solution I have is to remove my snackbar before making  page  transitions

**Comment by biklas7** [comment]
@Tameflame I still have the same problem, and that's the solution I have implemented for now. Removing the snackbar on the willpop widget.

**Comment by Tameflame** [comment]
@biklas7 

Check if you have a scaffold in another scaffold on ur tree. That could be the error

I.e scaffold(body: scaffold(...

Something like that.

I think if there are nested scaffolds in the widget tree scaffold messenger sends a snackbar to all of them. Causing the duplicate hero isue

**Comment by biklas7** [comment]
@Tameflame I thought that I wasn't nesting Scaffolds, but after reading your comment and searching carefully in my code I found that I was nesting Scaffolds in a screen where I had a `BottomNavigationBar` and an `IndexedStack`. The nesting was inside the stack :sweat_smile: 

Thanks :+1:
