### ISSUE TITLE
Flutter needs to be more open to the developer.

### ISSUE THREAD

**Issue by icnahom** [flutter/flutter#72135]
## Use case
I want control of my `PageRoute` as I `push` it, but I can't because `controller` is `@protected` in the `TransitionRoute`.

**Example use case would be:**
- Many apps have a Notification button on the top right of the screen, but in order to make it easier they let users swipe left to get to the Notification Screen instead of reaching for the button.

## Proposal
![unknown](https://user-images.githubusercontent.com/60504285/101893536-ee6a5f00-3bb5-11eb-9dd7-5418dd2768a3.png)
My heart tells me the ideal way of Developing this in Flutter:
- `onHorizontalDragStart` - `push` the route with a `controller.value` of `0.1`
- `onHorizontalDragUpdate` - update route's `controller.value` 
- `onHorizontalDragEnd` - decide if I should `push` or `pop`

I wish everything in Flutter was done the "Flutter Way".
p.s `DraggableScrollableSheet` suffers from this kind of issue as well (#45009). We don't have any control of it. Please give us more control of our widgets. We need more control!

**Comment by iapicca** [comment]
@icnahom 
listening to `dragupdate` and manually updating the `controller` (that you are asking to have access to) 
**_doesn't seem declarative_** to me, but very much **_imperative_**

are you using [navigation 2.0](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade) ?
can you provide a minimal reproducible code sample?

**Comment by TahaTesser** [comment]
Hi @icnahom 
Agree with @iapicca, can you please provide more details and a code sample to show what limitations you're facing, explain your proposal in detail 
Thank you

**Comment by icnahom** [comment]
@iapicca you're right. A video I saw on YouTube had me to miss understand declarative way of programming. Sorry!

@iapicca Currently I have implemented my own `Stack`, `SlideTransition`, `GestureDetector`, `AnimationController` and `WillPopScope`. Everything is working. But this is a work-around, and I feel like I didn't have to include all these extra lines in my codebase if I had access to the `controller` and had the ability to tell what to Navigator do. Like passing my own `controller` and pushing that route the way I wanted it.

Question to Taha and iapicca:
I want to see how you think this should be done? If one wanted to slide a new page in from the side.

**Comment by TahaTesser** [comment]
Hi @icnahom 
To me this looks very custom, not everybody needs this control or should have,  this could be a package and anybody can use it to get the same results.

What are your thoughts? @iapicca

**Comment by iapicca** [comment]
@TahaTesser 
in my opinion exposing the `controller` in `TransitionRoute` is dangerous and against [Unidirectional Data Flow](https://en.wikipedia.org/wiki/Unidirectional_Data_Flow_(computer_science)) pattern

**Comment by icnahom** [comment]
> regardless the use case I'm against it
You're against a very common UX practice amongst many popular apps?

**Comment by iapicca** [comment]
> > regardless the use case I'm against it
> 
> You're against a very common UX practice amongst many popular apps?

yes if it is...
>dangerous and against [Unidirectional Data Flow](https://en.wikipedia.org/wiki/Unidirectional_Data_Flow_(computer_science)) pattern

**Comment by icnahom** [comment]
I know, and that's why Flutter allows us to provide our own `controller` in some places. That's the reason I love the Flutter Framework so much! 

Who likes including a package for every controlless widget in Flutter? No one.
