### ISSUE TITLE
set up a travis cron job for the website

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#7213]
The travis bot for the website validates the code snippets against the latest flutter framework source. This is good, but we don't get validation until someone pushes a PR to the website.

Travis has a new fancy cron job feature, which we could use to regularly test the website snippets. The blog has a bit more info: https://docs.travis-ci.com/user/cron-jobs/

Somebody with admin access would have to flip a bit here in the settings page: https://travis-ci.org/flutter/website.

**Comment by abarth** [comment]
I added a daily cron job.

**Comment by sethladd** [comment]
Cool, thanks for pointing this out!
