### ISSUE TITLE
[webview_flutter] - Cookie same name, same value but different domain doesn't work

### ISSUE THREAD

**Issue by Jokernight** [flutter/flutter#72130]
Hello,

I'm facing an issue with cookies in the webview plugin. 

I have two cookies to set by two different urls, this two cookies have the same name and the same value but a different domain, One is for access and the other for the images.

I first load the access cookie URL which set it good, and then with the PageFinished event, I load the image cookie URL, and then again with the PageFinished event I load the website. I have access to the website but the images are not loading at all.

By looking at the document.cookie variable, I have only one cookie with this name and value.

This issue is for both Android and iOS.

Thanks by advance for your help !

## Steps to Reproduce

1. Open a webview and set a cookie.
2. Load an other url with a cookie which has the same name and value but different domain

**Expected results:** 
Have the 2 cookies set in the webview

**Actual results:**
Only the first cookie is set and the second is ignored

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale fr-BE)
    • Flutter version 1.22.3 at /Users/dev/Desktop/Projects/SDK/flutter
    • Framework revision 8874f21e79 (6 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode 12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @Jokernight 
Can you please provide ` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Jokernight** [comment]
Hi @TahaTesser, 

Here is the flutter run --verbose with the document.cookie printed

<details>
  <summary>Flutter run</summary>
I/WebViewFactory(10782): Loading com.google.android.webview version 74.0.3729.185 (code 373018518)
[   +4 ms] I/com.saipm.dh(10782): The ClassLoaderContext is a special shared library.
[  +58 ms] I/com.saipm.dh(10782): The ClassLoaderContext is a special shared library.
[        ] I/cr_LibraryLoader(10782): Time to load native libraries: 9 ms (timestamps 6397-6406)
[  +23 ms] I/chromium(10782): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
[        ] I/cr_LibraryLoader(10782): Expected native library version number "74.0.3729.185", actual native library version number "74.0.3729.185"
[   +7 ms] W/cr_ChildProcLH(10782): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
[   +3 ms] W/com.saipm.dh(10782): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (greylist, reflection,
allowed)
[  +12 ms] I/cr_BrowserStartup(10782): Initializing chromium process, singleProcess=false
[ +112 ms] W/com.saipm.dh(10782): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (greylist,
reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
(greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
(greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection, allowed)
[        ] W/com.saipm.dh(10782): Accessing hidden method
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;
(greylist, reflection, allowed)
[  +24 ms] W/cr_media(10782): Requires BLUETOOTH permission
[  +15 ms] D/HostConnection(10782): HostConnection::get() New Host Connection established 0xb6218dd0, tid 10996
[  +32 ms] D/HostConnection(10782): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan
ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles
ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing
ANDROID_EMU_gles_max_version_2 
[   +1 ms] E/chromium(10782): [ERROR:gl_surface_egl.cc(342)] eglChooseConfig failed with error EGL_SUCCESS
[   +4 ms] D/EGL_emulation(10782): eglCreateContext: 0xb6289a20: maj 2 min 0 rcv 2
[   +8 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xb6289a20: ver 2 0 (tinfo 0xb6301290)

[  +15 ms] E/chromium(10782): [ERROR:gl_surface_egl.cc(342)] eglChooseConfig failed with error EGL_SUCCESS
[  +10 ms] I/VideoCapabilities(10782): Unsupported profile 4 for video/mp4v-es
[   +7 ms] W/cr_MediaCodecUtil(10782): HW encoder for video/avc is not available on this device.
[   +3 ms] D/EGL_emulation(10782): eglCreateContext: 0xb51a90c0: maj 2 min 0 rcv 2
[   +1 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xb51a90c0: ver 2 0 (tinfo 0xb6301290)
[  +54 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[   +4 ms] W/Gralloc3(10782): allocator 3.x is not supported
[  +28 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[  +30 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[   +7 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[ +152 ms] I/flutter (10782): initial
[ +135 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xb51a90c0: ver 2 0 (tinfo 0xb6301290)
[  +50 ms] I/flutter (10782): COOKIE ====> "__gfp_64b=jeEcSCCmmmSbdNbxyOVVBdRxS__6p8PRYH3XNIEnTSP.W7|1606922355; _gcl_au=1.1.2043608803.1606922357; cX_S=ki7k2y40ktvnieku; cX_P=ki7k2y42os5uj94s; _ga=GA1.2.1289434766.1606922357;
_fbp=fb.1.1606922357394.1453655733; sbt_i=7OTIzMTM3M2MtMTA2Yi00NzM0LWJlYTktMjk1NDIzY2U0YzEyOzZjkyYjg3ODktMGU5MC00ZjgwLWFlMzQtODY1OWMyZjBkYWM3OzsE=; cX_G=cx%3Au3flieiucuk139g18tvpev6c6%3A985pzdt3enyx; cstp=604800;
ddsg=8ljvl2jc8v9j.8n3patb4zc40; ;
didomi_token=eyJ1c2VyX2lkIjoiMTc2MjQwOTQtOWE3YS02ODlkLWFmMDItZWQzYjY0MTQ0YjkzIiwiY3JlYXRlZCI6IjIwMjAtMTItMDhUMTA6NTc6MDguMzc0WiIsInVwZGF0ZWQiOiIyMDIwLTEyLTA4VDEwOjU3OjA4LjM3NFoiLCJ2ZXJzaW9uIjoyLCJwdXJwb3NlcyI6eyJlbmFibGVkIjpbImRldml
jZV9jaGFyYWN0ZXJpc3RpY3MiLCJnZW9sb2NhdGlvbl9kYXRhIl19LCJ2ZW5kb3JzIjp7ImVuYWJsZWQiOlsiZ29vZ2xlIl19LCJ2ZW5kb3JzX2xpIjp7ImVuYWJsZWQiOlsiZ29vZ2xlIl19fQ==;
euconsent-v2=CO-GZgsO-GZgsAHABBENBDCsAP_AAH_AAAAAHKNf_X_fb3_j-_59_9t0eY1f9_7_v20zjgeds-8Nyd_X_L8X42M7vF36pq4KuR4Eu3LBIQdlHOHcTUmw6IkVqTPsbk2Mr7NKJ7PEinMbe2dYGH9_n9XTuZKY79_s___z__-__v__77f_r-3_3_v
[   +2 ms] I/flutter (10782): secondary
[   +1 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[  +13 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[  +19 ms] I/a@268042015(10782): Clearing queue as user status changed
[  +17 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[  +30 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[        ] I/flutter (10782): COOKIE ====> "arc-access=vT5Jqa7PceSk9Hj4"
[  +19 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[ +249 ms] D/EGL_emulation(10782): eglMakeCurrent: 0xe12682a0: ver 2 0 (tinfo 0xc17ad030)
[+3631 ms] I/chromium(10782): [INFO:CONSOLE(1)] "<link rel=preload> has an unsupported `type` value", source: https://sandbox.dhnet.be/?outputType=android (1)
[ +688 ms] I/chatty  (10782): uid=10133(com.saipm.dh) identical 5 lines
[   +1 ms] I/chromium(10782): [INFO:CONSOLE(1)] "<link rel=preload> has an unsupported `type` value", source: https://sandbox.dhnet.be/?outputType=android (1)
[        ] I/chromium(10782): [INFO:CONSOLE(72)] "TypeError: Cannot read property 'sg' of null", source: https://sandbox.dhnet.be/?outputType=android (72)
[  +52 ms] I/chromium(10782): [INFO:CONSOLE(1)] "A parser-blocking, cross site (i.e. different eTLD+1) script,
https://www.ultimedia.com/api/widget/videolistjs?j=new&t=1607688128809&otherplayer=0&exclude=&videolist=qs3lu0&url=https%3A%2F%2Fsandbox.dhnet.be%2F%3FoutputType%3Dandroid&mdtk=01032022&zone=11&autoplay=no&layout=pix_slide_xl&target
=_ultimedia_widget_wrapper, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be
confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://www.ultimedia.com/js/common/videolist.js (1)
[   +3 ms] I/chromium(10782): [INFO:CONSOLE(1)] "A parser-blocking, cross site (i.e. different eTLD+1) script,
https://www.ultimedia.com/api/widget/videolistjs?j=new&t=1607688128809&otherplayer=0&exclude=&videolist=qs3lu0&url=https%3A%2F%2Fsandbox.dhnet.be%2F%3FoutputType%3Dandroid&mdtk=01032022&zone=11&autoplay=no&layout=pix_slide_xl&target
=_ultimedia_widget_wrapper, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be
confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://www.ultimedia.com/js/common/videolist.js (1)

</details>

And here is a sample code i've done for you to try it out :

<details>
<summary> Code Sample </summary>

```
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewWidget extends StatefulWidget {

  const WebViewWidget({Key key}) : super(key: key);

  static WebViewWidgetAppState of(BuildContext context) => context.findAncestorStateOfType();

  @override
  WebViewWidgetAppState createState() => new WebViewWidgetAppState();
}

class WebViewWidgetAppState extends State<WebViewWidget> {
  WebViewController controller;

  final Completer<WebViewController> _controller = Completer<WebViewController>();

  bool isInitialLoading = true;
  bool isSecondaryLoading = false;

  @override
  void initState() {
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: "https://sandbox.dhnet.be/4QotAuo9P5003YiB/",
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        _controller.complete(webViewController);
        setState(() {
          controller = webViewController;
        });
      },
      onPageFinished: (String url) {
        if(isSecondaryLoading) {
          isSecondaryLoading = false;

          controller.loadUrl("https://sandbox.dhnet.be?outputType="+getPlatform().toLowerCase());

          print("secondary");
          this.getCookie();
        }

        if (isInitialLoading) {
          isInitialLoading = false;

          controller.loadUrl("https://ipmgroup-dhnet-sandbox.cdn.arcpublishing.com/4QotAuo9P5003YiB/");

          isSecondaryLoading = true;

          print("initial");
          this.getCookie();
        }
      },
      gestureNavigationEnabled: true,
    );
  }

  Future<void> getCookie() async {
    final cookiesString = await controller.evaluateJavascript('document.cookie');

    print("COOKIE ====> $cookiesString");

  }

  String getPlatform() {
    // Platform detection in order to construct the new UserAgent
    String deviceData;

    if (Platform.isAndroid) {
      deviceData = "android";
    } else if (Platform.isIOS) {
      deviceData = "ios";
    } else {
      deviceData = "Other";
    }

    return deviceData;
  }

}
```
</details>

Thanks in advance ;)

**Comment by TahaTesser** [comment]
Hi @Jokernight 
I can reproduce the issue 
<details> 
<summary>logs</summary> 

```bash
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/Choreographer( 4943): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
Restarted application in 1,992ms.
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
V/PhoneWindow( 4943): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@4c7a24a, this = DecorView@12fee9f[MainActivity]
D/Surface ( 4943): Surface::connect(this=0x6f7b783000,api=1)
D/mali_winsys( 4943): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface ( 4943): Surface::setBufferCount(this=0x6f7b783000,bufferCount=4)
I/SurfaceView( 4943): 24788529 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
D/ViewRootImpl( 4943): setSurfaceViewCreated, created:true
I/SurfaceView( 4943): 24788529 surfaceChanged -- format=4 w=1080 h=2400 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
D/SurfaceView( 4943): updateScreenMode w:1080 h:2400 ViewRoot w:1080 h:2400
D/SurfaceView( 4943): try to resquest 60Hz
D/ViewRootImpl( 4943): set screen refresh mode 1 due to SurfaceView-24788529
D/SurfaceView( 4943): updateScreenMode w:1080 h:2400 ViewRoot w:1080 h:2400
D/SurfaceView( 4943): try to resquest 60Hz
I/flutter ( 4943): initial
I/flutter ( 4943): COOKIE ====> "arc-access=vT5Jqa7PceSk9Hj4; cX_P=kioadnu41ygfsdn0; __gfp_64b=BIjHz17NpSAyfGFrcYreh4T2ekTZYk0hGhlaeE9aqBP.e7|1607933983; didomi_token=eyJ1c2VyX2lkIjoiMTc2NjA1NWEtYTExMy02ZmQyLWE5MGUtODFiM2QzNjE1OTE3IiwiY3JlYXRlZCI6IjIwMjAtMTItMTRUMDg6MjU6MzIuMDc5WiIsInVwZGF0ZWQiOiIyMDIwLTEyLTE0VDA4OjI1OjMyLjA3OVoiLCJ2ZW5kb3JzIjp7ImVuYWJsZWQiOlsiZ29vZ2xlIl19LCJwdXJwb3NlcyI6eyJlbmFibGVkIjpbImRldmljZV9jaGFyYWN0ZXJpc3RpY3MiLCJnZW9sb2NhdGlvbl9kYXRhIl19LCJ2ZW5kb3JzX2xpIjp7ImVuYWJsZWQiOlsiZ29vZ2xlIl19LCJ2ZXJzaW9uIjoyfQ==; euconsent-v2=CO-Z07ZO-Z07ZAHABBENBDCsAP_AAH_AAAAAHKNf_X_fb3_j-_59_9t0eY1f9_7_v20zjgeds-8Nyd_X_L8X42M7vF36pq4KuR4Eu3LBIQdlHOHcTUmw6IkVqTPsbk2Mr7NKJ7PEinMbe2dYGH9_n9XTuZKY79_s___z__-__v__77f_r-3_3_vp9V---_fA5QAkw1L4CLMSxwJJo0qhRAhCuJDoAQAUUIwtE1hASuCnZXAR-ggYAIDUBGBECDEFGLIIAAAAAkoiAkAPBAIgCIBAACAFSAhAARoAgsAJAwCAAUA0LACKAIQJCDI4KjlMCAiRaKCeSMASi72MMIQyigBoFH4AAAAA.f_gAD_gAAAAA; cX_S=kioaqs8oe9y446bx; cX_G=cx%3A3lzcjrtyau0yk18vll99z1zhzd%3A1aockj8qugme6; _ga=GA1.2.1787667149.1607934604; _gid=GA1.2.1319
I/Choreographer( 4943): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4943): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/flutter ( 4943): secondary
I/flutter ( 4943): COOKIE ====> "arc-access=vT5Jqa7PceSk9Hj4"
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/chromium( 4943): [INFO:CONSOLE(1)] "<link rel=preload> has an unsupported `type` value", source: https://sandbox.dhnet.be/?outputType=android (1)
I/chatty  ( 4943): uid=10532(com.nevercode.triage) identical 5 lines
I/chromium( 4943): [INFO:CONSOLE(1)] "<link rel=preload> has an unsupported `type` value", source: https://sandbox.dhnet.be/?outputType=android (1)
I/chromium( 4943): [INFO:CONSOLE(72)] "TypeError: Cannot read property 'sg' of null", source: https://sandbox.dhnet.be/?outputType=android (72)
I/Choreographer( 4943): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/chromium( 4943): [INFO:CONSOLE(1)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.ultimedia.com/api/widget/videolistjs?j=new&t=1607935146595&otherplayer=0&exclude=&videolist=qs3lu0&url=https%3A%2F%2Fsandbox.dhnet.be%2F%3FoutputType%3Dandroid&mdtk=01032022&zone=11&autoplay=no&layout=pix_slide_xl&target=_ultimedia_widget_wrapper, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://www.ultimedia.com/js/common/videolist.js (1)
I/Choreographer( 4943): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/chromium( 4943): [INFO:CONSOLE(12)] "VIDEOJS: WARN: A plugin named "errors" already exists. You may want to avoid re-registering plugins!", source: https://cdnjs.cloudflare.com/ajax/libs/video.js/7.7.5/video.min.js (12)
I/chromium( 4943): [INFO:CONSOLE(12)] "VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead", source: https://cdnjs.cloudflare.com/ajax/libs/video.js/7.7.5/video.min.js (12)
I/chromium( 4943): [INFO:CONSOLE(1)] "fun-hooks: referenced 'registerAdserver' but it was never created", source: https://www.ultimedia.com/js/player-digiteka/dtkplayer-vjs.js?v=5.10.44 (1)
I/chromium( 4943): [INFO:CONSOLE(1)] "The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features", source: https://www.ultimedia.com/js/player-digiteka/dtkplayer-vjs.js?v=5.10.44 (1)
I/chromium( 4943): [INFO:CONSOLE(12)] "The deviceorientation events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features", source: https://cdnjs.cloudflare.com/ajax/libs/video.js/7.7.5/video.min.js (12)
I/chromium( 4943): [INFO:CONSOLE(1)] "[object DOMException]", source: https://www.ultimedia.com/js/player-digiteka/dtkplayer-vjs.js?v=5.10.44 (1)
I/chromium( 4943): [INFO:CONSOLE(38)] "Error: Bad Request", source: https://sandbox.dhnet.be/pf/dist/engine/react.js?d=587 (38)
I/chatty  ( 4943): uid=10532(com.nevercode.triage) identical 1 line
I/chromium( 4943): [INFO:CONSOLE(38)] "Error: Bad Request", source: https://sandbox.dhnet.be/pf/dist/engine/react.js?d=587 (38)
I/chromium( 4943): [INFO:CONSOLE(38)] "Error: {"Reason":"ReservedFunctionConcurrentInvocationLimitExceeded","Type":"User","message":"Rate Exceeded."}", source: https://sandbox.dhnet.be/pf/dist/engine/react.js?d=587 (38)
I/chromium( 4943): [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'dataLayer' of undefined", source: https://sandbox.dhnet.be/?outputType=android (1)
I/chromium( 4943): [INFO:CONSOLE(0)] "The script has an unsupported MIME type ('text/html').", source:  (0)
I/chromium( 4943): [INFO:CONSOLE(35)] "ServiceWorker registration failed:  [object DOMException]", source: https://sandbox.dhnet.be/pf/dist/components/combinations/android.js?d=587 (35)
I/chromium( 4943): [INFO:CONSOLE(38)] "Error: Bad Request", source: https://sandbox.dhnet.be/pf/dist/engine/react.js?d=587 (38)
I/SurfaceView( 4943): 24788529 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
D/ViewRootImpl( 4943): setSurfaceViewCreated, created:false
D/Surface ( 4943): Surface::disconnect(this=0x6f7c543000,api=-1)
D/SurfaceView( 4943): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView( 4943): try to resquest 90Hz
D/ViewRootImpl( 4943): set screen refresh mode 0 due to SurfaceView-24788529
I/GED     ( 4943): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (4 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android
      10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS
      14.2

! Doctor found issues in 1 category.
```

</details>

Perhaps this be night be addressed by https://github.com/flutter/flutter/issues/27795  https://github.com/flutter/plugins/pull/2999
CC @Sunbreak 
Thoughts?

**Comment by Jokernight** [comment]
Hello,

Any news for this issue ?
