### ISSUE TITLE
Make `_DialogRoute` a public class

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#72138]
https://github.com/flutter/flutter/blob/7891006299/packages/flutter/lib/src/widgets/routes.dart#L1697-L1756

`_DialogRoute` is used in `showGeneralDialog` which is used in `showDialog`. Today, in the era of Navigator 2.0 it would be _really_ handy to have the ability of showing a material dialog in a declarative, not imperative way. 

## Use case

My specific use case uses declarative routes for deeplinks and "global" handlers. So that whenever user clicks on a specific deeplink he may be shown a dialog. I know I can do it the other way. I'm asking for the declarative approach.

## Proposal

My proposal is to make the `_DialogRoute` class a public one and prospectively make it viable to use in the userspace, not only inside the Flutter framework.

**Comment by TahaTesser** [comment]
Hi @Albert221 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/29106
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Albert221** [comment]
I agree with you that it's a duplicate. But I'm describing here the need for this in the context of Navigator 2.0. I'll comment on the issue you mentioned too, then :)
