### ISSUE TITLE
flutter build or xcode archive get ipa,Flutter.framework size is different.

### ISSUE THREAD

**Issue by len8657** [flutter/flutter#72133]
flutter build or xcode archive get ipa,Flutter.framework size is different.
```
build -release: 202.6M
build- debug: 33.4M
arichive: 7.7M
```
------------------------
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (4 available)
    ! Error: Walter的iPad is busy: Waiting for Device. Xcode will continue when Walter的iPad is finished. (code -10)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @len8657 
Please check out https://flutter.dev/docs/perf/app-size, to read more app sizes 
App sies could vary for various reasons between debug and relase, hope this helps
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by len8657** [comment]
> Hi @len8657
> Please check out https://flutter.dev/docs/perf/app-size, to read more about app sizes
> App sies could vary for various reasons between debug and relase, hope this helps
> Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
> Thank you


I have read this article. The information provided in the article cannot answer my doubts.
I had find some information in Xcode archive Packaging.log
-----------------------------
2020-12-14 01:31:37 +0000          $ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip -r -o /var/folders/td/4819yvmx4md_xm0jj_m02p140000gn/T/ipatool20201214-85786-1waez9s/thinned-out/arm64/Payload/Runner.app/Frameworks/Flutter.framework/Flutter /var/folders/td/4819yvmx4md_xm0jj_m02p140000gn/T/ipatool20201214-85786-1waez9s/thinned-in/arm64/Payload/Runner.app/Frameworks/Flutter.framework/Flutter
------------------------------
I use '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip -r -o ' bitcode_strip, Flutter.framework size from 202.6M to 7.7M.
flutter build -release, xcode arichive  ,two way is different.
I want to understand what happened in this process

**Comment by TahaTesser** [comment]
@len8657 
Please take a look at this issue https://github.com/flutter/flutter/issues/64626 and https://github.com/flutter/website/issues/4852
