### ISSUE TITLE
[google_sign_in_web] latest google_sign_in doesn't point to latest google_sign_in_web

### ISSUE THREAD

**Issue by praveeno** [flutter/flutter#72131]
I updated google_sign_in:  ^4.5.6, to latest version
and it is updated locally, ( checked .flutter-plugins file, pointing to /google_sign_in-4.5.6/)
but google_sign_in_web is still pointing to /google_sign_in_web-0.9.1+1/ path, and seems like i didn't get this pull req https://github.com/flutter/plugins/pull/2943

ditman suggested that he published on v0.9.2.

so, do i have to manually add google_sign_in_web: ^v0.9.2 in pub file, or this should fetch by google_sign_in ?
![image](https://user-images.githubusercontent.com/19618730/101888443-24164480-3bc4-11eb-8109-e40b8bf506b0.png)

**Comment by praveeno** [comment]
Hello @ditman, 
you submitted a pull request on this, can you help me understand how to use it properly.

Thank You

**Comment by praveeno** [comment]
[maybe because google_web_in still pointing to ^0.9.1,](https://github.com/flutter/plugins/blob/7d392476ac20569c8afd9ebc5f0328d383fdc7c5/packages/google_sign_in/google_sign_in/pubspec.yaml#L28)
let me know if this is the issue, I would love to submit a PR.
Thanks

**Comment by TahaTesser** [comment]
Hi @praveeno 
Thanks for filing the issue, it does still point to a previous of 1`google_sign_in_web`
While it gets updated, you do the following
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.6
  http: ^0.12.2
  google_sign_in_web: ^0.9.2
```
```lock
  google_sign_in_web:
    dependency: "direct main"
    description:
      name: google_sign_in_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.2"
```

Thank you

**Comment by ditman** [comment]
Pub should be able to resolve this @praveeno, ^0.9.1 means "everything equals or greater than 0.9.1, but less than 0.10.0".

Can you try doing a `flutter clean` and doing `flutter pub get` again? It should refresh your dependencies. Also ensure that your pubspec.lock isn't locking 0.9.1 (you may want to try and delete the pubspec.lock file to grab all the latest versions)

**Comment by praveeno** [comment]
Hello @ditman @TahaTesser, I already did manually added google_sign_in_web: ^0.9.2, in pub yaml
also let me know if i can update version in google_sign_in, what steps should i follow ?
I would love to submit a PR for this

**Comment by ditman** [comment]
> I would love to submit a PR for this

@praveeno there's no need to update the `google_sign_in` package, but if you want to collaborate with any other open bug, feel free to do so!

Here's some instructions to get you started:

* https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md

**Comment by praveeno** [comment]
Thank you for update me on this.
