### ISSUE TITLE
--target-platform contains binaries for multiple platforms

### ISSUE THREAD

**Issue by safield** [flutter/flutter#72146]
I am running 'flutter build apk --debug --target-platform=android-arm'.

After inspecting the apk, it still has .so files targetting x86 and x86_64.

The espected behaviour, is that the apk will only contain binaries for the target platform.

**Comment by darshankawar** [comment]
@safield 
Can you provide `flutter doctor -v` ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
