### ISSUE TITLE
engine roll failed flutter_gallery_ios__transition_perf test; autoroller disabled

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#72158]
On engine roll https://github.com/flutter/flutter/pull/72147 the flutter_gallery_ios__transition_perf test failed consistently. The engine roll was reverted in https://github.com/flutter/flutter/pull/72155 and the engine autoroller was set into dry mode. The framework tree went back to green after the revert.

There was no meaningful/obvious error message in the log: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyLzdjMmNmZmZhZDYwOTlhNmExYzZlMDFhMGRmOWFlNDdjZjY4NWFjNmQMCxIEVGFzaxiAgJjbkayLCgw

On the same engine roll, this flake also appeared: https://github.com/flutter/flutter/issues/72153 (maybe related?)

**Comment by chinmaygarde** [comment]
Dan reverted the PR that caused the issue. Closing.

**Comment by chinmaygarde** [comment]
Autoroller has been re-enabled.
