### ISSUE TITLE
Flutter crashing on Samsung S6 Edge running 5.1

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7215]
I apologize had copied wrong info... This is for hello_services "flow" Works fine in development on Moto X.

Same issue as well on Xperia Z5 Premium (E6853) 4 running Android 6.0

I could imagine that the other library I create causes some sort of conflict? that library builds to the following targets: x86, arm64-v8a, x86_64, armeabi-v7a

**Comment by jtrunick** [comment]
java.lang.RuntimeException: Unable to create application org.domokit.sky.shell.SkyApplication: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
	at io.flutter.view.FlutterMain.initNative(FlutterMain.java:218)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:122)
	at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
	... 8 more
Caused by: org.chromium.base.library_loader.ProcessInitException
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
	at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
	at io.flutter.view.FlutterMain.initNative(FlutterMain.java:214)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/harpsoft.bendometer.ui.android-2/base.apk"],nativeLibraryDirectories=[/data/app/harpsoft.bendometer.ui.android-2/lib/arm64, /data/app/harpsoft.bendometer.ui.android-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libsky_shell.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
	... 14 more

**Comment by eseidelGoogle** [comment]
Can you tell us more about what you're trying to run?  Is this `flutter run` or the `hello_services` flow?  Looks like it's saying 'couldn't find "libsky_shell.so"'.  Maybe it's an arm64 device which doesn't know how to do armv7 fallback?

**Comment by eseidelGoogle** [comment]
According to those specs it's an ARM7 device (32-bit) so I don't see why its saying anything about arm64 in the logs?

**Comment by jtrunick** [comment]
Sorry accidently deleted, but realized this was reported for a different device:
Galaxy S6 Edge (zerolte) 1

java.lang.RuntimeException: Unable to create application org.domokit.sky.shell.SkyApplication: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
	at io.flutter.view.FlutterMain.initNative(FlutterMain.java:218)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:122)
	at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
	... 8 more
Caused by: org.chromium.base.library_loader.ProcessInitException
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
	at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
	at io.flutter.view.FlutterMain.initNative(FlutterMain.java:214)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/harpsoft.bendometer.ui.android-2/base.apk"],nativeLibraryDirectories=[/data/app/harpsoft.bendometer.ui.android-2/lib/arm64, /data/app/harpsoft.bendometer.ui.android-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libsky_shell.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
	... 14 more

**Comment by eseidelGoogle** [comment]
So that one: http://www.gsmarena.com/samsung_galaxy_s6_edge-7079.php is a 64-bit device.

Now we just need to know how you're running on that device? :)  Also `flutter doctor` output would be helpful.

**Comment by jtrunick** [comment]
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision b7f8ec667c (3 weeks ago), 
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[-] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 7.3, Build version 7D175
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin installed
    • Flutter plugin installed

**Comment by jtrunick** [comment]
Joels-MBP:android joel$ ./gradlew build
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:libraries:sp:preBuild UP-TO-DATE
:libraries:sp:preReleaseBuild UP-TO-DATE
:libraries:sp:checkReleaseManifest
:libraries:sp:preDebugAndroidTestBuild UP-TO-DATE
:libraries:sp:preDebugBuild UP-TO-DATE
:libraries:sp:preDebugUnitTestBuild UP-TO-DATE
:libraries:sp:preReleaseUnitTestBuild UP-TO-DATE
:libraries:sp:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:libraries:sp:prepareReleaseDependencies
:libraries:sp:compileReleaseAidl UP-TO-DATE
:libraries:sp:compileLint UP-TO-DATE
:libraries:sp:copyReleaseLint UP-TO-DATE
:libraries:sp:compileReleaseRenderscript UP-TO-DATE
:libraries:sp:generateReleaseBuildConfig UP-TO-DATE
:libraries:sp:generateReleaseResValues UP-TO-DATE
:libraries:sp:generateReleaseResources UP-TO-DATE
:libraries:sp:mergeReleaseResources UP-TO-DATE
:libraries:sp:processReleaseManifest UP-TO-DATE
:libraries:sp:processReleaseResources UP-TO-DATE
:libraries:sp:generateReleaseSources UP-TO-DATE
:libraries:sp:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:compileReleaseJavaWithJavac UP-TO-DATE
:libraries:sp:extractReleaseAnnotations UP-TO-DATE
:libraries:sp:mergeReleaseShaders UP-TO-DATE
:libraries:sp:compileReleaseShaders UP-TO-DATE
:libraries:sp:generateReleaseAssets UP-TO-DATE
:libraries:sp:mergeReleaseAssets UP-TO-DATE
:libraries:sp:mergeReleaseProguardFiles UP-TO-DATE
:libraries:sp:packageReleaseRenderscript UP-TO-DATE
:libraries:sp:packageReleaseResources UP-TO-DATE
:libraries:sp:processReleaseJavaRes UP-TO-DATE
:libraries:sp:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:libraries:sp:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:libraries:sp:generateJsonModelRelease UP-TO-DATE
:libraries:sp:externalNativeBuildRelease
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/release/obj/x86/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/release/obj/arm64-v8a/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/release/obj/x86_64/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/release/obj/armeabi-v7a/libSuperpoweredExample.so
:libraries:sp:mergeReleaseJniLibFolders UP-TO-DATE
:libraries:sp:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:libraries:sp:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:libraries:sp:bundleRelease UP-TO-DATE
:app:prepareAndroidLibrariesSpUnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:flutterBuild
Building AOT snapshot in release mode (android-arm-release)... 8433ms
Built to /Users/joel/dev_3rd/flutter/examples/hello_services/android/app/build/intermediates/flutter/.
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:copyFlutterAssetsDebug
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:transformNative_libsWithStripDebugSymbolForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:mergeReleaseShaders UP-TO-DATE
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:copyFlutterAssetsRelease
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources UP-TO-DATE
:app:generateReleaseSources UP-TO-DATE
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
:app:transformClassesWithDexForRelease UP-TO-DATE
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:app:transformNative_libsWithStripDebugSymbolForRelease UP-TO-DATE
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:validateSigningRelease
:app:packageRelease
:app:assembleRelease
:app:assemble
:app:lint
Ran lint on variant release: 5 issues found
Ran lint on variant debug: 5 issues found
Wrote HTML report to file:///Users/joel/dev_3rd/flutter/examples/hello_services/android/app/build/outputs/lint-results-debug.html
Wrote XML report to file:///Users/joel/dev_3rd/flutter/examples/hello_services/android/app/build/outputs/lint-results-debug.xml
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:app:processDebugUnitTestJavaRes UP-TO-DATE
:app:compileDebugUnitTestSources UP-TO-DATE
:app:mockableAndroidJar UP-TO-DATE
:app:assembleDebugUnitTest UP-TO-DATE
:app:testDebugUnitTest UP-TO-DATE
:app:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preReleaseUnitTestBuild UP-TO-DATE
:app:prepareReleaseUnitTestDependencies
:app:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:app:processReleaseUnitTestJavaRes UP-TO-DATE
:app:compileReleaseUnitTestSources UP-TO-DATE
:app:assembleReleaseUnitTest UP-TO-DATE
:app:testReleaseUnitTest UP-TO-DATE
:app:test UP-TO-DATE
:app:check
:app:build
:libraries:sp:checkDebugManifest
:libraries:sp:prepareDebugDependencies
:libraries:sp:compileDebugAidl UP-TO-DATE
:libraries:sp:copyDebugLint UP-TO-DATE
:libraries:sp:compileDebugRenderscript UP-TO-DATE
:libraries:sp:generateDebugBuildConfig UP-TO-DATE
:libraries:sp:generateDebugResValues UP-TO-DATE
:libraries:sp:generateDebugResources UP-TO-DATE
:libraries:sp:mergeDebugResources UP-TO-DATE
:libraries:sp:processDebugManifest UP-TO-DATE
:libraries:sp:processDebugResources UP-TO-DATE
:libraries:sp:generateDebugSources UP-TO-DATE
:libraries:sp:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:compileDebugJavaWithJavac UP-TO-DATE
:libraries:sp:extractDebugAnnotations UP-TO-DATE
:libraries:sp:mergeDebugShaders UP-TO-DATE
:libraries:sp:compileDebugShaders UP-TO-DATE
:libraries:sp:generateDebugAssets UP-TO-DATE
:libraries:sp:mergeDebugAssets UP-TO-DATE
:libraries:sp:mergeDebugProguardFiles UP-TO-DATE
:libraries:sp:packageDebugRenderscript UP-TO-DATE
:libraries:sp:packageDebugResources UP-TO-DATE
:libraries:sp:processDebugJavaRes UP-TO-DATE
:libraries:sp:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:libraries:sp:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:libraries:sp:generateJsonModelDebug UP-TO-DATE
:libraries:sp:externalNativeBuildDebug
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/debug/obj/x86/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/debug/obj/arm64-v8a/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/debug/obj/x86_64/libSuperpoweredExample.so
  building /Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/intermediates/cmake/debug/obj/armeabi-v7a/libSuperpoweredExample.so
:libraries:sp:mergeDebugJniLibFolders UP-TO-DATE
:libraries:sp:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:libraries:sp:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:libraries:sp:bundleDebug UP-TO-DATE
:libraries:sp:compileDebugSources
:libraries:sp:assembleDebug
:libraries:sp:compileReleaseSources
:libraries:sp:assembleRelease
:libraries:sp:assemble
:libraries:sp:lint
Ran lint on variant debug: 2 issues found
Ran lint on variant release: 2 issues found
Wrote HTML report to file:///Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/outputs/lint-results-debug.html
Wrote XML report to file:///Users/joel/dev_3rd/flutter/examples/hello_services/android/libraries/sp/build/outputs/lint-results-debug.xml
:libraries:sp:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:prepareDebugUnitTestDependencies
:libraries:sp:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:libraries:sp:processDebugUnitTestJavaRes UP-TO-DATE
:libraries:sp:compileDebugUnitTestSources UP-TO-DATE
:libraries:sp:mockableAndroidJar UP-TO-DATE
:libraries:sp:assembleDebugUnitTest UP-TO-DATE
:libraries:sp:testDebugUnitTest UP-TO-DATE
:libraries:sp:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:prepareReleaseUnitTestDependencies
:libraries:sp:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:libraries:sp:processReleaseUnitTestJavaRes UP-TO-DATE
:libraries:sp:compileReleaseUnitTestSources UP-TO-DATE
:libraries:sp:assembleReleaseUnitTest UP-TO-DATE
:libraries:sp:testReleaseUnitTest UP-TO-DATE
:libraries:sp:test UP-TO-DATE
:libraries:sp:check
:libraries:sp:build

BUILD SUCCESSFUL

**Comment by eseidelGoogle** [comment]
In the above log I see superpowered building for 4 variants, and flutter (expectedly) only building for ARMv7.  It's possible that the resulting APK is partially-fat.  It has an arm64 directory, but that only contains libSuperpowered.so and not libsky_shell.so.  It's possible to build Flutter for all these variants, but you'll need to build flutter/engine yourself, since we currently only provide the ARMv7 flavor for the hello_services workflow.  https://github.com/flutter/engine/blob/master/CONTRIBUTING.md are the instructions for building your own flutter/engine artifacts.

**Comment by eseidelGoogle** [comment]
One way to work around this would be to strip out all the non-armv7 directories from the APK, then the APK wouldn't be confused into thinking it supports arm64 when it doesn't. :)

**Comment by jtrunick** [comment]
this theory sounds correct, i just didn't know much about how it functioned.

**Comment by eseidelGoogle** [comment]
@jakobr-google this may have been fixed by the gradle work?

**Comment by Hixie** [comment]
@jtrunick Over the past year we have changed our build system substantially so we believe this has probably been resolved in the meantime. Please do let us know (by filing a new bug) if it is still affecting you.
