### ISSUE TITLE
AlertDialog doesn't draw properly in release mode

### ISSUE THREAD

**Issue by etorunski** [flutter/flutter#72160]
Run the application in release mode, and click on the "click me" button.

1. Run `flutter create bug`.
2. Update the files as follows:       
     paste this into main.dart:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold( appBar: AppBar(title: Text(widget.title) ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: <Widget>[
              Text("hello",style:TextStyle( fontSize: 20)),
              GestureDetector(
                  onTap: () { _displayRateDialog(context, "Interest Rate");},
                  child:Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        Text("click me",style:TextStyle( fontSize: 20)),
                        Icon(Icons.add_circle_outline)])
              )])])));
  }

  _displayRateDialog(BuildContext context, String hint) async {
    double numEntered = 0;
    return showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: Text("Enter Number"),
            content: new Expanded(
                child: new TextField(
                  keyboardType: TextInputType.number,
                  autofocus: true,
                  decoration: new InputDecoration(hintText: hint),
                  onChanged: (value) {
                    setState(() { numEntered = double.parse(value); });
                  },
                )),

            actions: <Widget>[
              new FlatButton( textColor: Colors.black,
                  child: new Text("Cancel"), onPressed:() {  Navigator.of(context).pop(); } ),
              new FlatButton(
                textColor: Colors.black,
                child: new Text('Ok'),
                onPressed: () {
                  setState(() {
                  });
                  Navigator.of(context).pop();
                },
              )
            ],
          );
        });
  }
}


```

3. Run the program in release mode. Press the "Click me" button.

**Expected results:**  

In debug you see this:
![image](https://user-images.githubusercontent.com/6123729/101958173-ca684700-3bd0-11eb-910b-7472d86e7cd2.png)

**Actual results:** 
In release you see this:
![Unknown](https://user-images.githubusercontent.com/6123729/101958570-97728300-3bd1-11eb-9963-3fe34b7ca880.png)

<details>
  <summary>Logs</summary>
![image](https://user-images.githubusercontent.com/6123729/101958632-b2dd8e00-3bd1-11eb-850b-0bcd9a5b87dc.png)

etorunski@Erics-MacBook-Pro bug % flutter analyze
Analyzing bug...                                                        

   info • The value of the field '_counter' isn't used • lib/main.dart:31:7 •
          unused_field
   info • The declaration '_incrementCounter' isn't referenced •
          lib/main.dart:33:8 • unused_element
   info • The value of the local variable 'numEntered' isn't used •
          lib/main.dart:59:12 • unused_local_variable

3 issues found. (ran in 2.4s)

[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-CA)
    • Flutter version 1.25.0-8.0.pre at /Users/etorunski/Flutter/flutter
    • Framework revision a12e2a473a (3 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/etorunski/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Pixel 4a (mobile)    • 0A301JEC210711                           •
      android-arm64  • Android 11 (API 30)
    • Eric's iPad (mobile) • 84fadd133843759e4cded5d795e901b41feca972 • ios
      • iOS 14.2
    • macOS (desktop)      • macos                                    •
      darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                                   •
      web-javascript • Google Chrome 87.0.4280.88

• No issues found!

</details>

**Comment by etorunski** [comment]
It turns out that if you get rid of the line:
content: new Expanded(

then it works in Release mode

**Comment by Abhishek01039** [comment]
@etorunski 
`Expanded` should be only used in `column` or `Row`

you should remove `Expanded`.

Thanks

**Comment by darshankawar** [comment]
@etorunski 
As mentioned above, `Expanded` widget is recommended to be used if you have `Column` or `Row` or any `Flex` widget. Using it without any of the desired widgets results in unusual behavior as you saw.
I am going ahead and closing this as non-issue from Flutter framework, but an issue with code implementation. If you disagree, write in comments and I'll reopen it.
