### ISSUE TITLE
Why is flutter 1.22.5 only 125 mb for mac?

### ISSUE THREAD

**Issue by essuraj** [flutter/flutter#72168]
Flutter 1.22.4 on mac was around 900 MB I remember but the newest one is only 125MB. and any operation ends in flutter building message, had to roll back

**Comment by pedromassangocode** [comment]
Hi @essuraj 
What "building messages" are you getting? Can provide those messages?
Thank you

**Comment by essuraj** [comment]
it says building flutter tool... snd is stuck
i think its because of a dns issue
chnaged my dns to 8.8.8.8 and got fixed, but not sure hwy new flutter build is so small

**Comment by pedromassangocode** [comment]
I'm not sure as well, but is it working just fine?
