### ISSUE TITLE
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#14a4e](state: OverlayState#b3cf9(tickers: tracking 3 tickers, entries: [OverlayEntry#f9bf6(opaque: true; maintainState: false), OverlayEntry#94f39(opaque: false; maintainState: true)])): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2036 pos 12: '_elements.contains(element)': is not true.

### ISSUE THREAD

**Issue by maksymtrilenko** [flutter/flutter#72174]
```
The relevant error-causing widget was: 
  MaterialApp file:///Users/nbz/AndroidStudioProjects/coop_planograms/lib/main.dart:11:5
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:2036:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3526:29)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3551:32)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
```

Happens on SearchDelegate Back button tap when executing method:
close(context, null);

Only happens on iOS, and not every time, roughly 50:50.

**Comment by darshankawar** [comment]
@maksymtrilenko 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by maksymtrilenko** [comment]
Issue replication:
1. Call [Barras](https://pub.dev/packages/barras) barcode reader which navigates to a new panel from the main route.

2. Scan a barcode which sets the **result** string in the main route's **State** class to the barcode data after which **ShowSearch** is executed with the
**query: int.tryParse(result).toString() ?? result** parameter and value
The search panel loads with **query** set to the scanned barcode data.

3. The issue occurs on **IconButton** **onPressed() { query = ''; close(context, null); }** execution from **SearchDelegate**

Fixed by wrapping the whole main route **State** class **Scaffold** in **WillPopScope(onWillPop: () async => false,)**

**Comment by darshankawar** [comment]
@maksymtrilenko 
Closing this based on your comment above. If you disagree, write in comment and I'll reopen it.
Thanks.
