### ISSUE TITLE
 When I am building a new project in Flutter, when I am giving a new flutter SDK path, then it is not able to found the flutter SDK path in Linux OS.

### ISSUE THREAD

**Issue by phenomenal25** [flutter/flutter#72183]
The flutter sdk installation is incomplete please see https://flutter.dev/get-started

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (35 hours ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by flutternooob** [comment]
I have a similar issue on windows, but it says a file named flutter already exists. But thats just the start of my problems with flutter. Its been five days and I've still not even been able to write one line. No customer support either. Crazy.

**Comment by phenomenal25** [comment]
> I have a similar issue on windows, but it says a file named flutter already exists. But thats just the start of my problems with flutter. Its been five days and I've still not even been able to write one line. No customer support either. Crazy.

What is your flutter version?

**Comment by flutternooob** [comment]
Its 6.1.7601. Ive had do many problems its unreal i have no idea who to ask to help posted on multiple forums everyone just saying the same things and none if its working.

**Comment by phenomenal25** [comment]
> Its 6.1.7601. Ive had so many problems its unreal i have no idea who to ask to help posted on multiple forums everyone just saying the same things and none if its working.

run flutter --version command and then check what is your flutter version

**Comment by flutternooob** [comment]
Oh ok that was on flutter doctor the number i put there maybe that was the windows version sorry. Its 1.22.4 then is that right?

**Comment by flutternooob** [comment]
And right now i cant run any flutter commands im having to delete and reinstall for the 6th time now.

**Comment by phenomenal25** [comment]
> Oh ok that was on flutter doctor the number i put there maybe that was the windows version sorry. Its 1.22.4 then is that right?
above my problem is occuring in the latest flutter version 1.22.5

**Comment by flutternooob** [comment]
So what does that mean? Sorry im new to all this. Just trying to learn. What is the options?

**Comment by TahaTesser** [comment]
Hi @phenomenal25 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs and contents of `local.properties` file in your Android folder 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by naresh-upadhyay** [comment]
Just down grade your version to 1.22.4 it working fine. But version 1.22.5 showing the error .

**Comment by ssparun** [comment]
Just down grade your version to 1.22.4 it working fine. But version 1.22.5 showing the error .
thanks naresh bro is error ne to meri maa ch** di bosdike flutter team jab stable version n ho to release kue krte ho

**Comment by ssparun** [comment]
> Just down grade your version to 1.22.4 it working fine. But version 1.22.5 showing the error .

time sever its working

**Comment by TahaTesser** [comment]
@naresh-upadhyay  @ssparun 
Could you please provide details from https://github.com/flutter/flutter/issues/72183#issuecomment-744361913

**Comment by ragu-swaminathan** [comment]
It seems, some of the artifacts are missing in the flutter version 1.22.5.  I tried downloading it from the source and looks like, cache and mingit directories are missing in the version.  However, running flutter doctor may fix them.

**Comment by PriyaSindkar** [comment]
Yes, some artifacts are indeed missing from 1.22.5 and 1.22.6. I downgraded to 1.22.4 and it's working fine now. FYI, I am working on ubuntu v. 20.04

**Comment by eddienuel** [comment]
@ragu-swaminathan Yeah you are right running flutter doctor fixed it. previous versions come with dart and other tools. starting from 1.22.5, you have to run flutter doctor to install dart SDK and other files and tools. Just to confirm check the size of 1.22.6 is around 140MB while I was trying to downgrade to 1.22.4 the file was around 600+MB.
