### ISSUE TITLE
Can't catch Dart exception

### ISSUE THREAD

**Issue by Adrift001** [flutter/flutter#72188]
https://github.com/flutter/crashy
this code can't catch Dart exception

**Comment by Adrift001** [comment]
![image](https://user-images.githubusercontent.com/8119320/101978672-b2a4c780-3c91-11eb-8385-45794e7c3bd9.png)

**Comment by iapicca** [comment]
@Adrift001 
can you double check the [installation steps](https://github.com/flutter/crashy#crashy)
and provide your `flutter doctor -v` and you your `flutter run -v`
