### ISSUE TITLE
Why Testflight showing Ask Permission Request will be sent to Parent/Guardian while purchasing subscription

### ISSUE THREAD

**Issue by junaidlodhi22** [flutter/flutter#72192]
I am developing an application using **_in_app_purchase_** from flutter.
it works fine on android but on ios after subscribing to the in-app product(auto-renewing subscription) it asks permission. My client's iPhone does not have family sharing turned on and we are on testflight with internal testing.

check the video to see behavior [video link](https://youtu.be/1umE0EgKLkA)

I think because of ask permission it is not allowing the purchase completed.
the code works perfectly fine in android

my purchase stream code
```final Stream purchaseUpdates = InAppPurchaseConnection.instance.purchaseUpdatedStream;
    purchaseUpdates.listen((purchases) async {
      for (PurchaseDetails purchase in purchases) {
        if (purchase.status == PurchaseStatus.error) {
          print(purchase.error.code);
          print(purchase.error.message);
          print(purchase.error.details);
          reUse.show_toast("payment problem if");
          reUse.show_toast(purchase.status.toString());
          in_app_purchase.completePurchase(purchase);
        } else if (purchase.status == PurchaseStatus.purchased) {
          await reUse.add_purchase_details_to_user_account(
            user_id,
            purchase.purchaseID,
            purchase.transactionDate,
            purchase.billingClientPurchase.purchaseToken,
            purchase.billingClientPurchase.signature,
            selected_plan,
            purchase.billingClientPurchase.orderId,
          );
          reUse.show_toast("success");
          in_app_purchase.completePurchase(purchase);
          setState(() {
            subscribed = true;
          });
        } else {
          reUse.show_toast("payment problem else");
          reUse.show_toast(purchase.status.toString());
        }
      }
    });
```

**Comment by darshankawar** [comment]
@junaidlodhi22 
This looks very similar to [this](https://github.com/flutter/flutter/issues/68626) issue. Please check [this](https://github.com/flutter/flutter/issues/68626#issuecomment-713664740) issue comment and see if it helps to resolve your issue.

**Comment by junaidlodhi22** [comment]
thanks, @darshankawar. the message of ask permission gets removed. Getting a message that you are successfully subscribed. 
But the above purchase code is still not running
```
 purchaseUpdates.listen((purchases) async {
      for (PurchaseDetails purchase in purchases) {
        if (purchase.status == PurchaseStatus.error) {
          print(purchase.error.code);
          in_app_purchase.completePurchase(purchase);
        } else if (purchase.status == PurchaseStatus.purchased) {
          await reUse.add_purchase_details_to_user_account(
            user_id,
            purchase.purchaseID,
            purchase.transactionDate,
          );
          in_app_purchase.completePurchase(purchase);
        } else {
          reUse.show_toast("payment problem else");
        }
      }
    });
```

**Comment by darshankawar** [comment]
@junaidlodhi22 Good to know your `permission` is now resolved. 
Regarding your other issue, can you provide `flutter doctor -v` and which use case isn't working exactly related to purchase subscription ?
Thanks.

**Comment by junaidlodhi22** [comment]
I got it resolved. @darshankawar thank you again for helping...
actually, I was using the client's mobile to test so I could not see the error...
it was because of **_purchasewrapper_** class parameter **_billingClientPurchase_**
it is null on ios and that's why my code was breaking. I went into the code and saw that.
