### ISSUE TITLE
Fresh start vs Full restart are behaving differently when using DraggableScrollableSheet.

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#72199]
## Steps to Reproduce
Run this code:

```
void main()  => runApp(MaterialApp(home: FooPage()));

class FooPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DraggableScrollableSheet(
        builder: (_, controller) {
          return ColoredBox(
            color: Colors.blue,
            child: ListView.builder(
              controller: controller,
              itemCount: 20,
              itemBuilder: (_, i) => ListTile(title: Text('Item $i')),
            ),
          );
        },
      ),
    );
  }
}
```

### Problem:
On the first run, `DraggableScrollableSheet` works as expected, the list is filling up the entire available space on dragging. Now, do a full restart. This time the `DraggableScrollableSheet` is behaving differently. It isn't allowing the content to take up the space. This is weird. You can watch this behavior in [this video](https://www.dropbox.com/s/e1femay6mkcf8e1/screen-recording-2020-12-12-at-45524-pm_64zyB8HV_P8uv.mov?dl=0). Jump to 0:30 (where fresh install occurs)

### Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-10.2.pre, on Mac OS X 10.15.7)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.49.0)
[✓] Connected device (4 available)
```

**Comment by Dev-SK** [comment]
https://www.youtube.com/watch?v=Hgw819mL_78&vl=en
Watch this builder need a scrollable widget.

**Comment by darshankawar** [comment]
@iLoveDocs 
I tried your code sample on latest stable using Android 8.1.0 device but didn't see the issue after I did hot restart from IDE as well as from terminal (R). 
From your video, it seems you are using an emulator. Can you provide OS version of emulator ? Also can you try it on physical device and see if you get similar behavior ?

**Comment by iLoveDocs** [comment]
@darshankawar I ran the app on:
- Emulator (Android 11)
- Physical device (Android 10)

Same behavior.

**Comment by darshankawar** [comment]
@iLoveDocs 
It seems the issue is only happening on dev 1.24 version. I tried it on stable and master latest versions, the issue doesn't occur. 
Can you try to upgrade to latest dev (1.25) and see if you get same behavior ?
Also, dev branch is updated everyday and is very dynamic. I'd suggest you to be either on master or stable for your app / project. 
Anyways, you may try to upgrade to latest dev and see if issue persists or not.
Thanks.

**Comment by iLoveDocs** [comment]
@darshankawar 

> Also, dev branch is updated everyday and is very dynamic. I'd suggest you to be either on master or stable for your app / project.

Are you sure you aren't interchanging "master" with "dev"?

**Comment by darshankawar** [comment]
@iLoveDocs 
Verified on latest dev and saw no issues. 

[72199_d.mov.zip](https://github.com/flutter/flutter/files/5693777/72199_d.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a12e2a473a (6 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!


```

</details>

**Comment by iLoveDocs** [comment]
@darshankawar Upgrade fixed the issue.
