### ISSUE TITLE
Gallery: don't show red error messages in Input demo on initial load

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7219]
From a review by material eng.

We probably don't want to default show all the red error messages from the fields in the Text Input demo on Gallery.

Those error messages should only appear when a user tries to submit the form. Then we can show any validation errors.

**Comment by mpcomplete** [comment]
Clarification questions:
- should this apply to forms in general?
- should we update error messages in real time as the user types? or only update them when the user submits? or start updating them in real time after the first submit?

**Comment by sethladd** [comment]
cc @jestelle 

> should this apply to forms in general?

Yes, I think so. Don't show error messages unless the API (or developer) triggers the display of the error messages.

> should we update error messages in real time as the user types?

This should be up to the developer. Sometimes developers want to show errors when the user "tabs" out of the field, or as the user types, or after submit.
