### ISSUE TITLE
[tool_crash] ProcessException: A operação solicitada requer elevação. Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740

### ISSUE THREAD

**Issue by jimypavon** [flutter/flutter#72204]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: A operação solicitada requer elevação.
 Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740
```

```
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [versÃ£o 10.0.19042.685], locale pt-BR)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\jimyp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.0)
    • VS Code at C:\Users\jimyp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.60

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_core-0.4.5
firebase_core_web-0.1.1+2
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3

**Comment by jmagman** [comment]
This is permission denied.
We're missing the stack trace, can you attach the crash log that was generated at the same time?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by jimypavon** [comment]
I already understood the problem, it's about the new flutter update that does not present those elements in the console, however nothing happens and I can continue working normally.

Thanks

**Comment by jmagman** [comment]
This was closed because we were waiting for more information: 

> We're missing the stack trace, can you attach the crash log that was generated at the same time?

Can you give more details about what you mean here?  This issue is showing a crash in the command line tool so what does "continue working normally" mean?
> it's about the new flutter update that does not present those elements in the console, however nothing happens and I can continue working normally.

**Comment by jimypavon** [comment]
Thanks, Jmagman..
Check, even install flutter again and it kept giving the same problem, then the code that was working gave that problem, it was fixed and the part that had to work did it normally, consulting some colleagues, they informed me that this error is due to update of the flutter
