### ISSUE TITLE
Right, configuration by abstraction via pubspec, flutter tools argument or some other flutter side API are likely all subcomponents of option 2. By not letting users touch the platform build system for the module, we translate some for them. Works for 1-2 things but not for 10-20 things. This is also against the backdrop that the user is likely to try to edit everything for an outer project but may not necessarily want to do so for an inner module project.

### ISSUE THREAD

**Issue by SaavyGirl** [flutter/flutter#72208]
Right, configuration by abstraction via pubspec, flutter tools argument or some other flutter side API are likely all subcomponents of option 2. By not letting users touch the platform build system for the module, we translate some for them. Works for 1-2 things but not for 10-20 things. This is also against the backdrop that the user is likely to try to edit everything for an outer project but may not necessarily want to do so for an inner module project.

__Originally posted by @xster in https://github.com/flutter/flutter/issues/32989#issuecomment-494159359__

**Comment by bernaferrari** [comment]
the title is too long, you should reduce to something readable

**Comment by iapicca** [comment]
@SaavyGirl 

> Right, configuration by abstraction via pubspec, flutter tools argument or some other flutter side API are likely all subcomponents of option 2. By not letting users touch the platform build system for the module, we translate some for them. Works for 1-2 things but not for 10-20 things. This is also against the backdrop that the user is likely to try to edit everything for an outer project but may not necessarily want to do so for an inner module project.
> 
> **Originally posted by @xster in [#32989 (comment)](https://github.com/flutter/flutter/issues/32989#issuecomment-494159359)**

I miss the point of copy pasting someone else comment without any explanation or details, 
especially considering that  said comment has definitely being taken in account already and the issue being evaluated and closed by the team.

Can you provide more details about the point you are trying to make?

**Comment by TahaTesser** [comment]
Hi @SaavyGirl 
Looks like you created the using this option 
<img width="345" alt="Screenshot 2020-12-14 at 5 47 38 PM" src="https://user-images.githubusercontent.com/48603081/102080521-955c2e80-3e34-11eb-8603-87cc996eb5d4.png">


This issue doesn't seem to add anything, 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you"
