### ISSUE TITLE
integration-test legacy and null safety

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#72209]
flutter analyze
Analyzing ec...

   info - The library 'package:integration_test/integration_test.dart' is legacy, and should not be imported into a null safe library - integration_test\app_test.dart:10:8 - import_of_legacy_library_into_null_safe
   info - The library 'package:integration_test/integration_test_driver.dart' is legacy, and should not be imported into a null safe library - integration_test\driver.dart:6:8 - import_of_legacy_library_into_null_safe

2 issues found. (ran in 2.3s)

**Comment by pedromassangocode** [comment]
Hi @benedicte69 
Can you please elaborate more what this issue is about?
Thank you

**Comment by benedicte69** [comment]
hello @pedro,

here flutter analyze with environment: sdk: ">=2.7.0 <3.0.0"
 
flutter analyze
Running "flutter pub get" in mix...                                595ms
Analyzing mix...
No issues found! (ran in 2.6s)

here flutter analyze with environment: sdk: ">=2.12.0-0 <3.0.0" (that is for nullsafety)

flutter analyze
Analyzing mix...

   info - The library 'package:integration_test/integration_test.dart' is legacy, and should not be imported into a null safe library - integration_test\app_test.dart:10:8 - import_of_legacy_library_into_null_safe
   info - The library 'package:integration_test/integration_test_driver.dart' is legacy, and should not be imported into a null safe library - integration_test\driver.dart:6:8 - import_of_legacy_library_into_null_safe

2 issues found. (ran in 2.4s)

It is just informative, but...

The app is just the flutter demo one, master channel, Gradle 6.7

**Comment by pedromassangocode** [comment]
Yes, this is a known issue and is being tracked by https://github.com/flutter/flutter/issues/71379.

Follow up on https://github.com/flutter/flutter/issues/71379 for more updated, I'm closing this as a duplicate.
Thank you
