### ISSUE TITLE
Add ColorScheme.of(context)

### ISSUE THREAD

**Issue by LasseRosenow** [flutter/flutter#72201]
## Use case
Now that we have `TextTheme.of(context)` I think we should also have `ColorScheme.of(context)`, as I think most of the time `Theme.of(context)` is called, its just to access the `colorScheme` property.

Writing `Theme.of(context).colorScheme` is very long.
Writing `ColorScheme.of(context)` would be faster and also much cleaner

## Proposal

Add `ColorScheme.of(context)`

**Comment by amal-stack** [comment]
Another common use-case for `Theme.of(context)` is to access the `ThemeData.textTheme` property. 
I often find myself doing:
```dart
final ThemeData(:colorScheme, :textTheme) = Theme.of(context);
```

I believe along with `ColorScheme.of(context)`, a companion `TextTheme.of(context)` would also be of help which would provide access to `ThemeData.textTheme`. There is also `ThemeData.primaryTextTheme` which is not that commonly used but for parity, a `TextTheme.primaryOf(context)` can be added.
