### ISSUE TITLE
Scrollbar width is way to big compared to native mobile behavior 

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#72202]
The current scrollbar implementation has a width of 8, but native android apps have scrollbars with a width of something like 4.
Ther current scrollbar looks very big and weird to me.

## Use case

Changing the scrollbar width would make flutter look much more consistent to native android applications.

## Proposal

Change the scrollbar width for android to 4.0.

**Comment by asterix11** [comment]
Please handle this issue very soon, it feels very uncomfortable with that king size scrollbar currently served.

**Comment by TahaTesser** [comment]
Hi @lazylazyllama 
Can you please provide visual comparison and documentation if possible
Thank you

**Comment by Piinks** [comment]
@lazylazyllama the default scrollbar thickness is in line with Material Design specifications, there is a way to change the default though. You can set `Scrollbar.thickness` to the desired value.

**Comment by HansMuller** [comment]
Should the default scrollbar thickness "adapt" to the underlying platform?

**Comment by Piinks** [comment]
> Should the default scrollbar thickness "adapt" to the underlying platform?

I have reached out to the design team to ask exactly that question! :)

**Comment by lazylazyllama** [comment]
> @lazylazyllama the default scrollbar thickness is in line with Material Design specifications, there is a way to change the default though. You can set `Scrollbar.thickness` to the desired value. 

So that means that the native android implementation breaks with the current material design? Because in every native app the scrollbar is much thinner 🤔

**Comment by lazylazyllama** [comment]
@Piinks are you sure, the material design team was talking about the basic scrollbar width on Android and not the draggable? Because it makes sense for the draggable scrollbar to have a higher width, but the default scrollbar on Android is not draggable and thus way smaller

**Comment by Piinks** [comment]
> the default scrollbar on Android is not draggable and thus way thinner

That is correct! I just heard back on my inquiry to the design team. The difference is in  interaction vs. a visual indicator. We can add a separate thickness for a passive/indicator `Scrollbar`, and apply it automatically when we do not have a `ScrollController` - which is required for  dragging and tapping on the scrollbar.

WDYT @lazylazyllama?

I am also working on a `ScrollbarTheme` (https://github.com/flutter/flutter/pull/72308) right now, so we can factor this into that as well, so any desirable thickness in any state can be achieved across the whole app. :)

**Comment by lazylazyllama** [comment]
@Piinks That sounds very good :) I'm looking forward to it 😊

**Comment by lazylazyllama** [comment]
Actually what I just thought of: On the web scrollbars are draggable by default, so will they automatically get a Scrollcontroller on the web? Or do we have to add them with conditional statements to check the current platform?
