### ISSUE TITLE
flutter emulator uses wrong cmdline on Crostini for AVD

### ISSUE THREAD

**Issue by kaladron** [flutter/flutter#72205]
When executing the following command:

```flutter emulator --launch Pixel_4_API_30```

flutter chains out to:

```Android/Sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64 -avd Pixel_4_API-30```

which gives a pop-up saying that nested KVM performance is bad, and has terrible performance.

However, when executing with the commandline:

```Android/Sdk/emulator/emulator -avd Pixel_4_API-30 -crostini```

there is no warning and performance is acceptable.

**Comment by kaladron** [comment]
It looks like just adding -crostini to the qemu commandline also fixed performance.

I think just adding it to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_emulator.dart#L152 is probably enough, but nothing else in the code seems to detect crostini.

**Comment by TahaTesser** [comment]
Hi @kaladron 
Could you please provide your `flutter doctor -v` and `flutter emulator --launch Pixel_4_API_30 --verbose`
Thank you

**Comment by kaladron** [comment]
afterihavedreamed@penguin:~/Programming/uscis_test$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/afterihavedreamed/Programming/flutter
    • Framework revision 7891006299 (5 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/afterihavedreamed/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

**Comment by kaladron** [comment]
afterihavedreamed@penguin:~/Programming/uscis_test$ flutter emulator --launch Pixel_4_API_30 --verbose
[ +120 ms] executing: [/home/afterihavedreamed/Programming/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78910062997c3a836feee883712c241a5fd22983
[        ] executing: [/home/afterihavedreamed/Programming/flutter/] git tag --points-at HEAD
[  +15 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[  +12 ms] executing: [/home/afterihavedreamed/Programming/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/afterihavedreamed/Programming/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/home/afterihavedreamed/Programming/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +42 ms] executing: /home/afterihavedreamed/Android/Sdk/emulator/emulator -list-avds
[ +186 ms] Pixel_4_API_30
[   +5 ms] executing: /home/afterihavedreamed/Android/Sdk/emulator/emulator -avd Pixel_4_API_30
[+3018 ms] "flutter emulators" took 3,288ms.
[ +141 ms] ensureAnalyticsSent: 134ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by TahaTesser** [comment]
Hi @kaladron 
Can you please provide details of the device you use? 
Also, you can lunch emulator from Android Studio? Does it show the same warning?

**Comment by kaladron** [comment]
I'm on a Chromebook using a Crostini container.  I haven't tried launching from Android Studio.  The command line given in flutter emulator -v above shows the command-line as incorrect.

```[   +5 ms] executing: /home/afterihavedreamed/Android/Sdk/emulator/emulator -avd Pixel_4_API_30```

When running under Crostini, this command requires -crostini at the end to be performant.

**Comment by TahaTesser** [comment]
Hi @kaladron 
I just wanna make sure it is the same issue if you launch from UI In Android Studio
Thanks

**Comment by kaladron** [comment]
We're going to try to fix this in Android Studio to just detect it correctly instead.
