### ISSUE TITLE
Support for package formats

### ISSUE THREAD

**Issue by chrissxYT** [flutter/flutter#72218]
## Use case
When you want to actually ship your Flutter app on most platforms, you have to use different formats. Windows has MSIs and EXEs for its installers, macOS uses DMGs and PKGs as packages, iOS has IPAs and DEBs, and Linux, of course, is total chaos: DEB, RPM, APK (Alpine), Tarballs, …

## Proposal
Flutter's job in my opinion should should not be to support all package formats out there, but since you already support a few formats (APK (Android), AAB, IPA), it would be nice to have support for a few more common ones. Specifically I'd suggest supporting these ones:
* DMG or PKG (other people have already proposed it (e.g. #71674) and it's literally [2 shell commands](https://github.com/Ampless/Amplessimus/blob/e302755ab8d1474cd320e91e9bd3b04ce7d6f691/Makefile#L142))
* DEB (someone from the jailbreaking community would be able to implement it in half an hour, but for devs, who don't know a lot about the matter, it's quite hard (I have failed at it myself))
* MSI, EXE, Choco or WinGet
* AppImage/Docker/… (something portable that works on most modern Linuxes)

**Comment by jmagman** [comment]
This is going to get a lot more traction if you make an issue per suggested format.  Totally different teams (and even companies) work on different platforms, and it's going to be much easier for them to schedule and prioritize if they are separated out.

**Comment by stuartmorgan** [comment]
It appears that this is covering the desktop platfroms, so I'll say broadly that we don't currently have any plans to build these into the tool (precisely for the reason that you mentioned: there are a lot of them; supporting all of them is impractical, and there are not obvious criteria for choosing the others). I expect that each platform will have an ecosystem of third-party packaging utilities.

As @jmagman said, the right way to do this proposal would be with specific issues for each format (some such issues already have been filed) so they can be discussed individually. The merits vary per platform and format.
