### ISSUE TITLE
Navigator 2 Flaw Missing Browser History Control

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#72212]
This is a dedicated issue to properly highlight the Navigator 2 flaw I identified in https://github.com/flutter/flutter/issues/63429#issuecomment-742979410 

Hope to discuss with someone on the Flutter team. @chunhtai 

The issues:
- There is no way to intercept browser navigation and "prevent" navigation. Browser forward and backward button both call didPushRoute and pass the information to the RouterDelegate's setNewRoutePath. Because of the underlying browser implementation of forward and backward buttons, I understand there is no way to capture if forward or backward is pressed. However, the issue is that Navigator 2 does not offer a way to override forward or backward navigation. 
- There is no way to customize the browser history or programmatically navigate forward / backwards from Navigator 2. 

The combination of the above 2 issues means that there is no way to keep the browser and Navigator 2 state in sync. 

Here are some common use cases that are prevented by the issues listed above.
1. Showing a one-time onboarding flow. The user can always press back to navigate back to the onboarding flow because it cannot be removed from the browser history. Setting the onboarding flow to redirect to the homescreen after completion causes the browser and Navigator to no longer be synchronized. The URL shows 'onboarding' while the user is redirected to the 'home' page.
2. Showing a login page. Page 1 -> Page 2 -> Login Page -> Successfully completed login, return to Page 2
The login page is now stuck in the back history. After the user logs in successfully, pressing back should not take the user back to the login page. Instead, it should take the user to Page 1. 
3. Save use generated content / in progress work. Say the user is drawing a drawing. Pressing the browser navigation button should not cause them to lose their work. Instead, we can override the handle setNewRoutePath to prevent navigation and prompt the user to save their work whenever a browser navigation event occurs. However, if we do this, the browser is no longer in sync with the app state. While the user is still on the drawing page, the URL can change to the home page or any other page in the history stack.
4. Conditional flows where flow direction matters. A shopping cart flow would want to prevent backwards navigation to the shopping flow after the user completes checkout. A survey flow would want to prevent forward navigation if the user changes the previous answer and needs to be redirected to another question.

To support the above use cases with Navigator 2, I would need to do the following to override Navigator 2 behavior as follows:
- Maintain my own internal representation of the browser history stack. 
- Whenever parseRouteInformation is called, intercept and use Navigator.navigate() to override the URL to match my internal app state. 

Essentially, I would be writing my own Navigator and fighting with Navigator 2 because Navigator 2 cannot support the use cases I need. 

Please let me know if a code sample or example would help illustrate the issue.

<details>
<summary>Flutter Doctor</summary>
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.24.0-10.2.pre at D:\Development\flutter-sdk
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Development\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Development\android-sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Laptop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.47
</details>

**Comment by TahaTesser** [comment]
Hi @searchy2 
Thanks for filing the issue
Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by searchy2** [comment]
Please replicate the behavior with the following test case in my provided minimal reproducible sample.

http://testing.codelessly.com/develop/app/20201216/navigation_prevention/#/

The sample has two pages.

'Home' page.
![MaxthonSnap20201216205648](https://user-images.githubusercontent.com/19896174/102438119-54ede380-3fe1-11eb-9e58-108aa2f94910.png)

'Project' page.
![MaxthonSnap20201216205656](https://user-images.githubusercontent.com/19896174/102438138-5ddeb500-3fe1-11eb-917a-ba8fcf0a9a83.png)

1. Navigate to the Project page by clicking 'Open Project' on the Home page.
2. Toggle `canPop` to false by clicking the 'Toggle Can Pop' button. When `canPop` is set to false, `setNewRoute` updates are skipped and navigation is prevented. This is the only way I've found to prevent browser navigation.
3. Navigate back to the Home page with the browser back button.
4. Now, the URL shows the Home URL but the current page is still the Projects page.

The end result.
![MaxthonSnap20201216210330](https://user-images.githubusercontent.com/19896174/102438575-2b818780-3fe2-11eb-8a2b-da9f434473f0.png)

This example demonstrates that in order to prevent navigation, Navigator 2's routing is disabled and navigation gets out of sync.

Code:

```dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

Future<Null> main() async => runApp(App());

class App extends StatelessWidget {
  MainRouterDelegate mainRouterDelegate = MainRouterDelegate();
  MainRouteInformationParser mainRouteInformationParser =
      MainRouteInformationParser();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Codelessly',
      routerDelegate: mainRouterDelegate,
      routeInformationParser: mainRouteInformationParser,
      debugShowCheckedModeBanner: false,
    );
  }
}

/// The RouteDelegate defines application specific behaviors of how the router
/// learns about changes in the application state and how it responds to them.
/// It listens to the RouteInformation Parser and the app state and builds the Navigator with
/// the current list of pages (immutable object used to set navigator's history stack).
class MainRouterDelegate extends RouterDelegate<MainRoute>
    with ChangeNotifier, PopNavigatorRouterDelegateMixin<MainRoute> {
  //This is the state of the navigator widget (in build method).
  GlobalKey<NavigatorState> get navigatorKey => GlobalKey<NavigatorState>();

  /// Internal backstack and pages representation.
  List<MainRoute> _mainRoutes = [];
  List<MainRoute> get mainRoutes => _mainRoutes;

  bool _canPop = true;
  bool get canPop {
    if (_canPop == false) return false;

    return _mainRoutes.isNotEmpty;
  }

  set canPop(bool canPop) => _canPop = canPop;

  /// CurrentConfiguration detects changes in the route information
  /// It helps complete the browser history and enables browser back and forward buttons.
  MainRoute get currentConfiguration =>
      mainRoutes.isNotEmpty ? mainRoutes.last : null;

  @override
  Widget build(BuildContext context) {
    return Navigator(
        key: navigatorKey,
        pages: [
          if (mainRoutes.isEmpty)
            MainPageBuilder(context, MainRoute.home()).page,
          for (MainRoute path in mainRoutes)
            MainPageBuilder(context, path).page,
        ],
        onPopPage: (route, result) {
          print('Pop Page');
          if (!route.didPop(result)) {
            return false;
          }
          if (canPop) {
            pop();
          }
          return true;
        });
  }

  @override
  Future<void> setNewRoutePath(MainRoute path) async {
    print('Set New Route Path: ${path.name}');
    if (_canPop == false) return SynchronousFuture(null);
    if (path == currentConfiguration) return SynchronousFuture(null);
    _mainRoutes = _setNewRouteHistory(_mainRoutes, path);
    print('Main Routes: $mainRoutes');
    notifyListeners();
    return SynchronousFuture(null);
  }

  @override
  Future<bool> popRoute() {
    print('Pop Route');
    return super.popRoute();
  }

  /// Updates route path history.
  ///
  /// In a browser, forward and backward navigation
  /// is indeterminate and a custom path history stack
  /// implementation is needed.
  /// When a [newRoute] is added, check the existing [routes]
  /// to see if the path already exists. If the path exists,
  /// remove all path entries on top of the path.
  /// Otherwise, add the new path to the path list.
  List<MainRoute> _setNewRouteHistory(
      List<MainRoute> routes, MainRoute newRoute) {
    List<MainRoute> pathsHolder = [];
    pathsHolder.addAll(routes);
    // Check if new path exists in history.
    for (MainRoute path in routes) {
      // If path exists, remove all paths on top.
      if (path == newRoute) {
        int index = routes.indexOf(path);
        int count = routes.length;
        for (var i = index; i < count - 1; i++) {
          pathsHolder.removeLast();
        }
        return pathsHolder;
      }
    }

    // Add new path to history.
    pathsHolder.add(newRoute);

    return pathsHolder;
  }

  void push(MainRoute path) {
    assert(path != null);
    _mainRoutes.add(path);
    notifyListeners();
  }

  void pop() {
    _mainRoutes.removeLast();
    notifyListeners();
  }
}

/// The RouteInformationParser takes the RouteInformation
/// from a RouteInformationProvider and parses it into a user-defined data type.
class MainRouteInformationParser extends RouteInformationParser<MainRoute> {
  @override
  Future<MainRoute> parseRouteInformation(
      RouteInformation routeInformation) async {
    final Uri uri = Uri.parse(routeInformation.location);
    return SynchronousFuture(MainRoute.parse(uri));
  }

  @override
  RouteInformation restoreRouteInformation(MainRoute path) {
    return RouteInformation(location: path.uri.path);
  }
}

class MainRoute {
  final String name;
  final Uri uri;
  final dynamic data;
  final Object state;

  const MainRoute(
      {@required this.name, @required this.uri, this.data, this.state});

  factory MainRoute.home() => MainRoute(name: 'home', uri: Uri.parse('/'));

  factory MainRoute.unknown() =>
      MainRoute(name: 'unknown', uri: Uri.parse('/unknown'));

  factory MainRoute.project() =>
      MainRoute(name: 'project', uri: Uri.parse('/project'));

  factory MainRoute.parse(Uri uri) {
    if (uri.pathSegments.isEmpty) {
      return MainRoute.home();
    }

    if (uri.pathSegments.length == 1) {
      if (uri.pathSegments[0] == 'project') {
        return MainRoute.project();
      }
    }

    return MainRoute.unknown();
  }

  @override
  bool operator ==(Object other) => other is MainRoute && other.uri == uri;

  @override
  int get hashCode => uri.hashCode;
}

class MainPageBuilder {
  final BuildContext context;
  final MainRoute homeRoutePath;

  MainPageBuilder(this.context, this.homeRoutePath);

  dynamic get page {
    switch (homeRoutePath.name) {
      case 'home':
        return MaterialPage(
          key: ValueKey('home'),
          name: homeRoutePath.name,
          child: HomePage(),
        );
      case 'project':
        return MaterialPage(
          key: ValueKey('projects'),
          name: homeRoutePath.name,
          child: ProjectsPage(),
        );
      default:
        return MaterialPage(
          key: ValueKey('unknown'),
          name: homeRoutePath.name,
          child: Scaffold(
            body: Container(
              width: double.infinity,
              height: double.infinity,
              color: Colors.black,
              alignment: Alignment.center,
              child:
                  Text('Unknown Page', style: TextStyle(color: Colors.white)),
            ),
          ),
        );
    }
  }
}

class HomePage extends StatelessWidget {
  const HomePage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        color: Colors.amber,
        alignment: Alignment.center,
        child: Column(
          children: [
            Text('Home Page', style: TextStyle(color: Colors.white)),
            ElevatedButton(
                onPressed: () {
                  (Router.of(context).routerDelegate as MainRouterDelegate)
                      .push(MainRoute.project());
                },
                child: Text('Open Projects')),
          ],
        ),
      ),
    );
  }
}

class ProjectsPage extends StatefulWidget {
  @override
  _ProjectsPageState createState() => _ProjectsPageState();
}

class _ProjectsPageState extends State<ProjectsPage> {
  bool canPop;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    canPop = (Router.of(context).routerDelegate as MainRouterDelegate).canPop;
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        color: Colors.pinkAccent,
        alignment: Alignment.center,
        child: Column(
          children: [
            Text('Projects Page', style: TextStyle(color: Colors.white)),
            Text('Can Pop: $canPop', style: TextStyle(color: Colors.white)),
            ElevatedButton(
                onPressed: () {
                  canPop = !canPop;
                  (Router.of(context).routerDelegate as MainRouterDelegate)
                          .canPop =
                      !(Router.of(context).routerDelegate as MainRouterDelegate)
                          .canPop;
                  setState(() {});
                },
                child: Text('Toggle Can Pop')),
            Padding(padding: EdgeInsets.only(bottom: 8)),
            ElevatedButton(
                onPressed: () =>
                    (Router.of(context).routerDelegate as MainRouterDelegate)
                        .pop(),
                child: Text('Back')),
            Padding(padding: EdgeInsets.only(bottom: 8)),
            ElevatedButton(
                onPressed: () =>
                    (Router.of(context).routerDelegate as MainRouterDelegate)
                        .push(MainRoute.home()),
                child: Text('Open Home')),
          ],
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @searchy2 
Thank you for the amazingly detailed explanation and code sample.
<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8f89f6505b (33 hours ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API
      29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome
      87.0.4280.88

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 63062a6443 (4 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API
      29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69
      darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome
      87.0.4280.88

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.26.0-2.0.pre.64 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9ff4326e1f (2 hours ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API
      29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69
      darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome
      87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Comment by chunhtai** [comment]
>There is no way to intercept browser navigation and "prevent" navigation. Browser forward and backward button both call didPushRoute and pass the information to the RouterDelegate's setNewRoutePath. Because of the underlying browser implementation of forward and backward buttons, I understand there is no way to capture if forward or backward is pressed. However, the issue is that Navigator 2 does not offer a way to override forward or backward navigation.

There are two things:

1. intercept browser navigation and capture if forward or backward is pressed
I don't think you can tell whether it is a forward or backward in html web as well? This is a native limitation.

2. "prevent" navigation
The only way I know is to use replace or push to change the browser history, and block the forward and have an illusion they go to a different page. I think this can be done once we have web plugin.


>There is no way to customize the browser history or programmatically navigate forward / backwards from Navigator 2.

We should support this somehow, ideally through a first party or third party plugin cc @mdebbar , do we have any plan on this?


>Showing a one-time onboarding flow. The user can always press back to navigate back to the onboarding flow because it cannot be removed from the browser history. Setting the onboarding flow to redirect to the homescreen after completion causes the browser and Navigator to no longer be synchronized. The URL shows 'onboarding' while the user is redirected to the 'home' page.

You can use Router.neglect to make router to NOT create a history entry

>Showing a login page. Page 1 -> Page 2 -> Login Page -> Successfully completed login, return to Page 2
The login page is now stuck in the back history. After the user logs in successfully, pressing back should not take the user back to the login page. Instead, it should take the user to Page 1.

Same as above, when your app is going to login page make sure to wrap the it with Router.neglect 

```dart
Router.neglect(context,(){
  // update state to go to login.
})
```

>Save use generated content / in progress work. Say the user is drawing a drawing. Pressing the browser navigation button should not cause them to lose their work. Instead, we can override the handle setNewRoutePath to prevent navigation and prompt the user to save their work whenever a browser navigation event occurs. However, if we do this, the browser is no longer in sync with the app state. While the user is still on the drawing page, the URL can change to the home page or any other page in the history stack.

This may need web plugin.

>Conditional flows where flow direction matters. A shopping cart flow would want to prevent backwards navigation to the shopping flow after the user completes checkout. A survey flow would want to prevent forward navigation if the user changes the previous answer and needs to be redirected to another question.

same as above

**Comment by searchy2** [comment]
Thank you for taking the time to answer and address each scenario.

**Comment by mdebbar** [comment]
> > There is no way to customize the browser history or programmatically navigate forward / backwards from Navigator 2.

> We should support this somehow, ideally through a first party or third party plugin cc @mdebbar , do we have any plan on this?

You can control the browser history calling web APIs using the [`dart:html`](https://api.dart.dev/stable/2.10.5/dart-html/dart-html-library.html) library. But before you do this, you should disable Flutter's own history manipulation, so you don't end up in a corrupt state.

To stop Flutter from doing any browser history manipulation, use the `flutter_web_plugins` as follows:

```dart
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() {
  // Call this before `runApp`.
  setUrlStrategy(null);
  runApp(...);
}
```
If your app supports other platforms, you can't directly import `flutter_web_plugins`. You have to use conditional imports. I created an example here showing how to do it: https://github.com/mdebbar/gallery/commit/48bbd93ba7863a68100e827ebf4687c952fe2d5e

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
