### ISSUE TITLE
webview_flutter Freezes when opening the keyboard on some android devices, 

### ISSUE THREAD

**Issue by Inshaf111** [flutter/flutter#72221]

**Comment by TahaTesser** [comment]
Hi @Inshaf111 
Which devices you're experiencing this issue Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
