### ISSUE TITLE
Not able to install flutter on linux mint 

### ISSUE THREAD

**Issue by cw0x413** [flutter/flutter#72227]
## Steps to Reproduce

1. Fresh install of linux mint 
2. clone repository and setup paths
3. stuck at `Building flutter tool.....`
## Logs
flutter --verbose not working stuck at `Building flutter tool...`

this is not working either

**Comment by iapicca** [comment]
@cw0x413  
can you provide your `flutter doctor -v` and your `flutter run -v`
did you install flutter through [snapcraft](https://snapcraft.io/flutter) or manually?

**Comment by cw0x413** [comment]
I installed it manually @iapicca 
and both of those commands dont work,
 takes too long for this `Building flutter tool...`

**Comment by cw0x413** [comment]
I cloned the dev branch with depth 1 if that helps

**Comment by iapicca** [comment]
@cw0x413 can you provide the info mentioned [above](https://github.com/flutter/flutter/issues/72227#issuecomment-743977511)

**Comment by cw0x413** [comment]
> and both of those commands dont work,
takes too long for this Building flutter tool...
![Screenshot from 2020-12-13 15-26-33](https://user-images.githubusercontent.com/72194129/102008568-9c613f00-3d57-11eb-9245-609cf7bd1ff1.png)
its been like this for half an hour

**Comment by cw0x413** [comment]
I installed ubuntu -_-

**Comment by iapicca** [comment]
@cw0x413 
I'm an ubuntu user myself
just follow these steps
1- get flutter and android studio
```console
sudo snap install flutter --classic
sudo snap install android-studio --classic
```
- 2 run android to install android sdk
- 3 copy paste the stuff below in your `~/bashrc`
```bash
export PATH="$PATH:/snap/bin/flutter/bin"
export PATH="$PATH:/snap/flutter/common/flutter"
export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
export ANDROID_SDK_ROOT=/home/francesco/Android/Sdk
```
- 4 run `flutter config --android-studio-dir=/snap/android-studio/current/android-studio`

and you should be good to go
