### ISSUE TITLE
[url_launcher] 6.0.0-nullsafety.1 missing web support

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#72239]
[`url_launcher: 6.0.0-nullsafety.1`](https://pub.dev/packages/url_launcher/versions/6.0.0-nullsafety.1) is missing web support (it just does not work on web, while the previous version does support web). This is intended, see below.

See [its `pubspec`](https://github.com/flutter/plugins/blob/34667d44cc1f8668e24058f02f823f119214e2ee/packages/url_launcher/url_launcher/pubspec.yaml#L37):

```yaml
  # TODO(mvanbeusekom): Temporary disabled until web is migrated to nnbd (advised by @blasten).
  #url_launcher_web: ^0.1.3
```

---

I just figured it would be good to **document** this because it was non-trivial to figure this out.

**Comment by creativecreatorormaybenot** [comment]
(It is not even indicated in the changelog - I think a big disclaimer should have been added to the README)

**Comment by Roshan13046** [comment]
I would like to work on this issue.

**Comment by Roshan13046** [comment]
> (It is not even indicated in the changelog - I think a big disclaimer should have been added to the README)

what disclaimer statement is expected according to you, please suggest?

**Comment by ditman** [comment]
There's another package that is going to start having this problem: google_sign_in (see [this comment](https://github.com/flutter/plugins/pull/3329#pullrequestreview-569482593)). I'll document the de-endorsement of web in both.

Thanks for raising this issue, and bringing it to my attention!

**Comment by ditman** [comment]
[`url_launcher: 6.0.0-nullsafety.7`](https://pub.dev/packages/url_launcher/versions/6.0.0-nullsafety.7/changelog#600-nullsafety7) has support for web again :)

**Comment by BlaineFredrickson** [comment]
#ditman

Thank you very much.  Enjoy using this very much.  You've done a great job!

Blaine
