### ISSUE TITLE
[cupertino_icos] Upgrade to 1.0.1+1 fails :requires SDK version >=2.12.0-0 <3.0.0

### ISSUE THREAD

**Issue by mrjohnr** [flutter/flutter#72231]
Hi,I'm using cupertino_icons: ^1.0.0
I've updated flutter:  lutter upgrade
When I try to upgrade cupertino_icons: ^1.0.1+1 got this error:

```
[my_project ] flutter pub get
Running "flutter pub get" in my_project ...                 
The current Dart SDK version is 2.10.4.

Because my_project depends on cupertino_icons >=1.0.1 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because my_project depends on cupertino_icons >=1.0.1 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
exit code 1
```

something is strange with the update,on stable channel I got Flutter 1.22.5+Dart 2.10 on master I got Flutter 1.20.4+Dart 2.12.. 
next you'll get results for flutter doctor -v, your flutter run -v, and pubspec.yaml
thanks

**flutter doctor -v**
[v] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at D:\_dev_\flutter\_sdk
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[v] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**flutter run -v**
[ +122 ms] executing: [D:\_dev_\flutter\_sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78910062997c3a836feee883712c241a5fd22983
[        ] executing: [D:\_dev_\flutter\_sdk/] git tag --points-at HEAD
[  +33 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[   +7 ms] executing: [D:\_dev_\flutter\_sdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\_dev_\flutter\_sdk/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [D:\_dev_\flutter\_sdk/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] List of devices attached
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +48 ms] No supported devices connected.
[  +11 ms] "flutter run" took 143ms.
[  +20 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:353:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[ +259 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**pubspec.yaml**

name: my_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  provider: ^4.3.2+3
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  spinner_input: ^0.1.2
  flutter_local_notifications: ^3.0.2
  flutter_downloader: ^1.5.2
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

**Comment by yash1200** [comment]
`cupertino_icons` version 1.0.1+1 supports null safety that is why it requires dart sdk version greater than `2.12.0-0`.

**Comment by mrjohnr** [comment]
same error with 1.0.1

**Comment by yash1200** [comment]
Oh yes, `1.0.1` also supports null safety. Stick to `1.0.0` or if you want to use the latest version then use dart sdk version `>=2.12.0-0 <3.0.0` in your app.

**Comment by mrjohnr** [comment]
tried,not working, running flutter update got Flutter 1.22.5+Dart 2.10  but not Dart 2.12

**Comment by yash1200** [comment]
Yes, thats because null safety is not on stable channel yet, I'd say stick to 1.0.0.

**Comment by TahaTesser** [comment]
hi @mrjohnr 
Yep, this is a null-safety supported version,  please use the non-null-safety version for now  in the stable  channel
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by deakjahn** [comment]
This doesn't fly. I have flutter_localizations as a dependency because I need it, this requires 0.17.0-nullsafety.2, the null-safe prerelease version, but if I switch to it, it no longer works with this error message. The dependencies seem to be stuck in a circle and you now created a situation with no exit. Fell between two stools.

**Comment by priyadarshu** [comment]
I am facing the same issue

Running "flutter pub get" in flutter_actions_test...            
The current Dart SDK version is 2.10.4.

Because page_view_example depends on cupertino_icons >=1.0.1 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
---- Log transcript ----

![github action error](https://user-images.githubusercontent.com/45838555/104191129-1cf08980-5443-11eb-85aa-f57113ff0010.PNG)

**Comment by haiderkhalil** [comment]
I have the same issue

**Comment by TahaTesser** [comment]
Please use `1.0.0 `

**Comment by deakjahn** [comment]
I'd be glad to. How can I update the SDK? :-) If I change the sdk to > 2.12 in the yaml, nothing happens, it just keeps complaining. Neither `pub update` nor `flutter update` seems to pull the new SDK.

**Comment by smasinde** [comment]
I had this issue as well. The stable branch of flutter uses Dart 2.10.. if you want to use the latest Dart version I had to change to the beta channel with the command `flutter channel beta` this updated the dart sdk. I don't think there is another way to update it and keep using the stable channel as the flutter sdk uses it's own internal dart sdk rather than the locally installed version

**Comment by deakjahn** [comment]
Then I would say it was a bit premature to release this on the stable channel, wasn't it? :-)

**Comment by chitgoks** [comment]
im using cupertino 1.0.2 and i get the same error.

**Comment by shadow-recruit** [comment]
Everyone who is on the `stable` channel of flutter will be facing this issue, as it currently supports Dart SDK version up to 2.10.5
![image](https://user-images.githubusercontent.com/47930146/107139550-f9393a00-6941-11eb-9327-18a6213877c5.png)
[Source](https://dart.dev/get-dart)

To view what channel you are on, run this command:
```
$ flutter channel
```
To change to a different channel (say `beta`):
```
$ flutter channel beta
```
After changing the channel, upgrade to the latest SDK using this command:
```
$ flutter upgrade
```
