### ISSUE TITLE
Invalid Signature. Code object is not signed at all. 

### ISSUE THREAD

**Issue by gokulchan** [flutter/flutter#72233]
## Steps to Reproduce

1. flutter clean
2. flutter build ios
3. Xcode: using Automatic signing
4. Xcode: Product -> scheme -> Runner
5. Xcode: Product -> Destination -> Any iOS device (arm64)
6. Xcode: Product -> Archive
7. Validate (with proper certificate and App Store distribution profile)
8. Validation fails

**Expected results:**  Validation Success

**Actual results:** 

Invalid Signature. Code object is not signed at all. The file at path [Runner.app/Frameworks/App.framework/flutter_assets/assets/js/lib/snippets/lang.js] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

Tried the suggestions from https://github.com/flutter/flutter/issues/71164, but the same result.

<details>

**Flutter Doctor result**

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H15, locale en-AU)
    • Flutter version 1.22.2 at /Users/gokulnk/DevTools/flutter
    • Framework revision 84f3d28555 (8 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gokulnk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
</details>

**Comment by gokulchan** [comment]
I solved the issue. The issue was with the contents in file "lang.js".

**Comment by jidasheng** [comment]
I ran into a similar problem. How did you solve it? Can you tell me more specifically? Thanks!
