### ISSUE TITLE
➕ Add a flag to obfuscate assets so they are only readable if some key is used

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#72235]
## Use case

Protecting assets that you don't want people taking but want in your app bundled.

## Proposal

Adding a flag to the build command which in turn obfuscates all assets with some random key chosen by the user and gets unlocked if used by the app not by someone who gets hold of the `.ipa` or `.apk` and unzips it.

**Comment by jonahwilliams** [comment]
I'm not sure why you'd want to encrypt assets: you'd still need to have the key locally to decode them, and then anyone with the app would still be able to un-encrypt them. The different platforms may already have some mechanism for storing secrets, you should prefer that.
