### ISSUE TITLE
Flutter should provide iOS typography constants

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7225]
They're documented:
http://ivomynttinen.com/blog/ios-design-guidelines

Would be nice if we provided such as part of some sort of ios package for those seeking to match OEM typography sizes.

**Comment by yjbanov** [comment]
This has come up again: https://groups.google.com/forum/#!topic/flutter-dev/RTK3RdrDco4

Here are the official Cupertino typography numbers: https://developer.apple.com/ios/human-interface-guidelines/visual-design/typography

**Comment by xster** [comment]
Merging into #18037. Will be done in the context of CupertinoTheme.
