### ISSUE TITLE
[in_app_purchase] 0.3.4+16 PurchaseDetails `pendingCompletePurchase` is always `true` on `PurchaseStatus.purchased`

### ISSUE THREAD

**Issue by bradsb** [flutter/flutter#72268]
## Steps to Reproduce

1. Run In_app_purchase example app.
2. Make a purchase and acknowledge it when it hits the listener.
3. Check `pendingCompletePurchase` before and after acknowledgement, such as when using `queryPastPurchases`

**Expected results:** 
On Android, if the purchase has been acknowledged (i.e. `PurchaseDetails().billingClientPurchase.isAcknowledged` is true), `pendingCompletePurchase` will be false.
On iOS, if the purchase is in the queue, then it has not been acknowledged according to the Apple docs, so it is fine here.

**Actual results:** 
On Android, `pendingCompletePurchase` is always true on `PurchaseStatus.purchased`.

You can see in the source code that it doesn't check whether the purchase is acknowledged.
https://github.com/flutter/plugins/blob/0b158bd73e9924a4c57c9b3cea0e450ba5533ce0/packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart#L139-L154
```dart
  /// The status that this [PurchaseDetails] is currently on.
  PurchaseStatus get status => _status;
  set status(PurchaseStatus status) {
    if (_platform == _kPlatformIOS) {
      if (status == PurchaseStatus.purchased ||
          status == PurchaseStatus.error) {
        _pendingCompletePurchase = true;
      }
    }
    if (_platform == _kPlatformAndroid) {
      if (status == PurchaseStatus.purchased) {
        _pendingCompletePurchase = true;
      }
    }
    _status = status;
  }
```
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-CZ)
    • Flutter version 1.22.4 at /Users/xxx/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • B40FB6A4-963B-4A78-AA03-74C1997B444B • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
hI @bradsb 
Can you please provide` and a complete reproducible minimal code sample, probably modified official example to show `pendingCompletePurchase` is always true as you stated?
Thank you

**Comment by bradsb** [comment]
Hi @TahaTesser. Modifying the [official example code's main.dart](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/example/lib/main.dart) to simply log the output of `queryPastPurchases.pastPurchases` after the purchase and acknowledgement of a non consumable should be enough to show that `pendingCompletePurchase` is true on `PurchaseStatus.purchased` regardless of whether `billingClientPurchase.isAcknowledged` is true or false. `pendingCompletePurchase` should only be true on Android (according to the docs), if `billingClientPurchase.isAcknowledged == false` and `status == PurchaseStatus.purchased`

The documentation comments say to call [InAppPurchaseConnection.completePurchase] if the pendingCompletePurchase is true.

The only places `pendingCompletePurchase` is set in the plugin are here:

Starts false:
https://github.com/flutter/plugins/blob/d3bbef885e57cd0a018e968a186e2b805f7dcfa4/packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart#L171-L177
```dart
  /// The developer has to call [InAppPurchaseConnection.completePurchase] if the value is `true`
  /// and the product has been delivered to the user.
  ///
  /// The initial value is `false`.
  /// * See also [InAppPurchaseConnection.completePurchase] for more details on completing purchases.
  bool get pendingCompletePurchase => _pendingCompletePurchase;
  bool _pendingCompletePurchase = false;
```

After a purchase it is true, even if you have already called `InAppPurchaseConnection.completePurchase` because it only checks the `PurchaseStatus`:
https://github.com/flutter/plugins/blob/d3bbef885e57cd0a018e968a186e2b805f7dcfa4/packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart#L139-L154
```dart
  /// The status that this [PurchaseDetails] is currently on.
  PurchaseStatus get status => _status;
  set status(PurchaseStatus status) {
    if (_platform == _kPlatformIOS) {
      if (status == PurchaseStatus.purchased ||
          status == PurchaseStatus.error) {
        _pendingCompletePurchase = true;
      }
    }
    if (_platform == _kPlatformAndroid) {
      if (status == PurchaseStatus.purchased) {
        _pendingCompletePurchase = true;
      }
    }
    _status = status;
  }
```

I will try to provide a modified version of the official example as soon as it's possible that logs this information. 

This can be worked around by checking the `billingClientPurchase.isAcknowledged` instead of `pendingCompletePurchase` in our apps, but it means the docs and functionality are misleading

Thanks for your time!

**Comment by TahaTesser** [comment]
Hi @bradsb 
Please do, thanks

> I will try to provide a modified version of the official example as soon as it's possible that logs this information.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
