### ISSUE TITLE
Unable to Update flutter

### ISSUE THREAD

**Issue by techmeav** [flutter/flutter#72266]
So, I was using a flutter command after a long time and then it automatically started to upgrade. After downloading the ZIP file via BITS, it just started to extract the file. And suddenly, the moment it extracted the `dart.exe` file, my antivirus K7 thought that it was suspicious and deleted it while flutter got an error.

**MY OS : WINDOWS**
**Command = `flutter run`**

what flutter executed:
`Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ae90085a8437c0ae94d6b5ad2741739ebc742cb4...
Unzipping Dart SDK...
Error: Unable to update Dart SDK. Retrying...`

Response from K& antivirus
![Screenshot (198)](https://user-images.githubusercontent.com/70526033/102076920-81153300-3e2e-11eb-8207-37d8cbf84b25.png)

file : `c:/src/flutter/bin/cache/dart0sdk/bin/dart.exe`

I hope someone would find a solution for this

**Comment by techmeav** [comment]
**EDIT**  I got it updated when flutter just switched to WebRequest for a while and then...

`Waiting for 0 seconds, press CTRL+C to quit ...                                                                         Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ae90085a8437c0ae94d6b5ad2741739ebc742cb4...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : The decryption operation failed, see inner exception.
At D:\src\flutter\bin\internal\update_dart_sdk.ps1:70 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Error: Unable to update Dart SDK. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ae90085a8437c0ae94d6b5ad2741739ebc742cb4...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...`

**It some how updated**

**But, is there any way to change BITS to WebRequest to save my developing time??**

**Comment by pedromassangocode** [comment]
Hi @techmeav 
Are you still facing this issue?

> But, is there any way to change BITS to WebRequest to save my developing time??

I don't think so, as you can see the tool already try to use both if one failed. Why do you think it is necessary to change BITS manually?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
