### ISSUE TITLE
When I exit a page use iOS touch, click to enter this page quickly, click is invalid on iOS.

### ISSUE THREAD

**Issue by jeryfer** [flutter/flutter#72263]
I found 600 milliseconds delay.

**Comment by pedromassangocode** [comment]
Hi @jeryfer 
Can you please provide your `flutter doctor -v`, the steps to reproduce the issue and a minimal complete reproducible code sample?
Thank you

**Comment by jeryfer** [comment]
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/jeryfer/flutter
    • Framework revision 7891006299 (4 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.beta.2

**Comment by jeryfer** [comment]
Exit page use iOS touch from left to right quickly, then click is invalid in 600 milliseconds.

**Comment by pedromassangocode** [comment]
Please provide what was asked in https://github.com/flutter/flutter/issues/72263#issuecomment-744444891.

**Comment by jeryfer** [comment]
There is no code. It's a matter of user experience. I found this problem in all versions.
 Did anyone else see the problem？

**Comment by jeryfer** [comment]
I guess that flutter unable to detect the time of iOS's own gesture exiting the page.

**Comment by jeryfer** [comment]
When the time is 100 milliseconds using iOS's own gesture exting the page, the interface has no response within about 400 milliseconds.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
