### ISSUE TITLE
Augment flutter build output to state null safety compilation mode

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#72279]
When a developer builds a Flutter app using null safety, they may temporarily opt one or more libraries out from the null safety enforcement using a Dart language version marker such as `@dart = 2.10`. As discussed in https://github.com/dart-lang/sdk/issues/44234, they may forget to remove this opt-out again, which leave their app in partial null safety. Thus it would be good to offer some additional output to the developer.

From a discussion in the Dart language team, we think this should *not* be shown during analysis, as that could easily get annoying (the developer opts out, and is then immediately hit with warning).

But, we still think it's worth adjusting the output of commands that build *release-mode* artifacts to state which form of null safety was used. Concretely we'd like to suggest we adjust the output of `flutter build`, so that when the SDK constraint is 2.12 or above, we add output like this:

```
$ flutter build apk
Compiling Dart code with sound|unsound null safety.
Running Gradle task 'assembleRelease'... Done                     113.6s
✓ Built build/app/outputs/flutter-apk/app-release.apk (15.4MB).
```

**Comment by mit-mit** [comment]
cc @zanderso

**Comment by zanderso** [comment]
@mit-mit Thoughts on how this is related to https://github.com/flutter/flutter/pull/70718 ?

**Comment by mit-mit** [comment]
Ah, that is awesome, so we already have the detection in place. If we could add similar output to `flutter build` that would be great!

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/73426
