### ISSUE TITLE
maxLength is not working in AlphaNumeric Characters.

### ISSUE THREAD

**Issue by RalphNoel** [flutter/flutter#72270]
@AlexV525  Hi, it's working fine in when i set KeyboardType is number, but maxLength is not working in AlphaNumeric Characters.

For Eg.

I tried to set a bank IFS Code(INDIA) in TextFormField, the maxLength is not working in this Condition..

_Originally posted by @RalphNoel in https://github.com/flutter/flutter/issues/67898#issuecomment-744415484_

**Comment by AlexV525** [comment]
Could you provider more info about your platform? Including `flutter doctor -v` and which platform you're using, which keyboard you're using.

**Comment by RalphNoel** [comment]
@AlexV525 
Flutter (Channel stable, 1.22.1, on macOS 11.0.1 20B50, locale en-GB)
    • Flutter version 1.22.1 
    • Framework revision f30b7f4db9 (10 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

Platform : Android
KeyboardType : TextInputType.text, In android Default Keyboard

**Comment by AlexV525** [comment]
Thanks for the info. The fix has landed on the master channel. It will be landed on next release of the stable version if I get it right. Before that please use master channel or use the workaround in the previous issue.

**Comment by RalphNoel** [comment]
@AlexV525
 Which channel is recommended for mobile app production, When you will release the next version, then i didn't expect this silly issue from the flutter.
