### ISSUE TITLE
Esperanto as a language in Flutter

### ISSUE THREAD

**Issue by ferranrego** [flutter/flutter#72284]
## Use case

We want to add the Esperanto language to our [Flutter-based application](https://gitlab.com/vocdoni/client-mobile). We already have the language strings ready but found out that Flutter does not enable this language by default.

## Proposal

We would like to have Esperanto compatibility in Flutter so we can add it as a language.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi! Just to clarify, did you mean that the Flutter widget libraries (material, cupertino, etc) currently do not support Esperanto (eo)? Or, are you having trouble with your own localized strings?

**Comment by shihaohong** [comment]
If it's the former, we tend to support the languages that Android officially supports, and `eo` is not on the list, so I don't think that `eo` will be officially supported by Flutter in the short term

**Comment by brickpop** [comment]
The point is that we have the strings, but the material widgets throw an error when the (unsupported) language is selected.

If some language is unsupported, would it be possible to at least bypass the error on the Material boundaries and use a fallback there? This would allow us to display our localized strings, even if the widget tooltips remain in English.

**Comment by shihaohong** [comment]
Thanks for the additional context, I created a separate issue for the fallback mechanism you described (see https://github.com/flutter/flutter/issues/72422) since we can keep this issue as a thread to see interest in supporting `es` officially.

**Comment by deakjahn** [comment]
@shihaohong See https://pub.dev/packages/l10n_esperanto.

Actually, the solution is viable for any other unsupported language, it's not specific to Esperanto. Just create your own and include it in the app delegate list.
