### ISSUE TITLE
`felt test chrome` presubmit timeouts.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#72288]
[This was reported ](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Web%20Engine/11792/overview)as a presubmit flake on [an unrelated pull-request](https://github.com/flutter/engine/pull/22470). From the logs, it is unclear where the job hung up.

**Comment by yjbanov** [comment]
This was fixed when @nturgut implemented sharding.
