### ISSUE TITLE
Our website doesn't have a way to publish news

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7229]
We'd like to publish news every once in awhile. We'd like to publish news with a Flutter branded site/page of some sort. Examples of news might be updates to our dev cycle, updates to our IntelliJ plugins, big new features, etc.

These would be items bigger than a tweet, and more timely/announcement than a pure document.

**Comment by Hixie** [comment]
From past experience one thing I'd be wary of with this is that you end up with pages that are stale. e.g. don't publish news for 2 months and now it looks like you've been out to lunch for 2 months.

**Comment by sethladd** [comment]
We don't necessarily want to set up a whole blog: not sure how often we'll publish, and not excited to manage yet another site.

Perhaps we can use flutter.io's existing infrastructure, and add a "/news" subdirectory.

**Comment by sethladd** [comment]
> don't publish news for 2 months and now it looks like you've been out to lunch for 2 months

Agreed. We need to ensure we can publish at some reasonable schedule.

An idea for a solution is to just email the mailing list whenever we have something to say.

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
> An idea for a solution is to just email the mailing list

How many subscribers are there of that list?

**Comment by sethladd** [comment]
361 members

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1835](https://github.com/flutter/website/issues/1835) via [**ZenHub**](https://www.zenhub.com/)
