### ISSUE TITLE
Better documentation of canUpdate, specifically covering the default null case

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7231]
From Gitter:

Me: might be worth spelling out the default case in canUpdate: https://www.crossdart.info/p/flutter/0.0.21/src/widgets/framework.dart.html#line-413

Adam Barth @abarth 19:07
So if you append or prepend, we'll find the matches
(Please file bugs with doc requests)
For the middle, unmatched section
We put all the nonnull keys in a hashmap
We we'll also always find matches for nonnull keys (if they exist)
the most common bug with how we have the defaults set is "overmatching"
e.g., if you have a bunch of widgets with the same runtimeType and null keys
and you think you're prepending something
the newly prepended widget will match up with the old widget at index 0
because they have the same type and the same (null) key
so any state associated with that widget will become associated with the newly prepended widget
(hence the animation bug that @Hixie was mentioning)
the solution is to add more keys
so that the widgets match up the way you expect

**Comment by Hixie** [comment]
Not really sure what you want here. I've added this to canUpdate:

```
  /// If the widgets have no key (their key is null), then they are considered a
  /// match if they have the same type, even if their children are completely
  /// different.
```

**Comment by Hixie** [comment]
Closed based on PR above. Reopen if you want more.
