### ISSUE TITLE
Refactor TRACE_EVENT* to be safer when nesting/allow specifying arguments at the end of a trace

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#72314]
The following code is not safe:

```cpp
{
  std::string count1 = std::to_string(container.size());
  TRACE_EVENT1("flutter", "Foo::Bar", "count", count1.c_str());
  // ...
  std::string count2 = std::to_string(container.size());
  TRACE_EVENT_INSTANT1("flutter", "Foo::Bar", "count", count2.c_str());
}
```

This gets processed into:
```cpp
{
  // via FlutterTimelineEvent for TRACE_EVENT1:
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0, Dart_Timeline_Event_Begin,
                       1, {"count"}, {count1.c_str()});

  // ...
  // via FlutterTimelineEvent for TRACE_EVENT_INSTANT1:
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0, Dart_Timeline_Event_Begin,
                       1, {"count"}, {count2.c_str()});

  // from the scoped end for TRACE_EVENT_INSTANT1
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0, Dart_Timeline_Event_End,
                       0, nullptr, nullptr);
  // from the scoped end for TRACE_EVENT1
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0, Dart_Timeline_Event_End,
                       0, nullptr, nullptr);
}
```

And can lead to crashes as reported in https://github.com/flutter/flutter/issues/72153

See e.g. https://github.com/flutter/engine/commit/4276c735adff6dd87ef26965d046502b2a824d8d

It's not clear to me whether this is a bug in Dart or WAI. If it's WAI, Dart should probably document this in dart_api.h. /cc @rmacnak-google @a-siva for input on that.

It might be nice to have the FML macros support adding arguments at the end, or otherwise come up with a way that supports both Fuchsia and Dart tracing to report multiple arguments for a synchronous trace.

**Comment by rmacnak-google** [comment]
Adjusting the example so it compiles,

```
TEST_CASE(XYZ) {
  TimelineStream* stream = Timeline::GetEmbedderStream()->set_enabled(true);

  std::string count1 = std::to_string(1);
  const char* names1[] = {"count"};
  const char* values1[] = {count1.c_str()};
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0,
                     Dart_Timeline_Event_Begin, 1, names1, values1);

  std::string count2 = std::to_string(2);
  const char* names2[] = {"count"};
  const char* values2[] = {count2.c_str()};
  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0,
                     Dart_Timeline_Event_Begin, 1, names2, values2);

  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0,
                     Dart_Timeline_Event_End, 0, nullptr, nullptr);

  Dart_TimelineEvent("Foo::Bar", Dart_TimelineGetMicros(), 0,
                     Dart_Timeline_Event_End, 0, nullptr, nullptr);
}
```
it runs without any crash. Why do think there's an issue here? There's nothing special about nesting events: the VM doesn't try to match events in any way. That only happens much later in Observatory or chrome://tracing. A crash here suggests some violation of the lifetime requirements of Dart_TimelineEvent, which AddressSanitizer should be able to narrow down.

**Comment by dnfield** [comment]
This example crashes flakily - I was able to reproduce it on a Pixel 4 running it every frame, but not on an iPhone 11 running the same code.

In the devicelab, it reproduced more frequently (perhaps because it ran on less powerful phones, and ran many more times).

**Comment by zanderso** [comment]
We must still have instances of this in the engine. There was a crash on the framework tree that I filed an issue for here https://github.com/flutter/flutter/issues/73409. Since this is still popping up every so often on the tree (which closes it) I am going to bump this to P3.

**Comment by dnfield** [comment]
Did these crashes start after the path volatility patch?

Perhaps I was wrong in my assessment - that it's not the nesting, but the fact that we were calling things twice or something in that loop made the crash doubly likely?

We could disable the tracing in there for now. Or, we could disable passing the argument(s) we're passing to avoid the string getting double freed.

**Comment by zanderso** [comment]
Reading the code, it looks like a double free can occur if recording a timeline event races with `Dart_Cleanup()`. Do you see any risk of that anywhere?

**Comment by dnfield** [comment]
@chinmaygarde or @jason-simmons might know - this sounds like a Dart VM lifecycle issue. We call `Dart_Cleanup` when the `DartVM` object is destructed.

It seems possible to me that this bug has existed for a while, and just never gotten triggered because we only used a `TRACE_EVENT0` or something with no arguments for Dart to cleanup.

That said, the events I added should only be happening if the animator is active, and we shut down the animator before the Dart VM.

Would it make sense to change the Dart API (or add new Dart API) that gives back the pointer to the caller when Dart is done with it, so the caller can clean it up? That would remove responsibility from Dart_Cleanup for taking care of it.

**Comment by zanderso** [comment]
@dnfield Okay, if we don't see how we could get to a double-free by inspecting the code, then if you're able to repro this, the right thing to do is an ASAN build as @rmacnak-google suggested. It looks like the engine `tools/gn` accepts an `--asan` flag, but @chinmaygarde can confirm if anything else is needed.

**Comment by dnfield** [comment]
I'm having trouble reproducing this locally now. I'll keep trying that. In the mean time, I'm wondering if the `Free` code is problematic if multiple threads get involved.

Specifically, the `buffer_` that gets `free`d and is causing the crash isn't guarded by a mutex. If mutliple threads end up trying to free it (e.g. because VM is shutting down at the same time another thread is finishing up a timeline event), just checking that it's null doesn't guarantee that it's safe to free. See https://github.com/dart-lang/sdk/blob/800ec511f52861cdaf5e8c5d40739a253e63880a/runtime/vm/timeline.cc#L379-L387

**Comment by dnfield** [comment]
This test fails in the Flutter repo currently:

```
TEST_F(DartState, TimelineAfterShutdown) {
  ASSERT_FALSE(DartVMRef::IsInstanceRunning());
  auto settings = CreateSettingsForFixture();
  auto vm_ref = DartVMRef::Create(settings);
  ASSERT_TRUE(vm_ref);
  auto vm_data = vm_ref.GetVMData();
  ASSERT_TRUE(vm_data);
  TaskRunners task_runners(GetCurrentTestName(),    //
                           GetCurrentTaskRunner(),  //
                           CreateNewThread(),       //
                           CreateNewThread(),       //
                           CreateNewThread()        //
  );
  auto isolate_configuration =
      IsolateConfiguration::InferFromSettings(settings);
  auto weak_isolate = DartIsolate::CreateRunningRootIsolate(
      vm_data->GetSettings(),              // settings
      vm_data->GetIsolateSnapshot(),       // isolate snapshot
      std::move(task_runners),             // task runners
      nullptr,                             // window
      {},                                  // snapshot delegate
      {},                                  // hint freed delegate
      {},                                  // io manager
      {},                                  // unref queue
      {},                                  // image decoder
      "main.dart",                         // advisory uri
      "main",                              // advisory entrypoint
      DartIsolate::Flags{},                // flags
      settings.isolate_create_callback,    // isolate create callback
      settings.isolate_shutdown_callback,  // isolate shutdown callback
      "main",                              // dart entrypoint
      std::nullopt,                        // dart entrypoint library
      std::move(isolate_configuration),    // isolate configuration
      nullptr                              // Volatile path tracker
  );
  auto root_isolate = weak_isolate.lock();
  ASSERT_TRUE(root_isolate);

  tonic::DartState* dart_state = root_isolate.get();
  ASSERT_FALSE(dart_state->IsShuttingDown());

  fml::AutoResetWaitableEvent latch;
  task_runners.GetRasterTaskRunner()->PostTask([&latch]() {
    TRACE_EVENT1("flutter", "test", "arg_name", "arg_val");
    latch.Wait();
    TRACE_EVENT1("flutter", "test2", "arg_name", "arg_val");
  });

  ASSERT_TRUE(root_isolate->Shutdown());

  ASSERT_TRUE(dart_state->IsShuttingDown());
  latch.Signal();
}
```

**Comment by dnfield** [comment]
Err might have spoken too soon, that test looks like it might be failing for other reasons. Investigating.

**Comment by zanderso** [comment]
@dnfield Did you get a chance to look into this more? Is this still a source of flakes, or can we remove the `team: flakes` tag?

**Comment by dnfield** [comment]
I'm going to just close this as no longer reproducible - I wasn't able to reproduce it locally again with any consistency, it's possible this was dealing with some other bug that got fixed and the nesting or not nesting of trace events was just enough to change some timing issue...
