### ISSUE TITLE
Replace usage of deprecated syscall in Fuchisa

### ISSUE THREAD

**Issue by jodysankey** [flutter/flutter#72321]
## Use case

`zircon.System` in flutter engine defines a [`clockGet`](https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/dart-pkg/zircon/lib/src/system.dart) function that uses the Fuchsia `zx_clock_get` syscall and the associated concept of a clock ID.

Per [RFC-0008](https://fuchsia.dev/fuchsia-src/contribute/governance/rfcs/0008_remove_zx_clock_get_and_adjust) this syscall and the concept of a clock ID are deprecated in Fuchsia and I'm working through the long process of removing dependencies, including Flutter.

## Proposal

Thankfully this function is not heavily used and all the invocations I can find are for monotonic time. Therefore, as documented in [fxbug.dev/66266](https://fxbug.dev/66266) I'm recommending the following:

1. Add a new `clockGetMonotonic` operation in `zircon.System`.
2. Wait for that to roll into fuchsia and other repos
3. Move all the call sites from `zircon.System.clockGet(_zxClockMonotonic)` to `zircon.System.clockGetMonotonic()`
4. Mark the `clockGet` function deprecated upstream (and maybe have it return an exception instead of attempting the syscall so we unblock the removal of the syscall?)
5. Wait some more
6. Remove `zircon.System.clockGet` entirely

**Comment by chinmaygarde** [comment]
Looks like this was fixed in https://github.com/flutter/engine/pull/23128. cc @arbreng

**Comment by jodysankey** [comment]
Actually its only step one that's been completed so far. I still need to wait for that to roll downstream before deprecating and then removing the original function that uses the syscall we're removing. Can we leave the bug open to track the remaining steps.

**Comment by jonahwilliams** [comment]
Hopefully this is fixed now
