### ISSUE TITLE
Flutter don´t start

### ISSUE THREAD

**Issue by AGTolosa** [flutter/flutter#72327]
## Steps to Reproduce

I try to use Flutter, but always closes after I enter any command. The only return that I get it´s that:

after this message, the console closes
![Image1](https://user-images.githubusercontent.com/75871879/102161449-5a1e2780-3e55-11eb-9392-6a35f99de795.jpg)

flutter_console.bat to
![Image2](https://user-images.githubusercontent.com/75871879/102161454-5db1ae80-3e55-11eb-81fa-d598c1b35704.jpg)

Flutter version --> 1.22.5

Windows --> 8.1

path --> C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python38\Scripts;C:\Program Files\Python38;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs;C:\Users\AGT\AppData\Local\Android\Sdk\tools;C:\Users\AGT\AppData\Local\Android\Sdk\tools\bin;C:\Users\AGT\AppData\Local\Android\Sdk\platform-tools;C:\ant\apache-ant-1.9.15;C:\Users\AGT\AppData\Local\Android\Sdk\tools;C:\Users\AGT\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\Java\jdk1.8.0_271;C:\Gradle\bin;C:\src\flutter\bin;C:\Program Files\Git\cmd;C:\Windows\System32;C:\Program Files\Git\cmd\git.exe

## Logs

```
```

```
```

**Comment by pedromassangocode** [comment]
Hi @AGTolosa 
Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by hello-addweb** [comment]
Please set path in environment variable : https://flutter.dev/docs/get-started/install/windows
And after that restart your terminal and check flutter command.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
