### ISSUE TITLE
[Feature request] Stop pointer events propagation

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#72337]
## Use case

I have a vetrical `ListView` with some items, I want to vertically drag some items (i.e a map view) and stop list view to scrolling

## Proposal

I need a widget that wrap item, it stop pointer events propagation for parents but allows for children, that means if we have a onVerticalDrag on parents, it no invoked but for chidden invoked

**Comment by jiangkang** [comment]
has the problem been solved？

**Comment by Piinks** [comment]
@sm2017 this should be possible from what I understand by adding a gesture detector. Can you provide sample code of your use case?

**Comment by sm2017** [comment]
I am not able to provide sample code right now, as I am not working in flutter projects and have no flutter in my local machine.

See https://github.com/fleaflet/flutter_map/issues/253

Consider that we have a third party library, and a widgets interact with scroll, if we put the widget in a list view as a child, the list view get the scroll event not the child. In some cases we need to prevent parent scrolling.

For example, we have a contact us page, with a lot of scrollable information and an interactive small map in the scrollable area

**Comment by Piinks** [comment]
Unfortunately we cannot debug third party packages or plugins. This issue tracker is for issues that exist in the Flutter framework. If you can provide a reproduction of your issue without any packages or plugins, we can take a look and see if there is an issue. 

From what I can tell this is already possible, see some simple example code below:


https://user-images.githubusercontent.com/16964204/174343446-317c7eab-8dfb-4c14-a667-ef4ecd11101a.mov


```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      home: SomeWidget(),
      // By default on desktop, PointerDeviceKind.mouse
      // cannot drag scrollables.
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: PointerDeviceKind.values.toSet(),
      )
    );
}

class SomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Nested drag gestures')),
        body: ListView.builder(
          itemBuilder: (context, outerIndex) {
            if (outerIndex == 10) {
              return SizedBox(
                height: 150,
                child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: 30,
                  itemBuilder: (context, innerIndex) {
                    return SizedBox(
                      height: 50,
                      child: Row(
                        children: [
                          const SizedBox.square(dimension: 25),
                          Text('Inner list, index $innerIndex')
                        ],
                      )
                    );
                  },
                ),
              );
            }
            return Text('Outer list, index $outerIndex');
          }
        )
      );
}
```

We will need more information to understand your request.
