### ISSUE TITLE
expose properties for set duration enter/exit of `showBottomSheet/showModalBottomSheet`

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#72346]
## Use case

I want to show bottomSheet with custom duration of enter/exit action

## Proposal

expose some properties for config this duration/animation

**Comment by ZainUrRehmanKhan** [comment]
Pull request created.

**Comment by Piinks** [comment]
You can provide an AnimationController to the BottomSheet.animationController to configure however you like, is that not sufficient?

**Comment by tbm98** [comment]
> You can provide an AnimationController to the BottomSheet.animationController to configure however you like, is that not sufficient?
Hi, @Piinks
How can I provide an AnimationController to BottomSheet?
I was tried but not found any way to do

**Comment by tbm98** [comment]
I just saw it. But if I don't use BottomSheet, is there any way I can pass AnimationController?

**Comment by ZainUrRehmanKhan** [comment]
This should be closed now.

**Comment by tbm98** [comment]
Thank you for your PR @ZainUrRehmanKhan
