### ISSUE TITLE
Pass BuildContext to TextEditingController.buildTextSpan

### ISSUE THREAD

**Issue by Jjagg** [flutter/flutter#72343]
## Use case

I'm building a rich text editor by overriding `TextEditingController.buildTextSpan` in a `SpannedTextEditingController`. Users can apply `TextAttribute` to parts of the text managed by the controller (the controller maintains the active attributes as well).

*The following explanation is slightly simplified*

These attributes currently have a `TextStyle` that is applied to the `TextSpans` created in `TextEditingController.buildTextSpan`:

```
class TextAttribute {
  TextStyle get style;
}
```

However, I would like for the attributes to be themeable. E.g. a 'Header' attribute should not have a fixed size. They'd have a `resolve` method that takes a `BuildContext` - so they can use `InheritedWidgets` - and returns the actual `TextStyle`:

```
class TextAttribute {
  TextStyle resolve(BuildContext context);
}
```

Of course now I need access to the wrapping `BuildContext` in `buildTextSpan`.

### Alternatives

The `SpannedTextEditingController` could hold theming data itself (for example with an `AttributeTheme` field). I do not think this is a great solution because:

1. The responsibility of retrieving the theme is placed outside the `SpannedTextEditingController`.
1. It does not match with the way themes are used in flutter. Themes are not stored for later use, instead they are depended on and used immediately.
1. The theme would need to be depended upon (`AttributeTheme.of`) where the controller is created, which is not necessarily close to the widget that displays the text. This would most likely be a source of confusion and error as theming beneath the context that the controller was created in is not applied.

## Proposal

Add a `BuildContext` parameter to `TextEditingController.buildTextSpan` and pass the build context in [`EditableTextState.build`](https://github.com/flutter/flutter/blob/58081821ab8f0f56a1e4c21da61203fcd0ef2f13/packages/flutter/lib/src/widgets/editable_text.dart#L2602).

This would be a breaking change for inheritors and users of the API (because the parameter would be `required`).

Design doc: https://docs.google.com/document/d/1nr-g45gXcWTYoW9UmChZV7Ije3lKP4pEvDQCdz6NFdI/edit?usp=sharing

**Comment by pedromassangocode** [comment]
My input:
I think your  current text style property can be merged with a new text style from Theme:

```
    final myTextStyle = TextStyle();
    final newTextStyle = myTextStyle.merge(
        Theme.of(context).textTheme.bodyText1
    );
```

And then provide the `newTextStyle` to the `TextEditingController.buildTextSpan` method. Does that works?

**Comment by Jjagg** [comment]
Thank you for the quick response! :) 

I wouldn't pass `TextStyle` to the controller, because the controller itself is agnostic towards which attributes it can apply.
Instead I'd have a custom theme class that has a `Map` that attributes can use to retrieve theming data (based on some naming convention, e.g. BoldAttribute would use attributeTheme['bold_weight'] to store its `FontWeight`).

Passing this theming data to the constructor of my custom controller is how I would do it in the alternative discussed in my initial post. It has a few downsides that I would like to not have.

I depend on `buildTextSpan` being called by `EditableText` so I cannot customize what parameters are passed in my code.

**Comment by justinmc** [comment]
Reopening since https://github.com/flutter/flutter/pull/72344 was reverted.  Will be fixed again in https://github.com/flutter/flutter/pull/73510.
