### ISSUE TITLE
image_picker cause CacheNetworkImage not showing android release mode

### ISSUE THREAD

**Issue by vukhacbiet** [flutter/flutter#72350]
My Flutter app was everything fine until I installed image_picker today.

I have followed the instructions:
- Add user permission INTERNET
- Add android:requestLegacyExternalStorage="true"

But my application not show any picture from internet (use widget CacheNetworkImage), I tried to remove image_picker package and everything work fine again.

My doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@vukhacbiet
Please provide a complete reproducible code sample along with `pubspec.yaml` and device details on which you are seeing the issue.

**Comment by hello-addweb** [comment]
The solution in my case was to run flutter run --release (with the device connected) and the image picker worked fine. The app is automatically installed on your device but you can find the working apk usually there build\app\outputs\apk\release\app-release.apk (the console will print the path).

Thanks to the comment above for the hint.

**Comment by vukhacbiet** [comment]
In my case, I changed Gradle build from 4.1.1 to 3.5.0 and everything work normally, seem Android Studio changed Gradle build version of my project
