### ISSUE TITLE
Please move linux bots to prod

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#72369]
This requires several steps:

- [x] Copy bot config files from staging versions to prod
- [x] Move the bot names to the prod pool using the new bot configurations.
- [x] Update the server in the salt configurations and reboot the machines
- [x] Remove the keys from staging salt master
- [x] Add the keys to the prod salt master.

**Comment by yusufm** [comment]
Completed migration of linux-{1,2,3,4,7} to prod salt master.
