### ISSUE TITLE
path_provider depends on path_provider_windows that depends on an old ffi

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#72371]
I have a null-safe flutter app that uses these packages:
```
  sqlite3: 0.1.9-nullsafety.0
  path_provider:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/path_provider/path_provider
```

These don't play well together, because of a dependency on different versions of ffi:

```
Because sqlite3 >=0.1.9-nullsafety.0 depends on ffi ^0.2.0-nullsafety and every version of path_provider_windows depends on ffi ^0.1.3, sqlite3 >=0.1.9-nullsafety.0 is incompatible with path_provider_windows.

And because every version of path_provider from git depends on path_provider_windows ^0.0.4, sqlite3 >=0.1.9-nullsafety.0 is incompatible with path_provider from git.

So, because your app depends on both path_provider from git and sqlite3 ^0.1.9-nullsafety.0, version solving failed.
pub get failed (1; So, because your app depends on both path_provider from git and sqlite3 ^0.1.9-nullsafety.0, version solving failed.)
```

I wonder what would be involved in getting path_provider_windows to use ffi 0.2.0-nullsafety?

But note that the dependency isn't actually something my app cares about. The package path_provider depends on path_provider_windows, which then depends on various things that aren't relevant for my app. (My app is for Android and iOS only.)

Other than forking the package, I can't see a way to say "don't worry about the Windows dependency".

If this is a general pattern for packages with platform-specific implementations, I'm concerned that this will make package version resolution unnecessarily brittle.

@mehmetf, you seem to be looking into this kind of thing at the moment, so I hope you don't mind me mentioning you here.

**Comment by pedromassangocode** [comment]
Hi @SteveAlexander 
Please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please comment and I will reopen it.
Thank you
