### ISSUE TITLE
Consider throwToolExit when archive extraction fails

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#72386]
The code here:

https://github.com/flutter/flutter/blob/34d4c7fe018f74c63e60b9f442fec6973c48caca/packages/flutter_tools/lib/src/cache.dart#L1794

`rethrows` an exception if the last download/extract retry fails. Instead we should consider it a network failure since the bits are likely corrupt, and throw a ToolExit as in the case above:

https://github.com/flutter/flutter/blob/34d4c7fe018f74c63e60b9f442fec6973c48caca/packages/flutter_tools/lib/src/cache.dart#L1764

/cc @jonahwilliams who was working in this area recently.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/74259
