### ISSUE TITLE
State Error from DDS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#72385]
https://github.com/flutter/flutter/pull/70847 introduced a crasher in the tool. This is currently the most frequent crasher on dev, and will shortly be the most frequent crasher in the beta going out this week, which will take the tool above our upper threshold for crash rate.

```
Thread 0 main threadStateError: Bad state: No element
  | at ListMixin.firstWhere | (list.dart:167)
  | at DartDevelopmentService.startDartDevelopmentService | (dds.dart:63)
  | at <asynchronous gap> | (async)
  | at FlutterDevice.connect.<anonymous closure> | (resident_runner.dart:249)
  | at <asynchronous gap> | (async)
```

**Comment by Hixie** [comment]
Update from @bkonyi: _I've been investigating without much luck. Still unable to reproduce and lacking enough runtime details to know which direction to search in. Seems to happen on all platforms, physical/simulator devices, with/without IDEs, for both run and attach. We've included an error message with a link to the issue above with hopes that users encountering the error might report with additional details, but we haven't had any follow ups._

**Comment by zanderso** [comment]
I think we've tracked down the majority of these. I'll open a new issue if something comes up again.
