### ISSUE TITLE
Run hot reload benchmark on iOS, iOS simulator, Android emulator

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#7238]
The flutter hot reload / restart benchmark is currently only being run against Android devices.

@yjbanov I would like it to run on iOS devices, and simulators for both platforms.

The benchmark code is not platform-specific at all so this is more an issue for the infrastructure.

@eseidelGoogle This will have the added benefit of acting as an integration test that might have caught the repeated [breaking](https://github.com/flutter/flutter/issues/7233) of iOS hot reload support.

**Comment by johnmccutchan** [comment]
@sethladd FYI

**Comment by johnmccutchan** [comment]
Also:

We now have separate numbers for the three stages of a hot reload: devFS syncing, VM reloading, and Flutter reassemble. We should display these on the status board.

**Comment by yjbanov** [comment]
Sounds good. Is the data in the `hot_benchmark.json` file?

**Comment by johnmccutchan** [comment]
@yjbanov Yes. the keys are:

```
hotReloadDevFSSyncMilliseconds
hotReloadFlutterReassembleMilliseconds
hotReloadVMReloadMilliseconds
```

**Comment by johnmccutchan** [comment]
*ping*

**Comment by johnmccutchan** [comment]
I'm still waiting for the more fine grained benchmark numbers to be published as well as enabling the benchmark on more configurations.

**Comment by yjbanov** [comment]
Thanks for the ping! https://github.com/flutter/flutter/pull/7602

**Comment by Hixie** [comment]
@johnmccutchan What is missing now?
