### ISSUE TITLE
Adjust devicelab linux luci expiration_timeout when running stable in prod.

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#72383]
During migration of devicelab linux tasks to LUCI, we have limited number of bots in prod. When everything is stable, and all bots finish migrating, we need to adjust the expiration_timeout value.

Currently the value is set to 12 hours.

**Comment by godofredoc** [comment]
Can we close this one?

**Comment by keyonghan** [comment]
Not yet. This PR https://github.com/flutter/infra/pull/322 updated the execution_timeout rather than the expiration_timeout. I will look through the queue time and then adjust the number.
