### ISSUE TITLE
Cirrus build_and_test_linux_unopt_debug frequently timing out, blocking rolls

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#72391]
Example: https://cirrus-ci.com/task/5104108984074240

**Comment by keyonghan** [comment]
Checked a couple of failed runs, all are almost running to the end, but hit the timeout default value 60 mins. Didn't see any potential errors in the log.
Does extending the timeout to like 90 mins make sense to you? @zanderso

**Comment by godofredoc** [comment]
The fix for this problem is to migrate it to LUCI. We'll need to create a new recipe as it is using both engine and sdk repos.

**Comment by zanderso** [comment]
My understanding was that we were leaving some presubmit tests running on Cirrus so that they could be run on PRs from non-Googlers.

**Comment by godofredoc** [comment]
Yeah we need to sync up on which ones we would like to keep running on Cirrus for the engine. Added to my notes to discuss it as part of the 2021 planning.

**Comment by keyonghan** [comment]
Moving out of ticket queue.

**Comment by godofredoc** [comment]
Moving as P3 as this depends on external infrastructure and it requires some planning work to define which subset of tests will be running on cirrus for the engine.

**Comment by mdebbar** [comment]
This has been failing a lot lately. Is there a short term solution to reduce the failures?

* https://cirrus-ci.com/task/6426402732900352
* https://cirrus-ci.com/task/6671537722884096
* https://cirrus-ci.com/task/5612161155203072

**Comment by godofredoc** [comment]
@mdebbar those three links are test errors failing with exit code 6. 

@zanderso the original error on this bug is also a test problem.

I think we need additional logs on these tests to identify the real problem.

**Comment by zanderso** [comment]
Timeout of `ShellTest.DiscardLayerTreeOnResize` is here https://github.com/flutter/flutter/issues/74875

Timeout of `ShellTest.SkipAndSubmitFrame` is here https://github.com/flutter/flutter/issues/78071

**Comment by dnfield** [comment]
This does not block rolls anymor because the bot ignores cirrus tasks.  I have filed a separate bug for this on https://github.com/flutter/flutter/issues/82045

The most common reason this shard times out is that it's trying to run _all_ of the framework tests. 

IMO, this shard is currently worthless and should be deleted. It is completely ignored by the landing bot, and it routinely fails. It is very low signal and also gets ignored by reviewers.

If we do not want to delete it, we should make sure it at least can pass in an hour. We could do this by:

- Build host_debug_unopt (~10 minutes)
- test host_debug_unopt (~10 minutes)
- Clone the framework (~2 minutes)
- Analyze the framework (~2 minutes?)
- Run a small well defined number of tests on the framework that can complete in a couple minutes.

Right now, this shard runs more tests every time the framework team adds more tests. When we first created it, it probably ran 4000 tests; it now runs over 8000.

We haven't deleted this yet because it's not done on LUCI at all, but right now it's in a completely unusable state.

**Comment by dnfield** [comment]
Another reason to delete this is that once we have separated out build and test, we will be in a better position to actually simulate an engine roll earlier on (e.g. in a presubmit on the engine) than we currently are.

**Comment by godofredoc** [comment]
+1 on migrating this specific test to LUCI but we may also want to start defining a small subset of smoke tests to identify when a given engine PR is ready for review.

**Comment by dnfield** [comment]
YEs - and those need to be held to the same standards that we hold all our tests to in terms of reliability.

**Comment by chinmaygarde** [comment]
[Another instance of the failure](https://github.com/flutter/engine/pull/26083/checks?check_run_id=2589814511) from reported presubmit runs is here.

**Comment by chinmaygarde** [comment]
Given that the signal to noise ratio is so poor that even the bots ignoring these results, it's harsh to force this experience on pull request authors who have limited context to reason about these failures. We should disable this step ASAP. @zanderso mentioned that moving a subset of the test to LUCI is desirable. However, I think that can be tracked as a separate work item. Zach, do you have a strong opinion about the order in which to go about alleviating this issue?

**Comment by godofredoc** [comment]
I'm moving that task to LUCI today but taking a closer look at where the failures are we will probably still get the timeouts and failures in LUCI.

Most of the issues described in this bug seem more like test related rather than infrastructure.

**Comment by dnfield** [comment]
At the risk of sounding like a broke record, we should delete the task until we figure out a better/more meaningful way to test what it's testing. We can't expect to run all the framework tests in a single shard.

**Comment by zanderso** [comment]
Sure, if @godofredoc has the shift to LUCI in-progress, we can eagerly disable it on Cirrus if the consensus is that it is too painful.

**Comment by dnfield** [comment]
This test has been deleted from Cirrus - I think we can close this, unless @godofredoc wants to use it for context in tracking any issues with th emigration.

**Comment by godofredoc** [comment]
Let's keep it open until we land the recipe changes.

**Comment by chinmaygarde** [comment]
I believe this one is done.
