### ISSUE TITLE
Provide some method to run an application with verbose_gc

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#72396]
The Dart VM `verbose_gc` flag causes the VM to print additional details about why and when it's doing a GC. This is generally helpful for VM developers, and occasionally helpful for engine developers or especially motivated application developers.

We should make it possible (although not necessarily easy) for developers to turn this flag on to better understand the behavior of the GC in their application.

This should _not_ be exposed in any machine readable way - it is not meant for testing and not expected to be stable, but may help when examining tricky memory related issues.

**Comment by jonahwilliams** [comment]
Can't this be passed through with the existing --dart-flags option?

**Comment by dnfield** [comment]
We'd have to add it to the allow list in that case, but I think that's a reasonable thing to do.

**Comment by dnfield** [comment]
We should just look to the GC stream in the timeline instead of this.
