### ISSUE TITLE
There are no callbacks when SoundTrack:s complete

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#724]
There is no callback when a SoundTrack has finished playing.

API here: https://github.com/vlidholt/sky_engine/blob/master/skysprites/lib/src/sound.dart

**Comment by eseidelGoogle** [comment]
I believe @jason-simmons fixed this.  I'm not aware of any sound issues for the game?

**Comment by sethladd** [comment]
Closing. Please reopen if we need to.
