### ISSUE TITLE
No implementation found for method share on channel plugins.flutter.io/share

### ISSUE THREAD

**Issue by AkshayDilod** [flutter/flutter#72436]
ListTile(
          leading: Icon(
            Icons.share,
            color: JdColor.primary,
          ),
          title: Text('Share App'),
          onTap: () async {
            await Share.share(
                'https://play.google.com/store/apps/details?id=com.tencent.ig&hl=en');
          },
        ),
![share](https://user-images.githubusercontent.com/29436937/102196579-19baba00-3ee6-11eb-8fd9-bc7069cd2a74.PNG)

![flutter](https://user-images.githubusercontent.com/29436937/102499233-eff9c280-40a0-11eb-9201-2f6af7abb2b0.PNG)

working fine in debug mode but show above errors in release mode and share window not showing.

**Comment by darshankawar** [comment]
@AkshayDilod 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.

**Comment by AkshayDilod** [comment]
![flutter](https://user-images.githubusercontent.com/29436937/102583857-66430700-412b-11eb-84fe-98a4da1b5e14.PNG)

**Comment by darshankawar** [comment]
@AkshayDilod 
We'll also need a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing.

**Comment by AkshayDilod** [comment]
It happens due to the share package version not compatible with the Gradle version.
