### ISSUE TITLE
[pigeon] when a return type is stream should use eventchannel

### ISSUE THREAD

**Issue by ammaratef45** [flutter/flutter#72440]
I was exploring pigeon to see if it would be useful for my projects, I tried adding a stream as a return type but the generated code is still using `BasicMessageChannel` and I suppose it should be using `EventChannel` or whatever is necessary to support having a stream from the native code

**Comment by darshankawar** [comment]
@ammaratef45 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/66711
Please follow-up there for updates.
Closing this as duplicate.
