### ISSUE TITLE
Crash Report - Galaxy A5 (a5lte)

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7244]
Android 6.0
Galaxy A5 (a5lte) 

## Logs

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a5lteub/a5lte:6.0.1/MMB29M/A500MUBU1CPJ3:user/release-keys'
Revision: '10'
ABI: 'arm'
pid: 23051, tid: 23080, name: Thread-13491  >>> harpsoft.bendometer.ui.android <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
    r0 b8f28ad0  r1 9cd72388  r2 9cd72354  r3 9cd72350
    r4 b8f04600  r5 9cd72388  r6 00000000  r7 00000000
    r8 00000000  r9 b90ecd00  sl 12c1e0c0  fp 12d715e0
    ip b8efa674  sp 9cd72348  lr a11f1559  pc a120c46e  cpsr 800e0030

backtrace:
    #00 pc 0009146e  /data/app/harpsoft.bendometer.ui.android-2/lib/arm/libsky_shell.so
    #01 pc 00058a01  /data/app/harpsoft.bendometer.ui.android-2/lib/arm/libsky_shell.so
    #02 pc 000588d5  /data/app/harpsoft.bendometer.ui.android-2/lib/arm/libsky_shell.so
    #03 pc 00415f5b  /data/app/harpsoft.bendometer.ui.android-2/oat/arm/base.odex (offset 0x322000)

**Comment by chinmaygarde** [comment]
A bit more information would help.
- Does this happen on all build variants? (debug, profile, release)
- Is it reproducible? Is it possible to get a reduced test case?
- Is it device specific? For example, can you check on the iOS simulator if you are on a mac.

**Comment by jtrunick** [comment]
I realized i was on a older engine (about 4wks old). Upgraded to latest and see if there is another crash report.

**Comment by eseidelGoogle** [comment]
If we know what version of the engine this was (or we can figure it out from the version of flutter/flutter) I'm happy to help you symbolicate this stack.  I suspect it is one we fixed last week.

**Comment by Hixie** [comment]
This is not actionable in its current state. Please file a new bug if you are still seeing this. Sorry we didn't respond sooner.
