### ISSUE TITLE
Does FlutterEngine support JavaFX embedded operation?

### ISSUE THREAD

**Issue by Dukro** [flutter/flutter#72444]
## Use case
1.Use existing Android Flutter Engine to port and run to JavaFX Desktop application development

## Proposal

FlutterEngine support JavaFX embedded operation

**Comment by darshankawar** [comment]
Don't see any reference or dup issues for this. So labeling it as proposal for further analysis.

**Comment by jonahwilliams** [comment]
We don't plan to offer guidance for embedding in JavaFX
