### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle__benchmark hotReloadInitialDevFSSyncAfterRelaunchMilliseconds regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#72449]
https://flutter-flutter-perf.skia.org/e/?begin=1607714715&end=1608103683&keys=X4a4e3c57b71c45caf7d762fcf76c8434&requestType=0&xbaroffset=22861

Looks like maybe https://github.com/flutter/flutter/pull/71899, and may be expected. @xster can you comment and close if appropriate?

Thanks!

**Comment by xster** [comment]
Duping into https://github.com/flutter/flutter/issues/72435
