### ISSUE TITLE
complex_layout_android__scroll_smoothness janky_count_without_resampler_90Hz regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#72450]
https://flutter-flutter-perf.skia.org/e/?begin=1607554083&end=1608103683&keys=Xc2eaf57d02cf27a8d1b3c685eedca205&requestType=0&xbaroffset=22849

Looks like maybe https://github.com/flutter/flutter/pull/69428 or https://github.com/flutter/flutter/pull/72357. I'm betting on the engine roll. 

/cc @zanderso this week's engine sheriff.

**Comment by zanderso** [comment]
I will attempt a bisect

**Comment by zanderso** [comment]
I have not been able to reproduce the 10% regression on a Nexus 5x.

At several revisions I ran a few times and took the average:

At https://github.com/flutter/flutter/commit/617c57bc95a8400e217e97f8ce8b5b849619cb02: 456
At https://github.com/flutter/flutter/commit/f37969638dc9d61c0f26ce16cefe9f92104884c9: 462
At https://github.com/flutter/flutter/commit/12232294c1c6ba0a87741ca5b4a1a27f5500eb70: 461
At https://github.com/flutter/flutter/commit/7d2e3a185967929c6a4ed21cfa57fda3ac0a3cde: 449
At https://github.com/flutter/flutter/commit/e74712c4d6ff25ecdbadbc89534b0a606352f959: 444
At https://github.com/flutter/flutter/commit/38852baf0079a94fa67e6662cb8d64c41b716dba (HEAD): 450

In Skia perf, we are missing data for a number of commits. I think we should wait for the numbers to fill in, and then re-evaluate this. Leaving at P0 but removing my assignment, as this may need investigation using the same device as in the devicelab.

Also /cc @liyuqian and @CareF who might know more about this specific benchmark.

**Comment by CareF** [comment]
This metric is designed to compare with `janky_count_with_resampler_90Hz` to show that a touch screen input resampler does make the scrolling smoother. The number represents the number of frames that look janky but is **not** because of lost of a frame (see #19222). Increase of this number may be a result of better performance if the more counts come from which previously considered a lost frame. Generally speaking I don't think increase of this number itself represents any issue.

**Comment by zanderso** [comment]
@CareF Would you be willing to add documentation to https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test/measure_scroll_smoothness.dart or someplace better to help folks interpret the 'janky_....' numbers?

**Comment by zanderso** [comment]
Dropping to a P4 documentation issue based on this discussion.

**Comment by CareF** [comment]
> @CareF Would you be willing to add documentation to https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test/measure_scroll_smoothness.dart or someplace better to help folks interpret the 'janky_....' numbers?

There are docs in `scrollSummary` in that file, but I'll add more to make it clearer.

**Comment by zanderso** [comment]
Ohhh. Sorry! I didn't scroll down far enough =(

**Comment by CareF** [comment]
New docs add in PR #72479
