### ISSUE TITLE
Docs: InputFormField missing property documentation

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7245]
There is a disconnect in the docs regarding `InputFormField` and `Input`.

The `flutter_gallery` app uses `InputFormField` in it's `text_field_demo.dart` file and when searching the docs I found information on `InputFormField` but the majority of it's properties are not listed. There is a very handy usage guide but no property support.

I thought this was very strange because the flutter documentation is pretty accurate all the time, so I looked at the source code for the actual widget and found that it extends a `FormField<InputValue>` and if you want documentation on the actual properties, you have to look at `Input` as `InputFormField` just 'proxies' it's constructor to create an `Input` widget.

**Comment by mikemimik** [comment]
Re: #7031

**Comment by abarth** [comment]
Good point.
