### ISSUE TITLE
Cocoon should support showing LUCI builds on release branches

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#72466]
Currently, LUCI builds only show on the master branch of the flutter build dashboard.

This is blocked by teaching Cocoon which builder groups (dev, beta, stable) map to which release branches. Currently the source of truth for this information is in the flutter/infra repo.

**Comment by godofredoc** [comment]
We will add this to Q1 OKRs.

**Comment by CaseyHillers** [comment]
Did some digging into this, seems like we need to update [getLuciBuilders](https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/foundation/utils.dart;l=96?q=getLuciBuilders&ss=flutter%2Fcocoon) to accept a branch parameter. Then, we need to refactor [refresh_chromebot_status](https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/request_handlers/refresh_chromebot_status.dart;l=23?q=refreshChromebotStatus&ss=flutter%2Fcocoon) to iterate over the known branches.

**Comment by CaseyHillers** [comment]
@christopherfujino can you validate this on the release branches?

**Comment by christopherfujino** [comment]
@CaseyHillers I don't remember the thread on this issue. It looks like you merged https://github.com/flutter/cocoon/pull/1111 to support this, but then was reverted in https://github.com/flutter/cocoon/pull/1127.

**Comment by CaseyHillers** [comment]
@christopherfujino is the MILO page sufficient for releases? I've updated it to filter the bringup tasks into a separate column, and it serves the same data now that ci.yaml is generating the configs.

**Comment by CaseyHillers** [comment]
https://ci.chromium.org/p/flutter/g/beta_flutter/console here's the beta page for example

**Comment by christopherfujino** [comment]
> @christopherfujino is the MILO page sufficient for releases? I've updated it to filter the bringup tasks into a separate column, and it serves the same data now that ci.yaml is generating the configs.

For now, milo works fine. This would be a blocker to merging all targets to a single builder, however.

**Comment by CaseyHillers** [comment]
Ok, I'll close this out. Since there's a lot of work needed to move to a single builder, we'll track that work there.
