### ISSUE TITLE
desktop:windows build fails saying that plugins require symlink support, but developer mode already enabled

### ISSUE THREAD

**Issue by stevenovack** [flutter/flutter#72462]
Windows 10 Enterprise version 1909

When trying to build the flutter gallery app I get the following message:

**Please enable Developer Mode in your system settings. Run start ms-settings:developers to open settings.**

However, Developer Mode is already enabled on this machine. 

Note that this is corporate machine and I do not have admin rights. I have also verified that I *am* able to create symbolic links from the command line (using ln -s).

**Comment by TahaTesser** [comment]
Hi @stevenovack 
Can you please provide your `flutter doctor -v` your `flutter run -d windows --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by stevenovack** [comment]
Hi @TahaTesser, 
Unfortunately, I am not allowed to transfer any data from my work machine so I cannot show you the output. However, flutter doctor -v does not show any problems. Flutter run ends with the error mentioned above. Please let me know if there is anything in particular that you want me to look for.

To reproduce:

1. git clone https://github.com/flutter/gallery
2. cd gallery
3. flutter run

Note that flutter upgrade indicates that flutter is up to date.

**Comment by TahaTesser** [comment]
Hi @stevenovack 
You can censor/blur any directory location, the output would be mostly related to Flutter itself, it helps us to understand which version of Flutter causes the, what's the framework, engine revision, etc. 
If it reproduces with gallery repo, you don't need to provide a code sample 
Thanks

**Comment by stevenovack** [comment]
Hi @TahaTesser,

Sorry, but that's not an option -- my company is quite strict about this stuff. But, let me know if there is anything I can do to help diagnose the problem.

Cheers,
Steve

**Comment by TahaTesser** [comment]
Hi @stevenovack 
I understand, at least can you say what Flutter version you're on? Latest stable? 
Thank you

**Comment by stevenovack** [comment]
@TahaTesser 1.26.0-1.0.pre  channel dev  
Framework 63062a6443   2020-12-13
Engine 4797b06652
Dart 2.12.0

**Comment by TahaTesser** [comment]
Hi @stevenovack 
Can you please check the output of your `git config --list`
```bash
PS C:\Users\Taha> git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
user.name=Taha Tesser
user.email=tessertaha@gmail.com
PS C:\Users\Taha>
```
It would say `core.symlinks=true` 
If not, uninstall git and restart your machine, install it again

**Comment by stevenovack** [comment]
@TahaTesser OK, core.symlinks=false on my machine. I'll try uninstalling, restarting & reinstalling tomorrow and will let you know how it goes. Thanks for the help!

**Comment by stevenovack** [comment]
@TahaTesser Setting core.symlinks=true had no effect. 

But, after digging a bit deeper, it looks like I don't have the permission needed to create Windows symlinks, even though Developer Mode is enabled (apparently "ln -s", which does work, isn't implemented using Windows symlinks).

I may eventually be able to get Windows symlinks enabled on this machine, but I'm wondering if you can suggest any workarounds?  Or, would it be easy to change my local Flutter implementation to not need Windows symlinks?

Thanks for the help!

**Comment by TahaTesser** [comment]
Hi @stevenovack 
That might be it, hope you enable it and get it working on your system. I tried to find a workaround by disabling developer mode but I couldn't find any workaround. If you find any, comment below, it would help others.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
