### ISSUE TITLE
linux_web_integration_tests flake

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#72474]
There is one instance of flaky test

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_integration_tests/1330/overview
```
▌22:20:42▐ RUNNING: cd dev/integration_tests/web; ../../../bin/flutter run --debug -d chrome --web-run-headless --sound-null-safety -t lib/sound_mode.dart
Launching lib/sound_mode.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             514ms

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../../bin/flutter run --debug -d chrome --web-run-headless --sound-null-safety -t lib/sound_mode.dart
Relative working directory: dev/integration_tests/web
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
```

**Comment by jmagman** [comment]
Just saw this one https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8852024065734158784/+/steps/run_test.dart_for_web_integration_tests_shard_and_subshard_None/0/stdout

**Comment by goderbauer** [comment]
Happening again: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848867473267253184/+/steps/run_test.dart_for_web_integration_tests_shard_and_subshard_None/0/logs/stdout/0

**Comment by chunhtai** [comment]
duplicate of https://github.com/flutter/flutter/issues/77157
