### ISSUE TITLE
Recognize Visual Studio Code Insiders in flutter doctor

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#72489]
Visual Studio Code has two channels: the default and the Insiders channel. The latter is the 'beta' channel, used for testing early features.

We need to teach Flutter that it exists so that `flutter doctor` doesn't complain if this is the only editor available. For example, right now, on Apple Silicon, this is the only version of VSCode that has an Apple Silicon release.

```bash
$ which code-insiders
/usr/local/bin/code-insiders
```

## Flutter Doctor
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.62, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.26.0-2.0.pre.62 at /Users/timsneath/flutter
    • Framework revision 38852baf00 (5 hours ago), 2020-12-16 18:19:03 -0500
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
On linux I don't get the `Flutter IDE Support`, but doctor complains about missing android studio

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.64 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 9ff4326e1f (62 minutes ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

why my `flutter doctor -v` is so different ?

**Comment by timsneath** [comment]
You probably have `flutter config` set up for Android development, at which point you need Android Studio regardless. I have Android development disabled on this machine.

**Comment by jmagman** [comment]
This actually looks implemented, but hidden behind a flag:
https://github.com/flutter/flutter/blob/af164fe5594e24c869447df093a85d4790f84bf4/packages/flutter_tools/lib/src/vscode/vscode.dart#L12-L13

**Comment by jmagman** [comment]
@timsneath do you think `doctor` should always show Insiders, or just show it if there's no non-Insiders VS Code installation?

**Comment by timsneath** [comment]
Hmm. Good question. What do we do if someone has Android Studio release and canary installed? Probably it should be the same...

**Comment by jmagman** [comment]
@timsneath right now it shows all Android Studio versions, including `Android Studio Preview`.

**Comment by timsneath** [comment]
As the number of platforms continues to grow, this UI is starting to show its age a little. At some point I'd love to redesign it to pivot by platforms, so that we can show what platforms you have support for with the current installs, and then what is missing that you'd need to install to enable new targets. 

I believe there are several user journeys currently conflated in `flutter doctor`, along the following lines:

1. I want to make sure I have everything installed that I need to code for platform X;
2. I want to troubleshoot why something isn't working correctly (the 'doctor' element);
3. I want a log of the necessary version information to file a bug report.

I'll make a note to see if one of the PMs has interest in testing my assumptions and/or doing some research here.
