### ISSUE TITLE
Hot reload fails after restarting app with Android back button

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#7248]
Run a Flutter app in debug mode on Android.  Press the back button to dismiss the app, then use the task swticher to swtich back to the app.  Then do a hot reload.

flutter_tools will throw an exception:
    Exception from flutter run: NoSuchMethodError: Class 'NoSuchMethodError' has no instance method '[]'.
    Receiver: Instance of 'NoSuchMethodError'
    Tried calling: []("code")

This is coming from _validateReloadReport.  The reloadReport message in this case is not an actual ReloadReport.  It looks like:
    {type: Sentinel, kind: Collected, valueAsString: <collected>}

@johnmccutchan

**Comment by mit-mit** [comment]
@jason-simmons can we close this now that you landed #7249 ?

**Comment by jason-simmons** [comment]
I'm still seeing this error when I do a hot reload after a stop and restart:
    Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

#7249 improves the error message, but there's still an underlying issue

**Comment by johnmccutchan** [comment]
@jason-simmons Flutter tools is addressing the *old* isolate and the vm service is saying that it doesn't exist anymore. The fix is to enumerate the views and find the isolate again.

**Comment by AmitJoki** [comment]
I am still facing this problem. When I exit the app and enter again, this error crops up.

**Comment by eaotnc** [comment]
> I am still facing this problem. When I exit the app and enter again, this error crops up.

I same with you. Thx

**Comment by zoechi** [comment]
This issue is long closed. Please create a new issue with more information (filled out issue template).

**Comment by as1ndu** [comment]
Fixed this after running `flutter clean`

**Comment by duzenko** [comment]
> 
> 
> This issue is long closed. Please create a new issue with more information (filled out issue template).

https://github.com/flutter/flutter/issues/43164

**Comment by himanshuvats1996** [comment]
> Fixed this after running `flutter clean`

the correct solution save your time use this

**Comment by VanDerRomio** [comment]
i just restart my IDE and all work again:)

**Comment by prasannaprashi** [comment]
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
same error

**Comment by kumarishivanisingh14** [comment]
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
I am not getting correct solution for this error.

**Comment by devDeejay** [comment]
Getting same error after I was trying to work with Animations in Flutter.

**Comment by kutigbolahan** [comment]
> Getting same error after I was trying to work with Animations in Flutter.

Flutter clean worked for me
