### ISSUE TITLE
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().

### ISSUE THREAD

**Issue by xiongyoudou** [flutter/flutter#72484]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.62, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.0)
[✓] Connected device (2 available)

• No issues found!

I want to test flutter projects,so i have 3 steps

1. flutter build ios --debug
success

2. flutter run -d 'xxxxxxxx' --use-application-binary xxxx/build/ios/iphonesimulator/Runner.app  --vmservice-out-file=outputFile.txt --debug --start-paused --target=test_driver/app.dart

3. flutter drive --target=test_driver/app.dart --no-build --use-existing-app=http://127.0.0.1:57289/5hxel7t6xwc\=/ -d '131332B0-0330-4396-BB7A-6C1D16C2D035'

![image](https://user-images.githubusercontent.com/2812119/102436409-75568600-4053-11eb-997f-947698557968.png)

although waiting a long, still  will not output the test results.

I already tried on my iPhones or simulators，all failed in flutter drive,shows :
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().

So I tried add enableFlutterDriverExtension on my main.dart:
![image](https://user-images.githubusercontent.com/2812119/102435576-d1200f80-4051-11eb-9a6e-38a37b714435.png)

The result is that: flutter drive success, output the test result.

But in a real project, I shouldn't add enableFlutterDriverExtension in my main.dart, only in my test_driver/app.dart should OK.

![image](https://user-images.githubusercontent.com/2812119/102438789-f31c9080-4057-11eb-8d1e-a0bdf5c35283.png)

I already tried that ,when command flutter run ,i directly run without --use-application-binary parameter, this time, although no enableFlutterDriverExtension in my main.dart, still success.

So I confused, what's wrong with my situation.

**Comment by pedromassangocode** [comment]
Hi @xiongyoudou 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample? You may want to push a complete minimal sample project on GitHub!

Thank you

**Comment by xiongyoudou** [comment]
This is my flutter doctor -v:
[✓] Flutter (Channel master, 1.26.0-2.0.pre.62, on Mac OS X 10.15.6 19G2021 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.26.0-2.0.pre.62 at /Users/youduxiong/code/flutter
    • Framework revision 38852baf00 (13 小时前), 2020-12-16 18:19:03 -0500
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/youduxiong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhoneXR (mobile)          • 00008020-001E74862201002E            • ios            • iOS 14.1
    • iPhone 12 Pro Max (mobile) • 131332B0-0330-4396-BB7A-6C1D16C2D035 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 87.0.4280.88

And I found that use this command:
![image](https://user-images.githubusercontent.com/2812119/102486732-71068900-40a4-11eb-9adb-e168309f5b58.png)
the VMService i can successfully get the test results with flutter drive
or I use the runner.app from the command ,and then
![image](https://user-images.githubusercontent.com/2812119/102486823-985d5600-40a4-11eb-928e-f99d345f1fd2.png)

use the generated Runner.app, I also can successfully get the test results.

But when i get the Runner.app from command,
flutter build ios --debug
,use the generated Runner.app, firstly i can get the VMService successfuly，But when I use the generated VMService,I faild,output the below error:
![image](https://user-images.githubusercontent.com/2812119/102487000-d9556a80-40a4-11eb-8219-ee0f51c6e45e.png)

So I doubt is there something different in Runner.app between flutter run and flutter build ios

This is my code:https://github.com/xiongyoudou/testFlutter

**Comment by xiongyoudou** [comment]
I already solved the problem,thanks.
i forgot to add --target to flutter build ios,like this:
flutter build ios --debug --target=test_driver/app.dart
