### ISSUE TITLE
NNBD plugins in flutter/plugins are skipping some tests

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#72493]
In https://github.com/flutter/plugins/pull/3318 we introduced a mechanism to skip tests for the nnbd pluging on stable, determining whether to skip the plugins is done by looking at the `CHANNEL` environment variable set by Cirrus.

We had critical problems in that PR:
1. The comparison done with `[[ "$CHANNEL" -eq "stable" ]]` always returned true, which means we essentially stopped testing the nnbd plugins. (Not a bash expert but I believe `-eq` is for integer comparisons, this should have been a `==` comparison).
2. Some CI tasks are only running on stable which means for these tasks we won't be testing the nnbd plugins.

Unfortunately this resulted in bad code successfully passing CI and landing for example: the new tests in https://github.com/flutter/plugins/pull/3334 introduced Dart compile errors, this was not detected by the analyze phase as the plugin was completely skipped in https://cirrus-ci.com/task/4598922096148480, from the log of that task:

```
./script/incremental_build.sh analyze
Excluding the following plugins: android_intent,connectivity,device_info,flutter_plugin_android_lifecycle,flutter_webview,google_sign_in,local_auth,path_provider,plugin_platform_interface,share,url_launcher,video_player,webview_flutter
```

cc @blasten @bparrishMines

**Comment by blasten** [comment]
@Hixie has actually fixed this issue in https://github.com/flutter/plugins/pull/3281

**Comment by amirh** [comment]
It doesn't looks like flutter/plugins#3281 fixes the issue, from the analysis task for that PR:

```
Excluding the following plugins because stable does not yet support NNBD: android_intent,connectivity,device_info,flutter_plugin_android_lifecycle,flutter_webview,google_sign_in,local_auth,path_provider,plugin_platform_interface,share,url_launcher,video_player,webview_flutter
```

link: https://cirrus-ci.com/task/5319991153131520

**Comment by amirh** [comment]
I staged a fix in: https://github.com/flutter/plugins/pull/3342

**Comment by amirh** [comment]
Assigning @blasten  as I'm OOO and you know the exclusion logic the best.
I believe https://github.com/flutter/plugins/pull/3342 is fixing this.
