### ISSUE TITLE
flutter adds https git remote repo `__flutter_version_check__`

### ISSUE THREAD

**Issue by zjiekai** [flutter/flutter#72497]
## Steps to Reproduce
1. run `flutter -v help`.  The command gets stuck.

My local flutter repo will have a new remote `__flutter_version_check__` repo `https://github.com/flutter/flutter.git`.  But my dev environment can only use the `git:` protocol.

https://github.com/flutter/flutter/blob/05dadb0120b4aa3e5c0ccb1cf302632bf563d104/packages/flutter_tools/test/general.shard/version_test.dart#L103

**Comment by pedromassangocode** [comment]
Hi @zjiekai  
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by zjiekai** [comment]
I fixed my git https issue.  Now I can not reproduce this anymore.

**Comment by pedromassangocode** [comment]
Hi @zjiekai 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
