### ISSUE TITLE
SoundTrack:s cannot control volume

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#725]
It's not possible to control the volume of SoundTracks, this is required for fading/mixing different tracks.

API here: https://github.com/vlidholt/sky_engine/blob/master/skysprites/lib/src/sound.dart

**Comment by eseidelGoogle** [comment]
I believe @jason-simmons fixed this?  The game has different volume sounds last I knew?

**Comment by sethladd** [comment]
We'll want to take a fresh look at audio, but in the meantime, we're going to close this issue. We can reopen if we validate this use case again.
