### ISSUE TITLE
I am getting "Flutter intent redirection " issue as i upload the app on playstore, and they have given me until 21st December 2020 to clear this issue. if not they'll remove my app Please help me

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter/flutter#72504]
pubspec.yaml

name: hi_tech_flutter
description: A new Flutter project.

version: 1.0.0+17

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.0
  shimmer: ^1.1.1
  flutter_slidable: ^0.5.7
  flutter_rating: ^0.0.2
  intro_views_flutter: ^2.8.2
  global_configuration: ^1.6.0
  image_picker: ^0.6.7+15
  http: ^0.12.2
  intl: ^0.16.1
  shared_preferences: ^0.5.12
  mvc_pattern: ^6.0.0
  cached_network_image: ^2.3.2+1
  flutter_form_builder: ^3.14.0
  razorpay_flutter: ^1.2.3
  loading: ^1.0.2
  progress_dialog: ^1.2.4
  toast: ^0.1.5
  no_context_navigation: ^1.0.3
  flutter_plugin_android_lifecycle: ^1.0.11
  onesignal_flutter: ^2.6.1
  url_launcher: ^5.7.10
  provider : ^4.0.4
  pub_semver: ^1.4.4
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by pedromassangocode** [comment]
Hi @faisalmushtaq007 
This is not an issue with Flutter. See https://github.com/flutter/flutter/issues/66901#issuecomment-707006823 for more information.

See https://github.com/flutter/flutter/issues/66901 for more information about what maybe causing this issue.
