### ISSUE TITLE
'_debugLifecycleState == _StateLifecycle.created': is not true.

### ISSUE THREAD

**Issue by KOSSHOH** [flutter/flutter#72503]
Failed assertion: line 1117 pos 12: '_debugLifecycleState == _StateLifecycle.created': is not true.

**Comment by darshankawar** [comment]
@KOSSHOH 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by KOSSHOH** [comment]
> @KOSSHOH
> Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
> Thanks.
