### ISSUE TITLE
path_provider: Unsupported operation: Functionality only available on Android

### ISSUE THREAD

**Issue by salim-lachdhaf** [flutter/flutter#72502]
i'm getting this issue on Ios 

```
method_channel_path_provider.dart - Ligne 55
getExternalStoragePath

Unsupported operation: Functionality only available on Android
```

**Comment by darshankawar** [comment]
@salim-lachdhaf 
Check out [this](https://pub.dev/documentation/path_provider/latest/path_provider/getExternalStorageDirectory.html) document. You are probably trying to use access `getExternalStorageDirectory` which states:

`Path to a directory where the application may access top level storage. The current operating system should be determined before issuing this function call, as this functionality is only available on Android.`

**Comment by salim-lachdhaf** [comment]
i want that files being visible and accessible for the user , which function i use in this case in IOS ?
