### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by basha97** [flutter/flutter#72514]
device_info not running when i add file_picker packages, but running smoothly when i remove the file_picker package.

This is my log

Launching lib\main.dart on SM M307F in debug mode...
Running Gradle task 'assembleDebug'...
Error: unable to find directory entry in pubspec.yaml: D:\flutter_works\flortex_app\assets\lottie\

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Android resource linking failed
D:\flutter_works\flortex_app\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element found in .

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 32s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin device_info...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

Where:
Build file 'C:\src\flutter.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\android\build.gradle' line: 22

What went wrong:
A problem occurred evaluating root project 'device_info'.

Failed to apply plugin [id 'com.android.internal.version-check']
Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\src\flutter.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.6.4-all.zip

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin device_info could not be built due to the issue above.

**Comment by darshankawar** [comment]
@basha97 
You closed same issue and opened again. 
Closing this as per earlier issue's comment.
