### ISSUE TITLE
connectivity : Not working when tethering hotspot is turned on in Samsung mobile

### ISSUE THREAD

**Issue by Gowthamsubramaniam94** [flutter/flutter#72516]
I'm experiencing some strange behaviour in Samsung mobile (Android v10) with [Connectivity  ](https://pub.dev/packages/connectivity) plugin. 

I've turned Off the Internet but `connectivityResult == ConnectivityResult.wifi` returning **true** when tethering hotspot is enabled. But when I turned Off the tethering hotspot it working fine `connectivityResult == ConnectivityResult.wifi` it returning **false**.

Only I'm facing issue in below scenario,
**Mobile Data** - Turned Off
**WiFi** - Turned Off
**Tethering Hotspot** - Turned On

This scenario is working perfectly,
**Mobile Data** - Turned Off
**WiFi** - Turned Off
**Tethering Hotspot** - Turned Off

**Comment by darshankawar** [comment]
@Gowthamsubramaniam94 
Can you provide `flutter doctor -v` ? You can also checkout this behavior using official `connectivity` plugin example and confirm if you still see same issue.

**Comment by Gowthamsubramaniam94** [comment]
Yes I'm confirming that I've implemented the `Connectivity` plugin as per the document. 

Only I'm facing issue in Samsung device's tethering hotspot. In other devices it's working fine.

I think the issue is because of Samsung having Wi-Fi Sharing option under Tethering hotspot. May be this is the reason of returning `true` when mobile data & Wi-Fi turned Off (Tethering hotspot is turned ON).

**Comment by darshankawar** [comment]
@Gowthamsubramaniam94 
Can you try the same using `wifi_info_flutter` [plugin](https://pub.dev/packages/wifi_info_flutter/install) and see if you get same result ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
