### ISSUE TITLE
Android momentum scrolling should come to a rest sooner

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7251]
I think we have a flavor of this bug on file, but copying from internal bug 33583767 just in case:

"""
When you scroll and lift your finger, the Flutter version of the physics keeps scrolling longer than the Android one. This becomes an issue when you want to scroll and swipe, as it happens in the [see internal bug] view. 

The swipe gesture detection only kicks in once the list has come to a complete stop. If the list is still in motion when the user touches down, their gesture is interpreted as scroll, not swipe. So to swipe in Flutter the user must scroll, then wait for the list to stop completely (which is a longer amount of time than Android), and then touch down and swipe. Or alternatively, scroll, then tap (which stops the scrolling), make sure they lift the finger to ensure that a new gesture will be detected, and only then they can swipe.

The Android physics appears to have quicker dampening, tuned to stop scrolling in the time it takes a user to lift their finger and touch down.
"""

**Comment by eseidelGoogle** [comment]
@sethladd @HansMuller do we already have a flavor of this on file?

**Comment by eseidelGoogle** [comment]
customer: leafy has indicated this is an important bug to them for Q1.

**Comment by mehmetf** [comment]
I don't think this is an issue anymore. Testing with latest version of Flutter, I cannot detect any differences in scroll sensitivity between Flutter and native Android.
