### ISSUE TITLE
Use Vulkan Engine

### ISSUE THREAD

**Issue by tongweizhou** [flutter/flutter#72511]
When using the vulkan engine, there are many problems found。

1.Vulkan Engine has some Compilation issues ( 1.12 and 1.22 both)
   https://github.com/flutter/flutter/issues/72426  **can fix**

2.Abnormal color

3.Benchmark TestCase failed

**Comment by darshankawar** [comment]
@tongweizhou 
Is this issue different than https://github.com/flutter/flutter/issues/72426 or same ?
If it's same, please mention above issue and follow-up in original rather than creating new issue.

**Comment by tongweizhou** [comment]
@darshankawar  #7426 is  a compilation error
I want to discuss the benchmark errors and display exceptions for vulkan on this issue

**Comment by darshankawar** [comment]
@tongweizhou 
I'd suggest you to keep only one issue  since it's related to vulkan engine and no need to have separate tracking for same issue. Either you keep this issue open or the other since both are more or less have same steps to replicate. 
If you have further questions, you may follow-up in other issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
