### ISSUE TITLE
OTP message suggestion shows for all number pad text fields

### ISSUE THREAD

**Issue by kaarens93** [flutter/flutter#72537]
On an ios device, the OTP message suggestion doesn't go away even after I've used it. I have a form with multiple number pad text fields and the OTP message suggestion appears for all these fields.

I've tried the solutions from this issue: https://github.com/flutter/flutter/issues/22828 
They don't work for me.
```
enableSuggestions: false,
autocorrect: false
```
I can't use `keyboardType: TextInputType.visiblePassword` because my keyboard has to be numbers.

How can I hide or remove the keyboard suggestion after I've used it?

**Comment by darshankawar** [comment]
@kaarens93 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by GabrielF9** [comment]
Same issue here, using `flutter 1.22.1`

Has a way to reopen this issue or is better to open a new one? In bellow is my `flutter doctor -v`

---

[√] Flutter (Channel unknown, 1.22.1, on Microsoft Windows [versÃ£o 10.0.19041.746], locale pt-BR)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (4 months ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Gabriel\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Gabriel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30002.166
    • Windows 10 SDK version 10.0.18362.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Gabriel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64 • Microsoft Windows [versÃ£o 10.0.19041.746]

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@GabrielF9 
The latest stable version is 1.22.6. I'd recommend to upgrade to latest and try again to see if issue persists. 
If so, please open new issue by providing all required details.

**Comment by GabrielF9** [comment]
@darshankawar
Ok, perfect!
I'll try this today and comment here the results.

**Comment by GabrielF9** [comment]
Hey @darshankawar
I was only able to try with `flutter 1.22.6` this week, and the problem still happens, below is my `flutter doctor -v`:

---

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19041.746], locale pt-BR)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Gabriel\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Gabriel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.1)
    • VS Code at C:\Users\Gabriel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by GabrielF9** [comment]
Hey guys, any update on this?
