### ISSUE TITLE
The pushReplacement doesn't work

### ISSUE THREAD

**Issue by adrielrosanelli** [flutter/flutter#72535]
this is the message:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3144 pos 12: '_debugLocked && !_debugUpdatingPage': is not true.

**Comment by ZainUrRehmanKhan** [comment]
Kindly provide these details: 
     - Reproducible Code 
     -  flutter doctor -v

**Comment by adrielrosanelli** [comment]
I'm already solved the problem, just updated the flutter
