### ISSUE TITLE
Micro-tune all Cupertino widgets based on comparison tooling

### ISSUE THREAD

**Issue by xster** [flutter/flutter#72545]
@DanielEdrisian created an overlay comparison tooling for iOS at https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare between native UIKit/SwiftUI and Flutter's implementation. We should go back and comb through all of our current https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/cupertino widgets to double check for minor differences and possible iOS 14 changes to make them tightly match. 

PRs from community welcome as well for tweaks on the Flutter framework or additions to the https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare tool.

**Comment by adarsh-technocrat** [comment]
Hello, @xster 👋 I would love to work on this issue if you could explain me a bit more about this issue.

**Comment by xster** [comment]
The work would generally involve picking a Cupertino widget, adding it to the comparison tool's Flutter side in https://github.com/flutter/platform_tests/blob/master/ios_widget_catalog_compare/lib/main.dart, and also to the SwiftUI side in https://github.com/flutter/platform_tests/blob/master/ios_widget_catalog_compare/ios/Runner/OverlaySwiftUIView.swift to compare if they overlap correctly. 

If any discrepancies are observed, make the corresponding tweaks as needed in https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/cupertino. 

Thanks for anyone interested in participating!!

**Comment by nogicoder** [comment]
Hi @xster , can I take on this issue?

**Comment by xster** [comment]
Yes absolutely. Please send us PRs and reference this bug on the PR so others can know what's being worked on.

**Comment by nogicoder** [comment]
> Yes absolutely. Please send us PRs and reference this bug on the PR so others can know what's being worked on.

Hi @xster, currently I'm modifying for the widgets to be fit within each other. But since SwiftUI is not open source, I cannot access the exact value so the tweaks are done visually only. Is this method allowed to resolve this issue?

Also, can you please give me an advice for how to write a test in this case?

Thank you very much!

**Comment by xster** [comment]
Correct. It'll primarily be a visual alignment (which is why that tool was made to facilitate). However, there are still some help we can get from Xcode such as via https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-SW2 to pull out properties like the font style or color etc.

**Comment by Moluram** [comment]
Hello @xster !
I would like to take this issue
Should I attach before/after screenshots of the widgets?

**Comment by jmagman** [comment]
iOS 15 beta 1 dropped today, the Cupertino Form particularly is pretty different:

https://user-images.githubusercontent.com/682784/121098062-f04e5d00-c7a9-11eb-8e37-a52949281851.mov

**Comment by YazeedAlKhalaf** [comment]
I would like to contribute to this issue. 🙋‍♂️🚀

**Comment by xster** [comment]
That's correct. Thank you @YazeedAlKhalaf. 

cc @LongCatIsLooong

**Comment by YazeedAlKhalaf** [comment]
If anybody would like to contribute also, here you will find helpful resources for iOS design.
You can figure out sizes, colors, and some other stuff related to Cupertino design.

https://developer.apple.com/design/resources

Now there is only iOS 14 kits, and 13 kits too, but soon there will be iOS 15 once it is released to the public.

**Comment by cpboyd** [comment]
Rather than creating a separate issue, I'll mention it here:
It appears that iOS 15 bumped the persistent NavigationBar size to 56 and may have adjusted font sizes as well.

**Comment by ivirtex** [comment]
It seems that in iOS 15 all lists now use InsetGroupedListStyle.

![image](https://user-images.githubusercontent.com/57679865/137460564-9dd968b8-daa3-4924-b1e1-a5fb1a3def44.png)

We should implement something like this into the Cupertino library.

**Comment by Piinks** [comment]
We're using the overlay tool as we are working through fine tuning widgets individually. Since this is an older issue and we believe is covered by other issues for individual refinements, we are going to close this. Thanks!
