### ISSUE TITLE
The flutter app doesn't work on android 11, but everything is fine on android 8 and on IOS too

### ISSUE THREAD

**Issue by Vasajj** [flutter/flutter#72552]
In my flutter app i'm using cached_network_image: ^2.4.1 and it does't work in some android phones on android 11, on andrid 8 all is goin great. Full my question is by link https://stackoverflow.com/questions/65347111/the-flutter-app-doesnt-work-on-android-11-but-everything-is-fine-on-android-8

**Comment by darshankawar** [comment]
@Vasajj 
`cached_network_image` is a 3rd party plugin. Please open this issue in plugin owner's repo: https://github.com/Baseflow/flutter_cached_network_image/issues
Closing as this isn't an issue with Flutter. If you disagree, write in comments and I'll reopen it.
