### ISSUE TITLE
Flutter isn't connecting to my device after updating sdk

### ISSUE THREAD

**Issue by BrightCode1** [flutter/flutter#72550]
I tried doing flutter run but it says device not connected when actually my android emulator is opened, if i use my mobile device it works but if i use android emulator it doesn't
I ran **flutter doctor -v** and this is the result

<details> 
<summary>flutter doctor -v</summary> 

```bash
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (2 months ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\brightisaac\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\brightisaac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    ! Device emulator-5554 is offline.

! Doctor found issues in 1 category.`
```

</details>

My android sdk path is already updated which is at **android-sdk: C:\Users\brightisaac\AppData\Local\Android\sdk**

![emu](https://user-images.githubusercontent.com/32621169/102540942-1115df80-40b0-11eb-973a-e6ecb1f0cfbd.png)

Please what do i do to connect it to my android device

**Comment by TahaTesser** [comment]
Hi @BrightCode1 
I cannot reproduce this issue on the latest `stable` channel.
Can you please upgrade to the latest  `dev` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and `flutter emulators --verbose` logs,
Thank you

**Comment by BrightCode1** [comment]
I changed my command shell from git bash to terminal and ran `flutter run` and it worked
