### ISSUE TITLE
I had some problems updating the version of Flutter

### ISSUE THREAD

**Issue by ycf4971** [flutter/flutter#72577]
`flutter upgrade --force`
Upgrading Flutter from /Users/yaochaofeng/flutter/flutter...
Downloading Dart SDK from Flutter engine ae90085a8437c0ae94d6b5ad2741739ebc742cb4...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  172M    0  142k    0     0   746k      0  0:03:56 --:--:--  0:03:56  742k
  3  172M    3 6576k    0     0  5521k      0  0:00:32  0:00:01  0:00:31 5516k
  7  172M    7 12.1M    0     0  5667k      0  0:00:31  0:00:02  0:00:29 5665k
 10  172M   10 17.4M    0     0  5391k      0  0:00:32  0:00:03  0:00:29 5389k
 13  172M   13 23.1M    0     0  5648k      0  0:00:31  0:00:04  0:00:27 5646k
 15  172M   15 27.4M    0     0  4789k      0  0:00:36  0:00:05  0:00:31 4926k
 15  172M   15 27.4M    0     0  4388k      0  0:00:40  0:00:06  0:00:34 4129k
 18  172M   18 31.9M    0     0  4427k      0  0:00:39  0:00:07  0:00:32 3904k
 21  172M   21 37.4M    0     0  4680k      0  0:00:37  0:00:08  0:00:29 4196k
 25  172M   25 43.4M    0     0  4842k      0  0:00:36  0:00:09  0:00:27 4166k
 27  172M   27 47.7M    0     0  4795k      0  0:00:36  0:00:10  0:00:26 4803k
 28  172M   28 49.5M    0     0  4521k      0  0:00:39  0:00:11  0:00:28 4698k
 32  172M   32 56.1M    0     0  4681k      0  0:00:37  0:00:12  0:00:25 5064k
 35  172M   35 61.1M    0     0  4749k      0  0:00:37  0:00:13  0:00:24 4862k
 38  172M   38 65.7M    0     0  4742k      0  0:00:37  0:00:14  0:00:23 4561k
 41  172M   41 70.8M    0     0  4774k      0  0:00:37  0:00:15  0:00:22 4731k
 44  172M   44 77.3M    0     0  4888k      0  0:00:36  0:00:16  0:00:20 5713k
 48  172M   48 83.2M    0     0  4956k      0  0:00:35  0:00:17  0:00:18 5643k
 51  172M   51 89.0M    0     0  5013k      0  0:00:35  0:00:18  0:00:17 5710k
 54  172M   54 94.2M    0     0  5027k      0  0:00:35  0:00:19  0:00:16 5837k
 57  172M   57 99.7M    0     0  5056k      0  0:00:34  0:00:20  0:00:14 5915k
 61  172M   61  106M    0     0  5128k      0  0:00:34  0:00:21  0:00:13 5907k
 64  172M   64  112M    0     0  5171k      0  0:00:34  0:00:22  0:00:12 5911k
 67  172M   67  117M    0     0  5178k      0  0:00:34  0:00:23  0:00:11 5780k
 71  172M   71  123M    0     0  5214k      0  0:00:33  0:00:24  0:00:09 5933k
 73  172M   73  127M    0     0  5170k      0  0:00:34  0:00:25  0:00:09 5629k
 76  172M   76  131M    0     0  5138k      0  0:00:34  0:00:26  0:00:08 5179k
 79  172M   79  136M    0     0  5148k      0  0:00:34  0:00:27  0:00:07 5043k
 82  172M   82  142M    0     0  5188k      0  0:00:34  0:00:28  0:00:06 5232k
 86  172M   86  148M    0     0  5208k      0  0:00:33  0:00:29  0:00:04 5177k
 89  172M   89  153M    0     0  5221k      0  0:00:33  0:00:30  0:00:03 5478k
 93  172M   93  161M    0     0  5303k      0  0:00:33  0:00:31  0:00:02 6165k
 97  172M   97  167M    0     0  5322k      0  0:00:33  0:00:32  0:00:01 6268k
100  172M  100  172M    0     0  5327k      0  0:00:33  0:00:33 --:--:-- 6119k
Building flutter tool...

Unhandled exception:
Invalid argument(s): Cannot find executable for sysctl.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:92:30)
#2      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:481:37)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:380:14)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:481:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:425:51)
#6      _MacOSUtils.hostPlatform (package:flutter_tools/src/base/os.dart:302:25)
#7      _MacOSUtils.name (package:flutter_tools/src/base/os.dart:288:123)
#8      new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:243:18)
#9      new Usage (package:flutter_tools/src/reporting/usage.dart:80:9)
#10     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:241:20)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#15     flutterUsage (package:flutter_tools/src/globals.dart:52:35)
#16     _handleToolError (package:flutter_tools/runner.dart:133:13)
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:87:13)
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:81:17)
#19     _rootRunBinary (dart:async/zone.dart:1222:13)
#20     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#21     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
#22     _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#23     Future._propagateToListeners (dart:async/future_impl.dart:646:16)
#24     Future._completeError (dart:async/future_impl.dart:537:5)
#25     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
#27     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#28     _rootRunBinary (dart:async/zone.dart:1214:47)
#29     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#30     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#31     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#32     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#33     Future._completeError (dart:async/future_impl.dart:537:5)
#34     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#35     _rootRun (dart:async/zone.dart:1190:13)
#36     _CustomZone.run (dart:async/zone.dart:1093:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Any "`flutter`" command I use on the terminal after throwing an exception will give an error

**Comment by pedromassangocode** [comment]
Hi @ycf4971 
Are you able to run `flutter doctor -v`? If so, can you provide the output?
Thank you

**Comment by ycf4971** [comment]
> Hi @ycf4971
> Are you able to run `flutter doctor -v`? If so, can you provide the output?
> Thank you

No I can't run the command with flutter.

**Comment by pedromassangocode** [comment]
Hi @ycf4971 
Can you please provide the output of `flutter upgrade --force -v`?
Thank you

**Comment by ycf4971** [comment]
I have solved the problem. I added `export PATH=/usr/sbin:$PATH` to `.zsh` to make it work
