### ISSUE TITLE
[webview_flutter] `Video plays inline when allowsInlineMediaPlayback is true` stopped passing

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#72572]
This test was added in https://github.com/flutter/plugins/pull/3334, but it doesn't seem to pass in https://github.com/flutter/plugins/pull/3342

I have disabled this test temporarily.

Logs: https://api.cirrus-ci.com/v1/task/6645013176123392/logs/build.log

**Comment by mehmetf** [comment]
Dumb question: How do I run this test locally? :)

**Comment by cyanglaz** [comment]
https://github.com/flutter/flutter/issues/73768#issuecomment-813611070 probably because of this
