### ISSUE TITLE
[device_info] Exception: The plugin device_info could not be built due to the issue above.

### ISSUE THREAD

**Issue by JAICHANGPARK** [flutter/flutter#72578]
I had some problem about device info  that build time 
```
Building plugin device_info...
Running Gradle task 'assembleAarRelease'...
Exception: The plugin device_info could not be built due to the issue above.
```
## Flutter Doctor 
```
Flutter is already up to date on channel beta
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (2 days ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

**Comment by darshankawar** [comment]
@JAICHANGPARK 
I tried the official `device_info` plugin example on latest master and it compiled and ran properly.

<img width="340" alt="Screenshot 2020-12-18 at 1 54 40 PM" src="https://user-images.githubusercontent.com/67046386/102591825-a78de380-4138-11eb-8cb7-f8d24e12b0cd.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.64 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9ff4326e1f (26 hours ago), 2020-12-17 06:19:05 +0000
    • Engine revision 6edb402ee4
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!


```

</details>

Can you try the same and see if you still get similar error ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by IlyaOstashkov** [comment]
same issue

**Comment by akash-flutterdev** [comment]
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.685], locale en-IN)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Users/aaa/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:/Users/aaa/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\aaa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (3 available)
    • moto g 6 plus (mobile) • ZF6223C868 • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 88.0.705.56


same issue

**Comment by cristianms** [comment]
Same ussue here...
Has anyone managed to solve this?
in my case it occurs during the build in GitLab CI.

**Comment by darshankawar** [comment]
@cristianms 
`device_info` plugin is deprecated in favor of `device_info_plus`. See this for more details. https://pub.dev/packages/device_info#deprecation-notice

Please open your issue in dedicated repo: https://github.com/fluttercommunity/plus_plugins/issues
