### ISSUE TITLE
How to make status bar color & Appbar color is different?

### ISSUE THREAD

**Issue by pqtrong17** [flutter/flutter#72581]
My English isn't good. Hope everyone understand.
If `Appbar` appear, color of status bar & background app bar to same. How to I make status bar color & Appbar color is different?
Ex: Appbar background is `blue` and status bar color is `red` (In this case, present both is `blue`)

**Comment by shatanikmahanty** [comment]
You can use this package for android and ios : https://pub.dev/packages/flutter_statusbarcolor

**Comment by darshankawar** [comment]
@pqtrong17 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
