### ISSUE TITLE
Make Material support Hero, Let child InkWell splash and continue animating during move.

### ISSUE THREAD

**Issue by YeungKC** [flutter/flutter#72588]
This idea was suggested by @Hixie [0], but it is not clear what Material designer thinks about it.

[0]: https://discord.com/channels/608014603317936148/608021234516754444/788865123547873341

**Comment by YeungKC** [comment]
@willlarche Could you confirm this behavior? plz.

**Comment by Hixie** [comment]
I really don't think we need to do this. You can do it today by just putting the Material inside your hero.

**Comment by YeungKC** [comment]
OK

**Comment by YeungKC** [comment]
@Hixie 

If need inkwell to splash continue in a move (e.g. changing depth), then either inkwell or the ancestor widget must have a globalkey.

In this hero case, it is not possible to use globalkey in this case, because globalkey can only be used on one widget. When the hero is moving.
