### ISSUE TITLE
image_picker 0.6.7+17

### ISSUE THREAD

**Issue by Puspharaj** [flutter/flutter#72595]
Using Android 10.

https://pub.dev/packages/image_picker  => image_picker: ^0.6.7+17

getImage from source camera always crash, It's not that sporadically as mention in document.

When I click image from camera the app closes and nothing is retrieved using retrieve lost data as mentioned by the docs.
Images from gallery works fine.

It might be click from camera has to store the image somewhere and preview once the app restore.

```dart
Future<void> retrieveLostData() async {
        final LostData response =
             await picker.getLostData();
         if (response.isEmpty) {
          return;
         }
        if (response.file != null) {
                 setState(() {
              if (response.type == RetrieveType.video) {
                _handleVideo(response.file);
              } else {
                   _handleImage(response.file);
               }
               });
         } else {
                 _handleError(response.exception);
        }
       }
```

Please check and update ASAP.

Thanks.

**Comment by TahaTesser** [comment]
Hi @Puspharaj 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` while picking from image, capture crash logs. 
Which device are you using testing  on? 
Thank you

**Comment by Puspharaj** [comment]
[flutter] flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1139], locale en-IN)
    • Flutter version 1.22.4 at D:\Software\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Pusp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Pusp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Redmi 8A Dual (mobile) • 004a08490407 • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.
exit code 0

************************************************************************************************

 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(already_active, Image picker is already
active, null, null)
[  +12 ms] E/flutter ( 4128): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[   +5 ms] E/flutter ( 4128): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[ +188 ms] E/flutter ( 4128): <asynchronous suspension>
[ +157 ms] E/flutter ( 4128): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[ +335 ms] E/flutter ( 4128): #3      MethodChannelImagePicker.pickImagePath
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
[ +238 ms] E/flutter ( 4128): #4      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
[ +320 ms] E/flutter ( 4128): #5      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
[ +309 ms] E/flutter ( 4128): #6      _HomeFormState.getImage (package:Jatka/pages/home/view/home_form.dart:64:33)
[  +25 ms] E/flutter ( 4128): #7      _HomeFormState.build.<anonymous closure>.<anonymous closure> (package:Jatka/pages/home/view/home_form.dart:167:36)
[   +2 ms] E/flutter ( 4128): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
[   +1 ms] E/flutter ( 4128): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
[ +295 ms] E/flutter ( 4128): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[   +4 ms] E/flutter ( 4128): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[ +847 ms] E/flutter ( 4128): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[   +5 ms] E/flutter ( 4128): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
[ +352 ms] E/flutter ( 4128): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
[ +421 ms] E/flutter ( 4128): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[   +2 ms] E/flutter ( 4128): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)     
[   +3 ms] E/flutter ( 4128): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[ +273 ms] E/flutter ( 4128): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[ +673 ms] E/flutter ( 4128): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[ +253 ms] E/flutter ( 4128): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
[ +223 ms] E/flutter ( 4128): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[   +1 ms] E/flutter ( 4128): #22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[ +274 ms] E/flutter ( 4128): #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[ +242 ms] E/flutter ( 4128): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[ +257 ms] E/flutter ( 4128): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[ +185 ms] E/flutter ( 4128): #26     _rootRunUnary (dart:async/zone.dart:1206:13)
[ +194 ms] E/flutter ( 4128): #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[ +239 ms] E/flutter ( 4128): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[ +201 ms] E/flutter ( 4128): #29     _invoke1 (dart:ui/hooks.dart:265:10)
[   +2 ms] E/flutter ( 4128): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[   +2 ms] E/flutter ( 4128): 
[   +2 ms] I/Timeline( 4128): Timeline: Activity_launch_request time:703919387
[   +9 ms] Service protocol connection closed.
[ +841 ms] Lost connection to device.
[ +514 ms] Error writing "build/flutter_assets/fonts/Varela_Round/VarelaRound-Regular.ttf" to DevFS: SocketException: Write failed (OS Error: An establishedconnection was aborted by the software in your host machine.
                    , errno = 10053), address = 127.0.0.1, port = 54560
[ +560 ms] trying again in a few - 9 more attempts left



I don't think it's actually throw some error. It just quit from vscode  while run  or debug the application. Even might be the same case while out of the run || debug application.

Might me a temporary storage causing the issue i guess.

**Comment by TahaTesser** [comment]
Hi @Puspharaj 
Can you please provide  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Puspharaj** [comment]
`RaisedButton(
                          child: Text("Image Gallery"),
                          onPressed: () => getImage(true)),
                      Container(
                        height: 90,
                        width: 90,
                        child: _image == null
                            ? Text('No image selected.')
                            : Image.file(_image),
                      ),


               Future getImage(bool camera) async {
                      if (camera) {
                     _imageFile = await picker.getImage(source: ImageSource.camera);
                     } else {
                    _imageFile =
                            await picker.getImage(source: ImageSource.gallery, imageQuality: 25);
                  }

                 setState(() {
                 if (_imageFile != null) {
                        _image = File(_imageFile.path);
                 } else {
                 print('No image selected.');
                   }
                });
               }
      

          Future<void> retrieveLostData() async {
             final LostData response = await picker.getLostData();
             if (response.isEmpty) {
                return;
             }
          if (response.file != null) {
            setState(() {
              if (response.type == RetrieveType.video) {
                 //_handleVideo(response.file);
          } else {
            _imageFile = response.file;
          }
        });
           } else {
              // _handleError(response.exception);
              }
         }
`

These are the above code as per the doc which i've used nothing more or less, Is that anything to do with Android version 10?, I have not tried this app in other than android 10.!

**Comment by TahaTesser** [comment]
Hi @Puspharaj 
Your code sample is still incomplete but i added misisng pieces and tried to reproduce on Android 10,  when picking from the camera.

<details> 
<summary>code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  PickedFile _imageFile;
  final ImagePicker picker = ImagePicker();
  File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: RaisedButton(
            child: Text("Image Gallery"), onPressed: () => getImage(true)),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }

  Future getImage(bool camera) async {
    if (camera) {
      _imageFile = await picker.getImage(source: ImageSource.camera);
    } else {
      _imageFile =
          await picker.getImage(source: ImageSource.gallery, imageQuality: 25);
    }

    setState(() {
      if (_imageFile != null) {
        _image = File(_imageFile.path);
        print(_image);
      } else {
        print('No image selected.');
      }
    });
  }
}

``` 

</details>



Printed picked image
```bash
I/flutter ( 5877): File: '/storage/emulated/0/Android/data/com.nevercode.triage/files/Pictures/9ee88233-9e19-4b29-8b97-5543138835827163817677748928682.jpg'
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android
      10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS
      14.3

! Doctor found issues in 1 category.
```

</details>

Please try the code sample I have provided, check logs for the picked image file on your Android 10 device 
If the problem persists, please logs with `flutter run --verbose and complete reproducible code sample

Thank you

**Comment by Puspharaj** [comment]
I'm testing this in real device, When i click the button and take a picture, Connection to the device lost. The debug or run instance is closed with this message. 

`I/Timeline( 7728): Timeline: Activity_launch_request time:868292985
Lost connection to device.
Exited (sigterm)
`

**Comment by TahaTesser** [comment]
Hi @Puspharaj 
Which physical device are you experiencing this issue with? please provide logs with `flutter run --verbose` **with a crash logs** and complete reproducible code sample

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
