### ISSUE TITLE
Move sound API into Flutter

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#726]
Move the sound API into Flutter (it's currently in sprites).

API is currently here: https://github.com/vlidholt/sky_engine/blob/master/skysprites/lib/src/sound.dart

**Comment by sethladd** [comment]
After a recent discussion, we've decided to make an effort to move more functionality into dedicated packages. Here's the request to create a new flutter_audio package: https://github.com/flutter/flutter/issues/1364

Going to close this one. Please reopen if we're talking about two different things.
