### ISSUE TITLE
Flutter plugin not installed and Dart plugin not installed

### ISSUE THREAD

**Issue by giacomok** [flutter/flutter#72604]
I do not know howto solve these warnings. The 2 plugins are correctly installed in android studio.

As you can see I set android-studio-dir to the exact path of android-studio.

```
[!] Android Studio
    • Android Studio at /opt/android-studio/bin/
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /opt/android-studio/bin/
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=
```

**Comment by TahaTesser** [comment]
Hi @giacomok 
Please at this https://github.com/flutter/flutter/issues/67986#issuecomment-715452201
Plugin not being detected won't affect the Flutter functionally.

Regarding Android Studio, please `  flutter config --android-studio-dir= <add_your_android_studio_location>
and for java add  this in  your`.bashrc` 

`export JAVA_HOME=/home/your location/android-studio/jre`

Thank you

**Comment by giacomok** [comment]
I did both either flutter `config --android-studio-dir` or exported `JAVA_HOME`. This is the result of echo $JAVA_HOME:

`/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64`

**Comment by realrk69** [comment]
I faced a similar problem. Usually, Invalidating Cache and Restart fix all problems, and anyway, these issues should not prevent you from debugging or running. I had a major clash between almost 7 different Java versions installed on my system and I had to do a complete re-install of OS to clear the clutter. Flutter doctor still shows plugins missing sometimes, but it always works.

**Comment by TahaTesser** [comment]
Hi @giacomok 
https://github.com/flutter/flutter/issues/72604#issuecomment-748082269, looks it's not updated, please uninstall existing java 8 and point `export JAVA_HOME=/home/your location/android-studio/jre`

For plugins not being detected, already point to the answer https://github.com/flutter/flutter/issues/67986#issuecomment-715452201

@realrk69 has good suggestions for clearing the clutter


Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
