### ISSUE TITLE
Getting wrong video extension formate. 

### ISSUE THREAD

**Issue by panchalAlpit** [flutter/flutter#72600]
I have used image_picker: ^0.6.7+17 plugin for getting video but i'm getting "/data/user/0/com.example.praticeproject/cache/image_picker8656688061738700607.jpg" **jpg formate in video file**.
` final PickedFile file = await _picker.getVideo(
     source: source, maxDuration: const Duration(seconds: 10));`
     
  Thanks in advance

**Comment by pedromassangocode** [comment]
Hi @panchalAlpit 
This is a known issue and is being tracked in https://github.com/flutter/flutter/issues/52419.
I'm going to close this as a duplicate. Please follow up on https://github.com/flutter/flutter/issues/52419.
Thank you
