### ISSUE TITLE
Add onLongPress property to DataCell

### ISSUE THREAD

**Issue by slimyjimmy** [flutter/flutter#72609]
I'm using the `DataTable` widget which works like a charm. 

# Problem
Unfortunately, the `DataCell`s (building blocks for the `DataRows`) lack a `onLongPress` property (which would be quite handy in many cases for showing further options).

# Proposal
Add a `onLongPress` (and maybe even `onDoubleTap`) property to `DataCell`.

**Comment by chunhtai** [comment]
cc @dkwingsmt

**Comment by ZainUrRehmanKhan** [comment]
This should be closed now.

**Comment by dkwingsmt** [comment]
Close with https://github.com/flutter/flutter/pull/75393
