### ISSUE TITLE
StandardMessageCodec support for float arrays

### ISSUE THREAD

**Issue by OsmanAltun** [flutter/flutter#72613]
## Use case

Currently, if I were to send a float array from android to flutter with the use of eventSink.success(arr), It would not work. Double arrays are [supported](https://api.flutter.dev/flutter/services/StandardMessageCodec-class.html), but sometimes it is required to work with float arrays (i.e. the read function of the AudioRecord class). Converting an float array to an double array is not fast and efficient enough to work. This disables to possibility of using AudioFormat.ENCODING_PCM_FLOAT. 

## Proposal
See [StandardMessageCodec](https://api.flutter.dev/flutter/services/StandardMessageCodec-class.html) for better understanding.

Add support for message:
 - Float32List

On android:
 - Float32List: **float[]**

On IOS:
 - Float32List

**Comment by fuzzybinary** [comment]
Are there any big gotchas to potentially implementing this? Given the low-ish priority, is this something that someone from the community could tackle?

**Comment by fuzzybinary** [comment]
All code to support should now be in master -- documentation PR is up.

**Comment by stuartmorgan** [comment]
Closing as fixed.
