### ISSUE TITLE
Build failed Minimum supported Gradle version

### ISSUE THREAD

**Issue by basha97** [flutter/flutter#72619]
D:\flutter\flortex_app>flutter build apk
```
Running "flutter pub get" in flortex_app...                         0.7s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
WARNING: [Processor] Library 'C:\Users\vinoth\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_release\1.0.0-2c956a31c0a3d350827aee6c56bb63337c5b4e6e\d16762b6784c6a5a7b5
da4ab52be9bd1ca53ba16\flutter_embedding_release-1.0.0-2c956a31c0a3d350827aee6c56bb63337c5b4e6e.jar' contains references to both AndroidX and old support library. This seems like the li
brary is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'
Error: unable to find directory entry in pubspec.yaml: D:\flutter\flortex_app\assets\lottie\
WARNING: [Processor] Library 'C:\Users\vinoth\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_debug\1.0.0-2c956a31c0a3d350827aee6c56bb63337c5b4e6e\d766fe2feb740ead017d0
02eae7d82dd4f337a93\flutter_embedding_debug-1.0.0-2c956a31c0a3d350827aee6c56bb63337c5b4e6e.jar' contains references to both AndroidX and old support library. This seems like the librar
y is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: D:\flutter\flortex_app\build\app\intermediates\flutter\debug\libs.jar.
         > Transform's input file does not exist: D:\flutter\flortex_app\build\app\intermediates\flutter\debug\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 30s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      91.5s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin device_info...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    2.2s


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'device_info'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\flutter\.pub-cache\hosted\pub.dartlang.org\
device_info-1.0.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.6.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin device_info could not be built due to the issue above.
```

**Comment by iapicca** [comment]
@basha97 

can you please double-check that your app follows [this](https://flutter.dev/docs/development/androidx-migration)

**Comment by basha97** [comment]
Checking

**Comment by basha97** [comment]
@iapicca 

I checked androidx which you mentioned above.
now i am getting different error

D:\flutter\flortex_app>flutter build apk
Running "flutter pub get" in flortex_app...                         0.6s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Error: unable to find directory entry in pubspec.yaml: D:\flutter\flortex_app\assets\lottie\

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: D:\flutter\flortex_app\build\app\intermediates\flutter\debug\libs.jar.
         > Transform's input file does not exist: D:\flutter\flortex_app\build\app\intermediates\flutter\debug\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      60.4s
Gradle task assembleRelease failed with exit code 1

**Comment by darshankawar** [comment]
@basha97 
From your log, I see below:

`Error: unable to find directory entry in pubspec.yaml: D:\flutter\flortex_app\assets\lottie\`

It may be due to the way you have setup `assets` in your project. Double check if your `assets` implementation in `pubspec.yaml` is correct. Also check [this](https://www.reddit.com/r/Flutter/comments/eltysk/unable_to_load_images_into_project/) similar issue and comment and see if it helps.

**Comment by basha97** [comment]
@darshankawar 

 the pubspec file issue is common and i had removed that folder.

**Comment by darshankawar** [comment]
@basha97 
You seem to have open another duplicate issue, https://github.com/flutter/flutter/issues/72679 which has been closed based on your most latest [comment](https://github.com/flutter/flutter/issues/72679#issuecomment-748715673) in it. 

I am going ahead and closing this based on that comment.
