### ISSUE TITLE
Hot Reload and SQFlite

### ISSUE THREAD

**Issue by mado-bohsali** [flutter/flutter#72617]
Certain transactions only run **after hot reload**. Why?

**Comment by nstrelow** [comment]
SQFlite is not maintained by the Flutter team.
You might ask here: https://github.com/tekartik/sqflite or generally for questions like this ask on stackoverflow

**Comment by darshankawar** [comment]
@mado-bohsali 
I see that you have already asked this question on sqflite repo. Closing from here.
