### ISSUE TITLE
Request: Move charts_flutter aka google/charts to flutter/packages so it can receive some basic open source maintenance

### ISSUE THREAD

**Issue by nstrelow** [flutter/flutter#72618]
It would be very helpful, if we could have the charts_flutter package get some support from the community (and Google).

https://github.com/google/charts

It seams the package is some kind of export from google3. Not sure how opensourcing dart or flutter libraries is usually handled, but it would really mean a lot, if this package could be moved to the official flutter/packages repo, so that the PRs are actually included.

Thanks a lot for your work flutter community. And have some happy, safe and healthy holidays 🎄

**Comment by iapicca** [comment]
@nstrelow 
I'm not sure that flutter team can arbitrarily "absorb" other teams repositories
and if it could I'd advocate that probably shouldn't.

Moreover, judging from the [issues](https://github.com/google/charts/issues) I believe the community already contribute to said repository

**Comment by nstrelow** [comment]
Thanks for you explanation :)

Yes contribution is there, but sadly it is not accepted in any way.

from the Readme:

"This project is developed internally at Google and published for external consumption, external contributions unfortunately cannot be taken at this time."

So my quest is to find a way to make official contributions to jt possible, without forking it and adding a new package based on it.

Another problem is, that since it's in the Google repository, it seems very official, thus one might expect the same kind of support official packages get (if not reading the Readme fully).

This is also probably why one of my teammates chose it for our project.

**Comment by pedromassangocode** [comment]
Hi @nstrelow 
Flutter is not supposed to absorb other packages. 


> So my quest is to find a way to make official contributions to jt possible, without forking it and adding a new package based on it.

I think the best way to do this is by making a fork and release a new package from it (if the license allows that).

**Comment by nstrelow** [comment]
I see,
I was more hoping that someonce from Google internally could do something about it.

Thanks anyway 😁
