### ISSUE TITLE
flutter doctor issues

### ISSUE THREAD

**Issue by Mohammed-elklawy** [flutter/flutter#72623]
i make a variable JAVA_HOME and i put the path of jdk in it and still give me this problem !
 
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale ar-EG)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.52.0)
[√] Connected device (1 available)

**Comment by Mohammed-elklawy** [comment]
i unistalled android studio and reinstalling it and when i rum flutter doctor it give me 


! Doctor found issues in 1 category.

C:\Users\asm>flutter doctor
Waiting for another flutter command to release the startup lock...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale ar-EG)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Mohammed-elklawy** [comment]
and this for licenses

C:\Users\asm>flutter doctor --android-licenses
Android sdkmanager tool not found (C:\Users\asm\AppData\Local\Android\sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

**Comment by ritvij14** [comment]
https://stackoverflow.com/questions/52256569/android-sdkmanager-tool-not-found

Did you try any of these methods?

**Comment by darshankawar** [comment]
@Mohammed-elklawy 
Try [this](https://github.com/flutter/flutter/issues/55791#issuecomment-747303475) solution and see if it works.

**Comment by mahimakaushik-oss** [comment]
plugins are installed in android studio but still flutter doctor is showing its not installed . please help to remove this error
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
