### ISSUE TITLE
flutter doctor --android-licenses results in status unknown

### ISSUE THREAD

**Issue by safield** [flutter/flutter#72629]
When I run flutter doctor -v, it tell me my android licenses status is unknown...

```
✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.22.5 at /usr/local/flutter-sdk
    • Framework revision 7891006299 (8 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/local/android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/local/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

```

I then run flutter doctor --android-licenses, and see that the licenses are accepted.

```
Warning: File /home/user/.android/repositories.cfg could not be loaded.     
All SDK package licenses accepted.======] 100% Computing updates...         
```
I then run flutter doctor, and it still say android license status unknown.

**Comment by Abhishek01039** [comment]
please try `flutter doctor -v` after restarting the terminal or cmd.
Thanks

**Comment by iapicca** [comment]
@safield 
can you run the `flutter doctor --android-licenses -v` 
and post the output, preferably attached as `.txt` file if too verbose

**Comment by TahaTesser** [comment]
Hi @safield 
I noticed you're using Java 11, please downgrade to java 8, Android is compatible with 8 
You can uninstall 11 and point JAVA_HOME to Android Studio's jre which is 8
`export JAVA_HOME=/home/your_location/android-studio/jre`  in your .bashrc or similar file 
please provide details asked [above](https://github.com/flutter/flutter/issues/72629#issuecomment-748476346) and also worth restarting terminal

**Comment by safield** [comment]
> Hi @safield
> I noticed you're using Java 11, please downgrade to java 8, Android is compatible with 8
> You can uninstall 11 and point JAVA_HOME to Android Studio's jre which is 8
> `export JAVA_HOME=/home/your_location/android-studio/jre` in your .bashrc or similar file
> 
> If the problem persists after these channels Can you please provide your `flutter doctor -v` with change & your `flutter doctor --android-licenses -v`
> Thamk you

I use Java 8 when running android sdkmanager commands....otherwise the just blow up entirely.

**Comment by TahaTesser** [comment]
Hi @safield 
Yep, always Java 1.8, it also comes bundled with Android Studio for the same reason.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
