### ISSUE TITLE
webview with Hyrbid compostion don't show AlertDialog that have a State, Crashes after few sec later

### ISSUE THREAD

**Issue by ycv005** [flutter/flutter#72624]
## Steps to Reproduce

**To be Note**

Using Webview plugin with Hybrid composition enable, AlertDialog is blinking very frequently and 
app is crashes after some times whereas when I am using same things without Hybrid composition then it shows Ads and app don't crash.

Here is the Video (with Hybrid Composition is enabled)- https://photos.app.goo.gl/CwQQ2t88GRjrKafa8
Here is the Video (with Hybrid Composition is not enabled)- https://photos.app.goo.gl/cVaeDDqBxLkLyWYD8

1. Need a facebook monetisation account.
2. Using https://pub.dev/packages/facebook_audience_network package.
3. Now, Loading Ads into AlertDialog widget then showing, there is kind of state is involved.

**Expected results:** 
- On Exit, the webview, I actually show an Alert Dialog box and there I have placed an Facebook ads, which has an state mean, it appear when Ad is loaded.

**Actual results:** 
- AlertDialog box should be showing Ads without blinking with or without Hybrid composition enable.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

Some other issue related to webview hybrid composition that also hide some parts, i think- https://github.com/flutter/flutter/issues/72441

**Comment by iapicca** [comment]
@ycv005 
can you provide your `flutter doctor -v` and most importantly 
a **_minimal reproducible code sample_** that does not depend from 3rd party plugins or packages

**Comment by ycv005** [comment]
If I provide the code without 3rd party plugin then there will be no problem

Current Situation- 
- 3rd Party plugin with Hybrid comp. -> blink and then crash
- 3rd Party plugin with no Hybrid comp. -> All Normal
- No 3rd Party plugin at that particular place with or without Hybrid comp. -> All normal

I am providing the `flutter doctor -v`, if you still need the code, tell me

```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.5 at /home/yash/snap/flutter/common/flutter
    • Framework revision 7891006299 (9 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/yash/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • RMX1851 (mobile) • 65e4bff3 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
> If I provide the code without 3rd party plugin then there will be no problem

@ycv005 
in this case the bug is likely to depend from [facebook_audience_network](https://pub.dev/packages/facebook_audience_network)
you might want to open the issue in the dedicated [github](https://github.com/dreamsoftin/facebook_audience_network/issues)

**Comment by ycv005** [comment]
But, app works well while showing ads with 3rd party plugin when I am not using Hybrid composition.

**Comment by darshankawar** [comment]
@ycv005 
If the code runs well without any 3rd party plugins, then as @iapicca mentioned, it could well be an issue with the plugin you are using and you'll need to follow-up in it for your issue.
As far as the issue you referred earlier, https://github.com/flutter/flutter/issues/72441, it's device specific issue and not similar to what you've described.
The facebook plugin you are using may not be compatible with hybrid composition, so it's better to ask this question / issue in that repo instead of here. If the plugin owner confirms it's not an issue with the plugin, write in comments here and I'll reopen it.
Closing this for now. 
Thanks.
