### ISSUE TITLE
Android DartEntrypoint pathToEntrypointFunction should be customizable

### ISSUE THREAD

**Issue by xster** [flutter/flutter#72630]
There's bundle path and entrypoint function name, but no entrypoint file name. So there's no easy way to point to another dart file in lib/. 

https://github.com/flutter/engine/blob/21195a1aefcd79ceb1e1436a3649cd79448be619/shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java#L124 

is just null here.

**Comment by surda19-jin** [comment]
End

**Comment by apgapg** [comment]
This will help to reference proper main.dart file in case of different env like debug, prod. Currently, we need to use only lib/main.dart or it won't recognize main file
