### ISSUE TITLE
avoid_void_async lints async returns but docs advise other things

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter#72654]
# Description
In [async-await#working-with-futures-async-and-await](https://dart.dev/codelabs/async-await#working-with-futures-async-and-await) it says:

```
If the function has a declared return type, then update the type to be Future<T>, where T is the type of the value that the function returns. If the function doesn’t explicitly return a value, then the return type is Future<void>:
```

But If you enable this lint `avoid_void_async` then the lint will say:

![image](https://user-images.githubusercontent.com/76348/102694405-d8c8eb00-41ee-11eb-8fa6-b3e71980a0e0.png)

# Solution
The lint should not lint an async function, it does not make sense since the compiler will make the return value to be a `Future`.

**Comment by Roshan13046** [comment]
> In [async-await#working-with-futures-async-and-await](https://dart.dev/codelabs/async-await#working-with-futures-async-and-await) it says:
> 
> ```
> If the function has a declared return type, then update the type to be Future<T>, where T is the type of the value that the function returns. If the function doesn’t explicitly return a value, then the return type is Future<void>:
> ```
> 
> But If you enable this lint `avoid_void_async` then the lint will say:
> 
> ![image](https://user-images.githubusercontent.com/76348/102694405-d8c8eb00-41ee-11eb-8fa6-b3e71980a0e0.png)
> 
> It does not make sense to me if it will return a `Future` by the compiler.
> 
> The solution will be just to remove that lint by myself or it is really a bug in the linter?

can you please describe a bit more about what exactly to do here to fix it?

**Comment by danielgomezrico** [comment]
@Roshan13046 the lint just does not make sense, the return will be a `Future` for `async` functions even if you don't declare it explicitly.

**Comment by goderbauer** [comment]
These lints are part of the linter packages. Issues should be filed on the linter repository: https://github.com/dart-lang/linter/
