### ISSUE TITLE
flutter content handler on fuchsia can only launch one app per environment

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7266]
Subsequent apps don't seem to start.

**Comment by apwilson** [comment]
@gmesch

**Comment by abarth** [comment]
Sounds like a regression because this was working previously.

**Comment by gmesch** [comment]
This was https://fuchsia-review.googlesource.com/#/c/17309/. So we can close it here.

**Comment by Hixie** [comment]
Closing per last comment.
