### ISSUE TITLE
Can't use CupertinoDynamicColor with CupertinoApp theme

### ISSUE THREAD

**Issue by NuclleaR** [flutter/flutter#72664]
Hi!
I'm currently developing an iOS application with Flutter and I'm having problems with `CupertinoDynamicColor`.
I can't understand how to use `CupertinoDynamicColor` with `CupertinoThemeData`.
When I added `CupertinoDynamicColor` to the textStyle field it doesn't work when I use dark mode.
It seems to works when use `CupertinoDynamicColor.resolve(textColor, context))` but in this case context does't have media query and `CupertinoDynamicColor` always resolves with light theme.

this is example code:
```Dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      theme: CupertinoThemeData(
        barBackgroundColor: const CupertinoDynamicColor.withBrightness(
          color: Colors.blue,
          darkColor: Colors.red,
        ),
        textTheme: CupertinoTextThemeData(
          textStyle: TextStyle( 
            // in this place context doesn't have media query
            color: const CupertinoDynamicColor.withBrightness(
              color: Colors.blue,
              darkColor: Colors.red,
            ),
          ),
        ),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(middle: Text('Test')),
      child: Text('Test Text'),
    );
  }
}
```

**Comment by pedromassangocode** [comment]
Hi @NuclleaR 
Can you please provide your `flutter doctor -v` and the expected vs actual results?
Thank you

**Comment by NuclleaR** [comment]
@pedromassangocode Hi!

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale en-UA)
    • Flutter version 1.22.5 at /Users/nuclear/.flutter-bin
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

Expected result is to have ability to use `CupertinoDynamicColor` in Theme data.

solution with this example works well
```Dart
CupertinoDynamicColor.withBrightness(
  color: Colors.blue,
  darkColor: Colors.red,
).resolveFrom(context)
```
but problem here to make it works correct context should have media query. Media query exists inside `App` widget, but it doesn't exist when you creating theme data to pass to App widget.

**Comment by chunhtai** [comment]
cc @LongCatIsLooong

**Comment by pedromassangocode** [comment]
Hi @NuclleaR 
I'm not sure if I get you right, but I think you don’t need a context there. The code you provided does not even uses Dark mode, please see if the code bellow works for you, it has dark mode enabled and the text color is expected to be RED in dark mode and green in light mode.

![Screen Shot 2020-12-22 at 07 20 20](https://user-images.githubusercontent.com/67424416/102856128-34c98480-4426-11eb-9707-b71744440f28.png)

<details><summary>Code</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      theme: CupertinoThemeData (
        brightness: Brightness.dark,
        barBackgroundColor: const CupertinoDynamicColor.withBrightness(
          color: Colors.green,
          darkColor: Colors.red,
        ),
        textTheme: CupertinoTextThemeData(
          textStyle: TextStyle(
            // in this place context doesn't have media query
            color: const CupertinoDynamicColor.withBrightness(
              color: Colors.green,
              darkColor: Colors.red,
            ),
          ),
        ),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(middle: Text('Test')),
      child: Text('Test Text'),
    );
  }
}
```
</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
