### ISSUE TITLE
[google_maps_flutter] Widget as a child for the Markers of Google Maps 

### ISSUE THREAD

**Issue by malithkuruppu** [flutter/flutter#72668]
Is there a way to add a Widget to a child of Google Map markers?

If not, will the flutter developers be able to add this a new feature?

**Comment by darshankawar** [comment]
@malithkuruppu 
Can you elaborate on the use case and what are you trying to achieve ?

**Comment by malithkuruppu** [comment]
@darshankawar for example, it can be a travel app, where shows an array of images of the location the user has had visited. The user can tap on this marker to add more images. This needs to be marker on top of the google maps

**Comment by darshankawar** [comment]
@malithkuruppu 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/67199
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
