### ISSUE TITLE
ListTileTheme: lack of proprieties

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#72670]
## Use case

`ListTileTheme` has no all of proprieties of `ListTile`, for example it has no `visualDensity` ,`isThreeLine`, `mouseCursor` , ...

## Proposal

Make `ListTileTheme` more powerful by adding more props

**Comment by ahyangnb** [comment]
I feel it too.

**Comment by chunhtai** [comment]
cc @shihaohong

**Comment by shihaohong** [comment]
This might be related to the pending work for improving theming: https://github.com/flutter/flutter/issues/31247.

**Comment by TahaTesser** [comment]
`mouseCursor` is added in one of my previous PR and new PR would add `visualDensity` in the theme

`isThreeLine` is not suitable for the theme as it depends on the `subtitle`, not all `ListTile` would be expected to have `subtitle`.
