### ISSUE TITLE
Is there any resolution on this?   I've just run into the dame issue.  Will file out the "new issue" as requested.

### ISSUE THREAD

**Issue by GaryCampbell120177** [flutter/flutter#72674]
Is there any resolution on this?   I've just run into the dame issue.  Will file out the "new issue" as requested.
But if on the home screen in my app and the phone back button is pushed the app reverts to the splash and hangs?

_Originally posted by @GaryCampbell120177 in https://github.com/flutter/flutter/issues/28300#issuecomment-748589543_

**Comment by iapicca** [comment]
> Is there any resolution on this? I've just run into the dame issue. Will file out the "new issue" as requested.
> But if on the home screen in my app and the phone back button is pushed the app reverts to the splash and hangs?
> 
> _Originally posted by @GaryCampbell120177 in [#28300 (comment)](https://github.com/flutter/flutter/issues/28300#issuecomment-748589543)_

@GaryCampbell120177 
the message just before yours states

> [...]
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

could you provide the information requested above

**Comment by pedromassangocode** [comment]
Hi @GaryCampbell120177 
Please do file a new issue by filling the issue template.
