### ISSUE TITLE
devtool timeline tab UI and Raster bar got jank

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#72677]
Just One Text Widget!

<details><summary>Code</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Clock(),
    );
  }
}

class Clock extends StatefulWidget {
  @override
  _ClockState createState() => _ClockState();
}

class _ClockState extends State<Clock> {
  Timer timer;
  String _time;

  @override
  void initState() {
    super.initState();
    _time = DateTime.now().toString();
    timer = Timer.periodic(Duration(milliseconds: 1000), _updateTime);
  }

  @override
  void dispose() {
    timer.cancel();
    super.dispose();
  }

  _updateTime(_) {
    setState(() {
      _time = DateTime.now().toString();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Text(_time);
  }
}
```
</details>

**Comment by lyqiai** [comment]
![WeChat151fa79d20b9ba33422d93cd97b29770](https://user-images.githubusercontent.com/22760358/102712077-27fb4280-42f9-11eb-9ff7-1ad3069c873f.png)

**Comment by lyqiai** [comment]
![WeChat151fa79d20b9ba33422d93cd97b29770](https://user-images.githubusercontent.com/22760358/102712092-43664d80-42f9-11eb-92af-055b4f902874.png)

**Comment by vadvadvadvare** [comment]
Göm. Fram  


    .

**Comment by lyqiai** [comment]
The devTool outputs do not seem to observatory

**Comment by lyqiai** [comment]
<img width="1390" alt="WeChat5efdd17257ba8647c75903116b22ca83" src="https://user-images.githubusercontent.com/22760358/102735068-6ab22e80-437c-11eb-8e1e-e4a7590210e4.png">
build this clock widget need 46.7ms frame in my project ~_~

**Comment by pedromassangocode** [comment]
Hi @lyqiai, 
To report bugs or feature request regarding `devtools` please open an issue in the dedicated [github](https://github.com/flutter/devtools/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
