### ISSUE TITLE
Invoke-WebRequest exception in batch script / flutter run

### ISSUE THREAD

**Issue by Taarue** [flutter/flutter#72684]
I'm having an issue where my flutter wont run after I ran the flutter doctor command
 First I see this

 BITS Transfer                                                                                                              This is a file transfer that uses the Background Intelligent Transfer Service (BITS).                                   [                                                                                                            ]                                                                                                                                  Transferring      

Then this follows 

Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : The decryption operation failed, see inner exception.
At C:\src\flutter\bin\internal\update_dart_sdk.ps1:77 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Error: Unable to update Dart SDK. Retrying...

**Comment by iapicca** [comment]
@Taarue 
are you behind a firewall?
Or located in China or other countries with geo-fencing

**Comment by Taarue** [comment]
> @Taarue
> are you behind a firewall?
> Or located in China or other countries with geo-fencing

I'm not sure if my firewall is on.. and my country doesn't have geofencing... let me check the firewall and try again

**Comment by pedromassangocode** [comment]
Hi @Taarue 
Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by Taarue** [comment]
> > @Taarue
> > are you behind a firewall?
> > Or located in China or other countries with geo-fencing
> 
> I'm not sure if my firewall is on.. and my country doesn't have geofencing... let me check the firewall and try again

Didn't work.... (T-T)

**Comment by Taarue** [comment]
> ```
> flutter doctor -v
> ```
First this pops up
![image](https://user-images.githubusercontent.com/50864019/102751756-4e75b800-43a3-11eb-861c-008615d41881.png)

then this

![image](https://user-images.githubusercontent.com/50864019/102750884-a90e1480-43a1-11eb-8cb0-6e9c82a9d7d1.png)

**Comment by pedromassangocode** [comment]
Hi @Taarue 
Can you please provide information about your Operating system?
Thank you

**Comment by Taarue** [comment]
> Hi @Taarue
> Can you please provide information about your Operating system?
> Thank you

Processor: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz 230 GHz
RAM:         8 GB
System type: 64-bit operating system, x64-based processor
Windows 10 Home Single Language
MSI

**Comment by christopherfujino** [comment]
@Taarue to rule out network problems, can you try to download this file: https://storage.googleapis.com/flutter_infra/flutter/92ae191c17a53144bf4d62f3863c110be08e3fd3/dart-sdk-windows-x64.zip

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Taarue** [comment]
It was a network Issue, changed my internet provider and it started working Thank you all
