### ISSUE TITLE
unable to create dart snapshot

### ISSUE THREAD

**Issue by nomicool** [flutter/flutter#72687]
I a continuously facing unable to create dart snapshot issue with fresh SDK download fresh android studio everything id up to date I have also tried this solution

git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
 but still the same please help me with this.

**Comment by darshankawar** [comment]
@nomicool 
Please provide `flutter doctor -v` and elaborate when do you get the snapshot error ? Are you getting the error while building release build ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
