### ISSUE TITLE
Text doesn't appear on some devices until reloading. 

### ISSUE THREAD

**Issue by danbudworthmead** [flutter/flutter#72698]
Steps to repro:

Write application with text, images, adverts, buttons etc. 

Build the APK. 

Notice how it works fine on virtual devices and some physical devices. But on some physical devices text doesn't load until user navigates to home screen and back to the application. 

<img height="720" src="https://user-images.githubusercontent.com/9319945/102734731-7845c500-4338-11eb-8e7a-ae8e806e58a2.png">|<img height="720" src="https://user-images.githubusercontent.com/9319945/102734749-7d0a7900-4338-11eb-8384-eca5f53b8558.png">

<img height="720" src="https://user-images.githubusercontent.com/9319945/102734763-84ca1d80-4338-11eb-9c3b-c9ce716a9afb.jpg">

**Comment by pedromassangocode** [comment]
Hi @danbudworthmead 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Please provide more information about the devices in which you faced this issue.
Thank you

**Comment by danbudworthmead** [comment]
`[√] Flutter (Channel master, 1.26.0-2.0.pre.84, on Microsoft Windows [Version 10.0.19041.685], locale en-GB)
    • Flutter version 1.26.0-2.0.pre.84 at Z:\GitHub\flutter
    • Framework revision cda1fae6b6 (3 days ago), 2020-12-18 04:04:02 -0500
    • Engine revision 1be6f414e7
    • Dart version 2.12.0 (build 2.12.0-166.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\acurl\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\acurl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.60

• No issues found!`

**Comment by danbudworthmead** [comment]
`import 'dart:io';

import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/material.dart';
import 'package:skeld_launch_flutter/SkeldButtons/VideoAdvertButton.dart';
import 'SkeldButtons/PlayButton.dart';
import 'SkeldButtons/RevertButton.dart';
import 'InfoText.dart';
import 'TitleText.dart';
import 'package:admob_flutter/admob_flutter.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(
      MaterialApp(
          home: Home(
          ),
      ),
  );
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  AdmobBannerSize bannerSize;
  AdmobInterstitial interstitialAd;
  AdmobReward rewardAd;

  @override
  void initState() {
    super.initState();

    Admob.initialize();

    interstitialAd = AdmobInterstitial(
      adUnitId: getInterstitialAdUnitId(),
      listener: (AdmobAdEvent event, Map<String, dynamic> args) {
        if (event == AdmobAdEvent.loaded) {
          interstitialAd.show();
        }
        handleEvent(event, args, 'Interstitial');
      }
    );

    rewardAd = AdmobReward(
      adUnitId: getRewardBasedVideoAdUnitId(),
      listener: (AdmobAdEvent event, Map<String, dynamic> args) {
        if (event == AdmobAdEvent.opened) {
          rewardAd.load();
        }
        handleEvent(event, args, 'Reward');
      }
    );

    interstitialAd.load();
    rewardAd.load();
  }

  @override
  void dispose() {
    interstitialAd.dispose();
    rewardAd.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: InfoText(),
    );
  }

  _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }

  void handleEvent(AdmobAdEvent event, Map<String, dynamic> args, String adType) {
    switch (event) {
      case AdmobAdEvent.loaded:
        print('New Admob $adType Ad loaded!');
        break;
      case AdmobAdEvent.opened:
        print('Admob $adType Ad opened!');
        break;
      case AdmobAdEvent.closed:
        print('Admob $adType Ad closed!');
        break;
      case AdmobAdEvent.failedToLoad:
        print('Admob $adType failed to load. :(');
        break;
      default:
    }
  }`


`import 'package:flutter/material.dart';

class InfoText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: Text(
        'Make sure Among Us is closed!\n\n'
        'skeld.net is the world\'s first custom Among Us server.\n\n'
        'Play Zombies, Crazy Colors, Twins, and much more.\n\n'
        'Played by Ssundee, Socksfor1, H2O Delirious, Jelly, and others.\n\n'
        'These adverts help us pay for the costs of running the servers.\n\n'
        'skeld.net was created by Saghetti & Arkatme. We love the original '
        'Among Us game and wanted to add some new game modes!',
        textAlign: TextAlign.center,
        style: TextStyle(
          color: Colors.black,
          fontFamily: 'Arial',
          fontSize: 24,
        ),
      ),
    );
  }
}`


This code should just display some black text on a white background. But even that doesn't work. 
The black text doesn't appear on one of my staff members Android OS 8 devices and one's Android OS 10 device until they go to the home screen and back into the application.

I am a complete flutter newbie so forgive my code sample.

**Comment by danbudworthmead** [comment]
Upon further investigation, the example application works fine. So it must be an issue with my code.

**Comment by danbudworthmead** [comment]
![image](https://user-images.githubusercontent.com/9319945/102783939-94c31b00-4393-11eb-83bc-e58a4feacd68.png)
![image](https://user-images.githubusercontent.com/9319945/102783946-97be0b80-4393-11eb-87a7-091939f614ec.png)
![image](https://user-images.githubusercontent.com/9319945/102783954-9ab8fc00-4393-11eb-8b3f-a3456337c61a.png)


After a whole lot of testing, I have discovered that Colors.black breaks the application.
This really is a glaring issue.

**Comment by danbudworthmead** [comment]
![image](https://user-images.githubusercontent.com/9319945/102792897-02c20f00-43a1-11eb-8c88-7265de6151c1.png)
![image](https://user-images.githubusercontent.com/9319945/102792903-05246900-43a1-11eb-8322-9513e279a1d1.png)
![image](https://user-images.githubusercontent.com/9319945/102792948-13728500-43a1-11eb-9f3e-ba5666f4d51c.png)


So, it's like it the physical phone sometimes is unable to load the text.

**Comment by timsneath** [comment]
Possibly connected to https://github.com/flutter/flutter/issues/72632? Do you see a similar error in the console?

**Comment by nicksnz3k** [comment]
in my situation i see popup message "Device frame rate is invalid. Device returned a target frame rate of 0.0 FPS. Using 60 FPS instead.". Only web last version - all is ok.

**Comment by danbudworthmead** [comment]
Uhh I don't know as I don't have the device. One of my friends in another country does and they don't have a PC so are unable to connect it to a PC to check.

**Comment by Akiat** [comment]
I think I got the same issue with master branch. But in my case, sometimes it's even worst, the text is bugged and is bad rendered.

```
[√] Flutter (Channel master, 1.26.0-2.0.pre.86, on Microsoft Windows [version 10.0.18363.1256], locale fr-FR)
    • Flutter version 1.26.0-2.0.pre.86 at C:\src\flutter
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Akiat\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Akiat\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\Akiat\Desktop\chrome.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 87.0.664.60

• No issues found!
```

**Comment by danbudworthmead** [comment]
![image](https://user-images.githubusercontent.com/9319945/102837172-3037a880-43f3-11eb-872c-a0a4fd221b08.png)
Well, it seems like that version of the SDK was severely fucked.
Grabbing latest from the github fixed all of the issues...
