### ISSUE TITLE
Misguided code lab - first flutter app pt1 - invalid constant value

### ISSUE THREAD

**Issue by kmusco02** [flutter/flutter#72690]
Step 3 for this code lab is using the "const" keyword for the "Center" widget. However, the next step (step 4) is using an external package (english_words) that is causing the code to generate an "invalid constant value" error if the person following the lab does not remove the "const" keyword.  The actual code for step 4 is correct in the code lab, however, the instructions do not indicate to the user that they need to remove the "const" keyword.  My suggestion is to simply remove the "const" keyword from the step 3 of the lab. This will prevent the error from occurring if the user is trying to follow along with the code lab. 

Reference:  https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1

Screenshot for step 3:
![image](https://user-images.githubusercontent.com/944346/102720231-3c234d80-42c1-11eb-893f-5e9d6118f861.png)

Screenshot for step 4 (instructions do not say to remove "const"):
![image](https://user-images.githubusercontent.com/944346/102720292-7bea3500-42c1-11eb-8e9d-e837f3f53505.png)

**Comment by werainkhatri** [comment]
I would like to work on this issue

**Comment by 2002Bishwajeet** [comment]
Hey I would request you to close this issue as this has already been fixed

**Comment by noln** [comment]
Step 3 still has that `const Center(..`, and as I like to type changes rather than copy-paste the whole block when learning I got stuck on this part. I'm sure I'm not alone.

Removing the `const` from _Step 3_, as @kmusco02 suggested, or adding a comment to that line to let the person following the codelab know that the keyword was removed, would prevent some frustration.

**Comment by domesticmouse** [comment]
Closing this out as the fix is in the process of being published
