### ISSUE TITLE
Flutter build fails with: java.nio.file.NoSuchFileException: 

### ISSUE THREAD

**Issue by johnjiea** [flutter/flutter#72694]
All my previously Flutter apps fail to build even when the SSD is replaced with a clone from two days ago.

I have tried "flutter pub cache repair" and "flutter clean" as suggested on StackOverflow.
 
Output from build:

Parameter format not correct -
java.nio.file.NoSuchFileException: C:\[DemocracyGB]\democracygb 00-00-00\build\app\intermediates\external_file_lib_dex_archives\debug\out
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:80)
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:522)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at com.android.build.gradle.internal.tasks.DexMergingParams.getAllDexFiles(DexMergingTask.kt:502)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:423)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

**Comment by iapicca** [comment]
@johnjiea 
can you provide your `flutter doctor -v `and the full output of `flutter build -v`

**Comment by johnjiea** [comment]
Thank you for your help and sorry it took so long, 

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\IronW\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29)    
      (emulator)

• No issues found!

=======================================================================
C:\[DemocracyGB]\democracygb 00-00-00>flutter build -v
[ +123 ms] executing: [C:\src\flutter\flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H   
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +2 ms] executing: [C:\src\flutter\flutter/] git tag --points-at HEAD  
[  +50 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.4
[   +9 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref--symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url
origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +85 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-refHEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Missing subcommand for "flutter build".

[   +3 ms] Run 'flutter -h' (or 'flutter <command> -h') for available
flutter
           commands and options.
[  +10 ms] ensureAnalyticsSent: 6ms
[  +21 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 64

**Comment by johnjiea** [comment]
Before I contacted you about this I search for the problem and one suggestion was to run flutter pub cache repair. I did and it made no difference.

**Comment by iapicca** [comment]
@johnjiea 
sorry I meant `flutter build <whatever platform> -v`

**Comment by johnjiea** [comment]
I tried flutter build windows -v but received     "build windows" is not currently supported. 
I have a Dell optiplex 9020 
i7-4770 3.40 GHz
16 GB
500gb SSD

Windows 10 Pro

What should have I put into <whatever platform> please.

**Comment by johnjiea** [comment]
the complete output was 

C:\[DemocracyGB]\democracygb 00-00-00>flutter build windows -v   
[ +119 ms] executing: [C:\src\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +70 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +1 ms] executing: [C:\src\flutter\flutter/] git tag --points-at HEAD
[  +43 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.4
[  +14 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +72 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +66 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +27 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.        
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +110 ms] Found plugin firebase_auth at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[  +12 ms] Found plugin firebase_auth_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[   +3 ms] Found plugin firebase_core at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[   +5 ms] Found plugin firebase_core_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +25 ms] Found plugin google_sign_in at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.3\
[   +4 ms] Found plugin google_sign_in_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.2\
[ +140 ms] Found plugin firebase_auth at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[   +3 ms] Found plugin firebase_auth_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[   +4 ms] Found plugin firebase_core at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +20 ms] Found plugin firebase_core_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[   +4 ms] Found plugin google_sign_in at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.3\
[  +22 ms] Found plugin google_sign_in_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.2\
[  +31 ms] Generating C:\[DemocracyGB]\democracygb 00-00-00\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +70 ms] "flutter windows" took 520ms.
[   +7 ms] "build windows" is not currently supported.
[  +22 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:49:7)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #10     _rootRun (dart:async/zone.dart:1190:13)
           #11     _CustomZone.run (dart:async/zone.dart:1093:19)
           #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +266 ms] ensureAnalyticsSent: 257ms
[   +2 ms] Running shutdown hooks
[  +25 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by iapicca** [comment]
@johnjiea 
I didn't realized you were building for windows
please make sure your are following the [docs](https://flutter.dev/desktop#additional-windows-requirements)
also your doctor is incomplete, can you provide the full output

**Comment by pedromassangocode** [comment]
Hi @johnjiea 
Please provide what was asked above.

**Comment by johnjiea** [comment]
I am in Australia and not at my computer all the time that is why there is a delay in me responding, sorry. When it wanted a platform I thought it wanted the my OS. my app is for mobile phones. I have rerun Flutter doctor see below

Microsoft Windows [Version 10.0.19041.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\[DemocracyGB]\democracygb 00-00-00>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.685], locale en-AU)
    • Flutter version 1.22.4 at C:\src\flutter\flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\IronW\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\IronW\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

C:\[DemocracyGB]\democracygb 00-00-00>

**Comment by johnjiea** [comment]
I have looked at the docs and under "Build a release app" it says "flutter build windows" so I ran  "flutter build windows -v" and get the following result 

C:\[DemocracyGB]\democracygb 00-00-00>flutter build windows -v
[ +128 ms] executing: [C:\src\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +1 ms] executing: [C:\src\flutter\flutter/] git tag --points-at HEAD
[  +46 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.4
[  +12 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +70 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +127 ms] Found plugin firebase_auth at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[   +9 ms] Found plugin firebase_auth_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[   +4 ms] Found plugin firebase_core at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +17 ms] Found plugin firebase_core_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[   +4 ms] Found plugin google_sign_in at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.3\
[   +4 ms] Found plugin google_sign_in_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.2\
[ +144 ms] Found plugin firebase_auth at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[   +4 ms] Found plugin firebase_auth_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[   +2 ms] Found plugin firebase_core at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[   +3 ms] Found plugin firebase_core_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +26 ms] Found plugin google_sign_in at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.3\
[   +4 ms] Found plugin google_sign_in_web at C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.2\
[ +116 ms] Generating C:\[DemocracyGB]\democracygb 00-00-00\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +73 ms] "flutter windows" took 679ms.
[   +6 ms] "build windows" is not currently supported.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:49:7)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #10     _rootRun (dart:async/zone.dart:1190:13)
           #11     _CustomZone.run (dart:async/zone.dart:1093:19)
           #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +318 ms] ensureAnalyticsSent: 270ms
[   +8 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

C:\[DemocracyGB]\democracygb 00-00-00>

**Comment by johnjiea** [comment]
Hi @iapicca and @pedromassangocode,

I have removed  
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.0
from pubspec.yaml

also the import statements and the call to the auth code. No code has been written yet accessing firestore data.

It now compiles and runs. What I do not understand this as I did not alter the version numbers of these imports or make any changes to the code between the last test on the 20/12/2020 (which ran and login by Google and email & password worked) and the first test on the 21/12/2020. I always run a test before making changes so if there is a problem I know I have created it in the changes I have just made.

I hope this helps you because it makes no sense to me unless versions are changed on the fly.

Thank you for looking into this for me, John

**Comment by johnjiea** [comment]
The problem had to be caused by a change in one or more of the following packages:
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.0 

For anyone else with this problem this is what I did:
1) Updated to their newest versions 
2) This caused a new compile problem to do with multiDex. 
3) Added "multiDexEnabled true"  and  
                "implementation 'com.android.support:C:1.0.3' "  in the dependencies folder
    of the app build.gradle file.

Following that it compiled and ran. :)

**Comment by pedromassangocode** [comment]
Hi @johnjiea 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
