### ISSUE TITLE
[State Restoration] RestorableListener causes Dart compiler crash upon hot reload

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#72700]
First discovered when migrating the gallery to make use of state restoration: https://github.com/flutter/gallery/pull/389. 

This issue is seen in the Reply and Shrine mini apps, both of which use state management packages (provider and scoped_model).

Reproducible sample: https://github.com/shihaohong/state_restoration_provider_crash

Steps to reproduce: 
1. Run the Flutter application
2. Make any changes to the code in your IDE (ie. adding spaces after a line of code) and save.
3. Hot Reload

Stack trace:
```bash
Unhandled exception:
root::package:hot_reload_crash/main.dart::_RestorableCounterState::@methods::package:flutter/src/widgets/restoration.dart::_debugAssertNotDisposed is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:192:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1201:51)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:559:14)
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:10821:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:10783:7)
#5      sortComponent (package:vm/kernel_front_end.dart:679:13)

#6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:656:5)
#7      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:766:13)
```

I also noticed that this only happens when hot reload is called in the Dart files where `_RestorableCounterState` is defined. The sample all only has one Dart file, but in the gallery app, this is more apparent since changes to files that do not contain the `RestorableListenable` class do not trigger the crash.

**Comment by shihaohong** [comment]
cc/ @goderbauer

**Comment by jonahwilliams** [comment]
Does this happen if you set `flutter config --no-experimental-invalidation-strategy`? If not, it might be an issue with the alternative invalidation

**Comment by shihaohong** [comment]
@jonahwilliams With `flutter config --no-experimental-invalidation-strategy`, the crash no longer occurs. I tested this behavior on both the gallery and https://github.com/shihaohong/state_restoration_provider_crash.

**Comment by jensjoha** [comment]
This should be fixed on the dart side with https://github.com/dart-lang/sdk/commit/5fac8d3d7168bf20bac107b61e4995b7976de68c. I can't say for sure when it rolls into flutter though.

**Comment by kf6gpe** [comment]
The fix for this was merged. Closing. Please re-open if it occurs again.
