### ISSUE TITLE
Ability to specify maxLines for Text and RichText

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#7271]
Android allows you to specify the max lines for a generic Text widget like so:
```
<TextView
    android:id="@+id/text"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"  
    android:maxLines="5" />
```

We should support this too.

**Comment by eseidelGoogle** [comment]
This is likely related to https://github.com/flutter/flutter/issues/4202.

**Comment by eseidelGoogle** [comment]
@mpcomplete has an in-progress patch.

**Comment by eseidelGoogle** [comment]
customer: leafy has indicated this is an important bug to them for Q1.

**Comment by mpcomplete** [comment]
Is any particular visual indicator preferred when text overflows beyond the max lines? Simply clipping is easy enough. I'm looking into adding ellipses at the end of the text, which is a bit more involved.

**Comment by mehmetf** [comment]
The preference is to add ellipses or fade (if it is easier).
