### ISSUE TITLE
Flutter URL Routing only works when app has been opened

### ISSUE THREAD

**Issue by felixwortmann** [flutter/flutter#72717]
## Problem
I try to make it possible to route the user according to the path in flutter web.
For example, I try to show a specific widget when I open `localhost/#/test`and another when opening `localhost/#/`

## Steps to Reproduce

I mostly used code from the flutter gallery repo. Especially I copied [this](https://github.com/flutter/gallery/blob/master/lib/routes.dart) file with the `onGenerateRoute`function.
If I open anything that starts with `localhost/#/` in my browser, while running my flutter app on localhost, I end up on my home page under /. I want to end up on another widget when I open `localhost/#/test` though.

**This does work when I first open `localhost/#/` and then change it to `localhost/#/test`, if I do not open `localhost/#/` first, but just open `localhost/#/test`, I instantly get redirected to `localhost/#/`.**

### Another thing to know:
When I log `settings.name` at the beginning of [onGenerateRoute](https://github.com/flutter/gallery/blob/master/lib/routes.dart), I always get "/" when first opening the app. When I just change the url, I get the full correct path and it opens the page.

The question in my opinion is: **Why does `settings,name == "/"`in [onGenerateRoute](https://github.com/flutter/gallery/blob/master/lib/routes.dart) when first opening the app?**

<details>
 <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.1 20C69 darwin-x64,
    locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/felixwortmann/bin/flutter
    • Framework revision 022b333a08 (5 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/felixwortmann/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/felixwortmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/felixwortmann/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/felixwortmann/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.88

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @felixwortmann 
Can you please provide your `flutter run --verbose` while routing and a complete reproducible minimal code sample
Thank you

**Comment by chunhtai** [comment]
This is by design, you will need to use navigator 2.0 to enable web deeplinking see https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

**Comment by felixwortmann** [comment]
I found a solution for my specific problem by using Navigator 2.0 so I am closing this.
