### ISSUE TITLE
SearchDelegate not working on Flutter Web on Android mobile device

### ISSUE THREAD

**Issue by AbhideepChakravarty** [flutter/flutter#72710]
## Steps to Reproduce

1. Created a Search functionality using SearchDelegate.
2. It worked during development, as expected.
3. Deployed on Firebase hosting.
4. Opened the deployed app on mobile browser.

**Expected results:** When I type something and tap enter button on Android soft keypad, search result should come.

**Actual results:** Search result does not come.

Now when instead of typing, if I use auto complete and tap the enter button on Android soft keypad, I get the result.

Why typed content is not working while auto complete is working? Also, everything works fine if I open the same web app on laptop. Problem is only on mobile device.

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by AbhideepChakravarty** [comment]
Hi @pedromassangocode , 

I am developing a web application. Its debugging happens on Chrome on laptop. On laptop, it works properly. Post deploy it does not work on Android mobile (as of now). But here is what you asked for:

flutter doctor -v
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.24.0-10.2.pre at d:\flutter
    • Framework revision 022b333a08 (5 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\App\Android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\App\Android      
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter       
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.0)       
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

I am not giving flutter run as everything works fine in development (or even in production) mode on laptop, I would recommend this:
1. Please visit https://fs-restaurant.web.app/#/menu/AWIN-DJ7F on your Android mobile Chrome browser.
2. Click the search button and try to search chicken, soup or tandoori, or anything you wish.

This approach will give you the experience. About code, I have given you access on the codebase. The lib/ui/menu_page.dart has the code. Again, it works well if we use auto complete, not when we type. Found to be working on iOS mobile and has problem in Android.

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
I need a code that I can build a test and reproduce the issue by myself and as  I have no idea what the restaurant code your website is asking for.
Thank you

**Comment by AbhideepChakravarty** [comment]
@pedromassangocode I have added you in my GitHub repository with READ access. You can have the full source code. Please check your email.
![image](https://user-images.githubusercontent.com/9032142/102867440-ca810600-445e-11eb-8d5a-6188a49df3f2.png)

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
You should provide an open sample code so that anyone who wants to fix this issue can use it to verify the issue and help him write the test cases for the PR that fixes it.

**Comment by AbhideepChakravarty** [comment]
Here is the code:


import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:restaurants/helper/firebase.dart';

class MenuPageUI extends StatefulWidget {
  final String menuCode;
  MenuPageUI({Key key, this.menuCode}) : super(key: key);

  @override
  _MenuPageUIState createState() => _MenuPageUIState();
}

class _MenuPageUIState extends State<MenuPageUI> {
  List<SearchListItemContent> searchableFoodItems;

  @override
  Widget build(BuildContext context) {
    FirebaseFirestore firestore = FirebaseInitializer.firestore;
    DocumentReference menu =
        firestore.collection("menus").doc(widget.menuCode.toUpperCase());
    return StreamBuilder<DocumentSnapshot>(
      stream: menu.snapshots(),
      builder: (context, menu) {
        //print("Inside builder");
        Widget widget = Center(child: CircularProgressIndicator());
        if (!menu.hasData && menu.connectionState == ConnectionState.active) {
          //print("Inside error");
          widget = Scaffold(
            appBar: AppBar(title: Text("Error!!")),
            body: Center(
                child: Text("We could not load the " + " menu. Please retry.")),
          );
        } else if (menu.connectionState == ConnectionState.active &&
            menu.hasData) {
          ////print("Building body");
          widget = getBody(menu, context);
        } else if (!menu.hasData &&
            menu.connectionState == ConnectionState.waiting) {
          //print("Inside progress");
          widget = Center(
            child: CircularProgressIndicator(),
          );
        }
        return widget;
      },
    );
  }

  Widget getBody(AsyncSnapshot<DocumentSnapshot> menu, BuildContext context) {
    var scaffold = Scaffold(
      appBar: AppBar(
        title: Text(menu.data.data()['name'].toString()),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () {
              showSearch(
                  context: context,
                  delegate: FoodItemSearch(this.searchableFoodItems));
            },
          )
        ],
      ),
      body: buildSections(menu, context),
    );
    return scaffold;
  }

  buildSections(AsyncSnapshot<DocumentSnapshot> menu, BuildContext context) {
    Query sections = menu.data.reference.collection("sections").orderBy("seq");
    return StreamBuilder<QuerySnapshot>(
        stream: sections.snapshots(),
        builder: (context, sections) {
          Widget widget;
          if (!sections.hasData &&
              sections.connectionState == ConnectionState.active) {
            widget = Center(
              //appBar: AppBar(title: Text("Error!!")),
              child: Text("We could not load the " + "menu. Please retry."),
            );
          } else if (sections.hasData) {
            widget = getSections(sections, context);
          } else {
            widget = Center(
              child: CircularProgressIndicator(),
            );
          }
          return widget;
        });
    //return Text("Trying to build sections");
  }

  Widget getSections(
      AsyncSnapshot<QuerySnapshot> sections, BuildContext context) {
    List<Widget> widgets = List<Widget>();
    this.searchableFoodItems = List<SearchListItemContent>();
    sections.data.docs.forEach((section) {
      Widget sectionWidget = Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
          decoration: BoxDecoration(
            border: Border(
              bottom: BorderSide(width: 5.0, color: Colors.black),
            ),
          ),
          //alignment: AlignmentGeometry(),
          child: Text(
            section['name'],
            textAlign: TextAlign.left,
            style: TextStyle(fontSize: 28.0),
          ));
      Widget foodItems = getFoodItems(section, context, section['name']);
      widgets.add(sectionWidget);
      widgets.add(foodItems);
    });
    ////print("List size " + widgets.length.toString());
    return SingleChildScrollView(
      child: Column(
        children: widgets,
      ),
    );
  }

  Widget getFoodItems(
      QueryDocumentSnapshot element, BuildContext context, String sectionName) {
    CollectionReference foodItems = element.reference.collection("fooditems");
    var widget = StreamBuilder<QuerySnapshot>(
        stream: foodItems.snapshots(),
        builder: (context, foodItems) {
          Widget widget;
          if (!foodItems.hasData &&
              foodItems.connectionState == ConnectionState.done) {
            widget = Center(
              child: Text("We could not load the food items. Please retry."),
            );
          } else if (foodItems.hasData) {
            widget = getFoodItemWidget(foodItems, context, sectionName);
          } else {
            widget = Center(
              child: CircularProgressIndicator(),
            );
          }
          return widget;
        });
    return widget;
  }

  Widget getFoodItemWidget(AsyncSnapshot<QuerySnapshot> foodItems,
      BuildContext context, String sectionName) {
    List<Widget> listTile = List<Widget>();
    foodItems.data.docs.forEach((DocumentSnapshot foodItem) {
      this.searchableFoodItems.add(SearchListItemContent(
          title: foodItem.data()['name'],
          subTitle: foodItem.data()['desc'],
          price: foodItem.data()['price'],
          section: sectionName));
      Widget tile = Container(
          margin: EdgeInsets.all(8.0),
          decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(10.0)),
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                    color: Colors.black26, spreadRadius: 2.0, blurRadius: 5.0)
              ]),
          width: MediaQuery.of(context).size.width,
          child: Row(mainAxisSize: MainAxisSize.max, children: <Widget>[
            Expanded(
              child: getFoodItemTile(foodItem),
            ),
          ]));
      listTile.add(tile);
    });
    return Column(
      children: listTile,
    );
    //return foodItemList;
  }

  Widget getFoodItemTile(DocumentSnapshot foodItem) {
    ListTile listTile;
    if (foodItem.data()['desc'] != null) {
      listTile = ListTile(
          trailing: Text(foodItem.data()['price']),
          title: Text(foodItem.data()['name']),
          subtitle: Text(foodItem.data()['desc']));
    } else {
      listTile = ListTile(
        trailing: Text(foodItem.data()['price']),
        title: Text(foodItem.data()['name']),
      );
    }
    return listTile;
  }
}

class SearchListItemContent {
  final String title;
  final String subTitle;
  final String price;
  final String section;

  SearchListItemContent({this.title, this.subTitle, this.price, this.section});
}

class FoodItemSearch extends SearchDelegate<String> {
  final List<SearchListItemContent> searchableList;
  FoodItemSearch(this.searchableList);
  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      /*IconButton(
        icon: Icon(Icons.search),
        onPressed: () {
          print("On press search action:")
          build(context);
          body.dele

        },
      ),*/
      IconButton(
        icon: Icon(Icons.close),
        onPressed: () {
          query = "";
        },
      ),
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
          icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
      onPressed: () {
        close(context, null);
      },
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    Widget searchResult;
    if (query.length <= 2) {
      searchResult = Center(
          child: Text(
        "Type at least 3 character to perform a search.",
        style: TextStyle(color: Colors.red[800]),
      ));
    } else {
      List<Widget> resultSet = findMatch(context);
      if (resultSet.isEmpty) {
        searchResult = Center(
            child: Text(
          "We do not have what you are searching for!",
          style: TextStyle(color: Colors.red[800]),
        ));
      } else {
        searchResult = ListView(
          children: findMatch(context),
        );
      }
    }
    return searchResult;
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Text("");
  }

  List<Widget> findMatch(BuildContext context) {
    return this
        .searchableList
        .where((item) {
          return (item.title.toString().toLowerCase().contains(query) ||
              item.subTitle.toString().toLowerCase().contains(query));
        })
        .toList()
        .map((item) {
          return getSearchListItem(item, context);
        })
        .toList();
  }

  Widget getSearchListItem(
      SearchListItemContent foodItem, BuildContext context) {
    return Container(
      margin: EdgeInsets.all(8.0),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(10.0)),
          color: Colors.white,
          boxShadow: [
            BoxShadow(color: Colors.black26, spreadRadius: 2.0, blurRadius: 5.0)
          ]),
      width: MediaQuery.of(context).size.width,
      child: getFoodItemTileForSearch(foodItem),
    );
  }

  ListTile getFoodItemTileForSearch(SearchListItemContent foodItem) {
    ListTile listTile;
    if (foodItem.subTitle != null) {
      listTile = ListTile(
        trailing: Text(foodItem.price),
        title: Text(foodItem.title),
        subtitle: Text(foodItem.section + "\n" + foodItem.subTitle),
        isThreeLine: true,
      );
    } else {
      listTile = ListTile(
        trailing: Text(foodItem.price),
        title: Text(foodItem.title),
        subtitle: Text(foodItem.section),
      );
    }
    return listTile;
  }
}

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
Please provide a minimal complete reproducible code sample that does not contains third-party plugin/packages?
Thank you

**Comment by AbhideepChakravarty** [comment]
Hi @pedromassangocode 
How does a third party library, that too firestore and data from firestore is a problem in understanding the issue that when in Android chrome, we press enter after typing something in search bar without auto complete, nothing happens. I gave you source code. I gave you where it is deployed. Do you want me to write a separate one pager application just to show you the same?
In case of auto complete and window switch it works.

Give me some time so that I can write a code into which someone can look only when it is the code according to them.

@ianloic @anaisbetts @sgraham

**Comment by AbhideepChakravarty** [comment]
Here you go:

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  List<String> cities = ["Tokyo", "Toranto", "London", "Lonawala"];
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        actions: [
          IconButton(
            icon: Icon(Icons.search),
            onPressed: () {
              showSearch(context: context, delegate: CitySearch(this.cities));
            },
          )
        ],
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Click the search button and try searching for something stating with lon or to. On Android, press enter but dont use autocomplete.\n\n Now switch app and come back to this app and see it works.',
            ),
          ],
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class CitySearch extends SearchDelegate<String> {
  final List<String> cities;

  CitySearch(this.cities);

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
        icon: Icon(Icons.close),
        onPressed: () {
          query = "";
        },
      ),
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
          icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
      onPressed: () {
        close(context, null);
      },
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    Widget searchResult;
    if (query.length <= 1) {
      searchResult = Center(
          child: Text(
        "Type at least 2 character to perform a search.",
        style: TextStyle(color: Colors.red[800]),
      ));
    } else {
      List<Widget> resultSet = findMatch(context);
      if (resultSet.isEmpty) {
        searchResult = Center(
            child: Text(
          "We do not have what you are searching for!",
          style: TextStyle(color: Colors.red[800]),
        ));
      } else {
        searchResult = ListView(
          children: findMatch(context),
        );
      }
    }
    return searchResult;
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Text("");
  }

  List<Widget> findMatch(BuildContext context) {
    return this
        .cities
        .where((item) {
          return (item.toString().toLowerCase().contains(query.toLowerCase()));
        })
        .toList()
        .map((item) {
          return getSearchListItem(item, context);
        })
        .toList();
  }

  Widget getSearchListItem(String foodItem, BuildContext context) {
    return Container(
      margin: EdgeInsets.all(8.0),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(10.0)),
          color: Colors.white,
          boxShadow: [
            BoxShadow(color: Colors.black26, spreadRadius: 2.0, blurRadius: 5.0)
          ]),
      width: MediaQuery.of(context).size.width,
      child: Text(foodItem),
    );
  }
}


The app is deployed at https://search-flutter.web.app

Make it work in iPhone and Android. iPhone will work fine. Android wont.
@pedromassangocode @ianloic @anaisbetts @sgraham

**Comment by AbhideepChakravarty** [comment]
Any updates on the issue? @pedromassangocode @ianloic @anaisbetts @sgraham

**Comment by pedromassangocode** [comment]
Reproducible on latest master as well.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.137 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 8f5d0371af (2 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005                         • android-arm64  • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by AbhideepChakravarty** [comment]
@pedromassangocode When probably the fix will be released?

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
I'm not sure when, but it is open for anyone to fix it :)

**Comment by AbhideepChakravarty** [comment]
@pedromassangocode Can you help me on where the bug is in the code? Possible package and files and how to setup three development environment. I will see if I can get it fixed.

**Comment by pedromassangocode** [comment]
Hi @AbhideepChakravarty 
This may probably be an engine issue (I'm not really sure), you can start by reading the [contributor guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).

**Comment by AbhideepChakravarty** [comment]
@pedromassangocode Not only this, I tried implementing Search without SearchDelegate, and I am facing weird errors. I guess the TextField itself is screwed up, which in turn is impacting SearchDelegate. Just touching the text field triggers its methods. Its so bad!! I am not able to release the search feature because of this.

**Comment by tapizquent** [comment]
I can confirm, SearchDelegate is not working for Flutter Web. It does not register keyboard changes and nothing updates.

**Comment by AbhideepChakravarty** [comment]
And I had to release the feature only for iPhone users. For Android users, the feature does not show up. Kind of killing the whole purpose of hybrid app development.

**Comment by mdebbar** [comment]
> Can you help me on where the bug is in the code? Possible package and files and how to setup three development environment. I will see if I can get it fixed.

@AbhideepChakravarty I could be wrong but my hunch says the problem is happening because we try to re-focus the input field every time it loses focus ([here](https://github.com/flutter/engine/blob/70d08c6ac331f0df3f3350b42530c46f84211de8/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1194)). The reason we do that is because we don't want the field to lose focus until the framework/app decides it should lose focus.

That re-focus logic might be intervening with the input actions, which are triggered when the "ENTER" key is captured [here](https://github.com/flutter/engine/blob/70d08c6ac331f0df3f3350b42530c46f84211de8/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L928-L932).

That's where I would start looking.

To setup your environment, please take a look at these wiki pages:
* https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
* https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web

Please let me know if you need help.

**Comment by AbhideepChakravarty** [comment]
Seeing the updates, I dont think I am right candidate to give it a fix. I dont understand the difference between framework and engine here in this context.

**Comment by AbhideepChakravarty** [comment]
@mdebbar The whole search functionality is non functional on Android. Shouldn't it be P2, instead of P4? Assuming P1 is highest priority. Or do we have separate scale for severity?

**Comment by AbhideepChakravarty** [comment]
Any updates on this feature which does not work at all and still released and on top of it, it is marked as P4?

Why a completely non functional widget bug is marked as P4? It should be P1. Isnt it?

**Comment by MattyBoy4444** [comment]
Still broken.

**Comment by AbhideepChakravarty** [comment]
Its 7 months guys !!! In another 70 months, it wont be fixed if it remains at P4. For god sake, fix it !!

**Comment by tapizquent** [comment]
> Its 7 months guys !!! In another 70 months, it wont be fixed if it remains at P4. For god sake, fix it !!

I don't mean to be rude, but this is an open source project. You can, if you need to, fix it yourself and open a pull request.
All the code is there.

**Comment by AbhideepChakravarty** [comment]
No, you are not at all rude. It's just that the bug is in some engine,
side. Additionally, I am not a frontend developer and under special
situations I am writing frontend. If I was capable of fixing this bug, I
would not have waited. My concern is that if it is P4, it will never be
solved. It must not be P4 because a functionality DOES NOT work at all.
Changing the priority would bring it in attention and someone from the
engine side, would fix it. If it remains P4, it will remain in open state
for unlimited time. You certainly understand what if search does not work
in an application. Its severe by functionality and certainly severe by
priority as the functionally DOES NOT WORK AT ALL in a given scenario.
Someone please make it P2.

**Comment by AbhideepChakravarty** [comment]
@pedromassango Can you please get the severity increased from P4 to, may be P2.

**Comment by AbhideepChakravarty** [comment]
The P4 will never be resolved. No one bothers about anything less than P3. Please close this bug. Keeping it open and making it stale is useful for no one. @pedromassangocode

**Comment by maheshmnj** [comment]
@AbhideepChakravarty  I verified the issue on the latest master 3.7 and it seems to work fine. Please see the deployed demo app here https://fluttersearch.netlify.app/#/


<details>
<summary>deployed code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final int _counter = 0;

  List<String> cities = ["Tokyo", "Toranto", "London", "Lonawala"];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [
          IconButton(
            icon: const Icon(Icons.search),
            onPressed: () {
              showSearch(context: context, delegate: CitySearch(cities));
            },
          )
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'Click the search button and try searching for something stating with lon or to. On Android, press enter but dont use autocomplete.\n\n Now switch app and come back to this app and see it works.',
            ),
          ],
        ),
      ),
    );
  }
}

class CitySearch extends SearchDelegate<String> {
  final List<String> cities;

  CitySearch(this.cities);

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
        icon: const Icon(Icons.close),
        onPressed: () {
          query = "";
        },
      ),
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
          icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
      onPressed: () {
        close(context, '');
      },
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    Widget searchResult;
    if (query.length <= 1) {
      searchResult = Center(
          child: Text(
        "Type at least 2 character to perform a search.",
        style: TextStyle(color: Colors.red[800]),
      ));
    } else {
      List<Widget> resultSet = findMatch(context);
      if (resultSet.isEmpty) {
        searchResult = Center(
            child: Text(
          "We do not have what you are searching for!",
          style: TextStyle(color: Colors.red[800]),
        ));
      } else {
        searchResult = ListView(
          children: findMatch(context),
        );
      }
    }
    return searchResult;
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return const Text("");
  }

  List<Widget> findMatch(BuildContext context) {
    return cities
        .where((item) {
          return (item.toString().toLowerCase().contains(query.toLowerCase()));
        })
        .toList()
        .map((item) {
          return getSearchListItem(item, context);
        })
        .toList();
  }

  Widget getSearchListItem(String foodItem, BuildContext context) {
    return Card(
      child: ListTile(
        title: Text(foodItem),
        onTap: () {
          close(context, foodItem);
        },
      ),
    );
  }
}
```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
</details>

**Comment by AbhideepChakravarty** [comment]
@maheshmnj I will test the same and revert with the status whatever it is. Thanks for the update.
