### ISSUE TITLE
Design Question: icon margin in InputContainer, why?

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7272]
> tl;dr: Why is there a right margin on the `Container` around the `Icon` in an `InputContainer`? What was the motivation behind this design choice?

Just a question about the choice to add [`16.0` to the right margin](https://github.com/flutter/flutter/blob/bf289a2aeafe3081f37e30b23e964f91b09a21fc/packages/flutter/lib/src/material/input.dart#L361) of the icon in the `InputContainer` class. 

This generates something that looks like below:
![simulator screen shot dec 15 2016 5 10 29 pm](https://cloud.githubusercontent.com/assets/2818462/21244273/dcfce294-c2ea-11e6-8688-4101a11fb9ef.png)

Creating this unbalanced look, which is especially noticable when there is no padding around the screen edges:
![simulator screen shot dec 15 2016 5 23 30 pm](https://cloud.githubusercontent.com/assets/2818462/21244339/3a7f4f56-c2eb-11e6-829b-9146d43e9537.png)

If there were *no* right margin on the `Container` it would look like below, which seems more balanced:
![simulator screen shot dec 15 2016 5 24 43 pm](https://cloud.githubusercontent.com/assets/2818462/21244404/76d3395e-c2eb-11e6-8132-cdd1c7ad955f.png)

**Comment by eseidelGoogle** [comment]
This is probably a question for @Hixie or @mpcomplete

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
I assume that the 16 pixel margin on the icon's right is intended to match the text field examples that appear in the material design spec: https://material.io/guidelines/components/text-fields.html#text-fields-single-line-text-field

![components_textfields_single7](https://cloud.githubusercontent.com/assets/1377460/21269679/8eb0cc08-c368-11e6-9446-01dfdf9b09a7.png)

I don't think the spec requires the icon's right margin. I agree that we should probably leave it out.
