### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by Saleh-h-m-abbas** [flutter/flutter#72720]
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#a2987](dirty, dependencies: [HeroControllerScope], state: NavigatorState#d8229(tickers: tracking 2 tickers)):

'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

**Comment by TahaTesser** [comment]
Hi @Saleh-h-m-abbas 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by chunhtai** [comment]
cc @chunhtai

**Comment by Saleh-h-m-abbas** [comment]
salehabbas@Salehs-MacBook-Pro ActHubBeta % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.22.5 at /Users/salehabbas/Developer/flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/salehabbas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • 832E72F3-09FE-4559-8A76-62F7CDC60B67 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)

! Doctor found issues in 1 category.
salehabbas@Salehs-MacBook-Pro ActHubBeta % 


> Hi @Saleh-h-m-abbas
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

**Comment by Saleh-h-m-abbas** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.22.5 at /Users/salehabbas/Developer/flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/salehabbas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

 
[✓] Connected device (2 available)            
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • 832E72F3-09FE-4559-8A76-62F7CDC60B67 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)

! Doctor found issues in 1 category.

**Comment by Saleh-h-m-abbas** [comment]
> Hi @Saleh-h-m-abbas
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

I/Gralloc4(14950): mapper 4.x is not supported
D/HostConnection(14950): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer(14950): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation(14950): eglCreateContext: 0xf3d628a0: maj 3 min 0 rcv 3
D/EGL_emulation(14950): eglMakeCurrent: 0xf3d628a0: ver 3 0 (tinfo 0xbf8437f0) (first time)
D/HostConnection(14950): createUnique: call
D/HostConnection(14950): HostConnection::get() New Host Connection established 0xf3d43c70, tid 15020
D/goldfish-address-space(14950): allocate: Ask for block of size 0x100
D/goldfish-address-space(14950): allocate: ioctl allocate returned offset 0x3fda58000 size 0x2000
D/HostConnection(14950): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
I/.ngn.ActHubBet(14950): Background young concurrent copying GC freed 9325(583KB) AllocSpace objects, 8(964KB) LOS objects, 47% free, 6867KB/12MB, paused 117.320ms total 597.270ms
D/HostConnection(14950): HostConnection::get() New Host Connection established 0xf3d42b60, tid 15020
D/HostConnection(14950): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(14950): eglMakeCurrent: 0xf3d61560: ver 3 0 (tinfo 0xbf80c530) (first time)
I/OpenGLRenderer(14950): Davey! duration=3020ms; Flags=1, IntendedVsync=49948751560534, Vsync=49948901560528, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=49948910196125, AnimationStart=49948910244125, PerformTraversalsStart=49948910426125, DrawStart=49951266121125, SyncQueued=49951271762125, SyncStart=49951280825125, IssueDrawCommandsStart=49951282712125, SwapBuffers=49951677643125, FrameCompleted=49951781601125, DequeueBufferDuration=34832000, QueueBufferDuration=5588000, GpuCompleted=72904454231491230, 
I/Choreographer(14950): Skipped 174 frames!  The application may be doing too much work on its main thread.
I/flutter (14950): setState() or markNeedsBuild() called during build.
I/flutter (14950): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter (14950): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (14950):   Overlay-[LabeledGlobalKey<OverlayState>#34526]
I/flutter (14950): The widget which was currently being built when the offending call was made was:
I/flutter (14950):   Builder

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ActivityNotifier:
setState() or markNeedsBuild() called during build.

This _InheritedProviderScope<ActivityNotifier> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedProviderScope<ActivityNotifier>
  value: Instance of 'ActivityNotifier'
  listening to value
The widget which was currently being built when the offending call was made was: _BodyBuilder
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      _InheritedProviderScopeElement.markNeedsNotifyDependents (package:provider/src/inherited_provider.dart:496:5)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
#4      ActivityNotifier.activityRefreshMethod (package:ActHubBeta/notifier/ActivityNotifier.dart:21:5)
...
The ActivityNotifier sending notification was: Instance of 'ActivityNotifier'
====================================================================================================
W/DynamiteModule(14950): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(14950): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(14950): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/.ngn.ActHubBet(14950): The ClassLoaderContext is a special shared library.
I/.ngn.ActHubBet(14950): The ClassLoaderContext is a special shared library.
D/nativeloader(14950): classloader namespace configured for unbundled product apk. library_path=/product/priv-app/PrebuiltGmsCore/lib/x86:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/product/lib:/system/product/lib
W/.ngn.ActHubBet(14950): Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden field Ldalvik/system/DexPathList;->systemNativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ldalvik/system/DexPathList;->makePathElements(Ljava/util/List;)[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
V/NativeCrypto(14950): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/.ngn.ActHubBet(14950): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/ProviderInstaller(14950): Installed default security provider GmsCore_OpenSSL
W/.ngn.ActHubBet(14950): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/.ngn.ActHubBet(14950): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
I/zzbz    (14950): Making Creator dynamically
W/Gralloc4(14950): allocator 3.x is not supported
I/DynamiteModule(14950): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:201817000
I/DynamiteModule(14950): Selected remote version of com.google.android.gms.maps_dynamite, version >= 201817000
V/DynamiteModule(14950): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/.ngn.ActHubBet(14950): Unsupported class loader
W/.ngn.ActHubBet(14950): Unsupported class loader
I/Google Maps Android API(14950): Google Play services client version: 12451000
I/Google Maps Android API(14950): Google Play services package version: 201817022
I/.ngn.ActHubBet(14950): Background concurrent copying GC freed 87348(5904KB) AllocSpace objects, 12(1712KB) LOS objects, 49% free, 5759KB/11MB, paused 854us total 259.319ms
W/Google Maps Android API(14950): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where indoor is not supported, isIndoorEnabled() will continue to return the value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'. The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes unavailable on those map types.
D/HostConnection(14950): HostConnection::get() New Host Connection established 0xf3d7e280, tid 15167
D/HostConnection(14950): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(14950): eglCreateContext: 0xf3d7fa20: maj 1 min 0 rcv 1
D/EGL_emulation(14950): eglMakeCurrent: 0xf3d7fa20: ver 1 0 (tinfo 0xbf81c6b0) (first time)
D/EGL_emulation(14950): eglMakeCurrent: 0xf3d7fa20: ver 1 0 (tinfo 0xbf81c6b0) (first time)
W/DynamiteModule(14950): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(14950): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule(14950): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/.ngn.ActHubBet(14950): Unsupported class loader
W/.ngn.ActHubBet(14950): Unsupported class loader
I/.ngn.ActHubBet(14950): Background young concurrent copying GC freed 27686(2304KB) AllocSpace objects, 24(1404KB) LOS objects, 0% free, 13MB/13MB, paused 4.690ms total 967.133ms
I/.ngn.ActHubBet(14950): Background concurrent copying GC freed 14074(1918KB) AllocSpace objects, 141(5956KB) LOS objects, 49% free, 14MB/28MB, paused 11.418ms total 1.425s

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ActivityNotifier:
setState() or markNeedsBuild() called during build.

This _InheritedProviderScope<ActivityNotifier> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedProviderScope<ActivityNotifier>
  value: Instance of 'ActivityNotifier'
  listening to value
The widget which was currently being built when the offending call was made was: _BodyBuilder
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      _InheritedProviderScopeElement.markNeedsNotifyDependents (package:provider/src/inherited_provider.dart:496:5)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
#4      ActivityNotifier.profileRefresh (package:ActHubBeta/notifier/ActivityNotifier.dart:156:5)
...
The ActivityNotifier sending notification was: Instance of 'ActivityNotifier'
====================================================================================================

======== Exception caught by foundation library ====================================================
setState() or markNeedsBuild() called during build.
====================================================================================================

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ActivityNotifier:
setState() or markNeedsBuild() called during build.

This _InheritedProviderScope<ActivityNotifier> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedProviderScope<ActivityNotifier>
  value: Instance of 'ActivityNotifier'
  listening to value
The widget which was currently being built when the offending call was made was: _BodyBuilder
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      _InheritedProviderScopeElement.markNeedsNotifyDependents (package:provider/src/inherited_provider.dart:496:5)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
#4      ActivityNotifier.activityRefreshMethod (package:ActHubBeta/notifier/ActivityNotifier.dart:21:5)
...
The ActivityNotifier sending notification was: Instance of 'ActivityNotifier'
====================================================================================================

**Comment by Saleh-h-m-abbas** [comment]
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 4,342ms.
W/.ngn.ActHubBet( 6656): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
I/flutter ( 6656): setState() or markNeedsBuild() called during build.
I/flutter ( 6656): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter ( 6656): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 6656):   Overlay-[LabeledGlobalKey<OverlayState>#ffa3e]
I/flutter ( 6656): The widget which was currently being built when the offending call was made was:
I/flutter ( 6656):   Builder

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#4c57d](dirty, dependencies: [HeroControllerScope], state: NavigatorState#ddfb4(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4151 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/salehabbas/Developer/ActHubBeta/lib/main.dart:33:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:4151:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
...
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
setState() called after dispose(): OverlayState#dab16(lifecycle state: defunct, not mounted, entries: [OverlayEntry#fbf2f(opaque: true; maintainState: false), OverlayEntry#a6a0f(opaque: false; maintainState: true), OverlayEntry#4e38b(opaque: true; maintainState: false), OverlayEntry#8a493(opaque: false; maintainState: true)])

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1208:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1243:6)
#2      OverlayState._didChangeEntryOpacity (package:flutter/src/widgets/overlay.dart:441:5)
#3      OverlayEntry.opaque= (package:flutter/src/widgets/overlay.dart:91:15)
#4      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart:179:32)
...
The AnimationController notifying status listeners was: AnimationController#16c2e(⏭ 1.000; paused; for MaterialPageRoute<dynamic>(null))
====================================================================================================

**Comment by TahaTesser** [comment]
Hi @Saleh-h-m-abbas 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
