### ISSUE TITLE
The terminal process "C:\Windows\system32\cmd.exe" terminated with exit code: 1.

### ISSUE THREAD

**Issue by MJahangir82** [flutter/flutter#72724]
Hello Team,

Today is my first day on Flutter. I am trying to install flutter on a windows 7 machine. I have followed the steps given below.

1) C:\src>git clone https://github.com/flutter/flutter.git -b stable
2) add Flutter to the PATH environment variable
3) flutter doctor ( Error )

I run the flutter doctor command on CMD it terminates without showing anything so I didn't know what is going on. then I try to use the Visual Studio Code terminal and getting "The terminal process "C:\Windows\system32\cmd.exe" terminated with exit code: 1."

could you please help me to fix it? Thanks

**Comment by MJahangir82** [comment]
![image](https://user-images.githubusercontent.com/22867317/102870946-8cd0ad00-445f-11eb-8002-af5b1984f5c6.png)

since terminal terminates in a fraction of second, i recoreded my screen to see the message. So i came to know its because of powershell version. but there should be a proper message handeling instead of terminating.

**Comment by Jamil-code** [comment]
Same problem, it keeps crashing, am using Windows 8.1, and I've followed all the procedures.... Someone help us pls

**Comment by AlejoWally666** [comment]
hello, I had the same problem in Windows 8 and I solved them by updating Windows PowerShell to `version 5.1 `and it worked fine.
