### ISSUE TITLE
SDK problem

### ISSUE THREAD

**Issue by prince-mou** [flutter/flutter#72721]
```BASH
Downloading Dart SDK from Flutter engine 7983c6fda0b99fd8417b5ee89e227675e7d50bd2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    296      0 --:--:-- --:--:-- --:--:--   296
[/home/comboni/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/comboni/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/comboni/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/comboni/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

**Comment by TahaTesser** [comment]
Hi @prince-mou 
Did you download zip or  `git clone -b stable https://github.com/flutter/flutter.git`
Which channel you've downloaded? 

The problem might be double zip extensions in your logs
```
cache/dart-sdk-linux-x64.zip.zip
```
Please try again with

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by prince-mou** [comment]
Hello

Thanks for your reply .

I  still have the same problem even after i extracting the zip file.

If there's any alternatives solutions please feed me .

Thanks you .

**Comment by TahaTesser** [comment]
Hi @prince-mou 
Please delete your existing setup and clone fresh using `git clone -b stable https://github.com/flutter/flutter.git`, you don't to need to unzip any file using this method
