### ISSUE TITLE
CodeLabs - Building beautiful UIs with Flutter issues

### ISSUE THREAD

**Issue by DevDwarf** [flutter/flutter#72745]
Unsure where to post this as the Codelabs `Report a Mistake` button redirects me here, but I found two mistakes on the [Add a ui for composing messages](https://codelabs.developers.google.com/codelabs/flutter#4) step on the `Building beautiful UIs with Flutter issues` Codelab.

So in the example below it keeps referencing `Row` at 1 and 4 but it should be `Textfield`

<img width="574" alt="1" src="https://user-images.githubusercontent.com/26380322/102819401-13dc4180-43dc-11eb-9581-c8eb8003cc23.png">

This one below is just a spelling mistake in `IconThem` where it should be `IconTheme`

<img width="344" alt="2" src="https://user-images.githubusercontent.com/26380322/102819621-77666f00-43dc-11eb-8dfa-63b71bdd0035.png">

Not major issues and again unsure where to post things like this as the Codelabs issue reporter redirects to here, but just thought you should know.

**Comment by darshankawar** [comment]
@DevDwarf 
There's already similar issue opened in Flutter's website repo : https://github.com/flutter/website/issues/4881
Please follow-up there for updates.
Closing from here.
