### ISSUE TITLE
[tool_crash] RPCError: Bad state: The client closed with pending request "_createDevFS".

### ISSUE THREAD

**Issue by Kirstygoodary** [flutter/flutter#72753]
## Command
```
flutter run
```

## Steps to Reproduce
1. Using IOS 14.3, Iphone 12 pro
2. Ran flutter run. Ran flutter doctor and flutter clean, no issues raised. 
3. Tried changing channels.

## Logs
RPCError
```

```
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/Kirsty/Developer/flutter
    • Framework revision 63062a6443 (8 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Kirsty/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Users/Kirsty/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • 32686128-F88F-4D59-BFC8-ED9CFC4D8F0B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818

Crash report: 

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

RPCError: _createDevFS: (-32000) Bad state: The client closed with pending request "_createDevFS".

```
```

## flutter doctor

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/Kirsty/Developer/flutter
    • Framework revision 63062a6443 (8 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Kirsty/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Users/Kirsty/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • 32686128-F88F-4D59-BFC8-ED9CFC4D8F0B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @Kirstygoodary 
Can you provide the full logs of the crash?

**Comment by jmagman** [comment]
This is in `_createDevFS`, https://github.com/flutter/flutter/issues/70579 is in `_flutter.listViews`.

@Kirstygoodary Can you attach the log that was generated at the same time? We're missing the stack trace.

**Comment by Kirstygoodary** [comment]
Hi Jenn

Sorry, I'm relatively new to flutter. Where can I find this?

Thanks

Kirsty

**Comment by jmagman** [comment]
@Kirstygoodary when it crashes it will say something like "A crash report has been written to flutter_01.log".  Can you attach that file (in the working directory where you were when it crashed) if it's still around?

**Comment by Kirstygoodary** [comment]
Hi Jenn

Thanks, here you go. I hope this is what you were looking for :)

**Comment by jmagman** [comment]
@Kirstygoodary It didn't upload, can you try again from the GitHub web UI?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
