### ISSUE TITLE
Task :connectivity:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by prakash-indorkar** [flutter/flutter#72751]
Hi there, I'm not able to build for release. It works on debug mode. Due to this error, I can not release my app.

See the complete report on Gradle scan.

https://scans.gradle.com/s/cdkyow3cp4jpo

Thank you., Prakash

**Comment by sidrao2006** [comment]
Hello @prakash-indorkar ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you!

**Comment by darshankawar** [comment]
@prakash-indorkar 
What Version are you trying to build for release ? Please provide `flutter build apk --verbose`.

**Comment by prakash-indorkar** [comment]
Hi, @sidrao2006 and @darshankawar 

Surprisingly it built successfully today, after changing my JDK version from 14 to 1.8. I read your suggestion on one of the similar issues. I did install the jdk1.8 but forgot to change JAVA_HOME which was pointing on jdk14.

Thank you so much for your attention. I like being part of the flutter community.

**Comment by darshankawar** [comment]
Closing this as non-issue based on comment above.
