### ISSUE TITLE
`flutter upgrade` runs `buildUnlinkedForPackages`, but nothing else does

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7276]
Running `flutter upgrade` on a repo that you just cloned and ran `flutter doctor` and `flutter analyze` on should be a no-op. However, it's not, because we run `buildUnlinkedForPackages` when you run `flutter upgrade`, which does a bunch of `pub get`s in repo packages.

Either it's important to run this, in which case we should run it any time it's needed, or it's not, in which case we shouldn't run it when you upgrade.

**Comment by zoechi** [comment]
`buildUnlinkedForPackages` doesn't appear anywhere except this issue
[usedRepo Search](https://github.com/flutter/flutter/search?q=buildUnlinkedForPackages&unscoped_q=buildUnlinkedForPackages)

Do you think this is still relevant?

**Comment by jonahwilliams** [comment]
Closing as this issue is no longer relevant
