### ISSUE TITLE
Textfield in the Dismissible has focus issue

### ISSUE THREAD

**Issue by butterflyXX** [flutter/flutter#72771]
1 step : showPopView;
2 step : select the textfield,then keyboard cannot show

in ios

**Comment by butterflyXX** [comment]
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  build(BuildContext context) {
    print("reload");
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xFFF7F7F7),
      appBar: AppBar(
        title: Text("测试"),
      ),
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: goodsListView(),
            ),
          ],
        ),
      ),
    );
  }

  Widget goodsListView() {
    return Scaffold(
      resizeToAvoidBottomPadding:true,
      body: ListView.builder(
        padding: EdgeInsets.only(top: 5,bottom: 5),
        itemCount: 1,
        itemBuilder: (BuildContext context, int index) {
          return Dismissible(
            key: UniqueKey(),
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              height: 100,
              child: addGodsItem(context,index),
            ),
            background: Container(
              alignment: Alignment.center,
              color: Colors.red,
              child: ListTile(
                trailing: Icon(Icons.delete,color: Colors.white,),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget addGodsItem(BuildContext context,int index) {
    print("$index");
    var model = "widget.goodsList[index]";
    return Container(
      color: Colors.amberAccent,
      child: Column(
        children: [
          SizedBox(height: 10,),
          InkWell(
            onTap: () {
              showSkuSelectView(context);
            },
            child: Text("showCupertinoModalPopup"),
          ),
          TextField(
            textAlign: TextAlign.center,
            maxLines: 1,
            textInputAction: TextInputAction.done,
          )
        ],
      ),
    );
  }

  void showSkuSelectView(BuildContext context) {

    //选择当前选中的按钮

    showCupertinoModalPopup(
        context: context,
        semanticsDismissible: true,
        builder: (cxt) {
          return Material(
            color: Colors.white.withOpacity(0),
            child: Container(
              height: 200,
              width: double.infinity,
              color: Colors.white,
            ),
          );
        });
  }
}`

**Comment by butterflyXX** [comment]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  build(BuildContext context) {
    print("reload");
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xFFF7F7F7),
      appBar: AppBar(
        title: Text("测试"),
      ),
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: goodsListView(),
            ),
          ],
        ),
      ),
    );
  }

  Widget goodsListView() {
    return Scaffold(
      resizeToAvoidBottomPadding:true,
      body: ListView.builder(
        padding: EdgeInsets.only(top: 5,bottom: 5),
        itemCount: 1,
        itemBuilder: (BuildContext context, int index) {
          return Dismissible(
            key: UniqueKey(),
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              height: 100,
              child: addGodsItem(context,index),
            ),
            background: Container(
              alignment: Alignment.center,
              color: Colors.red,
              child: ListTile(
                trailing: Icon(Icons.delete,color: Colors.white,),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget addGodsItem(BuildContext context,int index) {
    print("$index");
    var model = "widget.goodsList[index]";
    return Container(
      color: Colors.amberAccent,
      child: Column(
        children: [
          SizedBox(height: 10,),
          InkWell(
            onTap: () {
              showSkuSelectView(context);
            },
            child: Text("showCupertinoModalPopup"),
          ),
          TextField(
            textAlign: TextAlign.center,
            maxLines: 1,
            textInputAction: TextInputAction.done,
          )
        ],
      ),
    );
  }

  void showSkuSelectView(BuildContext context) {

    //选择当前选中的按钮

    showCupertinoModalPopup(
        context: context,
        semanticsDismissible: true,
        builder: (cxt) {
          return Material(
            color: Colors.white.withOpacity(0),
            child: Container(
              height: 200,
              width: double.infinity,
              color: Colors.white,
            ),
          );
        });
  }
}

**Comment by butterflyXX** [comment]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  build(BuildContext context) {
    print("reload");
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xFFF7F7F7),
      appBar: AppBar(
        title: Text("测试"),
      ),
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: goodsListView(),
            ),
          ],
        ),
      ),
    );
  }

  Widget goodsListView() {
    return Scaffold(
      resizeToAvoidBottomPadding:true,
      body: ListView.builder(
        padding: EdgeInsets.only(top: 5,bottom: 5),
        itemCount: 1,
        itemBuilder: (BuildContext context, int index) {
          return Dismissible(
            key: UniqueKey(),
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              height: 100,
              child: addGodsItem(context,index),
            ),
            background: Container(
              alignment: Alignment.center,
              color: Colors.red,
              child: ListTile(
                trailing: Icon(Icons.delete,color: Colors.white,),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget addGodsItem(BuildContext context,int index) {
    print("$index");
    var model = "widget.goodsList[index]";
    return Container(
      color: Colors.amberAccent,
      child: Column(
        children: [
          SizedBox(height: 10,),
          InkWell(
            onTap: () {
              showSkuSelectView(context);
            },
            child: Text("showCupertinoModalPopup"),
          ),
          TextField(
            textAlign: TextAlign.center,
            maxLines: 1,
            textInputAction: TextInputAction.done,
          )
        ],
      ),
    );
  }

  void showSkuSelectView(BuildContext context) {

    //选择当前选中的按钮

    showCupertinoModalPopup(
        context: context,
        semanticsDismissible: true,
        builder: (cxt) {
          return Material(
            color: Colors.white.withOpacity(0),
            child: Container(
              height: 200,
              width: double.infinity,
              color: Colors.white,
            ),
          );
        });
  }
}

**Comment by pedromassangocode** [comment]
Hi @butterflyXX 
Can you please provide your `flutter doctor -v` and the clear steps to reproduce the issue?
Thank you

**Comment by butterflyXX** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.5 19F101 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/liuxiaochen/opt/flutter
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/liuxiaochen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/liuxiaochen/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0.beta.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone (4) (mobile) • 00008030-00166DDE21D8802E • ios • iOS 13.6.1

• No issues found!

**Comment by butterflyXX** [comment]
1 step: hit the "showCupertinoModalPopup" button, then cancel it.
2 step: click textField, the keyboard doesn't pop up
in iOS

**Comment by butterflyXX** [comment]
@pedromassangocode

**Comment by pedromassangocode** [comment]
Reproducible on latest `master` channel.


<details><summary>Code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    print("reload");
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      backgroundColor: Color(0xFFF7F7F7),
      appBar: AppBar(
        title: Text("测试"),
      ),
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: goodsListView(),
            ),
          ],
        ),
      ),
    );
  }

  Widget goodsListView() {
    return ListView.builder(
      padding: EdgeInsets.only(top: 5,bottom: 5),
      itemCount: 1,
      itemBuilder: (BuildContext context, int index) {
        return Dismissible(
          key: UniqueKey(),
          child: Container(
            padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
            height: 100,
            child: addGodsItem(context,index),
          ),
          background: Container(
            alignment: Alignment.center,
            color: Colors.red,
            child: ListTile(
              trailing: Icon(Icons.delete,color: Colors.white,),
            ),
          ),
        );
      },
    );
  }

  Widget addGodsItem(BuildContext context,int index) {
    print("$index");
    return Container(
      color: Colors.amberAccent,
      child: Column(
        children: [
          SizedBox(height: 10,),
          InkWell(
            onTap: () {
              showSkuSelectView(context);
            },
            child: Text("showCupertinoModalPopup"),
          ),
          TextField(
            textAlign: TextAlign.center,
            maxLines: 1,
            textInputAction: TextInputAction.done,
          )
        ],
      ),
    );
  }

  void showSkuSelectView(BuildContext context) {
    // using showModalBottomSheet does not cause the issue
    showCupertinoModalPopup(
        context: context,
        //semanticsDismissible: true,
        builder: (cxt) {
          return Material(
            color: Colors.white.withOpacity(0),
            child: Container(
              height: 200,
              width: double.infinity,
              color: Colors.white,
            ),
          );
        });
  }
}
```
</details>

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.103, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.103 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 32741c0ec8 (12 hours ago), 2020-12-21 18:34:02 -0600
    • Engine revision af6889a600
    • Dart version 2.12.0 (build 2.12.0-169.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by chunhtai** [comment]
cc @gspencergoog @justinmc

**Comment by LongCatIsLooong** [comment]
This doesn't seem to be a framework issue. The `Dismissible` is given a different key every build so the subtree keeps getting re-inflated. Closing.
