### ISSUE TITLE
Failed assertion: line 1612 pos 12: 'result': is not true.

### ISSUE THREAD

**Issue by Jungle68** [flutter/flutter#72781]
Exception:  

```
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1612 pos 12: 'result': is not true.

```

```
When the exception was thrown, this was the stack: 
#2      _NestedOuterBallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/nested_scroll_view.dart:1612:12)
#3      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:545:10)
#4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:136:19)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:797:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
...

```

**Comment by pedromassangocode** [comment]
Hi @Jungle68 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by chunhtai** [comment]
cc @Piinks

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
