### ISSUE TITLE
Suggestion: rename DestinationLabel to BottomNavigationBarItem (or similar)

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#7278]
`DestinationLabel` seems (?) to be a term used in the Material Design docs but when initially onboarding it can be confusing as a concept because they contain more than a simple label. In addition, the property for setting the items in the navbar is `labels` so it should probably be renamed to `items`.

`DestinationLabel` seems to be only used in the `BottomNavigationBar` but I'm not sure if there is a broader use case I'm missing.

Happy to do a PR if you need.

**Comment by abarth** [comment]
@HansMuller

**Comment by Hixie** [comment]
There was another thing we were going to use them for... Can't remember what though. :-)

**Comment by HansMuller** [comment]
DestinationLabel and TabLabel are rather similar, however in the new version of tabs I'm working on, TabLabel isn't needed anymore.  I agree that BottomNavigationBarItem is a more obvious name for the items in a BottomNavigationBar, despite the material design spec.

**Comment by lukef** [comment]
I created a PR (https://github.com/flutter/flutter/pull/7281) for this if you want to review.

**Comment by abarth** [comment]
Looks like this happened.
