### ISSUE TITLE
app crash on low performance devices when loading large number of images

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#72786]
Flutter app crash when loading a large number of images. (app crash only low-performance devices. ex: Xiaomi 9c 2GB). I tried both `FadeInImage.memoryNetwork` and `CachedNetworkImage`. 

Is there any better API to load network images without any issues?

    SliverGrid(
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(),
          childCount: model.length, //more than 1000
          delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                     return AspectRatio(
                       aspectRatio: childAspectRatio,
                       child: FadeInImage.memoryNetwork(
                                  placeholder: kTransparentImage,
                                  image: model[index].imageUrl,
                                  fit: BoxFit.cover),
    
                                //   CachedNetworkImage(
                                //     placeholder: (context, url) => Container(),
                                //     errorWidget: (context, url, error) =>Container(),
                                //     imageUrl: model[index].imageUrl,
                                //     fit: BoxFit.fill,
                                //   )

**Comment by Fa-d** [comment]
I think you are trying to load all the data at once. Then surely it will crash. 
Are you using paging ?? look here`https://pub.dev/packages/pagination`

**Comment by TahaTesser** [comment]
Hi @bhanuka96 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/50024
Related to https://github.com/flutter/flutter/issues/21571 https://github.com/flutter/flutter/issues/51584
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by bhanuka96** [comment]
@Fa-d Sometimes length more than 1000, sometimes length is 20-30. always crash on low-performance devices

**Comment by bhanuka96** [comment]
@TahaTesser I added these two parameters. now it's not crash. can you give me your feedback?

```
 imageCacheHeight: 50,
imageCacheWidth: 50,
```

```
FadeInImage.memoryNetwork(
              placeholder: kTransparentImage,
              image: image,
              fit: BoxFit.cover,
              width: 70,
              imageCacheHeight: 50,
              imageCacheWidth: 50,
              height: 70,
            ),
```
