### ISSUE TITLE
Improve gen-l10n detailed report flow

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#72795]
These were my steps

1. See the info message: `To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.`
2. Try `flutter run --untranslated-messages-file file.txt`, no option.
3. Figure out that it's `flutter gen-l10n --untranslated-messages-file file.txt`
4. Get an error `The 'template-arb-file', LocalFile: 'lib/l10n/app_en.arb', is
not readable.`
because we have an `l10n.yaml` that specifies custom options, and which gen-l10n doesn't read.

There's two underlying issues here: should `gen-l10n` read `l10n.yaml` by default if it exists? Can we provide an exact command in the info message for untranslated messages?

cc @shihaohong

**Comment by shihaohong** [comment]
Thanks for the report, I'll look into this later this week!

**Comment by shihaohong** [comment]
I just submitted a PR to improve the report flow between the usage of command line and l10n.yaml use-cases.

To further discuss what should happen with the command line `flutter gen-l10n` is used when an l10n.yaml file exists:

My thought process here is that if an `l10n.yaml` file exists, no matter what the user does with the command line tool, the generated files will eventually be overwritten upon building/running the Flutter app, running pub get, etc. So, reading the `l10n.yaml` file by default if it exists makes sense. We should also print a message when this happens so users aren't confused by the mismatching options that might've been passed into the command line call vs what is in the l10n.yaml file.

**Comment by larssn** [comment]
@shihaohong
To rebuild the translations I currently comment out `generate: true`, let it run and then comment it back in.

Is there a better way of rebuilding the translations while the app is running in dev mode, and hot-reloading?

**Comment by shihaohong** [comment]
@larssn Could you try running `flutter pub get`? That should regenerate the translations without the app running in dev mode. Alternatively, you could also use `flutter gen-l10n <your options>` and should effectively do the same thing.
