### ISSUE TITLE
CreateProcessW failed 193 Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by EuvolaGG** [flutter/flutter#72797]
Hello...am doing a project and I got the failed to extract manifest  from apk error from both android studio and vs code.Why am I getting this error and how do I solve it.This also happens when I run the project even before I input my own code.

1)This the errror message after running flutter run
PS C:\Users\NM\Desktop\resource\memo> flutter run
Launching lib\main.dart on TECNO P904 in debug mode...
CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE dump xmltree C:\Users\NM\Desktop\resource\memo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.No application found for TargetPlatform.android_arm64.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.

2)This what am getting from flutter doctor
PS C:\Users\NM\Desktop\resource\memo> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!

3)This my pubspec yaml
name: memo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  firebase_core:
  cloud_firestore:
  firebase_auth:
  image_picker:
  firebase_storage:
  flutter_image_compress:
  path_provider:
  uuid:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by darshankawar** [comment]
@EuvolaGG 
There was similar but old [issue](https://github.com/flutter/flutter/issues/31550) fixed and [merged](https://github.com/google/process.dart/pull/38) in master. Try by switching to latest master and see if it works or still get same issue. If so, provide `flutter doctor -v`.

**Comment by EuvolaGG** [comment]
I thought channel  master was for web development and channel stable for mobile development and my project is under mobile devlopment

**Comment by EuvolaGG** [comment]
i thought channel master was for web development but am doing a mobile project hence should use channel stable.

**Comment by darshankawar** [comment]
@EuvolaGG 
Not sure why you posted same comment twice, but to answer your question, since mobile platform is stable, hence we mostly use stable, but if you want recent release that are not on stable yet but on master, you may switch to latest master and confirm that.

**Comment by EuvolaGG** [comment]
I switched to master but still got the same issue..
1)This the response
CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE dump xmltree
  C:\Users\NM\Desktop\resource\memo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
No application found for TargetPlatform.android_arm64.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.

**Comment by darshankawar** [comment]
Similar issue was fixed https://github.com/flutter/flutter/issues/31550

**Comment by EuvolaGG** [comment]
Is there a timeline when a possible solution can be availed?

**Comment by christopherfujino** [comment]
@EuvolaGG can you provide the output of `flutter doctor -v`?

**Comment by EuvolaGG** [comment]
THIS IS MY FLUTTER DOCTOR -V @christopherfujino 
PS C:\Users\NM\Desktop\Repositories\memo> flutter doctor -v
[√] Flutter (Channel master, 1.26.0-2.0.pre.134, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.26.0-2.0.pre.134 at C:\flutter
    • Framework revision d61d7758ed (12 days ago), 2020-12-24 21:42:25 -0800
    • Engine revision 1c975f1e7c
    • Dart version 2.12.0 (build 2.12.0-177.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\NM\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\NM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 86.0.4240.75

**Comment by jmagman** [comment]
@EuvolaGG did you mean to close this?

**Comment by EuvolaGG** [comment]
Yes...I reinstalled all my software and it worked

**Comment by EuvolaGG** [comment]
Am thinking my android sdks were not update that's why it's ok since that all that changed...Thanks to all that helped @jmagman
