### ISSUE TITLE
Running "flutter clean" in a newly-created Flutter project results in (null-related) analysis errors

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#72807]
I'm not sure whether this is an Analysis server issue or a Flutter issue, but it appears to occur when `flutter clean` deletes the `.dart_tool/package_config.json` file.

To reproduce (using current `master` 32741c0ec8):

- Run `flutter create foo`
- Open in IDE
- Note there are no analysis errors
- Close IDE
- Run `flutter clean`
- Reopen in IDE
- There are now null-related analysis errors on `key`/`title`:
  > The parameter 'key' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
  > Try adding either an explicit non-'null' default value or the 'required' modifier.

Manually deleting the `.dart_tool/package_config.json` file (instead of `flutter clean`) triggers the same issue. I'm unsure whether the issue is the analysis server doing something incorrectly when that file is missing, or whether `flutter clean` should be excluding that file from what it deletes? (@devoncarew @bwilkerson)

(You don't actually need to close the IDE, it seems to update automatically if you leave it open - in both directions as you fetch packages and/or `clean`).

**Comment by pedromassangocode** [comment]
Easily reproducible with the steps above.

![Screen Shot 2020-12-23 at 08 58 29](https://user-images.githubusercontent.com/67424416/102973537-3154fc80-44fd-11eb-8d24-9493fdea4fca.png)


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.117, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.117 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 15c009b805 (7 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by DanTup** [comment]
@jonahwilliams with the fix, there are package resolution errors instead:

<img width="810" alt="Screenshot 2021-01-06 at 09 44 54" src="https://user-images.githubusercontent.com/1078012/103754161-e5797b80-5003-11eb-9f63-3b8b5d62ef22.png">

It's more obvious how to fix this, though is it expected that after running `clean` you'll have to re-fetch packages? I don't think that was the case prior to `.dart_tool/package_config.json`. If that's the first thing everyone will do after cleaning, would it make sense to do it automatically (or exclude `.dart_tool/package_config.json` from deletion to skip it)?

**Comment by devoncarew** [comment]
Hmm, from a casual read of this issue, I agree w/ what Danny said; `clean` should likely preserve .packages and .dart_tool/package_config.json.

**Comment by DanTup** [comment]
@jonahwilliams is there value in having `clean` re-fetch packages if it's correct for it to clean these out too? Otherwise, perhaps the editors could detect the file being deleted and offer to fetch - like the do on startup - although that's less friendly for CLI users.
