### ISSUE TITLE
`flutter pub` should support recently added subcommands from `dart pub`.

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#72805]
The following `dart pub` commands all seem to lack a `flutter pub` counterpart:

* `dart pub add`
* `dart pub remove`
* `dart pub logout`
* `dart pub login`
* `dart pub upgrade --null-safety`
* `dart pub upgrade --major-versions`

**Comment by RandalSchwartz** [comment]
And `dart pub global activate` puts things into a different directory from `flutter pub global activate`.  Yes, you need to add *two* elements to your PATH, and you can install the same thing in both dirs, which can get very confusing.

**Comment by sigurdm** [comment]
@RandalSchwartz are you sure? I believe those should go to the same directory: `$PUB_CACHE/bin`.
What directories are you seeing for each command? What platform are you on?

**Comment by jonasfj** [comment]
@RandalSchwartz, yes, flutter uses a different default path for `PUB_CACHE`, but that's an orthogonal issue.

**Comment by sigurdm** [comment]
One more missing option `--trace`:
```
flutter pub --trace get
Could not find an option named "trace".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by jonasfj** [comment]
Fixed in https://github.com/flutter/flutter/pull/74060

We're only missing `--trace`, but that is something we  can sync on later.
