### ISSUE TITLE
Flutter build issue

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#72804]
Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
> Execution failed for JetifyTransform: /home/aman/Desktop/projects/mservice/build/app/intermediates/flutter/debug/libs.jar.
> Transform's input file does not exist: /home/aman/Desktop/projects/mservice/build/app/intermediates/flutter/debug/libs.jar. (See https://issuetracker.google.com/issues/158753935) 

<details>
  <summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_IN)
    • Flutter version 1.22.5 at /home/aman/Android/flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/aman/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /home/aman/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/aman/Desktop/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)
```
</details>

flutter build apk -v at https://pastebin.com/4AkZdJXj 

There is currently a way to solve this run `flutter build apk --debug` then `flutter build apk --profile` then running this command 

But there is a new problem 

the app works fine in `flutter run --release`

But shows White Screen in this built apk

**Comment by amanv8060** [comment]
Forgot to mention : https://github.com/flutter/flutter/issues/58247#issuecomment-638344044 is the method how to use the default gradle version

**Comment by TahaTesser** [comment]
Hi @amanv8060 
Please change your gradle to ` classpath 'com.android.tools.build:gradle:3.5.0'` in your `build.gralde` and try again.

If the problem persists, Can you please provide `flutter run build apk --verbose` logs with updated gradle, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using third-party packages
Thank you

**Comment by amanv8060** [comment]
There is no issue with 3.5.0 version , I just posted the issue so that the problem can be further tracked that on latest gradle the built apk doesnt run even if its built . You can close it if there is a issue that mentions it, all i found were issues mentioning that apk is not being built

**Comment by TahaTesser** [comment]
Hi @amanv8060 
Gradle 4.0.0+ isn't fully supported, it is expected to have issues, there are open issues to address this. 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by niroj08** [comment]
I was having same issue with 4.1.1 gradle version. It worked well with certain abi but not with all. 
@TahaTesser  Thank you for the information
