### ISSUE TITLE
resamplingEnabled might cause cupertino back gestures not working

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#72809]
Due to release announcement of Flutter version 1.22.4. i found cupertino page route back gestures not work well after add following code
`
GestureBinding.instance.resamplingEnabled = true;
`

## Steps to Reproduce
add 
`
GestureBinding.instance.resamplingEnabled = true;
`

and navigate to a scaffold that body contains a listview or singlechildscrollview

back gesture will be delayed or not worked well on IOS devices.
This is an always existing bug after  resampling enabled .

**Comment by chunhtai** [comment]
cc @dkwingsmt

**Comment by pedromassangocode** [comment]
Hi @virskor 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by virskor** [comment]
I found this bug is not a flutter issue. i will close it
