### ISSUE TITLE
[web] Scroll in ListView causes unexpected state in PersistedOffset

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#72813]
## command

flutter run -d chrome

## exception

The exception occurrs when scrolling up & down in a list view which is within a Dialog created in the build() method of  a StatefulWidget:

**VIDEO:** https://github.com/svprdga/flutter-issue-72522/blob/main/list-view-issue.mkv?raw=true

Note: when the exception happens, the very first row with the checkbox 'jumps' to the bottom and the scroll freezes.

```
return Dialog(
  child: ConstrainedBox(
    constraints: BoxConstraints(maxWidth: MAX_WIDTH),
    child: Form(
      key: _formKey,
      child: ListView(
        children: widgets,
      ),
    ),
  ),
);
```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/picture.dart 54:62                    _recycleCanvas
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/picture.dart 321:9                    [_applyPaint]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/picture.dart 536:5                    apply
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
====================================================================================================

```
```

## flutter doctor

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.685], locale es-ES)
    • Flutter version 1.25.0-8.1.pre at C:\Users\Svprd\opt\flutter
    • Framework revision 8f89f6505b (7 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Svprd\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Svprd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```

**Comment by darshankawar** [comment]
@svprdga 
There was similar issue recently fixed and merged into master, https://github.com/flutter/flutter/issues/72171
Please switch to latest master and try again which should resolve the issue.
Closing this as already fixed. If you still get the same error on latest master, write in comments and I'll reopen it.
Thanks.

**Comment by svprdga** [comment]
Tested with master branch v1.26.0-2.0.pre.117, the error it's still there, it's **not** fixed.

**Comment by darshankawar** [comment]
@svprdga 
I do see the error on latest master. Will comment in original issue.
