### ISSUE TITLE
[web]: Different scroll heights for different OSes and browsers, causes inconsistent scrolling

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#72811]
Flutter seems to report different scroll heights for different OSes and browsers, which causes inconsistent scrolling and zooming behavior.

This results in inconsistent end user behavior on Rive app: https://feedback.rive.app/66

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mariamhas** [comment]
customer reported that the root cause of this issue was actually https://github.com/flutter/flutter/issues/73617.

Closing this issue since the other one is closed and fixed
