### ISSUE TITLE
Keystroke file not Found

### ISSUE THREAD

**Issue by harshjadon9** [flutter/flutter#72812]
*macOS

I have generated my keystroke file as name: 'key.jks'

**when i run:**
`flutter build apk `

**error:**
* What went wrong:                                                      
Execution failed for task ':app:validateSigningRelease'.                
> Keystore file '/key.jks>' not found for signing config 'release'. `

**my 'key.jks' file location:**
`...android/app/key.jks`

**my 'key.properties'**
```
storePassword=123456
keyPassword=123456
keyAlias=key
storeFile=/key.jks>
```

**my 'key.properties' location:**
`...android/key.properties`

**my 'build.gradle' location:**
`android/app/build.gradle`

**Comment by darshankawar** [comment]
@harshjadon9 
Can you try [this](https://github.com/flutter/flutter/issues/19106#issuecomment-411360844) solution and see if it works ?

**Comment by harshjadon9** [comment]
> @harshjadon9
> Can you try [this](https://github.com/flutter/flutter/issues/19106#issuecomment-411360844) solution and see if it works ?

Sir, can u please elaborate on it.I couldn't see any "<" and ">"...
i opened `key.jks` file in notepad there were no "<" and ">"...

**Comment by darshankawar** [comment]
@harshjadon9 
Check [this](https://stackoverflow.com/a/53979415) solution and see if it works for you.
Also, I don't think this is a Flutter issue, but your setup where the location of your .jks file isn't correct. I'd suggest you to ask this question on StackOver flow and see https://flutter.dev/community for resources.
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by darshankawar** [comment]
@harshjadon9 
Check [this](https://stackoverflow.com/a/53979415) solution and see if it works for you.
Also, I don't think this is a Flutter issue, but your setup where the location of your .jks file isn't correct. I'd suggest you to ask this question on StackOver flow and see https://flutter.dev/community for resources.
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by harshjadon9** [comment]
This worked for me! (I asked on Stackoverflow.com)
https://stackoverflow.com/questions/65446785/keystroke-file-not-found-flutter

**it should be** 
```
storeFile=./key.jks
```
**Not**
```
storeFile=/key.jks>
```
