### ISSUE TITLE
Swift apps not building in CI, standard libraries not found "error: header 'stdarg.h' not found"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#72823]
examples/platform_channel_swift isn't building on CI, it can't seem to find the standard libraries in build_test
```
            PrecompileSwiftBridgingHeader normal armv7 (in target 'Runner' from project 'Runner')
...         /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk/usr/include/module.modulemap:118:11: error: header 'stdarg.h' not found
               header "stdarg.h" // note: supplied by the compiler
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8860189854268075984/+/steps/run_test.dart_for_build_tests_shard_and_subshard_0/0/stdout

Started on https://github.com/flutter/flutter/commit/af1c629def7ac38b2428ac1837e8c6a3ec98b547 which isn't related.

Same issue on tool_test building mac app integration_tests/flutter_gallery (also Swift)

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8860189984899554176/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout

**Comment by jmagman** [comment]
\cc @godofredoc @keyonghan can we roll back https://flutter-review.googlesource.com/c/recipes/+/9460 ?

**Comment by keyonghan** [comment]
Seems related to https://flutter-review.googlesource.com/c/recipes/+/9460

**Comment by keyonghan** [comment]
Reverted: https://flutter-review.googlesource.com/c/recipes/+/9480

**Comment by godofredoc** [comment]
Setting as P1 as the change was reverted.

**Comment by godofredoc** [comment]
Here is the fix to force the drone to use the flutter package instead of the chromium one:

https://flutter-review.googlesource.com/c/recipes/+/9481
