### ISSUE TITLE
Android Studio 4.1.0 Flutter and Dart Plugin not installed

### ISSUE THREAD

**Issue by mbaust269** [flutter/flutter#72830]
Hi there. I'm having trouble setting up the IDE. I'm using Android Studio 4.1.0 and the Flutter Doctor says the following.

**[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale de-DE)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.**

I've been looking for a solution on the internet for hours and haven't found anything that worked. can someone help me?
Or is it normal that the plugins are not OK?

**Comment by MadeBugs** [comment]
```
ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1
```
拿好不送

**Comment by SheepYang1993** [comment]
windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？

**Comment by darshankawar** [comment]
@mbaust269 
This is a known issue. See [this](https://github.com/flutter/flutter/issues/67986) for reference. You may try [this](https://github.com/flutter/flutter/issues/67986#issuecomment-714856900) solution and see if it works.
Also, if you are still getting the plugins not installed, be informed that they are warnings and won't affect your development work.
Closing this as already fixed. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by torgodly** [comment]
use this commands

flutter channel dev
flutter channel upgrade

**Comment by cschen1205** [comment]
> windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？

open file "{FlutterFolderPath}\packages\flutter_tools\lib\src\android\android_studio.dart", then modify line 139 ~ 141 from         
       '.$studioAppName$major.$minor',
        'config',
        'plugins',
to 
        'AppData/Roaming/Google',
        'AndroidStudio$major.$minor',
        'plugins',
save file, and then delete file "{FlutterFolderPath}\bin\cache\flutter_tools.stamp". run command "flutter doctor -v" in cmd. It will rebuild flutter and can detect flutter and dart plugin now.

**Comment by jwhijazi** [comment]
> > windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？
> 
> open file "{FlutterFolderPath}\packages\flutter_tools\lib\src\android\android_studio.dart", modify line 139 ~ 141 from
> '.$studioAppName$major.$minor',
> 'config',
> 'plugins',
> to
> 'AppData/Roaming/Google',
> 'AndroidStudio$major.$minor',
> 'plugins',
> save file, and then delete file "{FlutterFolderPath}\bin\cache\flutter_tools.stamp". run command "flutter doctor -v" in cmd. It will rebuild flutter and can detect flutter and dart plugin now.

I tried this solution on Windows and it worked for me.
Thanks @cschen1205

**Comment by ghadeer45** [comment]
> > windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？
> 
> open file "{FlutterFolderPath}\packages\flutter_tools\lib\src\android\android_studio.dart", modify line 139 ~ 141 from
> '.$studioAppName$major.$minor',
> 'config',
> 'plugins',
> to
> 'AppData/Roaming/Google',
> 'AndroidStudio$major.$minor',
> 'plugins',
> save file, and then delete file "{FlutterFolderPath}\bin\cache\flutter_tools.stamp". run command "flutter doctor -v" in cmd. It will rebuild flutter and can detect flutter and dart plugin now.


it worked for me 
Thanks alot @cschen1205

**Comment by ismanir** [comment]
> > windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？
> 
> open file "{FlutterFolderPath}\packages\flutter_tools\lib\src\android\android_studio.dart", modify line 139 ~ 141 from
> '.$studioAppName$major.$minor',
> 'config',
> 'plugins',
> to
> 'AppData/Roaming/Google',
> 'AndroidStudio$major.$minor',
> 'plugins',
> save file, and then delete file "{FlutterFolderPath}\bin\cache\flutter_tools.stamp". run command "flutter doctor -v" in cmd. It will rebuild flutter and can detect flutter and dart plugin now.

thanks a lot, its work for me to <3

**Comment by Devya25** [comment]
> 
> 
> > windows平台，使用AndroidStudio4.1也是提示找不到插件，怎么设置？
> 
> open file "{FlutterFolderPath}\packages\flutter_tools\lib\src\android\android_studio.dart", modify line 139 ~ 141 from
> '.$studioAppName$major.$minor',
> 'config',
> 'plugins',
> to
> 'AppData/Roaming/Google',
> 'AndroidStudio$major.$minor',
> 'plugins',
> save file, and then delete file "{FlutterFolderPath}\bin\cache\flutter_tools.stamp". run command "flutter doctor -v" in cmd. It will rebuild flutter and can detect flutter and dart plugin now.
