### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by tonTed** [flutter/flutter#72839]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4686 pos 12: 'child == _child': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/tonted/codeboxx/odysseyProjects/mobile_rocket_elevator/lib/main.dart:12:16
When the exception was thrown, this was the stack: 
#2      ComponentElement.forgetChild (package:flutter/src/widgets/framework.dart:4686:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3522:14)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3551:32)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
...
====================================================================================================

**Comment by darshankawar** [comment]
@tonTed 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
