### ISSUE TITLE
DropdownButtonFormField way too small tap area

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#72832]
## Use case
The tap area on the `DropdownButtonFormField ` is very small. It only has the height of the actual `DropDownButton` widget. The whole `InputDecorator` with its padding etc. is not reacting to any taps/touches/clicks...
This results in a rather frustrating user experience, as you try to tap on the widget, but nothing happens, because you didn't touched on the very small area in the middle, but still inside the `InputDecorator` widget...

Image explaining the issue: (Only the green area reacts to tap/click actions.)
![image](https://user-images.githubusercontent.com/10547444/102939915-74887e80-44af-11eb-92ee-279cd5b002b4.png)

## Proposal
Increase the tap area so that the whole `InputDecorator` element can be clicked.
(Therefor the `DropDownButton` element needs to expose methods to open / close it from outside.)

**Comment by darshankawar** [comment]
@lazylazyllama 
Does [this](https://github.com/flutter/flutter/issues/53634) issue resemble yours ?
There seems to be a [PR](https://github.com/flutter/flutter/pull/72407) open just recently to fix the clickable area of DropdownButtonFormField.

**Comment by lazylazyllama** [comment]
It does. Closing as this is a duplicate.

**Comment by adimshev** [comment]
+1

**Comment by tonydigifiv** [comment]
Any solution for this to increase the tap size area?
