### ISSUE TITLE
video_player VideoPlayerValue size exception

### ISSUE THREAD

**Issue by workwing** [flutter/flutter#72849]
Using video_player after initialization, the size in videoplayervalue often changes. Sometimes the height and width of the same video are reversed, resulting in distortion of the video display.

> incorrect: VideoPlayerValue(duration: 0:00:04.151000, size: Size(1920.0, 1080.0), position: 0:00:00.000000, caption: Caption(number: null, start: null, end: null, text: null), buffered: [], isPlaying: true, isLooping: true, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null)

> correct: VideoPlayerValue(duration: 0:00:04.151000, size: Size(1080.0, 1920.0), position: 0:00:00.000000, caption: Caption(number: null, start: null, end: null, text: null), buffered: [], isPlaying: true, isLooping: true, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null)

`Container(
          height: double.infinity,
          child: Center(
              child: AspectRatio(
                aspectRatio: videoController.aspectRatio,
                child: VideoPlayer(videoController.controller),
              ),
            ),
        ),`

**Comment by workwing** [comment]
Sample video：https://timg.tebaobao.vip/images/idimages/202012/1608623299168797812.mp4

**Comment by TahaTesser** [comment]
Hi @workwing 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample with a sample video link or file. 
Thank you

**Comment by workwing** [comment]
sample video link: https://timg.tebaobao.vip/images/idimages/202012/1608623299168797812.mp4
video_player: 1.0.1
flutter version: 1.17.5

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.17.5, on macOS 11.0.1 20B29, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.0)
[✓] Connected device (3 available)


`import 'dart:async';

import 'package:connectivity/connectivity.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tebaobao/public/config/design.dart';
import 'package:tebaobao/public/config/gloab.dart';
import 'package:tebaobao/public/tools/event_bus.dart';
import 'package:tebaobao/public/tools/log_utils.dart';
import 'package:video_player/video_player.dart';
import 'package:tebaobao/public/tools/net_manager/q_hud.dart';

typedef VideoWidgetBuilder = Widget Function();

enum VideoStatus {
  normal,

  loading,

  init,

  playing,

  pause,

  error,
}

class VideoController extends ChangeNotifier {
  VideoPlayerController controller; 
  StreamSubscription<ConnectivityResult> _eventAction; 
  VideoStatus status;
  String url;
  bool isQuiet;
  bool autoPlay;
  bool repeatPlay;
  bool forceScale;
  double volume = 0;
  int buffered = 0;
  int position = 0;
  int totalTime = 0;
  bool drag = false;
  bool isPlaying = false;
  bool _isFinished = false;

  VideoController() {
    status = VideoStatus.normal;
    _eventAction =
        EventAction.eventBus.on<ConnectivityResult>().listen((status) {
      if (status == ConnectivityResult.none) {
        changeStatus(VideoStatus.error);
      } else {
        if (this.status == VideoStatus.error) {
          urlChange(true);
        }
      }
    });
  }

  void changeStatus(VideoStatus s) {
    if (status == s) {
      return;
    }
    status = s;

    notifyListeners();
  }

  void changeVolume(double v) {
    volume = v;
    controller.setVolume(v);
    isQuiet = v == 0 ? true : false;
    notifyListeners();
  }

  void play() {
    if (controller.value.isPlaying) {
      return;
    }
    changeStatus(VideoStatus.playing);
    controller.play();
  }

  void pause() {
    if (!controller.value.isPlaying) {
      return;
    }
    changeStatus(VideoStatus.pause);
    controller.pause();
  }

  Future<void> seekTo(int milliseconds, {bool complete = true}) async {
    await controller.seekTo(Duration(milliseconds: milliseconds));
    if (complete && status != VideoStatus.init) {
      changeStatus(VideoStatus.init);
      await controller.pause();
    }
  }

  void dragAction(bool action) {
    if (drag == action) {
      return;
    }

    drag = action;

    notifyListeners();
  }

  void _videoListener() async {
    if (controller.value.hasError && status != VideoStatus.error) {
      changeStatus(VideoStatus.error);
    } else {
      if (controller.value == null) {
        return;
      }
      totalTime = controller.value.duration.inMilliseconds;
      isPlaying = controller.value.isPlaying;

      Duration res = await controller.position;
      if (res >= controller.value.duration && status != VideoStatus.init && !_isFinished) {
        _isFinished = true;
        if(!repeatPlay){
          seekTo(0, complete: true);
        }
        Future.delayed(Duration(milliseconds: 300), (){
          _isFinished = false;
        });
        return;
      }

      if (controller.value.buffered.last.end.inMilliseconds != buffered) {
        buffered = controller.value.buffered.last.end.inMilliseconds;
        notifyListeners();
      }
      if (controller.value.position.inMilliseconds != position) {
        position = controller.value.position.inMilliseconds;
        notifyListeners();
      }
    }
  }

  void urlChange(bool init) async {
    if (url == null || url == '') {
      controller.removeListener(_videoListener);
      controller.dispose();
      return;
    }

    if (controller != null && !init) {
      seekTo(0);
      return;
    } else if (controller != null) {
      controller.removeListener(_videoListener);
      controller.dispose();
    }

    changeStatus(VideoStatus.normal);
    controller = VideoPlayerController.network(url);
    controller.setLooping(repeatPlay);
    changeStatus(VideoStatus.loading);
    controller.addListener(_videoListener);
    await controller.initialize();
    changeStatus(VideoStatus.init);
    changeVolume(isQuiet ? 0 : 1);

    if (autoPlay) {
      play();
    }
  }

  get size {
    if (controller == null) {
      return Size.zero;
    }
    return controller.value.size ?? Size.zero;
  }

  get aspectRatio {
    if (controller == null) {
      return 1.0;
    }
    return controller.value.aspectRatio;
  }

  @override
  void dispose() async {
    super.dispose();
    if (controller != null) {
      controller.pause();
      controller.removeListener(_videoListener);
      controller.dispose();
    }

    _eventAction.cancel();
    TLoger.v('video dispose');
  }
}

class TVideo extends StatelessWidget {
  final String url;
  final bool autoPlay;
  final bool forceScale;
  final bool isQuiet;
  final bool repeatPlay;
  final VideoController videoController;
  final VideoWidgetBuilder builder;
  final EdgeInsets padding;

  TVideo.network({
    Key key,
    @required this.videoController, 
    @required this.url, 
    this.builder,
    this.autoPlay = false, 
    this.isQuiet = false, 
    this.repeatPlay = false,
    this.forceScale = false, 
    this.padding = EdgeInsets.zero,
  }) : super(key: key) {
    videoController.url = url;
    videoController.autoPlay = autoPlay;
    videoController.isQuiet = isQuiet;
    videoController.forceScale = forceScale;
    videoController.repeatPlay = repeatPlay;
    if (url == videoController.url) {
      videoController.urlChange(false);
    } else {
      videoController.urlChange(true);
    }
  }

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
      value: videoController,
      child: Stack(
        children: <Widget>[
          _noUrl,
          Padding(
            padding: padding,
            child: _videoPlayer(),
          ),
          if (builder != null) ...{
            Padding(
              padding: EdgeInsets.zero,
              child: builder(),
            ),
          },
        ],
      ),
    );
  }

  Widget _videoPlayer() {
    return Selector<VideoController, bool>(
      selector: (ctx, controller) {
        bool flag = videoController.status.index < VideoStatus.error.index &&
            videoController.status.index > VideoStatus.loading.index;
        return !flag;
      },
      builder: (ctx, status, _) {
        if (videoController.status.index < VideoStatus.init.index || !videoController.controller.value.initialized) {
          return _videoLoad();
        } else if (videoController.status == VideoStatus.error) {
          return _videoError();
        }

        double forceRatio = 1;
        if (forceScale &&
            (videoController.size.height > videoController.size.width)) {
          double showHeight = TScreen.screenHeight() - padding.bottom;
          double vWidth = showHeight * videoController.aspectRatio;
          if (vWidth < TScreen.screenWidth()) {
            forceRatio = TScreen.screenWidth() / vWidth;
          } else {
            forceRatio = vWidth / TScreen.screenWidth();
          }
        }

        return Container(
          height: double.infinity,
          child: ClipRect(
            clipBehavior: Clip.hardEdge,
            child: Center(
              child: AspectRatio(
                aspectRatio: videoController.aspectRatio,
                child: VideoPlayer(videoController.controller),
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _videoError() {
    return Selector<VideoController, bool>(
      selector: (ctx, controller) {
        bool flag = videoController.status != VideoStatus.error;
        return flag;
      },
      builder: (ctx, show, _) {
        return Center(
          child: Offstage(
            offstage: !show,
            child: Text(
              'error',
              style: TextStyle(color: Colors.white),
            ),
          ),
        );
      },
    );
  }

  Widget _videoLoad() {
    return Selector<VideoController, bool>(
      selector: (ctx, controller) {
        bool flag = videoController.status != VideoStatus.normal;
        return flag;
      },
      builder: (ctx, show, _) {
        return Center(
          child: Offstage(
            offstage: !show,
            child: TLoading.circle,
          ),
        );
      },
    );
  }

  get _noUrl {
    return Selector<VideoController, bool>(
      builder: (ctx, show, _) {
        return Center(
          child: Offstage(
            offstage: !show,
            child: Text(
              'none info',
              style: TextStyle(color: Colors.white),
            ),
          ),
        );
      },
      selector: (ctx, controller) => isNullorEmpty(controller.url),
    );
  }
}

TVideo.network(
      videoController: VideoController(),
      url: _viewModel.detailEntity.videoUrl,
      autoPlay: true,
      repeatPlay: true,
      forceScale: false,
    );
`

**Comment by TahaTesser** [comment]
Hi @workwing 
You seem to be running quite an older version of  Flutter stable
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Also please provide [a minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example), not production code without using third-party packages

Thank you

**Comment by workwing** [comment]
Sorry, I can't upgrade the version, because the production environment can't support the upgrade, so only 1.17.5 can be used. I think this is related to the video_player. There is an exception in obtaining the size, width and height of the video, which cannot be obtained correctly all the time, as shown in the above question

**Comment by TahaTesser** [comment]
Hi @workwing 
Using your video link, I created a minimal code sample and ran it on the latest `stable` channel, no exceptions. 
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  VideoPlayerController videoController;

  @override
  void initState() {
    super.initState();
    videoController = VideoPlayerController.network(
        'https://timg.tebaobao.vip/images/idimages/202012/1608623299168797812.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  void dispose() {
    videoController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          height: double.infinity,
          child: Center(
            child: AspectRatio(
              aspectRatio: videoController.value.aspectRatio,
              child: VideoPlayer(videoController),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.play_arrow),
        onPressed: () {
          videoController.play();
        },
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on Taha’s iPhone in debug mode...
 lib/main.dart
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           29.8s
Connecting to VM Service at ws://localhost:54655/ws

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.3
    ! Error: Taha’s iPhone is busy: Copying cache files from device. Xcode will continue when Taha’s iPhone is finished. (code -10)

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
