### ISSUE TITLE
After I update from 1.24.0-10.2.pre to 1.25.0-8.1.pre,  My APP with permission_handler 5.0.1+1 compiled failed

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#72850]
It output a lot of error saying that something wrong with androidx.***
After I downgrade back to 1.24.0-10.2.pre, everything is OK.

**Comment by heroqin** [comment]
I use Windows7 OS: 
C:\geanapp\gphone>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)

• No issues found!

The following is the output when I compile under 1.25.0-8.1.pre:
Launching lib\main.dart on M2002J9E in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':permission_handler:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':permission_handler:debugCompileClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-common:{strictly 2.0.0}.
     Required by:
         project :permission_handler
      > Cannot find a version of 'androidx.lifecycle:lifecycle-common' that satisfies the version constraints: 
           Dependency path 'com.baseflow.permissionhandler:permission_handler:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-92ae191c17a53144bf4d62f3863c110be08e3fd3' --> 'androidx.lifecycle:lifecycle-common:2.2.0'
           Constraint path 'com.baseflow.permissionhandler:permission_handler:1.0-SNAPSHOT' --> 'androidx.lifecycle:lifecycle-common:{strictly 2.0.0}' because of the following reason: debugRuntimeClasspath uses version 2.0.0
           Dependency path 'com.baseflow.permissionhandler:permission_handler:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-92ae191c17a53144bf4d62f3863c110be08e3fd3' --> 'androidx.lifecycle:lifecycle-common-java8:2.2.0' --> 'androidx.lifecycle:lifecycle-common:2.2.0'
           Dependency path 'com.baseflow.permissionhandler:permission_handler:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-92ae191c17a53144bf4d62f3863c110be08e3fd3' --> 'androidx.lifecycle:lifecycle-runtime:2.2.0' --> 'androidx.lifecycle:lifecycle-common:2.2.0'

**Comment by TahaTesser** [comment]
Hi @heroqin 
This will be fixed in the next `beta` release, meanwhile, you can either upgrade to `dev`. 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/72627
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
