### ISSUE TITLE
I suggest adding a configuration to the main application to decide which files need to be obfuscated and which files do not need to be obfuscated, just like the "proguard-rules.pro" file developed by Android natively.

### ISSUE THREAD

**Issue by zhumj** [flutter/flutter#72857]
After obfuscating the code, the 3rd party plugins such as sqflite and dio cannot be used normally. A complete application will definitely have many third-party plug-ins, and the decision of whether to obfuscate should not be left to third-party plug-ins. I suggest adding a configuration to the main application to decide which files need to be obfuscated and which files do not need to be obfuscated, just like the "proguard-rules.pro" file developed by Android natively.

**Comment by pedromassangocode** [comment]
Hi @zhumj 
I think you can currently do that using proguard-rules.pro.

What are the advantages of this proposal over using proguard-rules.pro?

**Comment by zhumj** [comment]
@pedromassangocode 
"proguard-rules.pro" can choose which dart files not to obfuscate?

**Comment by pedromassangocode** [comment]
Hi @zhumj 
Obfuscation is not enabled by default, if you enable it you have the option to exclude from obfuscation. I think currently you can achieve whatever you want using "proguard-rules.pro".

I don't see any valid argument to consider this as a valid proposal.

**Comment by zhumj** [comment]
@pedromassangocode 
I added the following configuration to "proguard-rules.pro", but got the same result:
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
```
If you can exclude third-party dart plugins in "proguard-rules.pro", but I didn't see it on the documentation.
