### ISSUE TITLE
Text layout twice and cause performance degradation

### ISSUE THREAD

**Issue by Wings006** [flutter/flutter#72861]
That's a HelloWorld demo Text Widget layout trace:
![image](https://user-images.githubusercontent.com/63435250/102970480-88c18f80-4532-11eb-86bf-d3d0ce1142d0.png)
I found flutter text may layout twice, that will cause the  performace degradation. The code below cause this:
![image](https://user-images.githubusercontent.com/63435250/102970683-ef46ad80-4532-11eb-8fd7-6e866d1d029f.png)
In TextWidthBasis.longestLine(Default) mode, when the text is not full of one line, after first layout(), longestLine is the Text real width, and the _paragraph.width is the parent width, so  longestLine != _paragraph.width, that will cause the next layout process. In second layout process, the newWidth is the longestLine, so after second layout(), the _paragraph.width set to the  longestLine's value.
Why it need layout twice in this case? Can it be optimized here？
I make a modify: in TextWidthBasis.longestLine mode, assign the value of longestLine to ParagraphTxt.width_ after first Layout finish, that will avoid the second layout, and also can get the correct layout result.

**Comment by TahaTesser** [comment]
Hi @Wings006 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample to demonstrate this performance issue 
Thank you

**Comment by Wings006** [comment]
flutter doctor -v：
[✓] Flutter (Channel unknown, 1.22.5-0.0.pre.170, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5-0.0.pre.170
    • Framework revision fdcfd7929015cb3154dbe6a8 (6 days ago), 2020-12-17 14:01:23 +0800
    • Engine revision 1.22.4.0-201210033027
    • Dart version 2.10.4

The engine and framework has been modify，but the Text layout code is the same from origin。

The Flutter sdk example "hello_world" can reproduce this case：
`import 'package:flutter/widgets.dart';
void main() =>
  runApp(
    const Center(
      child:
        Text('Hello, world!',
          key: Key('title'),
          textDirection: TextDirection.ltr
        )
      )
    );`

**Comment by Wings006** [comment]
> flutter doctor -v：
> [✓] Flutter (Channel unknown, 1.22.5-0.0.pre.170, on Linux, locale en_US.UTF-8)
> • Flutter version 1.22.5-0.0.pre.170
> • Framework revision fdcfd7929015cb3154dbe6a8 (6 days ago), 2020-12-17 14:01:23 +0800
> • Engine revision 1.22.4.0-201210033027
> • Dart version 2.10.4
> 
> The engine and framework has been modify，but the Text layout code is the same from origin。
> 
> The Flutter sdk example "hello_world" can reproduce this case：
> `import 'package:flutter/widgets.dart'; void main() => runApp( const Center( child: Text('Hello, world!', key: Key('title'), textDirection: TextDirection.ltr ) ) );`

@TahaTesser

**Comment by TahaTesser** [comment]
Hi @Wings006 
Can you please provide steps to get the layout trace as seen in your screenshot?
Thank you

**Comment by Wings006** [comment]
> Hi @Wings006
> Can you please provide steps to get the layout trace as seen in your screenshot?
> Thank you

I'm output the flutter systrace to Android systrace，and use Android systrace.py to get the trace。The steps:
1. add TRACE_EVENT in ParagraphTxt::Layout();
2. use command "python systrace.py -a com.example.helloWorld -b 163840 -o trace.html"   start tracing;
3. click helloWorld flutter app icon start app;
4. when the  “hello world” Text show, stop tracing and get the trace.html, then we can see "hello world" layout do twice in one BegineFrame.

The TRACE_EVENT I add in paragraph_txt.cc:
```
void ParagraphTxt::Layout(double width) {
  TRACE_EVENT0("txt", "ParagraphTxt::Layout");
  std::u16string u16text(reinterpret_cast<const char16_t*>(text_.data()),
                                                           text_.size());
  std::string text(std::wstring_convert<
      std::codecvt_utf8_utf16<char16_t>, char16_t>{}.to_bytes(u16text));
  TRACE_EVENT0("txt", text.c_str());
```

**Comment by chunhtai** [comment]
cc @LongCatIsLooong @justinmc

**Comment by LongCatIsLooong** [comment]
> assign the value of longestLine to ParagraphTxt.width after first Layout finish, that will avoid the second layout, and also can get the correct layout result

Does this work if the text is right-aligned / centered / justified?

**Comment by TahaTesser** [comment]
@Wings006 
Please provide details asked above

**Comment by Wings006** [comment]
> > assign the value of longestLine to ParagraphTxt.width after first Layout finish, that will avoid the second layout, and also can get the correct layout result
> 
> Does this work if the text is right-aligned / centered / justified?

My rough test is OK, I will test it carefully later

**Comment by justinmc** [comment]
CC @GaryQian

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
