### ISSUE TITLE
Form: validator is broken

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7286]
After upgrading flutter 6d4191e98ce6752467bbb819cb5d36ce47497b65 is probably responsible for this. I don't have time at the moment to dive into this (this is basically a reminder for me).

The form fields don't get updated and revalidated on each change event. Using the `text_field_demo.dart` widget logics, when I click my submit button, the fields validate once. When I change the input in those fields after that, the error message doesn't update.

Again I'll come back and dive into this deeper when I have a moment.

**Comment by eseidelGoogle** [comment]
@mpcomplete @Hixie

**Comment by mikemimik** [comment]
I wasn't utilizing the `Form` correctly. I believe this is a non issue. I will close for now.
