### ISSUE TITLE
[google_maps_flutter] New version of Google Maps SDK for iOS available: 4.1.0.0 flutter

### ISSUE THREAD

**Issue by yadsbah** [flutter/flutter#72873]
I have latest google_maps_flutter: ^1.0.6 installed But when I run the Application on iOS Simulator. My app runs Fine but google map is not working.

I get the message in log

```
Google Maps SDK for iOS version: 3.9.0.0
New version of Google Maps SDK for iOS available: 4.1.0.0
```

I tried to add Google map 4.1.0.0 to PodFile But I am getting error when I try to Install Pod or Update

I am on Flutter beta channel

**Comment by anirudh-jwala** [comment]
Refer the [codelab](https://codelabs.developers.google.com/codelabs/google-maps-in-flutter#3) works fine with iOS devices

**Comment by darshankawar** [comment]
@yadsbah Check above mentioned codelab link and see if it helps.

**Comment by Gperez88** [comment]
Same happens to me, i have google_maps_flutter: ^1.2.0 but when I run the Application on iOS Simulator, google map working good but i get he message in log:

```
flutter: ----------------------------------------------------
Google Maps SDK for iOS version: 3.9.0.0
New version of Google Maps SDK for iOS available: 4.1.0.0
```

I tried `flutter clean` and `rm -Rf ios/Pods`

**Comment by dcchristopher** [comment]
https://github.com/flutter/plugins/blob/google_maps_flutter-v1.2.0/packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec

The problem is it calls for a google maps SDK less than 3.10 due to a 3.10 requiring iOS 9. More context: https://github.com/flutter/plugins/pull/2924

**Comment by Sammius** [comment]
All the same, it is not clear how to update it?

**Comment by dcchristopher** [comment]
If your map isn’t working, it has nothing to do with that _warning_. It probably has to do with your API key, key restrictions, etc. The warning will go away when the flutter SDK folks (who also manage the Google Maps plugin) remove (or increase) the version constraint in the pod spec.
