### ISSUE TITLE
Adding ExpansionTile with property initiallyExpanded set to true causes odd behaviour when scrolling

### ISSUE THREAD

**Issue by billy1380** [flutter/flutter#72886]
Developing on Mac OS Catalina 10.15.7

Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (10 days ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)

I have a structure where there is an ExpansionTile inside of a ListView

When initiallyExpanded value is not set the state of the ExpansionTile seems to be preserved after scrolling: where as when the value is set to true, collapsing the tile and scrolling down then up again to the tile results in it being rendered open.

### initiallyExpanded default value

https://user-images.githubusercontent.com/1329727/103033715-01d4dd00-455b-11eb-8080-40b3797d84c7.mov

### initiallyExpanded set to true

https://user-images.githubusercontent.com/1329727/103033794-3d6fa700-455b-11eb-8098-42299e45d6ba.mov

**Comment by iapicca** [comment]
@billy1380 
the behavior you are describing is expected when using a [ListView.builder](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html)
as the widget does not keep the state when not rendered,

a solution to keep the state of the [ExpansionTile](https://api.flutter.dev/flutter/material/ExpansionTile-class.html) is to use [AutomaticKeepAliveClientMixin](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html)
please see the example below

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Material(
        child: ListView.builder(
          itemBuilder: (BuildContext context, int index) => MyTile(index),
        ),
      ),
    ),
  );
}

class MyTile extends StatefulWidget {
  MyTile(this.index) : super(key: ValueKey('tile $index'));
  final int index;
  @override
  _MyTile createState() => _MyTile();
}

class _MyTile extends State<MyTile> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ExpansionTile(title: Text('${widget.index}'));
  }

  @override
  bool get wantKeepAlive => true;
}

```

if this isn't representative of the situation please provide a minimal reproducible code sample

**Comment by billy1380** [comment]
Thanks @iapicca for the quick response... I can understand that the "recycled view" does not keep the state but my query was related to why the state is maintained when a value is not set but it is not when a value is set.

Check out the first video... I open the properties panel... and if the state is lost on scrolling back up to it, it should have lost the state and be painted closed. But instead it has retained the open state.

I tried that multiple times. When the initial value is true, the state is lost if it is default the state is retained.

**Comment by iapicca** [comment]
@billy1380 
can you provide a minimal code sample that represent the issue you are describing

**Comment by billy1380** [comment]
@iapicca here is a minimum code sample, but I cannot recreate the issue with the sample... it must be something else that is the issue... I will close it... thanks again

``` dart
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Expanded state test"),
        ),
        body: ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            return ExpansionTile(
              title: Text("Expanded$index"),
              children: [
                ...[1, 2, 3, 4, 5, 6, 7, 8].map((e) => Padding(
                      padding: EdgeInsets.all(8),
                      child: Text("$index child $e"),
                    ))
              ],
            );
          },
        ),
      ),
    ),
  );
}
```
