### ISSUE TITLE
Text widget with multiline text and TextOverflow.ellipsis is rendering in one line 

### ISSUE THREAD

**Issue by psredzinski** [flutter/flutter#72891]
When you have a **Text** widget with TextOverflow.**ellipsis** it is always rendering in one line, even if it has more space available.

## Steps to Reproduce

I am seeing the same what I can see here:
https://dartpad.dev/aa393c54639630868ee131a75f744cd5?

**Expected results:** Expecting to see more lines of text and ellipsis at the end of the last possible line.

**Actual results:** Text is rendering only in 1 line

**Comment by anirudh-jwala** [comment]
That is the whole point of text overflow, you can mention `maxLines: 4` attribute for more lines based on the number passed

**Comment by anirudh-jwala** [comment]
@fluttergithubbot mark as invalid issue

**Comment by SANSKARJAIN2** [comment]
hi @psredzinski,
you need to provide the `maxLines` property. max Lines property is not provided then rendering is done based on parent widget size. If overflow property is provided then it will render 1 line only and provide the overflow effect. If more than 1 line needs to be rendered with overflow property then you can provide `maxLines` property.
Hope it helps.
Thank you.

**Comment by darshankawar** [comment]
@psredzinski 
This is an intended  behavior. 
Closing this as non-issue. If you disagree, write in comments and I'll reopen it.

**Comment by psredzinski** [comment]
@darshankawar 
How is it then possible to cut lines of text automatically when there is no more place in Container?
I'd like to get ellipsis mode, maxLines set to let's say 100 lines, and then I'd expect ellipsis to be placed earlier, when the text is in a SizedBox and there is no space. 

<img width="272" alt="Zrzut ekranu 2020-12-30 o 17 50 03" src="https://user-images.githubusercontent.com/23390884/103368281-75309e80-4ac7-11eb-9b8a-78c45eb784b7.png">

**Comment by m1n093** [comment]
> @darshankawar
> How is it then possible to cut lines of text automatically when there is no more place in Container?
> I'd like to get ellipsis mode, maxLines set to let's say 100 lines, and then I'd expect ellipsis to be placed earlier, when the text is in a SizedBox and there is no space.
> 
> <img alt="Zrzut ekranu 2020-12-30 o 17 50 03" width="272" src="https://user-images.githubusercontent.com/23390884/103368281-75309e80-4ac7-11eb-9b8a-78c45eb784b7.png">
> 
> https://dartpad.dev/a5cb34533edae8e860351a628358b050?

Found solution?
