### ISSUE TITLE
BoxDecoration with BoxShape.circle doesn't clip backgroundImage

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7289]
A BoxDecoration widget with `shape: BoxShape.circle` doesn't clip its backgroundImage.

One consequence of this is that CircleAvatar doesn't clip its backgroundImage either. See https://github.com/flutter/flutter/issues/5306

Similarly, using CircleAvatar in UserAccountsDrawerHeader doesn't do what's expected. See https://github.com/flutter/flutter/issues/7191.

```
import 'package:flutter/material.dart';

class BoxDecorationBackgroundImageClipFail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Image clip should be a circle'),
      ),
      body: new Center(
        child: new Container(
          width: 100.0,
          height: 100.0,
          decoration: new BoxDecoration(
            shape: BoxShape.circle,
            backgroundColor: Theme.of(context).primaryColor,
            backgroundImage: new BackgroundImage(
              image: new AssetImage('assets/cat.jpg'),
            ),
          ),
        ),
      ),

    );
  }
}

void main() {
  runApp(new MaterialApp(home: new BoxDecorationBackgroundImageClipFail()));
}
```

**Comment by mimigithub-prog** [comment]
you can use the image as SVG file ,so tha you will display the image extactly the way it is. it will also make you to change the color of the image and the background, you can also put the image both in circular shape or any shape of your choice.  install the flutter package for SVG  https://pub.dev/packages/flutter_svg 

example
child: CircleAvatar(
          backgroundColor: Colors.black,
          child: SvgPicture.asset('images/trt.svg',
            color: Colors.red,
          )
      ),
