### ISSUE TITLE
Flutter ImagePicker Plugin (No implementation found for method pickImage) when run on Android simulator.

### ISSUE THREAD

**Issue by exmozz** [flutter/flutter#72898]
Hi!

Have tried all the solutions in similar tickets, but nothing works.

Flutter 1.22.5
image_picker: 0.6.7+17

```
  File _avatar;
  final ImagePicker imagePicker = ImagePicker();

  Future getAvatar() async {

    final _file = await imagePicker.getImage(source: ImageSource.gallery);

    setState(() {
      if (_file != null) {
        _avatar = File(_file.path);
      } else {
        print('No file');
      }
    });

   }
```

Pressing the button results in MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker).

minSDKVersion in build.gradle = 19;

Has this permissions in AndroidManifest:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
```

And application tag is:
```
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="myApp"
        requestLegacyExternalStorage="true"
        android:icon="@mipmap/ic_launcher"> 
```

With this meta-data:
```
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

Nothing works.

On iOs everything is ok.

**Comment by anirudh-jwala** [comment]
Works perfectly for me though, update private variable `_file` to `file` and see if that works. Update application tag

```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="myApp"
        android:requestLegacyExternalStorage="true"
        android:icon="@mipmap/ic_launcher"> 
```

**Comment by coder-Aayush** [comment]
@exmozz can you share what packages you are using?

**Comment by wujianneng** [comment]
我也是一樣，請問是什麼原因

**Comment by darshankawar** [comment]
@exmozz 
You seem to be on older version of Flutter (1.20). Upgrade to latest version (1.22.5, stable) and check again if it helps. Also check this comment https://github.com/flutter/flutter/issues/72898#issuecomment-750842044 and see if it resolves your issue.

**Comment by exmozz** [comment]
> @exmozz
> You seem to be on older version of Flutter (1.20). Upgrade to latest version (1.22.5, stable) and check again if it helps. Also check this comment [#72898 (comment)](https://github.com/flutter/flutter/issues/72898#issuecomment-750842044) and see if it resolves your issue.

I've made a mistake, I've already used flutter 1.22.5. 
Comment [#72898 (comment)](https://github.com/flutter/flutter/issues/72898#issuecomment-750842044) didn't resolve the issue.

**Comment by exmozz** [comment]
> @exmozz can you share what packages/plugins you are using? Also, check that you have properly implemented plugins.

  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+17
  get_it: ^5.0.1
  stacked: ^1.7.6
  video_player: ^1.0.1
  form_field_validator: ^1.0.1
  flutter_countdown_timer: ^1.5.0
  flutter_share: ^1.0.5
  flutter_typeahead: ^1.9.1

  provider: ^4.3.2+2
  dio: ^3.0.10
  dio_firebase_performance: ^0.2.0

  rxdart: ^0.24.1 
  equatable: ^1.2.5
  flutter_i18n: ^0.20.1
  package_info: ^0.4.3
  random_string: ^2.1.0
  shared_preferences: ^0.5.12+4

  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.6.3

  google_sign_in: ^4.5.4
  apple_sign_in: ^0.1.0
  flutter_facebook_login: ^3.0.0
  debug_mode: ^0.1.1

**Comment by darshankawar** [comment]
@exmozz 
Can you try the official `file_picker` plugin [example](https://pub.dev/packages/image_picker/example) and check if you still get the same error ?

**Comment by exmozz** [comment]
> @exmozz
> Can you try the official `file_picker` plugin [example](https://pub.dev/packages/image_picker/example) and check if you still get the same error ?

I use official image_picker plugin and code for picking video is quite similar to that one from your example's link.

**Comment by darshankawar** [comment]
@exmozz 
What does  `final _file = await imagePicker.getImage(source: ImageSource.gallery);` and 
`_avatar = File(_file.path);` return ?
Also, I tried the `image_picker` plugin example and didn't see the exception. I am on latest stable.
Can you provide the entire `flutter run -v` log in formatted text ?

**Comment by exmozz** [comment]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for
method pickImage on channel plugins.flutter.io/image_picker)
[        ] E/flutter ( 7728): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[        ] E/flutter ( 7728): <asynchronous suspension>
[        ] E/flutter ( 7728): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] E/flutter ( 7728): #2      MethodChannelImagePicker.pickImagePath
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
[        ] E/flutter ( 7728): #3      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
[        ] E/flutter ( 7728): #4      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
[        ] E/flutter ( 7728): #5      _ProfileEditPageState.getAvatar (package:ity_app/app/profile/profile_edit.dart:33:37)
[        ] E/flutter ( 7728): #6      _ProfileEditPageState.build.<anonymous closure>.<anonymous closure>
(package:ity_app/app/profile/profile_edit.dart:79:44)
[        ] E/flutter ( 7728): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] E/flutter ( 7728): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] E/flutter ( 7728): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] E/flutter ( 7728): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
[  +10 ms] E/flutter ( 7728): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
[        ] E/flutter ( 7728): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[        ] E/flutter ( 7728): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] E/flutter ( 7728): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] E/flutter ( 7728): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] E/flutter ( 7728): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[   +2 ms] E/flutter ( 7728): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
[        ] E/flutter ( 7728): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] E/flutter ( 7728): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] E/flutter ( 7728): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] E/flutter ( 7728): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] E/flutter ( 7728): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] E/flutter ( 7728): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter ( 7728): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter ( 7728): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter ( 7728): #26     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] E/flutter ( 7728): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] E/flutter ( 7728): 
[+3567911 ms] W/ConnectionTracker( 7728): Exception thrown while unbinding
[  +19 ms] W/ConnectionTracker( 7728): java.lang.IllegalArgumentException: Service not registered: ls@639bdb6
[   +2 ms] W/ConnectionTracker( 7728):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
[        ] W/ConnectionTracker( 7728):  at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
[        ] W/ConnectionTracker( 7728):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
[        ] W/ConnectionTracker( 7728):  at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):1)
[        ] W/ConnectionTracker( 7728):  at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):2)
[        ] W/ConnectionTracker( 7728):  at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):9)
[        ] W/ConnectionTracker( 7728):  at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):3)
[        ] W/ConnectionTracker( 7728):  at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):3)
[        ] W/ConnectionTracker( 7728):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
[        ] W/ConnectionTracker( 7728):  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] W/ConnectionTracker( 7728):  at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):5)
[+1889743 ms] E/flutter ( 7728): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found
for method pickImage on channel plugins.flutter.io/image_picker)
[  +13 ms] E/flutter ( 7728): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[        ] E/flutter ( 7728): <asynchronous suspension>
[        ] E/flutter ( 7728): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] E/flutter ( 7728): #2      MethodChannelImagePicker.pickImagePath
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
[        ] E/flutter ( 7728): #3      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
[        ] E/flutter ( 7728): #4      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
[        ] E/flutter ( 7728): #5      _ProfileEditPageState.getAvatar (package:ity_app/app/profile/profile_edit.dart:33:37)
[        ] E/flutter ( 7728): #6      _ProfileEditPageState.build.<anonymous closure>.<anonymous closure>
(package:ity_app/app/profile/profile_edit.dart:79:44)
[        ] E/flutter ( 7728): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] E/flutter ( 7728): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] E/flutter ( 7728): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] E/flutter ( 7728): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
[        ] E/flutter ( 7728): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
[        ] E/flutter ( 7728): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
[        ] E/flutter ( 7728): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] E/flutter ( 7728): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] E/flutter ( 7728): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] E/flutter ( 7728): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] E/flutter ( 7728): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
[        ] E/flutter ( 7728): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] E/flutter ( 7728): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] E/flutter ( 7728): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] E/flutter ( 7728): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] E/flutter ( 7728): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] E/flutter ( 7728): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter ( 7728): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter ( 7728): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter ( 7728): #26     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] E/flutter ( 7728): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] E/flutter ( 7728): `

**Comment by darshankawar** [comment]
@exmozz 
There was similar [issue](https://github.com/flutter/flutter/issues/60793) reported while back. Can you try [this](https://github.com/flutter/flutter/issues/60793#issuecomment-654643037) code sample and check if you still get same error ?

**Comment by exmozz** [comment]
> @exmozz
> There was similar [issue](https://github.com/flutter/flutter/issues/60793) reported while back. Can you try [this](https://github.com/flutter/flutter/issues/60793#issuecomment-654643037) code sample and check if you still get same error ?

Changed my code to this one in code sample, but still the same error. I would say that my code was quite similar to this one from code sample, just different variables names.

`  Future<File> getAvatar() async {

    File _image;
    final picker = ImagePicker();
    
    final pickedFile = await picker.getImage(source: ImageSource.camera);
    print('PickedFile: ${pickedFile.toString()}');

    setState(() {
      _image = File(pickedFile.path);
    });
    if (_image != null) {
      return _image;
    }
    return null;

  }`

**Comment by darshankawar** [comment]
@exmozz 
As requested earlier, can you provide what does `print('PickedFile: ${pickedFile.toString()}');` , `_image = File(pickedFile.path);` and `return _image;` return ?

**Comment by exmozz** [comment]
> @exmozz
> As requested earlier, can you provide what does `print('PickedFile: ${pickedFile.toString()}');` , `_image = File(pickedFile.path);` and `return _image;` return ?

Not sure how to provide you with this info, as I've got the error while executing `getImage` method and it is before `print('PickedFile: ${pickedFile.toString()}'); , _image = File(pickedFile.path);  return _image; `

**Comment by coder-Aayush** [comment]
> > @exmozz can you share what packages/plugins you are using? Also, check that you have properly implemented plugins.
> 
> cupertino_icons: ^0.1.3
> image_picker: ^0.6.7+17
> get_it: ^5.0.1
> stacked: ^1.7.6
> video_player: ^1.0.1
> form_field_validator: ^1.0.1
> flutter_countdown_timer: ^1.5.0
> flutter_share: ^1.0.5
> flutter_typeahead: ^1.9.1
> 
> provider: ^4.3.2+2
> dio: ^3.0.10
> dio_firebase_performance: ^0.2.0
> 
> rxdart: ^0.24.1
> equatable: ^1.2.5
> flutter_i18n: ^0.20.1
> package_info: ^0.4.3
> random_string: ^2.1.0
> shared_preferences: ^0.5.12+4
> 
> firebase_core: ^0.5.3
> firebase_analytics: ^6.3.0
> firebase_auth: ^0.18.4
> firebase_crashlytics: ^0.2.4
> firebase_messaging: ^7.0.3
> firebase_dynamic_links: ^0.6.3
> 
> google_sign_in: ^4.5.4
> apple_sign_in: ^0.1.0
> flutter_facebook_login: ^3.0.0
> debug_mode: ^0.1.1

I think you have an unimplemented plugin. For me, I have not set up ```flutter_facebook_login```, which cause this error

**Comment by darshankawar** [comment]
@exmozz 
Try per above comment and see if it works.

**Comment by exmozz** [comment]
@darshankawar @coder-Aayush thank you so much, removing flutter_facebook_login fixed it!

By the way, I've already tried to remove it before, but looks like I didn't run flutter clean and didn't reinstall the app on the emulator.

Anyway, that's really bad situation when some plugin that is not used in the part of code crashes the app, and debug tells you that issues is with another one plugin.

**Comment by darshankawar** [comment]
Closing this based on comment above.

**Comment by afdesk** [comment]
> @darshankawar @coder-Aayush thank you so much, removing flutter_facebook_login fixed it!
> 
> Anyway, that's really bad situation when some plugin that is not used in the part of code crashes the app, and debug tells you that issues is with another one plugin.

@exmozz thank you very much! your comment is really helped me for `flutter-facebook-auth` plugin.

ps. when I asked the author of `flutter-facebook-auth` to pay attention on this issue, he deleted my commend and locked me )
