### ISSUE TITLE
Mac build_tests failing on PRs

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#72899]
Pull requests appear to be blocked right now due to an issue with the `Mac Build_tests` shard.

Some sample runs:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests/4927/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests/4926/overview

Some affected PRs:
https://github.com/flutter/flutter/pull/72833
https://github.com/flutter/flutter/pull/72829

Also reported by @darrenaustin as blocking additional PRs.

**Comment by darrenaustin** [comment]
Other example PRs:

#72792
#72838

**Comment by godofredoc** [comment]
The problem with those builders have been fixed. Please retry the build on the failing PRs

**Comment by godofredoc** [comment]
This was fixed by using xcode 12.3 version.
