### ISSUE TITLE
plugins are installed in android studio but still flutter doctor is showing its not installed . please help to remove this error

### ISSUE THREAD

**Issue by shadow-recruit** [flutter/flutter#72906]
_Originally posted by @mahimakaushik-oss in https://github.com/flutter/flutter/issues/72623#issuecomment-749322662_

This has come to light in the past week. Many people including me have been facing this issue. 

Operating system: Windows 10
Installed: Android Studio 4.1 (Flutter and Dart Plugins installed), VS Code 1.52 (both plugins installed)
Licenses: All accepted

After running the command `flutter doctor`, it shows that the plugins of flutter and dart are not installed in Android Studio even when they are. I am not facing any issue while developing an app, but `flutter doctor` not giving a green light is bothersome.

![image](https://user-images.githubusercontent.com/47930146/103048450-adf6e200-45b4-11eb-9567-d5da34eaae1b.png)

**Comment by anirudh-jwala** [comment]
`flutter channel master`

**Comment by darshankawar** [comment]
@shadow-recruit 
This is already [fixed](https://github.com/flutter/flutter/issues/67986). Switch to latest master and check if it helps.
Closing this as already fixed and no need for tracking.
