### ISSUE TITLE
flutter build ios-framework ignore plugin vendored_frameworks

### ISSUE THREAD

**Issue by Y-JunKang** [flutter/flutter#72909]
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel unknown, 1.22.2, on macOS 11.0.1 20B50, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

</details>

**What I do**

1. create flutter module named MyFlutterModule
2. create flutter plugin named MyFlutterPlugin
3. add some vendored_frameworks in MyFlutterPlugin.podspec for example:
![image](https://user-images.githubusercontent.com/39218059/103057518-aa765180-45da-11eb-91dc-aa94be5ac124.png)

4. add dependency in MyFlutterModule.pubspec like:
![image](https://user-images.githubusercontent.com/39218059/103057618-f9bc8200-45da-11eb-96e7-54e3d174e680.png)

5. flutter build ios-framework --output=./build_out
6. there is no Masonry.framework found in build_out directory

**Comment by TahaTesser** [comment]
Hi @Y-JunKang 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a GitHub repository
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
