### ISSUE TITLE
AnimatedList itemBuilder Runs Twice

### ISSUE THREAD

**Issue by hasimyerlikaya** [flutter/flutter#72915]
Normally when I remove an element from the AnimatedList, the itemBuilder runs twice.
Is there any way to prevent this, why does it work like that?

![image](https://user-images.githubusercontent.com/7986394/103068212-b7407880-45cd-11eb-8809-0d2e88429478.png)

![image](https://user-images.githubusercontent.com/7986394/103068366-071f3f80-45ce-11eb-800b-f786e1e9d3a4.png)

`[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en)
• Flutter version 1.22.5 at /Users/hasimyerlikaya/flutter
• Framework revision 7891006299 (13 days ago), 2020-12-10 11:54:40 -0800
• Engine revision ae90085a84
• Dart version 2.10.4`

**Comment by iapicca** [comment]
@hasimyerlikaya 
can you provide a complete minimal reproducible code sample instead of a snippet
please avoid posting screenshot when simply posting the code or gist is sufficient

**Comment by hasimyerlikaya** [comment]
I ran a test by creating a clean project.
The result is as I said before.

When an item is removed, the itemBuilder works twice.

Sample project;
https://github.com/hasimyerlikaya/animated_list_test

![image](https://user-images.githubusercontent.com/7986394/103117460-8a4a9f00-467b-11eb-88de-454d8375aa48.png)

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!


```

</details>

```
I/flutter (10219): 0
I/flutter (10219): 1
I/flutter (10219): 2
I/flutter (10219): 3
I/flutter (10219): 4
I/flutter (10219): 5
I/flutter (10219): 6
I/flutter (10219): 7
I/flutter (10219): 8
I/flutter (10219): 0
I/flutter (10219): 1
I/flutter (10219): 2
I/flutter (10219): 3
I/flutter (10219): 4
I/flutter (10219): 5
I/flutter (10219): 6
I/flutter (10219): 7
I/flutter (10219): 8
```

**Comment by hasimyerlikaya** [comment]
> flutter doctor -v
> ```
> I/flutter (10219): 0
> I/flutter (10219): 1
> I/flutter (10219): 2
> I/flutter (10219): 3
> I/flutter (10219): 4
> I/flutter (10219): 5
> I/flutter (10219): 6
> I/flutter (10219): 7
> I/flutter (10219): 8
> I/flutter (10219): 0
> I/flutter (10219): 1
> I/flutter (10219): 2
> I/flutter (10219): 3
> I/flutter (10219): 4
> I/flutter (10219): 5
> I/flutter (10219): 6
> I/flutter (10219): 7
> I/flutter (10219): 8
> ```

Is it normal for him to print each element twice like this?

**Comment by justinmc** [comment]
CC @Piinks

**Comment by xu-baolin** [comment]
@hasimyerlikaya Hi,
I can tell you why they are built twice.
The first time, replace the item with a red container needs to rebuild.
The 2nd time, the red container disappears also needs to rebuild.

So I think it is normal.

Also said by @Hixie ` In general, you should assume that all widgets can rebuild at any time, that they don't is mostly just an optimisation.` https://github.com/flutter/flutter/issues/11655#issuecomment-348287396

**Comment by hasimyerlikaya** [comment]
@xu-baolin It seemed a little strange to me that it works this way. Because when this happens, the animations work again because the widgets after the widget I deleted are formed again and this is not good.

**Comment by Hixie** [comment]
The builder running twice should not cause animations to change. Can you post some brief sample code that shows what you mean?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
