### ISSUE TITLE
Flutter: Runner.app/Info.plist does not exist. The Flutter “Thin Binary” build phase must run after “Copy Bundle Resources”

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter#72914]
After upgrading flutter to flutter 1.22.4. I am getting the below error while building the Xcode Project.

> Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".

**Already tried the below options:**

1. Flutter clean and run.
2. Removed derived data, clean project, and rebuild.
3. - rm -Rf ios/Pods
    - rm ios/Podfile
    - rm -Rf ios/.symlinks
    - rm -Rf ios/Flutter/Flutter.podspec
    - rm -Rf ios/Flutter/Flutter.framework
    - flutter run

After trying all the above options still getting the same error.

**Flutter doctor:**

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/dhavalkansara/flutter 1.22.4
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhavalkansara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 9D65DC5D-5DE8-485A-886F-FF26C0466391 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

- Project files structure:
<img width="390" alt="Screen Shot 2020-12-24 at 12 17 42 PM" src="https://user-images.githubusercontent.com/44993081/103068001-2e800780-45e2-11eb-8135-ace1d4d129eb.png">

- Info.plist location in build setting:
<img width="1033" alt="Screen Shot 2020-12-24 at 12 06 04 PM" src="https://user-images.githubusercontent.com/44993081/103067714-94b85a80-45e1-11eb-9d28-0c9cdca0d4a2.png">

**Comment by vilashraj** [comment]
Yes, even I am also facing the same issue. This issue started after upgrading the flutter from **1.20.2** to **1.22.5**. I have also tried the solutions mentioned at https://stackoverflow.com/questions/64636941/unable-to-compile-flutter-application-with-flutter-1-22-3/64951775#64951775 but none of them worked for me.

**Comment by DhavalRKansara** [comment]
- **Solution:**


Go to `Runner(target app) > Build Phases > Run Script` and update the run script with `/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build`.


Also, verify that `Runner(target app) > Build Phases > This Binary` contains below scripts as suggested in [XCode 11.4 Support][1] by the flutter team. 

    /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
    /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin

 


  [1]: http://Xcode%2011.4%20Support
