### ISSUE TITLE
Failed to extract manifest

### ISSUE THREAD

**Issue by EuvolaGG** [flutter/flutter#72917]
Hello..I just created a new project on VSCODE and got an error when I tried to run it immedaitely without writing any code.I did flutter analyze and flutter doctor but no issue was found.The error in android studio doesn't apply since am using VS CODE.Why is this happening??
BELOW IS WHAT AM SEEING IN MY CONSOLE:-
PS C:\Users\NM\Desktop\memo1> flutter analyze
Running "flutter pub get" in memo1...                               0.8s
Analyzing memo1...
No issues found! (ran in 7.4s)
PS C:\Users\NM\Desktop\memo1> flutter run
Launching lib\main.dart on TECNO P904 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        60.2s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
CreateProcessW failed 193
Failed to extract manifest from APK: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\NM\AppData\Local\Android\sdk\build-tools\29.0.2\aapt.EXE dump xmltree
  C:\Users\NM\Desktop\memo1\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).
PS C:\Users\NM\Desktop\memo1> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 1.20.0, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by anirudh-jwala** [comment]
Install Flutter and Dart plugins in Android studio and change flutter channel to `master`

**Comment by EuvolaGG** [comment]
I have installed but still getting the same problem

**Comment by pedromassangocode** [comment]
Hi @EuvolaGG 
Looks like you are using an old version of Flutter.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by EuvolaGG** [comment]
I did all that but doesnt work

**Comment by pedromassangocode** [comment]
Hi @EuvolaGG 
Please provide your `flutter doctor -v`.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
