### ISSUE TITLE
After execute 'flutter clean' under macos/ios, Flutter.framework directory still exists with many scraps 

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#72913]
After I finished debugging my app under macos/ios, I cleaned the project using 'flutter clean' in order to copy a backup of my code, and I found the size of code is very large, and I found it was the directory ios/Flutter/Flutter.framework that having large size. and I have to delete  Flutter.framework manually.  Is it possible to delete Flutter.framework  directory when excecuting 'flutter clean'?

Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale zh-Hans-CN)

**Comment by TahaTesser** [comment]
Hi @heroqin 
When executing `flutter clean` on beta channel, app sizes goes from `334MB` to `1.1MB`. Are you using packages? 
```bash
tahatesser@Tahas-MacBook-Pro flutter_beta % flutter clean
Cleaning Xcode workspace...                                      2,988ms
Deleting build...                                                   26ms
Deleting .dart_tool...                                               1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
tahatesser@Tahas-MacBook-Pro flutter_beta % 
```

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
