### ISSUE TITLE
ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: Permission denied

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#72911]
Hi,
    When I copy my flutter app code from windows7 to macos (code compiled OK under windows7), and try to compile it under macos,  vscode always complain:
```bash
   /Users/lixs/Library/Developer/Xcode/DerivedData/Runner-cjifyopugqdswrdmyjwoaebglmqf/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-EBE0AEC4DD4A07BCE76D13C6.sh: line 2: /Users/lixs/Desktop/geanapp/gphone/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: Permission denied
    Command PhaseScriptExecution failed with a nonzero exit code
```
   and I have to mannually execute: chmod a+x Pods-Runner-frameworks.sh under macos, then compile OK, but it is inconvenient.
  the following is flutter doctor output:

<details> 
<summary>flutter doctor</summary> 

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @heroqin 
Can you please provide your `flutter run --verbose > flutter_run.log` logs (please provide this log file), and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pkmangukiya** [comment]
To complete solve this! go here:- https://stackoverflow.com/a/65473410/10563627

**Comment by TahaTesser** [comment]
@heroqin 
Please try the possible solution above

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
