### ISSUE TITLE
Pointer event resampling works poorly at low frame-rates

### ISSUE THREAD

**Issue by dreveman** [flutter/flutter#72924]
Pointer event resampling only works well for apps that run at 60 FPS and rarely jank (miss frames). That's because frame production currently drives sampling. Ideally, frame production should be taken into account in order to align sampling time to presentation time but sampling and input event dispatch should continue when the app is not producing frames or when frames are taking a long time to produce.

**Comment by justinmc** [comment]
CC @gspencergoog

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/73042 was reverted by https://github.com/flutter/flutter/pull/76179

**Comment by dreveman** [comment]
Fixed by this re-land: https://github.com/flutter/flutter/pull/76195
