### ISSUE TITLE
PaginatedDataTable should support zoomable.

### ISSUE THREAD

**Issue by svsno1** [flutter/flutter#72923]
When I look at the data in a PaginatedDataTable, it is difficult to see all the content. So, I want to be able to zoom in and out of the PaginatedDataTable. Case of DataTable, I can do it because it has a defined width and height but PaginatedDataTable is built differently and I cannot intervene further.

Thanks for your attention!

**Comment by darshankawar** [comment]
@svsno1 
Can you provide  a sample use case showing the issue and a proposal as what would you like to add to the widget which will help to resolve your issue ?
Thanks.
