### ISSUE TITLE
Losing storage after each compilation even after using flutter clean 

### ISSUE THREAD

**Issue by hadran9** [flutter/flutter#72928]
Hello everyone, I'm new to flutter and I'm facing an issue, a **storage problem** to be exact. 

Each time I compile a **flutter project** I'm losing approximately **1.3 GB** from my hard drive permanently .

I've searched the **WEB** and found the command `flutter clean`. And what this command does to me, it just removes the `build` and `dart_tool` folders and that gives me back approximately **350 MB** from the taken **2 GB**.

I'm still learning flutter so I'm working for the moment just with the base project of flutter (I mean by the base project here, when we create a new project by using `flutter create project_name` and compile it directly).

So let's put down the numbers: 
+ Lets say that I have approximately **20 GB** free hard drive storage.
+ If I hit compile or `flutter run` I've just lost approximately **2 GB**.
+ I stop the execution of `flutter run`.
+ I use the command `flutter clean`, and it gives me back just ~ **350 MB** back.
+ I've just lost ~ **1.5 GB** of storage.
+ Each time I hit compile or `flutter run` to the base project or any flutter project the same process happens again.

The only workaround I've found to escape the repeated compile process is to use the ***hot reload*** option, which I have no problem with it.

I'm using **VS Code** on **Windows 10**.

**Target Platform: Windows 10**
**Target OS version/browser: API 28 / Android 9**
**Devices: Pixel 2 Emulator**

## Logs

<details>
<summary>Logs</summary>

### `flutter analyze`

```console
C:\Users\Ayoub\Documents\flutter_projects\flutter_basics>flutter analyze
Running "flutter pub get" in flutter_basics...                      5.9s
Analyzing flutter_basics...                                             
No issues found! (ran in 93.7s)
```

### `flutter doctor -v`

```console
C:\Users\Ayoub\Documents\flutter_projects\flutter_basics>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.22.5 at C:\Users\Ayoub\Flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ayoub\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Ayoub\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Ayoub\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @hadran9 
I cannot reproduce the issue on Macbook Pro. What happens here is that after I stop the debugging process the memory gets back to where it was before. Tested with emulator (Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)).

Can you please share how are you evaluating the memory usage?


<details><summary></summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.137 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 8f5d0371af (2 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by hadran9** [comment]
Hi @pedromassango, so sorry for the late response.

> Can you please share how are you evaluating the memory usage?

Well I've used  [spacesniffer](http://www.uderzo.it/main_products/space_sniffer/download.html).

Once that've been said, when I used space sniffer I've noticed that the consumed space was gone into the **AVD** each time. 

So I don't think that the issue should be open here anymore because I think that's an issue of **android studio**. Regardless, I've found that I can use ***flutter hot reload*** to avoid recompiling each time, and after a few **hot reloads** I need to delete the AVD and create a new one again. I know it's not an efficient solution but it's the only way how I can get back some of my lost storage. 

I'm closing this issue, and if you need any more details please feel free to reopen it back and ask me about anything, I'm happy to help.
