### ISSUE TITLE
Importing dependencies or packages taking long on linux

### ISSUE THREAD

**Issue by Aaris-Kazi** [flutter/flutter#72925]
I'm working on a music player app I'm trying to install dependencies for audio/ music still it is taking too long for download I really don't know why

[music] flutter pub get
Running "flutter pub get" in music...                           
Could not resolve URL "https://pub.dartlang.org".

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

The above is the message

**Comment by iapicca** [comment]
@Aaris-Kazi 
can you provide your flutter doctor -v 
and after running `flutter clear`
the output of `flutter pub get -v`

**Comment by Aaris-Kazi** [comment]
## flutter doctor -v
![flutter](https://user-images.githubusercontent.com/40735215/103164887-e0b00d00-4836-11eb-8fbd-ac1b9369d918.png)

## flutter pub get -v
![pub get](https://user-images.githubusercontent.com/40735215/103164896-fe7d7200-4836-11eb-857d-92db8beb4c0f.png)

It was working fine now it has some issue I don't know how

**Comment by TahaTesser** [comment]
Hi @Aaris-Kazi 
Please make sure you have stable internet. If you're in a restricted, make sure you can access servers using a VPN. 
can you provide your `flutter doctor -v `
and after running `flutter clean`
the output of `flutter pub get -v`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
