### ISSUE TITLE
Need tests for BoxDecoration hitTesting

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7293]
Tests for BoxDecoration hitTesting are needed when shape is BoxShape.circle or borderRadius is non-null.

I would expect to find them in packages/flutter/test/widgets/box_decoration_test.dart or packages/flutter/test/painting/box_painter_test.dart

See https://github.com/flutter/flutter/pull/7292

**Comment by Hixie** [comment]
@HansMuller does #10438 address this to your satisfaction?

**Comment by HansMuller** [comment]
The new test does cover BoxShape.circle, but it doesn't  created rounded rectangles (borderRadius is non-null). Should be simple to add tests for that, I can do it.

**Comment by TheBiirb** [comment]
I believe this no longer an issue now @HansMuller ,right?

**Comment by darrenaustin** [comment]
Talked with @HansMuller, this was indeed fixed with #47915.
