### ISSUE TITLE
When I upgrade flutter to beta version  in MAC OSX 10.10.5 , I am not able to run any flutter commands 

### ISSUE THREAD

**Issue by Akhilkumargolla** [flutter/flutter#72935]
## Steps to Reproduce

1. flutter channel beta
2. flutter upgrade

## Logs

<details>
<summary>Logs</summary>

```
```

flutter doctor -v 
Building flutter tool...

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xc
pid=32672, thread=7939, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32672 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32689, thread=3587, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10312b480
  pc 0x00007fff92f1fa90 fp 0x000000010741fe60 __dynamic_cast+0x21
  pc 0x00007fff88b9706b fp 0x000000010741fe70 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff88bc1d57 fp 0x000000010741ffa0 allowedEVRootsForLeafCertificate+0x65
  pc 0x00007fff88bc0d0c fp 0x0000000107420230 Security::KeychainCore::Trust::evaluate(bool)+0x52
  pc 0x00007fff88bc0b19 fp 0x0000000107420290 SecTrustEvaluate+0x29
  pc 0x0000000103121bb9 fp 0x0000000107420380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x000000010333159f fp 0x0000000107420cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x000000010332e6f6 fp 0x0000000107420d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x136

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7ffefffffff0
  pc 0x000000010332ed34 fp 0x0000000107420dd0 dart::MessageHandler::TaskCallback()+0x1e4
Aborting re-entrant request for stack trace.
Aborting re-entrant request for stack trace.
Aborting re-entrant request for stack trace.
Aborting re-entrant request for stack trace.
Aborting re-entrant request for stack trace.
Aborting re-entrant request for stack trace.
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32689 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x4d555448
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32700, thread=8195, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=103929480
  pc 0x00007fff92f1fa90 fp 0x000000010a3fff50 __dynamic_cast+0x21

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
  pc 0x00007fff88b9706b fp 0x000000010a3fff60 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32700 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32712, thread=8195, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=101018480
  pc 0x00007fff92f1fa90 fp 0x0000000107ffff50 __dynamic_cast+0x21
  pc 0x00007fff88b9706b fp 0x0000000107ffff60 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff88ce5ffe fp 0x0000000107ffffa0 Security::CFToVector<Security::CssmData, OpaqueSecCertificateRef*, &(cfCertificateData(OpaqueSecCertificateRef*))>::CFToVector(__CFArray const*)+0x92

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32712 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32722 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32733, thread=3587, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10411c480

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
  pc 0x00007fff92f1fa90 fp 0x000000010840ff50 __dynamic_cast+0x21
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff1
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32733 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32746, thread=7683, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10930a480
  pc 0x00007fff92f1fa90 fp 0x00000001100ffe60 __dynamic_cast+0x21
  pc 0x00007fff88b9706b fp 0x00000001100ffe70 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff88bc1d57 fp 0x00000001100fffa0 allowedEVRootsForLeafCertificate+0x65
  pc 0x00007fff88bc0d0c fp 0x0000000110100230 Security::KeychainCore::Trust::evaluate(bool)+0x52
  pc 0x00007fff88bc0b19 fp 0x0000000110100290 SecTrustEvaluate+0x29

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32746 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x4d555448

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffffffffff8
Aborting re-entrant request for stack trace.

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
pid=32763, thread=6403, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32763 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
version=2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "macos_x64"
pid=32775, thread=6147, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10560f480
  pc 0x00007fff92f1fa90 fp 0x000000010ba7fe60 __dynamic_cast+0x21
  pc 0x00007fff88b9706b fp 0x000000010ba7fe70 Security::KeychainCore::Certificate::required(OpaqueSecCertificateRef*)+0x2b
  pc 0x00007fff88bc1d57 fp 0x000000010ba7ffa0 allowedEVRootsForLeafCertificate+0x65
  pc 0x00007fff88bc0d0c fp 0x000000010ba80230 Security::KeychainCore::Trust::evaluate(bool)+0x52
  pc 0x00007fff88bc0b19 fp 0x000000010ba80290 SecTrustEvaluate+0x29

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Aborting re-entrant request for stack trace.
/Users/Akhil007/Flutter/flutter/bin/internal/shared.sh: line 20: 32775 Abort trap: 6           (core dumped) "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up.

</details>

**Comment by pedromassangocode** [comment]
Hi @Akhilkumargolla 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
