### ISSUE TITLE
Your app(s) are vulnerable to Intent Redirection

### ISSUE THREAD

**Issue by snchawla** [flutter/flutter#72942]
Hello Google Play Developer,

We reviewed Dr Fitness Plus, with package name com.nikswebnapp.drfitnesspls, and found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please migrate your apps to use the updated software as soon as possible and increment the version number of the upgraded APK.

Fulleter doctor
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale en-IN)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\sakshi\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\AdoptOpenJDK\jdk8u192-b12\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] VS Code (version 1.52.1)
    • VS Code at C:\Users\S.N.Chawla\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Mi A2 (mobile) • 477b029 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.

pubsspec.yaml

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  dio: ^3.0.10
  carousel_pro: ^1.0.0
  image_ink_well: ^0.1.0
  path_provider: ^1.5.1
  image_picker: ^0.6.3+1
  image_cropper: ^1.3.1
  gx_file_picker: ^1.9.0+2
  fluttertoast: ^3.1.0
  permission_handler: ^5.0.1+1
  geolocator: ^5.1.3
  location: ^3.0.2
  shared_preferences: ^0.5.7+1
  youtube_player_flutter: ^7.0.0+7
  gallery_view: ^0.0.4
  flutter_html: ^1.0.2
  introduction_screen: ^1.0.9
  #cashfree: ^0.1.1
  cashfree_pg: ^0.0.4+9
  firebase_core: ^0.5.0
  firebase_database: ^4.1.1
  cloud_firestore:
  firebase_messaging: 7.0.0 #6.0.13
  flutter_local_notifications: 1.4.4+4 #1.4.0
  #new_version: ^0.0.5
  grouped_checkbox: ^1.0.0
  url_launcher: ^5.7.2
  change_app_package_name: ^0.1.2

#  file_picker: ^2.0.12

**Comment by snchawla** [comment]
Please give me solutions

**Comment by sidrao2006** [comment]
Hey @snchawla ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Please see https://flutter.dev/community for resources and asking queries doubts and assistance on personal code. You may get some help if you post it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=flutter) and if you need help with your code, please check https://www.reddit.com/r/flutterhelp/.

Thanks

**Comment by pedromassangocode** [comment]
Hi @snchawla 
This is not an issue with Flutter, please see https://github.com/flutter/flutter/issues/66901#issuecomment-707006823.

Closing as invalid.
