### ISSUE TITLE
A non-null String must be provided to a Text widget

### ISSUE THREAD

**Issue by a120476536** [flutter/flutter#72943]
A non-null String must be provided to a Text widget;
`
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════

A non-null String must be provided to a Text widget.

'package:flutter/src/widgets/text.dart':

Failed assertion: line 381 pos 10: 'data != null'

The relevant error-causing widget was: 

 MaterialApp file:///D:/asProject/flutter_mianzu/lib/main.dart:24:12

════════════════════════════════════════════════════════════════════════════════════════════════════
`

Like the title, it was normal yesterday. I suddenly reported this when I opened it today, and the login and registration are all unavailable. There is no positioning, only the error message. Where can I check it? And I seem to have encountered a problem. AndroidStudio does not seem to work for flutter breakpoint debugging.

**Comment by iapicca** [comment]
@a120476536 
the problem might be with your code rather than a big with flutter
can you provide your `flutter doctor -v` and most importantly a minimal reproducible code sample

**Comment by pedromassangocode** [comment]
Hi @a120476536 
Please provide what were asked above.

**Comment by justinmc** [comment]
@a120476536 Here's the relevant source code if it helps:

https://github.com/flutter/flutter/blob/8f5d0371afeffa533e4efcbaf7f2394af4811af9/packages/flutter/lib/src/widgets/text.dart#L378-L381

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
