### ISSUE TITLE
ToolBarOptions doesn't fit well in ios when fonts are large

### ISSUE THREAD

**Issue by zhishan33** [flutter/flutter#72955]
<img width="312" alt="WeChat4bd2cc281ab9126d4f78b26af30473ce" src="https://user-images.githubusercontent.com/10361490/103134505-82771300-46ec-11eb-80c5-23c4c1956338.png">

**Comment by darshankawar** [comment]
@zhishan33 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
