### ISSUE TITLE
Could not determine the dependencies of task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by BrightCode1** [flutter/flutter#72964]
I just installed flutter in my new laptop and ran an app which got stuck at running `Running Gradle task 'assembleDebug'` i then did `gradlew clean build` which after installing `"Install Android SDK Platform 29 (revision: 5)" finished.` it threw an error saying

>FAILURE: Build failed with an exception.
 What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.core:core:1.1.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.core:core:1.1.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.pom'.
               > dl.google.com
   > Could not resolve androidx.collection:collection:1.1.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.collection:collection:1.1.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/collection/collection/1.1.0/collection-1.1.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/collection/collection/1.1.0/collection-1.1.0.pom'.
               > dl.google.com
   > Could not resolve androidx.viewpager:viewpager:1.0.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.viewpager:viewpager:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.pom'.
               > dl.google.com
   > Could not resolve androidx.loader:loader:1.0.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.loader:loader:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.pom'.
               > dl.google.com
   > Could not resolve androidx.activity:activity:1.0.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.activity:activity:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.0.0/activity-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.0.0/activity-1.0.0.pom'.
               > dl.google.com
   > Could not resolve androidx.lifecycle:lifecycle-viewmodel:2.0.0.
     Required by:
         project :app > io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4 > androidx.fragment:fragment:1.1.0
      > Could not resolve androidx.lifecycle:lifecycle-viewmodel:2.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.pom'.
               > dl.google.com
 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 Get more help at https://help.gradle.org
BUILD FAILED in 13m 54s
Exception: Gradle task assembleDebug failed with exit code 1

**flutter doctor -v**
>D:\flutter\Project\ohms>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 6.3.9600], locale en-GB)
    • Flutter version 1.22.5 at D:\flutter\Sdk\flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bright\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.
[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\bright\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0
[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
• No issues found!

please how do i go about this. Is there something am supposed to do

**Comment by pedromassangocode** [comment]
Hi @BrightCode1 
Looks like the tool was not able to get the required dependencies to build the app. Please make sure you have a stable internet connection and try to run the same command again.

If the issue persists, please provide your `flutter run --verbose` and your `pubspec.yaml`.
Thank you
