### ISSUE TITLE
show unity on Flutter 

### ISSUE THREAD

**Issue by JuneLeo** [flutter/flutter#72960]
I wanted to show Unity on Flutter, so I customized The Platformview in the Android project; The flutter side I take two ways to receive the SurfaceView;|

- one：

> flutter code

     ` AndroidView(
        viewType: 'unity_view',
        onPlatformViewCreated: onPlatformViewCreated,
      );`

> android code
      
     ` FlutterUnityView(PluginUnityPlugin plugin, Context context, int id) {
        this.context = context;
        PluginUnityPlugin.views.add(this);
        this.plugin = plugin;
        this.id = id;
        view = new FrameLayout(context);
        view.setBackgroundColor(Color.TRANSPARENT);
        surfaceView = new UnitySurfaceView(context);       //it‘s UnityPlayer
        view.addView(surfaceView);
        }
        @Override
       public View getView() {
        return view;
         }

`

This way on huawei phones, the second start will appear white screen

https://user-images.githubusercontent.com/22164576/103138201-1fe13f80-470b-11eb-9203-75882d8f9056.mp4

- two

> flutter code
    
     ` return PlatformViewLink(
            viewType: viewType,
            surfaceFactory: (BuildContext context,
                PlatformViewController controller) {
                controller.clearFocus();
              return AndroidViewSurface(
                controller: controller,
                gestureRecognizers: const <
                    Factory<OneSequenceGestureRecognizer>>{
                },
                hitTestBehavior: PlatformViewHitTestBehavior.opaque,
              );
            },
            onCreatePlatformView: (PlatformViewCreationParams params) {
              return PlatformViewsService.initSurfaceAndroidView(
                  id: params.id,
                  viewType: viewType,
                  layoutDirection: TextDirection.ltr,
                  creationParamsCodec: StandardMessageCodec(),
                  onFocus: () {
                    print("unity onFocus");
                  }
              )
                ..addOnPlatformViewCreatedListener(params
                    .onPlatformViewCreated)..addOnPlatformViewCreatedListener(
                    onPlatformViewCreated)
                ..create();
            }
        )`

> android code
      
     ` FlutterUnityView(PluginUnityPlugin plugin, Context context, int id) {
        this.context = context;
        PluginUnityPlugin.views.add(this);
        this.plugin = plugin;
        this.id = id;
        view = new FrameLayout(context);
        view.setBackgroundColor(Color.TRANSPARENT);
        surfaceView = new UnitySurfaceView(context);       //it‘s UnityPlayer
        view.addView(surfaceView);
        }
        @Override
       public View getView() {
        return view;
         }

`

In this way, on the vivo phone, the PlatformViewLink will always be floating on the page. Switching the page, I call unityplayer.pause()

https://user-images.githubusercontent.com/22164576/103138297-042a6900-470c-11eb-9f93-d4ee858974f5.mp4

- Page structure

Scaffold () + PageView

please help me！

**Comment by iapicca** [comment]
@JuneLeo 
this doesn't seem a bug with flutter or a feature request, but rather assistance for your code
I recommend to follow the link at `I want help writing my application` in the [new issue selection](https://github.com/flutter/flutter/issues/new/choose)

**Comment by JuneLeo** [comment]
> @JuneLeo
> this doesn't seem a bug with flutter or a feature request, but rather assistance for your code
> I recommend to follow the link at `I want help writing my application` in the [new issue selection](https://github.com/flutter/flutter/issues/new/choose)

I think it was a bug with flutter, because there was no problem with most phones, only some phones had this problem!

**Comment by darshankawar** [comment]
@JuneLeo 
I am guessing you are using https://pub.dev/packages/flutter_unity_widget. I'd suggest you to open this issue and follow-up in plugin owner's repo.
Closing this. If you disagree, write in comments and I'll reopen.

**Comment by iapicca** [comment]
@JuneLeo 
about unity support you may follow up here https://github.com/flutter/flutter/issues/18509

**Comment by JuneLeo** [comment]
I solved the problem by using TextureView replace SurfaceView;
