### ISSUE TITLE
'flutter packages get' overwrites symlinked .packages files

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#7296]
In fuchsia development setup, the `.packages` files are generated as part of fuchsia build and we create `.packages` file as a symbolic link to the fuchsia-generated `.packages` file, in order to make dart analysis work correctly with all the fuchsia dependencies.

The problem is that when we run `flutter packages get` when there is a symlinked `.packages` file in the directory, the tool overwrites the contents of the original file that the symlink points to, and this breaks any subsequent fuchsia build. The same happens when getting the packages as part of `flutter test`.

I think `flutter packages get` should delete the existing .packages file (whether or not it is a symbolic link) and newly create one.

**Comment by abarth** [comment]
The `flutter` tool just shells out to `pub`.  You probably want to file this issue in this tracker:

https://github.com/dart-lang/pub/issues/new

**Comment by yyoon** [comment]
Sure. I'll do that.
