### ISSUE TITLE
Installing Flutter SDK 1.22.5-stable fails early in the process

### ISSUE THREAD

**Issue by bbeliveau** [flutter/flutter#72977]
I’m getting trouble installing flutter on Windows 10 (windows SDK 1.22.5-stable) for the first time. I tried many times following the instructions given here: [https://flutter.dev/docs/get-started/install/windows](https://flutter.dev/docs/get-started/install/windows).

I also tried with the previous SDK (1.22.4-stable). I was able to get further in the installation process but still, the installation process is not going as expected.
So, I’m asking for help for the most up to date SDK 1.22.5-stable.
I have downloaded the windows SDK (1.22.5-stable) zip file and extracted it under my « Documents » folder. I did update my path. When I run flutter doctor, from the power shell, I’m getting this:

![Powershell 1][1] 

…followed by…

![Powershell 2][2]
 
I search forums about this and did not find a solution. I saw people suggesting deleting the bin\cache\ folder and retry flutter doctor. But before doing so I have noted that the cache folder was containing the dart-sdk folder but it was empty (I’m not sure that is normal).

So I have deleted the cache folder and ran flutter doctor again. I got the same result.
Next I tried to run flutter doctor again without deleting the cache folder. This time I got this:

![Powershell 3][3]
 
I don’t know what to do now. 

  [1]: https://i.stack.imgur.com/vsQCj.png
  [2]: https://i.stack.imgur.com/pHhYz.png
  [3]: https://i.stack.imgur.com/3joeV.png

**Comment by liodali** [comment]
try to re-install it manually like  you did it  in the first time
just download the  zip file  and unzip in existing path and overwrite  all files

**Comment by hamdikahloun** [comment]
Hi @bbeliveau 
Can you please provide your `flutter doctor -v` ?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
