### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by chrissxYT** [flutter/flutter#72971]
## Use case

Being able to distribute a fat binary instead of having to give your users a whole directory is nicer.

## Proposal

For macOS this is basically not a concern, because Apple likes directories and transparently makes them work more like files, but on Windows statically linked EXEs are more convenient. On Linux the problem is less obvious, but static linking would still be nice, of course. `flutter build` should just have a flag to statically link.

**Comment by iapicca** [comment]
@chrissxYT please look at this [answer](https://github.com/flutter/flutter/issues/33835#issuecomment-498938488)

**Comment by PixelToast** [comment]
Unfortunately we do not plan on supporting static linking and bundling flutter apps into a single `.exe` with the same reason as the issue linked above.

A more user-friendly approach you can take today is to create a self-extracting installer, there are quite a few solutions such as the built in `iexpress` and other third party utilities.
