### ISSUE TITLE
Unable to read the license file `../LICENSE` for the spec `integration_test

### ISSUE THREAD

**Issue by swarakorn** [flutter/flutter#72989]
I use Flutter with Android studio and when I run

The Error output from CocoaPods is shown as below

Do you know how to solve the problem?

![Screen Shot 2563-12-27 at 13 22 58](https://user-images.githubusercontent.com/76641150/103165183-f3cad900-4846-11eb-9efb-c309898cb04b.png)

Launching lib/main.dart on iPhone 8 in debug mode...

Running pod install...

CocoaPods' output:

↳

  Preparing
.
.
.
.
.

Error output from CocoaPods: ↳

[!] Automatically assigning platform `ios` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] A license was specified in podspec `integration_test` but the file does not exist - /Users/a/AndroidStudioProjects/flutter_app5/ios/.symlinks/plugins/integration_test/LICENSE

[!] Unable to read the license file `../LICENSE` for the spec `integration_test (0.0.1)`

[!] Unable to read the license file `../LICENSE` for the spec `integration_test (0.0.1)`

Error running pod install 
Error launching application on iPhone 8.

**Comment by darshankawar** [comment]
@swarakorn 
Provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample.

**Comment by jmagman** [comment]
This repros every time.

This is just a warning, you don't need to worry about it.  However, we should fix the podspec so this warning isn't emitted.

https://github.com/flutter/flutter/blob/32e1e00e2edb1b9ad278b2130890d2b7b22ac733/packages/integration_test/ios/integration_test.podspec#L12
