### ISSUE TITLE
[web]: Document how to do flutter development on chromeos

### ISSUE THREAD

**Issue by ghchinoy** [flutter/flutter#72982]
Unable to run `flutter run` or see web or chrome devices

Chrome OS / pixelbook 2017 / Version 88.0.4324.37 (Official Build) beta (64-bit)

`flutter doctor` / `flutter devices` does not have web-server or chrome targets for building an app. While I can do `flutter build web` and appropriate artifacts are generated in the app's `build/web` directory, this is suboptimal.

My main objective is do develop flutter web apps on ChromeOS.

Followed [install steps](https://flutter.dev/docs/get-started/web). Unclear what steps are needed to reset environment or which steps I may have missed to have a more complete flutter development experience  (i.e. `flutter run` and IDE integration).

<details>
<summary> <code>flutter doctor -v</code>
</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /home/ghchinoy/flutter
    • Framework revision 8f89f6505b (11 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ghchinoy/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • Google Pixelbook (mobile) • emulator-5554 • android-x64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
</details>

Flutter config does have `--enable-web`

```
Settings:
  enable-web: true
```

**Comment by wzslr321** [comment]
Try to run `flutter run -d web --web-port 8000` command, it fixed similar problem here: https://github.com/flutter/flutter/issues/40478

**Comment by ghchinoy** [comment]
Thank you for the response @wzslr321 , but there's no device named `web` so that command doesn't work.

```
 $ flutter run -d web --web-port 8000
No devices found with name or id matching 'web'
```

**Comment by wzslr321** [comment]
I am actually facing a very similar problem on archlinux than,  but my error log in flutter doctor is:
```
 Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
```

I have got exactly the same error log with no devices found because I do not see a webserver in flutter devices either, so I wish  to get help too.

**Comment by wzslr321** [comment]
Hey @ghchinoy , I fixed it on archlinux by adding execute permissions for google chrome to every user and resetting CHROME_EXECUTABLE environment variable, now I am able to  run it using `flutter run -d web-server` command and everything works cool

**Comment by agplusman** [comment]
On a chromebook to run flutter for web development I found it best to install Chromium browser from Crostini (Linux Beta);
$ sudo apt install chromium
Then in bashrc make sure to add this; 
export CHROME_EXECUTABLE=/usr/bin/chromium

Everything works fine thereafter including development with Android Studio

**Comment by ghchinoy** [comment]
Thanks, with additional install of chromium on crostini on ChromeOS, a `chrome` device is created so `flutter run -d chrome` does work.

This does put a lot of stress on the underlying cpu and I was hoping for a more integrated approach in the future (either via flag, lacros, etc.).

**Comment by jaydanurwin** [comment]
I agree with the comment above. This is definitely a sub-optimal solution. Having to install a separate Chromium instance is going to bog down the CPU unnecessarily. What's strange is it worked with `flutter run -d web --web-port 8000` when I filed #40478 but now that command just returns `No devices found with name or id matching 'web'`

**Comment by starquake** [comment]
`xdg-open "https://put-url-here"` so is there a workaround available?

**Comment by timsneath** [comment]
This is a good issue. Adding some suggestions for a path forward, along with formally documenting the current workaround, in #121462.
