### ISSUE TITLE
Use the dependency in your build.gradle ` implementation "androidx.annotation:annotation:1.1.0"`

### ISSUE THREAD

**Issue by tagesholly1** [flutter/flutter#72986]
Use the dependency in your build.gradle ` implementation "androidx.annotation:annotation:1.1.0"`
And change the imports _import android.support.annotation.**X**_ to _import androidx.annotation.**X**_ should fix the error if you are using android X libs.

_Originally posted by @BugsBunnyBR in https://github.com/flutter/flutter/issues/35239#issuecomment-512854924_

**Comment by iapicca** [comment]
@tagesholly1 
your issue seems to be a re-post of a message from a closed issue,
can you provide more details including your `flutter doctor -v` and your `flutter run -v`
