### ISSUE TITLE
Performance Overlay broken for Flutter Gallery

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#7298]
The performance overlay no longer works for the Flutter Gallery

<img width="642" alt="screen shot 2016-12-20 at 10 46 19 pm" src="https://cloud.githubusercontent.com/assets/871169/21376826/2c44aed0-c706-11e6-94f2-5d8426342c03.png">

**Comment by eseidelGoogle** [comment]
This definitely was broken recently, but I thought @chinmaygarde fixed it?  Maybe it's been fixed in the engine but the engine hasn't rolled into flutter/flutter yet?

**Comment by chinmaygarde** [comment]
This issue has been fixed but the engine has not been rolled to pull it in. An attempt was made but subsequently reverted due to a failing test.

**Comment by chinmaygarde** [comment]
This fixed was rolled in a while ago.
