### ISSUE TITLE
Support for loading platform-specific icons

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7299]
Per https://github.com/flutter/flutter/pull/7297#pullrequestreview-13884591

Currently, if you want the platform-specific version of the back icon, you need to write something like this:
```
  IconData _backIcon() {
    switch (Theme.of(context).platform) {
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return Icons.arrow_back;
      case TargetPlatform.iOS:
        return Icons.arrow_back_ios;
    }
    assert(false);
    return null;
  }
```
Perhaps we should add a utility function to Icons, like Icons.for(TargetPlatform), so you'd write this instead:

```
Icons.for(Theme.of(context).platform).arrow_back
```

**Comment by Hixie** [comment]
I'd be wary of adding that much overhead for all icons.

How about a specific method just for this icon, `Icons.arrow_back_for(Theme.of(context).platform)`?

**Comment by Hixie** [comment]
It would require a bit of tweaking to the script so that it adds breadcrumbs from the relevant real icons to this method.

**Comment by cbracken** [comment]
From a discoverability point of view, it's a little annoying to have the one-off static methods on `Icons`, though as you say a tweak to the docs mitigates that a bit. Given how few of these I'd expect there to be, agreed that keeping it all consts seems like a fair trade though.

Quick look at Apple's [icons page](https://developer.apple.com/ios/human-interface-guidelines/graphics/system-icons/) in the HIG and it doesn't look like many other widely-used icons where we'd want to use the iOS version. The main candidates look like the 'action' (share) icon and maybe the delete (trash can) icon.

**Comment by Hixie** [comment]
@abarth may have opinions on this given his work on the Cupertino library.

**Comment by xster** [comment]
I'm tentatively closing this. The decision of the icon to use should be in the 'application'-side Material `BackButton` rather than in the supply side Icons definitions.
