### ISSUE TITLE
StatelessWidget should provide a `markDirty()` method

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#72997]
There are cases where nothing has changed in the widget config, but you still want to easily rebuild a widget. For example, 
```
class ComparisonStack extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      Row(key: ValueKey(Random().nextDouble()), 
         children: [
             Expanded(child: Child1()),
             Expanded(child: Child2()),
      ]),
      FlatButton(
        onPressed: () => markDirty(),
        child: Text("Rebuild"),
      )
    ]);
  }
}
```

In this case I am intentionally using a random key in the Row, so the children can be rebuilt from a simple btn press in the parent. This is for debugging and testing purposes which I think are valid use cases?

Without a `markDirty()`, this is cludgy, requiring some sort of Builder and a notifier.

You could also imagine some use case where a Stateless parent receives a a Notification from a child, and then wants to rebuild the entire sub-tree because some siblings are presumed to have changed as well, or maybe you just want to delegate rebuilds to some widget(s) below that can fire `ScheduleABuildPlease` Notifications upwards and expect them to be handled.

**Comment by britannio** [comment]
I suggest that you read the documentation regarding the build method and stateful widgets.
https://api.flutter.dev/flutter/widgets/StatelessWidget/build.html
https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html
```dart
class ComparisonStack extends StatefulWidget {
  @override
  _ComparisonStackState createState() => _ComparisonStackState();
}

class _ComparisonStackState extends State<ComparisonStack> {
  double value = Random().nextDouble();
  
  void _updateValue() {
    setState(() {
      value = Random().nextDouble();
    });
  }
  
  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      Row(key: ValueKey(value),
          children: [
            Expanded(child: Child1()),
            Expanded(child: Child2()),
          ]),
      FlatButton(
        onPressed: _updateValue,
        child: Text("Rebuild"),
      )
    ]);
  }
}
```

**Comment by esDotDev** [comment]
I suggest you don't assume I don't understand StatelessWidget.

Compare line counts between the two examples. Like I said in op: "**this is cludgy**"

**Comment by PixelToast** [comment]
A few counter-arguments:

Calling `Random().nextDouble()` violates the principle that build methods should be pure. The framework can re-build your widget at any point in time, resetting the children even when the button wasn't pressed.

The code @britannio provided is how I would do it, but with a UniqueKey instead of generating a random ValueKey.

A `markDirty` method wouldn't work since `Widget`s don't have an inherent context, though if you really want to force stateless widgets to rebuild this would work fine:

```dart
extension on BuildContext {
  void markDirty() => (this as Element).markNeedsBuild();
}
```

`StatefulBuilder` would also do what you want, as it provides a callback that rebuilds the widget.

But if the point of providing a new key is to reset the state of each child, why not hoist their state into ComparisonStack, like with a controller class or bloc?

**Comment by esDotDev** [comment]
The primary use case I see for this is around testing and development, you may want, for whatever reason, (performance testing, regression testing, feature development) to be able to easily rebuild a view on tick.

But I also subscribe to another principle is that you can't possibly begin to imagine all the use cases people will come up with. 

This is just a pragmatic argument from the viewpoint of, hoisting the state is a bit of a hassle, this is a valid use case, why not just make the quality of life improvement and give developers this hook. Like you say, there's many easy easy to do this in a round-about-way, why force the extra lines?

**Comment by PixelToast** [comment]
I couldn't find any existing issues on this so I'd like opinions from someone else on the team if this is something we would want to make more accessible
