### ISSUE TITLE
GestureDetector doesn't receive events when it's child is a ListView or a ScrollView.

### ISSUE THREAD

**Issue by parsa-fs** [flutter/flutter#72996]
## Use case
Basically, when you want to receive the gesture events that happen on a widget, you'd wrap that widget inside a GestureDetector.
That works fine, except when that child widget is a ListView or a SingleChildScrollView. In those scenarios, GestureDetector doesn't receive those events and you need to use a Listener widget, which receives low-level gestures and has pretty basic gesture callbacks. And it is a pain to add thresholding deltas to prevent it from detecting taps instead of drag starts.

## Proposal
It would be awesome if flutter had this ability to receive gestures when a ListView or a ScrollView is inside a GestureDetector.

**Comment by iapicca** [comment]
@parsa-fs 
[GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) seems to catch the `onTap` as expected
does the code below represent the issue you are describing?

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () => print('gesture detected'),
            child: ListView.builder(
              itemBuilder: (context, _) => const Center(
                child: FlutterLogo(size: 80),
              ),
            ),
          ),
        ),
      ),
    );

```

**Comment by bernaferrari** [comment]
I think this is an old duplicated issue which seems like a bug. You should use Listener because yes.

**Comment by parsa-fs** [comment]
> @parsa-fs
> [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) seems to catch the `onTap` as expected
> does the code below represent the issue you are describing?
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(
>       MaterialApp(
>         home: Material(
>           child: GestureDetector(
>             behavior: HitTestBehavior.opaque,
>             onTap: () => print('gesture detected'),
>             child: ListView.builder(
>               itemBuilder: (context, _) => const Center(
>                 child: FlutterLogo(size: 80),
>               ),
>             ),
>           ),
>         ),
>       ),
>     );
> ```
Hey @iapicca ,
Thank you for the reply, yeah onTap works(but sometimes, I don't know why), but my main problem is detecting dragging events, when you have a callback for let's say onVerticalDragUpdate, it doesn't detect the drags.

**Comment by darshankawar** [comment]
@parsa-fs 
Can you provide a use case with code sample and proposal code sample that would resolve the issue ?
Thanks.

**Comment by justinmc** [comment]
+1 to a full code sample.

Flutter uses a gesture arena instead of something like event bubbling on the web.  It can be tough to listen for the same gesture in two different nested widgets.  [Here is an example](https://github.com/flutter/flutter/blob/8f5d0371afeffa533e4efcbaf7f2394af4811af9/packages/flutter/lib/src/widgets/text_selection.dart#L1490) of how we do this for taps in the framework.

**Comment by parsa-fs** [comment]
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _bottomSheetHeight = 200;
  final _maxBottomSheetHeight = 300;
  final _minBottomSheetHeight = 200;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("Hello"),
      ),
      bottomSheet: GestureDetector(
        onVerticalDragUpdate: (details) {
          setState(() {
            if (details.delta.dy < 0 &&
                (_bottomSheetHeight + details.delta.dy) <=
                    _maxBottomSheetHeight) {
              _bottomSheetHeight -= details.delta.dy;
            } else if (details.delta.dy > 0 &&
                (_bottomSheetHeight - details.delta.dy) >=
                    _minBottomSheetHeight) {
              _bottomSheetHeight -= details.delta.dy;
            }
          });
        },
        child: Container(
          height: _bottomSheetHeight,
          width: double.infinity,
          color: Colors.red,
          child: ListView(
            children: [
              Text("kjds"),
              Text("kjds"),
              Text("kjds"),
              Text("kjds"),
              Text("kjds"),
              Text("kjds"),
              Text("kjds"),
            ],
          ),
        ),
      ),
    );
  }
}

```
I know that here in this code I can use a DraggableScrollableBottomSheet, but If I have a dynamic child in the outer ListView, and if that child is another ListView which I can't pass it my own controller, it fails to handle the height of the bottom sheet.

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.


```

</details>

**Comment by parsa-fs** [comment]
It's interesting too, that the GestureDetector widget inherits from the Listener widget, but it can't receive the drag gestures, though Listener can.

**Comment by justinmc** [comment]
Could you achieve what you want by listening to scroll changes?

**Comment by parsa-fs** [comment]
Unfortunately no, because I need to know when the user starts dragging and when it ends.
Basically, I need to listen to onVerticalDragStart, onVerticalDragUpdate, and onVerticalDragEnd.

**Comment by TahaTesser** [comment]
Check https://github.com/flutter/flutter/issues/73039

**Comment by parsa-fs** [comment]
As I understood, there aren't many similarities between these two issues. I want to wrap my ListView inside a GestureDetector, but that issue is the opposite.
I wish there was a property for ListView to make it not to prevent the gestures to reach their ancestors.

**Comment by parsa-fs** [comment]
Hey everyone,
Any updates?

**Comment by EduardoNatale** [comment]
Maybe this can help you
https://pub.dev/packages/sliding_up_panel

Try to compare what you need with the package property panelBuilder

**Comment by Ruoyu2021** [comment]
FLUTTER在点击事件拦截上有很多问题，谁有解决办法吗？比如https://github.com/flutter/flutter/issues/62833应该也是事件拦截问题。

**Comment by Ruoyu2021** [comment]
https://stackoverflow.com/questions/52910339/flutter-gesturedetector-apparently-doesnt-receive-drag-events-when-it-has-a-li
Use Listener instead of GestureDetector, Listener can receive touch event.

**Comment by TheOnlyBeardedBeast** [comment]
I have a similar issue, I would like to achieve a "semantic zoom" effect, I wrapped my scrollView with a GestureDetector, but sometimes it just ignores my pinchzoom, and starts scrolling the scrollview, even if multiple drags are happening.

**Comment by TheOnlyBeardedBeast** [comment]
Ok so I went through the implementation of the scrollview, it uses a scrollbale, which has a defined RawGestureDetector with Vertical or Horizontal drag gesture, there is a listener in the scrollable, I added a pointer counter by using the Listener onPointer events, in case the number of pointers > 1 I disable the drag gesture recognition and I cancel any running drags, after this a gesture detector works above a customScrollview in my case.

**Comment by 1232209** [comment]
> 

can I get your code,appreciate!

**Comment by TheOnlyBeardedBeast** [comment]
@1232209 
`GestureScrollView.dart` and  `GestureScrollable.dart` in this repo https://github.com/TheOnlyBeardedBeast/FlutterWindowsUI `lib` folder.

**Comment by Piinks** [comment]
From the original code sample, this appears to be working as expected, a GestureDetector above a vertical list view will not receive a vertical drag because the ListView claims that gesture. There was a suggestion to listen to scroll notifications - you can listen to the start, update and end of the scrolling with notifications.

**Comment by JaffaKetchup** [comment]
Just a note for anyone reading in, 'flutter_map' has also had this problem (see https://github.com/fleaflet/flutter_map/issues/1308). Will update this if there is any news.
