### ISSUE TITLE
google_maps_flutter FATAL EXCEPTION

### ISSUE THREAD

**Issue by leonardompereira** [flutter/flutter#73008]
Steps to Reproduce:
1 - Performed all the configuration of the package page: google_maps_flutter.
2 - I copied the sample code in the README tab
3 - replaces the code in the main.dart file with the copied code
4 - I run the app on my smartphone.

details:
Error Log

Launching lib\main.dart on LG M700 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:58642/BCjLxJ2DwvU=/ws
Syncing files to device LG M700...
I/zzbz    (11120): Making Creator dynamically
I/DynamiteModule(11120): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule(11120): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule(11120): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/ResourceType(11120): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType(11120): ResTable_typeSpec entry count inconsistent: given 5411, previously 5412
W/System  (11120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000274/n/armeabi-v7a
W/System  (11120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000274/n/armeabi
I/Google Maps Android API(11120): Google Play services client version: 12451000
I/Google Maps Android API(11120): Google Play services package version: 204713018
W/Google Maps Android API(11120): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where indoor is not supported, isIndoorEnabled() will continue to return the value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'. The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes unavailable on those map types.
E/AndroidRuntime(11120): FATAL EXCEPTION: main
E/AndroidRuntime(11120): Process: com.example.flutter_app, PID: 11120
E/AndroidRuntime(11120): java.lang.AbstractMethodError: abstract method "void io.flutter.plugin.platform.PlatformView.onFlutterViewAttached(android.view.View)"
E/AndroidRuntime(11120): 	at io.flutter.plugin.platform.VirtualDisplayController.onFlutterViewAttached(VirtualDisplayController.java:181)
E/AndroidRuntime(11120): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:233)
E/AndroidRuntime(11120): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime(11120): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(11120): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(11120): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(11120): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AndroidRuntime(11120): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(11120): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/AndroidRuntime(11120): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(11120): 	at android.app.ActivityThread.main(ActivityThread.java:6349)
E/AndroidRuntime(11120): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11120): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/AndroidRuntime(11120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
W/DynamiteModule(11120): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(11120): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(11120): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/System  (11120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000273/n/armeabi-v7a
W/System  (11120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000273/n/armeabi

Flutter Analyze:
C:\Users\leona\OneDrive\MobileDeveloper\Flutter\flutter_app>flutter analyze
Analyzing flutter_app...
No issues found! (ran in 95.9s)

Flutter doctor:
C:\Users\leona\OneDrive\MobileDeveloper\Flutter\flutter_app>flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [versÃ£o 10.0.19042.685], locale pt-BR)
    • Flutter version 1.26.0-1.0.pre at D:\Flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android-Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android-Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • LG M700 (mobile) • LGM70055b7d251 • android-arm    • Android 7.1.1 (API 25)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!

Att,

**Comment by pedromassangocode** [comment]
Hi @leonardompereira 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Hi @leonardompereira 
I cannot reproduce the issue on latest master channel running on Redmi 5 Plus (mobile). There is no crash after running the sample code.

<details><summary>Logs</summary>

```
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:52369/I7RY_2TJ1Fw=/ws
Syncing files to device Redmi 5 Plus...
W/PlatformViewsController( 6510): Creating a virtual display of size: [1080, 2160] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2030].
W/ResourceType( 6510): No package identifier when getting name for resource number 0x00000000
I/zzbz    ( 6510): Making Creator dynamically
W/zygote64( 6510): Unsupported class loader
W/zygote64( 6510): Skipping duplicate class check due to unsupported classloader
W/zygote64( 6510): miui_dex2oat:　OatFile: /data/user_de/0/com.google.android.gms/app_chimera/m/00000187/oat/arm64/DynamiteLoader.odex Compiler-Filter = speed
I/DynamiteModule( 6510): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule( 6510): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule( 6510): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/ResourceType( 6510): No package identifier when getting name for resource number 0x00000000
W/ResourceType( 6510): ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType( 6510): ResTable_typeSpec entry count inconsistent: given 5411, previously 5412
I/DynamiteLoaderV2Impl( 6510): [71] Mapsdynamite
W/zygote64( 6510): Unsupported class loader
W/zygote64( 6510): miui_dex2oat: oat file of /data/user_de/0/com.google.android.gms/app_chimera/m/0000018b/MapsDynamite.apk is not exists
W/zygote64( 6510): miui_dex2oat: /data/user_de/0/com.google.android.gms/app_chimera/m/0000018b/MapsDynamite.apk: Fall back to running out of the original dex file.
W/ResourceType( 6510): No package identifier when getting name for resource number 0x00000000
I/Google Maps Android API( 6510): Google Play services client version: 12451000
I/Google Maps Android API( 6510): Google Play services package version: 204713021
I/zygote64( 6510): Do partial code cache collection, code=58KB, data=40KB
I/zygote64( 6510): After code cache collection, code=58KB, data=40KB
I/zygote64( 6510): Increasing code cache capacity to 256KB
W/Google Maps Android API( 6510): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where indoor is not supported, isIndoorEnabled() will continue to return the value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'. The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes unavailable on those map types.
E/GoogleMapController( 6510): Cannot enable MyLocation layer as location permissions are not granted
W/DynamiteModule( 6510): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 6510): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule( 6510): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
I/DynamiteLoaderV2Impl( 6510): [71] Googlecertificates
W/zygote64( 6510): Unsupported class loader
W/zygote64( 6510): miui_dex2oat: oat file of /data/user_de/0/com.google.android.gms/app_chimera/m/0000018a/GoogleCertificates.apk is not exists
W/zygote64( 6510): miui_dex2oat: /data/user_de/0/com.google.android.gms/app_chimera/m/0000018a/GoogleCertificates.apk: Fall back to running out of the original dex file.
W/ResourceType( 6510): No package identifier when getting name for resource number 0x00000000

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.137 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 8f5d0371af (2 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by leonardompereira** [comment]
@pedromassangocode 
I'm running on the dev channel, because I'm using the web flutter.
Is that the problem?

**Comment by pedromassangocode** [comment]
Still not able to reproduce on latest `dev` or `master` channel. 

<img height="720" src="https://user-images.githubusercontent.com/67424416/103219307-9bb2d600-491d-11eb-9b25-4025199b1249.png">

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-1.0.pre at /Users/pedromassango/dev/SDKs/flutter_dev
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by leonardompereira** [comment]
Launching lib\main.dart on LG M700 in debug mode...
Running Gradle task 'assembleDebug'...
Checking the license for package Android SDK Build-Tools 29.0.2 in D:\Workspace\Android\SDK\licenses
Warning: License for package Android SDK Build-Tools 29.0.2 not accepted.
Checking the license for package Android SDK Platform 29 in D:\Workspace\Android\SDK\licenses
Warning: License for package Android SDK Platform 29 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
     platforms;android-29 Android SDK Platform 29
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: D:\Workspace\Android\SDK

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
> Failed to install the following Android SDK packages as some licences have not been accepted.

This seems unrelated to the first crash logs, please make sure you accept the License for Android SDK Build-Tools before using it. See https://stackoverflow.com/a/49759126.

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and provide the logs once the app crashes?
Thank you

**Comment by leonardompereira** [comment]
@pedromassangocode 
Thanks.
