### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by Juanepaktho** [flutter/flutter#73009]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@Juanepaktho 
please describe the issue and provide your `flutter doctor -v `and your `flutter run -v`
