### ISSUE TITLE
Camera 6.3.1

### ISSUE THREAD

**Issue by leszekkrol** [flutter/flutter#73002]
while recording video on version 6.3.1 of plugins camera crash occurs with the error below. The error occurs both in our source code and in the sample code to use a camera.

the error appears while calling the method

stopVideoRecording (). then ((XFile file) {
       if (mounted) setState (() {}); 
       if (file! = null) {
         showInSnackBar ('Video saved to $ {file.path}');
         File takenVideo = File (file.path);
       }
     });

Downloading the file causes an error

E/AndroidRuntime(32209): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.camera.PictureCaptureRequest.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(32209): at io.flutter.plugins.camera.Camera$3.onCaptureFailed(Camera.java:291)
E/AndroidRuntime(32209): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32209): at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
E/AndroidRuntime(32209): at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
E/AndroidRuntime(32209): at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(32209): at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(32209): at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(32209): at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(32209): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32209): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(32209): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by mvanbeusekom** [comment]
This issue has been fixed with PR #3375, which has just been merged to the `master` branch awaiting release.
