### ISSUE TITLE
Our artifacts are too big

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7300]
My bin/cache directory is nearly half a gigabyte. That's almost half a gigabyte more than I expected. :-)

![](https://i.imgflip.com/1gdhp4.jpg)

For example, just the gen_snapshot binary for one platform is about 70MB.

Half a gigabyte takes over ten hours to download on a 128Kbps link, assuming that it actually works at that speed the whole time. In practice, over ten hours you are likely to have download errors and have to retry several times. This means our product is basically unusable in environments like on a train or plane with terrible shared wifi, or in remote areas with unreliable links. Not to mention that the artifacts alone take up one fortieth (2.5%) of my 20GB partition, and downloading them takes over one quarter of my 2GB monthly mobile download cap.

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/6491.

Maybe the first step is for us to track the total size of all our artifacts on our dashboard?  @yjbanov?

**Comment by yjbanov** [comment]
How about we measure the following two numbers?

- The size of a clean Flutter checkout (currently 65MB)
- The size of Flutter after running `flutter doctor` (currently 494MB)

I can add this to the dashboard. What should be our baseline and what should be our goal?

**Comment by Hixie** [comment]
Wow, 65MB is big. Maybe we should tell people to use those flags that limit how much history is downloaded or something.

There's several things we should be doing here:
- [ ] Limiting the size of the initial repo clone.
- [ ] Not downloading artifacts until they're needed.
- [ ] Reducing the size of artifacts (especially those we ship to end-users).

The total size of all the artifacts could be quite big, since it should be proportional to the number of artifacts and that would be proportional to the number of supported platforms or development features (e.g. AOT vs debug).

So maybe the key metric is "size of biggest set of artifacts that can get downloaded at once". Right now that's all of them (since we always download all of them), but eventually that will drop as we get them on-demand.

As to the baseline for what getting the artifacts should be: assume a 2Mbps link (average Internet speed in India), and a 1 minute window before people get tired of waiting (just guessing). That's about 15MB per group of artifacts.

**Comment by yjbanov** [comment]
> Not downloading artifacts until they're needed.

OTOH not downloading eagerly will indeed require an internet connection when you are on the go. Also, you'll need either Xcode or Android Studio, which weigh multiple GB each. So I think going from nothing to a complete Flutter setup will require a good internet connection regardless.

**Comment by Hixie** [comment]
You don't need Android Studio, you need the Android SDK and NDK. (But yes, those are big, unfortunately.) And hopefully one day we can get away with not needing XCode. In any case, those are both under another brand so they won't affect people's opinions of us as much.

For people who want to be able to work offline, we'll have the cache pre-populate feature.
