### ISSUE TITLE
[UserAccountsDrawerHeader] Add an option for changing profile image size

### ISSUE THREAD

**Issue by burekas7** [flutter/flutter#73012]
Regarding UserAccountsDrawerHeader.

## Use case
Currently there is no option for setting the account profile image size.
It fixed on const size of 72 x 72.

## Proposal
Please add an option in the constructor or anything else to set the size of the 'currentAccountPicture'.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/user_accounts_drawer_header.dart#L57

You can also read about this here:
https://stackoverflow.com/a/57454207/12837721

Thanks.

**Comment by justinmc** [comment]
That sounds reasonable to me.  This is open for PRs if anyone wants to try it.

**Comment by burekas7** [comment]
Hi,
I made a PR regarding this issue:
https://github.com/flutter/flutter/pull/73102

**Comment by burekas7** [comment]
I would be glad if someone may help me with the process of the PR (Tests, License, etc...)
Thanks.

**Comment by burekas7** [comment]
This feature was added officially to this beta sdk release: 
1.26.0-17.3.pre 

PR: https://github.com/flutter/flutter/pull/73105
https://github.com/flutter/flutter/compare/1.26.0-17.3.pre...master

Releases: https://flutter.dev/docs/development/tools/sdk/releases?tab=windows 

Thanks to each and everyone who contributed.
@GaspardMerten
@justinmc 
@AlexV525 
@shihaohong 

Closed.
