### ISSUE TITLE
Text and Checkbox cannot be aligned,

### ISSUE THREAD

**Issue by levenzz** [flutter/flutter#73015]
Container(
                // color: Colors.green,
                height: 17,
                margin: EdgeInsets.only(top: 26.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[

                  Text("自动登录",
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 12.0, color: Color(0xff606266)),
                  ),

                    Transform.scale(
                      scale: 0.7,
                      alignment: Alignment.center,
                      child: new [Checkbox](url)(
                        value: autoLogin,
                        onChanged: (bool value) {
                          setState(() {
                            autoLogin = value;
                          });
                        },
                        activeColor: Colors.blue,
                      ),
                    ),
                  ],
                ),
              ),

![image](https://user-images.githubusercontent.com/23116476/103183867-15cc6600-48f0-11eb-91cc-fab823792cfa.png)

**Comment by ggichure** [comment]
this is more suited as a stackoverflow question

**Comment by levenzz** [comment]
> this is more suited as a stackoverflow question
> 
> wrap this with an Expanded Widget , else play around with padding
> 
> `Text("自动登录", textAlign: TextAlign.center, style: TextStyle(fontSize: 12.0, color: Color(0xff606266)), ),`

**Comment by levenzz** [comment]
> this is more suited as a stackoverflow question
> 
> wrap this with an Expanded Widget , else play around with padding
> 
> `Text("自动登录", textAlign: TextAlign.center, style: TextStyle(fontSize: 12.0, color: Color(0xff606266)), ),`

but it's normal，in english  `Text("Login", textAlign: TextAlign.center, style: TextStyle(fontSize: 12.0, color: Color(0xff606266)), ),`
