### ISSUE TITLE
flutter适用flutterboost的open跳转原生页时，如果map中有一个key的值是true or false，则会导致崩溃

### ISSUE THREAD

**Issue by xujiangithub** [flutter/flutter#73023]
(StandardMessageCodec.java的writeValue方法，如果有值为true or false传递进来，则会造成崩溃，崩溃原因为throw new IllegalArgumentException("Unsupported value: " + value);

```
if (value == Boolean.TRUE) {
            stream.write(TRUE);
        } else if (value == Boolean.FALSE) {
            stream.write(FALSE);
        }
```

上面的判断是否应该写成
```
if (value.equals(Boolean.TRUE)) {
            stream.write(TRUE);
        } else if (value.equals(Boolean.FALSE)) {
            stream.write(FALSE);
        }
```

**Comment by darshankawar** [comment]
@xujiangithub 
This seems to be an issue with the plugin you are using https://github.com/alibaba/flutter_boost. Please consider opening this issue in plugin owner's repo.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by xujiangithub** [comment]
<img width="793" alt="截屏2021-01-08 下午6 09 45" src="https://user-images.githubusercontent.com/22951835/104002926-b23e1480-51dc-11eb-915b-4117021ed2b8.png">

这个错误是发生在这个库里面的，应该是flutter的吧
