### ISSUE TITLE
GestureDetector onPanDown() event

### ISSUE THREAD

**Issue by lau1944** [flutter/flutter#73039]
``` dart
GestureDetector(
    onPanUpdate: (detail) {
      print('first');
   }
   child: GestureDetector(
       onPanUpdate: (detail)  {
           print('second');
       }
  )
)
```

As my knowlege of GestureArenaManager, 
The code above would dispatch the child event first and the parent gesture would be dropped,
but the actual print result is 

```
   'second'
   'first'
```
This issue only appeared at onPanDown() method as I know, onTap(), onVerticalDragDown(), etc.. don't have this issue.

This issue was first discovered when I wanted to implement a draggable item inside listview, but when I scroll vertically, the draggable item move a little bit and the listview started to scroll. What I expect it is that after dispatch the event to draggable item, the state of event would be removed, it wouldn't pass to their parent, but onPanDown(), onPanUpdate... didn't do that way.

Sample 
``` dart
  ListView(
    controlller:  _controller,
   child: GestureDetector(
       onPanUpdate: (detail)  {
           dragEvent(detail);   
       }
  )
)
```
To be frank, the listview won't be scrolled when I drag the view except vertically.

I think it is related to PanGestureRecognizer, anyone help? 

_Originally posted by @lau1944 in https://github.com/flutter/flutter/issues/28202#issuecomment-751645873_

**Comment by TahaTesser** [comment]
Hi @lau1944 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by lau1944** [comment]
> Hi @lau1944
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

flutter doctor -v
``` dart

[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B50, locale zh-Hans-CN)
    • Flutter version 1.22.3 at /Users/liuquan/flutter
    • Framework revision 8874f21e79 (9 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/liuquan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

sample 
```dart

class HomePage extends StatefulWidget {
  static String path = 'home';

  static Widget routeBuilder(BuildContext context) {
    return HomePage();
  }

  @override
  State<StatefulWidget> createState() => HomePageState();
}

class HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Container(
          height: 100,
          width: 100,
          child: GestureDetector(
            onPanDown: (detail) {
              print(detail); 
            },
          ),
        )
      ],
    );
  }
}

```

As the code above, when our finger touch inside the container, the listview should not be scrolled.
But when I scroll vertically inside the Container, the listview can still be scrolled.

**Comment by justinmc** [comment]
CC @goderbauer

**Comment by TahaTesser** [comment]
Hi @lau1944 
When we just tap, it's not scrolled, I don't see it being scrolled. Can you please clarify?
>  when our finger touch inside the container, the listview should not be scrolled.

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  static String path = 'home';

  static Widget routeBuilder(BuildContext context) {
    return HomePage();
  }

  @override
  State<StatefulWidget> createState() => HomePageState();
}

class HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Container(
          height: 300,
          width: 300,
          child: GestureDetector(
            onPanDown: (detail) {
              print(detail);
            },
            child: FlutterLogo(
              size: 300,
            ),
          ),
        )
      ],
    );
  }
}

``` 

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS 14.3
    • iPhone 12 (mobile)     • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by lau1944** [comment]
> Hi @lau1944
> When we just tap, it's not scrolled, I don't see it being scrolled. Can you please clarify?
> 
> > when our finger touch inside the container, the listview should not be scrolled.
> 
> code sample
> flutter doctor -v

Sry, I didn't explain clearly, 
'When we just tap'  **I mean drag vertically** (Set the Container size to be bigger so it can test clearly)
, the item's gestureRecognizer and the listview is conflicted.

**Comment by lau1944** [comment]
> Hi @lau1944
> When we just tap, it's not scrolled, I don't see it being scrolled. Can you please clarify?
> 
> > when our finger touch inside the container, the listview should not be scrolled.
> 
> code sample
> flutter doctor -v

Just to be more clear,
I create my a customPanGestureRecognizer which extends PanGestureRecognizer,

```dart
class CustomPanGestureRecognizer extends PanGestureRecognizer {
   @override
   void rejectGesture(int pointer) {
       print(pointer);
   }
}
```

Which is found out, the rejectGesture method was called after the listview was scrolled, and cause the draggable items became undraggable..

**Comment by TahaTesser** [comment]
Hi @lau1944 
Can you please complete the code sample and steps tor reproduce with expected results and actual results for more clarity
Thank you

**Comment by lau1944** [comment]
> Hi @lau1944
> Can you please complete the code sample and steps tor reproduce with expected results and actual results for more clarity
> Thank you

In my project, I implement a custom draggable view myself, so it would be much confusing if I paste the whole code. But I simplify the problem below.

```dart

import 'package:flutter/cupertino.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: ListView(
        children: [
          Container( // a draggable zone
            height: 200,
            child: Container( // assume it's a draggable item inside the zone
              height: 40,
              width: 40,
              child: GestureDetector(
                onPanDown: (detail) {
                  print(detail);
                  // _handleDownEvent(detail);
                },
                onPanUpdate: (detail) {
                  print(detail);
                  // _handleUpdateEvent(detail);
                },
                onPanEnd: (detail) {
                  // _handleFinishEvent(detail);
                },
              ),
            ),
          )
        ],
      ),
    );
  }
}

```
Draggable zone is part of the item of listview.
A draggable item is inside a draggable zone, we need the draggable item can be dragged freely inside the draggable zone.
Which mean that  **onPanUpdate** method would always be **print()** while we are dragging.

However, everything works until we drag it vertically after our finger touches down, the listView is scrolled, 
**onPanUpdate**  would not print() anything.

** This happened is because the GestureRecognize of listView and the item is conflicted. The GestureArenaManager chose listView as winner and the draggable item is called **rejectGesture**.

What we want is, inside the draggable zone, we can drag anyway we want, the listView gesture event should not be dispatch while we are dragging.
That means, no matter what, onPanUpdate should always be print().

**Comment by TahaTesser** [comment]
Hi @lau1944 
Thanks for the details
Looks similar to https://github.com/flutter/flutter/issues/72996, which also suggest using this [workaround](https://github.com/flutter/flutter/issues/28202#issuecomment-700412365)
I can reproduce the behavior
Closing in favor of https://github.com/flutter/flutter/issues/73039
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
