### ISSUE TITLE
Execution failed for task ':app:desugarDebugFileDependencies'

### ISSUE THREAD

**Issue by Grigary-C-Antony** [flutter/flutter#73037]
```bash
Launching lib/main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > /home/(username)/Android/Sdk/build-tools/28.0.3/core-lambda-stubs.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by TahaTesser** [comment]
Hi @Grigary-C-Antony 
This seems to be related to `build-tools/28.0.3`, check this [stackoverflow](https://stackoverflow.com/questions/59509560/execution-failed-for-task-appdesugardebugfiledependencies)
please delete 28.0.3,  download builds tools 30.0 and try again
Thank you

**Comment by Grigary-C-Antony** [comment]
> Hi @Grigary-C-Antony
> This seems to be related to `build-tools/28.0.3`, check this [stackoverflow](https://stackoverflow.com/questions/59509560/execution-failed-for-task-appdesugardebugfiledependencies)
> please delete 28.0.3, download builds tools 30.0 and try again
> Thank you

Thank you brother it worked on me after when i started a new project , i think error may be because of build so i flutter cleaned the same and it worked for me and 
thank you for the help brother @TahaTesser
