### ISSUE TITLE
Visible seam on border

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7304]
Noticed during a workshop.

See screenshot (click to see full size):

![screen shot 2016-12-22 at 1 36 35 pm](https://cloud.githubusercontent.com/assets/5479/21441229/ccb32eb4-c84b-11e6-8226-a809f3a59997.png)

Notice the seems coming out from the corners.

Using iOS simulator. Haven't tried hardware.

**Comment by Hixie** [comment]
Dupe of #147.
