### ISSUE TITLE
Crash Metal: -[MTLIOAccelCommandBuffer commandBufferResourceInfo] + 12

### ISSUE THREAD

**Issue by sxsdjkk** [flutter/flutter#73041]
As I know, Matal is supported from iOS12 ， and this issue made crashes on iOS11 in my project .
 My Project is based on Flutter . So I suspect this problem caused by Flutter.

![Image](https://user-images.githubusercontent.com/10103345/103214189-c2d3cc80-494a-11eb-8ddb-90468e99e4a9.png)

**Comment by TahaTesser** [comment]
Hi @sxsdjkk 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
