### ISSUE TITLE
Webview not working when build apk

### ISSUE THREAD

**Issue by Perdiga** [flutter/flutter#73054]
Hi guys I am having issues generating a release apk using  `flutter build apk`. When I install the apk the app does not open the web view, but when I try to debug or install using `flutter run --release it works fine. Can someone help me ?

## Steps to Reproduce

1. Clone this repo https://github.com/Perdiga/flutter_okta_sample
2. Create a release key https://flutter.dev/docs/deployment/android
3. Run `flutter run --release`
4. Open the application and click on authentication
5. It will open a web view and redirect to Okta login page
6. Run `flutter build apk`
7. Open the application and click on authentication
8. Should open a web view and redirect to Okta login page but it not working.

**Expected results:**

`flutter run --release` and ` flutter build apk` should create the same code

**Actual results:** 

if you run `flutter run --release`  it will work on emulator and real device
if  you run `flutter build apk` it will not call the webview

<details>
  <summary>Logs</summary>

There are no useful logs :(

```
```

Analyzing flutter_okta_sample...
No issues found! (ran in 6.0s)

```
```

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.18363.1256], locale pt-BR)
    • Flutter version 1.22.5 at C:\tools\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ofx5o7h\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Moto G 5 Plus (mobile) • ZY22457ZL8 • android-arm • Android 8.1.0 (API 27)

```
```

</details>

**Comment by darshankawar** [comment]
@Perdiga 
Can you try the official `webview` plugin [example](https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example) and see if it works or shows same issue ?

**Comment by Perdiga** [comment]
The example worked just fine, but it´s using a beta channel (Dart SDK 2.12). I would like to understand what is the difference between `--release` and build apk. They should be pretty similar, right?

I will try to upgrade my plugin to use beta channel and see if it works 
BTW this is the plugin that I am working on https://github.com/sonikro/flutter-okta-sdk

**Comment by darshankawar** [comment]
@Perdiga 
Check out [this](https://stackoverflow.com/a/59590538) link to know difference between `flutter run --release` and `flutter build apk`. 
Also, since the official webview example works properly per your comment above, I am going ahead and closing this issue.
If you disagree, write in comments and I'll reopen it.
