### ISSUE TITLE
Problem running flutter drive

### ISSUE THREAD

**Issue by elwachin** [flutter/flutter#73061]
Dear comunitty,
I have a problem running fluter drive I have the test class main_test.dart and I have this error.

../../dev/flutter/packages/flutter/lib/src/semantics/semantics.dart:2121:39: Warning: Operand of null-aware operation '!' has type 'List<SemanticsNode>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'SemanticsNode' is from 'package:flutter/src/semantics/semantics.dart' ('../../dev/flutter/packages/flutter/lib/src/semantics/semantics.dart').
    for (int position = 0; position < childrenInDefaultOrder!.length; position += 1) {
                                      ^
test_driver/main_test.dart:4:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../dev/flutter/packages/flutter_test/lib/src/_goldens_io.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../dev/flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../dev/flutter/packages/flutter_test/lib/src/animation_sheet.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../dev/flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../dev/flutter/packages/flutter_test/lib/src/frame_timing_summarizer.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../dev/flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../dev/flutter/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../dev/flutter/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Offset;
^
../../dev/flutter/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' hide window;

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/ESpannoal/dev/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ESpannoal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 344B0C3F-87C5-4194-BF47-A50CD0888A0E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
![alfi](https://user-images.githubusercontent.com/11857730/103245996-31705480-4962-11eb-91ec-34841149d470.jpg)

**Comment by darshankawar** [comment]
@elwachin 
It seems your file `main_test.dart` has some imports which aren't allowed while running flutter driver tests. Can you try [this](https://flutter.dev/docs/cookbook/testing/integration/introduction) example and see if you get same issue ?

**Comment by elwachin** [comment]
Thank you! It works

**Comment by alessss** [comment]
Here are my imports:
```
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:dotp/dotp.dart';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';
import 'helpers.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
```
The problem is definitely in 
`import 'package:flutter_test/flutter_test.dart';`

But I need this import, because it contains WidgetTester.showKeyboard(), and I need it to type ext into text field. 

Is there any alternative way of calling keyboard using driver?
