### ISSUE TITLE
Documentation: Internationalization Guide is corrupted

### ISSUE THREAD

**Issue by matthewblain** [flutter/flutter#73074]
## Steps to Reproduce

The "Internationalization Guide" is an editable document and has been corrupted by end users.
It should not be world-writable!

1. Visit document [Internationalizing Flutter apps](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) . This is on flutter.dev and seems fine.
2. Note that the doc says _For more information about the localization tool, such as dealing with DateTime and handling plurals, see the [Internationalization User’s Guide](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit)._ This is fine.
3. Visit the User's Guide.

Result: An unreadable document which is a Googles Docs doc in suggest mode. It is uncertain if it has been intentionally or unintentionally edited by end users, but to result is the same: an unusable guide.

Expected: A link to a page on flutter.dev, or a "Publish to Web" version of Google Docs, or any other read-only documentation mechanism, possibly with a link where users may enable suggestions (e.g. using the Google Docs request permission mechanism, a github PR, or any other mechanism which requires intent and verification.)

## Logs

N/A

**Comment by shihaohong** [comment]
I fixed up the doc and locked suggestions. Thanks for the heads up!
