### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by ThePhoenixRisen** [flutter/flutter#73079]
I kept having issues on getting Flutter to behave as I keep seeing it should behave in tutorials so I started from scratch again. I downloaded Git and installed from the wizard. I downloaded Flutter zip onto Downloads folder and then extracted into the directory shown below. I edited environment variables to have a path for Flutter. I still keep getting the same response when I type flutter on cmd. What am I doing wrong, and can someone please help me do a proper install? For better specification, I followed the exact steps from the video https://www.youtube.com/watch?v=x0uinJvhNxI&t=2848s beginning at 41:36. The sole difference is when installing Git through the wizard, instead of having the option "Use Git from the Windows Command Prompt" my middle option and most similar was "Use Git from Command Line and 3rd party software". Below is the screenshot of what I  #get.
![directory](https://user-images.githubusercontent.com/71746795/103260780-8e6d0a00-4964-11eb-85b9-80dbd2aa76e5.JPG)
![Paths](https://user-images.githubusercontent.com/71746795/103260785-90cf6400-4964-11eb-8397-706e478f5ab0.JPG)
![CMD](https://user-images.githubusercontent.com/71746795/103260788-9331be00-4964-11eb-9a64-0a24b018c062.JPG)

**Comment by SaiHtetMyatHtut** [comment]
I Think you need to give writable permission to the user that login right now or just give full control to everyone.
like this...
![image](https://user-images.githubusercontent.com/28846218/103263959-a8940000-49d7-11eb-8271-795b10ee2a20.png)

**Comment by ritvij14** [comment]
https://github.com/flutter/flutter/issues/18229#issuecomment-395064146

This should help out.

**Comment by darshankawar** [comment]
@ThePhoenixRisen 
Check the official [documentation](https://flutter.dev/docs/get-started/install/windows) for installation on Windows. Per the documentation, it is not recommended to install Flutter sdk in Program Files:

<img width="881" alt="Screenshot 2020-12-29 at 1 17 30 PM" src="https://user-images.githubusercontent.com/67046386/103267740-396adb80-49d8-11eb-8ef1-80e612af2dff.png">

Try to reinstall at a path / location where Flutter won't require permission.

**Comment by ThePhoenixRisen** [comment]
> 
> 
> I Think you need to give writable permission to the user that's login right now or just give full control for everyone to that sdk folder.
> like this...
> ![image](https://user-images.githubusercontent.com/28846218/103263959-a8940000-49d7-11eb-8271-795b10ee2a20.png)

Thank you so much. This was it. I don't know how I didn't think of it. Very very much appreciated
