### ISSUE TITLE
Emoji rendering not working on 1.25.0-8.1.pre 

### ISSUE THREAD

**Issue by onb3891** [flutter/flutter#73077]
For Flutter web code 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Center(
        child: Text('😀'),
      ),
    );
  }
}

```
Emoji doesnt get rendered for **1.25.0-8.1.pre** but works for **1.24.0-10.2.pre**

**Comment by darshankawar** [comment]
@onb3891 
What version do you see this issue on ? Master, dev, or beta ?

**Comment by onb3891** [comment]
> @onb3891
> What version do you see this issue on ? Master, dev, or beta ?

beta

**Comment by darshankawar** [comment]
@onb3891 
I ran your code sample on latest beta (1.25) and saw emoji rendering properly:

<img width="829" alt="Screenshot 2020-12-30 at 3 39 04 PM" src="https://user-images.githubusercontent.com/67046386/103344668-3f82ba00-4ab5-11eb-94ec-0b8310023ab6.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>

**Comment by onb3891** [comment]
<img width="1187" alt="flutter_emoji" src="https://user-images.githubusercontent.com/33245503/103435515-9d3e1000-4c35-11eb-8292-b6834f1ea994.png">

flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.1.pre at /Users/Shared/flutterSDK/flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Shared/AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

**Comment by onb3891** [comment]
On furthur debugging I have following observations.

This happens when I run 
`flutter run --web-renderer auto `
or 
`flutter run --web-renderer canvaskit `

If I choose "--web-renderer html" issue is not seen. 
For 1.24.0-10.2.pre I have set this to auto. 
On my DartDev tool I can see empty icon on emoji for both cavaskit and html modes.

<img width="1399" alt="dartDevtool" src="https://user-images.githubusercontent.com/33245503/103437120-59550600-4c49-11eb-8308-eb8c9671ad78.png">

**Comment by darshankawar** [comment]
Issue replicable on latest beta while using skia flag to true.

1. flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true

<img width="703" alt="Screenshot 2021-01-04 at 11 58 03 AM" src="https://user-images.githubusercontent.com/67046386/103507559-7f66ea00-4e85-11eb-8e3b-40fd559fba38.png">

2. While works by running below command:

`flutter run -d chrome` or `flutter run --web-renderer html`:

<img width="706" alt="Screenshot 2021-01-04 at 11 58 45 AM" src="https://user-images.githubusercontent.com/67046386/103507636-a6252080-4e85-11eb-90f4-dbb17f0c8ed5.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>

**Comment by darshankawar** [comment]
May be related to https://github.com/flutter/flutter/issues/68704 and https://github.com/flutter/flutter/issues/53897

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/53897
