### ISSUE TITLE
Connecting to camera service - Nothing happened

### ISSUE THREAD

**Issue by leszekkrol** [flutter/flutter#73088]
@mvanbeusekom  Your last commit "Update camera_platform_interface to 1.2.0 (#3376)" causes the camera to not initialize ;/ Could you check it?

The log data only shows the "Connecting to camera service" status.

[+1576 ms] D/ViewRootImpl@9af74a5FlutterActivity: ViewPostImeInputStage processPointer 0
[ +52 ms] D/ViewRootImpl@9af74a5FlutterActivity: ViewPostImeInputStage processPointer 1
[ +113 ms] I/CameraManagerGlobal( 9094): Connecting to camera service
[ +159 ms] D/SensorManager( 9094): registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,

**Comment by mvanbeusekom** [comment]
@leszekkrol sorry that happened, this is a harsh lesson for me. 

Anyway we have a fix for this pushed with PR flutter/plugins#3377, if the tree goes green it should be merged and fixes the camera plugin.
