### ISSUE TITLE
Flutter - MacOS build issue 

### ISSUE THREAD

**Issue by kunaljoshi388** [flutter/flutter#73085]
I am working on an application in which I have given MacOS desktop app support. 

I have used **url_launcher** and **shared_preferences** plugin in my application. The IOS and Android application is working fine and even I can successfully create the builds for both the platforms.

But when I am trying to create a build for MacOS it gives me error as below:

> Undefined symbol: _FlutterMethodNotImplemented

> Undefined symbol: _OBJC_CLASS_$_FlutterError 

> Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel

Can anyone please help me to fix this issue?

**Comment by darshankawar** [comment]
@kunaljoshi388 
provide `flutter doctor -v` along with `pubspec.yaml`.

**Comment by kunaljoshi388** [comment]
@darshankawar 
output of `flutter doctor -v` is as below 

>  Flutter (Channel master, 1.26.0-2.0.pre.145, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.145 at /Users/Techseria/Documents/FlutterSDK/flutter
    • Framework revision 38fe7e2b1c (10 hours ago), 2020-12-28 21:39:03 -0500
    • Engine revision 892034dc6a
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.


> [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.0
> 

> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

> [✓] IntelliJ IDEA Community Edition (version 2020.3)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 52.0.5
>     • Dart plugin version 203.5981.152

> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88
> 

`pubspec.yaml` file

> version: 1.0.0+11
> 
> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
> 
>   built_collection: ^4.3.2
>   provider: ^3.2.0
>   shared_preferences: '>=0.5.10 <2.0.0'
>   characters: ^1.0.0
>   diffutil_sliverlist: ^0.4.0+1
>   #audioplayers: ^0.16.1
>   assets_audio_player: ^2.0.13+1
>   intl: ^0.16.1
>   uuid: ^2.2.2
>   cupertino_icons: ^0.1.2
>   shimmer: ^1.1.2
>   # dev dep
>   sentry: ^2.2.0
>   device_info: ^0.4.1+3
>   path: ^1.7.0
>   path_provider: ^1.6.14
>   package_info: '>=0.4.3 <2.0.0'
>   firebase_core: ^0.5.0+1
>   firebase_database: ^4.1.1
>   firebase_auth:
>   #cloud_firestore: ^0.14.3
>   reorderables: 0.3.2
>   flutter_boom_menu: ^1.0.2
>   flutter_slidable: ^0.5.7
>   unicorndial: "^1.1.5"
>   date_utils: ^0.1.0+3
>   connectivity: ^2.0.2
>   permission_handler: ^4.2.0
>   image_picker: ^0.6.7+14 #0.6.5+2 #0.6.2+2   #  0.6.1+11   #
>   #image_pickers: ^1.0.8+7
>   images_picker: ^0.0.6
>   firebase_storage: ^5.1.0
>   toast: ^0.1.5
>   flushbar: ^1.10.4
>   rflutter_alert: ^1.1.0
>   flutter_spinkit: ^4.1.2+1
>   flutter_local_notifications: ^3.0.1+6
>   rxdart: any
>   google_fonts: ^1.1.1
>   url_launcher: ^5.7.10
>   auto_size_text: ^2.1.0
>   widget_animator: ^1.0.0+7
>   cached_network_image: ^2.4.1
>   expandable: ^4.1.4
>   flutter_custom_dialog: ^1.0.20
>   scroll_to_index: ^1.0.6
> 
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter

**Comment by darshankawar** [comment]
@kunaljoshi388 
Are you trying to run in debug mode or in build / release mode ? Please provide verbose logs by running based on what mode you are trying to run.
Example : `flutter run -d chrome --verbose`

**Comment by kunaljoshi388** [comment]
@darshankawar 

I want to create a macOS build, so I am trying to create a release build.

**Comment by darshankawar** [comment]
@kunaljoshi388 
Tried to build for macOS on latest master using a sample app and was able to build without any issues.

<img width="363" alt="Screenshot 2020-12-30 at 4 17 36 PM" src="https://user-images.githubusercontent.com/67046386/103346749-f5043c00-4aba-11eb-944a-d8f61f965686.png">
<img width="644" alt="Screenshot 2020-12-30 at 4 18 13 PM" src="https://user-images.githubusercontent.com/67046386/103346756-f897c300-4aba-11eb-9e59-23e49bd68824.png">
<img width="513" alt="Screenshot 2020-12-30 at 4 20 06 PM" src="https://user-images.githubusercontent.com/67046386/103346760-f9c8f000-4aba-11eb-9c5d-064ec3205507.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.137 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f5d0371af (4 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.



```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
