### ISSUE TITLE
Video player is not buffering

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#73083]
Video player is not buffering and the controller always false of isBuffering property _controller.value.isBuffering

when i seek to a place i passed it re-download the video again .

I've tried to use other plugins but all of them depend on video_player under the hood

how to solve this issue ?

**Comment by SardorbekR** [comment]
@ModWU https://stackoverflow.com/a/63375798/10969195

**Comment by darshankawar** [comment]
@ModWU 
A similar issue was [fixed](https://github.com/flutter/flutter/issues/28494) and merged in Master.  What version are you on ? If not on latest master, switch and upgrade to latest master and try again to see if it works.

If issue persists, provide `flutter doctor -v` and minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by ModWU** [comment]
> 
> 
> @ModWU https://stackoverflow.com/a/63375798/10969195



> 
> 
> @ModWU
> A similar issue was [fixed](https://github.com/flutter/flutter/issues/28494) and merged in Master. What version are you on ? If not on latest master, switch and upgrade to latest master and try again to see if it works.
> 
> If issue persists, provide `flutter doctor -v` and minimal complete reproducible code sample that shows the issue.
> Thanks.

![图片](https://user-images.githubusercontent.com/16234264/103409002-c2803f00-4b9f-11eb-86a9-fb610008cb20.png)

**Comment by darshankawar** [comment]
@ModWU As requested earlier https://github.com/flutter/flutter/issues/73083#issuecomment-751992413, please provide `flutter doctor -v` and minimal complete reproducible code sample that we can copy paste and run to see the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
