### ISSUE TITLE
image_picker crash app on selecting large mb file more than 550mb solve the issue 800mb not work

### ISSUE THREAD

**Issue by gadgetsteach** [flutter/flutter#73086]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@gadgetsteach 
Provide a detailed description of the issue you are facing along with `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducbile code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
