### ISSUE TITLE
Upgrading camera_platform_interface from 1.0.4 to 1.2.0 results in camera not working

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#73091]
There's no error logs printed, so it's difficult to provide some more information about what is causing this. With the same code base, same `camera` plugin version (`0.6.3+2`), if I run `flutter pub upgrade` and `camera_platform_interface` bumps from `1.0.4` to `1.2.0`, parts of our app that use the camera stop working (black screen).

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [VersiÃ³n 10.0.19042.685], locale es-ES)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\crist\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • ONEPLUS A5000 (mobile) • f2eb43ee • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@Zazo032 
Can you provide `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by nekocode** [comment]
Found a related issue #73088

**Comment by Zazo032** [comment]
thanks @nekocode, seems related, will wait until it's fixed and check if it also fixes this

cc/ @mvanbeusekom

**Comment by kw2019ltd** [comment]
same issue

**Comment by mvanbeusekom** [comment]
This indeed looks like it is related to issue #73088, for which we have a pull request waiting to complete. In the meantime you can use a [dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) to workaround the problem. 

Adding the following to your pubspec.yaml should solve the issue:

```yaml
dependency_overrides:
  camera_platform_interface: ">=1.0.4 <1.1.0"
```

**Comment by andyvandermeyde** [comment]
Thank you @Zazo032, I don't know how you figured out that it is because of camera_platform_interface but you just saved me from spending another evening chasing this invisible problem. 

To add to the discussion, the camera plugin with camera_platform_interface 1.2.0 is broken on Samsung S8 and Samsung S10. 

Thanks @mvanbeusekom for the workaround as well.

**Comment by aytunch** [comment]
@mvanbeusekom I added the suggested dependency_overrides and the error is gone for the android emulator however my One Plus 7t still has the same problem. The cameraController.initialize() never ends. What else can I do?

**Comment by mvanbeusekom** [comment]
That should really do the trick to be honest. I don't have a One Plus 7t device to test with but it does work on an LG Nexus 5X and Samsung Galaxy S6 that I have around. 

Maybe something "old" is lingering around on the device or in your build folder that is in the way. Could you try the following:

1. Delete the `camera_platform_interface` package from your pub cache. On Mac devices this is located in the `~/.pub-cache/hosted/pub.dartlang.org/` folder. So running the following command would delete all versions of the cached package:
```bash
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/camera_platform_interface*
```
2. Now run `flutter clean` in the root of you app folder to remove all cached build information (basically next build will be completely fresh);
3. And last run `flutter pub get` to redownload all package dependencies that are missing.

Now you should be able to run the app.

**Comment by mvanbeusekom** [comment]
Yesterday version 0.6.4+3 was released to pub.dev which amongst other changes should also solve this issue. 

Please make sure when you upgrade to this new version to remove the dependency override on the `camera_platform_interface` if you used the workaround mentioned [above](https://github.com/flutter/flutter/issues/73091#issuecomment-752073164).
