### ISSUE TITLE
Summarizing multiple SkSL cache files

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#73098]
Is it possible to have several shader cache files and add them all to the build?
flutter build apk --bundle-sksl-path flutter_01.sksl.json -- how to add flutter_02.sksl.json, flutter_03, flutter_04 etc.?
Can I have a folder with cache files and add the whole folder?
So if I will add some screens or animations to the existing app, I will not delete the current cache, but re-run the app, find this janky screen and add a new cache file.
It would be extremely useful

(originally posted here https://github.com/flutter/flutter/issues/61045 , opened a new issue by request of @dnfield )

**Comment by RomanKapshuk** [comment]
I wrote some shell and python scripts to compile several sksl.json files in one single file as a result of flutter drive execution. 

See examples below. Seems it works as expected 

**warmup_shaders.sh:**

```
#!/bin/sh


# Parameter -p used as prefix for shaders file. Could be null or any prefix
while getopts ":p:" opt; do
  case $opt in
  p) prefix="$OPTARG"
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    ;;
  esac
  done


testsDirectory="test_driver"

find -E $testsDirectory -name "*_test.dart" | sort | while read testFileName; do

  echo "Test: $testFileName"
  shadersFileName="${testFileName%_test.dart}"
  shadersFileName="${shadersFileName#test_driver/}"
  shadersFileName="""$prefix""_${shadersFileName}.sksl.json"
  echo "Shaders file name: $shadersFileName"

  flutter drive --cache-sksl --write-sksl-on-exit "$shadersFileName" --target=test_driver/app.dart --driver="$testFileName"


#  Aggreagate all shaders in one single file
  python warmup_shaders_concatenate.py "$shadersFileName" "$prefix"

  done
```

**warmup_shaders_concatenate.py:**

```
import json
import sys
from os import path


def addDataToResultFile(filePath, platform, engineRevision, name, data):
    if path.exists(filePath):
        with open(filePath, 'r+') as file:
            resultJson = json.load(file)
            existedData = resultJson['data']
            for item in data:
                existedData[item] = data[item]
            resultJson['data'] = existedData
            file.seek(0)
            file.truncate()
            json.dump(resultJson, file)

    else:
        resultJson = {
            'platform': platform,
            'engineRevision': engineRevision,
            'name': name,
            'data': data
        }
        with open(filePath, 'w+') as file:
            json.dump(resultJson, file)


warmShadersFileName = sys.argv[1]
prefix = sys.argv[2]

platform = ''
engineRevision = ''
name = ''
data = {}
print('Start shaders extraction from: ' + warmShadersFileName)

with open(warmShadersFileName) as file:
    shadersFromTest = json.load(file)
    print('________________________')
    for entry in shadersFromTest:
        if entry == 'platform':
            platform = shadersFromTest[entry]
            print('Platform: ' + platform)
        if entry == 'engineRevision':
            engineRevision = shadersFromTest[entry]
            print('EngineRevision: ' + engineRevision)
        if entry == 'name':
            name = shadersFromTest[entry]
            print('Name: ' + name)
        if entry == 'data':
            data = shadersFromTest[entry]
            print('Data length: ' + data.__len__().__str__())
            print('________________________')

    resultFileName = prefix + "_" + platform + '_result_shaders.sksl.json'

    addDataToResultFile(resultFileName, platform, engineRevision, name, data)

```

Just execute place both files in the root of your project and execute `./warmup_shaders.sh`. Do not forget to make shell script executable `chmod u+x warmup_shaders.sh`.

**Comment by jonahwilliams** [comment]
FYI @liyuqian

Seems like a reasonable thing for the tool to do. The --bundle-sksl-path could be updated to be a multiarg and then the summarization could be ported to Dart and included around here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/assets.dart#L136

@RomanKapshuk any interest in open up a PR to add this feature?

**Comment by subzero911** [comment]
> Seems like a reasonable thing for the tool to do. The --bundle-sksl-path could be updated to be a multiarg 

And please add also an option to set a folder of cache files as an argument. So if I have a multiple filed, I wouldn't list it by one, like: `--bundle-sksl-path flutter_01.sksl.json flutter_02.sksl.json flutter_03.sksl.json...`, but `--bundle-sksl-path ./sksl`
Also it would be nice to add an option to save cache to the folder `flutter run --profile --cache-sksl --target=./sksl`, because currently it always puts it into the project root.

**Comment by dnfield** [comment]
Taking in globs/directories makes it more challenging to make the build hermetic/invalidate dirty builds. It saves a small amount of time up front but ends up costing a lot of time later.

**Comment by jonahwilliams** [comment]
Agree completely with Dan, no globs!

**Comment by subzero911** [comment]
Sorry, what are "globs"?

**Comment by zanderso** [comment]
SkSL caching and warm-up is no longer the approach the team is pursuing to solve early-onset jank.
