### ISSUE TITLE
[web] Tab preview in Firefox is glitched

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73100]
## Steps to Reproduce

1. Open a Flutter web app (for example https://funvas.creativemaybeno.dev) **in Firefox**.
2. Have at least 2 other tabs open.
3. Press <kbd>CTRL</kbd> + <kbd>Tab</kbd> to switch between tabs.

**Expected results:** the tab with the Flutter web app should show an image of the app as the tab preview.

**Actual results:** extremely glitched out version of the web app appears.

## Screenshot

![image](https://user-images.githubusercontent.com/19204050/103299420-69c07300-49f4-11eb-9867-478a5157d29d.png)

In the background, you can see how the Flutter web app actually looks. The leftmost tab in the tab preview is the one you see in the background and as you can see, it is completely glitched in the preview.

## Versions

```
Flutter 1.25.0-8.1.pre
Flutter engine 92ae191c17a53144bf4d62f3863c110be08e3fd3
```

The **build logs** can be found in the [package repo](https://github.com/creativecreatorormaybenot/funvas/tree/master/funvas_demo) CD: https://github.com/creativecreatorormaybenot/funvas/runs/1622040591

Build command: `flutter build web --web-renderer canvaskit`

### Reproduction

I am able to reproduce this with my other deployed Flutter web apps as well ([example](https://portfolio.creativemaybeno.dev)). It seems like this is a **CanvasKit** issue, however.

If I run a Flutter web app in demo mode (`flutter run -d chrome --web-renderer canvaskit`) and then open that app in Firefox, the tab preview is glitched as well, however, when I add `--web-renderer html`, the issue disappears.

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.132, locale en-US)
    • Flutter version 1.26.0-2.0.pre.132
    • Framework revision 6e5f55fb59 (5 days ago), 2020-12-24 12:29:02 -0500
    • Engine revision 1c975f1e7c
    • Dart version 2.12.0 (build 2.12.0-177.0.dev)

[✓] Chrome - develop for the web

[✓] Connected device (3 available)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.88
```

</details>

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Can you please provide your `flutter build web --web-renderer canvaskit --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser Thanks for pointing it out!

After testing it more, I realized that this happens *only on Windows*.

## Versions that reproduce bug (Windows)

## Versions without the bug (macOS)

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-1.0.pre at /Users/user/Library/flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

Firefox: 84.0.1 (64-bit)
```

## Reproduction

I can reproduce it (with the versions / platform that reproduces the bug) using just:

* `flutter create --platforms=web bug`
* `cd bug`
* `flutter run -d chrome --web-renderer canvaskit`
* Open in a Firefox window and check tab preview.

The problem is that the glitch is barely apparent in the demo app. So simply replace the counter with: 

```
home: Image.network('https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', fit: BoxFit.cover,),
```
 (as the `home:` parameter on the `MaterialApp`) and restart the app to see the effect.

| Firefox on macOS | Firefox on Windows |
| :----------------: | :-------------------: |
| <img width="337" alt="Screen Shot 2020-12-30 at 2 27 55 PM" src="https://user-images.githubusercontent.com/19204050/103357485-3987db80-4aab-11eb-8cc9-a12767f418a7.png"> | |

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser I can only reproduce it on one specific Windows machine (works on another) and not on macOS, so I will close this issue.

I doubt that this has something to do with Flutter in that case and it is likely not worth the effort.

If someone else thinks that this is more severe than this, we can surely reopen it :)

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Thank you but a quick question, tab preview as seen in your screenshot. I can't see it on Windows when executing `ctrl` + `tab`, only tabs are switched but no preview. How can I get that preview on Windows using Firefox?
Thank you

**Comment by creativecreatorormaybenot** [comment]
@TahaTesser It only appears for me once I have 3+ tabs open.

**Comment by TahaTesser** [comment]
@creativecreatorormaybenot 
Ohh. I tried with two tabs, thanks I can see it too
