### ISSUE TITLE
Image.network() doesn't show some images on the web but works on android.

### ISSUE THREAD

**Issue by antakuznet** [flutter/flutter#73109]
After latest update I'm unable to show some network images on the web platform. Everything works just fine on Android. 
This is  error message:

════════════════════Exception caught by image resource service ════════════════════════════
The following ProgressEvent$ object was thrown resolving an image codec:
  [object ProgressEvent]

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/yahts%2Fyaht.png?alt=media&token=dc4c2a5f-655c-4317-be80-68d6580c5a99", scale: 1)
Image key: NetworkImage("https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/yahts%2Fyaht.png?alt=media&token=dc4c2a5f-655c-4317-be80-68d6580c5a99", scale: 1)
═════════════════════════════════════════════════════════════════════════════

 flutter doctor -v

[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-1.0.pre at /Users/antonkuznetsov/development/tools/flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/antonkuznetsov/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • 0A211FDD4006JF • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

**Comment by antakuznet** [comment]
I was able to open this image on the web platform: 
https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500

But I couldn't opent any images stored in the firebase storage I was able to open before update: 
https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/yahts%2Fyaht.png?alt=media&token=dc4c2a5f-655c-4317-be80-68d6580c5a99

I tried also this one it's a gif from the example on flutter.dev and it's same error:
https://github.com/flutter/plugins/raw/master/packages/video_player/video_player/doc/demo_ipod.gif?raw=true

**Comment by pedromassangocode** [comment]
Hi @antakuznet 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by antakuznet** [comment]
Hi @pedromassangocode
Thank you for the reply. Here is my code:

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test Image',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Test Image'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.network(
              'https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
              width: 100,
              height: 100,
            ),
            Image.network(
              'https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/jets%2Fjetski.png?alt=media&token=f93b2680-6f03-4ba1-b1f5-17beb0df6648',
              width: 100,
              height: 100,
            ),
            Image.network(
              'https://github.com/flutter/plugins/raw/master/packages/video_player/video_player/doc/demo_ipod.gif?raw=true',
              width: 100,
              height: 100,
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by antakuznet** [comment]
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test Image',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Test Image'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.network(
              'https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
              width: 100,
              height: 100,
            ),
            Image.network(
              'https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/jets%2Fjetski.png?alt=media&token=f93b2680-6f03-4ba1-b1f5-17beb0df6648',
              width: 100,
              height: 100,
            ),
            Image.network(
              'https://github.com/flutter/plugins/raw/master/packages/video_player/video_player/doc/demo_ipod.gif?raw=true',
              width: 100,
              height: 100,
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by antakuznet** [comment]
This is what I got:

<img width="1201" alt="Screen Shot 2020-12-30 at 1 11 32 PM" src="https://user-images.githubusercontent.com/24783485/103381589-17895b80-4aa1-11eb-9bcb-5993d389317a.png">

And errors:

  [object ProgressEvent]

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/jets%2Fjetski.png?alt=media&token=f93b2680-6f03-4ba1-b1f5-17beb0df6648", scale: 1)
Image key: NetworkImage("https://firebasestorage.googleapis.com/v0/b/jetsea.appspot.com/o/jets%2Fjetski.png?alt=media&token=f93b2680-6f03-4ba1-b1f5-17beb0df6648", scale: 1)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
  [object ProgressEvent]
════════════════════════════════════════════════════════════════════════════════

**Comment by pedromassangocode** [comment]
Hi @antakuznet 
I cannot reproduce this issue either in dev nor master channel.

![Screen Shot 2020-12-31 at 08 20 28](https://user-images.githubusercontent.com/67424416/103399375-13147f80-4b41-11eb-89a0-d3782c08bb3e.png)

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-1.0.pre at /Users/pedromassango/dev/SDKs/flutter_dev
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by James-A-White** [comment]
I'm also experiencing this error accessing images stored in MS Azure Blob storage.

**Comment by supermakra** [comment]
I also saw this false behavior in Chrome (web-javascript) but it was always working on an Android device.
This bug is only seen after "git pull" my project on a different Computer. 
After "flutter clean" everything works as expected again.

**Comment by R12-cookies** [comment]
I am also facing this issue when trying to load my youtube videos' thumbnail images using youtube data API, the images load on the emulator but not chrome.

**Comment by Imgkl** [comment]
Having the same issue. I'm on ````beta channel````.

````
════════ Exception caught by image resource service ════════════════════════════
The following ProgressEvent$ object was thrown resolving an image codec:
  [object ProgressEvent]

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://github.com/Imgkl/FlikiPedia/blob/master/implementation.png", scale: 1)
Image key: NetworkImage("https://github.com/Imgkl/FlikiPedia/blob/master/implementation.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════
````

code:

````
class FlikipediaApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Image.network(
      "https://github.com/Imgkl/FlikiPedia/blob/master/implementation.png",
      height: 500,
      fit: BoxFit.contain,
    );
  }
}
````
Flutter doctor:

````
gokul@Kirans-MacBook-Pro-3 Imgkl.github.io % flutter devices
1 connected device:

Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• Error: Gokul’s iPhone is not connected. Xcode will continue when Gokul’s iPhone is connected. (code -13)
gokul@Kirans-MacBook-Pro-3 Imgkl.github.io % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
    ! Error: Gokul’s iPhone is busy: Waiting for Device. Xcode will continue when Gokul’s iPhone is finished. (code -10)

• No issues found!
````

**Comment by keitoro** [comment]
I would like to confirm that running flutter run solves the issue for me. Very strange.

**Comment by Imgkl** [comment]
To future readers,
It appears that this issue seems to be specific to **VS Code**.  Run the app, through the terminal with the command `flutter run`. Everything seems to be working fine. 


- Hot restart, enter `r`
- Hot reload, enter `R`

**Comment by keitoro** [comment]
Why is this issue not yet resolved?

**Comment by dannycortesv** [comment]
I'm also having this issue, any solution?

**Comment by peter-pr** [comment]
I am having same issue
Another exception was thrown: ImageCodecException: Failed to load network image.

**Comment by sanket27898** [comment]
I also face this issue i don't know why

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://firebasestorage.googleapis.com/v0/b/flutterprojectapp.appspot.com/o/Categogyimage%2F2021-02-16%2013%3A49%3A04.707?alt=media&token=7db9d42f-1db8-4250-bf69-e21421956572", scale: 1)
Image key: NetworkImage("https://firebasestorage.googleapis.com/v0/b/flutterprojectapp.appspot.com/o/Categogyimage%2F2021-02-16%2013%3A49%3A04.707?alt=media&token=7db9d42f-1db8-4250-bf69-e21421956572", scale: 1)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
  [object ProgressEvent]
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
  [object ProgressEvent]
═══════════════════════════

**Comment by yelkamel** [comment]
Same for me with Firebase Image or AWS S3 The following ImageCodecException was thrown resolving an image codec:
Failed to load network image.
Image URL: https://layouceferie.s3.eu-west-2.amazonaws.com/feminity.png
Trying to load an image from another domain? Find answers at:
https://flutter.dev/docs/development/platform-integration/web-images

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://layouceferie.s3.eu-west-2.amazonaws.com/feminity.png", scale: 1)
Image key: NetworkImage("https://layouceferie.s3.eu-west-2.amazonaws.com/feminity.png", scale: 1)

**Comment by abderrahmen-bmz** [comment]
Same problem for me ? any update for this issue ?

**Comment by pedromassangocode** [comment]
Could anyone facing this issue provide `flutter doctor -v`, a minimal code sample that reproduce the issue along with the steps to reproduce it?
Thank you

**Comment by antakuznet** [comment]
In my case I solved issues with network images from firebase storage by setting up CORS on a bucket with files. The best way to set it up is to  create .json file with config:
[
    {
      "origin": ["*"],
      "method": ["GET", "POST"],
      "responseHeader": ["Content-Type", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers"],
      "maxAgeSeconds": 7200
    }
]
and then use gsutil to set it up:
gsutil cors set 'path to .json' 'bucket'
It solved problems with all images from my firebase storage. Also you can limit access to the files by specifying allowed "origin" in the .json file.

**Comment by Malkhansingh4883** [comment]
I have the same issue please help 😕

**Comment by lukepighetti** [comment]
If this is a VSCode bug please file it in Dart-Code repo.

Issue filed here: https://github.com/Dart-Code/Dart-Code/issues/3176

**Comment by DanTup** [comment]
The last few comments look like https://github.com/flutter/flutter/issues/73327 to me, which is a CORS issue. It might be affected by the web renderer being used (which might cause it to occur from VS Code but not from the terminal if you're not passing the same web-renderer.. VS Code passes `--web-renderer=auto` by default) (see https://github.com/flutter/flutter/issues/73327).

**Comment by ChristianConstantNel** [comment]
I'm also facing this issue. Can't load any images, not firebase or any other hosted image.
Tried running through terminal as suggested and still the same problem.

**Comment by Puspharaj** [comment]
yup me too!

**Comment by victor-semenovich** [comment]
I use Firebase Storage and also faced this issue. I've resolved it by setting CORS configuration for my Cloud Storage bucket, as @antakuznet wrote [above](https://github.com/flutter/flutter/issues/73109#issuecomment-786849537). See also https://firebase.google.com/docs/storage/web/download-files#cors_configuration for details.

**Comment by subhendukundu** [comment]
This would be a fix when you have control over your image server or cdn.
What if we dont have access to the server. I think it should be done in flutter?
Tho `flutter run -d chrome --web-renderer html` works but not with `canvaskit`.

**Comment by kendji** [comment]
↑I really am confused to be mentioned my issue.
How do I erase that?

**Comment by TeoChirileanu** [comment]
> To future readers,
> It appears that this issue seems to be specific to **VS Code**. Run the app, through the terminal with the command `flutter run`. Everything seems to be working fine.
> 
>     * Hot restart, enter `r`
> 
>     * Hot reload, enter `R`

This did the trick

**Comment by samarjeetr2001** [comment]
> Could anyone facing this issue provide `flutter doctor -v`, a minimal code sample that reproduce the issue along with the steps to reproduce it?
> Thank you

Same issue I faced today:

flutter doctor -v :
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.0.2 at C:\Program Files\flutter
    • Framework revision 8962f6dc68 (13 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Samarjeet\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\Samarjeet\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!

code sample:

Container(
                          child:
                              Image.network(imagepath, width: double.infinity),
                        ),

**Comment by samarjeetr2001** [comment]
This solution work for me 🥇 

https://github.com/LunaGao/flag_flutter/issues/49#issuecomment-803008314

**Comment by javdev** [comment]
I got this error in Android Studio as well. The "solution":  flutter run -d chrome --web-renderer html
works, but it sucks. Can you examine it and provide a better solution.

**Comment by zibizz1** [comment]
It is because canvaskit needs proper CORS policy. So if you want to use canvaskit you can't load content from servers that do not let for that. If server is your you can configure proper CORS. When you use --web-renderer html browser do not use CORS policy.

I would like to use canvaskit but the only way I found is to use own server as proxy for loading these files

**Comment by sentd94** [comment]
> It is because canvaskit needs proper CORS policy. So if you want to use canvaskit you can't load content from servers that do not let for that. If server is your you can configure proper CORS. When you use --web-renderer html browser do not use CORS policy.
> 
> I would like to use canvaskit but the only way I found is to use own server as proxy for loading these files

I can't confirm that. My images are hosted in the Google Cloud (Firebase Storage) which I configured to allow all origins.

**Comment by zibizz1** [comment]
Mhhh for me after adding CORS it was fixed, for external things I need to use CORS proxy
https://flutter.dev/docs/development/platform-integration/web-images

**Comment by Malkhansingh4883** [comment]
Use HTML renderer 

flutter run -d chrome --web-renderer html

This is working for me you can click  the link below to know more about it
