### ISSUE TITLE
Question: Flutter doctor --verbose question, flutter/dart plugins in android studio

### ISSUE THREAD

**Issue by jordantsap** [flutter/flutter#73106]
Im using flutter stable version when i run flutter doctor --verbose and i see that , in studio there is no flutter and dart plugins even thought i've install them and configure then inside settings/languages.
When using dev channel On the other hand, the plugins are visible.
How can this be that way?
Stable channel is not that stable?
I know i could use dev channel to avoid this but this issue is not about how to solve this, is about why this happens

**Comment by darshankawar** [comment]
@jordantsap 
This issue was fixed and merged in master and must have reached dev, but not yet in stable https://github.com/flutter/flutter/issues/67986. You may need to wait till it reaches stable. Until then, you may switch to dev or master.
Closing this as already fixed.

**Comment by jordantsap** [comment]
Ok thanks
