### ISSUE TITLE
Arabic diacritcs misbehave when separated into spans

### ISSUE THREAD

**Issue by mrgnedy** [flutter/flutter#73108]
This might be partially related to #73092

I'm facing a problem working with Arabic diacritics as I'm trying to color the diacritics with different color than the letter itself so, I thought of rich text but I ended up with the results below
As seen in the image in the actual results there are two problems:
1- Diacritics don't stack
2- They clip with the letter 
As opposed to when I use a normal non-rich Text
**Expected results:** 
I'm expecting something like this 
![hI9pJ](https://user-images.githubusercontent.com/30890454/103307385-8bcbec80-4a18-11eb-9a06-345debad09ec.png)

**Actual results:** 
But instead I end up with this 
![diacritic](https://user-images.githubusercontent.com/30890454/103307638-3c39f080-4a19-11eb-8464-dcf2edb1a6f1.jpeg)

**Non-rich text:**
![diacritic2](https://user-images.githubusercontent.com/30890454/103308234-9a1b0800-4a1a-11eb-873a-21bb950d4630.jpeg)

It works fine when diacritics and letters are in a single Text string but of course I lose the ability to color the diacritics separately which is the main problem here 
## Steps to Reproduce

1. Create a flutter project
2. Run the following code snippet: 

<details>
  <summary>Snippet</summary>

        Scaffold(
         body: Center(
          child: RichText(
           softWrap: true,
           textWidthBasis: TextWidthBasis.longestLine,
           text: TextSpan(children: [
            TextSpan(
              text: "ك",
              style: TextStyle(
                color: Colors.blue,
                fontSize: 48,
                // fontFamily: "simplified-arabic"و
              ),
            ),
            TextSpan(
              text: "ِّ", //Diacritic
              style: TextStyle(
                color: Colors.red,
                fontSize: 48,
                // fontFamily: "simplified-arabic",
              ),
            ),
            TextSpan(
              text: "ـ",
              style: TextStyle(
                color: Colors.blue,
                fontSize: 48,
                // fontFamily: "simplified-arabic",
              ),
            ),
          ]),
         ),
       ),
     );

</details> 

## Flutter doctor
<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.17.5 at F:\Proging Stuff\Mobile-Flutter\sdk\flutter
    • Framework revision 8af6b2f038 (6 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at F:\Proging Stuff\Mobile-Flutter\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = F:\Proging Stuff\Mobile-Flutter\sdk
    • ANDROID_SDK_ROOT = F:\Proging Stuff\Mobile-Flutter\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\mrgne\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Nokia 7 plus • B2NGAEA841411747 • android-arm64 • Android 10 (API 29)

```

</details>

**Comment by justinmc** [comment]
CC @GaryQian

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RichText(
          softWrap: true,
          textWidthBasis: TextWidthBasis.longestLine,
          text: TextSpan(children: [
            TextSpan(
              text: "ك",
              style: TextStyle(
                color: Colors.blue,
                fontSize: 48,
                // fontFamily: "simplified-arabic"و
              ),
            ),
            TextSpan(
              text: "ِّ", //Diacritic
              style: TextStyle(
                color: Colors.red,
                fontSize: 48,
                // fontFamily: "simplified-arabic",
              ),
            ),
            TextSpan(
              text: "ـ",
              style: TextStyle(
                color: Colors.blue,
                fontSize: 48,
                // fontFamily: "simplified-arabic",
              ),
            ),
          ]),
        ),
      ),
    );
  }
}

``` 

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/tahatesser/Code/flutter_master
    • Framework revision 4b83be6c23 (8 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by mrgnedy** [comment]
Any updates on this?

**Comment by mdebbar** [comment]
This might be due to a "ligature" being separated into two spans.

**Comment by Ayman-Kortobaa** [comment]
Is there any news regarding this issue?

Here is a little repo (Flutter app) showing the issue with different contexts if it can help
https://github.com/Ayman-Kortobaa/flutter_arabic_diacritics

![inApp-Image](https://i.imgur.com/4kSKwrc.jpg)

## Walkthrough

The app has a `Column` with three children to show different usage of diacritics with `TextSpan`.

**note:**  the app uses Uthmanic font but this behavior is apparent with almost every font.

1. The first line is when the diacritics are in a separate `TextSpan` it gets displayed like it is on its own (like how `TextSpan` should be treated but it doesn't work like that in an Arabic context, the previous letter should be taken into account).
1. If the diacritics are in a `TextSpan` with a letter that they should be displayed on they get displayed correctly.
1. Using a `Text` widget with diacritics on a letter (first part) gets displayed correctly, and diacritics on their own (second part) get displayed on baseline (which is correct in this case) like the diacritics in the first line with a single difference is in the first line there is a letter actually before the diacritics so they shouldn't be displayed like that.

## Conclusion
Diacritics get treated correctly by Flutter but in Arabic context is important as even if they are on their own in the `TextSpan` they should care about their position in the sentence.

The same is also applicable for some letters as they can be drawn differently depending on their place in a sentence or word but `TextSpan` doesn't always respect that, the underlined letter in the next picture is drawn longer than it should be when preceded with a `TextSpan` with a different style.

![incorrect-letter](https://i.imgur.com/AHwjjGI.png)

**Comment by GaryQian** [comment]
The way layout currently functions can explain this behavior. When we currently do layout, we pass each span independently down to lay out the glyphs and ligatures. When split into multiple spans, the layout process cannot take the preceding and following spans into account.

@jason-simmons @Rusino Is this something SkParagraph can resolve more easily than LibTxt can?

**Comment by dahabit** [comment]
Hello, any updates on this issue? this is very important to us as Arab Developers and we appreciate any help 

we provided [here](https://github.com/flutter/flutter/issues/73108#issuecomment-855289117) full details about the issue 

and repo for testing [here](https://github.com/Ayman-Kortobaa/flutter_arabic_diacritics)

@behdad @RedBrogdon @eseidelGoogle @slightfoot

**Comment by slightfoot** [comment]
My 10 cents: You can work around this by painting two strings on top of each other and strip the diacritics from the one on top. Not ideal but would give immediate results.

The actual fix for this issue involves Skia and requires a non-trivial engine fix. And lots of testing.

**Comment by dahabit** [comment]
Thank you @slightfoot  for your suggestion will try it , and compare the performance , it will be great if we can get help from other teams to fix this issue as it affects all Arabic language applications

**Comment by behdad** [comment]
This is Working as Expected as far as I'm concerned, in that every time someone decides they need to write a text layout engine from scratch, it takes them five to ten years or more to learn what mistakes not to make. Is sad but is reality.

**Comment by hndrbrm** [comment]
I read from the source code, it seems flutter mechanism to draw text, is to draw one InlineSpan text each, without dependency to other InlineSpan text.

Which is failed in here caused, the draw mechanism in arabic diacritic, made dependency to the previous one.

For example if the previous character is Kaf like in the example above, then the diacritic need to render above it if it is Fathah diacritic. But it failed, since it doesn't consider the previous InlineSpan which is Kaf, so it just rendering itself which is in baseline (bottom) for the Uthmanic font in the example above.

I hope there is another solution for these. We all want to make Qur'an using Flutter, with a beautiful diacritic, for non arab guy, like myself to make it easier to read it.

Imagine if you are muslim flutter engine developer and could solve this, you will get a good deeds point for billion muslim out there which will use the application 🥺. Hopefully it will become your chance to go to heaven in hereafter 😃.

**Comment by tajjacob** [comment]
just use google font plugin

**Comment by joyas10** [comment]
Hey all, 

I'm currently facing the same problem when i parse the "tajweed" rules on arabic writing with "Richtext7Textspan" and found this. 
Are there any updates on this ? 
Has anyone found another solution to this problem ? I would be very grateful if someone has a good tip for me.
Since there are applications that offer "tajweed" function, there must be a solution for this.

i tried it with many different fonts but no one is working correct.

**Comment by tajjacob** [comment]
> Hey all, 
> 
> I'm currently facing the same problem when i parse the "tajweed" rules on arabic writing with "Richtext/Textspan" and found this. 
> Are there any updates on this ? 
> Has anyone found another solution to this problem ? I would be very grateful if someone has a good tip for me.
> Since there are applications that offer "tajweed" function, there must be a solution for this.
> 
> i tried it with many different fonts but no one is working correct.

I'm using plugin Google fonts and solved the problem.

**Comment by joyas10** [comment]
> 
What specific font did you use?

This is how it looks for me: 
(In vers 6 the Lam Alif is double printed for example )

![error](https://user-images.githubusercontent.com/110455561/182538467-5b631832-df67-4c52-aabe-ed6081f2c05f.png)

**Comment by rovshan-b** [comment]
Today I had same problem as in above screenshot (same word repeated twice).
Changing font to [Kitab](https://github.com/quranacademy/kitab-font) solved the issue.

**Comment by joyas10** [comment]
With Kitab Font it is not solved. Than there are other leters which are double printed. For example check in surah 1 Vers 7 the last word. The "alif" after "dad" is double printed. And this is just one example.

**Comment by rovshan-b** [comment]
This is how it looks for me:
![image](https://user-images.githubusercontent.com/12267949/201822821-c5df9a99-47a5-4e9e-b55e-0174c3cc1274.png)

**Comment by joyas10** [comment]
This is how it looks for me with Kitab (kitab-regular.ttf) font: 
![image](https://user-images.githubusercontent.com/110455561/201853226-765d5ff7-8109-4a74-b528-6640acbc4dc9.png)

With AmiriQuran Font this is problem is solved:
![amiriquran](https://user-images.githubusercontent.com/110455561/201853577-98a6964e-c0bd-4ea9-98e6-2035b4a20323.png)

BUT than i get in Surah Aal-I-Imran Aya 5 again double printed Alifs in the last word :
![amiriquran2](https://user-images.githubusercontent.com/110455561/201854096-8e0644f9-2d7e-408a-a717-dde581efb0d8.png)

**Comment by rovshan-b** [comment]
I extracted Tajweed rules highlighting part from my project and added to [this](https://github.com/rovshan-b/Quran-flutter-tajweed) repository. Could you please, check whether it works for you? Please, make sure that you are using latest version of Flutter.

**Comment by joyas10** [comment]
Your implementation is great and works for me. I am trying to find the error in my implementation using your code. If I don't get it solved, would you allow me to use your code and adapt it for me?

**Comment by rovshan-b** [comment]
Yes, of course, that is the reason I shared it. You can use it freely.
Also you can send PR's when you implement rules that I did not implement, as I am also still working on this project and doing modifications.

**Comment by joyas10** [comment]
Great, thank you very much.

**Comment by rovshan-b** [comment]
You are welcome brother.

**Comment by darshankawar** [comment]
Verified this using latest stable and master versions and observed that the originally reported / described behavior persists upon running the [code sample](https://github.com/flutter/flutter/issues/73108#issuecomment-752654401).

<img width="125" alt="Screenshot 2023-02-08 at 5 19 48 PM" src="https://user-images.githubusercontent.com/67046386/217521849-e66300ec-29b1-4fb6-86f8-81d7bd876117.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (28 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-7.0.pre.23, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.8.0-7.0.pre.23 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e7f580370 (14 minutes ago), 2023-02-08 12:37:24 +0800
    • Engine revision f310ffd146
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by LongCatIsLooong** [comment]
https://user-images.githubusercontent.com/67046386/217521849-e66300ec-29b1-4fb6-86f8-81d7bd876117.png

This seems to be the correct rendering of the glyph. @Rusino has fixed this in skparagraph. Closing.
