### ISSUE TITLE
Flutter plugin not installed. Dart plugin not installed

### ISSUE THREAD

**Issue by ThePhoenixRisen** [flutter/flutter#73104]
On my first app created from tutorial https://www.youtube.com/watch?v=x0uinJvhNxI&t=2881s starting at 42:23, I am getting from the cmd that Flutter and Dart plugins are not installed. I have installed both and made sure all components on Android Studio and Flutter are up to date. The one thing I find off is that cmd states I have Android Studio 4.1.0. The About section of Android Studio states I have Android Studio 4.1.1

Installed Git. Downloaded Zip file for Flutter. Extracted flutter to C:\Program Files\flutter. Changed enviroment variables and gave proper permissions. Installed Android Studio. 
`cd School\Development
flutter create first_app
cd first_app
flutter doctor`

![CMD](https://user-images.githubusercontent.com/71746795/103304717-fb1cee80-49ce-11eb-8350-e503881c51ab.JPG)
![Flutter](https://user-images.githubusercontent.com/71746795/103304724-fd7f4880-49ce-11eb-91ff-a62a5bf5e98c.JPG)
![Dart](https://user-images.githubusercontent.com/71746795/103304725-ff490c00-49ce-11eb-93d3-a24c3ef00eb1.JPG)

**Comment by darshankawar** [comment]
@ThePhoenixRisen 
This is already fixed and merged in master. https://github.com/flutter/flutter/issues/67986
Please switch to latest master and try again to see if it works. Also note that, even if the `flutter doctor -v` says plugins are not installed, they are just warnings, but you should be able to use those plugins inside your dev environment as usual without any issues.

Closing this as already fixed. If you still see this issue, write in comments and I'll reopen it.
Thanks.
