### ISSUE TITLE
assertion failed: sorted descendants are missing some nodes

### ISSUE THREAD

**Issue by dfrankow** [flutter/flutter#73115]
Exception is below.

On OS X (10.14.6)
From platform emulator: "orange rise 32 API 23 (android 6.0)"
```
$ flutter --version
```
Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2294d75bfa (10 months ago) • 2020-03-07 00:28:38 +0900
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
sorted descendants are missing some nodes: ({FocusNode#8ecde})
'package:flutter/src/widgets/focus_traversal.dart':
Failed assertion: line 308 pos 7: 'scope.traversalDescendants.toSet().difference(sortedDescendants.toSet()).isEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      FocusTraversalPolicy._sortAllDescendants (package:flutter/src/widgets/focus_traversal.dart:308:7)
#3      FocusTraversalPolicy._moveFocus (package:flutter/src/widgets/focus_traversal.dart:347:41)
#4      FocusTraversalPolicy.next (package:flutter/src/widgets/focus_traversal.dart:191:39)
#5      FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1068:55)
#6      NextFocusAction.invoke (package:flutter/src/widgets/focus_traversal.dart:1780:54)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by dfrankow** [comment]
Note: I was putting together an app from https://www.djamware.com/post/5ebb3fcf9c9e8f5505054768/flutter-tutorial-sqlite-offline-crud-ios-and-android-apps, with some modifications. It looks like it's working, so I don't know what the assert was about.

It is not easy for me to reproduce.

**Comment by darshankawar** [comment]
@dfrankow 
You seem to be on very old version of Flutter `Framework • revision 2294d75 (10 months ago) • 2020-03-07 00:28:38 +0900`.
I'd recommend you to first upgrade to latest version and try again to see if it works.

If issue persists, provide latest `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by justinmc** [comment]
CC @gspencergoog if this issue persists after upgrading.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
