### ISSUE TITLE
HTML tags support in RichText?

### ISSUE THREAD

**Issue by Katarn** [flutter/flutter#7311]
Will be implemented of support of HTML-tags processing at least at the same level as that of the native TextView widget?

**Comment by Hixie** [comment]
can you elaborate on what you want to do?

**Comment by Katarn** [comment]
@Hixie I want to try to write an application with the news list, in which the text of each news will be able to handle simple tags - <a>, <b>, <i>, <strong>, <em>, <br>, <span> with inline styles support.

**Comment by Hixie** [comment]
Ah, I see. You can write a simple parser which converts your input string into TextSpans, in much the same way as we do for markdown: https://github.com/flutter/flutter/tree/master/packages/flutter_markdown

I doubt we will implement true HTML support, that's a multiyear effort for hundreds of people with no end in sight.

**Comment by Katarn** [comment]
@Hixie thanks for answering!

**Comment by eseidelGoogle** [comment]
I suspect someone will write a small pub package to do some of this.  I know that others have already forked flutter_markdown to add some html support, or discussed doing so in gitter.im/flutter/flutter.  @olostan might know.

**Comment by olostan** [comment]
Yes, as I had to implement quick-and-dirty solution, I didn't extracted into separate pub package, but if you interested, I can quickly do. 

Until then, you can just copy [this folder](https://github.com/olostan/cruisedeals/tree/master/lib/markdown) to your app and use it :)

**Comment by Katarn** [comment]
@olostan Thanks, I'll try your solution! So far, a separate package do not need me, I'm just studying the possible tools and frameworks for write my amateur app. :)

**Comment by Katarn** [comment]
Hi guys. I did the necessary me widget, but I found a very serious limitation of the framework - all ListItems have a fixed height. In general, I understand that the framework is still very young. I will follow his further development.

If you're curious, here's what I got: https://gist.github.com/Katarn/588725dce850c81da8a551f92fb0923a. It is my first application on the Dart. :) Suffice it to replace this file main.dart file in any flutter application - in its all-inclusive for the successful launch demo application.

You can close this issue, if you think that the framework for such a widget is not required. For me, this issue has been resolved.

**Comment by eseidelGoogle** [comment]
This has come up before.  ListItem should probably be renamed MaterialListItem (or template?) and add some documentation explaining that it's fixed height because that's what the Material spec says to do. :)  https://docs.flutter.io/flutter/material/ListItem-class.html

I believe https://docs.flutter.io/flutter/widgets/LazyBlock-class.html is the alternative list you want.  @Hixie I'm sure will correct me if I'm wrong. :)

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/7318 to track improving docs/naming.

**Comment by Katarn** [comment]
@eseidelGoogle thanks, I'll try this widget after holidays. It supports the scroll position indicator?

**Comment by eseidelGoogle** [comment]
My understanding is that scrollbars do not work today (https://github.com/flutter/flutter/issues/5525) but @Hixie is in the process of adding them as part of his grand scrolling refactor: https://github.com/flutter/flutter/projects/3

**Comment by Hixie** [comment]
Not clear what to do for this bug. We do not intend to ever support HTML directly though.

**Comment by Hixie** [comment]
WebView is https://github.com/flutter/flutter/issues/730
