### ISSUE TITLE
[macos] error: is only available in macOS 10.15 or newer

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73122]
## Bug

When I try to `flutter run -d macos` with a `flutter_web_auth: 0.2.4` dependency, the build fails with the following error:

```
error: 'FlutterWebAuthPlugin' is only available in macOS 10.15 or newer
```

I believe that this is a framework issue rather than a plugin issue because it seems that the plugin is usable for some users on macOS.

### Setup

Apart from the `flutter_web_auth` dependency, I took two steps:

* Run `flutter create --platforms=macos .` in an existing project.
* Change `platform :osx, '10.11'` to `platform :osx, '10.15'` in `macos/Podfile`.

## Workaround fix

I found a way to fix this problem: using Android Studio's `Find in path...`, I was able to find all `10.11` occurrences and simply replaced them by `10.15`.

Most of them are `MACOSX_DEPLOYMENT_TARGET` values in `macos/Pods/Pods.xcodeproj/project.pbxproj`. However, this is a generated file and editing it cannot possibly be generally intended.

## Versions

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-1.0.pre at /Users/user/Library/flutter
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88
```
</details>

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Thank you for filing the issue

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 63062a6443 (2 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.156, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.156 at /Users/tahatesser/Code/flutter_master
    • Framework revision e7e7bb2ef5 (3 hours ago), 2020-12-29 23:44:01 -0500
    • Engine revision d3a0669458
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> I believe that this is a framework issue rather than a plugin issue

It is not; the plugin [requires 10.15](https://github.com/LinusU/flutter_web_auth/blob/master/macos/flutter_web_auth.podspec#L18) as the error message says, while the default project created by `flutter create` supports back to macOS 10.11. You can't use a plugin that requires a newer version of macOS than you are building your app for.

> Most of them are MACOSX_DEPLOYMENT_TARGET values in macos/Pods/Pods.xcodeproj/project.pbxproj. However, this is a generated file and editing it cannot possibly be generally intended.

You should not need to change the target of other plugins, just your application itself (via the Xcode project for the runner).

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Thanks.

Is this documented somewhere? I appreciate your response.

I am obviously not exactly sure how this works, hence the issue.

I saw all of what you said as well, however, I am missing docs for it / do not know how to do it through Xcode.

**Comment by stuartmorgan** [comment]
I would imagine that there is Apple documentation on managing build settings in Xcode, but I don't have a link offhand. There's no Flutter-specific documentation of the process, if that's what you mean; it isn't any different in a Flutter macOS application as it would be any other macOS application.

If you don't want to use Xcode, you can change `MACOSX_DEPLOYMENT_TARGET` directly in `Runner.xcodeproj/project.pbxproj`.

**Comment by creativecreatorormaybenot** [comment]
Thanks a lot 🙂 If anyone else is wondering, here is a screenshot for reference:

<img width="1189" alt="Screen Shot 2020-12-30 at 11 31 23 PM" src="https://user-images.githubusercontent.com/19204050/103386532-2995e900-4af7-11eb-9118-340670108ccb.png">


@stuartmorgan When running `flutter create`, the `platform :osx, '10.11'` entry in the `Podfile` is also set to `10.11`.  
I was not able to find a setting in Xcode for adjusting that - so do we need to do that manually?

That is even after adjusting the deployment target, there will be the following error:

```
Specs satisfying the `flutter_web_auth (from
    `Flutter/ephemeral/.symlinks/plugins/flutter_web_auth/macos`)` dependency
    were found, but they required a higher minimum deployment target.
```

And this is resolved by adjusting the `platform :osx, <version>`.

**Comment by stuartmorgan** [comment]
If adjusting the project's Podfile is necessary as well, then yes, you'd need to do that manually. Podfiles are not part of Xcode.
