### ISSUE TITLE
Unhandled error MissingPluginException(No implementation found for method createUserWithEmailAndPassword on channel plugins.flutter.io/firebase_auth) occurred in    Instance of 'SignInFormBloc'.

### ISSUE THREAD

**Issue by darshanputtaswamy** [flutter/flutter#73125]
I am trying the integrate firebase with flutter web. 
when I try to register a new user it fails with the below error. 

$ flutter run
Multiple devices found:
Web Server (web) • web-server • web-javascript • Flutter Tools
Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88
[0]: Web Server (web-server)
[1]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Running "flutter pub get" in test_app...                         1,538ms
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                  18.1s
Debug service listening on ws://127.0.0.1:62397/s2S44BOg2aE=/ws

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
``
**Error: Unhandled error MissingPluginException(No implementation found for method
createUserWithEmailAndPassword on channel plugins.flutter.io/firebase_auth) occurred in   
Instance of 'SignInFormBloc'.**
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
packages/flutter/src/services/platform_channel.dart 157:7
_invokeMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1450:54
runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 143:18   
handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 696:44   
handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 725:32   
_propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 529:5    
[_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:7    
callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart   
41:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart   
50:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

    at Object.throw_ [as throw] (http://localhost:62336/dart_sdk.js:4348:11)
    at http://localhost:62336/packages/bloc/src/cubit.dart.lib.js:105:21
    at sign_in_form_bloc.SignInFormBloc.new.onError
    (http://localhost:62336/packages/bloc/src/cubit.dart.lib.js:106:25)
    at sign_in_form_bloc.SignInFormBloc.new.onError
    (http://localhost:62336/packages/bloc/src/cubit.dart.lib.js:243:15)
    at _RootZone.runBinaryGuarded (http://localhost:62336/dart_sdk.js:37753:11)
    at sendError (http://localhost:62336/dart_sdk.js:31342:26)
    at _BroadcastSubscription.new.[_sendError]
    (http://localhost:62336/dart_sdk.js:31359:11)
    at _BroadcastSubscription.new.[_addError]
    (http://localhost:62336/dart_sdk.js:31282:27)
    at http://localhost:62336/dart_sdk.js:32012:34
    at _SyncBroadcastStreamController.new.[_forEachListener]
    (http://localhost:62336/dart_sdk.js:31858:13)
    at _SyncBroadcastStreamController.new.[_sendError]
    (http://localhost:62336/dart_sdk.js:32010:31)
    at _SyncBroadcastStreamController.new.[_addError]
    (http://localhost:62336/dart_sdk.js:31835:25)
    at _RootZone.runBinaryGuarded (http://localhost:62336/dart_sdk.js:37753:11)
    at sendError (http://localhost:62336/dart_sdk.js:31342:26)
    at _ForwardingStreamSubscription.new.[_sendError]
    (http://localhost:62336/dart_sdk.js:31359:11)
    at _ForwardingStreamSubscription.new.[_addError]
    (http://localhost:62336/dart_sdk.js:31282:27)
    at _ForwardingStreamSubscription.new.[_addError]
    (http://localhost:62336/dart_sdk.js:35462:25)
    at _MapStream.new.[_handleError] (http://localhost:62336/dart_sdk.js:35416:24)        
    at _ForwardingStreamSubscription.new.[_handleError]
    (http://localhost:62336/dart_sdk.js:35488:38)
    at _RootZone.runBinaryGuarded (http://localhost:62336/dart_sdk.js:37753:11)
    at sendError (http://localhost:62336/dart_sdk.js:31342:26)
    at _ControllerSubscription.new.[_sendError]
    (http://localhost:62336/dart_sdk.js:31359:11)
    at async._DelayedError.new.perform (http://localhost:62336/dart_sdk.js:34724:27)
    at _StreamImplEvents.new.handleNext (http://localhost:62336/dart_sdk.js:34806:15)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:62336/dart_sdk.js:34558:16)
    at Object._microtaskLoop (http://localhost:62336/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:62336/dart_sdk.js:38077:13)
    at http://localhost:62336/dart_sdk.js:33574:9
``

**Comment by darshankawar** [comment]
@darshanputtaswamy 
This seems to be an issue with Firebase which has separate repo for tracking. Consider opening this issue here : https://github.com/FirebaseExtended/flutterfire/issues
Closing from this repo.
