### ISSUE TITLE
Support Swift in  ios template project

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7312]
As Swift is the future of development with any Apple product, I'd like to know if the ios template that is generated from `flutter create` could be a swift template rather than an obj-c template. 

The code readability of swift in substantially higher that obj-c and seeing as how one of flutters goals is to make development across platforms simple, readability is an easy way to help with simplicity.

**Comment by sethladd** [comment]
I like this idea. I personally find myself able to read and understand Swift, but not ObjC.

**Comment by mit-mit** [comment]
I like it to; Swift is a lot easier to read.

But for plugins / native interop purposes we likely will need to support both. AFAIK that should be possible, as iOS supports projects with both using "mix and match":
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by sethladd** [comment]
@mit-mit if we change the output of `flutter create` to use Swift, how would that impact plugins?

(agreed that our plugins should support user code written in both objc and swift)

**Comment by mit-mit** [comment]
We think it will be fine, but we need to do more work to confirm it.

**Comment by mit-mit** [comment]
Changing this to supporting Swift as an option, in addition to OjbC. This could be something like `flutter create -swift myapp`

**Comment by rxlabz** [comment]
I suppose it's planned, but an option for swift plugin template like `flutter create --plugin -swift myplugin` would be handy.

**Comment by eseidelGoogle** [comment]
@rxlabz wrote one btw: https://github.com/rxlabz/FlutterSwiftPlugin-template

**Comment by mravn-google** [comment]
Closed per #10259
