### ISSUE TITLE
[web] ResizeImage not working

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73120]
When using [`ResizeImage`][docs], the resizing seems to be completed ignored on web.

## General steps to Reproduce

1. Use [`ResizeImage`][docs].
2. Run using `flutter run -d chrome --web-renderer canvaskit

**Expected results:** images get resized down to the specified size.

**Actual results:** the resizing is ignored on web.

This happens on the latest Flutter version:

<details><summary>doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.150, on macOS 11.1 20C69 darwin-x64,
    locale en-US)
    • Flutter version 1.26.0-2.0.pre.150
    • Framework revision 5b1aa60a46 (4 hours ago), 2020-12-29 12:06:41 -0800
    • Engine revision b304148d46
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88
```

</details>

### Detailed steps

I have no **widget** example for this but use `ResizeImage` directly. Because the setup is a little more involved, it would be super annoying to copy-paste everything into the GitHub text field.

Instead, I have some easy steps that directly use the [code from my repo](https://github.com/creativecreatorormaybenot/funvas/blob/17d3f685a823a9633256383c735f706f6b5c5580/funvas_tweets/lib/src/10.dart#L29):

* Make sure you are on the `master` channel and that you have run `flutter config --enable-web` and `flutter config --enable-macos` (or `flutter config --enable-windows` on Windows).
* `git clone https://github.com/creativecreatorormaybenot/funvas.git`
* `cd funvas/funvas_demo`
* `git checkout 332d84045c5e03ff850f0b999921d7c6d49b88a9`
* Now, follow the step below for both `flutter run -d chrome --web-renderer canvaskit --no-sound-null-safety` **and** `flutter run -d macos  --no-sound-null-safety` (or `-d windows`) to see the difference.
* Run the app (on web and on desktop) and press the left arrow button once in that app.

| Web | Desktop |
| :---: | :-------: |
| <img width="1150" alt="Screen Shot 2020-12-30 at 12 24 43 AM" src="https://user-images.githubusercontent.com/19204050/103322269-6bf6f180-4a35-11eb-984e-a6f0e533b64f.png"> | <img width="1239" alt="Screen Shot 2020-12-30 at 12 44 52 AM" src="https://user-images.githubusercontent.com/19204050/103322925-3e5f7780-4a38-11eb-919f-85bb1d682a53.png"> |

As you can see on **dekstop**, the overlayed image is _scaled down_ (to 245x245), however, on **web**, it will not be scaled down and stay the same size as the background image (420x420).

[docs]: https://api.flutter.dev/flutter/painting/ResizeImage-class.html

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
Thanks for filing the issue, I can reproduce it using the steps on the web.
<details> 
<summary>code sample</summary> 

```dart
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.26.0-2.0.pre.157 at C:\Code\flutter_master
    • Framework revision 4b83be6c23 (2 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 5.0.2 (API 21) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.685]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
``` 

</details>
Thank you

**Comment by yjbanov** [comment]
Corresponding Skia issue: https://bugs.chromium.org/p/skia/issues/detail?id=11275

**Comment by yjbanov** [comment]
Unassigning for now as this is blocked on Skia API.

**Comment by HayesGordon** [comment]
Hi 👋 , any update on this? I see that the Skia issue status is now marked as done?

**Comment by mboyamike** [comment]
Also asking, any update on this? Just faced it

**Comment by hterkelsen** [comment]
This issue is fixed now
