### ISSUE TITLE
Could not resolve io.flutter:armeabi_v7a_release:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4.

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#73135]
When I tried to integrate flutter natively in android, in the form of aar, referring to the official tutorial, there would be such a problem in the console of the native project. Only the debug mode library can be pulled down, but the release mode cannot be pulled down. In addition, where can this jar package be downloaded from?

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve io.flutter:armeabi_v7a_release:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4.
Show Details
Affected Modules: app

please help me ！！！！

**Comment by TahaTesser** [comment]
Hi @haibowen 
Please provide steps to reproduce the issue
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by haibowen** [comment]
> Hi @haibowen
> Please provide steps to reproduce the issue
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

hi @TahaTesser

My environment is as follows

hyplo@MacBook-Pro flutter_demo_show % flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[!] IntelliJ IDEA Community Edition (version 2020.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
hyplo@MacBook-Pro flutter_demo_show % 

My Resynt step  

https://flutter.dev/docs/development/add-to-app/android/project-setup  

Integrated into android in the form of aar

**Comment by TahaTesser** [comment]
Hi @haibowen 
Following the steps, I have no issues  when building aar but I see you are using Flutter from China

<details> 
<summary>logs</summary> 

```bash
tahatesser@Tahas-MacBook-Pro flutter_module % flutters build aar
Running Gradle task 'assembleAarDebug'...                               
Running Gradle task 'assembleAarDebug'... Done                     17.4s
✓ Built build/host/outputs/repo.
Running Gradle task 'assembleAarProfile'...                             
Running Gradle task 'assembleAarProfile'... Done                   29.5s
✓ Built build/host/outputs/repo.
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   25.1s
✓ Built build/host/outputs/repo.

Consuming the Module
  1. Open <host>/app/build.gradle
  2. Ensure you have the repositories configured, otherwise add them:

      String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?: "https://storage.googleapis.com"
      repositories {
        maven {
            url '/Users/tahatesser/AndroidStudioProjects/triage/add2app_examples/flutter_module/build/host/outputs/repo'
        }
        maven {
            url '$storageUrl/download.flutter.io'
        }
      }

  3. Make the host app depend on the Flutter module:

    dependencies {
      debugImplementation 'com.nevercode.flutter_module:flutter_debug:1.0'
      profileImplementation 'com.nevercode.flutter_module:flutter_profile:1.0'
      releaseImplementation 'com.nevercode.flutter_module:flutter_release:1.0'
    }


  4. Add the `profile` build type:

    android {
      buildTypes {
        profile {
          initWith debug
        }
      }
    }

To learn more, visit https://flutter.dev/go/build-aar
tahatesser@Tahas-MacBook-Pro flutter_module % 
```

</details>

<details> 
<summary>build.gradle</summary> 

```bash
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.nevercode.android_using_prebuilt_module"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        profile {
            initWith debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

repositories {
    maven {
        url '../../flutter_module/build/host/outputs/repo'
    }
    maven {
        url 'https://storage.googleapis.com/download.flutter.io'
    }
}

dependencies {
    debugImplementation 'com.nevercode.flutter_module:flutter_debug:1.0'
    profileImplementation 'com.nevercode.flutter_module:flutter_profile:1.0'
    releaseImplementation 'com.nevercode.flutter_module:flutter_release:1.0'

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

</details>


Please check out [Using Flutter in China](https://flutter.dev/community/china)

If the problem persists, please provide complete `flutter build aar` and logs from Android. Also, try running the official [examples](https://github.com/flutter/samples/tree/master/add_to_app) to see if you're not missing something

**Comment by haibowen** [comment]
> Hi @haibowen
> Following the steps, I have no issues when building aar but I see you are using Flutter from China
> 
> logs
> build.gradle
> Please check out [Using Flutter in China](https://flutter.dev/community/china)
> 
> If the problem persists, please provide complete `flutter build aar` and logs from Android. Also, try running the official [examples](https://github.com/flutter/samples/tree/master/add_to_app) to see if you're not missing something

Hi @TahaTesser
  thanks ！
I use in China  
thank you very much！

> Hi @haibowen
> Following the steps, I have no issues when building aar but I see you are using Flutter from China
> 
> logs
> build.gradle
> Please check out [Using Flutter in China](https://flutter.dev/community/china)
> 
> If the problem persists, please provide complete `flutter build aar` and logs from Android. Also, try running the official [examples](https://github.com/flutter/samples/tree/master/add_to_app) to see if you're not missing something

Hi @TahaTesser
  thanks ！
I use in China  
thank you very much！
