### ISSUE TITLE
Will want some way to validate cache files

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7313]
https://github.com/flutter/flutter/issues/7308 is another example of someone getting a corrupted bin/cache and then being stuck.

Not sure there is anything specific to do at this time, but something to track and consider for future improvement.

**Comment by zoechi** [comment]
@eseidel do you think there is still something to do?

**Comment by eseidelGoogle** [comment]
I haven't heard of any of these recently.  I think @goderbauer and @gspencergoog may have fixed them all.
