### ISSUE TITLE
Same Issue

### ISSUE THREAD

**Issue by darshankhadse** [flutter/flutter#73144]
Same here
Flutter app still shows me only blank white screen on release apk, but ok when debug version.
No one solution above either helped.

_Originally posted by @KanybekMomukeyev in https://github.com/flutter/flutter/issues/58247#issuecomment-737022991_

**Comment by justinmc** [comment]
I'm not sure what this issue is about.  Could you fill in all of the details and include a minimal app that reproduces your problem?  If so I'm happy to reopen.
