### ISSUE TITLE
errno5

### ISSUE THREAD

**Issue by f-ctrl** [flutter/flutter#73148]
when i tried to create a new app in flutter it this this error ,can anybody help me solve it iam basically new to programming and dont know much about this stuff.Btw i am using vscode.

below is the error:

PS C:\Users\Faiz mohd\Desktop\Flutter App> flutter create first  
Creating project first...
  ```
first\.gitignore (created)
  first\.idea\libraries\Dart_SDK.xml (created)
  first\.idea\libraries\KotlinJavaRuntime.xml (created)
  first\.idea\modules.xml (created)
  first\.idea\runConfigurations\main_dart.xml (created)
  first\.idea\workspace.xml (created)
  first\.metadata (created)
  first\android\app\build.gradle (created)
  first\android\app\src\main\kotlin\com\example\first\MainActivity.kt (created)
  first\android\build.gradle (created)
  first\android\first_android.iml (created)
  first\android\.gitignore (created)
  first\android\app\src\debug\AndroidManifest.xml (created)
  first\android\app\src\main\AndroidManifest.xml (created)
  first\android\app\src\main\res\drawable\launch_background.xml (created)
  first\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)

Failed to send crash report due to a network error: SocketException: OS Error: The semaphore timeout period has expired.
, errno = 121, address = clients2.google.com, port = 50764
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to 'C:\Users\Faiz mohd\Desktop\Flutter
App\first\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)".
 
A crash report has been written to C:\Users\Faiz mohd\Desktop\Flutter App\flutter_01.log.
```

**Comment by darshankawar** [comment]
@f-ctrl 
This issue has already been fixed and merged, https://github.com/flutter/flutter/issues/50880
What Flutter version are you on ? Please upgrade to latest master or stable and try again to see if it works.
If issue persists,  attach `flutter_01.log` the crash log generated as mentioned in your error log : `C:\Users\Faiz mohd\Desktop\Flutter App\flutter_01.log.`

**Comment by f-ctrl** [comment]
My error still persists ,Btw i am using the latest stable build of flutter and i have attached the flutterlog file below 
[flutter_01.log](https://github.com/flutter/flutter/files/5756748/flutter_01.log)
can you help me with this 
And thankyou for replying

**Comment by darshankawar** [comment]
@f-ctrl 
Can you switch to latest master and try again to see if it works or get same error ?

**Comment by f-ctrl** [comment]
I did but no ,when i try to create the same app with android studio my app got created but when  I tried to run that app it shows exit code 1 and while while using vs-code I got the error code errno5, I don't know what to do now

**Comment by darshankawar** [comment]
@f-ctrl 
I see you have spaces between folder names in your path `C:\Users\Faiz mohd\Documents\Flutter App>`
Can you remove the spaces and try again ?  like : `C:\Users\Faizmohd\Documents\FlutterApp>`

**Comment by f-ctrl** [comment]
ahh thankyou it worked at last, so glad its working fine

**Comment by f-ctrl** [comment]
Ahh thank you I see where my issue was ,its working fine now all thanks to you

**Comment by Abhishek01039** [comment]
Hello @f-ctrl 
you can close this issue if you got the solution.
Thanks

**Comment by darshankawar** [comment]
Closing this based on comment above.
