### ISSUE TITLE
Arabic Vowels in TextSpan

### ISSUE THREAD

**Issue by tajaouart** [flutter/flutter#73140]
Hello,

When using a TextView the vowels above Arabic Characters are well placed and look nice but when using TextSpan to create a word, the vowels and characters are not well placed and one is hiding behind another.

Example of the alphabet   ث  with the Vowel  ْ   in the word  إثْنان  here it is looking nice but using TextSpan the ْ  hides behind the 3 dots.

Thanks.

<details> 
<summary>flutter doctor -v</summary> 

```bash
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [version 10.0.18363.1256], locale fr-FR)
    • Flutter version 1.25.0-8.1.pre at C:\Users\aksel\AppData\Local\Android\flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\\Users\\aksel\\AppData\\Local\\Android\\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\aksel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\aksel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • SM J330FN (mobile) • 4200c553c63415c9 • android-arm    • Android 9 (API 28)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @tajaouart 
Are you referring to this https://github.com/flutter/flutter/issues/73108? 
Also, check out https://github.com/flutter/flutter/issues/73092.
If not, please provide more details Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
