### ISSUE TITLE
AppBar set toolbarHeight

### ISSUE THREAD

**Issue by gongshaozhu** [flutter/flutter#73157]
'package:flutter/src/material/scaffold.dart': Failed assertion: line 2406 pos 14: '_appBarMaxHeight >= 0.0 && _appBarMaxHeight.isFinite': is not true.

**Comment by darshankawar** [comment]
@gongshaozhu 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.
flutter_screenutil: ^4.0.2
appBar: AppBar(
        backgroundColor: Colors.grey[300],
        toolbarHeight: 80.0.h,
        elevation: 0,
        title: Text(
          'app',
          style: TextStyle(color: Colors.black, fontSize: 30.ssp),
        ),
        centerTitle: true,
        leading: Center(
          child: Container(
            width: 60.w,
            height: 60.h,
            child: Image.asset('images/logo.png'),
          ),
        ),
        automaticallyImplyLeading: false,
      ),

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.

flutter_screenutil: ^4.0.2

`@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.grey[300],
        toolbarHeight: 80.0.h,
        elevation: 0,
        title: Text(
          'app',
          style: TextStyle(color: Colors.black, fontSize: 30.ssp),
        ),
        centerTitle: true,
        // leadingWidth: 150.w,
        leading: Center(
          child: Container(
            width: 60.w,
            height: 60.h,
            child: Image.asset('images/logo.png'),
          ),
        ),
        automaticallyImplyLeading: false,
        actions: [
          Container(
            width: 200.w,
            child: Stack(
              children: [Text('news')],
            ),
          )
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        iconSize: 20,
        type: BottomNavigationBarType.fixed,
        currentIndex: currentIndex,
        items: bottomTabs,
        onTap: (index) {
          setState(() {
            currentIndex = index;
            currengPage = tabBodies[currentIndex];
          });
        },
      ),
      body: currengPage,
    );
  }`

**Comment by gongshaozhu** [comment]
> > @gongshaozhu
> > Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> > Thanks.
> 
> flutter_screenutil: ^4.0.2
`@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.grey[300],
        toolbarHeight: 80.0.h,
        elevation: 0,
        title: Text(
          'app',
          style: TextStyle(color: Colors.black, fontSize: 30.ssp),
        ),
        centerTitle: true,
        // leadingWidth: 150.w,
        leading: Center(
          child: Container(
            width: 60.w,
            height: 60.h,
            child: Image.asset('images/logo.png'),
          ),
        ),
        automaticallyImplyLeading: false,
        actions: [
          Container(
            width: 200.w,
            child: Stack(
              children: [Text('news')],
            ),
          )
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        iconSize: 20,
        type: BottomNavigationBarType.fixed,
        currentIndex: currentIndex,
        items: bottomTabs,
        onTap: (index) {
          setState(() {
            currentIndex = index;
            currengPage = tabBodies[currentIndex];
          });
        },
      ),
      body: currengPage,
    );
  }`

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.

![image](https://user-images.githubusercontent.com/43201283/103400913-c7ce9100-4b81-11eb-83a9-79e813efa926.png)

**Comment by gongshaozhu** [comment]
![image](https://user-images.githubusercontent.com/43201283/103400949-eb91d700-4b81-11eb-8f26-28d533544441.png)

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.

![Uploading image.png…]()

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
> Thanks.

![image](https://user-images.githubusercontent.com/43201283/103400971-082e0f00-4b82-11eb-8ddd-ade6e8b4aabe.png)

**Comment by xu-baolin** [comment]
@gongshaozhu Why did you set a double property with `100.h`?

**Comment by gongshaozhu** [comment]
> @gongshaozhu Why did you set a double property with `100.h`? It is not a valid double.
flutter_screenutil: ^4.0.2 
example: set width or height   (  width: 100.w   height: 100.h)

**Comment by gongshaozhu** [comment]
> @gongshaozhu Why did you set a double property with `100.h`? It is not a valid double.

I used 100.0.h，It not work.

**Comment by xu-baolin** [comment]
What does `.h` mean?

**Comment by darshankawar** [comment]
@gongshaozhu 
I think you are able to use `100.h` and `100.w` due to the 3rd party plugin you are using `flutter_screenutil`. Can you directly provide height as 100 and try again to see if you still get same issue or not ?
If not, then it could be an issue with the plugin you are using and may have to open this issue in the plugin owner's repo.

**Comment by gongshaozhu** [comment]
> @gongshaozhu
> I think you are able to use `100.h` and `100.w` due to the 3rd party plugin you are using `flutter_screenutil`. Can you directly provide height as 100 and try again to see if you still get same issue or not ?
> If not, then it could be an issue with the plugin you are using and may have to open this issue in the plugin owner's repo.

thank you !
It's solved. It's probably height over
![image](https://user-images.githubusercontent.com/43201283/103407958-8a76fd00-4b9b-11eb-91dc-ca3de62a5626.png)
