### ISSUE TITLE
Google Maps intermittent render errors

### ISSUE THREAD

**Issue by craigjp99** [flutter/flutter#73156]
Hi, apologies if this shouldn't be logged as an issue .... initially I just want some guidance on whether this is something I should be concerned about, or just let it go for now (given the nature of when the problem occurs).
I'm using the "google_maps_flutter" (currently 1.0.6) plug-in to show a map with markers (based on different search criteria).  Intermittently (most often when I'm first starting a debug session), the map widget may render in one of the following ways:
![flutter_map_error](https://user-images.githubusercontent.com/66446471/103391765-29393480-4b6f-11eb-8d12-231328eb1f76.png)
or
![flutter_map_duplicate](https://user-images.githubusercontent.com/66446471/103391784-31916f80-4b6f-11eb-9364-2936e30cd64b.png)

I can't say there's any particular rhyme or reason as to which problem may occur, and the problem only occurs maybe 50% of the time - ie. often I can fire up my laptop, start up Visual Studio and the android emulator, start debugging, and it will work as expected.  Working as expected means the map should render something like this:
![flutter_map_correct](https://user-images.githubusercontent.com/66446471/103391935-af557b00-4b6f-11eb-88d5-0f1d372721e5.png)

I should add that any time one of the "problem" rendering happens, if I just stop the debug session and restart then the map will render fine, and from then on I can do all sorts of different searches (that may rebuild the map with different markers), it will continue to render fine.

So, like I said in the intro, based on people's past experience (either with the same plug-in, or just debugging flutter apps in general), should I let this problem go and assume it's probably a development environment issue - or is there likely some underlying issue in my app that could potentially still cause the same problems to occur once it's released.  (I've not yet got to that point).
Cheers, Craig

**Comment by darshankawar** [comment]
@craigjp99 
I believe the complete error message in console you get is below:

```
setState() or markNeedsBuild() called during build.
I/flutter ( 6677): This Overlay widget cannot be marked as needing to build because the framework is
I/flutter ( 6677): already in the process of building widgets. A widget can be marked as needing to be built during the
I/flutter ( 6677): build phase only if one of its ancestors is currently building. This exception is allowed because
I/flutter ( 6677): the framework builds parent widgets before children, which means a dirty descendant will always be
I/flutter ( 6677): built. Otherwise, the framework might not visit this widget during this build phase.
```

There's similar issue open describing your case, https://github.com/flutter/flutter/issues/21638.
Please follow-up in that issue for updates.

You may also check for solutions / workarounds on StackOverflow as it seems to be an implementation issue rather than framework issue.
Closing this from here. If you disagree, write in comments and I'll reopen it.
Thanks.
