### ISSUE TITLE
Analyzer no longer warns about @override missing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7316]
I'm 90% sure this used to show warnings, but now the `flutter analyze` gives the following code a clean bill of health:

```dart
abstract class A {
  void test1() { }
  void test2();
}

class B extends A {
  void test1() { }
  void test2() { }
}

void main() { }
```

I would have expected two warnings, one on B.test1 and one on B.test2, both saying that `@override` was missing.

cc @pq, @danrubel

**Comment by zoechi** [comment]
The linter rule     
```
- annotate_overrides
```
is enabled?

**Comment by Hixie** [comment]
How do I determine what rules are enabled and where the rules are coming from?

**Comment by zoechi** [comment]
I don't know if there is something specific to Flutter but usually its enabled in `analysis_options`. See also https://pub.dartlang.org/packages/analyzer

**Comment by Hixie** [comment]
Ah, interesting. We have it commented out for the user code analysis options. I wonder why it doesn't always trigger for repo code, though... maybe we're picking up the wrong one sometimes?

I'm going to close this for now.

**Comment by eseidelGoogle** [comment]
FYI @danrubel (who built most recent user/repo files).
