### ISSUE TITLE
Arabic language not appear correctly (flutter-web)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#73165]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31797198/103400159-c171f200-4b4c-11eb-97b9-45b1218f5d52.gif)

**Expected results:** 
arabic language
**Actual results:** 
another thing
<details>
  <summary>Logs</summary>

```
[ +105 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +115 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] executing: [C:\flutter\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +94 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[        ] 1.25.0-8.1.pre
[  +58 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +64 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +127 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +97 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +85 ms] executing: C:\flutter\sdk\platform-tools\adb.exe devices -l
[  +73 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +252 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +251 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +156 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ +184 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +171 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +159 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +143 ms] Multiple devices found:
[  +60 ms] Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
[ +110 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66
[ +150 ms] [0]: Chrome (chrome)
[ +137 ms] [1]: Edge (edge)
[ +144 ms] Please choose one (To quit, press "q/Q")
[ +137 ms] : 
[+25775 ms] q
[  +34 ms] "flutter run" took 28,076ms.
[ +172 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:306:7)
                    <asynchronous suspension>
                    #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:294:37)
                    <asynchronous suspension>
                    #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1170:28)
                    <asynchronous suspension>
                    #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:433:15)
                    <asynchronous suspension>
                    #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1091:5)
                    <asynchronous suspension>
                    #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
                    <asynchronous suspension>
                    #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
                    <asynchronous suspension>
                    #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9) 
                    <asynchronous suspension>
                    #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
                    <asynchronous suspension>
                    #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
                    <asynchronous suspension>
                    #15     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
                    <asynchronous suspension>
                    #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #18     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
                    <asynchronous suspension>
                    #19     main (package:flutter_tools/executable.dart:88:3)
                    <asynchronous suspension>


[+2886 ms] ensureAnalyticsSent: 262ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
info - Avoid empty statements - lib\pages\department\department_page.dart:74:13 - empty_statements
   info - Dead code - lib\pages\department\department_page.dart:74:13 - dead_code

2 issues found. (ran in 2.9s)
```

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\flutter\flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\flutter\sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\Program Files\Java\jdk-11.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @mahmoudsalah37 
Are you using canvaskit? Here I experienced a similar issue https://github.com/flutter/flutter/issues/69396#issuecomment-720360735

Can you please provide your `flutter run  -d chrome --verbose`(if using html) or `flutter run  -d chrome  --dart-define=FLUTTER_WEB_USE_SKIA=true --verbose` (if using canvaskit)  and a complete reproducible minimal code sample


Thank you

**Comment by mahmoudsalah37** [comment]
[ +105 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +116 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] executing: [C:\flutter\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[ +115 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] 1.25.0-8.1.pre
[  +92 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +68 ms] Exit code 0 from: git ls-remote --get-url origin
[  +28 ms] https://github.com/flutter/flutter.git
[ +124 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[ +108 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +69 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +30 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +40 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +87 ms] executing: C:\flutter\sdk\platform-tools\adb.exe devices -l
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +111 ms] executing: C:\flutter\sdk\platform-tools\adb.exe devices -l
[  +24 ms] Skipping pub get: version match.
[ +141 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[ +191 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[   +8 ms] Generating C:\Users\Mahmoud salah
eldin\Desktop\test1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +125 ms] List of devices attached
[  +75 ms] Launching lib\main.dart on Chrome in debug mode...
[  +25 ms] List of devices attached
[ +191 ms] Updating assets
[ +161 ms] Waiting for connection from debug service on Chrome...
[  +76 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[  +55 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[  +76 ms] <- reset
[  +13 ms] C:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata --output-dill
C:\Users\MAHMOU~1\AppData\Local\Temp\flutter_tools.a76899fa\flutter_tool.19700b2b\app.dill --libraries-spec
file:///C:/flutter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\Mahmoud salah
eldin\Desktop\test1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root C:\Users\MAHMOU~1\AppData\Local\Temp\flutter_tools.a76899fa\flutter_tools.ce77c0cb    
--filesystem-scheme org-dartlang-app --initialize-from-dill build\fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill        
--platform file:///C:/flutter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +34 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+25073 ms] Waiting for connection from debug service on Chrome... (completed in 25.3s)
[   +2 ms] Synced 28.6MB.
[   +1 ms] <- accept
[  +56 ms] Caching compiled dill
[ +372 ms] Using Opening in existing browser session.

[+2164 ms] [CHROME]:
[   +5 ms] [CHROME]:DevTools listening on ws://127.0.0.1:8498/devtools/browser/035aea29-0387-4678-a5b8-45e001dd65b8
[ +570 ms] DwdsInjector: Received request for entrypoint at http://localhost:8402/main_module.bootstrap.js
[   +9 ms] MetadataProvider: Loading debug metadata...
[  +37 ms] MetadataProvider: Loaded debug metadata
[  +30 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:8402/main_module.bootstrap.js
[+7514 ms] DevHandler: Debug service listening on ws://127.0.0.1:8551/LREkaMNGJ84=/ws

[  +13 ms] Debug service listening on ws://127.0.0.1:8551/LREkaMNGJ84=/ws
[  +28 ms] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +5 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".

**Comment by mahmoudsalah37** [comment]
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --verbose`

![2](https://user-images.githubusercontent.com/31797198/103434707-c77bd780-4c0d-11eb-8053-d40c5bb00728.png)

[  +98 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +106 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] executing: [C:\flutter\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[ +110 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] 1.25.0-8.1.pre
[  +61 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +99 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[  +26 ms] https://github.com/flutter/flutter.git
[ +127 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[ +108 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +62 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +56 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +41 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +85 ms] executing: C:\flutter\sdk\platform-tools\adb.exe devices -l
[  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +45 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +105 ms] executing: C:\flutter\sdk\platform-tools\adb.exe devices -l
[  +45 ms] Skipping pub get: version match.
[ +135 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[ +180 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[   +8 ms] Generating C:\Users\Mahmoud salah
eldin\Desktop\test1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +154 ms] List of devices attached
[  +81 ms] Launching lib\main.dart on Chrome in debug mode...
[  +49 ms] List of devices attached
[ +129 ms] Updating assets
[ +151 ms] Waiting for connection from debug service on Chrome...
[  +63 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[  +52 ms] Found plugin integration_test at C:\flutter\flutter\packages\integration_test\
[  +65 ms] <- reset
[  +13 ms] C:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_USE_SKIA=true --output-dill
C:\Users\MAHMOU~1\AppData\Local\Temp\flutter_tools.4b2e648c\flutter_tool.f3f9c1b1\app.dill --libraries-spec
file:///C:/flutter/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\Mahmoud salah
eldin\Desktop\test1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root C:\Users\MAHMOU~1\AppData\Local\Temp\flutter_tools.4b2e648c\flutter_tools.b68eb5cd    
--filesystem-scheme org-dartlang-app --initialize-from-dill build\3b22c16eb48c043f81099103590514a0.cache.dill.track.dill        
--platform file:///C:/flutter/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[ +114 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23533 ms] Waiting for connection from debug service on Chrome... (completed in 23.8s)
[   +1 ms] Synced 28.6MB.
[  +37 ms] <- accept
[   +1 ms] Caching compiled dill
[ +299 ms] Using Opening in existing browser session.

[+6603 ms] [CHROME]:
[   +7 ms] [CHROME]:DevTools listening on ws://127.0.0.1:9226/devtools/browser/8daec1b9-0c55-4750-b3d4-3b8ec55c1c99
[ +412 ms] DwdsInjector: Received request for entrypoint at http://localhost:9124/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +35 ms] MetadataProvider: Loaded debug metadata
[  +29 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:9124/main_module.bootstrap.js
[+7192 ms] DevHandler: Debug service listening on ws://127.0.0.1:9270/_J5p9jSpNy4=/ws

[  +10 ms] Debug service listening on ws://127.0.0.1:9270/_J5p9jSpNy4=/ws
[  +35 ms] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[ +113 ms] For a more detailed help message, press "h". To quit, press "q".
[+47422 ms] DevHandler: Stopped debug service on ws://127.0.0.1:9268

[+15006 ms] Application finished.
[   +6 ms] "flutter run" took 102,605ms.
[ +288 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[  +31 ms] Shutdown hook priority 4
[ +224 ms] Shutdown hooks complete
[   +3 ms] exiting with code 0

**Comment by mahmoudsalah37** [comment]
minimal code sample:
[test1.zip](https://github.com/flutter/flutter/files/5758682/test1.zip)

**Comment by TahaTesser** [comment]
Hi @mahmoudsalah37 
Thanks for the details, looks like it only reproduces in canvaskit as mentioned in https://github.com/flutter/flutter/issues/69396#issuecomment-722698952, it is being worked on
Thank you

**Comment by AbdoTareq** [comment]
I had this issue before 
change font family to Cairo or bahij janna solved my problem

**Comment by malik446644** [comment]
I had the same problem .. I think the browser cant read the default Arabic font of flutter app
the solution is really simple .. just change Arabic text font to anything else 
(I used google fonts flutter package to change the font)
