### ISSUE TITLE
fired up onChange TextField event when TextFieldEditing changed

### ISSUE THREAD

**Issue by MohammadMobasher** [flutter/flutter#73178]
hi
i have a text field and i want call/fired up the onchange event, when set text or value for the TextEditingController,
how can o do that? for example this code :
```
StreamBuilder(
                      stream: this._saveSessionLogic.startTime,
                      builder: (context, snapshot){
                                            return TextField(
                                                                  onchanged: this._saveSessionLogic.startTime,
                                                                  controller: this.startTimeController,
                                                                  .
                                                                  .
                                                                  .
                                            );})
                                             

```
now, i use this code to set init value for textfield:
`this.startTimeController.text = "test value" `
but the onChange event not fired.
how can i handle this ?
tanks :)

**Comment by iapicca** [comment]
@MohammadMobasher 
[TextField](https://api.flutter.dev/flutter/material/TextField-class.html)'s [onChanged](https://api.flutter.dev/flutter/material/TextField/onChanged.html)
seems to work just fine

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: TextField(
              onChanged: (s) => print(s),
            ),
          ),
        ),
      ),
    );

```

the issue you are experiencing might depend from your implementation,
if you need assistance with you code please follow the link `I want help writing my application` in the [new issue choice](https://github.com/flutter/flutter/issues/new/choose)

if you believe this is a bug with flutter, please provide a **complete** minimal reproducible code sample

**Comment by MohammadMobasher** [comment]
tanks. i created an issue and explained it ...

**Comment by MohammadMobasher** [comment]
yes, it's work fine, but when set default value (set value on TextEditingController) this event not called

**Comment by iapicca** [comment]
> yes, it's work fine, but when set default value (set value on TextEditingController) this event not called

it seems to work

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: TextField(
              controller:  TextEditingController()..text = 'hello',
              onChanged: (s) => print(s),
            ),
          ),
        ),
      ),
    );
```
if the code sample isn't representative can you provide a complete minimal reproducible code sample

**Comment by AbhideepChakravarty** [comment]
TextField behaves super weird in Android Web. Its methods gets triggered just by touching the field. And on Android Web ENTER button does not work for TextField, causing #72710

**Comment by darshankawar** [comment]
@MohammadMobasher 
Check [this](https://github.com/flutter/flutter/issues/73178#issuecomment-753380449) comment and confirm if it resolves your issue. 
If not, provide a complete minimal reproducible code sample as requested that shows the issue per your comment https://github.com/flutter/flutter/issues/73178#issuecomment-753378320

**Comment by MohammadMobasher** [comment]
no it's not work. when you set default value with controller, onChange not call 
onChange based you'r documents just call when user add some input (input text ...)

**Comment by darshankawar** [comment]
@MohammadMobasher 
Provide a complete minimal reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by iapicca** [comment]
> no it's not work. when you set default value with controller, onChange not call
> onChange based you'r documents just call when user add some input (input text ...)

@MohammadMobasher 
if your expectation is that setting `text` from [TextEditingController](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html) would trigger [TextField](https://api.flutter.dev/flutter/material/TextField-class.html)'s  [onChanged](onChanged) , 

>> ` TextEditingController()..text = 'hello',`

I'm afraid you are gonna be disappointed as it can be triggered only by the `user`, please see the docs
> Called when the **_user_** initiates a change to the TextField's value: when they have inserted or deleted text.

**Comment by MohammadMobasher** [comment]
@iapicca 
yes, that's it, i want this. why onChange not called? some times we need this feature

**Comment by iapicca** [comment]
> @iapicca
> yes, that's it, i want this. why onChange not called? some times we need this feature

@MohammadMobasher 
I'm confused, it seemed to me that you where describing a bug,
if this is a feature request please provide the information requested in the form

```console

## Use case

<!--
     Please tell us the problem you are running into that led to you wanting
     a new feature.

     Is your feature request related to a problem? Please give a clear and
     concise description of what the problem is.

     Describe the alternative solutions you've considered. Is there a package
     on pub.dev/flutter that already solves this?
-->

## Proposal

<!--
     Briefly but precisely describe what you would like Flutter to be able to do.

     Consider attaching images showing what you are imagining.

     Does this have to be provided by Flutter directly, or can it be provided
     by a package on pub.dev/flutter? If so, maybe consider implementing and
     publishing such a package rather than filing a bug.
-->

```

at the moment I fail to imagine any desirable use case

**Comment by MohammadMobasher** [comment]
sorry my fault, i think this is an error nut when i read you'r doc ...
this is a good item if you can set this.
tanks

**Comment by darshankawar** [comment]
@MohammadMobasher 
Please elaborate on the issue / feature request you would like to see in the format mentioned above. https://github.com/flutter/flutter/issues/73178#issuecomment-754859864

**Comment by AbhideepChakravarty** [comment]
You implement any kind of TextField, it does not work after one or two executions. Just touching the field, refreshes the whole page. The code you asked to refer can be taken as minimum reproducible code and just run it on flutter web and deploy on some place and use it on Android device. It will not work.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
