### ISSUE TITLE
When I Run Command Flutter doctor I got the Error

### ISSUE THREAD

**Issue by Araw830** [flutter/flutter#73175]
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.

After Installing Flutter and Dart Plugin in Android Studio, I Got The Same Error......

**Comment by justkawal** [comment]
Follow https://flutter.dev for installation.

If you are on Mac then use Home-brew to install dart-sdk.

**Comment by iapicca** [comment]
@Araw830 
can you please provide your full `flutter doctor -v`

are you on linux and using snapcraft?

**Comment by darshankawar** [comment]
@Araw830 
Try [this](https://github.com/flutter/flutter/issues/68429#issuecomment-740430602) solution and see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
