### ISSUE TITLE
AssetImage fails with flutter versions starting about 1.5 months ago...

### ISSUE THREAD

**Issue by jsnydersss** [flutter/flutter#73173]
About 1.5 months ago I updated/upgraded to the latest flutter and continued doing that. Ever since 1.5 months ago I have been getting this exception in my Flutter Web app.

The following _Exception was thrown resolving an image codec:
Exception: Failed to decode image

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
lib/_engine/engine/canvaskit/image.dart 53:7                                  createDefault
lib/_engine/engine/canvaskit/skia_object_cache.dart 141:41                    new
lib/_engine/engine/canvaskit/image.dart 45:3                                  decodeFromBytes
lib/_engine/engine/canvaskit/image.dart 11:26                                 skiaInstantiateImageCodec
...
Image provider: AssetImage(bundle: null, name: "screen_captures/flutter_result-final-02-mini.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#9270d(), name: "screen_captures/PaxHeader/flutter_result-final-02-mini.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
Exception: Failed to decode image
════════════════════════════════════════════════════════════════════════════════
 Before 1.5 months ago, this code was working fine. This is a Flutter Web (only) application. 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!

Here are examples of working/non-working images:
http://snydersoftwaresolutions.com/flutter-issue/does_not_work_1.png
http://snydersoftwaresolutions.com/flutter-issue/works_1.png
http://snydersoftwaresolutions.com/flutter-issue/works_2.png

The code that executes the AssetImage was working all along up until the 1.5 months ago.

static AssetImage loadAssetImage(String filename) {
    return AssetImage('screen_captures/$filename.png');
  }

**Comment by iapicca** [comment]
```bash
> The following _Exception was thrown resolving an image codec:
> Exception: Failed to decode image
> 
> When the exception was thrown, this was the stack
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49 throw_
> lib/_engine/engine/canvaskit/image.dart 53:7 createDefault
> lib/_engine/engine/canvaskit/skia_object_cache.dart 141:41 new
> lib/_engine/engine/canvaskit/image.dart 45:3 decodeFromBytes
> lib/_engine/engine/canvaskit/image.dart 11:26 skiaInstantiateImageCodec
> ...

@jsnydersss 
from the logs seems that you are using [skia](https://flutter.dev/docs/development/tools/web-renderers#command-line-options),
can you please provide the output of `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true` 
and a minimal reproducible code sample

**Comment by darshankawar** [comment]
@jsnydersss 
Please provide above requested details to better address your issue.
Thanks.

**Comment by jsnydersss** [comment]
I am working on that now. Thank you @darshankawar and @iapicca

**Comment by jsnydersss** [comment]
@iapicca Per your request above, here is the stack trace:

For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Failed to decode image

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
lib/_engine/engine/canvaskit/image.dart 53:7                                  createDefault
lib/_engine/engine/canvaskit/skia_object_cache.dart 141:41                    new
lib/_engine/engine/canvaskit/image.dart 45:3                                  decodeFromBytes
lib/_engine/engine/canvaskit/image.dart 11:26                                 skiaInstantiateImageCodec
lib/ui/src/ui/painting.dart 458:12                                            instantiateImageCodec
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:12           _async
lib/ui/src/ui/painting.dart 450:36                                            instantiateImageCodec
packages/flutter/src/painting/binding.dart 97:12                              instantiateImageCodec
packages/flutter/src/painting/image_provider.dart 685:24                      _loadAsync
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1194:47                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1097:19                                          runUnary
dart-sdk/lib/async/future_impl.dart 150:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 703:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 732:32                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 536:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 574:7                                     <fn>
dart-sdk/lib/async/zone.dart 1186:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1090:19                                          run
dart-sdk/lib/async/zone.dart 994:7                                            runGuarded
dart-sdk/lib/async/zone.dart 1034:23                                          callback
dart-sdk/lib/async/schedule_microtask.dart 41:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 50:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

Image provider: AssetImage(bundle: null, name:
  "screen_captures/flutter_result-golfpt_website-final-16.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a206b(), name:
  "screen_captures/PaxHeader/flutter_result-golfpt_website-final-16.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Exception: Failed to decode image
Another exception was thrown: Exception: Failed to decode image
Another exception was thrown: Exception: Failed to decode image
Another exception was thrown: Exception: Failed to decode image
Another exception was thrown: Exception: Failed to decode image

**Comment by jsnydersss** [comment]
@iapicca @darshankawar A helloworld web is here:

http://snydersoftwaresolutions.com/flutter-issue/image_error.tar.gz

**Comment by darshankawar** [comment]
@jsnydersss 
The link you shared earlier isn't working. Please provide a complete minimal reproducible code sample that we can copy paste and run to see the issue.
Thanks.

**Comment by iapicca** [comment]
@jsnydersss 
ignoring some approaches that I don't recall being considered "best practice"
there are 2 errors in your code:

-  in your [sample](http://snydersoftwaresolutions.com/flutter-issue/image_error.tar.gz)'s `pubspec.yaml`

```yaml
  assets:
    - screen_captures/flutter_result-final-03-mini.png
    - screen_captures/flutter_result-final-02-mini.png
    - screen_captures/flutter_result-final-01-mini.png
    - screen_captures/download-play-store-icon.png
    - screen_captures/download-app-store-icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

```

you forgot to import some files

```yaml
    - screen_captures/flutter_result-final-07-mini.png
    - screen_captures/flutter_result-final-06-mini.png
    - screen_captures/flutter_result-final-05-mini.png
    - screen_captures/flutter_result-final-04-mini.png
```

- your page is overflowing

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/103620072-89e3bb00-4f3b-11eb-8879-40223a8c9f09.png)

</details>

if you update your pubspec.yaml and replace the code in your `main.dart` with the following
everything works just fine

```dart
import 'package:flutter/material.dart';

const _assets = <AssetImage>[
  AssetImage('screen_captures/download-app-store-icon.png'),
  AssetImage('screen_captures/flutter_result-final-01-mini.png'),
  AssetImage('screen_captures/flutter_result-final-02-mini.png'),
  AssetImage('screen_captures/flutter_result-final-03-mini.png'),
  AssetImage('screen_captures/flutter_result-final-04-mini.png'),
  AssetImage('screen_captures/flutter_result-final-05-mini.png'),
  AssetImage('screen_captures/flutter_result-final-06-mini.png'),
  AssetImage('screen_captures/flutter_result-final-07-mini.png'),
  AssetImage('screen_captures/download-play-store-icon.png'),
];

void main() {
  runApp(
    MaterialApp(
      home: Material(
        child: PageView.builder(
          itemCount: _assets.length,
          scrollDirection: Axis.horizontal,
          itemBuilder: (context, index) =>
              Center(child: Image(image: _assets[index])),
        ),
      ),
    ),
  );
}

```

I recommend to close this issue

**Comment by darshankawar** [comment]
Adding the missing images solves your issue @jsnydersss.

<img width="340" alt="Screenshot 2021-01-05 at 3 49 34 PM" src="https://user-images.githubusercontent.com/67046386/103634942-cf20e080-4f6d-11eb-8c3a-a1c013f83707.png">

Closing this as non-issue.

**Comment by jsnydersss** [comment]
@darshankawar @iapicca 

Thanks for the information and your time on this issue. Some more clarification:

I have 2 websites written in flutter that do not have the problem because they were written with the flutter version 2 months ago: 

https://golfpt.app
https://betterthanflashcards.app

In their implementations I don't use anywhere near the code that you put above (nor really what I provided as a helloworld program that reproduces the issue). During other coding, I've received that overflow yellow/black banner but never for this issue nor before the flutter upgrade 1.5 months ago. Unfortunately this issue needs to be re-opened.

I've adjusted my code and re-uploaded it here to use SingleChildScrollView (which better aligns with my websites)
http://snydersoftwaresolutions.com/flutter-issue/image_error2.tar.gz

This new code, when debugging from VSCode, produces this stacktrace:

Connecting to VM Service at ws://127.0.0.1:53822/2Jx9qS7_rIc=/ws
Error while trying to load an asset: Failed to load asset at "assets/screen_captures/flutter_result-final-04-mini.png" (404)

════════ Exception caught by image resource service ════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: screen_captures/flutter_result-final-04-mini.png

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
packages/flutter/src/services/asset_bundle.dart 227:55                        load
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1194:47                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1097:19                                          runUnary
...
Image provider: AssetImage(bundle: null, name: "screen_captures/flutter_result-final-04-mini.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#629da(), name: "screen_captures/flutter_result-final-04-mini.png", scale: 1)

When it is run w/ the "flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true", it produces this stacktrace:

Error while trying to load an asset: Failed to load asset at
"assets/screen_captures/flutter_result-final-04-mini.png" (404)
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: screen_captures/flutter_result-final-04-mini.png

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
packages/flutter/src/services/asset_bundle.dart 227:55                        load
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1194:47                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1097:19                                          runUnary
dart-sdk/lib/async/future_impl.dart 150:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 703:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 732:32                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 536:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 574:7                                     <fn>
dart-sdk/lib/async/zone.dart 1186:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1090:19                                          run
dart-sdk/lib/async/zone.dart 994:7                                            runGuarded
dart-sdk/lib/async/zone.dart 1034:23                                          callback
dart-sdk/lib/async/schedule_microtask.dart 41:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 50:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

Image provider: AssetImage(bundle: null, name: "screen_captures/flutter_result-final-04-mini.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#378f2(), name:
  "screen_captures/flutter_result-final-04-mini.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
