### ISSUE TITLE
Zooming performance issue on Raster thread

### ISSUE THREAD

**Issue by jaween** [flutter/flutter#73185]
## Details

https://user-images.githubusercontent.com/5057145/103440136-1586ee80-4c93-11eb-9848-2da9fa557097.mp4

1. Run the sample code

2. Zoom in to reach the maximum zoom level.

3. Repeatedly zoom out and then back in.

4. Notice the large amount of work that happens on the Raster thread sometimes.

Note: The performance issue doesn't seem very noticeable in this small example (besides the tall bars in the performance overlay), however in my app this does appear to cause significant jank.

Sample code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Resize(),
      ),
    ),
  );
}

class Resize extends StatefulWidget {
  @override
  _ResizeState createState() => _ResizeState();
}

class _ResizeState extends State<Resize> {
  double startScale = 1;
  double scale = 1;
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Center(
          child: Transform.scale(
            scale: scale,
            child: SizedBox(
              width: 200,
              height: 200,
              child: Image.asset('assets/flowers.jpg'),
            ),
          ),
        ),
        Positioned.fill(
          child: GestureDetector(
            onScaleStart: (_) {
              setState(() => startScale = scale);
            },
            onScaleUpdate: (details) {
              setState(
                  () => scale = (startScale * details.scale).clamp(1.0, 10.0));
            },
          ),
        ),
      ],
    );
  }
}
```

**Target Platform:** Android
**Target OS version:** Observed on Android 8 and 10
**Devices:** Samsung Galaxy A5 (2017), Google Pixel

## Logs

<details>
<summary>Logs</summary>

[dart_devtools_2021_1_2-1609508999381000.txt](https://github.com/flutter/flutter/files/5759027/dart_devtools_2021_1_2-1609508999381000.txt)

[Flowers asset image](https://user-images.githubusercontent.com/5057145/103440280-018fbc80-4c94-11eb-86cf-f7712284dd32.jpg)

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.26.0-2.0.pre.167 at /opt/flutter
    • Framework revision d3a2259541 (18 hours ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/jaween/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0
    • cmake version 3.19.1
    • ninja version 1.10.1
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • SM A520F (mobile) • 5200676a4a815579 • android-arm64  • Android 8.0.0 (API
      26)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      87.0.4280.66

• No issues found!
```

</details>

**Comment by iapicca** [comment]
@jaween 
it might be lack of optimization rather than a bug with flutter
(as a matter of fact you are rebuilding the whole stack!)

please try this [code sample](https://dartpad.dartlang.org/e8dc69a7351bb3b942d23978131854c4?)
it doesn't have the same performance issue as you can see in this [screen recording](https://user-images.githubusercontent.com/45637986/103444242-80263300-4c6f-11eb-82f0-7889e0cc258c.mp4)

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.167 at /home/francesco/snap/flutter/common/flutter
    • Framework revision d3a2259541 (22 hours ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

**Comment by jaween** [comment]
Thank you for your reply @iapicca , your code sample does indeed appear to reduce the issue significantly. I assumed rebuilding those few widgets in such a small example would only have a trivial impact.

I have a few quick questions that will help me figure out which optimisations make sense to apply to my app.

The optimisation of only rebuilding the _MyScaleTransformer widget via the ChangeNotifier seems to yield the most performance benefit here, I think? But does adding ValueKeys to the Stateless widgets actually change the rebuilding behaviour in this example?

Also, in general, would it be safe to put the ScaleNotifier inside the stateless MyScalableWidget? Since if the MyScalableWidget widget gets rebuilt, we would lose the scale state wouldn't we? 


See these two screenshots of the performance overlay:

Before your optimisations:
<a href="https://user-images.githubusercontent.com/5057145/103448005-2b240480-4ce3-11eb-89dd-04f01fe813f6.jpg"><img alt="Performance overlay indicating lots of raster thread usage" src="https://user-images.githubusercontent.com/5057145/103448005-2b240480-4ce3-11eb-89dd-04f01fe813f6.jpg" width="300"></a>

After your optimisations (your code sample with the network image replaced with the asset image):
<a href="https://user-images.githubusercontent.com/5057145/103448089-21e76780-4ce4-11eb-854a-be1224a248ca.jpg"><img alt="Performance overlay indicating less raster thread usage" src="https://user-images.githubusercontent.com/5057145/103448089-21e76780-4ce4-11eb-854a-be1224a248ca.jpg" width="300"></a>

There's still the occasional spike, I'm not sure if this is worth leaving open for the Flutter team to investigate further.

**Comment by iapicca** [comment]
> There's still the occasional spike, I'm not sure if this is worth leaving open for the Flutter team to investigate further.

@jaween 
in my opinion this is more a topic for stackoverflow or (better) [discord](https://discord.gg/N7Yshp4)
because I believe is more a question than a bug.

regardless, it's definitely a valid question and aside for pointing you at the [docs](https://flutter.dev/docs/perf/rendering/best-practices)
I'd like to give you my 2 cents on the matter:

- **keys are great**: you could probably get the same optimization in you [original code](https://github.com/flutter/flutter/issues/73185#issue-777292962) simply adding a key to each widget,
so it won't be rebuilt / removed from the tree at each set state

- **my sample code is lame**: [here](https://dartpad.dartlang.org/e8dc69a7351bb3b942d23978131854c4?) I just put something together to prove a point, 
it's definitely not production ready code, please use your favorite state management instead of my solution,
I can recommend [riverpod](https://riverpod.dev/) or [bloc](https://bloclibrary.dev/#/)
 
 - **I don't like the result**: ... shown in your _after optimization_ [screenshot](https://user-images.githubusercontent.com/5057145/103448089-21e76780-4ce4-11eb-854a-be1224a248ca.jpg), are you running it 
 with the flag `--profile` or `--release`?
 
 do as you prefer,  but I suggest to continue the conversation on stack or discord, not much the team can do about this

**Comment by jaween** [comment]
Regarding the result: All of the tests, including the *after optimization* are using `--profile`.
Now that I think about it, the device in general is a little sluggish, I don't think it's Flutter in this case.
Thank you for your answers, they make sense.
I think that's all for this issue then.
