### ISSUE TITLE
Camera permission

### ISSUE THREAD

**Issue by dmrcierhn** [flutter/flutter#73180]
When I want to take an image from the camera, it doesn't ask permission the first time. i think this is required by google. How can i do this ? thank you

**Comment by iapicca** [comment]
@dmrcierhn 
this issue doesn't seem to represent a bug with flutter or a feature request,
please follow the link `I want help writing my application` in the [new issue selection](https://github.com/flutter/flutter/issues/new/choose)

I recommend this issue to be closed

**Comment by darshankawar** [comment]
Closing this as non-issue. @dmrcierhn please follow the link mentioned in above comment to get help on your question.
Thanks.
