### ISSUE TITLE
Flutter doctor not detecting Flutter and Dart plugin installation

### ISSUE THREAD

**Issue by tulioveneno** [flutter/flutter#73199]
I am trying to install Flutter, but even after installing the plugins on Android Studio, Flutter Doctor does not recognize that they are installed. I've tried to reinstall, but still don't recognize it. I'm using the latest stable version of Flutter Android Studio 4.1.1.

Here my log:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.19041.685], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

Here the plugins installed:
![image](https://user-images.githubusercontent.com/76860090/103451100-94355900-4c9e-11eb-94ee-266bdc61ad9e.png)

**Comment by ATLANT1S** [comment]
Its issue with Android Studio 4.1.
Just switch your flutter channel to dev and upgrade flutter.
```
flutter channel dev
flutter upgrade
```

**Comment by pedromassangocode** [comment]
Hi @tulioveneno 
As said above, it is just a warning and it does not stops you from using Flutter. This is a known issue since Android Studio 4.1 and it was eventually fixed.

Thank you

**Comment by datvimaru50** [comment]
You still can run flutter app but you will fail to open DevTools to debug your app!
