### ISSUE TITLE
How to fix flutter lib/main.dart errors

### ISSUE THREAD

**Issue by hocinebegache** [flutter/flutter#73191]
Hello i am new to flutter, when i run the app on android studio I get the following errors, anyone please know how to fix them?
```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
lib/main.dart:7:37: Error: Can't find '}' to match '{'.
class MyApp extends StatelessWidget {
                                    ^
lib/main.dart:33:1: Error: Classes can't be declared inside other classes.
Try moving the class to the top-level.
class MyHomePage extends StatefulWidget {
^^^^^
lib/main.dart:33:18: Error: Expected a class member, but got 'extends'.
class MyHomePage extends StatefulWidget {
                 ^^^^^^^
lib/main.dart:33:26: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
class MyHomePage extends StatefulWidget {
                         ^^^^^^^^^^^^^^
lib/main.dart:51:1: Error: Classes can't be declared inside other classes.
Try moving the class to the top-level.
class _MyHomePageState extends State<MyHomePage> {
^^^^^
lib/main.dart:51:24: Error: Expected a class member, but got 'extends'.
class _MyHomePageState extends State<MyHomePage> {
                       ^^^^^^^
lib/main.dart:51:32: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
class _MyHomePageState extends State<MyHomePage> {
                               ^^^^^
lib/main.dart:29:13: Error: The method 'MyHomePage' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MyHomePage'.
      home: MyHomePage(title: 'Flutter Demo Home Page'),
            ^^^^^^^^^^
lib/main.dart:34:19: Error: Expected ',' before this.
  MyHomePage({Key key, this.title}) : super(key: key);
                  ^^^
lib/main.dart:34:35: Error: Expected ';' after this.
  MyHomePage({Key key, this.title}) : super(key: key);
                                  ^
lib/main.dart:34:37: Error: Expected an identifier, but got ':'.
  MyHomePage({Key key, this.title}) : super(key: key);
                                    ^
lib/main.dart:34:37: Error: Expected ';' after this.
  MyHomePage({Key key, this.title}) : super(key: key);
                                    ^
lib/main.dart:34:37: Error: Unexpected token ';'.
  MyHomePage({Key key, this.title}) : super(key: key);
                                    ^
lib/main.dart:34:39: Error: Can't use 'super' as an expression.
To delegate a constructor to a super constructor, put the super call as an initializer.
  MyHomePage({Key key, this.title}) : super(key: key);
                                      ^
lib/main.dart:45:16: Error: The final variable 'title' must be initialized.
Try adding an initializer ('= expression') to the declaration.
  final String title;
               ^^^^^
lib/main.dart:48:3: Error: '_MyHomePageState' isn't a type.
  _MyHomePageState createState() => _MyHomePageState();
  ^^^^^^^^^^^^^^^^
lib/main.dart:34:3: Error: The method 'MyHomePage' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'MyHomePage'.
  MyHomePage({Key key, this.title}) : super(key: key);
  ^^^^^^^^^^
lib/main.dart:34:29: Error: The getter 'title' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'title'.
  MyHomePage({Key key, this.title}) : super(key: key);
                            ^^^^^
lib/main.dart:48:37: Error: The method '_MyHomePageState' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named '_MyHomePageState'.
  _MyHomePageState createState() => _MyHomePageState();
                                    ^^^^^^^^^^^^^^^^
lib/main.dart:55:5: Error: The method 'setState' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setState'.
    setState(() {
    ^^^^^^^^
lib/main.dart:77:21: Error: The getter 'widget' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:new_app/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
        title: Text(widget.title),
                    ^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'I:\Programs\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'I:\Programs\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 24s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by jaydip-pawar** [comment]
can you provide your code it'll help us to find what's wrong in your code :-)

**Comment by hocinebegache** [comment]
> can you provide your code it'll help us to find what's wrong in your code :-)
here is the code below :

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
    
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by wzslr321** [comment]
There are a few ideas about how to fix it, but I am not sure that will work. 
1.Make sure that you have Flutter and Dart extensions installed, which may point some small mistake. 
2.Try to _Invalidate Caches / Restart_ in _FIle_ section - Right top corner of the Android studio. 
3.Check your gradle version in file /android/gradle/wrapper/gradle-wrapper.properties - `distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip` and if it is something like 5.x.x, try to change it to 6.3.

**Comment by hocinebegache** [comment]
I found a solution, the flutter and dart plugin was installed in android studio but everytime i run flutter -v i would get an error that it wasn't installed so i fixed it using the following steps

```
flutter upgrade

flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"

flutter doctor -v
    
flutter channel beta

flutter upgrade
```
then i created a new project and launched it and it worked
