### ISSUE TITLE
Chromakey support for video_player

### ISSUE THREAD

**Issue by md84419** [flutter/flutter#73193]
## Use case

As a software developer, I would like to remove the constant-colour-encoded background of videos playing in the video_player, so that the thing under the video selectively shows through on each frame of the video.

## Proposal
1. I'd like to be able to pass a Color in on a chromakey attribute of VideoPlayer(), or perhaps via controller.setChromakey(), and have those pixels in the video turned transparent in each frame of the video.

2. I'd like to be able to place the chromakeyed video over the top of any other widget including another video.  I'd like to build a Flutter app with similar functionality to this webpage: http://test.bsl.nrw/obv-client-demo/boy-test.html (but I want to use video_player, I don't want to embed web content into my app).

The webpage uses the seriously.js JavaScript library from https://github.com/brianchirls/Seriously.js/ which in turn uses WebGL.  The code is distributed under the MIT Open Source license.  The chromakey implementation is at https://github.com/brianchirls/Seriously.js/blob/master/effects/seriously.chroma.js

3. A more complete and flexible implementation would also support a similar featureset to seriously.chroma.js, including the ability to set the weight, balance, clipBlack and clipWhite properties in addition to the chromakey screen colour:
https://github.com/brianchirls/Seriously.js/wiki/Chroma-Key  One might even want to consider adding lumakey support at the same time as adding chromakey support.  Seriously.js has a lumakey implementation too, but the algorithm isn't as advanced as their chromakey implementation.

**Comment by iapicca** [comment]
@md84419 

is the feature you are describing supported in [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer) and [ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer)?

> On iOS, the backing player is AVPlayer. The supported formats vary depending on the version of iOS, AVURLAsset class has audiovisualTypes that you can query for supported av formats.
> On Android, the backing player is ExoPlayer, please refer here for list of supported formats.
> On Web, available formats depend on your users' browsers (vendor and version). Check package:video_player_web for more specific information.

[source](https://pub.dev/packages/video_player)

**Comment by md84419** [comment]
AVPlayer: Yes, using ARKit: https://stackoverflow.com/questions/49960262/chromakey-video-in-arkit

ExoPlayer: Looks like Exoplayer doesn't do this out of the box due to current limitations of the Google Android drivers.  But note that the WebGL solution I referenced paints each frame into a buffer and then processes that buffer on every frame, which could be an option for Flutter for non-DRM'd videos until Android supports this natively.

https://github.com/google/ExoPlayer/issues/7789
https://github.com/google/ExoPlayer/issues/2509

**Comment by stuartmorgan** [comment]
This kind of processing (and ARKit in general) is out of scope for `video_player`. This seems like a good opportunity for either a separate (third-party) package/plugin that preprocesses the video to make it transparent, or a dedicated plugin for doing this kind of on-the-fly composited playback.
