### ISSUE TITLE
firefox-integration-linux is flaky and causes tree closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#73198]
This test seems to fail about once a week. The logs are fairly noisy to its hard to determine the cause.

Instances in the past week or so:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Drone/1304/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Drone/1116/overview

**Comment by chinmaygarde** [comment]
Landing an unrelated commit to open the tree.

**Comment by Hixie** [comment]
cc @ferhatb

**Comment by yjbanov** [comment]
Looks like this is not a flake. It fails for me every time. I'm updating the golden: https://github.com/flutter/goldens/pull/137
