### ISSUE TITLE
Fingerprint authentication is not working in flutter

### ISSUE THREAD

**Issue by jaydip-pawar** [flutter/flutter#73192]
I have asked my full question on StackOverflow Please refer my link: https://stackoverflow.com/q/65533253/13359721

**Comment by williamgh2019** [comment]
I found these but not sure it can help.

[(https://blog.codemagic.io/flutter-local-authentication-using-biometrics/)]

[(https://pub.dev/packages/local_auth)]

**Comment by jaydip-pawar** [comment]
> I found these but not sure it can help.
> 
> https://blog.codemagic.io/flutter-local-authentication-using-biometrics
> 
> https://pub.dev/packages/local_auth

Yes, i also followed same tutorial but i am getting exceptions don't know why?
