### ISSUE TITLE
[flutter create plugin] does not show an error or warning when selecting a platform that is not enabled

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#73190]
On the shell execute 
```
 flutter create --org com.example --template=plugin --platforms=android,ios,windows,macos,linux -a kotlin -i swift hello
```
After that I only see platform folders for android, ios and macos, but not for Window and Linux

I now found out that it works after I enabled windows and linux, but at least a warning with the hint to activate the platforms first would be really helpful

I'm currently on the latest master channel

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.17, on macOS 11.1 20C69 darwin-arm, locale de-DE)
    • Flutter version 1.26.0-2.0.pre.17 at /Users/escmoteur/Entwicklung/flutter
    • Framework revision e74712c4d6 (2 weeks ago), 2020-12-15 12:48:05 -0500
    • Engine revision cca6ab654e
    • Dart version 2.12.0 (build 2.12.0-153.0.dev)
```

**Comment by SirusCodes** [comment]
I would try to work on it. I just need to show a warning before [creating template](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L225)?

**Comment by escamoteur** [comment]
I think so, you would have to check if all passed platforms are enabled

**Comment by SirusCodes** [comment]
I might try this in few days🤔

**Comment by SirusCodes** [comment]
@escamoteur these warnings should also show while making an app?
