### ISSUE TITLE
Deprecated warning is hard to understand without dates

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#73194]
I believe Flutter's deprecation warnings are way too hard to understand. For example, it usually says "deprecated after v1.22.0-12.0.pre". What does that mean? Was it deprecated last week? Last month? Last year? How urgent is this deprecation? I have no idea. It is extremely verbose.

![image](https://user-images.githubusercontent.com/351125/103446653-e192d580-4c60-11eb-89cf-910e5a66802f.png)

You may wonder, isn't it just a Google search away? The answer is no, you won't find in Google.

![image](https://user-images.githubusercontent.com/351125/103446682-29b1f800-4c61-11eb-8b66-78f7042a13da.png)

My suggestion is to include the date. Instead of `This feature was deprecated after v1.22.0-12.0.pre.`, it could be `This feature was deprecated after v1.22.0-12.0.pre on December 20, 2020` or something like that. The same thing affects the Material Fonts change; no one knows what is 'v1.13.8' or how long it's been.

**Comment by TahaTesser** [comment]
Hi @bernaferrari 
You can easily find the release date of each and every Flutter version released [here](https://github.com/flutter/flutter/releases) and [here](https://flutter.dev/docs/development/tools/sdk/releases?tab=linux).
I see no reason to add hard coded dates in the deprecated warnings
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
