### ISSUE TITLE
SingleChildScrollView doesn't set viewport dimension at right time

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#73197]
`SingleChildScrollView` sets its viewport dimension **after** laying out its children, but should probably set the viewport dimension **before** laying out the children.

https://github.com/flutter/flutter/blame/d3a22595416b2a2a98b8082c751d7c4fee9029d3/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L562

Children may use `Scrollable.of()`, obtain the related `position` and then access the viewport dimension. With the current implementation, that value will be null for children, even though it shouldn't be. Also, the value may be 1 frame behind by the child's perspective if the viewport dimension changes.

**Comment by matthew-carroll** [comment]
CC @slightfoot

**Comment by dnfield** [comment]
The problem is that it doesn't know its dimension until it lays out children. The size is set from the children, and the dimension is just taken from the size.

**Comment by matthew-carroll** [comment]
Why would the viewport size be based on the children? The viewport dimension comes from the parent, doesn't it?

**Comment by dnfield** [comment]
It gets constrained to the size of the child, if there is a child: https://github.com/flutter/flutter/blame/d3a22595416b2a2a98b8082c751d7c4fee9029d3/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L559

Presumably becasue depending on how tall or wide the child is, the viewport might shrink or grow to that size.

**Comment by matthew-carroll** [comment]
Ok. I'll close this issue, but someone might want to look into the `Scrollable` contract which may not really be honored here. Should it be the case that some `Scrollable` positions have viewport dimensions and others don't? I'm not sure a contract is particularly useful if you can't depend on it.
