### ISSUE TITLE
dialog background color is not configurable

### ISSUE THREAD

**Issue by lequem** [flutter/flutter#7320]
In the dialog.dart file, line 44 and 46, the background color is set staticly and not configurable for Dialogs, whereas in ThemeData class, we can configure everything for the application.

I propose to define the new property dialogBackgroundColor in the ThemeData class and use it in the dialog.dart file.

**Comment by lequem** [comment]
I have pulled a request to patch this but the travis task failed and I don't understand why.

**Comment by sethladd** [comment]
PR is here: https://github.com/flutter/flutter/pull/7321

**Comment by sethladd** [comment]
cc @cbracken @yjbanov does the travis failure look familiar?

**Comment by cbracken** [comment]
Travis run looks green after @abarth's re-run.

**Comment by abarth** [comment]
@cbracken Sorry, next time I'll save the log.

**Comment by FlutterIODev** [comment]
Can I set the color for a specific dialog not for all of my app dialogs?

**Comment by yjbanov** [comment]
@FlutterIODev something along these lines should do it (but I haven't tried myself):

```dart
Theme(
  data: themeDataWithCustomDialogColor,
  child: Builder(builder: (BuildContext contextWithNewTheme) {
    // some widget here will be calling `showDialog`. When it
    // does that, it should pass `contextWithNewTheme` to it,
    // e.g. `showDialog(context: contextWithNewTheme, ...);`
  }),
);
```

Having to wrap like that is a bit annoying, but I think it's consequence of https://github.com/flutter/flutter/issues/12655. Maybe @Hixie knows of a better way.
