### ISSUE TITLE
[flutter_tools] Doesn't show connected devices when ADB devices does 

### ISSUE THREAD

**Issue by chenjuyu** [flutter/flutter#73200]
## Steps to Reproduce

1. The native Java Android project can display redmi K30 5g
2. flutter doctor -v display 
 Connected device
    !
What is the reason？？？
[
![捕获](https://user-images.githubusercontent.com/39434962/103451646-9977bf80-4d01-11eb-88b5-3adc6f224c68.PNG)
](url)

<details> 
<summary>flutter doctor -v</summary> 

```bash
D:\flutter>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17763.1158], locale zh-CN)
    • Flutter version 1.22.5 at D:\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\IDEA20193
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    !

! Doctor found issues in 2 categories.
```

</details>

**Comment by JonathanImmanuelKennedy** [comment]
Have you enabled usb debugging on your phone

**Comment by chenjuyu** [comment]
> Have you enabled usb debugging on your phone
Enabled

**Comment by JonathanImmanuelKennedy** [comment]
run flutter devices to check if flutter can see if devices are detected

**Comment by chenjuyu** [comment]
> run flutter devices to check if flutter can see if devices are detected

D:\my_app\my_app>flutter devices
No devices detected.

**Comment by JonathanImmanuelKennedy** [comment]
How have you connected your phone to your computer.
Have you used a cable or some other method

**Comment by chenjuyu** [comment]
> How have you connected your phone to your computer.
> Have you used a cable or some other method

USB data line connected

**Comment by JonathanImmanuelKennedy** [comment]
<img width="1792" alt="Screenshot 2021-01-02 at 12 10 53 PM" src="https://user-images.githubusercontent.com/74782726/103452282-92e24b80-4cf3-11eb-9e64-ec5f16ddb908.png">
It should be like this . I guess there is some connectivity issue

**Comment by JonathanImmanuelKennedy** [comment]
Look at the top near main.dart

**Comment by JonathanImmanuelKennedy** [comment]
Try with an emulator.

**Comment by JonathanImmanuelKennedy** [comment]
Then if it connects properly you can try with your phone and find out what's causing the problem.

**Comment by Udit-singh** [comment]
Hey, @chenjuyu Just go to **Device Manager** on your system, connect the device with usb cable and from there **Update** your USB Driver.

**Comment by chenjuyu** [comment]
> Hey, @chenjuyu Just go to **Device Manager** on your system, connect the device with usb cable and from there **Update** your USB Driver.
![Uploading 1.PNG…]()

emulator  No devices detected.

**Comment by MrUnfunny** [comment]
Looks similar to [this](https://github.com/flutter/flutter-intellij/issues/2084). Since your android-sdk is installed in D drive, it might be some issue with path variables

**Comment by chenjuyu** [comment]
> Looks similar to [this](https://github.com/flutter/flutter-intellij/issues/2084). Since your android-sdk is installed in D drive, it might be some issue with path variables

path  flutter doctor -v  It's listed. It shouldn't be this problem,Native  Android project normal display

**Comment by MrUnfunny** [comment]
![image](https://user-images.githubusercontent.com/43833743/103454334-e9a65000-4d08-11eb-9654-bdf225f5ae1f.png)
Does this look similar to your situation? At least check the provided link to the issue. By default Android-sdk is supposed to be in c drive, however you have it in d drive, that's why i asked to check the path.

**Comment by chenjuyu** [comment]
> ![图片](https://user-images.githubusercontent.com/43833743/103454334-e9a65000-4d08-11eb-9654-bdf225f5ae1f.png)
> 这看起来与您的情况类似吗？至少检查提供的问题链接。默认情况下，Android-sdk应该位于c驱动器中，但是您在d驱动器中具有它，这就是为什么我要求检查路径的原因。

![1](https://user-images.githubusercontent.com/39434962/103454459-62180b80-4d1f-11eb-85f4-545736a42996.PNG)
![2](https://user-images.githubusercontent.com/39434962/103454462-6ba17380-4d1f-11eb-9759-55b5a18e7996.PNG)

Is there a problem with Windows environment variables

**Comment by TahaTesser** [comment]
Hi @chenjuyu 
What's your `adb devices` output?  Did you do a fresh install or this is an upgrade from the previous channel? 
Did you experience this on this machine before?
Thank you

**Comment by chenjuyu** [comment]
> Hi @chenjuyu
> What's your `adb devices` output? Did you do a fresh install or this is an upgrade from the previous channel?
> Did you experience this on this machine before?
> Thank you
adb devices output  
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
3f98c669        device

It has been installed on the computer before, but not on the mobile phone
flutter_windows_v1.12.13+hotfix.5-stable 
![1](https://user-images.githubusercontent.com/39434962/103904610-75204680-5138-11eb-892d-70b80f28dde0.PNG)

**Comment by chenjuyu** [comment]
> Hi @chenjuyu
> What's your `adb devices` output? Did you do a fresh install or this is an upgrade from the previous channel?
> Did you experience this on this machine before?
> Thank you

How long will it take to fix this problem？？

**Comment by chenjuyu** [comment]
setting solve the problem
Windows environment variable system variable path   
path setting  D:\Flutter\bin
![QQ图片20210131113511](https://user-images.githubusercontent.com/39434962/106373870-c2e74200-63b8-11eb-8520-86c997fa3114.png)
