### ISSUE TITLE
[web] flutter_service_worker.js routine downloadOffline is broken

### ISSUE THREAD

**Issue by bradchristie** [flutter/flutter#73213]
To reproduce:
1.  Start a new project with web support
2.  Replace the script in index.html with this code

`    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js')
        .then((reg) => {
             navigator.serviceWorker.controller.postMessage('downloadOffline');
        });
      });
    }`

3.  Build the web project
4. Access build/web/index.html through a web server, and refresh the page to get the service worker to run downloadOffline.
5. Look at the network log in the browser.  Instead of loading real resource files, the service worker attempts to download files named "0" through "14".

I have uploaded the result of steps 1-3 to my web site at https://www.bradchristie.com/sample_web_project/

The bug is one line in downloadOffline,

`  for (var resourceKey in Object.keys(RESOURCES)) {`

should be

`  for (var resourceKey of Object.keys(RESOURCES)) {`

**Comment by darshankawar** [comment]
@bradchristie 
Please provide `flutter doctor -v`.

**Comment by bradchristie** [comment]
For development I'm using beta 1.24 because of #72627, I also checked the current beta 1.25 and the issue is there as well.

`  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.24.0-10.2.pre at P:\flutter
    • Framework revision 022b333a08 (7 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at p:\programs\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = p:\programs\AndroidSDK
    • ANDROID_SDK_ROOT = p:\programs\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] Connected device (5 available)
    • SM T580 (mobile)                   • 520010335ba39425 • android-arm    • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Web Server (web)                   • web-server       • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                         • edge             • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!`

**Comment by darshankawar** [comment]
<img width="463" alt="Screenshot 2021-01-05 at 12 40 00 PM" src="https://user-images.githubusercontent.com/67046386/103616894-44cb8300-4f53-11eb-814e-e30ed18050c0.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!



```

</details>

**Comment by MrBirb** [comment]
@ferhatb PR landed. Close this?
