### ISSUE TITLE
Flutter test directly on your mobile phone

### ISSUE THREAD

**Issue by rodnic28** [flutter/flutter#73217]
I would like to test my app developed in Flutter / Android Studios directly on my mobile phone. How do I save the new app on my phone?

**Comment by iapicca** [comment]
@rodnic28 
this issue doesn't seem to describe a bug or a feature request,
if you need assistance please follow the link at `I want help writing my application` in the [new issue choice](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
Closing this as non-issue. @rodnic28 Your question is better suited for Stackover flow. Please follow the link mentioned above to get answer on your question.
