### ISSUE TITLE
flutter 1.22.5 has issue with Mac OS X 11.1

### ISSUE THREAD

**Issue by abcdef123ghi** [flutter/flutter#73228]
Hi flutter
   I'm really new to Mac OS X(used to be Windows user) and I tried to use flutter on a Intel based Mac books pro with Mac OSX 11.1 ,Android Stduio 4.1.1 and XCode 12.3 as well 
it's so bizzard that indicated that I installed Xcode incompeleted like 

 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.

any idea how do I resolve the problems?or I just ignore these problem?my Xcode was installed from App store though

**Comment by tuzimoe** [comment]
**flutter doctor --android-licenses**

This is the key! You need accept licence to compile the flutter Android App or if u want to compile iOS App u need Xcode and CocoaPods installed.

**Comment by abcdef123ghi** [comment]
> Android
> 
> **flutter doctor --android-licenses**
> 
> iOS
> 
> **sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
> 
> sudo xcodebuild -runFirstLaunch
> 
> sudo gem install cocoapods**
> 
> This is the key! You need accept licence to compile the flutter Android App or if u want to compile iOS App u need Xcode and CocoaPods installed.

Thank you so much
