### ISSUE TITLE
Error handling 'checkPlatformOverride' 

### ISSUE THREAD

**Issue by flutteresbolivia** [flutter/flutter#73221]
I start my application with F5, and the application runs normal, but I get some errors that make the hot reaload and hotRestart not work, any solution?

Flutter 1.22.5 version actually
Stable channel

Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked

**Comment by iapicca** [comment]
@flutteresbolivia 
please provide your complete `flutter doctor -v` and your complete `flutter run -v`

**Comment by pedromassangocode** [comment]
Hi @flutteresbolivia 
Please provide what was asked above along with the steps to reproduce the issue.

**Comment by uc-dve** [comment]
Hi, I faced same issue while started using **rate_my_app** plugin.
when i did below code for never ask for rating. then after reload this issue occur, it does not crash app but only warning. I have checked this on android device in debug mode
  ```
await rateMyApp.callEvent(RateMyAppEventType.noButtonPressed);
  Navigator.pop<RateMyAppDialogButton>(context, RateMyAppDialogButton.no);
```

**Comment by iapicca** [comment]
@uc-dve 
if you are experiencing the issue with the 3rd party plugin [rate_my_app](https://pub.dev/packages/rate_my_app)
you may want to open an issue in the dedicated [github](https://github.com/Skyost/RateMyApp/issues)
otherwise could you provide a minimal reproducible code sample without 3rd party packages

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 0biWanKenobi** [comment]
Console warnings on hot reload and restart:

```
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Restarted application in 11.487ms.
Error handling 'serviceExtension' custom request: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from ext.flutter.inspector.setPubRootDirectories()
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
```


Flutter doctor:

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Versione 10.0.19041.804], locale it-IT)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Thetis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Thetis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

**Comment by iapicca** [comment]
@0biWanKenobi 

> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by 0biWanKenobi** [comment]
I have told you what happens: those warnings appear in console on app hot reload and/or restart. I have also appended the verbose output from flutter doctor. ATM I don't have any logs to provide, I had already stopped the app when I stumbled on this github issue. If it happens again, I'll try to provide logs too. I thought contributing something was better than nothing.

**Comment by iapicca** [comment]
@0biWanKenobi 
was closed as not reproducible and it isn't currently worked on,
the partial logs you provided are appreciated, but don't make the issue workable,

>  If it happens again, I'll try to provide logs too.

thank you in advance,
doing so, please open a `new issue` your `flutter doctor -v`, your complete  `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by kamleshwebtech** [comment]
I am still facing this issue, my code is as: 

```
import 'package:flutter/material.dart';
import 'package:contacts_service/contacts_service.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Contact> contacts;

  @override
  void initState() {
    super.initState();
    fetchContacts();
  }

  fetchContacts() async {
    // Get all contacts on device
    await ContactsService.getContacts().then((value) {
      contacts = value;
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test contact service'),
      ),
      body: Container(
        child: ListView.builder(
            itemCount: contacts.length,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text(contacts[index].displayName),
              );
            }),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

Getting error in console:

Error handling 'checkPlatformOverride' custom request: ext.flutter.platformOverride: (-32000) Bad state: The client closed with pending request "ext.flutter.platformOverride".
Error handling 'checkBrightnessOverride' custom request: ext.flutter.brightnessOverride: (-32000) Bad state: The client closed with pending request "ext.flutter.brightnessOverride".
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Bad state: The client closed with pending request "ext.flutter.inspector.setPubRootDirectories".
Error handling 'checkIsWidgetCreationTracked' custom request: ext.flutter.inspector.isWidgetCreationTracked: (-32000) Bad state: The client closed with pending request "ext.flutter.inspector.isWidgetCreationTracked".

Please check and suggest, what is the issue and how can we fix it. Thanks a lot.

**Comment by iapicca** [comment]
@kamleshwebtech 
please open a `new issue` providing your `flutter doctor -v`, your complete  `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_** like [contacts_service](https://pub.dev/packages/contacts_service)

**Comment by fasil712** [comment]
please provide your complete **flutter doctor -v** and your complete **flutter run -v**. by this command solve my problems.
