### ISSUE TITLE
[url_launcher] on iPhone with Firefox canLaunch returns false, but launch works

### ISSUE THREAD

**Issue by abs0** [flutter/flutter#73224]
On an iPhone (seen on iPhone 6s running 4.2 and iPhone 12), if Firefox is installed and set to the default browser, then canLaunch() returns false for an https:// URL, but launch() for that URL works

Sample URL was of the form:

https://beta.trainasone.com/goals?webSessionToken=75e36457fed54d079ce48ac8c3b50173

**Comment by iapicca** [comment]
@abs0 
can you provide your `flutter doctor -v`,
are there any errors in the logs running the app with `flutter run --release -v`?

**Comment by TahaTesser** [comment]
Hi @abs0 
Please add [this](https://github.com/flutter/flutter/issues/65936#issuecomment-720954413) in your info.plist to fix this.
There is an open[ PR](https://github.com/flutter/plugins/pull/3252) to add this in the documentation.
Closing, as this isn't an issue with `url_launcher` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by abs0** [comment]
Thanks @TahaTesser - wfm :)
