### ISSUE TITLE
After updating to flutter beta my app is broken of null safety in string

### ISSUE THREAD

**Issue by nextcodelab** [flutter/flutter#73236]
Why all types class and instance in flutter beta cannot be null .. and need to add sign ? before in can be use?
![Screenshot 2020-12-31 183501](https://user-images.githubusercontent.com/73583588/103477666-040d2600-4dfc-11eb-97ad-b7ab2e77d566.png)

**Comment by nextcodelab** [comment]
Even function and string cannot be null... I cannot pass optional parameter without question mark ?

**Comment by pedromassangocode** [comment]
Hi @nextcodelab 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, the steps to reproduce the issue and a minimal complete reproducible code sample?

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by henry0510** [comment]
Aurora
                                    JS
                            
                    
                        
                            
                                    BAT
                                    1000-10086
                                    liangchengtong95@sina.com
                                    BeiJIn
                                    1000
                                    10000-888
