### ISSUE TITLE
I am facing problem with fingerprint authentication

### ISSUE THREAD

**Issue by jaydip-pawar** [flutter/flutter#73240]
I have added fingerprint unlock in my application with the help of flutter_screen_lock and local_auth
And it works fine in debug mode like when i run my app on emulator or on physical device but when i generate a release apk of my application and when fingerprint authentication appears my application crashes. I don't know why this happening because it's working in debug but not in release version of it?

**Comment by pedromassangocode** [comment]
Hi @jaydip-pawar 
Please provide your `flutter doctor -v`, logs of the crash,  the steps to reproduce the issue, and a minimal complete reproducible code sample?
Thank you

**Comment by jaydip-pawar** [comment]
> Hi @jaydip-pawar
> Please provide your `flutter doctor -v`, logs of the crash, the steps to reproduce the issue, and a minimal complete reproducible code sample?
> Thank you

I am getting following error when try to build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\nobit\AndroidStudioProjects\Production\secret_keeper\build\app\intermediates\flutter\profile\libs.jar.
         > Transform's input file does not exist: C:\Users\nobit\AndroidStudioProjects\Production\secret_keeper\build\app\intermediates\flutter\profile\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:


Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.




* Get more help at https://help.gradle.org

BUILD FAILED in 5m 40s
Running Gradle task 'assembleRelease'...                          344.9s (!)
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

so i have seen some solution of it and by using one solution that said "first create a debug apk and then create a release apk" it works for me but when try to authenticate app is crashing this problem started when i add authentication in my applicaton:

This method i am using to authenticate 
```
showLockScreen(
      context: context,
      title: "Enter vault password",
      digits: 5,
      correctString: _password,
      cancelText: "Close",
      showBiometricFirst: _isFingerprintEnabled,
      canCancel: false,
      onUnlocked: () => Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => Home())),
      canBiometric: _isFingerprintEnabled,
      biometricAuthenticate: (context) async {
        bool authenticated = false;
        try{
          authenticated = await auth.authenticateWithBiometrics(
              localizedReason: "Please authenticate",
              useErrorDialogs: true,
              stickyAuth: false,
          );
        } on PlatformException catch(e){
          print(e);
        }
        if(!mounted) return false;

        if (authenticated) {
          return true;
        }
        return false;
      },
    );
```

I have changed some content in Styles.xml and MainActivity to works:

MainActivity.kt
```
package com.pawarsproduction.secret_keeper

import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}

```

Styles.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting -->
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@android:color/white</item>
    </style>
</resources>

```

**Comment by pedromassangocode** [comment]
> I am getting following error when try to build:

Hi @jaydip-pawar this was already discussed in https://github.com/flutter/flutter/issues/73211 which was filled by yourself. Please see https://github.com/flutter/flutter/issues/73211#issuecomment-753487063 to learn how to fix it.

Please provide a minimal complete reproducible code sample that reproduces this issue along with your `pubspec.yaml`.

**Comment by jaydip-pawar** [comment]
> > I am getting following error when try to build:
> 
> Hi @jaydip-pawar this was already discussed in #73211 which was filled by yourself. Please see [#73211 (comment)](https://github.com/flutter/flutter/issues/73211#issuecomment-753487063) to learn how to fix it.
> 
> Please provide a minimal complete reproducible code sample that reproduces this issue along with your `pubspec.yaml`.

I followed all the steps and build apk successfully but application is crashing.. I found why it's happen when i open my project in android it give me a option to upgrade the plugins and i updated it that's why i am facing this issue. After that i re-opened my old project and added fingerprint authentication and it works without any error.
