### ISSUE TITLE
https://docs.flutter.io/flutter/foo/ should redirect to https://docs.flutter.io/flutter/foo/foo-library.html

### ISSUE THREAD

**Issue by danafergan** [flutter/flutter#7324]
And https://docs.flutter.io/flutter/foo/Bar/ should redirect to https://docs.flutter.io/flutter/foo/Bar-class.html

Under each library, individual class pages are all located at https://docs.flutter.io/flutter/foo/Bar-class.html and properties/constructors/objects/methods are all located at https://docs.flutter.io/flutter/foo/Bar/property.html 
I like to just be able to delete the individual html page from the URL to go back up a level. However, I get a Firebase Page Not Found error (since there's no 404.html) when I do this for a class or library.

## Steps to Reproduce
Visit https://docs.flutter.io/flutter/widgets/Border/dimensions.html
Decide to check out the Border class by visiting https://docs.flutter.io/flutter/widgets/Border/ , get Page Not Found error.
Try to just get back to the widget library index by visiting https://docs.flutter.io/flutter/widgets/ and find Border there... get Page Not Found again.

**Comment by sethladd** [comment]
Thanks for the suggestion. I'm not sure how to do this with Firebase Static Hosting. But maybe it's possible?

Another idea is to change how dartdoc produces HTML files.

**Comment by danafergan** [comment]
It looks like Firebase Static Hosting supports [redirects](https://firebase.google.com/docs/hosting/url-redirects-rewrites#section-redirects).

**Comment by sethladd** [comment]
Is it possible to come up with maintainable redirect rules? We might accept a patch if the rules were pretty simple.

Also, I'm trying to remember why we used `ClassName-class.html`, and I think it's because there are other top-level names. We needed a way to disambiguate top-level functions, classes, typedefs, and (others?).

**Comment by danafergan** [comment]
There are few enough libraries that you could write those redirects explicitly. 

For the class names, I don't think the destination accepts a glob pattern, so I'm not sure there's a scalable method (unless you write a script that creates a redirect rule for each class, but that seems pretty hacky...)
@jamesdaniels -- is there a good solution to this??

I think the `ClassName-class.html` pattern is to differentiate the class page from the constructor page and makes sense-- so that https://docs.flutter.io/flutter/material/Border-class.html and https://docs.flutter.io/flutter/widgets/Border/Border.html are clearly different targets.

**Comment by jamesdaniels** [comment]
Captured redirects could help achieve this, if I'm gathering what you intend to do correctly. https://firebase.google.com/docs/hosting/full-config#redirects

E.g,

```json
{
  "source": "/flutter/:foo/:bar/",
  "destination": "/flutter/:foo/:bar-class.html",
  "type": 301
}
```

**Comment by Hixie** [comment]
cc @jcollins-g since this may be something dartdocs could implement.

Moving out of m3 since this doesn't fit our current priorities.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1821](https://github.com/flutter/website/issues/1821) via [**ZenHub**](https://www.zenhub.com/)
