### ISSUE TITLE
SingleChildScrollView Rolling conflict in iOS presentViewController

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#73249]
When I add a flutterView to my native iOS app, and use presentViewController to show this flutterView, I found my SingleChildScrollView Widget can't scroll anymore.When I try to scroll this interface, it often triggers a slide back operation.Even when I disabled the iOS native sliding return property, the entire interface still can’t slide.

iOS code
```
if (@available(iOS 13.0, *)) {
                        flutterViewController.modalInPresentation = YES;
 }
[weakSelf presentViewController:flutterViewController animated:YES completion:nil];
```

Flutter code
```
    return Scaffold(
      backgroundColor: Theme.of(context).cardColor,
      body: Container(
        child: SingleChildScrollView(
          child: Column(
            children: [
             Container(
               color: Colors.blue,
               height: 300,
             ),
              Container(
                color: Colors.greenAccent,
                height: 300,
              ),
              Container(
                color: Colors.redAccent,
                height: 300,
              ),
              Container(
                color: Colors.yellow,
                height: 300,
              ),
            ],
          ),
        ),
      ),
    );
```

```
Flutter Version 1.22.4
```

Screenshot:
<img src="https://user-images.githubusercontent.com/32046282/103494148-4cfec200-4e70-11eb-8d5b-b3e7e932b117.png" width="250" height="550" />

**Comment by TahaTesser** [comment]
Hi @tongyangsheng 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample in a GitHub repo including module and iOS app
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
