### ISSUE TITLE
Can not found CocoaPods

### ISSUE THREAD

**Issue by 0xfeb** [flutter/flutter#73257]
**It can not run in Visual Studio Code, when I click run, it show me error messages:** 

```bash
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

Exception: CocoaPods not installed or not in valid state.
```
 

 **I'm sure CocoaPods is all right because I run CocoaPods in terminal, like 'pod install', 'pod update', it's ok.**  

**And I have re-installed CocoaPods and still error.** 

**One more thing, I can run it in Xcode without any error message.** 

  

_Flutter doctor results:_

<details> 
<summary>flutter doctor -v</summary> 

```bash
➜  project flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/wangyuanou/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wangyuanou/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,192.168.*
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost
```

</details>

**Comment by bhtri** [comment]
I think it is necessary to clean the `Pods/` in the `ios` folder. [here](https://stackoverflow.com/a/63506237/6284714)

Then if necessary run `pod init` in the `ios/` directory and add the library (ex: pod 'SwiftLint') in the Podfile

**Comment by TahaTesser** [comment]
Hi @0xfeb 
Please try the possible solution suggested above.
Does this reproduce in VS Code? Can you also reproduce it using `flutter run --verbose > run.log` in terminal (please provide this log file) 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
