### ISSUE TITLE
no pubspec.yaml found

### ISSUE THREAD

**Issue by WhereareUmylove** [flutter/flutter#73253]
when I create a new flutter project,out log print 'no pubspec.yaml found'

**Comment by pedromassangocode** [comment]
Hi @WhereareUmylove 
Can you please provide your `flutter doctor -v` and the reproducible steps?
Thank you

**Comment by WhereareUmylove** [comment]
thankyou verymuch,I deleted the flutter SDK and downloaded a new version to solve the problem，

**Comment by pedromassangocode** [comment]
Hi @WhereareUmylove 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
