### ISSUE TITLE
Request: a landing page for "material + flutter"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7325]
We have three requirements:

* easily answer the question "does Flutter do/provide/have material [design]?"
* help users see that Flutter has-but-is-also-more-than-just material
* provide a landing page to link from material.io

Which can probably help all three requirements by building a landing page that clearly explains and shows material and its usage and status with Flutter.

Right now, material is interlaced across our site. This makes it appear that Flutter only does material. Also, we don't have a single place to link to that shows material+flutter, for the audience that knows/understands material and wants to see what Flutter has to offer.

If we had a flutter.io/material, we could:

* list the components we have implemented
* explain material's relationship with/to Flutter
* speak to designers that already know material

**Comment by Hixie** [comment]
I would be very wary of adding more docs to our site unless we make it very clear that it's not a reference page.

I think once we have demo apps that aren't material focused, it'll be easy to just add screen shots of those aside the regular screen shots and then the question answers itself.

**Comment by sethladd** [comment]
To be clear, this issue is proposing a landing page for the product of "material components for Flutter", not actually _docs_. This landing page would link out to docs.

**Comment by Hixie** [comment]
This is handled by https://material.io/develop/flutter/ now.
