### ISSUE TITLE
ld: framework not found file_picker clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by yvngaayush** [flutter/flutter#73251]
When I run the flutter app, the build fails due to this error :

ld: framework not found file_picker
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Flutter doctor output is fine and this is the error thrown. Not sure what file_picker is. 

Thank you in advance for the help!

**Comment by darshankawar** [comment]
@yvngaayush 
Provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample in formatted text that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
