### ISSUE TITLE
[camera] ISO, Shutter Speed, Aperture

### ISSUE THREAD

**Issue by resoglas** [flutter/flutter#73250]
## Proposal

Camera Plugin: https://github.com/flutter/plugins/tree/master/packages/camera

I would like for this plugin to be able to return `CaptureResult.LENS_APERTURE`, `CaptureResult.SENSOR_EXPOSURE_TIME`, `CaptureResult.SENSOR_SENSITIVITY` and possibly any other property of `CaptureResult` together with `plugins.flutter.io/camera/imageStream` `CameraImage` DTO mainly so that this metadata could be shown together with image preview and used for exposure calculations.

I am not sure about iOS but it seems https://developer.apple.com/documentation/avfoundation/avcapturedevice has all of these properties as well - `AVCaptureDevice.iso`,  `AVCaptureDevice.lensAperture`, `AVCaptureDevice.exposureDuration`.

**Comment by pedromassangocode** [comment]
For reference: https://developer.android.com/reference/kotlin/android/hardware/camera2/CaptureResult#lens_aperture

**Comment by iapicca** [comment]
it could be added to this list https://github.com/flutter/flutter/issues/31225

**Comment by BeMacized** [comment]
Support for the three properties mentioned have been added in flutter/plugins#4170. 
To prevent unnecessarily increasing the scope of the plugin, only these three were included. 
If demand is shown for more of these properties to be included, we can add them at some later point.
