### ISSUE TITLE
PageViewer changes page on hot reload

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#73274]
(I see the performance label for this issue, it's not performance related. If someone can edit, thanks)

On hot reload a page view comes back to the first page. What I'm assuming happens is that a widget calls the dispose of a PageController and the current page is lost. That state shouldn't be lost.

What I did as a workaround is to have an init method to reinitialize the PageController with the last page that was displayed before the hot reload.

```
class DrawerService {
  PageController controller = PageController();
  final List<DrawerLink> links = drawerLinks;
  int _lastIndex = 0;


  init() {
    controller = PageController(initialPage: _lastIndex);
  }

  goTo(String name) {
    final navIndex = links.indexWhere((info) => info.name == name);
    controller.animateToPage(
      navIndex,
      duration: Duration(milliseconds: 300),
      curve: Curves.ease,
    );
    _lastIndex = navIndex;
  }

  List<Widget> getPages(BuildContext context) {
    return links.map((link) => link.builder(context)).toList();
  }
}
```

And in the widget
```

class HomeScreen extends StatelessWidget {
  final DrawerService nav = GetIt.I.get<DrawerService>();

  HomeScreen() {
    nav.init();
  }

  @override
  Widget build(BuildContext context) {
    return DrawerLayout(
      // ...
      body: PageView(
        controller: nav.controller,
        children: nav.getPages(context),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@cedvdb 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue along with expected and actual behavior ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
