### ISSUE TITLE
Isolates in --debug mode exited with an error

### ISSUE THREAD

**Issue by ZhangQinglian** [flutter/flutter#7327]
## Steps to Reproduce

when I run the code below ,it throw an error ;

```dart
import 'package:flutter/material.dart';
import '_picker/picker.dart';
import 'dart:isolate';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    ReceivePort receivePort = new ReceivePort();
    receivePort.listen((data){});
    Isolate.spawn(func,receivePort.sendPort);
  }

  static void func(var message){

  }
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(config.title),
      ),
      body: new Center(
        child: new Text(
          'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}

````

## Logs

[+4016 ms] E/flutter ( 7740): [ERROR:../../flutter/runtime/dart_init.cc(125)] Isolate app.flx$func-240983148 exited with an error
[        ] E/flutter ( 7740): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unable to find library '/data/user/0/com.yourcompany.flutterWeather/cache/flutter_weatheriulcaz/lib/main.dart'.

 scott@tomato  ~/workspace/flutter_weather  flutter analyze
Analyzing 3 files...
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 51, col 21)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 53, col 16)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 50, col 23)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 46, col 24)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 44, col 19)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 45, col 19)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 52, col 21)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 48, col 22)
[hint] Unused import. (lib/_picker/china_cities.dart, line 2, col 8)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 47, col 22)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 43, col 15)
[hint] Unused import. (lib/_picker/china_cities.dart, line 3, col 8)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 54, col 16)
[lint] Avoid using braces in interpolation when not needed. (lib/_picker/china_cities.dart, line 49, col 23)
[hint] Unused import. (lib/_picker/china_cities.dart, line 1, col 8)
[hint] Unused import. (lib/main.dart, line 2, col 8)
(Ran in 8.7s)
 ✘ scott@tomato  ~/workspace/flutter_weather  

## Flutter Doctor

 ✘ scott@tomato  ~/workspace/flutter_weather  flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/scott/dart/flutter
    • Framework revision d05c7f62f2 (2 weeks ago), 2016-12-21 06:19:42
    • Engine revision 2f32e8054d
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.1)
    • Android SDK at /Users/scott/soft/sdk
    • Platform android-25, build-tools 25.0.1
    • ANDROID_HOME = /Users/scott/soft/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    x libimobiledevice is incompatible with the installed XCode version. To update, run:
      brew uninstall libimobiledevice
      brew install --HEAD libimobiledevice

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Nexus 6 • ZX1G227KCN                               • android-arm • Android 7.0 (API 24)
    •         • d66b71e3af665e3de1f97faac6bea1bc76cc6e71 • ios         • iOS  ()

**Comment by eseidelGoogle** [comment]
@jason-simmons or @johnmccutchan know about our isolates support.

**Comment by jason-simmons** [comment]
Tried an engine build with a tip-of-tree Dart VM.  Isolates work as expected on the initial run, but after a hot reload I get the "Unable to find library" error.

The isolate library URL in the initial load is the path of the source on the host at build time.

The library URL after the hot reload is the path to the file on the device that was copied over by hot reload sync.

@johnmccutchan does the Flutter embedder need to do something in order to resolve the new library path?

**Comment by johnmccutchan** [comment]
@jason-simmons Yes, we might need to add an API to retrieve the URI of the root library (which as you've noted changes after a reload).

**Comment by Hixie** [comment]
cc @a-siva, @rmacnak-google

**Comment by Hixie** [comment]
Moving out of m3 since this doesn't fit our current priorities.

**Comment by rmacnak-google** [comment]
This would have been fixed whenever tonic added the Dart_kScriptTag case to its tag handler.
