### ISSUE TITLE
Flutter plugins repo should have a bluetooth implementation

### ISSUE THREAD

**Issue by safield** [flutter/flutter#73279]
It would be nice if the official Flutter plugins repo had support for bluetooth.

The most popular flutter bluetooth library (flutter blue) currently has an afk maintainer.

It would probably be best for the health of flutter that a core mobile behaviour like Bluetooth have official support. Potentially the unmaintained flutter blue repo could be forked by the flutter team.

**Comment by sidrao2006** [comment]
@safield this is an amazing idea but the flutter team seems to have a lot on its plate already. They are planning to improve platform support and allow dynamic loading. Check out the 2021 Roadmap.

@Hixie @blasten what are your thoughts on this?

**Comment by TahaTesser** [comment]
Hi @safield 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/53493
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
