### ISSUE TITLE
Pin Icon requested for Icons

### ISSUE THREAD

**Issue by Reagankm** [flutter/flutter#7329]
This is a feature request.  Is it possible to add a push pin icon to the Icons class, something [similar to this one](https://materialdesignicons.com/icon/pin)?

**Comment by eseidelGoogle** [comment]
It looks like it used to exist in the Material Design Icons (it's even in the screenshot at: https://material.io/guidelines/style/icons.html#icons-product-icons) but it no longer does?  Not sure.

**Comment by Hixie** [comment]
`Icons` just does whatever is in the Material font. In theory you can provide icons from other fonts, though this hasn't been thoroughly tested.

**Comment by Reagankm** [comment]
I see.  In that case, never mind.  If Android is moving away from the "pinning" concept I guess we'll have to use an alternative, like "favorites" with a star or something.

**Comment by emvaized** [comment]
By the way, there _is_ such an icon in Material Icons right now: [https://material.io/resources/icons/?search=push&icon=push_pin&style=baseline](https://material.io/resources/icons/?search=push&icon=push_pin&style=baseline)
