### ISSUE TITLE
flutter module doesn't have macos folder 

### ISSUE THREAD

**Issue by zsy61314** [flutter/flutter#73298]
I want usr flutter to develope a mac os app module. So i run "flutter create -t module flutter_module", but there is no .macos dir.

**Comment by TahaTesser** [comment]
Hi @zsy61314 
There is no add-to-app support for the macOS platform, only iOS, and Android platforms integrating the Flutter module. [Check out](https://flutter.dev/docs/development/add-to-app).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
