### ISSUE TITLE
MissingPluginException for quick_actions plugin

### ISSUE THREAD

**Issue by asadamatic** [flutter/flutter#73291]
I recently added ```quick_actions``` plugin works fine in debug mode but shows a blank screen in release mode.

### Found these issues in the log.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getLaunchAction on channel plugins.flutter.io/quick_actions)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
    <asynchronous suspension>
    #1      QuickActions.initialize (package:quick_actions/quick_actions.dart:68)
```

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method setShortcutItems on channel plugins.flutter.io/quick_actions)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
```

**Comment by pedromassangocode** [comment]
Hi @asadamatic 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by asadamatic** [comment]
Thanks @pedromassangocode , someone gave this answer on stacoverflow and now the issue is resolved but I  don't know if it's a permanent fix, looks like a workaround.

> I found the same issue for google_fonts package. As of now to remove this issue from the release mode I added shrinkResources false in the app level build.grade file of android folder. Let me know if this helps.
> 
> You should also use `minifyEnabled` , for reason see this answer
> 
>  https://stackoverflow.com/a/39629780/10285344
> 
> ```
> buildTypes {
>         //.....
>         release {
>             minifyEnabled false
>             shrinkResources true
>           
>         }
>         //......
>     }
> ```

**Comment by pedromassangocode** [comment]
Hi @asadamatic 
Can you please provide what was asked in https://github.com/flutter/flutter/issues/73291#issuecomment-754509920?
Thank you

**Comment by stuartmorgan** [comment]
There was an issue where some plugins had a dependency with a key class that was being stripped out during minification, and that would cause an exception during registration breaking the plugin and (due to another issue) all plugins after it alphabetically.

Both those issues are resolved on master, so this is likely fixed. If you can still reproduce on a current version of master, please update with details—it should have exception information logged during registration failures now—and we can re-open.
