### ISSUE TITLE
Draw fonts with gradient fill

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#733]
Make it possible to draw text with a gradient fill (top to bottom primarily).

**Comment by Hixie** [comment]
This should be possible if you use masks and so forth.

**Comment by Gaubee** [comment]
I use ShaderMask do that.
```dart
new ShaderMask(
    shaderCallback: (Rect bounds) {
        return new LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: <Color>[Colors.red, Colors.yellow],
        tileMode: TileMode.clamp,
        )
            .createShader(bounds);
    },
    blendMode: BlendMode.modulate,
    child: new Center(
        child: new Text('Gradient Text'),
         style: Theme
            .of(context)
            .textTheme
            .display1
            .copyWith(color: Colors.white)),
    ),
),
```
![image](https://user-images.githubusercontent.com/2151644/36375307-c5557efe-15a9-11e8-95ef-8b70040c3803.png)

**Comment by d-silveira** [comment]
this does not work for me, I also tried the example on the doc.: https://docs.flutter.io/flutter/widgets/ShaderMask-class.html ans it also does not do what it advertises, which is to color the text, instead, it paints a rectangle below the text
Here's my Doctor summary :
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/18347 will fix this more thoroughly.

**Comment by d-silveira** [comment]
@Hixie thank you so much for the speedy and useful reply.
I'm still left with two questions, nonetheless:
1. The feature #18347 is still not available through flutter upgrade, right? And if so,when can we expect that?
2. Is the shaderMask deprecated? does the docs example work for you? or should the docs example be updated to a working one?

Thanks again
