### ISSUE TITLE
Constrain the minimum height of an AppBar's toolbar

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7330]
Currently an AppBar's toolbar is fixed at 56.0 per the material spec - https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior.

It would be much more accommodating to only constrain the toolbar's minimum height.

This could be included as part of  https://github.com/flutter/flutter/issues/5288,

@Hixie

**Comment by zoechi** [comment]
Is this still relevant?

**Comment by genesiscz** [comment]
Is this getting some changes soon or not? I am having problems with just width and I can't even fit a FlatButton with Text("Save") there

**Comment by fralways** [comment]
Another bump here. Should be easy fix.

**Comment by brianoh** [comment]
I have situations where I want the height of the title to be less than 56 (this works currently for some reason). I also have situations where I want the title and actions to be more than 56, and making the AppBar higher does not allow for a higher title and actions which is disappointing. Making it higher than 56 does increase the height of the AppBar, but not the title area, and nothing will make the title and actions area higher. I would like the height of both the title and actions area and the AppBar area and the bottom to be modifiable. Thanks.

**Comment by brianoh** [comment]
AppBar "flexibleSpace:" appears to solve this issue 100% for me. If this appears to be the case for other situations, perhaps this issue should be marked resolved.

**Comment by genesiscz** [comment]
And how about changeable width and FlatButton(child: Text("Save")) in the leading?

**Comment by brianoh** [comment]
If you use "flexibleSpace:" you can specify your own widgets to be anything you like. In my case, I define an Icon, Text, Icon, Icon to emulate the standard AppBar toolbar. The Icons have a text above and below and the text for the title is two lines. All of these are within a "Container". I then use the "bottom:" for a TabBar. It works like a treat for me, so I cannot see why it wouldn't solve your problem. If you google it you should find some examples.
