### ISSUE TITLE
 CupertinoIcons are under the question mark symbol. 

### ISSUE THREAD

**Issue by hailemix** [flutter/flutter#73308]
Some of my CupertinoIcons like `arrow_right_arrow_left` still under the question mark symbol. I've already added all the materialApp and Cupertino icons in pubspec.

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.2 20D5029f darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
user@chenwenhaideMacBook-Pro Birr-Converter-Flutter-App % flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.2 20D5029f darwin-x64, locale en-CN)
    • Flutter version 1.25.0-8.1.pre at /Applications/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 30497074-7E35-44F3-8046-3E447431559E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

`

_Originally posted by @hailemix in https://github.com/flutter/flutter/issues/8358#issuecomment-754528902_

**Comment by darshankawar** [comment]
@hailemix 
Can you provide a minimal complete reproducible code sample, `pubspec.yaml` along with screenshot of how they are looking in UI ?

**Comment by hailemix** [comment]
Hi @darshankawar
Here is the sample code...
`Widget _buildIosPage(BuildContext context) {
    var appLanguage = Provider.of<AppLanguage>(context);
    List<BottomNavigationBarItem> _cupertinoCurrencyTabs = [
      BottomNavigationBarItem(icon: Icon(CupertinoIcons.money_dollar_circle), label: AppLocalizations.of(context).translate('exchangeTab')),
      BottomNavigationBarItem(icon: Icon(CupertinoIcons.info), label: AppLocalizations.of(context).translate('bankInfoTab')),
      BottomNavigationBarItem(icon: Icon(CupertinoIcons.settings), label: AppLocalizations.of(context).translate('more')),

    ];
     return WillPopScope(
      onWillPop: _onBackPressed,
      child: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(
          items: _cupertinoCurrencyTabs,
        ),
        tabBuilder: (BuildContext context, int index){
          return CupertinoTabView(
           builder: (BuildContext context){
             return CupertinoPageScaffold(
               navigationBar: CupertinoNavigationBar(
                 middle: Text(AppLocalizations.of(context).translate('appTitle'),
                   style: TextStyle(
                       fontWeight: FontWeight.bold,
                       fontSize: 16.0,
                       color: Colors.white),),
                 trailing: CupertinoButton(
                   onPressed: () {
                     changeLanguage = !changeLanguage;
                     setState(() {
                       changeLanguage
                           ? appLanguage.changeLanguage(Locale("am"))
                           : appLanguage.changeLanguage(Locale("en"));
                     });
                   },
                   child: Text(
                     AppLocalizations.of(context).translate('languageChangerText'),
                     style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12.0),
                   ),
                 ),
                 backgroundColor: _baseColors[_currentIndex],
               ),
               child: SafeArea(
                 child: allPages[index],
               )
             );
           },`

The first bottom navigation bar item shows a question mark in the UI

**Comment by hailemix** [comment]
Here is **pubspec.yaml**
       `name: ethiobirr_converter
description: Ethiopian Birr Converter is a Flutter app which converts all major currencies of the world to Ethiopian Birr.
version: 1.0.0+2

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+2
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.24
  url_launcher: ^5.7.10
  intl: ^0.17.0-nullsafety.2
  flare_flutter: ^2.0.6
  firebase_core: ^0.5.3
  firebase_admob: ^0.10.3
  firebase_crashlytics: ^0.2.4
  firebase_analytics: ^6.3.0
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - images/about_us.png
    - images/drawer_image.png
    - images/waterloading.flr
    - i18n/en.json
    - i18n/am.json
    - bank_logo/abay.png
    - bank_logo/awash.png
    - bank_logo/commercial.png
    - bank_logo/dashen.png
    - bank_logo/wegagen.png
    - bank_logo/abyssinia.png
    - bank_logo/addis.png
    - bank_logo/anbessa.png
    - bank_logo/berhan.png
    - bank_logo/bunna.png
    - bank_logo/cooperation.png
    - bank_logo/debub.png
    - bank_logo/enat.png
    - bank_logo/hibret.png
    - bank_logo/nib.png
    - bank_logo/oromia_international.png
    - bank_logo/zemen.png
    - images/exchange.png
  uses-material-design: true
`

**Comment by hailemix** [comment]
And here is the screenshot;The first bottom navigation bar item is the problem with a question mark.

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-05 at 14 41 32](https://user-images.githubusercontent.com/17510754/103642607-726cf800-4f64-11eb-8c04-fafc3de5de54.png)

**Comment by darshankawar** [comment]
@hailemix 
I see lot of custom code in the sample you provided. We would need a complete minimal reproducible sample that we can copy paste and directly run in IDE to see the issue. Please provide the same.
Thanks.

**Comment by hailemix** [comment]
Hi,

I have finally resolved it. It is due to the **old Cupertino icon plugin version.** As soon as I update to `cupertino_icons: ^1.0.1`, the icon starts showing.
