### ISSUE TITLE
Unhandled Exception: MissingPluginException only on release mode version but no error in debug mode?

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#73316]
I have been running my app with onesignal all works fine on my emulator which is debug mode. The moment I run it on flutter build apk and install on the phone I notice something was wrong. Thereafter I did run this flutter logs and connect the phone. What I found below as below. What I am not sure is one why it run on the debug mode with no error ? Secondly is it a bug related to one signal or flutter itself ?
```
E/flutter (32589): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#setLogLevel on channel OneSignal)
E/flutter (32589): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): #1      OneSignal.setLogLevel (package:onesignal_flutter/onesignal_flutter.dart:72)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): 
E/flutter (32589): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#log on channel OneSignal)
E/flutter (32589): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): #1      OneSignal._onesignalLog (package:onesignal_flutter/onesignal_flutter.dart:391)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): 
E/flutter (32589): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#init on channel OneSignal)
E/flutter (32589): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): #1      OneSignal.init (package:onesignal_flutter/onesignal_flutter.dart:64)
E/flutter (32589): <asynchronous suspension>
E/flutter (32589): 
I/flutter (32589): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
I/flutter (  320): Observatory listening on http://127.0.0.1:40885/rljYfy4bdxg=/
```

**Comment by darshankawar** [comment]
@newbieflutter 
Do you still get the same error if you remove the one signal dependency ?
If not, then it could be an issue with one signal sdk you are using and may have to open this issue in their repo.
If issue persists still after removing the dependency, then provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by newbieflutter** [comment]
Hi Darshan,
                    Ok what I did what build a brand new app. First I just add the one signal portion looks ok. Then next I added the shared preference plugin and I did the same build a release copy and then I connect my phone then I ran flutter logs
Showing Instance of 'NoOpDeviceLogReader' logs: and it immediately stops so do you think its shared preference issue?

**Comment by newbieflutter** [comment]
Hi Darshan,
                    Here is the list of issue with shared_preferences.

/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:9: warning: [deprecation] AsyncTask in android.os has been deprecated
import android.os.AsyncTask;                                            
                 ^                                                      
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask in android.os has been deprecated
    new AsyncTask<Void, Void, Boolean>() {                              
        ^                                                               
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {                              
    ^                                                                   
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:123: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
      protected Boolean doInBackground(Void... voids) {                 
                        ^                                               
  where Params,Result are type-variables:                               
    Params extends Object declared in class AsyncTask                   
    Result extends Object declared in class AsyncTask                   
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:121: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
    new AsyncTask<Void, Void, Boolean>() {                              
                                         ^                              
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:128: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
      protected void onPostExecute(Boolean value) {                     
                     ^                                                  
  where Result is a type-variable:                                      
    Result extends Object declared in class AsyncTask                   
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:131: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
    }.execute();                                                        
     ^                                                                  
  where Params,Progress,Result are type-variables:                      
    Params extends Object declared in class AsyncTask                   
    Progress extends Object declared in class AsyncTask                 
    Result extends Object declared in class AsyncTask                   
7 warnings

**Comment by darshankawar** [comment]
@newbieflutter 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by newbieflutter** [comment]
Hi,
     Here is the flutter doc

```
flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.179, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.179 at /usr/local/flutter
    • Framework revision a293c82251 (27 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shaisingh/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```

Below here is the sample codes.
```
import 'package:flutter/material.dart';
//import OneSignal
import 'package:onesignal_flutter/onesignal_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  // This widget is the root of your application.

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    if (!mounted) return;

    OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);

    OneSignal.shared.consentGranted(true);

    var settings = {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };

    OneSignal.shared
        .setNotificationReceivedHandler((OSNotification notification) {});

    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {});

    OneSignal.shared
        .setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      print("SUBSCRIPTION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
      print("PERMISSION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    // NOTE: Replace with your own app ID from https://www.onesignal.com
    await OneSignal.shared
        .init("b2f7f966-d8cc-11e4-bed1-df8f05be55ba", iOSSettings: settings);

    OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);

    // bool requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
      print("COUNTER IS" + _counter.toString());
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
