### ISSUE TITLE
[Question] Does the current version of url_launcher supports opening of desktop(windows, macOS) directory in native file explorer?

### ISSUE THREAD

**Issue by shrey112710** [flutter/flutter#73317]
I went through the code, for both macOs and windows. Since, swift and c++ are not my strong languages but having a brief look at the code made me wonder if the support, for opening the directory in the native file explorer (of windows and macOs), when a local path of that directory is provided, is already available or will be provided in the near future? Because I couldn't find anything in the documentation about it. If there is an alternate solution, already out there, please let me know. Please be gentle as I am relatively new to flutter and still learning about it.

**Comment by darshankawar** [comment]
@shrey112710 
What's the current behavior if you use `url_launcher` on windows and macOS ?
If you would like this to be something the plugin should support, then could you provide a use case of what are you trying to achieve / looking for so that we can better address this issue ?
Thanks.

**Comment by shrey112710** [comment]
@darshankawar currently, `url_launcher` works for certain URL schemes as mentioned in the [documentation](https://pub.dev/packages/url_launcher). 

I want to open a specific directory, in the native file explorer of the desktop, when it's path passed to the `launch` method.
When passing a local path of a directory (macOS), it doesn't work. 
I am passing the path of the directory like this: `"/Users/xyz/test_folder/"`. I am not sure if support for this feature is already implemented or there is a different URL scheme for passing a directory path, so as to open that directory in native file explorer (finder in macOS & file explorer in windows) or if in the near future it will be available, if yes, then I would love to contribute as well.

**Comment by stuartmorgan** [comment]
> I want to open a specific directory, in the native file explorer of the desktop, when it's path passed to the `launch` method.

This is not explicitly in scope for the `url_launcher` plugin.

> When passing a local path of a directory (macOS), it doesn't work. I am passing the path of the directory like this: `"/Users/xyz/test_folder/"`.

That's not a URL, so not working would be expected behavior for the plugin. It may or may not work with `file:` URLs, but again, that's not a deliberately supported use case.

> Edit: If such a feature is in the pipeline it would be nice to also be able to open the file when the path is of a file instead of a directory. If there is a possibility of it then I am more than happy to contribute to it.

As with directories, this may work when given a file URL, depending on the details of the OS function that is used to implement URL launching.

**Comment by technolion** [comment]
I can confirm that both on Windows and macOS it's possible to use `url_launcher` to open file URLs for local directories. This results in a new Windows Explorer or Finder window to be opened.

**Comment by sgehrman** [comment]
Doesn't seem to work in Linux, but works on macOS.
