### ISSUE TITLE
Issue when we use ListView inside the Column(children: [])

### ISSUE THREAD

**Issue by shylendramadda** [flutter/flutter#73329]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@shylendramadda 
does this code sample represent the issue you are describing?

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Column(
            children: [
              const FlutterLogo(size: 80),
              SizedBox(
                height: 400,
                child: ListView.builder(
                  itemBuilder: (context, _) => const FlutterLogo(size: 80),
                ),
              ),
            ],
          ),
        ),
      ),
    );

```

**Comment by shylendramadda** [comment]
No, but it is fixed now

**Comment by pedromassangocode** [comment]
Hi @shylendramadda 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
