### ISSUE TITLE
Pixel C (running Flutter) gets disconnected from MacBook Pro after ~20 minutes

### ISSUE THREAD

**Issue by bkobash** [flutter/flutter#7332]
## Steps to Reproduce

1. Connect the Pixel C to the MacBook Pro. (Pixel C appears as a target device in the Atom toolbar; also appears as a connected device in flutter doctor.)
![1-found-device](https://cloud.githubusercontent.com/assets/1093474/21658691/6c26ec4e-d27c-11e6-99b8-cb3cffc3f8bd.png)

2. Run a Flutter project.
![2-normal-operation](https://cloud.githubusercontent.com/assets/1093474/21658696/712e67f8-d27c-11e6-8c19-534d43c36298.png)

3. After some period of time (10-20 minutes), a couple of messages appear in Atom:
- "flutter: lib/main.dart finished."
- "Pixel C removed."
![3-device-disconnected](https://cloud.githubusercontent.com/assets/1093474/21658703/7561bda2-d27c-11e6-9690-d4bb9de3d5d9.png)

4. At this point, the Pixel C is inaccessible from Atom.
![4-cant-run-device](https://cloud.githubusercontent.com/assets/1093474/21658721/8476614e-d27c-11e6-9943-96d563a3694d.png)

5. If you unplug the Pixel C, the entire MacBook crashes. (Black screen of death.) OS X logs attached.
[log-pixelc-20170104-1141.txt](https://github.com/flutter/flutter/files/685731/log-pixelc-20170104-1141.txt)

Currently running:
- MacBook Pro: OS X El Capitan 10.11.6
- Pixel C: Android 7.1.1

## Logs

The logs are pretty minimal, and "flutter doctor" and "flutter analyze" don't report anything unusual. But you can see in the attached screenshots that at around (3), this log message appears: 

> Application finished.
> 
> process finished • exit code 0

**Comment by ahmetaa** [comment]
Perhaps this is Atom related. Have you tried the same with Intellij plugin?

**Comment by bkobash** [comment]
I get this when I run `adb version`:
```
Android Debug Bridge version 1.0.36
Revision 88f64719d756-android
```
Will try with a different cable, as well.

**Comment by bkobash** [comment]
As a quick update: I tried with a different USB-C to USB-A cable and got the same issue after ~20 minutes. (The Pixel gets disconnected, and there's a hard crash upon unplugging. Also, the laptop crashes when put into sleep mode.)

**Comment by eseidelGoogle** [comment]
http://apple.stackexchange.com/questions/119849/internal-keyboard-and-trackpad-stop-working-after-plugging-in-usb-device or https://code.google.com/p/android/issues/detail?id=39548 might be relateD?

**Comment by bkobash** [comment]
I tried connected a Nexus 9 to my laptop (via Micro USB) and experienced the same issue. 

However, it turns out my Android SDK was at **version 24**. I upgraded to **25** and haven't experienced any of the problems on either the Pixel C or the Nexus 9. I'm still monitoring things, but it looks like a safe bet that the older SDK was the culprit.

**Comment by sethladd** [comment]
Thanks for the update! Going to close this in preference of https://github.com/flutter/flutter/issues/7588

But, if anyone is reading this, try upgrading to Android 25. :)
