### ISSUE TITLE
GridView main-axis-count

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#73326]
**GridView.count** supports only **crossAxisCount**, and **GridView.builder** supports only **SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2)**.

I'm trying to create 2 lines, one below the other, for a gallery view in my website, i didn't find any widget that support it.
I think is a good idea to support **mainAxisCount** for main axis count.

**Comment by darshankawar** [comment]
@xOldeVx 
Can you provide `flutter doctor -v` and a code sample use case of what you are trying to achieve and a proposal of how `mainAxisCount` would solve your issue ?
