### ISSUE TITLE
Regression: Talkback no longer works at all with Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7333]
Flutter used to have some very basic Talkback support, but it no longer seems to do anything.

Presumably we broke this when moving away from mojo for transport?

**Comment by eseidelGoogle** [comment]
@abarth or @jason-simmons may have some context.  Given that we don't expect our AX to work at this point, this is a lower priority than other regressions.  However we have had at least a couple customers ask about our AX support (which is a broader question than just talkback of course).

When we fix this we should figure out if we can set up some very basic integration testing to catch this kind of thing.

**Comment by jason-simmons** [comment]
Spent some time looking at this.  The exchange of semantics tree information between the engine and the framework is now based on JNI, and as far as I can tell it works as expected.

However, the accessibility tree that we publish to Android does not seem to match the expectations of TalkBack.  In particular, the AccessibilityNodeInfo bounds rectangles look like they have been transformed to the wrong size.

**Comment by eseidel** [comment]
We had a similar report in https://github.com/flutter/flutter/issues/7205 using a different way to visualize AX information.

**Comment by eseidelGoogle** [comment]
We should consider starting AX work in May.

**Comment by Hixie** [comment]
This is too vague to be actionable. There's lots of bugs, but it does work in the basic sense that we do different things when accessibility is enabled than when it's not.

https://github.com/flutter/flutter/issues/7205 covers the problem whereby all the sizes are wrong.
