### ISSUE TITLE
Hot reload does not recognize changes to data objects

### ISSUE THREAD

**Issue by bkobash** [flutter/flutter#7334]
## Steps to Reproduce

I'm quite new at Dart/Flutter, putting together a simple list of movie reviews for a sample app. To provide the data for those reviews, I have an array of Review objects, like so:

```
class Review {
  const Review({
    this.name,
    this.publication,
    this.quote,
    this.isPositive,
  });
  final String name;
  final String publication;
  final String quote;
  final bool isPositive;
}
List<Review> _reviewData = [
  new Review (
    name: 'Joe Reviewer',
    publication: 'Generic Star Ledger',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: true,
  ),
  new Review (
    name: 'Jane Reviewer',
    publication: 'Generic Times',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: false,
  ),
];
```

I populate a series of Text elements in build() with the  _reviewData members, and it works fine. But I encounter what appears to be an issue when updating that _reviewData list.

1) In main.dart, update _reviewData's first member's "name" from "Joe Reviewer" to "Bob Reviewer"
2) Hit the Reload button in Atom.

**Expected**: "Joe Reviewer" gets replaced with "Bob Reviewer".
**Actual**: Nothing happens. In Atom, I have to Shift+Click the Reload button to do a full restart, and then the data gets updated accordingly.

Another approach:

1) Stop running main.dart
2) In main.dart, update _reviewData's first member's "name" from "Joe Reviewer" to "Bob Reviewer"
3) Run main.dart

**Expected**: "Joe Reviewer" gets replaced with "Bob Reviewer".
**Actual**: Nothing happens - similar to above, I have to do a full restart.

**Comment by Hixie** [comment]
We'd need to see more code to track this down, but my suspicion is that this is working as intended: hot reload does not rerun initialisers or code in functions like constructors or initState.

If you're doing it in initState you can work around this by putting it in a separate method which you call from both initState and reassemble.

**Comment by sethladd** [comment]
Thanks @bkobash ! This is a tricky usability issue with hot reload, don't worry about not understanding. We have some work to do to better explain what's happening to users.

Hot reload works great with changes made to code that is inside of a _function_ or _constructor_ (and only works when the function and constructor is re-run after the reload). Code that's just "sitting there" at the top level of your app, or is run only once, like the list of _reviewData, is only evaluated _once_ (even after a hot reload).

That said, I think @johnmccutchan added support for more change scenarios, so maybe this could work in the future.

Regardless, we could and should do more to show a clearer UX about what you can expect to change after a Hot Reload.

**Comment by Hixie** [comment]
If you put the data in a constant, and update the constant initialiser, that's another way to do it. We do reevaluate constants.

**Comment by johnmccutchan** [comment]
Hi,

This is working as intended. We reload code not data. This is covered in Todd and I's talk: 

https://www.youtube.com/watch?v=iPlPk43RbpA

**Comment by johnmccutchan** [comment]
@bkobash Note that const data does get reloaded. It should work if you reformulated your code like so:

```
const List<Review> _reviewData = const [
  const Review (
    name: 'Joe Reviewer',
    publication: 'Generic Star Ledger',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: true,
  ),
  const Review (
    name: 'Jane Reviewer',
    publication: 'Generic Times',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: false,
  ),
];```

**Comment by sethladd** [comment]
@bkobash you can also put it behind a function, like this:

```
List<Review> _reviewData() {
 return [
  new Review (
    name: 'Joe Reviewer',
    publication: 'Generic Star Ledger',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: true,
  ),
  new Review (
    name: 'Jane Reviewer',
    publication: 'Generic Times',
    quote: 'Lorem ipsum dolor sit amet, consec etur.',
    isPositive: false,
  ),
];
}
```

**Comment by bkobash** [comment]
Ah, got it. Thanks for all the advice!
