### ISSUE TITLE
If application sha1 file is missing on Android, `flutter run` fails

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#7335]
In [`AndroidDevice.isAppInstalled()`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L219), we check the following:

    _getDeviceApkSha1(app) == _getSourceSha1(app)

However, if the sha1 file is missing entirely, this call will throw as opposed to returning false.

We've gotten a few reports in the wild of Flutter apps that were installed, yet this file was inexplicably missing.  Initial reports seem like this may only affect Android emulators.

**Comment by tvolkert** [comment]
Just got word that this has been on a real device as well.  We should just gracefully handle the case of the sha1 file not being there.

**Comment by eseidelGoogle** [comment]
customer:fast just ran into this.  Internal bug 34854670.

**Comment by eseidelGoogle** [comment]
I believe @jakobr-google changed some of this code recently? Not sure if it addressed the internal bug.

**Comment by jakobr-google** [comment]
I think it did. I used `runSync()` instead of `runCheckedSync()` when reading the sha1 file, so we don't throw an error anymore if it's missing but just treat it as meaning "not installed".
