### ISSUE TITLE
Flutter & dart issue

### ISSUE THREAD

**Issue by Linawho** [flutter/flutter#73350]
Why did I get the error message when I run flutter doctor in vs code?=
[an_app] flutter pub get
Waiting for another flutter command to release the startup lock...
Running "flutter pub get" in an_app...                          

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...

Thanks.

**Comment by iapicca** [comment]
@Linawho 
can you provide the full output running  `flutter doctor -v`  from terminal (not vscode)

**Comment by Linawho** [comment]
Hi iapicca, Here it is=
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-MY)
    • Flutter version 1.22.5 at C:\Users\PC\git\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\PC\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\PC\AppData\Local\Android\Sdk\platform-tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Thank you.

**Comment by Linawho** [comment]
Only 1 issue since I didn't connect my phone to my computer.

**Comment by TahaTesser** [comment]
Hi @Linawho 
Please make sure you have stable internet. Are you in a restricted country? Disable/Whitelist/Firewall any Antivirus you've.
If the problem persists, Can you please provide complete `flutter run --verbose` 
Thank you

**Comment by Linawho** [comment]
Hi Taha,

I have stable internet. No, I am not in a restricted country. I have
disabled my antivirus & allow my editor to run in my firewall.
Here is the complete flutter run --verbose on a new project=
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\PC\IdeaProjects\the_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version
10.0.19042.685], locale en-MY)

[√] Android toolchain - develop for Android devices (Android SDK version
30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific
functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

C:\Users\PC\IdeaProjects\the_app>flutter run --verbose
[ +458 ms] executing: [C:\Users\PC\git\flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +206 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] 78910062997c3a836feee883712c241a5fd22983
[   +2 ms] executing: [C:\Users\PC\git\flutter/] git tag --points-at HEAD
[ +140 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.5
[  +27 ms] executing: [C:\Users\PC\git\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[ +121 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Users\PC\git\flutter/] git ls-remote --get-url
origin
[ +114 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +980 ms] executing: [C:\Users\PC\git\flutter/] git rev-parse --abbrev-ref
HEAD
[ +185 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +364 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[  +16 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[  +94 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +126 ms] List of devices attached
                    320136568203254a       device product:j1minive3gxtc
model:SM_J106B device:j1minive3gxtc transport_id:1
[  +26 ms] C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell getprop
[ +324 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[  +17 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[+1796 ms] Generating
C:\Users\PC\IdeaProjects\the_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +113 ms] ro.hardware = sc8830
[   +3 ms] ro.build.characteristics = default
[ +243 ms] Starting incremental build...
[  +17 ms] Initializing file store
[  +43 ms] Skipping target: gen_localizations
[  +93 ms] complete
[  +23 ms] Launching lib\main.dart on SM J106B in debug mode...
[  +75 ms] C:\Users\PC\git\flutter\bin\cache\dart-sdk\bin\dart.exe
--disable-dart-dev
C:\Users\PC\git\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root
C:\Users\PC\git\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\PC\AppData\Local\Temp\flutter_tools.131d954d\flutter_tool.8465745c\app.dill
--packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +92 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[ +332 ms] Exit code 0 from:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           01-06 17:36:12.652 D/WCND    (  230): is_cp2_alive_ok: loop:
/proc/mdbg/loopcheck is OK
[  +14 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[ +299 ms] Exit code 0 from:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[   +3 ms] --------- beginning of main
           01-06 17:36:12.652 D/WCND    (  230): is_cp2_alive_ok: loop:
/proc/mdbg/loopcheck is OK
[  +82 ms] <- compile package:the_app/main.dart
[  +26 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +216 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.5-6877874
                    Installed as
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe
[  +35 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +798 ms] Building APK
[ +252 ms] Running Gradle task 'assembleDebug'...
[  +28 ms] set `android.enableR8=true` in gradle.properties
[  +20 ms] Using gradle from
C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat.
[   +7 ms] C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat mode: 33279
rwxrwxrwx.
[  +49 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java
-version
[+1683 ms] Exit code 0 from: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +9 ms] executing: [C:\Users\PC\IdeaProjects\the_app\android/]
C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm
-Ptarget=C:\Users\PC\IdeaProjects\the_app\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+23151 ms] Welcome to Gradle 5.6.2!
[+2168 ms] Here are the highlights of this release:
[   +5 ms]  - Incremental Groovy compilation
[   +5 ms]  - Groovy compile avoidance
[   +7 ms]  - Test fixtures for Java projects
[   +2 ms]  - Manage plugin versions via settings script
[   +3 ms] For more details see
https://docs.gradle.org/5.6.2/release-notes.html
[+17132 ms] Starting a Gradle Daemon, 1 busy and 1 incompatible and 1
stopped Daemons could not be reused, use --status for details

Thank you.

**Comment by TahaTesser** [comment]
### Above comment marked down.

Hi Taha,
I have stable internet. No, I am not in a restricted country. I have
disabled my antivirus & allow my editor to run in my firewall.
Here is the complete flutter run --verbose on a new project=

```
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\PC\IdeaProjects\the_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version
10.0.19042.685], locale en-MY)

[√] Android toolchain - develop for Android devices (Android SDK version
30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific
functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

```bash
C:\Users\PC\IdeaProjects\the_app>flutter run --verbose
[ +458 ms] executing: [C:\Users\PC\git\flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +206 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] 78910062997c3a836feee883712c241a5fd22983
[   +2 ms] executing: [C:\Users\PC\git\flutter/] git tag --points-at HEAD
[ +140 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.5
[  +27 ms] executing: [C:\Users\PC\git\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[ +121 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Users\PC\git\flutter/] git ls-remote --get-url
origin
[ +114 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +980 ms] executing: [C:\Users\PC\git\flutter/] git rev-parse --abbrev-ref
HEAD
[ +185 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +364 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[  +16 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[  +94 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +126 ms] List of devices attached
                    320136568203254a       device product:j1minive3gxtc
model:SM_J106B device:j1minive3gxtc transport_id:1
[  +26 ms] C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell getprop
[ +324 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[  +17 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[+1796 ms] Generating
C:\Users\PC\IdeaProjects\the_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +113 ms] ro.hardware = sc8830
[   +3 ms] ro.build.characteristics = default
[ +243 ms] Starting incremental build...
[  +17 ms] Initializing file store
[  +43 ms] Skipping target: gen_localizations
[  +93 ms] complete
[  +23 ms] Launching lib\main.dart on SM J106B in debug mode...
[  +75 ms] C:\Users\PC\git\flutter\bin\cache\dart-sdk\bin\dart.exe
--disable-dart-dev
C:\Users\PC\git\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root
C:\Users\PC\git\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\PC\AppData\Local\Temp\flutter_tools.131d954d\flutter_tool.8465745c\app.dill
--packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +92 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[ +332 ms] Exit code 0 from:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           01-06 17:36:12.652 D/WCND    (  230): is_cp2_alive_ok: loop:
/proc/mdbg/loopcheck is OK
[  +14 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[ +299 ms] Exit code 0 from:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe -s
320136568203254a shell -x logcat -v time -t 1
[   +3 ms] --------- beginning of main
           01-06 17:36:12.652 D/WCND    (  230): is_cp2_alive_ok: loop:
/proc/mdbg/loopcheck is OK
[  +82 ms] <- compile package:the_app/main.dart
[  +26 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +216 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.5-6877874
                    Installed as
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe
[  +35 ms] executing:
C:\Users\PC\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +798 ms] Building APK
[ +252 ms] Running Gradle task 'assembleDebug'...
[  +28 ms] set `android.enableR8=true` in gradle.properties
[  +20 ms] Using gradle from
C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat.
[   +7 ms] C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat mode: 33279
rwxrwxrwx.
[  +49 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java
-version
[+1683 ms] Exit code 0 from: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +9 ms] executing: [C:\Users\PC\IdeaProjects\the_app\android/]
C:\Users\PC\IdeaProjects\the_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm
-Ptarget=C:\Users\PC\IdeaProjects\the_app\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+23151 ms] Welcome to Gradle 5.6.2!
[+2168 ms] Here are the highlights of this release:
[   +5 ms]  - Incremental Groovy compilation
[   +5 ms]  - Groovy compile avoidance
[   +7 ms]  - Test fixtures for Java projects
[   +2 ms]  - Manage plugin versions via settings script
[   +3 ms] For more details see
https://docs.gradle.org/5.6.2/release-notes.html
[+17132 ms] Starting a Gradle Daemon, 1 busy and 1 incompatible and 1
stopped Daemons could not be reused, use --status for details
```

Thank you.

**Comment by TahaTesser** [comment]
Hi @Linawho 

Logs you provided are not complete, there is no `pub get failed (server unavailable) -- attempting retry 1 in 1 second...` 
Can you please make sure you complete logs by execute `flutter run --verbose > run.log` (after run logs end, copy this `run.log` file drop it here)
Thank you

**Comment by Linawho** [comment]
Hi Taha,

I already know how to solve my problem because I need to run my command
outside IDE. Thanks.

**Comment by TahaTesser** [comment]
Hi @Linawho 
I'm not sure what do you mean. Please provide asked in https://github.com/flutter/flutter/issues/73350#issuecomment-755954335
Thank you

**Comment by Linawho** [comment]
Hi @TahaTesser,
But when I run application using command line : https://flutter.dev/docs/get-started/test-drive?tab=terminal and then run flutter doctor, the same error still shows=
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version
    10.0.19042.685], locale en-MY)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

Does ( https://stackoverflow.com/questions/51860845/flutter-plugin-not-installed-error-when-running-flutter-doctor = the issue is just that "flutter doctor" is not able to read behind the scene that everything is fine and up to date. This issue is temporary till next patch or update and can be avoided as it won't affect anywhere in the development process) mean that we can just ignore the flutter plugin & dart plugin not installed error? 

Or how to run ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1?
Because when I run this in git bash, there is an error = 
PC@LAPTOP-DU1VCII0 MINGW64 /dapp
$ In -s ~/Library/Application\Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1
bash: In: command not found

And I don't need to edit the pubspec.yaml but leave it as default, right? 

Thank you.

**Comment by TahaTesser** [comment]
Hi @Linawho 
You can ignore plugins not being detected, it doesn't affect the Flutter functionality, you would still be able to use the Flutter plugin in Android Studio your app.

Other than a plugin, you didn't provide any other reproduction steps to indicate there is another issue 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
