### ISSUE TITLE
How to Build APK with Plugin Lib?

### ISSUE THREAD

**Issue by mkkatjp** [flutter/flutter#73379]
I am using a lib like this,
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.6.7+4

app-release.apk(file size 16M) does not work, but app-debug.apk(49M) can work fine.

How can fix this problem?

**Comment by pedromassangocode** [comment]
Hi @mkkatjp 
What is the problem?
What exactly is not working?

Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by mkkatjp** [comment]
C:\flutterSDK\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, 1.26.0-2.0.pre.200, on Microsoft Windows [Version 10.0.18363.1256], locale ja-JP)
    • Flutter version 1.26.0-2.0.pre.200 at C:\flutterSDK\flutter
    • Framework revision d0e9959a46 (8 hours ago), 2021-01-05 22:14:03 -0500
    • Engine revision e115066dcd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\flutterSDK\flutter
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:/Users/m/AppData/Local/Android/sdk
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\m\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (3 available)
    • ASUS X00ID (mobile) • J2AXB760V768V75 • android-arm64  • Android 7.1.1 (API 25)
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)          • edge            • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
Process finished with exit code 0

**Comment by mkkatjp** [comment]
main.dart


import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();
  bool camera = true;

  Future getImage() async {
    var v = ImageSource.camera;
    if (!camera) v = ImageSource.gallery;
    var pickedFile = await picker.getImage(source: v);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null
            ? Text('No image selected.')
            : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getImage();
          camera = !camera;
        },
        tooltip: 'Pick Image',
        child:
        Icon(Icons.add_a_photo),
      ),
    );
  }
}

**Comment by mkkatjp** [comment]
pubspec


name: my_image_picker01
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.6.7+4



flutter:
  uses-material-design: true

**Comment by mkkatjp** [comment]
android/build.gradle


buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

dependencies {
}

**Comment by mkkatjp** [comment]
app/build.gradle


def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.triumph.my_image_picker01"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

**Comment by mkkatjp** [comment]
gradle-wrapper.properites

#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by mkkatjp** [comment]
Thanks for you reply.

I can RUN in my smartphone, in Debug Mode.
But when I build it in release mode,
app-release.apk(file size 16M)  can install in smartphone, but It does not work in smartphone,
(can not show Picker Page?[or Dialog])
but app-debug.apk(49M) can work fine.

How can fix this problem?

**Comment by pedromassangocode** [comment]
@mkkatjp 
Does it shows any error/crash logs in the console?

**Comment by mkkatjp** [comment]
No any Error or Crash in console. It is all OK when in Debug mode.

**Comment by pedromassangocode** [comment]
Hi @mkkatjp 
I was able to reproduce the issue however there is already a similar issue (https://github.com/flutter/flutter/issues/72759) so I'm going to close this one. Please follow up on that issue for updates!

Closing this as duplicate.
Thank you.
