### ISSUE TITLE
Stuck in Waiting for  xxx to report its views

### ISSUE THREAD

**Issue by lvpeng0412** [flutter/flutter#73387]
[✓] Flutter (Channel master, 1.22.5, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/fuxiaoquan/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.dartlang.org
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/fuxiaoquan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/fuxiaoquan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • 测试iPhone7 (mobile)                 • 16c2efb1f5cd2e3da6878abbbfa2e619c51857ca • ios         • iOS 14.1

! Doctor found issues in 1 category.

**Comment by lvpeng0412** [comment]
Running Xcode build...
Xcode build done.                                           76.3s
Installing and launching...
Waiting for 测试iPhone7 to report its views...

**Comment by darshankawar** [comment]
@lvpeng0412 
Please provide `pubspec.yaml` and a minimal complete reproducible code sample.
Is your mac M1 ?

**Comment by lvpeng0412** [comment]
MacBook Pro (Retina, 15-inch, Mid 2015)
I update flutter from 1.22.0 to 1.22.5 occurred this problem

**Comment by darshankawar** [comment]
@lvpeng0412 
As requested earlier, provide `pubspec.yaml` and minimal complete reproducible code sample to better address your issue.
Thanks.

**Comment by lvpeng0412** [comment]
name: zdd_wallet_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+76

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # 动画
  flare_flutter: ^2.0.6
  # 消息传递
  event_bus: ^1.1.1
  # 路由
  fluro: ^1.7.3
  provider: ^4.3.2+2
  # 网络库
  dio: ^3.0.10
  # 字符串格式化
  sprintf: ^4.1.0
  # 手机信息
  package_info: ^0.4.3+2
  # https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # 偏好保存
  shared_preferences: ^0.5.10
  sp_util: ^1.0.1
  # toast
  oktoast: ^2.3.2
  # flutter_lifecycle_state: ^1.0.0
  uuid: ^2.0.2
  # ntp: ^1.0.4
  path_provider: ^1.6.14
  # 图片库(带缓存)
  cached_network_image: ^2.3.2
  # 数据库orm
  moor: ^3.1.0
  moor_ffi: ^0.8.0
  sqlite3_flutter_libs: ^0.2.0
  # json注解
  json_annotation: ^3.0.1
  # 高精度货币结算
  decimal: ^0.3.0
  # 框架
  fish_redux: ^0.3.4
  # 无限滚动
  # flutter_swiper: ^1.1.6
  transformer_page_view: 0.1.6
  # 国际化
  flutter_i18n: ^0.20.1
  # 刷新与分页
  pull_to_refresh: ^1.6.2
  # 交错网格
  flutter_staggered_grid_view: ^0.3.2
  # 二维码
  qr_flutter: ^3.2.0
  # 二维码扫描
  # barcode_scan: any
  # 图片选择
  image_picker: ^0.6.0+3
  #保存文件或图片到本地: https://pub.dev/packages/gallery_saver
  image_gallery_saver: any
  #权限管理
  permission_handler: any
  # 短信sdk
  #mobsms: ^1.1.0
  mobsms:
    git:
      url: https://github.com/lvpeng0412/SMSSDK-for-Flutter
  # 富文本: https://pub.dev/packages/flutter_html
  flutter_html: ^1.0.2
  # 图片查看器: https://pub.dev/packages/photo_view
  # photo_view: ^0.10.2
  # 图片查看器: https://github.com/fluttercandies/extended_image/blob/master/README-ZH.md
  extended_image: ^1.5.0
  # 网络状态：https://pub.dev/packages/connectivity
  connectivity: ^0.4.9+5
  # 设置界面
  # flutter_settings_screens: ^0.2.1
  # 启动url
  url_launcher: 5.1.0
  # WebView: https://pub.dev/packages/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.11
  # MobPush: https://pub.dev/packages/mobpush_plugin
  mobpush_plugin: ^1.1.6
  #tags
  flutter_tags: ^0.4.9
  #虚线边框
  dotted_border: ^1.0.6
  #lottie 动画
  lottie: ^0.7.0+1
  extended_nested_scroll_view: ^2.0.0
  #友盟sdk
  umeng_sdk:
    path: ./umeng_sdk/
  # 下载器：https://pub.dev/packages/flutter_downloader
#  flutter_downloader:
#    path: ./flutter_downloader/
  # 轮播控件：https://pub.dev/packages/carousel_slider
  carousel_slider: ^2.3.1
  # 分享：https://pub.dev/packages/share
  # share: ^0.6.5+4
  # mob share sdk：https://pub.dev/packages/sharesdk_plugin
  sharesdk_plugin: ^1.2.8
  # switch: https://pub.dev/packages/flutter_switch
  flutter_switch: ^0.1.4
  # 打电话：https://pub.dev/packages/flutter_phone_direct_caller
  # flutter_phone_direct_caller:
  #   git:
  #     url: https://github.com/yanisalfian/flutter-phone-direct-caller.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  # 数据库
  moor_generator: ^3.3.1
  # json
  json_serializable: ^3.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/anim_img/
    - assets/anim/
    - assets/img/
    - assets/str/
  fonts:
    - family: YouSheBiaoTiHei
      fonts:
        - asset: assets/font/YouSheBiaoTiHei.ttf
    - family: DroidSans
      fonts:
        - asset: assets/font/DroidSans.ttf

#flutter_intl:
#  enabled: true

**Comment by lvpeng0412** [comment]
`name: zdd_wallet_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+76

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # 动画
  flare_flutter: ^2.0.6
  # 消息传递
  event_bus: ^1.1.1
  # 路由
  fluro: ^1.7.3
  provider: ^4.3.2+2
  # 网络库
  dio: ^3.0.10
  # 字符串格式化
  sprintf: ^4.1.0
  # 手机信息
  package_info: ^0.4.3+2
  # https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # 偏好保存
  shared_preferences: ^0.5.10
  sp_util: ^1.0.1
  # toast
  oktoast: ^2.3.2
  # flutter_lifecycle_state: ^1.0.0
  uuid: ^2.0.2
  # ntp: ^1.0.4
  path_provider: ^1.6.14
  # 图片库(带缓存)
  cached_network_image: ^2.3.2
  # 数据库orm
  moor: ^3.1.0
  moor_ffi: ^0.8.0
  sqlite3_flutter_libs: ^0.2.0
  # json注解
  json_annotation: ^3.0.1
  # 高精度货币结算
  decimal: ^0.3.0
  # 框架
  fish_redux: ^0.3.4
  # 无限滚动
  # flutter_swiper: ^1.1.6
  transformer_page_view: 0.1.6
  # 国际化
  flutter_i18n: ^0.20.1
  # 刷新与分页
  pull_to_refresh: ^1.6.2
  # 交错网格
  flutter_staggered_grid_view: ^0.3.2
  # 二维码
  qr_flutter: ^3.2.0
  # 二维码扫描
  # barcode_scan: any
  # 图片选择
  image_picker: ^0.6.0+3
  #保存文件或图片到本地: https://pub.dev/packages/gallery_saver
  image_gallery_saver: any
  #权限管理
  permission_handler: any
  # 短信sdk
  #mobsms: ^1.1.0
  mobsms:
    git:
      url: https://github.com/lvpeng0412/SMSSDK-for-Flutter
  # 富文本: https://pub.dev/packages/flutter_html
  flutter_html: ^1.0.2
  # 图片查看器: https://pub.dev/packages/photo_view
  # photo_view: ^0.10.2
  # 图片查看器: https://github.com/fluttercandies/extended_image/blob/master/README-ZH.md
  extended_image: ^1.5.0
  # 网络状态：https://pub.dev/packages/connectivity
  connectivity: ^0.4.9+5
  # 设置界面
  # flutter_settings_screens: ^0.2.1
  # 启动url
  url_launcher: 5.1.0
  # WebView: https://pub.dev/packages/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.11
  # MobPush: https://pub.dev/packages/mobpush_plugin
  mobpush_plugin: ^1.1.6
  #tags
  flutter_tags: ^0.4.9
  #虚线边框
  dotted_border: ^1.0.6
  #lottie 动画
  lottie: ^0.7.0+1
  extended_nested_scroll_view: ^2.0.0
  #友盟sdk
  umeng_sdk:
    path: ./umeng_sdk/
  # 下载器：https://pub.dev/packages/flutter_downloader
#  flutter_downloader:
#    path: ./flutter_downloader/
  # 轮播控件：https://pub.dev/packages/carousel_slider
  carousel_slider: ^2.3.1
  # 分享：https://pub.dev/packages/share
  # share: ^0.6.5+4
  # mob share sdk：https://pub.dev/packages/sharesdk_plugin
  sharesdk_plugin: ^1.2.8
  # switch: https://pub.dev/packages/flutter_switch
  flutter_switch: ^0.1.4
  # 打电话：https://pub.dev/packages/flutter_phone_direct_caller
  # flutter_phone_direct_caller:
  #   git:
  #     url: https://github.com/yanisalfian/flutter-phone-direct-caller.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  # 数据库
  moor_generator: ^3.3.1
  # json
  json_serializable: ^3.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/anim_img/
    - assets/anim/
    - assets/img/
    - assets/str/
  fonts:
    - family: YouSheBiaoTiHei
      fonts:
        - asset: assets/font/YouSheBiaoTiHei.ttf
    - family: DroidSans
      fonts:
        - asset: assets/font/DroidSans.ttf

#flutter_intl:
#  enabled: true
`

**Comment by lvpeng0412** [comment]
[pubspec.yaml.zip](https://github.com/flutter/flutter/files/5780117/pubspec.yaml.zip)

**Comment by lvpeng0412** [comment]
I create a new flutter project use the pubspec.yaml,run ok. I tried several other projects without any problems, but this is the case with this project

**Comment by lvpeng0412** [comment]
@darshankawar

**Comment by darshankawar** [comment]
@lvpeng0412 
Try to run `flutter clean` or `flutter pub cache repair` and then try again.
If issue persists, provide `flutter run --verbose` log.

**Comment by lvpeng0412** [comment]
Thank you. I solved the problem in the way you said
