### ISSUE TITLE
Flutter issue

### ISSUE THREAD

**Issue by parthapaul** [flutter/flutter#73385]
Flutter config: Exception: Cannot run program "C:\flutter\bin\flutter.bat" (in directory "C:\flutter"): CreateProcess error=2, The system cannot find the file specified

**Comment by pedromassangocode** [comment]
Hi @parthapaul 
Can you please provide your `flutter doctor -v`, the command that caused this issue and complete logs?

This may be an unrelated Flutter issue thought, please see [this](https://stackoverflow.com/questions/19874546/createprocess-error-2-the-system-cannot-find-the-file-specified-android-studio).

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
