### ISSUE TITLE
Move mac_ios tests from staging to prod

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#73392]
DeviceLab mac ios tests have been running and passing consistently for a few weeks now. We will start moving them to prod with the following steps:

* Move flutter_ios_staging.py bot config file to prod by copying it to flutter_ios.py.
* Add mac 6,7,8 and 11 to flutter staging pool.
* Request 10 mac machines from the fuchsia ops to replace old machines.
* Wait for salt configurations to propagate from staging to prod.
* Move all the test beds from the staging pool to prod.
* Move all the tests to the flutter infra prod devicelab configuration.

**Comment by godofredoc** [comment]
There is a problem with salt states: @yusufm is looking at that problem

**Comment by yusufm** [comment]
The line of template code in the sls file that gets the gid for the group runs first. Which means that the group doesn't yet exist (since its created in that sls file itself), so it fails. We need to ensure that the group is created first before this code runs.

**Comment by godofredoc** [comment]
We also need to use fixed installations of xcode to remove the 10+ minutes overhead when the caches are cold.

**Comment by godofredoc** [comment]
This is complete.
