### ISSUE TITLE
[web] Flutter Web app takes more time to execute in debug mode.

### ISSUE THREAD

**Issue by dillibabun** [flutter/flutter#73408]
I have a existing plugin which supports Android and iOS. Now, i have tried to provide a web support. So, i followed the steps mentioned here,
https://flutter.dev/docs/get-started/web 
It takes more time to run the app in chrome.

In console of chrome, i could see following message.

<details>
<summary>logs</summary>

```bash
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/web_entrypoint.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer_example/generated_plugin_registrant.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter_web_plugins/src/plugin_registry.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer_example/main.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer_web/src/web/syncfusion_flutter_pdfviewer_web.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/services/system_channels.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/debug.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/widgets/icon.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer/src/control/scroll_head.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/material/colors.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer_web/src/web/resources/document_repository.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/material/app.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/syncfusion_flutter_pdfviewer_web/src/web/resources/page_repository.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/serialization.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/object.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/synchronous_future.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/scheduler/binding.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/change_notifier.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/licenses.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/scheduler/priority.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/_isolates_web.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/binding.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/consolidate_response.dart.lib.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://localhost:53829/packages/flutter/src/foundation/print.dart.lib.js.map: Load canceled due to load timeout
```
</details>

Flutter information:

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\xx\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\xx\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.31.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
Hi @dillibabun 
Can you please provide  your `flutter run -d chrome --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by dillibabun** [comment]
E:\testApp\exa
mple>flutter run -d chrome --verbose
[ +119 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] executing: [C:\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +61 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] 1.25.0-8.1.pre
[  +69 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +91 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] executing: C:\Users\DilliBabuN\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +212 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +128 ms] executing: C:\Users\DilliBabuN\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +26 ms] Skipping pub get: version match.
[  +64 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +29 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +5 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +5 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +49 ms] Found plugin myOldPlugin at
E:\testApp\
[   +4 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[ +216 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +19 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +3 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +4 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +42 ms] Found plugin myOldPlugin at
E:\testApp\
[   +3 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[  +16 ms] Generating
E:\testApp\exa
mple\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +97 ms] List of devices attached
[  +72 ms] List of devices attached
[  +83 ms] Launching lib\main.dart on Chrome in debug mode...
[ +145 ms] Updating assets
[ +177 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun.
for more information see #56466.
[   +6 ms] Waiting for connection from debug service on Chrome...
[  +23 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +11 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +2 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +3 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +32 ms] Found plugin myOldPlugin at
E:\testApp\
[   +3 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[  +25 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +17 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +2 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +3 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +29 ms] Found plugin myOldPlugin at
E:\testApp\
[   +3 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[ +243 ms] <- reset
[  +13 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata --output-dill
C:\Users\DILLIB~1\AppData\Local\Temp\flutter_tools.4e646685\flutter_tool.167ef0f9\app.dill
--libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
E:\testApp\exa
mple\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\DILLIB~1\AppData\Local\Temp\flutter_tools.4e646685\flutter_tools.6becda57 --filesystem-scheme
org-dartlang-app --initialize-from-dill build\fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill
--platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+53806 ms] Waiting for connection from debug service on Chrome... (completed in 54.2s)
[   +2 ms] Synced 134.2MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+1921066 ms] Using
[+11743 ms] [CHROME]:
[  +19 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:53401/devtools/browser/3421199d-90ce-4cf1-8307-6dd8b7dd3a61
[+1553 ms] DwdsInjector: Received request for entrypoint at
http://localhost:51381/main_module.bootstrap.js
[  +13 ms] MetadataProvider: Loading debug metadata...
[  +27 ms] MetadataProvider: Loaded debug metadata
[  +23 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:51381/main_module.bootstrap.js
[+2236619 ms] "flutter run" took 4,226,899ms.
[  +10 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly
establish a
           connection, for example due to a firewall.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _ResidentWebRunner.run
(package:flutter_tools/src/isolated/resident_web_runner.dart:548:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:24)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[ +270 ms] ensureAnalyticsSent: 265ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +326 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

E:\testApp\exa
mple>flutter run -d chrome --verbose
[ +223 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +123 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +2 ms] executing: [C:\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +82 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[   +1 ms] 1.25.0-8.1.pre
[  +95 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +68 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +136 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] beta
[ +111 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +149 ms] executing: C:\Users\DilliBabuN\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +88 ms] List of devices attached
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +196 ms] Skipping pub get: version match.
[  +72 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +39 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +7 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +5 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +8 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +66 ms] Found plugin myOldPlugin at
E:\testApp\
[   +5 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[ +317 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +35 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[  +18 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +22 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[  +10 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +81 ms] Found plugin myOldPlugin at
E:\testApp\
[  +20 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[  +20 ms] Generating
E:\testApp\exa
mple\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +293 ms] Launching lib\main.dart on Chrome in debug mode...
[ +275 ms] Updating assets
[ +286 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun.
for more information see #56466.
[   +9 ms] Waiting for connection from debug service on Chrome...
[  +23 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +14 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +2 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +5 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +36 ms] Found plugin myOldPlugin at
E:\testApp\
[   +2 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[  +21 ms] Found plugin device_info at C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +18 ms] Found plugin path_provider at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +2 ms] Found plugin path_provider_linux at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[   +4 ms] Found plugin path_provider_windows at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +25 ms] Found plugin myOldPlugin at
E:\testApp\
[   +2 ms] Found plugin myOldPlugin_web at
E:\testApp_web
\
[ +119 ms] <- reset
[  +24 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata --output-dill
C:\Users\DILLIB~1\AppData\Local\Temp\flutter_tools.f133ee30\flutter_tool.be59831e\app.dill
--libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
E:\testApp\exa
mple\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\DILLIB~1\AppData\Local\Temp\flutter_tools.f133ee30\flutter_tools.3fb5e877 --filesystem-scheme
org-dartlang-app --initialize-from-dill build\fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill
--platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +23 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+84343 ms] Waiting for connection from debug service on Chrome... (completed in 84.7s)
[   +2 ms] Synced 134.2MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill

**Comment by TahaTesser** [comment]
Hi @dillibabun 
To better address the issue, Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
