### ISSUE TITLE
optimization defaultHitTestChildren of RenderBoxContainerDefaultsMixin

### ISSUE THREAD

**Issue by answershuto** [flutter/flutter#73401]
Is it possible to optimize here when Offset is (0,0) to avoid unnecessary calculations?

https://github.com/flutter/flutter/blob/d0e9959a46e95b88572d38a3ecf2f589f042f64f/packages/flutter/lib/src/rendering/box.dart#L2760

offset: Offset(0,0) == childParentData.offset ? null : childParentData.offset

**Comment by darshankawar** [comment]
@answershuto 
Can you elaborate on the issue by providing a detailed description ? If it's a feature request, please provide a use case and proposal as how it will resolve your issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
