### ISSUE TITLE
Make SurfaceView work with TalkBack when the status bar color is transparent.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#73413]
See https://github.com/flutter/flutter/issues/33811 for context

In the new Android embedding, using a SurfaceView when setting

```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle( 
  statusBarColor: Colors.transparent, 
));
```

i.e. `activity.getWindow().setNavigationBarColor(0)`

breaks TalkBack highlighting.

Using a TextureView for this purposes is a performance hit that we'd like to avoid. We should see if we can somehow get TalkBack to work without requiring a TextureView where it would otherwise not be needed.

One suggestion from the Android team is to look at using the `gatherTransparentRegion` override on `SurfaceView`, but it's not entirely clear if or how this would help yet.

**Comment by dnfield** [comment]
```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle( 
  statusBarColor: Color(0x01000000), 
));
```

avoids this with a nearly transparent statusbar.

**Comment by michael-woolsey** [comment]
Thank you @dnfield! The solution of `SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Color(0x01000000)));` works for me until there is a better solution.
