### ISSUE TITLE
add option for pub deps command to show supported platforms

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#73415]
## Use case

When developing for multiple target platforms (especially desktop apps) we have to track down individual plugins that have platform-specific code. Currently you have to go to pub.dev and check descriptions for each plugin one by one or try to build for each platform and see where it fail (and then chase plugins that have needed platform support).

## Proposal

It would be really helpful if the `pub deps` would show the platforms listed in plugins' pubspecs like:

```
my_app 1.0
|-- csv 4.1.0 [all]
|-- cupertino_icons 1.0.0 [all]
|-- firebase_analytics 6.3.0 [android,ios,web]
     ...
|-- firebase_core 0.5.3 [android,ios,macos,web]
     ...
|-- flutter_blue 7.3.6 [android,ios,macos]
     ...
|-- mp_chart 0.3.0 [all]
|   |-- flutter... [all]
|   |-- image_gallery_saver 1.6.7 [android,ios]
    ...
|-- path_provider 1.6.24 [android,ios,macos,linux,windows]
    ...
```

**Comment by jmagman** [comment]
This is a pub feature request, please file at https://github.com/dart-lang/pub/.

**Comment by ekuleshov** [comment]
For the record, the `flutter pub` behaves differently from `dart pub`, i.e. not all options supported by the former and this feature is more relevant to fullter.
