### ISSUE TITLE
command generated archive using 'flutter build ipa' is missing dSYM files

### ISSUE THREAD

**Issue by oklimberg** [flutter/flutter#73414]
While trying to automate the distribution of my app as much as possible, I stumbled across the command `flutter build ipa` which seems more intuitive instead of calling build_ios_app in fastlane. However, in contrast to archives generated with Xcode or build_ios_app in fastlane, the flutter version does not contain the previously generated dSYM files.

I further noticed, that all commands of xcodebuild use the project file instead of the workspace file, which seems odd to me.
Since I cannot build the app within Xcode using only the project file, i would assume, the Flutter CLI would also encounter problems when using the project file instead of the workspace file.

## Steps to Reproduce

1. create a new project in your favorite IDE
2. execute `flutter build ipa`
3. the dSYM folder of the generated archive under `build/ios/archive` is empty

## Logs

<details>
<summary>Logs</summary>

```
Could not attach flutter output due to length restriction of the issue body
```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-DE)
    • Flutter version 1.24.0-10.2.pre at /Users/me/sdk/flutter
    • Framework revision 022b333a08 (7 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Users/me/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/me/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/me/Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code
    • VS Code at /Users/me/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@oklimberg 
`flutter build ipa` gives me `Could not find a subcommand named "ipa" for "flutter build".`.
Is this specific to fastlane ?

**Comment by oklimberg** [comment]
Hi, no this not Gastland specific. Which flutter version did you use? My attached flutter doctor output states, I’m using a beta version

**Comment by darshankawar** [comment]
@oklimberg 
Tried on beta 1.25 by running `flutter build ipa` for which I see the `Runner.xcarchive` file generated.

```
Running pod install...                                              3.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        19.0s
Xcode archive done.                                         86.2s
Built /Users/dhs/Documents/NCFlutter/testapp/build/ios/archive/Runner.xcarchive.
```

<img width="568" alt="Screenshot 2021-01-07 at 4 15 40 PM" src="https://user-images.githubusercontent.com/67046386/103883845-bfd39b80-5103-11eb-8e89-860ce7b24f85.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

```

</details>

**Comment by oklimberg** [comment]
As I said, it is not about the archive not being build. The build archive is missing the debug symbols!
 Right click on the archive, select show package contents, and confirm, the `dSYMs` folder is empty.
 If the archive would have been build using Xcode, the dSYM folder within the archive contains the `Runner.app.dSYM`

**Comment by darshankawar** [comment]
@oklimberg 
ah I see. 

<img width="481" alt="Screenshot 2021-01-07 at 4 59 26 PM" src="https://user-images.githubusercontent.com/67046386/103887840-be0cd680-5109-11eb-899e-07d485bf4ada.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision b0a2299859 (2 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!


```

</details>

**Comment by oklimberg** [comment]
After further investigation, specifying the BUILD_DIR variable while calling xcodebuild causes this behaviour.
This is the current build command (I removed my developer team):
`xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES DEVELOPMENT_TEAM=XXXXXX -allowProvisioningUpdates -allowProvisioningDeviceRegistration -workspace Runner.xcworkspace 		-scheme Runner BUILD_DIR=/Users/me/projects/flutter/sampleapp/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/yc/t07gh0l13c163ry7fn5446_80000gn/T/flutter_tools.vPwN4j/flutter_build_log_pipe.MCJKef/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -archivePath /Users/me/projects/flutter/sampleapp/build/ios/archive/Runner archive`

removing `BUILD_DIR=/Users/me/projects/flutter/sampleapp/build/ios` will use the default Xcode build directory and the generated will contain the dSYM files.
Maybe by specifying BUILD_DIR additional variables need to be set

**Comment by jmagman** [comment]
@oklimberg thanks for your detailed issue and `BUILD_DIR` investigation!

`flutter build ipa` generates the dSYM to `/build/ios/Release-iphoneos/MyApp.app.dSYM` but it's not copying to the right place in the archive.
When it works (without `BUILD_DIR`) `DWARF_DSYM_FOLDER_PATH` looks like
```
<DerivedData>/Runner-asrszkthjhuqfdcyidwleqxjtniu/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos
```
with `BUILD_DIR` it's 
```
DWARF_DSYM_FOLDER_PATH\=/Users/magder/Projects/flutter/dev/integration_tests/flutter_gallery/build/ios/Release-iphoneos
```
which is correct--that's where the dsymutil puts it and it's definitely generated there.

I tried setting `SYMROOT` `OBJROOT` and `-derivedDataPath` but none of that helped.  I don't really why it doesn't just copy from wherever `DWARF_DSYM_FOLDER_PATH` is, but I bet this is a very untested Xcode use case.

The easiest thing to do is to leave off `BUILD_DIR` for archive...

**Comment by oklimberg** [comment]
In that case, the command `flutter clean` should probably also call `xcodebuild clean` To make sure, all used build locations get cleaned.
