### ISSUE TITLE
Add a memory related benchmark with a Rive animation

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#73431]
We have several high priority customers using Rive. We are working to reduce the memory needed in this case and should have a benchmark tracking it.

**Comment by hamedtayeban22** [comment]
#73431

**Comment by hamedtayeban22** [comment]
@hamedtayeban22

**Comment by dnfield** [comment]
@hamedtayeban22 if you wish to subscribe to the issue you can do so by clicking the subscribe button in the right hand column: 
![image](https://user-images.githubusercontent.com/8620741/103827228-60a35780-502d-11eb-99ca-9ff576e0c77e.png)

Please do not add comments with no real content in them to issues.

**Comment by hamedtayeban22** [comment]
@hamedtayeban22

**Comment by hamedtayeban22** [comment]
@hamedtayeban22 
#73421

**Comment by hamedtayeban22** [comment]
@hamedtayeban22 #73431

**Comment by hamedtayeban22** [comment]
#73431

**Comment by hamedtayeban22** [comment]
@hamedtayeban22
