### ISSUE TITLE
Make the cocoon filtering update and read some query parameter to allow for GETting/sharing links to it

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#73432]
e.g. https://flutter-dashboard.appspot.com/#/build?filter=*memory* to show benchmarks with memory in the name.

/cc @flar who developed the feature
/cc @CaseyHillers who might have some good ideas about this.

**Comment by keyonghan** [comment]
The `Setting` filtering logic does this work. Or are you specifically looking for url filtering?

![Screen Shot 2022-04-26 at 9 39 41 AM](https://user-images.githubusercontent.com/54558023/165350182-49e4a15a-14c1-4fb8-8da1-ce6f69dcfd6f.png)

**Comment by dnfield** [comment]
Right now there's no way to link to a persistent filtered view - you always have to load the whole thing, click the settings icon, type your filter, and click apply.

I'd like to be able to have that preserved in the URL so I could just quickly navigate to a window that has the filters I like.

**Comment by CaseyHillers** [comment]
I used the settings dialog, clicked apply, and the url updated with https://flutter-dashboard.appspot.com/#/build?taskFilter=memory&repo=flutter&branch=master

Does this work for you? Is there a specific field not working?

**Comment by dnfield** [comment]
Ah!  I'm pretty sure that when I filed this bug that did not work, but sounds like now it does.
