### ISSUE TITLE
Show Tooltip onTap Instead of onLongPress

### ISSUE THREAD

**Issue by kjmj** [flutter/flutter#73445]
## Use Case
I am using the [Tooltip widget](https://api.flutter.dev/flutter/material/Tooltip-class.html) in one of my flutter projects and would like to show the tooltip `onTap` instead of `onLongPress`.

## Proposal
Here are some suggestions on how a developer could choose to show the tooltip `onTap` instead of `onLongPress`.

**Option 1**

Let the developer specify if they want to use `onTap` instead of `onLongPress`.
```
Tooltip(
  message: "Hello World",
  child: Text("Foo"),
  showOnTap: true, // add this property, defaults to false
)
```

**Option 2**

Let the developer specify the `onLongPress` duration (`Duration.zero` would essentially mimic `onTap`). Not really sure if this is feasible, since I can't find anything about being able to customize the `onLongPress` duration in flutter.
```
Tooltip(
  message: "Hello World",
  child: Text("Foo"),
  longPressDuration: Duration.zero, // add this property, mimic onTap
),
```

## Final Notes
I would be more than happy to try and implement this if the flutter team thinks this is a useful feature to have. Also open to discussion on how this might work from a developers perspective.

**Comment by darshankawar** [comment]
@kjmj 
Check out [this](https://stackoverflow.com/a/59967908) SO solution and see if it answers your issue.

**Comment by kjmj** [comment]
@darshankawar 
That looks like a reasonable solution. I'm still pretty new to open source, but I want to contribute. Can I try to implement this in the official flutter Tooltip widget and submit a PR? Just want to get approval/revise my proposal before writing code.

**Comment by Abhishek01039** [comment]
I guess the first scenario is good for developers. @kjmj
