### ISSUE TITLE
LUCI test results have no stdout

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73446]
Step 17 `run module_test_ios` is missing stdout.  Though the test succeeded it's often important to be able to read test output, often to compare it to a succeeding test.
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/1223/steps?succeeded=true&debug=false

Another example, `run build_aar_module_test` is missing stdout:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_aar_module_test/1187/steps?succeeded=true&debug=false

Another, `run gradle_plugin_light_apk_test` is missing stdout:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20gradle_plugin_light_apk_test/1186/steps?succeeded=true&debug=false

**Comment by godofredoc** [comment]
Those steps are getting an empty command that's the reason they are showing up as noop.

**Comment by godofredoc** [comment]
Fix under review:
https://flutter-review.googlesource.com/c/recipes/+/9641
