### ISSUE TITLE
[test infra] Flutter web HHH bot does not load correct SDK outline

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#73444]
It manifests as wrong kernel version every time the kernel version is updated but really just means we are loading incorrect SDK for the tests, so the bot is not actually testing against the latest SDK head. The issue reappears during SDK rolls and prevents us from detecting SDK changes that might break flutter's debugging features for web (for example, expression evaluation in the debugger).

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-engine-linux-web_tests/1431/overview

@mkustermann 's  hypothesis is that flutter/flutter code doesn't fully support local engine correctly. See some discussion on [1].

[0] https://github.com/flutter/flutter/pull/71721 
[1] https://github.com/flutter/flutter/pull/71721#issuecomment-743218994

Requires:

https://github.com/flutter/flutter/issues/72368

Related:

The issue was discovered in non-HHH bot but we moved the web tests to web HHH since then:
https://github.com/flutter/flutter/issues/69711

**Comment by sigmundch** [comment]
On a related note, after https://github.com/dart-lang/sdk/commit/f376642572b9890b78dabab8d0b70444653ca881 we should start reporting what is the .dill file that has the mismatched version. The fact that the log above doesn't show this detail is also a sign that we may be using a different version of the CFE than the one at the tip of tree.

**Comment by godofredoc** [comment]
@athomas FYI

**Comment by dcharkes** [comment]
This is still failing when the kernel version gets bumped.

Latest incarnation: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8851986851676848432/+/steps/flutter_test_tool_tests/0/stdout

**Comment by yjbanov** [comment]
May be related: we recently fixed an issue where the Flutter SDK wasn't picking up the correct Engine in tests (https://github.com/flutter/flutter/issues/78072). The issue was that `--local-engine` was passed the full path to the engine instead of splitting it into `--local-engine-src-path=/PATH_TO_ENGINE/src --local-engine=BUILD_VARIANT` and the Flutter SDK silently fell back to the cached engine, making it look like it runs all tests successfully. @jmagman fixed it in https://github.com/flutter/flutter/pull/78496, so now we pick up the locally built engine.

**Comment by annagrin** [comment]
@yjbanov the problem here is a bit different AFAIK - the tests are not running with local engine because if they do some tests are broken due to requiring a different build of the local engine. See the current effort to solve this here:

https://github.com/flutter/flutter/issues/72368

**Comment by annagrin** [comment]
@sigmundch I believe this is fixed now?

**Comment by sigmundch** [comment]
Yes, the fix landed in https://github.com/flutter/flutter/pull/83308
