### ISSUE TITLE
Doesn't load new code in IDEA

### ISSUE THREAD

**Issue by rantianhua** [flutter/flutter#7344]
I create a new flutter app in IDEA, firstly, there are default codes in main.dart, and I ran it normally in my Android phone. I changed main.dart with codes showed in [Tutorial](https://flutter.io/widgets-intro/). However, after I ran again, the content didn't change any.

my codes in main.dart were : 
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: "Jean's app",
      home: new MyScaffold()
  ));
}

class MyAppBar extends StatelessWidget {

  MyAppBar({this.title});

  final Widget title;

  @override
  Widget build(BuildContext context) {
    return new Container(
        height: 56.0,
        padding: const EdgeInsets.symmetric(horizontal: 8.0),
        decoration: new BoxDecoration(backgroundColor: Colors.blue[500]),
        child: new Row(
            children: <Widget>[
              new IconButton(
                  icon: new Icon(Icons.menu),
                  tooltip: 'Navigation Menu',
                  onPressed: null
              ),
              new Flexible(
                  child: title
              ),
              new IconButton(
                  icon: new Icon(Icons.search),
                  tooltip: 'Search',
                  onPressed: null
              )
            ]
        )
    );
  }
}

class MyScaffold extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new Material(
        child: new Column(
            children: <Widget>[
              new AppBar(
                  title: new Text(
                      'Example',
                      style: Theme.of(context).primaryTextTheme.title
                  )
              ),
              new Flexible(
                  child: new Center(
                      child: new Text('Hello Jean')
                  )
              )
            ]
        )
    );
  }
}
```
and the screen started is : 
![screen](https://cloud.githubusercontent.com/assets/7328707/21682128/c92f8bdc-d38d-11e6-91f6-2dcc87738366.jpeg)

**Comment by sethladd** [comment]
Thanks for the report! Can you provide more details:

* What exact steps did you use?
* Did you save the file before running again?
* Which button/buttons/keys did you use to run the app again?
* What happens if you use our CLI (`flutter run`) to run and reload the app?

**Comment by rantianhua** [comment]
- Firstly, I installed flutter sdk using `git clone https://github.com/flutter/flutter.git` command, and then ran command `export PATH=`pwd`/flutter/bin:$PATH` to export flutter, after this, I ran `flutter doctor`, and finally all it worked. I wanted to create a project in IDEA, then I installed Dart and Flutter plugins for IDEA, my IDEA information is:
============
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 18, 2016
Licensed to lan yu
Subscription is active until November 23, 2017
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
============
At last, the problem I've described occurred.

- Yes, I've saved main.dart before running again.
- every time I ran the app use __run__ green button instead of debug button.
- I've tried CLI(`flutter run`), unfortunately, the situation had not changed.

**Comment by rantianhua** [comment]
@sethladd

**Comment by sethladd** [comment]
Thank you for the detailed steps!

Perhaps @devoncarew and @mit-mit can take a look?

**Comment by devoncarew** [comment]
Sure, will do.

**Comment by devoncarew** [comment]
@rantianhua, can you try to things:

- after the app first runs, try doing a hot reload (available in the UI) and see if the new code is loaded
- can you run `adb logcat` from the cli in parallel to starting the app, and look for any exceptions in the output?

Thanks!

**Comment by aleki** [comment]
Try to remove `build` folder and run app again.

**Comment by rantianhua** [comment]
@devoncarew I do a hot reload after first run, but the screen becomes full red, and the log info are as  follows : 

Uninstalling old version...
I/flutter ( 9606): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9606): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter ( 9606): '/Users/rantianhua/IdeaProjects/HelloFlutter/lib/main.dart': malformed type: line 24: type
I/flutter ( 9606): 'MyHomePage' is not loaded
I/flutter ( 9606):         home : new MyHomePage(title : "Flutter Demo Home Page"),
I/flutter ( 9606):                    ^
I/flutter ( 9606): When the exception was thrown, this was the stack:
I/flutter ( 9606): #0      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2895:23)
I/flutter ( 9606): #1      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter ( 9606): #2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1769:33)
I/flutter ( 9606): #3      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:313:20)
I/flutter ( 9606): #4      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:165:5)
I/flutter ( 9606): #5      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:653:15)
I/flutter ( 9606): #6      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:588:9)
I/flutter ( 9606): #7      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.reassembleApplication (package:flutter/src/rendering/binding.dart:231:5)
I/flutter ( 9606): #8      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.reassembleApplication (package:flutter/src/widgets/binding.dart:362:32)
I/flutter ( 9606): #9      BindingBase.registerSignalServiceExtension.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/foundation/binding.dart:151)
I/flutter ( 9606): (elided 3 frames from package dart:async)
I/flutter ( 9606): ════════════════════════════════════════════════════════════════════════════════════════════════════

Reloaded in 3247ms.
Reloaded 377 of 393 libraries.
Exception from flutter run: FormatException: Bad UTF-8 encoding 0xd
dart:convert/utf.dart 483                                  _Utf8Decoder.convert
dart:convert/string_conversion.dart 333                    _Utf8ConversionSink.addSlice
dart:convert/string_conversion.dart 329                    _Utf8ConversionSink.add
dart:convert/chunked_conversion.dart 92                    _ConverterStreamEventSink.add
dart:async/stream_transformers.dart 119                    _SinkTransformerStreamSubscription._handleData
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
dart:async/zone.dart 1158                                  _rootRunUnary
dart:async/zone.dart 1037                                  _CustomZone.runUnary
dart:async/zone.dart 932                                   _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 331                            _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 258                            _BufferingStreamSubscription._add
dart:async/stream_controller.dart 768                      _StreamController&&_SyncStreamControllerDispatch._sendData
dart:async/stream_controller.dart 635                      _StreamController._add
dart:async/stream_controller.dart 581                      _StreamController.add
dart:io-patch/socket_patch.dart 1680                       _Socket._onData
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
dart:async/zone.dart 1162                                  _rootRunUnary
dart:async/zone.dart 1037                                  _CustomZone.runUnary
dart:async/zone.dart 932                                   _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 331                            _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 258                            _BufferingStreamSubscription._add
dart:async/stream_controller.dart 768                      _StreamController&&_SyncStreamControllerDispatch._sendData
dart:async/stream_controller.dart 635                      _StreamController._add
dart:async/stream_controller.dart 581                      _StreamController.add
dart:io-patch/socket_patch.dart 1247                       _RawSocket._RawSocket.<fn>
dart:io-patch/socket_patch.dart 781                        _NativeSocket.issueReadEvent.issue
dart:async/schedule_microtask.dart 41                      _microtaskLoop
dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage

**Comment by rantianhua** [comment]
@aleki I remove `build` folder and then I run the project, but what I can see in the device screen is full red color, nothing anymore, and I'm confused by the log information: 

Launching lib/main.dart on m2 in debug mode...
I/flutter (10402): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10402): The following assertion was thrown building LayoutBuilder:
I/flutter (10402): 'package:flutter/src/material/app_bar.dart': Failed assertion: line 360: 'constraints.maxHeight <
I/flutter (10402): double.INFINITY' is not true.
I/flutter (10402): When the exception was thrown, this was the stack:
I/flutter (10402): #2      AppBar._buildForSize (package:flutter/src/material/app_bar.dart:360)
I/flutter (10402): #3      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:112)
I/flutter (10402): #4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1750)
I/flutter (10402): #5      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:108)
I/flutter (10402): #6      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1834)
I/flutter (10402): #7      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:975)
I/flutter (10402): #8      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1834)
I/flutter (10402): #9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207)
I/flutter (10402): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:477)
I/flutter (10402): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #13     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #15     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #17     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #26     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2347)
I/flutter (10402): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #28     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #30     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354)
I/flutter (10402): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #32     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
I/flutter (10402): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1736)
I/flutter (10402): #42     RenderView.performLayout (package:flutter/src/rendering/view.dart:114)
I/flutter (10402): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1612)
I/flutter (10402): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953)
I/flutter (10402): #45     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:220)
I/flutter (10402): #46     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:314)
I/flutter (10402): #47     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:165)
I/flutter (10402): #48     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:653)
I/flutter (10402): #49     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:588)
I/flutter (10402): #50     runApp (package:flutter/src/widgets/binding.dart:386)
I/flutter (10402): #51     main (/Users/rantianhua/IdeaProjects/HelloFlutter/lib/main.dart:4)
I/flutter (10402): #52     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
I/flutter (10402): #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

the cods in /lib/main.dart are the same as showed in the first question.

**Comment by mit-mit** [comment]
@rantianhua, just to make sure, does your code pass code analysis? You can run `flutter analyze` in the main directory of your app to check.

**Comment by aleki** [comment]
@rantianhua, you should use `MyAppBar` instead of `AppBar` on the 35 line.

**Comment by aleki** [comment]
@sethladd  I think this issue can be closed, as it was a code problem.

**Comment by rantianhua** [comment]
@aleki  Yes, you are right, It's my fault, but there is a truth that I must remove `build` folder to see my code change, and the `hot reload` doesn't work either.

**Comment by Hixie** [comment]
@rantianhua That I believe should be fixed now? Try pulling the latest code. If it is still broken please file a bug.

**Comment by rantianhua** [comment]
@Hixie `hot reload` doesn't work yet, if I want to see my code changes in the phone, the only way is to remove `build` folder and run again. I will try your advice later, but it will takes some time. I will tell you the result after that. At last, I don't know how to file a bug, in this issue or sending a email, or there is a specific site to do it? Thanks!

**Comment by mit-mit** [comment]
@rantianhua, clarifying question: Does it fail to reload for you just with your own app code, and also with the template code you get when you create a new app?

In other words, does this work for you?

In a termnial:
1. Run `flutter doctor` and make sure there are no error
1. Run `flutter create testapp`
1. `cd testapp`
1. `flutter run`
1. Open `lib\main.dart` in a text editor, and change line 24 from `MyHomePage(title: 'Flutter Demo Home Page')` to `MyHomePage(title: 'Flutter Test Home Page')`
1. Save the changes to `main.dart`
1. In the terminal, press `r` to reload
1. See if the titlebar changed on the target

**Comment by sethladd** [comment]
Closing because we haven't heard back yet. But please let us know if this is still happening.

**Comment by hitanshu1** [comment]
is your problem solved... I am facing same problem

**Comment by AlexKel** [comment]
I'm also having this issue. When I first run the app (I attach to an existing native app) it loads to an old version on iOS. Then shift + 4 in the console and it loads my code. So kind of works with refreshing after the first start. I'm currently archiving the build to see if it's an issue that will be in production, as there is no way to hot reload in prod :D My flutter doctor:

**Comment by LearningCurveSL** [comment]
> Try to remove `build` folder and run app again.

Work well for me
