### ISSUE TITLE
Using the device_info plugin to package the release version always reports the problem of the gradle-wrapper version

### ISSUE THREAD

**Issue by saltFishxxx** [flutter/flutter#73450]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Translation: `Using the device_info plugin to package the release version always reports the problem of the gradle-wrapper version`

@saltFishxxx 
Please provide detailed description of the issue along with `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
