### ISSUE TITLE
performPrivateCommand -> onAppPrivateCommand @ EditableText: "_CastError (Null check operator used on a null value)"

### ISSUE THREAD

**Issue by GefaketHD** [flutter/flutter#73456]
## Steps to Reproduce

I am kind of not sure. AFAIK I just created a TextField and (on my phsyical Android device) the keyboard reset to the initial "Page" (the one where u can put in the letters) whenever I deleted one char. Was wondering about that and after turning on debug mode to halt on every even catched exception, it showed me:
"_CastError (Null check operator used on a null value)" in line 1718:EditableTextState.performPrivateCommand --> widget.onAppPrivateCommand!

Traced from TextInput._handleTextInputInvocation -->_currentConnection!._client.performPrivateCommand(args[1]['action']... WHERE args[1]['action'] == 'Normal_Mode'

**Expected results:** 
Just delete the char without throwing any error anywhere.

**Actual results:** 
My debugger halted at described point for described reason.

<details>
  <summary>Logs</summary>

```
I/InputMethodManager(29614): startInputInner - mService.startInputOrWindowGainedFocus
W/IInputConnectionWrapper(29614): getCursorCapsMode on inactive InputConnection
```

```
[✓] Flutter (Channel unknown, 1.25.0-4.0.pre, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.25.0-4.0.pre at /home/jbadstuebner/fvm/versions/1.25.0-4.0.pre
    • Framework revision a7f5fd5360 (vor 5 Wochen), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/jbadstuebner/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • SM A320FL (mobile) • 330088969034a481 • android-arm • Android 8.0.0 (API 26)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@GefaketHD 
Are you on beta or master version, `Channel unknown, 1.25.0-4.0.pre` ?
Also, can you provide a complete minimal reproducible code sample that shows the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
