### ISSUE TITLE
Flutter app version solving failed

### ISSUE THREAD

**Issue by Phirke** [flutter/flutter#73468]
Because flutter_app depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because flutter_app depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because flutter_app depends on intl ^0.16.1, version solving failed.)

**Comment by darshankawar** [comment]
@Phirke 
What Flutter version are you on `flutter doctor -v` ? Can you also provide your `pubspec.yaml`. It seems you are using some plugins which aren't migrated to nullsafety.

**Comment by acoutts** [comment]
Similar to https://github.com/flutter/flutter/issues/72682#issuecomment-751599348

**Comment by itwondersteam** [comment]
check https://github.com/flutter/flutter/issues/70433#issuecomment-727154345

dependency_overrides:
   intl: ^0.17.0-nullsafety.2

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
