### ISSUE TITLE
Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).     at Object.f [as app] (https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js:1:16867)

### ISSUE THREAD

**Issue by bgwissam** [flutter/flutter#73460]
Flutter Web Version: 
Browser Version: Version 87.0.4280.88 (Official Build) (64-bit) Chrome 

Trying to build flutterFire web app is always causing the same error. Below is my index.html and main.dart files that are handling the initialization of the app.

Index.html

<!DOCTYPE html>
<html>
  <head>
    <base href="/" />

    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="A new Flutter project." />

    
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="web_product_unitrade" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />

    
    <link rel="icon" type="image/png" href="favicon.png" />

    <title>web_product_unitrade</title>
    <link rel="manifest" href="manifest.json" />
  </head>
  <body>
    <p id="error-element"></p>

    <script>
      if ("serviceWorker" in navigator) {
        window.addEventListener("flutter-first-frame", function () {
          navigator.serviceWorker.register("flutter_service_worker.js");
        });
      }
    </script>
    
    <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>

    
    <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-analytics.js"></script>

    
    <script src="https://www.gstatic.com/firebasejs/7.8.0/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-storage.js"></script>
    

    <script type="module">
      // import { firebaseConfig } from "/lib/configuration/firebase-config.js";
      // Initialize Firebase
      var firebaseConfig = {
      //data removed for security reasons
      };

      firebase.initializeApp(firebaseConfig);
      //firebase.analytics();
    </script>

    <script src="main.dart.js" type="application/javascript"></script>
  </body>
</html>

main.dart

Future<void> main() async {
  // WidgetsFlutterBinding.ensureInitialized();
  // await Firebase.initializeApp();
  // developer.log('${Firebase.apps.length}', name: 'main.dart');
  // FlutterError.onError = (FlutterErrorDetails details) {
  //   FlutterError.dumpErrorToConsole(details);
  // };
  runApp(App());
}

class App extends StatefulWidget {
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  final Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: _initialization,
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Container(
              child: Text('An Error Occurred'),
            );
          }
          if (snapshot.connectionState == ConnectionState.done) {
            return StreamProvider<UserData>.value(
              value: AuthService().user,
              child: MaterialApp(
                title: MAIN_TITLE,
                debugShowCheckedModeBanner: false,
                theme: ThemeData(
                    primarySwatch: Colors.amber,
                    accentColor: Colors.amber[200]),
                home: MyHomePage(
                  title: HOME_PAGE,
                ),
                routes: <String, WidgetBuilder>{
                  '/home': (BuildContext context) => new Wrapper(),
                },
              ),
            );
          }
          return MaterialApp(
            title: MAIN_TITLE,
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
                primarySwatch: Colors.red, accentColor: Colors.red[200]),
            home: Loading(),
          );
        });
  }
}

I have tried cleaning the code and building again several times, but the error persists, Is there anyway to get more details on the error from index.html?

**Comment by darshankawar** [comment]
@bgwissam 
This seems to be an issue with Flutterfire which has separate repo for tracking issues : https://github.com/FirebaseExtended/flutterfire/issues
Closing this from here.

**Comment by flutterq** [comment]
[Flutter Error : No Firebase App ‘[DEFAULT]’ has been created – call Firebase.initializeApp() in Flutter and Firebase
](https://fluttercorner.com/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in/)

**Comment by LakshithVithana** [comment]
The error is here may be the default SDK setup and configuration - 

<script src="/__/firebase/8.6.5/firebase-app.js"></script>




<script src="/__/firebase/init.js"></script>

is added and other firebase sdk services such as firebase-firestore is defining before the 
<script src="/__/firebase/8.6.5/firebase-app.js"></script>

So you need to add other services as 
<script src="/__/firebase/8.6.5/firebase-app.js"></script>
<script src="/__/firebase/8.6.5/firebase-firestore.js"></script>
etc.

if you use CDN configuration, configure other sdk services as below after the firebase-app.js
<script src="https://www.gstatic.com/firebasejs/8.6.5/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.5/firebase-firestore.js"></script>
etc.
