### ISSUE TITLE
Key object can't be find in integration test by flutter_driver 

### ISSUE THREAD

**Issue by tkmsikd** [flutter/flutter#73462]
As `flutter_test` package can find key object by `find.ByKey` class to implement widget test, I want to find key object  in integration test with `flutter_driver` package. But I only can see `find.ByValueKey` class implemented for` flutter_driver `integration test.

Is it possible to find `UniqueKey` in integration test? If not, why isn't it possible to find Key object in `flutter_driver` integration test which is possible in `flutter_test` widget test?

**Comment by darshankawar** [comment]
@tkmsikd 
Currently it doesn't seem to have `find.ByKey` property for `integration_test` plugin.

**Comment by tkmsikd** [comment]
> @tkmsikd
> Currently it doesn't seem to have `find.ByKey` property for `integration_test` plugin.
@darshankawar  Thank you for your reply.
Is there any practice to manage `UniqueKey` for integration test? If not, why does not `flutter_driver` package supports `Key` object for integration test?

**Comment by brenodt** [comment]
I may have misunderstood the issue at hand, if so, please forgive me. But, by using the new [integration testing](https://flutter.dev/docs/testing/integration-tests) workflow, you'll have access to the `WidgetTester` just like when writing widget tests.

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:<your_package_name>/main.dart' as app;
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("test foo", (WidgetTester tester) async {
      await app.main();
      await tester.pumpAndSettle();
      await tester.pump();

      final fooFinder = find.byKey(fooKey);  // fooKey is a UniqueKey declared somewhere
      expect(fooFinder, findsOneWidget);
  });
}
```

I'm using this logic with no issues in my tests.

**Comment by TahaTesser** [comment]
Hi @tkmsikd 
Please follow the above sample, it should find key for you 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
