### ISSUE TITLE
memory leaks on device but not on simulator;

### ISSUE THREAD

**Issue by lilubin1992** [flutter/flutter#73477]
a simple demo with flutter module, but exist a leak when a start the engine 
![flutter_leaks](https://user-images.githubusercontent.com/11613499/103892391-79436880-5126-11eb-90cb-8b5d5058c449.jpg)

**Comment by lilubin1992** [comment]
i detect a leaks on device with instruments, but there no leaks on simulator

**Comment by darshankawar** [comment]
@lilubin1992 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue including on which platform you are seeing leak (Android or iOS) to properly address your issue.

**Comment by lilubin1992** [comment]
> @lilubin1992
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue including on which platform you are seeing leak (Android or iOS) to properly address your issue.

the code is easy, i just create a engine in "appdelegate" and run, the flutter module is a initial module, i change nothing. the leaks is decter by xcode's instruments, the image is below

**Comment by lilubin1992** [comment]
![Uploading 5A28248F-589E-4DC3-ACD6-A20B88E77FE6.jpeg…]()

**Comment by lilubin1992** [comment]
![Uploading 57D35F41-F4BC-4C79-848D-1806611FCA03.jpeg…]()

**Comment by lilubin1992** [comment]
![E9D427CE-73E7-4680-871D-D11751F7181F](https://user-images.githubusercontent.com/11613499/103967729-8c454f80-519d-11eb-9e79-f034568602e0.jpeg)
![BD31C2CD-A4AA-4DFC-A5CD-84C1004A3D4B](https://user-images.githubusercontent.com/11613499/103967734-8f404000-519d-11eb-8f2a-81e946aa1ebf.jpeg)

**Comment by lilubin1992** [comment]
anyone can answer?

**Comment by darshankawar** [comment]
@lilubin1992 
You seem to be on older version of Flutter. Current stable version is 1.22.5. I'd recommend you to upgrade to latest version and try again to see if it works or issue persists.
If issue persists, provide a concrete minimal reproducible code sample that we can copy paste and run to see the issue.
Also, please don't post the screenshots. Provide the details in text format.
Thanks.

**Comment by lilubin1992** [comment]
other reasons, not about flutter

**Comment by zhangjk4859** [comment]
@darshankawar I just create a new project by the command `flutter create projectName` and run, that's it, no more extra code, and found a memory leak in Instruments as below 
![image](https://user-images.githubusercontent.com/13939499/110562590-c83c6700-8184-11eb-9831-c3344cc0dc88.png),should I care about it? device model is iPhone 5s
