### ISSUE TITLE
connectivity：Could not resolve com.android.tools.build:gradle:3.5.0.

### ISSUE THREAD

**Issue by Ruijiao** [flutter/flutter#73472]
A problem occurred configuring project ':connectivity'.
> Could not resolve all artifacts for configuration ':connectivity:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.0.
     Required by:
         project :connectivity
      > Could not resolve com.android.tools.build:gradle:3.5.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
               > Connection reset
> Could not get unknown property 'android' for project ':connectivity' of type org.gradle.api.Project.

current my gradle version 4.1.0

**Comment by darshankawar** [comment]
@Ruijiao 
Please provide `flutter doctor -v`, `pubspec.yaml` and `flutter run --verbose` to better address this issue.

**Comment by Ruijiao** [comment]
flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.14.6 18G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-1.0.pre at /Users/fangruijiao/software/flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/fangruijiao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/fangruijiao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)         • B91A4834-F127-4027-8F55-232A0FA0BB90 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.

**Comment by Ruijiao** [comment]
pubspec.yaml:

name: flutter_module
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^4.0.1
  cupertino_icons: ^0.1.2
  dio: ^3.0.4
  json_annotation: ^3.0.0
  shared_preferences: ^0.5.7+3
  cached_network_image: ^2.2.0+1
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.6.0
  photo_view: ^0.8.0
  flutter_easyrefresh: ^2.0.4
  pull_to_refresh: ^1.5.7
  scroll_to_index: ^1.0.5
  connectivity: ^2.0.2
  common_utils: ^1.1.3
  flutter_gifimage: ^1.0.1
  webview_flutter: 0.3.21
  url_launcher: ^5.4.10
  cookie_jar: ^1.0.1
  path_provider: ^1.6.9
  dio_cookie_manager: ^1.0.0
  pin_code_fields: ^2.4.0
  azlistview: ^0.1.2  #latest version
  flutter_slidable: "^0.5.4"
  event_bus: ^1.1.1
  flukit: ^1.0.2
  # intl: ^0.15.8
  convert_hex: ^0.1.7
  # flutter_statusbarcolor: ^0.2.3
  badges: ^1.1.1
  image_picker: ^0.6.6+4
  flutter_touch_spin: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0
  # flutter_appavailability: ^0.0.21
  device_apps: ^1.0.10

  # flutter_webview_plugin: ^0.3.11



dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
     - assets/imgs/common/
     - assets/imgs/goods/
     - assets/imgs/home/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DIN-Medium,DIN
      fonts:
        - asset: assets/fonts/DIN-Medium.otf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



  module:
    androidX: true
    androidPackage: com.msApp
    iosBundleIdentifier: com.pacage

**Comment by Ruijiao** [comment]
Plugin project :path_provider_macos not found. Please update settings.gradle.
[   +2 ms] Plugin project :connectivity_macos not found. Please update settings.gradle.
[        ] Plugin project :url_launcher_web not found. Please update settings.gradle.
[+7296 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] A problem occurred configuring project ':connectivity'.
[        ] > Could not resolve all artifacts for configuration ':connectivity:classpath'.
[        ]    > Could not resolve com.android.tools.build:gradle:3.5.0.
[        ]      Required by:
[        ]          project :connectivity
[        ]       > Could not resolve com.android.tools.build:gradle:3.5.0.
[        ]          > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[        ]             > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom'.
[        ]                > Connection reset
[        ] > Could not get unknown property 'android' for project ':connectivity' of type org.gradle.api.Project.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 13s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[ +453 ms] Running Gradle task 'assembleDebug'... (completed in 14.3s)
[   +3 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 91,636ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[  +70 ms] ensureAnalyticsSent: 58ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by Ruijiao** [comment]
> @Ruijiao
> Please provide `flutter doctor -v`, `pubspec.yaml` and `flutter run --verbose` to better address this issue.

**Comment by Ruijiao** [comment]
flutter clean
flutter build apk
