### ISSUE TITLE
Engine crash in fast_scroll_large_images__memory

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#73489]
From the engine -> framework roll: https://github.com/flutter/flutter/pull/73465

Maybe https://github.com/flutter/engine/pull/23188? /cc @jason-simmons

**Comment by zanderso** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/73489#issue-781468133 engine#7f00e2f6c53c8511e16ad17b55aca4d14fb6c533 android release arm

**Comment by zanderso** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/73489#issue-781468133 engine#7f00e2f6c53c8511e16ad17b55aca4d14fb6c533 android release arm

**Comment by zanderso** [comment]
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/athene/athene:7.0/NPJS25.93-14-8.1-9/4:user/release-keys'
Revision: 'p2a0'
ABI: 'arm'
pid: 12242, tid: 12260, name: 1.io  >>> com.example.macrobenchmarks <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
     r0 00000000  r1 00002fe4  r2 00000006  r3 00000008
     r4 91c36978  r5 00000006  r6 91c36920  r7 0000010c
     r8 91c36698  r9 a0962900  sl 514715e4  fp 00000000
     ip 00000009  sp 91c364e8  lr aa6043e7  pc aa606c44  cpsr 20010010

backtrace:
    #00 pc 00049c44  /system/lib/libc.so (tgkill+12)
    #01 pc 000473e3  /system/lib/libc.so (pthread_kill+34)
    #02 pc 0001d535  /system/lib/libc.so (raise+10)
    #03 pc 00019081  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 000170e4  /system/lib/libc.so (abort+4)
    #05 pc 002b4853  /data/app/com.example.macrobenchmarks-2/lib/arm/libflutter.so (offset 0x139000)
```

**Comment by zanderso** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/73489#issuecomment-756255686 engine#7f00e2f6c53c8511e16ad17b55aca4d14fb6c533 android release arm

**Comment by zanderso** [comment]
Based on the stack trace, this could be from one of the two Skia rolls in that engine roll:

https://github.com/flutter/engine/pull/23479
https://github.com/flutter/engine/pull/23464

**Comment by chinmaygarde** [comment]
This is being discussed with Skia in https://chat.google.com/room/AAAAXsGfCIs/SxTfk07s36A. Christopher Dalton was able to reproduce on Friday. This is probably not a P0 because the effects of the crash are not widespread but leaving the priority as is till we know more.

**Comment by zanderso** [comment]
The change was reverted in Skia, so I think we can close this.
