### ISSUE TITLE
FlutterError: Null check operator used on a null value in DragGestureRecognizer.acceptGesture

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#73499]
**Problem:**
We received via crashlytics several dozens reports of FlutterError: Null check operator used on a null value in the `acceptGesture` method of the `DragGestureRecognizer` class on our production app.

**Stack traces:**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'yx'.
       at .#0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321)
       at .#1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157)
       at .#2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362)
       at .#3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338)
       at .#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267)
       at .#5      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295)
       at .#6      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240)
       at .#7      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213)
       at .#8      _rootRunUnary (dart:async/zone.dart:1206)
       at .#9      _CustomZone.runUnary (dart:async/zone.dart:1100)
       at .#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
       at .#11     _invoke1 (dart:ui/hooks.dart:265)
       at .#12     _dispatchPointerDataPacket (dart:ui/hooks.dart:174)

```

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1) 
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Pixel 3a (mobile) • 94AAY0LLBG • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

**Comment by ZainUrRehmanKhan** [comment]
kindly provide minimal reproducible code of this issue.

**Comment by pedromassangocode** [comment]
Hi @talent-apps 
Can you please provide your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices and a minimal reproducible code sample?.
Thank you

**Comment by talent-apps** [comment]
These crash reports come from crashlytics. 
This issue occurs on **multiple devices** (36% Samsung, 32% Xiaomi, 10% Oppo, 6 % Huawei, 16% Other) and **multiple Android versions** (61% Android 10, 26% Android 9, 7% Android 7, 6% Android 8).
From the reports we see that this error occurs in multiple screens of the app so we are not sure which piece of code is relevant.
The only "draggable" widget that is common to these screens is a `TabBarView`.

**Comment by pedromassangocode** [comment]
Hi @talent-apps 
It is still not clear how to reproduce this issue. For anyone to help you, we need a code that reproduces the issue so we know what causes the issue and where it is happening. Please try to find a reproducible code sample based on your current implementation.
Thank you

**Comment by RafaelBarbosatec** [comment]
Hi!
I also have this same problem in my production app using version 1.22.4 of the flutter.
I still couldn't simulate the error. But from the crashlytics records, it seems that it usually occurs on a screen that has a vertical scroll with children that have a horizontal scroll.

**Comment by talent-apps** [comment]
@RafaelBarbosatec Can you provide a code sample of it?

**Comment by RafaelBarbosatec** [comment]
I'm trying to reproduce. On my device it doesn't happen at all. I don't know if it's intermittent. But as soon as I can reproduce, I'll put the test code here.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
