### ISSUE TITLE
fix the flaky test AXPlatformUniqueIdTest.UnassignedIdsAreReused and re-enable the test.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#73512]
The failing [run is here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858729497408162272/+/steps/Host_Tests_for_host_debug_unopt/0/stdout). Sheriff [thread ID is here](https://chat.google.com/room/AAAAm69vf-M/S1kO-aEOpFM). Regression was introduced in https://github.com/flutter/engine/pull/23110.

**Comment by chunhtai** [comment]
lower the priority since the test is skipped, I will keep this open to track un-skipping the test
