### ISSUE TITLE
[cocoon test]Temporarily skip a test case('SignInButton shows avatar when authenticated')

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#73527]
Context addresses https://github.com/flutter/cocoon/pull/1043#issuecomment-756288403

This issue should be opened until relanding the test case.

CC @CaseyHillers @Piinks

**Comment by CaseyHillers** [comment]
Friendly ping. Is there an ETA for when we can re-enable this test case?

**Comment by xu-baolin** [comment]
Thanks for reminds.
I think it will be a couple of days in case of that the change was not revert! :)

**Comment by Piinks** [comment]
Once https://github.com/flutter/flutter/pull/70160 rolls to dev we'll know it won't be reverted. It should be fine, but we can wait on the roll to land and then turn this back on.

**Comment by xu-baolin** [comment]
Update: Unfortunately, #70160 was reverted by #74439. I will try to fix it as soon as possible. @CaseyHillers 

If it cannot be resolved in a short time, it will consider resuming the test first.

**Comment by CaseyHillers** [comment]
Thanks @xu-baolin for the update. If this issue is getting periodic updates, it's fine to keep the test disabled.

**Comment by xu-baolin** [comment]
Update: Reland via #74620. Waiting to roll to the dev branch.
