### ISSUE TITLE
Flutter Image picker displays distorted video

### ISSUE THREAD

**Issue by smarteertech** [flutter/flutter#73541]
Flutter Image picker plugin displays a distorted video on iOS if we pick a video that was edited using default iOS video editor. Any ideas how to solve this?

Video - https://youtu.be/58nKnaRMlps

**Comment by TahaTesser** [comment]
Hi @smarteertech 
This is not an  `image_picker` issue but a `video_player` issue which is used in the example https://github.com/flutter/flutter/issues/71299
I see there's an open issue addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
