### ISSUE TITLE
Cocoapods error saying it is not installed

### ISSUE THREAD

**Issue by nathan-kane** [flutter/flutter#73565]
I am having trouble getting the app to run on the iOS simulator. When I try to run the app I get the following error:

Warning: CocoaPods not installed. Skipping pod install. CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side. Without CocoaPods, plugins will not work on iOS or macOS. For more info, see https://flutter.dev/platform-plugins To install: sudo gem install cocoapods

CocoaPods not installed or not in valid state. Error launching application on iPhone 12 Pro Max.

I have installed cocoapods successfully as you can see from the below information from the installation so I don't understand why I am getting this error.

MacBook-Pro ios % sudo gem install cocoapods
Password:
Successfully installed cocoapods-1.10.1
Parsing documentation for cocoapods-1.10.1
Done installing documentation for cocoapods after 1 seconds
1 gem installed

pod install runs fine now.

So, now what do I do because I still get the same error when I try to run the app saying cocoapods is not installed?

**Comment by Abhishek01039** [comment]
Hello @nathan-kane 
can you please try `gem which cocoapods`
Thanks

**Comment by nathan-kane** [comment]
This is what I get

/Users/nathankane/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods.rb

**Comment by darshankawar** [comment]
@nathan-kane 
Check out [this](https://github.com/flutter/flutter/issues/57433) similar issue and underlying comments and see if it helps to resolve your issue.
Thanks.

**Comment by henry2man** [comment]
@nathan-kane Hi! I was facing the same issues. I'm not sure which one of the solutions worked for me (also tried to reinstall multiple times) but definitely restarting the IDE was something needed in order to use the simulator.

Hope this helps.
