### ISSUE TITLE
Proposal: Simple custom text selection toolbars

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#73574]
It should be easier to create and modify custom text selection toolbars.

## Use case
Users often want to just do something simple like add an extra button to the existing text selection toolbar.  That should look something like this:

```dart
TextField(
  textSelectionToolbar: TextSelectionToolbar(
    children: <Widget>[
      ...TextSelectionToolbar.defaultChildren,
      TextSelectionToolbarTextButton(
        onPressed: () { /* Do special stuff */ },
        child: const Text('My special button'),
      ),
    ],
  ),
)
```

<img width="261" alt="Screen Shot 2021-01-08 at 10 17 01 AM" src="https://user-images.githubusercontent.com/389558/104049956-b1848e80-519a-11eb-8a89-03f9447644d3.png">

## Context
Recently, https://github.com/flutter/flutter/pull/69428 made it possible to customize the Material text selection toolbar and buttons, and https://github.com/flutter/flutter/pull/73578 does the same for Cupertino.  However, the current TextSelectionControls interface still requires a bunch of extra work in order to be able to use a custom toolbar.  Rather than the simple example above, it looks more like this:

```dart
TextField(
  textSelectionControls: MyTextSelectionControls(),
)

...

class MyTextSelectionControls extends TextSelectionControls {
  @override
  Widget buildToolbar(
    // Lots of confusing parameters that I don't care about when I just want to add a button:
    BuildContext context,
    Rect globalEditableRegion,
    double textLineHeight,
    Offset selectionMidpoint,
    List<TextSelectionPoint> endpoints,
    TextSelectionDelegate delegate,
    ClipboardStatusNotifier clipboardStatus,
  ) {
    /*
      ... Lots of confusing math that's duplicating what we do internally to calculate the anchors...
   */

    return TextSelectionToolbar(
      anchorAbove: anchorAbove,
      anchorBelow: anchorBelow,
      children: <Widget>[
        ...aRecreationOfTheDefaultButtons,
        TextSelectionToolbarTextButton(
          onPressed: () { /* Do special stuff */ },
          child: const Text('My special button'),
        ),
      ],
    );
  }
}
```

## Proposal

I propose that we make a breaking change to the existing TextSelectionControls and its Material and Cupertino counterparts.  The new interface should allow something similar to the simplicity of the first example above.  It should be built around TextSelectionToolbar and should not hardcode a preference for the existing default buttons.

I plan to update this with a full design doc if I'm able to get around to it.

*Update*: [Design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?usp=sharing&resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ)

**Comment by YeungKC** [comment]
I've suggested some ideas about toolbar before. https://github.com/flutter/flutter/issues/36985#issuecomment-758596125

It started when I wanted to make a ux similar to GitHub at someone, but I had no control over not calling hideToolbar().

Currently, the toolbar's show and hide are still heavily dependent on internal properties, and there is no way to know externally when to trigger, or the editing region of the selection, so I suggest exposing these externally and refactoring the toolbar on top of that.

I believe more exposure will lead to more interesting design cases.

**Comment by justinmc** [comment]
I was just working on a Mac desktop text selection toolbar (https://github.com/flutter/flutter/pull/73882), and I ran into the problems you mentioned in https://github.com/flutter/flutter/issues/36985#issuecomment-758596125, like wanting to show the menu in places other than EditableText.  As you mentioned here, the logic of when the toolbar should show/hide is really difficult to control.

I'm working on moving all of this text editing stuff to use the Shortcuts/Actions/Intents system ([design doc](https://docs.google.com/document/d/1QaVIr1bbOWJGNyyNsB75sXgTDRMuxP268sLGTBNDut0/edit#heading=h.pub7jnop54q0)).  This will make it possible to override this behavior anywhere in the widget tree using Shortcuts and Actions widgets.  It should also make the logic for hiding and showing the toolbar much simpler.

I think TextSelectionControls also needs to be rethought to fit into this system.  Hopefully we can come up with something that works for both the mobile text selection toolbars and the idea of menus that fits the desktop right-click menu better.

**Comment by yixiaco** [comment]
Whether the text selection control can span multiple SelectableText components, similar to web selection behavior

**Comment by justinmc** [comment]
@yixiaco You're right, we do need some kind of global selection.  Some people have been thinking about this like https://github.com/flutter/flutter/pull/81849

**Comment by cv0cv0** [comment]
Is it still not finished in version 2.5?

**Comment by Patrick386** [comment]
A year has already passed. Any news?

**Comment by justinmc** [comment]
Update: You still need to implement your own TextSelectionControls if you want to customize the toolbar, which is still annoyingly difficult.  However, refactoring is underway that should unblock this issue.

I'm currently working on getting the context menu to work outside of EditableText (https://github.com/flutter/flutter/issues/98272).  I think this will include a way to specify the context menu in different parts of the tree as a widget.  I'll update this issue when I make progress on that.

**Comment by Patrick386** [comment]
> 
This is a must-have feature. Thanks for your hard work.

**Comment by justinmc** [comment]
Here's a [design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?usp=sharing&resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ) that I've written to make it easy to customize these menus on desktop and mobile.

It looks like I'll deprecate TextSelectionControls.buildToolbar, along with .canCopy and .handleCopy, etc.  Is anyone using those canCopy/handleCopy methods?  Maybe I'll provide a direct replacement.  Currently in the design doc, it's slightly more complicated to remove the Copy button or change what it does (you have to find and modify a buttonData in a list).

**Comment by justinmc** [comment]
A few examples have been added to the repo related to this, [this one](https://github.com/flutter/flutter/blob/master/examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart) for example.  Further examples will be added [in the flutter/samples repo](https://github.com/flutter/samples/pull/1463).
