### ISSUE TITLE
LUCI fails when comparing gradients generated using metal on macos 

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#73590]
I've added a test that `CanRenderGradientWithMetal` which generates a gradient and compares it against a golden: `gradient_metal.png`. This works locally every time but fails on the bots after multiple revisions on the comparison mechanism.

The test still provides value as it ensures that rendering with metal doesn't error out. This issue is to ensure that we re-enable the golden image comparison.

Logs to the failure: https://logs.chromium.org/logs/flutter/led/kaushikiska_google.com/ebafda5f64674703b06b765614a459d75fdf6958b5bba14b03c28631852d1cf6/+/steps/Host_Tests_for_host_debug_unopt_metal/0/stdout

Recipe change: https://flutter-review.googlesource.com/c/recipes/+/9600

cc: @godofredoc

**Comment by godofredoc** [comment]
Is it possible to change the tests to output golden images to a given folder? there are some tests that upload golden images at the end of the test execution and we can potentially reuse that functionality.

**Comment by iskakaushik** [comment]
I think those tests are in the framework repo, not in the engine repo. I have dumped the images as base64 but the images looked the same. I likely need to set some breakpoints to figure out what might be wrong.

**Comment by godofredoc** [comment]
Those machines are chromium provided and we don't have vnc access. We can try running the tests on one of the staging machines where we have full access.

To use the staging machines you can override the pool to use luci.flutter.staging pool and the id flutter-devicelab-mac-9 or 10.

**Comment by Hixie** [comment]
@chinmaygarde says this is obsolete.
