### ISSUE TITLE
lib/main.dart:1:8: Error: Error when reading : The system cannot find the path specified.

### ISSUE THREAD

**Issue by ThePhoenixRisen** [flutter/flutter#73592]
Trying to run the demo flutter counter app that is created when you type `flutter create <appname>`. I keep getting the message in the picture when on Visual Studio. Same thing with Android Studio. Flutter Doctor keeps stating that I am missing Dart and Flutter plugins. Both are installed on Android Studio as well as Visual Studio, as can be shown below. Are my paths, exceptions, and permissions incorrect? What am I missing?
![Visual Studio](https://user-images.githubusercontent.com/71746795/104056925-de469f00-51b6-11eb-8fc8-51e04b901585.JPG)
![Flutter](https://user-images.githubusercontent.com/71746795/104056941-e4d51680-51b6-11eb-8fb5-030792e8df9f.JPG)
![Dart](https://user-images.githubusercontent.com/71746795/104056951-e7377080-51b6-11eb-9c62-575953f74c4e.JPG)
![Android SDK](https://user-images.githubusercontent.com/71746795/104056964-ebfc2480-51b6-11eb-82d7-2b1bd6c02700.JPG)
![Android Plugins](https://user-images.githubusercontent.com/71746795/104056972-ed2d5180-51b6-11eb-9dad-43f60dd3d62f.JPG)
![ANDROID_HOME](https://user-images.githubusercontent.com/71746795/104056978-f0284200-51b6-11eb-8e70-e1141ff77333.JPG)
![Paths](https://user-images.githubusercontent.com/71746795/104056983-f1f20580-51b6-11eb-9add-e8124f9a8759.JPG)

**Comment by iapicca** [comment]
@ThePhoenixRisen 
making sure a virtual or physical device is connected
could you please run from terminal (not from android studio or vs code)
```console
flutter upgrade -f
flutter create issue
cd issue
flutter run -v
```
and post the output. possibly as `.txt` file

**Comment by TahaTesser** [comment]
Hi @ThePhoenixRisen 
Plugins not being detected isn't an issue, it doesn't affect Flutter functionality.  [Reference](https://github.com/flutter/flutter/issues/67986#issuecomment-715452201)

Please follow the steps mentioned above and provide your `flutter doctor -v` your `flutter run --verbose` logs instead of screenshots
Thank you

**Comment by ThePhoenixRisen** [comment]
It just wasn't connecting to the emulated device for some reason. Tried running it from terminal first since the first response asked me to run from terminal and not vs code. Now it runs in both. Still getting the red errors, but it runs without a problem. Thank you guys.
