### ISSUE TITLE
Android: Share Skia context between multiple engines

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#73597]
Android equivalent of https://github.com/flutter/flutter/issues/72021

**Comment by xster** [comment]
The Vulkan one will be done in a separate PR to make the PRs smaller since it's currently made a bit deeper inside the VulkanWindow https://github.com/flutter/engine/blob/0c79393dde018e1b99b4ccaabea48a16314ed93d/vulkan/vulkan_window.cc#L113.
