### ISSUE TITLE
[integration_test] Enable screenshots for iOS / Android

### ISSUE THREAD

**Issue by smkhalsa** [flutter/flutter#73596]
It seems that you can [only](https://github.com/flutter/flutter/blob/87746c767408e3936093f338f9427e9b3ae4bfa7/packages/integration_test/example/integration_test/extended_test.dart#L7) take screenshots using the web platform at the moment.

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/51890
