### ISSUE TITLE
The current 404 page for the website isn't helpful

### ISSUE THREAD

**Issue by danafergan** [flutter/flutter#7359]
The current 404 page is a Firebase Page Not Found with directions for the host to replace it. Adding a 404.html page to the root would make it friendlier and give users a link back to an index usable page.

**Comment by sethladd** [comment]
Great idea! Patches most welcome.

(is this for the docs or the website?)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1833](https://github.com/flutter/website/issues/1833) via [**ZenHub**](https://www.zenhub.com/)
