### ISSUE TITLE
We shouldn't collapse leading or trailing whitespace when rendering text

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#736]
I wanted to make some text line up. It was just numbers. I tried padRight(4) to add spaces on the right so that it would always be the same width. Unfortunately we eat all the trailing spaces.

**Comment by abarth** [comment]
Fixed.

**Comment by danehale0612** [comment]
I don't know if this is the same issue but it seems like it still exists around TextFormFields as well:
https://github.com/flutter/flutter/issues/30975
