### ISSUE TITLE
Deferred library change + hot reload causes failure

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#73602]
Context: https://docs.google.com/document/d/1jOJu-XBX1yC0y2DB-wgiiXwt_M46VywGuYYNIZ_fdFk/edit?resourcekey=0-knknGFrNOyzlozGI6E858w&disco=AAAALD4Xgzs

Making changes to a deferred dart library and hot reloading results in failure.

cc @jonahwilliams @rmacnak-google

**Comment by rmacnak-google** [comment]
This is because we never got to matching up the old and new library prefixes to propagate their was-loaded bits. E.g, if `prefix.loadLibrary()` was already called before a reload, `prefix.foo()` shouldn't throw a not-loaded exception after a reload, even though reload created a fresh `prefix`.

**Comment by GaryQian** [comment]
Thanks Ryan!
