### ISSUE TITLE
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 178 pos 16: 'earliestUsefulChild != null': is not true.

### ISSUE THREAD

**Issue by Feptkdie** [flutter/flutter#73600]

**Comment by iapicca** [comment]
@Feptkdie 
please provide your `flutter doctor -v` your `flutter run -v` and a minimal reproducible code sample

**Comment by TahaTesser** [comment]
Hi @Feptkdie 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Feptkdie** [comment]
Thanks sir, i already fixed. That error was not to be included in the list view builder in columns widget with no height.

**Comment by TahaTesser** [comment]
Hi @Feptkdie 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
