### ISSUE TITLE
plugin_lint_mac fails, error: failed to load module 'Swift'

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73606]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_lint_mac/1218/overview
```
[plugin_lint_mac] [STDOUT] stdout:     /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk/usr/lib/swift/Swift.swiftmodule/armv7-apple-ios.swiftinterface:21488:21: error: module 'Builtin' has no member named 'convertUnownedUnsafeToGuaranteed'
[plugin_lint_mac] [STDOUT] stdout:         return try body(Builtin.convertUnownedUnsafeToGuaranteed(fakeBase,
[plugin_lint_mac] [STDOUT] stdout:                         ^~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[plugin_lint_mac] [STDOUT] stdout:     <unknown>:0: error: failed to load module 'Swift'
[plugin_lint_mac] [STDOUT] stdout:     Command CompileSwift failed with a nonzero exit code
```

Swift symbols missing again?  https://github.com/flutter/flutter/issues/72823

Same failure in mac_build_ios_framework_module_test and mac_plugin_lint_mac
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_ios_framework_module_test/1226/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_lint_mac/1218/overview

**Comment by GaryQian** [comment]
cc @godofredoc

**Comment by keyonghan** [comment]
Didn't see suspicious changes from infra side. Last time `xcode` version was bumped to fix the `Mac build_tests` (https://github.com/flutter/infra/pull/320/files). Shall we update the xcode version for these builders as well @godofredoc ?

**Comment by godofredoc** [comment]
Tests were being noop'ed and just fixed that issue: https://github.com/flutter/flutter/issues/73446

**Comment by keyonghan** [comment]
Test passes with updated xcode version: https://chromium-swarm.appspot.com/task?id=50fd1a6c3f974c10

Working on a config PR to fix.

**Comment by godofredoc** [comment]
We are not ready to start using xcode 12.3 yet. Actually we need to add swift dependency to the 11.3 xcode
