### ISSUE TITLE
Add selectableDayPredicate option to the showDateRangePicker function

### ISSUE THREAD

**Issue by Sam3077** [flutter/flutter#73615]
Currently, the `showDatePicker()` function has an optional argument of `selectableDayPredicate` that allows you to disable certain days and not allow them to be selected. The disabled days also get a different style so the user can easily tell what they can, and can't pick. The `showDateRangePicker()` function, however, has no such argument. The use cases for these two functions are not identical, but they are close enough where this ability would still be useful with a `DateRangePicker`.

## Use case
My specific use case is in a P2P rental marketplace. Users can list items and create blackout days for those items where nobody can request to rent them. It would be very useful to show this information to potential users by having non-selectable days in the `DateRangePicker`.

A potential interim solution is to use two `DatePicker`s, each with the same `selectableDayPredicate`, but that pattern is more clunky and awkward than simply using a `DateRangePicker`.

This feature could also be useful for an app that only wants to allow users to select date ranges on weekdays.

## Proposal
The proposed UI is very similar to what has already been implemented with the `DatePicker`. Dates that return `false` from the `selectableDayPredicate` should be displayed differently, and should not be selectable as shown below
![Screen Shot 2021-01-08 at 4 18 44 PM](https://user-images.githubusercontent.com/25106528/104074382-37213200-51cd-11eb-8f97-f6c31cc8b9b9.png)
(here, the 19th and 20th are disabled).

If a disabled date is included in the selected range, even more attention should be called to the dates to signal that they are not allowed.
![image](https://user-images.githubusercontent.com/25106528/104074494-88c9bc80-51cd-11eb-9611-2c0e121442d4.png)

Having a disabled date in a selection should prevent the user from saving their selection and notify them of the issue.
![image](https://user-images.githubusercontent.com/25106528/104074549-a5fe8b00-51cd-11eb-9f64-9d2cea168ea1.png)

The `input` style `DateRangePicker` should also prevent users from selecting a range that contains non-selectable dates. Also, when switching between the two modes, an illegal selection from `calendar` mode should be discarded, but an illegal selection from `input` mode should be maintained to highlight the areas that cause issues.

https://user-images.githubusercontent.com/25106528/104074862-713f0380-51ce-11eb-8b75-5111f41c10d7.mov

I'm wondering if there may be a better way to display non-selectable dates in `input` mode. If anyone has any ideas, let me know!

## Progress
I'm working on this feature in https://github.com/Sam3077/flutter/tree/date_range_picker_with_predicate.

I have all of the detailed UI and features implemented and working. I still need to write tests for what I added and squash any bugs I find along the way. I may also try to rework how non-selectable dates are shown in `input` mode since that could lead to some frustration if users don't switch to `calendar` mode.

**Comment by darshankawar** [comment]
@Sam3077 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/63973.
Please follow-up there for updates.
Closing this as duplicate.
