### ISSUE TITLE
Flutter Web: holding down Control in a Windows browser prevents scroll wheel detection

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#73617]
I've attached a sample Flutter app to demonstrate the issue.

When compiled with CanvasKit and the build served with a simple web server, the behavior of the app is different on Mac and Windows browsers.

On Mac, when the Control key is held down and the mouse wheel scrolled, the scroll wheel activity is detected. This also works when the shift key is held down.

On Windows, the default behavior for Control/ScrollWheel is to zoom the browser in and out. This can be disabled in Javascript with. The attached app index.html has the following in it:

```
  <script>
    document.addEventListener("wheel", (e) => (e.ctrlKey || e.shiftKey)
      && e.preventDefault(), { passive: false });
  </script>
```

With this in place, everything behaves as expected on the Mac.

In browsers on Windows, however, when the control key is held down, the app cannot detect scroll wheel movements. When shift (or other keys) is held down, it can.

[ck_wheel_test.zip](https://github.com/flutter/flutter/files/5789789/ck_wheel_test.zip)

This behavior can be replicated on latest Flutter master.

**Comment by ferhatb** [comment]
@mjohnsullivan , issue landed in engine, waiting for roll into flutter master.

**Comment by mjohnsullivan** [comment]
Thanks for landing the fix!
