### ISSUE TITLE
Web : Special characters (ex: Chinese) not rendering on latest master using `flutter run -d chrome`

### ISSUE THREAD

**Issue by zengfr** [flutter/flutter#73628]
how to Set a unified encoding  utf8 for flutter web?
now  Chinese is messy encoding
![捕获](https://user-images.githubusercontent.com/9524903/104080561-c2e59d80-5263-11eb-9a60-1ab4977d5e81.PNG)

**Comment by iapicca** [comment]
@zengfr 
I can reproduce the issue with the latest master

<details>
<summary>code sample with utf8 encoding</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:convert' show utf8;

final _encoded = utf8.encode('你好，世界');

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Text(
              utf8.decode(_encoded),
            ),
          ),
        ),
      ),
    );

```

</details>
<details>
<summary>logs</summary>

```bash
[ +934 ms] Launching lib/main.dart on Chrome in debug mode...
[ +101 ms] Updating assets
[  +56 ms] Waiting for connection from debug service on Chrome...
[   +4 ms] Found plugin battery at /home/francesco/.pub-cache/hosted/pub.dartlang.org/battery-1.0.11/
[  +15 ms] Found plugin battery at /home/francesco/.pub-cache/hosted/pub.dartlang.org/battery-1.0.11/
[  +47 ms] <- reset
[   +6 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.DWAYZT/flutter_tool.MCABKJ/app.dill
--libraries-spec file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.DWAYZT/flutter_tools.BTIYLO --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+20062 ms] Waiting for connection from debug service on Chrome... (completed in 20.1s)
[        ] Synced 28.7MB.
[        ] <- accept
[        ] Caching compiled dill
[ +542 ms] Using Chromium 87.0.4280.141 snap

[ +567 ms] [CHROME]:
[   +1 ms] [CHROME]:(chrome:200544): Gtk-WARNING **: 13:12:42.403: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name
[   +3 ms] [CHROME]:
[        ] [CHROME]:(chrome:200544): Gtk-WARNING **: 13:12:42.408: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name
[   +1 ms] [CHROME]:
[        ] [CHROME]:(chrome:200544): Gtk-WARNING **: 13:12:42.410: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
[ +376 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:44477/devtools/browser/ac41a692-35b8-4bb9-9ebe-452c0af95e9e
[+3695 ms] DwdsInjector: Received request for entrypoint at http://localhost:41681/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +18 ms] MetadataProvider: Loaded debug metadata
[  +13 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:41681/main_module.bootstrap.js
[+3471 ms] DevHandler: Debug service listening on ws://127.0.0.1:35015/TXeKIfrrDl4=/ws

[  +13 ms] Debug service listening on ws://127.0.0.1:35015/TXeKIfrrDl4=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+60097 ms] Application finished.
[   +7 ms] "flutter run" took 90,455ms.
[  +10 ms] DevHandler: Stopped debug service on ws://127.0.0.1:41165

[ +247 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

</details>
<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/104090039-778bb900-527c-11eb-94a4-4e5613778590.png)

</details>

nevertheless the issue seems to occur even with a regular string, 
I'm not sure the issue is with encoding / decoding `utf8`

<details>
<summary>code sample with simple string</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Text('你好，世界'),
          ),
        ),
      ),
    );

```

</details>
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.275 at /home/francesco/snap/flutter/common/flutter
    • Framework revision d9044a8a61 (2 hours ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 87.0.4280.141 snap

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
This seems to be case of regression. On latest master, a simple internationalized string (ex: Chinese) isn't rendering using `flutter run -d chrome`:

<img width="779" alt="Screenshot 2021-01-11 at 2 14 32 PM" src="https://user-images.githubusercontent.com/67046386/104160637-75119680-5417-11eb-84cd-1b5fad4c5082.png">

<details>
<summary>latest masterflutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.275 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.


```

</details>

Whereas, on previous master, the same string is rendered properly:

<img width="758" alt="Screenshot 2021-01-11 at 2 11 11 PM" src="https://user-images.githubusercontent.com/67046386/104160671-83f84900-5417-11eb-9e0a-655175f28e8a.png">

<details>
<summary>previous master flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.220, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.220 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 01babcac16 (4 days ago), 2021-01-06 22:34:03 -0500
    • Engine revision 1758eaa4ed
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.


```

</details>

**Comment by darshankawar** [comment]
May be due to this PR was reverted : https://github.com/flutter/flutter/issues/53897#issuecomment-756427678

**Comment by noordawod** [comment]
Experiencing the same for Arabic and Hebrew texts, even for emojis. At least in both Text() and TextField() widgets.

**Comment by noordawod** [comment]
For now, how do I revert back to the previous version on `master`?

**Comment by ferhatb** [comment]
@hterkelsen is about to land a fix. Please use flutter run -d chrome -web-renderer=html , same for flutter build for now.

**Comment by noordawod** [comment]
@ferhatb please correct to `--web-renderer=html` (double dashes)

**Comment by pedromassangocode** [comment]
I was able to reproduce this issue on latest beta channel as well (based in https://github.com/flutter/flutter/issues/73927). The issue only reproduces with CanvasKit as well.

| Actual | Expected |
|-|-|
|![Screen Shot 2021-01-14 at 09 13 11](https://user-images.githubusercontent.com/67424416/104563190-a2de2180-5649-11eb-9db4-549e3b6c268b.png)|![Screen Shot 2021-01-14 at 09 21 05](https://user-images.githubusercontent.com/67424416/104563358-d620b080-5649-11eb-8eca-2f06931ddc01.png)|



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-8.2.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by noordawod** [comment]
Still showing gibberish in:

```
Flutter 1.26.0-2.0.pre.364 • channel master • https://github.com/flutter/flutter.git
Framework • revision fb9e485dd8 (2 hours ago) • 2021-01-15 01:39:02 -0500
Engine • revision efa768683e
Tools • Dart 2.12.0 (build 2.12.0-225.0.dev)
```

**Comment by A7medMaher** [comment]
any update ?

**Comment by newskylabs** [comment]
This topic is marked as closed - but I am still experiencing the same problem after updating right now:

Flutter is already up to date on channel beta
Flutter 1.26.0-17.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 4b50ca7f7f (3 days ago) • 2021-02-04 19:44:27 -0800
Engine • revision 2c527d6c7e
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)

First only spaceholder glyphs are shown.  After about half a second 90% of the hanzi are displayed - but the rest ~10% are still replaced by spaceholder glyphs.

Here what is shown in the chrome device:

<img width="508" alt="flutter-chinese-garbled000" src="https://user-images.githubusercontent.com/10684995/107159493-ad61b180-6990-11eb-9168-235004734639.png">

The text, however, should be:

没有人喜欢的女孩。她叫李叶，是一个不太好看的女孩。李叶出生在海
南。海南在中国的最南边，很远很远。李叶的爸爸经常在外面，很少在
家。李叶的妈妈是个很好看的女人，她有很多朋友，每天都和朋友一起

**Comment by newskylabs** [comment]
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Text(
          '没有人喜欢的女孩。'
          '她叫李叶，是一个不太好看的女孩。'
          '李叶出生在海南。'
          '海南在中国的最南边，很远很远。'
          '李叶的爸爸经常在外面，很少在家。'
          '李叶的妈妈是个很好看的女人，她有很多朋友，每天都和朋友一起玩。',
        ),
      ),
    ),
  );
}
```

**Comment by iapicca** [comment]
@newskylabs @A7medMaher 
are you experincing the issue upgrading to master?
```console
flutter channel master
flutter upgrade -f
```

**Comment by yjbanov** [comment]
Reopened to investigate.

**Comment by yjbanov** [comment]
Confirmed in a local test that some characters, e.g. 欢, are missing glyphs.

**Comment by newskylabs** [comment]
@yjbanov
> are you experincing the issue upgrading to master?

I experience the same issue in both, beta as well as master.

Beside the missing glyphs it is annoying how long it takes to load the font:   initially, for at least half a second, only placeholder glyphs are shown.

**Comment by jing-pei** [comment]
same issue

<details>
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel master, 1.26.0-18.0.pre.215, on macOS 11.1 20C69
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-18.0.pre.215 at /Users/angus/flutter
    • Framework revision f3c10bd23a (26 hours ago), 2021-02-08 21:52:03 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150
    ! Error: iPad is not connected. Xcode will continue when iPad is connected.
      (code -13)

• No issues found!

</details>

**Comment by pedromassangocode** [comment]
I can confirm that this is still valid. Reproduced based in https://github.com/flutter/flutter/issues/76003.

![Screen Shot 2021-02-15 at 08 58 48](https://user-images.githubusercontent.com/67424416/107919684-05d61780-6f6c-11eb-817b-0b8964130728.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
        body: Text("Special char : ← ↑ → ↓ \u2190 \u2191 \u2192 \u2193"));
  }
}
```
</details>

**Comment by Hixie** [comment]
(@yjbanov says progress is being made)

**Comment by yjbanov** [comment]
Update: yesterday @hterkelsen and I investigated the issue. Turns out there are three issues that by chance all exhibit the same symptom, missing glyphs:

- The issue with the arrow symbols was a simple typo in one of the code unit ranges. The fix is trivial.
- The issue with the missing Han characters (e.g. 欢) is due to two bugs.
  - One is in the logic that determines the family of fonts and downloads the respective fonts.google.com CSS stylesheet with the manifest of fonts and _actual_ supported code ranges by those fonts. That logic is conservative and in some cases downloads more stylesheets than we need. The bug was in the logic that attempted to minimize the number of downloaded fonts, where instead it minimized the number of downloaded stylesheets, eliminating the needed fonts in the process.
  - Another bug is that one of the fonts that claims to support the requested characters is actually missing the glyphs for them. We'll raise the issue with the Google Fonts team. In the meantime we will disable the tie-breaking logic for CJK fonts that compete for the same glyphs so we have at least one font covering it.

We have a solution, I'm cleaning up a PR to send for review.

**Comment by mrcsh** [comment]
I am seeing glyphs in the range U+1D49C - U+1D503 rendered at all.
Also some glyphs in other ranges (I have seen U+2460-U+24EA) don't seem render correctly until some Chinese or other language's are shown.

**Comment by yjbanov** [comment]
Reopening because to fully fix this we also need to land https://github.com/flutter/engine/pull/24470

**Comment by YowFung** [comment]
Same issue in flutter 2.x, when Chinese characters is followed by an `overflow: TextOverflow.ellipsis`.

![image](https://user-images.githubusercontent.com/26346560/117234020-caeecc00-ae56-11eb-909f-defb2b003103.png)
