### ISSUE TITLE
Platform deeplink doesn't respect query parameters

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter#73637]
Triggering a deeplink in both iOS/Android platform only sends URI path to Engine's navigation channel. 

Send a deeplink as `https://flutterbooksample.com/book/1?author=dash`.

# Actual Result
`Navigator.defaultRoute = /books/1`

# Expected Result
`Navigator.defaultRoute = /books/1?author=dash`

**Comment by darshankawar** [comment]
@sarbagyastha 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that we can copy paste or clone and run to see the issue ?
Thanks.
