### ISSUE TITLE
flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt 

### ISSUE THREAD

**Issue by AmitLakhani098** [flutter/flutter#73635]
Hi @julien100000 
I can't reproduce it with the same dependencies (on dev v1.15.21).
Can you see the error after running `flutter pub cache repair`?

_Originally posted by @VladyslavBondarenko in https://github.com/flutter/flutter/issues/52739#issuecomment-600185008_

**Comment by AmitLakhani098** [comment]
I tried this solution now i am getting error : 

The plugin `flutter_plugin_android_lifecycle` doesn't have a main class defined in

C:\Users\amitl\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pub_cache-0.2.3\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\android\src\main\java\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.java or  
C:\Users\amitl\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pub_cache-0.2.3\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt. This is likely to due to an incorrect
`androidPackage: io.flutter.plugins.flutter_plugin_android_lifecycle` or `mainClass` entry in theplugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to
any of locations used above. Otherwise, please contact the author of this plugin and consider
using a different plugin in the meanwhile.


Please help!!! i not able to fix this issue...

**Comment by iapicca** [comment]
@AmitLakhani098 
please try this [solution](https://github.com/flutter/flutter/issues/52739#issuecomment-600566849)
if the issue persists please provide your `flutter doctor -v` your `flutter run -v`
and a minimal reproducible code sample

**Comment by TahaTesser** [comment]
Hi @AmitLakhani098 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
