### ISSUE TITLE
showDatePicker change year UX issue

### ISSUE THREAD

**Issue by theisoft** [flutter/flutter#73632]
https://api.flutter.dev/flutter/material/showDatePicker.html

Let say ive already chosen a date 01/12/2006. Then I just want to change the year so I simply click to open the DatePicker, change Year and click okay. I would expect to change the date to 01/12/THE_NEW_YEAR. Please see attached linked to the video to demonstrate the UX issue.

https://1drv.ms/u/s!Ash989zb3HPlgdtkLgxLvgLNUI7_lQ?e=U9UYrE

**Comment by iapicca** [comment]
@theisoft 
please provide your `flutter doctor -v` and a minimal reproducible code sample

**Comment by theisoft** [comment]
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-PH)
    • Flutter version 1.25.0-8.2.pre at D:\flutter\flutter
    • Framework revision b0a2299859 (4 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.1
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\ozting\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by theisoft** [comment]
DateTime d = await showDatePicker(
  context: context,
  initialDate:
      DateTime.now().add(Duration(days: -15 * 365)),
  firstDate:
      DateTime.now().add(Duration(days: -60 * 365)),
  // lastDate: DateTime.parse('2021-01-01'),
  helpText: 'Birth Date',
);

**Comment by darshankawar** [comment]
@theisoft 
I used [this](https://fluttercentral.com/Articles/Post/1199/Flutter_DatePicker_Example) code sample on latest master. First selected a date `1/12/2006` and then again went back to select year 2021 and clicked OK that gave me current year as expected.

<img width="325" alt="Screenshot 2021-01-11 at 2 35 40 PM" src="https://user-images.githubusercontent.com/67046386/104162284-53fe7500-541a-11eb-81d5-c1722e6bfe01.png">

<img width="329" alt="Screenshot 2021-01-11 at 2 35 51 PM" src="https://user-images.githubusercontent.com/67046386/104162287-55c83880-541a-11eb-9455-64b38de0e0e4.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.275 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.


```

</details>

**Comment by theisoft** [comment]
Yes, working on master. Thanks
