### ISSUE TITLE
Exception after flutter clean : A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade 

### ISSUE THREAD

**Issue by jaydip-pawar** [flutter/flutter#73641]
https://stackoverflow.com/q/65643211/13359721 Please refer this link..

**Comment by iapicca** [comment]
@jaydip-pawar 
your stackoverflow question has been [answered](https://stackoverflow.com/a/65643362/9836706

The problem is with multidex builder.

> Go to android/app/build.gradle and add the following lines of codes:
> 
>```gradle
> dependencies {
>   implementation "androidx.multidex:multidex:2.0.1"
> }
> android {
>     defaultConfig {
>         multiDexEnabled true
>     }
> })
>```

does this solve the issue?

**Comment by jaydip-pawar** [comment]
> @jaydip-pawar
> your stackoverflow question has been [answered](https://stackoverflow.com/a/65643362/9836706
> 
> The problem is with multidex builder.
> 
> > Go to android/app/build.gradle and add the following lines of codes:
> > ```groovy-gradle
> > dependencies {
> >   implementation "androidx.multidex:multidex:2.0.1"
> > }
> > android {
> >     defaultConfig {
> >         multiDexEnabled true
> >     }
> > })
> > ```
> 
> does this solve the issue?

Yes! It solved my issue.
