### ISSUE TITLE
in_app_purchase: way to show expiration date or status of subscriptions

### ISSUE THREAD

**Issue by odonc** [flutter/flutter#73642]
Using the in_app_purchase: ^0.3.5+1 package, I'm trying to verify that a user has an active subscription. 

I can get the productID and transaction date, with purchaseDetails.productID &  purchaseDetails.transactionDate. But I can't seem to get an expiration date or status. Watching the apple videos they talk about "status" heaps. I'm not sure if someone starts a free 3 day trial if the transaction date will know if they cancelled, so not confident to base everything off this transaction date. 

I can get the purchaseDetails.verificationData.localVerificationData, which seems to be a ANS1 string, seems very hard to decode, i can't get it to make anything readable, just a list of integers. If you know how to decode this to get more info that would solve my problem. 

I'm trying not to use a platform like RevenueCat (as they take a cut), they seem to offer features like this.

**Comment by iapicca** [comment]
@odonc 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, 
please provide your `flutter doctor -v` your `flutter run -v`
and a minimal reproducible code sample

**Comment by odonc** [comment]
Ok i'll post on stackoverflow.
