### ISSUE TITLE
new windows app was broken after flutter upgrade

### ISSUE THREAD

**Issue by nicksnz3k** [flutter/flutter#73644]
After flutter upgrade, when i create new project or add windows platform to existed project and try to compile app for windows - i get message: 
d:\pf\vs2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: пользовательская сборка для "D:\Documents\Dev\flutter examples\qwe\build\windows\CMakeFiles\1bd7d30445e9dc76eaf351c47bdb4e99\flutter_windows.dll.rule;D:\Documents\Dev\flutter examples\qwe\build\windows\CMakeFiles\3da60b3a1a9bffa68e3692f413a55d8d\flutter_assemble.rule" завершила работу с кодом 1. [D:\Documents\Dev\flutter examples\qwe\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
_______________________
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-2.0.pre.275, on Microsoft Windows [Version 10.0.19042.685], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.8.3)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] Connected device (3 available)

• No issues found!

**Comment by nicksnz3k** [comment]
my mistake, space in path

**Comment by TahaTesser** [comment]
Created https://github.com/flutter/flutter/issues/75611 to avoid this

**Comment by marcelo-tm** [comment]
I'm having the same issue, but I can't find any spaces. Can anyone please help me?

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'C:\playground\flutter\desktopapp\build\windows\CMakeFiles\207ed13bfb2b690e4e310b88b1dd8c22\flutter_windows.dll.rule;C:\playground\flutter\desktopapp\build\windows\CMakeFiles\7b92412c37a677b5dc7ee51a1ef9d988\flutter_assemble.rule' exited with code 1. [C:\playground\flutter\desktopapp\build\windows\flutter\flutter_assemble.vcxproj]`

**Comment by Maheswari01A** [comment]
I am also facing same issue. Dont have space or special characters in path
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066:40,5): error MSB8066: Custom build for 'C:\GITREPO\go2\go2\build\windows\CMakeFiles\0002ba41b23f9613be3582c8ace94283\ule;C:\GITREPO\go2\goflutter_windows.dll.rule;C:\GITREPO\go2\go2\build\windows\CMakeFiles\0804c8c686836170ab70105db4c256be\flutter_assembl2\go2\build\windows\fe.rule' exited with code 1. [C:\GITREPO\go2\go2\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
