### ISSUE TITLE
[web]: In web. flutter can't use korean

### ISSUE THREAD

**Issue by Wolfsil** [flutter/flutter#73645]
![캡처](https://user-images.githubusercontent.com/37937078/104094354-d2043400-52d3-11eb-8a80-d160bfb9122e.JPG)

Hello. I can resolve this problem. I use Text("안녕") in scaffold widget.

**Comment by iapicca** [comment]
@Wolfsil 
I can confirm the issue occur with the latest master, 
![image](https://user-images.githubusercontent.com/45637986/104105975-d7a15000-52ba-11eb-8370-8565442506a3.png)

<details>
<summary>code sample </summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Text('안녕하세요 세계'),
          ),
        ),
      ),
    );

```
</details>

<details>
<summary>doctor </summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.275 at /home/francesco/snap/flutter/common/flutter
    • Framework revision d9044a8a61 (10 hours ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 87.0.4280.141 snap

! Doctor found issues in 1 category.

```
</details>

**Comment by mrantivirus** [comment]
While I'm not sure what your exact issue may be, my app/site works fine with Korean text (using Stable and Beta). Have you tried changing the font?

**Comment by iapicca** [comment]
@mrantivirus 
sounds like a regression to me, 
if you flutter web app has been built with an older version make sense that it works well;
what flutter version are you using?

**Comment by mrantivirus** [comment]
> @mrantivirus
> sounds like a regression to me,
> if you flutter web app has been built with an older version make sense that it works well;
> what flutter version are you using?

For us, we're using the latest beta version (v1.25.0-8.2.pre) but also the [Intl package](https://pub.dev/packages/intl) with the locale set to ko_KR. Then we can display the localized app strings. We do have API calls that return Korean content as well, and that works fine without any issues.

However, even if I use the sample code provided, it still works fine.

![image](https://user-images.githubusercontent.com/4400467/104141259-bcfbd380-53ad-11eb-9b14-3b7cc1a93fcd.png)

**Comment by darshankawar** [comment]
This is indeed a regression. Similar open issue describes this case,  https://github.com/flutter/flutter/issues/73628
Closing this as duplicate.
