### ISSUE TITLE
Navigator.replaceNamed

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#7365]
I'm looking to set up some high-level navigation between some different pages of the Leafy app from our app drawer. The desired flow is as follows:

Page1 --> drawer --> Selection between {Page1, Page2, Page3} --> drawer --> Selection between ...

This would be much easier to do if the replace methods from NavigatorState were exposed statically through Navigator, just like the pop and push methods are.

**Comment by Hixie** [comment]
Yeah we definitely need this soon.

**Comment by HansMuller** [comment]
Here's a rough proposal about how this might work.  Please let us know if this would work for your application.

`Navigator.of(context).replaceNamed('/foo', '/bar')` could essentially push '/bar' and then remove '/foo'. The effect of this replace operation would be that '/foo' would be  immediately dropped from the history list, so if '/bar' were popped during its push transition the Navigator would not expose '/foo'. It would behave as if '/foo' had already been popped.

Currently the Navigator remove operations do not run their route's transition animation. During the remove part of the replaceNamed operation we -would- run the outgoing route's backward transition animation.

If both routes had complementary transition animations, we could enable the app to use replaceNamed to push and pop the two routes at the same time. Ideally this would appear as if the incoming route were pushing the old route out of the way.

**Comment by abarth** [comment]
See also https://github.com/flutter/flutter/issues/6544

**Comment by aleki** [comment]
@HansMuller It should pushNamed and reset the navigator's stack of routes.

**Comment by DaveShuckerow** [comment]
I like your proposal, @HansMuller. That seems to accurately express what we're looking for.

@abarth, that seems very similar to this. Leafy has similar flows to what's described in the other issue and that could also be helpful.

I'm curious about the case where the route being replaced is not currently top-of-stack. That might need special consideration, but I imagine we'd want to have the same behavior there.

**Comment by DaveShuckerow** [comment]
Thinking about it, the underlying user issue in both this and #6544 could be that popAndPushNamed doesn't work properly on the first route in an app. It seems like both involve trying to change the first route into a different route.

**Comment by HansMuller** [comment]
I've built a version of this in terms of popAndPushNamed as @DaveShuckerow  suggested.

It stretches the meaning of "popAndPushNamed" a little because - if the Navigator's stack only contains one route -  the new (named) route is pushed first and then the old route is effectively popped.  If the Navigator's stack contains more than one route then the method works exactly as it did before.

**Comment by HansMuller** [comment]
I changed the API to pushReplacement() and pushReplacementNamed() per https://github.com/flutter/flutter/issues/6544 The popAndPushNamed() method remains the simple macro operation that  it has been. See https://github.com/flutter/flutter/pull/7611

**Comment by DaveShuckerow** [comment]
Just replacing the top route is very similar to popAndPush. From a developer standpoint, the end result is the same -- the old route comes off and the new route goes on.

Is there a way to reduce the API duplication?

**Comment by DaveShuckerow** [comment]
The primary problem with popAndPush that we were having was that it does not work when popping the initial route of the app and pushing a new route in its place. If we can make it possible to support that, then I think we only need popAndPush.
