### ISSUE TITLE
app closes unexpectedly when trying to run google_maps_flutter in my app,W/System  (10769): A resource failed to call release.  E/BufferQueueProducer(10769): [SurfaceTexture-0-10769-0](this:0x94a7b000,id:0,api:1,p:401,c:-1) dequeueBuffer: BufferQueue has been abandoned

### ISSUE THREAD

**Issue by morka17** [flutter/flutter#73650]
![Screenshot from 2021-01-09 18-35-26](https://user-images.githubusercontent.com/59286046/104105012-b7b66000-52ab-11eb-8a65-78d9287ecd93.png)

**Comment by morka17** [comment]
W/System  (10769): A resource failed to call release. 
E/BufferQueueProducer(10769): [SurfaceTexture-0-10769-0](this:0x94a7b000,id:0,api:1,p:401,c:-1) dequeueBuffer: BufferQueue has been abandoned

**Comment by morka17** [comment]
Please help, somebody please help.

**Comment by darshankawar** [comment]
@morka17 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue. Also please avoid posting screenshots of the error or the above details. Provide the code in text format.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
