### ISSUE TITLE
I cann't install on my physical device

### ISSUE THREAD

**Issue by heinzan** [flutter/flutter#73658]
This is error Log.This error is not happen in earlier run.But sudden occur.    
    
    Error: ADB exited with exit code 1
    Performing Streamed Install

    adb: failed to install /../app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to 
    collect certificates from /data/app/vmdl714559976.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of 
    contents did not verify]
    Error launching application on Mi A2 Lite.

This is doctor log.
    

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
 
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    [!] Android Studio (version 4.1)
        ✗ Flutter plugin not installed; this adds Flutter specific functionality.
        ✗ Dart plugin not installed; this adds Dart specific functionality.
    [✓] Connected device (1 available)

I restarted my device sometime i can run but cann't run again.I can run with emulator.I have been tried a lot ways but cann't solve my problem.

**Comment by iapicca** [comment]
@heinzan 
can you provide your `flutter doctor -v` (with your device connected)
and your full `flutter run -v`

**Comment by heinzan** [comment]
@iapicca 
    
    [✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/heinzan/Downloads/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/heinzan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

    [!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

    [✓] Connected device (1 available)
    • Mi A2 Lite (mobile) • 08fde05c0705 • android-arm64 • Android 9 (API 28)

    ! Doctor found issues in 1 category.

**Comment by Sal7one** [comment]
@heinzan

Please try these steps:

1 - Uninstall your app from phone ( If you have it already installed) 

2 - Do "flutter clean"

3 - Update SDK build tools to 30.x.x

**Comment by heinzan** [comment]
@Sal7one 
Thanks for your answer.Your answer was solved.
