### ISSUE TITLE
Please add an option to flutter create that creates an barebone project

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#73655]
Hi,

as great it is that you get a full working demo app with good comments when calling ´flutter create´ so annoying  it gets to delete all that stuff before you can start with your own app if you do this often.

Would it be able to add a flag to ´flutter create -barebone myProject´that only creates the project and stops after adding main.dart?

thanks a lot for all your work

**Comment by 06000000-0000** [comment]
Hi

**Comment by 06000000-0000** [comment]
Good

**Comment by pedromassangocode** [comment]
Hi @escamoteur 
Sorry it is not clear to me what exactly the proposed flag should do. Do you mean create a `main.dart` without all the code comments?
Thank you

**Comment by escamoteur** [comment]
actually a main.dart with just 

´´´dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: 
    );
  }
}
´´´

**Comment by jmagman** [comment]
See discussion in https://github.com/flutter/flutter/issues/14719#issuecomment-591815024
https://github.com/flutter/flutter/issues/15279

**Comment by jmagman** [comment]
Feature request covered by https://github.com/flutter/flutter/issues/13611 and https://github.com/flutter/flutter/issues/15279 and closed with cause https://github.com/flutter/flutter/issues/14719, I don't think we need another one.  Feel free to chime in on the open issues.
