### ISSUE TITLE
AndroidX incompatibilities in a plugin "connectivity"

### ISSUE THREAD

**Issue by Adityapanther** [flutter/flutter#73664]
### **getting error while building debug of my app and full error code written below**

`FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:processDebugResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     C:\Users\Aditya_kumar\.gradle\caches\transforms-2\files-2.1\a3b8085db30285646632e9aaa0c95070\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s
Running Gradle task 'assembleDebug'...                            123.6s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...                         8.9s

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'connectivity'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

Exception: The plugin connectivity could not be built due to the issue above.`

**Comment by iapicca** [comment]
@Adityapanther 
please provide your `flutter doctor -v`, your `flutter run -v` and your `pubspec.yaml`

**Comment by Adityapanther** [comment]
**this is my `flutter doctor -v` data witten below**

`[ΓêÜ] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 6.3.9600]
    locale en-IN)
    ΓÇó Flutter version 1.22.5 at C:\flutterSDK\flutter
    ΓÇó Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    ΓÇó Engine revision ae90085a84
    ΓÇó Dart version 2.10.4

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK version 30.
3)
    ΓÇó Android SDK at F:\Sdk
    ΓÇó Platform android-30, build-tools 30.0.3
    ΓÇó ANDROID_HOME = F:\Sdk;F:\Sdk\platform-tools
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    ΓÇó All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.`

### this is My `pubspec.yaml` data written below and `//` written at the place of` #`

`name: #####
description: A new Flutter project.

// The following line prevents the package from being accidentally published to
// pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

// The following defines the version and build number for your application.
// A version number is three numbers separated by dots, like 1.2.43
// followed by an optional build number separated by a +.
// Both the version and the builder number may be overridden in flutter
// build by specifying --build-name and --build-number, respectively.
// In Android, build-name is used as versionName while build-number used as versionCode.
// Read more about Android versioning at https://developer.android.com/studio/publish/versioning
// In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
// Read more about iOS versioning at
// https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  // The following adds the Cupertino Icons font to your application.
  // Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  youtube_player_flutter: ^7.0.0+7
  google_fonts: ^1.1.1
  http: ^0.12.2
  // connectivity: ^2.0.2
  permission_handler: ^5.0.1+1
  flutter_spinkit: "^4.1.2"
  // flutter_native_admob: ^2.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

// For information on the generic Dart part of this file, see the
// following page: https://dart.dev/tools/pub/pubspec

// The following section is specific to Flutter.
flutter:

  // The following line ensures that the Material Icons font is
  // included with your application, so that you can use the icons in
  // the material Icons class.
  uses-material-design: true

  // To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/i1.jpg
    - assets/images/i2.jpg
    - assets/images/i3.jpg
    - assets/icons/movies.png
    - assets/icons/news.png
    - assets/icons/web-series.png
    - assets/icons/movies-blue.png
    - assets/icons/news-blue.png
    - assets/icons/web-series-blue.png


`

**Comment by iapicca** [comment]
```yaml
// The following adds the Cupertino Icons font to your application.
// Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^1.0.0
flutter_svg: ^0.19.1
youtube_player_flutter: ^7.0.0+7
google_fonts: ^1.1.1
http: ^0.12.2
// connectivity: ^2.0.2
permission_handler: ^5.0.1+1
flutter_spinkit: "^4.1.2"
// flutter_native_admob: ^2.1.0+3
```

@Adityapanther 
odd, you are getting a connectivity error, but your [connectivity](https://pub.dev/packages/connectivity) plugin is commented out in your `pubspec.yaml`
can you provide a minimal reproducible code sample?

**Comment by Adityapanther** [comment]
@iapicca 
yes, I was commented [connectivity](url) plugin because I have to build my project for ui testing

**Comment by darshankawar** [comment]
@Adityapanther 
Your log clearly shows the error:

`C:\Users\Aditya_kumar\.gradle\caches\transforms-2\files-2.1\a3b8085db30285646632e9aaa0c95070\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.`

What gradle version are you using ? If its 3.5.0, try to upgrade to 4.1.0 and try again to see if it works.

One of the plugins you are using may not be compatible with the <queries> tag, so you'd need to upgrade your gradle version along with gradle `distributionurl` in `gradle-wrapper.properties`.  See [this](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-possible-solution-1) for reference.

**Comment by Adityapanther** [comment]
@darshankawar 
my gradle version is 4.6.0

**Comment by darshankawar** [comment]
@Adityapanther 
Can you try by removing each plugin one by one and check if any of the plugins is causing that issue ?
Also, provide `project level and app level `build.gradle`.

**Comment by Adityapanther** [comment]
@darshankawar 
I tried that then I found that connectivity plugins is causing that issue.

**Comment by darshankawar** [comment]
@Adityapanther 
Can you provide a repo of your project that we can clone and verify the issue ?

**Comment by Adityapanther** [comment]
@darshankawar 

sorry, I can't provide my project repo due to project privacy.

**Comment by darshankawar** [comment]
@Adityapanther 
I understand and we are not asking your private project repo. A clone of your private repo with demo / sample code that doesn't involve any of your project related code (and contains only minimal reproducible code sample in it) that we can clone and try to replicate / verify the issue.

**Comment by Adityapanther** [comment]
@darshankawar 
ok, I will provide you soon.

**Comment by Adityapanther** [comment]
@darshankawar 
I am getting same issue with admob package

**Comment by darshankawar** [comment]
@Adityapanther 
`admob` is a firebase plugin which has separate repo for tracking issues. Are you only getting this error using `admob` ?
Also, I am not completely sure what exactly your issue is. It's better you provide a sample repo.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Adityapanther** [comment]
when I added `multidex= true` and `multidex` dependencies in app level `build.gradle` file it worked for me.

**Comment by roderikpeeters** [comment]
> app
can you show us exact what did you? Im having the same problem and I already have multidex enabled.

**Comment by Adityapanther** [comment]
@roderikpeeters like this in `app` level `build.gradle` file
```
android {
    defaultConfig {
        multiDexEnabled true
    }
}

dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
}
```
