### ISSUE TITLE
Incorrect dimensions of generated PNG image using HTML renderer (but correct using CanvasKit)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [flutter/flutter#73661]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace main.dart with the file contained in [main.zip](https://github.com/flutter/flutter/files/5791890/main.zip)
3. Run this file in Chrome (web) device.
4. Click the Generate image button.
5. The generated image is shown and also downloaded immediately.

**Expected results:** 
As the source graphics is rendered in size 100x100px, I am expecting the PNG size of 100x100px. 

**Actual results:** 
The size of downloaded PNG file is 154x154px.
![html](https://user-images.githubusercontent.com/3907898/104109496-cf531000-52ce-11eb-8bfb-89ce1b133794.png)
However, running example using the CanvasKit renderer I am getting the correct size.
![canvaskit](https://user-images.githubusercontent.com/3907898/104109499-cfeba680-52ce-11eb-89dc-d032152db7a1.png) 

<details>
  <summary>Logs</summary>

```
info - Avoid using web-only libraries outside Flutter web plugin packages - lib\main.dart:4:1 - avoid_web_libraries_in_flutter
```

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\flutter-sdk\flutter
    • Framework revision 8f89f6505b (4 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\j.tosovsky\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\RedHat\java-11-openjdk-11.0.8-2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\j.tosovsky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 79.0.309.65

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @jan-tosovsky-cz 
I was able to reproduce the issue on latest beta channel. On latest master channel it seems to work as expected without canvasKit, can you please verify that?
Thank you

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-8.2.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision b0a2299859 (6 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.275 at /Users/pedromassango/Code/flutter_master
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Comment by ferhatb** [comment]
Verified with -web-renderer=html that it generates:
```
<img src="blob:http://localhost:61480/9279d412-694e-4252-9e70-65be77887244" decoding="async" style="position: absolute; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 1.5, 1); left: 0px; top: 0px; width: 100px; height: 100px;">
```

**Comment by jan-tosovsky-cz** [comment]
I've upgraded Flutter to master channel and the result is same. However, I had to explicitly specify -web-renderer=html in the flutter command as default seems to be changed from html to canvaskit (what could be the reason you see the correct result in master).

flutter **beta**:
`<img src="blob:http://localhost:64083/661612da-391a-49a6-b706-9bc3ec36949b" decoding="async" style="position: absolute; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 1.66667, 1); left: 0px; top: 0px; width: 100px; height: 100px;">`

flutter **master**:
`<img src="blob:http://localhost:51851/eda4ecbb-e7c3-42ec-9435-8b6adf69c322" decoding="async" style="position: absolute; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 1.66666, 1); left: 0px; top: 0px; width: 100px; height: 100px;">`

<details>
  <summary>flutter doctor -v</summary>
[√] Flutter (Channel master, 1.26.0-2.0.pre.287, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.26.0-2.0.pre.287 at C:\flutter-sdk\flutter
    • Framework revision 0b5905070c (33 minutes ago), 2021-01-11 21:57:40 +0100
    • Engine revision bbf8668d53
    • Dart version 2.12.0 (build 2.12.0-212.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\j.tosovsky\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\RedHat\java-11-openjdk-11.0.8-2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\j.tosovsky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 79.0.309.65

! Doctor found issues in 2 categories.
</details>

**Comment by darshankawar** [comment]
@jan-tosovsky-cz 
Tried running the code you provided in original description and updated it based on latest framework, but while running, getting below compile error:

`LateInitializationError: Field 'imgBytes' has not been initialized.`

Can you confirm if you still have same error using latest framework versions ? If so, can you provide updated code sample ?
