### ISSUE TITLE
Code coverage compatibility with Dart SDK 1.22

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7366]
With Dart SDK 1.22, the VM service protocol has added a security token in its URIs, so that observatory URIs now look like `http://127.0.0.1:54804/PTwjm8Ii8qg=/` rather than just a host port pair.

We're updating `package:coverage` APIs with a breaking change to take a base URI rather than host and port parameters which will be released in version 0.9.0.

On the Flutter side, we'll need a small patch to the platform plugin code coverage collection logic once the new version of `package:coverage` is released.

[Related announcement](https://groups.google.com/a/dartlang.org/forum/#!msg/announce/VxSw-V5tx8k/wPV0GfX7BwAJ)

**Comment by eseidelGoogle** [comment]
This is resolved, correct?

**Comment by cbracken** [comment]
I've completed the work in `package:coverage` but it's likely we still need a little work in `flutter_tools`. I'll take a look at verifying and landing required patches in the next couple days.

After speaking with @johnmccutchan it sounds like the auth token will not be required in 1.22 unless the VM is called with an environment variable set that enables this behaviour.
