### ISSUE TITLE
when will flutter desktop support sqlite etc. plugin

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#73671]
go-flutter-desktop has many support on plugins such as shared_preference, sqflite etc. But it's not official and not support very well with Chinese charactors on Linux.

When will flutter official will add plugin support plan on those **very** common use plugin such as sqflite?

**Comment by stuartmorgan** [comment]
All of the plugin APIs necessary for a plugin like sqflite are supported on all three desktop platforms, and have been for some time. Questions about if or when a given third-party plugin will add desktop support need to be directed to the developer of that plugin.

Alternately, nothing is preventing anyone from making their own independent federated implementation of existing plugins (exactly as was done for go-flutter-desktop).

**Comment by jinfagang** [comment]
@stuartmorgan  But when I run `flutter run` on linux, it can show main screen but will tell me no plugin for sqflite etc. go-flutter-desktop supports very well but they seems ignore much more general usage such as showing Chinese characters on Linux, inputing Chinese characters on Linux etc. So I suppose official one could be much more stable and general to support all that.

**Comment by stuartmorgan** [comment]
> @stuartmorgan But when I run `flutter run` on linux, it can show main screen but will tell me no plugin for sqflite

I didn't say that it had already been implemented, I said that the APIs necessary to implement it are already available in Flutter, and that actually implementing the plugin is up to someone else given that it's a third-party plugin.

> go-flutter-desktop supports very well

Because someone wrote an implementation of the sqflite plugin for that embedding.

**Comment by jinfagang** [comment]
@stuartmorgan So there is no one in community do such a thing?

**Comment by stuartmorgan** [comment]
Again:

> Questions about if or when a given third-party plugin will add desktop support need to be directed to the developer of that plugin.
