### ISSUE TITLE
Seperate flutter.so from app package

### ISSUE THREAD

**Issue by lxb0478** [flutter/flutter#73680]
Currently flutter.so is packaged into application, I'm wondering why not put flutter.so as part of platform, so that application package size will be decreased.

**Comment by Skyost** [comment]
@lxb0478 Well, because <q>they're just Flutter</q>, they have no control over Android nor iOS 😄

**Comment by pedromassangocode** [comment]
I remember @Hixie  giving a pretty good reason why libflutter.so ships with the app and not in the platform it self but I can't find that comment.

**Comment by chinmaygarde** [comment]
Closing this as inactionable.

**Comment by Hixie** [comment]
@lxb0478 The reason why not is that libflutter.so changes every time we have a release (so, multiple times a day if you count releases on master, several times a year if you count releases only on the stable channel), and there are hundreds of thousands of Flutter applications each of which could have different libflutter.so files, so it's not clear how we would convince the platform owners to host the libflutter.so files. (For example, Apple are unlikely to want to host even one file, let alone several per year.)
