### ISSUE TITLE
[web]: Flutter web development server, serve JS file with wrong MIME type

### ISSUE THREAD

**Issue by dhorajiaabhishek** [flutter/flutter#73687]
Hi Team,
I am trying to integrate firebase_messaging package on my web project.
On development server, I am getting error while generating firebase token
```
The script has an unsupported MIME type ('application/octet-stream').
 [firebase_messaging/failed-service-worker-registration] Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:19656/firebase-cloud-messaging-push-scope') with script ('http://localhost:19656/firebase-messaging-sw.js'): The script has an unsupported MIME type ('application/octet-stream'). .
```
Cause of this error is wrong MIME type of .js file in development server.
But it work find when I release build on IIS.
As JS on IIS are serve with proper MIME type (text/javascript)

**Comment by darshankawar** [comment]
@dhorajiaabhishek 
This seems to be an issue using the firebase_messaging plugin, which has separate repo for tracking. https://github.com/FirebaseExtended/flutterfire/issues
Closing from here.
