### ISSUE TITLE
[PARSE][Double] Incorrect Double to String value when trying parse a long String to Double

### ISSUE THREAD

**Issue by khanhnt748** [flutter/flutter#73692]
Hi all,
Currently I am try parse a String` '111222333444555666'` to Double by using `double.parse` and `double.tryParse` but both of them have an result `111222333444555660` (with the zero in the end).
I have try with those codes below:
```dart
var data = '111222333444555666';
var expectedResult = 111222333444555666;
var number1 = double.parse(data);
var number2 = double.tryParse(data);
if (number == expectedResult) {
   print('Value is matched');
} else {
   print('Value is not matched');
}
```
The result: `Value is matched` and its value is '111222333444555660'.
I want find out what happen with the last digit?!
Thank you and best regards.

Note that my Flutter SDK version `1.22.5 stable channel` on `Mac OS X 10.15.5 `
![Screenshot](https://user-images.githubusercontent.com/30397729/104156496-c2900280-541b-11eb-9f50-7f92be7ff809.png)

**Comment by stuartmorgan** [comment]
Doubles have fixed storage size, and thus a fixed precision; see https://en.m.wikipedia.org/wiki/Double-precision_floating-point_format

If you want arbitrary levels of precision you'll need to use a special library that handles numbers differently.
