### ISSUE TITLE
HUAWEI and Xiaomi mobile phones appear jittery and drop frames

### ISSUE THREAD

**Issue by liubing1007** [flutter/flutter#73694]
我发现部分手机（华为和小米）滑动就出现抖动掉帧，非常简单的demo都会出现抖动掉帧 ，是release包也会出现，三星和苹果手机没问题，有没有解决方案，我们的客户主要是小米和华为手机

**Comment by pedromassangocode** [comment]
Hi @liubing1007 
Please avoid posting comments in non-English language as we use English as the only way to communicate in Flutter community.

Can you please provide a reproducible code sample and steps to reproduce the issue along with your `flutter doctor -v`? Please share how you are measuring performance as well.

Thank you

[from Google Translate]
@ liubing1007，您好：请避免以非英语发表评论，因为我们将英语作为在Flutter社区中交流的唯一方法。 您能否与您的Flutter Doctor -v一起提供可复制的代码示例和重现此问题的步骤？ 请分享您如何衡量绩效。 谢谢

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
