### ISSUE TITLE
[webview_flutter] v1.0.7  Flutter webview resume app from Background show white screen

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#73703]
flutter doctor:

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

首页是个 webview 页面。 打开app,  然后(保证 webview 能加载 url) 立马进入后台，过 2s 切换回这个app, 显示空白。【The home page is a webview page. Open the app, then (make sure the webview can load the url) immediately enter the background, switch back to this app after 2s, and the display is blank.】

**Comment by darshankawar** [comment]
@OHeroJ 
What devices you see this issue on ? Can you provide video of it ?
Also see [this](https://github.com/flutter/flutter/issues/48867) similar but closed issue and confirm if it resemble yours.

https://github.com/flutter/flutter/issues/48867#issuecomment-739932854

**Comment by OHeroJ** [comment]
> @OHeroJ
> What devices you see this issue on ? Can you provide video of it ?
> Also see [this](https://github.com/flutter/flutter/issues/48867) similar but closed issue and confirm if it resemble yours.
> 
> [#48867 (comment)](https://github.com/flutter/flutter/issues/48867#issuecomment-739932854)

i just have iPhoneX.

**Comment by OHeroJ** [comment]
还有就是如果首页是 webview, 然后通过 testflight 测试下载的app, 进入app 会出现版本升级的信息，这个时候首页的 webview 也会空白。(Also, if the homepage is webview, and then test the downloaded app through testflight, a version upgrade message will appear when entering the app, and the webview on the homepage will also be blank at this time)

**Comment by darshankawar** [comment]
@OHeroJ 
I tried the official `webview_flutter` plugin example on latest stable using iOS simulator but didn't notice the white screen while bringing app from background.
Can you provide video of the issue ?

**Comment by OHeroJ** [comment]
controller.refresh()
