### ISSUE TITLE
[proposal] Add an enabled bool to RaisedButton and deprecate, use of Null by onPressed

### ISSUE THREAD

**Issue by elansys-kc** [flutter/flutter#73700]
## Use case

I have a custom button that wraps RaisedButton. When updating the code to be compatible with null safe OnPressed. I noticed in the website documentation that a null is used to disable the button ( a feature that I had missed or not bothered with). It occurred to me that a disabled Bool named parameter would be far more readable and shown in the IDE and not just in the web documentation. 

My Button wrapper now has a required "disabled" bool parameter that passes null to RaisedButtons onpressed when present and I find it to be not only simpler but an improvement, whilst avoiding any ? syntax and extra null safety code.

<pre>
          RaisedButton(
            onPressed: (!askPass.isValid) ? null : askPass.Submit,
          ),
</pre>
<pre>
          ElansysButton(
            onPressed: askPass.Submit,
            disabled: !askPass.isValid,
          ),
</pre>
          
## Proposal

Add an enabled bool to RaisedButton and deprecate, use of Null by onPressed.

Additionally when migrating to null safety either during or after the initial compatibility work. Flutter could aim to avoid nulls unless required especially where there use may seem logical but is not required and certainly where it isn't optimal to readability. Such as where a simple bool or empty string causes no issue.

**Comment by pedromassangocode** [comment]
Hi @elansys-kc 
I see there's an open issue (https://github.com/flutter/flutter/issues/58867) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
