### ISSUE TITLE
"Build infra failed", but all steps succeeded

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73718]
This `Linux animated_placeholder_perf__e2e_summary` build is marked "Build infra failed" and closed the tree, but it looks like all steps succeeded.
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20animated_placeholder_perf__e2e_summary/279/overview

When I switch back to legacy view I see the `flutter doctor` step is blue but I'm not sure what went wrong and if it's something to fix on the Flutter recipe side:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20animated_placeholder_perf__e2e_summary/279

**Comment by godofredoc** [comment]
This happened because the bot died:

https://chromium-swarm.appspot.com/task?id=510b83298c9da910&o=true&w=true

**Comment by godofredoc** [comment]
Obsolete.
