### ISSUE TITLE
SMS format differs when launched using SMS launcher on android 9 and 10

### ISSUE THREAD

**Issue by cntoss** [flutter/flutter#73717]
While sending sms from url_launcher package.  SMS output is not symmetric on android 10 and 9 below is my code 

**Result in android 9:** Message: Hello Developer Welcome 

**Result in android 10:** Message: Hello+Developer+Welcome 

    void sendSMS() async {
      String message = 'Hello+Developer+Welcome';
      String scheme = 'sms:7005?body=${Uri.encodeFull('Message: $message')}';
      if (await canLaunch(scheme)) {
        await launch(scheme);
      } else {
        print('problem on launcher');
      }
     }

**Alternatively** 
If I replaced '+' symbol by '\%2B' then result was changed
**Result in android 9:** Message: Hello+Developer+Welcome 

**Result in android 10:**  Message: Hello Developer Welcome

Below is code

        void sendSMS() async {
        String message = 'Hello+Developer+Welcome';
        String mesWithoutPlus = message.replaceAll('+', '\%2B');
        String scheme =
            'sms:7005?body=${Uri.encodeFull('Message: $mesWithoutPlus')}';
        if (await canLaunch(scheme)) {
          await launch(scheme);
        } else {
          print('problem on launcher');
        }
      }
**Android 9**    
![9](https://user-images.githubusercontent.com/47077442/104275130-61733800-54ca-11eb-8058-32835cacdaab.png)
**Android 10**
![10](https://user-images.githubusercontent.com/47077442/104275141-646e2880-54ca-11eb-947b-cc3604590080.jpg)

**Comment by darshankawar** [comment]
Issue reproducible using latest stable version. 

1. Android 11:

<img width="544" alt="Screenshot 2021-01-12 at 1 52 32 PM" src="https://user-images.githubusercontent.com/67046386/104289093-b6b94480-54de-11eb-967e-57b359738432.png">

2. Android 8:

<img width="544" alt="Screenshot 2021-01-12 at 1 52 32 PM" src="https://user-images.githubusercontent.com/67046386/104289136-c5076080-54de-11eb-96d6-b722f6ae11bd.png">

3. Android 9:

<img width="332" alt="Screenshot 2021-01-12 at 2 00 04 PM" src="https://user-images.githubusercontent.com/67046386/104289151-cc2e6e80-54de-11eb-8985-6933ff0cfe43.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 64 arm64 (mobile)    • emulator-5554
      • android-x64 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • AOSP on IA Emulator (mobile)        • emulator-5556
      • android-x86 • Android 9 (API 28) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by cntoss** [comment]
### Temporary fixed: 

        var androidInfo = await DeviceInfoPlugin().androidInfo;
        var release = androidInfo.version.release;
        print(release);
        if (release != '10') {
          scheme= scheme.replaceAll('+', '\%2B');
        }

**Comment by stuartmorgan** [comment]
See https://github.com/dart-lang/sdk/issues/43838 for more discussion. We need to update the docs to flag this since it's happening for several common schemes on recent versions of Android.

**Comment by d9media** [comment]
> ### Temporary fixed:
> ```
>     var androidInfo = await DeviceInfoPlugin().androidInfo;
>     var release = androidInfo.version.release;
>     if (release != '10') {
>       scheme= scheme.replaceAll('+', '\%2B');
>     }
> ```

This didn't work for us in IOS.

Here's what did:

`final String _emailUriString = _emailLaunchUri
                                .toString()
                                .replaceAll('+', '\%20');`

Not tested in Android yet.

**Comment by stuartmorgan** [comment]
For SMS, for now the safest and simplest approach would be `encodeComponent`. E.g.,:

```
String message = 'Your SMS message body here';
String urlString = 'sms:7005?body=${Uri.encodeComponent(message)}';
```

(`encodeFull` is not intended for individual components, so the original code in this issue wasn't correct.)

**Comment by stuartmorgan** [comment]
In general (e.g. for `mailto`) see https://github.com/dart-lang/sdk/issues/43838#issuecomment-823551891 for a safer workaround for now than a `replaceAll`; the `url_launcher` README will be updated accordingly, likely with a utility method for this added to the API surface.
