### ISSUE TITLE
Mac build_gallery failed, unable to find sdk 'iphoneos14.0' 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73721]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_gallery/960/overview
```
    error: unable to find sdk 'iphoneos14.0' (in target 'video_player' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'url_launcher' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'Pods-Runner' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'Reachability' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'Flutter' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'device_info' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'Runner' from project 'Runner')
    error: unable to find sdk 'iphoneos14.0' (in target 'connectivity' from project 'Pods')
    error: unable to find sdk 'iphoneos14.0' (in target 'integration_test' from project 'Pods')
```

**Comment by yusufm** [comment]
It seems like the tests is getting its properties from the system installation of xcode (new version), and not the sandbox version (which is older and does not contain the sdk)

**Comment by jmagman** [comment]
Another: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858373866854169456/+/steps/prepare_environment/0/steps/Build_gallery/0/steps/build_gallery/0/stdout
Did something change with this test?

**Comment by jmagman** [comment]
Also why is it passing on some bots and not others?  It passed on a re-run.

**Comment by jmagman** [comment]
This is keeping the tree closed, it's failed 3 times in a row on the last commit.

**Comment by jmagman** [comment]
Also interesting it only seems to be failing on `Mac build_gallery`, not the many other thats are building iOS apps like `Mac build_tests`.

**Comment by jmagman** [comment]
I temporarily turned these tests off so it doesn't keep the tree closed https://github.com/flutter/flutter/pull/73728

**Comment by jmagman** [comment]
@keyonghan This isn't the same manifestation of [Swift being missing](https://github.com/flutter/flutter/issues/73606), but maybe `mac_build_gallery` also needs the updated Xcode version? https://github.com/flutter/infra/pull/325

**Comment by jmagman** [comment]
Eh nevermind that was a devicelab config, this is happening on luci.
