### ISSUE TITLE
Windows devicelab agents offline, Windows tests not being run

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73737]
flutter-devicelab-windows-1 and flutter-devicelab-windows-2 are down, post-submit devicelab tests are not being run.
<img width="171" alt="Screen Shot 2021-01-11 at 1 49 32 PM" src="https://user-images.githubusercontent.com/682784/104242299-d6d00180-5413-11eb-9895-caff73da4c90.png">

**Comment by jmagman** [comment]
Maybe a planned outage, or part of the cutover?

**Comment by yusufm** [comment]
This was not a planned outage. Investigating.

**Comment by yusufm** [comment]
Power cycled them through the PDU, they seem to be back up and running:

![image](https://user-images.githubusercontent.com/463376/104249164-b312b880-541f-11eb-8f40-475e318b7921.png)
