### ISSUE TITLE
[pigeon] Add support for Windows

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#73739]
## Use case

Currently, [pigeon](https://pub.dev/packages/pigeon) only supports generating for iOS and Java and allows very easy platform calls.

However, plugins might also want to support **Windows** and use pigeon for that. cc @gaaclarke 

### Other desktop platforms

See also:

* macOS feature request: https://github.com/flutter/flutter/issues/73738
* Linux feature request: https://github.com/flutter/flutter/issues/73740

**Comment by ram231** [comment]
Just want to link this issue for Web. #98084

**Comment by stuartmorgan** [comment]
Closing, as the C++ generator landed a while ago. Remaining issues with that generator are tracked separately.
