### ISSUE TITLE
make IOSContextGL conform to "GetMainContext()"

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#73744]
Currently IOSContextMetal reuses the same skia context across surfaces, IOSContextGL creates a new one for each surface and there is no concept of the skia context for surfaces in the IOSContext.

I added a virtual method for IOSContext for skia contexts (I promoted the IOSContextMetal api to its superclass) but the OpenGL variant hasn't been updated to use it yet.  We should start using it to make the code more similar and potentially remove some of the static casts we have in the code to downcast IOSContexts.

see also: https://github.com/flutter/engine/pull/23539

**Comment by jonahwilliams** [comment]
IOSContextGL  is deleted so I'm closing this bug
