### ISSUE TITLE
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

### ISSUE THREAD

**Issue by Max-Job** [flutter/flutter#73742]
## Steps to Reproduce

1. I use webview_flutter: ^1.0.7

2. There aren't any crashes, but I get error in console:

> Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by TahaTesser** [comment]
Hi @Max-Job 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
