### ISSUE TITLE
Support specifying button size in new material button styles and button themes

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#73741]
The only way to enforce a fixed height on buttons currently is to wrap the buttons in a sized box. Adding a `fixedSize` parameter to button styles and themes would mitigate this issue.

**Comment by pedromassangocode** [comment]
[cross-reference]
Similar to https://github.com/flutter/flutter/issues/62882.

**Comment by kenzieschmoll** [comment]
Reopening this issue. It often is the case that we only know the button height, but not necessarily the width (dynamic text or resizable text). Is there any way we can add a parameter for fixedHeight and fixedWidth instead, enforcing only whichever one (or both) that are specified?

**Comment by HansMuller** [comment]
To specify buttons with a fixed width and the default height use fixedSize: Size.fromWidth(320). Similarly, to specify a fixed height and the default width use fixedSize: Size.fromHeight(100).
