### ISSUE TITLE
App running slow on "SystemView 10" Device

### ISSUE THREAD

**Issue by riteshakya037** [flutter/flutter#73775]
## Details

So I was testing my application on [this](https://www.easyio.eu/products/hmi-products/sh-systemview10/), and noticed it was unbearably sluggish.

I tried installing a version specific to armeabi-v7 by using split, but to no luck. After which I though maybe it was something wrong with my code so create a fresh new project and tried installing it. This also resulted in the same performance issue.

I know this is an OEM device and wouldn't be in the testing suite, but I just wanted to know if there is something that can be done, or else if this is a lost case. 

**Target Platform:** Android
**Target OS version/browser:** API 23
**Devices:** [SystemView 10”](https://www.easyio.eu/products/hmi-products/sh-systemview10/)

## Logs

<details>
<summary>Logs</summary>

````
> flutter analyze
Analyzing nube_mqtt_dashboard...                                        

   info • The value of the field '_page' isn't used • lib/application/layout/pages/pages_cubit.dart:12:20 • unused_field

1 issue found. (ran in 12.4s)
````

```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.22.5 at /home/hill/snap/flutter/common/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/hill/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/hill/Android/Sdk
    • Java binary at: /home/hill/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[!] Android Studio
    • Android Studio at /home/hill/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/hill/Downloads/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1
[✓] Connected device (1 available)
    • EasyIO SystemView10 (mobile) • 20080411 • android-arm • Android 6.0.1 (API 23)
! Doctor found issues in 1 category.
```

</details>

> Export from Observatory (In txt cause I couldn't include json)
[dart-timeline-2021-1-12.txt](https://github.com/flutter/flutter/files/5800435/dart-timeline-2021-1-12.txt)

> Video Export
[![Video Of the Device in action](https://img.youtube.com/vi/aQSrOHh0AJ0/0.jpg)](https://www.youtube.com/watch?v=aQSrOHh0AJ0 "Video Of the Device in action")

**Comment by pedromassangocode** [comment]
Hi @riteshakya037 
Can you please provide your `flutter run --verbose`, the actual vs expected results and a minimal complete reproducible code sample?
Thank you

**Comment by riteshakya037** [comment]
I can send you the verbose next working day, since I don't have the device at hand atm. 

My main concern is that even the starting flutter counter app runs a sluggish. I've attached a video recording of the starter app. 

[![Flutter Counter App](https://img.youtube.com/vi/vC7lx9qhWxA/0.jpg)](https://www.youtube.com/watch?v=vC7lx9qhWxA "Flutter Counter App")

**Comment by riteshakya037** [comment]
As promised I have attached `flutter run --verbose` logs. As for the minimal complete reproducible code sample, the delay is throughout the app so, it's not like its a piece of code. 

[actual_app_verbose_logs.txt](https://github.com/flutter/flutter/files/5806536/actual_app_logs.txt)


Here's the export of Observatory for the sample counter app running on the tablet. 


[![Flutter Counter App](https://img.youtube.com/vi/vC7lx9qhWxA/0.jpg)](https://www.youtube.com/watch?v=vC7lx9qhWxA "Flutter Counter App")
[dart-timeline-2021-1-13 Counter App.txt](https://github.com/flutter/flutter/files/5806576/dart-timeline-2021-1-13.Counter.App.txt)

**Comment by kf6gpe** [comment]
Is this generally reproducible on Android API 23? It will be difficult to root cause this without the hardware. It's possible that it's due to the hardware itself; it looks like that platform is based on a 7-year-old SOC. We may just not be able to perform adequately on it.  As filed, we're afraid this isn't actionable.

**Comment by riteshakya037** [comment]
@kf6gpe Thanks for the response. As you mentioned it isn't reproducible on API 23. And since it is most probably because of the outdated SoC the best approach would be to upgrade the hardware and move forward anyways.
