### ISSUE TITLE
Implement CupertinoDatePicker

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7377]
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/#date-pickers

**Comment by eseidelGoogle** [comment]
Posse has received a lot of negative feedback about their current use of a Material Datepicker on iOS (for picking a birthday).  Supposedly it's the most common complaint from their current set of iOS users.  If we don't write a CupertinoDatePicker in the next few weeks they will likely write their own.  Both paths are of course viable.  Will depend on how busy @xster or @HansMuller are with other tasks as to if we try to take this one on in the short term.

**Comment by Hixie** [comment]
It's not on our short-term priority list, so if we decide to do it we should decide what we're not doing instead.

**Comment by Hixie** [comment]
Moving to next milestone since Cupertino widget improvements aren't on our short-term priority list.

**Comment by eseidelGoogle** [comment]
My understanding is that @xster just landed a UIPickerView equivalent in Flutter from which it should now be possible to build a date-picker like control in cupertino.

**Comment by rajeshzmoke** [comment]
Checkout my repo, i've created a custom Cupertino style Date Picker

https://github.com/rajeshzmoke/Flutter_cupertino_date_picker

**Comment by DaveShuckerow** [comment]
A new team member is working on this as a starter project. I'll assign to him once his GitHub account is linked.

**Comment by xster** [comment]
Ah I see. I wasn't able to find him for assignment. Thanks!

**Comment by xster** [comment]
@doxuanviet1996: sorry I didn't catch you in the office today. re: the builder API, I chatted with @Hixie today. Let's keep the whole thing in the RenderBox system without bringing in slivers. We can extend the existing RenderListWheelViewport to take in a delegate similar but simpler than RenderSliverBoxChildManager and let the RenderListWheelViewport instantiate those RenderBox children lazily similar to how RenderSliverList creates uncreated children lazily during layout. 

In the widget layer, let's keep the ListWheelScrollView API backward compatible by adding creating this delegate behind the scene in the default constructor and letting there be a separate builder factory like ListView does.

**Comment by cosinus84** [comment]
I tried other date picker widgets, neither one is complete. What I found is not looking like native ios, or others are somehow slow. This native widget is a must for quick productivity.

**Comment by markmooibroek** [comment]
I think its still missing docs, and not in beta channel yet?

**Comment by xster** [comment]
cc @gspencergoog. I think we had some temporary issues with doc generation. Should be back shortly.
