### ISSUE TITLE
Disabled ListTile theme colors are not applied to the leading and trailing text widgets

### ISSUE THREAD

**Issue by sm2017** [flutter/flutter#73781]
## Steps to Reproduce

From documentation for `enabled` property we have
>Whether this list tile is interactive.
> If false, this list tile is styled with the disabled color from the current Theme and the onTap and onLongPress callbacks are inoperative.

The disabled color is no applied to **leading** and **trailing**
```dart
ListTile(
      leading: FlutterLogo(size: 56.0),
      title: Text('Two-line ListTile'),
      subtitle: Text('Here is a second line'),
      trailing: Text('Trailing'),
      enabled: false,
    );
```

**Expected results:** 

The disabled theme must be applied to **leading** and **trailing** too

**Actual results:** 

![image](https://user-images.githubusercontent.com/19644997/104304121-398ecf00-54e0-11eb-9a29-58fac7c5a21f.png)

**Comment by xu-baolin** [comment]
@shihaohong Hi,
The `leading` and `trailing` are typically an [Icon] or a [CircleAvatar] widget, so we only apply the `IconTheme`.
Do you think we should add `AnimatedDefaultTextStyle` for those?

**Comment by darshankawar** [comment]
<img width="546" alt="Screenshot 2021-01-12 at 6 47 37 PM" src="https://user-images.githubusercontent.com/67046386/104319445-e11ef800-5506-11eb-8a56-cb92e2bb6a1f.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.

```

</details>

**Comment by shihaohong** [comment]
@xu-baolin That's one way to approach it. The biggest concern is that it will likely be a pretty breaking change since `ListTile`s are pretty common. Since the expected behavior seems more common, we could try and push this change, and if it happens to be too breaking (a lot of customer tests fail), then we can always revert.

**Comment by xu-baolin** [comment]
OK, I will try it.

**Comment by shihaohong** [comment]
I'm looking into the internals for ListTile and it looks like the way that text is styled for the `title` and `subtitle` widgets can be pretty complicated. Maybe just start with modifying the text's disabled color to prevent too big of a change.

**Comment by xu-baolin** [comment]
That'll be great! 👍
