### ISSUE TITLE
Ability to show null pointer fields

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#73788]
```
'<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
The relevant error-causing widget was: 
   PaddingAll
```

The line numbers specified are never correct, and it takes forever to find problems. It would be nice if something like

```
'<Unexpected Null Value>:  PADDING (line number)'
The relevant error-causing widget was: 
   PaddingAll (an actually correct line number)
```

**Comment by iapicca** [comment]
@cyberpwnn 
I'm not sure how wise could be investing resources into mitigating null pointer "interactions"
when [null safety](https://flutter.dev/docs/null-safety) is in the pipeline

**Comment by darshankawar** [comment]
@cyberpwnn 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
