### ISSUE TITLE
Face Id not work in iphone 12

### ISSUE THREAD

**Issue by MajidAlNuumani** [flutter/flutter#73782]
Hi all,

I face issue with some of iPhone 12 pro and all iPhone 12 pro max that Face ID prompt not show.

I am using https://github.com/agens-no/EllipticCurveKeyPair to create signature and send it to server.

I am developing in flutter and using MethodChannel as bridge between flutter and swift code.

My app works in other iPhone without any issue in Face ID.

Please assist if any changes happen in Flutter, iPhone 12 devices, or it is related to my code.

**Comment by darshankawar** [comment]
@MajidAlNuumani 
By Face ID, do you mean the Face ID of iphone that we use to unlock phone ? 
If so, not sure how is your issue related to Flutter framework. The link you mentioned above seems to be 3rd party.
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
