### ISSUE TITLE
codesigning server down?

### ISSUE THREAD

**Issue by pcsosinski** [flutter/flutter#73796]
i believe the codesigning server is having ssh issues:

flutter@flutter-ssh-bridge-001:~$ ssh 192.168.1.86
ssh: connect to host 192.168.1.86 port 22: Connection refused

/cc @christopherfujino

**Comment by yusufm** [comment]
192.168.1.86 is responding to pings, but ssh is down.

**Comment by christopherfujino** [comment]
does vnc work?

**Comment by christopherfujino** [comment]
I tried connecting via VNC, and it also failed.

**Comment by yusufm** [comment]
Rebooting through the PDU didn't work either.

Might require local intervention to check settings.

**Comment by christopherfujino** [comment]
If the problem is that the setting in macos for ssh has been disabled, we need to figure out how to prevent it in the future. It's happened once before where the ssh flipped from on to off in the OS.

**Comment by yusufm** [comment]
Ticket has been opened to check the host locally. 

Will update post here with any updates.

**Comment by christopherfujino** [comment]
> Ticket has been opened to check the host locally.
> 
> Will update post here with any updates.

Thanks @yusufm

**Comment by yusufm** [comment]
Host is back up. 

(Remote login sharing settings were set via Access >> Sharing >> Remote Login preferences)
