### ISSUE TITLE
[CupertinoDatePicker] should inherit the current theme's brightness by default

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#73795]
## Use case

Using CupertinoDatePicker with a "dark mode" enabled app leads to the following in each mode:

Light mode:
![image](https://user-images.githubusercontent.com/16725750/104353308-c1231080-54d5-11eb-8e4b-648816d7f513.png)

Dark mode (text should be white):
![image](https://user-images.githubusercontent.com/16725750/104353425-def07580-54d5-11eb-86bb-d84c6c055cdb.png)

In order to resolve this the widget must be wrapped in a CupertinoTheme like so:

```dart
CupertinoTheme(
  data: CupertinoThemeData(
      brightness:
          Theme.of(context).brightness,
      ),
  child: CupertinoDatePicker(
    //...
  ),
)
```

## Proposal

Have the CupertinoDatePicker's brightness be set to the current theme's brightness by default.

**Comment by TahaTesser** [comment]
This seems to be working fine, the theme's brightness is inherited without wrapping  `CupertinoTheme`

<details> 
<summary>preview</summary>


![Screenshot 2021-11-12 at 11 19 42 AM](https://user-images.githubusercontent.com/48603081/141442854-ac1edb75-dcba-491c-8328-9433c17899ac.png)




</details>


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      theme: const CupertinoThemeData(
        brightness: Brightness.dark,
      ),
      home: CupertinoPageScaffold(
        navigationBar: const CupertinoNavigationBar(
          middle: Text('Cupertino App Bar'),
        ),
        child: Center(
          child: CupertinoDatePicker(
            mode: CupertinoDatePickerMode.dateAndTime,
            onDateTimeChanged: (dateTime) {},
          ),
        ),
      ),
    );
  }
}
``` 
	
</details>
