### ISSUE TITLE
Increasing the number of linux bots for builds

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#73814]
Periodically the tasks end up in pending state, due to limited bot capacity, triggering alerts:

PENDING swarming tasks: https://chromium-swarm.appspot.com/tasklist?f=pool%3Aluci.flutter.prod&f=state%3APENDING
name: TooManyPendingSwarmingTasks

 We need to increase the number of linux bots to keep up.

**Comment by yusufm** [comment]
@keyonghan can you please help calculate how much new capacity we need.

**Comment by godofredoc** [comment]
@yusufm @keyonghan did you get a chance to calculate how many bots are needed for try and how many for prod?

**Comment by keyonghan** [comment]
Did a quick calculation: from 01/07/2021 to 01/15/2021, we have around
15000 total builds, ~2000 builds/day, 45min 90th% queue time, 60 bots for prod;
28000 total builds, ~3000 builds/day, 15min 90th% queue time, 100 bots for try.

I would say double the prod capacity to 120, and add 20-40 for try if it allows.

**Comment by godofredoc** [comment]
We were not able to add the 100 bots and we only added 30 to the linux prod pool.

**Comment by godofredoc** [comment]
I'll close this bug for now and will open a new one when capacity becomes available.
