### ISSUE TITLE
Allow for Listeners when routes change in Material App.

### ISSUE THREAD

**Issue by marklester** [flutter/flutter#7381]
As a developer I would like to add listeners the Navigator to a MaterialApp so that I can save current state of the app to disk. This would allow for a user to pick up where they last left off.

**Comment by Hixie** [comment]
Yeah we definitely need a way to serialise the state to disk. On Android at least I believe there's system-level support for this which we should leverage.

**Comment by sethladd** [comment]
Does this feature proposal require MaterialApp, or can it work with any Navigator (which I assume doesn't require MaterialApp) ?

**Comment by marklester** [comment]
Any of these outcomes would be helpful

**Comment by sethladd** [comment]
Tentatively adding a API stability label. If this is a New Feature that doesn't require API stability, we can move to M3.

**Comment by Hixie** [comment]
This is a new feature.

**Comment by Hixie** [comment]
The NavigatorObserver now lets you listen to all the ways the Navigator can change route, does that satisfy your needs, @marklester ?

**Comment by marklester** [comment]
Sure, if I have any issues I will follow up

**Comment by Hixie** [comment]
Cool, I'll close this one then. Please don't hesitate to file new bugs!
