### ISSUE TITLE
Interrupted RPCs cause bad state error when running with dds enabled

### ISSUE THREAD

**Issue by ravtechbr** [flutter/flutter#73815]
I'm having problems running my application for linux.
There is the generated log.

## command

flutter run --verbose

## exception

RPCError: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".

```
```

## flutter doctor

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.26.0-1.0.pre at /home/luiz/snap/flutter/common/flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/luiz/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @ravtechbr 
This crash usually generate a .log file, can you provide it so we can see the stack?
Thank you

**Comment by ravtechbr** [comment]
Hi @pedromassangocode, 
It does not have a .log file in the user's folder. The only .log generated is in the project folder. The same as I informed just above that indicates the exception: RPCError: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".

**Comment by RoyWaqasAzeem** [comment]
I am facing the same issue (Error connecting to the service protocol flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews)

Some can guide me what to do?

**Comment by pedromassangocode** [comment]
Hi @RoyWaqasAzeem 
Does this crash generated a .log file under your project is root directory? If so, can you provide it?

**Comment by jmagman** [comment]
https://github.com/dart-lang/sdk/commit/fc892d7fca37932c373f34aad1e82c5e8f8cb11f is in https://github.com/flutter/engine/pull/22889 is in #71771 which is available in 1.25.0-8.0.pre
.  So it looks like that didn't fix it.  @bkonyi can you take a look?

**Comment by jonahwilliams** [comment]
According to crash logging this is definitely still happening.

**Comment by Hixie** [comment]
update from @bkonyi:
> Mostly resolved, but we're still in the process of doing some refactoring to better catch these exceptions. Zach is working on that, but these exceptions should only show up when a device connection is unexpectedly lost so shouldn't affect normal workflows.
> However, users shouldn't be seeing that particular error anymore, but potentially another RPCError with a "Service Disappeared" message.

**Comment by zanderso** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/75297
