### ISSUE TITLE
FATAL EXCEPTION: Didn't find class "com...............MainActivity" 

### ISSUE THREAD

**Issue by mustafaerdogmus** [flutter/flutter#73813]
I am getting an error "Unable to instantiate activity " when i attempt to run the program. I am using Android Studio

> Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, Dart, io.flutter

the application crashes and show the error as below:

> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(26518): FATAL EXCEPTION: main
E/AndroidRuntime(26518): Process: com.inspireui.fnews, PID: 26518
E/AndroidRuntime(26518): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.inspireui.fnews/com.inspireui.fnews.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.inspireui.fnews.MainActivity" on path: DexPathList[[zip file "/data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/base.apk"],nativeLibraryDirectories=[/data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/lib/x86, /data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(26518): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
E/AndroidRuntime(26518): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime(26518): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(26518): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(26518): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(26518): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(26518): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26518): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(26518): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(26518): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26518): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(26518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(26518): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.inspireui.fnews.MainActivity" on path: DexPathList[[zip file "/data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/base.apk"],nativeLibraryDirectories=[/data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/lib/x86, /data/app/com.inspireui.fnews-tlWGEtRBZ3jRjUz-S7Q9xA==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(26518): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(26518): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(26518): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(26518): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
E/AndroidRuntime(26518): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(26518): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
E/AndroidRuntime(26518): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
E/AndroidRuntime(26518): 	... 11 more
Application finished.

main/AndroidManifest.xml 

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.inspireui.fnews">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="FluxNews"
            android:icon="@mipmap/launcher_icon">
        <activity
            android:label="FluxNews"
            android:name=".MainActivity">

            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            
            
            <meta-data android:name="com.google.android.geo.API_KEY"
                android:value="your-google-api-key-here"/>
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />

  
             <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/LaunchTheme"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>fl
                <data android:scheme="https" android:host="www.news.inspireui.com" android:pathPrefix="/"/>

            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="fluxnews" android:host="inspireui" android:pathPrefix="/"/>
            </intent-filter>

        </activity>
        <meta-data
            `android:name="com.facebook.sdk.ApplicationId"`
            android:value="@string/fb_app_id" />
        <meta-data
            android:name="com.facebook.accountkit.ApplicationName"
            android:value="@string/app_name" />
        <meta-data
            android:name="com.facebook.accountkit.ClientToken"
            android:value="@string/ak_client_token" />
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/api_key"/>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/admob_api"/>
    </application>
    <meta-data
    android:name="flutterEmbedding"
    android:value="2" />
</manifest>

pubspec.yaml

> name: fstore
> description: Mobile commerce app by Flutter
> 
> https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
> version: 1.4.1+2
> 
> environment:
>   sdk: ">=2.2.2 <3.0.0"
> 
> dependencies:
>   logs:
>     git: https://github.com/pq/logs
>   flutter:
>     sdk: flutter
>   http: 0.12.1
>   html_unescape: 1.0.1+3
>   provider: 4.1.0
>   after_layout: 1.0.7+2
>   font_awesome_flutter: 8.8.1
>   flutter_facebook_login: 3.0.0
>   #vector_math: 2.0.7
>   configurable_expansion_tile: 1.0.0
>   timeago: 2.0.26
>   share: 0.6.4+1
>   validate: 1.7.0
>   shared_preferences: 0.5.7+1
>   firebase_messaging: 6.0.13
>   firebase_analytics: 5.0.11
>   transparent_image: 1.0.0
>   pull_to_refresh: 1.5.8
>   localstorage: 3.0.2+5
>   notification_permissions: 0.4.4
>   flare_splash_screen: 3.0.1
>   rate_my_app: 0.6.0+3
>   page_indicator: ^0.3.0
>   intro_slider: 2.2.9
>   url_launcher: 5.4.5
>   extended_image: 0.7.3-dev
>   firebase_core: 0.4.4 # keep these version as there is new issue
>   firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
>   firestore_ui: 1.9.1
>   flutter_webview_plugin: 0.3.11
>   connectivity: 2.0.2
>   cached_network_image: 2.2.0+1
>   image_picker: 0.6.6+1
>   fab_circular_menu: 1.0.0
>   uuid: 2.0.4
>   uni_links: 0.2.0
>   flutter_staggered_grid_view: 0.3.0
>   auto_size_text: 2.1.0
>   flutter_swiper: 1.1.6
>   flutter_widgets: 0.1.12
>   flutter_spinkit: 4.1.2+1
>   percent_indicator: 2.1.3
>   animated_text_kit: 2.0.1
>   wave: 0.0.8
>   http_auth: 0.2.9
>   firebase_admob: 0.9.3+2
>   facebook_audience_network: 0.5.0
>   launch_review: 2.0.0
>   custom_splash: 0.0.2
>   google_fonts: 1.0.0
>   google_sign_in: 4.4.4
>   apple_sign_in: 0.1.0
>   international_phone_input: 1.0.4
>   pin_code_fields: 3.0.0
>   onesignal_flutter: 2.4.1
>   flutter_widget_from_html: 0.3.3+3
>   flutter_statusbarcolor: 0.2.3
>   event_bus: 1.1.1
>   liquid_swipe: ^1.4.3
> 
>   flutter_localizations:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_launcher_icons: 0.7.5
>   flutter_test:
>     sdk: flutter
> 
> flutter_icons:
>   android: "launcher_icon"
>   ios: true
>   image_path: "assets/images/app_icon.png"
> 
> 
> 
> flutter:
> 
>   uses-material-design: true
>   assets:
>     - lib/common/
>     - assets/icons/categories/
>     - assets/icons/tabs/
>     - assets/icons/profile/
>     - assets/icons/payment/
>     - assets/images/
>     - assets/images/country/
> 
>   fonts:
>     - family: Raleway
>       fonts:
>         - asset: assets/fonts/Raleway-Regular.ttf
>         - asset: assets/fonts/Raleway-Medium.ttf
>         - asset: assets/fonts/Raleway-Bold.ttf
>         - asset: assets/fonts/Raleway-Light.ttf
>         - asset: assets/fonts/Raleway-Thin.ttf
>     - family: Roboto
>       fonts:
>         - asset: assets/fonts/Roboto-Regular.ttf
>         - asset: assets/fonts/Roboto-Medium.ttf
>         - asset: assets/fonts/Roboto-Bold.ttf
>         - asset: assets/fonts/Roboto-Light.ttf
>         - asset: assets/fonts/Roboto-Thin.ttf
> 
> flutter_intl:
>   enabled: true

build.gradle

```
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
repositories {
    maven { url 'https://maven.google.com' }
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.inspireui.fnews"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        resConfigs "en"
        manifestPlaceholders = [
                onesignal_app_id: 'a76dd222-35a3-4391-98db-9fadfb653304',
                // Project number pulled from dashboard, local value is ignored.
                onesignal_google_project_number: 'REMOTE'
        ]
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-storage:18.1.0'
    implementation 'com.google.firebase:firebase-ads:17.2.0'
//    implementation 'com.onesignal:OneSignal:3.12.7'
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
}
apply plugin: 'com.google.gms.google-services'
googleServices { disableVersionCheck = true }
```

MainActivity.kt

```
' package com.app.inspireui.fnews

import io.flutter.embedding.android.FlutterActivity


class MainActivity: FlutterActivity() {

}'
```

**Comment by darshankawar** [comment]
@mustafaerdogmus 
Check out [this](https://github.com/flutter/flutter/issues/60831) similar issue and underlying comment / solutions to see if it helps.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mustafaerdogmus** [comment]
I solved the problem. I've actually tried a lot of things. I've dealt with a lot of errors also after solving this error. 


I changed the MainActivity class file as follows

```
package com.app.inspireui.fluxnews
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import com.facebook.FacebookSdk;

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);


    }

}
```
