### ISSUE TITLE
Linux shell ignoring non-smooth scroll events

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#73823]
In order to fix https://github.com/flutter/flutter/issues/71385 the Linux shell is ignoring non-smooth scroll events.

The reason is on X11 scroll events are being directly sent to the FlView X window. This is causing them to bypass the normal scroll handling and means this widget received both smooth and non-smooth scroll events. This issue doesn't occur in Wayland.

This could cause issues on older versions of the X server that don't send smooth scroll events. To fix this we need to work out why the events are being sent directly to the `FlView` X window and not the main X window where they are processed by GTK appropriately.

**Comment by robert-ancell** [comment]
I did some investigation into this and could stop the events from going to `FlView` by not giving it focus, but this causes the keyboard events to stop working. I think using a `GtkEventBox` around the `FlView` might work around this issue?

**Comment by Techno-Disaster** [comment]
Any updates on this? I could **not** get any scrolling to work on x11 but everything works fine on wayland. On Fedora KDE right now.

**Comment by robert-ancell** [comment]
Since f94cf140c5 events are now handled in a GtkEventBox and the duplicate event issue is no longer occuring here.
