### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

### ISSUE THREAD

**Issue by UjjawalPanchal** [flutter/flutter#73833]
E/flutter ( 3417): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter ( 3417): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160:7)
E/flutter ( 3417): <asynchronous suspension>
E/flutter ( 3417): #1      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:19)
E/flutter ( 3417): <asynchronous suspension>
E/flutter ( 3417): #2      _MyAppState.openCamera (package:flutter_app/screen/my_app.dart:759:24)
E/flutter ( 3417): <asynchronous suspension>
E/flutter ( 3417): 

I am getting this error can any one help me with this?

**Comment by pedromassangocode** [comment]
Hi @UjjawalPanchal 
Please see if [this](https://github.com/flutter/flutter/issues/70314#issuecomment-726919984) solve this issue for you, if not, can you please provide your `flutter doctor -v`,  and your `pubspec.yaml`. 

Thank you

**Comment by UjjawalPanchal** [comment]
Okay, thanks.

> Hi @UjjawalPanchal
> Please see if [this](https://github.com/flutter/flutter/issues/70314#issuecomment-726919984) solve this issue for you, if not, can you please provide your `flutter doctor -v`, and your `pubspec.yaml`.
> 
> Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
