### ISSUE TITLE
A problem occurred configuring project ':url_launcher'.

### ISSUE THREAD

**Issue by yetunnaing18121996** [flutter/flutter#73831]
FAILURE: Build failed with an exception.
I am getting this error while I build android apk using url_laucher in my app.
can you please tell me how can I solve this problem?

* What went wrong:
A problem occurred configuring project ':url_launcher'.
> Could not load compiled classes for build file 'D:\YTNData\Flutter\flutter_windows_1.22.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\android\build.gradle' from cache. Expected class file C:\Users\Ye Tun Naing\.gradle\caches\5.6.2\scripts-remapped\build_4wed21haxtpow5blkbcj7c2g7\2w6ata9gtgynubxxmn48z3bxi\cp_proj40e7ec637808a9c747559d26950b1d9b\classes\build_4wed21haxtpow5blkbcj7c2g7.class does not exist.
> Could not get unknown property 'android' for project ':url_launcher' of type org.gradle.api.Project.

**Comment by pedromassangocode** [comment]
Hi @yetunnaing18121996 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
