### ISSUE TITLE
flutter ios app stuck at white screen but android is fine

### ISSUE THREAD

**Issue by zatkontact** [flutter/flutter#73836]
Hi,
I am currently building an app using flutter. The android is working find and all features are as expected. Whenever I am running the ios app, whether in simulator or a real device, it keeps stuck at the white screen. I have tried running from xcode, visual studio and the result is same.  I have searched online and tried many things. But it doesn't seem to work. The output of flutter doctor -v is below. If anyone could offer me some help, I'd be really grateful. Thanks

```[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-AU)
    • Flutter version 1.22.5 at /Users/zat_km/Desktop/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zat_km/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 4BC984F9-7795-4DDE-96AF-1211E7255F08 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@zatkontact 
Can you provide `flutter run --verbose` logs in properly formatted text so that we can take a look what's going on ?
Also, provide `pubspec.yaml` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
