### ISSUE TITLE
html.document.removeEventListener not working 

### ISSUE THREAD

**Issue by chentianxin** [flutter/flutter#73842]
## Steps to Reproduce

![C6183AD5-5EED-4E48-B626-8C093A04F712](https://user-images.githubusercontent.com/49486355/104439371-fdd13380-55cb-11eb-9ae9-e5a777fa6dab.png)

**Expected results:** 
```js
document.removeEventListener works normally
```

**Actual results:** 
![9391CF0A-4A65-4A62-8D4C-7571741D7557](https://user-images.githubusercontent.com/49486355/104439604-3ec94800-55cc-11eb-855a-7d7fd1ef5a2d.png)
![9EB69E03-984D-4591-859B-E52B96D626E9](https://user-images.githubusercontent.com/49486355/104439760-72a46d80-55cc-11eb-91e4-db572cbaf08f.png)

The event cannot be deleted normally, causing the event to be repeatedly added and run

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @chentianxin 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) instead of screenshot
Thank you

**Comment by jakemac53** [comment]
I wonder if the tearoffs are not canonicalized? Can you try doing a single tearoff, assigning that to a variable, and passing that?

```
final onWebVisibilityChange = _webVisibilityChange;
// And then pass `onWebVisibilityChange` to `addEventListener` and `removeEventListener`
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
