### ISSUE TITLE
Misleading Error Message "CocoaPods did not set the base configuration of your project."

### ISSUE THREAD

**Issue by gatzsche** [flutter/flutter#73845]
### Create a Plugin Project

~~~bash
cd ~/tmp
flutter create --org com.example --template=plugin --platforms=ios base_configuration_error
cd base_configuration_error
cd example
flutter pub get
~~~
### Setup Xcode to build the project

- `~/tmp/base_configuration_error/example/ios/Runner.xcworkspace`with Xcode
- Setup development team to be able to run the application on an iPhone.

### Build the Project

~~~bash
flutter build ios
~~~

### Reproduce Misleading Error Message

~~~
cd ios
pod install
~~~

- The following error message appears:

~~~bash
[!] CocoaPods did not set the base configuration of your project because your
project already has a custom config set. For CocoaPods integration to
work at all, please either set the base configurations of the target `Runner`
to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include
the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your
build configuration (`Flutter/Release.xcconfig`).
~~~

## The Problem

- First, the required action is not necessary. `Flutter/Release.xcconfig` already
  includes `Pods-Runner.profile.xcconfig`.
- Second, users are motivated to open the project in Xcode and make the
  following setting shown in the following screenshot.
  <img width="1055" alt="INL008260" src="https://user-images.githubusercontent.com/1993248/104445739-c47fd000-5599-11eb-9746-6a1a9e267814.png">

- After doing so, pod install will work, but then the project is broken and
  cannot be compiled via Xcode anymore. The following error will happen:

  ~~~bash
  `/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh failed with a nonzero exit code` will happen.
  ~~~

- This error is already a [GitHub known issue](https://github.com/flutter/flutter/issues/17234).

## Solution / Required Action:

- Developers should not change the Xcode Configurations like before (See also [Issue 66222](https://github.com/flutter/flutter/issues/66222))
- Replace the error message `In order for CocoaPods integration to
  work at all, please either set the base configurations ...` by a statement,
  that tells like this:

  > In Flutter `pod install` should not called manually. To run `pod install`
  > execute the following commands `flutter clean`, `flutter pub get` and
  > `flutter build ios`.

**Comment by TahaTesser** [comment]
Hi @gatzsche 
Thanks for filing the issue, I like the new error message proposal better, I can reproduce the issue using your steps

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by funder7** [comment]
Thanks for your info @gatzsche, I was going to follow that instrucitions in XCode

**Comment by jmagman** [comment]
As you point out, the error message is suggesting an action that isn't necessary.  The `flutter` command suppresses that message from `pod`.  You ran `pod` directly, which isn't a recommended workflow.  We don't have any control of error messages coming from CocoaPods, and the `flutter` command line tool already suppresses the confusing message.
