### ISSUE TITLE
[tool][windows 7] The term 'Unblock-File' is not recognized as the name of a cmdlet. Flutter requires PowerShell 5.0 or newer

### ISSUE THREAD

**Issue by mytja** [flutter/flutter#73840]
## Steps to Reproduce

1. Download latest version of Flutter (from stable or dev branch)
2. Install Flutter (add it to PATH)
3. Run any dart or flutter command
4. CMD closes instantly

## Logs

<details>
<summary>Logs</summary>

It closes so fast, i can't see any logs! I also tried ```os.system``` in Python, but it returns only status code 1

```
```

```
```

</details>

# Details
I'm using Windows 7 SP1 64-bit machine

Flutter 1.22.3 works fine, 1.22.5 is causing problems

**Comment by TahaTesser** [comment]
Hi @mytja 
Can you please provide your `flutter doctor -v` and please capture using `flutter run --verbose > run .log`, this will create this log file and capture logs even if it closes fast. 
Thank you

**Comment by mytja** [comment]
```
Checking Dart SDK version...
The term 'Unblock-File' is not recognized as the name of a cmdlet, function, sc
ript file, or operable program. Check the spelling of the name, or if a path wa
s included, verify that the path is correct and try again.
At line:1 char:13
+ Unblock-File <<<<  -Path 'C:\Users\User\Downloads\flutter/bin/internal/update
_dart_sdk.ps1'; & 'C:\Users\DOMA\Downloads\flutter/bin/internal/update_dart_sdk
.ps1'; exit $LASTEXITCODE;
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Current version is 2.
```

**Comment by TahaTesser** [comment]
Hi @mytja 
Can you please try with Command Prompt instead of PowerShell, your PowerShell is outdated. 

Related to https://github.com/flutter/flutter/issues/22802
Thank you

**Comment by mytja** [comment]
This was a CMD, i was using...

**Comment by TahaTesser** [comment]
Hi @mytja 
That is strange it's showing PowerShell requirement.

> Flutter 1.22.3 works fine, 1.22.5 is causing problems

Can you please delete the existing setup and clone a fresh copy of the latest stable channel in the same directory?
`git clone -b stable https://github.com/flutter/flutter.git`
Thank you

**Comment by mytja** [comment]
Still the same...

**Comment by jonahwilliams** [comment]
Previous versions of flutter did not correctly check the powershell version and would fail to update the dart sdk. This has been fixed, but it requires you to update to a newer version, see:

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1
