### ISSUE TITLE
infowindow

### ISSUE THREAD

**Issue by sherdiltahir** [flutter/flutter#73853]
please add infowindow without tap on marker

**Comment by TahaTesser** [comment]
Hi @sherdiltahir 
You can show infoWindow without tap programmatically using https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMapController/showMarkerInfoWindow.html
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
