### ISSUE TITLE
Flutter build caching mechanism issue

### ISSUE THREAD

**Issue by 0ttik** [flutter/flutter#73858]
## Steps to Reproduce

(I'm not sure it's reproducable, didn't test since it's strange)

1. Started dev from standard `flutter create`
2. At some point changed version in pubspec to 0.0.1 and ended up at 0.0.2+8. During that period did a lot of different builds, did `flutter clean` and did all other basic development w/0 chaning dev environment. 

## Description

After "steps to reproduce" I noticed that internal app cache (which is for example my local db file where I save user data and firebase auth persisted state - with logged user X) is restored every time I do the following: 

1. Delete app from physical device which is Android phone.
2. Run `flutter clean`, `flutter pub cache repair`, restart PC
3. Load same project from git to different directory at same PC
4. Do all commands from 2. in newly loaded dir with same commit checked out as in 2.
5. Finally run `flutter run`...
6. And get same application cache result (so I get user X logged in state in Firebase Auth and same DB state as it was before deleting).

So basically I was getting some full snapshot of my application everytime I was trying to install it from my PC. When I loaded same commit at another PC it did not load any old cache and worked as expected. I could not get rid of that snapshot by running standard cache cleaning commands.

What helped is changing build version from 0.0.2+8 to 0.0.2+9. That's when rebuild did happen with just `flutter run`. Is this an expected behaviour and how can I get rid of this cached version of my app without changing build number in pubspec?

## Flutter doctor

Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.746], locale ru-RU)
• Flutter version 1.22.5 at C:\Flutter
• Framework revision 7891006 (5 weeks ago), 2020-12-10 11:54:40 -0800
• Engine revision ae90085a84
• Dart version 2.10.4

**Comment by TahaTesser** [comment]
Hi @0ttik 
Seems to strange, can you same behavior even if the app is installed but the same build? 
To better address, the issue, can you please more specific with your steps reproducible. It's hard to pinpoint what code and what changes are in your code? Does it reproduce again? 
Please more specific and provide reproducible steps and code sample
Thank you

**Comment by 0ttik** [comment]
> Hi @0ttik
> Seems to strange, can you same behavior even if the app is installed but the same build?
> To better address, the issue, can you please more specific with your steps reproducible. It's hard to pinpoint what code and what changes are in your code? Does it reproduce again?
> Please more specific and provide reproducible steps and code sample
> Thank you

If the app is installed it's files are not changed and everything's fine. This issue only occurs if I remove application from a phone and install it again with `flutter run` or manually with `flutter build apk` followed by installation on a phone. 

I'll try to craft reproduction repo soon.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
