### ISSUE TITLE
Many time outs on Mac Host Engine

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#73869]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine

P0 because this is frequently causing the engine tree to be closed.

**Comment by zanderso** [comment]
Related https://github.com/flutter/flutter/issues/73871. Leaving up to you which to keep open.

**Comment by yusufm** [comment]
From dev team: "need to increase the timeouts by ~6 mins (3 for build and 3 for test)" due to recent addition of host_debug_unopt_metal which increases the build time.

**Comment by yusufm** [comment]
Increased timeout to 75min:

flutter/infra@6f671a2
