### ISSUE TITLE
Images with transparency have graphical artifacts on fuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7386]

**Comment by apwilson** [comment]
![img_20170106_153120](https://cloud.githubusercontent.com/assets/142874/21736440/90bb7ca0-d425-11e6-8b0f-efc4a7d7c8d4.jpg)

**Comment by apwilson** [comment]
Original asset: https://github.com/fuchsia-mirror/sysui/blob/master/armadillo/lib/res/logo_googleg_24dpx4.png

**Comment by apwilson** [comment]
Image is created via: 
```
new Image.asset(<url>, fit: ImageFit.cover)
```

**Comment by eseidelGoogle** [comment]
Presumably this is a bad interaction with Skia on Fuschia?  FYI @chinmaygarde

**Comment by eseidelGoogle** [comment]
This may also have been fixed by recent skia rolls.  This is Fuschia only.  @apwilson can you re-confirm this is still an issue?

**Comment by abarth** [comment]
@eseidelGoogle I've added the `waiting for customer response` label because this bug is now blocked on a response from apwilson.

**Comment by apwilson** [comment]
This is fixed.
