### ISSUE TITLE
multi_widget_construction_perf__timeline_summary timed out

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73873]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858199145548236432/+/steps/run_multi_widget_construction_perf__timeline_summary/0/stdout
```
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +23 ms] VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:38693/HWRG-yMgbZA=/
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [ +101 ms] VMServiceFlutterDriver: Isolate found with number: 433950321518587
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +79 ms] VMServiceFlutterDriver: Isolate is paused at start.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [   +1 ms] VMServiceFlutterDriver: Attempting to resume isolate
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [ +401 ms] VMServiceFlutterDriver: Connected to Flutter application.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [+6629 ms] VMServiceFlutterDriver: waitFor message is taking a long time to complete...
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [+38728 ms] 00:45 [32m+0[0m[31m -1[0m: multi_widget_construction_perf [1m[31m[E][0m[0m
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +1 ms]   TimeoutException after 0:00:45.000000: Test timed out after 45 seconds.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +14 ms]   package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1178:47                      _rootRun
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1090:19                      _CustomZone.run
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1186:13                      _rootRun
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1090:19                      _CustomZone.run
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +22 ms] 00:46 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [   +2 ms] Unhandled exception:
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [        ] Dummy exception to set exit code.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +69 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K shell am force-stop com.example.macrobenchmarks
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [+1032 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K uninstall com.example.macrobenchmarks
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [ +409 ms] Success
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +5 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --list
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +10 ms] Exit code 0 from: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --list
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ] ZY22465W9K tcp:46197 tcp:41863
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +4 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --remove tcp:46197
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +11 ms] "flutter drive" took 186,346ms.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +10 ms] 
```

**Comment by jmagman** [comment]
Looks like maybe not a flake, it happened on the next build, too:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858194219923639488/+/steps/run_multi_widget_construction_perf__timeline_summary/0/stdout

Started on https://github.com/flutter/flutter/commit/7cb0c16e5dbda9edcfb8ad8c35f7f33b45c9d719, but `macrobenchmarks` doesn't use the `video_player` plugin, so unrelated?

**Comment by jmagman** [comment]
Seen on flutter-devicelab-linux-1 and flutter-devicelab-linux-3 so probably not a device issue.  I don't see a recent recipe or infra commit that may have caused it.  Rerunning.

**Comment by jmagman** [comment]
And this test passed for me locally on top of tree on a Pixel.
@yusufm Can we get a screenshot of what this device is doing while it's stuck?  Was there a recent change on these devices?

**Comment by zanderso** [comment]
Is it actually re-running? https://ci.chromium.org/p/flutter/builders/prod/Linux%20multi_widget_construction_perf__timeline_summary Job 305 looks like it has been queued for 40-some minutes.

**Comment by jmagman** [comment]
305 passed on flutter-devicelab-linux-4 https://ci.chromium.org/p/flutter/builders/prod/Linux%20multi_widget_construction_perf__timeline_summary/305.

**Comment by jmagman** [comment]
Since this seems to be a flake, the most recent suspect is https://github.com/flutter/flutter/commit/1cb0a24a466fb1d1cf8ad95b15c9857ab9817293 reverted to see if that helps. \cc @kenzieschmoll

**Comment by jmagman** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20multi_widget_construction_perf__timeline_summary/309/overview flaked again on revert of https://github.com/flutter/flutter/commit/1cb0a24a466fb1d1cf8ad95b15c9857ab9817293, restoring at https://github.com/flutter/flutter/pull/73903.

linux_animated_placeholder_perf also seems to be flaking.  I'm going to mark them as flaky while this is being investigated.  Starting with `engine`, maybe @liyuqian can take a look?

**Comment by jmagman** [comment]
Tests marked flaky https://github.com/flutter/flutter/pull/73904

**Comment by liyuqian** [comment]
Sure, I'll take a look soon :)

**Comment by liyuqian** [comment]
It seems that `multi_widget_construction_perf__e2e_summary` always passes while `multi_widget_construction_perf__timeline_summary` sometimes timed out. This suggests that the timeout might be caused by the vm service communication that's removed by the e2e (currently integration_test) package. I think we shall remove the `multi_widget_construction_perf__timeline_summary` task as we did earlier with similar tests where the non-e2e version is significantly more flaky. PR uploaded at https://github.com/flutter/flutter/pull/73986

Meanwhile, I found that https://flutter-dashboard.appspot.com/#/build mistakenly classifies all "linux/android" tasks as "chromebot" instead of devicelab android bots. Is that a known issue? CC @CaseyHillers

**Comment by CaseyHillers** [comment]
> Meanwhile, I found that https://flutter-dashboard.appspot.com/#/build mistakenly classifies all "linux/android" tasks as "chromebot" instead of devicelab android bots. Is that a known issue?

This is intentional as the Devicelab tasks are being migrated to LUCI. When the migration to LUCI is complete, we can revisit how to categorize tasks (tracked in https://github.com/flutter/flutter/projects/151)

**Comment by jmagman** [comment]
Does flaky `linux_animated_placeholder_perf` also need to be removed in favor of `linux_backdrop_filter_perf__e2e_summary` @liyuqian?  I was kind of tracking both with this issue but I can open a new one if you prefer!

**Comment by liyuqian** [comment]
Yes, uploaded https://github.com/flutter/flutter/pull/74062 for removing `linux_animated_placeholder_perf`.
