### ISSUE TITLE
[share] When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared

### ISSUE THREAD

**Issue by mwolffalonso** [flutter/flutter#73874]
When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared.
I expected that the behavior would be that text is just sent once.
I am using share plugin version "share: ^0.6.5+4"
I have just tested in Android Emulator and Real device with Android 8 and 9.
Thanks

**Comment by darshankawar** [comment]
@mwolffalonso 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
I tried the official `share` plugin [example](https://pub.dev/packages/share/example) on latest dev on iOS in which the text was shared only once, although even after selecting the images, they weren't part of the share for some reason.

Can you also try the official example and see if you still get same behavior ?

**Comment by mwolffalonso** [comment]
@darshankawar 

Down here is the flutter doctor -v output. 
I have to use a previous release of Flutter as i am having issues with another plugin which does not work correctly at the last versions. 
I will provide minimal code later today, thanks! 



[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.17763.1637], locale es-UY) 
• Flutter version 1.21.0-9.2.pre at C:\Users\martinwo\flutter 
• Framework revision 81a45ec2e5 (5 months ago), 2020-08-27 14:14:33 -0700 
• Engine revision 20a9531835 
• Dart version 2.10.0 (build 2.10.0-7.3.beta) 


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
• Android SDK at C:\Users\martinwo\AppData\Local\Android\sdk 
• Platform android-30, build-tools 29.0.2 
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java 
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01) 
• All Android licenses accepted. 

[√] Android Studio (version 4.0) 
• Android Studio at C:\Program Files\Android\Android Studio 
• Flutter plugin version 50.0.1 
• Dart plugin version 193.7547 
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01) 

[√] Connected device (1 available) 
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator) 

----- Mensaje original -----

De: "darshankawar" <notifications@github.com> 
Para: "flutter/flutter" <flutter@noreply.github.com> 
CC: "mwolffalonso" <martin.wolff@vera.com.uy>, "Mention" <mention@noreply.github.com> 
Enviados: Jueves, 14 de Enero 2021 4:01:31 
Asunto: Re: [flutter/flutter] [share] When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared (#73874) 






@mwolffalonso 
Can you provide flutter doctor -v and a minimal complete reproducible code sample that shows the issue ? 
I tried the official share plugin example on latest dev on iOS in which the text was shared only once, although even after selecting the images, they weren't part of the share for some reason. 

Can you also try the official example and see if you still get same behavior ?

**Comment by darshankawar** [comment]
@mwolffalonso 
Sure. I'd also suggest you to take a look at the official share plugin [example](https://pub.dev/packages/share/example) and check there if you get similar issue or not.

**Comment by mwolffalonso** [comment]
Hello darshankawar,

I have just tested with the share plugin example and i reproduce the same behavior. Text gets embedded into all photos shared into whatsapp in the same share event.

Thanks

**Comment by darshankawar** [comment]
@mwolffalonso 
Can you provide gif or screenshot of the issue ? 
I am unable to replicate it. Also can you try the same on latest master to check if you get same behavior ?
Thanks.

**Comment by mwolffalonso** [comment]
Hello darshankawar,

I am attaching the screenshots you requested. I will test with latest master in a while.

Thanks!

![WhatsApp Image 2021-01-15 at 10 13 50 (2)](https://user-images.githubusercontent.com/19885531/104732070-6bd84080-571b-11eb-9e4b-aa17a9aac5be.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 50 (1)](https://user-images.githubusercontent.com/19885531/104732075-6d096d80-571b-11eb-8c31-e9d001f9dff2.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 50](https://user-images.githubusercontent.com/19885531/104732076-6d096d80-571b-11eb-953d-396fe5b7c5b4.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 51](https://user-images.githubusercontent.com/19885531/104732077-6e3a9a80-571b-11eb-91d1-7968575d8c59.jpeg)

**Comment by darshankawar** [comment]
@mwolffalonso 
Is it only happening for WhatsApp ? I tried on default messaging on Android  device which sent the text only once.
Can you also check other share modes (not external) but default to see if issue persists ?

**Comment by mwolffalonso** [comment]
@darshankawar 
Works fine with:
Twitter
Email

Works "wrong" (not expected) with:
WhatsApp (this issue)
Telegram --> Does not share the text, only images when multiple images are shared. Ok when just one is shared

Instagram, only images, but that makes sense for that app.

**Comment by darshankawar** [comment]
Issue replicable on latest stable while trying to use WhatsApp share option.

<details>
<summary>stable flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android
      11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by mwolffalonso** [comment]
Also replicated in latest beta release

Thanks

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).

**Comment by linxkaa** [comment]
hey, any fix on this issues ? im still getting the error using share either share_plus package. any help will highly appreciated, thankyou.
