### ISSUE TITLE
Flutter building error Program type already present: com.my.app.MainActivity

### ISSUE THREAD

**Issue by MATTYGILO** [flutter/flutter#73888]
## Steps to Reproduce

I have changed my app id to com.my.app

Gradle.properties:
`
      org.gradle.jvmargs=-Xmx512m
      android.enableJetifier=true
      android.useAndroidX=true
      android.enableR8=true
      sdk.dir = /Users/myUserName/Library/Android/sdk`
      
     
build.gradle:

```
buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

app/build.gradle:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 29

    aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.my.app”
        minSdkVersion 20
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    implementation 'androidx.multidex:multidex:2.0.1'
}

```

**Expected results:** 

To Build and run

**Actual results:** 

<details>
  <summary>Logs</summary>
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.7.2/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-6.3.0/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.4.3/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/MethodCallHandlerImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.3.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/myUserName/.pub-cache/hosted/pub.dartlang.org/tflite-1.1.1/android/src/main/java/sq/flutter/tflite/TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Program type already present: com.my.app.MainActivity

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: com.my.app.MainActivity

</details>

**Comment by darshankawar** [comment]
@MATTYGILO 
There seems to be some name conflict after you updated the app id. Can you try running `flutter clean` and then` flutter packages get` to see if it helps ?

Also, Check out [this](https://www.xspdf.com/resolution/50086364.html) link and see if it helps to resolve your issue.

**Comment by MATTYGILO** [comment]
The error was occurring in the folder:

src/java
src/kotlin

1. I deleted these folder
2. I created a new flutter app and copied these folders to my app
3. Fixed the errors that arose due to the replacement
4. It fixed the initial error

**Comment by darshankawar** [comment]
@MATTYGILO 
Sounds like your issue is resolved. Closing this based on your comment above.
