### ISSUE TITLE
DefaultTextStyle should inherit from its own BuildContext

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7388]
Today, you need to give it the build context to inherit from explicitly.  Instead, it should be able to default to its own build context.

**Comment by HansMuller** [comment]
I'm not sure what "you need to give it the build context to inherit from explicitly" refers to. The DefaultTextStyle and DefaultTextStyle.merge() constructors don't require a build context parameter.

**Comment by abarth** [comment]
Yeah, @Hixie fixed this bug recently
