### ISSUE TITLE
Support triggering a Flutter CI run with a custom engine

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#73893]
The usecase here is if a developer is working on a PR for the Engine, which passes all Engine CI, but breaks the roller because of an issue in Framework CI, it'd be nice to have a way of testing fixes in the same environment before merging again to Engine.

cc @CaseyHillers

**Comment by godofredoc** [comment]
I think this use case is already covered by Linux Web Framework Tests @yjbanov is my assumption correct?

**Comment by godofredoc** [comment]
No updates for over a year, closing as obsolete.
