### ISSUE TITLE
The binary product of flutter module libapp.so

### ISSUE THREAD

**Issue by yohyow** [flutter/flutter#73906]
The binary product of flutter module libapp.so
It is hoped that the official code will not be hard coded and can be changed, for example: libxxbusiness.so
thanks!

**Comment by darshankawar** [comment]
@yohyow 
Can you elaborate on this ? Is this a proposal ? If so, can you update the issue in `use case` and `proposal` [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
