### ISSUE TITLE
Remove the "mac-catalina/ios" devicelab capability, move remaining tests to "mac/ios" or other appropriate combo 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73907]
All agents with capability requirement "mac-catalina/ios" are down.
`smoke_catalina_hot_mode_dev_cycle_ios__benchmark` and `smoke_catalina_start_up_ios` haven't run for awhile (weeks?)

It looks like most of the LUCI bots are running on Catalina (10.15) which is exercising that host OS pretty well.

We should either remove the tests:

- [x] Swap the `smoke_catalina_hot_mode_dev_cycle_ios__benchmark` capability to `mac/ios` and ideally rename to `hot_mode_dev_cycle_ios__benchmark` if there's some way to do that without breaking benchmarking and release branches.
- [x] Swap `smoke_catalina_start_up` capability to `mac/android` and ideally rename to `flutter_gallery_<something>__start_up` without breaking benchmarks.
- [x] Remove `smoke_catalina_hot_mode_dev_cycle__benchmark` since the mac/android combo is covered by `hot_mode_dev_cycle__benchmark`.
- [x] Remove `smoke_catalina_start_up_ios` since it's already covered by `flutter_gallery_ios__start_up`.

Or bring the agent back up if these tests are valuable.

Introduced in https://github.com/flutter/flutter/pull/39300.

**Comment by jmagman** [comment]
@xster What do you think?

**Comment by jmagman** [comment]
@kf6gpe how sad would you be to lose `smoke_catalina_hot_mode_dev_cycle_ios__benchmark` and `smoke_catalina_start_up` benchmark data?  I'd like to run them on whatever OS the other devicelab agents are running, which would involve a rename.

**Comment by kf6gpe** [comment]
No worries. Seems reasonable to me.

Thanks!!
Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>

**Comment by keyonghan** [comment]
Seems we still have some catalina tests. Just in case, brought the agent back up online.

**Comment by jmagman** [comment]
Thanks @keyonghan 
Let's re-purpose this to track removing the last two tests as described in the description then.

**Comment by jmagman** [comment]
@keyonghan re: https://github.com/flutter/infra/pull/353 and https://github.com/flutter/flutter/pull/75798

**Comment by keyonghan** [comment]
These two tests have been updated as follows, and their benchmarks are populating
```
smoke_catalina_hot_mode_dev_cycle_ios__benchmark => hot_mode_dev_cycle_ios__benchmark
smoke_catalina_start_up => flutter_gallery_mac__start_up
```
https://flutter-flutter-perf.skia.org/e/?queries=test%3Dhot_mode_dev_cycle_ios__benchmark
https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_gallery_mac__start_up
