### ISSUE TITLE
Remove deprecations at EOL after 1.22 release

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#73910]
Tracker issue for removing the deprecations that have reached end of life after the 1.22 stable release.

Some resources and context:

- All deprecations that are due for removal: https://flutter.dev/go/deprecations-removed-after-1-22
- Deprecation policy: https://github.com/flutter/flutter/wiki/Tree-hygiene#deprecation
- Policy design doc: https://flutter.dev/go/deprecation-lifetime
- Article: https://medium.com/flutter/deprecation-lifetime-in-flutter-e4d76ee738ad
- Original Eval PR: https://github.com/flutter/flutter/pull/67789

This should also have a final migration guide under breaking changes on the website for additional guidance/seo. :)

**Comment by goderbauer** [comment]
We are waiting on a migration within google to land for https://github.com/flutter/flutter/pull/73750 and for a roll for https://github.com/flutter/flutter/pull/73751.

**Comment by Piinks** [comment]
We're just waiting on a migration in flutter/plugins now for the last one here: https://github.com/flutter/plugins/pull/3494

**Comment by Piinks** [comment]
#73751 is waiting for #75514

**Comment by Piinks** [comment]
Last one was reverted, reopening

**Comment by goderbauer** [comment]
Triage update: everything should be migrated, we are ready to submit the last PR after one final check.
