### ISSUE TITLE
Make third_party/freetype2 on flutter.googlesource.com publicly cloneable

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#73912]
`git clone https://flutter.googlesource.com/third_party/freetype2` currently requires authentication

It should be cloneable without credentials (similar to how the `infra` and `recipes` repositories are set up on flutter.googlesource.com)

**Comment by godofredoc** [comment]
The project configuration for that project was inheriting from all-projects and changed it to inherit from public projects.

Can you please give it another try?

**Comment by godofredoc** [comment]
This was fixed by inheriting from public projects.
