### ISSUE TITLE
[tool_crash] StateError: Bad state: Stream has already been listened to (Flutter web).

### ISSUE THREAD

**Issue by idipak** [flutter/flutter#73931]
## Command
```
flutter run --release --machine
```

## Steps to Reproduce
1. Run default app (works fine)
2. Add the following dependencies in pubspec.yaml -  firebase_core: ^0.5.3, cloud_firestore: ^0.14.4 , firebase: ^8.0.0
3. Chrome shows a blank screen. 

## Logs
StateError: Bad state: Stream has already been listened to.
```
#0      _StreamController._subscribe (dart:async/stream_controller.dart:709:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:1880:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:53:16)
#6      _BoundSinkStream.listen (dart:async/stream_transformers.dart:185:9)
#7      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:53:16)
#8      _BoundSinkStream.listen (dart:async/stream_transformers.dart:185:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
#13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
#14     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
#15     new Daemon (package:flutter_tools/src/commands/daemon.dart:84:42)
#16     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:463:29)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
<asynchronous suspension>
#18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
```
```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-IN)
    • Flutter version 1.25.0-8.2.pre at C:\src\flutter\flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: b0a22998593fc605c723dee8ff4d9315c32cfe2c
### Plugins
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
firebase_core-0.5.3
firebase_core_web-0.2.1+1
integration_test

**Comment by jmagman** [comment]
> Chrome shows a blank screen.

Are you getting a `Uncaught ReferenceError: firebase is not defined` console error?

https://github.com/flutter/flutter/blob/b0a22998593fc605c723dee8ff4d9315c32cfe2c/packages/flutter_tools/lib/src/commands/daemon.dart#L889-L896
https://github.com/flutter/flutter/blob/b0a22998593fc605c723dee8ff4d9315c32cfe2c/packages/flutter_tools/lib/src/commands/daemon.dart#L84-L91

**Comment by ditman** [comment]
> Add the following dependencies in pubspec.yaml - firebase_core: ^0.5.3, cloud_firestore: ^0.14.4 , firebase: ^8.0.0

That's an odd set of dependencies. @idipak, are you attempting to use these dependencies on your Flutter app, or is this the minimal set of dependencies that reproduces the issue?

**In case you're attempting to build an app with firebase in the web:**

In the latest [Flutterfire Migration guide](https://firebase.flutter.dev/docs/migration) they recommend the following package versions:

* `firebase_core: ^0.7.0`
* `cloud_firestore: ^0.16.0+1`

`package:firebase` is (or _was_) an implementation detail for the web version of the Flutterfire plugins, and you should not depend on it directly.

Read more info here: https://firebase.flutter.dev/docs/overview

**If the dependencies are prepared to cause a crash**, please let me know, so I can dig further into the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
