### ISSUE TITLE
We are getting FlutterMethodChannel* _methodChannel; error while creating build for iOS

### ISSUE THREAD

**Issue by aTeamSolace** [flutter/flutter#73948]
**Here is my error console**

```bash
/Users/ankitafirake/Documents/flutter/bin/flutter --no-color build ios --simulator
Building com.adamcompanies.technicianapp for simulator (ios)...
Running pod install... 9.6s
Running Xcode build...
Xcode build done. 12.4s
Failed to build iOS app
Error output from Xcode build:
↳
* BUILD FAILED *


Xcode's output:
↳
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:8:3: error: unknown type name 'FlutterMethodChannel'
FlutterMethodChannel* _methodChannel;
^
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:12:40: error: expected a type
- (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
^
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:29:17: warning: unused variable 'arguments' [-Wunused-variable]
NSDictionary* arguments = @{
^
1 warning and 3 errors generated.
note: Using new build system
note: Planning build
note: Constructing build description

Encountered error while building for simulator.
Process finished with exit code 1
```

**Comment by aTeamSolace** [comment]
Here is my flutter doctor console 

flutter doctor
Downloading android-arm-profile/darwin-x64 tools... 2.3s
Downloading android-arm-release/darwin-x64 tools... 1.9s
Downloading android-arm64-profile/darwin-x64 tools... 2.2s
Downloading android-arm64-release/darwin-x64 tools... 1.9s
Downloading android-x64-profile/darwin-x64 tools... 2.2s
Downloading android-x64-release/darwin-x64 tools... 1.8s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 4.1)
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
! No devices available

! Doctor found issues in 3 categories.

**Comment by aTeamSolace** [comment]
**Here is my pubspec file**

environment:
  sdk: ">=2.7.0 <3.0.0"

cupertino_icons: ^1.0.0
http: ^0.12.2
shared_preferences: ^0.5.12
fluttertoast: ^7.1.1
google_fonts: ^1.1.0
pin_code_fields: ^5.2.0
google_sign_in: ^4.5.4
flutter_facebook_login: ^3.0.0
device_preview: ^0.4.8
image_picker: ^0.6.7+11
firebase_messaging: ^7.0.3
provider: ^4.3.2+2
rect_getter: ^0.1.0
flutter_screenutil: ^3.2.0
dio: ^3.0.10
geolocator: ^6.1.13
google_maps_flutter: ^1.0.6
flutter_datetime_picker: ^1.4.0
intl: ^0.16.1
rflutter_alert: ^1.1.0
carousel_slider: ^2.3.1
badges: ^1.1.4
flutter_staggered_animations: ^0.1.2
location: ^3.1.0
flutter_html: ^1.0.2
flutter_inappwebview: ^4.0.0+4
searchable_dropdown: ^1.1.3
firebase_core: ^0.5.2
code_field: ^1.22.0
connectivity: ^2.0.1

**Comment by aTeamSolace** [comment]
**Flutter doctor -v** 

flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-IN)
• Flutter version 1.22.5 at /Users/ankitafirake/documents/flutter
• Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
• Engine revision ae90085a84
• Dart version 2.10.4


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
• Android SDK at /Users/ankitafirake/Library/Android/sdk
• Platform android-30, build-tools 30.0.2
• ANDROID_HOME = /Users/ankitafirake/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
• Xcode at /Users/ankitafirake/Desktop/Xcode.app/Contents/Developer
• Xcode 11.3, Build version 11C29
• CocoaPods version 1.10.0.beta.2

[!] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
! No devices available

! Doctor found issues in 3 categories.

**Comment by chornthorn** [comment]
Hello dear! i knew this problem is take your time so much, but i spent time an hour to solve it before i know the answer by doing some step in xcode:
1. Open ios project that create in flutter project and open it on xcode
2. Select " Pods" 
3. Change on menu " Build Active Architecture Only" to **true** and depend on running mode.

<img width="1186" alt="Screen Shot 2021-01-15 at 1 19 28 AM" src="https://user-images.githubusercontent.com/36778896/104632161-e24f5100-56cf-11eb-8830-3129514ff36b.png">


*Sorry! for my english

**Comment by TahaTesser** [comment]
Hi  @aTeamSolace 
`webview_flutter` isn't included in your `pubspec.yaml` which might mean one of youyour packages is using it such as `flutter_inappwebview ` and it's an old version of the package based on the error `pub.dartlang.org/webview_flutter-0.3.24/ios/`. 


Can you please try a possible solution provided above in https://github.com/flutter/flutter/issues/73948#issuecomment-760383624? 


If the problem persists, Can you please provide `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using third-party packages such as `flutter_inappwebview` but using `webview_flutter`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
