### ISSUE TITLE
flutter analyze only file changes - Improve DX

### ISSUE THREAD

**Issue by harrytran998** [flutter/flutter#73945]
## Use case

When our project is bigger in times, the flutter analyze is very slow(it takes ~ 30s-1m). So I suggest flutter team do that, improve DX!

## Proposal
I think maybe we check the modified file changes with GIT --> So run only specific those file changed?

**Comment by jonahwilliams** [comment]
You can't analyze a file without analyzing all of its dependencies. If you want incremental analysis, I recommend using the --watch flag.
