### ISSUE TITLE
After focusing a text field, typing always raises the keyboard?

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#73940]
https://user-images.githubusercontent.com/298850/104585150-8b0f9900-565b-11eb-846c-083c25879372.mp4

Please see the above video, after focusing a text field, my app will always raise the keybaord even if the textfield is no longer selected?

The code for this text field is as follows:
```dart
TextField(
  autofocus: false,
  controller: _textController,
  minLines: 1,
  maxLines: 1,
  onSubmitted: (_) => _searchTextUpdated(),
  decoration: InputDecoration(
    fillColor: Colors.grey.shade100,
    filled: true,
    border: InputBorder.none,
  ),
)
```

A different part of my app uses the RawKeyboardListener for keyboard controls and having the keyboard occassionaly appear if the user has previously focused a text field is causing issues.

**Comment by darshankawar** [comment]
@jimmyff 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
Also, does the issue occur on physical device too ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
