### ISSUE TITLE
[web]: widget below DropdownButtonFormField is rendered incorrectly

### ISSUE THREAD

**Issue by temp11750** [flutter/flutter#73952]
Example - column of Widgets in Form:

DropdownButtonFormField(
  isExpanded: true,
  value: _documentType,
  onChanged: (newDocumentType) {
  setState(() {
    documentType = newDocumentType;
     });
  },
  items: widget.listItems,
  decoration: const InputDecoration(
  labelText: 'Dokument tożsamości',
  border: OutlineInputBorder(),
  isDense: true,
   ),
),
TextFormField(
  decoration: const InputDecoration(
  labelText: 'Nr seryjny dokumentu',
  isDense: true,
  border: OutlineInputBorder(),
  ),
  controller: _serialController,
),

![shadow](https://user-images.githubusercontent.com/77452109/104615870-f2dcd880-5689-11eb-8d1e-9dfab40e482d.png)

 When both text field and dropdown are filled shadow is visible.

**Comment by darshankawar** [comment]
This looks same as https://github.com/flutter/flutter/issues/73951.
Closing as duplicate.
