### ISSUE TITLE
[file_selector] Make treatment of extensions given with with '.' consistent

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#73959]
Currently, on some platforms providing `XTypeGroup` extensions with the `.` will work, and on others it won't; see https://github.com/flutter/devtools/pull/2506#issuecomment-760362834 for an example of confusion caused by that.

We should strongly consider normalizing the extensions in the Dart side of the plugin (or maybe in XTypeGroup itself) to the non-`.` form (since that's what an extension list should have; the extension of foo.txt is `txt`, not `.txt`), so that we don't end up with different behavior on different platforms when people pass the wrong version.

/cc @tugorez, @ditman

**Comment by ditman** [comment]
This is a good point. From what I've read, this is an issue with the web version that requires "." for extensions, however, those can be added within the plugin. Let's make this a bug of the web plugin.

We can also add some warnings/assertions that extensions shouldn't start with a "." when creating the XTypeGroup object?

**Comment by stuartmorgan** [comment]
> This is a good point. From what I've read, this is an issue with the web version that requires "." for extensions, however, those can be added within the plugin. Let's make this a bug of the web plugin.

Currently the web implementation accepts either; other platforms don't. The issue is that when some platforms are more permissive than others, cross-platform surprises are more likely. I think the Dart code should either assert there's no `.`, or silently strip any leading `.` before passing to platform implementations. Either one ensures consistency.

**Comment by ditman** [comment]
So let's:

1. Strip+warn leading `.` when initializing `XTypeGroup` with `extension`. (Also check docs to make sure we don't have examples with `.` in them?)
2. Fix _web to add the `.` when converting the `XTypeGroup` to the `accept` String.

**Comment by stuartmorgan** [comment]
> 2. Fix _web to add the `.` when converting the `XTypeGroup` to the `accept` String.

As I said above, web already does this. From the discussion on the PR:
https://github.com/flutter/plugins/blob/master/packages/file_selector/file_selector_web/lib/src/utils.dart#L37

**Comment by tugorez** [comment]
> 1. Strip+warn leading . when initializing XTypeGroup with extension. (Also check docs to make sure we don't have examples with . in them?)

Already working on it!
