### ISSUE TITLE
Some flutter run flag to remove I/flutter (XXXX) from every line in logs

### ISSUE THREAD

**Issue by maxifom** [flutter/flutter#73954]
## Use case
I want to get clean logs in my console like this:
```
INFO: Hello world
```
Instead I get this:
```
I/flutter ( 7372): INFO: Hello world
```

## Proposal

Flag in flutter run command like:
```
flutter run --disable-log-prefix
```

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/50890
