### ISSUE TITLE
iOS Scenario App integration tests failing on beta branch

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#73963]
On the flutter-1.25-candidate.8 branch, the "Mac beta iOS Engine" build is failing because the Scenario App Integration Tests are failing with a golden diff [luci build](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20beta%20iOS%20Engine/68/overview).

Here is a [led build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/fujino_google.com/ad5871b2a9229d2459e818cc3e45fe5dd4088d1fc4564ae4b736e67ce43afc9e/+/annotations) using the previous commit, which originally passed but is now failing.

This test is passing on the master branch. Both beta and master are downloading and installing the same version of Xcode.

To un-block the build, I am going to skip this test on the beta recipe.

**Comment by godofredoc** [comment]
@christopherfujino can we close this bug?

**Comment by christopherfujino** [comment]
sure
