### ISSUE TITLE
Japanese keyboard zenkaku/hankaku, kana keyup events missing

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#73966]
On Windows desktop builds, pressing the 全角／半角 key or the ひらがな／カタカナ key results in a keydown event with no associated keyup event. This seems to cause processing of backspace/arrow key events to fail after that point.

The 全角／半角 key shows keycode 229 (0xe5), scancode: 41, physical keyboard key: 70035.
The  ひらがな／カタカナ key shows keycode 229 (0xe5), scancode 112, physical keyboard key: 70088.
Both have code point 0, modifiers 0.

To repro, run `flutter run -d windows lib/raw_keyboard.dart`. Since that project doesn't yet have windows support, you'll need to add it first by moving it out of the flutter directory, then from within the directory:
```
flutter config --enable-windows-desktop
flutter create .
```
then move it back into the dev/manual_tests directory.

**Comment by stuartmorgan** [comment]
Hopefully fixed by #44918?

**Comment by cbracken** [comment]
This was fixed by https://github.com/flutter/engine/pull/23905
