### ISSUE TITLE
Use consistent directory structure for package_integration_test samples

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#73975]
The [integration_test example](https://github.com/flutter/plugins/tree/master/packages/integration_test/example) uses this folder structure:

```
integration_test/
  example_test.dart
test_driver/
  integration_test.dart
```

But creating a new flutter project only creates a single `integration_test/` directory containing the `integration_test` tests and `flutter_driver` wrapper:

```
integration_test/
  app_test.dart
  driver.dart
```

Right now the [integration_test docs](https://pub.dev/packages/integration_test) and [Integration testing page](https://flutter.dev/docs/testing/integration-tests) both suggest the former, but this should probably match what the template generates, or vice-versa.

**Comment by dnfield** [comment]
The template had to get backed out for other reasons - when we look to reland this, we should make sure it's consistent. Closing for now since it's not clear when we'll do that and this bug no longer applies to code in the repo.
