### ISSUE TITLE
add-to-app project not building with local engine

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#73982]
```
Showing Recent Messages
[   +5 ms] Target debug_universal_framework failed: ProcessException: Process exited abnormally:

           ld: building for iOS, but linking in .tbd file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/usr/lib/libSystem.tbd) built for iOS Simulator, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/usr/lib/libSystem.tbd' for architecture arm64
```

Looks like flutter is trying to build a universal binary despite the need to build for one architecture when you are dealing with a local engine.  My xcode project settings are set to "Build Active Architecture Only" true, which would be x86_64 in this case.

flutter version: 
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.291, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.291 at /Users/aaclarke/dev/flutter
    • Framework revision d83134ae36 (3 days ago), 2021-01-11 16:37:42 -0800
    • Engine revision 0ed964d6b7
    • Dart version 2.12.0 (build 2.12.0-212.0.dev)
```

xcode version: 
12.2

**Comment by gaaclarke** [comment]
Here's the full output from that phase: [log.txt](https://github.com/flutter/flutter/files/5817223/log.txt)

**Comment by jmagman** [comment]
The local engine build is always setting `ARCHS=arm64`.

In the host app Xcode is passing `ARCHS=x86_64` but it's being overridden. `.ios/Flutter/flutter_export_environment.sh` has:
```
export "LOCAL_ENGINE=ios_debug_sim_unopt"
export "ARCHS=arm64"
```

https://github.com/flutter/flutter/blob/f63055a895b337afd81672cc1ae4499e6aa06a3f/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L204-L207

I don't see how this ever worked in host apps using a local engine, this logic was introduced in #17919.
