### ISSUE TITLE
Adding Accessibility ID in flutter app - Android

### ISSUE THREAD

**Issue by shadab2510** [flutter/flutter#74013]
I want to add Accessibility ID in the flutter app, so that i can use it for the automation testing using appium to locate the specific element, 

e.g - If we have "Username" text field on the app and we want to give a unique Accessibility ID to "Username" text field

**Comment by darshankawar** [comment]
@shadab2510 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/17988
Please follow-up there for updates.
Closing this as duplicate.
