### ISSUE TITLE
document the purpose of setState's callback argument

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#74011]
I just randomly realized I don't understand why `setState` has a callback argument, i.e. what's the difference between these two
```dart
setState(() { _myState = newValue; });
```

```dart
_myState = newValue;
setState(() {});
```

Why is the former one better the the latter?

**Comment by darshankawar** [comment]
@nt4f04uNd 
The function callback argument is triggered when `setState()` is complete and underlying method or widget is rendered. As it's an `async` call, the callback argument is used for any action after rendering is done.

**Comment by nt4f04uNd** [comment]
> @nt4f04uNd
> The function callback argument is triggered when `setState()` is complete and underlying method or widget is rendered. As it's an `async` call, the callback argument is used for any action after rendering is done.

@darshankawar WHAT?
i'm gonna encourage you to triage the issue decetly, what you are doing is simply inappropriate. the issue is about documentation but from your statement it's obvious you didn't even bothered yourself with checking it out https://api.flutter.dev/flutter/widgets/State/setState.html

your statement is diametrically opposite to the documented and actual behavior
https://github.com/flutter/flutter/blob/b7f6d9bcb2333bae29e55e98befdad3723a97f2b/packages/flutter/lib/src/widgets/framework.dart#L1267-L1287

**Comment by darshankawar** [comment]
@nt4f04uNd 
Thanks for the advice and suggestion.

**Comment by nt4f04uNd** [comment]
Closing, because https://github.com/flutter/flutter/issues/12296 was reopened
