### ISSUE TITLE
[web]: flutter run fails when targeting android emulator

### ISSUE THREAD

**Issue by Simon-GitHub-Code** [flutter/flutter#74015]
Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859 (9 days ago) • 2021-01-05 12:34:13 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)

Flutter works when targeting the web but if I target an Android Emulator it fails with the following error when trying to build the application.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:processDebugManifest' (type 'ProcessMultiApkApplicationManifest').
> File '.\build\app\intermediates\merged_manifest\debug\out\AndroidManifest.xml' specified for property 'mainMergedManifest' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        22.2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
Hi @Simon-GitHub-Code 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `android\app\src\main\AndroidManifest.xml`?
Thank you

**Comment by Simon-GitHub-Code** [comment]
PS D:\code\flutter\demo> flutter doctor -v
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-AU)
    • Flutter version 1.25.0-8.3.pre at C:\Users\SimonTulett\src\flutter
    • Framework revision 5d36f2e7f5 (23 hours ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\SimonTulett\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\SimonTulett\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!






PS D:\code\flutter\demo> flutter run --verbose
[ +159 ms] executing: [C:\Users\SimonTulett\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +134 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +2 ms] executing: [C:\Users\SimonTulett\src\flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[  +96 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +1 ms] 1.25.0-8.3.pre
[ +205 ms] executing: [C:\Users\SimonTulett\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +108 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Users\SimonTulett\src\flutter/] git ls-remote --get-url origin
[  +83 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +179 ms] executing: [C:\Users\SimonTulett\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[ +141 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +40 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +39 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +176 ms] executing: C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +81 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:4
[  +12 ms] C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +100 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +96 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +376 ms] Skipping pub get: version match.
[ +165 ms] Found plugin integration_test at C:\Users\SimonTulett\src\flutter\packages\integration_test\
[ +233 ms] Found plugin integration_test at C:\Users\SimonTulett\src\flutter\packages\integration_test\
[  +12 ms] Generating D:\code\flutter\demo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +108 ms] ro.hardware = ranchu
[  +29 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +40 ms] Initializing file store
[  +16 ms] Skipping target: gen_localizations
[  +18 ms] complete
[   +7 ms] Launching lib\main.dart on sdk gphone x86 arm in debug mode...
[  +28 ms] C:\Users\SimonTulett\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\SimonTulett\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\SimonTulett\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\SIMONT~1\AppData\Local\Temp\flutter_tools.50cd34e5\flutter_tool.af940111\app.dill --packages D:\code\flutter\demo\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation   
--filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +53 ms] executing: C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +36 ms] <- compile package:demo/main.dart
[ +150 ms] --------- beginning of main
                    01-16 09:44:03.617 I/MicroDetectionWorker( 3307): #onError(false)
[  +20 ms] executing: C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +150 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.5-6877874
                    Installed as C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\SimonTulett\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +68 ms] Building APK
[  +35 ms] Running Gradle task 'assembleDebug'...
[  +25 ms] Using gradle from D:\code\flutter\demo\android\gradlew.bat.
[  +79 ms] D:\code\flutter\demo\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +44 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +193 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +42 ms] executing: [D:\code\flutter\demo\android/] D:\code\flutter\demo\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=D:\code\flutter\demo\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1418 ms] Welcome to Gradle 6.7!
[   +3 ms] Here are the highlights of this release:
[   +3 ms]  - File system watching is ready for production use
[   +3 ms]  - Declare the version of Java your build requires
[   +2 ms]  - Java 15 support
[   +4 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+5565 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[  +98 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :integration_test:preBuild UP-TO-DATE
[   +1 ms] > Task :integration_test:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :integration_test:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +159 ms] > Task :integration_test:packageDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +3 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +61 ms] > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
[   +2 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +3 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +83 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +5 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +2 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +2 ms] > Task :integration_test:mergeDebugShaders UP-TO-DATE
[   +3 ms] > Task :integration_test:compileDebugShaders NO-SOURCE
[   +4 ms] > Task :integration_test:generateDebugAssets UP-TO-DATE
[  +76 ms] > Task :integration_test:packageDebugAssets UP-TO-DATE
[   +3 ms] > Task :app:mergeDebugAssets UP-TO-DATE
[  +70 ms] > Task :app:copyFlutterAssetsDebug NO-SOURCE
[  +43 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +74 ms] > Task :integration_test:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :integration_test:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :integration_test:generateDebugResources UP-TO-DATE
[  +11 ms] > Task :integration_test:packageDebugResources UP-TO-DATE
[  +86 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +2 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[  +49 ms] > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
[  +37 ms] > Task :integration_test:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest FAILED
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +2 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +2 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +3 ms] 20 actionable tasks: 1 executed, 19 up-to-date
[  +50 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[   +1 ms] A problem was found with the configuration of task ':app:processDebugManifest' (type 'ProcessMultiApkApplicationManifest').
[   +2 ms] > File 'D:\code\flutter\demo\build\app\intermediates\merged_manifest\debug\out\AndroidManifest.xml' specified for property 'mainMergedManifest' does not exist.
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[  +62 ms] BUILD FAILED in 7s
[ +381 ms] Running Gradle task 'assembleDebug'... (completed in 8.8s)
[+4819 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 15,831ms.
[  +30 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>


[ +175 ms] ensureAnalyticsSent: 115ms
[   +7 ms] Running shutdown hooks
[  +36 ms] Shutdown hook priority 4
[  +16 ms] Shutdown hooks complete
[  +40 ms] exiting with code 1









<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.demo">
   <application
        android:label="demo"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by pedromassangocode** [comment]
Hi @Simon-GitHub-Code 
Have you changed your manifest.xml file or any related file in your /android folder? If not I would suggest you to delete the Android folder and run `flutter create .`to recreate the android folder.

**Comment by Simon-GitHub-Code** [comment]
I tried that and got this error message instead.


PS D:\code\flutter\demo> flutter run
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compressDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
   > D:\code\flutter\demo\build\app\intermediates\merged_assets\debug\out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        60.4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
Hi @Simon-GitHub-Code 
Can you please provide your `flutter run -v`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
