### ISSUE TITLE
ClipRRect does not work on Fuchsia for ChildViews

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7402]

**Comment by abarth** [comment]
This feature is blocked on @j9brown adding RRect clips to Mozart's scene graph.

**Comment by apwilson** [comment]
@jimbeveridge @maryx

**Comment by eseidelGoogle** [comment]
@apwilson was asking about this today.  Is this still blocked on @j9brown?

**Comment by Hixie** [comment]
Current status from Flutter team is that we are not working on this because we believe this has upstream dependencies. Please let us know if this is something we should be dealing with in the near future.

**Comment by j9brown** [comment]
This is fixed in Mozart 2.
