### ISSUE TITLE
Flutter web app is not running in linux | Web app crashes without even launching |flutter run -d chrome|

### ISSUE THREAD

**Issue by Gladrin22** [flutter/flutter#74020]
**I am trying to run my 1st flutter web app** by using the command **_flutter run -d chrome_** so , to be specific i am using Linux . yeah , i was trying to run it but  i didn't get to see the output in my chrome ..??? so could you please help me .     :-)

![Screenshot from 2021-01-15 11-50-05](https://user-images.githubusercontent.com/61659332/104689048-d98a6980-5727-11eb-8a11-63cfde2e499e.png)

[flutter_04.log](https://github.com/flutter/flutter/files/5818801/flutter_04.log)
I have even attached the log file with this ,... _**kindly help me to solve this**_ .

**Comment by TahaTesser** [comment]
Hi @Gladrin22 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/73743
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
