### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by fpagano** [flutter/flutter#74025]
I am not able to run the initial sample program in Chrome on Linux Mint. I already tried to:
1) disable firewall: sudo ufw off
2) switch flutter to stable channel and back to beta channel
3) flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Linux, locale it_IT.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (1 available)
4) force the listening port: flutter run -d chrome --web-hostname 0.0.0.0 --web-port 55555 -v

The problem arises either from command line (flutter run) either from Android Studio

## Command
```
flutter run -v
```

## Steps to Reproduce
1. flutter create myapp
2. cd myapp
3. flutter run -v

## Logs
HttpException
```

```
```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Linux, locale it_IT.UTF-8)
    • Flutter version 1.25.0-8.2.pre at
      /home/francesco/snap/flutter/common/flutter
    • Framework revision b0a2299859 (9 giorni fa), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/francesco/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/francesco/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: b0a22998593fc605c723dee8ff4d9315c32cfe2c
### Plugins
integration_test

##System:
System:    Kernel: 5.4.0-62-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 80SV v: Lenovo ideapad 510-15IKB serial: <filter> 
           Chassis: type: 10 v: Lenovo ideapad 510-15IKB serial: <filter> 
           Mobo: LENOVO model: Torronto 5C1 v: SDK0J40709 WIN serial: <filter> UEFI: LENOVO 
           v: 3JCN31WW date: 07/17/2018 
Battery:   ID-1: BAT0 charge: 21.6 Wh condition: 22.0/28.5 Wh (77%) volts: 8.1/7.3 
           model: SANYO L15S2TB0 serial: <filter> status: Unknown 
           Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard serial: <filter> 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i7-7500U bits: 64 type: MT MCP arch: Amber Lake 
           rev: 9 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 23199 
           Speed: 2968 MHz min/max: 400/3500 MHz Core speeds (MHz): 1: 2968 2: 2981 3: 2974 
           4: 2980 
Graphics:  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:5916 
           Device-2: NVIDIA GM108M [GeForce 940MX] vendor: Lenovo driver: N/A bus ID: 03:00.0 
           chip ID: 10de:134d 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.2.6 
           direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo driver: snd_hda_intel 
           v: kernel bus ID: 00:1f.3 chip ID: 8086:9d71 
           Sound Server: ALSA v: k5.4.0-62-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo 
           driver: r8169 v: kernel port: 5000 bus ID: 01:00.0 chip ID: 10ec:8168 
           IF: enp1s0 state: down mac: <filter> 
           Device-2: Realtek RTL8821AE 802.11ac PCIe Wireless Network Adapter vendor: Lenovo 
           driver: rtl8821ae v: kernel port: 4000 bus ID: 02:00.0 chip ID: 10ec:8821 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 1.38 TiB used: 719.33 GiB (51.1%) 
           ID-1: /dev/sda type: USB vendor: Sabrent model: SABRENT size: 476.94 GiB 
           serial: <filter> 
           ID-2: /dev/sdb vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 424.45 GiB used: 32.60 GiB (7.7%) fs: ext4 dev: /dev/sda6 
           ID-2: swap-1 size: 29.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 45.5 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyssa main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https: //packages.microsoft.com/repos/ms-teams stable main
Info:      Processes: 229 Uptime: 59m Memory: 11.60 GiB used: 3.38 GiB (29.2%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by darshankawar** [comment]
@fpagano 
There's similar open issue describing your case, affecting linux platform, https://github.com/flutter/flutter/issues/72522
Please follow-up there for updates.
Closing this as duplicate.

**Comment by iapicca** [comment]
this is a `snap` installation issue, follow up [here](https://github.com/canonical/flutter-snap/issues/23)
