### ISSUE TITLE
Date Picker is not  working after clicking cancle.

### ISSUE THREAD

**Issue by yannainghtun-mk** [flutter/flutter#74032]

**Comment by pedromassangocode** [comment]
Hi @yannainghtun-mk 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by yannainghtun-mk** [comment]
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.2.pre at /home/kishan/flutter
    • Framework revision b0a2299859 (10 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/kishan/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/kishan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at /home/kishan/android-studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/kishan/intellij
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • CPH1933 (mobile) • ad928c66 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by yannainghtun-mk** [comment]
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.2.pre at /home/kishan/flutter
    • Framework revision b0a2299859 (10 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/kishan/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/kishan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at /home/kishan/android-studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/kishan/intellij
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • CPH1933 (mobile) • ad928c66 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by yannainghtun-mk** [comment]
https://user-images.githubusercontent.com/74854366/104796913-bbd10900-57e8-11eb-9d00-9996bb40189b.mp4

**Comment by yannainghtun-mk** [comment]
void _selectDate(BuildContext context) async {
    _selected_date=await showDatePicker(context: context, initialDate: _selected_date, firstDate: DateTime(1920), lastDate: DateTime.now());
    if (_selected_date!=null)
    setState(() {
      _date_shower="${_selected_date.day}-${_selected_date.month}-${_selected_date.year}";
    });
  }
