### ISSUE TITLE
iOS app crashes after splash screen when installed using TestFlight

### ISSUE THREAD

**Issue by kaushal231291** [flutter/flutter#74038]
**iOS app crashing after splash screen when installed using TestFlight. However, its working fine when installed directly on device or simulator.** I checked on iOS 13 and 14. Both apps are crashing right after splash screen.

**Flutter version:**
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Xcode Version: 12.3 (12C33)**

- Steps to Reproduce
1. flutter build ios
2. Go to Xcode, Product > Archive
3. Upload the app build using Xcode
4. Install the app using TestFlight

**flutter doctor -v** output below:

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.5 at /Users/my_name/Downloads/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/my_name/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Redmi Note 7 (mobile)     • 8b77dea9                                 •
      android-arm64 • Android 10 (API 29)
    • My_phone's iPhone (mobile) •iphone_id • ios
      • iOS 13.3.1

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
Hi @kaushal231291 
Can you please reproduce using `.ipa`?  Are you using any packages? Just splash screen.  
Thank you

**Comment by kaushal231291** [comment]
Hi @TahaTesser , Thanks for the reply. "Can you please reproduce using .ipa?" I could not get what you are asking for here. Do you want me to share ipa file with you? 

We are using following packages:
  provider: ^3.2.0
  styled_widget: ^0.2.1+2
  flappy_search_bar: ^1.4.1
  url_launcher: ^5.7.10
  infinite_listview: ^1.0.1+1
  flutter_speed_dial: ^1.0.10
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.0.3
  percent_indicator: ^2.1.1
  intl: ^0.16.0
  oauth1: ^1.0.1
  http: ^0.12.0+4
  syncfusion_flutter_charts: ^18.1.45
  smooth_page_indicator: ^0.1.5
  fl_chart: ^0.9.3
  carousel_slider: ^2.2.1
  charts_flutter: ^0.9.0
  shared_preferences: ^0.5.7
  webview_flutter: ^1.0.6
  bmprogresshud: ^0.0.6
  cached_network_image: ^2.2.0
  flutter_local_notifications: ^3.0.1+6
  firebase_core: ^0.5.2
  auto_size_text: ^2.1.0
  firebase_messaging: ^6.0.15
  star_menu: ^1.0.4
  get_it: ^4.0.2
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share
  youtube_player_flutter: ^7.0.0+3
  razorpay_flutter: ^1.2.1
  google_fonts: ^1.1.0
  json_annotation: ^3.1.0
  flutter_svg: ^0.18.1
  marquee: ^1.6.1
  toast: ^0.1.5
  image_picker: ^0.6.7+14
  firebase_storage: ^5.0.1
  sqflite: ^1.3.2+1
  flutter_linkify: ^4.0.2
  clipboard: ^0.1.2+8
  page_transition: ^1.1.7+4
  
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.11
  firebase_dynamic_links: ^0.5.1
  firebase_remote_config: ^0.4.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  google_sign_in: ^4.4.1
  apple_sign_in: ^0.1.0
  showcaseview: ^0.1.6
  uuid: ^2.2.2
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  rename: ^1.1.9
  build_runner: ^1.10.4
  json_serializable: ^3.5.0

**Comment by TahaTesser** [comment]
Hi @kaushal231291 
Can you please try reproducing locally in `flutter run --release --verbose`, on a physical, provide these logs or by using `ipa` build and installing it on a physical device.
Also to better address the issue, we need a reproducible code sample. 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
