### ISSUE TITLE
Migrate devicelab mac-android tests to LUCI

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#74059]
This is part of devicelab migration to LUCI, and is focused on mac-android tests.

Detailed steps:
- [x] Provision mac bot supporting android device in staging pool
- [x] Enable all mac-android tests in staging
- [x] Mark staging bots as prod
- [x] Update config to trigger post tests to prod pool
- [x] Disable triggering devicelab agent tests
- [x] Move bots to production salt.

**Comment by keyonghan** [comment]
flutter-devicelab-mac-22 is available in staging. With https://github.com/flutter/cocoon/pull/1038, and bot config from chromium side, the android phone is visible in swarming bot.

**Comment by godofredoc** [comment]
@yusufm can we move all the mac_android bots to from salt staging to prod? we'll need to verify all the relevant changes have landed to salt prod before moving them.

**Comment by yusufm** [comment]
Checking salt server version.

**Comment by yusufm** [comment]
cacbe0ef is still missing from prod. Will switch over as soon as it lands.

**Comment by yusufm** [comment]
Hosts moved to prod salt master: https://github.com/flutter/flutter/issues/75016

**Comment by keyonghan** [comment]
I guess this is done. Closing.
