### ISSUE TITLE
Universal Windows Platform development tools missing from Windows build bots

### ISSUE THREAD

**Issue by clarkezone** [flutter/flutter#74050]
Attempting to land this PR: https://github.com/flutter/engine/pull/23573 which introduces a Windows UWP shell embedder to Flutter Engine.  Whilst the patch builds on my local dev box, it isn't building on the bots:

FAILED: obj/flutter/shell/platform/windows/flutter_windows_source.angle_surface_manager.obj 
ninja -t msvc -e environment.x64 -- C:\b\s\w\ir\cache\goma\client/gomacc.exe ../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe  /nologo /showIncludes @obj/flutter/shell/platform/windows/flutter_windows_source.angle_surface_manager.obj.rsp /c ../../flutter/shell/platform/windows/angle_surface_manager.cc /Foobj/flutter/shell/platform/windows/flutter_windows_source.angle_surface_manager.obj /Fdobj/flutter/shell/platform/windows/flutter_windows_source_cc.pdb
../../flutter/shell/platform/windows/angle_surface_manager.cc(13,10): fatal error: 'winrt/Windows.UI.Core.h' file not found
#include <winrt/Windows.UI.Core.h>

Which I'm guessing is due to the fact that the Visual Studio install on the build bots doesn't include 

1. Universal Windows Platform development tools
2. Windows 10 SDK 10.0.18362
3. C++ (v141) Universal Windows Platform Tools
4. C++ (v142) Universal Windows Platform Tools

![image](https://user-images.githubusercontent.com/1128250/104751662-8a820b80-570a-11eb-958c-376cb2a17aae.png)

@stuartmorgan for FYI

**Comment by stuartmorgan** [comment]
I'm not clear on whether it's the goma machines or our locally installed VS that determines whether there are missing header issues. If the latter, maybe if I can manage to get the VS 2019 roll working that would address this? We should look at what the package that's installed locally by that script includes for 2017 and 2019.

**Comment by godofredoc** [comment]
Talked to the goma team yesterday and they asked us to run the builder without goma to identify if it is a problem with goma or not.  They mention goma is using ATS and should be using the same toolchains as the bot is using.

**Comment by godofredoc** [comment]
Taking this bug out of the ticket queue as it may take a few days to resolve.

**Comment by dnfield** [comment]
I doubt this has anything to do with GOMA. It's very likely that some SDK pieces are missing on the bots.

**Comment by godofredoc** [comment]
@cbracken with your new changes to the visual studio bundle will this get fixed?

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
