### ISSUE TITLE
Create a Flutter SDK packages allowlist and use it to prevent accidentally adding new dependencies

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#74070]
As discussed with several members of the Dart team today, they'd like to avoid us introducing new pinned dependencies without first getting approval from their authors. Similarly, the Flutter team would like to avoid accidentally introducing new dependencies in user-facing packages within the SDK.

To accomplish this goal, I will create an allow-list of the current package set (post integration_test reverts) and change `flutter update-packages --force-upgrade` to fail if the set of core package dependencies grows beyond this. As a separate process, we will also review this allow-list with the Dart team to highlight any problematic packages.

**Comment by Hixie** [comment]
SGTM. Make sure to add a big comment in the code near where you would need to change it to allow more things to say that the list shouldn't be changed without following this or that protocol and getting review from this or that person (that can be me if you would like, or can be whomever else you think is appropriate, e.g. you). You may want to consider also adding a test that verifies that the list itself hasn't been changed... that way it's even more obvious that the list shouldn't change.
