### ISSUE TITLE
Stuck at Running Gradle task 'assembleDebug'... when running flutter app

### ISSUE THREAD

**Issue by SamDc73** [flutter/flutter#74076]
i'm runing Pop_OS! 20.10

`flutter doctor -v `
```
> [✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.22.3 at /home/samdc/DevTools/flutter
>     • Framework revision 8874f21e79 (3 months ago), 2020-10-29 14:14:35 -0700
>     • Engine revision a1440ca392
>     • Dart version 2.10.3
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/samdc/DevTools/Android/SDK
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [!] Android Studio
>     • Android Studio at /opt/android-studio
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • android-studio-dir = /opt/android-studio
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.52.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.18.1
> 
> [✓] Connected device (1 available)
>     • Google Nexus 5 (mobile) • 192.168.56.101:5555 • android-x86 • Android 5.1
>       (API 22)
```

`dart --version`
> Dart SDK version: 2.10.3 (stable) (Tue Oct 27 14:44:30 2020 +0100) on "linux_x64"

`java --version`
> openjdk 14.0.2 2020-07-14
> OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-1)
> OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-1, mixed mode, sharing)

`gradle -v`
```
> ------------------------------------------------------------
> Gradle 6.8
> ------------------------------------------------------------
> 
> Build time:   2021-01-08 16:38:46 UTC
> Revision:     b7e82460c5373e194fb478a998c4fcfe7da53a7e
> 
> Kotlin:       1.4.20
> Groovy:       2.5.12
> Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
> JVM:          14.0.2 (Private Build 14.0.2+12-Ubuntu-1)
> OS:           Linux 5.8.0-7630-generic amd64


When i try to run flutter app from terminal using `flutter run ` i get this massege 
> Launching lib/main.dart on Google Nexus 5 in debug mode...
> Running Gradle task 'assembleDebug'...
```
and  it will be stuck forever .

and as the emulator i'm using genymotion
and i'm using VPN because my country is banned from using google services , and the internet speed is unstable .
and also i tried to run the app from VS Code with no luck .
i've been trying to install flutter for 2 weeks with no luck , hope find the solution

**Comment by iapicca** [comment]
> > openjdk 14.0.2 2020-07-14

@SamDc73 
only [OpenJDK8](http://download.java.net/openjdk/jdk8u40/ri/openjdk-8u40-src-b25-10_feb_2015.zip) is supported
try installing the correct version

**Comment by SamDc73** [comment]
@iapicca
i installed OpenJDK8,still not luck.
the output of `java -version` is

>  openjdk version "1.8.0_275"
> OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.10-b01)
> OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
>

**Comment by SamDc73** [comment]
Now i'm getting this error when trying to run the flutter app via terminal:

> 
> Launching lib/main.dart on Google Nexus 5 in debug mode...
> Running Gradle task 'assembleDebug'...                                  
> Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/samdc/.gradle/wrapper/dists/gradle-6.8-all/9emh0d32e025cam7aasxcw002/gradle-6.8-all.zip
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.Install.createDist(Install.java:48)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Running Gradle task 'assembleDebug'...                                                                                                         
> Running Gradle task 'assembleDebug'... Done                       120.5s (!)
> [!] Gradle threw an error while downloading artifacts from the network. Retrying to
> download...
> Running Gradle task 'assembleDebug'...                                  
> Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/samdc/.gradle/wrapper/dists/gradle-6.8-all/9emh0d32e025cam7aasxcw002/gradle-6.8-all.zip
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.Install.createDist(Install.java:48)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> Running Gradle task 'assembleDebug'...                                                              at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Running Gradle task 'assembleDebug'...                                                                                                         
> Running Gradle task 'assembleDebug'... Done                       120.3s (!)
> [!] Gradle threw an error while downloading artifacts from the network. Retrying to
> download...
> Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TahaTesser** [comment]
Hi @SamDc73 
https://github.com/flutter/flutter/issues/74076#issuecomment-761581262 this due to incomplete or broken Gradle installation.
Go to your root directory and delete `.gradle` folder
`cd ~`
`rm -rf .gradle/`
and connect to a stable internet connection and run the flutter app, this will download fresh Gradle, it will take time, don't cancel or restart the app until the app launches.

This isn't an issue with Flutter itself 
Thank you

**Comment by flutterq** [comment]
All Possible Solutions Added [[Solved] Flutter App stuck at “Running Gradle task ‘assembleDebug’… ”](https://fluttercorner.com/flutter-app-stuck-at-running-gradle-task-assembledebug/)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
