### ISSUE TITLE
StreamBuilder + Firestore works in a weird way at times, randomly.

### ISSUE THREAD

**Issue by AbhideepChakravarty** [flutter/flutter#74071]
I can't exactly summarize the problem in one line for title. Not even in detail as I am not sure what exactly is going wrong. I am attaching two screenshots. One is from laptop (PC) chrome and another Android Chrome. Rest is same. Same data base, same code..... Just the different output - At one place its complete "WESTERN MAINS" and another place its just "WESTERN". Not sure what is wrong. Please suggest.

D:\Eclatian\Code\restaurants>flutter doctor
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-2.0.pre.275, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (2 available)  

! Doctor found issues in 1 category.
![FlutterPCChrome](https://user-images.githubusercontent.com/9032142/104774258-59521b80-579c-11eb-990c-91c0267190db.png)
![Screenshot_20210116-013611.jpg](https://user-images.githubusercontent.com/9032142/104774293-71c23600-579c-11eb-899a-86208eb15668.jpg)

**Comment by GZGavinZhao** [comment]
Is it possible to attach your code for the "WESTERN" part?

**Comment by AbhideepChakravarty** [comment]
This is part of a full file.

Widget getSections(AsyncSnapshot<QuerySnapshot> sections, String foodItemSeq,
      String tnc, BuildContext context) {
    List<Widget> widgets = [];
    this.searchableFoodItems = Map();
    sections.data.docs.forEach((section) {
      Widget sectionWidget = Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
          width: MediaQuery.of(context).size.width,
          height: 200,
          child: Stack(children: getSectionTitle(section)));
      Widget foodItems =
          getFoodItems(section, context, section['name'], foodItemSeq);
      widgets.add(sectionWidget);
      widgets.add(foodItems);
    });
    if (tnc != null) {
      widgets.add(Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10), child: HtmlWidget(tnc)));
    }
    return SingleChildScrollView(
      child: Column(
        children: widgets,
      ),
    );
  }


and then 

Widget getSectionTitle(QueryDocumentSnapshot section) {
    List<Widget> widgets = [];
    widgets.add(Text(
      section['name'],
      textAlign: TextAlign.left,
      style: TextStyle(fontSize: 28.0),
    ));

    if (section.data().containsKey("subText")) {
      widgets.add(Text(
        section['subText'],
        textAlign: TextAlign.left,
        style: TextStyle(fontSize: 18.0),
      ));
    }
    return Container(
      padding: EdgeInsets.all(8),
      child: Column(
        children: widgets,
      ),
    );
  }

**Comment by AbhideepChakravarty** [comment]
Try to search "Search me for section"


`import 'package:provider/provider.dart';
import 'package:restaurants/ui/theme/mytheme.dart';
import 'package:universal_io/io.dart';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:restaurants/helper/firebase.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:restaurants/ui/icon_helper.dart';

class MenuPageUI extends StatefulWidget {
  final String menuCode;
  MenuPageUI({Key key, this.menuCode}) : super(key: key);

  @override
  _MenuPageUIState createState() => _MenuPageUIState();
}

class _MenuPageUIState extends State<MenuPageUI> {
  Map<String, SearchListItemContent> searchableFoodItems;

  @override
  Widget build(BuildContext context) {
    FirebaseFirestore firestore = FirebaseInitializer.firestore;
    DocumentReference menu =
        firestore.collection("menus").doc(widget.menuCode.toUpperCase());
    return StreamBuilder<DocumentSnapshot>(
      stream: menu.snapshots(),
      builder: (context, menu) {
        Widget widget = Center(child: CircularProgressIndicator());
        if (!menu.hasData && menu.connectionState == ConnectionState.active) {
          widget = Scaffold(
            appBar: AppBar(title: Text("Error!!")),
            body: Center(
                child: Text("We could not load the menu. Please retry.")),
          );
        } else if (menu.connectionState == ConnectionState.active &&
            menu.hasData) {
          widget = getBody(menu, context);
        } else if (!menu.hasData &&
            menu.connectionState == ConnectionState.waiting) {
          widget = Center(
            child: CircularProgressIndicator(),
          );
        }
        return widget;
      },
    );
  }

  Widget getBody(AsyncSnapshot<DocumentSnapshot> menu, BuildContext context) {
    var scaffold = Scaffold(
      appBar: AppBar(
          title: Text(menu.data.data()['name'].toString()),
          actions: getAppBarActions()),
      body: buildSections(menu, context),
    );
    return scaffold;
  }

  List<Widget> getAppBarActions() {
    List<Widget> widgets = [];
    if (Platform.operatingSystem.toLowerCase() != "android") {
      widgets.add(IconButton(
        icon: Icon(Icons.search),
        onPressed: () {
          showSearch(
              context: context,
              delegate: FoodItemSearchDelegate(this.searchableFoodItems));
        },
      ));
    }
    return widgets;
  }

  buildSections(AsyncSnapshot<DocumentSnapshot> menu, BuildContext context) {
    Query sections = menu.data.reference.collection("sections").orderBy("seq");
    String foodItemSeq = menu.data.data()['seq'].toString();
    String tnc;
    if (menu.data.data().containsKey("tnc")) {
      tnc = menu.data.data()['tnc'].toString();
    }
    return StreamBuilder<QuerySnapshot>(
        stream: sections.snapshots(),
        builder: (context, sections) {
          Widget widget;
          if (sections.hasData) {
            widget = getSections(sections, foodItemSeq, tnc, context);
          } else {
            widget = Center(
              child: CircularProgressIndicator(),
            );
          }
          return widget;
        });
  }

  Widget getSections(AsyncSnapshot<QuerySnapshot> sections, String foodItemSeq,
      String tnc, BuildContext context) {
    List<Widget> widgets = [];
    this.searchableFoodItems = Map();
    sections.data.docs.forEach((section) {
      Widget sectionWidget = Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
          decoration: BoxDecoration(
            border: Border(
              bottom: BorderSide(width: 5.0, color: Colors.black),
            ),
          ),
          //alignment: AlignmentGeometry(),
          child: Column(children: getSectionText(section)));
      Widget foodItems =
          getFoodItems(section, context, section['name'], foodItemSeq);
      widgets.add(sectionWidget);
      widgets.add(foodItems);
    });
    if (tnc != null) {
      widgets.add(Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10), child: HtmlWidget(tnc)));
    }
    return SingleChildScrollView(
      child: Column(
        children: widgets,
      ),
    );
  }

  List<Widget> getSectionText(QueryDocumentSnapshot section) {
    List<Widget> widgets = [];
    widgets.add(Text(
      section['name'],                         //Search me for section
      textAlign: TextAlign.left,
      style: TextStyle(fontSize: 28.0),
    ));

    if (section.data().containsKey("subText")) {
      widgets.add(Text(
        section['subText'],
        textAlign: TextAlign.left,
        style: TextStyle(fontSize: 18.0),
      ));
    }
    return widgets;
  }

  Widget getFoodItems(QueryDocumentSnapshot element, BuildContext context,
      String sectionName, String foodItemSeq) {
    Query foodItems =
        element.reference.collection("fooditems").orderBy(foodItemSeq);

    /////orint("Creating section body : " + foodItems.toString());
    var widget = StreamBuilder<QuerySnapshot>(
        stream: foodItems.snapshots(),
        builder: (context, foodItems) {
          ////orint("Food item has data :" + foodItems.error.toString());
          Widget widget;
          if (!foodItems.hasData &&
              foodItems.connectionState == ConnectionState.done) {
            widget = Center(
              child: Text("We could not load the food items. Please retry."),
            );
          } else if (foodItems.hasData) {
            widget = getFoodItemWidget(foodItems, context, sectionName);
          } else {
            widget = Center(
              child: CircularProgressIndicator(),
            );
          }
          return widget;
        });
    return widget;
  }

  Widget getFoodItemWidget(AsyncSnapshot<QuerySnapshot> foodItems,
      BuildContext context, String sectionName) {
    List<Widget> listTile = [];
    foodItems.data.docs.forEach((DocumentSnapshot foodItem) {
      SearchListItemContent value = SearchListItemContent(
          title: foodItem.data()['name'],
          subTitle: foodItem.data()['desc'],
          price: foodItem.data()['price'],
          section: sectionName,
          category: foodItem.data()['category']);
      this.searchableFoodItems.update(
            foodItem.id,
            (existingValue) => value,
            ifAbsent: () => value,
          );
      Widget tile = Container(
          padding: EdgeInsets.all(8.0),
          decoration: BoxDecoration(
              //borderRadius: BorderRadius.all(Radius.circular(10.0)),
              color: Colors.white,
              border: Border(
                bottom: BorderSide(
                    width: 1.0,
                    color: Provider.of<ThemeChanger>(context)
                        .getTheme
                        .primaryColor),
              )
              //boxShadow: [
              //BoxShadow(
              //    color: Colors.black26, spreadRadius: 2.0, blurRadius: 5.0)
              //]
              ),
          width: MediaQuery.of(context).size.width,
          child: Row(mainAxisSize: MainAxisSize.max, children: <Widget>[
            Expanded(
              child: getFoodItemTile(foodItem),
            ),
          ]));
      listTile.add(tile);
    });
    return Column(
      children: listTile,
    );
    //return foodItemList;
  }

  Widget getFoodItemTile(DocumentSnapshot foodItem) {
    ListTile listTile;
    if (foodItem.data()['desc'] != null) {
      listTile = ListTile(
          trailing: Text(foodItem.data()['price']),
          title: getFoodItemTitle(foodItem),
          subtitle: Text(foodItem.data()['desc']));
    } else {
      listTile = ListTile(
        trailing: Text(foodItem.data()['price']),
        title: getFoodItemTitle(foodItem),
      );
    }
    return listTile;
  }

  Widget getFoodItemTitle(DocumentSnapshot foodItem) {
    List<Widget> titelContent = getCategoryIcon(foodItem);
    titelContent.add(Text(foodItem.data()['name']));
    return Row(
      children: titelContent,
    );
  }

  List<Widget> getCategoryIcon(DocumentSnapshot foodItem) {
    List<Widget> rowItems = [];
    if (foodItem.data().containsKey('category')) {
      foodItem.data()['category'].toString().split(",").forEach((element) {
        switch (element) {
          case "0":
            rowItems.add(IconHelper.getFoodCategoryIcon("0"));
            break;
          case "1":
            rowItems.add(IconHelper.getFoodCategoryIcon("1"));
            break;
          case "2":
            rowItems.add(IconHelper.getFoodCategoryIcon("2"));
            break;
          case "3":
            rowItems.add(IconHelper.getFoodCategoryIcon("3"));
            break;
          case "4":
            rowItems.add(IconHelper.getFoodCategoryIcon("4"));
            break;
        }
      });
    }
    return rowItems;
  }
}

class SearchListItemContent {
  final String title;
  final String subTitle;
  final String price;
  final String section;
  final String category;

  SearchListItemContent(
      {this.title, this.subTitle, this.price, this.section, this.category});
}

class FoodItemSearchDelegate extends SearchDelegate<String> {
  final Map<String, SearchListItemContent> searchableList;
  FoodItemSearchDelegate(this.searchableList);
  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      /*IconButton(
        icon: Icon(Icons.search),
        onPressed: () {
          //orint("On press search action:")
          build(context);
          body.dele
        },
      ),*/
      IconButton(
        icon: Icon(Icons.clear),
        onPressed: () {
          query = "";
        },
      ),
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
          icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
      onPressed: () {
        close(context, null);
      },
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    Widget searchResult;
    if (query.length <= 2 && query.length > 0) {
      searchResult = Center(
          child: Text(
        "Type at least 3 character to perform a search.",
        style: TextStyle(color: Colors.red[800]),
      ));
    } else if (query.length == 0) {
      searchResult = searchResult = Center(
          child: Text(
        "Type something to search.",
        style: TextStyle(color: Colors.black),
      ));
    } else {
      List<Widget> resultSet = findMatch(context);
      if (resultSet.isEmpty) {
        searchResult = Center(
            child: Text(
          "We do not have what you are searching for!",
          style: TextStyle(color: Colors.red[800]),
        ));
      } else {
        searchResult = ListView(
          children: findMatch(context),
        );
      }
    }
    return searchResult;
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Text("");
  }

  List<Widget> findMatch(BuildContext context) {
    return this
        .searchableList
        .keys
        .where((item) {
          print("Item Key : " + item);
          print("Item in list : " + this.searchableList[item].toString());
          return (this
                  .searchableList[item]
                  .title
                  .toString()
                  .toLowerCase()
                  .contains(query) ||
              this
                  .searchableList[item]
                  .subTitle
                  .toString()
                  .toLowerCase()
                  .contains(query));
        })
        .toList()
        .map((item) {
          print("Selected Keys : " + item);
          return getSearchListItem(this.searchableList[item], context);
        })
        .toList();
  }

  Widget getSearchListItem(
      SearchListItemContent foodItem, BuildContext context) {
    print(foodItem);
    return Container(
      padding: EdgeInsets.all(8.0),
      decoration: BoxDecoration(
          color: Colors.white,
          border: Border(
            bottom: BorderSide(
                width: 1.0,
                color:
                    Provider.of<ThemeChanger>(context).getTheme.primaryColor),
          )),
      width: MediaQuery.of(context).size.width,
      child: getFoodItemTileForSearch(foodItem),
    );
  }

  ListTile getFoodItemTileForSearch(SearchListItemContent foodItem) {
    ListTile listTile;
    if (foodItem.subTitle != null) {
      listTile = ListTile(
        trailing: Text(foodItem.price),
        title: getFoodItemTitle(foodItem),
        subtitle: Text(foodItem.section + "\n" + foodItem.subTitle),
        isThreeLine: true,
      );
    } else {
      listTile = ListTile(
        trailing: Text(foodItem.price),
        title: getFoodItemTitle(foodItem),
        subtitle: Text(foodItem.section),
      );
    }
    return listTile;
  }

  Widget getFoodItemTitle(SearchListItemContent foodItem) {
    List<Widget> rowItems = [];
    if (foodItem.category != null) {
      foodItem.category.split(",").forEach((element) {
        switch (element) {
          case "0":
            rowItems.add(IconHelper.getFoodCategoryIcon("0"));
            break;
          case "1":
            rowItems.add(IconHelper.getFoodCategoryIcon("1"));
            break;
          case "2":
            rowItems.add(IconHelper.getFoodCategoryIcon("2"));
            break;
          case "3":
            rowItems.add(IconHelper.getFoodCategoryIcon("3"));
            break;
          case "4":
            rowItems.add(IconHelper.getFoodCategoryIcon("4"));
            break;
        }
      });
    }
    rowItems.add(Text(foodItem.title));
    return Row(children: rowItems);
  }
}`

**Comment by GZGavinZhao** [comment]
OK, honestly I'm having trouble following up your code (not you're fault sometimes I even have trouble understanding my own). Nevertheless, have you tried adding a `print()` statement right before or after  wherever that part is? Watch for the debug console and see if it's different for two platforms. If for both two platforms the debug console prints "WESTERN MAIN", then I assume there's probably a problem with your alignment or the container padding. But try this first and see what you get.

**Comment by AbhideepChakravarty** [comment]
That's a good idea. I will try that. Trust me sometimes even I get lost in
what is containing what. I brand new to flutter and brand new to frontend.

**Comment by darshankawar** [comment]
@AbhideepChakravarty 
Your question / issue is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

Closing, as this isn't an issue with Flutter itself. Also, since you are using firestore and if you think this is a genuine issue, please open this in Firebase dedicated issue tracking repo : https://github.com/FirebaseExtended/flutterfire/issues
If you disagree, please write in the comments and I will reopen it.
Thank you
