### ISSUE TITLE
Add ios/build/XCBuildData to .gitignore

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#74081]
as i mentioned in here https://github.com/flutter/flutter/issues/13892#issuecomment-761071708, `.gitignore` in `ios` folder for some reason doesn't include such entry
```
**/build
```
shouldn't this be ignored?

![image](https://user-images.githubusercontent.com/39104740/104785869-a3d39800-579c-11eb-9038-e19d6d65c8d1.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.19041.685], locale ru-RU)
    • Flutter version 1.24.0-8.0.pre.374 at c:\dev\src\flutter
    • Framework revision 183f0e797a (7 weeks ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64 • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86   • Android 11 (API 30) (emulator)

• No issues found!
```
</details>

**Comment by jmagman** [comment]
Flutter doesn't wrap any commands that should generate `ios/build/XCBuildData` so it's not `.gitignore`d.  Any chance you manually ran an `xcodebuild` command that did this?  You can try removing that directory, and notice what commands you ran if it ever reappears.

**Comment by nt4f04uNd** [comment]
@jmagman yes most definitely i did this, but why flutter runner `.gitignore` should be any different from default recommeded for any other ios project?

**Comment by jmagman** [comment]
> @jmagman yes most definitely i did this, but why flutter ios `.gitignore` should be any different from default recommeded for any other ios project?

Where is this recommended?  Flutter tooling sets the Xcode build directory in your top level project `build` directory.

**Comment by jmagman** [comment]
Also, what command did you run?  Or did you set your DerivedData relative to your project?  More details would be helpful.

**Comment by nt4f04uNd** [comment]
> Flutter tooling sets the Xcode build directory in your top level project `build` directory.

 i wasn't aware of this

> Where is this recommended

it's not recommeded by apple, but it's just in general git thing to `.gitignore` build folders and most of the ios projects do that, but i can understand to some extent why you did not ignore it, as it should not ever appear if you only use `flutter build ios`

> Also, what command did you run? Or did you set your DerivedData relative to your project? More details would be helpful

in one of my projects, i don't remember why in particular (it was 6 months ago), but i certainly did run it. i was trying to setup my macos flutter build, and tried running `xcodebuild`, something like that

weird thing is that in another project this `XCBuildData` folder appeared without me actually running this command, i have no clue why. even weirer that it's completely empty

**Comment by jmagman** [comment]
You are welcome to update your own `.gitignore` if this is part of your workflow--Flutter won't try to update it and won't care if there's unexpected strings in there.  

I'm going to close this for now since we generally only add `.gitignore` paths except files generated by
- `flutter` tool
- dependencies/wrapped commands
- common IDEs like IntelliJ or VS Code or Xcode

These aren't really hard or fast rules, it's generally whatever will make developer lives easier.  But the tool can't really predict generated files from commands run manually by the user.
