### ISSUE TITLE
Running 'flutter test' in multiple projects in parallel

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#7409]
I'm trying to run multiple `flutter test` commands in parallel to shorten down our presubmit test time, but I'm seeing this message:

    Waiting for another flutter command to release the startup lock...

at the beginning of every 'flutter test' execution except for the very first one. This makes me think that it is currently not possible to run multiple flutter commands in parallel, including `flutter test`.

Is there any real reason why multiple flutter tests cannot be run in parallel?
If not, could this restriction be relaxed?

**Comment by abarth** [comment]
You can bypass the `flutter` script and run the Dart command directly if you like.  The lock exists because the `flutter` command mutates `bin/cache` (e.g., to compile itself and to download artifacts).  If you know for some reason that it won't mutate that directory (e.g., because you've already run `flutter precache`), then you can probably get away with skipping the lock.

**Comment by abarth** [comment]
Keep in mind, though, that `flutter test` spawns as many subprocesses as you have CPU cores, so multiple `flutter test` in parallel might not actually be that much faster.  It depends how many test files you have per project.

**Comment by Hixie** [comment]
Does it hang at that point? I would have expected it to wait for the lock, then quickly get the lock, then quickly release the lock. Maybe `flutter test` isn't releasing the lock?

**Comment by yyoon** [comment]
Okay. I did some more thorough experiment by prepending timestamp in every line of stdout, and it turns out the average time it takes to get the lock from one thread is ~2sec, which is not a huge time loss.

Running `flutter test`s in parallel on my Macbook reduced the total test time from ~1m20s to ~0m58s. This is less significant than I originally expected, but understandable given that `flutter test` was already parallelizing tests to some extent. I'm closing this issue.

Thanks for the input!
