### ISSUE TITLE
crashlytics

### ISSUE THREAD

**Issue by AgarwalMilan** [flutter/flutter#74105]
I tried integrating Crashlytics following the [official guide](https://firebase.flutter.dev/docs/crashlytics/overview) and its working fine for Android but when I run the same for iOS it throwing the following build errors:

/ios/Pods/FirebaseCrashlytics/run: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by Abhishek01039** [comment]
Hello @AgarwalMilan 
can you please provide more details?
Thanks

**Comment by iapicca** [comment]
@AgarwalMilan 
[firebase](https://firebase.flutter.dev/)  is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by darshankawar** [comment]
Closing from here. @AgarwalMilan Please open this issue in Firebase repo as mentioned above.
