### ISSUE TITLE
How to off Tabstop of any widget

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#74108]
i have some icon buttons and i want to off tabstop on some buttons. how can i achieve this without disable buttons

**Comment by iapicca** [comment]
@abdulrehmananwar 
this issue seems more a question than a bug report or a feature request
if you need assistance with your code please follow the link I want help writing my application in the new issue menu

**Comment by abdulrehmananwar** [comment]
requesting a feature

**Comment by iapicca** [comment]
@abdulrehmananwar 
could you please provide the information listed in the [feature request template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) located in the [new issue selection](https://github.com/flutter/flutter/issues/new/choose)

```console

## Use case

<!--
     Please tell us the problem you are running into that led to you wanting
     a new feature.

     Is your feature request related to a problem? Please give a clear and
     concise description of what the problem is.

     Describe the alternative solutions you've considered. Is there a package
     on pub.dev/flutter that already solves this?
-->

## Proposal

<!--
     Briefly but precisely describe what you would like Flutter to be able to do.

     Consider attaching images showing what you are imagining.

     Does this have to be provided by Flutter directly, or can it be provided
     by a package on pub.dev/flutter? If so, maybe consider implementing and
     publishing such a package rather than filing a bug.
-->

```

**Comment by abdulrehmananwar** [comment]
> @abdulrehmananwar
> could you please provide the information listed in the [feature request template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) located in the [new issue selection](https://github.com/flutter/flutter/issues/new/choose)
> 
> ```
> ## Use case
> 
> 
> 
> ## Proposal
> 
> 
> ```

Sir i have already mentioned my requirement above. its very simple to understand. i just want to off tabstop against some widgets (like when i press tab key it bypass those widget focus which tabstop off)

**Comment by darshankawar** [comment]
@abdulrehmananwar 
If this is a feature request, we would appreciate if the issue details are presented in above mentioned format, that'll help us to better address it.

**Comment by abdulrehmananwar** [comment]
ok i have submited this as a new feature request thanks. now i am closing this from here.
