### ISSUE TITLE
Waiting for another flutter command to release the startup lock...

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#74101]
Waiting for another flutter command to release the startup lock...
i try it. clear. flutter/bin/cache lockfile
reboot android studio 
pls.help me

**Comment by Abhishek01039** [comment]
Please refer to this 
https://stackoverflow.com/questions/51679269/waiting-for-another-flutter-command-to-release-the-startup-lock

**Comment by chongbo2013** [comment]
hello, Executing:xxx/adb/macosx/x86_64/adb devices -l
flutter: ProcessException: Permission denied
how to set file chmod u+x ,pls help me.

**Comment by iapicca** [comment]
@chongbo2013 
I believe @Abhishek01039  pointed you in the right direction

but if  you believe this is a bug with flutter
please provide your `flutter doctor -v` and  your `flutter run -v`
