### ISSUE TITLE
Implement expandable search in AppBar

### ISSUE THREAD

**Issue by AlexeySemigradsky** [flutter/flutter#7411]
https://material.io/guidelines/patterns/search.html#search-in-app-search

**Comment by eseidelGoogle** [comment]
@HansMuller would have most context here.  I think there are several things there (like a padded/floating app-bar) which we don't yet have support for.

**Comment by p30arena** [comment]
I need this feature.

**Comment by ericmand** [comment]
#9783

**Comment by goderbauer** [comment]
This should be implemented in https://github.com/flutter/flutter/pull/17629 now. Please re-open if that's not capturing this.
