### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "$user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\async-2.5.0-nullsafety.3"[web]: <describe issue here>

### ISSUE THREAD

**Issue by rajenderkumar3088** [flutter/flutter#74118]
when ever i use webdev serve commnad i always get the above error. please help me.

**Comment by iapicca** [comment]
@rajenderkumar3088 
can you provide your `flutter doctor -v` and your full logs

**Comment by darshankawar** [comment]
@rajenderkumar3088 
Please provide above requested details to better address your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
