### ISSUE TITLE
Gradient colors parameter issue 

### ISSUE THREAD

**Issue by imssurya** [flutter/flutter#74116]
## Steps to Reproduce

1. LinearGradient(
                  colors: [Colors.black, Colors.red],
                  ),
## Logs

<colors parameter not accepting colors>
<summary>The named parameter 'colors' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'colors'</summary>

</details>
![image](https://user-images.githubusercontent.com/31724055/104812409-f4440780-5827-11eb-8791-1dfc449cc3dc.png)

**Comment by iapicca** [comment]
@imssurya 
it works fine for me

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

/// [https://api.flutter.dev/flutter/painting/LinearGradient-class.html#painting.LinearGradient.1]

void main() => runApp(
      MaterialApp(
        home: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [Colors.black, Colors.red],
              tileMode: TileMode.repeated,
            ),
          ),
        ),
      ),
    );

```

</details>

maybe your installation is `corrupted` 
you may want to try this [fix](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted)

**Comment by imssurya** [comment]
after restarting VScode solved for me and i am closing this issue
