### ISSUE TITLE
[web]: flutter run -d chrome not working 

### ISSUE THREAD

**Issue by NithinPremchand** [flutter/flutter#74115]
PS D:\Flutter Projects\Employee> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             73.0s
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

**Comment by iapicca** [comment]
@NithinPremchand 
can you provide your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment]
Hi @NithinPremchand 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/49482
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
