### ISSUE TITLE
Cross origin error for any request "Error: XMLHttpRequest error."

### ISSUE THREAD

**Issue by Jamalianpour** [flutter/flutter#74123]
hello,
I try to build an web application with flutter web but I got Cross origin error on any request on every website like Google.com.

this is my code:
```
Future<bool> getInfo() async {
  final response = await http.get('https://www.google.com');
  if (response.statusCode == 200) {
    return true;
  } else {
    return false;
  }
}
```

and this is error:
> Error: XMLHttpRequest error.
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28
> packages/http/src/browser_client.dart 84:2
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1446:54
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 150:18
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 703:44
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 732:32
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 526:7
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1302:7
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58
    at Object.createErrorWithStack (http://localhost:5296/dart_sdk.js:4375:12)
    at Object._rethrow (http://localhost:5296/dart_sdk.js:38296:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5296/dart_sdk.js:38290:13)
    at Object._microtaskLoop (http://localhost:5296/dart_sdk.js:38122:13)
    at _startMicrotaskLoop (http://localhost:5296/dart_sdk.js:38128:13)
    at http://localhost:5296/dart_sdk.js:33625:9

**Comment by darshankawar** [comment]
@Jamalianpour 
Sounds like this is a CORS issue. See [this](https://github.com/flutter/flutter/issues/32892#issuecomment-570045513) and [this](https://github.com/flutter/flutter/issues/32892#issuecomment-599346313) possible solution and check if it works.

**Comment by Jamalianpour** [comment]
@darshankawar 
I can not use them, because I try to use third party API and I don't have access to edit CORS policy. and they don't have any CORS problem.

**Comment by darshankawar** [comment]
I am getting same error while trying to run above code sample, but not sure if this is related to Flutter. Hence, keeping this issue open for further analysis.

```
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 84:22                                       <fn>
dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>


    at Object.createErrorWithStack (http://localhost:60916/dart_sdk.js:5325:12)
    at Object._rethrow (http://localhost:60916/dart_sdk.js:39283:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60916/dart_sdk.js:39277:13)
    at Object._microtaskLoop (http://localhost:60916/dart_sdk.js:39109:13)
    at _startMicrotaskLoop (http://localhost:60916/dart_sdk.js:39115:13)
    at http://localhost:60916/dart_sdk.js:34651:9


```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.402 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2a188eeca3 (10 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 87.0.4280.141

! Doctor found issues in 1 category.


```

</details>

**Comment by darshankawar** [comment]
Leaving these for reference here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

https://github.com/flutter/flutter/issues/32892#issuecomment-543838238

**Comment by Jamalianpour** [comment]
@darshankawar 
if you not sure this is related to Flutter, test other URL like this APIs:
`https://www.thesportsdb.com/api/v1/json/1/searchteams.php?t=Arsenal`
`http://ip-api.com/json/?fields=61439`
`http://apilayer.net/api/check`
I hope this issue will be fix soon.

**Comment by yjbanov** [comment]
There's nothing we can do on the Flutter side. This is a fundamental limitation on the Web. When sending HTTP requests (XHR) the server you are communicating with needs to allow it via a CORS handshake.

**Comment by Jamalianpour** [comment]
so in flutter web we can't use many of third party API.
and I should say I can use these APIs in react or razor and I don't understand why flutter can't do this.
