### ISSUE TITLE
Calling dispose on a video controller hangs if it failed to initialise 

### ISSUE THREAD

**Issue by febg11** [flutter/flutter#74121]
Hi

I am testing my error handling and think I have come across a bug. I am initialised a videoController with a bad path to get the initialise catch to fire. I am then trying to dispose of the controller and create a new one with a different video. However, when i call the await _videoController.dispose() after the initalisation error is thrown it just hangs. 

e.g. 

```
    _videoPlayerController = VideoPlayerController.file(File('aRandomPathThatDoesntExist'))
      ..initialize().then((_) {
        
        setState(() {});
      }).catchError((error) {
        print("error initialising the video");
        print(error);
        setState(() {
          hasInitialiseError = true;
        });
      });

     ... ElseWhere 

  Future<void> properlyDisposeOfVideoController(VideoPlayerController controller) async {
    if (controller != null) {
      print("Going to dispose of video controller");
      controller.removeListener(videoPlayerControllerListener);
      await controller.dispose();
      controller = null;
    }
  }

```

The code stops at await controller.dispose();... It is only doing this if the .catchError((error) {} on the initialize() is exectuted, otherwise it is working fine (e.g. if the video file was good) 

EDIT - I am using version video_player: 1.0.1

**Comment by febg11** [comment]
Removing the await fixed my problem but does it still mean the dispose is hanging, just in the background?

**Comment by darshankawar** [comment]
@febg11 
In order to better address this issue, can you provide `flutter doctor -v` , a minimal reproducible code sample and steps to replicate the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
