### ISSUE TITLE
The dart binary is not exported to the path when installed with snapcraft

### ISSUE THREAD

**Issue by adnan449** [flutter/flutter#74133]
## Steps to Reproduce

Install flutter-sdk with snap on Linux

## Issue

`which dart` will not see any dart binaries in the path

## Expected

The command should return the path to dart: `~/snap/flutter/common/flutter/bin/dart` to confirm it is indeed exported to $PATH

## Suggestion:

Add `~/snap/flutter/common/flutter/bin/dart` to path. I manually added it to `.bash_rc`

**Comment by iapicca** [comment]
@adnan449 
I'm not sure if yours is a `proposal` or a `bug report`, but I most certainly agree with the desirability of the feature
as I have encountered difficulties using dart from snap myself https://github.com/canonical/flutter-snap/issues/22

nevertheless issues regarding [snapcraft](https://snapcraft.io/flutter) package of flutter should be open in the dedicated [github](https://github.com/canonical/flutter-snap/issues )

**Comment by adnan449** [comment]
Thank you. Closing.
