### ISSUE TITLE
Add Comment

### ISSUE THREAD

**Issue by billdhar** [flutter/flutter#74144]
<p>In the <b>"Write Your First Flutter App, part 1"</b> Codelab on part 5, a comment is required to avoid confusion.</p>
<p>The code snippet <i>"Remove the word generation code from MyApp by making the changes below:"</i>, line 12 is changed from <b>"body: const Center("</b> to <b>"body: Center("</b>.</p>
<p>The removal of the <b>"const"</b> keyword is not indicated in the comments and it causes confusion if someone is not copying the code but typing it as it is relatively easy to miss.</p>
<p>A simple comment like <i>"// Remove const keyword"</i> at the end of line 12 will be very helpful.
<p>As a beginner at both Flutter and Dart it took me a couple of minutes to identify this issue and I believe that this change can help beginners not get stuck and will help them have a smoother and easier Flutter learning experience.</p>

<br><br>
<b>Original Code</b>
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final WordPair wordPair = WordPair.random();  // Delete this line.

    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          //child: Text(wordPair.asPascalCase), // Change this line to... 
          child: RandomWords(),                 // ... this line.
        ),
      ),
    );
  }
}
```
<br><br>
<b>Suggested Edit</b>
```
class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
      final WordPair wordPair = WordPair.random();  // Delete this line.
  
      return MaterialApp(
        title: 'Welcome to Flutter',
        home: Scaffold(
          appBar: AppBar(
            title: Text('Welcome to Flutter'),
          ),
          body: Center( // Remove const keyword
            //child: Text(wordPair.asPascalCase), // Change this line to... 
            child: RandomWords(),                 // ... this line.
          ),
        ),
      );
    }
  }
```

**Comment by roohaani786** [comment]
@billdhar  Flutter documentation tells us how to get started with it's resources, however it expects the user to have or take some prior programming knowledge before adding anything not suggested in the document. The idea of adding "//Remove const keyword" in itself is vague. Because a variable with the const keyword is initialized at compile-time and is already assigned when at runtime. You can't define const inside a class.
A const variable has to be declared within the class, but it cannot be defined in it. We need to define the const variable outside the class.

**Comment by darshankawar** [comment]
@billdhar 
Flutter codelab related issues are tracked here: https://github.com/flutter/website/issues. Please open issue there.
Closing from here.
