### ISSUE TITLE
Android devicelab agents are down, tests not running

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74142]
`mac/android` tests are not running since Jan 15.
<img width="1056" alt="Screen Shot 2021-01-16 at 9 43 41 PM" src="https://user-images.githubusercontent.com/682784/104832155-e7cda800-5843-11eb-823d-2bb85126a9d8.png">

**Comment by yusufm** [comment]
android-platform-tools is missing from the mac hosts. Adding it now

**Comment by godofredoc** [comment]
Phones need to manually trust the hosts, fuchsia foundation will go to the lab and press the buttons for us. After that we will need to land a few configurations. ETA for this to be resolved is today EOD.

**Comment by godofredoc** [comment]
Test beds were rebooted and they are back to normal.

**Comment by godofredoc** [comment]
Sorry closed the wrong bug accidentally.

**Comment by godofredoc** [comment]
Moving to P1 as mac_android tests are fully migrated to LUCI and will be blocking the tree in the new commits.

**Comment by godofredoc** [comment]
Work is complete and will monitor for a couple of hours before closing this bug.
