### ISSUE TITLE
Badly need SignalR support in Flutter

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#74140]
I've been working for a few months on a mobile app that requires chat messaging. The backend was developed in Asp.Net Core and utilizes SingalR transport. I tried a few packages on pub.dev and found that signalr_client 0.1.6 works the best of any other available there but still far from good. I had to include the package code into my app project in order to fix a few bugs but still, this is not the right solution. 
Due to this situation, my company started to consider the option of abandoning the whole project regardless they like my solution and everything else I've done like scheduling with appointment reminders, progress notes stored in a local, encrypted SQLite database, etc. They don't really care how I make SingalR work 100% reliable, they just want it done. You already have a package to work with a WebSocket server, you have this signalr_client package and I believe it should be a big deal for you to make something good and reliable.

**Comment by iapicca** [comment]
@misici234 
a `1st party` porting a `.net specific` library to flutter IMO isn't a realistic expectation

As there are at least two `3rd party` plugins available, namely
[signalr_core](https://pub.dev/packages/signalr_core) [[github](https://github.com/jamiewest/signalr_core/issues)] and [signalr_client](https://pub.dev/packages/signalr_client) [[github](https://github.com/soernt/signalr_client/issues)]
I recommend to address possible bug or missing feature in the respective github repo

alternatively you might want to take a look to this [stackoverflow answer](https://stackoverflow.com/a/50985178/9836706)

> If flutter plugins are not available for Signalr, you can always use native libraries available for signalr and use flutter's [platform channels](https://flutter.io/platform-channels/) to use those native features in your flutter code.
> Here are some helpful resource that might help
> [How to use signalr in Android?](https://stackoverflow.com/questions/32573823/how-to-use-signalr-in-android)
> [https://github.com/Gurgen/SignalR-.net-core-android-client](https://github.com/Gurgen/SignalR-.net-core-android-client)

**Comment by misici234** [comment]
@iapicca 
I tried all SignalR 3rd party plugins and none of them was reliable enough or didn't work at all. Specifically, the [signalr_client](https://pub.dev/packages/signalr_client) is abandoned plugin and [signalr_core](https://pub.dev/packages/signalr_core) didn't work for me at all.
To develop native libraries available for SignalR and use Flutter's platform channels is not the point of Flutter development. We don't want to write the same code twice. This can be a temporary solution until the Flutter team produce a permanent solution. There is a growing popularity for SignalR communication and it's high time Flutter provides official support for it.

**Comment by pedromassangocode** [comment]
Hi @misici234 
I don't think this is something the Flutter team want to address. Flutter team is already maintaining lots of plugins/packages and since the team is small in numbers it is difficult to maintain all those packages/plugins and Flutter itself. I would suggest you to open issues in the mentioned plugin repositories or fork them and make your own version of it.

**Comment by misici234** [comment]
Hi @pedromassangocode 
I don't agree with you. When I search flutter.dev by word SignalR I get the following [Work with WebSockets](https://flutter.dev/docs/cookbook/networking/web-sockets). Considering the growing popularity of SignalR it makes a lot of sense to add official support for it by the Flutter team. You mentioned that your team is small but I can tell you that I'm the only one developing in Flutter in my mid-size company where all other developers are C#, ASP.NET, in other words Microsoft technology. I managed to introduce Flutter and they were no so happy about it because their preference was Xamarin. Now, I'm in trouble. I told them I can do their mobile app in Flutter but it turned out that I can't because of SignalR. Please, reconsider your priorities and add SignalR in your recent TODO list.

**Comment by iapicca** [comment]
@misici234 
since [signalr_client](https://pub.dev/packages/signalr_client) is seamingly abbandoned
what about opeing an issue on [signalr_core](https://pub.dev/packages/signalr_core)'s [[github](https://github.com/jamiewest/signalr_core/issues)] and ask to implement the features you are expecting?

**Comment by misici234** [comment]
@iapicca 
I tested all of them on pub.dev and I couldn't even start a connection using the signalr_core plug-in. This is not about missing features but this is the issue about basic functionality that doesn't work and the plug-in is useless for me. Why don't Flitter team take over any of these plugins and just make them work reliably? This should not take too much time.

**Comment by iapicca** [comment]
@misici234 

> [...] Why don't Flitter team take over any of these plugins and just make them work reliably? This should not take too much time.

the team has a lot on its plate right now, personally I don't see why this should be a priority
it's like asking [aspnet](https://github.com/aspnet) team team to officially support a flutter plugin...
probably not their top priority

if you don't want anything to do with the current plugins, not even open an issue in their repo,
as mentioned [here](https://github.com/flutter/flutter/issues/74140#issuecomment-761749439), you can create a flutter plugin as follow
- implementing the [signalR android client](https://github.com/Gurgen/SignalR-.net-core-android-client) and/or [swift client](https://github.com/moozzyk/SignalR-Client-Swift) (please not that even those plugins aren't 1st party!)
- connect the native client to flutter with [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels)

**Comment by misici234** [comment]
@iapicca 
In that case, why does the Flutter team support WebSockets? (see [Work with WebSockets](https://flutter.dev/docs/cookbook/networking/web-sockets)). As you know, SignalrR supports 3 modes of transport: WS, SSE and LP. What has more value WS or WS, SSE and LP together?
I don't expect the team to provide a solution tomorrow but expect they do it in near future.

**Comment by muzammilsharief** [comment]
Hi, 

If you are looking for 100% Reliable messaging, then please check this video, here Brady says that do not use this SignalR when you need 100% reliability.

Hope it clears some thoughts.

**Comment by muzammilsharief** [comment]
Hi,

If you are looking for 100% Reliable messaging, then please check this video, https://youtu.be/YwezzKWrFuo here Brady says that do not use this SignalR when you need 100% reliability.

Hope it clears some thoughts.
