### ISSUE TITLE
Date range picker occupying the whole screen

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#74157]
I'm using on my flutter web project both the date picker and the date range picker widgets. The first one is rendered on a normal size, but the last gets full screen when opened. Is this a bug or i must open it in another way?

I read that there was a remake of the datepicker some months ago, but nothing about the rangedatepicker.

The code snippet that opens the picker:

```

MaterialButton(
  height: 62,
  shape: RoundedRectangleBorder(
      borderRadius:
          BorderRadius.circular(15.0),
      side:
          BorderSide(color: Colors.blueGrey)),
  child: Padding(
    padding: const EdgeInsets.fromLTRB(
        8, 10, 8, 10),
    child: Text(dateFormat2
            .format(_selectedRange.start) +
        " - " +
        dateFormat2
            .format(_selectedRange.end)),
  ),
  onPressed: () async {
    final picked = await showDateRangePicker(
        context: context,
        lastDate: _fimdate,
        firstDate: _iniciodate);
    if (picked != null &&
        picked != _selectedRange)
      setState(() {
        _selectedRange = picked;
      });
  }),
```

my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-2.0.pre.376, on Microsoft Windows [versÃ£o 10.0.19041.746], locale
    pt-BR)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed        
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by pedromassangocode** [comment]
Hi @Macacoazul01 
I think the docs says by itself. I can say that this is working as intended. If you are referring to this rework https://github.com/flutter/flutter/pull/70708, it was just a code restructure update and everything is supposed to work as before.

![Screen Shot 2021-01-18 at 11 31 31](https://user-images.githubusercontent.com/67424416/104903753-b9a1b280-5980-11eb-8818-bca087dc014c.png)

Thank you

**Comment by jonasbark** [comment]
@pedromassango is there somewhere we can read on the decision to make this full screen only? This looks very out of place on Web and Desktop size screens

**Comment by Macacoazul01** [comment]
@jonasbark thats why i opened this issue. It's strange to use the date picker as a full screen dialog on web/desk

**Comment by pedromassangocode** [comment]
> @pedromassango is there somewhere we can read on the decision to make this full screen only?

I'm not sure. cc @HansMuller

**Comment by manish-cashify** [comment]
@Macacoazul01  I was facing same problem, [https://stackoverflow.com/questions/65110888/flutter-make-showdaterangepicker-smaller](this could help you).
