### ISSUE TITLE
Make image loading synchronous

### ISSUE THREAD

**Issue by mregnauld** [flutter/flutter#74167]
## Use case

In my Flutter project, I use a `CustomPainter` to draw a customized shape in a widget, with icons in it.

The thing is, I need that widget to be drawn in the very first frame, to avoid any glitch when I open the page of my app containing that widget.

This is unfortunately a problem, because I need to draw the icons in that `CustomPainter`: the only way I've found so far to draw icons is to load them, then drawing them when available. I load them using the following:

```Dart
Future<ImageInfo> getImageInfo(String path, BuildContext context) async {
    AssetImage assetImage = AssetImage(path);
    ImageStream stream = assetImage.resolve(createLocalImageConfiguration(context));
    stream.addListener(ImageStreamListener((ImageInfo imageInfo, _) {
        return completer.complete(imageInfo);
    }));
    return completer.future;
}
```

and then use a `FutureBuilder` that contains the widget I want to draw.

Unfortunately, there is always a little glitch in the beggining.

That said, the only workaround I've found so far is to load all icons in my landing page and store them in a singleton. I don't know if it's a good practice though, especially since I need to load every icon just in case, without knowing in advance if I'll really need all of them.

## Proposal

The implementation in native Android is much simpler, and I would suggest to maybe do something simimar, in order to:

- make images loading much simpler
- make images loading synchronous, so we can draw them right away in a `CustomPainter` without glitch

maybe with something like this:

```Dart
ImageInfo imageInfo = loadAssetImage("/path/to/image.png");
```

**Comment by nt4f04uNd** [comment]
@mregnauld i'm not that much into the issue itself, but why do you draw icons as images and not a font?

**Comment by mregnauld** [comment]
@nt4f04uNd Because I need to draw a very customized menu with animations, and drawing the icons in the menu makes things much easier to me.

**Comment by pedromassangocode** [comment]
I'm not really sure if this is feasible since loading assets takes some time (and that is probably why the API was made asynchronous).

**Comment by nt4f04uNd** [comment]
> @nt4f04uNd Because I need to draw a very customized menu with animations, and drawing the icons in the menu makes things much easier to me.

@mregnauld this didn't answer what i asked, tho fyi you can use https://www.fluttericon.com/ and draw icons as font, like like flutter does for material or cupertino ones

**Comment by mregnauld** [comment]
@nt4f04uNd oh ok, I didn't know that, I'll try later on, thanks.

**Comment by Piinks** [comment]
@mregnauld did the suggestions above resolve your issue?
