### ISSUE TITLE
Macos Big Sur 11.1 Flutter install problem 

### ISSUE THREAD

**Issue by Gelistirix** [flutter/flutter#74166]
Hello there,
I want to install flutter on my system. When I do all the steps and run the sudo flutter doctor command, the cocoapods are constantly causing problems. I tried several times to install it with various tools but could not solve the problem.
```
`   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to
        invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.`
```

**Comment by Abhishek01039** [comment]
Hello @Gelistirix 
what is the output of `gem which cocoapods`?

**Comment by Gelistirix** [comment]
it is "gem which cocoapods" command output
`/Users/blackx/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods.rb`

**Comment by TahaTesser** [comment]
Hi @Gelistirix 
Can you please reinstall using `sudo gem install cocoapods` and try again
If the problem persists, please file a new issue on Cocoapods  dedicated [GitHub](https://github.com/CocoaPods/CocoaPods/issues)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Gelistirix** [comment]
Hello there,
Please don't turn this off. I also asked those on the cocoapods side of this problem, but they said it was related to Flutter.
As a result, although the cocoapods are loaded, the flutter doesn't see it.


gem which cocoapods
`/Users/blackx/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods.rb
`
sudo gem install cocoapods
`
Successfully installed cocoapods-core-1.10.1
Parsing documentation for cocoapods-core-1.10.1
Done installing documentation for cocoapods-core after 0 seconds
1 gem installed
`
sudo flutter doctor
`[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods`

**Comment by TahaTesser** [comment]
Hi @Gelistirix 
Can you reinstall cocoapods completely, check out steps [here](https://superuser.com/a/686319) and check the issue mentioned in the error itself https://github.com/flutter/flutter/issues/14293
Thank you

**Comment by Gelistirix** [comment]
Hi @TahaTesser 

I think I solved this way for now, I don't want to tamper with it yet.I'll wait a long time to get macos updates coming out from now on.
Getting new updates is not a good idea.

`blackx@Black-MacBook-Air ~ % sudo gem uninstall cocoapods
Remove executables:
	pod, sandbox-pod

in addition to the gem? [Yn]  y
Removing pod
Removing sandbox-pod
Successfully uninstalled cocoapods-1.10.1
Successfully uninstalled cocoapods-try-1.2.0
Successfully uninstalled cocoapods-trunk-1.5.0
Successfully uninstalled cocoapods-search-1.0.0
Successfully uninstalled cocoapods-plugins-1.0.0
Successfully uninstalled cocoapods-downloader-1.4.0
Successfully uninstalled cocoapods-deintegrate-1.0.4
Successfully uninstalled cocoapods-core-1.10.1
blackx@Black-MacBook-Air ~ % sudo gem install cocoapods -v 1.7.5
Fetching cocoapods-trunk-1.5.0.gem
Fetching cocoapods-search-1.0.0.gem
Fetching cocoapods-try-1.2.0.gem
Fetching cocoapods-stats-1.1.0.gem
Fetching cocoapods-plugins-1.0.0.gem
Fetching cocoapods-downloader-1.4.0.gem
Fetching cocoapods-deintegrate-1.0.4.gem
Fetching i18n-0.9.5.gem
Fetching cocoapods-1.7.5.gem
Fetching activesupport-4.2.11.3.gem
Fetching cocoapods-core-1.7.5.gem
Successfully installed cocoapods-try-1.2.0
Successfully installed cocoapods-trunk-1.5.0
Successfully installed cocoapods-stats-1.1.0
Successfully installed cocoapods-search-1.0.0
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-downloader-1.4.0
Successfully installed cocoapods-deintegrate-1.0.4
Successfully installed i18n-0.9.5
Successfully installed activesupport-4.2.11.3
Successfully installed cocoapods-core-1.7.5
Successfully installed cocoapods-1.7.5
Parsing documentation for cocoapods-try-1.2.0
Installing ri documentation for cocoapods-try-1.2.0
Parsing documentation for cocoapods-trunk-1.5.0
Installing ri documentation for cocoapods-trunk-1.5.0
Parsing documentation for cocoapods-stats-1.1.0
Installing ri documentation for cocoapods-stats-1.1.0
Parsing documentation for cocoapods-search-1.0.0
Installing ri documentation for cocoapods-search-1.0.0
Parsing documentation for cocoapods-plugins-1.0.0
Installing ri documentation for cocoapods-plugins-1.0.0
Parsing documentation for cocoapods-downloader-1.4.0
Installing ri documentation for cocoapods-downloader-1.4.0
Parsing documentation for cocoapods-deintegrate-1.0.4
Installing ri documentation for cocoapods-deintegrate-1.0.4
Parsing documentation for i18n-0.9.5
Installing ri documentation for i18n-0.9.5
Parsing documentation for activesupport-4.2.11.3
Installing ri documentation for activesupport-4.2.11.3
Parsing documentation for cocoapods-core-1.7.5
Installing ri documentation for cocoapods-core-1.7.5
Parsing documentation for cocoapods-1.7.5
Installing ri documentation for cocoapods-1.7.5
Done installing documentation for cocoapods-try, cocoapods-trunk, cocoapods-stats, cocoapods-search, cocoapods-plugins, cocoapods-downloader, cocoapods-deintegrate, i18n, activesupport, cocoapods-core, cocoapods after 4 seconds
11 gems installed
blackx@Black-MacBook-Air ~ % pod setup
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git --progress -- master
  Cloning into 'master'...
  remote: Enumerating objects: 628, done.        
  remote: Counting objects: 100% (628/628), done.        
  remote: Compressing objects: 100% (559/559), done.        
  remote: Total 4639997 (delta 245), reused 117 (delta 41), pack-reused 4639369        
  Receiving objects: 100% (4639997/4639997), 820.06 MiB | 1.61 MiB/s, done.
  Resolving deltas: 100% (2915479/2915479), done.
  Updating files: 100% (471390/471390), done.
  warning: the following paths have collided (e.g. case-sensitive paths
  on a case-insensitive filesystem) and only one from the same
  colliding group is in the working tree:
  
    'Specs/5/1/1/Governor/1.0.11-APPS-1582-beta11/Governor.podspec.json'
    'Specs/5/1/1/Governor/1.0.11-apps-1582-beta11/Governor.podspec.json'

CocoaPods 1.10.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.1

Setup completed
blackx@Black-MacBook-Air ~ % which flutter                      
/Users/blackx/development/flutter/bin/flutter
blackx@Black-MacBook-Air ~ % sudo chmod -R a+rwx /Users/blackx/development/flutter 
Password:
blackx@Black-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale tr-TR)
    • Flutter version 1.22.5 at /Users/blackx/development/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/blackx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/blackx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

**Comment by uday1201** [comment]
I used these packages 

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/uupreti/sos/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/uupreti/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.8.0

**Comment by ShivangiPathak2001** [comment]
![Uploading Screenshot 2021-05-22 at 1.56.57 AM.png…]()
