### ISSUE TITLE
marked as '@immutable', but one or more of its instance fields aren't final

### ISSUE THREAD

**Issue by mealinux** [flutter/flutter#74169]
i got this error (page bar.dart);
![New Project](https://user-images.githubusercontent.com/10341948/104855472-086a3080-591e-11eb-8149-f5c426155a0e.png)

//main.dart
```
import 'package:flutter/material.dart';
import 'bar/bar.dart';
import 'body/body.dart';

void main() =>
    runApp(MaterialApp(home: Scaffold(appBar: BarState(), body: BodyState())));
```

//bar.dart
```
import 'package:flutter/material.dart';
import '../bottomSheet/bottomSheet.dart';

class BarState extends StatefulWidget implements PreferredSizeWidget {
  BarState({
    Key key,
    this.visible,
  }) : super(key: key);

  bool visible = true;

  @override
  Size get preferredSize => const Size.fromHeight(50);

  @override
  Bar createState() => Bar();
}

class Bar extends State<BarState> {
  void iniState() {
    super.initState();
    widget.visible = true;
  }

  @override
  Widget build(BuildContext context) {
    return AppBar(
      title: Text('To Do List'),
      actions: <Widget>[
        Visibility(
          child: IconButton(
            icon: Icon(Icons.add),
            tooltip: 'Add a TO DO',
            onPressed: () => {
              displayBottomSheet(context),
              setState(
                () => {widget.visible = false},
              )
            },
          ),
          visible: widget.visible,
        ),
      ],
    );
  }
}

```

**Comment by iapicca** [comment]
@mealinux 
it's not a bug with flutter,
you can declare only finals in `StatefulWidget`
just an error with your code


```diff
class BarState extends StatefulWidget implements PreferredSizeWidget {
  BarState({
    Key key,
    this.visible,
  }) : super(key: key);

- bool visible = true;

  @override
  Size get preferredSize => const Size.fromHeight(50);

  @override
  Bar createState() => Bar();
}

class Bar extends State<BarState> {
+ var _visible = true
  void iniState() {
    super.initState();
-   widget.visible = true;
  }

  @override
  Widget build(BuildContext context) {
    return AppBar(
      title: Text('To Do List'),
      actions: <Widget>[
        Visibility(
          child: IconButton(
            icon: Icon(Icons.add),
            tooltip: 'Add a TO DO',
            onPressed: () => {
              displayBottomSheet(context),
              setState(
-              () => {widget.visible = false},
+              () => _visible = !_visible
              )
            },
          ),
-        visible: widget.visible,
+        visible: _visible,
        ),
      ],
    );
  }
}
```

**Comment by mealinux** [comment]
> @mealinux
> it's not a bug with flutter,
> you can declare only finals in `StatefulWidget`
> just an error with your code
> 
> ```diff
> class BarState extends StatefulWidget implements PreferredSizeWidget {
>   BarState({
>     Key key,
>     this.visible,
>   }) : super(key: key);
> 
> - bool visible = true;
> 
>   @override
>   Size get preferredSize => const Size.fromHeight(50);
> 
>   @override
>   Bar createState() => Bar();
> }
> 
> class Bar extends State<BarState> {
> + var _visible = true
>   void iniState() {
>     super.initState();
> -   widget.visible = true;
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return AppBar(
>       title: Text('To Do List'),
>       actions: <Widget>[
>         Visibility(
>           child: IconButton(
>             icon: Icon(Icons.add),
>             tooltip: 'Add a TO DO',
>             onPressed: () => {
>               displayBottomSheet(context),
>               setState(
> -              () => {widget.visible = false},
> +              () => _visible = !_visible
>               )
>             },
>           ),
> -        visible: widget.visible,
> +        visible: _visible,
>         ),
>       ],
>     );
>   }
> }
> ```

okay, i want to get parameter from out inside class Bar, how will i do? because when i define as final in BarState i got this error

![asdasdasdasdasd](https://user-images.githubusercontent.com/10341948/104904674-7a7c5d00-5992-11eb-89f3-7380611d81e2.png)

**Comment by iapicca** [comment]
@mealinux 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
