### ISSUE TITLE
Get each function call of my code in a stacktrace

### ISSUE THREAD

**Issue by mregnauld** [flutter/flutter#74162]
## Use case

When I test my Flutter app, I sometimes got errors and a stacktrace in the console.

But even if I heavily use `assert()` in all my widgets constructors, I still get quite often stacktraces that are hard to read, since I sometimes don't know where the error occurs in my code (happends quite often actually, which is really annoying).

## Proposal

That would be great (and I'm actually surprised it's not the case already) if, in every stacktrace, we can get the stack of each call that leads to the error, **_including each call in our code_** and not only the SDK code, as it is in Java and Kotlin, for example.

That would definitely help a lot.

**Comment by pedromassangocode** [comment]
Hi @mregnauld 
Can you please provide a code sample that produces a confused stacktrace alog with your `flutter doctor -v`?
Thank you

**Comment by mregnauld** [comment]
@pedromassangocode My bad, I don't manage to reproduce the problem.
I'll close that thread and reopen it if it occurs again.
