### ISSUE TITLE
Hot reload in profile and release mode

### ISSUE THREAD

**Issue by mregnauld** [flutter/flutter#74160]
## Use case

My Flutter app heavily relies on animations, so I need a fast way to test them.

## Proposal

Would it be possible to provide hot reload / hot restart not only in debug mode, but also in profile and release mode?

**Comment by pedromassangocode** [comment]
Hi @mregnauld 
I don't think this is possible. You can test your app in Debug mode or write unit/integration tests to test your implementations.

**Comment by mregnauld** [comment]
@pedromassangocode Why wouldn't it be possible? I'm curious.
Also, yeah, I know that I can test in debug mode, but it's pretty useless when it comes to testing animations.
And I don't see the point of unit test if you want to quickly test animations while you're programming them.

**Comment by nt4f04uNd** [comment]
@mregnauld fyi on emulator debug mode gives you a pretty good performance so it's easy to test animations there
