### ISSUE TITLE
[local_auth] For Android 10 Face Id never been asked for Authentication 

### ISSUE THREAD

**Issue by Purvik** [flutter/flutter#74194]
As per note in package information, if we're targeting Android Q and lower than we should directly go for Authentication instead of checking available biometrics. I did same using latest version package  and tested for two different devices, Samsung Galaxy M20 & Oneplus 6 where Face Id is registered in the system. 

Also for an update I did check permission for Android where an update that I got is permission `USE_FINGERPRINT` is deprecated in API 28 and instead of that we need to use `USE_BIOMETRIC` further. Does this has to do something with it or it's working for other devices or some users?

**Comment by TahaTesser** [comment]
Hi @Purvik 
`USE_BIOMETRIC` didn't help, still asks for a Fingerprint 
I see there's an open issue addressing the case you described.https://github.com/flutter/flutter/issues/45775
Please follow up on that issue, I'm closing the current one as a duplicate. 
If you disagree, please write in the comments and I will reopen it.
Thank you
