### ISSUE TITLE
Update startup_namer codelab for upcoming Flutter relase

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#74208]
From [failing CI run](https://github.com/flutter/codelabs/pull/49/checks?check_run_id=1724535915#step:7:101):

```
Your application code is in startup_namer/step1_base/lib/main.dart.

+ flutter analyze
Analyzing step1_base...                                         

  error • Target of URI doesn't exist: 'package:integration_test/integration_test.dart' • integration_test/app_test.dart:10:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:step1_base/main.dart' • integration_test/app_test.dart:12:8 • uri_does_not_exist
  error • The function 'run' isn't defined • integration_test/app_test.dart:14:16 • undefined_function
  error • Target of URI doesn't exist: 'package:integration_test/integration_test_driver.dart' • integration_test/driver.dart:6:8 • uri_does_not_exist
  error • The function 'integrationDriver' isn't defined • integration_test/driver.dart:8:24 • undefined_function
```

**Comment by filiph** [comment]
Looks like someone ran `flutter create .` in here, which creates the `integration_test` directory and the example files in it. Is it CI that does this?

**Comment by filiph** [comment]
(Sent too soon.) We need to figure out if we want to build integration tests for each of our codelabs, or whether to delete (not create) the `integration_test` directory. What do you think, @domesticmouse?

**Comment by domesticmouse** [comment]
My plan is to go through the codelabs (and samples) to get them to work on both stable and beta. I hope that adding `integration_test` directories to all the projects is enough. We will see. =)

**Comment by filiph** [comment]
I thought it's the opposite. If we add `integration_test` with the default contents to each sample, then that's going to break, because the default `integration_test/*.dart` files are referencing non-existent `lib/` files.

Or is it that `beta` _requires_ the directory to exist?

**Comment by domesticmouse** [comment]
I haven't looked closely, but if memory serves the CI script runs `flutter create .` in each project before running the test suite. Flutter beta and newer create the integration test, and thus CI on beta and dev channels require said integration tests to be declared, even if only as no-ops. IIUC.
