### ISSUE TITLE
Running flutter clean results in Target of URI doesn't exist everywhere

### ISSUE THREAD

**Issue by hanabon** [flutter/flutter#74218]
## Steps to Reproduce

Run `flutter clean`

Then my entire project has this issue:
`Target of URI doesn't exist`,

even 'Target of URI doesn't exist: 'package:flutter/material.dart'.`

I can sometimes get it to work by running `flutter pub get` and then restarting vscode. But what changed that could be causing this?

<details>
  
`flutter doctor -v` output:

[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.26.0-8.0.pre at /Users/katzheng/Development/flutter
    • Framework revision b9d06fffb2 (11 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/katzheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/katzheng/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/katzheng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1
```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @hanabon 
Every time you run `flutter clean` Flutter will delete some temporary files/directories which are required by the IDE to compile your project so it is required to run `flutter pub get` so that Flutter will re-create then again.

I'm closing this for now since there is no sign of Flutter issue here.
Thank you
