### ISSUE TITLE
App doesn't repaint when resizing on Linux before first interaction

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#74211]
STEPS TO REPRODUCE:
1. `flutter create dummy_desktop`
2. `cd dummy_desktop`
3. `flutter run -d linux`
4. Split your window, or resize your pane, or some such, BEFORE interacting with the app in any way (including e.g. hovering over the floating action button).

ACTUAL RESULTS: The window doesn't repaint ever again. You can tell, by shrinking the window so small that it causes a RenderFlex overflow, that the layout _is_ still happening; we're just not putting any pixels on the screen.

EXPECTED RESULTS: The window should repaint when resized.

I tested this with ratpoison and fvwm2.

**Comment by cbracken** [comment]
@robert-ancell @wmww any thoughts on what might be going on here?

**Comment by wmww** [comment]
No idea, and I can't repro. Tried the current tip of main on Sway/Wayland, Sway/XWayland, GNOME/Wayland, GNOME/XWayland and i3 (X11)

**Comment by dnfield** [comment]
When trying to resize a window on `Debian 5.17.11-1rodete2`, the window becomes unusable - I cannot even resize it anymore and have to restart the application.

**Comment by dnfield** [comment]
This is using X11 GNOME

**Comment by wmww** [comment]
I was briefly seeing Flutter open unresponsive and with no window contents on i3, but after switching desktops and switching back it worked again. Also worked after a reboot. Unclear what was up with that. Now that I know it's intermittent I'll investigate more closely next time I see it.

**Comment by cbracken** [comment]
@Hixie I'm curious if this still repros for you at tip-of-tree on `master` branch? 

Wondering if https://github.com/flutter/engine/pull/35272 may have resolved both this issue and the issue it was targeting.

**Comment by dnfield** [comment]
This is no longer reproducing for me.

**Comment by Hixie** [comment]
Seems fixed. Thanks!
