### ISSUE TITLE
Disable `flutter_service_worker.js` file for web projects

### ISSUE THREAD

**Issue by p554157atch** [flutter/flutter#74223]
Not all web projects require service worker. eg Chrome and Firefox extensions, electron apps etc.

In such situations it is best to disable the default `flutter_service_worker.js` file.

For example Chrome, Firefox extensions require their own specialized service worker like scripts called background scripts.

Such scripts currently can't be generated using the `flutter build web` command, so an option must be added to generate custom scripts that act as service worker scripts, I have opened a separate issue for this FR:
https://github.com/flutter/flutter/issues/74221

An option to disable `flutter_service_worker.js` to `flutter build web` will be great.

**Comment by jonahwilliams** [comment]
@p554157atch 

```
jonahwilliams-macbookpro2% flutter build web -h
Build a web application bundle.

[...]

    --pwa-strategy                   The caching strategy to be used by the PWA service worker.
                                     offline-first will attempt to cache the app shell eagerly and then lazily cache all subsequent assets as they are loaded. When making a network request for an asset,
                                     the offline cache will be preferred.
                                     none will generate a service worker with no body. This is useful for local testing or in cases where the service worker caching functionality is not desirable
                                     [offline-first (default), none]

Run "flutter help" to see global options.
```

**Comment by p554157atch** [comment]
I ran following command:

```bash
flutter build web -t lib/main.dart --pwa-strategy=none
```

After that `flutter_service_worker.js` is created but this file has no content.

This is acceptable solution for me but I would still like to run `rm flutter_service_worker.js`.

Feel free to close this issue.
