### ISSUE TITLE
Dependence problem

### ISSUE THREAD

**Issue by Luffys6** [flutter/flutter#74229]
![image](https://user-images.githubusercontent.com/21170493/105010952-52b2f500-5a77-11eb-977b-e3c15cef3299.png)
![image](https://user-images.githubusercontent.com/21170493/105011102-7ece7600-5a77-11eb-9801-d80a6f0bd74f.png)

**Comment by Luffys6** [comment]
Plugin version is the latest

**Comment by darshankawar** [comment]
@Luffys6 
Please provide complete `flutter doctor -v`, `pubspec.yaml` and the error log using `flutter run --verbose` in formatted text instead of screenshots.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
