### ISSUE TITLE
Clean My Ram

### ISSUE THREAD

**Issue by Fanqish** [flutter/flutter#74230]
I See That After Building My Own App That There Are Processes Related To The Build Which I Do not Need Any More 
And Every Time I Had To Remove That Processes By My Self
It Not A Problem For People Who Has A Lot Of Ram 
But It Is A Problem For Me
Thanks For Listeng. Awesome Flutter Team

**Comment by darshankawar** [comment]
@Fanqish 
Can you elaborate on the issue ? What are the processes that are being built for your app that you've to remove them ? Is your app facing memory leak which might be consuming too much space / ram ?

Also, what would you like Flutter team to do on this ? Do you have a use case and proposal on how it could help you ?

**Comment by iapicca** [comment]
@darshankawar 
I don't know if that's the exact case,
but I also noticed after running some `pub` related command on `ubuntu 20.04`
that even after shutting down the process `bpytop` shows a **lot** of ram still in use
until rebooted, if this is the case it's probably a dart problem

I have no idea how to repro this

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
