### ISSUE TITLE
why flutter pub get checks example/pubspec.yaml

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#74234]
I want to create some simple packages with an example without `example/pubspec.yaml`,
The structure looks like this:
```
├── analysis_options.yaml
├── CHANGELOG.md
├── example
│   └── pkg1_example.dart
├── lib
│   ├── pkg1.dart
│   └── src
├── pubspec.lock
├── pubspec.yaml
├── README.md
└── test
    └── pkg1_test.dart
```
And `pkg1/pubspec.yaml` contains:
```
dependencies:
  flutter:
    sdk: flutter
```
And when I run `flutter pub get`:
```
Could not find a file named "pubspec.yaml" in "/.../pkg1/example".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/.../pkg1/example".)
```
But `dart pub get` works fine.
Is this error on purpose when I don't need a `pubspec.yaml` in the example folder?

**Comment by darshankawar** [comment]
@aliyazdi75 
Usually having `example` folder is a best practice while developing any package. The `example` folder will contain, as the name suggest, a runnable code sample that devs can use, while a one level up contains the core code for the plugin.
The `pubspec.yaml` is checked for specifications of the plugin, accordingly the listed plugins are installed.

**Comment by aliyazdi75** [comment]
@darshankawar
Yes, that's correct but my `example` doesn't need a `pubspec.yaml` and I want to show how to use some core methods in the `example` folder. Actually, I'm using https://github.com/dart-lang/stagehand and generate many simple packages in my app, and the examples don't need a `pubspec.yaml`.

**Comment by darshankawar** [comment]
@aliyazdi75 
I am not much aware of the `stagehand` dart generator. May be this issue should be asked in that repo itself ?

**Comment by aliyazdi75** [comment]
@darshankawar 
I am not sure. The `flutter pub get` makes the problem by checking the example folder `pubspec.yaml` existence. I think it shouldn't do that or makes a warning, not an error. I don't know what is the difference but `dart pub get` works fine.

**Comment by darshankawar** [comment]
@aliyazdi75 
I think the reason `dart pub get` works fine is because it doesn't seem to run inside `example/` folder. Check this open issue https://github.com/dart-lang/pub/issues/2831

Anyways, I am labeling this for further analysis.

**Comment by aliyazdi75** [comment]
@darshankawar 
So it is necessary to have an empty `pubspec.yaml` inside the `example` folder?

**Comment by aliyazdi75** [comment]
Hi, @darshankawar 
I tried this issue with the latest flutter and I think this issue has been fixed, Am I right?

**Comment by darshankawar** [comment]
@aliyazdi75 
Thanks for getting back. I didn't get a chance to verify that, but if you can confirm it that it's fixed, you may go ahead and close this.

**Comment by aliyazdi75** [comment]
@darshankawar 
Ok, thanks.
