### ISSUE TITLE
Whenever I do any change in pubspec.yaml there was an error on edited line and it does not ask for get dependencies.

### ISSUE THREAD

**Issue by rajput-abdullah** [flutter/flutter#74231]
Working dir: C:\Users\apex\AndroidStudioProjects\net_ninja
C:\usr\flutter\bin\cache\dart-sdk\bin\pub.bat get
Error on line 45, column 4 of pubspec.yaml: Expected a key while parsing a block mapping.
   â•·
45 â”‚    assets:
   â”‚    ^
   â•µ

**Comment by darshankawar** [comment]
@rajput-abdullah 
It seems your `pubspec.yaml` is not aligned properly with required indentation. You may checkout following links to see if they help to resolve your issue.

https://medium.com/@tashpemhiwa/expected-a-key-while-parsing-a-block-mapping-5512965dafca
https://www.xspdf.com/resolution/50171766.html

Closing this, as it isn't an issue with Flutter. This question is better suited for StackOver flow. If you disagree, write in comments and I'll reopen it.
