### ISSUE TITLE
Check FingerPrint has enabled

### ISSUE THREAD

**Issue by maheshmaersk** [flutter/flutter#74237]
Hi Team,
There are some android phones without fingerprint or faceID Enabled how to check those 
i see no methods for that and its needed mandatorly please do the needful

**Comment by ManuLpz4** [comment]
In https://pub.dev/packages/local_auth:

> To check whether there is local authentication available on this device or not, call canCheckBiometrics:
> ```
> bool canCheckBiometrics = await localAuth.canCheckBiometrics;
> ```

**Comment by darshankawar** [comment]
@maheshmaersk 
Check above comment and see if it answers your question.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by maheshmaersk** [comment]
Hi @pedromassangocode  See this is the use case 
Now in xiomi Mobiles Finger print is not necessary Or many android phones fingerprint is not mandatory

Now what details i had required is if there are fingerprints which are registered like devices would be having one or 2 fingerprints commonly Can you try to build an option for that 


Second is If fingerprint is rejected is there any way can u navigate to system default Pin
