### ISSUE TITLE
No devices found with name or id matching. Apple M1 Mac and real device. Happens frequently

### ISSUE THREAD

**Issue by dgurudot** [flutter/flutter#74244]
## Steps to Reproduce
1. Connect iPhone device to Macbook M1 laptop.
2. It will show up on the device list but when installing, we get an error.

**Expected results:** 
Able to install on the real device on Apple M1 Mac and using latest Android Studio.

It works sometimes but doesn't work a lot of time.

**Actual results:** 

1. Searched internet and past suggestions but nothing helped so far.
2. When I reboot laptop, then it works for a little while but starts to happen again.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.22.5 at /Users/vmacair/development/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vmacair/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! Error: Errors were encountered while preparing your device for development. Please check the Devices and Simulators Window.  (code -1)

! Doctor found issues in 1 category.
```

**Comment by markusaksli-nc** [comment]
Hi @dgurudot 
Is there anything relevant logged to `flutter run -v` or the device console?
Is there anything useful in `Devices and Simulators`?
I'm not seeing this with our M1.
Thank you

**Comment by dgurudot** [comment]
I am finding the following error while running "flutter run -v". I checked
that my device is using latest iOS 14.3 and Xcode is latest version 12.3

============================================================================================================================

                    2021-01-22 08:19:25.707 xcdevice[51186:6970077]
 DTDeviceKit: Failed to mount DDI from

'<DVTFilePath:0x11170d210:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.3/Develop
                    erDiskImage.dmg'>', error=-402653066: Error
Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for
                    development."
UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage,
NSUnderlyingError=0x12a894d90 {Error
                    Domain=com.apple.dt.MobileDeviceErrorDomain
Code=-402653066 "Could not support development."
                    UserInfo={MobileDeviceErrorCode=(0xE8000076),
com.apple.dtdevicekit.stacktrace=(
                        0   DTDeviceKitBase
0x00000001044612f8 DTDKCreateNSErrorFromAMDErrorCode + 272
                        1   DTDeviceKitBase
0x000000010449ad84 -[DTDKMobileDeviceToken
_mountDeveloperDiskImage:withError:] +
                        916
                        2   DTDeviceKitBase
0x000000010449b76c __58-[DTDKMobileDeviceToken
                        mountDeveloperDiskImageWithError:]_block_invoke +
556
                        3   libdispatch.dylib
0x000000018b298420 _dispatch_client_callout + 20
                        4   libdispatch.dylib
0x000000018b2a6a98 _dispatch_lane_barrier_sync_invoke_and_complete + 60
                        5   DTDeviceKitBase
0x000000010449b4d8 -[DTDKMobileDeviceToken
mountDeveloperDiskImageWithError:] + 168
                        6   IDEiOSSupportCore
0x00000001186d7dc8 __37-[DVTiOSDevice(Connect) hasConnected]_block_invoke_2
+ 272
                        7   DVTFoundation
0x0000000105976730 __DVT_CALLING_CLIENT_BLOCK__ + 16
                        8   DVTFoundation
0x000000010597b3a4 __DVTDispatchGroupAsync_block_invoke + 680
                        9   libdispatch.dylib
0x000000018b2968bc _dispatch_call_block_and_release + 32
                        10  libdispatch.dylib
0x000000018b298420 _dispatch_client_callout + 20
                        11  libdispatch.dylib
0x000000018b29b82c _dispatch_continuation_pop + 560
                        12  libdispatch.dylib
0x000000018b29aec4 _dispatch_async_redirect_invoke + 592
                        13  libdispatch.dylib
0x000000018b2a8fac _dispatch_root_queue_drain + 356
                        14  libdispatch.dylib
0x000000018b2a97a4 _dispatch_worker_thread2 + 116
                        15  libsystem_pthread.dylib
0x000000018b441024 _pthread_wqthread + 216
                        16  libsystem_pthread.dylib
0x000000018b43fd94 start_wqthread + 8
                    ), DVTRadarComponentKey=261622,
NSLocalizedDescription=Could not support development.}},
NSLocalizedRecoverySuggestion=If
                    you are certain that Xcode supports development on this
device, try disconnecting and reconnecting the device.,
                    NSLocalizedFailure=This operation can fail if the
version of the OS on the device is newer than the version of Xcode that is
                    running., DVTRadarComponentKey=487927,
NSLocalizedDescription=Failed to prepare device for development.}
                    2021-01-22 08:19:25.707 xcdevice[51186:6970077]
 iPhoneConnect: 📱<DVTiOSDevice (0x119686660), VIPhone, iPhone, 14.3
                    (18C66), 71abd87bd654537024591e3131cb4fd1ade326c6>
unable to mount developer disk image, (Error Domain=com.apple.dtdevicekit
                    Code=806 "Failed to prepare device for development."
UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage,
                    NSUnderlyingError=0x12a894d90 {Error
Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653066 "Could not
support
                    development."
UserInfo={MobileDeviceErrorCode=(0xE8000076),
com.apple.dtdevicekit.stacktrace=(
                        0   DTDeviceKitBase
0x00000001044612f8 DTDKCreateNSErrorFromAMDErrorCode + 272
                        1   DTDeviceKitBase
0x000000010449ad84 -[DTDKMobileDeviceToken
_mountDeveloperDiskImage:withError:] +
                        916
                        2   DTDeviceKitBase
0x000000010449b76c __58-[DTDKMobileDeviceToken
                        mountDeveloperDiskImageWithError:]_block_invoke +
556
                        3   libdispatch.dylib
0x000000018b298420 _dispatch_client_callout + 20
                        4   libdispatch.dylib
0x000000018b2a6a98 _dispatch_lane_barrier_sync_invoke_and_complete + 60
                        5   DTDeviceKitBase
0x000000010449b4d8 -[DTDKMobileDeviceToken
mountDeveloperDiskImageWithError:] + 168
                        6   IDEiOSSupportCore
0x00000001186d7dc8 __37-[DVTiOSDevice(Connect) hasConnected]_block_invoke_2
+ 272
                        7   DVTFoundation
0x0000000105976730 __DVT_CALLING_CLIENT_BLOCK__ + 16
                        8   DVTFoundation
0x000000010597b3a4 __DVTDispatchGroupAsync_block_invoke + 680
                        9   libdispatch.dylib
0x000000018b2968bc _dispatch_call_block_and_release + 32
                        10  libdispatch.dylib
0x000000018b298420 _dispatch_client_callout + 20
                        11  libdispatch.dylib
0x000000018b29b82c _dispatch_continuation_pop + 560
                        12  libdispatch.dylib
0x000000018b29aec4 _dispatch_async_redirect_invoke + 592
                        13  libdispatch.dylib
0x000000018b2a8fac _dispatch_root_queue_drain + 356
                        14  libdispatch.dylib
0x000000018b2a97a4 _dispatch_worker_thread2 + 116
                        15  libsystem_pthread.dylib
0x000000018b441024 _pthread_wqthread + 216
                        16  libsystem_pthread.dylib
0x000000018b43fd94 start_wqthread + 8
                    ), DVTRadarComponentKey=261622,
NSLocalizedDescription=Could not support development.}},
NSLocalizedRecoverySuggestion=If
                    you are certain that Xcode supports development on this
device, try disconnecting and reconnecting the device.,
                    NSLocalizedFailure=This operation can fail if the
version of the OS on the device is newer than the version of Xcode that is
                    running., DVTRadarComponentKey=487927,
NSLocalizedDescription=Failed to prepare device for development.}) {
                        AssociatedMobileDeviceFunction = AMDeviceMountImage;
                        DVTRadarComponentKey = 487927;
                        NSLocalizedDescription = "Failed to prepare device
for development.";
                        NSLocalizedFailure = "This operation can fail if
the version of the OS on the device is newer than the version of Xcode
                        that is running.";
                        NSLocalizedRecoverySuggestion = "If you are certain
that Xcode supports development on this device, try disconnecting
                        and reconnecting the device.";
                        NSUnderlyingError = "Error
Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653066 \"Could not
support
                        development.\"
UserInfo={MobileDeviceErrorCode=(0xE8000076),
com.apple.dtdevicekit.stacktrace=(\n\t0   DTDeviceKitBase
                        0x00000001044612f8
DTDKCreateNSErrorFromAMDErrorCode + 272\n\t1   DTDeviceKitBase
        0x000000010449ad84
                        -[DTDKMobileDeviceToken
_mountDeveloperDiskImage:withError:] + 916\n\t2   DTDeviceKitBase
                        0x000000010449b76c __58-[DTDKMobileDeviceToken
mountDeveloperDiskImageWithError:]_block_invoke + 556\n\t3
                        libdispatch.dylib
0x000000018b298420 _dispatch_client_callout + 20\n\t4   libdispatch.dylib
                        0x000000018b2a6a98
_dispatch_lane_barrier_sync_invoke_and_complete + 60\n\t5   DTDeviceKitBase
                        0x000000010449b4d8 -[DTDKMobileDeviceToken
mountDeveloperDiskImageWithError:] + 168\n\t6   IDEiOSSupportCore
                        0x00000001186d7dc8 __37-[DVTiOSDevice(Connect)
hasConnected]_block_invoke_2 + 272\n\t7   DVTFoundation
                        0x0000000105976730 __DVT_CALLING_CLIENT_BLOCK__ +
16\n\t8   DVTFoundation                       0x000000010597b3a4
                        __DVTDispatchGroupAsync_block_invoke + 680\n\t9
libdispatch.dylib                   0x000000018b2968bc
                        _dispatch_call_block_and_release + 32\n\t10
 libdispatch.dylib                   0x000000018b298420
                        _dispatch_client_callout + 20\n\t11
 libdispatch.dylib                   0x000000018b29b82c
_dispatch_continuation_pop +
                        560\n\t12  libdispatch.dylib
0x000000018b29aec4 _dispatch_async_redirect_invoke + 592\n\t13
                        libdispatch.dylib
0x000000018b2a8fac _dispatch_root_queue_drain + 356\n\t14  libdispatch.dylib
                        0x000000018b2a97a4 _dispatch_worker_thread2 +
116\n\t15  libsystem_pthread.dylib             0x000000018b441024
                        _pthread_wqthread + 216\n\t16
 libsystem_pthread.dylib             0x000000018b43fd94 start_wqthread +
8\n),
                        DVTRadarComponentKey=261622,
NSLocalizedDescription=Could not support development.}";
                    }
                    2021-01-22 08:19:25.708 xcdevice[51186:6969905] [MT]
iPhoneConnect: 📱<DVTiOSDevice (0x119686660), VIPhone, iPhone, 14.3
                    (18C66), 71abd87bd654537024591e3131cb4fd1ade326c6> --
An error occurred whilst preparing device for development -- Failed to
                    prepare device for development.
                    Domain: com.apple.dtdevicekit
                    Code: 806
                    Recovery Suggestion: If you are certain that Xcode
supports development on this device, try disconnecting and reconnecting
                    the device.
                    User Info: {
                        AssociatedMobileDeviceFunction = AMDeviceMountImage;
                        DVTRadarComponentKey = 487927;
                        NSLocalizedFailure = "This operation can fail if
the version of the OS on the device is newer than the version of Xcode
                        that is running.";
                    }

**Comment by dgurudot** [comment]
If I reboot the laptop then everything works perfectly fine.

I am puzzled if something or another app is creating conflict here

**Comment by markusaksli-nc** [comment]
In any case this doesn't seem like an issue with flutter, but rather the apple development environment. You could try submitting this to https://feedbackassistant.apple.com/ or the Xcode forums but for now it seems like this isn't the place for the issue so I'm going to close it.

If this does turn out to be an issue with flutter just let me know and I will reopen.

**Comment by dgurudot** [comment]
Just wanted to add an update that latest android studio update and flutter upgrade automatically fixed this issue.
