### ISSUE TITLE
Execution failed for task ':thumbnails:verifyReleaseResources'.

### ISSUE THREAD

**Issue by rehamalraee** [flutter/flutter#74240]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':thumbnails:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\Users\ThinkPad\.gradle\caches\transforms-2\files-2.1\031dc452fd8fe95433a5948018abd92f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
     C:\Users\ThinkPad\.gradle\caches\transforms-2\files-2.1\031dc452fd8fe95433a5948018abd92f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resourceandroid:attr/ttcIndex not found.

**Comment by TahaTesser** [comment]
Hi @rehamalraee 
This is an issue with your Gradle cache, please[ delete your existing Gradle cache](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) and run the app again 

If the problem persists, Can you please provide your `flutter doctor -v` with upgrade and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by rehamalraee** [comment]
@TahaTesser  Hi, I got this 
` 
Note: C:\Users\ThinkPad\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\thumbnails-1.0.1\android\src\main\java\com\asapjay\thumbnails\ThumbnailsPlugin.java us
es or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
`

**Comment by TahaTesser** [comment]
Hi @rehamalraee 
That's just a deprecated API warning, not an error. 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
