### ISSUE TITLE
Update flutter.dev/desktop docs

### ISSUE THREAD

**Issue by csells** [flutter/flutter#74250]

**Comment by domesticmouse** [comment]
I'm trying to write up how to distribute a macOS Desktop Flutter app following Apple's [Signing Your Apps for Gatekeeper docs](https://developer.apple.com/developer-id/). However, the app fails to run once hardened runtime is enabled: https://github.com/flutter/flutter/issues/75825

**Comment by cbracken** [comment]
Closing since we believe everything for this was completed for beta 2.

**Comment by samuel-cavalcanti** [comment]
![image](https://user-images.githubusercontent.com/24573157/135278632-1ac02727-095d-4360-8615-4ce6d461f5b8.png)

![image](https://user-images.githubusercontent.com/24573157/135277922-daafb06e-2cd9-4c6f-868d-a50a62fef708.png)

maybe __x64__ is missing
