### ISSUE TITLE
[google_maps_flutter_web] Migrate to google_maps-5.x

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#74261]
Currently `google_maps_flutter` depends on `google_maps-3`.

Version `4.0.0` of `google_maps` now relies only on `package:js` and extensions methods and several tests need to be rewritten.

/cc @ditman

**Comment by ditman** [comment]
@a14n should I wait for v5.0.0 with Null Safety, or do I get started on this one? :)

**Comment by a14n** [comment]
I will try to work on a Null Safety version but I think I will basically make everything nullable because there is nothing in the documentation of Google Maps JS to decide what should be non-nullable or not. So you shouldn't see a lot of change with a 5.x if you start migrating to 4.x today

**Comment by ditman** [comment]
Yeah, I couldn't find any info about nullability in the Maps Docs. We'll hide the nullability behind the API of the plugin :)

**Comment by a14n** [comment]
I just released the `5.0.0` version of `google_maps` with the null-safety migration (making everything nullable :-/)

**Comment by ditman** [comment]
Wooow, big change with the removal of the MapTypeStyleFeatureType and other enums. I [deleted a bunch of lines of code](https://github.com/ditman/plugins/commit/a02aadb7d147dbf187d1426370a8043ac1be0afd#diff-ad093591ababe86bff6ff2af9ce718a9b0ef32f011611922b7d245420c71cb27L118-L191) converting from String to the appropriate values!

**Comment by ditman** [comment]
@a14n btw I found a source of nullability information for the google_maps library, but I'm not sure that it can be automatically imported.

In the docs, GMaps documents how to use the SDK with Typescript: https://developers.google.com/maps/documentation/javascript/using-typescript

And they link to the definitely typed repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google.maps

In the index.d.ts there you can see (for example) that Circle.getDraggable [can't be null](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google.maps/index.d.ts#L67), or that Map.getCenter [can be null](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google.maps/index.d.ts#L3016)

_(In fact many things can be null, as expected from a JS lib)_

Anyway, this might help being more strict with the types, maybe by parsing this file and deciding on the nullability of a type/field just by seeing if it's `| undefined` or `| null` (?).

(This is probably more work than what it's worth)

**Comment by a14n** [comment]
> In the index.d.ts there you can see (for example) that Circle.getDraggable can't be null

In a js console `new google.maps.Circle().getDraggable()` returns `undefined` so it's really strange that the description file has `boolean` as retrun type!

**Comment by ditman** [comment]
> In a js console new google.maps.Circle().getDraggable() returns undefined so it's really strange that the description file has boolean as return type!

@a14n LOL so much for the typescript definition :/
