### ISSUE TITLE
please create flutter.googlesource.com/third_party/libxml

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#74279]
Part of https://github.com/flutter/flutter/issues/39532

@godofredoc

**Comment by godofredoc** [comment]
We will also need the source repo for the initial import if we want to keep history

**Comment by godofredoc** [comment]
Done:

https://flutter-review.googlesource.com/admin/repos/third_party/libxml

**Comment by dnfield** [comment]
Thanks! I lost track of finding a good source for you, but we can always fix the history if we need to.
