### ISSUE TITLE
We've got no logs but "Lost connection to device" when plugin crash on iOS.

### ISSUE THREAD

**Issue by Elvis5566** [flutter/flutter#74319]
Flutter app crash without any logs if it's from native error.
on android, we'll get PlatformException.
Since app crash immediately, there is no way to pass exception to crashlytics.

Please help
Thank you

## Steps to Reproduce

1. Create new flutter app from android studio.
2. use a plugin that has error.
3. Observe that there is no logs but "Lost connection to device" on console.

**Expected results:** 
We should get PlatformException that indicate what native crash is.

**Actual results:** 
there is no logs but "Lost connection to device" on console.

<details>
  <summary>Logs</summary>

```

Launching lib/main.dart on Elvis’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8NKXDSKES7
Running Xcode build...
 └─Compiling, linking and signing...                         3.3s
Xcode build done.                                            7.4s
Installing and launching...                                        13.9s
Waiting for Elvis’s iPhone to report its views...                    5ms
Syncing files to device Elvis’s iPhone...                          125ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Elvis’s iPhone is available at: http://localhost:63990

```

</details>

**Comment by darshankawar** [comment]
@Elvis5566 
Can you elaborate on when you say `Flutter app crash without any logs if it's from native error.` ?
Also, in order to better address this issue, please provide a complete minimal reproducible code sample along with `flutter doctor -v` that we can use to verify this crash. 
Also, from your log, it seems you are trying to run app in release mode, correct ? :

```
Running Xcode build...
 └─Compiling, linking and signing...                         3.3s
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
