### ISSUE TITLE
Option+Backspace and Cmd+Backspace does not work on EditableText fields on MacOS

### ISSUE THREAD

**Issue by gkpln3** [flutter/flutter#74316]
## Steps to Reproduce

Flutter desktop for MacOS:
1. Run `flutter create bug`.
2. Update the files as follows: 
main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: EditableText(
          controller: TextEditingController(),
          focusNode: FocusNode(),
          style: TextStyle(),
          cursorColor: Colors.black,
          backgroundCursorColor: Colors.white,
        ),
      ),
    );
  }
}
```
3. Enter some text into the `EditableText` field.
4. Try deleting a whole word using "Option+Backspace" or deleting the whole sentence by using "Cmd+Backspace".

**Expected results:** Option+Backspace should delete one word backwards; Cmd+Backspace should delete backwards till the start of the line.

**Actual results:** Cmd+Backspace does not delete anything, Option+Backspace deletes just one character.

**Comment by stuartmorgan** [comment]
@justinmc Do we have a central issue tracking this kind of thing?

**Comment by justinmc** [comment]
I think this one: https://github.com/flutter/flutter/issues/30725

I'll go ahead and close this and we can keep discussion over there.  I'll make a comment about cmd/option+backspace specifically.
