### ISSUE TITLE
Discussion about possibilities to integrate WebGPU as external backing of a Texture Widget

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#74318]
Hi, 

after a short exchange on Discord @iskakaushik and I agreed to continuse the discussion here in an issue. 

Here is what we talked so far:

> Hi,
> 
> after receiving my email, Eric and Hixie told me I should ask you here:
> 
> Some friends and I started a new plugin project with the goal to allow Flutter developers getting access to the full power of the GPU. 
> Meaning to be able to draw the Content of a TextureWidget by accessing the GPU directly.
> Actually I need this for my Client, so he supports that effort.
> After posting on this on Twitter I got a lot of positiv feedback of people longing for the option to do 3D inside Flutter.
> 
> As OpenGL is deprecated in the Mac and iOS we decided to give the upcoming WebGPU standard a try as it abstracts the different backend technologies Vulkan, Windows and Metal to one unified API.
> 
> https://gpuweb.github.io/gpuweb/
> 
> Besides that this will be integrated in all Browsers there are two native implementations, one in Rust and one vom Google in C++ called Dawn which is also used inside Chrome.
> 
> https://dawn.googlesource.com/dawn/
> 
> The two Dawn Delelopers (GitHub handles senorblanco kainino0x) also told me that there is already a Skia backend for Dawn, so maybe this could be interesting for Flutter in the long run. 
> 
> After creating FFI bindings for the Rust web_gpu implementation we are now facing a problem we didn’t expect that way. We wanted to use the  Texture Widget to connect to the Web_GPU but it seems from what I understood that it only can work with OpenGL Texture IDs. Although I wonder how this works on iOS and Android with Skia Metal.
> 
> Would it be possible to have a short Zoom Call with people of your team that know this area well to discuss if there is any chance in our Approach? Possibly together with one of the Dawn team?
> Or isn't there any chance to solve this?
> 
> 

and @iskakaushik reply:

_

> @escamoteur , It might be useful for you to take a look at how external textures are currently being supported, for example on iOS, FlutterEngine acts as a FlutterTextureRegistry:
> 
> If using the Metal backend, callers go through: registerTexture: as seen here in the video_player plugin (https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L486). This then finally invokes: IOSExternalTextureMetal (https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/ios_external_texture_metal.mm#L16).  FlutterEngine gives you an id, that you can presumably use as the textureId in the Texture widget.
> 
> If you are using the OpenGL backend, embedding does it exactly as above and finally goes to IOSExternalTextureGL. This again gives you a corresponding textureId.
> 
> I wasn’t able to find any documentation in regards to WebGPU interop with existing rendering backends, other than an open issue: https://github.com/gpuweb/gpuweb/issues/18. In the absence of this, for each platform where you wish to support WebGPU, you will need to do the following:
> 
> You will first need to add embedder support for rendering using WebGPU, might not be that difficult given Skia support for Dawn. At least the equivalent of IOSExternalTextureMetal::Paint. 
> Add external texture support for the same. This is what gives you a textureId.
> 
> Hope this answers your questions. Chinmay maybe able to add more.

Maybe the easiest way would be if someone from the Engine team could check with  @senorblanco and @kainino0x from the Dawn team how we could access rendered Textures inside Dawn from the Flutter Engine.

If we get some guidance @jpnurmi and I can probably work on needed PRs to make this possible.

thanks a lot for your time.

**Comment by kainino0x** [comment]
Interoperability with native APIs is outside of the scope of the W3C community group (gpuweb), which only concerns the Web. For native development there's a relevant organization here: https://github.com/webgpu-native

Dawn doesn't have an easy way to grab internal textures (although it's likely possible if you do the appropriate casts to dawn_native types and gram the Metal texture handle from inside). However, we do have a way to import external IOSurfaces into Dawn as textures. This is how we import canvas swap chain textures from Chrome into Dawn for rendering. Maybe it will help.
https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/metal/MetalBackend.mm;l=34;drc=0b29732cd84f7cfcf39eb90efabdb2c895c5d4b9

**Comment by escamoteur** [comment]
@kainino0x so there is no way to access an plaform independent way to access an internal Texture/Surface? 
To clarify Terminology, a Dawn Texture is where Dawn can draw on? I'm a bit confused because in some contexts surface and in others Texture is used.

**Comment by kainino0x** [comment]
Texture in WebGPU/Dawn is any memory resource that may have a non-linear layout, including textures used as render targets (have RENDER_ATTACHMENT usage, may come from the swap chain), textures used as resources (have SAMPLED usage), and so on.

Accessing the Vulkan/D3D12/Metal resource underlying a Dawn texture is fundamentally platform dependent as they give you platform-dependent object types.

Surfaces in Dawn/webgpu.h are for creating platform-specific windows/surfaces and getting swap chains from them. I'm not sure exactly what you're trying to achieve but they may be useful.

**Comment by escamoteur** [comment]
Thanks a lot for your time @kainino0x and all others investing time thinking on this.

I dug a bit more into the API of  web_gpu and compared it to OpenGL. IMHO Rendering with webgu is way more difficult.
It may have some benefits compared to OpenGL but I don't see that this will be needed inside  a Flutter App.
As we are already using OpenGL in Flutter I hope this will make the connection to Texture widgets also easier.
Also as Simon pointed out, there is a ton of WebGL examples/turtorials out there.
If I had known about MetalAngle I probably wouldn't got into WebGpu at all.
So my I will go forward on the OpenGL path where we already have a full ffi binding thanks to @kentcb  work. I will create a new repo soon and add what we already have.

I will close this issue now. @iskakaushik I probably open a new one to ask more specific questions on what will be the best way to register surfaces ;-)
