### ISSUE TITLE
report functional problems with this 'removeItem' function with class 'SliverAnimatedList' 

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#74317]
Can the child actually be destroyed after the ‘’FadeTransition' animation ends? Because of this My video was immediately destroyed.This is not what I expected to happen.

**Comment by TahaTesser** [comment]
HI @ModWU 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by ModWU** [comment]
Can the child actually be destroyed after the ‘’FadeTransition' animation ends? Because of this My video was immediately destroyed.This is not what I expected to happen.

> 
> 
> HI @ModWU
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

Can the child actually be destroyed after the ‘’FadeTransition' animation ends? Because of this My video was immediately destroyed.This is not what I expected to happen.

**Comment by ModWU** [comment]
> 
> 
> Can the child actually be destroyed after the ‘’FadeTransition' animation ends? Because of this My video was immediately destroyed.This is not what I expected to happen.
> 
> > HI @ModWU
> > Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> > Thank you
> 
> Can the child actually be destroyed after the ‘’FadeTransition' animation ends? Because of this My video was immediately destroyed.This is not what I expected to happen.

Sorry, problem solved

**Comment by TahaTesser** [comment]
@ModWU 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by ModWU** [comment]
Thank you! Please close it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Taha Tesser"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午3:54
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "．．猪．．"<985477819@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] report functional problems with this &#39;removeItem&#39; function with class &#39;SliverAnimatedList&#39;  (#74317)





 
@ModWU
 Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
 Thank you
