### ISSUE TITLE
Support for selection of multiple directories, through desktop's native open panel, in 'file_selector' package

### ISSUE THREAD

**Issue by shrey112710** [flutter/flutter#74323]
Since the `file_chooser` package has been superseded by the `file_selector` package so it makes more sense to use the latter than the previous one, however, `file_selector` does not allow the selection of multiple directories like how `file_chooser` used to allow. Until now our company's application was relying solely on the `file_chooser` package for selecting and adding multiple files and multiple directories, of the desktop, so as to later upload and send them to the desired person using the desktop's native open panel. Therefore, It would be nice to have that functionality to be included in the 'file_selector' package as well.

**Comment by geotro** [comment]
Dear flutter friends, the world still needs this feature! Would be great to have it with the next release.

**Comment by geotro** [comment]
Really hoping for this to make it into the next flutter release! :)

**Comment by stuartmorgan** [comment]
@geotro Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs
