### ISSUE TITLE
flutter initialization

### ISSUE THREAD

**Issue by mehranshoqi** [flutter/flutter#74339]
![Screenshot from 2021-01-20 13-20-59](https://user-images.githubusercontent.com/65711096/105217900-7717db80-5b22-11eb-864d-3999d5884b7f.png)

Hello everyone,

when i write < flutter > in terminal on ubuntu for initialize flutter sdk, it return some error: 

```bash
Initializing Flutter
Downloading https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.5-stable.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    342      0 --:--:-- --:--:-- --:--:--   342
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Flutter initialization failed
Could not find working copy of Flutter
```

i dont know what is really happend!!

**Comment by TahaTesser** [comment]
Hi @mehranshoqi 
Which flutter version you've installed and what method you used to install it? `snapd` or `git clone`? 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
