### ISSUE TITLE
[canvaskit]: fix and test paragraph height/textHeightBehavior

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#74337]
I wrote a test for text styles in https://github.com/flutter/engine/pull/23800 and noticed that setting `height` or `textHeightBehavior` in the paragraph style has no effect (`height` works when we on `CkTextStyle`).

**Comment by hterkelsen** [comment]
https://github.com/flutter/engine/pull/25659 fixed the `height` issue.

The `textHeightBehavior` issue requires a fix on the CanvasKit end. I filed an issue here: https://bugs.chromium.org/p/skia/issues/detail?id=11881
