### ISSUE TITLE
flutter_immediately_exit_test is flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#74361]
https://ci.chromium.org/p/flutter/builders/prod/Linux%20tool_tests

This could be related to the devtools update. 

Skipping it here: https://github.com/flutter/flutter/pull/74359

/cc @jonahwilliams @kenzieschmoll @jmagman

**Comment by jmagman** [comment]
Do we think we can re-enable this @jonahwilliams @kenzieschmoll?

**Comment by christopherfujino** [comment]
Looks like this test was deleted
