### ISSUE TITLE
Unnecessary reference to unsound null safety

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#74366]
When rebuilding the Flutter tool, Flutter prints an informational message to the console that the tool is compiled with unsound null safety. This is unnecessary friction, since it seems like a warning to the developer, but they can't do anything about it. We should mute this message (e.g. by passing a `--silent` flag). 

```
$ flutter upgrade
Upgrading Flutter to 1.26.0-2.0.pre.442 from 1.26.0-2.0.pre.440 in /Users/timsneath/flutter...
Building flutter tool...
Info: Compiling with unsound null safety

Upgrading engine...

Flutter 1.26.0-2.0.pre.442 • channel master • git@github.com:flutter/flutter.git
Framework • revision 97481e125a (16 minutes ago) • 2021-01-20 17:44:02 -0600
Engine • revision 0c79393dde
Tools • Dart 2.12.0 (build 2.12.0-240.0.dev)

etc.
```

**Comment by zanderso** [comment]
This message is coming from Dart compiling the tool. I think there's already a companion issue filed for this in Dart. I'll close this since it isn't actionable.

**Comment by timsneath** [comment]
Per offline conversation, I think the expectation is that Dart needs to add a `--silent` flag, but that there's still actionable work on the Flutter side to call it.

**Comment by zanderso** [comment]
Is there an issue we can link this to to see when the `--silent` flag has landed?

**Comment by timsneath** [comment]
Yeah -- it's the Dart one above: https://github.com/dart-lang/sdk/issues/44727

**Comment by mit-mit** [comment]
@zanderso it looks like flutter [is using](https://github.com/flutter/flutter/blob/master/bin/internal/shared.sh#L154) the snapshot option for building the flutter tool. You can now combine that with the verbosity flag; this is working in current Dart master, so we just need a roll:

```console
$ dart --snapshot=foo hello.dart
Info: Compiling with sound null safety

$ ~/sdk/master/dart-sdk/bin/dart --verbosity=warning --snapshot=foo hello.dart
$
```

**Comment by zanderso** [comment]
The engine roll with this change is here: https://github.com/flutter/flutter/pull/74726
