### ISSUE TITLE
`flutter analyze` can break down when host and target sdk versions differ

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#7437]
Consider the following case:

1. Flutter engine is linked against Dart VM at https://github.com/dart-lang/sdk/commit/554c3c9683264ab9840a2c2371942b5a9f5e1fae
2. The tools SDK version is set to `1.21.0`
3. In Flutter Tools, we implement the [`Process`](https://api.dartlang.org/stable/1.20.1/dart-io/Process-class.html) interface.  As part of this implementation, we override `set exitCode`
4. https://github.com/dart-lang/sdk/commit/e5a16b1ca56414af3008afb8833660f95a9d06da is submitted in SDK 1.22.  It makes `Process.exitCode` immutable to fix https://github.com/dart-lang/sdk/issues/27950
5. The tools SDK version is updated to `1.22.0-dev.5.0`, which picks up https://github.com/dart-lang/sdk/commit/e5a16b1ca56414af3008afb8833660f95a9d06da
6. The analyzer in the IDE complains that `set exitCode` is not defined in `Process`, so the `@override` annotations are incorrect.
7. We remove the `@override` annotations, and send a PR
8. Travis kicks off its validation, which includes running `flutter analyze --flutter-repo`

Now, at this point, the target Dart SDK defines `set exitCode`, and the host Dart SDK does not.  `flutter analyze --flutter-repo` will make one giant project that includes all the code, and it analyzes that against the *target SDK version* (necessarily because some code uses `dart:ui`).  Since the target SDK version has the older `Process` API, `flutter analyze` yields analysis failures, and Travis checks fail.

We may want to consider making `flutter analyze` break apart the code into distinct projects -- those which requires host analysis vs target analysis.

**Comment by Hixie** [comment]
Removing the non-analyzer-server analysis code path has been on the cards for a while, but it's blocked mainly on the server being slower right now.

**Comment by tvolkert** [comment]
One option would be build a stock Dart SDK at the version in the DEPS file of the engine and publish that to Cloud storage, then download it from there as opposed to dartlang.org -- that would ensure that our tools sdk and flutter embedder SDK are always in sync.

**Comment by tvolkert** [comment]
This is obsolete nowadays.
