### ISSUE TITLE
Some flutter libraries have unnecessary import directives

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#74381]
## Details

1.  Please tell us exactly how to reproduce the problem you are running into, and how you measured the performance.

   1. Build a Dart SDK which can detect unnecessary imports. Use https://dart-review.googlesource.com/c/sdk/+/177221.
   2. Analyze Flutter sources.
   3. Witness many files which contain import directives whose used elements are provided by another import directive.

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

No thank you.

3.  Switch flutter to master channel and run this app on a physical device
     using profile or release mode. Verify that the performance issue can be
     reproduced there.

n/a

**Target Platform:** any
**Target OS version/browser:** any
**Devices:** any

## Logs

n/a

**Comment by Enigma04** [comment]
Is this still an issue? If so I'd like to solve it

**Comment by srawlins** [comment]
I think there are still a few lingering libraries which have unnecessary imports, but they're hard to detect today; I am using a local branch of Dart where I enable the analyzer to detect such code.

If you're inspired though, there is a similar issue which the Flutter developers may appreciate visibility into. There are some files in this repo with imports like this:

```dart
import 'dart:io';
// ...
import 'package:file/file.dart';

File f ...
```

Each of these two imported libraries provide a class named `File`, so which one is referenced in the library? It turns out there is a little-known rule in the language specification which says that any non-system (non-`dart:`) import elements shadow any would-be colliding system (`dart:`) imports, so the `File` from `package:file` wins. However, I'm fairly certain most developers would like this made explicit. That is, I think a change to `hide File` in the `dart:io` import would be an improvement. I think this goes for `Directory` as well.

**Comment by nt4f04uNd** [comment]
@srawlins this might be unrelated, but i always wondered - if we have a single file to import `package:app/app.dart` that export all files that we potentially might need, and we import it in any place of our project, does it affect on something? like speed of compilation, speed of analyzer, whatever?
