### ISSUE TITLE
[URLlauncher] get URL

### ISSUE THREAD

**Issue by hossam-zaki** [flutter/flutter#74384]
## Use case

The User opens the browser and does certain tasks, but then clicks done, and we on the backend want to capture the URL

## Proposal

I would like flutter to capture the URL the user is on when they press "done" on the browser. Let me know if this is a thing. Thanks for your help!

**Comment by pedromassangocode** [comment]
Hi @hossam-zaki 
Can you please elaborate what where is the "done" button? Does it exists on Chrome?

Please elaborate more about your proposal.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
