### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by shashiben** [flutter/flutter#74387]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.448, on Linux, locale en_IN.utf8)
    • Flutter version 1.26.0-2.0.pre.448 at /home/shashi/snap/flutter/common/flutter
    • Framework revision eeb7c261f2 (4 hours ago), 2021-01-20 23:04:03 -0500
    • Engine revision dde6b7e8ea
    • Dart version 2.12.0 (build 2.12.0-246.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/shashi/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[!] Android Studio
    • Android Studio at /home/shashi/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 87.0.4280.141 Arch Linux

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 6e5f55fb59245fcb8147a5d572a2d7e43a70d46e
### Plugins
cloud_firestore-0.16.0
cloud_firestore_web-0.3.0+1
firebase_auth-0.20.0+1
firebase_auth_web-0.3.2+6
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_storage-7.0.0
firebase_storage_web-0.1.1+3
image_picker_web_redux-1.1.3
picker-1.0.6

**Comment by pedromassangocode** [comment]
@shashiben  
There's similar open issue, affecting linux platforms, https://github.com/flutter/flutter/issues/72522.
Please follow-up on that issue for more updates.
Thank you

**Comment by iapicca** [comment]
this is a `snap` installation issue, follow up [here](https://github.com/canonical/flutter-snap/issues/23)
