### ISSUE TITLE
package:flutter/src/widgets/basic.dart': Failed assertion: line 7170 pos 15: 'builder != null': is not true.

### ISSUE THREAD

**Issue by sovan-7** [flutter/flutter#74390]

**Comment by TahaTesser** [comment]
Hi @sovan-7 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by sovan-7** [comment]
10.0.17134.1304

**Comment by sovan-7** [comment]
The relevant error causing widget was materialapp
when the exception was thrown this was the stack
#builder

**Comment by TahaTesser** [comment]
Hi @sovan-7 
To better address the issue, can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
