### ISSUE TITLE
Flutter occasionally locks up on Pixel C

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7440]

**Comment by eseidelGoogle** [comment]
I think we might need a bit more info to debug. :)  Is this reproducible?

**Comment by sethladd** [comment]
The designers were also talking about this.

**Comment by sethladd** [comment]
cc @bkobash has a pixel c we can borrow. He saw hard crashes.

**Comment by eseidelGoogle** [comment]
@chinmaygarde also has a pixel C on his desk.

**Comment by chinmaygarde** [comment]
@jason-simmons thinks the fix for https://github.com/flutter/flutter/issues/7431 which was applied in  https://github.com/flutter/engine/pull/3339 addresses this issue as well. Please re-open if you still see this issue. By locks up, we are assuming it never resumes rendering.
