### ISSUE TITLE
I want to know how to set cookie for the webview before the h5 loaded?

### ISSUE THREAD

**Issue by lanmch** [flutter/flutter#74406]
I want to know how to set cookie for the webview before the h5 loaded?

i try to excused js(document.cookie='xxxx') in the PageFinished function, but it seems that the cookie just take effect when the h5 has loaded. 
Then i set the 'header' property, but it just set cookie to the page url, rather than the http request(cgi) in the h5.
Then i found a solution, i try to use a package named webview_flutter_cookie( sorry i might forget the correct name), but it just can be used on IOS 11+, but my project is for IOS 9+, so the xcode throw the error.

Now, i dont know how to solve this problem, i really want to know if i can set the cookie to the h5 before it loaded, or the flutter cant make it.
I really need your help. Expecting your reply.

**Comment by darshankawar** [comment]
@lanmch 
Your question is better suited for StackOverflow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
