### ISSUE TITLE
[webview_flutter] : android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes

### ISSUE THREAD

**Issue by Jokernight** [flutter/flutter#74412]
Hi,

My app crash on Android in debug and release mode when i try to go out the app by opening another app with an Intent or launch the external browser with the plugin "url_launcher" v 5.7.6.

I use the 1.0.7 version of the plugin.

Thanks by advance.

## Steps to Reproduce

1. Run the app
2. Within the NavigationDecision i intercept the url and analyze it, four scenarios :
    - Nothing is intercepted and url is authorized, Navigation.navigate >> No crash
    - Call is intercepted to do a particular thing (Google connect for example) Navigation.prevent and call the native login >> No crash
    - Url is not authorized and the url needs to be opened in an external browser, use of the "url_laucher" plugin >> Crash
    - Url is intercepted to launch an intent corresponding to the url clicked on, Navigation.prevent >> Crash
3. The app crashes or not depending on the scenario

**Expected results:** 

App is opening the intent or the external browser

**Actual results:** 

App is crashing

<details>
  <summary>Logs</summary>

```
D/AndroidRuntime( 2451): Shutting down VM
E/AndroidRuntime( 2451): FATAL EXCEPTION: main
E/AndroidRuntime( 2451): Process: com.tapptic.lalibre, PID: 2451
E/AndroidRuntime( 2451): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime( 2451): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1625)
E/AndroidRuntime( 2451): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1864)
E/AndroidRuntime( 2451): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1183)
E/AndroidRuntime( 2451): 	at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:188)
E/AndroidRuntime( 2451): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 2451): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 2451): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 2451): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 2451): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2451): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 2451): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I use Intelli J IDEA Ultimate 

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /opt/flutter
    • Framework revision 1aafb3a8b9 (10 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ylorson/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/ylorson/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~19.10-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Jokernight 
I see that you are using an older version of `url_launcher`. Current version is `^5.7.10`. You may try to upgrade it and see if you still get the error.
You may also want to upgrade to latest stable (1.22.5) and check if it improves error behavior.

Also, check out these 2 similar but closed issues and see if any of the underlying comments help, https://github.com/flutter/flutter/issues/58229
https://github.com/flutter/flutter/issues/62022

If none of the above works and issue still persists, please provide a complete minimal reproducible code sample that we can run to see the crash.

**Comment by searchy2** [comment]
Seeing this crash as well.
webview_flutter: ^1.0.7

<summary>Crash Logs</summary>
<details>

```
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
android.view.inputmethod.InputMethodManager.startInputInner (InputMethodManager.java:1625)
android.view.inputmethod.InputMethodManager.checkFocus (InputMethodManager.java:1864)
android.view.inputmethod.InputMethodManager.isActive (InputMethodManager.java:1183)
io.flutter.plugins.webviewflutter.InputAwareWebView$1.run (InputAwareWebView.java:188)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7397)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)
```
</details>

I'll let you @Jokernight create a reproducible sample unless you're unable to.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
