### ISSUE TITLE
Allow enter line breaks in TextFormField

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#74411]
## Use case

I am creating a form in a website with flutter web. Some of my fields are multiline, and I would like to allow the user to enter text with jump lines, something like this:

```
First line,

Above this is an empty line
```

Right now if I click enter the focus jumps to the next field.

## Proposal

It would be nice to add some kind of property to TextFormField, something like 'multiline' that overwrites the behaviour of the enter button and let the user enter empty lines.

**Comment by pedromassangocode** [comment]
Hi @svprdga 
Sorry, I don't understand this proposal right, is this what you are looking for?

![gif](https://user-images.githubusercontent.com/67424416/105850276-d1f97900-5fe1-11eb-9513-eb35e0c90e59.gif)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
  MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextFormField(
          maxLines: 4,
          keyboardType: TextInputType.multiline,
        ),
      ),
    ),
  ),
);
}
```
</details>

**Comment by svprdga** [comment]
Yes @pedromassangocode, that's what I whish to achieve in web builds.

**Comment by pedromassangocode** [comment]
Hi @svprdga
Isn't this currently possible? I ran the same code in https://github.com/flutter/flutter/issues/74411#issuecomment-767537173 and I was able to replicate the expected behavior.

Is this what you want to achieve?
Thank you

**Comment by svprdga** [comment]
Yes @pedromassangocode, I didn't know that this can be done like that. Sorry for the time you have lost and many thanks.
