### ISSUE TITLE
[web]: <package incompatible version after upgrading flutter>

### ISSUE THREAD

**Issue by Simouad** [flutter/flutter#74419]
My Flutter app depends on intl_utils: ^1.6.3, and today I upgraded Fluter to the latest Flutter (Channel master, 1.26.0-2.0.pre.).

Now when I run pub get I get this error:

> Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0, flutter_localizations from sdk is incompatible with intl_translation >=0.17.7.
> 
> Because intl_utils >=1.6.3 <1.9.0 depends on intl_translation 0.17.10 and intl_utils >=1.9.0 depends on intl_translation 0.17.10+1, intl_utils >=1.6.3 requires intl_translation 0.17.10 or 0.17.10+1.
> Thus, flutter_localizations from sdk is incompatible with intl_utils >=1.6.3.
> So, because xxx depends on both flutter_localizations any from sdk and intl_utils ^1.6.3, version solving failed.
> pub get failed (1; So, because xxx depends on both flutter_localizations any from sdk and intl_utils ^1.6.3, version solving failed.)
> 
so I added intl: ^0.17.0-nullsafety.2 and intl_translation: ^0.17.10+1 but now I get this

> Because intl_translation >=0.17.0 <0.17.7 depends on intl ^0.15.3 and xxx depends on intl ^0.17.0-nullsafety.2, intl_translation >=0.17.0 <0.17.7 is forbidden.
> 
> So, because gipi_partner depends on intl_translation 0.17.6, version solving failed.
> 
> pub get failed (1; So, because xxx depends on intl_translation 0.17.6, version solving failed.)

I'm trying all combinations of versions but none is working. And when i downgrade  flutter it works fine?

**Comment by TahaTesser** [comment]
Hi @Simouad 
This is because `intl_translation` targetting an older `intl`, please file an issue on their dedicated GitHub
You can make your project work by downgrading the `stable` flutter channel and using non-null-safety dependencies
These are  package conflicts, not an issue with Flutter itself
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Simouad** [comment]
thanks
