### ISSUE TITLE
Add .shadeX documentation to colors

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#74422]
Relates to https://github.com/flutter/flutter/issues/71591

Color documentation (e.g. https://api.flutter.dev/flutter/material/Colors/red-constant.html) should be updated to indicate that shades of color are available via `.shadeX`, e.g. `Colors.red.shade100`. 

The generated diagrams for color shades should also be updated

**Comment by thisisamank** [comment]
Hi, @pedromassango I would like to solve this issue, can you please assign it to me?

**Comment by madhur1846** [comment]
Why this issue is opened even after it merged?
