### ISSUE TITLE
Failing tests running in devicelab_staging, not blocking tree

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#74431]
"Mac_android hot_mode_dev_cycle__benchmark" is currently failing in devicelab_staging. It is not running in either cocoon or luci devicelab prod (and thus not blocking the tree) https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20hot_mode_dev_cycle__benchmark/36/overview

Brief summary of what happened:

- due to a mistake during the cocoon -> luci devicelab migration, 100% of the mac/android bots were moved from cocoon to devicelab_staging, and thus the cocoon builds were not running and thus the tests were not able to make the tree red.
- there were three failing tests that were not noticed. the three tests were `Mac_android microbenchmarks`, `Mac_android hot_mode_dev_cycle__benchmark` and `Mac_android android_semantics_integration_test`.
- https://github.com/flutter/flutter/commit/444c954f439bb5dce0e9c130c7a37a424ccb5927 was landed to intentionally fail `hot_mode_dev_cycle_macos_targetbenchmark` in order to explicitly close the tree until either the tests are fixed or the devicelab tests are migrated to devicelab prod, in which case they will show up on the build dashboard.
- https://github.com/flutter/flutter/commit/75dc45aba388b6db05914ae1d20c9298a0191172 was landed to fix "Mac_android hot_mode_dev_cyclebenchmark"
- The revert https://github.com/flutter/flutter/commit/cecb7f3b58c00fdb038fe8d78d1ecb76598926b3 was landed to fix "Mac_android android_semantics_integration_test" (the initial commit landed right after the migration of the test from cocoon to devicelab_staging)
- the mac/android tests have been migrated to devicelab prod luci group, and a framework commit will soon be landed to populate them in the build dashboard.

Things that need to happen for this issue to be closed:

- [x] `Mac_android hot_mode_dev_cycle__benchmark` passes [green build](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20hot_mode_dev_cycle__benchmark/41/overview)
- [x] `Mac_android android_semantics_integration_test` fixed and passes [green build](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20android_semantics_integration_test/49/steps?succeeded=true&debug=true)
- [x] `Mac_android microbenchmarks` passes [green build](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/44/overview)
- [x] framework `prod_builders.json` file updated to include mac/android tasks
- [x] the intentional fail in `hot_mode_dev_cycle_macos_targetbenchmark` removed [PR](https://github.com/flutter/flutter/pull/74438)

**Comment by christopherfujino** [comment]
cc @godofredoc and @zanderso

**Comment by christopherfujino** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20android_semantics_integration_test/44/overview is also failing

**Comment by jonahwilliams** [comment]
@goderbauer

**Comment by godofredoc** [comment]
Mac android were moved to prod and they will become blockers in a few mins

**Comment by godofredoc** [comment]
Moving to P1
