### ISSUE TITLE
[Windows] platformBrightness always returns 'Brightness.light' 

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#74436]
Using the latest Master, Windows receives `Light` always as the value, and no rebuild of the app occurs at all when the OS theme is changed. 

MacOS and Ubuntu work as expected.

```
Widget build(BuildContext context) {
    MediaQueryData mq = MediaQuery.of(context);
    print(mq.platformBrightness);
    return Container();
}
```

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/54612
