### ISSUE TITLE
Cocoon auto build failed: metrics_center 0.0.4, version solving failed

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#74430]
Detailed error message:
```
Resolving dependencies...
The current Dart SDK version is 2.10.5.

Because metrics_center 0.0.4 depends on meta 1.3.0-nullsafety.6 which requires SDK version >=2.12.0-0 <3.0.0, metrics_center 0.0.4 is forbidden.
So, because cocoon_service depends on metrics_center 0.0.4, version solving failed.
The command '/bin/sh -c pub get' returned a non-zero code: 1
```

**Comment by keyonghan** [comment]
@liyuqian Could you please help take a look?

**Comment by liyuqian** [comment]
Just had an offline discussion with Keyong. We believe the solution is to fix the Dart SDK version on the cloud build. The cloud build is using dev channel Flutter so it should come with Dart SDK 2.12. Maybe it's using another stable Dart SDK version that's preinstalled.

**Comment by keyonghan** [comment]
Do we know how/which Dart SDK is used when deploying cocoon to appengine? Here is the step we use cloud build to auto deploy: https://github.com/flutter/cocoon/blob/master/cloudbuild.yaml#L22 Is it included in `gcr.io/cloud-builders/gcloud` or somewhere else?
@dnfield @godofredoc

**Comment by dnfield** [comment]
Where did you get the failure message from?

**Comment by keyonghan** [comment]
At the step: https://github.com/flutter/cocoon/blob/master/cloud_build/deploy.sh#L10

I reproduced this locally, and verified that it is caused the the dart sdk preinstalled in ENV (separate from the Flutter one). My local has dart 2.10.5, and it gives the same error.

**Comment by keyonghan** [comment]
Here is the detailed log of a failed cloud build: [log](https://00f74ba44b2cb5232f7a6a4a52ca24a86690127834-apidata.googleusercontent.com/download/storage/v1/b/staging.flutter-dashboard.appspot.com/o/log-8c5f69f3-e10c-4622-bf42-bc1db79d3e14.txt?jk=AFshE3VwEwNAXLx4lMCktrm_guHYNR_ERB-xZI0dCMOfrCUl2qRws86xBSGrKk3R0vBFCDOC2zbX0WaZDPrZRfy6q4hWpsbZcab7O1IVnUZ2PYPBFRbYnOAT6Kme1XsW3Ixidpr1VdeBCL6Q_y3j7FmUh8o8Zvr9_PaPhmTHdjRRM2xq4EPVVV2xGJZ_zuw0QncR6STKVCTPxgv6Xytkm2XuiLPz5AL_cameDQgUL7bxOmi0wvySsWUodbqQ1QGFAe3xHsflQRWirtKJXoD62lr44O76I4jhN7VnHiHiNnouUSDU19rdpZe1nTXf0alQdRFWxWTi29-_CyBmFf_Rg_XVt9nEw97SQhDFeGDKGL-0YSeO7V5O5sVGhM2F7o9Dxt6NKz4FKYaHut9I4hEpwqMLkybeWQE6vp5k04ZfqL8NtqIRPIlre54H5hYwnoDXxIzNImJUlXVjrMIKc1d0_CEr32W2rprdbeUZKR9kVl7M1ihfA3dRNuLCd1Usvq_iZMK8v6kXbgW0v76xfHzNhoHPD9MGtdC3_O4u79AfK0t9chJyDu7BI62YQiJ4FeSxUSScjluhf1hAIpu7g9ZQPCZIIFU_4D9KfSaRROKZlEUw11FiLCR2ImW-hoyU3w_muv6js3t6T0WUwwlPuxRrKgPwjsnW0MyH-ghXYaBFD0dC3oH1-ns941qQbo-ivBjGDDVH97GlCape4TceNv9m0s6S1jt2ppONrOliRqlBYzZj7RfTKrvzrdINV5daWGGpxU1akmSRtdr0LMW1285nYQIZCAVdPJcEY2IvVuH45JGS6j7IWSKFxqNTxkhPDPKreGKnj-kwg_4wOTAIKwpScEu6wzBrFjOOGIdlXn4dl9mPh9IGU0Jnb0_76O7BYsxvjUUQEse4rdVRsxwUhYfWbnRwFn5NlPMkc5XNx6_xbYC5erBYY9qNKJ-S1zS21lqNpnav52SELo0dwcm84FFZuaPCKkk6kcx6YeSMIPg&isca=1)

**Comment by dnfield** [comment]
It's pulling in a google/dart-runtime docker image. If we can switch that to `docker pull google/dart-runtime:2.12-dev` it should work. Right now it's pulling in a stable version from 2.10.x.

**Comment by dnfield** [comment]
Alternatively we can wait for Dart 2.12 to go to stable, or revert the metricscenter change in the mean time.

**Comment by dnfield** [comment]
Could also consider just using the dev tag, since that will more closely match whatever Flutter has anyway.

**Comment by keyonghan** [comment]
Thanks Dan! `google/dart-runtime:2.12-dev` works.

Since this is blocking the cocoon auto build, and `metrics_center` has to keep with head, we may choose to use `dev` version instead.
