### ISSUE TITLE
Add BackButtonListener into Flutter framework - Navigator 2.0

### ISSUE THREAD

**Issue by douglasiacovelli** [flutter/flutter#74437]
## Use case
When using the navigator 2.0 with routes it becomes really hard to listen to the back button in screens that wouldn't need a router otherwise.

Examples:
-  User is on page A, adds page B to the stack and then as one presses back on page B, a confirmation dialog should be shown to confirm the intent to leave.

- User is on page A with a PageView widget. User swipes right and then after pressing the back button, the user expects to be taken to the previous page of the PageView instead of leaving the app.

## Proposal
I may be simplifying things, but it seems to me that it would be better if we had WillPopScope wrapping the router/navigator widget instead of having a thing such as BackButtonDispatcher, which depends on the router. This would also allow each screen to wrap itself with WillPopScope if it wants to do something before the user leaves.

Ideally this solution should call the farthest WillPopScope element on the tree before the one on top and so forth, following the chain of responsibility pattern.

Right now the only solution I see is to wrap ScreenB with a router element and implement another routerDelegate (with a single screen), which seems unnecessary for such a simple thing.

Am I missing something from the current API?

@chunhtai

**Comment by douglasiacovelli** [comment]
I was able to get it working with a not so elegant solution:

```dart
class BackButtonListener extends StatelessWidget {
  final Widget child;
  final Future<bool> Function() onBackPressed;

  const BackButtonListener({
    this.child,
    this.onBackPressed,
  });

  @override
  Widget build(BuildContext context) {
    BackButtonDispatcher dispatcher = Router.of(context)
        .backButtonDispatcher
        .createChildBackButtonDispatcher()
          ..takePriority();

    return Router(
      routerDelegate: BackButtonRouterDelegate(
        child: child,
        onBackPressed: onBackPressed,
      ),
      backButtonDispatcher: dispatcher,
    );
  }
}

class BackButtonRouterDelegate extends RouterDelegate with ChangeNotifier {
  final Widget child;
  final Future<bool> Function() onBackPressed;

  BackButtonRouterDelegate({@required this.child, this.onBackPressed});

  @override
  Widget build(BuildContext context) {
    return child;
  }

  @override
  Future<void> setNewRoutePath(configuration) {
    return null;
  }

  @override
  Future<bool> popRoute() {
    return onBackPressed();
  }
}
```

and the usage with a simple widget is like so:
```dart
return BackButtonListener(
      onBackPressed: () {
        //do something and return true when it is handled and false if you want to pass it to the next one
      },
      child: ...
);
```

**Comment by chunhtai** [comment]
something like this should work.
```dart
class BackButtonListener extends StatefulWidget {
  final Widget child;
  final Future<bool> Function() onBackPressed;

  const BackButtonListener({
    this.child,
    this.onBackPressed,
  });
  @override
  BackButtonListenerState createState()=>BackButtonListenerState();
}

class BackButtonListenerState extends State<BackButtonListener> {

  BackButtonDispatcher dispatcher;
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (dispatcher != null) {
      dispatcher.removeCallback(widget.onBackPressed);
    }
    dispatcher = Router.of(context)
        .backButtonDispatcher
        .createChildBackButtonDispatcher();
    dispatcher.addCallback(widget.onBackPressed);
    dispatcher.takePriority();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```

**Comment by douglasiacovelli** [comment]
So there's no need to use a new router? This looks much better, thanks.

In spite of that, I still believe it would be beneficial if we didn't have to implement this manually. Do you think this Widget could be inserted into the lib?

**Comment by chunhtai** [comment]
yes, I think this can be a useful widget. I will update this issue

**Comment by douglasiacovelli** [comment]
Changed! Thank you again, @chunhtai :) 
That code worked perfectly. Same result as the previous one.

**Comment by idkq** [comment]
@chunhtai I need to prevent swiping back iOS style (dragging from the edges) depending on a variable (I got a slider near the edges which are causing unintended swipe backs, so I want to prevent swiping if slider is moving). 

The above does not work for me as it is triggered post swipe. I'm using nested navigation from @johnpryan https://gist.github.com/johnpryan/bbca91e23bbb4d39247fa922533be7c9 any ideas?

**Comment by chunhtai** [comment]
@idkq I think this is a separate issue, I took a look at how willpopcallbacks is tied to cupertinopagetransition, and found it quite weird that we just disable pop animation when there is will pop callback. I think we have to rework this part a little bit, can you file a new issue with this?

**Comment by idkq** [comment]
Here https://github.com/flutter/flutter/issues/76621 I just found a workaround btw

**Comment by douglasiacovelli** [comment]
I've just run into an issue on my app and I believe I found the solution. On the [BackButtonListener](https://github.com/flutter/flutter/issues/74437#issuecomment-765576033) it is important to dispose and remove the callback, otherwise it might still be alive even if the screen that used it is no longer active.

```dart
  @override
  void dispose() {
    _dispatcher?.removeCallback(widget.onBackPressed);
    super.dispose();
  }
```

**Comment by douglasiacovelli** [comment]
@chunhtai I'll open up a PR for this. I may need some help in the near future regarding the tests, but I'll give it a try first :)

**Comment by chunhtai** [comment]
@douglasiacovelli Much appreciate! Feel free to ping me on the PR, I can definitely help with the test.

**Comment by pedromassango** [comment]
Fixed by https://github.com/flutter/flutter/pull/79642
