### ISSUE TITLE
Output dir cleanup prior to artifact inconsistent between apk and appbundle build commands

### ISSUE THREAD

**Issue by jrmiddle** [flutter/flutter#74460]
After building a stripped **apk**, the symbol files I expect to see are present in the path I pass to `--split-debug-info` upon build completion. However, when building a stripped **aab**, the symbols are **not** present at the requested path upon build completion.

Upon further observation, it looks like the symbol files *are* generated, ahead of `app.aab` and `app.sig`, but are then deleted immediately before `app.aab` and `app.sig` appear. It should be noted that the directory I'm passing to `--split-debug-info` is the same as the directory into which `app.aab` eventually placed by the build process:
```
~/flutter/bin/flutter build appbundle \
                --release \
                --build-name=1.0.666 \
                --build-number=666 \
                --target-platform android-arm,android-arm64 \
                --no-shrink \
                --split-debug-info=./build/app/outputs/bundle/release
```

If I pass a different directory to `--split-debug-info`, such as `./build/app/outputs/bundle-symbols/release`, the symbols do persist after the build completes.

Low priority probably, but perhaps worth noting.

**Comment by TahaTesser** [comment]
Hi @jrmiddle 
Can you please provide your `flutter doctor -v`?
Thanks for filing the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
