### ISSUE TITLE
Why would flutter use gradle 5.6.2 instead of 6.5 like AS?

### ISSUE THREAD

**Issue by UltraBurstXD** [flutter/flutter#74496]
Hi,
I'm running into some problems because flutter is using an old and buggy version of Gradle. I've bunch of offline dependencies, when I try to run my app I get:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not open cp_init remapped class cache for 3truk786bichutpwwp37wxiyx (/home/[USER_NAME]/.gradle/caches/5.6.2/scripts-remapped/offline_elo2liyi6dyjcsoova2o93p29/3truk786bichutpwwp37wxiyx/cp_init40e7ec637808a9c747559d26950b1d9b).
> Could not open cp_init generic class cache for initialization script '/home/[USER_NAME]/.gradle/init.d/offline.gradle' (/home/[USER_NAME]/.gradle/caches/5.6.2/scripts/3truk786bichutpwwp37wxiyx/cp_init/cp_init40e7ec637808a9c747559d26950b1d9b).
   > Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 5m 34s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```
I'm using Flutter with VS Code BTW...

**Comment by TahaTesser** [comment]
Hi @UltraBurstXD 
If you're using flutter `beta` and up channels, the Flutter template uses Android Gradle 4.1.0 which requires Gradle 6.5+
Can you upgrade your Flutter channel and update your Gradle to `'com.android.tools.build:gradle:4.1.0'` and try again? 

If the problem persists, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by UltraBurstXD** [comment]
Well, I'm using flutter from stable channel, 1.22.5. I fixed that by changing the Gradle version manually changing config (I don't remember the name) file in my project's root from 5.6.2 to 6.8... By default, flutter uses 5.6.2, and I don't know why...

**Comment by TahaTesser** [comment]
Hi @UltraBurstXD 
As mentioned in https://github.com/flutter/flutter/issues/74496#issuecomment-766612742, currently `beta` and up channels are using Android Gradle 4.1 but stable still uses Android Gradle 3.5.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
