### ISSUE TITLE
Flutter webview with file choose

### ISSUE THREAD

**Issue by BhagirathGadhesariya** [flutter/flutter#74490]
We are creating an app which uses the webview and will access a page where the user needs to upload a file. We are facing problems with the file chooser does not open and clicking the edit button open file manager. We need to open file chooser with two option one is camera and second one is file manager.

Check this image for what i want 

![screenshot-nimbus-capture-2021 01 22-10_35_48](https://user-images.githubusercontent.com/69451838/105491229-fef51580-5cdb-11eb-8cda-9acbed871d9c.png)

**Comment by darshankawar** [comment]
@BhagirathGadhesariya 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample.
Also, checkout [this](https://github.com/flutter/flutter/issues/27924) similar but fixed issue related to choosing a file using `webview_flutter` and see if it helps.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
