### ISSUE TITLE
Showing this error while trying to run app

### ISSUE THREAD

**Issue by akashlilhare** [flutter/flutter#74512]
`event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in news_app...}
event sent after app closed: {id: 0, progressId: null, finished: true}
Launching lib\main.dart on ASUS X00TD in debug mode...

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF759AF24E8
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=12768, thread=12908, isolate_group=(nil)(0000000000000000), isolate=(nil)(0000000000000000)
isolate_instructions=0, vm_instructions=7ff759a0f240
Stack dump aborted because InitialRegisterCheck failed.
Running Gradle task 'assembleDebug'...
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.`

**Comment by iapicca** [comment]
@akashlilhare 
can you provide your `flutter doctor -v` and your `flutter run -v`

**Comment by akashlilhare** [comment]
## result of **flutter doctor -v**

`C:\Users\91966>flutter doctor -v
[√] Flutter (Channel master, 1.26.0-13.0.pre.122, on Microsoft Windows [Version 10.0.18363.1316], locale
    en-US)
    • Flutter version 1.26.0-13.0.pre.122 at C:\flutter\flutter
    • Framework revision e599cdd414 (21 hours ago), 2021-01-22 11:07:08 -0800
    • Engine revision 90641fa923
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\91966\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk-15.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.1+9-18)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio
    • Android Studio at C:\Program
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.6397.47

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\91966\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 2 categories.`

## result of flutter run -v

`C:\Users\91966>flutter run -v
[ +144 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +118 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e599cdd414d79c78caedef2dad13edd015b806f1
[   +1 ms] executing: [C:\flutter\flutter/] git tag --points-at e599cdd414d79c78caedef2dad13edd015b806f1
[  +78 ms] Exit code 0 from: git tag --points-at e599cdd414d79c78caedef2dad13edd015b806f1
[   +5 ms] executing: [C:\flutter\flutter/] git describe --match *.*.* --long --tags
e599cdd414d79c78caedef2dad13edd015b806f1
[ +138 ms] Exit code 0 from: git describe --match *.*.* --long --tags
e599cdd414d79c78caedef2dad13edd015b806f1
[   +1 ms] 1.26.0-12.0.pre-122-ge599cdd414
[  +52 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +100 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +114 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +80 ms] executing: C:\Users\91966\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +61 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +60 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +93 ms] "flutter run" took 388ms.
[  +24 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[  +55 ms]
           #0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:1274:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:432:19)
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +305 ms] ensureAnalyticsSent: 278ms
[   +7 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[  +11 ms] exiting with code 1`

**Comment by iapicca** [comment]
> `[ +24 ms] Error: No pubspec.yaml file found.`

@akashlilhare 
please  run the command in your app folder

**Comment by akashlilhare** [comment]
after changing the channel from mater to stable its working fine
