### ISSUE TITLE
Commands shouldn't be case sensitive

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#74521]
It seems unnecessarily user-hostile to make commands case-sensitive. We could accept `FLUTTER UPGRADE`, `Flutter Upgrade` and any other accidentally typed casing work, I think?

```
[C:\Windows\System32] flutter Upgrade
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Could not find a command named "Upgrade".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by ashishkhuraishy** [comment]
Hey i would like to be assigned to this

**Comment by Hixie** [comment]
I think on Linux that this would be very unusual. It might make sense for Windows, but being different between Linux and Windows seems like it would cause a lot of confusion.

That said, I think it would be quite reasonable to do something like `git` and say something like "Did you mean...":

```
[C:\Windows\System32] flutter Upgrade
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Could not find a command named "Upgrade". Did you mean "upgrade"?

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by ashishkhuraishy** [comment]
I thought converting the commands to lowercase will fix this issue but after reading @Hixie's comment I think `Did you mean...` will be a much more cleaner approach

**Comment by timsneath** [comment]
That could work. In general, Windows commands tend to be case-insensitive, but we're certainly not unique in having a CLI tool that doesn't follow Windows conventions. That said, Windows is our most-used customer OS. 

This is a low-pri issue, for sure, though -- it was only a fat finger on my part that even brought this to my attention.

**Comment by ashishkhuraishy** [comment]
I think `git` is case sensitive in windows(not sure though). That being said i would like to work on this, but now i am confused on which approach should I take. I personally would preffer the `Did you mean...` one. Could anyone suggest which I should go for?

**Comment by timsneath** [comment]
git is case sensitive just because even on Windows, it's not a true Windows
app (it's a POSIX app running on Windows through Cygwin).

**Comment by ashishkhuraishy** [comment]
I think the same can be said for `flutter` too right? Even though most of the users use windows we cant say flutter is a windows specific app. The same approach as `git` would be cleaner through out all the builds imo

**Comment by Hixie** [comment]
@timsneath I think there's a high cost to case-insensitivity that is hard to quantify. It permeates through the system and leads to all kinds of weird problems that are hard to debug. I agree that it's unlike Windows to be case-sensitive but I think the overall costs outweigh the benefits of matching the platform in this case.

@ashishkhuraishy If you are interested in "Did you mean" and can find a way to implement it in a non-invasive manner (i.e. something that is pretty self-contained and doesn't have a risk of introducing complications to the codebase) then that would be great.

**Comment by jonahwilliams** [comment]
I can't find it, but there have been similar requests for common typos - i.e. did you mean `flutter analyze` instead of `flutter analyse`. I think that would have to be implemented in package:args though.

**Comment by MrBirb** [comment]
Found it [#46009](https://github.com/flutter/flutter/issues/46009)

**Comment by Hixie** [comment]
Yes, doing this as a feature of `args` is a great idea. That way it can benefit any app that wants it, not just us.

**Comment by ashishkhuraishy** [comment]
Yes doing edits on `flutter_tools` will result in unwanted complications. Editing [args/command_runner](https://github.com/dart-lang/args/blob/master/lib/command_runner.dart) will be the easy approach imo
