### ISSUE TITLE
Move macOS/Android device-specific perf benchmarks to Linux/Android builders

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74522]
There are currently many devicelab Android and benchmark behavior tests that run on a macOS host with a tethered Android device.  However, the infra team says Linux hosts are easier to maintain and more stable in terms of infra issues.  Consider moving tests that are only measuring on-device Android performance and features since the host OS shouldn't matter for these tests.

#### Benchmark tests
- complex_layout_scroll_perf__timeline_summary
- tiles_scroll_perf__timeline_summary
- home_scroll_perf__timeline_summary
- cull_opacity_perf__timeline_summary
- picture_cache_perf__timeline_summary
- cubic_bezier_perf__timeline_summary
- cubic_bezier_perf_sksl_warmup__timeline_summary
- backdrop_filter_perf__timeline_summary
- textfield_perf__timeline_summary
- fullscreen_textfield_perf__timeline_summary
- color_filter_and_fade_perf__timeline_summary
- fading_child_animation_perf__timeline_summary
- imagefiltered_transform_animation_perf__timeline_summary
- platform_view__start_up
- complex_layout__start_up
- complex_layout_scroll_perf__memory
- hello_world__memory
- microbenchmarks
- flutter_view__start_up
- new_gallery__transition_perf
- fast_scroll_large_images__memory

#### Android functionality tests
- channels_integration_test
- external_ui_integration_test
- embedded_android_views_integration_test
- hybrid_android_views_integration_test
- android_semantics_integration_test
- platform_interaction_test
- platform_channel_sample_test
- integration_ui_driver
- integration_ui_keyboard_resize
- integration_ui_screenshot
- integration_ui_textfield
- flavors_test
- service_extensions_test (?)

#### flutter_drive test
- drive_perf_debug_warning

#### Host-dependent tests (should not be moved)
- run_release_test
- hello_world_android__compile
- hot_mode_dev_cycle__benchmark
- ~~android_plugin_example_app_build_test~~ ([moved to tools integration](https://github.com/flutter/flutter/issues/70978))

Validate these tests pass on a Linux host and adjust the configs from `mac_android_tasks ` to `linux_tasks`
https://github.com/flutter/infra/blob/1943e229def07d8826f690dc4e6e22e7fe69f2a4/config/devicelab_staging_config.star#L169

**Comment by jmagman** [comment]
@liyuqian What do you think?

**Comment by liyuqian** [comment]
That sounds good. Maybe just leave 1-2 tasks on `mac/android` to verify Android development flow on Mac, and migrate all the rest to `linux/android`.

**Comment by jmagman** [comment]
> That sounds good. Maybe just leave 1-2 tasks on `mac/android` to verify Android development flow on Mac, and migrate all the rest to `linux/android`.

I think `Host-dependent tests (should not be moved)` section should cover it.

**Comment by jmagman** [comment]
@godofredoc can we prioritize this?  It'll probably make life easier for both of us...

**Comment by godofredoc** [comment]
Sounds good I'll start taking a look

**Comment by godofredoc** [comment]
Took a look and ran all the tests in the list using linux android test beds. The ones using flutter drive are as flaky in linux as they are on mac:

* [Linux android_semantics_integration_test](https://chromium-swarm.appspot.com/task?id=5214d6ce04f19e10)
* [Linux integration_ui_textfield](https://chromium-swarm.appspot.com/task?id=5214da483b000910)

**Comment by jmagman** [comment]
@godofredoc That's not surprising, those tests are testing on the device, not the host, so the host shouldn't matter.  So let's use Linux instead of Mac to host.

**Comment by godofredoc** [comment]
@zanderso then new linux/android capacity will be ready sometime between this and next week and we would like to start moving this list of macOS/android tests to linux/android. This will change the name of the metrics but it will also help us provide more capacity. Are there any concerns that need to get addressed before starting moving the benchmarks to Linux?

**Comment by keyonghan** [comment]
These benchmarks should be unblocked to be migrated to linux.
Whenever they are using the same `task name` as in mac, we will not use their historical data.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/24062 moved these tests from mac to linux in staging. All are passing except these four:
```
[Linux_android_staging complex_layout__start_up ](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android_staging%20complex_layout__start_up/5/overview)
[Linux_android_staging complex_layout_scroll_perf__memory  ](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android_staging%20complex_layout_scroll_perf__memory/5/overview)
[complex_layout_scroll_perf__timeline_summary](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android_staging%20complex_layout_scroll_perf__timeline_summary/5/overview)
[tiles_scroll_perf__timeline_summary ](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android_staging%20tiles_scroll_perf__timeline_summary/5/overview)
```
All are due to java version mis config. Version 11 is needed and has been enabled in prod for a while. We need to update the java version in staging as well to pass these tests.

**Comment by jmagman** [comment]
@blasten Can you take a look at these failing tests?

**Comment by keyonghan** [comment]
> @blasten Can you take a look at these failing tests?

https://flutter-review.googlesource.com/c/infra/+/24161 to switch to java 11.

**Comment by keyonghan** [comment]
All tests are passing except `Linux_android_staging android_semantics_integration_test`, filed https://github.com/flutter/flutter/issues/95298 to track.

Will wait for several more runs before migrated to prod.

**Comment by keyonghan** [comment]
All tests are passing except below two, and are ready to move to prod: https://github.com/flutter/flutter/pull/95365.

`Linux_android_staging android_semantics_integration_test` was fixed by https://github.com/flutter/flutter/pull/94875, will wait for validation.
` Linux_android_staging microbenchmarks ` started failing intermittently: https://github.com/flutter/flutter/issues/95366 (it keeps passing in prod under mac).

**Comment by keyonghan** [comment]
`Linux android_semantics_integration_test` is now enabled in prod, and is running okay.
Closing this bug in favor of https://github.com/flutter/flutter/issues/95366 to track `Linux_android_staging microbenchmarks`.
