### ISSUE TITLE
Regression: images that worked yesterday don't work today

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7452]
## Steps to Reproduce

Yesterday I could display these images in my Flutter app, but today they are blank. (I grabbed their URLs from photo.google.com and I can view them in a browser, but they don't show up in the Simulator.)

String pic1 =
    'https://lh3.googleusercontent.com/KF0R8kSdorTk2rATzkK0fQV1Rp0wSqk0N_0pJrfNxFVjTzwxksTLILD8OknHWu6s1qGw1vB_73RDuI95CpFiZZJYBwmXnFin5EOtzhWQ91suGId_CANSLHIBwPB1Vl9NRQU8sU9npWOFpMqq8QZ4XoKyVlAUY5HWF2nsZFsmtrd3P5GN-qrGalIg7tCYDXeMCPG6yX4WGjIFXKliE_LVsy_rwgyFezyfQG6dqXDdXvBURPHtacs6bVGdF-VNzuWTUvrEMJGBX9A72TkcUy5LG3PU_Q2kOV2DSODlh-pCStqBJr80COy4tV7kYJzKQ_lLcRa7Dk9Ao8P_cCR8WXECS3-DId1M8S87B4OHcOfybxr9JykBZgvw8VUiXPENCEQV7JPUfGnxWkuZGVb2gz6gpBsQHm6x-GdzHRNHDcGTIh5eFil7T9cQ7Rke5CauVFeDUIxvjWE1V_QA1M2MCph3UqUIqopcO6lN1jukJe2lppeb1t6sidFymXf-G6PWh8fQTUXSHM1HvkLYAdlHyI4YBnMqP5p-L7OKmx62HLAjAiSAEeR6CcKh19NP6IuQNjx6BOSE3YPOjQ9ehI4oUjHE1QZ83bctdKnI681ybAslg2YsfVOd-Qdb-g=w525-h700-no';
String pic2 =
    'https://lh3.googleusercontent.com/v_eUmjQfgg1C-W07Fib_pO1ooztOFS6kKNswpI4Y6KWr7YTOxKh003a7oMbkLjkPZmkyawMzOL0cROr4A99C_z6a8awlVCfcOcfjyg1lf6LgMEv53kwFRMxzt9xL9UfWtuKhpvNkn4wiuSfa5o0mlObFajTr21iwGjvD3_iY3LmqY7RlEqMoC887bM6UKTRKdcw4dKLO83Y_Q15Ue1UxXUndOl1XUyGrBt2y9AMElStb2NxEUgoKS8NXR1r6Ks-2irsWLw6Kdkpr_K1URL0neE_jgYDyXKTRO9t4r4-zRi2RcjOb0Xn8NVsyEFzJyGEONUSXAcz8lYFhzTBYEj2pj11i-FKEHgKgQgVUr8L8Tzng6QWn54PdmjMdwRsOONyPh-ANzgyzmtEVnpWMqpuw7GG6d4kaQjpaU2tGhurrQMrqJbuCnVPH4BXGX8svuwJgNftRus6yXhMpA6PtKqG_IFZB4rXtQK3W6_asxvyj95DroBSQR8NDVdMNKZlehK4q5q5c-IlgavgYv9CmsBBLQDNzI8wjlGNmqHjquG264ktLRse_bQyy7HLeCXxToWZ_JK14hVSJfb4rGLgTSXjsesvY70-B3gM0pZfEZba4hz-7T0UZ6ZYSiQ=w525-h700-no';
String pic3 =
    'https://lh3.googleusercontent.com/Zu_92jb_EVA8yZ578Dh8sznJZmGdlK88VACHb8UlbfdKjCIApFlfVk9tAlfuLdJSRqEeM3d5xYoHXnrynC5rLAZUN57-UQj2eGeyM4y9YpnX7AfWM_Gy5fD5D_5aITOTazrUT4lRwfzs672OCiivsE5OTB_N_2cw2rvhVsXLuq2TL4nbAIQAk--mh3ecFJNyVg6Cm3vWqveSzvx8Q5staEYBe-cOnfs-8ns3u84lI9YQBrIeCpNKXW5h7LNcuRQBGMDg1U3xg950pmz9LDzsTK4YKd2kh6xLWZXv2d0tFeFQ4_VU6747Usb87hbU5p0GH_E_BgUWRdO1LSCQ4N1wvG4K7BQ2jzgN3U9Ygr9S6A3L2S22XE9bP3U5TA9lMj_sSz3NH1Tkl0iUeFNNCVNt1B2JwvODK6CBAYv8u_fwwYSB0-PqjS4rQmL_2dNl57B9x5AEn5-b8YMMcCButwK2_VGwjNAuqBN0_dSI9Q5c2Ch-PjS5qLCYlRXFgbpBoMGH828GK6DD9ld435SNL_oHvuBp2DoQx71IaScIgkW2aA8sSK8hBFqHhcF2s7c8yT8_Uz1DlrwZaKGTed449Joa9HI71FB91pH08MtPzYs5ClsdQOlAGs5_Lg=w525-h700-no';
String pic4 =
    'https://lh3.googleusercontent.com/bPU5SwZcEXxnoU9lKLf202QpXnNX5wcibVYFu9T1vc9ve1zmOHZSXToQOeVvaKjTzmp2wCXTPbx1NmahWozw-_pnbniuJeSHETZvGv1c2vo4vYTU3ycEadDDZflDjwFKp2PeoY9tldgb_wJbrbFr6YQpl2RG2Iz8K8qICNZXDeEP-jQPkhQDlWztUNYEWKL_BU9-V_pa8265G7mZ7n4TlvSsVrYrVvwXSlEzTrCk2q0UZEjGoVc6fk2tGfUy2XVguFFZd2bz21bd_yZI2PaMtSH9ORyjWfQ4PG8L9NmndZwL0QY5Ld5aOqNEX0JgO1MUvU2Lck5mzpWjPiXVHC7k_QwPoKPVHDPE8WV36zId7_dECrRry1s6Q6hAbcVtUNtqWwMKvAX40zBtgrs_k_HKMKm3olSIHop0ZxT872AuokPvU1CnsR0dYvour40cHKx_zVf8sceTVjwmzKxLeIJuw0DTV4MKTlHvl5QuqOQA3YEuriSLLxsWBYyenApg1AE23pnh67ebZvGNiQcKoygRZKWY2T5ZawtObzvDSXatNMrinQUlVvEnXUDMrnTC5-9H7JSctgUT5OMe43AZRXGg2rZQcz8wBuWqLuYUE7RFZxEFUVq5HhO7lQ=w525-h700-no';

## Logs

Run your application with `flutter run` and attach all the log output.

Launching lib/main.dart on iPhone 6s Plus in debug mode...
CoreSimulatorBridge: Requesting installation of file:///Users/shaza/GoogleDrive/TMP-layout-flutter/ex1/build/ios/Release-iphonesimulator/Runner.app/ with options: {
	    CFBundleIdentifier = "com.yourcompany.popfashion";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/shaza/Library/Developer/CoreSimulator/Devices/00A1718E-C7AA-4B05-B650-6AFA1BA1F84B/data";
	}
	state->old_bundle: /Users/shaza/Library/Developer/CoreSimulator/Devices/00A1718E-C7AA-4B05-B650-6AFA1BA1F84B/data/Containers/Bundle/Application/545EE305-AC32-495C-8750-FB4E0B498251/Runner.app
	state->new_bundle: /Users/shaza/GoogleDrive/TMP-layout-flutter/ex1/build/ios/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/shaza/Library/Developer/CoreSimulator/Devices/00A1718E-C7AA-4B05-B650-6AFA1BA1F84B/data/Library/Caches/com.apple.mobile.installd.staging/temp.XggQjm/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/shaza/Library/Developer/CoreSimulator/Devices/00A1718E-C7AA-4B05-B650-6AFA1BA1F84B/data/Library/Caches/com.apple.mobile.installd.staging/temp.XggQjm/extracted
	Added: {(
	)}
	Removed: {(
	)}
	Modified: {(
	    "com.yourcompany.popfashion"
	)}
CoreSimulatorBridge: Requesting launch of com.yourcompany.popfashion with options: {
	    arguments =     (
	        "--enable-dart-profiling",
	        "--flx=/Users/shaza/GoogleDrive/TMP-layout-flutter/ex1/build/app.flx",
	        "--dart-main=/Users/shaza/GoogleDrive/TMP-layout-flutter/ex1/lib/main.dart",
	        "--packages=/Users/shaza/GoogleDrive/TMP-layout-flutter/ex1/.packages",
	        "--enable-checked-mode",
	        "--observatory-port=8100"
	    );
	    environment =     {
	    };
	}
assertion failed: 15G1212 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
Observatory listening on http://127.0.0.1:8100/
Syncing files to device...                          1269ms

Run `flutter analyze` and attach any output of that command also.

flutter analyze
Analyzing lib/main.dart...
No analyzer warnings! (ran in 6.5s)

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/shaza/GoogleDrive/TMP-flutter/flutter
    • Framework revision 7f2915d331 (3 hours ago), 2017-01-11 10:54:42
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/shaza/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.8

[✓] Connected devices
    • iPhone 6s Plus • 00A1718E-C7AA-4B05-B650-6AFA1BA1F84B • ios • iOS 9.3 (simulator)

**Comment by chinmaygarde** [comment]
I get an HTTP 403 when trying to retrieve those images. You can serve them up from the asset bundle too.

**Comment by chinmaygarde** [comment]
I have verified that images that can be successfully retrieved from the network display correctly.

**Comment by eseidelGoogle** [comment]
Thanks for the bug @Sfshaza. :)
