### ISSUE TITLE
resident_runner_test actually calling "http.head('https://pub.dev')", takes 10 seconds

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74539]
`test/general.shard/resident_runner_test.dart: ResidentRunner fails its operation if the device initialization is not complete`
actually calls `http.head(Uri.https('pub.dev', ''))` which takes ~10 seconds on my machine.

https://github.com/flutter/flutter/blob/118f61230acdfb947e6ca739d0dc58aae7b17a61/packages/flutter_tools/lib/src/devtools_launcher.dart#L58

Caused by #73903
Found with https://github.com/flutter/flutter/pull/74531

**Comment by Hixie** [comment]
Are you sure that's what took ten seconds, and not the ten-second timeout lower in that function?

**Comment by Hixie** [comment]
Yeah I'm pretty sure that it's not the HTTP get that's the source of the 10 seconds. When I removed the 10 second timeout (which violated our style guide), the test failed by timing out at 15 seconds instead. I think something in there is never finishing in the test environment.

**Comment by jmagman** [comment]
> Are you sure that's what took ten seconds, and not the ten-second timeout lower in that function?

It was just paused on that line for 10 seconds when I was stepping through it.  The test doesn't actually time out, it just takes ~10 seconds to run (it's currently running in CI).

**Comment by jmagman** [comment]
...and now I can't reproduce the same way and it does look stuck in the 10 seconds timeout below, as you suggested.  Maybe there was a sun flare.

**Comment by Hixie** [comment]
I'm removing the timeout in https://github.com/flutter/flutter/pull/74859
