### ISSUE TITLE
Tapping on discrete slider values does not change the slider value

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#7454]
[This used to work last month and broke sometime in between.]

Slider widget used to support tapping on a discrete value on the track to change its state. Now the state does not change unless the thumb tack is grabbed and slid along the track.

**Comment by eseidelGoogle** [comment]
Might have been broken in adding Cupertino sliders?  @abarth or @HansMuller

**Comment by abarth** [comment]
Cupertino sliders didn't involve any modification to material sliders.

**Comment by abarth** [comment]
I'll take a look.

**Comment by abarth** [comment]
I'm not able to reproduce this issue in the Flutter Gallery discrete slider demo.  Can you help me reproduce the issue you're seeing?

**Comment by mehmetf** [comment]
This seems to be a problem on our side, I cannot create a simple example either. I need to deconstruct the UI to see what's going on. It is particularly odd that sliding it updates the value but not tapping. My guess is that tap is being swallowed by something else. Is there an effective way to debug that?

**Comment by mehmetf** [comment]
Reproduced it.

**The problem is that the slider is in a block that scrolls.**

```Dart
import 'package:flutter/material.dart';

class TabsDemo extends StatefulWidget {
  @override
  _TabsDemoState createState() => new _TabsDemoState();
}

class _TabsDemoState extends State<TabsDemo> {
  double selectedValue = 2.0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text('Slider Issue')),
        body: new Container(
            padding: const EdgeInsets.all(16.0),
            constraints: new BoxConstraints.expand(),
            decoration: new BoxDecoration(backgroundColor: Colors.white),
            child: new Block(children: [
              new Slider(
                  value: selectedValue.toDouble(),
                  max: 5.0,
                  divisions: 5,
                  onChanged: (value) {
                    setState(() => selectedValue = value);
                  }),
              new SizedBox(height: 1000.0),
            ])));
  }
}

void main() {
  runApp(new MaterialApp(home: new TabsDemo()));
}
```

Comment the SizedBox and it works.

**Comment by abarth** [comment]
Thanks.  I'll take a look to see what's going on.

**Comment by abarth** [comment]
I can repro the issue.

**Comment by abarth** [comment]
I'm about halfway to a fix.
