### ISSUE TITLE
Option to remove arrows on iPad share sheet

### ISSUE THREAD

**Issue by ruskakimov** [flutter/flutter#74552]
## Use case

Some apps remove the arrow from the sheet and center it.
E.g. video export share sheet in Procreate:
![IMG_8D736FBE281B-1](https://user-images.githubusercontent.com/5536948/105574222-0f6dc480-5d9e-11eb-91b4-85081eb3b15e.jpeg)

## Proposal

Exposing [permittedarrowdirections](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller/1622319-permittedarrowdirections) in [Share.shareFiles](https://pub.dev/documentation/share/latest/share/Share/shareFiles.html) or at least allowing the configuration on the screenshot above (centered and no arrows).

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
