### ISSUE TITLE
flutterEngine runWithEntrypoint not work.

### ISSUE THREAD

**Issue by zhaiyunbin** [flutter/flutter#74551]
I want add Flutter Module to my APP
Since I have multiple flutter modules, I use the following method，but it not working.
Flutter  lib/feed_entry_main.dart
```Dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';


@pragma('vm:entry-point')
void feedEntryPoint() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {


  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Main APP',
      builder: EasyLoading.init(),
      routes: BRoute.routes,
      initialRoute: BRoute.HomeRoute,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // home: MyHomePage(title: 'Flutter Main APP Home Page'),
    );
  }
}
``` 

iOS
```C
self.flutterEngine = [[FlutterEngine alloc] initWithName:@"MDflutter engine"];
[self.flutterEngine runWithEntrypoint:@"feedEntryPoint" libraryURI:@"feed_entry_main.dart"];

  FlutterViewController *fv = [[FlutterViewController alloc] initWithEngine:[MDFlutterDridge shareInstance].flutterEngine nibName:nil bundle:nil];
``` 

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/zyb/FlutterSDK
    • Framework revision f7a6a7906b (9 个月前), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zyb/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/liuyuhang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.0.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 3.1.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.0.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5.2.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @zhaiyunbin 
You seem to be using quite an old Flutter `stable` channel

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository with module and iOS App?
Thank you

**Comment by zhaiyunbin** [comment]
> Hi @zhaiyunbin
> You seem to be using quite an old Flutter `stable` channel
> 
> Can you please upgrade to the latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository with module and iOS App?
> Thank you

**Comment by zhaiyunbin** [comment]
> Hi @zhaiyunbin
> You seem to be using quite an old Flutter `stable` channel
> 
> Can you please upgrade to the latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository with module and iOS App?
> Thank you

I upgraded the flutter and fix it but I dont want do it, 💔
