### ISSUE TITLE
TextField Click and Drag UP/DOWN to select text not scrolling to the end of text. [Desktop Windows]

### ISSUE THREAD

**Issue by naseemali925** [flutter/flutter#74558]
## Steps to Reproduce

1. gist-> https://dartpad.dev/d191cb183d1bc3415808607932f0935c?
2. Click Run and then paste 4-5 paragraphs of text. Now try clicking the first character and drag down to select the complete or part of the text.

**Expected results:** 
The TextField should scroll towards the end/start of text based on whether the user is dragging up/down.

**Actual results:** 
It doesn't scrolls down to the end of the text instead the selection stops.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @naseemali925 
I can reproduce the issue. 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/73323
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
