### ISSUE TITLE
Typo in Codelab projects

### ISSUE THREAD

**Issue by armaebii** [flutter/flutter#74569]
I have been following the Codelab guides for building beautiful UIs with Flutter, and I found some typos.

**Section 5 'Add a responsive send button'**
_In \_buildTextComposer(), wrap the Container in an IconThem_ the ending letter 'e' for IconTheme is missing.

**Section 8 at step 3**
`void _handleSubmitted(String text) {
  _textController.clear();
  ChatMessage message = ChatMessage(
    text: text,
    animationController: AnimationController(      // NEW
      Duration: const Duration(milliseconds: 700), // NEW
      vsync: this,                                 // NEW
    ),                                             // NEW
  );                                               // NEW
  setState(() {
    _messages.insert(0, message);
  });
  _focusNode.requestFocus();
  message.animationController.forward();           // NEW
}`

I think the duration property for `AnimationController()` should start with lowercase.

**Comment by MrBirb** [comment]
Issue mentioned here [#66772](https://github.com/flutter/flutter/issues/66772)

**Comment by armaebii** [comment]
Oh I didn't know, thanks 😀.
