### ISSUE TITLE
SingleChildScrollView not scroll Complete screen

### ISSUE THREAD

**Issue by aaryan9499** [flutter/flutter#74567]
body: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(5),
                child: Container(
                  decoration:
                      BoxDecoration(borderRadius: BorderRadius.circular(10)),
                  height: 200.0,
                  child: carsouel(),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(5),
                child: Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.zero,
                    color: Theme.of(context).accentColor.withOpacity(0.1),
                  ),
                  //height: 480,
                  child: Column(
                    children: [
                      //------------Day Container-----
                      Padding(
                        padding: const EdgeInsets.only(left: 15, right: 15),
                        child: Container(
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.zero,
                          ),
                          height: 60,
                          child: ListView.builder(
                            scrollDirection: Axis.horizontal,
                            itemCount: getDaysOfWeek().length,
                            itemBuilder: (context, index) {
                              var now = new DateTime.now();
                              var day = DateFormat('EEEE').format(now);
                              var days = getDaysOfWeek()[index];
                              return Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(
                                      left: 15, right: 15),
                                  child: Container(
                                      decoration: BoxDecoration(
                                        borderRadius: BorderRadius.circular(25),
                                        color: days.toLowerCase() ==
                                                day.toLowerCase()
                                            ? Theme.of(context).accentColor
                                            : null,
                                      ),
                                      child: GestureDetector(
                                        onTap: () {},
                                        child: Padding(
                                          padding: const EdgeInsets.all(12),
                                          child: Text(
                                            '${days.substring(0, 3)}',
                                            style: TextStyle(
                                                color: days.toLowerCase() ==
                                                        day.toLowerCase()
                                                    ? Theme.of(context)
                                                        .canvasColor
                                                    : null),
                                          ),
                                        ),
                                      )),
                                ),
                              );
                            },
                          ),
                        ),
                      ),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Card(
                            child: Center(
                              child: TableCalendar(
                                initialCalendarFormat: CalendarFormat.month,
                                calendarStyle: CalendarStyle(
                                    todayColor: Theme.of(context).accentColor,
                                    selectedColor:
                                        Theme.of(context).accentColor,
                                    todayStyle: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 20.0,
                                        color: Colors.white)),
                                headerStyle: HeaderStyle(
                                  centerHeaderTitle: true,
                                  formatButtonDecoration: BoxDecoration(
                                    color: Theme.of(context)
                                        .accentColor
                                        .withOpacity(0.6),
                                    borderRadius: BorderRadius.circular(25.0),
                                  ),
                                  formatButtonTextStyle:
                                      TextStyle(color: Colors.white),
                                  formatButtonShowsNext: false,
                                ),
                                startingDayOfWeek: StartingDayOfWeek.monday,
                                builders: CalendarBuilders(
                                  selectedDayBuilder: (context, date, events) =>
                                      Container(
                                          margin: const EdgeInsets.all(5.0),
                                          alignment: Alignment.center,
                                          decoration: BoxDecoration(
                                              color:
                                                  Theme.of(context).accentColor,
                                              borderRadius:
                                                  BorderRadius.circular(8.0)),
                                          child: Text(
                                            date.day.toString(),
                                            style:
                                                TextStyle(color: Colors.white),
                                          )),
                                  todayDayBuilder: (context, date, events) =>
                                      Container(
                                    margin: const EdgeInsets.all(5.0),
                                    alignment: Alignment.center,
                                    decoration: BoxDecoration(
                                        color: Colors.blue,
                                        borderRadius:
                                            BorderRadius.circular(8.0)),
                                    child: Text(
                                      date.day.toString(),
                                      style: TextStyle(color: Colors.white),
                                    ),
                                  ),
                                ),
                                calendarController: calenderController,
                              ),
                            ),
                          ),
                          Container(
                            child: Padding(
                              padding: const EdgeInsets.only(
                                  left: 10, top: 10, bottom: 5),
                              child: Text('Quick actions'),
                            ),
                          ),
                          Container(
                            child: Padding(
                              padding: const EdgeInsets.only(
                                left: 10,
                                bottom: 10,
                              ),
                              child: RaisedButton(
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12.0),
                                    side: BorderSide(
                                        color: Theme.of(context).accentColor)),
                                onPressed: () {
                                  showResponseMessage("coming soon...");
                                },
                                child: Padding(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 10, vertical: 12),
                                  child: Text(
                                    "See scheduled orders",
                                    textAlign: TextAlign.center,
                                  ),
                                ),
                              ),
                            ),
                          )
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(5),
                child: Container(
                  width: MediaQuery.of(context).size.width,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.zero,
                    color: Theme.of(context).accentColor.withOpacity(0.1),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Consumer<CategoryListProvider>(
                        builder: (context, categoryItem, child) {
                          return ListView.builder(
                            shrinkWrap: true,
                            itemCount:
                                categoryItem.categoryWithItemResponse.length,
                            itemBuilder: (context, catIndex) {
                              var category =
                                  categoryItem.categoryWithItemResponse;
                              return Padding(
                                padding:
                                    const EdgeInsets.fromLTRB(15, 10, 10, 0),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    Padding(
                                      padding: const EdgeInsets.all(8.0),
                                      child: Row(
                                        children: [
                                          Text(
                                            category[catIndex].categoryName,
                                            style: Theme.of(context)
                                                .accentTextTheme
                                                .headline4
                                                .copyWith(
                                                  color: Theme.of(context)
                                                      .accentColor,
                                                  fontSize: 18,
                                                  fontWeight: FontWeight.w500,
                                                ),
                                          ),
                                          SizedBox(
                                            width: 2,
                                          ),
                                          Icon(
                                            Icons.arrow_forward_ios,
                                            size: 14,
                                            color:
                                                Theme.of(context).accentColor,
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      height: 180,
                                      child: ListView.builder(
                                        shrinkWrap: true,
                                        itemCount: 5,
                                        scrollDirection: Axis.horizontal,
                                        itemBuilder: (context, index) {
                                          return Padding(
                                            padding: const EdgeInsets.only(
                                                right: 8.0),
                                            child: Container(
                                              height: 155,
                                              width: 155,
                                              decoration: BoxDecoration(
                                                borderRadius:
                                                    BorderRadius.circular(10),
                                                color: Colors.white,
                                              ),
                                              child: Center(
                                                child: Text("Data $index"),
                                              ),
                                            ),
                                          );
                                        },
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            },
                          );
                        },
                      )
                    ],
                  ),
                ),
              )
            ],
          ),
        ),

**Comment by iapicca** [comment]
@aaryan9499 
can you describe the issue and provide a your `flutter doctor -v` and a **_complete_** **runnable** [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
not a snippet from production code

**Comment by aaryan9499** [comment]
i want to make full screen scrollable with mutiple listview builder and so on,
how do i need to align on in single scroll view, can you suggest me something for that.
![Screenshot (1)](https://user-images.githubusercontent.com/77610575/105608613-e7945600-5dc9-11eb-948b-00df4bbc7552.png)
![Screenshot (2)](https://user-images.githubusercontent.com/77610575/105608614-e95e1980-5dc9-11eb-8acf-86982013b253.png)
i am not able to scroll from second part from items

**Comment by iapicca** [comment]
@aaryan9499 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, 
please provide your `flutter doctor -v` your `flutter run -v`
and a **_complete runnable_** [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
