### ISSUE TITLE
Remove extension methods from flutter_tool

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#74575]
Extension methods are difficult to reason about and have surprising/confusing behavior.

Here is an example of a problem I ran into. I'm sure it has a reasonable explanation, but the point would be that in this case extension methods were more distracting than helpful.

Consider the extension method here:

https://github.com/flutter/flutter/blob/f9a8c86d7948102e874c0a79eae88f407d871de2/packages/flutter_tools/lib/src/vmservice.dart#L819

A method with the same name, but a slightly different type appears in the extended class:

https://github.com/dart-lang/sdk/blob/089ca8c1eb5a277d1392599f14f9a73a1c728bfa/pkg/vm_service/lib/src/vm_service.dart#L1841

I was trying to add a test of the method in https://github.com/flutter/flutter/pull/74574, but I couldn't figure out how to get the extension method to be called instead of the method on the extended class.

Which one will be chosen in various situations? One of the features of Dart, I would say, is that generally you don't have to think about that the way you would with other OO languages. Further, if you change the name of the extension method, there is no signal from the analyzer that call sites might now be calling a totally different method since it's still there in the extended class.

We should remove uses of extension methods from the tool, and enable a lint to keep them from sneaking back in, if possible.

/cc @jonahwilliams @bkonyi

**Comment by bkonyi** [comment]
I think you meant to link to [this line](https://github.com/dart-lang/sdk/blob/089ca8c1eb5a277d1392599f14f9a73a1c728bfa/pkg/vm_service/lib/src/vm_service.dart#L1926)?
