### ISSUE TITLE
[local_auth] canCheckBiometrics always return false in android 6

### ISSUE THREAD

**Issue by araafat3** [flutter/flutter#74583]
bug:
[local_auth] i have fingerprint in my emulator and in my mobile version android 6 when i am call canCheckBiometrics function always return false to me

/data/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
• Flutter version 1.12.13+hotfix.8 at /data/flutter
• Framework revision 0b8abb4 (9 weeks ago), 2020-02-11 11:44:36 -0800
• Engine revision e1e6ced81d
• Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /data/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: /data/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✓] Android Studio (version 3.5)
• Android Studio at /data/android-studio
• Flutter plugin version 43.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.42.1)
• VS Code at /usr/share/code
✗ Flutter extension not installed; install from
https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by iapicca** [comment]
> v1.12.13+hotfix.8

@araafat3 your [flutter version](https://flutter.dev/docs/development/tools/sdk/releases) is almost a year old
please run `flutter upgrade -f`

**Comment by TahaTesser** [comment]
Hi @araafat3 
Can you please upgrade to the latest  `stable` flutter channel and try again with the latest `local_auth: ^0.6.3+4`
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` the upgrade? 
Thank you

**Comment by araafat3** [comment]
Hi @TahaTesser 
I am using local_auth: ^0.6.3+4
and this issue still appear to me in mobile android version 6 and emulator android version 6

[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /var/www/html/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /data/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /data/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /data/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

**Comment by TahaTesser** [comment]
Hi @araafat3 
I can reproduce on the Android 6 emulator, it always returns false, this is a known [issue](https://github.com/flutter/flutter/issues/46227), which is just updated to better reflect the issue.

Please follow up on that issue, I'm closing the current one as a duplicate.  https://github.com/flutter/flutter/issues/46227
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by araafat3** [comment]
Hi @TahaTesser 
ok no problem and thank you
