### ISSUE TITLE
About androidx and support

### ISSUE THREAD

**Issue by slowguy** [flutter/flutter#74581]
I created a flutter module, run "flutter build aar", then i got a .aar file, now i have a problem that is my Android project is used Android support dependencies and seems there is some androidx dependencies in aar or "io.flutter:flutter_embedding_debug"...

I cant figure it out.

I changed the androidX options in my **pubspec.yaml** ,but seems nothing changed...
  module:
    androidX: false

**Comment by iapicca** [comment]
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
