### ISSUE TITLE
flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip

### ISSUE THREAD

**Issue by Homebrew1** [flutter/flutter#74591]
执行flutter doctor
资源错误
Failed to download https://mirrors.sjtug.sjtu.edu.cn//flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip.
Ensure you have network connectivity and then try again.
Exception: 404

**Comment by Homebrew1** [comment]
网络是正常的

**Comment by Homebrew1** [comment]
已解决

**Comment by shenzheniapps** [comment]
how to solved ?
