### ISSUE TITLE
fatal error: 'GoogleMaps/GoogleMaps.h' file not found

### ISSUE THREAD

**Issue by toan12520447** [flutter/flutter#74596]
Hi, 
I am building google_maps_flutter and got a problem "'GoogleMaps/GoogleMaps.h' file not found". 
Please help. Thank you so much.

**Comment by iapicca** [comment]
@toan12520447 
please try this possible [solution](https://github.com/react-native-maps/react-native-maps/issues/3175#issuecomment-556070823)
if the issue persists please provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by rymotion** [comment]
@toan12520447 make sure you check your cocoapods install and that it is up to date with your project. Worse case scenario you would need to clean build in XCode.

**Comment by pedromassangocode** [comment]
Hi @toan12520447  does any of the solutions above solved your issue?

**Comment by toan12520447** [comment]
flutter doctor -v on my mac: 

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/toantran/Desktop/CloneF/flutter
    • Framework revision 198df796aa (3 months ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/toantran/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Toan’s iPhone SE (mobile) • f431c931761951287d8a6e44d527422ae8d6a520 • ios • iOS 13.5.1

• No issues found!
Process finished with exit code 0

**Comment by toan12520447** [comment]
1. about this solution https://github.com/react-native-maps/react-native-maps/issues/3175#issuecomment-556070823,
target 'mainTargetTests' do
    inherit! :search_paths
    # Pods for testing
  end
-> I try to replace the current target with it, but it removed google Maps out my project. 
-> what are the search_paths? 
2. I use one target. 
Please help, Thank you.

**Comment by toan12520447** [comment]
Hi
Pedro Massango

 I still have issues, I reported it on github. Please help. Th
ank you.

**Comment by pedromassangocode** [comment]
Hi @toan12520447 
Can you please try the solution listed in https://github.com/flutter/flutter/issues/70895#issuecomment-744734693? If it does not solve the issue, can you please run `flutter run --verbose` and provide the logs once the issue reproduces?
Thank you

**Comment by toan12520447** [comment]
Hi, I try to the solution listed in https://github.com/flutter/flutter/issues/70895#issuecomment-744734693
It still can not work. 
I send to you my console log of command flutter run --verbose, please help.

[flutter.txt](https://github.com/flutter/flutter/files/5873846/flutter.txt)

**Comment by pedromassangocode** [comment]
Hi @toan12520447 
Make sure you run that command in the root directory of your project.

**Comment by toan12520447** [comment]
Hi @pedromassangocode,
I remember that I run it in the root directory of my project. I will do it and send you the console log again. 
I am afraid that incompatible between Xcode and android studio. I use Xcode 12.1.

**Comment by toan12520447** [comment]
Hi @pedromassangocode, I send you that console log of command flutter run --verbose
[
[flutter_command.txt](https://github.com/flutter/flutter/files/5897318/flutter_command.txt)
](url)

**Comment by alfonsoterron** [comment]
Hi @cyanglaz and @pedromassangocode,

I am getting same issue and starting a beta testing :S.

What's the status about it?

Is there some workaround?

Thank you for your hard work!

**Comment by foxmind1** [comment]
This answer worked for me
https://stackoverflow.com/a/75501503/11938374

**Comment by jmagman** [comment]
@foxmind1 if that worked, what actually changed in the project?  Did source control give any hints?

**Comment by foxmind1** [comment]
@jmagman I don't really remember sorry, and i think there's a good chance that the change was ignored anyway.

**Comment by jmagman** [comment]
I don't know why this issue is still open, it seems unactionable since we don't know what happened or what caused the original report. @bachtiyar93 can you file a new issue and give us reproduction steps?  There are a bunch of reasons this could happen, many of which were likely fixed since 2021, and I'd like to track your issue down particularly.
