### ISSUE TITLE
Texts are invisible on Flutter web

### ISSUE THREAD

**Issue by berkipekoglu** [flutter/flutter#74603]
After updating Flutter, I am getting an error on the WEB.
Texts aren't visible. Not because of its color. I think there is something wrong with the Flutter WEB. Does anyone have an idea?

![1](https://user-images.githubusercontent.com/70268103/105640507-8040d980-5e8f-11eb-8ff1-844e8e83c73e.png)
![2](https://user-images.githubusercontent.com/70268103/105640509-81720680-5e8f-11eb-94e5-86cdd027c96d.png)

**_- I added a button._**

![3](https://user-images.githubusercontent.com/70268103/105640510-81720680-5e8f-11eb-8ed7-9d65366328df.png)
![4](https://user-images.githubusercontent.com/70268103/105640511-820a9d00-5e8f-11eb-9e4b-b6e574330c95.png)

**Comment by iapicca** [comment]
@berkipekoglu 
can you provide a `copy-paste-able` [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) instead of a screenshot

**Comment by berkipekoglu** [comment]
@iapicca 
Oh sure

### Main.dart

``` dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.white,
        child: Column(
          children: [
            Row(
              children: [
                SizedBox(
                  height: 80,
                  width: 100,
                  child: Image.asset("assets/logo.png"),
                ),
                Text(
                  "Berk",
                  style: TextStyle(color: Colors.black),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by pedromassangocode** [comment]
I'm able to reproduce this issue on latest master channel. The issues does not reproduces on Dev channel!

## Left: Beta VS Right: Master channels
![Screen Shot 2021-01-25 at 15 47 50](https://user-images.githubusercontent.com/67424416/105721568-ffccb800-5f24-11eb-986e-662ae0a4603f.png)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Scaffold(
      body: Container(
        color: Colors.white,
        child: Column(
          children: [
            SizedBox(
              height: 80, width: 100,
            ),
            Text("Berk",
              style: TextStyle(color: Colors.black),
            ),
            Text("Flutter ",
              style: TextStyle(color: Colors.red),
            ),

            Text("Berk",
              style: TextStyle(color: Colors.green),
            ),

            Text("Berk",
              style: TextStyle(color: Colors.blue),
            ),
          ],
        ),
      ),
    ),
  ));
}
```
</details>

**Comment by berkipekoglu** [comment]
I ran it on the beta channel without any problems. So thank you. I am grateful to you. Thanks for your help.
