### ISSUE TITLE
Can‘t input character in Text Fields

### ISSUE THREAD

**Issue by jet10000** [flutter/flutter#7460]
<img width="371" alt="qq20170112-1 2xxxxx" src="https://cloud.githubusercontent.com/assets/2258120/21884629/0dfbf5aa-d8ef-11e6-9a99-9183b9e94320.png">

**Comment by eseidelGoogle** [comment]
May be related to https://github.com/flutter/flutter/issues/7459 or https://github.com/flutter/flutter/issues/6939.

**Comment by eseidelGoogle** [comment]
@cbracken is working on re-writing our iOS input and may fix this.

**Comment by cbracken** [comment]
Fixed by flutter/engine#3586
