### ISSUE TITLE
flutter build web have issue when deploy to server

### ISSUE THREAD

**Issue by tripgame262** [flutter/flutter#74608]
In my server
Uncaught ReferenceError: Hello is not defined
    at main.dart.js:1

In my localhost

Failed to load resource: the server responded with a status of 404 (Not Found)
manifest.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
<img width="513" alt="Screen Shot 2564-01-25 at 01 56 03" src="https://user-images.githubusercontent.com/47244124/105643026-007f3300-5ec0-11eb-9ff7-db000af93be0.png">

<img width="517" alt="Screen Shot 2564-01-25 at 03 44 23" src="https://user-images.githubusercontent.com/47244124/105643030-037a2380-5ec0-11eb-9ce8-72ffc0e5dccd.png">

**Comment by iapicca** [comment]
@tripgame262 
can you follow these steps:

1. [install Dart SDK](https://dart.dev/get-dart#install)
2. [update your path](https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path)
3. run the commands below
```console
pub global activate dhttpd
flutter create counter_app
cd counter_app
flutter build web --release
cd build/web
dhttpd --port 8888
```
4. paste `localhost:8888` in your browser
5. provide `dhttpd` logs and your `flutter doctor -v`

**Comment by tripgame262** [comment]
> @tripgame262
> can you follow these steps:
> 
> 1. [install Dart SDK](https://dart.dev/get-dart#install)
> 2. [update your path](https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path)
> 3. run the commands below
> 
> ```
> pub global activate dhttpd
> flutter create counter_app
> cd counter_app
> flutter build web --release
> cd build/web
> dhttpd --port 8888
> ```
> 
> 1. paste `localhost:8888` in your browser
> 2. provide `dhttpd` logs and your `flutter doctor -v`

It's work fine on dhttpd -> localhost:8888 but I try deploy to my server [apache] it not working.

**Comment by tripgame262** [comment]
I change <base href=''/> to my domain name. The issue is solved.
