### ISSUE TITLE
BorderRadius.copyWith is missing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#74613]

**Comment by thisisamank** [comment]
Hi, @pedromassangocode I would like to implement this, can you assign this to me?

**Comment by MrBirb** [comment]
@HansMuller your PR was merged. Should this be closed?

**Comment by HansMuller** [comment]
@MrBirb thanks for the heads-up.

Fixed by @thisisamank in https://github.com/flutter/flutter/pull/75340
