### ISSUE TITLE
org.gradle.wrapper.Download.downloadInternal

### ISSUE THREAD

**Issue by Homebrew1** [flutter/flutter#74619]
flutter run
Exception in thread "main" java.net.ConnectException: Operation timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)        
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)   
        at java.net.Socket.connect(Socket.java:607)                     
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)      
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)  
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)  
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)       
        at org.gradle.wrapper.Install$1.call(Install.java:61)           
        at org.gradle.wrapper.Install$1.call(Install.java:48)           
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)       
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
据说是gradle的问题，但是修改了配置没有作用

**Comment by iapicca** [comment]
@Homebrew1 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Homebrew1** [comment]
flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-13.0.pre.120, on Mac OS X 10.13.6 17G65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-13.0.pre.120 at /Users/mac/Flutter
    • Framework revision 46b0797b58 (3 days ago), 2021-01-22 14:48:49 +0500
    • Engine revision 90641fa923
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)
    • Pub download mirror https://dart-pub.mirrors.sjtug.sjtu.edu.cn
    • Flutter download mirror https://mirrors.sjtug.sjtu.edu.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.96
flutter run -v
/Users/mac/Flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/_s/jngzbhqx4pgf_n0t389c55hw0000gn/T/flutter_tools.WrMS4f/flutter_tool.KLagSC/app.dill --packages
/Users/mac/AndroidStudioProjects/flutter_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +48 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +30 ms] <- compile package:flutter_app/main.dart
[  +91 ms] --------- beginning of kernel
           01-25 20:10:44.020 I/init    (    0): Untracked pid 9942 received signal 1
[  +74 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb version
[  +48 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /Users/mac/Library/Android/sdk/platform-tools/adb
[   +6 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb start-server
[  +32 ms] Building APK
[  +53 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew.
[  +29 ms] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew mode: 33261 rwxr-xr-x.
[ +590 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +22 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"MainClass":"com.intellij.idea.Main","ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/C
ontents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.
jar","JVMVersion":"1.8*,1.8+","Properties":{"idea.home.path":"$APP_PACKAGE\/Contents","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.paths.selector":
"AndroidStudio4.1","idea.vendor.name":"Google"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.41.7042882","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in
Android Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeExtensions":["ipr"],"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeIconFile":"studio.icns","CFBundleTypeRole":"Editor"},{"CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"LSTypeIsPackage":false,"CFBundleTypeNa
me":"All
documents","CFBundleTypeRole":"Editor"}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":t
rue,"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's
location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"],"CFBundleTypeRole":"Editor"}],"CFBundleIdent
ifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFo
lderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio
requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network
volume.","CFBundleGetInfoString":"Android Studio 4.1, build AI-201.8743.12.41.7042882. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An
application in Android Studio requests access to files on a removable volume."}
[  +50 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +127 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +3 ms] executing: [/Users/mac/AndroidStudioProjects/flutter_app/android/] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=/Users/mac/AndroidStudioProjects/flutter_app/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Pdart-defines=FLUTTER_WEB_AUTO_DETECT%3Dtrue assembleDebug
[ +327 ms] Downloading https://services.gradle.org/distributions/gradle-6.7-all.zip
在这个位置卡住了，请问是gradle安装不上吗

**Comment by Homebrew1** [comment]
[  +41 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +39 ms] <- compile package:flutter_app/main.dart
[ +150 ms] --------- beginning of main
                    01-25 20:27:34.354 W/GAv4-SVC( 2071): Network compressed POST connection error: java.net.UnknownHostException: Unable to resolve host
                    "ssl.google-analytics.com": No address associated with hostname
[  +61 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb version
[  +34 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /Users/mac/Library/Android/sdk/platform-tools/adb
[   +8 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb start-server
[  +61 ms] Building APK
[  +61 ms] Running Gradle task 'assembleDebug'...
[  +16 ms] Using gradle from /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew.
[   +1 ms] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew mode: 33261 rwxr-xr-x.
[ +624 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +27 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[   +1 ms] {"CFBundleName":"Android
Studio","JVMOptions":{"MainClass":"com.intellij.idea.Main","ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/C
ontents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.
jar","JVMVersion":"1.8*,1.8+","Properties":{"idea.home.path":"$APP_PACKAGE\/Contents","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.paths.selector":
"AndroidStudio4.1","idea.vendor.name":"Google"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.41.7042882","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in
Android Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeExtensions":["ipr"],"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeIconFile":"studio.icns","CFBundleTypeRole":"Editor"},{"CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"LSTypeIsPackage":false,"CFBundleTypeNa
me":"All
documents","CFBundleTypeRole":"Editor"}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":t
rue,"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's
location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"],"CFBundleTypeRole":"Editor"}],"CFBundleIdent
ifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFo
lderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio
requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network
volume.","CFBundleGetInfoString":"Android Studio 4.1, build AI-201.8743.12.41.7042882. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An
application in Android Studio requests access to files on a removable volume."}
[  +30 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +152 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +6 ms] executing: [/Users/mac/AndroidStudioProjects/flutter_app/android/] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=/Users/mac/AndroidStudioProjects/flutter_app/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Pdart-defines=FLUTTER_WEB_AUTO_DETECT%3Dtrue assembleDebug
[+120349 ms] Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file:
/Users/mac/.gradle/wrapper/dists/gradle-6.7-all/cuy9mc7upwgwgeb72wkcrupxe/gradle-6.7-all.zip
[   +3 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
[        ]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[        ]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[        ]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +45 ms] Running Gradle task 'assembleDebug'... (completed in 121.2s)
[   +8 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[+1016 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] Using gradle from /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew.
[        ] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/mac/AndroidStudioProjects/flutter_app/android/] /Users/mac/AndroidStudioProjects/flutter_app/android/gradlew -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=/Users/mac/AndroidStudioProjects/flutter_app/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Pdart-defines=FLUTTER_WEB_AUTO_DETECT%3Dtrue assembleDebug
[ +239 ms] Downloading https://services.gradle.org/distributions/gradle-6.7-all.zip
最后面几行是报错位置

**Comment by pedromassangocode** [comment]
Hi  @Homebrew1 
This seems to be an internet connection issue.

Can you please run `flutter run --verbose >> logs.txt`? this command will generate a logs.txt file in the directory where you run this command, please provide that same file.
Thank you

**Comment by Homebrew1** [comment]
[logs.txt](https://github.com/flutter/flutter/files/5866763/logs.txt)
English is difficult
Maybe it's a proxy problem. I can't get gradle's package
Thank you for your answer，But I really only know Chinese
谢谢

**Comment by Homebrew1** [comment]
@pedromassangocode I pay attention to you. I hope you can be my teacher

**Comment by pedromassangocode** [comment]
Hi @Homebrew1 
Looks like the download has completed successfully. 

```
[ +773 ms] Welcome to Gradle 6.7!
[        ] Here are the highlights of this release:
[        ]  - File system watching is ready for production use
[        ]  - Declare the version of Java your build requires
[        ]  - Java 15 support
[        ] For more details see https://docs.gradle.org/6.7/release-notes.html
[ +297 ms] Starting a Gradle Daemon (subsequent builds will be faster)
```

Are you still facing this issue?

This definitely seems to be an internet connection issue.

**Comment by Homebrew1** [comment]
@pedromassangocode There was a pause for many seconds, but there was no pause when downloading other packages

**Comment by pedromassangocode** [comment]
Are you able to provide the full logs?
