### ISSUE TITLE
flutter-devicelab-windows-{1,2} reporting as timed-out, not running tests.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#74612]
The last commit with these bots running was https://github.com/flutter/flutter/commit/c87f15fe094b5645305efd4cc638fc17788eab30. Since that commit was red, the tree is closed and won't re-open before those columns are green again.

**Comment by keyonghan** [comment]
Recovered these windows bots. Waiting for the task picked up.

**Comment by zanderso** [comment]
It looks like the tasks are failing with:
```
ERROR: FileSystemException: Deletion failed, path = 'C:\Users\flutter\.cocoon\flutter' (OS Error: Access is denied.
, errno = 5)
```

**Comment by keyonghan** [comment]
Task failed with

```
Task failed with the following reason:
ERROR: FileSystemException: Deletion failed, path = 'C:\Users\flutter\.cocoon\flutter' (OS Error: Access is denied.
, errno = 5)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      rrm (package:cocoon_agent/src/utils.dart:148:35)
#3      getFlutter (package:cocoon_agent/src/utils.dart:508:5)
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
```

@yusufm @godofredoc do we have any recent changes on Windows bots?

**Comment by keyonghan** [comment]
The above error happens on only Windows2 btw.

**Comment by keyonghan** [comment]
Disabling window2 for now, and rerun tasks for win1 to pick up.

**Comment by yusufm** [comment]
No recent changes on windows that I know off. Keep win2 offline, I will work on salt states for win today and use win2 as a testbed.

**Comment by godofredoc** [comment]
Seems like we are leaking processes that are preventing some files to be deleted because they are still in use.

**Comment by keyonghan** [comment]
Manually rm the directory brings win2 back.
