### ISSUE TITLE
Plugin will not attach to enginge when using Kotlin 1.3.50 and Coroutines greater than 1.3.6

### ISSUE THREAD

**Issue by shrektrumpet** [flutter/flutter#74624]
Flutter doctor (Android Studio Plugins installed):
![image](https://user-images.githubusercontent.com/77962639/105688076-7653c080-5ef9-11eb-989e-42dee89dda6f.png)

The problem occurred while using Kotlin coroutines in one of our Flutter plugins.

How to reproduce:
1.	Create Flutter Plugin (-a kotlin) 
 
![image](https://user-images.githubusercontent.com/77962639/105688153-8bc8ea80-5ef9-11eb-87bd-a4435bc22c1d.png)

2.	Add Kotlin Coroutines dependencies to build.gradle
 
![image](https://user-images.githubusercontent.com/77962639/105688167-8ff50800-5ef9-11eb-820f-ec0fc1599032.png)

3.	Add Coroutine dependencies and a coroutine to the getPlatformVersion call
 
![image](https://user-images.githubusercontent.com/77962639/105688199-98e5d980-5ef9-11eb-89a6-9cec34b28392.png)

Running the example app of the plugin now prints “World!” as expected.
4.	Reference the call or result variable
 
![image](https://user-images.githubusercontent.com/77962639/105688219-9edbba80-5ef9-11eb-9b08-30a9f02846d9.png)

5.	Run the example app

We get a MissingPluginException because the plugin will not be attached to the flutter engine
 
![image](https://user-images.githubusercontent.com/77962639/105688229-a307d800-5ef9-11eb-8461-e80fcf6b621f.png)

This error occurs with Kotlin version 1.3.50 and Coroutine version 1.4.2
Change Kotlin version to 1.3.60 in the example app 
 
![image](https://user-images.githubusercontent.com/77962639/105688242-a733f580-5ef9-11eb-8c8f-09c93b33acee.png)

Rerun the example app and it runs as intended
Same with changing the Coroutine versions to 1.3.6 and keeping the Kotlin version to 1.3.50 
 
![image](https://user-images.githubusercontent.com/77962639/105688257-ab601300-5ef9-11eb-9b13-9100449f73c2.png)

The Coroutine version 1.4.2 only needs a Kotlin version greater than 1.3, which works fine in an Android app but not in Flutter.
So I assume something is wrong with Flutter here. I would highly appreciate feedback regarding this topic.

**Comment by TahaTesser** [comment]
Hi @shrektrumpet 
Actual code is always better than low-res  screenshots, to better address please provide a reproducible code sample in a repository in this case  and  `flutter run --verbose` logs
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
