### ISSUE TITLE
unable to check version or even upgrade it

### ISSUE THREAD

**Issue by Varun11940** [flutter/flutter#74628]
-Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
 its showing me this error continuosly

**Comment by pedromassangocode** [comment]
Hi @Varun11940 
Can you please provide your `flutter doctor -v` and the full logs of the command you are using?
Thank you

**Comment by Varun11940** [comment]
I just used two commmands first one is you mentioned it and second was
flutter --version

**Comment by pedromassangocode** [comment]
Hi @Varun11940 
Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by Varun11940** [comment]
sir i am new to this can you please instruct me on how to provide full logs

**Comment by pedromassangocode** [comment]
Hi @Varun11940 
You just run `flutter doctor -v` in Terminal and provide what it prints.

**Comment by Varun11940** [comment]
sir thanks to you my initial problem was solved but a new issue arose


Exception in thread "main" java.lang.NoClassDefFoundError:
javax/xml/bind/annotation/XmlSchema
        at
com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at
com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at
com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at
com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at
com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException:
javax.xml.bind.annotation.XmlSchema
        at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by pedromassangocode** [comment]
> sir thanks to you my initial problem was solved but a new issue arose

Hi @Varun11940 
Given your last message I feel safe to close this issue. Please open a new issue as we don't track more than one issue in the same ticket. 
Thank you

**Comment by Varun11940** [comment]
thank you, sir, for helping
