### ISSUE TITLE
☂️  Investigate performance differences between pipeline state object creation in OpenGL and Metal.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#74631]
This is an umbrella issue issue to investigate if there is a performance difference between the OpenGL and Metal backends when the pipeline state objects are being constructed, to quantify those differences and track any work necessary to bring parity between the two. Specifically, this is related to the work done in `GrMtlPipelineStateBuilder::finalize`. The scope of this issue is limited to ensuring parity between the backends. Moving the work outside the frame workload [is tracked here](https://github.com/flutter/flutter/issues/74630). More context in the original issue asking for an [investigation on Metal Binary Archives](https://github.com/flutter/flutter/issues/60267#issuecomment-762786388).

**Comment by zanderso** [comment]
Closing this as obsoleted by past and upcoming work on Impeller.
