### ISSUE TITLE
FlutterView crash with a descprition of CALayer position contains NaN

### ISSUE THREAD

**Issue by daselangzhuang1989** [flutter/flutter#74638]
## Steps to Reproduce

git clone https://github.com/klaus01/iOS_Flutter.git
cd iOS_Flutter/my_flutter
flutter pub get
cd ..
pod install
open iOS_Flutter.xcworkspace

Add flutterVC as childController of a custom controller

**Expected results:** flutter displayed with position {0, 0}

**Actual results:** flutter displayed with position {inf, inf}

<details>

![image](https://user-images.githubusercontent.com/10403123/105724179-8b186e80-5f62-11eb-9cfe-a5fdb9efe830.png)

After add the code below, this crash is fixed

![image](https://user-images.githubusercontent.com/10403123/105723623-f3b31b80-5f61-11eb-8417-b4a09b059933.png)

I doubt there is a bug in flutterview initwithframe, and initial value probally {inf, inf},can you figure out why this happened?

</details>

**Comment by darshankawar** [comment]
@daselangzhuang1989 
I cloned your repo and followed your steps, but getting below error while running `pod install`:

```
dhs@Dhss-MacBook-Pro iOS_Flutter % pod install

[!] Invalid `Podfile` file: cannot load such file -- ./my_flutter/.ios/Flutter/podhelper.rb.

 #  from /Users/dhs/Documents/NCFlutter/iOS_Flutter/Podfile:5
 #  -------------------------------------------
 #  flutter_application_path = './my_flutter/'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #  
 #  -------------------------------------------
dhs@Dhss-MacBook-Pro iOS_Flutter % 
```

Also, can you provide `flutter doctor -v` and details around how to `Add flutterVC as childController of a custom controller`

**Comment by lipnpn** [comment]
Mee too.

UncaughtException=>CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [-inf nan]' =>CoreFoundation=>___exceptionPreprocess

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ldhlfzysys** [comment]
try set FlutterViewController.view.frame = CGRectMake(0,0,0,0)

the origin value is (inf,inf,0,0)

@daselangzhuang1989
