### ISSUE TITLE
Flutter ios App crashes on Google Sign In cancel click 

### ISSUE THREAD

**Issue by jainvipin69** [flutter/flutter#74634]
Hi, 

we have setup google sign in our flutter ios app and have followed all the steps.

when we click on the button it opens a dialog confirmation, on click of cancel the app crashes. Also if we complete the sign in process the app crashes. 

Version: 4.5.9
Flutter version 1.22.5 stable

**Comment by TahaTesser** [comment]
Hi @jainvipin69 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` with the crash logs, your `pubspec.yaml`  and a complete reproducible minimal code sample
Thank you

**Comment by jainvipin69** [comment]
[details.docx](https://github.com/flutter/flutter/files/5866922/details.docx)
Please find attached the details requested

**Comment by jainvipin69** [comment]
Code Snippet:

Initialization
GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: [
      'email',
      'https://www.googleapis.com/auth/contacts.readonly',
    ],
    hostedDomain: '',
  );

Use:
Future<void> googleLogin() async {
    try {
      final GoogleSignInAccount profile = await _googleSignIn.signIn();
    } on PlatformException catch(e){
      print('error caught: $e');
    } catch (e){
      print('error caught: $e');
    }
  }

**Comment by TahaTesser** [comment]
Hi @jainvipin69 
Using your code snippet, I created a code sample below, clicking or logging in on a physical device or simulator, no crash, your logs also don't show anything helpful with the crash.  Can you try the code sample below, if the app crashes. Please open the ios folder of your project from Xcode, run it from Xcode, there will be crash logs there, please provide those logs.

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/105817407-922f9300-5fdb-11eb-8e6a-0332e8f5b027.gif)



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: [
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
  hostedDomain: '',
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  Future<void> googleLogin() async {
    try {
      final GoogleSignInAccount profile = await _googleSignIn.signIn();
    } on PlatformException catch (e) {
      print('error caught: $e');
    } catch (e) {
      print('error caught: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          await googleLogin();
        },
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.3

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by jainvipin69** [comment]
Could you please what other configurations you did, I mean on info.plist and others

**Comment by jainvipin69** [comment]
The only error that I see from Xcode is
Error Domain=com.google.GIDSignIn Code=-5 "The user canceled the sign-in flow." UserInfo={NSLocalizedDescription=The user canceled the sign-in flow.}

Lost connection to the device and app crashes, there is no further logs.

**Comment by TahaTesser** [comment]
Hi @jainvipin69 
Used the [config](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example/ios/Runner) as the official example 

Which device are you using to reproduce this issue?  Can you reproduce on the simulator as well? 
https://github.com/flutter/flutter/issues/44431 only throws an exception, doesn't crash the app. 
Can you run the code sample I provided in https://github.com/flutter/flutter/issues/74634#issuecomment-767374921 from Xcode and provide complete crash logs 
Thank you

**Comment by jainvipin69** [comment]
Hi Taha,

I checked the independent code from my project and it works fine, however on calling the code from main.dart it is failing. We are checking things at our end. Thanks so far for the support.

**Comment by jainvipin69** [comment]
The issue has been solved, we were initialising FlutterDownloader in our main method which was somehow troubling the google sign in. I do not why it was causing issue but for now our issue is solved.

Thanks again.

**Comment by jainvipin69** [comment]
The issues is because of flutter_downloader, if I remove the app works fine, but with 
FlutterDownloader.initialize(); this line the google sign in crashes my app.
Could you please explain or advice when will a fix be available.

**Comment by TahaTesser** [comment]
@jainvipin69 
It's a third-party package causing the issue, I suggest you raise this issue on their dedicated GitHub, you can find it from pub.dev page and try alternative packages in the mean time. 

Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by aakrutibeladiya** [comment]
Hello, 
Im not using flutter_downloader and still there is issue, 
i dont understand the error , does anyone have idea
