### ISSUE TITLE
The issue was: How to Change onAcitvityResult ,Please help

### ISSUE THREAD

**Issue by Aashutosh3804** [flutter/flutter#74639]
The issue was:

01. Add Permission in Manifest : `<uses-permission android:name="android.permission.CAMERA"/>`

02. Change `onActivityResult(requestCode: Int, resultCode: Int, data: Intent)` to 
`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)`

_Originally posted by @pacifire in https://github.com/flutter/flutter/issues/63172#issuecomment-670940436_

**Comment by iapicca** [comment]
@Aashutosh3804 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@Aashutosh3804 
Your question is better suited for StackOver flow. Please follow above referred link to get better traction for your question.
Closing from here, as this isn't an issue or feature request for framework, but more of a support question.
