### ISSUE TITLE
Mac iOS Engine timeout during "OS info" step

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#74642]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/8663/overview

I will land a new PR to see if this is transient.

**Comment by keyonghan** [comment]
This seems to be an expected timeout after running 90 min: https://devops-console-oss.corp.google.com/flutter/infra/+/master:config/engine_config.star;l=389.

**Comment by keyonghan** [comment]
Took a deeper look at this build, and compared it with a successful build. Some major differences happen on `build` related steps. For example:

build 8663 v.s. build8701

- 18. build ios_debug_sim 3 mins 11 secs v.s. 1 min 11 secs
- 22. build host_debug_unopt 7 mins v.s. 4 mins 58 secs
- 31. build ios_debug 28 mins 40 secs v.s. 17 mins 44 secs
- 32. build ios_debug_arm 27 mins 51 secs v.s. 17 mins 28 secs

sounds like bot running slow for the timeout build.

**Comment by godofredoc** [comment]
We may still have some vms in the pool that may be slower than the other machines. Can we verify if is this the problem?

**Comment by keyonghan** [comment]
All our mac bots are real for both prod and try.

**Comment by godofredoc** [comment]
> All our mac bots are real for both prod and try.

What about the versions? we may still have a mix of old and new hardware

**Comment by keyonghan** [comment]
Yes, we have a mix of two mac models: 
prod pool: 11 Macmini7, 37 Macmini8.
try pool: 5 Macmini7, 80 Macmini8.

**Comment by godofredoc** [comment]
I assume that we can correlate the longer execution times to the old machines, am I correct?

**Comment by keyonghan** [comment]
Confirmed those timeout builds ran on macmini7. Seems we need to replace them with macmini8 ones.

**Comment by godofredoc** [comment]
Can we add the Macmini8 dimension to engine builds? that will ensure that we are using only new hardware for resource intensive tasks.

**Comment by keyonghan** [comment]
Timeout builders have been switched to use Macmini8 only, and the issue should be resolved. Please reopen if still any issues.
