### ISSUE TITLE
Regression in benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#74649]
Regressions occur in the following:

* text_canvas_cached_layout.html.layout.average 
* text_canvas_color_grid.html.text_layout.average 
* text_dom_cached_layout.html.layout.average 
* text_dom_color_grid.html.text_layout.outlierRatio

See https://flutter-flutter-perf.skia.org/e/?begin=1610648124&end=1611361782&keys=X744151f3a1869facf837e9d3ae711558&requestType=0&xbaroffset=23230.

May be related to https://github.com/flutter/flutter/issues/74648; regressions occurred in the roll  #74126 for other benchmarks.

**Comment by yjbanov** [comment]
I think the regression happened in https://github.com/flutter/flutter/pull/74078, not https://github.com/flutter/flutter/pull/74126.

**Comment by mdebbar** [comment]
@yjbanov yes the regression happened in https://github.com/flutter/flutter/pull/74078.

This benchmark is measuring two things:
1. Duration of drawing the entire frame.
2. Duration of the text layout portion of the frame.

It does the above twice. Once with Dom measurement and once with Canvas measurement. Now both are replaced by a new implementation that supports rich text, so the benchmark numbers converged:
![image](https://user-images.githubusercontent.com/1278212/105754269-b5d0db80-5efe-11eb-8d25-50baf594aed0.png)

As seen in the screenshot, the new implementation is only slightly worse than the Canvas measurement, but still orders of magnitude better than Dom measurement.

<hr>

When we look at the big picture, the entire frame duration numbers have converged too (Dom vs Canvas). The difference between the new numbers and the old Canvas numbers is negligible. See the pink and orange lines:

![image](https://user-images.githubusercontent.com/1278212/105755331-0268e680-5f00-11eb-8c07-24ea7b51c4c2.png)

That said, I believe there are opportunities to improve the performance of the new text layout implementation. So I'll keep this issue open and reduce the priority.
