### ISSUE TITLE
Execution failed for task ':app:processDebugResources'. > AAPT: error: unexpected element <queries> found in <manifest>.

### ISSUE THREAD

**Issue by sadaqatkarimi** [flutter/flutter#74647]
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\sadaq\.gradle\caches\transforms-2\files-2.1\a3b8085db30285646632e9aaa0c95070\play-services-ads-lite-19.6.0\AndroidManifest.xml:27:5-38:15: AAPT: error: unexpected element <queries> found in <manifest>.

**Comment by iapicca** [comment]
@sadaqatkarimi 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@sadaqatkarimi 
Along with above requested details, can you also provide the gradle version you are using ? Check [this](https://stackoverflow.com/a/62969918) SO answer and see if it helps to resolve your issue.

**Comment by sadaqatkarimi** [comment]
i solve this problem by upgrading android gradle version to gradle-6.5 and plugin version to 4.1.1
