### ISSUE TITLE
Remove BM_StyledRunsGetRun

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#74650]
See https://flutter-engine-perf.skia.org/e/?begin=1611107042&end=1611167642&keys=X3d1a3d68fd0a4ed1cbfb19af6d60c95d&num_commits=50&request_type=1&xbaroffset=21035.

Started with the Dart roll https://github.com/flutter/engine/pull/23791, which is goofy, because that's a revert.

May need help from someone on @a-siva's team to help us pin this down.

**Comment by chinmaygarde** [comment]
The benchmark measures what is effectively a constant time operation. The time went from 2 to 3 ns.

**Comment by chinmaygarde** [comment]
Since this is not measuring anything useful, I vote we repurpose this issue to remove the benchmark.
