### ISSUE TITLE
'package:flutter/src/rendering/binding.dart': Failed assertion: line 308 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.

### ISSUE THREAD

**Issue by harshabhadra** [flutter/flutter#74651]

**Comment by toimc** [comment]
Same question here.

**Comment by darshankawar** [comment]
@harshabhadra 
Please elaborate on the issue you are facing. Check [this](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) link and provide the requested details to better address the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by timobaehr** [comment]
If I add a PersistentFrameCallback inside a StatefulWidget's State, then we can see this crash.

```dart
class ExampleState<T extends StatefulWidget> extends State<T> {
  @override
  void initState() {
    WidgetsBinding.instance.addPersistentFrameCallback((timeStamp) {}
  }
}
```

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 326 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:326:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:321:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
...
====================================================================================================
```

**Comment by pedromassangocode** [comment]
@timobaehr 
Please file a new issue as suggested in the comment above yours.
Thank you

> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

**Comment by kamleshwebtech** [comment]
`'package:flutter/src/rendering/binding.dart': Failed assertion: line 325 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.`

How to check and fix this issue. Kindly suggest. Thanks.

**Comment by subinspathilettu** [comment]
Any update on this issue. I am also facing the same.

`======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.`

**Comment by nxcco** [comment]
Same issue here. When adding a persistent frame callback inside a stateful widget, the error shows. The assertion which is not true can be found here: https://github.com/flutter/flutter/blob/76b2f987b0203e0848e4ba1f23b5dd8c593b92ff/packages/flutter/lib/src/rendering/binding.dart#L336

**Comment by lxzh** [comment]
Is there any progress on this issue recently?

**Comment by Auridel** [comment]
Same issue. Does anyone know how to fix this?

`======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:334:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
...
====================================================================================================`
