### ISSUE TITLE
video_player plugin throws exception when flutter_facebook_auth or flutter_play_asset plugins are included in pubspec

### ISSUE THREAD

**Issue by deepikanathan** [flutter/flutter#74678]

**Comment by darshankawar** [comment]
@deepikanathan 
What exception does the plugin throw ? Can you provide `flutter doctor -v` and plugin version you are using ?
Also, provide a complete minimal reproducible code sample that shows the issue.
Also, both the plugins you mentioned are 3rd party. You may want to open this issue in respective plugin repo if you think only these plugins are causing the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
