### ISSUE TITLE
App-debug is working fine. But app-release is not working as expected.

### ISSUE THREAD

**Issue by yannainghtun-mk** [flutter/flutter#74698]
After app-release,
CachedNetworkImage is not working.
ImagePicker is not working.
Goto next screen is not working.
And AnimatedList is not working.
What is going on?

I have used firebase.

**Comment by yannainghtun-mk** [comment]
flutter run --release




Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
E/flutter (22654): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (22654): 
E/flutter (22654): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)
E/flutter (22654): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
E/flutter (22654): <asynchronous suspension>
E/flutter (22654): #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:73)
E/flutter (22654): <asynchronous suspension>
E/flutter (22654): #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:28)
E/flutter (22654): <asynchronous suspension>
E/flutter (22654): #3      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:33)
E/flutter (22654): <asynchronous suspension>
E/flutter (22654): #4      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:7)
E/flutter (22654): <asynchronous suspension>
E/flutter (22654): 
I/flutter (22654): Invalid argument (message): Must be a String: null
I/flutter (22654): #0      log (dart:developer-patch/developer.dart:36)
I/flutter (22654): #1      new _ChaterState (package:hindu_youth_society/pages/chater.dart:35)
I/flutter (22654): #2      Chater.createState (package:hindu_youth_society/pages/chater.dart:28)
I/flutter (22654): #3      new StatefulElement (package:flutter/src/widgets/framework.dart:4774)
I/flutter (22654): #4      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:918)
I/flutter (22654): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3620)
I/flutter (22654): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4857)
I/flutter (22654): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4848)
I/flutter (22654): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4857)
I/flutter (22654): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4848)
I/flutter (22654): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4857)
I/flutter (22654): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #54     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4848)
I/flutter (22654): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6174)
I/flutter (22654): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4857)
I/flutter (22654): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4848)
I/flutter (22654): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4857)
I/flutter (22654): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)
I/flutter (22654): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4664)
I/flutter (22654): #94     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4848)
I/flutter (22654): #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4659)
I/flutter (22654): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3625)
I/flutter (22654): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3390)
I/flutter (22654): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4710)
I/flutter (22654): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:4379)

**Comment by pedromassangocode** [comment]
Hi @yannainghtun-mk 
For the shared_preferences plugin, please see https://github.com/flutter/flutter/issues/66833.
For the path_provider plugin, see https://github.com/flutter/flutter/issues/46679, and see https://github.com/flutter/flutter/issues/46679#issuecomment-749699122 for a workaround for this problem.


For the Framework logs:

```console
I/flutter (22654): Invalid argument (message): Must be a String: null
I/flutter (22654): #0 log (dart:developer-patch/developer.dart:36)
I/flutter (22654): #1 new _ChaterState (package:hindu_youth_society/pages/chater.dart:35)
I/flutter (22654): #2 Chater.createState (package:hindu_youth_society/pages/chater.dart:28)
```

Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that does not uses any third-party plugin/package?
Thank you

**Comment by yannainghtun-mk** [comment]
It is all working now. 
But image_picker is not working. Opened new issue.

**Comment by pedromassangocode** [comment]
Hi @yannainghtun-mk 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by yannainghtun-mk** [comment]
Close this it is solved.
