### ISSUE TITLE
flutter.new (dartpad) "hello world" example only renders "Hello" when zoomed != 100%

### ISSUE THREAD

**Issue by jensjoha** [flutter/flutter#74704]
When going to flutter.new and pressing the "run" button I get this:

![image](https://user-images.githubusercontent.com/20773519/105814644-005f6000-5fb2-11eb-83b3-13531aa23acc.png)

My browser is zoomed to 110%. Zooming to 100% shows the whole "Hello, World!", but 90%, 80%, 125% etc also shows only "Hello".

This is on a Chromebox with Chrome "Version 87.0.4280.142 (Official Build) (64-bit)".
I can't reproduce on my Linux desktop with Chrome "Version 88.0.4324.96 (Official Build) (64-bit)" though.

**Comment by iapicca** [comment]
@jensjoha 
this seems a [dartpad](https://github.com/dart-lang/dart-pad) problem, 
you may want to open the issue in the dedicated [github](https://github.com/dart-lang/dart-pad/issues)

**Comment by jensjoha** [comment]
I can certainly create an issue there, but my guess would be that dartpad just basically runs flutter on the code, and the resulting code has this issue. That would make it a flutter issue.

**Comment by darshankawar** [comment]
@jensjoha 
Tried your code sample using latest master on Flutter web `(Google Chrome 88.0.4324.96)` and zoomed to 125% and also to 90% and was able to see full text properly.

<img width="793" alt="Screenshot 2021-01-26 at 2 55 07 PM" src="https://user-images.githubusercontent.com/67046386/105826383-b17fed80-5fe6-11eb-8364-1334e11f49ab.png">

<img width="1056" alt="Screenshot 2021-01-26 at 2 55 20 PM" src="https://user-images.githubusercontent.com/67046386/105826393-b3e24780-5fe6-11eb-9a4d-43ea514972ba.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.177, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.177 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2eeeba9c09 (4 hours ago), 2021-01-25 20:52:30 -0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.

```

</details>

Hence, I'd suggest you to open this issue in dartpad repo as suggested above.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
