### ISSUE TITLE
Inconsistent behavior of `Listener` in a `Stack` with `Container` w/ and w/o `child`

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#74707]
## Steps to Reproduce

1. run  code sample and tap on the screen

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Stack(
            children: [for (var i = 0; i < 3; i++) MyListener(i)],
          ),
        ),
      ),
    );

class MyListener extends StatelessWidget {
  MyListener(this.index) : super(key: ValueKey('MyListener: $index'));
  final int index;
  @override
  Widget build(BuildContext context) => Center(
        child: Listener(
          behavior: HitTestBehavior.translucent,
          onPointerDown: (_) => print('$index'),
          child: Container(),
        ),
      );
}


```

</details>

<details>
  <summary>Logs</summary>

```bash
🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
2
1
0
2
1
0
2
1
0
2
1
0

Application finished.

```

</details>

2. modifie the code sample as indicated below and tap on the screen

```diff
          child: Container(
+            color: const Color.fromRGBO(200, 0, 0, .3),
          ),

```

or 

```diff
    child: Container(
+            child: FlutterLogo(),
          ),
```
          
<details>
  <summary>Logs</summary>

```bash
🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
2
2
2
```

</details>

**Expected results:**

the behavior should not change

**Actual results:** 

[Container](https://api.flutter.dev/flutter/widgets/Container-class.html) having a `color` or a `child` (and so on) breaks `HitTestBehavior.translucent`

<details>
  <summary>doctor</summary>
  
```console
[✓] Flutter (Channel master, 1.26.0-13.0.pre.178, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-13.0.pre.178 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 22f1700427 (84 minutes ago), 2021-01-26 14:34:03 +0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 88.0.4324.96 snap

! Doctor found issues in 1 category.

```

</details>

## Notes

**Possibly related issues:**

- this issue https://github.com/flutter/flutter/issues/72113 reports that [Container](https://api.flutter.dev/flutter/widgets/Container-class.html) is removing childrens from the widget tree

**References:**
- the issue has been initially reported [here](https://github.com/flutter/flutter/issues/74606) but closed for reasons beyond my understanding

**Comment by pedromassangocode** [comment]
I'm able to reproduce the issue.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.178, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.178 at /Users/pedromassango/Code/flutter_master
    • Framework revision 22f1700427 (17 minutes ago), 2021-01-26 14:34:03 +0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

**Comment by nt4f04uNd** [comment]
this is explained in https://github.com/flutter/flutter/issues/18450
solution suggested in https://github.com/flutter/flutter/issues/18450#issuecomment-575447316

**Comment by iapicca** [comment]
> this is explained in #18450 (i guess)
> solution suggested in [#18450 (comment)](https://github.com/flutter/flutter/issues/18450#issuecomment-575447316)

@nt4f04uNd 
this seems to me a `workaround`  rather than a `solution`
coming from a feature request for documentation, so likely not intended for production purpose

also does not really explains why the inconsistency of the behavior

**Comment by nt4f04uNd** [comment]
@iapicca i agree it behaves weird, but this is how it was intended to work

check what hixie says https://github.com/flutter/flutter/issues/18450#issuecomment-397372078

this is even documented
https://github.com/flutter/flutter/blob/7a3a29e71f0da5b3c45ac359b02582fc3b2514c0/packages/flutter/lib/src/rendering/box.dart#L2728-L2755

**Comment by iapicca** [comment]
@nt4f04uNd 
I take back my statement, you are right!
https://github.com/flutter/flutter/issues/18450#issuecomment-397416779
> Use a PointerListener instead of a GestureDetector.

**Comment by nt4f04uNd** [comment]
@iapicca changing default `hitTestBehavior` with `Stack` might be a proposal

this is completely unobvious in the way it works right now, like when we specify `HitTestBehavior.translucent`, we expect all children behind to receive an event and it doesn't makes sense not to do that as it looks inconsistently and moreover useless

**Comment by Hixie** [comment]
The behaviour described here is as intended.

The next step if you'd like it changed is to describe (preferably in a new bug so that we start afresh) the use case -- that is, the end-user behaviour you are trying to achieve -- and an explanation of why/how it's inconvenient to get that behaviour today.

**Comment by iapicca** [comment]
> The behaviour described here is as intended.

@Hixie 
if this is indeed the intended behavior than I'll close the issue
as the remaining points are addressed in existing issues:
- provided more detailed documentation: https://github.com/flutter/flutter/issues/18450 https://github.com/flutter/flutter/issues/74733
- provide a `HitTestBehavior` that works for all the children i stack https://github.com/flutter/flutter/issues/47119

**Comment by Hixie** [comment]
Sounds good, thanks!
