### ISSUE TITLE
Flutter integration test: problem using rootBundle before test

### ISSUE THREAD

**Issue by Schnodderbalken** [flutter/flutter#74706]
I had the idea to create my test expectations in a language independent format so that I preserve the ability to migrate them to another project / platform / language whatever. So I wrote a JSON file holding the information and was planning on reading that JSON file before the test, then iterating over the expectations and creating the tests just like that.
However, I get an error if I try to do that.

## Steps to Reproduce

First, run the steps for installing an integration test that are described here https://flutter.dev/docs/testing/integration-tests. That means:

1. Add `integration_test: ^1.0.0` to dev_dependencies
2. Create a folder `test_driver` with the content: `Future<void> main() => integrationDriver();`
3. Create a file in this directory ` integration_test/sample_test.dart`

The content of this file:
```
void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  String json = await rootBundle.loadString('assets/test_images/expectations.json');
  List expectations = jsonDecode(json)['expectations'];

  group('Sample tests: ', () {
    for (var expectation in expectations) {
      testWidgets('${expectation['title']}', (WidgetTester tester) async {
        expect(1, expectation['expectation']);
      });
    }
  });
}
```
Make sure there is a file called `expectations.json` located in `assets/expectations.json` that needs to be added to pubspec.yml assets as well. The content of the JSON file would be:

```
{
  "expectations": [
    {
      "title": "First expectation",
      "expectation": 2
    }
  ]
}
```

**Expected results:** 
A log indicating that all tests have passed

**Actual results:**
It tells me ` Can't call group() once tests have begun running.`.

At first I suspected running async operations in general before the first test or group, but when I read a String instead of the file content of the JSON like this:
```
String json = await Future.value('{"expectations": [{"title": "First expectation", "expectation": 2}]}');
```
then everything works like charm.
I also tried to put the rootBundle operation into `setUp` or `setUpAll` but that doesn't seem to get executed at all as the compiler complains about the result of jsonDecode(...) being `null`.

<details>
  <summary>Logs</summary>

Output from: ` flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/sample_test.dart`
```
I/flutter (18128): Observatory listening on http://127.0.0.1:39161/MoJfry1J8zY=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60964/MoJfry1J8zY=/
VMServiceFlutterDriver: Isolate found with number: 3084240294280707
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (18128): 00:00 +0: (tearDownAll)
VMServiceFlutterDriver: Connected to Flutter application.
E/flutter (18128): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Can't call group() once tests have begun running.
E/flutter (18128): #0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:290:5)
E/flutter (18128): #1      Declarer.group (package:test_api/src/backend/declarer.dart:196:5)
E/flutter (18128): #2      group (package:flutter_test/src/test_compat.dart:188:13)
E/flutter (18128): #3      main (file:///Users/marcgerken/dev/projects/cross-platform/kanzleiland_crossplatform/integration_test/image_test/image_test_2.dart:24:3)
E/flutter (18128): <asynchronous suspension>
E/flutter (18128): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (18128): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (18128): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (18128): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (18128): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (18128): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (18128): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (18128): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (18128): 
I/flutter (18128): 00:00 +1: All tests passed!
All tests passed.
```

```
```

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale de-DE)
    • Flutter version 1.22.5 at /Users/marcgerken/dev/flutter-sdk/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/marcgerken/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

 
[✓] Connected device (1 available)            
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Schnodderbalken 
I was able to reproduce the issue, however I'm curious why this test pass even it is expecting 1 to equals to 2.

The test crash but the last log message says that all tests have passed.

```
E/flutter (10592): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Can't call group() once tests have begun running.
E/flutter (10592): #0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:320:5)
E/flutter (10592): #1      Declarer.group (package:test_api/src/backend/declarer.dart:221:5)
E/flutter (10592): #2      group (package:flutter_test/src/test_compat.dart:191:13)
E/flutter (10592): #3      main (file:///Users/pedromassango/dev/Projects/flutter_example/integration_test/app_test.dart:13:3)
E/flutter (10592): <asynchronous suspension>
E/flutter (10592): 
All tests passed.
I/flutter (10592): 00:00 +1: All tests passed!
```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.178, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.178 at /Users/pedromassango/Code/flutter_master
    • Framework revision 22f1700427 (17 minutes ago), 2021-01-26 14:34:03 +0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

**Comment by Schnodderbalken** [comment]
@pedromassangocode
Yes, that's another thing that surprised me. I think that the `All tests passed!` is logged because no tests have been executed. So 0 out of 0 tests passed.

**Comment by Schnodderbalken** [comment]
@pedromassango 
Do you know of any workaround I can use until it's fixed?

**Comment by manoellribeiro** [comment]
Hey @Schnodderbalken, I'm facing the same issue, have you found a workaround for this?

**Comment by jaypatel04** [comment]
> I had the idea to create my test expectations in a language independent format so that I preserve the ability to migrate them to another project / platform / language whatever. So I wrote a JSON file holding the information and was planning on reading that JSON file before the test, then iterating over the expectations and creating the tests just like that.
> However, I get an error if I try to do that.
> 
> ## Steps to Reproduce
> First, run the steps for installing an integration test that are described here https://flutter.dev/docs/testing/integration-tests. That means:
> 
> 1. Add `integration_test: ^1.0.0` to dev_dependencies
> 2. Create a folder `test_driver` with the content: `Future<void> main() => integrationDriver();`
> 3. Create a file in this directory ` integration_test/sample_test.dart`
> 
> The content of this file:
> 
> ```
> void main() async {
>   IntegrationTestWidgetsFlutterBinding.ensureInitialized();
>   String json = await rootBundle.loadString('assets/test_images/expectations.json');
>   List expectations = jsonDecode(json)['expectations'];
> 
>   group('Sample tests: ', () {
>     for (var expectation in expectations) {
>       testWidgets('${expectation['title']}', (WidgetTester tester) async {
>         expect(1, expectation['expectation']);
>       });
>     }
>   });
> }
> ```
> 
> Make sure there is a file called `expectations.json` located in `assets/expectations.json` that needs to be added to pubspec.yml assets as well. The content of the JSON file would be:
> 
> ```
> {
>   "expectations": [
>     {
>       "title": "First expectation",
>       "expectation": 2
>     }
>   ]
> }
> ```
> 
> **Expected results:**
> A log indicating that all tests have passed
> 
> **Actual results:**
> It tells me ` Can't call group() once tests have begun running.`.
> 
> At first I suspected running async operations in general before the first test or group, but when I read a String instead of the file content of the JSON like this:
> 
> ```
> String json = await Future.value('{"expectations": [{"title": "First expectation", "expectation": 2}]}');
> ```
> 
> then everything works like charm.
> I also tried to put the rootBundle operation into `setUp` or `setUpAll` but that doesn't seem to get executed at all as the compiler complains about the result of jsonDecode(...) being `null`.
> 
> Logs

Yes this is an issue, but there is one work around this (till Flutter publishes solution). ```rootBundle.load('assets/test_images/expectations.json')``` works fine. So, first read in ByteData and convert it to string.

```
void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  ByteData data = await rootBundle.load('assets/test_images/expectations.json');
  final buffer = data.buffer;
  var list = buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  String json = utf8.decode(list);
  List expectations = jsonDecode(json)['expectations'];

  group('Sample tests: ', () {
    for (var expectation in expectations) {
      testWidgets('${expectation['title']}', (WidgetTester tester) async {
        expect(1, expectation['expectation']);
      });
    }
  });
}
```

**Comment by eyalkutz** [comment]
I get the same error when trying to use the firebase emulator in integration tests

**Comment by aatikakhan** [comment]
I'm also getting the same issue while adding provider to write widget test. Below here's the log I'm getting
```
Running Gradle task 'assembleDebug'...                             21.6s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 8.1s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:57079/DDR_EPTfjT8=/
VMServiceFlutterDriver: Isolate found with number: 1986165753266631
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter ( 6057): 00:00 +0: (tearDownAll)
VMServiceFlutterDriver: Connected to Flutter application.
E/flutter ( 6057): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Can't call test() once tests have begun running.
E/flutter ( 6057): #0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:319:5)
E/flutter ( 6057): #1      Declarer.test (package:test_api/src/backend/declarer.dart:164:5)
E/flutter ( 6057): #2      test (package:flutter_test/src/test_compat.dart:166:13)
E/flutter ( 6057): #3      testWidgets (package:flutter_test/src/widget_tester.dart:159:5)
E/flutter ( 6057): #4      main (file:///Users/aatikakhan/Projects/knight-app/test/widget_integration_test.dart:22:3)
E/flutter ( 6057): <asynchronous suspension>
E/flutter ( 6057): 
I/flutter ( 6057): 00:00 +1: All tests passed!
All tests passed.
```
Code for test is here: `void main() async{
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  testWidgets('knight App', (WidgetTester tester) async {
    await tester.pumpWidget(MultiProvider(
        providers: [
          Provider<LoginProvider>(create: (_) => LoginProvider())],
        child: Builder(builder: (context) {
          return App();
        })));
    await tester.pumpAndSettle();
  });
}
`

**Comment by aatikakhan** [comment]
Hi @pedromassango do you have any solution for the above?

**Comment by SionBrown** [comment]
@aatikakhan try putting the 'await Firebase.initializeApp();' inside the testWidgets function like so;

void main() async{
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  
  testWidgets('knight App', (WidgetTester tester) async {
    await Firebase.initializeApp();
    await tester.pumpWidget(MultiProvider(
        providers: [
          Provider<LoginProvider>(create: (_) => LoginProvider())],
        child: Builder(builder: (context) {
          return App();
        })));
    await tester.pumpAndSettle();
  });
}

**Comment by rikai-trongpq** [comment]
I'm getting same issue when I tried load json from asset. Any solution?

**Comment by dispersik** [comment]
> ByteData data = await rootBundle.load('assets/test_images/expectations.json');
>   final buffer = data.buffer;
>   var list = buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
>   String json = utf8.decode(list);

for me it's not working :(

**Comment by dario-digregorio** [comment]
> ByteData data = await rootBundle.load('assets/test_images/expectations.json');
> final buffer = data.buffer;
> var list = buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
> String json = utf8.decode(list);

works for me :) I had the problem `rootBundle.loadString` did work in the first test inside a group or when running the test alone. But when I run the test alone it works.

**Comment by darshankawar** [comment]
@Schnodderbalken 
I verified this issue using latest stable and found below:

1. Since you are using `integration_test` package and it is now the preferred method for testing instead of `flutter_driver`, running `flutter test integration_test/app_test.dart` gives me below result which I think is expected:

<details>
<summary> console log </summary>

```

dhs@Dhss-MacBook-Pro test_app % flutter test integration_test/app_test.dart
00:10 +0: loading /Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart                                                                                                Ru00:31 +0: loading /Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart                                                                                                 
00:38 +0: loading /Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart                                                                                             7.1s
Xcode build done.                                           28.5s
00:43 +0: Sample tests:  First expectation                                                                                                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <2>
  Actual: <1>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart:15:9)
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart line 15
The test description was:
  First expectation
════════════════════════════════════════════════════════════════════════════════════════════════════
00:43 +0 -1: Sample tests:  First expectation [E]                                                                                                                                        
  Test failed. See exception logs above.
  The test description was: First expectation
  

To run this test again: /Users/dhs/documents/fluttersdk/flutter/bin/cache/dart-sdk/bin/dart test /Users/dhs/Documents/NCFlutter/test_app/integration_test/app_test.dart -p vm --plain-name 'Sample tests:  First expectation'
00:43 +0 -1: Some tests failed.                                                                                                                                                          
dhs@Dhss-MacBook-Pro test_app % 


```

</details>


2. Running the old command though gives me same error as you reported.

So I suggest you to try the updated command as I mentioned in step 1 and check at your end to see if it works as expected or not.
