### ISSUE TITLE
Disable vmservice RPC timeout when debugging

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7470]
Our VM service RPCs have timeouts. They shouldn't when the user is debugging the Flutter application.

**Comment by johnmccutchan** [comment]
I'm not a fan of putting policy in library code. The caller of the vm service rpc should decide what an appropriate timeout should be.

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/7310.
