### ISSUE TITLE
PlatformException(already_active, Image picker is already active, null, null)

### ISSUE THREAD

**Issue by saprahits** [flutter/flutter#74715]
`PlatformException(already_active, Image picker is already active, null, null)

I/flutter (30950): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (30950): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (30950): <asynchronous suspension>
I/flutter (30950): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (30950): #3      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
I/flutter (30950): #4      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
I/flutter (30950): #5      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
I/flutter (30950): #6      _EditProfileState.getImage (package:graham/screens/Profile/sc_editProfile.dart:113:37)
I/flutter (30950): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
I/flutter (30950): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
I/flutter (30950): #9      GestureRecognizer.invokeCallback (package`

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @saprahits 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/72759
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
