### ISSUE TITLE
Downloading Material fonts during flutter doctor run gives FilesystemException

### ISSUE THREAD

**Issue by naveenneog** [flutter/flutter#74724]
## Steps to Reproduce

1. Install the flutter on Windows 10 
2. run flutter doctor from cmd line
3. Hitting this issue consistently in my machine

## Logs

To report your crash to
<details>
<summary>Logs</summary>

```
Downloading Material fonts...                   Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path =
'C:\Users\hi\Documents\development\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\fonts\136360
3dd17dd609018e53cdbd5fef6791814337\fonts.zip' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Windows\System32\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+open+file%2C+path+%3D+%27C%3A%5CUsers%5Chi%5CDocuments%5Cdevelopment%5Cflutter%5Cbin%5Ccache%5Cdownloads%5Cstorage.googleapis.com%5Cflutter_infra%5Cflutter%5Cfonts%5C1363603dd17dd609018e53cdbd5fef6791814337%5Cfonts.zip%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

```

```
```

</details>

**Comment by darshankawar** [comment]
@naveenneog 
Can you provide the contents of the crash log generated ?  `A crash report has been written to C:\Windows\System32\flutter_02.log.`

**Comment by iapicca** [comment]
@naveenneog
[google_fonts](https://pub.dev/packages/google_fonts) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/material-foundation/google-fonts-flutter/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by guidezpl** [comment]
This is not a `google_fonts` issue since it's part of the framework. The url above looks malformed, should start with https:// (https://github.com/flutter/flutter/blob/9d5a540cbb56e250eb1f7b0ff1b7102daab5a3fd/packages/flutter_tools/lib/src/cache.dart#L400). Are you still facing the issue?
