### ISSUE TITLE
[BUG] [CAMERA] Flutter camera can't find video path when start recording video on iPhone in stable 1.22.6.

### ISSUE THREAD

**Issue by davidRuland1234** [flutter/flutter#74728]
I'm using Flutter camera plugin camera: ^0.5.8+15 For some reason, my camera can't find video path when I stoped recording my video.
This is the error I'm getting.    

Here is my code of start and stop video recording. The same code use to work before but it's not working now.

```
class _CameraWidget extends State<CameraWidget>
    with WidgetsBindingObserver, SingleTickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  CameraController controller;
  String videoPath;
  VideoPlayerController videoController;
  VoidCallback videoPlayerListener;
  bool enableAudio = true;
  List<CameraDescription> cameras = [];
  bool initialized = false;
  int cameraIndex = 0;
  bool flashEnabled = false;
  AnimationController animController; // for camera switch animation
  bool get isRecording => initialized && controller.value.isRecordingVideo;

  @override
  void initState() {
    super.initState();
    cameras = Globals().cameras;
    onNewCameraSelected(cameras[cameraIndex]);
    cameraIndex++;
    WidgetsBinding.instance.addObserver(this);
    animController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 500),
      // upperBound: pi,
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    if (videoController != null) {
      videoController.dispose();
    }
    if (controller != null) {
      controller.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: Container(
        color: Colors.black,
        child: Stack(
          children: <Widget>[
            Align(alignment: Alignment.center, child: _cameraPreviewWidget()),
            Positioned(
              left: 10,
              top: 15,
              child: IconButton(
                icon: iconShadow(
                  Icons.close,
                  color: Colors.white,
                  size: 35,
                ),
                onPressed: () {
                  widget.onNavPressed(true);
                },
              ),
            ),
            if (cameraIndex == 1)
              Container(
                margin: const EdgeInsets.only(top: 15),
                alignment: Alignment.topCenter,
                child: IconButton(
                  icon: iconShadow(
                    flashEnabled ? Icons.flash_on : Icons.flash_off,
                    color: flashEnabled ? Colors.white : Colors.grey[400],
                    size: 30,
                  ),
                  onPressed: () {},
                ),
              ),
            Positioned(
              right: 10,
              top: 15,
              child: IconButton(
                icon: iconShadow(
                  Icons.arrow_forward_ios,
                  color: Colors.white,
                  size: 30,
                ),
                onPressed: () {
                  widget.onNavPressed(false);
                },
              ),
            ),
            Container(
              alignment: Alignment.bottomCenter,
              margin: const EdgeInsets.only(bottom: 50),
              // color: Colors.black.withOpacity(0.3),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  IconButton(
                    onPressed: () {
                      // Toggle between cameras
                      onNewCameraSelected(cameras[cameraIndex]);
                      cameraIndex++;
                      if (cameraIndex >= cameras.length) {
                        cameraIndex = 0;
                      }
                      if (animController.status == AnimationStatus.dismissed) {
                        animController.forward();
                      } else {
                        animController.reverse();
                      }
                    },
                    icon: RotationTransition(
                      alignment: Alignment(0.1, 0.1),
                      turns: Tween(
                        begin: 0.0,
                        end: 0.5,
                      ).animate(animController),
                      child: iconShadow(
                        Icons.loop,
                        size: 35,
                      ),
                    ),
                  ),
                  _captureControlRowWidget(),
                  IconButton(
                    onPressed: () {
                      widget.onNavPressed(false);
                    },
                    icon: iconShadow(
                      Icons.add_to_photos,
                      // color: Colors.white,
                      size: 35,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _captureControlRowWidget() {
    final iconSize = 100.0;
    return IconButton(
      icon: Container(
        child: Icon(isRecording ? Icons.stop : Icons.fiber_manual_record),
      ),
      iconSize: iconSize,
      color: Colors.red,
      onPressed: initialized && !controller.value.isRecordingVideo
          ? onVideoRecordButtonPressed
          : onStopButtonPressed,
    );
  }

  void onVideoRecordButtonPressed() {
    startVideoRecording().then((String filePath) {
      if (mounted) setState(() {});
      if (filePath != null) {
        customToastNotification(_scaffoldKey, 'Recording...');
      }
    });
  }

  void onStopButtonPressed() {
    stopVideoRecording().then((_) {
      if (mounted) setState(() {});
      GallerySaver.saveVideo(videoPath, albumName: '/temp/video')
          .then((bool success) {
        setState(() {
          customToastNotification(_scaffoldKey, 'Recording stopped!');
          widget.callBack(videoPath);
        });
      });
    });
  }

  Future<void> stopVideoRecording() async {
    if (!controller.value.isRecordingVideo) {
      return null;
    }
    try {
      await controller.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    //await _startVideoPlayer();
  }

  /*Future<void> _startVideoPlayer() async {
    final VideoPlayerController vcontroller =
        VideoPlayerController.file(File(videoPath));
    videoPlayerListener = () {
      if (videoController != null && videoController.value.size != null) {
        // Refreshing the state to update video player with the correct ratio.
        if (mounted) setState(() {});
        videoController.removeListener(videoPlayerListener);
      }
    };
    vcontroller.addListener(videoPlayerListener);
    await vcontroller.setLooping(true);
    await vcontroller.initialize();
    await videoController?.dispose();
    if (mounted) {
      setState(() {
        imagePath = null;
        videoController = vcontroller;
      });
    }
    await vcontroller.play();
  }*/

  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  /// Display the preview from the camera (or a message if the preview is not available).
  Widget _cameraPreviewWidget() {
    if (controller == null || !controller.value.isInitialized) {
      return loader();
    } else {
      return AspectRatio(
        aspectRatio: controller.value.aspectRatio,
        child: CameraPreview(controller),
      );
    }
  }

  Future<String> startVideoRecording() async {
    if (!controller.value.isInitialized) {
      customToastNotification(_scaffoldKey, 'Error: select a camera first.');
      return null;
    }

    final Directory extDir = await getTemporaryDirectory();
    final String dirPath = '${extDir.path}/temp/video';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${timestamp()}.mp4';

    if (controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }
    try {
      videoPath = filePath;
      await controller.startVideoRecording(filePath);
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    return filePath;
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        onNewCameraSelected(controller.description);
      }
    }
  }

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(
      cameraDescription,
      ResolutionPreset.high,
      enableAudio: enableAudio,
    );

    // If the controller is updated then update the UI.
    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        customToastNotification(
            _scaffoldKey, 'Camera error ${controller.value.errorDescription}');
      }
    });
    try {
      await controller.initialize();
      initialized = true;
    } on CameraException catch (e) {
      _showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  void _showCameraException(CameraException e) {
    customToastNotification(_scaffoldKey, 'Error: ${e.code}\n${e.description}');
  }
}


```

## Steps to Reproduce

I have already used this flutter commands to recreate issue. Its also same error in new project. 
        flutter clean
         rm -Rf ios/Pods
         rm -Rf ios/.symlinks
         rm -Rf ios/Flutter/Flutter.framework
         rm -Rf ios/Flutter/Flutter.podspec
        pod cache clean —all
        rm -Rf ~/Applications/flutter/.pub-cache
        rm -rf ~/.pub-cache/hosted
        rmDir ~/.pub-cache/hosted
        flutter get packages

## Logs

<details>
<summary>
No error logs, but videoPath is empty.
</summary>

### Pod file

# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def flutter_install_ios_plugin_pods(ios_application_path = nil)
  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  ios_application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
  raise 'Could not find iOS application path' unless ios_application_path

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.

  symlink_dir = File.expand_path('.symlinks', ios_application_path)
  system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

  symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
  system('mkdir', '-p', symlink_plugins_dir)

  plugins_file = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  plugin_pods = flutter_parse_plugins_file(plugins_file)
  plugin_pods.each do |plugin_hash|
    plugin_name = plugin_hash['name']
    plugin_path = plugin_hash['path']
    if (plugin_name && plugin_path)
      symlink = File.join(symlink_plugins_dir, plugin_name)
      File.symlink(plugin_path, symlink)

      if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/https-gpl', :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      else
          pod plugin_name, :path => File.join('.symlinks', 'plugins', plugin_name, 'ios')
      end
    end
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
end
end
```
```

<[flutter] flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale sv-SE)
    • Flutter version 1.22.6
    • Framework revision 9b2d32b605 (4 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Connected device (1 available)
    • iPhone (mobile)  • ios • iOS 14.3</details>
```

**Comment by darshankawar** [comment]
@davidRuland1234 
You seem to be using an older version of camera. The current version is ^0.7.0 which includes bunch of fixes and new features. https://pub.dev/packages/camera/changelog.
Does the issue also occur with latest plugin version ?
Also, what exactly the issue you are getting ? Can you provide steps to replicate that shows the issue along with a complete `flutter doctor -v` ?

**Comment by davidRuland1234** [comment]
I have not tried with the latest plugin since its using XFile imageFile and XFile videoFile and it doesnt take a video path in  await controller.startVideoRecording(filePath). But I will try to update to new plugin and see if error exist. My issue is that my video path is empty in next screen when I try to get it. I think its have something with broken sound in video so its not recognized when I  record a video. Audio recorder/microphone is also displayed at top left corner after I stop record my video.

**Comment by darshankawar** [comment]
@davidRuland1234 
I tried your code sample but it seems to have lot of customized code which is giving me compile errors (ex : `customToastNotification`, `loader`, `GallerySaver` and so on) hence I am unable to verify this using latest plugin version).

I'd suggest you to upgrade to latest version and try again to see if issue persists or works as expected.
If issue persists, please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can simply copy paste and run in IDE to see the issue.

**Comment by davidRuland1234** [comment]
Still not working with Camera 0.7.0 and I am using path provider 1.6.10. I think its something with path provide plugin that's causing video not be displayed as a preview. 
**This is a minimum code example for my Camera.**             `
class Globals {
  static final Globals _instance = Globals._init();

  List<CameraDescription> cameras;

  String get deviceLocale {
    return _deviceLocale != null ? _deviceLocale : 'unknown';
  }

  String _deviceLocale;

  factory Globals() {
    return _instance;
  }

  Globals._init() {
    _getCameras();
    _getDeviceLocale();
  }

  Future<void> _getCameras() async {
    cameras = await availableCameras();
  }

  Future<void> _getDeviceLocale() async {
    await CountryCodes.init();
    _deviceLocale = CountryCodes.getDeviceLocale().countryCode.toLowerCase();
  }
}.
class _CameraWidget extends State<CameraWidget>
    with WidgetsBindingObserver, SingleTickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  CameraController controller;
  String videoPath;
  XFile imageFile; 
  XFile videoFile;
  VideoPlayerController videoController;
  VoidCallback videoPlayerListener;
  bool enableAudio = true;
  List<CameraDescription> cameras = [];
  bool initialized = false;
  int cameraIndex = 0;
  bool flashEnabled = false;
  AnimationController animController; // for camera switch animation
  bool get isRecording => initialized && controller.value.isRecordingVideo;

  @override
  void initState() {
    super.initState();
    cameras = Globals().cameras;
    onNewCameraSelected(cameras[cameraIndex]);
    cameraIndex++;
    WidgetsBinding.instance.addObserver(this);
    animController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 500),
      // upperBound: pi,
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    if (videoController != null) {
      videoController.dispose();
    }
    if (controller != null) {
      controller.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: Container(
        color: Colors.black,
        child: Stack(
          children: <Widget>[
            Align(alignment: Alignment.center, child: _cameraPreviewWidget()),
            Positioned(
              left: 10,
              top: 15,
              child: IconButton(
                icon: iconShadow(
                  Icons.close,
                  color: Colors.white,
                  size: 35,
                ),
                onPressed: () {
                  widget.onNavPressed(true);
                },
              ),
            ),
            if (cameraIndex == 1) // only show flash in back cam mode
              Container(
                margin: const EdgeInsets.only(top: 15),
                alignment: Alignment.topCenter,
                child: IconButton(
                  icon: iconShadow(
                    flashEnabled ? Icons.flash_on : Icons.flash_off,
                    color: flashEnabled ? Colors.white : Colors.grey[400],
                    size: 30,
                  ),
                  onPressed: () {},
                ),
              ),
            Positioned(
              right: 10,
              top: 15,
              child: IconButton(
                icon: iconShadow(
                  Icons.arrow_forward_ios,
                  color: Colors.white,
                  size: 30,
                ),
                onPressed: () {
                  widget.onNavPressed(false);
                },
              ),
            ),
            Container(
              alignment: Alignment.bottomCenter,
              margin: const EdgeInsets.only(bottom: 50),
              // color: Colors.black.withOpacity(0.3),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  IconButton(
                    onPressed: () {
                      // Toggle between cameras
                      onNewCameraSelected(cameras[cameraIndex]);
                      cameraIndex++;
                      if (cameraIndex >= cameras.length) {
                        cameraIndex = 0;
                      }
                      if (animController.status == AnimationStatus.dismissed) {
                        animController.forward();
                      } else {
                        animController.reverse();
                      }
                    },
                    icon: RotationTransition(
                      alignment: Alignment(0.1, 0.1),
                      turns: Tween(
                        begin: 0.0,
                        end: 0.5,
                      ).animate(animController),
                      child: iconShadow(
                        Icons.loop,
                        size: 35,
                      ),
                    ),
                  ),
                  _captureControlRowWidget(),
                  IconButton(
                    onPressed: () {
                      widget.onNavPressed(false);
                    },
                    icon: iconShadow(
                      Icons.add_to_photos,
                      // color: Colors.white,
                      size: 35,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _captureControlRowWidget() {
    final iconSize = 100.0;
    return IconButton(
      icon: Container(
        child: Icon(isRecording ? Icons.stop : Icons.fiber_manual_record),
      ),
      iconSize: iconSize,
      color: Colors.red,
      onPressed: initialized && !controller.value.isRecordingVideo
          ? onVideoRecordButtonPressed
          : onStopButtonPressed,
    );
  }

  void onVideoRecordButtonPressed() {
    startVideoRecording().then((String filePath) {
      if (mounted) setState(() {});
    });
  }
  void onStopButtonPressed() {
    stopVideoRecording().then((file) {
      if (mounted) setState(() {});
      if (file != null) {
        videoFile = file;
        widget.callBack(videoPath);
      }
    });
  }

  Future<XFile> stopVideoRecording() async {
    if (!controller.value.isRecordingVideo) {
      return null;
    }

    try {
      return controller.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }

  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  /// Display the preview from the camera (or a message if the preview is not available).
  Widget _cameraPreviewWidget() {
    if (controller == null || !controller.value.isInitialized) {
      return loader();
    } else {
      return AspectRatio(
        aspectRatio: controller.value.aspectRatio,
        child: CameraPreview(controller),
      );
    }
  }


  Future<String> startVideoRecording() async {
    if (!controller.value.isInitialized) {
      customToastNotification(_scaffoldKey, 'Error: select a camera first.');
      return null;
    }

    final Directory extDir = await getTemporaryDirectory();
    final String dirPath = '${extDir.path}/temp/video';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${timestamp()}.mp4';

    if (controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }
    try {
      videoPath = filePath;
      await controller.startVideoRecording(/*filePath*/);
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    return filePath;
  }

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(
      cameraDescription,
      ResolutionPreset.high,
      enableAudio: enableAudio,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );

    // If the controller is updated then update the UI.
    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        customToastNotification(
            _scaffoldKey, 'Camera error ${controller.value.errorDescription}');
      }
    });

    try {
      await controller.initialize();
      initialized = true;
    } on CameraException catch (e) {
      _showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        onNewCameraSelected(controller.description);
      }
    }
  }
 
  void _showCameraException(CameraException e) {
    customToastNotification(_scaffoldKey, 'Error: ${e.code}\n${e.description}');
  }
}
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  Globals();`

**Comment by darshankawar** [comment]
@davidRuland1234 
Tried your code sample above but it still seem to be giving me compile errors. See below the complete code:

<details>
<summary> code sample </summary>

```
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:video_player/video_player.dart';

class Globals {
  static final Globals _instance = Globals._init();

  List<CameraDescription> cameras;

  String get deviceLocale {
    return _deviceLocale != null ? _deviceLocale : 'unknown';
  }

  String _deviceLocale;

  factory Globals() {
    return _instance;
  }

  Globals._init() {
    _getCameras();
    _getDeviceLocale();
  }

  Future<void> _getCameras() async {
    cameras = await availableCameras();
  }

  Future<void> _getDeviceLocale() async {
    await CountryCodes.init();
    _deviceLocale = CountryCodes.getDeviceLocale().countryCode.toLowerCase();
  }
}
class _CameraWidget extends State<CameraWidget>
    with WidgetsBindingObserver, SingleTickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  CameraController controller;
  String videoPath;
  XFile imageFile;
  XFile videoFile;
  VideoPlayerController videoController;
  VoidCallback videoPlayerListener;
  bool enableAudio = true;
  List<CameraDescription> cameras = [];
  bool initialized = false;
  int cameraIndex = 0;
  bool flashEnabled = false;
  AnimationController animController; // for camera switch animation
  bool get isRecording => initialized && controller.value.isRecordingVideo;

  @override
  void initState() {
    super.initState();
    cameras = Globals().cameras;
    onNewCameraSelected(cameras[cameraIndex]);
    cameraIndex++;
    WidgetsBinding.instance.addObserver(this);
    animController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 500),
      // upperBound: pi,
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    if (videoController != null) {
      videoController.dispose();
    }
    if (controller != null) {
      controller.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      body: Container(
        color: Colors.black,
        child: Stack(
          children: <Widget>[
            Align(alignment: Alignment.center, child: _cameraPreviewWidget()),
            Positioned(
              left: 10,
              top: 15,
              child: IconButton(
                icon: Icon(
                  Icons.close,
                  color: Colors.white,
                  size: 35,
                ),
                onPressed: () {
                  widget.onNavPressed(true);
                },
              ),
            ),
            if (cameraIndex == 1) // only show flash in back cam mode
              Container(
                margin: const EdgeInsets.only(top: 15),
                alignment: Alignment.topCenter,
                child: IconButton(
                  icon: Icon(
                    flashEnabled ? Icons.flash_on : Icons.flash_off,
                    color: flashEnabled ? Colors.white : Colors.grey[400],
                    size: 30,
                  ),
                  onPressed: () {},
                ),
              ),
            Positioned(
              right: 10,
              top: 15,
              child: IconButton(
                icon: Icon(
                  Icons.arrow_forward_ios,
                  color: Colors.white,
                  size: 30,
                ),
                onPressed: () {
                  widget.onNavPressed(false);
                },
              ),
            ),
            Container(
              alignment: Alignment.bottomCenter,
              margin: const EdgeInsets.only(bottom: 50),
              // color: Colors.black.withOpacity(0.3),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  IconButton(
                    onPressed: () {
                      // Toggle between cameras
                      onNewCameraSelected(cameras[cameraIndex]);
                      cameraIndex++;
                      if (cameraIndex >= cameras.length) {
                        cameraIndex = 0;
                      }
                      if (animController.status == AnimationStatus.dismissed) {
                        animController.forward();
                      } else {
                        animController.reverse();
                      }
                    },
                    icon: RotationTransition(
                      alignment: Alignment(0.1, 0.1),
                      turns: Tween(
                        begin: 0.0,
                        end: 0.5,
                      ).animate(animController),
                      child: Icon(
                        Icons.loop,
                        size: 35,
                      ),
                    ),
                  ),
                  _captureControlRowWidget(),
                  IconButton(
                    onPressed: () {
                      widget.onNavPressed(false);
                    },
                    icon: Icon(
                      Icons.add_to_photos,
                      // color: Colors.white,
                      size: 35,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _captureControlRowWidget() {
    final iconSize = 100.0;
    return IconButton(
      icon: Container(
        child: Icon(isRecording ? Icons.stop : Icons.fiber_manual_record),
      ),
      iconSize: iconSize,
      color: Colors.red,
      onPressed: initialized && !controller.value.isRecordingVideo
          ? onVideoRecordButtonPressed
          : onStopButtonPressed,
    );
  }

  void onVideoRecordButtonPressed() {
    startVideoRecording().then((String filePath) {
      if (mounted) setState(() {});
    });
  }
  void onStopButtonPressed() {
    stopVideoRecording().then((file) {
      if (mounted) setState(() {});
      if (file != null) {
        videoFile = file;
        widget.callBack(videoPath);
      }
    });
  }

  Future<XFile> stopVideoRecording() async {
    if (!controller.value.isRecordingVideo) {
      return null;
    }

    try {
      return controller.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }

  String timestamp() => DateTime.now().millisecondsSinceEpoch.toString();

  /// Display the preview from the camera (or a message if the preview is not available).
  Widget _cameraPreviewWidget() {
    if (controller == null || !controller.value.isInitialized) {
      return loader();
    } else {
      return AspectRatio(
        aspectRatio: controller.value.aspectRatio,
        child: CameraPreview(controller),
      );
    }
  }


  Future<String> startVideoRecording() async {
    if (!controller.value.isInitialized) {
      customToastNotification(_scaffoldKey, 'Error: select a camera first.');
      return null;
    }

    final Directory extDir = await getTemporaryDirectory();
    final String dirPath = '${extDir.path}/temp/video';
    await Directory(dirPath).create(recursive: true);
    final String filePath = '$dirPath/${timestamp()}.mp4';

    if (controller.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return null;
    }
    try {
      videoPath = filePath;
      await controller.startVideoRecording(/*filePath*/);
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
    return filePath;
  }

  void onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(
      cameraDescription,
      ResolutionPreset.high,
      enableAudio: enableAudio,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );

    // If the controller is updated then update the UI.
    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        customToastNotification(
            _scaffoldKey, 'Camera error ${controller.value.errorDescription}');
      }
    });

    try {
      await controller.initialize();
      initialized = true;
    } on CameraException catch (e) {
      _showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        onNewCameraSelected(controller.description);
      }
    }
  }

  void _showCameraException(CameraException e) {
    customToastNotification(_scaffoldKey, 'Error: ${e.code}\n${e.description}');
  }

  void customToastNotification(GlobalKey<ScaffoldState> scaffoldKey, String s) {}
}
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
//  await Firebase.initializeApp();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  Globals();
}

```

</details>

It's giving me errors on `loader`, `CountryCodes` and so on.

**Comment by davidRuland1234** [comment]
Its using country_codes: ^1.0.0 plugin, loader is a widget and I have already tried with path_provider 1.6.27. Its still same error.                                                                                           Widget loader() {
  if (Platform.isIOS) {
    return Center(
      child: CupertinoActivityIndicator(),
    );
  } else {
    return Center(
      child: CircularProgressIndicator(
        valueColor: AlwaysStoppedAnimation<Color>(Colors.orange),
      ),
    );
  }
}

**Comment by darshankawar** [comment]
@davidRuland1234 
With your updated code sample above, I still had to fix lot of your code sample to put it together. I'd suggest you to provide your entire code sample in single file (main.dart) that we can simply copy paste and run to verify the issue.

**Comment by davidRuland1234** [comment]
yes, will put code sample in one file so you can test it.

**Comment by davidRuland1234** [comment]
Hi, sorry for late answear. When I run it in debug mode recording works fine If I do a hot reload.  Then preview of my video is displayed at next screen directly after I stop recording. Is It possible to call a hot reload for my Camera preview?

**Comment by darshankawar** [comment]
@davidRuland1234 
I am not too sure whether hot reload works for camera preview. Also, is your original issue resolved or persists still ?

**Comment by davidRuland1234** [comment]
Its still not working, but It worked in Flutter. stable 1.17.1 and I cant downgrade my Flutter version since I need it for other projects.

**Comment by darshankawar** [comment]
> yes, will put code sample in one file so you can test it.

@davidRuland1234 Will need a complete reproducible use case as you mentioned earlier in order to make this issue actionable.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
