### ISSUE TITLE
I have a problem for running with some of flutter packages

### ISSUE THREAD

**Issue by bahramee** [flutter/flutter#74725]
my issue is with some of flutter packages, like: keyboard_visibility and clipboard_manager
my os is: Ubuntu 20.04.1 LTS
and this is my error details when is user that packages...

<details>
  <summary>Logs</summary>

What went wrong:                                                      
Execution failed for task ':clipboard_manager:parseDebugLibraryResources'.
> Could not resolve all files for configuration ':clipboard_manager:androidApis'.
   > Failed to transform file 'android.jar' to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}
      > Execution failed for PlatformAttrTransform: /home/milad/Android/Sdk/platforms/android-27/android.jar.
         > /home/milad/Android/Sdk/platforms/android-27/android.jar (No such file or directory)

[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/milad/engines/flutter
    • Framework revision 9b2d32b605 (4 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/milad/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/milad/software/android-studio-ide-201.6953283-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/milad/software/android-studio-ide-201.6953283-linux/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/milad/software/android-studio-ide-201.6953283-linux/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

</details>

**Comment by darshankawar** [comment]
@bahramee 
The plugins you mentioned are 3rd party. Please consider opening this issue in respective plugin owner's repo: https://github.com/adee42/flutter_keyboard_visibility/issues and https://github.com/anuranBarman/ClipboardManager/issues.
Closing from here, as this doesn't seem to be an issue with Flutter.
If you disagree, write in comments and I'll reopen it.

**Comment by bahramee** [comment]
no this is not about plugins. i ran this plugins in windows 10 without problem, i think my issue is about android.jar (No such file or directory)
