### ISSUE TITLE
Documentation - BottomNavigationBarItem constructor - says title should not be null but title is deprecated 

### ISSUE THREAD

**Issue by ronriley** [flutter/flutter#74732]
At:
 https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html

@Deprecated('Use "label" instead, as it allows for an improved text-scaling experience. ' 'This feature was deprecated after v1.19.0.') Widget **title**,

then..
 
The argument icon should not be null and the argument **title** should not be null when used in a Material Design's BottomNavigationBar.

**Comment by Anas35** [comment]
This has been already fixed in #67218 and docs - https://master-api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html

**Comment by HansMuller** [comment]
Closing, since the issue is already fixed, per the previous comment  https://github.com/flutter/flutter/issues/74732#issuecomment-768281037
