### ISSUE TITLE
[android] how  libapp.so  transfer to app.dill, or other useful tool?

### ISSUE THREAD

**Issue by impeiwei** [flutter/flutter#74730]
## Steps to Reproduce

I have problem when running release apk (we add some code in compile time when create app.dill), 

so when running we found:

![image](https://user-images.githubusercontent.com/55788007/105858035-de9fc080-6025-11eb-8974-9f799fea2514.png)

and addr2line:

![image](https://user-images.githubusercontent.com/55788007/105858164-faa36200-6025-11eb-9920-d86ffc902201.png)

**Expected results:** 

**Actual results:** 
this APP1 (flutter 1.12.13-hotfix.9)with flutter has this issus (crashed when open FlutterActivity),  but other APP2 (flutter 1.12.13-hotfix.9) , or APP3 with (flutter 1.22.4) is correct.
so, it may APP1 some dart code , but we can not debug .

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/peiwei/.flutterw/lianjia/1.12.13
    • Framework revision f139b11009 (10 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/peiwei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @impeiwei 
Looks like you are using a 6+ months old Flutter version.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v`.
Thank you

**Comment by impeiwei** [comment]
@pedromassangocode we had solved this problem, we missed some info such as "@vm.inferred-type.metadata" in app.dill 。
but we also didnot know why it happen in this FlutterApp,  and other FlutterApp2 is right.
