### ISSUE TITLE
Fatal signal 4 (SIGILL) at 0x8ee1c63c (code=1), thread 10708 (pool-7-thread-1)

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#74731]
got almost the same error today :
`Fatal signal 4 (SIGILL) at 0x8ee1c63c (code=1), thread 10708 (pool-7-thread-1)`

It started failing yesterday with an upgrade of flutter dev channel it seems but not sure.
The problem is when running on the emulator with API 16, it's part of our CI/CD so it's blocking us at ADEO services

```sh
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-12.0.pre at /home/kleak/fvm/versions/dev
    • Framework revision a706cd2112 (12 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/kleak/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio
    • Android Studio at /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/kleak/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.155
    • Flutter plugin version 51.0.4
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • emulator-5554 (mobile) • emulator-5554 • android-arm    • Android 4.1.2 (API 16) (emulator)
    • Linux (desktop)        • linux         • linux-x64      • Linux
    • Chrome (web)           • chrome        • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

I also tried with an android-x86 and i got a white screen
here are the log when i launch it on an android-x86 emulator

```sh
Launching lib/main_mock.dart on emulator-5554 in debug mode...
lib/main_mock.dart:1
E/flutter ( 4572): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(71)] Failed to setup Skia Gr context.
E/flutter ( 4572): [ERROR:flutter/shell/common/platform_view.cc(81)] Failed to create platform view rendering surface
E/flutter ( 4712): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(71)] Failed to setup Skia Gr context.
E/flutter ( 4712): [ERROR:flutter/shell/common/platform_view.cc(81)] Failed to create platform view rendering surface
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/kleak/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/kleak/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.4.0/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:43659/-bmKgR6KWmo=/
```

_Originally posted by @Kleak in https://github.com/flutter/flutter/issues/60604#issuecomment-767470331_

**Comment by joffre** [comment]
Hi, I'm working with @Kleak and I have the same problem on old Android versions (4.1) using emulators. Here are fewer details :
`[   +4 ms] Observatory URL on device: http://127.0.0.1:40502/PTE0ZUa6J4s=/
[   +1 ms] executing: D:\Env\Android\Sdk\platform-tools\adb.exe -s emulator-5556 forward tcp:0 tcp:40502
[  +24 ms] 53300
[        ] Forwarded host port 53300 to device port 40502 for Observatory
[   +4 ms] Caching compiled dill
[  +48 ms] Connecting to service protocol: http://127.0.0.1:53300/PTE0ZUa6J4s=/
[   +3 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:53300/PTE0ZUa6J4s=/.
[  +52 ms] Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:53300/PTE0ZUa6J4s=/ws
[        ] Fail to connect to service protocol: http://127.0.0.1:53300/PTE0ZUa6J4s=/: DartDevelopmentServiceException: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:53300/PTE0ZUa6J4s=/ws
[ +258 ms] E/flutter ( 6926): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(71)] Failed to setup Skia Gr context.
[   +5 ms] E/flutter ( 6926): [ERROR:flutter/shell/common/platform_view.cc(81)] Failed to create platform view rendering surface
[ +765 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:53300/PTE0ZUa6J4s=/
[   +2 ms] "flutter run" took 12 544ms.`

The DDS connection with the VM Service doesn't work well.

About the white screen, I enabled software rendering by adding the --enable-software-rendering flag to flutter run and the app got deployed with success but the DDS connection is still lost. Also, --enable-software-rendering can't be passed to a flutter drive, which is problematic.

**Comment by darshankawar** [comment]
@Kleak 
Can you provide a complete minimal reproducible code sample that shows the issue ?
This could be happening due to the low end Android emulators and their incompatibility with `Skia Gr context` and `platform view rendering surface`. https://github.com/flutter/flutter/issues/15451, https://github.com/flutter/flutter/issues/18601.

Does the issue occur locally or only in your CI/CD ?
Also just curious to know the reason behind using low end Android emulators (api 16) to run your app ?

**Comment by Kleak** [comment]
It happens on both. The error started recently.

We run old API because we have lot of old device to support 😉.
It's an internal application and we can't upgrade the fleet of device currently.

So Flutter is no more compatible with API 16 on dev channel ?

**Comment by Kleak** [comment]
with the project created with flutter create on channel dev you will got the white screen with the integration test.
here is a newly created project https://github.com/Kleak/fail_api_16

**Comment by Kleak** [comment]
with `--enable-software-rendering` we can launch the app but there is no way to launch integration with this flag ...

**Comment by darshankawar** [comment]
@Kleak thanks for the repo.  I cloned it and ran it on emulator api 16 and noticed the white screen while running the app.

<img width="346" alt="Screenshot 2021-01-27 at 2 59 53 PM" src="https://user-images.githubusercontent.com/67046386/105975192-aeebc980-60b4-11eb-8e8d-d1097a2bc31b.png">

<details>
<summary>api 16 console log</summary>

```
Launching lib/main.dart on emulator-5554 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
E/flutter ( 2650): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(67)] Failed to setup Skia Gr context.
E/flutter ( 2650): [ERROR:flutter/shell/common/platform_view.cc(81)] Failed to create platform view rendering surface
Debug service listening on ws://127.0.0.1:54305/0Maf2V5lvBQ=/ws
Syncing files to device emulator-5554...

```

</details>

While the same ran properly on Emulator api 28:

<img width="332" alt="Screenshot 2021-01-27 at 3 01 08 PM" src="https://user-images.githubusercontent.com/67046386/105975308-d347a600-60b4-11eb-89c3-34272658eea8.png">

<details>
<summary>api 28 console log</summary>

```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:54589/GZy_WaG3US0=/ws
Syncing files to device AOSP on IA Emulator...
D/EGL_emulation(11910): eglMakeCurrent: 0xdfcdf9e0: ver 3 0 (tinfo 0xde1dfb40)
D/eglCodecCommon(11910): setVertexArrayObject: set vao to 0 (0) 1 0

```

</details>

Also, the integration tests ran properly on emulator 28, while throwing below error on api 16:

`Oops; flutter has exited unexpectedly: "HttpException: Connection closed before full header was received, uri = http://127.0.0.1:56186/QFRx3-KvrxU=/ws".`

This may indicate that the emulator 16 may not be compatible to connect to service protocols and could be specific to low level emulators as this (api 16).  See this for example : https://github.com/flutter/flutter/issues/32587

Is there a way for you to verify the same integrations tests on api 16 physical device ? Just trying to see if this issue is specific to emulators or happens with devices as well.  Can you also let us know when does the crash occur ? 


Also, regarding your another question on unable to use `--enable-software-rendering` flag to run tests, there's a similar proposal open describing it, https://github.com/flutter/flutter/issues/43967.  You may follow-up there for updates.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.177, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.177 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2eeeba9c09 (29 hours ago), 2021-01-25 20:52:30 -0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)      • 5200763ebcfa861f • android-arm    • Android 8.1.0
      (API 27)
    • emulator-5554 (mobile) • emulator-5554    • android-x86    • Android 4.1.2
      (API 16) (emulator)
    • macOS (desktop)        • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)           • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Comment by Kleak** [comment]
> Is there a way for you to verify the same integrations tests on api 16 physical device

no unfortunately I can't run them on a real device as i don't have one with me.

**Comment by darshankawar** [comment]
@Kleak 
Same here. We don't have that old physical device to verify this, so not sure if this is specific to emulators or happens on devices too. Couple of questions:

Is your main issue related to app showing white screen on api 16 emulators ? or that you are unable to run integration tests on api 16 emulators ?

**Comment by Kleak** [comment]
> or that you are unable to run integration tests on api 16 emulators ?

This one.

**Comment by darshankawar** [comment]
@Kleak 
For that issue, I'd suggest you to follow-up in the original issue I referred earlier, https://github.com/flutter/flutter/issues/43967.  But one caveat for doing this is, https://github.com/flutter/flutter/issues/43967 seems to be specific to `flutter driver` as I don't see any `integration_test` plugin related labels to it. 
May be you can open a new issue as a proposal to support `--enable-software-rendering` flag for `integration_test` plugin.

**Comment by Kleak** [comment]
will do that thanks
