### ISSUE TITLE
[animations] Migrate to null-safety

### ISSUE THREAD

**Issue by gaetschwartz** [flutter/flutter#74736]
## Use case

Using the [animations ](https://pub.dev/packages/animations) package with null-safety.

## Proposal

Migrate it to null-safety, see the PR here : https://github.com/flutter/packages/pull/261.

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
Live at https://pub.dev/packages/animations/versions/2.0.0-nullsafety.0.
