### ISSUE TITLE
flutter doctor cannot find flutter+dart plugin installed in android studio

### ISSUE THREAD

**Issue by testexample2016** [flutter/flutter#74739]
## Steps to Reproduce

1. flutter doctor cannot find flutter+dart plugin installed in android studio but changing channel to dev or master make it working fine
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

C:\flutter>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (4 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

</details>

**Comment by darshankawar** [comment]
@testexample2016 
This issue is already fixed and merged into master a while back, https://github.com/flutter/flutter/issues/67986.
Although you see those warnings in your `flutter doctor -v` log, the warnings should not matter and you should be able to continue using the plugins as usual.

You may try this solution to see if it works for you, https://github.com/flutter/flutter/issues/68429#issuecomment-740430602

Closing this as already fixed and there's no need to track.

**Comment by PranitModak** [comment]
> @testexample2016
> This issue is already fixed and merged into master a while back, #67986.
> Although you see those warnings in your `flutter doctor -v` log, the warnings should not matter and you should be able to continue using the plugins as usual.
> 
> You may try this solution to see if it works for you, [#68429 (comment)](https://github.com/flutter/flutter/issues/68429#issuecomment-740430602)
> 
> Closing this as already fixed and there's no need to track.

this issue still persist for Windows User
