### ISSUE TITLE
cannot find symbol     flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());

### ISSUE THREAD

**Issue by aaryan9499** [flutter/flutter#74746]
```
C:\Users\hp\Documents\flutter_doctor_appointment\Doctor Prescription\doctor_medicine_prescription\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:16: error: cannot find symbol
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
                                                                      ^
  symbol:   class PathProviderPlugin
  location: package io.flutter.plugins.pathprovider
1 error

FAILURE: Build failed with an exception.

```

**Comment by darshankawar** [comment]
@aaryan9499 
Did you run `flutter pub get` ?
Can you also try `flutter clean` and then `flutter run` to see if it helps ?

Also check out [this](https://stackoverflow.com/a/61970503) similar issue and see if it helps to resolve your issue.

If issue persists, provide `flutter doctor -v`, `pubspec.yaml` and a minimal complete reproducible code sample that shows the issue.

**Comment by aaryan9499** [comment]
flutter run -v

[ +244 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +148 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +83 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +4 ms] executing: [E:\flutter/] git tag --points-at HEAD
[ +275 ms] Exit code 0 from: git tag --points-at HEAD
[   +8 ms] 1.22.6
[  +33 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +192 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [E:\flutter/] git ls-remote --get-url origin
[  +94 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +163 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
[ +196 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +120 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +88 ms] List of devices attached
           96819e1b               device product:RMX1992 model:RMX1992 device:RMX1992L1 transport_id:30 
           192.168.0.5:6666       offline product:RMX1992 model:RMX1992 device:RMX1992L1 transport_id:26
[  +13 ms] C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe -s 96819e1b shell getprop
[ +283 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +299 ms] Found plugin path_provider at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[  +14 ms] Found plugin path_provider_linux at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +5 ms] Found plugin path_provider_macos at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[  +66 ms] Found plugin path_provider_windows at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +63 ms] Found plugin shared_preferences at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[  +32 ms] Found plugin shared_preferences_linux at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[   +8 ms] Found plugin shared_preferences_macos at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[  +64 ms] Found plugin shared_preferences_web at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +51 ms] Found plugin shared_preferences_windows at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[ +551 ms] Found plugin path_provider at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.24\
[   +6 ms] Found plugin path_provider_linux at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +95 ms] Found plugin path_provider_macos at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+6\
[  +82 ms] Found plugin path_provider_windows at E:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +52 ms] Found plugin shared_preferences at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.12+4\
[  +41 ms] Found plugin shared_preferences_linux at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-0.0.2+4\
[  +42 ms] Found plugin shared_preferences_macos at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +3 ms] Found plugin shared_preferences_web at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +6 ms] Found plugin shared_preferences_windows at E:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-0.0.1+3\
[ +152 ms] Generating C:\Users\hp\Documents\flutter_doctor_appointment\Doctor
Prescription\doctor_medicine_prescription\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +120 ms] ro.hardware = qcom
[ +118 ms] Starting incremental build...
[   +8 ms] Initializing file store
[  +24 ms] Skipping target: gen_localizations
[  +52 ms] complete
[  +44 ms] Launching lib\main.dart on RMX1992 in debug mode...
[  +64 ms] E:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
E:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
E:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\hp\AppData\Local\Temp\flutter_tools.e522fd25\flutter_tool.1ed779e6\app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +183 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe -s 96819e1b shell -x logcat -v time -t 1
[ +143 ms] Exit code 0 from: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe -s 96819e1b shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           01-27 23:21:15.554 D/AudioManager(25896): getStreamVolume packageName=com.google.android.youtube, index=14, streamType=3
[   +3 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe -s 96819e1b shell -x logcat -v time -t 1
[ +125 ms] Exit code 0 from: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe -s 96819e1b shell -x logcat -v time -t 1
[  +12 ms] --------- beginning of main
           01-27 23:21:15.580 I/MediaCodec(25896): (0x775f7e2000) Decoder: mInputBufCnt = 25 fps, mOutputBufCnt = 23 fps, mRenderFrameCnt = 26 fps 
[  +33 ms] <- compile package:doctor_medicine_prescription/main.dart
[ +131 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +317 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.4-6686687
                    Installed as C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +9 ms] executing: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +379 ms] Building APK
[ +128 ms] Running Gradle task 'assembleDebug'...
[  +52 ms] gradle.properties already sets `android.enableR8`
[ +100 ms] Using gradle from C:\Users\hp\Documents\flutter_doctor_appointment\Doctor Prescription\doctor_medicine_prescription\android\gradlew.bat.[  +72 ms] C:\Users\hp\Documents\flutter_doctor_appointment\Doctor Prescription\doctor_medicine_prescription\android\gradlew.bat mode: 33279
rwxrwxrwx.
[  +25 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +431 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +18 ms] executing: [C:\Users\hp\Documents\flutter_doctor_appointment\Doctor Prescription\doctor_medicine_prescription\android/]
C:\Users\hp\Documents\flutter_doctor_appointment\Doctor Prescription\doctor_medicine_prescription\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=C:\Users\hp\Documents\flutter_doctor_appointment\Doctor
Prescription\doctor_medicine_prescription\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+10878 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +429 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +331 ms] [ +511 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [   +1 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[ +179 ms] [   +2 ms] executing: [E:\flutter/] git tag --points-at HEAD
[ +247 ms] [ +443 ms] Exit code 0 from: git tag --points-at HEAD
[ +102 ms] [        ] 1.22.6
[ +342 ms] [  +30 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +93 ms] [ +291 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ +112 ms] [        ] origin/stable
[ +210 ms] [        ] executing: [E:\flutter/] git ls-remote --get-url origin
[  +75 ms] [ +236 ms] Exit code 0 from: git ls-remote --get-url origin
[ +115 ms] [        ] https://github.com/flutter/flutter.git
[ +186 ms] [ +322 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
[  +26 ms] [ +209 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +96 ms] [        ] stable
[  +37 ms] [ +143 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +46 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +112 ms] [  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +116 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +116 ms] [  +45 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +121 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ +200 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +351 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +79 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +167 ms] [  +56 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[ +159 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[  +84 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +167 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +293 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +94 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +758 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +64 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +225 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +106 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +280 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +78 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +75 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +14 ms] [ +313 ms] Initializing file store
[  +63 ms] [  +83 ms] Done initializing file store
[ +132 ms] [ +188 ms] Skipping target: gen_localizations
[+1013 ms] [+4429 ms] Skipping target: kernel_snapshot
[+1395 ms] [+1323 ms] Skipping target: debug_android_application
[   +2 ms] [   +1 ms] Persisting file store
[ +131 ms] [  +36 ms] Done persisting file store
[  +71 ms] [  +26 ms] build succeeded.
[  +42 ms] [  +52 ms] "flutter assemble" took 6,638ms.
[ +263 ms] [  +11 ms] ensureAnalyticsSent: 1ms
[  +67 ms] [   +3 ms] Running shutdown hooks
[   +2 ms] [   +1 ms] Shutdown hooks complete
[ +255 ms] [  +10 ms] exiting with code 0
[ +131 ms] Parameter format not correct -
[  +39 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :path_provider:preBuild UP-TO-DATE
[ +113 ms] > Task :path_provider:preDebugBuild UP-TO-DATE
[  +44 ms] > Task :path_provider:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :shared_preferences:preBuild UP-TO-DATE
[   +1 ms] > Task :shared_preferences:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :shared_preferences:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +9 ms] > Task :path_provider:packageDebugRenderscript NO-SOURCE
[  +55 ms] > Task :shared_preferences:packageDebugRenderscript NO-SOURCE
[  +63 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +77 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[ +108 ms] > Task :path_provider:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :path_provider:generateDebugAssets UP-TO-DATE
[   +2 ms] > Task :path_provider:packageDebugAssets UP-TO-DATE
[   +2 ms] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[   +9 ms] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[ +182 ms] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[  +30 ms] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[  +28 ms] > Task :app:mergeDebugAssets
[ +260 ms] > Task :app:copyFlutterAssetsDebug
[  +14 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[ +333 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +53 ms] > Task :path_provider:compileDebugRenderscript NO-SOURCE
[ +245 ms] > Task :path_provider:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :path_provider:generateDebugResources UP-TO-DATE
[  +62 ms] > Task :path_provider:packageDebugResources UP-TO-DATE
[   +3 ms] > Task :shared_preferences:compileDebugRenderscript NO-SOURCE
[ +179 ms] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[  +17 ms] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[  +51 ms] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[   +4 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +5 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +708 ms] > Task :path_provider:checkDebugManifest UP-TO-DATE
[  +14 ms] > Task :path_provider:processDebugManifest UP-TO-DATE
[   +3 ms] > Task :shared_preferences:checkDebugManifest UP-TO-DATE
[  +50 ms] > Task :shared_preferences:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +9 ms] > Task :path_provider:parseDebugLibraryResources UP-TO-DATE
[  +53 ms] > Task :path_provider:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :shared_preferences:parseDebugLibraryResources UP-TO-DATE
[   +7 ms] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[  +89 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :path_provider:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[   +2 ms] > Task :shared_preferences:javaPreCompileDebug UP-TO-DATE
[  +97 ms] > Task :shared_preferences:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :shared_preferences:bundleLibCompileDebug UP-TO-DATE
[   +4 ms] > Task :path_provider:javaPreCompileDebug UP-TO-DATE
[  +43 ms] > Task :path_provider:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :path_provider:bundleLibCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +64 ms] > Task :app:compileDebugJavaWithJavac FAILED
[   +1 ms] 44 actionable tasks: 5 executed, 39 up-to-date
[  +90 ms] C:\Users\hp\Documents\flutter_doctor_appointment\Doctor
Prescription\doctor_medicine_prescription\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:16: error: cannot find symbol[   +7 ms]     flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
[   +1 ms]                                                                       ^
[ +308 ms]   symbol:   class PathProviderPlugin
[  +42 ms]   location: package io.flutter.plugins.pathprovider
[  +54 ms] 1 error
[   +2 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[   +2 ms] Execution failed for task ':app:compileDebugJavaWithJavac'.
[   +2 ms] > Compilation failed; see the compiler error output for details.
[   +2 ms] * Try:
[   +4 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get   
full insights.
[ +142 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 22s
[  +31 ms] Running Gradle task 'assembleDebug'... (completed in 24.9s)
[+6805 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 35,884ms.
[  +65 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +440 ms] ensureAnalyticsSent: 182ms
[  +75 ms] Running shutdown hooks
[   +7 ms] Shutdown hook priority 4
[  +43 ms] Shutdown hooks complete

**Comment by aaryan9499** [comment]
--   pubspec.yaml----

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  google_fonts: ^1.1.1
  simple_animations: ^1.3.3
  gradient_widgets: ^0.5.2
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+3

**Comment by darshankawar** [comment]
@aaryan9499 
As the error from the log says:

`C:\Users\hp\Documents\flutter_doctor_appointment\Doctor
Prescription\doctor_medicine_prescription\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:16: error: cannot find symbol[   +7 ms]     flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
[   +1 ms`

It is pointing to plugin `path_provider`, but I don't see it in `pubspec.yaml` you shared above.

**Comment by aaryan9499** [comment]
After using plugin **path_provider** continuously arise same error

**Comment by darshankawar** [comment]
@aaryan9499 
I see that your folder name `Doctor Prescription` has space in it. Can you update it to `DoctorPrescription` and try again to see if it helps ?

If issue persists, provide a sample repo of your project that we can clone and run to verify the issue.

**Comment by aaryan9499** [comment]
Issue resolve.
Thanks
