### ISSUE TITLE
[canvaskit] spaces appear as crossed out boxes in CJK text

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#74742]
## Steps to Reproduce

1. In the engine repo run `felt test test/canvaskit/canvas_golden_test.dart`
2. Observe that `lib/web_ui/.dart_tool/goldens/engine/web/canvaskit_text_styles_locale_ja.png` looks like this:

![canvaskit_text_styles_locale_ja](https://user-images.githubusercontent.com/211513/105885845-897c9400-5fbe-11eb-9ba1-6ed18240dfac.png)

**Comment by hterkelsen** [comment]
Related SkBug: https://bugs.chromium.org/p/skia/issues/detail?id=11201

**Comment by MrBirb** [comment]
Fwiw the mentioned skia bug was closed as wont fix.

**Comment by yjbanov** [comment]
@MrBirb this is because it was already fixed by the time we filed it. We just need to roll to the latest version.
