### ISSUE TITLE
flutter_tool doesn't clean up old artifacts

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#74772]
When flutter_tool downloads a new version of sky_engine, it unpacks it over the old version in the cache. If files have been removed from the new version (compared to the previously installed version), those are not deleted in the cache - even though they should be.

The old files are confusing the analyzer in some situations, see https://cirrus-ci.com/task/4637233509564416?command=main#L15 as an example (here, wasm.dart has been removed from the dart sdk. However, even after updating flutter it remained in the cache).

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
This may be a blocker for next release cycle, as it trips up the analyzer during a dart migrate/publish
