### ISSUE TITLE
E/flutter ( 6169): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Source file [

### ISSUE THREAD

**Issue by Abenezerfikadu** [flutter/flutter#74774]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Abenezerfikadu 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Abenezerfikadu** [comment]
> Hi @Abenezerfikadu
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, and a minimal complete reproducible code sample?
> Thank you

it's not about flutter doctor -v or flutter run --verbose case, I get this error when I try to read JSON file from JSON asset folder

**Comment by pedromassangocode** [comment]
Can you please provide what was asked in https://github.com/flutter/flutter/issues/74774#issuecomment-768129273?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
