### ISSUE TITLE
Regression: Flings on iOS have too-high velocity

### ISSUE THREAD

**Issue by jet10000** [flutter/flutter#7477]
When I quick slide interface, why always bounce back?

**Comment by abarth** [comment]
When you say "slide", do you mean something to do with scrolling?

**Comment by jet10000** [comment]
yes, scrolling!

**Comment by eseidelGoogle** [comment]
We just got a report of this from customer: leafy as well.

**Comment by eseidelGoogle** [comment]
Leafy reproduced this on an iPhone 5s.  I have lots of iOS devices if someone needs one to repro. :)

**Comment by Hixie** [comment]
I would first check if backing out https://github.com/flutter/flutter/pull/7363 fixes it

**Comment by eseidelGoogle** [comment]
This is a bad regression which blocks folks shipping on iOS.  Definitely need an update today. :D

**Comment by HansMuller** [comment]
Reverting #7363 does fix this problem.  Narrowing down the source of the problem now...
