### ISSUE TITLE
[Local_auth]

### ISSUE THREAD

**Issue by Godfather6666** [flutter/flutter#74789]
Verifying fingerprint errors three times on an iPhone7P will cause the APP to flash back.

**Comment by TahaTesser** [comment]
Hi @Godfather6666 
This is reproduced in https://github.com/flutter/flutter/issues/47465, after third-time screen flash, if you enter two more wrong inputs, the whole app will crash
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
