### ISSUE TITLE
How can can define MODE_PRIVATE,MODE_WORLD_READABLE,MODE_WORLD_WRITABLE in shared_preferences

### ISSUE THREAD

**Issue by shahnawazahmed88** [flutter/flutter#74783]
In shared_preferences, I didn't found a way to define MODE_PRIVATE, MODE_WORLD_READABLE, MODE_WORLD_WRITABLE.

**Comment by pedromassangocode** [comment]
Hi @shahnawazahmed88 
`SharedPreferences` uses `MOODE_PRIVATE`  and by now you don't have the option to change this.

The other options are now deprecated and it is not recommended to use then. See https://developer.android.com/reference/android/content/Context.html#MODE_WORLD_READABLE.
