### ISSUE TITLE
[web]: RadioListTile - A value of type 'Object?' can't be assigned to a variable of type 'int'

### ISSUE THREAD

**Issue by LAPPIT** [flutter/flutter#74796]
Have changed to Flutter beta channel to test Flutter Web on my project and when adapting for null safety I get the error: "A value of type 'Object?' can't be assigned to a variable of type 'int'" on a RadioListTile. I returns according to the documentation an Function(int?), but for some reason the error check thinks it is an Object?. See attached hardcopies.

[RadioListTile - A value of type Object can't be assigned to a variable of type int.docx](https://github.com/flutter/flutter/files/5878638/RadioListTile.-.A.value.of.type.Object.can.t.be.assigned.to.a.variable.of.type.int.docx)

Flutter doctor:

C:\Flutter\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-SE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)

• No issues found!

C:\Flutter\flutter>

I test in the Chrome browser, but here I do not get that far.

**Comment by pedromassangocode** [comment]
Hi @LAPPIT 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by LAPPIT** [comment]
Sorry! Here it comes:

C:\Flutter\flutter>flutter doctor -v
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-SE)
    • Flutter version 1.25.0-8.3.pre at C:\Flutter\flutter
    • Framework revision 5d36f2e7f5 (12 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mariette\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin version 52.0.2
    • Dart plugin version 202.8070

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Mariette\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

C:\Flutter\flutter>

**Comment by pedromassangocode** [comment]
Hi @LAPPIT 
I need a code sample as well.
Thank you

**Comment by LAPPIT** [comment]
Hi,
I just updated the versions in pubspec.yaml to later versions of Dart and Flutter and then the problem went away. It feels strange, but now it works.

I'm sorry to have wasted your time :(

Kind regards, 
Mariette Lindström
