### ISSUE TITLE
Http client very slow if compared with native request call.

### ISSUE THREAD

**Issue by ngminhduong** [flutter/flutter#74794]
I have issue when create http request with flutter it always take double the time when compared with native request.

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.14.6 18G95 darwin-x64, locale en-VN)
    • Flutter version 1.22.5 at /Users/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nmduong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

**Comment by pedromassangocode** [comment]
Hi @ngminhduong 
Can you please elaborate how are you measuring the speed of your request? Keep in mind that speed of internet may depend on your internet connection.

Do you have a minimal reproducible code sample?
Please provide your `flutter doctor -v`.
Thank you

**Comment by iapicca** [comment]
@ngminhduong 
assuming, [but not given](https://github.com/flutter/flutter/issues/74794#issuecomment-768191642), that your assumption is correct
I believe the issue should be addressed on [http](https://pub.dev/packages/http) 's [github](https://github.com/dart-lang/http/issues)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
