### ISSUE TITLE
flutter run -d web : web device no longer available in OS X Catalina (10.15.7)

### ISSUE THREAD

**Issue by ecl66** [flutter/flutter#74793]
## Steps to Reproduce

1. flutter run -d chrome is working (ie web conf enabled)
2. flutter run -d web : web device not available
3. flutter devices => no web device reported

## Logs

<details>
<summary>Logs</summary>

 flutter devices                
1 connected device:
Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

</details>

**Comment by pedromassangocode** [comment]
Hi @ecl66 
As far as I know `web` is not a supported device name to run Flutter web apps. I think you mean `flutter run -d chrome`.

I'm currently using Catalina OS and I am able to build Flutter web apps on Chrome using the command above.
Thank you

**Comment by ecl66** [comment]
Hi Pedro. It was my understanding that I could launch flutter web app as a web server such as to test with any other brower or device on a local network. This is working under Ubuntu and used to work under Catalina with rel 1.24

**Comment by pedromassangocode** [comment]
Hmm, you mean `web-server` device name. This is now disabled by default starting from https://github.com/flutter/flutter/pull/71491 however, you can still use it by running `flutter run -d web-server` or with --show-web-server-device.

**Comment by ecl66** [comment]
Thanks Pedro. Indeed the web-server device no longer appears (doc should be corrected accordingly) but I can run on this device. You may close this issue then. Thanks for all the good work ;)
