### ISSUE TITLE
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by karthikeyanrao** [flutter/flutter#74807]
Can Anyone Solve this error plz 
i am new to Fluttter

Launching lib\main.dart on ASUS X00LD in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     F:\AndroidStudioProjects\flutter_1\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:35: AAPT: error: '' is incompatible with attribute resource (attr) reference.

     F:\AndroidStudioProjects\flutter_1\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:45: AAPT: error: '' is incompatible with attribute resource (attr) reference.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 4s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin integration_test...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateReleaseRFile'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.test:monitor:1.2.0, androidx.test:rules:1.2.0, androidx.test.espresso:espresso-idling-resource:3.2.0, androidx.test:runner:1.2.0, androidx.test.espresso:espresso-core:3.2.0, androidx.annotation:annotation:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

Exception: The plugin integration_test could not be built due to the issue above.

**Comment by pedromassangocode** [comment]
> * What went wrong:
>   Execution failed for task ':generateReleaseRFile'.
> 
> > This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
> > The following AndroidX dependencies are detected: androidx.test:monitor:1.2.0, androidx.test:rules:1.2.0, androidx.test.espresso:espresso-idling-resource:3.2.0, androidx.test🏃1.2.0, androidx.test.espresso:espresso-core:3.2.0, androidx.annotation:annotation:1.0.0
> 


Hi @karthikeyanrao 
Can you please try the suggesttion above and try again?

**Comment by karthikeyanrao** [comment]
Ok bro i will try

**Comment by karthikeyanrao** [comment]
Can i know where is gradle properties

**Comment by karthikeyanrao** [comment]
![16118564686441708455397410012027](https://user-images.githubusercontent.com/78087029/106178623-03c83680-61c0-11eb-876d-64832e7f62b7.jpg)


this is in true only but also it is in error

**Comment by karthikeyanrao** [comment]
The error i got now

Launching lib\main.dart on ASUS X00LD in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\AndroidStudioProjects\flutter_1\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Cannot parse project property android.enableJetifier='true,' of type 'class java.lang.String' as boolean. Expected 'true' or 'false'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
> Failed to apply plugin 'com.android.internal.version-check'.
> Cannot parse project property android.enableJetifier='true,' of type 'class java.lang.String' as boolean. Expected 'true' or 'false'.

Looks like you changed the type of value of some property. Make sure you content look like this:

```properties
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

```

**Comment by karthikeyanrao** [comment]
This is a new Error

Launching lib\main.dart on ASUS X00LD in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\AndroidStudioProjects\flutter_1\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'kotlin:app' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by pedromassangocode** [comment]
Hi @karthikeyanrao 
Alright, I will ask you to open a new issue related to the new error you are facing since the original issue is already solved.
In the new issue please provide the content of your Gradle file in: `F:\AndroidStudioProjects\flutter_1\android\app\build.gradle`
Thank you

**Comment by karthikeyanrao** [comment]
Can u plz say how to send

**Comment by karthikeyanrao** [comment]
#
[build.zip](https://github.com/flutter/flutter/files/5894325/build.zip)

i have attached the file u have asked
u can also send reply to rippleskarthi@gmail.com sir

**Comment by dehypnosis** [comment]
Having exactly same issue
