### ISSUE TITLE
Error when running on Android

### ISSUE THREAD

**Issue by jaredgreener** [flutter/flutter#74825]
Stack Trace:

E/flutter (27136): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
E/flutter (27136): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (27136): <asynchronous suspension>
E/flutter (27136): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (27136): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)
E/flutter (27136): #3      PackageInfo.fromPlatform (package:package_info/package_info.dart:43:25)
E/flutter (27136): #4      main (package:InvictMe/main.dart:30:47)
E/flutter (27136): <asynchronous suspension>
E/flutter (27136): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (27136): #6      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (27136): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (27136): #8      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (27136): #9      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (27136): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (27136): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (27136): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (27136): 

Usage:

void main() async {

  WidgetsFlutterBinding.ensureInitialized();

  String deviceUUID = await DeviceId.getID;

  PackageInfo packageInfo = await PackageInfo.fromPlatform();

  final Config config = Config(deviceUUID: deviceUUID, appVersion: packageInfo.buildNumber);
  
  await getDatabasePath().then((value) {
    print(value);
  });

  runApp(InvictMeApp(config));

}

**Comment by alectogeek** [comment]
@jaredgreener have you figured out what was the problem?
