### ISSUE TITLE
iOS app is janky on first run. Need short-term solution

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#74824]
Hello there!

My iOS application is severely janky on the first run. The issue is actual for a long long time. (Shaders compilation jank)
@zanderso said:
`We will continue to be hard at work on solving first-run shader compilation jank on both iOS and Android, as we currently view it as one of the most serious performance issues facing Flutter. We are focusing our efforts on a long-term, maintainable solution to this problem outlined by the linked issues.`

I've talked to many mobile developers (both Flutter and native) and on behalf of a large group of people I want to ask you to provide some short-term solution that would work now. Lots of people who trusted your advertisement about 60 FPS are losing their money including me. Guys, we need not a long-term and maintainable, but working now solution. 

**Perfection is the enemy of done.** We will be happy to receive any improvement.

**Comment by alectogeek** [comment]
And the https://github.com/flutter/flutter/issues/74631 has P4 priority :(

**Comment by zanderso** [comment]
Unfortunately, this issue is not actionable in its current form. Please follow the guidance here https://github.com/flutter/flutter/issues/74833 to give us something more concrete to go on. In the meantime, I'll close this issue, but feel free to re-open with more information. Thanks!

**Comment by Renesanse** [comment]
@alectogeek my short-term solution: https://gist.github.com/Renesanse/1572e5090075fd79251d4fd4543d7274

**Comment by danReynolds** [comment]
@zanderso Could we get a ballpark timeline estimation? We can wait a month, maybe two if it'll be fixed but if this is a 6-month roadmap item or a "we don't know how hard/long it'll take" issue, we'll go forward with our launch as we can't wait that long.

**Comment by AphinityApp** [comment]
> @zanderso Could we get a ballpark timeline estimation? We can wait a month, maybe two if it'll be fixed but if this is a 6-month roadmap item or a "we don't know how hard/long it'll take" issue, we'll go forward with our launch as we can't wait that long.

+1 for this. and we will have to abandon flutter and do a rebuild in native, because this issue will mean a horrible experience for our first time users. The issue needs to be a P2 issue at the very least, not a P4 issue. Again the flutter team is not taking this seriously enough and it shows

**Comment by vukhacbiet** [comment]
@AphinityApp  It seems they don't care about iOS, maybe that's a strategy...

**Comment by danReynolds** [comment]
Hello all! I created this issue to help the Flutter team debug jank: https://github.com/flutter/flutter/issues/76180

feel free to +1 so that we can get more eyes on this issue
