### ISSUE TITLE
[web] main.dart.js is downloaded and cached twice

### ISSUE THREAD

**Issue by czetxinc** [flutter/flutter#74831]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run `flutter build web`.
3. Deploy to a server with https support (eg. `firebase deploy` after configuring hosting)
4. Open Chrome in Incognito, open DevTools and go to the Network tab
5. Load the newly deployed web page
6. Observe duplicate request for `main.dart.js`
6. Wait for service worker to finish installing and activating
7. Refresh page 
8. In DevTools go to Application/Cache/Cache Storage/flutter-app-cache
9. Observe that `main.dart.js` is cached twice

**Expected results:** 

`main.dart.js` is only downloaded and cached once

**Actual results:** 

![Screenshot from 2021-01-27 19-34-43](https://user-images.githubusercontent.com/78102084/106043453-1e7aac80-60e7-11eb-8ee2-e65b3a9ee6df.png)

![Screenshot from 2021-01-27 19-35-40](https://user-images.githubusercontent.com/78102084/106043480-29cdd800-60e7-11eb-8d0c-3ff2299589e0.png)

Also after loading [gallery.flutter.dev](https://gallery.flutter.dev)

![Screenshot from 2021-01-27 16-05-56](https://user-images.githubusercontent.com/78102084/106043965-c7c1a280-60e7-11eb-813c-06cd6c901f2b.png)

![Screenshot from 2021-01-27 16-01-10](https://user-images.githubusercontent.com/78102084/106043990-d019dd80-60e7-11eb-9e26-5e2cdd4d3875.png)

**Comment by pedromassangocode** [comment]
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.229, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.229 at /Users/pedromassango/Code/flutter_master
    • Framework revision 650b240634 (72 minutes ago), 2021-01-27 21:39:06 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

**Comment by yjbanov** [comment]
I think the first one is the `index.html` requesting `main.dart.js` from the service worker, and the second one is the service worker actually downloading it from the network. So maybe this is not an issue? @jonahwilliams WDYT?

**Comment by yjbanov** [comment]
Tip: in order to see the duplicate download I had to check the "Preserve log" checkbox in the network tab. Otherwise, Chrome hides the first network request for some reason.

**Comment by jonahwilliams** [comment]
I would be concerned if each subsequent hit downloaded it twice, but if its only the first run then that is expected. The service worker cannot cache anything until it is activated, and that will by necessity happen after the page is loaded over the network.

I'm not aware of any other way to do the caching here.

**Comment by czetxinc** [comment]
@jonahwilliams 
From my testing of the generated service worker code, when the service worker installs, it fetches and caches `main.dart.js?revision=hash`. At this point `main.dart.js` is already fetched by the browser (from the <script> tag in index.html) without any query param. The version of `main.dart.js` with the revision query is never used in future page loads and is totally redundant.

On the second page load, after the service worker is installed and activated it does a new fetch for `main.dart.js` without the revision query. This request comes again from the <script> tag in index.html but this time the browser sends the request through the service worker, as it is now activated. This second fetch hits the browser's cache (if there is caching setup on the server) as main.dart.js was fetched by the browser the first time the page was loaded.

This is visible in the following screenshot of the second page load. (from gallery.flutter.dev)

![Screenshot from 2021-01-29 01-42-38](https://user-images.githubusercontent.com/78102084/106213427-56601d80-61d5-11eb-8d3d-d1c7c1f23a62.png)

**Comment by czetxinc** [comment]
I guess the point I am trying to make is that all files fetched by the service worker on the install event, that use the ?revision=hash query are never used.
