### ISSUE TITLE
The `flutter create` command should be allowed in some directories in the repo

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#74839]
Currently, there are multiple directories in the repo that contain the shims needed to run an app: `dev/integration_tests`, `dev/manual_tests`, and `examples` to name a few.

It would be helpful if, instead of preventing it outright, the `flutter create` command would allow itself to be run in a select subset of directories inside of the Flutter repo itself.  This would make updating the shims easier, but still protect new users from the confusion of creating their projects inside of the repo.

**Comment by jmagman** [comment]
Context in https://github.com/flutter/flutter/issues/6480
