### ISSUE TITLE
Flutter iOS Application rejected by Apple because of "white screen on startup"

### ISSUE THREAD

**Issue by TheMkrage** [flutter/flutter#74843]
I am receiving this message with a rejection when I submit my app for review on the App Store: 
"Specifically, your app displayed a white, blank screen when we launched your app."

When I test the app on device, everything appears to be working fine. I have tried the following to test:
1. `flutter build ios`
`flutter run`

2. `flutter build ios --release`
`flutter run`

3. Test with VSCode's run feature. 

4. Run in xcode onto physical device both in Debug and Release schema settings
5. If I archive, and upload the same build to Testflight, the app can be installed and ran without issue on several different devices.

While all of these methods work on my physical iphone, when I run
`flutter build ios --release`
open xcode
archive
upload with Organizer in xcode

The app is rejected by Apple. I searched around and found nothing that solves my issues. Any suggestions or good next steps?

flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/matthewkrager/flutter
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/matthewkrager/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
```

**Comment by UdaraWanasinghe** [comment]
What you can do is to add splash screen to the app. https://flutter.dev/docs/development/ui/advanced/splash-screen#ios-launch-screen

**Comment by TahaTesser** [comment]
Hi @TheMkrage 
Please make sure you don't any aawait future before the UI loads in either the `main` function, `init` function of the initial screen, or any other places where await might be delaying your UI. 
Test your packages, make sure none of them is slowing your UI or main thread. If it not possible to remove, try adding Splash screen. 

This doesn't look like a bug, if you think otherwise, please provide a reproducible code sample 
Thank you

**Comment by TheMkrage** [comment]
@TahaTesser  I can revisit the code and see if anything is blocking the main method somehow. And I can add a splash screen in xcode. Unfortunately, I will only know if this fixes the issue a day after since it is only happening for Apple. 

As I mentioned, this issue only shows up for the reviewers at Apple. None of the testflight testers or myself are able to reproduce, so I am unsure how to reproduce here. Is there anything that would change in a release build that I could simulate?

Thanks

**Comment by TahaTesser** [comment]
@TheMkrage 
Please do, let us know, when testing make sure your installing fresh or test a new device 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
