### ISSUE TITLE
Widget/Material API doc confusion

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#7484]
Go to https://docs.flutter.io/ and search for Scaffold, or Row, or Table, or just about any layout widget. You'll see something like this:

![screen shot 2017-01-13 at 10 42 05 am](https://cloud.githubusercontent.com/assets/6293442/21941303/f9fbd596-d97c-11e6-914c-1e9641d0f054.png)

How do I know if I want Row from Widget, or Row from Material? Visually, these pages look identical, but are they?

This is rather confusing.

**Comment by eseidelGoogle** [comment]
This is https://github.com/dart-lang/dartdoc/issues/1158 I believe, which is already fixed in dartdoc, just not yet released.

**Comment by devoncarew** [comment]
I opened https://github.com/dart-lang/dartdoc/issues/1325 to publish a new dartdoc -

**Comment by Hixie** [comment]
Fixed
