### ISSUE TITLE
Dart engine upgrade causes Windows terminal font reset

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#74864]
There's something very weird going on with flutter upgrade on Windows in the last few days. Whenever there's a Dart engine upgrade, the terminal font resets in a way I have never seen before on Windows from a client app (setting the window from the system TrueType font to a fallback bitmap font).

Screenshot demonstrates the issue. 
https://user-images.githubusercontent.com/2319867/106079834-d3eb3700-60ca-11eb-83e4-6b07bb3351b0.mov

**Comment by zanderso** [comment]
I am not able to reproduce this. I tried triggering updates under cmd.exe, PowerShell, and Windows Terminal, and did not see the effect in the video. @timsneath cmd.exe is not really supported. See [here](https://flutter.dev/docs/get-started/install/windows#system-requirements). Could you share a video of what the update looks like when invoked in PowerShell? Thanks!

**Comment by aam** [comment]
Invocations of powershell scripts from under cmd.exe shell could lead to change in font or background color if powershell background is different from cmd.exe one.
I propose we run powershell functions without visualization progress effects therefore fixing the problem. See https://gist.github.com/aam/09e5b7388879ce969a1dca03848c4520
