### ISSUE TITLE
$ which dart returns no dart in path. dart language server crashing returning Invalid file path

### ISSUE THREAD

**Issue by CadeMichael** [flutter/flutter#74863]
after several works of working fine something in dart broke today and started returning the error.

Error - 10:54:12 AM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
/volumes/A/GXC-iOS/lib/views/thumbnail.dart
[Error - 10:54:12 AM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
/volumes/A/GXC-iOS/lib/views/thumbnail.dart
[Error - 10:54:21 AM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
/volumes/A/GXC-iOS/lib/views/thumbnail.dart
[Error - 10:55:39 AM] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
/volumes/A/GXC-iOS/lib/views/thumbnail.dart

only when I tried to access my  thumbnail.dart file. and after noticing this the `$which dart` terminal command began to fail aswell.

**Comment by pedromassangocode** [comment]
Hi @CadeMichael 
Can you please elaborate what happened for this error to appear?
I'm not really sure that this is a problem with Flutter!

Can you please provide your `flutter doctor -v`?
Thank you

**Comment by CadeMichael** [comment]
Thank you for your response,

 I am using the 17.0 branch of flutter as the project I'm working on requires the older version. I think that dart not being in path and this error is a symptom of some bugs in the older release that I will have to deal with, but I'm not sure.

I was able to get the "not valid file path" to work after fixing some syntax in the broken file which doesn't make sense as the server should be able to lint errors.

**Comment by pedromassangocode** [comment]
Hi @CadeMichael 
Assuming that you meant `1.17.0`, this version of Flutter is too old and the issue you are facing may be already solved on latest version. Please upgrade and try again, if the issue persists, write in the comments bellow and provide your `flutter doctor -v`.

In the other hand, if you are facing a different issue now, please feel free to open a new issue and filling the issue-template.

Thank you
