### ISSUE TITLE
[shared_preferences] Support nnbd

### ISSUE THREAD

**Issue by gaetschwartz** [flutter/flutter#74876]
Sub-packages:
- [x] shared_preferences_platform_interface
- [x] shared_preferences_linux (https://github.com/flutter/plugins/pull/3523)
- [x] shared_preferences_macos
- [x] shared_preferences_web (https://github.com/flutter/plugins/pull/3523)
- [x] shared_preferences_windows (https://github.com/flutter/plugins/pull/3516)
- [ ] shared_preferences - could be migrated in advance of the above by un-endorsing not-yet-migrated implementations

## Use case

Anyone using nnbd would need nnbd support for shared_preferences.

## Proposal

As it probably is one of the most depended on package we would need to support nnbd soon. Is  there any PR working on it ? If not I can make one, if yes I'd gladly help !

Note : I'll also have to refactor https://github.com/flutter/flutter/issues/64739 to support nnbd and then it will hopefully be reviewed !

**Comment by thisisamank** [comment]
Hi, @gaetschwartz are you working on it? I would love to collaborate with you on this :)

**Comment by gaetschwartz** [comment]
@thisisamank I am not as of now, was unsure if anyone was already working on it. Sure, we can collaborate. Can you fork and create a branch ? I'm not home right now.

**Comment by thisisamank** [comment]
@gaetschwartz I have forked and created a branch `iss74876` I am a newbie to the opensource world, so can you guide me on what next step should I take?

**Comment by gaetschwartz** [comment]
I just migrated `path_provider_linux`. Was really quick so it didn't really necessitate any collaboration. I will see how it goes and keep you updated @thisisamank

**Comment by Sameerkash** [comment]
@stuartmorgan  is there a PR for `path_provider_macos` and `path_provider_web` ? 
In need of null safe `shared_preferences` as a dependency, happy to help with the migration

**Comment by stuartmorgan** [comment]
> @stuartmorgan is there a PR for `path_provider_macos` and `path_provider_web` ?
> In need of null safe `shared_preferences` as a dependency, happy to help with the migration

`path_provider` is now tracked at https://github.com/flutter/flutter/issues/75240 to provide a central place for discussion.

I've also modified this issue to better match the format of the various tracking bugs that are now filed under the overall umbrella of https://github.com/flutter/flutter/issues/75247.

**Comment by Sameerkash** [comment]
@stuartmorgan  sounds good, I would like to work on migrating `shared_preferences`, I'm watching dependencies to migrate.

**Comment by stuartmorgan** [comment]
> @stuartmorgan sounds good, I would like to work on migrating `shared_preferences`, I'm watching dependencies to migrate.

`shared_preferences_windows` and `shared_preferences_web` can be migrated now; currently only `shared_preferences_linux` is blocked (which should be resolved soon)

**Comment by Sameerkash** [comment]
> > @stuartmorgan sounds good, I would like to work on migrating `shared_preferences`, I'm watching dependencies to migrate.
> 
> `shared_preferences_windows` and `shared_preferences_web` can be migrated now; currently only `shared_preferences_linux` is blocked (which should be resolved soon)

On it.

**Comment by gaetschwartz** [comment]
I migrated the platform plugins at https://github.com/flutter/plugins/pull/3523. Only `shared_preferences` is left to do.

> On it.

Sorry @Sameerkash if I cut you off, but I had time and figured it shouldn't take so long.

**Comment by Sameerkash** [comment]
> I migrated the platform plugins at [flutter/plugins#3523](https://github.com/flutter/plugins/pull/3523). Only `shared_preferences` is left to do.
> 
> > On it.
> 
> Sorry @Sameerkash if I cut you off, but I had time and figured it shouldn't take so long.

Ahhh, okay I think the issue wasn't referenced properly in my PR. I'm currently migrating `shared_prefrences_windows`. 
and yeah I'd have liked to work on rest as well, but okay 

Which one are you saying is left?   `shared_preferences_web`?  @gaetschwartz

**Comment by gaetschwartz** [comment]
@Sameerkash I migrated **all** platform plugins meaning :


- [x] shared_preferences_linux (https://github.com/flutter/plugins/pull/3523)
- [x] shared_preferences_web (https://github.com/flutter/plugins/pull/3523)
- [x] shared_preferences_windows (https://github.com/flutter/plugins/pull/3523)

Again sorry if I cut you out, it was taking some time and many people are waiting for it.

**Comment by Sameerkash** [comment]
@gaetschwartz , I rasied the request yesterday and was only waiting for a review. And I'm on my way to push the fixes as well.

**Comment by gaetschwartz** [comment]
Alright, you didn't mention the issue so I didn't see it. I can remove the `shared_preferences_windows` part if needed. All of my tests are passing though. Will see what is more convenient.

**Comment by stuartmorgan** [comment]
Thanks to both of you for jumping on this! Looks like we should easily be able to get this published next week 🙂

**Comment by Sameerkash** [comment]
@stuartmorgan I saw a PR open for every other package. Is everything ready to go or is there any other package remaining?

**Comment by stuartmorgan** [comment]
> is there any other package remaining?

I filed https://github.com/flutter/flutter/issues/75567 as a placeholder for a full list of things in flutter/packages that need migration, if you're looking for more. (You could potentially also look at the broader ecosystem of Flutter packages, and see if there's are any that interest that haven't migrated, and reach out to their maintainers.)

**Comment by stuartmorgan** [comment]
Platform implementations are all published if someone wants to put together a PR for the app-facing package now. If not, I'll do it sometime tomorrow.

**Comment by gaetschwartz** [comment]
@stuartmorgan Opened a PR here : https://github.com/flutter/plugins/pull/3526

**Comment by nt4f04uNd** [comment]
@stuartmorgan interfaces updates are still not on pub.dev

**Comment by stuartmorgan** [comment]
Sounds like your SDK version is too old; you should update Flutter.
