### ISSUE TITLE
Issue with the webview_flutter when getting the current address in certain pages. 

### ISSUE THREAD

**Issue by gabxap** [flutter/flutter#74870]
Currently working with webview_flutter and getting the current address with the OnPageStated() method and updating it in a text field. It gets the new address when navigating in certain webpages such as Google but when navigating in other webpages such as the mobile versions of Facebook or YouTube it doesn't update the new addresses, only once I call the reload method in the WebView the address in the textfield gets updated.  I know that probably it is because these webpages really doesn't charge another page when updating the urls (Probably there's some Javascript framework behind). Is this something normal to happen with this plugin? Does anyone know a work around for this? Or maybe this can be some kind of new feature that can be added in the plugin. 

```

class WebViewWidget extends StatelessWidget {
  final HomeController homeController;

  const WebViewWidget({Key key, this.homeController}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: homeController.url,
      javascriptMode: JavascriptMode.unrestricted,
      onPageStarted: (String address) {
        homeController.onPageStarted(address);
      },
      onPageFinished: (_) {
        SystemChannels.textInput.invokeMethod('TextInput.hide');
      },
      onWebViewCreated: (WebViewController controller) {
        homeController.setWebViewController(controller);
      },
    );
  }
}
```

```

void onPageStarted(String address) {
_addressBarController.text = text;
}



```

**Comment by pedromassangocode** [comment]
Hi @gabxap 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by gabxap** [comment]
> Hi @gabxap
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the actual vs expected results?
> Thank you

**Flutter doctor -v** 
```

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-PE)
    • Flutter version 1.22.6 at /Users/jumpbotron/programming/installations/flutter
    • Framework revision 9b2d32b605 (6 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at /Users/jumpbotron/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Mi A3 (mobile) • ba2b9fba2ef7 • android-arm64 • Android 10 (API 29)

• No issues found!
```
**Code sample:**

**WebView**
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:retro/controllers/browser_controller.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewWidget extends StatelessWidget {
  final BrowserController browserController;

  const WebViewWidget({Key key, this.browserController}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: browserController.url,
      javascriptMode: JavascriptMode.unrestricted,
      onPageStarted: (String address) {
        browserController.onPageStarted(address);
      },
      onPageFinished: (_) {
        SystemChannels.textInput.invokeMethod('TextInput.hide');
      },
      onWebViewCreated: (WebViewController controller) {
        browserController.setWebViewController(controller);
      },
    );
  }
}
```
**Business Logic** 
```
class BrowserController extends GetxController {
  WebViewController _controller;
  TextEditingController _addressBarController;
  String _url = 'https://www.google.com/';

  WebViewController get controller => _controller;
  TextEditingController get addressbarcontroller => _addressBarController;
  String get url => _url;

  @override
  void onInit() {
    super.onInit();
    _addressBarController = new TextEditingController(text: "://home");
  }


  void setWebViewController(WebViewController someController) {
    _controller = someController;
  }

  void onPageStarted(String address) {
    _addressBarController.text = address;
    _url = address;
  }

```
**TextField**
```

class SearchBar extends StatelessWidget{
@override
      Widget build(BuildContext context) {
          return TextField(
                controller: browserController.addressbarcontroller,     
          );
     }
}

```

**Expected result:**
A normal browser such as Brave updates the current url at any time. Including Youtube urls when clicking a video
![brave](https://user-images.githubusercontent.com/24376974/106181422-92f72f00-616b-11eb-9497-92173da21c86.gif)


**Actual result:**
My browser does not update the urls when navigating in certain webpages such as YouTube (clicking a video )but in other yes such as searching in Google yes. I am using the OnPageStarted() method of the WebView plugin which has a parameter called String adress.
![retro](https://user-images.githubusercontent.com/24376974/106181660-dea9d880-616b-11eb-84b0-befb8e0a25bb.gif)

**Comment by pedromassangocode** [comment]
Hi @gabxap 
Can you please provide a code sample that does not use any third-party plugin/package? Also, please try to provide a complete code that I can just copy/paste and run it.
Thank you

**Comment by gabxap** [comment]
> Hi @gabxap
> Can you please provide a code sample that does not use any third-party plugin/package? Also, please try to provide a complete code that I can just copy/paste and run it.
> Thank you

Hey don't worry I already solved it constantly asking the route with another method.
