### ISSUE TITLE
"--cache-sksl" reports "No data was received"

### ISSUE THREAD

**Issue by bianning-nl** [flutter/flutter#74873]
try
```
flutter run lib/app/main.dart --profile --cache-sksl --purge-persistent-cache
```
but
```
No data was received. To ensure SkSL data can be generated use a physical device then:
  1. Pass "--cache-sksl" as an argument to flutter run.
  2. Interact with the application to force shaders to be compiled.
```
flutter doctor -v
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.24.0-10.2.pre at /Users/bian/opt/flutter
    • Framework revision 022b333a08 (2 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost
```

**Comment by iapicca** [comment]
@bianning-nl 
your flutter version is quite old, can you please run `flutter upgrade -f`

**Comment by pedromassangocode** [comment]
Hi @bianning-nl 
Please follow https://github.com/flutter/flutter/issues/74873#issuecomment-768906369. If the issue persists, provide your `flutter doctor -v` and the device information where you are facing this issue, along with a reproducible code sample.
Thank you

**Comment by lpylpyleo** [comment]
I encountered this issue, too.

`flutter run --profile --cache-sksl`

```
No data was receieved. To ensure SkSL data can be generated use a physical device then:
  1. Pass "--cache-sksl" as an argument to flutter run.
  2. Interact with the application to force shaders to be compiled.
  ```
By the way, the word 'receieved' has a typo.

flutter doctor -v                 
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-CN)
    • Flutter version 1.22.6 at /Users/spikeliao/SDK/flutter
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/spikeliao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Spike 的 iPad (mobile) • 00008020-001A4C8036B8003A • ios • iOS 14.3

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
> No data was receieved. To ensure SkSL data can be generated use a physical device then:
>   1. Pass "--cache-sksl" as an argument to flutter run.
>   2. Interact with the application to force shaders to be compiled.

Hi @bianning-nl 
Can you please follow the suggestion in the logs?

**Comment by Hixie** [comment]
@bianning-nl What device were you testing with?

**Comment by evetechsolutions** [comment]
@Hixie I had the same exact problem today, I have Flutter version 1.22.3 and I used a real device to try capture the shaders (iPhone XS with iOS 14.4)

**Comment by Hixie** [comment]
@evetechsolutions Can you file a new bug with the precise steps to reproduce (including any source code that's necessary if you need something beyond `flutter create`'s default template), listing what devices and command lines you used? That would be super helpful. You can cc me on the new bug if you want and I can prioritize it accordingly.

**Comment by evetechsolutions** [comment]
@Hixie I've updated my Flutter version to 2.0 as I wanted to make sure the problem wasn't a too old Flutter version. As I thought, I was able to cache the SkSL without any problem after updating, so the problem was the version I was using
