### ISSUE TITLE
test

### ISSUE THREAD

**Issue by colbort** [flutter/flutter#74889]
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 846 pos 12: 'activity.isScrolling': is not true.

**Comment by TahaTesser** [comment]
Hi @colbort 
duplicate of https://github.com/flutter/flutter/issues/53937
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
