### ISSUE TITLE
video_player Dependency is not playing video for Desktops (like Windows/Mac/Linux)

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#74887]
Please suggest if any other Dependency is there to play videos properly on Flutter Desktop Application.

**Comment by TahaTesser** [comment]
Hi @unoravi 
`video_player` isn't currently supported on these `macOS `, `Linux`, and `Windows`.
https://github.com/flutter/flutter/issues/41688
https://github.com/flutter/flutter/issues/39091
https://github.com/flutter/flutter/issues/37673

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
