### ISSUE TITLE
PageView item view page is not visible, still drawing problems call build，pls help me.

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#74883]
pls help me. thank you .
PageView item view page is not visible, still drawing problems call build(BuildContext context), how to make the page not call when the page is not visible, improve performance

i do it on item child view.
AutomaticKeepAliveClientMixin 

@override
  bool get wantKeepAlive => true;

**Comment by pedromassangocode** [comment]
Hi @chongbo2013 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample and the actual vs expected results?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
