### ISSUE TITLE
Webview flutter doesn't work when app upload to google play developer

### ISSUE THREAD

**Issue by sikking100** [flutter/flutter#74893]
i make my application with flutter stable version, and inside my app i have a feature that open an url by webview package, when i run it from debug mode it works fine, but when i upload it to google play developer the webview page doesn't work and it just show me a whitescreen, i use webview_flutter 1.0.7 by flutter.dev, does anyone experience this?

**Comment by darshankawar** [comment]
@sikking100 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
What exactly you mean by `uploading it to google player developer` ? Also provide details around it to properly replicate the issue.

**Comment by iipavlov** [comment]
I have the same issue.
Running in debug mode is ok.

When running a production build the following error is reported:

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
        at io.flutter.plugin.platform.j$a.f(Unknown Source:87)
        at io.flutter.embedding.engine.i.j$a.b(Unknown Source:139)
        at io.flutter.embedding.engine.i.j$a.g(Unknown Source:149)
        at f.a.c.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.d(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
    , null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:742)
    <asynchronous suspension>
```

**flutter doctor output:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on macOS 11.1 20C69 darwin-x64, locale en-BG)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

/android/build.gradle
...
```
buildscript {
    ext.kotlin_version = '1.4.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

/android/app/build.gradle
....
```
minSdkVersion 21
targetSdkVersion 29
```

**Comment by sikking100** [comment]
> @sikking100
> Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
> What exactly you mean by `uploading it to google player developer` ? Also provide details around it to properly replicate the issue.

this is my flutter doctor -v
<img width="1280" alt="Screen Shot 2021-01-29 at 22 03 58" src="https://user-images.githubusercontent.com/55334671/106284310-04bf9d80-627e-11eb-9a16-0eb4c9544304.png">

this is my code
<img width="881" alt="Screen Shot 2021-01-29 at 22 04 22" src="https://user-images.githubusercontent.com/55334671/106284361-19039a80-627e-11eb-9c6b-38e51bbf0f92.png">

what exactly i mean by uploading it to google player developer is i build bundle my application and upload it to internal testing in google play developer, it works fine when i debug it on local, but if i install my application from google play, the webview doesn't work and just show me a white screen.

**Comment by darshankawar** [comment]
@sikking100 
Do you see the white screen if you try to run `flutter run --release` or `flutter build apk` and then install it on a device and run ?
Also for better readability, please post your reproducible code sample in text format instead of a screenshot.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
