### ISSUE TITLE
Scrollbar scrolls when dragging in iOS but fails on Android. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#74907]
### Minimal reproducible code:

```dart
final _controller = ScrollController();
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: Scrollbar(
      controller: _controller,
      thickness: 20,
      isAlwaysShown: true,
      child: ListView.builder(
        controller: _controller,
        itemCount: 20,
        itemBuilder: (_, i) => ListTile(title: Text('Item $i')),
      ),
    ),
  );
}
```

As you can see in the following screenshots, the Android one fails to drag. However, if I use `CupertinoScrollBar` it works on both the platforms, but why a regular `Scrollbar` doesn't scroll on Android, is this a bug?

### Screenshot (working in iOS)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/65380329/106175637-a53a9280-6196-11eb-9afb-81400f2fba5b.gif)

### Screenshot (NOT working in Android)

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/65380329/106176232-55a89680-6197-11eb-85e4-2af9660c5cda.gif)

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Mac OS X 10.15.7)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] VS Code (version 1.49.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by Piinks** [comment]
Hi @iLoveDocs It looks like the version of Flutter you are using does not contain the latest Scrollbar updates.
Dragging was enabled for all scrollbars in https://github.com/flutter/flutter/commit/770a9b25d91a0a57b04885239025b87d976dcd20 which is first tagged in version 1.26.0-1.0.pre

**Comment by nt4f04uNd** [comment]
@Piinks what is the motivation of this change? it doesn't match native behaviour.
if you add some enhancement of widgets that are supposed to represent native ones, it should be by default match native and tweaked by a parameter, i.e. in this case not draggable by default and enablled with `draggable` parameter. now it's enabled and you can't disable it and i was astonished you decided to make it in the way it is right now

**Comment by nt4f04uNd** [comment]
@Piinks moreover i want to note a bug for you with previous implementation that is illustrated in the op - scrollbar consumes pointer events while it should be ignored and allow dragging the scrollable underneath it

**Comment by Piinks** [comment]
Hi @nt4f04uNd can you file a new bug describing your issue? Please include a reproducible code sample and the output of flutter doctor. Thanks! :)
