### ISSUE TITLE
Refresh to init page url_launcher even used BLOC

### ISSUE THREAD

**Issue by Faisal282** [flutter/flutter#74914]
So when i click the material / which of the container. the modal link pop up showed. but my page is automatically initialize. so can i click the material without auto initialize and change to my main page.

**Comment by pedromassangocode** [comment]
Hi @Faisal282 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
