### ISSUE TITLE
Mac-Android specific salt states are running on mac-ios test beds 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74913]
Mac ios machines do not have android phones attached making the android-sdk step fail and preventing some other steps from running. We prevent this problem we need to separate how the states are assigned to mac-ios and mac-android test beds.

\cc @keyonghan

**Comment by keyonghan** [comment]
This is fixed by configuring salt.

**Comment by godofredoc** [comment]
For this type of issues should we track until they land to prod?

**Comment by keyonghan** [comment]
Good point. Reopen.

**Comment by godofredoc** [comment]
Blocked on the salt configs propagating to prod master.

**Comment by godofredoc** [comment]
@keyonghan can we close this one?

**Comment by keyonghan** [comment]
Configs have propagated.
