### ISSUE TITLE
Generate DevTools deep links for layout errors

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#74918]
Currently, deep links are only supported for renderflex overflow errors. We'd like to support deep links for all layout errors where possible.

**Comment by goderbauer** [comment]
@kenzieschmoll Do you need help from the framework team for this? If so, could you provide some details on what would need to be implemented?

**Comment by kenzieschmoll** [comment]
This work is no longer a priority. We can reopen this issue if we decide to do this in the future.
