### ISSUE TITLE
DeviceLab salt states failing to copy mobileprovision files

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74912]
If the provisioning of the machine fails to copy of the mobileprovision file then it is not attempted anymore when it finds the certificate. This causes several unrelated problems very difficult to debug and triage.

To solve this problem we need to:

- [x] Verify if copying the mobileprovision is needed independently of copying the certificate
- [x] Add a new health check to ensure mobile provision and certificates are valid.

\cc @jmagman @keyonghan @yusufm

**Comment by godofredoc** [comment]
Change to copy the mobileprovision file correctly has landed.

**Comment by keyonghan** [comment]
Health check added: https://github.com/flutter/flutter/issues/74960
