### ISSUE TITLE
Support Flutter desktop Linux x64 host/Linux arm64 target cross-build by building additional gen_snapshot binary

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#74929]
The PR https://github.com/flutter/flutter/pull/61221 unblocks developing Linux arm64 target Flutter apps from Linux arm64 host. However, in order to cross-build Linux arm64 target apps from Linux x64 host machines, an additional gen_snapshot binary will have to be built.

Part of https://github.com/flutter/flutter/issues/60678

**Comment by HidenoriMatsubayashi** [comment]
I plan to start considering this task from next week.

**Comment by yangcheng** [comment]
great, happy to help with early testing

> I plan to start considering this task from next week.

**Comment by HidenoriMatsubayashi** [comment]
I’m sorry to keep you waiting.

**Comment by christopherfujino** [comment]
> I plan to start considering this task from next week.

If you work on this, I would recommend writing up a short (1 page) document on what to name the new binary, where the compiled binary will be uploaded to, and what the tool code that downloads it will look like, and then you can share the document with me. If I remember, when I considered doing this, it was not obvious how to handle these decisions, so I think discussing and getting agreement on them first will save you time in code review.

**Comment by HidenoriMatsubayashi** [comment]
@christopherfujino 
I updated the design document. I considered it again, and I found it will be easier than I thought before. Could I ask you to confirm "gen_snapshot for cross-building" section in https://docs.google.com/document/d/19tzWySgtgtTA99XQsjx5Pg0SFJeZKXyUlYavR0EXv8c/edit?usp=sharing?
![image](https://user-images.githubusercontent.com/62131389/120880487-db38c900-c605-11eb-958a-67d42a9ffd71.png)

**Comment by vinman1** [comment]
@HidenoriMatsubayashi , I'm very interested in being able to cross-compile a flutter app (linux x86_64 -> linux arm64). Can you please provide an update on this issue? Are there development builds (and instructions) available to try/test? Thanks.

**Comment by christopherfujino** [comment]
> @HidenoriMatsubayashi , I'm very interested in being able to cross-compile a flutter app (linux x86_64 -> linux arm64). Can you please provide an update on this issue? Are there development builds (and instructions) available to try/test? Thanks.

That contributor only works on Flutter in their free time, so I doubt they have made any undocumented progress on this. Feel free to thumbs up this issue so we can track your interest and subscribe to to it to track future updates on progress, but please don't ping contributors for status updates.

**Comment by ydddx** [comment]
Does it now support cross-compiling linux arm64 on linux x64?

**Comment by heyiqian** [comment]
hello @HidenoriMatsubayashi ,the document link is invalid now，can you confirm it? thank you.

**Comment by HidenoriMatsubayashi** [comment]
@heyiqian Sorry, I deleted the document by my mistake😅 However, we need to prepare `gen_snapshot` for linux-arm64 on linux-x64. [flutter-elinux](https://github.com/sony/flutter-elinux) will be helpful. It is doing the same thing.

**Comment by jld3103** [comment]
Any updates?

**Comment by ramoncjj** [comment]
any updates for this?

**Comment by godofredoc** [comment]
@christopherfujino is this bug obsolete?

**Comment by christopherfujino** [comment]
> @christopherfujino is this bug obsolete?

Sure, I don't think we're considering supporting this currently.
