### ISSUE TITLE
Support Flutter for web from arm host by building dart2js artifact for arm64 host dart-sdk.

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#74928]
Previously, the dart-sdk did not support building the dart2js snapshot for arm64 hosts [tracking issue](https://github.com/dart-lang/sdk/issues/43776). However, this was fixed upstream in https://github.com/dart-lang/sdk/commit/9866c0686744028c3c66693d8f89a8350dc4343b. Flutter's compiled arm64 sdk does not include this snapshot, but it should be possible to build it and include it in the cached artifacts the Flutter tool downloads, allowing arm64 linux host users to develop Flutter for web apps.

**Comment by HidenoriMatsubayashi** [comment]
dart2js will seem to be included in version 2.12 of dart-sdk. Currently, it’s still only in the [2.12-beta](https://storage.googleapis.com/dart-archive/channels/beta/release/2.12.0-259.8.beta/sdk/dartsdk-linux-arm64-release.zip) version.

**Comment by HidenoriMatsubayashi** [comment]
@christopherfujino 
Currently, version 2.12 in stable channel is released! See: https://dart.dev/tools/sdk/archive

**Comment by christopherfujino** [comment]
> @christopherfujino
> Currently, version 2.12 in stable channel is released! See: https://dart.dev/tools/sdk/archive

Thanks! I haven't got a chance to circle back on this, but if you have some free time, I suspect the fix is a one-line gn build rule change to our engine repo.

**Comment by HidenoriMatsubayashi** [comment]
If we leave it alone, will it be incorporated into the engine repo automatically eventually? If not, I'll fix it.

**Comment by christopherfujino** [comment]
> If we leave it alone, will it be incorporated into the engine repo automatically eventually? If not, I'll fix it.

I think I figured this out, I'll prepare a PR...

**Comment by HidenoriMatsubayashi** [comment]
Thank you so much!

**Comment by christopherfujino** [comment]
Confirmed building for web from ARM64 host works as of framework commit `824b1ad3f8`.
