### ISSUE TITLE
Devicelab "mac/ios32" test not running

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74920]
flutter_gallery_ios32__start_up, flutter_gallery__transition_perf_e2e_ios32, flutter_gallery_sksl_warmup__transition_perf_e2e_ios32 haven't run in awhile.  Is the agent with the 32-bit iPhone agent down?

**Comment by godofredoc** [comment]
Yes this test bed requires manual intervention. We'll schedule it for the next visit to the lab.

**Comment by godofredoc** [comment]
The dialog blocking tests will be dismissed tomorrow 02/05/2021 morning.

**Comment by jmagman** [comment]
I think these are still down, @godofredoc.

**Comment by jmagman** [comment]
Oh wait it's running in staging. https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20native_ui_tests_ios32/16

**Comment by godofredoc** [comment]
yes, the reason we haven't moved them to prod is because they are still failing most of the time. Do we want to keep them on staging  or move them to prod as flaky?

**Comment by jmagman** [comment]
No we can keep them in staging, I'm trying to get them passing now.
