### ISSUE TITLE
How to format CameraImage to file or ui.image

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#74955]
How to format CameraImage to file or ui.image

**Comment by thisisamank** [comment]
Hi @qiuguian do you mean that you want to save a picture taken from camera to a file? if that's the case, please read https://flutter.dev/docs/cookbook/plugins/picture-using-camera otherwise please explain it further.

**Comment by qiuguian** [comment]
Thank you for response,I want to use cameraController.startImageStream((CameraImage image){});  to  scan qrcode, but i don't know how to get CameraImage to file

**Comment by thisisamank** [comment]
if you just want to get the file from camera image try this:
```
final path = join((await getTemporaryDirectory()).path, '${DateTime.now()}.png');
await cameraController.takePicture(path)
```
then read this file on your QrCode scanner
```
File file = File('path/to/image/file.png');
```
if your question isn't answered yet, please explain your issue further

**Comment by iapicca** [comment]
@qiuguian 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@qiuguian 
Your question is better suited for StackOver flow. Please use above referred link to get help on your question. Also see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter.
