### ISSUE TITLE
What is the envisioned "Flutter way" to extend the framework?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#7495]
From both an interested party and a developer of a web framework, I'm curious what the authors have in mind for ways they'd like to see others extend the framework (i.e. with plugins, new abstractions, services).

I imagine once Dart has a sound type system and extension methods, that'll help.

**Comment by abarth** [comment]
Generally, we like the composition approach.  I'd expect most people to extend the framework by creating new widgets and (potentially) render objects.  There's also a plugin system for services, which is another dimension for extension.

The framework itself is built up in layers using public interfaces from the layer below (and often using public interfaces within a layer).  That's intended to make compositional extension quite powerful.
