### ISSUE TITLE
Image Picker is crash when take pictures on nokia device

### ISSUE THREAD

**Issue by tiennh123** [flutter/flutter#74957]
I I am using image_picker: ^0.6.7+21 when I open app and take pictures on nokia device. It's crash app and show logs exception:

E/AndroidRuntime(25926): FATAL EXCEPTION: FireBase
E/AndroidRuntime(25926): Process: com.hmdglobal.app.camera, PID: 25926
E/AndroidRuntime(25926): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/AndroidRuntime(25926): 	at com.android.camera.util.m.i(Unknown Source:57)
E/AndroidRuntime(25926): 	at com.android.camera.util.m.e(Unknown Source:88)
E/AndroidRuntime(25926): 	at com.android.camera.util.m.a(Unknown Source:0)
E/AndroidRuntime(25926): 	at com.android.camera.util.m$b.handleMessage(Unknown Source:24)
E/AndroidRuntime(25926): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(25926): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(25926): 	at android.os.HandlerThread.run(HandlerThread.java:67)
2
E/VpsExtension(25655): Failed to get binder for service "vendor.vpsservice"

**Comment by pedromassangocode** [comment]
Hi @tiennh123 
Can you please provide your `flutter doctor -v`, your `flutter run --release --verbose` and your `pubspec.yaml`.
Thank you

**Comment by tiennh123** [comment]
Hi @pedromassangocode 

<detail>
<summary>flutter doctor</summary>
![image](https://user-images.githubusercontent.com/67668092/106344687-ed180180-62dd-11eb-8df7-b34f4ccf903c.png)

</detail>

<detail>
<summary>flutter run --release --verbose</summary>
![image](https://user-images.githubusercontent.com/67668092/106344965-7c71e480-62df-11eb-9af7-b9e4b342cf76.png)
![image](https://user-images.githubusercontent.com/67668092/106344983-94e1ff00-62df-11eb-88e2-8b06113a06ed.png)
![image](https://user-images.githubusercontent.com/67668092/106345016-be028f80-62df-11eb-8666-b84465139456.png)

</detail>

<detail>
<summary>flutter run --release --verbose</summary>

version: 6.0.0+2424

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chips_input: ^1.9.5
  font_awesome_flutter: ^8.10.1
  http: ^0.12.0+2
  provider: ^4.3.2
  flutter_secure_storage: ^3.3.5
  intl: 
  intl_translation:
  url_launcher: ^5.2.7
  flutter_form_builder: ^4.0.2
  card_settings: ^1.14.0
  local_auth: ^0.6.0
  appcenter: ^0.2.1
  pattern_formatter: 
  onesignal_flutter: ^2.6.2
  shimmer: ^1.0.0
  package_info:
  device_info:
  flutter_xlider: ^3.4.0
  connectivity:
  call_log: ^2.0.0
  contacts_service: ^0.4.6  
  flt_telephony_info:
  web_socket_channel: ^1.0.15
  badges: ^1.1.0
  flutter_widgets:
  couchbase_lite: ^2.8.1
  async: ^2.4.0
  date_range_picker: ^1.0.6
  flutter_speed_dial: ^1.2.5
  get_mac: ^0.0.1
  background_fetch: '^0.6.0'
  fixnum: ^0.10.11
  protobuf: ^1.0.1
  grpc: ^2.1.3
  flutter_background_geolocation: ^1.10.3
  shared_preferences: ^0.5.12
  logger: ^0.9.4
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+21
  multi_image_picker: ^4.7.14
  path_provider: ^1.6.11
  image_gallery_saver: ^1.5.0
  flutter_staggered_grid_view: ^0.3.2
  geocoder: ^0.2.1
  flutter_svg: ^0.19.0
  uuid: ^2.2.2
  flutter_local_notifications: ^3.0.2
  flutter_image_compress: ^0.7.0
  maps_toolkit: ^1.1.0+2
  latlong: ^0.6.1
  ntp: ^1.0.7
  device_apps: ^1.2.0
  google_maps_flutter: ^1.0.2
  flutter_polyline_points: ^0.2.4
  geolocator: ^6.1.7
  app_settings: ^4.0.4
  photo_manager: ^0.5.8
  fluttertoast: ^7.1.6
  firebase_ml_vision: ^0.9.10
  disk_space: ^0.0.3
  system_info: ^0.1.3
</detail>

Thank you

**Comment by pedromassangocode** [comment]
Hi @tiennh123 
It seems that your `flutter run --release --verbose` did not completed successfully. Can you please run it again and once the issue reproduces provide the full logs?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
