### ISSUE TITLE
Engine roller closed a roll that was essentially all green

### ISSUE THREAD

**Issue by flar** [flutter/flutter#74965]
If you look at this Engine->Flutter roll, it was closed when the only red item was the Flutter build, rather than waiting for the tree to go green:

https://github.com/flutter/flutter/pull/74933

I think the issue might have been that the first run of the Linux framework tests task had failed due to a network error. I restarted the task from the PR and it later went green. The PR reached a state where the only task that was red was the "waiting for the tree to go green" task, which should have waited until the tree was green and then merged the PR, but instead the roller bot closed it because of the earlier failure result of the test as can be seen in this comment:

https://github.com/flutter/flutter/pull/74933#issuecomment-769450617

The bot should probably double check the status of tasks that it had received a failure on to see if they've been restarted or have since gone green.

**Comment by keyonghan** [comment]
This seems to be controlled by the skia autoroller. Could anyone from skia team help take a look?

**Comment by godofredoc** [comment]
It is possible that one of the checks was still pending/running when the PR was closed. @flar can you please confirm if this assumption is correct?

**Comment by flar** [comment]
I can confirm that I looked at the task list on the PR before it was closed and all were green except for the "flutter build" item. There were no pending items.

It looks like there are 2 bots working there and they seem to alternately visit a PR every hour or so. The timeline looks like this:

1:46 - @engine-flutter-autoroll visits the PR and adds the "waiting for tree" flag
2:49 - @fluttergithubbot visits the PR, adds a comment about failed tests and removes the flag
3:46 - @engine-flutter-autoroll visits the PR again and closes it

I must have visited after 2:49 because I saw the roll had failures and I clicked on the failing test to re-run it. I don't remember when I went back a second time, but it was before 3:46 and I saw that everything was green except for the build so I assumed it would be merged when the tree recovered.

It was @engine-flutter-autoroll that chose to close the PR, so I would be curious what logic it used. Was it thinking "the last comment I see is the other bot telling me there were failures"? Was it the fact that the [engine roll status page](https://autoroll.skia.org/r/flutter-engine-flutter-autoroll?tab=status) had recorded the failure? Note that if I see a build on that status page that is marked as a failure, that status never updates to pending or success if I rerun all failed tests and they succeed on a re-run. I have seen the comments on the PR that list the test failures acknowledge re-runs, but I don't think I've ever seen that roller status page acknowledge re-runs.

**Comment by rmistry** [comment]
The autorollers rely on the @fluttergithubbot to watch bots and land rolls. IIRC, it starts watching a PR once the "waiting for tree to go green" label is added.
If the @fluttergithubbot removes the "waiting for tree to go green" label then the autoroller considers the roll a failure and moves on.
Regarding the roller status page and re-runs: It is very possible that it does not acknowledge re-runs because it does not know about flutter's bots as much as the @fluttergithubbot does, it only uses that for display purposes on the status page. The roller completely relies on the @fluttergithubbot to land/abandon a roll.

**Comment by flar** [comment]
So it looks like we have the following division of labor:

@fluttergithubbot is responsible for:
- adding a comment and removing the flag if it sees a failure anywhere in the task list
- merging the PR when it is fully green and has the flag

@engine-flutter-autoroll is responsible or:
- adding the flag
- closing the PR automatically under some conditions

It looks like one bot has the ability to tell if there is a problem with the roll, but the other bot is the one that closes it. As a result of this division of responsibilities the bot that closes PRs doesn't have the logic to determine if the PR should be closed?

**Comment by rmistry** [comment]
I think of it like this:
The roller bot creates a roll with all appropriate commits and then hands it to the flutter-bot to figure it if it should land or not via the label.

> It looks like one bot has the ability to tell if there is a problem with the roll, but the other bot is the one that closes it. As a result of this division of responsibilities the bot that closes PRs doesn't have the logic to determine if the PR should be closed?

If someone wants to give the flutter bot the ability to directly close the roll then that would work too. I mean, the flow will continue to be the same.
IMO, the best way to improve things is that bot failures should be auto-retried both in PRs and on the tree. It would be even better if there were no flakes.

**Comment by flar** [comment]
That makes sense. We probably don't want it to close PRs that have the "waiting for tree to go green" flag, developers add that and would probably want the opportunity to fix the problem before the PR is closed.

Perhaps a new flag that rollers use which is basically "close or land when all checks are complete"?

**Comment by flar** [comment]
I suppose a workaround is to add the "waiting for tree to go green" flag when you re-run a test that failed.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
