### ISSUE TITLE
Hope to find out the problem foxs. Thanks in advance.

### ISSUE THREAD

**Issue by halim1984** [flutter/flutter#74968]
Here is my code throwing the error:

import 'package:flutter/material.dart';
import './homeListTile2.dart';
import './core/services/api__services.dart';
import './homeListTile.dart';
import './homeSlider.dart';
import './homeStaggeredGridView.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  ApiServices _api = ApiServices();
  @override
  void initState() {
    _api.getMainCategory().then((value) => {
          setState(() {
            _api.mainCategories.addAll(value);
            print(_api.mainCategories.length.toString());
          })
        });

    _api.getLastCompanies().then((value) => {
          setState(() {
            _api.lastCompanies.addAll(value);
            print(_api.lastCompanies.length.toString());
          })
        });

    super.initState();
  }

  final category = [
    {
      'image': '',
      'category_name': 'Katlanır Bisiklet',
      'category_subtitle': 'Dahon',
    },
    {
      'image': '',
      'category_name': 'Akıllı Telefon',
      'category_subtitle': 'Samsung S10',
    },
    {
      'image': '',
      'category_name': 'Motosiklet',
      'category_subtitle': 'Yamaha Tracer 700',
    },
    {
      'image': '',
      'category_name': 'Araba',
      'category_subtitle': 'BMW 3',
    },
    {
      'image': '',
      'category_name': 'Diz Üstü',
      'category_subtitle': 'Mac Book Pro',
    },
    {
      'image': '',
      'category_name': 'Akıllı Saat',
      'category_subtitle': 'Huawei GT2',
    },
  ];
  List imgList2 = List();

  final List<String> imgList = [
    'https://www.aslibisiklet.com/Uploads/UrunResimleri/buyuk/Dahon-2019-MU-D9-Katlanir-Bisiklet-7c1f.jpg',
    'https://im.haberturk.com/2019/01/23/ver1548248841/2300536_810x458.jpg',
    'https://mcn-images.bauersecure.com/PageFiles/597581/1IMG_5491.jpg',
    'https://i2.milimaj.com/i/milliyet/75/0x410/5cf5249cec10bb5cc8aff4b1.jpg',
    'https://shiftdelete.net/wp-content/uploads/2020/05/13-inc-macbook-pro-2020-ozellikleri-ve-fiyati.jpg',
    'https://reimg-teknosa-cloud-prod.mncdn.com/mnresize/600/600/productimage/145059507/145059507_0_MC/35344835.jpg'
  ];

  @override
  Widget build(BuildContext context) {
    for (int i = 0; i < category.length; i++) {
      category[i]['image'] = imgList[i];
    }

    final List<Widget> imageSliders = imgList
        .map(
          (item) => Container(
            width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
              image: DecorationImage(
                image: NetworkImage(item.toString()),
                fit: BoxFit.cover,
              ),
              borderRadius: BorderRadius.all(Radius.circular(15.0)),
            ),
            margin: EdgeInsets.all(5.0),
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.all(Radius.circular(15.0)),
                gradient: LinearGradient(
                  colors: [
                    Color.fromARGB(500, 0, 0, 0),
                    Color.fromARGB(300, 0, 0, 0),
                  ],
                  begin: Alignment.bottomCenter,
                  end: Alignment.lerp(
                      Alignment.bottomCenter, Alignment.center, 0.5),
                ),
              ),
              padding: EdgeInsets.symmetric(vertical: 10, horizontal: 20.0),
              child: Align(
                alignment: Alignment.bottomLeft,
                child: Text(
                  '${category[imgList.indexOf(item.toString())]['category_subtitle']}',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20.0,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ),
          ),
        )
        .toList();

    return Scaffold(
      appBar: AppBar(
        title: Text('ÖDEV 1'),
        centerTitle: true,
      ),
      body: ListView(
        children: [
          HomeSlider(
            category: category,
            imgList: imgList,
            imageSliders: imageSliders,
          ),
          getCategories(),
          Divider(height: 5),
          HomeStaggeredGridView(),
          getCompanies(),
        ],
      ),
    );
  }

  getCategories() {
    return ListView.builder(
      shrinkWrap: true,
      physics: NeverScrollableScrollPhysics(),
      itemCount: _api.mainCategories.length,
      itemBuilder: (context, index) {
        return HomeListTile(
          category: _api.mainCategories[index],
        );
      },
    );
  }

  getCompanies() {
    return ListView.builder(
      scrollDirection: Axis.horizontal,
      shrinkWrap: true,
      itemCount: _api.lastCompanies.length,
      itemBuilder: (context, index) {
        return HomeListTile2(
          company: _api.lastCompanies[index],
        );
      },
    );
  }
}

**Comment by halim1984** [comment]
Here is the error by the way sorry:

The relevant error-causing widget was
ListView
lib\homePage.dart:160
When the exception was thrown, this was the stack
#2      RenderShrinkWrappingViewport.performLayout
package:flutter/…/rendering/viewport.dart:1852
#3      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
#4      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:113
#5      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
#6      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:113
...
The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#dda63 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderShrinkWrappingViewport#dda63 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
    size: MISSING
    axisDirection: right
    crossAxisDirection: down
    offset: ScrollPositionWithSingleContext#9e601(offset: 0.0, range: null..null, viewport: null, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#9a2a9, ScrollDirection.idle)
    child 0: RenderSliverPadding#42b8e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: layoutOffset=None
        constraints: MISSING
        geometry: null
        padding: EdgeInsets.zero
        textDirection: ltr
        child: RenderSliverList#b26f6 NEEDS-LAYOUT NEEDS-PAINT

**Comment by pedromassangocode** [comment]
Hi @halim1984 
Can you please provide your `flutter doctor -v`, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Please provide a code that does not uses private code or third-party plugin/packages
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
