### ISSUE TITLE
Back traverses drawer

### ISSUE THREAD

**Issue by aleki** [flutter/flutter#7496]
Selection an item in the drawer should reset the navigator's stack of routes. 
https://youtu.be/Sww4omntVjs?t=13m44s

**Comment by Hixie** [comment]
The drawer widget is completely agnostic about this. I think this is basically a dupe of https://github.com/flutter/flutter/issues/7365, which would make this pattern easier.

**Comment by aleki** [comment]
@Hixie yes, that's what I need. Thank you.
