### ISSUE TITLE
Add health checks to validate requirements for code signing

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74960]
The are some of the required checks:

* Can the keychain be unlocked?
* Is the cert present and not expired?
* Is the device paired?

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by godofredoc** [comment]
@jmagman do you know how can we check if the device is paired? idevicepair seems not to work.

**Comment by jmagman** [comment]
> idevicepair seems not to work.

What are you seeing?  Does `idevicepair validate` work?

`xcrun xcdevice list` can be parsed to see which non-simulators ("simulator"=false) are available ("available"=false).  Unpaired ones look like this: 
```
  {
    "modelCode" : "iPad8,5",
    "simulator" : false,
    "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
    "error" : {
      "code" : -9,
      "failureReason" : "",
      "description" : "iPad is not paired with your computer.",
      "recoverySuggestion" : "To use iPad with Xcode, unlock it and choose to trust this computer when prompted.",
      "domain" : "com.apple.platform.iphoneos"
    },
...
    "available" : false,

  },
```

**Comment by keyonghan** [comment]
`idevicepair validate` shows the correct info. Thanks!

As for the second item: Is the cert present and not expired?
I found command `security find-certificate -a`, listing all available certificates. How can I know which one is the target one and how can I check if it is expired or not?

**Comment by jmagman** [comment]
I think `security find-identity -p codesigning -v` should contain the valid unexpired codesigning certs.

**Comment by keyonghan** [comment]
Health checks have been added. Waiting for bot_config side validation before closing.

**Comment by keyonghan** [comment]
validated in staging. Closing.
