### ISSUE TITLE
Keyboard does not hide when enter key is tapped

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#7497]
When I turn on autofocus on Input widget, it is focused nicely, but after tapping enter button on keyboard, keyboard is closed but automatically reopened due to renewed autofocus. When I set autofocus on false, enter button properly hides the keyboard. I can reproduce this behavior on Android 5.1, 6.0, 7.0 with default system keyboards.

## Steps to Reproduce
I can reproduce this issue in "stocks" app in flutter examples.
1. run Stocks app from flutter sdk examples directory
2. tap the search icon. (input is automatically selected and keyboard is shown)
3. tap enter key on the keyboard

## Logs
No log messages during performing steps above

## Flutter Doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /opt/flutter-sdk
    • Framework revision a0666f330e (3 days ago), 2017-01-10 21:33:04
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /opt/android-sdk/
    • Platform android-25, build-tools 23.0.3
    • ANDROID_HOME = /opt/android-sdk/
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • SM N9005 • 4dfeba26 • android-arm • Android 5.1.1 (API 22)

**Comment by eseidelGoogle** [comment]
We should consider moving a search example into the gallery given how likely apps are going to want one.  That can be a separate bug of course. :)

@mpcomplete probably knows this area best.

**Comment by cbracken** [comment]
This should now be fixed on both iOS and Android.

**Comment by abbadabbatech** [comment]
I do not see the keyboard going away in either, once I click my submit button or enter key, the keyboard just stays.  Is there something I am supposed to call to get it to remove?

**Comment by cbracken** [comment]
@abbadabbatech I believe a later change #8028 changed the return key behaviour for multi-line text fields.

**Comment by abbadabbatech** [comment]
Thanks for the response, only thing that works is maxlines to 1 give the Done button on keyboard. I was hoping to trigger the keyboard just disappearing when its submitted. I will check around for that, thanks.

**Comment by cbracken** [comment]
If you're not able to work anything convenient out, definitely file a bug and /cc myself and/or @gspencergoog.
