### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

### ISSUE THREAD

**Issue by Lukaalishi** [flutter/flutter#74974]

**Comment by iapicca** [comment]
@Lukaalishi 
can you provide your `flutter doctor -v`, your `flutter run  -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment]
Hi @Lukaalishi
I see there's an open issue (https://github.com/flutter/flutter/issues/72970) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
