### ISSUE TITLE
Scroll position not updated on children change

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#7498]
When scrolling down in both ScrollableGrid and ScrollableList and then applying filter on children objects (e.g. search) scroll position stays unchanged, therefore new smaller subset of objects rendered in scrollable widget is not visible. It is refreshed properly after display tap of any sort. I can reproduce this behavior on Android 5.1, 6.0, 7.0 with default system keyboards.

## Steps to Reproduce
I can reproduce this issue in "stocks" app in flutter examples.
1. run Stocks app from flutter sdk examples directory
2. scroll down to item named "AETI"
3. tap the search icon and type "ad" into search input
4. display is empty. tap on it to force scroll refresh and filtered items are shown

## Logs
No log messages during performing steps above

## Flutter Doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /opt/flutter-sdk
    • Framework revision a0666f330e (3 days ago), 2017-01-10 21:33:04
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /opt/android-sdk/
    • Platform android-25, build-tools 23.0.3
    • ANDROID_HOME = /opt/android-sdk/
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • SM N9005 • 4dfeba26 • android-arm • Android 5.1.1 (API 22)

**Comment by Hixie** [comment]
i have this fixed in my refactor

**Comment by ethael** [comment]
Thanks a lot!
