### ISSUE TITLE
Migrate the path_provider plugin to null safety.

### ISSUE THREAD

**Issue by enetor** [flutter/flutter#74996]
Internal bug: http://b/177908022

This is one of the blocking migrations that need to happen before a number of internal packages can be migrated to null safety.

**Comment by ryanheise** [comment]
Hi @enetor Could this issue be open until path_provider is fully migrated? It will be useful for others who want to track its progress.

**Comment by tsinis** [comment]
> Hi @enetor Could this issue be open until path_provider is fully migrated? It will be useful for others who want to track its progress.

Same here!
