### ISSUE TITLE
Very strange calculate difference between two dates in UTC

### ISSUE THREAD

**Issue by Bes79** [flutter/flutter#74991]
1) Right calculate then not use UTC
    DateTime d1 = DateTime.now().add(Duration(hours: 1));
    DateTime d11 = DateFormat('yyyy-MM-dd H:m:s').parse(d1.toString()); // imitation of get DateTime from DB
    print(DateTime.now());
    print(d11);
    print(d11.difference(DateTime.now()).inSeconds);

that prints:
2021-01-29 19:31:58.854184
2021-01-29 20:31:58.000
3599

2) Not right calculate the use UTC

    DateTime d1 = DateTime.now().toUtc().add(Duration(hours: 1));
    DateTime d11 = DateFormat('yyyy-MM-dd H:m:s').parse(d1.toString()); // imitation of get DateTime from DB
    print(DateTime.now().toUtc());
    print(d11);
    print(d11.difference(DateTime.now().toUtc()).inSeconds);

that prints:
2021-01-29 16:40:32.323210Z
2021-01-29 17:40:32.000
-7200

**Comment by stuartmorgan** [comment]
`DateTime` is part of Dart, not Flutter, so issues with it would need to be reported in [the Dart issue tracker](https://github.com/dart-lang/sdk/issues)
