### ISSUE TITLE
ListTile.selected should cause tile to have different background color

### ISSUE THREAD

**Issue by AlexeySemigradsky** [flutter/flutter#7499]
Stocks app (Flutter):
![screenshot_20170115-112533](https://cloud.githubusercontent.com/assets/4836709/21961286/ac77d0f4-db16-11e6-8b67-e5dd93466c20.png)

Inbox:
![screenshot_20170115-112605](https://cloud.githubusercontent.com/assets/4836709/21961296/056ee706-db17-11e6-9d4b-b358a234e6cf.png)

**Comment by abarth** [comment]
DrawerItem has as selected property:

https://docs.flutter.io/flutter/material/DrawerItem/selected.html

We're just not using it properly in the stocks demo.

**Comment by aleki** [comment]
@abarth Actually, you are using it property in the stocks demo: https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_home.dart#L128

**Comment by abarth** [comment]
Ah, interesting.  Thanks!

**Comment by aleki** [comment]
@abarth It change text (foreground) color, but not change background color.

**Comment by Hixie** [comment]
Looks like we're doing it wrong (and should be doing the background highlight also), though it's not 100% clear:
https://material.io/guidelines/patterns/navigation-drawer.html#

**Comment by efroim102** [comment]
@Hixie Any update on this?
@AlexeySemigradsky Have you found any workaround?

**Comment by TahaTesser** [comment]
### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: Text('ListTile guide')),
        body: BodyWidget(),
      ),
    );
  }
}

String horseUrl = 'https://i.stack.imgur.com/Dw6f7.png';
String cowUrl = 'https://i.stack.imgur.com/XPOr3.png';
String camelUrl = 'https://i.stack.imgur.com/YN0m7.png';
String sheepUrl = 'https://i.stack.imgur.com/wKzo8.png';
String goatUrl = 'https://i.stack.imgur.com/Qt4JP.png';

class BodyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        ListTile(
          leading: CircleAvatar(
            backgroundImage: NetworkImage(horseUrl),
          ),
          title: Text('Horse'),
          subtitle: Text('A strong animal'),
          trailing: Icon(Icons.keyboard_arrow_right),
          onTap: () {
            print('horse');
          },
          selected: true,
        ),
        ListTile(
          selected: true,
          leading: CircleAvatar(
            backgroundImage: NetworkImage(cowUrl),
          ),
          title: Text('Cow'),
          subtitle: Text('Provider of milk'),
          trailing: Icon(Icons.keyboard_arrow_right),
          onTap: () {
            print('cow');
          },
        ),
        ListTile(
          selected: true,
          leading: CircleAvatar(
            backgroundImage: NetworkImage(camelUrl),
          ),
          title: Text('Camel'),
          subtitle: Text('Comes with humps'),
          trailing: Icon(Icons.keyboard_arrow_right),
          onTap: () {
            print('camel');
          },
          enabled: false,
        ),
        ListTile(
          leading: CircleAvatar(
            backgroundImage: NetworkImage(sheepUrl),
          ),
          title: Text('Sheep'),
          subtitle: Text('Provides wool'),
          trailing: Icon(Icons.keyboard_arrow_right),
          onTap: () {
            print('sheep');
          },
        ),
        ListTile(
          leading: CircleAvatar(
            backgroundImage: NetworkImage(goatUrl),
          ),
          title: Text('Goat'),
          subtitle: Text('Some have horns'),
          trailing: Icon(Icons.keyboard_arrow_right),
          onTap: () {
            print('goat');
          },
        ),
      ],
    );
  }
}

```

**Comment by Hixie** [comment]
This hasn't been a high enough priority for the folks contributing patches so far. Feel free to contribute a PR if it is a high priority for you though.

**Comment by mono0926** [comment]
I've made a widget for adding ListTile selected background color.

- Widget: https://github.com/mono0926/flutter_mono_kit/blob/master/lib/widgets/list_tile_selected_background_colored_box.dart
- Sample: https://github.com/mono0926/flutter_mono_kit/blob/master/example/lib/pages/list_tile_selected_background_colored_box_page.dart

The default design is based on the Gmail app, but it is also customizable.

[ListTileSelectedBackgroundColoredBox](https://github.com/mono0926/flutter_mono_kit/blob/master/lib/widgets/list_tile_selected_background_colored_box.dart) | Gmail | [Navigation drawer - Material Design](https://material.io/components/navigation-drawer/#)
--- | --- | ---
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-13 at 14 49 43](https://user-images.githubusercontent.com/1255062/79095701-117a1000-7d96-11ea-90c2-0e0a4bcbdbf8.png) | ![Screenshot_20200413-144437](https://user-images.githubusercontent.com/1255062/79095582-b5af8700-7d95-11ea-8ffa-3f8e72f2d481.png)  | <img width="376" alt="image" src="https://user-images.githubusercontent.com/1255062/79095550-a0d2f380-7d95-11ea-8830-4d9bd04a28a3.png">

**Comment by mono0926** [comment]
#61347 was merged, but it can’t change the shape of background color.

**Comment by shihaohong** [comment]
Closing this issue since this feature has been added with https://github.com/flutter/flutter/pull/61347

**Comment by shihaohong** [comment]
@mono0926 Can you file a new issue? I think this has to do with the `Container`'s shape itself (given that it's a non-standard shape)?
