### ISSUE TITLE
Web app with CanvasKit doesn't render text on some Android phones

### ISSUE THREAD

**Issue by tomgilder** [flutter/flutter#74990]
## Steps to Reproduce

1. Create a new Flutter project and enable web
2. Build using CanvasKit: `flutter build web --web-renderer canvaskit`
3. Load in Chrome on some Nokia and OnePlus phones (example at https://flutter-test-abcb2.web.app)

No text appears on first load, and some appears after pressing the button.

- Chrome 88.0.4324.93
- We've seen this on a Nokia 6 (model TA-1021), a Nokia 8, and a OnePlus 5 - all on Android 9
- Flutter latest master  

Here's how it looks initially: 

<img src="https://user-images.githubusercontent.com/756862/106299018-54da3800-625d-11eb-886e-5097164ccb0c.png" width="300">

After pressing the + button, it renders the number and a line on the app bar:

<img src="https://user-images.githubusercontent.com/756862/106299114-7804e780-625d-11eb-8bad-1a08c690e830.png" width="300">

There's nothing related to this logged in Chrome's console.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on macOS 11.1 20C69 darwin-x64, locale en-FI)
    • Flutter version 1.26.0-18.0.pre.73 at /Users/tom/fvm/versions/master
    • Framework revision 791edc230d (10 hours ago), 2021-01-28 21:54:03 -0800
    • Engine revision 4ba79a34a0
    • Dart version 2.12.0 (build 2.12.0-272.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by JotaPe** [comment]
You already tried to run normally, like an app, instead on the browser?

**Comment by tomgilder** [comment]
Yes, this is a web-only issue. Compiled Android apps are fine.

**Comment by darshankawar** [comment]
This seems to be specific to Nokia phones, as I tried a sample app on Samsung Galaxy 8.1.0 device and Pixel 3XL emulator (OS 9) that rendered properly upon app launch:

<img width="184" alt="Screenshot 2021-02-01 at 1 21 31 PM" src="https://user-images.githubusercontent.com/67046386/106429431-6bb4a080-6490-11eb-84cb-7ac52a0a8acb.png">

Since I don't have Nokia phone to verify this, I am keeping this issue open for further analysi.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.90 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 25134a16d1 (2 days ago), 2021-01-29 23:52:30 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86    • Android
      9 (API 28) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google
      Chrome 88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Comment by tomgilder** [comment]
Update: once logging in to our app, text is semi-rendering in a really weird way on Nokia phones (the text is in Finnish so is pretty weird anyway 😉).

<img src="https://user-images.githubusercontent.com/756862/106461680-c4d70100-649d-11eb-8149-f32746e9f246.png" width="300">
<img src="https://user-images.githubusercontent.com/756862/106461889-0ebfe700-649e-11eb-8640-9744c5e2fd72.png" width="300">

(the black boxes are redacted information)

The text is always incorrectly rendered in the same way on every draw.

Not sure if there's any info #74990 or #73628 that could be useful?

**Comment by yjbanov** [comment]
Unfortunately I don't have a Nokia phone. Is there anything else logged on the console, such as a warning that we're falling back to CPU rendering. I'm wondering if WebGL is busted on that phone.

**Comment by yjbanov** [comment]
While we're investigating the issue, consider using `--web-renderer=auto`, which will use the HTML renderer on phones.

**Comment by tomgilder** [comment]
Hello, we've now seen this on other phones, including a OnePlus 5 on Android 9. 

Screenshots from [this website](https://moi.codemate.dev/).

<img src="https://user-images.githubusercontent.com/756862/111593098-42e33300-87d2-11eb-9079-b056e31167e9.jpg" width="400">
<img width="400" src="https://user-images.githubusercontent.com/756862/111593107-44acf680-87d2-11eb-84db-b9d31b0319b2.jpg">

**Comment by LeonWehrhahn** [comment]
I am having the same problem on a One plus 3T. We decided to switch to canvas kit, because of inconsistencies between our desktop web (Canvas kit) and mobile (HTML). However it is rendering the text in a pretty weird way. On some widgets the text is not displaying at all and on others it is cut off. On rare occasions the text is however sometimes rendered correctly. This is holding us back from releasing our website.

**Comment by tomgilder** [comment]
I feel like this deserves a higher priority. It totally breaks apps on many popular devices.

The workaround of using the HTML renderer doesn't work for all projects due to its lack of support for certain drawing methods, and worse performance for graphical heavy apps. It could easily be a total blocker for projects that require using CanvasKit.

**Comment by doppio** [comment]
This is a significant issue for my production web app and is likely affecting hundreds (perhaps thousands) of users with no workaround. Like @tomgilder, the HTML renderer is not an option for us due to several other show-stopper bugs and inconsistencies with other platforms. Two users have contacted my support channel about this, but there are likely many others who just abandon the app.

**Comment by StefPtrs** [comment]
We are encountering the exact same issue (screenshot from a OnePlus 9) using flutter 2.2.3:
![a63730b8-572c-4eff-b5a4-2bc0b89929a4](https://user-images.githubusercontent.com/10376763/128733722-cc6c478c-9f37-4129-b751-9afbab8fa732.jpeg)

The same issue still exists on the latest beta (2.4.0-4.2.pre) and dev (2.5.0-5.0.pre) versions.  

I agree with @doppio & @tomgilder, the priority of this issue should be raised. For web apps on mobile there is no workable alternative:
- **canvaskit**: breaks text on an unknown number of (Android?) devices 
- **html**: breaks the layout in several other ways and worse performance (e.g. [1](https://github.com/flutter/flutter/issues/82176), [2]https://github.com/flutter/flutter/issues/84331),...)

Happy to produce a dummy example if that would help.

**Comment by tomgilder** [comment]
@StefPtrs we're still seeing this with the standard template with 2.5.2 on a Nokia 6 😢

**Comment by StefPtrs** [comment]
@tomgilder Can you try including the js script in this post in your index.html? That seems to have helped on my end as well (it might have a small performance penalty). https://github.com/flutter/flutter/issues/89655#issuecomment-955852024

**Comment by MatthewPatience** [comment]
Just wanted to add some more info about what devices we are seeing the same issue on because it doesn't seem to affect all devices. Will update this content as we continue testing on different devices. 

# Works fine on:
- Samsung Galaxy Fold 3
- Pixel 6

# Broken on:
- LG Q70

**Comment by MatthewPatience** [comment]
@darshankawar would it be possible to see if some more priority might be applied to this issue? We would really love to use the canvas renderer on mobile for our web app.

**Comment by nosmirck** [comment]
We are experiencing the same issue. Funny is that before flutter 3.0.1 and after 2.10.0 (when we started developing the app) everything was rendering fine on mobile.

Now, we're having issues with text rendering.

I'm using a Samsung Galaxy S8 and this is how it renders on Chrome android.

https://user-images.githubusercontent.com/6027290/171966381-c13c3603-1549-4d6e-b352-74336db5d8d9.mp4

As you can see, the text breaks and shows when the new kind of elastic feedback of the scroll view happens, it looks like it gives a few more pixels to the texts fields to render properly, without it, it seems that the polygons that compose the text have some exploding vertices making text invisible.

It is a very hard issue to reproduce and debug, but these are my two cents!
