### ISSUE TITLE
Bots sometimes timeout waiting for scheduling.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#74997]
I've seen this several times now on https://github.com/flutter/flutter/pull/74922 and a couple other recent PRs, particularly on Windows bots.

For example: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_tests/9570/steps?succeeded=true&debug=false

AFAICT, what's happening is that the "sharding" bot gets scheduled and starts. It spawns 3 more builders and waits. Those other 3 builders take most of the ~1hr the original bot has to run to even get scheduled and start. the original bot sees it is out of time and cancels the other builders, and is marked as a failure.

I think we need some combination of:

- More bots
- Fewer shards (or more shards so they finish/fail faster?)
- No timeout on shard waiting bots
- No dedicated bot waiting for the sharded bots.

/cc @godofredoc @keyonghan @CaseyHillers 

I've seen this on several PRs recently.

**Comment by godofredoc** [comment]
Do we know how frequently is this happening? have you seen this problem in mtv-working hours 9:00AM - 5:00PM?

The reason for the questions is that we are intentionally reducing capacity from 5:00PM to 9:00PM to 1/3 as most of the capacity is idle on that time window.

@keyonghan is this something we can check on the current metrics and dashboards?

**Comment by dnfield** [comment]
I've seen it happening more in the evening for sure, but I've also seen it happen outside that window - e.g. one I just linked was scheduled after 9pm PST.

**Comment by dnfield** [comment]
Speaking just for myself, I'll frequently pop on after dinner if I noticed a test failed for something that needs a minor fix, or a reviewer added a nit I can fix quickly. So I'll change 1 or 2 lines of code, push back up, and go back to my evening - to find later that CI failed because of this issue.

**Comment by godofredoc** [comment]
We'll look at the metrics and adjust the numbers. A proper fix will need to be able to extend mtv working hours after 5:00PM and adjust the try pool size for try on non working hours.

**Comment by christopherfujino** [comment]
What if we extend the timeout for parent recipe, while keeping the shorter timeout for the drone?

**Comment by dnfield** [comment]
That's probably fine for now, but tying up a bot for more than an hour is problematic. Hurts capacity and takes way too long to find out if something failed.

**Comment by christopherfujino** [comment]
> That's probably fine for now, but tying up a bot for more than an hour is problematic. Hurts capacity and takes way too long to find out if something failed.

I agree it's not ideal, although, if the parents times out after an hour while the drones are still running, we don't find out if something fails anyway.

**Comment by keyonghan** [comment]
Working hours are good, but after hours queue time is way above our SLO:

90%th queue time for last two week:
Windows builds working hours 7.05 min v.s. after hours 45.9min
Linux builds working hours 8.83 min v.s. after hours 44.7min

**Comment by godofredoc** [comment]
Additional capacity was added for non working hours. @keyonghan can we compare the timeout rates?

**Comment by godofredoc** [comment]
With the new capacity tasks on non working hours are not timing out anymore.
