### ISSUE TITLE
Stocks app everything is awesome checkbox changes without waiting for validation from the popup when you touch it directly

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#75]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:27 GMT_
_Originally opened as https://github.com/flutter/engine/issues/33_

----

_From @iansf on July 7, 2015 22:21_

Touching the "Everything is awesome" text correctly waits for validation from the popup, though.

_Copied from original issue: domokit/mojo#305_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [collinjackson](https://github.com/collinjackson)**
_Monday Aug 10, 2015 at 17:46 GMT_

----

I believe that this will get easier once we have the gesture recognizers that can negotiate for ownership over the tap event.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Monday Aug 24, 2015 at 21:43 GMT_

----

I think this is the same as https://github.com/domokit/sky_engine/issues/42  Can we close one of them?

**Comment by sethladd** [comment]
There's no prompt when you disable "everything is awesome", but there is a prompt when you enable "everything is awesome".

Should there be a prompt when you disable/uncheck?

If not, we can probably close this.

**Comment by Hixie** [comment]
Does it act any differently if you tap the checkbox directly vs tapping the text?

**Comment by Hixie** [comment]
Just tested it, and yeah, it looks like it's working well now.
