### ISSUE TITLE
The build failed likely due to AndroidX incompatibilities in a plugin

### ISSUE THREAD

**Issue by najamshidi** [flutter/flutter#75019]
![Screenshot (22)](https://user-images.githubusercontent.com/69300211/106325885-2ed28900-6299-11eb-870e-ae338bd15f0f.png)
![Uploading Screenshot (23).png…]()

**Comment by iapicca** [comment]
@najamshidi 
can you provide your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@najamshidi 
Along with above requested details, please provide `pubspec.yaml`. Also provide the logs and code in text format instead in screenshots. 
Moreover, check if any of the plugin you added recently that may be causing this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
