### ISSUE TITLE
Build failures in window target not surfaced to tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#75017]
To repro `flutter create example` , migrate to null safety, then add an import and dependency on non-null safe code.

`flutter run -d windows` should fail, since it will detect the entrypoint as being migrated and default to sound mode. This happens, but we don't seem to notice or forward the error from cmake, so instead of existing with an error - we run whatever the previously built binary was.

**Comment by jonahwilliams** [comment]
Actually it appears that the tool never notices build failures now

**Comment by jonahwilliams** [comment]
From some investigation, this appears to have broken with the VERBTAIM change https://github.com/flutter/flutter/pull/70026/files

**Comment by stuartmorgan** [comment]
Is the issue that the values for the flags are a space-separated list, and thus no longer quoted? Maybe we need to annotate variables with whether they should be quoted or not?

**Comment by jonahwilliams** [comment]
This particular issue is that a `%` character is being interpreted either by the windows command line or cmake as some kind of control character, and it is chopping off everything after it in when cmake sets the environment for the flutter tool process.
