### ISSUE TITLE
Would be nice to run hello_services test on bots

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7502]
We have an android instrumentation test:
https://github.com/flutter/flutter/tree/master/examples/hello_services/android/app/src/androidTest/java/com/example/flutter

Would be nice to run it on travis.  Or some other way to validate that we don't break our hello_services (soon to be `flutter create` default) workflow.

@jason-simmons @jakobr-google 

Just something to think about as we're changing this code.

https://github.com/flutter/flutter/blob/master/dev/bots/test.sh
is the script travis runs, here is it's config:
https://github.com/flutter/flutter/blob/master/.travis.yml

**Comment by eseidelGoogle** [comment]
@abarth notes that we likely need to use the Chrome infa bots for this.  FYI @mit-mit

**Comment by szakarias** [comment]
@eseidelGoogle  I am writing integration test for platform_services which runs on Devicelab. Maybe we can change the title of this issue to something like 'Would be nice to run platform_services test on Devicelab' ?

**Comment by eseidelGoogle** [comment]
Changed.  Please feel free to edit further.   DeviceLab will provide post-commit testing and is typically used for running things on real hardware.  If we only need simulators/emulators chrome infra can work too.

**Comment by szakarias** [comment]
Done in  #8826 .
