### ISSUE TITLE
Devicelab LUCI Mac-android bot picks up multiple tests

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#75031]
Mac17 in staging env, and Mac18-Mac19 in prod env all hit this issue. These bots kept restarting, leaving in-process task in zombie status, and reserving new tasks.

Log from swarming bot:
```
'53687091200', '--cache', u'/opt/s/isolated_cache', '--max-items', '51200', '--cas-cache', u'/opt/s/cas_cache', '--kvs-file', u'/opt/s/cas_kvs.db', '--named-cache-root', u'/opt/s/c']
117 2021-01-29 18:01:51.860 I: Got signal 15
76767 2021-01-29 18:01:58.852 I: importing bot_main: /opt/s/swarming_bot.1.zip, 0106c7ddb56c79dde8ca35bd2ef82d0da10e48167b8b733143040aa8f70824de
76767 2021-01-29 18:01:58.854 E: Singleton "/opt/s/swarming.lck" is held by ""
Traceback (most recent call last):
  File "/opt/s/swarming_bot.1.zip/bot_code/singleton.py", line 61, in acquire
    fcntl.flock(self.handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
IOError: [Errno 35] Resource temporarily unavailable
76767 2021-01-29 18:01:58.854 I: Restarting machine with command sudo -n /sbin/shutdown -r now (Found a previous bot, 76767 rebooting as a workaround for https://crbug.com/569610.)
```

What have been tried:
- Remove `/opt/s/swarming.lck` and reboot the bot. It helps for some cases. But the issue is reproducible pretty soon.
- Remove the machine from salt server: issue gets mitigated, and bots come back to a normal state.

The root problem seems that one of the salt states is killing the swarming bot when triggered from the server.
The potential culprit https://source.corp.google.com/fuchsia-infra/turquoise/salt/salt/luci/swarming/init.sls;l=37

\cc @godofredoc @yusufm

**Comment by keyonghan** [comment]
Mac20 started picking up multiple tasks as well.
Just removed it out of salt server, together with mac21 and mac22 (though these two haven't seen the issue yet).

**Comment by yusufm** [comment]
From the bug @godofredoc found, looks like we need to go to v3001.1 for the fix: https://github.com/saltstack/salt/issues/57436

**Comment by godofredoc** [comment]
According to maruel@ we also need to move the bot_code.py outside of /opt/b/s/

**Comment by godofredoc** [comment]
This was a problem with the salt service restarting swarming service every time it was run.
