### ISSUE TITLE
complex_layout_ios__start_up brings up a system dialog that makes next tests fail.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75048]
complex_layout_ios__start_up shows a dialog to allow to connect to devices in your local network. This dialog makes all the tests running on the same bot to fail.

![Screen Shot 2021-01-29 at 8 01 32 PM](https://user-images.githubusercontent.com/54371434/106346551-d4bbce80-626c-11eb-89fc-78163f11042a.png)

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by jmagman** [comment]
@godofredoc Hopefully fixed with https://github.com/flutter/flutter/pull/75163.  Let me know if you see this again.

**Comment by jmagman** [comment]
Test-only hotfix request to get `complex_layout_ios__start_up` passing on the stable branch.
