### ISSUE TITLE
Should be able to update FlutterPlugin.groovy

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7504]
In gradle-based builds, we have a FlutterPlugin.groovy in the user's source tree.  As we iterate in the build system, we're likely to want to change this plugin.  We need a mechanism for updating the copy of this file in the user's source tree when we change the version in our source tree.

The simplest thing is to check whether the version in the user's source tree is byte-identical (or has a matching hash) with the version `flutter_tools` expects.

**Comment by abarth** [comment]
Someone just hit this issue in gitter.

**Comment by eseidelGoogle** [comment]
Is this now resolved with @jakobr-google's work?

**Comment by abarth** [comment]
Yes.  It will be resolved once https://github.com/flutter/flutter/pull/7902 lands.
