### ISSUE TITLE
Android gradle-based build should support local-engine builds

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7505]
When working on the Flutter engine and the Flutter framework simultaneously, it's useful to be able to create complete builds of apps that use a locally modified version of the framework and of the engine.

The `flutter` tool supports this workflow in the old Android build system using the `--local-engine` flag.  We should make sure the gradle-based workflow also supports this feature (i.e., via a configuration file, similar to how we support it in the Xcode-based build).

**Comment by abarth** [comment]
This might already work.  I just filed  the issue so we make sure to check it.

**Comment by jakobr-google** [comment]
Probably doesn't work yet, at least according to #6761.

**Comment by jakobr-google** [comment]
Tracking this in #6761.
