### ISSUE TITLE
Game Overlay support

### ISSUE THREAD

**Issue by AndreGroeschel** [flutter/flutter#75065]
## Use case

I would like to create a desktop voice chat application for gamers so that they can directly talk with each other while playing. The best solution would be if this could happen as a game overlay application so that players don't miss messages.
Did some research if this is possible at all and I found that Discord has a very nice [game overlay](https://support.discord.com/hc/en-us/articles/217659737-Games-Overlay-101)

As far as I know, Discord uses the Electron framework and I found some repositories that provide functionality like this.

## Proposal

It would be cool if there was a way to build game overlay apps with Flutter when targeting desktop applications.
Would also like to start developing overlay support and any help or suggestions on how this can be accomplished would be greatly appreciated.

**Comment by iapicca** [comment]
@AndreGroeschel 
the feature you are describing seems easily obtainable with a simple [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html)
what feature you feel is missing from it?

**Comment by AndreGroeschel** [comment]
@iapicca 
The challenge here is to have Flutter render on top of a running game (usually build with different tech, i.e. Unity). So it needs to be hooked into Vulkan, OpenGL, and DirectX to render everything from Flutter after the rendering of a single frame from a game is completed.

Is there any way to read the renderbuffer from Flutter's Skia engine?

**Comment by iapicca** [comment]
@AndreGroeschel 
what platform are you referring to?
for mobile you can use [add-to-app](https://flutter.dev/docs/development/add-to-app)
for desktop it seems to me a very unlikely scenario

**Comment by jonahwilliams** [comment]
Embedding Flutter in other rendering libraries, engines, applications, et cetera is possible but we have no plans to offer more templates describing how to do so
