### ISSUE TITLE
error when i add firebase and geolocator dependencies in my application

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#75060]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by alihassan143** [comment]
Running "flutter pub get" in flutter_app...                         1.1s
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'play-services-location.aar (com.google.android.gms:play-services-location:17.0.0)' to match attributes {artifactType=android-manifest}.
      > Execution failed for AarTransform: C:\Users\aliha\.gradle\caches\transforms-2\files-2.1\4161f8a9e84a9b33200d774e9c3e8fdc\play-services-location-17.0.0.
         > Cannot parse result path string: 
   > Failed to transform artifact 'play-services-places-placereport.aar (com.google.android.gms:play-services-places-placereport:17.0.0)' to match attributes {artifactType=android-mani
fest}.
      > Execution failed for AarTransform: C:\Users\aliha\.gradle\caches\transforms-2\files-2.1\15ef44584736ececfa6c8ba441f42b43\play-services-places-placereport-17.0.0.
         > Cannot parse result path string: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        48.9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by alihassan143** [comment]
> Running "flutter pub get" in flutter_app... 1.1s
> Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
> Launching lib\main.dart on sdk gphone x86 in debug mode...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:processDebugManifest'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Failed to transform artifact 'play-services-location.aar (com.google.android.gms:play-services-location:17.0.0)' to match attributes {artifactType=android-manifest}.
> > > Execution failed for AarTransform: C:\Users\aliha.gradle\caches\transforms-2\files-2.1\4161f8a9e84a9b33200d774e9c3e8fdc\play-services-location-17.0.0.
> > > Cannot parse result path string:
> > Failed to transform artifact 'play-services-places-placereport.aar (com.google.android.gms:play-services-places-placereport:17.0.0)' to match attributes {artifactType=android-mani
> > fest}.
> > > Execution failed for AarTransform: C:\Users\aliha.gradle\caches\transforms-2\files-2.1\15ef44584736ececfa6c8ba441f42b43\play-services-places-placereport-17.0.0.
> > > Cannot parse result path string:
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 48.9s
> Exception: Gradle task assembleDebug failed with exit code 1

i am getting these error

**Comment by iapicca** [comment]
@alihassan143 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin,
please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by alihassan143** [comment]
PS E:\AndroidProjects\fapp\flutter_app> flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-PK)
    • Flutter version 1.22.6 at C:\Users\aliha\flutter
    • Framework revision 9b2d32b605 (8 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\aliha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio2
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\aliha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

**Comment by alihassan143** [comment]
Execution failed for task ':app:processDebugManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'play-services-location.aar (com.google.android.gms:play-services-location:17.0.0)' to match attributes {artifactType=android-manifest}.
      > Execution failed for AarTransform: C:\Users\aliha\.gradle\caches\transforms-2\files-2.1\4161f8a9e84a9b33200d774e9c3e8fdc\play-services-location-17.0.0.
         > Cannot parse result path string: 
   > Failed to transform artifact 'play-services-places-placereport.aar (com.google.android.gms:play-services-places-placereport:17.0.0)' to match attributes {artifactType=android-manifest}.
      > Execution failed for AarTransform: C:\Users\aliha\.gradle\caches\transforms-2\files-2.1\15ef44584736ececfa6c8ba441f42b43\play-services-places-placereport-17.0.0.
         > Cannot parse result path string: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Exception: Gradle task assembleDebug failed with exit code 1
that wrror i am facing when i try to restart app

**Comment by alihassan143** [comment]
issue resolved by changing build gradle dependecies
from
 classpath 'com.android.tools.build:gradle:3.5.0'

    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
             To
 classpath 'com.android.tools.build:gradle:3.3.0'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
