### ISSUE TITLE
Cannot call set state inside NotificationListner

### ISSUE THREAD

**Issue by kiranIssac** [flutter/flutter#75067]
Another exception was thrown: ScrollController not attached to any scroll views.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.

**Comment by iapicca** [comment]
@kiranIssac 
can you provide your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@kiranIssac 
Check out [this](https://flutteragency.com/how-to-solve-scroll-controller-could-not-attached-to-any-scroll-views-in-flutter/) link and see if it resolves your issue.
If not, provide the above requested details.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
