### ISSUE TITLE
search box missing on docs.flutter.io on mobile

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7507]
![simulator screen shot jan 17 2017 7 09 04 am](https://cloud.githubusercontent.com/assets/11857803/22025847/dddbec52-dc83-11e6-898b-8a27b5360d8f.png)

**Comment by LarkAscending** [comment]
More detail - on Android/Nexus 5x, the search box appears in landscape mode but not in portrait.

**Comment by sethladd** [comment]
This might be a bug with dartdoc. Same thing happens on api.dartlang.org

**Comment by sethladd** [comment]
Tracking this on https://github.com/dart-lang/dartdoc/issues/1348
