### ISSUE TITLE
Flutter web deployed using GitHub Pages redirects to a different site.

### ISSUE THREAD

**Issue by Imgkl** [flutter/flutter#75070]
I found a peculiar bug that happens **ONLY** to Flutter Web projects which use GitHub pages deployment. 

So I'm trying to deploy my flutter web app using GitHub pages, but I'm facing a weird issue. So I have my portfolio on [imgkl.github.io][1] and I'm trying to deploy another app called fl_catalogue which has the URL, [imgkl.github.io/fl_catalogue/][2]. But when I try to go to the fl_catalogue app, it takes me to my portfolio.

FYI: Already opened a Stackoverflow question regarding this, no luck there. 

[![my portfolio][3]][3] 

[![fl_catalogue][4]][4]

I'm deploying the site, using this workflow.

    name: Flutter Web
    on:
    push:
    branches:
      - master
    jobs:
     build:
       name: Build Web
       env:
         my_secret: ${{secrets.commit_secret}}
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v1
          - uses: subosito/flutter-action@v1
            with:
               channel: 'beta'
          - run: flutter config --enable-web
          - run: flutter pub get
          - run: flutter build web --release
          - run: |
              cd build/web
              git init
              git config --global user.email my_email
              git config --global user.name Imgkl
              git status
              git remote add origin https://${{secrets.commit_secret}}@github.com/Imgkl/fl_catalogue.git
              git checkout -b gh-pages
              git add --all
              git commit -m "update"
              git push origin gh-pages -f

  [1]: https://imgkl.github.io
  [2]: https://imgkl.github.io/fl_catalogue/
  [3]: https://i.stack.imgur.com/9WjEz.png
  [4]: https://i.stack.imgur.com/DZFPc.png

**Comment by bernaferrari** [comment]
Shouldn't it be /#/fl_catalogue/ or something like this?

**Comment by Imgkl** [comment]
No. Tried the url, https://imgkl.github.io/#/fl_catalogue/ 

But, still it redirects to my portfolio.

**Comment by Imgkl** [comment]
Found a solution to this issue, We have to change the `<base href="/">` to `<base href="/fl_catalogue/">` in the index.html which is in web folder. 

```
<!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    Fore more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/">
```
