### ISSUE TITLE
The lifecycle is called over and over again in the method 'didChangeAppLifecycleState' of the class 'WidgetsBindingObserver'.

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#75080]
When my app is in the background by locking out the screen，My video player is constantly pausing and playing. 

_The sample code is as follows：_

> 
 @override
 `void` didChangeAppLifecycleState(AppLifecycleState state) {

    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      print("resumed");
      _tryResumeVideo();
    } else if (state == AppLifecycleState.paused) {
      print("paused");
      _pausePlayingVideos();
    }

  `}`
> 
**I've been testing and testing and I've found exactly what the title says. The log 'resumed' and 'paused' are constantly being printed After the rest screen.**

**Comment by iapicca** [comment]
@ModWU 
can you provide your `flutter doctor -v` and a **_complete runnable_** [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@ModWU 
According to official documentation, `didChangeAppLifecycleState` is only called when your application is sent to background or returns to foreground, like when swapping between other applications. While `resumed` is called when application is visible and responding to user input.
Do you see similar behavior ?
If not, provide above requested details to better address your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
