### ISSUE TITLE
Showing error  'assetName != null': is not true 

### ISSUE THREAD

**Issue by Amit506** [flutter/flutter#75082]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building SplashContent(dirty):
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 136 pos 15: 'assetName != null': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
SplashContent
lib\…\components\body.dart:48
When the exception was thrown, this was the stack
#2      new AssetImage
package:flutter/…/painting/image_resolution.dart:136
#3      new Image.asset
package:flutter/…/widgets/image.dart:641
#4      SplashContent.build
package:uniapp/…/components/splash_content.dart:32
#5      StatelessElement.build
package:flutter/…/widgets/framework.dart:4701
#6      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
...

**Comment by iapicca** [comment]
@Amit506 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Amit506** [comment]
@iapicca thank you for your response , but somehow I managed to correct it.

**Comment by gohardhuddi** [comment]
in my case the variable returning null I debug it and now it works fine
