### ISSUE TITLE
App behaves differently in release and debug mode

### ISSUE THREAD

**Issue by Batflash5** [flutter/flutter#75081]
Navigation to new page with Get.off()  works in debug mode but it is not working in release mode(Same page is pushed again).

RaisedButton(
                      elevation: 5.0,
                      onPressed: (){
                        String username = 'Lorem ipsum';
                        String password = 'Lorem ipsum';
                        print(password);
                        if (username != '' && password != '') {
                          print('Successful');
                          userdata.write('isLogged', true);
                          userdata.write('username',username );
                          userdata.write('password',password );
                          Get.offAll(LoadingScreen(),popGesture:false); // Navigation should occur here.
                        }else{
                          Get.snackbar("Error", "Please Enter RollNo & Password",snackPosition: SnackPosition.BOTTOM);
                        }
                      },
                      padding: EdgeInsets.all(15.0),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      color: Colors.white,
                      child: Text(
                        'LOGIN',
                        style: TextStyle(
                          color: Color(0xFF527DAA),
                          letterSpacing: 1.5,
                          fontSize: 18.0,
                          fontWeight: FontWeight.bold,
                          fontFamily: 'OpenSans',
                        ),
                      ),
                    )

flutter doctor :
   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.630], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
@Batflash5 
[get](https://pub.dev/packages/get) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/jonataslaw/getx/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by Batflash5** [comment]
Navigation to new page  works in debug mode but it is not working in release mode(Same page is pushed again).

Minimal Reproducible Code:

RaisedButton(
elevation: 5.0,
onPressed: (){
String username = 'Lorem ipsum';
String password = 'Lorem ipsum';
print(password);
if (username != '' && password != '') {
print('Successful');
userdata.write('isLogged', true);
userdata.write('username',username );
userdata.write('password',password );
Navigator.push(context,MaterialPageRoute(builder: (context)=>LoadingScreen())); // Navigation should occur here.
}else{
Get.snackbar("Error", "Please Enter RollNo & Password",snackPosition: SnackPosition.BOTTOM);
}
},
padding: EdgeInsets.all(15.0),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30.0),
),
color: Colors.white,
child: Text(
'LOGIN',
style: TextStyle(
color: Color(0xFF527DAA),
letterSpacing: 1.5,
fontSize: 18.0,
fontWeight: FontWeight.bold,
fontFamily: 'OpenSans',
),
),
)

flutter doctor :

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.630], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
> Get.snackbar("Error", "Please Enter RollNo & Password",snackPosition: SnackPosition.BOTTOM);

@Batflash5 
can you provide  a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
**_without 3rd party plugins_**

**Comment by Batflash5** [comment]
class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  final username_controller = TextEditingController();
  final password_controller = TextEditingController();


  @override
  Widget build(BuildContext context) {
    final double height=MediaQuery.of(context).size.height;
    final double width=MediaQuery.of(context).size.width;
    return Scaffold(
      body: Container(
        child: Center(
          child: Container(
            padding: EdgeInsets.symmetric(horizontal: width/10),
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        'RollNo',
                      ),
                      SizedBox(height: 10.0),
                      Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(20),
                        ),
                        alignment: Alignment.centerLeft,
                        height: 60.0,
                        child: Card(
                          color: Colors.transparent,
                          elevation: 45,
                          child: TextField(
                            controller: username_controller,
                            keyboardType: TextInputType.text,
                            style: TextStyle(
                              color: Colors.white,
                              fontFamily: 'OpenSans',
                            ),
                            decoration: InputDecoration(
                              border: InputBorder.none,
                              contentPadding: EdgeInsets.only(top: 14.0),
                              prefixIcon: Icon(
                                Icons.add,
                                color: Colors.white,
                              ),
                              hintText: 'Enter your RollNo',
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(
                    height: height/35,
                  ),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        'Password',
                      ),
                      SizedBox(height: 10.0),
                      Card(
                        elevation: 45,
                        color: Colors.transparent,
                        child: Container(
                          alignment: Alignment.centerLeft,
                          height: 60.0,
                          child: TextField(
                            controller: password_controller,
                            obscureText: true,
                            style: TextStyle(
                              color: Colors.white,
                              fontFamily: 'OpenSans',
                            ),
                            decoration: InputDecoration(
                              border: InputBorder.none,
                              contentPadding: EdgeInsets.only(top: 14.0),
                              prefixIcon: Icon(
                                Icons.lock,
                                color: Colors.white,
                              ),
                              hintText: 'Enter your Password',
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(
                    height: height/20,
                  ),
                  Container(
                    padding: EdgeInsets.symmetric(vertical: 25.0),
                    width: double.infinity,
                    child: RaisedButton(
                      elevation: 5.0,
                      onPressed: (){
                        String username = username_controller.text;
                        String password = password_controller.text;
                        print(password);
                        if (username != '' && password != '') {
                          print('Successful');
                          Navigator.push(context,MaterialPageRoute(builder: (context)=>LoadingScreen())); 
                        }
                      },
                      padding: EdgeInsets.all(15.0),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      color: Colors.white,
                      child: Text(
                        'LOGIN',
                        style: TextStyle(
                          color: Color(0xFF527DAA),
                          letterSpacing: 1.5,
                          fontSize: 18.0,
                          fontWeight: FontWeight.bold,
                          fontFamily: 'OpenSans',
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by Batflash5** [comment]
@ianloic 
Is the code enough?

**Comment by pedromassangocode** [comment]
Hi @Batflash5 
Please provide your `flutter doctor -v` and a complete runnable minimal reproducible code sample
without 3rd party plugins. Please see [here](https://stackoverflow.com/help/minimal-reproducible-example) in how to create code sample.
Thank you

**Comment by Batflash5** [comment]
**flutter doctor -v**
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.630], locale en-IN)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (9 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\hpyes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\hpyes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • CPH2001 (mobile) • WSBQYPPRYSYHCULZ • android-arm64 • Android 10 (API 29)

**Minimal Reproducible Code:**

`void main(){
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  final username_controller = TextEditingController();
  final password_controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            TextField(
              controller: username_controller,
            ),
            TextField(
              controller: password_controller,
            ),
            RaisedButton(
              onPressed: (){
                String username = username_controller.text;
                String password = password_controller.text;
                if (username != '' && password != '') {
                  Navigator.push(context,MaterialPageRoute(builder: (context)=>Container(child:Text('Logged in'))));
                }
                else {
                  print('Error');
                }
              },
              child: Text(
                'LOGIN',
              ),
            )
          ],
        ),
      ),
    );
  }
}`

**Comment by Batflash5** [comment]
Is it enough? @pedromassangocode 
Should I provide more details?

**Comment by pedromassangocode** [comment]
Hi @Batflash5 
Can you please provide the actual vs expected results?
Thank you

**Comment by Batflash5** [comment]
Expected:  Navigation should occur
Actual: Navigation didn't occur

**Comment by iapicca** [comment]
@Batflash5 
there are a few things off in your code sample,
to verify that the issue is with flutter an not in your implementation a wrote a [new code sample](https://dartpad.dartlang.org/3a7581fde6139b48db226def0395bc0d?) that does essentially the same as yours

please try it out with `flutter run --release`
i tried it out myself on physical device and everything works just fine

**Comment by Batflash5** [comment]
I got the problem figured out.
Permission for internet was not given.
Thanks for the help
