### ISSUE TITLE
Flutter 1.12.13+hotfix.9 Crash

### ISSUE THREAD

**Issue by huangshengjie123** [flutter/flutter#75089]
AppleMetalGLRenderer | GLRResourceList::addResource(GLRResource*) + 40
-- | --
1 AppleMetalGLRenderer | GLDContextRec::addRenderPassResources() + 68
2 AppleMetalGLRenderer | GLDContextRec::addRenderPassResources() + 68
3 AppleMetalGLRenderer | gldClearFramebufferData + 224
4 GLEngine | _glClear_Exec + 452
5 Flutter | 0x0000000104118000 + 2005140
6 Flutter | 0x0000000104118000 + 1953608
7 Flutter | 0x0000000104118000 + 1955068
8 Flutter | 0x0000000104118000 + 2084716
9 Flutter | 0x0000000104118000 + 2546828
10 Flutter | 0x0000000104118000 + 4281636
11 Flutter | 0x0000000104118000 + 576184
12 Flutter | 0x0000000104118000 + 502000
13 Flutter | 0x0000000104118000 + 505508
14 Flutter | 0x0000000104118000 + 502704
15 Flutter | 0x0000000104118000 + 527232
16 Flutter | 0x0000000104118000 + 241496
17 Flutter | 0x0000000104118000 + 250332
18 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
19 CoreFoundation | ___CFRunLoopDoTimer + 1004
20 CoreFoundation | ___CFRunLoopDoTimers + 324
21 CoreFoundation | ___CFRunLoopRun + 1912
22 CoreFoundation | CFRunLoopRunSpecific + 572
23 Flutter | 0x0000000104118000 + 250040
24 Flutter | 0x0000000104118000 + 248004
25 libsystem_pthread.dylib | _pthread_start + 288

How can I do?

[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on macOS 11.1 20C69, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[!] Xcode - develop for iOS and macOS       
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

**Comment by iapicca** [comment]
@huangshengjie123 
your flutter version is **_VERY_** old please run `flutter upgrade -f`
if the issue persists please provide 
your updated `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by huangshengjie123** [comment]
> @huangshengjie123
> your flutter version is **_VERY_** old please run `flutter upgrade -f`
> if the issue persists please provide
> your updated `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Which version？

**Comment by huangshengjie123** [comment]
Which version? @iapicca

**Comment by Abhishek01039** [comment]
The latest stable version is `1.22.6`. @huangshengjie123

**Comment by pedromassangocode** [comment]
Hi @huangshengjie123 
Please follow the steps described in https://github.com/flutter/flutter/issues/75089#issuecomment-770396489.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
