### ISSUE TITLE
Implement CupertinoSegmentedControl

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7509]
https://developer.apple.com/ios/human-interface-guidelines/controls/segmented-controls/

**Comment by xster** [comment]
https://github.com/theobouwman/flutter_cupertino_segment_control, nice

**Comment by lukaspili** [comment]
I have written a fully featured segmented control widget internally.
Do you consider PR for this kind of work? If yes, I can make one shortly.

**Comment by xster** [comment]
@lukaspili, absolutely. PRs are highly appreciated. We had a previous PR (https://github.com/flutter/flutter/pull/12584) that you can look at for reference (of things we look at in review).

**Comment by xster** [comment]
Small side note: worth building it in a way that has a reusable component to support https://developer.apple.com/design/human-interface-guidelines/ios/controls/steppers/

**Comment by xster** [comment]
What's left for this item?

**Comment by nataliesampsell** [comment]
Waiting for a LGTM to push a PR adding animation: https://github.com/flutter/flutter/pull/18811

Once this has landed, I believe this widget is complete.

**Comment by xster** [comment]
As a last task, please also add a demo of the segmented control into our flutter_gallery

**Comment by xster** [comment]
As a last+1 task :) please also add this to https://flutter.io/widgets/cupertino/ in the https://github.com/flutter/website repo

**Comment by xster** [comment]
For record, the PRs are #18373 and #18811

**Comment by xster** [comment]
The widget is in the gallery and the widgets catalog website now.
