### ISSUE TITLE
Is it possible to pass --no-sound-null-safety in gradle build?

### ISSUE THREAD

**Issue by MrCreeper1008** [flutter/flutter#75092]
When I try to make project in Android Studio in the android folder, I encountered this:
```
> Task :app:compileFlutterBuildDebug
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
```
Normally this would be resolved by passing `--no-sound-null-safety` to the `flutter` command, but as far as I am aware this is not possible to do when running gradle builds without actually running the app. I need this functionality to generate protobuf code from my protobuf schemas.

## Steps to Reproduce

1. Enable null safety by setting Dart sdk constraint to `>=2.12.0-0 <3.0.0`
2. Open android folder in Android Studio
3. Run "make project"

**Expected results:**

Able to enable `--no-sound-null-safety` in my gradle file.

**Actual results:**

I can run my app just fine with `flutter run --no-sound-null-safety`, but when I try to make project in Android Studio this occurs:

```
> Task :app:compileFlutterBuildDebug
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Users/kenneth/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kenneth/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/kenneth/Library/Android/sdk
    • Java binary at: /Users/kenneth/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/kenneth/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Pixel 3a (mobile)          • 9ADAY1D26G                           • android-arm64 • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 95E5AEE5-6906-496D-8651-654AAA48E051 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by aarontwf** [comment]
Try adding add `// @dart=2.9` to the top of your app entry point file (usually `lib/main.dart`), that worked for me when generating APKs.

https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs

**Comment by darshankawar** [comment]
@MrCreeper1008 
Check above solution and see if it helps.

**Comment by MrCreeper1008** [comment]
Thank you, that worked wonderfully.

**Comment by deviant-studio** [comment]
Guys this needs to be resolved.
What if I already migrated my code to null safety?

I get ```Error: The modifier 'late' is only available in null safe libraries.``` when trying proposed solution.

**Comment by jiangxiaoqiang** [comment]
> Try adding add `// @dart=2.9` to the top of your app entry point file (usually `lib/main.dart`), that worked for me when generating APKs.
> 
> https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs

not fix it.

**Comment by mmkumr** [comment]
> Guys this needs to be resolved.
> What if I already migrated my code to null safety?
> 
> I get `Error: The modifier 'late' is only available in null safe libraries.` when trying proposed solution.

Just remove late keyword, '?' and "!"(If it is showing error in that line).

**Comment by 0xNF** [comment]
Im stuck on this too. A build using the `build.gradle` file will fail in a no sound null safety library. adding // @dart=2.9 to the main.dart file isn't a fix because it removes it sets dart back to a version where null safety isn't implemented at all, i.e., syntax such as ? and ! aren't recognized. This is not an acceptable fix. 

How do I pass `--no-sound-null-safety` to the flutter build process through gradle?

**Comment by EviCoach** [comment]
> Try adding add `// @dart=2.9` to the top of your app entry point file (usually `lib/main.dart`), that worked for me when generating APKs.
> 
> https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs

This worked for me
