### ISSUE TITLE
Improper assertion in maxCrossAxisExtent in SliverGridDelegateWithMaxCrossAxisExtent

### ISSUE THREAD

**Issue by chinmoy12c** [flutter/flutter#75093]
The assertion in ```SliverGridDelegateWithMaxCrossAxisExtent``` checks for ```maxCrossAxisExtent >= 0```  instead of ```maxCrossAxisExtent > 0```

**Comment by pedromassangocode** [comment]
Hi @chinmoy12c 
I'm not really sure if this is a bug in the code. Has this caused any issue in your Flutter code?

From the docs, it says that `maxCrossAxisExtent` must not be negative so it should be greater or equals to zero. It clearly seems that it allows Zero (0).

![Screen Shot 2021-02-01 at 09 07 12](https://user-images.githubusercontent.com/67424416/106430957-e10e7a00-646c-11eb-9e3d-9c4b1ca49634.png)

**Comment by chinmoy12c** [comment]
Hi @pedromassango ,

actually it does throw an assertion error later due to this asset statement in the code ,
