### ISSUE TITLE
Running `flutter clean` should verify the current directory is a Flutter project before proceeding

### ISSUE THREAD

**Issue by amugofjava** [flutter/flutter#75098]
## Use case

I will often perform a `flutter clean` before creating a release for the Play Store to ensure a clean build. On one occasion I mistakenly ran this one level up from the actual project directory. The clean process then reported it had moved to my home directory before deleting `.dart_tool` and `.android`. On a Linux system `.android` lives under a user's home directory and contains all the AVDs.

## Proposal

Running `flutter clean` should report if the current directory does not contain a Flutter project, rather than deciding to move to the user's home directory and then performing its deletes. If the current directory does not contain a Flutter project, why would it switch to a home directory and try again?

![Screenshot from 2021-01-31 17-31-57](https://user-images.githubusercontent.com/5526902/106392549-3fdedf80-63ea-11eb-9c64-295b945fa1f9.png)

As you can see from the above screen shot, I mistakingly ran the command at the top level projects directory, rather than the application sub-directory; but, `flutter clean` decided to move to my home directory and remove `.android` thus deleting all my Android AVDs. 

If you run `flutter clean` outside of the home directory tree, for example /tmp, you are given a more expected result:

```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

![Screenshot from 2021-01-31 17-35-12](https://user-images.githubusercontent.com/5526902/106392647-baa7fa80-63ea-11eb-8a9f-81364d400335.png)

Running `flutter clean --help` shows it should delete the `build` and `.dart_tool` directory and has no mention of `.android`.

Flutter doctor:

```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.6 at /home/ben/Development/flutter
    • Framework revision 9b2d32b605 (9 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /media/ubuntudata/Development/android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/ben/Development/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/ben/Development/android/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Thanks.

**Comment by jonahwilliams** [comment]
flutter clean does check for a pubspec.yaml. Do you have one in your home dir?

**Comment by amugofjava** [comment]
Hi @jonahwilliams. Yes, there is a backup one in my home directory. If a it doesn't find a `pubspec.yaml` in the current directory, does a clean search up the directory tree until it finds a `pubspec.yaml` in a parent directory?

**Comment by jonahwilliams** [comment]
> Yes, there is a backup one in my home directory

For all intents and purposes, you have communicated to the flutter tool that your home directory is a flutter project. flutter can't really determine what is a flutter project besides checking for one of those.

**Comment by amugofjava** [comment]
OK, testing a little here, if I make several nested directories below a project and do a `flutter clean` from the bottom of the tree it does search back up until it finds a `pubspec.yaml`. I have learnt something there.

Many thanks for your help.
