### ISSUE TITLE
While I try to switch from stable channel to beta for web development , this error stopped my progress!!!

### ISSUE THREAD

**Issue by abraraltaf92** [flutter/flutter#75106]
Unhandled exception:
Exception: Flutter failed to create a directory at "/Users/abraraltaflone/.config/flutter". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:731:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:686:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:550:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:397:12)
#5      new Config (package:flutter_tools/src/base/config.dart:33:17)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:144:21)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:301:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     config (package:flutter_tools/src/globals.dart:47:30)
#12     getBuildDirectory (package:flutter_tools/src/build_info.dart:673:48)
#13     defaultDepfilePath (package:flutter_tools/src/bundle.dart:29:55)
#14     new BuildBundleCommand (package:flutter_tools/src/commands/build_bundle.dart:24:42)
#15     new BuildCommand (package:flutter_tools/src/commands/build.dart:30:19)
#16     main.<anonymous closure> (package:flutter_tools/executable.dart:100:5)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:49:13)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:88:3)
<asynchronous suspension>

**Comment by timsneath** [comment]
...and does Flutter have permissions to that folder?

**Comment by abraraltaf92** [comment]
how to check that? And why shouldn't it have?

**Comment by abraraltaf92** [comment]
*got resolved . Actually had to give permission to access it and it felt a brainstorming kinda
