### ISSUE TITLE
Adding property for the scrollbar to be in right or the left side of the screen

### ISSUE THREAD

**Issue by alionour** [flutter/flutter#75105]

**Comment by pedromassangocode** [comment]
Hi @alionour 
Can you please elaborate why do you need this feature and what is your use-case?
Thank you

**Comment by alionour** [comment]
## Use case



## Proposal

**Comment by pedromassangocode** [comment]
Thanks for the information.
This can be easily done by providing a way to change the text direction of the Scrollbar widget.

**Comment by HansMuller** [comment]
CC @Piinks
