### ISSUE TITLE
Camera - example code is not finding any cameras

### ISSUE THREAD

**Issue by ozhikaye** [flutter/flutter#75103]
I ran the example code as is without any modifications. The app starts up and the preview section shows up with the text "Tap a camera" in the middle. At the bottom where it would list the camera's it says "No camera found".

How can I figure out why it's not finding the cameras?

Flutter doctor command result:
```bash
  Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.6 19G2021 darwin-x64,
      locale en-AU)
 
  [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
  [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
  [✓] Android Studio (version 4.1)
  [✓] Connected device (1 available)

  • No issues found!
```

**Comment by TahaTesser** [comment]
Hi @ozhikaye 
Please make sure to follow the [Installation](https://pub.dev/packages/camera#installation) instructions
Can you please provide more details? Which device are you using to test this? Have you tried another device?
Thank you

**Comment by ozhikaye** [comment]
Ah. I just assumed that all that would be setup in the example. I'll check
and report back.

**Comment by TahaTesser** [comment]
@ozhikaye 
If you're cloning the repo, it should work and you shouldn't have any issues. If you're copying code sample, you need to do more.

**Comment by ozhikaye** [comment]
I did clone the repo and confirmed that all the required entries are there as per the install instructions.
I'm using a MacOS and using the iOS Simulator. I followed the following instructions for setting up and running the simulator.
https://flutter.dev/docs/get-started/install/macos

I did have an error in the output that stated "...Because android_intent requires SDK version >=2.12.0-0 <3.0.0,..."

I was able to resolve this by switching to Flutter Beta channel.

Errors are showing up for the other packages in the repo though the camera package has no errors.

**Comment by amzahrani** [comment]
use setState(){} after updating the available cameras.

**Comment by TahaTesser** [comment]
Hi @ozhikaye 
You can't use cameras on an iOS simulator, please use a physical device for iOS. Check out this [answer](https://stackoverflow.com/a/25486148).
Closing, as this isn't an issue with `camera` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ozhikaye** [comment]
Don't want to re-open. 
Just as a note, the camera worked on a physical device. Thanks for your assistance @TahaTesser .
