### ISSUE TITLE
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

### ISSUE THREAD

**Issue by abdulrojak288** [flutter/flutter#75112]
flutter channel master
flutter upgrade
flutter clean
flutter run

but not resolve [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

please help me.

**Comment by pedromassangocode** [comment]
Hi @abdulrojak288 
Is this happening during Flutter upgrade? Can you please run from your terminal (making sure that flutter is added to your path)
```console
flutter doctor -v
```
and provide the full logs.
Thank you

**Comment by abdulrojak288** [comment]
> Hi @abdulrojak288
> Is this happening during Flutter upgrade? Can you please run from your terminal (making sure that flutter is added to your path)
> 
> ```
> flutter doctor -v
> ```
> 
> and provide the full logs.
> Thank you
![8BC70C3B-D83A-49D6-8970-A9F122C8C36A](https://user-images.githubusercontent.com/25262540/109265014-7288c600-7838-11eb-92ee-cba593395f7c.jpeg)

**Comment by pedromassangocode** [comment]
Hi @abdulrojak288 
Your Flutter version is three months old, can you please upgrade and try again?
To upgrade, please run:

`flutter channel master`
`flutter upgrade -v`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v` and the steps to reproduce.
Thank you

**Comment by abdulrojak288** [comment]
> Hi @abdulrojak288
> Your Flutter version is three months old, can you please upgrade and try again?
> To upgrade, please run:
> 
> `flutter channel master`
> `flutter upgrade -v`
> `flutter doctor -v`
> 
> If the issue persists, please provide your `flutter doctor -v` and the steps to reproduce.
> Thank you

hi sir @pedromassangocode is it safe to use the master channel for production?

**Comment by pedromassangocode** [comment]
> hi sir @pedromassangocode is it safe to use the master channel for production?

It depends. I personally would not recommend as it is a working branch and may contain unwanted behaviors, bugs.

**Comment by abdulrojak288** [comment]
> > hi sir @pedromassangocode is it safe to use the master channel for production?
> 
> It depends. I personally would not recommend as it is a working branch and may contain unwanted behaviors, bugs.

actually I used a stable channel before but a bug appeared [VERBOSE-2: profiler_metrics_ios.mm (184)] Error retrieving thread information: (ipc / send) invalid destination port, after that someone recommended me to change to the master channel. issue:
[](https://github.com/flutter/flutter/issues/63025#issuecomment-745733989)

now a bug appears on the master channel as described above. I'm confused whether to return to the stable channel or not. can you give the best advice for me

**Comment by pedromassangocode** [comment]
Have you updated to the latest version of Flutter yet? Can you provide your `flutter doctor -v`? Do you have any steps to reproduce this issue?
Thank you


> now a bug appears on the master channel as described above. I'm confused whether to return to the stable channel or not. can you give the best advice for me

I'm not sure about that. If you are building mobile apps and all you want is on stable, I suggest to use it to avoid bugs. All depends on you. My advice may not be the best for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by semmdeveloper** [comment]
hello
