### ISSUE TITLE
How to do Hard Restart in flutter web?

### ISSUE THREAD

**Issue by priyeshstackapp** [flutter/flutter#75114]
I've uploaded my webapp many times but I'm continuously one issue. I've to do hard restart manually.

I used **version** as per below but not working.

`<script src="main.dart.js?version=4" type="application/javascript"></script>`

Anybody have solution regarding this?

**Comment by darshankawar** [comment]
@priyeshstackapp 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter framework but more of a `How to` question. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by priyeshstackapp** [comment]
Hi @darshankawar I've updated my question now, Can you please check this issue and make it open now?

**Comment by darshankawar** [comment]
@priyeshstackapp 
hot reload is not supported on web yet. See this open issue for your reference, https://github.com/flutter/flutter/issues/53041

**Comment by priyeshstackapp** [comment]
Okay thank you!
