### ISSUE TITLE
[gen-l10n] Generated code not linted according to the Flutter style guide

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#75127]
For example, the following lines were accepted in the generated Dart code (see [this commit](https://github.com/flutter/flutter/pull/75056/files#diff-81aebbc212a47249da1768da48e4049abdeb436b527fb755d5ef2249b4d5f661R116)):
```dart
    final @(placeholder)NumberFormat = intl.NumberFormat.@(format)(localeName);
    final @(placeholder)String = @(placeholder)NumberFormat.format(@(placeholder));
```

However, we should really require specifying the variable type, so it should be:
```dart
    final intl.NumberFormat @(placeholder)NumberFormat = intl.NumberFormat.@(format)(localeName);
    final String @(placeholder)String = @(placeholder)NumberFormat.format(@(placeholder));
```

**Comment by christopherfujino** [comment]
Out of curiosity, why does this generated code need to conform to Flutter's style guide?

**Comment by christopherfujino** [comment]
Closing this as a won't fix, as I don't think gen-l10n needs to conform to the Flutter repo style guide.
