### ISSUE TITLE
Execution failed for task ':app:mergeDebugAssets'.

### ISSUE THREAD

**Issue by Calvin1121** [flutter/flutter#75129]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
I installed the Flutter, and created an demo named 'myapp'. And when it done, I checked to root of the directory, and run 'flutter run'. And then, it throws an error and build failed. I run it on Win7, but I executed it in the same way on Mac, and it worked well.
**Expected results:** 
The project can work well.
**Actual results:** 
The terminal throws an error. And I got these.
PS C:\Users\admin\Desktop\myapp> flutter run
Running "flutter pub get" in myapp...                              799ms
Launching lib\main.dart on MI 9 in debug mode...
Running Gradle task 'assembleDebug'...

```

FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:mergeDebugAssets'.

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

   > Could not find io.flutter:flutter_embedding_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.

     Searched in the following locations:

       - https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e77
6ac03fa9bc/flutter_embedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/f
lutter_embedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca0
2c276dce02f8dd42a44e776ac03fa9bc/flutter_embedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

     Required by:

         project :app

   > Could not find io.flutter:x86_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.

     Searched in the following locations:

       - https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86
_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_debug-1.0.0
-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd
42a44e776ac03fa9bc/x86_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

     Required by:

         project :app

   > Could not find io.flutter:x86_64_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.

     Searched in the following locations:

       - https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/
x86_64_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_64_debug
-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

       - https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f
8dd42a44e776ac03fa9bc/x86_64_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom

     Required by:

         project :app



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 31s
Running Gradle task 'assembleDebug'...                             32.9s
Exception: Gradle task assembleDebug failed with exit code 1
PS C:\Users\admin\Desktop\myapp>
<details>
  <summary>Logs</summary>

<!--
      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->

```
[  +77 ms] executing: [D:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +203 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] executing: [D:\src\flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[ +184 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +40 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +169 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [D:\src\flutter/] git ls-remote --get-url origin
[ +160 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +198 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +264 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +153 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +179 ms] List of devices attached
           127.0.0.1:21503        device product:MI 9 model:MI_9 device:MI 9 transport_id:1
[   +6 ms] C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 127.0.0.1:21503 shell getprop
[ +178 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] "flutter run" took 483ms.
[  +17 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +4 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1251:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:430:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1091:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)

           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>

[ +299 ms] ensureAnalyticsSent: 295ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Calvin1121 
Your error log shows below:

`[ +17 ms] Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.`

Are you sure you are running `flutter ` command from root of your project path ?
If so, can you check if at the root path of your project, do you see `pubspec.yaml` file ? If not, fix the path (ie, `cd` to the correct path where `pubspec.yaml` is and try again to see if it works).

**Comment by Calvin1121** [comment]
I'm sure there is the file at the root path of project. And when I run 'flutter run --verbose' at the root path on ternimal. The log is:

PS C:\Users\admin\Desktop\myapp> flutter run --verbose
[  +75 ms] executing: [D:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +196 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] executing: [D:\src\flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[ +173 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +40 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +161 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [D:\src\flutter/] git ls-remote --get-url origin
[ +160 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +194 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +162 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +148 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +179 ms] List of devices attached
           127.0.0.1:21503        device product:MI 9 model:MI_9 device:MI 9 transport_id:1
[   +6 ms] C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 127.0.0.1:21503 shell getprop
[ +176 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] Skipping pub get: version match.
[ +235 ms] Found plugin integration_test at D:\src\flutter\packages\integration_test\
[ +187 ms] Found plugin integration_test at D:\src\flutter\packages\integration_test\
[   +5 ms] Generating
C:\Users\admin\Desktop\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +53 ms] ro.hardware = qcom
[  +37 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +5 ms] Launching lib\main.dart on MI 9 in debug mode...
[   +6 ms] D:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\admin\AppData\Local\Temp\flutter_tools.cc79b5f1\flutter_tool.b55f955c\app.dill --packages
C:\Users\admin\Desktop\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +15 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 127.0.0.1:21503 shell -x logcat

-v time -t 1
[ +225 ms] <- compile package:myapp/main.dart
[ +179 ms] --------- beginning of main
           02-04 15:10:17.346 W/WifiMode(  547): cxyap22682, Invalid SupportedRates!!!
[ +149 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +178 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +176 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from C:\Users\admin\Desktop\myapp\android\gradlew.bat.
[   +1 ms] C:\Users\admin\Desktop\myapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +13 ms] executing: D:\Android\jre\bin\java -version
[ +192 ms] Exit code 0 from: D:\Android\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +3 ms] executing: D:\Android\jre\bin\java -version
[ +201 ms] Exit code 0 from: D:\Android\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +2 ms] executing: [C:\Users\admin\Desktop\myapp\android/] C:\Users\admin\Desktop\myapp\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\admin\Desktop\myapp\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +766 ms] Welcome to Gradle 6.7!
[   +1 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[        ]  - Declare the version of Java your build requires
[   +1 ms]  - Java 15 support
[   +1 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+1217 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :integration_test:preBuild UP-TO-DATE
[        ] > Task :integration_test:preDebugBuild UP-TO-DATE
[        ] > Task :integration_test:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :integration_test:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
[+20968 ms] > Task :app:checkDebugAarMetadata FAILED
[  +11 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugAarMetadata'.
[   +1 ms] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[   +6 ms]    > Could not find io.flutter:flutter_embedding_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.
[        ]      Searched in the following locations:
[   +1 ms]        -
https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9b

c/flutter_embedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[   +3 ms]        -
https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/flutter_em

bedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[  +12 ms]        -
https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-7a8f8ca02c276dce0

2f8dd42a44e776ac03fa9bc/flutter_embedding_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[   +7 ms]      Required by:
[  +18 ms]          project :app
[   +5 ms]    > Could not find io.flutter:x86_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.
[        ]      Searched in the following locations:
[        ]        -
https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_debug-1.

0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[        ]        -
https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_debug-1.0.0-7a8f8ca0

2c276dce02f8dd42a44e776ac03fa9bc.pom
[   +1 ms]        -
https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/x86_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776

ac03fa9bc/x86_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[   +1 ms]      Required by:
[        ]          project :app
[        ]    > Could not find io.flutter:x86_64_debug:1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.
[        ]      Searched in the following locations:
[        ]        -
https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_64_de

bug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[        ]        -
https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc/x86_64_debug-1.0.0-7a

8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[        ]        -
https://mirrors.cloud.tencent.com/flutter/download.flutter.io/io/flutter/x86_64_debug/1.0.0-7a8f8ca02c276dce02f8dd42a44e

776ac03fa9bc/x86_64_debug-1.0.0-7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc.pom
[   +1 ms]      Required by:
[        ]          project :app
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 22s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 5 actionable tasks: 1 executed, 4 up-to-date
[ +316 ms] Running Gradle task 'assembleDebug'... (completed in 23.8s)
[   +5 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 25,829ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)

           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>


[ +257 ms] ensureAnalyticsSent: 253ms
[   +5 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[  +16 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
PS C:\Users\admin\Desktop\myapp>

Actually, I run the project on the third-party simulator.

**Comment by darshankawar** [comment]
@Calvin1121 
I see couple of things from your log:

1. You seem to have your app created in `C:/admin` path which may have limited permissisons to execute flutter commands. So try to move your flutter installation and apps created somewhere else where you won't require permissions (ex : Documents or other drive).
2. Assuming you are from China, you may have to use mirror flutter site to run Flutter (esp on Windows). Check this and see if it helps https://github.com/flutter/flutter/issues/14968. Also check this link and try to configure your setup accordingly, https://flutter.dev/community/china
3. Also provide `flutter doctor -v`
4. `Actually, I run the project on the third-party simulator.`. Try that on a physical device or AS emulator / simulator to see if you get same issue or not.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
