### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by krishnatandon1208** [flutter/flutter#75123]
Facing responsiveness issue on https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#2
The Back button hides behind the menu. 
![Responsiveness issue ](https://user-images.githubusercontent.com/58399691/106432876-58f09a80-6495-11eb-8959-bf29cbd7df63.png)

Currently using macOC and browser is chrome

**Comment by darshankawar** [comment]
@krishnatandon1208 
Codelab related issues are maintained and tracked here : https://github.com/flutter/website/issues/
Please consider opening this issue in that repo or check if similar issue already exists in it.
Closing from here.
