### ISSUE TITLE
flutter_plugins check failing on analyzer error

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#75121]
Putting the relevant part of the logs here. This started failing on the most recent commit that caused the tree to go red, which does not seem related: https://github.com/flutter/flutter/commit/25134a16d128ed22dc0ad8d41d2b931fcad3b014

It seems to be a problem with the `path_provider_windows` plugin, but I'm not exactly sure what's going on here since I'm less familiar.

An attempted revert of the latest PR in `packages/path_provider` seemed to try to address this: https://github.com/flutter/plugins/pull/3488

```
...
Running command: "pub global run tuneup check" in /b/s/w/ir/tmp/t/pluginsUOIOGI/packages/path_provider/path_provider_windows
Checking project path_provider_windows...

  error - The method 'setGUID' isn't defined for the type 'Pointer' at lib/src/path_provider_windows_real.dart:119:57 - (undefined_method)

1 issue found; analyzed 11 source files in 5.9s.
...
The following packages have analyzer errors (see above):
 * path_provider_windows
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../../k/flutter/bin/cache/dart-sdk/bin/pub global run flutter_plugin_tools analyze
Relative working directory: ../../tmp/t/pluginsUOIOGI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by shihaohong** [comment]
Seems like https://github.com/flutter/flutter/pull/74885 fixes the issue by forcing the upgrade of flutter's dependencies.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/75050 for an explanation of why this happened. Since `win32` is an external package, and the breaking change was in a prerelease bump, it can be pulled in as soon as it's released without any in-tree changes.

The only way to avoid it in our that I can see would be to pin to an exact version of `win32` in `path_provider_windows`, but pub doesn't allow publishing that way.

**Comment by stuartmorgan** [comment]
@timsneath If this happens again maybe we can coordinate landings of `win32`, `path_provider_windows`, and the plugins->flutter roll to make the breakage window as short as possible?

**Comment by Hixie** [comment]
This breaks flutter/flutter because it's running flutter/plugins test unpinned, right? In principle we could check in the pubspec.lock files for the plugins repo and then it wouldn't try to upgrade arbitrarily when running the tests? (Of course then we'd need to be rolling those files too.)

**Comment by stuartmorgan** [comment]
Closing as obsolete since this was long-since resolved.

> This breaks flutter/flutter because it's running flutter/plugins test unpinned, right?

It's already pinned; the issue here was unpinned dependencies within the plugins themselves, but we already have an issue tracking whether we can reasonably do anything about that.
