### ISSUE TITLE
CP include ffi_allocator_patch.dart

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#75134]
CP request for https://github.com/flutter/engine/pull/23954.

This makes sure `ffi_allocation_patch.dart` is included in the build.
This prevents `AllocatorAlloc.call` from throwing `NoSuchMethodError`s.
Which enables using `Allocator` in `package:ffi` and deprecating `allocate` in `package:ffi` (https://github.com/dart-lang/ffi/commit/b0724659e00ca107120a1e50f841c890128b1982).
Which in turn is needed to roll `package:win32` forward.
Which is needed to address https://github.com/flutter/flutter/issues/75113.

Besides https://github.com/flutter/flutter/issues/75113, this CP is needed also for users to be able to use `Allocator`s in their own `dart:ffi` usage.

**Comment by pcsosinski** [comment]
if this issue is only to track a CP a fix for https://github.com/flutter/flutter/issues/75113, we can just tag https://github.com/flutter/flutter/issues/75113 (we do it differently in Flutter than Dart)

**Comment by dcharkes** [comment]
Closing this because the CP request is on #75113 instead.
