### ISSUE TITLE
Update web site to account for new focus system

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7514]
## Steps to Reproduce

See https://github.com/flutter/website/pull/359

Currently the Tour of the Widget Framework on flutter.io says:
Some widgets, such as Input require global keys because they can hold focus, which means they receive any text the user enters into the app. The Focus widget keeps track of which State object is focused by remembering its GlobalKey. That way the same Input widget remains focused even if it moves around in the widget tree.

But the framework now manages this case for developers, so no action is needed on their part. Rewording and/or a different example is needed.

**Comment by abarth** [comment]
The new focus system is in, so now is a good time to update the web site.

**Comment by abarth** [comment]
Done.
