### ISSUE TITLE
Flutter emulators to run tablet device

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#75149]
## Use case
I am using code magic with Flutter driver to do the E2E test but I need to take screenshots for tablet devices

## Proposal
I wonder if there is any way I can define screen size while running the Flutter emulators command?

**Comment by iapicca** [comment]
@amorenew 
this doesn't seem related to flutter,
you may want to try creating a custom emulator following this [SO answer](https://stackoverflow.com/questions/30211017/create-android-emulatoravd-with-custom-screen-size-and-resolution-from-command)

**Comment by amorenew** [comment]
@iapicca Ok, I am convinced thank you for sharing that StackOverflow answer
