### ISSUE TITLE
[iOS] google_maps_flutter showing thin border when transition to other page

### ISSUE THREAD

**Issue by davidwijayanto2** [flutter/flutter#75150]
I have problem using google_maps_flutter 1.1.1 package, when i test it with iphone 7+ ios 14.3, its showing thin border when transition to other page,and then disappear when the page is shown. It will appear again when transition to close the page and disappear when the page is closed. But when i test it with iphone 6s ios 14.3, its not appear.
Screenshot:
![1612197167790](https://user-images.githubusercontent.com/58428572/106489714-05f80100-64f0-11eb-8c1f-0180692b172d.jpg)

![1612197180216](https://user-images.githubusercontent.com/58428572/106489952-46f01580-64f0-11eb-85f3-2b85ea2697ea.jpg)

I try it with other version of google_maps_flutter but the border still appear. Maybe it related with this issues #61340 #59751? Can you fix this problem? or anyone have the solution for this problem?

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-ID)
    • Flutter version 1.22.5 at /Applications/development/mobile/flutterSDK/flutter
    • Framework revision 7891006299 (8 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/berkatbejana/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

 
[✓] Connected device (1 available)            
    • iPhone (mobile) • 2295cce0eb128bb1d06c2b1eee522a1de3a7c6f7 • ios • iOS 14.3

• No issues found!
</details>

**Comment by flappygod** [comment]
UiKitView shows a thin black border on iPhone11，not only google_maps_flutter，it's a bug in Rendering。

**Comment by pedromassangocode** [comment]
Hi @davidwijayanto2 
This definitely seems to be the same issue as https://github.com/flutter/flutter/issues/61340. I'm going to close this as duplicate, please follow up on that issue for more updates.
Thank you
