### ISSUE TITLE
Mitigation for windows build issue with dart-defines

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#75157]
https://github.com/flutter/flutter/pull/75027 is not usable as a cherry pick for the current windows build issue. I haven't actually verified that the verbatim change was the culprit, but reverting that is not really feasible either because 1) it will re-break users with spaces in their directory paths and 2) it will cause everyone that upgrades from dev to break.

A mitigation is to ensure that `flutter run` does not set any dart defines by default, since the `=` being escaped into a `%3D` is what caused the break. A default dart define was introduced as part of the web renderer options, and updating this code so that it is only run when the target device is web should stop a default windows template from being broken.

FYI @stuartmorgan @cbracken

**Comment by pcsosinski** [comment]
what's the "current windows build issue" ?

**Comment by jonahwilliams** [comment]
#75017 / #74705 - same issue really.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/75252 tracks the follow up work
