### ISSUE TITLE
flutter tool should notice that it's not from the same repo as the one you're in

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7515]
When you run `flutter` in a package that points to a different flutter repo than the one from which the tool is running, we output a useful message to that effect.

We should do the same when your current directory is a flutter repo that isn't the same as the tool's.

**Comment by Hixie** [comment]
We do this now.

**Comment by zanderso** [comment]
This looks like it was fixed here: https://github.com/flutter/flutter/pull/7601
