### ISSUE TITLE
Builds breaking with obscure NNBD stack trace

### ISSUE THREAD

**Issue by flar** [flutter/flutter#75168]
Recent Framework builds have been breaking and the logs show this error and stack trace in them:

```
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original error: type '() => Null' is not a subtype of type '(() => FutureOr<Map<String, dynamic>>)?' of 'onTimeout'
[platform_channel_sample_test] [STDOUT] stdout: [        ]   Original stack trace:
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #0      Future.timeout (dart:async/future_impl.dart)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #1      _warnIfSlow (package:flutter_driver/src/driver/vmservice_driver.dart:633:6)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #2      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:315:25)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #3      FlutterDriver.checkHealth (package:flutter_driver/src/driver/driver.dart:187:34)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #4      VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:232:40)
[platform_channel_sample_test] [STDOUT] stdout: [        ]   <asynchronous suspension>
[platform_channel_sample_test] [STDOUT] stdout: [        ]   #5      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
```

It would appear that an NNBD assertion is failing.

**Comment by flar** [comment]
It looks like the line at 314 in vmservice_driver.dart is asserting that the json from a `vms.Response` is non-null, but the `Response` makes no such promise.

https://github.com/flutter/flutter/blob/6bd54753d7ca9dbdda5762637fb529c7d0b6bf5a/packages/flutter_driver/lib/src/driver/vmservice_driver.dart#L314

**Comment by goderbauer** [comment]
@flar That line is not causing the error from your first message. That error is caused by this line here:

https://github.com/flutter/flutter/blob/6bd54753d7ca9dbdda5762637fb529c7d0b6bf5a/packages/flutter_driver/lib/src/driver/vmservice_driver.dart#L633

Small repro:

```dart
Future<void> main() async {
  final Future<int> a = Future<int>.delayed(const Duration(seconds: 2), () => 2);
  final Future<int?> b = foo(a);
  print(await b);
}

Future<T?> foo<T>(Future<T?> a) {
  // Runtime Error: type '() => Null' is not a subtype of type '(() => FutureOr<int>)?' of 'onTimeout'
  return a.timeout(const Duration(seconds: 1), onTimeout: () => null);
}

```

**Comment by goderbauer** [comment]
I am currently looking into fixing this.

**Comment by flar** [comment]
Yes, that `onTimeout` should return an empty map to comply. Sorry for the wild goose chase.

**Comment by goderbauer** [comment]
We have tests that should have caught this in https://github.com/flutter/flutter/blob/master/packages/flutter_driver/test/flutter_driver_test.dart. But it appears that these tests are not running on CI: https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L745. :( 

I'll enable them once they are fixed..
