### ISSUE TITLE
[google_maps_flutter] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#75165]
[ +336 ms] E/flutter ( 3678): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check
operator used on a null value
[ +439 ms] E/flutter ( 3678): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure>
(package:flutter/src/services/platform_views.dart:601:73)
[ +564 ms] E/flutter ( 3678): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
[ +519 ms] E/flutter ( 3678): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
[  +77 ms] E/flutter ( 3678): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
[ +270 ms] E/flutter ( 3678): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
[ +222 ms] E/flutter ( 3678): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
[ +257 ms] E/flutter ( 3678): #6      _AndroidMotionEventConverter.toAndroidMotionEvent
(package:flutter/src/services/platform_views.dart:602:12)
[ +277 ms] E/flutter ( 3678): #7      AndroidViewController.dispatchPointerEvent
(package:flutter/src/services/platform_views.dart:864:31)
[ +396 ms] E/flutter ( 3678): <asynchronous suspension>
[ +300 ms] E/flutter ( 3678): #8      _PlatformViewGestureRecognizer.handleEvent
(package:flutter/src/rendering/platform_view.dart:535:26)
[ +351 ms] E/flutter ( 3678): #9      PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:77:12)
[ +490 ms] E/flutter ( 3678): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[  +21 ms] E/flutter ( 3678): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[ +421 ms] E/flutter ( 3678): #12     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:120:18)
[ +756 ms] E/flutter ( 3678): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)[ +264 ms] E/flutter ( 3678): #14     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:358:19)
[  +14 ms] E/flutter ( 3678): #15     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:338:22)
[ +202 ms] E/flutter ( 3678): #16     RendererBinding.dispatchEvent
(package:flutter/src/rendering/binding.dart:267:11)
[ +535 ms] E/flutter ( 3678): #17     GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:295:7)
[ +176 ms] E/flutter ( 3678): #18     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:240:7)
[ +344 ms] E/flutter ( 3678): #19     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:213:7)
[ +286 ms] E/flutter ( 3678): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
[ +210 ms] E/flutter ( 3678): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[ +326 ms] E/flutter ( 3678): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[ +201 ms] E/flutter ( 3678): #23     _invoke1 (dart:ui/hooks.dart:265:10)
[ +167 ms] E/flutter ( 3678): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by imeDevelopers** [comment]
i can't move the map by finger

**Comment by pedromassangocode** [comment]
Hi @imeDevelopers 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
