### ISSUE TITLE
[image_picker] Migrate web to null-safety

### ISSUE THREAD

**Issue by zigapovhe** [flutter/flutter#75162]
Can't find any open pull requests or issues regarding image_picker package with null-safety support. Is it even planned for that?
Is there any null-safety roadmap for official flutter packages? Thanks.

Whenever I try to upgrade my pubspec.yaml file, I receive this error:
`Because image_picker >=0.6.3 depends on flutter_plugin_android_lifecycle ^1.0.2 and local_auth >=1.0.0-nullsafety.3 depends on flutter_plugin_android_lifecycle ^2.0.0-nullsafety, image_picker >=0.6.3 is incompatible with local_auth >=1.0.0-nullsafety.3.
So, because project_flutter depends on both local_auth ^1.1.0-nullsafety and image_picker ^0.6.7+17, version solving failed.`

**Comment by stuartmorgan** [comment]
> Is there any null-safety roadmap for official flutter packages?

There is now https://github.com/flutter/flutter/issues/75247 as an overall tracker.

**Comment by Sameerkash** [comment]
@stuartmorgan  I would like to work on this!

**Comment by stuartmorgan** [comment]
Sub-packages to migrate, in order:
- [ ] image_picker_platform_interface
- [ ] image_picker_for_web
- [ ] image_picker

**Comment by stuartmorgan** [comment]
@cyanglaz Are you doing `image_picker` as well, or is @Sameerkash? I want to make sure we don't accidentally end up with duplicated work again.

**Comment by cyanglaz** [comment]
@Sameerkash I plan to start `image_picker` migration work tomorrow (Friday 2/5 PST). Let me know if you want to do it instead :) Otherwise, I'll start tomorrow.

**Comment by Sameerkash** [comment]
@cyanglaz I've already made a pill request. If you could review it..

**Comment by Sameerkash** [comment]
@stuartmorgan  so do I just remove the integration_test  dependency and migrate?

**Comment by stuartmorgan** [comment]
> do I just remove the integration_test dependency

I checked on this; we don't need to restructure the integration tests in the packages where they are at the top level, you can just leave the `integration_test` dependency as-is, and you'll need to [opt-out the integration test file](https://dart.dev/null-safety/unsound-null-safety#migrating-incrementally) using `// @dart=2.9`.

**Comment by cyanglaz** [comment]
> Also, Deperectaed Methods have been removed from the interface. shall I remove them from the package as well?

Yes. And please also mark it as breaking change in the CHANGELOG.

**Comment by cyanglaz** [comment]
@Sameerkash Let's start with image_picker work first. I'd check with @ditman on the  `image_picker_web`.

**Comment by Sameerkash** [comment]
@cyanglaz  on it, should be up soon

**Comment by stuartmorgan** [comment]
Re-titled and re-opened to track migrating web.

**Comment by Sameerkash** [comment]
> Re-titled and re-opened to track migrating web.

Can I claim it @stuartmorgan ? 
Although I'll get it up in 2 days.

**Comment by ditman** [comment]
`image_picker` for web should be upgradable, it's still using the flutter test --platform chrome style of tests, and not flutter driver, so the migration (and tests!) should be straightforward!
