### ISSUE TITLE
flutter_gallery_win__compile failing on flutter-devicelab-windows-2 "Building with plugins requires symlink support"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75164]
Failed on unrelated PR https://github.com/flutter/flutter/pull/75161
```
Executing: C:\Users\flutter\.cocoon\flutter\bin\flutter build apk --release --target-platform=android-arm --tree-shake-icons --split-debug-info=infos/ in C:\Users\flutter\.cocoon\flutter/dev/integration_tests/flutter_gallery with environment {}
2021-02-01T11:51:41.640689: stdout: Running "flutter pub get" in flutter_gallery...                  1,264ms
2021-02-01T11:51:41.819153: stderr: Building with plugins requires symlink support.
2021-02-01T11:51:41.819153: stderr: 
stderr: Please enable Developer Mode in your system settings. Run
stderr:   start ms-settings:developers
stderr: to open settings.
```
[flutter_gallery_win__compile_6bd5475_2.log](https://github.com/flutter/flutter/files/5906437/flutter_gallery_win__compile_6bd5475_2.log)

**Comment by jmagman** [comment]
@yusufm is this related to your work bringing win2 back up? https://github.com/flutter/flutter/issues/75035#issuecomment-771070998

**Comment by yusufm** [comment]
no, my changes should not have touched this area

**Comment by yusufm** [comment]
I turned on dev mode as referenced in the error message you mentioned. Hopefully this will resolve the issue. Please let me know if its still an issue.

**Comment by jmagman** [comment]
That seemed to work, it passed on re-run.  Is there anything else to track here @yusufm (documentation, maybe?)

**Comment by yusufm** [comment]
I don't believe there is anything specific to doc here. There is higher level changes being made to the windows machines, and any specific details will be documented along with those.
