### ISSUE TITLE
[pigeon] Can't be tested on stable channel as of 1.22.6 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#75187]
Due to unrecognized version to the Dart SDK on the stable channel:

https://github.com/flutter/packages/pull/252/checks?check_run_id=1811547446

**Comment by stuartmorgan** [comment]
Closing as obsolete.

**Comment by stuartmorgan** [comment]
Turns out this wasn't obsolete:
https://github.com/flutter/packages/blob/main/packages/pigeon/run_tests.sh#L17

I assumed it had been disabled in the Cirrus config, not the script itself.
