### ISSUE TITLE
Linux emoji not in color

### ISSUE THREAD

**Issue by robert-ancell** [flutter/flutter#75188]
When using Emoji characters in a Text widget, these don't show in color, instead a blocky black and white version is used:
![Screenshot from 2021-02-02 16-27-31](https://user-images.githubusercontent.com/126560/106548270-90357900-6573-11eb-8366-e6d75b244c68.png)

In GTK applications or using a web browser (Firefox/Chromium/Chrome) these do so in color:
![Screenshot from 2021-02-02 16-32-42](https://user-images.githubusercontent.com/126560/106548689-4dc06c00-6574-11eb-958c-28794846f6bb.png)

**Comment by robert-ancell** [comment]
GTK actually switches the font family to "emoji" when encountering Emoji glyphs. The "emoji" family is configured via fontconfig to be an appropriate Emoji font (e.g. Noto). The Emoji detection and font family shifting is [done in Pango](https://gitlab.gnome.org/GNOME/pango/-/commit/fe0669798d617406b52a638fb2525b1f7527a2d6).

WebKit [does the same thing](https://trac.webkit.org/changeset/239822/webkit) of detecting Emoji and using the "emoji" font family for them. Firefox has a `font.name-list.emoji` setting which it uses as the font for Emoji, so that suggests it detects Emoji and sets the font for it. I'm not sure how Chromium/Chome is doing it.

I suspect the solution here is to make Flutter appropriately detect the Emoji characters and ensure it is using the "emoji" font. Perhaps this is done inside Skia?

**Comment by TahaTesser** [comment]
<img src="https://user-images.githubusercontent.com/48603081/106576883-a9362e00-6563-11eb-96fc-e0b6871b2f6d.png" height="200" />

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.125, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.125 at /home/taha/Code/flutter_master
    • Framework revision 11609d1114 (43 minutes ago), 2021-02-02 00:22:14 -0800
    • Engine revision bb2bbde4d0
    • Dart version 2.12.0 (build 2.12.0-279.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by rbozan** [comment]
> On PopOS 20.10, neither Linux nor web renders emoji
> 
> <img alt="" height="200" src="https://user-images.githubusercontent.com/48603081/106576883-a9362e00-6563-11eb-96fc-e0b6871b2f6d.png">
> 
> flutter doctor -v

Hi, I think this is partially fixed with https://github.com/flutter/flutter/issues/75188. For me it downloads the Noto emoji font, so it does actually render on CanvasKit and HTML renderer.

**Comment by yisibl** [comment]
So what color font formats does Flutter support?
![image](https://user-images.githubusercontent.com/2784308/109757153-2ec10280-7c24-11eb-8ad9-c7d0cb3610fa.png)

https://www.colorfonts.wtf/#w-node-85d8080e63a6-0134536f:~:text=Web%20browsers

**Comment by cbracken** [comment]
@jason-simmons for thoughts on where the code for this lies re: font-fallback.

**Comment by jason-simmons** [comment]
If the explicitly specified fonts do not cover a particular character, then the Flutter engine will call `SkFontMgr::matchFamilyStyleCharacter` to find a font that can handle the character.

The specific `SkFontMgr` implementation used by the engine depends on the target platform and the engine's build configuration.

**Comment by jason-simmons** [comment]
I can reproduce the behavior in this issue by building the engine with `--enable-fontconfig`.

The Fontconfig-based implementation of `SkFontMgr` finds the font for the emoji character here:
https://github.com/google/skia/blob/master/src/ports/SkFontMgr_fontconfig.cpp#L911

On my setup the Fontconfig query returns the "Symbola" font.  I don't know if there is a way to get Fontconfig to prioritize the "emoji" font in this scenario.

**Comment by cbracken** [comment]
Updates from @jason-simmons:

My last response on that bug has a link to the Skia font manager implementation based on FontConfig and the code there that queries for a font that can handle a given character.

I'd suggest that Canonical look there.  I don't know if there is a way to change the FontConfig request so that it will choose a better emoji font, or whether the choice is controlled by FontConfig configuration on the host system.

Another possibility might be replacing the default font manager used by the Libtxt or SkParagraph FontCollection.

The engine has a platform-specific hook that selects a default font manager.  On Linux it's using one based on FontConfig or one that just picks fonts from a filesystem directory:
https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/platform_linux.cc

Possibly they could subclass the FontConfig SkFontMgr and add some rules to their implementation of matchFamilyStyleCharacter that prioritize a particular emoji font.

**Comment by letungcntt** [comment]
any fix it?

**Comment by huycozy** [comment]
This issue is reproducible on the latest `stable` and `master` channels.

| Linux | Web |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/234846891-92dc9619-5812-453a-bac3-e848475de8fe.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/234846896-267f57a0-ab7d-4fb8-b0c8-1f38963d67e2.png">

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[!] Flutter (Channel stable, 3.7.12, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/huynq/Documents/Working/flutter
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.10.0-12.0.pre.29, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.10.0-12.0.pre.29 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60077ff979 (24 hours ago), 2023-04-23 07:09:16 -0400
    • Engine revision fcf46af2d3
    • Dart version 3.1.0 (build 3.1.0-35.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

----

But this looks very similar to https://github.com/flutter/flutter/issues/119536 and may be fixed by its PR. As mentioned at https://github.com/flutter/flutter/issues/119536#issuecomment-1513309144, try using `useColorEmoji: true` on Web and I see it can work (I checked this on master channel):

<img width="400" src="https://user-images.githubusercontent.com/104349824/234848767-fea16712-4116-4559-960f-036737ffa4b6.png">

So I will close this issue in favor of #119536. Please follow up on that issue for further updates. If you disagree, please write in the comments and I will reopen it. Thank you!
