### ISSUE TITLE
Docs for SizeChangedLayoutNotifier are unclear.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7518]
Docs for SizeChangedLayoutNotifier are unclear.  I'm not sure how I can use this widget.  In particular this statement is odd: "A widget that automatically dispatches a SizeChangedLayoutNotifier when the layout of its child changes."

What does it mean to dispatch a SizeChangedLayoutNotifier which links to this same class?

**Comment by apwilson** [comment]
Perhaps it means it dispatches a SizeChangedLayoutNotification?

**Comment by Hixie** [comment]
Please open a new bug if this is still unclear.
