### ISSUE TITLE
Unable to call a platform channel method from another isolate 

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#75197]
Unable to call a platform channel method from another isolate 
can't use platform channels on a separate isolates
how can i do it. thank you.

**Comment by iapicca** [comment]
@chongbo2013 
it's not a bug, [isolates don't share memory](https://youtu.be/vl_AaCgudcY?t=35)

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/13937
