### ISSUE TITLE
[flutter_web] some file download failed , 360 browser

### ISSUE THREAD

**Issue by chen412115** [flutter/flutter#75191]
This file downloads failed in release mode(flutter build web)
http://adzjz.ekuapi.com/chrome/index?title=enterprise_mangement_web&url=http%3A%2F%2Flocalhost%2Fenterprise%2Findex.html%23%2F

**Comment by iapicca** [comment]
@chen412115 
it seems to be the file itself rather than flutter
![image](https://user-images.githubusercontent.com/45637986/106562115-82abcf00-6532-11eb-8525-54e0e5b71c0c.png)

**Comment by pedromassangocode** [comment]
Hi @chen412115 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by wenlisu** [comment]
I have the same problem as you. How can I solve it
