### ISSUE TITLE
[webview_flutter] add consistent API for zoom controls

### ISSUE THREAD

**Issue by NickalasB** [flutter/flutter#75196]
This issue is being filed as part of PR feedback for https://github.com/flutter/plugins/pull/3325.

That PR adds the missing ability to enable pinch to zoom and on-screen zoom controls for WebViews running on Android. iOS pinch to zoom already works but there isn't currently a way to disable that functionality if a dev wanted to do so.

The available params that control pinch zoom/on-screen zoom controls on Android's [WebView](https://developer.android.com/reference/android/webkit/WebSettings#setSupportZoom(boolean)) and Apple's [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) are not one-to-one but it seems the basic functionality of enabling/disabling zoom on a WebView for both platforms should be possible.

**Comment by pedromassangocode** [comment]
> but there isn't currently a way to disable that functionality if a dev wanted to do so

Is this issue about this statement? Just to make things clear.

**Comment by NickalasB** [comment]
@pedromassango I update the name of this issue to more accurately reflect the intent, which I believe would be the ability to simply have an `enableZoom` boolean param on `WebView` that would allow enabling/disabling of zoom, regardless of platform.

**Comment by stuartmorgan** [comment]
Fixed by https://github.com/flutter/plugins/pull/3325
