### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by rahuldubey093** [flutter/flutter#75205]
Facing this issue when I am pressing back to exit the app. I believe https://github.com/flutter/flutter/issues/69884 is also about the same issue but, the error popping up while closing the app is not listed there. 

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#29127](dirty, dependencies: [HeroControllerScope], state: NavigatorState#2b5b6(tickers: tracking 1 ticker)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
MaterialApp
lib/main.dart:94
When the exception was thrown, this was the stack
#2      NavigatorState.build
package:flutter/…/widgets/navigator.dart:4041
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#5      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#6      Element.rebuild
package:flutter/…/widgets/framework.dart:4343
...

**Comment by pedromassangocode** [comment]
Hi @rahuldubey093 
Can you please provide your `flutter doctor -v`  and a minimal complete reproducible code sample?
Thank you

**Comment by rahuldubey093** [comment]
Here is the  `flutter doctor -v`:

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
    • Flutter version 1.22.4 at _[PATH REMOVED]_/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at _[PATH REMOVED]_/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • MI 5 (mobile) • 5d0bf4e • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @rahuldubey093 
I need a reproducible code sample as well.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
