### ISSUE TITLE
The method 'InkWell' isn't defined for the class 'AndroidWebView'

### ISSUE THREAD

**Issue by TheinvinciblePrints** [flutter/flutter#75202]
Error: The method 'InkWell' isn't defined for the class 'AndroidWebView'.
 - 'AndroidWebView' is from 'package:webview_flutter/src/webview_android.dart'
Try correcting the name to the name of an existing method, or defining a method named 'InkWell'.
    return InkWell()

**Comment by darshankawar** [comment]
@TheinvinciblePrints 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by TheinvinciblePrints** [comment]
I think the issue is from this package am using **webview_flutter**

**Comment by darshankawar** [comment]
@TheinvinciblePrints 
We would need a complete minimal reproducible code sample that we can run to verify the issue you reported.

**Comment by TheinvinciblePrints** [comment]
I think i found a better package to work with...so its ok, you can close this case. Thanks
