### ISSUE TITLE
A RenderObject does not have any constraints before it has been laid out.

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#75201]
I don't know why this happens

**Comment by pedromassangocode** [comment]
Hi @mulieli 
Is this causing any unexpected behavior in your code? Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by mulieli** [comment]
> 嗨@mulieli
> 这是否会在您的代码中引起任何意外行为？您能否提供您的`flutter doctor -v`代码和最少的完整可复制代码示例，以及实际结果与预期结果？
> 谢谢

I don’t know how this error is generated. It will not print the error on the console.

**Comment by mulieli** [comment]
> Hi @mulieli
> Is this causing any unexpected behavior in your code? Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you

I don’t know how this error is generated. It will not print the error on the console.

**Comment by mulieli** [comment]
> Hi @mulieli
> Is this causing any unexpected behavior in your code? Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you
![image](https://user-images.githubusercontent.com/24307960/106568814-be648a00-656e-11eb-8eb7-d781eed8450a.png)

**Comment by mulieli** [comment]
> Hi @mulieli
> Is this causing any unexpected behavior in your code? Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you

It only appears occasionally

**Comment by mulieli** [comment]
> Hi @mulieli
> Is this causing any unexpected behavior in your code? Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you
![image](https://user-images.githubusercontent.com/24307960/106578486-85321700-657a-11eb-834f-8abe9c319ed6.png)

**Comment by meritozh** [comment]
@mulieli you should provide a complete reproducible code sample. call stack is not useful in this case.

**Comment by pedromassangocode** [comment]
Hi @mulieli
Can you please provide a minimal complete reproducible code sample along with the actual vs expected results?
Thank you

**Comment by mulieli** [comment]
> Hi @mulieli
> Can you please provide a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you

I may not be able to provide a minimal implementation because I only have this problem in a formal project

**Comment by mulieli** [comment]
> @mulieli you should provide a complete reproducible code sample. call stack is not useful in this case.

I may not be able to provide a minimal implementation because I only have this problem in a formal project

**Comment by mulieli** [comment]
> Hi @mulieli
> Can you please provide a minimal complete reproducible code sample along with the actual vs expected results?
> Thank you

I don’t know why this error occurred, so I don’t know how to reproduce it

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by PavelPZ** [comment]
reproducible code sample here: https://github.com/flutter/flutter/issues/75596
