### ISSUE TITLE
Cannot install Flutter 1.22.5+ in secure network with proxy

### ISSUE THREAD

**Issue by spajker** [flutter/flutter#75210]
Hi,
looks like Flutter SDK installer which is now in version 1.22.5+ (btw cannot find any information in documentation and any details regarding feature) seems to be not respecting proxy settings. Looks like Dart SDK download works fine but fails on fonts and most likely other such resources. With web browser with proxy it downloads fine https://storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip

There is also no information there is a way and how to install as workaround those dependencies manually.

BTW when HTTP_PROXY was not set, flutter doctor -v just hangs for few hours with any log.

## Steps to Reproduce

1. Be in environment with mandatory proxy with HTTPS certificates replacement feature
2. Set HTTP_PROXY and HTTPS_PROXY variables
3. Set GRADLE_OPTS variable to use proxy and custom truststore
4. Set DART_VM_OPTIONS to use custom truststore
2. Download Flutter SDK in version 1.22.5+
3. Run "flutter doctor -v"

## Logs

<details>
<summary>Logs</summary>

```bash
F:\>flutter doctor --verbose

Checking Dart SDK version...

Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed...

Unzipping Dart SDK...

Building flutter tool...

Running pub upgrade...

VersionCheckError: Command exited with code 128: git fetch __flutter_version_check__ stable

Standard error: fatal: unable to access 'https://github.com/flutter/flutter.git/': Failed to connect to github.com port

443: Connection refused

Downloading Material fonts...                                       0,1s

Downloading Material fonts...                                       0,0s

Failed to download

https://storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip. Ensure

you have network connectivity and then try again.

 

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)

#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1486:11)

<asynchronous suspension>
```
 
</details>

**Comment by TahaTesser** [comment]
Hi @spajker 
You might need to [configure git](https://stackoverflow.com/a/18356572) for the proxy as well, can you try cloning and see if it works
Thank you

**Comment by spajker** [comment]
Hi,
I know that there is line in logs:

VersionCheckError: Command exited with code 128: git fetch __flutter_version_check__ stable

Standard error: fatal: unable to access 'https://github.com/flutter/flutter.git/': Failed to connect to github.com port

443: Connection refused

but I believe it is a separate aspect - this is as I understand to check if newer versions are available "VersionCheckError", we had that with older versions as access to github is limited but everything works fine. So this is not subject of that issue report.

The issue I raised is about lines:
```
Downloading Material fonts...                                       0,1s

Downloading Material fonts...                                       0,0s

Failed to download

https://storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip. Ensure

you have network connectivity and then try again.
```

Based on log I believe is not using git but just file over https and here even if I had HTTPS_PROXY it is ignoring it. Also as I mention Dart download part is respecting correctly.

**Comment by jmagman** [comment]
I think the `HttpClient` handles finding the proxy from the env?

**Comment by christopherfujino** [comment]
@spajker as a workaround, the newest stable release fixed an issue where not all of the artifacts were present. Here's a link to the latest windows stable release: https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_2.0.3-stable.zip

As for the dart sdk download respecting the proxy but not the rest, the dart sdk is downloaded via PowerShell on windows, while the rest of the cache uses the Dart HttpClient, as Jenn points out. The `HttpClient` is [*supposed*](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/http.dart#L1788) to respect `HTTP_PROXY`, although apparently it's not?

**Comment by AlexV525** [comment]
Closing as https://github.com/flutter/flutter/issues/75210#issuecomment-811401253, please submit a new issue with the latest situation if it still persists.
