### ISSUE TITLE
Document why you can't call setState in NotificationListener.onNotification

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7521]
It seems a logical place to call setState.

**Comment by Hixie** [comment]
Calling setState in response to a Notification indicates an incorrect data flow pattern. If you want your build to depend on your layout, use a layout builder. Otherwise you'll have the "one-frame-behind" problem.

**Comment by Hixie** [comment]
Fixed to some extent by https://github.com/flutter/flutter/pull/11330
