### ISSUE TITLE
Correction in the Week1 Codelab -Part1 Doc

### ISSUE THREAD

**Issue by ananya0504** [flutter/flutter#75215]
Doc which needs correction-
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#4

***

In the **Create boilerplate code for a stateful widget** section- 
It can go anywhere in the file outside of MyApp, but the solution places it at the bottom of the file. In lib/main.dart, position your cursor after all of the code, enter Return a couple times to start on a fresh line. In your IDE, start typing stful. The editor asks if you want to create a Stateful widget. Press Return to accept. The boilerplate code for two classes appears, and the cursor is positioned for you to enter the name of your **stateless** widget.

Correction-
It should be a **stateful** widget in the second last word.

***

In the **Creating a stateful widget** section- 
Once you've entered RandomWords as the name of the stateful widget, the IDE automatically updates the accompanying State class, naming it **_RandomWordState**. By default, the name of the State class is prefixed with an underscore. Prefixing an identifier with an underscore enforces privacy in the Dart language and is a recommended best practice for State objects.

Correction-
It should be **_RandomWordsState** there.

**Comment by darshankawar** [comment]
@ananya0504 
Codelab related issues are maintained and tracked here: https://github.com/flutter/website/issues
I already see an open issue related to `_RandomWordsState` there https://github.com/flutter/website/issues. Please follow-up in it for updates.
Closing from this repo.
