### ISSUE TITLE
Engine depends on legacy drawBitmap/Image calls that were recently removed

### ISSUE THREAD

**Issue by flar** [flutter/flutter#75214]
A recent Skia commit has removed flags that included legacy versions of these methods.

https://skia.googlesource.com/skia.git/+/5c6c3be98196b514d89e95817b763d43475a4012%5E%21/#F0

The failures can be seen in this PR which was the first to encounter the problem:

https://github.com/flutter/engine/pull/24127

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/24135
