### ISSUE TITLE
Inconsistent theming across widgets

### ISSUE THREAD

**Issue by aleripe** [flutter/flutter#75217]
Hi guys,
I have inconsistent theming across widgets.
`OutlineInputBorder ` widget uses the theme's `primaryColor ` when focused, while the `Radio` widget uses the theme's `accentColor` when selected.
This doesn't allow us to set the primaryColor for other uses.

In general, I find theming very inconsistent.

**Comment by darshankawar** [comment]
@aleripe 
Can you check out [this](https://github.com/flutter/flutter/issues/65782) issue and confirm if it resemble yours ? 
Also see the underlying comments which describes the new updates and ongoing work on themes and confirm if they resolve some of your queries and if landing of those issues would resolve your issue as well. 

https://github.com/flutter/flutter/issues/65782#issuecomment-693496339
https://github.com/flutter/flutter/issues/65782#issuecomment-693592819

**Comment by aleripe** [comment]
Not exactly the same problem, but I think it's related to all the inconsistencies in theming... I see you're already working on a theme redesign so it might solve my problem in the future.

**Comment by HansMuller** [comment]
@aleripe - you are right that the material library theme system is still inconsistent. We continue to work on improving that, as @darshankawar [pointed out](https://github.com/flutter/flutter/issues/75217#issuecomment-771623139) however, it's a slow process.  The fact that the Theme's toggleableActiveColor defaults to the (obsolete) Theme accent color is on our list of things to undo - it probably should default to the color scheme's secondary color. That will be a breaking change.

**Comment by darshankawar** [comment]
@aleripe 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the inconsistency ? We can link this with the original so that it'll be tracked properly.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
