### ISSUE TITLE
LengthLimitingTextInputFormatter not work on ios 14.4

### ISSUE THREAD

**Issue by hu70258tao** [flutter/flutter#75212]
在苹果14.4的系统下.
TextField使用了LengthLimitingTextInputFormatter的话
当使用苹果自带的输入键盘,在输入中文的时候,
点击字幕按钮,会在输入框内重复显示数次该字母.

**Comment by pedromassangocode** [comment]
Hi @hu70258tao 
Please avoid posting comments in any language other than English.

Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

[Google Translate]
嗨@ hu70258tao
请避免以英语以外的任何其他语言发布评论。

您能否提供您的Flutter Doctor -v和最少的完整可复制代码示例？
谢谢

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
