### ISSUE TITLE
[Flutter_web] canvaskit.wasm file downloads very slow

### ISSUE THREAD

**Issue by chen412115** [flutter/flutter#75219]
2.4M  takes 8.85s

**Comment by chen412115** [comment]
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm
is there any way to change other link

**Comment by peerwaya** [comment]
Is there a way to provide feedback to the user that such file needed for the app to render is loading? this way an app can show a spinner while waiting for canvaskit to download and initialize

**Comment by pedromassangocode** [comment]
Hi @chen412115 
Can you please elaborate on this issue?
Download speed may vary depending on the network you are conned in, with this in mind, how are you measuring the download speed?

Can you please provide the steps to verify that? 
Please also describe your actual vs expect results.

Thank you

**Comment by chen412115** [comment]
Is there any way to change other Mirror Address in flutter web project

**Comment by pedromassangocode** [comment]
Hi @chen412115 
Can you please provide what was asked in https://github.com/flutter/flutter/issues/75219#issuecomment-772430095?
Thank you

**Comment by steeling** [comment]
@pedromassango can we reopen this?

It took > 1s to download this, and as the page rendering is blocking on this that's not so great.

A couple ways to repeat this

1.  `curl -o /dev/null -s "https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.wasm" -w %{time_connect}:%{time_starttransfer}:%{time_total}`

2. Open a tab in chrome and open the network tab in developer tools. Then click "disable cache", and browse to your app. You should see in the list of network requests the calls being made to download the wasm files.

I'd expect the file to load in < 500 ms. Can you please allow us to change the link at which this downloads, or put such a popular library on a CDN?

**Comment by steeling** [comment]
even the ping time to unpkg.com, is atrocious at over 200ms from san francisco

**Comment by steeling** [comment]
Looks like they are hosted by cloud flare and cloudflare is having planned maintenance throughout may and june.. still I'd imagine a CDN would be doing a better job. It would be nice to allow us to provide our own version of the file in the meantime

**Comment by gururajahegde** [comment]
It is taking 10-20 seconds, tried from various location / internet service provider in India.

Can it be hosted on our flutter web server or on some better CDN?

**Comment by pedromassangocode** [comment]
> @pedromassango can we reopen this?

Hi @steeling,
This issue was closed by its author, can you please file a new issue providing the steps to reproduce?

**Comment by gururajahegde** [comment]
> > @pedromassango can we reopen this?
> 
> Hi @steeling,
> This issue was closed by its author, can you please file a new issue providing the steps to reproduce?

added #82810

**Comment by shenyan008** [comment]
4.5s
