### ISSUE TITLE
[camera] Migrate the camera plugin to nnbd

### ISSUE THREAD

**Issue by mvanbeusekom** [flutter/flutter#75228]
## Use case

The camera plugin can be migrated to nnbd since all dependencies already have a nnbd version available.

## Proposal

 This issue is meant to track the progress of migrating the camera plugin to nnbd. Steps to be taken:
 
- [x] Migrate the [camera_platform_interface] package (see PR flutter/plugins#3530);
- [x] Migrate the [camera] package;
  - Draft PR created (awaiting NNBD of camera_platform_interface to be published): flutter/plugins#3533

(`path_provider` is a blocker via `dev_dependencies`)

**Comment by AlexV525** [comment]
`camera_platform_interface` seems rolled in already, also is the `2.0.0-nullsafety` version of `path_provider` still be a blocker?

**Comment by mvanbeusekom** [comment]
Indeed I merged version `2.0.0-nullsafety` yesterday evening into `master` but it isn't published yet. I also have the null migration of the `camera` package ready but it is waiting for the `camera_platform_interface` to get published (I have just created a draf PR flutter/plugins#3533). 

The `path_provider` is not a blocker for any further migration.
