### ISSUE TITLE
Flutter Release App Not Opening After Install

### ISSUE THREAD

**Issue by BLUE-DEVIL1134** [flutter/flutter#75223]
## Steps to Reproduce

1. **`flutter doctor`**
```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.418], locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (not installed)
[✓] VS Code, 64-bit edition (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Note :- Don't Go With The Android Licenses, It Works Fine, Before It Was Working Just Fine Even With This Output Of Doctor, But After The Latest `flutter upgrade` run up, It Still works with `flutter run`, but cant see the app icon nor the open button of release app.**

2. Ok So, When i do `flutter run`, the app works fine on my device,
but when i quit the app, it dosn't shows the app icon on home screen

Also, when i did `flutter build apk --release`, it generated the apk and i installed it..
It said installed successful but the open option next to `Done` was disables and also there was no
app icon on the home page..

Tried With 7 different Phones And Still The Same Result !!

**Expected results:** 
The App Should Open After Install...

**Actual results:** 
Neither The Open Option Is Showing Nor The App Logo On The Real Device Home Screen Is Showing ..

<details>
  <summary>Files</summary>

**`android/app/build.gradle`**
```java
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.IronEye"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation platform('com.google.firebase:firebase-bom:26.3.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

**`/pubspec.yaml`**
```dart
name: IronEye
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^0.3.7
  ext_storage: ^1.0.3
  permission_handler: ^5.0.1+1
  http: ^0.12.2
  fluttertoast: ^7.1.6
  simple_auth: ^2.0.7
  simple_auth_flutter: ^2.0.7

  # FireBase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  # Url-Launchers
  url_launcher: ^5.5.2
  uni_links: ^0.4.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
```

**`android\app\src\main\AndroidManifest.xml`**
```dart
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.IronEye">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="IronEye"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that begin with YOUR_SCHEME://YOUR_HOST -->
                <data
                  android:scheme="https"
                  android:host="ironeye-9937c.firebaseapp.com" />
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
</manifest>

```

</details>

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 

1. Try running `flutter run --release --verbose` and launch / interact with the app. Do you see any exception, errors in the console ? If so, provide them in text format.
2. What devices have you tried on which it shows this issue ?
3. Provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can copy paste and run directly in our IDE that will show us the same issue you are facing.

**Comment by BLUE-DEVIL1134** [comment]
When I Run `flutter run --release --verbose`, The Outputs all regular and no exception or errors.

For The Devices , The List Goes Here ->

1. Vivo Y51L (API 22)
2. Oppo A9 (API 29)
3. RealMe (API 28)
4. Google Pixel (API 28)

And 5 - 6 More Devices As I Published It On My Telegram Channel And All Users Faced The Problem..


For The Code Part, It's [Here](https://github.com/flutter/flutter/files/5916297/lib.zip)..

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 
Please don't just provide `lib` folder, it would be good if you could provide complete project that we can run directly. If possible, upload it on github and share the repo link that we can clone and run to see the issue.

**Comment by BLUE-DEVIL1134** [comment]
The Github Repo Won't Be Possible As My Friend Are Gonna Copy Out The Code Completely..
So The File Way Is Just Perfect .. - [Complete Project](https://github.com/flutter/flutter/files/5916608/IronEye.zip)

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 
I ran your project and indeed don't see the app launcher icon on the device which is quite strange. Can you try using https://pub.dev/packages/flutter_launcher_icons/install plugin and see if it helps to show the app icon ?

Note that this isn't an endorsement of the plugin but just a try to see if using it atleast, the app launcher shows up.

**Comment by BLUE-DEVIL1134** [comment]
I Did Changed The App Icon And Build It.
Built.. Still Doesn't Shows On The Home Screen.

Again Tried This For 3 Devices With API Levels 22, 28 and 27

I Am Sure This Is The Problem With FireBase As When The App Was Without FireBase It Worked Fine 
But Now After Adding Firebase, Its All Gone..

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 
After commenting out below implementation from Manifest, I was able to see the app launcher icon:

<img width="568" alt="Screenshot 2021-02-04 at 11 32 26 AM" src="https://user-images.githubusercontent.com/67046386/106851734-cf330e00-66dc-11eb-96f8-0f5481edbba2.png">

Are you using that for deep links (dynamic links) or for passwordless signin ?
If it is for passwordless signin, check out [this](https://firebase.google.com/docs/auth/android/email-link-auth#enable_email_link_sign-in_for_your_firebase_project) link and see if your config is same as mentioned in it.

**Comment by BLUE-DEVIL1134** [comment]
I Use It For `Email + Password` Login Scheme.
The Password Less Will Make Up A Lot Of Fake Accounts So `Email + Password` Is What I Am Using..

Its Strange As I Did Whatever Its Written On The Docs Of FireBase Still Can't See The Icon..

Is There Any Other Way To Use Firebase `Email + Password` Authentication ?

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 
Check out [this](https://firebase.flutter.dev/docs/auth/usage/#emailpassword-registration--sign-in) link and see if you have correct setup to use `email + password` authentication. Looking at the link, it doesn't seem to have an entry in manifest for it.

**Comment by BLUE-DEVIL1134** [comment]
OK So I Did As You Said, 
Found Out That It Works Which Is Strange..

But When I Created My App On Firebase, 
It Said To Do So.. 

Now there is a small thing that when I made a release APK, in settings / app manager it does not shows the firebase app like as trusted links.. 

Could you please tell me what is the use of the part u said to comment out ?

**Comment by darshankawar** [comment]
@BLUE-DEVIL1134 
Can you point us to the step where it says to add the entry in the manifest ?

**Comment by BLUE-DEVIL1134** [comment]
ok,
So it seems that i did it from a post on medium and not from docs
so its my fault..

Thanks For Your Help...
Now My App Works !
