### ISSUE TITLE
Convert Dart web app to Flutter web Widget

### ISSUE THREAD

**Issue by vin-fandemand** [flutter/flutter#75221]
Is there a way to take a Dart web application code and convert it into Flutter widget? Dart web uses query selector, Html document etc to render UI. One option I found is to use HtmlElementView class in Flutter with some caveats. Other than that, is there a better way?

## Use case

Convert Dart Web App to Flutter Web App

## Proposal

Conversion tool for Dart Web App pages to Flutter Web App

**Comment by yjbanov** [comment]
`HtmlElementView` is the best way. It has some known issues that we're working on resolving, but other than that it is our recommended way to embed non-Flutter content into a Flutter app.

**Comment by AMH8790** [comment]
L
