### ISSUE TITLE
[url_launcher] on web. Url cannot be opened in IOS Safari.

### ISSUE THREAD

**Issue by Kainanchen** [flutter/flutter#75227]
I am using package url_launcher to open an external website on Android/IOS/WEB.
It works well on every platform except Safari on IOS. MacOS+Safari, IOS+Chrome, etc are perfect.
I also tried forceSafariVC, but it didn't help.

Is there a known issue for that or I should configure something else? If it cannot be solved, could anyone suggest an alternative solution? Thanks!

**Comment by devj3ns** [comment]
Hey @Kainanchen,
could you please provide a snippet of your code and your flutter and url_launcher version?

**Comment by devj3ns** [comment]
Make sure that your url starts with `http://` or `https://`. 

For example:
```
await launch('https://www.google.com');
```
instead of 
```
await launch('www.google.com');
```

**Comment by Kainanchen** [comment]
Thanks for your reply.
I tested using the example in the url_launcher demo. It just doesn't work on IOS with Safari.

`if (await canLaunch(checkoutURL)) {
          var res = await launch(
            "https://flutter.dev",
            enableJavaScript: true,
          );
          print(res);
        } else {
          throw 'Could not launch $checkoutURL';
}`

**Comment by devj3ns** [comment]
Could you please show some more code and format it properly? For example what the value of `checkoutURL` is.

Try to wrap your code with  ``` instead of ` :)

Are you using the latest version of `url_launcher`? And which Flutter version are you using?

**Comment by Kainanchen** [comment]
Sorry I am not familiar with code formatting.
I just tested with both url changed to flutter.dev
```
String checkoutURL = 'https://flutter.dev';
if (await canLaunch(checkoutURL)) {
          var res = await launch(
            checkoutURL,
            enableJavaScript: true,
          );
          print(res);
        } else {
          throw 'Could not launch $checkoutURL';
        }
```
The versions are:
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (3 months ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

url_launcher: ^5.7.10

**Comment by devj3ns** [comment]
No problem :) 

For me the code you posted above works.

Flutter 1.25.0-8.3.pre (channel beta) 
url_launcher: ^5.7.10
iOS 14.4

Is there something which get's printedin the console when you try to open the website?

Can you try to run `flutter clean`? In some cases this helps to fix some issues.

**Comment by Kainanchen** [comment]
Thank you for your test!
I am trying to start a blank flutter project with Flutter 1.24.0-10.2.pre • channel beta to see if it is related to that.
It is anyway a good news that the problem is not the from the url_launcher.

I will come back when I find something!

**Comment by Kainanchen** [comment]
Hi, I just want to confirm. Did you tested in Web? Open the web from IOS in Safari, and use url_launcher to open a new website.

**Comment by devj3ns** [comment]
No, I thought you mean if it works in an iOS App.

But now I have tested it on an iPhone and an iPad in Safari with my current web project and it works too.

**Comment by Kainanchen** [comment]
Hi, thanks for your tests again.

I am not sure what the reason is, I followed this article:
[https://levelup.gitconnected.com/flutter-hyperlinks-d2eee3fd24f](url)

He mentioned:
The above methods won’t work on Safari (iOS and macOS) if any of the openLink functions are called after waiting for an async operation to end (the call is not synchronized).

After I removed async, it finally works.

It was a bit difficult to find the problem as the same piece of code works perfect everywhere else except web on IOS in Safari. Maybe it is rare to see, hope this solution can help someone else.

**Comment by Kainanchen** [comment]
Alllll right!
I got to know the problem.

In IOS and Safari in general html, it allows to open a link in a new tab when the user click on something. For example, when user open the website, a ton of new tabs open automatically is not allowed.

Then, if I put this piece of code not related to any click event (onTap, onPressed, etc), Safari would not allow. If I put launch only inside onTap(), a new tab comes.

(I am not an expert and I haven't done comprehensive tests. Please forgive me if something wrong.)
