### ISSUE TITLE
[file_selector] Migrate to NNBD

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#75235]
This is a federated plugin, so will need the following migrated, in order:
- [x] `file_selector_platform_interface`
- [ ] `file_selector_web`
- [ ] `file_selector`

(`file_selector_web` is currently blocked by `platform_detect`—although it's not clear that's actually used—and a solution for `integration_test`).

**Comment by SirusCodes** [comment]
I would like to work on this

**Comment by SirusCodes** [comment]
Migrated file_selector_platform_interface waiting for platform_detect and integration_test to migrate

**Comment by stuartmorgan** [comment]
@SirusCodes The first step is to migrate the `_platform_interface` sub-package, which isn't blocked, so if you are interested in working on this that would be the place to begin.

`platform_detect` is in the pubspec, but I don't see any imports of it, so you should check whether it can just be removed. `integration_test` isn't going to be migrated in the near future (there are significant complications); /cc @ditman to discuss options there, since this seems to be a general issue for web plugins.

**Comment by SirusCodes** [comment]
> @SirusCodes The first step is to migrate the `_platform_interface` sub-package, which isn't blocked, so if you are interested in working on this that would be the place to begin.

I migrated will open a PR with [WIP] maybe

> `platform_detect` is in the pubspec, but I don't see any imports of it, so you should check whether it can just be removed.

Yes I can do that👍

> `integration_test` isn't going to be migrated in the near future (there are significant complications); /cc @ditman to discuss options there, since this seems to be a general issue for web plugins.

Yes...

**Comment by ditman** [comment]
Thanks for the migration!

I'm currently working in migrating `url_launcher_web` to null-safety, with the newest version of integration_test (the one coming from the SDK, not pub).

I got the tests to compile and run, but result reporting is a little bit rough. I'm not sure if this is a bug in the migrated version of the package, or the way tests are run in web. I'm submitting bugs/patches for this currently.

The next issue I haven't solved yet is the usage of Mockito. There's some extra documentation that I haven't gone through yet to make Mockito work in null-safety, but it may also need to be removed.

About platform_detect in this package, it might be a leftover from some old implementation detail. Maybe it can be removed (please, do :P)

_(Using integration_test from the SDK for web packages means that, in the near term, we won't be able to automatically run web tests in CI, only when people do changes in their local machines, but that's exactly the case now, so nothing is lost.)_

**Comment by SirusCodes** [comment]
> I'm currently working in migrating `url_launcher_web` to null-safety, with the newest version of integration_test (the one coming from the SDK, not pub).
Should I also use `integration_test` coming from SDK?
 
> The next issue I haven't solved yet is the usage of Mockito. There's some extra documentation that I haven't gone through yet to make Mockito work in null-safety, but it may also need to be removed.
I also need to go through the docs. But when I migrated `file_selector_platform_interface` all test passed without any changes to Mockito

> About platform_detect in this package, it might be a leftover from some old implementation detail. Maybe it can be removed (please, do :P)
Already did that ;)

**Comment by ditman** [comment]
Hey @SirusCodes, this is the WIP of the url_launcher_web migrated to null safety (still not landed!):

https://github.com/flutter/plugins/pull/3522

> Should I also use integration_test coming from SDK?

Yes, you must use that version; it's the one that has been migrated to null-safety and that will be able to run the `integration_test` of the package once migrated to null safety.

> I also need to go through the docs. But when I migrated file_selector_platform_interface all test passed without any changes to Mockito

(Well, maybe that package didn't use Mockito :P)

**Comment by SirusCodes** [comment]
> Hey @SirusCodes, this is the WIP of the url_launcher_web migrated to null safety (still not landed!):
> 
> [flutter/plugins#3522](https://github.com/flutter/plugins/pull/3522)

Thanks I could learn some stuff from you PR
 
> > I also need to go through the docs. But when I migrated file_selector_platform_interface all test passed without any changes to Mockito
> 
> (Well, maybe that package didn't use Mockito :P)

https://github.com/flutter/plugins/blob/bb21db859f26eb3871a555e7ae9720707be2d808/packages/file_selector/file_selector_platform_interface/test/file_selector_platform_interface_test.dart#L36

It is using it 😶

**Comment by ditman** [comment]
> It is using it 😶

Haha, ok, I just asked somebody to remove those particular tests from the `camera` plugin to drop the mockito dependency for this types of tests, here: https://github.com/flutter/plugins/pull/3497#discussion_r572394822

These tests work because we're not really doing anything with the Mock, not calling any methods or anything. Otherwise, it wouldn't work at all (See my PR above for some "functional" mocks, where we do `when` and `verify` :P)

**Comment by stuartmorgan** [comment]
Agreed, we should drop the tests of mockability given the issues with mocks.

@SirusCodes Are you actively working on `file_selector_web`? We're trying to wrap up the remaining plugins ASAP, so if you're not already working on this someone else should take it over.

**Comment by SirusCodes** [comment]
> Agreed, we should drop the tests of mockability given the issues with mocks.
> 
> @SirusCodes Are you actively working on `file_selector_web`? We're trying to wrap up the remaining plugins ASAP, so if you're not already working on this someone else should take it over.

@stuartmorgan I have migrated the plugin but I confused with the tests. Will fix that and open a PR. Can you please suggest me some written code without mocking?

**Comment by stuartmorgan** [comment]
@SirusCodes I'm not sure what your question is. I'm saying you should just remove the test that tests mockability.

**Comment by SirusCodes** [comment]
> @SirusCodes I'm not sure what your question is. I'm saying you should just remove the test that tests mockability.

Ohh...I will remove those tests.

**Comment by stuartmorgan** [comment]
What do you mean by "those tests"? The file you linked to above has a single test related to mockability.

Are there other tests involved in this?

**Comment by SirusCodes** [comment]
> What do you mean by "those tests"? The file you linked to above has a single test related to mockability.
> 
> Are there other tests involved in this?

No no, only 1 file has mocks

https://www.github.com/flutter/plugins/tree/master/packages%2Ffile_selector%2Ffile_selector_web%2Fintegration_test%2Ffile_selector_web_test.dart

Should I delete the whole file or comment the whole file because once the issues with mocks is fixed it could be used again?

**Comment by stuartmorgan** [comment]
Ah, I thought you were talking about the file you linked to earlier.

For those tests, you should just manually implement a mock (i.e., a simple class that implements that interface, and lets you set the files to return). Then the tests stay basically the same.
