### ISSUE TITLE
[in_app_purchase] Migrate to NNBD

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#75237]
This is a monolithic plugin, but has a substantial amount of code to migrate.

It also has a number of `dev_dependencies` blockers. Those will need to be evaluated and potentially restructured. (E.g., usually integration_test is part of `example` not the plugin.)

**Comment by SirusCodes** [comment]
@stuartmorgan should I wait for the migration of dependencies or add `--skip-import-check` ?

**Comment by stuartmorgan** [comment]
The dependencies will need to be migrated first, or restructured. I think this will need at least an initial look from someone who has significant familiarity with the plugin.
