### ISSUE TITLE
[url_launcher] Migrate web to NNBD and re-endorse it

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#75244]
To avoid blocking overall migration, the web implementation was unendorsed in the null-safe version of the app-facing plugin. It needs to be migrated, and then re-endorsed.

**Comment by ditman** [comment]
Currently working on this one.

**Comment by ditman** [comment]
[`url_launcher: 6.0.0-nullsafety.7`](https://pub.dev/packages/url_launcher/versions/6.0.0-nullsafety.7/changelog#600-nullsafety7) has support for web again :)
