### ISSUE TITLE
Url Launcher doesn't open url on Android 11

### ISSUE THREAD

**Issue by Zeynal7** [flutter/flutter#75245]
Hello,

Today I have update my Samsung Galaxy S10e to Android 11, and url launcher stopped working. 
I use url_launcher to open my website, and mailto, and both of them doesn't work.
Today morning before update I checked the app, and urls were working correctly, but now, after update it stopped working. canLaunch returns false. I have tried the app on Android 7 and iPhone and it is working as expected.

**Comment by Zeynal7** [comment]
found an article for solving the problem. If anyone needs it: https://medium.com/flutter-community/package-visibility-for-url-launcher-on-android-11-api-30-7c03cbce76a5

**Comment by mansurov1024** [comment]
> found an article for solving the problem. If anyone needs it: https://medium.com/flutter-community/package-visibility-for-url-launcher-on-android-11-api-30-7c03cbce76a5

Did you solve this problem it using this article? Cause It is not working for me even using this solution.
Links not opened only after uploading to the Play Store while in debug mode it is working ...

**Comment by Zeynal7** [comment]
I had to update build gradle, and now, I have problems with other packages. I will try the launcher and let you know after I can fix these errors and run the app.

**Comment by mansurov1024** [comment]
> I had to update build gradle, and now, I have problems with other packages. I will try the launcher and let you know after I can fix these errors and run the app.
> 
> Edit: @mansurov1024 The article fixed my issue regarding the urls. But opening email is still not working

Did you try to check it after uploading your app to the Google Play store?

**Comment by Zeynal7** [comment]
No, I just tried it in debug mode. I will add an update here after I upload my app to play store.

**Comment by mansurov1024** [comment]
You can also reproduce it when running the app on a real device in release mode.

I see the next error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)

**Comment by Zeynal7** [comment]
It is working for me on release mode. Maybe you should try to fix MissingPluginException separately?

**Comment by mansurov1024** [comment]
> It is working for me on release mode. Maybe you should try to fix MissingPluginException separately?

Thanks. Yes, it is a more global problem than a URL launcher plugin.
I found a temporary solution. It is described here https://stackoverflow.com/a/65872227

**Comment by datacru** [comment]
I had the same problems with Android 11 (API level 30) - everything worked well before software update (and on my test device that is running earlier version) - The following seems to have put me on the right track
https://developer.android.com/training/basics/intents/package-visibility#all-apps


I solved my problem by adding the following in the AndroidManifest.xml (although it may not be necessary.
```
<activity android:name="io.flutter.plugins.urllauncher.WebViewActivity"
           android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
           android:exported="false"/>
```
That alone did not work, and then I added to the lines just below <manifest ... package="com.example.app":
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

**Comment by thang510023** [comment]
> Tôi đã gặp vấn đề tương tự với Android 11 (API cấp 30) - mọi thứ hoạt động tốt trước khi cập nhật phần mềm (và trên thiết bị thử nghiệm của tôi đang chạy phiên bản trước đó) - Những điều sau đây dường như đã đưa tôi đi đúng hướng
> [https: // developer. android.com/training/basics/intents/package-visibility#all-apps](https://developer.android.com/training/basics/intents/package-visibility#all-apps)
> 
> Tôi đã giải quyết vấn đề của mình bằng cách thêm phần sau vào AndroidManifest.xml (mặc dù có thể không cần thiết.
> 
> ```
> <activity android:name="io.flutter.plugins.urllauncher.WebViewActivity"
>            android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
>            android:exported="false"/>
> ```
> 
> Điều đó một mình không hoạt động và sau đó tôi đã thêm vào các dòng ngay bên dưới <tệp kê khai ... package = "com.example.app":
> `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />`

Thank you, it worked fine
