### ISSUE TITLE
Please create Widget like Android RecyclerView

### ISSUE THREAD

**Issue by wonpyohong** [flutter/flutter#75256]
I know that flutter recently start creating new ReorderableList widget(https://github.com/flutter/flutter/pull/74299, https://github.com/flutter/flutter/issues/66080).
![image](https://user-images.githubusercontent.com/10491866/106645356-95281600-65cf-11eb-8e67-141eb3df5ac1.png)
However this support only list type.

Android RecyclerView is powerful.

1. types (linear, grid, staggered grid)
2. reorderable using ItemTouchHelper (+slidable)
3. animation for add/remove animation

There are many many packages because Flutter does not provide good widget(s) like Android RecyclerView.
Almost packages are buggy and not managed actively.

https://pub.dev/packages/implicitly_animated_reorderable_list
- best package if you need only linear
- reorderable (O)
- add/remove animation (O)
- buggy(e.g., reversed: true) and not managed actively

https://pub.dev/packages/reorderables
- deals with many types (list, sliver list, wrap, column, row, table)
- staggered grid (X).
- reorderable (O)
- add/remove animation (X)
- buggy and not managed actively
- I am using ReorderableWrap. If you have small Container and ReorderableWrap that have many items in the Container, reordering may almost impossible because of scroll problem.

https://pub.dev/packages/flutter_staggered_grid_view
- if someone request staggered grid to flutter github issue, all people recommend this package
- reorderable (X)
- add/remove animation (X)

https://pub.dev/packages/reorderableitemsview
- reoderable version for flutter_staggered_grid_view 
- reorderable (O)
- add/remove animation (X)
- only support StaggeredTile.count (.fit, .extent not supported)
- buggy(reorder change only content but not size) and not managed actively

Any other package you know?
Please create Widget like Android RecyclerView

**Comment by nt4f04uNd** [comment]
dup https://github.com/flutter/flutter/issues/74152

**Comment by wonpyohong** [comment]
#74152 discuss about only linear

**Comment by nt4f04uNd** [comment]
@wonpyohong ok, i just noted these points in the comment in #74152
i think this one should be closed not to split discussion about this feature over two issues

**Comment by wonpyohong** [comment]
@nt4f04uNd OK, I guess it is enough. thanks
