### ISSUE TITLE
Building a flutter app with the Java 15 and the connectivity package

### ISSUE THREAD

**Issue by JamiLu** [flutter/flutter#75267]
The build fails to an exception Execution failed for task ':connectivity:compileReleaseJavaWithJavac' when building the app with the Java version 15 and the connectivity package version 2.0.2. The problem is the Java compiler. The build operation tries to use the deprecated properties of the Java compiler which have changed after the Java 1.8 thus causing the build to fail. A workaround to this is to use Java version 1.8 with the connectivity package in order to successfully build the application. But an official fix to this would be appreciated.

**Comment by darshankawar** [comment]
@JamiLu 
I tried connectivity official [example](https://pub.dev/packages/connectivity/example) on latest stable and was able to compile and run properly without any issues.
My java version is:

<img width="571" alt="Screenshot 2021-02-03 at 1 27 08 PM" src="https://user-images.githubusercontent.com/67046386/106715775-89663f00-6623-11eb-8130-46a2c5ffed22.png">

What version are you on ? Can you provide `flutter doctor -v`, `flutter run --verbose` ? Can you also try the official example and see if you get same issue ?

**Comment by iapicca** [comment]
@darshankawar @JamiLu 
AFAIK java 15 isn't supported to my knowledge,

> [...]A workaround to this is to use Java version 1.8 with the connectivity package in order to successfully build the application. But an official fix to this would be appreciated.

this isn't a workaround, this is the correct approach

Nothing bad in "hacking around", 
but I don't believe that encountering issues doing so
qualifies the problem as flutter bug

**Comment by CarltonK** [comment]
In my case I was using Java version 15 and I migrated to version 1.8 and it works for me.
