### ISSUE TITLE
[canvaskit] browser zoom does not relayout the contents

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#75286]
Changing browser zoom level changes the device-pixel ratio of the page. The expected behavior is that Flutter lays out the page with the new device-pixel ratio for the available logical space. Instead, in CanvasKit mode we simply scale the content linearly, which is wrong.

For example, starting with this UI:

![zoom-start](https://user-images.githubusercontent.com/211513/106670255-a4707a80-6561-11eb-97bf-405b2c4da66b.png)

At 200% zoom level the UI should look like this:

![zoom-expected](https://user-images.githubusercontent.com/211513/106670281-ae927900-6561-11eb-85b1-e9adfa103f71.png)

Instead, it looks like this:

![zoom-actual](https://user-images.githubusercontent.com/211513/106670291-b4885a00-6561-11eb-9243-cefa893a114c.png)

**Comment by xu-baolin** [comment]
Hi, @yjbanov, Would you like to take a look at [this issue](https://github.com/flutter/flutter/issues/77084) which only repro on the canvas kit backend.
