### ISSUE TITLE
"Run app to dismiss dialogs" step failed in build_ios_framework_module_test

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75283]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856376694323866912/+/steps/Dismiss_dialogs/0/steps/Run_app_to_dismiss_dialogs/0/stdout
```
xcodebuild: error: missing value for key 'id' of option 'Destination'

Usage: xcodebuild [-project <projectname>] [[-target <targetname>]...|-alltargets] [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings [-json]] [<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild [-project <projectname>] -scheme <schemeName> [-destination <destinationspecifier>]... [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings [-json]] [-showdestinations] [<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild -workspace <workspacename> -scheme <schemeName> [-destination <destinationspecifier>]... [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings] [-showdestinations] [<buildsetting>=<value>]... [<buildaction>]...
       xcodebuild -version [-sdk [<sdkfullpath>|<sdkname>] [-json] [<infoitem>] ]
       xcodebuild -list [[-project <projectname>]|[-workspace <workspacename>]] [-json]
       xcodebuild -showsdks [-json]
       xcodebuild -exportArchive -archivePath <xcarchivepath> [-exportPath <destinationpath>] -exportOptionsPlist <plistpath>
       xcodebuild -exportNotarizedApp -archivePath <xcarchivepath> -exportPath <destinationpath>
       xcodebuild -exportLocalizations -localizationPath <path> -project <projectname> [-exportLanguage <targetlanguage>...[-includeScreenshots]]
       xcodebuild -importLocalizations -localizationPath <path> -project <projectname> [-mergeImport]
       xcodebuild -resolvePackageDependencies [-project <projectname>|-workspace <workspacename>] -clonedSourcePackagesDirPath <path>
       xcodebuild -create-xcframework [-help] [-framework <path>] [-library <path> [-headers <path>]] -output <path>
```
https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_ios_framework_module_test/1510

**Comment by jmagman** [comment]
\cc @godofredoc re: https://flutter.googlesource.com/recipes/+/be3176d2664ebaf18ae6f8268340c048d91ae70e

**Comment by godofredoc** [comment]
I'm confused is the name of the test incorrect and instead of ios is running on mac/android? We haven't migrated any of the mac/ios tests to prod but this test ran in a devicelab test bed.

**Comment by godofredoc** [comment]
Confirmed the test bed is a mac/android that do not contains an ios device: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-18

**Comment by godofredoc** [comment]
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=os%3AMac-10.15.7&k=os&s=id

mac-18 - 21 are picking up engine and framework tasks instead of picking up devicelab tasks only.

**Comment by godofredoc** [comment]
The fix is to hardcode an additional dimension to prevent mac with ios devices attached from picking generic mac tasks.

**Comment by jmagman** [comment]
Yeah that test doesn't need a tethered device.

**Comment by jmagman** [comment]
If they are otherwise idle it might be nice to have macs with iOS pick up generic mac tasks as long as the reverse isn't true.  Can `Run app to dismiss dialogs` detect nothing is attached and bail?
