### ISSUE TITLE
Assets are not updated because of browser cache

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#75288]
## Context

We're currently using Flutter Web and clients don't receive the updated icon font after every deploys. There's also no information on the web about refreshing browser cache for fonts and Flutter does not add a `?cache=1611921763` when querying for fonts.

### Suggestion

Assets should receive the `?cache=1611921763` parameter that `main.dart.js` receive to bypass the browser cache.

A temporary solution to avoid this problem is using `FontLoader` (https://github.com/flutter/flutter/issues/47236).

```dart
/// Fetches the latest version of `icons.ttf` by adding a unique `GET` parameter per version. The `GET` parameter is used to bypass the local cache.
Future<ByteData> fetchFont() async {
  if (PlatformUtil.isWeb) {
    final response = await http.get(Uri(path: 'assets/assets/fonts/icons.ttf', queryParameters: {'cache': appVersion.toString()}));

    if (response.statusCode == 200) return ByteData.view(response.bodyBytes.buffer);
    throw Exception('Failed to load font');
  }

  WidgetsFlutterBinding.ensureInitialized();
  return await rootBundle.load('assets/fonts/icons.ttf');
}

FontLoader('AppIcons')
  ..addFont(fetchFont())
  ..load();
```

That does seem like a massive hack. It would be acceptable for one single file, but if there's many file, it might become unbearable, and *fast*.

## Steps to Reproduce

1. Create a web app that uses a custom `.ttf` file with custom icons
2. Deploy it in production
3. Use it
4. Update icons
5. Deploy updated icons

**Expected results:** 

Updated icons should be shown

**Actual results:** 

Old icons are shown

<details>
  <summary>Logs</summary>

```log
```

```
Analyzing live_app...                                                   
No issues found! (ran in 23.6s)
```

```
[√] Flutter (Channel unknown, 1.22.4, on Microsoft Windows [Version 10.0.19042.746], locale fr-CA)
    • Flutter version 1.22.4 at C:\Users\natob\Applications\flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\natob\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\ProgramData\scoop\apps\android-studio\current\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\ProgramData\scoop\apps\android-studio\current
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 88.0.705.56

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@NatoBoram 
When you update icons -> deploy it, does manually refreshing browser cache shows the updated icons ?
Can you check out [this](https://github.com/flutter/flutter/issues/57391) issue and underlying comment https://github.com/flutter/flutter/issues/57391#issuecomment-629679155 if is answers your question ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
