### ISSUE TITLE
NoSuchMethodError major was called on null

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#75294]
https://crash.corp.google.com/browse?q=product_name%3D%22Flutter_Tools%22+AND+STRPOS%28product.Version%2C+%27dev%27%29+%3E+0+AND+product.Version%3D%27dev%2F1.26.0-17.1.pre%27+AND+stable_signature%3D%27NoSuchMethodError+at+Object.noSuchMethod+at+dart%3Acore-patch%2Fobject_patch.dart-55edb480%27

Caused by null safety analytics code. Needs a fix

**Comment by AccessibleProgrammer** [comment]
Ruh Roh
