### ISSUE TITLE
Flutter module with plugins requires "flutter build ios" in the module before being able to build for the simulator in host app

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75296]
Steps to reproduce:
1. Run `flutter pub get` in a module with plugins, like [the samples flutter_module_using_plugin](https://github.com/flutter/samples/tree/master/add_to_app/flutter_module_using_plugin).  See [README](https://github.com/flutter/samples/tree/master/add_to_app) for details.
2. Run `pod install` in the host app like [samples ios_using_plugin](https://github.com/flutter/samples/tree/master/add_to_app/ios_using_plugin).
3. Open the host app xcworkspace and build for the simulator

```
ld: warning: ignoring file flutter_module/.ios/Flutter/engine/Flutter.xcframework/ios-armv7_arm64/Flutter.framework/Flutter, missing required architecture x86_64 in file flutter_module/.ios/Flutter/engine/Flutter.xcframework/ios-armv7_arm64/Flutter.framework/Flutter (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in EspressoPlugin.o
  "_FlutterMethodNotImplemented", referenced from:
      -[EspressoPlugin handleMethodCall:result:] in EspressoPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`flutter pub get` copies a release version of the Flutter.xcframework to a known spot in the module (`.ios/engine`). 
When the host app builds, it runs a Flutter script (`xcode_backend`) that copies the correct build mode version of the framework to that spot, depending on the mode you're building the host app in (`Debug` in the case of running the simulator). However, if you have plugins in the host app they build before the script runs, you get the linker warning because it's trying to link on the release version of the framework, and the app won't build.

Probably made worse by #73072 which changed the copied framework from debug (which can fail on archiving) to release (which can fail on the simulator).
https://github.com/flutter/flutter/blob/74bd7b6f6db6433783a36f94d9e43173745187f4/packages/flutter_tools/lib/src/project.dart#L674

**Comment by jmagman** [comment]
\cc @gaaclarke

**Comment by jmagman** [comment]
I swear there was a duplicate for this but I can't find it now.

It's essentially an add-to-app version of https://github.com/flutter/flutter/issues/37850.

**Comment by pedromassangocode** [comment]
Is this somehow related to https://github.com/flutter/flutter/issues/72737 as well?

**Comment by jmagman** [comment]
@pedromassangocode not related, I'll comment on that issue though.

**Comment by jmagman** [comment]
In Xcode 12 when another pod tries to link against App.framework first, this manifests as `ld: building for iOS Simulator, but linking in dylib built for macOS, file '.ios/Flutter/App.framework/App' for architecture x86_64`.

**Comment by changleibox** [comment]
> 在 Xcode 12 中，当另一个 pod 尝试首先链接 App.framework 时，这表现为`ld: building for iOS Simulator, but linking in dylib built for macOS, file '.ios/Flutter/App.framework/App' for architecture x86_64`.

你好，我也遇到了这个问题，请问有解决办法吗

**Comment by masashi-sutou** [comment]
> In Xcode 12 when another pod tries to link against App.framework first, this manifests as `ld: building for iOS Simulator, but linking in dylib built for macOS, file '.ios/Flutter/App.framework/App' for architecture x86_64`.

- I think https://github.com/flutter/flutter/issues/48292 is related this issue.
