### ISSUE TITLE
NoSuchMethodError caused by null response from listViews

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#75292]
For example: https://crash.corp.google.com/browse?q=product_name%3D%22Flutter_Tools%22+AND+STRPOS%28product.Version%2C+%27dev%27%29+%3E+0+AND+product.Version%3D%27dev%2F1.26.0-17.1.pre%27+AND+stable_signature%3D%27NoSuchMethodError+at+Object.noSuchMethod+at+dart%3Acore-patch%2Fobject_patch.dart-7603d491%27

There are a few different instances of this error, based on where the call was made.

**Comment by jonahwilliams** [comment]
Dupe of https://github.com/flutter/flutter/issues/75292

**Comment by pcsosinski** [comment]
dupe comment self-links, please make sure the actual dupe has a CP label if necessary
