### ISSUE TITLE
Support compressed image textures

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#75302]
This would involve something like supporting (compressed) basis universal image textures and getting Skia to support cross context compressed images.  I plan to build a prototype to see how much memory this could save.

**Comment by zanderso** [comment]
Dan, would this still be a helpful thing to follow up on?

**Comment by dnfield** [comment]
I never got to the prototype and it would only help for asset images or images a customer could compress on the server. I'm not really sure how much it'd help right now.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/148443 has more details and is actionable since we own the renderer now
