### ISSUE TITLE
Rework assets-and-images.md

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#7530]
## Steps to Reproduce

See https://github.com/flutter/website/pull/352

This page needs the following additional renovations:
1. Restructure and simplify as user tasks. First section needs to address 'how do I add and use an image in my app?', without talking about rootBundle, DefaultAssetBundle, or even AssetBundle. 
   1. Show the basic, most common, default scenario up front. 
   1. Then, under "Customization" talk about the complexities of swapping out an asset bundle at run time.
1. Rewrite and restructure the headings to cue into user tasks. For example, "Adding images to an app", "Optimizing image resolution"
1. Need to add a code sample of DefaultAssetBundle.of().
1. Resolution awareness content needs updating. AssetVendor has been removed, but the way rootBundle and DefaultAssetBundle work needs to be described.
1. Resolution awareness needs to be rewritten from a task perspective, rather than 'this is how the classes are structured".

**Comment by LarkAscending** [comment]
See @Hixie 's [post on 4.](https://groups.google.com/forum/#!topic/flutter-dev/fV3f3sR68Dg)

**Comment by eseidelGoogle** [comment]
@sethladd can you determine the severity?

**Comment by eseidelGoogle** [comment]
@sethladd will find an owner and assign or punt.

**Comment by sethladd** [comment]
Love the suggestions in this issue, and looks like none of them hint that we're showing incorrect information. So, we move out to M3. But, if there's wrong info in the doc, let's see if we can address it sooner.

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/9901

**Comment by sethladd** [comment]
From a customer: "how do I use assets from another package?"

**Comment by Hixie** [comment]
@LarkAscending @filiph @Sfshaza Is this something that is on your radar for the new few months? Please update the milestone accordingly.

**Comment by Sfshaza** [comment]
This PR was merged, and szakarias updated the page. Closing, but open a new bug if further info is wrong or missing.
