### ISSUE TITLE
flutter_immediately_exit_test integration times out on Windows

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75310]
https://github.com/flutter/flutter/issues/74052 was tracking an intermittent flake and we started skipping on Windows until https://github.com/flutter/devtools/pull/2600 was merged.

But https://github.com/flutter/flutter/issues/74052#issuecomment-763981214 spotted a different symptom where it fails 100% with a timeout, and they may need to be investigated separately since the `SocketException` is theoretically already fixed.
> Is this really marked flaky? I am seeing this causing rolls to fail like here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20SDK%20Drone/174321/overview

I tried to [turn the test back on](https://github.com/flutter/flutter/pull/75300) and it is still timing out:
```
19:28 +6 -1: test\integration.shard\flutter_immediately_exit_test.dart: immediate exit flutter_tools gracefully handles quick app shutdown [E]                                                         
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
  
Failed to delete C:\b\s\w\ir\tmp\t\flutter_run_test.8c3b4d85: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\tmp\t\flutter_run_test.8c3b4d85' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856359214797468416/+/steps/run_test.dart_for_tool_integration_tests_shard_and_subshard_2_3/0/stdout

**Comment by jmagman** [comment]
In the teardown I can see the `FlutterRunTestDriver` is still running, and when I `await _flutter?.stop();` I can see it sigterm. 
```
Waiting for process to end...
Sending SIGTERM to 96462..
```

We could just add `stop` to the teardown, but shouldn't this process already be killed?  When did it start failing?  Is this even related to the Windows timeout where it can't delete the directory?
I don't have a Windows development machine to bisect on at the moment.

**Comment by jmagman** [comment]
\cc @kenzieschmoll @jonahwilliams

**Comment by jonahwilliams** [comment]
This was fixed by deleting the test
