### ISSUE TITLE
Update documentation regarding shader warm-up on Metal

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#75311]
We should update the FAQ entry "SkSL warm-up doesn’t help newer iPhones using Metal" on https://flutter.dev/docs/perf/rendering/shader now that we've determined what we're going to do on that front. (I forget if we support shader warm-up on Metal; seems like we should, but in either case we should either say that we do or that we don't and why we don't in the latter case, rather than pointing to closed bugs.)

**Comment by aliakhtar** [comment]
>  now that we've determined what we're going to do on that front

What is that?

**Comment by Hixie** [comment]
I'm not 100% sure, I was hoping that I'd find out when this got fixed. :-)

**Comment by wfinf** [comment]
newer iphones => iphone 5 :) 6,7,8,x,11,12
99% of iphones

**Comment by Hixie** [comment]
@chinmaygarde Any chance you can update the docs here either to remove the text that says it doesn't work (assuming it does work), or otherwise explaining why it doesn't (and can't) work? I see a lot of people who aren't sure what the status here is and I'm not really sure I can explain it myself.

**Comment by theniceboy** [comment]
@Hixie Can you please confirm if Skia shader warmup work with Metal? This would be really helpful. Thanks!

**Comment by Hixie** [comment]
My understanding is that some level of shader warm-up exists on Metal but it does not reduce the shader compilation time enough to matter.

**Comment by Hixie** [comment]
@chinmaygarde I tried to update the docs based on your recent comments. See https://github.com/flutter/website/pull/5351.
