### ISSUE TITLE
WebView_flutter javascript callback message is difficult to parse

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#75313]
In WebView_flutter piugin, when it  get the javascript callback message, first the message will change to the String and then in the flutter ,it is difficult to parse the string to Map  or List etc .
In the file  JavaScriptChannelHandler.m 
```
- (void)userContentController:(WKUserContentController*)userContentController
      didReceiveScriptMessage:(WKScriptMessage*)message {
NSAssert(_methodChannel != nil, @"Can't send a message to an unitialized JavaScript channel.");
NSAssert(_javaScriptChannelName != nil,
           @"Can't send a message to an unitialized JavaScript channel."); 
NSDictionary* arguments = @{
          @"channel" : _javaScriptChannelName,
          @"message" : [NSString stringWithFormat:@"%@", message.body]
        };
    }
[_methodChannel invokeMethod:@"javascriptChannelMessage" arguments:arguments];
}
```

It is better to change like this:

```
- (void)userContentController:(WKUserContentController*)userContentController
      didReceiveScriptMessage:(WKScriptMessage*)message {
  NSAssert(_methodChannel != nil, @"Can't send a message to an unitialized JavaScript channel.");
  NSAssert(_javaScriptChannelName != nil,
           @"Can't send a message to an unitialized JavaScript channel.");
    NSDictionary* arguments = nil;
    if([message.body isKindOfClass:[NSDictionary class]]){
        NSData *jsonData = [NSJSONSerialization dataWithJSONObject:message.body options:NSJSONWritingPrettyPrinted error:nil];
        NSString * str = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
        arguments = @{
          @"channel" : _javaScriptChannelName,
          @"message" : str
        };
    }else{
        arguments = @{
          @"channel" : _javaScriptChannelName,
          @"message" : [NSString stringWithFormat:@"%@", message.body]
        };
    }
  [_methodChannel invokeMethod:@"javascriptChannelMessage" arguments:arguments];
}
```

**Comment by pedromassangocode** [comment]
Hi @haohongwei 
Can you please elaborate why it is difficult to parse? Do you have any code sample that shows that difficulty? Please provide the plugin version you are using.
Thank you

**Comment by haohongwei** [comment]
version is 1.7.0 

For example：if the js in the webview post message like: 
postMessage({
"method":"scan",
"param":"scanQRCode",
"callback":"result",
});

and after the webview_flutter change it to string, it become 
"{
    callBackId = result;
    method = scan;
    params = scanQRCode;
}"

and how can  I judge the value of callBackId or method form the string.

```
JavascriptChannel javascriptChannel(BuildContext context,String channelName){
    return JavascriptChannel(
        name: channelName,
        onMessageReceived: (JavascriptMessage message) => messageHandle(context, message)
    );
  }

void messageHandle(BuildContext context,JavascriptMessage message){
    String jsmessage = message.message;
    String responseJson;
    Map<String, dynamic> jsMap;
    try{
      jsMap = json.decode(jsmessage);
      if(jsMap['method'] == 'scan'){
        scanCode().then((codeString){
          controller.future.then((webViewCOntroller) => webViewCOntroller.evaluateJavascript('showBarcodeScanCallback("$codeString")'));
        });
      }
    }catch (e){
      print('prase error');
    }
  }
```

**Comment by pedromassangocode** [comment]
Hi @haohongwei 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
