### ISSUE TITLE
Regression in FirstRecompileTime windows_chrome_dev_mode

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#75329]
https://flutter-flutter-perf2.skia.org/e/?begin=1611963981&end=1612323964&keys=X76d10fc0cc553eb4438258df9a1b8ff6&requestType=0&xbaroffset=22469.

**Comment by yjbanov** [comment]
Reducing to P3 as the regression is not severe enough to warrant a P0. I can't find anything in the code around the time the regress begins that could have caused it. Could it be an infra change? /cc @jonahwilliams

**Comment by jonahwilliams** [comment]
No idea, haven't touched this recently

**Comment by liyuqian** [comment]
The number went up since an engine roll: https://github.com/flutter/flutter/pull/75234. The engine commit flutter/engine#24125 might be the cause?

**Comment by jmagman** [comment]
Adding engine tag to look at referenced roll.

**Comment by jonahwilliams** [comment]
I don't believe this actionable any more, since we've lost the context around this change.
