### ISSUE TITLE
Error execute flutter app 

### ISSUE THREAD

**Issue by wildsrincon** [flutter/flutter#75328]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

This is the error message when you try run the app 

Oops; flutter has exited unexpectedly: "HttpException: Connection closed before full header was received.

Please help for issue
SO Linux Mint 20

When run command flutter doctor all that's good.

This log for the issue

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

HttpException: HttpException: Connection closed before full header was received, uri = http://localhost:41615/devtools/page/840F6A5CC0B14260FC46AA3738EE41E7

```
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale es_CO.UTF-8)
    • Flutter version 1.25.0-8.3.pre at /home/wildcox80/snap/flutter/common/flutter
    • Framework revision 5d36f2e7f5 (hace 3 semanas), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/wildcox80/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

**Comment by darshankawar** [comment]
@wildsrincon 
This issue seem to occur due to Flutter installation done using snap. If you directly git clone the sdk, you won't see this issue. There's an open issue in snap repo for this, please follow-up there, canonical/flutter-snap#23 to get updates.
Closing this as not an issue with Flutter.
