### ISSUE TITLE
Windows Web Engine failing in presubmit checks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#75332]
For example on https://github.com/flutter/engine/pull/24173/checks

Github is showing:

flutter-dashboard / Windows Web Engine

failed 14 seconds ago in 4s

Windows Web Engine

Empty summaryMarkdown

**Comment by yusufm** [comment]
Fix is in: https://github.com/flutter/infra/commit/54b4ebe741c85edb7d3abf5241d8ee0a88577434

**Comment by yusufm** [comment]
run is successful.

**Comment by yusufm** [comment]
https://ci.chromium.org/p/flutter/builders/try/Windows%20Web%20Engine
