### ISSUE TITLE
dynamic icon data

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [flutter/flutter#75356]
Hello,

I have an application that we get the `codePoint` of the `IconData` from an API.
We've recently updated our app to use the latest Flutter version and now we are having to set `--no-tree-shake-icons` flag when building a release version of our app.

How should I dynamically set my icon without having to use this flag? Is there a solution for this? or I will have to always use this flag?

**Comment by jonahwilliams** [comment]
There is no way to use dynamic icon data and the tree shake icons flag.

**Comment by Vitor-Bukovitz** [comment]
Will `--no-tree-shake-icons` always be available? Any suggestion to make a workaround for this?

**Comment by jonahwilliams** [comment]
Yes it will always be available. The tree shaking feature can only be used if all IconData uses compile time constants. If you are using arbitrary code points at runtime then there is no workaround.

**Comment by pedromassangocode** [comment]
Hi @Vitor-Bukovitz 
I think your question is answered by now. I'm closing this, if you disagree please write in the comments bellow.
Thank you
