### ISSUE TITLE
Tried calling: matchAsPrefix("ERROR: FormatException: Could not find an option named \"bytecode-options\".", 0)". ⣽Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'matchAsPrefix' was called on null.

### ISSUE THREAD

**Issue by MikePendo** [flutter/flutter#75357]
## Steps to Reproduce

1. Setting a local engine [local Engine](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)
2. Setting Compiling for iOS [Compiling for ios](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos)
3. Checkout to master 
4. ./flutter/tools/gn --ios --simulator --unoptimized, ./flutter/tools/gn --unoptimized, ninja -C out/ios_debug_sim_unopt
5. flutter run --local-engine=ios_debug_sim_unopt

## Logs

<details>
<summary>Logs</summary>

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IL)
    • Flutter version 1.22.6 at /Users/michaelrozenblat/Desktop/flutter
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • EAEA42C2-3B8F-48EF-B1D3-BEA68FE046A0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

```
```

```
```

</details>

Error: `Tried calling: matchAsPrefix("ERROR: FormatException: Could not find an option named \"bytecode-options\".", 0)". ⣽Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'matchAsPrefix' was called on null.`

I saw this issue: [issue](https://github.com/flutter/flutter/issues/72972) so I switched to master (didn't help).
I am also not quite sure how I suppose to debug in Xcode how do I basically link ios_debug_sim_unopt to my app in order to debug.
Tanks a lot

**Comment by jonahwilliams** [comment]
Your local engine and flutter checkout are out of sync, i.e. bytecode-options was removed as a compiler argument but your tool checkout is still passing that into the engine. I'm not sure that you checked out master correctly, as bytecode-options was removed from the code base months ago.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
