### ISSUE TITLE
Stop uploading artifacts to old bucket once flutter tool moves to stable

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75363]
We are changing the bucket where we store flutter artifacts and temporarily we will upload the artifacts to the old and new locations until the flutter tool including the change to the new bucket releases to stable.

**Comment by godofredoc** [comment]
\cc @christopherfujino @pcsosinski

**Comment by christopherfujino** [comment]
Specifically once https://github.com/flutter/flutter/pull/70673 lands on stable, we will no longer need to support the `flutter_infra` bucket.

**Comment by xster** [comment]
@chenglu could you point the mirror upstream address from https://storage.googleapis.com/flutter_infra/flutter to https://storage.googleapis.com/flutter_infra_release/flutter (see exact changes in https://github.com/flutter/flutter/pull/70673) starting from now? We've changed our cloud storage hosting location. The old https://storage.googleapis.com/flutter_infra/flutter location will no longer receive updates soon. The new location should have all the existing binaries and the new ones going forward. 

The mirror can still be hosted at the same location (no need to create 2 to mirror the 2 upstream locations). Could you tweak your cloning script? Thanks!

**Comment by chenglu** [comment]
Hi Xiao @xster, I've awared this change while sync the English docs to flutter.cn, let me start working on this and heads up with the folks who maintain the Tsinghua and SJTUG mirrors, too, thanks! 
cc/ @z4yx @skyzh

**Comment by xster** [comment]
😃 thanks!

**Comment by skyzh** [comment]
Thanks! We SJTUG have updated the infra configuration, and will deploy this change in a day or two.

**Comment by chenglu** [comment]
Hi Alex @skyzh , we did not move all flutter_infra resources to flutter_infra_releases, only the SDK binaries, so I think you might be add a new "sub folder" like https://mirrors.sjtug.sjtu.edu.cn/flutter_infra_release to host the SDK files.
@xster correct me if I'm wrong...

**Comment by chenglu** [comment]
Got you, thanks to Alex @skyzh and @godofredoc !

**Comment by z4yx** [comment]
TUNA has adopted this change.

**Comment by godofredoc** [comment]
@christopherfujino can we now remove saving to the old bucket?

**Comment by christopherfujino** [comment]
> @christopherfujino can we now remove saving to the old bucket?

Nope, we'll have to wait until the next stable release https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/cache.dart#L836
