### ISSUE TITLE
Engine::HandleAssetPlatformMessage should do its work on a background thread

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7536]
Currently we handle asset requests on the main thread, which can block the main thread.  Instead, we should farm the request off to the IO thread.

**Comment by jtrunick** [comment]
+1

**Comment by Hixie** [comment]
Moving to m4 since this doesn't fit our current priority list.

**Comment by eseidelGoogle** [comment]
@cbracken may find this is needed in his investigations of our missed frame benchmarks.  But yes, I agree, unless we have a problem for which we believe this would be a solution, no need to implement this. :)

**Comment by Hixie** [comment]
cc @chinmaygarde In all the various refactors do you know if we ever resolved this?

**Comment by chinmaygarde** [comment]
We no longer read and copy assets into separate buffers. Instead, large asset buffers are mmap-ed with zero copy availability to the Dart isolate. In this scheme, asset resolution and transfer are unlikely to be bottlenecks on the platform thread.
