### ISSUE TITLE
`flutter create .` fails in Flutter channel beta when using flavors

### ISSUE THREAD

**Issue by MaruQuarky** [flutter/flutter#75368]
##Summary:

Per the following issues filed in GitHub:
- https://github.com/flutter/flutter/issues/72329
- https://github.com/flutter/flutter/issues/66486
- https://github.com/flutter/flutter/issues/59388

I've tried to test the simple app taken from the [example](https://cogitas.net/creating-flavors-of-a-flutter-app/) presented in the [Flutter documentation](https://flutter.dev/docs/deployment/flavors).

## Steps to Reproduce

1. Make sure the Flutter channel is in beta to enable web.
2. Run the command `flutter create .` in a terminal from the root project directory of the project. Per documentation, [Add web support to an existing app](https://flutter.dev/docs/get-started/web#add-web-support-to-an-existing-app).
3. Run the command `flutter create --platforms web` in a terminal from the root project directory of the project.
4. Switch to Flutter channel dev to test if the same behavior.

**Expected results:** 
Running the command `flutter create --platforms web` should create the web files in Flutter channel beta.

**Actual results:** 
After running the command `flutter create .` in the beta channel
```
user-macbookpro2% flutter create .
Recreating project ....
Running "flutter pub get" in sample_flavorapp...                   731ms
Wrote 3 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.
```
It work and it seems 3 files was written but not specified in the logs.

Running the command `flutter create --platforms web .`
```
user-macbookpro2% flutter create --platforms web .
Recreating project ....
Running "flutter pub get" in sample_flavorapp...                   697ms
Wrote 0 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.
```
And still the web files was not created.

I've tried to switch to the Flutter channel dev to check what is the behavior. Upon switching, the web files was suddenly created.

```
user-macbookpro2% flutter channel
Flutter channels:
  master
  dev
* beta
  stable
user-macbookpro2% flutter channel dev
Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:    d01d57323f..7711c1ef8f  master     -> origin/master
git: Switched to branch 'dev'
git: Your branch is up to date with 'origin/dev'.
Successfully switched to flutter channel 'dev'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
user-macbookpro2% flutter create .                
Downloading Dart SDK from Flutter engine 5d3477eab415fbcc3d58624b07f0a768f8208f98...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  194M  100  194M    0     0   946k      0  0:03:30  0:03:30 --:--:-- 1221k
Building flutter tool...
Info: Compiling without sound null safety
Downloading package sky_engine...                                1,905ms
Downloading flutter_patched_sdk tools...                           13.6s
Downloading flutter_patched_sdk_product tools...                   18.3s
Downloading darwin-x64 tools...                                    34.4s
Downloading darwin-x64/font-subset tools...                         5.1s
Recreating project ....
  web/favicon.png (created)
  web/index.html (created)
  web/manifest.json (created)
  web/icons/Icon-192.png (created)
  web/icons/Icon-512.png (created)
  lib/main.dart (created)
  .idea/runConfigurations/main_dart.xml (created)
Running "flutter pub get" in sample_flavorapp...                 2,693ms
Wrote 10 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

To enable null safety, type:

  $ cd .
  $ dart migrate --apply-changes

Your application code is in ./lib/main.dart.
```
<details>
  <summary>Logs</summary>

```
user-macbookpro2% flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.25.0-8.1.pre at /Users/user/Developer/flutter
    • Framework revision 8f89f6505b (7 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

```
</details>

**Comment by pedromassangocode** [comment]
> I've tried to test the simple app taken from the [example](https://cogitas.net/creating-flavors-of-a-flutter-app/) presented in the [Flutter documentation](https://flutter.dev/docs/deployment/flavors).

Hi @MaruQuarky 
Can you please provide that sample project?
Thank you

**Comment by MaruQuarky** [comment]
Hi @pedromassangocode,

There is a [newly released version on Flutter beta channel](https://flutter.dev/docs/development/tools/sdk/releases). I'm thinking to try the said project using the latest version and will update this post once done testing it.

Thanks.

**Comment by rohan20** [comment]
As per [this comment](https://github.com/flutter/flutter/issues/59388#issuecomment-644202660), it seems that flavors on web are not supported. Any plans of supporting them soon?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
