### ISSUE TITLE
Flutter doctor fail ( access denied)

### ISSUE THREAD

**Issue by RichardChua** [flutter/flutter#75369]
## Steps to Reproduce

1. git clone https://github.com/flutter/flutter.git -b stable
2. add the environment variable
3. flutter doctor
![Capture1](https://user-images.githubusercontent.com/3457075/106824723-5f158f80-66be-11eb-835c-f8cf452616a6.JPG)

It cannot run pub upgrade and cannot building flutter tool.

**Comment by RichardChua** [comment]
Any one can help me? i try 5 hour already. Thanks

**Comment by darshankawar** [comment]
@RichardChua 
Can you the other way (by downloading the zip) and follow steps to see if it works ? https://flutter.dev/docs/get-started/install/macos#get-sdk

**Comment by RichardChua** [comment]
on Windows. i try already. must download old version of flutter. Thanks

**Comment by darshankawar** [comment]
@RichardChua 
Does that mean you don't see the issue anymore ? Can this be closed ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
