### ISSUE TITLE
flutter_tools appears to bail out silently if devtools fails to activate

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#75376]
See https://github.com/flutter/flutter/blob/3490ae82d1be88668ebb16bc84db971dc49eb30b/packages/flutter_tools/lib/src/devtools_launcher.dart#L75-L77

We are probably in a good position here to print a meaningful error message, like "check your internet connection" or "check the output of pub global activate devtools -v" or something like that) here, rather than just silently bailing.

**Comment by jonahwilliams** [comment]
Is this sort of user message actionable? We should definitely add a trace log for our own sanity

**Comment by dnfield** [comment]
If we or pub can tell them they can't reach the server for example it might be.  They may have to connect to the internet or tell pub to use the Chinese mirror or something.

**Comment by Hixie** [comment]
I'll see what can be done when fixing https://github.com/flutter/flutter/issues/75366

**Comment by jonahwilliams** [comment]
The situation I'm concerned about is if a user is in a situation where they can't reach pub and know it, then I'd like to avoid spamming with an error every time they run.

**Comment by dnfield** [comment]
If a user routinely can't reach pub won't they have other problems?

Is this something where we'd be able to detect an --offline flag?

**Comment by jonahwilliams** [comment]
Once a users dependencies are resolved they do not need ongoing access to pub. I don't believe the offline flag is wired up to this right now (a http HEAD request is used), but we should definitely add that

**Comment by Hixie** [comment]
It turns out we're already reporting why we failed if we fail to update DevTools, so there's nothing to add here.
When we're offline we don't bother doing any of this. We determine if we're offline by doing a HEAD request on pub's server before all of this.
