### ISSUE TITLE
ElevatedButton needs dartpad demo on official docs

### ISSUE THREAD

**Issue by rafekun** [flutter/flutter#75385]
## Use case
ElevatedButton documentation doesn't have dartpad demo though RaisedButton had it.
Demo will be helpful for new devs to understand the widget.

## Proposal
I'm thinking to adding dartpad demo like [RaisedButton](https://api.flutter.dev/flutter/material/RaisedButton-class.html).
But, where should I put demo codes?

**Comment by pedromassangocode** [comment]
Hi @rafekun 
You should add it in this line https://github.com/flutter/flutter/blob/e96ce0ecb4b3fff994df5acbc3ec8b53a9764280/packages/flutter/lib/src/material/elevated_button.dart#L49

See this as example:

https://github.com/flutter/flutter/blob/e96ce0ecb4b3fff994df5acbc3ec8b53a9764280/packages/flutter/lib/src/material/icon_button.dart#L43-L73

**Comment by rafekun** [comment]
@pedromassangocode Thank you for your advice!
Ok, I will do it ASAP!

**Comment by rafekun** [comment]
I think I will create PR next week

**Comment by rafekun** [comment]
@pedromassangocode Which branch should I fork? master?

**Comment by rafekun** [comment]
stable branch, right?
https://medium.com/flutter-community/contributing-to-flutter-getting-started-a0db68cbcd5b

**Comment by pedromassangocode** [comment]
> @pedromassangocode Which branch should I fork? master?

You probably should fork the whole repository and create a new branch from master.

**Comment by Abhishek01039** [comment]
cc @HansMuller
