### ISSUE TITLE
What happened to "doctor"?

### ISSUE THREAD

**Issue by willvsimple** [flutter/flutter#75381]
I have read the documentation.

OS :          Microsoft Windows 10 professional
OS version:   10.0.19041 Build 19041

I have installed: 7zip ,git VSCode .

Problems encountered: 
flutter doctor

logs:
--------------------------------------------------------------------------------------------------------
flutter doctor 
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed... 
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...

-----------------------------------------------------------------------------------------------------------
15 hours later...... 
nothing had happened.

Is this "doctor" also a Time Lord ? Does it freeze time?

**Comment by willvsimple** [comment]
The reason is that flutter.dev cannot be accessed .

**Comment by victorleshe** [comment]
experiencing same issue... Does anyone has a way around it?...
