### ISSUE TITLE
Image.network() content-length default 0 , image service returns 403

### ISSUE THREAD

**Issue by zylz10** [flutter/flutter#75384]
## Steps to Reproduce

ENV
Flutter 1.22.6 • channel stable
Framework • revision 9b2d32b605 (12 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

Image.network(url)

When content length = 0, the image service returns 403

Temporary solutions
_network_image_io.dart
line 93
 headers?.forEach((String name, String value) {
        request.headers.add(name, value);
 });
add
if(request.headers.contentLength == 0){
      request.headers.remove("content-length", "0");
 }
**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @zylz10 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by zylz10** [comment]
> Hi @zylz10
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

**Comment by zylz10** [comment]
Image.network() 

> Hi @zylz10
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you



> Hi @zylz10
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Image.network()

**Comment by zylz10** [comment]
> Hi @zylz10
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Image.network(url)

**Comment by pedromassangocode** [comment]
> Image.network(url)

Hi @zylz10
This is not a reproducible code sample. See [here](https://stackoverflow.com/help/minimal-reproducible-example) how to create a minimal reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
