### ISSUE TITLE
How do I build my app for x86 to run on appetize.io (and other services)?

### ISSUE THREAD

**Issue by aleki** [flutter/flutter#7539]
Currently when I try run my application on the appetize.io I get this error:
> APK has native code but does not have x86 architecture. Switching device type to physical Nexus 5, aka "hammerhead". Please try again.

**Comment by eseidelGoogle** [comment]
This may get easier as part of the hello_services refactor underway, FYI @mit-mit.

However we also probably need to publish some additional artifacts, as noted in https://github.com/flutter/flutter/issues/2898.

**Comment by eseidelGoogle** [comment]
`flutter build apk --target-arch x86` should work today?

**Comment by mit-mit** [comment]
@jakobr-google will your build changes resolve this?

**Comment by jakobr-google** [comment]
Yep, after the change we'll produce either a universal APK, or APKs split on ABI, and we should support x86 profile/release builds as well.

@aleki If your app is not gradle-based (hello_services example), then you can get a x86 debug APK using `flutter build apk --debug --target-arch=x86`. I've verified that this does run in appetize.io, but it's slightly slower than a release APK due to running in debug mode.

**Comment by aleki** [comment]
@jakobr-google My app is gradle-based :pensive:

**Comment by jakobr-google** [comment]
Then hang tight. I'm working on fixing this right now.

**Comment by jakobr-google** [comment]
Just to clarify: With the PR I just merged, we now include both x86 and ARM native code in debug builds of the hello_services example. Profile and release builds still only contain ARM code.

**Comment by mit-mit** [comment]
Validated that this works:

Create and build app
```
flutter create testapp
cd testapp
flutter build apk --debug
```

Then upload `/android/app/build/outputs/apk/app-debug.apk' to https://appetize.io and run it on a Nexus 5 (virtual, not physical)

**Comment by AppleEducate** [comment]
@mit-mit That worked for me thank you!

**Comment by carly1987** [comment]
run:  "flutter build apk --release --target-arch=arm64-v8a"
return: Could not find an option named "target-arch".

**Comment by zoechi** [comment]
@carly1987 
```
 $ flutter build apk -h
Build an Android APK file from your app.

...

    --target-platform         [android-arm (default), android-arm64]

Run "flutter help" to see global options.
```
