### ISSUE TITLE
Document how to load icon font in golden testing

### ISSUE THREAD

**Issue by tomokitakahashi** [flutter/flutter#75391]
## Use case

I'm trying flutter golden test.
But it doesn't support fonts.

I can load fonts like  https://github.com/flutter/flutter/issues/17700 for character fonts, but for icons, .ttf and .otf suitable for flutter's material icon are not published.

## Proposal

Please provide a way to manually load the icon.

**Comment by pedromassangocode** [comment]
> but for icons, .ttf and .otf suitable for flutter's material icon are not published.

Hi @tomokitakahashi 
What do you mean by "are not published"?

**Comment by tomokitakahashi** [comment]
Hi @pedromassangocode 

Thank you for your quick reply.

Looking at [this](https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons), the file is not shared with us and there is no way to get it.

**Comment by pedromassangocode** [comment]
> Looking at [this](https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons), the file(MatetrialIcon.ttf or .otf) is not shared with us and there is no way to get it.

I can't see how this is related to you proposal

**Comment by tomokitakahashi** [comment]
@pedromassangocode 

If I can get the file, I can load it on my golden test using `FontLoader` and the icon is also displayed correctly.

**Comment by Piinks** [comment]
I think this can be done, here is a recent change that I think did what you are mentioning above: https://github.com/flutter/flutter/pull/74131/files

**Comment by tomokitakahashi** [comment]
@Piinks 
Thanks !
When will this feature be released to stable?

**Comment by Piinks** [comment]
> @Piinks
> Thanks !
> When will this feature be released to stable?

Hey @tomokitakahashi I don't think it's a new feature, that's just a test that is loading material icons. I think you could do it now on stable if you tried to write a similar test. Look at the `_loadIconFont` method. That may be what you are looking for. :)

**Comment by tomokitakahashi** [comment]
@Piinks 
I tried running `_loadIconFont` and it worked on stable !
Thanks for your help :)

**Comment by pedromassangocode** [comment]
Adding docs label to mention in the docs how to do that on golden tests.

**Comment by joshykautz** [comment]
This was really helpful, now I'm able to easily add material icons to my golden tests. Thank you! 🥇

**Comment by orevial** [comment]
Agreed, this is an important thing to document for anyone trying to do golden tests with appropriate icons. I just searched for an hour after Flutter 2.2 broke my golden tests 

The first thing that I did not understand is that Flutter does not use [default `MaterialIcons` font](https://github.com/google/material-design-icons/tree/master/font) but instead uses a custom font generated specifically for Flutter that is indeed not published anywhere.

As I was struggling to find the appropriate MaterialIcons that Flutter was using I came across [this Flutter issue](https://github.com/flutter/flutter/issues/75633) that actually gave a pointer to the generated Flutter font for MaterialIcons:

`/path/to/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf`

There it was !

I then copied this font to my `test/assets` folder and use Flutter `FontLoader` class to load this `MaterialIcons` as we would for any font, something along these lines:

```dart
final materialIconsFontLoader = FontLoader('MaterialIcons')
    ..addFont(File('assets/fonts/MaterialIcons-Regular.otf')
        .readAsBytes()
        .then((bytes) => ByteData.view(Uint8List.fromList(bytes).buffer)));
  await materialIconsFontLoader.load();
```

where the font is located in my project `test` folder under an `assets` subfolder.

Hope this helps anyone struggling with the same issue, I think this should really be documented in some way, let me know if you need a PR or help to update the doc in that regard.

**Comment by edwardaux** [comment]
FWIW, I bumped into this today. The approach suggested by @orevial works well for Material Icons 🎉 

However, `CupertinoIcons` has a small subtlety that took me a while to figure out. You would think that the font name should be `CupertinoIcons`, but there's a little bit of black magic that goes on where we need to factor in the Cupertino package name.

So, using @orevial's code as a base, this is what you need to get `CupertinoIcons` to work:
```
final cupertinoIconsFontLoader = FontLoader('packages/cupertino_icons/CupertinoIcons')
    ..addFont(File('assets/fonts/CupertinoIcons.ttf')
        .readAsBytes()
        .then((bytes) => ByteData.view(Uint8List.fromList(bytes).buffer)));
  await cupertinoIconsFontLoader.load();
```

**Comment by Piinks** [comment]
This now documented in https://api.flutter.dev/flutter/flutter_test/matchesGoldenFile.html
Closing as resolved.

**Comment by pedromassango** [comment]
@Piinks I am still getting squares instead of text, do I need still to manually include material fonts file myself?
