### ISSUE TITLE
Flutter Error while running main.dart

### ISSUE THREAD

**Issue by parthraj1001** [flutter/flutter#75390]
Error running 'main.dart': java.io.EOFException
I'm getting this error when I try to run a Flutter project on Android Studio.
Please help!

**Comment by thisisamank** [comment]
this issue is already being solved here: https://github.com/flutter/flutter-intellij/issues/2713

**Comment by darshankawar** [comment]
@parthraj1001 
Provide `flutter doctor -v` and `flutter run --verbose` to properly address your issue.

**Comment by parthraj1001** [comment]
> @parthraj1001
> Provide `flutter doctor -v` and `flutter run --verbose` to properly address your issue.

![Screenshot (43)](https://user-images.githubusercontent.com/70284371/106870268-e979e580-66f6-11eb-9e58-33b7dc0c3861.png)
This is what I got when I run flutter doctor -v 
I've been working with flutter for the past year without any problems
What should I do now?

**Comment by darshankawar** [comment]
@parthraj1001 
Avoid providing the details in a screenshot. Also your `flutter run --verbose` is incomplete. Provide the entire log in properly formatted text.
