### ISSUE TITLE
assembleAndroidTest gradle task fails because integration_test plugin doesn't support Java 8 compile options

### ISSUE THREAD

**Issue by jitinsharma** [flutter/flutter#75396]
I'm using integration_test plugin and following the guide written here: https://pub.dev/packages/integration_test

When running `./gradlew assembleAndroidTest` I'm facing this issue

```
Execution failed for task ':integration_test:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':integration_test:debugAndroidTestRuntimeClasspath'.
   > Failed to transform flutter_embedding_debug-1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4.jar (io.flutter:flutter_embedding_debug:1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/jitinsharma/.gradle/caches/transforms-2/files-2.1/398c39fe9aa57fbbe65b5ae87391f9fc/jetified-flutter_embedding_debug-1.0.0-ae90085a8437c0ae94d6b5ad2741739ebc742cb4.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 24 or above.
```

I was able to isolate and solve problem by adding following lines of code in `build.gradle` of `integration_test`
```
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
```

But this solves the problem locally and it still fails on CI.
This can be solved by adding `compileOptions` to [build.gradle](https://github.com/flutter/plugins/blob/42d5325a93ffc80179ab770febcdd79243c3ff87/packages/integration_test/android/build.gradle) of `integration_test` plugin.

I also noticed following
- `integration_test` uses AGP 3.6.3 whereas latest stable is 4.1.x
- It also uses older versions of `runner`, `rules` and `espresso-core`. If these dependencies have different version in target project, the compilation itself fails(same is not true for AGP version though).
Are there any plans to update these versions?

**Comment by pedromassangocode** [comment]
Hi @jitinsharma 
Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample and the steps to reproduce the issue?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
