### ISSUE TITLE
[device_info] Provide toMap functions

### ISSUE THREAD

**Issue by vHanda** [flutter/flutter#75406]
It would be nice if`AndroidDeviceInfo` and `IosDeviceInfo` have a public `toMap` function, as this helps a lot with debugging / serialization. The implementation of `toMap` is already provided in the [example](https://github.com/flutter/plugins/blob/master/packages/device_info/device_info/example/lib/main.dart#L60). I'm duplicating this in many projects.

I'll be happy to make a pull request and implement this.

There is a similar [issue](https://github.com/flutter/flutter/issues/54430) which could also be fixed by this.

**Comment by tmthecoder** [comment]
I'd like to work on this, I can write up a PR on the device_info_plus plugin to add a toMap functionality

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
