### ISSUE TITLE
PlatformMessages docs are sparse

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7540]
https://docs.flutter.io/flutter/services/PlatformMessages-class.html

They should probably at least link to flutter.io https://flutter.io/platform-services/ or hello_services?  And could explain better what they're used for (or where to find docs which explain that).

@abarth @LarkAscending

**Comment by Hixie** [comment]
I did a pass over these docs the other day, including adding a link as suggested above. Please file new bugs with more specific questions you'd like answered in the docs if it's still too sparse.
