### ISSUE TITLE
universal link not working with some links in ios

### ISSUE THREAD

**Issue by mohammad-alshelleh** [flutter/flutter#75402]
i am using universal link in flutter , added AASA file in web site and all is correct , and added associated domain like this in Runner.entitlement and RunnerDebug.entitlement :

```
<plist version="1.0">
<array>
	<string>applinks:www.example.com</string>
	<string>webcredentials:example.com</string>
	<string>activitycontinuation:example.com</string>
</array>
</plist>
```

when i click in link like this : https://www.example.com is open in application , but when i click in link like this : https://www.example.com/product not open in app and open in safari .

json file like this :

```
{
	"activitycontinuation": {
		"apps": ["7DTHDKd89.com.example"]
	},
	"applinks": {
		"apps": [],
		"details": [{
			"appID": "7DTHDKd89.com.example",
			"paths": [" * ", "/"]
		}]
	}
}
```

how can i solve it , or any thing i worked wrong

**Comment by darshankawar** [comment]
@mohammad-alshelleh 
Your question is better suited for StackOver flow. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
You may also checkout [this](https://appvesto.medium.com/flutter-deep-links-ios-universal-links-and-android-app-links-8207eea694fb) article to know more about universal links and see if you are missing any config. 

Closing, as this isn't an issue in the framework but more of a implementation issue. If you disagree, please write in the comments and I will reopen it.
