### ISSUE TITLE
[VERBOSE-3:dart_vm.cc(409)] Error while initializing the Dart VM: Wrong full snapshot version, expected '20e5c4f7dc44368ac5a17643b93665f6' found '68cf77b6d1fc9b557802c26dd144297f'

### ISSUE THREAD

**Issue by ZQDXY** [flutter/flutter#75408]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by preetshah21699** [comment]
Greetings, @ZQDXY your issue is not very well described. Please add more details based on the given template. Thank you.

**Comment by ZQDXY** [comment]
My problem is mixed development. When I run projects in IOS release mode, I report errors directly. Console printing is the only way. However, I can't solve it by cleaning the cache or replacing the SDK

**Comment by preetshah21699** [comment]
I think you need to reinstall flutter on your device.

**Comment by ZQDXY** [comment]
I've reloaded it many times, and it's still the same problem

**Comment by preetshah21699** [comment]
Could you please share "What exactly do you do that gives you this error?"

**Comment by ZQDXY** [comment]
Now the situation is that I can't find out how this error occurred, and it can work normally in debug mode.

**Comment by preetshah21699** [comment]
Give us the device info, the steps that you followed, any commands that you might be running. It would be very much helpful.

**Comment by darshankawar** [comment]
@ZQDXY 
Try the solutions listed below and see if they work for you:

https://github.com/flutter/flutter/issues/33007#issuecomment-493779932

https://github.com/flutter/flutter/issues/30904#issuecomment-482254892

https://github.com/flutter/flutter/issues/16103#issuecomment-481832580

https://github.com/flutter/flutter/issues/16103#issuecomment-498205907

**Comment by ZQDXY** [comment]
@darshankawar I've tried all these operations, but there are still problems

**Comment by darshankawar** [comment]
@ZQDXY 
Can you provide `flutter doctor -v` ? When do you get this error ?

**Comment by ZQDXY** [comment]
MACdeiMac:iOS_NJF mac$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/mac/development/flutter
    • Framework revision 0b8abb4724 (12 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ZQD • 4a677b37ac5a1b1cfaa15acb65f9b43ab74e212b • ios • iOS 14.3

**Comment by ZQDXY** [comment]
It's always like this

**Comment by darshankawar** [comment]
@ZQDXY 
You are on an obsolete version of Flutter (Channel stable, v1.12.13+hotfix.8,). Current stable version is 1.22.6. I recommend you to upgrade to latest version and try again to see if it works.

**Comment by ZQDXY** [comment]
@darshankawar 

I encountered this problem after upgrading
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E287 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/mac/development/flutter
    • Framework revision 9b2d32b605 (13 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins


Ld /Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Intermediates.noindex/Pods.build/Release-iphoneos/AFNetworking.build/Objects-normal/arm64/AFNetworking normal arm64
    cd /Users/mac/Desktop/iOS_NJF/Pods
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Products/Release-iphoneos/AFNetworking -F/Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Products/Release-iphoneos/AFNetworking -filelist /Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Intermediates.noindex/Pods.build/Release-iphoneos/AFNetworking.build/Objects-normal/arm64/AFNetworking.LinkFileList -install_name @rpath/AFNetworking.framework/AFNetworking -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Intermediates.noindex/Pods.build/Release-iphoneos/AFNetworking.build/Objects-normal/arm64/AFNetworking_lto.o -fobjc-arc -fobjc-link-runtime -framework Flutter -framework CoreGraphics -framework Foundation -framework MobileCoreServices -framework Security -framework SystemConfiguration -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Intermediates.noindex/Pods.build/Release-iphoneos/AFNetworking.build/Objects-normal/arm64/AFNetworking_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/Nongjuanfeng-bdqgnecubcvgoldcxehcykmavwos/Build/Intermediates.noindex/Pods.build/Release-iphoneos/AFNetworking.build/Objects-normal/arm64/AFNetworking

ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by darshankawar** [comment]
@ZQDXY 
Try [this](https://stackoverflow.com/a/62830644) solution and see if it works.

**Comment by ZQDXY** [comment]
@darshankawar 
I have changed the integration mode, but how can I import more frameworks into my project?

Option C - Embed application and plugin frameworks in Xcode and Flutter framework with CocoaPods

**Comment by ZQDXY** [comment]
Release/
        ├── Flutter.podspec
        ├── App.xcframework
        ├── FlutterPluginRegistrant.xcframework
        └── example_plugin.xcframework

For example, I want to import more .xcframework, but I don't know how to import it

**Comment by darshankawar** [comment]
@ZQDXY 
Your question is better suited for support channels like StackOver flow. Please see https://flutter.dev/community for resources.
Closing this issue since, I believe your original issue is resolved. If you disagree, write in comments and I'll reopen.
