### ISSUE TITLE
Caret position does not changes in production mode (web)

### ISSUE THREAD

**Issue by akkinenirajesh** [flutter/flutter#75411]
Caret position is not changing when we click at different positions, if TextSpan contains multiple styles. 
This problem is coming only in production mode and not in debug mode. 

This issue is related to web mode only.

Flutter version: 
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (3 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)

## Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class OwnController extends TextEditingController {
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    return TextSpan(
      style: style,
      children: [
        TextSpan(
          text: 'Hello ',
        ),
        TextSpan(text: 'World!', style: TextStyle(color: Colors.red.shade400)),
      ],
    );
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  OwnController _controller = OwnController();

  @override
  void initState() {
    _controller.text = 'Hello World!';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: TextField(
      controller: _controller,
    ));
  }
}

```

**Expected results:**
When user clicks on any position in text field, we expect caret to move to that location. 

**Actual results:**
Caret stays at 0/start position.

If we remove style to 'World!' text span above, it is working.

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.25.0-8.3.pre at C:\Users\Rajesh\apps\flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rajesh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Rajesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```
```

</details>

**Comment by darshankawar** [comment]
@akkinenirajesh 
I see a similar [issue](https://github.com/flutter/flutter/issues/64330) mentioning your use case, which was closed in favor of original open [issue](https://github.com/flutter/flutter/issues/41630). Can you check out those and confirm if they resemble your use case ?

**Comment by akkinenirajesh** [comment]
@darshankawar I have seen those issues. I don't think it is same issue. In my case caret is not at all moving from starting position. unable to select text etc. Where as those issues are related to caret being shown in wrong location or related to scroll.

**Comment by akkinenirajesh** [comment]
Also here difference is from debug mode to release mode. Everything working fine in debug more. (same chrome browser in both cases).

**Comment by akkinenirajesh** [comment]
This is working in dev channel. So closing it.
