### ISSUE TITLE
Videos (.mp4) are not playable on Windows/Mac/Linux devices.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#75414]
I am using video_player: ^1.0.1 for Android & iOS platform and it's working properly. Please suggest if any solution to play videos properly on these desktop platforms.

**Comment by TahaTesser** [comment]
`video_player` isn't currently supported on these `macOS `, `Linux`, and `Windows`.
https://github.com/flutter/flutter/issues/41688
https://github.com/flutter/flutter/issues/39091
https://github.com/flutter/flutter/issues/37673

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
