### ISSUE TITLE
flutter widget 

### ISSUE THREAD

**Issue by kunalpohakar** [flutter/flutter#75415]
```bash
 EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25849): The following assertion was thrown building OnboardingPage(dirty):
I/flutter (25849): PageController.page cannot be accessed before a PageView is built with it.
I/flutter (25849): 'package:flutter/src/widgets/page_view.dart':
I/flutter (25849): Failed assertion: line 180 pos 7: 'positions.isNotEmpty'
```

**Comment by TahaTesser** [comment]
Hi @kunalpohakar 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by kunalpohakar** [comment]
> Hi @kunalpohakar
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Thank you for your concern but solved my problem. actually, the problem was in my code but thank you.

**Comment by 0xdanny** [comment]
I think this should be closed now @TahaTesser

**Comment by TahaTesser** [comment]
Hi @kunalpohakar 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
