### ISSUE TITLE
Plugins that were not migrated for Android V2 breaks background services.

### ISSUE THREAD

**Issue by atrope** [flutter/flutter#75416]
Hi All and @markusaksli-nc :)

Bringing here  what was discussed in
https://github.com/FirebaseExtended/flutterfire/issues/4424 and #62006 

When we upgraded firebase_messaging for V8 we were expected to be able to use plugins without the workaround that was needed before to manually register the ones we would need.

The problem is that in the App itself after migrating to V8 the `Shared Preference` was not working giving us:

`E/flutter (26007): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
`

When trying to reproduce in a minimal app everything would work perfectly and Shared Preference would work without problems.

That's when i realized:

Everyone having this problem, please open your `GeneratedPluginRegistrant` and you will see flutter registering the plugins with 2 different types, the old plugins and the new ones.

The plugins are inserted there alphabetically independent of V1 or V2 embedding.

Now, here's the Catch, as long as you include a plugin that uses the V2 Embedding AND do not include any V1 embedding BEFORE(and by before i mean alphabetically, by the plugin name) it will work.

In my case, i was trying to use `Shared Preferences`, it starts with "S", So i CAN include the "Social Share" plugin because the order of the `GeneratedPluginRegistrant` will be ok

```
flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());   

com.shekarmudaliyar.social_share.SocialSharePlugin.registerWith(shimPluginRegistry.registrarFor("com.shekarmudaliyar.social_share.SocialSharePlugin"));

flutterEngine.getPlugins().add(new name.avioli.unilinks.UniLinksPlugin());

```
So i could theoretically use `SharedPreferences` but NOT  `unilinks`. 

I Can see 3 different approaches to fix this problem...

1 - Generate the GeneratedPluginRegistrant by Embedded version Order V2->V1, we would not be able to use V1 Plugins in our Background process, but it would not break Any V2 Plugin

2 - Remove or fix the plugin to use V2

3 - Check with Flutter Team why it's breaking when registering V1 (It's OK if it does not work, but it SHOULD not break the rest of the plugins)

While Flutter team cannot check the 3rd one I've come with a workaround to at least  use all V2 plugins without issues..

What we will accomplish is to change the order of the `GeneratedPluginRegistrant` to put all V1 in the bottom. (The first option)
To do this we need to alter the flutter tools responsible for generating that file it is pretty simple.

Open the file 
`<flutter-sdk-location>/packages/flutter_tools/lib/src/plugins.dart`

find the `_writeAndroidPluginRegistrant` function and add the following snippet AFTER the call to _extractPlatformMaps:

```
    androidPlugins.sort((Map<String, dynamic> left, Map<String, dynamic> right) {
      if (left["supportsEmbeddingV2"] != right["supportsEmbeddingV2"]) {
        return left["supportsEmbeddingV2"] ? -1 : 1;
      }
      return left["name"].compareTo(right["name"]);
    });
```

![Screen Shot 2021-02-03 at 15 53 18](https://user-images.githubusercontent.com/2945478/106794679-f08dee80-6637-11eb-98bd-5575f47dbc09.png)

Now we only need to rebuild flutter tools, to do that we need to remove  the flutter_tools.stamp:

`rm -rf  <flutter-sdk-location>/bin/cache/flutter_tools.stamp
`

That's it, now you can flutter pub get and the `GeneratedPluginRegistrant` will be sorted as we want and we will be able to use V2 embedded plugins without problems.

I could theoretically make a PR to change this snippet on flutter tools, but I think we need first to confirm with someone from the team that it would be needed..

PS: As stated in the #62006 I Have not yet tested on iOS and this issue is related to Android only for now.

**Comment by darshankawar** [comment]
@atrope 
Thanks for the detailed report. Is there a way to replicate the core issue and then try to implement the fix you've proposed above, in order to better analyze this issue ?

**Comment by atrope** [comment]
Yes, Just use the example app from firebase_messaging and add the plugins For example:

  mdns_plugin: ^1.1.4
  shared_preferences: ^0.5.12+4

And try to use Shared Preference in the background function of Messaging.

**Comment by TahaTesser** [comment]
Hi @atrope 
When adding these packages to  firebase_messaging, getting the following errors 
```bash
  mdns_plugin: ^1.1.4
  shared_preferences: ^0.5.12+4
```

<details>
<summary>logs</summary>

```bash
[  +71 ms] --------- beginning of main
           02-04 20:30:46.245 W/InputChannel-JNI( 1420): Input channel object 'ClientState{c4d4a79 uid=10075 pid=2104 displayId=0}
           (server)' was finalized without being disposed!
[  +20 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb version
[  +21 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /Volumes/Extreme/SDK/platform-tools/adb
[   +2 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb start-server
[  +11 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from
/Users/tahatesser/AndroidStudioProjects/flutterfire/packages/firebase_messaging/firebase_messaging/example/android/gradlew.
[   +1 ms]
/Users/tahatesser/AndroidStudioProjects/flutterfire/packages/firebase_messaging/firebase_messaging/example/android/gradlew mode:
33261 rwxr-xr-x.
[   +6 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +14 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKA
GE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib
\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"ide
a.paths.selector":"AndroidStudio4.1","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.vendor.name":"Google","
idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to
the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.41.7042882","CFBundleDevelopmentRegion":"English","NS
CameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSu
pportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,
"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in
Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFB
undleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.develo
per-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android
Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio
requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests
access to files on a network volume.","CFBundleGetInfoString":"Android Studio 4.1, build AI-201.8743.12.41.7042882. Copyright
JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on
a removable volume."}
[  +26 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +115 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +1 ms] executing:
[/Users/tahatesser/AndroidStudioProjects/flutterfire/packages/firebase_messaging/firebase_messaging/example/android/]
/Users/tahatesser/AndroidStudioProjects/flutterfire/packages/firebase_messaging/firebase_messaging/example/android/gradlew
-Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/Users/tahatesser/AndroidStudioProjects/flutterfire/packages/firebase_messaging/firebase_messaging/example/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1186 ms] FAILURE: Build completed with 2 failures.
[        ] 1: Task failed with an exception.
[        ] -----------
[        ] * Where:
[        ] Build file '/Users/tahatesser/.pub-cache/hosted/pub.dartlang.org/mdns_plugin-1.1.4/android/build.gradle' line: 12
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':mdns_plugin'.
[        ] > Could not get unknown property 'kotlin_version' for object of type
org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] ==============================================================================
[        ] 2: Task failed with an exception.
[        ] -----------
[        ] * Where:
[        ] Script '/Users/tahatesser/Code/flutter_beta/packages/flutter_tools/gradle/flutter.gradle' line: 318
[        ] * What went wrong:
[        ] A problem occurred configuring project ':mdns_plugin'.
[        ] > Could not get unknown property 'android' for project ':mdns_plugin' of type org.gradle.api.Project.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] ==============================================================================
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 996ms
[ +401 ms] Running Gradle task 'assembleDebug'... (completed in 1,764ms)
[+5331 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 75,827ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[ +116 ms] ensureAnalyticsSent: 105ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1
tahatesser@Tahas-MacBook-Pro example % 
```

</details>

**Comment by blasten** [comment]
@atrope `mdns_plugin: 1.1.4` has a bug in https://github.com/djthorpe/flutter/blob/master/mdns_plugin/android/build.gradle#L12. (`kotlin_version` is not defined). Bonus point if you could send them a PR to fix that issue. 😃

About your suggestion specifically, were you able to identify why the order of registration matters?  More importantly, is this a situation that holds true only for these plugins?

**Comment by atrope** [comment]
Any plugin that uses V1 and starts alphabetically first than S would work for the example :)


@blasten I do not know why registering a V1 plugin makes flutter stop registering be plugins. I guess some error occurs and it stops "gracefully" it does not show anything for us.

And as I said ANY plugin that uses V1 breaks the registration for those underneath, I sent the mdns because it is one that I use.. and the solution is to 'break' after registering all V2 plugins

**Comment by atrope** [comment]
@TahaTesser 
remove mdns and add   disk_space: ^0.0.3
:)

**Comment by darshankawar** [comment]
I was able to see the alphabetical registration of the plugins in the `GeneratedPluginRegistration` class, after adding `disk_space`, `shared_preferences` and `social_share`plugins using `firebase_messaging` official [repo](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example).

<img width="920" alt="Screenshot 2021-02-05 at 12 35 50 PM" src="https://user-images.githubusercontent.com/67046386/107000959-c9a5f880-67ae-11eb-87c9-90a26e8e7c4f.png">

While using above added plugins and trying to call `onBackgroundMessage` using `shared_preferences`, I received below in console:

```
E/flutter (15820): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (15820): 
E/flutter (15820): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (15820): 
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (13 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.

```

</details>


Keeping this issue open for further analysis.

**Comment by rockingdice** [comment]
This issue may be quite annoyed for new flutter developers.
Currently, some plugins are not migrated to v2.
They are likely to use the latest stable version flutter, plugins from pub.dev, and some of them are v1.
Eventually, they will find this issue will be the blocker. A v1 plugin added to the project will break it. The v2 plugins are not working anymore.

I think it's better to provide a quick and temporary solution for them.

**Comment by dgaedcke** [comment]
Certain plugins (eg await Firebase.initializeApp();) CAN be called BEFORE runApp()  ... at top of:
void main() async {}

**others (await SharedPreferences.getInstance(); ) MUST be called from a Widget INSIDE of runApp()**

This was confusing to me and has not been clearly stated in any docs I've been able to find.

I suspect a lot of the people seeing "shared_preferences -- No implementation found for method getAll" were making the same mistake as I was ... trying to bind SharedPreferences too early in the load sequence.

**Comment by atrope** [comment]
@darshankawar should I open a PR to the engine to apply the change(at least for now)  to order V2->V1?

**Comment by atrope** [comment]
Ok, PR Opened 😆, I Guess we will have no problems approving it as it only changes the order of plugins being registered and it can save a lot of problems for many users.

**Comment by Desno365** [comment]
Had the same issue, luckily I found this thread after some hours of debugging. Thanks a lot @atrope!

**Comment by themadmrj** [comment]
Please merge this, I just lost a few hours until I found this solution...

**Comment by atrope** [comment]
The PR has been merged.

I Will close this PR as it is already available on master channel :)

**Comment by larssn** [comment]
The most aggravating thing about this issue is that it **completely** masks the underlying problem! We **cannot** build for Flutter 2.0.4 (stable) currently (the deleting of flutter_tools.stamp doesn't work for us). `master` works, but we have a production app that we'd rather didn't run on the master channel.

Can we please get this fix into stable ASAP?

Anyway, kudus @atrope for figuring this out! It was quite the head scratcher for us.

**Comment by atrope** [comment]
@larssn 

If master is working, you can apply the fix we did in any branch you like.

Instead of sorting out the plugins, change the  `_androidPluginRegistryTemplateNewEmbedding` variable and rebuild the tool.



```

const String _androidPluginRegistryTemplateNewEmbedding = '''
package io.flutter.plugins;
import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;
import io.flutter.embedding.engine.FlutterEngine;
{{#needsShim}}
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;
{{/needsShim}}
/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
{{#needsShim}}
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
{{/needsShim}}
{{#plugins}}
  {{#supportsEmbeddingV2}}
    try {
      flutterEngine.getPlugins().add(new {{package}}.{{class}}());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin {{name}}, {{package}}.{{class}}", e);
    }
  {{/supportsEmbeddingV2}}
  {{^supportsEmbeddingV2}}
    {{#supportsEmbeddingV1}}
    try {
      {{package}}.{{class}}.registerWith(shimPluginRegistry.registrarFor("{{package}}.{{class}}"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin {{name}}, {{package}}.{{class}}", e);
    }
    {{/supportsEmbeddingV1}}
  {{/supportsEmbeddingV2}}
{{/plugins}}
  }
}
''';

```


Let me know if that works for you :)

**Comment by atrope** [comment]
Remember to Rebuild you must delete the flutter_tools.stamp

**Comment by larssn** [comment]
@atrope I know, but monkey patching stable is something we'd prefer to avoid. Would rather this wasn't a P4. 🙂

**Comment by rockingdice** [comment]
I would suggest to make it available on stable branch too. It's broken on the stable branch right now. I think we should reconsider it as an emergency hotfix.

**Comment by FabioPaganoAPSystem** [comment]
Currently a workaround is to add in "/android/app/build.gradle" the values  
   shrinkResources false
   minifyEnabled false

under

   buildTypes {
       release {

To remove when the fix will arrive in stable.
