### ISSUE TITLE
Performance issues with Gallery on Sony Xperia XZ

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7541]
From a user report on Reddit: https://www.reddit.com/r/androiddev/comments/5o8v0g/anyone_using_dart_with_flutter_how_is_it/dcms0gf/?context=3

"""
Was using a Sony Xperia XZ. I unfortunately don't have it with me right now. The framedrops were frequent and obvious, even in pure text sections like the main screen. Felt quite jarring, along with the non-androidy fling velocity.

I just installed on a Snapdragon 650(?) based Xperia X and the performance is basically fine. Occasional stutters on the main "Flutter Gallery" screen and "Pesto" when flinging, and e.g. on the opening animation of "Shrine". Not terrible.
"""

**Comment by eseidelGoogle** [comment]
The XZ is a modern phone (sept 2016): http://www.gsmarena.com/sony_xperia_xz-8313.php with the same GPU as the pixel: http://www.gsmarena.com/google_pixel_xl-8345.php and similar CPU.  I would not expect any stutter on this device.

We do not have one in our central lab last I looked.

**Comment by sethladd** [comment]
Happy to buy one. I've asked the original reporter for more specifics.

**Comment by orestesgaolin** [comment]
I also have performance issues in Flutter Gallery app on Samsung S8 which is relatively powerful phone. Please see attached video showing how frames are dropped in _Crane_ example within Flutter Gallery 2.3.0 app downloaded from the Play Store.

Similar issue: #26688

[flutter_gallery_perf_issue.zip](https://github.com/flutter/flutter/files/4270323/flutter_gallery_perf_issue.zip)

**Comment by markusaksli-nc** [comment]
@sethladd Is something still planned to be to done here?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
