### ISSUE TITLE
Removing UIKitView when dragging and scrolling from CustomScrollView breaks the scrolling animation 

### ISSUE THREAD

**Issue by el12n** [flutter/flutter#75421]
When by any chance we drag the UIKitView when scrolling a CustomScrollView and then we hide UIkitView tends to break the whole scroll animation of the CustomScrollView widget.

![uikitview-scroll-issue](https://user-images.githubusercontent.com/5896630/106907976-3947b500-66d5-11eb-85ee-caafef1ea314.gif)

## Steps to Reproduce

1. Clone the test project from the following [repo](https://github.com/el12n/test_scrollview_uikitview)
2. Run in an iOS device and slowly start scrolling down until see the UIKitView (the red rectangle)
3. Scroll and drag it until it vanish.
4. Check the whole scroll animation gets laggy.

**Target Platform**: iOS
**Devices**: All iOS devices

## Flutter Doctor 
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-18.0.pre.187, on macOS 11.2 20D64
    darwin-arm, locale en-DO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment]
Was able to replicate it on latest stable. Dragging the red rectangle makes the scrolling animation slow and laggy.

![IMG-0625](https://user-images.githubusercontent.com/67046386/107005112-3fad5e00-67b5-11eb-8003-b86d2fc9cd8e.PNG)
![IMG-0626](https://user-images.githubusercontent.com/67046386/107005123-420fb800-67b5-11eb-8fa1-4c2d3e46a1e7.jpg)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (13 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.2

! Doctor found issues in 1 category.

```

</details>

**Comment by blasten** [comment]
cc @cyanglaz  - sounds like the gesture issue you looked at a while back

**Comment by cyanglaz** [comment]
The fix has rolled into the framework at https://github.com/flutter/flutter/commit/b957144136c36f189f00876b71379a0a7cae7efc
Please try out Flutter on master see if it resolves the issue :)
