### ISSUE TITLE
Tool reports errors that are not user responsibility related to FFI

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#75429]
Related to https://github.com/flutter/flutter/issues/75113

I talked a bit more with @dcharkes about this.

Package:ffi is getting updated, so other packages will be able to update. I'm still concerned that users will see a big wall of red text that they shouldn't when they depend on a non-upgraded package on the current release candidate.

For example, this program (using path_provider: 1.6.27, which in turn depends on win32 and ffi transitively):

```dart
import 'package:path_provider/path_provider.dart'

void main() {
  print('hello');
}
```

Will print out the string of warnings listed in #75113.

If the CFE reports these issues in a dependency, we should not print out the warnings, similar to how we do not print out deprecation warnings in other packages (we let the analyzer handle that).

/cc @dcharkes @jonahwilliams @christopherfujino

**Comment by dnfield** [comment]
In particular, we want to avoid users who are going to upgrade to the new release candidate and depend on any of a number of popular packages that depend no package:ffi/win32/etc from seeing a wall of red text whenever they run/test their app.

@dcharkes is going to provide the specific hint type the CFE is emitting.

**Comment by dcharkes** [comment]
Analyzer codes for deprecation messages: `EMPTY_STRUCT_WARNING`, `NON_CONSTANT_TYPE_ARGUMENT_WARNING`.

**Comment by dnfield** [comment]
We talked offline some more - it'll probably be best to remove the hints from the CFE for this, @dcharkes is going to look into this

**Comment by dcharkes** [comment]
Turns out my CLs were the first to ever emit `info`-severity messages from the frontend_server. We've landed a change to no longer print `info`s in the frontend server and filed a CP on Dart (https://github.com/dart-lang/sdk/issues/44869).

Thanks @johnniwinther for the background info and quick review!

**Comment by tvolkert** [comment]
@dcharkes is there anything still to do here, or are we just waiting for the CLs to roll through?

**Comment by dcharkes** [comment]
Do you need to do anything on your side to make the Dart beta roll into a new Flutter beta? If no, then we're done.

Dart beta with CP https://github.com/dart-lang/sdk/commit/bc1fa173477efb6192bddd5f95c1ad0cccbc8d6f

**Comment by christopherfujino** [comment]
@tvolkert @pcsosinski sounds like with regards to the RC branch, the next release will pick up the dart fix and resolve this issue.

**Comment by pcsosinski** [comment]
removing cp label as this will be picked up with the Dart CP
