### ISSUE TITLE
The new Flutter project will not start. at android\app\build.gradle' line: 25

### ISSUE THREAD

**Issue by l3liang** [flutter/flutter#75424]
The new Flutter project will not start.

<details>
<summary>logs</summary>

```bash

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\myapp\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> org/jetbrains/kotlin/cli/common/PropertiesKt

---------------
Detailed log
 FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[        ] Build file 'D:\myapp\android\app\build.gradle' line: 25
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred evaluating project ':app'.
[   +1 ms] > org/jetbrains/kotlin/cli/common/PropertiesKt
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 2s
[ +496 ms] Running Gradle task 'assembleDebug'... (completed in 3.6s)
[+5396 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 10,966ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
```

</details>

**Comment by TahaTesser** [comment]
Hi @l3liang 
Can you please provide your `flutter doctor -v` your  complete`flutter run --verbose` logs
Thank you

**Comment by l3liang** [comment]
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18362.1256], locale zh-CN)
    • Flutter version 1.22.6 at D:\flutter\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.


[ +143 ms] executing: [D:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +479 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +1 ms] executing: [D:\flutter\flutter/] git tag --points-at HEAD
[ +183 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.6
[   +8 ms] executing: [D:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +165 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\flutter\flutter/] git ls-remote --get-url origin
[ +159 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +194 ms] executing: [D:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[ +180 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +159 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] executing: D:\sdk\platform-tools\adb.exe devices -l
[ +164 ms] List of devices attached
                    emulator-5554          device product:sdk_gphone_x86_64_arm64 model:sdk_gphone_x86_64_arm64 device:generic_x86_64_arm64 transport_id:1
[   +8 ms] D:\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +190 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +298 ms] Generating D:\code\flutter_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +28 ms] ro.hardware = ranchu
[  +36 ms] Using hardware rendering with device sdk gphone x86 64 arm64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +39 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +9 ms] complete
[   +6 ms] Launching lib\main.dart on sdk gphone x86 64 arm64 in debug mode...
[   +6 ms] D:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\xx~1\AppData\Local\Temp\flutter_tools.4e9726d\flutter_tool.d0e3bcb2\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +27 ms] executing: D:\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +188 ms] Exit code 0 from: D:\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-05 15:33:11.020 E/netmgr  (  479): Failed to open QEMU pipe 'qemud:network': Invalid argument
[   +2 ms] executing: D:\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +181 ms] Exit code 0 from: D:\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of kernel
           02-05 15:33:37.278 D/logd    (    0): logdr: UID=2000 GID=2000 PID=6449 n tail=1 logMask=99 pid=0 start=0ns timeout=0ns
[  +45 ms] <- compile package:flutter_app/main.dart
[  +24 ms] executing: D:\sdk\platform-tools\adb.exe version
[ +206 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.5-6877874
                    Installed as D:\sdk\platform-tools\adb.exe
[   +3 ms] executing: D:\sdk\platform-tools\adb.exe start-server
[ +168 ms] Building APK
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from D:\code\flutter_app\android\gradlew.bat.
[   +1 ms] D:\code\flutter_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +281 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [D:\code\flutter_app\android/] D:\code\flutter_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x64 -Ptarget=D:\code\flutter_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4256 ms] FAILURE: Build failed with an exception.
[  +17 ms] * Where:
[   +1 ms] Build file 'D:\code\flutter_app\android\app\build.gradle' line: 25
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred evaluating project ':app'.
[   +1 ms] > org/jetbrains/kotlin/cli/common/PropertiesKt
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[  +20 ms] BUILD FAILED in 3s
[ +532 ms] Running Gradle task 'assembleDebug'... (completed in 5.1s)
[+3600 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 10,490ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by l3liang** [comment]
![image](https://user-images.githubusercontent.com/32877313/107057504-824f5480-680e-11eb-88c0-44adf47cdafe.png) 
Just don't choose
