### ISSUE TITLE
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)

### ISSUE THREAD

**Issue by virux99** [flutter/flutter#75420]
In reference of [https://github.com/flutter/flutter/issues/51562](url)
I am facing same error iOS app crashes on ipad mini please see the logs below, if you need any more information let me know

```
Error:
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)

 
Stack trace:
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)

#1 MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345)

#2 MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:61)

#3 _CameraScreenState._initCamera (package:Jula_App/component/camera/camerascreen.dart:167)
 

 
Device parameters:
model: iPad
isPsychicalDevice: true
name:  iPadMini
identifierForVendor: xxxxxxxxxx
localizedModel: iPad
```

**Comment by darshankawar** [comment]
@virux99 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue ?
Also, is this issue only occuring on iPad or on iPhone as well ?

**Comment by virux99** [comment]
thankyou for your response, yes sure I will provide the required details tonight

**Comment by virux99** [comment]
And yes this issue occurs only on ipad mini with ios 9.0

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by vers10ne** [comment]
Hi, I get the same/similar: 

```
Error: MissingPluginException(No implementation found for method availableCameras
on channel plugins.flutter.io/camera)
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5339:11)
    at MethodChannel._invokeMethod
    (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.j
    s:962:21)
```
etc etc 

I'm just trying to do the complete example: [https://flutter.dev/docs/cookbook/plugins/picture-using-camera#complete-example](https://flutter.dev/docs/cookbook/plugins/picture-using-camera#complete-example)

flutter doctor -v says: • No issues found!
Running in Chrome on Mac.

Any help please?
Thank you!

**Comment by lauraAriasFdez** [comment]
I am having the same issue, but flutter doctor says "No issues found!" Any idea how to solve the problem?
