### ISSUE TITLE
State not maintained in web application

### ISSUE THREAD

**Issue by Tusshu** [flutter/flutter#75437]
Created web application using instructions here: https://flutter.dev/docs/get-started/web
Changing the primarySwatch color and hot reloading the application with "r" command resets the click count to 0. Shouldn't the click count not supposed to change as mentioned in comments in "theme: ThemeData(...)" section?

**Comment by erickzanardo** [comment]
@Tusshu Flutter web at the moment don't support hot reload yet, only hot restart is supported, you can see a mention to that on the Hot reload documentation [here](https://flutter.dev/docs/development/tools/hot-reload#how-to-perform-a-hot-reload).
