### ISSUE TITLE
java.lang.NullPointerException at io.flutter.plugins.b.c$a.a

### ISSUE THREAD

**Issue by PJosue100** [flutter/flutter#75433]
I have an Android application currently on Google Play and these crashes are very recurring

**Crash 1**

java.lang.NullPointerException:
  at io.flutter.plugins.b.c$a.a (Unknown Source:2)
  at io.flutter.plugins.b.c$a.a (Unknown Source:69)
  at io.flutter.plugins.b.c$a.a (Unknown Source:8)
  at io.flutter.plugins.b.c$a.a (Unknown Source)
  at io.flutter.plugins.b.c$a$a.a (Unknown Source:2)
  at c.c.a.b.i.x.run (Unknown Source:23)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)

**Crash 2**

java.lang.NullPointerException:
  at io.flutter.plugins.b.c$a.a (Unknown Source:2)
  at io.flutter.plugins.b.c$a.a (Unknown Source:33)
  at io.flutter.plugins.b.c$a.a (Unknown Source)
  at io.flutter.plugins.b.c$a$a.a (Unknown Source:2)
  at c.c.a.b.i.x.run (Unknown Source:23)
  at android.os.Handler.handleCallback (Handler.java:795)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:6861)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:450)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

**Comment by darshankawar** [comment]
@PJosue100 
Can you elaborate when you say `Android application currently on Google Play` ? Does that mean you have Android embedded with Flutter ? 
Can you provide `flutter doctor -v` Does the crash occur locally in non-prod environment ?
Is there a way to provide a reproducible use case that can possibly show this crash ?

**Comment by PJosue100** [comment]
@darshankawar 
Giving context, it is an android application using Flutter that after uploading the apk to google play console began to give these two crashes constantly.

Este es el flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [VersiÃ³n 10.0.18363.1316], locale es-GT)
    • Flutter version 1.22.3 at C:\Users\Josue\flutter_windows_1.17.5-stable\flutter
    • Framework revision 8874f21e79 (3 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Josue\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Josue\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

I do not know how to replicate the error since in the google console it only shows me the previously published error. Maybe they can give me an idea of where to start looking.

**Comment by darshankawar** [comment]
@PJosue100 
Is it possible for you to install the app from play console and check where do you get the crash ?
Also, you seem to be on older version of stable. Current version is 1.22.6. May be upgrade your app to latest and try again to see if you still get same crashes ?

**Comment by PJosue100** [comment]
hi @darshankawar

The application at the moment is only available for a certain country, I can create an internal test and include it to the list of testers of the application; so you can download it.
You can send me your email to the following email pjdeveloper100@gmail.com.

At the time I decided to update the stable version, but android studio stopped recognizing the flutter and dart plugins. In some forums it is recommended to change from stable to master. But I don't think it's the best (https://es.stackoverflow.com/questions/398533/flutter-doctor-no-me-reconoce-el-complemento-de-flutter-y-dart).

At this time it is not feasible to set an update because an update was recently released and we could lose users.

**Comment by darshankawar** [comment]
> but android studio stopped recognizing the flutter and dart plugins.

@PJosue100 This is not an issue. Even though you see these messages in `flutter doctor -v` output, they are just warnings but you can still be able to use those plugins in your code without any issues.

Also, If possible, share repo of your code / app here that we can clone and ran to verify the issue. We don't need your production code, a sample code which is reproducible that we can use.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
