### ISSUE TITLE
flutter_localization server unavailable

### ISSUE THREAD

**Issue by hasenbalg** [flutter/flutter#75451]
Hi, adding   `flutter_localization` to my pubspec.yaml results in an endless loop of `flutter pub get`

## Steps to Reproduce
I added it this way:
```
...

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localization:
    sdk: flutter
...

```

and ran `flutter pub get`

## Logs

<details>
<summary>Logs</summary>

```
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Because trex_app depends on flutter_localization any from sdk which doesn't exist (could not find package flutter_localization in the Flutter SDK), version solving failed.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
```

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/megalosaurus/development/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/megalosaurus/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/megalosaurus/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/megalosaurus/development/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/megalosaurus/development/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Nokia 6 1 (mobile) • PL2GAR9892507100 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by mmmcorpsvit** [comment]
send you issue here: https://github.com/billylev/flutter_localizations/issues

**Comment by darshankawar** [comment]
@hasenbalg 
There's usually `flutter_localizations` plugin in `pubspec.yaml`:

<img width="252" alt="Screenshot 2021-02-05 at 1 46 17 PM" src="https://user-images.githubusercontent.com/67046386/107007498-9cf6de80-67b8-11eb-84ed-b28f6685443a.png">

You seem to be using `flutter_localization`. Is it a 3rd party ? Can you point us to it's pub dev ?

**Comment by iapicca** [comment]
> You seem to be using `flutter_localization`. Is it a 3rd party ? Can you point us to it's pub dev ?

@darshankawar 
[flutter_localizations](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) is definitely part of `flutter` as you can see from the [repo](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations);
what @mmmcorpsvit [referenced](https://github.com/flutter/flutter/issues/75451#issuecomment-773623127), for reasons beyond my understanding, 
seems to be a long-time-inactive fork

@hasenbalg 
it seems to me that you add the dependency correctly, 
your logs points at a connection issue
`pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...`
please take a look to the proposed solutions [here](https://github.com/dart-lang/pub-dev/issues/1767)

**Comment by behzodfaiziev** [comment]
@hasenbalg  I think you should upgrade  Flutter version 1.22.4 to  Flutter version 1.22.6

**Comment by behzodfaiziev** [comment]
@hasenbalg I think you should upgrade Flutter version 1.22.**4** to Flutter version 1.22.**6**
And edit **flutter_localization** to **flutter_localizations**

@iapicca I think he had a spelling mistake.

**Comment by iapicca** [comment]
@hasenbalg 
I think @behzodfaiziev is right, probably just a typo in you import

**Comment by hasenbalg** [comment]
@behzodfaiziev @iapicca you are right. having an `s` in the end makes it work. must be an magic `s`. Thanks a LOT
