### ISSUE TITLE
FlutterDesktopEngineCreate takes argument by reference

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#75465]
I'm not sure how much of a problem this in practice, but I'm bringing this up just in case.

The methods in `flutter_windows.h` are declared as extern "C", but `FlutterDesktopEngineCreate` takes `engine_properties` by const reference, which is not a C thing. 

Right now calling it with a pointer (i.e. through FFI or from Rust) works, and I don't suppose it's going to change in future, but it seems like it's relying on unspecified behavior.

**Comment by stuartmorgan** [comment]
That should definitely be fixed, the sooner the better to minimize possible breaks (in practice, probably nobody will be broken because the template only uses the wrapper). It's there because for some reason I'm incapable of remembering that references are C++, not C.

/cc @cbracken
