### ISSUE TITLE
MediaQuery.of should not fallback

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7547]
MediaQuery.of() should throw a FlutterError explaining that you should use a WidgetsApp if it doesn't find a MediaQuery in the tree.

**Comment by Hixie** [comment]
(rather than defaulting to fromWindow, which is a foot gun waiting to happen)

**Comment by abarth** [comment]
The problem is that `Text` and other basic widgets use `MediaQuery`...  We could add a `nullOk` flag, but it's not clear to me how to decide when to pass that flag...

**Comment by Hixie** [comment]
You pass it when you're able to handle it being null by providing your own defaults.

**Comment by abarth** [comment]
As an example, should `AppBar` be willing to fall back when it is trying to learn the top padding?

**Comment by Hixie** [comment]
It has three options:
1. Require that you provide a `MediaQuery`, e.g. via a `WidgetsApp`, the same way a `FlatButton` requires a `Material`.
2. Default to nothing, so if you don't provide a `MediaQuery`, and you put it at the top of the screen, it'll go under the bar, the same way we default to white Text if you don't have a DefaultTextStyle.
3. Implement a fallback mechanism that hooks into the engine notification mechanism and marks itself dirty when the relevant metrics change.

I don't propose to ever do 3 except in `WidgetsApp`. I don't have an opinion on whether 1 or 2 is better in general. We have precedent for both. I think for `AppBar`, it being a material concept, it's reasonable to require a `MaterialApp`. I think for `Text`, it being a core concept that you're likely to use even when driving things directly via `runApp` with few if any high-level widgets (e.g. a splash screen, a custom widget set, a game), it's reasonable to not require that the author provide a `MediaQuery` and thus it's ok to default to 0 on any interesting metric that would have come from `MediaQuery`.

**Comment by abarth** [comment]
Ok.  I can go through all the uses and try to categorize them.
