### ISSUE TITLE
Error while initializing the Dart VM: Precompiled runtime requires a precompiled snapshot

### ISSUE THREAD

**Issue by UjjawalPanchal** [flutter/flutter#75488]
```
2021-02-05 14:28:52.000 24171-24171/com.farmer.farmerconnection A/flutter: [FATAL:flutter/runtime/dart_vm.cc(441)] Error while initializing the Dart VM: Precompiled runtime requires a precompiled snapshot
2021-02-05 14:28:52.001 24171-24171/com.farmer.farmerconnection A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 24171 (armerconnection), pid 24171 (armerconnection)
```

flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-13.0.pre.96, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!


flutter doctor -v :

[√] Flutter (Channel master, 1.26.0-13.0.pre.96, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-13.0.pre.96 at D:\Flutter SDK\flutter_windows_1.22.5-stable\flutter
    • Framework revision eeb7c261f2 (2 weeks ago), 2021-01-20 23:04:03 -0500
    • Engine revision dde6b7e8ea
    • Dart version 2.12.0 (build 2.12.0-246.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM T820 (mobile) • 192.168.2.15:5555 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome            • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)       • edge              • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!



need urgent help.



```

**Comment by darshankawar** [comment]
@UjjawalPanchal 
When do you get this error ?

**Comment by UjjawalPanchal** [comment]
> @UjjawalPanchal
> When do you get this error ?

When I installed the release apk to device, it will crash instantly.

**Comment by darshankawar** [comment]
@UjjawalPanchal 
Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can run that'll show the crash ? 
Also, How did you generate release build (build apk or appbundle) ? (provide full command).

**Comment by UjjawalPanchal** [comment]
I am running released build variant from separate android studio code, APK is installed successfully but the issue is with "Error while initializing the Dart VM".
I can share my dependencies which I added in pubspec.yaml
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  persistent_bottom_nav_bar: ^3.1.0
  flushbar: ^1.10.4
  http: ^0.12.2
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  keyboard_actions: ^3.3.1+1
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.2+1
  country_pickers: ^1.3.0
  pin_input_text_field: ^3.3.0
  shared_preferences: ^0.5.12+4
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  place_picker: ^0.9.17
  url_launcher: ^5.7.10
  speech_to_text: ^3.1.0
  material_design_icons_flutter: ^4.0.5855
  webview_flutter: ^1.0.7
  flutter_tts: 2.1.0
  firebase_messaging: ^7.0.3
  geocoder: ^0.2.1


I also tried with flutter build run --release but getting same error.

I also tried with creating new demo project but initially it is running fine but when I move my dart classes to the demo project the result is same I am getting same error.

**Comment by darshankawar** [comment]
@UjjawalPanchal 
Only providing dependencies won't help. We would need a reproducible use case that triggers the crash you mentioned. You may prepare a sample app (doesn't have to be your production code) that has all required code which will be enough to reproduce the crash.

**Comment by UjjawalPanchal** [comment]
Thanks got the issue.

**Comment by kustraslawomir** [comment]
> Thanks got the issue.

and how you fix'd this??

**Comment by chiragintersoft** [comment]
> Thanks got the issue.

Can u pls tell how did you solve it ?

**Comment by skustra** [comment]
> Thanks got the issue.

Coul you respond u little fuck shit?

**Comment by skustra** [comment]
> Thanks got the issue.

???

**Comment by UjjawalPanchal** [comment]
Hey in my case I just remove all dependencies and add them again

**Comment by kustraslawomir** [comment]
@UjjawalPanchal @chiragintersoft 

Thanks but only downgrading gradle to:

` classpath 'com.android.tools.build:gradle:3.6.2'`

Fixed issue for me.

**Comment by M2dL1fe** [comment]
I also had this problem, which only appeared in Release

**Comment by chris-nagy98** [comment]
Is there a solution for this issue occurring in `release` build mode? I am trying to profile my Flutter app with Android Profiler (by running the `android` subproject in Android release build mode) and this error keeps getting thrown, and the app directly crashes after launch: 

> A/flutter: [FATAL:flutter/runtime/dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Precompiled runtime requires a precompiled snapshot
> A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20532 (ple.flutter_app), pid 20532 (ple.flutter_app)

After running `flutter doctor` in my root project:

> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)
> • No issues found!

**Comment by nagychris** [comment]
For me the solution was changing the version of the Gradle Plugin to 
`classpath 'com.android.tools.build:gradle:3.5.4'`
