### ISSUE TITLE
Flutter doctor keeps on downloading Darts-SDK

### ISSUE THREAD

**Issue by Tinaye20** [flutter/flutter#75480]
Hello, Im using Windows 8.1 pro with  Powershell V5.0 running Flutter v1.22.6.I configured my git network  proxy and setup environment variables properly. When I run `flutter doctor`  and any other flutter command it appears like this:
![1](https://user-images.githubusercontent.com/10128995/106991261-b7827680-672a-11eb-9269-df97cf890e3a.PNG)

I tried downloading the Dart-SDK manually and extracting it to C:\src\flutter\bin\cache location but the `flutter doctor` command is creating dart-sdk.old files overriding the folder I extracted manually:
![2](https://user-images.githubusercontent.com/10128995/106991586-66bf4d80-672b-11eb-9c01-f527497a4f86.PNG)

I even tried installing dart sdk using chocolatey but still flutter is downloading its own dart sdk. Its been 4 days trying to look for a solution to no avail.

Can anyone help Im new to this Flutter Framework.

**Comment by TahaTesser** [comment]
Hi @Tinaye20 
Flutter uses its own Dart SDK, you don't need to download Dart SDK separately. 
Please follow [Windows install](https://flutter.dev/docs/get-started/install/windows) for complete installation
Hope this helps
Thank you

**Comment by Tinaye20** [comment]
Thank you for your response @TahaTesser 

I followed the instructions laid out on the flutter website. The dart-sdk file was successfully downloaded using the `flutter doctor`  command But now im incurring this **Running Pub upgrade...** process which is taking forever , its been like this for 3 hours now:
![4](https://user-images.githubusercontent.com/10128995/107030115-fc2b0380-6764-11eb-95dc-69c464a9277a.PNG)

**Comment by Tinaye20** [comment]
At @TahaTesser,I guess it pays to be patient :)
![11](https://user-images.githubusercontent.com/10128995/107033676-8033ba00-676a-11eb-83cd-8d43d5f6df05.PNG)

Thank you:)

**Comment by TahaTesser** [comment]
Hi @Tinaye20 
`flutter pub upgrade` is downloading required packages, the time to take to download it depends on your internet speed.
You're still missing the Android SDK path, please follow the instructions from the official page
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
