### ISSUE TITLE
ipa processing failed ad hoc

### ISSUE THREAD

**Issue by Adrift001** [flutter/flutter#75481]
## Environment

MacBook M1

## Steps to Reproduce

1. Run xcode archive, select Ad Hoc.
2. ipa processing failed

## Log
```
2021-02-05 03:21:07 +0000  Scanning IPA...
2021-02-05 03:21:07 +0000  Assertion failed: Expected 4 archs in otool output:
/var/folders/jk/87_370js6z9bld46ppj5q6380000gn/T/IDEDistributionOptionThinning.~~~7OiIsl/Payload/Runner.app/Frameworks/libswiftAVFoundation.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    36       3952   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS APP_EXTENSION_SAFE
Load command 0
```

**Comment by TahaTesser** [comment]
Hi @Adrift001 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/72622
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
