### ISSUE TITLE
Flutter clean should delete lock files

### ISSUE THREAD

**Issue by tryadelion** [flutter/flutter#75483]
Flutter clean should delete lock files to prevent inconsistency with what's specified in the YAML, specially if using non-versioned git references.

solves issues when referencing direct branch heads or folders, where there is no version to check against hence no update is performed on dependencies, code completion or even build process. example:

![Screenshot 2021-02-05 at 08 45 52](https://user-images.githubusercontent.com/3778474/107013103-382c8b80-679a-11eb-8f0b-deff2251bbaa.png)

submitted for my PR.

**Comment by tryadelion** [comment]
added more info on why

**Comment by jmagman** [comment]
[Dart recommends checking application pubspec.locks into source control.](https://dart.dev/guides/libraries/private-files#pubspeclock)  The tool shouldn't be dirtying the working copy on every `clean`, and would need to detect that the lock file isn't checked in.

This doesn't seem like a good idea.

**Comment by christopherfujino** [comment]
> [Dart recommends checking application pubspec.locks into source control.](https://dart.dev/guides/libraries/private-files#pubspeclock) The tool shouldn't be dirtying the working copy on every `clean`, and would need to detect that the lock file isn't checked in.

I agree, the idea of a `pubspec.lock` is to version control the exact packages that were resolved in the last stable build. Updating `flutter clean` to delete this file would affect all Flutter users using this command.

**Comment by jonahwilliams** [comment]
I don't believe this is a bug and it is not something we intended to fix. Closing.
