### ISSUE TITLE
Allow DropdownMenuItem that does not close DropdownButton

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#75487]
There is sometimes a need to add separators to `DropdownButton`'s list. One can do this by adding a `DropdownMenuItem` with `Divider` for a child, or by subclassing `DropdownMenuItem` to not be affected by items' min height. But such a separator is still tappable, and it does close the dropdown.

I propose to:
- Add some field to `DropdownMenuItem` to indicate that it is not interactive.
- Check this field in `_DropdownMenuItemButtonState._handleOnTap` and do not pop the route. Also such item should not appear as `InkWell`.

**Comment by MahmoudMehisen** [comment]
I would like to work on this if you don't mind.
Can you provide some pointers?

**Comment by pedromassangocode** [comment]
Hi @MahmoudMehisen 
I would start by reading the [contributor guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).

**Comment by werainkhatri** [comment]
I guess this issue has been resolved by the PR #76968 so it should be closed.

**Comment by PixelToast** [comment]
Closing as a duplicate of #75609, resolved by #76968
