### ISSUE TITLE
" Select all " menu in Textfield  don't work well.

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#75482]
Steps to Reproduce
```dart
 Scaffold(body: Column(children: [
      TextField()
    ],),);
```

run on below device :
![image](https://user-images.githubusercontent.com/2295872/107001353-7474e180-67c4-11eb-9e7f-f3abb77d5f8b.png)
long press textfied,paste and select all menu show,then click 'select all'.
Actual results:
![RPR](https://user-images.githubusercontent.com/2295872/107002053-a5a1e180-67c5-11eb-9ac0-24e883eeacde.gif)

flutter doctor -v:
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.21.0-9.1.pre at /Users/liuyanfeng/Library/flutter
    • Framework revision be9bc8cb39 (6 months ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/liuyanfeng/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/liuyanfeng/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[✓] Connected device (4 available)
    • JKM AL00a (mobile) • HYJNW18A15002346          • android-arm64  • Android 9 (API 28)
    • iPhone xs (mobile) • 00008020-00141D2026A1002E • ios            • iOS 13.5.1
    • Web Server (web)   • web-server                • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 88.0.4324.146

**Comment by pedromassangocode** [comment]
> • Framework revision [be9bc8c](https://github.com/flutter/flutter/commit/be9bc8cb3942bda5d8ef4e44b44616c470625e18) (6 months ago), 2020-08-18 09:46:08 -0700

You are running a six-month old version of Flutter. Please upgrade to the latest version and try again.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
