### ISSUE TITLE
Velocity tracker microbenchmark regressed

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7549]
https://github.com/flutter/flutter/commit/60847a1dedc21deeb1a10aef7918d544c95068ce resulted in a ~2x regression of the velocity tracker microbenchmark.

![velocity_tracker_regression](https://cloud.githubusercontent.com/assets/211513/22127300/392e4e4c-de50-11e6-9275-d238ede162bc.png)

To reproduce:

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/microbenchmarks.dart
```

/cc @HansMuller

**Comment by HansMuller** [comment]
#7510 restored the duration of the motion event sample from 40 back to 100ms. That's probably the source of this micro benchmark regression - we're doing a least squares fit of 2x as many events.

**Comment by yjbanov** [comment]
Should I change the expected number for this benchmark?

**Comment by abarth** [comment]
Yes, I think so.

**Comment by yjbanov** [comment]
Done.
