### ISSUE TITLE
BUG:  build step fails

### ISSUE THREAD

**Issue by tryadelion** [flutter/flutter#75490]
the build step on master seems to be failing for many PR's all at the same spot:

  Target kernel_snapshot failed: Exception
  Exception: Failed to build bundle.
  
  dart:async                                                    _Completer.completeError
  test/integration.shard/test_driver.dart 397:18                FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                       FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                    _StreamImpl.listen
  test/integration.shard/test_driver.dart 376:35                FlutterTestDriver._waitFor
  test/integration.shard/test_driver.dart 578:54                FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                       FlutterRunTestDriver._setupProcess.<fn>
  test/integration.shard/test_driver.dart 604:6                 FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 474:11                FlutterRunTestDriver.run
  test/integration.shard/vmservice_integration_test.dart 31:21  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncThenWrapperHelper
  test/integration.shard/vmservice_integration_test.dart        main.<fn>.<fn>
  
  Exception: Exception: Received app.stop event while waiting for app.debugPort event
  
  
  ===== CRASH =====
  si_signo=Bus error: 10(10), si_code=2, si_addr=0x10fc08140
  version=2.13.0-0.0.dev (dev) (Thu Feb 4 08:08:19 2021 -0800) on "macos_x64"
  pid=17426, thread=10243, isolate_group=main(0x7fedc0821a00), isolate=(nil)(0x0)
  isolate_instructions=10f081000, vm_instructions=10b82fc40
  
    pc 0x000000010bb9a917 fp 0x0000700007c95e20 dart::MarkingVisitorBase<true>::DrainMarkingStack()+0x297
    pc 0x000000010bb9b20c fp 0x0000700007c95e90 dart::ConcurrentMarkTask::Run()+0x6c
    pc 0x000000010bb6bb18 fp 0x0000700007c95f20 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
    pc 0x000000010bb6bddf fp 0x0000700007c95f50 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
    pc 0x000000010bacf435 fp 0x0000700007c95fb0 dart::ThreadStart(void*)+0xb5
    pc 0x00007fff72372109 fp 0x0000700007c95fd0 _pthread_start+0x94
    pc 0x00007fff7236db8b fp 0x0000700007c95ff0 thread_start+0xf
  -- End of DumpStackTrace
  
  Target kernel_snapshot failed: Exception
  Exception: Failed to build bundle.
  
  ex:

https://github.com/flutter/flutter/pull/75486
https://github.com/flutter/flutter/pull/75091
https://github.com/flutter/flutter/pull/75095
https://github.com/flutter/flutter/pull/75153

**Comment by godofredoc** [comment]
@tryadelion can you please rebase your PRs?

**Comment by tryadelion** [comment]
@godofredoc  my pr was cancelled/discarded,please check on the others though.

**Comment by godofredoc** [comment]
Some of the PRs have been already rebased and have been passing the test. If there are still some PRs failing the tasks please rebase.
