### ISSUE TITLE
~5x regression in the stock build microbenchmark

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7550]
https://github.com/flutter/flutter/commit/3312af7da5dffbaf6a08def1ad9d6f03e84d0d74 resulted in a ~5x regression in the https://github.com/flutter/flutter/blob/master/dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart microbenchmark.

![stock_build_regression](https://cloud.githubusercontent.com/assets/211513/22127459/c8e62b2c-de50-11e6-9fd1-517e5e5b5b5b.png)

To reproduce, connect an Android device, then:

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/microbenchmarks.dart
```

/cc @abarth

**Comment by abarth** [comment]
Ouch.  Reverting.

**Comment by abarth** [comment]
Reverted in https://github.com/flutter/flutter/pull/7552

**Comment by yjbanov** [comment]
Back to normal:

<img width="265" alt="screen shot 2017-01-19 at 11 44 36 pm" src="https://cloud.githubusercontent.com/assets/211513/22140442/611cdea4-dea1-11e6-9be3-92fc91d7fc8c.png">
