### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by UjjawalPanchal** [flutter/flutter#75503]
getting this exception for each and every plugins that I used in my project
**Unhandled Exception: MissingPluginException**

it is working in Debug and Profile mode but not in Release mode apk.

can anyone help me I need urgent help.

Thanks.

**Comment by Dararii** [comment]
I have the same problem.

**Comment by TahaTesser** [comment]
Hi @UjjawalPanchal 
Can you please provide your `flutter doctor -v` and `flutter run --release  --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang  希望能帮到你

**Comment by UjjawalPanchal** [comment]
Thanks it is resolved now.
