### ISSUE TITLE
[Flutter Desktop] Textfield does not accept accents

### ISSUE THREAD

**Issue by Bestfastfire** [flutter/flutter#75510]
On the desktop when I try to insert a letter with accents it looks as if I had pressed the button 2 times.

Ex:
```
~ + a = ã
~~ = ~~
```

But what is happening is:
`~ + a = ~~ a`

What happens:
![Gravar_2021_02_05_12_33_38_532](https://user-images.githubusercontent.com/22732544/107054252-9f543b00-67ae-11eb-87ac-a43fbfe6659b.gif)

What should happen:
![Gravar_2021_02_05_12_33_55_241](https://user-images.githubusercontent.com/22732544/107054256-a0856800-67ae-11eb-9a21-b8ffaf92ff4a.gif)

Code example:
```
TextField(
     controller: TextEditingController())
```

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-17.2.pre, on Microsoft Windows [versÃ£o 10.0.19042.746], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

• No issues found!

```

Edit:

Im using logitech k380 (en_US format) and typing pt_BR, I tried do this with virtual keyboard and works well. Probably the problem is because the keyboard is in the en_US standard and my pc is set to type pt_BR.

**Comment by Bestfastfire** [comment]
An alternative solution until this is fixed, is to put in `onChanged` to identify **~~a or ^^e**  etc. And replace the controller with the correct one, ex:

```
onChanged: (v) {
    if (v.contais ('~~a') {
         controller.text = v.replace ('~~a', 'ã');

    }
}
```

With regex I will make a better solution than comparing with all possible accents.

**Comment by HansMuller** [comment]
CC @cbracken

**Comment by cbracken** [comment]
@Bestfastfire thanks for filing! Would you mind adding detailed repro steps for this? Specifically, which keyboard/language settings are you using? Looks like your input method/keyboard are configured with `~` and `^` as dead keys, and then you type  `~a` or `^e` to get ã and ê respectively?

**Comment by Bestfastfire** [comment]
> @Bestfastfire thanks for filing! Would you mind adding detailed repro steps for this? Specifically, which keyboard/language settings are you using? Looks like your input method/keyboard are configured with `~` and `^` as dead keys, and then you type `~a` or `^e` to get ã and ê respectively?

Im using logitech k380 with lang pt_BR

**Comment by Bestfastfire** [comment]
> @Bestfastfire thanks for filing! Would you mind adding detailed repro steps for this? Specifically, which keyboard/language settings are you using? Looks like your input method/keyboard are configured with `~` and `^` as dead keys, and then you type `~a` or `^e` to get ã and ê respectively?

I tried with virtual keyboard and works well. Now that you mention it, I think the problem may be due to alternative keyboards since the k380 is in the en_US format and I'm trying to pt_BR.

**Comment by cbracken** [comment]
Thanks! Can you confirm whether this started recently or whether it's always been an issue for you?

**Comment by Bestfastfire** [comment]
> Thanks! Can you confirm whether this started recently or whether it's always been an issue for you? There have been two major Windows keyboard input related changes recently: one that deals with individual key events, another that adds support for CJK input via IMEs, either of which I could imagine impacting multi-key character input.

Sorry, I didn't notice before, I just noticed it today.

**Comment by cbracken** [comment]
No problem -- thanks for filing the issue. Will take a look!

**Comment by PavelPZ** [comment]
The same for me. I thing the problem is with every windows desktop keyboard. For web (with the same keyboard) is everything OK.

**Comment by pablohls** [comment]
The same problem for me.
When I use the virtual keyboard everything works fine, but when using the physical keyboard the error happens.
For me the error started to happen in version 1.27 of the Dev channel, in version 1.26 the error did not happen.

**Comment by PavelPZ** [comment]
@gspencergoog, is there any relation with https://github.com/flutter/flutter/issues/76121?
I have the impression that TextField for windows is a bit forgotten and it would be good to solve it globally.

**Comment by inceptusp** [comment]
> Looks like your input method/keyboard are configured with ~ and ^ as dead keys, and then you type `~a` or `^e` to get ã and ê respectively?

@cbracken that is how every physical (native) Portuguese or Spanish keyboard works (I don't know about other languages that have diacritics 'cause I've never seen other keyboards)...

I don't know about macos but this bug appears on Windows only (I've just tested on linux and it works fine), I've received some feedback from users, and I am experiencing this bug too... I am using a default Brazilian Keyboard (Português ABNT) like 99% of the users from Brazil...

**Comment by eduardo-cervantes** [comment]
Any predictions for solving this problem, or do you have any workarounds?

**Comment by alberteije** [comment]
It seems there is no solution for now?

**Comment by Bestfastfire** [comment]
> It seems there is no solution for now?

So far nothing, I am using the latest stable version of the flutter the bug continues, but it is only on this specific keyboard that I reported, it is in the EN_US standard and on windows it is set to PT_BR.

I tested it on a keyboard that is PT_BR and it worked normally

**Comment by alberteije** [comment]
> 
> 
> > It seems there is no solution for now?
> 
> So far nothing, I am using the latest stable version of the flutter the bug continues, but it is only on this specific keyboard that I reported, it is in the EN_US standard and on windows it is set to PT_BR.
> 
> I tested it on a keyboard that is PT_BR and it worked normally

Interesting, my keyboard is PT_BR (brazilian laptop) and it doesn't work. I have exactly the problem the you mentioned early.

**Comment by pablohls** [comment]
> > > It seems there is no solution for now?
> > 
> > 
> > So far nothing, I am using the latest stable version of the flutter the bug continues, but it is only on this specific keyboard that I reported, it is in the EN_US standard and on windows it is set to PT_BR.
> > I tested it on a keyboard that is PT_BR and it worked normally
> 
> Interesting, my keyboard is PT_BR (brazilian laptop) and it doesn't work. I have exactly the problem the you mentioned early.

The same for me.

**Comment by alycwb** [comment]
I have an entire application developed, but I can't release it to production because of this issue. Any ETA to fix this bug?

**Comment by ReniDelonzek** [comment]
If anyone needs an urgent fix to release (since the bug has been around for a long time and an official fix hasn't been released yet), I've made this ugly fix so it can work. I created a custom input and replaced it with the default one, then added that to my onChange.

```
if (UtilsPlatform.isWindows) {
    int pos = controller.selection.start;
    String newValue = value
        // A
        .replaceAll('´´a', 'á')
        .replaceAll('``a', 'à')
        .replaceAll('^^a', 'â')
        .replaceAll('~~a', 'ã')
        .replaceAll('´´A', 'Á')
        .replaceAll('``A', 'À')
        .replaceAll('^^A', 'Â')
        .replaceAll('~~A', 'Ã')
        // E
        .replaceAll('´´e', 'é')
        .replaceAll('``e', 'è')
        .replaceAll('^^e', 'ê')
        .replaceAll('´´E', 'É')
        .replaceAll('``E', 'È')
        .replaceAll('^^E', 'Ê')
        // I
        .replaceAll('´´i', 'í')
        .replaceAll('``i', 'ì')
        .replaceAll('^^i', 'î')
        .replaceAll('´´I', 'Í')
        .replaceAll('``I', 'Ì')
        .replaceAll('^^I', 'î')
        // O
        .replaceAll('´´o', 'ó')
        .replaceAll('``o', 'ò')
        .replaceAll('^^o', 'ô')
        .replaceAll('~~o', 'õ')
        .replaceAll('´´O', 'Ó')
        .replaceAll('``O', 'Ò')
        .replaceAll('^^O', 'Ô')
        .replaceAll('~~O', 'Õ')
        // U
        .replaceAll('´´u', 'ú')
        .replaceAll('``u', 'ù')
        .replaceAll('^^u', 'û')
        .replaceAll('´´U', 'Ú')
        .replaceAll('``U', 'Ù')
        .replaceAll('^^U', 'Û');

    /// Makes the cursor stay in the correct place
    pos -= (value.length - newValue.length);
    if (pos > newValue.length) {
      pos = newValue.length;
    }
    controller.selection =
        TextSelection.fromPosition(TextPosition(offset: pos));
    onChanged(newValue);
  } else {
    onChanged(value);
  }
```

It's not the best solution, and I haven't checked every possible character with accents, but it works fine for me.

**Comment by alycwb** [comment]
Tks ReniDelonzek, I will try that!

**Comment by SalahAdDin** [comment]
I'm having this bug with mobile applications.

**Comment by marcoprodata** [comment]
Any news about this bug?

**Comment by nero-angela** [comment]
> I'm having this bug with mobile applications.

mobile issue https://github.com/flutter/flutter/issues/59541
