### ISSUE TITLE
[Samsung][One UI 3] : Screen flickers on keyboard opening/closing and there is additional offset on top of the keyboard

### ISSUE THREAD

**Issue by lotusgate** [flutter/flutter#75520]
1. Almost every time the keyboard opens/closes, the whole screen flickers. 
2. When the keyboard is opened, although the scaffold takes all of the available space, its body doesn't - there is empty space below the content, as seen in the example. I noticed that locking and unlocking the phone makes that padding disappear.

OS:
Android 11, One UI 3 (Samsung device)

Flutter doctor:
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.789], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

Video example:
https://user-images.githubusercontent.com/35681808/106921957-2ead1000-6715-11eb-93d9-bdf42e02094d.mp4

Code for the example:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: KeyboardTest(),
    );
  }
}

class KeyboardTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.purple,
      appBar: AppBar(title: Text('Hello')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Container(height: 200, width: 200, color: Colors.pink),
          TextField(
            decoration: const InputDecoration(
              border: InputBorder.none,
              filled: true,
              fillColor: Colors.green,
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by lotusgate** [comment]
> @lotusgate, this is the repo for documentation issues on flutter.dev. This is an issue with Flutter behavior. I'm moving this to the flutter/flutter repo.

Oops, my bad. 😅

**Comment by darshankawar** [comment]
@lotusgate 
Although I don't have Android 11 Samsung device, I tried your code on Samsung S10 device but didn't notice the issue.


https://user-images.githubusercontent.com/67046386/107183568-0a974a80-6a05-11eb-9bab-4ee5468fc0a1.mp4

Can you provide your complete `flutter doctor -v` ?


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

</details>

**Comment by lotusgate** [comment]
I don't think this has happened before updating my Samsung S10E. The android 11 emulator is fine. So One UI 3.0 might be the issue.
Also, just in case this was somehow caused by the samsung keyboard, I installed gboard, but the bug persists.

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.789], locale en-US)
    • Flutter version 1.22.6 at C:\Languages\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Programs\Android_SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Programs\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\hrist\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • SM G970F (mobile) • RF8M31LTVNP • android-arm64 • Android 11 (API 30)
```

**Comment by darshankawar** [comment]
@lotusgate 
I'll try to upgrade my S10 to 11 and verify to confirm.

**Comment by darshankawar** [comment]
It seems that the S10+ device I've isn't yet compatible to upgrade to One UI 3.0, so I am unable to verify this issue.
Keeping this open for further investigation.

**Comment by nikssj** [comment]
Wow I was like wtf is going on with my project/keyboard?

Can confirm this issue happens for me too on:

Stable: 1.22.5
Device: Samsung Note 20
OS: Android 11 UI 3.0

**Comment by lotusgate** [comment]
With Flutter 2.0 the issue seems to have disappeared. Here is how the project behaves now:

https://user-images.githubusercontent.com/35681808/110210404-3b4e9080-7e9a-11eb-8ca3-6263b777e43c.mp4

If @nikssj or someone else confirms everything is ok with them too, the issue can be closed I think.

**Comment by XF9** [comment]
The current android update for my S10 solved this issue for me.
