### ISSUE TITLE
Generate DevTools deep links for failed network requests

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#75539]
Currently, deep links are only supported for renderflex overflow errors. We'd like to support deep links for more than just layout errors, and show them also for network related errors.

**Comment by goderbauer** [comment]
@kenzieschmoll Do you need help from the framework team for this? If so, could you provide some details on what would need to be implemented?

**Comment by kenzieschmoll** [comment]
This work is no longer a priority. We can reopen this issue if we decide to do this in the future.
