### ISSUE TITLE
flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory> 

### ISSUE THREAD

**Issue by Abenezerfikadu** [flutter/flutter#75557]
### after using this command, I get a white screen when I open it on mobile, my code works fine in debug, and without this command.

> android\app\build.gradle

```
buildTypes {
       release {
            signingConfig signingConfigs.release
       }
   }
```
> Flutter doctor -v
```

C:\Users\abene>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\abene\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\abene\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\abene\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • SM G928A (mobile) • 06157df6d5c23023 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by darshankawar** [comment]
@Abenezerfikadu 
Provide `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify the issue.

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> Provide `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify the issue.
https://github.com/flutter/flutter/issues/75557#issue-802694947

**Comment by darshankawar** [comment]
@Abenezerfikadu 
Your code sample has lot of 3rd party and customized code. We would need a complete minimal code sample (without 3rd party code) that we can directly copy paste and run in IDE to see the issue.

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> Your code sample has lot of 3rd party and customized code. We would need a complete minimal code sample (without 3rd party code) that we can directly copy paste and run in IDE to see the issue.

which means obfuscate command didn't work for flutter packages

**Comment by darshankawar** [comment]
@Abenezerfikadu 
That's fine, but we would need a reproducible use case to investigate and identify the issue. Please provide one that we can use and run the command to properly address your issue.


> @Abenezerfikadu
> Your code sample has lot of 3rd party and customized code. We would need a complete minimal code sample (without 3rd party code) that we can directly copy paste and run in IDE to see the issue.

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> That's fine, but we would need a reproducible use case to investigate and identify the issue. Please provide one that we can use and run the command to properly address your issue.
> 
> > @Abenezerfikadu
> > Your code sample has lot of 3rd party and customized code. We would need a complete minimal code sample (without 3rd party code) that we can directly copy paste and run in IDE to see the issue.

 maybe someone will fix this issue, who knows flutter properly. your asking is not the problem of the command.

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> That's fine, but we would need a reproducible use case to investigate and identify the issue. Please provide one that we can use and run the command to properly address your issue.
> 
> > @Abenezerfikadu
> > Your code sample has lot of 3rd party and customized code. We would need a complete minimal code sample (without 3rd party code) that we can directly copy paste and run in IDE to see the issue.

also after the build, I can see the splash screen correctly, but after that, I get a white screen.

**Comment by darshankawar** [comment]
@Abenezerfikadu 
Does the `symbols` folder generate when you run the command `flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>` ?
What do you pass in `<project-name>/directory` ?

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> Does the `symbols` folder generate when you run the command `flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>` ?
> What do you pass in `<project-name>/directory` ?

 `flutter build apk --obfuscate --split-debug-info=some_parent_directory/some_child_directory`

**Comment by darshankawar** [comment]
@Abenezerfikadu 
My question was, does the command generate `symbols` directory in the path you provided ?

**Comment by Abenezerfikadu** [comment]
> @Abenezerfikadu
> My question was, does the command generate `symbols` directory in the path you provided ?

yeah

**Comment by darshankawar** [comment]
@Abenezerfikadu 
As requested earlier before as well, we would need a complete minimal reproducible code sample that we can copy paste and run in IDE to see the issue. Without code sample, we will just keep running around the bush. Provide a code sample that we can use to verify the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
