### ISSUE TITLE
PWA crash in iphone older IOS version when using obscure: true 

### ISSUE THREAD

**Issue by MahdiGharooni** [flutter/flutter#75551]
I publish a Flutter application in the **Android and PWA** version. All features are fine but in my forms when I use **obscure: true** for my password text fields, the application crash and can't perform correctly. I see this problem in the **older versions of IOS like 9 or 8** but in the new version of IOS, there isn't any problem.

**Comment by MahdiGharooni** [comment]
I couldn't find a solution but I finally solved the problem with some changes, I'm sure it is not the best solution.

I wrote my custom textField to handle obscure feature, I check the **os type** and **browser type** to handle my text field: 

> class PasswordTextFormField extends StatefulWidget {
  final TextEditingController controller;
  final bool enabled;
  final AutovalidateMode autoValidateMode;
  final bool ignoreValidation;
  final String labelText;
  final String hintText;
  final VoidCallback showSelectionDialog;
  final FocusNode focusNode;
  final VoidCallback onEditingComplete;
  final FormFieldValidator<String> validator;
  final TextInputType keyboardType;
  final int maxLength;
  final TextDirection textDirection;
  final TextDirection hintTextDirection;
  final String counterText;
  final bool obscureText;
  final ValueChanged<String> onChanged;
  PasswordTextFormField({
    @required this.controller,
    this.enabled = true,
    this.ignoreValidation,
    this.labelText,
    this.showSelectionDialog,
    this.focusNode,
    this.hintText,
    this.onEditingComplete,
    this.validator,
    this.keyboardType = TextInputType.number,
    this.maxLength,
    this.autoValidateMode = AutovalidateMode.onUserInteraction,
    this.textDirection = TextDirection.ltr,
    this.hintTextDirection = TextDirection.ltr,
    this.counterText = '',
    this.obscureText = true,
    this.onChanged,
  });
  @override
  State<StatefulWidget> createState() => _PasswordTextFormFieldState();
}


> class _PasswordTextFormFieldState extends State<PasswordTextFormField> {
  String _value = '';
  final TextEditingController _textEditingController = TextEditingController();
  final platform = ph.getPlatform();
  var browser;
  @override
  void initState() {
    super.initState();
    widget.controller.addListener(() {
      if (widget.controller.text.isNotEmpty) {
        _textEditingController.text = '';
        for (int _i = 0; _i < widget.controller.text.length; _i++) {
          _textEditingController.text += '•';
        }
        _value = widget.controller.text;
      }
    });
    if (platform == ph.PlatformType.web) {
      browser = ph.Browser();
    }
  }
  @override
  Widget build(BuildContext context) {
    /// Safari
    if (platform == ph.PlatformType.web && browser.browser == 'Safari') {
      return TextFormField(
        autovalidateMode: widget.autoValidateMode,
        onEditingComplete: widget.onEditingComplete,
        focusNode: widget.focusNode,
        enabled: widget.enabled,
        textDirection: widget.textDirection,
        keyboardType: widget.keyboardType,
        controller: _textEditingController,
        validator: (value) => widget.validator?.call(value),
        maxLength: widget.maxLength,
        textInputAction: TextInputAction.next,
        obscureText: false,
        maxLines: 1,
        onChanged: (value) async {
          if (value.isNotEmpty) {
            // when value has only dot, it means user remove characters
            if (RegExp(r'^(•){0,}$').hasMatch(value)) {
              int _baseOffset = _textEditingController.selection.baseOffset;
              // offset of changed character
              int _deletedCount = _value.length - value.length;
              String _part1 = _value.substring(0, _baseOffset);
              String _part2 = _value.substring(_baseOffset + _deletedCount);
              _value = _part1 + _part2;
              _textEditingController.text = '';
              for (int _i = 0; _i < _value.length; _i++) {
                _textEditingController.text += '•';
              }
            } else {
              // add a character and replace it with a dot
              _textEditingController.text = '';
              _value = _value + value.replaceAll('•', '');
              for (int _i = 0; _i < _value.length; _i++) {
                _textEditingController.text += '•';
              }
            }
          } else {
            // when user delete all characters
            _value = '';
            _textEditingController.text = '';
          }
          widget.controller.text = _value;
          // move cursor to end of text
          _textEditingController.selection = TextSelection.fromPosition(
            TextPosition(offset: _textEditingController.text.length),
          );
        },
        decoration: InputDecoration(
          labelText: widget.labelText,
          hintText: widget.hintText,
          hintTextDirection: widget.hintTextDirection,
          counterText: widget.counterText,
        ),
      );
    } else {
      /// android, chrome & others
      return TextFormField(
        autovalidateMode: widget.autoValidateMode,
        onEditingComplete: () {
          widget.onEditingComplete?.call();
        },
        focusNode: widget.focusNode,
        enabled: widget.enabled,
        textDirection: widget.textDirection,
        keyboardType: widget.keyboardType,
        controller: widget.controller,
        validator: (value) => widget.validator?.call(value),
        maxLength: widget.maxLength,
        textInputAction: TextInputAction.next,
        obscureText: widget.obscureText,
        maxLines: 1,
        onChanged: (value) async {
          widget.onChanged?.call(value);
        },
        decoration: InputDecoration(
          labelText: widget.labelText,
          hintText: widget.hintText,
          hintTextDirection: widget.hintTextDirection,
          counterText: widget.counterText,
        ),
      );
    }
  }
}


For checking os and browser type you can use flutter packages.

**Comment by TahaTesser** [comment]
Hi @MahdiGharooni 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by MahdiGharooni** [comment]
I'm working on **master channel** and it seems doesn't have any problem.

> [√] Flutter (Channel master, 1.26.0-18.0.pre.212, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.26.0-18.0.pre.212 at C:\src\flutter
    • Framework revision 02d441ea55 (2 days ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\programming\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

> [√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

> [√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

> [√] Connected device (2 available)
    • HTC One M9PLUS (mobile) • FA6ACBD00060 • android-arm64  • Android 5.0.2 (API 21)
    • Chrome (web)            • chrome       • web-javascript • Google Chrome 88.0.4324.146

> • No issues found!

**Comment by TahaTesser** [comment]
Hi @MahdiGharooni 
Can you please provide which version of Flutter had this issue for you before you upgrade to `master`?
Thank you

**Comment by MahdiGharooni** [comment]
I was in the `master` branch but I don't know exactly the Flutter version. It was about **1 month ago** and think the version was `1.22.5` or `1.22.4`.

**Comment by TahaTesser** [comment]
Hi @MahdiGharooni 
That sounds like a quite old `master` branch, it is even lower than the current `stable`
if you can reproduce the issue on the` stable` channel, please comment below, otherwise, this looks it's been fixed
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
