### ISSUE TITLE
Flutter not working on Mac stuck at building tool 

### ISSUE THREAD

**Issue by anooppoommen** [flutter/flutter#75563]
I Recently ran the flutter upgrade command on my Mac 
and even after waiting for half a day the tool is stuck 
on building flutter tool. I tried removing the flutter installation with a fresh install and 
the problem still persists. can't even get the output of flutter doctor 

os version: Mac OS Catalina 10.15.7

## Logs

<details>
<summary>Logs</summary>

```
flutter doctor -v
Building flutter tool...
```

</details>

**Comment by TahaTesser** [comment]
Hi @anooppoommen 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by anooppoommen** [comment]
@TahaTesser can't get an output from the `flutter doctor -v` just shows Building flutter tool...

**Comment by TahaTesser** [comment]
Hi @anooppoommen 
Is that after the upgrade? I meant `fluter doctor -v` before you upgrade `fluter upgrade`, which version were you trying to upgrade from? which channel?


Can you try the following commands
`flutter channel stable`
`flutter upgrade -f` (force upgrade)
`flutter doctor -v`

Thank you
