### ISSUE TITLE
Nothing to repeat at Regex

### ISSUE THREAD

**Issue by sushilbalami** [flutter/flutter#75561]
I am using Regex this way
```
  var str = "r\(.*?;.*?\)(*SKIP)(*F)|;"; 
  RegExp _regExp = RegExp(str);
  html = html.replaceAllMapped(_regExp, (Match m) => ";\n");
```
Tried by putting 
` "r\\(.*?;.*?\\)(*SKIP)(*F)|;"; `
but cannot be resolved.
working well while testing see here: https://regex101.com/r/x63m3p/1
how to resolve it. any bug or I couldn't figure out.

**Comment by iapicca** [comment]
@sushilbalami 
this seems an issue with [dart](https://dart.dev/) rather than `flutter`,
please open an issue in the dedicated [github](https://github.com/dart-lang/sdk/issues)

**Comment by stuartmorgan** [comment]
It's not a Dart issue either; you're using a non-standard regex syntax. See https://stackoverflow.com/questions/24534782/how-do-skip-or-f-work-on-regex

**Comment by sushilbalami** [comment]
Worked on regex101 
I think escaped character giving problem... 
Any one know?

**Comment by stuartmorgan** [comment]
> Worked on regex101

Because you have the flavor set to PCRE, which is, as the link I provided says, one of the only implementations that supports that syntax.

They changing it to any of the other options and see what happens.
