### ISSUE TITLE
Android permission with API level 30

### ISSUE THREAD

**Issue by legyes** [flutter/flutter#75573]
AndroidManifest.xml should contain:
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

Please add to the readme. Thank you.

**Comment by iapicca** [comment]
@legyes 
can you provide details for this issue as indicated in the [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=)

>[...]
> ## Use case
> 
> 
> 
> ## Proposal
> 
> 
>

**Comment by hammyofmha** [comment]
[https](http://Admin@192.168.1.35:8000/)

**Comment by legyes** [comment]
With "targetSdkVersion 30" and Android 11, but without "QUERY_ALL_PACKAGES" permission, the plugin gives "no_avaiable_camera" exception. It's hard to find what the problem is. So, the readme should contain this information.

**Comment by legyes** [comment]
## Use case

Android 11 and targetSdkVersion=30 causes "no_avaiable_camera" Exception. It's hard to find the solution as a newbie. 

My suggestion is related to the problem, it helps for developers with useful information. The problem is the Android API level 29+, because permission managements are changed. 

Package and Flutter/Dart updates doesn't help. 

This information is useful, when somebody uses this plugin, so please add into the readme:  

On Android 11 and targetSdkVersion 30 place this code into the AndroidManifest:
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`
to access the camera.

## Proposal

This plugin is provided by pub.dev. It isn't a code bug, it is a documented change by Android developers, but it's hard to find the proper usege syntax.

**Comment by TahaTesser** [comment]
Hi @legyes 
When targetting API 30 and running Android 11 device (Oneplus 8) on the latest `camera: ^0.7.0+2` on the `stable` channel using the official example WITHOUT using `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

When reading https://developer.android.com/about/versions/11/privacy/package-visibility, I don't see any relevance to `camera` package

Cameras are detected, no exceptions
```bash
I/Camera  (22988): [FPS Range Available] is:[15, 15]
I/Camera  (22988): [FPS Range Available] is:[8, 30]
I/Camera  (22988): [FPS Range Available] is:[30, 30]
I/Camera  (22988): [FPS Range] is:[8, 30]
```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```

</details>

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
