### ISSUE TITLE
Black screen problem

### ISSUE THREAD

**Issue by Godfather6666** [flutter/flutter#75577]
Hello, I found that my APP would appear black screen and could not be operated after staying in the background for too long. I would like to ask whether it is possible to restart it when this happens.

**Comment by Godfather6666** [comment]
![Uploading 89A73173D580CFA17D1B5CE0E89D26A9.jpg…]()

**Comment by Godfather6666** [comment]
After testing, we found this problem. Could you please help us to have a look?

**Comment by iapicca** [comment]
@Godfather6666 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

> Uploading 89A73173D580CFA17D1B5CE0E89D26A9.jpg…

also the image you meant to upload isn't visible

**Comment by pedromassangocode** [comment]
Hi @Godfather6666 
Can you please provide what was asked in https://github.com/flutter/flutter/issues/75577#issuecomment-774677378?
Thank you

**Comment by Godfather6666** [comment]
Thank you, I have found the reason for the black screen, you can close this problem.

**Comment by Erenyang** [comment]
> Thank you, I have found the reason for the black screen, you can close this problem.

met same problem，could you tell me how to solve it？
