### ISSUE TITLE
Image Picker Crashing on Second Click

### ISSUE THREAD

**Issue by buzzicards** [flutter/flutter#75575]
Image Picker always crashing on second Click

```
ClipOval(
                    child: Material(
                      color: Colors.blue, // button color
                      child: InkWell(
                        // splash color
                        splashColor: Colors.green,
                        onTap: () async {
                          //final picker = ImagePicker();
                          // PickedFile pickedFile =
                          try {
                            var image = await ImagePicker()
                                .getImage(source: ImageSource.gallery);
                            imageFile = File(image.path);

                            setState(() {
                              if (imageFile != null) {
                                uploadFile(imageFile);
                              }
                            });
                          } catch (ex) {
                            print(ex);
                          }
                        }, // button pressed
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Icon(Icons.edit,
                                size: SizeConfig.safeBlockHorizontal * 6),
                          ],
                        ),
                       ),
                    ),
                  ),

```
Seems its ongoing issue but not seen solution.... Please help

**Comment by mjmon** [comment]
I had the issue today of ios. I fixed it by adding the following into the `info.plist` as suggested by the documentation

```
	<key>NSPhotoLibraryUsageDescription</key>
	<string>${PRODUCT_NAME} would like to access your photo gallery for your profile photo and post photo upload.</string>
	<key>NSCameraUsageDescription</key>
	<string>${PRODUCT_NAME} require access to capture pictures for your profile photo and post photo upload.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>${PRODUCT_NAME} library Usage - require access  to capture audio</string>
```

**Comment by NarHakobyan** [comment]
it always happens the app is running on the simulator

**Comment by buzzicards** [comment]
> I had the issue today for iOS. I fixed it by adding the following into the `info.plist` as suggested by the documentation
> 
> ```
> 	<key>NSPhotoLibraryUsageDescription</key>
> 	<string>${PRODUCT_NAME} would like to access your photo gallery for your profile photo and post photo upload.</string>
> 	<key>NSCameraUsageDescription</key>
> 	<string>${PRODUCT_NAME} require access to capture pictures for your profile photo and post photo upload.</string>
> 	<key>NSMicrophoneUsageDescription</key>
> 	<string>${PRODUCT_NAME} library Usage - require access  to capture audio</string>
> ```

I have that but still same issue...

**Comment by buzzicards** [comment]
> it always happens the app is running on the simulator

I guess never really paid attention... is there a work around this?

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/67430

**Comment by NarHakobyan** [comment]
> > it always happens the app is running on the simulator
> 
> I guess never really paid attention... is there a work around this?

Nope, we are using an android device for development, sorry it's crashing not in simulation but in every IOS device which runs on debug mode

**Comment by darshankawar** [comment]
@NarHakobyan 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
