### ISSUE TITLE
Add web support to flutter package_info

### ISSUE THREAD

**Issue by harsimranmaan** [flutter/flutter#75574]
## Use case
I am running flutter app in Chrome and cannot display the info about the app. Since, package_info does not support web, I see the following error.

```
Error: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
    at Object.throw_ [as throw] (http://localhost:52707/dart_sdk.js:5331:11)
    at MethodChannel._invokeMethod (http://localhost:52707/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
```

Sample code
```
final packageInfo = await PackageInfo.fromPlatform();
final appName = packageInfo.appName;
final version = packageInfo.version;
```

## Proposal

Add web support to package_info.

I can use an alternative to supply the package info inline using a flag for web until the package can provide it but it would be really nice to get this work across platforms.

**Comment by darshankawar** [comment]
@harsimranmaan 
There's [package_info_plus](https://pub.dev/packages/package_info_plus) plugin that supports web implementation. A [similar](https://github.com/flutter/flutter/issues/46609#issuecomment-707934235) proposal was closed in favor of above plugin, so you may try that plugin and see if it works for you.
Closing from here for now.
