### ISSUE TITLE
TextField Label/Placeholder should be of type Widget rather than String

### ISSUE THREAD

**Issue by preetshah21699** [flutter/flutter#75580]
## Use case
It is not a major problem but awfully convenient to be able to format the text in the label/placeholder of a TextField. Like [this](https://i.stack.imgur.com/dWc4h.gif).

## Proposal

So, instead of taking them as String, we should take a Widget as a parameter for label/placeholder. It would also allow developers to use icons and other visually pleasing widgets over there.

**Comment by pedromassangocode** [comment]
> It is not a major problem but awfully convenient to be able to format the text in the label/placeholder of a TextField. Like [this](https://i.stack.imgur.com/dWc4h.gif).

I think this is currently possible with `labelStyle` of the `InputDecoration` class. 

> So, instead of taking them as String, we should take a Widget as a parameter for label/placeholder. It would also allow developers to use icons and other visually pleasing widgets over there.

I don't think this is a valid proposal as it will make de codebase too much complex and hard to maintain (breaking changes, deprecation).

**Comment by preetshah21699** [comment]
@pedromassangocode if you could share your solution for it, I would be happy. But as I said, it is not a problem but it would be convenient to be take in RichText as input rather than the String directly. With respect to maintaining the codebase, yes it will be a problem. But a lot of them want to be able to format their text.
However, if you could give an example for your workaround, it would be great as well.
