### ISSUE TITLE
ios release mode Bug !!!

### ISSUE THREAD

**Issue by akedevsiph** [flutter/flutter#75586]
Token Not register when app Up 
But kill app then open again It works !!
What wrong Guys

**Comment by iapicca** [comment]
@akedevsiph 
can you provide your `flutter doctor -v`, your `flutter run --release -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment]
Hi @akedevsiph 
Are you using Firebase or Google sign in?
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
