### ISSUE TITLE
Dismissable is too difficult to swipe on iOS

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#7559]
If you try to swipe a dismissable before the scrolling completely stops, you cause a bit more scroll. Try again and you cause a bit more scroll and so on. It seems:

- Scroll decay is much longer on iOS than Android.
- Any swipe action with a vertical component is being considered a scroll unless the scroll completely stops.

**Comment by mehmetf** [comment]
See https://drive.google.com/open?id=0ByNIo5jv3coeWDBtMFhJSFEydVE for a demo [only visible to google.com]

**Comment by Hixie** [comment]
Specifically what's going on is that while the scrollable is scrolling, you can't interact with the contents at all. The only gesture in the arena is the scroll gesture. If you tap the screen then you'll stop the scroll and then you can dismiss.

This is supposed to match native platforms. Is that not what they do?

**Comment by abarth** [comment]
> This is supposed to match native platforms. Is that not what they do?

I just tested this behavior on my iPhone, and qualitatively the behavior is the same.  However, the "feel" of the behavior is different.  I think what's going on is that we have too low a min-velocity threshold for ballistic scrolling.  If we raise the min-velocity, many of the interactions in the video won't trigger ballistic scrolling and so the horizontal swipes will be immediately available.

**Comment by mehmetf** [comment]
The same thing applies for scale gesture as well, perhaps not surprisingly. Chart scaling is difficult to trigger on iOS.

**Comment by eseidelGoogle** [comment]
According to leafy this is their top issue with flutter as of this afternoon.

**Comment by eseidelGoogle** [comment]
@HansMuller may have fixed this?

**Comment by eseidelGoogle** [comment]
When I last asked @mehmetf for his team's bug priorities, this was at the top.  Although my understanding from more recent discussions is that https://github.com/flutter/flutter/issues/8735 is also up there.

**Comment by abarth** [comment]
My understanding is that this issue is fixed.  If it's not fixed, please re-open and help me understand what's being requested here.
