### ISSUE TITLE
[web] Problematic folder name "icons"

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#75598]
Flutter Web places its icons into a folder named `icons`. The problem is that many standard Apache installations use this folder name as an alias* to its own icon directory, see https://electrictoolbox.com/apache-icons-directory/, making it unavailable for a Flutter Web app hosted in such an environment.

\* it's located in the `httpd-autoindex.conf` file.

It would be advisable to change this folder name to something else.

**Comment by yjbanov** [comment]
Flutter default icons don't have to go into the `icons/` directory. They can be moved or deleted. They are there only for ease of bootstrapping a simple app. Also, Apache can be configured to either provide the same icons that Flutter expects, or to use a different alias. I'm not sure we can accommodate all possible HTTP server configurations out there, so we'll keep it as is.
