### ISSUE TITLE
Allow DropDownMenuItem to be disabled.

### ISSUE THREAD

**Issue by chitgoks** [flutter/flutter#75609]
Have a property for DropDownMenuItem to be disabled or not

Doing this, item wont be selected if user selects on a disabled item.

This is very useful in showing tree like dropdown with parent and child where parent cannot be clicked.

**Comment by pedromassangocode** [comment]
Hi @chitgoks 
This seems to be currently possible now. Here is a screenshot of the API docs

![Screen Shot 2021-02-08 at 09 30 10](https://user-images.githubusercontent.com/67424416/107194378-3f4cd700-69f0-11eb-89e3-550fdb7757ef.png)

**Comment by chinmoy12c** [comment]
Related issue #75487

**Comment by werainkhatri** [comment]
I would like to work on this issue.
