### ISSUE TITLE
Ubuntu 20.04 command flutter sdk-path hangs, never completes

### ISSUE THREAD

**Issue by DarraghOFlaherty** [flutter/flutter#75601]
I installed flutter using `sudo snap install flutter --classic`

After installing I ran `flutter sdk-path` 

I get the following
![image](https://user-images.githubusercontent.com/10475290/107162374-7b554d00-699a-11eb-92fb-8fb3225397e5.png)

It then continues to hang on `Building flutter tools...` indefinitely 

I'm on my home network and not in china so it not a VPN/Firewall issue

**Comment by DarraghOFlaherty** [comment]
After about 30 mins the following appears

![image](https://user-images.githubusercontent.com/10475290/107163471-911a4080-69a1-11eb-8f4b-894dc0308371.png)

**Comment by TahaTesser** [comment]
Hi @DarraghOFlaherty 
Can you remove uninstall snap Flutter and try the [manual installation ](https://flutter.dev/docs/get-started/install/linux#install-flutter-manually)
```bash
sudo snap remove --purge flutter
rm -rf ~/snap/flutter
```
Thank you

**Comment by DarraghOFlaherty** [comment]
Hi, @TahaTesser thanks for your response,

Unfortunately, it is the exact same outcome 
![image](https://user-images.githubusercontent.com/10475290/107206434-f2203380-69f6-11eb-8a52-7eb7048e3ad0.png)

**Comment by TahaTesser** [comment]
Hi @DarraghOFlaherty 
Do you mind if I ask which country are you from? Are you using corporate internet? 
This looks like an issue for you in your environment? Are you using VM or boot?
Thank you

**Comment by DarraghOFlaherty** [comment]
@TahaTesser no problem, I live in Ireland and I'm just using my home personal network. I'm not using a VM or boot.

To give a little more backstory, I had Flutter running on Ubuntu 18.04 on this machine, I then had an unrelated issue with the kernel where I was forced to reinstall the OS, I decided to upgrade to Ubuntu 20.04 and now I can no longer install Flutter

**Comment by TahaTesser** [comment]
Hi @DarraghOFlaherty 
This looks like an environment issue, can you please reinstall your OS, it's hard to pinpoint any issue related to Flutter her.
If it isn't a restricted network and you mentioned it was running, it could be local issue
Thank you

**Comment by DarraghOFlaherty** [comment]
@TahaTesser I fresh installed Ubuntu 20.04 this morning and it has solved my issues. Thanks for your help and your time I will close the issue now
