### ISSUE TITLE
Flutter ignores Android low memory events

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7561]
This may be the root cause of https://github.com/flutter/flutter/issues/7560 and is also mentioned in internal bug 34098075 affecting customer: leafy.

Presumably we need to expose a "please clear your caches" callback from the engine up to the framework and have the framework know how to use it.

My recollection is that we also might just have some never-clearing caches in the framework to fix too.

**Comment by mehmetf** [comment]
This is definitely higher priority than #7560. Both platforms (iOS/Android) will ask apps to cleanup resources:

https://developer.android.com/reference/android/content/ComponentCallbacks2.html#onTrimMemory(int)
https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623063-applicationdidreceivememorywarni

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/6500 and https://github.com/flutter/flutter/issues/3006 are also related.  The latter is likely a dupe.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/3568.

**Comment by eseidelGoogle** [comment]
leafy currently feels blocked on this bug.  They could write their own plugin, but given we have other plumbing for existing notifications @DaveShuckerow expressed that this seems it would make more sense to come in via Flutter's engine.  Thoughts?

**Comment by DaveShuckerow** [comment]
Some additional conversation on the topic:

> there's a lifecycle event
> https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html
> https://docs.flutter.io/flutter/widgets/WidgetsBinding/addObserver.html is how you subscribe to these events
> look at the implementation of WidgetsApp for an example
> https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/app.dart

We think it would be good if our hooks into the OS were organized consistently in a fashion similar to this.

**Comment by eseidelGoogle** [comment]
@jason-simmons would you be able to look at this?

**Comment by eseidelGoogle** [comment]
Discussed with @jason-simmons and @Hixie offline.  My understanding from that discussion was that onTrimMemory was believed to be relatively uncommon vs things like onSaveInstanceState or onPause. (In part because my understanding is there are many times your app can be killed w/o it being called.)  I searched internal google app code and found the data seemed to agree at 8x and 16x more common for the latter two respectively than the former.  Donno?

Both agreed that we definitely needed better lifecycle support exposed from the engine and implemented in the framework than we have, and @Hixie agreed to write up a proposal this week of an improved shared lifecycle api which we can expose to the framework and implement for iOS and android.

@mehmetf Let us know if that does not sound like it's moving towards answering your concern, or you have additional data about the specific need for onTrimMemory exposure?

**Comment by Hixie** [comment]
Ok here's what I've learnt:

iOS has shouldSaveApplicationState / shouldRestoreApplicationState.
Android has onSaveInstanceState / onRestoreInstanceState.

It's not clear to me when shouldRestoreApplicationState and onRestoreInstanceState are invoked relative to when the Dart VM starts up. Is it predictable?

**Comment by mehmetf** [comment]
Two parts to that question:

- onTrimMemory vs onSaveInstanceState
An app can be killed for many reasons including low memory. So, a good app would save state (as discussed in #7560) but a really good app should handle both. No matter how much state you save, it is nearly impossible to achieve the feel of an app that was never killed in the first place.

- Moving in the right direction
A better lifecycle support and communication of platform callbacks to Flutter layer is indeed the right solution. One of these channels should communicate the low memory state to the app which will resolve this issue.

**Comment by mehmetf** [comment]
As part of P1 cleanup on our side, could we get an ETA on this? It would be great to have this in the next week or so.

**Comment by eseidelGoogle** [comment]
I spoke with @Hixie about this just this afternoon.

@jason-simmons is busy until Weds, but perhaps we can wire up the Android side then? Maybe @cbracken can wire up the iOS side?  @Hixie has volunteered to do any framework plumbing once either of those are in.

@Hixie would you be willing to coordinate with @cbracken and @jason-simmons on the above?

**Comment by Hixie** [comment]
Happy to coordinate whatever needs coordinating. The plan is to add an `onMemoryPressure` VoidCallback to the Window class. The pattern to do this kind of thing is established.

**Comment by mehmetf** [comment]
Could we get an update on this please?

**Comment by eseidelGoogle** [comment]
@jason-simmons is working on this as we speak.

**Comment by eseidelGoogle** [comment]
iOS side was added in https://github.com/flutter/engine/commit/642e325f83f0df98939cf5fe8b257b9660cdaf3c

**Comment by eseidelGoogle** [comment]
Framework side was landed in https://github.com/flutter/flutter/commit/054b5669152acfe8c86620342c78a979fdd76434

**Comment by eseidelGoogle** [comment]
Looks like this is the new API:
https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver/didHaveMemoryPressure.html

@jason-simmons should we resolve this?

@mehmetf this should be available next time Flutter is released into Google3.  We're currently blocked on the Dart release but that should be resolved this week and then there will be a series of rolls to catch up (as we're a little behind).  Reach out to @tvolkert if you need more infos.

**Comment by jason-simmons** [comment]
Marking this as complete
