### ISSUE TITLE
[Discussion] Flutter should have providers / dependency injection mechanism & state management

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#75625]
I understand that flutter aims to be as scoped as possible as just widgets. However with the lack of some essential features in the framework itself a lot of libraries are popping off, which are basically solving the same problem and the only purpose they serve is to fragment the community. Or worse it makes it hard for a newcomer to pick the right tool. It also requires reading about the different solutions before understanding that they all do the same thing. It's daunting at first when seeing the list of state management [(taken from this reddit thread):](https://www.reddit.com/r/FlutterDev/comments/he949d/remi_rousselet_just_released_riverpod_his_next/) 

```
Scoped Model
ProviderScope
Redux
BLOC
RxVMS
MVC
rebloc
Dartea
MobX
Statelessly/Reactivity
var_widget
fish-redux
Provider
AsyncRedux
OSAM
Get
Momentum
state_notifier 
cubit 
maestro
meowchannel
no_bloc
blocstar
mvcprovider
states_rebuilder
mvvm_builder
riverpod (by creator of provider)
vmiso
```

Most of them come packaged with their dependency injection mechanism:

It all boils down to a separation of concerns of MVC. People want:

- a clear representation of state (although this is often merged with the C )
- a service that changes said state
- a clean UI architecture without state management 

There is already classes that do this in the framework: [ValueNotifier](https://api.flutter.dev/flutter/foundation/ValueNotifier-class.html) & [ValueListenableBuilder](https://api.flutter.dev/flutter/widgets/ValueListenableBuilder-class.html).

But since flutter doesn't have dependency injection people use `provider` which comes packaged with it's own state management solution. StateNotifier for example is about the same as value notifier although better implemented, which is about the same as a cubit which is arguably even better implemented. People can't just use cubit / bloc because it doesn't come with a dependency injection mechanism so flutter_bloc uses Provider. However provider is not only dependency injection but also state management so you end up with 2 state management solutions when using flutter_bloc. You see were I'm going ? 

State Management and dependency injection has become essential to building apps of any decent size.
Imo flutter should embrasse that, cut the madness dry: have those 2 things implemented in the framework itself;

 - DI Providers( providers: []) : For dependency injection. Just one Providers widget. No ChangeNotififierProvider, no StreamProvider, etc - this is mixing concerns-. Just one simple providers, it's just DI.
  It can evolve with time when reflection becomes better in dart to have annotations for injection a la angular. At least everyone would be on the same baseline.
- (MV)**C**: Cubit, StateNotifier, ValueNotifier,  make your pick, just the one with the less boiler plate (seems to be cubit).

**Comment by iapicca** [comment]
@cedvdb 
I don't believe flutter's github repo is the right place for a `discussion`,
imho such an open topic should be discussed on one of the many channels of [flutter community](https://flutter.dev/community)

**Comment by TahaTesser** [comment]
Hi @cedvdb 
There is no one solution fits all, each approach has it own pros and cons hence list of packages, I'm not sure but i don't think this is a brand new idea to implement this in Flutter itself and it hasn't been done probably for a good reason.
Please see https://flutter.dev/community for discussions for like these 
Thank you
