### ISSUE TITLE
[web]: <Flutter Web hot Restart issue>

### ISSUE THREAD

**Issue by rakeshcoolrex** [flutter/flutter#75631]
when I do hot restart multiple times simultaneouly it give textspan  error or any other error of RenderFlex etc can you fix it fast. Also when I use GetX package it does not hot restart fast It takes too much time and I have to close tab and restart VS code and run flutter run command

**Comment by iapicca** [comment]
duplicate of https://github.com/flutter/flutter/issues/75630

**Comment by erickzanardo** [comment]
Closing this as it is a duplicated as @iapicca mentioned above.
