### ISSUE TITLE
Access phone number from incoming calls.

### ISSUE THREAD

**Issue by sanjay23singh** [flutter/flutter#75634]
Is there any way to access the phone number of an incoming  call in flutter, like the one truecaller does?

**Comment by iapicca** [comment]
@sanjay23singh 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@sanjay23singh 
Your question is better suited for StackOver flow. Please follow above referred link to get help on it.
Closing.
