### ISSUE TITLE
TextButton, ElevatedButton, and OutlinedButton need API doc samples

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#75642]
Although many useful examples can be found in flutter.dev/go/material-button-migration-guide and in https://github.com/flutter/flutter/pull/59702 as well as the [ButtonStyle API doc](https://api.flutter.dev/flutter/material/ButtonStyle-class.html), the API docs for the new Button classes need examples as well.

**Comment by Abhishek01039** [comment]
Hello @HansMuller 
can you please look at this PR?
https://github.com/flutter/flutter/pull/75519
Thansk
