### ISSUE TITLE
Send list to server without json_encode dart

### ISSUE THREAD

**Issue by hason1** [flutter/flutter#75646]
Iam using [http][1] package to communicate with the server.
How to send an list to php file in the server without json_encode in Dart with Flutter.
```
dynamic result = null;

List ids = [12, 65, 7];

Map data = {
      'name': 'Mark',  
      'ids': ids, 
};

var client = new http.Client();

  await client.post('https://example.com/control/',
headers: {
                "Accept": "application/json",
              },
            body: data,) 
              .then((response) => result = jsonDecode(response.body));
```
My code above dont work, The problem is I must write `json_encode(ids)` to send the data, and when I want to get the array/list in my php file I need to write `json_decode($this->input->post('ids'))`

How to solve it without json_encode and json_encode, how to send an json object which can accept arrays without any problem?

  [1]: https://pub.dev/packages/http

**Comment by iapicca** [comment]
@hason1 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment]
@hason1 
Your question is better suited for StackOver flow. Follow above referred link to get help on it. If you think there's an issue / bug in `http` plugin, file an issue in dedicated repo : https://github.com/dart-lang/http/issues

Closing from here.
