### ISSUE TITLE
Split out FML into its own independent library

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#75653]
cc/ @cbracken @zanderso @chinmaygarde 

After some discussion we've decided to explore splitting FML out into its own independent library for embedders and other dependencies to be able to use. This would also allow us to have a convenient place to put utility classes that are currently being duplicated in multiple places (e.g. a `Rect` class).

**Comment by cbracken** [comment]
Everything necessary here has landed and we're now using FML in the desktop embedders.
