### ISSUE TITLE
Dart 2.9.2 is incompatible with your dependencies' SDK constraints. Please run \"pub get\" again.

### ISSUE THREAD

**Issue by ishaileshmishra** [flutter/flutter#75651]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@ishaileshmishra 
Going by the issue title, you may check out [this](https://github.com/flutter/flutter/issues/38697) issue and underlying comments to see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
