### ISSUE TITLE
Prevent scrolling when changing TextEditingController text flutter

### ISSUE THREAD

**Issue by hason1** [flutter/flutter#75655]
Iam using  TextEditingController control and when I set the control text to a new data by using `control.text = 'hi';` 
 in a function, the listview scroll to the widget which use this control because the data has been changed.

How to prevent scrolling the widget which use this control when I change the control text and stay in the same position in the screen?
```
Widget textbox_widget1(){
         return TextFormField(
          keyboardType: TextInputType.number, 
          controller: control, 
          autofocus: false,
        );
}

```
and here I added my listview in a scaffold in build function

<details>
<summary>code sample</summary>

```dart
     child: Scrollbar(
                controller: _scrollController,
                child: Padding(
                  padding: EdgeInsets.only( bottom: MediaQuery.of(context).viewInsets.bottom / 1.5), // fixade keyboard över title med padding, 1.5 ta bort vit padding
                  child: ListView(
                    controller: _scrollController,
                    shrinkWrap: true,
                    padding: EdgeInsets.only(left: 24.0, right: 24.0),
                    children: <Widget>[

                      SizedBox(height: 15.0),

                      textbox_widget1(),

                      SizedBox(height: 15.0),

                      textbox_widget2(),

			         SizedBox(height: 15.0),

                      textbox_widget3(),

 			SizedBox(height: 15.0),

 		      textbox_widget4(),

  			textbox_widget5(),
                      SizedBox(hight: 70,),


                    ],
                  ),
                ),
              ),
```
</details>

and the function is something like this
```
    void set_text(){control.text = 'new data';}
```

Thanks

**Comment by CoderBuck** [comment]
#51703

**Comment by pedromassangocode** [comment]
Hi @hason1 
I see there's an open issue (https://github.com/flutter/flutter/issues/50713) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
