### ISSUE TITLE
DartVMTest.OldGenHeapSize hangs during presubmit.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#75654]
[This was observed](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856823771689803392/+/steps/Host_Tests_for_host_debug_unopt/0/stdout) once in the past week during a presubmit. The test did not complete in 30 seconds and was killed by unresponsive test watchdog.

**Comment by zanderso** [comment]
From engine flake triage: This has not occurred recently, so I am closing this issue as stale.
