### ISSUE TITLE
Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterEngine io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.getFlutterEngine()' on a null object reference

### ISSUE THREAD

**Issue by darrinps** [flutter/flutter#75656]
I want to use by ViewModel in my MainActivity class. FlutterActivity does not extend AppCompatActivity (which it should) so I extended FlutterFragmentActivity instead. Now this exception is thrown where before it worked fine when FlutterActivity was extended.

So, this workaround does not seem to be complete: https://github.com/flutter/flutter/issues/45678#issuecomment-575411589

Here is some sample code to reproduce. 

```kt
open class MainActivity: FlutterFragmentActivity() {
//Note: works with FlutterActivity

    private val callbackById = mutableMapOf<Int, Runnable>()
    lateinit var stripe: Stripe
    lateinit var stripeMethodChannel: MethodChannel

//DPS For the below line to work, you have to derive from a specific version of FlutterFragmentActivity
//but doing that leaves you unable to use flutterEngine
    private val viewModel: StripeIntentViewModel by viewModels()
//    private lateinit var viewModel: StripeIntentViewModel
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        Timber.i("In onCreate")

        //DPS First some basic checks to make sure all is up and running
        when {
            flutterEngine == null -> {
                Timber.w("Flutter Engine is null. We are hosed!")
            }
            flutterEngine?.dartExecutor == null -> {
                Timber.w("Dart Extractor is null. We are hosed!")
            }
            flutterEngine?.dartExecutor?.binaryMessenger == null -> {
                Timber.w("Binary Messenger is null. We are hosed!")
            }
        }
```

**Comment by TahaTesser** [comment]
Hi. @darrinps 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample in a repository
Thank you

**Comment by darrinps** [comment]
Basically, just create a Hello World app and add this in MainActivity (under app/java/app package directory).


`open class MainActivity:  FlutterFragmentActivity() {
    private val callbackById = mutableMapOf<Int, Runnable>()
    lateinit var stripe: Stripe
    lateinit var stripeMethodChannel: MethodChannel
    private lateinit var viewModel: StripeIntentViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        //First some basic checks to make sure all is up and running
        when {
            flutterEngine == null -> {
               val itWillNeverGetHere = 0
            }
            flutterEngine?.dartExecutor == null -> {
               val itForSureWillNeverGetHere = 0
            }
        }
`

**Comment by darrinps** [comment]
C:\Users\darri>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version
    10.0.19042.804], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[!] VS Code (version 1.51.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

Note that it is incorrect. Android Studio is installed (how I work with Android).

**Comment by TahaTesser** [comment]
HiI @darrinps 
It also never gets called when extending `FlutterActivity` but you mentioned 

>  it worked fine when FlutterActivity was extended.



This is also not getting called 
<details>
<summary>code sample</summary>

```dart
package com.nevercode.triage

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import timber.log.Timber

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        Timber.d("configureFlutterEngine called!")



        //DPS First some basic checks to make sure all is up and running
        when {
            flutterEngine == null -> {
                val x = 0 //will never get here
                Timber.w("Flutter Engine is null. We are hosed!")

            }
            flutterEngine?.dartExecutor == null -> {
                val y = 0 //for certain will never get here
                Timber.w("Dart Extractor is null. We are hosed!")

            }
            flutterEngine?.dartExecutor?.binaryMessenger == null -> {
                val z = 0 ///no way it will ever get here
                print(z.toString())
                Timber.w("Binary Messenger is null. We are hosed!")


            }
        }

    }

}

```

</details>

**Comment by darrinps** [comment]
/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fluttercrash, PID: 30278
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.fluttercrash/com.example.fluttercrash.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterEngine io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.getFlutterEngine()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterEngine io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.getFlutterEngine()' on a null object reference
        at io.flutter.embedding.android.FlutterFragment.getFlutterEngine(FlutterFragment.java:913)
        at io.flutter.embedding.android.FlutterFragmentActivity.getFlutterEngine(FlutterFragmentActivity.java:514)
        at com.example.fluttercrash.MainActivity.onCreate(MainActivity.kt:13)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
I/Process: Sending signal. PID: 30278 SIG: 9
Disconnected from the target VM, address: 'localhost:60819', transport: 'socket'


`package com.example.fluttercrash

import android.os.Bundle
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        //DPS First some basic checks to make sure all is up and running
        when {
            flutterEngine == null -> {
                var x = 1
                x++
            }
            flutterEngine?.dartExecutor == null -> {
                var x = 1
                x++
            }
            flutterEngine?.dartExecutor?.binaryMessenger == null -> {
                var x = 1
                x++
            }
        }
    }
}
`

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}


class MyApp extends StatelessWidget {

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  static const crashPlatformChannel = const MethodChannel('com.example.fluttercrash/crash');


  void _incrementCounter() {

    _crashThisApp();

    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  Future<void> _crashThisApp() async {
    print("Making call to crash the app now");
    var args;

    final String returnCode = await crashPlatformChannel.invokeMethod<String>('crashme', args);
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by TahaTesser** [comment]
Hi @darrinps 
Thanks for the complete code sample, I can reproduce the issue with `FlutterFragmentActivity` but I meant to show me a working example with `FlutterActivity` which does print `x` value.  Setting breakpoints or put timber logs doesn't print those lines even in `FlutterActivity`
Can you please clarify this, `FlutterActivity` doesn't throw the error but also it doesn't print or stops at breakpoint? what is your use case here?
Thank you

**Comment by darrinps** [comment]
That's correct. FlutterActivity will not throw an exception. FlutterFragmentActivity will. 

Don't worry about the log statements here. It's the Exception that I wanted to draw attention to.

**Comment by TahaTesser** [comment]
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[!] Connected device
    ! No devices available
! Doctor found issues in 4 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/tahatesser/Code/flutter_master
    • Framework revision 5642bed237 (4 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>

**Comment by RaicuRobert** [comment]
Any news? I came across the same issue.

**Comment by michaelsoliman1** [comment]
Having the same issue here!! @TahaTesser any solution ?

**Comment by guymclean** [comment]
Experiencing the same issue

**Comment by michaelsoliman1** [comment]
I solved it by writing the code in `onAttachFragment`! since the problem was in the fragment being null, don't know if it's the right thing but it worked for me

**Comment by xiejinpeng007** [comment]
I have the same problem and move the code into `onAttachFragment ` doesn't work.
