### ISSUE TITLE
How to report memory leak?

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#75661]
After a few hours of working in Flutter, Dart process slows my computer and when I see, it is consuming 20 GB of RAM. This happens frequently (like daily/weekly). Is it possible to somehow report it? If I get the process information, will it be useful? I don't have any reproducible steps, but I wish there were a magical log file I could get for you to help you mitigate the issue.  

![image](https://user-images.githubusercontent.com/351125/106063298-b754fc00-60d6-11eb-95fa-046f376c0552.png)

ps -p $PID returns

>   PID TTY           TIME CMD
10428 ??         6:47.03 /usr/local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/usr/local/flutter/packages/flutter_tools/.packages /usr/local/flutter/bin/cache/flutter_tools.snapshot --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --web-port=1234 --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main_editor5.dart

**Comment by pedromassangocode** [comment]
Hi @bernaferrari 
This is an issue in the Dart SDK, please see a similar issue https://github.com/dart-lang/sdk/issues/41793. You may want to leave a comment there rather than opening a new issue ticket.
Thank you

**Comment by bernaferrari** [comment]
Ok. I opened an issue in Dart sdk, but they told me it was a flutter framework issue, not Dart, because of the process id. But no problem, if it is the same issue..

**Comment by Dana-Ferguson** [comment]
I'm having the same issue. `flutter_tools.snapshot` is only being run while dev-tools is running against an active process. If I stop running my flutter code (in Chrome as WebApp in this case, which the code being run does not have a memory leak), then all the memory gets released. At 32 GB it will fail, with requested '80 bytes' and failed (it will print this A LOT), without being able to inspect the process (can I do this somehow?), I would guess it's logging performance information and never releasing it. It's slow enough that it's not a big issue (for our flutterinians with low RAM, I could see this being a big issue).
