### ISSUE TITLE
Lints to enable in the default analysis options

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#75663]
I think we should enable these lints by default (in addition to any we enable now):

    - no_logic_in_create_state
    - annotate_overrides
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_implementing_value_types
    - avoid_null_checks_in_equality_operators
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - do_not_use_environment
    - hash_and_equals
    - implementation_imports
    - no_adjacent_strings_in_list
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - no_runtimeType_toString
    - prefer_adjacent_string_concatenation
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_string_buffers
    - valid_regexps

**Comment by jacob314** [comment]
Fyi @pq

**Comment by jonahwilliams** [comment]
> do_not_use_environment

Definitely against turning that one on. Aside from the fact it is _incredibly_ useful, we also make use of environment constructors of the flutter framework. We should be dogfooding all of these lints unless there is a strong reason, otherwise its _features for me and not for you_ .

**Comment by pq** [comment]
@Hixie: is this for default flutter _user_ options or for the flutter repo?

**Comment by Hixie** [comment]
This is intended for users. Happy to defer to @jonahwilliams's comment above, the list should not be taken as being set in stone. I just noticed that there's a bunch of useful lints (e.g. no_logic_in_create_state) that we really should enable but haven't yet.

I agree with @jonahwilliams that we shouldn't enable any here that we don't enable for ourselves. I recently went through a bunch of these (e.g. no_logic_in_create_state) to enable them for the flutter repo, FWIW.

**Comment by goderbauer** [comment]
I agree that we should enable all the lints suggested by Hixie for our users except for the following lints, which are currently not enabled for the framework (and I think we should dogfood them there first):

* ~`avoid_type_to_string` - "we do this commonly"~ (enabled in https://github.com/flutter/flutter/pull/77013)
* `do_not_use_environment` - "we do this commonly", see also Jonah's comment above
* `missing_whitespace_between_adjacent_strings` - "not yet tested"
* `prefer_interpolation_to_compose_strings` - "not yet tested"
* `sized_box_for_whitespace` - "not yet tested"
* `use_key_in_widget_constructors` - "not yet tested"
* `use_string_buffers` - has false positives: https://github.com/dart-lang/sdk/issues/34182

We should enable the ones marked as "not yet tested" above for our users once they are enabled and tested in the framework. `use_string_buffers` could be enabled for users and in the framework once the linked bug is fixed.

**Comment by Hixie** [comment]
For missing_whitespace_between_adjacent_strings, prefer_interpolation_to_compose_strings, sized_box_for_whitespace, and use_key_in_widget_constructors, I've tested them extensively on my own projects, and I think they're unambiguously good. I agree that we should enable them for the framework too, but I think that's orthogonal.

**Comment by Hixie** [comment]
avoid_implementing_value_types is another one we should enable. avoid_unnecessary_containers also.

**Comment by goderbauer** [comment]
The `prefer_interpolation_to_compose_strings` lint seems to have a problem with raw strings: https://github.com/dart-lang/linter/issues/2490

**Comment by goderbauer** [comment]
For context, this is the list of lints used to **score** packages on pub: https://github.com/dart-lang/linter/blob/master/tool/canonical/score.yaml

This is the list of dart-**recommended** lints: https://github.com/dart-lang/linter/blob/master/tool/canonical/recommend.yaml

This is the list of **all** lints: https://github.com/dart-lang/linter/blob/master/example/all.yaml

**Comment by goderbauer** [comment]
Closing this as this is resolved with the new `package:flutter_lints`, which is the default for newly created flutter apps.

**Comment by kuhnroyal** [comment]
I am not sure where to raise this, I will gladly open an issue somewhere if you can point me to the correct project.
I have noticed that `sized_box_for_whitespace` is no longer working, in hindsight this may be the case since Flutter 2, not exactly sure, but I have changes in a bigger project where this lint should have kicked in for some 2-3 month.

Easy to reproduce on Flutter 2.2.2 and master:
* `flutter create`
* setup `flutter_lints` (I have an own custom config, same problem there)
* add a `Container()` somewhere

**Comment by pq** [comment]
Hi @kuhnroyal,

Could you open an issue on the linter?  That's where lint issues are tracked.  Thanks!

https://github.com/dart-lang/linter/issues
