### ISSUE TITLE
Text field hidden behind keyboard

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#75667]
https://buganizer.corp.google.com/issues/176785475.

After I upload a picture (default aspect ratio of square), when I come back to the item edit screen, the cursor is on the item title field, but the actual field is hidden behind my keyboard

Device: Pixel 3a

/cc @HansMuller

**Comment by HansMuller** [comment]
@LongCatIsLooong - can you take a look at this? It appears to be an issue with WebView and the support for automatically scrolling the focused field into view when the viewInsets change (keyboard appears).

**Comment by HansMuller** [comment]
@stuartmorgan - please take a look; appears to be specific to the WebView plugin

**Comment by blasten** [comment]
I replied in the internal bug. This issue is fixed by hybrid composition, but they reported an issue (https://buganizer.corp.google.com/issues/174807815) that blocks them from adopting it.

**Comment by blasten** [comment]
The resolution of this issue is blocked until b/174807815 is fixed, which I'm actively looking at

**Comment by blasten** [comment]
I have been debugging this issue with the eng from customer:pay. No action items yet on my side as I haven't been able to reproduce http://b/174807815 yet.
