### ISSUE TITLE
Internal error (java.util.concurrent.ExecutionException): com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class org.jetbrains.android.facet.AndroidFacetProperties java.util.concurrent

### ISSUE THREAD

**Issue by NishantKrishali** [flutter/flutter#75671]
Hi,

I can run my app in Andriod studio but I am gettting Java issues in Flutter/Intellij. Error Attached
[JavaBuildError.pdf](https://github.com/flutter/flutter/files/5947629/JavaBuildError.pdf)

**Comment by darshankawar** [comment]
@NishantKrishali 
It seems the error is coming from intellij plugin for Flutter. I suggest you to open this issue in dedicated repo and follow-up there for updates. https://github.com/flutter/flutter-intellij/issues
If you disagree, or think this error is coming from Flutter framework, write in comments and I'll reopen it.
