### ISSUE TITLE
My Flutter App Does Not Display Cloud Firestone Document Data

### ISSUE THREAD

**Issue by goldewater** [flutter/flutter#75674]
Perhaps, the App doesn't even retrieve the data! 
The only Error message I can see in the RUN Log says: 
"E/flutter ( 5360): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: MissingPluginException(No implementation found for method Query#getDocuments on channel plugins.flutter.io/cloud_firestore), stack trace: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)"
Has anyone encountered and resolved this issue?

**Comment by darshankawar** [comment]
@goldewater 
Firebase related issues are tracked here : https://github.com/FirebaseExtended/flutterfire/issues. Please open this issue there.
Closing.
