### ISSUE TITLE
Call sycn method in main, Stuck on white scree

### ISSUE THREAD

**Issue by chandanitnou** [flutter/flutter#75696]
<img width="329" alt="Screen Shot 2021-02-09 at 4 29 46 PM" src="https://user-images.githubusercontent.com/8949345/107343564-072ebc80-6af4-11eb-838a-0261b7a3f3f0.png">
<img width="470" alt="Screen Shot 2021-02-09 at 4 30 07 PM" src="https://user-images.githubusercontent.com/8949345/107343613-144bab80-6af4-11eb-8390-88f4c4831748.png">
<img width="456" alt="Screen Shot 2021-02-09 at 4 30 42 PM" src="https://user-images.githubusercontent.com/8949345/107343686-288fa880-6af4-11eb-8d42-e7e448e0c29d.png">
if click Run it work as expected, but when I build app bundle for test with play store, the screen is stuck on white screen.
thanks for advices.

**Comment by eliezerp3** [comment]
I am having the same problem. Did you solve this? @chandanitnou
