### ISSUE TITLE
webview_flutter: ^1.0.7 Is not supporting for download files from website

### ISSUE THREAD

**Issue by harshasuraweera** [flutter/flutter#75703]
**PLEASE HELP ME - In simply, I want to enable file download in webview_flutter**
I am using webview_flutter: ^1.0.7 [](https://pub.dev/packages/webview_flutter) as the WebViewController in my Flutter App. 

There is s pdf download link on the website. In chrome or other browsers, when I clicked this it begins to download the file. But in my flutter app, it is **just clickable only**. Nothing happened when clicked it. 
Code I use [](https://pastebin.com/1JvxLyrc)

import 'dart:math';
import 'package:am_sliit/bookmark_screens/bookmarks.dart';
import 'package:am_sliit/timetable_screens/timetable.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'main.dart';

class IndexPage extends StatefulWidget{
  @override
  _MyIndexPage createState() => _MyIndexPage();
}

class _MyIndexPage extends State<IndexPage>{

  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final Color logoGreen = Color(0xffD0752c);
  WebViewController _controller;
  final String url = "https://google.com"

  DatabaseReference bookmarkRef = FirebaseDatabase.instance.reference().child("bookmarks").child(FirebaseAuth.instance.currentUser.uid);
  TextEditingController _controllerBookmarkTitle = TextEditingController();

  createAddBookmarkAlertDialog (BuildContext context, String currentUrlByUser){
    return showDialog(context: context, builder: (context){
      return AlertDialog(
        title: Text("Add this page as a bookmark"),
        content: TextField(
          controller: _controllerBookmarkTitle,
          decoration: InputDecoration(
            hintText: "Give a title",
          ),
        ),
        actions: [
          MaterialButton(
            elevation: 5.0,
            child: Text("Add"),
            onPressed: (){
              String _bookMarkTitle = _controllerBookmarkTitle.text.trim().toString();
              makeThisPageAsBookMark(context, _bookMarkTitle , currentUrlByUser);
              Navigator.of(context).pop();
            },
          )
        ],
      );
    }
    );
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        bottomNavigationBar: BottomAppBar(
          color: logoGreen,
          child: Row(
            children: [
              IconButton(icon: Icon(Icons.arrow_back_ios, color: Colors.white,), onPressed: () {
                _controller.goBack();
              }),
              Spacer(),
            IconButton(icon: Icon(Icons.arrow_forward_ios, color: Colors.white,), onPressed: () {
                _controller.goForward();
              }),
            ],
          ),
        ),
        floatingActionButton:
        FloatingActionButton(
          backgroundColor: logoGreen,
          child: Icon(Icons.grid_view),
            onPressed: () {
              // Navigator.push(context,
              //     MaterialPageRoute(builder: (_) => Timetable("zz")));
              Navigator.of(context).push(MaterialPageRoute(
                builder: (context) =>Timetable(clickedDay : null),
              ));

            },
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        appBar: AppBar(
          backgroundColor: logoGreen,
          title:  Text("AM GG"),
          actions: [
            IconButton(
              icon: Icon(Icons.push_pin_rounded),
              onPressed: () async {
                createAddBookmarkAlertDialog(context, await _controller.currentUrl());
              } , // => function();
            ),
            IconButton(
              icon: Icon(Icons.collections_bookmark_sharp),
              onPressed: () async {
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => Bookmark()));
              } , // => function();
            ),
          ],
        ),
        drawer: Drawer(
            // Populate the Drawer in the next step.
          child: ListView(
            // Important: Remove any padding from the ListView.
            padding: EdgeInsets.zero,
            children: <Widget>[
              DrawerHeader(
                child: Text("Hi, Good " +greeting() + "!",
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                      fontSize: 20,
                    ),
                ),
                decoration: BoxDecoration(
                  color: Color (0xff00007b),
                  ),
                ),
              ListTile(
                title: Text('T1'),
                onTap: () {
                  // Update the state of the app
                  // ...
                  _controller.loadUrl('https://google.com/');
                  // Then close the drawer
                  Navigator.pop(context);
                },
              ),
              ListTile(
                title: Text('T2'),
                onTap: () {
                  // Update the state of the app
                  // ..
                  _controller.loadUrl('https://fb.com/');
                  // Then close the drawer
                  Navigator.pop(context);
                },
              ),
              ListTile(
                title: Text('Sign Out'),
                onTap: () {
                  // Update the state of the app
                  // ..
                  signOutNow(context);
                  // Then close the drawer
                  Navigator.pop(context);
                },
              ),
            ],
          ),
        ),
       body:
       WebView(
         initialUrl: url,
         javascriptMode: JavascriptMode.unrestricted,
         onWebViewCreated: (WebViewController webViewController) {
           _controller = webViewController;
         },
       ),
      ),
    );
  }

  void makeThisPageAsBookMark(BuildContext context, String bookmarkTitle, String bookmarkUrl) {

    final User user = FirebaseAuth.instance.currentUser;
    final uid = user.uid;

    Map bookmarkDetails = {
      "bookmarkTitle": bookmarkTitle,
      "bookmarkUrl": bookmarkUrl,
    };

    DatabaseReference bookmarkRef = FirebaseDatabase.instance.reference().child("bookmarks");
    bookmarkRef.child(uid).child(_randomString(10)).set(bookmarkDetails);

  }

  }

  loadLoggedUsersBookmarks(BuildContext context){

    final User user = FirebaseAuth.instance.currentUser;
    final uid = user.uid;
    DatabaseReference bookmarkRef = FirebaseDatabase.instance.reference().child("bookmarks");

    bookmarkRef.child(uid).once().then((DataSnapshot snapshot){
      if(snapshot.value.isNotEmpty){
          snapshot.value.forEach((key,values) {

            Map bookmarkDetails = {
              "bookmarkTitle": values["bookmarkTitle"],
              "bookmarkUrl": values["bookmarkUrl"],
            };

            print(bookmarkDetails);
          });

      }
    });

  }

String greeting() {

  var hour = DateTime.now().hour;
  if (hour < 12) {
    return 'Morning';
  }
  if (hour < 17) {
    return 'Afternoon';
  }
  return 'Evening';
}

String _randomString(int length) {
  var rand = new Random();
  var codeUnits = new List.generate(
      length,
          (index){
        return rand.nextInt(33)+89;
      }
  );

  return new String.fromCharCodes(codeUnits);
}

Future<void> signOutNow (BuildContext context) async {
  await FirebaseAuth.instance.signOut();
  Navigator.push(context,
      MaterialPageRoute(builder: (_) => LoadWelcomePage()));
}

displayToastMessage(String message, BuildContext context){
  Fluttertoast.showToast(msg: message);
}

**Comment by darshankawar** [comment]
@harshasuraweera 
File download feature is not yet supported by `webview_flutter` plugin. See this open proposal for same, https://github.com/flutter/flutter/issues/39321.
Follow-up in that issue to get updates.
Closing this as duplicate.

**Comment by harshasuraweera** [comment]
> @harshasuraweera
> File download feature is not yet supported by `webview_flutter` plugin. See this open proposal for same, #39321.
> Follow-up in that issue to get updates.
> Closing this as duplicate.

So what is the way to do this?
