### ISSUE TITLE
Document quirky Listenable notification pattern

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#7570]
If you add the same callback to a Listenable twice and remove it once while an iteration is ongoing, the callback might still be called twice.  We should document that quirky behavior (or figure out a clever way to remove the quirk).

This quirk is especially tricky when you have derivative animations that share a common parent.  They'll forward their listeners to the parent, which might be surprising.

**Comment by Hixie** [comment]
https://docs.flutter.io/flutter/foundation/ChangeNotifier/removeListener.html documents this.
