### ISSUE TITLE
Doc Request: Focus issue while using a Form widget

### ISSUE THREAD

**Issue by mikemimik** [flutter/flutter#7575]
## Steps to Reproduce

- Create a `Form` with `TextField`'s in it
- Create a widget which just returns this `Form`
- The app will break stating `Two focusable widgets with different keys, [GlobalKey 115789168] and [GlobalKey 956381934], exist in
the widget tree simultaneously, but they have no Focus widget ancestor.
If you have more than one focusable widget, then you should put them inside a Focus. Normally, this
is done for you using a Route, via Navigator, WidgetsApp, or MaterialApp.`

## Logs
```
Two focusable widgets with different keys, [GlobalKey 115789168] and [GlobalKey 956381934], exist in
the widget tree simultaneously, but they have no Focus widget ancestor.
If you have more than one focusable widget, then you should put them inside a Focus. Normally, this
is done for you using a Route, via Navigator, WidgetsApp, or MaterialApp.
```

## Request
Perhaps in the `Form` docs there can be mention that if you put _things that have a focus_ then you should have that `Form` nested inside the mentioned widgets. This wasn't completely apparent from the error message displayed.

**Comment by abarth** [comment]
This message no longer exists because this constraint no longer exists in the new focus system.  Your app should work now without having to mess around with focus scope widgets.
