### ISSUE TITLE
The Bottom Navigation Bar doesn't show correctly when I add an option.

### ISSUE THREAD

**Issue by RenaSki** [flutter/flutter#75753]
## Steps to Reproduce

1. Run `flutter create bug`.
Recreating project bug...
Wrote 3 files.
All done!
[√] Flutter: is fully installed. (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[!] Android toolchain - develop for Android devices: is partially installed; more components are available. (Android SDK
    version 30.0.2)
[√] Android Studio: is fully installed. (version 4.0)
[!] VS Code: is partially installed; more components are available. (version 1.50.1)
[!] Connected device: is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug\lib\main.dart.
2. Update the files as follows: ... 
I am trying to make a bottom navigating bar. It works correctly when I have three options in the bottom navigation bar. However, it doesn't work correctly when I have four potions. The four options appear but it all-white color and hard to see. I have attached pictures to describe below.
Three options:
![atempsnip](https://user-images.githubusercontent.com/70543067/107446155-74961980-6b03-11eb-9443-c295ee0a24bd.png)
Four options:
![tempsnip](https://user-images.githubusercontent.com/70543067/107445941-0ea99200-6b03-11eb-93a2-06c1145b5d7e.png)

**Expected results:** 
I expect to see the same design as when there are 3 options is displayed. So I can see the options well.
**Actual results:** 
Four options are displayed on the bottom navigation bar , but it is hart to see because the color is all white.
<details>
  <summary>Logs</summary>

Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

  info - The value of the field '_widgetOptions' isn't used -
          AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:13:15 - unused_field
   info - The value of the field '_counter' isn't used -
          AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:31:7 - unused_field
warning - The parameter 'onPressed' is required - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:50:11 -
       missing_required_param
  error - Expected to find '}' - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:109:4 - expected_token
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\mealPlan.dart:3:7 -
          camel_case_types
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:2:8 - unused_import
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:16:7 -
          camel_case_types
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:21:7 -
          camel_case_types
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:2:8 - unused_import
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:17:7 -
          camel_case_types
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:22:7 -
          camel_case_types
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\shopping.dart:2:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: Shopping.listTiles -
          AndroidStudioProjects\meal_flutter_app\lib\shopping.dart:4:7 - must_be_immutable
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\shoppingBackup.dart:2:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: Shopping.listTiles -
          AndroidStudioProjects\meal_flutter_app\lib\shoppingBackup.dart:4:7 - must_be_immutable
   info - Unused import: 'package:flutter/rendering.dart' - AndroidStudioProjects\meal_flutter_app\lib\store.dart:2:8 -
          unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\stors.dart:3:8
          - unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\storsBackup.dart:2:8 - unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' -
          AndroidStudioProjects\meal_flutter_app\lib\storsDraft.dart:2:8 - unused_import
   info - Unused import: 'dart:async' - AndroidStudioProjects\meal_flutter_app\lib\storsDraft.dart:3:8 - unused_import

20 issues found. (ran in 97.2s)

[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.20.3 at C:\src\flutter_windows_1.20.3-stable\flutter
    • Framework revision 216dee60c0 (5 months ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\sakai017\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.50.1)
    • VS Code at C:\Users\sakai017\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

</details>

**Comment by pedromassangocode** [comment]
Hi @RenaSki 
Looks like you are using a old version of Flutter.
Can you please upgrade and try again?

If the issue persists, provide your `flutter doctor -v`.
Thank you

**Comment by bhawesh2002** [comment]
Add 'selectedItemColor' and 'unselectedItemColor' Property to BottomAppBar

For Ex:-


```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bottom Navigation Bar',
      home: Scaffold(
        appBar: AppBar(
          title: Text('App Bar'),
        ),
        body: Center(child: Text("Bottom Navigation Bar Sample")),
        bottomNavigationBar: BottomNavigationBar(
          backgroundColor: Colors.red,
          selectedItemColor: Colors.blue,
          unselectedItemColor: Colors.blue.shade200,
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Home',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.business),
              label: 'Business',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.school),
              label: 'School',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.school),
              label: 'School',
            ),
          ],
        ),
      ),
    );
  }
}

```
![Screenshot_20210210-180837](https://user-images.githubusercontent.com/55053472/107512665-264d4d00-6bcd-11eb-9eb2-04edcf2b44fd.png)

**Comment by RenaSki** [comment]
> Hi @RenaSki
> Looks like you are using a old version of Flutter.
> Can you please upgrade and try again?
> 
> If the issue persists, provide your `flutter doctor -v`.
> Thank you

I updated Flutter and tried again. But it didn't work.
I have attached a result of `flutter doctor -v` below. Thank you.

C:\Users\sakai017>
C:\Users\sakai017>flutter upgrade
Flutter is already up to date on channel stable
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (3 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

C:\Users\sakai017>flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter_windows_1.20.3-stable\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\sakai017\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.50.1)
    • VS Code at C:\Users\sakai017\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

**Comment by RenaSki** [comment]
> Hi **RenaSki**,
> It's eazy to solve it.
> just Add 'selectedItemColor' and 'unselectedItemColor' Property to BottomAppBar
> Use the line of code between **_ ... _**
> For Ex:-
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Bottom Navigation Bar',
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('App Bar'),
>         ),
>         body: Center(child: Text("Bottom Navigation Bar Sample")),
>    **_[bottomNavigationBar: BottomNavigationBar(
>           backgroundColor: Colors.red,
>           selectedItemColor: Colors.blue,
>           unselectedItemColor: Colors.blue.shade200,]_**
>           items: const <BottomNavigationBarItem>[
>             BottomNavigationBarItem(
>               icon: Icon(Icons.home),
>               label: 'Home',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.business),
>               label: 'Business',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.school),
>               label: 'School',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.school),
>               label: 'School',
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> ![Screenshot_20210210-180837](https://user-images.githubusercontent.com/55053472/107512665-264d4d00-6bcd-11eb-9eb2-04edcf2b44fd.png)

Hello bhawesh2002,
Thank you for your reply. It worked!! Thank you for your helping.

**Comment by RenaSki** [comment]
The problem solved. Thank you.

**Comment by bhawesh2002** [comment]
Welcome
