### ISSUE TITLE
[camera] freeze parameter for CameraPreview

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#75751]
this would allow to easily allow freeze the frame when we takePickture()

currently it's impossible to seamlessly show taken image, because the image buffer is not exposed, and if it would be exposed, i doubt there would be a way to seamlessly display it in `Image.memory`, because it anyway will take some time to process and will show black frame a few vsync frames, which should be addressed by https://github.com/flutter/flutter/issues/75750, i guess

blockers 
* https://github.com/flutter/flutter/issues/75737
* https://github.com/flutter/flutter/issues/75228 - as camera that's not migrated to nnbd yet can't depened on camera_platform_interface that's already migrated

see also
https://github.com/flutter/plugins/pull/3531#issuecomment-776353450

**Comment by matejthetree** [comment]
when taking a picture, in the Future where you wait for the picture to be ready, you can also precache it.
then once complete, it can be shown immediately,

**Comment by nt4f04uNd** [comment]
explained why this is not possible in mentioned #75750

**Comment by nt4f04uNd** [comment]
Duplicate of https://github.com/flutter/flutter/issues/27079 and https://github.com/flutter/flutter/issues/34997
