### ISSUE TITLE
[web]: Flutter build web command builds older version of the webapp

### ISSUE THREAD

**Issue by tevin-morake** [flutter/flutter#75762]
Everytime I build a flutter webapp with command `flutter build web` , I get an older version of the app.
This issue has been solved for mobile applications as per [16604](https://github.com/flutter/flutter/issues/16604), but continues to be a pain on the web.

I'm using chrome Version 88.0.4324.146 (Official Build) (x86_64) on OS X Big Sur.

I've also tried the following as a means of fixing this issue: 
1.  flutter clean before build
2.  flutter pub cache repair and then followed by step 1
3. git clean -fdx in the root and build folder of my project followed by step 1 above

Here is an output of the web build command 
`flutter build web -v
[  +99 ms] executing: [/Users/tevin/Applications/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f3c10bd23a274f51579f662986e871cb45d6d941
[        ] executing: [/Users/tevin/Applications/flutter/] git tag --points-at f3c10bd23a274f51579f662986e871cb45d6d941
[ +160 ms] Exit code 0 from: git tag --points-at f3c10bd23a274f51579f662986e871cb45d6d941
[   +4 ms] executing: [/Users/tevin/Applications/flutter/] git describe --match *.*.* --long --tags f3c10bd23a274f51579f662986e871cb45d6d941
[  +80 ms] Exit code 0 from: git describe --match *.*.* --long --tags f3c10bd23a274f51579f662986e871cb45d6d941
[        ] 1.26.0-17.0.pre-215-gf3c10bd23a
[  +52 ms] executing: [/Users/tevin/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/tevin/Applications/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/Users/tevin/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +21 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.1
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20C69
[  +11 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +88 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +79 ms] Skipping pub get: version match.
[  +98 ms] Found plugin firebase_auth at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.20.0+1/
[  +10 ms] Found plugin firebase_auth_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+6/
[   +2 ms] Found plugin firebase_core at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/
[   +4 ms] Found plugin firebase_core_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+3/
[   +6 ms] Found plugin fluttertoast at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.6/
[  +33 ms] Found plugin package_info at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3+2/
[   +6 ms] Found plugin path_provider at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[   +2 ms] Found plugin path_provider_linux at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +2 ms] Found plugin path_provider_macos at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +3 ms] Found plugin path_provider_windows at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +20 ms] Found plugin sentry_flutter at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-4.0.1/
[ +151 ms] Found plugin firebase_auth at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.20.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+6/
[        ] Found plugin firebase_core at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/
[   +1 ms] Found plugin firebase_core_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+3/
[   +2 ms] Found plugin fluttertoast at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.6/
[  +14 ms] Found plugin package_info at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3+2/
[   +2 ms] Found plugin path_provider at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[        ] Found plugin path_provider_linux at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +1 ms] Found plugin path_provider_windows at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[   +6 ms] Found plugin sentry_flutter at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-4.0.1/
[  +29 ms] Generating /Users/tevin/git/work/RunningHillPartners/io/dashboard/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +32 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[+1644 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.2
           Build version 12B45b
[  +66 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +30 ms] Found plugin firebase_auth at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.20.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+6/
[        ] Found plugin firebase_core at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/
[   +1 ms] Found plugin firebase_core_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+3/
[   +3 ms] Found plugin fluttertoast at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.6/
[  +13 ms] Found plugin package_info at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3+2/
[   +4 ms] Found plugin path_provider at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[   +2 ms] Found plugin path_provider_linux at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +3 ms] Found plugin path_provider_windows at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[   +9 ms] Found plugin sentry_flutter at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-4.0.1/
[  +50 ms] Found plugin firebase_auth at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.20.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.2+6/
[   +1 ms] Found plugin firebase_core at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/
[   +1 ms] Found plugin firebase_core_web at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.1+3/
[   +2 ms] Found plugin fluttertoast at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.6/
[   +8 ms] Found plugin package_info at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3+2/
[   +2 ms] Found plugin path_provider at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[        ] Found plugin path_provider_linux at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +1 ms] Found plugin path_provider_windows at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[   +5 ms] Found plugin sentry_flutter at /Users/tevin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-4.0.1/
[  +15 ms] Compiling lib/main.dart for the Web...
[   +9 ms] Initializing file store
[   +9 ms] Done initializing file store
[  +91 ms] Skipping target: web_entrypoint
[  +11 ms] Skipping target: gen_localizations
[ +876 ms] Skipping target: dart2js
[  +18 ms] invalidated build due to missing files: /Users/tevin/git/work/RunningHillPartners/io/dashboard/DOES_NOT_EXIST_RERUN_FOR_WILDCARD1071880749
[ +188 ms] web_release_bundle: Starting due to {InvalidatedReason.inputMissing, InvalidatedReason.inputChanged}
[ +162 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +76 ms] web_release_bundle: Complete
[ +259 ms] web_service_worker: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.outputChanged}
[ +123 ms] web_service_worker: Complete
[   +2 ms] Persisting file store
[  +11 ms] Done persisting file store
[  +30 ms] Compiling lib/main.dart for the Web... (completed in 1 852ms)
[   +1 ms] "flutter web" took 4 415ms.
[ +260 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0`

**Comment by darshankawar** [comment]
@tevin-morake 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
Also, when you say older version, does it mean it's not updating the web app with latest changes ? If so, can you provide an example of it ?

**Comment by tevin-morake** [comment]
Hi @darshankawar 
`flutter doctor -v` output: 
```[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-ZA)
    • Flutter version 1.26.0-17.3.pre at /Users/tevin/Applications/flutter
    • Framework revision 4b50ca7f7f (5 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tevin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tevin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150```

@darshankawar I'll compile a **complete minimal reproducible code sample** by the morning, thanks.

**Comment by tevin-morake** [comment]
Hi @darshankawar I've managed to solve this issue after going through [#55008](https://github.com/flutter/flutter/issues/55008).

The author resolved it by recreating the project from scratch.
I did the same.
I am not sure what caused the initial problem, but I have a few suspicions from the following git diff : 
![Screenshot 2021-02-11 at 11 32 10](https://user-images.githubusercontent.com/15342622/107621032-5264de80-6c5e-11eb-8d43-32c4acce06d0.png)

The service worker file.
Most of the contents of the web folder were deleted.


Step-by-step this is what I did to solve it : 
1. Create a new flutter web project i.e `flutter create someotherrepo`
2. Copied the `lib/`, `assets` folder of my broken repo to the `someotherrepo` repo
3. Copied the `index.html` of the broken repo into the `someotherrepo` repo
4. Performed a build `flutter build web`
5. Ran the static site locally using `lite-server`(NB: You need to install lite-server if you don't have it i.e `npm install -g lite-server` or serve it using the pub command) i.e `cd build/web && lite-server`
6. Made more modifications and reran steps 4-5 and received equal results. 

A big thanks to @skibz and @Webmoss for contributing towards the solution

**Comment by SpaceboatDVLP** [comment]
My project was only building the master branch when running 'flutter build web', regardless of which branch i had checked out. After merging my dev branch into master I was able to build and deploy the latest version.

**Comment by SpaceboatDVLP** [comment]
@tevin-morake - it may be that the `flutter build web` command was only compiling from your master branch. Do you still have your old repo to test out the theory? When I ran into the same issue, merging my dev branch into master allowed me to successfully build my newest revisions.

**Comment by tevin-morake** [comment]
Unfortunately not @SpaceboatDVLP .
It was proprietary repo I was working on.
