### ISSUE TITLE
RefreshIndicator unnecessarily rebuilding Listview, while tapping and dragging

### ISSUE THREAD

**Issue by msarkrish** [flutter/flutter#75765]
In my application i'm having RefreshIndicator and child as Listview. whenever i tap the children of the listview, Listview getting rebuild. if i remove the refreshindicator and tapping the children of the listview, then no rebuild happens.

I'm using Flutter 1.12.13+hotfix.8

My Code:

    import 'package:flutter/material.dart';

    class DashboardScreen extends StatefulWidget {
     @override
     _DashboardScreenState createState() => _DashboardScreenState();
    }

    class _DashboardScreenState extends State<DashboardScreen> {
        

    @override
     Widget build(BuildContext context) {
        return Scaffold(
           appBar: AppBar(
              title: Text('Dashboard'),
              backgroundColor: Colors.pink,
           ),
           body: RefreshIndicator(
                onRefresh: () {},
                child: ListView(
                    children: <Widget>[
                         KKScreen(),
                              ],
                ),
               ),
           );
           }
        }

       import 'package:flutter/material.dart';

       class KKScreen extends StatefulWidget {
         @override
         _KKScreenState createState() => _KKScreenState();
           }

        class _KKScreenState extends State<KKScreen> {
              @override
             Widget build(BuildContext context) {
                 print("KK");
                 return Container(
                   child: Text('KK'),
                   height: 200,
                    color: Colors.red,
                 );
             }
            }

Flutter Doctor:
C:\FlutterSDK\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at C:\FlutterSDK\flutter
    • Framework revision 0b8abb4724 (1 year ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/t/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/t/AppData/Local/Android/Sdk
    • ANDROID_SDK_ROOT = C:\Users\t\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_271\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\t\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Redmi Note 4 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
Process finished with exit code 0

Related Closed Issue:
https://github.com/flutter/flutter/issues/33294

**Comment by pedromassangocode** [comment]
Hi @msarkrish 
Looks like you are using a one year old version of Flutter. 

> • Framework revision [0b8abb4](https://github.com/flutter/flutter/commit/0b8abb4724aa590dd0f429683339b1e045a1594d) (1 year ago), 2020-02-11 11:44:36 -0800

Please upgrade and try again, if the issue persists, then provide your `flutter doctor -v`.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
