### ISSUE TITLE
[web] don't use absolute paths or make the root path configurable

### ISSUE THREAD

**Issue by skoehler** [flutter/flutter#75771]
I'm building a simple flutter web app using `flutter build web --release`. As is evident from the generated `index.html` and the generated `flutter_service_worker.js`, the web app is expected to run in the root folder.

The generated `index.html` contains `<base href="/">` and the generated `flutter_service_worker.js` contains the following file list: 
```
const CORE = [
  "/",
"main.dart.js",
"index.html",
"assets/NOTICES",
"assets/AssetManifest.json",
"assets/FontManifest.json"];
```
As you can see, most of the paths are relative, except of `"/"` of course. I'm pretty sure you mean something like `""` or `"."`.

I kindly ask you to resolve this issue once and for all. I see so many requests on the web and here on github regarding this issue.
Most people seem to be fine with changing `index.html` to `<base href="/some/folder/">` and are not even aware of the issue with `flutter_service_worker.js`.

Please make the root of the webapp configurable.  Make this part of the getting started guide at https://flutter.dev/docs/get-started/web . Have `flutter_service_worker.js` use relative paths only (relative to the base defined in `index.html`). Of course, when debugging locally, the webapp should be placed in the configured subfolder as well. 

```
$ CHROME_EXECUTABLE=/usr/bin/chromium flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.26.0-17.3.pre at /opt/flutter
    • Framework revision 4b50ca7f7f (vor 5 Tagen), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 88.0.4324.150 Arch Linux

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @skoehler 
I see there's an open issue (https://github.com/flutter/flutter/issues/68686) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
