### ISSUE TITLE
Image_picker has some issues in release mode with android.

### ISSUE THREAD

**Issue by monkeyMax-SVG** [flutter/flutter#75779]
Hello, everyone.
I was building an app using image_picker ( ^0.6.7+22 or ^0.6.7+21) in windows android studio 4.1.2

Regarding to my gradle version,  I am using this.

> classpath 'com.android.tools.build:gradle:4.1.2'
> distributionUrl=https://services.gradle.org/distributions/gradle-6.6.1-all.zip

Also I am using 

> compileSdkVersion 29
> minSdkVersion 21
> targetSdkVersion 29

With following commandes (flutter run --release, flutter run, flutter build apk --debug) , image_picker works correctly.
But only in release mode, it has issue.

Reproduce steps are like following :
1. Build apk as release mode
2. Install apk and tap on button
3. App require camera permission
4. If I tap on allow, permission window disappear, and camera is not opening.
5. I close app and open again. now camera works but after taking photo, it doesnot get image file.
6. when I tap on button, it shows following error.

`> E/flutter (30698): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(already_active, Image picker is already active, nul l, null) E/flutter (30698): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582) E/flutter (30698): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159) E/flutter (30698): E/flutter (30698): #2 MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart :30) E/flutter (30698): E/flutter (30698): #3 _HomeBodyState.getImage (package:myapp/View/Components/Home/home_body.dart:51) E/flutter (30698): E/flutter (30698): #4 _HomeBodyState.build. (package:myapp/View/Components/Home/home_body.dart:224) E/flutter (30698): E/flutter (30698):`

This is some code part in my projects.

```
Future getImage(source_type) async {
     final pickedFile = await picker.getImage(source: source_type ? ImageSource.camera : ImageSource.gallery);
     print(pickedFile);
 
     if(pickedFile != null) {
       String pickPath =  pickedFile.path;
       await getCropImage(pickPath);
     } 
   }
 
 Future getCropImage(_pickedPath) async {
     File croppedFile = await ImageCropper.cropImage(
         maxHeight: 400,
         maxWidth: 300,
         sourcePath: _pickedPath, //imageFile.path,
         aspectRatioPresets: [
           CropAspectRatioPreset.square,
           CropAspectRatioPreset.ratio3x2,
           CropAspectRatioPreset.original,
          CropAspectRatioPreset.ratio4x3,
           CropAspectRatioPreset.ratio16x9
         ],
         androidUiSettings: AndroidUiSettings(
             toolbarTitle: 'Cropper',
             toolbarColor: MainColor,
             toolbarWidgetColor: Colors.white,
             initAspectRatio: CropAspectRatioPreset.square,
             lockAspectRatio: false
         ),
         iosUiSettings: IOSUiSettings(
           minimumAspectRatio: 1.0,
         )
     );
     setState(() {
       if (croppedFile != null) {
         _image = File(croppedFile.path);
       } else {
         print('No image selected.');
       }
     });
   }
```

This is my flutter doctor -v

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18362.53], locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

```

and this is flutter run --release -v

E:\MY_Project\app\franku>flutter run --release -v
[ +113 ms] executing: [E:\VisualStudio\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +50 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +1 ms] executing: [E:\VisualStudio\flutter/] git tag --points-at HEAD
[  +34 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[   +7 ms] executing: [E:\VisualStudio\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\VisualStudio\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [E:\VisualStudio\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +22 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +357 ms] List of devices attached
                    4d26104c               device product:PD1838 model:V1838A device:PD1838 transport_id:8
[   +6 ms] C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4d26104c shell getprop
[ +323 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] Found plugin cloud_firestore at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\cloud_firestore-0.14.4\
[   +7 ms] Found plugin cloud_firestore_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\cloud_firestore_web-0.2.1+2\
[   +4 ms] Found plugin connectivity at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity-2.0.2\
[   +3 ms] Found plugin connectivity_for_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_for_web-0.3.1+4\
[   +2 ms] Found plugin connectivity_macos at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_macos-0.1.0+7\
[   +9 ms] Found plugin firebase_auth at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_auth-0.18.4+1\
[   +3 ms] Found plugin firebase_auth_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_auth_web-0.3.2+3\
[   +2 ms] Found plugin firebase_core at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_core-0.5.3\
[   +3 ms] Found plugin firebase_core_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_core_web-0.2.1+1\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-1.0.11\
[   +9 ms] Found plugin image_picker at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\image_picker-0.6.7+22\
[  +29 ms] Found plugin video_player at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\video_player-1.0.1\
[   +3 ms] Found plugin video_player_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\video_player_web-0.1.4+1\
[ +156 ms] Found plugin cloud_firestore at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\cloud_firestore-0.14.4\
[   +3 ms] Found plugin cloud_firestore_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\cloud_firestore_web-0.2.1+2\
[   +2 ms] Found plugin connectivity at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity-2.0.2\
[   +1 ms] Found plugin connectivity_for_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_for_web-0.3.1+4\
[   +1 ms] Found plugin connectivity_macos at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity_macos-0.1.0+7\
[   +5 ms] Found plugin firebase_auth at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_auth-0.18.4+1\
[   +2 ms] Found plugin firebase_auth_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_auth_web-0.3.2+3\
[   +1 ms] Found plugin firebase_core at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_core-0.5.3\
[   +2 ms] Found plugin firebase_core_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\firebase_core_web-0.2.1+1\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_plugin_android_lifecycle-1.0.11\
[   +7 ms] Found plugin image_picker at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\image_picker-0.6.7+22\
[  +15 ms] Found plugin video_player at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\video_player-1.0.1\
[   +2 ms] Found plugin video_player_web at E:\VisualStudio\flutter\.pub-cache\hosted\pub.flutter-io.cn\video_player_web-0.1.4+1\
[  +13 ms] Generating E:\MY_Project\app\franku\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +24 ms] ro.hardware = qcom
[  +54 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree E:\MY_Project\app\franku\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +46 ms] Exit code 0 from: C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree E:\MY_Project\app\franku\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.example.franku" (Raw: "com.example.franku")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" (Raw: "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: application (line=27)
                 A: android:label(0x01010001)="franku" (Raw: "franku")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 A: android:requestLegacyExternalStorage(0x01010603)=(type 0x12)0xffffffff
                 E: activity (line=34)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.franku.MainActivity" (Raw: "com.example.franku.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=48)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=58)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040015
                   E: intent-filter (line=62)
                     E: action (line=63)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=65)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=72)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: service (line=76)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw: "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=80)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.auth.FlutterFirebaseAuthRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.auth.FlutterFirebaseAuthRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=83)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=86)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=89)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=92)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.firestore.FirestoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=95)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=98)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                 E: provider (line=103)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw: "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.example.franku.flutter.image_provider" (Raw: "com.example.franku.flutter.image_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=108)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw: "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f0c0000
                 E: activity (line=113)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.firebase.auth.internal.FederatedSignInActivity" (Raw: "com.google.firebase.auth.internal.FederatedSignInActivity")
                   A: android:permission(0x01010006)="com.google.firebase.auth.api.gms.permission.LAUNCH_FEDERATED_SIGN_IN" (Raw: "com.google.firebase.auth.api.gms.permission.LAUNCH_FEDERATED_SIGN_IN")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:excludeFromRecents(0x01010017)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x2
                 E: activity (line=120)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw: "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: provider (line=125)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw: "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.example.franku.firebaseinitprovider" (Raw: "com.example.franku.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                 E: receiver (line=132)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementReceiver" (Raw: "com.google.android.gms.measurement.AppMeasurementReceiver")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=138)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementService" (Raw: "com.google.android.gms.measurement.AppMeasurementService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=142)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementJobService" (Raw: "com.google.android.gms.measurement.AppMeasurementJobService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw: "android.permission.BIND_JOB_SERVICE")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=148)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f060000
[  +22 ms] Launching lib\main.dart on V1838A in release mode...
[  +32 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4d26104c shell -x logcat -v time -t 1
[ +498 ms] Exit code 0 from: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4d26104c shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-10 18:40:05.933 E/libc    ( 7347): Access denied finding property "ro.vendor.net.upload.benchmark.default"
[   +1 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4d26104c shell -x logcat -v time -t 1
[ +452 ms] Exit code 0 from: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4d26104c shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           02-10 18:40:06.408 E/libc    ( 7352): Access denied finding property "ro.vendor.net.upload.benchmark.default"
[  +18 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +256 ms] Building APK
[  +16 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from E:\MY_Project\app\franku\android\gradlew.bat.
[   +1 ms] E:\MY_Project\app\franku\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +129 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [E:\MY_Project\app\franku\android/] E:\MY_Project\app\franku\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\MY_Project\app\franku\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleRelease
[ +580 ms] Welcome to Gradle 6.6.1!
[   +1 ms] Here are the highlights of this release:
[        ]  - Experimental build configuration caching
[        ]  - Built-in conventions for handling credentials
[        ]  - Java compilation supports --release flag
[        ] For more details see https://docs.gradle.org/6.6.1/release-notes.html
[ +401 ms] > Configure project :app
[        ] WARNING: The option setting 'android.enableR8=true' is deprecated.
[   +2 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[  +10 ms] You will no longer be able to disable R8
[+2367 ms] > Task :app:compileFlutterBuildRelease
[   +1 ms] [  +96 ms] executing: [E:\VisualStudio\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] [        ] executing: [E:\VisualStudio\flutter/] git tag --points-at HEAD
[        ] [  +32 ms] Exit code 0 from: git tag --points-at HEAD
[        ] [        ] 1.22.6
[        ] [   +7 ms] executing: [E:\VisualStudio\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [E:\VisualStudio\flutter/] git ls-remote --get-url origin
[        ] [  +25 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +52 ms] executing: [E:\VisualStudio\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[   +1 ms] [  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.

Thank you.

**Comment by michaelspeed** [comment]
facing this same issue, but my fail logs looks like this -

`ClipboardService: Denying clipboard access to com.atmiyo.fiss.fiss_survey, application is not in focus neither is a system service for user 0`

this is the only log that makes sense. any solution to this?

**Comment by darshankawar** [comment]
@monkeyMax-SVG 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/72759
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by monkeyMax-SVG** [comment]
I just see that post but I cannot see exact solution.
finally, I wanna know it is already fixed or I need to wait for solution?

**Comment by monkeyMax-SVG** [comment]
Finally I just find issue. 
I was using flutter_login_facebook package.
When I remove it, it works perfectly.
Probably I need to do some setting for that package.
Let me share when I have solved it.

**Comment by MToheed** [comment]
@monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue. 
do you have any other solution?

**Comment by MToheed** [comment]
**build.gradle file**
buildscript {
    ext.kotlin_version = '1.4.31'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by samatzhusup** [comment]
> @monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue.
> do you have any other solution?

Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'

**Comment by yusufkorkmaz** [comment]
> > @monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue.
> > do you have any other solution?
> 
> Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'

This worked for me thanks

**Comment by MToheed** [comment]
> > @monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue.
> > do you have any other solution?
> 
> Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'

Hi, I just want to say thanks, buddy. Worked successfully for me.

**Comment by bllaw** [comment]
> 3.5.4

This works for me, thank you very much!

**Comment by mfirmansyahidris** [comment]
> > @monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue.
> > do you have any other solution?
> 
> Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'

I am so frustrated with image_picker ^0.6.7+22 that can open camera and gallery in release mode,
this is work for me, thank you so much!

**Comment by laway** [comment]
> Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'

This worked, thank you

**Comment by jangelRiveaux** [comment]
Hi every one. I am having the same error and I tried this solution but it does not fix it. Some know any other solution? 

> > @monkeyMax-SVG but I am not using flutter_login_facebook and facing the same issue.
> > do you have any other solution?
> 
> Hello! change in android/build.gradle classpath 'com.android.tools.build:gradle:3.5.4'
