### ISSUE TITLE
Fix Naming Convention

### ISSUE THREAD

**Issue by rrifafauzikomara** [flutter/flutter#75787]
Hi Flutter Team!

I'm new to contribute to open source, but I find some `parameters` in `TextField`, `TextFormField` which don't follow naming conversion like describe in the documentation ([here](https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase)).

This is the example widget that not follow the documentation for a naming convention:

```
TextField(
   autofocus: true,
   autocorrect: false,
)
```

**Comment by nt4f04uNd** [comment]
i think this breaking change is too nit a tradeoff is too big
moreover, i'm not arguing with the dart effective style, but with this particular name i personally prefer full lowercase as it is now, imo it looks a lot cleaner

**Comment by pedromassangocode** [comment]
Hi @rrifafauzikomara 
Flutter does not follow the Dart naming convention. Read more about the cases you described here: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#capitalize-identifiers-consistent-with-their-spelling.
