### ISSUE TITLE
[google_maps_flutter]: PlatformException

### ISSUE THREAD

**Issue by muddi900** [flutter/flutter#75784]
`Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setOnCameraMoveStartedListener(com.google.android.gms.maps.GoogleMap$OnCameraMoveStartedListener)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setOnCameraMoveStartedListener(com.google.android.gms.maps.GoogleMap$OnCameraMoveStartedListener)' on a null object reference`

The code to invoke the Maps page is:

```
`
[Future<void> _selectOnMap() async {
    final selectedLocation = await Navigator.of(context).push<LatLng>(
      MaterialPageRoute(
        fullscreenDialog: true,
        builder: (ctx) => MapScreen(
          isSelecting: true,
        ),
      ),
    );
    if (selectedLocation == null) {
      return;
    }
    _showPreview(selectedLocation.latitude, selectedLocation.longitude);
    widget.onSelectPlace(selectedLocation.latitude, selectedLocation.longitude);
  }
`

The code for the Maps page is:

`
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import '../models/place.dart';

class MapScreen extends StatefulWidget {
  final PlaceLocation initialLocation;
  final bool isSelecting;

  MapScreen({
    this.initialLocation = const PlaceLocation(
      latitude: 37.422,
      longitude: -122.084,
    ),
    this.isSelecting = false,
  });
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  LatLng _pickedLocation;

  void _selectLocation(LatLng position) {
    setState(() {
      _pickedLocation = position;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Your Map'),
        actions: [
          if (widget.isSelecting)
            IconButton(
              icon: Icon(Icons.check),
              onPressed: _pickedLocation == null
                  ? null
                  : () => Navigator.of(context).pop(_pickedLocation),
            ),
        ],
      ),
      body: GoogleMap(
        //mapType: MapType.hybrid,
        initialCameraPosition: CameraPosition(
          target: LatLng(
            widget.initialLocation.latitude,
            widget.initialLocation.longitude,
          ),
          zoom: 16,
        ),
        onTap: widget.isSelecting ? _selectLocation : null,
        markers: _pickedLocation == null
            ? null
            : {
                Marker(
                  markerId: MarkerId('m1'),
                  position: _pickedLocation,
                ),
              },
      ),
    );
  }
}
`](url)
```

**Comment by ArishSultan** [comment]
can you provide source code for `widget.onSelectPlace` and `_showPreview`

**Comment by muddi900** [comment]
```
 void _showPreview(double lat, double lng) {
    final staticMapImageUrl =
        LocationHelper.generateLocationPreviewImage(lat, lng);
    setState(() {
      _previewImageUrl = staticMapImageUrl;
    });
  }
```

```
Future<void> _selectOnMap() async {
    final selectedLocation = await Navigator.of(context).push<LatLng>(
      MaterialPageRoute(
        fullscreenDialog: true,
        builder: (ctx) => MapScreen(
          isSelecting: true,
        ),
      ),
    );
    if (selectedLocation == null) {
      return;
    }
    _showPreview(selectedLocation.latitude, selectedLocation.longitude);
    widget.onSelectPlace(selectedLocation.latitude, selectedLocation.longitude);
  }
  ```

**Comment by ArishSultan** [comment]
this is still unresolved `widget.onSelectPlace(selectedLocation.latitude, selectedLocation.longitude);`
the `_showPreview` method uses `LocationHelper` class you will need to provide them too.

**Comment by muddi900** [comment]
```
import 'package:http/http.dart' as http;

import 'dart:convert';

const GOOGLE_API_KEY = 'apiKeyString';

class LocationHelper {
  static String generateLocationPreviewImage(
      double latitude, double longitude) {
    return 'https://maps.googleapis.com/maps/api/staticmap?center=$latitude,$longitude&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:red%7Clabel:%7C$latitude,$longitude&key=$GOOGLE_API_KEY';
  }

  static Future<String> getPlaceAddress(double lat, double lng) async {
    final url =
        'https://maps.googleapis.com/maps/api/geocode/json?latlng=$lat,$lng&key=$GOOGLE_API_KEY';
    final response = await http.get(url);
    print(json.decode(response.body)['results'][0]['formatted_address']);
    return json.decode(response.body)['results'][0]['formatted_address'];
  }
}
```

**Comment by ArishSultan** [comment]
The Map is rendering perfectly at my side and there is no platform exception.

What version of flutter are you using?

**Comment by muddi900** [comment]
```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (3 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

I have tried it on multiple android emulators + My physical Pixel 3 Android 11 + Jan Security update. Google Play is on Dec 1,2020

**Comment by darshankawar** [comment]
@muddi900 
Please provide a complete minimal reproducible code sample in single file (main.dart) that we can copy paste and run in IDE to verify the issue.

**Comment by muddi900** [comment]
Can I give you access to the github repo? Would that be ok?

**Comment by darshankawar** [comment]
@muddi900 
You may share your repo link here that we can clone and verify the issue.

**Comment by muddi900** [comment]
You can check the whole code here:
https://github.com/muddi900/places_app

It is missing `location_helper.dart`. You can use the code above.

**Comment by darshankawar** [comment]
@muddi900 
Thanks for the repo. I cloned it and ran your app and saw the issue after tapping on `Select on Map` and then tapping on X which throws the `PlatformException`. But looking at the code snippet, you are checking below:

```
if (selectedLocation == null) {
      return;
    }
```
Ofcourse, if we are not selecting any map and directly tapping on X, the above method will be called returning a null instance of the map / controller. You need to figure out in this code block what to do after tapping on X and `selectiedLocation` is `null`.

I am going ahead and closing this as code implementation issue and not an issue with the plugin. If you disagree, write in comments and I'll reopen it.

**Comment by muddi900** [comment]
Ok. So the error is being thrown by null value.  The original issue remains, I can't see the map. The map is not rendering for me.

**Comment by darshankawar** [comment]
@muddi900 
I thought the original issue you filed was related to the `PlatformException` and not with map rendering (I may be mistaken).
Can you try the official `google_maps_flutter` [repo](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example) and see how the map is rendered in it ? That may give you an idea as why the map is not rendering.
