### ISSUE TITLE
smoother gradle setup (picking the right version)

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter#7578]
I tried out the hello_services app, and it said to run 'flutter config --gradle-dir'. I wasn't sure which one to download, so I installed the latest (3.3). It turns out this is the wrong one and it fails later, requiring version 2.10. I now see this version is specified in android/build.gradle.

It seems like we should save people a redundant gradle download by telling them which version to install, or at least explain how to figure this out? Better yet, maybe download gradle for them, since we already auto-download so many other things.

**Comment by abarth** [comment]
The intent is to use the gradle that comes with Android Studio.

**Comment by skybrian** [comment]
A bit of context: I'm attempting to run hello_services using the Flutter plugin in IDEA CE. The gradle build happens when I press the 'run' button from within the IDE, with a Nexus 5x hooked up. (Behind the scenes this uses 'flutter run'.) I don't have Android Studio installed, just the Android SDK.

I ran into an issue because the Android support libraries were not installed in the SDK. After that the gradle config was pretty messed up, so I deleted it and checked out a fresh version.

Now I get further when using 'flutter run', but I run into a different bug, causing 'lint' to fail.
 
GradleCompatible: Incompatible Gradle Versions
../../build.gradle:22: This support library should not use a different version (22) than the compileSdkVersion (25)
  19 }
  20 
  21 dependencies {
  22     androidTestCompile 'com.android.support:support-annotations:22.0.0'
  23     androidTestCompile 'com.android.support.test:runner:0.5'
  24     androidTestCompile 'com.android.support.test:rules:0.5'

It appears that something automatically modified the version numbers in android/app/build.gradle, messing it up. Here are the diffs:

 android {
-    compileSdkVersion 22
-    buildToolsVersion '22.0.1'
+    compileSdkVersion 25
+    buildToolsVersion '25.0.0'
 
So, 'flutter run' is not working. (I verified this is also the case outside the Flutter plugin.)

I started over and tried running gradle directly from the command line, following the instructions in the README. This failed because I didn't have Android API 22 installed, but after fixing that it build successfully.

After doing a manual build, running the app from the Flutter plugin worked, but it printed an error that made it look like it failed:

E/flutter (28515): [ERROR:../../flutter/runtime/dart_init.cc(129)] Isolate vm-service exited with an error
E/flutter (28515): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (28515): FileSystemException: Creation of temporary directory failed, path = '/data/local/tmp' (OS Error: Permission denied, errno = 13)
E/flutter (28515): #0      _Directory.createTemp.<anonymous closure> (directory_impl.dart:128)

Request to Dart VM Service timed out: _createDevFS({fsName: hello_services})
Error initializing DevFS: TimeoutException after 0:00:10.000000: Future not completed

So it appears that it's possible to get hello_services to work, but 'flutter run' doesn't do it right, at least not automatically. And even when it works it's pretty rough.

**Comment by abarth** [comment]
> I don't have Android Studio installed, just the Android SDK.

Android Studio is required to create Flutter apps that run on Android.  The configuration you're experimenting with is not supported.

**Comment by skybrian** [comment]
I'm confused then, because I'm pretty sure I'm working on a plugin for IDEA, not necessarily Android Studio. So far it's worked. Or do we require people to use two IDE's?

**Comment by devoncarew** [comment]
@skybrian, there's a team in AAR working on making the the workflow with gradle and flutter run better. The flutter plugin delegates to the flutter cli tool; if things aren't working great in the plugin, it's probably als not working great from the cli.

**Comment by abarth** [comment]
> Or do we require people to use two IDE's?

We don't require developers to use Android Studio.  We just require that it is installed on the system to create APKs, similar to how we require Xcode to be installed to created IPAs.

**Comment by abarth** [comment]
See Step 1 in the Android section of the setup guide: in https://flutter.io/setup/#android-setup

**Comment by abarth** [comment]
The reason this is relevant to this issue is that we don't want to create a smoother path for installing gradle because the intent is to use the version of gradle that is installed with Android Studio.  That also reduces the matrix of which versions of gradle we need to support because we need only support the version(s) that come with Android Studio.

**Comment by mit-mit** [comment]
Agree with the comments above; however, the current gradle versions in hello_services are outdated. I'll send a PR.
