### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)

### ISSUE THREAD

**Issue by Zeeshan-progs** [flutter/flutter#75782]
<html> 
<h1>  Logs </h>
</html>

<html> 
<br>
</html>
<html> 
<h1>  flutter Doctor  -v </h>
</html>

![Screenshot (19)](https://user-images.githubusercontent.com/67018643/107529663-1b041c80-6be1-11eb-93b4-7d0b30a9a28b.png)

**Comment by Zeeshan-progs** [comment]
Logs ------



D/ColorViewRootUtil(25456): nav gesture mode swipeFromBottom ignore false downX 369 downY 247 mScreenHeight 1600 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 3 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=369.0, y[0]=247.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=170158066, downTime=170158066, deviceId=4, source=0x1002, displayId=0 } rotation 0
E/flutter (25456): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method logIn on channel com.roughike/flutter_facebook_login)
E/flutter (25456): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter (25456): <asynchronous suspension>
E/flutter (25456): #1      FacebookLogin.logIn
package:flutter_facebook_login/flutter_facebook_login.dart:108
E/flutter (25456): <asynchronous suspension>
E/flutter (25456): #2      handleFBSignIn
package:firebaseauth/Facebook/facebookAuths.dart:24
E/flutter (25456): <asynchronous suspension>
E/flutter (25456): #3      loginWithFacebook
package:firebaseauth/Facebook/facebookAuths.dart:10
E/flutter (25456): <asynchronous suspension>
E/flutter (25456): #4      _FacebookState.build.<anonymous closure>.<anonymous closure> (package:firebaseauth/Facebook/facebookScreen.dart)
package:firebaseauth/Facebook/facebookScreen.dart:1
E/flutter (25456): <asynchronous suspension>
E/flutter (25456):

**Comment by Zeeshan-progs** [comment]
<html><h1> flutter channel </h1></html>


![Screenshot (19)](https://user-images.githubusercontent.com/67018643/107530331-c7de9980-6be1-11eb-9cc8-83187fa8f36b.png)

<html>
<h1>
flutter doctor</h1>
</html> 

![Screenshot (20)](https://user-images.githubusercontent.com/67018643/107530456-e3e23b00-6be1-11eb-90bc-13c9f7cc35af.png)

**Comment by iapicca** [comment]
@Zeeshan-progs 
[flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/roughike/flutter_facebook_login/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by pedromassangocode** [comment]
Closing as invalid. Please see https://github.com/flutter/flutter/issues/75782#issuecomment-776807766 for more information.
Thank you
