### ISSUE TITLE
[local_auth] authentication call Iris instead of Fingerprint

### ISSUE THREAD

**Issue by apoleo88** [flutter/flutter#75781]
## Steps to Reproduce on Samsung S8, SM G950F

1# Register fingerprint to your device and enable it to unlock the screen.
2# Register irises for iris scanning and enable it in Knox Secure Area
3# Attempt biometric authentication via local_auth plugin on an app installed on the regular area (not in knox)

**Expected results:** 
Ask for fingerprint authentication.

**Actual results:** 
Ask only for Iris Scanner.

More details:
Iris Scanner is disabled to unlock the screen, but it is enable to authenticate on Knox secure area.

There is no way to ask for a specific authentication method to local_auth, and even if the app is installed in the "common area" and not in the knox secure area, local_auth ask for Iris authentication on:
`await localAuth.authenticateWithBiometrics(localizedReason: 'Please authenticate'); `

**Comment by darshankawar** [comment]
@apoleo88 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/41272
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
