### ISSUE TITLE
Different treatment to variables in debug and release mode

### ISSUE THREAD

**Issue by juppdes** [flutter/flutter#75780]
By example this function:

`
static navega(context, page) {   
 actualProgram = page.toString();
 Navigator.push(context, MaterialPageRoute(builder: (context) {
           return page;
 }));
}
`

In debug mode, calling this function "**navega(context, Customers());**", 
the content of the currentProgram variable will be "**Customers**", and in Release mode it will be "**Widget**".

How should I handle these differences? Is this right ?

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19042.746], locale pt-BR)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\juppd\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.53.1)
    • VS Code at C:\Users\juppd\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • SM T295 (mobile)                   • R9XMB03Y34H   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```
</details>

**Comment by pedromassangocode** [comment]
Hi @juppdes 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by juppdes** [comment]
`import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            navega(context, SecondRoute());
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}

navega(context, page) {
  String actualProgram = page.toString();
  print(actualProgram);
  Navigator.push(context, MaterialPageRoute(builder: (context) {
    return page;
  }));
}`

**Comment by pedromassangocode** [comment]
Hi @juppdes 

You should specify the type of date your function requires:

```
navega(BuildContext context, Widget page) {            // changed this line
  String actualProgram = page.toString();
  print(actualProgram);
  Navigator.push(context, MaterialPageRoute(builder: (context) {
    return page;
  }));
}
```

Debug and release builds are different, to lean more see https://flutter.dev/docs/testing/build-modes.

**Comment by juppdes** [comment]
Hi @pedromassango ,

Even specifying the type of data in the function, the return of the print remains "Widget" and not the name of the screen, as in Debug mode. Is there any way to resolve this?
