### ISSUE TITLE
Turn on --assert-initializer, --assert-message, and --initializing-formal-access in the VM

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7579]
cc @abarth, @jason-simmons 

It's possible --initializing-formal-access is already on by default, see dart-lang/sdk#27891.

**Comment by sethladd** [comment]
Helps resolve https://github.com/flutter/flutter/issues/5865

**Comment by Hixie** [comment]
I can't find any evidence that --enable-assert-initializer is a thing. I think the other two are already implemented by default.

**Comment by Hixie** [comment]
Ah maybe the problem is the "enable" part. Correcting title.

**Comment by eseidelGoogle** [comment]
@jason-simmons can you take this on?  This would unblock us deploying const asserts in the Framework, which may be a big perf win.

**Comment by jason-simmons** [comment]
This can be enabled by adding "--assert-initializer" to the kDartCheckedModeArgs list in flutter/runtime/dart_init.cc

@Hixie @abarth is this something that we should land now?  Or do you want to experiment with this feature before committing it?

**Comment by Hixie** [comment]
Yeah we should just land it. We want to enable `assert_initializer`, and probably while we're there `await_is_keyword` and `warn_super`.
