### ISSUE TITLE
Disable long press context menu

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#75791]
## Use case
Disable long press context menu

## Proposal
Would it be possible to add a feature to allow disabling/prevention of the long press context menu. The one that appears after text selection and includes "copy / paste / web search"

**Comment by pedromassangocode** [comment]
Hi @carman247 
Have you tried `enableInteractiveSelection` of text fields? It disable long-press context menu.

```dart
TextField(
    enableInteractiveSelection: false,
)
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
