### ISSUE TITLE
allow to simulate Platform

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#75795]
allow to fake Platform to opt in/out of different widget behaviors
it should be scoped, like Theme (even might be a part of it?)

### use cases
* i would like to show `materialTextSelectionControls` in web, but even if i explicitly pass them to `selectionControls` - they are simply not shown
* opting out of oncoming desktop scrollables changes https://github.com/flutter/flutter/pull/75728, https://github.com/flutter/flutter/pull/75354

and other places where there are platform-specific behaviors

**Comment by pedromassangocode** [comment]
Hi @nt4f04uNd 
I'm not really sure if I understood your proposal. Can you please elaborate?
Do you want to simulate platform or opting out of oncoming feature?



> * opting out of oncoming desktop scrollables changes #75728, #75354

I would suggest to either wait for it to land or leave your suggestion in the issue that those PRs are closing or even in the PRs itself as the feature is not even implemented.


> * i would like to show `materialTextSelectionControls` in web, but even if i explicitly pass them to `selectionControls` - they are simply not shown

I may be wrong but this sounds like an issue or a feature request since (AFAIK) web does not use text selection controls. Do you have any reproducible code sample?

**Comment by nt4f04uNd** [comment]
> allow to fake Platform to opt in/out of different widget behaviors
> it should be scoped, like Theme (even might be a part of it?)

@pedromassangocode i'm suggesting to add a distinct Platform that we could change contextually dependent on our needs

> Do you want to simulate platform or opting out of oncoming feature?

the former one as a way of doing the latter. adding such thing would allow to opt out of any platform-specific behavior. as you can see at the OP, i mentioned those specific PRs as use cases

> I would suggest to either wait for it to land or leave your suggestion in the issue that those PRs are closing or even in the PRs itself as the feature is not even implemented.

this would not be required with adding suggested in this issue feature

> I may be wrong but this sounds like an issue or a feature request since (AFAIK) web does not use text selection controls. Do you have any reproducible code sample?

same case as per mentioned PRs - this is a use case

to elaborate even more, since after your answer i feel like you don't understand what "use case" means

***use case*** - is a case of someone willing to do something, but not necessarily able of doing at the time being

**Comment by nt4f04uNd** [comment]
i discovered this is already implemented in TargetPlatform and ThemeData.platform lol
