### ISSUE TITLE
android scrollbar fidelity

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#75806]
reproducible https://github.com/nt4f04unds-archive/issues/tree/flutter_75806

i will discuss three versions of scrollbar on android
* flutter per 1.24 https://github.com/flutter/flutter/commit/183f0e797a3bf8aa1b35b650150f7522d5d10377 (see doctor below)
* flutter per master 1.26 https://github.com/flutter/flutter/commit/16af4aa7ebf549f893ebed12106c45adb9440fbd
* native

<details>
<summary>flutter doctor -v (1.24)</summary>

```
[√] Flutter (Channel nt4f04und_texture, 1.24.0-8.0.pre.377, on Microsoft Windows [Version
    10.0.19041.746], locale ru-RU)
    • Flutter version 1.24.0-8.0.pre.377 at c:\dev\src\flutter
    • Framework revision f9e981a348 (22 hours ago), 2021-02-10 01:23:02 +0300
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64 • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86   • Android 11 (API 30) (emulator)     

• No issues found!
```
</details>

here are videos for each of them

https://user-images.githubusercontent.com/39104740/107566108-7e984500-6bf5-11eb-901f-ad93e474cc34.mp4

https://user-images.githubusercontent.com/39104740/107566117-835cf900-6bf5-11eb-8d5b-18317e087ada.mp4

https://user-images.githubusercontent.com/39104740/107567523-d5eae500-6bf6-11eb-9f09-c98726b4dd39.mp4

## 1.24

differences:
1. scrollbar has different color (comparing on same `#ffffff`)

* 1.24 `#bfbfbf`
* native `#b4b4b4`

screenshots accordingly
* ![1.24](https://user-images.githubusercontent.com/39104740/107569941-efd9f700-6bf9-11eb-8b4d-a4c60fe3b0b5.png)
* ![native](https://user-images.githubusercontent.com/39104740/107569962-f2d4e780-6bf9-11eb-83c5-892e2f63e64e.png)

2. scrollbar consumes drag events and doesn't allow to scroll the scrollable beneath it
3. <strike>width</strike> - it was fixed in master so not paying attention to this

## 1.26

this version changes the scrollbar in a really weird way and introduced even more differences:

1. instead of making scrollbar click-through, added drag support that was enabled by default (and cannot be disabled)
   - this should not be like that. by default it should match native - not draggable, and should be enabled via `draggable` parameter or something like that. not to say that such behavior by default is not expected neither by developer, nor by user
2. default color changed and the scrollbar now bearly noticable and differs even more from the native one

a few more notes:
* small: i feel like the fade curves and durations are slightly different as well
* i doubt draggable scrollbar should be with this implementation on android at all. with large and complex lists it can drop fps ***really hardly***. it was ok for ios because it represents the native behavior and apple devices are in gerenal more performant, so these peformance pressures wasn't felt like a lot, which is yet again not the case for the most of android devices. this is related to https://github.com/flutter/flutter/issues/52207

what what what and what (and why (and how))

/cc @Piinks

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hi @nt4f04uNd thanks for the accounting over different versions of flutter, I am going to be focusing on the current behavior on master. The other versions of scrollbar you mentioned are not actionable, as they do not reflect the latest version.

I can confirm the recent refactoring of scrollbars did not change the fade curves and durations.

I appreciate your concern for adhering to native behavior. We can certainly expose whether or not the scrollbar should be draggable, there are draggable scrollbars on Android in some native applications, so I believe it should still be available on Android. I'll see about adding the ability to turn dragging off.

I don't see how https://github.com/flutter/flutter/issues/52207 is related specifically to the Scrollbar. The Scrollbar certainly exposes the fact that a **really** high scrolling velocity will impact UI rendering, but the root cause of this is not the Scrollbar. There is a similar issue where I discussed this further in https://github.com/flutter/flutter/issues/75399#issuecomment-780133956
If there is a separate performance issue related to scrollbar, please update here. :)

> what what what and what (and why (and how))

Please see https://github.com/flutter/flutter/issues/70866 and #74907 for reference.

**Comment by nt4f04uNd** [comment]
> I'll see about adding the ability to turn dragging off.

what about making it turned off by default?

> I don't see how #52207 is related specifically to the Scrollbar.

https://github.com/flutter/flutter/issues/52207 has the same cause as https://github.com/flutter/flutter/issues/75399 which you discussed in https://github.com/flutter/flutter/issues/75399#issuecomment-780133956. this can be proven by fact that scrollbar internally uses jumpTo

and you still didn't cover these two

> scrollbar consumes drag events and doesn't allow to scroll the scrollable beneath it
> 2. default color changed and the scrollbar now bearly noticable and differs even more from the native one

**Comment by Piinks** [comment]
> > I'll see about adding the ability to turn dragging off.
> 
> what about making it turned off by default?

I think that would cause confusion for users to add more complexity to default behaviors on varying platforms, but we can take a look when I have a patch available.

> and you still didn't cover these two

I considered these trivial and not in need of further discussion. Changing a color is an easy fix, and if there are no gestures enabled then the consumption of drag events is a non-issue.

This is actively being worked on. I appreciate your patience.
