### ISSUE TITLE
[web] we need to warm-up CanvasKit renderer shaders

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#75801]
Currently shader warm-up is conditional behind `kIsWeb` flag because the HTML renderer crashes during warm-up. Because the flag doesn't distinguish between HTML and CanvasKit we end up not warming up CanvasKit either. This leads to jank in the middle of animations after the app starts up. We need a way to do the shader warm-up for the CanvasKit renderer.

**Comment by franarolas** [comment]
I'm experiencing a huge initial load difference from version 1.26 to 1.25, can it be related? The load time in 1.26 is like 2x times the load time in 1.25.

**Comment by yjbanov** [comment]
> I'm experiencing a huge initial load difference from version 1.26 to 1.25, can it be related? The load time in 1.26 is like 2x times slower than the load time in 1.25.

Unlikely. Typically initial load is affected by the download size and strategy. Currently, CanvasKit is 2.3MB when compressed using Brotli, and we start downloading it later than we could.
