### ISSUE TITLE
Execution failed for task ':compileGroovy'.

### ISSUE THREAD

**Issue by albertog** [flutter/flutter#7580]
When you try to compile:

Running 'flutter packages get' in flutter-camera-plugin-master... 1928ms
Launching lib/main.dart on SM G930F in debug mode...
Running 'gradle wrapper'...                              
:buildSrc:clean
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Could not open cache directory workerMain (/home/albertog/.gradle/caches/2.13/workerMain).
   > com/tonicsystems/jarjar/asm/commons/SignatureRemapper

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this issue.  Presumably this is attempting to compile https://github.com/FaisalAbid/flutter-camera-plugin from @FaisalAbid?

It looks like it's having trouble opening a cache directory on your system?

**Comment by Hixie** [comment]
Not sure how to reproduce this. Please file a new bug with more details so that we can address the problem. Thanks.
