### ISSUE TITLE
Duplicate #includes of the Pods-Runner xcconfig

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75817]
The tool is adding `#include?` and `#include` imports of the `Pods-Runner` xcconfig.
```
#include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
#include "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
```
Caused by https://github.com/flutter/flutter/pull/73112

**Comment by jmagman** [comment]
This dirties the working copy of any project using plugins created before https://github.com/flutter/flutter/pull/73112 on a `flutter pub get`, `build`, `run`, etc.
Request for cp.

**Comment by digitalwert-developer** [comment]
we have the same problem with duplicated includes or faulty includes which produce linker issues. it generally works after the 3. or 4. try when flutter clean is performed followed by flutter build, followed by retrying in xcode. Is there a better workaround regarding linker issues?
:)

**Comment by jmagman** [comment]
@digitalwert-developer I don't think this `include` duplication would cause any linker issues.  Can you file a new issue and completely fill out the template?  Include a `--verbose` flutter run so I can see the linker flags and errors.
