### ISSUE TITLE
Samsung S3 Android 4.4

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7581]
Ends at libsky_shell. Not the latest engine, curious if something already fixed.

Build fingerprint: 'samsung/d2lterefreshspr/d2lterefreshspr:4.4.2/KOT49H/L710TVPU0AOH1:user/release-keys'
Revision: '14'
pid: 5873, tid: 5899, name: AudioRecord >>> harpsoft.bendometer.ui.android <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000010
r0 5c72c7b8 r1 6741b988 r2 6741b95c r3 6741b958
r4 5c9cccd8 r5 6741b988 r6 00000000 r7 00000000
r8 00000000 r9 6328cef4 sl 6553f680 fp 6741ba04
ip 00000000 sp 6741b948 lr 612448cd pc 6125fb36 cpsr 000b0030
d0 0000000000000000 d1 0000000000000000
d2 0000000000000000 d3 0000000000000000
d4 3fe0000001307180 d5 408f400000000000
d6 0000000900000000 d7 3ce3f3b645a1cac0
d8 0000000000000000 d9 0000000000000000
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 6374695063696d10 d17 00300030002e0038
d18 412e848000000000 d19 3fd999cdcc446c61
d20 3ff7ced916872b02 d21 4097400000000000
d22 3fd2494f4a5fda06 d23 3fcc720d0de8ad34
d24 3fc746aa1b0a4652 d25 3fc2f112df3e5244
d26 4097400000000000 d27 4000000000000000
d28 3ffbdda2f05dadd4 d29 bfd3e2d6389f3b8c
d30 3ff0000000000000 d31 4000000000000000
scr 88000011

backtrace:
#00 pc 00092b36 /data/app-lib/harpsoft.bendometer.ui.android-1/libsky_shell.so
#1 pc 000596eb /data/app-lib/harpsoft.bendometer.ui.android-1/libsky_shell.so
#2 pc 000595bd /data/app-lib/harpsoft.bendometer.ui.android-1/libsky_shell.so
#3 pc 00020d8c /system/lib/libdvm.so (dvmPlatformInvoke+112)
#4 pc 00051ae7 /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
#5 pc 0002a220 /system/lib/libdvm.so
#6 pc 000316d0 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#7 pc 0002ed68 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#8 pc 00064035 /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
#9 pc 0004d617 /system/lib/libdvm.so
#10 pc 0000ec55 /data/app-lib/harpsoft.bendometer.ui.android-1/libSuperpoweredExample.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+40)
#11 pc 0000ebdf /data/app-lib/harpsoft.bendometer.ui.android-1/libSuperpoweredExample.so
#12 pc 000110b5 /data/app-lib/harpsoft.bendometer.ui.android-1/libSuperpoweredExample.so
#13 pc 00009e83 /system/lib/libwilhelm.so
#14 pc 00060f1b /system/lib/libmedia.so (android::AudioRecord::processAudioBuffer(android::spandroid::AudioRecord::AudioRecordThread const&)+666)
#15 pc 00061085 /system/lib/libmedia.so (android::AudioRecord::AudioRecordThread::threadLoop()+164)
#16 pc 0000e9ed /system/lib/libutils.so (android::Thread::_threadLoop(void*)+104)
#17 pc 0000e58f /system/lib/libutils.so
#18 pc 0000d280 /system/lib/libc.so (__thread_entry+72)
#19 pc 0000d418 /system/lib/libc.so (pthread_create+240)

code around pc:
6125fb14 61256920 6801b120 e8bd69c9 470840b0
6125fb24 0000bdb0 b08bb5f0 4606460d fec9f7e4
6125fb34 69316804 68066820 f7fea801 6828fbd8
6125fb44 90032700 602f2010 ee06f7c0 ad044912
6125fb54 44799008 60013108 60419901 97029902
6125fb64 99036081 462060c1 97034629 980847b0
6125fb74 d00342a8 6801b128 e0016949 69096801
6125fb84 98034788 f7c8b108 9802fa45 f7c7b108
6125fb94 b00bfc96 bf00bdf0 006eb99e b08bb5f0
6125fba4 460e4615 f7e44607 6804fe8c 68206939
6125fbb4 46686807 fb9bf7fe e9cd2014 f7c06502
6125fbc4 4911edcc 4479ad04 60013108 60419900
6125fbd4 60819901 91012100 1202e9dd 1203e9c0
6125fbe4 90084629 47b84620 42a89808 b128d003
6125fbf4 69496801 6801e001 47886909 b1089801
6125fc04 fc5df7c7 bdf0b00b 006eb94e b08ab570

code around lr:
612448ac 00737712 00513c34 00513c58 007376ee
612448bc f7ffb580 3004ffdb b580bd80 ffd6f7ff
612448cc bd803008 f7ffb580 300cffd1 0000bd80
612448dc b0a6b5b0 48184604 68004478 4818b158
612448ec 4a162103 44782333 447a9000 f367a801
612448fc f367fcf1 2010fdbd ef2af7db 48114605
6124490c 0050efc0 44784621 46286005 0a8ff945
6124491c f81af000 1d281d21 f816f000 0108f104
6124492c 0008f105 f810f000 010cf104 000cf105
6124493c f80af000 bdb0b026 007376a8 00513bce
6124494c 00513bfc 0073767a 4604b510 b1406808
6124495c e8503004 32012f00 2300e840 d1f82b00
6124496c 68216808 b1916020 f3bf1d08 e8508f5b
6124497c 1e4a1f00 2300e840 d1f82b00 d1062901
6124498c f3bf3804 bf1e8f5b 69496801 46204788
6124499c b5f0bd10 466eb08d 46304604 f023460d

**Comment by eseidelGoogle** [comment]
Can you tell us what version of Flutter this was built with?  With that information we (or you) can symbolicate the trace following:
https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks
We need to make that easier. :(  But at least it's written down as a start.

**Comment by Hixie** [comment]
This issues has insufficient information to be actionable. Please, if you see this still, file a new bug with steps to reproduce so that we can try it locally. Thanks!
