### ISSUE TITLE
[proposal] add label overflow property on TextField

### ISSUE THREAD

**Issue by DN-1596** [flutter/flutter#75830]
## Use case

When the material textfield label is too long currently the ui just shows ellipsis. This leads to loss in information that is being conveyed to the user. 

This is related to the problem mentioned in https://github.com/flutter/flutter/issues/30439 

However the solution provided in that problem still doesn't solve the use case wherein the entire label has to be shown. 

## Proposal

Please refer to the following design for a textfield, here in unfocused state the entire label is being shown however in focused state the label is shown with ellipsis , this design solves my use case as the user is conveyed the entire information at some point in time. 

UNFOCUSED STATE : 
![Screenshot 2021-02-11 at 1 07 31 PM](https://user-images.githubusercontent.com/38540693/107611982-33b91480-6c6b-11eb-86db-1672c3f75a9e.png)

FOCUSED STATE: 
![Screenshot 2021-02-11 at 1 08 17 PM](https://user-images.githubusercontent.com/38540693/107612001-3ddb1300-6c6b-11eb-9737-a53c7b72146b.png)

**Comment by pedromassangocode** [comment]
Similar to https://github.com/flutter/flutter/issues/20569 that is being worked in https://github.com/flutter/flutter/pull/72602.
