### ISSUE TITLE
Observatory won't load sometimes

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#7583]
I'm running off the latest from `master`. I've encountered this twice where I can't load the Observatory site. This has happened twice now, and both times I've been able to get Observatory to work by cleaning the build or deleting the build folder. This doesn't always work though.

I'm using a Genymotion Android emulator.

## Steps to Reproduce
1. Run flutter application from command line or IntelliJ.
2. Copy / Paste Observatory link into browser
3. See that Observatory doesn't load.

**Comment by Hixie** [comment]
It would be valuable to try to figure out what's going on if you see this again.

Things to check:
- does adb think there's any port-forwarding going on?
- is the relevant port itself not responding, or is the problem that once we connect the server is dead?
- is the application hung in some way?

**Comment by ScottPierce** [comment]
* I tried restarting my emulator, and when that didn't work I also tried restarting my computer. Restarting my computer has always resolved any adb issues I've encountered.
* How would I check this?
* The application was very responsive

**Comment by Hixie** [comment]
For the adb thing, I forget the exact commands but adb has a series of commands you can give it to list the currently forwarded ports, and so forth.
For whether the port is responding, you can try telnetting into the port, for example.

**Comment by ScottPierce** [comment]
Debugging with @Hixie has given the following results:

```
flutter: Diagnostic server listening on http://127.0.0.1:39408
flutter: Observatory listening on http://127.0.0.1:39173/
```

```
adb forward --list
192.168.56.101:5555 tcp:8101 tcp:46665
192.168.56.101:5555 tcp:8100 tcp:33870
192.168.56.101:5555 tcp:8103 tcp:35070
192.168.56.101:5555 tcp:8102 tcp:36037
192.168.56.101:5555 tcp:8105 tcp:39408
192.168.56.101:5555 tcp:8104 tcp:39173
```

In the above scenario, `http://127.0.0.1:39173/` fails to connect to observatory, but `http://127.0.0.1:8104/` works.

**Comment by cbracken** [comment]
@johnmccutchan 
@tvolkert (who may have landed a workaround)

**Comment by ScottPierce** [comment]
I haven't been using flutter recently, so I'm not sure.

**Comment by sethladd** [comment]
Fair enough :)

Closing this for now, but happy to reopen if it happens again.

Thanks again for the feedback!
