### ISSUE TITLE
microbenchmarks_ios running for hours without timing out

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75851]
Logs:

https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/godofredoc_google.com/15e28fdf5416728310250fe80d868d178b795977279a5341418a44dcbd936cb4/+/annotations

There are two problems here:

# Test level

The runner is not progressing from:

```
[microbenchmarks_ios] [STDOUT] [  +58 ms] Successfully connected to service protocol: http://127.0.0.1:53924/
[microbenchmarks_ios] [STDOUT] [  +14 ms] Application running.
[microbenchmarks_ios] [STDOUT] [   +5 ms] Connected to iPhone
[microbenchmarks_ios] [STDOUT] [   +2 ms] Flutter run key commands.
[microbenchmarks_ios] [STDOUT] [   +1 ms] h Repeat this help message.
[microbenchmarks_ios] [STDOUT] [        ] c Clear the screen
[microbenchmarks_ios] [STDOUT] [        ] q Quit (terminate the application on the device).
[microbenchmarks_ios] [STDOUT] [        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:53927/7vUpRFk2E18=/
```

# Task level

The task should be timing out in 30 mins after we start using static xcode installations or 1 hour max before that.

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by jmagman** [comment]
Let's use this one to track the task level infra problem that it's not timing out.  Filed https://github.com/flutter/flutter/issues/76163 to track the test not progressing.

**Comment by Hixie** [comment]
should I understand from the last comment that this should be put onto the infra queue?

**Comment by jmagman** [comment]
You're right, I put the `team: infra` keyword on it.  It's already being tracked via the `[infra] Devicelab on LUCI` project.

**Comment by godofredoc** [comment]
Closing as obsolete this was a one time issue related to buildbucket backend failures.
