### ISSUE TITLE
[web] service worker code should be upgradeable with Flutter SDK upgrades

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#75869]
Currently we embed the service worker loading code into the source `index.html` file with `flutter create` ([example](https://github.com/flutter/flutter/blob/236ee295bd90342cf2530f74f679072d0cd554d3/dev/integration_tests/web/web/index.html#L21)). This is efficient because a single HTTP request can load both the HTML and bootstrap the app. It also makes it easy to customer service worker loading in advanced situations. However, when the app upgrades to a new version of the Flutter SDK it doesn't get the new service worker code.

This is a feature request to provide an easy way to upgrade service worker loading code, while still allowing advanced use-cases to supply their own.

## Option 1: use a special tag for embedding service worker code

`flutter create` (or the developer) puts a special tag in `index.html` that Flutter Tools knows to replace with service worker loading code during `flutter build` and `flutter run`. For example, we could use a special HTML comment like this:

```html
<!-- flutter_service_worker_loader -->
```

Flutter Tool would look for this exact comment and replace it with service worker loading code. Advanced use-cases that prefer custom service worker loading can simply remove this comment and add their own code.

A disadvantage of this approach is that what you see in your source `index.html` is not what you see loaded in the browser.

## Option 2: move service worker code into a separate JS file

We replace the inline JavaScript with `<script src="path/to/flutter_service_worker_loader.js">`. Similar to Option 1, advanced use-cases can replace this tag with their own.

A disadvantage of this approach is that it requires one extra HTTP fetch before it starts loading the app. It also requires extra care in version management of the loading JS file. Option 1 doesn't have this problem.

## Option 3: edit service worker code in place

In this option we keep the full JavaScript embedded in `index.html` like we do today. However, during upgrade we edit it and replace with the new version. This is as efficient as Option 1, because it only needs on HTTP fetch to start loading the app.

A disadvantage of this approach is that it requires even more magic in the upgrade logic than Option 1. The upgrade process needs to answer several questions prior to upgrade:

- Which `<script>` tag should I edit (there could be many)?
- Does the loading code contain hand-edited code?
- Should the upgrade proceed automatically? Or should the user confirm the upgrade?

This would create more cognitive overhead for the developer, and add complexity to the Flutter Tool.

## Recommendation

Option 1 seems the best overall. The magic that it provides is not too magical because `index.html` is explicitly requesting that we embed the service worker loader. The magic is trivial: replace the special comment with some JavaScript. This option also retains performance and customizability of today's approach.

**Comment by eliabieri** [comment]
Why was this marked as complete?
