### ISSUE TITLE
win_tool_integration_tests is flaky

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#75860]
win_tool_integration_tests is flaky.

[Sample run](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8855573068568148480/+/steps/run_test.dart_for_tool_integration_tests_shard_and_subshard_3_3/0/stdout)

Failure:

```
(process terminated with exit code 0)
The subprocess terminated before all the expected transitions had been matched.
The transition that we were hoping to see next but that we never saw was:
    4 NOW WAITING FOR> "ready", "called main", "called paint" (matched 2 so far)

06:18 +8 ~3 -1: test\integration.shard\overall_experience_test.dart: flutter run can hot reload and hot restart, handle "p" key [E]                                                                    
  Missed some expected transitions.
  test\integration.shard\overall_experience_test.dart 275:5  runFlutter
```

**Comment by jmagman** [comment]
@Hixie I believe this is relevant to your interests. https://github.com/flutter/flutter/pull/74533

**Comment by Hixie** [comment]
Aha, the problem is that we put the `called main` line on the same line as `Performing hot restart`. I guess the device is faster than the host.
```
stdout: Performing hot restart...                                       called main
```
