### ISSUE TITLE
Flutter release exception on dev/master channel but not on stable

### ISSUE THREAD

**Issue by febg11** [flutter/flutter#75874]
Hi 

I am having some issues with running my plugin in release mode when on master/dev channels. When running the same code on stable channel it works fine.

I dont actually get any error on the app, it just closes immediately. 

I managed to find where it crashes using the logcat when on dev channel. 

```
2021-02-11 20:57:37.310 4511-4511/? E/VLC/JNI/VLCObject: FindClass(org/videolan/libvlc/interfaces/IMedia$Track) failed
2021-02-11 20:57:37.310 4511-4511/? E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.example.<PROJECT_NAME>_example-21j3LdWeSIilfuuESQrnAw==/base.apk!/lib/arm64-v8a/libvlcjni.so"
```

I have read on <a href='https://stackoverflow.com/questions/52571279/android-cant-load-vlcjni-library-libvlc'> this</a> which says that it is linked to proguard... Is it safe to modify this in flutter or there a better way to fix this problem? (if this is even the cause) 

Here is my flutter doctor for dev which fails
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on Mac OS X 10.15.5 19F101 darwin-x64,
    locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.4.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
```

My flutter version for stable is 
```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB)
```

I have tried recreating the plugin with the flutter create command and copying my android code in, but this doesn't seem to help. 

Can any one suggest any solutions? 

Thanks a lot

**Comment by pedromassangocode** [comment]
Hi @febg11 
Can you please provide your `flutter doctor -v`, your `flutter run --release --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by febg11** [comment]
Dont worry pedro, it turned out to be the vlc player plugin... i don't know why but it crashes on master branch. I will close this now.
