### ISSUE TITLE
Android SDK 24 can lead to crashes with devices and Macs, but flutter tool says 24 is OK

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7588]
We diagnosed a problem with crashing from device+flutter+mac. After the user upgraded to Android SDK 25, the crashes stopped. See https://github.com/flutter/flutter/issues/7332#issuecomment-274401118

We might want to change `flutter tool` to prompt the user to upgrade to Android 25. Right now, flutter tool says 24 is OK.

**Comment by sethladd** [comment]
I confirmed with our user that once he upgraded to Android SDK 25, his crashes went away.

We recommend that `flutter doctor` suggest the user upgrade to 25.

Are we aware of a reason to continue to prefer 24?

**Comment by sethladd** [comment]
cc @abarth or @jason-simmons  might know some background here...

**Comment by sethladd** [comment]
Hi. This might help avoid issues for new users on macs. If this is easy, can we do this by/before March 8th ?

**Comment by abarth** [comment]
I'm not aware of any reason to prefer SDK 24.

**Comment by eseidelGoogle** [comment]
Sounds like a simple fix to `flutter doctor`:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L15
Looks like we check a bunch of versions, but not sure we require one yet.

**Comment by mit-mit** [comment]
@johnmccutchan are you looking at this one?

**Comment by johnmccutchan** [comment]
https://github.com/flutter/flutter/pull/8462
