### ISSUE TITLE
[Web]Tooltip widget meets accessibility standard

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#75885]
According to the new internal accessibility rating, the tool tip needs to fulfill two requirements

1. It needs to be dismissible, developer (or by default) can implement an interaction that allows users to dismiss the tooltip without moving the pointer hover or keyboard focus. It also need to be dismissible through esc key.
2. toolbar needs to be hoverable itself. Currently, the tooltip will be dismissed right after the pointer exit the target. We need to make it so the tooltip will stay on when pointer exit the target and hover over the actually tooltip box.

**Comment by yjbanov** [comment]
It doesn't look like there are action items on the web engine side, so I removed the web label. However, if anything needs to be done in the engine, feel free to add the label back.

**Comment by chunhtai** [comment]
although the work will likely need to be done in framework side, but this is an engine only issue because the tooltip works differently between mobile and web. There is no hover in mobile, you can only trigger tooltip by long pressing.
