### ISSUE TITLE
[Web] flutter app is accessible when uses NVDA

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#75880]
NVDA is the windows only screen reader https://www.nvaccess.org/

We need to make sure our flutter web application on windows browser is accessible through NVDA

**Comment by yjbanov** [comment]
@chunhtai Can you please assign a priority for this issue?

**Comment by chunhtai** [comment]
assigning p3 because this is something we should looking to next quarter.

As far as i know the new accessibility standard will be enforced around middle 2021 (I will confirm the exact day shortly), but that is a hard requirement only for mobile. I am not sure how this will affect web, please feel free to re-adjust.

**Comment by Radeonisos** [comment]
Hello
Do you have any information about this subject ?
Other questions : Can we modify or delete the sentence when we arrive on a web site flutter "button accessibility press for activate ..." ?

**Comment by yjbanov** [comment]
NVDA works. We do have bugs to fix, but no work remains to be done to bring up initial support. So I'm closing this as fixed.
