### ISSUE TITLE
flutter_plugins analyze shard is failing with path_provider_windows analyzer warning 'unpackString' is deprecated and shouldn't be used

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75890]
Tree is closed on flutter_plugins error.
```
Checking project path_provider_windows...

  info - 'unpackString' is deprecated and shouldn't be used at lib/src/path_provider_windows_real.dart:37:33 - (deprecated_member_use)
  info - 'unpackString' is deprecated and shouldn't be used at lib/src/path_provider_windows_real.dart:67:23 - (deprecated_member_use)
  info - 'unpackString' is deprecated and shouldn't be used at lib/src/path_provider_windows_real.dart:135:37 - (deprecated_member_use)
  info - 'unpackString' is deprecated and shouldn't be used at lib/src/path_provider_windows_real.dart:187:30 - (deprecated_member_use)
...
The following packages have analyzer errors (see above):
 * path_provider_windows
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8855548098372693696/+/steps/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/0/stdout

I reproduced this locally as well.

**Comment by jmagman** [comment]
When I ran it locally the pubspec.lock shows win32 at `2.0.0-nullsafety.12`
```
  win32:
    dependency: "direct main"
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0-nullsafety.12"
```

**Comment by jmagman** [comment]
I guess path_provider_windows pubspec.yaml needs to be pinned to < 2.0.0-nullsafety.12 where this was deprecated \cc @timsneath https://github.com/timsneath/win32/commit/3938010cc468d00279fe7b42ec87e1d21fba5e4e

https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_windows/pubspec.yaml#L20
```dart
  win32: ^2.0.0-nullsafety.10
```

**Comment by timsneath** [comment]
Yup -- pending PR here: 
https://github.com/flutter/plugins/pull/3540

The breaking change is in `ffi`, not `win32`...

**Comment by jmagman** [comment]
https://github.com/flutter/plugins/pull/3540 was merged.  Should be fixed with plugins roll https://github.com/flutter/flutter/pull/75891.
