### ISSUE TITLE
flutter_sprites should be analyzed and tested by travis

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#759]
Right now there appears to be zero test and analysis coverage of the flutter_sprites library.

**Comment by Hixie** [comment]
cc @vlidholt

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/pull/909 was an attempt to add this to travis, but it fails for unknown reasons.

**Comment by Hixie** [comment]
This is done now.
