### ISSUE TITLE
PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by djfunkd** [flutter/flutter#75901]
when I run my app in API 24 or 25 using local_auth ^0.6.3+4 the error appear but in the API 28 it's ok.

This is the error:

```
- W/ResourceType( 8918)   : Invalid package identifier when getting bag for resource number 0x0000024a
- W/art     ( 8918)    : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter,
android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable

```

FLUTTER DOCTOR:
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.17763.107], locale en-PH)
    • Flutter version 1.22.4 at C:\src\git\flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xConvic\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.53.1)
    • VS Code at C:\Users\xConvic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```

**Comment by darshankawar** [comment]
@djfunkd 
You seem to be on older version of Stable. Current version is 1.22.6. Can you upgrade to latest and try again to see if it works or no ?
If issue persists, does it occur when you add `local_auth` in `pubspec.yaml` and then run `flutter pub get` or while compiling the app ?
Can you provide `flutter run --verbose` ?
Also, can you try the official `local_auth` [repo](https://github.com/flutter/plugins/tree/master/packages/local_auth/example) on api 24 or 25 and confirm if you still get same error ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
