### ISSUE TITLE
[image_picker] App crashes when trying to pick an image using the camera

### ISSUE THREAD

**Issue by guilhermeagostinelli** [flutter/flutter#75935]
Hello,

I'm using the following code to pick an image using the camera:

```dart
PermissionStatus status = await Permission.camera.status;
if (status.isPermanentlyDenied) return openAppSettings();
status = await Permission.camera.request();
if (status.isDenied) return;
final ImagePicker picker = ImagePicker();
final PickedFile selected = await picker.getImage(source: ImageSource.camera);
setState(() => _imageFile = File(selected.path));
```

but the app crashes without any exceptions or stack traces. Sometimes it crashes right after opening the camera, sometimes right after confirming the photo that I've just taken.

Only

```
Lost connection to device.
Exited (sigterm)
```

is printed to the console. The app then immediately seems to re-launch itself and keeps stuck at the splash screen indefinitely.

I'm using the latest version of [image_picker](https://pub.dev/packages/image_picker), which is currently 0.6.7+22.

I'm running on a real device (Motorola One Hyper).

```
flutter doctor -v

[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/guilherme/Downloads/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/guilherme/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/guilherme/Android/Sdk
    • Java binary at: /home/guilherme/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/guilherme/Downloads/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.53.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • motorola one hyper (mobile)        • 0066348421    • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
```

**Related issues:**

- https://github.com/flutter/flutter/issues/66322
- https://github.com/flutter/flutter/issues/70751
- https://github.com/flutter/flutter/issues/21871 (please see comments)
- https://github.com/ShekarMudaliyar/social_share/issues/45 (the same silent crash/restart problem happens when sharing to Instagram Stories using this [social_share](https://pub.dev/packages/social_share) plugin right after leaving the app)

**Comment by darshankawar** [comment]
@guilhermeagostinelli 
Can you provide a complete minimal reproducible code sample that shows the issue ?

**Comment by guilhermeagostinelli** [comment]
@darshankawar sure, I've created a new project, here it is: https://github.com/guilhermeagostinelli/camera-test

I've also recorded both my PC and device screens while performing the test. It took two camera opens for the app to crash. You can find the recordings over [here](https://github.com/guilhermeagostinelli/camera-test/tree/master/crash_problem_recordings) in the same repo.

I wonder if it has something to do with RAM usage, because from what I tested in another app, the number of camera opens needed in order to see the crash vary based on its "complexity". If you navigate to some screens with relatively heavy memory usage before navigating to the image picker screen, then the crash happens right after opening the camera for the first time.

**Comment by darshankawar** [comment]
Thanks @guilhermeagostinelli for the repo and video. I cloned it and was able to replicate the crash. Took 2 to 3 pictures using live camera and then app shows white screen and console log shows `lost connection to device`. I tested with Samsung Android 8.1.0 device.
This points to an already open issue describing similar case, https://github.com/flutter/flutter/issues/48016. Hence I believe it'll be good to follow-up in original issue. I am going ahead and closing this as duplicacte. If you disagree, write in comments and I'll reopen.

**Comment by isrishu** [comment]
this issue is occurring on 0.8.0 and 0.8.0+1 also. I basically get a java.lang.securityexception: permission denial: starting intent with revoked permission android.permission.camera message in the console
the gallery opens without any problem but the camera crashes the app.
I checked this on a Mi A1, Samsung Galaxy, Pixel emulator. all have the same problem
App Info shows that the "camera" permission has been denied for the app. 
Does the plugin ask for the camera permission? I remember that it asked for permission in the earlier version, but now it doesnt.

**Comment by ChangJoo-Park** [comment]
reproduce here.

**Comment by isrishu** [comment]
> reproduce here.

are you asking for reproduction steps? 
there is not much to do. it works in 0.7.5
and breaks in 0.8.0
and the console log shows that camera permission has been denied or not requested. so, something broke between those 2 versions

**Comment by pundlikadav1000** [comment]
i am use in image picker then open camera but camera capturing image app is crash in flutter many mobile are work but many mobiles are not work specically redmi device .why should this error any solution suggest me .

**Comment by MohiniThakkar1995** [comment]
Hello, is there any solution for  this issue?
I'm getting the same issue while picking image from camera. I have added permission as well but still getting same issue.
it's working in Mi Pro Max but not working in Mi Pro.

**Comment by kareemX** [comment]
I'm getting the same issue and I'm not even using the camera I'm picking from the gallery and same thing happen 'lost connection to device'

**Comment by ayberkcal** [comment]
I have faced same issue phsical devices. Any update?

**Comment by toladele** [comment]
I'm facing the same issue on my physical device.

**Comment by maheshts** [comment]
i am also same situation during capture image from camera

**Comment by toladele** [comment]
Does anyone have a workaround for this?

**Comment by kadnan0900** [comment]
![WhatsApp Image 2021-08-04 at 12 10 23 PM](https://user-images.githubusercontent.com/51955352/128137721-0054c63b-46f3-4545-93b0-8f41fc7b7c9a.jpeg)

**Comment by mangei** [comment]
probably related #87896

**Comment by iloveteajay** [comment]
I faced this same issue when I used a physical device (Redmi), I found out that taking pictures with the "Google Camera" app was the issue. I tried using the phone's default camera app and it worked!
