### ISSUE TITLE
Have options autocomplete for shell tool

### ISSUE THREAD

**Issue by xster** [flutter/flutter#7593]
Would be nice to have options autocomplete for the shell flutter tool in bash, zsh, fish. 
Something like:
<img width="1051" alt="screen shot 2017-01-23 at 1 47 30 pm" src="https://cloud.githubusercontent.com/assets/156888/22224184/9a44d6ae-e172-11e6-857a-e05c88656627.png">

**Comment by eseidelGoogle** [comment]
I feel like someone looked into this at some point.  There may even have been some code for this?  Maybe @devoncarew or @jimbeveridge remember?

**Comment by devoncarew** [comment]
@danrubel discussed this (he added similar support for fletch I believe).

**Comment by xster** [comment]
Very brief research. But it seems like we can either:

1. Program it in via the the built-in `complete` and insert the various options one by one. We can potentially do it when building the flutter tool.
2. Somewhat a slight superset of 1 but let `complete` refer to a more complex shell function that's contextually smarter.
3. Contribute to some widely maintained 'framework' for completions like https://github.com/zsh-users/zsh-completions/tree/master/src and https://github.com/fish-shell/fish-shell/tree/master/share/completions. 
4. Create man pages for flutter(potentially autogen'ed from --help). zsh, fish can scrape man pages for completions.

In ascending order, the cost is probably 1<4<3<2

**Comment by danrubel** [comment]
I like auto-generating a tab complete shell script when building the flutter tool so that it stays in sync with flutter tool itself. Everything needed should already be in the flutter tool itself including text for auto generating the man pages.

When [implementing cmdline tab completion for fletch / dartio](https://github.com/dartino/sdk/commit/ee89048fc6f0e24fdd02431093bb1884f87997ea), I wanted to minimize the shell script so I tried having a shell script launch a dart app to provide tab completion, but the result felt sluggish. I think code gen when building the flutter tool is the way to go.

Working on this interests me, but I have too many other things on my plate right now.

**Comment by xster** [comment]
Seems like 'installing' man pages (4) reliably for all OSes isn't easy without root and we won't be running flutter script in root. Doesn't seem like a good vehicle unless the user installs with homebrew (and homebrew is installed on /usr/local with chmod to the user) or apt-get. 

(1) is rather incomplete. Having sub-command's options and their own sub-commands' autocomplete is pretty useful too. 

I think it's back to (2) and (3). Not an easy fix.

**Comment by kevmoo** [comment]
This might make this easier - https://github.com/kevmoo/completion.dart/

Assuming you're using 'pkg/args'

**Comment by xster** [comment]
Waaaaat. Was just thinking whether the Dart sdk could include something like https://github.com/alecthomas/kingpin#bashzsh-shell-completion. Will take a look.

**Comment by kevmoo** [comment]
@xster haven't touched this in a VERY long time. Would love another set of eyes on it.

**Comment by xster** [comment]
Duping #18988 which has more recent activity

**Comment by shilangyu** [comment]
> Duping #18988 which has more recent activity

This issue mentions fish while #18988 does not. Both issues are now closed. Does it mean fish completions will not be supported?

**Comment by xster** [comment]
@shilangyu can you open an issue specifically for fish?

**Comment by qiuxiang** [comment]
@xster u can try my solution: https://github.com/qiuxiang/flutter-fish-completions write with dart, parse and generate fish completions from `flutter help` command.

<img width=600 src="https://user-images.githubusercontent.com/1709072/103061217-9e43c180-45e5-11eb-8b7c-c49da7d3f826.png" />
<img width=600 src="https://user-images.githubusercontent.com/1709072/103061336-05617600-45e6-11eb-82b7-318aef4628b0.png" />
<img width=600 src="https://user-images.githubusercontent.com/1709072/103125814-509f8580-46c7-11eb-8c6c-6116a23c7563.png" />
<img width=600 src="https://user-images.githubusercontent.com/1709072/103187656-1ec53380-4900-11eb-8f7f-d1c4c06caaa1.png" />
<img width=600 src="https://user-images.githubusercontent.com/1709072/103187675-3997a800-4900-11eb-8666-373dbce23cae.png" />
