### ISSUE TITLE
Metal SkSurface has sample count = 1

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#75947]
Code: https://github.com/flutter/engine/blob/e0d515369fac81e34c2d48f39c6ca766096add54/shell/gpu/gpu_surface_metal.mm#L70

The documentation says that that value should be 0 to disable MSAA.

I tried switching the value to 0 but it crashes with an assert:
```
../../third_party/skia/src/gpu/GrTextureRenderTargetProxy.cpp:183: fatal error: "assert(surface->asRenderTarget()->numSamples() == this->numSamples())"
```

**Comment by jonahwilliams** [comment]
Out of date with Impeller
