### ISSUE TITLE
SnackBar shows behind modalBottomSheet

### ISSUE THREAD

**Issue by oyvindsam** [flutter/flutter#75968]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
add to scaffold fab:
```
onPressed: () {
  showModalBottomSheet(
    context: context,
    builder: (context) {
      return Container(height: 100, color: Colors.green);
    },
  );
  ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Snackbar is behind modal')));
},
```
3. Run and press fab

**Expected results:** 

SnackBar should show above modalBottomSheet, as detail in Material spec: https://material.io/components/snackbars#placement
(see "Place snackbars in front of medium extended sheets.")

**Actual results:**

SnackBar is hidden behind modal. 

I believe this is closely related to https://github.com/flutter/flutter/pull/73558, however that PR was for persistent bottom bars, not modals. That PR is working as expected. 

The issue can be seen in the screenshot below. 
![Screenshot from 2021-02-13 15-15-44](https://user-images.githubusercontent.com/25007299/107852029-75ce8b80-6e0e-11eb-9c19-9effc76f15e8.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
flutter doctor -v
[✓] Flutter (Channel master, 1.27.0-2.0.pre.96, on Linux, locale en_US.UTF-8)
• Flutter version 1.27.0-2.0.pre.96 at /home/oyvindsam/Development/flutter/sdk/flutter
    • Framework revision 8104c5786d (11 hours ago), 2021-02-12 21:41:03 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/oyvindsam/Development/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Issue replicable on latest master.

<img width="546" alt="Screenshot 2021-02-15 at 2 08 47 PM" src="https://user-images.githubusercontent.com/67046386/107923712-e05f0300-6f97-11eb-9037-ecf18bc71da1.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.101 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c2ee916a5d (5 hours ago), 2021-02-14 23:01:04 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hi @oyvindsam I am not sure I see where in the Material Design specification that SnackBars should behave this way. I searched for references to modal sheets etc but did not find any in the link you supplied.

SnackBars show above persistent bottom sheets per #73558, but a modal bottom sheet is different. It is shown on top of the UI, like a Dialog, and unlike the persistent bottom sheet, it is not controlled by the Scaffold. It's also intended to prevent the user from interacting with the rest of the app. I think that includes SnackBars.

From the docs:

> A modal bottom sheet is an alternative to a menu or a dialog and prevents the user from interacting with the rest of the app.

For reference between the two:

> * _Persistent_: A persistent bottom sheet shows information that supplements the primary content of the app. A persistent bottom sheet remains visible even when the user interacts with other parts of the app. Persistent bottom sheets can be created and displayed with the [ScaffoldState.showBottomSheet] function or by specifying the [Scaffold.bottomSheet] constructor parameter. 
> * _Modal_: A modal bottom sheet is an alternative to a menu or a dialog and prevents the user from interacting with the rest of the app. Modal bottom sheets can be created and displayed with the [showModalBottomSheet] function.

**Comment by oyvindsam** [comment]
Hi thanks for the response, indeed it seems like I misunderstood the material spec. Will close.

**Comment by ntop001** [comment]
The so called material design is stopping flutter. If you ask "How can we show some error message", they said "use SnackBar".  But when you ask "Why SnackBar cannot be shown in a ModalBottomSheet", they said "Yes, it's by design". You have to use other message system like "Toast" to solve the problem and changes lots of you code. So when you ask "How can we show some error message", I would say, just use "Toast" fuck SnackBar.
