### ISSUE TITLE
Hope TabBarView provides a parameter to control whether to scroll

### ISSUE THREAD

**Issue by LuckyJayce** [flutter/flutter#75979]
I want to prohibit the sliding of TabBarView. I have used the following method to prohibit gesture sliding, 

    TabBarView(
          physics: NeverScrollableScrollPhysics(),
          children: [
            AScreen(),
            BScreen(),
          ],
        )
but the TabBarView still has a sliding effect after clicking the TabBar switch. I hope to provide a parameter to control whether the scrolling effect is required, which is to control the call to animateToPage or jumpToPage in _TabBarViewState

**Comment by darshankawar** [comment]
@LuckyJayce 
There's similar open proposal describing your case, https://github.com/flutter/flutter/issues/16474
Please follow-up there for updates.
Closing this as duplicate.
