### ISSUE TITLE
Can't see my app on my real device

### ISSUE THREAD

**Issue by kiyotato** [flutter/flutter#75975]
After i installed my flutter apk on my device using Flutter run and i deleted the apk for some reason but now i want to re install the apk however i run flutter run on my terminal in VScode 
```bash
[`Launching lib\main.dart on MAR LX1A in debug mode...
Running Gradle task 'assembleDebug'...               
                 
Running Gradle task 'assembleDebug'... Done                         4.1s

√ Built build\app\outputs\flutter-apk\app-debug.apk.

Installing build\app\outputs\flutter-apk\app.apk...                 4.7s`
```
and it got stuck right here and i can't see my apk installed

**Comment by iapicca** [comment]
@kiyotato 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment]
Hi @kiyotato 
This could have been if you cancel the app in the middle running process
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
