### ISSUE TITLE
flutter-devicelab-linux-4 test bed in bad state

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75983]
flutter-devicelab-linux-4 is in a bad state and failing most of the tasks.

```
[backdrop_filter_perf__e2e_summary] [STDOUT] Executing: /opt/s/w/ir/cache/android/platform-tools/adb devices -l in /opt/s/w/ir/k/recipe_cleanup/tmpGHVZHD/flutter sdk/dev/benchmarks/macrobenchmarks
[backdrop_filter_perf__e2e_summary] [STDOUT] "/opt/s/w/ir/cache/android/platform-tools/adb" exit code: 0
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: List of devices attached
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: ZY22465WKN             device usb:1-4 product:athene model:Moto_G__4_ device:athene transport_id:1
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: 
[backdrop_filter_perf__e2e_summary] [STDOUT] 
[backdrop_filter_perf__e2e_summary] [STDOUT] Executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465WKN shell getprop ro.bootimage.build.fingerprint ; getprop ro.build.version.release ; getprop ro.build.version.sdk in /opt/s/w/ir/k/recipe_cleanup/tmpGHVZHD/flutter sdk/dev/benchmarks/macrobenchmarks
[backdrop_filter_perf__e2e_summary] [STDOUT] Device chosen: ZY22465WKN 
[backdrop_filter_perf__e2e_summary] [STDOUT] 
[backdrop_filter_perf__e2e_summary] [STDOUT] Executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465WKN shell dumpsys power in /opt/s/w/ir/k/recipe_cleanup/tmpGHVZHD/flutter sdk/dev/benchmarks/macrobenchmarks
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr: Can't find service: power
[backdrop_filter_perf__e2e_summary] [STDOUT] "/opt/s/w/ir/cache/android/platform-tools/adb" exit code: 0
[backdrop_filter_perf__e2e_summary] [STDERR] Task failed: Bad state: No element
```

**Comment by godofredoc** [comment]
To prevent this type of problems in the future we need a mechanism to manually put a device on maintenance to prevent it from taking more tasks: https://github.com/flutter/flutter/issues/75277

**Comment by godofredoc** [comment]
We also need a health check for this use case to quarantine the device as soon as it detects power service is not up and running.

**Comment by keyonghan** [comment]
test bed is running tests well for a while. Closing this one.
Created https://github.com/flutter/flutter/issues/76130 to track health check.

**Comment by godofredoc** [comment]
Did we do something to fix it? I had to manually block it several times during the weekend and yesterday?

**Comment by keyonghan** [comment]
I didn't make any changes from my side. Thought you fixed something to bring it back to normal.
The bot seemed to get back to normal since 2/15/2021, 10:07:11 PM
What have you tried to block it manually?

**Comment by godofredoc** [comment]
I manually leased the bot for 24h twice during the weekend. Maybe a reboot fixed the problem did you try running the command manually? it was failing to find the power service.

If it is working know we should prioritize adding the health check as this single bot was causing tens of tasks to fail in a single commit.

**Comment by keyonghan** [comment]
Tested the command worked before closing hours ago.
Will implement the healthcheck.

**Comment by godofredoc** [comment]
Sounds good, thanks for the info. Let's close this one and follow up on the bug for the health check.
