### ISSUE TITLE
ScaffoldState vs ScaffoldMessengerState - stable/master channels

### ISSUE THREAD

**Issue by craigjp99** [flutter/flutter#75999]
Hi, 
I have a question about the stable vs. master channel.  A while back now, I had switched to the "master" channel because my GoogleMap widget was throwing an exception on "stable" (but not on "master").  At the time when I switched to the "master" channel, I had to change my references from GlobalKey<ScaffoldState> to GlobalKey<ScaffoldMessengerState>, which I was using for SnackBars.
I thought that maybe it was time to switch back to the "stable" channel, to see if the GoogleMap widget would be OK, but then GlobalKey<ScaffoldMessengerState> isn't valid under the "stable" channel ..... it was probably like a fair few months ago that I had changed to "master".
So my general question is about when something like that "ScaffoldState" vs "ScaffoldMessengerState" change would be implemented into the "stable" channel?  Maybe the simple answer is a link to a development roadmap (that I can't easily find myself).   Or, more broadly, how would I know when something in the "master" channel (that resolves an issue I'm having) has been migrated to "stable"?

**Comment by iapicca** [comment]
@craigjp99 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by craigjp99** [comment]
Hi @iapicca,
Firstly, I've noticed that my initial post dropped some content, because I'd put greater than/less than symbols.
I was trying to say that when I switched from "stable" to "master", I had to change GlobalKey &lt;ScaffoldState&gt; to GlobalKey &lt;ScaffolderMessengerState&gt;
Then, some months later when I switch back to "stable", it doesn't like GlobalKey &lt;ScaffolderMessengerState&gt;
Therefore, I'm not sure that what I need is help writing my application - I know the right class/type to use for SnackBar control (whether I'm in "stable" or "master").  My question was more just around understanding how I know when a certain change, or new functionality, goes from "master" to "stable"?

**Comment by pedromassangocode** [comment]
Hi @craigjp99 the `ScaffoldMessengerState ` is not available on stable for now that is why you got the error while switching from master to stable channel.

For more info, see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.
