### ISSUE TITLE
Can't get the right direction

### ISSUE THREAD

**Issue by AmosYang6814** [flutter/flutter#75992]
When I use the orientation lock option on my phone to lock the screen orientation, he cannot get the video or photo orientation correctly

**Comment by iapicca** [comment]
@AmosYang6814 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@AmosYang6814 
Please provide above requested details to properly address your issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
