### ISSUE TITLE
[flutter_image] is now deprecated and [hf_retry] come up on top of if

### ISSUE THREAD

**Issue by Abhishek01039** [flutter/flutter#75993]
As said https://github.com/flutter/flutter_image/pull/18#issuecomment-775721675 here.
This package is now deprecated so I have created a new package on top of it (https://github.com/hireflutter-dev/hf-retry).
I have some ideas regarding this package. 
1. migrate this package to null safety.
2. same like image retry mechanism I have a plan to do for all kinda network calls.
3. and much more...

**Comment by Abhishek01039** [comment]
cc @Hixie

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please take a look?

**Comment by Abhishek01039** [comment]
Thanks for your response
This is package on pub https://pub.dev/packages/hf_retry

**Comment by Hixie** [comment]
@Abhishek01039 Can you work with @csells to get the package into the ["Flutter Favorite" program](https://flutter.dev/docs/development/packages-and-plugins/favorites)? That way when we deprecate the version we have, it's not going to raise any eyebrows. (For example, right now hf_retry is v0.0.1, which won't fill people with confidence compared to v3.0.0 for flutter_image.)

**Comment by Abhishek01039** [comment]
Sure @Hixie

**Comment by Hixie** [comment]
I expect that will be one of the things needed but I would talk to @csells about it to find the full list.

**Comment by stuartmorgan** [comment]
@Hixie Is the plan to deprecate this package? This was on my list of packages to move into flutter/packages.

**Comment by Hixie** [comment]
If @Abhishek01039 is able to get their package into the Flutter Favorites program then I'm totally fine with us removing our version, yeah. If that's not likely to happen in the near future then migrating the current one in the meantime is still valuable.

**Comment by Abhishek01039** [comment]
@Hixie, @csells is not seems like very active here!
Once he will back then I will migrate this to null safety and change the version as well!

**Comment by Hixie** [comment]
You probably need to reach out to him by e-mail. There should be some documentation on how to get into the Flutter Favorites program on our web site.

**Comment by stuartmorgan** [comment]
There's a PR that's very close to landing that migrates flutter_image to null safety, so it would be much better to merge that into your version (once it's landed) than to re-migrate it yourself.

**Comment by stuartmorgan** [comment]
https://flutter.dev/docs/development/packages-and-plugins/favorites has an overview of the criteria and the process to apply (which is currently to email csells)

**Comment by Abhishek01039** [comment]
Thanks @stuartmorgan and @Hixie 
I have mailed him and got this 
```Thanks, Abhishek. I've added this to the list of Flutter Favorite candidates for future consideration by the committee. However, this is a small enough package with a narrow enough use case that it's unlikely to be awarded a Flutter Fix designation. The committee tends to pick more generally applicable packages.```

**Comment by Abhishek01039** [comment]
Hello @Hixie 
should I mail to @csells second time to add this package to flutter favourite?

**Comment by csells** [comment]
@Abhishek01039 a package must be generally useful to a wide range of Flutter apps and pass the criteria listed in the [Flutter Favorite program](https://flutter.dev/docs/development/packages-and-plugins/favorites) description. Decisions about Flutter Favorite packages are made by the Flutter Ecosystem Committee in rounds. We just finished round #4 and the results will be announced soon. The hf_retry package was nominated after round #4 was closed, but it will be considered for round #5, which will happen in Q3.

**Comment by stuartmorgan** [comment]
Since we don't have a short-term path to a Flutter Favorite designation, I've gone ahead with migrating the repository to flutter/packages. As a result, it can be maintained using our normal processes, so we aren't currently deprecating it. Given that, closing this issue.

@Abhishek01039 we always welcome contributions to our packages, and if you're interested in getting even more involved with this one, you could also do initial reviews of PRs that come in there related to flutter_image, fix `flutter_image`-tagged issues, etc.
