### ISSUE TITLE
[google_maps_flutter] multi polygons no fill

### ISSUE THREAD

**Issue by icangku** [flutter/flutter#76001]
I've implemented multi polygons with multiple colors, some polygons show with the color, some not, I've heard this about intersecting issue, is this true, and how to solve this?

**Comment by TahaTesser** [comment]
Hi @icangku 
Can you please link the issue about intersecting polygons?
Also please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by icangku** [comment]
```
Future<void> _initPolygon(PolaRuang request) async {
    var polygonIdVal = request.ogcFid.toString();
    final PolygonId polygonId = PolygonId(polygonIdVal);
    List<LatLng> latlngs = new List();
    for(int i = 0; i < request.polyJson.coordinates[0][0].length; i++){
     latlngs.add(LatLng(request.polyJson.coordinates[0][0][i][1],request.polyJson.coordinates[0][0][i][0]));
    }

    Polygon polygon = Polygon(
      polygonId: polygonId,
      points: latlngs,
      strokeColor: Colors.transparent,
      strokeWidth: 0,
      fillColor: colorFromHex(request.color),
      consumeTapEvents: true,
      onTap: (){
        modalInfoPolaRuang(this.context, request);
      }
    );
    setState(() {
      _polygons[polygonId] = polygon;
    });
  }```

**Comment by TahaTesser** [comment]
Hi @icangku 
To better address the issue, please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **instead of production code**?
Thank you

**Comment by icangku** [comment]
```
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alvin/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

i've installed android studio, its just not detecting it, btw its all the code that I use try to solve

**Comment by TahaTesser** [comment]
Hi @icangku 
`flutter doctor -v` you provided doesn't include Flutter versions and the [code snippet](https://github.com/flutter/flutter/issues/76001#issuecomment-779232366) you provided is incomplete and not runnable
To better address the issue please provide all required details, please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **instead of production code**?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
