### ISSUE TITLE
Any one pls help me to solve this error......

### ISSUE THREAD

**Issue by Gowthamkarthi-R** [flutter/flutter#76006]
C:\Users\Gowtham Karthi>flutter doctor -v
```
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.27.0-1.0.pre at D:\Downloads\flutter apps\flutter_windows_1.22.6-stable\flutter
    • Framework revision 68c96f100e (6 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

**[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Gowtham Karthi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.**

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.1)
    • VS Code at C:\Users\Gowtham Karthi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

**Comment by Gowthamkarthi-R** [comment]
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at C:\Users\Gowtham Karthi\AppData\Local\Android\sdk
• Platform android-30, build-tools 30.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
X Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

**Comment by iapicca** [comment]
@Gowthamkarthi-R 
please run `flutter doctor --android-licenses` as stated in the logs you posted

> **[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at C:\Users\Gowtham Karthi\AppData\Local\Android\sdk • Platform android-30, build-tools 30.0.3 • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01) X Android license status unknown. Run `flutter doctor --android-licenses` to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.**

**Comment by darshankawar** [comment]
@Gowthamkarthi-R 
Can you try [this](https://github.com/flutter/flutter/issues/51670#issuecomment-592943797) solution and see if it works ?

**Comment by Gowthamkarthi-R** [comment]
C:\Users\Gowtham Karthi>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
**[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.**
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

C:\Users\Gowtham Karthi>**flutter doctor --android-licenses**
**Error: Could not find or load main class Karthi\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..**

C:\Users\Gowtham Karthi>

**i tried bro....its not working help me...**

**Comment by iapicca** [comment]
@Gowthamkarthi-R 
I believe this isn't a bug with flutter, but a problem with your setup
this type of issue should be addressed on stackoverflow or with the [community](https://flutter.dev/community)

given your new logs

> C:\Users\Gowtham Karthi>**flutter doctor --android-licenses**
> **Error: Could not find or load main class Karthi\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\..**

you may want to follow this [discussion](https://stackoverflow.com/questions/60727326/sdkmanager-error-could-not-find-or-load-main-class-com-android-sdklib-tool-sdk)

**Comment by darshankawar** [comment]
@Gowthamkarthi-R 
As suggested above, please follow the link to get help on your issue.
Closing from here. If you disagree, write in comments and I'll reopen it.
