### ISSUE TITLE
CHANGELOG template for packages is misaligned

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#76018]
## Misalignment

When looking at the `CHANGELOG.md.tmpl` in `templates/plugin`, we can see the following template:

https://github.com/flutter/flutter/blob/696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17/packages/flutter_tools/templates/plugin/CHANGELOG.md.tmpl#L1

Now, if we take a look at the same file in `templates/package`, we can see this:

https://github.com/flutter/flutter/blob/696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17/packages/flutter_tools/templates/package/CHANGELOG.md.tmpl#L1

### Date & square brackets

The date and square brackets seem entirely out-of-place because (apart from my opinion that they add no value when using Git and Pub having a versioning system built-in) it is not even used in _official packages_, e.g. https://github.com/flutter/packages/blob/master/packages/pigeon/CHANGELOG.md.

## Aligning it

I think there is intrinsic value to aligning the templates of `plugin` and `package`. Because the simple version without dates and square brackets seems to be the one more widely spread, I propose that we align the `package` template.

**Comment by nt4f04uNd** [comment]
> The date and square brackets seem entirely out-of-place because (apart from my opinion that they add no value when using Git and Pub having a versioning system built-in) it is not even used in official packages, e.g. https://github.com/flutter/packages/blob/master/packages/pigeon/CHANGELOG.md.

i don't actually know, they sometimes use one, sometimes another, that differs from package to package. @stuartmorgan can you clarify why are they different and which to prefer?

**Comment by stuartmorgan** [comment]
The difference dates to https://github.com/flutter/flutter/pull/17840 which is before I was on the team, so I have no context for the change (and there's no real explanation there unfortunately). @mit-mit Do you know the history of this alternate changelog style?

**Comment by creativecreatorormaybenot** [comment]
I think following #17840, it does only make sense to also push #76019 unless there has been a new change in style guidelines.

**Comment by mit-mit** [comment]
> The difference dates to #17840 which is before I was on the team, so I have no context for the change (and there's no real explanation there unfortunately). @mit-mit Do you know the history of this alternate changelog style?

If I'm reading https://github.com/flutter/flutter/pull/17840/files correctly, that PR applied the expected changelog style (without brackets).

**Comment by mit-mit** [comment]
Relevant docs for this (which do not use the bracket style):
https://dart.dev/tools/pub/package-layout#changelogmd
