### ISSUE TITLE
allow AnimationController animateTo to change animation direction and remove animateBack

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#76012]
this is same as for animateWith https://github.com/flutter/flutter/issues/60419

shortly
https://github.com/flutter/flutter/blob/c9cb43ce1aaaaf94e9998d1ba5b0a7c911f96733/packages/flutter/lib/src/animation/animation.dart#L13-L26

but these methods hardcode the direction values for forward and reverse accordingly

animateBack must be deprected and animateTo must automatically set the animation direction

/cc @Hixie

**Comment by pedromassangocode** [comment]
Hi @nt4f04uNd 
Can you please elaborate the issue better? The title of the issue does not seems to match the issue description. Is this a proposal or a problem? What are the those framework animation rules?

Please update the issue for clarity and mention only one problem as we don't track more than one problem in the same issue.
Thank you

**Comment by nt4f04uNd** [comment]
<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Foo(),
      ),
    );
  }
}

class Foo extends StatefulWidget {
  Foo({ Key key }) : super(key: key);

  @override
  _FooState createState() => _FooState();
}

class _FooState extends State<Foo> with SingleTickerProviderStateMixin {
  AnimationController controller;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(
      vsync: this, // the SingleTickerProviderStateMixin
      duration: const Duration(milliseconds: 2000),
    );
    controller.addStatusListener((status) {
      print(status);
    });
    controller.value = 1.0;
    controller.animateTo(0.5);
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox();
  }
}
```
</details>

<details>
<summary>logs</summary>

```
AnimationStatus.completed
AnimationStatus.forward
AnimationStatus.completed
```
</details>

that reproducible helped me to understand that actually AnimationStatus.forward is not supposed to mean that animation value grows (which i was thinking of previous, and that's why opened this issue), it's something more ephemeral

i change my proposal a little bit:
we could add direction parameter to animateTo (the same as per animateWith in #60419) and remove animateBack

**Comment by Hixie** [comment]
forward just means it goes from the lower bound to the upper bound. If you have an upper bound that's lower than the lower bound, well...

I'm not really sure what this bug is asking for.

**Comment by nt4f04uNd** [comment]
initially i misunderstood what AnimationStatus.forward is supposed to do and made wrong proposal
now i just suggest that animateBack could be removed in favor of new direction parameter in animateTo (if i'm not missing some more differences between them), that's not a feature request

you can think of it just like if it was a part of https://github.com/flutter/flutter/issues/24722

**Comment by Hixie** [comment]
#24722 is changes we'll probably never make. If you would like it added to that list, I recommend posting a comment on that bug (don't forget to explain _why_ you think that would have been a good thing to have done). But don't count on anything in that list ever happening, they're specifically things that are likely not worth ever doing.

**Comment by nt4f04uNd** [comment]
ok
