### ISSUE TITLE
ability to change default fling springDescription of AnimationController

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#76016]
i'm proposing to allow changing the default springDescription for the AnimationController. changing it for a single `fling` call is already possbile via parameter on the same name. to not change it every time we use the fling, we could just allow changing the default one for a whole controller

**Comment by goderbauer** [comment]
As mentioned on the PR: Not sure why this would be useful. The spring description can already be modified directly when calling the fling method. Adding another property that's only relevant for one methods would make the API more confusing, though.

**Comment by nt4f04uNd** [comment]
this would make it more convenient if you often use fling per some controller instance. i don't agree this would make api any more complicated, i could remove this from constructors though
a controller design mistake that we have only one controller both for simulations and ordinary transitions - this what can make people be more confused than this i believe
