### ISSUE TITLE
Mac/Ios tasks are timing out when rebooting the devices

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76027]
Log:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20integration_ui_ios_screenshot/384

```
[integration_ui_ios_screenshot] [STDOUT] "/opt/s/w/ir/k/recipe_cleanup/tmpOrlw9Z/flutter sdk/bin/flutter" exit code: 0
[integration_ui_ios_screenshot] [STDOUT] 
[integration_ui_ios_screenshot] [STDOUT] 
[integration_ui_ios_screenshot] [STDOUT] ═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════
[integration_ui_ios_screenshot] [STDOUT] 
[integration_ui_ios_screenshot] [STDOUT] Checking for reboot
[integration_ui_ios_screenshot] [STDOUT] rebooting
```

This is happenning because the command used to reboot the ios phones is actually collecting the syslog continuously.

**Comment by christopherfujino** [comment]
Requesting cherrypicking https://github.com/flutter/flutter/commit/4597b51cbc2121ad8bcfd38cb925a497867e80cc to fix devicelab. This is a test-only fix, and thus low-risk.
