### ISSUE TITLE
image_picker: ^0.6.7+22 storing recorded video in Picture directory.

### ISSUE THREAD

**Issue by shofizone** [flutter/flutter#76031]
I am picking video from camera in this way. 

`  final _picker = ImagePicker();

  Future<String> recordAndGetVideo()async{
    PickedFile file = await _picker.getVideo(source: ImageSource.camera);
    if(file != null){
      return file.path;
    }
    return null;
  }`

After recoding the final path is this path. 
/storage/emulated/0/Android/data/com.example.app/files/Pictures/a190e227-a42c-4b09-bad8-4a9591454ff64584234230431626592.mp4

**Comment by pedromassangocode** [comment]
Hi @shofizone 
I'm not sure if I understood what the issue is. Can you please elaborate?
Is `image_picker` causing unwanted behavior? Can you please provide the actual vs expected behavior and the steps to reproduce the issue?
Thank you

**Comment by shofizone** [comment]
Sorry for my bad explanation. I was trying to pick a video using camera. So everything happened as I expected.  But the problem is the folder, where it saving video it's named "Pictures". While I recorded a video so it should be in Videos folder.
so Expected ->  /storage/emulated/0/Android/data/com.example.app/files/**Videos**/ex-video.mp4
but Actual - > /storage/emulated/0/Android/data/com.example.app/files/**Pictures**/ex-video.mp4
It's not a major issue. If you think it can be ignored then I will closed the  issue. 
Thank you !

**Comment by pedromassangocode** [comment]
I don't think it is a major issue as it is just a temporary location.
