### ISSUE TITLE
iOS Simulator file path error

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7603]
iPhone6s Simulator error message

Every other time I run simulator (debug mode), I get the following error and it doesn't start the app:
assertion failed: 15G1004 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d

the next time it'll work (alternating), this is a full refresh 'R'

**Comment by eseidelGoogle** [comment]
Originally when you filed the bug you had a longer error message which included
`Error connecting to the service protocol: Bad state: No element`, which I suspect is the only message from flutter.

You might also try looking at the full logs either via `flutter run -v` or by using command-\ in the simulator to open up the console log for that simulator instance.  `flutter run` does some log filtering for you by default and might be hiding an error.

**Comment by eseidelGoogle** [comment]
The libxpc.dylib assertion is benign and has nothing to do with Flutter: http://stackoverflow.com/questions/36874368/assertion-failed-warnings

**Comment by xster** [comment]
Will treat as cleanup as part of #7652
