### ISSUE TITLE
How to fix an error which is Emulator: glTexImage2D: got err pre :( 0x501 internal 0x1908 format 0x1908 type 0x140? I'm trying OCR in Flutter

### ISSUE THREAD

**Issue by RenaSki** [flutter/flutter#76030]
## Steps to Reproduce

1. Run `flutter create bug`.
All done!
[√] Flutter: is fully installed. (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[!] Android toolchain - develop for Android devices: is partially installed; more components are available. (Android SDK
    version 30.0.2)
[√] Android Studio: is fully installed. (version 4.0)
[!] VS Code: is partially installed; more components are available. (version 1.50.1)
[√] Connected device: is fully installed. (1 available)

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug\lib\main.dart.

2. Update the files as follows: ... 

3. ... 
I'm trying OCR in Flutter. But I always get an error which is "Emulator: glTexImage2D: got err pre :( 0x501 internal 0x1908 format 0x1908 type 0x140."
It opens the camera when I run a code, but It doesn't scan characters.
<img width="156" alt="4Capture" src="https://user-images.githubusercontent.com/70543067/107896542-30888780-6efc-11eb-8787-2584250a771b.PNG">

**Expected results:** 
    Scan characters and output characters.
**Actual results:** 
    It opens the camera when I run a code, but It doesn't scan characters.

<details>
  <summary>Logs</summary>

[ +119 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +1 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git tag --points-at HEAD
[  +69 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.6
[  +10 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +4 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +100 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +66 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +22 ms] executing: C:\Users\sakai017\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +58 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[   +9 ms] C:\Users\sakai017\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +58 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +32 ms] "flutter run" took 226ms.
[  +20 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
           Do not run this command from the root of your git clone of Flutter.
[   +5 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1074:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:348:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[ +238 ms] ensureAnalyticsSent: 233ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

 info - The value of the field '_widgetOptions' isn't used - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:13:15 - unused_field
   info - The value of the field '_counter' isn't used - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:31:7 - unused_field
warning - The parameter 'onPressed' is required - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:50:11 - missing_required_param
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:97:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:100:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\calendarDraft.dart:103:15 - deprecated_member_use
   info - Unused import: 'package:table_calendar/table_calendar.dart' - AndroidStudioProjects\meal_flutter_app\lib\mealPlan.dart:2:8 - unused_import
   info - Unused import: 'package:meal_flutter_app/shopping.dart' - AndroidStudioProjects\meal_flutter_app\lib\mealPlan.dart:3:8 - unused_import
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\mealPlan.dart:5:7 - camel_case_types
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\nav.dart:44:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\nav.dart:47:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\nav.dart:50:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\nav.dart:53:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\navBackup.dart:38:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\navBackup.dart:41:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was deprecated after v1.19.0.
          - AndroidStudioProjects\meal_flutter_app\lib\navBackup.dart:44:15 - deprecated_member_use
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:2:8 - unused_import
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:16:7 - camel_case_types
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipeBackup.dart:21:7 - camel_case_types
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:2:8 - unused_import
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:17:7 - camel_case_types
   info - Name types using UpperCamelCase - AndroidStudioProjects\meal_flutter_app\lib\recipes.dart:22:7 - camel_case_types
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\shopping.dart:2:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Shopping.listTiles -
          AndroidStudioProjects\meal_flutter_app\lib\shopping.dart:4:7 - must_be_immutable
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\shoppingBackup.dart:2:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Shopping.listTiles -
          AndroidStudioProjects\meal_flutter_app\lib\shoppingBackup.dart:4:7 - must_be_immutable
   info - Unused import: 'package:flutter/rendering.dart' - AndroidStudioProjects\meal_flutter_app\lib\store.dart:2:8 - unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\stors.dart:3:8 - unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\storsBackup.dart:2:8 - unused_import
   info - Unused import: 'package:meal_flutter_app/nav.dart' - AndroidStudioProjects\meal_flutter_app\lib\storsDraft.dart:2:8 - unused_import
   info - Unused import: 'dart:async' - AndroidStudioProjects\meal_flutter_app\lib\storsDraft.dart:3:8 - unused_import

31 issues found. (ran in 56.7s)

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter_windows_1.20.3-stable\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\sakai017\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.50.1)
    • VS Code at C:\Users\sakai017\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

</details>

**Comment by pedromassangocode** [comment]
Hi @RenaSki 
Can you please provide your `flutter run --verbose` (make sure you run this inside of your project directory) and a minimal complete reproducible code sample that does not uses any third-party plugin/package?
Thank you

**Comment by RenaSki** [comment]
> Hi @RenaSki
> Can you please provide your `flutter run --verbose` (make sure you run this inside of your project directory) and a minimal complete reproducible code sample that does not uses any third-party plugin/package?
> Thank you

Hello pedromassangocode,

Can you please provide your flutter run --verbose (make sure you run this inside of your project directory) :
The result of 'flutter run --verbose' below⬇
 
[ +183 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +138 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +1 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git tag --points-at HEAD
[ +135 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.6
[  +19 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git ls-remote --get-url origin
[  +90 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +137 ms] executing: [C:\src\flutter_windows_1.20.3-stable\flutter/] git rev-parse --abbrev-ref HEAD
[  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +120 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] executing: C:\Users\sakai017\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +109 ms] List of devices attached
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +26 ms] "flutter run" took 332ms.
[  +24 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
           Do not run this command from the root of your git clone of Flutter.
[   +8 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1074:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:348:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +258 ms] ensureAnalyticsSent: 242ms
[   +7 ms] Running shutdown hooks
[   +4 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

A minimal complete reproducible code sample that does not uses any third-party plugin/package?
I am using "package:flutter_mobile_vision/flutter_mobile_vision.dart"

Thank you,
Rena

**Comment by pedromassangocode** [comment]
> [ +26 ms] "flutter run" took 332ms.
> [ +24 ms] Error: No pubspec.yaml file found.
> This command should be run from the root of your Flutter project.
> Do not run this command from the root of your git clone of Flutter.

I have to run this in the root directory of your project!

**Comment by RenaSki** [comment]
Hello Pedro Massango,

What do I need to do?

**Comment by RenaSki** [comment]
> > [ +26 ms] "flutter run" took 332ms.
> > [ +24 ms] Error: No pubspec.yaml file found.
> > This command should be run from the root of your Flutter project.
> > Do not run this command from the root of your git clone of Flutter.
> 
> I have to run this in the root directory of your project!

Hello Pedro Massango,

What do I need to do?

**Comment by pedromassangocode** [comment]
Hi @RenaSki 
Please run `flutter run` in a valid Flutter project directory.

>This command should be run from the root of your Flutter project.
>Do not run this command from the root of your git clone of Flutter.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
