### ISSUE TITLE
Latest build won't run in release mode, only debug

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#7604]
## Steps to Reproduce

Upgraded to latest engine, my "hello_services" (not the original, but based off of it) still works in --debug, but no longer --release. It actually installs apk-debug in release mode, and then fails to run on device.

My non-services project seems fine with the latest flutter build.

## Logs

Launching lib/main.dart on XT1060 in release mode...
Running 'gradlew build'...                               
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:libraries:sp:preBuild UP-TO-DATE
:libraries:sp:preReleaseBuild UP-TO-DATE
:libraries:sp:checkReleaseManifest
:libraries:sp:preDebugAndroidTestBuild UP-TO-DATE
:libraries:sp:preDebugBuild UP-TO-DATE
:libraries:sp:preDebugUnitTestBuild UP-TO-DATE
:libraries:sp:preReleaseUnitTestBuild UP-TO-DATE
:libraries:sp:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:libraries:sp:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:libraries:sp:prepareReleaseDependencies
:libraries:sp:compileReleaseAidl UP-TO-DATE
:libraries:sp:compileLint UP-TO-DATE
:libraries:sp:copyReleaseLint UP-TO-DATE
:libraries:sp:compileReleaseRenderscript UP-TO-DATE
:libraries:sp:generateReleaseBuildConfig UP-TO-DATE
:libraries:sp:generateReleaseResValues UP-TO-DATE
:libraries:sp:generateReleaseResources UP-TO-DATE
:libraries:sp:mergeReleaseResources UP-TO-DATE
:libraries:sp:processReleaseManifest UP-TO-DATE
:libraries:sp:processReleaseResources UP-TO-DATE
:libraries:sp:generateReleaseSources UP-TO-DATE
:libraries:sp:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:compileReleaseJavaWithJavac UP-TO-DATE
:libraries:sp:extractReleaseAnnotations UP-TO-DATE
:libraries:sp:mergeReleaseShaders UP-TO-DATE
:libraries:sp:compileReleaseShaders UP-TO-DATE
:libraries:sp:generateReleaseAssets UP-TO-DATE
:libraries:sp:mergeReleaseAssets UP-TO-DATE
:libraries:sp:mergeReleaseProguardFiles UP-TO-DATE
:libraries:sp:packageReleaseRenderscript UP-TO-DATE
:libraries:sp:packageReleaseResources UP-TO-DATE
:libraries:sp:processReleaseJavaRes UP-TO-DATE
:libraries:sp:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:libraries:sp:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:libraries:sp:generateJsonModelRelease UP-TO-DATE
:libraries:sp:externalNativeBuildRelease
  building /Users/joel/dev/bendometer/bendometer_flutter/android/libraries/sp/build/intermediates/cmake/release/obj/armeabi-v7a/libSuperpoweredExample.so
:libraries:sp:mergeReleaseJniLibFolders UP-TO-DATE
:libraries:sp:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:libraries:sp:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:libraries:sp:bundleRelease UP-TO-DATE
:app:prepareAndroidLibrariesSpUnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:flutterBuild
Building AOT snapshot in release mode (android-arm-release)... 7737ms
Built to /Users/joel/dev/bendometer/bendometer_flutter/android/app/build/intermediates/flutter/.
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:copyFlutterAssetsDebug
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
Full recompilation is required because at least one of the classes of removed jar 'flutter.jar' requires it. Analysis took 0.017 secs.
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug
:app:transformNative_libsWithStripDebugSymbolForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:mergeReleaseShaders UP-TO-DATE
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:copyFlutterAssetsRelease
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources UP-TO-DATE
:app:generateReleaseSources UP-TO-DATE
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:compileReleaseJavaWithJavac
Full recompilation is required because at least one of the classes of removed jar 'flutter.jar' requires it. Analysis took 0.009 secs.
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources
:app:lintVitalRelease
:app:transformClassesWithDexForRelease
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForRelease
:app:transformNative_libsWithStripDebugSymbolForRelease
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease
:app:validateSigningRelease
:app:packageRelease
:app:assembleRelease
:app:assemble
:app:lint
Ran lint on variant debug: 5 issues found
Ran lint on variant release: 5 issues found
Wrote HTML report to file:///Users/joel/dev/bendometer/bendometer_flutter/android/app/build/outputs/lint-results-debug.html
Wrote XML report to file:///Users/joel/dev/bendometer/bendometer_flutter/android/app/build/outputs/lint-results-debug.xml
:app:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:app:processDebugUnitTestJavaRes UP-TO-DATE
:app:compileDebugUnitTestSources UP-TO-DATE
:app:mockableAndroidJar
:app:assembleDebugUnitTest
:app:testDebugUnitTest UP-TO-DATE
:app:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:preReleaseUnitTestBuild UP-TO-DATE
:app:prepareReleaseUnitTestDependencies
:app:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:app:processReleaseUnitTestJavaRes UP-TO-DATE
:app:compileReleaseUnitTestSources UP-TO-DATE
:app:assembleReleaseUnitTest
:app:testReleaseUnitTest UP-TO-DATE
:app:test UP-TO-DATE
:app:check
:app:build
:libraries:sp:checkDebugManifest
:libraries:sp:prepareDebugDependencies
:libraries:sp:compileDebugAidl UP-TO-DATE
:libraries:sp:copyDebugLint UP-TO-DATE
:libraries:sp:compileDebugRenderscript UP-TO-DATE
:libraries:sp:generateDebugBuildConfig UP-TO-DATE
:libraries:sp:generateDebugResValues UP-TO-DATE
:libraries:sp:generateDebugResources UP-TO-DATE
:libraries:sp:mergeDebugResources UP-TO-DATE
:libraries:sp:processDebugManifest UP-TO-DATE
:libraries:sp:processDebugResources UP-TO-DATE
:libraries:sp:generateDebugSources UP-TO-DATE
:libraries:sp:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:compileDebugJavaWithJavac UP-TO-DATE
:libraries:sp:extractDebugAnnotations UP-TO-DATE
:libraries:sp:mergeDebugShaders UP-TO-DATE
:libraries:sp:compileDebugShaders UP-TO-DATE
:libraries:sp:generateDebugAssets UP-TO-DATE
:libraries:sp:mergeDebugAssets UP-TO-DATE
:libraries:sp:mergeDebugProguardFiles UP-TO-DATE
:libraries:sp:packageDebugRenderscript UP-TO-DATE
:libraries:sp:packageDebugResources UP-TO-DATE
:libraries:sp:processDebugJavaRes UP-TO-DATE
:libraries:sp:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:libraries:sp:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:libraries:sp:generateJsonModelDebug UP-TO-DATE
:libraries:sp:externalNativeBuildDebug
  building /Users/joel/dev/bendometer/bendometer_flutter/android/libraries/sp/build/intermediates/cmake/debug/obj/armeabi-v7a/libSuperpoweredExample.so
:libraries:sp:mergeDebugJniLibFolders UP-TO-DATE
:libraries:sp:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:libraries:sp:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:libraries:sp:bundleDebug UP-TO-DATE
:libraries:sp:compileDebugSources
:libraries:sp:assembleDebug
:libraries:sp:compileReleaseSources
:libraries:sp:assembleRelease
:libraries:sp:assemble
:libraries:sp:lint
Ran lint on variant release: 2 issues found
Ran lint on variant debug: 2 issues found
Wrote HTML report to file:///Users/joel/dev/bendometer/bendometer_flutter/android/libraries/sp/build/outputs/lint-results-debug.html
Wrote XML report to file:///Users/joel/dev/bendometer/bendometer_flutter/android/libraries/sp/build/outputs/lint-results-debug.xml
:libraries:sp:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:prepareDebugUnitTestDependencies
:libraries:sp:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:libraries:sp:processDebugUnitTestJavaRes UP-TO-DATE
:libraries:sp:compileDebugUnitTestSources UP-TO-DATE
:libraries:sp:mockableAndroidJar UP-TO-DATE
:libraries:sp:assembleDebugUnitTest UP-TO-DATE
:libraries:sp:testDebugUnitTest UP-TO-DATE
:libraries:sp:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:libraries:sp:prepareReleaseUnitTestDependencies
:libraries:sp:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:libraries:sp:processReleaseUnitTestJavaRes UP-TO-DATE
:libraries:sp:compileReleaseUnitTestSources UP-TO-DATE
:libraries:sp:assembleReleaseUnitTest UP-TO-DATE
:libraries:sp:testReleaseUnitTest UP-TO-DATE
:libraries:sp:test UP-TO-DATE
:libraries:sp:check
:libraries:sp:build

BUILD SUCCESSFUL

Total time: 29.87 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Built android/app/build/outputs/apk/app-debug.apk (11.3MB).

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision 4bec9cd940 (3 hours ago), 
    • Engine revision adef37080f
    • Tools Dart version 1.22.0-dev.8.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 7.3, Build version 7D175

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.7743.25
    • Flutter plugin version 0.1.5

[✓] Connected devices
    • XT1060 • T062005DI0 • android-arm • Android 5.1 (API 22)

**Comment by abarth** [comment]
Possibly caused by this change to FlutterPlugin.groovy:

https://github.com/flutter/flutter/commit/76460967e662a287818a3b1e3e39af5dfbf10802#diff-92da56abb16a9541802d63a6720733da

Do you have the old version of FlutterPlugin.groovy in your project?

(See https://github.com/flutter/flutter/issues/7504)

**Comment by jtrunick** [comment]
I noticed that the latest hello_services when run in --release mode also installs:
app-debug.apk

but it is running in release, no red "slow mode" sash is present. So it appears that possibly my project is building for --release, but some bug is allowing the debug version to work, but not the --release version.

**Comment by jtrunick** [comment]
I did swap out the FlutterPlugin.groovy with the latest same result it looks like the other difference I notice is the latest is using gradle 2.2.3

**Comment by jtrunick** [comment]
After I swapped the groovy file... AND cleaned the anddroid/build/ directory it started working again... Thanks!

**Comment by jtrunick** [comment]
Shouldn't I expect it to install the -release version of the .apk though?

**Comment by jakobr-google** [comment]
With the current gradle scripts, it should install app-debug.apk. The '-debug' part only refers to the Android portion of the build, not the Flutter part.

The --profile/--release build mode currently only affects which native Flutter binaries are put in the .apk, and how we build the snapshot of the Dart code. As you've noticed, you get the 'slow mode' sash only on a debug build, and not on profile/release builds, even though app-debug.apk is installed.

I'm fixing this in PR #7606.

**Comment by jtrunick** [comment]
Maybe you'd have an idea why on the iOS build, my images get mucked up... Maybe corrupted is the right word. Only on iOS, the image will display but its something else (in my case it its mostly black, and looks like a blurred red line in it --- both of my images show the same way, even though the original images are very different). I can load the image and obtain the bytes, and the byte count is correct.

The two images are listed in my assets. I'll see if I can take the latest build and see if it happens right out of the gate. I'm pretty sure its something I'm changing in iOS project, but I can't imagine what. Also... Should I ever touch the workspace? Or, just the project part of iOS?

**Comment by jakobr-google** [comment]
Gradle-based Android builds now produce app-{debug,profile,release}.apk if you update to the latest version of the build scripts from the hello_services example. Sounds like the original issue here has been fixed.

The iOS image issue is tracked in #7728. If you need to touch the native iOS bits, you should always open ios/Runner.xcworkspace, and not the project file. This is a Cocoapods thing.
