### ISSUE TITLE
Maths calculation with flutter

### ISSUE THREAD

**Issue by ivsaneesh** [flutter/flutter#76044]
void main() {
  print('result ${43.12 - 93.12 + 50}');
}

result -7.105427357601002e-15

**this is wrong
the result must me 0**

![dart 1 ](https://user-images.githubusercontent.com/34297370/107914141-d6cd9f00-6f87-11eb-9d53-d50a5c74e6c9.png)

**Comment by TahaTesser** [comment]
Hi @ivsaneesh 
This is related to Dart, not Flutter itself
Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by stuartmorgan** [comment]
Also, this is not a big. You are using numbers that cannot be exactly represented as doubles. The answer you are getting is equivalent to zero to within the accuracy of a `double`.

I suggest reading about floating point numbers, as this is not language-specific.
