### ISSUE TITLE
[tool_crash] Running for web on arm64: FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by JakesMD** [flutter/flutter#76049]
I installed flutter on a Chromebook with ARM64 Linux (see [[flutter_tools] Add ARM64 Linux host and cross-building option support #61221](https://github.com/flutter/flutter/pull/61221#issue-447310852)). Flutter doctor could not find a chrome executable so I installed Chromium on Linux (see [[web]: Flutter Web not working on Chrome OS #40478](https://github.com/flutter/flutter/issues/40478#issue-493576543)). I created a new flutter project called _hello_ and ran `flutter run`

Looks like a problem with the [ARM64 Linux support](https://github.com/flutter/flutter/pull/61221#issue-447310852).
There is no directory `dev_compiler`:
```
~/development/flutter/bin/cache/dart-sdk/lib$ ls
api_readme.md  core       indexed_db  js              svg
async          developer  _internal   js_util         typed_data
cli            ffi        internal    libraries.json  web_audio
collection     html       io          math            web_gl
convert        _http      isolate     mirrors         web_sql
```

## Logs
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...                 ⣽
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file,
path =
'/home/user/development/flutter/bin/cache/dart-sdk/lib/dev_compiler/kernel
/amd/require.js' (OS Error: No such file or directory, errno = 2)".
A crash report has been written to /home/user/Flutter              
Projects/hello/flutter_03.log.
```
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:771:57)
#6      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:721:54)
<asynchronous suspension>
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:505:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:113:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.99, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-2.0.pre.99 at /home/user/development/flutter
    • Framework revision ce318b7b53 (11 hours ago), 2021-02-14 12:56:05 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 87.0.4280.141 built on
      Debian 10.7, running on Debian 10.4

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 696e4f70d1a7a9b9b793aa3fc4ad2d8d3d8eac17

**Comment by pedromassangocode** [comment]
Hi @JakesMD 
I see there's an open issue (https://github.com/flutter/flutter/issues/68958) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by JakesMD** [comment]
Hi @pedromassangocode
I'm not entirely sure whether that is a duplicate. It's throwing the same error, but it looks like a different file is missing. He has actually tried to compile the engine on Linux whereas I have simply installed flutter on arm64 Linux. But you decide.

**Comment by HidenoriMatsubayashi** [comment]
Please see https://github.com/flutter/flutter/issues/74928.

**Comment by christopherfujino** [comment]
Yes, this binary is not implemented yet: https://github.com/flutter/flutter/issues/74928, pending me updating the build rules.
