### ISSUE TITLE
stuck at dart sdk downloading while setup the flutter

### ISSUE THREAD

**Issue by Prashant4900** [flutter/flutter#76047]
## Steps to Reproduce

Whenever I tried to run any flutter or dart on cmd after installing the git bash it's start download the dart SDK again even I already set up it. I used flutter for nearly 7 8 months but I never face a problem like this recently I reset my pc and setup flutter again but this time it's not setup 

**Steps I will do for installing the flutter**
1.  download the Dart SDK and setup path in a user variable and run dart --version so it works fine its show the current dart version
2. After I setup flutter SDK similar to dart but after run dart --version and it again works fine and shows the current version or if I run any flutter command like flutter doctor its shows an error like this  
Error: Unable to find git in your PATH.
3. To resolve this error I install git 
**Now the problem has come **
4. Again when I run the dart --version its work fine but if I tried to run flutter doctor or any flutter command its start downloading the Dart SDK

`Microsoft Windows [Version 10.0.18363.1379]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\prash>dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"

C:\Users\prash>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 2f0af3715217a0c2ada72c717d4ed9178d68f6ed...
Terminate batch job (Y/N)? y

C:\Users\prash>dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"`

Please help so to fix this I doesn't want to download the dart SDK if I already setup its

**Comment by darshankawar** [comment]
@Prashant4900 
Are you able to switch between Flutter channels ? If so, after switching and running `flutter doctor -v`, it may download dart sdk since it could be first time it may be setting it up. 
What happens are all dart sdk are downloaded ? Does running `flutter doctor -v` again shows it downloading dart sdk if you are in same channel ?

Can you try to install the sdk using https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk and follow all steps ? maybe it has something to do with your PATH variables not setup properly. And also, you got the error `Error: Unable to find git in your PATH.`

**Comment by Prashant4900** [comment]
> @Prashant4900 
> Are you able to switch between Flutter channels ? If so, after switching and running `flutter doctor -v`, it may download dart sdk since it could be first time it may be setting it up. 
> What happens are all dart sdk are downloaded ? Does running `flutter doctor -v` again shows it downloading dart sdk if you are in same channel ?
> 
> Can you try to install the sdk using https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk and follow all steps ? maybe it has something to do with your PATH variables not setup properly. And also, you got the error `Error: Unable to find git in your PATH.` Did you try to find out why do got that error ?
> 

No I don't switch any flutter channel initially it's will stuck at looping to download the dart sdk not now it's will solve I don't know how but it's solve

I deleted everything and install only git or flutter (not dart) at different locations so it's also download dart SDK again but this time it's will not stuck at looping and now flutter will run fine

Also thank for reply

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing this based on your comment above.
