### ISSUE TITLE
Autofill/AutofillGroup doesnt work with obscureText: true

### ISSUE THREAD

**Issue by declanwoods** [flutter/flutter#76052]
## Steps to Reproduce

Platform: iOS (not tested on Android)

1. Create an app with an associated webcredential domain
2. Have two textfields with AutofillHints.newUsername and AutofillHints.newPassword
3. Enter text in both and then transfer page to dispose of the fields to trigger the save prompt
4. Change the fields to use AutofillHints.username and AutofillHints.password
5. Restart app and notice that autofill details are recommended and work correctly
5. Apply `obscureText: true` to the password field
6. Restart app and try to use autofill again

**Expected results:** 

Should suggest username and password autofill details as saved in the step 3

**Actual results:** 

Results vary but include the following:

- Pressing in username first doesnt suggest any autofill details
- Pressing in password first shows the "Secure password" keyboard, as it would for a new password

<details> 
<summary>flutter doctor -v</summary> 

```bash
  [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
[✓] VS Code (version 1.53.2)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.
```

</details>

Please let me know if a full example project is needed, but it will still require modification due to the nature of webcredentials

cc @LongCatIsLooong

**Comment by TahaTesser** [comment]
Hi @declanwoods 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by declanwoods** [comment]
Output:

<details>

> 
> [✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-AU)
>     • Flutter version 1.22.6 at /users/declanwoods/flutter
>     • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/declanwoods/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.0
> 
> [!] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] IntelliJ IDEA Community Edition (version 2020.1.4)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 48.0.3
>     • Dart plugin version 201.8538.45
> 
> [✓] VS Code (version 1.53.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.19.0
> 
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 3 categories.

</details>

**Comment by TahaTesser** [comment]
Hi @declanwoods 
Thanks for the details, either my host has issues or some configuration is not working, I'm unable to test this 
I will just label it for further triage
Thank you

**Comment by LongCatIsLooong** [comment]
I'm seeing a "Cannot identify the calling app's process" error on iOS 14.4 that prevented me from testing automatic strong password so I couldn't follow the exact steps. I started from step 6, with `obscureText: true` I still got the password prompt and was able to autofill both the username field and the password field. 

@declanwoods you mentioned in the last step 
>  "Restart app and try to use autofill again"

Was it a hot-restart or a cold-restart?

**Comment by declanwoods** [comment]
@LongCatIsLooong Hey, thanks for the response

It was a cold-restart, but I think a hot-reload/(hot-restart?) should work.

With regards to "Cannot identify the calling app's process", I think this appears when you haven't got a correctly linked Associated Domain. You can use this tool to confirm [https://limitless-sierra-4673.herokuapp.com](https://limitless-sierra-4673.herokuapp.com). Maybe try adding `?mode=developer` to the end of your associated domain, i.e. `webcredentials:declan.sh?mode=developer`.

Was the password prompt that you got the lock with the word "Passwords", or was it the one that comes up for linked domains, with something like "for this app" with the username underneath?

**Comment by LongCatIsLooong** [comment]
@declanwoods oh thanks it says my `apple-app-site-association` isn't served with the correct content-type.  But I think the repro doesn't look like a typical user flow (as the user typically won't be able to change the `autofillHints` of a `TextField`, and generally the autofillHints of a text field shouldn't change). Could you verify that the bug persists, if you start straight from step 6?

> Was the password prompt that you got the lock with the word "Passwords", or was it the one that comes up for linked domains, with something like "for this app" with the username underneath?

I was only able to get the generic password autofill (the one with a key icon) presumably because of the associated domain problem. But it still autofilled both fields with no problem which means the iOS heuristics for detecting autofillable password fields worked fine. So I suspected in your repro some internal states from step 2-5 carried over to step 6 and caused the issue.

**Comment by declanwoods** [comment]
That is true, this isnt typical user flow. Ill explain my case to see if there is a better way to achieve this

I am updating my app that has a large user base that already have accounts, with barely any people making new accounts. The login token lifecycle has to be fairly short for security reasons, and sometimes people will go weeks without using the app to refresh their token. This leads to them needing to log back in. 

None of these users will have saved credentials for this app as the setup pages do not attempt to save these using autofillHints. So my desired behaviour is that when they log back in, the fields tagged with `AutofillHints.username` and `.password` need to trigger an autofill "save event". The reason they are of those autofill types is because they still need to receive saved values too, incase they get logged out again.

This flow is very similar to how normal autofill on a website works. Is this achievable in Flutter?

**Comment by LongCatIsLooong** [comment]
@declanwoods ah I see. I think the best bet right now would be to still use `.username` and `.password` for your fields, and create a plugin that saves the user credentials using [`SecAddSharedWebCredential`](https://developer.apple.com/documentation/security/1617986-secaddsharedwebcredential). According to https://developer.apple.com/documentation/security/shared_web_credentials/managing_shared_credentials:

> You can change a password using the SecAddSharedWebCredential function. This is exactly the same procedure used when creating a new user account (see Listing 2). However, if credentials already exist for the given user name and domain, this method prompts the user for permission before making the change. The user can cancel this change.

This sounds like with `SecAddSharedWebCredential` you'll get the prompt UI too.

**Comment by LongCatIsLooong** [comment]
closing this in favor of https://github.com/flutter/flutter/issues/76052.
