### ISSUE TITLE
InteractiveViewer - enable 'negative' scaling

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [flutter/flutter#76069]
## Use case

InteractiveViewer widget used as **desktop image viewer** should spread the available area. Currently it can be controlled by `constrained: false`. However, in this mode the image is still constrained in a way dimensions can't be smaller than the widget itself. This is unexpected behavior. For example, if the image is tall, it cannot be displayed fully on wide desktop screen:

![image](https://user-images.githubusercontent.com/3907898/107959900-42256a00-6fa4-11eb-95bd-8d53c577f12c.png)

The goal is to be able to display entire image:
![image](https://user-images.githubusercontent.com/3907898/107960957-90873880-6fa5-11eb-910f-94852efeab51.png)

And make it even smaller
![image](https://user-images.githubusercontent.com/3907898/107961159-d0e6b680-6fa5-11eb-9e30-48ab731d8792.png)

## Proposal
1. Backward incompatible. For `constrained` use enum instead of boolean. 
    - `ON` = current true
    - `WIDGET` = current false
    - `OFF` = doesn't apply any additional constraints, the scale can be set freely in <minScale, maxScale> range
2. Backward compatible. Keeping `constrained` as it is, but introduce a new option, e.g. `enableFullScaleRange`. By default false. When true, no additional constraints are aplied, the scale can be set freely in <minScale, maxScale> range

When the content size is smaller than the widget size, some new behavior needs to be elaborated:
- it should be possible to specify background (by default transparent)
- it should be possible to specify alignment in both axis (left center right : top center bottom)

**Comment by jan-tosovsky-cz** [comment]
I've just found `boundaryMargin: EdgeInsets.all(double.infinity)` solves my issue. Originally I haven't expected "margin" can have some relation to scaling.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I'll go ahead and close this since it seems to be achievable as-is.

I want to point out another issue that brings up the idea of a boxFit for InteractiveViewer.  That might make things like this easier.  Or maybe the docs could be improved to make it clear that the boundary will prevent scaling?
