### ISSUE TITLE
Locale HINDI - INDIA is not rendering on web via desktop browser while mobile browser rendering properly.

### ISSUE THREAD

**Issue by Abhishek0116** [flutter/flutter#76062]
## Locale HINDI - INDIA is not rendering on web via desktop browser while mobile browser rendering properly.

I am creating a Flutter Application for my client and targeting all platform for my experiment.
Here is two locale I used
1. EN-US (English - United State)
2. HI-IN (Hindi - India)

App working on all platform offered by Flutter but I it's look like a bug on web platform.
Web platform displaying some locale like unsupported character on web via desktop but displaying correctly on web via mobile platform.

## Here is reference screenshots

![Screenshot 2021-02-15 at 17 19 49](https://user-images.githubusercontent.com/35359840/107945266-5d4ca580-6fb5-11eb-92a3-589d4bcd0e2f.png)

![Screenshot_1613389465](https://user-images.githubusercontent.com/35359840/107945308-6f2e4880-6fb5-11eb-9617-d16dc67f9bbc.png)

## Here is actual web URL*

[Bug URL](https://beetalubricants.com
)

*URL is for demo purpose only and may not be unavailable in future.

## Here is output of `flutter doctor -v`

```
abhishekkumar@Abhisheks-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-IN)
    • Flutter version 1.26.0-12.0.pre at /Users/abhishekkumar/flutter
    • Framework revision a706cd2112 (5 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/abhishekkumar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
abhishekkumar@Abhisheks-MacBook-Air ~ % 
```

**Comment by darshankawar** [comment]
@Abhishek0116 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/73628 which is related to special characters not rendering on web properly.
Please follow-up there for updates. Closing this as duplicate.
