### ISSUE TITLE
gradle build

### ISSUE THREAD

**Issue by AhmebashaAnter** [flutter/flutter#76070]
```bash
class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```
![Screen Shot 02-15-21 at 05 05 PM](https://user-images.githubusercontent.com/76538677/107963244-98000f00-6fb0-11eb-800a-cd3103841679.PNG)

**Comment by TahaTesser** [comment]
Hi @AhmebashaAnter 
The issue isn't clear, looks like a copy/paste
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by AhmebashaAnter** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle.
> Could not configure services using GradleScopeCompileServices.configure().


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Exception: Gradle task assembleDebug failed with exit code 1
![Screen Shot 02-15-21 at 05 52 PM](https://user-images.githubusercontent.com/76538677/107968468-13fd5580-6fb7-11eb-9de0-1c8bf607772b.PNG)
![Screen Shot 02-15-21 at 05 49 PM](https://user-images.githubusercontent.com/76538677/107968485-18c20980-6fb7-11eb-83ec-b4d9afe53b53.PNG)
![Screen Shot 02-15-21 at 05 55 PM 001 - Copy](https://user-images.githubusercontent.com/76538677/107968492-1a8bcd00-6fb7-11eb-8b78-3a6c678ca13d.PNG)
![Screen Shot 02-15-21 at 05 55 PM - Copy](https://user-images.githubusercontent.com/76538677/107968497-1bbcfa00-6fb7-11eb-9bd0-606dc608fe98.PNG)

**Comment by AhmebashaAnter** [comment]
![Screen Shot 02-15-21 at 05 55 PM 001](https://user-images.githubusercontent.com/76538677/107968619-40b16d00-6fb7-11eb-96ca-1ab554991938.PNG)
![Screen Shot 02-15-21 at 05 55 PM](https://user-images.githubusercontent.com/76538677/107968624-4313c700-6fb7-11eb-971f-c74a91751fa9.PNG)
![Screen Shot 02-15-21 at 05 53 PM](https://user-images.githubusercontent.com/76538677/107968627-4444f400-6fb7-11eb-84ae-6c9839053347.PNG)
![Screen Shot 02-15-21 at 05 52 PM](https://user-images.githubusercontent.com/76538677/107968633-460eb780-6fb7-11eb-8c59-62f02bc332ae.PNG)
![Screen Shot 02-15-21 at 05 49 PM](https://user-images.githubusercontent.com/76538677/107968635-46a74e00-6fb7-11eb-9535-e8dfc774f790.PNG)

**Comment by AhmebashaAnter** [comment]
> Hi @AhmebashaAnter
> Please make sure you've a stable internet connection, this requires a network for Gradle process
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

i tried many soultions but not fixed
