### ISSUE TITLE
Update libpng

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#76079]
Our libpng seems to be 5 years old, assuming it's the one in buildroot. We should upgrade to a more recent version.

cc @timsneath @zanderso @jason-simmons

**Comment by Hixie** [comment]
@jason-simmons Since you seem to be working on this I've assigned it to you, hope that's ok. Thanks for looking at it!

**Comment by chinmaygarde** [comment]
Can we just put this behind an autoroller instead of managing manual updates?

**Comment by chinmaygarde** [comment]
We are waiting on the creation and import of a [separate managed repository](https://flutter.googlesource.com/third_party/libpng/) for the dependency. Jason is following up with @godofredoc about it.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/24616.
