### ISSUE TITLE
FFI support for locally hosted pub

### ISSUE THREAD

**Issue by ErrApparent** [flutter/flutter#76078]
## Use case

I am using a locally hosted pub and trying to import internal packages with C interop.
The build fails when the Flutter toolchain uses Ninja on a pub-cache path.
It doesn't work because Flutter pub-cache uses "%" when ports are involved, Flutter cmake uses Ninja, and Ninja gets confused by "%".
Using a "path" field in the dependency isn't really a solution for team projects. Yes, team projects could use path with a shared remote directory, or have a privately served pub without a port, but it'd be nice to have this use case work without additional setup.

## Proposal

Please adjust the pub-cache format to be compatible with your toolchain. This seems like the easiest fix.
An interim workaround that should work is via name resolution on the local machine (I think; I'm not 100% clear on whether it is the port specification that introduces the "%").

**Comment by TahaTesser** [comment]
Hi @ErrApparent
`pub` package manager isn't part of Flutter, Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
Thank you
