### ISSUE TITLE
[Web] Timing issue using js.dart package & HtmlElementView

### ISSUE THREAD

**Issue by ylruiz** [flutter/flutter#76071]
I'm having a timing issue when I try to call a javascript method for my flutter app because the expected DivElement isn't in the widget tree when I need to use it. However, I don't understand why that is happening. 

Here is a minimal example:

**Project Structure (just involved folders and files)**
```
project_name 
- lib
   - container.dart
   - main.dart
- web
   - js
       - container.js
   - index.html
- pubspec.yaml
```

**pubspec.yaml**
  ```
  ...
  dependencies:
    flutter:
      sdk: flutter
    js: ^0.6.0
 ...
```

**container.js**
```
function showText() {
  setTimeout(() => {
    const rootElem = document.getElementById("div_container_elem");
    const paragraph = document.createElement("p");
    const textNode = document.createTextNode("It's my favorite");

    paragraph.appendChild(textNode);
    rootElem.appendChild(paragraph);
  }, 300);
}
```

**index.html**
```
...
<script src="js/container.js" type="application/javascript"></script>
...
```

**container.dart**
```
@JS()
library container;

import 'package:js/js.dart';

@JS('showText')
external void showText();
```

<details> 
 <summary><strong>main.dart</strong></summary>
<code>

    // ignore: avoid_web_libraries_in_flutter
    import 'dart:html' as html;
    import 'dart:ui' as ui;
    import 'package:flutter/material.dart';
    
    import 'container.dart';
    
    void main() => runApp(MyApp());
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Timing issue',
          home: Scaffold(
            appBar: AppBar(
              title: Text('Timing issue'),
            ),
            body: Home(),
          ),
        );
      }
    }
    
    class Home extends StatefulWidget {
      @override
      _HomeState createState() => _HomeState();
    }
    
    class _HomeState extends State<Home> {
      bool _isFavorite;
    
      @override
      void initState() {
        super.initState();
        _isFavorite = false;
      }
    
      @override
      Widget build(BuildContext context) {
        return Container(
          width: 300,
          height: MediaQuery.of(context).size.height * 0.57,
          child: CardView(
            isFavorite: _isFavorite,
            isFavoriteChanged: () => setState(() => _isFavorite = !_isFavorite),
          ),
        );
      }
    }
    
    class CardView extends StatelessWidget {
      final bool isFavorite;
      final VoidCallback isFavoriteChanged;
    
      const CardView({Key key, this.isFavorite, this.isFavoriteChanged})
          : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return Card(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Image.network(
                    "https://images.unsplash.com/photo-1613315051145-30905e91ed7c?ixid=MXwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw4fHx8ZW58MHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
                    width: 300,
                    height: 350,
                  ),
                  isFavorite ? showHtmlElement() : Container(),
                ],
              ),
              SizedBox(
                height: 8,
              ),
              ButtonBar(
                children: <Widget>[
                  TextButton(
                    child: Icon(
                      !isFavorite ? Icons.favorite_border : Icons.favorite,
                      color: Colors.black,
                      size: 30,
                    ),
                    onPressed: () => isFavoriteChanged(),
                  ),
                ],
              ),
            ],
          ),
        );
      }
    
      Widget showHtmlElement() {
        String viewId = 'div_container_elem';
        html.DivElement htmlData = html.DivElement()..id = viewId;
    
        // ignore: undefined_prefixed_name
        ui.platformViewRegistry
            .registerViewFactory(viewId, (int viewId) => htmlData);
    
        showText(); // call the showText() method located in web/js/container.js
    
        return Container(
          width: 300,
          height: 350,
          child: HtmlElementView(
            viewType: viewId,
          ),
        );
      }
    }
</code>
</details>

With this in mind, let me explain the problem. When I delete the method `setTimeout()`, the app throws the following error:

<details>
  <summary> NoSuchMethodError: invalid member on null: 'appendChild' </summary>
  <code>

      ══╡ EXCEPTION CAUGHT BY WIDGETSLIBRARY╞══
      The following JSNoSuchMethodError was thrown building CardView(dirty):
      NoSuchMethodError: invalid member on null: 'appendChild'
      
      The relevant error-causing widget was:
        CardView file:///Users/yunetluisruiz/Documents/projects/artivive/time_issue/lib/main.dart:44:14
      
      When the exception was thrown, this was the stack:
      js/container.js 8:14                                 showText
      packages/time_issue/main.dart 103:5                  showHtmlElement
      packages/time_issue/main.dart 72:28                  build
      packages/flutter/src/widgets/framework.dart 4645:28  build
      packages/flutter/src/widgets/framework.dart 4571:15  performRebuild
      packages/flutter/src/widgets/framework.dart 4265:5   rebuild
      packages/flutter/src/widgets/framework.dart 4652:5   update
      packages/flutter/src/widgets/framework.dart 3361:14  updateChild
      packages/flutter/src/widgets/framework.dart 6057:14  update
      packages/flutter/src/widgets/framework.dart 3361:14  updateChild
      packages/flutter/src/widgets/framework.dart 4596:16  performRebuild
      packages/flutter/src/widgets/framework.dart 4265:5   rebuild
      packages/flutter/src/widgets/framework.dart 4652:5   update
      packages/flutter/src/widgets/framework.dart 3361:14  updateChild
      packages/flutter/src/widgets/framework.dart 4596:16  performRebuild
      packages/flutter/src/widgets/framework.dart 4743:11  performRebuild
      packages/flutter/src/widgets/framework.dart 4265:5   rebuild
      packages/flutter/src/widgets/framework.dart 2595:31  buildScope
      packages/flutter/src/widgets/binding.dart 873:9      drawFrame
      packages/flutter/src/rendering/binding.dart 319:5    [_handlePersistentFrameCallback]
      packages/flutter/src/scheduler/binding.dart 1144:15  [_invokeFrameCallback]
      packages/flutter/src/scheduler/binding.dart 1082:9   handleDrawFrame
      packages/flutter/src/scheduler/binding.dart 998:5    [_handleDrawFrame]
      lib/_engine/engine/platform_dispatcher.dart 931:13   invoke
      lib/_engine/engine/platform_dispatcher.dart 147:5    invokeOnDrawFrame
      lib/_engine/engine.dart 261:45                       <fn>
  </code>
</details>

**I don't have clear why that is happening (or if that is supposed to happen). Why doesn't the app add the DivElement in the widget tree when I registered the platform view?**

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on macOS 11.1 20C69 darwin-arm, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (1 available)

• No issues found!
```

Thanks in advance!

**Comment by TahaTesser** [comment]
Hi @ylruiz 
This seems to dart js than Flutter. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+HtmlElementView).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
