### ISSUE TITLE
Create a health to ensure swarming user is auto logged in in mac

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76091]
Tests for flutter desktop require the GUI to be available to run the desktop application. If the user is not logged in the test just hangs until the task times out.

We need to create a health check to quarantine mac bots where the swarming user is not configured to auto login.

**Comment by keyonghan** [comment]
Before implement the health check, we need to set up auto login for all Macs swarming users first.
Currently only mac6, mac9 and mac10 are set up.

**Comment by godofredoc** [comment]
I manually set the auto login for all the macs from 6-11 a few days ago

**Comment by keyonghan** [comment]
This is how it looks on mac7:
![Screen Shot 2021-02-18 at 4 43 19 PM](https://user-images.githubusercontent.com/54558023/108440693-7ac57d80-7208-11eb-9c66-76228a2dd88d.png)

**Comment by godofredoc** [comment]
I see that is because mac-7 is not actually being used for mac/ios. The phone connected to the machine is an iphone 6 that does not update to anything about ios 12.3.

**Comment by keyonghan** [comment]
Blocked on https://github.com/flutter/flutter/issues/76389

**Comment by keyonghan** [comment]
This has been implemented and validated in staging pool.
