### ISSUE TITLE
SpriteBoxEvent should be rationalised with PointerEvent

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#761]
The SpriteBoxEvent API is now different than the PointerEvent API in a confusing way.
I recommend we just remove SpriteBoxEvent and just pass the PointerEvents through unmodified.

(For now I've changed SpriteBoxEvent.type to be a Type rather than a String, but that doesn't seem like a great API. See #760.)

**Comment by Hixie** [comment]
cc @vlidholt

**Comment by abarth** [comment]
We've moved sprites out of the main SDK.
