### ISSUE TITLE
Add removeRoute by name to the Navigator class

### ISSUE THREAD

**Issue by marynovskyi** [flutter/flutter#76113]
Hi,

Could you add another implementation of removeRoute method from Navigator class, so we can remove route by its name. This should be easy to implement since Navigator uses _history list to manage history of routes and therefore route name should be enough to find it and remove.

**Comment by darshankawar** [comment]
@marynovskyi 
Check out the Navigator 2.0 design [doc](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit) and see if it already answers your question. You may also check the updated routes and navigator api [doc](https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring) to see if it helps.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
