### ISSUE TITLE
I'm trying to display polylines as per Google road map on my flutter app using authorized google key which is working fine in android app. But In flutter app it's showing unauthorised key.

### ISSUE THREAD

**Issue by bhagyashrieducloud** [flutter/flutter#76118]
I'm using google_maps_flutter: ^0.5.11+1 and flutter_polyline_points: ^0.1.0 plugin.

When i'm debugging internal libraries i'm getting following errors in response -> { "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 2405:204:969c:11f6::24b9:a8a4, with empty referer", "routes" : [], "status" : "REQUEST_DENIED" }
My code is in this file->
[Google_Map_Page.txt](https://github.com/flutter/flutter/files/5989008/Google_Map_Page.txt)

**Comment by darshankawar** [comment]
@bhagyashrieducloud 
Didn't you just open a similar issue which we closed ? https://github.com/flutter/flutter/issues/76115 ?
Also, you seem to be on very old version of `google_maps_flutter`. Current version is https://pub.dev/packages/google_maps_flutter/install
Try with latest version and see if it works. Else, please use the links we referred in your previous issue to get help on it. https://github.com/flutter/flutter/issues/76115

**Comment by darshankawar** [comment]
Closing this as solved based on https://github.com/flutter/flutter/issues/76115#issuecomment-782062082
