### ISSUE TITLE
Expose navigation history from NavigatorState

### ISSUE THREAD

**Issue by marynovskyi** [flutter/flutter#76112]
Hi,

Could you expose access to navigation history (NavigatorState._history) in order to be able to view history without reinventing the wheel. It should be quite easy to implement, since just simple getter need to be added, like this:
`List<Route> get history => List<Route>.from(_history);`

**Comment by darshankawar** [comment]
@marynovskyi 
There was similar [issue](https://github.com/flutter/flutter/issues/40329) raised earlier which was closed in favor of https://github.com/flutter/flutter/issues/45938. You may need to follow-up in it to get more details on your issue. 
Also, check out Navigator 2.0 [document](https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring#description-of-change) to get more insights on it.

Closing this as duplicate.
