### ISSUE TITLE
Disabled behavior of floating action buttons like other buttons

### ISSUE THREAD

**Issue by Chris1234567899** [flutter/flutter#76120]
## Use case

Currently, a fab (floating action button) can be disabled by setting the onPressed attribute to null. This is in accordance with other buttons and fine like it is. However, in contrary to the behavior to other buttons, the visuals do not change, so the user does not know that the button is disabled.
The [docs ](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html) state that it's better to never disable it at all, or change the background color manually, which of course can be done. But I don't see the reason to why not automatically adapt the color, if it's disabled. Imo the behavior should be the same as with other buttons.

## Proposal

Automatically adapt the color, if the fab is disabled, so no cumbersome workaround is needed.

**Comment by emem365** [comment]
> If the onPressed callback is null, then the button will be disabled and will not react to touch. It is highly discouraged to disable a floating action button as there is no indication to the user that the button is disabled. Consider changing the backgroundColor if disabling the floating action button.

 - [Docs](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html)
Seems like this could be a nice addition to the behavior. I'd be willing to open a PR if that's alright :)

**Comment by iamchathu** [comment]
Yeap it will nice that FAB too works like the other buttons when disabled.

**Comment by jesselpereira** [comment]
Great

**Comment by vedantkulkarni** [comment]
Hey please can I work on this ?

**Comment by guidezpl** [comment]
From Material's perspective, FABs should never be disabled (show enabled or not at all), so the actual fix here would be to make the onPressed callable non-nullable and required.

**Comment by guidezpl** [comment]
107480
