### ISSUE TITLE
Fall back to software rendering when we encounter GL issues on desktop

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#76132]
https://github.com/flutter/flutter/issues/75536 and https://github.com/flutter/flutter/issues/51286 document cases where GL issues caused abort at startup. In these cases, we should ideally:

1. Emit a more useful error message indicating the user should update their graphics drivers.
2. Fall back back to software rendering.

**Comment by gw280** [comment]
This seems to be getting more and more prevalent, and the correct solution here is to fully fallback to software rasterisation through Skia.

**Comment by leielyq** [comment]
It's so funny, this problem has existed for more than a year and has not been solved yet.

**Comment by leielyq** [comment]
It is recommended to use go-flutter
