### ISSUE TITLE
Unable to generate Release build for Flutter application

### ISSUE THREAD

**Issue by dashanan13** [flutter/flutter#76144]
Hi, I am trying to generate a signed bundle for my Working Flutter application but i keep getting a huge number of null messages.
Tool: Android Studio
Steps:
1. Compiled Flutter app nd installed on various mobiles, it works
2. Next Opened the Android module in Android Studio to generate signed bundle
3. Created New Key store
4. Selected Release as build type and let it process.
5. Got a bunch of errors, shown below.

```
> Task :app:compileFlutterBuildRelease FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\MobileApps\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\MobileApps\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
1 actionable task: 1 executed
[app-build.gradle.txt](https://github.com/flutter/flutter/files/5991468/app-build.gradle.txt)
[project-build.gradle.txt](https://github.com/flutter/flutter/files/5991469/project-build.gradle.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/5991471/pubspec.yaml.txt)
[error_message.txt](https://github.com/flutter/flutter/files/5991476/error_message.txt)


```

**Comment by darshankawar** [comment]
@dashanan13 
Looking at the error messages, it shows below:

```
../../../flutter/packages/flutter/lib/src/rendering/layer.dart:223:36: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.


Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
```

This may indicate some of the plugins you are using are not null safety ready yet and you may be trying to release app with null safety enabled.  Can you provide `flutter doctor -v` ?   Check [this](https://flutter.dev/docs/null-safety) document to know more about null safety .

Try the suggestions mentioned in the error messages `Try removing the package language version or setting the language version to 2.10 or higher.` and check if it resolves your issue.

I am closing this as not an issue with the framework, but some conflicts in your setup related to null safety. If you disagree, write in comments and I'll reopen it.  You may also look for solutions on how to fix those errors by asking this in StackOver flow or other support communities.

**Comment by dashanan13** [comment]
@darshankawar I do read the error message and it does confuse me that the same package installs and compiles to my test devices.
Attaching 'flutter doctor -v' but this error comes up when I try to generate a signed build like shown [here](https://stackoverflow.com/questions/55536637/how-to-build-signed-apk-from-android-studio-for-flutter)
Attaching the latest 'pubspec.yaml' too.

**I do not see which package do to take care of and where do i set the language version to 2.10 or higher**
**Also the error complains about gradle version 7 but i File: google-services.json shows version 6.5**

The only help i found is [this](https://stackoverflow.com/questions/63969287/flutter-error-null-safety-features-are-disabled-for-this-library)

===================================
**Output for gradlew build --warning-mode all**

> Task :app:compileFlutterBuildDebug FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\MobileApps\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
[error.txt](https://github.com/flutter/flutter/files/6018854/error.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/6018855/pubspec.yaml.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/6018859/pubspec.yaml.txt)
[error.txt](https://github.com/flutter/flutter/files/6018860/error.txt)




Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\MobileApps\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
1 actionable task: 1 executed

===================================

===================================
**File: google-services.json**

Wed Feb 17 12:14:07 CET 2021
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip

===================================

===================================
**C:\MobileApps\ProApps\akshar\akshar>flutter doctor -v**
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1377], locale en-US)
    • Flutter version 1.22.5 at C:\MobileApps\flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\mohsharm\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • SM A530F (mobile) • 520057c78c9db563 • android-arm64 • Android 9 (API 28)
    • Redmi 4 (mobile)  • 53bb3687d040     • android-arm64 • Android 7.1.2 (API 25)

Doctor found issues in 2 categories.

===================================

**Comment by shameemreza** [comment]
Yesterday I faced same issues. Probably you have enabled Flutter web.

To resolve, I did flutter clean, Pub get and then run the debug and got it working everything.

If above things dont work, you may try by changing the SDK to 2.10.

**Comment by dashanan13** [comment]
@shameemreza  I am not sure i have Flutter web enabled and belive me when i say i have tried Flutter clean, coz i have tried it many times.
I think you were referring to Dart SDK, i have it at  Dart version 2.10.4, i think that should be ok, right?
I am a beginner and i have not done any customization, the same code works when i deploy it on device via run, it builds and installs.

Thanks for the response brother but i think i need more suggestion, if you have any do let me know :)

**Comment by shameemreza** [comment]
If you have 2.10+ on Environment SDK, then again revert it to 2.7.0. And if its still 2.7.0, then try changing to 2.10+.

![Screenshot_2](https://user-images.githubusercontent.com/14240438/108703127-66e58880-7534-11eb-9b54-a7e86783895c.jpg)

But make sure you did: Flutter Clean, Flutter pub get and then flutter run.

**Comment by dashanan13** [comment]
@shameemreza 
I tried the below steps
1.   sdk: ">=2.7.0 <3.0.0" changed to   sdk: ">=2.10.0 <3.0.0"
2. Flutter Clean
3. Flutter pub get
4. On Android Studio, Tools > Flutter > Open Android module in Android Studio
5. Wait for Gradle sync to complete on the new Android studio window
6. On New Android Studio, Build > Generate Signed Bundle (s) / APK (s)

It did go through and got a release build but to be true I don't understand why???
Except point 1 i did everything else, a number of times all night yesterday
Can you explain a bit what happened? 
If a package had null exceptions, why is it not there anymore?

**Comment by shameemreza** [comment]
Now if you try using 2.7.0 also will works. but make sure you do the flutter clean and pub get command. It seems, Sometimes Android studio or VS code auto pub get dont work properly.

**Comment by dashanan13** [comment]
Can you explain a bit what happened?
If a package had null exceptions, why is it not there anymore?
@shameemreza

**Comment by shameemreza** [comment]
To understand it clearly, I will suggest you to read this: https://dart.dev/null-safety/understanding-null-safety

What I can tell from Flutter docs (https://flutter.dev/docs/null-safety) is, Not all parts of the Flutter SDK support null safety yet, as some parts still need additional work to migrate to null safety.

Also, dont forget to read Null safety frequently asked questions in dart docs.

**Comment by dashanan13** [comment]
@shameemreza  Thanks, i will try to understand the concepts a lot better.
