### ISSUE TITLE
Flutter's interaction with Android's new Instant Apps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7614]
Looks like Instant Apps is starting to get rolled out for testing. We may want to better understand how Flutter interacts with Instant Apps and what the trade-offs are.

Learn more: https://android-developers.googleblog.com/2017/01/android-instant-apps-starts-initial.html

**Comment by yathit** [comment]
👍 interested my app also available as Instant App

**Comment by GuruKyuu** [comment]
Also looking for more information here.

**Comment by agicquel** [comment]
Hello there, what's point now for the instant app availability ?

**Comment by Hixie** [comment]
Closing in favour of https://github.com/flutter/flutter/issues/16833.

**Comment by randallmitchell** [comment]
Eight months of hard work has brought the APK size of the official hello world app down to 4.2MB.  The work done to reduce framework and build size looks to have been a phenomenal and worthwhile success. Sadly, I don't think it has come anywhere close to the mark for what is needed to support Instant Apps.  If this the now current Flutter base size is cut again in half, developers would still only have under 2MB of leeway for building engaging apps. Closing the Instant App conversation in favor of simply trying to reduce APK size seems invalid from this perspective.

From the perspective of what the entire Instant App modular architecture tries to achieve, I think the idea of supporting Instant App through a single binary file was never valid. A single binary means large, complex apps cannot be broken down into small chunks to alleviate download size.  This requirement limits all apps to having a size of somewhere south of 4MB of app specific binary, regardless of how small Flutter can get it's own framework.  Is this even feasible for the more robust apps and games currently on the market?

While the binary shrinking endeavor has been going on, Instant App has grown in support by the Play Store - the Play Store now leverages Instant App architecture for the traditional app install.  In other words, Google has further ingrained instant apps into the ecosystem. It seems to me, reducing APK size is a short term workaround for what may grow to be a very large problem.

I hope Flutter begins to face this problem in earnest.  This means support for modular applications.

Ultimately, if Flutter wants to support Instant Apps, it will undoubtedly need to make some significant and painful changes.  Flutter should probably either acknowledge that it will never really support Instant Apps, or it should begin considering the structural implications such support would mean.

**Comment by rodydavis** [comment]
Could we use flutter web for instant apps?

**Comment by Hixie** [comment]
Commenting on closed bugs will have no effect; please file a new bug if you have specific requests. Thanks.
