### ISSUE TITLE
Set up Android and iOS method channel unit tests infrastructure in flutter/plugins for webview_flutter.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#76152]
Some code in `webview_flutter` could be benefit from having java/objc unit tests to test java/objc implementations. For example: https://github.com/flutter/plugins/pull/2895

As examples, we do have some plugins that contains method channel unit tests, such as https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/ios/Tests/ImagePickerPluginTests.m

We need to at least set up the unit test infrastructure, so future PRs can simply add tests.

**Comment by stuartmorgan** [comment]
The Dart-first rewrite added a lot of test coverage, so I think this is probably resolved (especially since with the switch to Pigeon, we don't need tests of the channel part in particular).
