### ISSUE TITLE
Flutter swarming pools are using two versions of Windows bots

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#76166]
Flutter swarming builders are expected to use Windows Server 2019 only, but swarming pools seem to still have two versions of Windows bots:
![Screen Shot 2021-02-16 at 4 19 01 PM](https://user-images.githubusercontent.com/54558023/108138433-d4943f00-7072-11eb-96b4-0a7fd2d5fb43.png)

**Comment by 06000000-0000** [comment]
Diamond

**Comment by 06000000-0000** [comment]
Hi
