### ISSUE TITLE
The Route didPush and didPop methods are not just notifications

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#7617]
Methods called didFoo() sound like notifications that Foo has happened.

The Route methods called didPop and didPush are not just notifications that a Navigator pop or a push operation has happened, although they are called immediately upon a call to Navigator.push or Navigator.pop. Routes use these methods to start transitions and, in the case of didPop, to [optionally] carry out the pop operation. Perhaps they should just be called push() and pop() or finishPush() and finishPop().

#7611 further complicates matters by having didPush() return a Future that resolves when the push transition (if any) completes. It would be nice if didPop also returned a Future with the same meaning, but didPop already returns a boolean that indicates if the pop operation was handled internally.

**Comment by Hixie** [comment]
@HansMuller Did you have any alternative names in mind?

I think it's not wrong to view them as notifications. The Navigator is notifying the route. The route then does something with the notification, as is usually the case when one listens for a notification.

**Comment by HansMuller** [comment]
What I found confusing was that when I overrode `Route.didPush()` I was handling a Navigator notification, not responding to the fact that the Route had already been pushed. 

That said, I'm pretty sure I filed this issue with the understanding that I'd come up with an alternative naming scheme proposal, and it's been a long time and I've got nothing.  So I will close it.
