### ISSUE TITLE
engine -> framework rolls blocked on failing web tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76182]
See https://github.com/flutter/flutter/pull/76169

From web_e2e_test: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8855091937959594400/+/steps/prepare_environment/0/steps/Web_e2e_tests/0/steps/web_e2e_test/0/stdout?format=raw

```
Running "flutter pub get" in web_e2e_tests...                    1,363ms
Launching test_driver/text_editing_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         28.6s
test_driver/text_editing_integration.dart is being served at http://localhost:38357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
Failure Details:
Failure in method: Focused text field creates a native input element
â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
The following message was thrown:
Multiple exceptions (23) were detected during the running of the
current test, and at least one was unexpected.
```

But see also:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8855091906176725072/+/steps/run_test.dart_for_web_long_running_tests_shard_and_subshard_1_3/0/stdout?format=raw

I suspect the buildroot roll in that roll is unrelated, which indicates https://github.com/flutter/engine/pull/24249 might have introduced the issue.

/cc @hterkelsen @yjbanov

**Comment by zanderso** [comment]
This is still waiting on a successful engine -> framework roll to confirm that it is fixed.

**Comment by mdebbar** [comment]
@zanderso FYI the web integration tests already passed in the new roll (https://github.com/flutter/flutter/pull/76314).
