### ISSUE TITLE
Google_map_flutter of strigePC, the branch about map ground overlay, overlayed image lays on polyline

### ISSUE THREAD

**Issue by CuongPTIT** [flutter/flutter#76191]
Hi bro,
I am using 
  google_maps_flutter:
    git:
      url: https://github.com/strigePC/plugins.git
      path: packages/google_maps_flutter/google_maps_flutter/
      ref: maps-ground-overlays
this is a branch of strigePC to make overlays image on Google Map. It is normal on Android but on IOS, the overlayed image lays on polyline. Who is having this issue?

**Comment by darshankawar** [comment]
@CuongPTIT 
Please ask this question in `strigePC` repo, as it is external and 3rd party to Flutter.
Closing from here, as it's not related to framework. 

If you disagree or getting the issue directly using the `google_maps_flutter` [plugin](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example) (not using `strigePC`, write in comments and provide all required details to properly address it.
