### ISSUE TITLE
I am not able use flutter on linux [kali]

### ISSUE THREAD

**Issue by GNVageesh** [flutter/flutter#76209]
I recently changed my OS from Windows 10 to Kali Linux and started with flutter development here as well. It worked well for a while. And 2-3 months, now, when I removed the version that was there and replaced it with the latest stable version, 1.22.6 for Linux, and when I run flutter doctor, I get this error shown in the following link: https://i.stack.imgur.com/1U5ts.png

A further flutter doctor -v gives me this https://textuploader.com/18xbv

Please help me out with this

**Comment by pedromassangocode** [comment]
Hi @GNVageesh 
As the error says: `Please ensure that the SDK and/or project is installed in a location that has read/write
      permissions for the current user.`

You must install Flutter in a directory with read/write access.
