### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by hemanthkb97** [flutter/flutter#76214]
This is happing in web, when i refresh page.
Restarted application in 153ms.

Restarted application in 371ms.

```
[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building Builder:[39;49m
setState() or markNeedsBuild() called during build.

[38;5;244mThis Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.[39;49m
[38;5;244mThe widget on which setState() or markNeedsBuild() was called was: Overlay-[LabeledGlobalKey<OverlayState>#b7bea][39;49m
    [38;5;244mstate: OverlayState#450fe(entries: [OverlayEntry#5680a(opaque: true; maintainState: false), OverlayEntry#378e9(opaque: false; maintainState: true), OverlayEntry#c1e15(opaque: false; maintainState: false), OverlayEntry#a70af(opaque: false; maintainState: true)])[39;49m
[38;5;244mThe widget which was currently being built when the offending call was made was: Builder[39;49m
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mMaterialApp[39;49m
 lib\main.dart
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;248mC:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_[39;49m
[38;5;248mpackages/flutter/src/widgets/framework.dart 4152:11                                                                        <fn>[39;49m
[38;5;248mpackages/flutter/src/widgets/framework.dart 4166:14                                                                        markNeedsBuild[39;49m
[38;5;248mpackages/flutter/src/widgets/framework.dart 1126:5                                                                         setState[39;49m
[38;5;248mpackages/flutter/src/widgets/overlay.dart 436:5                                                                            rearrange[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m


flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

• No issues found!

```

**Comment by Abhishek01039** [comment]
`if(mounted)` Please use this condition while calling setstate.

**Comment by iapicca** [comment]
@hemanthkb97 
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by hemanthkb97** [comment]
> `if(mounted)` Please use this condition while calling setstate.
> 
> 

I have used that

**Comment by hemanthkb97** [comment]
> @hemanthkb97
> can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

when i was trying to minimal the code i found that when i reload my app web i am getting user null

if (user == null) {
      user = await FirebaseAuth.instance.authStateChanges().first;
      inspect(user);
      if (user == null)
        Navigator.pushNamedAndRemoveUntil(
            context, '/welcome', (route) => false);
      else
        print(user.uid);
    }
i remove everything to make sure nothing else causing problem, but still im getting user null when i reload

[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
    • Flutter version 1.27.0-1.0.pre at D:\flutter
    • Framework revision 68c96f100e (9 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Hemanth\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Andriod studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Andriod studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Hemanth\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

**Comment by darshankawar** [comment]
@hemanthkb97 
By `minimal complete reproducible code sample`, we meant a code sample that we can directly copy paste and run to see the issue. The one you provided has lot of 3rd party plugins which are not required. Please update your code sample to have minimal reproducible code sample (without 3rd party, ex: firebase and others) that show the issue you are getting.

For your another issue of getting `null` user, it seems to be code implementation issue and should be asked in support channels like StackOverflow. If you think using firebase you are getting null user on web, please file this issue in dedicated repo : https://github.com/FirebaseExtended/flutterfire/issues

**Comment by hemanthkb97** [comment]
@darshankawar  okay i created new project without any 3rd party plugins

<details><summary>Click To Expand</summary>
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

FirebaseAuth _auth = FirebaseAuth.instance;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String email, pass;

  @override
  void initState() {
    checkuser();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: 500,
        height: 300,
        child: Column(
          children: [
            TextField(
              onChanged: (value) {
                email = value;
              },
            ),
            TextField(
              onChanged: (value) {
                pass = value;
              },
              onSubmitted: (value) {
                singin(email, pass);
              },
            )
          ],
        ),
      ),
    );
  }

  void singin(email, pass) {
    _auth.signInWithEmailAndPassword(email: email, password: pass);
    if (_auth.currentUser != null) {
      print(_auth.currentUser.email);
    }
  }

  void checkuser() {
    if (_auth.currentUser != null) {
      print(_auth.currentUser.email);
    } else {
      print("no user");
    }
  }
}
</details>

**Comment by iapicca** [comment]
@hemanthkb97 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin
> okay i created new project without any 3rd party plugins
> [...]
> ```dart
> import 'package:firebase_auth/firebase_auth.dart'; 
> ```

**Comment by darshankawar** [comment]
@hemanthkb97 
As mentioned above, please update your code sample without firebase and check if you still get the issue. If so, provide the updated sample.

**Comment by hemanthkb97** [comment]
i posted the issue in flutterfire,
Thanks for response :)
