### ISSUE TITLE
Improve error message if no font could be found to display all characters

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#76212]
The error message `Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters.` should be improved to contain the list of characters (hexcodes) or at least the first missing character.

Even better would be a reference to the location in source code where this occured.

**Comment by darshankawar** [comment]
@hlemcke 
Can you provide `flutter doctor -v` and when / how do you get this error message ?

**Comment by hlemcke** [comment]
Output of Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!
```

The error message appears sometimes when navigating to a new page. The page is always the same but the error does not appear every time. I do not miss any characters on it, that's why I ask for this enhancement.

**Comment by darshankawar** [comment]
Check [this](https://github.com/flutter/flutter/issues/76093#issuecomment-780302785) issue comment and see if it helps.

**Comment by hlemcke** [comment]
I have tested this approach and did not enounter any further error messages so far. Nevertheless would it be helpful to have an error message with more information in it.

**Comment by darshankawar** [comment]
@hlemcke 
Can you provide us a minimal reproducible code sample that we can use which may trigger this message ? It will help us to analyze and address this issue in a better way.

**Comment by Uni2K** [comment]
I also encountered this issue while using the Chewie (https://pub.dev/packages/chewie) package in combination with Flutter web. It was sufficient to use the default implementation given on their site.

**Comment by eseidel** [comment]
I am able to trigger this console message in my app by enabling "showDebugPaint".  It does not trigger for me without that.

**Comment by eseidel** [comment]
Confirmed it reproduces with latest `dev` too:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.54.2)
[√] Connected device (2 available)
```
I'm using https://github.com/eseidel/pangram/commit/bb0fcfc6e09e36eae80c2b0b522f70b68ff8b6be and just turning on showDebugPaint.  I suspect the default counter app may also trigger this, but I haven't tried.
