### ISSUE TITLE
URL Launcher App Store Export Compliance

### ISSUE THREAD

**Issue by jamesnicholls04** [flutter/flutter#76218]
Hi - I'm using the url_launcher 5.7.10 package to link to a particular website hosting my privacy policy.

I was wondering whether, given that the link was 'https:...', I had to do anything about encryption export compliance?

https://help.apple.com/app-store-connect/#/dev88f5c7bf9

Would love any thoughts on this!

Thanks

**Comment by vukhacbiet** [comment]
Select "yes" 2 times in the Export compliance dialog (after create release version), and that's all you need.

**Comment by jamesnicholls04** [comment]
> Select "yes" 2 times in the Export compliance dialog (after create release version), and that's all you need.

Brilliant! Thank you :)

**Comment by darshankawar** [comment]
Seems your issue is resolved. Closing.
