### ISSUE TITLE
Regenerate Dart plugin registrant after a hot restart

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#76219]
The Dart plugin registrant is generated once the app is initially compiled.
There's a case where a user may start a `flutter run` session, then change the pubspec.yaml in the middle, and then hot restart the app.

With the changes from https://github.com/flutter/flutter/pull/74469, these steps will yield into an error. 

In the case the plugins were removed from pubpsec.yaml:
```
Error: Could not resolve the package 'url_launcher_linux' in 'package:url_launcher_linux/url_launcher_linux.dart'.
Error: Could not resolve the package 'url_launcher_macos' in 'package:url_launcher_macos/url_launcher_macos.dart'.
.dart_tool/flutter_build/generated_main.dart:9:8: Error: Not found: 'package:url_launcher_linux/url_launcher_linux.dart'
import 'package:url_launcher_linux/url_launcher_linux.dart';
       ^
.dart_tool/flutter_build/generated_main.dart:10:8: Error: Not found: 'package:url_launcher_macos/url_launcher_macos.dart'
import 'package:url_launcher_macos/url_launcher_macos.dart';
       ^
.dart_tool/flutter_build/generated_main.dart:15:7: Error: Getter not found: 'UrlLauncherPlugin'.
      UrlLauncherPlugin.registerWith();
      ^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/generated_main.dart:17:7: Error: Getter not found: 'UrlLauncherPlugin'.
      UrlLauncherPlugin.registerWith();
      ^^^^^^^^^^^^^^^^^
Performing hot restart...                                              ⣾Error: Could not resolve the package 'url_launcher_linux' in 'package:url_launcher_linux/url_launcher_linux.dart'.
Error: Could not resolve the package 'url_launcher_macos' in 'package:url_launcher_macos/url_launcher_macos.dart'.
.dart_tool/flutter_build/generated_main.dart:9:8: Error: Not found: 'package:url_launcher_linux/url_launcher_linux.dart'
import 'package:url_launcher_linux/url_launcher_linux.dart';
       ^
.dart_tool/flutter_build/generated_main.dart:10:8: Error: Not found: 'package:url_launcher_macos/url_launcher_macos.dart'
import 'package:url_launcher_macos/url_launcher_macos.dart';
       ^
.dart_tool/flutter_build/generated_main.dart:15:7: Error: Getter not found: 'UrlLauncherPlugin'.
      UrlLauncherPlugin.registerWith();
      ^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/generated_main.dart:17:7: Error: Getter not found: 'UrlLauncherPlugin'.
      UrlLauncherPlugin.registerWith();
```

**Comment by jonahwilliams** [comment]
Either hot reload or hot restart could require regeneration - but only if the pubspec.yaml has changed. See the localizations code for some examples of how to wire this up https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L912

**Comment by zanderso** [comment]
@blasten The beta branch cut is coming up very soon. What is the status of this?

**Comment by blasten** [comment]
@cyanglaz offered help. Thanks!  I will be OOO starting next week. 

From a very quick look, it would need to call [this function](https://github.com/flutter/flutter/blob/098ece522d41f25370d19f5ec09d93ce2e727019/packages/flutter_tools/lib/src/compile.dart#L247 ) from [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L1594) (Hot restart) if the pubpsec.yaml has changed since last time it was invoked.

**Comment by cyanglaz** [comment]
I'm confused about the expected result. Just want to confirm: 

If I remove some deps (say url_launcher), and do a hot reload/restart, I should see the error in the main description of this issue, correct? 

So what is the issue? Is the issue about error not showing?

**Comment by jonahwilliams** [comment]
> If I remove some deps (say url_launcher), and do a hot reload/restart, I should see the error in the main description of this issue, correct?

It should be possible to remove a plugin from the pubspec and hot reload or restart without a compilation error.

**Comment by cyanglaz** [comment]
I just tried with removing url_launcher in the middle of an app session, and run a hot restart, it seems fine, no error is generated. 

https://user-images.githubusercontent.com/3756895/110398294-6c5ccb80-8028-11eb-9859-6fdfe206bb5d.mov

**Comment by jonahwilliams** [comment]
If you removed url_launcher from your pubspec yaml in an example app that was using url_launcher you should get a compilation error - did pub get run and remove url_launcher from the package_config.json? You would also need to remove the usage from the app itself.

**Comment by cyanglaz** [comment]
I removed the url_launcher when the app is running, then hot restarted.
The hot start did not run `pub get`, which leads to no error.

**Comment by jonahwilliams** [comment]
The tool doesn't run pub for you on hot restart/reload

**Comment by cyanglaz** [comment]
talked to @blasten, I need to apply https://github.com/flutter/plugins/pull/3577 to reproduce the issue.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/79669
