### ISSUE TITLE
Functions in dart:io's network_policy.dart (such as isInsecureConnectionAllowed) are not available in the Flutter SDK but are in the VM at runtime

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#76228]
This could be deliberate, but it seems a bit strange. There's a function called `isInsecureConnectionAllowed` in the `dart:io` library when using the Dart SDK directly, but missing when using it via Flutter:

<img width="973" alt="Screenshot 2021-02-17 at 19 34 17" src="https://user-images.githubusercontent.com/1078012/108257788-3332e900-7157-11eb-8f33-d7dcbf2abb53.png">

The function is defined in the file `network_policy.dart` which does not appear in the `sky_engine` package inside Flutter, which means the analysis server doesn't discover it/can't navigate to it:

<img width="1011" alt="Screenshot 2021-02-17 at 18 01 05" src="https://user-images.githubusercontent.com/1078012/108247145-307dc700-714a-11eb-8063-c47a7f711ea7.png">

It seems like maybe this function isn't available, however if you step into the HttpClient class while debugging, the function actually _does_ exist in the VM (and the source code can be downloaded from the VM so you can step into it):

<img width="635" alt="Screenshot 2021-02-17 at 18 07 42" src="https://user-images.githubusercontent.com/1078012/108247851-185a7780-714b-11eb-8232-e740e53fd09f.png">

I don't know if this is a bug, but it is a little confusing when debugging - you can step into functions but can't use Go-to-Definition in the editor to get to them. (This originally came up at https://github.com/Dart-Code/Dart-Code/issues/3017).

**Comment by TahaTesser** [comment]
### Flutter analyze
<details>
<summary>logs</summary>

```bash
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm analyze
Analyzing master_flutter...                                             

   info • Unused import: 'dart:io' • lib/main.dart:1:8 • unused_import
  error • The function 'isInsecureConnectionAllowed' isn't defined •
         lib/main.dart:3:9 • undefined_function
   info • Unused import: 'package:triage/main.dart' • test/widget_test.dart:11:8
          • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 •
         undefined_function

4 issues found. (ran in 2.3s)
tahatesser@Tahas-MacBook-Pro master_flutter % 
```

</details>

### Dart analyze
<details>
<summary>logs</summary>

```bash
tahatesser@Tahas-MacBook-Pro dartdemo % dart analyze
Analyzing dartdemo...                  1.0s

   info • The value of the local variable 'a' isn't used at bin/dartdemo.dart:4:7 • (unused_local_variable)
          Try removing the variable, or using it.

1 issue found.
tahatesser@Tahas-MacBook-Pro dartdemo % 
```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.45, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.45 at /Users/tahatesser/Code/flutter_master
    • Framework revision 90531179f5 (35 minutes ago), 2021-02-17 23:21:02 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>


<details>
<summary>dart --version</summary>

```bash
tahatesser@Tahas-MacBook-Pro dartdemo % dart --version
Dart SDK version: 2.12.0-259.12.beta (beta) (Fri Feb 12 11:00:34 2021 +0100) on "macos_x64"
tahatesser@Tahas-MacBook-Pro dartdemo % 
```

</details>

**Comment by jonahwilliams** [comment]
We might be missing these sources in the sky-engine package, I'll take a look

**Comment by jonahwilliams** [comment]
The problem is network_policy.dart is missing from the io_sources.gni rule, so this file isn't getting copied into the right place:

https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/io_sources.gni

**Comment by DanTup** [comment]
@jonahwilliams Thanks! I don't know what that file is, but I've raised https://github.com/dart-lang/sdk/issues/45041 and added your findings to see if it can be fixed (or explained) there. Ty!
