### ISSUE TITLE
Non-standard colors in theme data throw an illusive exception

### ISSUE THREAD

**Issue by ShaseOfBase** [flutter/flutter#76220]
Setting primary color to something non-standard like below:

```
 theme: ThemeData(
          primaryColor: Colors.black54,
          accentColor: Colors.greenAccent,
          textTheme: TextTheme(bodyText2: TextStyle(color: Colors.white70))
      ), 

 causes this:
The following assertion was thrown building WidgetsApp-[GlobalObjectKey _MaterialAppState#c3710](dirty, state: _WidgetsAppState#77ca7):
'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.


```

**Comment by kashishkhullar** [comment]
`accentColor` is of type `Color` object
`Colors.greenAccent` return `MaterialAccentColor` object not `Color`

Its a type mismatch error. Change `Colors.greenAccent` to just `Colors.green` or use different shade `Colors.green[500]`

**Comment by darshankawar** [comment]
@ShaseOfBase 
Check above comment and possible solution to see if it works for you.

**Comment by ShaseOfBase** [comment]
Perfect, sorted, thanks guys.
