### ISSUE TITLE
Make analysis_options in flutter/plugins much stricter

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#76229]
Currently the flutter/plugins `analysis_options.yaml` is essentially just https://github.com/google/pedantic/blob/master/lib/analysis_options.1.8.0.yaml. Ideally we should be using all (or at the very least most) of the same options as flutter/flutter.

We'd need to figure out how to introduce these it a way that wouldn't be incredibly disruptive to all future incremental changes. Likely turning them on one by one in conjunction with repo-wide fixes for everything they turn up (one PR per lint option if there are widespread changes).

**Comment by stuartmorgan** [comment]
For anyone interested in contributing to this, the process is:
1. Pick a package in flutter/plugins that has a local `analysis_ootions.yaml` file.
2. Remove that file.
3. Run `dart fix --apply` in the package. (Often it needs to be run several times since some fixes create new warnings.)
4. Fix any remaining issues by hand.
5. Run `dartfmt` on any changed files.
6. Remove the exemption from `script/config/custom_analysis.yaml`

Each package should be its own PR, to make reviews easier.

**Comment by jmagman** [comment]
@stuartmorgan since you're marching through these, `pedantic` is now deprecated.  https://github.com/dart-lang/lints#migrating-from-packagepedantic

> Ideally we should be using all (or at the very least most) of the same options as flutter/flutter.

I believe this can be done via the [`flutter_lints`](https://pub.dev/packages/flutter_lints) package.

**Comment by stuartmorgan** [comment]
> @stuartmorgan since you're marching through these, `pedantic` is now deprecated. https://github.com/dart-lang/lints#migrating-from-packagepedantic

The new options that we're migrating to are a (slightly outdated now) copy of flutter/flutter's analysis options, which doesn't use `pedantic`, so once that's complete we'll be off of it.

> > Ideally we should be using all (or at the very least most) of the same options as flutter/flutter.
> 
> I believe this can be done via the [`flutter_lints`](https://pub.dev/packages/flutter_lints) package.

My original plan was to, once we'd done the initial work of getting aligned to the copy, see about moving flutter/flutter's options into a package we could share. Now that `flutter_lints` exists we should see how similar that is, since if it's close enough that would be an easier option. (AFAIK flutter/flutter doesn't actually use flutter_lints itself.)

**Comment by jmagman** [comment]
> Now that `flutter_lints` exists we should see how similar that is, since if it's close enough that would be an easier option. (AFAIK flutter/flutter doesn't actually use flutter_lints itself.)

If `flutter_lints` is intended to contain "a recommended set of lints for Flutter apps, packages, and plugins to encourage good coding practices" it may be more appropriate to use for the plugins repo than for Flutter itself (particularly the framework)

**Comment by stuartmorgan** [comment]
True; I'd like to see what the diffs are though. In general I suspect we're more conservative in what we put in a template, and more strict in what we enforce in our own code (which is a feature IMO). We could potentially do flutter_lints + local additions though.

**Comment by amanv8060** [comment]
@stuartmorgan this is labeled as "team", can I work for google_maps_flutter_web?

**Comment by stuartmorgan** [comment]
Anyone is welcome to send a PR to update a package to the new options.

**Comment by stuartmorgan** [comment]
The remaining work here is to uncomment the lines in the analysis options that are marked as locally disabled to fully synchronize us with the current state of flutter/flutter.

**Comment by stuartmorgan** [comment]
We also need to update
>    implicit-casts: false
>    implicit-dynamic: false

to
>    strict-casts: true
>    strict-raw-types: true

**Comment by stuartmorgan** [comment]
We're almost entirely aligned with flutter/flutter at this point, so I'm going to close this out. We'll continue to make incremental improvements over time, but we're past the point of needing the umbrella issue.
