### ISSUE TITLE
RawKeyboardListener key input triggering system sounds on MacOS

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#76242]
I am not sure if this is happening on other platforms but I am running on MacOs. I have a `RawKeyboardListener` widget listening for input to w-a-s-d keys. When any of those keys are pressed, a system sound plays. I'm not sure when this started happening, but this did not used to be the case. This does not happen on web.

**Comment by darshankawar** [comment]
Hi @kenzieschmoll 
Can you provide a minimal code sample that shows the issue along with `flutter doctor -v ?
Thanks.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/74287; see Greg's comment near the end for how to report keys as handled.
