### ISSUE TITLE
Add a microtask checkpoint between transient callback phase and build phase

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7626]
Tickers return Futures.
It's possible for the following sequence of events to happen:
 - a transient callback for a ticker results in that ticker's future completing
 - during build, we tear down the world
 - after the frame, the ticker's future's callbacks get called, expecting the world to still be around

This leads to people writing pretty-looking code that just doesn't work in edge cases that they won't think to test.

**Comment by Hixie** [comment]
We should maybe flush microtasks between the transient callbacks and the build phase?

@johnmccutchan is there any way to force the VM to flush microtasks synchronously?

**Comment by johnmccutchan** [comment]
@floitschG @rmacnak-google PTAL

**Comment by rmacnak-google** [comment]
The VM service internally uses DartLibraryCalls::DrainMicrotaskQueue(), which calls dart:isolate._runPendingImmediateCallback(). It's possible to invoke this from the embedding API, but it might be nicer to shuffle things around so dart:ui could give it a public facade.

**Comment by johnmccutchan** [comment]
Flutter's microtask queue is implemented in C++ ([dart_microtask_queue.h](https://github.com/fuchsia-mirror/tonic/blob/master/dart_microtask_queue.h)). `dart:ui` could get a new method e.g. `runMicrotasks` that is implemented by native code that just calls `DartMicrotaskQueue::RunMicrotasks`. @abarth probably knows about any reentrant call issues.

**Comment by abarth** [comment]
It's easy to add a microtask checkpoint there.  It's a bit of a slippery slope to adding lots of microtask checkpoints all over the place.  The web has them on every DOM mutation, for example.  We can take one step down the slide and see what happens next though.  😉

**Comment by Hixie** [comment]
Jason and I looked at this. Our theory is that the simplest way to solve this is to split onBeginFrame into onTick and onDrawFrame or some such, with a microtask checkpoint between the two.

**Comment by Hixie** [comment]
@jason-simmons Let me know if you need anything from me on this.
