### ISSUE TITLE
Refresh token missing on google_sign_in package

### ISSUE THREAD

**Issue by BoonJunTan** [flutter/flutter#76265]
Hey all, is there any way to retrieve refresh token from the flutter package: google_sign_in because it is not there in the credential. I also tried firebase authentication but the refresh token for user is also empty.

**Comment by darshankawar** [comment]
@BoonJunTan 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/15796
Please follow-up there for updates and for any questions.
Closing this as duplicate.
