### ISSUE TITLE
_debugCanPerformMutations sometimes shows in in cpu profiles of debug mode apps

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#76261]
For this profile running Flutter DevTools on Flutter DevTools (in debug mode) inspecting the Flutter Gallery
debugCanPerformMutations takes over 100ms over the course of click on and scrolling the inspector tree a bit.
It would be nice to be able to toggle off these checks or optimize them when trying to use a debug build to iterate on an app instead of to debug.
https://github.com/flutter/flutter/blob/efe8a397a800bf7550e7a37ae8bd8aeaf29a88a6/packages/flutter/lib/src/rendering/object.dart#L1369

Devtools cpu profiler snapshot file.  Remove the .txt to load in Flutter Devtools.
[dart_devtools_2021_2_17-1613612140883000.json.txt](https://github.com/flutter/flutter/files/5999646/dart_devtools_2021_2_17-1613612140883000.json.txt)

**Comment by jonahwilliams** [comment]
That method is also either documented wrong or implemented incorrectly, it says it returns null outside of debug mode but due to the use of late calling in release/profile will actually throw a LateInitializationException

**Comment by Hixie** [comment]
@jonahwilliams Probably just a null safety migration oversight, we should indeed fix that (either docs or implementation, doesn't really matter).
