### ISSUE TITLE
[Espresso Android] How to find element on Flutter screen in Android Instrument Testing

### ISSUE THREAD

**Issue by TBoonkwan** [flutter/flutter#76284]
I have integrated Flutter module to existing native app. Then we need to assert some element when the Flutter screen is showing on android instrument testing [espresso framework]

I already added these framework but that's not working fine
- Flutter driver
- Flutter espresso

I got some error when assert element --> **Flutter testing APIs not registered with Dart isolate.** onFlutterWidget(withValueKey("waiting_order_label")).check(matches(FlutterMatchers.withText("please wait...")))

**Comment by darshankawar** [comment]
@TBoonkwan 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that has the test setup ?

Does your Flutter module to existing Android native app tries to call platform channel from another isolate ? If so, then then check this open issue, https://github.com/flutter/flutter/issues/13937. which may be limiting your testing scope and cause of the error you are getting `Flutter testing APIs not registered with Dart isolate.`

If not, then have you looked at integration_testing [plugin](https://pub.dev/packages/integration_test/install) which is now preferred way to writing integration tests  and see if using it in your test setup helps ?

**Comment by TBoonkwan** [comment]
> @TBoonkwan
> Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that has the test setup ?
> 
> Does your Flutter module to existing Android native app tries to call platform channel from another isolate ? If so, then then check this open issue, #13937. which may be limiting your testing scope and cause of the error you are getting `Flutter testing APIs not registered with Dart isolate.`
> 
> If not, then have you looked at integration_testing [plugin](https://pub.dev/packages/integration_test/install) which is now preferred way to writing integration tests and see if using it in your test setup helps ?

Thanks, I will try integration_testing to flutter module and existing android app with espresso and flutter driver

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
