### ISSUE TITLE
Avoid microfone permissions

### ISSUE THREAD

**Issue by marcodecarolisidt** [flutter/flutter#76290]
## Use case

To use this package [image_picker](https://pub.dev/packages/image_picker) the user has to give the microphone's permission 

## Proposal

Is it possible to use it without asking to use the microphone, and therefore not using this feature?

**Comment by iapicca** [comment]
> To use this plugin in the user has to give the microphone's permission

@marcodecarolisidt what plugin?

**Comment by marcodecarolisidt** [comment]
Sowwy the 

> > To use this plugin in the user has to give the microphone's permission
> 
> @marcodecarolisidt what plugin?

Sorry I updated the description
