### ISSUE TITLE
OnFieldsubmitted event is not working in textformfield

### ISSUE THREAD

**Issue by jackselvam** [flutter/flutter#76293]
Hi, I'm using latest master version for the flutter. In windows, textformfield onfieldsubmitted event is not firing. pls check this issue

**Comment by darshankawar** [comment]
@jackselvam 
Can you provide `flutter doctor -v` and a minimal complete reproducible code sample ? Also, by windows, you mean desktop platform on windows ?

**Comment by shanu5544** [comment]
@jackselvam I think OnFieldsubmitted isn't any callback available on TextField. Here is sample which is working on even windows as well as android.
![image](https://user-images.githubusercontent.com/44698417/108394677-fa6c4000-723a-11eb-9752-f32abfa29445.png)

**Comment by jackselvam** [comment]
when i press enter key in the keyboard, the onfieldsubmitted event is not firing

![image](https://user-images.githubusercontent.com/35285298/108441553-5ce53080-727b-11eb-808c-359bc2df767c.png)

@shanu5544 i'm using textformfield not textfield.
@darshankawar i mean windows desktop only


[√] Flutter (Channel master, 1.27.0-5.0.pre.67, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-5.0.pre.67 at D:\SW\flutter_master\flutter
    • Framework revision 934dfde42f (43 minutes ago), 2021-02-18 19:16:03 -0500
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\SW\sdk-tools-windows-4333796
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0 Preview 4.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.9.31004.235
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Jack Selvam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 2 categories.

**Comment by jackselvam** [comment]
i found the root cause, i placed textformfield inside ListTile that's why onfieldsubmitted event is not fired, same code it was working after migrating flutter master latest version this issue happened
