### ISSUE TITLE
SignInWithEmailAndPassword freezes the app

### ISSUE THREAD

**Issue by fede-da** [flutter/flutter#76296]
I already asked on StackOverflow but didn't resolve this issue.
When calling Firebase services to sign in a user with `signInWithEmailAndPassword` if the user isn't registered the app crashes. What I want is just to catch this error and show a window dialogue, telling the user what to do.
I already inserted many case to check the error, I don't know what I'm missing.

This is the code : 

```
`Future<void> submit(
      context, FirebaseAuth authF, String email, String password) async {
    try {
      UserCredential userCredential =
          await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
    } catch (e) {
      print(e.code);
      switch (e.code) {
        case 'ERROR_INVALID_EMAIL':
          showErrDialog(context, e.code);
          break;
        case 'ERROR_WRONG_PASSWORD':
          showErrDialog(context, e.code);
          break;
        case 'ERROR_USER_NOT_FOUND':
          showErrDialog(context, e.code);
          break;
        case 'ERROR_USER_DISABLED':
          showErrDialog(context, e.code);
          break;
        case 'ERROR_TOO_MANY_REQUESTS':
          showErrDialog(context, e.code);
          break;
        case 'ERROR_OPERATION_NOT_ALLOWED':
          showErrDialog(context, e.code);
          break;
      }
    }
  }

  Future<void> _submit(Auth auth, FirebaseAuth authF) async {
    //Create Artist and send it to the database
    if (_validateAndSaveForm()) {
      try {
        await submit(context, authF, emailF, password);
        navigateToHome(context);
        //submit(context, authF, emailF, password);
        //Dovrebbe andare in home page ma per ora va bene così
      } catch (e) {
        if (Platform.isIOS) {
          logInCupertinoDialogue(context, e);
        } else {
          logInAndroidDialogue(context, e);
        }
      }
    }
  }`

```

**Comment by iapicca** [comment]
@fede-da 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by fede-da** [comment]
> @fede-da
> [firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
> or provide your `flutter doctor -v`, your `flutter run -v`
> and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

Ok I'll ask in Firebase section, thanks!

**Comment by darshankawar** [comment]
@fede-da 
Not sure if you reopened it by accident. Closing from here based on your comment above. If you think your issue is related to Flutter framework, provide requested details to properly address your issue.
