### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by fstag** [flutter/flutter#76302]
I am getting below error while trying to archive (build) the flutter application in Xcode for generic application.

I've read the other threads related to this issue but none of the suggested solutions worked for me.

This is the flutter doctor -v output

>  [✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-arm, locale en-IT)
>     • Flutter version 1.27.0-4.0.pre at /Users/francesca/development/flutter
>     • Framework revision f8cd24de95 (2 days ago), 2021-02-16 11:24:17 -0800
>     • Engine revision 1d537824d6
>     • Dart version 2.13.0 (build 2.13.0-30.0.dev)
> 
> [✓]` Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> 
>     • Android SDK at /Users/francesca/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] Connected device (2 available)
>     • iPad Air (4th generation) (mobile) • 14443ABB-109D-419F-82A7-0DF14A89A861 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
>     • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 88.0.4324.182
> 
> • No issues found!
> 

The logs when I try to build from the terminal
[build_ios_verbose.log](https://github.com/flutter/flutter/files/6002598/build_ios_verbose.log)

The logs when I use xcode
[build_xcode.log](https://github.com/flutter/flutter/files/6002602/build_xcode.log)

pubspec.yaml
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/6003011/pubspec.yaml.txt)

Thanks

**Comment by darshankawar** [comment]
@fstag 
The error you are getting `Command PhaseScriptExecution failed` could be due to many reasons, so it's hard to pinpoint exact cause of your issue.
Can you confirm your `podfile` is in sync with all the plugins and they are up-to-date ? 
Did it work before or you made any changes / updates that led to this error ?
Can you also try to switch to latest master or beta and see if you get similar error ?

**Comment by fstag** [comment]
I can confirm that the podfile are synced with all the plugins and it was working before.

By switching to the beta channel I have the same message but with more details, that I guess are the ones that trigger the error

[Build target Runner_2021-02-18T17-49-51.txt](https://github.com/flutter/flutter/files/6004495/Build.target.Runner_2021-02-18T17-49-51.txt)

Thanks

**Comment by darshankawar** [comment]
@fstag 
Thanks for providing updated logs. There's similar open issue describing your case, https://github.com/flutter/flutter/issues/75167.
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by MuhammadUmairMoosani** [comment]
Facing the same issue on Xcode 12.4 React Native 0.64.2 Macos Catalina 10.15.7

Solution work for me:

https://github.com/facebook/react-native/issues/31181#issuecomment-802155250

Remove NVM https://github.com/nvm-sh/nvm/issues/298#issuecomment-30618281

**Comment by hkodes** [comment]
Easy way to Fix this:

1.Go to Menu System Preferences -> Security & Privacy.
2.Choose the Privacy Tab.
3.Select Full Disk Access item in left list.
4.Select Xcode in right list.
