### ISSUE TITLE
Re-add flutter/cocoon to flutter/tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#76334]
https://github.com/flutter/flutter/pull/76329 included breaking change to Cocoon's goldens. Since the diff was <0.03%, we're disabling to unblock the rolls.

After the roll has landed, we can update Cocoon's goldens and re-add it to flutter/tests

**Comment by CaseyHillers** [comment]
@gw280 with the engine roll landed, can we re-add cocoon?

**Comment by CaseyHillers** [comment]
\cc @jason-simmons @zanderso as Cocoon was removed again in https://github.com/flutter/tests/pull/81

Is there an ETA for when it will get re-added?

**Comment by zanderso** [comment]
Looks like it should be good to re-enable since the golden updates landed https://github.com/flutter/cocoon/pull/1097

**Comment by zanderso** [comment]
https://github.com/flutter/tests/pull/82
