### ISSUE TITLE
testFullScreenColdPop potentially flaky

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#76332]
failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/1726/overview
log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8854927186930278272/+/steps/run_module_test_ios/0/stdout

```
[module_test_ios] [STDOUT] stdout: /opt/s/w/ir/tmp/t/flutter_module_test.jZEA0k/hello_host_app/FlutterUITests/FlutterUITests.m:24: error: -[FlutterUITests testFullScreenColdPop] : (([app.staticTexts[@"Button tapped 1 time."] waitForExistenceWithTimeout:60.0]) is true) failed
[module_test_ios] [STDOUT] stdout:     t =    65.58s Tear Down
[module_test_ios] [STDOUT] stdout: Test Case '-[FlutterUITests testFullScreenColdPop]' failed (65.780 seconds).
```

It seems we've seen this kind of timeout before: https://github.com/flutter/flutter/issues/70630 
 /cc @jmagman

**Comment by LongCatIsLooong** [comment]
`-[FlutterUITests testDualCold]` had a similar failure:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8855009944721676608/+/steps/run_module_test_ios/0/stdout

**Comment by jmagman** [comment]
Boo, the test logs didn't upload.  https://github.com/flutter/flutter/pull/76341

**Comment by jmagman** [comment]
#76341 is merged, hopefully get the the test logs next time.

**Comment by jmagman** [comment]
This hasn't failed in the last 200 runs.  Let's close, and if we see it again at least we have more logs.
