### ISSUE TITLE
Windows web_tool_tests failing consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76360]
Logs:

https://ci.chromium.org/p/flutter/builders/prod/Windows%20web_tool_tests

Should we remove this test?

**Comment by godofredoc** [comment]
\cc @jmagman @jonahwilliams

**Comment by jmagman** [comment]
@annagrin @jonahwilliams I can't find an issue tracking that these tests never passed, but I know we talked about it.
```
15:12 +0 ~1 -1: test\web.shard\expression_evaluation_web_test.dart: flutter run expression evaluation - error if expression evaluation disabled [E]                                                    
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```
https://github.com/flutter/flutter/issues/69711

Is it worth skipping just that test while it's investigated to get coverage from the rest of the tests?

**Comment by jonahwilliams** [comment]
Lets disable the single failing test and keep the shard running. Do we know when these started failing?

**Comment by godofredoc** [comment]
They have never passed on windows.

**Comment by jonahwilliams** [comment]
right, I think this is something we might have dropped during the holidays. I can send a PR to skip the failing test so we can get coverage for the rest

**Comment by annagrin** [comment]
We had some infra problems on windows preventing those tests before, but if this the only one failing it means a real failure. I will look into it later and enable back on when fixed.

**Comment by jmagman** [comment]
@annagrin
> if this the only one failing it means a real failure. I will look into it later and enable back on when fixed.

They are all failing as far as I know. [I kept skipping them and the next one would time out.](https://github.com/flutter/flutter/pull/76399)  
See 
https://github.com/flutter/flutter/issues/76398
https://github.com/flutter/flutter/issues/76421

**Comment by Hixie** [comment]
I'm bumping the priority since this is costing us cycles for no value, and we could be spending the cycles on tests that are useful.

**Comment by Hixie** [comment]
cc @yjbanov since these are web tests, dunno if you're the right contact

**Comment by annagrin** [comment]
I got my windows laptop so I can try the tests themselves (not the infra) after some initial setup.

**Comment by jmagman** [comment]
@annagrin you can run just this via:
```
$ cd packages/flutter_tools
$ flutter test test\web.shard
```

**Comment by yjbanov** [comment]
Are all tests failing on Windows or only some of them? If it's only some of them, can we skip just those? Running tool tests on Windows seems useful.
